RETURN
by Lawrence Kasdan
George Lucas
From The Novel by George Lucas
Third Draft
Property of Lucasfilm Ltd.
Completion Date December 1, 1981
The boundless heavens serve as a back-drop for the MAIN TITLE, followed by a ROLL-UP, which crawls into infinity.
Episode VI
Luke Skywalker has returned to his home planet of Tatooine in an attempt to rescue his friend Han Solo from the clutches of theEvile gangster Jabba the Hutt.
Little does Luke know that the GALACTIC EMPIRE has secretly begun construction on a new armored space station even more powerful than the first dreaded Death Star.
When completed, this ultimate weapon will spell certain doom for the small band of Rebels struggling to restore freedom to the galaxy...
PAN DOWN to reveal a monstrous half-completed Death Star, its massive superstructure curling away from the completed section like the arms of a giant octopus.
Beyond, in benevolent contrast, floats the small, green moon of ENDOR.
An Imperial Star Destroyer moves overhead toward the massive armored space station, followed by two zipping TIE fighters.
A small Imperial shuttle rockets from the main bay of the ship and hustles toward the Death Star.
The shuttle captain makes contact with the Death Star.
SHUTTLE CAPTAIN Command station, this is ST 321.
SHUTTLE CAPTAIN Code Clearance Blue.
SHUTTLE CAPTAIN We're starting our approach.
SHUTTLE CAPTAIN Deactivate the security shield.
SHUTTLE CAPTAIN You are clear to proceed.
SHUTTLE CAPTAIN We're starting our approach.
Operators move about among the control panels.
A SHIELD OPERATOR hits switches beside a large screen, on which is a display of the Death Star, the moon Endor, and a bright web delineating the invisible deflector shield.
A control officer rushes over to the shield operator.
Inform the commander that Lord Vader's shuttle has arrived.
Yes, sir.
The control officer moves to a view port and watches as the Imperial shuttle lands in the massive docking bay.
A squad of Imperial stormtroopers moves into formation before the craft.
The DEATH STAR COMMANDER, MOFF JERJERROD, a tall, confident technocrat, strides through the assembled troops to the base of the shuttle ramp.
The troops snap to attention; many are uneasy about the new arrival.
But the Death Star commander stands arrogantly tall.
The exit hatch of the shuttle opens with a WHOOSH, revealing only darkness.
Then, heavy FOOTSTEPS AND MECHANICAL BREATHING.
From this black void appears DARTH VADER, LORD OF THE SITH.
Vader looks over the assemblage as he walks down the ramp.
JERJERROD Lord Vader, this is an unexpected pleasure.
JERJERROD We're honored by your presence.
VADER You may dispense with the pleasantries, Commander.
VADER I'm here to put you back on schedule.
The commander turns ashen and begins to shake.
JERJERROD I assure you, Lord Vader, my men are working as fast as they can.
VADER Perhaps I can find new ways to motivate them.
JERJERROD I tell you, this station will be operational as planned.
VADER The Emperor does not share your optimistic appraisal of the situation.
JERJERROD But he asks the impossible.
JERJERROD I need more men.
VADER Then perhaps you can tell him when he arrives.
JERJERROD (aghast) The Emperor's coming here?
VADER That is correct, Commander.
VADER And he is most displeased with your apparent lack of progress.
JERJERROD We shall double our efforts.
VADER I hope so, Commander, for your sake.
VADER The Emperor is not as forgiving as I am.
A lonely, windswept road meanders through the desolate Tatooine terrain.
We HEAR a familiar BEEPING and a distinctive reply before catching sight of ARTOO-DETOO and SEE-THREEPIO, making their way along the road toward the ominous palace of Jabba the Hutt.
THREEPIO Of course I'm worried.
THREEPIO And you should be, too.
THREEPIO Lando Calrissian and poor Chewbacca never returned from this awful place.
Artoo whistles timidly.
THREEPIO Don't be so sure.
THREEPIO If I told you half the things I've heard about this Jabba the Hutt, you'd probably short-circuit.
The two droids fearfully approach the massive gate to the palace.
THREEPIO Artoo, are you sure this is the right place?
THREEPIO I better knock, I suppose.
Threepio looks around for some kind of signaling device, then timidly knocks on the iron door.
THREEPIO (instantly) There doesn't seem to be anyone there.
Let's go back and tell Master Luke.
A small hatch in the middle of the door opens and a spidery mechanical arm, with a large electronic eyeball on the end, pops out and inspects the two droids.
Tee chuta hhat yudd!
THREEPIO Goodness gracious me!
Threepio points to Artoo, then to himself.
THREEPIO Artoo Detoowha bo Seethreepiowha ey toota odd mischka Jabba du Hutt.
The eye looks from one robot to the other, there is a laugh then the eye zips back into the door.
The hatch slams shut.
Artoo beeps his concern.
THREEPIO I don't think they're going to let us in, Artoo.
THREEPIO We'd better go.
THREEPIO Artoo starts forward into the gloom.
THREEPIO Threepio rushes after his stubby companion.
THREEPIO The door lowers noisily behind them.
THREEPIO Artoo, wait.
THREEPIO Oh, dear!
THREEPIO Artoo.
THREEPIO Artoo, I really don't think we should rush into all this.
Artoo continues down the corridor, with Threepio following.
THREEPIO Oh, Artoo!
THREEPIO Artoo, wait for me!
The door slams shut with a loud crash that echoes throughout the dark passageway.
The frightened robots are met by two giant, green GAMORREAN GUARDS, who fall in behind them.
Threepio glances quickly back at the two lumbering brutes, then back to Artoo.
One guard grunts an order.
Artoo beeps nervously.
THREEPIO Just you deliver Master Luke's message and get us out of here.
THREEPIO Oh my!
THREEPIO Oh!
THREEPIO Oh, no.
Walking toward them out of the darkness is BIB FORTUNA, a humanlike alien with long tentacles protruding from his skull.
BIB Die Wanna Wanga!
THREEPIO Oh, my!
THREEPIO Die Wanna Wauaga.
THREEPIO We -- we bring a message to your master, Jabba the Hutt.
THREEPIO THREEPIO (cont) ...and a gift.
THREEPIO Gift, what gift?
Bib shakes his head negatively.
BIB Nee Jabba no badda.
BIB Me chaade su goodie.
Bib holds out his hand toward Artoo and the tiny droid backs up a bit, letting out a protesting array of squeaks.
Threepio turns to the strange-looking alien.
THREEPIO He says that our instructions are to give it only to Jabba himself.
Bib thinks about this for a moment.
THREEPIO I'm terribly sorry.
THREEPIO I'm afraid he's ever so stubborn about these sort of things.
Bib gestures for the droids to follow.
BIB Nudd Chaa.
The droids follow the tall, tentacled alien into the darkness, trailed by the two guards.
THREEPIO Artoo, I have a bad feeling about this.
The throne room is filled with the vilest, most grotesque CREATURES ever conceived in the universe.
Artoo and Threepio seem very small as they pause in the doorway to the dimly lit chamber.
Light shafts partially illuminate the drunken courtiers as Bib Fortuna crosses the room to the platform upon which rests the leader of this nauseating crowd: JABBA THE HUTT.
The monarch of the galactic underworld is a repulsive blob of bloated fat with a maniacal grin.
Chained to the horrible creature is the beautiful alien female dancer named OOLA.
At the foot of the dais sits an obnoxious birdlike creature, SALACIOUS CRUMB.
Bib whispers something in the slobbering degenerate's ear.
Jabba laughs horribly, at the two terrified droids before him.
Threepio bows politely.
THREEPIO Good morning.
JABBA Bo Shuda!
The robots jump forward to stand before the repulsive, loose-skinned villain.
THREEPIO The message, Artoo, the message.
Artoo whistles, and a beam of light projects from his domed head, creating a hologram of LUKE on the floor.
The image grows to over ten feet tall, and the young Jedi towers over the space gangsters.
LUKE Greetings, Exalted One.
LUKE Allow me to introduce myself.
LUKE I am Luke Skywalker, Jedi Knight and friend to Captain Solo.
LUKE I know that you are powerful, mighty Jabba, and that your anger with Solo must be equally powerful.
LUKE I seek an audience with Your Greatness to bargain for Solo's life.
LUKE With your wisdom, I'm sure that we can work out an arrangement which will be mutually beneficial and enable us to avoid any unpleasant
confrontation.
As a token of my goodwill, I present to you a gift: these two droids.
Threepio is startled by this announcement.
THREEPIO What did he say?
THREEPIO Both are hardworking and will serve you well.
THREEPIO This can't be!
THREEPIO Artoo, you're playing the wrong message.
THREEPIO Jabba laughs while Bib speaks to him in Huttese.
JABBA (in Huttese subtitled) There will be no bargain.
THREEPIO We're doomed.
THREEPIO JABBA (in Huttese subtitled) I will not give up my favorite decoration.
THREEPIO I like Captain Solo where he is.
THREEPIO Jabba laughs hideously and looks toward an alcove beside the throne.
THREEPIO Hanging high, flat against the wall, exactly as we saw him last, is a carbonized HAN SOLO.
THREEPIO Artoo, look!
THREEPIO Captain Solo.
THREEPIO And he's still frozen in carbonite.
One of Jabba's Gamorrean guards marches Artoo and Threepio down a dank, shadowy passageway lined with holding cells.
The cries of unspeakable creatures bounce off the cold stone walls.
Occasionally a repulsive arm or tentacle grabs through the bars at the hapless droids.
Artoo beeps pitifully.
THREEPIO What could possibly have come over Master Luke.
THREEPIO Is it something I did?
THREEPIO He never expressed any unhappiness with my work.
THREEPIO Oh!
THREEPIO Oh!
THREEPIO Hold it!
THREEPIO Ohh!
A large tentacle wraps around Threepio's neck.
He manages to break free, and they move on to a door at the end of the corridor.
The door slides open, revealing a room filled with steam and noisy machinery.
The guard motions them into the boiler room, where they are met by a tall, thin humanlike robot named EV-9D9.
Behind the robot can be seen a torture rack pulling the legs off a screaming baby work droid.
A second power droid is upside down.
As smoking branding irons are pressed into his feet, the stubby robot lets out an agonized electronic scream.
Artoo and Threepio cringe as the guard grunts to EV-
NINEDENINE Ah, good.
NINEDENINE New acquisitions.
NINEDENINE You are a protocol droid, are you not?
THREEPIO I am See-Threepio, human-cy...
NINEDENINE Yes or no will do.
THREEPIO Oh.
THREEPIO Well, yes.
NINEDENINE How many languages do you speak?
THREEPIO I am fluent in over six million forms of communication, and can readily...
NINEDENINE Splendid!
NINEDENINE We have been without an interpreter since our master got angry with our last protocol droid and disintegrated him.
THREEPIO Disintegrated?
THREEPIO The guard shoves Threepio toward the door.
THREEPIO Artoo lets out a plaintive cry as the door closes.
THREEPIO Then he beeps angrily.
NINEDENINE You're a feisty little one, but you'll soon learn some respect.
NINEDENINE I have need for you on the master's Sail Barge.
NINEDENINE And I think you'll fit in nicely.
The poor work droid in the background lets out another tortured electronic scream.
The court of Jabba the Hutt is in the midst of a drunken, raucous party.
Sloppy, smelly monsters cheer and make rude noises as Oola and a fat female dancer perform in front of Jabba's throne.
Jabba leers at the dancers and with a lustful gleam in his eye beckons Oola to come and sit with him.
She stops dancing and backs away, shaking her head.
Jabba gets angry and points to a spot next to him.
JABBA Da Eitha!
The lovely alien shakes her head again and screams.
Na Chuba negatorie Na!
Na!
Natoota...
Jabba is furious and pulls her toward him, tugging on the chain.
JABBA Boscka!
JABBA Threepio cringes and glances wistfully at the carbonite form of Han Solo, but is immediately distracted by a gunshot offscreen.EAn unnatural quiet sweeps the boisterous gathering.
JABBA On the far side of the room, the crush of debauchers moves aside to allow the approach of two guards followed by BOUSHH, an oddly cloaked bounty hunter, leading his captive, Han Solo's copilot, CHEWBACCA THE WOOKIEE.
JABBA BOUSHH (in Ubese subtitled) I have come for the bounty on this Wookiee.
THREEPIO Oh, no!
THREEPIO Chewbacca!
THREEPIO Jabba lets out a loud, long, blood-curdling laugh and turns to Threepio, waving him closer.
THREEPIO The reluctant droid obeys.
THREEPIO Oh, uh, yes, uh, I am here, Your Worshipfulness.
THREEPIO Uh...
THREEPIO yes!
Jabba continues speaking, as Threepio nervously translates.
Boushh listens, studying the dangerous creatures around the room.
He notices BOBA FETT standing near the door.
THREEPIO Oh.
THREEPIO The illustrious Jabba bids you welcome and will gladly pay you the reward of twenty-five thousand.
THREEPIO BOUSHH (in Ubese subtitled) I want fifty thousand.
THREEPIO Jabba immediately flies into a rage, knocking the golden droid off the raised throne into a clattering heap on the floor.
THREEPIO Boushh adjusts his weapon as Jabba raves in Huttese and Threepio struggles back onto the throne.
THREEPIO The disheveled droid tries to compose himself.
THREEPIO Uh, oh...
THREEPIO but what, what did I say?
THREEPIO Uh, the mighty Jabba asks why he must pay fifty thousand.
The bounty hunter holds up a small silver ball in his hand.
Threepio looks at it, then looks at Jabba, then back to the bounty hunter.
The droid is very nervous and Jabba is getting very impatient.
THREEPIO Because he's holding a thermal detonator.
THREEPIO JABBA (in Huttese subtitled) This bounty hunter is my kind of scum.
THREEPIO Fearless and inventive.
Jabba continues.
THREEPIO Jabba offers the sum of thirty-five.
THREEPIO And I suggest you take it.
Bib and the other monsters study the bounty hunter and wait for his reaction.
Boushh releases a switch on the thermal detonator and it goes dead.
BOUSHH Zeebuss.
THREEPIO He agrees!
THREEPIO Boushh leans against a column with gunfighter cool and surveys the scene, his gaze stopping only when it connects with a glare from across the room.
THREEPIO Boba Fett is watching him.
THREEPIO Boushh shifts slightly, cradling his weapon lovingly.
THREEPIO Boba Fett shifts with equally ominous arrogance.
Gamorrean guards lead Chewie down the same hallway we saw before.
When a tentacle reaches out at the Wookiee, Chewie's ferocious ROAR echoes against the walls and the tentacle snaps back into its cell in terror.
It takes all the guards to hurl Chewie roughly into a cell, slamming the door behind him.
Chewie lets out a pathetic howl and bangs on the iron door.
The palace is sitting in the light of the double sunset.
On the road in front, a large toadlike creature flicks its tongue out for a desert rodent and burps in satisfaction.
Silence.
The room is deserted, only the awful debris of the alien celebration giving mute witness to the activity here before.
Several drunk creatures lie unconscious around the room, snoring loudly.
A shadowy figure moves stealthily among the columns at the perimeter of the room and is revealed to be Boushh, the bounty hunter.
He picks his way carefully through the snoring, drunken monsters.
Han Solo, the frozen space pirate, hangs spotlighted on the wall, his coffin-like case suspended by a force field.
The bounty hunter deactivates the force field by flipping a control switch to one side of the coffin.
The heavy case slowly lowers to the floor of the alcove.
Boushh steps up to the case, studying Han, and then turns to the controls on the side of the coffin.
He activates a series of switches and, after one last hesitant look at Han, slides the de-carbonization lever.
The case begins to emit a sound as the hard shell covering the contours of Han's face begins to melt away.
The bounty hunter watches as Han's body is freed of its metallic coat and his forearms and hands, previously raised in reflexive protest, drop slackly to his side.
His face muscles relax from their mask of horror.
He appears quite dead.
Boushh's ugly helmet leans close to Han's face listening for the breath of life.
Nothing.
He waits.
Han's eyes pop open with a start and he begins coughing.
The bounty hunter steadies the staggering newborn.
BOUSHH Just relax for a moment.
BOUSHH You're free of the carbonite.
Han touches his face with his hand and moans.
BOUSHH Shhh.
BOUSHH You have hibernation sickness.
HAN I can't see.
BOUSHH Your eyesight will return in time.
HAN Where am I?
BOUSHH Jabba's palace.
HAN Who are you?
The bounty hunter reaches up and lifts the helmet from his head, revealing the beautiful face of PRINCESS LEIA.
LEIA Someone who loves you.
HAN Leia!
LEIA I gotta get you out of here.
As Leia helps her weakened lover to stand up, the relative quiet is pierced by an obscene HUTTESE CACKLE from the other side of the alcove.
HAN What's that?
HAN I know that laugh.
The curtain on the far side of the alcove opens, revealing Jabba the Hutt, surrounded by Bib and other aliens.
He laughs again, and his gross cronies join in a cacophony of alien glee.
HAN Hey, Jabba.
HAN Look, Jabba, I was just on my way to pay you back, but I got a little sidetracked.
HAN It's not my fault.
HAN JABBA (in Huttese subtitled) It's too late for that, Solo.
HAN You may have been a good smuggler, but now you're Bantha fodder.
HAN Look...
HAN The guards grab Han and start to lead him away.
HAN Jabba...
HAN I'll pay you triple!
HAN You're throwing away a fortune here.
HAN Don't be a fool!
HAN JABBA (in Huttese subtitled) Bring her to me.
Jabba chuckles as Lando and a second guard drag the beautiful young princess toward him.
Threepio peeks from behind a monster and quickly turns away in disgust.
LEIA We have powerful friends.
LEIA You're gonna regret this...
LEIA JABBA (in Huttese subtitled) I'm sure.
LEIA Inexorably her lovely face moves to within a few inches of Jabba's ugly blob of a head, and Leia turns away in disgust.
LEIA Ugh!
THREEPIO Ohhh, I can't bear to watch.
The heavy metal door of the dungeon whines and slowly creaks open.
A guard throws the blinded star captain into the dark cell and the door slams shut behind him, leaving only a thin sliver of light from a crack in the door.
Han is trying to collect himself when suddenly a growl is heard from the far side of the cell.
He jumps back against the cell door and listens.
HAN Chewie?
HAN Chewie, is that you?
The shadowy figure lets out a crazy yell and races toward Han, lifting him off the ground with a big hug that carries them into the light, revealing Chewie.
HAN Ah!
HAN Chew--Chewie!
The giant Wookiee barks with glee.
HAN Wait.
HAN I can't see, pal.
HAN What's goin' on?
Chewie barks an excited blue streak.
HAN Luke?
HAN Luke's crazy.
HAN He can't even take care of himself, much less rescue anybody.
Chewie barks a reply.
HAN A...Jedi Knight?
HAN I--I'm out of it for a little while, everybody gets delusions of grandeur.
Chewie growls insistently.
He holds Han to his chest and pets his head.
HAN I'm all right, pal.
HAN I'm all right.
Noisily, the main gate lifts to flood the blackness with blinding LIGHT and reveal the silhouetted figure of LUKE SKYWALKER.
He is clad in a robe similar to Ben's and wears neither pistol nor laser sword.
Luke strides purposefully into the hallway.
Two giant guards move to block Luke's path.
Luke halts.
Luke raises his hand and points at the puzzled guards, who immediately lower their spears and fall back.
The young Jedi lowers his hand and moves on down the hallway.
Bib Fortuna appears out of the gloom.
He speaks to Luke as they approach each other, but Luke doesn't stop and Bib must reverse his direction and hurry alongside the young Jedi in order to carry on the conversation.
Several other guards fall in behind them in the darkness.
LUKE I must speak with Jabba.
Bib answers in Huttese, shaking his head in denial.
Luke stops and stares at Bib; he raises his hand slightly.
LUKE You will take me to Jabba now!
Bib turns in hypnotic response to Luke's command, and Luke follows him into the gloom.
LUKE You serve your master well.
Bib responds.
LUKE And you will be rewarded.
Jabba is asleep on his throne, with Leia lying in front of him.
Salacious sits by Jabba's tail, watching it wriggle.
Leia is now dressed in the skimpy costume of a dancing girl; a chain runs from a manacle/necklace at her throat to her new master, Jabba the Hutt.
Threepio stands behind Jabba as Bib comes up to the gangster slug.
THREEPIO At last!
THREEPIO Master Luke's come to rescue me.
BIB Master.
Jabba awakens with a start and Bib continues, in Huttese.
BIB ...Luke Skywalker, Jedi Knight.
BIB JABBA (in Huttese subtitled) I told you not to admit him.
LUKE I must be allowed to speak.
LUKE Jabba, furious, clobbers Bib and shoves him away.
LUKE JABBA (in Huttese subtitled) You weak-minded fool!
LUKE Luke stares hard at Jabba.
LUKE You will bring Captain Solo and the Wookiee to me.
JABBA (in Huttese subtitled) Your mind powers will not work on me, boy.
LUKE Nevertheless, I'm taking Captain Solo and his friends.
LUKE You can either profit by this...
LUKE or be destroyed!
LUKE It's your choice.
LUKE But I warn you not to underestimate my powers.
Jabba's laugh is mean and loud.
Threepio attempts to warn Luke about the pit.
THREEPIO Master Luke, you're standing on...
THREEPIO I shall enjoy watching you die.
THREEPIO Luke reaches out, and a pistol jumps out of a guard's holster and flies into Luke's hand.
THREEPIO The bewildered guard grabs for it as Jabba raises his hand.
JABBA Bascka!
The floor suddenly drops away, sending Luke and the hapless guard into the pit.
The pistol goes off, blasting a hole in the ceiling.
Jabba laughs and his courtiers join in.
Leia starts forward but is restrained by a human guard-- Lando, recognizable behind his mask.
She looks at him and he shakes his head "no."
Luke and the guard have dropped twenty-five feet from a chute into the dungeonlike cage.
Luke gets to his feet as the guard yells hysterically for help.
A crowd gathers up around the edge of the pit as the door in the side of the pit starts to RUMBLE open.
The guard screams in panic.
Luke looks calmly around for a means of escape.
THREEPIO Oh, no!
THREEPIO The Rancor!
THREEPIO The Rancor moves past Luke, and as the guard continues to scramble, the Rancor picks him up and pops him into its slavering jaws.
THREEPIO A few screams, and the guard is swallowed with a gulp.
THREEPIO The audience cheers and laughs at the guard's fate.
THREEPIO The monster crushes the bone in its jaws and sees Luke, who squeezes into a crevice in the pit wall.
THREEPIO Luke looks past the monster to the holding cave beyond.
THREEPIO On the far side of the holding cave is a utility door--if only he can get to it.
THREEPIO The Rancor spots Luke and reaches into the crevice for him.
THREEPIO Luke grabs a large rock and raises it, smashing it down on the Rancor's finger.
The Rancor lets out a loud howl as Luke makes a run for the holding cave.
He reaches the door and pushes a button to open it.
When he succeeds, he sees a heavy barred gate between him and safety.
Beyond the gate two guards look up from their dinner.
Luke turns to see the monster heading for him, and pulls with all his might on the gate.
The guards move to the gate and start poking at the young Jedi with spears, laughing.
Luke crouches (against the wall) as the monster starts to reach for him.
Suddenly he notices a main door control panel halfway up the wall.
As the Rancor moves in for the kill, Luke picks up a skull from the cave floor and hurls it at the panel.
The giant overhead door comes crashing down on the beast's head, squashing it like a sledgehammer on an egg.
A startled gasp is heard from the stunned court.
There's consternation at this turn of events.
Heads look to Jabba, who is actually turning red with anger.
Leia cannot suppress her joy.
Jabba utters harsh commands to his guards and they hurry off.
JABBA (in Huttese subtitled) Bring me Solo and the Wookiee.
They will all suffer for this outrage.
The Rancor KEEPERS have come into the cage and are examining their dead beast.
One of them breaks down and weeps.
The other glares menacingly at Luke, who is unworried.
Several guards rush into the holding tunnel and take Luke away.
The crowd of creepy courtiers parts as Han and Chewie are brought into the throne room, and other guards drag Luke up the steps.
LUKE Han!
HAN Luke!
LUKE Are you all right?
HAN Fine.
HAN Together again, huh?
LUKE Wouldn't miss it.
HAN How are we doing?
LUKE The same as always.
HAN That bad, huh?
HAN Where's Leia?
Luke looks to Leia.
LEIA I'm here.
LEIA Threepio steps forward and translates for the captives.
THREEPIO Oh, dear.
THREEPIO His High Exaltedness, the great Jabba the Hutt, has decreed that you are to be terminated immediately.
HAN Good, I hate long waits.
THREEPIO You will therefore be taken to the Dune Sea and cast into the pit of Carkoon, the nesting place of the all-powerful Sarlacc.
HAN (to Luke) Doesn't sound so bad.
THREEPIO In his belly, you will find a new definition of pain and suffering, as you are slowly digested over a thousand years.
HAN On second thought, let's pass on that, huh?
Chewie barks his agreement.
LUKE You should have bargained, Jabba.
LUKE That's the last mistake you'll ever make.
LUKE As the guards drag the prisoners from the throne room, a loud cheer rises from the crowd.
LUKE Leia and Chewie exchange concerned looks, but Luke Skywalker, Jedi warrior, cannot suppress a smile.
Jabba's huge SAIL BARGE moves above the desert surface accompanied by two smaller Skiffs.
One of the skiffs glides close, revealing Luke, Han, and Chewie -- all in bonds -- surrounded by guards, one of whom is Lando in disguise.
HAN I think my eyes are getting better.
HAN Instead of a big dark blur, I see a big light blur.
LUKE There's nothing to see.
LUKE I used to live here, you know.
HAN You're gonna die here, you know.
HAN Convenient.
LUKE Just stick close to Chewie and Lando.
LUKE I've taken care of everything.
HAN Oh...
HAN great!
Jabba the Hutt rides like a sultan in the massive antigravity ship.
His entire retinue is with him, drinking, eating, and having a good time.
Leia is watching her friends in the skiff when the chain attached to her neck is pulled tight and Jabba tugs the scantily clad princess to him.
JABBA (in Huttese subtitled) Soon you will learn to appreciate me.
Threepio wanders among the Sail Barge aliens, bumping into a smaller droid serving drinks, spilling them all over the place.
The stubby droid lets out an angry series of beeps and whistles.
THREEPIO Oh, I'm terribly sor...
THREEPIO Artoo!
THREEPIO What are you doing here?
Artoo beeps a quick reply.
THREEPIO Well, I can see you're serving drinks, but this place is dangerous.
THREEPIO They're going to execute Master Luke and, if we're not careful, us too!
Artoo whistles a singsong response.
THREEPIO Hmm.
THREEPIO I wish I had your confidence.
The convoy moves up over a huge sand pit.
The Sail Barge stops to one side of the depression, as does the escort skiff.
But the prisoner's skiff moves out directly over the center and hovers.
At the bottom of the deep cone of sand is a repulsive, mucous-lined hole, surrounded by thousands of needle-sharp teeth.
This is the SARLACC.
A plank is extended from the edge of the prisoner's skiff.
Guards release Luke's bonds and shove him out onto the plank above the Sarlacc's mouth.
Jabba and Leia are now by the rail, watching.
Threepio leans forward and the slobbering villain mumbles something to him.
As Threepio steps up to a comlink, Jabba raises his arm and the motley array of intergalactic pirates fall silent.
Threepio's voice is amplified across loudspeakers.
THREEPIO Victims of the almighty Sarlacc: His Excellency hopes that you will die honorably.
THREEPIO But should any of you wish to beg for mercy, the great Jabba the Hutt will now listen to your pleas.
Han steps forward arrogantly and begins to speak.
HAN Threepio, you tell that slimy piece of...
HAN worm-ridden filth he'll get no such pleasure from us.
HAN Right?
Chewie growls his agreement.
LUKE Jabba!
LUKE This is your last chance.
LUKE Free us or die.
Lando moves unobtrusively along the skiff as Luke shoots a quick look of conspiracy to him.
The assembled monsters rock with mocking laughter as Artoo zips unnoticed up the ramp to the upper deck.
Jabba's laughter subsides as he speaks into the comlink.
JABBA (in Huttese subtitled) Move him into position.
Jabba makes a thumbs-down gesture.
Leia looks worried.
Artoo appears from below and zips over to the rail facing the pit.
Below, in the skiff, Luke is prodded by a guard to the edge of the plank over the gaping Sarlacc.
Luke looks up at Artoo, then gives a jaunty salute: the signal the little droid has been waiting for.
A flap opens in Artoo's domed head.
JABBA (in Huttese subtitled) Put him in.
Luke is prodded and jumps off the plank to the cheers of the bloodthirsty spectators.
But, before anyone can even perceive what is happening, he spins around and grabs the end of the plank by his fingertips.
The plank bends wildly from his weight and catapults him skyward.
In midair he does a complete flip and drops down on the end of the plank in the same spot he just vacated, but facing the skiff.
He casually extends an open palm and -- his lightsaber, which Artoo has sent arcing toward him, drops into his hand.
With samurai speed, Luke ignites it and attacks the guard who prodded him off the plank, sending the hapless monster screaming overboard.
The other guards swarm toward Luke.
He wades into them, lightsaber flashing.
Lando struggles with another guard at the back of the skiff.
A bewildered guard lands in the soft, sandy slope of the pit, and begins sliding.
He claws desperately as a Sarlacc tentacle grabs him and pulls him screaming into the viscous mouth.
Jabba watches this and explodes in rage.
He barks commands, and the guards around him rush off to do his bidding.
The scuzzy creatures watching the action from the window are in an uproar.
Luke knocks another guard off the skiff and into the waiting mouth of the Sarlacc.
He starts to untie Chewie's bonds.
LUKE Easy, Chewie.
At that moment, the deck gunmen on the barge unleash a series of blasts from a big cannon on the upper deck.
Lando is tossed from the deck of the rocking skiff.
He manages to grab a rope, and dangles desperately above the Sarlacc pit.
LANDO Whoa!
LANDO Whoa!
LANDO Help!
With two swift strides, the dangerous Boba Fett ignites his rocket pack, leaps into the air, and flies from the barge down to the skiff.
Boba lands on the skiff and starts to aim his laser gun at Luke, who has freed Han and Chewie from their bonds.
But before Boba can fire, the young Jedi spins on him, lightsaber sweeping, and hacks the bounty hunter's gun in half.
Immediately, the skiff takes another direct hit from the barge's deck gun.
Shards of skiff deck fly.
Chewie and Han are thrown against the rail.
HAN Chewie, you okay?
HAN Where is he?
The Wookiee is wounded and he howls in pain.
HAN I'm okay, pal.
HAN Another blast from the Barge's deck gun hits near Boba and he is knocked unconscious to the deck, next to where Lando is hanging.
LANDO Han!
LANDO Chewie?
HAN Lando!
HAN Chewie, wounded, tries to lift himself as he barks directions to Han, guiding him toward a spear which has been dropped by one of the guards.
HAN Han searches the deck as Chewie barks directions; finally he grabs hold of the spear.
HAN Chewie barks desperately at Han.
HAN Boba Fett?!
HAN Boba Fett?!
HAN Where?
HAN The impact of the swing causes the rocket pack to ignite.
HAN Boba blasts off, flying over the second skiff like a missile, smashing against the side of the huge Sail Barge and sliding away into the pit.
HAN He screams as his armored body makes its last flight past Lando and directly into the mucous mouth of the Sarlacc.
HAN The Sarlacc burps.
HAN Chewie growls a weak congratulations to Han.
Leia turns from the spectacle outside, leaps onto Jabba's throne, and throws the chain that enslaves her over his head around his bulbous neck.
Then she dives off the other side of the throne, pulling the chain violently in her grasp.
Jabba's flaccid neck contracts beneath the tightening chain.
His huge eyes bulge from their sockets and his scum-coated tongue flops out.
The Exalted Hutt's huge tail spasms through its death throes and then slams down into final stillness.
Leia struggles to free herself of her bondage.
Luke continues to destroy the aliens on the guards' skiff, as Han extends his spear downward to Lando, who is still dangling precariously from a rope on the prisoner's skiff.
HAN Lando, grab it!
LANDO Lower it!
HAN I'm trying!
A major hit from the barge deck gun knocks the skiff on its side.
Han and almost everything else on board slides overboard.
The rope breaks, and Lando falls to the side of the Sarlacc pit.
Luckily, Han's foot catches on the skiff railing and he dangles above Lando and the pit.
The wounded Wookiee holds onto the skiff for dear life as another hit from the deck gun rocks the skiff violently.
HAN Whoa!
HAN Whoa!
HAN Grab me, Chewie!
HAN I'm slipping.
Chewie grabs hold of Han's feet, holding him upside down, as Han extends the spear toward Lando, who is clutching to the side of the pit.
HAN Grab it!
HAN L--Lando.
HAN Grab!
HAN The injured Chewie is reaching over the rail for the dangling Han, who is in turn blindly reaching down toward the desperate Lando.
HAN The Baron has stopped his slippage down the sandy slope of the Sarlacc pit by lying very still.
HAN Every time he tries to reach for Han, the loose sand moves him closer to his final reward.
HAN Grab it!
HAN Almost...
HAN You almost got it!
Another blast hits the front of the tilted skiff, causing Lando to let go of the spear.
LANDO Hold it!
LANDO Whoa!
Again Han extends the spear toward Lando.
HAN Gently now.
HAN All...
HAN all right.
HAN Now easy, easy.
HAN Hold me, Chewie.
Lando screams.
One of the Sarlacc's tentacles has wrapped tightly around his ankle, dragging him down the side of the pit.
HAN Chewie!
HAN Chewie, give me the gun.
HAN Don't move, Lando.
LANDO No, wait!
LANDO I thought you were blind!
HAN It's all right.
HAN Trust me.
HAN Don't move.
LANDO All right!
LANDO A little higher!
LANDO Just a little higher!
Han adjusts his aim as Lando lowers his head, and the fuzzy-eyed pirate fires at the tentacle.
Direct hit.
The tentacle releases Lando, and Chewie starts to pull them on board the skiff.
HAN Chewie, Pull us up!
HAN Come on!
HAN Okay...
HAN up, Chewie, up!
The deck gunners have Chewie and the desperate dangling human chain in their gun sights when something up on deck commands their attention: Luke, standing before them like a pirate king, ignites his lightsaber.
The deck gunners have barely reached for their pistols before the young Jedi has demolished them.
Immediately, Luke turns to see two more gunners (who have been uncovering a giant gun at the end of the barge) racing for him, firing their laser pistols.
Leia is struggling against her chains in desperation as Artoo zips through the tumult of confused monsters to the rescue; the stubby little droid extends a small laser gun and blasts the chain apart.
LEIA Come on.
LEIA We gotta get out of here quick.
Artoo and Leia race for the exit, passing Threepio, who is kicking and screaming as Salacious Crumb, the reptilian monkey- monster picks out one of the golden droid's eyes.
THREEPIO Not my eyes!
THREEPIO Artoo, help!
THREEPIO Quickly, Artoo.
THREEPIO Oh!
THREEPIO Ohhh!
THREEPIO You beast!
Artoo zips over and zaps Salacious, sending him skyward with a scream, crashing into the rafters as Artoo, Leia, and Threepio (with his eye dangling from a wire) hurry off.
Luke is warding off laser blasts with his lightsaber, surrounded by guards and fighting like a demon.
Leia emerges onto the deck as Luke turns to face another guard.
LUKE (to Leia) Get the gun!
Point it at the deck!
Leia turns toward the barge cannon, climbs on the platform, and swivels the gun around.
LUKE Point it at the deck!
LUKE Near the rail of the upper deck, Artoo and Threepio steady themselves as Threepio gets ready to jump.
LUKE Artoo beeps wildly.
THREEPIO Artoo, where are we going?
THREEPIO I couldn't possibly jump.
THREEPIO Luke runs along the empty deck toward Leia and the barge gun, which she has brought around to point down at the deck.
LUKE Come on!
Luke has hold on one of the rigging ropes from the mast.
He gathers Leia in his other arm and kicks the trigger of the deck gun.
The gun explodes into the deck as Luke and Leia swing out toward the skiff.
Han leans panting against the rail as Chewie helps Lando onto the deck.
Luke and Leia land on the skiff with flair.
LUKE Let's go!
LUKE And don't forget the droids.
LANDO We're on our way.
The Sail Barge is exploding in stages in the distance.
Half of the huge craft is on fire.
Threepio's legs stick straight up from the dune where he landed.
Next to it, Artoo's periscope is the only thing above the sand.
The skiff floats above them and two large electromagnets dangle down on a wire.
With a loud CLANG, both droids are pulled from the sand.
The little skiff skips around the burning Sail Barge, which continues its chain of explosions.
As the skiff sails off across the desert, the barge settles to the sand and disappears in one final conflagration.
A ferocious sandstorm blocks our view.
Then, through the ROAR, we HEAR THE VOICES of our heroes.
They emerge slowly from the veil of sand, pressing on against the wind.
First come Artoo and Threepio, followed by Leia guiding Han, then Luke and Lando come into view, each supporting one side of the towering Chewbacca, who hobbles from his wound.
Soon, they can make out some large vague shapes in the blowing sand.
It is the Millennium Falcon and, parked beside it, Luke's trusty X-wing and a two-seated Y-wing.
They must shout to be heard.
HAN I don't know.
HAN All I can see is a lot of blowing sand!
LEIA That's all any of us can see.
LEIA HAN (blinking) Then I guess I'm getting better.
LEIA As soon as the group huddles under the bulk of the Falcon, the wind dies down to something more describable as a severe weather condition.
LEIA Threepio hits a switch, and the gang-plank lowers with a HUM.
LEIA HAN (turning to Luke) I've got to hand it to you, kid, you were pretty good out there.
LEIA LUKE (shrugging it off) I had a lot of help.
LEIA Think nothing of it.
HAN No, I'm thinking a lot about it.
HAN That carbon freeze was the closest thing to dead there is.
HAN And it wasn't just sleepin'.
HAN It was a big wide awake nothing!
HAN LUKE (moving to his ship) I'll see you back at the fleet.
HAN Why don't you leave that crate and come with us?
LUKE I have a promise I have to keep first...
LUKE to an old friend.
Luke and Artoo take off in their spacecraft.
HAN Guess I owe you some thanks, too, Lando.
LANDO Figured if I left you frozen like that you'd just give me bad luck the rest of my life, so I might as well get you unfrozen sooner or later.
LEIA He means "You're welcome."
LANDO Come on, let's get off this miserable dust ball.
The desolate yellow planet fills the screen, Luke's X-wing appears and peels off to the left.
A moment later, the FALCON appears as a dot and grows huge, to roar directly over the CAMERA.
Luke is at the controls, with Artoo attached behind him outside the canopy.
Luke speaks into his comlink to the others, in the MILLENNIUM
LUKE I'll meet you back at the fleet.
LEIA (over comlink) Hurry.
The Alliance should be assembled by now.
LUKE I will.
LUKE Now I owe you one.
LUKE A message from Artoo appears on the small monitor screen in front of Luke.
LUKE He smiles at the monitor and speaks to Artoo, as he pulls a black glove on to cover his wounded mechanical hand.
LUKE That's right, Artoo.
LUKE We're going to the Dagobah system.
LUKE I have a promise to keep...
LUKE to an old friend.
A Super Star Destroyer and several ships of the Imperial Fleet rest in space above the half-completed Death Star and its green neighbor, Endor.
Four squads of TIE fighters escort an Imperial shuttle toward the Death Star.
Lord Vader strides down the hallway, accompanied by a very nervous Death Star commander.
Thousands of Imperial troops in tight formation fill the mammoth docking bay.
Vader and the officer walk to the landing platform, where the shuttle is coming to rest.
The shuttle's ramp lowers and the Emperor's Royal Guards come out and create a lethal perimeter.
The assembled troops move to rigid attention with a momentous SNAP.
Then, in the huge SILENCE which follows, the EMPEROR appears.
He is a rather small, shriveled old man.
His bent frame slowly makes its way down the ramp with the aid of a gnarled cane.
He wears a hooded cloak similar to the one Ben wears, except that it is black.
The Emperor's face is shrouded and difficult to see, except for his piercing yellow eyes.
Commander Jerjerrod and Darth Vader kneel to him.
The Supreme Ruler of the galaxy beckons to the Dark Lord.
EMPEROR (to Vader) Rise, my friend.
Vader rises and falls in next to the Emperor as he slowly makes his way along the rows of troops.
Jerjerrod and the other commanders stay kneeling until the Supreme Ruler and Vader, followed by several Imperial dignitaries, pass by; only then do they join in the procession.
VADER The Death Star will be completed on schedule.
EMPEROR You have done well, Lord Vader.
EMPEROR And now I sense you wish to continue your search for young Skywalker.
VADER Yes, my Master.
EMPEROR Patience, my friend.
EMPEROR In time he will seek you out.
EMPEROR And when he does, you must bring him before me.
EMPEROR He has grown strong.
EMPEROR Only together can we turn him to the dark side of the Force.
VADER As you wish.
EMPEROR Everything is proceeding as I have foreseen.
He laughs to himself as they pass along the vast line of Imperial troops.
Once again, Artoo finds himself waiting around in the damp environs of the swamp planet, and he's none too happy about it.
He beeps disconsolately to himself and turns to look at Yoda's cottage.
Warm yellow light escapes the oddly shaped windows to fight the gloom.
The tip of a walking stick taps hesitantly across the earthen floor of the cottage.
Our view travels up the stick to the small green hand that clutches it, and then to the familiar face of YODA, THE JEDI MASTER.
His manner is frail, and his voice, though cheerful, seems weaker.
YODA Hmm.
YODA That face you make.
YODA Look I so old to young eyes?
Luke is sitting in a corner of the cramped space and, indeed, his look has been woeful.
Caught, he tries to hide it.
LUKE No...
LUKE of course not.
LUKE YODA (tickled, chuckles) I do, yes, I do!
LUKE Sick have I become.
LUKE When nine hundred years old you reach, look as good you will not.
LUKE Hmm?
Yoda chuckles at this, coughs, and hobbles over toward his bed.
YODA Soon will I rest.
YODA Yes, forever sleep.
YODA Earned it, I have.
Yoda sits himself on his bed, with great effort.
LUKE Master Yoda, you can't die.
YODA Strong am I with the Force...
YODA but not that strong!
YODA Twilight is upon me and soon night must fall.
YODA That is the way of things...
YODA the way of the Force.
LUKE But I need your help.
LUKE I've come back to complete the training.
YODA No more training do you require.
YODA Already know you that which you need.
Yoda sighs, and lies back on his bed.
LUKE Then I am a Jedi?
LUKE You must confront Vader.
LUKE Then, only then, a Jedi will you be.
LUKE And confront him you will.
LUKE Luke is in agony.
LUKE He is silent for a long moment, screwing up his courage.
LUKE Finally he is able to ask.
LUKE Master Yoda...
LUKE is Darth Vader my father?
Yoda's eyes are full of weariness and compassion.
An odd, sad smile creases his face.
He turns painfully on his side, away from Luke.
YODA Mmm...
YODA rest I need.
YODA Yes...
YODA rest.
Luke watches him, each moment an eternity.
LUKE Yoda, I must know.
YODA Your father he is.
Luke reacts as if cut.
YODA Told you, did he?
LUKE Yes.
A new look of concern crosses Yoda's face.
He closes his eyes.
YODA Unexpected this is, and unfortunate...
LUKE Unfortunate that I know the truth?
LUKE YODA (gathering all his strength) No.
LUKE Unfortunate that you rushed to face him...
LUKE that incomplete was your training.
LUKE Not ready for the burden were you.
LUKE Well, I'm sorry.
YODA Remember, a Jedi's strength flows from the Force.
YODA But beware.
YODA Anger, fear, aggression.
YODA The dark side are they.
YODA Once you start down the dark path, forever will it dominate your destiny.
He beckons the young Jedi closer to him.
YODA Luke...Luke...Do not...Do not underestimate the powers of the Emperor, or suffer your father's fate, you will.
YODA Luke, when gone am I (cough), the last of the Jedi will you be.
YODA Luke, the Force runs strong in your family.
YODA Pass on what you have learned, Luke...
YODA There is...another...Sky...Sky...walker.
He catches his breath.
A shiver runs through the ancient green creature, and he dies.
Luke stares at his dead master as he disappears in front of his eyes.
Luke wanders back to where his ship is sitting.
Artoo beeps a greeting, but is ignored by his depressed master.
Luke kneels down, begins to help Artoo with the ship, then stops and shakes his head dejectedly.
LUKE I can't do it, Artoo.
LUKE I can't go on alone.
Yoda will always be with you.
Luke looks up to see the shimmering image of BEN KENOBI.
LUKE Obi-Wan!
LUKE Why didn't you tell me?
The ghost of Ben Kenobi approaches him through the swamp.
LUKE You told me Vader betrayed and murdered my father.
BEN You father was seduced by the dark side of the Force.
BEN He ceased to be Anakin Skywalker and became Darth Vader.
BEN When that happened, the good man who was your father was destroyed.
BEN So what I have told you was true...
BEN from a certain point of view.
LUKE (turning away, derisive) A certain point of view!
BEN Luke, you're going to find that many of the truths we cling to depend greatly on our own point of view.
Luke is unresponsive.
Ben studies him in silence for a moment.
BEN I don't blame you for being angry.
BEN If I was wrong in what I did, it certainly wouldn't have been for the first time.
BEN You see, what happened to your father was my fault.
Ben pauses sadly.
BEN Anakin was a good friend.
Luke turns with interest at this.
As Ben speaks, Luke settles on a stump, mesmerized.
Artoo comes over to offer his comforting presence.
BEN When I first knew him, your father was already a great pilot.
BEN But I was amazed how strongly the Force was with him.
BEN I took it upon myself to train him as a Jedi.
BEN I thought that I could instruct him just as well as Yoda.
BEN I was wrong.
BEN My pride has had terrible consequences for the galaxy.
Luke is entranced.
LUKE There's still good in him.
BEN I also thought he could be turned back to the good side.
BEN It couldn't be done.
BEN He is more machine now than man.
BEN Twisted and evil.
LUKE I can't do it, Ben.
BEN You cannot escape your destiny.
LUKE I tried to stop him once.
LUKE I couldn't do it.
BEN Vader humbled you when first you met him, Luke...
BEN but that experience was part of your training.
BEN It taught you, among other things, the value of patience.
BEN Had you not been so impatient to defeat Vader then, you could have finished your training here with Yoda.
BEN You would have been prepared.
LUKE But I had to help my friends.
LUKE BEN (grinning at Luke's indignation) And did you help them?
LUKE It was they who had to save you.
LUKE You achieved little by rushing back prematurely, I fear.
LUKE LUKE (with sadness) I found out Darth Vader was my father.
BEN To be a Jedi, Luke, you must confront and then go beyond the dark side - the side your father couldn't get past.
BEN Impatience is the easiest door - for you, like your father.
BEN Only, your father was seduced by what he found on the other side of the door, and you have held firm.
BEN You're no longer so reckless now, Luke.
BEN You are strong and patient.
BEN And now, you must face Darth Vader again!
LUKE I can't kill my own father.
BEN Then the Emperor has already won.
BEN You were our only hope.
LUKE Yoda spoke of another.
BEN The other he spoke of is your twin sister.
LUKE But I have no sister.
BEN Hmm.
BEN To protect you both from the Emperor, you were hidden from your father when you were born.
BEN The Emperor knew, as I did, if Anakin were to have any offspring, they would be a threat to him.
BEN That is the reason why your sister remains safely anonymous.
LUKE Leia!
LUKE Leia's my sister.
BEN Your insight serves you well.
BEN Bury your feelings deep down, Luke.
BEN They do you credit.
BEN But they could be made to serve the Emperor.
BEN BEN (continuing his narrative) When your father left, he didn't know your mother was pregnant.
BEN Your mother and I knew he would find out eventually, but we wanted to keep you both as safe as possible, for as long as possible.
BEN So I took you to live with my brother Owen on Tatooine...
BEN and your mother took Leia to live as the daughter of Senator Organa, on Alderaan.
BEN BEN (attempting to give solace with his words) The Organa household was high-born and politically quite powerful in that system.
BEN Leia became a princess by virtue of lineage...
BEN no one knew she'd been adopted, of course.
BEN But it was a title without real power, since Alderaan had long been a democracy.
BEN Even so, the family continued to be politically powerful, and Leia, following in her foster father's path, became a senator as well.
BEN That's not all she became, of course...
BEN she became the leader of her cell in the Alliance against the corrupt Empire.
BEN And because she had diplomatic immunity, she was a vital link for getting information to the Rebel cause.
BEN That's what she was doing when her path crossed yours...
BEN for her foster parents had always told her to contact me on Tatooine, if her troubles became desperate.
Luke is overwhelmed by the truth, and is suddenly protective of his sister.
LUKE But you can't let her get involved now, Ben.
LUKE Vader will destroy her.
BEN She hasn't been trained in the ways of the Jedi the way you have, Luke...
BEN but the Force is strong with her, as it is with all of your family.
BEN There is no avoiding the battle.
BEN You must face and destroy Vader!
The vast Rebel Fleet stretches as far as the eye can see.
Overhead a dozen small Corellian battleships fly in formation.
Fighters and battlecruisers surround the largest of the Rebel Star Cruisers, the
Hundreds of Rebel commanders of all races and forms are assembled in the WAR ROOM.
WEDGE is among them.
In the center of the room is a holographic model depicting the half-completed Imperial Death Star, the nearby Moon of Endor, and the protecting deflector shield.
MON MOTHMA, the leader of the Alliance, enters the room.
She is a stern but beautiful woman in her fifties.
Conferring with her are several military leaders, including GENERAL MADINE and ADMIRAL ACKBAR (a salmon-colored Mon Calamari).
Lando moves through the crowd until he finds Han and Chewie, standing next to Leia and the two droids.
Han peers at Lando's new insignia on his chest, and is amused.
HAN Well, look at you, a general, huh?
LANDO Oh, well, someone must have told them about my little maneuver at the battle of Taanab.
LANDO I just said you were a fair pilot.
LANDO I didn't know they were lookin' for somebody to lead this crazy attack.
LANDO LANDO (smiling) I'm surprised they didn't ask you to do it.
HAN Well, who says they didn't.
HAN But I ain't crazy.
HAN You're the respectable one, remember?
Mon Mothma signals for attention, and the room falls silent.
MON MOTHMA The Emperor has made a critical error and the time for our attack has come.
This causes a stir.
Mon Mothma turns to a holographic model of the Death Star, the Endor moon and the protecting deflector shield in the center of the room.
MON MOTHMA The data brought to us by the Bothan spies pinpoints the exact location of the Emperor's new battle station.
MON MOTHMA We also know that the weapon systems of this Death Star are not yet operational.
MON MOTHMA With the Imperial Fleet spread throughout the galaxy in a vain effort to engage us, it is relatively unprotected.
MON MOTHMA But most important of all, we've learned that the Emperor himself is personally overseeing the final stages of the construction of this Death Star.
MON MOTHMA MON MOTHMA (cont) Many Bothans died to bring us this information.
MON MOTHMA Admiral Ackbar, please.
Admiral Ackbar steps forward and points to the Death Star's force field and the Moon of Endor.
ACKBAR You can see here the Death Star orbiting the forest Moon of Endor.
ACKBAR Although the weapon systems on this Death Star are not yet operational, the Death Star does have a strong defense mechanism.
ACKBAR It is protected by an energy shield, which is generated from the nearby forest Moon of Endor.
ACKBAR The shield must be deactivated if any attack is to be attempted.
ACKBAR Once the shield is down, our cruisers will create a perimeter, while the fighters fly into the superstructure and attempt to knock out the main reactor.
ACKBAR ACKBAR (cont) General Calrissian has volunteered to lead the fighter attack
Han turns to Lando with a look of respect.
HAN Good luck.
Lando nods his thanks.
HAN You're gonna need it.
ACKBAR General Madine.
Madine moves center stage.
GENERAL MADINE We have stolen a small Imperial shuttle.
GENERAL MADINE Disguised as a cargo ship, and using a secret Imperial code, a strike team will land on the moon and deactivate the shield generator.
The assembly begins to mumble among themselves.
THREEPIO Sounds dangerous.
THREEPIO LEIA (to Han) I wonder who they found to pull that off.
GENERAL MADINE General Solo, is your strike team assembled?
Leia, startled, looks up at Han, surprise changing to admiration.
HAN Uh, my team's ready.
HAN I don't have a command crew for the shuttle.
Chewbacca raises his hairy paw and volunteers.
Han looks up at him.
HAN Well, it's gonna be rough, pal.
HAN I didn't want to speak for you.
HAN HAN (smiles) That's one.
LEIA Uh, General...
LEIA count me in.
I'm with you, too!
They turn in that direction and peer into the crowd as there are more cheers.
The commanders part, and there at the back stands Luke.
Han and Leia are surprised and delighted.
Leia moves to Luke and embraces him warmly.
She senses a change in him and looks into his eyes questioningly.
LEIA What is it?
LEIA Han, Chewie, and Lando crowd around Luke as the assembly breaks up.
HAN Luke.
LUKE Hi, Han...
LUKE Chewie.
Artoo beeps a singsong observation to a worried Threepio.
THREEPIO "Exciting" is hardly the word I would use.
The Millennium Falcon rests beyond the stolen IMPERIAL SHUTTLE, which looks anomalous among all the Rebel ships in the vast docking bay.
Chewie barks a final farewell to Lando and leads Artoo and Threepio up the shuttle, crowded now with the Rebel strike team loading weapons and supplies.
Lando turns to face Han.
Luke and Leia have said their good- byes and start up the ramp.
HAN Look.
HAN I want you to take her.
HAN I mean it.
HAN Take her.
HAN You need all the help you can get.
HAN She's the fastest ship in the fleet.
LANDO All right, old buddy.
LANDO You know, I know what she means to you.
LANDO I'll take good care of her.
LANDO She-she won't get a scratch.
LANDO All right?
LANDO I got your promise now.
Not a scratch.
LANDO Look, would you get going, you pirate.
Han and Lando pause, then exchange salutes.
LANDO Good luck.
HAN You, too.
Han goes up the ramp.
Lando watches him go and then slowly turns away.
Luke is working on a back control panel as Han comes in and takes the pilot's seat.
Chewie, in the seat next to him, is trying to figure out all the Imperial controls.
HAN You got her warmed?
LUKE Yeah, she's comin' up.
Chewie growls a complaint.
HAN No.
HAN I don't think the Empire had Wookiees in mind when they designed her, Chewie.
HAN Chewie barks and hits some switches.
HAN Han's glance has stuck on something out the window: the Millennium Falcon.
HAN Leia nudges him gently.
LEIA Hey, are you awake?
HAN Yeah, I just got a funny feeling.
HAN Like I'm not gonna see her again.
HAN LEIA (softly) Come on, General, let's move.
Han snaps back to life.
HAN Right.
HAN Chewie, let's see what this piece of junk can do.
HAN Ready, everybody?
LUKE All set.
THREEPIO Here we go again.
HAN All right, hang on.
The stolen Imperial shuttle leaves the main docking bay of the Headquarters Frigate, lowers its wings into flight position, and zooms off into space.
The converted control room is dimly lit, except for a pool of light at the far end.
There the Emperor sits in an elaborate control chair before a large window which looks out across the half-completed Death Star to the giant green moon of Endor.
Darth Vader, standing with other members of the Imperial council, cautiously approaches his master.
The ruler's back is to Vader.
After several tense moments, the Emperor's chair rotates around to face him.
VADER What is thy bidding, my Master?
EMPEROR Send the fleet to the far side of Endor.
EMPEROR There it will stay until called for.
VADER What of the reports of the Rebel fleet massing near Sullust?
EMPEROR It is of no concern.
EMPEROR Soon the Rebellion will be crushed and young Skywalker will be one of us!
EMPEROR Your work here is finished, my friend.
EMPEROR Go out to the command ship and await my orders.
VADER Yes, my Master.
Vader bows, then turns and exits the throne room as the Emperor walks toward the waiting council members.
There is a great deal of Imperial traffic in the area as construction proceeds on the Death Star.
Transports, TIE fighters, and a few Star Destroyers move about.
Now the huge Super Star Destroyer announces itself with a low roar and soon fills the frame.
Han looks back at Luke and Leia as Chewie flips several switches.
Through the viewscreen, the Death Star and the huge Super Star Destroyer can be seen.
HAN If they don't go for this, we're gonna have to get outta here pretty quick, Chewie.
HAN CONTROLLER (over radio) We have you on our screen now.
HAN Please identify.
HAN Shuttle Tydirium requesting deactivation of the deflector shield.
CONTROLLER (over radio) Shuttle Tydirium, transmit the clearance code for shield passage.
HAN Transmission commencing.
Leia and Chewbacca listen tensely as the sound of a high speed transmission begins.
LEIA Now we find out if that code is worth the price we paid.
HAN It'll work.
HAN It'll work.
Chewie whines nervously.
Luke stares at the Huge Super Star Destroyer that looms ever larger before them.
LUKE Vader's on that ship.
HAN Now don't get jittery, Luke.
HAN There are a lot of command ships.
HAN Keep your distance though, Chewie, but don't look like you're trying to keep your distance.
Chewie barks a question.
HAN I don't know.
HAN Fly casual.
LUKE I'm endangering the mission.
LUKE I shouldn't have come.
HAN It's your imagination, kid.
HAN Come on.
HAN Let's keep a little optimism here.
Chewie barks his worries as the Super Star Destroyer grows larger out the window.
Lord Vader stands, back to us, staring out a window at the Death Star.
Now, some vibration felt only by him causes him to turn.
After a moment of stillness, he walks down the row of controllers to where ADMIRAL PIETT is leaning over the tracking screen of the controller we've seen earlier.
Piett straightens at Vader's approach.
VADER Where is that shuttle going?
VADER PILOT VOICE (HAN) (filtered) Parts and technical crew for the forest moon.
The Bridge Commander looks to Vader for a reaction.
VADER Do they have a code clearance?
PIETT It's an older code, sir, but it checks out.
PIETT I was about to clear them.
Vader looks upward, as he senses Luke's presence.
PIETT Shall I hold them?
VADER No.
VADER Leave them to me.
VADER I will deal with them myself.
VADER PIETT (surprised) As you wish, my lord.
VADER Carry on.
Piett nods at controller, who switches on his comlink.
The group waits tensely.
HAN They're not goin' for it, Chewie.
HAN Everyone breaths a sigh of relief.
HAN Everyone but Luke, who looks worried.
HAN Chewie barks.
HAN Okay!
HAN I told you it was gonna work.
HAN No problem.
The stolen Imperial shuttle moves off toward the green Sanctuary Moon.
The stolen Imperial shuttle sits in a clearing of the moon's dark, primeval forest, dwarfed by the ancient towering trees.
On an adjacent hill, the helmeted Rebel contingent makes its way up a steep trail.
Leia and Han are slightly ahead of Chewie and Luke.
The troops of the strike-team squad follow, with Artoo and Threepio bringing up the rear.
Artoo beeps.
Up ahead, Chewie and Leia reach a crest in the hill and drop suddenly to the ground, signaling the rest of the group to stop.
Han and Luke crawl up to take a look.
THREEPIO Oh, I told you it was dangerous here.
THEIR POV.
Not far below them, two IMPERIAL SCOUTS are wandering through bushes in the valley below.
Their two ROCKET BIKES are parked nearby.
LEIA Shall we try and go around?
HAN It'll take time.
HAN This whole party'll be for nothing if they see us.
Leia motions for the squad to stay put, then she, Han, Luke and Chewie start quietly down.
The four friends make their way to the edge of the clearing not far from the two Imperial scouts.
HAN Chewie and I will take care of this.
HAN You stay here.
LUKE Quietly, there might be more of them out there.
LUKE Han and Chewie turn and start through the bushes toward the scouts.
LUKE Luke and Leia exchange smiles.
Han sneaks up behind one of the scouts, steps on a twig and the scout whirls, knocking Han into a tree.
The scout shouts for his companion.
SCOUT #1 Go for help!
SCOUT #1 Go!
SCOUT #1 LUKE (sarcastic) Great.
SCOUT #1 Come on.
Luke starts for the scuffle, followed by Leia with her laser pistol drawn.
As they run through the bushes, Leia stops and points to where two more scouts are sitting on their speeder bikes, with an unoccupied bike parked nearby.
LEIA Over there!
LEIA Two more of them!
LUKE I see them.
LUKE Wait, Leia!
LUKE LUKE (pointing to the controls) Quick!
LUKE Jam their comlink.
LUKE Center switch!
Luke and Leia speed into the dense foliage in hot pursuit, barely avoiding two huge trees.
HAN Hey, wait!
HAN Ahhh!
He flips the remaining scout to the ground.
The two fleeing Imperial scouts have a good lead as Luke and Leia pursue through the giant trees at 200 miles an hour, the fire from their bike's laser cannon hitting harmlessly near the moving targets.
LUKE Move closer!
Leia guns it, closing the gap, as the two scouts recklessly veer through a narrow gap in the trees.
One of the bikes SCRAPES a tree, slowing the scout.
LUKE Get alongside that one!
Leia pulls her speeder bike up so close to the scout's bike that their steering vanes SCRAPE noisily.
Luke leaps from his bike to the back of the scout's, grabs the Imperial warrior around the neck, and flips him off the bike, into a thick tree trunk.
Luke gains control of the bike and follows Leia, who has pulled ahead.
They tear off after the remaining scout.
LUKE Get him!
LUKE LUKE (indicating the one ahead) Keep on that one!
LUKE I'll take these two!
LUKE The scout's cohort takes one glance back at the flash and shifts into turbo drive, going even faster.
LUKE Luke keeps on his tail.
LUKE The scout turns in confusion, unable to see his pursuer.
LUKE Suddenly, Leia dives down upon him from above, cannon blasting.
LUKE The scout's bike takes a glancing hit.
LUKE ANOTHER PART OF THE FOREST: Luke and the last remaining scout continue their weaving chase through the trees.
LUKE Now Luke moves up close.
LUKE The scout responds by slamming his bike into Luke's.
LUKE A fallen tree forms a bridge across their path.
LUKE The scout zips under.
LUKE Luke goes over the top and crashes his bike down on the scout's.
LUKE Both riders look ahead - a wide trunk looms directly in Luke's path, but the scout's bike beside him makes it almost impossible for him to avoid it.
LUKE Luke banks with all his might, leaning almost horizontal over the scout's bike, and is able to make it by, just clipping the tree.
LUKE When he straightens, he and the scout discover that their two bikes have locked front vanes and are moving as one.
LUKE Luke rises from the undergrowth as the scout bears down on him and opens fire with his laser cannon.
LUKE Luke ignites his laser sword and begins deflecting the bolts.
LUKE The scout's bike keeps coming and it appears that in a second it will cut Luke in half.
LUKE At the last instant, Luke steps aside and chops off the bike's control vanes with one mighty slash.
LUKE The scout's bike begins to shudder, then, pitching and rolling, it rises up to slam directly into a tree in a giant ball of fire.
Han, Chewie, and the droids, along with the rest of the squad, wait anxiously in the clearing.
Artoo's radar screen sticks out of his domed head and revolves, scanning the forest.
He beeps.
THREEPIO Oh, General Solo, somebody's coming.
THREEPIO Oh!
THREEPIO Luke steps out of the foliage to find the weapons trained on him.
THREEPIO He's too tired to care.
THREEPIO He plops himself down on a boulder and looks around.
HAN Luke!
HAN Where's Leia?
LUKE (concerned) What?
She didn't come back?
HAN I thought she was with you.
LUKE We got separated.
Luke and Han exchange a silent, grim look.
Luke gets up wearily.
LUKE Hey, we better go look for her.
Han nods, and signals to a Rebel officer.
HAN Take the squad ahead.
HAN We'll meet at the shield generator at 0300.
LUKE Come on, Artoo.
LUKE We'll need your scanners.
Luke, Chewie, Han, and the droids move off in one direction as the squad proceeds in another.
THREEPIO Don't worry, Master Luke.
THREEPIO We know what to do.
THREEPIO THREEPIO (to Artoo) And you said it was pretty here.
THREEPIO Ugh!
A strange little furry face with huge black eyes comes slowly into view.
The creature is an EWOK, by the name of WICKET.
He seems somewhat puzzled, and prods Leia with a spear.
The princess groans; this frightens the stubby ball of fuzz and he prods her again.
Leia sits up and stares at the three-foot-high Ewok.
She tries to figure out where she is and what has happened.
Her clothes are torn; she's bruised and disheveled.
The Ewok jumps up and grabs a four-foot-long spear, which he holds in a defensive position.
Leia watches him as he circles warily and begins poking her with the sharp point of the spear.
LEIA Cut it out!
She stands up, and the Ewok quickly backs away.
LEIA I'm not gonna hurt you.
Leia looks around at the dense forest, and at the charred remains of her speeder bike, then sits down, with a sigh, on a fallen log.
LEIA Well, looks like I'm stuck here.
LEIA Trouble is, I don't know where here is.
She puts her head in her hands to rub away some of the soreness from her fall.
She looks over at the watchful little Ewok and pats the log beside her.
LEIA Well, maybe you can help me.
LEIA Come on, sit down.
Wicket holds his spear up warily and growls at her like a puppy.
Leia pats the log again.
LEIA I promise I won't hurt you.
LEIA Now come here.
More growls and squeaks from the little bear creature.
LEIA All right.
LEIA You want something to eat?
She takes a scrap of food out of her pocket and offers it to him.
Wicket takes a step backward, then cocks his head and moves cautiously toward Leia, chattering in his squeaky Ewok language.
LEIA That's right.
LEIA Come on.
LEIA Hmmm?
Sniffing the food curiously, the Ewok comes toward Leia and sits on the log beside her.
She takes off her helmet, and the little creature jumps back, startled again.
He runs along the log, pointing his spear at her and chattering a blue streak.
Leia holds out the helmet to him.
LEIA Look, it's a hat.
LEIA It's not gonna hurt you.
LEIA Look.
LEIA You're a jittery little thing, aren't you?
Reassured, Wicket lowers his spear and climbs back on the log, coming to investigate the helmet.
Suddenly his ears perk up and he begins to sniff the air.
He looks around warily, whispering some Ewokese warning to Leia.
LEIA What is it?
LEIA SCOUT #l Freeze!
LEIA Come on, get up!
She hands the weapon over, as a second scout emerges from the foliage in front of the log.
SCOUT #1 Go get your ride and take her back to base.
Yes, sir.
The second scout starts toward his bike, as Wicket, crouched under the log, extends his spear and hits the first scout on the leg.
The scout jumps and lets out an exclamation, and looks down at Wicket, puzzled.
Leia grabs a branch and knocks him out.
She dives for his laser pistol, and the second scout, now on his bike, takes off.
Leia fires away and hits the escaping bike, causing it to crash into the first scout's bike, which flies end over end and explodes.
The forest is quiet once more.
Wicket pokes his fuzzy head up from behind the log and regards Leia withEnew respect.
He mumbles his awe.
Leia hurries over, looking around all the time, and motions the chubby little creature into the dense foliage.
LEIA Come on, let's get outta here.
As they move into the foliage, Wicket takes the lead.
He shrieks and tugs at Leia to follow him.
Darth Vader walks down the corridor to the Emperor's Tower and private elevator.
The Emperor's private guard steps in Vader's path.
GUARD Halt!
GUARD The Emperor does not wish to be disturbed at the moment.
VADER The Emperor will see me, now!
GUARD The Emperor will see you, now.
Two red Imperial Guards stand watch at the elevator as the door opens to reveal Vader.
Vader enters the eerie, foreboding throne room.
It appears to be empty.
His footsteps echo as he approaches the throne.
He waits, absolutely still.
The Emperor sits with his back to the Dark Lord.
EMPEROR I told you to remain on the command ship.
VADER A small Rebel force has penetrated the shield and landed on Endor.
VADER EMPEROR (no surprise) Yes, I know.
VADER VADER (after a beat) My son is with them.
VADER EMPEROR (very cool) Are you sure?
VADER I have felt him, my Master.
EMPEROR Strange, that I have not.
EMPEROR I wonder if your feelings on this matter are clear, Lord Vader.
Vader knows what is being asked.
VADER They are clear, my Master.
EMPEROR Then you must go to the Sanctuary Moon and wait for them.
VADER (skeptical) He will come to me?
EMPEROR I have foreseen it.
EMPEROR His compassion for you will be his undoing.
EMPEROR He will come to you and then you will bring him before me.
EMPEROR VADER (bows) As you wish.
EMPEROR The Dark Lord strides out of the throne room.
Han, Luke, Chewie, and the two droids are spread out as they move through the heavy foliage near the clearing where we last saw Leia.
Luke finds Leia's helmet, picks it up with an expression of concern.
Luke!
Luke!
Luke runs with the helmet to where Han has found the charred wreckage of a speeder bike in the grass.
THREEPIO Oh, Master Luke.
LUKE There's two more wrecked speeders back there.
LUKE And I found this.
He tosses the helmet to Han.
THREEPIO I'm afraid that Artoo's sensors can find no trace of Princess Leia.
THREEPIO HAN (gravely) I hope she's alright.
THREEPIO Chewbacca growls, sniffing the air, then, with a bark, pushes off through the foliage.
HAN What, Chewie?
HAN What?
HAN Chewie!
The others rush to keep up with the giant Wookiee.
As he scoots along, Artoo whistles nervously.
The group has reached a break in the undergrowth.
Chewie walks up to a tall stake planted in the ground.
There is a dead animal hanging from it.
HAN Hey, I don't get it.
HAN HAN (cont) Nah, it's just a dead animal, Chewie.
Chewie can't resist.
He reaches toward the meat.
LUKE Chewie, wa-wait!
LUKE Don't!
Too late.
The Wookiee has already pulled the animal from the stake.
SPROOING!
The group finds itself hanging upside down in an Ewok net, suspended high above the clearing.
Artoo lets out a wild series of beeps and whistles, and Chewie howls his regret.
Their bodies are a jumble in the net.
Han removes a Wookiee paw from his mouth.
HAN Nice work.
HAN Great, Chewie!
HAN Great!
HAN Always thinking with your stomach.
LUKE Will you take it easy?
LUKE Let's just figure out a way to get out of this thing.
LUKE Han, can you reach my lightsaber?
HAN Yeah, sure.
Artoo is at the bottommost point in the net.
He extends his cutting appendage and begins slicing at the net.
Han is trying to squeeze an arm past Threepio to get at Luke's lightsaber.
The net continues to spin.
THREEPIO Artoo, I'm not sure that's such a good idea.
THREEPIO It's a very long dro-o- op!!
Artoo has cut through and the entire group tumbles out of the net, crashing to the ground.
As they regain their senses and sit up, they realize they are surrounded by dozens of Ewoks, each brandishing a long spear.
HAN Wha--?
HAN Hey!
HAN Point that thing someplace else.
Han pushes the spear wielded by TEEBO out of his face and a second Ewok warrior comes up to argue with Teebo.
The spear returns to Han's face.
He grabs it angrily and starts to go for his laser pistol.
HAN Hey!
LUKE Han, don't.
LUKE It'll be all right.
The Ewoks swarm through them and confiscate their weapons.
Luke lets them take his lightsaber.
Chewie growls at the furry critters.
LUKE Chewie, give 'em your crossbow.
Artoo and Threepio are just untangling themselves.
Threepio gets free of the net and sits up, rattled.
THREEPIO Oh, my head.
THREEPIO Oh, my goodness!
When the Ewoks see Threepio, they let out a gasp and chatter among themselves.
Threepio speaks to them in their native tongue.
The Ewok nearest him drops his spear and prostrates himself before the droid.
In a moment, all the Ewoks have followed suit.
Chewie lets out a puzzled bark.
Han and Luke regard the bowed creatures in wonder.
The Ewoks begin to chant at Threepio.
LUKE Do you understand anything they're saying?
THREEPIO Oh, yes, Master Luke!
THREEPIO Remember that I am fluent in over six million forms of communication.
HAN What are you telling them?
THREEPIO Hello, I think...
THREEPIO I could be mistaken.
THREEPIO They're using a very primitive dialect.
THREEPIO But I do believe they think I am some sort of god.
Chewbacca and Artoo think that's very funny.
Han and Luke exchange "what next?" looks.
HAN Well, why don't you use your divine influence and get us out of this?
THREEPIO I beg your pardon, General Solo, but that just wouldn't be proper.
HAN Proper?!
THREEPIO It's against my programming to impersonate a deity.
Han moves toward Threepio threateningly.
HAN Why, you--
Several Ewoks' spears are thrust in Han's face at the affront to their god.
The Ewoks move in to protect their god and Han is surrounded by a menacing circle of spears, all aimed at him.
He holds up his hands placatingly.
HAN My mistake.
HAN He's an old friend of mine.
A procession of Ewoks winds through the ever-darkening forest.
Their prisoners - Han, Luke, Chewie, and Artoo - are tied to long poles and wrapped in vines, cocoonlike.
Each pole is carried on the shoulders of several Ewoks.
Behind the captives, Threepio is carried on a litter, like a king, by the remaining creatures.
The procession moves along a shaky, narrow, wooden walkway, high in the giant trees.
It stops at the end of the walkway, which drops off into nothingness.
On the other side of the abyss is a village of mud huts and rickety walkways, attached to the giant trees.
The lead Ewok takes hold of a long vine and swings across to the village square; the other Ewoks follow suit.
The procession winds its way into the village square.
Mother Ewoks gather their babies up and scurry into their huts at the sight of the newcomers.
The group stops before the largest hut.
Han, Luke, Chewie, and Artoo are still bound to their poles.
Han is placed on a spit above what looks like a barbecue pit and the others are leaned against a tree nearby.
Threepio's litter/throne is gently placed near the pit.
He watches with rapt fascination.
Han, Luke, and Chewie are less than fascinated.
HAN I have a really bad feeling about this.
HAN Suddenly all activity stops as LOGRAY, the tribal Medicine Man, comes out of the big hut.
HAN He examines the captives carefully, goes to join Threepio, whose throne has been placed on an elevated platform.
HAN A larger, gray-haired Ewok, CHIEF CHIRPA, is examining Luke's lightsaber with great curiosity.
Logray speaks to Threepio and the assemblage of fuzzy Ewoks, pointing to the prisoners tied to the stakes.
The Ewoks begin filling the pit under Han with firewood.
HAN What did he say?
THREEPIO I'm rather embarrassed, General Solo, but it appears you are to be the main course at a banquet in my honor.
THREEPIO HAN and LUKE Leia!
As she moves toward them, the Ewoks block her way with raised spears.
LEIA Oh!
THREEPIO Your Royal Highness.
Artoo and Chewie chime in with their welcome.
Leia looks at the assembled Ewoks and sighs.
LEIA But these are my friends.
LEIA Threepio, tell them they must be set free.
Threepio talks to Chirpa and Logray, who listen and shake their heads negatively.
The Medicine Man gestures toward the prisoners and barks some orders.
Several Ewoks jump up and pile more wood on the barbecue with vigor.
Leia trades frantic looks with Luke and Han .
HAN Somehow, I got the feeling that didn't help us very much.
LUKE Threepio, tell them if they don't do as you wish, you'll become angry and use your magic.
THREEPIO But Master Luke, what magic?
THREEPIO I couldn't possibly --
LUKE Just tell them.
Threepio speaks to the Ewoks.
The Ewoks are disturbed.
Logray steps forward and challenges Threepio.
Luke closes his eyes and begins to concentrate.
THREEPIO You see, Master Luke; they didn't believe me.
THREEPIO Just...
Now the litter/throne, with Threepio sitting upon it, rises from the ground.
At first Threepio doesn't notice and keeps talking.
THREEPIO ...
THREEPIO as I said they wouldn't.
THREEPIO Wha-wha-what's happening!
THREEPIO Oh!
THREEPIO Oh, dear!
THREEPIO Oh!
The Ewoks fall back in terror from the floating throne.
Now Threepio begins to spin as though he were on a revolving stool, with Threepio calling out in total panic at his situation.
THREEPIO Put me down!
THREEPIO He-e-elp!
THREEPIO Master Luke!
THREEPIO Artoo!
THREEPIO Somebody, somebody, help!
THREEPIO Master Luke, Artoo!
THREEPIO Artoo, quickly!
THREEPIO Do something, somebody!
THREEPIO Oh!
THREEPIO Ohhh!
Chief Chirpa yells orders to the cowering Ewoks.
They rush up and release the bound prisoners.
Luke and Han enfold Leia in a group embrace.
Luke notices the spinning Threepio, with Artoo beeping up at him, and slowly lowers the golden droid and the throne to the ground.
Logray orders the little droid cut down.
Artoo crashes to the ground.
When the Ewoks set him upright, the little droid is fighting mad.
Artoo beeps a blue streak at the nearest Ewok, and begins pursuing him, finally getting close enough to zap him with an electric charge.
The Ewok jumps two feet in the air and runs away, screaming.
A small group of Ewoks surround the giant Wookiee, scratching their heads and marveling at his height.
THREEPIO Oh, oh, oh, oh!
THREEPIO Thank goodness.
LUKE Thanks, Threepio.
LUKE THREEPIO (still shaken) I...I never knew I had it in me.
A glowing fire dances in the center of the spartan, low-ceilinged room, creating a kaleidoscope of shadows on the walls.
Along one side, a group of ten Ewok elders flank Chief Chirpa, who sits on his throne.
The Rebels sit along the walls of the hut, with Threepio between the two groups and Wicket and Teebo off to one side.
Threepio is in the midst of a long, animated speech in the Ewok's squeaky native tongue.
The Ewoks listen carefully and occasionally murmur comments to each other.
Threepio points several times at the Rebel group and pantomimes a short history of the Galactic Civil War, mimicking the explosion and rocket sounds, imitating Imperial walkers.
Throughout the long account, certain familiar names are distinguishable in English: Princess Leia, Artoo, Darth Vader, Death Star, Jedi, Obi- Wan Kenobi.
Artoo begins beeping excitedly at Threepio.
THREEPIO Yes, Artoo.
THREEPIO I was just coming to that.
THREEPIO At the end of it, the Chief, Logray, and the elders confer, then nod in agreement.
THREEPIO The Chief stands and makes a pronouncement.
The drums begin to sound, and all the Ewoks stand with a great cheer and screeches.
HAN What's going on?
LEIA I don't know.
Luke has been sharing the joy with smiling visage, but now something passes like a dark cloud through his consciousness.
The others do not notice.
THREEPIO Wonderful!
THREEPIO We are now a part of the tribe.
Several of the little teddy bears run up and hug the Rebels.
HAN Just what I always wanted.
HAN HAN (chuckles) Well, short help is better than no help at all, Chewie.
HAN Thank you.
HAN Okay.
THREEPIO He says the scouts are going to show us the quickest way to the shield generator.
Chewie barks.
Luke has drifted to the back of the hut.
Now he wanders outside into the moonlight.
Leia notices and follows.
HAN Good.
HAN How far is it?
HAN Ask him.
HAN We need some fresh supplies, too.
HAN And try and get our weapons back.
HAN HAN (cont) And hurry up, will ya?
HAN I haven't got all day.
The walkway is deserted now.
The windows of the little huts glow and flicker from the fires inside.
The sounds of the forest fill the soft night air.
Luke has wandered away from the Chief's hut and stands staring up at the Death Star.
Leia finds him like that.
LEIA Luke, what's wrong?
Luke turns and looks at her a long moment.
LUKE Leia...
LUKE do you remember your mother?
LUKE Your real mother?
LEIA Just a little bit.
LEIA She died when I was very young.
LUKE What do you remember?
LEIA Just...images, really.
LEIA Feelings.
LUKE Tell me.
LEIA She was very beautiful.
LEIA Kind, but...sad.
LEIA Why are you asking me all this?
He looks away.
LUKE I have no memory of my mother.
LUKE I never knew her.
LEIA Luke, tell me.
LEIA What's troubling you?
LUKE Vader is here...now, on this moon.
LUKE LEIA (alarmed) How do you know?
LUKE I felt his presence.
LUKE He's come for me.
LUKE He can feel when I'm near.
LUKE That's why I have to go.
LUKE As long as I stay, I'm endangering the group and our mission here.
LUKE I have to face him.
Leia is distraught, confused.
LEIA Why?
Luke moves close and his manner is gentle.
And very calm.
LUKE He's my father.
LEIA Your father?
LUKE There's more.
LUKE It won't be easy for you to hear it, but you must.
LUKE If I don't make it back, you're the only hope for the Alliance.
Leia is very disturbed by this.
She moves away, as if to deny it.
LEIA Luke, don't talk that way.
LEIA You have a power I--I don't understand and could never have.
LUKE You're wrong, Leia.
LUKE You have that power too.
LUKE In time you'll learn to use it as I have.
LUKE The Force is strong in my family.
LUKE My father has it...I have it...and...my sister has it.
Leia stares into his eyes.
What she sees there frightens her.
But she doesn't draw away.
She begins to understand.
LUKE Yes.
LUKE It's you Leia.
LEIA I know.
LEIA Somehow...I've always known.
LUKE Then you know why I have to face him.
LEIA No!
LEIA Luke, run away, far away.
LEIA If he can feel your presence, then leave this place.
LEIA I wish I could go with you.
LUKE No, you don't.
LUKE You've always been strong.
LEIA But, why must you confront him?
LUKE Because...there is good in him.
LUKE I've felt it.
LUKE He won't turn me over to the Emperor.
LUKE I can save him.
LUKE I can turn him back to the good side.
LUKE I have to try.
LUKE Leia holds back her tears as Luke slowly lets her go and moves away.
LUKE He disappears onto the walkway that leads out of the village.
LUKE Leia, bathed in moonlight, watches him go as Han comes out of the Chief's hut and comes over to her.
LUKE Leia is crying, her body trembling.
LUKE He realizes only now that she is crying.
HAN Hey, what's goin' on?
Leia attempts to stifle her sobs and wipes her eyes.
LEIA Nothing.
LEIA I - just want to be alone for a little while.
LEIA She looks up at him, struggling to control herself.
LEIA I...I can't tell you.
LEIA HAN (loses his temper) Did you tell Luke?
LEIA Is that who you could tell?
HAN Ahhh...
He starts to walk away, exasperated, then stops and walks back to her.
HAN I'm sorry.
LEIA Hold me.
Han gathers her tightly in his protective embrace.
An Imperial shuttle floats down from the Death Star and lands gracefully on the huge platform.
Now, an Imperial walker approaches the platform from the darkness of the forest.
The whole outpost - platform, walkers, military - looks particularly offensive in the midst of this verdant beauty.
Darth Vader walks down the ramp of the shuttle onto the platform, into an elevator, and appears on a ramp on a lower level.
He walks toward another ramp exit and is met by two troopers and a commander with Luke, in binders, at their center.
The young Jedi gazes at Vader with complete calm.
COMMANDER This is a Rebel that surrendered to us.
COMMANDER Although he denies it, I believe there may be more of them, and I request permission to conduct a further search of the area.
The commander extends his hand, revealing Luke's lightsaber.
COMMANDER He was armed only with this.
Vader looks at Luke, turns away and faces the commander, taking the lightsaber from the commander's hand.
VADER Good work, Commander.
VADER Leave us.
VADER Conduct your search and bring his companions to me.
COMMANDER Yes, my Lord.
The officer and troops withdraw.
Vader and Luke are left standing alone in the oddly tranquil beauty of the place.
The sounds of the forest filter in upon them.
VADER The Emperor has been expecting you.
LUKE I know, father.
VADER So, you have accepted the truth.
LURE I've accepted the truth that you were once Anakin Skywalker, my father.
VADER (turning to face him) That name no longer has any meaning for me.
LUKE It is the name of your true self.
LUKE You've only forgotten.
LUKE I know there is good in you.
LUKE The Emperor hasn't driven it from you fully.
LUKE That is why you couldn't destroy me.
LUKE That's why you won't bring me to your Emperor now.
LUKE VADER (indicating lightsaber) I see you have constructed a new lightsaber.
Vader ignites the lightsaber and holds it to examine its humming, brilliant blade.
VADER Your skills are complete.
VADER Indeed, you are powerful, as the Emperor has foreseen.
They stand for a moment, the Vader extinguishes the lightsaber.
LUKE Come with me.
VADER Obi-Wan once thought as you do.
Luke steps close to Vader, then stops.
Vader is still.
VADER You don't know the power of the dark side.
VADER I must obey my master.
LUKE I will not turn...and you'll be forced to kill me.
VADER If that is your destiny.
LUKE Search your feelings, father.
LUKE You can't do this.
LUKE I feel the conflict within you.
LUKE Let go of your hate.
VADER It is too late for me, son.
VADER The Emperor will show you the true nature of the Force.
VADER He is your master now.
Vader signals to some distant stormtroopers.
He and Luke stand staring at one another for a long moment.
LUKE Then my father is truly dead.
Han, Leia, Chewbacca, the droids, Wicket, and another Ewok scout, PAPLOO, hide on a ridge overlooking the massive Imperial shield generator.
At the base of the generator is an Imperial landing platform.
Leia studies the installation.
LEIA The main entrance to the control bunker's on the far side of that landing platform.
LEIA This isn't gonna be easy.
HAN Hey, don't worry.
HAN Chewie and me got into a lot of places more heavily guarded than this.
Wicket and Paploo are chattering away in Ewok language.
They speak to Threepio.
LEIA What's he saying?
THREEPIO He says there's a secret entrance on the other side of the ridge.
The vast fleet hangs in space near a blue planet.
A giant Rebel Star Cruiser is up at the front, but now the Millennium Flacon roars up to a spot ahead of it, tiny in comparison.
Lando is in the pilot seat.
His alien copilot, NIEN NUNB, takes some getting used to in the familiar environs of the Falcon's cockpit.
Lando speaks into his comlink.
LANDO Admiral, we're in position.
LANDO All fighters accounted for.
Proceed with the countdown.
All groups assume attack coordinates.
Lando turns to his weird copilot.
LANDO Don't worry, my friends are down there.
LANDO They'll have that shield down on time...
LANDO or this'll be the shortest offensive of all time.
The copilot flips some switches and grunts an alien comment.
All craft, prepare to jump to hyperspace on my mark.
LANDO All right.
LANDO Stand by.
He pulls a lever, and the stars outside begin to streak.
We are treated to an awesome sight: first the Millennium Falcon, then Ackbar's Star Cruiser, then, in large segments, the huge fleet ROARS INTO HYPERSPACE.
And disappears.
Han, Leia, Chewie, the droids, and their two Ewok guides, Wicket and Paploo, have reunited with the Rebel strike squad.
The entire group is spread through the thick undergrowth.
Below them is the BUNKER that leads into the generator.
Four Imperial scouts, their speeder bikes parked nearby, keep watch over the bunker entrance.
Chewie growls an observation, and Paploo chatters away to Han in Ewok language.
HAN Back door, huh?
HAN Good idea.
HAN HAN (cont) It's only a few guards.
HAN This shouldn't be too much trouble.
LEIA Well, it only takes one to sound the alarm.
LEIA HAN (with self-confident grin) Then we'll do it real quiet-like.
LEIA Threepio explains what is going on to Wicket and Paploo.
LEIA The Ewoks chatter a moment between themselves.
LEIA Then Paploo jumps up and scampers into the underbrush.
Threepio asks Wicket where Paploo went and is given a short reply.
THREEPIO Oh!
THREEPIO Oh, my.
THREEPIO Uh, Princess Leia!
LEIA Quiet.
THREEPIO I'm afraid our furry companion has gone and done something rather rash.
LEIA Oh, no.
Paploo has slipped out of the undergrowth near where the Imperial scouts are lounging.
He silently swings his furry ball of a body onto one of the scout's speeder bikes and begins flipping switches at random.
Suddenly, the bike's engine fires up with a tremendous ROAR.
Paploo grins and continues flipping switches.
The scouts leap up in surprise.
Han, Leia and company watch in distress.
Chewie barks.
HAN (sighs) There goes our surprise attack.
The Imperial scouts race toward Paploo just as his speeder zooms into motion.
Paploo hangs on by his paws and shoots away into the forest.
Look!
Over there!
Stop him!
Three of the Imperial scouts jump on their rocket bikes and speed away in pursuit.
The fourth watches them go from his post at the door.
Han, Leia, and Chewie exchange delighted looks.
HAN Not bad for a little furball.
HAN There's only one left.
HAN You stay here.
HAN We'll take care of this.
Han and the Wookiee nod at each other and slip down toward the bunker.
Threepio moves to stand next to Wicket and Artoo.
THREEPIO I have decided that we shall stay here.
Paploo sails through the trees, more lucky than in control.
It's scary, but he loves it.
When the Imperial scouts pull within sight behind him and begin firing laser bolts, he decides he's had enough.
As he rounds a tree, out of their sight, Paploo grabs a vine and swings up into the trees.
A moment later, the scouts tear under him in pursuit of the still-flying, unoccupied bike.
Han sneaks up behind the remaining Imperial scout, taps him on the shoulder and lets the scout chase him behind the bunker into the arms of the waiting Rebel strike team.
Han returns to the front, and taps out a pattern on the bunker door's control panel.
Everyone stands out of sight, police-style, as the door opens.
Han and Leia peek inside.
No sign of life.
The group enters the bunker silently, leaving one lookout behind.
The elevator opens.
Vader and Luke enter the room alone.
They walk across the dark space to stand before the throne, father and son side by side beneath the gaze of the Emperor.
Vader bows to his Master.
EMPEROR Welcome, young Skywalker.
EMPEROR I have been expecting you.
Luke peers at the hooded figure defiantly.
The Emperor then looks down at Luke's binders.
EMPEROR You no longer need those.
The Emperor motions ever so slightly with his finger and Luke's binders fall away, clattering to the floor.
Luke looks down at his own hands, free now to reach out and grab the Emperor's neck.
He does nothing.
EMPEROR Guards, leave us.
EMPEROR EMPEROR (to Luke) I'm looking forward to completing your training.
EMPEROR In time you will call me Master.
LUKE You're gravely mistaken.
LUKE You won't convert me as you did my father.
The Emperor gets down from his throne and walks up very close to Luke.
The Emperor looks into his eyes and, for the first time, Luke can perceive the evil visage within the hood.
EMPEROR Oh, no, my young Jedi.
EMPEROR You will find that it is you who are mistaken...about a great many things.
VADER His lightsaber.
Vader extends a gloved hand toward the Emperor, revealing Luke's lightsaber.
The Emperor takes it.
EMPEROR Ah, yes, a Jedi's weapon.
EMPEROR Much like your father's.
EMPEROR By now you must know your father can never be turned from the dark side.
EMPEROR So will it be with you.
LUKE You're wrong.
LUKE Soon I'll be dead...and you with me.
The Emperor laughs.
EMPEROR Perhaps you refer to the imminent attack of your Rebel fleet.
Luke looks up sharply.
EMPEROR Yes...I assure you we are quite safe from your friends here.
Vader looks at Luke.
LUKE Your overconfidence is your weakness.
EMPEROR Your faith in your friends is yours.
VADER It is pointless to resist, my son.
VADER EMPEROR (angry) Everything that has transpired has done so according to my design.
VADER Your friends up there on the Sanctuary Moon...
VADER EMPEROR (cont) ...are walking into a trap.
VADER As is your Rebel fleet!
VADER It was I who allowed the Alliance to know the location of the shield generator.
VADER It is quite safe from your pitiful little band.
VADER An entire legion of my best troops awaits them.
Luke's look darts from the Emperor to Vader and, finally, to the sword in the Emperor's hand.
EMPEROR Oh...I'm afraid the deflector shield will be quite operational when your friends arrive.
Han, Leia, Chewie, and the Rebel strike team storm through a door and enter the main control room, taking all of the personnel prisoner.
HAN All right!
HAN Up!
HAN Move!
HAN Come on!
HAN Quickly!
HAN Quickly, Chewie.
The Rebel troops herd the generator controllers away from their panels.
Leia glances at one of the screens on the control panel.
LEIA Han!
LEIA Hurry!
LEIA The fleet will be here any moment.
HAN Charges!
HAN Come on, come on!
HAN THREEPIO (to Wicket) Oh, my!
HAN They'll be captured!
Wicket chatters in Ewok language, and then takes off full steam into the forest.
THREEPIO Wa-wait!
THREEPIO Wait, come back!
THREEPIO Artoo, stay with me.
Inside the bunker, Han looks up from setting charges as an Imperial commander enters.
COMMANDER Freeze!
COMMANDER You Rebel scum.
Han and Leia spin, to find dozens of Imperial weapons trained on them and their cohorts.
A poised force of Imperial troops surround them.
Even more pour into the room, roughly disarming the Rebel contingent.
Han, Leia, and Chewie exchange looks.
They're helpless.
The Death Star and its Sanctuary Moon hang distant in space as the Rebel fleet comes out of hyperspace with an awesome roar.
The Millennium Falcon and several Rebel fighters are at the front as the space armada bears down on its target.
Lando flips switches, checks his screen, and speaks into the radio.
LANDO All wings report in.
WEDGE Red Leader standing by.
Gray Leader standing by.
Green Leader standing by.
WEDGE Lock S-foils in attack positions.
From the bridge of the Rebel Headquarters Frigate, Admiral Ackbar watches the fighters massing outside his viewscreen.
ACKBAR May the Force be with us.
Lando looks worriedly at his alien copilot, Nien Nunb, who points to the control panel and talks to Lando.
LANDO We've got to be able to get some kind of a reading on that shield, up or down.
LANDO Well, how could they be jamming us if they don't know if we're coming.
Lando shoots a concerned look out at the approaching Death Star as the implications of what he's just said sink in.
He hits a switch on his comlink.
LANDO Break off the attack!
LANDO The shield is still up.
I get no reading.
Are you sure?
LANDO Pull up!
LANDO All craft pull up!
The Falcon turns hard to the left.
Out the window the stars and the Death Star move off right.
The Falcon and the fighters of Red Squad veer off desperately to avoid the unseen wall.
Alarms are screaming and lights flashing as the huge ship changes course abruptly.
Other ships in the fleet shoot by outside as the armada tries to halt its forward momentum.
ACKBAR Take evasive action!
ACKBAR Green Group, stick close to holding sector MV-7.
A Mon Calamari controller turns away from his screen and calls out to Ackbar, quite excited.
The Admiral rushes over to the controller.
CONTROLLER Admiral, we have enemy ships in sector 47.
On the screen can be seen the moon, Death Star, and the massive Imperial fleet.
Ackbar moves to the comlink.
ACKBAR It's a trap!
ACKBAR There is much excitement on the bridge as the attack begins.
The Millennium Falcon and several squads of Rebel fighters head into an armada of TIE fighters.
The sky explodes as a fierce dogfight ensues in and around the giant Rebel cruisers.
REBEL PILOT There's too many of them!
LANDO Accelerate to attack speed!
LANDO Draw their fire away from the cruisers.
WEDGE Copy, Gold Leader.
The battle continues around the giant cruisers.
Through the round window behind the Emperor's throne can be seen the distant flashes of the space battle in progress.
EMPEROR Come, boy.
EMPEROR See for yourself.
The Emperor is sitting in his throne, with Vader standing at his side.
Luke moves to look through a small section of the window.
EMPEROR From here you will witness the final destruction of the Alliance, and the end of your insignificant Rebellion.
Luke is in torment.
He glances at his lightsaber sitting on the armrest of the throne.
The Emperor watches him and smiles, touches the lightsaber.
EMPEROR You want this, don't you?
EMPEROR The hate is swelling in you now.
EMPEROR Take your Jedi weapon.
EMPEROR Use it.
EMPEROR I am unarmed.
EMPEROR Strike me down with it.
EMPEROR Give in to your anger.
EMPEROR With each passing moment, you make yourself more my servant.
Vader watches Luke in his agony.
LUKE No!
EMPEROR It is unavoidable.
EMPEROR It is your destiny.
EMPEROR You, like your father, are now mine!
Han, Leia, Chewie, and the rest of the strike team are led out of the bunker by their captors.
The surrounding area, deserted before, is now crowded with two-legged Imperial walkers and hundreds of Imperial troops.
The situation looks hopeless.
STORMTROOPER All right, move it!
STORMTROOPER I said move it!
STORMTROOPER Go on!
From the undergrowth beyond the clearing comes a wild series of beeps and whistles.
And --
THREEPIO Hello!
THREEPIO I say, over there!
THREEPIO Were you looking for me?
Bring those two down here!
STORMTROOPER Let's go!
Artoo and Threepio are standing near one of the big trees.
As six Imperial stormtroopers rush over to take them captive, the two droids duck out of sight behind the tree.
THREEPIO Well, they're on their way.
THREEPIO Artoo, are you sure this was a good idea?
STORMTROOPER Freeze!
STORMTROOPER Don't move!
THREEPIO We surrender.
The stormtroopers come around the tree and find the two droids waiting quietly to be taken.
As the Imperial troops move to do that, however, a band of Ewoks drops down from above and overpowers them.
THREEPIO Ohhh!
THREEPIO Stand back, Artoo.
THREEPIO In the confusion of the battle, Han and Leia break away and dive for the cover of the bunker door as explosions erupt around them.
THREEPIO Han goes to the bunker door control panel.
LEIA The code's changed.
LEIA We need Artoo!
HAN Here's the terminal.
HAN LEIA (into comlink) Artoo, where are you?
HAN We need you at the bunker right away.
HAN Artoo and Threepio are hiding behind a log as the battle ragesaround them.
HAN Suddenly the stubby little astrodroid lets out a series of whistles and shoots off across the battlefield.
HAN Threepio, panicked, runs after him.
THREEPIO Going?
THREEPIO What do you mean, you're going.
THREEPIO But-- but going where, Artoo?
THREEPIO No, what!
THREEPIO Artoo!
THREEPIO Oh, this is no time for heroics.
THREEPIO Come back!
THREEPIO A group of Ewoks have moved a primitive catapult into position.
THREEPIO They fire off a large boulder that hits one of the walkers.
THREEPIO The walker turns and heads for the catapult, blasting away with both guns.
THREEPIO The Ewoks abandon their weapons and flee in all directions.
THREEPIO Just as the walker moves in to stomp the catapult, Ewoks drop vines restraining two huge logs that swing down and smash thewalker's head flat.
THREEPIO Two speeder bikes chase Ewoks through the underbrush.
THREEPIO As the scouts round a tree, they are knocked off their bikes by a vinetied between two trees.
The Falcon and other Rebel fighters are engaged in a ferocious combat with Imperial TIE fighters, the battle raging around thecruisers of the Rebel armada.
Lando is in radio communication with the pilots of the other Rebel squads.
LANDO Watch yourself, Wedge!
LANDO Three from above!
WEDGE Red Three, Red Two, pull in!
Got it!
Three of them coming in, twenty degrees!
WEDGE Cut to the left!
WEDGE I'll take the leader!
WEDGE They're heading for the medical frigate.
Lando steers the Falcon through a complete flip, as his crew fires at the TIEs from the belly guns.
Pressure's steady.
The copilot Nien Nunb chatters an observation.
LANDO Only the fighters are attacking.
LANDO I wonder what those Star Destroyers are waiting for.
The giant Imperial Star Destroyer waits silently some distance from the battle.
The Emperor's huge Super Star Destroyer rests in the middle of the fleet.
Admiral Piett and two fleet commanders watch the battle at the huge window of the Super Star Destroyer bridge.
COMMANDER We're in attack position now, sir.
PIETT Hold here.
COMMANDER We're not going to attack?
PIETT I have my orders from the Emperor himself.
PIETT He has something special planned for them.
PIETT We only need to keep them from escaping.
The Emperor, Vader, and a horrified Luke watch the aerial battle fireworks out the window and on the viewscreens.
Another Rebel ship explodes against the protective shield.
EMPEROR As you can see, my young apprentice, your friends have failed.
EMPEROR Now witness the firepower of this fully armed and operational battle station.
EMPEROR Fire at will, Commander.
Luke, in shock, looks out across the surface of the Death Star to the Rebel fleet beyond.
Controllers pull back on several switches.
Commander Jerjerrod stands over them.
JERJERROD Fire!
A button is pressed, which switches on a panel of lights.
A hooded Imperial soldier reaches overhead and pulls a lever.
A huge beam of light emanates from a long shaft.
Two stormtroopers stand to one side at a control panel.
The giant laser dish on the completed half of the Death Star begins to glow; Then a powerful beams shoots out toward the aerial battle.
The air is thick with giant ships.
In among them, Rebel X-wings dogfight with Imperial TIE fighters.
Now an enormous Rebel cruiser is hit by the Death Star beam and is blown to dust.
The Millennium Falcon roars over CAMERA, followed closely byseveral TIE fighters.
The ship is buffeted by the tremendous explosion of the Rebel cruiser.
Lando and his copilot are stunned by the sight of the Death Star firepower.
LANDO That blast came from the Death Star!
LANDO That thing's operational!
LANDO Home One, this is Gold Leader.
Ackbar stands amid the confusion on the wide bridge and speaks into the comlink.
ACKBAR We saw it.
ACKBAR All craft prepare to retreat.
LANDO You won't get another chance at this, Admiral.
ACKBAR We have no choice, General Calrissian.
ACKBAR Our cruisers can't repel firepower of that magnitude.
LANDO Han will have that shield down.
LANDO We've got to give him more time.
Artoo and Threepio make it to the door, as Han and Leia provide cover fire.
THREEPIO We're coming!
HAN Come on!
HAN Come on!
THREEPIO Oh, Artoo, hurry!
The little droid moves to the terminal and plugs in his computer arm.
A large explosion hits near Artoo, knocking him head over heels, finally landing on his feet.
The stubby astrodroid's head is spinning and smoldering.
Suddenly there is a loud SPROOING and Han and Leia turn around to see Artoo with all his compartment doors open, and all of his appendages sticking out; water and smoke spurt out of the nozzles in his body.
Han rushes to the terminal, as Threepio rushes to his wounded companion.
THREEPIO My goodness!
THREEPIO Artoo, why did you have to be so brave?
HAN Well, I suppose I could hotwire this thing.
LEIA I'll cover you.
Ewoks in handmade, primitive hanggliders drop rocks onto the stormtroopers, divebombing their deadly adversaries.
One is hit in the wing with laser fire and crashes.
A walker lumbers forward, shooting laser blasts at frantic Ewoks running in all directions.
Two Ewoks are struck down by laser blasts.
One tries to awaken his friend, then realizes that he is dead.
The Rebel fleet continues to be picked off, from one side by the Death Star's deadly beam, from the other by the rampaging Imperial Star Destroyers.
Lando steers the Falcon wildly through an obstacle course of floating giants.
He's been yelling into the comlink.
LANDO (desperately) Yes!
I said closer!
Move as close as you can and engage those Star Destroyers at point- blank range.
ACKBAR At that close range, we won't last long against those Star Destroyers.
LANDO We'll last longer then we will against that Death Star...and we might just take a few of them with us.
LANDO The control tower of a Star Destroyer is under attack.
REBEL PILOT She's gonna blow!
I'm hit!
The damaged Y-wing plummets toward the Star Destroyer, and crashes into the control tower, exploding.
Out of the window and on the view screens, the Rebel fleet is being decimated in blinding explosions of light and debris.
But in here there is no sound of battle.
The Emperor turns to Luke.
EMPEROR Your fleet has lost.
EMPEROR And your friends on the Endor moon will not survive.
EMPEROR There is no escape, my young apprentice.
EMPEROR The Alliance will die...as will your friends.
Luke's eyes are full of rage.
Vader watches him.
EMPEROR Good.
EMPEROR I can feel your anger.
EMPEROR I am defenseless.
EMPEROR Take your weapon!
EMPEROR Strike me down with all your hatred, and your journey towards the dark side will be complete.
Luke can resist no longer.
The lightsaber flies into his hand.
He ignites it in an instant and swings at the Emperor.
Vader's lightsaber flashes into view, blocking Luke's blow before it can reach the Emperor.
The two blades spark at contact.
Luke turns to fight his father.
The battle rages on.
Stormtroopers fire on Ewoks with sophisticated weapons while their furry little adversaries sneak up behind the Imperial troopers and bash them over the head with large clubs.
A walker marches through the undergrowth blasting Ewoks as it goes.
An Ewok warrior gives the signal, and a pile of logs is cut loose.
The logs tumble under the walker's feet, causing it to slip and slide until it finally topples over with a great crash.
A scout bike races past and is lassoed with a heavy vine.
The other end of the vine is tied to a tree, and the bike swings around in ever- tightening circles until it runs out of rope and crashes into the trees with a huge explosion.
Chewie swings on a vine to the roof of one of the walkers.
Two Ewoks cling to him.
They land with a thud on the top of the lurching machine, then hang on for dear life.
One of the Ewoks peeks through the window.
Look!
Get him off of there!
The walker pilot opens the hatch to see what's going on.
He is yanked out and tossed overboard before he can scream.
The two Ewoks jump into the cockpit and knock the second pilot unconscious.
The Ewoks are thrown violently as the mighty machine careens out of control.
Outside, Chewie is almost knocked overboard; he sticks his head into the hatch with a series of angry barks.
The Ewoks are too busy and frightened to listen to the Wookiee's complaint.
Chewie slips inside the walker.
Chewbacca's walker moves through the forest, firing laser blasts at unsuspecting stormtroopers, and destroying other Imperial walkers.
The Ewoks shout and cheer as the giant machine helps turn the tide of the battle in their favor.
Han works furiously at the control panel; wires spark as he attempts to hotwire the door.
He motions to Leia, who is blasting away at some stormtroopers.
HAN I think I got it.
HAN I got it!
HAN Han frowns and turns back to the wires again.
HAN Leia exchanges shots with stormtroopers in the bushes, then suddenly cries out in pain, her shoulder hit by a laser blast.
THREEPIO Oh, Princess Leia, are you all right?
HAN Let's see.
LEIA It's not bad.
Freeze!
They freeze.
THREEPIO Oh, dear.
STORMTROOPER Don't move!
Leia holds her laser gun ready, behind Han, out of view of the two stormtroopers moving toward them.
Han and Leia's eyes lock; the moment seems suspended in time.
HAN I love you.
Another shared look between them, as she smiles up at Han.
LEIA I know.
STORMTROOPER Hands up!
STORMTROOPER Stand up!
STORMTROOPER HAN (to Leia) Stay back.
The hatch on top of the walker opens and Chewie sticks his head out and barks triumphantly.
HAN Chewie!
HAN Get down here!
HAN She's wounded!
HAN No, wait....
HAN I got an idea.
Luke and Vader are engaged in a man-to-man duel of lightsabers even more vicious then the battle on Bespin.
But the young Jedi has grown stronger in the interim, and now the advantage shifts to him.
Vader is forced back, losing his balance, and is knocked down the stairs.
Luke stands at the top of the stairs, ready to attack.
EMPEROR (laughing) Good.
Use your aggressive feelings, boy!
Let the hate flow through you.
Luke looks momentarily toward the Emperor, then back to Vader, and realizes he is using the dark side.
He steps back, turns off his lightsaber, and relaxes, driving the hate from his being.
VADER Obi-Wan has taught you well.
LUKE I will not fight you, father.
Vader walks back up the stairs to Luke.
VADER You are unwise to lower your defenses.
Vader attacks, forcing Luke on the defensive.
The young Jedi leaps in an amazing reverse flip up to the safety of the catwalk overhead.
Vader stands below him.
LUKE Your thoughts betray you, father.
LUKE I feel the good in you...the conflict.
VADER There is no conflict.
LUKE You couldn't bring yourself to kill me before, and I don't believe you'll destroy me now.
VADER You underestimate the power of the dark side.
VADER If you will not fight, then you will meet your destiny.
VADER EMPEROR (laughs) Good.
VADER Good.
The two armadas, like their sea-bound ancestors, blast away at each other in individual point-blank confrontations.
A Star Destroyer explodes.
The Rebel victor limps away, its back half alive with a series of minor explosions.
The Rebel cruiser manages to move in next to a second Star Destroyer before it explodes completely, taking the Imperial Star Destroyer with it.
The Falcon and several fighters attack one of the larger Imperial ships.
LANDO Watch out.
LANDO Squad at .06.
REBEL PILOT I'm on it, Gold Leader.
WEDGE Good shot, Red Two.
LANDO Now...come on, Han, old buddy.
LANDO Don't let me down.
Controllers watch the main viewscreen on which a vague figure of an Imperial walker pilot can be seen.
There is a great deal of static and interference.
It's over, Commander.
The Rebels have been routed.
They're fleeing into the woods.
We need reinforcements to continue the pursuit.
The controllers cheer.
Send three squads to help.
Open the back door.
Yes, sir.
As the door to the bunker opens and the Imperial troops rush out, they're surprised to find themselves surrounded by Rebels, their weapons pointed at them.
Ewoks holding bows and arrows appear on the roof of the bunker.
The Imperial troops throw down their guns as Han and Chewie rush inside the bunker with explosive charges.
Han, Chewie, and several troops rush into the control room and plant explosive charges on the control panels and rush out.
HAN Throw me another charge.
Vader stalks the low-ceilinged area on the level below the throne, searching for Luke in the semi-darkness, his lightsaber held ready.
VADER You cannot hide forever, Luke.
LUKE I will not fight you.
VADER Give yourself to the dark side.
VADER It is the only way you can save your friends.
VADER Yes, your thoughts betray you.
VADER Your feelings for them are strong.
VADER Especially for...
Vader stops and senses something.
Luke shuts his eyes tightly, in anguish.
VADER Sister!
VADER So...you have a twin sister.
VADER Your feelings have now betrayed her, too.
VADER Obi-Wan was wise to hide her from me.
VADER Now his failure is complete.
VADER If you will not turn to the dark side, then perhaps she will.
LUKE Never-r-r!
LUKE The Dark Lord is knocked to his knees, and as he raises his sword to block another onslaught, Luke slashes Vader's right hand off at the wrist, causing metal and electronic parts to fly from the mechanical stump.
LUKE Vader's sword clatters uselessly away, over the edge of the platform and into the bottomless shaft below.
LUKE Luke moves over Vader and holds the blade of his sword to the Dark Lord's throat.
LUKE The Emperor watches with uncontrollable, pleased agitation.
EMPEROR Good!
EMPEROR Your hate has made you powerful.
EMPEROR Now, fulfill your destiny and take your father's place at my side!
Luke looks at his father's mechanical hand, then to his own mechanical, black-gloved hand, and realizes how much he is becoming like his father.
He makes the decision for which he has spent a lifetime in preparation.
Luke steps back and hurls his lightsaber away.
LUKE Never!
LUKE I'll never turn to the dark side.
LUKE You've failed, Your Highness.
LUKE I am a Jedi, like my father before me.
The Emperor's glee turns to rage.
EMPEROR So be it...Jedi.
Han and several of the fighters run out of the bunker and race across the clearing.
HAN Move!
HAN Move!
A shock wave knocks them flat as the bunker explodes, followed by a spectacular display as the huge shield-generator radar dish explodes along with the bunker.
Ackbar, sitting in his control chair, speaks into the radio.
ACKBAR The shield is down!
ACKBAR Commence attack on theDeath Star's main reactor.
LANDO We're on our way.
LANDO Red Group, Gold Group, all fighters follow me.
LANDO Told you they'd do it!
The Falcon, followed by several smaller Rebel fighters, heads toward the unfinished superstructure of the Death Star.
Luke stands still, as the Emperor reaches the bottom of thestairs.
The Emperor's laughter has turned to anger.
He raises his arms toward Luke.
EMPEROR If you will not be turned, you will be destroyed.
Blinding bolts of energy, evil lightning, shoot from the Emperor's hands at Luke.
Even in his surprise, the young Jedi tries to use the Force to deflect them.
At first he is half successful, but after a moment the bolts of energy are coming with such speed and power the young Jedi shrinks before them, his knees buckling.
The wounded Vader struggles to his feet, and moves to stand at his master's side.
EMPEROR Young fool...only now, at the end, do you understand.
Luke is almost unconscious beneath the continuing assault of the Emperor's lightning.
He clutches a canister to keep from falling into the bottomless shaft as the bolts tear through him.
EMPEROR Your feeble skills are no match for the power of the dark side.
EMPEROR You have paid the price for your lack of vision.
EMPEROR LUKE (groans) Father, please.
EMPEROR Help me.
Again Vader stands, watching Luke.
He looks at his master, the Emperor, then back to Luke on the floor.
EMPEROR Now, young Skywalker...you will die.
EMPEROR Vader grabs the Emperor from behind, fighting for control of the robed figure despite the Dark Lord's weakened body and gravely weakened arm.
EMPEROR The Emperor struggles in his embrace, his bolt-shooting hands now lifted high, away from Luke.
EMPEROR Now the white lightning arcs back to strike at Vader.
EMPEROR He stumbles with his load as the sparks rain off his helmet and flow down over his black cape.
EMPEROR He holds his evil master high over his head and walks to the edge of the abyss at the central core of the throne room.
EMPEROR With one final burst of his once awesome strength, Darth Vader hurls the Emperor's body into the bottomless shaft.
The Emperor's body spins helplessly into the void, arcing as it falls into the abyss.
Finally, when the body is far down the shaft, it explodes, creating a rush of air through the room.Vader's cape is whipped by the wind and he staggers, and collapses toward the bottomless hole.
Luke crawls to his father's side and pulls him away from the edge of the abyss to safety.
Both the young Jedi and the giant warrior are too weak to move.
Rebel fighters follow the Falcon across the surface of the Death Star to the unfinished portion, where they dive into the superstructure of the giant battle station, followed by many TIE fighters.
WEDGE I'm going in.
LANDO Here goes nothing.
Three X-wings lead the chase through the ever-narrowing shaft, followed by the Falcon and four other fighters, plus TIE fighters who continually fire at the Rebels.
Lights reflect off the pilot's faces as they race through the dark shaft.
LANDO Now lock onto the strongest power source.
LANDO It should be the power generator.
WEDGE Form up.
WEDGE And stay alert.
WEDGE We could run out of space real fast.
The fighters and the Falcon race through the tunnel, still pursued by the TIE fighters.
One of the X-wings is hit from behind and explodes.
LANDO Split up and head back to the surface.
LANDO See if you can get a few of those TIE fighters to follow you.
Copy, Gold Leader.
The Rebel ships peel off pursued by three of the TIE's, while Lando and Wedge continue through the main tunnel.
It narrows, and the Falcon scrapes the side dangerously.
Two other TIE fighters continue to blast away at them.
LANDO That was too close.
Nien Nunb agrees.
The battle between the Rebel and Imperial fleet rages on.
Several cruisers fire at the giant Super Star Destroyer.
ACKBAR We've got to give those fighters more time.
ACKBAR Concentrate all fire on that Super Star Destroyer.
X-wings pilots head across the surface of the huge battleship.
Admiral Piett and a commander stand at the window, looking out to the battle.
They look concerned.
CONTROLLER Sir, we've lost our bridge deflector shield.
PIETT Intensify the forward batteries.
PIETT I don't want anything to get through.
The commander is looking out of the window where a damaged Rebel fighter is out of control and heading directly toward the bridge.
PIETT Intensify forward firepower!
COMMANDER It's too late!
The Rebel pilot screams as his ship hits the Star Destroyer, causing a huge explosion.
The giant battle ship loses control, crashes into the Death Star, and explodes.
There is excitement on the bridge as the battle rages on all sides.
They cheer as the giant Star Destroyer blows up.
Chaos.
For the first time, the Death Star is rocked by explosions as the Rebel fleet, no longer backed against a wall, zooms over, unloading a heavy barrage.
Imperial troops run in all directions, confused and desperate to escape.
In the midst of this uproar, Luke is trying to carry the enormous deadweight of his father's weakening body toward an Imperial shuttle.
Finally, Luke collapses from the strain.
The explosions grow louder as Vader draws him closer.
VADER (a whisper) Luke, help me take this mask off.
LURE But you'll die.
VADER Nothing can stop that now.
VADER Just for once...
VADER let me look on you with my own eyes.
VADER ANAKIN (very weak) Now...go, my son.
VADER Leave me.
LUKE No.
LUKE You're coming with me.
LUKE I can't leave you here.
LUKE I've got to save you.
You already have, Luke.
You were right about me.
Tell your sister...you were right.
LUKE Father...I won't leave you.
LUKE A huge explosion rocks the docking bay.
LUKE Slowly, Luke rises and, half carrying, half dragging the body of his father, stumbles toward a shuttle.
The Millennium Falcon leads a swerving bomb run through the immense superstructure of the half-built Death Star.
The Rebel Star Cruisers outside continually bombard the huge station.
And each direct hit is answered by resonating, chain-reaction explosions within the station itself.
Lando's crew fires away at the pursuing TIE fighters as the dashing Baron of Bespin and his alien copilot home in on the main reactor shaft.
It is awesome.
A lone X-wing is just in front of the Falcon.
WEDGE There it is!
LANDO All right, Wedge.
LANDO Go for the power regulator on the north tower.
WEDGE Copy, Gold Leader.
WEDGE I'm already on my way out.
WEDGE The Falcon heads for the main reactor, and when it is dangerously close, Lando fires the missiles, which shoot out of the Falcon with a powerful roar, and hit directly at the center of the main reactor.
He maneuvers the Falcon out of the winding superstructure just ahead of the continuing chain of explosions.
Ackbar and other Mon Calamari lean on the railing of the bridge, watching the large screen showing the Death Star in the main briefing room.
ACKBAR Move the fleet away from the Death Star.
An Imperial shuttle, with Luke alone in the cockpit, rockets out of the main docking bay as that entire section of the Death Star is blown away.
Finally, just as it looks like the Falcon will not make it, Lando expertly pilots the craft out of the exploding superstructure and whizzes toward the Sanctuary Moon, only a moment before the Death Star supernovas into oblivion.
Lando and Nien Nunb laugh and cheer in relief.
Han and Leia, Chewie, the droids, the Rebel troops, and the Ewoks all look to the sky as the Death Star reveals itself in a final flash of self-destruction.
They all cheer.
THREEPIO They did it!
Han looks town from the sky to Leia, a look of concern on his face.
Leia continues to look at the sky as though listening for a silent voice.
HAN I'm sure Luke wasn't on that thing when it blew.
LEIA He wasn't.
LEIA I can feel it.
HAN You love him, don't you?
Leia smiles, puzzled.
LEIA Yes.
HAN All right.
HAN I understand.
HAN Fine.
HAN When he comes back, I won't get in the way.
She realizes his misunderstanding.
LEIA Oh.
LEIA No, it's not like that at all.
LEIA He's my brother.
Han is stunned by this news.
She smiles, and they embrace.
Luke sets a torch to the logs stacked under a funeral pyre where his father's body lies, again dressed in black mask and helmet.
He stands, watching sadly, as the flames leap higher to consume Darth Vader -- Anakin Skywalker.
In the sky above, fireworks explode and Rebel fighters zoom above the forest.
A huge bonfire is the centerpiece of a wild celebration.
Rebels and Ewoks rejoice in the warm glow of firelight, drums beating, singing, dancing, and laughing in the communal language of victory and liberation.
Lando runs in and is enthusiastically hugged by Han and Chewie.
Then, finally, Luke arrives and the friends rush to greet and embrace him.
They stand close, this hardy group, taking comfort in each other's touch, together to the end.
Rebels and Ewoks join together in dancing and celebration.
The original group of adventurers watch from the sidelines.
Only Luke seems distracted, alone in their midsts, his thoughts elsewhere.
He looks off to the side and sees three shimmering, smiling figures at the edge of the shadows: Ben Kenobi, Yoda, and Anakin Skywalker.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
