THE DEVIL'S ADVOCATE
screenplay by
Jonathan Lemkin and Tony Gilroy
based on the novel by
Andrew Neiderman
REVISED SHOOTING DRAFT January 18, 1997
DEVIL'S ADVOCATE - Rev.
11/2/96
Northern Florida in the midst of a heat wave.
Air conditioners fighting a losing battle.
The gallery is full.
The JUDGE a stern, old hand.
The PROSECUTOR, an efficient man with a good case.
The witness is BARBARA.
She is maybe 13.
She is a witness in a criminal trial.
Her testimony has been carefully rehearsed.
BARBARA ...
BARBARA we go back to our homeroom for dismissal, unless you have a pass for sports or something.
PROSECUTOR And is that what you did on the day in question?
BARBARA No.
BARBARA Mr. Gettys asked me to stay after class.
PROSECUTOR What happened next, Barbara?
BARBARA Mr. Gettys closed the door.
PROSECUTOR Everyone else had gone?
BARBARA Yes.
BARBARA He told me to sit in the chair beside his desk.
MR.
GETTYS, the defendant, is 50.
The very picture of respectability.
His perfect wife and son staunchly enduring this testimony.
PROSECUTOR In your own words, Barbara, can you tell us exactly what happened during the next few minutes?
KEVIN LOMAX.
Defense counsel.
Taking it all in.
BARBARA I told him I was afraid I would miss my bus.
BARBARA He promised I would get to the bus on time if I would help him to do something...
Kevin -- his eyes -- drifting around the courtroom -- taking inventory -- assessing damage --
BARBARA ...
BARBARA Then he put -- before I could say anything -- he placed his hand inside my blouse...
Kevin -- checking the jury and --
BARBARA ...
BARBARA I was so frightened I didn't move.
BARBARA I thought if I was just quiet it would be okay...
Kevin -- checking Gettys -- seeing something that stops him cold --
BARBARA ...
BARBARA Then his other hand went up under -- inside my skirt...
Gettys' hand -- down below the table -- down where no one but Kevin could possibly see it -- Getty's fingers subtly feeling their way along the leg of his chair --
BARBARA ...
BARBARA his hand then, it started, he started, moving back and forth -- farther and farther inside my skirt...
Kevin -- glancing around -- nobody else can see it --
BARBARA ...
BARBARA he said he was testing to see if I had any special feelings, that he wanted to find out what kind of feelings I had...
Gettys' hand -- excited now -- stroking the chair leg -- absently -- involuntarily -- unmistakably sexual --
BARBARA ...
BARBARA I didn't know what to say, I was trying to think of something to say but I was confused and he just kept on -- with his hand -- moving it -- under my dress -- higher and higher...
Kevin is rocked.
Trying not to show it.
BARBARA ...
BARBARA then I, I was asking him to stop but it was like he couldn't hear me -- he just kept on --
Suddenly, Gettys' hand stops moving --
BARBARA -- and then I screamed...
Kevin looks up to find Gettys' eyes waiting for him.
Gettys quickly returns his hand into his lap.
He's been caught -- watching, as Kevin turns away and --
BARBARA ...
BARBARA then he, he got mad and said we would have to try again sometime.
PROSECUTOR And did he try again?
BARBARA Not with me.
PROSECUTOR With friends of yours?
BARBARA Yes.
PROSECUTOR And when you told them what he had done to you, they told you what he had done to them, isn't that true?
BARBARA Yes.
PROSECUTOR I have nothing further.
JUDGE Your witness, Mr. Lomax.
KEVIN Any chance, Your Honor, for a short recess?
Kevin heading quickly away from the courtroom.
Gettys right on his heels.
KEVIN Lloyd, as your attorney, I'm advising you to get the fuck away from me.
GETTYS Why?
GETTYS What are you talking about?
KEVIN The wife.
KEVIN The kid.
KEVIN The outrage.
KEVIN You definitely had me fooled.
GETTYS You're my lawyer!
GETTYS You're here to defend me!
KEVIN You know what I'm thinking?
KEVIN Why don't we put you on the stand and you can jerk off for the judge.
GETTYS You know she's lying.
KEVIN Get the hell out of my way.
Gettys standing aside, as we --
An ancient upstairs facility.
Kevin standing at the mirror.
Frozen there.
Identity crisis.
Morality crisis.
He takes off his wedding ring.
Letting cold water run in the sink.
His eyes never leaving the mirror.
Behind him, the door opens.
A local REPORTER enters, moves to the urinal.
REPORTER Well, hell, there you are.
REPORTER Rumor was you were out wandering in traffic.
KEVIN Not now, Larry.
REPORTER What's the game plan, Kevin?
REPORTER I got a four-thirty deadline.
REPORTER I need a quote.
REPORTER Gimme a quote.
KEVIN Fuck off.
REPORTER 'Mr.
REPORTER Lomax had no comment on today's events.
REPORTER Speculation, however, was widespread that the young lawyer's unblemished string of victories would come to an end in this courtroom.'
Kevin pulls some cold water to his face.
Startled, as THUNDER EXPLODES overhead -- then just as suddenly, becomes nothing more than the urinal flushing...
REPORTER It was a nice run, Kev.
REPORTER Had to close out someday.
REPORTER Nobody wins 'em all.
The Reporter exits.
Kevin alone with the mirror.
And then it's over.
He's made his decision.
Replacing his wedding ring.
Reaching for his jacket, as we --
Kevin walking through.
His game face.
A court officer opening the doors and --
DEVIL'S ADVOCATE - Rev.
11/2/96 6.
Barbara on the stand.
Everyone in place.
KEVIN Math hasn't exactly been your subject this year, has it?
BARBARA No.
KEVIN Any theories on why you've done so poorly in math this year?
BARBARA It's not my fault.
KEVIN Would you say Mr. Gettys is the problem?
KEVIN You're not sure.
KEVIN Have you had any discipline problems in math class this year?
BARBARA No.
KEVIN No?
KEVIN Isn't it true Mr. Gettys has had to talk to you repeatedly about your behavior?
KEVIN Isn't that why he asked you to stay after class?
BARBARA No.
KEVIN Have other teachers ever asked you to stay after class?
BARBARA Once or twice.
KEVIN Did they want to talk about your behavior?
PROSECUTOR Objection.
PROSECUTOR Immaterial.
KEVIN Goes to motive.
DEVIL'S ADVOCATE - Rev.
11/15/96 7.
JUDGE Overruled.
JUDGE You may answer the question.
BARBARA I don't know what the other teachers wanted.
BARBARA You'd have to talk to them.
KEVIN You ever pass notes in class, Barbara?
KEVIN Maybe a note that made fun of Mr. Gettys?
BARBARA No.
KEVIN No?
KEVIN Never called him a 'disgusting pig monster'?
BARBARA No.
Kevin handing out paperwork.
KEVIN Your Honor, I've pre-marked this Defense Exhibit A...
PROSECUTOR Objection, Your Honor, we've had plenty of time for discovery here.
The Judge quickly studying his copy of the note.
JUDGE I'm gonna let this in, Mr. Lomax, I'm also gonna suggest that if you have any other exhibits you present in a timely fashion or not at all.
KEVIN I'm sorry, Barbara, I was wrong, it's 'huge hog beast'.
KEVIN This is your handwriting, isn't it?
BARBARA Yes, but --
DEVIL'S ADVOCATE - Rev.
11/15/96 8.
KEVIN You wrote this in his class.
BARBARA It's a joke.
KEVIN 'He's a huge hog beast.
KEVIN He probably eats a thousand pancakes for breakfast.' You're writing here about Mr. Gettys, aren't you?
BARBARA It was meant to be a joke.
KEVIN Have you ever had a party at your house when your parents were away?
KEVIN Yes or no?
PROSECUTOR Objection.
PROSECUTOR This is way out of...
KEVIN Credibility and bias.
JUDGE Overruled.
JUDGE Answer the question.
BARBARA Yes.
KEVIN The word special came up in your testimony earlier.
KEVIN You claimed that Mr. Gettys asked you whether you had special feelings, if you felt special.
KEVIN Have you ever heard of a game called 'Special Places?'
KEVIN You're under oath, Barbara.
KEVIN A man's career -- his reputation -- his life is on the line.
KEVIN This is not a joke.
KEVIN Have you ever played the game Special Places?
BARBARA Yes.
DEVIL'S ADVOCATE - Rev.
11/15/96 9.
KEVIN Is this game sexual in nature?
KEVIN Is this game sexual in nature?
BARBARA We only played it once.
KEVIN This special party, Barbara, this was the first time you told the story about Mr. Gettys.
BARBARA Yes.
KEVIN I've spoken to the other children who were there that day.
KEVIN Can you think of anything else, Barbara, they might have told me about that party?
PROSECUTOR Objection.
PROSECUTOR Your Honor, if he has other witnesses let him call them.
KEVIN If I need to call those other children, I will.
JUDGE I'm gonna sustain that, Mr. Lomax.
JUDGE Rephrase your question.
KEVIN You threatened those children, didn't you?
BARBARA That's not the way it happened --
KEVIN You told them to falsely claim that Mr. Gettys had hurt them, didn't you?
BARBARA These things did happen!
DEVIL'S ADVOCATE - Rev.
11/15/96 9A.
KEVIN Because if they didn't go along you were going to tell everyone about this special party.
BARBARA They happened to me.
KEVIN So you made up a story.
KEVIN A special story, about a math teacher -- a disgusting pig monster -- you didn't like.
KEVIN That's what really happened, isn't it?
BARBARA I didn't want to be the only one!
BARBARA'S FATHER can take it no longer -- suddenly on his feet -- charging --
BARBARA'S FATHER You son of a bitch!
The bailiff making a diving grab --
KEVIN I have no further questions, Your Honor.
Chaos -- court officers struggling with Barbara's Father and people yelling and Gettys hugging his wife and son and the gavel banging like mad and Kevin just sitting there, staring at the floor, completely drained, emotionally, morally, physically and --
In the back of the room, a man.
He's black.
Elegant.
Amused by the scene.
His name is LEAMON HEATH.
MARY ANN LOMAX leans in behind her husband.
She is a doll.
We love her.
MARY ANN Pack it up, baby.
MARY ANN You need a drink.
It's a rock and roll joint.
Florida style.
But it's early and empty.
Kevin at the bar with Mary Ann, two LAWYER friends, the Reporter and someone's girl friend.
12 shot glasses, two rows of six.
A perfect tequila pour and --
LAWYER #1 In the event we all get drunk and forget, I suggest we frontload the ceremonial bullshit...
LAWYER #1 To the best damn trial lawyer in Alachua County.
Kevin, subdued, watches the rest of them drink.
REPORTER So, Kev, off the record, how's it feel to squeeze a man like Gettys through the door of reasonable doubt?
MARY ANN No.
MARY ANN I told you already, we're not gonna discuss that damn case anymore.
MARY ANN Done.
MARY ANN Am I right?
KEVIN I'll drink to that.
KEVIN No shop talk.
Tequila pours.
As the night goes on.
Drunk frat boys laughing as they exit.
A BAR BAND in the distance.
Kevin done pissing.
Moving for the sink, when he suddenly stops.
Freezes.
A mirror above the sink.
There he is.
The guy that set Gettys free.
HEATH Mr. Lomax?
Kevin turns -- Leamon Heath standing beside him.
HEATH Helluva job today.
HEATH I didn't want to disturb your party.
KEVIN Milton, Chadwick, Waters.
KEVIN Never heard of it.
KEVIN What're you gonna do?
KEVIN Sue me?
HEATH Actually, we were hoping to retain your services.
HEATH We've been following your progress.
KEVIN From New York.
HEATH You've never lost a case.
KEVIN I've had some sympathetic juries.
HEATH That's exactly what we're looking for.
HEATH We want you to come to New York.
HEATH Help us pick a jury.
KEVIN Really.
KEVIN I'll tell you, man.
KEVIN You're pretty damn good.
KEVIN And the card is great.
KEVIN And the black thing -- you being black -- whose idea was that?
KEVIN Paul's?
KEVIN 'Cause that's just brilliant.
KEVIN I'm just not drunk enough yet to fall for it.
HEATH You'd have to start next week.
HEATH All expenses.
HEATH First class travel and lodging.
HEATH You and your wife.
HEATH A lump sum payment, regardless of verdict in the amount of, well...
HEATH Here.
HEATH Take a look.
Kevin takes the check.
Still looking at it, as we --
Two dozen cars parked.
MUSIC and SINGING from inside.
A sign reads:
Inside the church.
Plain and functional.
Poor but faithful.
A trio -- electric guitar, accordion, tambourine -- playing a hymn.
Forty-five voices raised in song.
The tempo is ragged and the pitch shaky, but the feeling is strong.
They mean it.
The CAMERA FINDS -- MRS.
LOMAX.
Kevin's mother.
Forty- six.
Singing her heart out.
A woman with faith, in the presence of her Lord.
The CAMERA FINDS -- Kevin.
In the very back.
Standing in the doorway.
Halfway in.
Halfway out.
Shadow.
Light.
Waiting.
Post-service.
Mrs. Lomax and Kevin walking to her car.
KEVIN It's two weeks at most.
MRS. LOMAX You've never been to New York.
KEVIN Every dog gets a day.
MRS. LOMAX Pick a jury...
MRS. LOMAX I feel the hand of Mary Ann on this adventure.
KEVIN Mom.
MRS. LOMAX New York is not a good idea.
KEVIN Look, how you fixed for cash?
MRS. LOMAX I have my bad feeling.
KEVIN I put a couple hundred in here...
MRS. LOMAX Sounds like more than two weeks.
KEVIN Mary Ann typed out the numbers for you -- phone, the flights -- it's all in there.
MRS. LOMAX Let me tell you about New York.
KEVIN Babylon.
MRS. LOMAX Forewarned is forearmed.
MRS. LOMAX 'Fallen, fallen is Babylon the great.
MRS. LOMAX It has become a dwelling place of demons.' Revelation Eighteen.
MRS. LOMAX Wouldn't hurt you to look it over.
KEVIN Couldn't forget it if I tried.
LOMAX And what happened to Babylon?
KEVIN 'Thou mighty city.
KEVIN In one hour hast thou mighty judgement come.'
MRS. LOMAX 'And the light of a single lamp shall shine in thee no more.'
Kevin gathers her in.
Kissing her good-bye, as we --
Darkness.
Where are we?
A door opens in another room -- VOICES -- KEVIN and MARY ANN.
They're LAUGHING.
Coming in from a big night out.
For an instant -- light -- we glimpse a great hotel suite -- and then --
KEVIN -- wait -- leave 'em off --
MARY ANN -- what are you...
MARY ANN I can't --
KEVIN -- close your eyes -- do it --
More LAUGHTER.
Stumbling shadows moving PAST us and --
KEVIN Okay.
KEVIN Stop.
Kevin behind Mary Ann with his hands over her eyes.
He takes his hands away, but her eyes stay closed...
KEVIN Okay.
KEVIN Open your eyes.
MARY ANN Wow.
The view.
Wham.
The definitive New York skyline.
KEVIN 'Go ahead...'
KEVIN '...
KEVIN bite the Big Apple.'
MARY ANN '...
MARY ANN Rats on the West Side, bed bugs uptown, I can't give it away on Seventh Avenue.
MARY ANN This town don't look good in tatters...'
KEVIN I don't know...
KEVIN looks to me like that dress is in your way.
MARY ANN Why, counselor...
MARY ANN Surely you don't think a small- town girl changes overnight just because a man buys her dinner in the big city.
KEVIN No, ma'am.
KEVIN In fact, I hardly ever think at all.
MARY ANN Well, that's different, then.
MARY ANN You're my kind of guy.
Kevin smiles.
She's taking off the dress.
Babylon.
Six huge courthouses.
All those courtrooms.
Criminal court.
Voire dire.
Potential jurors fill the benches.
A bored judge.
MEISEL, defense counsel, is a sour, New York veteran.
The juror being questioned, a PIE-FACED MAN with bad vision.
DEVIL'S ADVOCATE - Rev.
11/15/96 16.
MEISEL Do you think as a juror you'd be able to set aside any prior opinions you might hold about the savings and loan industry?
MEISEL That was a question, sir.
PIE-FACE What?
PIE-FACE Do I like bankers?
Heath catches Meisel's eye.
Waves him over.
MEISEL Your Honor, may I have a minute to speak with my colleagues.
Kevin and Heath.
And the defendant -- a well-tailored reptilian banker.
Meisel joins them.
Sotto voce.
KEVIN Dump him.
KEVIN While you're at it let's get rid of number six, eight, and I'd say lose number twelve, except the prosecutor's gonna fuck up and do it for us.
MEISEL Number six?
MEISEL You're kidding, right?
MEISEL She's my first choice.
KEVIN She's my first pass.
MEISEL And eight?
MEISEL With the dreadlocks?
MEISEL That's crazy.
MEISEL He's a defendant juror if I ever saw one.
KEVIN You see his shoes?
MEISEL Look, kid, maybe down in Florida you're the next big thing, but this is New York.
MEISEL Manhattan.
MEISEL We're not squeezing oranges here.
KEVIN He polishes those shoes every night.
KEVIN He makes his own clothes.
KEVIN He may look like a brother-with- an-attitude to you, but I see a man who's got a shotgun under his bed and woe betide the creature who steps into his garden.
KEVIN And number six?
KEVIN Your favorite?
KEVIN She's damaged goods.
MEISEL She's a Catholic schoolteacher.
MEISEL She believes in human frailty.
KEVIN No.
KEVIN There's something missing from her.
KEVIN She's wrong.
KEVIN She wants on this jury.
KEVIN Somebody hurt her and she wants revenge.
MEISEL How the hell do you know that?
KEVIN I don't know.
MEISEL Look, either you put a stop to this happy horseshit or I walk.
HEATH Walk.
MEISEL All right.
MEISEL Here's the deal.
MEISEL I lose with your jury?
MEISEL You do the explaining.
The defendant staring a hole into Kevin, as we --
Kevin leaving court.
In no hurry to get home.
He likes it here.
Across the street, a man, one of many passing on the sidewalk.
Except this man turns as Kevin passes.
Watching him.
Seeing something that pleases him.
This is JOHN MILTON.
And now, as Kevin disappears, Milton joins the flow of people heading down into a subway station -- down -- and gone, as we PULL BACK TO --
As day becomes night.
Mary Ann watching TV alone.
Remnants of a room service dinner.
They've been living here for weeks now.
The maids have started to give up.
Kevin enters looking beat.
Grabs a cold french fry.
MARY ANN Your mother called.
MARY ANN She has her bad feeling.
KEVIN Every now and then she gets one right.
MARY ANN What's up?
MARY ANN You okay?
MARY ANN Something's up.
KEVIN They deliberated for thirty-eight minutes.
MARY ANN Oh shit...
DEVIL'S ADVOCATE - Rev.
11/2/96 19.
MARY ANN (CONT'D) Oh, Kevin...
MARY ANN (CONT'D) I'm sorry, honey.
MARY ANN (CONT'D) What the hell did they expect?
MARY ANN (CONT'D) The man is guilty as can be.
MARY ANN (CONT'D) Wasn't a jury anywhere gonna let him off.
KEVIN Yeah.
KEVIN Except one.
MARY ANN Kev....
KEVIN Not fucking guilty.
MARY ANN Omigod...
KEVIN Thirty-eight minutes.
KEVIN My jury.
MARY ANN You did it!
MARY ANN Omigod, Kevin...
KEVIN Put on something that's gonna be easy to take off later.
KEVIN We are going out, girl!
Milton, Chadwick, Waters.
Those words written in stone on the wall.
The decor is stark, dramatic, awesome.
The receptionist is simply stunning.
Kevin, wearing his best suit, walking with Heath.
HEATH Sorry to keep you waiting, but Mr.
HEATH Milton got pinned down in Indonesia a little longer than expected.
HEATH Not bad, huh?
HEATH You can play it cool if you want, but the first time I walked in here, my jaw was on the floor.
The firm offices.
A large central atrium.
Offices rim this space.
Lawyers come in all shapes and sizes.
Assistants -- male and female -- are uniformly attractive.
The HUM of serious BUSINESS in the background.
HEATH We've got forty partners vested at the moment.
HEATH Close to six hundred associates.
HEATH This is the home office, but we've got quite a few international arrangements, so Mr.
HEATH Milton spends a good deal of his time in the air.
HEATH In addition to our corporate clients, we're currently representing about twenty-five foreign countries.
HEATH Mid-East, Balkans, Central America, West Africa.
HEATH Interesting work, but travel intensive.
Kevin slowing as they pass an open doorway --
HEATH He's got you scheduled for fifteen minutes, which is a good sign, so make the most of it...
THROUGH a large window we see a woman pacing her office.
She's wearing a headset and arguing in machine-gun Italian.
She is a goddess.
Her name is CHRISTABELLA.
She is beautiful beyond propriety.
She will also turn out to be a brilliant EUC lawyer.
She turns.
Sees us staring -- like that -- Venetian blinds close tightly.
Heath is now far ahead.
Kevin rushing to catch up --
Kevin about six steps into it when suddenly, he looks down.
Stops.
Completely spooked.
HEATH Gotcha.
HEATH Man, I just love that...
The floor is nothing but glass.
Sixty stories above the world.
A bridge between two skyscrapers.
HEATH I watched a Senator piss his pants right where you're standing.
KEVIN Great.
HEATH He's waiting for you.
HEATH Good luck.
Kevin sucks it up.
Starts walking.
Up ahead, nothing but an open door.
First of all it's round.
And large.
The walls are made of stone.
No windows.
There are dramatic shafts of natural light from above.
Stark and clean to the extreme.
No paper anywhere.
Kevin standing there.
Taking in the space.
MILTON Behind you.
Kevin turns.
There he is.
MILTON Sorry.
MILTON Didn't mean to...
KEVIN No.
KEVIN Please.
KEVIN Kevin Lomax.
MILTON John Milton.
KEVIN Nice to meet you.
MILTON Have we been treating you well?
KEVIN Very well.
KEVIN Thank you.
MILTON Your wife, she's had a good time?
KEVIN She sure has.
KEVIN It's been great.
KEVIN The whole thing's been great.
MILTON Good.
MILTON That's our secret.
MILTON We kill you with kindness.
MILTON What's your secret?
KEVIN I couldn't say.
MILTON You were a prosecutor.
KEVIN Out of law school.
KEVIN Five years in the Jacksonville D.A.'s office.
MILTON Sixty-four straight convictions.
MILTON What a number.
KEVIN I like to be in court.
KEVIN I didn't plea out a lot.
MILTON What's that like?
MILTON One day you're putting them away and the next you're setting them free?
KEVIN Takes a little getting used to.
MILTON Pays better though, doesn't it?
KEVIN Yes it does.
MILTON The math teacher.
MILTON The Gettys case.
MILTON I hear you were brilliant.
KEVIN Prosecutor dropped the ball.
DEVIL'S ADVOCATE - Rev.
11/2/96 23.
MILTON Really.
MILTON So you think your guy was guilty.
KEVIN I didn't say that.
MILTON What did you say?
KEVIN How's this?
KEVIN I began the case with a clear conscience.
MILTON I was sure you had a secret.
KEVIN The men's room.
KEVIN Upstairs men's room in the Duval County courthouse.
KEVIN There's a hole in the wall.
KEVIN Straight through to the next room.
KEVIN I spent five years listening to juries deliberate.
MILTON I love it.
KEVIN Love it all you want, just don't repeat it.
KEVIN I'm not sure the Florida Bar Association would appreciate it.
MILTON You don't really want to go back to Florida, do you?
MILTON Walk with me.
With that, Milton pushes a button.
Huge panel screens open out to:
A reflecting pool.
Water right to the edge.
A narrow walkway straight through the middle.
And we're fifty stories above the city.
The effect is staggering.
DEVIL'S ADVOCATE - Rev.
11/15/96 24.
MILTON What do you think?
MILTON Some people can't handle it.
KEVIN It's peaceful.
MILTON Exactly.
MILTON Fill in the resume.
MILTON Tell me about your family.
MILTON What does your father do?
KEVIN I never got to know my father.
KEVIN He passed away before I was born.
KEVIN My mom raised me.
KEVIN Just the two of us.
MILTON She never remarried?
KEVIN She wasn't married the first time.
MILTON That can't be easy in Gainesville.
KEVIN I don't think it's easy anywhere.
KEVIN Holy shit...
MILTON Little different when you're looking down, isn't it?
MILTON Tell me about her.
MILTON Your mother.
MILTON What's she like?
KEVIN She's a preacher's daughter.
KEVIN She's tough.
KEVIN She's worked in the same poultry plant for as long as I can remember.
KEVIN I think she's up to eight-fifty an hour.
KEVIN She's got a church she really likes, so she's usually either there or they go out, they do a lot of volunteer work.
DEVIL'S ADVOCATE - Rev.
11/15/96 25.
MILTON 'Many are in high places, and of great renown: but mysteries are revealed unto the meek.'
KEVIN So they say.
MILTON Didn't rub off on you?
MILTON The book?
MILTON The church?
KEVIN I'm on parole.
KEVIN Early release for time served.
Suddenly they're quiet.
Silenced by the view.
MILTON Lotta potential clients down there.
MILTON (Sooner or later it all flows through the streets.)
KEVIN You don't have to sell me on New York.
MILTON You like it here, don't you?
KEVIN Are we negotiating?
MILTON Always.
KEVIN Why do you need a criminal department?
MILTON Because our clients break the law just like everyone else and I'm tired of sending their business across the street.
KEVIN Are you offering me a job?
MILTON I'm thinking about it.
MILTON You have the talent.
MILTON I knew that before you got here.
MILTON It's the other thing I wonder about.
DEVIL'S ADVOCATE - Rev.
11/15/96 26.
KEVIN What thing is that?
MILTON Pressure.
MILTON Changes everything.
MILTON Some people, you squeeze them, they focus.
MILTON Some people fold.
MILTON Can you summon your talent at will?
MILTON Can you deliver on deadline?
MILTON Can you sleep at night?
KEVIN When do we talk about money?
MILTON Money's the easy part.
Carnegie Hall.
High off Central Park.
A Mercedes stretch pulls to the curb.
HEATH (V.O.) Mt.
HEATH (V.O.) Sinai Hospital right up the street.
HEATH (V.O.) Some excellent schools.
The driver rushing to open the door.
Heath, Kevin and Mary Ann getting out of the car just as a group of uniformed school children come charging out of the building to meet their bus.
HEATH I doubt it was at the top of his list when Mr. Milton bought the building, but it's a great neighborhood for children.
A stately, pre-war apartment house.
One unique touch; the penthouse rises in a sort of wedding cake design.
Turn of the Century.
Elegant.
Two apartments per floor.
JACKIE HEATH waiting here.
She is black, early thirties, and very, very attractive.
The elevator doors open.
Mary Ann steps out, followed by Kevin and Heath.
JACKIE You must be Mary Ann -- Welcome.
JACKIE I'm Jackie Heath...
MARY ANN It's so sweet of you to come by.
JACKIE Please.
JACKIE We live across the hall.
MARY ANN You're kidding?
HEATH Right here.
KEVIN So it's just two apartments per floor?
JACKIE You didn't tell them about the apartment?
HEATH I thought I'd let it speak for itself.
Opening the door, and we enter --
A dream.
Twelve-foot ceilings.
Huge, oversized rooms.
Crown moldings.
A huge central hallway.
And light.
Kevin and Mary Ann walking through.
Blown away.
HEATH It's what they call a classic eight.
JACKIE We had them paint everything white.
JACKIE Let you see it naked before you pick your palette.
MARY ANN What am I picking?
JACKIE Palette.
JACKIE Your colors.
HEATH I need to warn you about one thing.
HEATH There are going to be some very envious people at the firm.
HEATH These apartments, there aren't many of them, it's really a partner's perk.
HEATH You must've made quite an impression.
JACKIE Took us six years to get in here.
French doors opening.
Kevin walks out.
Mary Ann just behind him.
They stand there, staring at the park.
MARY ANN Are you really this good?
DEVIL'S ADVOCATE - Rev.
11/2/96 29.
KEVIN I sure as hell hope so.
MARY ANN They must want you pretty bad.
KEVIN Look, Mare, I'm only getting behind this if you're on board.
KEVIN You want to go home, I'm with you.
MARY ANN Sure.
MARY ANN Let's go back to Gainesville.
MARY ANN You can keep scrounging for clients and pumping out the basement and I'll keep repossessing cars for Akamian.
MARY ANN Maybe, if we kill ourselves, in about five years we can afford a baby and a weekend shack at Gulf Shores.
MARY ANN Are you shitting me?
She smiles first.
Kevin pulling her toward him, as we --
Incredible and extreme.
Forty people -- SENIOR PARTNERS and department heads -- seated at the table.
They've been going around the table introducing themselves to Kevin.
Nearing the end now --
LAWYER #1 Krasna.
LAWYER #1 Maritime Law.
LAWYER #2 Parvathi Resh.
LAWYER #2 Energy law.
LAWYER #2 I run the Islamic sub-group.
LAWYER #3 Joyce Rensaleer.
LAWYER #3 Mergers and acquisitions.
LAWYER #4 Chan Sanyou.
LAWYER #4 Intellectual property.
BARZOON Eddie Barzoon.
BARZOON Managing Director.
Christabella and another woman running in.
Taking seats quickly.
Christabella beside Kevin.
DEVIL'S ADVOCATE - Rev.
11/2/96 30.
CHRISTABELLA Christabella Adrioli.
CHRISTABELLA Economics.
CHRISTABELLA Primarily G-7 and E.C.
MILTON There you go, Kevin.
MILTON The whole team.
MILTON I'm trying to think how long it's been since we were all together.
MILTON All of us.
MILTON Too long.
MILTON I'm looking around, I know some of you came from very far away to be with us here today.
MILTON It's appreciated.
MILTON This room we're in was built -- architecturally designed -- to promote healthy group dynamics.
MILTON A psychic centrifuge.
MILTON Makes you want to reach out, doesn't it?
MILTON Inclusion.
MILTON Commonality.
MILTON Synergy.
MILTON All that good shit.
MILTON That's what I'm looking for today.
MILTON Because when I hear stories -- the kind of stories I've been hearing -- about backbiting, about partners not working together, departments cutting each other's throats over clients, or worse...
MILTON I feel drained.
MILTON It drains me.
MILTON I feel empty.
MILTON I feel as though I've let you all down.
MILTON We need something.
MILTON A gesture.
MILTON What do I need, Eddie?
BARZOON How about a public flogging?
MILTON Wait a minute.
MILTON I got it.
MILTON It's perfect.
MILTON It's intimate.
MILTON It's quick.
MILTON Doesn't cost a thing.
MILTON There's a power to it.
MILTON What is it?
MILTON Let's hold hands.
MILTON All of us.
MILTON Together.
Milton is first.
Reluctance begins to fold.
DEVIL'S ADVOCATE - Rev.
11/2/96 31.
MILTON Right now.
MILTON Every person at this table -- take the hand of the person on either side...
Kevin finds Christabella's hand at his side.
MILTON You want out of this, Eddie?
BARZOON You've made your point, John.
MILTON You won't hold hands?
MILTON It's important to me, Eddie.
Kevin watching Barzoon fold.
Watching the circle form.
MILTON See.
MILTON See, I feel better already.
Very nice.
Major windows.
Stripped down at the moment, but there's a desk and phone.
HEATH What do you think?
KEVIN I guess it'll do.
PAM Until something better comes along...
In the doorway, PAM GARRETY.
Never married.
Two-pack-a- day habit.
Tough as dirt.
HEATH Kevin Lomax.
HEATH Pam Garrety.
HEATH (CONT'D) Pam was with the Brooklyn D.A.'s office for fourteen years, so she knows her way around the local scene.
HEATH (CONT'D) She'll be your guide.
HEATH (CONT'D) You're gonna be expediting his New York Bar application, right?
PAM In the pipeline.
PAM For now, we'll just have you work pro hac vice.
PAM We've petitioned Florida for a letter of good conduct.
PAM And...
PAM ...
PAM I prepared, at Mr. Milton's request, an overview of the Moyez case.
KEVIN The Moyez case?
Deep ghetto side street.
One of those blocks that have been completely lost.
One whole side of the street has nothing but boarded-up row houses.
A black Town Car pulling through.
Slowing now --
Kevin and his DRIVER peering across the street.
DRIVER I gotta stick with the vehicle.
A storefront botanica.
Insane colors.
Rusted iron grates covering two tiny cataract windows.
A steel door is open.
There's a sick-looking DOG tied to the doorknob; he begins BARKING wildly, as he sees --
Kevin walking from the car.
Suit and tie.
Briefcase.
Turning, as he hears --
DEVIL'S ADVOCATE - Rev.
11/2/96 33.
JUNKIE You get 'em!
JUNKIE Go get 'em, man!
Three JUNKIES camped on the stoop of a burned-out brownstone across the street.
Dull, wasted faces aroused by the DOG'S BARKING --
JUNKIE Tell her turn that shit down!
JUNKIE I know what she's doin'!
JUNKIE That's right!
JUNKIE Tell 'em take that noise back t'Africa 'fore I --
Stopping instantly because -- a WOMAN is standing in the botanica doorway.
Her skin is jet black.
Her eyes are pale blue.
Her hair is white.
She holds a live chicken by its feet.
The DOG is still BARKING so she slaps it.
Hard.
Now there is silence.
KEVIN I'm looking for Phillipe Moyez.
She moves aside.
Kevin enters --
It's dark.
Oil lamps and candles for light.
The air thick with incense.
Jars and bags and boxes are stacked on shelves everywhere.
Powders.
Oils.
Bones.
Skins.
Potions.
Dried herbs.
KEVIN I called this morning, I'm not sure who I spoke with.
KEVIN I'm his lawyer.
KEVIN I have a card...
KEVIN They said he would meet me here.
KEVIN Phillipe Moyez.
WOMAN Bhalla!
WOMAN Bhalla!
Kevin taking a very deep breath, as we --
Darkness.
A door opening above us.
A BOY -- maybe ten -- standing there.
Kevin behind him.
KEVIN Look, I'm not sure I'm making myself clear here.
BOY Moyez.
BOY You need him.
BOY Speak wid him.
The Boy hits the lights.
A naked bulb on the landing below.
Beyond that, darkness.
KEVIN You're saying he's down here?
KEVIN In the basement?
KEVIN In the dark?
BOY Where?
BOY Where you think -- ?
BOY Where you think me taking you?
The Boy, still laughing, starts down the stairs -- into the darkness.
Kevin hesitates.
Sucks it up.
Crouching not to hit his head as he goes down into --
Around the landing -- the Boy still in front of him and -- down -- as another light comes up and the boy moves quickly through the space, turning on lamps here and there.
No furniture.
Mounds of bones.
The walls painted a deep, black red.
Kevin waiting as the last light goes on --
MOYEZ I thought I would recognize you, but I do not.
Kevin, spooked, wheels around --
PHILLIPE MOYEZ squatting in the corner.
Skinny and intense.
His eyes opaque and piercing at the same time.
At once unassuming and terrifying.
A plastic bag of fresh green roots in his lap.
Ghat.
Miraa.
African cocaine.
His teeth black from chewing it.
KEVIN Mr. Moyez?
KEVIN We've never met.
KEVIN I'm a lawyer.
KEVIN I'm here about the animals.
MOYEZ As you wish.
KEVIN I'll be arguing your case with the city.
KEVIN I need to ask you some questions.
KEVIN I've done a little preliminary research -- precedent -- cases in the past that dealt with Santeria and Vou--
MOYEZ No.
MOYEZ This is not Santeria.
MOYEZ We are not Voodoo.
MOYEZ Candomble.
MOYEZ Obeayisne.
MOYEZ None of that.
MOYEZ We are much older.
MOYEZ Before.
MOYEZ Before all of it.
KEVIN Okay.
KEVIN Is there a name?
KEVIN Or...
MOYEZ We have papers.
MOYEZ At your firm.
MOYEZ We have the tax exemption.
KEVIN Okay.
KEVIN I'll get right into that.
KEVIN The animals.
KEVIN Let's start with that, then.
MOYEZ We have an investment in blood.
MOYEZ Think of it as spiritual currency.
Moyez stands.
Starts slowly across the room.
KEVIN Look, Mr. Moyez, I'm going to need your help with this.
MOYEZ Yes.
MOYEZ That's very clear.
KEVIN Perhaps we could start at the beginning?
Moyez, ignoring him, moves to an old refrigerator beside the stairs.
For an instant, the door is open -- just a glimpse.
Meat.
Bags of entrails.
Jars of blood.
Moyez goes to a workbench near the wall --
KEVIN Mr. Moyez?
MOYEZ What is the name of the man who will prosecute us?
KEVIN Merto.
KEVIN Assistant District Attorney Arnold Merto.
MOYEZ Bhalla.
MOYEZ La chemise noire.
MOYEZ Vite!
The Boy already running up the stairs.
The sound of NAILS FALLING onto the workbench --
KEVIN What are you doing, Mr. Moyez?
Moyez stands aside, wiping his hands on his trousers.
A huge beef tongue sits on the bench.
The nails are scattered around it.
MOYEZ You can go now.
MOYEZ You will have all the help I can give you.
Moyez now with a hammer.
And the nail.
Driving it into the tongue.
Kevin backing away, as we --
Video monitor -- FULL FRAME.
DEVIL'S ADVOCATE - Rev.
11/2/96 37.
Hand-held footage of a police raid.
We're running -- through a building -- New York cops -- an animal control officer -- through a door -- voices yelling -- down some steps -- into a back yard -- people standing --
Here -- a scuffle starting -- voices rising -- the camera shaking -- we see Bhalla -- and the Woman -- and --
There -- in the middle, is a goat -- on its knees -- its throat has just been cut -- blood pouring into a pan and Moyez holding its head with one hand -- a knife in the other and this positively orgiastic expression on his face, and on that image, we freeze frame.
48   INT. KEVIN'S OFFICE AND HALL - KEVIN - DAY                       48 with the remote control.
Pam there with him.
A long, sour silence.
PAM What do you think?
KEVIN It's a health code case.
KEVIN And it's a loser.
KEVIN So what's the point?
KEVIN It's a test, right?
PAM Isn't everything?
KEVIN The smart thing to do is make a deal.
KEVIN Plea him out and suppress the tape.
PAM I'm sure the D.A.'s waiting for your call.
KEVIN Yeah, well, let him wait.
KEVIN And you can tell Milton too.
KEVIN I didn't come to New York to plea bargain.
DEVIL'S ADVOCATE - Rev.
11/15/96 38.
Jackie rejecting Mary Ann's color choices.
Law books stacked around.
An associate wheels in a trolley with more books.
Mary Ann eating fried chicken.
She doesn't like the wallpaper.
She's tearing it off, as we --
Kevin working late.
Across the hall Pam is going home.
PAM It's only a health code case.
Bench trial.
No jury.
JUDGE THEO SKLAR and staff.
A.D.A.
MERTO at his seat.
Pam sits with Moyez.
Other than that, it's empty.
A rump roast slaps down onto a table.
KEVIN That's a veal roast, Your Honor.
KEVIN U.S.D.A.
KEVIN approved and stamped.
KEVIN Eight days ago, in Kansas City, two men pushed a calf into a steel frame as a third man fired a high- voltage staple-gun into the animal's skull.
KEVIN Men kill animals and eat their flesh.
KEVIN Phillipe Moyez killed a goat.
KEVIN He killed a goat.
KEVIN And he did it at home, in a manner consistent with his religious beliefs.
KEVIN Now some people may find it bizarre.
DEVIL'S ADVOCATE - Rev.
11/15/96 38A/39.
KEVIN (O.S.CONT'D) It's certainly not a religious practice performed by everyone.
KEVIN (O.S.CONT'D) It's not as common as, say, circumcision.
KEVIN (O.S.CONT'D) It's certainly not as common as the belief that wine is transformed into blood.
KEVIN (O.S.CONT'D) It's not even as common as the handling of poisonous snakes to prove one's faith.
KEVIN (O.S.CONT'D) But Phillipe Moyez isn't two thousand miles away in a stockyard.
KEVIN (O.S.CONT'D) He doesn't use electricity to kill.
KEVIN (O.S.CONT'D) And worst of all...
KEVIN (O.S.CONT'D) Phillipe Moyez is not shrink- wrapped.
Merto begins to cough.
Quietly at first, but...
KEVIN Your Honor, the city timed this police action to catch my client exercising his constitutionally- protected right to religious freedom.
Merto's coughing getting worse as he tries to stop...
JUDGE SKLAR This is a law protecting Kosher butchering.
KEVIN Exactly, Your Honor.
KEVIN And I'd like to move at this time for an immediate directed verdict for dismissal.
Moyez staring a hole in Merto, and the man cannot stop coughing...
JUDGE SKLAR I happen to know a little bit about Kashrut law, Mr. Lomax.
DEVIL'S ADVOCATE - Rev.
11/2/96 40.
KEVIN I'm aware of that, Your Honor, which is why I feel confident in requesting a dismissal.
JUDGE SKLAR Mr. Merto?
Merto can't speak -- wheezing and coughing, as we --
Empty and dark.
Kevin, Moyez and Pam leaving the courtroom.
All smiles.
Moyez shaking his hand and thanking him, and then, from behind them, the sound of one person CLAPPING --
MILTON Bravo, Kevin.
MILTON Bravo.
MILTON Pamela, you're looking lovely.
MILTON Satisfied, Phillipe?
MOYEZ Always.
MILTON Kevin, what can I say?
MILTON Outstanding.
Kevin, trying to look modest and failing, as we --
A street-food stall.
Milton paying for Kevin's eggroll.
And they're walking...
MILTON Best street food in the world.
MILTON Try that.
MILTON Tell me it isn't great.
MILTON New York.
MILTON What a scene, right?
DEVIL'S ADVOCATE - Rev.
11/2/96 41.
MILTON (CONT'D) Guy like Moyez living in that subterranean shithole all the time he's running around with fifteen million dollars in the bank.
KEVIN You gotta be kidding.
MILTON What do you think?
MILTON We're giving you away?
MILTON He's paying us in goat's blood?
MILTON I'm billing you out at four-hundred an hour, my friend.
MILTON I don't see a whole lot of pro bono work in your immediate future.
MILTON Seriously, what I like, you got in there with him.
MILTON Inside the cage.
MILTON That's instinct.
MILTON Can't be taught.
MILTON You gotta hear that on your own.
MILTON It's gotta be in your blood.
MILTON It's molecular.
MILTON I bet I've got five thousand lawyers working around the planet.
MILTON I couldn't name ten -- couldn't name three -- I'd trust with Moyez.
KEVIN So what the hell are they doing?
MILTON What are they doing?
MILTON They're corporate lawyers, what do you think they're doing?
MILTON They're busy reducing life and death to the proper position of a semi- colon.
MILTON They're doing needlepoint.
MILTON Push button battles.
MILTON Push button wars.
MILTON Armies that get so fucking far away from each other they need satellites to tell them who won.
MILTON No pain.
MILTON No sound.
MILTON No smell.
MILTON One big, multinational circle jerk.
MILTON You, on the other hand, you're on the slaughterhouse floor.
MILTON You can't help but smell your clients.
KEVIN I figure you came to court to make sure I didn't fuck this up.
DEVIL'S ADVOCATE - Rev.
11/2/96 42.
MILTON Maybe I did.
MILTON But don't get too cocky.
MILTON No matter how good you are.
MILTON Don't let them see you coming.
MILTON That's the gaff, my friend -- make yourself small.
MILTON Be the hick.
MILTON The cripple.
MILTON The nerd.
MILTON The leper.
MILTON The shit- kicking surfer.
MILTON Look at me -- I've been underestimated from day one.
MILTON Do I look like a master of the universe?
MILTON That's your only weakness as far as I can tell.
KEVIN What's that?
MILTON The look.
MILTON The Florida stud thing.
MILTON 'Scuse me, ma'am, did I leave my boots under your bed?'
KEVIN Never worked a jury didn't have a woman.
MILTON You know what you're missing?
MILTON What I have?
MILTON This beautiful girl she's just fucked me every way she knows how -- we're done -- she's walking to the bathroom -- she turns back -- and there I am.
MILTON It's me.
MILTON And she smiles -- it's like a veil coming down across her face -- and that smile, that's a question mark, because she's looking at me, she's wondering, how did that happen?
MILTON And see, right there, from that moment on, she's got a secret.
MILTON I'm the hand up Mona Lisa's skirt.
MILTON I'm the whisper in Nefertitti's ear.
MILTON I'm a surprise.
MILTON They never see me coming.
MILTON That's what you're missing.
Milton escaping across the street.
KEVIN So why did you come down today?
DEVIL'S ADVOCATE - Rev.
11/2/96 43.
MILTON Because I knew it was gonna be good.
MILTON Because I knew I was gonna like it.
MILTON That you would shine -- that we would take this walk -- that we'd really talk.
MILTON Why I came down?
MILTON You want the truth?
MILTON I'm an aging, hipster plutocrat.
MILTON I came up from nothing.
MILTON From dirt.
MILTON I'm warming my hands on your talent --
MILTON Where's the chicken?
KEVIN What?
A CHINESE MAN sits in a doorway --
MILTON Where's the chicken?
MILTON The chicken that plays tic-tac-toe.
MILTON He used to be right here.
CHINESE MAN No, you passed it.
CHINESE MAN Back that way.
MILTON There's a chicken, he's famous, he plays tic-tac-toe.
MILTON He never loses.
MILTON Hey.
MILTON Like you.
MILTON Right?
MILTON Look, I'm rambling because I'm excited.
MILTON You're in the part of the game I like best.
MILTON The realm of the True Believers.
MILTON You are a believer, aren't you?
KEVIN I believe in the presumption of innocence.
MILTON Better a hundred guilty men go free than a single innocent be executed.
DEVIL'S ADVOCATE - Rev.
11/2/96 44.
KEVIN Something like that.
MILTON No.
MILTON Exactly like that.
MILTON It's faith.
MILTON You're either in or out.
MILTON You can't believe a little bit.
KEVIN I was kidding.
MILTON You're not here to amuse me.
MILTON See, that's why people hate lawyers.
MILTON So many of us have lost our faith.
MILTON Don't let that happen to you.
MILTON Token?
KEVIN Excuse me?
Milton offering a token.
Behind him, the entrance to the Canal Street station --
MILTON Learn the subways, Kevin.
MILTON Use them.
MILTON Stay in the trenches.
Kevin taking the token, as we --
Kevin just coming in from work.
The apartment is starting to come together.
Still not enough furniture, but the sparseness reads as elegance.
KEVIN Mare...
KEVIN Mare...?
MARY ANN You're late...
DEVIL'S ADVOCATE - Rev.
11/2/96 45.
He stops.
In the hallway -- a wall is missing -- sheetrock stacked on the floor -- tools piled around -- a renovation project halted for the night.
KEVIN What's all this?
MARY ANN All what?
Mary Ann up the hall in the bedroom door.
Finishing her makeup for a night out.
MARY ANN Oh, that...
MARY ANN It was gonna be a nursery, but then I remembered you'd have to be home long enough to knock me up, so now I'm thinking of building a law library.
Kevin smiles.
Drops his briefcase.
Drops his pants.
MARY ANN Save the thought.
MARY ANN We were due up there fifteen minutes ago.
She blows him a kiss.
Ducking back into bedroom.
Kevin and Mary Ann in their go-to-meeting clothes.
Going up.
Nervous.
MARY ANN Tell me I can handle this.
KEVIN You can handle this.
MARY ANN Say something nice.
KEVIN Something nice.
MARY ANN Promise me you won't leave me alone in there.
DEVIL'S ADVOCATE - Rev.
11/2/96 46.
KEVIN Promise.
MARY ANN How the hell did we get here?
KEVIN Instinct.
The door opens.
DIANA BARZOON, tonight's hostess, standing there.
DIANA There you are!
DIANA Diana Barzoon, Eddie's wife.
DIANA Come on, you two.
DIANA Everyone can't wait to meet you.
Twice the size of Kevin's place.
Decorated and furnished to the max.
Seventy-five guests and ten in staff.
The crowd is very smart, sleek, and experienced at these sort of things.
Mary Ann's hand squeezing Kevin's just a bit more tightly as Diana leads them into the throng, and we begin --
Faces -- some of them strangers.
Some of them familiar from the conference room scene.
61   KEVIN                                                         61 huddled with Jackie and Mary Ann as Heath brings them drinks from the bar.
62   PAM                                                           62 and two lawyers near the terrace doors -- the smoking section -- talking with nicotine-driven intensity.
DEVIL'S ADVOCATE - Rev.
11/2/96 47.
64   CHRISTABELLA                                                 64 simply walking through the room.
They've found Kevin and Mary Ann.
DIANA I love the eights.
DIANA The entire 'A' line -- such a great shell.
DIANA I do.
DIANA I envy you.
DIANA Starting from scratch.
DIANA Do you have your fabrics yet?
DIANA Tell me you don't.
MARY ANN Not yet.
MARY ANN I don't think so.
DIANA Come with me.
DIANA Instantly.
DIANA I'm borrowing your wife...
BARZOON Be gentle, honey.
BARZOON These are normal people.
Mary Ann giving Kevin a "help me" look as she's dragged into the party --
BARZOON Your first?
KEVIN Excuse me?
BARZOON Is this your first marriage?
Front door -- abuzz -- Milton has just arrived.
DEVIL'S ADVOCATE - Rev.
11/2/96 48.
Across the room, Mary Ann with Jackie and Diana and another wife --
MARY ANN Who is that?
JACKIE My God, girl...
DIANA You haven't met him yet?
MARY ANN Who is he?
Milton -- across the room -- looks over -- he's found them -- already coming toward them -- smiling --
DIANA I swear he can hear us.
JACKIE Hell, he can smell us.
MILTON Mary Ann?
MILTON John Milton...
MILTON I was hoping we'd meet tonight.
MILTON And here you are, already swimming with the sharks.
Even as he says this, he's kissing their smiling cheeks.
Mary Ann looking a little lost, as we --
Kevin talking with another lawyer.
Looking over as Christabella glides through the room.
Milton and Mary Ann sitting together.
Alone.
DEVIL'S ADVOCATE - Rev.
11/2/96 49.
MARY ANN Deadbeats.
MARY ANN I mean, that's what it comes down to.
MARY ANN You can call yourself a finance trainee, or a financial resources adviser, or whatever, you're still spending most of your day trying to hammer car payments out of deadbeats.
MARY ANN No deadbeats here tonight.
MILTON You'd be surprised.
MILTON There's a lot more fear in this room than you'd think.
MARY ANN What do these people have to be afraid of?
MILTON Each other.
MILTON Themselves.
MILTON Why?
MILTON What scares you?
MARY ANN Not knowing who the deadbeats are.
MILTON You'll figure that out.
MILTON There's only one thing worth being frightened of anyway, and that's being alone.
MILTON Truly and finally alone.
MARY ANN Yes.
MARY ANN I think you're right.
MILTON You know what terrifies me?
MILTON Responsibility.
MARY ANN For what?
MILTON For what.
MILTON For you.
MILTON Let's be honest, I've changed your life.
MILTON Changed it forever.
MILTON There's been a seismic shift in your existence and I'm responsible.
MILTON And you've never even met me.
MILTON We're talking for the very first time.
MILTON How insane is that?
DEVIL'S ADVOCATE - Rev.
11/2/96 50.
MARY ANN It's a wonderful opportunity for Kevin.
MILTON Kevin.
MILTON Please.
MILTON I'm not worried about Kevin.
MILTON He buys a few new suits.
MILTON Learns a few new tricks.
MILTON He's there.
MILTON I don't worry about Kevin.
MILTON What about you?
MARY ANN I'm not leaving a lot behind.
MILTON You must have family.
MARY ANN Bad subject.
MARY ANN I haven't spoken to my folks in a long time.
MARY ANN My sister ran all the way to Germany.
MILTON Whoaa...
MILTON I gotta think about that.
MILTON I had you down as daddy's little girl, you know?
MILTON The princess.
MILTON Sugar plum snapshots.
MILTON Pastel bedspreads.
MILTON Cinnamon cookies.
MARY ANN I tell Kevin the only thing worse than not having a father was having mine.
MILTON So you've got a lot at stake here.
MILTON You've made a real commitment.
MARY ANN I guess I have.
MILTON It's not gonna be like Gainesville, but then you know that already.
MARY ANN We're gonna be fine.
MARY ANN It's gonna be great.
DEVIL'S ADVOCATE - Rev.
11/2/96 51.
MILTON If it isn't, will you come to me?
MILTON Let me help?
MILTON I'd feel a lot less responsible.
MILTON Will you do that for me?
MARY ANN Sure.
MILTON The worst vice is advice, right?
MILTON But can I make a suggestion?
MILTON It's about your hair, some people are sensitive, that's why I ask.
MARY ANN No.
MARY ANN I mean, go ahead.
MARY ANN You don't like it?
MILTON You have shoulders nobody can see.
MILTON Pull it back.
MARY ANN You mean, you want me to pull my hair back?
MILTON If I do it, everyone in this room that's pretending not to watch us will assume we're fucking or something.
MILTON Pull back your hair.
MILTON Take a look.
MILTON See.
MILTON That's it.
MILTON Isn't that incredible?
MILTON You need to cut your hair.
MARY ANN You're kidding.
MILTON A woman's shoulders are the frontlines of her mystique.
MILTON And her neck, if she's alive, has the very mystery of a border town.
MILTON It's the no man's land in the battle between mind and body.
MILTON You know, your natural color would really bring out your eyes...
Mary Ann frozen there, as we --
DEVIL'S ADVOCATE - Rev.
11/2/96 52.
Kevin standing at the rail.
He looks over.
Christabella not ten feet away.
CHRISTABELLA Do you have this view?
KEVIN Sorry?
CHRISTABELLA From your terrace, is this your view?
KEVIN Sort of.
KEVIN Not exactly.
KEVIN I'm about twelve floors down.
KEVIN What about you?
CHRISTABELLA No, I live downtown.
CHRISTABELLA This is the family building.
KEVIN Sounds like fun.
KEVIN Downtown, I mean.
KEVIN I'm just getting to know the city.
CHRISTABELLA Is it everything you expected?
KEVIN More.
CHRISTABELLA May we always have more than we expect.
CHRISTABELLA Salute.
KEVIN Amen.
CHRISTABELLA Are you alone?
KEVIN You mean, tonight?
CHRISTABELLA Is your wife a jealous woman?
CHRISTABELLA Silly question.
CHRISTABELLA We're all jealous, aren't we?
CHRISTABELLA DEVIL'S ADVOCATE - Rev.
CHRISTABELLA 11/2/96 53.
CHRISTABELLA (CONT'D) Oh, dear, I'm going to scare you away.
KEVIN I doubt it.
CHRISTABELLA You like to be on top, don't you?
KEVIN Excuse me?
CHRISTABELLA Of the situation.
CHRISTABELLA You prefer to be on top.
KEVIN Depends on the view.
MILTON You know what I see?
MILTON Milton in the doorway.
MILTON He's been watching them.
MILTON I see the future of this law firm.
MILTON Christabella, cara, prestamelo per favore, pe lo riporto piu tardi.
CHRISTABELLA It's a boring party, anyway.
CHRISTABELLA Ciao.
CHRISTABELLA Kevin can't help watching her walk away.
MILTON Look, we gotta talk.
MILTON You grab Heath and Eddie Barzoon and get up to my place right away.
MILTON And let's be quiet about it.
73     OMITTED                                                            73 thru thru
DEVIL'S ADVOCATE - Rev.
11/2/96 54.
Getting louder and wilder.
Mary Ann looking lost.
Searching for Kevin...
He's not here...
not there...
MARY ANN Have you seen Kevin?
Jackie Heath shaking her head no, as Mary Ann continues on through the party.
Silence.
Going up.
Kevin, Heath, and Barzoon.
Mary Ann still looking for Kevin.
Scanning faces.
Stopping as she reaches a door.
Opening it and --
Just enough light to make out two MEN standing across the room.
Silhouettes against the window.
MARY ANN Sorry...
MARY ANN I'm looking for my husband.
The Men -- two vaguely familiar faces from the firm.
MAN #1 Don't think he's here.
Suddenly, a WOMAN's head rises INTO FRAME --
WOMAN It's just us...
MAN #2 But feel free to join in...
And suddenly it's clear, she's walked in on an impromptu menage a trois.
The Woman is kneeling on a table, dress hiked up, ass in the air.
Man #1 fucking her from behind.
Man #2 is getting blown and --
Mary Ann IN SHOT as the woman begins to laugh and the door WIPES the FRAME.
DEVIL'S ADVOCATE - Rev.
11/2/96 55.
The penthouse.
One enormous room.
Grand scale everything.
Otherworldly.
Staggering.
Of special, special interest: a huge Bas Relief dominates an entire wall.
Carved into the marble are human forms -- young, naked bodies swimming in a hypnotic chaos of clouds.
Milton is on the phone.
Two lines going.
The dialogue is unimportant, we'll not understand it anyway -- he's going back and forth between Korean and Russian -- brokering some emergency deal.
Heath is at the bar, mixing drinks.
Barzoon has a cigar.
Kevin just standing there gaping at the space.
KEVIN Is there more to it?
BARZOON Just this room.
KEVIN And a bedroom?
BARZOON No bedroom.
KEVIN Where does he sleep?
HEATH Who said he sleeps?
KEVIN Where does he fuck?
MILTON Everywhere.
BARZOON What's up, John?
MILTON How many hours did we bill Alex Cullen last year?
HEATH Sixteen thousand, two hundred and forty-two.
DEVIL'S ADVOCATE - Rev.
11/2/96 56.
BARZOON What the fuck did he do now?
MILTON Alex Cullen has just been charged with murdering his ex- wife, her stepson, and a maid.
BARZOON When did this happen?
MILTON Just now.
MILTON Tonight.
MILTON I already sent Pam downtown to make bail arrangements.
DEVIL'S ADVOCATE - Rev.
10/22/96 57.
BARZOON They'll fucking crucify him.
BARZOON They'll get in line.
BARZOON I gotta call Meisel...
MILTON No.
MILTON I want Kevin on this case.
BARZOON I hope you're kidding.
BARZOON Alexander Cullen in a Manhattan triple murder?
BARZOON With Kevin?
BARZOON You're dreaming.
MILTON I've shaken hands with every marquee defense attorney in town.
MILTON I take Kevin and I don't look back.
BARZOON You're a great judge of talent, John.
BARZOON You're the master.
BARZOON I just don't see it coming together.
MILTON I want you on board, Eddie.
KEVIN Look, I appreciate the vote of confidence, but maybe Eddie's got a point here.
MILTON We can get this case.
MILTON The man's our client.
BARZOON He's a business client.
MILTON We know him better than he knows himself.
MILTON We have the inside track.
MILTON We have the best damn trial lawyer in the city.
MILTON It's ours to lose.
BARZOON Tell it to Cullen.
MILTON No.
MILTON That's up to Kevin.
With that, the PHONE starts RINGING --
MILTON That's Pam calling...
MILTON Are we fighting for this, or not?
It's late.
Dark.
Kevin tiptoeing through the apartment -- turning the corner and --
MARY ANN You left me there.
MARY ANN I had a fucking panic attack until Jackie told me where you were.
MARY ANN Three hours?
MARY ANN You don't even call?
KEVIN Stop.
KEVIN Reset.
KEVIN I'm upstairs, I'm with Milton and Barzoon and there is a very good possibility that I'm about to catch a triple homicide defendant who also happens to be the largest real estate developer in the city.
KEVIN I had to bail on the party!
MARY ANN You bailed on me!
KEVIN Mare...
KEVIN did you hear me?
MARY ANN I was all by myself!
KEVIN For three whole hours...
KEVIN You gotta be kidding, right?
No, she's leaving.
Kevin left there, alone --
DEVIL'S ADVOCATE - Rev.
11/2/96 59.
A news van whipping up the block.
TIRES SCREECHING as it pulls up beside a construction site where two other news vans are already unloading.
The smell of headlines and --
Two photographers sprinting toward the shell of a high- rise building.
A sign blankets the scaffolding.
Huge, ego-size lettering reads...
CULLEN TOWERS "The Next Great Address"
Looking DOWN FROM fifty stories high, as the media vehicles converge like toys below.
CULLEN (V.O.) ...
CULLEN (V.O.) Look at this, I'm not out twenty minutes, we're running from the goddamn press.
CULLEN (V.O.) Look at those insects down there...
ALEXANDER CULLEN turns back from the edge.
Forty-five.
Tan, grief-stricken, and sleep deprived.
The space is huge and bare.
Unfinished concrete.
Wide, open views.
Kevin, Milton, and Barzoon standing there.
CULLEN ...
CULLEN You may be right, but look at it from my point of view.
CULLEN I'm sure he's a whiz kid.
CULLEN I believe you.
CULLEN But this is my ass we're talking.
CULLEN Jesus, Eddie...
MILTON Alex, you know how this town works.
MILTON You've got enemies you never heard of.
MILTON And now?
MILTON Now you're down?
MILTON I'd prepare for a class-A, New York pig-fuck.
MILTON You're going to have to ask yourself who you really trust.
MILTON Who do you trust, Alex?
DEVIL'S ADVOCATE - Rev.
11/2/96 60.
CULLEN I don't know...
CULLEN I gotta look around.
KEVIN You don't have time to shop, Mr.
KEVIN Cullen.
KEVIN Jury selection started this morning at every breakfast table in the city.
KEVIN You lost round one.
KEVIN This is what people know.
KEVIN They know you and your wife were living separately.
KEVIN They see this maid -- Elucinda -- a sixty-eight-year-old grandmother supporting seven children.
KEVIN And then there's your stepson, a ten-year-old with a bullet in his brain.
KEVIN Those are already powerful images in the mind of the public.
CULLEN I didn't kill anybody.
KEVIN I'm telling you how it looks.
KEVIN You discover the crime.
KEVIN You call it in.
KEVIN You've got blood on your person and clothes, and -- (before Cullen can cut him off) -- and -- your prints are on the murder weapon.
CULLEN How do you know that?
KEVIN There's a second print in blood -- it's a partial of a hand -- on the wall next to th--
CULLEN I have keys!
CULLEN I called the cops from the house!
CULLEN I touched the goddamn wall!
CULLEN I was panicked!
CULLEN I panicked!
KEVIN We need twelve people who can see past all that.
KEVIN I'd get out in front of this fast.
DEVIL'S ADVOCATE - Rev.
11/2/96 61.
CULLEN I panicked!
CULLEN Is that a crime?
CULLEN I touched the wall!
BARZOON He's right, Alex.
BARZOON People need to hear these things.
KEVIN You're not happy tomorrow?
KEVIN The next day?
KEVIN We'll move over.
KEVIN But right now -- this moment -- you need immediate representation.
CULLEN I've got a fourteen-year-old stepdaughter who I care more about than anything in the world.
CULLEN They won't let me call her from downtown.
CULLEN They won't let me talk to her after I'm out.
CULLEN I gotta go deal with that first.
KEVIN We need to issue a statement.
Cullen looks to Milton.
Waiting.
Help me.
MILTON He's a winner, Alex.
MILTON And they'll never see him coming.
CULLEN I'm gonna make some very tough phone calls.
CULLEN Then I'm gonna take a pill and try to get some sleep.
CULLEN My place.
CULLEN Eight A.M. tomorrow.
CULLEN Alone.
CULLEN And you better be every fucking inch as good as you think you are.
A woman with short dark hair -- her back to us -- looking in a shop window.
Her reflection in the glass, it's Mary Ann.
She's cut and colored her hair.
Jackie and Diana already going in and --
DEVIL'S ADVOCATE - Rev.
11/2/96 62.
White wine and couture.
Mary Ann holding a blouse.
MARY ANN This is three thousand dollars.
JACKIE Know what you need to do?
JACKIE Buy it.
JACKIE Wear it once.
JACKIE And then throw it away.
JACKIE That'll loosen you up.
DIANA I say spend it all.
DIANA If you're never gonna see your husband, you might as well have a relationship with his money.
DIANA I swear, if he wasn't afraid of me shooting my mouth off, Eddie would've put a cellulite clause in the pre-nup.
JACKIE Dr. Robert, I'm telling you, he's the miracle man.
JACKIE You've seen my new tits, I mean who does it better than that?
DIANA It's not my tits I'm worried about.
Mary Ann turns.
Jackie beside her.
Topless.
Smiling.
JACKIE Real or not?
JACKIE They look real...
JACKIE They move real...
MARY ANN Must be real.
JACKIE Feel them.
JACKIE Go ahead.
JACKIE That's the ultimate test.
Before Mary Ann can stop her, Jackie is taking her hand, guiding it to her breast, and holding it there.
JACKIE DEVIL'S ADVOCATE - Rev.
JACKIE 11/2/96 63.
JACKIE Feel real?
MARY ANN Yes.
MARY ANN Absolutely.
MARY ANN Real.
JACKIE Dr. Robert.
JACKIE When you're ready.
JACKIE Mary Ann looking away as Jackie walks off.
JACKIE Everything is as it was, and yet different.
JACKIE And then, she turns and sees --
(EFX) Jackie pulling a dress down over her head.
She's taking her time because it's a delicate, clingy...
...
complicated outfit -- turning -- and for one brief moment we see a serpent's head -- disappearing now into the dress as she struggles inside the material -- her body -- the body inside the dress -- transforming -- ribs and spikes and huge moving muscles strain the limits of the material, and then, suddenly, it's over.
Jackie's face appears.
She straightens the seams.
Turning now --
JACKIE What do you think?
JACKIE But Mary Ann is gone.
95     OMITTED                                                         95 thru thru
DEVIL'S ADVOCATE - Rev.
11/2/96 64/65.
Kevin, coming out a door with Heath and an associate.
KEVIN ...
KEVIN first thing -- I need this ASAP -- I want articles, clippings, TV interviews, I want everything you can get on Alex Cullen.
HEATH You better get a semi truck.
Christabella climbing the stairs.
Short skirt.
Great angle.
Halfway up, she stops to fix her stockings.
CHRISTABELLA Enjoying yourself?
KEVIN Sorry.
KEVIN I'm just...
CHRISTABELLA Just what?
CHRISTABELLA Looking?
KEVIN Guilty.
CHRISTABELLA Congratulations on Cullen.
KEVIN Thank you.
CHRISTABELLA What an incredible situation, even if you lose you become a star.
KEVIN What if I win?
CHRISTABELLA If you win...
CHRISTABELLA If you win it's everything.
KEVIN Any advice?
CHRISTABELLA Cullen is a pig.
CHRISTABELLA He's a pig beyond reasonable doubt.
CHRISTABELLA I suggest you keep him as far away from the jury as possible.
KEVIN I'll keep it in mind.
CHRISTABELLA You can look all you want, but I don't fuck married men.
KEVIN What a relief.
KEVIN I was starting to think you were perfect.
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 10/22/96 67.
PAM Kevin...
PAM He turns instantly -- Pamela standing behind him.
PAM Your wife is on the phone.
PAM She sounds upset...
PAM Christabella smiling as Kevin rushes off.
Mary Ann very upset.
Kevin has just come home.
MARY ANN I don't care if they can hear me!
MARY ANN I don't care!
MARY ANN I don't like it here.
MARY ANN And these women, my God...
MARY ANN I mean, I'm seeing things for crissake!
KEVIN You just left them in the store?
MARY ANN Yes!
KEVIN Look, calm down, all right?
KEVIN Listen to me...
KEVIN Mare?
KEVIN First, you do this radical thing with your hair...
MARY ANN You hate it.
KEVIN Stop.
KEVIN I think it's fine.
KEVIN But I also think it's traumatic.
KEVIN You've got the pressure of fitting in with new friends, a new place...
KEVIN add three bottles of wine and --
MARY ANN No!
MARY ANN It wasn't the wine.
MARY ANN It wasn't the wine or my hair or talking to Kathy, because I know that's what you're gonna say --
MARY ANN DEVIL'S ADVOCATE - Rev.
MARY ANN 10/22/96 68.
KEVIN What about Kathy?
MARY ANN What about her?
MARY ANN She's pregnant again.
KEVIN Oh, and that's got nothing to do with it...
MARY ANN Kevin, I never see you anymore.
MARY ANN Now that you've got this big case, it's just only gonna get worse.
MARY ANN I don't know anybody here.
MARY ANN These women scare the living shit out of me.
MARY ANN If you can believe it, I'm actually looking forward to having your mother come and visit.
KEVIN What about the apartment?
MARY ANN Exactly!
MARY ANN You just go out -- you buy a few new suits and you're fine.
MARY ANN I've got this whole place to fill up and I know we have all this money and it's supposed to be fun, but it isn't!
MARY ANN It's like a test!
MARY ANN The whole thing is like one big test!
MARY ANN I'm lonely.
KEVIN Let's make a baby.
MARY ANN Don't tease me.
KEVIN I wouldn't do that.
KEVIN Unless you asked.
MARY ANN You hate my hair, don't you?
His hand moves against her cheek, and then down the back of her neck.
She moves into his body and --
DEVIL'S ADVOCATE - Rev.
10/22/96 68A.
(EFX) Suddenly -- She's Christabella -- right there -- in his arms -- before he can react -- before he can speak -- she finds his mouth and they are kissing and --
Suddenly -- She's Mary Ann -- and he's pulling up her dress and she's helping him and his hand is moving over bare thigh and --
DEVIL'S ADVOCATE - Rev.
11/2/96 69.
(EFX) Suddenly -- She's Christabella unbuttoning her blouse -- and she can't do it fast enough -- still with her mouth on his and his hand between her legs and --
Suddenly -- She's Mary Ann -- flattening against the wall and her blouse is open and --
(EFX) Suddenly -- She's Christabella -- pulling off her bra as his mouth moves over her breasts and his hands are everywhere and the bra is gone and she's tearing at his shirt and he's helping her and her dress is on the floor and there's no rug or anything, but this is where they will fuck because they can't stop themselves and she's on her back on the bare floor and he's kicking away his shoes and she's feeling herself and staring into his eyes and suddenly --
MARY ANN Stop.
MARY ANN Kevin looks like he's been shot.
MARY ANN In the balls.
MARY ANN Where are you?
KEVIN Right here.
KEVIN Mary Ann doesn't look so sure.
Huge.
Opulent.
Kevin and Pamela have been taking notes.
Cullen is exhausted, frustrated.
KEVIN ...
KEVIN because it needs to be clear, Mr. Cullen, because I need to understand exactly what happened -- you're standing there -- you look down -- there's the gun --
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 11/2/96 70.
CULLEN I don't know why I picked it up -- it was before I saw Elucinda's body and then, I mean we've been over this...
KEVIN You kneeled down to pick it up?
CULLEN You work late.
CULLEN You come home.
CULLEN You walk in.
CULLEN Everybody's dead.
CULLEN It's not something you plan for.
KEVIN Back up.
KEVIN Two prints by the gun.
KEVIN Right knee.
KEVIN Right hand.
KEVIN It's a strange move you must've made to pick it up.
CULLEN The blood, I don't know, maybe I was trying to avoid the blood.
KEVIN I'm trying to picture it...
KEVIN Your hand came from inside and underneath.
KEVIN Cullen reaches into his jacket and pulls out a gun.
CULLEN You want to see?
CULLEN Here...
CULLEN I'll fucking show you.
CULLEN Kevin watching Cullen quickly retrieve the gun from the floor with this weird little motion.
CULLEN Okay?
CULLEN Clear?
CULLEN Got it?
KEVIN Whose gun is that, Alex?
CULLEN It's mine.
CULLEN DEVIL'S ADVOCATE - Rev.
CULLEN 11/2/96 71.
KEVIN Are you out of your mind?
KEVIN You're charged in a triple homicide, you're walking around with a forty-five?
CULLEN I've had nine death threats.
KEVIN Give it over.
KEVIN Now.
KEVIN Gimme the gun.
CULLEN I gotta protect myself.
KEVIN That's my job.
KEVIN When the case is over you can have it back.
KEVIN This is a dealbreaker, Alex.
KEVIN Cullen hands him the gun.
KEVIN Okay.
KEVIN Let's wrap it up.
CULLEN So what's next?
KEVIN We need to talk to your assistant.
CULLEN Call her.
KEVIN You feel confident she'll back you on the time.
CULLEN Melissa, yeah.
CULLEN She's okay.
CULLEN She's a real straight arrow.
KEVIN So we're going to talk to her and you're not going to talk to anybody.
KEVIN Okay?
CULLEN No comment.
DEVIL'S ADVOCATE - Rev.
11/2/96 72.
A large, ugly cube.
Daylight through dirty windows.
Kevin alone.
On the table, a large, grey envelope.
Printed on it:
FORENSIC LOG - #546D - STATE VS. ALEX CULLEN Kevin going through a stack of crime scene photographs.
FORENSIC LOG - #546D - STATE VS. ALEX CULLEN Tough stuff.
FORENSIC LOG - #546D - STATE VS. ALEX CULLEN One after another.
FORENSIC LOG - #546D - STATE VS. ALEX CULLEN Three victims.
FORENSIC LOG - #546D - STATE VS. ALEX CULLEN Many angles.
FORENSIC LOG - #546D - STATE VS. ALEX CULLEN We can see their horror in his face.
PANNING ALONG Wall Street.
The whole downtown skyline.
SETTLING finally ON the 60th floor of the law firm building.
Hovering at a distance.
Lights on here and there and --
One window.
Kevin's office.
He and Pamela are talking to a young woman.
This is MELISSA BLOCK, Cullen's assistant and alibi.
We can't hear what they're saying, but it looks to be a collegial meeting.
Kevin and Pam walking Melissa out through the empty reception area.
MELISSA Would my babysitter have to testify?
KEVIN We need her to establish the time you returned home.
MELISSA She doesn't have her green card is why I ask.
MELISSA I don't want her to get in trouble.
MELISSA DEVIL'S ADVOCATE - Rev.
MELISSA 11/2/96 73.
KEVIN Tell you what, Melissa, let's talk to her first.
KEVIN See where she stands and take it from there.
PAM I'll make sure Melissa gets down to the car.
MELISSA Mr. Cullen didn't kill those people.
KEVIN That's why we're all working so hard.
KEVIN As Melissa exits with Pam, Kevin notices two associates carrying boxes far up the hall and we --
Paper shredders.
Half a dozen of them cranking full tilt.
Stacks of files left to go.
Barzoon and six associates working late.
Shirtsleeves and coffee.
BARZOON Okay, Excelsior Insurance, who's handling that?
BARZOON All this has to go.
BARZOON Guatemala, Sudan, Cyprus...
BARZOON Let's stay organized here.
BARZOON Martin, no.
BARZOON Devada Holdings.
BARZOON That's all you're doing.
BARZOON Believe me, it'll take all night.
BARZOON Barzoon stops as he sees Kevin in the doorway.
KEVIN I thought I was the only one working late.
BARZOON So did we.
BARZOON DEVIL'S ADVOCATE - Rev.
BARZOON 11/2/96 74.
KEVIN Good news.
KEVIN We just wrapped up with Cullen's assistant.
KEVIN She looks like a great alibi.
BARZOON What a pleasant surprise.
KEVIN But it looks like you have your hands full.
BARZOON Just a little housekeeping.
BARZOON If they ask, you never saw this.
KEVIN Who would ask?
BARZOON Weaver.
KEVIN Who's that?
BARZOON Justice Department.
BARZOON Weaver Commission.
BARZOON You don't know about Weaver?
KEVIN Sorry.
BARZOON How nice for you.
MILTON Grab your coat, Mr. Lomax...
MILTON Milton in the hall behind Kevin.
MILTON Tickets in hand.
MILTON The night is young.
MILTON Title fight.
MILTON Ringside.
KEVIN I'd have to call Mary Ann...
MILTON Do it on the way.
MILTON DEVIL'S ADVOCATE - Rev.
MILTON 11/2/96 75.
BARZOON You get my message?
MILTON You write beautifully, Eddie.
BARZOON We need to talk.
MILTON Soon.
BARZOON I hope so.
The car half full.
Kevin and Milton standing near the door.
Right behind them, three guys in the midst of an intense conversation in Spanish.
KEVIN So what's this Weaver Commission?
MILTON I don't micro-manage.
MILTON You find the talent and then you delegate.
MILTON Who knows what the hell Eddie's up to.
MILTON He's got a lotta fingers in a lotta pies.
MILTON Suddenly, one of the guys behind them, the biggest of the three, we'll call him BIG GUY, turns back --
BIG GUY What the fuck you looking at?
BIG GUY You fucking deaf or something?
MILTON No.
MILTON I can hear you just fine.
BIG GUY Good, 'cause I want you should get your skinny little ass somewhere down the fucking car away from me.
MILTON I'm not going anywhere.
MILTON Big Guy pulls open his jacket -- a knife in his belt.
KEVIN Oh, shit.
KEVIN John...
KEVIN But Milton doesn't move.
KEVIN He smiles.
MILTON Maricela, the moment you left the apartment she was upstairs with Carlos.
MILTON They're on the pipe right now, my friend.
MILTON They're in the kitchen splitting a jumbo and then he's going to fuck her in the ass, right on your bed, and she's going to like it.
MILTON Big Guy backing away -- into his friends --
BIG GUY Como...?
BIG GUY How do you...?
BIG GUY The SUBWAY RATTLING into the Fourteenth Street station.
MILTON Do yourself a favor and put that knife where it belongs.
MILTON The doors open.
MILTON Big Guy stumbling back -- his friends catching him -- helping him off the train -- looking back, as the doors close and...
MILTON It's like it never happened.
MILTON Milton straightening his cuffs as the train pulls away.
KEVIN What did you say to him?
MILTON I told him if he didn't leave us alone, you were going to kick all three of their asses.
DEVIL'S ADVOCATE - Rev.
11/2/96 77.
Right INTO it.
Red trunks with a huge right hand and blue trunks drops and the Garden goes wild -- five thousand people yelling for blood.
And Milton at ringside, breathing deeply of the vibe and --
KEVIN Get up!
KEVIN Get up, dammit!
KEVIN C'mon!
Blue trunks rises on shaky legs as the BELL RINGS, the round over and the crowd groans back into its seats.
Milton turning as DON KING collars him.
DON KING Look at this sorry shit, you got better seats than me.
MILTON You need a better lawyer.
DON KING Nobody better than you, Johnny.
MILTON Hang on a second...
MILTON Meet my new heavyweight.
MILTON Kevin Lomax.
MILTON Kevin shaking hands with Don King, as we --
Serious flamenco.
Music is loud.
The dancer is fantastic.
Deep reds.
Deep blacks.
Skin.
Duende.
Milton, sitting beside some blonde he's discovered, he's got his jacket off, clapping perfectly to the beat.
Behind him, a large table of ten/fifteen people.
Food and wine to excess.
Laughter and music and...
DEVIL'S ADVOCATE - Rev.
11/2/96 78.
Kevin on a pay phone near the kitchen.
KEVIN And say what?
KEVIN He's the senior partner at the --
KEVIN Mare, you're really starting to piss me off --
KEVIN Yes.
KEVIN I'm having one cigarette.
KEVIN You want me to lie?
KEVIN One cigarette after seven months is not --
KEVIN That's exactly what I'm saying.
KEVIN Go to bed.
KEVIN I have no idea.
KEVIN I told you, he never sleeps.
KEVIN Mare.
KEVIN Stop.
KEVIN The guy pays our bills.
KEVIN The food, the heat, the rent on that enormous fucking apartment we live in.
KEVIN I live there, too!
KEVIN CLICK.
KEVIN The LINE is dead.
KEVIN He looks at the cigarette.
KEVIN Takes a hit.
KEVIN Fuck it.
KEVIN And then his eyes find --
KEVIN The dressing room across the hall.
KEVIN An open door.
KEVIN Inside, a woman, one of the dancers, all but nude, stepping into her dress.
KEVIN A simply perfect body.
KEVIN And then she turns TOWARD us and it's Christabella -- clearly -- for a single moment -- before she slams shut the door.
KEVIN Kevin crosses to the door.
KEVIN Knocks.
KEVIN And again.
KEVIN The door opens.
KEVIN A DANCER standing there.
KEVIN It's not Christabella.
DANCER Can I help you?
DANCER Kevin already backing toward --
Kevin moving toward the Milton table.
Sitting down and just realizing that --
Cullen has joined the party.
He's wasted.
He waves.
DANCER DEVIL'S ADVOCATE - Rev.
DANCER 11/2/96 79.
Milton catching Kevin's eye, smiling as the Blonde slips below the table.
As if nothing were going on.
129    OMITTED                                                         129 thru thru
Dark.
Mary Ann asleep in a chair.
A breeze through the open terrace windows.
Suddenly she wakes.
MARY ANN Kevin?
MARY ANN Silence.
MARY ANN And then, the sound of a BABY CRYING...
Mary Ann rushing through the dark, toward the nursery and the sound of the CRYING -- stopping suddenly at the nursery door --
MARY ANN How...?
MARY ANN What are you...?
A one-year-old child sits naked on the floor amidst the tools and material.
MARY ANN You poor thing...
MARY ANN Mary Ann easing slowly forward.
MARY ANN How did you...
MARY ANN how did you get here?
MARY ANN Are you okay?
MARY ANN Look at you...
MARY ANN hello...
MARY ANN hello...
MARY ANN Where's your mommy?
MARY ANN The baby turns to her voice.
MARY ANN Smiling now.
MARY ANN DEVIL'S ADVOCATE - Rev.
MARY ANN 11/2/96 80.
MARY ANN What are you playing with?
MARY ANN What do you have there?
MARY ANN The baby offers his open hands --
MARY ANN Viscera.
MARY ANN Entrails and blood and slime.
MARY ANN The child's hands full of someone's insides...
MARY ANN ...
MARY ANN Oh, God, no...
MARY ANN The baby raising his hands toward her --
MARY ANN ...
MARY ANN no...
MARY ANN please, God, no --
MARY ANN Stopping suddenly as she looks down at her body.
MARY ANN Her nightgown is covered with blood.
MARY ANN Just starting to scream, as we --
136    OMITTED                                                            136 thru thru
Motion -- Kevin rushing down a hallway -- Heath behind him -- heading for an open door and into --
Mary Ann in bed.
Dead asleep.
Jackie Heath, bedside nurse.
JACKIE Took two seconals to get her out.
KEVIN Milton got his hooks into me.
HEATH Relax.
HEATH We've all been there.
JACKIE Leave her with me.
JACKIE Let her sleep.
JACKIE She'll be out another five, six hours at least.
JACKIE DEVIL'S ADVOCATE - Rev.
JACKIE 11/2/96 81.
KEVIN This transition, it's been really tough on her...
HEATH We're gonna find some names for you.
HEATH Doctors.
HEATH Good people.
HEATH Kevin nods.
HEATH Jackie ushering them out, as we --
New York time transition -- MOS.
Pamela and three other women smoking.
Looking up, as Kevin comes flying out of the building.
PAM Caught me.
KEVIN I've gotta find Cullen.
KEVIN We just got the prosecution discovery package.
PAM That bad?
PAM Kevin just keeps going into --
Kevin needs a taxi -- bingo -- a cab -- dropping off right here -- he's got it -- opening the door and --
CHRISTABELLA Careful...
CHRISTABELLA You'll spoil me for other men.
KEVIN That's what they all say.
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 11/15/96 82.
CHRISTABELLA Heard he finally dragged you out the other night...
CHRISTABELLA Can't believe I missed it.
CHRISTABELLA Kevin watching her go, looking up, seeing the glass bridge high above.
A limousine double-parked outside a brownstone.
Kevin standing there as Cullen comes storming out of the building.
CULLEN I get one supervised hour a week with my stepdaughter.
CULLEN This is it.
CULLEN You better have a great reason to call me out.
KEVIN Your wife, the day she was killed, had lunch with a friend.
KEVIN She says and I quote: 'Alex is fucking around and I can prove it.'
CULLEN Hearsay.
CULLEN Never gets in.
KEVIN Wrong answer.
KEVIN Your prenuptial agreement is on file at the firm.
KEVIN The contract is null and void in the event of marital infidelity.
KEVIN You fuck around, she gets rich.
KEVIN That's a motive, Alex.
KEVIN What do I need to know?
CULLEN Melissa.
CULLEN My assistant.
CULLEN She's not even that good a fuck.
CULLEN DEVIL'S ADVOCATE - Rev.
CULLEN 11/15/96 83.
KEVIN And, on the night in question?
CULLEN I was boning my assistant while my wife was getting shot.
KEVIN I've got to re-interview Melissa.
CULLEN Forget it.
CULLEN We're not telling that story.
KEVIN Juries want honesty.
KEVIN Fuck with that at your peril.
KEVIN Cullen turns -- something more important --
CULLEN Allesandra.
CULLEN Wait...
CULLEN Allesandra emerging from the building looking teary and distraught.
CULLEN Her THERAPIST helping her toward the limo.
KEVIN Arthur...
CULLEN Not now.
THERAPIST Time's up, Mr. Cullen.
CULLEN Allesandra.
CULLEN Please...
CULLEN Kevin watching Cullen rush away, as we --
148    OMITTED                                                             148 thru thru
New York time transition -- MOS.
152    OMITTED                                                             152 thru thru
DEVIL'S ADVOCATE - Rev.
11/15/96 84.
A Towncar pulls up.
Mary Ann, Kevin and Mrs. Lomax emerge.
Just back from dinner.
Two steps and --
A PAPARAZZI photographer nearby --
PAPARAZZI Kevin, hey, how's it going?
PAPARAZZI Can we get a couple shots here?
PAPARAZZI How about a thumbs-up here?
PAPARAZZI What do you say?
PAPARAZZI Kevin reluctantly smiles.
PAPARAZZI Get it over with.
MRS. LOMAX What's he doing?
MARY ANN Kevin's had his picture in the paper.
MARY ANN FEENEY, the doorman, at the ready.
MARY ANN Mary Ann first inside.
MARY ANN Mrs. Lomax lingers a moment watching Kevin have his picture taken.
KEVIN Welcome to Babylon, Ma.
FEENEY Sorry, Mr. Lomax, I thought we'd scared 'em all away...
MRS. LOMAX Always did like to stick his nose in a camera.
FEENEY And how are you, Mrs. Lomax?
FEENEY Did you have a fine dinner?
MRS. LOMAX I surely did.
MRS. LOMAX Are you hungry?
FEENEY No, I'm fine.
FEENEY Thank you.
MILTON Speak of the devil...
MILTON DEVIL'S ADVOCATE - Rev.
MILTON 11/15/96 85/86.
There he is, waiting for the elevator.
With him are Christabella and an Asian woman who is so sexy it hurts.
Kevin off balance from this moment on.
Mary Ann smells the danger.
Everything is awkward.
MILTON I was just telling the Moyez story.
KEVIN Really.
MILTON And is this your mother?
KEVIN Yes.
KEVIN Mom, this is...
MILTON John Milton.
MILTON Nice to meet you.
MRS. LOMAX Alice Lomax.
MRS. LOMAX How do you do?
MILTON Mary Ann...
MILTON I think you've met Christabella, and this is Giselle who's just in from Paris.
MILTON A moment of bullshit superficial greetings and then -- the elevator doors opening and the whole uncomfortable clot of them moving into --
Just enough room.
They ascend.
KEVIN Thanks for the champagne.
MILTON You've very welcome.
MILTON This isn't really your first visit to New York, is it?
KEVIN Yes.
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 11/2/96 87.
GISELLE Cette femme, elle est la mere de l'homme dont vous m'avez parle?
MILTON She can't believe you're his mother.
MILTON You've done one helluva job bringing him up, Mrs. Lomax.
MILTON I'm sure it wasn't easy.
MRS. LOMAX No.
MRS. LOMAX Mrs. Lomax has been staring, and now Milton meets her eyes as the elevator stops and the doors open.
MARY ANN Nice to see you...
CHRISTABELLA Have a lovely evening.
CHRISTABELLA Kevin next out, holding the door, waiting --
KEVIN Mom, we're here...
MRS. LOMAX Yes.
MRS. LOMAX Good night to you.
MRS. LOMAX Mrs. Lomax takes one last look at Milton as she exits.
MILTON Kevin, hang on...
MILTON How's Cullen.
MILTON Everything on beam?
KEVIN That's a long conversation.
KEVIN In the b.g., Mary Ann opening the apartment door and going inside.
KEVIN Mrs. Lomax right behind her.
MILTON Why don't you come on up?
KEVIN Now?
KEVIN Milton smiles.
KEVIN Christabella smiles.
KEVIN Giselle smiles.
KEVIN Let's talk tomorrow.
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 11/2/96 88.
Milton shrugs.
Your loss.
Christabella has her hand on Giselle's ass, working up her skirt --
MILTON You sure?
MILTON Kevin left standing there as the doors close.
158    OMITTED                                                           158 thru thru
Mrs. Lomax, subdued, listening to Kevin and Mary Ann bickering.
MARY ANN That what you're doing when you're working late?
KEVIN What are we talking about?
MARY ANN You know exactly what I'm talking about.
KEVIN That's ridiculous.
MARY ANN I'm going to bed.
MARY ANN 'Night, Alice...
MRS. LOMAX 'Night.
MRS. LOMAX Mary Ann exits.
MRS. LOMAX DEVIL'S ADVOCATE - Rev.
MRS. LOMAX 11/15/96 89.
LOMAX I'm worried about her.
LOMAX You shouldn't fight like that.
KEVIN That's not a fight, Ma, it's marriage.
KEVIN Not exactly your area of expertise.
MRS. LOMAX Are you happy here?
KEVIN What?
MRS. LOMAX Are you happy here?
KEVIN You're kidding, right?
KEVIN Am I happy?
KEVIN Every now and then I look around and I think my mama must be praying awful hard for me, 'cause I died and went to heaven.
KEVIN Am I happy?
MRS. LOMAX You were always running somewhere.
KEVIN I guess I finally got there.
KEVIN Look, I'm sorry about being so busy this week.
KEVIN Maybe Saturday I can get some time off and...
MRS. LOMAX Don't worry on it.
MRS. LOMAX I love you more than anything in the whole world.
MRS. LOMAX You know that, don't you?
KEVIN I love you too, Ma.
KEVIN Kevin turning out the lights, as we --
Newspapers.
Laying on the doorstep.
Headline reads:
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 11/15/96 90.
CULLEN PRE-NUP SHOCKER! Kevin, dressed for work, briefcase in hand, rushing down a cup of coffee, reading the headline and --
KEVIN Shit!
KEVIN The door to the guest room is open.
KEVIN He looks in --
Mrs. Lomax fully dressed.
The bed is made.
Her bag is packed.
KEVIN Mom?
KEVIN Ma, what are you doing?
MRS. LOMAX I'm going home, Kevin.
KEVIN What?
KEVIN What are you talking about?
MRS. LOMAX I don't feel right.
KEVIN You just got here.
KEVIN Look, I'm late and I just got my teeth kicked in on the front page, so I gotta run.
KEVIN We'll talk later.
MRS. LOMAX I have to go, Kevin.
MRS. LOMAX I miss my church.
KEVIN Ma, this is New York, there must be twenty-thousand goddamn churches.
KEVIN Take your pick.
MRS. LOMAX You need to do a better job with Mary Ann.
MRS. LOMAX She's not well.
MRS. LOMAX This place isn't good for her.
MRS. LOMAX DEVIL'S ADVOCATE - Rev.
MRS. LOMAX 11/15/96 91.
KEVIN So stay.
KEVIN Take care of her if you're so concerned!
KEVIN Help me out.
MRS. LOMAX I'll take her home if you let me.
KEVIN This is home.
KEVIN You understand?
KEVIN This is where we live!
KEVIN I'm not going back to Gainesville.
KEVIN Unbelievable.
MRS. LOMAX 'Wide is the gate, and broad is the way that leadeth to temptation.'
KEVIN It's a little early for scripture.
KEVIN I'm going to work.
KEVIN You can do whatever you want.
KEVIN Mrs. Lomax watching him go, as we --
Melissa and Kevin on a bench.
Kids playing.
One of them is hers, but she's not paying much attention at the moment --
MELISSA I can't do it.
MELISSA It's one thing to have an affair with your boss, it's another to have to tell the world in a murder case.
KEVIN We have to bring it out, Melissa.
MELISSA My ex-husband would have a field day with this.
KEVIN A man's life is at stake.
KEVIN You're our whole case.
KEVIN Melissa looking away, as we --
DEVIL'S ADVOCATE - Rev.
11/15/96 92.
Modern.
Empty.
The JUDGE is a WOMAN.
No bullshit.
Barzoon sitting alone at the defense table.
Federal prosecutor MITCHELL WEAVER on his feet.
WEAVER ...
WEAVER there is nothing vague or exploratory about this subpoena request, Your Honor.
WEAVER We're specifically asking for any and all documents relating to Devada Holdings.
WEAVER It's taken six months and seventeen separate motions and we still don't know who's responsible here.
WEAVER We've got a paper trail here that seems to stretch into eternity!
WOMAN JUDGE Mr. Barzoon?
BARZOON Can't turn over what you don't have, Your Honor.
BARZOON We've been conducting a comprehensive search of our records and I'm sorry to say it's a great deal less than Mr. Weaver would suggest.
WEAVER Your Honor, this is outrageous.
WEAVER We need to get in there and seize these documents before there's nothing left!
BARZOON Your Honor, it's exactly these types of insulting accusations --
WOMAN JUDGE Enough.
WOMAN JUDGE Both of you.
WOMAN JUDGE Put it on paper.
WOMAN JUDGE I'll read it.
WEAVER Your Honor...
WEAVER DEVIL'S ADVOCATE - Rev.
WEAVER 10/22/96 93.
But the gavel comes down.
Done.
Barzoon packing up, looks to the back of the room.
Kevin sitting there.
Waiting.
Busy.
Lots of traffic.
Barzoon and Kevin walking.
BARZOON Forget about lunch.
BARZOON This guy Weaver is running me ragged.
BARZOON A REPORTER pulls up alongside -- excited --
REPORTER Kevin.
REPORTER Nancy Osborne, Metro News.
REPORTER How are you?
KEVIN Busy.
REPORTER We had a report of a private plane at Teterboro airport ready to take Alexander Cullen out of the coun --
KEVIN Mr. Cullen is innocent.
KEVIN He's not going anywhere.
KEVIN He's been released on a two million dollar bond.
KEVIN He looks forward to having his day in court.
KEVIN Thank you.
REPORTER Kevin, is there any truth to --
KEVIN I'm in the middle of a meeting.
KEVIN Call my office.
KEVIN Schedule an interview.
KEVIN Or else forget it.
KEVIN Barzoon is getting away.
KEVIN Kevin hustling to catch up.
KEVIN I'm picking a jury tomorrow.
BARZOON You're good at that.
BARZOON DEVIL'S ADVOCATE - Rev.
BARZOON 10/22/96 94.
KEVIN You're not gonna have time to help me on Cullen, are you?
BARZOON No.
BARZOON Just then, Weaver comes rumbling past --
WEAVER Devada Holdings, Eddie.
WEAVER Look in your rearview window, I'm right behind you.
WEAVER Before he can answer -- ANOTHER REPORTER swoops in --
REPORTER #2 Kevin, Chuck Higgery, Action News.
REPORTER #2 Have you spoken with Alex Cullen concerning the D.A.'s report...
REPORTER #2 Kevin turns to see two more REPORTERS jogging over.
REPORTER #3 Kevin, just a statement --
REPORTER #3 And a photographer -- Kevin under siege and --
BARZOON Gotta go.
BARZOON Barzoon escaping as reporters begin to materialize from all sides, and we --
Dark.
Quiet.
Mary Ann in her chair.
She looks like hell.
Eyes red from crying.
Kevin has just come home and found her like this.
MARY ANN I dreamt about this.
MARY ANN Right here.
MARY ANN It's not a dream if it's true.
KEVIN Tell me this is the medication.
MARY ANN You won't stay with me now.
KEVIN Look, let's get you undressed and in the tub.
KEVIN Okay?
MARY ANN You won't stay.
MARY ANN I know you.
MARY ANN You'll leave me now for sure.
MARY ANN Get-away-from-me!
KEVIN Okay.
KEVIN I'm confused.
KEVIN Why?
KEVIN What is it now?
KEVIN What the fuck is it today, Mare?
KEVIN I swear to God, I'm calling this doctor, I'm gonna find out what the hell they're giving you.
MARY ANN They took my ovaries.
MARY ANN I told you!
MARY ANN My sisters have seven children between them.
MARY ANN My mother had Derek when she was forty-five.
MARY ANN You could set a clock by my periods.
KEVIN What are you talking about?
MARY ANN I can't have children!
KEVIN Says who?
MARY ANN The doctor!
MARY ANN The other doctor.
MARY ANN I was there today.
MARY ANN Non-specific ovarian failure.
KEVIN That's ridiculous.
KEVIN The PHONE begins to RING across the room.
MARY ANN I know you.
MARY ANN You'll leave me.
MARY ANN DEVIL'S ADVOCATE - Rev.
MARY ANN 11/2/96 96.
KEVIN Mary Ann...
MARY ANN It's these monsters, Kevin.
MARY ANN I dreamt this...
MARY ANN The PHONE keeps RINGING.
MARY ANN Kevin will finally pull away.
MARY ANN Answering the phone O.S., quietly conducting business as Mary Ann falls apart.
Kevin on a cell phone walking with Milton.
KEVIN Uh huh.
KEVIN For sleep.
KEVIN And she can take that during the day?
KEVIN No, she won't be driving.
KEVIN I'm gonna have the pharmacy call you right back.
KEVIN Thanks.
KEVIN He thinks, he's not sure, he thinks it could be some kind of hormonal imbalance.
MILTON I'm taking you off the case.
KEVIN What?
MILTON I want you to drop this case.
KEVIN This case?
KEVIN Cullen?
KEVIN John, I've got a jury showing up this morning.
MILTON Do you love this woman?
KEVIN Yes.
KEVIN Of course I do.
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 10/22/96 97.
MILTON Kevin, she's sick.
MILTON Everyone will understand.
MILTON I'll understand.
KEVIN What about Cullen?
MILTON We'll find someone new.
MILTON You consult.
MILTON You live to fight another day.
KEVIN I put together a great jury.
MILTON It's a disappointment.
MILTON We all have them.
MILTON Embrace it.
MILTON Use it.
MILTON You move on.
KEVIN Hang on, we gotta talk about this.
MILTON What's to talk?
MILTON It's your wife, man.
MILTON And she's very sick.
MILTON And that's gotta come first.
MILTON Are you telling me the possibility of leaving the case has never crossed your mind?
KEVIN You know what scares me?
KEVIN I quit the case.
KEVIN She gets better.
KEVIN And I hate her for it.
KEVIN I don't want to resent her, John.
KEVIN I've got a winner here.
KEVIN I gotta nail this fucker down, do it fast, and put it behind me.
KEVIN Just get it done.
KEVIN Then put all my energy into her.
MILTON I guess you have thought about it.
MILTON I stand corrected.
DEVIL'S ADVOCATE - Rev.
11/15/96 98.
Packed.
JUDGE ARMAND POE presiding.
Cullen seated with Kevin and Pam.
The jury in their box.
And prosecutor FRANK BROYGO on his feet, just wrapping up his opening statement --
BROYGO ...
BROYGO And when all that evidence is laid before you, when all these pieces weave together, you will conclude -- you will know -- that Alexander Cullen is guilty of murdering three people in cold blood with malice aforethought.
BROYGO Done.
BROYGO The courtroom is silent.
BROYGO The jury liked him.
JUDGE POE Mr. Lomax...
JUDGE POE We can break for lunch now, or you can do a stop and start...
KEVIN If it's a choice, I'll go now.
KEVIN I won't be as long as Mr. Broygo.
JUDGE POE Proceed.
KEVIN We just spent our morning listening to Mr. Broygo talk about his 'evidence'.
KEVIN What he neglected to tell you is what this case is really about.
KEVIN He left out the most important fact of all: Alex Cullen was somewhere else when these murders took place.
KEVIN Now, Alex Cullen has done a lot of things I don't like.
KEVIN He's been a terrible husband to all three of his wives.
KEVIN He's been a destructive force in the lives of his step-children.
KEVIN He's cheated the city.
KEVIN His partners.
KEVIN His employees.
KEVIN He's paid hundreds of thousands of dollars in penalties and fines over the years.
KEVIN I don't like those things.
KEVIN I don't expect you to like them.
KEVIN There will be other things during the course of this trial that you will hear about and like even less.
KEVIN But this isn't a popularity contest.
KEVIN It's a murder trial and Alex Cullen hasn't killed anybody.
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 11/15/96 99.
KEVIN (CONT'D) The state is going all out here.
KEVIN (CONT'D) They've got a whole team over there.
KEVIN (CONT'D) They're throwing everything but the kitchen sink at this case.
KEVIN (CONT'D) I need one thing from you.
KEVIN (CONT'D) That's it.
KEVIN (CONT'D) One thing.
KEVIN (CONT'D) I need you to ask yourself, 'Is not liking this man reason enough to convict him of murder?'
KEVIN (CONT'D) Enjoy your lunch.
KEVIN (CONT'D) We'll talk again.
KEVIN (CONT'D) Stunned silence, and then --
Kevin thrown back against a wall --
CULLEN What the fuck was that?
CULLEN Are you out of your fucking mind?
CULLEN They fucking hate me!
CULLEN Kevin -- one push -- Cullen sent flying.
KEVIN Listen to me like you've never listened to anybody before.
KEVIN I'm going to bust my ass to make sure they hate you.
KEVIN Because as long as you're out boning Melissa, you're not home killing your wife.
CULLEN Why didn't you tell me before?
KEVIN Then it doesn't look spontaneous.
DEVIL'S ADVOCATE - Rev.
11/2/96 100.
A Forensic TECHNICIAN on the stand.
A display chart beside him.
Blowups of the bloody hand-prints.
KEVIN Let me put it this way, then: can you tell from a blood sample if the person were alive or dead?
TECHNICIAN The victim?
TECHNICIAN Of course not.
KEVIN And there's a two hour window in which to place these murders.
TECHNICIAN Yes.
KEVIN So, you've got absolutely no way to determine the condition of the victims when Alexander Cullen put his hand on that wall.
Kevin into the evening air, carrying a bag of stuff.
Barzoon standing there in a jogging suit.
Furious.
KEVIN Eddie...
BARZOON Saw you go in.
KEVIN What's up?
BARZOON Congratulations.
BARZOON DEVIL'S ADVOCATE - Rev.
BARZOON 11/2/96 101.
KEVIN It's not over yet.
BARZOON I'm not talking about the trial.
KEVIN What are you talking about?
BARZOON How the fuck does your name get on the firm's charter?
KEVIN What?
BARZOON Looks like it's been there for years.
BARZOON Now you're a partner?
BARZOON When did that happen?
BARZOON I am still the managing director of this firm.
BARZOON You want my job?
BARZOON Take me head on.
BARZOON Backdoor me one more time and I'll take your partnership papers and stuff 'em down your throat.
KEVIN I don't know what you're talking about, but I sure as hell don't like your tone of voice.
BARZOON Bullshit.
KEVIN You got a problem with documents, I suggest you put together one of your late-night shredding sessions.
BARZOON You think you're tough enough to run this firm?
BARZOON Fine.
BARZOON You tell Milton next time Weaver calls maybe I pick up the phone.
Kevin standing there, watching him jog away, as we --
Kevin sitting there with his bag of groceries.
Milton looking sadly perplexed --
MILTON Was he drunk?
KEVIN I doubt it.
KEVIN He was going running.
KEVIN What the hell was he talking about?
MILTON Eddie's gotten himself into trouble again.
MILTON And he wants me to save him.
MILTON And I can't.
KEVIN Why does he think I'm after his job?
MILTON Do you have any experience with manic-depression?
KEVIN Not directly, no.
MILTON You do now.
MILTON Milton already on the phone.
MILTON Punching a number.
MILTON Yes, it's me.
MILTON Get Eddie Barzoon.
MILTON Right away.
MILTON He may be out running, so page him if you have to.
MILTON It's an emergency.
MILTON Looks like you could use a drink.
Mary Ann coming through the living room.
She looks stoned.
But moving with purpose.
As if she were hearing something.
Opening the terrace doors and staring out over the park, as we --
The reservoir entrance.
It's a nice night and busy with runners and bikes and --
Barzoon comes jogging past.
Kevin has a vodka in his hand.
MARY ANN Eddie Barzoon.
MARY ANN I've nursed him through two divorces, a cocaine rehab, and a pregnant receptionist.
MARY ANN God's creature, right?
No leaves on the trees.
Barzoon running.
Breaking a sweat now.
Leaving the heavy traffic behind.
MILTON I'll tell you, Kevin, because I know you're into theology.
MILTON When you've seen -- when you've represented -- when you've dealt with as many people as I have over the years, finally you say to yourself, 'God must've been awfully bored.'
MILTON DEVIL'S ADVOCATE - Rev.
MILTON 11/2/96 104.
MILTON (CONT'D) Choice.
MILTON (CONT'D) The opportunity to fuck up.
MILTON (CONT'D) Talk about entertainment value.
Barzoon running.
Into his pace.
Glancing down and on the horsepath below.
Three running shadows.
Side-by-side.
Just passing beneath an iron bridge.
MILTON (V.O.) You take a look at Eddie Barzoon you gotta wonder if maybe God overplayed his hand.
MILTON (V.O.) Maybe he made the game a little too interesting...
Barzoon turns back -- stumbles -- catches himself -- sprinting now to the Pump House.
He pulls up here.
Resting as several other runners pass by.
Glancing back, almost an afterthought and --
Those three running shadows are now crossing the bridge which is completely impossible considering where they just were a moment ago and --
Barzoon starts running again -- instinctively -- faster than before -- glancing back and --
(EFX) The three shadows.
The sun setting behind them.
Transforming as they run -- animal shapes mixing with the harsh silhouettes of bare trees and --
DEVIL'S ADVOCATE - Rev.
11/2/96 105.
Barzoon freaked -- What the fuck was that?
-- The park suddenly looking very empty -- and dark --
The three shadows and they're closer and weirder and --
Barzoon -- suddenly turning -- changing course -- leaving the path -- into the woods -- quickly ducking down beside a huge sycamore tree.
Hiding.
Sweating.
Scared.
Staring back out at the path --
Three women runners -- clear as day -- pass beneath a streetlight.
Team clothes.
Machine-like strides.
Flat- out.
And then gone.
Barzoon stands from behind the sycamore tree.
Relief.
Smiling at his own stupidity.
What a jerk.
Dusting off.
Heading back toward the path, when --
Suddenly, there's an arm around his neck -- throwing him to the ground --
Standing there above him, a crazed-looking homeless MAN -- he's white and old and hungry --
OLD MAN Gimme your watch.
BARZOON You want the watch, old man?
BARZOON Come and get it.
BARZOON DEVIL'S ADVOCATE - Rev.
BARZOON 11/2/96 106.
Barzoon moving toward the old guy when -- Crack!
-- A tree branch swings out of nowhere -- catching his elbow -- snapping it back and --
A second homeless man.
He's black and older than the first guy but just as wild and dangerous and he's winding up to swing the branch again and --
Barzoon on his knees -- dazed -- blood pouring from his head -- uncomprehending eyes watching these park creatures tear at his clothes --
(EFX) Watching them grow more feral and less human by the moment and --
Mary Ann staring out at the park.
Covering her ears against some horrible sound that she alone can hear.
Barzoon -- on his belly -- in the dirt -- trying to move -- crawl -- anything --
The two men beating Barzoon to death with stones --
-- transforming with every blow -- (EFX) as their hands descend they become terrifying, demonic creatures, and as they rise we see them as men and over and over, as we hear --
DEVIL'S ADVOCATE - Rev.
11/2/96 107/108.
MILTON (V.O.) You take a look at Eddie Barzoon you gotta wonder if maybe God overplayed his hand.
MILTON (V.O.) Maybe he made the game a little too interesting.
MILTON (V.O.) Milton turns to find Kevin staring at him.
KEVIN I'm gonna, I'm gonna go downstairs now.
KEVIN Put this stuff away.
KEVIN Ice cream's already melting.
KEVIN Milton watching him walk away, as we --
Pam exits the room.
Melissa sitting at the head of the table.
Kevin pacing around her.
They are alone.
Practicing her testimony over early morning coffee.
KEVIN You testified that the defendant called you at four-thirty to ask you to come to his office gym for the purposes of sex.
MELISSA Yes.
KEVIN Mr. Cullen, though, he's not just your lover, is he?
KEVIN He's the boss.
MELISSA Yes.
KEVIN So two hours go by before you act on his request?
MELISSA Yes, I went up at six-ten.
MELISSA I knew it was six-ten, they had weather coming on the news.
MELISSA I remember --
MELISSA Cut off by --
KEVIN Okay.
KEVIN Stop.
KEVIN This prosecutor is no fool.
KEVIN He's gonna change tempo, attitude, tone of voice -- he's gonna come out with questions you never thought of, just to screw you up.
KEVIN So what do we do?
MELISSA Yes and no answers.
MELISSA Stay calm.
KEVIN Exactly.
KEVIN Is it your testimony, Ms. Block, that between the hours of six-ten and nine-forty you were engaged in sexual congress with the defendant?
MELISSA Yes.
KEVIN At any point during this three hour marathon, Ms. Block, did you lose sight of the defendant?
MELISSA No.
KEVIN Did he use the bathroom?
MELISSA Yes.
KEVIN Is he circumcised?
KEVIN You understand the question?
MELISSA Yes.
KEVIN So is he cut or not?
MELISSA Yes.
KEVIN Which is it?
KEVIN Silence.
KEVIN Melissa looks away.
KEVIN You've been polishing his knob three times a week for six months and you don't know whether or not he's got foreskin?
MELISSA I've had it up to here with this fucking game.
MELISSA Why don't you take your questions and shove 'em up your ass.
MELISSA Kevin staring at her.
MELISSA Looking away.
MELISSA Moving quickly for
the door, and into:
Three steps out and he stops.
Something's wrong.
Very wrong.
People are out of their offices, standing in the doorways.
Some of them crying.
Christabella rushes toward him, into his arms --
CHRISTABELLA Oh, Kevin --
KEVIN What's happened?
CHRISTABELLA Eddie Barzoon...
KEVIN What about him?
CHRISTABELLA He's dead.
CHRISTABELLA He was killed.
KEVIN When?
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 11/2/96 111.
Heath nearby has more answers --
HEATH Last night in the park.
HEATH He was running if you can believe it.
HEATH Kevin standing there, holding Christabella.
HEATH Feeling heat on the back of his neck and turning to find Milton at the far end of the hall.
HEATH Their eyes lock --
CHRISTABELLA What is wrong with people?
HEATH At least they got the scumbags who did it.
KEVIN Who?
LAWYER #1 Two old, homeless crazies.
LAWYER #1 Pam coming through the hallway like steel --
PAM Kevin...
PAM Kevin, I'm sorry, but you're due in court in thirty minutes.
PAM As Melissa appears in the conference room door --
MELISSA Are we through here, or what?
PAM I'll bring Melissa down in the car, but you better get going.
SCREAMING uptown.
Kevin looking very rattled.
Milton, beside him.
Talking him down.
MILTON I want you to put Eddie aside.
MILTON Let me worry about it.
MILTON You gotta deal with Cullen now.
MILTON Marshal your strength.
MILTON Prioritize.
MILTON Conserve your energy.
MILTON DEVIL'S ADVOCATE - Rev.
MILTON 11/2/96 112.
KEVIN I can't put her on the stand.
MILTON What choice do we have?
KEVIN I know she's lying.
MILTON Because she didn't answer you fast enough?
MILTON Did she lie to you?
MILTON No.
MILTON She said nothing.
MILTON The fact is, you'll never know.
KEVIN He killed those people.
MILTON You really believe that?
KEVIN Cullen set me up.
KEVIN Melissa, the whole thing, I know it.
MILTON Look, you gotta go with your gut.
KEVIN That's your advice?
MILTON I'll back you either way.
MILTON Hey, you think I haven't lost before?
MILTON We talked about this, Kevin.
MILTON Pressure.
MILTON Take a big whiff.
MILTON Kevin unreadable.
MILTON The SUBWAY CAR RATTLING away.
Packed and ready.
JUDGE POE Mr. Lomax, you may call your next witness.
A long, awful pause.
Kevin in agony.
Milton behind him.
Cullen and Pamela and everyone waiting...
JUDGE POE Counselor...
KEVIN I call Melissa Block.
Chaos!
-- media madness -- Kevin pushing past dozens of reporters and camera crews -- court officers trying to clear the way -- fifteen voices screaming at once -- questions flying like shrapnel -- Cullen, all smiles, alongside Milton as they're pushed along -- Pam, waving a cell phone, fighting her way to Kevin and --
PAM Kevin!
PAM Kevin, it's for you --
PAM Kevin takes the phone, trying to hear above the noise.
A cab speeds to a stop.
Kevin jumps out.
Feeney, the doorman, standing there with Felix, his partner.
FEENEY She didn't look well, sir.
FEENEY Felix tried to talk to her, but she --
KEVIN Where is she?
Kevin running down the sidewalk and --
Kevin enters.
It's empty and dark.
Two old ladies up front.
Mary Ann in back, wrapped in a comforter.
KEVIN Honey...
KEVIN Mare.
KEVIN It's me.
MARY ANN He let himself in.
MARY ANN You need to know that.
MARY ANN The bath running, or something, I didn't hear him.
MARY ANN I swear to you.
KEVIN Who?
MARY ANN Then we talked.
MARY ANN We talked for hours.
MARY ANN I haven't talked to anyone, really talked to anyone in such a long time.
MARY ANN You have this whole life and all I have is me and he was so clear about it all.
KEVIN Who let himself in?
MARY ANN I came down here.
MARY ANN I've just been sitting.
MARY ANN I'm afraid to pray.
MARY ANN I let him stay.
MARY ANN I'm sorry.
MARY ANN I'm sorry.
MARY ANN I'm sorry, Kevin.
KEVIN Did somebody hurt you?
MARY ANN Milton.
MARY ANN He fucked me, Kevin.
MARY ANN I let him fuck me.
MARY ANN I couldn't stop him.
KEVIN What?
KEVIN When?
MARY ANN Today.
MARY ANN This afternoon.
MARY ANN All afternoon.
MARY ANN God, I'm so ashamed...
MARY ANN DEVIL'S ADVOCATE - Rev.
MARY ANN 11/2/96 115.
KEVIN Today?
KEVIN Today?
KEVIN Today.
KEVIN He was in court, Mare.
KEVIN He was in court, in my presence all afternoon!
MARY ANN I'm not crazy.
MARY ANN I'm not.
MARY ANN I swear.
KEVIN I don't know, Mare.
KEVIN I don't know how much more of this I can take.
KEVIN She stands.
KEVIN Throws open the comforter.
KEVIN She is naked.
KEVIN There are scratch marks all over her body.
Kevin with a NURSE and paperwork.
NURSE Sign there...
NURSE And there...
NURSE And one more...
NURSE She's calm now so this might be a good time to say good night.
NURSE Kevin nods.
NURSE Stands, moving now -- into --
Mary Ann on a moving gurney.
Calm now, in the sway of some very strong drugs.
Kevin kneels beside her.
MARY ANN I know why this is happening.
KEVIN They want you to go to sleep.
MARY ANN It's the money, Kevin.
MARY ANN Blood money.
MARY ANN We just drank it down.
MARY ANN Both of us.
MARY ANN We knew it.
MARY ANN Winning those cases, taking the money.
MARY ANN We knew they were guilty.
MARY ANN But you kept winning.
MARY ANN Every time.
MARY ANN DEVIL'S ADVOCATE - Rev.
MARY ANN 11/2/96 116.
MARY ANN (CONT'D) I can't look at myself in the mirror, Kevin.
A big one.
A funereal morning.
Hearse and cortege parked on the street outside.
Barzoon's funeral.
Big deal.
Big crowd.
An excess of flowers.
ORGAN MUSIC as foreplay.
Milton, up front, seating Diana and children.
Kevin seated on the aisle.
Beside him, Jack Heath.
JACKIE What do they say?
KEVIN They don't know.
KEVIN It's bad.
KEVIN She's falling apart.
CHRISTABELLA Do you have room for one more?
CHRISTABELLA Kevin turns to see Christabella standing beside him.
CHRISTABELLA Jackie's concerned expression blossoms into a private, knowing smile now that Kevin has turned away.
CHRISTABELLA Christabella squeezes in, as the MUSIC SWELLS and THE PRIEST walks solemnly to the altar.
CHRISTABELLA Kevin caught in a high-intensity sexual cross-fire between Jackie and Christabella.
CHRISTABELLA He's tense.
CHRISTABELLA He's flipping out.
Milton passes on his way to the back.
Smiles.
DEVIL'S ADVOCATE - Rev.
11/2/96 117.
On one side the Therapist, on the other Allesandra, except she looks different than last we saw her.
Hair down.
Makeup.
She could be all of seventeen.
THE PRIEST We are here today, to remember and pray and exalt in the spirit of Edward Barzoon...
THE PRIEST Kevin staring at Cullen and the girl.
THE PRIEST ...
THE PRIEST Father, husband, partner, friend, colleague...
(EFX) Cullen's hand stroking at the back of the pew -- nothing outrageous, except it does call to mind the hand of Mr. Gettys back in Florida --
THE PRIEST ...
THE PRIEST taken from us so suddenly...
THE PRIEST Cullen's hand moving with purpose -- stopping -- waiting -- as Allesandra sits back and now his fingers find her skin -- stroking ever so subtly --
THE PRIEST ...
THE PRIEST to contemplate evil.
THE PRIEST How it robs -- how it steals everything of value from us...
THE PRIEST Cullen turns -- except it's not Cullen, it's Gettys -- yes, Gettys -- whispering in Allesandra's ear and --
THE PRIEST ...
THE PRIEST farther from God's purpose...
Kevin out of his seat.
Pushing past Christabella -- rushing up the aisle --
THE PRIEST ...
THE PRIEST and the greater that distance, the greater evil's pleasure...
Milton watching Kevin flee the church.
Moments later.
Kevin hustling away --
WEAVER Mr. Lomax?
KEVIN No comment.
KEVIN I'll have something for you later.
WEAVER I'm a friend of Eddie Barzoon.
WEAVER Kevin turns.
WEAVER Weaver walking beside him.
WEAVER Remember me?
WEAVER Mitch Weaver.
WEAVER Justice Department.
KEVIN Staking out the funeral?
WEAVER Looking for you actually.
KEVIN I'm in a bit of a hurry right now.
KEVIN I need to talk to my wife.
WEAVER Just wanted to ask you -- off the record -- I had a few questions about Eddie.
The funeral.
In progress.
CHOIR and ORGAN getting LOUDER.
We're watching Milton move in the back of the church.
Kevin walking faster.
Weaver right beside him.
WEAVER Milton, Chadwick, Waters is a little more than a law firm, but then I assume you knew that.
WEAVER Devada Holdings?
WEAVER I'm sure you've heard of it.
WEAVER London, Kinshasa, Karachi -- Arms brokering mostly.
WEAVER You've got Munzer-Dietch, they're in Berlin and Djakarta -- chemical weapons, toxic waste.
WEAVER Ivanaco Limited -- Moscow -- money laundering for the Eastern Bloc.
WEAVER It goes on and on, Kevin.
Stained glass.
Angels.
The Stations of the Cross.
Milton standing in the shadows at the back.
Taking it all in.
Prodigal angel.
(EFX) And then, the stained-glass angels begin to move.
Wings begin to beat.
Expressions come alive.
Expressions of panic and fear and --
Kevin really striding.
Weaver right there.
WEAVER Milton is into everything.
WEAVER Barzoon was coming in, Kevin.
WEAVER He was gonna testify.
WEAVER (CONT'D) Desoto and Dibalista, in Panama, that's a firm that specializes in opening bank accounts for judges all over South America.
WEAVER (CONT'D) Huge drug cases.
WEAVER (CONT'D) Murder.
WEAVER (CONT'D) Everything.
KEVIN He's a lawyer!
KEVIN What the fuck do you want?
KEVIN Stay off my back.
KEVIN Weaver left standing there, as Kevin rushes away -- through traffic -- across the street --
WEAVER This is a first time, last time offer!
WEAVER I'm learning about you, Kevin.
WEAVER I talked to some old friends down in Florida this morning...
WEAVER The Gettys case.
WEAVER The eighth grade teacher?
WEAVER Found him this morning.
WEAVER He had the body of a ten-year-old girl in the trunk of his car.
WEAVER Kevin, across the street, stops.
(EFX) Stained-glass angels going nuts now -- wings flapping like mad -- danger everywhere, as the MUSIC STARTS to CLIMAX and --
Milton down below.
Lowering a single finger into the holy water.
Instantly -- it's boiling, and we --
DEVIL'S ADVOCATE - Rev.
1/18/97 121.
Kevin standing there, across the street -- Weaver smiles, thinking he'll talk now for sure -- stepping off the curb and --
TIRES SCREECHING and Weaver turning and --
A car trying to stop and --
Kevin watching as --
WHAMM!
-- Weaver ploughed onto the hood and --
A mother at the wheel -- her daughter beside her -- both screaming and --
The car's WINDSHIELD as it CRUMPLES and --
Kevin watching as the car stops and --
Weaver is dazed but alive -- his face buried in the windshield -- pulling himself up and --
Weaver's face THROUGH the shattered glass as he looks down to see --
Mother and child (EFX) -- transforming -- for an instant -- into monsters and --
Weaver more terrified than hurt -- scrambling off the hood of the car -- staring back in horror and --
Mother and child -- completely freaked out -- both of them hysterical and --
Weaver holding his arm -- nose bloodied -- but moving -- backing away -- turning to find Kevin still across the street and --
It's gonna be okay.
And then, a big flat-nose truck -- out of nowhere -- air BRAKES BLASTING as it just wipes Weaver OFF the SCREEN and --
Kevin falling back, flat against a wall -- STAYING ON Kevin -- as the street comes alive with the SOUNDS of EMERGENCY and he starts moving away and we --
DEVIL'S ADVOCATE - Rev.
1/18/97 122.
Kevin walking through -- stopping finally at an open door --
Mary Ann in a chair.
Heavily sedated.
Pam standing beside her, brushing her hair.
Mrs. Lomax, on her knees, standing now --
MRS. LOMAX Kevin...
MRS. LOMAX honey...
KEVIN What are you doing here?
MRS. LOMAX I came this morning.
MRS. LOMAX I been calling the house and getting no answer and then I spoke to Pam and...
MRS. LOMAX I need to talk to you.
PAM We got her on the first flight up this morning.
MRS. LOMAX Are you all right?
KEVIN I just...
KEVIN I don't know.
MRS. LOMAX Will you excuse us a moment?
MRS. LOMAX Mrs. Lomax guides Kevin out.
MRS. LOMAX Mary Ann's vacant eyes watching them exit --
Just outside the room.
MRS. LOMAX I never should've left.
MRS. LOMAX I knew it.
MRS. LOMAX I'll never forgive myself.
KEVIN I was gonna call you, I just...
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 1/18/97 123.
LOMAX What I did, Kevin, I thought it was for the best.
LOMAX Loving you was always first for me.
KEVIN There's nothing you could've done.
MRS. LOMAX I could've told you the truth.
KEVIN About what?
MRS. LOMAX I've lied to you, Kevin.
KEVIN When?
MRS. LOMAX Always.
MRS. LOMAX Baptist Endeavor Youth Crusade, ninety-sixty-four.
MRS. LOMAX I was here.
MRS. LOMAX In New York.
MRS. LOMAX That night in the elevator, you never let me answer.
KEVIN What are you talking about?
MRS. LOMAX We stayed a week.
MRS. LOMAX The Tremont Hotel, it's not there anymore, I went by and it's gone -- they had a restaurant downstairs and we ate there almost every meal --
KEVIN Wait.
KEVIN Stop.
MRS. LOMAX Your father was a waiter in that restaurant.
KEVIN Oh, this is great, Ma...
KEVIN this is just perfect --
MRS. LOMAX -- honey, listen to me --
MRS. LOMAX DEVIL'S ADVOCATE - Rev.
MRS. LOMAX 1/18/97 124.
KEVIN -- Now?
KEVIN You do this now?
KEVIN -- Because, I mean, your timing -- it's superb -- you wait thirty years?
KEVIN -- you fly up here -- you pick today?
KEVIN --
MRS. LOMAX -- Kevin, honey, wait --
KEVIN -- obviously I'm not under enough pressure -- I don't have enough on my mind, I need this little --
MRS. LOMAX Listen to me.
KEVIN Why are you doing this now?
MRS. LOMAX Because I'm afraid!
MRS. LOMAX Kevin overwhelmed -- walking away -- down the hall -- completely fritzed -- leaving her standing there --
MRS. LOMAX Kevin.
MRS. LOMAX Kevin!
MRS. LOMAX 'Behold I send you out as sheep amidst the wolves.'
MRS. LOMAX Kevin just stopped walking.
Mary Ann quiet as Pam finishes brushing her hair.
PAM Don't you look beautiful now.
PAM Here.
PAM Have a look and see.
PAM A hand mirror.
PAM Mary Ann turns away instantly --
MARY ANN No.
MARY ANN DEVIL'S ADVOCATE - Rev.
MARY ANN 1/18/97 125.
PAM It's all right, dear.
PAM Look...
MARY ANN No.
MARY ANN Please...
PAM Go on.
PAM Take a look.
PAM See how beautiful you are?
PAM Mary Ann opens her eyes.
PAM There's her reflection.
PAM She is beautiful.
PAM It's okay.
PAM She smiles.
PAM What was she afraid of?
PAM And then, the mirror shifts to find --
Pam -- A monster (EFX) -- her features horribly transformed in the glass and --
Mary Ann rears back -- her head smashing into Pam's face so hard that the MIRROR SHATTERS -- Pam, blind for a moment, staggering back -- Mary Ann on her feet and fighting and Pam suddenly pushed and --
Pam standing there, holding her face in pain, as the glass door slams shut and --
MRS. LOMAX What's going on?
MRS. LOMAX Mary Ann THROUGH the glass, jamming a chair up under the doorknob --
MRS. LOMAX Kevin!
MRS. LOMAX Kevin jogging down the hall -- trying the door --
MRS. LOMAX DEVIL'S ADVOCATE - Rev.
MRS. LOMAX 1/18/97 126.
KEVIN Mary Ann.
KEVIN Hey.
KEVIN Hey!
KEVIN Omigod...
KEVIN Get somebody!
KEVIN Go!
KEVIN Pam doesn't move.
Mary Ann, kneeling on the floor, picking up a broken shard of mirror and --
KEVIN Mare!
KEVIN -- Look at me!
KEVIN -- Stop!
KEVIN -- right now -- Mare!
KEVIN --
Mary Ann raising the glass/blade to her throat.
KEVIN Mary Ann, no!
KEVIN No!
KEVIN No!
LOMAX -- Help!
LOMAX -- Help!
LOMAX -- Somebody!
LOMAX We need help --
DEVIL'S ADVOCATE - Rev.
1/18/97 127.
Kevin banging like mad on the glass but --
KEVIN -- Mare!
KEVIN -- No!
KEVIN -- Look at me!
KEVIN --
KEVIN Mary Ann raising the blade to her throat and --
KEVIN -- Stop!
KEVIN -- No!
KEVIN -- Mare!
KEVIN --
KEVIN Kevin grabbing a folding chair -- swinging it --
241A   OMITTED                                                         241A thru thru
SMASH!
-- GLASS SHATTERING over the floor, but Kevin still can't get in -- wire mesh embedded in the window is bent but unbroken and he's tearing at it and --
KEVIN -- Mare!
KEVIN -- Hang on!
KEVIN -- I'm almost there!
KEVIN -- Look at me!
KEVIN And she does.
KEVIN Watching him claw at the wire --
MARY ANN I loved you.
MARY ANN Pulling the blade across her neck --
KEVIN Noooooooooo!
243B   OMITTED                                                         243B thru thru
Kevin kicking full force against the door and --
DEVIL'S ADVOCATE - Rev.
1/18/97 128.
The door buckles -- the chair wedged in there sent flying -- Kevin stumbling over broken glass --
KEVIN Oh, God, Mare, what've you done?
KEVIN -- no...
KEVIN Mary Ann falling to the floor -- her bloody hand still holding the blade deep in her neck --
ORDERLY #1 -- why?
ORDERLY #1 -- Oh God, Mare, why?
ORDERLY #1 We need a doctor in here!
Patients out of their rooms -- standing at their doorways -- sedated, bovine expressions watching --
MRS. LOMAX -- please -- somebody -- help her!
MRS. LOMAX -- What are you all doing?
MRS. LOMAX Somebody!
MRS. LOMAX --
MRS. LOMAX ORDERLY #1 turning the corner up ahead --
ORDERLY #1 What's the hell's going on down here?
Kevin cradling Mary Ann -- his hand trying to staunch the wound in her neck -- blood flowing -- she isn't moving -- her eyes are starting to fix and --
KEVIN -- no, Mare -- hang on -- please, Mare, I'm right here, it's gonna be okay, baby -- oh, God, Mare, why did you do this?
KEVIN --
KEVIN Where's the fucking doctor?!
ORDERLY #1 Oh shit, man...
ORDERLY #1 DEVIL'S ADVOCATE - Rev.
ORDERLY #1 1/18/97 129.
Kevin turns -- Orderly #1 in the doorway --
KEVIN What are you doing?
KEVIN Help her!
ORDERLY #1 Hey, look, I ain't no doctor...
ORDERLY #1 Hang on -- lemme --
ORDERLY #1 YELLING in the hall now, and faces in the doorway.
ORDERLY #1 Mrs.
ORDERLY #1 Lomax crying and two weird patients from the next staring and...
ORDERLY #1 Pam.
ORDERLY #1 And only we can see it, but she's smiling...
KEVIN -- please, baby, stay with me...
KEVIN it'll be okay -- it's gonna be fine just, just stay with me -- Oh God, Mare...
KEVIN please, baby...
KEVIN Kevin holding her, but she's gone, as we --
245    OMITTED                                                            245 thru thru
But someplace completely different.
Older.
Dark.
Empty.
Echoey.
A fluorescent bulb sputtering out.
FOOTSTEPS approaching...
It's Kevin.
And we know instantly that Mary Ann is dead.
There's blood on his shirt.
His eyes are raw.
At his side, a small suitcase containing her personal effects.
More than grief, more than shock, what we notice most is his frighteningly grim determination.
Up ahead, a bench.
Mrs. Lomax huddled here.
Cried out.
Empty.
Holding herself more tightly as he sets down the suitcase.
MRS. LOMAX I could've packed that up for you.
MRS. LOMAX Kevin sits.
MRS. LOMAX If he loses his steel he'll drown.
MRS. LOMAX DEVIL'S ADVOCATE - Rev.
MRS. LOMAX 1/18/97 130.
LOMAX I wish you'da let me help you.
KEVIN Finish the story.
KEVIN Nineteen-sixty-four.
KEVIN You're in New York.
KEVIN There's a waiter in a restaurant.
KEVIN Finish the story.
MRS. LOMAX He talked to me.
MRS. LOMAX Nobody'd ever really talked to me before.
MRS. LOMAX Sixteen years old, a thousand miles away from home, somebody takes an interest...
MRS. LOMAX Working so hard, putting himself through school, I'd never met anybody like that.
MRS. LOMAX Knew the Bible, every word, just knew it by heart.
MRS. LOMAX Every meal, there he was, at my ear and I just...
MRS. LOMAX I didn't want that week to ever end.
MRS. LOMAX But it did.
MRS. LOMAX He came to say goodbye, it was late, and I started to cry and he said not to worry, 'Behold, I send you out as sheep amidst the wolves.' And that just stopped me cold because we'd spent that whole day at Bible study reading Matthew Ten and there was just no way for him to know about that, so I was...
MRS. LOMAX I took it as a sign.
MRS. LOMAX I let him in.
MRS. LOMAX And then everything was different.
MRS. LOMAX He was cruel.
MRS. LOMAX He was so cruel and I was so ashamed, I thought I'd die...
MRS. LOMAX Kevin's eyes settle on the suitcase.
MRS. LOMAX Mary Ann...
MRS. LOMAX I promised right there if God would let me back into His grace I would never leave again.
MRS. LOMAX I prayed there was a reason this terrible thing had happened.
MRS. LOMAX There had to be a reason.
MRS. LOMAX And there was.
MRS. LOMAX It was you.
MRS. LOMAX You were my blessing.
MRS. LOMAX You were reason enough to endure anything.
MRS. LOMAX How much I love you.
KEVIN I want to hear you say it.
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 1/18/97 131.
LOMAX His face -- that night -- I knew it was him and the same time I was confused -- and you were so proud you'd come to New York and done all this on your own, I didn't have the heart to tell you --
KEVIN Say it.
MRS. LOMAX -- you wondered yourself -- the apartment, the money, all this attention, everything out of nowhere...
MRS. LOMAX Milton.
MRS. LOMAX He's your father.
MRS. LOMAX Somehow he found us.
MRS. LOMAX Tracked you down.
KEVIN No.
MRS. LOMAX What do you mean?
KEVIN He's always been there.
KEVIN I know that now.
KEVIN Watching.
KEVIN Waiting.
KEVIN He's been playing us like a game.
KEVIN Jerking us around.
KEVIN Destroying Mary Ann...
KEVIN Kevin stands.
KEVIN Quiet fury.
KEVIN A machine.
MRS. LOMAX What are you doing?
KEVIN I gotta go.
MRS. LOMAX No...
MRS. LOMAX let it alone!
MRS. LOMAX Stay with me.
MRS. LOMAX Forget about him!
MRS. LOMAX We can leave here.
MRS. LOMAX We can go home!
MRS. LOMAX We don't ever have to see him again!
MRS. LOMAX DEVIL'S ADVOCATE - Rev.
MRS. LOMAX 1/18/97 132.
KEVIN I can't do that.
KEVIN You go home.
KEVIN Pray for Mary Ann.
MRS. LOMAX Kevin, please...
MRS. LOMAX Honey!
MRS. LOMAX I love you!
MRS. LOMAX Kevin disappearing down the stairs.
MRS. LOMAX Mrs. Lomax dropping to her knees as his FOOTSTEPS ECHO away, and we --
As Kevin explodes through a fire door.
Pam standing there, having a smoke.
PAM There you are...
PAM Look at you...
PAM you're terrified.
PAM Not to worry.
PAM He'll take that fear away.
PAM You don't ever have to be frightened again.
PAM Go on, he's waiting...
PAM Kevin turning and something is very wrong --
Fifty-seventh Street is empty.
No cars.
No people.
Just the building and the silence.
Turning back and Pam is gone, and then --
And then a WIDER ANGLE -- it goes on and on...
He's alone.
Just now realizing the scale of Milton's power.
Starting to walk, as we --
The room's only light coming from the huge bas relief.
Kevin steps off the elevator, into the room.
PAM DEVIL'S ADVOCATE - Rev.
PAM 1/18/97 133.
MILTON You're right about one thing...
MILTON I have been watching.
MILTON Couldn't help myself.
MILTON Watching, waiting, holding my breath.
MILTON But I'm no puppeteer, Kevin...
MILTON Milton appears out of nowhere.
MILTON Walking past Kevin.
MILTON ...
MILTON I don't make things happen.
MILTON Doesn't work like that.
MILTON Free will -- it's like butterfly wings -- one touch and it never gets off the ground.
MILTON I only set the stage.
MILTON You pull your own strings.
MILTON Kevin has a gun -- Cullen's gun, in his hand --
KEVIN What did you do to Mary Ann?
MILTON A gun?
MILTON In here?
KEVIN What did you do to my wife?
MILTON On a scale of one to ten, ten being the most depraved acts of sexual theater, one being an average Friday night run-through at the Lomax household, I'd say...
MILTON Six.
MILTON Kevin FIRES the GUN -- BANG!
MILTON BANG!
MILTON BANG!
MILTON -- bullets pass right through him -- into the wall --
MILTON Whoa...
MILTON Got me!
MILTON Damn!
MILTON That's my boy.
MILTON Step on up!
MILTON Stay angry!
MILTON Keep hold to that great fury!
MILTON Hang on tight, Kevin, because it's the final fig leaf.
MILTON Kevin lowers the gun to his side.
KEVIN Who are you?
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 1/18/97 134.
MILTON Never lost a case.
MILTON Why?
MILTON Why?
MILTON Because you're so fucking good?
MILTON Yes.
MILTON But why?
KEVIN Because you're my father.
MILTON Well, I'm a little more than that.
MILTON Awful hot in that courtroom, wasn't it?
MILTON 'What's the game plan, Kevin?'
MILTON 'It was a nice run, Kevin.
MILTON Had to close out someday.'
KEVIN Who are you?
MILTON I have so many names.
KEVIN Satan.
MILTON Call me Dad.
KEVIN Mary Ann, Barzoon, Weaver...
MILTON Come on.
MILTON You're not listening.
MILTON Blaming me for Mary Ann?
MILTON I hope you're kidding.
MILTON You could've saved her any time you liked.
MILTON She only wanted love.
MILTON But you knew it wouldn't really work out, didn't you?
MILTON Mary Ann in New York?
MILTON Face it, you started looking to better- deal her the minute you got here.
KEVIN That's a lie.
MILTON Hey, it's not that you didn't care for her, it's just you were a little bit more involved with someone else.
MILTON Yourself.
KEVIN What the hell do you know about love?
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 1/18/97 135.
MILTON Bio-chemically no different than eating large quantities of chocolate.
MILTON Don't be such a fucking chump.
MILTON There's only one real sickness in all of creation and that is self- delusion.
MILTON I told you to take care of your wife -- that the world would understand.
MILTON And you made a choice.
MILTON 'You know what scares me, John?
MILTON I leave the case, she gets better and I hate her for it...' Remember?
KEVIN You set me up.
KEVIN It's entrapment.
MILTON Who told you to pull out the stops for Mr. Gettys?
MILTON And Moyez -- the direction you took -- Snake handlers, Popes and swamis all feeding at the same trough -- whose ideas were those?
MILTON And then Cullen -- knowing he's guilty -- seeing those pictures -- putting that lying bitch on the stand...
MILTON What did I say, Kevin?
MILTON Maybe it was time to lose, right?
MILTON You didn't think so.
KEVIN That's my job.
KEVIN That's what I do!
MILTON Exactly!
MILTON Vanity is definitely my favorite sin.
MILTON Self love.
MILTON It's so basic.
MILTON What a drug.
MILTON Cheap, all-natural, and right at your fingertips.
MILTON Pride.
MILTON That's where you're strongest.
MILTON And believe me, I understand.
MILTON Work for someone else?
MILTON -- Hey, I couldn't hack it.
MILTON 'Better to reign in Hell than serve in Heaven.'
KEVIN What do you want from me?
MILTON What do I want?
MILTON I want you to be yourself!
MILTON DEVIL'S ADVOCATE - Rev.
MILTON 1/18/97 136.
(EFX) The Bas Relief -- that wall of bodies swirling in marble clouds -- it's going to come to life --
MILTON I've had many children, Kevin.
MILTON So many disappointments.
MILTON Neurotic, indecisive wannabes.
MILTON Over-eager, ham-handed butchers.
MILTON Strung-out, priapic losers.
MILTON And then there's you.
MILTON Your mother, I'll tell you, she outstripped my wildest fantasy.
MILTON That church she dragged you to?
MILTON Every day?
MILTON What training.
MILTON What a challenge!
MILTON It's awesome what you've done.
MILTON How far you've come.
MILTON Both of you...
MILTON You and your sister.
MILTON Christabella emerges from behind the bar --
MILTON Half-sister to be exact.
CHRISTABELLA Surprise.
MILTON What do you think, Kevin?
MILTON What a scene, huh?
CHRISTABELLA Don't let him scare you.
MILTON Wait till you meet her mother.
KEVIN It is a test, isn't it?
KEVIN The whole game, you sitting there, keeping score.
MILTON No.
MILTON That's the other guy.
MILTON I don't judge anybody.
MILTON As far as I'm concerned, everyone's a winner.
MILTON DEVIL'S ADVOCATE - Rev.
MILTON 1/18/97 137.
MILTON (CONT'D) God's your prankster, my boy.
MILTON (CONT'D) Think of it.
MILTON (CONT'D) He gives man instincts.
MILTON (CONT'D) He gives you this extraordinary gift and then, I swear to you -- for his own amusement -- his own private, cosmic gag reel -- he sets the rules in opposition.
MILTON (CONT'D) It's the goof of all time.
MILTON (CONT'D) Look but don't touch.
MILTON (CONT'D) Touch but don't taste.
MILTON (CONT'D) Taste but don't swallow.
MILTON (CONT'D) And while you're jumping from one foot to the other he's laughing his sick fucking ass off!
MILTON (CONT'D) He's a tight-ass.
MILTON (CONT'D) He's a sadist.
MILTON (CONT'D) He's an absentee landlord!
MILTON (CONT'D) Worship that?
MILTON (CONT'D) Never.
(EFX) The Bas Relief getting stranger and more seductive by the moment -- bodies spinning and spawning --
MILTON I'm here, on the ground, my nose in it since the whole damn thing began.
MILTON Why?
MILTON Because I worship man himself.
MILTON And it's my time now.
MILTON Our time.
CHRISTABELLA Anybody want a drink?
CHRISTABELLA I'm having a drink.
KEVIN This is some pitch.
KEVIN You must need me pretty bad.
KEVIN What do you want?
MILTON Eddie was right.
MILTON Your name is on the partnership charter.
MILTON I want you to take over the firm.
MILTON You and your sister.
KEVIN Is that it?
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 1/18/97 138.
MILTON No.
MILTON She's ovulating.
MILTON Right now.
KEVIN What?
MILTON Your vanity is justified, Kevin, you're the seed to a new future.
MILTON Your son will sit at the head of all tables.
MILTON You hold a special place in the history of all things.
KEVIN You want a child.
MILTON I want a family.
KEVIN The Antichrist.
MILTON Whatever...
KEVIN But I have to volunteer.
KEVIN Christabella begins to strip.
MILTON Free will.
MILTON It's a bitch.
MILTON I need a family.
MILTON I command an ever larger presence on the board.
MILTON I'm busy and I need some help.
MILTON There's a plan here.
MILTON I've been conserving my energy.
MILTON Synergy.
MILTON Prioritize.
MILTON It's the millennium, Kevin.
MILTON Title fight.
MILTON Round twenty.
MILTON I'm ready to work.
KEVIN So what are you offering?
MILTON Are we negotiating?
KEVIN Always.
KEVIN DEVIL'S ADVOCATE - Rev.
KEVIN 1/18/97 139.
MILTON Yes!
KEVIN What are you offering?
MILTON Everything.
MILTON Anything.
MILTON All of it!
MILTON What am I offering?
MILTON I'm offering bliss.
MILTON Instant bliss.
MILTON Bliss by remote control.
MILTON Bliss on tap.
MILTON That first line of cocaine.
MILTON That walk into a strange girl's bedroom.
MILTON The jury coming back in thirty- eight minutes.
MILTON Freedom.
MILTON Revolution!
MILTON Viva la causa!
257    OMITTED                                                           257 thru thru
(EFX) The Bas Relief transforming into real clouds and bodies and the frame of it disappearing and --
KEVIN You're right, aren't you?
KEVIN About me.
KEVIN I mean, I made all the choices, didn't I?
KEVIN Gettys.
KEVIN Cullen.
KEVIN Mary Ann.
KEVIN I did kill her, didn't I?
MILTON Don't be too hard on yourself.
MILTON Christabella passing Kevin, handing him her bra.
CHRISTABELLA It's done.
CHRISTABELLA Forget it.
CHRISTABELLA It's all for us now.
MILTON God, she's just fucking stunning, isn't she?
MILTON Christabella lingering and Kevin leaning in...
MILTON kissing her...
MILTON just a moment before she pulls away --
MILTON DEVIL'S ADVOCATE - Rev.
MILTON 1/18/97 140.
KEVIN You're right.
KEVIN I wanted to fuck her from the minute we met.
MILTON Like that's wrong.
MILTON Like there's anything wrong with that.
MILTON That there could be laws preventing something so natural.
MILTON That's our ticket in.
MILTON Did you know there were more students in law school right now than lawyers walking the Earth?
(EFX) The Bas Relief has become an orgy, bodies coming to life in a swirling, narcotic haze and --
MILTON We're coming out, guns blazing.
MILTON The two of you -- all of us -- acquittal after acquittal until the stench of it reaches so high into heaven it chokes the whole fucking lot of them!
MILTON What we cannot legislate we will buy.
MILTON What we cannot buy we will degrade.
MILTON We will blow every fuse of enlightenment until it looks like a vandalized, neon sign!
MILTON And while God is busy at his peephole -- as he deigns us with his disapproval -- as he lumbers around his empty kingdom like some overfed colonial governor -- as God sleeps late, we will win.
MILTON We've got a winner here, kids!
KEVIN In the Bible you lose.
KEVIN You're destined to lose.
MILTON Consider the source.
MILTON Christabella -- her hands -- moving over her body --
CHRISTABELLA Stop talking.
CHRISTABELLA Both of you.
CHRISTABELLA Kevin, please...
CHRISTABELLA DEVIL'S ADVOCATE - Rev.
CHRISTABELLA 1/18/97 141.
(EFX) The bodies craning to watch as they roll by.
CHRISTABELLA Kevin, really, please...
MILTON She's right, my son.
MILTON It's time to step up and take what's yours.
KEVIN You're right.
KEVIN It's time.
KEVIN Kevin raises the GUN to his temple -- quick and simple -- SNAP!
KEVIN -- he's blown his brains out --
KEVIN Milton stunned -- disbelieving for a moment and then an aura of fire and heat explodes around him --
MILTON Nooooooo...!
(EFX) Kevin starting to fall in SUPER SLOW MOTION and --
(EFX) The room consumed with fire as the heat explodes around Milton's body and --
(EFX) Kevin still falling and --
(EFX) Christabella beating at the flames that now cover her body and --
(EFX) Kevin still falling and --
(EFX) The Bas Relief.
The clouds are now fire -- the bodies now burning and --
(EFX) Kevin still falling and --
(EFX) Milton as his clothes burn away -- as the heat eats away his features --
(EFX) as he becomes younger and younger and younger, until suddenly --
(EFX) For a moment.
He is an angel.
An instant of exquisite perfection amidst the flames.
And then, just as --
(EFX) suddenly -- HE EXPLODES!
-- and we --
(EFX) The Bas Relief freezing instantly back into stone -- trapped in tortured, agonizing finality.
(EFX) And then, the whole thing just crumbling.
Stone raining down in tiny pieces and --
(EFX) Kevin in SUPER SLOW MOTION as he falls the final few inches to the floor and at the moment of impact we hear the sound of THUNDER and we --
The mirror.
And Kevin's face.
As THUNDER ECHOES AWAY and becomes nothing more than a FLUSHING URINAL.
We're back in Florida.
Where we started.
Kevin touches his face.
His body.
His head.
He's alive.
He touches the mirror.
He's insane.
He's here.
It's now.
WATER RUNNING in the sink.
REPORTER It was a nice run.
REPORTER Kev.
REPORTER Had to close out someday.
REPORTER Nobody wins 'em all.
REPORTER The Reporter exits.
REPORTER Kevin alone with the mirror and his reflection.
REPORTER And then it's over.
REPORTER He's made his decision.
REPORTER Replacing his wedding ring.
REPORTER Reaching for his jacket, as we --
Kevin walking through.
His game face.
A court officer opening the doors and --
Kevin entering.
Standing there a moment.
Searching for Heath in the back of the courtroom.
He's not there.
A single empty seat.
Kevin moving quickly down the aisle.
Mary Ann standing there, completely unprepared as Kevin comes in behind her.
Embracing her.
Holding her tightly to him with a fervor that we alone will understand.
MARY ANN Honey, what are you doing?
MARY ANN Are you okay?
MARY ANN Kevin nods.
MARY ANN Smiles.
MARY ANN Backs away.
MARY ANN Into his seat.
MARY ANN Gettys there beside him.
MARY ANN Kevin will not look at him.
BAILIFF All rise for the honorable Justice Garson Deeds.
BAILIFF The Judge enters.
BAILIFF Takes his seat.
JUDGE You're still under oath, young lady.
JUDGE (CONT'D) Your witness, Mr. Lomax.
KEVIN Your Honor, I'm terribly sorry, but I can no longer represent my client.
KEVIN I need to be replaced as counsel.
KEVIN Another silence.
KEVIN But this one isn't very long.
KEVIN There will be chaos in the courtroom.
KEVIN Gettys will freak out and the press will start running for the phones and the Judge will be banging that gavel, as we --
As the doors open and the chaos begins to spill into the hallway.
Kevin trying to rush away with Mary Ann but right behind them --
REPORTER Kevin!
REPORTER -- Hey!
REPORTER Listen, this story -- this is the one, pal -- this is the one you dream about --
KEVIN There is no story.
REPORTER Bullshit.
REPORTER A lawyer with a crisis of conscience?
REPORTER You gotta be kidding.
REPORTER It's huge!
KEVIN They're gonna disbar me, Larry.
KEVIN You can cover that.
MARY ANN Can they do that?
REPORTER Not when I get through with the story.
REPORTER You gotta talk, Kevin.
REPORTER You gotta gimme an exclusive.
REPORTER (CONT'D) This is wire service.
REPORTER (CONT'D) This is 'Sixty Minutes'.
REPORTER (CONT'D) This is a story that needs to be told.
REPORTER (CONT'D) It's you!
REPORTER (CONT'D) You're a star!
KEVIN Call me tomorrow.
REPORTER You got it.
REPORTER First thing.
REPORTER Kevin nods.
REPORTER Holding Mary Ann's hand as they escape.
The Reporter watching them go for a moment.
Then turning back.
(EFX) And as he does, his features change, transforming - - like that -- into Milton.
It's Milton.
Always there.
And he smiles.
And we FREEZE FRAME.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
