by Jonathan Lawton & Stephen Metcalfe
The view of downtown Los Angeles from the enormous, ornate house is extraordinary.
A small outdoor dinner party is in progress.
A MAGICIAN is entertaining guests.
Playing cards and coins appear and disappear in his nimble hands.
EDWARD HARRIS stands at the window, impassively looking down at the party.
Edward is a handsome, well groomed man of around forty.
He looks tired; the kind of fatigue that can't be cured by a night's sleep.
EDWARD Left pocket.
And indeed, down below, the magician pulls the coin from the left pocket of the incredulous WOMAN's silk blazer.
More laughter and applause.
The study is in keeping with the rest of the house.
Luxurious.
Everything the best.
WILLIAM STUCKEY, Edward's contemporary, is a crafty looking lawyer who is the party host.
VANCE is an investment banker.
His assistant JAKE, is a financial researcher.
The other men are INVESTMENT BANKERS.
They are in dark suits and power ties.
On the table are stacks of documents and folders, the name "KROSS INDUSTRIES" is prominent on many of the folders.
Our banks certainly doesn't want to discourage Harris Enterprises from investing in California.
We think this is a great new venue for you but you've got to understand the mergers and acquisitions market is changing.
With the upswing in inflation we have to make these offerings tempting to offset the risk.
VANCE Look, we're talking about hard assets and a straight liquidation.
VANCE We have over a thousand man hours in this deal.
STUCKEY This is a "no brainer".
STUCKEY There's no risk for you.
STUCKEY No one has ever lost money backing Mr. Harris.
Not yet.
But ship building is a new endeavor for you...
STUCKEY Come on.
STUCKEY You know we're not going to go into ship building.
STUCKEY Besides, you're the ones with the troubled track record, not us!
Bill, be reasonable.
If you're really going to digest Kross Industries that quickly eighteen should not be such a problem.
Besides, I don't think there's anywhere else you can go for the money in the time you have.
EDWARD It's unacceptable.
Edward turns from the window.
He hasn't miss a thing.
All eyes are on him.
EDWARD Draymen Heux has offered me seventy-five in the pool at sixteen and a half.
EDWARD I can secure the other half personally.
EDWARD You have until tomorrow morning to make me a better offer.
The bankers speechlessly stare at him.
EDWARD The meeting is over, gentlemen.
He turns away.
The bankers look at one another.
They rise.
Silence as they exit.
When the door closes.
Stuckey explodes with laughter.
STUCKEY Hah!
STUCKEY Did you see the look on their faces?
VANCE You don't think we pushed too hard?
STUCKEY NO way!
STUCKEY They'll come back.
STUCKEY They can't afford not to.
STUCKEY Edward, that bluff was beautiful.
EDWARD Maybe I should have made it rhyme.
The others stare at him, uncertain.
Stuckey laughs.
The others follow suit.
EDWARD Well!
EDWARD It's late.
EDWARD We've been at this long enough.
Stuckey rises.
Edward ushers Vance and Jake toward the door.
EDWARD Gentlemen, enjoy the party.
EDWARD The magician's wonderful.
Vance and Jake exit.
EDWARD Watch your left pocket.
A BUTLER has entered the room.
Phone call, Mr. Harris.
It's Miss Charles.
STUCKEY Cynthia?
STUCKEY Is she coming out?
EDWARD We're about to find out.
EDWARD Go on.
EDWARD Take care of your guests.
Stuckey exits the room as Edward crosses to the telephone.
EDWARD Where are you, Cynthia?
EDWARD I see.
EDWARD No, I don't expect you to be at my beck-and-call.
EDWARD Are you coming or not?
Edward descends the long, curved stairway.
He has Vance in tow.
EDWARD Prepare the filing papers.
EDWARD Have them ready by the middle of the week.
EDWARD I'll tell you when to submit them.
The PEOPLE talking and drinking on the stairway gravitate toward Edward.
Edward!
EDWARD Yes!
Will we see you at the polo matches Wednesday?
EDWARD Wouldn't miss it.
EDWARD I want this done fast and easy.
EDWARD No slip-ups.
EDWARD I want to be back in New York by Saturday.
EDWARD Got it?
He deftly keeps making his way through the crowd.
Stuckey is sipping champagne and talking to a beautiful WOMAN in a tight sheath of an evening dress.
An elegant woman ELIZABETH STUCKEY approaches from behind him.
She taps him on the shoulder and he turns, startled.
ELIZABETH Bill?
STUCKEY Oh...
STUCKEY Hi, honey...
STUCKEY Millicent, uh, uh, Millicent.
Lowell.
STUCKEY Lowell, right.
STUCKEY My wife, Elizabeth.
ELIZABETH Is Edward leaving?
Stuckey looks up to see Edward moving quickly toward the door.
Stuckey abruptly leaves the two woman together to follow Edward.
Edward comes out of the house.
Jags, a limo with waiting DRIVER and two BMW's pack the circular driveway behind a black Ferrari.
The limo driver leaps to attention at the sight of Edward.
Edward stands, making an obvious effort to keep his impatience under control.
Stuckey comes out of the house and down the walk.
STUCKEY What's up, where you going?
EDWARD Give me your car keys, will you, I'm going back to my hotel.
STUCKEY At least stay for a drink.
STUCKEY This party's for you.
EDWARD Apologize to Elizabeth for me.
Stuckey gropes uncertainly in his pocket for keys.
STUCKEY Listen, there're some major local talent inside just dying to meet you...
EDWARD Really?
EDWARD Some high class gold digger who speaks French better than I do?
EDWARD No, thank you.
EDWARD I just got off the phone with one.
STUCKEY Cynthia's not coming?
EDWARD No.
Edward grabs the keys out of Stuckey's hand.
He crosses to a black Ferrari and gets in.
STUCKEY Let your driver take you.
STUCKEY We'll move the cars...
Edward starts the car.
STUCKEY Can you drive a stick?
The car lurches forward with a squeal of wheels and promptly stalls.
STUCKEY Edward, give me a break!
With a squeal of tires, the Ferrari bucks out of the driveway and...
stalls again.
EDWARD Love this car!
EDWARD Is it new?
STUCKEY Yes!
STUCKEY And you don't even know where you're going!
Edward starts it again and heads uncertainly uphill.
Stuckey watching, throws up his hands.
STUCKEY That's the wrong way!
The Ferrari, moving fast through the Hollywood Hills, passes large, beautiful homes...
Edward shifts, grinding gears...
The Ferrari comes to a red light and pulls up next to a Dodge Colt.
The GIRL in the Colt looks at Edward and his car admiringly.
Edward feeling confident now, revs the engine.
The light turns green.
Edward immediately stalls the Ferrari.
The Colt leaves him in the dust.
Edward drives.
He blinks, shakes his head as if trying to rid himself of his own tired thoughts.
The Ferrari comes to the intersection of OUTPOST and FRANKLIN, stops.
Edward gets out of the car.
He looks at the street signs.
He has no idea where he is.
He signs.
He gets back in the car and takes off on Franklin heading East.
A crumbling old apartment building.
Dark alley ways, deserted parking lot.
The Ferrari -- blink and you miss it -- motors past the building, looking very out of place on the street.
PANNING UP A building facade of lit windows and metal fire escape.
One window in particular.
A GIRL stands there in a short kimono, looking down.
And then she turns away.
A SERIES OF SHOTS to see her dressing.
VIVIAN turns and stares at herself in a grainy, cracked bedroom mirror.
She is twenty years old and a prostitute.
Make-up applied to give her a hard, older look doesn't quite succeed.
She'd be innocently beautiful without it.
She is wearing tiny shorts, a tight tube top, thigh high boots.
She stares at herself, not really liking what she sees.
A moment.
She signs, turns off the light and walks out of the bedroom.
Faded, peeling walls.
Thread bare, dirty carpet.
Vivian locks the apartment door behind her and starts down the dim hallway.
A door suddenly opens, startling her.
An unshaved, enormously pot bellied MAN in a stained t-shirt stares at Vivian with pig eyes.
LANDLORD Vivian.
Vivian turns some "tough" on him.
VIVIAN Yeah, what?
LANDLORD Rent.
LANDLORD You're late.
VIVIAN Don't give me that.
VIVIAN Kit gave it to you yesterday, cash.
LANDLORD Kit give me nothin'.
VIVIAN You bullshittin' me?
LANDLORD Of rent I do not bullshit.
Vivian hurries at a run back down the hallway.
LANDLORD By the end of the week or you're otta here.
LANDLORD By the way, you look very nice tonight!
Vivian pulls a coffee can off a shelf.
She pulls off the top.
It's empty.
She tosses the can away, starts for the door.
She opens it.
Down the hallway, the landlord is standing in front of his open doorway, talking to a FAT WOMAN.
They both glance up.
Vivian quickly closes the door.
She doesn't want to deal with them.
Vivian comes off the fire escape onto the sidewalk.
She hurried away.
Vivian walks along, urgently looking for something...
someone.
A BABBLING STREET-TYPE goes by happily talking to himself.
He wears an "I Love Hollywood" t-shirt.
Vivian passes TOURISTS but doesn't notice them any more than she pays attention to the VAGRANT she passes further on, huddle in a doorway.
A LONG-HAIRED KID on a SKATEBOARD goes by dropping off little bags to various STREET-TYPES.
A BARKER-TYPE stands in front of a photo store urging tourists to come in and take a photo with a cardboard cut-out of a movie star.
Some go in.
Vivian hurries past a group of rubbernecking JAPANESE TOURISTS.
A BLACK PROSTITUTE in a mini skirt strolls toward her.
A car passes.
The DRIVER stares at Vivian with interest.
She ignores him.
The black prostitute approaches the car.
Hey, baby, you lookin' for a date?
The Driver looks her over.
The Black Prostitute gets in the car and it drives away.
A GROUP OF MEN, mostly drug dealers, hang out at an all night coffee shop.
They WHISTLE and make obscene gestures and SOUNDS as Vivian hurries by.
She ignores them and goes next door into a falafel stand.
Half a dozen PEOPLE sit at dirty tables inside.
Behind the counter are a MAN and a WOMAN, Vietnamese cooks frying food, trying to ignore the unsavory crowd camped in the shop.
VIVIAN Chan, you seen Kit tonight?
Hi, hi!
No see nothing.
VIVIAN You do, tell her I'm looking for her.
Looking good, bay-bee.
VIVIAN Yeah, you too, D'Nai.
VIVIAN If Kit comes in here, tell her stay.
Both of them nod and smile at Vivian.
Vivian exits.
Skateboard zips by a GROUP.
We SEE a police car parked at the entrance to an alcove.
Also, an ambulance.
The bubblegum lights are going.
A CROWD has gathered.
The happy man with the "I Love Hollywood" t-shirt and a POLICE OFFICER are engaged in tense conversation.
COP They just pulled her out of a dumpster in the back.
COP Now talk to me.
MAN I tell you, man, I don't know who she hang with.
COP She have a pimp?
MAN Cocaine her pimp, man.
MAN She a strawberry.
MAN She be out on these streets, day in, day out, tradin' her sorry ass for crack.
MAN And now she dead from it.
Vivian rushes up to join the outskirts of the crowd as the body of a YOUNG GIRL is pulled out of an open dumpster and carried towards the waiting ambulance.
For a moment Vivian thinks it's...
no, Vivian turns grimly away.
Vivian surveys the dark street.
And suddenly sees who's she's looking for.
Walks.
We SEE a young, tough-looking MAN and WOMAN trying on wigs.
The STOREKEEPER is a man wearing a dress and wild wig.
The girl, KIT, is around 18, is dark haired and thin.
The young man, CARLOS, has his arm sloppily draped across Kit's shoulder.
They giggle about something, both obviously high.
Kit looks up, bleary-eyed.
She stops.
Vivian is standing in front of her.
VIVIAN You spent it on drugs, didn't you?
KIT Hi, Viv.
KIT Carlos, you know my roommate, Viv.
CARLOS Lookin' good, baby.
VIVIAN Did you blow it all, Kit?
VIVIAN Is it all gone?
KIT Carlos had some great rock.
VIVIAN I bet.
VIVIAN That was our rent!
Carlos attempts to put an arm around Vivian's shoulders.
CARLOS Calm down, Chica.
Vivian throws him off.
CARLOS Ey!
CARLOS What is it you wan', baby?
CARLOS I can fix you up.
VIVIAN Beat it, scum bucket!
CARLOS You kiss your mother with that mouth?
CARLOS Your frien' still owes me 200.
VIVIAN Let's go.
Skateboard appears suddenly, blocking Vivian and Kit's path.
VIVIAN Get out of my face or I'll have those cops on your ass in two seconds.
Carlos glares at her.
He looks down toward the lights of the cop cars.
One of the POLICEMEN looks towards them, curiously.
Vivian waves at the cop.
CARLOS Don't take no dates tonight, chica, you got one with me.
Vivian grabs Kit by the arm and pulls her across the Boulevard.
Vivian and Kit sit at a table sipping tea.
Vivian is still mad at her.
VIVIAN We worked for that money.
VIVIAN We were gonna put together enough to get out of that dump we live in, get off this street.
KIT Viv...
KIT don't be stupid.
KIT We're whores.
Vivian looks like she wants to weep.
Or scream.
She does neither.
She slowly nods.
Kit's sorry she said that.
KIT (cont'd) So I blew our stash.
We could make it all back with one good night on the streets.
VIVIAN I just saw somebody pulled out of a dumpster.
VIVIAN I wonder how much she made tonight?
KIT Don't be mad at me.
KIT I'll pay you back.
KIT I promise.
VIVIAN I thought you were giving up that drug shit.
KIT I will.
KIT I'm trying.
KIT Meanwhile I got some crack left, you wanna get high?
VIVIAN No, let's go to work.
VIVIAN Okay?
KIT Okay.
KIT I'm sorry I said your dream was stupid.
Edward's Ferrari turns onto Hollywood Blvd., finally out of the Hollywood Hills.
Vivian and Kit are out trying to hustle John's in passing cars.
Vivian strikes a sexy pose at the bus stop.
Kit is talking to another prostitute, RACHEL.
KIT No no, honey.
KIT You see these stars on the sidewalk.
KIT Me and Vivian work from Don Ameche all the way up to Roy Rogers.
KIT This is our office.
KIT We got seniority.
KIT Get off our corner.
I was just taking a rest here.
Besides, she's new.
KIT But I'm old.
KIT Go rest up by Monty Hall or Debra Paget where you belong.
Rachel walks off.
VIVIAN Looks slow tonight.
KIT Maybe we should get a pimp.
KIT Carlos likes you and --
VIVIAN Forget it.
VIVIAN We work for it.
VIVIAN We keep it.
They keep hustling.
KIT I can't handle this tonight.
KIT I'm going home.
VIVIAN That crack is burning a hole in your pocket.
VIVIAN There isn't even milk in the fridge.
VIVIAN The rent's due.
VIVIAN Now come on --
KIT Hey, hey -- There's a rent.
VIVIAN He's not gonna want us.
The Ferrari goes by and stops.
EDWARD Excuse me.
KIT Don't take less than a hundred.
KIT You look hot tonight.
KIT And remember, don't mouth off.
KIT They don't like that.
VIVIAN Okay.
VIVIAN Go home.
VIVIAN But take it easy on that shit.
Kit gives Vivian a quick hug.
KIT You're the greatest.
KIT I'll wait up for you.
And then Kit is off, moving quickly away.
Vivian turns.
She stares at the Ferrari, loathing it and all it represents.
And then it's as if Vivian turns a switch.
She fluffs her mane of hair, throws her shoulders back, thrusting her breasts out and sashays towards the car, a sexy, friendly smile on her face.
In the driver's seat of the Ferrari, Edward is looking furious and distracted.
Vivian leans over the passenger window.
VIVIAN Hey Sugar, you lookin' for a date?
EDWARD What's that?
VIVIAN You looking' for some company?
EDWARD Uh, no.
EDWARD How do I get to Beverly Hills?
VIVIAN What?
VIVIAN You gonna tell me you're lost?
EDWARD Yes.
VIVIAN Great.
VIVIAN What do I look like a tourguide?
Edward takes a good look at her.
EDWARD No, you look like a hooker.
VIVIAN Actually, I'm a movie star out for a walk.
EDWARD Good.
EDWARD Can you tell me how to get to Beverly Hills?
VIVIAN Sure.
VIVIAN For five bucks.
EDWARD That's ridiculous.
VIVIAN The price just went up to ten.
EDWARD Why don't you just do it out of the kindness of your heart?
VIVIAN Sit...
VIVIAN and spin.
EDWARD Sit-and-spin.
EDWARD Alright...
EDWARD why not?
He pulls out his money clip.
Vivian suddenly freezes.
On the sidewalk up ahead, Carlos and Skateboard.
Carlos flashes an evil, menacing grin.
He motions to Skateboard, they start forward.
EDWARD You have change for a twenty.
Vivian pulls open the door of the car and jumps in.
VIVIAN For twenty, Ill show you personal.
VIVIAN Drive.
Edward stares at her.
She smiles sweetly.
VIVIAN (cont'd) Make a "U-ee".
Beverly Hills is the other way.
The Ferrari pulls away, passing Carlos on the sidewalk.
VIVIAN Nice car.
VIVIAN Yours?
EDWARD No.
VIVIAN Stolen?
EDWARD Not exactly.
He smiles.
Vivian smiles back.
VIVIAN Mind if I turn on some heat?
EDWARD If you can figure it out, be my guest.
Vivian reaches out, turns on the heat.
EDWARD Very good.
EDWARD You're obviously mechanical.
VIVIAN You're not from L.A., huh?
EDWARD New York.
VIVIAN What motel you staying at?
EDWARD Hotel.
VIVIAN Okay, what hotel?
EDWARD Regent Beverly Wilshire.
EDWARD I bet you know it.
VIVIAN Yeah, I peed in the fountain there once.
VIVIAN Give me a break.
Edward glances over, amused.
It hits him that she really is an attractive girl.
EDWARD What's your name?
VIVIAN What do you want it to be?
VIVIAN Vivian, my name's Vivian.
EDWARD You like being a hooker, Vivian?
VIVIAN It pays.
EDWARD So do day jobs.
VIVIAN Day jobs, yeah.
VIVIAN I've tried them.
VIVIAN Turn right.
The Ferrari glides along a seedy, West Hollywood section of Santa Monica.
EDWARD Must be dangerous.
EDWARD Hooking.
VIVIAN Tell me about it.
VIVIAN L.A.
VIVIAN is suffering from a wacko epidemic.
VIVIAN And who knows where half the guys I pick up have been.
VIVIAN I mean, I use condoms.
VIVIAN Always.
VIVIAN And I get checked out once a month at the free clinic.
VIVIAN Not only am I better in the sack than an amateur, I'm probably safer.
EDWARD Very good.
EDWARD You ought to have that printed up on your business card.
VIVIAN If you're making fun of me, I don't like it.
EDWARD Sorry.
EDWARD If I did, I didn't mean to.
Vivian unconsciously bites her fingernails.
EDWARD Ugly habit, biting your nails.
VIVIAN You don't know habits, you think this is ugly.
But she puts her hands in her lap.
She looks out the window.
She's safe from Carlos.
VIVIAN Okay, pull over.
VIVIAN Let me out.
VIVIAN I've got to get back to work.
Edward pulls the Ferrari to the curb and stops.
VIVIAN (cont'd) Stay on this street and you'll hit Beverly Hills.
EDWARD What do you charge for company, Vivian?
VIVIAN Company would cost you...
VIVIAN a hundred dollars.
EDWARD For the whole night?
VIVIAN For an hour.
EDWARD You're joking.
VIVIAN I never joke about money.
EDWARD Neither do I.
EDWARD A hundred bucks an hour though.
EDWARD That's pretty stiff.
She reaches across the seat.
Her hand goes in his lap.
VIVIAN No, but it's getting there.
EDWARD Vivian, how much to put up with me for the entire night?
VIVIAN You couldn't afford it.
Vivian starts to get out of the car.
EDWARD Try me.
A moment.
Vivian's sexy smile comes on.
VIVIAN Three hundred.
EDWARD Fine.
VIVIAN What's your name, lover.
EDWARD Edward.
EDWARD My name is Edward.
VIVIAN Edward...
VIVIAN you got it!
Edward gets out of the car.
Vivian looks at him confused.
EDWARD Get in.
EDWARD This side.
VIVIAN What?
EDWARD You know how to drive a stick?
Vivian moves around the car.
VIVIAN Better believe it.
EDWARD Then let's go.
EDWARD It's worth 300 just so I don't have to drive.
They get in the car.
She starts the car, revs it.
VIVIAN Here we go Edward.
The Ferrari peels out, fishtails madly and SCREAMS up the street.
Thousands of tiny white lights sparkle along the walls of the Regent Beverly Wilshire Hotel.
Bright flags are illuminated by carefully placed spotlights.
The Ferrari SCREAMS into the driveway and comes to a jarring stop by the front door.
Edward takes a moment to get his breath.
He gestures toward the back.
EDWARD My raincoat's in the back.
EDWARD Put it on.
VIVIAN Why?
EDWARD You may feel more comfortable.
EDWARD This is not the kind of place that rents rooms by the hour.
VIVIAN You mean they don't have hookers.
EDWARD Every place has hookers, but if this hotel has hookers, they don't look like they're...
VIVIAN Off the boulevard.
EDWARD Exactly.
As they walk in, Vivian is tying the trenchcoat.
VIVIAN Great.
VIVIAN Now I took like a hooker in a trenchcoat.
She looks up.
She stops in her tracks.
The lobby is bright and spacious, filled with thick carved wood paneling.
Even at this hour there is a great deal of activity.
MEN in business suits and WOMEN in furs and jewels are passing by.
Vivian's face quickly conceals the sudden awe she feels at the sight of all this luxury.
Vivian matter of factly reaches out and takes Edward's arm.
VIVIAN So let's go.
Edward guides them across the lobby.
They reach the elevators and go inside.
The young ELEVATOR OPERATOR is dressed in a clean red uniform that seems just a bit too tight.
As the elevator doors close he nods toward Edward.
OPERATOR Evening, sir.
EDWARD Good evening.
EDWARD Penthouse.
VIVIAN Penthouse.
VIVIAN My, my.
She sees the operator glancing at her.
VIVIAN The penthouse.
VIVIAN And step on it.
Edward and Vivian come out of the elevator into a hallway leading to a single doorway with two heavy wood doors.
Edward pulls out his key and unlocks the doors.
With a gentle push the door slide open in unison.
Edward gestures to Vivian to go inside.
She does.
Edward closes the doors behind her.
As Vivian steps into the room she has the sensation of falling off the top of the building.
In front of her is a sunken living room with massive windows revealing the sparkling lights of the city below.
For the first time, she is speechless.
Edward closes the door and walks past her down the steps to the living room.
Edward picks up a phone.
Vivian checks out the room.
EDWARD Room service.
EDWARD What do you drink?
VIVIAN Diet coke.
EDWARD Send up a bottle of Crystal champagne.
VIVIAN Can I have some chips?
EDWARD -- and a bowl of strawberries.
EDWARD Thank you.
Vivian makes her way down the steps to the living room.
She stares at the view.
EDWARD Impressed?
Vivian is impressed but she's not going to admit it.
VIVIAN You kidding?
VIVIAN I come here all the time.
VIVIAN As a matter of fact they do rent this room by the hour.
Edward smiles.
He sits down in a comfortable chair and leans back.
Vivian looks at him.
VIVIAN (cont'd) Well, now that you have me for the night, what are you going to do with me?
EDWARD Want to know something?
EDWARD I don't quite know.
EDWARD I hadn't planned this.
VIVIAN Do you plan everything?
EDWARD Always.
VIVIAN Well, the meter's running, it's your money.
VIVIAN Speaking of which, cash'll do.
VIVIAN In advance.
EDWARD Fair enough.
He rises.
Takes out his wallet.
Standing over her, he drops THREE crisp, new hundred dollar bills in Vivian's lap.
She picks up the bills, stares at them, trying not to be impressed.
She puts the money in her jacket.
She realizes Edward is standing over her as if waiting.
She leans forward, reaches out to unzip his pants.
He abruptly turns away.
EDWARD Let's talk some more first.
VIVIAN Right.
VIVIAN So!
VIVIAN In town on business?
EDWARD Uh-huh.
VIVIAN Let me guess, you're a...
VIVIAN lawyer.
EDWARD And why do you say that?
VIVIAN I dunno...
VIVIAN you have that sharp, useless look.
Edward almost smiles.
He sits across from her again.
EDWARD Sounds like you've known a lot of lawyers.
VIVIAN I've known a lot of everybody.
A chime goes off to indicate there's someone at the door.
EDWARD Champagne.
He starts to sit up.
Vivian motions for him to stay put.
VIVIAN Hey.
VIVIAN I might as well make myself useful.
Edward sits back down.
Vivian waltzes up the steps and opens the front door.
A WAITER comes into the room with a silver cart; on it is a bucket of champagne and a covered bowl.
WAITER Where would you like it?
VIVIAN Where would we like it?
EDWARD Where would we like it?
EDWARD Here'll be fine.
The Waiter carries it down the steps and sets it in the middle of the living room.
He turns and heads back up the stairs and pauses near Vivian, staring.
Vivian stares back at him.
VIVIAN What are you looking at?
The Waiter glances away uncomfortably and exits.
Vivian closes the door behind him.
Vivian marches back down the stairs.
EDWARD I think he wanted you to tip him.
VIVIAN Tsk.
VIVIAN Excuse me, I didn't think he had change for a hundred.
Edward crosses to the silver stand.
Vivian watches with interest as he twirls the champagne bottle in the ice bucket.
VIVIAN (cont'd) You have a wife?
Girlfriend?
EDWARD I have both.
Edward lifts the bottle out.
He deftly pops the cork on the bottle without losing a drop of champagne.
VIVIAN Where are they?
VIVIAN Shopping together?
EDWARD They should be.
EDWARD They're both good at it.
Edward pours the champagne into a single long stemmed glass and hands one to Vivian.
EDWARD (cont'd) My ex-wife lives in London in what used to be my home.
My girlfriend is in New York moving out of my apartment even as we speak.
Cheers.
He drinks, nods approvingly.
EDWARD It's a very good year.
VIVIAN Oooh, thank god.
Edward laughs softly.
She sips it.
To her surprise, really likes it.
Edward lifts a lid on a silver bowl to reveal a dozen enormous strawberries.
EDWARD Try a strawberry.
VIVIAN Why?
EDWARD Because they bring out the flavor of the champagne.
VIVIAN Jesus, you act like you're seducing some Valley girl you picked up in a dance club.
EDWARD Vivian...
EDWARD the meter's running...
EDWARD cooperate.
A moment.
She slowly eats a strawberry.
The juice of it stains her lips.
Her eyes are like smoke as she takes a sensuous sip of champagne, licks away the stain of the strawberry.
His eyes haven't left her.
EDWARD You really are a very beautiful girl.
VIVIAN Just a romantic, that's you.
EDWARD Yes...
Her mouth is so wet and inviting...
he leans closer...
VIVIAN Me too.
He's about to kiss her...
VIVIAN (cont'd) Not on the lips.
He freezes.
She pulls his head down to her breast.
Edward and Vivian on the bed.
He is on his back, his shoulder and head resting against the headboard.
She is astride him, hands resting on his chest, rocking...
in control, confident...
very much liking the fire she's kindled in his eyes.
EDWARD What do you like?
VIVIAN If I want you to turn me on I'll pay you three hundred.
VIVIAN Just lay back and let me drive.
Smiling, Vivian reaches behind her, touching him.
He tries not to groan.
She's moving faster now.
Edward suddenly pulls her violently to him, he rolls her over...
A heavy spray of water comes down upon Edward.
He stands there quietly letting it wash over him.
He turns off the shower, steps out of the stall, picks up a towel and dries himself.
Edward stares.
His expensive clothes are on the floor, haphazardly dropped everywhere.
Vivian's clothes, as tattered as they are, are neatly folded and piled on a chair.
The incongruity of it touches Edward in a sad way.
He looks toward the bed.
Vivian is fast asleep.
Her heavy makeup has long since been rubbed off.
Asleep, her wary, smart-ass attitude is gone.
She looks like a sweet, gentle girl.
He stares at her a moment longer.
He turns, goes into the living room.
Vivian opens her eyes.
Through the open door she sees Edward sitting in a living room chair.
He is reading contracts.
The sun is coming up as HOTEL EMPLOYEE hoses down the sidewalk in front of the hotel.
A WOMAN EMPLOYEE is vacuuming the lobby.
She sees something and pauses.
She pulls a dead leaf from one of the potted plants.
The elevator doors open and A WAITER rolls a cart out into the hallway.
He takes it to the doors of the penthouse.
He rings the bell.
EDWARD It's open.
The Waiter wheels in a table of food, coffee, champagne and orange juice.
Edward dressed in suit pants, white shirt and suspenders, stands in the living room talking into a cordless phone.
Edward points the Waiter to the dining table.
EDWARD Sorry.
EDWARD Go ahead.
William Stuckey is behind his desk.
STUCKEY Kross knows we're after his company.
STUCKEY He wants to talk with you.
STUCKEY I don't think you should.
The Waiter returns.
Edward signs the bill.
The Waiter exits.
EDWARD I want to.
STUCKEY Edward, if the three of us sit down together we might as well announce our plans in the Wall Street Journal.
EDWARD I'll see him alone.
EDWARD Everyone knows you're my muscle.
EDWARD We'll make it social.
EDWARD Tell Kross I'll meet him for dinner.
EDWARD Tonight if you can arrange it.
STUCKEY You shouldn't go alone.
STUCKEY He might claim that you tried to black mail him.
EDWARD Bill, we're businessmen, not the damn mafia.
EDWARD I'll see you in the office.
EDWARD By the way, about your car...
STUCKEY Oh, god, what?
EDWARD I'll bring it back.
Edward hangs up.
He pours a glass of orange juice and takes a sip, thinking.
Something makes him turn.
Vivian, wearing a monogrammed hotel terry robe, is standing uncertainly in the bedroom doorway.
EDWARD Good morning.
VIVIAN You didn't wake me.
VIVIAN I'll be out of here in a minute.
EDWARD No hurry.
EDWARD Would you like some breakfast?
She's hungry and the breakfast looks great.
VIVIAN Only if you do.
Edward sits.
Waits.
Vivian sits across from him.
Edward serves them breakfast.
EDWARD Did you sleep well?
VIVIAN Yeah.
VIVIAN Too good.
VIVIAN I forgot where I was.
EDWARD Occupational hazard?
She looks at him sharply, sees that he means no offense, relaxes.
VIVIAN Where'd you go?
EDWARD I took the couch.
EDWARD I had some work to do.
EDWARD About last night...
VIVIAN Oooh, Baby, you were the best.
VIVIAN I was beside myself.
EDWARD Mmm, I could tell.
VIVIAN I just hope it was worth three hundred bucks.
EDWARD I'd say you give a good dollar value.
They share a small smile.
They eat.
EDWARD Do you ever...
EDWARD enjoy it?
VIVIAN I like guys if that's what you're asking.
VIVIAN Not that I trust'm.
EDWARD No?
EDWARD Why's that?
VIVIAN "Occupational hazard".
A moment.
Edward chuckles.
Vivian grins.
VIVIAN (cont'd) what do you do anyway?
EDWARD I buy companies.
VIVIAN No shit.
VIVIAN They expensive?
He almost smiles.
She almost smiles back.
EDWARD The one I'm buying this week will cost around 150 million.
VIVIAN ...
VIVIAN dollars?
He nods.
This time Vivian is impressed.
VIVIAN (cont'd) You are major league, baby.
Your mother must be very proud.
Edward is oddly pleased at her reaction.
The closet door is open.
Edward reaches for a tie.
In the closet are about a dozen expensive looking suits, shirts, shoes, etc.
She follows him in.
VIVIAN So what a ya do with the companies once you buy'm?
EDWARD I sell them.
VIVIAN What?
VIVIAN Why?
She undoes his knot and starts over.
VIVIAN (cont'd) At ease, let me do that.
Part of the all night services.
EDWARD By breaking up a company's assets
VIVIAN What are assets?
EDWARD Vivian --
VIVIAN C'mon, I might buy a company some day.
EDWARD Assets are anything of value a company owns.
EDWARD Sometimes the pieces are worth more than the whole.
EDWARD By selling them off, I make a profit.
VIVIAN Sorta like stealing cars and selling'm for parts, huh?
EDWARD Not...
EDWARD quite.
VIVIAN There, see?
VIVIAN Now the emblem is right in the middle of the knot.
EDWARD Where'd you learn to do this?
VIVIAN I fucked the debate team in high school.
VIVIAN Tsk.
VIVIAN I had a grampa.
VIVIAN He liked ties on Sundays.
VIVIAN You mind if I take a swim in your bathtub before I hit it?
EDWARD Don't drown.
Vivian turns and heads toward the bathroom.
He follows her into the bathroom.
Vivian turns on the water in the tub.
It fills the tub in a torrential rush.
VIVIAN You could hold a pep rally in here!
The phone on the marbled bathroom wall suddenly rings.
Edward reaches for it.
EDWARD Yes.
Stuckey is walking around his desk.
STUCKEY Edward, it's me.
STUCKEY Kross is all set for tonight.
Vivian stares curiously at the bidet.
STUCKEY Listen, I gotta say this again, I don't like you going alone.
She turns it on.
The water hits her in the face.
EDWARD I'm a big boy.
There are lotions and shampoos and bubblebaths on the edge of the tub.
Vivian regards them like a kid in a candy shop.
STUCKEY Let me at least get you a date.
STUCKEY Keep it social.
Edward watches as Vivian smells some bubble bath.
She smiles.
Her eyes ask Edward if it's okay to...?
He nods.
STUCKEY Edward, did you hear me?
EDWARD I'm here.
STUCKEY I know a lot of nice girls.
Vivian pours the bubblebath into the swirling water.
There's something about the look on her face...
the way she bites her lower lip...
curious, sensual...
EDWARD I have one.
Edward hangs up the phone as Vivian curiously turns on the television.
The sound blares.
She fumbles to turn it down.
Edward reaches over and turns it off.
EDWARD All right.
EDWARD How much for the week?
VIVIAN What?
EDWARD I'm in town until Saturday.
She look at him like he isn't speaking English.
EDWARD Do-you-want-to-stay-here- for-the-week?
It takes Vivian a moment to respond.
VIVIAN It'd cost you.
EDWARD Of course.
EDWARD How much?
VIVIAN Five full nights...
VIVIAN days too?
Edward nods.
Vivian hesitates...
it's got to be enough to really change things...
She shoots for the moon again.
VIVIAN Four thousand.
EDWARD Vivian, may I point out five more nights at three hundred a night is only 1,500.
VIVIAN But you want days too.
EDWARD All right, two thousand.
VIVIAN Three.
EDWARD Done.
VIVIAN Holy shit.
And then, quickly getting herself back together, she flips on the sexy smile.
VIVIAN (cont'd) Sugar, you got it.
I will treat you like a prince.
Anything, anyway you want.
EDWARD I'm not just talking about sex.
VIVIAN Look butthead, I'll treat you so nice you'll never want to let me go, okay?
EDWARD Three thousand for five days.
EDWARD And Vivian, I will let you go.
Edward comes out into the bedroom.
Vivian quickly follows.
They move through the bedroom into the living room.
EDWARD I'll be out most of the day.
He reaches into his pocket for a money clip.
He peels off bills.
He hands the cash to Vivian.
EDWARD I want you to go out and buy some decent clothes.
Vivian's eyes go wide at the amount of money.
EDWARD Nothing too flashy, not too sexy.
EDWARD Conservative.
EDWARD Understand?
They're at the front door.
VIVIAN Yeah, you want me to dress like your high class girlfriend.
VIVIAN You're wasting your money though.
VIVIAN All I'm gonna do is hang around the hotel.
VIVIAN As a matter of fact, I may never get out of that bathtub.
Edward opens the door, he starts to exit.
He turns back.
EDWARD Think again.
EDWARD I'm taking you out to an important dinner with me tonight.
The door closes in her face.
VIVIAN What?
VIVIAN Are you crazy?
Edward smiles to himself.
EDWARD Probably.
Vivian is stretched out in the hot bubble bath.
The TV is on.
She clicks the remote control in her hand.
VIVIAN Three thousand...
She lies back into the soapy water and disappears.
She suddenly pops back up, laughing.
VIVIAN Three thousand!
A thought occurs to her.
She reaches for the cordless phone.
She dials.
She waits.
She is about to disconnect when the phone is answered.
KIT 'Lo.
VIVIAN Kit!
VIVIAN Where've you been?
KIT I was asleep.
KIT You woke me.
KIT You okay?
VIVIAN Kit, listen, the guy last night, the one in the Ferrari, I'm at this hotel, the Regent Beverly Wilshire, it's this absolutely unbelievable place and he's hired me for a whole week and Kit, listen, he's paying me three thousand bucks!
VIVIAN We can get out of the apartment.
VIVIAN We can get out of this town.
VIVIAN We can do anything!
VIVIAN Kit?
VIVIAN Hey, you there?
KIT Why'd he want you?
That hurts.
Perhaps because Vivian's been wondering the same thing.
VIVIAN He...
VIVIAN he just does.
KIT I'm sorry, Viv'.
KIT Carlos has been on my back.
KIT Did you get the money up front like I taught ya'?
VIVIAN Three hundred for last night and he gave me extra to buy some clothes.
VIVIAN Now listen, I'm gonna leave an envelope for you at the front desk.
VIVIAN Give me two hundred to the scum bucket and the other hundred to that asshole landlord for part of the rent.
VIVIAN Spend it on drugs and I'll pull your hair out.
KIT I'm getting dressed now.
KIT I'll be over.
KIT Bye.
VIVIAN Hey Kit, where do I go for the clothes?
VIVIAN Good stuff on him.
KIT In Beverly Hills?
VIVIAN Yeah.
KIT Baby!
KIT Rodeo Drive.
Vivian comes out of the elevator and crosses the lobby.
She is back in her hooker clothes.
She leaves an envelope at the front desk.
MR.
THOMAS, the prim, middle-aged hotel manager, steps out from his office.
He stares in surprise and displeasure as he sees Vivian exit out the front door.
Vivian doesn't notice the odd stares she gets from two well-dressed MIDDLE-AGED WOMEN who are just entering.
Vivian is looking wide-eyed and delighted and yes, more than a bit overwhelmed.
She passes store windows...
and MORE STORE WINDOWS...
and still MORE STORE WINDOWS.
Each display is more beautiful and expensive than the one before.
Vivian is also aware that she is getting odd looks.
From PASSERBY'S.
Two beautiful dressed GIRLS her own age look at her, turn away and giggle.
The uniformed GUARDS that stand at attention in front of many of the stores, stare at her suspiciously.
Feeling more and more uncomfortable, Vivian comes to a posh woman's boutique.
She hesitates for a moment.
She enters.
Vivian is no sooner in the door than she is subject to the disapproving stare of a SALESWOMAN standing behind the counter.
SALESWOMAN May I help you?
VIVIAN I'm just looking, thanks.
Vivian tiptoes through the shop as if it was filled with delicate glass objects.
She cautiously examines a dress.
The Saleswoman quickly comes around the counter and approaches her.
SALESWOMAN Are you looking for something in particular?
VIVIAN Yes.
VIVIAN Something...
VIVIAN conservative.
SALESWOMAN Yes...
Vivian eyes the Saleswoman, puzzled at her tone.
She examines a dress.
VIVIAN You have beautiful things.
VIVIAN How much is this?
SALESWOMAN I don't think it would fit you.
VIVIAN I didn't ask if it would fit.
VIVIAN I asked how much it was.
SALESWOMAN It's very expensive.
Vivian's body tenses as she stares at the Saleswoman.
VIVIAN What is with you?
SALESWOMAN Excuse me?
VIVIAN I'm going to spend money.
SALESWOMAN I don't think we have anything for you here.
SALESWOMAN You're obviously in the wrong place.
Vivian is speechless.
She turns and stomps toward the door.
She stops and spins around staring at the Saleswoman.
Vivian flips her off.
She throws the door open and storms outside.
The Saleswoman calmly strolls back to her counter and returns to her place.
Vivian comes out onto the street and stands, lost.
She takes a deep breath, trying to control herself.
Two WOMEN, in elegant designer outfits, stroll by, eyeing Vivian as if she were a freak.
Vivian suddenly feels naked.
She turns and hurries away.
Vivian enters the lobby, upset, nervous and paranoid.
She feels an emptiness in her stomach at the sight of all the luxury around her.
She hurries toward the elevators.
At the front desk, Mr. Thomas, once again spots her.
He crosses the lobby and deftly cuts her off from the elevator.
MR. THOMAS May I help you Miss?
Vivian stops, practically shaking with terror.
VIVIAN I'm just going to my room.
MR. THOMAS You're a guest here?
VIVIAN I'm -- I'm with a friend.
MR. THOMAS And who is that?
VIVIAN I...
VIVIAN Edward...
Vivian's face is filled with confusion.
She doesn't know his name.
The elevator doors open behind them.
She spots the Operator.
VIVIAN He knows me.
Mr. Thomas turns and eyes the Operator curiously.
The Operator looks back at them innocently.
With a smooth gesture Mr. Thomas waves the Operator over.
MR. THOMAS Do you know this young lady?
The Operator nods.
OPERATOR She's with Mr. Harris.
MR. THOMAS Mr. Harris?
OPERATOR She apparently joined him last night.
Mr. Thomas waves the Operator away.
MR. THOMAS Why don't you come with me.
MR. THOMAS We'll chat for just a moment.
He takes Vivian gently but firmly by the arm and leads her off.
In a richly furnished office, Mr. Thomas places Vivian in a comfortable chair and then leans against the edge of his desk.
MR. THOMAS What's your name?
VIVIAN Vivian.
MR. THOMAS Miss Vivian...
MR. THOMAS things that go on in other hotels don't happen at the Regent Beverly Wilshire.
Vivian says nothing.
MR.
THOMAS (cont'd) Mr. Harris, however, is a very special customer.
And we like to think of our special customers as friends.
As a customer, we would expect Mr. Harris to sign in any additional guests.
But as a friend, we're willing to overlook it, I'm assuming you're a...
relative?
Vivian finds herself nodding.
MR.
THOMAS (cont'd) I thought so.
You must be his...?
VIVIAN Niece?
MR. THOMAS Of course.
MR. THOMAS Naturally when Mr.
MR. THOMAS Harris leaves, I won't see you in this hotel again.
Vivian bites her lower lip, nods.
MR.
THOMAS (cont'd) Good.
We understand one another.
(as a gentle afterthought:) I would also encourage you to dress in a more appropriate manner.
Vivian's face screws up as she tries hard not to cry.
VIVIAN That's what I was trying to do.
She can't help it, the tears come.
Vivian pulls out the money Edward gave her.
She drops it on the desk.
It's a moist- looking wad now.
VIVIAN (cont'd) I was trying to get some other clothes...
but...
they wouldn't...
they made me feel like shit...
She can't go on.
Mr. Thomas politely glances at the money.
He unfolds it, smoothes it and hands it back to her.
He sighs.
He picks up the phone.
He dials.
MR. THOMAS Women's clothing.
MR. THOMAS Bridget, please.
Vivian is staring at him.
MR.
THOMAS (cont'd) Bridget, hello, this is Barnard Thomas over at the Regent Beverly Wilshire.
Well, thank you, that's flattering.
I'd like to ask a favor of you.
I'm going to send someone over.
Her name is Vivian.
She's a guest of ours.
A very special guest.
He glances at Vivian.
With those simple words, he'd made her feel better.
MR.
THOMAS (cont'd) She's from out of town and she needs a little help in dressing.
Perhaps you could help her out.
Thank you very much.
She'll be right over.
He sets the phone down and smiles patronizingly at Vivian.
MR.
THOMAS (cont'd) There you are.
If you have any other problems, come ask for me personally.
I'm Mr. Thomas.
VIVIAN Barney.
She smiles mischievously.
A sleek corporate helicopter flies over the port.
Edward, Vance, Stuckey and Jake walk toward the building's edge.
They look out over the empty shipyard as Vance describes it.
VANCE Okay...
VANCE this is the jewel in Kross's crown.
VANCE We can strip out all the heavy equipment.
VANCE Some of the cranes are very valuable overseas.
VANCE The Japanese are salivating for them.
STUCKEY Prime industrial property straddling the Port of Long Beach and Los Angeles.
STUCKEY It gives me a hard-on.
Edward points toward one of the edges of the shipyard.
EDWARD What's that long building over there?
JAKE Storage, I think.
EDWARD Not with those smokestacks it's not.
VANCE Let me check.
Vance pulls out a notebook.
JAKE The real estate possibilities are endless.
JAKE Most of the yard we'll just level.
JAKE I talked to a couple of developers, under the table, of course, and they said
EDWARD You what?
JAKE I talked to some developers about the land.
STUCKEY What kind of an idiot are you?
STUCKEY You don't talk about this to anyone.
JAKE They're close friends, they'd never breathe a word --
STUCKEY Where did you dig this moron up?
VANCE He's right, Jake, that was an incredibly stupid thing to do.
VANCE It won't happen again, Edward.
VANCE I'll pull him off the project immediately.
EDWARD Don't bother.
STUCKEY What!?
EDWARD We don't have the time to bring someone new up to speed.
EDWARD Besides...
EDWARD You've already impressed everyone you need to, haven't you?
JAKE It won't happen again, Mr. Harris.
Vance has found what he was looking for in his notebook.
VANCE This is interesting.
VANCE That building is storage now, but it used to be a smelting plant.
VANCE They closed it down after World War
EDWARD I want our lawyers to check into the toxic waste licences on them right away.
EDWARD I want to know if the permits are still valid and what kind of limits are on them.
STUCKEY Jesus, yes.
STUCKEY It's a long shot but if the permits are still in effect, they're worth a fortune.
He turns away.
The other follow Edward back toward the stairs.
EDWARD What time's diner tonight?
STUCKEY Eight o'clock.
STUCKEY Kross is bringing his son.
STUCKEY Very bright kid, watch yourself with him.
STUCKEY Who's this girl you're taking?
EDWARD No one you know.
The elevator opens and Vivian walks out and surveys the room nervously.
She walks toward the women's clothing section.
BRIDGET, a large friendly woman, spots her and quickly approaches.
BRIDGET You must be Vivian.
Vivian nods.
BRIDGET (cont'd) Let's look at you...
She steps back, regards Vivian with a professional eye.
BRIDGET (cont'd) Where are you from, dear?
VIVIAN Georgia.
BRIDGET No wonder.
BRIDGET For starts, you should know that hot pants are horrid, even when you do have the legs to carry them off.
BRIDGET What are your plans while you're in town?
VIVIAN Well...
VIVIAN I might be going out to dinner.
BRIDGET You'll want a cocktail dress then.
BRIDGET Turn.
BRIDGET You have a beautiful figure.
BRIDGET A little too out in the open but simply lovely.
BRIDGET Size six?
BRIDGET Do you need shoes?
VIVIAN I dunno.
VIVIAN Do thigh high, leather boots go with a cocktail dress?
BRIDGET Philip!
BRIDGET We'll need shoes!
Bridget leads Vivian towards the racks of clothes.
She pulls out a dress.
BRIDGET Your uncle will like this.
VIVIAN He's not really my uncle.
BRIDGET They never are, dear.
Mr. Thomas is behind the desk.
He looks up.
Vivian is standing there, a happy look on her face.
She holds up a garment bag.
VIVIAN I got a dress.
MR. THOMAS I rather hoped you'd be wearing it.
VIVIAN I didn't want to get it messed.
VIVIAN I got shoes too.
VIVIAN Wanna see?
MR. THOMAS That's all right.
MR. THOMAS I'm sure they're quite lovely.
VIVIAN They were real nice to me there.
VIVIAN They treated me, y'know...
VIVIAN nice.
VIVIAN Thanks, Barney.
Mr. Thomas tries not to wince at the familiarity.
MR. THOMAS You're very welcome, Miss Vivian.
She smiles at him.
He watches as Vivian turns and walks toward the elevator.
The provocative way her hips move just naturally attracts the attention of a MALE PASSERBY.
And the white gloved ELEVATOR MAN literally leaps to press the elevator button for Vivian who rewards him with a happy smile.
Mr. Thomas sighs.
The phone is ringing Vivian enters.
She hurries to pick it up.
VIVIAN Hello?
The phone keeps ringing -- it has more than one line.
Vivian frantically punches buttons.
VIVIAN (cont'd) Hello?
What?
Hello?
Edward is in a private office.
EDWARD Never answer the phone.
EDWARD Ever.
VIVIAN Tsk, believe me, this will be the last time.
EDWARD Did you buy some clothes?
VIVIAN I got a dress, yeah.
EDWARD Just one?
EDWARD Christ...
EDWARD I hope it's appropriate.
VIVIAN It's very tasteful.
VIVIAN I think you'll especially like the zipper in the crotch.
VIVIAN I'm -- joking.
EDWARD Let's hope so.
EDWARD You'll get some more clothes tomorrow.
EDWARD I'll be pushed for time so meet me in the hotel lobby at seven forty-five sharp.
EDWARD Got it?
VIVIAN No, I don't "got it".
VIVIAN Even the farmboys back in Georgia come to the door when they're taking you on a date.
EDWARD This isn't a date.
VIVIAN Go by yourself then.
VIVIAN Where you taking me anyway?
EDWARD The Rex.
VIVIAN Any good?
EDWARD I think you'll approve.
VIVIAN ...
VIVIAN all right.
VIVIAN I'll meet you in the lobby.
VIVIAN But only cause you're paying me to.
EDWARD Thank you very much.
Vivian slowly sets the phone down.
The phone rings again.
Vivian, very carefully, punches the flashing button and picks it up.
VIVIAN Hello?
EDWARD I thought I told you not to answer the phone.
VIVIAN Oooh!
Edward hangs up.
He smiles to himself.
Vivian bites her fingernails, looking nervous.
The doorbell RINGS.
Vivian looks up, startled.
She rises, moves to answer it.
It's the Spanish MAID.
She nods politely at Vivian.
MAID Housekeeping.
MAID I come to turn down the bed.
MAID 5:00, I turn down the bed.
VIVIAN What?
The Maid points to her hotel badge, trying to explain.
MAID Housekeeping.
MAID I come to turn down the bed.
VIVIAN Okay.
The Maid enters.
VIVIAN Is there a trick to it?
The Maid turns down the bedspread.
VIVIAN Is that all?
VIVIAN You just fold back the bedspread?
MAID I also place las chocolates on the pillow.
VIVIAN Oooh, I love those.
MAID I leave extras, miss.
VIVIAN Thanks!
VIVIAN Consuelo, are all rich people so lazy they can't do this on their own?
Consuelo shrugs.
Mr. Thomas is still behind the desk, working when a soft voice startles him.
VIVIAN Barney.
He looks up.
He sighs.
Vivian still hasn't changed.
MR. THOMAS What is it, Miss Vivian?
VIVIAN Edward is taking me to some fancy place for dinner.
VIVIAN The Rex.
VIVIAN Ever been there?
MR. THOMAS It's a bit beyond my...
MR. THOMAS range, shall we say.
VIVIAN Yeah, mine too.
VIVIAN Is it like, y'know, normal?
MR. THOMAS I think you'll find it normal enough.
VIVIAN Will I like it?
MR. THOMAS You'll like it fine.
VIVIAN Okay.
VIVIAN Thanks, Barney.
VIVIAN You're the best.
She turns away.
MR. THOMAS Just mind which fork you use.
Vivian turns abruptly back, a horrified look on her face.
VIVIAN Fork?
An elegant formal placesetting complete with a myriad of different size forks, spoons, stacked china plates and crystal glassware.
ANGLE ON MR. THOMAS AND VIVIAN sit across from one another at a fully set table.
MR. THOMAS In fifteen minutes I can teach you everything you need to know to dine with the Queen.
MR. THOMAS First, as you pick up the knife you shift your fork to the left hand.
VIVIAN But I always eat like this.
MR. THOMAS Either you're European or badly brought up.
VIVIAN Hmmm...
VIVIAN I vonder vich.
MR. THOMAS Actually, some of the richest people I know have the worst manners.
MR. THOMAS Of course, Mr. Harris, being of old money, knows his way around a table.
MR. THOMAS All right now, pay attention please.
MR. THOMAS Salad fork.
VIVIAN What if they serve soup?
MR. THOMAS They will serve salad.
VIVIAN But what if they serve soup?
MR. THOMAS Then you use your soup spoon.
VIVIAN I like steak.
MR. THOMAS Then you would use your--
VIVIAN Steak spoon!
Mr. Thomas swallows his exasperation.
WE PULL BACK from their table to reveal the cavernous, empty banquets room, each table is set and ready for the dinner service.
MR. THOMAS Miss Vivian --
VIVIAN Maybe I'll just order a burger, Barney, that way I can eat with my hands.
MR. THOMAS Miss Vivian...
MR. THOMAS there's a salon here in the hotel.
MR. THOMAS Instead of worrying unnecessarily about table manners, why don't you just have your hair done instead?
VIVIAN Professionally?
Vivian sits in a salon chair.
The last customer, THANE, a young man of about twenty with his long hair pulled back in a pony tail, tilts her head one way and then another, eyeing her professionally.
VIVIAN I have a friend who has a friend who does Cher's wigs.
THANE I hate him already.
THANE All set?
VIVIAN Yeah...
VIVIAN what a ya say we chop it all off and bleach the tips.
THANE Darling?
THANE Trust me.
Edward enters and looks around the lobby.
No Vivian.
Annoyed.
Edward crosses to a house phone and picks it up.
He's about to dial when:
MR. THOMAS Good evening, Mr. Harris.
Edward looks at him blankly.
MR. THOMAS Barnard Thomas, manager of the hotel.
EDWARD Of course, yes.
EDWARD If you'll excuse me just a moment --
MR. THOMAS I have a message for you from your "niece", sir.
EDWARD My what?
MR. THOMAS The young lady staying in your room?
Edward's eyes narrow.
He hangs up the phone.
EDWARD I think we both know she's not my niece.
Mr. Thomas looks uncomfortable.
EDWARD (cont'd) Does this hotel have any problem with that?
MR. THOMAS Mr. Harris, a guest of yours, is a guest of ours and shall be treated accordingly.
MR. THOMAS The young lady asked me to tell you that she is waiting for you in the lounge.
EDWARD Thank you.
He starts towards the lounge.
MR. THOMAS Very intriguing young woman, Miss Vivian.
His tone stops Edward in his tracks.
MR.
THOMAS (cont'd) Have a good evening, sir.
And off he goes, leaving Edward to wonder what the hell transpired during the afternoon.
Edward enters the lounge.
He looks around, not seeing Vivian.
And suddenly his eyes go back to...
the beautiful girl with the beautifully styled hair in the beautiful black cocktail dress at the piano bar.
Edward tries to hide his surprise as Vivian rises, moves elegantly towards him.
She smiles.
VIVIAN You're late.
Such a beautiful woman deserves an apology and so, without thinking:
EDWARD I'm sorry.
VIVIAN You're forgiven.
She waits expectantly.
He holds out an arm.
She takes it.
Vivian comes out of the ladies room.
She walks forward past the MAITRE'D'S station.
She stops.
She takes a breath...
and then walks forward.
Vivian moves down a marble starircase, through the elegant restaurant toward a far table.
Her beauty and natural grace draw approving stares.
She is like a queen moving through a ballroom.
At a secluded table, Edward sits in conversation with two men.
JAMES KROSS, in his early 70's, a bulky self-made millionaire industrialist.
Sitting next to him is his son and second in command, DAVID KROSS, a handsome man in his early thirties.
All of them rise as Vivian comes to the table.
David Kross holds out Vivian's chair for her.
Surprised, she nods her thanks.
In front of her is an enormous placesetting.
She smiles down at the utensils, filled with confidence.
Waiters have placed a delicate salad down in front of each of them.
Vivian proudly reaches for her salad fork.
But then she sees that Kross has picked up the fork closest to his plate and is digging into his salad with that.
Vivian looks to see what Edward will do.
He doesn't seem interested in eating yet.
Neither does David Kross.
Feeling a sudden panic, Vivian puts her fork down.
KROSS So young man, I understand you are trying to take over my company.
A moment.
The abruptness of the question takes Edward back for a moment.
But then he almost smiles.
EDWARD Please don't patronize me, Mr.
EDWARD Kross.
EDWARD Our ages mean nothing here.
Kross and David look at each other.
DAVID Mr. Harris, we know you've purchased at least twenty percent of our stock.
DAVID We also know you plan to file a formal bid for a majority share.
EDWARD Twenty-five percent.
KROSS Mr. Harris, I built Kross Enterprises myself.
KROSS I know every man who ever worked there by his first name.
KROSS I know their wives...
KROSS and their children.
KROSS If your intention is to take over my company and turn it into a glorified real estate deal, think again.
Edward, thankfully, now reaches for his salad fork and begins to eat.
Relieved, Vivian picks up hers.
They all eat for a moment.
EDWARD What do you suggest, Mr. Kross?
WAITERS approach, some to clear the salad plates, some to put down the next course.
Vivian, thinking she's got to finish, quickly stuffs her mouth with the rest of her salad.
She is reluctant to let the Waiter take her fork.
KROSS What would it take to buy our stock back?
KROSS Name your price.
EDWARD To get me in a mood to sell -- double what I paid.
EDWARD But your company doesn't have enough capital right now to buy anything.
DAVID We're on the verge of closing a large navy contract.
DAVID Double is ridiculous but we can assure you a healthy profit on your shares.
DAVID We would give you a promissory note...
EDWARD You're not getting any navy contracts.
Vivian can see that both father and son are stunned by this news.
DAVID There's no way you could know that.
EDWARD But I do know.
EDWARD I also know your lines of credit are over-extended.
EDWARD If I don't buy your company, someone else will...
EDWARD Ah, the escargot.
Escargot are put down in front of everyone.
Vivian stares at them dubiously.
She picks up what she assumes is the next "right" fork.
She picks up a snail.
The two do not fit.
Flustered, she doesn't know what to do.
No one else seems to be eating.
And now a Waiter comes and places escargot forks at each place.
Vivian picks it up with a sigh of relief.
VIVIAN Scume me, what are these things?
WAITER Escargot, mademoiselle.
EDWARD Snails.
Vivian stares at them, horrified.
She, like James and David Kross, no longer seem interested in eating.
Edward eats with pleasure.
EDWARD Mr. Kross, I'm not here to sell you my stock.
EDWARD On the contrary, I'm here to buy yours.
KROSS You've got a lot of nerve.
EDWARD No.
EDWARD What I have is a lot of money.
KROSS I know all about you, Mr. Harris.
KROSS When you buy companies, they have a way of disappearing.
KROSS Even the pension funds are stripped clean.
KROSS The last three companies you took over were cut up in so many pieces, widows were left without their retirement checks.
EDWARD What I did with those companies was perfectly legal.
KROSS I don't question the legality of what you do.
KROSS It's your morality that makes me sick.
KROSS I will not allow my company to be raped by a man like you.
EDWARD It is not your company.
EDWARD It's a public company.
EDWARD And I am going to acquire it.
EDWARD Either I buy from the other stock holders, or I buy from you.
Vivian struggles with her escargot.
EDWARD (cont'd) I would suggest that you and your board cooperate with me, rather than fight a battle you don't have the ammunition to win.
Vivian suddenly ZINGS her snail across the table.
Everyone looks to her.
VIVIAN Slippery little suckers...
Kross rises.
KROSS If you'll excuse me young lady, Mr. Harris...
KROSS Deal with this, David, you know where we stand.
KROSS I need to go someplace and puke.
He rises.
He exits.
DAVID Men like my father built this country.
DAVID He was no saint.
DAVID He screwed people.
DAVID But for every guy he stepped on, he gave a hundred a good job.
Edward is silent.
VIVIAN He seems like a nice man.
David looks at Vivian as if seeing her for the first time.
EDWARD We can reach an understanding on this.
DAVID I don't think so.
DAVID You should know we're going to fight you with every resource we have.
EDWARD Do what you have to do.
EDWARD I don't take it personally.
DAVID I do.
DAVID I take it all very personally.
DAVID Very nice meeting you, Vivian.
David Kross gets up and leaves.
Vivian and Edward sit in silence.
EDWARD And that's the way the game is played.
VIVIAN Some game.
VIVIAN Screwin' some poor slob out of his retirement.
Edward says nothing.
But Vivian can see she's hit a nerve.
VIVIAN Snails for dinner.
VIVIAN No wonder everybody is in such a bad mood.
A Waiter appears at the table.
WAITER Are we ready for the next course, sir?
EDWARD No.
EDWARD Bring a check, please.
Edward's face is pensive and thoughtful as he stares out of the glass window down at the city lights.
He quickly drains his champagne glass.
Vivian moves to stand next to him.
She refills his glass from the bottle.
EDWARD Thank you.
He drinks.
Silence.
VIVIAN You're upset, huh?
EDWARD Upset.
EDWARD No.
EDWARD I never get upset about business.
VIVIAN You liked the guy, though.
EDWARD Whether I liked him or not is irrelevant.
EDWARD It's business.
EDWARD There's no emotion involved in business...
EDWARD if you want to survive.
VIVIAN We're the exactly the same!
VIVIAN Kit keeps telling me don't get emotional when you turn tricks -- that's why no kissing -- it's too personal.
VIVIAN The key is like you're saying, stay numb, don't get involved -- when I'm with a guy, I'm a robot, I just do it.
VIVIAN Except with you.
VIVIAN At your price I give my all...
Edward laughs.
VIVIAN (cont'd) Let's not talks about this heavy stuff.
Come on, relax.
Vivian comes up behind him.
She begins to rub his shoulders.
EDWARD That...
EDWARD is very good.
A moment.
Edward is silent.
Turns him, unknots his tie, unbuttons his collar.
VIVIAN Know what we're gonna do in a little while then?
VIVIAN We're gonna call Domino's and have'm deliver a bigass pizza.
VIVIAN We're gonna eat it in bed.
VIVIAN We're gonna veg' out and watch television.
EDWARD Television?
VIVIAN Yeah, it's this box, it has pictures, sound.
VIVIAN You don't have to use your brain at all.
EDWARD I have work to do.
VIVIAN Uh-uh.
VIVIAN No work.
Smiling, she softly kisses his throat.
VIVIAN (cont'd) See...
what you haven't figured out yet...
She kissed his neck.
She fumbles with his belt.
VIVIAN (cont'd) Is that while you're the boss everyplace else...
I'm the one in charge here.
She kisses his chest.
VIVIAN (cont'd) You...
just think you are.
She starts to kneel down.
He stops her.
They stare at one another for a moment.
He releases her.
She smiles.
She starts to undress him.
Vivian is asleep.
She turns over, slowly waking.
Her hand goes out to touch Edward and encounters nothing but empty bed.
Vivian comes awake with a sudden start.
She look around momentarily frightened, not sure where she is.
Sighing with relief, she lies back down.
She sees Edward's American Express card on the pillow next to her.
EDWARD Wake up, Vivian.
EDWARD Time to shop.
Edward comes out of the bathroom and moves toward the bed.
He is tying his tie.
Vivian sits up and ties it for him.
He smiles at her.
EDWARD I still don't understand why you only bought one dress.
VIVIAN I wasn't as much fun as I thought it was going to be.
EDWARD Why not?
VIVIAN Well, you know those cold bitches that work in those stores and try to intimidate you?
VIVIAN It works.
EDWARD Was someone rude to you?
VIVIAN I had a little problem in one store.
VIVIAN I wasn't dressed right.
VIVIAN I don't know what to say.
VIVIAN I don't belong there.
VIVIAN Maybe I'll just go back to Bridget.
VIVIAN She was cool.
EDWARD Vivian, you belong wherever you are.
EDWARD I don't care how you were dressed, they were the ones who were wrong, not you.
Edward sits on the bed.
EDWARD (cont'd) People aren't going to respect you unless you respect yourself.
The next time someone is rude to you, you stare at them right here.
He softly touches her, right between the eyes.
EDWARD (cont'd) It's an old trick I use, especially with bankers.
Works every time.
Will you try it?
VIVIAN Okay.
EDWARD Good.
VIVIAN Come with me?
Edward looks at his watch.
Vivian covers it with her hand.
VIVIAN Please.
A beautiful, chic women's shop.
The haughty SALESGIRL approaches Vivian near a rack of dresses.
Edward hovers in the b.g.
VIVIAN Hello.
VIVIAN Can you help me?
The Salesgirl looks Vivian up and down.
A Pause.
Vivian gives her "the stare" and straightens up.
We see the Salesgirl's reaction change.
VIVIAN I'm looking for a dress, nothing too flashy, not too sexy, conservative.
VIVIAN In a size six.
(uncomfortable under Vivian's stare) Do...
do you have a charge account with us?
Vivian smiles and draws out Edward's American Express card.
The Salesgirl nods and quickly moves to a rack of dresses to find Vivian's size.
Vivian tries on different clothes under Edward and the Salesgirl's supervision.
Vivian comes happily out of the dressing room wearing a low cut, spangled and fringed outfit.
Edward shakes his hand.
The Salesgirl holds a classic tweed ensemble over Vivian's outfit.
Vivian scowls.
VIVIAN I look like fucking Nancy Reagan.
The Salesgirl shows Edward clothes by Ann Taylor.
He turns to find Vivian happily holding up a tiny, low cut leather dress.
Edward shakes his head in mock disapproval.
Vivian scowls.
Vivian is wearing an elegant pastel dress.
Edward is standing at the store's bar, watching and talking on the telephone.
Stuckey and Vance are pouring over stock reports, talking to Edward on the speaker phone.
VANCE Kross came out of his corner swinging.
VANCE He started buying up all available stock as soon as the market opened.
EDWARD He's a tough old son of a bitch...
Edward is watching Vivian.
She pulls the hem of her skirt up to mid thigh.
She looks hopefully over to Edward.
Edward shakes his head.
VANCE It's up to ten and a quarter.
EDWARD Offer nine and a half.
EDWARD Bring them back down to earth.
STUCKEY Goddamit!
STUCKEY Where is he getting the money to fight?
EDWARD Someone's loaning it to him.
EDWARD Get on it right away.
STUCKEY Our contract guys are working on the Kross pension funds.
STUCKEY There's another forty million there.
STUCKEY We can bleed'm dry.
There is a sudden hesitation in Edward's eyes.
He watches as Vivian tries on a hat.
She preens for him.
He smiles.
EDWARD Put the pension funds on hold until I say otherwise.
STUCKEY We're letting them slide?
EDWARD I want the treatment plant licenses to be top priority right now.
STUCKEY But, Edward...
EDWARD Do it.
Edward hangs up and takes a long look at Vivian.
She moves to him.
EDWARD You're on your own now, Vivian.
EDWARD I've got to get to work.
EDWARD Be sensible and you can keep everything.
EDWARD Spend too much and it all goes back.
Vivian hugs him again.
Vivian walks along Rodeo Drive.
She looks lovely in the pink dress and new, white shoes.
A pretty, white hat is the final touch.
She carries a bag containing her old clothes.
She stops at a trashcan and ceremonially throws the offending items away.
We SEES Vivian in each department within the store with different SALESPEOPLE.
She happily and confidently tries on a variety of dresses, hats, shoes, accesarries, etc.
1) Vivian is in a dressing stall.
She tosses a dress out to a waiting SALESWOMAN.
VIVIAN Not me!
2) A SALESWOMAN holds a long, purple evening gown.
VIVIAN Horrid!
3) Vivian is admiring a pair of beautiful suede dress pumps.
Her attention is drawn to the SALESMEN'S exotic hand-painted tie.
VIVIAN Where'd you get your tie?
4) Vivian stands in front of an enormous tie rack with the Salesman, a dozen wild, swirling designed ties are hanging over his outstretched arm.
Vivian picks out the brightest one and smiles.
Vivian's arms are filled with clothing boxes and bags.
She feels like she owns the block.
A well-dressed MAN passes by, smiling politely.
Vivian's nose lifts as she happily ignores him.
Suddenly Vivian stops.
She's about to pass the shop she was thrown out of.
Vivian takes a breath and enters the shop.
Vivian enters.
The moment she steps through the door, Vivian's courage leaves her.
The saleswoman is waiting on a CUSTOMER.
SALESWOMAN Isn't this lovely?
SALESWOMAN I think it would look wonderful on you.
Vivian musters her courage.
She takes a deep breath and starts forward.
SALESWOMAN Would you like to try it on?
VIVIAN 'Scume me.
Both the saleswoman and her customer look up.
The saleswoman smiles pleasantly.
SALESWOMAN Yes?
VIVIAN Do you remember me?
SALESWOMAN No, I'm sorry, I don't.
VIVIAN I was in here yesterday.
Vivian slowly raises her middle finger.
The recognition starts to dawn in the saleswoman's eyes.
Vivian's courage begins to return.
VIVIAN Yeah.
VIVIAN That's right.
VIVIAN It's me.
VIVIAN I want you to know something.
VIVIAN You made me feel terrible.
VIVIAN I wasn't dressed right and you said I didn't belong here.
VIVIAN Well, I do.
VIVIAN You're the one that was wrong, not me.
VIVIAN And I want to tell you something else.
VIVIAN I'm never gonna shop here again as long as I live.
And with that, Vivian turns and walks out.
The saleswoman is stunned.
A beat.
The customer thrusts the dress into the saleswoman's arm as if offended by Vivian's speech and leaves the store also.
Mr. Thomas looks up from the desk.
And stares.
Vivian and a BELLHOP stroll through the hotel entrance and across the hotel lobby to the elevator.
The bellhop's arms are packed with boxes and shopping bags.
Mr. Thomas can't help it.
He smiles to himself.
Vivian opens the front door for the Bellhop who carries in her packages.
She motions for him to place them on the couch.
He does.
Vivian happily tips him with a five dollar bill.
He exits.
The door closes.
VIVIAN Wheee!!!
Vivian does a giddy spin and falls onto the couch.
Stuckey enters.
Edward is standing at the end of a long meeting table.
He is serving himself coffee from a tray.
STUCKEY You were right.
STUCKEY Kross mortgaged everything he has down to his grandson's college tuition to secure loans from a bank.
STUCKEY Not just any bank.
STUCKEY One we do business with.
Edward just sips his coffee.
STUCKEY (cont'd) It goes without saying that your business means a great deal more to them than our friend Kross's.
All you have to do is make a call.
Edward is silent.
Stuckey is again surprised.
STUCKEY Excuse me for saying this but what is wrong with you this week?
STUCKEY First, you go soft on the pension funds.
STUCKEY Now, you're giving him the chance to get away?
STUCKEY As of two minutes ago, you are committed to the tune of over fifty million dollars --
EDWARD Come on, Bill, don't talk to me about how much money's involved.
EDWARD It's my money.
STUCKEY And some of it's mine.
STUCKEY Edward, his jugular's exposed.
Edward hesitates.
Then:
EDWARD Get the bank on the phone for me.
Edward enters.
He closes the door.
He turns.
And stops.
A beautiful, candlelit, food laden table has been set up in the middle of the room.
Champagne and wine chills in a bucket.
A fire burns in the fireplace.
Music is playing.
VIVIAN Hi.
Edward turns.
And stares again.
Vivian stands in the bedroom doorway.
She is wearing an exquisite silk dressing gown.
She looks incredibly beautiful.
VIVIAN I thought maybe you'd like dinner.
EDWARD Thank you.
EDWARD I would.
EDWARD Nice.
VIVIAN Wait till you see what I have on underneath.
EDWARD Please.
She opens the dressing gown.
What she has on underneath is absolutely nothing.
Edward crosses to her.
Taking her in his arms, he lifts her up and kisses her breasts.
VIVIAN What about dinner?
EDWARD Dinner can wait.
The bathroom is lit by candles.
Vivian and Edward are in the marble tub.
Vivian sits behind Edward.
She lazily washes his shoulders and back with a large sponge.
VIVIAN You always been rich?
EDWARD No.
VIVIAN Seems like it.
VIVIAN I guess it's easy to get used to, huh?
EDWARD Easier than learning how to be poor.
EDWARD My father's family was wealthy.
EDWARD When I was young there were cars and houses, private schools, nannies.
EDWARD But then my father divorced my mother to marry another woman.
EDWARD And he took his money with him.
Silence.
VIVIAN Keep talkin'.
VIVIAN I like hearin'.
EDWARD Not much to tell.
EDWARD I went to public school.
EDWARD Went to university on scholarship.
EDWARD Went to work for an investment firm.
EDWARD In eight years I owned it.
EDWARD My father was chairman of the board of the third company I ever went after.
EDWARD I swallowed that company and shit out the pieces.
EDWARD One of the pieces was him.
Vivian softly traces small patterns on Edward's shoulders with a finger.
VIVIAN You still mad at'm?
EDWARD He died a long time ago.
She gently rests her head on his back.
PANNING BELLIES People are sunbathing by the pool.
Overweight...
lobster red...
old and stretch-marked...
fishy white...
and then gorgeous.
The gorgeous is Vivian.
She is wearing a miniscule bikini and sunglasses.
WAITER Miss Vivian?
She looks up.
A young WAITER, looking a little dry-mouthed at the sight of her, is holding a telephone.
WAITER You have a call.
WAITER Mr. Harris.
VIVIAN Hi, baby.
VIVIAN I'll be ready.
VIVIAN Bye.
She hangs up.
She looks at the Waiter, confused.
VIVIAN What do you wear to polo?
Horses and riders crash and careen on the playing field.
An enthusiastic crowd cheers.
DOWN OFF THE EDGE OF THE FIELD a tailgate party using Cadillacs and Rolls Royces is in progress.
Horses and riders thunder by a crowd of very well-dressed, successful-looking people -- celebrities, execs, socialites, aficionados -- most of whom ignore the game.
They are there to see and be seen much more than to watch a polo match.
Vivian and Edward make their way towards the party.
Edward is wearing his new tie.
Vivian is looking very chic and beautiful in one of her new outfits.
Not that it's helping -- the place, the people, the wealth -- everything here suddenly has her overwhelmed.
She suddenly stops.
VIVIAN You're really pushing it, bringing me here.
EDWARD I think it's exciting.
VIVIAN What id we run into someone I know?
EDWARD I really doubt anyone here frequents Hollywood Boulevard.
VIVIAN You did.
A VOICE calls out.
STUCKEY Edward!
They turn.
William Stuckey is with a group of people.
He waves them over.
STUCKEY (cont'd) Come on!
Over here!
Edward takes Vivian's arm and leads her forward.
Stuckey grins and shakes Edward's hand.
STUCKEY Well, well, well...
Vivian dislikes this guy on sight.
Dislikes the frosty looking woman at his side.
EDWARD Bill, I'd like you to meet Vivian.
STUCKEY Bill Stuckey, Vivian.
STUCKEY My wife, Elizabeth.
VIVIAN Hi.
Elizabeth Stuckey stretches her thin lips in a cold smile.
STUCKEY Lots of fun people here.
STUCKEY Let me get you two some champagne.
He moves quickly away.
ELIZABETH STUCKEY Excuse me.
She moves to greet someone else.
Vivian and Edward survey the milling CROWD.
VIVIAN Real genuine guy.
EDWARD He's good at what he does.
VIVIAN You could freeze ice on his wife's ass.
VIVIAN She anything like your ex?
EDWARD Shall we mingle?
A goal is scored.
Edward watches and guides her, Vivian sips champagne and meets and chats and wins over different PEOPLE.
A group of PEOPLE.
WOMAN I simply love your dress, Vivian.
VIVIAN This old thing?
WOMAN Of course, a figure like yours can wear anything.
WOMAN You must work out constantly.
VIVIAN I lead a very physical life.
Are you into running, Vivian?
VIVIAN I'm into walking.
VIVIAN I walk a lot.
In another group of PEOPLE.
You look awfully familiar, Vivian.
Haven't we run into one another at the spa in La Costa?
VIVIAN Well, I do often spa there.
Edward and Elizabeth Stuckey watch Vivian laugh and chat with a group of WOMEN.
ELIZABETH STUCKEY Edward, she's marvelous.
ELIZABETH STUCKEY Warm and witty and down to earth.
EDWARD She is, isn't she.
ELIZABETH STUCKEY So unlike your usuals.
ELIZABETH STUCKEY Where on earth did you find her?
Edward smiles enigmatically.
Taking an hors d'oeuvres off a passing WAITERS's tray, he starts forward.
We're good together.
He has to admit it.
I've been just what he wants me to be.
I say the right things, I know the right people, I give wonderful parties.
No question, no arguments, no embarrassments.
It works for both of us.
That makes Vivian think.
And then she smiles as she sees Edward approaching.
Vivian moves to him.
VIVIAN Edward, these women here, I don't think any of'm like the guys they're with.
VIVIAN They're just into it for the money.
EDWARD I'm sure that's true for some of them.
VIVIAN I thought I was the pro.
VIVIAN These women make me feel like an amateur.
EDWARD Ready to stomp sod?
The CROWD engages in sod stomping.
They drink champagne.
They make a dance out of it.
They laugh.
Shoes get stuck in the mud.
It's ludicrous -- these people in their suits and fancy clothes, replacing divots and stepping over the horse shit.
In a corner of the field, grazing horses stare, seemingly in disbelief.
Vivian is having a wonderful time.
And then, as she moves towards the outside of the crowd she sees someone staring at her from over among some of the riders and grazing horses.
David Kross smiles at Vivian.
She hesitates...
and then she crosses towards him.
Hi.
VIVIAN Hi.
VIVIAN I never thought stomping in grass could be so much fun.
DAVID I like your hat.
VIVIAN Huh?
VIVIAN Oh...
VIVIAN yeah.
VIVIAN S'okay?
VIVIAN Uhm...
VIVIAN how're...
VIVIAN business things going.
DAVID Let's not talk about it, it's too depressing.
DAVID Come on, I'll show you Thunder.
VIVIAN Please, we hardly know each other.
DAVID Thunder's a horse.
DAVID Come on.
They approach the sweating mount.
David Kross caresses the horses muzzle.
DAVID Hey, big guy, you getting tired, yet?
DAVID I am.
DAVID This is Vivian.
DAVID You two been together long?
DAVID You and Edward?
VIVIAN No.
DAVID Hope to be?
To Vivian's surprise, the question causes a pang inside.
VIVIAN It's...
VIVIAN it's not like that.
DAVID I see.
DAVID Well.
DAVID Maybe that means you'd have lunch with me sometime then.
Vivian is suddenly silent.
She looks away.
DAVID (cont'd) I'm sorry, am I being too forward?
VIVIAN You don't know anything about me.
DAVID I'd like to find out.
DAVID You don't know anything about me either.
DAVID That's why people have lunch.
But something holds Vivian back, a feeling.
William Stuckey turns...
stops...
stares.
He sees Vivian and David Kross standing together.
He stares, his mind racing, and anxious, angry look on his face.
Stuckey has Edward off to the side.
He is talking to him in a low, earnest voice.
STUCKEY Fill me in on this.
STUCKEY How'd you and Vivian meet?
EDWARD We just did.
STUCKEY Come on, you can tell me.
STUCKEY I sure would like to know where a guy runs into a girl as attractive as this.
EDWARD The night I left your house, I was lost.
EDWARD I was looking for directions.
STUCKEY And you just happened to run into her.
STUCKEY Great.
STUCKEY What's she do?
STUCKEY She work?
EDWARD Yes...
STUCKEY Doing what?
EDWARD Vivian's in sales.
STUCKEY Sales, really?
STUCKEY That's great.
STUCKEY What does she sell?
Edward's eyes narrow.
EDWARD Why do you want to know?
STUCKEY Hear me out.
STUCKEY I've known you a long time.
STUCKEY I see a difference in you this week.
STUCKEY Like that tie.
STUCKEY I'm suddenly wondering if this girl's not the difference.
STUCKEY Especially when I see her talking with David Kross.
Vivian turns away from the bar, now holding two glasses of champagne.
She scans the crowd for Edward.
EDWARD She met him at dinner last night...
EDWARD I like this tie.
STUCKEY So now they're best friends?
STUCKEY Edward, this girl appears out of nowhere and now I see her talking to a guy whose company we're trying to buy.
STUCKEY It's too convenient.
EDWARD You're being ridiculous.
STUCKEY Industrial espionage is not ridiculous.
STUCKEY Edward, how do you know she hasn't attached herself to you so she can bring Kross back information?
EDWARD Christ, Bill, she's not a spy, she's a hooker.
EDWARD I picked her up off Hollywood Boulevard.
EXT. EQUESTRIAN CENTER - ANGLE ON VIVIAN as she hear loud sudden LAUGHTER.
She turns.
She sees that it's Stuckey laughing.
Smiling, Vivian starts towards them with two glasses of champagne.
STUCKEY I swear to God, you are the only millionaire I ever heard of who'd go looking for a goddam bargain streetwalker!
Edward sees Vivian coming.
EDWARD Let's drop it, shall we?
Edward turns.
He smiles gently as Vivian quietly approaches and hands him his glass of champagne.
A group of BUSINESSMEN are standing a short distance away.
One of them calls out:
MAN Edward!
MAN May we have your opinion on something?
EDWARD Excuse me a moment.
He moves to join the group of men.
Stuckey gives Vivian a broad smile.
STUCKEY Having a good time, Vivian?
VIVIAN Yeah.
VIVIAN Thanks.
STUCKEY All this must be quite a change from Hollywood Boulevard.
Vivian looks as if she's been struck.
VIVIAN What?
STUCKEY It's okay.
STUCKEY Edward told me.
STUCKEY Your secret's safe with me.
Stuckey runs his hand up her arm.
STUCKEY (cont'd) What do you charge, Vivian?
Maybe you and I could get together after Edward leaves.
VIVIAN Yeah.
VIVIAN Sure.
VIVIAN Why not.
VIVIAN Call me at the Regent Beverly Wilshire.
STUCKEY I just might do that.
He moves away.
Vivian turns.
Edward looks up from his conversation, sees her looking at him.
He smiles, raises his glass in a small toast.
A moment.
Vivian toasts him back.
They enter.
Edward switches on a light.
Vivian comes down the steps into the room.
Edward follows after her.
EDWARD You're awfully quiet.
EDWARD You haven't said a word since the party.
As Edward touches her shoulder, Vivian suddenly spins and explodes with anger.
VIVIAN You asshole!
VIVIAN I can't believe what a --!
EDWARD Vivian, what the --
Tears well in Vivian's eyes as she yells at him.
VIVIAN Clean the slut up, take her out, huh?!
VIVIAN What are you trying to prove!?
VIVIAN I'm not a piece of meat for you to offer to your friends!
EDWARD I don't know what you're talking about.
VIVIAN I've been with stinking old men who've made me want to puke but I've never had anyone make me feel as dirty as you did tonight.
EDWARD Would you please calm down.
EDWARD Tell me what happened.
VIVIAN Stuckey!
VIVIAN He wants an "appointment" with me after you leave.
VIVIAN You my pimp now or did he think that up on his own?
Edward looks guiltily away.
EDWARD What was I supposed to do?
EDWARD I told the truth.
EDWARD Why should the truth upset you?
EDWARD It's not as if you're from a convent.
VIVIAN I want my fucking money.
VIVIAN I'm getting out of here.
VIVIAN I don't want anything more to do with you.
EDWARD Can we talk about this?
EDWARD Can you just try to calm down?
VIVIAN Your goddamned friend, he thinks the only reason I'm with you is for the money.
A tear falls from Vivian's eyes.
VIVIAN Well, it's true.
VIVIAN Just pay me what you owe me and I'm gone.
EDWARD Vivian...
VIVIAN Pay me!
VIVIAN Before I pick up this chair and smash your face in.
EDWARD Fine.
EDWARD I'm only here a couple of more days and I'm not going to spend them fighting with you.
VIVIAN Fuck off.
EDWARD I'll call you a cab.
EDWARD If you want the clothes, pack them up.
Vivian stands quietly for a moment.
And then she turns and walks into the bedroom.
Vivian starts roughly picking up her clothes in the dim light of the bedroom.
As she does she starts crying.
With each item of clothing the tears come down harder.
Edward appears at the doorway.
His face is genuinely concerned.
EDWARD Vivian...
EDWARD I'm sorry.
EDWARD I wasn't prepared for questions about us.
EDWARD It was an idiotic and insensitive thing I did.
EDWARD I should have known that it would hurt you.
VIVIAN I'm not hurt.
VIVIAN It doesn't hurt you when somebody pisses on you, it just pissed you off.
EDWARD I really am sorry.
Vivian lets the clothes fall from her arms.
Sobbing, she stands limply.
VIVIAN You hurt me.
Edward goes to her and wraps his arms around her shoulders.
She touches his hand.
He sits on the bed.
He pulls her to him and wraps his arms around her, holds her tight.
EDWARD I'll make it up to you.
Edward, carrying a briefcase, moves jauntily down a long hallway.
Stuckey trails after him.
STUCKEY This is no time to disappear.
STUCKEY We're in too far.
EDWARD Bill?
EDWARD Stop panicking.
EDWARD Kross isn't going anywhere and I don't need to spend the rest of the day watching his stock go down.
EDWARD I'll be in the office tomorrow.
STUCKEY Promise me you'll read those contracts by then.
EDWARD Goodbye, Bill.
Stuckey stops.
He calls after Edward.
STUCKEY Shit...
STUCKEY By tomorrow, Edward!
Edward hurries on.
Edward exits out of his limo and walks to the front doors.
Edward smiles, moving jauntily to the elevators.
Mr. Thomas at the front desk notices Edward's happy mood.
MR. THOMAS Good afternoon, Mr. Harris.
EDWARD Afternoon.
Edward's attention is taken by the glittering jewelry display in the hotel jewelry store window.
He detours from the elevators and moves to the window for a closer look.
He thinks a moment and enters the jewelry store.
Vivian comes out of the bedroom into the living room wearing an elegant red sequined evening dress.
She looks incredibly beautiful.
She sees the phone.
A thought occurs to her and going to it, she picks it up.
Waits.
VIVIAN C'mon, Kit...
No answer.
She hears someone at the door.
She hangs up.
Edward enters.
He is carrying a small case.
He stops at the sight of Vivian.
VIVIAN Do I look okay?
EDWARD Hmm...
EDWARD let's see...
EDWARD no, there's something missing.
He holds up the small case.
VIVIAN What's that?
EDWARD I don't want you to get too excited...
EDWARD these are on loan...
EDWARD however...
Vivian's jaw drops.
Edward is holding a diamond and ruby necklace in his hands, holds it as if it might melt if he breathed too hard.
Edward behind Vivian, fastens the necklace around her neck.
EDWARD This is made for a princess.
EDWARD I think she'd approve of you wearing it tonight.
EDWARD There.
EDWARD Come look.
He leads her to a mirror.
She stares at her reflection.
VIVIAN Edward, I can't.
EDWARD Shush.
EDWARD Of course you can.
VIVIAN What if I lose it?
EDWARD You won't.
VIVIAN What if someone tries to steal it?
EDWARD I'll guard them and you with my life.
A limo pulls onto the tarmac at Burbank Airport.
A PILOT in a leather jacket and sunglasses hurries forward to open the limo door.
Edward -- now wearing evening clothes -- and Vivian climbs out of the limo.
Your plane is ready to go, Mr.
Harris.
EDWARD Very good.
VIVIAN Plane?
Taking her arm, Edward leads her across the tarmac.
EDWARD You don't want to go all the way to San Francisco in a limousine, do you?
EDWARD I don't.
VIVIAN Where are you taking me!?
EDWARD To meet some friends.
EDWARD Rudolpho, a poet...
EDWARD Benoit, a landlord...
EDWARD Mimi, a flower maker...
VIVIAN Huh?
EDWARD The opera.
Up ahead is a waiting private jet, its engines already HUMMING.
She is speechless.
Edward grins, loving the look on her face.
The corporate jet takes off down the landing strip.
Edward and Vivian are alone in the passenger lounge of the jet.
Vivian can't believe the cabin.
It is a comfortable room featuring a long couch that curves across two walls, built in bar, television and stereo.
Edward is once again, going over papers.
VIVIAN I've never been on a plane before.
EDWARD I'm glad you like it.
EDWARD Now be quiet, I've really got to read these.
Vivian fluffs her hair up.
She makes a happy, excited growling sound -- Rrrrr!
A wicked gleam comes to her eye.
She walks over to Edward and stands in front of him.
He looks up.
She parts the thigh high slit in her gown to expose silken quarters.
She begins to unfasten the garters one at a time.
EDWARD Vivian, what do you think you're doing?
Edward watches silk stockings slide down Vivian's lovely legs.
VIVIAN Being quiet.
She reaches out and gently caresses Edward's face.
Edward sets down his papers.
The setting sun casts an incredibly glow over the city and the coast.
VIVIAN You ever been in love with anyone?
Vivian is at the window, looking out.
She carefully puts her earrings back on.
She stares, mesmerized by the skyline, the golden gate bridge in the distance.
She turns.
Edward is buttoning his shirt.
He is silent.
VIVIAN Sorry.
VIVIAN You're not paying me to ask you question like that.
EDWARD Vivian.
EDWARD I'm paying you to be you.
EDWARD Be you.
EDWARD Have you?
EDWARD Ever been in love with anyone?
VIVIAN You mean, besides Elvis?
VIVIAN I'm a human being.
VIVIAN Sure.
VIVIAN Once.
VIVIAN First time I ever ran away from home, I got as far as Atlanta.
VIVIAN I met this boy.
VIVIAN He'd been with his parents on their way to Chicago.
VIVIAN They stopped at a gas station.
VIVIAN He went to the john.
VIVIAN When he came back they'd split.
VIVIAN We sorta started looking out for each other.
VIVIAN Aw, he was sweet.
VIVIAN And boy, was he good looking, y'know, dark hair and eyes.
VIVIAN The chicken hawks were on him all the time.
VIVIAN He hated that.
VIVIAN Sometimes we'd find a safe place to crash nights and we'd curl up together and we'd talk about all these crazy things.
VIVIAN The two of us getting married someday.
VIVIAN Having kids.
VIVIAN Stupid stuff.
EDWARD What happened to him?
A moment.
Vivian shrugs.
VIVIAN My father found me.
VIVIAN Dragged me home.
VIVIAN I don't know why, he never seemed to like me much when I was there.
VIVIAN 'Cept when he was drunk, then he liked me a whole lot.
VIVIAN I made it back to Atlanta a year later.
VIVIAN Andy was gone.
Silence.
Vivian stares out the window.
VIVIAN Aw, but things sure look fine when you're sitting way up high.
Edward moves close to Vivian and putting an arm around her shoulders, stares with her out at the view.
Vivian rests her head against him.
An airport limo pulls to a stop in front of the San Francisco Opera House.
The DRIVER walks around back and opens the passenger door.
Edward emerges and helps Vivian out.
Edward puts his hand on Vivian's elbow as they walk through the elegant lobby.
EDWARD Some people say that opera is an acquired taste, but I don't believe it.
EDWARD You can always tell when someone goes to the opera for the first time.
EDWARD They either love it or hate it.
EDWARD Those who love it will always love it; those who hate it might come to appreciate it, but they'll never truly love it.
Vivian is wide eyed as they walk past a beautifully lit fountain with several graceful statues in its center.
Everywhere she looks she sees elegantly dressed WOMEN and prosperous looking MEN.
It makes her nervous.
Without realizing it, she raises a protective hand up to her necklace.
She looks as if she suspects someone is going to step up and steal it.
EDWARD Viv?
EDWARD I really doubt if anyone here is going to try and grab it.
Vivian reluctantly lowers her hands.
A crowd of PEOPLE mill around the lobby, heading toward their seats.
Vivian is aware of the looks she draws as she passes -- curious, even envious looks from the WOMEN, appreciative glances from the MEN.
Her hands again rises nervously to her necklace.
EDWARD They all think you look very beautiful, Vivian.
Vivian gives him a grateful look.
Relaxing, she lowers her hand from the necklace.
With a flourish, he offers his arm.
She takes it.
They start forward.
Edward and Vivian take their seats in a box high above the stage.
VIVIAN If it's in Italian, how will I know what they're saying?
EDWARD I'll whisper some of the main parts of the story to you.
EDWARD But you'll be surprised how much you understand.
EDWARD The music conveys the story more powerfully than any words.
VIVIAN But don't they have it in English?
EDWARD Vivian, don't be afraid of what you don't know.
EDWARD That's the fun of it.
The lights dim.
VIVIAN Okay.
VIVIAN Even if I hate it, I'm glad you brought me.
The orchestra begins to play.
Vivian's eyes focus intensely on the stage, as if a new world is about to be revealed to her.
IN A MONTAGE OF IMAGES AND MUSIC - LA BOHEME is performed.
The lights from the stage dance across Vivian's face.
Edward leans over to translate the tenor's aria.
EDWARD What am I?
EDWARD I am a poet.
EDWARD Not a man of wealth but one rich in dreams.
EDWARD You have come to replace my vanished dreams.
EDWARD I dwell now only in your eyes.
The MUSIC ebbs and swells.
The sets and costumes change.
The story continues.
Edward again leans close to Vivian.
EDWARD And now she asks Rudolpho if he still thinks her beautiful --
Vivian raises a hand and gently covers Edward's mouth.
Her eyes are fixed on the stage.
She doesn't need his help.
The emotions building inside Vivian swell as the music is reaching its tragic climax.
Her lips tremble.
Her eyes fill with tears.
Edward glances at her.
He studies her a long moment, watching the emotions play unashamedly across her face.
Strangely moved, he takes Vivian's hand.
As the opera ends, they are both swept away by it.
As the lights come up, Vivian wipes off her tear-ruined mascara.
She sighs, happy.
The WOMEN in the next box smile at her.
Did you enjoy the opera, dear?
VIVIAN It was so beautiful I just about pissed my pants.
Edward smiles at the now shocked looking Older Woman and he and the still misty Vivian exit.
Edward and Vivian sit side by side.
EDWARD If you'd gone on about how much you liked it, I'm not sure I'd have believed you.
VIVIAN I more than liked it.
EDWARD I know.
EDWARD I'm glad.
VIVIAN Did you?
EDWARD Yes.
EDWARD I've never enjoyed it more.
EDWARD Thank you.
Vivian looks at him a moment.
And then, leaning slowly forward she kisses him gently on the mouth.
He looks at her surprise.
He puts his arms around her and kisses her back.
It is the first time they've kissed and they make it very special.
The plane flies in the night.
Back to L.A.
IN A SERIES OF CROSS FADES Edward and Vivian make love.
Equally giving, equally taking.
No masks, no shields.
In the darkened bedroom, Edward and Vivian lie together.
Edward cradles Vivian.
Her back rests against his chest.
His arm is over her body.
She takes Edward's hand in her hands and carefully examines it; marveling at the fingers, the tiny hairs on the back.
She gently kisses the palm.
VIVIAN Love you...
She clutches Edward's hand tightly to her breast.
She closes her eyes, ready to sleep now.
His eyes open.
Vivian's whispered endearment has filled with him with sudden confusion and uncertainty.
He stares into the dark, wondering what to do with the woman in his arms.
The phone rings.
Edward immediately reaches out and picks it up.
He is dressed in a robe.
Breakfast is on the umbrella'd table in front of him.
EDWARD Yes?
Stuckey, not even dressed yet, paces around his desk.
STUCKEY Did I wake you?
EDWARD I'm up.
STUCKEY I had to call.
STUCKEY I jus got off the phone with James Kross.
STUCKEY Get this.
STUCKEY He wants to see you.
STUCKEY Today.
EDWARD Why?
STUCKEY He wouldn't say.
STUCKEY Edward...
STUCKEY I think we got him.
STUCKEY His nuts are on the block and we got him.
STUCKEY You there?
EDWARD Give me twenty minutes.
STUCKEY We'll be there.
STUCKEY Listen, if he's really caving in, we'll go from there down to the office.
STUCKEY I want him to commit his stock to us this morning.
Edward hangs up.
His mind seems on other things.
He rises.
Vivian is still asleep.
She is face down on the bed, the sheets just covering her to her waist.
Edward stares down at her.
He gently reaches out and runs a finger down the soft line of her spine.
Vivian murmurs contentedly.
VIVIAN Mmm.
VIVIAN Hi.
Edward smiles at her softly.
And then:
EDWARD Better get dressed.
EDWARD We're having guests.
Vivian is wearing her yellow dress.
She stares at herself in the bedroom mirror.
Her hair...
her make-up...
she realizes how different she is now, realizes that she likes it.
Edward comes out of the bathroom.
He crosses to the closet for a tie.
VIVIAN Here.
VIVIAN Let me.
She comes over, starts to tie his tie for him.
He is very aware of the closeness of her.
She smiles at him.
He smiles; puts his hand on her stopping her for a moment.
Looking up, she sees that he is serious now; no more jokes.
He releases her hand.
EDWARD One more night and you're finally rid of me.
VIVIAN Yeah, you've been pretty tough to take.
EDWARD I have to go to New York tomorrow.
Vivian says nothing.
EDWARD (cont'd) But I'll be back in Los Angeles.
Soon.
I'd like to see you again.
I thought we could work out something...
An arrangement.
Vivian is silent.
EDWARD (cont'd) I'll get you an apartment, buy you a car --
Vivian sighs, letting something go inside.
Finished with his tie, she turns away.
EDWARD (cont'd) What is it?
VIVIAN What else?
VIVIAN You gonna leave some cash by the bed when you pass through town?
EDWARD It wouldn't be like that.
EDWARD I want to get you off the street.
EDWARD You'll have a different kind of life.
EDWARD What's wrong with that?
VIVIAN I'm sorry.
VIVIAN That's very sweet, Edward, and I know you mean it...
She is silent.
EDWARD Vivian, I've thought about this a lot.
EDWARD This is the best solution.
VIVIAN When I was a little girl, my mother locked me in the attic when I was bad, which was pretty often.
VIVIAN I'd stare out the window up there and make believe I was a princess trapped in the tower by the wicked queen.
VIVIAN Then suddenly a knight on a white horse with his bright colors flying would ride up.
VIVIAN Rescue me from the tower, and then we'd ride off...
VIVIAN but never, ever in all the times I had that dream did the knight say, "Come on baby, I'll put you up in a great condo."
She finished his tie.
EDWARD Vivian, life's not a fairy tale.
VIVIAN I know.
VIVIAN Hey, don't mind me.
VIVIAN I'm being stupid.
VIVIAN I'll think about it, okay?
VIVIAN It's a real good offer for a whore.
EDWARD I've never treated you like a whore.
VIVIAN You just did.
The doorbell suddenly rings in the living room.
Edward enters the living room.
Vivian slowly enters behind him.
Edward opens the front door.
Mr. Kross slowly enters.
He looks very old and tired; so much so that Edward has to mask his surprise.
KROSS Mr. Harris.
EDWARD How are you, Mr. Kross.
KROSS Not bad for a man who hasn't slept in four nights.
KROSS I'll get used to it.
An angry, reluctant looking David Kross is behind his father.
Stuckey brings up the rear.
Edward and David give one another perfunctory nod.
Stuckey smugly winks at Edward.
Edward closes the door and leads them all down the stairs.
Vivian is very troubled at Kross's appearance.
He gently nods at Vivian.
KROSS Young lady.
VIVIAN Hello.
VIVIAN Hi.
DAVID Hello, Vivian.
STUCKEY Let's not waste time here, shall we?
STUCKEY Mr. Kross, you said this morning, you wished to speak with Mr. Harris.
STUCKEY Mr. Harris is now listening.
Kross has to fight down his humiliation at Stuckey's tone.
He turns to Edward.
KROSS Yes.
KROSS I'm here to tell you that I've reconsidered my position on your acquisition offer.
EDWARD Expected...
EDWARD offer.
KROSS Of course, yes.
KROSS After the expected filing period is over, I'm going to recommend to the board that we accept your bid.
EDWARD You're making the right decision, sir.
Stuckey glances triumphantly at Edward.
He is surprised to see that there doesn't seem to be any victory in Edward's face.
Edward is silent.
Kross interprets his silence as second thoughts.
KROSS I'll see you on one condition.
KROSS I'm not so concerned for me but the people who have worked for me...
Vivian is disturbed watching this tired looking man.
STUCKEY They'll be taken care of.
STUCKEY Won't they, Edward?
Kross ignores Stuckey.
He looks to Edward.
Edward slowly nods.
KROSS I'll sign anything you want then.
STUCKEY Today.
Kross nods tiredly.
His voice is very soft.
KROSS Today.
Vivian abruptly turns and disappears into the bedroom, obviously upset.
The men all watch her go.
Edward hesitates.
He turns to Kross:
EDWARD Excuse me, please?
He heads to the bedroom.
Vivian is sitting on the bed, on the phone.
VIVIAN Hello.
VIVIAN Is Kit DeLuca there?
VIVIAN When she comes in will you have her call Vivian Wells at 560-30000.
VIVIAN Yes.
VIVIAN Okay.
She hangs up as Edward comes in.
VIVIAN What did you do to him?
EDWARD What do you mean?
VIVIAN Last time I saw him he was this strong guy.
VIVIAN Now he's beaten.
VIVIAN And you liked him.
EDWARD Vivian, I want you to listen to me.
EDWARD The man realized that it would be better for his future and his son's future, if he cooperated.
VIVIAN Right.
EDWARD It's not your concern.
EDWARD It's...
EDWARD business, that's all.
VIVIAN Business.
EDWARD Yes.
EDWARD The man made a business decision.
VIVIAN It's all just business to you.
VIVIAN Him.
VIVIAN Me.
VIVIAN Your life.
VIVIAN Everything's business.
EDWARD It's what I do for a living.
EDWARD It's how I make money.
Silence.
EDWARD I'll be back in a few hours.
EDWARD We'll talk about this later.
Edward enters the living room.
The men look at him expectantly.
EDWARD We'll continue this down at the office.
He heads for the door.
Vivian stands at the railing, unhappily looking out at the city beyond.
The phone RINGS.
She turns and hurries inside.
Vivian answers the phone.
VIVIAN Lo?
Mr. Thomas is standing behind the front desk, a rather strained expression on his face.
MR. THOMAS Barnard Thomas here.
MR. THOMAS Miss Vivian, I wonder if you might come down to the front desk.
MR. THOMAS There's someone here to see you.
VIVIAN Me?
MR. THOMAS I'd send them up, but sadly, I don't trust the young lady to find you on her own.
A hand reaches out and wrenches the phone away from Mr. Thomas.
Kit, heavy make-up, skimpy outfit, chewing gum, cigarette and all, keeps her voice just below a bellow.
KIT Viv?
KIT Where are you, babe?
KIT The sphincter-police won't let me through.
Kit finishes slurping on a big, frosty ice cream soda.
She smacks her lips like a happy, little girl.
Vivian isn't having anything.
VIVIAN Yes, I'm glad you're clean but I've been calling and calling.
KIT Was that you?
VIVIAN Who did you think?
KIT Carlos.
KIT I still owe him two hundred bucks...
VIVIAN Kit, I left that money for you days ago.
KIT Yeah.
KIT I just got it.
An OLDER COUPLE walk past the table.
They stare at Kit.
KIT Fifty bucks, grampa.
KIT For seventy-five, the wife can watch.
Horrified, the elderly couple hurry away.
VIVIAN Kit...
KIT Everybody keeps starin' at me.
VIVIAN Yeah...
VIVIAN I know what you mean.
KIT What do you know?
KIT You look good.
KIT All dressed up.
KIT You clean up real nice.
KIT You sure don't fit in down on the Boulevard, lookin' like you do.
KIT Not that you ever did anyway.
VIVIAN You think I fit here where they just about chew your food for you?
KIT Where do you fit?
Vivian is silent, then.
VIVIAN I kissed him, Kit.
VIVIAN On the mouth.
KIT Honey, you're not supposed to do that.
VIVIAN I know.
VIVIAN I stopped pretending and started liking it with him for real.
KIT Oh, my god, you mean it was good?
VIVIAN It was great.
KIT Dummy.
VIVIAN He wants to set me up in a place, give me some money.
KIT I pray for that.
VIVIAN All I'm doing is feeling lousy about it.
VIVIAN I don't know what to do.
VIVIAN What do I do, Kit?
KIT Go for the bucks.
VIVIAN I don't care about bucks.
VIVIAN I might love this guy.
KIT Wow, are you in deep shit.
KIT You know he'll break your heart.
Vivian is silent again.
KIT (cont'd) I blame myself here.
First time I laid eyes on ya', I knew you were too complicated to be a whore.
Vivian nods.
Her face is filled with confusion.
Edward stands at the window looking out.
There is something about his somber demeanor that both reflects the look we've just seen on Vivian and suggests the way we saw him at the top of the story.
Jake enters, a pile of papers under his arm.
He begins laying them out on the conference table.
JAKE Congratulations, sir.
EDWARD What?
JAKE Mr. Kross is just getting off the phone with his stock broker.
JAKE It's finished.
JAKE You've won.
Edward says nothing.
JAKE Who are you going after next, sir?
EDWARD Who indeed...
He turns as Stuckey, James and David Kross, and Vance enter the room.
They surround a conference table.
Kross sits, the papers laid out in front of him.
Stuckey hands Kross a pen.
A SECRETARY lays out finger food.
They wait for her to leave before they speak.
STUCKEY If we can get these letters of intent out of the way now...
STUCKEY Mr.
STUCKEY Harris and I would like to ask you some questions about your company.
DAVID Dad, excuse me, but that's inappropriate.
DAVID You're under no obligation to answer any questions at all.
KROSS Could we at least wait till after the filing period?
Stuckey glances to Edward for help.
Edward is silent; indeed it's as if something is twisting inside of him.
Stuckey plunges ahead.
STUCKEY Mr. Harris is preparing a bid based on our speculation of the corporation's net worth.
STUCKEY The price he ultimately pays for your father's stock will be based on that bid.
STUCKEY The more we know, the higher our bid can be.
KROSS It's in my best interest to cooperate, David.
DAVID If he throws himself on your sword, you promise to take care of him and his family, huh?
David stares at him.
STUCKEY That's unfair!
DAVID You bed it is.
DAVID You're everything he said you were.
DAVID Do what you have to do, Dad.
DAVID Just don't expect me to watch it.
He exits.
A moment.
Kross looks at Edward with a resigned smile.
KROSS He's young.
KROSS He hasn't learned how to lose gracefully yet.
KROSS I'll sign your papers.
KROSS And I'll answer your questions.
KROSS Whatever you want.
He sighs.
He picks up the pen.
He's about to sign.
EDWARD Stop.
EDWARD For just a moment.
EDWARD Mr. Kross, I'd like to ask you a few questions before you sign.
EDWARD You realize that you're a target.
EDWARD If you weren't mine, you'd be someone elses, correct?
KROSS Yes.
EDWARD If you had a...
EDWARD reprieve, what would do?
STUCKEY I don't think there's any sense in --
EDWARD Let him answer.
KROSS I...
KROSS I would take advantage of it.
EDWARD How?
Kross looks uncertain.
He gropes for an answer.
KROSS I...
KROSS I don't know.
KROSS There...
KROSS there wasn't time...
EDWARD I suppose you'd find out soon enough that you have assets you presently don't seem aware of, wouldn't you?
EDWARD The waste processing licenses at that abandoned shipyard of yours, you'd certainly find out about that.
Surprise suddenly flares in Stuckey's eyes.
STUCKEY Oh, my god...
STUCKEY Edward, no!
EDWARD I suppose you'd use them as collateral on new loans, wouldn't you?
STUCKEY Have you lost your mind?
KROSS Quiet.
KROSS Would I get the loans?
EDWARD This time I imagine you would, yes.
EDWARD Hmm...
EDWARD With all this in mind, Mr. Kross, I can't logically make a formal bid on your company, can I?
KROSS You'd be initiating a financial battle you'd ultimately lose, Mr.
KROSS Harris.
EDWARD You're very right.
EDWARD I think the best thing we could all do is go home.
STUCKEY What!?
EDWARD Have a good day, gentlemen.
He exits from the room.
Stuckey follows.
Edward is walking down the hall.
Stuckey comes out of the office and calls after him.
STUCKEY Edward, what happened?
STUCKEY What kind of move was that?
Edward silently goes into the elevators.
The doors close.
STUCKEY Dammit Edward, speak to me.
Stuckey heads back to the conference room.
Edward comes out of the building.
His Chauffeur leaps to open the limo door.
EDWARD No...
EDWARD take the car back to the hotel.
EDWARD I need to walk.
He sets off across Century Park East.
Vivian is in the living room, pacing, edgy, the doorbell rings.
She turns.
It rings again.
She opens it.
Stuckey is standing outside with a small briefcase.
He looks agitated.
He tries to hide it.
STUCKEY Well, well...
STUCKEY Hello again.
STUCKEY I'm looking for Edward.
Vivian just stares at him.
VIVIAN Edward's not back.
VIVIAN I thought he was with you.
Stuckey walks past her and down the steps into the living room.
STUCKEY No, I'll just have to wait then, won't I?
There is a bar set up.
Stuckey sets his briefcase down.
He crosses to the bar.
STUCKEY (cont'd) Mind if I have a drink?
VIVIAN No.
He pours liquor in a glass.
He fires it down.
It seems to calm him a bit.
STUCKEY Do you want to know what he did?
STUCKEY Do you want to know what the crazy son of a bitch did?
STUCKEY He handed the whole thing back to Kross!
STUCKEY On a silver platter.
STUCKEY For no reason!
STUCKEY What was he thinking, I mean, what was going through his goddam head?
STUCKEY Why?
STUCKEY What was all that benevolent crap?
STUCKEY What are we going to become, a philanthropic foundation?
STUCKEY I'll probably be the director of several worthwhile charities.
VIVIAN I think it's great.
Stuckey glares at Vivian.
STUCKEY I bet.
STUCKEY A lousy whore and you're the gum in a hundred million dollar deal.
VIVIAN Aw, come on, Bill.
VIVIAN It's just business.
He looks at her a moment.
STUCKEY But what do I know, maybe you're worth it.
STUCKEY Come on, show me.
STUCKEY Let's see your act.
He grabs her wrist.
VIVIAN Get out!
STUCKEY Don't worry.
STUCKEY I'll pay for it.
STUCKEY What a you charge?
STUCKEY Huh?
STUCKEY Twenty, thirty, fifty bucks, maybe?
STUCKEY Are you a fifty dollar whore?
He tries to kiss her and pulls her down on the couch on top of him.
VIVIAN Are you crazy?
She bites his hand.
Stuckey slaps her.
Vivian starts flailing back.
But Stuckey is too strong.
Vivian staggers back at the force of another slap.
Stuckey slams her up against a wall and starts rubbing up against her.
STUCKEY You got a mean streak in you, don't you.
He tries to kiss her again.
STUCKEY (cont'd) Is that what he likes about you?
Huh?
Answer me!
And suddenly a HAND lands on Stuckey's shoulder.
Stuckey turns his head, startled.
Edward, murder in his eyes, belts Stuckey across the room.
Stuckey falls on the ground.
Edward rushes forward, berserk with rage, to hit Stuckey again.
His fist hits the top of Stuckey's head, hurting Edward's hand more than Stuckey's skull.
Vivian rushes out of room to bathroom.
Again Stuckey tries to rise.
Edward kicks him in the butt, sends him headfirst into the bar.
Glasses and bottles CRASH to the floor.
Stuckey again tries to rise.
And collapses.
Edward rubs his fist.
They're not used to this violence and both stare at each other panting.
STUCKEY You broke my nose.
EDWARD I think I broke my hand.
EDWARD You're fired.
STUCKEY Edward, we've been together ten years.
EDWARD And I don't like what we've become.
EDWARD I'll cover any losses you have on this one.
EDWARD Now get out, you asshole!
STUCKEY All this because of that whore!
EDWARD Yes.
Edward pushes Stuckey out the door and throws his briefcase after him.
STUCKEY Edward, think about what you're
Edward slams the door in his face.
Edward stands there, reflecting on what he's done.
EDWARD Well, I didn't plan that!
Edward holds an icepack to Vivian's cheek.
VIVIAN Why do guys always know how to hit a woman?
VIVIAN Right across the cheek, wham, so it feels like your eye is gonna explode.
VIVIAN What do they do, take you all aside in high school and show you how?
VIVIAN It pisses me off!
EDWARD Not all men hit.
EDWARD And no one is going to hit you anymore.
VIVIAN Right.
VIVIAN You're quite the Sir Galahad today, aren't ya'?
VIVIAN I heard what you did with Kross.
EDWARD It was a business decision.
Vivian looks at him.
EDWARD I got tired of hating my father.
VIVIAN It was good.
EDWARD It felt good.
Edward looks on the bed at her suitcases.
EDWARD You're packing.
VIVIAN I'm leaving.
VIVIAN Don't ya see?
VIVIAN If I stay with you like you want me to, there'll always be some guy, your friends eve, treatin' me like that...
VIVIAN thinkin' they're allowed to.
VIVIAN What are you gonna do, fight'm all?
VIVIAN No.
VIVIAN I'll take my money now, please.
A moment.
Edward reaches for his wallet.
He counts out bills.
He places them in Vivian's suitcase.
He puts his arms around Vivian.
VIVIAN Aw, don't...
VIVIAN no...
EDWARD Stay with me tonight.
EDWARD Not because you're being paid to.
EDWARD Stay with me because you want to.
VIVIAN I do.
VIVIAN I do want to.
VIVIAN That's why I'm leaving.
VIVIAN That's what you given me, see?
VIVIAN I know what I want now.
VIVIAN I want a guy like you for real.
VIVIAN Not because you buy me things and give me money.
VIVIAN The nicest thing you ever done for me is hold my hand.
VIVIAN You gonna give me that?
Edward is silent.
VIVIAN I didn't think so.
EDWARD Vivian...
VIVIAN It's not your fault.
VIVIAN You're right.
VIVIAN Kit's right.
VIVIAN But I want the fairy tale.
Vivian comes out of the elevators.
A BELLMAN sees her and springs forward, reaching for her bags.
BELLMAN Let me take those, miss.
VIVIAN Thanks.
Vivian sees Mr. Thomas behind the front desk.
VIVIAN I'll be out front in a minute.
VIVIAN I got a cab comin'.
The bellman moves away.
Vivian walks to the front desk.
VIVIAN Hi, Barney!
MR. THOMAS Miss Vivian.
VIVIAN Look I just wanted to say goodbye.
MR. THOMAS Mr. Harris doesn't check out until tomorrow.
VIVIAN Yeah, well, I check out today.
MR. THOMAS You're not accompanying him to New York?
VIVIAN Come on, Barney, you and me live in the real world.
VIVIAN You don't know how to treat a girl like anything but a lady, Mr.
VIVIAN Thomas.
MR. THOMAS Certain ladies make that very easy...
MR. THOMAS Vivian.
MR. THOMAS John, call a limousine for our guest, please.
MR. THOMAS Have it take her anywhere she wishes to go.
MR. THOMAS Bill the hotel.
MR. THOMAS See you again sometime soon.
Vivian smiles softly at him.
She turns and walks for the door.
A long silver limo drives down Hollywood Blvd.
The LIMO DRIVER pushes the button that rolls down the screen between back and front seats.
You're sure this is the right street, ma'am?
VIVIAN Yes.
VIVIAN 1312.
VIVIAN It's a big apartment building.
The limo pulls to a stop in front of a rundown apartment building on a dirty Hollywood side street.
The Limo Driver, a large Latino man, steps out of the car and walks around to the passenger door.
As he does, he surveys the surroundings uncomfortably.
Ths is rough neighborhood.
He opens the door.
Vivian steps out.
Maybe I should go with you.
This doesn't look like a good place for a lady to be alone.
Several PEOPLE pass.
All of them stare at the car, at the driver, at Vivian in her lovely clothes.
VIVIAN I'll be okay.
VIVIAN I'm home.
VIVIAN Thank you.
The driver, confused, watches her hurry up the steps to the apartment building.
He drives off.
Vivian walks toward her apartment.
The Landlord is sitting at the front desk in a dirty undershirt.
LANDLORD Hey, we announce guests here.
LANDLORD You a relative of somebody?
Vivian lowers her sunglasses.
LANDLORD (cont'd) Viv -- is that you?
VIVIAN Yeah, it's me.
She keeps walking.
LANDLORD You lookin' good, Viv'.
LANDLORD Nice threads.
LANDLORD I gotta find time to shop.
Edward stands at the penthouse window, looking out.
He is dressed now, ready for travel.
There is something about his expression, his somber demeanor that suggests the way we saw him at the very top of the story.
A BELLMAN enters from the bedroom, rolling a luggage loaded dolly along in front of him.
BELLMAN Is that everything, sir?
EDWARD That's everything.
The Bellman exits, closing the door behind him.
The phone rings.
Edward crosses to it, picks it up.
The Maid comes in, looks around.
MAID The lady, she go?
EDWARD Yes.
EDWARD She go.
Edward with the Bellhop heads to the front door.
He's leaving.
Do you have a car taking you to the airport, sir?
EDWARD Yes.
Vivian, looking fresh scrubbed without make-up, is wearing clean jeans, a nice looking shirt and a suit jacket.
Her bureau's are open.
She is packing.
Kit is watching.
She takes the photo of her and Kit dressed up hot in hooker clothes and packs it.
KIT So whatta' you going to do in San Francisco?
VIVIAN Get a job and probably go back to school.
VIVIAN Figure out what I'm gonna be.
KIT What kind of school?
VIVIAN School, school.
VIVIAN Regular.
VIVIAN I used to get pretty good grades in school, you know.
KIT So did I. I made it with the principal.
KIT Study hard And get a "B."
KIT Lift your dress and an "A" you'll see.
They both laugh but too hard.
VIVIAN Want a pair of boots?
KIT Do I!?
KIT Momma!
Taking them, she sits on the bed and puts them on.
VIVIAN You sure you won't come with me?
KIT And leave all this?
KIT Not in a million.
They laugh together.
KIT (cont'd) What time's your bus?
VIVIAN Couple a hours.
KIT Yeah.
KIT Well...
KIT I gotta split.
KIT Goodbye's make me crazy.
VIVIAN Cool your jets a second.
VIVIAN Here's some money.
KIT No.
KIT You took care of rent, that's enough.
VIVIAN I want to.
VIVIAN For food, got it?
VIVIAN Eat something before the wind blows you away.
KIT I'm gonna pay you back next time I see ya, babe.
KIT Just wait, I'm gonna do something real nice for you some day.
They hug.
KIT (cont'd) Shit, I'm gettin' all weepy now.
Kit begins backing out of the room.
KIT (cont'd) Take care of you, okay?
Take care of you.
Love ya...
Kit turns and hurries out of the apartment.
Kit enters the falafel stand on Hollywood Boulevard.
Kit enters, sits at the counter.
KIT Coffee, Chan.
KIT And maybe a grilled cheese on white, okay?
A very young GIRL is sitting just down the counter from Kit.
Kit nods at her.
KIT Hey, how you doin'.
KIT You new, huh?
GIRL Yeah.
GIRL Got a cigarette?
KIT Sure.
She passes the girl down the pack.
She strikes a match, lights her cigarette for her.
The girl inhales deep, lets it out with a sigh.
She looks towards the window.
GIRL Jeez, did the wacko in the suit.
Kit turns to look.
Outside, across the street, Edward has accosted two PROSTITUTES; one blonde, one a red haired black one.
Kit rises.
KIT Chan?
KIT Keep the sandwich warm, I'll be back.
She heads out the door.
Edward is still talking to the prostitutes.
EDWARD I'm looking for a girl, Vivian, young, dark hair, big eyes...?
They shake their heads.
EDWARD She's mouthy.
EDWARD Sort of difficult...?
Ain't seen her, wouldn't know her.
What's wrong with us, man?
Two for the price a one, what ya say?
EDWARD Thank you.
EDWARD No.
They turn and walk away.
Edward stands there, not knowing what to do next.
He looks discouraged and lost.
KIT Edward Harris, as I live and breathe!
Edward quickly turns to find Kit staring at him.
Kit smiles, triumphantly.
KIT (cont'd) Yeah.
Boy, you're just like she said.
She turns and starts away.
She stops, turns back.
KIT (cont'd) You comin' or not?
I don't got all day, I got a grilled cheese waitin'.
Edward follows Kit.
Vivian sits on her bed, lost in thought.
Her bags are packed, ready to go.
With a sigh she rises.
She picks up the bags, exits the room.
Vivian stands in the dreary living room, looking at it, taking it all in for the last time.
She suddenly looks more than a little bit frightened to be leaving.
She musters resolve.
She goes to the door, opens it and exits, closing it behind her.
Silence.
Vivian suddenly comes back in.
She puts down her bags.
She crosses to the kitchen where she takes coffee can/piggy bank from the shelf.
She puts some more bills into it, places it back where Kit will find it.
She turns and starts again for the door.
She stops.
She hears something.
MUSIC.
An aria from La Boheme.
Faint.
Seemingly coming from nowhere.
She dismisses it -- she's hearing things.
She opens the door.
Stops.
The music is louder and getting louder now -- it's not her imagination.
She hurries over to the window.
Vivian comes out onto the fire escape.
She stares in wonder.
A snow white limo comes up the street.
A necktie has been tied to the antennae like a knight's token.
The MUSIC from La Boheme is BLARING from the car's stereo.
Edward is standing on the car's seat, his head and body up through the open sunroof.
The wind blows at his hair.
He is smiling.
Everywhere on the street people are staring; the BUMS, the PUSHERS, the PASSERBY'S, the TOURISTS.
Vivian doesn't know whether to laugh or cry.
The car comes to a stop in front of the Vivian's building.
Vivian's landlord comes out the front door.
His eyes go wide in disbelief.
Edward disembarks from the limo by coming up through the sunroof.
He leaps nimbly to the ground.
He crosses to the entrance of the alleyway, looking up at Vivian on the fire escape.
VIVIAN You are really lost this time.
Edward wordlessly holds up a hand for her.
With a sudden cry of joy, Vivian comes down the fire escape.
She stops at the bottom stair.
Edward comes forward and sweeps her into his arms.
They kiss.
He carries her to the limo as if she's weightless.
Her feet never touch the ground.
The car door closes behind them.
The limo drives away.
The people of the street watch it go.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
