by
Mard Andrus
And
James L. Brooks
Story by
Mark Andrus
ANGLE ON apartment doorway.
As it opens and an enormously SWEET-FACED, ELDER WOMAN steps out, bungled up against the cold -- turning back to call inside to the unseen love of her long life.
SWEET-FACED WOMAN I'm just going to get some flowers, dear.
SWEET-FACED WOMAN I'll be back in twenty minutes.
SWEET-FACED WOMAN It's tulip season today.
SWEET-FACED WOMAN I'm so happy.
And now she turns and faces the hallway...
her sweetness dissolves in a flash...
replaced by repulsion and that quickly she has reversed herself and re-entered her apartment...
closing the door as we consider her vacated.
POV - MELVIN UDALL in the hallway...
Well past 50...
unliked, unloved, unsettling.
A huge pain in the ass to everyone he's ever met.
Right now all his considerable talent and strength is totally focused on seducing a tiny dog into the elevator door he holds open.
MELVIN Come here, sweetheart...
MELVIN come on.
Sniffing at a particular spot on the hall carpeting.
Melvin lets the elevator door close and advances on the mutt who has ignores him.
MELVIN Wanna go for a ride?
MELVIN Okay, sweetie?
The dog lifts his leg at the precise moment Melvin lunges and picks him up with a decisive heft -- so that dog urine squirts the hall wall for a second or two.
The DOG sensing a kindred spirit starts to GROWL and BARK.
MELVIN You've pissed your last floor, you dog-eared monkey.
The dog takes a snap at Melvin, but the man is much meaner and quicker than the dog -- he holds his snout shut with his hand and reaches for the door of the garbage chute.
MELVIN I'll bet you wish you were some sort of real dog now, huh?
MELVIN Don't worry...
MELVIN this is New York.
MELVIN If you can make it here, you can make it anywhere, you know?
MELVIN You ugly, smelly fuck.
And with that, he stuffs him in the garbage chute and lets go.
We hear a FADING SERIES of PLEADING "ANOOOOS" from the DOG fade to nothingness...
as another apartment door opens emitting the loud sounds of a PARTY and SIMON NYE, early 30s.
Simon has been born and raised with Gothic horror and it's strange that what that stew of trauma has produced is a gifted, decent man.
Frantic...
he bolts into the hall...
Melvin is just about to enter his apartment.
SIMON Verdell!?!!
SIMON Here, good doggie...
He notices Melvin at the far end of the hall.
SIMON Mr. Udall...
SIMON excuse me.
SIMON Hey there!
SIMON Have you seen Verdell?
MELVIN What's he look like?
Melvin starts to walk back to his apartment door which is directly opposite Simon's.
SIMON My dog...
SIMON you know...
SIMON I mean my little dog with the adorable face...
SIMON Don't you know what my dog looks like?
MELVIN I got it.
MELVIN You're talking about your dog.
MELVIN I thought that was the name of the colored man I've been seeing in the hall.
Simon looks O.S. -- and sees his black friend.
SIMON Which color was that?
MELVIN Like thick molasses, with one of those wide noses perfect for smelling trouble and prison food...
Simon has had it.
SIMON Frank Sachs -- Melvin Udall.
MELVIN How're you doing?
SIMON Franks shows my work, Mr. Udall.
SIMON I think you know that.
FRANK Simon, you've got to get dressed.
MELVIN What I know is that as long as you keep your work zipped up around me, I don't give a fuck what or where you shove your show.
MELVIN Are we being neighbors for now?
SIMON Do you still think I was exaggerating?
FRANK can only smile.
FRANK Definitely a package you don't want to open or touch.
MELVIN Hope you find him.
MELVIN I love that dog.
Simon, terminally non-confrontational, still finds himself compelled to turn back toward Melvin.
SIMON You don't love anything, Mr.
SIMON Udall.
Simon closes his door leaving Melvin alone in the hallway.
MELVIN I love throwing your dog down the garbage chute.
Melvin locks and unlocks and locks his door, counting to five with each lock.
He turns the lights quickly on and off and on five times and makes a straight-line towards his bathroom where he turns on the hot water and opens the medicine chest.
Scores of neatly stacked Neutrogena soaps.
He unwraps one -- begins to wash -- discards it -- goes through the process two more times.
A group of PARTY GOERS enters -- followed by a HANDYMAN holding Verdell who looks and finds:
SIMON who looks up -- lights up -- and tears up as he moves quickly toward the group and his dog.
SIMON Thank the good Lord...
SIMON wow...
SIMON my honey...
SIMON where have you been?
PARTY GOER He always liked me.
As Simon goes past him to take the dog from the Handyman...
JACKIE, Frank's junior partner, barking a laugh at the Party Goer -- VERDELL BARKING some love.
As the others greet Simon, Jackie directs the group inside.
Jackie lingers, looking on affectionately as Simon picks some awful, sticky gunk from the dog's body...
he puts Verdell down to reach for his wallet -- the tiny DOG YAPS in protest.
SIMON Just for a second, okay?
The DOG YAPS "no."
Simon, delighted, picks him up again.
SIMON Look at him...
SIMON where was little baby?
HANDYMAN In the basement garbage bin eating diaper shit.
Simon reacts -- then notices the Handyman, tongue in cheek, trying to suppress his amusement.
SIMON Go ahead, John, you earned your fun.
SIMON How did he get down in the basement?
SIMON I mean even if he got on the elevator how...
HANDYMAN Maybe some nice neighbor shoved him down the garbage chute.
SIMON My God!
SIMON No!
He stares out...
Frank frustrated following.
Quiet -- safe -- just Melvin's voice reading aloud as he writes.
MELVIN 'Somewhat in the dark, she had confessed and he had forgiven.
MELVIN This is what you live for, he said.
MELVIN Two heads on a pillow where there is only the safety of being with each other.
MELVIN How, she wondered, could she find such hope in the most shameful part of her.'
He barely reacts as we hear a LOUD KNOCKING at he reads.
SIMON Mr. Udall.
But Melvin's into it.
His fingers flying as he reads.
MELVIN 'At last she was able to define love.
MELVIN Love was...
More KNOCKING.
SIMON Mr. Udall, I'd like to talk to you please.
MELVIN 'Love was...
He almost has the rest of the sentence -- the meaning of love -- but the knocking throws him.
MELVIN ...
MELVIN Son-of-a-bitch-pansy-assed- stool-pusher.
He burst from his chair.
As Simon hears MELVIN through the door and takes a step back.
Melvin throws open the door.
He looks demonic.
MELVIN Yeeeess!!!
SIMON Maybe this can wait.
Frank signals encouragement as Melvin opens the door.
SIMON I found Verdell, Mr. Udall.
MELVIN Well, that's a load off.
Melvin walks back into the apartment and is about to close the door when Simon has another burst of bravery.
SIMON Did you...
SIMON do something to him?
MELVIN Do you realize that I work at him?
SIMON No, I didn't.
MELVIN Do you like to be interrupt when you are danging around in your little garden?
SIMON No...
SIMON actually, I even shut the phone off and put a little piece of cardboard in the ringer so no one can just buzz me from d...
MELVIN Well, I work all the time.
MELVIN So never, never again interrupt me.
MELVIN Okay?
MELVIN I mean, never.
MELVIN Not 30 years from now...
MELVIN not if there's fire.
MELVIN Not even if you hear a thud from inside my home and a week later there's a smell from in there that can only come from a decaying body and you have to hold a hanky against your face because the stench is so thick you think you're going to faint even then don't come knocking or, if it's election night and you're excited and want to celebrate because some fudge-packer you dated has been elected the first queer President of the United States...
MELVIN and he's going to put you up in Camp David and you just want to share the moment with someone...
MELVIN don't knock ...
MELVIN not on this door.
MELVIN Not for anything.
MELVIN Got me.
MELVIN Sweetheart?
SIMON Yes.
SIMON It's not a subtle point you're making.
MELVIN Okay, then.
Melvin enters his apartment and slams the door shut.
SIMON So the theory of confrontations is that now he'll think twice before messing with me?
Frank smiles affectionately.
Simon turns serious.
SIMON He's genuinely upsetting, isn't he?
FRANK Won't worry about it.
FRANK You go ahead.
Frank waits till Simon EXITS SCENE and then knocks loudly on Melvin's door.
There is a sharp change in his demeanor.
MELVIN Oh, I'm pissed!!
MELVIN Now I am really pissed!!!
Frank waits patiently as Melvin jerks his door back open.
Frank immediately grabs Melvin by his shirt and jerks him forward...
Melvin is scared.
Operating on survival mode.
MELVIN No touch.
MELVIN No touch.
MELVIN No touch.
FRANK You may think you can intimidate the whole world with your attitude, but I grew up in Hell.
FRANK My grandmother had more attitude.
FRANK You don't intimidate me.
MELVIN Police!
MELVIN Police!
MELVIN Fucking crooked police...
MELVIN doughnut-munching morons help me!
MELVIN Assault and battery and you're black.
FRANK Shhhh now.
FRANK I like Simon.
FRANK I like him enough to batter you unrecognizable if you verbally abuse him or so much as touch his dog again.
FRANK Meanwhile, I'll try and think how you can make this up to him.
FRANK I hate doing this.
FRANK I'm an art dealer.
FRANK Have a nice day.
FRANK Party!
He tosses Melvin back and walks out.
Melvin straightens his shirt as he steps out into the hall.
Frank smiles as he re-enters the other apartment.
Melvin appears impressed.
A crowded and dirty street and here comes Melvin.
His walk is brisk -- an animal wanting to pass through the danger without giving off the scent of its mounting fear.
At times he places his palms together and extends his arms cutting a path through people.
We will be very pointed in the fact that he avoids stepping on cracks.
His eyes focused on the terrain.
CAROL CONNELLY talks with another MOTHER -- a customer.
You would not guess it, but her working hours tend to be the most carefree time of the day.
She is telling a story about her son for the umpteenth time.
CAROL Look at you, you're all better.
MOTHER It's that new medication.
CAROL You know all my son's stuff, right?
The Mother nods too sympathetically that she does, but Carol interrupts her.
CAROL No, no, no, I got a date tonight.
CAROL I'm walking out the door this morning and he says to me, 'Mom, I promise not to get one of my fevers or coughs during your date.'
MOTHER Isn't that sweet.
CAROL Little blonde angle.
CAROL Eat everything.
Melvin enters and moves past several empty tables to a table towards the back and is obviously surprised to find a MAN and WOMAN sitting at the table.
WOMAN It just came out of me.
WOMAN I said you love me the way a remote control loves a TV.
WOMAN As long as I switch every time...
HER MALE COMPANION Wonderful.
MELVIN People who talk in metaphors can shampoo my crotch.
MELVIN Eat up.
They turn away -- Melvin walks a few paces to the waitress station where two waitresses, LISA and CAROL, are talking.
LISA Pay me back next week.
CAROL I owe you.
CAROL I told you today...
CAROL them's the rules.
CAROL Oh, excuse me, Melvin.
She puts two hands lightly on his waist to move him out of the way.
He gulps at the contact (since no one else ever touches him) but covers his self-consciousness.
MELVIN I'm starving.
CAROL Will you please take it?
Melvin intentionally moves a step in her path, with stealth, so that she must touch him again to get him out of the way...
LISA This way you take a cab home so you have time to get ready for the date.
CAROL "Ready" is not my problem.
She barks a mirthless though hearty laugh.
If we could read Melvin which we can't, we'd see him unsettled by the date talk.
To Carol he is as harmless as furniture.
CAROL Go sit down.
CAROL You know you're not allowed back here...
CAROL Spencer's more excited about it than I am...
CAROL He says, "Mom, I promise not to get a fever or couch during your date."
The other WAITRESSES and the SHORT ORDER COOK all go "awww."
CAROL I know.
CAROL He's just the best.
MELVIN I've got Jews at my table.
CAROL It's not your table.
CAROL It's the place's table.
CAROL Behave.
CAROL This once, you can sit at someone else's station.
The two waitresses signal their protests.
CAROL Or you can just wait your turn...
Melvin walks back into the restaurant proper...
he hangs near their table...
his discomfort builds in this limbo...
then:
MELVIN How much more you got to eat?
MELVIN Your appetite isn't as big as your noses, is it?
WOMAN What?!!
MAN Let's go --
The Woman starts to protest.
MAN Let's leave.
MAN We're going.
Melvin sits down at the table -- and takes from his pocket a plastic eating utensil set wrapped and sealed.
As he opens his utensils.
CAROL Bryan says he doesn't care how long you've been coming you ever act like this again you're barred for life.
CAROL I'm gonna miss the excitement, but I'll handle it.
There is in Carol's attitude toward Melvin some ingredient of self-satisfaction -- that she is the only one in the place who can handle him.
She starts to clear the table.
MELVIN The table's fine if it had some cholesterol on it.
MELVIN Two sausages, six bacon strips, fries, three eggs over easy and coffee.
CAROL You're gonna die soon with that diet, you know that?
MELVIN We're all gonna die soon.
MELVIN I will.
MELVIN You will.
MELVIN It sure sounds like your son will.
Stunned.
Some crazy street-freak has slipped under her perfect guard and momentarily devastated her.
Melvin senses that he's gone way too far.
He wipes his knife.
CAROL If you ever mention my son again, you will never be able to eat here again.
CAROL Do you understand?
CAROL Give me some sign you understand or leave now.
CAROL Do you understand me...
CAROL you crazy freak?
CAROL Do you?!?
A beat and then Melvin nods, hardly breathing -- backing down.
CAROL Okay.
CAROL I'll get your order.
She walks away.
Melvin watches her, biting his lower lip.
He takes some napkins and cleans the table himself.
She is underneath a YOUNGER, cuter MAN on the living room sofa.
He is expertly into foreplay.
She begins to make noises as she responds...
each time startling herself with her own noise and trying to reign it in.
She's two women here -- one speeding the pleasure highway -- the other -- functional mom so blown away by the emergence of this sexy self that she laughs.
The Young Man stops and looks at her.
YOUNG MAN What?
CAROL I...
CAROL I...
CAROL I don't know...
CAROL You got me.
His eyes try to burn into hers...
She is getting excited but doesn't know how to play it...
He pushes one of the fingers of the hand caressing her face toward her mouth...
She closes her teeth, his fingers attempt opening her mouth.
She stops him.
CAROL Let me just do whatever I do by myself...
CAROL I'll catch up to you someplace I promise.
CAROL Oh, no...
CAROL don't look like that.
CAROL No.
CAROL I'm sorry if I'm a goof.
And so with earnestness and caring, she has transformed the sex into something more intimate -- and, talk about egg in your beer, hotter.
Things are getting wild when we hear from the distance a child, SPENCER, CALLING and
CAROL Kissing...
CAROL kissing boys.
CAROL Oh my.
Carol pulls her head away -- as Spencer's call continues.
SPENCER Grandma, grandma...
YOUNG MAN Maybe you better check.
CAROL Like what did you think I was going to do?
Pulling herself together she goes off down the hallway...
she ducks her head into the first bedroom where her mother, BEVERLY, is listening to music on headphones...
she takes them off when she sees Carol, then hears the cough.
BEVERLY I'm sorry.
BEVERLY I was hearing just everything you were doing so I put these on to give you privacy.
Carol now goes into her son's room.
The room is a monument to horrible, sleepless nights...
two drugstore de-humidifying filters, a nebulizer (breathing contraption) a waste basket...
a night stand filled with medicine, a blood pressure kit...
along with some stacks of seven-year-old toys and a small TV wedged into the tiny space.
SPENCER I'm sorry.
CAROL Don't be silly.
CAROL How bad?
SPENCER Not bad.
Carol feels his head...
that's okay.
Then he coughs -- trying to suppress it...
then a bigger cough...
they each know what that signals...
She brings up a waste basket as he throws up...
she comforts him.
He apologizes.
She loves him.
As she re-enters.
He is taking a cigarette from a pack.
CAROL You can't smoke...
CAROL He can't take smoke.
He palms the cigarette -- resumes making out -- his hand squeezes her breast -- then he stops and looks at his hand.
She looks down and sees a bit of throw-up he picked up while feeling her and then notices him looking at her with extreme distaste...
She barks a laugh to cover her embarrassment but speaks the truth.
CAROL Oh, God...
CAROL I don't even notice anymore.
She crosses to the kitchen for a dishtowel.
Tries to make light.
CAROL That'll teach you.
YOUNG MAN Don't apologize.
CAROL That wasn't an apology.
She notices his demeanor -- how he avoids looking at her -- how uncomfortable he is.
CAROL Hey...
CAROL this is just a little throw- up -- it's nothing to be so embarrassed about.
CAROL Really.
CAROL Thanks for the dinner.
CAROL Let me write down which trains you take to get back.
YOUNG MAN No way.
She brightens.
YOUNG MAN I'll take a cab.
She deflates as he moves past her.
YOUNG MAN Too much reality for a Friday night.
A cold night in hell.
Three young men bullshit near the approach to the tunnel.
Their names are VINCENT, EVAN and DOUG, who is the oldest at 28.
Vincent is dopey and the most likeable of the gritty little trio.
EVAN Why is every customer surprised I read books?
DOUG You read books?
EVAN Oh, wow!
EVAN I know this guy!
EVAN Look!
EVAN He even bought me dinner.
They all focus on a black BMW as it slows and stops in front of them.
CARL checks them out carefully through the front window.
He is talking on the speaker phone.
CARL Look, I just can't.
CARL I promised Simon I'd find him a model.
FRIEND (V.O.) Carl, take me off the speaker.
FRIEND (V.O.) Did I tell you that these are house seats?
FRIEND (V.O.) C'mon, you could use a break.
FRIEND (V.O.) Hello...
FRIEND (V.O.) Carl, are you there...
FRIEND (V.O.) hello?
Seeing the hustlers:
...
I just found a model.
DOUG Hey, how it's goin'...
EVAN Hey, hi...
EVAN remember?
CARL I only need one.
EVAN You picked me up, maybe a few weeks, I don't know, some time ago.
EVAN You were very flattering about our...
EVAN encounter.
CARL Maybe just you and me...
CARL but this is for a painting.
CARL I need a pretty face.
Carl beckons to Vincent who joins him, trying to conceal his pride at winning this lowest end of beauty contest.
There is a KNOCK at the door -- Simon crosses to answer.
He is more relaxed than we've seen him -- a man at peace humming to his favorite music, talking to his dog who scratches at the door.
Simon opens the door to Vincent.
SIMON Sorry, I was out in the studio doing some work and I forgot about our appointment.
He leads the way back toward the studio -- chatting away -- unaware that Vincent is disrobing as he follows him and eyeing the expensive apartment.
SIMON I usually make such a big deal out of picking models but Carl's so thorough.
SIMON I'll bet he drove you nuts checking your references.
And he turns and sees the naked model.
SIMON This isn't a nude.
Vincent moves back to retrieve his clothes.
VINCENT Just kidding around.
VINCENT So much for love.
Vincent is striking blatantly sexual poses to the increasingly uneasy Simon.
SIMON Exactly what is your previous experience?
VINCENT How about that pose?
VINCENT This is not fun...
VINCENT Give me some direction.
Vincent has instinctively put Simon on the defensive.
He tries not to show it.
SIMON Nothing.
SIMON I just watch till something strikes me.
SIMON Do anything you think of -- try different thing.
SIMON Until I say, "hold that pose."
SIMON Then just try and comfortably hold it.
VINCENT The fact that you haven't said, "hold it" means I haven't done it right...
VINCENT is that correct?
VINCENT I haven't done it right?
SIMON No...
SIMON Okay.
SIMON What I do is watch and wait for, um...
SIMON You ever watch someone who doesn't know you're watching...
SIMON an old woman on a bus, kids going to school and you see this flash come over them and you know immediately that it has nothing to do with anything external -- that it's in respond to a private thought they just had?
SIMON They are just sort of realer and more alive.
SIMON And when you notice it so are you.
SIMON If you look at someone long enough, you discover their humanity.
Vincent's slack-jawed expression changes.
He feels an intellectual tingle to be having this conversation.
VINCENT I know exactly what you mean.
There's a joy in him at this moment -- a bit of purity.
SIMON Hold it.
Vincent does so -- hums a bit of "Satisfaction" to celebrate.
Carol and LESLIE, another waitress, are waiting for their order at the cappuccino bar.
Leslie is telling the story of the traumatic audition which may have turned her life.
Carol is rapt.
As they pass Melvin she does not break stride, nor give him notice.
Though she is aware of him -- resentfully so -- hard not to be since he is giving a moment to moment commentary on her every action.
MELVIN Clippity clop -- clippity clop -- she has to pretend she doesn't hear me.
MELVIN Listening to the story from the upset friend...
MELVIN now she drops off the cappuccino and smiles at the putzette who doesn't even say, "Thank you."
MELVIN No, the putzette wanted the whipped cream so back she goes and now she has to pass him again and it's getting tougher to make believe.
CAROL Okay.
Melvin stops -- she passes behind him to deliver an uncharacteristic rabbit punch.
CAROL What's with the plastic picnic ware?
CAROL Why not try ours...
CAROL afraid it isn't clean?
MELVIN I see the help -- judgement call.
CAROL Just give yourself a little pep talk.
CAROL "Must try other people's clean silverware as part of the fun of dining out."
MELVIN What's wrong with your son, anyway?
CAROL What do you care?
Melvin just looks at her.
CAROL He's gotta fight to breathe.
CAROL His asthma can just shoot off the charts -- he's allergic to dust and this is New York and his immune system bails on him when there's trouble so an ear infection...
CAROL Is this bothering you?
MELVIN No.
CAROL An ear infection can send us to the emergency room -- maybe five, six times a month where I get whatever nine-year-old they just made a doctor.
CAROL Nice chatting with you.
MELVIN His name?
CAROL Spencer.
MELVIN Okay.
CAROL Spence.
She exits.
The greenhouse studio is a busy sanctuary, as Simon puts the finishing touches on his painting of Vincent.
A beat and then a strange figure crosses between the CAMERA and the scene -- gone before we can examine him further.
SIMON You can put on anything you want now.
SIMON I might be sort of done here...
Vincent quickly and expertly picks a CD to meet his immediate needs and puts it on -- dying a little at every second of silence during the transition...
then LOUD MUSIC PLAYS...
Vincent even GOOSING the VOLUME.
Simon does a take -- he gestures Vincent to take it down -- which Vincent does.
ANGLE - APARTMENT where it is not clear that a robbery is in progress -- Vincent's two friends from the street sweeping all objects into large sacks -- one of them, Doug, pauses to look past the terrace to the studio.
DOUG Lucky Vinnie -- he's a painting.
MUSIC PLAYS -- Simon cleaning up his stuff.
VINCENT So you're practically finished, huh?
SIMON Yes...
SIMON well, there's one more stage -- trying to figure out if it's any good.
Simon sneaks a look at the canvas from another perspective...
he focuses -- then the smallest shy nod of self-approval -- he's finished.
Vincent is desperate to distract.
CLOSE ON dog as Verdell awakens, stretches and pricks his ears.
He moves quickly to the closed door and starts to frantically scratch, attracting Simon's attention.
As Simon keeps walking...
Vincent shoots over to the canvas.
VINCENT Wait -- I want to see the painting.
SIMON Just a second -- he has to go.
VINCENT Please!!
VINCENT NO!!!
Simon opens the door and Verdell shoots out like a bullet.
Vincent pauses before the painting and is thrown to see his humanity captured -- to be "immortalized."
Doug and Evan are nearly to the front door as VERDELL stops them with a vicious GROWL and BARK.
Simon is distracted -- looking down at his pet so that he continues to walk toward Doug and Evan, not noticing them -- Vincent, terribly afraid, appears behind Simon.
SIMON What's the matter, sweetheart?
He instantly stops.
Shocked.
Frozen.
His eyes on the stranger, Doug, looking at him.
Now Vincent comes in.
Doug greets him.
DOUG Yo.
Simon turns to Vincent.
SIMON Why are you doing this?
VINCENT No.
VINCENT No.
VINCENT No.
VINCENT Hey, that painting in there...
VINCENT I just want to tell you...
Now Evan appears holding a brass hat rack.
EVAN What are you doing?
EVAN Cruising him?
And he uses the hat rack first as a spear, then as a club, as the brief savage attack begins.
ON VERDELL as he starts to go toward Simon and then scurries back in fear.
The three attackers leave.
Now silence.
A single BARK from VERDELL.
A mass of OFFICIAL PEOPLE clutter the hall as a gurney is whisked down to the elevator.
It's impossible to tell if Simon is awake or dead.
Melvin is standing against the wall near his door a cop, RAY, interviewing him.
RAY Okay.
RAY So you call 911 and don't leave your name -- even a dumb geezer should know that emergency automatically pulls up your name.
RAY How come you make a mistake like that?
MELVIN How come you're pretending to do cop work -- 'cause I don't think you could find your ass if you were spotted the hole.
RAY What?
MELVIN Just move on.
MELVIN No one here killed him.
RAY Oh, is he dead?
MELVIN Ask him.
RAY We will if we can and if we can't, we'll come back and ask you again and again.
Frank standing upset, anxious, holding a dog bowl, a leash and VERDELL, who is more upset making pathetic little CRYING SOUNDS.
As we FOCUS BRIEFLY ON Verdell...
Frank is talking to the Sweet-Faced Woman.
SWEET-FACED WOMAN I've been praying for him since I heard.
FRANK So I've got to get to the hospital.
FRANK If you could take the dog just for tonight.
SWEET-FACED WOMAN Oh, Lord -- I've got all these antique knick-knacks...
SWEET-FACED WOMAN Or else I'd be glad...
FRANK Maybe if you kept locked in the bathroom.
FRANK No?
FRANK Okay.
FRANK Thanks.
FRANK Old bitch...
FRANK Damn dog.
A short laugh makes us realize that Melvin has witnessed and enjoyed Frank's hostile mutterings...
VERDELL starts WHIMPERING as a pissed Frank approaches his mugger:
FRANK You're taking him...
FRANK yes...
FRANK you're taking him -- this will clear the books.
FRANK One night.
FRANK You want to say "no" to me?
FRANK Try...
FRANK because I've never felt as nuts as I do right this second.
FRANK I almost want you to try saying "no."
MELVIN I'm not saying nothing to you.
FRANK Thanks for looking after him.
Frank pushes open the door to Melvin's apartment and places Verdell inside.
MUSIC IN: as Frank pulls the door partially closed to block Verdell's escape.
The music represents Verdell's state of mind -- trapped in the apartment of the man who tried to kill him.
We STAY with the dog during the O.S. dialogue: As his head turns in panic we see his various POVs as the dialogue continues O.S.
MELVIN Hey, where are you going?
MELVIN You can't do this.
MELVIN I can't take a dog.
MELVIN Nobody's ever been in here before.
FRANK You don't want to mess with me today.
FRANK I'll figure something else out tomorrow.
Melvin enters -- the dog cowers in the shadows.
Now Melvin sees him.
MELVIN You're dead!!
VERDELL STOPS -- gives Melvin wide berth -- slinking along the far wall.
Melvin finds Verdell's fear of him a bit calming.
MELVIN I don't have dog food.
MELVIN And I won't want dog food here.
MELVIN You'll eat what we have.
MELVIN You'll eat what we eat.
Melvin exits.
Verdell is in a major funk.
Melvin breaks two eggs over a large pile of prime chopped meat, sticks raw pieces of bacon into it and exits the room.
MELVIN Don't you touch anything.
Verdell cringing as his new master approaches -- MUSIC CONTINUES ominously.
Melvin sets the bowl down and exits...
Verdell breathes excitedly though looking alternately in all directions...
his recent past making him suspect this feast is a trick.
He sniffs cautiously -- then dives in -- GOTHIC MUSIC CHANGING on a dime TO SCORE his RAPTURE...
from O.S. we hear the sound of RUNNING WATER as steam escapes the bathroom -- then MUSIC OUT -- as Melvin returns...
ignoring Verdell he sits at the piano and his one key repeatedly.
It's odd.
Verdell shifts his body so he is eating from the bowl with his tail to Melvin.
Then Melvin begins to play and sing Monty Python's "Always Look On The Bright Side Of Life," with its cheerful whistle refrain.
Verdell looks over with surprise and pleasure.
But just as mood lifts and warmth threatens, Melvin stops abruptly, turns out the lights and exits.
Frank on the phone.
FRANK Put the solid red dots on three of them and the hold blue dots on two others...
FRANK Well, we're not going to sell anything if they know we're two weeks into a show and have no sales.
FRANK No, you can't reduce a price at this stage...
FRANK We're in free fall here.
FRANK Any calls?
JACKIE We can see him.
FRANK I'll meet you in there.
As Jackie enters.
JACKIE How you doing, great one?
SIMON I haven't looked at myself yet.
SIMON I figured I could tell from your reaction.
He turns toward her.
Much of his body -- taped -- his painting hand wrapped.
Simon's face is something of a horror.
Swollen, one savage discolored cut.
We are into yuccchhh...
The sight is a jolt.
Jackie breaks into tears...
sobs, actually.
SIMON That bad, huh?
They share a helpless half-laugh -- then Frank appears in the doorway.
FRANK Hey, hey...
FRANK Haaa...
FRANK bad but temporary.
FRANK The nurses say it's much better than you looked three weeks ago...
FRANK the hand will come back...
FRANK they're sure...
SIMON Jackie, will you hand me the mirror?
JACKIE No.
She starts to hand him a large mirror from her purse -- then thinks better of it.
JACKIE Wait, I have a smaller one.
But he holds out his hand and she gives him the mirror -- he starts to look -- then thinks better of it.
SIMON So, what's new anyway?
SIMON How's Verdell?
FRANK Your neighbor -- Udall -- is taking care of him.
SIMON How could you do that?
SIMON He'll hurt him.
FRANK No, I promise...
FRANK not a chance.
FRANK I own this guy.
FRANK There was no one else.
FRANK I'm on the move too much.
FRANK Trust me.
SIMON You are very certain my dog is okay...
SIMON because you have no idea...
FRANK Yes.
FRANK Your dog is fine, Simon.
Simon holds the mirror poised for a moment of discovery, then he takes a breath -- like someone about to dive underwater.
First a small, mumbled pep talk to himself.
SIMON Okay, waiting gives the devil time.
SIMON Now!
He quickly brings his hand up and looks at the mirror...
he is startled -- the bottom drops out -- leaving him awed by his misfortune.
SIMON Oh my...
SIMON Where'd I go?
SIMON Ummmm?
AN ESTABLISHING SHOT FEATURING Verdell tied up in front.
Melvin finishing a plate of eggs, bacon and sausage with his plastic knife and fork.
Carol looks totally beat as she sets down a cup of coffee.
Melvin is craning periodically to keep an eye of his dog.
CAROL So what are you doing with a dog?
MELVIN Suckered in.
MELVIN Set up.
MELVIN Pushed around.
CAROL You're not worried that someone might take him?
MELVIN Well, not until now -- for Christ's sake.
CAROL Sorry.
MELVIN It's okay -- I'll sit here.
He changes tables for the first time ever so that he can keep an eye on Verdell.
Carol is amazed.
CAROL You know he's a little dog.
CAROL Next time, if Bryan's not here, you can bring him in.
MELVIN How old are you?
CAROL Oh, please...
MELVIN If I had to guess by your eyes, I'd say you were fifty.
Carol looks at him.
CAROL And if I had to guess by your eyes.
CAROL I'd say you were kind.
CAROL So, so much for eyes.
CAROL But as long as you bring up age...
CAROL how old are you?
MELVIN Otherwise, you're not ugly.
CAROL Okay, pal...
CAROL I accept the compliment, but go easy -- my knees start a-knocking when you turn on the charm full blast.
MELVIN What's with the dark?
He indicates the bags under her eyes by tapping his own.
CAROL Dawn patrol -- major dawn patrol.
CAROL My son had a full blown attack.
CAROL And this time, for extra fun, they gave us the wrong antibiotics, so I get him home...
She reaches for the plate of uneaten bacon -- he goes nuts.
MELVIN No...
MELVIN no...
MELVIN leave it...
MELVIN the bacon's for the dog.
She is jolted by the insensitivity of his interruption, but he doesn't notice, turning, almost chatty.
MELVIN Last week I was playing the piano for him and he likes it, and so I decide I'm going to make a little joke...
CAROL You all set here?
Melvin nods -- a bit frustrated about not being able to finish his dog story.
He pockets the remaining bacon.
As Melvin walks Verdell back home, we notice, perhaps a beat before Melvin, a remarkably event.
Verdell is avoiding the cracks in the sidewalk.
MELVIN It's a beautiful day for our walk.
Melvin slows -- observes the dog mirroring his behavior.
ON VERDELL again carefully placing his paws to avoid a crack in the sidewalk.
Melvin laughs out loud -- puts on plastic gloves hurriedly so he can lift the dog to eye level.
MELVIN Don't be like me, don't you be like me.
MELVIN You stay just the way you are because you are a perfect man.
MELVIN I'm gonna take you home and get you something to eat...
MELVIN what you love.
FEMALE PASSERSBY Ohhh.
FEMALE PASSERSBY I'd like to be treated like that.
MELVIN Let's go home and do some writing.
Melvin whaling away at his computer, reading to himself with great satisfaction as he goes.
Verdell sits at his chair, fascinated by the speed of his master's fingers on the keyboard.
He reads his writing aloud to the dog.
MELVIN "He turned off the gas jets and carried her outside.
MELVIN He kissed her brow and when her eyes opened and found him, he said, 'there are easier ways to break a date.' She laughed.
MELVIN The only sensible ambition he had ever known was now realized.
MELVIN He had made the girl happy.
MELVIN And what a girl.
MELVIN 'You've saved my life,' she said, 'you'd better make it up to me.'"
Exhilarated by his own words, he shuts down the machine...
MELVIN Done!
MELVIN Yes, I hate the doggy...
MELVIN yes, I hate the doggy.
He exits.
MELVIN (V.O.) Sixty-two books...
MELVIN (V.O.) done!
As the dog goes shooting off to the kitchen we leave our couple's play time for...
As the rookie invalid awakens in precisely the same foul mood he'd had on falling asleep.
In the living room, the maid, NORA, is talking with Jackie -- we catch only a few words as they review Simon's mounting pile of bills and talk of how long Nora can stay on.
Frank knocking on Melvin's door.
He opens it.
FRANK How's Verdell doing?
MELVIN He's a pain in the ass.
As he looks over at the dog, Verdell trots over and, without realizing it, Melvin smiles at him to Frank's surprise.
FRANK Simon's home.
FRANK I was sort of hoping you could keep the dog until he's had a chance to think and adjust...
MELVIN It's been five weeks...
MELVIN another few won't kill me.
FRANK No.
FRANK He wants him back.
FRANK He'll be by tomorrow.
MELVIN Okay by me.
Frank exits.
Melvin sits -- Verdell looks up at him.
Melvin walks to the door.
He turns the lock...
then checks that they are locked...
checks again to make sure he turned them in the correct direction...
turns from the door...
then back to check once more.
And again...
and again...
anguished, until now he breaks briefly, the dog looking on.
Melvin opens the door -- looks at the scarred Simon in a wheelchair and shudders...
MELVIN That's some face they left hanging on you.
MELVIN You look like...
SIMON Could you take it just a little easy, Mr. Udall?
A beat of silence as Melvin thinks whether to comply.
SIMON Thank you.
SIMON Verdell...
SIMON sweetheart?
SIMON By the way, thanks for saving me.
MELVIN I called.
MELVIN I never touched you.
MELVIN I didn't leave my name or nothing.
SIMON Verdell?
Totally weirded out...
hiding behind Melvin...
now Melvin shifts and Simon and Verdell see each other...
Simon smiles at the dog...
he is emotionally caught up in the reunion.
SIMON Hi, sweetheart.
Verdell isn't eager.
The first gnawing pains of rejection.
Simon pats his leg -- trying unsuccessfully to get Verdell to approach him.
Instead the dog goes to the door and scratches at it.
Jackie starts to pick the dog up.
SIMON No.
SIMON Please, don't force him.
JACKIE You little stinker.
JACKIE He's given you everything.
Verdell's towel on the floor -- near his bowl.
Melvin's lips compress...
he sits on the piano bench and hits a few keys...
looks at Verdell's empty spot again...
there are those who "get the joke" -- Melvin is clearly one -- he laughs suddenly and helplessly even as he feels the panic rise in him...
...
all his painstaking success in keeping the lid on and now it threatens to blow for a reason he articulates.
MELVIN Over the dog...
MELVIN an ugly dog.
It's hilarious.
But now the humor detours.
An actual sob is choked back...
he gets up -- following a definite pattern across the room.
He is conducting a small but highest-stakes fight for survival.
Momentarily a scared, beaten middle-aged man -- he races out the door.
Melvin charging as fast as crack checks allow and then turning into a building with a copper sign reading "Grammercy Park Psychiatric Group."
MELVIN Worst sidewalk in New York and look where they put in.
Melvin bursts in on the psychiatrist and emits one word.
MELVIN Help!
DOCTOR If you want to see me you will not do this.
DOCTOR You will make an appointment...
MELVIN Explain to me how you can diagnose someone as "obsessive compulsive disorder" and then act like I have any choice in barging in.
DOCTOR There's not going to be a debate.
DOCTOR You must leave.
The Doctor moves into the hallway, forcing Melvin to follow.
MELVIN You said you could help me -- what was that -- a tease?
DOCTOR I can help you if you take the responsibility to keep regular app --
MELVIN You changed the room around...
DOCTOR Two years ago...
Melvin shakes his head -- as if things weren't bad enough he must go through a careful exercise noting every new element before he's at all comfortable...
as he studies each object.
The Doctor is professionally intrigued despite himself.
DOCTOR I also regrew my beard...
DOCTOR but you're not interested in changes in me...
DOCTOR so it's like I always told you...
DOCTOR when it comes to people you...
MELVIN Shhhhhhh.
MELVIN I don't have this mountain of available time...
MELVIN I got to get to my restaurant on time.
MELVIN Do you know how hard it is for me to be here?
DOCTOR Yes.
DOCTOR No.
More PATIENTS in the almost-crowded waiting room.
Melvin passes through -- visibly drawn and upset.
He stops.
Eyes on them.
Then:
MELVIN What if this is as good as it gets?
They look stricken.
He exits.
As he walks to his booth and sits down.
Enormous relief.
CHERYL, a heavy-set waitress, reluctantly moves to his table -- unseen by Melvin as he takes out his utensils and arranges them.
In a corner booth, four big TRANSIT AUTHORITY POLICE are having a meal together.
Cheryl looks at his utensils.
CHERYL What the heck are those for?
MELVIN No.
MELVIN No.
MELVIN Get Carol.
CHERYL I'm filling in.
CHERYL We don't know if she's coming back.
CHERYL She might have to get a job closer to home.
MELVIN What are you trying to do to me?
CHERYL What the heck do you mean?
MELVIN Hey, elephant girl, call her or something...
MELVIN just let her do my one meal here.
MELVIN I'll pay whatever.
MELVIN I'll wait.
MELVIN Do it!!!
The MANAGER comes over, gesturing to the table of police that he can handle it.
All attention is on Melvin.
MANAGER Out.
MANAGER Be silent or leave.
MELVIN I'll be quiet.
MELVIN Just let me wait.
MELVIN No problem.
MELVIN Get her here -- have her get me two sausages, four bacon, two eggs over easy and coffee.
MELVIN I'm not a prick here -- I'm a great customer.
MELVIN This day is a disaster.
MELVIN I can't handle this, too.
MANAGER Get out immediately or there's going to be trouble.
Melvin looks at the police, sizes up the hopeless situation and rises.
MELVIN There's going to be trouble???
He walks toward the door as Cheryl and all the other employees applaud his defeat.
As he passes a BUSBOY near the door he hands him 20 dollars.
MELVIN Carol's last name?
BUSBOY Connelly.
An uncomfortable Melvin sitting in the back of a taxi.
A neighborhood in Brooklyn -- a community.
Melvin, ever the shark observer, looks from the cab to see slices of community life -- MEN in front of a bar, PARENTS giving their CHILD a ride on a mechanical horse outside a local store -- two YOUNG WOMEN discuss dating.
As he exits -- RINGS the BELL and is BUZZED in.
Carol opens the door just as he arrives on her landing.
She holds a container of ice, washclothes and a thermometer.
MELVIN I'm hungry.
MELVIN You've upset my whole day.
MELVIN I haven't eaten.
CAROL What are you doing here?
Melvin ignores the question, instead answering a charge he had imagined she might make...
MELVIN This is not a sexist thing.
MELVIN If you were a waiter I would still be here saying...
CAROL Are you totally gone?
CAROL This is my private home...
MELVIN I am trying to keep emotions out of this.
MELVIN Even though this is an important issue to me and I have strong feelings about the subject.
CAROL What subject?
CAROL That I wasn't there to take crap from you and bring you eggs?
CAROL Do you have any control over how creepy you allow yourself to get?
MELVIN Yes, I do, as a matter of fact...
MELVIN and to prove it I have not gotten personal and you have.
MELVIN Why aren't you at work?
MELVIN You're not sick -- you don't look sick...
MELVIN just very tired and bitter.
CAROL My son is sick, okay?
Even saying the sentence, "My son is sick" pushes some emotions toward the surface which are wasted on the crazy man at her threshold.
MELVIN What about your mother?
CAROL How do you know about my mother?
MELVIN I hear you talk when I'm waiting!!!
She crosses to the sink to dump the ice.
Melvin takes a step inside.
Spencer, seven and looking ill, walks into the room.
CAROL Sorry, honey...
CAROL I'll be right there.
MELVIN How ya doing?
Spencer just stares at him.
MELVIN You should answer when someone talks to you...
Carol eyes Melvin with disgust and disbelief then emphatically gestures him to "clear out."
Melvin backs out the door.
CAROL Sorry.
CAROL There is a limit, Melvin, and I can't handle you teaching my son manners.
She closes the door in his face, then walks to her son and leads him back to his room.
CAMERA MOVES TOWARD mother and son sitting on the edge of Spencer's bed.
She holds a digital thermometer to his ear.
They both count down the seconds.
CAROL AND SPENCER 5...
CAROL AND SPENCER 4...
CAROL AND SPENCER 3...
CAROL AND SPENCER 2...
CAROL AND SPENCER 1...
CAROL AND SPENCER Bingo.
CAROL We are going to treat ourselves to a cab ride.
As Carol carries her young son through a class of uniformed KIDS from a Catholic elementary school.
She spots Melvin about to enter a cab.
CAROL Melvin, wait!
The school kids pick up the chant in unison.
SCHOOL KIDS Melvin, wait!
SCHOOL KIDS Melvin, wait!
SCHOOL KIDS Melvin, wait!
He turns to face them.
MELVIN Shut up, kids!
They immediately obey as Carol approaches him.
CAROL Melvin...
CAROL give us a lift.
CAROL We've got to go see our friends at the hospital.
Melvin is thrown...
he pauses a beat...
then holds the rear door open as Carol hustles the kid inside.
The maneuver puts the beet red, sweating Spencer at his face.
MELVIN I'll ride up front.
MELVIN Cover your mouth when you cough, kid.
As they settle in and drive off.
CAROL Brooklyn Presbyterian Hospital, please and quickly please.
As Carol enters the hospital.
CAROL I owe you three dollars.
Melvin follows behind her as she carries her son...
MELVIN Yeah, yeah...
MELVIN any chance you'll get back to work today?
CAROL No!!!
CAROL Stay away from me!
Verdell lies just inside the front door whimpering for Melvin.
Jackie sits across from Simon's wheel chair...
she has some index cards in her laps which she occasionally consults and shuffles.
JACKIE I feel terrible that I have to...
JACKIE Simon?
JACKIE Forget about the dog for a second.
Simon forces his attention to Jackie.
SIMON Sorry.
SIMON What are those cards?
JACKIE Frank's idea.
JACKIE He thought I should have notes so I did this right...
JACKIE maintained focus, didn't get emotional and tried not to terrify you.
SIMON Terrify me?
JACKIE See, he's right.
JACKIE I need the cards.
JACKIE Simon, you're broke.
ANGLE ON VERDELL as their conversation continues -- the dog is distressed.
JACKIE The medical bill are 61 thousand now.
JACKIE I've spoken to your parents and they didn't hang up or anything -- they just said they would feel strange calling you.
SIMON Well, I can't reach them.
Verdell walks out on the terrace and looks off.
He turns for:
SIMON Here, baby...
SIMON what is it, Verdell?...
SIMON You miss the tough guy...
SIMON Well, here I am, you little pissant mop, happy to see me?
SIMON How about another ride down the chute?
SIMON Oh, God...
SIMON I don't mean it, sweetheart...
SIMON I'm sorry.
SIMON I know...
Verdell hides behind a chair.
JACKIE Frank loves you.
JACKIE You know that...
JACKIE but I've spoken to him and he feels that --
JACKIE -- as a businessman, with limited resources...
SIMON I'll be able to keep my apartment and studio, won't I?...
SIMON Just tell me.
As Jackie looks at him then thumbs for a card.
SIMON Wow...
Verdell has come near him -- he reaches out a hand to pet the dog and the dog ducks.
He is trying to write.
He can't.
His world has been upset.
He walks away from his work -- a highly unusual act.
He is distressed -- and then an idea and he exits.
We are looking at ZOE, the receptionist.
She is listening with interest to an O.S. conversation while answering phone calls, "Premier Publishing."
FEMALE EXECUTIVE Yes, you write more than anyone else.
FEMALE EXECUTIVE Yes, you make us a lot of money, but isn't there someone more appropriate to...
MELVIN I need this.
MELVIN Just say, "Melvin, I'll try," okay?
FEMALE EXECUTIVE Melvin, I'll try.
They appear now -- the woman tall, attractive, etc.
She pauses at the elevator.
FEMALE EXECUTIVE Now, on a pleasant note, our son got accepted at Brown.
FEMALE EXECUTIVE My husband...
MELVIN Great, wonderful.
MELVIN I don't need you to wait with me.
She nods, pissed, waves and leaves.
As Melvin waits, Zoe summons her moxie.
ZOE I can't resist.
ZOE You usually move through here so quickly and I have so many questions I want to ask you.
ZOE You have no idea what your work means to me.
MELVIN What's it mean?
ZOE That somebody out there knows what it's like to be...
ZOE in here.
MELVIN Oh God, this is like a nightmare.
ZOE Aw come on, just a couple of questions -- how hard is that?
As he hits the button, wipes his fingers, hits the button etc.
ZOE How do you write women so well?
MELVIN I think of a man and take away reason and accountability.
The fan is jolted as the elevator doors open and close.
A depleted, exhausted Carol approaches her home.
She is suddenly wary -- SOUND DIALED DOWN -- as we MOVE CLOSER.
A car at the curb with "MD" license plate.
As Carol breaks into a run.
As she bounds the stairs, comes to her apartment door and jiggles with the keys, a strange prescient whimpering sound coming from her.
As she enters the apartment.
CAROL Hello?
CAROL Hello?
VOICE Mrs. Connelly, I'm in here.
The worst confirmed, she moves down the narrow hallway, her innards squirting the same chemicals that drives elk on opening day of the hunting season.
CAROL What?
CAROL Please?
CAROL Now?
CAROL Tell me?!
DR. BETTES Mrs. Connelly.
DR. BETTES I'm Martin Bettes ...
DR. BETTES Dr. Bettes.
CAROL Not your name...
CAROL what are you telling me your name for!!
CAROL Where is he?
DR. BETTES He's in the bathroom...
DR. BETTES He's fine.
CAROL Tell me how bad it is.
CAROL I let him go out last night when it was so cool without an overshirt -- just and underone with just the straps and I know better...
CAROL and I let him talk me into it.
CAROL He was whining and...
CAROL you don't need this.
CAROL Give me a second to catch hold.
And so she does.
Wow does she...
and gives us some notion of the size of her fear demon and the strength it takes to subdue it as Dr. Bettes keeps reassuring her and she keeps nodding...
finally a deep breath as Spencer enters from the bathroom.
All at hyper speed now.
Salvation as farce.
SPENCER Hi...
SPENCER Did you know there are doctors who come to your house?
CAROL No, I didn't.
CAROL So why are you h...
Beverly, Carol's mother, enters the room.
She is ebullient which, if life allowed, would be her natural state.
BEVERLY I didn't know you had a secret admire.
CAROL Huh?
BEVERLY You met the gift.
SPENCER He's good...
SPENCER And I'm an expert on doctors.
CAROL Stay out of this...
CAROL Doctor?
DR. BETTES My wife is Melvin Udall's publisher.
DR. BETTES She says I have to take great care of this guy because you're urgently needed back at work.
DR. BETTES What work do you do?
CAROL I'm a waitress.
ON Dr. Bettes' reaction her mother adds a saving grace.
BEVERLY In Manhattan.
VOICE Dr. Bettes?
DR. BETTES In here.
A NURSE enters.
NURSE Sorry it took so long.
NURSE I don't know Brooklyn.
DR. BETTES It's okay, Terry.
DR. BETTES Tell the lab I'd like the report back today.
Carol and her mother exchange a look of incredulity.
CAROL You're going to get the results today?!
As we approach the doctor and Carol seated across from each other at a small table...
soft voices...
relaxation.
Bettes is examining medicine bottles.
DR. BETTES How long has he been having problems?
CAROL Since forever.
DR. BETTES Have they done blood tests on him?
CAROL Yes.
DR. BETTES Only in the emergency room or when he was well.
CAROL Emergency room only.
DR. BETTES Have they done skin testing for allergies?
CAROL No.
DR. BETTES They haven't done the standard scratch test.
DR. BETTES Where they make small injections into the skin?
CAROL No.
CAROL I asked.
CAROL They said it's not covered under my plan.
CAROL And it's not necessary anyway.
DR. BETTES It's amazing these things weren't done.
CAROL Fucking H.M.O. bastard piece of shit...
CAROL I'm sorry...
CAROL forgive me.
DR. BETTES No.
DR. BETTES Actually, I think that's their technical name.
CAROL Once the tests come back, is there someone I can reach in your office for the results?
DR. BETTES Me.
DR. BETTES My home number is on this card.
CAROL His home number.
Carol look at her mother -- they share a laugh.
Beverly has a hard time stopping.
CAROL Do you want some juice or coffee or two female slaves?
DR. BETTES Water...
DR. BETTES Nobody told you it might be a good idea to remove the carpeting and drapes in Spencer's room?
CAROL No.
She starts towards Spencer's room.
DR. BETTES You don't have to do it this second...
DR. BETTES it's not dangerous or anything.
DR. BETTES It's just something that's advisable.
DR. BETTES Look, there's a lot to be checked but...
DR. BETTES Hey, your son is going to feel a good deal better at the very least...
She pats his head...
Then embraces him with fierce intimacy.
CAROL Doc!!!
CAROL So listen, you gotta let me know about the additional costs -- one way or the other we'll...
DR. BETTES They're considerable.
DR. BETTES But Mr.
DR. BETTES Udall wants to be billed.
She takes this as a blow to the heart, stomach and groin.
Simon practices walking using his cane.
A tearstained Nora hugs him good-bye.
NORA You poor, poor man.
SIMON Let's use just one poor, okay?
SIMON Anyway, dear, thanks for everything.
SIMON Forgive my recent crankiness and as soon as things are on track again I'll call.
She kisses him and starts for the door and suddenly a sharp intake of breath -- she's forgotten something.
SIMON What's wrong?
NORA Who's going to walk Verdell?
Simon hadn't thought of this either.
SIMON No, no.
Nora holding her things, knocks on Melvin's door.
Melvin opens the door.
Nora is still sniffling.
He misinterprets.
MELVIN Is he dead yet?
NORA No!
NORA Would there be any way for you to be willing to walk his dog for him?
MELVIN Absolutely.
NORA Not just today -- Uh, could you do it -- until, until he gets back on his feet?
MELVIN Sure thing.
NORA You're a wonderful man.
NORA Two o'clock is a good time.
NORA Here's the key in case he's asleep.
NORA Open the curtains for him, so he sees God's beautiful work and knows that even things like this happen for the best.
MELVIN Where'd they teach you to talk like this -- some Panama City "Sailor want to hump-hump bar"?
MELVIN Or was today getaway day and your last shot at his whiskey.
MELVIN Sell crazy some place else -- we're all stocked up here.
He closes the door in her face.
She stands there...
thrown by the abruptness -- then lifts the two paper shopping bags holding her things -- walks back toward the elevator -- pausing briefly outside Simon's door -- then continues on her way.
The doctor gone, mother and daughter arguing.
CAROL There is a seriously goofy man behind this.
CAROL You are not allowed to block out that fact.
BEVERLY Do you really want to go back to the runt doctors in Emergency who keep telling us they can't help?
CAROL It lets a crazy man into our lives.
BEVERLY Come on.
BEVERLY Why fight when we know how it will come out.
BEVERLY This isn't like stocking or a string of pearls.
BEVERLY You don't send this one back.
Shades drawn.
Simon is a wheelchair...
the PHONE RINGS.
He goes to answer...
the phone across the bed so that reaching for the phone is a brief but difficult struggle...
he grunts with pain, hope and anxiety as he answers.
SIMON Hello?...
SIMON yes...
SIMON sure...
SIMON finally, huh?
SIMON Why, "finally"?
SIMON Because I called you so many times.
SIMON Maybe
20. Oh, boy...
20. I was hoping it was something like that.
20. You didn't get one of them, huh?
20. 'Cause I mean it wasn't only your office -- it was your home, hotel and the cigar club you like in San Francisco.
20. No -- Sarcastic...
20. Of course.
20. I believe you.
20. No, don't fire anyone...
20. Please.
20. Maybe I'm wrong about the 20 times.
20. Take a breath...
20. So, you miss me a little?
20. Hey, strike the question -- How's the case going?
20. Really.
20. Fantastic.
20. I didn't hear.
20. I haven't been watching.
20. Great.
20. Just great.
20. I'm so happy.
20. Whoopie!
20. Me?
20. Well, I'm mending.
20. No, I look fine.
20. Well, some of the damage might still be noticeable if you look closely...
He runs a hand across his scarred and still bloated and beaten face...
SIMON Carl, I need some help and you're the logical one to turn to.
SIMON No!
SIMON Not 'cause I blame you for what happened.
SIMON I hardly get how you can ever think that.
SIMON No, I'm not being sarcastic.
SIMON I guess because you hired the guy who did this you think...
SIMON No, I am a sarcastic person.
SIMON Well, if you must know, the reason I said you were the logical person is because you always told me how you thought I was this great person who made you feel good about humanity and everything.
SIMON You do remembering saying that?
SIMON Well, whew.
SIMON Okay, so Carl.
SIMON I hate asking but this money thing is ridiculously serious...
He picks up an index card from his night stand and takes the leap -- reading the text he prepared in advance.
SIMON "Will you please loan me money?
SIMON I will pay you back.
SIMON I will give you whatever percentage of my income I don't absolutely need until I do.
SIMON It will take a while.
SIMON But I don't know what I'll do if you say"...
SIMON that.
SIMON I understand...
SIMON yes...
SIMON No, I do.
SIMON But you know, you know -- you didn't even ask how much, Carl?
SIMON Well, Frank has no right to discuss how much I'm in hock...
SIMON no, you're right -- not the point.
SIMON So...
SIMON what have you been up to???
SIMON Uh-huh...
SIMON Oh, the group show...
SIMON how was it?
SIMON Well, I'm not surprised that there's that much talent around...
SIMON great...
SIMON Look -- gotta go...
SIMON no, you shouldn't feel that way at all...
SIMON take care, you, too...
SIMON you, too...
SIMON Good-bye.
SIMON Pal o' mine.
It's very quiet.
A lonely figure -- who now holds his good hand up to his face and appears on the verge of enormous emotional release -- CAMERA MOVES TOWARD him as if to rendezvous with the moment of catharsis...
...
but Simon is denied even this small luxury as the CAMERA ABRUPTLY ADJUSTS just as he begins sobbing to focus on the door opening and Melvin and Verdell entering the room.
MELVIN Maybe I'll bring him some food by.
SIMON Thank you for walking him.
Simon wheels away from Melvin.
SIMON If you'll excuse me I'm not feeling so well.
MELVIN It smells like shit in here?
SIMON Go away.
MELVIN That cleaning woman doesn't...
SIMON Please, just leave.
MELVIN Where are all your queer party friends?
SIMON Get out.
Melvin pauses -- Simon weeping...
Verdell looks at Simon with concern.
Melvin is thrown.
Moved?
SIMON Nothing worse than having to feel this way in front of you?
MELVIN Nellie, you're a disgrace to depression.
SIMON Rot in hell, Melvin.
MELVIN No need to stop being a lady...
MELVIN quit worrying -- you'll be back on your knees in no time.
Simon swings his arm and cast at Melvin -- the sudden attack jolts Melvin but not as much as what follows.
SIMON Is this fun for you?
SIMON Well, you lucky devil...
SIMON It just gets better and better.
SIMON I am losing my apartment and Frank wants me to promise to paint hotter subjects and to beg my parents, who haven't called, for help...
SIMON and I won't.
SIMON And I don't want to paint anymore.
Melvin has made for the door...
Simon blocks him.
SIMON So the life I was trying for is over.
SIMON The life I had is gone and I am feeling so damn sorry for myself that it is difficult to breathe.
SIMON Right times for you -- huh, Melvin.
SIMON The gay neighbor is terrified...
SIMON Terrified...
SIMON Lucky you, you're here for rock bottom...
SIMON me wallowing in self-pity in front of you, you absolute horror of a human being...
As Simon works to stop crying, Melvin is weird with discomfort.
MELVIN Well, I'll do one thing for you that might cheer you up.
SIMON Get out.
MELVIN Don't piss on a gift, tough guy.
MELVIN You want to know why the dog prefers me...
MELVIN it's not affection.
MELVIN It's a trick.
Simon looks up, his mood turning on a dime -- he's rapt...
Melvin comes and stands by his wheelchair.
MELVIN I carry bacon in my pocket.
SIMON Oh, my gosh.
MELVIN Now we'll both call him.
SIMON Come on, sweetheart...
MELVIN Yo, yo, yo...
Verdell goes like a bullet to Melvin...
who is totally surprised and staggered by the implications.
True love and such.
SIMON Would you leave now, please?
MELVIN Stupid dog.
MELVIN I don't get it.
He exits...
looking apologetically at Simon in stoic ruin.
Carol in bed on the pullout sofa...
She is in turmoil...
there is THUNDER, but no rain.
She walks to the kitchen.
She is trembling as she drinks a glass of water and exits.
The room is on an air shaft and this is where Carol shares a closet with her mother, who is now asleep.
Carol quietly extracts a dress from the closet, leaving her nightgown on the floor.
There is something sexy here, the woman in Carol churning.
She plops on a summer dress -- no time for underwear.
Carol seeing a bus and dashing after it.
Carol crossing to Manhattan.
She looks as if she's on her way to some final exam where she has no notion of the subject.
Hot summer night as she gets off the bus and now the rains come...
We are in a familiar neighborhood.
As Carol consults the slip of paper with the address on it.
As she enters building and realizes it's not just that she's wet -- the thin summer dress is a winner in any wet T-shirt contest...
the fabric clinging to her breasts, like the old movie poster of The Deep.
As Carol passes Simon's door...
stands in front of Melvin's apartment -- twists herself to ease nervousness and knocks on the door...
then RINGS the BELL.
Finally Carol hears MUFFLED THROAT CLEARING on the other side of the door.
CAROL Uh, Udall?
MELVIN Carol the waitress?
CAROL Yes.
As we hear him unlock the door, Carol looks at her breasts and gasps.
She grasps the fabric and holds it straight out just as Melvin opens the door.
His hair is static city, standing on end as he periodically gives it self-conscious pats.
CAROL The doctors had your billing address.
CAROL I'm sorry about the hour.
MELVIN I was working...
MELVIN can't you just drop me a thank-you note?
CAROL That's not why I'm here...
CAROL ...
CAROL though you have no idea what it's like to have a real conversation with a doctor about Spencer...
MELVIN Note.
MELVIN Put it in the note.
CAROL Why did yo do this for me?
MELVIN To get you back at work so you can wait on me.
CAROL But you do have some idea how strange that sounds???
CAROL I'm worried that you did this because...
She pauses -- the beginning of an extraordinarily long silence.
Finally.
MELVIN You waiting for me to say something?
MELVIN What sort of thing do you want?
MELVIN Look, I'll be at the restaurant tomorrow.
CAROL I don't think I can wait until tomorrow.
CAROL This needs clearing up.
MELVIN What needs clearing up?
CAROL I'm not going to sleep with you.
CAROL I will never, ever sleep with you.
CAROL Never.
CAROL Not ever.
Melvin's reaction?
Well, he'll never get credit for the brief but intense inner struggle -- the struggle not to scream --
-- not to cry -- to process the sudden and stunning hurt during his half turn away from her -- and then answer hoarsely.
MELVIN I'm sorry.
MELVIN We don't open for the no-sex oaths until 9 a.m.
Carol is amused, surprised...
maybe, in some small way ever taken by his style...
but top priority is clarity.
CAROL I'm not kidding.
MELVIN Okay!!!!
MELVIN Anything else?!?
CAROL Just how grateful I am.
Her mission completed -- she turns.
MELVIN So you'll be at work?
CAROL Yes.
It's a 3:22 a.m.
as the two digital clocks on Melvin's night stand tell us...
He gets up -- the first time we've seen his waking routine -- taps one foot on the floor twice -- then the other foot -- two more taps and his body angles from the bed in a deliberate way.
He is having anxiety.
He sits at the piano and plays very briefly...
Stops -- wipes some sweat from his forehead...
Walks to his computer room -- turns the light on and then quickly off...
Walks to his refrigerator...
As he grabs a cardboard take-out box...
He knocks of Simon's door...
It opens quickly.
MELVIN I took a chance you were up.
Simon walks painfully back to a chair.
MELVIN I brought you Chinese soup.
SIMON Thanks.
MELVIN I have never been so tired in my life.
MELVIN Okay, if I sit here?
SIMON Got any easier questions?
Melvin sits and moans -- the dog sitting near him.
MELVIN I haven't been sleeping.
MELVIN I haven't been clear or felt like myself.
MELVIN I'm in trouble.
MELVIN Some son of a bitch is burning my bridges behind my back...
MELVIN But the tiredness -- boy...
MELVIN Not just sleepy.
SIMON But sick -- nauseous -- where everything looks distorted and everything inside just aches -- when you can barely get up the will to complain.
MELVIN Yeah...
He feels a touch of community and not knowing where to take it from here.
MELVIN I'm glad we did this.
He rises and makes an awkward exit.
MELVIN Good talking to you.
He exits -- Simon puzzled and concerned.
Carol seated working on a letter...
She is trying to express her gratitude...
An enormous sheaf of completed pages sit next to her...
She is so involved she doesn't even look up as a young man, SEAN, knocks on the door and is let in by Beverly.
They exchange greetings and move inside where we faintly hear Spencer greeting him...
We MOVE IN and read over Carol's shoulder -- "I'm sorry to have gotten sloppy and emotional in this letter, but it would have been on my conscionce (sic) forever if I didn't tell you how gratefull (sic)...
BEVERLY You're not still writing that thank-you note?
CAROL I'm on the last page.
CAROL How do you spell conscience?
BEVERLY C-o-n-s-c-i-e-n-c-e.
BEVERLY I got Sean from the bakery to baby-sit so let's go out.
CAROL I still don't feel safe leaving Spencer with someone.
CAROL How do you spell it again?
BEVERLY Spencer is okay.
BEVERLY You'd better start finding something else to do with your free time.
BEVERLY If you can't feel good about this break and step out a little...
BEVERLY You ought to get Mr. Udall to send you over a psychiatrist.
CAROL I don't need one 'cause I know what's really going on here.
CAROL I have to finish this letter or I'll go nuts.
CAROL This can't be right -- con- science.
Carol breathes heavily -- gets control, stopping herself on the brink of crying.
BEVERLY Carol.
BEVERLY What?
Carol is amazed at herself...
that she might not be able to stem the flow...
wide-eyed with apprehension, she looks at her mother, who, in return, only nods permission for Carol to let it go.
A last defiant snort from Carol -- and then she is overwhelmed.
The headline comes first.
CAROL I don't know...
CAROL It's very strange not feeling that stupid panic thing inside you all the time.
CAROL Without that you just start thinking about yourself -- and what does that ever get anybody.
CAROL Today, on the bus there was this adorable couple and I felt myself giving them a dirty look -- I had no idea everything was...
BEVERLY Go ahead.
CAROL ...
CAROL moving in the wrong direction...
CAROL Away from when I even remembered what it was like to have a man to...
CAROL anything...
CAROL hold fucking -- sorry -- hands with, for Christ's sake.
CAROL I was feeling like really bad that Dr.
CAROL Bettes is married.
CAROL Which is probably why I make poor Spencer hug me more than he wants to...
CAROL Like the poor kid doesn't have enough problems.
CAROL He has to make up for his mom not getting any.
CAROL Oh, boy.
CAROL Who needs these thoughts?
BEVERLY Spencer's doing fine.
BEVERLY So what are you saying, that you're frustr...
CAROL Leave me be!
CAROL Why are you doing this?
CAROL Why are you picking at my sores...
CAROL What is it that you want?...
CAROL You want what?
CAROL What's with you?
CAROL I hope getting me thinking of everything that's wrong when all I want is to not do this has some purpose.
CAROL What is it, Mom?
CAROL No kidding.
Slumped, fought out -- Carol gets out one last, naked husky voiced question.
CAROL What is it you want?
CAROL What?
BEVERLY I want us to go out.
A beat, then.
CAROL Okay.
As they enter, still wiping away the effects of their cry.
CAROL We're going out.
SEAN Looks like fun.
She kisses Spencer -- almost getting involved in what he's doing -- then sees her mother waiting.
CAROL Okay -- we're out of here.
CAROL I love you.
Spencer nods -- involved with Sean.
CAMERA FOLLOWS Carol as she exits the apartment -- her mother leading.
Halfway down the stairs, she stops and reverses herself, going back to the apartment which she re-enters -- then to her son to ask:
CAROL Do you love me?
SPENCER Uh-huh.
Carol exits.
Beverly and Carol walking past the store windows.
A simple and unprecedented experience in their recent lives.
BEVERLY Nice to get out, isn't it?
Carol nods tightly...
then they wrap arms around each other and continue walking, turning into a corner bar.
As Carol stands nervously while Lisa finishes reading her 14-page letter.
In the b.g.
Melvin and Frank are seated at the same table and in earnest conversation.
Lisa keeps flicking away tears -- a few drops on the pages.
CAROL Don't get it wet.
Lisa brushes the paper -- finishes and embraces Carol.
CAROL So it's okay?
LISA You almost have me liking him.
LISA You sure come from the heart.
LISA I never knew what you went through with everything.
CAROL I wanted him to know how much he'd done.
CAROL Can you believe he's eating with someone.
MELVIN It's not my dog and this Simon seems to have enough on his mind -- but he did throw up twice and his spark is off.
FRANK Sure -- take him to the vet.
MELVIN I did.
MELVIN And his stomach is out of whack.
MELVIN So they need him for a couple of days.
FRANK Do it.
CAROL Melvin.
She self-consciously hands him with the thick envelope.
MELVIN What's this?
CAROL A thank-you note for what you did for me.
He hands it back to her deliberately.
She takes it and walks back to the service area where, embarrassed, confused, and messed with -- she tosses the note.
After Carol leaves...
FRANK She's nice.
MELVIN Really nice.
MELVIN Shouldn't that be a good thing...
MELVIN telling someone, 'no thanks required.'
FRANK It looks like it really went over.
FRANK You're sure making the rounds.
FRANK Simon says you brought him soup last night.
FRANK I hope he doesn't write you a note.
Melvin looks up -- wary -- his brain sends a disturbing message.
FRANK What?
MELVIN "What?" Look at you...
MELVIN You sense a mark.
FRANK Hey -- you called me...
FRANK I...
MELVIN About a dog.
FRANK Yeah, but it's all about Simon now...
FRANK you helped with the dog...
FRANK And now there are other things.
FRANK I'm just as concerned as you are about Simon.
MELVIN Concerned.
MELVIN I'm just the hall monitor here.
FRANK It's not only financial assistance.
FRANK What he's got to do is go to Baltimore tomorrow and ask his parents for money.
FRANK It's not going to happen on the phone.
MELVIN Yeah.
MELVIN If his parents are alive they've got to help -- those are the rules.
MELVIN Good.
FRANK Yes.
FRANK And tomorrow?
FRANK I have a high maintenance selling painter coming through...
FRANK So I'm out.
FRANK Can you take him?
MELVIN Think white and get serious.
Carol enters scene.
FRANK Take my car -- a convertible.
FRANK Do you drive?
MELVIN Like the wind but I'm not doing it.
CAROL Getting loud, getting loud.
MELVIN He wants me to take his car and his client to Baltimore.
CAROL I want your life for a minute where my big problem is someone offers me a free convertible so I can get out of this city.
She exits.
Frank prepares to depart.
MELVIN Okay.
MELVIN I'll take him.
MELVIN Get him packed -- ready -- tomorrow morning.
Frank stumbles back...
self-satisfied, he relaxes.
MELVIN Okay...
MELVIN so I'll see you tomorrow.
MELVIN Let's not drag this out.
MELVIN We don't enjoy another that much.
FRANK If there's some mental health foundation that raises money to help people like you be sure to let me know.
MELVIN Last word freak.
Frank adjusts and exits...
Carol approaches calling a "good-bye" to him.
CAROL So.
CAROL Anything else?
MELVIN Yes.
MELVIN I'm going to give my queer neighbor a lift to Baltimore.
CAROL Okay.
MELVIN Hey, what I did for you is working out?
CAROL What you did changed my life.
She offers him the note.
MELVIN No...
MELVIN no thank you notes.
CAROL Well, part of what I said in this entire history of my life which you won't read is that somehow you've done more for my mother, my son and me, than anyone else ever has...
CAROL And that makes you the most important, surprising, generous person I've ever met and that you be in our daily prayers forever.
MELVIN Lovely.
CAROL I also wrote one part...
CAROL I wrote I'm sorry...
CAROL I was talking about I was sorry when I got mad at you when you came over and you told my son that he ought to answer back so I wrote that.
CAROL I was sorry for busting you on that...
CAROL and I'm sorry for busting in on you that night...
CAROL when I said I was never...
CAROL I was sorry and I'm sorry every time your food was cold and that you had to wait two seconds for a coffee filler...
Melvin wants to disappear but Carol is getting into it -- emotionally moved by her own words.
CAROL ...
CAROL and I'm sorry for never spotting, right there at the table in the restaurant, the human being that had it in him to do this thing for us...
CAROL You know what, I'm just going to start from the beginning...
CAROL I have not been able to express my gratefulness to you...
CAROL even as I look at the word "grateful" now it doesn't begin to tell you what I feel for you...
And finally Carol notes Melvin's mood and pauses.
MELVIN Nice of you...
MELVIN thank you.
CAROL Thank you.
MELVIN Now I want you to do something for me.
She looks at him for a very strange, long beat.
CAROL Oh, I'm sorry...
CAROL Didn't I say, "what?" I thought I said, "what?"...
CAROL What?
MELVIN I want you to go on this trip.
CAROL No, sir...
MELVIN I can't do this alone.
MELVIN I'm afraid he'll pull the stiff one eye on me.
MELVIN I need you to chaperon.
MELVIN Separate everything but cars.
MELVIN You said you liked convertibles.
MELVIN Now I'm on the hook.
CAROL The stiff one eye?
MELVIN Two days.
CAROL I can't.
CAROL I work.
MELVIN You take off when you have to.
CAROL My son.
MELVIN Bettes tells me he's doing fine.
CAROL Melvin, I'd rather not.
MELVIN What's that got to do with it?
CAROL Funny, I thought it was a strong point.
MELVIN Write me a note and ain't she sweet.
MELVIN I need a hand and where'd she go.
CAROL Are you saying accepting your help obligates me!?
MELVIN Is there another way to see it?
CAROL No.
Carol takes an old weekend case down from the top shelf of the closet.
CAROL Well, here's a little suitcase shocked that it's been used.
She holds up a dress -- a pretty one...
then decides it's too pretty and puts it back...
Now she looks in another drawer and pauses as if she ponders one of the mysteries of the ages.
She hesitates then talks to herself.
Her best underwear neatly stacked alongside her everyday "girl Jockies."
She fingers the good stuff -- puts it back -- then the everyday -- hesitates.
CAROL There's not way to pack for this trip...
CAROL well, I'll tell you -- I'm not packing the camera.
As she exits the room --
As she picks up the phone.
Melvin is in his bedroom -- everything he's taking neatly stacked on the bed waiting to be packed (he is taking a camera).
He has a list of what he needs.
All items -- underwear, socks, etc...
with four checks next to each one and still he -- checks each stack on the bed and adds another check.
The PHONE RINGS.
This is an amazing development.
He has almost no recent experience with receiving a nighttime phone call.
He makes a little comment to himself as he moves.
MELVIN Woo-woo.
He stops -- briefly trying to remember where the phone is -- and then, remembering, crosses and picks it up but before bringing it to his mouth nervously clears his throat.
As she hears his throat being cleared.
It is not a pretty sound.
(The following conversation is INTERCUT.)
CAROL Hello?
MELVIN Are you still coming?
CAROL Yes.
Melvin visibly relaxes.
CAROL Melvin...
CAROL I'd like to know exactly where we are going.
MELVIN Just south to Baltimore, Maryland.
MELVIN So I know what you're going to ask next.
MELVIN That you might ask -- I'm not certain.
CAROL There's...
CAROL there's no need to bring anything dressy...
CAROL or...
CAROL I mean -- I didn't know if we'd be eating at any restaurant that have dress codes.
MELVIN Oh.
MELVIN We might.
MELVIN Yes.
MELVIN We can.
MELVIN Let's.
CAROL Okay, gotcha.
CAROL What did you think I was going to ask?
MELVIN Whether crabs are in season there now...
CAROL Oh.
CAROL Okay, then -- Melvin.
CAROL Good night.
Beverly looks up expectantly as her daughter enters.
BEVERLY How was it talking to him?
CAROL Stop treating this like I'm going away with a man.
CAROL He's just going to say those crappy, sick, complaining, angry things to me.
CAROL I hate this, Mom -- I hate this.
CAROL He's a freak show -- the worst person I ever met.
BEVERLY Well, maybe he has nice friends.
Beverly and Spencer wait with her.
The bus approaches.
She kisses them.
CAROL You stand there and I'll wave to you from the back window.
As she boards the bus.
BEVERLY Call me as soon as you're settled.
CAROL I love you.
The bus driver closes the doors on her -- she shoves them open.
CAROL Sensitive, huh?!
The bus pulls out.
He runs after the bus -- waving at his mother who grows concerned that he might be taxing himself.
A female VETERINARIAN in surgical scrubs holds Verdell as Melvin finishes filling out some forms.
On opposite sides of the waiting room, a very large black dog and a tiny Chihuahua sit patiently with their owners.
VETERINARIAN Anything unusual in the dog's diet?
MELVIN No.
MELVIN Everybody gets their own cage?
VETERINARIAN Certainly.
MELVIN Put him in with that one, not that one...
MELVIN ...
MELVIN Builds his confidence.
Carol disembarks.
As she walks and turns a corner.
The shot of the prisoner taking the walk toward the death chamber.
But the prisoner -- has grit -- her knees do not buckle.
She does not whimper.
No prison "screws" will have to support her weight.
Still, the prospect couldn't be grimmer.
Melvin next to a spiffy convertible.
Top down.
Trunk open.
He is wearing driving gloves and turns to witness the tussle Frank and Simon are having just inside the building.
FRANK I'm sorry that I'm not taking you.
SIMON So am I, Frank.
Frank starts to leave -- Simon stops him.
They embrace.
MELVIN Soak it up -- it's your last chance at a hug for a few days.
As Frank moves off Melvin sees Carol and his demeanor changes...
that quickly there is a shyness.
CAROL Hi.
MELVIN Thanks for being on time...
MELVIN Carol, the waitress, this is Simon, the fag.
CAROL Hello...
CAROL Oh, my God, who did that to you?
SIMON I, uh...
SIMON I was...
SIMON attacked.
SIMON Walked in on people robbing me.
SIMON I was hospitalized.
SIMON I almost died.
MELVIN Let's do the small talk in the car.
MELVIN Load up.
Carol puts her bag in the car.
MELVIN I was going to do that for you.
CAROL It's okay.
CAROL No problem.
CAROL Where should we sit?
MELVIN I -- uh, I...
MELVIN Well, there is no place cards or anything.
CAROL Let me go in back.
CAROL You look like you need all the room you can manage.
SIMON That's very thoughtful.
MELVIN Never a break.
MELVIN Never.
Carol steps into the back.
Melvin disappointed that he's not sitting next to Carol...
Carol is wedged in the small back seat.
She struggles to get her feet in.
MELVIN You're really jammed back there.
He reaches for the latch between his legs and slides his seat and, with some effort, wrenches it forward giving Carol more room and putting his right against the wheel.
She is startled by the gesture.
CAROL Thanks, Melvin.
MELVIN Welcome.
And off they go.
Simon and Carol stunned by the manners.
Turning onto Fifth.
MELVIN I got the whole ride programmed.
CAMERA FOLLOWS as Melvin goes to a rack of CDs -- all carefully labelled.
He selects and begins to play the one marked "ICEBREAKER."
It is a song which we clearly and quickly judge as off the circumstances -- a quick burst of "Y.M.C.A."
Melvin STOPS the MUSIC and chuckles.
MELVIN Just wanted to see what you'd do.
MELVIN No, we have greatness here.
He goes for another CD labelled "FOR USE TO REP THINGS
The car turns onto Seventh as we hear BEAUTIFULLY
CAROL Hey, I like this music.
And, as the MUSIC PLAYS, Simon looks out.
The three of them...
Carol chattering away.
CAROL I don't know the last time I've been out of the city...
CAROL Hey, my arms are tanning.
CAROL I used to tan great.
CAROL We gotta stop soon so'se I can check on Spencer.
SIMON I'm sorry...
SIMON I can't hear you.
SIMON I can't turn my head all the way yet...
SIMON tell her we can't hear her.
MELVIN Doesn't matter.
MELVIN She's enjoying herself.
MELVIN Consider it part of the music.
A short time later.
Carol is now driving.
CAROL I'm sure, Simon, they did something real off for you to feel this way...
CAROL But when it comes to your partners -- or your kid -- things will always be off for you unless you set it straight.
CAROL Maybe this thing happened to you just to give you that chance.
MELVIN Nonsense!
CAROL Anybody here who's interested in what Melvin has to say raise their hands.
Simon does not raise his hand.
Simon and Carol have thus declared their majority.
SIMON Do you want to know what happened with my parents?
CAROL Yes.
CAROL I really would.
SIMON Well...
CAROL No, let me pull over so I can pay full attention.
Car pulling over toward parking spot.
She takes the car curbside and parks.
CAROL Now go ahead.
Simon looks back at Melvin as does Carol.
He looks innocent.
Several beats -- Melvin almost says something -- a hidden hand gesture from Carol stops him.
Finally.
SIMON Well, I always painted.
SIMON Always.
SIMON And my mother always encouraged it.
SIMON She was sort of fabulous about it actually...
SIMON and she used to...
SIMON I was too young to think there was anything at all wrong with it...
SIMON and she was very natural.
SIMON She used to pose nude for me...
SIMON and I thought or assumed my father was aware of it.
MELVIN This stuff is pointless.
CAROL Hey -- you let him...
MELVIN You like sad stories -- you want mine.
CARL Go ahead, Simon.
CARL Really.
CARL Please.
CARL Don't let him stop you.
CARL Ignore him.
SIMON Okay.
SIMON Well, one day my father came in on one of those painting sessions when I was nine -- and he just started screaming at her -- at us -- at evil.
SIMON And...
MELVIN ...
MELVIN my father didn't leave his room for 11 years -- he hit my hand with a yardstick if I made a mistake on the piano.
CAROL Go ahead, Simon.
CAROL Your father walked in on you and was yelling and...
CAROL really, come on.
SIMON I was trying to defend my mother and make peace, in the lamest way.
SIMON I said, "she's not naked -- it's art."
SIMON And then he started hitting me.
SIMON And he beat me unconscious.
SIMON After that he talked to me less and less -- he knew before I left for college, my dad came into my room.
SIMON He held out his hand.
SIMON It was filled with money.
SIMON A big wad of sweaty money.
SIMON And he said to me, "I don't want you to ever come back."
SIMON I grabbed him and I hugged him...
SIMON He turns and walked out.
Carol, whose life has been rugged but basic, feels as strange as she does moved by Simon's trauma which is so much more complicated than her meat and potatoes troubles.
She looks out her window -- then kisses her fingers and touches them to Simon's cheek.
A nice, understated, gesture of friendship.
CAROL Well, you know -- I still stay what I said.
CAROL You've got to get past it all when it comes to your parents.
CAROL We all have these horror stories to get over.
Melvin shifts INTO the FRAME.
MELVIN That's not true.
MELVIN Some of us have great stories...
MELVIN pretty stories that take place at lakes with boats and friends and noodle salad.
MELVIN Just not anybody in this car.
MELVIN But lots of people -- that's their story -- good times and noodle salad...
MELVIN and that's what makes it hard.
MELVIN Not that you had it bad but being that pissed that so many had it good.
CAROL No.
SIMON Not it at all, really.
MELVIN Not at all, huh?!...
MELVIN Let's go to the hotel.
MELVIN And if you're lucky tomorrow Dad will give you another wad of sweaty money.
MELVIN Two bedrooms and the sofa opens...
Carol is on the phone in the living room -- she hangs up.
CAROL No answer...
CAROL Maybe we should just drive there tomorrow.
CAROL Can I have that one?
MELVIN Yes...
MELVIN sure.
MELVIN I'll take the sofa.
Carol walks into her room -- the nicest room she'll ever have slept in...
She goes to the phone and dials...
CAROL Hello...
CAROL Hi, Spencer...
CAROL Why are you out of breath?
CAROL You did?!?
CAROL That is great...
CAROL So great...
CAROL So -- no, wait a second, Spence...
Melvin watches Simon struggle to unpack his especially neat suitcase.
Melvin is uncomfortable.
MELVIN Can I ask you a personal question?
Simon laughs loudly in apprehension squared.
MELVIN Do you ever get an erection for a woman?
SIMON Melvin...
MELVIN Wouldn't your lie be a lot easier if you were not...
SIMON You consider your life easy.
MELVIN I give you that one...
MELVIN Nice packing.
Carol enters the common living room...
Melvin is sitting there.
Carol is dealing with a number of unsettling new factors in her life.
CAROL My son was outside playing soccer.
CAROL I never saw him playing ball.
CAROL Come on, you guys -- take me out for a good time...
CAROL Take me out dancing.
MELVIN Dancing?
SIMON I can't, I'm exhausted.
Carol walks to Simon and puts an arm on him.
Melvin is visibly disturbed by her gesture.
CAROL I don't blame you...
CAROL This is a monumental first day out...
CAROL You sad or anything?
SIMON No...
SIMON Nervous.
SIMON It would be very rough, Carol, if you weren't along.
CAROL What a nice compliment.
She gives Simon a kiss...
Melvin deals with jealousy.
She turns to him.
CAROL I'm happy.
CAROL And you're my date.
CAROL Let's get dressed.
She exits the room.
Melvin unnerved.
MELVIN I'm going to jump in the shower.
MELVIN I'll be right with you.
As Carol, dressed in a thrift shop find, enters the main room of the suite and hears the SHOWER running -- she sits down to wait -- through...
Showing the enormous length of time which transpires until finally a seriously clean Melvin emerges from the bathroom through a cloud of steam.
They exit.
As they drive up.
VALET Good evening, sir.
MELVIN They sell hard shell crabs here?
VALET Yes.
As they enters...
HEAD WAITER Good evening.
MELVIN Hi.
MELVIN You have hard shells, right?
CAROL Stop asking everyone.
MELVIN Just him and that's it.
MELVIN Okay, you can answer -- we've worked it out.
HEAD WAITER Yes, we do...
HEAD WAITER And I can give you a tie and jacket.
MELVIN What?
HEAD WAITER They require a tie and jacket but we have some available.
He reaches into the coat and check room and withdraws them.
MELVIN No...
MELVIN I'm not wearing that -- and just in case you were going to ask I'm not going to let you inject me with plaque either.
CAROL You promised a nice place -- can't you just...
CAROL You have these dry cleaned all the time, don't you?
HEAD WAITER Actually, I don't think so.
MELVIN Wait here.
As Melvin takes his car back from the valet.
As the car goes right across the street to a shopping mall.
Melvin walks to the doorway and stops suddenly.
SALESMAN Good evening.
MELVIN I need a coat and tie.
CAMERA REVEALS that the floor is intricately patterned so that passage for Melvin is impossible.
SALESMAN Come on in.
MELVIN No.
SALESMAN No?
MELVIN That jacket and give me a tie.
As he pulls up - a new VALET taking his car.
VALET #2 Good evening.
MELVIN You have hard shells?
VALET #2 I'm not sure.
MELVIN Everyone else says you do.
VALET #2 Then I guess we do.
As he enters, looks for and then spot Carol.
She is having a martini at the bar...
Sitting on a stool -- watching COUPLES dance...
Happy by herself...
Turning down a MAN who wants to buy her another...
And Melvin watches...
Watches his date.
HEAD WAITER Shall I get her for you?
MELVIN No, it's all right.
MELVIN I'll just watch.
He enjoys watching her for a few more beats...
She turns -- Melvin makes a "Haul your ass over here" gesture...
and she smiles and walks toward him...
A WAITER has lifted her drink -- placed it on a tray and follows her.
She takes a bit of a slalom course through the tables, giddy as the MUSIC PLAYS and couples dance in the b.g.
She notices the waiter in her trail.
CAROL My drink is following me.
Melvin watches her approach.
It is all too exquisite.
He takes a breath -- it doesn't come easily.
CAROL You look s...
She stops herself from saying "sexy," regathers, then...
CAROL You look great.
They arrives at the table.
He holds out her chair for her.
CAROL You wanna dance?
MELVIN I've been thinking about that since you brought it up before.
CAROL And?
MELVIN No...
MELVIN ...
MELVIN I don't get this place.
MELVIN They make me buy an outfit but they let you wear a house dress.
MELVIN I don't get it.
Melvin has no idea he has insulted her.
Sandbagged in extreme, she gets up -- actually ready to leave.
MELVIN No.
MELVIN Wait.
MELVIN What?
MELVIN Why?
MELVIN I didn't mean it.
MELVIN You gotta sit down.
MELVIN You can still give me the dirty look...
MELVIN just sit down and give it to me.
CAROL Melvin, pay me a compliment...
CAROL I need one and quick...
CAROL You have no idea how much what you said just hurt my feelings.
MELVIN That monominute somebody gets that you need them they threaten to go away.
MELVIN Never fails.
CAROL That's not compliment, Melvin...
CAROL That's just trying to sound smart so I feel stupid...
CAROL A compliment is something nice about somebody else...
CAROL Now or never.
MELVIN Okay.
He waves her down.
CAROL And mean it...
MELVIN Can we order first?
She thinks and then nods.
The waiter is across the room.
This does not stop Melvin.
MELVIN Two crab dinners and pitcher of cold beer.
MELVIN Baked or fries?
CAROL Fries.
MELVIN One baked -- one fries.
STARTLED WAITER I'll tell your waiter.
MELVIN Okay, I got a real great compliment for you and it's true.
CAROL I am so afraid you're about to say something awful...
MELVIN Don't be pessimistic.
MELVIN It's not your style.
MELVIN Okay...
MELVIN Here I goes...
MELVIN Clearly a mistake.
MELVIN I have this -- what?
MELVIN Ailment...
MELVIN And my doctor -- a shrink...
MELVIN who I used to see all the time...
MELVIN he says 50 or 60 percent of the time a pill can really help.
MELVIN I hate pills.
MELVIN Very dangerous things, pills.
MELVIN "Hate," I am using the word "hate" about pills.
MELVIN My compliment is that when you came to my house that time and told me how you'd never -- well, you were there, you know...
MELVIN The next morning I started taking these pills.
CAROL I don't quite get how that's a compliment for me.
Amazing that something in Melvin rises to the occasion -- so that he uncharacteristically looks at her directly -- then:
MELVIN You make me want to be a better man.
Carol never expected the kind of praise which would so slip under her guard.
She stumbles a bit -- flattered, momentarily moved and his for the taking.
CAROL That's maybe the best compliment of my life.
MELVIN Then I've really overshot here 'cause I was aiming at just enough to keep you from walking out.
Carol laughs.
CAROL So how are you doing with those pills?
CAROL Well, I hopahopahopa.
MELVIN Takes months to know...
MELVIN They work little by little.
MELVIN Talking like this is exhausting.
Carol moves to the chair next to him...
She sits very close -- he tenses.
CAROL Have you ever let a romantic moment make you do something you know is stupid?
MELVIN Never.
CAROL Here's the trouble with never.
TIGHT SHOT for the kiss.
Their faces are close -- she looks at him...
She closes her eyes -- her face moving toward him -- he is wide-eyed and afraid...
His face almost moves away -- in a shot this close it's almost flight...
But now his head moves back and he receives her kiss.
It is brief.
Carol smiles encouragement to him and herself.
Melvin can't bear the pleasure.
MELVIN You don't owe me that.
CAROL That wasn't payment.
CAROL When you first came into breakfast, when I saw you -- I thought you were handsome...
CAROL Then, of course, you spoke...
CAROL So now that your soft li'l underbelly is all exposed.
CAROL Tell me, why did you bring me?
Melvin's voice is soft -- hesitant, okay, vulnerable...
as he holds up his hands in a "stop" signal.
MELVIN Well, ah...
MELVIN that's a personal question.
CAROL Tell me even if you're scared.
CAROL Tell me why you wanted me here.
CAROL It's okay.
She kisses him again.
CAROL If you ask me...
CAROL I'll say, "yes."
MELVIN There are lots of reason...
MELVIN I had a thought that if you had sex with Simon it might...
CAROL Sex with Simon?
MELVIN It's one idea...
CAROL That's why you brought me?
CAROL Look at me!
CAROL Is that really why you brought me...
CAROL Like I'm a what and I owe you what?!
MELVIN I don't know why I brought you -- that idea occurred to me is all...
MELVIN It came out first...
MELVIN Hey, you kiss him -- me...
MELVIN He says he loves you.
MELVIN You two hit it off.
MELVIN But you don't want to...
MELVIN fine...
MELVIN Forget what I said about sex with Simon.
MELVIN It was a mistake.
CAROL I'll never forget you said it.
MELVIN It was a mistake.
But she has already turned away and exits the restaurant...
Melvin alone and miserable.
He finishes dialing.
He is extremely tense -- not breathing -- a lump in his throat -- trying not to let the anxiety immobilize him...
the NUMBER RINGS twice, then a humorless male voice:
PARENTS' VOICE Hi.
PARENTS' VOICE This is Fred Bishop...
PARENTS' VOICE ...
PARENTS' VOICE and Betty.
PARENTS' VOICE We are sorry to be unable to take your call right now.
PARENTS' VOICE Please leave a message and we'd appreciate your including the time/date and purpose of your call.
PARENTS' VOICE (Simon mouths the word "date," then Betty speaks before the beep Bye-bye.
SIMON Ah, this is Simon...
SIMON I'm here in town...
SIMON ...
SIMON and, folks, you haven't come home later than 10 in your lives.
SIMON Please pick up -- really...
SIMON Okay...
SIMON I'm going to call again in the morning.
SIMON I need to see you.
SIMON Or, at least get you to answer the phone.
He hangs up.
His parents want no part of him and he needs help.
As Carol enters with some energy.
We FOLLOW her as she goes into her room -- takes her suitcase, begins throwing things in.
SIMON Hello...
SIMON Hello???
Carol thrusts open the door and enters...
SIMON Was this supposed to be your room?
CAROL Our room.
CAROL I don't want to see him and he's not going to come knocking on your door.
Simon struggles with his shirt -- she helps him, inadvertently venting some anger as she does so.
SIMON Can you not be violent?
CAROL I don't think so.
CAROL You need help with the pants?
SIMON No!!!
CAROL I'm going to take a big bath and order a big meal.
SIMON Uh-huh...
CAROL I'm sorry...
CAROL are you okay?
SIMON Well, considering everything's horrible and tomorrow I have to face my parents...
SIMON Don't ask me ...
SIMON I'm sick of my own complaints ...
SIMON got to get me a new set of thoughts.
CAROL Why?
CAROL What have you been thinking about?
SIMON How to die, mostly.
CAROL Can you believe in our little mix you're the good roommate.
Simon laughs -- as she crosses to the bathroom and begins to prepare a bath.
SIMON Good night.
CAROL Good night.
We are ON Simon settling in for sleep, when instinct or sounds or the faint glow of hope turns him so that he faces the bathroom and we have...
Carol sitting at tub's edge -- a towel around her and now as Simon looks at the bathing beauty she adjusts her hair -- the towel falls -- a better than perfect breast exposed...
SIMON Hold it.
He leaves the bed.
What's he up to...
he takes the blotter from the desk set and a pen from his jacket pocket which hangs on the chair and with vigor and faint pain moves to the other side of the bed where he turns on the light and stares at Carol.
SIMON I've got to sketch you.
CAROL No...
CAROL Absolutely not.
CAROL I'm shyer than you think.
CAROL I give the wrong impression sometimes and...
SIMON I haven't even been thinking about sketching for weeks.
CAROL Stop staring.
CAROL Do a vase.
SIMON But you're beautiful...
SIMON your skin glows.
CAROL Thanks.
CAROL But I just want to take a bath and...
SIMON That long neck -- the line of you...
SIMON you're porcelain...
SIMON your back goes on forever.
SIMON You're classic...
SIMON you're why cavemen chiseled on walls...
CAROL All right, cut me a break.
Simon's pen moves across the blotter -- Carol sees him earnestly engrossed, a beat of indecision and then shyly but deliberately she lowers the towel.
He's right.
She's breathtaking.
Melvin sits alone, nursing a drink.
He's been talking to the bartender.
MELVIN So then, the next thing I know, she's sitting right next to me, and then, well, it's not right to go into the details, but I screwed up.
MELVIN I got nervous.
MELVIN I said the wrong thing and if I hadn't, I could be in bed now with a woman who if you could make her smile you got a life.
MELVIN Instead, I'm here with you, no offense, a moron pushing the last legal drug.
He sits there, just another Joe on a bar stool with his heart breaking.
He's excited -- smiling...
We hear Carol -- also revved.
CAROL I don't care how you put it -- We're being naughty here, pal.
Carol holding a pose for Simon...
He is holding a ballpoint over the back of a hotel desk blotter.
His style cramped by his cast.
SIMON No.
SIMON No.
SIMON This is great, this is so great.
SIMON I can't get the angle with this cast.
He struggles with the cast, and then decides to struggle no more.
Summoning remarkable strength, he rips a piece from the cast, freeing his hand -- he roars ironically -- a lion's roar of liberation.
He is back at his center.
Melvin is having a room service breakfast.
The door opens...
Simon enters.
A new Simon -- better than ever, clearly happy -- a morning-after glow.
MELVIN Did you have sex with her?
Carol follows his out.
Her arms are filled with the hotel soaps, shampoos, etc.
MELVIN Sorry, didn't realize she was right there.
MELVIN Did you have sex with her?
CAROL To hell with sex.
Carol looks at Melvin -- he can't meet her gaze.
CAROL We held each other.
CAROL It was better than sex.
CAROL What I need he gave me great.
SIMON I just love her.
SIMON How're you doing?
Melvin reacts.
Simon finishes dialing the phone...
a brief wait, then:
SIMON Hello, hi, Mom -- I can barely hear you.
SIMON Do you have to whisper?
SIMON No -- don't apologize -- it was the luckiest thing for all of us that you didn't answer last night...
SIMON I can't hear you...
SIMON okay, dear, just listen to me then.
Melvin has been reduced to straight talk as Carol brings the bathroom bounty into the room and begins to put it in her suitcase.
MELVIN I get why you're angry.
MELVIN It's no snap to explain why I was like that, but let's not try to do it on the run...
SIMON ...
SIMON so Mom.
SIMON Truly no grudges -- truly.
SIMON A little odd that you didn't come to see me when you heard I was hurt, but the important thing I want you to know is your son is happy.
SIMON I'm working again.
SIMON I'll make do -- I don't want a thing.
SIMON Wouldn't take it if it was offered.
SIMON I'll drop you a note from wherever I land and then it's up to you.
SIMON I hope we patch things up but know that if we don't, I wish you both the very best...
SIMON I can't hear you.
SIMON You heard me, though, right?
SIMON Good -- take good care.
SIMON 'Bye.
He hangs up, totally satisfied with himself and rips over to Carol and Melvin.
MELVIN ...
MELVIN Now he's going to want to stay.
MELVIN And they'll want to take a ride to the lake or whatever.
MELVIN So it's a good five hours back.
MELVIN It gives us a chance to take it easy and...
SIMON I'm going back with you.
CAROL But what about...
SIMON I'll take care of myself --
MELVIN What are you talking about?
MELVIN You got real problems.
SIMON I know.
SIMON I'm a little bit nervous.
SIMON Suddenly everything seems so easy.
SIMON Carol, a load has been lifted.
CAROL One night with me!
SIMON You think you're kidding.
Melvin stalks out.
The car parked near a phone booth --
MELVIN Aww Jesus!
MELVIN No choice.
Carol walks up to Simon in the car.
CAROL I got a gift for you.
She hands him a base ball cap.
MELVIN Nothing like no choice to make you feel at home.
CAROL Let me see...
CAROL Ahh, gorgeous!
MELVIN Do it then.
MELVIN Get the dog picked up.
MELVIN I can't believe you let it stay there.
Melvin hangs up the phone.
MELVIN Good-bye.
MELVIN Well, your luck is holding.
MELVIN They sublet your place.
MELVIN You're homeless.
MELVIN Frank's got a line on another place you can use for now.
SIMON Another place where?
MELVIN Does it matter?
Melvin gets in -- goes to the glove compartment for a special CD labelled "For Emergency Use Only."
As it PLAYS a confessional love SONGS:
CAROL I don't want to hear that music right now.
MELVIN What do you mean?
MELVIN You said you liked it.
CAROL I don't.
MELVIN This one has a special meaning.
CAROL It's your car but I don't want to hear it.
CAROL If that means anything.
Melvin hesitates and then turns OFF the SONG in mid- proclamation of love.
As the car arrives...
They get out...
MELVIN Here are the keys to my apartment.
MELVIN I'm going to park you in my place while I take Carol home.
CAROL I'll take a bus.
MELVIN I'll take you...
MELVIN why not?
CAROL I don't care what you did for me.
CAROL I don't think I want to know you anymore -- all you do is make me feel badly about myself.
CAROL You have my number.
SIMON I love you...
SIMON Let him take you home.
CAROL Don't want to.
CAROL I love you.
She shakes her head and walks off.
Simon looking at Melvin with some sympathy.
MELVIN Don't say anything.
Where Verdell's ears prick.
As they enter.
MELVIN I told you to go on in.
SIMON Look, I've got to get a hold of Frank and see where I'm hanging my hat 'cause...
The door opens, revealing them:
MELVIN I think you gotta camp it here...
SIMON What are you talking about?
The dog vaults toward them -- all else forgotten as the dog greets his two favorite people and they talk to him.
SIMON I know the feeling -- you feel like your ol' self again, huh?
SIMON -- Mommy and Daddy are home.
Melvin reacts.
SIMON Sorry...
SIMON You're fun to mess with.
Melvin gets up...
Simon notices some of his paintings.
MELVIN They took your place furnished.
MELVIN Jackie said she grabbed your personal stuff -- they were supposed to set you up here.
MELVIN There's this extra room -- I never use.
MELVIN It gets good light.
MELVIN No other answer really.
Simon follows.
As they enter...
the room clean and organized -- a small but lovely garret.
SIMON Thank you, Melvin.
SIMON You overwhelm me.
MELVIN They did a nice job...
MELVIN Cozy, huh?
SIMON I love you.
Melvin looks at him finally -- pretensions fall.
MELVIN I'll tell you, buddy, I'd be the luckiest guy alive if that did it for me.
As Carol unpacks, she gives gifts to her mother and Spencer.
But clearly something gnaws at her psyche.
Melvin's two digital clocks are two minutes apart...
each around 1:55 a.m...
He sits in a chair still fully dressed...
forlorn...
Verdell in his lap.
A beat then we hear Simon's whispered voice.
SIMON Where is my big hairy boy?
Melvin is alarmed.
He stops breathing as his gay houseguest approaches.
SIMON Verdell, sweeties?
Melvin breathes again.
Simon enters the room.
SIMON Sorry, didn't know you were awake.
SIMON I just thought Verdell shouldn't get too used to sleeping in here 'cause then...
MELVIN Look, we both want the dog -- and...
The PHONE RINGS...
they look at each other.
Melvin doesn't move.
SIMON Should I get it?
Melvin nods.
Simon walks into the next room...
several beats as he finds the phone.
We hear him pick it up and:
SIMON Hello.
SIMON Hello.
SIMON It's me.
SIMON He took me in.
SIMON Did you know?
SIMON Hold on, I'll get him for you.
He walks back to Melvin's room.
As he enters.
SIMON It's Carol.
Melvin is quickly out of his chair -- the dog in one mitt...
he thrusts it at Simon.
MELVIN Here.
MELVIN Take the dog.
As he speeds him out...
SIMON Good luck.
As Melvin picks up the phone...
He clears his throat loudly.
Following is INTERCUT between Carol and Melvin -- the first such CUT showing Carol blasted by the throat clearing.
MELVIN Hello.
CAROL Yeah...
CAROL Well...
MELVIN How you doing?
CAROL I can trust my brain.
MELVIN That seems like a good choice.
CAROL I don't know whether I'm being sensible or hard on you.
MELVIN The two might go together.
CAROL See.
CAROL There's an example.
CAROL I don't know whether you're being cute or crazy now.
MELVIN Cute.
CAROL You don't have to answer everything I say.
CAROL Just listen to me.
CAROL Okay?
He nods his head, "yes."
CAROL It's really something that you're looking after Simon.
CAROL And what I said on the street.
CAROL That was a bad thing to say.
CAROL And it made me sick to my stomach.
CAROL It was a bad thing to say.
CAROL And I'd be lying if I didn't say that I enjoyed your company...
CAROL but the truth is you do bother me enormously and I know -- think -- that it's best for me to not have contact with you because you're just not ready and you're a pretty old guy to not be ready...
CAROL and I'm too old to ignore that.
CAROL But there were extraordinary kindnesses that did take place.
CAROL So thanks for the trips...
She's just broken up with him but she's being nicer than ever.
It's hard to know whether to die or not.
MELVIN Okay to say something now?
CAROL Go ahead.
MELVIN I should've danced with you.
CAROL Okay.
CAROL Good-bye.
MELVIN So long.
Carol hangs up.
She feels strange.
A shoe hasn't dropped.
Oh, hell...
she missed him.
Melvin walks in anxious circles in the living room.
He is impatient.
MELVIN You going to come talk to me or not?
SIMON I'm coming.
We enters the room carrying Verdell who strains to be allowed closer to Melvin.
Simon releases him.
SIMON What did she say?
MELVIN I'm a great guy -- "extraordinary"...
MELVIN ...
MELVIN and she doesn't want contact with me.
MELVIN I'm dying here.
SIMON Because...
SIMON ...
SIMON you love her?
MELVIN No...
MELVIN and you're supposed to be sensitive and sharp.
SIMON Okay...
SIMON you tell me why --
SIMON "You're dying here."
MELVIN I don't know...
MELVIN Let me sleep on it and figure it out.
MELVIN Because I'm stuck!
MELVIN Can't go back to what I had...
MELVIN She's evicted me from my life.
SIMON Did you like it that much?
MELVIN It was better than this...
MELVIN Look, you, I'm very intelligent.
MELVIN If you're going to give me advice or conversation or consolation or hope, you got to be better than you're doing.
MELVIN If you can't be at least momentarily interesting than shut the hell up.
MELVIN I'm drowning and you're describing water.
SIMON Picking on me won't help.
MELVIN Well, if that's true then I'm really in trouble.
SIMON But you know where you're lucky?
MELVIN Absolutely not.
SIMON You know who you want.
SIMON I'll take your seat any day.
SIMON So do something...
SIMON don't sleep on it...
SIMON go over there.
SIMON I don't think anybody should ever sleep on anything -- it's not always good to let things calm down.
MELVIN Hey...
MELVIN I'm charged here.
MELVIN But she might kill me for showing up this late.
SIMON Then get in your jammies and I'll read you a story...
SIMON I think you've got a chance.
SIMON The only real enemy you have is her ability to think logically -- the best thing you have going for you is your willingness to humiliate yourself if it gives you one chance in whatever -- so go catch her off- guard.
MELVIN Okay.
MELVIN Thanks a lot.
MELVIN Here I go.
He moves for the door...
stops suddenly, jolted.
SIMON What's wrong?
MELVIN I forgot to lock the door.
As he parks.
He exits the car -- now wary...
looks at his watch...
hesitates...
walks reluctantly into the apartment house.
As Melvin looks at Carol's doorbell with great uncertainty.
Carol in a cotton wrap-around dress/bathrobe...
sitting directly in front of a fan...
the windows open, reading one of Melvin's books...
There is the briefest possible sound of a DOORBELL...
someone has jabbed her downstairs button ever so briefly -- so briefly that she's not certain it's her DOORBELL -- until the same brief sound REPEATED...
She walks to her wide open window and looks over.
The convertible at the curb.
She hesitates --
As Melvin gives up and starts out...
turning as the sudden blast of being BUZZED into Carol's life sounds.
He bolts for the door and enters.
She opens the door...
she hears the sound of MELVIN SOUNDING HEAVILY up the stairs...
He reaches her side.
CAROL What do you want, Melvin?
MELVIN Were you asleep?
CAROL What do you want?
MELVIN 'Cause if you were asleep -- I'm sorry.
MELVIN And you could be grouchy.
CAROL Grouchy?
MELVIN ...
MELVIN 'Cause of being woken up, and it would make my job impossible.
MELVIN So then I wouldn't even try.
CAROL What job?
MELVIN Were you asleep?
CAROL What are you doing here?
Beverly in the hallway looking on --
MELVIN I'm sorry I woke you -- some other time.
He half turns to leave.
CAROL I wasn't asleep!!
MELVIN What a break...
CAROL Is it a secret what you're doing here?
MELVIN I had to see you...
CAROL Because...
MELVIN It relaxes me...
MELVIN I'd feel better just sitting on the curb in front of your house than anyplace else I can think of or imagine.
Carol has not ever heard anything like that before...
it's sort of sexy in its sincerity.
As we see in the b.g.
that Beverly, standing near her door down the hallway, has heard at least this last part...
Melvin, of course, cannot leave well enough alone...
MELVIN Wait a minute, I'm overstating here, maybe the inside stairs.
MELVIN I don't want to sit with my feet in the gutter.
MELVIN What does that serve?
MELVIN It only...
But suddenly Carl is shouting to the heavens.
CAROL Stop it!!
CAROL Why can't I have a normal boyfriend???
CAROL Why?
CAROL Get out of here.
CAROL Just a regular boyfriend who doesn't go nuts on me...
BEVERLY Everybody wants that, dear -- it doesn't exit...
BEVERLY Sorry...
BEVERLY didn't mean to interrupt.
She disappears into her room.
Carol snorts a laugh -- gathers herself.
A beat.
MELVIN Boyfriend?
CAROL Oh, come on in and try not to ruin everything by being you.
MELVIN Maybe we could live without the wise cracks.
She looks at him -- then:
CAROL Maybe we could...
Melvin glances at the cracked pattern of Carol's kitchen linoleum and stalls at the door.
MELVIN It feels a little confined here.
MELVIN Let's take a walk.
CAROL See.
CAROL It's four in the morning.
CAROL A walk sounds a little screwy to me, if you don't mind.
MELVIN If you need an excuse, there's a bakery on the corner.
MELVIN There's a shot it'll open soon -- that way we're not screwy -- we're just two people who like warm rolls.
CAROL Okay.
They walk quietly -- Melvin still walking with his usual attention to where he steps.
Melvin walking -- and though we can see an improvement -- it is still decidedly strange as he conspicuously avoids stepping on the lines.
Carol sighs.
It is the sound of possibilities crashing down.
Melvin looks at her -- embarrassed, self-conscious -- his habits making him appear unworthy.
CAROL I'm sorry, Melvin -- but whatever this is -- is not going to work.
He takes this hard.
It forces him to half-whisper something he hasn't at all said to himself...
given his history...
this is an extraordinary intimacy.
MELVIN I'm feeling...
MELVIN I've been feeling better.
CAROL Melvin, even though it may seem that way now -- you don't know me all that well...
CAROL I'm not the answer for you.
She starts to turn.
He tugs at her arm.
As she turns back to him.
MELVIN Hey, I've got a great compliment for you.
CAROL You know what?
CAROL I...
MELVIN Just let me talk.
MELVIN I'm the only one on the face of the earth who realizes that you're the greatest woman on earth.
MELVIN I'm the only one who appreciates how amazing you are in every single thing you do -- in every single thought you have...
MELVIN in how you are with Spencer -- Spence...
MELVIN ...
MELVIN in how you say what you mean and how you almost always mean something that's all about being straight and good...
She stands on the precipice of being transported away from the logic which has been her lifeline.
MELVIN I think most people miss that about you and I watch wondering how they can watch you bring them food and clear their dishes and never get that they have just met the greatest woman alive...
MELVIN And the fact that I get it makes me feel great...
MELVIN about me!
MELVIN You got a real good reason to walk out on that?
That last question clearly a true question, not the least rhetorical -- she considers her answer, then:
CAROL No!
CAROL It's certainly not.
CAROL No -- I don't think so.
CAROL No.
MELVIN I'm gonna grab you.
MELVIN I didn't mean it to be a question.
MELVIN I'm gonna grab you.
He kisses her.
An awkward bomb of a kiss.
They separate.
A tense beat.
Then:
MELVIN I know I can do better.
They embrace again.
He does indeed do much better.
A first-class smooch.
CAMERA MOVES DOWN to see his foot land squarely on a crack in the sidewalk without his knowledge.
They break -- look at each other without a notion of where to take it from here, and the ALMOST in unison begin to walk away FROM CAMERA, Melvin following a path that avoids cracks.
Suddenly the lights of the bakery turn on as it opens for business.
CAROL Warm rolls...
They walk to the bakery, Melvin avoiding the cracks.
As they enter the bakery, a WORKER moves toward them to clean the entranceway.
Melvin, forced to step back onto a crack, this time notices -- registers the momentous fact and joins Carol inside as we:
</pre> </pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
