<script> <script>
<!-- if (window!= top) top.location.href=location.href
</script> <TITLE>There's Something About Mary - by Ed Decter &amp; John J. Strauss and Peter Farrelly &amp; Bobby Farrelly</TITLE>
<PRE><FONT SIZE="+2"><U>There's Something About Mary
</U></FONT>Screenplay by
Ed Decter &amp; John J. Strauss
and
Peter Farrelly &amp; Bobby Farrelly
Story by Ed Decter &amp; John J. Strauss
It's the early 1980's and everyone is arriving at school.
We push through the parking lot crowd to a nervous, lanky kid, TED
MAN'S VOICE (V.O.) When I was sixteen years old I fell in love...
<U>CLOSE ON</U> - RENISE, a tough girl with stringy brown hair and a shiny forehead, as she turns toward the camera.
TED Hey, Renise.
She barely looks at him as he approaches, just drags on her smoke.
RENISE Hey.
TED So what's up?
RENISE Eh.
TED Great.
TED Great.
TED So listen, uh, I was wondering if maybe you wanted to go to the prom you know, with me.
Renise looks unenthused.
TED (cont'd) It's no big deal, whatever I mean, if you want.
RENISE See, the thing is, I heard a rumor that this guy I like was gonna ask me.
TED Uh-huh.
RENISE Yeah, so...I'm gonna wait and see what happens there...But that sounds great, yeah.
Ted nods, confused.
TED Okay.
TED So is that a yes or a no?
RENISE I think I was very clear, Ted.
RENISE If everything else falls apart, maybe.
Renise throws down her butt and storms off.
TED I'm gonna hold you to that.
<U>ANGLE ON</U> - a pretty girl, MARY, climbing off a ten-speed in the school parking lot.
She's athletic and tanned and doesn't have a bad bone in her body.
MAN'S VOICE (V.O.) Her name was Mary.
MAN'S VOICE (V.O.) She'd moved to our little Rhode Island town from Minnesota two years earlier.
She locks up the bike and starts walking toward the school.
MAN'S VOICE (V.O.) Mary was very smart, and very cool, and she had a faceful of eyes that promised you a better life if you could only know her.
As she approaches the camera, we PAN to see Ted watching her.
He's sitting on a picnic table with two FRIENDS.
FRIEND #1 Hey, dirtbud, who you going to the prom with?
Finally Ted takes his eyes off Mary.
TED Ah, I don't know if I'm even gonna.
TED You know, not my style.
FRIEND #2 You have a style?
FRIEND #1 Why don't you be a gentleman and ask Rosey?
TED Who?
Friend #1 makes a jerk-off motion.
FRIEND #1 Rosey Palm, your girlfriend.
FRIEND #1 God knows you spend enough fucking time with her.
The guys LAUGH.
TED Yeah, and who are you gonna take, your own palm?
His friends stare at him.
FRIEND #1 Clever.
FRIEND #1 I like the way you just spun that around on me.
Friend #2 notices Mary talking to her FRIENDS.
FRIEND #2 I wonder who she's going with.
FRIEND #1 Some guy named Woogie.
TED Who?
FRIEND #1 Big guy--goes to Barrington high school.
This irks Ted.
TED Woogie from Borrington high?
TED Sounds like a loser.
FRIEND #1 Loser?
FRIEND #1 Woogie was all-state football and and basketball and valedictorian of his class.
FRIEND #2 I heard he got a scholarship to Princeton but he's going to Europe first to model.
This takes the wind out of Ted's sails.
FRIEND #3 Yeah and he's got a huge cock.
Everyone looks at him.
FRIEND #3 (cont'd) I heard.
Suddenly Friend #1 NOTICES something.
FRIEND #1 Hey, check it out.
<U>THEIR POV</U> - A large, goofy YOUNG MAN with an unfashionable crewcut comes walking up the street.
He's in his early twenties and though the weather is mild he's WEARING EARMUFFS.
He approaches a GROUP OF KIDS sitting on a car hood.
EAR-MUFF GUY You seen my baseball?
CAR HOOD KID #2 No.
The kids watch as the Ear-Muff Guy approaches another group.
EAR-MUFF GUY You seen my baseball?
This guy must be in the 'tard squad.
Hey, buddy, come here, I think I know where your ball is.
The Ear-Muff Guy heads back to the car.
EAR-MUFF GUY You seen my baseball?
CAR HOOD KID #1 Yeah, I seen it.
CAR HOOD KID #1 That girl over there, she has it.
Car Hood Kid #1 points to a BUSTY GIRL leaning against another car talking to her large BOYFRIEND.
CAR HOOD KID #2 (cont'd) 'Cept she doesn't call it a baseball.
CAR HOOD KID #2 (cont'd) She has another name for it...
<U>ON BUSTY GIRL</U> - The Ear-Muff Guy marches up to her and her boyfriend.
EAR-MUFF GUY You seen my pecker?
GIRL What?!
EAR-MUFF GUY You seen my pecker?
The Boyfriend grabs him by the collar.
BOYFRIEND You son-of-a-bitch, I'll kick your ass!
The Boyfriend throws the Ear-Muff Guy to the ground and is about to pummel him when Ted intervenes.
TED Take it easy, Smokey.
BOYFRIEND/SMOKEY This fucking pervert just came on to Nance!
TED All right, just be cool.
TED He looks like he's not all there, you know what I mean?
A crowd starts to gather which only incites Smokey more.
BOYFRIEND/SMOKEY Get the fuck out of my way, man!
Smokey tosses Ted out of the way and moves toward the Ear-Muff Guy.
Just then Mary shows up and steps between them.
MARY What's going on here?
She bends down and helps the Ear-Muff Guy off the ground.
MARY (cont'd) Are you all right?
EAR-MUFF GUY Mary, you seen my baseball?
MARY No, I haven't seen your baseball.
MARY Jeez, Warren, you know you're not supposed to leave the yard by yourself.
BOYFRIEND/SMOKEY You know him?
MARY He's my brother.
BOYFRIEND/SMOKEY Oh.
BOYFRIEND/SMOKEY I didn't realize he was...you know...
At this, Smokey and his girlfriend reluctantly head toward the school, along with most of the crowd.
Mary turns her attention in the direction Ted was thrown.
MARY You okay?
<U>HER POV</U> - Ted is sitting in a mud puddle.
He stands and brushes himself off.
TED Oh yeah.
TED Fine.
MARY Thanks a lot, Ted.
<U>CLOSE ON</U> - Ted.
He can't believe what he's just heard.
As Mary helps him up, she turns her attention to Warren.
MAN'S VOICE (V.O.) That she knew my name blew my mind.
MAN'S VOICE (V.O.) Some of my best friends didn't know my name.
Mary and a muddied Ted are walking Warren home.
Warren lags behind, mumbling to himself.
Mary notices that Ted is limping.
MARY Hey, you're limping.
MARY Did you just hurt yourself?
TED No, it's an old football injury.
MARY Oh, are you on the team?
TED No, a couple of the players and me were joking around and, uh, I fell off the school.
Warren approaches and motions for Ted to hop on his back.
WARREN Piggyback ride?
MARY Warren, come on, leave Ted alone.
Warren pats his back again.
WARREN Piggyback ride.
TED I don't mind.
TED If you think he can hold me.
MARY Oh he can hold you.
MARY He weighs two-hundred-and-thirty pounds.
TED A real Clydesdale, huh Warren?
Ted hops onto Warren's back.
TED (cont'd) Giddy-up.
Warren walks about five feet and stops.
WARREN My turn now.
Off Ted's reaction, we
Muddy sweat is running down Ted's face as he struggles up a hill with Warren on his back.
TED We're here, Warren.
TED You wanna get off?
WARREN Giddy-up.
Ted rolls his eyes and continues toward the front door.
Mary looks on, amused.
MARY So who you taking to the prom?
TED Huh?
MARY The prom--you going?
TED Oh, I don't know.
TED I think proms are pretty dumb.
MARY 'Cause I thought maybe you and I could go if you weren't already taking someone.
TED I mean dumb in the sense that they only happen once a year.
She smiles at this.
MAN'S VOICE (V.O.) From that moment on the guys at school looked at me in a whole new light.
You're a fucking liar!
<U>PULLBACK TO REVEAL</U> - Ted is leaning against his locker surrounded by a group of guys.
FRIEND #2 You expect us to believe you're going to the prom with Mary?
FRIEND #2 What about Woogie?
TED They broke up.
TED She said he started getting weird on her.
FRIEND #1 I got twenty bucks says you're full of shit.
TED Oh come on, why would I lie?
FRIEND #1 Because you're a loser, and in some warped way this gives you a momentary sense of worth.
FRIEND #2 Put me down for fifty.
FRIEND #3 I'm in.
As the others join in, we
A tuxedoed and smiling Ted drives up in his parent's station wagon.
Ted knocks on the door and Mary's gruff DAD answers.
MARY'S DAD Yeah?
MARY'S DAD What do you want?
TED Um, hi, I'm Ted Peloquin.
TED I'm here to take Mary to the prom.
MARY'S DAD Prom?
MARY'S DAD You're about twenty minutes late.
MARY'S DAD She just left for the prom with her boyfriend Woogie.
Ted looks devastated.
Suddenly the door swings open revealing
MARY'S MOM Charlie, that's mean.
MARY'S MOM Come on in, Ted.
MARY'S MOM Don't listen to Mr. Wise Guy here.
MARY'S MOM He's a joke a minute.
TED Oh.
TED Oh, that's a good one.
Ted nervously enters and sees Warren watching T.V. in the den.
TED Hey, Warren.
Warren doesn't look his way.
Just then Mary comes down the stairs looking as if the directors had really taken their time casting this role.
Ted can't believe his eyes.
MARY Hi, Ted.
TED Hi, Mary.
MARY'S MOM Poor Teddy--he's been getting it both barrels from the Wisenheimer here.
MARY Dad, have you been busting Ted's chops?
Mary's Dad shrugs.
MARY (cont'd) Warren, did you say hi to Ted?
WARREN 'Bout ten times.
TED Hey, Warren, I think I know where your baseball is.
This finally gets Warren's attention.
WARREN You seen my baseball?
We see Ted discreetly pull a BRAND NEW BASEBALL out of his pocket and palm it in his hand.
TED Well, if it's a big white one with red stitching, I think I saw it right behind your ear ..
Ted is reaching behind Warren's ear when suddenly Warren TAKES A SWIPE AT HIM, knocking him to the ground.
MARY Warren!!!
Ted HITS HIS HEAD on the coffee table.
<U>ON THE BASEBALL</U> - as it rolls under the couch, stopping right next to the OTHER MISSING BALL.
<U>BACK TO SCENE</U> - In a split second, Warren is up like a cat and DIVES ONTO TED.
As MARY AND HER PARENTS SCREAM, Ted manages to free himself from the disabled man's clutches and GETS WARREN IN A
MARY'S DAD What the hell are you doing?!
MARY'S MOM Teddy, let him go!
TED I'm trying...tell him to...calm down.
The family jumps on Warren and finally break it up.
MARY'S DAD (cont'd) Jesus Christ, guy, what the hell were you doing?!
TED I was playing a trick.
TED I-I-I had a baseball.
MARY'S MOM What baseball?
MARY'S MOM Where's a baseball?
Ted looks around but there's no ball in sight.
TED There was a ball I had a honest.
As Mary helps Ted up, we see that his shirttail is out and his tie is hanging off.
Mary's parents lead the frothing Warren back to the couch.
MARY (to Ted) I'm sorry.
MARY (to Ted) I should've told you, he's got a thing about his ears.
TED Oh.
TED Okay.
TED I gotcha.
MARY Are you all right?
TED Oh yeah.
MARY'S MOM Honey, now you're all wrinkled.
Mary looks down and frowns.
MARY Ted, will you just give me one more minute?
MARY I have to iron this thing.
Ted starts to tuck his pants in as Mary and her mother head back up the stairs.
Mary's Dad and Ted are left alone.
And Warren.
Ted rubs his head, sees a spot of blood.
TED May I use your bathroom?
Ted dabs his head with a tissue, then moves to the toilet.
As he TAKES A LEAK he glances out the window to his left.
<U>TED'S POV</U> - two LOVEBIRDS are perched on a branch.
Ted smiles...
...at the SOUND of these beautiful tweeties singing their love song for themselves, for the spring, for Ted and Mary, and suddenly they fly away and we...
</U>...to reveal Mary in the bedroom window DIRECTLY BEHIND WHERE THE BIRDS WERE, in just a bra and panties, and just then her mother glances Ted's way and MAKES EYE-CONTACT with what she can only presume to be a leering Peeping Tom.
...he loses the smile and ducks his head back into the bathroom,
PANICKING NOW, he hastily zips up his fly and
A concerned Mary, her Mom, Dad, and Warren are huddled outside the bathroom.
MARY Ted, are you okay?
TED Just a minute.
MARY'S MOM He's been in there over half an hour.
MARY'S MOM Charlie, I think he's masturbating.
MARY Mom!
MARY'S MOM Well he was watching you undress with a silly grin on his face.
TED I was watching the birds!
They all look at one another.
MARY'S MOM Charlie, do something.
MARY'S DAD All right, kid, that's it, I'm coming in.
A whimpering Ted huddles in the corner as Mary's Dad enters.
MARY'S DAD (cont'd) What seems to be the situation here?
MARY'S DAD (cont'd) You shit yourself or something?
TED I wish.
Ted motions for him to close the door and Mary's Dad obliges.
TED (cont'd) I, uh...I got it stuck.
MARY'S DAD You got what stuck?
TED It.
MARY'S DAD It?
MARY'S DAD Oh <U>it</U>.
MARY'S DAD All right, these things happen, let me have a look.
MARY'S DAD It's not the end of the world.
Mary's Dad moves closer and puts his reading glasses on.
As Mary, her Mom, and Warren listen in...
TED Shhhhhh!
MARY'S DAD Shirley, get in here!
MARY'S DAD You gotta see this!
TED What?!
TED No please, sir--
MARY'S DAD She's a dental hygienist.
MARY'S DAD She'll know what to do.
Mary's Mom comes in and closes the door behind her.
MARY'S MOM Teddy, hon, are you okay?
TED Would you shhh!
TED Mary's gonna hear us.
MARY'S MOM Just relax, dear.
MARY'S MOM Now, um...what exactly are we looking at here?
TED What do you mean?
MARY'S MOM I mean is it...is it...?
MARY'S DAD Is it the frank or the beans?
TED I think a little of both.
Suddenly we hear Warren from outside the door:
WARREN Franks and beans!
Ted hangs his head.
Mary and Warren are huddled outside the door.
MARY Shhhh.
MARY'S DAD What the hell's that bubble?
Mary REACTS to this.
TED One guess.
MARY'S DAD How the hell'd you get the beans all the way up top like that?
TED I don't know.
TED It's not like it was a well thought-out plan.
MARY'S MOM Oh my, there sure is a lot of skin coming through there.
MARY'S DAD I'm guessing that's what the soprano shriek was about, pumpkin.
MARY'S MOM I'm going to get some Bactine.
TED No, please!
Suddenly a POLICE OFFICER sticks his head in the bathroom window.
POLICE OFFICER Ho there.
TED Oh God.
POLICE OFFICER Everything okay here?
POLICE OFFICER Neighbors said they heard a lady scream.
MARY'S DAD You're looking at him.
MARY'S DAD C'mere and take a look at this beauty.
TED No, that's really unneces--
But the Officer's already climbing in the window.
Once inside, he turns his flashlight on Ted and WHISTLES.
POLICE OFFICER Now I've seen it all.
POLICE OFFICER What the hell were you thinking?
TED I wasn't trying--
POLICE OFFICER Is that bubble what I think it is?
Mary's parents nod.
POLICE OFFICER (cont'd) But...how...how'd you get the zipper all the way to the top?
MARY'S DAD Let's just say the kid's limber.
The Officer makes a face, then rolls up his sleeves.
POLICE OFFICER Well, there's only one thing to do.
TED No, no, no, I'll be fine.
TED I'll just hang my shirttail out and work on it in the morning.
POLICE OFFICER Look, son, this'll only hurt for a second.
The Officer reaches down and takes hold of the zipper.
TED No, no, please!
MARY'S MOM Teddy, be brave.
WARREN Beans and franks!
MARY Warren, <U>shhh</U>.
Defeated, Ted holds his breath and braces for the worst.
POLICE OFFICER It's just like pulling off a Band-aid.
POLICE OFFICER A-one and a-two and...
PARAMEDIC We got a bleeder!
TWO PARAMEDICS rush Ted out the front door on a stretcher.
Mary runs alongside him holding a towel on his crotch.
while a THIRD PARAMEDIC dabs at his crotch with a towel.
Mary's Mom and Dad are out front along with two FIRETRUCKS, four POLICE CARS, and a crowd of about thirty NEIGHBORS.
PARAMEDIC Keep pressure on it!
Mary does as she's told.
MARY Ted, I'm so sorry.
MARY Are you going to be okay?
TED You betcha!
He gives her two thumbs up as they slide him into the ambulance.
The doors SLAM shut and as the ambulance pulls away Ted starts to WHIMPER and we can see Mary fade into the night, as we
Ted, now in his 30's, lays on his therapist's couch.
TED ...Anyway, school ended a few days later and that July her father got transferred to Florida.
The <U>CAMERA PANS</U> up to reveal that the CHAIR BEHIND HIM IS EMPTY.
<U>Ted has been telling all this to no one</U>.
TED (cont'd) It took me half the summer to pay off all those bets.
TED (cont'd) I never did see Mary again.
TED (cont'd) That was about twelve years ago.
Just then the door quietly opens and Ted's PSYCHIATRIST tip-toes back into the room and takes his seat.
(He has a dab of mustard on his chin and has forgotten about the cloth napkin tucked into his collar.)
PSYCHIATRIST Uh-huh.
PSYCHIATRIST Interesting.
The Psychiatrist notices the napkin and quickly wipes his chin, then tosses it aside.
TED Anyway, it's not something you exactly forget about, but I guess I must've blocked it out of my head.
TED Then about a week ago I'm driving on the highway and I got to thinking about Mary and suddenly I couldn't breathe...I couldn't keep up with the flow of traffic anymore I felt like I was going to die.
TED I pulled into a rest area, parked the car, and just started shaking.
The Psychiatrist scratches his chin.
PSYCHIATRIST You know...rest areas are homosexual hang-outs.
TED Huh?
PSYCHIATRIST Highway rest areas--they're the bathhouses of the nineties for some gay men.
Ted thinks about this, then glances back at the shrink.
TED What are you saying?
PSYCHIATRIST Oops, time's up.
PSYCHIATRIST We'll have to delve into that next week.
Off Ted's look, we
Ted and his friend DOM are blasting a couple buckets.
DOM Gay?
DOM He said you were gay?
TED He implied it.
DOM Well you're a writer, and a lot of writers are gay.
DOM Look at Truman Capote.
TED Yeah, but he was successful.
DOM Let me ask you this: When you smoke a cigar, do you ever pretend it has balls?
Ted appears to think about this.
TED Come on, that wouldn't make me gay.
DOM I'm going to fix you up with my new assistant.
TED What's he like?
Dom LAUGHS, then watches as Ted hits a ball.
DOM You're leaving it out.
DOM Finish your swing.
DOM You're going to like this one--she's half Asian, half American.
TED Good-looking?
DOM I just told you, <U>she's half Asian.
DOM half
</U> <U>American</U>.
They're all good looking.
You could mate Don Rickles and Yoko Ono and they're going to have a gorgeous kid.
It's a foolproof combo.
Ted thinks about it.
TED What's the point?
TED Let's face it, Dom, I'm in a slump.
TED Lately I've been feeling like...well...like a loser.
DOM Loser?
DOM You?
Ted shrugs.
DOM (cont'd) Give me a break.
DOM (cont'd) Remember five years ago, when your kidneys failed?
DOM (cont'd) If you were a loser would they have been able to find a donor with an exact tissue match?
DOM (cont'd) What are the odds of that, one in a million?
TED Oh, so I'm lucky because my brother got killed in an explosion?
DOM I never said that.
DOM I'm saying your lucky those kids found his kidneys.
DOM Besides, your brother Jimmy never gave a shit about you.
Ted gives him a look.
DOM (cont'd) You know, you're a real glass-is-half-empty guy.
DOM (cont'd) You got a fucking guardian angel, man.
Ted manages a small smile.
Just then, Ted's cell phone RINGS.
TED I gotta take this, it might be my boss.
TED Ted here.
GARBLED VOICE You're a cocksucking motherfucking piece of puke!
Whoever it is HANGS UP.
Without reacting, Ted closes the phone and puts it back in his pocket.
TED Yep.
Dom and Ted are drinking beer while sitting on Dom's front steps.
We see signs of kids everywhere: a tricycle, six-foot basketball hoop, dolls, etc.
DOM'S WIFE comes out and hands them each a cigar.
DOM'S WIFE I thought you guys might like these with your beers.
DOM Thanks, baby.
She goes back inside.
TED See, that's what I want.
TED I don't need these bimbettes you got me chasing.
TED I want what you have.
TED A family....Someone to...you know...love.
These guys don't usually talk about this crap, and Ted gets a little embarrassed.
TED (cont'd) It must be great with a wife like that.
DOM Each day is better than the next.
DOM Have you ever been, you know...in love with someone?
TED Nah.
DOM Never?
TED Well once.
TED Mary.
Dom SIGHS.
DOM Mary again.
TED Look, I admit it was brief, but it was definitely love.
TED Crushes don't last twelve years.
DOM Whatever happened to Mary?
TED I told you, her family moved to Miami.
DOM I mean since then.
TED I don't know.
DOM Well why don't you look her up?
TED Yeah, right.
DOM Why not?
TED Because I guarantee she's married and has a couple kids.
TED Girls like Mary don't stay single.
DOM What if you're wrong?
DOM You just said she's the only girl you ever loved, what have you got to lose by calling her?
TED I did try calling her.
TED A few years ago.
TED She wasn't listed.
DOM So that was it?
DOM One bump in the road and you gave up?
TED I also called <U>Unsolved Mysteries</U>.
DOM You're kidding?
DOM What did they say?
TED They told me they don't help out stalkers.
TED Look, maybe they're right, it's been a long time.
DOM I got it--you hire a private eye, fly him out there, he follows her around a couple days, she'll never know a thing.
Ted considers this.
TED No.
TED No fucking way.
TED That's too creepy.
Dom thinks a moment, then SNAPS his fingers.
DOM Wait a second.
DOM There's a guy named Healy in my office who might be able to help you out.
DOM He's a claims investigator and he goes to Miami every couple weeks.
As Ted thinks about this, we
<U>ESTABLISHING SHOT</U> of a big insurance company - MORNING
Ted and Dom are walking down a hallway.
TED I don't know about this, Dom.
DOM Relax, this guy owes me a big one.
DOM A couple years ago he got in a jam up in the Boston office; some bullshit about padding his resume--like we haven't all done that.
DOM Anyway, they were going to let him go but his mother wrote a tear-jerker letter that ended up on my desk.
TED His mother?
DOM Yeah, I guess he still lives with her.
DOM Seemed like a sweet lady--got diabetes or something--so I went out on a limb and got him transferred down to Providence.
TED And you think he could find out her number for me?
DOM He'll do better than that.
DOM I'll send him down to Miami on business, you throw him a couple bucks on the side, and he'll track her down.
Ted thinks about this.
DOM (cont'd) Just let me warn you--This guy runs a little hot, but he gets the job done.
Ted is seated inside a small cubicle across the desk from PATRICK HEALY, a shaggy-looking guy in a mis-matched three-piece suit.
Healy looks more like a used-car salesman than an insurance investigator.
HEALY So, Dom tells me you're looking for some lady-friend you knew in high school.
TED Uh-huh.
HEALY Any idea where I might start looking?
TED She moved to Miami Beach twelve years ago.
TED I checked directory assistance down there and she's not listed.
TED She might've moved ten times since then.
HEALY All you want is a phone number?
TED Well, I know you're busy
HEALY Don't play games with me, Ted.
TED I don't know, maybe you could poke around for a half day and see if she has five kids and a Labrador.
HEALY I don't buy it.
TED You don't buy what?
Suddenly Healy is in his face.
HEALY Ted, I'm the kind of guy who shoots from
the hip.
Now I want you to level with me: Did you knock this skirt up?
TED No.
HEALY She's blackmailing you, right?
TED <U>No.
You want her dead, don't you?
TED You can't be serious.
HEALY Do you really expect me to believe this is a straight stalker case?
TED I'm not a stalker !
TED She's a friend of mine.
HEALY Sure she is.
HEALY That's why she got an unlisted number and you haven't heard squat from her in a dozen years.
HEALY Oh you're good, Ted.
HEALY You're a real piece of work.
TED Look, let's forget it.
TED Let's forget the whole thing.
HEALY I get one hundred a day plus expenses.
TED You get fifty a day, period.
TED It's a business trip, they'll pay for your expenses.
Healy thinks about it.
HEALY Okay, Ted, I'll do it.
HEALY But if this chick turns up with a toe tag, I'm rolling over on you.
<U>ESTABLISHING SHOT</U> - of Miami Beach
Healy waits alone on a corner carrying one bag and a RACK OF BEERS.
Suddenly a '89 Chrysler Lebaron convertible with a GREAT DANE in the back SCREECHES to a halt in front of him.
The driver, SULLY, is a muscular, well-groomed man in his thirties.
SULLY Healy you dog!
HEALY Fucking Sully!
HEALY Look at you!
SULLY You hot shit.
SULLY Ya look fuckin' pisser.
The dog is catching wind in the backseat and Sully hands Healy a packet.
SULLY Here's the info you asked for.
HEALY Thanks.
SULLY You should thank me--that girl was not easy to find.
SULLY What'd she scam you out of-some insurance dough?
HEALY Nah, some guy threw me a few bucks to track down his high school girlfriend.
SULLY Stalker, huh?
HEALY Big time.
This place is modest and clean but it has a direct view of South Beach.
Healy puts his bags down and looks around.
HEALY Very nice.
SULLY I'm doing okay.
SULLY I gotta get ready for work.
Sully ducks into the bedroom and Healy looks around the apartment.
HEALY Okay?
HEALY With this pad, the killer wheels?
HEALY Looks like you really cleaned up your act.
SULLY What can I tell you?
SULLY It's a healthier lifestyle down here, and it's easier to succeed when your head's clear.
SULLY Those guys I worked with back in Boston, they were a bad influence.
HEALY Fuckin' animals.
HEALY Hey, what do you say we go grab a couple drinks.
SULLY Not for me, buddy.
SULLY I don't drink anymore.
HEALY Yeah, and you don't drink any less, right?
Suddenly a huge Boa Constrictor slithers up on Healy's lap.
HEALY (cont'd) What the...?!
Sully comes back in the room wearing a police uniform.
SULLY Take it easy, that's Bill.
HEALY Tell Bill to get the fuck off!
SULLY Relax, he just ate.
Healy just stares at his friend.
SULLY (cont'd) Nineteen months I been sober.
HEALY What are you talking about?
HEALY You were never an alky, you were a cokehead.
SULLY Yeah, well when you quit blow, you gotta quit the booze, too.
HEALY Is that right?
HEALY Well good for you, Sull, I'm proud of you.
Healy pops open one of his beers and hands it to Sully.
HEALY (cont'd) Here, just have one of these then.
SULLY Healy, what I just tell you?
HEALY This is a light beer.
HEALY You can't have a light beer?
SULLY No I can't.
Healy stares at him, baffled.
HEALY Sully, it's one fuckin' beer for Christ sakes.
HEALY Ooh, the big bad beer's gonna get ya.
Sully stares at the beer, weakening.
HEALY (cont'd) I'm worried about you, man.
HEALY (cont'd) You better learn to have a pop once in a while or you're gonna fall off the wagon.
HEALY (cont'd) You're being a fanatic and that ain't healthy.
SULLY Am I?
HEALY Bet your ass you are.
HEALY Now I don't want to hear anymore of your happy horseshit.
HEALY You gotta learn how to bend a little or believe me...you're gonna break.
Finally, Sully takes the beer.
He stares at it a moment and then sips.
SULLY Jesus, you know what?
SULLY This shit doesn't even taste good to me anymore.
HEALY Ah, fuck ya then, you big pussy.
HEALY What are you, spotting?
Healy takes the beer from Sully and as he chugs it, we
Healy is on a stakeout.
He's dozing.
He's been here for hours, food wrappers litter Sully's car.
He's wearing Walkman-type HEADPHONES which are connected to a RADIO SURVEILLANCE MICROPHONE attached to a pair of BINOCULARS.
Suddenly MUSIC explodes through his headphones--Healy's jolted awake.
Who threw the grenade?
Recovering, Healy aims the binoculars toward...
Healy has a clear, unobstructed view into Mary's apartment.
The music is coming from Mary's clock radio.
MARY sits up in bed and shakes herself awake, like someone's just poured cold water over her.
She cranks the music even LOUDER.
Mary hops out of bed, wearing only her panties, and though she's a little older now, she still looks well cast.
<U>CLOSE UP</U> - ON HEALY - he's become extremely interested in his work.
As much as Healy's enjoying the show, he's got a job to do--he speaks into a MICRO-CASSETTE RECORDER:
HEALY Okay, Ted, I found your Mary.
HEALY Her current address, two-niner-eight Euclid Avenue, Miami Beach.
HEALY Husband, negative.
HEALY Children and Labrador, negative.
HEALY Extremely nice ass, affirmative.
Mary walks into the living room where we see an old woman, MAGDA, sitting on the couch LISTENING to a stack of RADIO SCANNERS.
MARY Have you been up all night again?
MAGDA Bet your ass I have.
MAGDA It's an important job, Neighborhood Watch is.
MARY Neighborhood Watch?
MARY Is that what you call listening in on stranger's phone conversations?
MAGDA These ain't strangers, they're <U>neighbors</U>.
MAGDA This only picks up signals in a half-mile radius.
MARY Meaning?
MAGDA Meaning these are the people you live amongst, you got a right to know if they're creeps.
MAGDA For instance, did you know there's a guy down the hall cheating on his wife?
MARY You picked that up on the scanner.
MARY We gotta move.
MAGDA I <U>confirmed</U> it on the scanner.
MAGDA I knew something was up because Puffy used to bark like hell whenever he saw him and you know Puffy only barks at bad people.
Magda pats her little dog PUFFY on the head.
MARY Magda, Puffy barks at everybody.
MAGDA That's because there's a lot of bad people out there.
MAGDA Hey, Puffy tried to warn you about that Steve guy you was seeing--he was a fucking asswipe--but you had to find out for yourself, didn't you?
MARY Okay, you win.
MARY Now try to get some sleep, huh.
Mary gives Magda a kiss and heads to her bedroom.
<U>MUSIC MONTAGE</U> - as Healy follows Mary around town.
Mary exits her apartment and bounces out into the world.
There is a HOMELESS MAN sitting on the sidewalk.
Mary flips him an apple, then jumps in her Honda Civic and drives off.
Mary is at the range HITTING a couple buckets of balls.
<U>ON HEALY</U> - watching from the parking lot.
HEALY Looks like we got an athlete on our hands.
Mary waits in the drive-thru lane reading the SPORTS PAGE.
Finally the window opens and she is handed a HUGE BAG OF FOOD.
<U>PAN TO</U> Healy watching from his car.
HEALY Well, from her figure and her appetite, I'm guessing she's either got a bowel disorder or we've got a hurler on our hands.
Mary's brother Warren is wearing a walkman as he plays catch out front with a SPECIAL ED TEACHER while several other MENTALLY-DISABLED PATIENTS entertain themselves.
Mary pulls up, gets out, and starts handing out Egg McMuffins.
MARY Get in line.
MARY One at a time.
A fat patient, GARY, approaches.
GARY Can I have two, Mary?
MARY Yeah, you can have two halves, just like everyone else.
GARY Thanks.
Gary takes his and walks off.
A couple more patients and then bucktoothed FREDDIE steps up to her.
FREDDIE Will you marry me, Mary?
MARY Oh yeah, pretty boy?
MARY And what about Dolores?
Mary points to another PATIENT staring bashfully at Freddie.
FREDDIE Would you marry us both, Mary?
MARY Yeah, that'd be a good deal for you, wouldn't it?
Freddie moves off and fat Gary is back, trying to be inconspicuous.
MARY (cont'd) Wow, this is weird.
MARY (cont'd) There was somebody who looked just like you here a minute ago.
Mary smiles and hands Gary another McMuffin.
<U>CLOSE ON</U> Healy.
HEALY Ixnay on the big appetite.
HEALY She's just got a big heart.
Neighborhood restaurant and bar.
After-work crowd.
Mary and her friends, BRENDA, LISA, and JOANIE are sitting at a table under an umbrella.
Lisa reads from the PERSONALS COLUMN in <U>South Beach Magazine</U>.
LISA Listen to this one--'Seeking sensitive Wasp doctor to share candlelit dinners, long walks in Coconut Grove, marriage.'
BRENDA What does this girl want, a corpse?
BRENDA You gotta be more specific: 'Seeking deaf mute with three pound cock and trust fund.'
JOANIE No, it should be 'a hockey player with great pecs.'
MARY Ugh, not pecs.
MARY Sounds like one of those guys with a fish-net shirt and a banana hammock.
<U>PAN TO</U> the bar where we see Healy eavesdropping on their conversation.
BRENDA I suppose you wouldn't like someone with a washboard stomach like Brad Pitt?
BACK ON Mary and friends.
MARY I'm just saying I don't mind a guy with a bit of a beer belly.
MARY It means he's a guy.
MARY You can have those pretty boys who hang out in a gym all day staring at their reflections.
A girl after your own heart, Ted.
<U>BACK ON</U> Mary and friends.
JOANIE I can live with those reflections.
MARY I'm sick of these calorie-countin' pansies.
MARY Give me a guy who likes kielbasa and beer and playing thirty-six holes and still has enough energy to take me and Warren out to a ballgame.
JOANIE Jeez, I don't know where you're ever going to find a guy like that.
MARY But here's the rub.
MARY The guy I'm talking about has got to be self-employed.
LISA You mean, like an architect or something?
MARY Architect, yeah.
BRENDA You mean creative, but not poor.
MARY No, it's not the money.
MARY Creative, yeah, that's good, but it's the freedom I'm talking about.
MARY See, this guy has to have a job he could do anywhere.
MARY That way we could just up and leave at the drop of a hat.
LISA And where would you and your beer-bellied architect be leaving to?
MARY I don't know.
MARY The Super Bowl, New Orleans Jazz Festival...maybe a couple months in Nepal.
JOANIE Yeah, and you'd probably dump the poor guy halfway to Katmandu.
MARY What's that supposed to mean?
JOANIE It means you're too hard on guys.
MARY No I'm not.
JOANIE Oh come off it, Mare.
JOANIE What about what's-his-name...Steverino?
JOANIE You could've at least passed the baton on that one.
The girls LAUGH.
MARY Yeah, Steve.
MARY Steve was all right for awhile.
JOANIE All right for awhile?
JOANIE The guy's good-looking, rich, witty.
JOANIE He was a god.
LISA At one point you were talking about marrying him.
LISA Come on, why'd you dump him?
Mary thinks about this.
MARY I don't know, it was complicated.
MARY He's in San Francisco, I'm in Miami.
MARY Besides, Magda's psychic dog hated him.
JOANIE Is that old crab still with you?
JOANIE Mary, you said you were putting her up for a month--it's been a year and a half.
MARY Ah, she's okay.
LISA Mary, cut the crap, what really happened with Steve?
MARY Nothing.
MARY I mean, you know my brother.
MARY Warren.
JOANIE What?
JOANIE Steve seemed to put up with Warren.
MARY I don't want someone who'll <U>put up</U> with him.
MARY I want someone who will enjoy him, the way I do.
MARY Do you know what he told my friend Tucker?
MARY He said he would've popped the question a lot earlier if Warren wasn't in my life.
MARY Well he is in my life and I'm goddamn lucky to have him.
MARY The hell with Steve.
Everyone is touched by this.
Then:
BRENDA Well, that's the last time I blow <U>him
</U> behind your back.
As the girls LAUGH, we
Healy sits out front in his car again waiting for Mary to get home.
He picks up the phone, dials a number, and someone answers but doesn't speak.
HEALY Hello...?
HEALY Sully...?
HEALY Sully, that you?
SULLY (V.O.) Who the fuck is it to you?
HEALY Sully, it's Healy.
HEALY What's going on over there?
Sully is sitting on the kitchen floor in his police uniform, a ring of white around his nostrils.
The room is littered with beer cans, he has another one in his hand, there's a pile of cocaine and a rolled-up bill on the breakfast table.
The dog and the snake are in the doorway looking at him with concern.
SULLY Fuckin' Patrick Healy, you think your shit don't stink.
SULLY Well I got news for you--you're goddamn right it don't!
SULLY How the hell are ya?!
Healy looks at the phone, concerned.
HEALY Uh, I'm fine.
HEALY Just wanted to let you know I'll have your car back in a couple hours, I'm still staking out this girl's apartment.
SULLY (V.O.) You found my car?!
Just then Healy notices Mary pull up and park.
He slides down in his seat.
<U>ON MARY</U> - she gets out carrying a bag and approaches the Homeless Man, who is still sitting on the sidewalk.
She hands him the bag.
HOMELESS MAN Thanks, Mary.
MARY You watch out for yourself, Herb.
As Mary bounds up the steps of her building, we
<U>HOLD ON</U> the Homeless Man as he happily takes a sandwich and soda out of the bag.
As Mary rushes into the apartment, Magda is glued to her radio scanner, listening intently.
MAGDA Jesus, Mary, you gotta hear this--some cop's staking out this broad's apartment.
MARY No time, Magda, my show's starting.
...
he can hear the conversation through the SURVEILLANCE EQUIPMENT pointed at Mary's place.
MAGDA (V.O.) This is a good one, Mare.
MAGDA (V.O.) Sounds like his partner's all lubed up.
HEALY Call you back.
SULLY God, I miss ya, ya fuck-
Healy hangs up abruptly.
MAGDA Ah, Christ, I lost 'em.
Mary runs into her bedroom, shuts the door and flips on the tube just as <U>ESPN Sportscenter's</U> OPENING THEME SONG is playing.
Relieved, Mary lays back on her bed and starts watching.
Mary is now watching <U>Andy Griffith</U> while SMOKING A JOINT and GIGGLING away in bed.
<U>ON HEALY</U> - he's sitting in his car, GIGGLING, too.
HEALY Fucking Barney...he never learns...
As the show's end credits start to WHISTLE AWAY, Mary stands and starts to UNDRESS for bed.
<U>BACK ON HEALY</U> - he sits up, very interested now.
HEALY Here we go, Teddo.
HEALY Here comes the money shot.
Healy quickly reaches in the back seat and pulls out a bigger,
<U>HEALY'S BINOCULAR POV</U> - we're CLOSE ON the wrinkliest, saggiest, droopiest set of milkbags on the planet.
<U>ON HEALY</U> - he cringes.
HEALY (cont'd) Oooof.
HEALY (cont'd) First chink in the armor, Teddy Boy....
HEALY'S BINOCULAR POV - He moves his view up from the tits to reveal...MAGDA UNDRESSING for bed.
<U>ON HEALY</U> - He flinches, sickened by his mistake, then repositions the binoculars dead left to the next window.
<U>HEALY'S BINOCULAR POV</U> - moving over to the next window we see...
Mary as she just finishes putting on some sexy t-shirt.
<U>ON HEALY</U> - as he starts to drool.
HEALY (cont'd) Oh sweet Jesus
Ted is sitting alone having a beer when a smiling Healy approaches.
HEALY I've got some very, very good news for you, my friend.
TED Really?
TED <U>Very, very</U>?
Healy sits down and motions for a beer.
HEALY I think your life's about to change.
TED So you found Mary?
HEALY Right there in Liberty City.
HEALY And you were right, she's really something.
TED So she hasn't changed?
HEALY That I couldn't.
HEALY say.
HEALY Let me ask you something: Was she a little <U>big-boned
</U> in high school?
TED No, not at all.
HEALY Well she must've packed on a few pounds over the years.
This doesn't dampen Ted's enthusiasm.
TED Mary's a little chubby, huh?
HEALY I'd say about a deuce, deuce and a half.
HEALY Not bad.
Ted's smile starts to fade.
HEALY (cont'd) But you know, you shit out a bunch of kids, you're going to put on a few pounds.
TED So she's married?
HEALY Nope.
HEALY Never been.
TED Huh?
HEALY Four kids, three different guys.
TED Three different guys?
HEALY Well I'm guessing.
HEALY There's a black kid, two whites, and a midget.
TED Oh my.
HEALY Hyperactive little fuckers, too.
HEALY Tough to keep up with in a wheelchair, I bet.
TED She's in a wheelchair?!
Ted looks completely drained.
HEALY Don't look so shocked, it's been a long time.
HEALY I bet you've changed a lot over the last twelve years, haven't you?
TED It's just that...Mary.
TED I wouldn't have thought...
HEALY Anyway, the good news is I have all the information you need.
HEALY Got it from her bookie--nice guy.
HEALY You should definitely call her, Ted.
HEALY I mean she's a real sparkplug, that one.
HEALY She seems determined to get those rugrats off welfare and with your help I'll bet she does it.
Ted stands and starts moping away.
TED Thanks, Healy.
TED Good work.
HEALY Ted?
HEALY Don't you want the name of the housing project?
TED Uh, that's okay.
HEALY You sure, big guy?
HEALY I'll bet she'd love to hear from you before her mastectomy!
As Ted leaves, Healy puts his feet up on the table and sits back.
We PAN across the room of unopened boxes to Ted laying awake in bed.
We hear HEAD-BANGER MUSIC coming from the apartment next door.
Finally Ted gets up and walks over to his dresser.
As he flips on a small light we see loose change, a balled-up Kleenex, a few golf tees, and Ted's wallet.
Ted picks up the wallet and opens it.
<U>TED'S POV</U> - Inside is an an old high school photo of a smiling Mary.
As Ted looks at it, he can't help but smile, too.
<U>ON HEALY'S CUBICLE</U> - Healy's taking his last boxload of crap out of his cubicle when he spots Ted.
He tries to duck back in but Ted sees him.
Healy forces a smile as Ted approaches.
TED What are you doing?
HEALY Oh, uh, I resigned.
Ted picks up a plane ticket off the desk.
TED Miami?
HEALY Yeah, this insurance business is too slow for me.
HEALY I'm going to go down and try my hand at jai alai.
TED Jai alai?
HEALY Yeah, I don't know why but I always felt at home in the fronton.
Healy starts walking out of the office and Ted follows.
Healy is having a hard time looking him in the eye.
So he doesn't.
TED Look, uh, I've been thinking about everything you told me.
HEALY Good good.
TED Well I think you're right, I should look her up.
HEALY Rollerpig?
HEALY Are you nuts?
TED But you said she was a sparkplug...?
HEALY I said buttplug.
HEALY She's heinous.
Ted SIGHS and follows Healy out the front door.
They walk across the lot toward Healy's car.
TED All the same, I still want to call her.
TED I know it sounds crazy--Mary sure has a lot of troubles in her life--but, I don't know, maybe I can help her out.
TED The poor thing's had it tough--she's in a wheelchair for Godsakes.
HEALY It's a goddamn bunion.
HEALY It'll heal.
TED Oh.
TED I thought
TED That's not it anyway.
TED I know this doesn't make any sense to you, but I just can't turn it off that fast.
TED I still feel something for her.
Healy comes to his car and puts his stuff in the trunk.
HEALY Okay, tell you what: I'll get her number for you just as soon as she gets back from Japan.
TED Japan?
TED What's she doing in Japan?
HEALY You've heard of mail-order brides?
HEALY Well they go that way, too.
Ted is devastated.
TED Mary's a mail-order bride?
HEALY Fetched a pretty penny, too.
HEALY Don't forget, it's the Sumo culture, they pay by the pound there.
HEALY Sort of like tuna.
Off Ted's look, we
Ted and Dom are having a beer and a dog.
TED That's it, I'm making an oath.
TED I'll never procrastinate about anything again.
TED Life is too fucking short.
DOM Hey, look on the bright side--
TED What's that, Dom?
TED What's the bright side?
DOM Well...at least now you know.
TED I think it was better when I didn't.
TED It was kind of inspiring to know there was someone so pure in the world.
As Ted dwells on this, Dom bursts out LAUGHING.
TED What's so funny?
DOM I'm sorry, it's just that you're taking this all wrong, pal.
DOM Don't you see?
DOM You're <U>liberated</U>.
DOM I feel liberated.
DOM I mean here you've been in therapy thinking you blew it with the greatest girl ever, and it turns out that getting your dick stuck in your zipper was the best thing that ever happened to you!
Ted flinches at this.
TED Wait a second, I never told you that.
DOM Christ, Ted, I was only four towns away.
Ted thinks it over.
TED Maybe you're right.
TED I should look on the bright side.
TED I mean, I've still got my health...
TED I'm out of here.
TED I've got to get up at six a.m.
TED to move my boss's brother into his apartment.
DOM <U>What</U>?
DOM On your day off?
DOM Do you even know the guy?
TED Never met him.
DOM Jesus, Ted, you've got to finish that damn novel so you can quit that stupid magazine.
TED Amen to that.
Healy pays for a bucket of balls, then takes his clubs and strolls jauntily to...
</U>Healy places a ball on the tee and takes a swing.
He tops the ball and it dribbles about ten yards.
HEALY Hit a house!
HEALY Bite bite!
HEALY Haven't swung the wrenches in a while.
Mary nods.
Healy takes another swing and duck-hooks one about fifty yards.
Mary addresses her ball, takes a smooth backswing, and
HEALY (cont'd) Hey, can you give me some tips here?
She cracks her shot long and straight.
MARY Yeah, don't talk in someone's backswing.
HEALY Thanks.
Mary tees up another ball and Healy puts down his club.
HEALY (cont'd) I'm gonna get a soda, you want one?
MARY No thanks.
Healy pulls out a huge wad of change from his pocket.
HEALY Oh cripes.
HEALY Do you have change for a dollar?
HEALY All I have is these stupid Nepalese coins.
MARY Nepal?
MARY Have you been?
HEALY Not in months.
HEALY I don't even know why I bought the damn place.
MARY You own a home there?
HEALY Well...it's just a condo really.
HEALY Right outside Katmandu.
MARY Wow.
MARY That's a place I've always wanted to go.
MARY Is it true the mountains are so tall you can't see the tops?
HEALY Not 'til you get about three hundred yards from the summit.
HEALY That's been my experience anyway.
She looks impressed.
Healy looks at his watch.
HEALY (cont'd) You know, I should just get going.
HEALY (cont'd) I'll work on my game next week.
He flips her a coin.
HEALY (cont'd) Here.
HEALY (cont'd) Spend it on your trip to Katmandu.
MARY Thanks.
Healy starts to walk off.
Mary doesn't know what to do.
Will she ever see this guy again?
MARY (cont'd) It was nice meeting you!
Healy doesn't answer or turn around.
He just raises his hand and gives her a little wave.
Mary shrugs her shoulders.
Oh well...
Healy is sitting in Sully's Chrysler LeBaron, right next to Mary's Honda Civic.
He watches the rear-view mirror, and the moment he sees Mary coming out from the driving range, he swings his legs out the door and starts changing out of his golf shoes.
As Mary tosses her golf bag into the trunk, she notices Healy tying his shoes.
A second chance.
MARY Well, it was nice meeting you, again.
HEALY Same here again.
MARY By the way, what's your name?
HEALY Pat Healy.
There's an uncomfortable pause...Why doesn't this guy ask the usual questions?
MARY Don't you want to know my name?
HEALY I already know it, Mary.
MARY How'd you know that?
HEALY It's right there on your golf bag.
Healy opens the back door to put away his golf shoes.
Suddenly, rolls and rolls of paper come tumbling out.
Mary bends over to help Healy pick them up.
MARY What are you doing with all these blueprints?
HEALY Some buildings I'm working on.
MARY Are you...an architect?
HEALY Well, just until I get my PGA Tour card.
Mary stares at him, mouth agape.
HEALY (cont'd) I'm kidding.
HEALY (cont'd) Yeah, I guess you could call me an architect--it's just a job really, a way to keep me moving.
HEALY (cont'd) My real passion is my hobby.
MARY What's that?
HEALY I work with retards.
MARY I beg your pardon?
HEALY You know...
HEALY ...the guys who ride the short bus.
MARY Isn't that a little politically incorrect?
HEALY The hell with that.
HEALY No one's gonna tell me who I can and can't work with.
MARY No, I mean
HEALY --There's this one kid, we call him Mongo on account of he's a mongoloid.
HEALY He got out of his cage once and--
MARY --He's in a cage?!
HEALY Well it's more of an enclosure really.
MARY They keep him confined?
MARY That's bullshit!
HEALY That's what I said, so I went out and got him a leash you know, one of those clothesline runners for the backyard.
HEALY He's got plenty of room out there to dig.
HEALY The kid's really blossomed.
HEALY Now I can take him to ball games, movies--you know, happy stuff.
MARY That sounds like fun.
HEALY Yeah, it's fun for them, but it's heaven for me.
HEALY Those goofy bastards are just about the best thing I have in this crazy old world.
HEALY Ooh, hey, I gotta run.
MARY Look, uh, I was thinking maybe we should go have dinner sometime.
Healy smiles at this and we
A profusely sweating Ted has a DRESSER ON HIS BACK and EEKS his way toward the front door as his BOSS'S DISABLED BROTHER catches up to him IN A WHEELCHAIR.
(The man is a quadriplegic who needs to use a MOUTHPIECE to operate his chair.)
BOSS'S DISABLED BROTHER Hey, shit-for-brains, be careful not to scratch that thing, huh?
TED What?
BOSS'S DISABLED BROTHER You heard me.
BOSS'S DISABLED BROTHER You already put a fucking nick in my piano.
TED I'll try to be more careful.
BOSS'S DISABLED BROTHER S'matter with you?
BOSS'S DISABLED BROTHER You look like you're fading.
TED The thing's kind of heavy.
BOSS'S DISABLED BROTHER Heavy?
BOSS'S DISABLED BROTHER Heavy?!
BOSS'S DISABLED BROTHER What I wouldn't give to know what heavy feels like, you insensitive prick.
TED No, I just meant...
BOSS'S DISABLED BROTHER Yeah yeah.
BOSS'S DISABLED BROTHER I'm going to the corner to get a cup of coffee.
The Boss's Disabled Brother bites into the mouthpiece and ZIPS AWAY up the sidewalk.
Ted takes a step.
Rests.
A step.
Rests.
ASSERTIVE WOMAN'S VOICE Hey you!
Ted glances back toward the street to see a T.V. NEWS REPORTER from the CHANNEL 7 I-TEAM rushing toward him with a NEWS CREW on her heels.
T.V. NEWS REPORTER (cont'd) Do you know that you're parked in a handicapped spot?
Ted is splayed out on a table in obvious pain while DR.
LALONDE, an old high school pal, palpates his spine.
DR. LALONDE So...I see you made the news.
TED It wasn't my truck--I was helping out a guy in a wheelchair.
DR. LALONDE Uh-huh.
DR. LALONDE Where was he?
TED Out getting coffee.
DR. LALONDE Yeah, that's more or less what the others said, too.
DR. LALONDE Out getting coffee...supposed to meet him here...picking up my grandma...
Ted turns and GLARES at him.
DR. LALONDE (cont'd) I'm just saying...They sure made you look dumb.
Ted SIGHS.
A couple big CRACKS of the neck.
TED Bob, do you remember Mary?
DR. LALONDE Who?
TED Mary.
DR. LALONDE From high school Mary?
DR. LALONDE Yeah, I saw her about six months ago at a convention in Las Vegas.
Ted sits up.
TED A convention?
TED How'd you see her at a convention?
DR. LALONDE I'm an orthopedic surgeon, <U>she's</U> an orthopedic surgeon.
The Doc SIGHS, still able to recall the feeling.
DR. LALONDE (cont'd) What a babe...
Ted sits up on his elbows.
TED Babe?
A buckled-over Ted limps into Dom's office with a crazed look on his face.
TED Mary's a babe!
DOM What?
TED My Mary--she's not in Japan, she's single, and she's got no rugrats.
TED She does have a little gambling problem, she plays the football cards a bit too much, but she's a babe, a surgeon babe!
DOM Huh?
DOM But why did Healy?
TED Well think about it.
Ted folds his arms.
DOM No You mean...?
TED Uh-huh.
DOM The lazy fuck just didn't bother to look her up.
TED That sneaky prick was probably practicing his jai alai.
Dom shakes his head.
Then:
DOM Well then you've got to call her, man.
TED Fuck calling her.
TED I'm going down there.
While Mary gets ready for her date, Magda sits in front of the radio scanner in her bathrobe with her little dog Puffy on her lap.
MAGDA So who's the lucky guy?
MARY Name's Patrick, I met him at the driving range.
MAGDA Good lookin'?
MARY He's no Steve Young.
Healy, listening through his headphones, reacts to this.
MAGDA (V.O.) What's he like?
MARY (V.O.) I don't know.
MARY (V.O.) He's kind of a mook.
MAGDA (V.O.) What's a mook?
MARY (V.O.) You know, a mookalone, a schlep.
MAGDA Then why you going out with him if he's a schlep?
MARY Come on, Magda
MARY It's like that movie <U>Harold and Maude</U>.
MAGDA I don't watch the new ones.
MARY This one's almost thirty years old.
MARY It's about a young kid and an old lady who fall in love.
MAGDA That's exactly why I don't watch 'em anymore--it's bullshit!
MAGDA Why the hell would an old lady go for a young kid?
Mary smiles at this.
MARY The point is, love isn't about money or social standing or age, it's about <U>connecting with someone</U>, having things in common kindred spirits.
MAGDA Fuck kindred spirits.
MAGDA My little Puffy here's gonna tell you all you need to know about this guy in about two seconds flat.
MAGDA If he starts yapping, he's a loser; if Puffy's relaxed...well, you got yourself a keeper.
As Healy thinks about this, we
Healy enters the building.
Healy tiptoes up to Mary's apartment door.
He peeks through the mail slot.
<U>HEALY'S POV</U> - Puffy is staring at him and GROWLING.
Healy reaches in his pocket, pulls out a VALIUM and a DOGGY TREAT.
Healy shoves the pill into the treat's soft center, examines it, then thinks what the hell and SHOVES IN ANOTHER ONE.
Puffy GROWLS LOUDER.
Healy pops the treat through the mail slot and listens as the dog DEVOURS IT.
Healy looks at his watch, then sneaks back outside to wait a few minutes for the drugs to kick in.
Healy is sitting on Mary's couch with Puffy spread-eagled upside-down on his lap, KNOCKED OUT COLD.
Mary and Magda look on in amazement.
HEALY Oh, Pufferball likes his little tum-tum rubbed, doesn't he now?
MARY Wow, I've never seen him like this.
MARY He doesn't usually like guys.
MAGDA You mean he doesn't like <U>bad guys</U>.
HEALY 'That right?
MAGDA He can tell you're an animal nut.
MAGDA You are, aren't ya?
HEALY Truth is I usually get along better with animals than with people.
HEALY In Nepal the villagers call me 'Kin-tan-tee', which means 'man who is loved by many animals...
HEALY ...who love him a lot, too...and so on.'
Magda stares dreamily at Healy, smitten.
MAGDA Would you like a glass of tea or something?
HEALY You got a brew?
MARY Sure.
MARY Uh, Magda, why don't you get some more cheese and crackers...?
MAGDA Oh, yeah, of course, dear.
The two women go into the kitchen and Healy is left to pet the MOTIONLESS DOG.
Suddenly Healy notices that the dog is A LITTLE TOO MOTIONLESS.
Healy checks Puffy's pulse.
He looks at his watch to time the rate.
MARY Sorry, Pat, out of beer.
MARY You like vodka?
HEALY Great.
He starts SHAKING THE DOG, but Puffy doesn't move.
Healy goes into action.
He starts pressing on his heart, PERFORMING DOGGIE CPR.
One-and-two-and-three, he continues trying to revive him.
MAGDA Would you like a little clam-dip, honey?
HEALY No, thanks.
HEALY Love a little bundt cake if you have some!
Magda and Mary are on their way out the door when they stop.
MAGDA Bundt cake?
MARY Must have a sweet tooth.
MARY See if you can find some cookies.
As Magda starts to go through the cupboards...
A panicked Healy is giving the little mutt MOUTH-TO-MOUTH now.
Then back to the heart, the mouth, the heart, the mouth....
HEALY Come on, man, stay away from the light!
Healy resumes blowing into the dog's snout, pumping his chest, with no results.
Desperate, he picks up the cheese knife and quickly SLICES THE WIRES ON TWO TABLE LAMPS.
Healy grabs the two wires and TOUCHES THEM TOGETHER LIKE A DEFIBRILLATOR on the little pooch's chest.
<U>ZZZZZTTTTTT</U> - the dog BOUNCES a couple feet off the couch as
Healy takes his pulse again.
Nothing.
He ZAPS him once more with the LIVE WIRES.
<U>ZZZZZTTTTT</U> - Still nothing.
Healy gets to his feet and peeks into the kitchen.
When he turns his back, we see PUFFY IGNITE IN
When Healy turns back, he's horrified at what he sees.
He grabs a vase of flowers and POURS THE WATER ON THE BURNING DOG.
With this, Puffy flinches and comes to, GASPING FOR AIR!
MAGDA All I had was some Funny Bones--how does that sound, honey?
Healy picks up the stunned pooch and swaddles it in a blanket as Magda ENTERS the room followed by Mary.
HEALY Fine.
HEALY Fine.
MARY Here you go.
MARY What's that smell?
Mary hands Healy his vodka and as he downs it, we
Healy looks slightly disoriented as Mary leads the way into the courtyard area by the main building.
HEALY The museum?
HEALY I thought we were going out to dinner?
MARY We will, but first I have a surprise.
HEALY A surprise?
MARY The architecture exhibit!
MARY My friend Tucker is going to be here.
MARY He's an architect, too.
MARY You guys will have tons to talk about.
<U>CLOSE ON HEALY'S FACE</U> as he starts to panic.
Mary and Healy walk through the exhibit area.
Mary scans the room for her friend.
Healy's face is ashen.
MARY I know he's around here someplace.
HEALY What say we get outta here and go crush a bucket?
MARY We just got here thirty seconds ago.
MARY Isn't this stuff great?
Mary points to an architectural model.
MARY (cont'd) Is this one art deco or art nouveau?
HEALY Deco.
MARY Would you call that a portico or a vestibule?
HEALY That...?
HEALY Vestibule.
MARY How about--?
HEALY When you look at architecture, try not to concern yourself with the pieces--look at the building in its totalitarianism.
Mary gives him a look.
Suddenly, Healy draws a couple of invisible sixshooters at her.
HEALY (cont'd) Stone crab time!
HEALY (cont'd) Come on, let's get outta here, goofy.
He turns to go but Mary notices something O.S.
MARY Tucker!
Mary leads Healy over to her friend TUCKER, a distinguished-looking man in his fifties.
Healy looks like a dog that's being dragged to the vet.
Mary and Tucker embrace.
TUCKER Come on, like you mean it.
Mary LAUGHS and hugs Tucker tighter.
Then:
MARY Tucker, this is my friend Pat Healy.
MARY Healy and Tucker shake hands.
TUCKER Pleasure to meet you, Patrick.
HEALY Same here.
MARY Pat's an architect, too.
TUCKER Hey, no kidding?
TUCKER Where are your offices?
HEALY Mainly I work out of Boston.
TUCKER Boston, huh?
TUCKER Did you get your degree up there?
HEALY Yes yes, I did get my degree up there.
TUCKER Harvard?
HEALY You bet.
TUCKER Did you study under Kim Greene?
HEALY Among others.
TUCKER Kim and I are close friends!
HEALY Well, I'll tell her I ran into you.
TUCKER You mean him.
HEALY Well...that's debatable.
Healy makes a hand-gesture to imply that Kim's sexuality is in doubt.
TUCKER <U>Really</U>?
TUCKER But he's been married for twenty years--they've got six kids.
HEALY Nice smokescreen, isn't it?
Tucker can hardly believe his ears.
MARY Pat does projects all over the world.
TUCKER Where would I have seen your work?
HEALY Have you been to
HEALY Let's see--Santiago, Chile?
TUCKER Absolutely!
TUCKER I was there twice last year.
TUCKER Which building is yours?
HEALY Do you know the...soccer stadium?
TUCKER Did you build the Estadio Olympico?
HEALY No...just down the street, the Amigo Tower.
TUCKER I'm sorry, I'm not familiar with it.
TUCKER What style?
HEALY Uh, sort of nouveau deco...with a big vestibule.
HEALY Check it out next time you're up there.
Tucker starts to look a little suspicious.
TUCKER You know, I really should take your card.
HEALY Oh look, it's Doob!
HEALY Will you excuse me a minute, Tucker?
Healy drags Mary across the room toward a MAN who's looking at an exhibit.
HEALY Dooby, you old sheep-fucker!
HEALY How the hell are ya?
MAN My name's Mel.
HEALY Oh, sorry.
HEALY Anyone ever tell you you look just like Jim Dubois?
MAN The sheepfucker?
Healy shrugs and the man walks away angrily.
A two-door Toyota Tercel flies by the camera.
A determined Ted is cruising along the highway in his rent-a-car.
He has a cup of coffee in his hand and a HITCHHIKER in the seat beside him.
The Hitchhiker sits with a LARGE RED DUFFEL BAG between his legs.
HITCHHIKER Thanks for picking me up.
TED No prob, I could use the company.
TED I've been on the road going on fifteen hours straight.
HITCHHIKER I know how you feel--I been standing in the same spot for the last five hours.
HITCHHIKER You know it's against the law to pick up a hitchhiker in this state.
TED That must make it tough.
HITCHHIKER Sucks.
HITCHHIKER So what's up?
HITCHHIKER You some kind of salesman or something?
TED Nah.
TED I'm...I'm nothing.
HITCHHIKER Oh.
HITCHHIKER Well I am.
TED Hm?
HITCHHIKER A salesman--that's what I am.
HITCHHIKER I mean, I'm gonna be anyway.
HITCHHIKER I'm starting my own company--video sales--just as soon as I get enough seed money.
TED 'That right?
TED Good for you.
HITCHHIKER Yeah, you wouldn't believe my idea--it's a home run.
HITCHHIKER You ever hear of <U>Eight-Minute
</U> <U>Abs</U>?
TED The exercise tape?
TED Sure, I've seen it on
HITCHHIKER Two million copies it sold last year.
HITCHHIKER <U>Two
</U> <U>million, man</U>.
But not next year--my idea's gonna blow them outta the water.
Get this:
<U>Seven-Minute Abs</U>.
TED I see where you're going.
HITCHHIKER Think about it.
HITCHHIKER You walk into a video store and you see <U>Eight-Minute Abs</U> and right next to it you see <U>Seven-Minute
</U> <U>Abs</U>--which one you gonna spring for?
TED I'd go with the seven.
HITCHHIKER Bingo.
HITCHHIKER Especially since we guarantee you'll get every bit as good a work-out.
TED How do you guarantee that?
HITCHHIKER Well it's the company motto: 'If you ain't happy we'll send you the extra minute.'
TED Huh.
TED That sounds great.
TED Unless someone else comes out with Six-Minute Abs.
Ted CHUCKLES, but the Hitchhiker just GLARES at him, unamused.
TED (cont'd) I'm gonna pull over.
TED (cont'd) I gotta take a leak.
The Toyota Tercel pulls in and parks.
Ted gets out and walks into the bushes to whiz.
<U>ON TED</U> - as he steps into the dark brush UNZIPPING his fly he TRIPS over something and FALLS TO THE GROUND.
TED What the--?
Suddenly WHOOSH, WHOOSH, WHOOSH--several huge SPOTLIGHTS illuminate the area revealing
<U>TWO DOZEN FRIGHTENED MEN</U> scurrying to pull their pants up all around him.
<U>ANGLE ON</U> a startled Ted ON HIS KNEES directly in front of ANOTHER MAN, making it appear that he's been BLOWING THE GUY.
<U>REVERSE ANGLE</U> reveals a DOZEN POLICE OFFICERS holding the spotlights and moving in for the arrests followed by a CAMERA
TED Wait a second, it's not what you think.
A GUY with his pants at his ankles jumps on the bandwagon.
PANTS AT ANKLES GUY That's right!
PANTS AT ANKLES GUY I-I-I was just pissing!
Ted glares at him.
TED No!
TED I was pissing!
POLICE OFFICER Yeah, I'll bet you all were.
POLICE OFFICER Come on, in the truck.
As they grab Ted and the others and hustle them away, we
<U>PAN TO</U> the Hitchhiker sitting in the Toyota watching the raid unfold.
The Hitchhiker is clearly PANICKY at the sight of all the cops.
Quietly he OPENS THE CAR DOOR, ducks down, and then SPRINTS AWAY
<U>CLOSE UP OF TELEVISION SCREEN</U> as the bust continues.
Each of the men COVER THEIR FACES as they pass by the camera, EXCEPT FOR TED who is extremely visible.
TED Okay, take it easy, you don't have to push.
<U>REVERSE ANGLE REVEALS</U> a shocked Dom and his wife watching this on their television.
DOM Oh my God.
DOM Is that...?
DOM'S WIFE Told you he was gay.
<U>BACK ON THE TELEVISION</U> - The COPS struggle to get the feisty Ted into a police van.
TED I was taking a leak!
T.V. ANNOUNCER (V.O.) We'll be right back with more of our special edition of <U>COPS</U> - LIVE IN THE
Healy and Mary are walking home at the end of their date.
Healy is eating a big, wild cone of COTTON CANDY and drinking a beer.
HEALY That grandmother of yours--she's really something.
MARY Magda?
MARY She's not my grandmother--actually she rents the apartment right next to mine.
MARY Her husband passed away a couple years ago so she doesn't like to be alone.
HEALY And it doesn't cramp your style?
MARY Sadly, no.
MARY Well except for the lint.
HEALY Lint?
MARY Yeah, I think it's that dog of hers running around on the rug all day--just makes for a lot of lint.
MARY Look at this...
Mary lifts her shirt, revealing a BIG CLUMP OF COTTON CANDY
MARY (cont'd) See?
MARY (cont'd) That's just one day.
Healy CRACKS UP and then gazes at her.
What a babe.
HEALY You know, sometimes I wish I could be like Magda and not go home.
HEALY I'd like to just bounce around for awhile, do a little traveling...
MARY Why bounce when you have your own condo in Nepal to go to?
It's clear Healy forgot about that one.
HEALY Ah, I'd sell that.
HEALY Start fresh in a new place, quit the architect game, slow things down, read more books, see more movies...
MARY You're a movie buff?
HEALY Try to be.
HEALY It's tough going with the crap they make today.
HEALY If <U>Dumb and Dumber</U>'s the best they've got to offer I say thanks but no thanks.
MARY Have you seen it?
HEALY No.
HEALY But the Boston Globe critic Jay Carr hated it.
MARY A fucking moron.
HEALY Huh.
HEALY I guess I just wish they made them like they used to.
HEALY You know, something like <U>The Heartbreak Kid</U>...or <U>Harold and
</U> <U>Maude</U>.
Mary can't believe her ears.
MARY <U>Harold and Maude</U> is my all-time favorite movie.
HEALY Ouch.
HEALY Come on, don't bust my chops.
HEALY I know it's corny, but I do love it.
MARY Pat, I'm not kidding.
MARY I really think it's the greatest--
HEALY --Love story of our time.
Mary smiles.
Is this guy for real?
MARY Yeah.
HEALY Wow.
HEALY I thought I was the only one.
They come to her apartment building and stop.
It gets a little awkward.
MARY So...
HEALY Yeah...I guess this is it, huh?
MARY I guess.
HEALY Well, I'll see ya.
Healy turns to go but stops.
HEALY (cont'd) Mary ah, forget it.
MARY What?
HEALY No, forget it, it was stupid.
MARY Come on, what were you going to say?
HEALY Nah, really, it was moronic.
She grabs him by the shirt playfully.
MARY <U>Just say it.
</U>Healy takes a deep breath.
HEALY Could I feel your bosoms before I go?
Mary just stares at him.
MARY (beat) Knock yourself out.
Healy reaches out and cups her breasts.
He doesn't kiss her, she doesn't kiss him, he just fondles her breasts.
Then:
HEALY Okey-dokey, so tomorrow night?
She smiles and as Healy walks away we
Ted is sitting alone at a table in a small interrogation room.
<U>PULLBACK</U> to reveal that he is being observed through a two-way mirror by two detectives, FRANEK and CAVALLO.
DETECTIVE FRANEK Man, they never look like you'd expect.
DETECTIVE CAVALLO That's probably how he got the victim to drop his guard.
DETECTIVE FRANEK Where'd they find the body?
DETECTIVE CAVALLO In a big red bag on the front passenger seat.
DETECTIVE CAVALLO All hacked up--fucking gruesome--a real psycho, this one.
The Detectives ENTER the room.
Ted stands as the Detectives take a seat across from him.
TED I'm telling you, I did not solicit sex!
TED I was just stopping to go the bathroom, next thing I know I tripped over something--well someone--and, POOF, there's cops and lights and--
DETECTIVE FRANEK Okay, calm down, Ted, we believe you.
DETECTIVE FRANEK The problem is we found your <U>friend</U> in the car.
As Ted sits back down the Detectives just stare at him.
Finally Ted thinks he gets it.
TED Oh.
TED The hitchhiker.
TED That's what this is all about.
Ted puts his head in his hands and smiles.
TED (cont'd) Isn't that just my luck--I get caught for everything.
DETECTIVE CAVALLO So you admit it?
TED Guilty as charged.
TED I'm not gonna play games with you.
TED I could give you a song and dance but what's the point?
TED I did it and we all know it.
TED The hitcher himself told me it's illegal The irony.
The Detectives are surprised by his forthrightness.
DETECTIVE CAVALLO Well, uh, can you tell us his name?
TED Jeez, I didn't catch it.
The Detectives flinch at his glib demeanor.
DETECTIVE FRANEK So he was a stranger?
DETECTIVE FRANEK It was totally random?
TED He was the first hitcher I saw, what can I tell you?
TED Now cut to the chase, how much trouble am I in?
The Detectives look at one another.
DETECTIVE FRANEK First tell us why you did it.
TED Why I did it?
TED I don't know.
TED Boredom?
TED I thought I was doing the guy a favor.
The Detectives look at each other.
DETECTIVE CAVALLO This wasn't your first time, was it, Ted?
DETECTIVE CAVALLO How many we talking?
TED Hitchhikers?
TED I don't know--fifty...a hundred maybe--Who keeps track?
Finally Detective Cavallo EXPLODES across the table and starts WAILING on a shocked Ted.
DETECTIVE CAVALLO You sonofabitch!
DETECTIVE CAVALLO You're gonna fry!!!!
Mary pulls up in her Honda Civic.
She parks out front and enters the building.
<U>PAN ACROSS THE STREET TO REVEAL</U> - Healy is parked in his car.
His surveillance equipment is pointed toward Mary's office.
Mary walks into the office and sees a MEDICAL ASSISTANT standing near the coffee maker.
MARY Mornin', Jane.
MEDICAL ASSISTANT #1 Good morning, Doctor.
MEDICAL ASSISTANT #1 Your friend Tucker's in your office to see you.
Mary nods and heads toward her office.
Mary walks into her office and sees Tucker seated at her desk.
TUCKER What's up, Doc?
MARY Tucker, you look different some how.
MARY Did you do something with your hair?
<U>MARY'S POV</U> - Tucker's got two TONGUE DEPRESSORS under his upper lip making him look like a walrus.
TUCKER The teeth, the teeth.
TUCKER I got 'em capped.
<U>ON MARY</U> - smiles.
MARY Oh yeah, they look great.
He's got his listening gun fixed on Mary's office.
TUCKER (V.O.) You don't think they're too big?
MARY (V.O.) No no, the bigger the better.
MARY (V.O.) But I must say, they could be a little brighter.
MARY (V.O.) Nothing's sexier than a mouthful of pearly whites.
Healy looks at his teeth in the mirror.
Not exactly pearly.
Tucker pulls the tongue depressors out of his teeth and laughs.
He stands up, and when Mary tries to squeeze past him he gives her a kiss on the cheek.
TUCKER You ever been laid in this office?
Mary pushes past him.
MARY Behave yourself, Tucker.
MARY Come on, what are you doing here?
She sits in her chair and leans against her desk.
TUCKER I wanted to talk to you about your friend Patrick.
Healy almost flies out of his seat.
MARY He's a nice guy, isn't he?
TUCKER Well that's what I'm trying to figure out.
TUCKER How long have you known him?
Tucker has a look of concern.
MARY Not long at all, but I really like him.
MARY Okay, I know he's a little different, Tucker, but that's what I like about him.
MARY He's a guy.
MARY A real guy.
MARY He dresses like a dork and eats corndogs and he isn't always politically correct and he probably farts, too.
MARY And that's okay with me.
TUCKER That's what you've been looking for--a farter?
MARY I've been looking for a <U>guy</U>--not one of these South Beach pussies.
TUCKER Look, it's just that something about him struck me as odd last night.
TUCKER He gave me this funny vibe.
TUCKER Anyway, I called some friends back east.
TUCKER They don't know of any architect named Patrick Healy and he's not listed as a Harvard alumnus.
Healy SLAMS his hand on the steering wheel.
HEALY Fuck!!
MARY Huh...that's strange.
TUCKER I thought so.
TUCKER Anyway, I hope you don't think I'm being meddlesome.
TUCKER I just think you should be careful with this guy.
MARY No no no, Tucker, thank you.
TUCKER I mean let's face it, Mary, you're beautiful, you've got money, you trust people--I'm just saying, there's a lot of psychos out there.
MARY I appreciate you looking out for me.
<U>CLOSE ON</U> - Detective Franek as he SPEAKS, sheepishly.
His remorseful- looking partner Cavallo stands behind him.
DETECTIVE FRANEK On behalf of the entire South Carolina law enforcement community, I would like to offer our heartfelt apologies for any pain or temporary inconvenience we may have caused you, Mr. Peloquin.
<U>REVERSE ANGLE</U> - reveals that Ted is lying on his prison bed being spooned by a 300-pound SLEEPING INMATE.
The two Detectives and an apoplectic Ted walk down the hallway.
DETECTIVE FRANEK At exactly 10:48 this morning a man was apprehended not far from where you were arrested.
DETECTIVE FRANEK He was identified as an escaped mental patient and subsequently confessed to the murder that you were being held for.
DETECTIVE FRANEK Lab tests confirmed a fingerprint match on the bag.
TED So...I'm free to go?
Detective Cavallo stops and holds out his hand.
DETECTIVE CAVALLO No harm, no foul?
TED I guess.
Still traumatized, Ted shakes the man's hand, then mopes toward the door.
DETECTIVE FRANEK By the way, there's somebody here to see you.
Dom is driving; a bruised and somber Ted is in the passenger seat.
DOM You are one lucky sonofabitch, you know that?
TED I am?
DOM Didn't they tell you?
DOM That hitcher was just about to cut your throat when you stopped to take a leak.
DOM You got a fucking horseshoe up your ass, man.
TED Yeah feels like it.
Ted grimaces and shifts in his seat.
TED (cont'd) How the hell did you get here anyway?
DOM Flew.
DOM Told my wife I was going to a Promise Keepers convention.
Ted gives him a look.
DOM (cont'd) I hate to ruin your day, Ted, but I have some bad news for you.
Ted SIGHS.
TED Shoot.
DOM Remember our friend Healy?
DOM Well, I didn't know where to mail his last paycheck so I sent my assistant by his mother's apartment.
DOM Turns out there is no diabetic mom.
DOM Landlord said she's been dead for ten years.
TED And this adversely affects me how...?
DOM Don't you see?--Healy lied to us about <U>everything</U>!
DOM The landlord said when he got back from Miami he kept talking about falling for some doctor named Mary!
Ted is stunned.
TED Huh?
TED What?
TED No...<U>My Mary</U>?
TED Mary wouldn't go for him....would she?
Dom hands Ted a SLIP OF PAPER.
DOM His address in Miami.
DOM You know, when you think about it, we really don't know the first thing about this guy.
Finally the implications of this dawn on Ted.
TED Jesus Christ what have I done?
A confused Mary and her girlfriends are in the apartment while Magda listens to the radio scanner in the b.g.
LISA You're not seriously thinking about going out with this guy again?
JOANNIE Mary, he sounds like a psycho!
MAGDA Would you hens quit ya cackling and let her do what she wants to do.
MAGDA Puffy liked him and Puffy's never wrong.
The girlfriends roll their eyes.
BRENDA Mary, the guy's full of shit.
MARY What if he's not?
MARY What if Tucker just made an honest mistake?
LISA What if he didn't?
It's clear that Mary is torn.
MARY I don't know how I can bail now, he's going to be here any minute.
JOANNIE Well then blow him off when he gets here.
MARY But you didn't meet him.
MARY He seems so I don't know...perfect...kind of.
BRENDA He has a big cock, doesn't he?
Mary shoots Brenda a look.
MAGDA Hey hey, what did you say Pat's last name was?
MARY Healy.
Magda's eyes almost come out of her head.
MAGDA I think you better listen to this.
Magda turns up the volume on her scanner and we can clearly hear Healy TALKING ON HIS CELLULAR PHONE.
Mary and her girlfriends gather around.
SULLY (V.O.) So where the hell are you, Healy?
HEALY (V.O.) Ah, I got a date tonight with that Mary girl I told you about.
SULLY (V.O.) The sawbones?
HEALY (V.O.) Yep.
The girls all look at one another.
BRENDA We hit the motherlode.
MARY We shouldn't be listening to this.
LISA AND JOANNIE Shhh.
SULLY (V.O.) She still think you're a fucking architect?
HEALY (V.O.) Oh yeah.
SULLY (V.O.) Dumbshit.
LISA Mr. Perfect, huh?
Mary starts to feel like a fool.
MARY Turn it up, Magda.
HEALY (V.O.) Hey, watch your mouth--she's a great gal.
HEALY (V.O.) I'm the dumbshit for lying to her.
SULLY (V.O.) Why didn't you just tell her the truth?
HEALY (V.O.) I don't know.
HEALY (V.O.) I guess...it just seems that women today are more impressed by the mighty buck than by some schmo who spent the last seventeen years scraping by on Peace Corp wages.
The girls all seem moved by this.
Healy is parked out front, the phone in one hand, a SCRIPT in the other, as he listens to Sully read the following words:
SULLY (V.O.) But Jesus, Pat, if she's as special as you say, she's going to want to hear about the things you did.
HEALY Ahh.
A disheveled and wired-looking Sully is sitting on the couch in his underwear READING FROM THE SAME SCRIPT.
There's COKE on the table, DOG SHIT on the floor, and FLIES everywhere.
In the B.G. we see the Great Dane SNIFFING at his empty bowl and the Boa Constrictor sprawled out on the floor, barely moving.
SULLY Come on, you could tell her about the irrigation ditches you dug in Sudan, the orphan babies who cried in your arms in Romania...
SULLY ...the hope you gave Freddie the leper in Calcutta...
Suddenly the dog snatches the page out of his hand and STARTS TO
<U>BACK ON</U> Mary and friends.
JOANNIE I love this man.
Magda folds her arms and gloats.
HEALY Look, I did all those things for myself.
HEALY I'll be honest with you, I'm a selfish prick.
HEALY I get a high from helping all of God's creatures.
HEALY An honest to goodness high.
Just then, Healy sees a bug on the car window and instinctively squashes it.
<U>ON SULLY</U> - he has the phone wedged between his cheek and shoulder as he STRUGGLES with the dog to get the script.
Sully still can't retrieve the script, nor his next line.
SULLY That's bullshit, man you, uh, you were on the front line.
SULLY Remember the, uh, malaria the, uh, typhoon fever that vicious strain of genital herpes?
<U>ON MARY AND FRIENDS</U> - they flinch at this.
<U>ON HEALY</U> - he stares at the phone, horrified.
HEALY (V.O.) Uh, sure.
HEALY (V.O.) I cured a lot of nasty illnesses in third-world countries.
<U>ON MARY AND FRIENDS</U> - as they let out a sigh.
HEALY (V.O.)
(cont'd) The bottom line is, I'm not going to use my philanthropy as some form of currency...especially after what I did.
HEALY (V.O.) I lied to this poor girl.
HEALY (V.O.) Lied.
HEALY (V.O.) man.
HEALY (V.O.) She deserved better.
SULLY (V.O.) Hey, love will make you do fucked-up things.
HEALY (V.O.) You said it, mister.
HEALY (V.O.) I gotta go.
<U>ON SULLY</U> - as he HANGS UP the phone and does another line, we
<U>PAN TO</U> the Great Dane Hal as he looks around for something, anything to eat.
He SNIFFS at a sock, then a beer bottle, before finally setting his sights on the Boa Constrictor Bill.
Bill glances the dog's way nervously, SENSES TROUBLE, and wiggles his way into another room.
As Hal TAKES OFF after the snake, we
Healy starts to knock on Mary's door, but, before he can, the door suddenly swings open revealing a beaming Mary.
HEALY Oh Mary.
HEALY Look, there's something I have to tell you.
HEALY I'm not
Before he can finish, Mary steps forward and their mouths meet in a passionate KISS.
</U>--As Mary watches, Healy plays TOUCH FOOTBALL with Warren and a few of his friends.
Healy catches a pass then, trying a little too hard to impress Mary, he delivers a forearm shiver to his defender and gives Warren a vicious STRAIGHT-ARM.
When Healy gets into the end zone he spikes the ball and starts talking trash to another defender.
--Healy shows up at Mary's door sporting a set of OVERSIZED INCREDIBLY-WHITE CAPPED TEETH.
He gives her a big horse smile and she reacts uncertainly.
--Healy is in Mary's apartment as Mary finishes dressing for a night on the town.
MARY All set.
HEALY You look great.
HEALY Hey, Mare, do I have a rip in the back of these pants?
When she puts her head close to inspect his pants, he lets fly a THUNDEROUS FART.
She pulls her head away, repulsed, but Healy just
--Mary and and the horse-toothed Healy are having dinner in a romantic restaurant.
As he eats he tells an animated story but he's having trouble with the new choppers and chunks of food are spraying out of his mouth with every word.
Mary has to BOB AND WEAVE to avoid being covered with debris.
--Healy and Warren are playing monopoly.
When Warren isn't looking, Healy cheats and puts a couple hotels on Boardwalk.
In the b.g.
we see one of Warren's buddies fall out of a palm tree.
A lovesick Healy is mauling Mary out on the sidewalk in front while Warren stands off to the side LISTENING TO A WALKMAN.
<U>REVERSE ANGLE</U> reveals a devastated Ted and Dom watching this from Ted's car.
TED Fuck me.
TED Let's go home.
DOM No!
DOM You've gone through way too much to back down now.
DOM Get over there and do something--I can't stand watching this.
<U>BACK ON MARY AND HEALY</U> as Healy starts OVER-DOING IT and Mary has to break it off.
MARY Whoa, whoa, how's my stomach taste?
Healy LAUGHS.
HEALY How's my stomach taste, she says.
HEALY Hey thanks for picking up the lunch tab, Mare.
HEALY Sorry I forgot my wallet.
HEALY I feel like a dog.
MARY Forget it.
MARY It was...fun.
</U>Ted recognizes Warren.
TED Holy shit, there's Warren.
</U>Suddenly we see Warren PERK UP at something.
WARREN Franks and beans!
Jesus, I think her brother spotted me.
They both duck down in their seats.
Beans and franks.
MARY Give it a rest, War.
MARY You just ate.
HEALY Aw, leave him alone, he's just got a big appetite.
HEALY Am I right?
Healy winks at Mary.
WARREN Huh?
Healy reaches over and lifts a headphone off Warren's ear.
HEALY I said you've got a big app--
Suddenly Warren SUCKER-PUNCHES HEALY IN THE THROAT.
HEALY (cont'd) Urrggghh...
MARY Warren!
<U>ON TED AND DOM</U> - as they flinch.
DOM Attaboy!
<U>BACK ON MARY et al</U> - Healy holds his throat, clearly in pain.
MARY Are you okay?
HEALY (cont'd) Not to worry.
HEALY (cont'd) So...see you tonight, right?
HEALY (cont'd) Right?
MARY Sure.
Mary watches with a look of concern as Healy gets in his car and drives off.
</U>Ted stares gazily.
DOM Well?
DOM What are you waiting for?
TED I don't know what to say.
DOM Tell her the truth about Healy!
DOM Blow the schmuck out of the water.
TED Are you crazy?
TED I've unleashed a psycho on her.
TED She's gonna be fucking pissed.
TED She's even more beautiful than I remember.
<U>THEIR POV</U> - Mary and Warren start to go in the apartment.
DOM Get over there, you pussy!
DOM She's leaving!
Suddenly Dom HONKS THE HORN, then ducks down.
Mary turns around and sees Ted.
TED You asshole, what are you--
TED Mary!
TED Is that you?
MARY Who's that?
Ted gets out of the car and hustles across the street toward Mary.
TED It is you!
TED It's me...Ted.
TED From Rhode Island Ted.
Finally she recognizes him.
MARY Oh my God...Ted.
MARY What are you...?
MARY I can't believe this.
MARY I haven't seen you since--
TED Yup, that's right.
TED Junior prom...kinda.
MARY And did everything--?
TED Oh yeah, healed right up.
TED No visible scars.
Mary LAUGHS.
TED (cont'd) How are you doing, Warren?
WARREN Good, Ted.
WARREN Piggy back ride?
TED I'm gonna take a rain check.
Mary is stunned.
MARY I can't believe he remembered you.
MARY He never remembers anybody.
MARY You know I tried to call you for weeks after that.
TED Really?
TED I never got a message.
MARY That's weird.
MARY I talked to your brother Jimmy five or six times.
Ted is devastated to hear this.
MARY (cont'd) By the way, how's he doing?
TED He's dead.
MARY Oh, Ted I'm so sorry to hear that.
TED No, it was a good thing.
TED I mean, good in that it was very quick.
Ted pantomimes an explosion.
MARY Oh.
MARY So...what brings you down here?
TED Funny story.
TED You see, me and a buddy of mine decided to...ah...you know...just ...drive down.
She stares at him.
MARY Well you look great.
MARY Are you married, do you have kids?
TED Nope, nope--dodged a few bullets.
TED God, I cannot believe I'm standing here with Mary Jenson.
MARY Actually, it's Mary <U>Brooks</U> now.
TED Oh...are you...?
MARY Nope, haven't walked the plank yet.
MARY There was this guy back in college who was bothering me...got kind of ugly--a restraining order, the whole bit.
MARY Anyway, when I got out of Princeton I changed my name as a precaution.
TED Jeez...that sounds awful.
TED Hey, what do you say we go out to dinner tonight, catch up on old times?
MARY Didn't we just do that?
Ted doesn't know how to respond to this and then she smiles.
MARY (cont'd) I'm kidding.
MARY (cont'd) I'd really love to, Ted, but the thing is I already have plans.
MARY (cont'd) How about tomorrow night?
TED Mary, we haven't seen each other in twelve years.
TED Don't make me wait another day.
Mary seems touched by this.
MARY Tell me where you're staying.
MARY I'll pick you up at eight.
Ted finally smiles and we
A content Healy is parked out front of Mary's apartment, absently listening to her spill her guts to Magda while he reads the newspaper.
MAGDA (V.O.) I'm buying bananas tonight.
MARY (V.O.) Why?
MAGDA (V.O.) Back when I was your age I always used to make myself a big banana split after sex.
MAGDA (V.O.) I think you're gonna need one tonight.
MARY (V.O.) Don't get ahead of yourself.
MARY (V.O.) You'll probably need it before I will.
Mary is skipping around the apartment while Magda sits on the couch.
MAGDA Don't bet on it.
MAGDA Last time I had a pap smear the guy needed leather gloves and an oyster shucker.
MARY So maybe I could find a nice gentleman to take you to the movies.
MAGDA Knock it off, Pollyanna, just 'cause you're in love doesn't mean everyone else has to be.
MARY Love?
MARY Come on, I wouldn't call it love.
MAGDA Oh no?
MAGDA I ain't seen you beaming like this since you broke ninety on the Blue Monster.
<U>BACK ON HEALY</U> - he's reveling in it all.
MARY (V.O. ) Well I am pretty psyched.
MARY (V.O. ) I ran into a guy today I hadn't seen since high school.
Healy loses the smile and sits up.
MAGDA (V.O.) An old flame?
MARY (V.O.) Kind of.
MARY (V.O.) Ted Peloquin--one of the sweetest guys in the world.
Healy TURNS UP THE VOLUME.
He was so shy and clumsy...I had a major crush on him.
<U>BACK ON HEALY</U> as he nearly puts his head through the roof.
He grabs hold of the steering wheel and pounds his head on it.
HEALY No!!!!!!!!!!!!!!!!
HEALY MARY (V.O.)
HEALY (cont'd) We're gonna go out tonight.
HEALY Oh, that reminds me, I've got to call what's-his-face and cancel.
Do I sense a chill in the air?
Mary sits down.
MARY Oh, Magda, I let my head get in the way of my love life.
MARY I always pick guys on what I feel in here.
MARY But with this Pat guy my head kept saying &quot;Grow up, Mary.
MARY You have a lot in common with this one, you'll grow to feel something for him.&quot; But it never happened.
<U>ON HEALY</U> - he couldn't look more crushed.
Suddenly his cellular phone RINGS.
He stares at it for TWO, THREE, FOUR RINGS.
Panic-stricken.
Then he answers it.
HEALY Hey, Patty-boy here.
HEALY Sorry I missed ya, but I'm out rustling up some champagne and roses in preparation for the greatest birthday of my life.
HEALY Hope you and yours are having a good day, too.
Healy makes a BEEP sound and then holds his breath.
<U>ON MARY</U> - she stares at the phone, feeling cornered.
MARY Uh, hi Pat, it's me, Mary.
MARY Just wanted to say I'm...looking forward to tonight.
She hangs up.
MAGDA You vicious bitch, how do you sleep at night?
MARY I can't do it--I just found out it's his birthday.
MARY I guess I've gotta cancel on Ted.
<U>ON HEALY</U> - he blows imaginary smoke off an imaginary gun.
Then he sits back and smugly listens to her DIAL THE PHONE.
But then he hears something that concerns him--a KNOCK on the door and the dog
<U>ON MARY</U> - she puts down the phone and answers the door.
It's Tucker, the architect.
MARY Tucker...come on in.
<U>BACK ON HEALY</U> pulling his hair out.
He's on an emotional roller coaster heading downhill.
MAGDA (V.O.) Well look who's here.
<U>BACK TO MARY'S APARTMENT</U> - Tucker is carrying an unopened BOTTLE OF SCOTCH and absently flicking the YAPPING pooch off his ankles.
TUCKER There she is--I brought you a little thirst-quencher, Mag.
MAGDA Oh, you are sweet.
TUCKER No, I'm not.
TUCKER I just want to get you-drunk so you'll pass out and I can have my way with Mary.
Everyone LAUGHS.
MARY Can I pour you one?
TUCKER Thanks, but I've got to be going.
TUCKER Unfortunately, Doc, this isn't a social visit.
Tucker's tone shifts and Mary grows concerned.
MARY What's up?
TUCKER Well...I've got a little more news about your friend Healy.
Mary seems relieved.
MARY I know what you're going to say, but he already told me everything.
MARY I know he's not an architect.
Tucker pulls out a piece of paper.
TUCKER (cont'd) I think you'd better sit down.
MARY Tucker, I appreciate you doing all this, but I'm really strapped for time here and--
TUCKER Mary, the man's a killer.
<U>ON HEALY</U> - he can't believe his ears.
<U>BACK ON MARY</U> - as she lowers herself onto the couch.
MARY What...?
TUCKER I've got a friend in the Boston police department.
TUCKER He faxed me this this morning.
TUCKER I'll just give you the highlights.
TUCKER After a short stint as a petty thief, Patrick R. Healy graduated to armed robbery by the age of fourteen.
TUCKER At sixteen he committed his first murder--a pretty teacher's aid named Molly Pettygrove.
TUCKER He was incarcerated until age twenty-two when, despite a grim psychological profile, the state was forced to release him.
TUCKER In his mid-twenties and again in his early thirties he was suspected of homicides in the states of Utah and Washington.
TUCKER Unfortunately, the bodies were so badly decomposed that there wasn't enough evidence to hold him, and on and on and so forth and so on.
Mary looks like she's going to throw up.
<U>ON HEALY</U> - he listens intently, his face ashen.
MARY (V.O.) Holy shit...
MAGDA (V.O.) Puffy, get over here.
We hear the PITTER-PATTER of the dog's nails on the floor, then a LOUD THUMP followed by a YELP.
Magda!
MAGDA The little shit lied to me about that guy!
Mary picks up the startled dog and pets him.
MARY I can't believe this is happening.
MARY I'm supposed to be meeting him in an hour.
TUCKER Okay, just calm down.
TUCKER It's going to be okay.
Tucker puts his arms around her.
MAGDA Why you two never hooked up is beyond me.
Mary looks fondly at Tucker.
MARY Magda's right, I'm so lucky to have you in my life.
TUCKER Don't get all gooey on me now, you'll give me a big head.
TUCKER The important thing, Doctor, is you've got to distance yourself as much as possible without pissing this psycho off.
MARY Yeah, yeah.
MARY Okay, I think I know what to do.
MARY I'll call him right now.
<U>BACK ON HEALY</U> - he looks stunned.
His cellular PHONE RINGS.
He stares at it, then picks it up.
HEALY Hi, I'm out drinking champagne and roses...and I'm really happy.
HEALY Leave a message.
HEALY BEEP.
MARY (V.O.) Uh, hey buddy.
MARY (V.O.) Oh boy, am I pissed.
MARY (V.O.) You're not going to believe this--well, you'll believe it, there's no reason not to--but I just got beeped for emergency surgery.
MARY (V.O.) Well, um, sorry, but I'm going to have to bail on you.
As we hear a CLICK, Healy stares at the cell phone, seething.
Tucker comes out the front door, looks around, then walks off down the sidewalk.
<U>ANGLE ACROSS THE STREET</U> - on Healy, his steely gaze fixed on Tucker.
HEALY You're gonna pay, fucker.
Healy discreetly pulls out and slowly follows Tucker in his car.
<U>BACK ON TUCKER</U> - He continues down the sidewalk, looking back once or twice, apprehensive.
He rounds a corner, then stops next to an OLD FORD PINTO.
He looks around nervously again.
Then Tucker DUCKS INTO THE DRIVER'S SEAT and DRIVES OFF.
Healy pulls into traffic and follows.
Dom's mixing a drink while Ted paces nervously.
TED Oh God, I'm fucking nervous.
TED I don't know if I'm ready for this, man.
DOM Just relax.
DOM Have you hit the cash machine?
TED Got cash.
DOM Car clean?
DOM Plenty of gas?
TED Check.
DOM Mints?
TED Copped a tin of Altoids at the car wash.
Dom nods, satisfied.
DOM Okay, sounds like you're all set.
DOM Just clean the pipes and it's a go.
TED Hm?
DOM You know, clean the pipes.
TED Pipes?
TED What are you talking about?
DOM You jerk off before all big dates, right?
DOM Tell me you jerk off before your big dates.
Ted just stares at him.
DOM (cont'd) You don't jerk off before--?!
DOM (cont'd) Are you crazy?!
DOM (cont'd) That's like going out there with a loaded gun.
DOM (cont'd) No wonder you're nervous!
Ted considers this.
DOM (cont'd) Think about it: After you've had sex with a girl and the two of you are laying in bed, are you nervous?
TED No.
Dom shrugs...Duh.
DOM Why's that?
TED I'm usually too tired to be.
Dom makes a game-show BUZZER sound.
DOM Wrong.
DOM It's because you ain't got the baby batter in your brain any more.
DOM That'll fuck with your head, that stuff will.
TED Huh.
DOM The most honest moment in a man's life is the five minutes after he's blown a load.
DOM That's a medical fact.
DOM And it's because you're no longer trying to get laid.
DOM You're actually thinking like a girl.
DOM They love that.
TED Jesus Christ you're right.
DOM You bet your ass I'm right.
DOM You don't go out with a loaded gun, you empty the barrels!
TED Holy shit, I've been going out with a loaded gun!
DOM People get hurt that way.
Dom walks out of the lobby just as another cab arrives and Mary gets out.
He sees and her and ducks behind a bush as she walks past him.
Ted has a newspaper splayed out on the counter (open to the bra ads) as he furiously FLOGS THE DOLPHIN (chest-high side view.)
We see some balled-up tissue nearby.
After several frantic strokes, he takes a deep breath and slowly and loudly EXHALES, clearly having COMPLETED HIS MISSION.
He draws a few more breaths, picks up a face cloth, and goes to clean up.
But something's missing: The Load.
Ted looks down, checks his hands, pants, shoes, looks in the sink, finally glances at the ceiling, with no luck.
<U>The Load IS MISSING</U>!!!!
That's when the doorbell RINGS.
Ted couldn't look more HORRIFIED.
As he buckles his pants, he makes a last, panicky reconnaissance of the area.
The doorbell RINGS AGAIN and Ted reluctantly goes to answer it.
Ted opens the door and Mary is standing there looking as lovely as ever.
TED Hey.
MARY Hi, Ted.
TED You look great.
MARY Thanks.
She notices something.
MARY (cont'd) What's that?
TED Hm?
MARY On your ear, you've got something.
<U>MARY'S POV</U> - a HUGE LOAD is hanging off of Ted's earlobe like a drop earring.
MARY (cont'd) It looks like a gob of...
Mary leans forward for a closer look.
Ted is terrified.
MARY (cont'd) Is that....hair gel?
TED Sure.
MARY Oh great, I ran out.
Before Ted can stop her, Mary grabs The Load off his ear and WIPES
Healy is still following Tucker in his car.
Finally Tucker stops in front of a lavish Victorian home and gets out carrying a pizza and wearing a PIZZA DELIVERY HAT.
Healy SCREECHES to a sideways stop, jumps out and POUNCES ON HIM.
HEALY (cont'd) You motherfucker, you're a dead man!
Tucker drops the pizza as Healy SLAMS HIM into a tree.
TUCKER Okay, Pat, take it easy--don't do anything stupid.
HEALY Who the fuck do you think you are making up that bullshit about me?!
Healy SLAMS HIM AGAINST THE TREE AGAIN.
TUCKER Whoa, whoa--I don't know what you're talking about.
HEALY Maybe this'll jog your memory.
Healy SLAPS him across the face.
HEALY (cont'd) I'll give you a hint--it's got something to do with me being a murderer.
Healy raises his arm again and Tucker tries to shield himself.
TUCKER Okay, okay, I might've gotten some bad information.
Healy grabs him by the collar.
HEALY That stalker Ted got to you, right?
HEALY You're working for him, aren't you, you little shit?
TUCKER Who?
Healy throws Tucker to the ground and takes off his sport coat.
HEALY This is your last chance, you fuck.
HEALY Now either you come clean or I'm going to kick your ass from here to Tallahassee.
Healy grabs Tucker by the hair and cocks his arm.
Tucker suddenly gets emotional.
Healy stops and looks at him.
HEALY You what?
TUCKER You heard me, goddamnit.
TUCKER I...I love her.
Healy slowly lets go.
TUCKER (cont'd) I'm a phony--just like you, man.
HEALY What do you mean?
TUCKER I mean I'm a fucking fraud.
TUCKER I'm no architect.
TUCKER Don't be a putz--who's been to Santiago twice in a year?
TUCKER <U>Estadio Olimpico</U>--please!
HEALY But...but you knew people at Harvard.
TUCKER I knew shit.
TUCKER The only thing I knew was that you were a fake and I made up everything else.
TUCKER My real name's Norm.
TUCKER I deliver pizzas.
HEALY Bullshit!
Tucker rolls his eyes and pulls out his PIZZA DELIVERY BADGE, with him pictured beside the name Norman Plante.
As Healy let's this sink in, we
Ted's rolling a little wine around in a glass.
He takes a sip, nods his approval.
TED Thanks, that's great.
The WAITER turns to Mary.
WAITER Madame?
<U>ANGLE ON MARY</U> - The light, puffy bangs that Mary started the night with are gone, replaced by a glazed, ACE VENTURA-STYLE WAVE up front.
MARY Thank you.
The waiter pours her a glass and leaves.
TED Now by <U>killer</U>, you mean...?
MARY I mean he murdered someone and did time back in Boston.
MARY The guy's a freak.
TED Jeez, Mary...I'm...
MARY Well, lucky for me I found out.
MARY Thank God I have friends like Tucker.
MARY Look, I'm sick of talking about stalkers.
MARY Let's talk about you.
Healy and Tucker are bonding over a beer.
TUCKER ...So then in '94 I went back to Dade Community College for a semester and when the Wal-Mart cashier job fell through I hooked up with the Pizza Barn.
HEALY And you met Mary how?
TUCKER Just dumb luck.
TUCKER I delivered a pie to her one night and she answered the door in her nightgown--that was it for me.
TUCKER I went home that night, shaved my beard, and a week later I was laid out in her office with a broken back.
HEALY How'd you manage that one?
TUCKER Friend.
TUCKER Baseball bat.
HEALY Nice.
TUCKER Oh yeah, the plan was going along just fine until you showed up.
HEALY Hey, hey, hey, I'm not the one who started telling bald-faced lies about the competition--that's crossing the line!
TUCKER What line?
TUCKER The day you first laid your oily rap on my future wife you started a war!
HEALY <U>Future wife</U>?
HEALY Get real, man--you're nothing more than a glorified brother in her eyes.
TUCKER Why you son of a--
Tucker grabs Healy by the jacket.
HEALY Okay, calm down, calm down--the bottom line is neither of us are going to get her if we don't do something about that headcase she's with now.
As Tucker slowly releases him, we
Ted and Mary are eating CORNDOGS at the snack bar.
MARY You hit the ball pretty good for a fourteen.
TED No short game.
She smiles.
MARY We should play some time...I mean, if you can afford to lose some money.
TED What are you?
MARY Twenty-two.
TED Bullshit, a twenty-two doesn't carry a one-iron--don't sandbag me, lady.
Mary smiles coyly.
MARY Okay, sometimes I'm a nineteen.
TED That's more like it.
TED Two more nitrate-sicles please.
COUNTER-MAN You got it.
Mary is amused by this.
MARY Nitrate-sicles--I like that.
TED I say they should put more meats on a stick, you know?
TED They got a lot of sweets on sticks--popsicles, fudgesicles, lollipops--but hardly any meat.
MARY I agree there should be more.
The Counter-Man hands each of them another corndog.
TED You know what I'd like to see?
TED Meat in a cone.
TED You could put corned beef hash in a cone, or chopped liver.
MARY I like it.
MARY And think of the toppings--cheese, mushrooms, mint jelly
TED Not to mention ketchup and hot peppers.
They smile at one another.
MARY It's too bad you don't live down here, Ted.
TED Yeah?
MARY We've got a lot in common.
Ted takes a chance.
TED Well...why don't you move back?
MARY Ah, my roots here are too deep.
MARY I love my practice, the people I work with, Warren's got a nice thing going
MARY Why don't you just move down here and marry me?
Mary smiles and Ted LAUGHS...perhaps a little too hard.
Ted and Mary are sitting on her front stoop SMOKING A BONE.
MARY So you're a writer?
TED Trying to be.
MARY Well good for you.
MARY I bet it works out for you.
TED We'll see.
TED If it doesn't, what the hell, at least I gave it a shot.
MARY That's right.
MARY And the good thing is you can do it anywhere.
TED What about you, Mare?
TED How the hell'd you manage to stay single?
MARY I don't know...My friends think I'm too picky.
MARY I think I'm just a weirdo magnet.
MARY I did come close once--just last year, in fact.
MARY There was this guy he lived in San Francisco.
<U>ANGLE ON</U> the corner of building.
We see Healy and Tucker SPYING ON THEM from the shadows.
TUCKER That stalkin' son-of-a-bitch!
HEALY Fucking sickening.
Healy and Tucker duck back into the alley.
Healy is throwing DOGGIE TREATS through an open THIRD-FLOOR
We hear the TELEVISION and see Magda DOZING on the couch with a watery COCKTAIL IN HER HAND and the dog Puffy at her feet.
Suddenly a DOGGIE TREAT flies through the window, landing on the rug.
Puffy SNAPS TO ATTENTION and approaches the treat.
He sniffs it, then GOBBLES IT UP.
ANOTHER doggie treat lands beside him and he eats that, too.
Then ANOTHER.
Tucker keeps throwing the treats up and Healy looks concerned.
HEALY How many is that?
TUCKER Four.
HEALY That seems like a lot of speed for a little pooch--you sure it won't kill him?
TUCKER I never said that.
As Tucker throws another...
The doggie treat LANDS IN MAGDA'S COCKTAIL, waking her up.
Magda looks around, gets her bearings, and then DOWNS THE DRINK!
Mary and Ted, still sitting on the stoop.
Mary seems a little reflective.
MARY ...
MARY and then it was all over.
MARY We haven't spoken since.
TED Wow.
TED That's too bad.
TED He sounds almost perfect.
MARY Yeah...almost.
MARY You want to come up and watch Sportscenter?
TED Uh no.
TED I think I'm gonna get out while I'm ahead.
Mary looks a little disappointed.
MARY Ted...you're not that far ahead.
TED Look, Mary, the truth is...I'll be in town for a while now but I don't think we should see each other for a few weeks.
MARY Why not?
TED Well...to be honest....I'm really crazy about you and it's making me nervous and when I get nervous I'm not myself and I'm afraid I'm going to doing something really dumb before we get started so I think I should just lay back until I regain my composure.
Mary sort of smiles.
MARY That's really sweet, Ted, but you should save it for one of your books.
TED All right, let's go.
Ted jumps up and starts up the stairs two at a time.
As Ted and Mary ENTER, we see Magda HOLDING UP THE COUCH with one hand and VACUUMING WITH THE OTHER.
Mary doesn't know what to make of it.
MARY Magda, what are you doing?
Magda turns off the vacuum and we hear a BANGING SOUND coupled with the O.S. MUFFLED YAPPING of Puffy.
MAGDA Oh, hi hon.
MAGDA Just straightening up.
MARY Where's Puffy?
MAGDA Ah, he was being a pest so I put him in the bathroom.
As the O.S. YAPPING AND BANGING continues, Magda PICKS UP THE TELEVISION and starts DUSTING the TV stand.
MARY Um, Ted, I need a moment with Magda--would you let the dog out of the bathroom.
TED Yeah, sure.
Ted walks down the hall, following the YAPPING AND BANGING SOUND until he comes to the bathroom door.
The YAPPING is MUCH LOUDER now and he NOTICES SOMETHING THAT MAKES HIM HESITATE.
<U>TED'S POV</U> - the bottom part of the door is being DENTED OUTWARD from the force of something BATTERING IT FROM WITHIN.
TED Uh, Mare, what kind of dog is Puffy?
MARY Toy poodle!
Ted thinks about this, shrugs, and opens the door.
BARING HIS TEETH like a Rottweiler, Puffy SPRINGS at Ted's jugular!
Ted stumbles back into the living room with the hopped-up dog ON HIS FACE.
He KNOCKS OVER A LAMP, tumbles onto the floor, and fights for his life.
Mary and Magda SCREAM as Ted and Puffy mix it up on the floor.
Ted tries to CRAWL TOWARD THE DOOR but Puffy GRABS THE CUFF OF HIS
<U>DOOR POV</U> of Ted's anguished face as he gets pulled back into the room.
Ted manages to GET THE DOG IN A HEADLOCK.
MAGDA Stop it, you're hurting him!
TED Tell him...to calm down.
Puffy gets a piece of Ted's wrist and Ted SCREAMS and drops him.
Both man and toy poodle SPRING TO THEIR FEET.
They start CIRCLING ONE ANOTHER.
Puffy leaps at Ted and Ted SMACKS HIM into a wall.
Unfazed, the dog gets a running start and LEAPS
Ted manages to duck and PUFFY FLIES OUT THE OPEN WINDOW!
</U>--Ted and Warren are at the top of a giant WATER SLIDE Warren motions that he has decided this is not for him.
Ted shoots him a look that makes Warren feel like a sissy.
Convinced it's not too dangerous, Warren decides to go for it and Ted follows.
--At the bottom of the slide Ted splashes into the huge pool of water, laughing, having a blast.
Then he looks
around...no sign of Warren.
Concerned, Ted dives underwater and a moment later Resurfaces clutching a GASPING Warren.
--Mary pumps Warren's stomach as he coughs water out of his mouth.
Ted looks on sheepishly.
Ted and Warren walk down a city sidewalk.
As they pass a shop Warren points to the window excitedly.
In the window there is a mannequin dressed in a Super- hero outfit, i.e.
a generic superman.
Warren then pulls Ted into the store.
Ted comes out followed by a beaming Warren dressed in the Super-Hero outfit.
They continue walking again and a few steps later Warren excitedly points to another shop window.
In the window is a mannequin dressed in a cowboy outfit, i.e.
Lone Ranger (hat, badge, holster, chaps, vest, boots, spurs, etc.)
Again, Warren pulls Ted into the store.
Mary is window shopping with a few bags in hand.
She turns and reacts amused.
Warren is now dressed in the cowboy outfit and a humiliated Ted follows dressed in the loose fitting Super-hero outfit.
--Ted and Mary are walking arm and arm on a SCENIC PIER where PEOPLE ARE FISHING.
Right behind them are Magda and Herb (the Homeless guy) enjoying one another's company.
Ted is on top of the world, feeling good, looking good-right up until he gets the HOOK IN HIS MOUTH.
Suddenly he gets YANKED OUT OF FRAME.
--Ted is FLOPPING AROUND on the pavement and a FISHERMAN has his FOOT ON HIS FACE as he STRUGGLES TO REMOVE THE HOOK.
Mary looks on, concerned.
--Ted and Mary come out of the grocery store each HOLDING A COUPLE BAGS.
Ted also is CARRYING PUFFY, IN A BODYCAST.
Ted PUTS PUFFY ON THE ROOF, then starts putting the groceries in the back seat.
--Mary pulls her car up in front of her apartment.
AS Ted gets out of the passenger's side, he notices that PUFFY IS STILL ON THE ROOF.
He quickly GRABS PUFFY before Mary notices.
--Warren is futilely taking swings in a BATTING CAGE while Mary looks on helplessly.
Finally Ted goes into the cage, SIGNALS THE GUY TO STOP THE PITCHING MACHINE, and MOVES WARREN A LITTLE CLOSER TO THE PLATE.
--A distraught Ted SITS SOMBERLY on a bench.
Beside him, Mary comforts Warren whose LEFT EYE IS BLACK AND BLUE AND COMPLETELY
Ted shows up at Mary's apartment door carrying a BOUQUET OF FLOWERS and a BASEBALL.
When he KNOCKS, the door opens.
Ted peeks around the corner and sees a SOMBER Mary sitting on the couch.
TED Hey.
Mary doesn't look up.
Ted ENTERS, revealing his gifts.
TED (cont'd) The flowers are for you and the ball's for Warren.
TED (cont'd) I had a friend of mine Fedex it to me--it's signed by Tony Conigliaro.
Mary finally looks up but doesn't smile.
MARY Did you hire Pat Healy to follow me around?
Ted tries to hide his horror.
TED What do you mean?
Mary picks up a letter off the coffee table and hands it to him.
Ted takes a quick look and then drops it on the table.
MARY It's not true...right, Ted?
Ted CLEARS HIS THROAT.
TED Well, funny story there.
TED You see, uh, it started out as a uh...yeah...it's true.
Mary stands up.
MARY Get out.
TED Wait, hold on, Mary--it's not as bad as it sounds.
TED I certainly didn't know--
MARY That you put a murderer on my trail?
TED Well yeah, I didn't know much about him.
TED I just thought--
MARY What did you think, Ted?
MARY That you could spy on me and trick me into thinking you were someone I could...really go for?
Mary starts to get emotional.
TED Mary, I swear I wasn't trying to trick you.
MARY Then what the fuck did you do it for?
TED I did it because because I'd never stopped thinking about you and if I didn't find you I knew my life would never be good again.
Mary looks away.
MARY Please leave.
TED Mary, come on...
MARY Go!
TED Okay.
And so Ted does.
Ted comes out of the building, a broken man.
He paces back and forth on the sidewalk, manic with despair.
Then he seems to grow angry.
He rifles through his pockets until he finds a SLIP OF
<U>TED'S POV</U> - the paper reads: 'Healy's Miami address--229 Court Street, apt.
43.'
Ted walks down a rather dark hallway until he comes to apartment 43.
He KNOCKS on the door but no one answers.
He tries the handle and THE DOOR OPENS.
Ted ENTERS and immediately reacts to the STENCH.
<U>REVERSE ANGLE</U> reveals that the place is a fucking PIG-STY.
DOG SHIT is everywhere, FLIES fill the room, a MOUSE scampers across the carpet.
TED Hello...?
No answer.
Suddenly he HEARS SOMEONE out in the hall, so he ducks behind the door.
Healy and Tucker ENTER the apartment and stop in their tracks when they see the MESS.
HEALY Ho-ly shit.
TUCKER Hey, this is a pretty nice place.
HEALY Sully...!
HEALY What the fuck happened here?!
Again, no answer.
Suddenly Ted SLAMS THE DOOR shut and grabs Healy by the collar.
HEALY (cont'd) Hey, hey, hey!
TED Surprised?
TUCKER Hey, buddy, don't do anything rash now.
TED Who the fuck are you?
HEALY He's in love with Mary, too.
Ted releases Healy and glares at him.
TED You fucked me, man?
TED Why would you do that?
HEALY What do you mean 'why'?
TED Answer the question, shitball.
TUCKER I think everybody could use a drink.
Tucker goes into the kitchen.
HEALY Look, you asked me to follow your girl around, and I did and I started to like her, and then I realized I just couldn't in good conscience do it.
TED Do what?
HEALY Turn her over to a stalker.
TED What?!
TED You're calling <U>me</U> a stalker?
HEALY That's right--if you weren't you would've looked for her yourself!
Suddenly they hear a SOUND and turn to see Bill the Boa slithering into the room with A HUGE, GREAT-DANE-SIZE LUMP in his midsection.
HEALY (cont'd) Oh Christ...poor dog.
TED You're a sick man, you know that?
HEALY Yeah well fuck you!
HEALY You just can't stand the fact that it was my turn.
TED Your turn?
HEALY That's right, hot shot!
HEALY <U>My turn</U>.
HEALY What's the matter with me, huh?
HEALY Why can't I ever get the great girl?
HEALY Give the big pig with the B.O. to Healy, right?
HEALY Well I was sick of it, man!
HEALY No more--it was my turn.
HEALY It was time for me...time for me...to be happy.
This is so pathetic that it actually gets to Ted.
He sits down, runs his fingers through his hair.
TED Well you didn't have to blow us both out of the water.
TED Jesus Christ, just because she found out about you, why'd you have to take me down with you?
HEALY I don't know what you're talking about.
TED I'm talking about the letter, asshole.
HEALY What?
Ted stares at him.
TED Are you telling me you didn't send Mary a letter outlining our deal?
HEALY Why the fuck would I do that?
HEALY I'd be screwing myself.
The guys stare at one another, then Tucker comes out the kitchen with a drink.
They turn their attention to him.
HEALY (cont'd) You little fuck.
TUCKER What?
HEALY You fucking prick, we had a deal--you said you wouldn't fuck me and I wouldn't fuck you until we had this fuck out of the fucking picture.
HEALY You crossed the line, man.
Tucker backs away nervously.
TUCKER Whoa, whoa, you're getting crazy now.
TUCKER Why would I cross the line--what do you think I got no pride?
Healy grabs Tucker by the neck.
TUCKER (cont'd) I swear!
TUCKER (cont'd) I didn't tell her nothing!
TUCKER (cont'd) You probably did it yourself, you piece of shit.
HEALY Oh that makes a lot of sense.
HEALY Why would I rat myself out?
TUCKER Like I'm going to try to figure out a guy who's idea of courting is blowing farts in the chick's face
HEALY You were following us?
TUCKER Don't flatter yourself--I was following <U>her</U>, I always do.
TUCKER How the hell you think I got rid of Mary's boyfriend Steve?
This gets Ted's attention.
TED You mean...Steve didn't say all that stuff about Warren?
TUCKER Are you shitting me--Mr.
TUCKER Goody-Two-Shoes?
TUCKER He was like a fucking eagle scout.
TUCKER You two should be kissing my balls--if it wasn't for me, she might've married that schmuck!
Ted thinks about this.
TED The hell with you both--I'm out of here.
Ted walks out the door leaving Healy and Tucker to stare each other down.
Just then Hal the Great Dane walks out of the bedroom with a CEREAL BOX stuck on his head.
Healy does a double-take, then looks back at the snake.
HEALY Oh...Sully.
TUCKER Look, if it wasn't you who sent the letter, and it wasn't me who sent it?
<U>CLOSE ON</U> an alarmed Mary.
MARY Woogie?
MARY What are what are you doing here?
<U>REVERSE ANGLE</U> reveals Dom sitting on her bed.
DOM Did you get my letter, Mare?
DOM The one about Ted?
MARY You sent that?
DOM Uh-huh.
DOM I was worried about you.
MARY Well...thank you.
MARY But...you know you're not supposed to be within four hundred yards of me.
DOM That's what I want to tell ya.
DOM I've been through two years of extensive psychotherapy and you know what?
DOM <U>You were
</U> <U>right</U>--I needed help.
MARY That's great, Woogie, I'm happy you're better--you seem...good--but...you put me through quite an ordeal, you know.
Dom nods aggressively.
MARY (cont'd) I had to move, go to court, change my last name--you stole all my shoes!
Dom stands up.
DOM Look at me.
Mary turns her head.
DOM (cont'd) <U>Look at me, Mary</U>.
DOM (cont'd) On my mother's soul, on God above, on everything that is holy to me, I did not steal your shoes.
MARY Woogie, I caught you red-handed.
DOM All right, I did, but I was in a weird place then.
He approaches her.
DOM (cont'd) Give me a break, Mare, I was nuts!
Mary backs into the living room.
Healy and Tucker are parked right out front LISTENING TO THIS CONVERSATION.
They seem concerned.
MARY (V.O.) Woogie, please, you're starting to scare me.
HEALY Who the hell's Woogie?
Tucker just shrugs.
<U>BACK ON</U> Mary and Dom.
=~
MARY I'm asking you to leave.
DOM Oh, Mary, honey, you're taking this all wrong.
DOM I'm not leaving...
</U> DOM (cont'd) (V.O.)
...Not until I get a little something to remember you by.
MARY (V. O . ) Stop that!
MARY (V. O . ) No!
MARY (V. O . ) Somebody help me!!!!!
Healy and Tucker jump out of the car and RUN INTO THE BUILDING.
Healy and Tucker STORM INTO THE ROOM and freeze at what they see.
<U>THEIR POV</U> - Dom is cradling SEVERAL PAIRS OF SHOES in his arms and trying to crawl to the door while Mary holds him back.
MARY Stop it!
DOM Just one pair!
DOM You owe me that much, you heartless bitch!
Healy and Tucker grab Dom and throw him down on the couch.
HEALY Dom, you're pathetic, fucking over your friend Ted like that.
DOM What?
DOM You fucked him over, too.
HEALY He's no friend of mine.
Suddenly Magda ENTERS from her bedroom.
She's holding a half-eaten BANANA SPLIT.
Herb, the Homeless Man, follows after her, sporting a Tom Jones and buttoning up his shirt.
MAGDA What the hell's going on here?
At first no one knows what to say.
Then:
HEALY We're in love with your roommate.
MAGDA Aw, Christ, I can't take it anymore.
MAGDA I'm gonna pack my bags and go back to my own place.
Magda heads back into her bedroom and Herb follows.
MARY Tucker, where are your crutches?
Tucker is stumped for a second, then:
TUCKER Interesting query, Mary...
Healy slaps Tucker in the back of the head.
HEALY Shut the fuck up and tell her the truth.
Before he can respond, Ted ENTERS.
TUCKER Well isn't this nice--now we've got the whole gang together.
Ted can hardly believe Dom is there.
TED Dom?
TED What are you?
DOM You stole her from me.
DOM Now I want her back.
MARY Woogie and I went out for awhile in high school.
TED <U>You're Woogie</U>?
DOM Dom Wooganowski.
DOM Duh.
TED But but you're married.
TED You have kids a great wife.
DOM If you're so happy with them, please, be my guest.
HEALY If I may I have a proposal.
Everyone turns to Healy.
HEALY (cont'd) I say none of us leave this room until our young Mary here stops jerking us around and decides once and for all who she wants.
HEALY (cont'd) Now Mary, I know this is difficult but you really will be doing them all a favor to tell them the truth about us.
MARY Are you crazy?
MARY Why would I pick you?
MARY You're a murderer.
Healy glares at Tucker.
TUCKER Uh, well...not exactly.
TUCKER You see, I exaggerated a little there.
MARY You mean he's not a criminal?
HEALY God no!
HEALY I'm just a pathological liar!
Mary looks at Tucker, confused.
MARY Tucker...not you, too?
Tucker lowers his head and reluctantly nods.
TUCKER Name's Norm.
TUCKER I live up in Pompano with my folks.
MARY Oh Jesus...
Just then the door opens and BRETT FAVRE, the Packers quarterback ENTERS, with Warren (wearing a walkman) beside him.
Everyone is stunned.
MARY (cont'd) Brett...?
BRETT FAVRE Hi, Mary.
HEALY What the hell is Brett Favre doing here?
BRETT FAVRE We're in town to play the Dolphins.
TED I called him.
TED I told him to pick up Warren and get over here.
everyone turns their attention to Ted.
TED (cont'd) Mary, I found out that your buddy Tucker there lied to you about Brett.
Tucker lowers his head.
TED (cont'd) Brett never said anything bad about Warren.
TED (cont'd) He loves Warren...and from what he just told me on the phone, he loves you, too.
TED (cont'd) He's the guy you should be with.
BRETT FAVRE That's right, Mare.
BRETT FAVRE And you know I'll always be true to you.
DOM Aw shit, this isn't fair.
Mary manages a smile.
TED I realized something tonight.
TED I'm no better than any of these guys.
TED None of them really love you...they just fixated on you because of how you made them feel.
TED But that's not real love...Thank you for letting me see that.
TED Now I can get on with the rest of my life.
Tucker, Healy, and Dom scoff.
TUCKER Oh please...
DOM Don't listen to him, Mary.
DOM It's a ploy.
HEALY You are so full of shit, Strohman.
HEALY Are you going to stand here and tell us that you aren't in love with this girl?
Ted looks into Mary's eyes.
She looks vulnerable.
TED Yeah...that's what I'm telling you.
TED See you, Mare.
Ted looks Mary in the eye, then starts for the door.
TED (cont'd) See you, Warren.
WARREN Huh...?
Ted lifts the earphones off Warren's ear.
TED See you, Warren.
WARREN Bye, Ted.
Ted then WALKS OUT OF THE ROOM.
They all stand there in silence for a moment, then Dom turns to Brett Favre.
DOM Hey, Brett, any chance I can get you to autograph one of these pumps for me?
Ted is walking down the street BLUBBERING LIKE A SCHOOLGIRL.
Everyone he passes stares at him.
Suddenly Mary comes running down the OTHER SIDE OF THE STREET.
MARY Ted!
Ted stops and looks across the street at her.
He wipes his eyes, hopeful.
TED What what are you doing here?
MARY You forgot your keys!
She holds up a RABBIT FOOT KEY-CHAIN.
TED Oh.
TED Thanks.
They remain across the street from one another.
MARY Did you mean what you said back there, Ted?
Ted starts to well up again.
MARY (cont'd) Ted...?
TED I...I just want you to be happy, Mary.
MARY But I think I'd be happiest...with you.
Ted just stares at her.
TED You're fucking with me, right?
Mary smiles.
TED (cont'd) But but what about Steve?
MARY Oh yeah, that'd make golf real fun--the guy doesn't even drink beer or gamble.
Now Ted smiles.
MARY (cont'd) Get over here.
TED Really?
MARY Really.
The BEAMING Ted starts walking across the street.
Suddenly a BUS WHIZZES BY AND SMACKS TED BROADSIDE.
He bounces around under the bus like a rag doll, then finally squirts out the back end and
Mary SCREAMS and runs toward the body as a CROWD begins to gather.
MARY Ted, no, no....!
She starts giving him CPR.
Somebody covers him with a blanket.
Just then, another CAR WHIZZES OVER HIS FEET like speedbumps.
The crowd winces.
MARY (cont'd) Somebody hold up traffic!
MARY (cont'd) Come on, Ted.
MARY (cont'd) Come on.
MARY (cont'd) Tell me you're going to be okay.
Then Ted takes a deep breath and his eyes flutter open.
TED Mary....Oh Mary, I love you.
Mary's smile is as bright as the light from heaven.
MARY I love you too, Ted.
MARY I think I always have.
As the two lovebirds kiss, a LADY CALLS OUT:
LADY Over here!
LADY I found his foot!
LADY It was in the storm drain!
<U>ON THE LADY</U> as she holds up a SEVERED FOOT in a cloth.
MARY All right, everyone, let's fan out and look for the penis!
As Ted REACTS to this, we pull UP, UP, UP, and
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
