by Jim Uhls
based on a novel by Chuck Palahnuik
JACK (V.O.) People were always asking me, did I know Tyler Durden.
TYLER has one arm around Jack's shoulder; the other hand holds a HANDGUN with the barrel lodged in JACK'S MOUTH.
Tyler is sitting in Jack's lap.
They are both sweating and disheveled, both around 30; Tyler is blond, handsome; and Jack, brunette, is appealing in a dry sort of way.
Tyler looks at his watch.
TYLER One minute.
TYLER This is the beginning.
TYLER We're at ground zero.
TYLER Maybe you should say a few words, to mark the occasion.
JACK ...
JACK i...
JACK ann....iinn..
JACK ff....nnyin...
JACK (V.O.) With a gun barrel between your teeth, you only speak in vowels.
Jack tongues the barrel to the side of his mouth.
JACK I can't think of anything.
JACK (V.O.) With my tongue, I can feel the rifling in the barrel.
JACK (V.O.) For a second, I totally forgot about Tyler's whole controlled demolition thing and I wondered how clean this gun is.
Tyler checks his watch.
TYLER It's getting exciting now.
JACK (V.O.) That old saying, how you always hurt the one you love, well, it works both way.
Jack turns so that he can see down -- 31 STORIES.
JACK (V.O.) We have front row seats for this Theater of Mass Destruction.
JACK (V.O.) The Demolitions Committee of Project Mayhem wrapped the foundation columns of ten buildings with blasting gelatin.
JACK (V.O.) In two minutes, primary charges will blow base charges, and those buildings will be reduced to smoldering rubble.
JACK (V.O.) I know this because Tyler knows this.
TYLER Look what we've accomplised.
TYLER Thirty seconds.
JACK (V.O.) Somehow, I realize all of this -- the gun, the bombs, the revolution -- is really about Marla Singer.
PULL BACK from Jack's face.
It's pressed against TWO LARGE BREASTS that belong to...BOB, 45, a moose of a man.
Jack is engulfed by Bob in an intense embrace.
Bob weeps openly.
JACK (V.O.) Bob had bitch tits.
PULL BACK to wide on...
Men are paired off, hugging, talking in emotional tones.
Near the door, a SIGN on a stand: "REMAINING MEN TOGETHER."
JACK (V.O.) This was a support group for men with testicular cancer.
JACK (V.O.) The big moosie slobbering all over me was Bob.
BOB We're still men.
JACK Yes.
JACK We're men.
JACK Men is what we are.
JACK (V.O.) Six months ago, Bob's testicles were removed.
JACK (V.O.) Then hormone therapy.
JACK (V.O.) He developed bitch tits because his testosterone was too high and his body upped the estrogen.
JACK (V.O.) That was where my head fit -- into his huge, sweating tits that hung enormous, the way we think of God's as big.
BOB They're gonna have to open my pec's again to drain the fluid.
Bob hugs tighter; then looks with empathy into Jack's eyes.
BOB Okay.
BOB You cry now.
Jack looks at Bob.
JACK (V.O.) Wait.
JACK (V.O.) Back up.
JACK (V.O.) Let me start earlier.
Jack lies in bed, staring at the ceiling.
JACK (V.O.) For six months.
JACK (V.O.) I could not sleep.
Jack, sleepy, stands over a copy machine.
His Starbucks cup sits on the lid, moving back and forth as the machine copies.
JACK (V.O.) With insomnia, nothing is real.
JACK (V.O.) Everything is far away.
JACK (V.O.) Everything is a copy of a copy of a copy.
Other people make copies, all with Starbucks cups, sipping.
Jack picks up his cup and his copies and leaves.
Jack, sipping, stares blankly at a Starbucks bag on the floor, full of newspapers and FAST FOOD GARBAGE.
JACK (V.O.) When deep space exploration ramps up, it will be corporations that name everything.
JACK (V.O.) The IBM Stellar Sphere.
JACK (V.O.) The Philip Morris Galaxy.
JACK (V.O.) Planet Starbucks.
Jack looks up as a pudgy man, Jack's BOSS, enters, Starbucks cup in hand, and slides a stack of reports on Jack's desk.
BOSS I'm going to need you out-of-town a little more this week.
BOSS We've got some "red-flags" to cover.
JACK (V.O.) It must've been Tuesday.
JACK (V.O.) he was wearing his "cornflower-blue" tie.
JACK You want me to de-prioritize my current reports until you advise of a status upgrade?
BOSS You need to make these your primary "action items."
JACK (V.O.) He was full of pep.
JACK (V.O.) Must've had his grande latte enema.
BOSS Here are your flight coupons.
BOSS Call me from the road if there are any snags.
BOSS Your itinerary...
Jack hides a yawn, pretends to listen.
Jack sits on the toilet, CORDLESS PHONE to his ear, flips through an IKEA catalog.
There's a stack of old Playboy magazines and other catalogs nearby.
JACK (V.O.) Like everyone else, I had become a slave to the IKEA nesting instinct.
JACK Yes.
JACK I'd like to order the Erika Pekkari slip covers.
Jack drops the open catalog on the floor.
MOVE IN ON CATALOG -- ON PHOTO of COFFEETABLE SET...
JACK (V.O.) If I saw something like clever coffee table sin the shape of a yin and yang, I had to have it.
PAN TO PHOTO of ARMCHAIR...
JACK (V.O.) Like the Johanneshov armchair in the Strinne green stripe pattern...
The armchair APPEARS.
PAN OVER next to armchair...
JACK (V.O.) Or the Rislampa wire lamps of environmentally-friendly unbleached paper.
The lamps APPEAR.
PAN OVER to wall...
JACK (V.O.) Even the Vild hall clock of galvanized steel, resting on the Klipsk shelving unit.
The clock APPEARS as the shelving unit APPEARS on the wall.
JACK (V.O.) I would flip through catalogs and wonder, "What kind of dining set defines me as a person?" We used to read pornography.
JACK (V.O.) Now it was the Horchow Collection.
A dining room set APPEARS.
Jack, the cordless phone still glued to his ear, walks INTO FRAME and continues.
JACK No, I don't want Cobalt.
JACK Oh, that sounds nice.
JACK Apricot.
Jack opens a cabinet, takes out a plate.
JACK (V.O.) I had it all.
JACK (V.O.) Even the glass dishes with tiny bubbles and imperfections, proof they were crafted by the honest, simple, hard-working indigenous peoples of wherever.
He rummages through the refrigerator.
It's practically empty.
Jack takes out a jar of mustard, opens it and uses a butter knife to eat it.
Jack, eyes puffy, face pale, sits before an INTERN, who studies him with bemusement.
INTERN No, you can't die of insomnia.
JACK Maybe I died already.
JACK Look at my face.
INTERN You need to lighten up.
JACK Can't you give me something?
JACK (V.O.) Red-and-blue Tuinal, lipstick-red Seconals.
INTERN You need healthy, natural sleep.
INTERN Chew valerian root and get some more exercise.
The Intern ushes Jack to the door.
They step into the...
The Intern walks away from Jack, picks up a chart.
JACK I'm in pain.
INTERN You want to see pain?
INTERN Swing by First Methodist Tuesday nights.
INTERN See the guys with testicular cancer.
INTERN That's pain.
The Intern moves into the other room.
Jack stares after him.
Jack heads for the front door.
Jack stares at a group of men, including Bob, who are all listening to a group member speak at a lectern.
The SPEAKER has pale skin and sunken eyes -- he's clearly dying.
SPEAKER I...
SPEAKER wanted three kids.
SPEAKER Two boys and a girl.
SPEAKER Mindy wanted two girls and one boy.
SPEAKER We never could agree on anything.
The Speaker cracks a sad smile.
Some men chuckle, happy to lighten the mood.
SPEAKER Well, she had her first child a month ago, a girl, with her new husband...
SPEAKER And, Thank God.
SPEAKER I'm glad for her, because she deserves...
The speaker breaks down, WEEPS UNCONTROLLABLY.
Jack watches.
A couple of the men go up to the speaker, comforting him, leading him away.
A LEADER takes the stand.
LEADER Everyone, let's thank Thomas for sharing himself with us.
Jack, uncomfortable, joins EVERYONE ELSE:
EVERYONE Thank you, Thomas.
LEADER I look around this room and I see a lot of courage.
LEADER And it gives me strength.
LEADER We give each other strength.
Jack looks around.
Many of the men are sniffling, sobbing.
Jack squirms in his seat.
LEADER It's time for the one-on-one.
LEADER Let's follow Thomas's example and open ourselves.
Everyone gets out of their chairs and begins pairing-off.
Jack stands, uncomfortable.
LEADER Can everyone find a partner?
Bob, his chin down on his chest, starts toward Jack, shuffling his feet.
JACK (V.O.) The big moosie, his eyes already shrink-wrapped in tears.
JACK (V.O.) Knees together, invisible steps.
Bob takes Jack into an embrace.
JACK (V.O.) Bob was a champion bodybuilder.
JACK (V.O.) You know that chest expansion program you see on TV?
JACK (V.O.) That was his idea.
BOB ...using steroids.
BOB I was a juicer.
BOB Diabonol, then, Wisterol -- it's for racehorses, for Christsake.
BOB Now I'm bankrupt, divorced, my two grown kids won't return my calls...
JACK (V.O.) Strangers with this kind of honesty make me go a big rubbery one.
Bob breaks into sobbing, putting his head on Jack's shoulder and completely covering Jack's face.
After a long beat of crying, Bob raises up his head, looks at Jack's NAMETAG.
BOB Go ahead, Cornelius.
BOB You can cry.
They look at each other.
Slowly, Jack's eyes grow wet.
JACK (V.O.) Then...
JACK (V.O.) something happened.
JACK (V.O.) I was lost in oblivion -- dark and silent and complete.
Bob pulls Jack's head back into his chest.
Jack tightens his arms around Bob.
JACK (V.O.) I found freedom.
JACK (V.O.) Losing all hope was freedom.
Jack pulls away from Bob.
On Bob's chest, there's a WET MASK of Jack's face from how he looks weeping.
JACK (V.O.) Babies don't sleep this well.
Jack lies sound asleep.
JACK (V.O.) I became addicted.
Jack moves into a "group hug" of sickly people, men and women.
In view is a sign by the door "Free and Clear."
Jack stands with a weeping middle-aged WOMAN.
He begins to cry along with her.
A sign by the door: "Onward and Upward."
JACK (V.O.) If I didn't say anything, people assumed the worst.
JACK (V.O.) They cried harder.
JACK (V.O.) I cried harder.
Everyone, including Jack, sits back in their seats, EYES CLOSED.
The Leader speaks into a microphone.
LEADER Tonight, we're going to open the green door -- the heart chakra...
JACK (V.O.) I wasn't really dying, I wasn't host to cancer or parasites; I was the warm little center that the life of this world crowded around.
LEADER ...And you open the door and you step inside.
LEADER We're inside our hearts.
LEADER Now, imaging your pain as a white ball of healing light.
LEADER That's right, the pain itself is a ball of healing light.
Jack, eyes closed, is silent...
LEADER It moves over your body, healing you.
LEADER Keep this going and step forward, through the back door of the room.
LEADER Where does it lead?
LEADER To your cave.
LEADER Step forward into your cave.
Jack walks along, moving through an ICE CAVERN...
LEADER'S VOICE That's right.
LEADER'S VOICE You're going deeper into your cave.
LEADER'S VOICE And you're going to find your power animal...
Jack comes upon a PENGUIN.
The penguin looks at him, cocks his head to signal Jack forward.
PENGUIN Slide.
The penguin jumps onto a patch of ICE and slides away.
Jack walks out a doorway, saying goodbye to people.
He walks down the sidewalk, shining with peace.
JACK (V.O.) Every evening I died and every evening I was born again.
JACK (V.O.) Resurrected.
Jack's still in an embrace with Bob.
JACK (V.O.) Bob loved me because he thought my testicles were removed too.
JACK (V.O.) Being there, my face against his tits, ready to cry -- this was my vacation.
MARLA SINGER enters.
She has short matte black hair and big, dark eyes like a character from japanese animation.
JACK (V.O.) And, she ruined everything.
Marla looks around, raises a cigarette to her lips.
MARLA This is cancer, right?
Bob and Jack stare, dumbfounded.
Everyone paired-off.
MOVE THROUGH ROOM...
FIND JACK'S FACE as he stares...
MOVE THROUGH ROOM...
FIND MARLA'S FACE.
She's drinking coffee, smoking a cigarette.
JACK (V.O.) This ...
JACK (V.O.) chick ...
JACK (V.O.) Marla Singer ...
JACK (V.O.) did not have testicular cancer.
JACK (V.O.) She was a liar.
Marla sits with the group, smoking, listening intently while a member speaks.
Jack spies on her.
JACK (V.O.) She had no diseases at all.
JACK (V.O.) I had seen her at my melanoma Monday night group ...
Marla sits at the end of a row, smoking.
All the faces down the row are turned toward her, incredulous...
JACK (V.O.) ...
JACK (V.O.) and at "Free and Clear," my blood parasites group Thursdays.
Jack leans out further than the others, scornful.
JACK (V.O.) -- And, again, at "Seize The Day," my tuberculosis Friday night.
Jack watches...
Marla's eyes are closed, her head on the shoulder of the MAN she's embraced by.
She opens her eyes, catching Jack's stare.
Jack looks away.
JACK (V.O.) Marla -- the big tourist.
JACK (V.O.) Her lie reflected my lie.
Marla rests her chin on the man's shoulder.
Tears roll down her cheeks.
She wipes at them.
Marla walks out, The support group's dispersing.
Jack exits amongst them.
He spots Marla walking away.
JACK (V.O.) And suddenly, I felt nothing.
JACK (V.O.) I couldn't cry.
JACK (V.O.) So, once again, I could not sleep.
Jack stares after Marla for a long moment.
He walks away.
Jack, in underwear, is cross-legged on the floor, assembling IKEA furniture, CORDLESS PHONE shouldered to his ear.
JACK No, I just can't believe that card is declined -- Okay, okay, let me give you a different card number.
Jack gets his wallet off the floor, pulls out another card and, MOS over the following, he reads it into the phone.
JACK (V.O.) Next group, after guided meditation, after we open our chakras, when it's time to hug, I'm going to grab that little bitch, Marla Singer, pin her arms against her sides and say...
CLOSE ON JACK as he CLAMPS his arms around Marla.
JACK Marla, you liar, you big tourist.
JACK I need this.
JACK Get out.
Jack, in pajamas, stares at Home Shopping Network on his TV.
JACK (V.O.) When you have insomnia, you're never really asleep and you're never really awake.
JACK (V.O.) I hadn't slept in four days...
Jack walks in and joins the crowd, looking around.
People are chattering with each other.
JACK (V.O.) -- But, in here, in everyone, there's the squint of a five-day headache.
JACK (V.O.) Yet they forced themselves to be positive.
JACK (V.O.) They never said "parasite;" they said "agent."
JACK (V.O.) They always talked about getting better.
LEADER Okay, everyone.
Everyone sits in chairs.
Jack catches sight of Marla.
LEADER To open tonight's communion, Chloe would like to say a few words.
Taking the lectern is CHLOE, a pale, sickly girl whose skin stretches yellowish and tight over her bones.
She wears a head bondage.
She clears her throat.
JACK (V.O.) Ahh, Chloe.
JACK (V.O.) Chloe looked the way Joni Mitchell's skeleton would look if you made it smile and walk around a party being extra nice to everyone.
CHLOE Well, I'm still here -- but I don't know for how long.
CHLOE That's as much certainty as anyone can give me.
CHLOE but I've got some good news -- I no longer have any fear of death.
APPLAUSE from around the room.
CHLOE But...
CHLOE I am in a pretty lonely place.
CHLOE No one will have sex with me.
CHLOE I'm so close to the end and all I want is to get laid for the last time.
CHLOE I have pornographic movies in my apartment, and lubricants and amyl nitrate ...
The LEADER gingerly takes control of the microphone.
LEADER Thank you, Chloe.
LEADER Everyone, let's thank Chloe.
EVERYONE Thank you, Chloe.
LEADER Now, you're standing at the entrance to your cave.
LEADER You step inside your cave and you walk.
LEADER Keep walking.
Jack's face, eyes closed, is motionless.
JACK (V.O.) If I did have a tumor, I'd name it Marla.
JACK (V.O.) Marla...the little scratch on the roof of your mouth that would heal if only you could stop tonguing it, but you can't.
LEADER Now, find your power animal.
Jack finds Marla smoking a cigarette.
Marla cocks her head, indicating whe wants him to --
MARLA Slide.
Jack's eyes open and turn to Marla, watching her blow smoke rings with her eyes closed.
Everyone stands and mills about, pairing-off.
LEADER Pick someone special to you tonight.
Jack sees the ghastly spectre of Chloe ambling towards him.
He tries to smile.
She smiles with a twisted, dying mouth.
CHLOE Hello, Mr. Tayler.
JACK (V.O.) I never gave my real name at support groups.
JACK Hi, Chloe.
CHLOE We've never actually talked.
Chloe's eyes are eerily bright with desperation.
Jack, in a sincere attempt at levity, chokes out:
JACK You look good.
JACK You ...
JACK look ...
JACK like a pirate.
Chloe laughs, a little too much.
Jack squeezes out a laugh.
Then he sees Marla, off by herself.
Someone heads for her.
JACK Excuse me, I have to...
Jack gives a quick nod to Chloe and darts towards Marla.
Chloe watches him go.
STAY ON JACK AND MARLA as Jack CLAMPS his arms around her.
He whispers into her ear.
JACK We need to talk.
MARLA Sure.
JACK I'm on to you.
JACK You're a faker.
JACK You aren't dying.
MARLA What?
JACK Okay, in the Sylvia Plath philosophy way, we're all dying.
JACK But you're not dying the way Chloe is dying.
LEADER Tell the other person how you feel.
JACK You're a tourist.
JACK I saw you at melanoma, tuberculosis and testicular cancer.
MARLA And I saw you practicing this...
JACK Practicing what?
MARLA Telling me off.
MARLA Is it going as well as you hoped...
MARLA "...
MARLA Mr. Taylor."
JACK I'll expose you.
MARLA Go ahead.
MARLA I'll expose you.
LEADER Share yourself completely.
Marla puts her head down on Jack's shoulder as if she were crying.
Jack pulls her head back up.
She deadpans at him.
JACK Why are you doing this?
MARLA It's cheaper than a movie, and there's free coffee.
JACK These are my groups.
JACK I was here first.
JACK I've been coming for a year.
MARLA A year?
MARLA How'd you manage that?
JACK Anyone who might've noticed either died or recovered and never came back.
LEADER Let yourself cry.
MARLA Why do you do it?
JACK I...
JACK I don't know.
JACK I guess...
JACK when people think you're dying, they really listen, instead...
MARLA -- Instead of just waiting for their turn to speak.
JACK Yeah.
Brief recognition between them, broken as the Leader passes.
LEADER Quietly, now.
LEADER Share with each other.
Jack waits till the Leader's out of earshot.
JACK It becomes an addiction.
MARLA Really?
Jack sighs, then pulls back.
JACK Look, I can't cry with a faker present.
MARLA Candy-stripe a cancer ward.
MARLA It's not my problem.
JACK Please.
JACK Can't we do something...
Marla starts out of the room.
Jack follows her.
LEADER Now, the closing prayer.
Marla gets to the sidewalk, moving quickly along.
JACK We'll split up the week.
JACK You can have lymphoma, tuberculosis and --
MARLA You take tuberculosis.
MARLA My smoking doesn't go over at all.
JACK I think testicular cancer should be no contest.
MARLA Well, technically, I have more of a right to be there than you.
MARLA You still have your balls.
JACK You're kidding.
MARLA I don't know -- am I?
Jack follow Marla into...
Marla walks with authority up to an unwatched DRYER.
She takes out clothes, picks out jeans, pants and shirts.
MARLA I'll take the parasites.
JACK You can't have both parasites.
JACK You can take blood parasites --
MARLA I want brain parasites.
JACK Okay.
JACK I'll take blood parasites and organic brain dementia --
MARLA I want that.
JACK You can't have the whole brain!
MARLA So far, you have four and I only have two!
JACK Then, take blood parasites.
JACK It's yours.
JACK Now we each have three.
Marla gathers the chosen garments and heads out past Jack...
Jack follows, bewildered.
JACK You...
JACK left half your clothes.
HONK!
Jack starts.
Marla's led him into the street with traffic barreling down.
Marla walks on, oblivious as CARS screech to a halt, HORNS BLARING.
Jack dashes, following...
Marla drops the pile of clothes on a counter.
An old CLERK sifts through the clothes, begins writing on a pad.
JACK You're selling those?
Marla steps down hard on Jack's foot.
He winces in pain.
MARLA Yes, I'm selling some chothes.
The Clerk starts to ring up the assessed amounts.
MARLA So, we each have three -- that's six.
MARLA What about the seventh day?
MARLA I want ascending bowel cancer.
JACK (V.O.) The girl had done her homework.
JACK I want ascending bowel cancer.
The Clerk gives a strange look as he hands money to Marla.
MARLA That's your favorite, too?
MARLA Tried to slip it by me, eh?
JACK We'll split it.
JACK You get it the first and third Sunday of the month.
MARLA Deal.
They shake.
Jack tries to withdraw his hand; Marla holds it.
MARLA Looks like this is goodbye.
JACK Let's not make a big thing out of it.
She walks to the door, pocketing money, not looking back.
MARLA How's this for not making a big thing?
Jack watches her go.
A moment, then he follows after...
Jack hesitates, unsure, then run/walks to catch up to her...
JACK Um...
JACK Marla, should we maybe exchange numbers?
MARLA Should we?
JACK In case we want to switch nights.
MARLA I suppose.
Jack takes out a business card, writes his number on the back, hands it to her.
She takes the pen, grabs his hand and writes her number on his palm.
She walks into the street, causing more SCREECHING and HONKING.
She turns, holds up the card.
MARLA It doesn't have your name.
MARLA Who are you?
MARLA Cornelius?
MARLA Mr. Taylor?
MARLA Dr.
MARLA Zaius?
MARLA Any of the stupid names you give each night?
Jack starts to answer, but the traffic noise is too loud.
Marla just shakes her head, turns, and keeps moving.
A BUS moves into view, obscuring her.
JACK (V.O.) This is how I met Marla Singer.
The plane touches down; the cabin BUMPS.
Jack's eyes open.
JACK (V.O.) You wake up at O'Hare.
Jack snaps awake again, looking around, disoriented.
JACK (V.O.) You wake up at SeaTac.
The rear of a CRASHED CAR sticks up by the side of the road.
Jack stands, marking on a clipboard.
The SUN SETS behind.
Jack stands at a gate counter.
An ATTENDANT smiles at him.
ATTENDANT Check-in for that flight doesn't begin for another two hours, Sir.
Jack looks with blearing eyes at his watch, steps away and looks at an overhanging CLOCK.
JACK (V.O.) Pacific, Mountain, Central.
JACK (V.O.) Lose an hour, gain an hour.
JACK (V.O.) This is your life, and it's ending one minute at a time.
Jack's eyes snap open as the plane LANDS.
JACK (V.O.) You wake up at Air Harbor International.
Jack stands on a conveyor belt, briefcase at his feet.
He watches PEOPLE MOVING PAST on the opposite conveyor.
JACK (V.O.) If you wake up at a different time and in a different place, could you wake up as a different person?
Jack misses seeing TYLER on the opposite conveyor belt.
They pass each other.
Jack sits next to a BUSINESSMAN.
As they have idle CONVERSATION, we MOVE IN ON Jack's tray.
An ATTENDANT'S HANDS set coffee down with a small container of cream.
JACK (V.O.) Everywhere I travel -- tiny life.
JACK (V.O.) Single-serving sugar, single-serving cream, single pat of butter.
HANDS place a dinner tray down.
JACK (V.O.) Microwave Cordon Bleu hobby kit.
Jack brushes his teeth in the MIRROR.
JACK (V.O.) Shampoo/conditioner combo.
JACK (V.O.) Single- serving mouthwash, tiny bar of soap.
Jack picks up an individual, wrapped Q-TIP, looks at it.
He moves out of the bathroom into...
Jack sits on the bed.
He turns on the TV.
It's tuned to the "Sheraton Channel," shows WAITERS serving people in a large BANQUET ROOM.
Jack stops brushing his teeth, feels something on the bed, lifts it -- a small DINNER MINT.
Jack sits next to a frumpy WOMAN.
They chat.
Jack turns to look at his food, takes a bite.
He turns back and it's...
--a BALD MAN next to him, talking.
Jack takes another bite, turns back and it's...
--a BUSINESSMAN next to him.
Jack takes another bite, turns back, and it's...
--a BUSINESS WOMAN next to him.
JACK (V.O.) The people I meet on each flight -- they're single-serving friends.
JACK (V.O.) Between take-off and landing, we have our time together, but that's all we get.
Jack's eyes snap open.
JACK (V.O.) You wake up at Logan.
A giant corrugated METAL DOOR opens.
JACK (V.O.) On a long enough time line, the survival rate for everyone drops to zero.
Two TECHNICIANS lead Jack to the BURNT-OUT SHELL of a WRECKED AUTOMOBILE.
Jack sets down his briefcase, opens it and starts to make notes on a CLIPBOARDED FORM.
JACK (V.O.) I'm a recall coordinator.
JACK (V.O.) My job is to apply the formula.
JACK (V.O.) It's a story problem.
TECHNICIAN #1 Here's where the infant went through the windshield.
TECHNICIAN #1 Three points.
JACK (V.O.) A new car built by my company leaves somewhere traveling at 60 miles per hour.
JACK (V.O.) The rear differential locks up.
TECHNICIAN #2 The teenager's braces around the backseat ashtray would make a good "anti-smoking" ad.
JACK (V.O.) The car crashes and burns with everyone trapped inside.
JACK (V.O.) Now: do we initiate a recall?
TECHNICIAN #1 The father must've been huge.
TECHNICIAN #1 See how the fat burnt into the driver's seat with his polyester shirt?
TECHNICIAN #1 Very "modern art."
JACK (V.O.) Take the number of vehicles in the field, (A), and multiply it by the probable rate of failure, (B), then multiply the result by the average out-of-court settlement, (C).
JACK (V.O.) A times B times C equals X...
Jack is speaking to the BUSINESSWOMAN next to him.
JACK If X is less than the cost of a recall, we don't do one.
BUSISNESS WOMAN Are there a lot of these kinds of accidents?
JACK Oh, you wouldn't believe.
BUSINESS WOMAN ...
BUSINESS WOMAN Which...
BUSINESS WOMAN car company do you work for?
JACK A major one.
Turgid silence.
Jack turns to the window.
He sees a PELICAN get SUCKED into the TURBINE.
JACK (V.O.) Every time the plane banked too sharply on take-off or landing, I prayed for a crash, or a mid-air collision -- anything.
Jack's face remains bland during the following: the plane BUCKLES -- the cabin wobbles.
People panic.
Masks drop.
JACK (V.O.) No more haircuts.
JACK (V.O.) Nothing matters, not even bad breath.
The side of the plane SHEARS OFF!
Screaming PASSENGERS are sucked out into the night air, flying past the quivering wind.
Magazines and other objects fly everywhere.
JACK (V.O.) Life insurance pays off triple if you die on a business trip.
Jack remains in his same position, same bland expression.
DING!
-- the seatbelt light goes OUT.
Jack SNAPS AWAKE.
EVERYTHING IS NORMAL.
Some passengers get out of their seats.
From next to Jack, a VOICE we've heard before...
VOICE There are three ways to make napalm.
VOICE One, mix equal parts of gasoline and frozen orange juice...
Jack turns to see TYLER.
Without turned to Jack, Tyler continues:
TYLER Two, equal parts gasoline and diet cola.
TYLER Three, dissolve kitty-litter in gasoline until the mixture is thick.
JACK Pardon me?
Tyler turns to Jack.
JACK (V.O.) This is how I met --
TYLER Tyler Durden.
Tyler offers his hand.
Jack takes it.
TYLER You know why they have oxygen masks on planes?
JACK No, supply oxygen?
TYLER Oxygen gets you high.
TYLER In a catastrophic emergency, we're taking giant, panicked breaths...
Tyler grabs a safety instruction CARD from the seatback, hands it to Jack.
TYLER Suddenly, we become euphoic and docile.
TYLER We accept our fate.
Tyler points to passive faces on the drawn figures.
TYLER Emergency water landing, 600 miles per hour.
TYLER Blank faces -- calm as Hindu cows.
Jack laughs.
JACK What do you do, Tyler?
TYLER What do you want me to do?
JACK I mean -- for a living.
TYLER Why?
TYLER So you can say, "Oh, that's what you do."
TYLER -- And be a smug little shit about it?
Jack laughs.
Tyler reaches under the seat in front of him and lifts a BRIEFCASE.
TYLER You have a kind of sick desperation in your laugh.
Jack points to his own briefcase.
JACK We have the same briefcase.
Tyler turns the top of his briefcase toward Jack.
TYLER Open it.
Jack looks at Tyler, then pops the latches and raises the lid to reveal quaintly-wrapped bars of SOAP.
TYLER Soap -- the yardstick of civilization.
TYLER I make and sell soap...
Tyler hands Jack his card.
"THE PAPER STREET SOAP COMPANY."
TYLER If you were to add nitric acid to the soap-making process, one would get nitroglycerin.
TYLER With enough soap, one could blow up the world, if one were so inclined.
Tyler SNAPS the briefcase shut.
Jack stares.
JACK Tyler, you are by far the most interesting "single-serving" friend I've ever met.
Tyler stares back.
Jack, enjoying his own chance to be witty, leans closer to Tyler.
JACK You see, when you travel, everything is small, self-contained--
TYLER The spork.
TYLER I get it.
TYLER You're very clever.
JACK Thank you.
TYLER How's that working out for you?
JACK What?
TYLER Being clever.
JACK Well, uh...
JACK great.
TYLER Keep it up, then.
TYLER Keep it right up.
Tyler stands, looks towards the aisle.
TYLER ...
TYLER As I squeeze past, do I give you the ass or the crotch?
Tyler moves to the aisle, his ass toward jack, walks away...
TYLER We are defined by the choices we make.
Tyler goes to the curtain dividing First Class, slaps the curtain aside and sits in an empty seat.
Jack watches.
How I came to live with Tyler is: airlines have this policy about vibrating luggage.
Utterly empty of baggage.
No people except for Jack and a SECURITY TASK FORCE MAN.
The Security TFM, smirking, holds a receiver to his ear from an official phone on the wall.
SECURITY TFM Throwers don't worry about ticking.
SECURITY TFM Modern bombs don't tick.
JACK Excuse me?
JACK "Throwers?"
SECURITY TFM Baggage handlers.
SECURITY TFM But when a suitcase vibrates, the throwers have to call the police.
JACK My suitcase was vibrating?
SECURITY TFM Nine time out of ten, it's an electric razor.
SECURITY TFM But, every once in a while ...
SECURITY TFM ...it's a dildo.
SECURITY TFM It's airline policy not to imply ownership in the event of a dildo.
SECURITY TFM We use the indefinite aricle: "A dildo."
SECURITY TFM Never "Your dildo."
Jack sees, through the window, Tyler, at the curb, throwing his briefcase into the back of a shiny, red CONVERTIBLE.
Tyler leaps over the door into the driver's seat and PEELS OUT.
jack turns away, looks at the Security TFM.
In the background, a HARRIED MAN dashes after Tyler and the convertible, SCREAMING.
JACK I had everything in that bag.
JACK My C.K.
JACK shirts...
JACK my D.K.N.Y. shoes...
SECURITY TFM Yeah, uh huh...
SECURITY TFM yeah?
SECURITY TFM Oh...
A lone SUITCASE sits on the concrete.
SECURITY PERSONNEL keep their distance.
KABOOM!
The suitcase explodes.
The Security TFM, shakes his head, hangs up.
SECURITY TFM I'm terribly sorry.
The Security TFM hands Jack a claim form.
Jack snatches it, disgusted, takes out a pen, starts filling out the form.
SECURITY TFM You know the industry slang for "Flight Attendant?" "Air Mattress."
Along a residential street.
Jack looks ahead, sees a tall, grey, bland BUILDING on the corner.
JACK (V.O.) Home was a condo on the fifteenth floor of a filing cabinet for widows and young professionals.
JACK (V.O.) The walls were solid concrete.
JACK (V.O.) A foot of concrete is important when your next- door neighbor lets her hearing aid go and has to watch game shows at full volume...
The taxi turns a corner and Jack sees the front of the building.
A diffuse CLOUD of SMOKE wafts away from a BLOWN- OUT SECTION of the fifteenth floor.
FIRETRUCKS, POLICE CARS and a MOB are all crowded around the lobby area.
JACK (V.O.) -- Or when a volcanic blast of debris that used to be your furniture and personal effects blows out your floor- to-ceiling windows and sails flaming into the night.
Jack, gaping at the sight above him, absently gives the Cabbie money.
The taxi pulls away.
Jack starts toward the building.
He pushes through the fray of people, into the...
The DOORMAN sees Jack enter, gives a sad smile, shakes his head.
Jack starts for the elevator.
DOORMAN There's nothing up there.
Jack presses the button.
The Doorman moves next to him.
DOORMAN You can't go into the unit.
DOORMAN Police orders.
The elevator doors open.
Jack hesitates.
The doors close.
Jack heads out the lobby doors.
The Doorman follows...
Jack walks past SMOKING, CHARRED DEBRIS -- a flash of ORANGE from the Yang table, a CLOCK FACE from the hall clock, part of an arm from the GREEN ARMCHAIR.
His feet CRUNCH glass.
JACK (V.O.) How embarrassing.
DOORMAN Do you have somebody you can call?
Jack comes to his REFRIGERATOR lying on its side.
He reaches down and takes a note: "MARLA --" and a phone number, from under a BANANA MAGNET.
Hissing.
JACK (V.O.) The police would later tell me that the pilot light might have gone out...
JACK (V.O.) letting out just a little bit of gas.
Jack gets to a PAYPHONE.
The Doorman follows, watching him.
DOORMAN Lots of young people try to impress the world and buy too many things.
Jack picks up the receiver, puts in a quarter.
He looks at Marla's number a long moment.
The SOUND of the HISS...
JACK (V.O.) The gas could have slowly filled the condo.
JACK (V.O.) Seventeen-hundred square feet with high ceilings, for days and days.
Jack replaces the receiver.
He pockets Marla's number, digs out a small FILOFAX.
He flips through the pages for phone numbers and addresses.
Most of the pages are blank.
DOORMAN Many young people feel trapped and desperate.
JACK (V.O.) Then, the refrigerator's compressor could have clicked on...
Click.
KABOOM!
SCREEN GOES WHITE.
Jack looks at the Doorman.
Tyler's BUSINESS CARD falls from the Filofax.
Jack catches it.
DOORMAN If you don't know what you want, you end up with a lot you don't.
The Doorman walks away.
Jack stares at Tyler's card.
JACK (V.O.) If you asked me now, I couldn't tell you why I called him.
Jack re-deposits the quarter, dials Tyler's number.
It RINGS...
and RINGS and RINGS.
Jack sighs and hangs up the phone.
A moment, then the phone RINGS.
JACK Hello?
TYLER'S VOICE Who's this?
JACK Tyler?
TYLER'S VOICE Who's this?
JACK Uh...
JACK I'm sorry.
JACK We met on the plane.
JACK We had the same briefcase.
JACK I'm...
JACK you know, the clever guy.
TYLER'S VOICE Oh, yeah.
JACK I just called a second ago.
JACK There was no answer.
JACK I'm at a payphone.
TYLER'S VOICE I star-sixty-nined you.
TYLER'S VOICE I never pick up my phone.
TYLER'S VOICE What's up?
JACK Well...
JACK let me see...
JACK here's the thing...
A small building in the middle of a concrete parking lot.
Jack and Tyler sit in the back, with a pitcher of BEER.
JACK You buy furniture.
JACK You tell yourself: this is the last sofa I'll ever need.
JACK No matter what else happens, I've got the sofa issue handled.
JACK Then, the right set of dishes.
JACK The right dinette.
TYLER This is how we fill up our lives.
Tyler lights a cigarette.
JACK I guess so.
TYLER And, now it's gone.
JACK All gone.
Tyler offers cigarettes.
Jack declines.
TYLER Could be worse.
TYLER A woman could cut off your penis while you're asleep and toss it out the window of a moving car.
JACK There's always that.
TYLER I don't know, maybe I'm wrong.
TYLER Maybe it's a terrible tragedy.
JACK ...no ...no ...
TYLER I mean, you did lose a lot of nice, neat little shit.
TYLER The trendy paper lamps, the Euro-trash shelving unit, am I right?
Jack laughs, nods.
He shakes his head, drinks.
TYLER But maybe, just maybe, you've been delivered.
JACK Delivered from Swedish furniture.
TYLER Delivered from armchairs in obscure green stripe patterns.
JACK Delivered from Martha Stewart.
TYLER Delivered from bullshit colors like "Cobalt," "Ebony," and "Fuchsia."
They laugh together.
Then, silence.
They drink.
JACK Insurance'll cover it.
TYLER Oh, yeah, you gotta start making the list.
JACK What list?
TYLER The "now I get to go out and buy the exact same stuff all over again" list.
TYLER That list.
JACK I don't...
JACK think so.
TYLER This time maybe get a widescreen TV.
TYLER You'll be occupied for weeks.
JACK Well, I have to file a claim...
TYLER The things you own, they end up owning you.
JACK Don't I?
TYLER Do what you like.
JACK God, it's late.
JACK I should find a hotel...
TYLER A hotel?
JACK Yeah.
TYLER So, you called me up, because you just wanted to have a drink before you...
TYLER go find a hotel?
JACK I don't follow...
TYLER We're on our third pitcher of beer.
TYLER Just ask me.
JACK Huh?
TYLER You called me so you could have a place to stay.
JACK No, I...
TYLER Why don't you cut the shit and ask if you can stay at my place?
JACK Would that be a problem?
TYLER Is it a problem for you to ask?
JACK Can I stay at your place?
TYLER Yes, you can.
JACK Thank you.
TYLER You're welcome.
TYLER But, I want you to do me one favor.
JACK What's that?
TYLER I want you to hit me as hard as you can.
JACK What?
TYLER I want you to hit me as hard as you can.
Freeze picture.
JACK (V.O.) Let me tell you a little bit about Tyler Durden.
-- And we see it's PORNOGRAPHY.
Jack, in the foreground, FACES CAMERA.
In the BACKGROUND, Tyler sits at a bench, looking at individual FRAMES cut from movies.
Near him, a PROJECTOR rolls film.
JACK Tyler was a night person.
JACK He sometimes worked as a projectionist.
JACK A movie doesn't come in one big reel, it's on a few.
JACK In old theaters, two projectors are used, so someone has to change projectors at the exact second when one reel ends and another reel begins.
JACK Sometimes you can see two dots on screen in the upper right hand corner...
Tyler points to the side of OUR FRAME and the TWO DOTS briefly APPEAR ONSCREEN.
TYLER They're called "cigarette burns."
JACK It's called a "changeover."
JACK The movie goes on, and nobody in the audience has any idea.
TYLER Why would anyone want this shitty job?
JACK It affords him other interesting opportunities.
TYLER -- Like splicing single frames from adult movies into family films.
JACK In reel three, right after the courageous dog and the snooty cag -- who have celebrity voices -- eat out of a garbage can, there's the flash of Tyler's contribution...
In the AUDIENCE, CHILDREN suddenly start squirming, confused, looking at each other.
A WOMAN abruptly stops sucking her soda straw, feeling vaguely terrible.
Her uncomfortable HUSBAND slowly leans back in his seat.
Jack and Tyler watch from the projection booth window.
TYLER One-forty-eighth of a second.
TYLER That's how long it's up there.
JACK No one really knows that they've seen it.
JACK But they did.
TYLER A nice, big cock.
JACK Only a hummingbird could have caught Tyler at work.
Tyler moves around one of many tables, setting down SOUP BOWLS.
Jack stands in the same position, FACING CAMERA.
JACK Tyler also worked as a banquet waiter at the luxurious Pressman Hotel.
The GUESTS command the WAITERS with snaps of fingers.
Jack turns and WE PAN to Tyler, standing by a CART with a giant SOUP TUREEN.
His hands are at his open fly and he's in position to piss into the soup.
JACK He was the guerrilla terrorist of the food service industry.
TYLER Don't watch.
TYLER I can't if you watch.
Jack waits.
The SOUND of a STREAM of LIQUID is HEARD.
TYLER ...
TYLER Oh, yeah.
TYLER Oh, yeah.
JACK He farted on meringue; he sneezed on braised endive; and, with creme of mushroom soup, well...
TYLER Go ahead.
TYLER Say it.
JACK You get the idea.
Tyler and Jack come out the back door.
JACK I don't know about this.
TYLER I don't know, either.
TYLER I want to find out.
TYLER I've never been hit, have you?
JACK No.
JACK That's a good thing, isn't it?
TYLER I don't want to die without any scars.
TYLER How much can you really know about yourself if you've never been in a fight?
TYLER Come on...
TYLER you're the only person I've ever asked.
JACK Me?
Jack stares at him.
TYLER Why not you?
TYLER I'm letting you go first.
TYLER Do it.
JACK This is crazy.
TYLER Alright, go crazy.
TYLER Let 'er rip.
JACK Where do you want it?
JACK In the face?
TYLER Surprise me.
Jack swings a wide, clumsy roundhouse -- hits Tyler's neck -- makes a dull, flat sound.
JACK Shit.
JACK Sorry.
JACK That didn't count.
TYLER Like hell.
TYLER That counted.
Tyler shoots out a straight punch to Jack's chest.
Jack falls back against a car.
His eyes tear up.
TYLER How do you feel?
JACK Strange.
TYLER But a good strange.
JACK Is it?
TYLER We've crossed the threshold.
TYLER You want to call it off?
JACK Call what off?
TYLER The fight.
JACK What fight?
TYLER This fight, pussy.
Jack swings another roundhouse that slams right under Tyler's ear.
Tyler punches Jack in the stomach.
Tyler and Jack move clumsily, throwing punches.
They breathe heavier, drooling saliva and blood, growing dizzier from every impact.
Jack and Tyler sit on the curb, watching sparse headlights on the nearby freeway.
Their eyes are glazed with endorphin- induced serenity.
They look at each other, laugh.
Look away.
TYLER If you could fight anyone...
TYLER one on one, whoever you wanted, who would you fight?
JACK Anyone?
TYLER Anyone.
Jack thinks.
JACK My boss, probably.
JACK Who would you fight?
TYLER My dad.
TYLER No question.
A long pause as Jack studies Tyler's face.
JACK Oh, yeah.
JACK I didn't know my dad.
JACK Well, I knew him, till I was six.
JACK He went and married another woman, had more kids.
JACK Every six years or so he'd do it again -- new city, new family.
TYLER He was setting up franchises.
TYLER My father never went to college, so it was really important that I go.
JACK I know that.
TYLER After I graduated, I called him long distance and asked, "Now what?" He said, "Get a job."
TYLER When I turned twenty-five, I called him and asked, "Now what?" He said, "I don't know.
TYLER Get married."
JACK Same here.
TYLER A generation of men raised by women.
TYLER I'm wondering if another woman is the answer we really need.
Another pause.
Jack feels his bleeding lip, smiles.
JACK We should do this again sometime.
Tyler cracks a smile, give a sidelong glance to Jack.
A street sign: "PAPER STREET."
A PAPER MILL stis on one side, facing a lone HOUSE on the other.
The rest of the land is grass and weeds.
It's a grand, old three-story, long abandoned.
Tyler leads Jack toward it.
JACK Where's your car?
TYLER What car?
JACK (V.O.) I don't know how Tyler found the house, but he'd been there for half a year.
Tyler leads Jack through the FRONT DOOR...
JACK (V.O.) It looked like it was waiting to be torn down.
JACK (V.O.) Most of the windows were boarded up.
Tyler and Jack climb CREAKY STAIRS to the 2ND FLOOR LANDING.
JACK (V.O.) None of the doors locked.
JACK (V.O.) The stairs were ready to collapse.
JACK (V.O.) I didn't know if he owned it or he was squatting.
Tyler opens the door to a ROOM...
Jack enters, stis on the creaky BED.
Dust drifts upwards.
JACK (V.O.) Neither would have surprised me.
Jack turns on the water.
LOUD VIBRATIONS from the walls.
Water spits in starts.
JACK (V.O.) Nothing worked.
JACK (V.O.) The rusty plumbing leaked.
JACK (V.O.) Turning on a light meant another light in the house went out.
All the tavern's lights are off.
Tyler and Jack FIGHT.
FIVE GUYS stand around watching.
Jack, his face showing NEW BRUISES AND CUTS, makes coffee with a wire-mesh strainer.
Tyler shuffles in, wearing a flannel bathrobe.
He spears pieces of bread on a fork, starts roasting them over a burner.
JACK (V.O.) There were no neighbors.
JACK (V.O.) Just warehouses and the paper mill.
JACK (V.O.) The fart smell of steam, the hamster cage smell of wood chips.
Jack sits watching as Tyler SWINGS an old GOLF CLUB -- THWACK -- sends a golf ball soaring down the desolate street.
JACK (V.O.) At night, Tyler and I were alone for half a mile in every direction.
All the lights are off.
TEN GUYS YELL, standing around Jack and Tyler, who FIGHT.
THREE CARS are parked in the lot.
Jack sits on basement stairs, watching as Tyler, knee-deep in water, works at an open FUSEBOX, flipping breakers in a certain order, showing Jack how it's done.
JACK (V.O.) When it rained, we had to kill the power.
JACK (V.O.) By the end of the first month, I didn't care about TV.
JACK (V.O.) I didn't mind the warm, stale refrigerator.
CANDLES BURN.
Tyler and Jack are seated across from each other on the buckled floor, reading MAGAZINES.
Rain DRIPS from the ceiling.
No furniture.
THOUSANDS of MAGAZINES.
JACK (V.O.) The previous occupant had been a bit of a shut-in.
TYLER Hum.
JACK What?
TYLER Oh, a new riot control grenade...
TYLER "...the successful combination of concussive, 3000 foot-candle flash- blasts and simultaneous high-velocity disbursement of...blah, blah, blah..."
Tyler begins RIPPING the ARTICLE from his magazine.
JACK "I am Joe's Lungs."
JACK It's written in first person.
JACK "Without me, Joe could not take in oxygen to feed his red blood cells."
JACK There's a whole series -- "I am Joe's Prostate."
TYLER "I get cancer, and I kill Joe."
Tyler tosses his article in a pile of other articles, chooses another magazine.
JACK What are you reading?
TYLER Soldier of Fortune.
TYLER Business Week.
TYLER New Republic.
JACK Show-off.
All the lights are off.
Jack and Tyler stand amidst FIFTEEN GUYS around TWO GUYS FIGHTING.
The crowd YELLS MORE WILDLY than before.
In the background are EIGHT PARKED CARS.
JACK (V.O.) I should have been haggling with my insurance company.
JACK (V.O.) I should have been looking for a new condo...
Jack walks along.
He stops, looking at a CHURCH with SUPPORT-GROUP-PEOPLE milling around the entrance, drinking coffee and sodas.
Marla's there, amongst them, smoking.
JACK (V.O.) ....
JACK (V.O.) I should have been upset about my nice, neat, flaming little shit.
Jack's face shows no reaction.
He continues to walk.
JACK (V.O.) But I wasn't.
Jack, in work clothes, interlocks his fingers and POPS his knuckles, picks up a saucepan with coffee and sips.
Tyler, in waiter's uniform, comes to have Jack straighten his tie.
JACK (V.O.) Most of the week, we were Ozzie and Harriet.
Jack picks up his briefcase and walks out the door.
JACK (V.O.) But, Wednesday night, ever Wednesday night...
All the lights are off.
No one around, but there are at least TWENTY-FIVE CARS parked in the full lot.
JACK (V.O.) ...
JACK (V.O.) we were finding something out: we were finding out, more and more, that we were not alone.
A SLIDE SHOW progresses, run by a chipper salesman, WALTER.
Jack sits, deadpan, with a PUFFY LIP and a BRUISED cheek.
JACK (V.O.) Thursday mornings, all I could do was think about next week.
Boss gives Jack a dubious look.
Walter's next SLIDE: a
WALTER The basic premise of cyber-netting your office is -- make things more efficient.
BOSS Can I get the icon in cornflower blue?
WALTER Absolutely.
Walter continues, his sales pitch drowned out by Jack's V.O.:
JACK (V.O.) Walter, the Microsoft account exec.
JACK (V.O.) Walter, with his smooth, soft hands.
JACK (V.O.) Maybe he was thinking about the free- range potluck he'd been to last weekend, or his church-group car-wash fund-raiser.
JACK (V.O.) Or, probably not.
Walter moves to Jack and slaps him in the shoulder.
WALTER I showed this already to my man here.
WALTER You liked it, didn't you?
Jack smiles.
His teeth are RED with BLOOD.
They GLOW eerily in the dim light.
JACK (V.O.) You can swallow a pint of blood before you get sick.
WALTER Jesus, I'd hate to see what happened to the other guy.
Jack keeps the smile frozen on his face.
JACK (V.O.) Screw Walter.
JACK (V.O.) His candy-ass wouldn't last a second Wednesday night.
Out of silent darkness, HEADLIGHTS appear from all directions.
CARS PULL UP and park in the already-packed lot.
YOUNG MEN get out and march into the tavern...
The men, including Jack and Tyler, enter and stand against the back wall, waiting.
The bartender, IRVINE, calls out:
IRVINE Drink up people.
IRVINE We're closing.
Irvine flicks on the LIGHTS.
Drunken customers squint and get the message.
They plop down money, leaving.
JACK (V.O.) It was right in everyone's face.
JACK (V.O.) Tyler and I just made it visible.
Irvine hits a button and the JUKEBOX loses power.
Members of the waiting army begins to share secret looks.
Finally, one buy locks the door.
Two other guys close the blinds.
JACK (V.O.) It was on the tip of everyone's tongue.
JACK (V.O.) Tyler and I just gave it a name.
A BOMB-SHELTER.
Concrete walls.
One BARE BULB above, Tyler standing directly beneath it.
TYLER Welcome to fight club.
The guys mill around, finding partners.
Everyone brims with eagerness, but tries to act cool.
CHATTER gets LOUDER.
Everyone spreads out, forming a circle, Tyler at center.
JACK (V.O.) Every week, Tyler gave the rules that he and I decided.
PEAKING CHATTER, till Tyler raises his arms and the CHATTER DIES.
A couple of COUGHS, FEET SHUFFLING, then, SILENCE.
TYLER The first rule of fight club is -- you don't talk about fight club.
TYLER The second rule of fight club is -- you don't talk about fight club.
TYLER The third rule of fight club is -- when someone says "stop" or goes limp, the fight is over.
TYLER Fourth rule is -- only two guys to a fight.
TYLER Fifth rule -- one fight at a time.
TYLER Sixth rule -- no shirts, no shoes.
TYLER Seventh rule -- fights go on as long as they have to.
TYLER And the eighth and final rule -- if this is your first night at fight club, you have to fight.
Tyler steps back.
A short guy, RICKY, and a GOATEED MAN take off shirts and shoes and step to the center.
JACK (V.O.) This kid, Ricky -- supply clerk -- couldn't remember whether you ordered pens with blue ink or black ink ...
The two fighters circle, then begin throwing PUNCHES...
JACK (V.O.) But Ricky was a god for ten minutes last week when he trounced an actuary twice his size.
Harder, faster PUNCHES between the two.
SWEAT flies.
SHOUTS become DEAFENING.
Ricky's getting the best of Goateed Man, POUNDING him...
JACK (V.O.) Sometimes all you could hear were flat, hard packing sounds over the yelling, or the wet choke when someone caught their breath and sprayed...
GOATEED MAN Ssssstop...
Jack, eating lunch, watches the BROKEN-NOSED WAITER with a GOATEE -- from the above fight -- converse with a MAITRE D'.
JACK (V.O.) Even if I could tell someone they had a good fight, I wouldn't be talking to the same man.
The Goateed Waiter approaches Jack and sets a refill soda down on the table.
The two of them briefly make eye contact.
JACK (V.O.) Who you were in fight club is not who you were in the rest of the world.
Jack stands over a copy machine, hit by flashes of light.
He glances over his shoulder, watches Ricky, wearing an apron, push a supply cart.
Ricks nods at Jack.
JACK (V.O.) You weren't alive anywhere like you were there.
JACK (V.O.) But fight club only exists in the hours between when fight club starts and when fight club ends.
Jack, playing SOLITAIRE on his computer, daubs blood from his mouth with a handkerchief.
Boss, passing by the doorway, looks in at Jack, irritated.
BOSS What are you getting yourself into every week?
Jack keeps playing Solitaire.
Boss enters, folds his arms.
JACK (V.O.) After fight club, everything else in your life gets the volume turned down.
JACK (V.O.) You can deal with anything.
BOSS Have you finished those reports?
JACK Yes.
JACK (V.O.) The people who had power over you have less and less.
Jack looks at Boss.
Reflexively, Jack's tongue plays with his teeth.
JACK (V.O.) By this point, I could wiggle most of the teeth in my jaw.
Tyler and Jack walk, both smoking cigarettes.
JACK (V.O.) A guy came to fight club for the first time, his ass was a wad of cookie dough.
JACK (V.O.) After a few weeks, he was carved out of wood.
JACK If you could fight any celebrity?
TYLER Alive or dead?
JACK Doesn't matter.
TYLER Hemingway.
TYLER You?
JACK Shatner.
JACK William Shatner.
They reach a BUS STOP as a BUS arrives, tossing their cigarettes, getting on board...
The bus is crowded.
As Tyler and Jack walk toward the back, Jack studies the faces of OTHER PASSENGERS...
JACK (V.O.) We all started seeing things differently.
JACK (V.O.) Wherever we went.
They hold hand grips.
Jack looks up at an ADVERTISEMENT; a CALVIN KLEIN ad featuring a tan, bare-chested MUSCLE STUD.
JACK (V.O.) I felt sorry for all the guys packing into gyms, trying to look like what Calvin Klein and Tommy Hilfiger said they should.
Tyler looks at Jack, looks at the C.K. advertisement.
TYLER Self-improvement is masturbation.
TYLER Self-destruction is the answer.
A MAN in a suit KNOCKS Tyler's shoulder as he passes.
The Man takes a handle, close by.
Jack's pissed, staring at the man, who stares back.
JACK You could take him.
Tyler looks to Jack, glances over his shoulder at the Man.
Tyler casually picks a small scab off Jack's nostril.
TYLER The trick is not to care.
Tyler stares forward.
Tyler HITS the floor, stomach first.
HIS OPPONENT lands on top of him, grappling, trying for a CHOKE HOLD.
The surrounding CROWD, Jack included, SCREAMS at them...
Tyler and the Opponent wrestle desperately, and Tyler flips his attacker, gets on top, sprawling to pin him.
Tyler turns -- starts reining PUNCHES into the Opponent's GROIN...
Jack lands a couple of BLOWS to HIS OPPONENT'S stomach -- brings up a left uppercut that smashes the Opponent's jaw.
Tiny spatters of BLOOD adorn the walls, along with sweat.
Jack catches sight of a swollen-faced Tyler, watching appreciatively, a smile growing slowly on his face.
JACK (V.O.) Fight club wasn't about winning or losing.
JACK (V.O.) It wasn't about words.
The Opponent recovers, throws a headlock on Jack.
Jack snakes his arm into a counter headlock.
They wrestle like wild animals.
The crowd CHEERS maniacally.
JACK (V.O.) They hysterical shouting was in tongues, like at a Pentecostal church.
Onlookers kneel to stay with the fight, cheering LOUDER.
The Opponent SMASHES Jack's head to the floor, over and over.
JACK ...
JACK stop...
JACK (V.O.) When the fight was over, nothing was solved, but nothing mattered.
Everyone moves in as the Opponent steps away.
Tyler pushes through the crowd.
Others lift Jack up.
They turn their attention to the floor, to a BLOOD MASK of Jack's face -- similar to the TEAR MASK on BOB'S SHIRT.
TYLER Cool.
Jack limply shakes his Opponent's hand.
OPPONENT How about next week?
JACK Look at me.
JACK How about next month?
Everyone helps Jack walk.
He's sweating, bleeding, smiling.
JACK (V.O.) Afterwards, we all felt saved.
A NURSE tends to Jack while Tyler watches.
TYLER He fell down some stairs.
The Nurse doesn't look at Tyler, just keeps tending to Jack.
JACK I fell down some stairs.
JACK (V.O.) Sometimes Tyler spoke for me.
Tyler and Jack share the cracked MIRROR.
Tyler's clipping at his hair with blunt, ill-suited SCISSORS.
Jack's brushing his teeth, spitting out pink foam.
JACK (V.O.) Fight club became the reason to cut your hair short and trim your fingernails.
TYLER Any historical figure.
JACK Okay...
JACK Ghandi.
TYLER Good answer.
JACK You?
TYLER Abe Lincoln.
TYLER Big reach.
TYLER Skinny guys fight till they're burger.
Jack reaches in his mouth, exploring, pulls -- yanks a TOOTH.
Jack looks at it.
Tyler puts scissors down, done.
TYLER Remember, even the Mona Lisa's falling apart.
Jack drops the tooth in the sink with Tyler's hair.
Jack enters, buttoning his shirt.
The PHONE RINGS.
JACK Hello?
Marla's in the HALL, on the PAYPHONE, twisting the phone cord around her neck.
MARLA Where have you been the last few weeks?
JACK Marla?
Jack looks through the archway and sees Tyler, in his gummy flannel bathrobe, doing sit-ups.
Jack leans, cups the phone.
JACK How did you find me?
MARLA The forwarding number.
MARLA I haven't seen you at any support groups.
JACK That's the idea -- we split them.
MARLA You haven't been going to yours.
JACK I found a new one.
MARLA Really?
JACK It's for men.
MARLA Like testicular cancer?
JACK Look, this is a bad time...
MARLA I've been going to debtor's anonymous.
MARLA You want to see some truly fucked up people?
JACK I'm just on my way out...
MARLA Me too.
MARLA I got a stomach full of Xanax.
MARLA I took what was left of a bottle.
MARLA Might've been too much.
Jack looks exasperated, turns TO LOOK INTO THE CAMERA.
JACK (V.O.) Picture yourself watching Marla Singer throw herself around her crummy apartment.
MARLA This isn't a for-real suicide thing.
MARLA This is probably one of those cry-for- help things.
JACK (V.O.) This could go on for hours.
JACK So you're staying in tonight?
MARLA Do you want to wait to hear me describe death?
Jack puts the handset on top of the phone, still off the hook, walks out the back door.
MARLA'S VOICE Do you want to listen and see if my spirit can use the telephone?
Thru the archway: Tyler leans to look in, curious.
GRUNTS of PLEASURE and EXERTION.
Glimpses of TORSOS, ASSES, LEGS, ARMS, BREASTS, and FEMALE HAIR, all DRENCHED in SWEAT.
Sheets RIP.
Bodies hit the FLOOR.
Insane GRUNTING and LAUGHING.
A flash of MARLA'S FACE.
Jack sits up in bed, looks around the room.
Jack steps out of his room.
The neighboring door is closed.
JACK (V.O.) Tyler's door was closed.
JACK (V.O.) I'd been living here two months, and Tyler's door was never closed.
Jack stares into the TOILER, looking at SIX USED CONDOMS.
Jack sits at the table, sips coffee, read Reader's Digest.
He hears FOOTSTEPS approaching.
JACK You're not going to believe what I dreamt last night.
Marla walks in, straightening her dress, looks like she's been raped by a hurricane.
Jack's jaw drops.
MARLA I can hardly believe anything about last night.
Marla goes to pour coffee.
She takes a swig, GARGLES and SPITS it in the sink.
She gives Jack a lascivious smile.
JACK What are you doing here?
MARLA What...
JACK What the hell are you doing here?
Marla stares at him a beat, then drops the cup in the sink.
MARLA Fuck you.
Marla shoves open the door to the backyard and walks out.
Jack gets up, watches her stomp away.
Jack turns and -- Tyler is at his shoulder, staring after Marla.
He's in his usual sweatpants.
He grins at Jack, then moves away, pours himself coffee.
Jack, smoldering, slumps at the table and picks up Reader's Digest.
Tyler puts his foot on a countertop, does stretching exercises.
TYLER She's a piece of work.
TYLER Get this -- I come in here last night, the phone's off the hook...
Jack pretends to read, quickly glances at Tyler.
TYLER'S
JACK (V.O.) I already knew the story before he told it to me.
Tyler enters, gently lifts the handset and listens.
MARLA'S VOICE I'll tell you when I'm floating out of my body.
Tyler smiles.
JACK (V.O.) How could Tyler, off all people, think it was a bad thing that Marla Singer was about to die?
Tyler, a wry smile on his face, ambles up the stiars, looking at the rotting walls.
He reaches the top of the stairs and heads for Marla's room.
Before he can knock, Marla's hand shoots out and grabs him...
Marla pulls Tyler inside and shuts the door.
Her drugged eyes look him over.
MARLA You got here fast.
She staggers and sits on the bed.
She slides off, along with the blanket and sheets, to the floor.
MARLA The mattresses are all sealed in slippery plastic.
She tries to focus her eyes on Tyler.
MARLA Did I call you?
Tyler studies her with cynical curiosity, looks at a DILDO lying atop a dresser.
Marla follows his gaze.
MARLA Don't worry.
MARLA It's not a threat to you.
SIRENS and vehicles SCREECHING outside can be HEARD; doors opening and SLAMMING; running FOOTFALLS.
MARLA Oh, no!
MARLA Somebody called the cops...
She gets to her feet, grabs Tyler, pulls him out the door.
Marla LOCKS her door, then pulls Tyler toward the STAIRCASE.
COPS and PARAMEDICS charge up with oxygen and medical kits.
Marla and Tyler flatten against the wall to let them pass.
COP 8-G!
COP Where's 8-G?
MARLA End of the hall.
The rescuers keep running.
MARLA The girl who lives there used to be a charming, lovely girl, but she's lost faith in herself...
COP Miss Singer, let us help you!
COP You have every reason to live!
Marla yanks Tyler's arm, heading down the stairs.
MARLA She's a monster!
MARLA Infectious human waste!
MARLA Good luck trying to save her!
Tyler makes coffee.
Marla slouches against the refrigerator.
MARLA If I fall asleep, I'm done for.
MARLA You're gonna have to keep me up all night.
Tyler chuckles, shakes his head.
TYLER Unbelievable, huh?
JACK (V.O.) He was obviously able to handle it.
Tyler stands across from Jack, gets a cigarette from a pack.
TYLER I mean, this girl...
TYLER uh, you're not into her or anything...
JACK No.
JACK Not at all.
JACK (V.O.) I am Jack's Raging Bile Duct.
Tyler lights his cigarette.
TYLER You're sure?
JACK Yeah, I'm sure.
TYLER Good.
TYLER This chick was up on the table with her legs in the stirrups before the doctor even walked in the room.
TYLER The things that she said...
TYLER I've never heard a woman talk like that...
Tyler smokes, post-coital.
Marla puts her lips to his ear.
MARLA I want to have your abortion.
Tyler laughs, shakes his head.
Jack's gripping his Reader's Digest just a little too tight.
JACK (V.O.) How could Tyler not go for that?
JACK (V.O.) Night before last, he was splicing sex organs into "Little Mermaid."
Tyler sits, studies Jack's face.
TYLER You're okay with this?
JACK I'm fine.
JACK (V.O.) Put a gun to my head and paint the wall with my brains.
Tyler smokes.
TYLER She is a wild, twisted bitch.
TYLER Stay away from that one.
JACK Oh, and my pace is more librarians.
TYLER Hey...
TYLER don't knock librarians.
JACK Marla doesn't need a lover.
JACK She needs a case worker.
TYLER She needs an exorcist.
TYLER This isn't love.
TYLER This is sport-fucking.
JACK (V.O.) She'd invaded my support groups, now she's invading my home.
TYLER Listen...
TYLER do me a favor...
TYLER sit here a minute...
Tyler pulls out a closer chair, motions to it.
Jack puts down his Reader's Digest and moves to that chair.
JACK What?
TYLER You've gotta understand something about me.
TYLER I have a little rule, okay?
TYLER Don't ever talk to her about me.
TYLER Ever.
TYLER I can't stand that kind of shit.
Tyler fixes Jack with a friendly, but firm stare.
TYLER If you ever say anything about me or about what happens here in this house, to her or anyone -- I will find out.
TYLER And you'll never see me again.
TYLER Promise me.
JACK Okay.
TYLER Promise you won't.
JACK Yes, I promise.
TYLER Promise?
JACK I said I promise!
TYLER That was three times you promised.
Tyler smiles, gets up and leaves.
Jack sits smoldering.
JACK (V.O.) If only I had wasted a couple of minutes and gone to watch Marla die, none of this would have happened.
Jack watches TV at HIGH VOLUME.
SOUNDS of SEX from upstairs.
Jack lies calmly on his bed, staring at the ceiling.
Sounds of THUMPS and CRASHES from beyond the wall.
MARLA'S VOICE Miserable fucking discharge!
JACK (V.O.) I could've moved to another room, one on the third floor -- so I wouldn't have heard them.
JACK (V.O.) But I didn't.
SOUNDS of RAIN.
Jack flips FUSES off, then walks upstairs.
Jack walks, HEARS Marla SCREAM in orgasm.
He reaches the landing.
Tyler's door is ajar.
Jack peeks in...
Marla's legs are sprawled on the bed.
The door PUSHES OPEN WIDER -- Tyler, naked, stands CLOSE TO CAMERA.
TYLER What are you doing?
Jack steps back.
JACK I...
JACK uh...
JACK just going to bed.
Tyler scratches his head, wears a RUBBER GLOVE.
TYLER You want to finish her off?
JACK Uh...
JACK nah...
Jack continues toward his room.
Jack brushes his teeth.
JACK (V.O.) I became the calm, little center of the world.
JACK (V.O.) I was the Zen master.
Haiku is BEING TYPED in a trendy, italicized font.
"Worker bees can leave Even drones can fly away The queen is their slave"
JACK (V.O.) I wrote little haiku poems.
Jack's clothes are PERMANENTLY STAINED with BLOOD.
He sits in Zen pose, cigarette in mouth, finishes typing Haiku.
JACK (V.O.) I faxed them around to everyone.
He hits "SEND," gets the "ERROR CHIME" SOUND.
He presses this key over and over.
Boss enters.
BOSS Is that your blood?
JACK Some of it, yes.
Boss stares at Jack like he's from Mars.
BOSS Take the rest of the day off.
BOSS Come back tomorrow with clean clothes.
BOSS Get yourself together.
Jack's leaving, looks like a war casualty, passing COWORKERS who coldly stare at him.
His face is totally passive.
JACK (V.O.) I got right in everyone's hostile little face.
JACK (V.O.) Yes, these are bruises from fighting.
JACK (V.O.) I'm comfortable with them.
JACK (V.O.) I am enlightened.
Jack walks toward the HOUSE.
JACK (V.O.) You give up the condo life, give up all your flaming worldly possessions, go live in a dilapidated house in the toxic waste part of town...
Jack walks in.
SOUNDS of VIOLENT SEX and a POLAROID CAMERA from upstairs.
Pieces of PLASTER fall from the ceiling.
JACK (V.O.) ...
JACK (V.O.) and you come home to this.
TYLER'S VOICE You fucking slut!!
MARLA'S VOICE Thank you, sir, may I have another!
MARLA'S VOICE Thank you sir, may I have another...
Jack rolls his eyes, takes off his pants.
He runs water in the sink, finds a tiny bit of SOAP and scrubs at the blood stains.
The PHONE RINGS.
He answers it.
JACK Yeah.
JACK Speaking.
A cop, DETECTIVE STERN, refers to a file.
DETECTIVE STERN This is Detective Stern with the arson unit.
DETECTIVE STERN We have some new information about the "incident" at your condo.
JACK Yes?
DETECTIVE STERN I don't know if you're aware...
DETECTIVE STERN your front door -- it seems someone sprayed freon into the lock, then tapped it with a chisel to shatter the cylinder.
JACK No, I wasn't aware...
JACK (V.O.) I am Jack's Cold Sweat.
DETECTIVE STERN Does this sound strange to you?
JACK Yes, sire, strange.
JACK Very strange.
Jack starts to sweat, scrubs his pants obsessively.
DETECTIVE STERN The dynamite...
JACK Dynamite?
DETECTIVE STERN Yes.
DETECTIVE STERN It left a residue of ammonium oxalate and potassium perchloride.
DETECTIVE STERN Do you know what that means?
JACK What does that mean?
DETECTIVE STERN It means it was homemade.
JACK This is...
JACK really a shock...
DETECTIVE STERN Whoever set this homemade dynamite could've blown out the pilot light days before the explosion.
DETECTIVE STERN The gas, it seems, was just a detonator.
JACK Who do you think could've done this?
DETECTIVE STERN I'll ask the questions, son.
TYLER Tell him...
Jack almost leaps out his skin, startled; looks to see Tyler standing right next to him.
JACK Huh?
TYLER "The liberator who destroyed my property has re-aligned my paradigm of perception."
JACK Shhhhhh!
JACK I don't know what to make of this, sir, I really don't...
DETECTIVE STERN Do you know anyone who'd have the expertise or motive to do something like this?
TYLER "I reject the basic assumptions of civilization, including material possession."
Jack pushes Tyler away, cups the receiving.
JACK No.
JACK No, sir.
JACK I loved that condo.
JACK I loved every stick of furniture.
JACK The lamps, the chairs, the rugs, were me.
JACK The dishes were me.
JACK The plants were...
JACK (V.O.) I'd like to thank the academy...
DETECTIVE STERN Well, if any ideas come to you, give me a call.
DETECTIVE STERN In the meantime, don't leave town.
DETECTIVE STERN I may need to bring you in for questioning.
Jack hangs up.
Tyler shrugs.
TYLER Could be worse.
TYLER You could be cursed with the three terrible Karmas.
TYLER You could be beautiful, rich and famous.
Jack turns away, continues to scrub his pants.
Marla's FOOTSTEPS can be HEARD coming downstairs...
Jack really grinds the soap against the pants, splashing water.
He turns, sees Marla enter.
Tyler is GONE.
Marla lights a cigarette.
JACK (V.O.) Except for their humping, Tyler and Marla were never in the same room.
MARLA I got this dress at a thrift store for one dollar.
JACK Worth every penny.
JACK (V.O.) My parents pulled this exact act for years -- one came in, the other disappeared.
Marla begins a slow, exotic dance, moving very close to Jack.
She lifts her dress dangerously high, dancing close to Jack's body, almost touhcing.
MARLA It's a bridesmaid's dress.
MARLA Someone loved it intensely for one day, then tossed it.
MARLA Like a Christmas tree -- so special, then, bam -- it's abandoned on the side of the road, tinsel still clinging to it...
Jack becomes very aware of having no pants on, presses against the counter.
Marla pulls her hemline further up.
MARLA Like sex crime victims, underwear inside-out, bound with electrical tape.
JACK It suits you.
She leans in very close to Jack's ear, whispers hoarsely:
MARLA You can borrow it sometime.
Jack takes a step away, keeps scrubbing.
Marla blows smoke in his face.
Jack takes her cigarette and throws it in the sink.
Marla backs away, fed up, storms out, going UPSTAIRS.
TYLER Get rid of her.
Jack turns to see Tyler in the doorway.
JACK You get rid of her.
TYLER Don't mention me.
Marla's FOOTSTEPS are coming DOWNSTAIRS.
Jack looks to the archway, then back at -- Tyler's GONE.
Marla enters, shoes and balled up clothing under one arm, looking for something on the junk strewn table.
JACK (V.O.) I'm six years old again, passing messages between my parents.
JACK I, uh...
JACK think you should go now.
Marla ignores, still searching the table, tossing things, pushing other things off to the floor.
JACK It's time for you to leave.
MARLA Don't worry, I'm leaving.
Marla finds what she wanted, a pack of cigarettes.
She moves up into Jack's face.
MARLA You're such a nutcase, I can't even begin to keep up.
JACK Goodbye.
She laughs, spins on her heels.
As she exits the back door, she sings "This Merry-Go-Round" from "Valley of the Dolls."
Jack watches her through the kitchen window.
TYLER Nice work.
Jack turns.
Tyler's right behind him.
Through the window, Marla can be seen walking away.
Tyler picks up the remnant of SOAP Jack's been using, holds it up to Jack.
TYLER To make soap, first we have to render fat.
Jack looks at Tyler.
Tyler stands inside the fence.
Jack's atop the fence, struggling to cross BARBED WIRE.
He wobbles, gets over, snags his shirt.
Jack falls, RIPPPPP.
Tyler helps.
FOOTSTEPS.
A FLASHLIGHT BEAM.
Tyler pulls Jack behind a DUMPSTER, one of DOZENS.
A silhouette of a SECURITY GUARD moves along the perimeter, flashlight first.
He walks away.
MOVE BACK to Tyler and Jack, who emerge from hiding.
Tyler eagerly grabs the lid of the closest dumpster.
TYLER The best fat for making soap -- because the salt balance is just right -- comes form human bodies...
Tyler lifts the lid -- it CREAKS.
JACK What is this place?
TYLER A liposuction clinic.
From the dumpster, Tyler pulls out an industrial-sized, thick plastic bag full of PINK GOO.
TYLER Paydirt.
TYLER From society's richest asses and thighs.
TIME CUT: Tyler and Jack climb back over the fence, carrying BAGS of fat.
One of Jack's bags RIPS, spilling the goo down the chain-link fench.
Jack slips and slides.
Tyler laughs.
Tyler tries to scoop the running fat back into the bag.
Jack and Tyler each stir a boiling pot.
TYLER As the fat renders, the tallow floats to the surface.
TYLER Remember the crap they taught you in Boy Scouts.
JACK Hard to imagine you in Boy Scouts.
TYLER This clear layer in glycerin.
TYLER We'll mix it back in when we make the soap.
Tyler sticks a spoon into a pot, lifts up a scoop of the glycerin layer.
Then, he crabs a can, opens it.
TYLER Lye -- the crucial ingredient.
TYLER Ancient peoples found their clothes got cleaner if they washed them at a certain spot in the river.
TYLER Why?
TYLER Because, human sacrifices were once made on the hills above this river.
TYLER Year after year, bodies burnt.
TYLER Rain feel.
TYLER Water seeped through the wood ashes to become lye.
TYLER The lye combined with the melted fat of the bodies, till a thick white soapy discharge crept into the river.
Tyler licks his lips until they're gleaming wet.
He takes Jack's hands and KISSES the back of it.
TYLER The first soap was made from the ashes of heroes.
TYLER Like the first monkeys shot into space.
The saliva shines in the shape of the kiss.
Tyler pours a bit of the flaked lye onto Jack's hand.
TYLER Without sacrifice, without death, we would have nothing.
Jack's whole body JERKS.
Tyler holds tight to Jack's hand and arm.
Tears well in Jack's eyes; his face tightens.
TYLER This is a chemical burn.
TYLER It will hurt more than you've ever been burned and you will have a scar.
Jack looks -- the burn is swollen, glossy, in the shape of Tyler's kiss.
Jack's face spasms.
JACK (V.O.) Tyler's kiss was a bonfire on the back of my hand.
TYLER Look at your hand.
JACK (V.O.) Guided meditation worked for cancer, it could work for this.
Tyler looks at Jack's glazed and detached eyes.
TYLER Come back to the pain.
TYLER Don't shut this out.
Jack, snapping back, tries to jerk his hand away.
Tyler keeps hold of it and their arms KNOCK UTENSILS off the table.
JACK (V.O.) I tried not to think of the words "searing" or "flesh."
JACK (V.O.) I imagined my pain as a ball of healing white light.
Tyler JERKS Jack's hand, getting Jack's attention...
TYLER Stop it.
TYLER This is your pain -- your burning hand.
TYLER It's right here.
TYLER Look at it.
JACK (V.O.) I was going to my cave to find my power animal.
Tyler JERKS Jack's hand again.
Jack re-focuses on Tyler...
TYLER Don't deal with this the way those dead people do.
TYLER Deal with it the way a living person does.
Jack tries to pull his hand free.
Tyler won't let go.
Jack's eyes glaze over again.
Jack speaks, whiny from pain:
JACK I...
JACK I think I understand.
JACK I think I get it...
TYLER No, what you're feeling is premature enlightenment.
Tyler SLAPS Jack's face, regaining his attention...
TYLER This is the greatest moment of your life and you're off somewhere, missing it.
JACK No, I'm not...
TYLER Shut up.
TYLER Our fathers were our models for God.
TYLER And, if our fathers bailed, what does that tell us about God?
JACK I don't know...
Tyler SLAPS Jack's face again...
TYLER Listen to me.
TYLER You have to consider the possibility that God doesn't like you, he never wanted you.
TYLER In all probability, He hates you.
TYLER This is not the worst thing that can happen...
JACK It isn't...
TYLER We don't need him...
JACK We don't...
Jack is a wide-eyed zombie...
JACK ...
JACK Marla ...
TYLER Fuck damnation.
TYLER Fuck redemption.
TYLER We are God's unwanted children, with no special place and no special attention, and so be it.
Jack looks at Tyler -- they lock eyes.
Jack does his best to stifle his spasms of pain, his body a quivering, coiled knot.
He bolts toward the sink, but Tyler holds on.
TYLER You can go to the sink and run water over your hand.
TYLER Look at me.
TYLER Or you can use vinegar to neutralize the burn, but first you have to give up.
TYLER First, you have to know that someday, you are going to die.
TYLER Until you know that, you will be useless.
Jack spasms with a shiver of pain...
JACK You ...
JACK you don't know what this feels like, Tyler.
Tyler shows Jack a LYE-BURNED KISS SCAR on his own hand.
Tears begin to drip from Jack's eyes.
Tyler grabs a bottle of VINEGAR -- pours it over Jack's wound.
Jack closes his eyes, holds his hand...
slumps to the floor.
TYLER Congratulations.
TYLER You're a step closer to hitting bottom.
Jack and Tyler, in trench coats, looking like deaht-warmed- over, wait as a BUYER fills out forms.
There are bars of "The Paper Street Soap Company" soap on the counter.
Jack looks like he's half-expecting to get arrested.
His hand is BANDAGED.
JACK (V.O.) Tyler sold the soap to department stores at twenty bucks a Ear.
JACK (V.O.) God knows what they charged.
JACK (V.O.) How ironic.
JACK (V.O.) We were selling rich women their own fat asses back to them.
Jack sits at his desk, playing a game on his computer, smoking a cigarette.
Boss enters.
JACK (V.O.) He was wearing a yellow tie.
JACK (V.O.) It must be Thursday.
JACK (V.O.) I didn't even wear a tie to work anymore.
Boss slaps a piece of PAPER down on Jack's desk.
BOSS "The first rule of fight club is you don't talk about fight club."
Jack snuffs his cigarette in an ashtray, stares up stoically.
JACK (V.O.) I must've left the original in the copy machine.
BOSS "The second rule of fight club...
BOSS Is this yours?
JACK Hmm?
BOSS You don't get paid to abuse the copy machine.
JACK "Abuse" the copy machine.
JACK There's an image.
BOSS Pretend you're me.
BOSS You find this.
BOSS What would you do?
Jack rises slowly, walks to his door, shuts it.
JACK Me?
JACK I'd be very careful who I talked to about this.
JACK It sounds like someone dangerous wrote it...
JACK someone who might snap at any moment, stalking from office to office with an Armalite AR-10 Carbine-gas semiautomatic, bitterly pumping round after round into colleagues and co- workers.
Jack moves very close to Boss, picks up the PAPER and starts tearing it into pieces.
JACK Might be someone you've known for years...
JACK somebody very close to you.
JACK Or, maybe you shouldn't be bringing me every little piece of trash you pick up.
Jack puts the PAPER in his trash.
Bass stares with a tinge of outrage, a tinge of fear.
PHONE RINGS.
Jack answers it.
JACK Compliance and Liability.
MARLA'S VOICE My tit's going to rot off.
JACK Just a second.
JACK Could you excuse me?
JACK I need to take this call.
Boss goes to the door, stares at Jack a beat, then leaves.
JACK What are you talking about?
MARLA Would you do something for me?
MARLA I need you to check and see if there's a lump in my breast.
MARLA I can't afford to throw money away on a doctor.
JACK I don't know ...
MARLA Please.
JACK (V.O.) She didn't call Tyler.
JACK (V.O.) I'm neutral in her book.
Jack walks down the sidewalk, seeing Marla take two BOXES from a VAN with the sign "MEALS ON WHEELS."
Marla leads Jack inside.
JACK This is a sweet side of you.
JACK Picking these up for ...
JACK "Mrs.
JACK Haniver" and...
JACK "Mrs.
JACK Raines."
JACK Where are they?
MARLA Tragically, they're dead.
MARLA I'm alive and I'm in poverty.
MARLA You want any?
JACK No, thanks.
MARLA Good.
He stares at her while she eats.
MARLA What happened to your hand?
Jack awkwardly puts his bandaged hand behind his back.
JACK Nothing.
Marla stands facing a MIRROR with her shirt open.
Jack stands behind her with his hand on the bottom side of her breast.
Marla's hand guides his.
JACK Where?
JACK Here?
MARLA Here.
JACK There?
MARLA Here.
JACK Here.
MARLA Feel anything?
JACK No.
Jack's head is behind Marla's.
They speak softer, slower.
MARLA Make sure.
JACK Okay.
JACK Okay, I'm sure.
MARLA You feel nothing?
JACK Nothing.
Marla turns around and faces him, begins to button her shirt.
MARLA Well, that's a relief.
MARLA Thank you.
JACK No...
JACK no problem.
MARLA I wish I could return the favor.
Jack touches his own chest, shakes his head.
JACK I think everything's okay here.
MARLA I could check your prostate.
JACK Uh ...
JACK nah.
MARLA Well...
MARLA thanks, anyway.
Marla leans to kiss him -- lingers for a bit longer than just friendly.
Jack pulls away.
JACK So....
JACK are we done?
Marla sighs.
MARLA Yeah, we're done.
MARLA See you around.
Jack emerges from the lobby.
He looks up at Marla's window, watches her silhouette.
He walks away, right into -- Big BOB, the moose, eating a donut and drinking orange juice.
BOB Cornelius!
BOB How are you?
JACK Bob.
JACK I'm okay.
JACK How are you?
BOB Better than I've ever been in my life.
JACK Really?
JACK Great.
JACK Still "Remaining Men Together?"
An intense look of born-again fervor comes over Bob's face.
BOB No.
BOB I found something new.
JACK Really, what's that?
BOB The first rule is...
BOB you aren't supposed to talk about it...
JACK Oh.
BOB And the second rule about it is...
BOB you're not supposed to talk about it.
BOB And the third rule...
JACK Bob, Bob...
JACK I'm a member.
BOB You are?!
JACK Look at my face.
Bob roughly slaps Jack's shoulder.
BOB That's a fucking great, man!
BOB Fucking great!
BOB Congratulations.
JACK Yeah, both of us.
BOB You know about the guy who invented it?
BOB I hear all kinds of things.
BOB Supposedly, he was born in a mental institution.
BOB They say he only sleeps one hour a night.
BOB You know about this guy?
BOB Tyler Durden?
The CROWD SCREAMS insanely as Bob and Jack go at it in the circle of light.
Bob's eyes are wild with glee.
Everyone sneaks out of this new location - we've seen none of these guys before - it's a new chapter.
Jack and Bob Stagger out last, Jack being in worse shape.
They both grin with religious serenity.
Bob hugs Jack.
BOB Thank you.
BOB Thank you.
Bob relaxes the hug and Jack drops to the ground like a sack, completely enervated from the beating he took.
JACK You're welcome.
JACK (V.O.) Fight club -- this was mine and Tyler's gift...
JACK (V.O.) our gift to the world.
Jack has his briefcase on the table, looks at PAPERWORK.
Tyler wanders in, carries a dirty pot to the sink.
Jack takes out a cigarette, lights up.
He offers the pack...
TYLER No thanks, I quit.
JACK You quit?
TYLER Yeah.
TYLER Where you headed?
JACK Work.
JACK Going to work.
Tyler scratches his chin absently.
JACK What...
TYLER Nothing.
TYLER Do what you like.
Tyler walks out the way he came.
Jack sits staring at his SCREEN SAVER.
Jack steps into the open doorway, knocks on the doorframe.
Boss looks up from his large, expensive desk.
JACK We need to talk.
BOSS Okay.
BOSS Where to begin?
BOSS With your constant absenteeism?
BOSS With your unpresentable appearance?
BOSS You're up for review...
JACK I Am Jack's Complete Lack of Surprise.
Boss sits up in his seat, becoming enraged.
JACK Let's pretend.
JACK You're the Department of Transportation, and you discover that our company intentionally did nothing about leather seats cured in third world countries with chemicals we know cause birth defects?
JACK Brake linings that fail after a thousand miles.
JACK Fuel injectors that burn people alive.
BOSS Just who the fuck do you think you are?!
BOSS Get out!
BOSS You're fired!
JACK What about this?
JACK Keep me on payroll as an outside consultant.
JACK In exchange for my salary, I'll keep my mouth shut.
JACK I won't need to come to the office.
JACK I can do this job from home.
Boss stands, moves around his desk, glaring with rage.
BOSS You little fucker!
BOSS I oughta...
Jack PUNCHES HIMSELF in the nose.
Blood starts to trickle.
He punches himself in the jaw, throws himself back as if by the force of the punch, SLAMS against a framed picture and SHATTERS the glass.
He falls to the floor.
JACK (V.O.) I Am Jack's Smirking Revenge.
Jack gets back to his feet.
JACK Please...
JACK don't hit me again, please.
JACK I'm your responsibility...
He PUNCHES himself in the stomach, then in the jaw again.
He reels backwards, pulls down a hanging shelf, its contents flying.
He hits the floor.
JACK (V.O.) For some reason, I thought of my first fight -- with Tyler.
Jack crawls toward Boss, dripping blood, grabs Boss's leg.
JACK Please...
JACK give me the paychecks like I asked for.
JACK I won't be any trouble.
JACK You won't see me again.
Jack climbs up Boss's leg while Boss tries to shake him off.
Boss stumbles back into his desk, knocking off belongings.
JACK (V.O.) Under and behind and inside everything this man took for granted, something horrible had been growing.
Jack crawls high enough to grab Boss's belt, hoisting himself up.
He dribbles blood an Boss's clothing, SMUDGES blood from his face onto the knuckles of Boss's hand.
JACK Please...
JACK please...
JACK (V.O.) And right then, at our most excellent moment together...
Two SECURITY GUARDS enter and gape at the sight.
Behind them stand CURIOUS WORKERS, looking in.
JACK Please don't hit me again.
Jack holds a CHECK in front of Tyler's face.
JACK Six months advance pay.
JACK Six months!
TYLER Fucking sweet.
JACK Okay, and...
JACK and...
Jack digs in his pocket, takes out a thick bundle of CARDS.
JACK Forty-eight airline flight coupons.
JACK Plus...
JACK hold on...
JACK just a minute...
Jack holds up a finger, going to open the front door.
He drags an unwieldy SHOPPING CART in behind him; filled with his COMPUTER, PHONE, FAX and other office equipment.
JACK I am now officially self-employed.
Jack looks at the cart, then back at Tyler, proud.
TYLER Good for you.
LOUD.
An enormous CROWD of guys, including Jack and Bob, stands around Tyler, who's in the center of the circle, holding up his hands to quiet them...
TYLER I look around...
TYLER I look around and see a lot of new faces.
An enthusiastic RUMBLE from the crowd.
TYLER Shut up!
TYLER Which means a lot of you have been breaking the first two rules of fight club.
A glum silence falls.
Guys look at each other.
TYLER I see in fight club the strongest and smartest men who have ever lived -- an entire generation pumping gas and waiting tables; or they're slaves with white collars.
TYLER (cont) Advertisements have them chasing cars and clothes, working jobs they hate so they can buy shit they don't need.
TYLER (cont) We are the middle children of history, with no purpose or place.
TYLER (cont) We have no great war, or great depression.
TYLER (cont) The great war is a spiritual war.
TYLER (cont) The great depression is our lives.
TYLER (cont) We were raised by television to believe that we'd be millionaires and movie gods and rock stars -- but we won't.
TYLER (cont) And we're learning that fact.
TYLER (cont) And we're very, very pissed-off.
The crowd erupts into a DEAFENING CHORUS of agreement.
Jack looks at the blazing excitement in the eyes of the crowd.
TYLER We are the quiet young men who listen until it's time to decide.
A fat, MIDDLE-AGED MAN stomps down the stairs, pushing into the crowd, followed by a TALL, HEFTY THUG who holds a GUM.
TYLER Who are you?
FAT MAN (LOU) Who am I?!
FAT MAN (LOU) There's a sign on the front that says "Lou's Tavern."
FAT MAN (LOU) I'm fucking Lou.
FAT MAN (LOU) Who the fuck are you?!
TYLER Tyler Durden.
Tyler extends his hand for a shake, but Lou SLAPS it away.
LOU Who told you motherfuckers you could use my place?
TYLER We have a deal worked out with Irvine.
LOU Irvine?
LOU Irvine's at home with a broken collarbone.
Everyone glances guiltily at each other.
LOU He don't own this place, I do.
LOU How much money's he getting for this?
TYLER There is no money.
LOU Really?
TYLER It's free to all.
LOU Ain't that something?
TYLER Yes, it is.
LOU Look, stupid fuck, I want everyone outta here now!
TYLER You're welcome to join our club.
LOU Did you hear what I just said?!
TYLER You and your friend.
Lou SLUGS Tyler in the stomach, doubles him over.
LOU You hear me now?
Tyler gains his breath, determined.
He looks up, turns his head, looking to Jack.
Jack watches, wide-eyed.
Tyler straightens, facing Lou.
TYLER No, I'm sorry, I didn't hear you.
Lou PUNCHES Tyler in the face.
Some of the guys move forward, but the Thug points his gun.
Jack-runs forward anyway -- Lou PUNCHES him in the face.
More guys move forward, but Tyler waves them off, facing Lou.
TYLER We really need to use this place.
Lou proceeds to beat the shit out of Tyler, PUNCHING his face, his stomach.
Tyler collapses to the floor.
Lou starts KICKING his.
Tyler bleeds from the mouth and face.
TYLER That's it....
TYLER that's good.
TYLER Get it all out.
TYLER You'll feel better.
Lou flushes red with exasperation, KICKS more.
Finally, sweating, bewildered, Lou stops.
He looks to the Thug, who is just as bewildered.
Suddenly, Tyler SPRINGS UP, grabs onto Lou...
TYLER Yes, I am shit and crazy, to you and this whole fucking world...
Tyler's blood spatters on Lou.
Lou tries to shake Tyler off, but Tyler BITES Lou's NECKTIE.
The Thug grabs Tyler and pulls, the necktie tightening and strangling Lou.
Lou slaps at Tyler's face, but recoils from the blood.
Tyler spits and shouts through clenched teeth...
TYLER You don't know where I've been.
Tyler bear hugs Lou, pulls him to the floor.
Tyler rubs his bloody face into Lou's face.
The Thug lifts Tyler.
Tyler clings to Lou's belt, dragging Lou as he is dragged...
TYLER We need this place.
TYLER We need it.
TYLER Please let us keep it, please...
Blood dribbles out of Tyler's mouth, spattering Lou.
LOU What are you doing?!
TYLER Pleeeeeease!
LOU Okay!
LOU Okay, fuck it!
LOU Use the basement!
LOU Get off me!
TYLER We need some towels, Lou.
TYLER We need replacement light bulbs.
LOU Alright, Christ!
LOU Fucking let me go!
TYLER Thank you.
TYLER Thank you, sir...
LOU Let go of me!!
Tyler lets go of Lou's belt.
Lou scrambles away.
The Thug drops Tyler, trying to keep clear of the blood.
Lou gets to his feet, looks at Tyler, then at the rest of the guys.
He and the Thug back away...
slamming the door behind.
Fight club surrounds Tyler.
They help him up, move him to a crate.
Tyler sits slumped for a long moment, his breathing labored...
then, he sits back, crossing his legs and looking to the group, his demeanor businesslike.
TYLER This week, each of you has a homework assignment.
TYLER You're going to go out and start a fight with a total stranger...
TYLER You're going to start a fight...
TYLER and you're going to lose.
Jack beams in appreciation.
Ricky trips a passing YUPPIE.
The Yuppie falls.
JACK (V.O.) Not as easy as it sounds.
JACK (V.O.) People'll do just about anything to avoid a fight.
The Yuppies gets up, angry, and Ricky PUNCHES him...
YUPPIE Hey!
YUPPIE Wha...
YUPPIE What the hell...
YUPPIE what are you doing?!
YUPPIE Who are you?!!
The Yuppie backs away.
Ricky follows...
YUPPIE Get away from me!
YUPPIE Keep away!
Ricky TACKLES the Yuppie.
The Yuppie struggles spastically.
YUPPIE Who are you!?
YUPPIE Why are you attacking me...
YUPPIE ?!
Having no recourse, the Yuppie begins trading blows.
A MECHANIC WITH A BATTERED FACE uses a hose to wash the sidewalk.
As MEN pass, he jerks the hose up and SPRAYS them.
FIRST MAN Hey...
FIRST MAN hey...
SECOND MAN Watch out, jackass!
These men continue on their way.
The Mechanic sprays a third man, a SEMINARY STUDENT, who looks down, stunned.
SEMINARIAN You...
SEMINARIAN you did that on purpose!
The Mechanic DOUSES the Seminarian.
The Seminarian grabs the hose, wrestling the Mechanic for it.
The Mechanic shoves the Seminarian, who responds with a half-assed PUNCH.
The Mechanic purposely takes it.
The Seminarian starts to run away.
The Mechanic sprints after him, PUNCHING the Seminarian in the back of the neck.
They fight.
A FIST smashes a JAW.
Guys CHEER.
An arm snakes around a neck and squeezes, blood and sweat dripping.
It's the YUPPIE and the SEMINARIAN fighting.
Tyler walks around the perimeter of the circle.
JACK (V.O.) Now nobody was the center of fight club except the two men fighting.
JACK (V.O.) The leader walked around in the crowd, out in the darkness.
Tyler hands ENVELOPES out to the crowd.
JACK (V.O.) Everyone took a homework assignment.
Ricky and another FIGHT CLUBBER paste up a BILLBOARD which reads: "DID YOU KNOW?
YOU CAN USE YOUR OLD MOTOR OIL TO
HANDS use a MARKER, writing on a FILE: "Disinformation."
Jack and Tyler, in work gloves, armed with TOOLS, work together to lift the entire METAL PLATE of EXIT SPIKES from the ground.
They reverse it, then replace it.
Jack and Tyler walk away, each carrying a 4x4 plank of WOOD.
JACK There's fight club in Delaware City.
TYLER I heard.
TYLER Local 15, Monday nights.
As they pass PARKED CARS, they SWING the planks against front bumpers -- activating ALARMS and INFLATING AIR BAGS...
JACK Local 8 just started in Penns Grove.
JACK And, Bob said he was at fight club in Newcastle last week.
TYLER Newcastle?
TYLER Did you start that one?
JACK I thought you did.
In the background, a CAR quickly EXITS the parking lot -- front tires EXPLODING, wheel rims throwing sparks.
FATHER, MOTHER, YOUNG DAUGHTER and SON, eat dinner, watching TELEVISION.
Suddenly, the TV IMAGE turns to SNOW and static.
Family members stop eating.
Father picks up the REMOTE, points it -- all channels are SNOW.
Father turns the TV OFF.
He and his family members look at each other, utensils in hand, uncomfortable.
The Yuppie SWINGS a BASEBALL BAT -- DESTROYS a digital SATELLITE DISH.
The Yuppie and the Seminarian move on, climbing to a neighboring rooftop.
They come upon another DISH.
The Seminarian takes the bat, takes a SWING...
HANDS place NEWS CLIPPINGS into a FILE: "Mischief."
Two AIRPLANE MAINTENANCE,MEN, with bruised faces, rip open a box from a PRINT SHOP.
They dig up AIRPLANE SAFETY INSTRUCTION CARDS and begin inserting them into each seatback.
We SEE a CARD - it shows passengers SCREAMING and FLAILING ABOUT IN TERROR.
Huge office.
Rows and rows of desks.
FIGHT CLUB MEMBERS work: one guy moving from COMPUTER MONITOR to COMPUTER MONITOR, using a DRILL to drill a hole into the top of each.
Other guys follow behind, with FUNNELS and CANS of GASOLINE, filling each monitor with gasoline.
Files and newspaper clippings are piled up.
HANDS write on a new FILE FOLDER: "Arson."
The Yuppie crumbles a loaf of stale bread into a bucket, stirring it with a big spoon, mixing in a BOTTLE of EX-LAX.
Nearby, Rob throws handfuls of wet BREADCRUMBS to PIGEONS...
HUNDREDS of PIGEONS -- a rooftop feeding-frenzy.
Tyler and Jack cross the parking lot, towards the convenience store.
Jack wears a BACKPACK.
TYLER Let me have that a minute...
Tyler takes the BACKPACK, unzips it, searching the contents.
JACK What are we doing?
TYLER Homework assignment.
JACK What is it?
Tyler takes out a HANDGUN, hands the backpack back.
TYLER Human Sacrifice.
Jack turns white, staring at the gun.
The BACK DOOR opens and Tyler brings the store's CLERK out at gunpoint, forces him to his knees.
Jack follows, freaked.
Tyler points the gun at the Clerk.
JACK (V.O.) On a long enough time line, the survival rate for everyone drops to zero.
CLERK Please...
CLERK don't...
TYLER Give me your wallet.
The Clerk fumbles his wallet out of his pocket and Tyler snatches it.
Tyler pulls out the DRIVER'S LICENCE.
TYLER Raymond K. Hessel.
TYLER 1320 SE Benning, apartment A. A small, cramped basement apartment.
RAYMOND How'd you know?
TYLER They give basement apartments letters instead of numbers.
TYLER Raymond, you're going to die.
Tyler rummages through the wallet.
TYLER Is this a picture of Mom and Dad?
RAYMOND Yesssss...
TYLER Your mom and dad will have to call kindly doctor so-and-so to dig up your dental records, because there won't be much left of your face.
RAYMOND Please, God, no...
Raymond begins to weep, shoulders heaving.
JACK Tyler...
TYLER An expired community college student ID card.
TYLER What did you used to study, Raymond K. Hessel?
RAYMOND S-S-Stuff.
TYLER "Stuff."
TYLER Were the mid-terms hard?
Tyler rams the gun barrel against Raymond's temple.
TYLER I asked you what you studied.
JACK Tell him!
RAYMOND Biology, mostly.
TYLER Why?
RAYMOND I...
RAYMOND I don't know...
TYLER What did you want to be, Raymond K.
TYLER Hessel?
Raymond weeps and says nothing.
Tyler COCKS the gun.
Raymond GASPS.
TYLER The question, Raymond, was "what did you want to be?"
A beat.
JACK Answer him!
RAYMOND A veterinarian!
TYLER Animals.
RAYMOND Yeah ...
RAYMOND animals and s-s-s ---
TYLER Stuff.
TYLER That means you have to get more schooling.
RAYMOND Too much school.
Tyler shoves Raymond's wallet back into Raymond's pocket.
TYLER Would you rather be dead?
RAYMOND No, please, no, God, no!
Tyler moves the gun right between Raymond's eyes.
Tyler UNCOCKS the gun, lowers it.
TYLER I'm keeping your license.
TYLER I know where you live.
TYLER I'm going to check on you.
TYLER If you aren't back in school and on your way to being a veterinarian in six weeks, you will be dead.
TYLER Get the hell out of here.
Raymond staggers to his feet, heads down an alleyway.
Jack and Tyler watch Raymond flee, then Tyler looks at Jack.
JACK I feel sick.
TYLER Imagine how he feels.
Tyler brings the gun to his own head, pulls the trigger -- CLICK.
Empty.
JACK I don't care, that was horrible.
Tyler walks away.
TYLER Tomorrow will be the most beautiful day of Raymond K. Hessell's life.
Jack watches Tyler go.
TYLER His breakfast will taste better than any meal he has ever eaten.
Jack turns to look the direction Raymond ran.
He finally turns back, following after Tyler.
SLOW MOTION: in the deserted office, gasoline filled COMPUTER MONITORS begin to EXPLODE...BOOM...BOOM...BOOM...
Luxury AUTOMOBILES are parked, splattered with BIRD SHIT.
VIEWED OUT 3RD STORY WINDOW: Tyler uses a RAKE, dragging it across rocks and dirt.
He stops a moment, rake on his shoulder, staring off.
Then, back to work...
TYLER ...
TYLER You are not how much money you have in the bank.
TYLER You are not the shoes you wear.
Tyler's marking a large SQUARE in the weeds and rubble of the backyard, kicking rocks away, dragging the rake...
TYLER You are not the contents of your wallet...
The DRIVER has a broken nose.
The bus is empty, except for Jack, in the very last seat, sleepy.
JACK (V.O.) He had a plan.
JACK (V.O.) Maybe you just didn't see it till it hit you between the eyes.
JACK (V.O.) But, it started to make sense...
JACK (V.O.) in a Tyler sort of way.
JACK (V.O.) No fear.
JACK (V.O.) No distractions.
JACK (V.O.) The ability to let that which does not matter truly slide.
Jack gets off the bus.
As the bus pulls away, we see it dropped Jack off right in front of the house.
Jack enters.
Tyler, dressed in FATIGUES and splattered with PAINT, grabs BEERS from the refrigerator.
JACK Hey.
TYLER Hey.
Jack notices ROPE and RAPPELLING TOOLS on the table.
Tyler comes to hand Jack a bunch of beers, nod to the living room.
TYLER Go on in.
TYLER We're celebrating.
Jack, bewildered, enters carrying beers.
Tyler does NOT follow.
BOB, RICKY and several other fight club guys sit in front at the TV, chanting not too loudly, all also dressed in FATIGUES and splattered with PAINT.
RICKY You are not your job.
OTHERS TOGETHER You are not your job.
RICKY You are not how much money you have in the bank.
BOB Shhhh, wait...
BOB they're back to it...
Bob goes to turn up the TV.
One guy, sixteen years old with an angelic face, ANGEL FACE, gets up to take beer from Jack.
ANGEL FACE Great, thanks.
Angel face starts distributing beer amongst his cohorts.
BOB Shhhhh!
BOB Watch!
Jack looks to the TV -- it shows a LIVE shot of the "PARKER MORRIS BUILDING."
The building has a GIANT, GRINNING FACE PAINTED on it -- two BROKEN WINDOWS for EYES, with flames pouring out...
FIRETRUCKS spray water.
REPORTER (V.O.) Police Commissioner Jacobs has just arrived...
REPORTER (V.O.) just a second...
REPORTER (V.O.) excuse me, Commissioner, could you tell us what you think has happened?
COMMISSIONER JACOBS, a wrinkled official, turns to camera.
COMMISSIONER JACOBS (V.O.) We believe this is related to the recent acts of vandalism around the city.
COMMISSIONER JACOBS (V.O.) It's some kind of organized group, and we are coordinating a rigorous investigation.
Jack turns, sees Tyler in the archway, watching him.
Tyler tips his beer to toast, pulls back, out of sight.
JACK What did you guys do?
They all BURST INTO LAUGHTER.
They look at Jack and shake their heads.
Jack doesn't get it.
Suddenly, the guys' faces turn to stone.
Bob sits rigid.
BOB The first rule of Project Mayhem is...
BOB you do not ask questions.
Jack stares at them.
A luxurious BANQUET.
Commissioner Jacobs guzzles champagne.
He rises and starts out of the room.
Jack, in a WAITER'S UNIFORM, looks apprehensively to OTHER WAITERS: BOB...
RICKY...
ANGEL FACE -- who all give each other a look.
Jacobs saunters down an empty hall.
He stops to check his tie in a mirror.
He pushes open the door of the MEN'S BATHROOM -- face to face with TYLER.
Tyler GRABS Commissioner Jacobs, pulling him into the bathroom.
He slaps a piece of tape over Jacobs' mouth.
The OTHER "WAITERS" rush in.
Jack stays back to keep the door shut.
Tyler and the others hold Jacobs, pulling down his pants.
Bob snaps a rubber band -- reaches to Jacob s crotch.
TYLER Wrap it around the top of his hackie- sack.
BOB Man, his balls are ice cold.
Ricky produces a KNIFE, moves it down to Jacob's testicles.
Jacobs is bug-eyed.
Jack, red-faced, keeps his distance.
TYLER You're not going to continue your "rigorous investigation."
TYLER You will publicly state that there is no underground group.
TYLER Or -- imagine, the rest of your life with your scrotum flapping empty.
JACOBS ...
JACOBS no...
JACOBS please, no...
TYLER We'll send one to the New York Times and one to the Los Angeles Times.
TYLER Press release style.
TYLER Your nuts will be bicoastal.
TYLER Understood?
TYLER The people you're after are everyone you depend on.
TYLER (cont) We do your laundry, cook your food and serve you dinner.
TYLER (cont) We guard you while you sleep.
TYLER (cont) We drive your ambulances.
TYLER (cont) Do not fuck with us.
Ricky makes a dramatic cut with the knife, causing Jacobs to JUMP -- Ricky holds up the severed RUBBER BAND.
Jack, Tyler and the others file quickly out the back SERVICE ENTRANCE.
Tyler gives Angel Face a hearty slap on the back.
Angel Face smiles at Tyler, nods, grinning.
Jack sees this, his eyes narrowing, stops walking.
Fight club in full swing.
Jack battles Angel Face, BEATING the shit out of him with unprecedented viciousness.
JACK (V.O.) I felt like putting a bullet between the eyes of every Panda that wouldn't screw to save its species.
The crowd shouts maniacally, save Tyler, who watches with an inscrutable stone face.
Angel Face tries to speak, but Jack POUNDS too hard.
Blood flies.
The crowd begins to grow QUIETER.
JACK (V.O.) I wanted to open the dump valves on oil tankers and smother all the French beaches I'd never see.
Finally, Angel Face lies still, unconscious.
Jack stops, stares down, numb.
Jack walks away -- the crowd parts to let him pass.
Jack scans faces...
finds Tyler.
TYLER Where did you go, Psycho-Boy?
JACK I felt like destroying something beautiful.
RAINING.
Tyler and Jack walk through pools of streetlight.
A idling car HONKS.
Tyler leads Jack toward it.
A bruised- faced VALET PARKER thrown keys to Tyler, but Jack intercepts.
VALET There you are, Mr. Durden.
VALET Airport parking, long term.
JACK After you, Mr. Durden...
TYLER No...
TYLER after you.
Tyler gets in the driver's seat.
Jack gets into the front passenger seat.
Ricky and the mechanic are in back.
Tyler pulls the stolen car away from the curb.
It has two bumperstickers: "RECYCLE YOUR ANIMALS" and "MAKE MINE VEAL."
RAIN GUSHES down.
Jack stews, silent.
The car moves down a HIGHWAY, intermittently illuminated by oncoming headlights.
TYLER Something on your mind?
JACK No.
Tyler shrugs; turns on the RADIO, ignores Jack.
JACK Why wasn't I told about "Project Mayhem?"
TYLER What should I have told you?
JACK Why wasn't I involved from the beginning?
JACK You and I started fight club together.
TYLER Fight club was the beginning.
TYLER Now it's out of the basements and there's a name for it -- Project Mayhem.
RICKY AND MECHANIC The first rule of Project Mayhem is you do not ask questions.
JACK This is as much mine as yours.
TYLER Is this a needlepoint club?
TYLER Is it about you and me?
JACK You know what I mean.
TYLER What do you want?
TYLER A statement of purpose...
JACK Look...
TYLER Should I E-mail you?
TYLER Should I put this on your "action item list?"
JACK I want to know --
TYLER What do you want to know about Project Mayhem?
RICKY AND MECHANIC The first rule of Project Mayhem --
JACK Shut up!!
JACK I want to know what's going on.
Tyler steers the car into the opposite lane, accelerates...
Opposing HEADLIGHTS get closer fast...
TYLER This does not belong to us.
TYLER We are not the leaders.
TYLER We are not special.
JACK What are you doing?!
TYLER We are the all-singing, all-dancing crap of the world.
TYLER We are all part of the same compost heap...
JACK Tyler...
Tyler steers back into the proper lane.
The other CAR flies past, HORN SOUNDING...
JACK What the hell ...
JACK ?!
TYLER You choose your level of involvement.
TYLER I won't make decisions for you.
JACK I'm not asking you to.
TYLER You're asking questions that don't have answers.
TYLER You know just as much about Project Mayhem as anybody else.
JACK I don't think that's true.
Tyler again steers into the oncoming lane, speeding up.
Through the windshield: oncoming headlights -- a TRUCK.
JACK Tyler...
JACK what is this...
Jack fights to turn the wheel, but Tyler uses both hands.
TYLER What will you wish you'd done before you died?
RICKY Paint a self-portrait.
MECHANIC Build a house.
TYLER And you?
JACK I don't know!
JACK Nothing!
TYLER If you died right now, how would you feel about your life?
JACK I would feel nothing about my life?
JACK Is that what you want to hear?!
The oncoming truck HONKS and FLASHES its LIGHTS.
It moves to the other side of the road.
Tyler steers there, too.
TYLER I want to hear the truth.
JACK Fuck my life.
JACK Fuck fight club.
JACK Fuck you and fuck Marla.
JACK I'm sick of this.
JACK How's that?
TYLER Why do you think I blew up your condo?
JACK What?
TYLER Hitting bottom isn't a weekend retreat!
TYLER It's not a seminar!
TYLER You have to forget everything you know, everything you think you know -- about life, about friendship, about you and me.
Nearing impact with the oncoming truck, Tyler takes his hands off the wheel -- Jack keeps his grip, turns the wheel...
the car swerves...
The truck ROARS past, spraying water, HORN BLASTING.
Tyler looks at Jack, his hands in the air.
Jack looks at Tyler with dead eyes.
JACK Okay, okay...
JACK fine...
Jack takes his hands off the wheel, holds them in the air.
Tyler studies Jack face, impressed.
Tyler makes no move to take the wheel.
THROUGH THR WINDSHIELD: a STALLED CAR ahead on the side of the road, surrounded by flares.
Jack and Tyler's eyes stay locked as the car drifts onto the shoulder...
heading for the stalled car.
Their faces are illuminated by the light of the flares.
Tyler smiles.
They SMASH into the stalled car -- AIRBAGS INFLATE!
The back of their car whips around and carries it into a ass- over-tea-kettle ROLL down a hill...
JACK (V.O.) I'd never been in a car accident.
JACK (V.O.) This must've been what all those statistics felt like before I filed them into my reports.
The car finally hits the bottom, lying on its roof.
Tyler crawls from the passenger side.
He walks around...
opens the driver's side door and drags Jack out into the mud.
Ricky and the Mechanic climb out the broken rear window.
Tyler sits beside the stunned, wounded Jack.
TYLER We just had a near-life experience.
Jack lies in bed, traumatized, eyes empty, staring at the ceiling.
Tyler sits in a nearby chair.
TYLER In the world I see -- you're stalking elk through the damp canyon forests around the ruins of Rockefeller Center.
TYLER You will wear leather clothes that last you the rest of your life.
TYLER You will climb the wrist- thick kudzu vines that wrap the Sears Tower.
TYLER You will see tiny figures pounding corn and laying-strips of venison on the empty car pool lane of the ruins of a superhighway.
Tyler stands, gives Jack's head a pat.
TYLER Feel better, champ.
Jack sits at the table, sips coffee.
He's pale, dazed, seems broken.
He hears the faint SOUND of SAWING and HAMMERING, unsure of where it's coming from.
Marla walks into the kitchen and goes straight to the counter.
Her back is to Jack as he looks at her.
She pours ccffee and lights a cigarette.
A beat of silence, then:
MARLA I'll be out of your way in a sec.
She seems to be as weak as Jack.
JACK You...
JACK don't have to...
JACK leave.
MARLA Whatever.
JACK Really...
JACK I mean it.
JACK Have you been going to your groups?
MARLA Chloe's dead.
JACK When?
MARLA Do you care?
JACK I don't know.
MARLA It was the smart move on her part.
Marla turns to face Jack, a grim expression on her face.
There's a BRUISE on her ARM.
Jack gets up, moves closer.
JACK Why are we both...
JACK caught up like this...
JACK with...
JACK (V.O.) I came so close to saying Tyler's name, I could feel it vibrate inside my mouth.
Marla looks a him, waiting.
JACK I don't understand.
JACK Why does a weak person have to go out and find a strong person...
JACK to hang onto?
MARLA What do you get out of it?
Faint SOUND of SAWING and HAMMERING.
Jack can't quite figure where it's coming from.
JACK You hear that?
MARLA Hear what?
JACK That...
JACK sawing and hammering.
MARLA Have we been talking too long?
MARLA Must we change the subject?
Jack turns -- through the crack of the open basement door, Tyler's staring at Jack from the bottom of the stairs.
TYLER You're not talking about me, are you?
Jack reacts, turns back to Marla.
JACK No.
MARLA That day you came over to my place to play doctor...
MARLA what was going on there?
TYLER What are you talking about?
JACK Nothing.
MARLA Nothing?
MARLA I don't think so.
TYLER This conversation...
JACK This conversation...
TYLER ...
TYLER is over.
JACK ...
JACK is over.
Marla comes to touch Jack's hair.
Jack closes the basement door.
Marla sees the kiss-scar on Jack's hand, grabs his hand.
Jack tries to pull it back, but Marla keeps a grip.
MARLA What is this?
MARLA Who did this?
JACK ...
JACK A person.
MARLA Guy or girl?
JACK Why would you ask if it's a guy or a girl?!
MARLA Why would you get bent if I asked?
JACK Let go of me...
JACK Leave me alone.
MARLA You're afraid to say.
Marla backs away, closes her eyes, struggling with frustration.
She leaves out the back door, not looking back.
Jack leans against the wall.
After a moment, he opens the basement door, heads downstairs...
Tyler walks upstairs, passing as Jack continues down...
Jack looks around.
TRIPLE-DECKER BUNKS clutter the basement, as many as can fit into the space.
JACK Tyler...
JACK What's this for?
From upstairs, the SOUND of the DOORBELL.
Jack opens the door.
Ricky stands on the porch, staring ahead in subordinate military style.
He's in black pants, black shirt, black shoes, holds a PAPER BAG, with an army surplus MATTRESS rolled-up at his feet.
JACK Um...
JACK what can I do for you, Ricky?
Tyler steps up beside Jack, looks Ricky over.
TYLER You're too young.
TYLER Sorry.
JACK Wait a minute...
Tyler comes back inside, shuts the door.
JACK "Too young?"
TYLER If the applicant is young, we tell him he's too young.
TYLER Old, too old.
TYLER Fat, too fat.
JACK "Applicant?"
TYLER If the applicant waits at the door for three days without food, shelter or encouragement, then he can enter and begin training.
JACK "Training?" Tyler...
Jack comes out, walks around Ricky, hands in his pockets, unsure.
Tyler watches, nods for Jack to go ahead.
JACK Uh, look.
JACK You're too...
JACK young to...
JACK train here.
JACK You should probably be on you way.
No response from Ricky, who remains at attention.
Jack goes back inside.
Tyler closes the door.
Ricky remains at attention.
Jack bursts out with a BROOM, knocks the brown bag out of Ricky's hand, kicks it away.
JACK Are you deaf?!
JACK I told you to leave!
JACK You will never get inside this house!
Ricky's still there.
Tyler comes out, friendly.
TYLER Look, friend, I'm sorry for the misunderstanding.
TYLER It's not the end of the world.
TYLER Just go away.
TYLER You're trespassing and I will call the police.
TYLER Nothing personal.
Ricky, same spot.
Jack bursts outside with the broom again.
JACK You're never getting through this door, you stupid little weasel!
JACK Look at me when I talk to you...
He WHACKS Ricky in the shoulder with the broom.
JACK What is your major malfunction!?
At the window, Tyler sips coffee, watches this scene on the PORCH below.
JACK (V.O.) Sooner or later, we all became what Tyler wanted us to be.
Ricky's there.
Bob is now next to him, in black, with a paper bag in hand, mattress at his feet.
Tyler steps out.
Jack stays in the doorway, locking eyes on Bob.
To all the following questions, Ricky answers "Sir!" --
TYLER You have two black shirts?
TYLER Two pair black trousers?
TYLER One pair black boots?
TYLER Two pair black socks?
TYLER One black coat?
TYLER Three hundred dollars personal burial money?
TYLER Go inside.
Ricky goes in.
Tyler turns to Bob.
TYLER You're too old.
TYLER Sorry.
TYLER And, you're too fat.
TYLER Nice seeing you.
Bob looks genuinely hurt.
He picks up his mattress and starts away.
Tyler looks at Jack and rolls his eyes.
Jack follows Bob...
JACK Bob...
JACK Bob, wait...
JACK Let me explain this to you...
CRICKETS CHIRP.
Bob stands at at rigid attention.
Tyler and Jack stand in bathroom doorway, watching Ricky finish SHAVING off all of his HAIR.
Tyler comes to give the top of Ricky's head a sharp SLAP.
TYLER A monkey, ready to be shot into space.
TYLER A Space Monkey, ready to sacrifice himself for Project Mayhem.
From here on, all those with shaved heads: "SPACE MONKEYS."
Jack looks out the window.
Bob stands motionless.
There's another "applicant," a SHORT GUY, beside Bob.
Ricky comes out the front door with the BROOM...
RICKY You're too fucking old, fatty!
RICKY We don't want your kind here!
RICKY You're too short.
RICKY Go away, stumpy!
RICKY Go back to the circus!
Ricky HITS them with the broom, then goes in, SLAMS THE DOOR.
JACK (V.O.) So it went...
Tyler works with a HALF DOZEN SPACE MONKEYS, preparing the square of backyard.
They pull weeds, clear rocks; working with shovels, rakes, etc.
They cart away WHEELBARROWS of rocks and carry in SACKS of FERTILIZER.
JACK (V.O.) Tyler built his army.
IN THE KITCHEN WINDOW, Jack watches...
Jack keeps watching out the window, eats toast.
JACK (V.O.) To what purpose, might one ask?
JACK (V.O.) Well, one might ask, if not for the first rule of Project Mayhem.
Jack turns to look around the kitchen.
THREE SPACE MONKEYS work -- one SCRUBBING the FLOOR, one WASHING DISHES, one SCRUBBING the walls.
Jack walks out.
JACK (V.O.) In Tyler We Trust.
Jack opens his eyes, awakening to sunlight thru the window.
JACK (V.O.) And, then...
Jack slowly pushes open the door to Tyler's room...
JACK Tyler...
The room is empty.
Jack stares.
JACK (V.O.) He was gone.
Jack comes downstairs...
finds DOZENS of SPACE MONKEYS.
Jack enters.
Space Monkeys render fat and make soap.
They pinch HERBS, adding them to the mix.
They add VODKA.
Off to the side, a couple Monkeys stir a vat of RICE.
On the wall is a big bulletin board with HUNDREDS of DRIVER's LICENSES; a sign above it: "HUMAN SACRIFICES."
FRECKLED SPACE MONKEY "You are not a beautiful and unique snowflake.
FRECKLED SPACE MONKEY You are the same decaying organic matter as everything else.
FRECKLED SPACE MONKEY We are all part of the same compost heap."
JACK (V.O.) Planet Tyler.
Jack dips a spoon into the rice, chomps on it irritatingly.
FRECKLED SPACE MONKEY "We are the all-singing, all-dancing crap of the world."
Jack picks up a BOTTLE of VODKA.
JACK (V.O.) I had to hug the walls, trapped inside this clockwork of Space Monkeys, cooking and working and sleeping in teams.
Jack enters, vodka in hand.
TEN SPACE MONKEYS here, reading.
JACK (V.O.) The house became a living thing, wet inside from so many people sweating and breathing.
JACK (V.O.) So many people moving, the house moved.
Jack walks out.
Jack enters.
Angel Face reads a book, marks on a chart.
Space Monkeys shuffle PAPERS and NEWS CLIPPINGS.
Walls are lined with FILES, each labeled with a STREET ADDRESS, under SIGNS: "Mischief," "Disinformation," "Arson."
Jack's eye lingers on "Arson."
He starts flipping through a file.
Angel Face comes to take the file from him.
ANGEL FACE That wouldn't interest you.
JACK Where's Tyler?
ANGEL FACE The first rule of Project --
JACK Right, right.
As Angel Face replaces the file, Jack notices -- a LYE- BURNED KISS-SCAR on the back of Angel Face's hand.
Jack takes a swig of vodka, smokes.
In the BACKGROUND, a Space Monkey WHACKS an APPLICANT with a BROOM.
It's a ritual; no words.
Other Space Monkeys tend the garden.
JACK (V.O.) I'm all alone.
JACK (V.O.) I Am Jack's Broken Heart.
Jack drops his cigarette in the gravel, steps on it.
A Space Monkey immediately comes to clean it up.
JACK Get away from me!
MARLA'S VOICE Who are all these people?
Jack turns, sees Marla with an overnight bag.
JACK The Paper Street Soap Company.
MARLA Can I come in?
JACK He's not here.
MARLA What?
JACK He's not here!
JACK Tyler's not here anymore!
JACK He's gone away!
Marla stares at Jack, miserable.
A tear runs down her cheek.
She turns and walks away.
Jack watches her go.
There's a LOUD COMMOTION from the house, VOICES SHOUTING.
Jack heads to the back door...
Jack enters.
Ricky crawls, bleeding from a gunshot wound to the LEG.
Space Monkeys begin a rudimentary job of treating the wound.
Other Space Monkeys carry in a DEAD BODY in BLACK CLOTHES and SKI MASK, putting it on the table.
JACK What's going on?
Space Monkeys stare at the body.
The Mechanic, sweating, gets to his knees and pulls the ski mask off the corpse -- it's BOB, with a gunshot wound to the HEAD.
JACK Bob...
JACK oh, Christ...
Jack pushes past a Space Monkey, stares down, stricken...
JACK What...
JACK what happened...
MECHANIC We were on assignment...
A SCULPTURE adorned with a giant GLOBE on top.
MECHANIC (V.O.) We were supposed to kill two birds
with one stone:
A SERIES of EXPLOSIONS blasts the GLOBE free.
It ROLLS...
MECHANIC (V.O.) A piece of corporate art...
The GLOBE ROLLS downhill, to the street -- rolling over one parked LUXURY CAR after another, crunching car roofs and causing windows to explode...
MECHANIC (V.O.) ...
MECHANIC (V.O.) and trash a trendy coffee bar.
Then, the GLOBE arrives at the lobby of a HOTEL...
BROADSIDES a limo, RICOCHETS...
ROLLS directly into the front of a closed ARROSTO coffee bar, SMASHING windows...
DECIMATING coffee push-pats...
Bob, the Mechanic and Ricky FLEE, LAUGHING at their handiwork.
They split up, running O.S.
MECHANIC (V.O.) We had it all worked out, man.
MECHANIC (V.O.) It went smooth...
MECHANIC (V.O.) until...
HARSH VOICE Police!
HARSH VOICE Freeze!
O.S.
SOUNDS of GUNSHOTS and FLASHES of MUZZLE FIRE.
The Mechanic looks up from Bob's corpse.
MECHANIC They shot Bob...
MECHANIC they shot him in the head.
MECHANIC Those fuckers...
Jack walks away from Bob's corpse, distraught, holds his head, turns to look back, his eyes filling with tears.
ANOTHER SPACE MONKEY We gotta do something.
RICKY We got to get rid of the evidence.
RICKY We have to get rid of this body.
ANGEL FACE Bury him...
Jack looks around in disbelief.
JACK What...
ANGEL FACE The garden.
ANGEL FACE Take him there.
ANGEL FACE Move, people.
ANGEL FACE Let's do this!
Several Space Monkeys gather around Bob's body.
JACK No...
Space Monkeys stop.
Jack gets between them and Bob, SHOVES a few Space Monkeys back...
JACK Get your hands off him!
JACK Get off...!
JACK What the hell do you think you're doing...
JACK Evidence?!
JACK This is a man...
JACK You killed him!
ANGEL FACE He was killed in action.
JACK No!
JACK Look at you!
JACK You're...
JACK you're running around in ski masks, exploding things...
ANGEL FACE He was killed serving Project Mayhem.
RICKY It's what he would have wanted, sir.
JACK What he wanted?
JACK Look...
JACK look at him.
JACK Look at him!
JACK What does he want?
JACK This is a person.
JACK This is not a cog in your machine...
RICKY But, this is Project Mayhem.
JACK No, no.
JACK This is a man -- this man has a name...
RICKY But, in Project Mayhem, we have no names.
JACK No!
JACK Wrong!
JACK This man's name is Robert Paulson.
RICKY Robert Paulson?
JACK Robert Paulson is dead.
JACK He's dead, because of you...
MECHANIC I understand.
Everyone just stares at Jack.
MECHANIC In death, a member of Project Mayhem has a name.
JACK No -- !
MECHANIC His name is Robert Paulson.
RICKY His name is Robert Paulson!
JACK No!
ALL SPACE MONKEYS His name is Robert Paulson!
JACK Stop that -- !
ALL SPACE MONKEYS His name is Robert Paulson!
ALL SPACE MONKEYS His name is Robert Paulson...
Jack backs away, surrounded, PUSHES his way out of the room.
Jack barges in, goes to the desk, rifling through drawers.
He finds FLIGHT COUPONS, used and unused.
The used coupons.
have the flight information, including the destination cities.
The PHONE RINGS.
Jack answers it...
JACK Tyler?
DETECTIVE STERN'S VOICE This is Detective Stern of the arson unit.
DETECTIVE STERN'S VOICE I'd like to see you in my office tomorrow morning...
Jack, in a panic, HANGS UP.
Jack sits stiffly in a seat.
JACK (V.O.) I went to the cities on Tyler's used tickets stubs.
Jack hurries from the terminal, runs to a TAXI ...
JACK (V.O.) In every city, I branched out from the airport to downtown, bar- hopping...
Jack's looks out the window, intently watching buildings.
JACK (V.0.) I didn't know how or why, but I could look at fifty different bars, and somehow I just knew...
JACK Here.
JACK Let me out, right here...
Jack enters.
He sees several MALE PATRONS with FIGHT BRUISES.
Jack moves to the bar.
The BARTENDER has a broken arm and swollen face.
JACK I'm looking for Tyler Durden.
BARTENDER Never heard of him.
JACK This is an emergency.
JACK It's important I find him.
BARTENDER I wish I could help you...
BARTENDER sir.
The bartender WINKS at Jack.
JACK (V.O.) Every city I went to...
JACK (V.0.) ...as soon as I set foot off the plane...
JACK (V.).) ...I knew fight club was close.
Jack RUNS through the airport, lugging his suitcase.
JACK (V.O.) Tyler was setting up franchises, all over the country.
The PROPRIETOR, his head bandaged, is confronted by Jack.
JACK I need to know where Tyler is.
JACK Can't you help me?
BANDAGED PROPRIETOR Sir, you're disturbing the other patrons with your laudish behavior.
JACK There's no one else here.
BANDAGED PROPRIETOR I'm sorry, I haven't the faintest idea what you're talking about.
JACK Look at my face.
JACK I'm a member.
JACK I just need to know if you've seen Tyler Durden.
BANDAGED PROPRIETOR I'm not disclosed to bespeak any such information to you, nor would I, even if I had said information you want, at this juncture be able.
Jack looks around, incredibly frustrated.
JACK You are a moron.
BANDAGED PROPRIETOR I'm afraid I have to insist you leave.
Jack gives up, shoves his way out the door.
Jack sits on the bus, looking out the window.
The bus stops.
JACK (V.O.) Under and behind and inside everything I took for granted, something horrible had been growing.
OUT THE WINDOW, a CONSTRUCTION WORKER with a BROKEN NOSE works a jackhammer.
He stops, wipes his brow.
TVs show football.
Jack is seated with TWO BRUISED PATRONS.
BRUISED PATRON #1 No one's ever seen him.
BRUISED PATRON #1 No one knows what he looks like.
BRUISED PATRON #2 He has facial reconstructive surgery every three years.
JACK That's the stupidest thing I've ever heard.
BRUISED PATRON #1 Is it true about fight club in Miami?
BRUISED PATRON 12 Is Mr. Durden building an army?
JACK (V.O.) Am I asleep...
Jack sits awake.
Everyone around him is asleep.
JACK (V.O.) Have I slept?
JACK (V.O.) I'm not sure if Tyler is my bad dream or if I'm Tyler's.
Jack steps off the sidewalk, hailing a TAXI...
The alleyway's deserted.
Jack heaft to rusty CELLAR DOORS.
He opens the doors, looks around, heads down stairs...
JACK (V.O.) I was living in a state of perpetual deja vu.
Jack enters this dark basement, walks ahead in the dim light.
The place is damp and empty.
Jack stops, looks down.
JACK (V.O.) Everywhere I went, I felt I had already been there.
At his feet -- DRIED BLOOD on the concrete floor.
Jack walks in.
The place is empty.
He walks to a KITCHEN DOOR, opens it and peers in at...
a GROUP of KITCHEN WORKERS solemnly stand in a circle, chanting...
KITCHEN WORKERS His name is Robert Paulson.
KITCHEN WORKERS His name is Robert Paulson...
MAN'S VOICE Welcome back, sir.
Jack whirls, startled -- facing the wounded BARTENDER, who wears a NECK BRACE, his nose a smashed eggplant.
WOUNDED BARTENDER How have you been?
JACK ...
JACK You know me?
WOUNDED BARTENDER Is this a test, sir?
JACK Yes...
JACK it's a test.
WOUNDED BARTENDER You were in here last Thursday night.
JACK What?
WOUNDED BARTENDER You were standing right where you are now, asking how good our security is.
WOUNDED BARTENDER It's tight as a drum.
JACK Who do you think I am?
WOUNDED BARTENDER Is this part of the test?
Jack nods slowly.
The Bartender holds up his hand, shows the KISS SCAR on the back of his hand...
WOUNDED BARTENDER You're the one who did this to me.
WOUNDED BARTENDER You're Mr. Durden, sir.
WOUNDED BARTENDER Tyler Durden.
JACK (V.O.) Please return your seatbacks to their full upright and locked position.
Jack bursts inside, out of breath, runs to grab the phone, punches a number, doesn't bother to turn on the lamp.
Marla answers.
MARLA Yeah?
JACK Marla, it's me.
JACK Have we...
JACK have we ever had sex?
MARLA What kind of stupid question is that?!
JACK Because the answer's "yes" or because the answer's "no?"
MARLA Is this a trick?
JACK Will you just answer me, for Christsake?!
MARLA You mean, you want to know if I think we were just having sex or making love?
JACK We did make love?
MARLA Is that what you're calling it?
JACK Answer the question!
MARLA You fuck me, then snub me.
MARLA You love me, you hate me.
MARLA You show me your sensitive side, then you turn into a total asshole!
MARLA Is that a pretty accurate description of our relationship, Tyler?
JACK (V.O.) We've just lost cabin pressure.
JACK What did you say...
MARLA What is wrong with you?
JACK Say my name.
MARLA What...
JACK Say my name!
JACK What's my name!?
MARLA Tyler Durden!
MARLA Tyler Durden, you fucking freak.
MARLA What's going on?
MARLA I'm coming over there...
JACK Marla, no, wait...
As Marla HANGS UP.
Jack stares at the receiver, dazed...
TYLER'S VOICE We've got six fight clubs in Chicago now...
Jack spins, dropping the phone -- TYLER sits beside him.
TYLER Four in Milwaukee.
JACK What's this all about, Tyler?
TYLER And, we're definitely filling a void in the rural South.
JACK Why do people think I'm you?
TYLER You broke your promise.
TYLER You talked to her about me.
JACK Why do people think I'm Tyler Durden?
TYLER Why did you do that?
JACK Answer me, Tyler.
TYLER Why do people think anything?
JACK I don't know!
JACK Tell me!
Tyler shakes his head in disgust, extremely irritated.
TYLER People think that you're me, because you and I happen to share the same body.
JACK What...
TYLER Is this really news to you?
JACK What are you talking about...
TYLER Sometimes I control it, and you imagine yourself watching me...
Commissioner Jacobs checks his tie in a mirror, goes to open the door of the MEN'S BATHROOM -- face to face with JACK.
JACK stands surrounded by eager fight club MEMBERS, under the bare bulb, talking and behaving like Tyler...
JACK The first rule of fight club is -- you don't talk about fight club.
TYLER And, sometimes you control it...
Jack stands in the yard, VODKA in hand, yells at Marla.
JACK He's not here!
JACK Tyler's not here anymore!
JACK He's gone away!
TYLER You can see me and hear me, but no one else can...
JACK sits alone on the curb, watching the nearby freeway.
He talks to someone beside him, but nobody's there.
JACK Anyone?
JACK My boss, probably.
JACK Who would you fight?
Jack listens, looks at the empty space beside him.
JACK Oh, yeah.
JACK I didn't really know my Dad...
TYLER But, when you fall asleep, I do things without you...
JACK is on top of Marla, sweating, making violent love...
TYLER I go places without you.
TYLER Get things done...
The Parker Morris Building.
JACK, Bob, Ricky, Angel Face and another GUY rappel down the side, SPRAYING PAINT.
JACK is "TYLER" in demeanor, mannerisms, speech...
JACK You are not your job.
JACK You are not how much money you have in the bank.
TWO WINDOWS SHATTER OUTWARD -- TWO MEN look out and yell:
BRUISED MAN #1 I am not my job!
BRUISED MAN #2 I am not how much money I have in the bank!
Jack's having trouble catching his breath.
Tyler stands.
TYLER There!
TYLER Happy?
TYLER I asked for one thing from you...
TYLER one simple promise.
TYLER Now look what you've done!
JACK This isn't possible...
TYLER We're going to have to do something about Marla...
JACK What...
JACK what are you saying?
TYLER It's okay.
TYLER We okay...
TYLER a little codependent, sure, but...
Jack shakes his head in disbelief, in denial...
JACK No!
JACK This isn't true.
JACK We...
JACK we were around other people, together, both of us...
TYLER You never talked to me in front of anyone else.
JACK Wrong, wrong -- what about the car crash...
JACK the two guys in the backseat?
TYLER What about them?
TYLER They're lunatics.
JACK You took me to the house.
TYLER The house is rented in your name.
JACK You have jobs.
TYLER Night jobs -- while you were sleeping.
JACK What about Marla?
TYLER What about Marla?
JACK She's...
JACK you...
JACK you're fucking her.
TYLER Um, well...
TYLER technically, no.
Jack stands, trying to absorb, feeling ill, trying to find words, then -- he suddenly FAINTS to the floor, OUT COLD.
JACK (V.O.) It's called a "changeover."
JACK (V.O.) The movie goes on, and nobody in the audience has any idea.
Jack's eyes snap open.
He sits up, alone.
He remembers the previous night...
looks at himself in the mirror...
looks at the clock -- 4:35am.
The room door SLAMS OPEN as Jack bursts out of the room, carrying his suitcase, SPRINTING for the STAIRWELL...
Jack races down, three steps at a time, dragging his suitcase - BOOM, BOOM, BOOM - behind him...
Jack hurries to the front door, his suitcase half-broken open, passing the front desk.
A DESK CLERK calls after him.
DESK CLERK Sir...
DESK CLERK sir?
DESK CLERK Are you checking out?
JACK Yes.
The clerk follows the length of the counter, waves a PAPER.
DESK CLERK Please initial this list of phone calls.
JACK Bill me!
Jack goes out the door, freezes.
He rushes back in, going to the desk -- snatches the bill, studies it: many NUMBERS.
JACK Wait...when were these made?
DESK CLERK It says right there, sir...
DESK CLERK between two and three-thirty this morning.
Jack looks at the clerk, at the bill, at the clerk.
JACK I need a copy of this.
Jack stares out the window, his face set hard.
JACK (V.O.) Had I been going to bed earlier every night?
JACK (V.O.) Have I been sleeping later?
JACK (V.O.) Has Tyler been in charge longer and longer?
A TAXI halts.
Jack leaps out, points to the GRUNGY CABBIE.
JACK Wait here.
Jack walks in to find the place EMPTY and DESERTED.
He continues on into the KITCHEN, gawks at BATHTUBS and CANISTERS holding vast amounts of liquid.
There are HOSES, GAS MASKS, BEAKERS, TEST TUBES and PUMPS.
He picks up a BOTTLE labeled "NITRIC ACID."
Jack sits by the PHONE, pulls out the HOTEL BILL, runs his finger up and down the list of PHONE NUMBERS...
JACK (V.O.) Deja vu, all over again...
Jack finger stops on a NUMBER.
He dials, phone to his ear.
VOICE Eighteen-eighty-eight.
Jack sees a file on the wall: "1888 CENTURY PARK EAST."
JACK Who is this?
VOICE Maintenance.
JACK Listen, something is going to happen, something terrible...
VOICE Very good, Sir.
JACK Excuse me?
VOICE Don't worry about us, sir.
VOICE We're solid.
JACK Now wait, there's been a mix-up.
JACK Everything's changed...
VOICE You told me you'd say that.
JACK Abort the plan.
VOICE You told me you'd say that, too.
JACK Did I tell you I'd call you a fascist dickhead?!
VOICE Well, sir, you said you might.
Jack HANGS UP, desperately dials the next number on the bill.
DIFFERENT VOICE Twenty-one-sixty.
DIFFERENT VOICE Maintenance.
Jack sees a file: "2160 PICO BOULEVARD."
He throws the phone, pocketing the bill.
He grabs up all the FILES.
Jack's TAXI halts.
Marla walks out of the lobby doors, sees Jack getting out of the cab, laden with files...
JACK Marla!
Marla makes a sharp turn, walking away.
Jack follows, hugging the files to his chest, catching up.
JACK Marla...
MARLA Your whacked-out, bald freaks hit me with a fucking broom.
MARLA I thought they were going to break my arm.
JACK I'm sorry, I...
MARLA The were burning their fingertips with lye.
MARLA The stink was unbelievable.
JACK Marla...
JACK I need to talk to you.
JACK It's going to take a tremendous act of faith on your part for you to hear me out.
MARLA Here comes an avalanche of bullshit.
Marla heads into a DINER.
Jack follows...
JACK -- A little more faith than that.
Marla sits in a BOOTH.
Jack sits across from her.
MARLA I don't want to hear anything you've got to say.
JACK Give me a minute, Marla, alright...
JACK just sixty seconds.
MARLA Sixty seconds, then I'm out of here.
JACK Absolutely, you have every right.
JACK I need you to do me a favor.
MARLA I've done you enough favors.
A WAITER with a BLACK EYE appears at the table.
WAITER Sir!
WAITER Anything you order is free of charge, sir.
MARLA Why is it free of charge?
JACK Because...
JACK I'm Tyler Durden.
MARLA Then, I'll have the clam chowder...
MARLA fried chicken and a baked potato with everything and a chocolate chiffon pie.
Jack look to the pass-through WINDOW into the kitchen where THREE COOKS look out with STITCHES in their faces.
JACK Clean food, please.
WAITER In that case, sir, may I advise against the lady eating the clam chowder?
JACK Thanks, no clam chowder.
JACK That's it.
The waiter snaps to attention and leaves.
MARLA You got about thirty seconds.
JACK I know that I've been...
JACK unwell.
JACK I know it's been like there's two sides to me.
MARLA Two sides?
MARLA You're Dr. Jeckle and Mr.
MARLA Jackass.
JACK I deserve that.
JACK Anyway, I've...
JACK I've only just realized
MARLA What?
JACK I mean, the depth and breadth of our relationship has only recently been illuminated for me.
JACK I know this...
JACK I know us hasn't been such a great thing for you...
MARLA Whatever.
MARLA I'll take my food to go...
Marla's getting up to go, but Jack rises, fed up, takes her by the arm, putting her back in her seat.
JACK Sit down!
JACK Sit down and give me my last fifteen seconds without opening your mouth!
Marla crosses her arms.
Jack collects himself.
JACK I'm trying to tell you -- and this is where you have to trust me -- but, I think your life might be in real danger.
MARLA What?
JACK You have to get out of here.
JACK Leave as soon as possible.
JACK Go to any rural town, away from any major city...
MARLA You are an insane person.
JACK Marla...
MARLA No, no, shut up!
MARLA I've had enough.
MARLA I tried, Tyler...
MARLA I have tried...
Marla's getting upset, tears coming to her eyes.
MARLA There's a part of you I really like, but I can't do this anymore.
MARLA I just can't.
MARLA This is killing me...
JACK I'm sorry, but I...
MARLA What?!
MARLA You're sorry?
MARLA I don't believe that for a minute.
Marla gets up.
Jack grabs for her, but she's gone, heading for the door.
Jack gathers his files, runs to follow...
Jack pushes out the door, files under one arm, catching up...
JACK I can't explain.
JACK You wouldn't believe me anyway.
JACK I'm trying to protect you...
Jack grabs her arm, tries to hail a TAXI, but the taxi races past.
Marla pulls free, screaming at him...,
MARLA Let go of me!
JACK Do this for me, Marla.
JACK Do this for me, if you never do anything else...
Jack spots a BUS idling further up the street.
MARLA Leave me alone!
MARLA I don't ever want to see you again!
JACK Okay, if that's what it takes, you'll never have to see me again.
JACK Here...
JACK here...
He pulls MONEY from his pocket, holding it out.
JACK Take this money, get on this bus...
JACK Get on, and I promise you, I'll never bother you again, if that's what you want.
JACK Please...
Marla looks at Jack, numb.
MARLA Tyler...
JACK I'm begging you.
JACK Get on the bus.
JACK Get on the bus.
Marla takes the money from Tyler, walks towards the bus.
As they approach it, Jack shields his eyes, afraid to look...
MARLA Why are you doing this?
JACK I can't let myself see where you're going.
JACK Go wherever it takes you, remember...
JACK keep away from major cities...
Marla stands at the doors of the bus, heartbroken, gives one last look at Jack.
MARLA I'm not paying this back.
MARLA I consider it "asshole tax."
JACK Yes, fine.
JACK Just, get on.
JACK Stay away a couple of weeks, at least.
Jack's still covering his eyes.
Marla gets on the bus.
MARLA Tyler...
Jack finally looks to her.
MARLA You are the worst thing that ever happened to me.
DOORS HISS SHUT.
The BUS LEAVES, heading away.
Jack seems relieved.
Then, a SCREAM is HEARD from MARLA...
Jack turns, looks...
THROUGH THE BUS WINDOWS: the bus is filled with BALD MEN IN BLACK: Space Monkeys.
Jack SPRINTS after the bus...
The bus speeds away.
Onboard, Space Monkeys subdue Marla.
Jack falls to the asphalt, rolls, files-flying.
JACK Son of a bitch!
Jack RUNS to the front desk, crazed, dumps the armload of files on the desk in front of the DESK SERGEANT...
JACK I want you to arrest me.
JACK I'm the leader of a terrorist organization responsible for acts of vandalism all over the city.
JACK Detective Stern in arson knows who I am...
Detective Stern and THREE DETECTIVES stand, staring at Jack, who's seated.
On the table are the phone bill and files.
JACK There are probably several hundred members in the metropolitan area.
JACK Chapters are sprouting in at least five other major cities.
JACK They're tightly-regimented, with many cells capable of operating without a
central leader.
Check this address: 1537 Paper Street.
You'll find the body of Robert Paulson buried in the garden.
You'll also find numerous tubs used to make gallons of nitroglycerin.
The plan, I believe, is to blow up these credit card headquarters and the TRW building.
STERN Why these buildings?
JACK You are not your job.
JACK You are not how much money you have in the bank.
STERN Keep him talking.
Stern leaves.
A beat, then, the remaining Detectives smile at Jack with REVERENCE.
FLAT-TOP DETECTIVE I really admire what you're doing.
FLAT-TOP DETECTIVE You're a brave man to order this.
JACK What?
REDHEAD DETECTIVE You're a genius, sir.
They grab Jack and force him on his back on the table.
Flat-Top has a rubber band; the Bald Detective has a knife.
BALD DETECTIVE You know the drill.
BALD DETECTIVE You said if anyone ever tries to interfere with Project Mayhem, even you, we got to get his balls.
Flat-Top PULLS Jack's pants completely off, tosses them aside.
Jack SCREAMS.
Flat-Top holds his legs.
FLAT-TOP It's useless to fight.
REDHEAD This is really a powerful gesture, Mr. Durden.
REDHEAD It'll set quite an example.
JACK No...
JACK you're making a mistake!
FLAT-TOP You told us you'd say that.
JACK I'm not Tyler Durden!
BALDY You told us you'd say that, too.
JACK Okay, I am Tyler Durden and I'm ordering you to abort the mission!
FLAT-TOP You said you would definitely say that.
BALDY What's our best time for a "cut and run?"
FLAT-TOP Four minutes.
BALDY Is somebody timing this?
REDHEAD Wait till the second hand gets to the twelve.
A KNOCK at the door.
Flat-Top slaps a hand over Jack's mouth.
He and Redhead block view of the table as Baldy opens the door a crack.
Stern mutters:
STERN Some of this info checks out.
STERN Let's go to the place on Paper Street.
Baldy glances back at the other Detectives, leaves, closing the door.
The two remaining Detectives continue.
Jack kicks and screams and writhes.
The Detectives wrangle him, but with more difficulty, now that Baldy's gone.
REDHEAD Mr. Durden, you're going to fuck up the time!
Jack gets one leg free, KICKS, knocks Flat-top backwards -- Flat-Top SLAMS the wall, falls.
Redhead lets go of one of Jack's arms, jams his elbow into Jack's throat...
cutting off the airway.
Jack's face reddens...
he's choking...
Jack's free hand reaches, searching..
pulls Redhead's GUN and points it at him.
Redhead backs off.
Jack gets up, gasping for air, PISTOL-WHIPS Flat-top as he rises.
Jack grabs one of the files off the table.
Jack, without pants, in BOXER SHORTS, escapes out the BACK DOOR.
He looks at the ADDRESS on the file folder.
Jack SPRINTS down the middle of the street, gun in hand, looking like a complete madman.
Cars almost hit him.
Jack, sweating and panting, stops, looks...
then heads toward the BUILDING with the address "1888."
Jack tries the door.
Locked.
He lifts a cast iron bench, runs forward -- RAMS it into the glass.
The bench immediately recoils from the glass, SLAMS Jack's groin!
Jack falls to his knees, doubled over, holding his package.
Then, he rises, SHOOTS the glass...
Jack pushes through the broken glass.
He sprints for the "PARKING" door...
Jack enters, looks -- NO CARS.
He bolts to the STAIRS...
Jack enters, heaving.
Again, NO CARS.
He moves from one SUPPORT POST to another, searching.
He finally spies, across the garage, NINE LARGE CANISTERS, heavily-WIRED.
Jack runs to the BOMB, frantic.
He walks around it.
There's a DIGITAL CLOCK, ticking down from "10:05"...
Jack moves to pull the lid off one CANISTER, looks inside..
TYLER Could be worse...
Jack looks -- Tyler's seated, his back against one post.
TYLER You could be standing under 37 stories of steel and concrete with a 150 gallons of nitroglycerin strapped to the support...
TYLER oh, maybe it couldn't be...
JACK You...
JACK you can't be serious about this.
TYLER What a ridiculous thing to say.
JACK I can't let you...
TYLER ...go through with this?
TYLER What are you going to do?
JACK I'm going to...
TYLER ...stop me?
JACK I'm not going...
TYLER ...to let this happen!
JACK Stop finishing...
TYLER ...your sentences!
TYLER They're our sentences.
TYLER Get your mind around that.
Tyler gets up walks to Jack.
TYLER What are you doing running through the streets in your underpants?
TYLER We both use that body.
JACK Since when is Project Mayhem about murder?
TYLER The buildings were evacuated thirty minutes ago.
TYLER Everything's proceeding exactly as planned.
JACK You don't know that.
JACK There could still be people inside.
Tyler keeps walking around, crosses his arms.
TYLER Maybe.
TYLER Maybe a couple of guys with shaved heads couldn't synchronize their watches.
TYLER Good riddance.
Jack looks back to the BOMB, goes to it, wipes sweat off his face.
He starts finger the MANY WIRES, sorting them.
TYLER I wouldn't be doing that.
TYLER Unless you know which wires, in what order...
JACK If you know, I know.
Jack holds his gun under one armpit, uses both hands to go through the tangle of colored wires.
TYLER Or...
TYLER maybe I knew you'd know, so I spent the whole day thinking about the wrong ones.
Jack chooses one wire, GREEN, holds it in his fingers.
JACK If I'm wrong, we're both dead..
TYLER This is not about martyrdom.
Jack twists the GREEN WIRE around his finger.
JACK I'm pulling the green wire.
TYLER Green?
TYLER Did you say green?
Tyler comes a little closer, leaning to try to get a look, seems genuinely concerned.
JACK Yes...
TYLER Don't pull the green wire.
TYLER Pull anything but the green wire.
JACK Fuck you.
TYLER I'm serious.
TYLER That's the wrong one.
Jack's unsure, swallowing, pulling the wire taunt, fingers trembling.
The SOUND of a VEHICLE is HEARD from below...
TYLER Hear that?
TYLER Marla's here.
TYLER Just in the nick of time, eh?
Jack looks to Tyler.
Tyler points towards the SOUND...
TYLER See for yourself.
Jack releases the wire, walks to a RAILING, gun in hand, keeps an eye on Tyler.
Jack looks over the railing...
BELOW, a BUS idles.
The doors open and MARLA'S dragged out, kicking and screaming, carried by SIX SPACE MONKEYS...
MARLA You motherfuckers...
They carry Marla into the BUILDING'S ENTRANCE.
Jack leans against the railing, exhausted.
TYLER I've got everything.
TYLER The bombs.
TYLER The army.
TYLER I've got Marla.
JACK Bob is dead, Tyler.
JACK The police blew a hole in his head.
JACK Was that part of your plan?
Tyler thinks, shrugs.
TYLER Bob was a grown man.
TYLER In any great struggle, there will be casualties.
TYLER Wouldn't that be implicit in the name?
TYLER Project "Mayhem."
JACK Fuck your struggle.
JACK I want out.
TYLER You want out?
JACK I quit.
TYLER Not an option, for the most obvious of reasons.
TYLER You need to get with the program.
TYLER Seven minutes.
TYLER Let's get out of here.
Tyler's walks away.
Jack looks at the gun in his hand.
He points the gun at Tyler...
JACK Tyler...
TYLER What?
JACK Defuse the bomb.
Tyler stops walking.
TYLER Ask me nicely.
JACK Defuse the bomb, please.
TYLER Defuse the bomb?
JACK Yes.
Tyler strides towards the BOMB.
Jack trains the gun...
JACK Please.
Tyler looks at the BOMB, reaches over to it.
He grips the GREEN WIRE, yanks it out -- the CLOCK STOPS.
Jack lowers his gun.
TYLER I did that for you.
TYLER As a gesture.
TYLER Now, how fast can you run?
TYLER There are ten other bombs, in ten other buildings in the immediate area.
TYLER If you're going to get them all, you better get cracking.
TYLER Six minutes.
TYLER Green wires, remember.
TYLER I'll be upstairs.
Jack's stunned.
Tyler walks across the parking garage, past Jack, heading for the STAIRS.
Jack aims the gun at Tyler's back, FIRES!
Tyler ducks to one side, impossibly quick, avoiding...
Tyler spins to face Jack.
TYLER Whoa!
TYLER What was that all about?
Jack aims...
FIRES!
Tyler DODGES behind a post as the BULLET THROWS CONCRETE.
Jack edges forward, gun held in both hands, moves around the post...
Tyler is NOT THERE.
Jack turns, takes slow steps, moving the gun from side to side...
Suddenly, a FIST ENTERS FRAME -- SLUGS Jack's face.
Jack falls.
The gun goes CLATTERING across the floor...
Jack turns, looking...
Tyler's GONE.
Jack looks to the gun, scrambles to his feet, running to pick up the gun...
Tyler KICKS Jack in the chest, sends Jack sprawling.
Jack rolls, holding his chest.
He looks up, sees Tyler run into the STAIRWELL.
Jack grabs the gun and follows...
Jack smashes the door open.
The stairwell's empty.
Jack RUNS up a flight of stairs, kicks open ANOTHER DOOR...
Jack steps forward, gun up...
TWO INTERLOCKED HANDS SLAM down onto his head.
Jack drops to the floor.
Tyler backs away, laughing.
Jack gets to his feet, aims his gun...
TYLER Fire at will.
Jack clenches his teeth, FIRING -- nothing happens to Tyler.
Jack FIRES TWICE -- no effect.
Tyler raises his arms.
TYLER What did you expect?
Jack charges.
Tyler dodges, PUNCHES, knocks the gun out of Jack's hand.
They FIGHT, trading PUNCHES, grappling, taking each other to the floor...
Banks of SECURITY MONITORS sit unmanned.
ON ONE MONITOR: Jack is seen in the lobby, on the floor, alone, wrestling himself.
He swings his left hand up, punching empty air, then swings his right hand -- PUNCHING himself in the side of the head...
Tyler and Jack fight viciously, bloodied.
Tyler manages to get his hands around Jack's throat, starts BANGING Jack's head against the floor...
...
Jack's got his hands around his own throat, BANGING his own head against the floor, over and over...
Jack manages to break Tyler's grip, KICKS Tyler away.
Tyler springs to his feet, RUNS, heading for a STAIRCASE.
Jack gets up, breathing hard, holding his head, follows...
ON THE STAIRS, Tyler reaches the LOFT LEVEL, above the lobby, disappears around a corner.
Jack's right behind, turning the corner -- Tyler's NOT THERE.
Jack receives a SHARP SLAP on the back of the head.
He wheels.
Tyler isn't there.
A TAP on his shoulder.
Jack turns around -- WHAM!
-- Tyler PUNCHES his face.
Jack falls against the loft railing.
Tyler comes forward, SWINGS...
Jack PUNCHES himself square in the nose!
Jack's dazed.
Tyler grabs Jack's shirt, pulls him forward, SWINGS HIM -- THROWS him DOWN THE STAIRS...
Jack TUMBLES horribly down...
HITS BOTTOM, striking his head on the floor.
Jack PASSES OUT...
CLOSE ON: Jack's head jerks back as he SNAPS AWAKE.
He looks around, trying to focus his eyes...
JACK'S P.O.V. -- TRACKS in the sawdust of the floor, from where his body was dragged across to where he is how.
CLOSE ON: Jack tries to comprehend.
He turns his head -- TYLER'S HAND brings the GUN up, PUTS THE GUN IN JACK'S MOUTH.
Jack freezes, looks around with his eyes...
Tyler is seated in Jack's lap.
Tyler holds the gun in Jack's mouth, his arm around him.
This huge room is being remodeled.
Tyler and Jack are seated near floor-to-ceiling windows affording a spectacular view of the CITY.
Tyler looks at his watch.
TYLER One minute.
JACK (V.O.) I think this is about where we came in.
TYLER This is the beginning.
TYLER We're at ground zero.
TYLER Maybe you should say a few words, to mark the occasion.
JACK i...
JACK ann....iinn..
JACK ff....nnyin...
Jack tongues the barrel to the side of his mouth.
JACK I still can't think of anything.
Tyler checks his watch.
TYLER It's getting exciting now.
Jack turns, so he can see down -- 31 STORIES.
TYLER Look what we've accomplished.
TYLER Thirty seconds.
TYLER Out these windows, we will view the economic collapse.
TYLER One step closer to global equilibrium.
TYLER I'm glad you're here with me.
Tyler watches the skyline, WHISTLES at tune, waiting.
JACK Can't you call it off...
TYLER It's out of our hands.
TYLER This is it.
JACK Please...
TYLER Fifteen seconds now.
TYLER Can you see alright?
TYLER 10...
TYLER 9...
TYLER 8....
Tyler looks out the windows, at SURROUNDING BUILDINGS, excited.
Jack closes his eyes, despairing.
Out the window, the SKYLINE remains unchanged.
Nothing.
A long beat.
A very dark scowl comes over Tyler's face.
Jack opens his eyes.
More waiting.
Tyler looks genuinely surprised, pissed-off.
TYLER What the fuck -- ?
JACK Paraffin.
TYLER What?
JACK Paraffin.
JACK Your merry band mixed the nitro with paraffin.
JACK I saw it floating in the bomb.
JACK (cont) They must've run out of cotton and Epsom salt.
JACK (cont) Paraffin is iffy at best.
Tyler rises, taking the gun from Jack's mouth, starts pacing.
Jack rubs his sore jowls, allows himself a smile.
TYLER Damn it!
TYLER God-damn it...
JACK Not exactly according to plan.
TYLER Do we have to do everything ourselves?!
Tyler stops walking, lets out a sigh of disgust.
He reaches into his pocket, taking out a WALKIE TALKIE.
TYLER ...
TYLER Codename Rooster.
TYLER Passcode First Strike...
Jack's eyes go wide.
TYLER Proceed with remote detonation.
Jack leaps -- TACKLES Tyler.
The GUN is knocked away.
Jack STRIKES Tyler's face repeatedly with his elbow, scrambles off...
Jack gets the gun, turns, pointing it.
Tyler's getting to his feet, sees the gun, annoyed.
Jack stands.
TYLER Haven't we already done this?
Jack SHOOTS TWICE.
Bullets pass right thorough Tyler.
Tyler just rolls his eyes, drops the walkie-talkie to the floor and STOMPS on it, CRUSHING it.
JACK How'd you do that?!
JACK You're a fucking figment of my imagination...
JACK you're psychogenic fugue state...
TYLER Fuck that, maybe you're my hallucination.
Jack falters, pointing at Tyler's feet.
There's no walkie- talkie there.
Jack looks down, sees the WALKIE-TALKIE CRUSHED under his own foot.
JACK Oh...
JACK Christ...
Jack holds his head, walks around, at his wit's end.
JACK Why...
JACK why...
JACK why...
TYLER Why what?
JACK Why can't I get rid of you?
JACK Why can't I just wish you away?
TYLER You need me.
JACK No, no, I don't.
JACK I thank you, I really do.
JACK Thank you, but I don't need you anymore.
TYLER Look, I can be selfish, I know that.
TYLER I'm not blind to my own failings...
JACK Noooo, please...
Jack backs up against a window, numb and weary.
TYLER From now on, we'll share Marla.
TYLER We've been spending too much time apart...
JACK ...
JACK no, no, no...
TYLER No more running off without you.
TYLER From here on out, we do it together.
JACK Why are you doing this?!
TYLER I'm doing this for us.
JACK Please understand...
JACK I've gotten all I can from this, Tyler.
TYLER If I leave, you will be right back where I found you...
JACK I swear on my life, I won't...
TYLER You will.
TYLER You know you will.
Jack stares at Tyler, tears welling up, hangs his head.
He looks at the gun in his hand...
TYLER Can you live with that?
Jack stares at the gun a long time...
then...
Jack brings the gun up, PUTS THE GUN IN HIS MOUTH.
Tyler cocks his head.
TYLER What are you doing?
JACK What have you left for me?
TYLER Why do you want to do that?
TYLER Why do you want to put that gun in your mouth?
JACK Not my mouth.
JACK Our mouth.
Tyler is calm.
TYLER This is interesting.
Tyler smiles in appreciation, slowly walks forward, stands very close to Jack.
TYLER Why are you going with this, Ikea- boy?
JACK It's the only way to get rid of you...
Jack COCKS the hammer on the gun.
TYLER I can see you feel very strongly.
TYLER I feel strongly too.
TYLER Hey, you and me.
TYLER Friends again?
Their eyes are locked, unblinking.
Long silence.
JACK Do something for me.
TYLER What?
JACK Appreciate something.
TYLER What?
JACK Look at me...
TYLER What?
JACK My eyes are open.
Jack's finger squeezes the trigger...
KABLAM!
-- Jack's cheeks INFLATE with gas.
His eyes bulge.
BLOOD flies out from his head.
The WINDOW behind him SHATTERS.
SMOKE wafts out of his mouth and tear ducts.
RESUME NORMAL SPEED as the GLASS FALLS behind Jack...
Tyler stands, in gunsmoke, eyes glazed, sniffs the air...
TYLER What's that smell...
Jack slumps to the floor...
Tyler falls...
Tyler hits the ground.
The back of TYLER'S HEAD is BLOWN OPEN, revealing blood, skull and brain.
Suddenly, a GROUP of SPACE MONKEYS burst into the room, moving forward to Jack.
TYLER'S BODY IS GONE.
TALL SPACE MONKEY Are you all right, sir...
TALL SPACE MONKEY ?!
Jack quakes, holding the side of his head; a ragged hole blown in his CHEEK.
He's bleeding hard, but he's alive.
JACK I'm okay...
Jack looks to the Space Monkeys, trying to get his eyes to see.
TWO SPACE MONKEYS enter with Marla.
One holds a gun to Marla as she struggles.
SHORT SPACE MONKEY Are you sure?
SHORT SPACE MONKEY You look terrible, sir!
SHORT SPACE MONKEY What's happened?
JACK Everything's fine.
ANOTHER SPACE MONKEY Sir, you look really awful!
ANOTHER SPACE MONKEY Do you need medical assistance?
Jack sees Marla, tries to get to his feet, falls...
JACK Bring the girl to me.
JACK The rest of you get out.
JACK Now!
The Monkeys bring Marla, releasing her, saluting.
MARLA What happened...
JACK Don't ask.
Marla crouches, takes out wadded TISSUES and tries to apply.
them to Jack's wound.
Space Monkeys are leaving, hesitantly.
JACK Get to the rendezvous point.
JACK Move it!
Jack and Marla are left alone.
MARLA My God, you're shot...
JACK Yes.
Jack tries to got up.
Marla helps him.
MARLA Who did this to you?
JACK I did, I think.
JACK But, I'm okay...
JACK I'm fine...
MASSIVE EXPLOSION...
the glass walls rattle...
Jack and Marla look -- OUT THE WINDOWS: a BUILDING EXPLODES; collapsing upon itself.
Then, ANOTHER BUILDING IMPLODES into a massive cloud of dust.
Jack and Marla are silhouetted against the SKYLINE.
Jack looks to Marla, reaches to take her hand.
JACK I'm sorry...
JACK you met me at a very strange time in my life.
Marla looks at him.
ANOTHER BUILDING IMPLODES and COLLAPSES inward...
and ANOTHER BUILDING...
and ANOTHER...
The FILM SLOWS, then ADVANCES ONE FRAME at a TIME -- SHOWING SPROCKET HOLES on the SIDES.
EACH FRAME is an IMPLODING BUILDING -- then, ONE FRAME IS A PENIS.
Then, the IMPLODING BUILDING again.
SPEED UP the frames, LOSE the sprocket holes, RESUME NORMAL SPEED...
end
</pre> </pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
