<TITLE>"THE SIXTH SENSE" -- by M. Night Shyamalan</TITLE>
<!-- MadeByWZ at http://plaza26.mbn.or.jp/%7Ehappywel/ -->
<BODY><div class=adjust>
<PRE> t h e s i x t h s e n s e
written by
M.
Night Shyamalan
A NAKED LIGHTBULB SPARKS TO LIFE.
It dangles from the ceiling of a basement.
LIGHT, QUICK FOOTSTEPS AS ANNA CROWE moves down the stairs.
Anna is the rare combination of beauty and innocence.
She stands in the chilly basement in an elegant summer dress that outlines her slender body.
Her gentle eyes move across the empty room and come to rest on a rack of wine bottles covering one entire wall.
She walks to the bottles.
Her fingertips slide over the labels.
She stops when she finds just the right one.
A tiny smile as she slides it out.
Anna turns to leave.
Stops.
She stares at the shadowy basement.
It's an unsettling place.
She stands very still and watches her breath form a TINY CLOUD IN THE COLD AIR.
She's visibly uncomfortable.
Anna Crowe moves for the staircase in a hurry.
Each step faster than the next.
She climbs out of the basement in another burst of LIGHT, QUICK FOOTSTEPS.
Two place settings are arranged on the living room coffee table.
Take-out Chinese food sits half eaten on good china.
An empty bottle of red wine sits between boxes of Chinese food.
Anna arrives with the backup bottle and is now wearing a sweater.
She hands a collegiate rowing team sweatshirt to Malcolm.
ANNA It's getting cold.
MALCOLM CROWE sits on the floor at the coffee table, his vest and tie on the sofa behind him.
A jacket and an overcoat lay on a brirfcase next to him.
Malcolm is in his thirties with thick, wavy hair and striking, intelligent eyes that squint from years of intense study.
His charming, easy-going smile spreads across his face.
He points.
MALCOLM That's one fine frame.
MALCOLM A fine frame it is.
Malcolm points to the HUGE FRAMED CERTIFICATE propped up on a dining room chair.
It's printed on aged parchment-type paper.
The frame is a polished mahogany.
He slips on the sweatshirt.
MALCOLM How much does a fine frame like that cost, you think?
Anna hands the backup bottle over to Malcolm.
ANNA I've never told you...
ANNA but you sound a little like Dr. Seuss when you're drunk.
Malcolm uncorks the wine and starts pouring in the empty glass.
MALCOLM Anna, I'm serious.
MALCOLM Serious I am, Anna.
Anna giggles.
She's clearly buzzed herself.
Malcolm doesn't get it.
Anna takes a few calming sips of her wine.
Her attention slowly moves to the framed certificate.
ANNA Mahogany.
ANNA I'd say that cost at least a couple hundred.
ANNA Maybe three.
MALCOLM Three?
MALCOLM We should hock it.
MALCOLM Buy a C.D.
MALCOLM rack for the bedroom.
ANNA Do you know how important this is?
ANNA This is big time.
ANNA I'm going to read it for you, doctor.
MALCOLM Do I really sound like Dr. Seuss?
Anna ignores Malcolm and clears her throat.
She leans forward her seat and reads the certificate out loud as Malcolm tries to tickle her.
ANNA In recognition for his outstanding achievement in the field of child psychology, his dedication to his work, and his continuing efforts to improve the quality of life for countless children and their families, the City of Philadelphia proudly bestows upon its son Dr.
ANNA Malcolm Crowe...
ANNA That's you...
ANNA the Mayor's Citation for Professional Excellence.
Beat.
The power of the words sobers the two of them.
ANNA Wow.
ANNA They called you their son.
MALCOLM We can keep it in the bathroom.
Anna turns to Malcolm.
He smiles.
MALCOLM It's not real, Anna.
MALCOLM Some secretary wrote that up.
MALCOLM Don't tell me you thought it was real?
Anna's expression becomes serious.
MALCOLM What?
She just keeps staring.
Beat.
MALCOLM Don't do the quiet thing.
MALCOLM You know I hate it.
Beat.
ANNA This is an important night for us.
ANNA Finally someone is recognizing the sacrifices you made.
ANNA That you have put everything second, including me, for those families they're talking about.
Malcolm plays softly with her face.
Anna takes his hands and holds them steady.
ANNA They're also saying that my husband has a gift.
ANNA Not an ordinary gift that allows him to hit a ball over a fence.
ANNA Or a gift that lets him produce beautiful images on a canvas...
ANNA Your gift teaches children how to be strong in situations where most adults would piss on themselves.
ANNA Yes, I believe what they wrote about you.
Anna lets go of his hands.
Anna's eyes are emotional.
Malcolm smiles softly.
MALCOLM Thank you.
Anna leans towards him.
They hold each other tight.
Beat.
MALCOLM What are we hugging about again?
Anna laughs as she wipes her eyes.
ANNA Nothing.
ANNA There wasn't supposed to be any crying at this celebration.
ANNA Just a lot of drinking and sex.
Malcolm's charming, easy-going smile returns.
MALCOLM I would like some red wine in a glass.
Anna hands him his glass.
He stares at it.
MALCOLM I would not like it in a mug.
MALCOLM I would not like it in a jug.
Malcolm looks at Anna surprised at what he said.
They crack up laughing.
THEIR SWEET LAUGHTER FILLS THE HOUSE.
TWO GIGGLING SHADOWS APPEAR IN THE BEDROOM DOORWAY.
They try to turn on the light.
It doesn't come on.
MALCOLM Bulb's out.
Anna giggles some more as Malcolm's shadow stumbles across the bedroom.
A SHAFT OF LIGHT falls on Anna as she stands in the corner of the room.
Anna smiles playfully and pulls off her sweater.
She sways to a pretend striptease song.
Malcolm can't hold back his grin.
He joins in -- slowly peeling off the sweat-shirt.
He looks back to Anna.
She's stopped her playful dance.
She's facing away from him.
He walks towards her.
HIS GRIN QUIETLY DISAPPEARS.
Malcolm's face turns to rock as his attention is drawn to the SHATTERED WINDOW in their bedroom.
The wind moves through the room.
A lamp lays broken on the ground by the window.
Malcolm kneels down.
Beat.
Anna's eyes fill with a quiet awareness.
ANNA He's still in the house.
Malcolm spins around.
His heart stops.
Malcolm and Anna stare at the bathroom doorwary.
They know someone is inside.
Beat.
Malcolm slowly starts towards the door.
The first thing that comes into view are the clothes on the bathroom floor.
Then the figure of a man comes into view.
A STRANGER stands bare chested in the back of the bathroom.
The STRANGER is about nineteen.
Drugged out.
Pitch black eyes bulging.
His body is covered in scars and bruises.
His hands are folded in front of him.
He shakes ever so slightly.
He has a patch of white in his hair.
Malcolm speaks in a very calm voice.
Never takes his eyes off the stranger.
MALCOLM Anna, don't move.
MALCOLM Don't say a word.
Anna barely nods her understanding.
MALCOLM This is forty-seven Locust Street.
MALCOLM You have broken a window and entered a private residence.
MALCOLM Do you understand what I'm saying?
The stranger slowly looks up for the first time.
His eyes lock on Malcolm.
STRANGER You don't know so many things.
Beat.
MALCOLM There are no needles or prescription drugs of any kind in this house.
The stranger suddenly comes forward into the doorway.
Malcolm stumbles back onto the edge of the bed.
Anna sees the stranger for the first time.
Her face drains of color.
The stranger looks at Malcolm.
He half grins.
STRANGER Are you drunk?
The stranger's stare slides to Anna.
STRANGER Did you get him drunk?
The stranger gazes at Anna.
Gazes directly into her eyes.
A penetrating, unwavering stare.
STRANGER Do you know why you're scared when you're alone?
Anna's expression instanly changes.
STRANGER I know.
MALCOLM What do you want?
MALCOLM I don't understand what you want.
The stranger turns and glares at Malcolm.
STRANGER What you promised.
Malcolm stops all movement.
ANNA --My God.
MALCOLM --Do I know you?
STRANGER Let's all celebrate, Dr. Malcolm Crowe.
STRANGER Recipient of awards from the Mayor on the news.
STRANGER Dr. Malcolm Crowe, he's helped so many children...
STRANGER And he doesn't even remember my name?
Malcolm can't speak.
Beat.
The stranger's face starts to tremble.
STRANGER I was ten when you worked with me.
Beat.
Malcolm's intelligent eyes race for answers.
STRANGER Downtown clinic?
STRANGER Single parent family?
STRANGER I had a possible mood disorder...
STRANGER I had no friends...
STRANGER you said I was socially isolated.
STRANGER I was afraid -- you called it acute anxiety...
STRANGER You were wrong.
STRANGER Come on, clear your head...
STRANGER Male, nine...
STRANGER Single parent...
STRANGER Mood discorder...
STRANGER Acute anxiety.
Malcolm looks like someone hit him with a sledgehammer.
STRANGER I'm nineteen.
STRANGER I have drugs in my system twenty-four hours a day...
STRANGER I still have no friends.
STRANGER I still have no peace.
STRANGER I'm still afraid.
Tears jump into the stranger's eyes.
STRANGER ...I'm still afraid.
Malcolm stands.
MALCOLM Please give me a second to think.
Malcolm's shaking hands touch his mouth as he stares at the stranger.
Beat.
MALCOLM Bed Freidken?
STRANGER Some people call me freak.
MALCOLM ...Ronald...
MALCOLM Ronald Sumner?
Tears fall down the stranger's face.
STRANGER I am a freak.
Malcolm looks up at the sound of those words.
Something clicks in his head.
MALCOLM --Vincent?
MALCOLM Vincent Gray?
VINCENT GRAY stares with surprise through his tears.
Malcolm lets out a deep breath like he just emerged from deep waters.
MALCOLM I do remember you, Vincent.
MALCOLM You were a good kid.
MALCOLM Very smart...
MALCOLM Quiet...
MALCOLM Compassionate...
MALCOLM Unusually compassionate...
Vincent's eyes burn at Malcolm.
VINCENT You forgot cursed.
VINCENT is fully crying now.
VINCENT You failed me.
MALCOLM Vincent...
MALCOLM I'm sorry I didn't help you...
MALCOLM I can try to help you now.
Vincent turns to the sink.
His hand goes in.
He turns arund and raises a gun at Malcolm.
He FIRES.
A VIOLENT, EAR-SHATTERING ECHO.
Malcolm clutches his stomach and folds like a rag doll onto the bed.
Vincent instantly moves the gun to his own head.
ANOTHER HORRIFIC BLAST SPIKES THE AIR.
Vincent crumples onto the bathroom floor.
The legend, "Two Years Later" appears.
A man flips open a worn file folder on his lap.
Handwritten notes fill every line.
At the top of the first page reads, "Vincent Gray, age 10, Referred January 19, 1989."
The man's hand touches the name almost reverently.
He glances through the page.
Words and phrases are circled throughout the file.
"...Acute anxiety" "...Socially isolated" "...Possible mood disorder" "...Parent status -- Divorced" "...Communication difficulty between mother-child dyad"
The man's hands flip the page.
At the top of this new page reads, "Cole Sear, age 8, Referred September 1998."
As the man's fingers move through the notes we again see words and phrases circled throughout this new case history.
"...Acute anxiety" "...Socially isolated" "...Possible mood disorder" "...Parent status -- Divorced" "...Communication difficulty between mother-child dyad"
The hands close the notepad.
The hands are slightly shaking now.
WE PULL BACK to reveal the shaking hands belong to Dr. Malcolm Crowe.
Malcolm sits on a sidewalk bench facing a row of brownstone homes across the street.
He gazes blankly at the brownstones.
Beat.
A door opens.
Malcolm is brought out of his trance.
COLE SEAR steps out his front door.
Cole is a munchkin of a boy with large, black eyes that seem to take in everything around him.
His hair is dark, with a small patch of jet white on the side.
Cole carefully locks the door behind him.
He moves to the bottom of the stairs and looks around nervously.
Anxiously.
The eight-year-old child reaches into his pocket and slips on a pair of VERY LARGE GLASSES.
They look comical on him.
Malcolm rises to his feet.
He smooths out his shirt.
Looks down and buttons his jacket.
When he looks up, Cole is gone.
Malcolm barely catches a glimpse of the boy.
Cole runs at full speed down the street and turns the corner.
TINY SNEAKERS
For a second, Malcolm doesn't react.
The second passes.
He stuffs the file in his bag and starts running too.
Malcolm hauls down the sidewalk.
He comes to a hard stop at a street intersection.
Searches.
Spots Cole running into a parking lot.
COLE sprints across the empty lot and reaches the doors of a building.
He has to use all his strength to push open the highly ornate doors.
He slips inside.
Malcolm jogs into the parking area.
His pace slows to a walk and then to stillness as he gazes up at the building.
Its old stone and huge towers make it stand out from the modern buildings all around it.
Malcolm stares up at the historic Philadelphia church quietly.
A SHOOTING PAIN PIERCES HIS SIDE.
Malcolm's hand goes to it quickly.
He waits for it to pass before starting for the ornate doors.
Only a few people sit and pray in the sea of oak pews.
Malcolm scans the majestic room and finds what he's looking for in the last row of the church.
He moves down the center aisle towards the back.
Malcolm finds Cole playing in his pew with a set of green and beige plastic soldiers.
Cole makes the soldiers talk to each other.
COLE Pro...
COLE Fun...
COLE Add...
The words are unintelligible.
Cole senses someone.
He looks up and sees Malcolm staring at him.
The boy immediately goes white.
Every cell of his body still with fear.
MALCOLM It's okay, Cole.
MALCOLM Don't be frightened.
Cole stays rigid.
Hands clutching a handful of plastic riflemen.
MALCOLM My name is Dr. Malcolm Crowe.
MALCOLM I was supposed to meet you today.
MALCOLM Sorry I missed our appointment.
Malcolm waits for a response.
None comes.
MALCOLM Do you mind if I sit down?
MALCOLM I have this injury from a couple of years ago and it flares up every once in a while just so I won't forget it.
Beat.
Cole slowly slides down the pew, giving Malcolm most of the seat.
Malcolm sits.
Cole fidgets with his soldiers.
Beat.
Malcolm looks over and stares at Cole's glasses.
He leans forward to inspect them more carefully.
MALCOLM Your eye frames.
MALCOLM They don't seem to have any lenses in them.
COLE They're my dad's.
COLE The lenses hurt my eyes.
MALCOLM I knew there was a sound explanation.
Malcolm returns to staring at his lap.
Beat.
MALCOLM What was that you were saying before with your soldiers?
MALCOLM Day pro fun.
COLE ...De profundis clamo ad te domine.
Malcolm stares surprised.
COLE It's called Latin.
COLE It's a language.
Malcolm nods at the information.
MALCOLM All your soldiers speak Latin?
COLE No, just one.
Malcolm smiles at Cole.
His eyes drift down to Cole's arms.
Malcolm's smile slowly disappears.
Cole's arms are covered in TINY CUTS AND BRUISES.
Some almost healed.
Some fresh.
Malcolm looks around to gather himself.
Beat.
MALCOLM I like churches, too.
MALCOLM In olden times, in Europe, people used to hide in churches.
MALCOLM Claim sanctuary.
Cole looks up.
COLE What were they hiding from?
MALCOLM Oh, lots of things, I suppose.
MALCOLM Bad people for one.
MALCOLM People who wanted to imprison them.
MALCOLM Hurt them.
COLE Nothing bad can happen in a church, right?
Malcolm studies Cole's anxious face.
MALCOLM Right.
Malcolm and Cole just stare at each other.
COLE I forgot your name.
MALCOLM Dr. Crowe.
COLE You're a doctor.
COLE What kind?
MALCOLM I work with young people who might be sad or upset or just want to talk.
MALCOLM I try to help them figure things out.
Beat.
COLE Are you a good doctor?
Malcolm smiles.
MALCOLM I got an award once.
MALCOLM From the Mayor.
COLE Congratulations.
MALCOLM Thank you.
MALCOLM It was a long time ago.
MALCOLM I've kind of been retired for a while.
MALCOLM You're my very first client back.
COLE You use needles?
MALCOLM No.
COLE Not even little ones that aren't supposed to hurt?
MALCOLM No.
COLE That's good.
Cole pockets his soldiers and rises from his pew.
COLE I'm going to see you again, right?
MALCOLM If it's okay with you?
Cole thinks it over carefully.
COLE It's okay with me.
Cole and Malcolm just stare at each other.
MALCOLM And Cole, next time I won't be late for you.
COLE Next time I won't be scared of you.
Cole turns and starts to the rear of the church.
Malcolm loses himself in his thoughts.
When Malcolm looks back, he sees Cole stop by the exit doors and take a tiny STATUE OF JESUS off the back table.
Cole pockets the statue and quietly leaves the church.
Malcolm just sits and stares.
The house is dimly lit.
Malcolm has to turn on the HALLWAY LIGHT.
MALCOLM It's me.
He stops before a pile of mail collecting on a thin table.
He stares at it blankly.
Almost every envelope has "Over Due" or "Final Notice" stamped on it.
Malcolm stares down at the remains of a meal on the only place setting on the table.
Malcolm quietly walks into his bedroom.
Only A READING LIGHT IS
Malcolm moves to her side.
The sight of her stops him.
He stares at his wife...
She huddles under a blanket, a wad of tissues in her hand.
He takes it in silently.
His eyes move to her face...
One wisp of hair falls over her soft lips.
OUTLINED IN THE SOFT READING LIGHT, Anna Crowe truly looks like an angel.
Malcolm forms a tiny smile.
Malcolm turns and moves for a narrow door in the hallway.
THE DOOR KNOB.
He tries to open it.
IT'S LOCKED.
Malcolm reaches into his pockets.
Searches for his keys.
The empty basement is no longer empty.
It's piled with file cabinets and boxes of psychology and medical books.
A desk sits in the corner next to the wine racks.
The room still feels unsettling.
Malcolm hunches over one of the books.
Rifles through a stack of dusty books.
Pulls out a thick text.
The spine of the text reads, "The Meridian Latin Dictionary."
Malcolm sits back at his desk and opens Cole's file.
Handwritten on the first page are the words,
"De profundis calms ad te, domine"
Malcolm starts working through the Latin text.
As he comes to each word, he jots it down underneath the Latin.
Malcolm translates the last word.
He stares quietly at the paper.
The new words reads...
"Out of the depths, I cry to you Lord."
Beat.
MALCOLM ...The mass for the dead.
The words seem to hang in the air forever.
Old Philadelphia awakens...
For a moment, it's like we're back in time.
A golden sun dances on the waters of Penns Landing.
Historical old ships sit docked in its harbor...
The dark bronze surface of the Liberty Bell reflects the dawn...
A majestic Independence Hall stands watch as its city begins to stir...
A thirty foot statue of Ben Franklin makes a proud silhouette against the morning sky...
FLUORESCENT HOUSE LIGHTS COME ON IN WINDOWS...
Jeeps and hatchbacks start roaming the cobblestone streets...
Neon restaurants signs flicker to life...
Traffic helicopters make their rounds...
CAR ALARMS PIERCE THE AIR.
A hand turns off a radio, shutting off the morning news.
A small dog with two different colored eyes sticks his head out of the dryer, where he plays with the newly-dried clothes.
LYNN SEAR reaches in and pulls out a blouse.
She shakes it in the air and slips it on as she dresses hurriedly for work.
Lynn is a woman in her late twenties.
One hundred percent South Philly.
Hair teased.
She chews on an early morning piece of Trident.
Under all of it, Lynn Sear is an attractive and sweet-looking young woman.
Lynn enters THE KITCHEN through a swinging door.
A bowl of cereal and milk sit on a table in an empty kitchen.
Lynn stares at a handful of kitchen CABINETS and DRAWERS that are open.
Lynn shakes her head.
LYNN Cole.
She closes them one at a time before moving to the coffee machine.
Lynn shivers a little.
She leans over the thermostat and raises the heat.
She returns to her post at the coffee machine.
Lynn turns to see Cole standing in his private school uniform.
LYNN Your Cocoa Puffs are getting soggy.
Lynn walks over to Cole.
Checks his tie.
LYNN You got a spot.
Lynn unclips the tie.
Cole takes a seat at the kitchen table as Lynn walks back into the laundry room.
The dog is gone now.
Lynn reaches into the dryer, digging for a new tie.
She finds one, then turns and steps back into the kitchen and SCREAMS AT THE TOP OF HER LUNGS.
Every cabinet and every drawer is wide open.
Cole sits at the kitchen table.
His hands are pressed flat on the tabletop.
He looks shaken.
Neither says anything for a beat.
LYNN Something you were looking for, baby?
Beat.
COLE Pop Tarts.
Lynn looks over to the open cabinet near the sink.
The pop tarts are clearly visible.
LYNN They're right here.
COLE Oh.
Cole gets up from the table.
Takes his pop tarts.
Doesn't make eye contact.
COLE What are you thinking, Momma?
LYNN Lots of things.
COLE Anything bad about me?
Lynn leans down.
LYNN Look at my face.
Cole does.
LYNN I wasn't thinking anything bad about you, got it?
He looks at her eyes.
Beat.
COLE Got it.
COLE That's Tommy, Momma.
Cole quietly kisses his mother on the cheek and starts out.
LYNN Don't you want this?
Cole turns to see Lynn holding the pop tarts.
He walks back and takes them from her before leaving.
Beat.
Lynn glances to the kitchen table.
Her gaze stops on the TWO TINY HAND PRINTS OF SWEAT formed on the table's surface.
Lynn stands motionless in the kitchen.
She looks up and wraps her arms around her shivering shoulders.
TOMMY TAMMISIMO is a tough-looking, eight-year-old Italian kid who waits at the bottom of Cole's brownstone stairs in his school uniform.
Cole emerges from the brownstone and moves down the steps.
Lynn's face appears in the kitchen window.
The two boys begin their walk down the street to school.
Tommy puts his arm around Cole.
Lynn waves.
Cole waves back.
When the two boys turn the corner and are out of Lynn's sight, Tommy rips his arm away.
TOMMY Hey freak, how'd you like the "arm around your shoulder" bit.
TOMMY I just made it up.
TOMMY Went with it.
TOMMY That's what great actors do.
TOMMY It's called improv.
Tommy starts to run ahead, he turns and back pedals.
TOMMY Be careful...
TOMMY I hope no one jumps out and gets you.
Tommy runs away.
Beat.
Cole looks around nervously.
The last uniformed boys and girls rush into the front doors of St.
Anthony's Academy as the FINAL BELL SOUNDS.
Cole is the last one to go in.
He stands alone on the sidewalk.
He looks like he'd rather be anywhere but there.
Beat.
He buries his hands in his pockets and begins a quiet walk by himself into the school.
The front door CREAKS open as Cole walks in after school.
He looks around before closing the door.
His eyes stop on Lynn seated in the open doorway of the den.
Malcolm is seated with her.
They both look up.
Lynn comes out.
She reaches Cole -- kneels down in front of him.
LYNN How was school, baby?
Cole shrugs.
LYNN You know, you can tell me things if you need to.
Cole doesn't respond.
Beat.
LYNN Well, you know what I did today?
Cole shakes his head "No."
LYNN I won the Pennsylvania Lottery in the morning.
LYNN I quit my jobs.
LYNN Ate a big picnic in the park with lots of chocolate mouses pie and then swam in the fountain all afternoon...
LYNN What did you do?
Cole starts to smile too.
He thinks.
COLE I was picked first for kickball teams at recess.
COLE I hit a grand slam to win the game and everyone lifted me up on their shoulders and carried me around cheering.
Cole and Lynn smile at each other.
Beat.
Lynn tries to hide the utter sadness behind her smile.
LYNN I'll make triangle pancakes.
LYNN You got an hour.
Lynn takes Cole's school bag and jacket before moving to the kitchen.
The den doubles as a playroom.
Boxes of old toys sit in the corner.
A small, plastic, multi-colored table sits on the rug.
Cole appears in the doorway.
Malcolm sits up and smiles.
He points to the chair on the other side of the coffee table.
MALCOLM You want to sit?
Cole nods very softly, "No."
MALCOLM Don't feel like talking right now?
Cole nods again very softly, "No."
MALCOLM How about we play a game first?
Cole looks a little more interested.
MALCOLM It's a mind-reading game...
MALCOLM Did I mention I could read minds?
Cole nods, "No."
MALCOLM Here's the game.
MALCOLM I'll read your mind.
MALCOLM If what I say is right, you take a step forwards the chair.
MALCOLM If I'm wrong, you take a step backwards the doorway.
MALCOLM If you reach the chair, you sit.
MALCOLM If you reach the door, you can go.
MALCOLM Deal?
Cole tilts his head, then nods, "Yes."
Malcolm presses his fingers to his temples like a vaudeville magician.
He closes his eyes tight.
MALCOLM Just after your mom and dad were divorced, your mom went to a doctor like me and it didn't help her.
MALCOLM And so you think I'm not going to help you.
Beat.
Cole, surprised, takes a small step forward.
MALCOLM You're worried because she said she told him things.
MALCOLM Things she couldn't tell anybody else.
MALCOLM Secrets.
Cole takes a step.
Malcolm opens his eyes.
He looks right at Cole.
MALCOLM You have a secret.
MALCOLM But you don't want to tell me.
Beat.
Cole takes another step.
The next step will put him at the chair.
Malcolm lowers his fingers from his temple.
MALCOLM You don't have to tell me your secret if you don't want to.
Malcolm smiles.
Returns his fingers to the mind-reading position.
Malcolm looks to Cole's arm.
Cole is wearing A LARGE SILVER WATCH.
It swims on his thin wrist.
It could probably slide up to his shoulder.
Malcolm closes his eyes.
MALCOLM Your father gave you that watch as a present before he left.
Cole takes a step BACK.
Beat.
Malcolm lowers his hands surprised.
COLE He forgot it in a drawer.
COLE It doesn't work.
Beat.
Malcolm puts his fingers to his temple.
This time a little bit slower.
He gazes at Cole's school uniform.
MALCOLM You don't like to say much at school.
MALCOLM You're an excellent student however.
MALCOLM You've never been in any kind of serious trouble.
Beat.
Cole takes a slow step back.
Beat.
COLE We were supposed to draw a picture.
COLE Anything we wanted...
COLE I drew a man.
COLE He got hurt in the neck by another man with a screwdriver.
MALCOLM You saw that on T.V., Cole?
Cole answers by taking a small step back.
Beat.
COLE Everybody got upset.
COLE They had a meeting.
COLE Momma started crying.
COLE I don't draw like that anymore.
MALCOLM How do you draw now?
COLE I draw people with smiles, dogs running, and rainbows.
COLE They don't have meetings about rainbows.
MALCOLM I guess they don't.
Malcolm looks down at Cole's feet.
They're almost at the doorway.
One more step and he's there.
Cole is very still.
He doesn't move at all.
COLE What am I thinking now?
Malcolm takes his time before speaking.
He just stares.
No fingers to the temple.
No games.
He just stares.
Beat.
MALCOLM You're thinking...
MALCOLM I don't know what you're thinking, Cole.
Cole quietly takes a step back into the doorway of the other room.
COLE I was thinking...
COLE you're nice.
COLE But you can't help me.
Cole's tiny figure steps away.
Malcolm stares helplessly at the empty doorway where his client used to stand.
Malcolm hurriedly enters a spacious, dimly-lit Italian restaurant.
He stops in the dining room and searches the many candle-lit tables.
He finds Anna.
Anna sits alone at a corner table.
The remains of her half-eaten dinner lay on the only place setting on the table.
A small PIECE OF CAKE WITH A CANDLE in it sits untouched.
Anna stirs sugar in her coffee as Malcolm sits in the seat across from her.
She gently stops stirring, but doesn't look up.
Beat.
MALCOLM I thought you meant the other Italian restaurant I asked you to marry me in.
Anna isn't laughing.
Not even close.
MALCOLM I'm so sorry.
MALCOLM I can't seem to keep track of time.
Anna quietly takes a sip from her coffee.
MALCOLM It didn't go well today.
MALCOLM Spent some time after trying to get my head together.
Anna looks around for the waiter.
MALCOLM They're so similar, Anna.
MALCOLM They have the same mannerisms.
MALCOLM The same expressions.
MALCOLM The same thing hanging over them.
MALCOLM It might be some kind of abuse.
That makes Anna turn back.
She glances across the table, then looks down.
MALCOLM There are cuts on Cole's arms.
MALCOLM Fingernail marks, I think.
MALCOLM Looks like defensive cuts.
Malcolm demonstrates by holding up his arm to shield his face.
MALCOLM Possibly a teacher, neighbor.
MALCOLM I don't think it's the mother.
MALCOLM Just a gut thing.
MALCOLM The way she deals with him.
MALCOLM It doesn't fit.
MALCOLM Hard to say this early.
MALCOLM Could just be a child climbing a lot of trees.
Malcolm loses himself in his thoughts.
The waiter drops off the check on the table.
Anna grabs it before Malcolm and quickly signs it.
MALCOLM I know I've been kind of out of it for a long while and you resent it.
MALCOLM You do.
MALCOLM I know you're mad.
MALCOLM I know it's put some distance between us.
Beat.
MALCOLM But I'm getting a second chance here.
MALCOLM I can't let it slip away.
Anna waits till he's done and rises from the table.
She pushes her chair in hard and walks away without a word.
Malcolm sits alone and stares at the piece of cake with a candle on it.
MALCOLM ...Happy Anniversary.
Cole is seated on the front stoop of his brownstone.
On the steps and on the landing are his plastic soldiers in the grips of a war.
Malcolm sits with his bag and overcoat on the step next to him.
Malcolm just observes quietly.
Beat.
Cole glances up as he plays.
Sees Malcolm's expression.
COLE You want to ask me a question?
MALCOLM See, this is why I lose at poker.
MALCOLM Yes, I do have a question.
On the step are two rows of soldiers facing each other.
To one side are a couple soldiers covered by a tissue.
Malcolm points to them.
MALCOLM What happened to those two?
MALCOLM Being under tissue paper can't be a good thing.
Cole removes the tissue.
COLE That's Private Jenkins and Private Kinney.
COLE They got killed.
COLE Private Jenkins has a baby girl that was born seven pounds, six ounces.
COLE He's never seen her.
COLE He wanted to get back to Blue Bell, Pennsylvania and hold her...
Cole points to the other soldier.
COLE Private Kinney's wife is really sick -- she has something called a brain anism.
MALCOLM You mean aneurysm.
COLE Yeah, Private Kinney needed to get back safe to take care of her.
Beat.
Cole's face becomes emotional.
Tears fill his eyes.
COLE It's sad they died, isn't it?
Malcolm falls into silence and stares at his client.
Beat.
Cole wipes his eyes quickly.
COLE Don't look at me.
COLE I don't like people looking at me like that.
Malcolm takes in Cole's gesture and expression.
COLE Stop looking at me.
Malcolm looks down.
MALCOLM Where should I look then, Cole?
COLE Look over there.
Cole points to the corner of the street.
Malcolm slowly turns.
He sits in profile to Cole.
Beat.
MALCOLM It's very unusual for someone your age to understand the kind of problems that Private Jenkins and Private Kinney have or even to be thinking about them at all...
Malcolm continues to stare at the street.
Beat.
MALCOLM It is okay if I look back now?
Cole doesn't answer.
MALCOLM Tap the foot once for "No" and twice for "Yes."
Cole taps his foot once.
Malcolm sits patiently.
Beat.
They don't say anything for a while.
MALCOLM You wouldn't want to take a walk, would you?
Cole looks up from his soldiers.
Malcolm stares at the far side of the street.
Cole taps his foot twice.
The two of them walk down a row of brownstones across from a park where children Cole's age are playing.
COLE I walk this way to school with Tommy Tammisimo.
MALCOLM He your best buddy?
Cole almost smiles.
COLE He hates me.
MALCOLM You hate him?
Cole shakes his head, "No.!
Malcolm thinks for a bit.
MALCOLM Your mom set that up?
Cole nods "Yes."
MALCOLM You ever tell her about how it is with Tommy?
COLE I don't tell her a thing.
MALCOLM Why?
COLE Cause she doesn't look at me like everybody and I don't want her to.
COLE I don't want her to know.
MALCOLM Know what?
COLE That I'm a freak.
Malcolm stops walking.
The words hit him hard.
He stares at Cole.
MALCOLM Listen to me.
MALCOLM You are not a freak.
MALCOLM Don't you believe anybody that tells you that.
MALCOLM It's bullshit and you don't have to grow up believing that.
Beat.
Cole is surprised.
COLE You said the "s" word.
MALCOLM Yeah.
MALCOLM Sorry.
Malcolm's face is filled with emotion.
Cole is suddenly hit by Malcolm's passion.
Beat.
Cole nods slowly as he looks at Malcolm with different eyes.
They start walking again in silence.
They turn a corner and move down another street.
Cole spots an old man with a cane standing at the gate of a brownstone.
COLE Is it okay if I do something?
COLE I have to do something.
Malcolm nods "yes" as they continue walking.
Cole slows as they approach the old man.
As we get closer, we make out the man can barely see.
COLE Hi, Mr. Marschal.
MR.
MARSCHAL leans over his gate and stares at Cole for a few seconds.
MR. MARSCHAL Guten Tag, Cole.
Mr. Marschal has a thick German accent.
The old man squints down the block with a concerned expression.
COLE What's wrong?
MR. MARSCHAL Mrs. Marschal.
MR. MARSCHAL She went food shopping.
MR. MARSCHAL She's running late.
Beat.
COLE Ich Habe Durst.
Malcolm's eyes dart to Cole.
MR. MARSCHAL Wunderbar!
MR. MARSCHAL Where did you learn to speak German?
COLE I just know a couple lines.
MR. MARSCHAL Yes, you may have a drink.
MR. MARSCHAL What would you like?
COLE Lemonade, please.
Mr. Marschal smiles at Cole before walking back inside his house.
Cole turns back to Malcolm.
COLE Mr. Marschal gets real lonely.
MALCOLM What about Mrs. Marschal?
COLE She died a long time ago.
This brownstone has been home to the Marschal's for many, many years.
It's filled with a lifetime of memories.
Memories shared by two people.
Two rocking chairs sit side by side near the windows that overlook the street...
A corner table displays fancy wooden chess set.
The game half-finished, frozen in a layer of dust...
An easel stands before a piano.
The incomplete water color painting of a smiling elderly woman sitting on the piano bench sits sadly on the faded yellow paper.
Malcolm takes in the living room silently.
He stands near the open door.
Cole walks through the room.
Tiny eyes searching carefully.
He leans behind the sofa looking for something.
Malcolm watches Cole with a crinkled brow.
Cole peeks behind the old piano crammed against the wall.
MR. MARSCHAL Maybe Jill will play for us when she gets back.
Cole turns to find Mr. Marschal standing with a glass of lemonade.
Cole takes it from his shaking hands.
COLE Thank you.
Mr. Marschal shuffles over to the sofa.
Takes a seat.
Cole begins surveying the room again.
Beat.
His eyes finally come to rest on a plant seated in the corner.
He stares at it...
Cole puts down his glass on a table and walks over to the plant.
Cole kneels down and starts to push the potted plant aside.
THE
Malcolm calls to Cole under his breath.
MALCOLM Cole--
MR. MARSCHAL What's going on there?
Mr. Marschal strains to see across the room.
Cole doesn't answer either of them.
Instead, he continues to push the plant aside revealing AN AIR VENT.
Cole gently reaches over and takes off the metal face.
It slips right off.
Cole's hands disappear into the darkness of the vent.
They reemerge holding a STACK OF NOTEBOOKS.
Malcolm becomes very still.
Cole rises to his feet and carries the notebooks over to Mr.
Marschal.
Cole carefully places them on his lap.
MR. MARSCHAL Is this for me?
Mr. Marschal fingers the notebooks then reaches for his thick glasses hanging from his neck.
He places them on the tip of his nose and inspects the notebooks six inches from his face.
MR. MASCHAL What's this?
MR. MASCHAL Jill's keeping a diary.
Malcolm takes an involuntary step forward.
Mr. Marschal starts flipping through the notebooks.
MR. MARSCHAL She's full of surprises...
He gets to the last book.
His hands become still as he stares at the final page of writing.
MR. MARSCHAL She hasn't written anything for some time.
Beat.
Mr. Marschal slowly looks up from the notebooks.
Looks up to Cole.
Cole just stands quietly.
Mr. Marschal's eyes slowly fill with tears of realization.
They gently spill down his weathered face.
MR. MARSCHAL Oh no...
Cole takes a deep breath.
Trying hard not to cry himself.
The sight of Mr. Marschal weeping shakes Cole.
Cole softly lays his hand on Mr. Marschal's silver hair.
Mr.
Marschal reaches up and clutches his small hand.
They stay like that for a while.
Beat.
Mr. Marschal lets go and brings the notebooks tighter to his body.
Cole quietly walks to Malcolm who stands motionless.
He stares down at Cole in a daze.
Cole turns his head, crying.
COLE Stop looking at me.
Malcolm sits still in his office chair.
His eyes are fixed at a point in space.
He brings a slim, black tape recorder to his mouth.
MALCOLM April or March of Eighty-seven.
MALCOLM Two weeks into sessions with Vincent Gray.
MALCOLM I was treating a couple, Donald and Robin Wagner, who had lost their child to Leukemia.
MALCOLM They were waiting with Vincent in the reception room of the downtown clinic.
MALCOLM They were alone together maybe fifteen minutes.
MALCOLM When I entered the room, all three were crying.
MALCOLM The Wagner's progress from that afternoon was dramatic and sudden ....
MALCOLM As if some door had been opened for them.
MALCOLM I'm not at all clear what happened in those fifteen minutes.
MALCOLM But I now believe Vincent tried to tell me something, show me something and I didn't listen.
MALCOLM Cole Sear allowed me to witness something today.
MALCOLM This time I'm going to listen.
A long silence.
CLICK.
The tape recorder turns off.
Lynn holds a laundry basket on her hip as she fiddles with the thermostat in the hall.
The house is cold.
Lynn wears a winter jacket in the house.
Lynn turns and moves into the shadowy hallway.
No lights.
The house seems somewhat ominous.
Beat.
Lynn's eyes dart to an open guest room like she just saw something.
She stares in the doorway until a SOUND TURNS HER IN
She picks up balled-up boy's sweat socks and dirty T-shirts laying on the carpet.
When she reaches the end of the hall, she HITS A LIGHT SWITCH.
The hall LIGHTS UP REVEALING A WALL OF PHOTOS.
Lynn forms a tiny smile.
Snapshots of Cole and Lynn's life hang before her eyes.
Cole's birthday parties...
Lynn and Cole at an amusement park...
Cole under the Christmas tree...
Cole on Lynn's shoulders in a pool...
Cole with a group of neighbors at a barbecue...
Lynn takes a step forward.
Lynn's face betrays the fact that she notices something she never noticed before.
She touches a photo of three-year-old Cole.
Lynn looks to the adjacent photo -- the barbecue photo -- Everyone stands with hot dogs and sodas.
Lynn searches the picture.
Her eyes suddenly stop at the TINIEST BLUR OF WHITE
Lynn takes it all in curiously.
Lynn moves into Cole's room with the laundry basket balanced on her hip.
The Walkman headphones on her head blares A MUFFLED TECHNO DANCE BEAT.
Lynn starts picking clothes up around Cole's room.
This bedroom is an eerie place.
The shadows seem to make shapes and figures.
All the furniture is wood -- old fashioned.
The lamps, the paintings on the wall -- antiques as well.
The most striking feature of the room, however, is the homemade tent created from bedsheets and blankets tied to chairs and bureaus.
It takes up a large corner of the room.
A sign hangs over the bedsheets.
Lynn grabs the spiderman P.J.s that drape over the tent.
A German Shepherd Puppy sleeps on the pillow.
SEBASTIAN lifts his head sleepily and peers at Lynn before returning to his slumber.
Lynn slowly reaches for a picture frame that peeks out from under Cole's pillow.
Slides it out...
It's a VACATION PHOTO of a couple.
Lynn and Cole and a man.
The man looks in every way a larger version of Cole.
The picture has a visible effect on Lynn.
She lets out a shaky breath before returning the photo to its hiding place.
Lynn pulls a pair of school uniform pants off the wooden roll cover desk next to the bed.
The desk is covered with loose leaf papers filled with writings.
Lynn's eyes are drawn to the papers.
Her curious gaze turns serious.
Her mouth opens a tiny bit involuntarily.
THE PAPERS are strewn with lines of handwriting.
Countless lines.
Thousands of words...
Some horizontal, some vertical...
The writing moves in arcs and flows in various size -- written at great speed -- every word connected by a single pen stroke -- everything written in one continuous motion.
Lynn slowly spins the papers, taking in some of the phrases...
...Christ break the freaking glass oh no God no what the hell is going on Quiet the damn baby I'll cut you I swear it someone stop the burning I'll kill you I'll kill all you bastard...
The words go on and on.
Lynn removes her hands from the paper.
She pulls her headphones off slowly.
Malcolm stares as the rain pelts the windows of the den.
MALCOLM ...So your dad lives in Pittsburgh with a lady who works in a toll booth.
COLE What if she has to pee when she's working?
COLE You think she just holds it?
MALCOLM I don't know.
MALCOLM I was just thinking the same thing.
Beat.
COLE You ask a lot of questions about my dad today.
COLE How come?
Cole is playing behind the couch.
All we see is the top of his head.
MALCOLM Sometimes, we don't even know it, but we do things to draw attention.
MALCOLM Do things so we can express how we feel about issues...
MALCOLM Divorce or whatever.
Every now and then we get glimpses of things Cole is playing with peeking over the back of the couch, but we can't quite make out what he's doing.
MALCOLM One night, as an example...
MALCOLM leave something on a desk for someone to find.
The top of Cole's head stops moving.
MALCOLM Cole, have you ever heard of something called free-writing?
MALCOLM Or free-association writing?
Cole shakes his head, "No."
MALCOLM It's when you put a pencil in your hand and put the pencil to a paper and you just start writing...
MALCOLM You don't think about what you're writing...
MALCOLM You don't read over what you're writing...
MALCOLM You just keep your hand moving.
Cole has become very still.
He looks right at Malcolm.
MALCOLM After awhile if you keep your hand moving long enough, words and thoughts start coming out you didn't even know you had in you...
MALCOLM Sometimes they're things you heard from somewhere...
MALCOLM Sometimes they're feelings deep inside...
MALCOLM Have you ever done any free- association writing, Cole?
Beat.
Cole nods, "Yes."
MALCOLM What'd you write?
COLE Words.
MALCOLM What kind of words?
COLE Upset words.
Beat.
MALCOLM Did you ever write any upset words before your father left?
Beat.
COLE I don't remember.
Malcolm watches him carefully.
Beat.
Malcolm waves the question off casually.
MALCOLM Can you do something for me?
Malcolm smiles.
He rises and grabs his coat.
MALCOLM Think about what you want from our time together.
MALCOLM What our goal should be?
COLE Something I want?
MALCOLM If we could change something in your life, anything at all, what would you like that to be?
Cole's brow furrows as he thinks about it carefully.
MALCOLM You don't have to answer now.
Malcolm heads for the door, stops when Cole emerges from behind the couch.
Cole is wearing his father's jacket, it hangs to the ground like a dress.
COLE Instead of something I want, can I have something I don't want?
Malcolm turns back to Cole.
Malcolm nods "Yes."
Beat.
COLE I don't want to be scared anymore.
Cole's sad eyes stare up at Malcolm.
The surface of Malcolm's desk is covered with open texts.
Malcolm pours over a thick reference book.
He circles a phrase...
"...resulting bruises and abrasions on arms and legs may, in fact, be self-inflicted."
Malcolm appears disturbed by the thoughts running through his head.
His face turns up to the ceiling.
MALCOLM Are you calling me?
ANNA What?
ANNA You don't see enough of me at the store?
Malcolm gets up and moves closer to their voices as he stretches his legs.
MAN'S VOICE On my way to the flea market in Amish country.
MAN'S VOICE Thought maybe you want to come.
MAN'S VOICE Show me how to buy at these things.
ANNA I trust you...
ANNA Besides, I don't know if I'm up for the Amish today.
ANNA You can't curse or spit or anything around them.
Malcolm smiles at Anna.
MAN'S VOICE I thought you'd want to get out.
MAN'S VOICE You've been kind of down.
Malcolm slowly stops smiling.
ANNA That's very sweet.
ANNA I'm okay.
MAN'S VOICE Do you think I should stop by on my way back?
MAN'S VOICE Show you what I got?
MAN'S VOICE It's not a problem.
Malcolm shakes his head in disbelief.
ANNA You know that's probably not the best idea.
ANNA I'll just wait to see them in the store.
MAN'S VOICE Okay.
MAN'S VOICE Fine.
MAN'S VOICE Understood.
MAN'S VOICE I'm off then.
ANNA Don't step in the horse manure.
MAN'S VOICE Thanks.
Malcolm moves to the narrow basement window.
We see SEAN, an attractive young man in his late twenties.
He gets into his car across the street.
He just sits there for a moment before putting his forehead to the steering wheel.
MALCOLM Give it up, kid.
Malcolm turns away from the window as Sean's car starts up and pulls away from Malcolm's house.
STANLEY CUNNINGHAM is a teacher in his late forties.
He writes a question on the board.
MR. CUNNINGHAM Can anyone guess what city was the capital of the United States of America from 1790 to 1800?
Mr. Cunningham turns and stares at his class of eight and nine year old private school students.
They stare back at him blankly.
Cole rests his chin on his desk and watches the class with big eyes.
MR. CUNNINGHAM ...I'll give you a hint, it's the city you live in.
The class says the answer in unison.
CLASS Philadelphia.
MR. CUNNINGHAM Right...
MR. CUNNINGHAM Philadelphia is one of the oldest cities in the country.
MR. CUNNINGHAM A lot of generations have lived and died in this city...
MR. CUNNINGHAM Almost every place you visit has a history and a story behind it.
MR. CUNNINGHAM Even this school and the grounds they sit on...
MR. CUNNINGHAM Can anyone guess what this building was used for a hundred years ago, before you went here, before I went to this school even?
Stanley Cunningham looks over the class of blank faces.
He's just about to answer his own question when he sees a hand go up.
Mr. Cunningham looks surprised to see who it is.
MR. CUNNINGHAM Yes, Cole?
COLE They used to hang people here.
Mr. Cunningham furrows his brow.
Beat.
MR. CUNNINGHAM That's not correct.
MR. CUNNINGHAM Where'd you hear that?
COLE They'd pull the people in crying and kissing their families bye...
COLE People watching would spit at them.
Beat.
MR. CUNNINGHAM Cole, this was a legal courthouse.
MR. CUNNINGHAM Laws were passed here.
MR. CUNNINGHAM Some of the first laws of this country.
MR. CUNNINGHAM This building was full of lawyers.
MR. CUNNINGHAM Lawmakers.
COLE They were the ones who hanged everybody.
Mr. Cunningham chuckles.
Cole's face turns cement grey.
MR. CUNNINGHAM I don't know which one of these guys told you that, but they were just trying to scare you, I think.
Tommy Tammisimo leads the class in a wave of snickering.
Cole glances up.
Sees all the eyes on him.
He glances at the teacher who is still staring.
COLE I don't like people looking at me like that.
MR. CUNNINGHAM Like what?
COLE Stop it!
Mr. Cunningham sees the traumatized expression on Cole's face and instantly stops smiling.
MR. CUNNINGHAM I don't know how else to look--
COLE You're a stuttering Stanley!
Mr. Cunningham's face becomes still.
So does the classroom.
MR. CUNNINGHAM Excuse me?
COLE You talked funny when you went to school here.
COLE You talked funny all the way to high school!
The class falls into stunned silence.
Mr. Cunningham takes an involuntary step towards Cole's desk.
MR. CUNNINGHAM What--
COLE You shouldn't laugh at people.
COLE It makes them feel bad.
Mr. Cunningham moves closer to Cole.
MR. CUNNINGHAM How did you--?
COLE Stop looking at me.
Cole covers his eyes with his hands.
MR. CUNNINGHAM Who have you been s-speaking to?
We see Cole's mouth under his covered eyes.
COLE Stuttering Stanley!
COLE Stuttering Stanley!
MR. CUNNINGHAM Who!
Mr. Cunningham is standing right over Cole's desk now.
COLE Stuttering Stanley!
MR. CUNNINGHAM S-ssstop that!
COLE Stuttering Stanley!
COLE Stuttering Stanley!
MR. CUNNINGHAM S-ssssstop it!
COLE Stuttering--
MR. CUNNINGHAM --Shhhhhhut upppp you fffffffreak!
MR.
CUNNINGHAM SLAMS HIS HAND ON COLE'S DESK.
Cole's hands drop from his eyes.
The teacher's face is burning red.
The children in the room are frozen.
Completely startled.
Cole's eyes are filled with tears.
Mr. Cunningham's expression drains of anger as Cole Sear begins to cry.
Cole is seated in the school library by himself.
He sits at a long center table near the windows.
His head is laying on his folded arms on the table.
Malcolm peeks his head in the door -- unsure if he's in the right place.
He spots Cole and enters the room.
He silently takes a seat across from Cole.
The eight-year-old looks up.
Cole's eyes are hard -- filled with anger.
MALCOLM Hey, big guy.
Cole stares for a second.
COLE I don't want to talk about anything.
Cole lowers his head.
Malcolm just sits and thinks.
Cole turns his head and stares at the windows.
Malcolm takes in the sad vision of this boy.
It affects him.
Beat.
MALCOLM Do you like magic?
Cole's face softens a bit.
He turns from the windows and looks to Malcolm.
Beat.
Cole nods, "Yes."
Malcolm pulls out a penny from his pocket.
He places it in his right hand.
MALCOLM Watch the penny closely.
Malcolm closes his hand around the penny.
MALCOLM I do the magic shake...
Malcolm shakes his hand in circles.
Cole watches his hand carefully.
MALCOLM And suddenly the penny has magically traveled to my left hand...
Cole looks to Malcolm's closed left hand.
Malcolm doesn't open it.
MALCOLM But that's not the end of the trick.
MALCOLM With another magic shake, the penny travels into my shirt pocket...
Cole's eyes lock on Malcolm's shirt.
Malcolm taps the pocket but doesn't open it.
MALCOLM But that's still not the end!...
MALCOLM I do a final magic shake...
MALCOLM and suddenly...
MALCOLM The penny returns to the hand where it started from.
Malcolm opens his right hand.
The penny sits quietly in the center of his palm.
Cole looks at the penny and then up to Malcolm's face.
Beat.
Cole cracks a smile.
COLE That isn't magic.
MALCOLM What?
COLE You just kept the penny in that hand the whole time...
MALCOLM Who me?
Malcolm smiles a mischievous smile.
He places the penny on the table.
Cole stares at it and then looks to Malcolm.
COLE I didn't know you were funny.
MALCOLM I forgot myself.
Malcolm and Cole share a warm look.
Cole's expression changes back to sadness as he looks to the windows.
Malcolm leans across the table and whispers.
MALCOLM Cole...
Cole looks at Malcolm.
MALCOLM One day...
MALCOLM You're going to sound just like them.
Beat.
Cole's chin starts to tremble.
His voice cracks.
COLE Promise?
Beat.
MALCOLM Promise.
Malcolm and Cole sit in silence and listen to THE SOUND OF
Malcolm sorts through the many bills on the mail table.
WOMAN Malcolm, sit your cute butt down and listen up.
WOMAN Are you listening?
Malcolm turns AT THE SOUND OF THE WOMAN, and moves into the empty living room where the T.V. is on.
A blanket lays crumpled on the sofa.
BRIDESMAID No doubt about it.
BRIDESMAID Anna's like my sister.
BRIDESMAID You better make her happy...
BRIDESMAID And I'm not talking about -- mmm this tastes like real butter -- kind of happy...
BRIDESMAID I'm talking about Julie Andrews twirling around like a mental patient on a mountain top -- kind of happy.
BRIDESMAID You're really lucky.
BRIDESMAID She's got so much love for you.
BRIDESMAID Don't tell her I told you, but she said she loved you from the first time she met you on the street.
BRIDESMAID She'd do anything for you.
BRIDESMAID I love you guys.
BRIDESMAID My nose is running.
BRIDESMAID Why isn't someone getting me a tissue?
Malcolm can't help smiling as he stares at the flickering images.
He turns and looks down the hall to their bedroom.
Malcolm moves into their bedroom.
Malcolm moves to the bathroom door and opens it slowly.
Malcolm steps into the bathroom quietly.
He stares at the silhouette of Anna's body through the smoked glass of the shower.
Anna stands still, her head tilted back.
Malcolm watches quietly.
By his experience, it's clear he's taken by his wife's beauty.
Malcolm starts towards the shower when his eyes glance to the sink.
Malcolm locks on a tiny bottle resting on the marble surface.
He reaches out and picks it up.
The label on the plastic bottle reads,
"Zoloft Anti-depressant" "To be taken twice daily"
Malcolm gently puts down the plastic bottle.
He gazes at the still figure of his wife as the water covers her.
Malcolm leaves the bathroom.
He makes sure not to make a noise with the door as he closes it shut.
Colorful balloons flutter in the wind in front of an old grey stone home.
Cole and an overweight boy named BOBBY are seated at a dining table covered in colorful paper.
A stack of birthday presents are sitting on the table next to a cake.
The house is filled with the SOUND OF CHILDREN PLAYING AND
Cole and the overweight boy are the only ones in the dining room.
Bobby watches with a dull expression as Cole moves his hand in circles in the air.
COLE ...Then you do the magic shake.
COLE And now the penny moves from my pocket all the way to the hand it started in.
Cole smiles and holds out his hand.
His fingers open to reveal the penny.
Bobby stares.
BOBBY That's stupid.
Cole loses his smile.
COLE It's supposed to be funny.
BOBBY It's stupid.
Cole and the overweight boy stare at each other.
BOBBY Give me my penny back.
Cole gives the boy his penny.
Beat.
Cole gazes at Bobby.
COLE ...Don't be sad.
Bobby looks up sharply.
BOBBY What'd you say?
COLE ...Nothing.
Bobby stares down at him before returning his attention to his tattered napkin.
The two boys sit in silence.
Cole sits alone in the corner of the living room.
The open kitchen doorway is next to him.
Inside the kitchen are Lynn and DARREN'S MOM speaking.
It's clear they're from different worlds.
Lynn is wearing tight clothes with hair teased to dramatic heights.
Darren's mom is in a designer suit.
LYNN ...He doesn't get invited places.
DARREN'S MOM It's our pleasure.
LYNN The last time was a Chuck E. Cheese party a year ago.
LYNN He hid in one of those purple plastic tunnels and didn't come out.
DARREN'S MOM Chuck E. who?
LYNN Cheese.
LYNN It's a kid's place.
Darren's mom smiles formally and turns to give the catering people instructions on how to lay out the food on her sterling silver trays.
LYNN He's my whole life.
Darren's mom turns back to Lynn, the forced smile on her face.
LYNN I work at an insurance place and at Penny's, so Cole can go to that good school.
DARREN'S MOM J.
DARREN'S MOM C. Jenny's?
Lynn nods "Yes."
DARREN'S MOM Good for you.
LYNN I wish I could be like my momma though.
LYNN She always knew what was wrong.
LYNN Knew just what to say.
Darren's mom glances at her expensive watch.
LYNN Cole's going through something bad.
LYNN He won't talk to me.
LYNN I'm his momma.
LYNN And I don't know what's wrong and I don't know what to say.
Lynn drowns in her thoughts.
Cole moves away from the kitchen with sad eyes.
Cole walks past two expensively-dressed mothers eating hors d'oeuvres as they move down the hallway.
MRS. WESTON Did you have the Brie?
MRS. SAUNDERS It tasted like cheese whiz.
They pass when Cole moves down the shiny mahogany wood hallway.
The women's conversation FADES AWAY behind him.
Cole turns a corner and comes to a dead stop.
He turns white as he stares at an open CRAWL SPACE CLOSET a few feet away.
Cole's eyes are riveted in the darkness of the closet.
Beat.
Tommy Tammisimo is one of the children.
He talks with the birthday boy, DARREN, a skinny kid in a party hat.
TOMMY I even got a trailer.
DARREN For what?
DARREN You only had one line.
TOMMY You're slow, you know that.
TOMMY The star of the commercial always has his own trailer.
TOMMY You need to think about your character alone.
Tommy glances down the hall and sees Cole standing frozen staring at the crawl space closet.
Tommy grabs Darren.
TOMMY Darren, check it out.
DARREN looks down the hall to Cole.
DARREN My dad made me invite him.
Tommy nudges Darren to move down the hall.
Cole breaks from his trance as Tommy and Darren walk up.
COLE Happy birthday, Darren.
TOMMY Something you want to see in there?
Tommy points to the crawl space.
COLE --No.
Beat.
Tommy looks to Darren and then back to Cole.
TOMMY We're going to put on a pretend play.
TOMMY You want to be in it?
Beat.
COLE ...Okay.
TOMMY It's called, "Locked in the Dungeon."
Tommy stares at Darren.
Darren finally gets it.
DARREN Yeah, Cole...
DARREN you get to be the one locked in the dungeon.
It happens too quick for Cole to react.
Darren and Tommy shove Cole backwards.
He stumbles into the darkness of the crawl space.
COLE Don't!
Tommy slams the door closed.
Darren turns the lock.
They crack smiles at each other as Cole bangs on the door.
The BANGING GOES ON FOR A FEW SECONDS AND THEN IT JUST STOPS.
Darren and Tommy look at each other and then back at the crawl space door.
Then THE SCREAMING BEGINS.
Darren and Tommy back away from the door as COLE SCREAMS IN TERROR at the top of his lungs.
He CRASHES OVER AND OVER against the door.
HIS BODY SLAMMING AGAINST THE WOOD.
The DOOR RATTLES like it's going to break off its hinges.
The two boys are statues as Cole's BLOOD-CHILLING YELLS FILL THE
FOOTSTEPS SPIKE THE AIR AS children and mothers come running down the hall.
Lynn is one of them.
Darren's mother turns the corner.
DARREN'S MOTHER Who's making that noise?
She looks to the closet.
THE HIGH-PITCHED SCREAMS CUT THROUGH
LYNN Cole!
Lynn and Darren's mom rush to the door and turn the knob...
The door flies open.
Lynn reaches in and pulls out Cole.
He's
Darren's mom looks into the crawl space -- there's nothing inside except a couple packing boxes in the back.
She looks to Lynn.
She turns around with Cole in her arms.
LYNN Help me get him in the car.
Colorful murals don the curved walls of the pediatric reception area.
A spattering of children accompanied by adults sit and wait.
Lynn and Malcolm are seated at a children's play table.
A game made of a maze of wires sit on the table in front of them.
A young resident DR.
HILL takes a seat at the table with them.
He opens up his notes.
LYNN What's wrong with Cole?
Beat.
DR. HILL The tests indicate he did not have a seizure.
DR. HILL In fact he's doing fine.
DR. HILL After some rest, he could go home tonight.
Lynn closes her eyes.
Lets out a tense breath.
Beat.
Malcolm eyes the doctor as he glances back to an academic-looking woman standing at the reception room door.
MALCOLM There's something else going on, Lynn.
Lynn opens her eyes and catches the doctor's expression.
LYNN What is it?
DR. HILL There are some scratches and bruises on your son that concern me.
MALCOLM Oh, man.
LYNN Those are from sports, from playing.
LYNN He's not the most coordinated kid, but I don't want him to stop trying, you know what I mean?
Doctor Hill gestures to the woman standing near the doorway.
DR. HILL Mrs. Sloan over there is our social worker at the hospital.
DR. HILL She's going to ask you some procedural questions.
LYNN You think I hurt my child?
LYNN You think I'm a bad mother?
DR. HILL At this point it's just procedure.
DR. HILL And you should probably calm down.
MALCOLM How do you expect her to react?
LYNN You want me to answer your questions?
DR. HILL I'm sorry if I was being vague -- yes, I do.
LYNN Who's going to answer mine, you dick.
Dr. Hill stares at her before closing up his files.
LYNN What happened to my child today?
Dr. Hill gets up.
LYNN Something was happening to him -- physically happening.
LYNN Something was very wrong.
Dr. Hill hands his files to MRS.
SLOAN and exits the reception room without looking back.
Everyone in the reception room stares at Lynn.
Mrs. Sloan walks up to the table and waits.
Lynn takes a second.
Wipes her eyes.
Gathers her considerable strength.
Beat.
LYNN How long will these questions take?
Cole lays rigid in the hospital bed.
Blankets bundled around him as if to shield him.
Cole's eyes fixed out the window.
Malcolm quietly enters through the half-opened door to the room.
Cole spots him.
Visibly relaxes.
MALCOLM I've decided we shouldn't schedule sessions anymore.
MALCOLM I'll just follow you around.
Cole smiles weakly as Malcolm takes a seat on a rolling metal chair.
Malcolm notices Cole's legs emerging from under the hospital gown.
Cole is wearing A MAN'S DRESS SOCK.
The baggy folds ride up all the way to his knees.
MALCOLM Your father ever tell you bedtime stories?
COLE Yes.
Malcolm looks at Cole.
Malcolm makes a decision.
He rolls in the chair across the room as he thinks.
Beat.
MALCOLM Once upon a time there was a prince, who was being driven around...
MALCOLM He drove around for a long, long time...
MALCOLM Driving and driving...
MALCOLM It was a long trip...
MALCOLM He fell asleep...
MALCOLM When he woke up, they were still driving...
MALCOLM The long drive went on--
COLE Dr. Crowe.
MALCOLM Yes.
COLE You haven't told bedtime stories before?
MALCOLM No.
COLE You have to add some twists and stuff.
COLE Maybe they run out of gas.
MALCOLM No gas...
MALCOLM Hey, that's good.
They sit in silence.
Malcolm works on a new plot in his head.
COLE Tell me a story about why you're sad.
Beat.
MALCOLM Do you think I'm sad?
Cole nods, "Yes."
MALCOLM What makes you think that?
COLE Your eyes told me.
Beat.
Malcolm's affected by his client.
MALCOLM I'm not supposed to talk about stuff like that.
Cole smiles softly.
Malcolm stares at the tired child sitting before him in the hospital bed.
Malcolm rolls his stool away from his client as he thinks.
Beat.
He slowly moves the rolling chair closer to Cole's bed.
MALCOLM ...Once upon a time there was this person named Malcolm.
MALCOLM He worked with children.
MALCOLM Loved it more than anything.
MALCOLM Then one night, he finds out he made a mistake with one of them.
MALCOLM Didn't help that one at all.
MALCOLM He thinks about that one a lot.
MALCOLM Can't forget.
MALCOLM Ever since then, things have been different.
MALCOLM He's become messed up.
MALCOLM Confused.
MALCOLM Angry.
MALCOLM Not the same person he used to be.
MALCOLM His wife doesn't like the person he's become.
MALCOLM They don't speak anymore.
MALCOLM They're like strangers.
Malcolm breaks from his thoughts and looks at Cole who watches him with unwavering attention.
Malcolm smiles.
MALCOLM And then one day this person Malcolm meets a wonderful boy who reminds him of that one.
MALCOLM Reminds him a lot of that one.
MALCOLM Malcolm decides to try to help this new boy.
MALCOLM He thinks maybe if he can help this boy, it would be like helping that one too.
Malcolm leans forward, whispers with emotional eyes.
MALCOLM I don't know how the story ends.
MALCOLM I hope it's a happy ending.
COLE Me too.
Cole looks at Malcolm's caring eyes.
Cole stares at Malcolm a long time.
COLE I want to tell you my secret now.
Malcolm blinks very slowly.
MALCOLM Okay.
Cole takes an eternal pause.
A silent tension engulfs them both.
COLE ...I see people.
Malcolm just gazes quietly.
COLE I see dead people...
COLE Some of them scare me.
Beat.
MALCOLM In your dreams?
Cole shakes his head, "No."
MALCOLM When you're awake?
Cole nods, "Yes."
MALCOLM Dead people, like in graves and coffins?
COLE No, walking around, like regular people...
COLE They can't see each other.
COLE Some of them don't know they're dead.
MALCOLM They don't know they're dead?
Beat.
COLE I see ghosts.
Malcolm becomes completely motionless.
Works to hide his shock.
He and Cole stare at each other a long time.
COLE They tell me stories...
COLE Things that happened to them...
COLE Things that happened to people they know.
Beat.
Malcolm's words are extra-controlled.
Revealing nothing.
MALCOLM How often do you see them?
COLE All the time.
COLE They're everywhere.
COLE You won't tell anyone my secret, right?
Beat.
MALCOLM ...No.
COLE Will you stay here till I fall asleep?
Malcolm nods, "Yes."
Cole pulls the covers up to his chin and turns to the window in the room.
Malcolm is very still and stares at Cole.
MALCOLM'S EYES -- slowly turn and survey the room.
They find nothing.
Malcolm returns to watching Cole.
Beat.
And then we see what he's staring at.
Through Cole's hospital room window we see the adjacent wing of the hospital building.
Rows of hospital room windows are visible.
In the windows are patients...
SOME OLD, SOME YOUNG...
SOME ARE DRESSED IN MODERN
Malcolm hails a cab.
He steps off the sidewalk lost in his thoughts.
Steam rises from a street vent.
HEADLIGHTS.
A CAR
Malcolm jerks out of the way.
His briefcase falls to the ground.
His tape recorder falls to the sidewalk.
Beat.
Malcolm reaches down and picks it up.
MALCOLM Cole...
MALCOLM His pathology is more severe than initially assessed.
MALCOLM He's suffering from visual hallucinations, paranoia -- Symptoms of some kind of school age Schizophrenia.
MALCOLM Medication and hospitalization may be required.
CLICK.
Malcolm's hand with the tape recorder drops to his side.
MALCOLM I'm not helping him.
Malcolm stares into the night.
He stands alone as thoughts crash like thunder in his head.
The STREETS TURN RED as Lynn drives home from the hospital in silence.
She glances down to her right.
Cole is curled up asleep on the passenger seat, back in his regular clothes, a tiny party hat clutched in his hand.
He looks like a four-year-old.
The sight of him exhausted and still, hits Lynn hard.
Lynn's face drowns in deep concern.
She lays a hand on Cole's head as she drives.
The front door opens, Lynn carries Cole in.
He's asleep on her shoulder.
She carries him down the hall to his BEDROOM.
Lynn lays Cole gently on his bed next to his German Shepherd Puppy.
Cole curls up with Sebastian.
Lynn watches the two youngsters sleep for a moment.
Cole is curled up asleep with a tiny party hat clutched in his hands.
He looks like a four-year-old.
Lynn has been carrying Cole's sweater from over her shoulder.
She pulls it off and begins to fold it.
Her attention is drawn to the sweater.
She fingers the fabric of the back.
IT'S RIPPED.
Her eyes move to Cole.
In the middle of the back of his T-shirt are THREE SMALL TEARS.
Lynn pushes the fabric open with her fingers and sees DEEP FINGERNAIL LIKE SCRATCHES on his skin.
Lynn looks around helplessly, fear creeping into her eyes.
Lynn emerges from Cole's room.
She turns OFF THE HALL LIGHTS as she moves into her room and closes the door.
WE HEAR LYNN PICK UP A PHONE AND DIAL.
Beat.
LYNN Hi, this is Lynn Sear, Cole's mother.
LYNN I wonder if we could talk about your son and his friends keeping their goddamn hands off my boy?
The thermostat on the wall reads seventy-eight degrees.
A few hours later.
The house seems threateningly still.
Too still.
An unnatural silence fills each room of the house.
The thermostat on the wall now reads, fifty-two degrees.
The door opens a crack.
Cole's tiny face peeks out.
Eyes scan the darkness.
The door opens a little bit more.
Cole's knees are pressed together.
His body dances a little.
Cole has to pee.
He moves cautiously into the hall.
Cole moves briskly to a door halfway down the corridor.
Opens it.
Cole turns on the LIGHT IN THE BATHROOM.
He checks behind the shower curtain, before he turns his back and pees into the toilet.
Cole instantly stops peeing.
His body becomes very still.
He slowly reaches for the toilet handle and flushes.
He closes his pants and turns.
He doesn't come out of the bathroom at first.
He just stands there and stares into the darkness of the hall.
Beat.
Cole finally steps out into the hallway.
His eyes catch a SLANT OF LIGHT now coming from the kitchen.
Cole hesitates before being drawn to the kitchen.
He moves down the hall and turns the corner -- coming to a stop in the doorway of the kitchen.
Cole stares at the back of a person cooking food on the stove.
Cole's fear slowly fades away.
Beat.
COLE Momma?
COLE Dream about daddy again?
The person turns.
It's not Lynn.
It's a strange woman.
The woman's face is demented.
A purple gash cuts across her forehead.
ALL THE CABINETS AND DRAWERS ARE OPEN BEHIND HER.
Cole's face turns the color of ash.
WOMAN What are you going to do?
Cole backs up to the doorway.
WOMAN You can't hurt me anymore!
The woman smiles menacingly as she thrusts her wrists forward...
They've been savagely cut.
Cole turns and runs down the hall.
Cole runs across his room.
He heads right for the homemade tent seated in the corner with the "DO NOT TOUCH" sign on it.
He scurries in.
His legs disappear as the bedsheets flap closed behind him.
The crazed woman stands at the end of the hall.
Doesn't come any closer.
Cole is curled up in the tent.
He lays still for a moment reaching over and FLICKING ON A FLASHLIGHT.
The red interior of the tent gets LIP UP.
It's a striking sight.
The bedsheet walls of the tent are lined with religious pictures taped to the walls.
Tiny statues of saints surround the interior perimeter.
We see the statue Cole stole from the church is in here...
This tent is a sanctuary made by an eight-year-old to hide in.
A sign to the side of the stage reads, "The third and fourth grade presents -- Rudyard Kipling's "The Jungle Book."
The parents APPLAUD AS TOMMY TAMMISIMO WALKS OUT ON STAGE in a villager's outfit.
TOMMY There once was a boy, very different than other boys.
TOMMY He lived in the jungle, and he could talk with the animals.
BACKSTAGE, Mr. Cunningham cues the rest of the children.
Some are villagers, others are dressed as trees and animals.
Cole comes on stage holding a painted cardboard monkey.
The arched halls of the private school are lined with posted drawings and test papers.
Cole and Malcolm walk down an empty hall.
COLE Did you think the play sucked big time?
MALCOLM What?
COLE Tommy Tammisimo acted in a cough syrup commercial.
COLE He thought everybody was self-conscious and unrealistic.
COLE He said the play sucked big time.
MALCOLM I know every child is special in their own way, but Tommy sounds like a punk.
MALCOLM I thought the play was excellent.
MALCOLM Better than Cats.
COLE Cats?
MALCOLM Never mind.
Beat.
They continue down the hall in silence.
Malcolm takes his time.
MALCOLM Cole, I was really interested in what you told me in the hospital, I'd like to hear more about it.
Malcolm stops at a set of doors at the end of the hall -- realizes Cole is no longer next to him.
Malcolm turns to find Cole frozen about ten feet back.
Malcolm walks to him.
He notices Cole's expression as he gets closer.
MALCOLM What's wrong?
Cole points to the doors.
MALCOLM Is something in there?
Cole doesn't say anything.
Beat.
It's a large shadowy GYM.
Climbing ropes hang from the wood beamed ceiling.
Cole is trembling slightly as he stands next to Malcolm.
MALCOLM What is it?
Malcolm follows the child's gaze to the ceiling of the gym.
MALCOLM I don't see.
Beat.
COLE Be real still.
Malcolm looks to Cole and then turns back to the ceiling.
Malcolm's body becomes very still.
Beat.
COLE Sometimes you feel it inside.
COLE Like you're falling down real fast, but you're really just standing still.
Malcolm looks at the wood beams and climbing ropes.
COLE You ever feel prickly things on the back of your neck?
Beat.
MALCOLM Yes?
COLE And the tiny hairs on your arm.
COLE Are they all standing up?
Malcolm glances at Cole.
Surprise on his face.
MALCOLM -- Yes.
Beat.
COLE When they get mad, it gets cold.
MALCOLM Them?
Malcolm looks at the empty stairwell and then back to Cole.
Nothing is said for a few moments.
MALCOLM I don't see anything.
MALCOLM Are you sure they're there?
MALCOLM Cole?
Malcolm turns back to Cole, he finds the child with tears in his eyes.
Cole looks at Malcolm desperately.
COLE Please make them leave.
Malcolm stares helplessly.
MALCOLM I'm working on it.
Malcolm gently leads Cole away from the stairs.
COLE'S P.O.V. -- The ropes and school banners dangling at the top of the stairs sways a little...
But so do THE THREE BODIES
It's a truly horrific sight.
A BLACK MAN in britches and no shirt, face beaten to a pulp, hangs in the center.
A WHITE WOMAN in a torn white frilly dress -- tears soaking her face, hangs to the right.
A small MIXED RACE CHILD in half pants, hangs to their left.
The family stares at Cole.
They follow Cole with their tortured eyes as he exits the stairwell.
Malcolm walks from the bus stop over the cobblestone streets in front of Head House Square.
The streets are quiet and dark.
Night time has fallen over the city.
He slowly comes to a stop in front of an old building.
He holds his arm up.
Uses his other hand to gently touch his hairs on his arm's surface.
Malcolm looks up slowly.
Looks around.
The dark shadows fill the corners of the historic building...
Malcolm stares into the darkness...
Beat.
MALCOLM ...Is anyone there?
A long moment as he waits.
The shadows seem to move, then becomes still.
Malcolm shakes off the moment.
He returns his hands to his pockets as he moves through the dark streets of Philadelphia to his home.
The doorway to Malcolm and Anna's bedroom is open.
STRAINED
MALCOLM Look, he's an eight-year-old child.
MALCOLM He's my only client.
MALCOLM If he invites me to his play, I'm not thinking about how late I get back...
MALCOLM I go.
MALCOLM I have to go.
MALCOLM You know that.
MALCOLM That's the only way I know how to work.
MALCOLM Vincent said I failed him.
Beat.
THE PORTABLE PHONE RINGS OUT IN THE HALL.
MALCOLM Please let it ring.
WE HEAR MOVEMENT.
Anna emerges from the bedroom.
Eyes raw.
She wipes her tears.
She picks up the phone and moves down the stairs.
Malcolm walks out into the hall.
Stops at the top of the stairs.
ANNA'S VOICE CAN BE HEARD SPEAKING ON THE PHONE from downstairs.
ANNA I can't talk now.
Malcolm doesn't hear anything as Anna listens to the person on the phone.
She smiles as she wipes her tears.
He starts for the basement door again.
ANNA I thought about you too.
Malcolm turns.
He stands frozen at the top of the stairs.
Anna's HUSHED WORDS RISING IN THE AIR LIKE A GUN BLAST.
Lynn adjusts the thermostat as she tries to keep herself warm.
LYNN I don't care what they say, this thing is definitely broken.
Lynn fiddles with the dials.
Cole is standing before the beat-up twelve inch kitchen T.V.
ON THE TELEVISION SCREEN is Tommy Tammisimo.
He stands in his pajamas in a doorway.
He coughs.
TOMMY Mommy, my throat hurts.
Cole watches as Tommy's T.V. mother and father give him a spoonful of medicine.
NARRATOR Pediaease Cough Suppressant...
NARRATOR gentle, fast, effective.
Cole watches Tommy running around in his T.V. background, the very next T.V. morning.
He's not sick anymore.
Tommy waves to the camera smiling and healthy.
The T.V. goes BLACK as Cole throws his shoe at the power button.
He moves to the dinner table where Lynn is seated.
Cole sits.
His hands go on the table.
He's wearing a pair of his father's extra large LEATHER GLOVES.
Cole's small hands don't even fill the palm area.
Cole has difficulty trying to pick up his milk glass with the gloves.
LYNN Take 'em off.
Cole removes the gloves from his hand and places them next to his plate.
LYNN I don't want them on my table.
Cole moves them to the floor.
Lynn is irritated, this is a sore point between them.
Lynn and Cole eat quietly.
Beat.
LYNN I saw what was in your bureau drawer when I was cleaning.
Cole looks up.
An anxious expression on his face.
Beat.
LYNN You got something you want to confess?
Cole just stares.
LYNN The bumble bee pendant.
LYNN Why do you keep taking it?
Cole looks down at his lap.
LYNN It was Grandma's.
LYNN It's not for playing.
LYNN What if it broke?
LYNN You know how sad I'd be.
COLE You'd cry.
COLE Cause you miss grandma so much.
LYNN That's right.
LYNN So why do you take it, sweetheart?
COLE Sometimes people think they lose things and they didn't really lose them.
COLE It just gets moved.
LYNN Did you move the bumble bee pendant?
Cole shakes his head, "No."
Lynn just stares.
LYNN You didn't take it before.
LYNN You didn't take it the time after that.
LYNN And now, you didn't take it again?
COLE Don't get mad.
LYNN So who moved it?
Cole doesn't answer.
LYNN There's only two of us.
LYNN Maybe someone came in our house -- took the bumble bee pendant out of my closet, and then laid it nicely in your drawer?
LYNN Is that what happened?
COLE Maybe.
Lynn just stares at Cole.
LYNN I'm so tired, Cole.
LYNN I'm tired in my body.
LYNN I'm tired in my mind.
LYNN I'm tired in my heart.
LYNN I need a little help here.
LYNN I don't know if you noticed -- but our little family isn't doing so good.
Lynn folds her napkin quietly.
LYNN I'm praying for us, but I must not be praying right.
LYNN It looks like we're just going to have to answer each other's prayers.
LYNN If we can't talk to each other -- we're not going to make it.
LYNN Now baby, tell me...
LYNN I won't be mad, honey...
LYNN Did you take the bumble bee pendant?
Beat.
Cole's eyes start to water up.
COLE No.
Lynn goes cold.
LYNN You've had enough roast beef.
LYNN You need to leave the table.
Cole just stares at his mother's expression.
LYNN Go!
Cole gets up -- never taking his eyes off his mother -- and leaves the room.
Cole enters the DARK HALLWAY.
He gets startled by the SOUND OF
Sebastian comes racing down the hall and scurries past Cole.
Cole watches his puppy dart into the living room and under a couch.
Cole slowly turns back and looks down the hall.
Cole stops breathing.
BOY Come on...
BOY I'll show you where my dad keeps his gun...
BOY Come on.
Cole is too terrified to move.
Lynn is kneeling on the kitchen floor trying to coax the puppy out of the broom closet.
COLE Momma.
Lynn turns -- surprised to hear her son's voice.
Lynn's eyes are red from crying.
She wipes them quickly with the back of her hand.
Mother and son look at each other.
Beat.
COLE If you're not very mad...
COLE Can I sleep in your room tonight?
Lynn fights back some tears.
LYNN Look at my face, Cole.
Cole does.
Lynn smiles at her son.
LYNN I'm not very mad.
Lynn hugs him.
Beat.
LYNN Baby...
LYNN Why are you shaking?
Cole doesn't answer.
LYNN Cole, what's wrong?
Cole just closes his eyes and holds his mom tight.
LYNN ...Please tell me.
Cole doesn't say a word.
LYNN Please.
We are in an antique store.
Filled floor to ceiling with furniture and knickknacks.
Anna stands with a YOUNG COUPLE.
All three lean over and peer into a glass cabinet.
An antique engagement ring sits on a velvet stand.
ANNA It's Edwardian.
ANNA Beautifully worked.
ANNA Entirely platinum with a mine cut diamond and an actual color Burmese Sapphire...
ANNA It's timeless.
YOUNG MAN You got anything a little plainer?
The young woman looks at her beau.
YOUNG WOMAN Plainer?
YOUNG WOMAN You want a plain ring to go with your plain fiance.
YOUNG WOMAN Is that how it is?
YOUNG MAN No, baby.
YOUNG MAN Don't get in a tizzy.
YOUNG MAN It's just...
YOUNG MAN you're so beautiful...
YOUNG MAN you're like a Burmese Sapphire all by yourself.
YOUNG MAN You don't need all that.
YOUNG WOMAN Uh-huh.
Anna smiles as she takes the ring out of the cabinet.
ANNA Why don't you two hold it?
She places it in their hands.
ANNA Do you feel longing?
YOUNG WOMAN Excuse me?
ANNA When I touch this piece I feel a longing.
ANNA I imagine the woman who owned this, loved a man deeply she couldn't be with.
The young woman looks at Anna with great intrigue.
YOUNG WOMAN Did he have wavy hair and broad shoulders?
The young man throws an odd glance at his fiance.
ANNA I don't know...
ANNA But maybe...
ANNA A lot of the pieces in this store give me feelings.
ANNA I think maybe when people own things and then they pass away -- a part of themselves gets printed on those things -- like fingerprints.
Beat.
The young man and the young woman gaze at Anna silently.
They look down at the ring.
They place their hands on it reverently, delicately -- like checking for a pulse.
Anna can't hold back her sweet smile.
Anna moves to the back desk where SEAN comes out.
He's carrying an antique bench in his arms.
He places it down and takes a much needed seat.
SEAN You don't need someone with a masters.
SEAN You need a wrestler guy whose neck is larger than his head.
ANNA I need a wrestler with a masters.
Anna fills out the paperwork for the ring.
SEAN What's this?
Anna looks over to find Sean standing at his desk where a BIRTHDAY PRESENT sits on his tabletop.
Sean looks at her.
SEAN From you?
Anna nods, "yes."
SEAN Is it wrestling tights?
Anna smiles as she moves to his desk.
Sean begins to tear off the wrapping paper like a kid at Christmas.
Anna laughs.
Sean holds up a weathered hardback copy of "THE GREAT GATSBY."
Beat.
ANNA It's a first edition.
SEAN Wow, this is too much.
SEAN It's perfect, Anna.
Sean puts down the book and hugs her.
He pulls back a little, still holding her.
They smile at each other.
Beat.
The moment goes on just that crucial fraction of a second too long.
Their smiles slowly melt away as they continue to hold each other.
Nothing happens for the longest time.
CRASH!
A SHATTERING DOOR SLAM ECHOES THROUGH THE STORE.
Anna and Jeffery pull apart.
They rush past the young man and the young woman to the front of the store.
They find the glass front door cracked in a spider web pattern.
They carefully push open the door and step out onto the sidewalk.
Look around.
No one in sight.
Anna stares down the empty street.
A concerned expression on her face.
Malcolm walks angrily down the sidewalk.
He stops as his hand goes to his side.
He winces with pain as he keeps walking.
Lynn and Cole emerge from the supermarket.
Cole rides inside the shopping cart tucked between bags of food.
Mother and son are quiet as they move towards their car.
Beat.
Lynn leans over, looks at the side of her son's pensive face.
She starts pushing the cart faster.
Cole wakes from his thoughts as his hair flutters in the wind.
He looks back.
Lynn is smiling as she pushes.
Cole turns and raises his hands in the air like he's on a roller coaster.
Beat.
They slow and come to a rest at the bumper of their car.
Lynn leans over -- sees the side of Cole's face smiling.
Lynn's face shows a little happiness for the first time.
A little hope enters her eyes as she starts to load the groceries into the car.
Cole and Lynn ride home with a back seat full of groceries.
Cole finishes off a cherry popsicle as he watches out the window.
Lynn looks over.
LYNN Let's rent a movie.
Cole bites off the last of the popsicle and glances at his mom.
LYNN Your pick.
Cole stares at his mom quietly.
LYNN It can even have Jean Claude Van Damme in it if you want.
Cole smiles at that.
He nods, "Yes" joyfully.
His smile fades away as he notices his mother fiddling with the HEATER controls.
Cole gazes out the front windshield as the car moves towards home.
Suddenly a piece of paper sticks to the windshield.
It's a page from a Playbill.
A 1941 Playbill.
It flies away revealing a woman in a flowing flowery dress from the 40's suddenly walks into the middle of the street as the pages of her Playbill swirl in the air.
COLE Momma, look out!
The woman in the flowery dress turns.
Her hand rests on her stomach.
WE SEE SHE IS PREGNANT.
Playbills stick to the windshield obstructing the view.
Lynn slams the brakes...
Too late.
The line of cars behind them suddenly hit their brakes and swerve to one side avoiding a mass collision.
After a few seconds, the entire intersection has come to a halt.
Cole who has shut his eyes...
slowly opens them.
He looks around fearfully.
His eyes move to the windshield.
No broken glass.
No blood.
And no woman.
Cole looks out through the pristine windshield onto the street where cars are stopped and staring all around them.
Cole slowly looks over to his mother.
He finds her staring at him in complete and utter disbelief.
Her hands clutch the wheel.
The whites of her knuckles showing her fear.
She has no idea why he screamed.
The den is very quiet.
Cole and Malcolm sit around the multi- colored table.
Malcolm leans back in his small plastic chair -- arms folded over his chest.
Cole sits slumped over the table -- eyes peering out over his arms.
They both look like shit.
COLE You don't wanna ask me questions today?
Malcolm nods, "No."
Beat.
COLE Can I ask you then?
MALCOLM Yes.
COLE What do you want more than anything?
MALCOLM I don't know.
COLE I told you what I want.
MALCOLM I don't know, Cole.
COLE Why don't you think about it for a while?
Malcolm doesn't respond.
Cole watches him.
Beat.
MALCOLM I know what I want.
MALCOLM My goal is to speak to my wife.
MALCOLM The way she and I used to speak.
MALCOLM Like there was no one in the world but us.
Beat.
COLE How are you going to do that?
Beat.
MALCOLM I can't be your doctor anymore.
MALCOLM I haven't given my family enough attention.
MALCOLM Bad things happen when you do that.
MALCOLM Do you understand?
The room falls into silence again.
Cole speaks extra soft.
COLE You want to go home?
Malcolm stares across at Cole.
MALCOLM I have to.
COLE When?
MALCOLM Soon.
MALCOLM One week.
Malcolm looks down at his eyes full with emotion.
MALCOLM I'm going to transfer you.
MALCOLM I know two psychologists that are exceptional--
COLE Don't fail me.
Malcolm looks up sharply.
MALCOLM --What?
COLE Don't give up.
COLE You're the only one who can help me.
COLE I know it.
Beat.
Malcolm tries to stay composed.
It doesn't work.
MALCOLM You want to know a secret?...
MALCOLM I was a paper champion.
MALCOLM Do you know what that means?
Cole shake his head, "No."
Tears fall down Malcolm's cheeks.
COLE Don't cry.
MALCOLM I means I wasn't what everyone thought I was...
MALCOLM I was a fake.
COLE You weren't a paper champion.
MALCOLM Someone else can help you.
MALCOLM Someone else can make you happy.
Cole is crying now.
Cole wipes his eyes with his sleeve.
They sit quietly and stare at each other.
Beat.
Cole whispers.
COLE Dr. Crowe?
MALCOLM Yes.
COLE You believe me, right?
A long pause.
COLE Dr. Crowe, you believe my secret, right?
They both just stare.
MALCOLM I don't know how to answer that.
Cole searches for the answer in Malcolm's eyes...
He finds it.
It's not the one he wanted.
Malcolm looks down.
COLE How can you help me if you don't believe me?
Cole reaches into his pocket.
Pulls out a PENNY.
Cole pushes it across the table.
Malcolm gazes at it, then looks up at Cole's pained eyes.
Beat.
COLE Some magic's real.
Malcolm sits stoically at his desk in his basement.
His eyes gaze at the dusty FRAMED CERTIFICATE FROM THE CITY OF PHILADELPHIA shoved between two packing boxes.
Malcolm leans his head back against the chair.
Stares into the shadows.
Drowns in his thoughts.
Beat.
THE CHAIR CREAKS as he slowly sits up again.
Malcolm's eyes scan the room and come to a stop on a box marked with the label...
A tape slides into the tape player seated on Malcolm's desk.
Malcolm hits play.
MALCOLM Sorry about that.
MALCOLM Hope I didn't leave you alone too long...
MALCOLM Wow, it's cold in here.
WE HEAR A CHAIR MOVE AS MALCOLM SITS DOWN.
And then SILENCE.
Beat.
MALCOLM Vincent...
MALCOLM Why are you crying?
MALCOLM Vincent?
VINCENT Yes?
MALCOLM What happened?
MALCOLM Did something upset you?
Beat.
VINCENT SNIFFLES.
VINCENT You won't believe.
MALCOLM I won't believe what?
Beat.
VINCENT I don't want to talk anymore.
VINCENT I want to go home, okay?
VINCENT I want to go home.
Beat.
MALCOLM Okay, Vincent, you can go home.
Malcolm just sits in the shadowy basement.
He doesn't move for a while.
Then he hits the rewind button.
Stops it.
Presses play.
MALCOLM --about that.
MALCOLM Hope I didn't leave you too long...
MALCOLM Wow, it's cold in here--
Malcolm hits the rewind button again.
Lets it rewind for a while.
Presses play.
MALCOLM --like needles either.
MALCOLM When I was a kid, I had this blood test down -- threw up chill cheese fries all over this male nurse.
SECRETARY Excuse me, Doctor Reed is on line two.
MALCOLM Vincent, I have to take this.
MALCOLM Give me a minute.
VINCENT Okay.
Nothing happens for a long time.
AND THEN WE HEAR A SUDDEN CHAIR
Malcolm's eyes are locked on the spool of audio tape as it spins in the player.
Malcolm's fingers move to the volume dial.
He turns it way up.
Malcolm leans closer to the tape player.
Closes his eyes and listens...
Beat.
MAN'S WHISPERING Familia...
MAN'S WHISPERING No dejen que esto me pase...
MAN'S WHISPERING Mi familia...
MAN'S WHISPERING Yo no quiero morir...
MAN'S WHISPERING Familia...
Malcolm's mouth opens in disbelief.
MALCOLM ...Jesus Christ.
Malcolm stands on a familiar sidewalk.
He stares into the bay window of Mr. Marschal's brownstone.
Inside the window we see Mr. Marschal seated with a group of older gentlemen his age.
They sit around a table eating sandwiches and talking.
Malcolm watches as Mr. Marschal tells a story to his friends.
WE CAN'T HEAR WHAT HE'S SAYING, but when he finishes everyone at the table laughs.
Mr. Marschal smiles.
Malcolm can't help smiling as well.
This is not the same man he saw before.
Life has returned to this house.
Beat.
Malcolm turns and moves down the street.
Each step faster than the next.
Malcolm moves to the front of the church down the center aisle.
His eyes scan the empty seats.
No one in sight in any direction.
Malcolm stands in the aisle a little out of breath.
He holds his hand to his side as he winces a bit.
Malcolm's eyes float up to the balcony where toy soldiers sit on the bannister.
Cole's head pops up.
MALCOLM Hello again.
He looks down and studies Malcolm.
COLE You been running around?
Malcolm nods, "Yes."
COLE It makes you feel better?
Malcolm nods, "Yes" again.
COLE I like to run around.
COLE It's good exercise.
COLE You want to ask me questions now?
Malcolm shakes his head, "No."
COLE You want to be a lance corporal in Company M, 3rd Battalion, 7th Marines?
COLE We're being dispatched to the Quang Nam province.
Cole holds up his plastic rifleman.
Malcolm's eyes show he understands now.
MALCOLM Maybe later.
Beat.
COLE Something happened, didn't it?
MALCOLM Yes, it did.
COLE Are you wigging out?
MALCOLM Yes, I am.
COLE We're not gonna start crying again, are we?
MALCOLM No, we're not.
COLE What happened?
Beat.
Malcolm glances around the empty church before looking back up to Cole.
MALCOLM These people...
MALCOLM People that died and are still hanging around.
MALCOLM Maybe they weren't ready to go.
Cole studies Malcolm's passionate face.
A new face.
COLE You really look better.
MALCOLM Maybe they wake up that morning thinking they have a thousand things to do and a thousand days left to do them in...
MALCOLM And then all of a sudden, it's all taken away.
MALCOLM No one asked them.
MALCOLM It's just gone...
COLE You have nice red in your cheeks now.
MALCOLM Do you know what 'Yo no quiero morir' is?
Cole shakes his head, "No."
MALCOLM It's Spanish.
MALCOLM It means...
MALCOLM 'I don't want to die.'
MALCOLM Not all the ghosts are scary, are they?
MALCOLM Like Mrs. Marschal?
COLE No.
MALCOLM What do those ghosts want when they talk to you?
MALCOLM Think real careful now, Cole...
Cole stops moving.
He looks over the balcony railing at Malcolm.
COLE Just help.
MALCOLM Yes!
MALCOLM I think that's right!...
MALCOLM I think they all want that.
MALCOLM Even the scary ones...
COLE You believe now?
Malcolm's stare is unwavering.
MALCOLM I believe both of you now.
MALCOLM And I think I might know how to make them go away.
COLE You do?
Malcolm nods "Yes."
MALCOLM I think they know you're one of those guys rare people can see them.
MALCOLM You need to help them.
MALCOLM Each one of them.
MALCOLM Everyone wants to be heard.
MALCOLM Everyone.
Cole takes a big sigh.
Fiddles with his riflemen.
COLE What if they don't want help?
COLE What if they're just angry and they want to hurt somebody?
MALCOLM I don't think that's the way it works, Cole.
Cole looks nervous.
COLE How do you know for sure?
Malcolm's eyes are drawn to Cole's arm.
Peeking out from under his shirt sleeve are a set of cuts.
Malcolm gazes at them.
MALCOLM I don't.
Cole and Malcolm stand silently in the center aisle of the back of the church.
Malcolm moves around the corner on his street.
His mind surges with thoughts.
And then he glances up.
His steps slow to a complete stop.
Further down the sidewalk, coming out of the front door of his house is SEAN.
Malcolm's face turns to stone.
He watches as Sean comes down the front stairs and starts across the street.
A sudden rage surges up.
Malcolm moves towards Sean fast.
Sean reaches his car and enters it.
He doesn't notice the figure closing in on him.
THE ENGINE STARTS.
Malcolm reaches the car a second late.
Sean pulls away into traffic almost hitting another car as he does.
Malcolm watches the car disappear down the next street.
Beat.
Malcolm turns and looks up at his home with unchecked anger and overwhelming pain erupting his eyes.
Malcolm stands in his foyer.
Anna is sitting on the stairs, phone in her hand.
She faces away from the front.
Malcolm's a ball of tension as he listens to Anna talk into the phone.
ANNA ...You just walked out.
ANNA You're probably on your way home.
ANNA I'm leaving this message...
ANNA I just didn't get to say what I meant...
ANNA I know you're confused.
ANNA It's just...
ANNA I'm not prepared to do this, Sean.
ANNA I don't want to be ashamed of that.
ANNA I don't want to have to make excuses for that.
ANNA And I wanted to tell you...
ANNA I bought your present wholesale from a friend.
ANNA I didn't even pay tax on it.
ANNA You don't need someone cheap like that.
ANNA By the way, it's a non-refundable item, it's scratched on the bottom.
ANNA Are you smiling?...
ANNA I hope you're smiling.
ANNA I'll see you at the store.
Beat.
A long silence.
Then WE HEAR ANNA GENTLY HANG UP.
Malcolm leans back against an old radiator.
Beat.
His eyes close as the SOUND OF HIS WIFE'S FOOTSTEPS RISES UP THE
The house is silent.
No movement.
Cole is in his pajamas asleep on the floor of the TENT.
Curled up next to him is Sebastian.
They sleep surrounded by statues and pictures.
Cole's eyes open as he hears HIS MOTHER'S DISTANT VOICE.
LYNN Cole...
LYNN Cole, what's happening...
Cole quickly gets up and rushes out of the tent.
His foot catches one of the chairs the tent is fastened to.
He stumbles out.
He doesn't realize one of the bedsheets comes loose.
It folds to the ground.
He doesn't stop as he moves through the shadowy hall and pushes open his mother's bedroom door.
Cole stands in the doorway to his mother's bedroom.
He looks over the room carefully.
Everything is still.
Lynn's room is sparse.
No paintings, no accessaries.
A bed without a frame sits in the corner.
A table with a sewing machine fills the other side of the room.
HIS MOTHER'S VOICE turns his attention back to the bed.
LYNN Cole, what's happening to you?
Cole looks down and finds his mother laying in her bed.
Her face contorted in deep sadness as she speaks in her sleep.
LYNN Is someone hurting you?...
LYNN I'll beat their asses.
Cole smiles at his mother as he moves to her side.
Touches her face with his tiny fingers.
COLE Momma, you sleep now.
His touch seems to have an effect.
Lynn becomes still in her sleep.
Cole watches her carefully.
Cole closes the door to his mother's bedroom shut.
He stands still in the hallway.
Lets out a heavy sigh...
Cole's brow furrows.
He breathes again.
This time intentionally.
Watches as his breath materializes in the suddenly ice cold air.
Every muscle in Cole's eight-year-old body becomes rigid.
He takes a second before moving through the inky darkness of the hall.
Cole hurries to fix his tent.
He ties the collapsed bedsheet in a knot on the edge of the chair.
He checks it carefully before entering the tent.
When Cole turns around, he stops breathing.
AN EIGHT-YEAR-OLD GIRL VOMITS ON HERSELF IN HIS TENT.
She finishes and looks up at Cole with drawn eyes.
GIRL I'm feeling much better now.
The girl reaches out with her withered and emaciated hands -- tiny tubes hang from her wrists.
She scratches Cole as he tumbles back terrified out of the tent.
The whole tent collapses --
Cole runs hard out of his bedroom and down the hall to the living room.
He gets down to the ground and slides under the wooden- legged couch.
Sebastian is already huddled in fear under the couch.
Cole presses as far back as he can and waits.
COLE'S P.O.V. -- is of the living room floor.
Chair legs.
Coffee table base.
Rugs...
Everything is still.
Cole holds his breath.
He waits.
Beat.
Nothing happens.
He takes his first short breaths and watches the room for any sign of movement.
A few minutes later.
Cole is now standing in his doorway.
He stares at the hunched figure covered by the collapsed tent.
BEAT.
Cole makes a decision.
He looks like he is going to cry -- fights it back.
He walks towards it.
Reaches down and slowly pulls the sheet off the figure.
The girl vomits one more time before looking up at Cole.
GIRL I'm feeling much better.
Cole and the little girl stare silently at each other.
Cole holds her stare with trembling eyes.
He opens his mouth -- it takes a while before the words come out.
COLE Do you want to tell me something?
A downtown Septa public bus.
Malcolm and Cole are among the spattering of passengers.
They're both wearing suits.
Cole leans his head against the glass of the scratched window.
Cole's large eyes drink in the passing scenery.
COLE'S P.O.V. -- A dark, abandoned building stretches for an entire block on one side.
A MAN IN A GREY, FULL-BODIED UNIFORM
SHACKLED MAN My name's not Sullivan!
Cole jerks back from the window.
The bus quietly drives past THE OLD PRISON BUILDING.
Cole stares down at his lap and tries not to look up anymore.
Beat.
COLE She came a long way to visit me, didn't she?
MALCOLM I guess she did.
Cole falls into deep thoughts as he stares down at his dress shoes.
Malcolm slips back into silence.
The city bus slithers through the old Philadelphia streets working its way downtown.
A modest home sits on a corner.
Its small lawn, groomed carefully.
Rows of parked cars spill out from the driveway onto the streets.
People in suits and dark dresses move somberly in and out of the front door of the home.
Cole and Malcolm join the visitors as they walk slowly towards the doors.
A frail, little girl about four years of age sits in a dark dress on the swings in front of the house.
Visitors say hello to her as they pass.
She doesn't say anything back.
MALCOLM Her little sister?
Cole nods, "Yes."
Malcolm and Cole watch her for a moment before following others into the modest corner home.
The home is packed with people.
The gathering of mourners is standing room only.
The AIR IS FILLED WITH DOZENS OF HUSHED
VISITOR #1 ...can you imagine being a child in a bed for two years?
We move to.
VISITOR #2 ...I think it was six.
We move to.
VISITOR #3 ...Six separate doctors?
We move to.
VISITOR #4 ...the little one's falling ill now...
We move to.
VISITOR #5 ...God help them...
A FAMILY PORTRAIT HANGS NEAR THE FRONT DOOR.
Two girls, one bigger, one smaller sit on the ground in front of their mother and father.
Their smiling faces welcome the mourners.
Malcolm and Cole are standing at the bottom of a staircase.
Waiting.
The front door opens as another group arrives.
Malcolm nods to Cole as the foyer fills up.
The two of them quietly disappear upstairs.
The narrow hall is lined with boxes of medical supplies.
I.V.
stands, sterile needles and pads are in the process of being taken away.
The boxes are piled outside a closed bedroom door.
Cole stares at the shut door like he doesn't want to go in.
His eyes move to the large, colorful map of the world that dons the hallway wall.
He gazes at the many countries and continents.
Beat.
COLE I wish I were somewhere else.
MALCOLM Where will you go, where no one has died?
Cole stares at the map and then turns to Malcolm.
COLE Don't go home, okay?
MALCOLM I definitely won't.
Cole turns and stares quietly at the door.
He waits a long time before reaching for the doorknob.
Cole closes the door behind him.
He turns and gazes at the girl's bedroom.
There's a hospital bed near the window.
The walls are covered with get-well cards and drawings from family, friends, and school children.
Her shelves are filled with puppets.
All shapes and sizes of puppets.
Next to the shelf is a puppet stage and a camcorder on a mini tripod sitting next to it.
Cole walks to the shelf and picks up a FINGER PUPPET DANCER.
He places it in his pocket.
On the girl's desk, is a large collection of video cassettes.
The labels read, "Puppet Show Christmas 96," "Puppet Show Birthday party," "Puppet Show class trip"...
Cole reads the labels carefully before moving towards the closets.
He passes the bed.
Cole jerks back startled.
He watches as the girl's hand slips back under the bed.
Cole stays very still.
Waits.
Nothing happens.
He slowly bends down.
His hands touch the floor.
He tilts his head and looks under the bed.
The emaciated little girl who came to his tent lays curled on the floor.
Her bulging eyes glare at Cole.
She moves suddenly.
Thrusts a jewelry box forward.
It slides across the wooden floor and stops just before Cole.
Cole and the sickly girl stare at each other.
Neither of them say a word.
The room is thick with mourners.
Most are gathered around the GIRL'S MOTHER, a young woman in her late twenties.
As she moves through the room to the kitchen, she receives the many cards, hugs, and flowers that are offered as condolence.
Mrs. Collins leaves the living room.
Malcolm watches breathlessly from the doorway as Cole moves through the many adults across the room.
The girl's father, MR.
COLLINS, a thin man in his late twenties, is seated on the reading chair next to a T.V. His face is granite.
No one in the room dares to talk to him.
He stares statue-like at an abstract point in the room.
COLE Mister?
The man doesn't react.
Some of the guests look oddly at the little boy standing before the man.
COLE Excuse me, Mister.
Beat.
The man slowly turns and looks down at the boy standing next to him.
Cole is very shaky.
Malcolm watches everything anxiously.
Cole stares at Mr. Collins.
COLE Are you Kyra's daddy?
The man's face begins to crumble.
Beat.
He nods, "yes" softly.
Cole holds out the jewelry box.
It trembles with his hands.
The father just stares at it.
Beat.
COLE It's for you...
COLE She wanted to tell you something.
The father becomes very still.
His eyes fill with a storm of confusion and pain.
After the longest time, the father reaches and gently takes the box out of Cole's small hands.
Cole begins to back away...
The father gazes at Cole as he melts into the crowd.
Cole reaches Malcolm and the two then slip out of the house.
The father looks down in a daze.
He goes to open the jewelry box.
His movements are slow and strained.
He lifts the latch and open the box.
Mr. Collins stares at an unlabeled video cassette.
People in the room start to turn as the T.V. comes on.
Mr.
Collins is seated now.
Her father's face forms the most heartbreaking of smiles as he watches the performance.
The entire room has stopped what they were doing.
WE HEAR FOOTSTEPS COMING UP THE STAIRS.
The puppets go limp.
The entire stage gets lifted up.
We see it carried away by Kyra.
We can view the whole bedroom now.
The camera is seated on her desk in the corner.
Kyra climbs in bed and pretends to be sleeping when the door opens.
It's Mrs. Collins.
She carries in a tray of soup and a sandwich.
The crowd watches in riveted silence.
The father never takes his eyes off of the screen.
The image of the mother prepares the meal.
She uncovers the fruit and the soup.
Places a straw into the drink.
And then it happens.
The image of the mother walks to a closet.
Opens it.
An assortment of household cleaners and sponges are kept inside.
She pulls out a bottle of floor cleaner.
Reads the label for the ingredients.
Walks back to the food tray, where she unscrews the cap on the floor cleaner.
The mother pours some into the cap.
Checks it.
MRS. COLLINS That's too much.
The mother pours some into the bottle.
The remainder goes into the child's soup.
She replaces the cap and puts the bottle back in the closet.
The image of the mother turns to the bed carrying the tray.
She places the food on a metallic rolling table and swings it over the bed.
MRS. COLLINS Kyra, time for lunch.
Kyra pretends to wake from a deep sleep.
KYRA I'm feeling much better now.
The image of the mother smiles.
MRS. COLLINGS I'm glad, honey.
MRS. COLLINGS Time for your food.
KYRA Can I go outside, if I eat this?
MRS. COLLINS We'll see.
MRS. COLLINS You know how you get sick in the afternoon.
Kyra picks up the spoon and takes a sip.
Her face crinkles at the taste.
She looks up at her mother.
MRS. COLLINS Don't say it tastes funny.
MRS. COLLINS You know I don't like to hear that.
Kyra slowly brings the spoon to her mouth and swallows another spoonful.
The father SHUTS OFF THE TELEVISION with his trembling hands.
He presses his hands to his eyes like they're burning.
The ROOM IS UTTERLY SILENT.
Mrs. Collins is seated at the dining room surrounded by friends and family.
She fixes one of the many bouquets of flowers on the table.
It takes her a beat before she feels the stare.
She looks up.
Standing in the doorway to the dining room is Mr. Collins.
A group of ashen faced guests stand in the distance behind him.
Husband and wife's eyes meet.
Mrs. Collins smiles softly.
Mr. Collins' eyes tremble with tears.
MR. COLLINS You were keeping her sick...
The whole world stops.
The mother's face registers confusion at first.
Then slow realization.
Her eyes glace at the many faces around her.
She looks back at her husband.
His glare is painful.
Rage filling every cell of his body.
Tears falling faster down his cheeks.
Mrs. Collins turns her attention back to the flowers.
She concentrates with all her strength.
Beat.
Her hands begin to shake.
MRS. COLLINS I took care of her...
Her words are met with ice cold stares.
The first tears stream down her face.
The pretty flowers of consolation in her hand tumble to the floor.
Cole sits on the swings next to Kyra's four-year-old sister.
She doesn't look up.
Malcolm waits in the driveway.
Watches them from a distance.
Cole reaches into his pocket and pulls out the little FINGER PUPPET.
He holds it out.
COLE You liked it, she said.
The four-year-old stares at the finger puppet, then quietly takes it in her small hands.
The two children don't say anything for a while.
Malcolm glances to the house, where all movements in and out of the home has ceased.
Cole turns to the four-year-old.
COLE She watched out for you.
The little girl finally looks up.
She has the saddest eyes.
FOUR YEAR OLD Kyra's not coming back.
Beat.
COLE Not anymore.
The little girl stares down at the finger puppet.
Cole lightly places a hand on her shoulder.
Nothing else is said.
Nothing else is done.
Malcolm looks across the two children on the swings.
One mourning.
One consoling.
Malcolm takes it in, overwhelmed.
Stanley Cunningham moves between two curtains and comes to a prop room door in the back.
He puts an ear to the door, listens and then knocks.
After a second, he enters.
Mr. Cunningham finds Cole sitting in a poor villager costume as a FEMALE TEACHER kneels next to him and makes final adjustments.
Cole and the woman glance at Mr. Cunningham.
MR. CUNNINGHAM They're calling for the stable boy.
Mr. Cunningham looks around the room and then directly at Cole.
MR. CUNNINGHAM Who were you talking to?
The Female Teacher looks to Cole and nods.
FEMALE TEACHER Poor Stanley.
She stands up.
The entire left side of her face has been burnt horribly.
Grotesquely disfigured.
FEMALE TEACHER My favorite student.
Cole puts on his tattered hat.
COLE Thanks for giving me this part, Mr.
COLE Cunningham.
Mr. Cunningham smiles.
MR. CUNNINGHAM You're welcome, Cole.
They share a look before walking out of the prop room and entering the hall.
We see them walking away.
MR. CUNNINGHAM You know when I was in school, there was a terrible fire in this section of the theater.
MR. CUNNINGHAM They rebuilt the whole thing.
Beat.
COLE I know.
It begins to rain.
Malcolm pulls his jacket over his head as he scurries up the stairs of the school.
Malcolm stands and catches his breath in the corridor of St.
Anthony's Academy.
A teacher rushes in the hall with an armload of costumes.
MALCOLM Has the play started yet?
The teacher hurries past Malcolm and down the hall without saying a word.
MALCOLM Is that a yes?
The teacher scurries around a corner.
Malcolm watches her curiously.
Malcolm moves quickly to a set of double doors and opens them.
He steps into the DARKNESS OF THE AUDITORIUM.
The play is in full swing...
Cole and a large group of costumed children are on stage.
Cole holds a broom and wears a worn-down costume.
He stands to the side -- hidden by others.
A boy in a shiny-armored costume walks to the center of the stage where a large cardboard stone is seated.
A sparkling HANDLE sticks out of the top.
The armored boy tries to lift it.
It won't budge.
Bobby, the chubby boy from the party, is dressed in a magician's costume.
He is Merlin.
He steps forward.
MERLIN Only he who is pure of heart can take the sword from the stone.
Merlin looks to the group on stage.
Looks right at Cole.
MERLIN Let the boy try.
The group of villagers on the stage LAUGH AND MOCK THE SUGGESTION.
Tommy Tammisimo is dressed in a mismatched costume -- he hops around, clearly embarrassed.
TOMMY But he's the stable boy.
TOMMY He cleans after the horses.
MERLIN Silence village idiot!
MERLIN Let the boy step forward.
Tommy turns a deep shade of red and hobbles off the stage.
Merlin looks to Cole.
He smiles a true friend's smile.
MERLIN Arthur...
Cole hesitates.
Not because he's acting.
He really hesitates.
It takes him a moment before he steps forward.
Cole steps up to the stone.
He places his hand around the handle.
Begins to pull.
The sword starts to come out.
The villagers GASP.
Cole raises the shiny sword out of the stone and high above his head.
Merlin and everyone on stage bows.
A SILENCE FILLS THE
Malcolm watches his client, standing unafraid in the spot light for the first time.
The villagers rise and rush to Cole.
They scoop him up and carry him around the stage in celebration.
Cole chuckles and then starts laughing as the group of eight-year-olds try unsuccessfully to keep him up.
They slowly sag and then collapse.
All the students are laughing as they try to untangle themselves.
Malcolm watches with utter joy as Cole becomes indistinguishable among of a group of twenty children giggling and enjoying themselves on stage.
The rain comes down a little stronger now on the stained glass window.
Malcolm sits on the stairs in the lobby.
Cole walks back and forth in front of him.
Cole still holds the sword from the play.
COLE How come we're so quiet?
Malcolm shrugs his shoulders.
MALCOLM I think we said everything we needed to say.
MALCOLM Maybe it's time to say things to someone else?
MALCOLM Someone close to you?
COLE Maybe.
Cole keeps moving.
Beat.
COLE I'm not going to see you anymore, am I?
Malcolm doesn't respond for a while.
He shakes his head, "No."
Beat.
MALCOLM You were great in the play, Cole.
COLE Really?
MALCOLM And you know what else?
COLE What?
MALCOLM Tommy Tammisimo sucked big time.
Cole smiles huge.
Beat.
Cole's sword drags on the tile as he continues to circle around the hall.
We get the idea he doesn't want to be still.
COLE ...Maybe we can pretend we're going to see each other tomorrow?
Cole glances at Malcolm.
COLE Just for pretend.
Beat.
Malcolm exhales very slowly as he gets up.
MALCOLM Okay, Cole, I'm going to go now...
MALCOLM I'll see you tomorrow.
Cole watches as Malcolm walks down the stairs to the entrance.
Cole stops moving.
COLE See you tomorrow.
Malcolm's face shows his losing battle against his emotions.
He doesn't turn to look back.
A rain-soaked bridge.
A two-lane road merges to one lane around a severe car accident.
A rear-ended car has jumped the sidewalk and hit the guard rail of the bridge.
The driver is helped out by police.
He's shaken but okay.
Police flares guide the cars as they crawl by.
Lynn and Cole are standing still in bumper-to-bumper traffic.
Lynn leans her chin on the steering wheel.
She tries to stare through the layer of water on the glass.
She hits the windshield wipers.
LYNN I hope nobody got hurt.
Beat.
Lynn glances over to Cole who sits in his seat silently.
LYNN You're very quiet.
LYNN You're mad I missed the play, aren't you?
Cole shakes his head, "No."
LYNN I have two jobs, baby.
LYNN You know how important they are for us.
Beat.
LYNN I'd give anything to have been there.
COLE I'm ready to communicate with you now.
Beat.
LYNN Communicate?
COLE Tell you my secrets.
The way he says the words gives Lynn a chill.
LYNN What is it?
Cole takes a long time.
COLE You know that accident up there?
LYNN Yeah.
COLE Someone got hurt.
LYNN They did?
COLE A lady.
COLE She died.
LYNN Oh my God.
Lynn leans over the steering wheel.
She wipes the windshield with her palm to see better.
LYNN You can see her?
COLE Yes.
Lynn gazes out the windshield at the line of red tail lights.
Beat.
LYNN Where is she?
COLE Standing next to my window.
Lynn looks over slowly.
She doesn't see anything outside his window.
She eyes Cole.
LYNN Cole, you're scaring me.
COLE They scare me too sometimes.
LYNN They?
COLE Dead people.
LYNN Dead people?
COLE Ghosts.
Beat.
LYNN You see ghosts, Cole?
COLE They want me to do things for them.
LYNN They talk to you?
Cole nods, "Yes."
LYNN They tell you to do things?
Cole nods "Yes" again.
Lynn becomes upset.
She nods with grave understanding.
Cole watches her.
COLE What are you thinking, Momma?
LYNN ...I don't know.
COLE You think I'm a freak?
Lynn's eyes moves to Cole.
LYNN Look at my face.
Cole gazes at her intense expression.
LYNN I would never think that about you ...
LYNN ever...
LYNN Got it?
COLE Got it.
BEAT.
Cole smiles a tiny smile.
Lynn glances down.
LYNN Just let me think for a second.
She drowns in her thoughts.
Beat.
COLE Grandma says hi.
Lynn looks up sharply.
COLE She says she's sorry for taking the bumble bee pendant.
COLE She just likes it a lot.
LYNN What?
COLE Grandma comes to visit me sometimes.
Lynn becomes still.
Her face is unreadable.
When she speaks, her words are extremely controlled.
LYNN Cole, that's very wrong.
LYNN Grandma's gone.
LYNN You know that.
COLE I know.
Beat.
COLE She wanted me to tell you--
LYNN Cole, please stop.
COLE She wanted me to tell you, she saw you dance.
Lynn's eyes lock on Cole's.
COLE She said when you were little, you and her had a fight right before your dance recital.
COLE You thought she didn't come to see you dance.
COLE She did.
Lynn brings her hands to her mouth.
COLE She hid in the back so you wouldn't see...
COLE She said you were like an angel.
Lynn begins to cry.
COLE She said, you came to her where they buried her.
COLE Asked her a question...
COLE She said the answer is "Everyday."
Lynn covers her face with her hands.
The tears roll out through her fingers.
COLE What did you ask?
Beat.
Lynn looks at her son.
She barely gets the words out.
LYNN Do I make her proud?
Cole moves closer to Lynn.
She cradles him in her arms.
Mother and son hold each other tight.
Malcolm walks quietly down the sidewalk towards his home.
Malcolm enters the living room and smiles at what he sees.
Anna is asleep in a chair.
She's curled up in a ball.
In a way, she looks like a little girl.
Their WEDDING VIDEO PLAYS SOFTLY ON THE TELEVISION.
Malcolm watches himself and Anna cutting their wedding cake.
THE
Malcolm turns from the television and takes a seat next to Anna.
He gazes upon his wife softly.
MALCOLM Anna, I've been so lost.
MALCOLM I need my best friend.
Silence.
Malcolm gazes for a beat before looking down.
ANNA I miss you.
Malcolm's eyes move back up.
He looks at his sleeping wife.
Malcolm can't believe it.
MALCOLM I miss you.
Beat.
Her lips move again.
Eyes never open.
ANNA Why, Malcolm?
MALCOLM What, Anna?
MALCOLM What did I do?
MALCOLM What's made you so sad?
Beat.
ANNA Why did you leave me?
MALCOLM I didn't leave you.
Beat.
She becomes silent.
Anna falls back into deep sleep, her arm slides down.
SOMETHING SHINY FALLS OUT AND ROLLS ON THE
Malcolm's eyes watch as it comes to a stop...
Beat.
He gazes curiously at a GOLD WEDDING BAND laying on the wood floor.
Confusion washes over his face.
He looks to Anna's hand...
An identical gold wedding ring sits on her finger.
Beat.
Malcolm looks down at his own hand...
HIS WEDDING RING IS
Malcolm is completely lost.
He takes a couple steps back.
Looks around in confusion...
His eyes come to rest on the door to his basement office.
He looks in disbelief at the set of DEAD BOLT LOCKS on the door.
Malcolm doesn't know what the hell's going on...
His eyes are drawn to the dining table...
Only ONE PLACE SETTING is out on the tabletop.
His eyes search again -- they finally lock on the WEDDING VIDEO PLAYING.
Malcolm watches images of himself on the screen...
His eyes fill with a storm of emotions...
Malcolm looks to Anna's face and becomes very still.
Beat.
MALCOLM No...
Anna rushes across the room to a crumpled Malcolm laying on the floor.
Malcolm's hands are clutched at his side.
Anna pries his hands away to reveal the tiniest tear in his shirt.
Anna's eyes catch something dark -- moving...
A POOL OF BLOOD IS FORMING UNDER MALCOLM.
She slowly turns him over on his side...
A horrific sight...
An enormous exit wound on his lower back pours out blood uncontrollably.
Malcolm's jaw is locked open.
His breaths are long and strained.
Malcolm's open jaw releases a long strained breath and then becomes silent.
Anna tries to cover the wound with her hands desperately.
Anna just sleeps.
Malcolm staggers back.
His breathing erratic.
He takes a seat across from her.
He looks at his wife and suddenly becomes very still.
Anna's still curled up asleep, but tears are falling from her shut eyes.
Beat.
MALCOLM Don't cry.
Anna doesn't move, but her tears seem to fall a little faster.
MALCOLM I think I have to go.
Malcolm's mind is racing.
MALCOLM I just needed to do a couple of things.
MALCOLM And I needed to tell you something.
ANNA Tell me.
Beat.
MALCOLM You were never second...
MALCOLM Ever.
Malcolm gazes at his wife.
Tears fall from both their eyes.
MALCOLM You sleep now, Anna.
MALCOLM Everything will be different in the morning.
Anna lays still.
ANNA Goodnight, Malcolm.
MALCOLM Goodnight, sweetheart.
The room falls into silence.
Malcolm sits still across from his wife.
He drinks her in with his eyes.
Malcolm leans back in the chair.
Slowly closes his eyes.
They close shut.
WE PULL BACK to reveal Anna alone in the living room.
MALCOLM ...I think I've had too much to drink.
Malcolm smiles as he takes a sip.
The guests chuckle as they watch.
Beat.
MALCOLM I just have to say, this day today has been one very special day...
MALCOLM I wish we all could stay and play.
The crowd erupts in LAUGHTER.
MALCOLM What?
Malcolm looks around at everyone's smiling faces.
Beat.
Malcolm takes his time.
He looks just past the camera.
MALCOLM Anna, I never thought I'd feel the things I'm feeling.
MALCOLM I never thought I'd be able to stand up in front of my friends and family and tell them what's inside me...
MALCOLM Today I can...
Malcolm's eyes fill with water.
MALCOLM Anna Crowe...
MALCOLM I am in love.
MALCOLM In love I am.
</div>
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
