A FEW GOOD MEN
Written by
Aaron Sorkin
Revised Third Draft
July 15, 1991
-- in the middle of the night, in the middle of nowhere.
Small beams of light coming from lamps attached to the tower cut through the ground mist.
We HEAR all the unidentifiable sounds of night in the woods.
We also HEAR, very, very faintly, a slow, deliberate drum cadence.
And as this starts, we begin to MOVE SLOWLY UP THE TOWER, more becomes visible now:...
the sandbags on the ground piled ten-high...
the steel, fire escape-type stairway wrapping around the structure and leading to the lookout post, and finally...
THE LOOKOUT POST, maybe forty feet off the ground.
Standing the post is the silhouette of A MARINE.
He's holding a rifle and staring straight out.
The drum cadence has been building slightly.
A WIDER SHOT OF THE FENCELINE.
And we see by the moonlight that the tall wire-mesh fence winds its way far, far into the distance.
The drum cadence continues, and we
We HEAR two pairs of footsteps and then
THE BARRACKS CORRIDOR where we see that the footsteps belong to DAWSON and DOWNEY, two young marines who we'll get to know later.
They stop when they get to a certain door.
The drum cadence is still growing.
DAWSON puts his hand on the doorknob and turns it slowly.
He opens's the door and they walk into
WILLY SANTIAGO, a young, very slight marine, lies asleep in his bunk.
DAWSON kneels down by the bed, puts his hand on SANTIAGO'S shoulder and shakes him gently.
SANTIAGO opens his yes, looks at DAWSON, and for a moment there's nothing wrong --
-- and then SANTIAGO's eyes fill with terror.
He lunges out of the bed -- but forget about it.
In one flash DAWSON and DOWNEY grab him out of bed, and before the scream can come out, DOWNEY's shoved a piece of cloth into SANTIAGO's mouth.
Everything that happens next occurs with speed, precision and professionalism.
-- A strip of duct tape is pulled, ripped, and slapped onto his mouth and eyes --
-- A length of rope is wrapped around his hands and feet.
DOWNEY You're lucky it's us, Willy.
-- An arm grabs him tightly around the neck, not choking him, just holding his head still --
-- The drum cadence has built to a crescendo.
We HEAR four sharp blasts from a whistle and we
EXT. THE WASHINGTON NAVY YARD - DAY and the drum cadence we've been hearing has turned into Semper Fidelis and it's coming from THE U.S. MARINE CORPS BAND, a sight to behold in their red and gold uniforms and polished silver and brass.
The BAND is performing on the huge and lush parade grounds before a crowd made up mostly of TOURISTS and DAY-CAMPERS.
As the TITLES ROLL, we watch the BAND do their thing from various angles.
Incredible precision is the name of the game.
Each polished black shoe hitting the ground as if they were all attached by a rod.
Each drumstick raised to the same fraction of a centimeter before striking.
A RIFLE DRILL TEAM that can't possibly be human.
Flags, banners, the works.
HIGH ANGLE of the entire band an we end credits.
It's an important building, a main building.
A few SAILORS enter and exit and
A WOMAN as she walks across the courtyard toward the brick building.
The WOMAN is JOANNE GALLOWAY, a navy lawyer in her early 30's.
She's bright, attractive, impulsive, and has a tendency to speak quickly.
If she had any friends, they'd call her JO.
As she walks, she mutters to herself ...
JO I'm requesting...
JO I'm...
JO Captain, I'd like to request that I be the attorney assigned to rep -- I'd like to request that it be myself who is assigned to represent --
JO "That it be myself who is assigned to represent"?
JO ...Good, Jo, that's confidence inspiring.
We follow JO, still muttering, as she walks into the brick building which bears the seal of the
As JO enters.
CAPTAIN WEST and two other officers, GIBBS and LAWRENCE, sit around a conference table.
GIBBS Jo, come on in.
JO Thank you, sir.
GIBBS Captain West, this is Lt.
GIBBS Commander Galloway.
GIBBS Jo, you know Mike Lawrence.
JO Yes sir.
JO Captain, I appreciate your seeing me on such short notice.
WEST I understand there was some trouble over the weekend down in Cuba.
JO Yes sir...
JO This past Friday evening.
JO Two marines, Corporal Harold Dawson and Private Louden Downey, entered the barracks room of a PFC William Santiago and assaulted him.
JO Santiago died at the base hospital approximately an hour later.
JO The NIS agent who took their statements maintains they were trying to prevent Santiago from naming them in a fenceline shooting incident.
JO They're scheduled to have a hearing down in Cuba at 4:00 this afternoon.
LAWRENCE What's the problem?
JO Dawson and Downey are both recruiting poster marines and Santiago was known to be a screw-up.
JO I was thinking that it sounded an awful lot like a code red.
Jo lets this sink in a moment.
WEST Christ.
JO I'd like them moved up to Washington and assigned counsel.
JO Someone who can really look into this.
JO Someone who possesses not only the legal skill, but a familiarity with the inner workings of the military.
JO In short, Captain, I'd like to suggest that...
JO I be the one who, that it be me who is assigned to represent them.
JO Myself.
Jo looks around the room for a response.
WEST Joanne, why don't you get yourself a cup of coffee.
JO Thank you, sir, I'm fine.
WEST Joanne, I'd like you to leave the room so we can talk about you behind your back.
JO Certainly, sir.
JO gets up and walks out.
WEST I thought this Code Red shit wasn't going on anymore.
LAWRENCE With the marines at GITMO?
LAWRENCE Who the hell knows what goes on down there.
WEST Well lets find out before the rest of the world does, this thing could get messy.
WEST What about this woman?
LAWRENCE Jo's been working a desk at internal affairs for what, almost a year now.
WEST And before that?
GIBBS She disposed of three cases in two years.
WEST Three cases in two years?
WEST Who was she handling, the Rosenbergs?
GIBBS She's not cut out for litigation.
LAWRENCE She's a hall of an investigator, Jerry --
GIBBS In Internal Affairs, sure.
GIBBS She can crawl up a lawyer's ass with the best of 'em, but when it comes to trial work --
WEST I know.
WEST All passion, no street smarts.
WEST Bring her back in.
LAWRENCE goes to the door and motions for JO to come back in.
WEST Commander, we're gonna move the defendants up here in the morning.
JO Thank you, sir.
WEST And I'll have Division assign them counsel...
JO But...
JO not me.
WEST From what I understand from your colleagues, you're much too valuable in your present assignment to be wasted on what I'm sure will boil down to a five minute plea bargain and a week's worth of paper work.
JO Sir --
WEST Don't worry about it.
WEST I promise you, division'll assign the right man for the job.
His name is LIEUTENANT JUNIOR GRADE DANIEL ALLISTAIR KAFFEE, and it's almost impossible not to like him.
At the moment he's hitting fungoes to about a dozen LAWYERS who are spread out on the softball field on a corner of the bass.
The '27 Yankees they're not, but they could probably hold their own against a group of, say, Airforce dentists.
KAFFEE's in his late 20's, 15 months out of Harvard Law School, and a brilliant legal mind waiting for a courageous spirit to drive it.
He is, at this point in his life, passionate about nothing...
except maybe softball.
KAFFEE Alright, let's get two!
He smacks one to the SECOND BASE.
The ball bounces right between his legs.
SECOND BASE Sorry!
KAFFEE Nothing to be sorry about, Sherby.
KAFFEE Just look the ball into your glove.
He smacks one out to the same place.
It bounces off the heel of SHERBY's glove and into center field.
SECOND BASE (SHERBY) Sorry!
KAFFEE You gotta trust me, Sherby.
KAFFEE You keep your eyes open, your chances of catching the ball increase by a factor of ten.
SPRADLING, a young naval officer, sweaty and out of breath, walks up behind the backstop.
SPRADLING Kaffee!
KAFFEE Let's try it again.
SPRADLING Kaffee!!
KAFFEE Dave.
KAFFEE You seem upset and distraught.
SPRADLING We were supposed to meet in your office 15 minutes ago to talk about the McDermott case.
SPRADLING You're stalling on this thing.
SPRADLING Now we got this done and I mean now, or no kidding, Kaffee, I'll hang your boy from a fuckin' yardarm.
KAFFEE A yardarm?
KAFFEE Sherby, does the Navy still hang people from yardarms?
SHERBY I don't think so, Danny.
KAFFEE Dave, Sherby doesn't think the Navy hangs people from yardarms anymore.
KAFFEE Let's go, let's get two!
He goes back to hitting fungoes.
SPRADLING I'm gonna charge him with possession and being under the influence while on duty.
SPRADLING Plead guilty and I'll recommend 30 days in the brig with loss of rank and pay.
KAFFEE It was oregano, Dave, it was ten dollars worth of oregano.
SPRADLING Yeah, well your client thought it was marijuana.
KAFFEE My client's a moron, that's not against the law.
Swapp!
The THIRD BASEMAN takes one in the face.
KAFFEE Ow.
KAFFEE That had to hurt.
KAFFEE Way to keep your head in the play, Lester.
KAFFEE Walk it off!
SPRADLING I've got people to answer to just like you, I'm gonna charge him.
KAFFEE With what, possession of a condiment?
SPRADLING Kaffee --
KAFFEE Dave, I've tried to help you out of this, but if you ask for tall time, I'm gonna file a motion to dismiss.
SPRADLING You won't got it.
KAFFEE I will get it.
KAFFEE And if the MTD is denied, I'll file a motion in liminee seeking to obtain evidentiary ruling in advance, and after that I'm gonna file against pre-trial confinement, and you're gonna spend an entire summer going blind on paperwork because a Signalman Second Class bought and smoked a dime bag of oregano.
SPRADLING B Misdemeanor, 20 days in the brig.
KAFFEE C Misdemeanor, 15 days restricted duty.
SPRADLING I don't know why I'm agreeing to this.
KAFFEE 'Cause you have wisdom beyond your years.
KAFFEE Dave, can you play third base?
About 16 NAVY AND MARINE LAWYERS (several of whom are women) are taking their seats around a large conference table.
A PARALEGAL is handing out folders and some photocopied papers to the LAWYERS.
We might notice that one of the lawyers is Lieutenant Junior Grade SAM WEINBERG.
Sam's serious and studious looking.
If he weren't in uniform, you wouldn't guess that he was a naval officer.
CAPTAIN WHITAKER walks in.
WHITAKER 'Morning.
LAWYERS 'Morning Captain Whitaker.
WHITAKER Sam, how's the baby?
SAM I think she's ready to say her first word any day now.
WHITAKER How can you tell?
SAM She just looks like she has something to say.
KAFFEE walks in.
KAFFEE Excuse me, sorry I'm late.
WHITAKER I'm sure you don't have a good excuse, so I won't force you to come up with a bad one.
KAFFEE Thank you, Isaac, that's nice of you.
WHITAKER Sit-down, this first one's for you.
He hands KAFFEE some files.
WHITAKER You're moving up in the world, Danny, you've been requested by Division.
"Oooh"'s and "Ahhh"'S from the other LAWYERS.
(Subtle Note: Kaffee doesn't want to move up in the world.)
KAFFEE Requested to do what?
WHITAKER hands him a file.
WHITAKER Guantanamo Bay, Cuba.
WHITAKER A marine corporal named Dawson illegally fires a round from his weapon over the fenceline and into Cuban territory.
KAFFEE What's a fenceline?
WHITAKER Sam?
SAM A big wall separating the good guys from the bad guys.
KAFFEE Teachers pet.
WHITAKER PFC William Santiago threatens to rat on Dawson to the Naval investigative Service.
WHITAKER Dawson and another member of his squad, PFC Louden Downey, they go into Santiago's room, tie him up, and stuff a rag down his throat.
WHITAKER An hour later, Santiago's dead.
WHITAKER Attending physician says the rag was treated with some kind of toxin.
KAFFEE They poisoned the rag?
WHITAKER Not according to them.
KAFFEE What do they say?
WHITAKER Not much.
WHITAKER They're being flown up here tomorrow and on Thursday at 0600 you'll catch a transport down to Cuba for the day to find out what you can.
WHITAKER Meantime, go across the yard and see Lt.
WHITAKER Commander Joanne Galloway.
WHITAKER She's the one who had 'em brought up here.
WHITAKER She'll fill you in on whatever she has.
WHITAKER Any questions?
KAFFEE The flight to Cuba, was that 0600 in the morning, sir?
WHITAKER It seems important to Division that this one be handled by the book, so I'm assigning co-counsel.
WHITAKER Any volunteers?
SAM No.
WHITAKER Sam.
SAM I have a stack of paper on my desk --
WHITAKER Work with Kaffee on this.
SAM Doing what?
SAM Kaffee'll finish this up in four days.
WHITAKER Do various...
WHITAKER administrative...
WHITAKER you know...
WHITAKER things.
WHITAKER Back-up.
WHITAKER Whatever.
SAM In other words I have no responsibilities whatsoever.
WHITAKER Right.
SAM My kinda case.
JO sits behind her desk.
KAFFEE and SAM stand in the doorway.
KAFFEE knocks politely.
JO looks up.
KAFFEE Hi.
KAFFEE I'm Daniel Kaffee.
KAFFEE I was told to meet with --
KAFFEE -- Commander Galloway.
JO is staring at him.
KAFFEE doesn't know why.
KAFFEE About a briefing.
JO is finding this hard to believe.
JO You're the attorney that Division assigned?
KAFFEE I'm lead counsel.
KAFFEE This is Sam Weinberg.
SAM I have no responsibilities here whatsoever.
JO's deeply puzzled.
JO Come in, please, have a seat...
KAFFEE and SAM come into the office and sit.
JO Lieutenant, how long have you been in the Navy?
KAFFEE Going on nine months now.
JO And how long have you been out of law school?
KAFFEE A little over a year.
JO I see.
KAFFEE Have I done something wrong?
JO No.
JO It's just that when I petitioned Division to have counsel assigned, I was hoping I'd be taken seriously.
KAFFEE and SAM exchange a look.
KAFFEE No offense taken, if you were wondering.
SAM Commander, Lt.
SAM Kaffee's generally considered the best litigator in our office.
SAM He's successfully plea bargained 44 cases in nine months.
KAFFEE One more, and I got a set of steak knives.
JO Have you ever been in a courtroom?
KAFFEE I once had my drivers license suspended.
SAM Danny --
KAFFEE Commander, from what I understand, if this thing goes to court, they won't need a lawyer, they'll need a priest.
JO No.
JO They'll need a lawyer.
During this, she'll hand KAFFEE a series of files, which KAFFEE will pass To SAM without even glancing at them.
JO Dawson's family has been contacted.
JO Downey's closest living relative is Ginny Miller, his aunt on his mother's side, she hasn't been Contacted yet.
None of this really means anything to KAFFEE.
JO Would you like me to take care of that?
KAFFEE Sure, if you feel like it.
JO takes another beat to size this guy up.
JO One of the people you'll be speaking to down there is the barracks C.O., Colonel Nathan Jessep, I assume you've heard of him.
KAFFEE Who hasn't?
SAM He's been in the papers lately.
SAM He's expected to be appointed Director of Operations for the National Security Counsel.
Passing KAFFEE another file --
JO These are letters that Santiago wrote in his 8 months at GITMO --
SAM Guantanamo Bay.
KAFFEE I know that one.
JO He wrote to his recruiter, the fleet commander, HQ, Atlantic, even his senator.
JO He wanted a transfer.
JO Nobody was listening.
JO You with me?
KAFFEE Yes.
JO This last letter to the Naval investigative Service --
She hands it to KAFFEE who hands it to Sam --
JO -- where he offers information about Corporal Dawson's fenceline shooting in exchange for a transfer, was just a last ditch effort.
KAFFEE Right.
KAFFEE Is that all?
JO Lieutenant, this letter makes it look like your client had a motive to kill Santiago.
KAFFEE Gotcha.
KAFFEE And Santiago is...
KAFFEE who?
JO The victim.
KAFFEE Write that down.
KAFFEE Am I correct in assuming that these letters don't paint a flattering picture of marine corps life in Guantanamo Bay?
JO Yes, among other --
KAFFEE And am I further right in assuming that a protracted investigation of this incident might cause some embarrassment for the security counsel guy.
JO Colonel Jessep, yes, but --
KAFFEE Twelve years.
JO I'm sorry?
KAFFEE Twelve years.
KAFFEE I can get it knocked down to Involuntary Manslaughter.
KAFFEE Twelve years.
JO You haven't talked to a witness, you haven't looked at a piece of paper.
KAFFEE Pretty impressive, huh?
JO You're gonna have to go deeper than just --
KAFFEE Commander, do you have some sort of jurisdiction here that I should know about?
JO My job is to make sure you do your job.
JO I'm special counsel for Internal Affairs, so my jurisdiction's pretty much in your face.
JO Read the letters.
JO You're not under any obligation, but I'd appreciate a report when you get back from Cuba.
KAFFEE Sure.
KAFFEE gets up without waiting for JO to say --
JO You're dismissed.
KAFFEE Sorry, I always forget that.
KAFFEE's gone.
SAM's standing in the doorway.
SAM He's a little preoccupied.
SAM The team's playing Bethesda Medical next week.
JO Tell your friend not to get cute down there.
JO The marines in Guantanimo are fanatical.
SAM About what?
And in VOICE OVER we HEAR --
SANTIAGO (V.O.) Dear Sir,
JO About being marines.
And while we HEAR the letter read in V.O., what we're seeing is this: SANTIAGO's life in Guantanimo Bay over the last 8 months.
He had a rough time of it.
-- SANTIAGO running along at the rear of a group of MARINES.
It's been over seven miles and he's matted with sweat.
A SERGEANT runs up along side, grabs his back, and pushes him to keep up with the group.
SANTIAGO falls, struggles to get back up and keep running, and
-- SANTIAGO doing push-ups alone in the rain.
He's being supervised by a SERGEANT who sees to it that his face hits the mud every time down and
-- SANTIAGO sitting alone in the mess hall, not a friend within four seats of him and
-- SANTIAGO being chewed out by a Lieutenant in front of his squad and
-- SANTIAGO running with the squad of MARINES again, this time down a rocky hill.
It's hot as hell and it looks like he's gonna pass out.
He stumbles, and the SERGEANT picks him up and pushes him down the hill.
He rolls about 30 feet before he stops.
Over this, we HEAR
SANTIAGO (V.O.) "...My name is PFC William T.
SANTIAGO (V.O.) Santiago.
SANTIAGO (V.O.) I am a marine stationed at Marine Barracks, Rifle Security Company Windward, Second Platoon Delta.
SANTIAGO (V.O.) I am writing to inform you of my problems with my unit here in Cuba and to ask for your help.
SANTIAGO (V.O.) I've fallen out on runs before for several reasons such as feeling dizzy or nauseated, but on May 18th, I'd fallen back about 20 or 30 yards going down a rocky, unstable hill.
SANTIAGO (V.O.) My sergeant grabbed me and pushed me down the hill.
SANTIAGO (V.O.) Then I saw all black and the last thing I remember is hitting the deck.
SANTIAGO (V.O.) I was brought to the hospital where I was told I just had heat exhaustion and was explained to by the doctor that my body has trouble with the hot sun and I hyperventilate.
SANTIAGO (V.O.) I ask you to help me.
SANTIAGO (V.O.) Please sir.
SANTIAGO (V.O.) I just need to be transferred out of RSC.
SANTIAGO (V.O.) Sincerely.
SANTIAGO (V.O.) PFC William T.
SANTIAGO (V.O.) Santiago.
SANTIAGO (V.O.) U.S.
SANTIAGO (V.O.) Marine Corps."
At this point, with SANTIAGO's letter still in V.O., we
It's the last paragraph of the letter we've been hearing, and at the moment, we can't see the hands that are holding it.
SANTIAGO (V.O.) "P.S.
SANTIAGO (V.O.) In exchange for my transfer off the base, I'm willing to provide you with information about an illegal fenceline shooting that occurred the night of August 2nd."
And as these last words are spoken, we PULL BACK TO REVEAL COLONEL NATHAN R. JESSEP, who drops the letter he's been reading on his desk, where it joins a stack of other letters just like it.
JESSEP's a born leader, considered in many circles to be one of the real fair-haired boys of the Corps.
He's smart as a whip with a sense of humor to match.
As soon as he drops the letter, he says
JESSEP Who the fuck is PFC William T.
JESSEP Santiago.
He's talking to his two senior officers.
CAPTAIN MARKINSON is in his late 40's.
He's a career marine and a nice guy in a world where nice guys may not finish last, but they sure as shit don't finish first.
Lt.
JONATHAN JAMES KENDRICK is 26, from Georgia, and an Academy graduate.
If you asked him he'd tell you that the gates to heaven are guarded by the U.S. Marine Corps.
KENDRICK Sir, Santiago is a member of Second Platoon, Delta.
JESSEP Yeah, well, apparently he's not very happy down here at Shangri-La, cause he's written letters to everyone but Santa Claus asking for a transfer.
JESSEP And now he's telling tales about a fenceline shooting.
He tosses the letter over to MARKINSON.
MARKINSON is looking it over.
JESSEP is waiting for a response.
JESSEP Matthew?
MARKINSON I'm appalled, sir.
JESSEP You're appalled?
JESSEP This kid broke the Chain of Command and he ratted on a man of his unit, to say nothing of the fact that he's a U.S. Marine and it would appear that he can't run from here to there without collapsing from heat exhaustion.
JESSEP What the fuck's going on over at Windward, Matthew?
MARKINSON Colonel, I think perhaps it would be better to hold this discussion in private.
KENDRICK That won't be necessary, Colonel, I'll handle the situation.
MARKINSON The same way you handled the Curtis Barnes incident?
MARKINSON You're doing something wrong, Lieutenant this --
KENDRICK My methods of leadership are --
MARKINSON Don't interrupt me, I'm still your superior officer.
JESSEP And I'm yours, Matthew.
The room calms down for a moment.
JESSEP I want to know what we're gonna do about this.
MARKINSON I think Santiago should be transferred off the base.
MARKINSON Right away.
JESSEP He's that bad, huh?
MARKINSON Not only that, but word of this letter's bound to get out.
MARKINSON The kid's gonna get his ass kicked.
JESSEP Transfer Santiago.
JESSEP Yes I suppose you're right.
JESSEP I suppose that's the thing to do.
JESSEP Wait.
JESSEP Wait.
JESSEP I've got a better idea.
JESSEP Let's transfer the whole squad off the base.
JESSEP Let's -- on second thought -- Windward.
JESSEP The whole Windward division, let's transfer 'em off the base.
JESSEP Jon, go on out there and get those boys down off the fence, they're packing their bags.
JESSEP Tom!
The ORDERLY cones in from the outer office.
ORDERLY Sir!
JESSEP Got me the President on the phone, we're surrendering our position in Cuba.
ORDERLY Yes sir!
JESSEP Wait a minute, Tom.
The ORDERLY stops.
JESSEP Don't call the President just yet.
JESSEP Maybe we should consider this for a second.
JESSEP Maybe -- and I'm just spit balling here -- but maybe we as officers have a responsibility to train Santiago.
JESSEP Maybe we as officers have a responsibility to this country to see that the men and women charged with its security are trained professionals.
JESSEP Yes.
JESSEP I'm certain I once read that somewhere.
JESSEP And now I'm thinking that your suggestion of transferring Santiago, while expeditious, and certainly painless, might not be in a manner of speaking, the American way.
JESSEP Santiago stays where he is.
JESSEP We're gonna train the lad.
JESSEP You're in charge, Jon.
JESSEP Santiago doesn't make 4.1 on his next fitness report, I'm gonna blame you.
JESSEP Then I'm gonna kill you.
KENDRICK Yes sir.
MARKINSON I think that's a mistake, Colonel.
JESSEP Matthew, I believe I will have that word in private with you now.
JESSEP Jon, that's all.
JESSEP Why don't you and I have lunch at the "O" club, we'll talk about the training of young William.
KENDRICK Yes sir, I'd be delighted to hear any suggestions you have.
JESSEP Dismissed.
KENDRICK is gone.
JESSEP Matthew, sit, please.
MARKINSON sits.
JESSEP What do you think of Kendrick?
MARKINSON I don't know that --
JESSEP I think he's kind of a weasel, myself.
JESSEP But he's an awfully good officer, and in the end we see eye to eye on the best way to run a marine corps unit.
JESSEP We're in the business of saving lives, Matthew.
JESSEP That's a responsibility we have to take pretty seriously.
JESSEP And I believe that taking a marine who's not yet up to the job and packing him off to another assignment, puts lives in danger.
MARKINSON starts to stand --
JESSEP Matthew, siddown.
JESSEP We go back a while.
JESSEP We went to the Academy together, we were commissioned together, we did our tours in Vietnam together.
JESSEP But I've been promoted up through the chain with greater speed and success than you have.
JESSEP Now if that's a source of tension or embarrassment for you, well, I don't give a shit.
JESSEP We're in the business of saving lives, Captain Markinson.
JESSEP Don't ever question my orders in front of another officer.
JESSEP grabs his hat and walks out, leaving MARKINSON sitting all alone, and we
It's maybe a little hazier today than it was yesterday.
An M.P.
is waving a procession of three Military Police sedans and a fourth unmarked car through the gate.
The cars drive through and we
Another red-brick building.
A few M.P.Is stand out front as the cars pull up.
As soon as they come to a stop, all the doors swing open and various uniformed and non-uniformed officers hop out and move to the unmarked sedan where they escort DAWSON and DOWNEY, in handcuffs, out of the car.
HAROLD DAWSON's a handsome, young, black corporal.
Intense, controlled, and utterly professional.
LOUDEN DOWNEY's a 19-year-old kid off an Iowa farm.
He's happiest when someone is telling him exactly what to do.
DAWSON's his hero.
The two prisoners stand still for a moment.
They might as we'll be in Oz.
DOWNEY Hal?
DAWSON doesn't say anything.
DOWNEY Is this Washington, D.C.?
M.P. Alright, let's move.
EXT.  SOFTBALL FIELD - DAY and KAFFEE's at it again.
KAFFEE Alright, let's get tough out there!
JO walks up from behind the backstop.
JO Excuse me.
KAFFEE You want to suit up?
KAFFEE We need all the help we can get.
JO No, thank you, I can't throw and catch things.
KAFFEE That's okay, neither can they.
JO I wanted to talk to you about Corporal Dawson and Private Downey.
KAFFEE Say again?
JO Dawson and Downey.
KAFFEE Those names sound like they should mean something to me, but I'm just not --
JO Dawson!
JO Downey!
JO Your clients!
KAFFEE The Cuba thing!
KAFFEE Yes!
KAFFEE Dawson and Downey.
KAFFEE Right.
KAFFEE I've done something wrong again, haven't I?
JO I was wondering why two guys have been in a jail cell since this morning while their lawyer is outside hitting a ball.
KAFFEE We need the practice.
JO That wasn't funny.
KAFFEE It was a little funny.
JO Lieutenant, would you feel very insulted if I recommended to your supervisor that he assign different counsel?
KAFFEE Why?
JO I don't think you're fit to handle this defense.
KAFFEE You don't even know me.
KAFFEE Ordinarily it takes someone hours to discover I'm not fit to handle a defense.
Jo just stares.
KAFFEE Oh come on, that was damn funny.
Jo moves close to KAFFEE to say this with a degree of confidentiality.
JO I do know you.
JO Daniel AlliStair Kaffee, born June 8th, 1964 at Boston Mercy Hospital.
JO Your father's Lionel Kaffee, former Navy Judge Advocate and Attorney General, of the United States, died 1985.
JO You went to Harvard Law on a Navy scholarship, probably because that's what your father wanted you to do, and now you're just treading water for the three years you've gotta serve in the JAG Corps, just kinda layin' low til you can get out and get a real job.
JO And if that's the situation, that's fine, I won't tell anyone.
JO But my feeling is that if this case is handled in the same fast-food, slick-ass, Persian Bazaar manner with which you seem to handle everything else, something's gonna get missed.
JO And I wouldn't be doing my job if I allowed Dawson and Downey to spend any more time in prison than absolutely necessary, because their attorney had pre- determined the path of least resistance.
KAFFEE can't help but be impressed by that speech.
KAFFEE Wow.
KAFFEE I'm sexually aroused, Commander.
JO I don't think your clients murdered anybody.
KAFFEE What are you basing this on?
JO There was no intent.
KAFFEE The doctor's report says that Santiago died of asphyxiation brought on by acute lactic acidosis, and that the nature of the acidosis strongly suggests poisoning.
KAFFEE Now, I don't know what any of that means, but it sounds pretty bad.
JO Santiago died at one a.m.
JO At three the doctor was unable to determine the cause of death, but two hours later he said it was poison.
KAFFEE Oh, now I see what you're saying.
KAFFEE It had to be Professor Plum in the library with the candlestick.
JO I'm gonna speak to your supervisor.
KAFFEE Okay.
KAFFEE You go straight up Pennsylvania Avenue.
KAFFEE It's a big white house with pillars in front.
JO Thank you.
KAFFEE I don't think you'll have much luck, though.
KAFFEE I was assigned by Division, remember?
KAFFEE Somebody over there thinks I'm a good lawyer.
KAFFEE So while I appreciate your interest and admire your enthusiasm, I think I can pretty much handle things myself.
JO Do you know what a code red is?
KAFFEE doesn't, but he doesn't say anything.
JO What a pity.
And an M.P. is leading KAFFEE and SAM down to DAWSON and DOWNEY's cell.
M.P. Officer on deck, ten-hut.
DAWSON and DOWNEY come to attention.
Through the following, the M.P. will unlock the call door and let the lawyers in.
DAWSON Sir, Lance Corporal Harold W. Dawson, sir.
DAWSON Rifle Security Company Windward, Second Platoon, Delta.
KAFFEE Someone hasn't been working and playing well with others, Harold.
DAWSON Sir, yes sir!
DOWNEY Sir, PFC Louden Downey.
KAFFEE I'm Daniel Kaffee, this is Sam Weinerg, you can sitdown.
DAWSON and DOWNEY aren't too comfortable sitting in the presence of officers, but they do as they're told.
KAFFEE's pulled out some documents, SAM's sitting on one of the cots taking notes.
KAFFEE Is this your signature?
DAWSON Yes sir.
KAFFEE You don't have to call me sir.
KAFFEE Is this your signature?
DOWNEY Sir, yes sir.
KAFFEE And you certainly don't have to do it twice in one sentence.
KAFFEE Harold, what's a Code Red?
DAWSON Sir, a Code Red is a disciplinary engagement.
KAFFEE What does that mean, exactly?
DAWSON Sir, a marine falls out of line, it's up to the men in his unit to get him back on track.
KAFFEE What's a garden variety Code Red?
DAWSON Sir?
KAFFEE Harold, you say sir and I turn around and look for my father.
KAFFEE Danny, Daniel, Kaffee.
KAFFEE Garden variety; typical.
KAFFEE What's a basic Code Red?
DAWSON Sir, a marine has refused to bathe on a regular basis.
DAWSON The men in his squad would give him a G.I. shower.
KAFFEE What's that?
DAWSON Scrub brushes, brillo pads, steel wool...
SAM Beautiful.
KAFFEE Was the attack on Santiago a Code Red?
DAWSON Yes sir.
KAFFEE Do you ever talk?
DAWSON Sir, Private Downey will answer any direct questions you ask him.
KAFFEE Swell.
KAFFEE Private Downey, the rag you stuffed in Santiago's mouth, was there poison on it?
DOWNEY No sir.
KAFFEE Silver polish, turpentine, anti- freeze...
DOWNEY No sir.
DOWNEY We were gonna shave his head, sir.
KAFFEE When all of a sudden...?
DOWNEY We saw blood drippinq out of his mouth.
DOWNEY Then we pulled the tape off, and there was blood all down his face, sir.
DOWNEY That's when Corporal Dawson called the ambulance.
KAFFEE tries not to make too big a deal out of this last piece of news.
KAFFEE Did anyone see you call the ambulance?
DAWSON No sir.
KAFFEE Were you there when the ambulance got there?
DAWSON Yes sir, that's when we were taken under arrest.
KAFFEE kinda strolls to the corner of the cell to think for a moment.
SAM On the night of August 2nd, did you fire a shot across the fenceline into Cuba?
DAWSON Yes sir.
SAM Why?
DAWSON My mirror engaged, sir.
KAFFEE His mirror engaged?
SAM For each American sentry post there's a Cuban counterpart.
SAM They're called mirrors.
SAM The corporal's claiming that his mirror was about to fire at him.
KAFFEE Santiago's letter to the NIS said you fired illegally.
KAFFEE He's saying that the guy, the mirror, he never made a move.
DAWSON says nothing.
KAFFEE Oh, Harold?
SAM is staring at DAWSON.
KAFFEE You see what I'm getting at?
KAFFEE If Santiago didn't have anything on you, then why did you give him a Code Red?
DAWSON Because he broke the chain of command, sir.
KAFFEE He what?
DAWSON He went outside his unit, sir.
DAWSON If he had a problem, he should've spoken to me, sir.
DAWSON Then his Sergeant, then Company Commander, then --
KAFFEE Yeah, yeah, alright.
KAFFEE Harold, did you assault Santiago with the intent of killing him?
DAWSON No sir.
KAFFEE What was your intent?
DAWSON To train him, sir.
KAFFEE Train him to do what?
DAWSON Train him to think of his unit before himself.
DAWSON To respect the code.
SAM What's the code?
DAWSON Unit Corps God Country.
SAM I beg your pardon?
DAWSON Unit Corps God Country, sir.
KAFFEE The Goverrment of the United States wants to charge you two with murder.
KAFFEE You want me to go to the prosecutor with unit, corps, god, country?
DAWSON stares at KAFFEE.
DAWSON That's our code, sir.
KAFFEE takes a long moment.
He picks up his briefcase and he and SAM move to the door.
KAFFEE We'll be back.
KAFFEE You guys need anything?
KAFFEE Books paper, cigarettes, a ham sandwich?
DAWSON Sir.
DAWSON No thank you.
DAWSON Sir.
KAFFEE smiles at DAWSON.
KAFFEE Harold, I think there's a concept you better start warming up to.
DAWSON Sir?
KAFFEE I'm the only friend you've got.
And as KAFFEE and SAM walk out the open cell door, DAWSON and DOWNEY come to attention and snap a salute.
They hold the salute until KAFFEE and SAM are well out of sight, and we
He's packing up stuff into his briefcase at the end of the work day.
Lt.
JACK ROSS, a marine lawyer maybe two years older than Kaffee, opens the door and walks in..
ROSS Dan Kaffee.
KAFFEE Sailin' Jack Ross.
ROSS Welcome to the big time.
KAFFEE You think so?
ROSS I hope for Dawson and Downey's sake you practice law better than you play softball.
KAFFEE Unfortunately for Dawson and Downey, I don't do anything better than I play softball.
KAFFEE What are we lookin' at?
ROSS They plead guilty to manslaughter, I'll drop the conspiracy and the conduct unbecoming.
ROSS 20 years, they'll be home in half that time.
KAFFEE I want twelve.
ROSS Can't do it.
KAFFEE They called the ambulance, Jack.
ROSS I don't care if they called the Avon Lady, they killed a marine.
KAFFEE The rag was tested for poison.
KAFFEE The autopsy, lab report, even the initial E.R.
KAFFEE and C.O.D. reports.
KAFFEE They all say the same thing: Maybe, maybe not.
ROSS The Chief of Internal Medicine at the Guantanamo Bay Naval hospital says he's sure.
KAFFEE What do you know about Code Reds?
ROSS smiles and shakes his head.
ROSS Oh man.
He closes the office door.
ROSS Are we off the record?
KAFFEE You tell me.
ROSS I'm gonna give you the twelve years, but before you go getting yourself into trouble tomorrow, you should know this: The platoon commander Lt.
ROSS Jonathan Kendrick, had a meeting with the men.
ROSS And he specifically told them not to touch Santiago.
KAFFEE holds for a moment.
Dawson and Downey neglected to mention this...
He packs up his briefcase and cleats.
KAFFEE I'll talk to you when I get back.
ROSS Hey, we got a little four-on-four going tomorrow night.
ROSS When does your plane get in?
It's dusk and people on the base are going home from work.
We can see the flag being lowered in the background.
KAFFEE's walking toward his car.
JO intercepts him and starts walking along with him.
JO Hi there.
KAFFEE Any luck getting me replaced?
JO Is there anyone in this command that you don't either drink or play softball with?
KAFFEE Commander --
JO Listen, I came to make peace.
JO We started off on the wrong foot.
JO What do you say?
JO Friends?
KAFFEE Look, I don't --
JO By the way, I brought Downey some comic books he was asking for.
JO The kid, Kaffee, I swear, he doesn't know where he is, he doesn't even know why he's been arrested.
KAFFEE Commander --
JO You can call me Joanne.
KAFFEE Joanne --
JO or Jo.
KAFFEE Jo?
JO Yes.
KAFFEE Jo, if you ever speak to a client of mine again without my permission, I'll have you disbarred.
KAFFEE Friends?
JO I had authorization.
KAFFEE From where?
JO Downey's closest living relative, Ginny Miller, his aunt on his mother's side.
KAFFEE You got authorization from Aunt Ginny?
JO I gave her a call like you asked.
JO Very nice woman, we talked for about an hour.
KAFFEE You got authorization from Aunt Ginny.
JO Perfectly within my province.
KAFFEE Does Aunt Ginny have a barn?
KAFFEE We can hold the trial there.
KAFFEE I can sew the costumes, and maybe his Uncle Goober can be the judge.
Jo steps aside and lets KAFFEE got into his car.
JO I'm going to Cuba with you tomorrow.
KAFFEE And the hits just keep on comin'.
HOLD on KAFFEE and Jo.
JO smiles.
He's driving down a Washington street and pulls over at a sidewalk newsstand.
He gets out of his car, leaving the lights flashing, and runs up to the newsstand.
As he plunks his 35 cents down and picks up a newspaper, he engages in his daily ritual with LUTHER, the newsstand operator.
KAFFEE How's it goin', Luther?
LUTHER Another day, another dollar, captain.
KAFFEE You gotta play 'em as they lay, Luther.
LUTHER What comes around, goes around, you know what I'm sayin'.
KAFFEE If you can't beat 'em, join 'em.
LUTHER Hey, if you've got your health, you got everything.
KAFFEE Love makes the world go round.
KAFFEE I'll see you tomorrow, Luther.
And we
A baby sleeping in a crib pull rack to reveal SAM is standing over the crib.
KAFFEE's sitting on a beer.
SAM When Nancy gets back, you're my witness.
SAM The baby spoke.
SAM My daughter said a word.
KAFFEE Your daughter made a sound, Sam, I'm not sure it was a word.
SAM Oh come on, it was a word.
KAFFEE Okay.
SAM You heard her.
SAM The girl sat here, pointed, and said "Pa".
SAM She did.
SAM She said "Pa".
KAFFEE She was pointing at a doorknob.
SAM That's right.
SAM Pointing, as if to say, "Pa, look, a doorknob".
SAM joins KAFFEE in the living room.
KAFFEE Jack Ross came to see me today.
KAFFEE He offered me twelve years.
SAM That's what you wanted.
KAFFEE I know, and I'll...
KAFFEE I guess, I mean --
KAFFEE I'll take it.
SAM So?
KAFFEE It took albout 45 seconds.
KAFFEE He barely put up a fight.
SAM Danny, take the twelve years, it's a gift.
KAFFEE finishes off his beer, and stands.
KAFFEE You don't believe their story, do you?
KAFFEE You think they ought to go to jail for the rest of their lives.
SAM I believe every word they said.
SAM And I think they ought to go to jail for the rest of their lives.
KAFFEE nods and puts down the empty beer bottle.
KAFFEE I'll see you tomorrow.
Sam opens the front door for him and they stand out on the stoop for a moment.
SAM Remember to wear your whites, it's hot down there.
KAFFEE I don't like the whites.
SAM Nobody likes the whites, but we're going to Cuba in August.
SAM You got Dramamine?
KAFFEE Dramamine keeps you cool?
SAM Dramamine keeps you from throwing up, you get sick when you fly.
KAFFEE I get sick when I fly because I'm afraid of crashing into a large mountain, I don't think Dramamine'll help.
SAM I've got some oregano, I hear that works pretty good.
KAFFEE Yeah, right.
KAFFEE starts toward his car, then turns around.
KAFFEE You know, Ross said the strangest thing to me right before I left.
KAFFEE He said the platoon commander Lieutenant Jonathan Kendrick had a meeting with the men and specifically told them not to touch Santiago.
SAM So?
KAFFEE I never mentioned Kendrick.
KAFFEE I don't even know who he is.
KAFFEE What the hell.
KAFFEE I'll see you tomorrow.
We hold for a moment on KAFFEE as he walks to his car, then
The whole place, in stark contrast to the Washington Navy Yard, is ready to go to war.
Fighter jets line the tarmac.
Ground crews re-fuel planes.
Hurried activity.
A 36 seat Airforce Jet rolls to a stop on the tarmac and a stair unit is brought up.
HOWARD, a marine corporal, is waiting by the stairway as the passengers begin to got off.
Mostly MARINES, a few SAILORS, a couple of CIVILIANS, and KAFFEE, JO and SAM.
KAFFEE and SAM are wearing their summer whites, JO is in khakis.
KAFFEE and SAM stare out at what they see: They're not in Kansas anymore.
HOWARD shouts over the noise from the planes.
HOWARD Lieutenants Kaffee and Weinberg?
KAFFEE Yeah.
JO Commander Galloway.
HOWARD I'm Corporal Howard, ma'am, I'm to escort you to the Windward side of the base.
JO Thank you.
HOWARD I've got some camouflage jackets in the back of the jeep, sirs, I'll have to ask you both to put them on.
KAFFEE Camouflage jackets?
HOWARD Regulations, sir.
HOWARD We'll be riding pretty close to the fenceline.
HOWARD The Cubans see an officer wearing white, they think it's someone they might wanna take a shot at.
KAFFEE turns and glares at SAM.
KAFFEE Good call, Sam.
Tearing along down the road, and now we see a beautiful expanse of water, maybe 1000 yards across.
It's a section of Guantanamo Bay.
HOWARD We'll just hop on the ferry and be over there in no time.
KAFFEE Whoa!
KAFFEE Hold it!
KAFFEE We gotta take a boat?!
HOWARD Yes sir, to get to the other side of the bay.
KAFFEE Nobody said anything about a boat.
HOWARD Is there a problem, sir?
KAFFEE No.
KAFFEE No problem.
KAFFEE I'm just not that crazy about boats, that's all.
JO Jesus Christ, Kaffee, you're in the Navy for cryin' out loud!
KAFFEE Nobody likes her very much.
HOWARD Yes sir.
The jeep drives on and we
JESSEP, MARKINSON and KENDRICK are standing as the LAWYERS are led in.
JESSEP Nathan Jessep, come on in and siddown.
KAFFEE Thank you.
KAFFEE I'm Daniel Kaffee, I'm the attorney for Dawson and Downey.
KAFFEE This is Joanne Galloway, she's observing and evaluating --
JO Colonel.
JESSEP Pleased to meet you, Commander.
KAFFEE Sam Weinberg.
KAFFEE He has no responsibility here whatsoever.
JESSEP I've asked Captain Markinson and Lt.
JESSEP Kendrick to join us.
MARKINSON Lt.
MARKINSON Kaffee, I had the pleasure of seeing your father once.
MARKINSON I was a teenager and he spoke at my high school.
KAFFEE smiles and nods.
JESSEP Lionel Kaffee?
KAFFEE Yes sir.
JESSEP Well what do you know.
JESSEP Son, this man's dad once made a lot of enemies down in your neck of the woods.
JESSEP Jefferson vs.
JESSEP Madison County School District.
JESSEP The folks down there said a little black girl couldn't go to an all white school, Lionel Kaffee said we'll just see about that.
JESSEP How the hell is your dad?
KAFFEE He passed away seven years ago, colonel.
JESSEP Well...
JESSEP don't I feel like the fuckin, asshole.
KAFFEE Not at all, sir.
JESSEP Well, what can we do for you, Danny.
KAFFEE Not much at all, sir, I'm afraid.
KAFFEE This is really a formality more than anything else.
KAFFEE The JAG Corps insists that I interview all the relevant witnesses.
JO The JAG Corps can be demanding that way.
JESSEP smiles.
JESSEP Jonanthan'll take you out and show you what you wanna see, then we can all hook up for lunch, how does that sound?
KAFFEE Fine, sir.
A SQUAD OF MARINES jogs by as a jeep carrying KENDRICK and the three LAWYERS cruises down the road.
We FOLLOW the jeep.
KAFFEE I understand you had a meeting with your men that afternoon.
KENDRICK Yes.
KAFFEE What'd you guys talk about?
KENDRICK I told the men that there was an informer among us.
KENDRICK And that despite any desire they might have to seek retribution, Private Santiago was not to be harmed in any way.
KAFFEE What time was that meeting?
KENDRICK Sixteen-hundred.
KAFFEE turns around and looks at SAM.
SAM Four o'clock.
KENDRICK leads the LAWYERS down the corridor to Santiago's room.
Two strips of tape which warn DO NOT ENTER - AT ORDER OF THE MILITARY POLICE are crisscrossed over the closed door.
They open the door and step under the tape and walk into
The room is exactly an it was left that night.
The un-made bed, the chair knocked over...
The LAWYERS look around for a moment.
The room is sparse.
Kaffee goes to the closet and opens it: A row of uniforms hanging neatly.
He thumbs through then for a second, but there's nothing there.
He opens the footlocker: Socks, underwear...
all folded to marine corp precision...
A shaving kit, a couple of photographs, a pad of writing paper and some envelopes...
Kaffee closes the footlocker.
KAFFEE Sam, somebody should see about getting this stuff to his parents.
KAFFEE We don't need it anymore.
KENDRICK Actually, the uniforms belong to the marine corps.
The LAWYERS take a moment.
KAFFEE Lt.
KAFFEE Kendrick -- can I call you Jon?
KENDRICK No, you may not.
KAFFEE Have I done something to offend you?
KENDRICK No, I like all you Navy boys.
KENDRICK Every time we've gotta go someplace and fight, you fellas always give us a ride.
JO Lt.
JO Kendrick, do you think Santiago was murdered?
KENDRICK Commander, I believe in God, and in his son Jesus Christ, and because I do, I can say this: Private Santiago is dead and that's a tragedy.
KENDRICK But he's dead because he had no code.
KENDRICK He's dead because he had no honor.
KENDRICK And God was watching.
SAM turns to KAFFEE.
SAM How do you feel about that theory?
KAFFEE Sounds good.
KAFFEE Let's move on.
SAM and KENDRICK walk out the door.
JO stops KAFFEE.
JO You planning on doing any investigating or are you just gonna take the guided tour?
KAFFEE I'm pacing myself.
JESSEP, MARKINSON, KENDRICK and the LAWYERS are seated at a table in the corner.
Stewards clear the lunch dishes and pour coffee.
Jessep is finishing a story.
JESSEP ...And they spent the next three hours running around, looking for Americans to surrender to.
JESSEP laughs.
KENDRICK joins him.
SAM and KAFFEE force a laugh.
MARKINSON forces a smile.
JO remains silent.
JESSEP (continuing; to the
STEWARDS) That was delicious, men, thank you.
STEWARD Our pleasure, sir.
KAFFEE Colonel just need to ask you a couple of questions about August 6th.
JESSEP Shoot.
KAFFEE On the morning of the sixth, you were contacted by an NIS angent who said that Santiago had tipped him off to an illegal fenceline shooting.
JESSEP Yes.
KAFFEE Santiago was gonna reveal the person's name in exchange for a transfer.
KAFFEE An I getting this right?
JESSEP Yes.
KAFFEE If you feel there are any details that I'm missing, you should free to speak up.
JESSEP's not quite sure what to say to this Navy Lawyer Lieutenant-Smartass guy who just gave him permission to speak freely on his own base.
JESSEP Thank you.
KAFFEE Now it was at this point that you called Captain Markinson and Lt.
KAFFEE Kendrick into your office?
JESSEP Yes.
KAFFEE And what happened then?
JESSEP We agreed that for his own safety, Santiago should be transferred off the base.
Here's something else KAFFEE didn't know.
Neither did Jo.
SAM jots something down on a small notepad.
MARKINSON doesn't flinch.
KAFFEE Santiago was set to be transferred?
JESSEP On the first available flight to the states.
JESSEP Six the next morning.
JESSEP Three hours too late as it turned out.
KAFFEE nods.
KAFFEE Yeah.
There's silence for a moment.
KAFFEE takes a sip of his coffee.
Then drains the cup and puts it down.
KAFFEE Alright, that's all I have.
KAFFEE Thanks very much for your time.
KENDRICK The corporal's got the jeep outside, he'll take you back to the airstrip.
KAFFEE Thank you.
JO Wait a minute, I've got some questions.
KAFFEE No you don't.
JO Yes I do.
KAFFEE No you don't.
JO Colonel, on the morning that Santiago died, did you meet with Doctor Stone between three and five?
KAFFEE Jo --
JESSEP Of course I met with the doctor.
JESSEP One of my men was dead.
KAFFEE See?
KAFFEE The man was dead.
KAFFEE Let's go.
JO I was wondering if you've ever heard the term Code Red.
KAFFEE Jo --
JESSEP I've heard the term, yes.
JO Colonel, this past February, you received a cautionary memo from the Naval Investigative Service, warning that the practice of enlisted men disciplining their own wasn't to be condoned by officers.
JESSEP I submit to you that whoever wrote that memo has never served on the working end of a Soviet-made Cuban Ml-Al6 Assault Rifle.
JESSEP However, the directive having come from the NIS, I gave it its due attention.
JESSEP What's your point, Jo?
KAFFEE She has no point.
KAFFEE She often has no point.
KAFFEE It's part of her charm.
KAFFEE We're outta here.
KAFFEE Thank you.
JO My point is that I think code reds still go on down here.
JO Do Code Reds still happen on this base, colonel?
KAFFEE Jo, the colonel doesn't need to answer that.
JO Yes he does.
KAFFEE No, he really doesn't.
JO Yeah, he really does.
JO Colonel?
JESSEP You know it just hit me.
JESSEP She outranks you, Danny.
KAFFEE Yes sir.
JESSEP I want to tell you something Danny
and listen up 'cause I mean this: You're the luckiest man in the world.
There is, believe me gentlemen, nothing sexier on earth than a woman you have to salute in the morning.
Promote 'em all I say.
JO's not upset.
JO's not mad.
But she's gonna ask her question 'til she gets an answer.
JO Colonel, the practice of code Reds is still condoned by officers on this base, isn't it?
JESSEP You see my problem is, of course, that I'm a Colonel.
JESSEP I'll just have to keep taking cold showers 'til they elect some gal President.
JO I need an answer to my question, sir.
JESSEP Take caution in your tone, Commander.
JESSEP I'm a fair guy, but this fuckin' heat's making me absolutely crazy.
JESSEP You want to know about code reds?
JESSEP On the record I tell you that I discourage the practice in accordance with the NIS directive.
JESSEP Off the record I tell you that it's an invaluable part of close infantry training, and if it happens to go on without my knowledge, so be it.
JESSEP I run my base how I run my base.
JESSEP You want to investigate me, roll the dice and take your chances.
JESSEP I eat breakfast 80 yards away from 4000 Cubans who are trained to kill me.
JESSEP So don't for one second think you're gonna come down here, flash a badge, and make me nervous.
A moment of tense silence before --
KAFFEE Let's go.
KAFFEE Colonel, I'll just need a copy of Santiago's transfer order.
JESSEP What's that?
KAFFEE Santiago's transfer order.
KAFFEE You guys have paper work on that kind of thing, I just need it for the file.
JESSEP For the file.
KAFFEE Yeah.
JESSEP Of course you can have a copy of the transfer order.
JESSEP For the file.
JESSEP I'm here to help anyway I can.
KAFFEE Thank you.
JESSEP You believe that, don't you?
JESSEP Danny?
JESSEP That I'm here to help anyway I can?
KAFFEE Of course.
JESSEP The corporal'll run you by Ordinance on your way out to the airstrip.
JESSEP You can have all the transfer orders you want.
KAFFEE Let's go.
The LAWYERS start to leave.
JESSEP But you have to ask me nicely.
KAFFEE stops.
Turns around.
Sam and JO stop and turn.
KAFFEE I beg your pardon?
JESSEP You have to ask me nicely.
JESSEP You see, Danny, I can deal with the bullets and the bombs and the blood.
JESSEP I can deal with the heat and the stress and the fear.
JESSEP I don't want money and I don't want medals.
JESSEP What I want is for you to stand there in that faggoty white uniform, and with your Harvard mouth, extend me some fuckin' courtesy.
JESSEP You gotta ask me nicely.
KAFFEE and JESSEP are frozen.
Everyone'staring at Kaffee; The OFFICERS at their tables...
KENDRICK...
SAM...
MARKINSON...
JO...
KAFFEE makes his decision.
KAFFEE Colonel Jessep...
KAFFEE if it's not too much trouble, I'd like a copy of the transfer order.
KAFFEE Sir.
JESSEP smiles.
JESSEP No problem.
HOLD for a moment.
JO's very disappointed.
JESSEP stands there and watches the LAWYERS as they turn and leave the Officer's Club.
JESSEP I hate casualties, Matthew.
JESSEP There are casualties even in victory.
JESSEP A marine smothers a grenade and saves his platoon, that marine's a hero.
JESSEP The foundation of the unit, the fabric of this base, the spirit of the Corps, they are things worth fighting for.
MARKINSON looks at the ground.
JESSEP Dawson and Downey, they don't know it, but they're smothering a grenade.
MARKINSON looks up as we
As a plane touches down on the runway.
It's dusk in Washington and
A little one-bedroom.
Just the essential furniture, barely even that.
KAFFEE's sitting and watching a baseball came on t.v.
He's holding a copy of The Baseball Encyclopedia, normally his favorite reading material, but right now he's having trouble keeping his mind in it.
He's holding a baseball bat and fiddling with it.
The remnants of a pizza and Yoo-Hoo dinner sit next to him.
His white uniform in a pile in the corner.
There's a BUZZ at the door.
KAFFEE's not expecting anyone.
He goes to the door.
KAFFEE Who is it?
JO It's me.
KAFFEE opens the door and JO walks in.
KAFFEE I've really missed you, Jo.
KAFFEE I was just saying to myself, "It's been almost three hours since I last saw --
JO Markinson resigned his commission.
KAFFEE When?
JO This afternoon.
JO Sometime after we left.
KAFFEE I'll talk to him in the morning.
JO I already tried, I can't find him.
KAFFEE You tried?
KAFFEE Joanne, you're coming dangerously close to the textbook definition of interfering with a government investigation.
JO hands KAFFEE the file she's been holding.
JO I'm Louden Downey's attorney.
KAFFEE's stunned.
He opens the file and begins to read.
JO Aunt Ginny.
JO She said she feels like she's known me for years.
JO I suggested that she might feel more comfortable if I were directly involved with the case.
JO She had Louden sign the papers about an hour ago.
KAFFEE looks up.
Still too stunned to say anything.
Then finally...
KAFFEE I suppose it's way too much to hope that you're just making this up to bother me.
JO Don't worry, I'm not gonna make a motion for separation, you're still lead counsel.
KAFFEE hands her back the file.
KAFFEE Splendid.
JO I think Kendrick ordered the Code Red.
JO So do you.
DAWSON and DOWNEY come to attention as KAFFEE and JO are led in.
DAWSON Officer on deck, ten hut.
KAFFEE starts in immediately.
KAFFEE Did Kendrick order the code red?
DAWSON Sir?
KAFFEE Don't say sir like I just asked you if you cleaned the latrine.
KAFFEE You heard what I said.
KAFFEE Did Lt.
KAFFEE Kendrick order you guys to give Santiago a code red?
DAWSON Yes sir.
KAFFEE Did he?
DOWNEY Yes sir.
KAFFEE You mind telling me why the hell you never mentioned this before?
DAWSON You didn't ask us, sir.
KAFFEE Cutie-pie shit's not gonna win you a place in my heart, corporal, I get paid no matter how much time you spend in jail.
DAWSON Yes sir.
DAWSON I know you do, sir.
KAFFEE Fuck you, Harold.
There's some understandable tension in the room, broken by --
JO Alright.
JO Let's sort this out.
JO There was a platoon meeting on August 6th at four in the afternoon.
JO And Lt.
JO Kendrick, he gave strict instructions that nothing was to happen to Santiago.
JO Now is that true?
JO I want you to speak freely.
DAWSON Ma'am, that's correct.
DAWSON But then he dismissed the platoon and we all went to our rooms.
JO And what happened then?
DAWSON Lt.
DAWSON Kendrick came to our room, ma'am.
KAFFEE When?
DAWSON About five minutes after the meeting broke, sir.
DAWSON About 16:20.
KAFFEE And what happened then?
DAWSON Lt.
DAWSON Kendrick ordered us to give Santiago a Code Red.
ROSS is playing a game of full-court basketball with some other OFFICERS.
A door at the far end of the court opens and KAFFEE and JO walk in.
They head down the sideline toward Ross.
KAFFEE shouts --
KAFFEE Jack!
But ROSS is into the game...
KAFFEE Jack!!
ROSS Hang on...
KAFFEE They were given an order.
ROSS stops cold and looks over at Kaffee.
The game flies by him.
He motions to the locker room door in the corner of the gym and the three of them make their way to privacy.
JO How long have you known about the order?
ROSS I didn't --
ROSS Who is this?
KAFFEE This is Jo Galloway she's Downey's lawyer.
KAFFEE She's very pleased to meet you.
ROSS What exactly are you accusing me of, commander?
JO I'm accusing you of --
They're in the
LOCKER ROOM - NIGHT and KAFFEE slams the door shut behind them.
KAFFEE Jack didn't know about the order.
KAFFEE Because if he did and he hadn't told us, Jack knows he'd be violating about 14 articles of the code of ethics.
KAFFEE As it is, he's got enough to worry about.
KAFFEE God forbid our clients decide to plead not guilty and testify for the record that they were given an order.
ROSS Kendrick specifically told the men not to touch Santiago.
KAFFEE That's right.
KAFFEE And then he went into Dawson and Downey's room and specifically told them to give him a code red.
ROSS That's not what Kendrick said.
KAFFEE Kendrick's lying.
ROSS You have proof?
KAFFEE I have the defendants.
ROSS And I have 23 marines who aren't accused of murder and a lieutenant with four letters of commendation.
KAFFEE Why did Markinson resign his commission?
ROSS We'll never know.
KAFFEE You don't think I can subpoena Markinson.
ROSS You can try, but you won't find him.
ROSS You know what Markinson did for the first 17 of his 21 years in the corps?
ROSS Counter Intelligence.
ROSS Markinson's gone.
ROSS There is no Markinson.
Some of the wind has been taken Out of Kaffee's sails.
ROSS Jessep's star is on the rise.
ROSS Division'll give me a lot of room to spare Jessep and the corps any embarrassment.
KAFFEE How much room?
ROSS I'll knock it all down to assault.
ROSS Two years.
ROSS They're home in six months.
JO No deal, we're going to a jury.
KAFFEE Jo --
ROSS No you're not.
JO Why not?
ROSS 'Cause you'll lose, and Danny knows it.
ROSS And he knows that if we go to court, I'll have to go all the way, they'll be charged with the whole truckload.
ROSS Murder, Conspiracy, Conduct Unbecoming, and even though he's got me by the balls out here, Dan knows that in a courtroom, he loses this case.
ROSS Danny's an awfully talented lawyer, and he's not about to send his clients go to jail for life when he knows they could be home in six months.
This is now clear: Ross is as good as Kaffee.
ROSS That's the end of this negotiation.
ROSS From this moment, we're on the record.
ROSS I'll see tomorrow morning at the arraignment.
ROSS turns and heads back to the gym as we
Kaffee and JO are sitting at a table.
Dawson and Downey are at parade rest.
Kaffee lights a cigarette.
KAFFEE Here's the story: The Goverment's offering Assault and Conduct Unbecoming.
KAFFEE Two years.
KAFFEE You'll be home in six months.
DAWSON and DOWNEY say nothing.
KAFFEE "Wow, Kaffee, you're the greatest lawyer in the world.
KAFFEE How can we ever thank you?" Fellas, you hear what I just said, you're going home in six months.
DAWSON I'm afraid we can't do that, sir.
KAFFEE Do what?
DAWSON Make a deal, sir.
KAFFEE What are you talking about?
DAWSON We did nothing wrong, sir.
DAWSON We did our job.
DAWSON If that has consequences, then I accept them.
DAWSON But'I won't say I'm guilty, sir.
KAFFEE can't believe this.
He looks over at JO.
KAFFEE Did you --
KAFFEE Did she put you up to this?
JO No.
DAWSON We have a code, sir.
KAFFEE Well zippity-doo-dah.
KAFFEE You and your code plead not guilty and you'll be in jail for the rest of your life.
KAFFEE Do what I'm telling you and you'll be home in six months.
DAWSON just stares at him.
KAFFEE Do it, Harold.
KAFFEE Six months.
KAFFEE It's nothing.
KAFFEE It's a hockey season.
DAWSON Permission to --
KAFFEE Speak!
DAWSON What do we do then, sir?
KAFFEE When?
DAWSON After six months.
DAWSON We'd be dishonorably discharged, right sir?
KAFFEE Yes.
DAWSON What do we do then, sir?
DAWSON We joined the corps 'cause we wanted to live our lives by a certain code.
DAWSON And we found it in the corps.
DAWSON And now you're asking us to sign a piece of paper that says we have no honor.
DAWSON You're asking us to say we're not marines.
DAWSON If a judge and jury decide that what we did was wrong, I'll accept whatever punishment they give.
DAWSON But I believe I was riqht, sir.
DAWSON I believe I did my job.
DAWSON And I won't dishonor myself, my unit, or the Corps, so that I can qo home in six months.
DAWSON Sir.
HOLD ON the four of them for a moment, then
KAFFEE Commander, I want to talk to corporal Dawson alone for a minute.
Jo waits Just a moment before she calls out --
JO Let's go in another room.
JO Louden, everything's gonna be alright.
The M.P. has shown up and unlocked the cell door.
JO We're gonna go into a holding room.
M.P. Aye, aye, ma'am.
JO, DOWNEY, and the M.P. are gone.
KAFFEE paces a moment before he says --
KAFFEE You don't like me that much, do you?
KAFFEE Forget it, don't answer that, it doesn't matter.
KAFFEE paces another moment, then sits on the cot.
He's trying to choose his tack carefully.
KAFFEE You know, Downey worships you.
KAFFEE He's gonna do whatever you do.
KAFFEE Are you really gonna let this happen to him because of a code?
KAFFEE Harold?
DAWSON Do you think we were right?
KAFFEE It doesn't matter what I --
DAWSON Do you think we were right?
KAFFEE gets up.
KAFFEE I think you'd lose.
DAWSON You're such a coward, I can't believe they let you wear a uniform.
KAFFEE stares at DAWSON.
KAFFEE I'm not gonna feel responsible for this, Harold.
KAFFEE I did everything I could.
KAFFEE You're going to Levenworth for the better part of your life, and you know what?
KAFFEE I don't give a shit.
KAFFEE calls out --
KAFFEE and DAWSON are staring each other down.
The M.P. shows up and unlocks the cell door.
KAFFEE steps out to leave.
KAFFEE What happened to saluting an officer when he leaves the room?
DAWSON holds on KAFFEE.
Then DAWSON, a man who would rather die than breach military protocol, takes his hands and puts them in his pockets.
The cell door closes and we
One light is on at the end of the hall.
SAM has joined KAFFEE and JO.
The mood is somber.
KAFFEE Dawson's gonna go to jail just to spite me.
KAFFEE Fine.
KAFFEE If he wants to jump off a cliff, that's his business.
KAFFEE I'm not gonna hold his hand on the way down.
KAFFEE I want to get him a new lawyer.
KAFFEE How do I do it?
SAM You just make a motion tomorrow morning at the arraignment.
SAM The judge'll ask you if you want to enter a plea.
SAM You tell him you want new counsel assigned.
KAFFEE Then that's that.
JO Yeah.
JO One thing, though.
JO When you ask the judge for new counsel, Danny, be sure and ask nicely.
KAFFEE What do you want from me?
JO I want you to let 'em be judged!
JO I want you to stand up and make an argument!
SAM An argument that didn't work for Calley at My Lai, an argument that didn't work for the Nazis at Nuremberg.
KAFFEE For Christ sake, Sam, do you really think that's the same as two teenage marines executing a routine order that they never believed would result in harm?
KAFFEE These guys aren't the Nazis.
There's a pause in the room.
JO Don't look now, Danny, but you're making an argument.
KAFFEE Yeah.
KAFFEE Tomorrow morning I'll get them a new attorney.
JO Why are you so afraid to be a lawyer?
JO Were daddy's expectations really that high?
KAFFEE Please, spare me the psycho-babble father bullshit.
KAFFEE Dawson and Downey'll have their day in court, but they'll have it with another lawyer.
JO Another lawyer won't be good enough.
JO They need you.
JO You know how to win.
JO You know they have a case.
JO And you know how to win.
JO You walk away from this now, and you have sealed their fate.
KAFFEE Their fate was sealed the moment Santiago died.
JO Do you believe they have a defense?
KAFFEE You and Dawson both live in the same dreamland.
KAFFEE It doesn't matter what I believe, it only matters what I can prove.
KAFFEE So please don't tell me what I know and don't know.
KAFFEE I know the law.
JO looks at him, shakes her head, and turns to walk away.
She turns back.
JO You know nothing about the law.
JO You're a used car salesman, Daniel.
JO You're an ambulance chaser with a rank.
JO You're nothing.
JO Live with that.
Jo walks off leaving KAFFEE alone.
We HOLD on KAFFEE.
He's not having a good night.
KAFFEE sits at the bar.
The place is crowded with YUPPIES and STUDENTS.
KAFFEE's been drinking there a while now.
Next to him is a YUPPIE LAWYER, regaling his FRIENDS with the story of his latest brilliant maneuver in the world of high stakes corporate law.
We HOLD on a KAFFEE a moment longer, then
YUPPIE LAWYER ...So I told duncan if we leverage the acquisition of Biotech, the interrogatories would be there on demand.
YUPPIE LAWYER All I have to do is not pick up the phone and it'll run Flaherty ten thousand a day in court costs.
KAFFEE sits on a bench in the night.
He takes a sip from a bottle he's holding in a brown paper bag.
A bright, sunny morning.
The BAND is performing for a group of day campers.
DAWSON and DOWNEY are at the defense table, ROSS is his place.
KAFFEE walks in and joins JO and SAM at their table.
Papers are being passed back and forth between ROSS and the SERGEANT AT AMS.
Quiet activity.
The door in the back of the courtroom opens and RANDOLPH, a marine colonel, enters and takes his place at the bench.
We can HEAR the band in the background.
SERGEANT AT ARMS All rise.
Everyone present in the courtroom stands.
RANDOLPH Where are we?
SERGEANT AT ARMS Docket number 411275.
SERGEANT AT ARMS VR-5.
SERGEANT AT ARMS United States versus Lance Corporal Harold W.
SERGEANT AT ARMS Dawson and Private First Class Loudon Downey.
SERGEANT AT ARMS Defendants are charged with Conspiracy to Commit Murder, Murder in the First Degree, and Conduct Unbecoming a United States Marine.
RANDOLPH Does defense wish to enter a plea?
KAFFEE stands.
KAFFEE Yeah.
KAFFEE They're not guilty.
JO, SAM, ROSS, RANDOLPH...
it's hard to say who's the most surprised.
It takes everything Jo's got to suppress a smile.
The silence is broken by ROSS, who takes the two files, drops them into his briefcase, closes the lid, and snaps it shut.
RANDOLPH looks at KAFFEE and ROSS, then turns to the SERGEANT
RANDOLPH Enter a plea of not guilty for the defendants.
RANDOLPH We'll adjourn until ten- hundred, three weeks from today, at which time this Court will reconvene as a General Court-Martial.
He raps the gavel.
RANDOLPH walks out.
ROSS walks up the aisle without a word to anyone.
The M.P.'s come to escort DAWSON and DOWNEY back to their cell.
KAFFEE and JO and SAM are the only ones remaining.
SAM is looking at KAFFEE with question marks in his eyes.
KAFFEE Why does a junior grade with six months experience and a track record for plea bargaining get assigned a murder case?
KAFFEE Would it be so that it never sees the inside of a courtroom?
KAFFEE picks up his briefcase and begins heading toward the door.
KAFFEE We'll work out of my apartment.
KAFFEE Every night, seven o'clock.
KAFFEE Jo, before you come over tonight, pick up a carton of legal pads, a half-dozen boxes of red pens, a half-dozen boxes of black pens.
KAFFEE Sam get a couple of desk lamps.
KAFFEE I need you to start on a preliminary medical profile and Jo, we need all the fitness reports on Dawson, Downey and Santiago.
KAFFEE The only thing I have to eat is Yoo-Hoo and SugarSnacks, so if you want anything else, bring it with you.
KAFFEE Okay?
Jo's still stunned.
JO Yeah.
KAFFEE's at the door, stops, turns around, and takes it all in for a moment.
KAFFEE So this is what a courtroom looks like.
He walks out the door, and we
Among the stuff, is a blackboard that's been hung on the wall.
Written across the top are three headings:
Sam is on the floor, sorting papers into piles.
KAFFEE comes in from the kitchen with a fresh bottle of Yoo-Hoo and joins Sam on the floor.
KAFFEE Were you able to speak to your friend at NIS?
SAM She said if Markinson doesn't want to be found, we're not gonna find him.
SAM She said I could be Markinson and you wouldn't know it.
KAFFEE Are you Markinson?
SAM No.
KAFFEE Well, I'm not Markinson, that's two down.
SAM doesn't laugh.
KAFFEE What.
SAM I was wondering, now that Joanne's working on this...
SAM I was wondering if you still need me.
KAFFEE They were following an order, Sam.
SAM An illegal order.
KAFFEE You think Dawson and Downey know it was an illegal order?
SAM It doesn't matter if they know, any decent human being would've refused to --
KAFFEE They're not permitted to question orders.
SAM Then what's the secret?
SAM What are the magic words?
SAM I give orders every day, and nobody follows them.
KAFFEE We have softball games and marching bands.
KAFFEE They work at a place where you have to wear camouflage or you might get shot.
Sam looks away.
He doesn't buy it.
KAFFEE I need you.
KAFFEE You're better at research than I am and you know how to prepare a witness.
Jo lets herself in.
She's carrying a huge stack of papers under one arm, and a large brown paper bag under the other.
But we stay with KAFFEE and Sam a moment longer.
JO I've got medical reports and Chinese food.
JO I say we eat first.
KAFFEE's still looking at SAM.
SAM nods his head.
SAM Did you get any dumplings?
The remnants of the Chinese food is spread around.
SAM and JO are sitting and taking notes from KAFFEE.
As he speaks, he'll pace slowly around, carrying his baseball bat.
He refers to the blackboard.
KAFFEE This is our defense.
KAFFEE Intent: No one can prove there was poison on the raq.
KAFFEE Code Red: They're common and
accepted in Guantanamo Bay.
The Order:
A) Kendrick gave it.
B) They had no choice but to follow it.
That's it.
SAM What about motive?
KAFFEE We're a little weak on motive.
KAFFEE They had one.
JO Just because a person has a motive doesn't mean --
KAFFEE Relax.
KAFFEE We'll deal with the fenceline shooting when it comes up.
KAFFEE For now we start here --
KAFFEE I don't know what made Santiago die, I don't want to know.
KAFFEE I just want to be able to show it could've been something other than poison.
KAFFEE Jo, talk to doctors.
KAFFEE Find out everything there is to know about lactic acidosis.
KAFFEE Let's start prepping for Stone.
JO As long as we're on the subject of the doctor --
KAFFEE Here we go.
JO Listen to me, three o'clock he doesn't know what killed Santiago, then he meets with Jessep, and at five o'clock he says it was poison?
JO The doctor's covering up the truth.
KAFFEE Oh, that's a relief.
KAFFEE I was afraid I wouldn't be able to use the "Liar, Liar, Pants on Fire" defense.
KAFFEE We can't prove coercion!!
KAFFEE Alright, fitness reports and biographical information.
SAM Cartons 3 and 4.
KAFFEE looks at the cartons and the mind-numbing amount of paper.
KAFFEE No Cliff-Notes on these things?
The scenes cover the three weeks of preparation leading up to the trial, and are interspersed with shots of Kaffee's apartment getting messier, KAFFEE, JO and SAM flipping through documents and reference books, writing on the blackboard, dozzing off...
We start with
Jo's on the phone, KAFFEE and SAM are going over testimony, with SAM sitting in a mock witness chair.
During this, KAFFEE will go to the door, pay the PIZZA Man for the pizza, and return without missing a single beat.
JO Captain Hill, this is Lt.
JO Commander Galloway, I'm an internal affairs officer with the JAG Corps in Washington, D.C. I'm trying to track down a Captain Matthew Andrew Markinson, USMC...
KAFFEE Doctor, other than the rope marks, was there any other sign of external damage?
SAM No.
KAFFEE No scrapes?
SAM No.
KAFFEE No cuts?
JO He resigned his commission a week ago Thursday.
KAFFEE Bruises?
KAFFEE Broken bones?
SAM No.
JO No, please don't put me on hold --
KAFFEE Doctor, was there any sign of violence?
SAM You mean other than the dead body?
KAFFEE Fuck!!
KAFFEE I walk into that every goddam time!
SAM Don't ask the last question.
MOS -- JO pulls two thick volumes off a shelf and takes them to the table where SAM and KAFFEE are working.
She plops the books down where they join a pile of about two-dozen just like them and we
The LAWYERS have their books and papers spread out in front of them.
KAFFEE Lt.
KAFFEE Kendrick, the type of disciplinary action, or "training'' as you say --
JO Object.
KAFFEE Please the Court, I maintain that nothing could be more relevant than what the defendants learned by the example of, among others, the witness.
JO Nice.
MOS -- KAFFEE's paying the pizza boy again.
He goes into the living room where SAM is on the "stand".
It's getting hard to see the floor from all the papers, cartons, books, pizza boxes, etc., and
A HOLDING ROOM where DAWSON and DOWNEY are being put through their paces.
JO And what happened after Kendrick came into your room?
DOWNEY He ordered me and Corporal Dawson to give Willy a Code Red.
SAM His answers still have to come faster, Jo.
SAM The Iowa farmboy thing'll play for a while, but in the end it looks like he's searching for the truth.
KAFFEE He's right, and from now on, "Willy" is Private Santiago.
KAFFEE You start calling him Willy and all of a sudden he's a person who's got a mother who's gonna miss him.
MOS -- The clock reads 3:37, and KAFFEE, in sweatpants and a bathrobe, is pacing around slowly with his baseball bat and
SAM and JO art listening to a lecture for the 14th time.
KAFFEE Poker faces.
KAFFEE Don't flinch in front of the jury.
KAFFEE Something doesn't go our way, don't hang your head, don't shift in your seat, don't scribble furiously.
KAFFEE Whatever happens, you have to look like it's exactly what you knew was gonna happen.
KAFFEE When you pass me documents --
JO/SAM Do it swiftly, but don't look overanxious.
KAFFEE And don't wear that perfume in Court, it wrecks my concentration.
JO Really!
KAFFEE I was talking to Sam.
SAM What time is it?
KAFFEE Time to go home.
KAFFEE Try to get some sleep tonight.
JO I'll give you a ride.
SAM begins to gather up his things.
He stands in front of
KAFFEE You're a good man, Charlie Brown.
SAM See you in court.
Sam steps out the door.
JO looks at the ground, then up at
JO Danny --
KAFFEE I know what you're gonna say.
KAFFEE You don't have to.
KAFFEE We've had our differences.
KAFFEE I've said some things I didn't mean, you've said some things you didn't means but you're happy that I stuck with the case.
KAFFEE And if you've gained a certain respect for me over the last three weeks that you didn't have before, well, of course I'm happy about that, but we don't have to make a whole big deal out of it.
KAFFEE You like me.
KAFFEE I won't make you say it.
JO I was just gonna tell you to wear matching socks tomorrow.
KAFFEE Oh.
KAFFEE Okay.
KAFFEE Good tip.
JO We're ready.
KAFFEE Bet your ass.
Jo walks out the door and KAFFEE closes it and locks it behind her.
Then he says, very softly...
KAFFEE We're gonna get creamed.
A few M.P.Is are standing by the entrance.
KAFFEE comes around the corner and heads toward the courtroom.
We're immediately stricken by something:
In his dress blue uniform he could easily be mistaken for a real live naval officer.
He opens the courtroom doors and walks into
A few more M.P.'s are standing around.
THE JURORS, nine enlisted navy and marine men and women, are in their place, Ross is at his table looking through some papers, and DAWSON and DOWNEY, in handcuffs, are seated at the defense table.
The trial in a few moments from being underway and a few people are milling about.
KAFFEE walks down the aisle but is stopped by a voice behind him.
MAN Lieutenant Kaffee?
KAFFEE turns around to see a MAN and WOMAN who are clearly Dawson's parents.
MAN You're gonna save our son, aren't you?
KAFFEE I'll do my best.
KAFFEE continues on and stops next to JO, who's talking with a WOMAN in her mid-30's.
JO Danny, I want you to meet Ginny Miller, Louden's aunt.
KAFFEE You're Aunt Ginny?
GINNY Uh-huh.
KAFFEE I'm sorry, I was expecting someone older.
GINNY So was I.
Not quite the words of inspiration KAFFEE was hoping to hear before he does the hardest thing he's ever had to do.
He walks over to ROSS.
KAFFEE Last chance.
KAFFEE I'll flip you for it.
RANDOLPH enters.
SERGEANT AT ARMS All rise.
ROSS Too late.
KAFFEE walks back to his table as
SERGEANT AT ARMS All those having business with this general court-martial, stand forward and you shall be heard.
SERGEANT AT ARMS Captain Julius Alexander Randolph is presiding.
SERGEANT AT ARMS God save the United States of America.
RANDOLPH raps the gavel.
RANDOLPH without objection, the sworn confessions of the two defendants have been read to the jury and entered into the court record.
ROSS No objection, your honor.
KAFFEE No objection.
RANDOLPH Is the Government prepared to make an opening statement?
ROSS Yes sir.
ROSS walks to the jury box.
ROSS The facts of the case are this: At midnight on August 6th, the defendants went into the barracks room of their platoon-mate, PFC William Santiago.
ROSS They woke him up, tied his arms and legs with rope, and forced a rag into his throat.
ROSS A few minutes later, a chemical reaction in Santiago's body called lactic acidosis caused his lungs to begin bleeding.
ROSS He drowned in his own blood and was pronounced dead at 32 minutes past midnight.
ROSS These are the facts of the case.
ROSS And they are undisputed.
ROSS That's right.
ROSS The story I just told you is the exact same story you're going to hear from Corporal Dawson, and it's the exact same story you're going to hear from Private Downey.
ROSS Furthermore, the Government will also demonstrate that the defendants soaked the rag with poison, and entered Santiago's room with motive and intent to kill.
ROSS Now, Lt.
ROSS Kaffee, is gonna try to pull off a little magic act, he's gonna try a little misdirection.
ROSS He's going to astonish you with stories of rituals and dazzle you with official sounding terms like Code Red.
ROSS He might even cut into a few officers for you.
ROSS He'll have no evidence, mind you, none.
ROSS But it's gonna be entertaining.
ROSS When we get to the end, all the magic in the world will not have been able to divert your attention from the fact that Willy Santiago is dead, and Dawson and Downey killed him.
ROSS These are the facts of the case.
ROSS And they are undisputed.
ROSS walks back to his seat.
RANDOLPH Lt.
RANDOLPH Kaffee?
Before KAFFEE's even stood up, these words are coming out of his mouth.
KAFFEE There was no poison on the rag and there was no intent to kill and any attempt to prove otherwise is futile because it just ain't true.
KAFFEE When Dawson and Downey went into Santiago's room that night, it wasn't because of vengeance or hatred, it wasn't to kill or harm, and it wasn't because they were looking for kicks on a Friday night.
KAFFEE It's because it was what they were ordered to do.
KAFFEE Let me say that again: It's because it was what they were ordered to do.
KAFFEE Now, out in the real world, that means nothing.
KAFFEE And here at the Washington Navy Yard, it doesn't mean a whole lot more.
KAFFEE But if you're a marine assigned to Rifle Security Company Windward, Guantanamo Bay, Cuba, and you're given an order, you follow it or you pack your bags.
KAFFEE Make no mistake about it, Harold Dawson and Louden Downey are sitting before you in judgement today because they did their job.
KAFFEE walks back to the table and takes his seat.
RANDOLPH Is the Government ready to call its first witness?
ROSS Please the Court, the Government calls Mr. R.C McGuire.
While McCGUIRE, a civilian in his late 30's, is being sworn in, KAFFEE has sat back down.
He leans over to DAWSON and whispers.
KAFFEE How you doin'?
DAWSON doesn't change his expression.
KAFFEE Good.
ROSS Mr. McGuire, would you state your full name and occupation for the record, please?
MCGUIRE Robert C. McGuire, Special Agent, Naval Investigative Service.
ROSS Mr. McGuire, did your office receive a letter from PFC William Santiago on 3 August of this year?
MCGUIRE We did.
ROSS What did the letter say?
MCGUIRE That a member of Private Santiago's unit had illegally fired his weapon over the fenceline.
ROSS Was that marine identified in the letter?
MCGUIRE No sir.
MCGUIRE I notified the barracks C.O., Colonel Jessep, that I would be coming down to investigate.
ROSS And what did you find?
MCGUIRE For the shift reported, only one sentry returned his weapon to the switch with a round of ammunition missing.
ROSS And who was that?
MCGUIRE Lance Corporal Harold Dawson.
ROSS Your witness.
ROSS goes back to his table.
KAFFEE stands.
KAFFEE Mr. McGuire, have you questioned Corporal Dawson about the fenceline shooting?
MCGUIRE Yes.
MCGUIRE He claims to have been engaged in some manner by the enemy.
KAFFEE But you don't believe him.
MCGUIRE It's not my place --
KAFFEE Corporal Dawson's been charged with a number of crimes, why wasn't he charged with firing at the enemy without cause?
MCGUIRE There wasn't enough evidence to support such a charge.
KAFFEE Thank you.
KAFFEE sits.
ROSS Mr. McGuire, I don't understand what you mean when you say there wasn't enough evidence to support such a charge.
ROSS You had Willy Santiago's letter.
MCGUIRE Santiago was the only witness, but I never had a chance to interview him.
MCGUIRE So I don't know what he saw.
ROSS And now we won't ever know, will we, Mr. McGuire?
MCGUIRE No.
ROSS No more questions.
HAMMAKER, a young marine corporal, is being sworn in.
HAMMAKER Corporal Carl Edward Hammaker, Marine Barracks, Rifle Security Company Windward, Second Platoon Charlie.
ROSS Corporal, were you present at a meeting that Lt.
ROSS Kendrick held on the afternoon of August 6th with the members of second platoon.
HAMMAKER Yes sir.
ROSS Would you tell the Court the substance of that meeting?
HAMMAKER Lt.
HAMMAKER Kendrick told us that we had an informer in our group.
HAMMAKER That Private Santiago had gone outside the chain of command and reported to the NIS on a member of our platoon.
ROSS Did that make you mad?
ROSS You can tell the truth, corporal, it's alright.
ROSS Did it make you mad?
HAMMAKER Yes sir.
ROSS How mad?
HAMMAKER Private Santiago betrayed a code that we believe in very deeply, sir.
ROSS Were the other members of the squad angry?
KAFFEE Object --
ROSS Were Dawson and Downey?
KAFFEE Please the Court, is the judge advocate honestly asking this witness to testify as to how the defendant felt on August 6th?
RANDOLPH Sustained.
ROSS Corporal, did Lt.
ROSS Kendrick leave a standing order at that meeting?
RANDOLPH Yes sir.
ROSS What was it?
HAMMAKER Well it was clear that he didn't want us to take matters into our own hands, sir.
ROSS What was the order?
HAMMAKER Sir, he said that Santiago wasn't to be touched.
ROSS Your witness.
KAFFEE Corporal Hammaker, were you in Dawson and Downey's barracks room ten minutes after this meeting?
HAMMAKER No sir.
KAFFEE Thanks, I have no more questions.
HAMMAKER gets off the stand, and KAFFEE watches while walks past DAWSON and DOWNEY.
A barely perceptible exchange occurs between the eyes of DAWSON and HAMMAKER.
KAFFEE makes a decision.
ROSS The Government calls Corporal Raymond Thomas --
KAFFEE Please the Court, I understand Lt.
KAFFEE Ross is planning on calling all the other members of Rifle Security Company Windward to testify.
ROSS In light of the defense that Lt.
ROSS Kaffee is planning to mount, the explicit instructions of the platoon leader seems particularly relevant testimony.
KAFFEE The defense is willing to concede that all 23 witnesses will testify substantially as Corporal Hammaker did, if the Government is willing to concede that none of them were in Dawson and Downey's room at 16:20 on August 6th.
RANDOLPH Lieutenant?
ROSS The Government'll agree to the stipulation, sir.
RANDOLPH Then we'll adjourn for the day.
RANDOLPH You can call your next witness in the morning.
THE PARADE GROUNDS - EARLY MORNING, two SAILORS are raising the flag.
COMMANDER STONE, a Navy doctor in his mid-40's, is on the stand.
STONE ...And he was pronounced dead at zero-zero-thirty-seven.
ROSS Dr. Stone, what's lactic acidosis?
STONE If the muscles and other cells of the body burn sugar instead of oxygen, lactic acid is produced.
STONE That lactic acid is what caused Santiago's lungs to bleed.
ROSS How long does it take for the muscles and other cells to begin burning oxygen instead of sugar?
STONE Twenty to thirty minutes.
ROSS And what caused Santiago's muscles and other cells to start burning sugar?
STONE An ingested poison of some kind.
KAFFEE Your Honor, we object at this point.
KAFFEE The witness is speculating.
ROSS Commander Stone is an expert medical witness, in this courtroom his opinion isn't considered speculation.
KAFFEE Commander Stone is an internist, not a criminologist, and the medical facts here are ultimately inconclusive.
RANDOLPH A point which I'm confident you'll illustrate to the jury under cross- examination, so I'm sure you won't mind if his opinion is admitted now.
KAFFEE Not at all, sir.
KAFFEE Objection withdrawn.
KAFFEE sits.
ROSS Doctor Stone, did Willy Santiago die of poisoning?
STONE Absolutely.
ROSS Are you aware that the lab report and the coroners report showed no traces of poison?
STONE Yes I am.
ROSS Then how do you justify --
STONE There are literally dozens of toxins which are virtually undetectable, both in the human body and on a fabric.
STONE The nature of the acidosis is the compelling factor in this issue.
ROSS Thank you, sir.
KAFFEE gets up.
KAFFEE Commander, you testified that it takes lactic acidosis 20 to 30 minutes before it becomes lethal.
STONE Yes.
KAFFEE Let me ask you, is it possible for a person to have an affliction, some sort of condition, which might, in the case of this person, actually speed up the process of acidosis dramatically?
STONE says nothing for a moment.
KAFFEE Commander, is it possible?
STONE Certainly.
KAFFEE What might some of those conditions be?
STONE If a person had a coronary disorder...
STONE or a cerebral disorder, the process would be more rapid.
KAFFEE Commander, if I had a coronary condition, and a perfectly clean rag was placed in my mouth, and the rag was accidentally pushed too far down, is it possible that my cells would continue burning sugar after the rag was taken out?
STONE It would have to be a very serious condition.
KAFFEE Is it possible to have a serious coronary condition, where the initial warning signals were so mild as to escape a physician during a routine medical exam?
STONE Possibly.
STONE There would still be symptoms though.
KAFFEE What kind of symptoms?
STONE There are hundreds of symptoms of a --
KAFFEE Chest pains?
STONE Yes.
KAFFEE Shortness of breath?
STONE Yes.
KAFFEE Fatigue?
STONE Of course.
KAFFEE has gone back to his table where JO has handed him some documents.
He shows then to STONE.
KAFFEE Doctor, is this your signature?
STONE Yes it is.
KAFFEE This in an order for Private Santiago to be put on restricted duty.
KAFFEE Would you read your hand written remarks at the bottom of the page, please, sir.
STONE "Initial testing negative.
STONE Patient complains of chest pains, shortness of breath, and fatigue.
STONE Restricted from running distances over five miles for one week."
KAFFEE Commander, isn't it possible that Santiago had a serious coronary condition, and it was that condition, and not some mysterious poison, that caused the accelerated chemical reaction?
STONE No.
STONE I personally give the men a physical examination every three months.
STONE And every three months Private Santiago got a clean bill of health.
KAFFEE And that's why it had to be, poison, right, Commander?
KAFFEE 'Cause Lord knows, if you put a man with a serious coronary condition back on duty with a clean bill of health, and that man died from a heart related incident, you'd have a lot to answer for, wouldn't you, doctor?
ROSS Object.
ROSS Move to strike.
RANDOLPH Sustained.
RANDOLPH Strike it.
KAFFEE No more questions, judge.
ROSS stands immediately.
ROSS Dr. Stone, you've held a license to practice medicine for 21 years, you are Board Certified in Internal Medicine, you are the Chief of Internal Medicine at a hospital which serves over 8000 men.
ROSS In your professional opinion, was Willy Santiago poisoned?
Jo stands.
JO Your Honor, we re-new our objection to Commander Stone's testimony, and ask that it be stricken from the record.
JO And we further ask that the Court instruct the jury to lend no weight to this witness's testimony.
KAFFEE and SAM are dying, but they're trying to keep their poker-faces.
RANDOLPH'S gonna try to be polite about this, but he thought he made himself clear.
RANDOLPH The objection's overruled, counsel.
JO Sir, the defense strenuously objects and requests a meeting in chambers so that his honor might have an opportunity to hear discussion before ruling on the objection.
RANDOLPH The objection of the defense has been heard and overruled.
JO Exception.
RANDOLPH Noted.
RANDOLPH The witness is an expert and the court will hear his opinion.
ROSS Doctor, in your expert, professional opinion, was Willy Santiago poisoned?
STONE Yes.
ROSS Thank you, sir, I have no more questions.
RANDOLPH Commander, you may step down.
ROSS Please the Court, while we reserve the right to call rebuttal witnesses if the need arises, the Government rests.
RANDOLPH We'll stand in recess until ten- hundred hours this Monday, the l9th at which time the defense will call it's first witness.
RANDOLPH raps his gavel.
SERGEANT AT ARMS Ten hut.
And the courtroom begins clearing out.
KAFFEE, JO and SAM are packing up their various papers.
SAM I strenuously object?
SAM Is that how it works?
SAM Objection.
SAM Overruled.
SAM No, no, no, no, I strenuously object.
SAM Oh, well if you strenuously object, let me take a moment to reconsider.
JO I got it on the record.
SAM You also got it in the jury's head that we're afraid of the doctor.
SAM You object once so they can hear you say he's not a criminologist.
SAM You keep after it and it looks like this great cross we did was just a bunch of fancy lawyer tricks.
SAM It's the difference between paper law and trial --
KAFFEE Sam --
SAM Christ, you even had the Judge saying Stone was an expert!
KAFFEE Sam, she made a mistake.
KAFFEE Let's not relive it.
There's an uncomfortable silence.
SAM I'm gonna go call my wife.
SAM I'll meet you tonight.
Sam starts to leave.
JO turns and says
JO Why do you hate them so much?
Sam stops and turns around.
SAM They beat up on a weakling, and that's all they did.
SAM The rest is just smokefilled coffee-house crap.
SAM They tortured and tormented a weaker kid.
SAM They didn't like him.
SAM And they killed him.
SAM And why?
SAM Because he couldn't run very fast.
A long silence.
KAFFEE makes a decision.
KAFFEE Alright.
KAFFEE Everybody take the night off.
SAM I apologize, I, --
KAFFEE It's alright.
KAFFEE We've been working 20 hour days for three and a half weeks straight.
KAFFEE Take the night off.
KAFFEE Go see your wife, see your daughter.
KAFFEE Jo, do whatever it is you do when you're not here.
KAFFEE What day is tomorrow?
SAM Saturday.
KAFFEE We'll start at ten.
KAFFEE picks up his stuff and walks out.
SAM and JO stand there uncomfortably for a moment.
JO begins packing up her things.
SAM Why do you like them so much?
JO 'Cause they stand on a wall.
JO And they say "Nothing's gonna hurt you tonight.
JO Not on my watch."
Despite their differences, SAM likes this woman.
SAM Don't worry about the doctor.
SAM This trial starts Monday.
A baseball game is on.
KAFFEE's pacing slowly around, carrying his baseball bat.
He's looking at the blackboard as he walks around the room.
He's studying it.
Studying it hard.
There's a knock on the door.
KAFFEE answers it.
JO is standing in the doorway.
JO I'm sorry to bother you, I should've called first.
KAFFEE No, I was just watching a baseball game.
JO I was wondering if -- how you'd feel about my taking you to dinner tonight.
KAFFEE Jo, are you asking me out on a date?
JO No.
KAFFEE It sounded like you were asking me out on a date.
JO I wasn't.
KAFFEE I've been asked out on dates before, and that's what it sounded like.
JO Do you like seafood?
JO I know a good seafood place.
On the Virginia side of the Potomac.
KAFFEE and JO are sitting at a table, finishing up dinner.
JO My third case was a Drunk and Disorderly.
JO The trial lasted nine weeks.
JO I rounded up 31 people who were in the bar that night.
KAFFEE Nine weeks on a D and D?
KAFFEE What was the prosecutor offering?
JO 15 days.
KAFFEE Well, you sure hustled the shit outta him.
JO After that, they moved me to internal affairs.
KAFFEE Tough to blame them.
JO Where I've earned two distinguished service medals and two letters of commendation.
KAFFEE Why are you always giving me your resume?
JO Because I want you to think I'm good lawyer.
KAFFEE I do.
JO No you don't.
JO I think you're an exceptional lawyer.
JO I watch the jurors, they respond to you, they like you.
JO I see you convincing them.
JO I think Dawson and Downey are gonna end up owing their lives to you.
KAFFEE Jo...
KAFFEE I think you have to prepare yourself for the fact that we're gonna lose.
KAFFEE Ross's opening speech, it was all true.
KAFFEE I mean, let's pretend for a minute that it would actually matter to this jury that the guys were given an order.
KAFFEE We can't prove it ever happened.
KAFFEE We'll keep doing what we're doing, and we'll put on a show, but at the end of the day, all we have is the testimony of two people accused of murder.
JO We'll find Markinson.
KAFFEE Jo, we're gonna lose.
KAFFEE And we're gonna lose huge.
We HOLD on then for a moment, and in VOICE OVER hear
HOWARD (V.O.) Corporal Jeffrey Owen Howard, Marine Barracks Windward, Guantanamo Bay, Cuba.
CORPORAL HOWARD, the young marine who drove the lawyers around Cuba, is on the stand.
KAFFEE Corporal Howard, name some reasons why a marine would get a code red?
HOWARD Being late for platoon or company meetings, keeping his barracks in disorder, falling back on a run...
KAFFEE Have you ever received a code red?
HOWARD Yes sir.
HOWARD We were doing seven man assault drills, and my weapon slipped.
HOWARD It's just cause it was over a hundred degrees and my palms were sweaty and I'd forgot to use the resin like we were taught.
KAFFEE And what happened?
HOWARD That night the guys in my squad threw a blanket over me and took turns punching me in the arm for five minutes.
HOWARD Then they poured glue on my hands.
HOWARD And it worked, too, 'cause I ain't never dropped my weapon since.
KAFFEE Was Private Santiago ever late for platoon meetings?
HOWARD Yes sir.
KAFFEE Was his barracks ever in disorder?
HOWARD Yes sir.
KAFFEE Did he ever fall back on a run?
HOWARD All the time, sir.
KAFFEE Did he ever, prior to the night of August 6th, receive a code red?
HOWARD No sir.
KAFFEE Never?
HOWARD No, sir.
KAFFEE You got a code red 'cause your palms were sweaty.
KAFFEE Why didn't Santiago, this burden to his unit, ever get one?
HOWARD Dawson wouldn't allow it, sir.
KAFFEE Dawson wouldn't allow it.
HOWARD The guys talked tough about Santiago, but they wouldn't go near him.
HOWARD They were too afraid of Dawson, sir.
ROSS Object.
ROSS The witness is characterizing.
KAFFEE I'll rephrase.
KAFFEE Jeffrey, did you ever want to give Santiago a code red?
HOWARD Yes sir.
KAFFEE Why didn't you?
HOWARD 'Cause Dawson'd kick my butt, sir.
KAFFEE Good enough.
KAFFEE Lt.
KAFFEE Ross is gonna ask you some questions now.
ROSS takes three books out of his briefcase and puts them on the table.
He brings one to HOWARD.
ROSS Corporal Howard, I hold here The Marine Guide and General Information Handbook for New Recruits.
ROSS Are you familiar with this book?
HOWARD Yes sir.
ROSS Have you read it?
HOWARD Yes sir.
ROSS Good.
ROSS Would you turn to the chapter that deals with code reds, please.
HOWARD Sir?
ROSS Just flip to the page in that book that discusses code reds.
HOWARD Sir, you see, Code Red is a term we use -- it's just used down at GITMO, sir.
HOWARD I don't know if it actually --
ROSS has produced another book.
ROSS We're in luck, then.
ROSS The Marine Corps Guide for Sentry Duty, NAVY BASE Guantanamo Bay, Cuba.
ROSS I assume we'll find the term code red and its definition in this book, am I correct?
HOWARD No sir.
ROSS No?
ROSS Corporal Howard, I'm a marine.
ROSS Is their no book, no manual or pamphlet, no set of orders or regulations that let me know that, as a marine, one of my duties is to perform code reds?
HOWARD No sir.
HOWARD No books, sir.
ROSS No further questions.
ROSS sits.
KAFFEE walks over to ROSS's table and picks up one of the books.
He brings it to HOWARD.
KAFFEE Corporal, would you turn to the page in this book that says where the enlisted men's mess hall is?
HOWARD Lt.
HOWARD Kaffee, that's not in the book, sir.
KAFFEE I don't understand, how did you know where the enlisted men's mess hall was if it's not in this book?
HOWARD I guess I just followed the crowd at chow time, sir.
KAFFEE No more questions.
KAFFEE chucks the book back on ROSS's desk.
RANDOLPH Corporal Howard, you can step down.
HOWARD Thank you, sir.
KAFFEE gives HOWARD a subtle "You Did Good, Kid" look, and we
It's the end of the day's session.
KAFFEE walks down the hall with SAM and JO.
KAFFEE Seven tonight, we'll do a final Kendrick review.
KAFFEE I want to slam- dunk this guy.
KAFFEE'S CAR as it drives along a street in the D.C. business district.
it's evening now and the windshield wipers are fighting against a rain KAFFEE pulls over at his usual newsstand.
He hops out, leaving the lights flashing and the door open, and runs to the stand.
KAFFEE Hey, Luther.
LUTHER Admiral, how's the big case goin'?
KAFFEE Nose to the grindstone.
LUTHER No flies on you.
KAFFEE A rolling stone gathers no moss.
LUTHER Yeah, well it ain't over til the fat lady sings.
KAFFEE Ain't that the truth.
KAFFEE Catch you tomorrow.
He gets back in his car, tosses the newspaper on the passenger seat, and turns on the ignition.
And as soon as he does
-- a hand is slapped over his mouth --
VOICE It's Matthew Markinson.
-- and KAFFEE jumps out of his skin.
Because sitting in the back seat, in civilian clothes, is
KAFFEE Jesus fucking Christ!!--
MARKINSON You left the door unlocked.
KAFFEE Scared the shit outta me.
MARKINSON Drive.
KAFFEE Are you aware you're under subpoena?
MARKINSON Yes.
MARKINSON I'm also aware that the lives of two marines are in your hands.
MARKINSON If there was something I could do about that, I would, but since I can't, all I can do is help you.
MARKINSON Why don't you drive, Lieutenant.
KAFFEE begins driving down the street.
KAFFEE What do you know?
MARKINSON I know everything.
KAFFEE Was it a code red?
MARKINSON Yes.
KAFFEE Did Kendrick give the order?
MARKINSON Yes.
KAFFEE Did you witness it?
MARKINSON I didn't need to --
KAFFEE Did you witness it?!
MARKINSON No.
KAFFEE Then how do you know?
MARKINSON I know.
KAFFEE You know shit.
MARKINSON He was never gonna be transferred off the base.
And with this, KAFFEE screeches the car over to the side of the road.
He grabs the parking brake and pulls it up.
He turns to Markinson.
MARKINSON Jessep was going to keep him on the base.
MARKINSON He said he wanted him trained.
KAFFEE We've got the transfer order.
KAFFEE It's got your signature.
MARKINSON I know.
MARKINSON I signed it the morning you arrived in Cuba.
MARKINSON Six days after Santiago died.
KAFFEE's wheels are spinning.
He's pumped.
KAFFEE I'm gonna get you a deal.
KAFFEE Some kind of immunity with the prosecutor.
KAFFEE In about four days, you're gonna appear as a witness for the defense, and you're gonna tell the court exactly what you told me.
KAFFEE Right now I'm gonna check you into a motel, and we're gonna start from the beginning.
MARKINSON I don't want a deal.
MARKINSON And I don't want immunity.
KAFFEE shakes his head and laughs.
MARKINSON I want you to know, I'm proud neither of what I've done nor what I'm doing.
KAFFEE puts the car in gear and we
Where KAFFEE has just finished telling his story to an amazed SAM and JO.
There's silence.
Then JO has a total adrenaline rush.
JO Where is he?
KAFFEE The Route 23 Best Western.
JO picks up the phone.
JO I want him guarded.
KAFFEE That's probably a good idea.
JO This is Lt.
JO Commander Joanne Galloway.
JO My clearance code is 411273.
KAFFEE is impressed.
He turns to SAM --
KAFFEE Clearance code?
JO Thank you.
KAFFEE I don't have a clearance code.
KAFFEE Do you have a --
JO It's Jo Galloway.
JO I need to secure a witness.
Jo continues giving information to the person on the phone, while Kaffee keeps talking to the both of them.
Sam is writing down notes as fast as he can.
KAFFEE He also said that Jessep's lying about the transportation off the base.
KAFFEE Jessep said six the next morning was the first flight Santiago could've left on, Markinson says there was a plane that left seven hours earlier.
JO hangs up the phone.
JO Damn.
KAFFEE That was impressive.
KAFFEE Did you hear what I just said about the flight?
JO Yes.
KAFFEE Sam, when a plane takes off from a base, there's gotta be some kind of record kept, right?
SAM We need the Tower Chief's Log for
KAFFEE Get it.
JO We're gonna win.
KAFFEE Jo, don't get crazy about this.
KAFFEE We don't know who Markinson is.
KAFFEE We don't know what the log book's gonna say.
KAFFEE You just concentrate on Downey.
KAFFEE I'm gonna talk to Ross and tell him where we are.
JO "Kaffee's got his case now, Kaffee's got his case now."
KAFFEE You are like seven of the strangest women I have ever met.
A WAITRESS sets two drinks down in front of KAFFEE and ROSS, who are sitting across from each other in a booth in the back.
ROSS That was nice work today.
ROSS The redirect on Howard.
KAFFEE I have Markinson.
ROSS only takes a moment digest this.
ROSS Where is he?
KAFFEE A motel room in Arlington with 14 Federal Marshals outside his door.
KAFFEE Take a sip of your drink.
ROSS Damn.
KAFFEE The transfer order that Parkinson signed is phoney.
KAFFEE And Jessep's statement that the six a.m.
KAFFEE flight was the first available is a lie, we're checking the tower chief's log.
KAFFEE But in the meantime I'm gonna put the Apostle Jon Kendrick on the stand and see if we can't have a little fun.
ROSS takes another sip of his drink, then lays it on the line for Kaffee..
ROSS I have an obligation to tell you that if you accuse Kendrick or Jessep of any crime without proper evidence, you'll be subject to Court-Martial for professional misconduct.
ROSS And that's something that'll be stapled to every job application you ever fill out.
ROSS Markinson's not gonna hold up, he's a crazy man.
ROSS I'm not saying this to intimidate you.
ROSS I'm being your lawyer.
KAFFEE Thanks, Jack.
KAFFEE And I wanna tell you that I think the whole fuckin' bunch of you are certifiably insane.
KAFFEE And this code of honor of yours makes me wanna beat the shit outta something.
ROSS Don't you dare lump me in with Jessep and Markinson and Kendrick because we wear the same uniform.
ROSS I'm your friend, Danny, and I'm telling you, I don't think your clients belong in jail.
ROSS But I don't get to make that decision.
ROSS I represent the Government of the United States.
ROSS Without passion or prejudice.
ROSS And my client has a case.
ROSS I want you to acknowledge that the judge advocate has made you aware of the possible consequences involved in accusing a marine officer of a felony without proper evidence.
KAFFEE I've been so advised.
ROSS stands up and heaves a few dollars on the table.
ROSS You got bullied into that courtroom, Danny.
ROSS By everyone.
ROSS By Dawson, by Galloway, shit, I practically dared you.
ROSS Not for a second have you believed you could win.
ROSS You got bullied into that room by the memory of a dead lawyer.
KAFFEE You're a lousy softball player, Jack.
ROSS Your boys are going down.
ROSS I can't stop it anymore.
People are filing in.
KENDRICK is standing at the entrance to the courtroom.
KAFFEE glides past him...
KAFFEE Batter up, J.J.
KENDRICK watches this impudent thing walk into the courtroom as we
KENDRICK's on the stand.
What drives Kaffee's entire examination of Kendrick is this: Kaffee's got him.
He's gonna win.
At least this round.
All he has to do is not let his emotions take control of his professional skill.
SAM will have files and documents ready to hand Kaffee as he needs them.
KAFFEE Lt.
KAFFEE Kendrick, in your opinion, was Private Santiago a good marine?
KENDRICK I'd say he was about average.
KAFFEE Lieutenant, you signed three fitness reports on Santiago.
KAFFEE On all three reports you indicated a rating of Below Average.
KENDRICK Yes.
KENDRICK Private Santiago was Below Average I didn't see the need in trampling on a man's grave.
KAFFEE We appreciate that, but you're under oath now, and I think unpleasant as it may be, we'd all just as soon hear the truth.
KENDRICK I'm aware of my oath.
KAFFEE's handed some more files.
KAFFEE Lieutenant, these are the last three fitness reports you signed for Lance Corporal Dawson and PFC Downey.
KAFFEE Downey received three straight marks of Exceptional.
KAFFEE Dawson received two marks of Exceptional, but on this most recent report, dated June 9th of this year, he received a rating of Below Average.
KAFFEE It's this last report that I'd like to discuss for a moment.
KENDRICK That's fine.
KAFFEE Lance Corporal Dawson's ranking after Infantry Training School was perfect.
KAFFEE Records indicate that over half that class has since been promoted to full corporal, while Dawson has remained a lance corporal.
KAFFEE Was Dawson's promotion held up because of this last fitness report.
KENDRICK I'm sure it was.
KAFFEE Do you recall why Dawson was given such a poor grade on this report?
KENDRICK I'm sure I don't.
KENDRICK I have many men in my charge, Lieutenant, I write many fitness reports.
KAFFEE Do you recall an incident involving a PFC Curtis Barnes who'd been found stealing liquor from the Officer's Club?
KENDRICK Yes.
KAFFEE Did you report private Barnes to the proper authorities?
KENDRICK I have two books at my bedside, Lieutenant, the Marine Code of Conduct and the King James Bible.
KENDRICK The only proper authorities I'm aware of are my Commanding Officer, Colonel Nathan R.
KENDRICK Jessep and the Lord our God.
KAFFEE Lt.
KAFFEE Kendrick, at your request, I can have the record reflect your lack of acknowledgment of this court as a proper authority.
ROSS Objection.
ROSS Argumentative.
RANDOLPH Sustained.
RANDOLPH Watch yourself, counselor.
KAFFEE Did you report Private Barnes to your superiors?
KENDRICK I remember thinking very highly of Private Barnes, and not wanting to see his record tarnished by a formal charge.
KAFFEE You preferred it to be handled within the unit.
KENDRICK I most certainly did.
KAFFEE Lieutenant, do you know what a Code Red is?
KENDRICK Yes I do.
KAFFEE Have you ever ordered a code red?
KENDRICK No, I have not.
KAFFEE Lieutenant, did you order Dawson and two other men to make sure that Private Barnes receive no food or drink except water for a period of seven days?
KENDRICK That's a distortion of the truth.
KENDRICK Private Barnes was placed on barracks restriction.
KENDRICK He was given water and vitamin supplements, and I assure you that at no time was his health in danger.
KAFFEE I'm sure it was lovely for Private Barnes, but you did order the barracks restriction, didn't you?
KAFFEE And you did order the denial of food.
KENDRICK Yes.
KAFFEE Wouldn't this form of discipline be considered a code red?
KENDRICK Not necessarily.
KAFFEE If I called the other 8000 men at Guantanamo Bay to testify, would they consider it a Code Red?
ROSS Please the court, the witness can't possibly testify as to what 8000 other men would say.
ROSS We object to this entire line of questioning as argumentative and irrelevant badgering of the witness.
RANDOLPH The Government's objection is sustained, Lt.
RANDOLPH Kaffee, and I would remind you that you're now questioning marine officer with an impeccable service record.
ROSS Thank you judge.
KAFFEE looks over at DAWSON.
They share a brief moment before KAFFEE turns back to KENDRICK.
KAFFEE Lieutenant, was Dawson given a rating of Below Average on this last fitness report because you learned held been sneaking food to Private Barnes?
KAFFEE Not so fast.
KAFFEE Lieutenant?
KENDRICK Corporal Dawson was found to be Below Average because he committed a crime.
KAFFEE What crime did he commit?
KAFFEE Lieutenant Kendrick?
KAFFEE Dawson brought a hungry guy some food.
KAFFEE What crime did he commit?
KENDRICK He disobeyed an order.
KAFFEE And because he did, because he exercised his own set of values, because he made a decision about the welfare of a marine that was in conflict with an order of yours, he was punished, is that right?
KENDRICK Corporal Dawson disobeyed an order.
KAFFEE Yeah, but it wasn't a order, was it?
KAFFEE After all, it's peacetime.
KAFFEE He wasn't being asked to secure a hill...
KAFFEE or advance on a beachhead.
KAFFEE I mean, surely a marine of Dawson's intelligence can be trusted to determine on his own, which are the really important orders, and which orders might, say, be morally questionable.
KAFFEE Lt.
KAFFEE Kendrick?
KAFFEE Can he?
KAFFEE Can Corporal Dawson determine on his own which orders he's gonna follow?
KENDRICK No, he can not.
KAFFEE A lesson he learned after the Curtis Barnes incident, am I right?
KENDRICK I would think so.
KAFFEE You know so, don't you, Lieutenant.
ROSS Object!
RANDOLPH Sustained.
KAFFEE Lieutenant Kendrick, one final question: if you ordered Dawson to give Santiago a code red...
ROSS -- please the court --
KENDRICK I told those men not to touch Santiago.
KAFFEE -- is it reasonable to think that he would've disobeyed you again?
ROSS Lieutenant, don't answer that.
KAFFEE You don't have to, I'm through.
ROSS doesn't even wait before he says --
ROSS Lieutenant Kendrick, did you order Corporal Dawson and Private Downey to give Willy Santiaga code red?
But KENDRICK isn't listening -- he's glaring at Kaffee.
ROSS Lt.
ROSS Kendrick, did you --
KENDRICK No I did not.
ROSS Thank you.
FWAP!
- a nerf ball slams into a hoop.
JO and KAFFEE.
KAFFEE's pumped and shooting baskets as Sam walks in with some bound papers under his arm.
KAFFEE What's the word?
SAM This is the tower chief's log for that night.
SAM Jessep was telling the truth.
SAM The six a.m.
SAM flight was the first plane out.
KAFFEE lets the ball drop out of his hands.
KAFFEE Let me see that.
A SEDAN, with U.S. MARSHALL stenciled on the door, sits in front of one of the rooms, and the two FEDERAL AGENTS inside the car are reading the newspaper as KAFFEE'S CAR pulls next to them and KAFFEE jumps out.
AGENT #1 sticks his head out the window and calls to KAFFEE --
AGENT #1 Workin' late, lieutenant?
KAFFEE pays no attention and bangs on MARKINSON's door.
The door opens and KAFFEE walks into
HE tosses the log book on the table.
KAFFEE There was no flight out at eleven o'clock.
KAFFEE What the fuck are you trying to pull?
MARKINSON The first flight stateside left Guantanamo Bay at eleven and arrived at Andrews Airforce Base, Maryland, at a few minutes past two.
KAFFEE Then why the hell isn't it listed in the Tower Chief's log?!
MARKINSON Why the hell did you think it would be?!!
KAFFEE is silent.
And now it begins to sink in.
KAFFEE What are you telling me?
KAFFEE He fixed the log book?
Setback.
Big setback.
KAFFEE Well, maybe he can make it so a plane didn't take off, but I can sure as hall prove that one landed.
KAFFEE I'll get the log book from Andrews.
MARKINSON says nothing.
But his face says that KAFFEE was born yesterday.
KAFFEE He made an entire flight disappear?
MARKINSON Nathan Jessep is about to be named Director of Operations for the National Security Council.
MARKINSON You don't get to that position without knowing how to side-step a few land mines.
MARKINSON And putting me on the stand isn't gonna make him step on one.
KAFFEE stares at him.
Then shakes his head, sighs, and picks the log book up off the table, and heads for the door.
KAFFEE You're taking the stand.
KAFFEE Thursday.
KAFFEE leaves.
HOLD on MARKINSON.
KAFFEE'S APARTMENT later that night and SAM and J0 have just heard the report him.
KAFFEE There's gotta be someone who can testify to the flight.
KAFFEE A ground crew member.
KAFFEE Someone.
SAM Do you have any idea how many planes take off and land every day?
SAM A kid from the ground crew isn't gonna remember a flight that landed four weeks ago.
KAFFEE Forget the flight.
KAFFEE We'll put Markinson on the stand and we'll deal with Jessep's refusal to transfer Santiago and he'll testify to the forged transfer order.
KAFFEE That'll be enough.
KAFFEE That and Downey's testimony really oughta be enough.
Jo is working with DOWNEY.
He sits on a mock witness stand.
JO Private Downey, why did you go into Santiago's room on the night of the 6th?
DOWNEY To give Private Santiago a Code Red, ma'am.
JO And why did you give him a Code Red?
DOWNEY I was ordered to give him a Code Red by the Executive officer for Rifle Security Company Windward, Lieutenent Jonathan James Kendrick.
JO smiles.
JO You're gonna do fine.
DOWNEY smiles.
DOWNEY You think they'll let us go back to our platoon soon, ma'am?
JO Absolutely.
Jo is going over last-minute details with KAFFEE.
JO You remember the order of the questions?
KAFFEE Yes.
JO Are you sure?
KAFFEE Yes.
JO And you'll use small words?
KAFFEE Yes.
JO He gets rattled when he doesn't understand something.
KAFFEE Jo --
JO I'm just saying go slow.
KAFFEE I'm gonna go slow.
JO Okay.
KAFFEE Alright.
JO And get him off as fast as you can.
KAFFEE Joanne!
JO What?
KAFFEE He's gonna be fine.
They turn and head into the courtroom as we HEAR MARKINSON in VOICE OVER...
MARKINSON (V.O.) "Dear Mr. and Mrs. Santiago..."
MARKINSON is writing a letter and we HEAR it in V.O.
MARKINSON (V.O.) I was William's company commander.
MARKINSON (V.O.) I knew your son vaguely, which is to say I knew his name...
And while we continue to HEAR Markinson's voice writing the letter, we begin a SERIES OF SHOTS: MARKINSON is getting into his class A dress uniform, complete with medals, side arm, and military dress sabre.
MARKINSON (V.O.) In a matter of time, the trial of the two man charged with your son's death will be concluded, and seven men and two women whom you've never met will try to offer you an explanation as to why William is dead.
MARKINSON (V.O.) For my part, I've done as much as I can to bring the truth to light.
MARKINSON is finished dressing.
He stands in the middle of the motel room.
MARKINSON (V.O.) And the truth is this: your son is dead for only one reason.
MARKINSON (V.O.) I wasn't strong enough to stop it.
MARKINSON takes a pistol out of his holster and cocks the trigger.
MARKINSON (V.O.) Always, Captain Matthew Andrew Markinson.
MARKINSON puts the pistol in his mouth --
MARKINSON (V.O.) United states marine corps.
We HEAR the BLAST of the gunshot as we
Kaffee is at the end of his examination of Downey.
KAFFEE Private, I want you to tell us one last time: Why did you go into Private Santiago's room on the night of August 6th?
DOWNEY A code red was ordered by my platoon commander, Lt.
DOWNEY Jonathan James Kendrick.
KAFFEE Thank you.
KAFFEE Your witness.
ROSS Private, for the week of 2 August, the switch log has you down at Post 39, is that correct?
DOWNEY I'm sure it is, sir, they keep that log pretty good.
ROSS How far is it from Post 39 to the Windward barracks?
DOWNEY It's a ways, sir, it's a hike.
ROSS About how far by jeep?
DOWNEY About ten, fifteen minutes, sir.
ROSS Have you ever had to walk it?
DOWNEY Yes sir.
DOWNEY That day, sir.
DOWNEY Friday.
DOWNEY The Pick-up Private -- sir, that's what we call the fella who drops us at our posts and picks us up...
DOWNEY also, 'cause he can get girls in New York City -- the Pick-up Private got a flat...
At the defense table, KAFFEE, poker-faced, scribbles something down on a piece of paper and slides it to JO.
JO looks at it:
"Where's he going with this?" JO scribbles "?" And hands it back to KAFFEE.
DOWNEY ...Right at 39.
DOWNEY He pulled up and blam!
DOWNEY ...A blowout-with no spare.
DOWNEY The two of us had to double-time it back to the barracks.
ROSS And if it's ten or fifteen minutes by jeep, I'm guessing it must be a good hour by foot, am I right?
DOWNEY Pick-up and me did it in 45 flat, sir.
ROSS Not bad.
ROSS Now you say your assault on Private Santiago was the result of an order that Lt.
ROSS Kendrick gave in your barracks room at 16:20.
KAFFEE knows what's coming.
There's nothing he can do about it.
And he can't lose his cool in front of the jury.
DOWNEY Yes sir.
JO.
Helpless.
Panicked.
ROSS But you just said that you didn't make it back to Windward Barracks until 16:45.
DOWNEY's confused.
These are questions he hasn't been asked before.
DOWNEY Sir?
ROSS If you didn't make it back to your barracks until 16:45, then how could you be in your room at 16:20?
DOWNEY You see sir, there was a flat tire.
ROSS Private, did you ever actually hear Lt.
ROSS Kendrick order a Code Red?
KAFFEE's world is falling down around him, and there's nothing he can do about it.
And he knows it.
DOWNEY No, sir.
Jo leaps to her feet.
JO Please the court, I'd like to request a recess in order to confer with my client.
ROSS Why did you go into Santiago's room?
JO The witness has rights.
ROSS The witness has been read his rights, commander.
DOWNEY Hal?
RANDOLPH The question will be repeated.
ROSS Why did you go into Santiago's room?
JO Your honor --
DOWNEY Hal?
ROSS Did Corporal Dawson tell you to do it?
Everyone is frozen.
ROSS He did, didn't he?
ROSS Dawson told you to give Santiago a code red.
DOWNEY looks at DAWSON.
DOWNEY Hal?
ROSS Don't look at him.
DOWNEY Hal?
DAWSON Private.
DAWSON Answer the Lieutenant's question.
The room is still silent.
DOWNEY does something we've never seen him do before.
He straightens himself up and says this with the pride of a man who believes he's done the right thing.
DOWNEY Yes, Lieutenant.
DOWNEY I was given an order by my squad leader, Lance Corporal Harold W. Dawson of the U.S. Marine Corps.
DOWNEY And I followed it.
ROSS let's it hang.
He looks over at KAFFEE.
KAFFEE won't meet his eyes.
JO and SAM are sitting in silence.
It's dark outside.
JO Where do you think he is?
SAM doesn't know.
JO is beside herself, and trying to keep it together.
JO As far as Downey was concerned, it was an order from Kendrick.
JO It didn't matter that he didn't hear it first hand.
JO He doesn't distinguish between the two.
SAM understands, but he doesn't say anything.
The door opens and KAFFEE walks in.
JO Danny.
JO I'm sorry.
KAFFEE seems to be in an incredibly normal mood.
KAFFEE Don't worry about it.
JO Sam and I were just talking about how all we really have to do is call some witnesses who'll talk about implied orders...
JO or maybe we put Downey back on the stand before we get to Dawson.
KAFFEE Maybe if we work at it we can get Dawson charged with the Kennedy assassination.
JO studies KAFFEE for a moment.
JO Are you drunk?
KAFFEE Pretty much.
KAFFEE Yeah.
JO I'll make a pot of coffee.
JO We have a long night's work ahead.
KAFFEE She's gonna make coffee.
KAFFEE That's nice.
KAFFEE He wasn't in his room.
KAFFEE He wasn't even there.
KAFFEE That was an important piece of information, don't you think?
JO Danny, it was just a setback.
JO I'm sorry.
JO But we'll fix it and then move on to Markinson.
KAFFEE Markinson's dead.
JO and SAM are frozen.
KAFFEE says this with no particular feeling one way or the other.
KAFFEE You really gotta hand it to those Federal Marshals, boy.
KAFFEE It's not like he hanged himself by his shoelaces or slashed his wrists with a concealed butter knife.
KAFFEE This guy got, into full dress uniform, stood in the middle of that room, drew a nickle plated pistol from his holster, and fired a bullet into his mouth.
Jo and SAM don't say anything.
KAFFEE Anyway, since we seem to be out of witnesses, I thought I'd drink a little.
JO I still think we can win.
KAFFEE Then maybe you should drink a little.
JO Look, we'll go to Randolph in the morning and make a motion for a continuance.
JO 24 hours.
KAFFEE Why would we want to do that?
JO To subpoena Colonel Jessep.
KAFFEE What?
JO Listen for a second --
KAFFEE No.
JO Just hear me out --
KAFFEE No.
KAFFEE I won't listen to you and I won't hear you out.
KAFFEE Your passion is comforting, Jo.
KAFFEE It's also useless.
KAFFEE Private Downey needed a trial lawyer today.
JO You chicken-shit.
JO You're gonna use what happened today as an excuse to give up.
KAFFEE It's over!
JO Why did you ask Jessep for the transfer order?
KAFFEE What are you --
JO In Cuba.
JO Why did you ask Jessep for the transfer order?
KAFFEE What does it matter --
JO Why?!
KAFFEE I wanted the damn transfer order!
JO Bullshit!
JO You could've gotten it by picking up the phone and calling any one of a dozen departments at the Pentagon.
JO You didn't want the transfer order.
JO You wanted to see Jessep's reaction when you asked for the transfer order.
JO You had an instinct.
JO And it was confirmed by Markinson.
JO Now damnit, let's put Jessep on the stand and end this thing!
KAFFEE What possible good could come from putting Jessep on the stand?
JO He told Kendrick to order the Code Red.
KAFFEE He did?!
KAFFEE Why didn't you say so!?
KAFFEE That's qreat!
KAFFEE And of course you have proof of that.
KAFFEE Ah, I keep forgetting: You were sick the day they taught law at law school.
JO You put him on the stand and you get it from him!
KAFFEE Yes.
KAFFEE No problem.
KAFFEE We get it from him.
KAFFEE Colonel, isn't it true that you ordered the Code Red on Santiago?
SAM Look, we're all a little --
KAFFEE I'm sorry, your time's run out.
KAFFEE What do we have for the losers, Judge?
KAFFEE Well, for our defendants it's a lifetime at exotic Fort Levenworth.
KAFFEE And for defense counsel Kaffee?
KAFFEE That's right -- it's -- a court -- martial.
KAFFEE Yes, Johnny, after falsely accusing a marine officer of conspiracy, Lt.
KAFFEE Kaffee will have a long and prosperous career teaching typewriter maintenance at the Rocco Columbo School for Women.
KAFFEE Thank you for playing "Should We or Should-We-Not Follow the Advice of the Galacticly Stupid".
And with one motion, he knocks everything from his desk.
A ton of papers, books, files, etc., falls to the floor.
There's dead silence.
Maybe just the sound of KAFFEE breathing after this exhausting outburst.
Finally...
JO I'm sorry I lost you your set of steak knives.
Jo picks up her purse and coat and walks out.
The door slams behind her.
KAFFEE walks into the kitchen without a word.
SAM gets down on the floor and begins picking up all the stuff that Kaffee knocked off the desk.
KAFFEE comes back in with a bottle of Jack Daniels.
KAFFEE Stop cleaning up.
But Sam continues.
KAFFEE Sam.
KAFFEE Stop cleaning up.
SAM stops and sits in a chair.
KAFFEE sits on the couch.
KAFFEE You want a drink?
SAM Yeah.
SAM takes a swig from the bottle.
KAFFEE Is your father proud of you?
SAM Don't do this to yourself.
KAFFEE I'll bet he is.
KAFFEE I'll bet he bores the shit outta the neighbors and the relatives.
KAFFEE "Sam, made Law Review.
KAFFEE He's got a big case he's making -- He's arguing making an argument."
KAFFEE I think my father would've enjoyed seeing me graduate from law school.
KAFFEE I think he would've liked that...
KAFFEE an awful lot.
SAM Did I ever tell you that I wrote a paper on your father in college?
KAFFEE Yeah?
SAM He was one of the best trial lawyers ever.
KAFFEE Yes he was.
SAM And if I were Dawson and Downey and I had a choice between you or your father to represent me in this case, I'd take you any day of the week and twice on Sunday.
SAM You should have seen yourself thunder away at Kendrick.
KAFFEE Would you put Jessep on the stand?
SAM No.
KAFFEE You think my father would've?
SAM With the evidence we've got?
SAM Not in a million years.
SAM But here's the thing -- and there's really no way of getting around this -- neither Lionel Kaffee nor Sam Weinberg are lead counsel for the defense in the matter of U.S.
SAM versus Dawson and Downey.
SAM So there's only one question.
SAM What would you do?
We HOLD on the two of them for a moment, then
JO is walking through the night at a brisk pace.
She's doing her best not to fall apart.
TWO HEADLIGHTS appear coming down the street, and KAFFEE's CAR, with SAM driving and KAFFEE riding shotgun, slows down alongside JO.
KAFFEE rolls down his window.
KAFFEE Joanne.
JO ignores them and keeps walking.
The car crawls along with her.
JO starts walking faster.
KAFFEE Jo, we look ridiculous.
KAFFEE Stop the car.
KAFFEE hops out and calls --
KAFFEE Joanne.
JO keeps walking.
KAFFEE I apologize.
KAFFEE I was angry and...
KAFFEE I'm sorry about what I said.
But JO'S still walking.
KAFFEE I'm gonna put Jessep on the stand.
She stops.
She turns around.
A nerf ball bounces off the wall.
KAFFEE, JO and SAM are sprawled out in the living room.
For hours now they've been trying to come up with an idea.
KAFFEE's mind seems to be on his basketball game.
JO I say we hit him with the phoney transfer order.
SAM What's the transfer order without a witness?
KAFFEE We have a witness.
SAM A dead witness.
KAFFEE And in the hands of a lesser attorney, that'd be a problem.
SAM Look at this.
SAM Last night he was swimming in his Jack Daniels, now he can leap tall buildings in a single bound.
KAFFEE I'm getting my second wind.
KAFFEE Siddown.
KAFFEE Both of you.
He sees that SAM and JO were already sitting down.
KAFFEE Good.
KAFFEE Jessep told Kendrick to order a code red.
KAFFEE Kendrick did, and our clients followed the order.
KAFFEE The cover-up isn't our case.
KAFFEE To win, Jessep has to tell the jury that he ordered the code red.
SAM And you think you can got him to just say it?
KAFFEE I think he wants to say it.
KAFFEE I think he's pissed off that he's gotta hide from us.
KAFFEE I think he wants to say that he made a command decision and that's the end of it.
KAFFEE He eats breakfast 80 yards away from 4000 Cubans who are trained to kill him, and no one's gonna tell him how to run his base.
KAFFEE Least of all the pushy broad, the smart Jew, and the Harvard clown.
KAFFEE I need to shake him and put him on the defensive.
SAM and JO are silent for a moment.
SAM That's it?
SAM That's the plan?
KAFFEE That's the plan.
SAM You're gonna trip Jessep and he's gonna confess.
KAFFEE I'm not gonna trip him.
KAFFEE I'm gonna lead him right where he's dying to go.
SAM And how are you gonna do that?
KAFFEE I have no idea.
KAFFEE I need my bat.
JO What?
KAFFEE I need my bat.
KAFFEE I think better with my bat.
KAFFEE Where's my bat?
JO I put it in the closet.
KAFFEE You put it in the closet.
KAFFEE heads to the closet.
JO I was tripping over it.
KAFFEE Don't ever put a bat in a closet.
JO He thinks better with his bat?
And we go to KAFFEE AT THE CLOSET.
SAM I can understand that.
SAM I used to have stuffed panda named Mr. Boob.
SAM I could never do my home work without him.
During this, KAFFEE's opened the closet door.
He reaches in to grab his bat when all of a sudden he notices something:
His clothes.
His uniforms and his civilian clothes.
Hanging neatly along the bar.
He stares at this a moment, then suddenly heads back through the living room towards the front door.
KAFFEE Stay here, I'm going to the office for a while.
KAFFEE storms out.
SAM Boy, he does think better with that bat.
A small room at the end of a corridor at the office.
KAFFEE stands over a printer and watches it spit out something he's been waiting for.
He tears the printout off and we
KAFFEE is looking over the computer printout.
From what we can tell, it resembles a large, military coded phone bill.
KAFFEE picks up the phone and dials.
KAFFEE Sam.
KAFFEE I need you to do something.
SAM hangs up the phone slowly.
JO What's goin' on?
SAM I've gotta go out to Andrews.
The day's session is going to begin in a few minutes.
KAFFEE comes around the corner and runs into Jo.
KAFFEE Is Sam here?
JO Not yet.
KAFFEE Where is he?
JO He's on his way.
KAFFEE Did he got the guys?
JO Yes.
JO Listen, can I talk to you for a second?
JO closes the door behind them.
JO How're you feeling?
KAFFEE I think he's gonna have his hands full today.
JO Listen.
JO Danny.
JO When you're out there.
JO If it's not gonna happen he's not gonna say it
JO ...don't go for it.
KAFFEE looks at her.
JO If you feel like...
JO if you feel like...
JO You could get in trouble.
JO I'm special counsel for internal affairs, and I'm telling you, you could get in a lot of trouble.
KAFFEE Why Lt.
KAFFEE Commander Galloway...
KAFFEE are you suggesting I back off a material witness?
JO If you think you can't get him.
JO Yeah.
KAFFEE Do you think I can get him?
JO I think it doesn't matter what I think.
JO I'm an administrator.
JO I can't seem to defend people.
KAFFEE takes that in.
He picks up his briefcase and grabs his jacket.
Then he turns to JO.
KAFFEE You're my hero, Joanne.
KAFFEE From the first day, you were a lawyer.
KAFFEE Live with that.
And in VOICE OVER we HEAR the SERGEANT AT ARMS.
SERGEANT AT ARMS (V.O.) All rise.
Everyone stands at attention as RANDOLPH enters.
SAM is missing.
RANDOLPH Call your witness.
KAFFEE Where's Sam?
JO He'll be here.
RANDOLPH Lieutenant, call your witness.
KAFFEE Defense calls Colonel Nathan Jessep.
JESSEP is escorted in through a side door.
He's wearing his dress uniforms, adorned with the appropriate medals.
ROSS Colonel, do you solemnly swear that the testimony you will give in this General Court-Martial will be the truth, the whole truth, and nothing but the truth so help you God?
JESSEP Yes I do.
ROSS Would you state your name, rank, and current billet for the record please, air?
JESSEP Colonel Nathan R. Jessep, Commanding officer, Marine Ground Forces, Guantanamo Bay, Cuba.
ROSS Thank you, sir, would you have a seat, please.
JESSEP sits.
KAFFEE Colonel, when you learned of Santiago's letter to the NIS, you had a meeting with your two senior officers, is that right?
JESSEP Yes.
KAFFEE The Executive Officer, Lt.
KAFFEE Jonathan Kendrick, and the Company Commander, Captain Matthew Markinson.
JESSEP Yes.
KAFFEE And at present, Captain Markinson is dead, is that right?
ROSS Objection.
ROSS I'd like to know just what defense counsel is implying?
KAFFEE I'm implying simply that, at present, Captain Markinson is not alive.
ROSS Surely Colonel Jessep doesn't need to appear in this courtroom to confirm that information.
KAFFEE I just wasn't sure if the witness was aware that two days ago, Captain Markinson took his own life with a .45 caliber pistol.
And from the back of the room, SAM enters.
He's escorting two young AIRMEN in Airforce dress uniforms.
SAM shows the AIRMEN to a seat near the front, and takes his place at the defense table.
Over this we HEAR --
RANDOLPH The witness is aware, the Court is aware, and now the jury is aware.
RANDOLPH We thank you for bringing this to our attention.
RANDOLPH Move on Lieutenant.
SAM scribbles something on a piece of paper, KAFFEE walks over, looks at the paper on which are wrttten two names: Cecil O'Malley and Anthony Perez, then turns back to RANDOLPH.
KAFFEE Yes sir.
KAFFEE Colonel, at the time of this meeting, you gave Lt.
KAFFEE Kendrick an order, is that right?
JESSEP I told Kendrick to tell his men that Santiago wasn't to be touched.
KAFFEE And did you give an order to Captain Markinson as well?
JESSEP I ordered Markinson to have Santiago transferred off the base immediately.
KAFFEE Why?
JESSEP I felt that his life might be in danger once word of the letter got out.
KAFFEE Grave danger?
JESSEP Is there another kind?
KAFFEE holds up a document from his table.
KAFFEE We have the transfer order that you and Markinson co-signed, ordering that Santiago be lifted on a flight leaving Guantanamo at six the next morning.
KAFFEE Was that the first flight off the bass?
JESSEP The six a.m.
JESSEP flight was the first flight off the base.
KAFFEE nods and decides to move on.
JESSEP steals a quick glance at the two AIRMEN sitting out in the courtroom.
KAFFEE Colonel, you flew up to Washington early this morning, is that right?
JESSEP Yes.
KAFFEE I notice you're wearing your Class A appearance in dress uniform for court today.
JESSEP As are you, Lieutenant.
KAFFEE Did you wear that uniform on the plane?
ROSS Please the Court, is this dialogue relevant to anything in particular?
KAFFEE The defense didn't have an opportunity to depose this witness, your honor.
KAFFEE I'd ask the Court for a little latitude.
RANDOLPH A very little latitude.
KAFFEE Colonel?
JESSEP I wore fatigues on the plane.
KAFFEE And you brought your dress uniform with you.
JESSEP Yes.
KAFFEE And a toothbrush?
KAFFEE A shaving kit?
KAFFEE Change of underwear?
ROSS Your honor.
KAFFEE Is the Colonel's underwear a matter of national security?
RANDOLPH Gentlemen.
RANDOLPH You better get somewhere fast with this, Lieutenant.
KAFFEE Yes sir.
KAFFEE Colonel?
JESSEP I brought a change of clothes and some personal items.
KAFFEE Thank you.
KAFFEE gets a document from his table.
KAFFEE After Dawson and Downey's arrest on the night of the sixth, Santiago's barracks room was sealed off and its contents inventoried.
KAFFEE Pairs of camouflage pants, 6 camouflage shirts, 2 pairs of boots, 1 pair of brown shoes, 1 pair of tennis shoes, 8 khaki tee-shirts, 2 belts, 1 sweater --
ROSS Please the Court, is there a question anywhere in our future?
RANDOLPH Lt.
RANDOLPH Kaffee, I have to --
KAFFEE I'm wondering why Santiago wasn't packed.
That landed.
On the JURY, RANDOLPH, ROSS...
KAFFEE I'll tell you what, we'll get back to that one in a minute.
JO hands KAFFEE the computer printout.
KAFFEE This is a record of all telephone calls made from your base in the past 24 hours.
KAFFEE After being subpoenaed to Washington, you made three calls.
Handing Jessep the printout --
KAFFEE I've highlighted those calls in yellow.
KAFFEE Do you recognize those numbers?
JESSEP I called Colonel Fitzhuqhes in Quantico, Va.
JESSEP I wanted to let him know I'd be in town.
JESSEP The second call was to set up a meeting with Congressman Ramond of the House Armed Services Committee, and the third call was to my sister Elizabeth.
KAFFEE Why did you make that call, sir?
JESSEP I thought she might like to have dinner tonight.
ROSS Judge --
RANDOLPH I'm gonna put a stop to this now.
Jo's handed KAFFEE another printout and a stack of letters.
KAFFEE Your honor, these are the telephone records from GITMO for August 6th.
KAFFEE And these are 14 letters that Santiago wrote in nine months requesting, in fact begging, for a transfer.
KAFFEE Upon hearing the news that he was finally getting his transfer, Santiago was so excited, that do you know how many people he called?
KAFFEE Zero.
KAFFEE Nobody.
KAFFEE Not one call to his parents saying he was coming home.
KAFFEE Not one call to a friend saying can you pick me up at the airport.
KAFFEE He was asleep in his bed at midnight, and according to you he was getting on a plane in six hours, yet everything he owned was hanging neatly in his closet and folded neatly in his footlocker.
KAFFEE You were leaving for one day and you packed a bag and made three phone calls.
KAFFEE Santiago was leaving for the rest of his life, and he hadn't called a soul and he hadn't packed a thing.
KAFFEE Can you explain that?
KAFFEE The fact is there was no transfer order.
KAFFEE Santiago wasn't going anywhere, isn't that right, Colonel.
ROSS Object.
ROSS Your Honor, it's obvious that Lt.
ROSS Kaffee's intention this morning is to smear a high ranking marine officer in the desperate hope that the mere appearance of impropriety will win him points with the jury.
ROSS It's my recommendation, sir, that Lt.
ROSS Kaffee receive an official reprimand from the bench, and that the witness be excused with the Court's deepest apologies.
RANDOLPH ponders this a moment.
RANDOLPH Overruled.
ROSS Your honor --
RANDOLPH The objection's noted.
KAFFEE Colonel?
Jessep's smiling...
...and now he can't help but let out a short laugh.
KAFFEE Is this funny, sir?
JESSEP No.
JESSEP It's not.
JESSEP It's tragic.
KAFFEE Do you have an answer?
JESSEP Absolutely.
JESSEP My answer is I don't have the first damn clue.
JESSEP Maybe he was an early morning riser and he liked to pack in the nq.
JESSEP And maybe he didn't have any friends.
JESSEP I'm an educated man, but I'm afraid I can't speak intelligently about the travel habits of William Santiago.
JESSEP What I do know is that he was set to leave the base at 0600.
JESSEP Now are these really the questions I was called here to answer?
JESSEP Phone calls and footlockers?
JESSEP Please tell me you've got something more, Lieutenant.
JESSEP Please tell me there's an ace up your sleeve.
JESSEP These two marines are on trial for their lives.
JESSEP Please tell me their lawyer hasn't pinned their hopes to a phone bill.
JESSEP Do you have any other questions for me, counselor?
The courtroom is silenced.
Jessep's slammed the door.
KAFFEE looks around the room, sees that the world is waiting for him to do something...
RANDOLPH Lt.
RANDOLPH Kaffee?
KAFFEE says nothing.
He glances over to AIRMEN O'MALLEY and
RANDOLPH Lieutenant, do you have anything further for this witness?
KAFFEE doesn't respond.
JESSEP gets up to leave.
JESSEP Thanks, Danny.
JESSEP I love Washington.
And JESSEP starts to leave, but he's stopped by --
KAFFEE Excuse me, I didn't dismiss you.
JESSEP turns around.
JESSEP I beg your pardon.
KAFFEE I'm not through with my examination.
KAFFEE Sit down.
JESSEP Colonel.
KAFFEE What's that?
JESSEP I'd appreciate it if he addressed me as Colonel or Sir.
JESSEP I believe I've earned it.
RANDOLPH Defense counsel will address the witness as Colonel or Sir.
JESSEP I don't know what the hell kind of an outfit you're running here.
RANDOLPH And the witness will address this Court as Judge or Your Honor.
RANDOLPH I'm quite certain I've earned it.
RANDOLPH Take your seat, Colonel.
Jessep goes back to the stand.
JESSEP What would you like to discuss now!
JESSEP My favorite color?
KAFFEE Colonel, the six a.m.
KAFFEE flight, was the first one off the base?
JESSEP Yes.
KAFFEE There wasn't a flight that left seven hours earlier and landed at Andrews Airforce Base at 2 a.m.?
RANDOLPH Lieutenant, I think we've covered this, haven't we?
KAFFEE gets the two log books from his table as well as the piece of paper that SAM scribbled on.
KAFFEE Your Honor, these are the Tower Chief's Logs for both Guantanamo Bay and Andrews Airforce Base.
KAFFEE The Guantanamo log lists no flight that left at eleven p.m., and the Andrews log lists no flight that landed at 2 a.m.
KAFFEE I'd like to admit them as Defense Exhibits "A" and "B".
RANDOLPH I don't understand.
RANDOLPH You're admitting evidence of a flight that never existed?
KAFFEE We believe it did, sir.
KAFFEE Defense'll be calling Airman Cecil O'Malley and Airman Anthony Perez.
KAFFEE They were working the ground crew at Andrews at two a.m.
KAFFEE on the seventh.
ROSS Your Honor, these men weren't on the list.
ROSS Rebuttal witnesses, Your Honor, called specifically to refute testimony offered under direct examination.
If you looked closely at JESSEP, you could see a drop of sweat.
RANDOLPH I'll allow the witnesses.
JESSEP This is ridiculous.
KAFFEE Colonel, a moment ago --
JESSEP Check the Tower Logs for christ's sake.
KAFFEE We'll get to the airmen in just a minute, sir.
KAFFEE A moment ago said that you ordered Kendrick to order his men not to touch Santiago.
JESSEP That's right.
KAFFEE And Kendrick was clear on what you wanted?
JESSEP Crystal.
KAFFEE Any chance Kendrick ignored the order?
JESSEP Ignored the order?
KAFFEE Any chance he just forgot about it?
JESSEP No.
KAFFEE Any chance Kendrick left your office and said, "The 'old man's wrong"?
JESSEP No.
KAFFEE When Kendrick spoke to the platoon and ordered them not to touch Santiago, any chance they ignored him?
JESSEP Have you ever spent time in an infantry unit, son?
KAFFEE No sir.
JESSEP Ever served in a forward area?
KAFFEE No sir.
JESSEP Ever put your life in another man's hands, ask him to put his life in yours?
KAFFEE No sir.
JESSEP We follow orders, son.
JESSEP We follow orders or people die.
JESSEP It's that simple.
JESSEP Are we clear?
KAFFEE Yes sir.
JESSEP Are we clear?
KAFFEE Crystal.
KAFFEE speaks with the quiet confidence that comes from knowing you're about to drop your opponents
KAFFEE Colonel, I have just one more question before I call Airman O'Malley and Airman Perez: If you gave an order that Santiago wasn't to be touched, and your orders are always followed, then why would he be in danger, why would it be necessary to transfer him off the base?
And JESSEP has no answer.
Nothing.
He sits there, and for the first time, seems to be lost.
JESSEP Private Santiago was a sub-standard marine.
JESSEP He was being transferred off the base because --
KAFFEE But that's not what you said.
KAFFEE You said he was being transferred because he was in grave danger.
JESSEP Yes.
JESSEP That's correct, but --
KAFFEE You said, "He was in danger".
KAFFEE I said, "Grave danger".
KAFFEE You said --
JESSEP Yes, I recall what --
KAFFEE I can have the Court Reporter read back your --
JESSEP I know what I said.
JESSEP I don't need it read back to me like I'm a damn --
KAFFEE Then why the two orders?
KAFFEE Colonel?
KAFFEE Why did you --
JESSEP Sometimes men take matters into their own hands.
KAFFEE No sir.
KAFFEE You made it clear just a moment ago that your men never take matters into their own hands.
KAFFEE Your men follow orders or people die.
KAFFEE So Santiago shouldn't have been in any danger at all, should he have, Colonel?
Everyone's sweating now.
Everyone but KAFFEE.
JESSEP You little bastard.
ROSS Your Honor, I have to ask for a recess to --
KAFFEE I'd like an answer to the question, Judge.
RANDOLPH The Court'll wait for answer.
KAFFEE If Kendrick told his men that Santiago wasn't to be touched, then why did he have to be transferred?
Jessep is looking at O'MALLEY and PEREZ.
KAFFEE Colonel?
JESSEP says nothing.
KAFFEE Kendrick ordered the code red, didn't he?
KAFFEE Because that's what you told Kendrick to do.
ROSS Object!
RANDOLPH Counsel.
KAFFEE will plow through the objections of ROSS and the admonishments of RANDOLPH.
KAFFEE And when it went bad, you cut these guys loose.
ROSS Your Honor --
RANDOLPH That'll be all, counsel.
KAFFEE You had Markinson sign a phony transfer order --
ROSS Judge --
KAFFEE You doctored the log books.
ROSS Damnit Kaffee!!
KAFFEE I'll ask for the forth time.
KAFFEE You ordered --
JESSEP You want answers?
KAFFEE I think I'm entitled to them.
JESSEP You want answers?!
KAFFEE I want the truth.
JESSEP You can't handle the truth!
And nobody moves.
JESSEP Son, we live in a world that has walls.
JESSEP And those walls have to be guarded by men with guns.
JESSEP Who's gonna do it?
JESSEP You?
JESSEP You, Lt.
JESSEP Weinberg?
JESSEP I have a greater responsibility than you can possibly fathom.
JESSEP You weep for Santiago and you curse the marines.
JESSEP You have that luxury.
JESSEP You have the luxury of not knowing what I know: That Santiago's death, while tragic, probably saved lives.
JESSEP And my existence, while grotesque and incomprehensible to you, saves lives.
JESSEP You don't want the truth.
JESSEP Because deep down, in places you don't talk about at parties, you want me on that wall.
JESSEP You need me there.
JESSEP We use words like honor, code, loyalty...
JESSEP we use these words as the backbone to a life spent defending something.
JESSEP You use 'em as a punchline.
JESSEP I have neither the time nor the inclination to explain myself to a man who rises and sleeps under the blanket of the very freedom I provide, then questions the manner in which I provide it.
JESSEP I'd prefer you just said thank you and went on your way.
JESSEP Otherwise, I suggest you pick up a weapon and stand a post.
JESSEP Either way, I don't give a damn what you think you're entitled to.
KAFFEE Did you order the code red?
JESSEP I did the job you sent me to do.
KAFFEE Did you order the code red?
JESSEP You're goddamn right I did.
Silence.
From everyone.
RANDOLPH, ROSS, the M.P.'s, they're all frozen.
JO and SAM are likewise.
JESSEP seems strangely, quietly relieved.
KAFFEE simply takes control of the room now.
KAFFEE Please the court, I suggest the jury be dismissed so that we can move to an immediate Article 39a Session.
KAFFEE The witness has rights.
Silence.
RANDOLPH looks to ROSS.
RANDOLPH Lt.
RANDOLPH Ross?
ROSS is frozen.
He doesn't know what to do.
KAFFEE Jack.
ROSS looks at KAFFEE, then JESSEP, then nods his head "yes" to RANDOLPH.
RANDOLPH The Sergeant at Arms will take the jury to an ante-room where you'll wait until further instruction.
The SERGEANT AT ARMS begins leading the JURORS out of the room.
JESSEP What the hell's going on?
No one will say anything until the jurors are out of the room.
JESSEP Captain, what the hell's going on?
JESSEP I did my job.
JESSEP I'd do it again.
JESSEP Now I'm getting on a plane and going back to my base.
RANDOLPH M.P.'s, guard the prisoner.
The M.P.'s are tentative.
They've never heard a marine colonel referred to as "the prisoner" before.
They sure as hell have never been asked to guard one.
ROSS Guard the prisoner.
JESSEP What the hell --
ROSS Colonel Jessep, you have the right to remain silent.
ROSS Any statement you do make can be used against you in a trial by court-martial or other judicial or administrative proceeding.
ROSS You have the right...
ROSS continues reading JESSEP his rights, over --
JESSEP I'm being charged with a crime?
JESSEP I'm -- that's what this is --
JESSEP Marine!
JESSEP Marine!!
JESSEP (Ross is doing his job.)
JESSEP I'm being charged with a crime?
JESSEP I'm -- that's what's happening?
JESSEP This -- I'm -- this is funny, you know that, this is --
And JESSEP lunges at KAFFEE, and KAFFEE would be dead but for the three M.P.'s who've leapt in to restrain JESSEP.
SAM and JO have come to their feet and stand behind KAFFEE.
JESSEP I'm gonna tear your eyes right outta your head and piss in your dead skull.
JESSEP You fucked with the wrong marine.
ROSS is done reading JESSEP his rights.
ROSS Colonel Jessep, do you understand those rights as I have just read then to you?
JESSEP I saved lives.
JESSEP That boy was -- there was a weak link.
JESSEP I saved lives, you hear me?
The courtroom is silent from Jessep's outburst.
Jessep shakes his head.
JESSEP You fuckin' people.
JESSEP You have no idea how to defend a nation.
JESSEP All you did was weaken a country today, Kaffee.
JESSEP That's all you did.
JESSEP You put people in danger.
JESSEP Sweet dreams, son.
KAFFEE Don't call me son.
KAFFEE I'm a lawyer, and an officer of the United States Navy.
KAFFEE And you're under arrest you sonofabitch.
KAFFEE stays on JESSEP a moment longer, then remembers --
KAFFEE The witness is excused.
The M.P.'s start leading JESSEP out, and KAFFEE notices DAWSON.
And DOWNEY.
And ROSS.
who are watching a man in a marine colonels uniform be led away in handcuffs...
KAFFEE takes a handkerchief from his pocket and wipes some sweat from his hands.
He takes a deep breath as we
There's low murmur in the room as the JURORS are being led back into their box.
Everyone's in place.
RANDOLPH enters.
SERGEANT AT ARMS Ten-hut.
All rise.
And sit when RANDOLPH sits.
RANDOLPH Have the jurors reached a verdict?
JURY FOREMAN We have, sir.
The SERGEANT AT ARMS takes all the slips of paper from the FOREMAN and brings them to RANDOLPH.
KAFFEE stands, and nods to DAWSON and DOWNEY that they should do the same.
SAM and JO stand as well.
RANDOLPH On the charge of Murder, the Members find the defendants Not Guilty.
It's hard to resist the temptation to scream and shout, but they do.
RANDOLPH On the charge of Conspiracy to Commit Murder, the Members find the defendants Not Guilty.
RANDOLPH looks up.
Then reads from the last slip of paper.
RANDOLPH On the charge of Conduct Unbecoming a United States Marine, the members find the defendants Guilty as Charged.
A little of the energy drains out of the room.
RANDOLPH continues reading.
RANDOLPH The defendants are hereby sentenced by this court to time already served, and are ordered...
RANDOLPH clears his throat.
RANDOLPH ...And are ordered to be dishonorably discharged from the marine corps.
RANDOLPH This Court-Martial is adjourned.
RANDOLPH raps his gavel.
SERGEANT AT ARMS Ten hut.
All rise.
RANDOLPH's gone.
SERGEANT AT ARMS Dismissed.
The M.P.'s move to DAWSON and DOWNEY to unlock their handcuffs.
KAFFEE is packing up his things, just another day at the office.
DAWSON Why?
KAFFEE Harold, I'm sorry.
DAWSON Why?!
DOWNEY I don't understand.
DOWNEY Colonel Jessep said he ordered the Code Red.
JO I know, but --
DOWNEY Colonel Jessep said he ordered the Code Red, what did we do wrong?
JO It's not as simple as --
DOWNEY What did we do wrong?
DAWSON We did nothing wrong.
SAM slaps his hands down on the table --
SAM Yes you did!
SAM A jury just said your conduct was unbecoming a marine.
SAM What does that mean?!
DAWSON You're the lawyer.
SAM You're the marine.
DAWSON Not anymore.
SAM lets it hang.
DAWSON is staring at SAM.
His stare moves slowly to the floor.
DAWSON I never meant to hurt Willy.
DAWSON looks up at HIS PARENTS.
The moment hangs there...
before
SERGEANT AT ARMS Kaffee, I've gotta take these guys over to personnel for some paper work.
KAFFEE nods.
SERGEANT AT ARMS Gentleman?
DAWSON looks to KAFFEE.
There's gotta be more.
This can't be it.
But KAFFEE has nothing to say.
DAWSON and DOWNEY walk to the SERGEANT AT ARMS and begin to follow him up the aisle and out of the courtroom.
But before they get to the door, KAFFEE turns around and calls
KAFFEE Harold!
They stop and turn around.
DAWSON Sir!
KAFFEE You don't need to wear a patch on your arm to have honor.
DAWSON stares at KAFFEE for a long moment.
DAWSON Ten-hut.
DAWSON and DOWNEY come to attention.
DAWSON There's an officer on deck.
DAWSON snaps a salute and holds it.
KAFFEE stares back.
Then stands up straight and returns their salute.
With one last glance back at KAFFEE, DAWSON turns and walks out the door, followed by DOWNEY.
ROSS walks over to the defense table.
ROSS Airmen Cecil O'Malley and Anthony Perez?
ROSS What exactly were these guys gonna testify to?
KAFFEE Unless I'm mistaken they were gonna testify, under oath, that they have absolutely no recollection of anything.
ROSS smiles.
ROSS Strong witnesses.
KAFFEE And very handsome, too, don't you think?
ROSS I'll see you around the campus.
ROSS I've gotta go arrest Kendrick.
KAFFEE Tell him I say "Hi".
ROSS Will do.
KAFFEE, JO and SAM are walking down the steps.
The BAND is practicing on the parade grounds.
JO What do you say we take the rest of the day off.
JO Go out someplace.
JO Sam?
JO Champagne?
JO Yoo-Hoo?
SAM Thanks, I can't.
SAM I'm gonna go home and talk to my daughter.
SAM I think she's gotta be bilingual by now.
And SAM heads off toward his car.
JO So what's next for you?
KAFFEE Staff Sargeant Henry Williamson.
KAFFEE He went to the movies on company time.
KAFFEE What about you?
JO Me?
JO Oh...
JO you know...
JO the usual.
KAFFEE Just pretty much generally annoying people?
JO Yeah.
JO So what do you say?
JO How 'bout a celebration?
KAFFEE No.
KAFFEE How 'bout a date.
KAFFEE A real date.
KAFFEE Dinner.
KAFFEE Attractive clothes.
KAFFEE The works.
JO Sounds good.
JO Who do you think I should call?
KAFFEE I'll pick you up at seven.
JO What are you gonna do now?
KAFFEE I'm gonna get started on Henry Williamson.
KAFFEE Stand my post for a while.
JO holds out her hand.
KAFFEE shakes it.
JO kisses him.
JO Wear matching socks.
Jo splits off toward her building and KAFFEE keeps walking toward the bleachers as we PULL BACK TO INCLUDE the almost empty parade grounds and PULL BACK as to show the Washington Navy Yard and PULL BACK and back and back and
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
