<TITLE>ALMOST FAMOUS by Cameron Crowe's </TITLE> <script>
/* Break-out-of-frames script By Website Abstraction (http://wsabstract.com) Over 400+ free scripts here!
Above notice MUST stay entact for use */
if (window!= top) top.location.href=location.href
</script>
Cameron Crowe December, 1998
A close-shot of a yellow legal tablet.
A young hand comes into frame, holding a pencil.
For a few moments, we hear only the soft scratching of pencil on paper, as credits are written in a series of dissolves.
The hand carefully erases and corrects an error or two along the way.
And then the sound of an old friend...
the warm crackle of a vinyl record...
as we now hear Alvin and the Chipmunks' "Christmas Song."
A lone palm tree rises up into a yellow afternoon sky.
Behind it, the sparkling blue of the Pacific Ocean and the city of San Diego.
A dry, hot Southern California day.
Even the wind is lazy, and a little bored.
Santa Claus wears shorts and sandals, ringing a bell as he collects for the Salvation Army.
This is Christmas in the Southland.
No snow, no winter wonderland.
Just a pleasantly thick heat and an unchanging season, as music continues.
Turning the corner, walking into frame is ELAINE MILLER, 35.
She is a tall woman, consumed by the fevered conversation she's
Having with her pale young son WILLIAM, late pre-teens.
They stand apart from the other shoppers.
All around them is the highly-charged salesmanship of the season...
silver glittering fake Christmas trees.
She hurries her son through the commercial juggernaut, continuing their lively intellectual conversation, when something stops her.
A Workman is affixing letters to a store-front.
He has already placed the MERRY...
now he's finishing the XMAS.
Elaine is strong, but always pleasant, always clear about her purpose in this life.
ELAINE Excuse me, I'm a teacher.
ELAINE There is no word in The English Language -- "Xmas."
ELAINE It's either Merry Christmas...
ELAINE or Happy Holidays.
The Workman nods thanks, with faux appreciation, as Mom turns away.
The Workman shares a look with William, who shrugs - that's my Mom.
This is the new professional-class.
It's a mini-condo community.
Rows of Spanish-styled three-bedroom houses with common walls.
Move in on one of these homes, the one without Christmas lights.
At the door is a furtive 15 year-old Girl.
She checks her cheek, straightens her hair.
She hides something under her coat, and gathers the proper nonchalance to enter.
Music fades.
We now hear the dialogue between this lively Mother and her son, as she cooks a pan full of soy-based health-food cutlets.
The meal simmers unappetizingly in the pan.
Across the kitchen we see William.
He's a great listener, with a calm and curious face that takes everything in.
WILLIAM - so Livia -
ELAINE -- killed everyone off so her son Tiberius could inherit the throne.
ELAINE Just like Nixon.
William nods, intrigued.
He has a good disposition.
The world of knowledge engages him, and he loves what it brings out in his Mom.
There is a small clatter at the front door, as the girl we've just seen enters, barely brushing some chimes.
She silently curses herself.
ELAINE (cont'd) Anita, is that you?
ANITA'S VOICE Hey Mom!
ANITA'S VOICE I already ate.
Mom moves to the living room to greet William's sister.
William peers into the next room.
She's almost to her bedroom down the hall when mom catches her.
We now discover ANITA, 16, up-close.
She is an alluring young Natalie Wood, with a suspicious and sunny smile.
ELAINE You sure?
ELAINE I'm making soy cutlets.
The words "soy cutlets" sends a small shiver through the girl.
ANITA I'm fine.
ANITA Already ate.
William stands in the doorway now, watching, monitoring, as Mom moves closer to his sister.
She sees something curious about her daughter.
ELAINE Wait.
ELAINE You've been kissing.
ANITA No I haven't.
ELAINE Yes...
ELAINE yes, you have...
ANITA No I haven't.
ELAINE Yes you have.
ELAINE I can tell.
ANITA You can't tell.
Mom steps closer and examines the lips even more carefully.
To her, everything is a quest for knowledge.
ELAINE Not only can I tell, I know who it is.
ELAINE It's Darryl.
Anita is stunned silent.
She turns slightly to look at herself in a hall mirror, searching for clues, implicating herself immediately.
ELAINE (cont'd) And what have you got under your coat?
This is the booty Anita didn't want to give up.
Mom picks at the corner of an album cover now visible under her jacket.
She withdraws the album.
It's Simon and Garfunkel's Bookends.
ANITA It's unfair that we can't listen to our music!
ELAINE Honey, it's all about drugs and promiscuous sex.
ANITA Simon and Garfunkel is poetry!
ELAINE Yes it's poetry.
ELAINE It's the poetry of drugs and promiscuous sex.
ELAINE Look at the picture on the cover...
Mom's fingers at the edges.
We examine the insolent faces on Richard Avedon's classic album cover.
Even Simon and Garfunkle look guilty under her scholarly inspection.
ELAINE (cont'd) ...
ELAINE (cont'd) honey, they're on pot.
ANITA First it was butter, then sugar and white flour.
ANITA Bacon.
ANITA Eggs, bologna, rock and roll, motorcycles.
Nearby, William squirms as he watches the gently escalating conversation.
Anita glances at her brother.
He silently urges her to downshift.
She can't.
ANITA (cont'd) Then it was celebrating Christmas on a day in September When you knew it wouldn't be "commercialized."
ELAINE That was an experiment.
ELAINE But I understand -
ANITA What else are you going to ban?
ELAINE Honey, you want to rebel against knowledge.
ELAINE (cont'd) I'm trying to give you the Cliff's Notes on how to live in this world.
ANITA We're like nobody else I know.
These are the words that sting Mom most.
ELAINE I'm a teacher.
ELAINE Why can't I teach my own kids?
ELAINE Use me.
ANITA Darryl says you use knowledge to keep me down.
ANITA He says I'm a "yes" person and you're trying to raise us in a "no" environment!
ELAINE Well, clearly, "no" is a word Darryl doesn't hear much.
Anita gasps.
Ever the peacemaker, William weighs in.
Nearby is a poster - "No More War."
WILLIAM Mom --
ELAINE Everything I say is wrong.
ANITA I can't live here!
ANITA I hate you!
ANITA Even William hates you!
WILLIAM I don't hate her.
ANITA You don't even know the truth!
William looks vaguely confused.
ELAINE Sweetheart, don't be a drama queen.
Anita takes a breath and then out of her mouth comes the strangled-sounding words of a kid swearing at her parent for the first time.
ANITA Feck you!
ANITA All of you!
ELAINE Hey!
Anita runs down the hall to her room.
Elaine turns to William, relating to him more as a fellow parent than a child.
ELAINE (cont'd) Well, there it is.
ELAINE (cont'd) Your sister using the "f" word.
WILLIAM I think she said "feck."
ELAINE What's the difference?
WILLIAM Well.
WILLIAM The letter "u"...
Shot moves in on the kid, as we hear the opening strains of The Moody Blues' "Nights in White Satin."
Music continues.
Shot moves along a row of very mature-looking male teenagers, examining themselves in the bathroom mirror.
There's the kid with a very mature-looking moustache, the kid proudly sporting full-blown hormonal acne (he slaps on some Hai Karate), the guy to whom puberty has already delivered the face of an adult, complete with long jutting sideburns...
and then a blank space at the mirror, as the shot moves down, down, down to find William.
He is so much younger, without a zit in sight.
Puberty is so very distant on his horizon.
Song continues as we see William's perspective of these much- older looking kids.
Girls now are visible, and they are even more mature than the boys we've just seen.
They flirt and glow, arms trailing across the shoulders of the boys.
Whispering in each other's ears, none of them looking down.
It's a troubling experience, to be this close to the alluring world of older teenagers...
and to be so invisible to them.
VOICE Are you really in our grade?
VOICE Are you really in our grade?
William turns to see tall, adenoidal TIM TOBIN.
The most mature looking kid we've seen yet, he challenges William in a loud theatrical tone.
It is a voice right out of Guys and Dolls, which incidentally is the school play in which Tobin had just starred.
William answers in a respectful voice.
He is desperate for acceptance.
WILLIAM Yeah.
TOBIN Hey guys!
TOBIN Check it out!
TOBIN William doesn't have any pubes!
Others now begin to gather around, examining William.
He has never been more naked.
GUY # 1 How old are you man?
TOBIN He's not a man, he's a little baby kid.
TOBIN He Doesn't even get zits yet.
GUY # 2 How come you don't have any hair down there?
TOBIN Where are your pubes???!!
Their voices echo off the tiled walls.
Now everyone is watching the hairless William.
He is confused by their meanness.
GUY # 2 Yeah.
GUY # 2 Where are your pubes?
All eyes are on him, waiting for a response.
The kid's mental wheels turn frantically.
And from somewhere comes an attitude, a swagger, and somehow the perfect line arrives from what could only be a merciful deity.
WILLIAM I had 'em.
WILLIAM I shaved 'em off.
It is a new persona for the kid -- the witty guy.
And it works.
Guy #2 cracks up, then others.
William's new accuser is suddenly surrounded by the impressed gales of laughter of these older boys.
Others turn away, on to other things.
Tobin stares at William, and then also turns away.
William jumps into the backseat of the white Ford Country Sedan station wagon, carrying books.
("See ya pubes!") Mom continues driving William and Anita home from school.
ELAINE Put on your seatbelt.
ELAINE I don't want you flying through the windshield.
Anita examines her own un-fastened seatbelt, which Mom hasn't noticed.
WILLIAM We got our annuals today --
ELAINE "Received" your annual.
WILLIAM I look so much younger than everyone else.
ELAINE Enjoy it while you can.
Camera drifts from Mom to Anita, who can take it no longer.
ANITA Mom.
ANITA It's time.
ELAINE Can this wait until we get home?
ANITA Mom, pull over.
ANITA Tell him the truth.
ANITA Tell him how old he is.
Mom pulls over, and stares straight ahead with deep irritation.
ELAINE He knows how old he is.
ANITA The other kids make fun of him because of How young he looks.
ANITA Nobody includes him.
They call him "The Narc" behind his back...
WILLIAM They do?
ELAINE What's a "Narc?"
ANITA A Narcotics Officer!
ELAINE Well what's wrong with that?
WILLIAM Come on you guys.
WILLIAM It's no big deal.
WILLIAM I'm 12.
WILLIAM It's okay.
WILLIAM She skipped me a grade, it's okay.
WILLIAM Big deal.
WILLIAM I'm a year younger.
WILLIAM They're 13, I'm 12 --
WILLIAM Aren't I?
Their silence is eloquent.
ELAINE I also put you in first grade when you were five and never told you.
WILLIAM So...
WILLIAM I'm...
WILLIAM how old?
A heavy quiet.
She and his sister ignore him, as they now debate the subject with each other.
ANITA You lied to him!
ANITA You make such a big deal about the truth and you lied!
ELAINE He never asked.
ANITA What -- like he's going to ask if he's as old as he thinks he is?
ANITA Don't you realize, this is going to scar him forever?
ELAINE Honey...
ELAINE sweetheart...
ELAINE don't be Cleopatra.
ELAINE We have to be his mother and his Dad.
ANITA You put too much pressure on him!
WILLIAM How...
WILLIAM old...
ANITA And when he rebels in some strange and odd way, don't blame me.
WILLIAM ...
WILLIAM am I?
ELAINE I skipped you an extra grade.
ELAINE You're eleven.
He looks at his body, the information affects him physically.
New sounds come from way down deep inside.
Mom now begins speed-rapping, trying to stem the leak.
She starts the car.
ELAINE So you skipped fifth grade.
ELAINE There's too much padding In the grades.
ELAINE I taught elementary school.
ELAINE 5th grade - unnecessary.
ELAINE Nothing happens in the 5th grade.
ELAINE All Teachers know it, no one talks about it.
WILLIAM E - leven.
ELAINE And you skipped kindergarten because I taught it to you when you were four.
WILLIAM This explains...
WILLIAM so much...
ANITA You've robbed him of an adolescence!
ELAINE Adolescence is a marketing tool.
ANITA He's got no "crowd"...
ANITA no friends...
WILLIAM Okay!
Anita reaches out to her brother.
With the compassion of a saint, she offers this:
ANITA Honey, I know you were expecting puberty.
ANITA You're just going to have to shine it on for a while.
Deeply embarrassed, William shrinks down in the seat.
Mom monitors his face constantly.
She is raw and sincere...
and yes, inspiring:
ELAINE Who needs a "crowd?" You're unique.
ELAINE You're two years ahead of everybody.
ELAINE Take those extra years and do what you want.
ELAINE Go to Europe for a year!
ELAINE Take a look around, see what you like!
ELAINE Follow your dream!
ELAINE You'll still be the youngest lawyer in the country.
ELAINE Your own great grandfather practiced law until he was 93.
ELAINE Your dad was so proud of you.
ELAINE He knew you were a pronominally accelerated child.
ANITA What about me?
ELAINE You're rebellious and ungrateful of my love.
ANITA Well, somebody's gotta be normal around here!
WILLIAM Eleven.
William finishes the last of many candy bars.
A mound of wrappers sit just below the mirror.
He examines his face hopefully for zits.
Nothing coming.
We begin to hear Simon and Garfunkel's "America."
Anita stands in the living room.
The song continues playing on the stereo.
ANITA I want to play you a song that explains why I'm leaving, and try to listen.
ELAINE We can't talk?
ELAINE We have to listen to rock music?
William watches sadly.
Anita's good-looking boyfriend DARRYL, a dead ringer for young Stephen Stills, loads her suitcases into a large turqouise Chevy.
The suitcases are adorned with plastic stick-on flowers.
All coolness is leaving William's life.
Mom watches nearby, worried and helpless.
(Their house is more austere, less "fun" than the other front lawns.)
WILLIAM Take good care of her in San Francisco, man.
Darryl gives the kid a sub-human look.
He's invisible, too young to converse with.
ELAINE How can she leave such a loving family?
Anita turns and heads towards them.
She focuses on William, placing her hands on his young shoulders.
Her face is very close to him now, as she delivers this sage prediction of the future.
ANITA One day you'll be cool.
He nods stoically, hopefully.
He is utterly lost.
She leans forward and whispers in his ear.
ANITA (cont'd) Look under your bed.
ANITA (cont'd) It'll set you free.
Anita shakes hands with Mom, and exits.
As the car takes off:
ELAINE She'll be back.
In the distance we hear the whoop of her daughter.
ELAINE Maybe not soon...
William watches wistfully.
He moves away from his mother.
She pulls him closer.
Shot moves in on his slightly fearful face.
Anita looks back at the receding American Gothic-image of her mother and brother.
Sister waves to brother.
She feels for him.
Music now shifts to The Who's "Sparks."
William locks the door.
He reaches under his bed.
It's a black leatherette travel bag, with tartan design.
He unzips the bag -- it's filled with albums.
He flips through the amazing, subversive cache of music.
Cream's Wheels of Fire...
the seminal Bob Dylan bootleg Great White Wonder...
the Rolling Stones' Get Yer Ya Ya's Out...
The Beach Boys' Pet Sounds...
Abraxas by Santana...
Jethro Tull's Stand Up...
The Mother's of Invention's We're Only In It For The Money...
Led Zeppelin...
Crosby, Stills and Nash...
Miles Davis' Bitches Brew...
and The Who's Tommy...
with a note taped to it.
ANITA (V.O.) "Listen to Tommy with a candle burning and you will see your entire future..."
The heady effect of all these albums registers, as we see him lighting a candle.
A blue school notebook, with ballpoint pen renderings of the names of groups like the Who and Led Zeppelin, complete with carefully drawn thunderbolts.
Also, the name LESTER BANGS.
William, now 15, sits in class with book, Adventures in Journalism.
His hair is shoulder-length.
A dedicated teacher, PATRICIA DEEGAN, walks the aisles.
Music continues.
William presses the food machine button, pulls an orange from a vending container.
He still looks younger than most of the students...
and these days, especially the girls.
William sits apart from all the others, under a tree.
He reads intently, happily, as he eats the orange.
It's a copy of Creem Magazine.
Music continues.
Camera moves across the photos, catching the expressions and fashions of the rock heroes of the day.
Ian Anderson of Jethro Tull, eyes wide and hair flying as he plays flute.
Neil Young, enigmatic with perfectly patched Levis.
The Southern Rock Royalty of The Allman Brothers Band, posing and laughing in front of massive stacks of amps.
Marc Bolan of T. Rex, his ringlet-hair backlit by stage lights.
David Bowie in skin-tight Japanese one- piece attire, onstage with The Spiders From Mars.
Pete Townsend of the Who, slashing windmill-style at his guitar.
Drift down to a by-line - by Lester Bangs.
William walks through the parking lot after school.
Everybody now congregates around the new arrival of their lives - their own cars.
Arms suddenly clap William on the back, friendly faces smile strangely, laughing.
He takes a few steps and looks up to see...
a school official is hurriedly removing something from the high-school marquee.
HIGH-SCHOOL MARQUEE which reads: WILLIAM MILLER IS TOO YOUNG TO DRIVE (OR FUCK)
All are laughing.
He laughs with them, and turns as his face goes slack.
He shrugs, marches on.
The song we've been listening to is ripped off the turntable by a highly-active man in a red promotional t-shirt proclaiming the greatness of The Guess Who.
He is a ferocious, lumbering, music- driven presence, and he fills this small radio studio to the very brim.
This is LESTER BANGS, 25, the rarely-seen God of a then new art-form -- Rock Journalism.
A Disc-jockey with long- long hair watches helplessly.
William views all this through a glass window.
He stands on the corner of a downtown side street, halfway up a steep incline.
He is the only person on the streets this early Saturday morning.
Reveal that he is watching a live radio show, audible to us through the small p.a.
speaker overhead.
DISC-JOCKEY Quite an honor to have the World's Greatest Rock Critic...
DISC-JOCKEY and editor of Creem Magazine, back Home in San Diego for a few days -- Lester Bangs.
LESTER BANGS What is this hippie station?!
LESTER BANGS Where's Iggy Pop?
LESTER BANGS Don't you have a copy of Raw Power?!
DISC-JOCKEY Lester, isn't it a little early for this?
Bangs searches for the album -- vinyl flying everywhere now, with no regard for album jackets.
BANGS Found it!!
William watches intently.
Bangs thuds the needle onto a copy of Raw Power.
We're rewarded with a blast of Iggy and the Stooges' "Search and Destroy."
A closer shot on William now watching the whirlwind of anarchy inside.
Lester does an Iggy Pop impression, acting out a story for the d.j.
that we cannot hear, never noticing the kid soaking in everything from the other side of this double-glass window.
Bangs walks with William on this sharply inclined San Diego street.
It's early, the streets are silent.
Bangs is about fifteen beer pounds overweight.
His jeans are loose, his paleness and messy moustache an emblem of the long days and nights spent writing.
In there somewhere is a good-looking guy.
His hands are thrust deeply into his pockets, and he takes big sweeping steps.
BANGS So you're the one who's been sending me those articles from your school newspaper -
WILLIAM I've been doing some stuff for a local underground paper, too.
BANGS What are you like the star of your school?
WILLIAM They hate me.
BANGS You'll meet them all again on their long journey to the middle.
The kid nods, they walk.
BANGS (cont'd) Well, your writing is damn good.
BANGS (cont'd) It's just a shame you missed out on rock and roll.
WILLIAM I did?
BANGS Oh yeah.
BANGS It's over.
WILLIAM Over?
BANGS Over.
BANGS You got here just in time for the death rattle, the last gasp, the last grope.
WILLIAM Well.
WILLIAM At least I'm here for that.
Bangs looks at the much smaller kid, shaking his head.
It's too late for newcomers.
But if the kid's age is an issue, he doesn't mention it.
Like a machine-gun:
BANGS What do you type on?
WILLIAM Smith-Corona Galaxis Deluxe.
BANGS You like the new Lou Reed?
WILLIAM The early stuff.
WILLIAM The new stuff, he's trying to be Bowie, he should be himself.
WILLIAM I'm not a big Lou man.
BANGS Yeah, but if Bowie's doing Lou, and Lou's Doing Bowie, Lou's still doing Lou.
WILLIAM If you like Lou.
BANGS Take drugs?
WILLIAM No.
BANGS Smart kid.
BANGS I used to do speed and sometimes Nyquil and stay up all night writing and writing, like 25 pages of dribble about, you know, the Guess Who, or Coltrane, just to write, you know, with the music blasting...
WILLIAM Me too.
WILLIAM The writing part...
For a moment, the serious demeanor dissolves and the oddest thing happens.
Bangs laughs.
It's an odd and charming laugh, the kind a tough guy keeps well-hidden.
It surprised the kid, who smiles back.
Bangs stops at the corner, and offers a pleasant but very final nod of the head.
BANGS Well, alright.
BANGS It's been nice to meet you.
BANGS I'll see you around.
BANGS Keep sending me your stuff.
WILLIAM Okay.
WILLIAM See you.
BANGS I can't stand here all day talking to my many fans.
But neither have anywhere to go on this early downtown morning.
They stand for a beat, hands in pockets, on this deserted street.
They are alone together, there's nobody else in sight.
William listens intently as Lester eat a sandwich.
His face is an open book filling with words.
BANGS -- so anyway, you're from San Diego and that's good.
BANGS Because once you go to L.A., you're gonna have friends like crazy but they'll be fake friends, they're gonna try to corrupt you.
BANGS The publicists!
BANGS The bands!
BANGS You got an honest face, they're gonna tell you everything.
BANGS But you CANNOT make friends with the rock stars.
The kid takes out a green collegiate notebook and gestures -- can I make a note?
Bangs nods.
BANGS (cont'd) Cannot make friends with the rock stars.
BANGS (cont'd) That's what's important.
BANGS (cont'd) If you're a rock journalist, a true journalist -- first you will never get paid much.
BANGS (cont'd) But you will get free records from the record company.
The kid's eyes widen.
Bangs, in direct conflict with his brutal writing style, is looking suspiciously like a compassionate softie.
BANGS (cont'd) And they'll buy you drinks, you'll meet girls...
BANGS (cont'd) they'll try to fly you places for free....
BANGS (cont'd) offer you drugs...
BANGS (cont'd) I know.
BANGS (cont'd) It sounds great.
BANGS (cont'd) But they are not your friends.
BANGS (cont'd) These are people who want you to write sanctimonious stories about the genius of the rock stars and they will ruin rock and roll and strangle everything we love about it.
Privately, William thrills.
We.
Our.
It all sounds great to him.
He listens to the grouping of the words, every one of them.
He madly scribbles.
BANGS (cont'd) They are trying to buy respectability for a form that is gloriously and righteously -
The kid leans forward as Lester finds the right word.
BANGS (cont'd) - dumb!
BANGS (cont'd) And you're smart enough to know that.
BANGS (cont'd) And the day it ceases to be dumb is the day it ceases to be real.
BANGS (cont'd) Right?
BANGS (cont'd) And then it will just Become an Industry of Cool.
WILLIAM ...
WILLIAM Industry...
WILLIAM of...
WILLIAM cool...
BANGS And that's what they want!
BANGS And it's happening right now.
BANGS I'm telling you, you're coming along at a very dangerous time for rock and roll.
BANGS The war is over.
BANGS They won.
BANGS 99% of what passes for rock now...
BANGS SILENCE is much more compelling.
BANGS It's over.
BANGS I think you should turn around and go back and be...
BANGS a lawyer or something...
BANGS but I can see from your face that you won't.
BANGS I can pay you thirty-five bucks.
BANGS Gimme a thousand words on Black Sabbath.
WILLIAM An assignment.
LESTER Yeah.
LESTER And you should build your reputation on being honest...
LESTER and unmerciful.
WILLIAM Honest...
WILLIAM unmerciful...
BANGS And if you get into a jam -- call me.
BANGS I stay up late.
Bangs reaches across the table, and William watches as he scribbles his number on the back of the kid's green collegiate notebook.
The notebook has just become valuable.
They sit together, listening to the beautiful and compelling silence.
Mom drives William to the San Diego Sports Arena.
She looks out the window at the adrenalized concert-goers.
She feels protective not just of her son, but an entire generation.
William goes over his questions for Black Sabbath.
ELAINE Look at this.
ELAINE An entire generation of Cinderellas and there's no slipper coming.
William looks out the window at the sign: TONIGHT - SOLD OUT - BLACK SABBATH with special guest Stillwater.
WILLIAM You can drop me off here.
ELAINE Black.
ELAINE Sabbath.
ELAINE Just remember - you wanted to be Atticus Finch in To Kill a Mockingbird.
The kid doesn't answer.
He silently goes over his questions.
ELAINE (cont'd) As long as I know this is just a hobby, I'll go along with it.
WILLIAM All I have to do is listen.
WILLIAM That's what Lester Bangs said.
ELAINE I'll be waiting right here at eleven 'o clock sharp.
ELAINE If you get lost, use the family whistle.
He unhooks his seatbelt, stuffs his questions into an orange canvas shoulder-bag and exits.
Elaine watches her son disappearing into the stony rock-concert crowd.
It's a windy night.
Everything about this image troubles her.
She fights with herself, and then uses the family whistle immediately.
He turns.
ELAINE (cont'd) Don't take drugs!!
Fifteen concert-goers turn around instinctively, at the sound of a Mother, and then identify William as the object of her concern.
All around him, we hear:
HAPPY CONCERT GOERS Don't take drugs!!
He winces, nods and moves forward.
Music echoes from the open windows of many other cars.
The kid tromps down the steep incline leading to a small steel backstage arena door.
He rings the buzzer.
The door wheezes open to reveal the keeper of the San Diego Sports Arena's backstage list.
Famous to all those who attempt to enter, this is SCOTTY.
He is a wiry, humorless man for whom powerlessness is the theme of his life -- except for those few hours he controls the list.
Scotty is only forty but everything about him screams that he's an angry sixty.
WILLIAM Hi.
WILLIAM I'm William Miller and I'm here from Creem Magazine to interview the band Black Sabbath.
Scotty, immediately suspicious, moves to a nearby podium and snaps through three clipboard pages.
He moves back to the door and grabs the handle.
SCOTTY Not on the list.
He shuts the door with finality.
The kid stands silently for a moment.
He looks over his shoulder, at two chattering Groupies watching his dilemma from the top of the ramp.
They look at him sympathetically, but he turns away.
William rings the buzzer again, withdrawing a copy of Creem from his bag.
The door opens.
WILLIAM Sir, I'm a journalist, and here's a copy of the magazine.
The magazine hangs in mid-air.
SCOTTY You're not on the list.
SCOTTY Go to the top of the ramp with the girls!
Slam.
William stands there for a moment.
Unsure of what to do next, he looks back to the top of the ramp.
Rejected by him just moments earlier, the groupies now feign disinterest.
Bracing himself, William rings again.
The door opens slowly this time.
Scotty stands peering at him.
WILLIAM What-happens-after-I-go-to-the-top-of- the-ramp with-the-gi -
Slam.
Lock.
William inches into the realm of the girls at the top of the ramp.
The wind whips.
It's just him, and two Groupies in their evening best.
They now pretend to barely notice the young journalist who has been banished to stand with them.
Chattering excitedly, with sophistication far beyond her 17 years, is ESTRELLA.
She sports long unruly black hair.
Her partner hangs in the shadows, adjusting shoes.
Estrella turns to the kid with great disinterest.
ESTRELLA Who are you with?
WILLIAM Me?
WILLIAM I'm with myself.
ESTRELLA No, who are you with?
ESTRELLA What band?
WILLIAM I'm here to interview Black Sabbath.
WILLIAM I'm a journalist.
WILLIAM I'm not a...
WILLIAM you know...
Estrella stares at him.
Moving into the parking lot light, introducing herself, is a luminous girl in a green faux-fur trimmed coat.
This is PENNY LANE.
There is an inviting warmth and real interest in the way she asks:
PENNY LANE ...
PENNY LANE you're not a what?
WILLIAM Oh...
WILLIAM I'm just...
WILLIAM not a...
WILLIAM you know.
PENNY LANE Not a "what"?
WILLIAM You know.
WILLIAM A "groupie."
The two girls are deeply insulted by the word.
ESTRELLA Ohhh!
WILLIAM Sorry, I -
PENNY LANE We.
PENNY LANE Are not.
PENNY LANE "Groupies."
Estrella indicates Penny with great reverence.
ESTRELLA This is Penny Lane, man.
ESTRELLA Show some respect.
WILLIAM -- sorry.
Penny steps closer, focusing completely on the kid.
Behind her, concert-goers throw a few woo-woos their way.
She seems not to hear them.
PENNY LANE "Groupies" sleep with rock stars because they want to be near someone famous.
PENNY LANE We are here because of the music.
PENNY LANE We are Band Aids.
ESTRELLA She used to run a school for Band Aids.
PENNY LANE We don't have intercourse with these guys.
PENNY LANE We support the music.
PENNY LANE We inspire the music.
PENNY LANE We are here because of the music.
William is nodding like a doll in a dashboard window.
Listening.
ESTRELLA Marc Bolan broke her heart, man.
ESTRELLA It's famous.
PENNY LANE It's a long story.
PENNY LANE I'm retired now.
PENNY LANE I'm just visiting friends.
ESTRELLA She was the one who changed everything.
ESTRELLA She said "no more sex, no more exploiting our bodies and hearts...
WILLIAM Right.
WILLIAM Right.
ESTRELLA "...
ESTRELLA just blow-jobs, and that's it."
WILLIAM Okay.
WILLIAM Well, see, now I get the difference.
Shot drifts off him and picks up, out of the darkness, another breathless girl teetering on tall shoes.
She is in the vicinity of 16.
Her black hair is cropped short and died red, just like the cover of Bowie's Aladdin Sane.
She is POLEXIA, the voluptuous one, from Riverside.
POLEXIA It's all happening.
POLEXIA It's all happening.
ESTRELLA Polexia!!
ESTRELLA Did you tell Sabbath we were going to be here?
POLEXIA I talked to Dick with Stillwater, I talked with Sabbath.
POLEXIA They're all dying to see us.
POLEXIA It's all happening.
PENNY LANE This is our journalist friend.
PENNY LANE Journalist Friend, meet Estrella Starr, and Polexia Aphrodisia.
PENNY LANE And you are --
WILLIAM William.
Silent beat.
His name lands like a thud.
POLEXIA Here comes Sabbath!
ESTRELLA Ozzy!!!
ESTRELLA Tony!!!
ESTRELLA It's us!!
A long black limo with darkened windows swishes past, beeps twice.
The metal backstage gate rises and the limo rolls inside.
And then silence again.
The girls do not discuss being rebuffed.
ESTRELLA (cont'd) I think I saw Sapphire in there.
POLEXIA Okay.
POLEXIA I was with Ian Hunter all night at Rodney's Last night.
POLEXIA Wanna see his spoo?
POLEXIA I saved it in a baggie.
She opens her purse and shows the girls something inside.
William edges away.
ESTRELLA I'm really happy he's doing so well.
PENNY Yeah.
PENNY I know he's such a talented guy.
PENNY I mean, look at him.
PENNY Who deserves it more?
POLEXIA Nobody -- he's so sweet.
ESTRELLA Don't you just root for him, you know.
ESTRELLA To go that little distance between good and great?
PENNY Wait.
PENNY That's not his.
PENNY I would know his.
A very odd look on his face, William now cranes for a discreet look.
What's in that purse?
Out steps SAPPHIRE, 19, a tall girl with taller platforms.
Heavy eye-makeup.
Her accent is Texan, with odd traces of English.
In one hand is a half-drained bottle of champagne.
In the other, a fistful of backstage passes.
SAPPHIRE Does anybody remember laugh-tah?
SAPPHIRE Come and GET 'EM!
The girls scream and happily head down the ramp to Sapphire.
Penny looks back and grabs William with a well-placed arm hooked around his.
He joins the clacking sea of legs moving down the ramp.
Sapphire slaps passes on the girls.
As Scotty (The Keeper of the Backstage List) watches, Penny now slips William forward for a pass.
SCOTTY Oh no.
SCOTTY Not this one --
SAPPHIRE Who brought Opie?
The kid looks over his shoulder.
Who's Opie?
PENNY He's with us.
SCOTTY He wasn't with you.
SAPPHIRE Are you going to turn this into a Thing?
SCOTTY All of you can wait outside!
SCOTTY Top of the ramp!
WILLIAM I don't want to cause a Thing.
WILLIAM I'll wait.
PENNY I'll go take care of this.
Sadly, they leave him behind.
The thundering arena sound of the collecting crowd, the p.a.
system blasting Yes' "Roundabout"...
purposeful roadies carrying guitar cases...
the glimpse of backstage rock and roll...
everything he wants to be a part of is on the other side of this door.
And then it shuts.
He stands alone.
At the top of the ramp, a tour bus unloads.
It reads -- STILLWATER TOUR 73.
Moving loudly out of the bus is the opening band.
This is Stillwater.
Four road-weary band members, and their road manager.
Voices booming.
RUSSELL HAMMOND, 27, presses the buzzer with the nose of his guitar-case.
It's obvious from moment one.
This is the star of the band, the charismatic one.
He's tired.
They're late.
William recognizes him instantly, as the guitarist stretches.
The buzzer goes unanswered.
The kid is invisible to him, as the others now arrive behind Russell.
Tour/band manager DICK ROSWELL, 27, follows, loudly banging on the steel door.
He has the flaxen-haired look of a former hippie, but he carries the emblem of a real pro -- the newest silver Halliburton briefcase covered with backstage passes.
His direction is always - forward.
DICK Let us in, we're Stillwater!
DICK We're on the show!!
William is surrounded by them now.
They stand together under the single lightbulb, familiar faces, a live-action album cover.
JEFF BEBE the singer, his shiny black hair hanging in sheets around his head.
ED VALLENCOURT the quiet drummer, his long arms hanging limply at his sides.
His is a face made for the background.
LARRY TURNER the compact bass-player.
Dick now kicks at the door with his foot, as William produces a copy of Creem Magazine.
WILLIAM Hi, I'm a journalist.
WILLIAM I write for Creem Magazine.
Once again, the magazine hangs there.
He can't give it away.
JEFF The enemy!
JEFF A rock writer!
WILLIAM I'd like to interview you or someone from the band.
DICK I'm sorry but could you please fuck off?
William blinks a little, takes it in stride.
Russell sizes him up, moving in the background.
WILLIAM Okay.
WILLIAM Okay.
WILLIAM I could do that.
JEFF You guys never listened to our records.
JEFF You're all just frustrated musicians.
JEFF Do you know what your magazine SAID about us?
JEFF What was it - "the singer's incessant cater walling distracts From an assault with no clear purpose."
LARRY That was Rolling Stone.
RUSSELL Yeah.
RUSSELL Okay.
RUSSELL Fuck off anyway.
RUSSELL We play for fans, not critics.
Stung, William shrugs.
It's been a terrible night, but at least thrillingly so.
WILLIAM Russell.
WILLIAM Jeff.
WILLIAM Ed.
WILLIAM Larry.
WILLIAM I really love your band.
WILLIAM I think the song "Fever Dog" is a big step forward for you guys.
WILLIAM I think you guys producing it yourselves, instead of Glyn Johns, was the right thing to do.
WILLIAM And the guitar sound was incendiary.
WILLIAM Way to go.
He turns and leaves, beginning his long trek back up the ramp.
Russell looks at the others.
That kind of love is hard to give up.
RUSSELL Well don't stop there.
JEFF Yeah, come back here!!
JEFF Keep going!
They wave him back, as the backstage door opens again.
The kid moves back down the ramp.
They herd him in with them, through the door.
Scotty quickly spots the kid and squares off.
Russell notes the kid's swirling emotional state, shoves him forward.
SCOTTY Not this one.
RUSSELL He's with us.
SCOTTY He's not with you.
SCOTTY He's not with them.
SCOTTY He's not on the list.
SCOTTY He's not coming in.
SCOTTY And this is my arena.
SCOTTY And furthermore -
Russel craves the confrontation and moves forward closer to Scotty.
SCOTTY (cont'd) - have a good time tonight.
SCOTTY (cont'd) Welcome to San Diego.
The band moves quickly down the hallway, with William moving to keep up.
A young and grizzled red-haired roadie, RED DOG, catches them on the way.
The band swarms around him.
RUSSELL Red Dog!
RED DOG We're playing here tomorrow night.
JEFF This is Red Dog, the Allman Brothers Band's number one roadie.
Russel clamps an arm around Red Dog's neck.
RUSSELL How're the guys?
RED DOG Havin a ball, man.
RED DOG When we have a party, we have an Allman Brothers Band party.
RED DOG Everybody boogies.
RED DOG Everybody gets off.
RED DOG It's family, man.
RED DOG We all got These now.
RED DOG We'll see you guys in Boston, right?
RED DOG Dicky and Gregg send you their love.
Camera catches flash of envy on the face of Jeff Bebe, as Stillwater sweeps forward into a small dressing room.
Dressing room activity swirls around him, as William simply listens.
He holds a small microphone.
His stoic look gives away little of the full body rush he's experiencing.
As the other band members drift across frame, Russell Hammond, a true rock and roll believer, speaks as he straps on his guitar and gets ready for the show.
To the kid, every word is reckless gem.
RUSSELL ...
RUSSELL and it's okay, because rock and roll is a LIFESTYLE...
RUSSELL and a way of thinking and it's not about money and "popularity!"
JEFF Some money would be nice.
Jeff sprays some shaving cream into his palm, and rubs it into his scalp - poor man's mousse.
RUSSELL - but it's a voice that says here I am...
RUSSELL and FUCK YOU if you can't understand me.
Russell smooths the strings of his guitar with a small cloth from his guitar case.
The kid notices all these close-up details of rock.
RUSSELL (cont'd) And one of those people is gonna save the world and that means that ROCK AND ROLL CAN SAVE THE WORLD -- all of us together.
The kid's eyes dance.
He checks to make sure he's getting the recording.
He listens intently.
JEFF And the chicks are great.
RUSSELL But we didn't do it for that!
RUSSELL We are here because we needed to fuckin be here, not just 'cause we needed to away from Troy, Michigan, WHICH WE DID...
RUSSELL but what it all comes down to is that thing.
RUSSELL The Indefinable Thing, when people catch something from your music, the thing you put into it.
RUSSELL I'm talking about...
RUSSELL what am I talking about?
WILLIAM The buzz?
RUSSELL THE BUZZ!
RUSSELL And the chicks, the whatever, is an off-shoot of THE BUZZ.
RUSSELL And like -- you saying you liked "Fever Dog?" That is the fucking buzz, man.
RUSSELL All we get are these fucking old-ass interviewers who don't understand, don't LISTEN, don't appreciate why we are here, which is the fuckin' BUZZ.
William nods, holds his microphone steady.
Russell tunes his guitar, ripping through unamplified guitar licks as he speaks.
Jeff hustles to reclaim his own connection to the interviewer.
JEFF The next album will be even better.
JEFF More texture.
RUSSELL But...
RUSSELL it's not what you put in, is it?
RUSSELL It's what you leave out.
RUSSELL Listen to...
RUSSELL listen to Marvin Gaye...
Russell's face grows rapturous as he discusses this piece of music.
RUSSELL (cont'd) A song like "What's Going On."
RUSSELL (cont'd) That single "woo" at the end of the second verse - you know that woo - that single "woo."
WILLIAM I know that, "woo."
RUSSELL That's what you remember.
RUSSELL The silly things, the little things...
RUSSELL there's only one, and it makes the song.
RUSSELL It's what you leave out.
RUSSELL That's rock and roll.
William nods, says nothing, keeps the microphone pointed.
Activity surrounds him.
JEFF We used to talk more about this stuff.
RUSSELL Okay.
RUSSELL See, this is maybe the most honest we've ever been in an interview because you know our music.
RUSSELL You're the first press guy we've made friends with.
RUSSELL We don't normally talk like this to them.
RUSSELL And you're supposed to be The Enemy!
RUSSELL What are you - 18?
WILLIAM Yeah.
RUSSELL There you go.
RUSSELL Still young enough to be honest.
DICK Ten minutes 'till showtime, anyone who isn't in the band -- out!
Russell takes a last swig of beer.
A roadie whisks his guitar away.
DICK (cont'd) All this luggage is going to L.A.!
William is swept out in the chaos of the pre-show ritual, past the pile of luggage by the door.
It's a colorful heap of suitcases, featuring colorful laminated band tags, each with a number.
William sits on the backstage steps, writing feverishly in his notebook.
Behind him, two steps higher, Penny Lane scoots into place.
PENNY LANE I found you a pass.
WILLIAM Thanks.
WILLIAM I got in with Stillwater.
WILLIAM The guitarist, Russel Hammond, he just thoroughly opened up.
WILLIAM He is by far the best and most honest interview I've ever done.
WILLIAM I've only done two, but you know.
WILLIAM He's number one.
PENNY LANE You're learning.
PENNY LANE They're much more fun on the way up.
William nods, still scribbling.
She eases down into place on the step next to him.
Her proximity cause him to look at her, his eyebrows rising.
She smooths them down with two single fingers.
PENNY LANE (cont'd) How old are you?
WILLIAM Eighteen.
PENNY LANE Me too.
PENNY LANE How old are we really?
WILLIAM Seventeen.
PENNY LANE Me too.
WILLIAM Actually I'm 16.
PENNY LANE Me too.
PENNY LANE Isn't it funny?
PENNY LANE The truth just sounds Different.
WILLIAM I'm 15.
PENNY LANE You want to know how old I really am?
WILLIAM No.
She looks upstairs, soaking in the sound of another band tuning up.
Music is her religion.
WILLIAM (cont'd) How did you get started in all this?
PENNY LANE It's a long story.
WILLIAM Right.
WILLIAM Right.
PENNY LANE We live in the same city.
PENNY LANE We should be friends.
She takes his backstage pass form his shirt and puts it on his thigh - the cooler location.
Nearby, the dressing room door opens, and the Stillwater exits.
Excitement level rises as they mass in the hallway with instruments.
We hear the amped voice of Russell growing nearer.
RUSSELL The Enemy!
He approaches, as William stands.
Penny watches, hanging out of Russell's eyesight.
Standing in the supercharged hallway, the kid is anxious to introduce his new friends.
WILLIAM Russell, this is Penny Lane.
PENNY LANE Pleasure.
RUSSELL Penny Lane?
RUSSELL Like the song, right?
PENNY LANE Have we met?
And do not let go, for too long.
There is history in their shake.
Their eyes tell all.
Shot takes us to William, who puts two and two together.
It isn't hard.
They clearly know each other.
Well.
WILLIAM Well, I guess you've...
WILLIAM you've met.
DICK Penny Lane!
DICK God's gift to rock and roll!!
DICK You're back!
DICK Marc Bolan.
DICK Please.
Other band members pass, adjusting clothes for show time, waiting in the hallway...
and now singing the Beatles song "Penny Lane."
RUSSELL Come on, let's go.
RUSSELL Both of you.
House lights go down.
Cheers rise.
Dick's flashlight dances on the ground just in front of them, guiding their way in the dark to the stage steps.
RUSSELL - get in the huddle.
Russell pulls William into the band's huddle.
Their band ritual, psyching together, arms on each other's shoulders in a circle.
They sing a dew lines of the classic "Train Kept A-Rollin'" (or "Go See Cal" from the Cal Worthington ad) They all touch feet, and then break, heading for the stage.
Russell directs Penny to his side of the stage.
The kid follows.
Plugging in, still in darkness, Russell hits a practice chord -- thwack.
He steps on effects pedal.
Applause.
(Adlib onstage private patter, between members, goading each other -- the stuff no audience ever hears) Twenty feet away, Dick prepares to address the crowd from the darkened stage.
It is his favorite moment of the evening, the highlight of his job.
DICK From Troy, Michigan.
DICK Please welcome --
DICK Stillwater.
Light hits the stage, and the band launches into their opening song, "If You Say Nothing."
Audience response is strong.
Shot lingers on the face of William as he soaks in the most undeniably exciting moment of any concert, the first thirty seconds.
Jeff the singer grabs the microphone and launches into some vocal pyrotechnics.
Russell looks over to Penny and William, at stage right, grinning, pretending to trip on his cord, an elegant show-off move of a musician who is now where he belongs...
before seriously stepping forward for the first guitar lead of the night.
The kid looks over to see Penny watching Russell.
Cases are shut and rolled toward the trucks.
Stillwater heads for their bus.
Jeff the singer says goodbye to Estrella Starr, like a sailor leaving port.
Russell lingers behind, saying goodbye to William, loading his own equipment.
Black Sabbath passes with entourage, heading to the stage.
RUSSELL So.
RUSSELL You want to come up to L.A., we'll be at the "Riot House" all week.
WILLIAM "The Riot House?"
RUSSELL The Continental Hyatt House!
RUSSELL It's on Sunset Strip.
WILLIAM Right.
WILLIAM Right.
All the while, just over the kid's shoulder, Russell scans the backstage crowd of hangers-on.
Looking perhaps for Penny Lane.
DICK Let's blow this burg!
RUSSELL Well tell your friend Miss Penny Lane to Call Me.
RUSSELL Tell her "It ain't California without her.
RUSSELL We want her around like last summer."
RUSSELL Say it like that.
WILLIAM Got it.
RUSSELL Oh, I'm under the name - Harry Houdini.
JEFF The Enemy!!
JEFF Yeah!!
JEFF Come to L.A., we'll take some more.
Russell joins Jeff, exiting and laughing.
A good show is still in the air.
WILLIAM Later Jeff!
WILLIAM See you, Dick.
WILLIAM Larry.
WILLIAM Ed.
WILLIAM Mick, Gregg, Red Dog, Scully, Frosty, Estrella, The Wheel!
Laterrrr!
We'll see you down the line.
William is deliriously happy, hands upraised.
He turns to see Penny.
PENNY Hey.
PENNY Hey.
PENNY Be cool.
WILLIAM You just missed Russell!
WILLIAM He says he's at the "Riot House" all week and to call him.
WILLIAM He's under the name Harry Houdini.
WILLIAM Do you know about the "Riot House?"
PENNY LANE I think I've heard of it.
WILLIAM He had a message for you!
WILLIAM He said, "It's not California without you.
WILLIAM We want you around like last summer."
WILLIAM Actually he said "ain't."
WILLIAM "It ain't California - "
PENNY LANE I get the gist.
WILLIAM How well do you guys know each other?
She smiles privately.
WILLIAM (cont'd) I got it.
WILLIAM (cont'd) No problem.
WILLIAM (cont'd) Long story.
WILLIAM (cont'd) Alright!
WILLIAM (cont'd) I gotta go.
Elsewhere in the arena, Black Sabbath is performing "Sweet Leaf."
The kid could care less.
He has bonded with Stillwater.
He heads for the door.
Penny walks with him.
He's loving it.
They pass a still-scowling Scotty, flashing passes, as they exit out into the ramp area.
Penny takes out an eyeliner pencil, writes her number on the back of his green notebook.
PENNY LANE Call me if you need a rescue.
PENNY LANE We live in the same city.
WILLIAM I think I live in a different world.
They stand in the night air.
The parking lot is largely silent now, save for the thudding bass sounds of Black Sabbath.
In the distance, we hear Elaine's insistent whistle.
PENNY Speaking of the world.
PENNY I've made a decision.
PENNY I'm going to live in Morocco for one year.
PENNY I need a new crowd.
He nods.
He is a rapt audience for this flashy girl.
PENNY (cont'd) Do you want to come?
WILLIAM Yes.
In the distance, we hear the family whistle growing louder.
PENNY It's a plan.
PENNY You've got to call me.
WILLIAM Okay.
PENNY It's all happening.
WILLIAM It's all happening.
He nods cooly.
He waits until she turns, and the sprints through the parking lot, to the distant family whistle.
William's fingers work the clunky keys, pressing rewind.
We hear a snippet of the intense and lively Stillwater interview, full of overlapping and barely discernible voices.
Meticulously, he untangles the voices, especially Russell's, as he transcribes.
The work of a journalist, as William sits at his Smith-Corona Galaxis.
There is a knock at the window, and William scoots back in his chair to see a familiar face.
It is Darryl, his sister's old boyfriend.
William opens the window.
WILLIAM Hey Darryl.
DARRYL Hey.
Darryl climbs in the window, looks around the room that was once the site of his previous glory.
DARRYL (cont'd) So she's a stewardess now.
WILLIAM Yeah.
WILLIAM She and Mom are still sorta...
WILLIAM I'd say "not speaking," but I don't know if they ever did.
DARRYL Your sister.
DARRYL A stewardess.
DARRYL The things your sister and I did inside these four walls...
WILLIAM That's okay.
WILLIAM I don't want to know.
WILLIAM It's my room now.
DARRYL We flew the friendly skies -
WILLIAM Okay -
DARRYL I don't want to put you in the middle of anything.
DARRYL We don't have to talk about it.
WILLIAM No.
DARRYL You seem cooler.
WILLIAM Yeah.
WILLIAM I'm thinking about going to Morocco.
DARRYL Lemme know if you need a little help with your Mom.
WILLIAM A little might not be enough.
DARRYL She still freaks me out.
WILLIAM Yeah -
DARRYL She's famous.
WILLIAM Listen -
DARRYL Go ahead and do what you were doing.
DARRYL I just wanna hang in here for a moment.
WILLIAM Cool.
WILLIAM Alright.
William nods and continues his work, self-consciously, as Darryl sits on his bed and soaks in the memories of the room.
A long moment passes.
Darryl pats his thighs, and rises.
DARRYL Okay, man.
WILLIAM Okay, man.
William slips on corduroy jacket, over a tie-dyed shirt.
Well, it's definitely a look.
Mom appears more nervous than her son.
ELAINE I worry about the drunk drivers.
WILLIAM Mom.
WILLIAM I'm 15.
WILLIAM Right?
ELAINE Yes, you're 15.
ELAINE "And here's that money I owed you."
She reaches in a small box near the door, gives him twenty bucks.
It's their routine.
ELAINE (cont'd) Your dad's favorite joke.
ELAINE (cont'd) I don't do it as well.
WILLIAM I thought it was pretty good.
ELAINE Keep the small bills on the outside.
ELAINE And call me if anyone gets drunk.
WILLIAM I will call you if anyone anywhere gets drunk.
ELAINE Good.
WILLIAM And don't take drugs.
ELAINE Ha ha.
ELAINE Very funny.
ELAINE See -- sense of humor.
ELAINE Have fun at the dance.
ELAINE I'm glad you're making friends.
They move to the door, and he steadies her, as if to remind her she's not going.
He opens the door.
She's a wreck, and she knows it.
WILLIAM Mom?
ELAINE Yeah -
WILLIAM (loving but firm, as if to a dog.)
WILLIAM Stay.
ELAINE Oh...
ELAINE okay.
WILLIAM I-love-you-bye.
He opens the door.
Neil Young.
"Sugar Mountain."
Watching him leave is always a killer.
She's not getting any better at it either.
She folds her arms tightly across her chest.
Penny waist by her car, down the hill, sporting a different more elegant look.
She cups her hands and yells up to him.
He hikes down the hill, squishing down the water plants, almost falling, the first time we've seen him happy in his own skin.
Miss Penny Lane's yellow Vega makes the big swing onto Sunset Boulevard.
She sings along to the obscure words of Led Zeppelin's "Dancing Days."
William takes it all in from the passenger seat.
Huge billboards advertise not cigarettes or beer, but albums.
It's a wondrous piece of geography for any rock fan.
Shot moves in as William, watches, takes it all in.
He moves his head outside the window to see fully.
Her windshield is cracked along the side.
PENNY LANE The Continental Hyatt House.
PENNY LANE Also known as The Riot House.
PENNY LANE Every band stays here, all the ones that matter.
PENNY LANE The Who.
PENNY LANE Zeppelin.
PENNY LANE Alice.
PENNY LANE Bowie.
PENNY LANE English bands.
PENNY LANE American bands.
PENNY LANE We all know each other.
PENNY LANE Twenty- four hour room service.
PENNY LANE Like us, they were outsiders.
PENNY LANE They were so outside, they're inside, and insiders never even knew it, because they're outsiders and they are inside a place outsiders will never be.
PENNY LANE And why are we even talking about it?
PENNY LANE If you're really an insider, you're never gonna say it.
PENNY LANE You know what I mean?
WILLIAM Yeah.
WILLIAM Yes.
She makes a swift turn into a secret parking spot near the hotel.
PENNY And we're not gonna hang out with Russell.
PENNY You can, but not me.
WILLIAM What is it with you and Russell?
Neil Young and Crazy Horse's "Cinnamon Girl" ricochets across the Strip.
It's blasting from cars tuned into KMET.
Penny now wears her green faux-fur trimmed coat.
She grabs William's hand, steadying her hat at the same time.
They dart across the busy street.
She stumbles a little on her platforms.
He steadies his taller date.
They are a good team as they pass one of several humming tour busses parked out front.
Penny blasts into the Continental Hyatt House, William on her arm.
The lobby of this bastion of seventies rock is more alive than most clubs.
It's a swirling mass of Roadies carrying Halliburton briefcases plastered with tour stickers, mingling Rockers, and more than a few Groupies with lower-ambitions and taller-platforms than Penny Lane.
The feeling is communal, illicit, intoxicating.
The secret community of rock.
Penny attracts a hailstorm of friends and comrades.
PENNY LANE It's all happening.
PENNY LANE And I'm about to use you as protection.
ROADIE # 1 Penny Lane!!
PENNY LANE These guys are with Alice Cooper.
PENNY LANE I'm going to pretend I don't know them.
ENGLISH ROADIE # 2 Penny!!
ENGLISH ROADIE # 2 Does Alice know you're here?
PENNY LANE I'm just showing my very dear, very wonderful friend around.
PENNY LANE He's a very important writer - he knows Lester Bangs.
PENNY LANE I'm responsible for his moral conduct while he's abroad.
ROADIE # 3 Penny Lane!!
ROADIE # 3 God's gift to rock and roll!!
PENNY LANE I'm retired.
PENNY LANE And don't argue with me!
ROADIE # 3 Again?
PENNY LANE Have we met?
Effortlessly touching an arm here and there, charming all - she had four men suddenly circling her.
PENNY LANE (cont'd) I've made a decision.
PENNY LANE (cont'd) I'm going to go traveling in India.
PENNY LANE (cont'd) Then I'm going to learn how to play the violin.
PENNY LANE (cont'd) Then I'm going to go to college for one year.
William looks at her, perplexed and a little hurt.
What about Morocco?
ROADIE # 2 There's nothing they could teach you in college, darling.
ROADIE # 2 Call Alice.
ROADIE # 2 He's under the name Bob Hope.
ROADIE # 1 I heard you were with Russell from Stillwater.
PENNY Please.
PENNY I throw the little ones back.
Lusty laughs circle William.
Overlapping this dialogue is the appearance of our friend Polexia.
POLEXIA Ian Hunter is a fucking asshole!
WILLIAM Polexia!
POLEXIA Opie!!!
She hugs him like a long-lost friend, knocking the air out of him.
And now overlapping this action, appears Superfan RIC NUNEZ, 14.
His eyes are forever moist, but he's oddly formal and never feels worthy of the rockers he idolizes.
Tonight he wears a custom homemade t-shirt with iron-on block letters.
It features the four Led Zeppelin symbols and the words: "TO BE A ROCK AND NOT TO ROLL."
A felt-tip pen is still in his quivering hand.
Nunez walks with them, backpedaling as he says:
RIC It's all happening.
RIC I just saw them on the seventh floor!
RIC Mr. Jimmy Page...
RIC Mr. John Paul Jones...
RIC Mr. Robert Plant signed my shirt in the elevator!!
RIC Five minutes ago, he touched this pen.
RIC Please don't smear it.
RIC And Bonzo's gotta new motorcycle in the hotel!
PENNY Ric is a Zeppelin fan.
WILLIAM Yeah, I picked that up.
PENNY He tours with them, but not "with" them.
RIC They're on the 12th floor, but there's guards there!
RIC So you gotta go to the tenth floor and go up the back steps.
PENNY LANE This is my very dear, very close, very wonderful friend William Miller, he is very close with Lester Bangs.
RIC It's all happening!!
RIC See you in Cleveland!
Ric rushes back to the elevators.
PENNY LANE I'm retired!
PENNY LANE Doesn't anybody believe me!?
Penny nearby as William picks up the house phone.
He shouts over the din.
WILLIAM Harry Houdini, please.
As he waits, he discreetly pockets the matches, hotel pad and pencil next to the housephone.
William, Polexia and an ambivalent Penny walk the hallway, looking for the room.
William looks in the passing open doors, each one a different window into another world.
PENNY LANE Okay.
PENNY LANE Time to put on the lampshade.
Up ahead, the door to their smallish hotel room is open.
Inside, a band party in full swing.
A clunky early-model boom box segues from James Brown's "Make It Funky" to Led Zeppelin's "Gallows Pole."
Russell Hammond is the center of this party, jabbing out the chords, playing along on guitar.
Much singing echoes all around.
It's a hotel-room Hootenanny, and all members of the band are present.
Penny Lane takes a breath and enters, with arms extended and pointing in opposite directions.
She does a flawless stewardess imitation, with proper hand gestures, to a loud party ovation.
PENNY LANE (cont'd) "Ladies and Gentlemen.
PENNY LANE (cont'd) Please extinguish all smoking materials and notice that the captain has turned on The No Smoking sign.
PENNY LANE (cont'd) Your seat and tray tables should be locked in their full and upright positions."
She is instantly and overwhelmingly, the life of this party.
Russell joins William.
RUSSELL Alright.
WILLIAM Alright.
Russell places a beer in William's hands, and exits.
PENNY LANE "In the unlikely event of a water landing, the seat below you will serve as a -"
PENNY LANE Oh, the hell with it.
They all applaud her, laughing.
William watches her with wonder, as she turns his way and winks.
Jeff approaches the alluring Polexia, and goes to get her a beer.
Meanwhile, Polexia sidles up to William.
She sees him watching Penny at the other side of the room.
POLEXIA Act One, in which she pretends she doesn't care about him.
POV shot travels to Russell, strumming the guitar that is always a part of his body.
Russell is watching Penny Lane surreptitiously.
POLEXIA (cont'd) Act Two, in which he pretends he doesn't care...
POLEXIA (cont'd) and goes right for her.
Russell moves towards Penny.
POLEXIA (cont'd) Act Three, in which it all plays out the way she planned it.
POLEXIA (cont'd) She'll eat him alive.
WILLIAM We've got to stop them.
POLEXIA Stop them?
POLEXIA You were her excuse for coming here.
PENNY I need ice!
Penny disappears out the door, across the hallway.
Russell follows a moment later.
The kid's eyebrows rise.
Polexia regards the kid with affection, adjusting his collar and peeling a hair off his jacket.
POLEXIA I just worry about people using her.
POLEXIA You know?
POLEXIA 'Cause she brings out the good side in everybody else, but what do they do for her?
POLEXIA Life kills me.
POLEXIA Do you have any pot?
WILLIAM Not on me.
POLEXIA Do you smoke?
WILLIAM No.
WILLIAM But I...
WILLIAM I grow it.
WILLIAM I grow it.
Polexia looks at the kid, laughing at his poor job of lying.
POLEXIA You're funny.
POLEXIA You know, if you were only taller, English, rich, a guitar- player and older...
WILLIAM I'd be someone else.
POLEXIA Yeah.
POLEXIA Good point.
Jeff appears with her beer, and she whispers in the kid's ear before she exits with Jeff Bebe.
POLEXIA (cont'd) Bless me father for I may sin tonight.
The kid watches, as the boom box plays an obscure favorite of Russell's, Eddie Giles' "Losin' Boy."
There is the sound of a motorcycle somewhere down the hallway.
The ice machine makes new cubes with a grinding noise.
Penny puts ice in her glass.
Behind her, Russell moves into frame, hands delicately riding the sides of her body.
A motorcycle roars by, just outside the door, as Penny moves away from Russell's exploring hands.
PENNY How does it end?
RUSSELL What?
PENNY You know - the story about the girl who dumps the guy who has an ex-ex wife -- the one we don't talk about -- and gets a hundred...
PENNY okay, five letters from him, and then doesn't even leave a pass in San Diego.
PENNY Wake up!
PENNY I'm retired and I never believed you anyway.
PENNY You're too talented and too good-looking to be trusted and everybody knows it.
RUSSELL You're retired like Frank Sinatra is retired.
She makes a scoffing noise.
He moves to the ice machine, with a glass of his own.
RUSSELL (cont'd) Miss Penny Lane.
RUSSELL (cont'd) Let me tell you what rock and Roll will miss the day you truly retire.
He tosses cubes in his glass, one by one.
After the first cube:
RUSSELL (cont'd) The way you turn a hotel room into a home.
RUSSELL (cont'd) The way you pick up strays wherever you go.
RUSSELL (cont'd) Like Pied Piper.
RUSSELL (cont'd) The way you know the words to every song.
RUSSELL (cont'd) Every song.
RUSSELL (cont'd) Especially the bad ones.
RUSSELL (cont'd) Mostly the bad ones.
RUSSELL (cont'd) That green coat in the middle of summer.
RUSSELL (cont'd) The real name you won't reveal.
RUSSELL (cont'd) And.
RUSSELL (cont'd) I'd keep going, but my glass if full.
PENNY Damn.
He kisses her powerfully, hands at his sides.
She fights to keep her hands off him.
Bonham's motorcycle rips by, just outside the door.
RUSSELL Come to Arizona.
PENNY Never.
RUSSELL We leave Thursday morning.
RUSSELL 9 AM.
RUSSELL And pack light this time.
RUSSELL Jesus.
They kiss.
The motorcycle speeds by again, just outside.
The hallways are crowded, as William looks at the closed door of the ice room.
He leans against the wall, alone now.
Trying to look like he belongs.
Behind him, most of the band has disappeared into other rooms, leaving only hangers-on in their places.
Music.
We pan across cubicles bustling with laid-back fervor.
These are the San Francisco-based main offices of Rolling Stone Magazine.
We have arrived for the waning days that this magazine could still be called, with a straight-face, an "underground" publication.
Their mounting success crowds the edges of every frame.
Camera catches the Annie Leibowitz portraits that hang on the walls -- Lennon, Jagger, Rod Stewart, James Taylor.
We find editor BEN FONG-TORRES, 29, in his cramped cubicle.
Sitting nearby is curly-haired and mustachioed Star Staff writer, DAVID FELTON, 32, who smokes his cigarettes with a long holder.
Felton reads one of William's articles, chuckling.
BEN FONG-TORRES William Miller?
William is on the phone in his own small room.
WILLIAM This is he.
BEN Crazy.
BEN William, this is Ben Fong- Torres.
BEN I'm the music editor at Rolling Stone Magazine.
BEN We've got a copy of your stories from the San Diego Door.
BEN This is the same William Miller?
William instantly, nervously alters his voice to sound older.
WILLIAM Yes it is.
BEN Voice of God, howling dogs, the spirit of rock And roll...
BEN this is good solid stuff.
WILLIAM Thanks...
WILLIAM thanks.
BEN You should be writing for us.
BEN Any ideas?
WILLIAM How about Stillwater?
BEN Crazy.
BEN New album...
BEN their third...
BEN starting to do something.
Ben shuffles through papers, looking for a tour itinerary on his promotional-material laden-desk, automatically plotting the piece aloud.
BEN (cont'd) Stillwater.
BEN (cont'd) Hard-working band makes good.
BEN (cont'd) Get 'em to respond to the critics who dismissed the first two albums as workmanlike.
BEN (cont'd) Guitarist is the clear star of the band.
BEN (cont'd) Crazy.
BEN (cont'd) Let's do three- thousand words.
BEN (cont'd) You'll catch up to them on the road.
BEN (cont'd) We'll set up billing -- don't let the band pay for anything.
WILLIAM Sounds good.
BEN We can only pay -- lemme see, three- thousand words -- seven hundred dollars.
The kid's eyes widen.
BEN (cont'd) Alright, a grand.
BEN (cont'd) What's your background?
BEN (cont'd) You a journalism major?
WILLIAM Yes.
BEN What college --
Elaine now gets on the extension.
ELAINE Honey, I need you to do that thing that fixes the garbage disposal --
She hangs up.
The kid is paralyzed.
BEN Well, I know how my lady gets when I don't Snap to it -
WILLIAM Crazy.
BEN Crazy!
BEN I'll let you go.
BEN Call me at the San Francisco office tomorrow.
The great Lester Bangs stands in the promotional album-clogged bedroom of his Birmingham, Michigan, home/office at Creem Magazine.
There is nothing in frame that does not deal with music.
In the background, a scratchy and chaotic Coltrane record.
LESTER BANGS Beware Rolling Stone Magazine.
LESTER BANGS They will change your story, they'll re- write it and turn it into swill.
LESTER BANGS Beware!!
WILLIAM But besides that, what would be wrong with it?
LESTER BANGS You have starry eyes, my friend.
LESTER BANGS Look.
LESTER BANGS Do the story.
LESTER BANGS It's a good break for ya.
LESTER BANGS But remember this --
The kid listens intently, and makes notes.
LESTER BANGS (cont'd) ...
LESTER BANGS (cont'd) don't do it to make friends with people who are trying to use you to further the big business desire to glorify worthless rock stars like Stillwater.
LESTER BANGS (cont'd) And don't let those swill merchants re-write you.
WILLIAM ...
WILLIAM swill merchants...
LESTER BANGS Now.
LESTER BANGS What are you listening to?
William knocks on the teacher's lounge door.
A Teacher answers, protective of their sanctuary.
WILLIAM I need to talk to Mrs. Deegan, from Journalism.
Mrs. Deegan appears in the doorway.
The sun is still shining.
It's late afternoon, as Elaine Miller exits her car and arrives home.
She sees a few extra cars in the driveway, is immediately suspicious.
Elaine arrives to find William, Mrs. Deegan and Darryl awaiting her in the living room.
It's a 1973-style intervention.
They wear sunny, compassionate smiles.
ELAINE Whatever it is, the answer is no.
MRS. DEEGAN Elaine, we need to talk to you.
MRS. DEEGAN Nothing is wrong.
MRS. DEEGAN I am a teacher.
MRS. DEEGAN You're a teacher.
MRS. DEEGAN We speak the same language.
Mom sits down.
She is fully engaged and worried, her natural state.
MRS. DEEGAN (cont'd) Now I'm not a jump-up-and-down person, but something wondrous has happened to William.
MRS. DEEGAN (cont'd) And you have every reason to be happy...
MRS. DEEGAN (cont'd) ...
MRS. DEEGAN (cont'd) and calm.
Carefully gauging Elaine's face, the teacher continues.
MRS. DEEGAN (cont'd) William has been gifted with a shining opportunity in the world of journalism.
MRS. DEEGAN (cont'd) Through a love of music, and at an oddly-young age, he has received a major assignment from a national publication called Rolling Stone Magazine.
Mrs. Deegan produces a copy, and places it on Elaine's lap.
It sits there like the plague.
MRS. DEEGAN (cont'd) Now you are rather famously not a fan of rock music, but such are the ironies of life, that happens to be the very topic of William's assignment -
MRS. DEEGAN (cont'd) - rock music.
MRS. DEEGAN (cont'd) A band.
ELAINE Honey, what are you doing here?
DARRYL Moral support.
Mom looks evenly at her son, seated opposite her in this small living room.
ELAINE What's involved?
MRS. DEEGAN Well.
MRS. DEEGAN It's a great opportunity.
MRS. DEEGAN He'll be well-paid, and published nationally --
MRS. DEEGAN -- and he'll go on tour with a rock band for four days.
MRS. DEEGAN No small planes...
MRS. DEEGAN he travels on a bus.
ELAINE Is it time for me to say something?
MRS. DEEGAN Sure.
ELAINE No.
MRS. DEEGAN And in anticipation of that response -
ELAINE No.
MRS. DEEGAN -- William has prepared --
ELAINE "Lo, that which I have feared has come upon me."
WILLIAM "He who jealously guards his fears, quietly yearns to bring them about!"
Mrs. Deegan admires their high-strung intellectual parrying, makes an impressed noise.
ELAINE No.
ELAINE I have raised him to be an honor student, which he is.
ELAINE We have agreed on all our goals.
ELAINE We raised him to be a lawyer, we moved here to be near the finest law school in the West.
ELAINE Plus, he has finals coming up, and in one week he graduates with all his friends
DARRYL He's got no friends!!
WILLIAM Darryl.
WILLIAM Please.
Nearby, having anticipated all of the above, William nods to Mrs. Deegan, and stands.
MRS. DEEGAN Elaine, may I present to you...
MRS. DEEGAN your own son.
William takes a lawyerly stroll, turns to face his mom.
WILLIAM Lady of the Jury.
WILLIAM I wish to disprove the prevailing false belief that rock music is based on drugs and sex.
WILLIAM True, perhaps at one time...
WILLIAM but rock music is different now.
WILLIAM It is now performed by hard-working intellectuals, with...
WILLIAM with blazing intellectual pursuits, and I am going to play for you a piece of music designed to show you that my thesis is correct.
ELAINE This is going to be hell.
Across the room, Darryl takes his position near the stereo.
WILLIAM The song is based on the literature of Tolkien...
WILLIAM and it's mystical attempt to elevate humanity has been successful throughout the world...
WILLIAM this song will change your life.
Mom stifles a cough.
William nods to Darryl, who reverentially drops the needle with a thud.
Mom is trapped, as we listen to silent static...
and then...
the opening notes of Led Zeppelin's "Stairway to Heaven."
William gives his Mother the album cover's inner-sleeve with lyrics.
WILLIAM (cont'd) We ask you only to listen.
Camera passes across their serious and expectant faces.
The intro in not short.
We listen, just watching their faces, as Elaine becomes increasingly impatient.
When is it going to start - Soon.
Immediately, overlapping, the vocal begins.
("There's a lady who's sure all that glitters is gold."
Sprinklers click across the lawns.
("...
and it makes me wonder...
")
Mom adjust herself in the chair, listens politely, checks her watch.
She looks at William.
Sprinklers continue.
("If there's a bustle in your hedgerow...
")
Mom listens fitfully.
The song continues.
Sprinklers shut off.
Music is now blasting.
("To be a rock, and not to roll...
")
Mom's face remains stoic to the bitter end.
("...
and she's buying the Stairway to Heaven."
) The song ends.
Silence.
All look to Elaine.
They wait on her response.
We hear the turntable arm return to its cradle.
ELAINE What am I supposed to say?
ELAINE You say it's Tolkien, fine.
ELAINE They sound like nice kids.
ELAINE Is it meant to elevate humanity?
ELAINE "Sure, let's elevate humanity.
ELAINE After we sell you drugs and sex."
ELAINE All I have is my honesty.
ELAINE That's what I believe, and that's what I know.
ELAINE Oh.
ELAINE Here's a nice ad.
She holds up the magazine.
And ad reads, in large bold type:
ELAINE (cont'd) You've clearly ganged up on me, and I still say no.
ELAINE (cont'd) No no no no no no no.
She shuts her eyes, and blurts out something against her better judgement.
William nods gratefully, and exits frame.
Hold on the empty chair, as drums herald the beginning of the Allman Brothers Band's "Trouble No More" from Live at Fillmore East.
SHOT MOVES IN ON ELAINE who feels a very particular kind of loneliness.
It's the loneliness she got married, and then raised a family, to escape.
An empty Heineken beer bottle rolls up and down the aisle, taking us to William.
William picks up the bottle and places it in the seat back pocket in front of him.
He has joined the circus, and the feeling of being here is a lot more lonely and forbidding than he expected.
The bus struggles to make it up the hill, back rows shuddering loudly, as music continues.
DICK C'mon, Doris!
DICK Darling Bus.
DICK You can make it!
The Stillwater Tour Bus rumbles down the desert highway.
The destination banner reads - ALMOST FAMOUS -- TOUR 73.
Music continues.
William strains for a look at Russell five rows up.
He plays slide guitar, working out a part.
Next to Russell is Penny Lane.
Penny raises an early-model Polaroid camera and - flash - takes a picture of a nearby sleeping Jeff Bebe.
PENNY Gotcha.
Jeff grumbles from the depths of a hangover.
Penny stuffs the shot in her pocket.
William watches, his private heart pounds.
Polexia appears and sits next to him, noticing his shyness.
POLEXIA Do you have any pot?
WILLIAM No.
WILLIAM I'm a journalist.
POLEXIA Well, go do your job then.
POLEXIA You're on the road, man.
POLEXIA It's all happening!
POLEXIA Get in there.
POLEXIA Go talk to 'em!
Challenged, William rises and approaches Russell.
He fixes the charismatic guitarist in his sights.
Shot takes him down the aisle to the jamming star guitarist.
He crouches in the aisle and talks to Russell who immediately seems moody.
His mood is in the air.
WILLIAM Russell.
WILLIAM Do you think we might be able to find some time to talk when we get to Phoenix?
WILLIAM I want to interview everyone separately...
WILLIAM and I felt we'd start with you and me.
Nearby, Jeff now listens in, feeling immediately jealous.
RUSSELL Absolutely.
Russell turns away.
The kid squats uncomfortably in the aisle, babbling on.
WILLIAM Because I've got a thing in a couple days.
RUSSELL What.
WILLIAM It's a...
WILLIAM thing where...
WILLIAM uhm...
WILLIAM you go there to graduate.
WILLIAM School.
RUSSELL I never graduated.
RUSSELL And look what happened.
RUSSELL You're here interviewing me.
Good point.
Laughs from everybody listening nearby.
It's a good line.
William makes a quick jot in his notebook.
RUSSELL (cont'd) No no no.
RUSSELL (cont'd) Don't put that in Rolling Stone.
RUSSELL (cont'd) My bio says I graduated.
RUSSELL (cont'd) We'll come up with something better later.
RUSSELL (cont'd) Just enjoy the ride.
Russell eyes the notebook suspiciously before turning away.
Penny notices William's discomfort, laughing warmly, all while grabbing a Coke and giving one to nearby bassist Larry.
LARRY How did you know I was thirsty?
He didn't even realize he was thirsty, but he is.
He nods thanks to Penny, the perfect road companion for all.
And then Penny gives the other Coke, her Coke, to William.
He accepts it too, and starts back to his seat.
He's been blown off, and he knows it, but before he exits Penny grabs his arm and whispers in his ear:
PENNY I may need to stay in your room tonight.
PENNY Russell's in a bad mood.
PENNY He's very Bob Dylan in Don't Look Back today.
PENNY He's trying to write.
William nods cooly -- they are comrades -- and returns to his seat.
A large joint passes in front of him, across him, to Polexia, as everyone cheers Doris the Bus rumbling up another hill.
POLEXIA Want some?
WILLIAM No thanks.
A wall of pot smoke is exhaled, right into his face.
It surrounds him like a cloud.
The bus shudders, as Russell continues playing slide up ahead.
Elaine sits in her living room, filled with her books.
Large Department store photos of her children on the wall.
She feels her own loneliness, and his too, as she dials a phone number.
ELAINE Has William Miller arrived yet?
ELAINE He hasn't.
ELAINE Could you give him a message as soon as you see him?
Several hours later on this ride.
Outside, night and desert.
Inside, a few cigarettes, a joint of two glow in the darkness of the bus.
The end of the Led Zeppelin classic "Whole Lotta Love" plays from the bus stereo, full blast.
Everybody is free and anonymous in the dark.
They sing at full-volume.
William looks out the window in wonder.
ZEPPELIN/ALL "Way down inside...
ZEPPELIN/ALL (woman) woman...
ZEPPELIN/ALL you need...
The ten-ton guitar chord of Jimmy Page.
ZEPPELIN/ALL (cont'd) "Loooooooooooooooooooooooovvve...
John Bonham's drums thunder through the bus, everybody still singing as they dip down into the city ahead, Phoenix.
William watches the living documentary around him.
He writes furiously in the green notebook, scribbling in the dark, trying to steady his writing on the bumpy bus.
Behind him, someone is beating along to the song on his seat.
He never want to leave this world.
All enter the lobby like warriors, in a pack.
The hotel chairs are spotted with curious hangers-on, decked out and lounging.
Dick is already stationed, as always, at the front desk.
The sad state of hotel service grates on a road dog like Dick.
He is forever teaching others their jobs.
DICK Jeff, Tony...
DICK Keys...
DICK keys...
DICK keys...
DICK room list...
DICK If it doesn't have a number on it, it ain't ours!
He gives key and a stack of messages to Russell, and turns to William who he makes feel more important.
Penny is nearby with her suitcase and tackle box purse.
William watches Russell's guitars whisked away - they are luggage-numbered 1, 3, and 4.
DICK (cont'd) The Enemy!
DICK (cont'd) Here you go, here's the key to your palatial suite, room list, plus let me give you a luggage tag.
DICK (cont'd) You're Number 42.
CLERK Is this Mr. Miller?
CLERK You have a message from Elaine.
WILLIAM Thanks.
CLERK She's a handful.
WILLIAM I know.
William cooly takes the folded message, doesn't look at it, and tries to pretend this embarrassing moment didn't happen.
Jeff exchanges a look with Russell.
Nearby, the walking commotion arrives, clacking through the lobby.
It's Sapphire.
Last night's clothes are now today's.
She holds a travel case, and hanger with some odd blouses.
SAPPHIRE Finally, you're here!!
SAPPHIRE They kicked me out of my room!
SAPPHIRE Fuck Ozzy!
She hugs Penny Lane.
Estrella appears, happy to have help with Sapphire.
ON RUSSELL who approaches William.
RUSSELL Come by in a few minutes.
RUSSELL We'll do the interview.
The kid exits and goes to join Penny, who is still comforting Sapphire.
Russell looks through his messages.
The guitar, now in a case, never leaves his hand.
Jeff Bebe approaches, regarding William standing with Penny and the girls.
Intrigue is swirling in the lobby.
JEFF I'm worried, man.
RUSSELL Naw, we can trust him.
RUSSELL He's a fan.
JEFF But it's Rolling Stone.
JEFF He looks harmless, but he does represent the magazine that trashed Eric Clapton, broke up Cream, ripped Led Zeppelin, and wrote that lame story about the Allman Brothers Band that bummed Duane out before he died.
JEFF Don't forget the Rules.
JEFF This little shit is the Enemy.
JEFF He writes what he sees.
JEFF But it would be cool to be on the cover.
RUSSELL Leave it to me.
RUSSELL We'll get a good story.
JEFF Plus our girlfriends read this magazine and -
JEFF -- you know.
RUSSELL You made your point.
RUSSELL I'll take to him.
Penny speaks confidentially to him.
If she is slightly bossy, it is only because she's good at logistics, emotional and otherwise.
PENNY Can Sapphire stay in your room tonight?
PENNY She had a big fight with Ozzy, and Polexia's not working out with Jeff Bebe.
PENNY You just have to remember...
PENNY these guys are jealous, insecure, talented, egocentric, and manipulative geniuses...
PENNY they're lead-singers.
PENNY They can say "I love you" to 20,000 people...
PENNY but any fewer is a real problem.
PENNY Jeff Bebe has so much jealousy over Russell that he can't express.
PENNY Plus, he never slept last night.
PENNY You keep Sapphire and I'll stay with Russell.
William covers his disappointment over losing Penny as a roommate.
Cooly:
WILLIAM Sure.
WILLIAM I'll take her.
POLEXIA Me too?
WILLIAM Sure.
Estrella arrives with travel bag, equally homeless, looking hopeful.
WILLIAM (cont'd) If there's room -
Penny squeezes him.
He feels cool...
but the girl he really wanted to stay in his room now joins Russell, disappearing into the elevator.
He looks down at the message in his hand, and opens it.
It reads: DON'T TAKE DRUGS!
He snaps it closed quickly, before anyone can see.
59A IN.
RUSSELL's ROOM -- NIGHT 59A
Russell plays acoustic guitar, a notebook cradled on his lap.
Trying to write.
It's coming slowly.
Shot moves off him, past a flickering television, onto Penny who silently and intently watches Russell as if he's a rare and beautiful bird.
He looks over at her - she turns away quickly.
He goes back to work.
Tries to catch her watching him again.
She turns away just in time.
Stillwater's "Fever Dog" plays from the t.v.
radio.
William on the bed, a thick local phone book on his lap.
His hotel room.
He watches self-consciously as the girls go about the ritual of inhabiting a room on the road.
Sapphire flutters a paisley scarf over the room lamp.
Polexia puts a towel along the crack of the door, blows out the glowing embers on too- many sticks of incense, and moves to the phone.
Estrella has joined them as well, complete with a bag full of shoes.
Instantly, we have atmosphere and not much room left in this, the smallest room in the hotel.
William thumbs through the phone book with fascination.
WILLIAM All these people.
WILLIAM And they all live in Phoenix.
POLEXIA Hi Dad!!
POLEXIA I can't talk long!
POLEXIA I'm here in Paris.
POLEXIA I'm staying in another Youth Hostel with no phone and no address for mail!!
WILLIAM Alex.
WILLIAM Lowbatz.
SAPPHIRE I was the one who told him what to tattoo on his fingers, I was the one who made his shirts...
SAPPHIRE I was there when his wife left him.
WILLIAM Charles.
WILLIAM C.
WILLIAM Swoop.
She's reading from a European tour book.
WILLIAM Paul and Debbie Finger.
ESTRELLA Oh my God.
ESTRELLA Simon Kirke of Bad Company is by the pool.
The girls mobilize by the window.
William is increasingly aware that he is an outsider in his own tiny room.
He tries to organize his stuff in the corner.
ESTRELLA Is anybody here as worried about Penny and Russell as I am?
She winks at William, who looks away.
SAPPHIRE Ooo, watch out - whoever you look at when you say that - that's who you really mean.
Polexia hands up and throws a pillow at Sapphire, the kid watches these girls like a tennis match.
Russell puts down his guitar.
RUSSELL You know.
RUSSELL We should talk about what we don't talk about.
PENNY We don't have to.
RUSSELL No, I - I went to Catholic school.
RUSSELL I believe in guilt and...
RUSSELL you know, if there's any to be had, I pretty much want to roll around in it.
PENNY I don't believe in attachments.
PENNY No boundaries.
PENNY Just the music.
RUSSELL I'm just saying, it's okay to talk about it.
Penny stands and turns.
She speaks the word.
PENNY Leslie.
Russell nods.
The name is out in the open.
PENNY (cont'd) Leslie.
PENNY (cont'd) Leslie.
PENNY (cont'd) Leslie.
PENNY (cont'd) Leslie.
PENNY (cont'd) Leslie.
PENNY (cont'd) Leslie.
PENNY (cont'd) Leslie.
PENNY (cont'd) Leslie.
RUSSELL Alright - now we're talking.
But she continues, saying the name in a multitude of different ways, in different accents, and with different degrees of indifference and passion and lust and play-acting and mock- drama.
As he listens and studies this ethereal creature for meaning.
Is she mocking him?
In love with him?
Taunting him?
Seducing him?
PENNY Leslie.
PENNY Leslie.
PENNY Leslie.
PENNY Lesssssslie.
PENNY Leslie.
PENNY Leslie.
PENNY Leslie.
PENNY Leslie.
PENNY Leslie.
PENNY Leslie.
PENNY Leslie.
PENNY Leslie.
PENNY LESlie.
PENNY Leslie...
She continues saying it until it no longer has meaning.
And finally she sits next to him.
PENNY (cont'd) Now.
PENNY (cont'd) Have I helped you get that off your chest?
They kiss.
The girls continue their settling-in process.
SAPPHIRE Opie, can I order room service?
The nickname "Opie" re-opens a nagging wound.
Polexia hangs up, and begins to dial again.
WILLIAM Okay.
WILLIAM You guys.
WILLIAM Wait.
WILLIAM Put down the phone, Polexia.
WILLIAM First, this is my room...
SAPPHIRE Come on, you're a fan like us.
SAPPHIRE You're on our side of the line.
WILLIAM Second.
WILLIAM I'm not Opie.
WILLIAM Alright?
WILLIAM Opie is a little boy.
WILLIAM I'm here to do a job.
WILLIAM I am a professional.
ESTRELLA Ooooooo, sorry, Mr. 42.
WILLIAM Third!
WILLIAM ...
WILLIAM this phone is a big, big deal.
WILLIAM In a minute, I have to go interview Russell.
WILLIAM Do not answer this phone if it rings.
WILLIAM I have family members with severe anxiety Problems.
WILLIAM She will not understand.
POLEXIA But what if Ozzy calls Sapphire?
POLEXIA And I gave Jimmy Page this number.
ESTRELLA Or a guy who looked like Jimmy Page.
William looks at their troubled faces, full of too much-longing and too much make-up.
WILLIAM Okay.
WILLIAM I have a solution.
WILLIAM Answer the phone.
WILLIAM But if anyone without an English accent is on the phone...
WILLIAM Just hang up.
WILLIAM Or say it's the wrong room.
They nod.
It's a good plan.
The hanging sign on the door reads: DO NOT DISTURB.
William knocks on Russell's door.
A maid pushes up against him with her cart, which now blocks the hallway.
A group of golf conventioneers are now trapped behind the maid cart.
They ease past William as he negotiates with Russell through the door.
We hear Penny's giggle.
Then the door opens, and it's Penny looking ravishing.
In the background, Russell sits shirtless at the table.
He playfully pelts the kid with crumpled up wads of hotel stationery.
PENNY Don't worry.
PENNY Some to the radio interview.
WILLIAM No, I'm fine.
WILLIAM I'll just interview Jeff Bebe some more.
She shuts the door quickly.
It hurts a little.
He picks up the wadded pieces of paper, stuffs them in his pocket.
He leaves the door and helps himself to some soap and pencils and matches from the nearby maid's cart.
Then he returns to Russell's door.
He can't help but listen to the muffled sounds of laughter, just for a moment, escalating.
He flips the sign over: HOUSEKEEPING PLEASE ENTER - CLEAN ROOM.
Humble Pie.
"Thirty Days in the Hole."
Russell and band enter the radio station, passing through the now-empty front office.
As always, Russell sets the tone.
He's feeling good.
Stillwater takes over -- they feel mighty, like the Beetles, as they climb across chairs, rearrange wall hangings and gold records and head down the small hallway to the control room interview.
Rolling with the flow are William and Penny in her green coat.
He tries to distance himself from her -- still a little stung by the earlier hallway rebuff -- but she will have none of it.
She privately shares every great passing moment with him.
He tries not to succumb to these charms.
It's hard.
Music segues to Stillwater's own "Fever Dog."
Stillwater's own record spins, and it sounds good to everyone in this room.
Russell takes a seat near the open mike.
Jeff Bebe is quick to take the other seat, arranging himself to be just as close to the microphone as Russell.
William watches all as he sits at the dark back of this control booth.
Stillwater sits with late-night progressive disc-jockey QUINCE
Quince takes a long hit from a joint and does not pass it.
The entire Stillwater band is now collected in the studio and ready for the interview.
William can't avoid looking at Penny Lane, who looks great tonight.
She catches him, and he barely looks away in time.
Polexia, newly reconciled with Jeff, notices.
The very mellow disc-jockey eases up to the microphone, as the finale of "Fever Dog" is just ending.
QUINCE ALLEN The guitar of Russell Hammond.
QUINCE ALLEN "Fever Dog"...
QUINCE ALLEN The band is Stillwater.
QUINCE ALLEN Watch with your mind as they materialize.
Band members gets closer to the microphone, preparing to speak.
Quince lowers his head, shutting his eyes and getting into the music as the song plays out.
The phone rings.
Estrella answers.
ESTRELLA William's room.
Ben Fong-Torres is calling from Rolling Stone.
BEN Can I please speak to him?
BEN This is Ben Fong-Torres at Rolling Stone.
Estrella panics, hangs up quickly, as if the phone has just caught fire.
ESTRELLA I think I just messed up!
Quince raises his head and continues on-the-air.
The same song is still ending.
QUINCE Look at the dogs, wearing the funny hats.
QUINCE Juggling just for you.
QUINCE Freaks and family...
Penny shoots William a look.
Do you believe this guy?
QUINCE (cont'd) It's Quince, with Stillwater.
QUINCE (cont'd) Here.
QUINCE (cont'd) Live.
QUINCE (cont'd) It's the Night Circus.
The band scoots closer to the microphone, ready to talk.
Quince continues, looking meaningfully at the band.
They are waiting...
eager for a chance to speak.
QUINCE (cont'd) Every minute a baby is born somewhere..
QUINCE (cont'd) Life.
QUINCE (cont'd) Death.
QUINCE (cont'd) Hermetically sealed bags of human emotion.
QUINCE (cont'd) Bags of love...
QUINCE (cont'd) bags of kindness?
QUINCE (cont'd) How'd you get together?
As Jeff eagerly speaks, Quince lowers his head and listens...
feels...
the words of his guests.
JEFF Well...
JEFF not to get into a "me" thing...
JEFF this is Jeff talking...
JEFF but I did start the band, some time, actually, ago.
JEFF This is back when we were the Jeff Bebe band, and I placed an ad in a magazine called Peaches looking for a guitarist and Russell Hammond answered.
Quince nods, head bowed, swaying slowly.
QUINCE Peaches.
Jeff watches Quince's head lower.
It's hard to know when to talk with Quince.
The depth of his mellowness is tough to get in rhythm with.
JEFF I think he was a gift from God, actually.
JEFF Nobody plays like Russell Hammond.
RUSSELL Well, shit.
RUSSELL Thank you.
He instantly realizes he's slipped, on the air.
RUSSELL (cont'd) Ooops.
RUSSELL (cont'd) Better hit the delay button.
All eyes turn to Quince, whose head stays down, grooving to some inner beat.
He says nothing.
The band looks at each other.
We become increasingly aware that Quince may now be asleep.
Long silence.
William shares an amazed look with Penny.
Quince is definitely asleep.
Russell leans forward and continues talking quietly, with hilarious sincerity.
RUSSELL (cont'd) Okay - we're talking now, right?
RUSSELL (cont'd) Why the fuck do you wait until and interview in Arizona to say something nice about me.
RUSSELL (cont'd) Why don't you say it to my fucking face sometime?
RUSSELL (cont'd) Because I tell you every time I think you nailed something.
JEFF Everybody pays you compliments.
JEFF It's not my fucking job to kiss your fucking ass all the time.
RUSSELL Well then who's fucking job is it?
RUSSELL Because my ass is dying for a kiss.
RUSSELL And I know yours is too.
DICK It's my fucking job.
DICK You're all geniuses.
DICK And let me just add this thought - smegma.
Penny covers her mouth as offers a look of absurdity to William.
He offers one back, as laughs are stifled throughout the room.
William shares a look.
Quince is still deeply asleep, as the usually quiet tony leans forward to speak.
TONY Feces.
He cracks himself up, silently.
Quince snaps awake, fully in- stride.
QUINCE The dong is called "Love Thing."
QUINCE Your mind is Starting to take effect.
QUINCE They're all here to see you swallow fire.
QUINCE You scream soundlessly...
QUINCE on the Night Circus.
QUINCE It's Quince, with Stillwater.
"Love Thing" takes over, as Quince swivels in the chair.
QUINCE (cont'd) I thought that went well.
Adrenalized laughter.
The whole band is crammed into a medium- sized rental car.
Penny half on William's lap, half on Russell's.
RUSSELL See, this is what nobody writes about!
RUSSELL The in-between times!
RUSSELL This!
RUSSELL Us!
RUSSELL Right now!!
The phone is ringing.
Estrella emerges from the bathroom with no make-up and a t-shirt.
She picks up the phone.
Across the room, Sapphire signs for room service.
Now she is far too made-up.
The t.v.
radio plays Free's "Fire and Water" in the b.g.
ESTRELLA Hello?
It's Mom on the phone.
ELAINE May I speak with William please?
ESTRELLA He's not here.
ESTRELLA I think he's in the bar with the Band.
ESTRELLA They just got back from the radio station.
ESTRELLA Is this Maryann with the pot?
Silence.
ESTRELLA (cont'd) Hello?
ELAINE No this isn't Maryann with the pot.
ELAINE This is Elaine...
ELAINE his Mother.
Estrella physically recoils.
ESTRELLA I thought you were English.
ELAINE Could you please give him a message?
ELAINE Could you tell him to call home immediately?
ELAINE And could you also tell him -
ELAINE I know what's going on.
ESTRELLA Alright.
ESTRELLA Okay.
ESTRELLA But I'm just going to say this, and I'm going to stand by it.
ESTRELLA You should be really proud of him.
ESTRELLA 'Cause I know guys...
ESTRELLA and I'll bet you do too.
ESTRELLA And he respects women, and he likes women, and let's just pause and appreciate a man like that.
ESTRELLA You created him out of thin air, and you raised him right, and we're all looking out for him.
ESTRELLA And that's more than I've ever said to my own parents, so there you go.
ESTRELLA This is the maid speaking, by the way.
Russell and William sit in two large red-leatherette seats in the hotel lobby.
William shuffles through many pages of questions written in small script.
His tape recorder microphone sits balanced on the chair.
WILLIAM Now that you're starting to be successful, you had twenty-six years to write your first Album...
WILLIAM and you'll have maybe four months for the second.
WILLIAM Do you worry that the pressure of the business will get in the way of the original joy of making your music?
WILLIAM Or
Russell blinks.
The all-consuming issues of his life are right in front of him.
RUSSELL Whoa!
RUSSELL I need three more beers and my guitar before I can answer that question.
RUSSELL Let's take a walk.
Russell walks the outskirts of the pool area with William.
William follows him through the sliding glass door to his room, facing the pool.
Russell grabs his guitar.
They stand for a moment, unheard by the others, and regard the living portrait twenty yards in front of them.
The off-limits after-hours pool area has been overtaken by the Stillwater tour members.
Jeff Bebe sits in a chair nearby.
Dick laughs at a joke.
Always the life of the party, Penny Lane dispenses stolen towels from a maid cart.
And she is the first to slip into the pool for some after-hours, against-the-rules swimming.
Effortlessly, she turns a collection of people into a party.
They regard her, well out of earshot of the others.
RUSSELL For a minute I thought you were actually a real journalist...
RUSSELL which is...
RUSSELL you know, it's great.
RUSSELL Shut that thing off, and I'll tell you the truth.
William shuts his tape recorder off.
WILLIAM It's off.
RUSSELL Look.
RUSSELL I trust you.
RUSSELL I'm going to lay this right on you.
RUSSELL Just make us look cool.
WILLIAM I will quote you warmly and accurately.
RUSSELL That's what I'm worried about.
RUSSELL See - some of us have girlfriends back home.
RUSSELL Some of us have wives.
RUSSELL And...
RUSSELL some of the people you meet on the road are really amazing people...
They both watch Penny Lane, sparkling, fresh from the pool.
She places hotel furniture into the shallow end and inviting all, even other curious hotel guests, to join them in the pool.
RUSSELL (cont'd) Like you.
RUSSELL (cont'd) And some of the things that happen are good for just a few people to know about - as opposed to, say, a million people.
Dawn is breaking for William.
WILLIAM Ohhhh.
WILLIAM Oh.
WILLIAM Yeah.
RUSSELL You know what I mean?
WILLIAM Right.
WILLIAM Yeah.
RUSSELL See, you're dangerous.
RUSSELL Most people are just waiting to talk, but you listen.
WILLIAM Right.
WILLIAM Right.
RUSSELL So your question you asked me.
RUSSELL I think about It every fucking night.
RUSSELL The "business."
RUSSELL I hate it!
RUSSELL I grew up with these guys, okay?
RUSSELL I can't play all that I can play, I'm past these musicians, do you understand?
WILLIAM I do.
RUSSELL The more popular we get, the more I can't walk on them, the bigger their houses get, the more pressure...
RUSSELL you forget, man.
RUSSELL You forget what it was like to be real, to be a fan.
RUSSELL You can hear it in a lot of bands who've been successful - it doesn't sound like music anymore.
RUSSELL It sounds like...
RUSSELL like lifestyle maintenance.
RUSSELL I used to be able to hear the sounds of the world.
RUSSELL Everything, to me, used to sound like music.
RUSSELL Everything.
RUSSELL Now I don't hear it.
RUSSELL You know what I'm trying to say?
WILLIAM Yeah.
RUSSELL Man, it feels good to say this stuff out loud.
RUSSELL But what am I doing?
RUSSELL I'm telling secrets to the one guy you don't tell secrets to.
WILLIAM No, that's okay.
WILLIAM We'll do the interview tomorrow.
RUSSELL This is good.
RUSSELL So there's the "friend" and then there's the "interview guy."
WILLIAM Yeah.
RUSSELL So tonight it's "friend"....
RUSSELL and when we wake up tomorrow - "interview guy."
RUSSELL We'll figure it out as we go, buddy.
WILLIAM Hey - for whatever it's worth - you guys are really good.
Russell laughs at the kid's easy naivete.
He hands his guitar to the kid, and joins the party.
William watches, part of the crowd...
somehow feeling a little compromised.
He doesn't care.
Penny gestures for him to join them.
William interviews Larry in the seats of the empty arena.
On stage, Ed soundchecks his drums.
WILLIAM How would you describe your role in Stillwater?
WILLIAM What is the chemical that you add to the chemistry?
LARRY I'm the bass-player.
WILLIAM Right.
WILLIAM And when you take that away...
WILLIAM what would be missing?
WILLIAM Stylistically?
WILLIAM What chemical?
LARRY The bass?
Larry doesn't give him much.
It's raining.
The pre-show huddle breaks up, William a part of them.
Penny Lane adjusts Larry's look.
She takes the scarf from around his neck and ties it around his leg.
He looks instantly better.
William watches in the darkness as Dick takes the microphone.
The best part of his day has arrived.
In his important voice:
DICK Good evening Phoenix.
DICK From Troy, Michigan.
DICK Please welcome, Stillwater.
Lights come up, as the band launches into "Fever Dog."
Jeff begins singing.
Russell reaches to adjust the microphone for a back-up vocal and is hit with something unexpected.
A sharp electrical shock.
It's just a slight pop in the loud din of music, but within a moment something is clearly wrong.
Russell holds onto the microphone stand with a surprised look, conducting high-voltage for two seconds and then he snaps his hand off the metal.
His face is white, he takes off his guitar and walks off-stage, collapsing a couple steps later.
Dick is waving wildly for the band to board the bus, which has been pulled up into the backstage area.
He guides a sagging Russell, assisted by Penny Lane, into the bus.
DICK Get in, get in!!
William boards the bus, as the extremely agitated PROMOTER arrives to confront Dick.
PROMOTER Are you the manager of this band?
DICK That, and more.
DICK Get in!
PROMOTER You didn't even play a full set!
Dick whirls and unleashes an anger we've not yet seen, gesturing with the silver briefcase that does not leave his hand.
DICK Your shoddy stage set-up almost killed our guitarist!
PROMOTER You trashed the dressing room - you didn't play your thirty-five minutes.
PROMOTER You didn't fulfill your contract -
DICK Everybody in!
DICK Get in the bus!
PROMOTER I'll report you to every promoter in the country!
PROMOTER I'm gonna talk to Frank Barcelona!
PROMOTER I hope you have a good lawyer.
He swings into the bus, as the bus revs.
Russell sits, pale, next to Penny at the front of the bus.
He examines his singed hand, shaking it a little to emphasize the positivity of her words.
PENNY Don't worry.
PENNY It's happened to all the greats.
PENNY Thank God you didn't hold the mike stand with both hands, you'd still be holding it.
PENNY This is a good thing.
PENNY It's a good, good, good thing.
William sits nearby, watching Russell, making notes out of eye- sight of others.
The ever-wary Jeff, unseen by William, cranes to see that he's writing in his notebook.
Dick swings into the seat across from Russell.
The bus door shuts, as the promoter is still yelling.
Doris is slow to gain speed, as Estrella appears, running alongside.
She knocks on the window next to William.
ESTRELLA I forgot to tell you!
ESTRELLA Your mom says to call home immediately.
ESTRELLA She says she knows what's going on!
ESTRELLA See you guys in Topeka!
ESTRELLA I'll catch a ride with Sabbath!
William nods with embarrassment, waves to her, as the bus races toward the now closing gate.
DICK Wanna buy a gate?
Before Russell can answer - BASH.
Doris barrels through the steel-gate, snapping it like a chopstick to great cheers inside this bus.
DICK (cont'd) You just bought a gate.
DICK (cont'd) C'mon Doris!!
DICK (cont'd) Get us out of town!!
The bus struggles up a slight incline, everybody rooting for Doris, as she eases out of the parking lot and onto a thoroughfare.
WILLIAM What did it feel like to be electrocuted?
RUSSELL It burns.
RUSSELL It feels like a dose of lead shooting through your body...
RUSSELL and then you see God, and he says, "How bad do you want to be legendary?" And god damnit.
RUSSELL I let go.
RUSSELL Rock and roll.
Jeff watches this charisma with thinly veiled envy.
The kid scribbles in his notebook.
We hear Led Zeppelin's "That's the Way."
Song continues.
Almost everybody is asleep.
William takes the camera and snaps a Polaroid of a sleeping Penny.
She wakes up.
PENNY Give that to me.
She grabs for it, they have a brief play-fight.
He grabs some other Polaroids from her pocket.
He hustles to the back of the bus, pockets the photo, and settles down to watch the passing landscapes.
She chases him down the aisle.
Music continues as she sits down next to him.
Out the window, a long-distance running team of Girls keeps pace with the bus for a bit.
They wave.
Penny watches them over sunglasses, waves briefly to the real world.
PENNY (cont'd) When we go to Morocco, I think we should wear completely different clothes, and be completely different people.
WILLIAM What will our names be?
She snaps a Polaroid of a nearby sleeping Silent Ed, pockets the Polaroid.
She regards Russell up ahead, also sleeping.
Her attention has already wandered from Morocco.
PENNY What do you think of Russell?
WILLIAM I like him.
PENNY You're coming to Cleveland, right?
WILLIAM Cleveland, Ohio?
WILLIAM Oh no no no.
WILLIAM I gotta get my interview with Russell before Greenville.
WILLIAM And you've got to help me.
WILLIAM Okay?
WILLIAM Friends...
WILLIAM remember?
Penny is still watching Russell.
PENNY You should give him a break.
PENNY There are real problems in the band.
PENNY Off the record.
Gravely noting the word "problems", the kid joins Penny in watching Russell, who is splayed haphazardly, sleeping restlessly up ahead.
WILLIAM What problems?
PENNY Okay.
PENNY I got it.
PENNY I think your name should be Spencer, and mine will be Jane.
WILLIAM I can't keep up with you.
PENNY No one can.
WILLIAM What's your real name?
She looks at him briefly.
She puts her arm around him.
It's intoxicating, but he doesn't quite know how to act.
With her free hand, she gestures with a hanger.
As they regard Russell sleeping nearby:
PENNY Here's the thing about Russell.
PENNY He's my last project.
PENNY I only do this for a very few people.
PENNY And I think we should do it together - he is almost great.
PENNY We've got to take him there.
PENNY You and me - we can do it.
PENNY Deal?
PENNY Because the other guys are good - but he could be great.
PENNY He's my last project.
He looks at her.
She imitates his face back to him.
PENNY (cont'd) It's all happening.
William sits interviewing Silent Ed by some equipment cases.
WILLIAM What do you love about music?
Ed looks at him thoughtfully.
It is an eloquent moment.
He thinks.
He shrugs.
The kid tumbles with more questions.
These interviews are not going well.
William, looking concerned over the state of his interviews, walks into the backstage bathroom.
He makes a few surreptitious notes in his notebook before noticing that Jeff is standing there, clearly just finishing a quick hit of cocaine offered by a Local Hanger-On.
Seeing the kid, he immediately hides the coke spoon.
JEFF Hey.
WILLIAM Hey.
William pretends he sees nothing as he turns to the urinal, and shot stays on Jeff, who looks a little high and a little worried.
William is on the pay phone with his Mother.
The show booms in the background.
WILLIAM I know.
WILLIAM I know.
WILLIAM I know.
WILLIAM I know.
WILLIAM Mom.
WILLIAM Mom...
WILLIAM Mom.
Stillwater on-stage.
A great show.
Russell on fire.
William on the phone.
Estrella leans on him, fixing her shoe.
WILLIAM Right now -- Topeka.
WILLIAM Then Greenville.
WILLIAM Then home.
He winces slightly, holds the phone away from his ear for a moment.
WILLIAM (cont'd) I'm sorry I didn't call yesterday!
WILLIAM (cont'd) It's not like you can just carry a phone around with you.
Mom sits in her school office, a miniature version of her home - a fortress in which she is surrounded by books.
The sun is going down.
She can't resist a sentimental moment.
ELAINE I guess I just miss you, and I don't understand why I've driven both my kids so far away from me.
ELAINE By all practical rules don't I get you for three more years?
He is touched by her vulnerability, more visible now than ever, as music continues in b.g.
ELAINE (cont'd) Was I not fun?
William has his finger in his ear.
The din if Stillwater's set now blots out all other noise.
It is not the time to answer this question.
WILLIAM I missed the last thing you said.
Mom takes a pause.
Penny now enters, watching.
William now notices Penny standing nearby, picking at a salad from a paper dish.
Looking at her, he lets loose with what he believes is a private confession.
Penny smiles knowingly, collecting his affection like another backstage pass, and turns away.
Camera stays on William.
He is suddenly and deeply embarrassed.
He's just told her that he loves her and she knows it.
He hangs up, traumatized.
Russell's hair is slicked with sweat from a show just finished.
He is shirtless with a towel around his shoulders.
Luggage for the next city is stacked by the door.
RUSSELL Fire away.
RUSSELL I'm ready.
RUSSELL I'm on the "You" Train.
RUSSELL Take me there.
The kid plugs in his microphone.
Russell listens as he springs his first question.
WILLIAM Do you have to be depressed to write a sad song?
WILLIAM Do you have to be in love to write a love song?
WILLIAM Is a song better if it really happened to you?
WILLIAM Like, "If You Say Nothing"...
WILLIAM where did you write that and how did it come about?
Russell admires the many questions.
Says nothing.
He looks at his hand, thinks.
RUSSELL When did you get so professional?
In the background, Penny Lane irons Silent Ed's shirt.
Grinning, she cuffs his shoulder.
To the shirtless silent drummer, waiting for his shirt.
PENNY I'm almost done with my shirt.
Ed watches her appreciatively, drumming silently on a rubber pad.
Penny kisses Russell, who swings her onto his lap.
In the corner, Jeff watches them all with a vague feeling of being underappreciated.
And now Dick enters with a large cardboard box.
DICK Russell, your dad showed up again.
DICK And on a lighter note.
DICK Gentlemen.
DICK Your first t-shirts have arrived.
There is an immediate buzz in the room, as Dick yanks open the box filled with new white t-shirts.
He untangles the first fresh shirt, and displays it proudly.
A silent beat as all examine it - their first t-shirt.
Faces fall.
Ed stops drumming.
There has been a mistake.
It is a fuzzy band photo with the group name emblazoned below.
Only Russell, who stand out front, is colored- in and emphasized on the shirt.
He turns away, making a noise.
Jeff stares at the t-shirt.
He's just about in tears.
There is a long silence and then...
Ed resumes drumming on the rubber pad.
DICK (cont'd) It's the record company's mistake.
DICK (cont'd) And they will pay.
DICK (cont'd) Shirts gone, band happy.
He drops the offending shirt into the trash, as if it were contaminated, and exits with the box.
William watches as the two men, Russell and Jeff, move to opposite sides of the room.
Russell puts on a shirt, so does Jeff.
The vibe is thick.
Russel turns to see Jeff staring at him.
RUSSELL Can we just skip the vibe and go straight to us laughing about this?
JEFF Yeah.
JEFF Okay.
RUSSELL Because I can see by your face - you want to get into this -
JEFF How can you tell?
JEFF I'm just one of the out-of-focus guys.
RUSSELL Here we go.
William watches as Russell fishes the t-shirt out of the trash.
RUSSELL (cont'd) Here.
RUSSELL (cont'd) Take it.
RUSSELL (cont'd) You LOVE this shirt - it lets you say everything you want to say.
JEFF Well, it speaks pretty loudly to me.
RUSSELL It's a t-shirt.
Russell turns away.
JEFF I'm always gonna tell you the truth.
RUSSELL Are you doing coke again?
JEFF Oh yeah.
JEFF All the time.
The kid looks down.
JEFF (cont'd) This is big stuff, man.
JEFF (cont'd) From the very beginning -- we said -- I'm the front man and you're the guitarist with mystique.
JEFF (cont'd) That's the dynamic we agreed on -- Page, Plant...
JEFF (cont'd) Mick, Keith.
JEFF (cont'd) But somehow it's all turning around.
JEFF (cont'd) We have got to control what's happening to us.
JEFF (cont'd) There's a responsibility here -
RUSSELL Excuse me, but didn't we all get into this to avoid responsibility?
JEFF Forgive me.
JEFF But this is the slow-moving train of compromise that will kill us.
Russell makes a disgusted noise.
Penny Lane exits discreetly, looking back at William.
JEFF (cont'd) I can't say anymore with a writer here.
RUSSELL You can trust him, you can say whatever you want.
JEFF I works as hard or harder than anybody on that stage.
JEFF You know what I do - I connect.
JEFF I get people off.
JEFF I look for the guy who isn't getting off, and I make him get off.
JEFF Actually, that you can print.
JEFF And yet, why do I always end up feeling like I'm a joke to you?
JEFF I feel nothing but love for you.
JEFF We're a family.
He looks at the t-shirt and starts to cry.
Embarrassed, he grows angrier.
JEFF (cont'd) You want to pretend this isn't going to be a very big band.
JEFF (cont'd) Well it is.
JEFF (cont'd) You call yourself a leader of this band, but your direction allowed the t-shirt, when you allowed Dick to manage us, 'cause he's your friend...
JEFF (cont'd) don't you see?
JEFF (cont'd) The t-shirt is everything.
JEFF (cont'd) It's everything.
RUSSELL Is it my turn?
RUSSELL Because I think we should, for once, say what we really mean.
JEFF Oh, this is the part where you quit -
RUSSELL Right.
RUSSELL I'm so predictable.
JEFF No I gotta tell the truth -- I want you to like me.
JEFF But sometimes I feel like you collect people who love you and then very skillfully...
JEFF you make them feel bad that they're not good enough for you.
RUSSELL Stick to singing, brother, 'cause you ain't gonna make it as a shrink.
JEFF Deal with it!
JEFF And let me just say what nobody Else wants to say to you -
RUSSELL What?
JEFF Your looks have become a problem.
Russell walks swiftly past a happy silver-haired man, who holds court with beer in hand.
He dresses too young for his age, late fifties.
He is DAD.
DAD Son!
RUSSELL Hello Harry.
Dad introduces a woman much younger, who eyes Russell hungrily.
DAD He got all the good genes, huh?
DAD Meet Deirdre.
DAD We're getting married in July.
Russell walks fast outside the arena.
William hustles to catch up.
The two men walk in long silent strides in the cold night air, beyond the backstage area.
Fans begin to recognize and follow at a discreet distance.
WILLIAM You okay?
WILLIAM You alright?
Russell doesn't answer.
RUSSELL From here on out, I'm only interested in what's real.
The kid nods.
They walk.
RUSSELL (cont'd) Real feelings.
RUSSELL (cont'd) Real people.
RUSSELL (cont'd) That's all I'm interested in...
RUSSELL (cont'd) From here on out.
RUSSELL (cont'd) What is REAL?
RUSSELL (cont'd) You're real.
WILLIAM Thanks.
A wave of warmth comes over Russell.
RUSSELL You know, you know all about us and I don't know shit about you.
RUSSELL What's your...
RUSSELL your family like?
RUSSELL Tell me.
WILLIAM Well, my dad died of a heart attack and my sister believes that my Mom is so intense that she might have contributed to it.
WILLIAM Plus -
RUSSELL Okay, that's good.
RUSSELL That's enough.
WILLIAM It's good to talk about it.
WILLIAM Really good.
Russel now sees some hero worship in the kid's face, and it makes him nervous.
WILLIAM (cont'd) Hey, man, maybe we should go back.
RUSSELL If they want me, they can find me.
William turns and sees nobody following but fans.
WILLIAM So listen.
WILLIAM I have to go home tomorrow.
WILLIAM I know this is a bad time to finish our interview.
RUSSELL Hey, man, you know what?
RUSSELL Write whatever you want.
RUSSELL I trust you.
A big square Chevy van slows down.
A CONCERT-GOER hands his head out the window.
CONCERT-GOER Woooooooooo!!!
CONCERT-GOER You're Russel from Stillwater!!
RUSSELL On my better days, yes.
RUSSELL I am "Woooooo, Russell from Stillwater!"
CONCERT-GOER Wanna go to a party at my friend Aaron's house?!
CONCERT-GOER I know you're a big rock star, but do you want to hang with some people looking to have a good time?
Russel regards the van full of kids.
More fans crowding around.
The kid behind the wheel unknowingly says the magic words.
CONCERT-GOER (cont'd) We're just real Topeka people, man.
He has said the magic word.
Russell arrives at the party in the rural outskirts of Topeka.
William nearby.
William watches as Russell slugs from a Jack Daniels bottle.
They sit in the bedroom of a mindblown fan, 17 year-old AARON.
He has long frizzy brown hair, tied in a spray behind him.
Many from the neighborhood are now pouring into the home.
RUSSELL You.
RUSSELL Aaron.
RUSSELL Are what it's all about.
RUSSELL You are real.
RUSSELL Your room is real.
RUSSELL Your friends are real.
RUSSELL You are more important than...
RUSSELL than...
RUSSELL all the silly machinery.
RUSSELL And you know it!
RUSSELL In eleven years it's gonna be 1984, man.
RUSSELL Think about that!
AARON Wanna see me feed a mouse to my snake?
RUSSELL Yes.
KID # 1 Can I have your belt?
RUSSELL Take it!
Russel whips off his belt, gives it to the fan.
A joint goes by, headed for Russell.
William intercepts it and passes it on.
RUSSELL (cont'd) Aaron?
RUSSELL (cont'd) Where's your bathroom?
RUSSELL (cont'd) I want to live here.
RUSSELL (cont'd) I want to eat your food, and live in your city and fuckin rock like I used to.
RUSSELL (cont'd) I want to learn everything there is to know about your city and your town.
RUSSELL (cont'd) And your way of being real.
RUSSELL (cont'd) I used to be you.
AARON Down the hall by the washing machine.
RUSSELL What?
AARON The bathroom.
RUSSELL Okay.
RUSSELL Good to know.
Russell rises and squeezes past fans and heads down the hall.
William follows Russell protectively.
A QUIET GIRL, 14, turns and watches Russell pass.
We linger on her face for just a moment, full of wonder.
WILLIAM We should probably head back sometime.
Russell ignores him.
PASSING FAN # 2 Watch out, there's acid in the beer that's in the Red cups.
Russell looks at the cup in his own hand.
It's white.
Then, with his other hand, he grabs the red cup and drains it.
William winces.
They move on.
RUSSELL Topeka.
RUSSELL Check it out.
Russell enters the bathroom.
William stands guard.
With a finger outstretched from each hand, he lectures the fans massing in the hallway.
WILLIAM Please don't give him any more acid.
William watches as a wobbly Russell Hammond, in sunglasses now, goes through Aaron's record collection.
He places the albums over his face, like masks.
RUSSELL Faces.
RUSSELL Stones.
RUSSELL Sa-weet Baby James!!
RUSSELL None of these people are gonna be around in twenty years!
RUSSELL Plastic begets plastic!!
RUSSELL Black plastic.
Partygoers are strangely fascinated by the rock star in their living room.
William waits anxiously to use the phone, keeping an eye on Russell.
Russell is now strangely twisting/dancing with four girls in the living room, as more cars arrive outside.
KID ON PHONE He's here right now!
KID ON PHONE Go ahead and put it Out over the radio, tell people to bring food And beer and chicks.
KID ON PHONE We're at Rural Route # 4 -
WILLIAM No no.
WILLIAM Nope.
WILLIAM No.
William takes the phone and hangs up.
Keeping an eye on Russell in the next room, he dials from a tour itinerary sheet.
WILLIAM (cont'd) Dick Roswell, please?
WILLIAM (cont'd) Dick!!
WILLIAM (cont'd) I got him!!
WILLIAM (cont'd) He's okay...
WILLIAM (cont'd) I've been Looking after him.
WILLIAM (cont'd) He's on acid, though.
WILLIAM (cont'd) I can't Really tell.
WILLIAM (cont'd) How do you know when it's "kicked in?"
Russel stands on the jutting corner of the house rooftop.
The unlit, unheated greenish family pool beckons to him below.
It's kicked in.
Russell cackles at the joke of it all.
William yells up from down below.
WILLIAM Hey Russell -
WILLIAM Don't jump, okay?
RUSSELL And you can tell Rolling Stone Magazine my last words were -
He spreads his arms, and tries to think of last words.
RUSSELL (cont'd) -- I'm on drugs!!
The kids cheer.
William looks around, remains cool.
Yells upward in the cold night air.
WILLIAM I think we should work on those last words.
RUSSELL Critic!!
WILLIAM No, I'm not -
RUSSELL Okay I got it.
RUSSELL I got it.
RUSSELL I got it.
RUSSELL I got it.
RUSSELL This is better.
RUSSELL Last words
It gets a skimpy reaction from the partygoers.
RUSSELL (cont'd) I'm on drugs!!
They applaud again.
WILLIAM Just come on down!!
RUSSELL Okay.
He jumps from the roof into the cold, algaed water below.
He sinks immediately.
One kid jumps in, then another, then more.
Everybody wants to save Russell.
It's getting lighter.
Cars line the street.
And now, finally turning the corner, is Doris the Bus.
William watches the effects of personal charisma.
Wet partygoers surround Russell, bottle of Jack Daniels still in hand, wrapped in towels.
Now a bond has passes between them, all of them.
Algae drips from the corner of Russell's face and neck.
RUSSELL Thanks for saving my life.
RUSSELL I won't hold it against you.
Twenty different kids thank him for the opportunity.
("Glad to do it," "Right on," "Damn straight."
Door opens.
Dick enters.
Finding the guitarist in the kitchen, he clicks into time-tested road-managerial maintenance.
Easing Russell out of his towel, slipping his own jacket around him, from Russell's hands.
DICK They've been crying for you like a bunch of whimpering pussies --
RUSSELL The band is over.
RUSSELL This is my family now.
OTHERS Right on.
OTHERS He's staying with us.
DICK Definitely.
DICK It's all over.
DICK We'll just ride on to Greenville, listen to some great music, finish the tour, and leave those ungrateful fools behind.
DICK And then we'll come back here, where you'll live.
RUSSELL I know what you're doing...
RUSSELL and I like it.
RUSSELL Look at him.
RUSSELL He's taking notes with his eyes.
RUSSELL How do we know he's not a cop?
William laughs painfully, as Russell moves in, eyes flaring with sudden paranoia.
RUSSELL (cont'd) He could be selling information!
DICK Easy.
DICK He's your Guardian Angel.
Russell turns away.
William shrugs with style, but his lingering look is filled with hurt.
Dick guides Russell to the door, grabbing the kid and talking very directly to him as they move.
DICK (cont'd) Don't worry.
DICK (cont'd) He only means half of what he says.
WILLIAM Which half?
DICK Good question.
WILLIAM I have a lot more.
WILLIAM Just help me get my interview so I can go home from Greenville.
WILLIAM I have to go home.
WILLIAM I have to go home.
DICK Hey.
DICK You saved the tour.
DICK That's good enough for now.
Frustrated but feeling important, William hands him some of Russell's wet clothes.
William deftly retrieves Russell's shoes and smoothly plucks the guitarist's sunglasses from the partygoer who also wears his belt.
They move to the door in a pack.
We hear the beginning of Elton John's "Tiny Dancer."
Dick faces the crowd and addresses them in his "important" stage voice.
DICK (cont'd) Ladies and Gentlemen, the evening is over!
DICK (cont'd) We hope you've enjoyed yourselves, and we'll See you again in 1974!!
DICK (cont'd) Good evening!!
William gives Russell his sunglasses to face the sunlight.
Russell stumbles out of the house to great cheers.
The Quiet Girl breaks free to catch Russell on the way out.
QUIET GIRL I'll never forget you.
Dick pats William's arm one more time -- good work.
They leave Aaron's house as legends.
"Tiny Dancer" continues on the bus stereo.
Russell sits up front, swathed in a large robe, alone and silent.
The others have given him a wide berth.
He feels silly, and they know it, and he hates that they know it, which makes him feel foolish.
He sits silently.
William watches him from four rows back, next to Penny.
She kisses the top of his forehead, a hero's welcome.
He yawns.
The song's vocal begins.
There is only more silence.
Then, after a beat, we hear a voice or two, fighting the quiet and singing along.
Then others...
waking up...
joining in.
Then Jeff.
Russell hears them and starts to sing along too, louder now, without turning around.
It's a voice everyone wants to hear.
Like it or not, this is his family.
Passing signs announce Greenville, North Carolina.
Lester on the phone.
He is paler than ever, in a room clogged with vinyl, happily listening to the MC5 in the background.
LESTER How's it going?
It's a small wooden-walled hotel room in Greenville.
Polexia tries on clothes.
William barely notices as he talks to Lester on the phone.
WILLIAM Rolling Stone is calling me.
WILLIAM I don't have my key interview.
WILLIAM I don't know what to say.
LESTER BANGS You're flipping out.
LESTER BANGS That's good.
LESTER BANGS Alright.
LESTER BANGS This is how you blow their minds.
LESTER BANGS He'll ask you - this is Ben Fong-Torres, right?
LESTER BANGS - he'll ask you how the story's going.
LESTER BANGS Here's what you do - let's fry his mind.
LESTER BANGS Tell him "it's a think piece about a mid-level band struggling with their own limitations in the harsh face of stardom."
LESTER BANGS Ha ha!!
LESTER BANGS This is fun!
William scrambles to make notes.
WILLIAM ...
WILLIAM think...
WILLIAM piece...
Longhand small script on yellow legal tablets.
William sits in the tub, without water.
It's his makeshift office, he's surrounded with scraps of notepaper.
He writes savagely, and now, savagely throws it away.
In the bedroom, Sapphire, Polexia and Penny watch The Midnight Special.
Sapphire looks at a room service menu.
SAPPHIRE It says the food is hearty and adventurous.
POLEXIA Greenville.
POLEXIA I'm bored.
Penny yawns too, it's catchy, and rises to visit the bathroom.
POLEXIA (cont'd) Hey let's deflower the kid.
Now Sapphire yawns, looks in her purse.
SAPPHIRE Who his the quaaludes from me?
Penny enters to see William writing in the tub.
She sits on the toilet to pee.
Flustered:
WILLIAM Wait.
WILLIAM I'll leave.
He gets up, knocking his carefully organized notes onto the floor.
He is brimming with things to say.
More than he is even able to communicate.
WILLIAM (cont'd) You know, I think this is going backwards for me.
PENNY Backwards?
WILLIAM I don't know.
WILLIAM I just thought we could hang out, maybe do some stuff back home, regular stuff, get to know each other better...
WILLIAM and then I'd see you pee.
WILLIAM I mean, that's the way I usually do it.
PENNY You're one of us.
PENNY It's no big deal.
WILLIAM I'm not one of you.
PENNY Oh!
PENNY If you go to Cleveland, Bowie's going to be there at Swingo's, the greatest hotel in America.
PENNY I'll introduce you to him, and his security guy Dennis.
William stops at the door.
WILLIAM Don't you have any regular friends?
PENNY Famous people are just more interesting.
He looks at her.
Even sitting on the can, she's elegant and totally focused on him.
WILLIAM Well, I would be worried that they were using me.
WILLIAM And not that anybody's using you, but -
She swoons a little, touched and moved.
PENNY Boy, if this was the real world and some guy talked to me like that -
WILLIAM Let me finish.
WILLIAM I'm not famous....
WILLIAM but you could always use me.
WILLIAM If anything happens.
WILLIAM And I would never use you.
WILLIAM Even if I got famous.
WILLIAM So you know, you always have that from me...
WILLIAM in the real world.
WILLIAM If you ever have to go back there, for anything.
She looks at him curiously, as the door blasts open.
Sapphire and Polexia head for William.
SAPPHIRE Your time has come.
WILLIAM Did he call?
WILLIAM What are you -- stop it -- we're talking here.
SAPPHIRE Pants him.
SAPPHIRE Opie must die.
They swarm him, dragging him kicking into the bedroom.
Steely Dan, looking pale and somehow snappy, perform "Do It Again" on The Midnight Special.
The girls force William onto the bed, and envelope him.
Their sexuality is fun, untroubled.
Shot moves past bodies crossing frame, onto William's face.
Across room, sitting and watching.
SAPPHIRE Just relax.
SAPPHIRE Take a vacation from yourself.
SAPPHIRE Leave this to professionals.
Estrella and Polexia kiss each other playfully.
William looks confused.
Across the room, Penny laughs, turns up the TV, blows him a kiss.
Penny's eyes.
Across the room.
His eyes.
His sexual awakening may be downtime amusement for them, but to him it's an embarrassingly intense moment he shares only with Penny Lane -- across the room.
She turns away, smiling, disappears into the next room.
On the television.
Post-sex pajama party.
Sapphire, Estrella, and Polexia girltalk about their first rock and roll conquests.
Penny is conspicuous by her absence.
William is under the sheets, listening, feeling different, now a man and somehow one of the girls too.
William is awake.
Sunlight floods in from the corners of the window-shades.
He is surrounded by the fallen cavalry of the night before...
Sapphire and Polexia.
The phone rings, and Sapphire instantly snaps it up, still asleep.
Lost in her dreams, she offers the sexiest hello ever.
SAPPHIRE Hello.
SAPPHIRE Hi, Ben-Fong-Torres from Rolling Stone.
William snatches the phone.
WILLIAM Hello.
Ben Fong-Torres is up bright and early.
BEN Hello William, this is your editor at --
He offers the name of the magazine with a swirl that implies high-level importance.
BEN (cont'd) Rolling Stone.
BEN (cont'd) How's the story?
William snaps into his very professional tone of equally grave importance.
WILLIAM I'm getting good stuff out here.
BEN Sounds like it.
Next to him, Polexia yawns herself awake.
POLEXIA Man, I need some -
He clamps a hand over her mouth.
BEN Now listen.
BEN Get it together.
BEN We're both professionals, I don't have to tell you this.
BEN You're not out there to join the party -- we already have one Hunter Thompson.
BEN You're out there to interview and Report.
BEN You got me?
BEN This isn't Creem Magazine, it's Rolling Stone.
BEN We need this story in four days.
BEN Now I want to know how it's shaping up.
WILLIAM It's a think-piece about a mid-level band grappling with their limitations in the face of the harsh glare of success.
BEN I like what we're saying.
BEN Let me try and get you a thousand more words.
BEN It's in consideration for the cover, but don't tell the band.
WILLIAM Crazy.
The kid hangs up, now shouldering even more pressure.
He unclamps Polexia's mouth.
POLEXIA - coffee.
SAPPHIRE Me too.
SAPPHIRE Greenville is so boring.
SAPPHIRE Any other city in the world and you'd still be a virgin.
WILLIAM I'm going out to find Russell.
SAPPHIRE Will you take the laundry?
WILLIAM What am I to you?
WILLIAM Tell me right now!
WILLIAM What.
WILLIAM Am.
WILLIAM I.
WILLIAM To.
WILLIAM You.
Circles have sprouted up under William's eyes.
The orange bag strapped over his shoulder, he lugs a huge bag of laundry.
He consults room list.
A variety of noises and smells drift from the band rooms.
He sees Room Service arrive at Dick's door, and it's Estrella who opens the door.
(Dick in the background.)
She smiles sweetly to William -- good morning -- as the door shuts.
WILLIAM Houdini...
WILLIAM Houdini...
He arrives at Russell's door.
Two exclamation points have been Sharpie-markered to the words Do Not Disturb on the sign is gaffer-taped to his door.
He looks through the crack, at the bottom of the door.
Carefully and politely, he knocks.
Instantly:
Pissed, the kid flips off the door.
He sits down on a chair directly across from the room.
Push in on William, who is more pent-up than ever.
He tries hard not to cry, taking gulps of air as a maid cart swishes past, revealing...
he's failed.
He cries.
A super-energized Russell Hammond looks into William's sleepy face.
William's eyes open.
His own sleepy face is evident in Russell's sunglasses.
The bag of laundry is still at his feet.
RUSSELL (cont'd) We'll do the interview in Cleveland!
WILLIAM No.
WILLIAM I can't.
WILLIAM You've got to help me.
WILLIAM I have to go home.
RUSSELL Come on man, we'll have more time there.
RUSSELL Don't be tense!!
He begins rubbing the kid's shoulders.
He's waking up.
There's Penny, also rubbing his shoulders.
It is degrading...
and somehow cool too.
WILLIAM You said you'd help me.
PENNY Come to Cleveland.
RUSSELL Come to Cleveland...
RUSSELL Come to Cleveland...
WILLIAM I can't!!
RUSSELL Can we help it if we like having you around!
William is a bundle of nerves and exhaustion now.
Embarrassed and frustrated.
RUSSELL (cont'd) Cleveland, my man.
RUSSELL (cont'd) You can't miss out on the Rock Mecca of the midwest - you're with us.
RUSSELL (cont'd) It's all happening!
PENNY Rock and roll!
WILLIAM Rock and roll.
We hear David Bowie's live version of "Waiting for the Man."
They sit together, hair askew, in sunglasses, resting against the headboard.
Carefully, Russell identifies his thoughts.
RUSSELL I feel...
RUSSELL like his parents.
Penny runs a worried hand through her hair.
PENNY I know.
RUSSELL I wonder how that happened.
PENNY You ever notice that all our sentences begin with "I?"
RUSSELL I hadn't, no.
PENNY 'Cause we should work on that.
He looks at her, plays the guitar a little.
Night.
Doris rocks toward Cleveland on a muggy summer night.
The windows of passing houses offer rich Edward Hopper glimpses of lives and people William will never meet.
William watches from his bus bunk at the back, head on elbow.
Looking up, he sees the rhythmic motion of bodies on the mattress above him, as music continues.
William gets up, nods hello to the Roadie and his Date on the bunk above.
He moves down the aisle...
to the seats near the front.
A sleeping Russell sits upright, hugging his guitar.
Penny asleep next to him, Polaroid in her hand of...
Russell sleeping.
The kid moves on.
He sits with the Bus Driver, whose CB crackles with chatter from other tour buses headed to Cleveland.
Cleveland signs.
Music rises.
Heads pop awake.
RUSSELL Cleveland!
Like a slow-moving shark, Doris pulls into empty downtown Cleveland.
The streets are empty.
They pass the Agoura Ballroom, where a man with a long stick arranges the letters Stillwater on the marquee.
Applause in the bus.
Russell and band enter like warriors, in a pack.
William sags with the heavy bags in hand and over his shoulder.
Here, in the middle of the midwest, is an explosive rock mecca, just as promised.
The feeling of belonging invades all those in this lobby.
Fans and other touring rockers mingle together.
Outside in the real world, everyone else is going to work.
FAN It's Bowie!
The lobby ignites, as William stands near Penny and Russell.
Bowie races from a limousine through the lobby and into the elevators.
He is shrouded by a jacket.
Just the top of his electric red hair travels the lobby, as he's hustled by security man Dennis in the elevator.
And out of the chaos comes...
Jeff Bebe and Polexia smash against the wall of the Swingo's hotel room, making love.
Russell and Penny Lane smash against their own wall.
Dick squats at the front of the stage, and talks to a few fans in the front row of this crowd.
A wild Cleveland crowd in the building.
The cities on this tour are getting bigger, and so are the audiences.
And there is a whiff of business now too.
Men in satin tour jackets and some Disc-jockey types cruise the backstage.
A Hysterical Fan is led screaming to the nearby medic room.
Few even react - it's Cleveland - as the shot finds William, tired and yawning, on the backstage pay phone.
He is absolutely ready for the worst.
WILLIAM Hi Mom.
WILLIAM I'm in Cleveland.
He listens stoically.
Larry and Ed watch nearby.
Moms sits in silence.
WILLIAM (cont'd) I'm fine!
WILLIAM (cont'd) I'm fine!
WILLIAM (cont'd) I'm flying back on Monday Morning.
WILLIAM (cont'd) I'll only miss one test.
WILLIAM (cont'd) I'll make it up.
Russell listens in, holding his guitar, laughing.
RUSSELL Tell her you're a slave to the groove - you can't help it!
WILLIAM No.
Russell grabs the phone, talks to the silent mother on the other end.
RUSSELL Hi Mom!
RUSSELL It's Russell Hammond, I play guitar in Stillwater!
RUSSELL It's my fault.
RUSSELL How does it feel to be the mother of the future of rock journalism?
RUSSELL Hello?
Silence.
Penny passes and stands near William, smoothing her pass.
They watch a new pack of groupies prowl the road-crew.
They are more glam, more trashy and less selective.
They glare insolently at Penny Lane.
This is the future.
RUSSELL (cont'd) You've got a great kid -- nothing to worry about!
RUSSELL (cont'd) We're taking care of him!
RUSSELL (cont'd) And you should come to a show sometime!
RUSSELL (cont'd) Join the Circus!
ELAINE Listen to me.
ELAINE Your charm does not work on me.
ELAINE I'm onto you.
ELAINE Of course you like him.
RUSSELL Yes.
ELAINE He worships you people and that's fine with you, as long as he helps make you rich.
RUSSELL Rich?
RUSSELL I don't think so -
ELAINE Listen to me.
ELAINE He's a smart, good- hearted, 15 year-old kid, with infinite potential.
Russel looks over at the kid, eyes narrowing as he processes the truth.
He's 15?
ELAINE (cont'd) This is not some apron-wearing mother you're talking to.
ELAINE (cont'd) I know about your Valhalla of Decadence, and I shouldn't have let him go.
ELAINE (cont'd) He is not ready for your world of compromised values, and diminished brain cells that you throw away like confetti.
ELAINE (cont'd) Am I speaking clearly to you?
RUSSELL Yes, ma'am.
ELAINE If you break his spirit, harm him in any way, keep him from his chosen profession -- which is law, Something you may not value but I do -- you will meet the voice on the other end of this telephone.
ELAINE And it will not be pretty.
ELAINE Do we understand each other?
RUSSELL Yes...
RUSSELL yes...
ELAINE I didn't ask for this role, but I'll play it.
ELAINE Now go do your best.
ELAINE "Be bold and mighty forces will come to your aide!" Goethe said that.
ELAINE It's not too late for you to be a person of substance.
ELAINE Get my son home safely, I'm glad we spoke.
She hangs up.
Russell hangs up, oddly affected and shook up.
WILLIAM Some people get her.
WILLIAM Some don't.
Russell is still recovering.
William feels embarrassed by his mother, once again.
William with the band.
He yawns, as the band breaks.
Cleveland awaits.
We follow Dick, who guides the band onto the stage platform, still in darkness.
Already, stomping and applause is mounting.
Russell turns to William before taking the stage:
RUSSELL Your Mom kind of freaked me out.
WILLIAM She means well.
Still rattled, he takes the stage.
We see the unbridled enthusiasm of the faces on the front row.
A wave of cigarette lighters stretch out before them.
DICK From Troy, Michigan...
Russell thwacks a couple chords.
Audience thunders.
He turns to other members, feeling chills.
It's in these moments that everything else disappears.
They bow and wave, still in darkness...
each member seems to have his own fans.
Dick lets all this play out before finally adding...
DICK (cont'd) Would you please welcome to Cleveland...
More applause.
This is very very very very fun.
DICK (cont'd) Stillwater.
Lights come up.
A full blast of audience love hits them right in the face, as they begin "Fever Dog."
The band charges headlong into their set, as various fans are squeezed up out of the crowd and onto the stage.
Who is in the middle of playing, as he smoothly whips off his guitar, and uses the instrument to send a Frenetic fan back into the crowd.
He slips back under the strap, laughing.
More stage climbers spring up where that fan came from, and Russell now watches as Jeff Bebe dodges a fan and comes over to Russell to lean on him.
Russell turns to share the moment with Penny, dancing with arms in the air at the side of the stage.
William in the dressing room, eyes red with exhaustion, finally interviewing Russell.
He holds the mike stoically.
WILLIAM So when you play a great show like tonight...
Dick enters with great urgency.
DICK Okay.
DICK I need everybody's attention.
The kid shuts his eyes.
He knew this would happen.
DICK (cont'd) Alright, well, the rumors are true.
DICK (cont'd) The record company has sent a big-time manager here to try and talk you into replacing me.
DICK (cont'd) His name is Dennis Hope.
DICK (cont'd) I know you've all heard of him.
DICK (cont'd) He's got all the big bands.
DICK (cont'd) He's right outside.
DICK (cont'd) He wants five minutes with you right now.
DICK (cont'd) I think we gotta do it.
RUSSELL Then bring him in.
William shuts off his tape recorder.
JEFF Bring him in!
JEFF We'll send him out on a rail!
RUSSELL We'll finish on the way to Boston.
RUSSELL You can fly home from Boston.
William nods, exhausted, as Dick opens the door.
In walks a small general of a man in a baseball t-shirt, well-trimmed beard and bowl cut.
He holds the super-new Halliburton briefcase.
He is DENNIS HOPE, 25.
A man from the midwest, with a vision of the future of rock and roll.
Already in his head are all the things that will come to pass.
Higher ticket prices.
Merchandising deals.
Greater distribution and accounting of album sales.
He shrugs hello to the band.
DENNIS HOPE Hi.
RUSSELL We already have a manager.
RUSSELL He's been with us from the beginning.
Hope appreciates the lack of small talk.
He strides the room with the joyful enthusiasm of a kid who wants to build a fort.
Russell watches, dismissive, holding his guitar.
DENNIS HOPE Respectfully.
DENNIS HOPE We all have our roots.
DENNIS HOPE I believe in bands holding onto their roots.
DENNIS HOPE But those roots need to be augmented.
DENNIS HOPE I'm gonna tell you the truth - I may enrage some and enthrall others.
DENNIS HOPE I don't really give a fuck.
DENNIS HOPE Your manager here needs a manager.
DENNIS HOPE Example.
DENNIS HOPE If you hadn't run out on the contract in Phoenix, you could have sued over Russell's hand...
DENNIS HOPE but you left, negating the contract, forfeiting the deposit, and you effectively traveled a long way to pay that promoter...
DENNIS HOPE to electrocute you.
Russell looks at his hand.
DENNIS HOPE (cont'd) We can all work together.
DENNIS HOPE (cont'd) Your damages have put you way into the hole for this tour.
DENNIS HOPE (cont'd) Right now you owe the record company more than you've got.
DENNIS HOPE (cont'd) But your record's selling, there's money to be made.
DENNIS HOPE (cont'd) So I've brought a plane in, we can add more shows to make-up the difference.
DENNIS HOPE (cont'd) Respectfully.
RUSSELL We travel by bus.
JEFF Doris is the soul of this band!
JEFF That bus has been our home since we were the Jeff Bebe Band.
Dick watches his loyal band with admiration.
DENNIS Hey man -- it's travel on a pogo stick if I thought we'd make more money.
DENNIS You can play more dates with a plane...
Penny Lane stands on stage facing the empty arena.
The roadies have packed up and moved on.
She is alone in the poetic and trash filled structure that was just hours ago filled with people.
(Behavior to come)
The band meeting continues.
RUSSELL Hey man, it's not about the money!
RUSSELL It's about Playing music, and turning people on!
The band agrees.
DENNIS HOPE Yes, of course.
DENNIS HOPE Clearly.
DENNIS HOPE Respectfully.
DENNIS HOPE But on the distasteful subject of money.
DENNIS HOPE Just know.
DENNIS HOPE You're making it -- right now -- and it's all --
He gestures to infinity.
DENNIS HOPE (cont'd) -- out there.
DENNIS HOPE (cont'd) I'm just talking about bringing it --
Bringing his hand together in a fist, he returns it, close to his heart.
DENNIS HOPE (cont'd) -- back here.
The band looks at Dick, who manages not to be speechless.
DICK But why should we pay you for something we can do ourselves?
DENNIS HOPE Do you know how to keep from getting charged for the ice below the floorboards of Chicago Stadium?
DENNIS HOPE Do you know how to do a headlining tour, do you Claire Rothman at the L.A.
DENNIS HOPE Forum?
DENNIS HOPE Do you know Bobbi Cowan, Lisa Robinson, Jim Ladd, Frank Barcelona?
DENNIS HOPE This is Cleveland.
DENNIS HOPE Where's Kid Leo??
DENNIS HOPE Do you know how you get a record not pressed but played?
DENNIS HOPE Do you know?
DENNIS HOPE I didn't invent the rainy day, man.
DENNIS HOPE I just own the best umbrella.
He laughs.
It's fun.
Band members are now listening, curiously spellbound.
DENNIS HOPE (cont'd) Because as much as you may believe that it will last forever, it does not last forever...
DENNIS HOPE (cont'd) your biggest fan right now soon they're going to go to college, gonna wanna buy clothes, spend that money some other way, and you know what?
DENNIS HOPE (cont'd) They'll tape your record from a friend's copy.
Russell stops fingering his guitar.
Shot moves across the faces of the band members.
Pain.
DENNIS HOPE (cont'd) You've got to take what you can, when you can, while you can.
DENNIS HOPE (cont'd) And you've got to do it now.
DENNIS HOPE (cont'd) That's what the big boys do.
The band squirms, but listens.
DENNIS HOPE (cont'd) Because if you think Mick Jagger will still be out there trying to be a rock star at age fifty, you're sadly sadly mistaken.
Now he's reaching them.
Their slackened roar-weary faces stare back at the young dynamo.
DICK Yeah, well...
DICK we'll think about what you said.
DENNIS HOPE No no.
DENNIS HOPE You don't understand.
DENNIS HOPE I'll think about it.
DENNIS HOPE I'm not auditioning.
DENNIS HOPE I came here to decide whether I want to represent you.
DENNIS HOPE So I'll stand outside for a moment, and think about whether I want to stay.
He leaves the room with a pleasant shrug.
Stunned silence.
William watches their body language.
No one wants to talk first.
Their faces read as -- who was that guy, and how can we talk him into staying?
William watches as the band stands inside the new plane.
Dennis Hope looks on.
RUSSELL This is not us.
RUSSELL This is too much.
He looks around for support.
Grim nodding faces.
RUSSELL (cont'd) This is too much.
William watches as Russell reclines.
Russell grabs Penny, and she falls into the seat next to him.
We hear the loud oncoming sound of the plane in flight, as Dennis cooly asks for Penny's seat.
DENNIS HOPE Do you mind?
Doris the bus stays behind in the parking lot, abandoned near a field.
The new plane lifts off in the background, as the bus sits alone, as if crying steel tears.
Bus Banner reads simply: CLEVELAND.
Reprise ending of Whole Lotta Love.
The girls sit on the jumper seats at the back of the plane, with William.
William trudges the hallway with tape-recorder and notebook, trolling for Russell.
He passes Boston travelogue posters on the walls.
A few room doors are open, he looks for any sign of the guitarist.
William veers into Dick's room, where a poker game full of Roadies is in progress.
The room is thick with exotic smoke.
They are a bunch of road-hardened snobs, smoking cigars and other items, famous to themselves, listening not to rock and roll...
but Sarah Vaughn.
WILLIAM Anyone seen Russell?
DICK The Enemy!
Door widens to reveal Russell.
RUSSELL Hey!
RUSSELL Welcome to the Road Crew Poker Party.
RUSSELL This game's been going of for two years.
DICK That's Mick - he's with The Who.
DICK That's John - with J. Geils.
DICK And that's Richard with the Eagles...
DICK and you know The Wheel.
THE WHEEL Hey.
Grumbling roadies continue playing.
Like an old pro, the kid turns down a Cola-can hash-pipe.
This hand is down to Dick, and a roadie named REG from Humble Pie.
DICK Side proposition.
DICK For fifty dollars and a case of Heineken, I will put into the pot...
DICK three Lovely Ladies, Including the famous Penny Lane...
DICK the Band-Aids, who need to exit our tour before New York...
REG It's a deal.
REG Show 'em.
Dick lays down three tens.
Reg lays down three Kings.
Dick loses.
DICK Three Lovely Ladies...
DICK now in the custody of Humble Pie.
REG Alright, so we owe you fifty dollars and a case of Heineken.
Embarrassed, Russell notices the kids face.
He leans over, and speaks confidentially to him.
RUSSELL Look.
RUSSELL Nobody's feelings are getting hurt here.
RUSSELL She already knows Leslie's coming To New York tomorrow.
RUSSELL They all understand.
RUSSELL This is the Circus.
RUSSELL Everybody's trying not to go home.
RUSSELL Nobody's saying goodbye.
WILLIAM No, I got it.
RUSSELL These are the Rules that come with every electric Guitar and every amplifier.
RUSSELL They're not just written anywhere.
RUSSELL Rock and roll, brother.
RUSSELL No attachments.
RUSSELL No boundaries.
But the kid feels bad, and Russell knows it.
RUSSELL (cont'd) Quit looking at me like that.
The kid is still stuck on the road.
He is in hell now.
Wearily, with deep circles under his eyes, he shuts his eyes for a moment.
Another band is moving through.
SABBATH ROADIE Keep this hallway clear!
William and Penny sit on opposite ends of a blue locker-room bench.
It's a small dressing room, crowded with roadies, guitars and men in stages of half-dress.
Piles of luggage headed for New York sit by the door.
The door suddenly opens and Dick arrives with champagne and a cake decorated with a sparkler.
It is placed in Penny's lap.
It reads: Unforgettable Penny...
Age Unknown.
Boston, 1973.
They gather now as the cake sits before a surprised and enchanted Penny Lane.
DICK Happy Birthday from us.
William watches her face as she reads the message on the cake.
It hasn't sunk in yet.
Russell produces a piece of hotel stationery.
He reads a poem.
RUSSELL So Penny our friend has gained another year.
RUSSELL But long ago, she threw it in gear.
RUSSELL She rocked the south The East and West.
RUSSELL Could you please get off this endless tour Where we're Black Sabbath's fucking special guest?
Laughter.
RUSSELL (cont'd) She says she's retired Though we've heard that before.
RUSSELL (cont'd) She chose us...
RUSSELL (cont'd) And in Penny Lane we trust She is a fan of this band.
RUSSELL (cont'd) Much more so than us.
William watches her face.
Still enchanted, she hands out slices of the cake.
DENNIS HOPE Sorry the plane isn't bigger.
It hits her.
She looks at William for a clue.
His truthful face does not look away.
Now she knows.
She turns to the others -- the plane isn't bigger?
Shot moves in on Penny as she blinks just a little, cutting into the cake, still mugging for everybody, covering it all with a layer of sweet giddy laughter.
Shot comes to rest behind her, her head turning to connect with band members.
Each of them look away, nobody maintaining eye contact with her except the one she now doesn't look at.
William.
She blows out the candles, vamping Marilyn Monroe-style, and sucks off the frosting seductively, to cheers.
Russell watches, as we push in on Penny.
She notices all the luggage is gone, only her two cases remain by the door.
William exits a backstage Portosan.
Penny catches him by the grilling area where catering is preparing for the outdoor event.
Their laminated passes swing from around their necks.
Thuding in the distance, Stillwater plays for a cheering outdoor crowd.
The sound of summer insects in the air.
PENNY So it wasn't a birthday party, it was a farewell.
William doesn't answer.
He looks at her, blowing some hair out of her face.
PENNY (cont'd) You think you can fool me.
PENNY (cont'd) I read you.
PENNY (cont'd) I know what you're thinking.
WILLIAM What's that?
PENNY You're worried about me and Russell.
WILLIAM Yeah.
WILLIAM I gotta work on that.
PENNY You're so sweet.
PENNY God -- if there was more of you in him...
WILLIAM Don't tell me this stuff.
WILLIAM I want to like him.
PENNY Did you miss your test or something?
He shakes his head.
It's so beyond a test.
PENNY (cont'd) I know I'm not on the plane, and I'm not going on some other band's bus.
PENNY (cont'd) I mean, I could go with the Sabbath road crew, but that would be pathetic.
PENNY (cont'd) The girls are all going with Humble Pie.
PENNY (cont'd) If you could find out from Russell --
WILLIAM Penny -
PENNY Forget it.
PENNY I'm flying to New York myself.
PENNY I have a bunch of partial tickets.
PENNY I know his ex-wife, current girlfriend's going to be there -
William's eyebrows rise.
She examines his face for clues.
WILLIAM -- I'm not sure that's a good idea.
PENNY What?
PENNY What are you saying?
PENNY What do you know?
PENNY Did Russell say something?
WILLIAM I don't know anything.
PENNY I know he wants me there.
PENNY He gave me a cake.
PENNY He wrote me that sweet poem.
WILLIAM Wake up!
WILLIAM Don't go to New York!
PENNY What are you telling me?
She looks so achingly beautiful to him.
WILLIAM Because you're not who you said you were!
WILLIAM I thought you were retired!
PENNY You're right.
PENNY I'm not who I said I was.
PENNY I'm just like you.
PENNY I love music, so this is my family.
PENNY Some people like tractors, and they hang out with tractor people.
PENNY What's the worst that could happen if I go to New York?
PENNY "I get my little heart broken?"
WILLIAM Oh no.
WILLIAM Never you!
WILLIAM You eat people alive!
She tears some leaves off a tree.
He looks at her, unable to formulate a response.
PENNY I'm sorry I told you so much.
PENNY You have some way of making everybody tell you all their secrets.
WILLIAM That's a good one.
WILLIAM Tell me too much and make it my fault.
He continues walking, she follows.
They have ventured outside the backstage area, onto adjoining Boston farmland.
The show booms in the background.
PENNY Come on.
PENNY You've seen what's happened.
PENNY Russell and I fell in love.
PENNY How much, I don't know...
PENNY but this is the first time I've fallen for someone, really fallen...
PENNY since Iggy, and I'm not happy about it.
WILLIAM You slept with Iggy Pop!?
She says nothing.
WILLIAM (cont'd) Why don't you just tell me now, who else -- so when I go to the record store, I know who to be jealous of.
WILLIAM (cont'd) Because right now, it's looking like the whole store!
He's upset.
She stares at him.
PENNY You'll remember me forever.
PENNY I was there when you lost your virginity.
WILLIAM So was Steely Dan!
WILLIAM It was a crowded room.
She laughs, can't help it.
Then:
PENNY You make me laugh.
PENNY I think I'm gonna cry.
WILLIAM I thought we were going to Morocco!
WILLIAM There's no Morocco.
WILLIAM There's never been a Morocco.
WILLIAM There's not even a Penny Lane.
WILLIAM I don'teven know your real name.
PENNY If I ever met a guy in the real world, who looked at me the way you just looked at me...
WILLIAM When and where does the real world occur?
WILLIAM I am really...
WILLIAM confused here.
WILLIAM Fuck!
WILLIAM All these Rules And all these sayings...
WILLIAM and nicknames...
PENNY You know -- you're too sweet for rock and roll.
WILLIAM Where do you get off...
WILLIAM where do you get "sweet?" I'm not sweet.
WILLIAM I'm dark and mysterious and pissed-off and I could be very dangerous to all of you...
WILLIAM I'm not sweet, and you should know that about me!
WILLIAM I am The Enemy.
PENNY You're not any of those things and that's what I love about you.
William stands there in disbelief, unable to look at her.
WILLIAM You fall in love to keep from falling in love.
PENNY I don't want to go home!
WILLIAM Well, I have to go home.
WILLIAM And you never helped me.
PENNY Yes I did.
WILLIAM That disc-jockey in Arizona got a better interview than me...
WILLIAM and he was asleep.
He starts walking back to the stage.
She follows.
They are two very young kids thrashed by the seas of rock and roll.
His frustration increases.
She just doesn't get it.
Applause in b.g.
She grabs his shirt.
PENNY Look.
PENNY You should be happy for me.
PENNY You don't know what he says to me in private.
PENNY Maybe it is love.
PENNY As much as it can be with someone who --
WILLIAM -- sold you to Humble Pie for fifty dollars and a case of beer?
WILLIAM I was there!
He is instantly sorry.
Her world privately crumbles, but she tries to remain stoic and carefree.
PENNY What kind of beer?
Sapphire, Polexia, and Estrella bump along to the music and the road.
They strain to maintain dignity in these decidedly third-class surroundings.
There's only one small blurry window.
POLEXIA Who did this to us?
Mom on the phone.
ELAINE Then don't come home.
ELAINE Don't do this to me.
ELAINE If you're going to miss graduation, don't come home.
She hangs up.
William on the phone.
Speechless.
Elaine faces her Humanities class.
She stands in an amphitheater-style, inner-city college classroom, decorated with colorful unorthodox artifacts from her home.
These earnest city college students listen to her.
But she cannot continue.
There is a thundering upset inside her.
ELAINE I'm sorry.
ELAINE I can't concentrate.
ELAINE Rock stars kidnaped my son.
Music.
Russell and band bounces down in NYC.
Russell listens to music on headphones plugged into large boom box.
William watches, facing the band from the jump seat of their limousine, heading into New York.
Up ahead, Manhattan looms, beautiful and scary.
RUSSELL "New York.
RUSSELL Just like I pictured it...
JEFF " ...
JEFF skyscrapers and everything."
RUSSELL We showed you America.
RUSSELL We did everything but get you laid.
Beat.
They look at each other curiously.
How much does the other guy know?
Russell and band spill out of limo.
The New York cluster of hardcore Stillwater fans wait outside.
They hold collector's sleeves covering albums to be autographed, and fresh magic markers in hand.
William in tow crawls out of the limo last.
Dick goes to work, pulling luggage from the trunk.
A serious- looking Fan (LENNY) approaches Russell with an autograph card.
FAN I'm from the Church of Lenny.
FAN We bow to his will and all that it represents - The King of the King of Kings.
RUSSELL Make it out to - ?
FAN To Lenny.
Russell nods -- of course.
He signs, as Dick approaches with a well-placed word in his right ear.
DICK She's here.
William turns, expecting to see Penny.
Instead we see the long-limbed, athletic, pretty and collegiate LESLIE.
She holds a Nikon camera, and snaps their picture.
JEFF Leslie!
DICK Your room is completely stocked, far away from any noisy ice machines, elevators or maid quarters.
DICK The air- conditioning is already on.
DICK And here is your security key -- by the way, you look stunning.
LESLIE ThanksI'llseeyoulater.
Nearby, the young journalist studies the tour's subtle shift in welcoming Leslie.
Dick's New York side is almost military.
DICK Bags in five!
DICK Cars leave for the party at six!
William studies Leslie, everyone saying hello to her, everyone knowing the subtext.
Nobody saying a word.
William pulls his heavy bag out of the back of the limousine.
The bag breaks, and the contents spill out onto the New York sidewalk.
Bars of soap, ashtrays, hotel keys, crumpled paper, the contraband t-shirt, "Do Not Disturb" signs, notes, towels and thick telephone books from every city.
DICK (cont'd) You know.
DICK (cont'd) There are lighter souvenirs.
WILLIAM Well -- I kept thinking I was going home the next day --
DICK I did too.
DICK Fifteen years ago.
All help him with his spilled souvenirs.
Russell shares a private look with the kid.
Nearby Leslie greets other band members.
WILLIAM Ric!
It's Super Zeppelin fan Ric Nunez.
RIC It's all happening.
RIC Zeppelin is at the Plaza.
RIC So's four other bands.
RIC They're partying up there right now.
RIC Sapphire, and Miss Penny Lane too...
RIC She wants you to call her.
RIC They're all staying under the name Emily Rugburn.
William takes in the information, while regarding Ric's new custom shirt, which features the words to Zeppelin's "The Rain Song."
RUSSELL After the party.
RUSSELL I'll come to your room - I promise.
RUSSELL We'll talk.
RUSSELL This is Leslie, by the way.
RUSSELL Leslie, this is our wayward friend from Rolling Stone.
RUSSELL The Enemy.
They shake, she smiles randomly.
William checks in.
CLERK William Miller?
CLERK Sir, you have an urgent call from a Mr. "Ben Fong-Torres."
CLERK He's holding for you, right now.
William takes the phone.
The Clerk watches curiously as the kid adopts a new persona.
WILLIAM Hello.
On a rainy day in San Francisco, Ben Fong-Torres stands in the copy-strewn office of the young editor/publisher JANN WENNER.
Several other editors are also present in the background, including David Felton with cigarette-holder in mouth, and a prep-school Fact-Checker named ALLISON.
BEN Congratulations.
BEN It's gonna be a cover.
BEN Neal Preston will shoot 'em next week in L.A. we need you back in San Francisco tomorrow.
BEN We'll finish the story here.
William is overwhelmed with many emotions, fear topping the list.
BEN (cont'd) You can tell the band.
BEN (cont'd) Allison, our fact checker, needs you to transmit whatever you have of the story, tonight, now, along with your notes.
BEN (cont'd) There is a mojo at the Daily News they'll let us use -
WILLIAM Mojo?
BEN A mojo.
BEN It's a very modern machine that transmits pages over the telephone.
BEN It only takes eighteen Minutes a page...
The sound of feet on pavement.
William looks at addresses, hustling to the Daily News office.
William tears pages from his notebook and feeds them into the large and clunky earliest model fax machine -- "The Mojo."
We hear David Bowie.
"The Jean Genie."
William weaves, exhausted, into the Stillwater press party at this legendary New York nightspot.
The Doorman, who checks i.d.s, sees the kid and expresses great doubt.
DENNIS HOPE He's okay, he's with us -
Hope shoves him past the Guard, and sends him into a very mature new world.
The famous hub of New York rock and roll.
A strong whiff of decadence mixes with youthful naivete.
Not a hippie in sight.
William walks through, looking for familiar faces.
Overhead we hear Stillwater.
"If You Say Nothing."
The party is filled with scenesters, long silver-haired glamsters, some British journalists, and many hunched young skinny bodies in leather jackets.
Russell grabs him by the arm.
RUSSELL Ah ha!
RUSSELL There you are, ya little fucker.
RUSSELL Come on --
WILLIAM I have some good news.
RUSSELL -- I'll piss to that.
RUSSELL Follow me.
They enter the small bathroom.
Russell bolts the door, faces the urinal and pees.
His own music throbs in the next room.
RUSSELL Dennis Hope took me aside, and wants to manage Me solo.
RUSSELL Says to lose the band by February.
RUSSELL Should I do it?
RUSSELL I have no perspective anymore.
William pees in silence.
RUSSELL (cont'd) At what point do I just take the hint?
RUSSELL (cont'd) Nobody Loves this band.
RUSSELL (cont'd) People like us, do they love us?
WILLIAM I do.
RUSSELL Oh - get this - somebody told Penny Lane I sold her for beer.
RUSSELL The network of these chicks!
RUSSELL Like I would do that.
RUSSELL It's Jeff who told her, right?
RUSSELL Not you, right?
RUSSELL None of these guys can just calm down and be a fuckin adult.
RUSSELL Now she's here, freaking out.
RUSSELL Leslie can smell it.
WILLIAM Wait.
WILLIAM I've got something to tell -
But he finds himself trailing Russell to the back room bar.
Leslie in the bathroom.
Penny enters and watches her discreetly.
They stand together, side-by-side at the mirror.
Leslie looks once, turns and then turns back at Penny.
She knows.
William sits with the band.
Over Jeff's head, Penny hangs nearby, at the outskirts, drinking and dancing.
They share a look, feigning casualty.
WILLIAM You guys -- you guys --
WILLIAM You're gonna be on the cover of Rolling Stone.
Stunned and overwhelmed, the band waits a beat, lets it sink in...
and goes wild.
Russell, stunned too, looks at the kid.
It's big news.
Jeff stands immediately, eyes moist, glass raised.
JEFF The cover of Rolling Stone.
JEFF And we made it together.
JEFF They don't just put somebody with one little hit on the cover of Rolling Stone Fucking Magazine, man.
JEFF We made it.
The band nods solemnly, importantly.
JEFF (cont'd) Damn it -- I'm gonna enjoy this.
JEFF (cont'd) The first time I bought that magazine The Beatles were on the cover.
JEFF (cont'd) Four of them.
JEFF (cont'd) Four of us.
JEFF (cont'd) Together.
They begin singing the then-current Dr. Hook and the Medicine Show hit, "The Cover of the Rolling Stone" to William.
LESLIE Who is that girl?
LESLIE She's creeping me out.
LESLIE She's not with any of you, is she?
WILLIAM/DICK She's with me.
And now Leslie has confirmation.
A symphony of looks, as Dick gets to his feet and moves to confront Penny.
Penny Lane's eyes fill and she runs out.
Russell stands...
and sees William also stand.
William turns and follows her.
Russell stands watching, and does not leave.
We hear Elton John's "Mona Lisas and Mad Hatters."
William exits as a crush of Partygoers arrives.
He doesn't know where she is.
He takes off to examine the cabs stuck in traffic.
Song continues.
He looks in the backs of cabs.
None of them her.
Music continues.
He runs down the streets, looking for her.
Alone in New York City.
William on the house phone.
WILLIAM Emily Rugburn, please.
William approaches Suite 702.
The door is open.
He hears new band voices, and sees new faces.
MUSICIAN # 1 intercepts him.
WILLIAM Hi.
WILLIAM I'm a friend of Penny Lane's.
MUSICIAN # 1 Aren't we all -
Musician types are leaving.
WILLIAM Where is she?
Room Service arrives.
Some appetizers and a large expensive bottle of champagne on ice.
ROOM SERVICE GUY Can somebody sign for this?
William does.
ROOM SERVICE GUY (cont'd) Thank you Mr. Rugburn.
Two more Musicans (English) exit the back room party.
The room is clearing out.
ENGLISH MUSICIAN She's sick.
ENGLISH MUSICIAN Let's get out of here.
ENGLISH MUSICIAN # 2 She used to be so much more together.
William watches all, champagne in hand, and finds her in the backroom.
She's addled and nearly passed out.
WILLIAM What happened?
PENNY LANE I'm not good at goodbyes.
She sags.
He grabs the phone.
PENNY LANE (cont'd) You're the last of my old-time friends.
PENNY LANE (cont'd) Polexia went to England with Deep Purple...
PENNY LANE (cont'd) can you believe that?
PENNY LANE (cont'd) Even Sapphire's out someplace else.
PENNY LANE (cont'd) All she left was her quaaludes.
WILLIAM Oh -- wonderful.
WILLIAM Front desk?
WILLIAM Please send a doctor.
WILLIAM Room...
WILLIAM what room?
WILLIAM 703.
WILLIAM 702.
WILLIAM Both rooms, either room.
WILLIAM This is Mr. Rugburn, Yes.
WILLIAM My wife's had an accident with some quaaludes.
WILLIAM Yes - I'll do that.
The room has emptied out.
Just them, and the remnants of a movable party that has moved elsewhere.
WILLIAM (cont'd) Wake up!
He struggles to get her on her feet.
She tips over on her strappy platform shoes.
He struggles to untie them.
The School band plays "Colour My World."
School PRINCIPAL at the podium.
PRINCIPAL And now...
PRINCIPAL out graduating class!
PRINCIPAL Jane Abbott!
A peppy student bounds up and grabs her diploma.
Elaine Miller watches dolefully in the audience.
William holds Penny in his arms.
Finally she is close to him.
PRINCIPAL Victor Sanchez!
Warm applause for another student who grabs his diploma.
He takes off his mortar board to flash an American flag bandana.
He raises his diploma in victory.
William holds Penny Lane, and keeps her moving.
It's a sagging, messy slow dance.
WILLIAM "In the unlikely event of a water landing...
PENNY "...
PENNY you will be required to wear a safety vest."
WILLIAM Keep going.
PENNY "Please place all stowable luggage in the overhead compartments...
PENNY out in the seat in front of you."
WILLIAM "Seat and tray tables."
PENNY "And seat-backs and tray-tables should be in their full and upright and locked positions...
PRINCIPAL And now...
PRINCIPAL out "Pending" Graduates!
PRINCIPAL William Miller...
PRINCIPAL not present.
Elaine applauds her son, stoically.
It is a dagger through her heart.
A sympathetic look from a nearby Mother continues the pain.
They move slowly, she's fading.
WILLIAM "In the tragic event of a water landing..."
The Principal shares a few thoughts:
PRINCIPAL And to the class of 1973, we say --
PRINCIPAL Don't forget to remember yourself as you are today...
PRINCIPAL Full of hope...
PRINCIPAL and the dream that everything is possible...
PRINCIPAL Remember this, twenty years from now, when we all own home computers and we all travel in shiny electrical cars that move swiftly, high above the city...
PRINCIPAL They key to the future is keeping today alive forever.
Elaine's head lowers slowly in a sea of happy parents.
The day will never end.
Mrs. Deegan slips into the seat next to her.
MRS. DEEGAN First.
MRS. DEEGAN Release the guilt.
MRS. DEEGAN Second -
ELAINE Please let there be only two, because I can't get past Number One.
MRS. DEEGAN Second.
MRS. DEEGAN Leave a little room for the other teachers in this world.
MRS. DEEGAN He's out there looking for mentors.
ELAINE He's got twelve of them.
ELAINE They're lined up.
ELAINE He's just tired of me.
William holds Penny.
She is very woozy.
PENNY "...
PENNY you will be required to..."
PENNY I'm tired.
She is very groggy, as he holds her.
WILLIAM Well.
WILLIAM Now that I have your attention.
WILLIAM And you may not remember this later, I just want to make it clear that...
WILLIAM Hey!
WILLIAM I know you've heard this before.
WILLIAM And I have never said this to anybody, not really - well, nobody who didn't legally have to say it back to me, but -
WILLIAM I love you.
WILLIAM And I have a hard time sharing you with all of rock and roll because I - why am I nervous?
WILLIAM - You'll never remember this - HEY!
WILLIAM I love you, and I'm about to boldly go where...
WILLIAM Many men have gone before...
He kisses her.
A doctor and nurse come crashing into the room.
They push past William and pull Penny into the bathroom.
He sits on the edge of the bed, looking into the bathroom, as they work on her.
We hear Stevie Wonder.
"My Cherie Amor."
Doctor places a tube down Penny Lane's throat.
A bored nurse holds a water-bag, lowering it to ground level.
Her feet sticking out, wriggling.
He watches, as music continues.
Her amber-colored stomach contents look like a Jackson Pollack portrait of the era, with three partially dissolved pills.
Doctor hands enter frame and remove them.
Music continues.
The Doctor re-appears, and sits down next to William, as the Nurse exits.
The Doctor withdraws a three-page report form.
DOCTOR Your wife will be okay for now -
WILLIAM Thank you Doctor.
DOCTOR However, she says you're her brother.
WILLIAM She's a little confused.
The ice shifts in the champagne bucket nearby.
The Doctor sizes up the situation.
DOCTOR Nice champagne.
WILLIAM I don't have a driver's license.
WILLIAM With me.
DOCTOR Tomorrow's my wedding anniversary.
DOCTOR I'd prefer to take care of this without facing the dawn at the police station.
DOCTOR So if you can find a way to get this girl - your wife - back home to her parents, I'd let you pay me anything you can afford.
DOCTOR Because you don't appear to be related to the famous Rugburns of Rhode Island.
His eyes flick to the champagne.
The kid takes a hint, reaches over to the champagne.
WILLIAM Happy Anniversary.
The Doctor puts the champagne in his bag.
DOCTOR She won't be good company, but keep her awake for another four hours.
Song continues.
William and Penny drag themselves through the airport.
He guides her to the ticket counter.
Penny wears her green coat, large sunglasses.
He sorts through her many partial tickets.
They are both so tired.
She shakes off her coat -- she's suddenly very hot -- and he grabs it and loops it through her bags.
She's irritable, and ready to go home.
PENNY When I was 14, my Mom and her boyfriend took me to a Rolling Stones concert - and I freaked out and I rushed up to the front of the stage and then a thousand people had the same idea at the same time and I was getting crushed.
PENNY And I couldn't breathe and that thought flashed through me - almost like a car accident - I thought I might die.
PENNY And it was in the middle of "Midnight Rambler" and Keith Richards saw me.
PENNY And he came over, and came to the front of the stage, and he pulled me out.
PENNY And they took me backstage and they gave me coke with ice and a - and a lemon.
PENNY And I never went home.
WILLIAM What about your Mom?
PENNY She always said - "Marry Up."
PENNY Marry someone grand.
PENNY That's why she named me Lady.
WILLIAM She named you Lady?
PENNY Lady Goodman.
WILLIAM No.
PENNY You never really get used to it, either.
WILLIAM Well -- this -- this just explains everything.
He wishes it did.
She rubs her stomach.
It's a rocky morning.
WILLIAM (cont'd) See you back in the real world.
PENNY See you back there.
She kisses his forehead, and takes off down the accordian leading to her plane.
She drops her coat again, bending down to retrieve it.
WILLIAM Hey Lady!
Four Woman turn, but not Penny.
She disappears.
Penny Lane settles into her seat on the airplane.
She notices William watching from the terminal window, and waves.
STEWARDESS Please extinguish all flammable items, and return all seats and tray tables to their full and upright locked positions.
She mouths along with the words.
There is no one to share the joke with.
And then a few blurry memories come back to her.
She gestures to him...
understanding him more fully...
as he disappears.
William walks alongside her plane, moving from terminal window to terminal window.
Catching her glance again, he's picking up steam.
What's she saying?
She keeps watching as he runs alongside, still keeping up with her plane.
She now fully remembers, and places her outstretched fingers on the window.
She mouths the words: I'll see you back home!
He us running through her fingers.
Who can run no further.
Russell and William are in mid-interview.
The kid's microphone is out.
It's a little bit of a rough flight.
William wears the same clothes.
RUSSELL Why didn't you come back to the party?
RUSSELL Bob Dylan showed up.
RUSSELL He was sitting at our table for...
RUSSELL had to be an hour, right?
RUSSELL Just Rapping.
RUSSELL Bob Dylan!
RUSSELL I kept looking for you.
RUSSELL I was going to introduce you.
The kid feels pain.
JEFF What happened to you last night?
WILLIAM It's a log story.
A sharp jolt of turbulence.
Russell begins pounding on the card table in rhythm.
RUSSELL "Peggy Sure...
RUSSELL Peggy Sue...
DICK Please.
RUSSELL "Pretty pretty pretty pretty Peggy Sue...
A moment of laughter, and then bam.
Jeff's drink rises and suspends briefly in mid-air.
The plane takes another mighty knock.
JEFF We shouldn't be here.
RUSSELL Doris, we miss you!
Fear is creeping in around the edges.
William, already an uneasy flier, looks down.
PILOT'S VOICE This is Craig, your pilot.
PILOT'S VOICE It appears we've caught the edge of that electrical storm we were trying to outrun.
PILOT'S VOICE Buckle up tight now.
PILOT'S VOICE We're gonna do our best to getcha out of this.
The rocking of the plane worsens, as all buckle up.
JEFF "Electrical storm?"
RUSSELL Rock and roll.
The sky darkens abruptly.
William looks up, increasingly nervous, stares straight ahead.
The plane suddenly drops and stabilizes.
Everyone is silent but Russell.
RUSSELL (cont'd) Wooooooo Baby!
A moment later, an ashen-faced CO-PILOT emerges, balancing himself with hands on the ceiling of the shuddering plane.
CO-PILOT We're gonna try to land in Tupelo.
CO-PILOT We're going to have to cut the inside lighting for the next several minutes.
CO-PILOT We found a field to land in.
The kid notices Silent Ed is rubbing a small crucifix.
DENNIS HOPE A field?
JEFF I can't breathe.
Push in on Russell.
We hear a series of unfamiliar electrical sounds.
The plane screwballs through the sky.
CO-PILOT It might be a rough set-down.
CO-PILOT We should be fine.
CO-PILOT But what we do say in a situation like this is - We would pass but before the plane ...
CO-PILOT disassembled.
CO-PILOT However, God help us, if there's anything you want to say to each other, any secrets, anything like that, now would be a good time.
CO-PILOT But just hang in there.
CO-PILOT We'll get you out of this.
He returns to the cockpit.
The weather worsens, as the hail suddenly pelts the plane, and it comes down hard.
Inside lights shut off.
William stares straight ahead, as the cockpit door swings open - total chaos visible inside - and then shuts again.
DICK And everyone thinks it's so glamorous out here.
LARRY He just told us we're gonna die.
JEFF We're gonna crash in Elvis' hometown --
RUSSELL Shut up.
JEFF -- we can't even die in an original city!
RUSSELL C'mon Dennis, get us a better city.
Nervous laughter.
Another sheet of hail hits the plane.
LESLIE Oh my God.
Just shaking.
Nearly in tears.
Hyperventilating.
RUSSELL If something should happen.
RUSSELL I love all of you.
RUSSELL I don't think we have to do the secrets thing.
The plane shakes.
Now lightening strikes very close.
A flashing wall of electricity rolls through the plane and evaporates with a burning smell still in the air.
In the darkness:
DENNIS HOPE I once hit a man in Dearborn, Michigan.
DENNIS HOPE A hit-and-run.
DENNIS HOPE I hit him and kept on going.
DENNIS HOPE I don't know if he's alive or dead, but I'm sorry.
LESLIE Oh my God.
The plane wildly rises, and falls.
It stops for a moment.
A strange smooth patch.
DICK I love you all too, and you're my family.
DICK Especially since Marna left me.
DICK But if I ever took an extra dollar or two, here and there, it was because I knew I'd earned it.
RUSSELL I slept with Marna, Dick.
JEFF I did too.
LARRY I waited until you broke up with her.
LARRY But me too.
JEFF I also slept with Leslie, when you were fighting.
RUSSELL You...
RUSSELL slept with Jeff?
LESLIE Yes, but it didn't count.
LESLIE It was the summer we decided to be free of all rules.
RUSSELL And you say you "love me."
JEFF I don't love you, man.
JEFF I never did.
RUSSELL Please.
RUSSELL Enough.
JEFF NONE of us love you.
JEFF You act above us.
JEFF You ALWAYS HAVE!!
LARRY Finally.
LARRY The truth.
JEFF You just held it over us, like you light leave...
JEFF like we're lucky to be with you.
JEFF And we had to live with it.
JEFF I had to live with you, and now I might die with you and it's not fucking fair.
William watches, catatonic.
RUSSELL You hate me?
RUSSELL You too?
Larry stares at him.
Ed says nothing.
RUSSELL (cont'd) All this love.
RUSSELL (cont'd) All this loyalty.
RUSSELL (cont'd) And you don't even like me.
JEFF And I'm still in love with you Leslie.
Bam.
The plane is pulling sideways, and dropping altitude.
LESLIE I don't want to hear anymore.
LESLIE Shut up!
LESLIE Shut up!
LESLIE Shut up!
RUSSELL Whatever happens, you're dead.
JEFF Don't be self-righteous, Russell, not now.
JEFF You were sleeping with Penny, that groupie.
JEFF Last summer, and up until yesterday.
JEFF Why don't you tell Leslie THAT?
Russell tries to get up and attack him.
The force keeps him in his seat.
He yells.
Loud.
DENNIS I quit.
The turbulence worsens.
William finds his mouth saying emotional words he cannot control.
WILLIAM "That groupie?" She was a Band-Aid.
WILLIAM All she did was love your band.
WILLIAM And you all -- you used her, all of you.
WILLIAM You used her and threw her away.
WILLIAM She almost died last night, while you were with Bob Dylan.
WILLIAM You're always talking about the fans, the fans, the fans.
WILLIAM She was your biggest fan and you threw her away.
WILLIAM And if you can't see that, that's your biggest problem.
Russell and Jeff stare at each other.
The plane is rocking very very hard.
Leslie is crying.
ED I'm gay.
They all turn to the silent drummer.
(It's his first spoken dialogue of the movie.)
Then.
The plane pops out from below the clouds.
Sunshine spikes through the embattled windows of the plane, as they float downwards to the city of Tupelo, Mississippi.
A very very uneasy silence fills the plane.
No one can look at each other.
Out bursts the Co-Pilot, giddy with victory.
CO-PILOT Thank God above, WE'RE ALIVE!!
CO-PILOT WE'RE
Shot of all the occupants, ending with Russell.
Suddenly, the alternative seems far more attractive.
We hear Rod Stewart's "Jo's Lament" as music plays over their still-shocked faces.
Music continues, as they walk together like ghosts in a long and very pregnant silence, ignoring the kid.
Everything is different now.
The kid peels off and throws up in a dumpster.
We continue with the band, unhappily moving forward.
William hustles back to catch up.
They ignore him.
There are much bigger thoughts in play.
No one wants to speak.
JEFF Well, I think we can build on this new honesty.
Boom.
Russell attacks him, and they're pulled apart.
The band continues moving forward, arriving at a fork in the airport terminals.
William stops.
This is where he must part company.
He stands at the mouth of the next terminal, as the band continues, unaware he's split off.
He watches their backs, they've forgotten him.
Then Russell turns, sensing something missing.
William.
All now stop and turn.
Still shell-shocked, they summon a pre- occupied but heartfelt goodbye.
William waves.
Music continues.
William's finger finds San Francisco.
The kid checks the address as he arrives at the MJB Building, and its next-door neighbor, the San Francisco headquarters of Rolling Stone Magazine.
He still wears the same clothes from last night in New York.
William arrives at the front desk, gets the once-over from a friendly RECEPTIONIST, a paragon of new cool.
RECEPTIONIST Leave your package at the desk.
WILLIAM I'm not a messenger.
WILLIAM I'm one of your writers.
WILLIAM William Miller.
He is zombie-tired, with heavy duffel case and his orange bag.
William walks down the center aisle.
Editors and writers look at him, standing at the front of their cubicles to see this exhausted 15 year-old writer.
At the end of the aisle, like a human finish line, stand Ben Fong-Torres.
BEN You're William Miller?
The secret emerges not with a bang but with a slight and tired nod of the head.
WILLIAM Yep.
BEN Oh baby.
Ben leads him into the office of Jann Wenner, the editor- publisher.
William sits.
Editors are feverishly discussing the next issue.
The big concerns of a national magazine are in the air.
Everyone is focused and quick.
The conversation is machine- gun like.
Jann Werner turns to the kid.
JANN We can't run this piece.
The kid's eyes travel to his story -- a stack of fuzzy-looking sheets on the table.
BEN You obviously saw more than you wrote about.
BEN After eight days on the road with these guys.
DAVID FELTON Didn't anything happen?
JANN And where are you in this piece?
JANN What did you want to write?
JANN Because this reads like what they wanted you to write.
BEN What happened to your highly-touted think piece on limitations of a middle- level Band in the face of success?
William sits speechless.
It's sinking in.
Failure.
Conversation continues at a fast pace:
JANN We can push up Chet's Who cover -
FACT CHECKER Good 'cause it's going to take me three days to get through this research.
FACT CHECKER It's all handwritten, on little slips.
FACT CHECKER Plus, they all refer to woman as "chicks."
FACT CHECKER I mean, as a woman I have a problem with that.
FACT CHECKER I know it's a side issue.
DAVID FELTON It's a "puff piece."
DAVID FELTON you fell for 'em.
DAVID FELTON It happens.
DAVID FELTON A relationship forms.
DAVID FELTON You want them to like you.
DAVID FELTON Happened with me and Charlie Manson.
DAVID FELTON He was a very charming...
DAVID FELTON lively...
DAVID FELTON charismatic...
Felton catches himself swooning.
The other are staring at him.
He snaps out of it.
DAVID FELTON (cont'd) ...
DAVID FELTON (cont'd) mass-murderer.
WILLIAM Please let me finish it.
WILLIAM Give me tonight to work on it.
FACT CHECKER Chet's piece is all fact-checked and ready.
JANN Get some sleep.
JANN We'll do another story sometime.
JANN We'll get you a kill fee.
FACT CHECKER His research is all on little bits of paper.
FACT CHECKER Did I say that?
WILLIAM Ben.
WILLIAM You told me to send what I had.
WILLIAM It's not finished.
FACT CHECKER That's being charitable.
Ben looks at the kid, then at Jann.
Jann scans the kid's face for a beat, nods.
JANN Let him use the big office.
JANN It's where Hunter used to write.
William rises, gratefully.
He shakes Jann's hand.
FACT CHECKER You can type.
WILLIAM Yes.
WILLIAM It took it in grade school.
William sits in the "big" office.
It's a small white tank.
After all the sound and fury, there is only the hum of a large electric typewriter.
His research, transcripts and some band photos sit nearby.
He takes a bite of a candy bar, a sip of coffee.
He looks at the phone.
Crazy jazz is playing.
Lester Bangs on the phone.
LESTER BANGS Aw, man.
LESTER BANGS You made friends with them!
LESTER BANGS See, friendship is the booze they feed you.
LESTER BANGS They want you to get drunk on feeling like you belong.
William in the empty Rolling Stone office.
WILLIAM Well, it was fun.
LESTER BANGS They make you feel cool.
LESTER BANGS And hey.
LESTER BANGS I met you.
LESTER BANGS You are not "cool."
WILLIAM I know.
WILLIAM Even when I though I was, I knew I wasn't.
LESTER BANGS That's because we are uncool!
LESTER BANGS And while women will always be a problem for guys like us, most of the great art in the world is about that very problem.
LESTER BANGS Good-looking people have no spine!
LESTER BANGS Their art never lasts!
LESTER BANGS They get the girls, but we're smarter.
WILLIAM I can really see that now.
LESTER BANGS Yeah, great art is about conflict and pain and guilt and longing and love disguised as sex, and sex disguised as love...
LESTER BANGS and let's face it, you got a big head start.
WILLIAM I'm glad you were home.
LESTER BANGS I'm always home!
LESTER BANGS I'm uncool!
WILLIAM Me too!
LESTER BANGS The only true currency in this bankrupt world if what we share with someone else when we're uncool.
WILLIAM I feel better
LESTER My advice to you.
LESTER I know you think those guys are your friends.
LESTER You want to be a true friend to them?
William takes a deep breath.
Looks at the research cassettes and notebooks.
The empty page.
LESTER BANGS Be honest and unmerciful.
LESTER BANGS You're doing great.
LESTER BANGS Call me later is you want.
LESTER BANGS I'm always up.
Ben Fong-Torres and David Felton look at William's new manuscript with great interest.
FELTON Read me the opening line.
BEN "I am flying high over Tupelo, Mississippi, with America's hottest band, and we are all about to die."
FELTON Mmmmm.
FELTON Dark.
FELTON Lively.
BEN Yeah, and it gets better.
BEN Did this all really happen?
William sleeps restlessly nearby, mouth agape, sitting upright in a plastic chair.
FACT CHECKER Give it to me.
FACT CHECKER I'll call and check the quotes.
The band rides in a new tour bus.
The palpable tone in the air is -- PANIC.
JEFF Look.
JEFF Let's just piece together our information...
JEFF because the fact-checker asked us all about different parts of the story.
TONY What did he write about?
TONY What's he using?
JEFF It.
JEFF All.
JEFF He's using it all.
RUSSELL So what?
JEFF So what?
JEFF We come off like amateurs...
JEFF some average band...
JEFF trying to come to grips, jealous and fighting and breaking up - we're buffoons!
RUSSELL Maybe we just don't see ourselves the way we really are.
JEFF He was supposed to be our friend.
RUSSELL I told him to write what he wanted.
All eyes look to Russell.
TONY By the way, he has you on acid, screaming "I Am A Golden God" from a fan's rooftop.
RUSSELL Oh my God.
JEFF They used him to fuck us.
RUSSELL I didn't say "Golden God."
RUSSELL Or did I?
DICK We never took him seriously, and now it's serious.
RUSSELL I liked him as a person.
JEFF He was never a "person!" He was a journalist!
Russell nods.
He looks at Silent Ed, drumming soundlessly on a rubber pad.
RUSSELL You.
RUSSELL You had the right idea all along.
Ed silently nods thanks.
DENNIS HOPE How about the plane flight?
DICK It's all in there.
DICK But don't worry, it's all unspecific who say what.
DICK No names are mentioned in the more embarrassing sequences, it's just completely obvious who's who!
DICK We're fucked!
Silence.
RUSSELL I forgot he was there.
DENNIS HOPE Well, they haven't talked to Russell - he can always deny the key stuff to the fact checker.
DENNIS HOPE Then they can't print it.
JEFF Is that true?
DENNIS HOPE It's war, my friend.
DENNIS HOPE If you'd met me earlier, he would have never been on the around.
Dennis hands Russell the phone.
DENNIS HOPE (cont'd) He'll live.
William is still being congratulated by his new peers.
We see him woozy but beaming, as Allison the Fact Checker comes out of her office, waving the manuscript.
She works her way through the cluster of editors.
FACT CHECKER The band just denied 90% of the story.
FACT CHECKER It's a fabrication.
Everyone looks at William, who is speechless and confused.
Their congratulations stop on a dime.
The fact checker can't resist twisting the knife a little.
FACT CHECKER (cont'd) You weren't honest.
FACT CHECKER (cont'd) And worse, you wasted our time.
WILLIAM Did you talk to Russell?
FACT CHECKER Russell Hammond is the one who denied it.
BEN Crazy.
FACT CHECKER We're going with the Who - !
The kid has been sandbagged.
The machine of a big-time magazine whirs into action on another story, as the cluster moves down the hall.
SOMEONE'S VOICE He's just some fan...
SOMEONE'S VOICE what did you expect?
William sits there, as only David Felton stay behind, brandishing his cigarette-holder.
He sits down next to the kid.
FELTON Well, I believe you.
He looks at the kid, decides to offer a personal parable.
FELTON (cont'd) Jim Morrison once came to my house and drank a beer.
FELTON (cont'd) The beer is still on my mantle.
FELTON (cont'd) I'm 35 years old with Jim Morrison's beer as a shrine.
FELTON (cont'd) I wanted to be Earnest Hemingway.
FELTON (cont'd) Instead.
FELTON (cont'd) I have Jim Morrison's beer.
FELTON (cont'd) If you didn't make your story up, good for you.
FELTON (cont'd) If you did make it up...
FELTON (cont'd) good for you.
The kid looks at him, too tired and still in shock.
FELTON (cont'd) Say something, so I know you're alive.
WILLIAM Goodbye.
He exits.
FELTON Powerful word.
FELTON Strong.
FELTON Final.
Russell Hammond sits down on a plastic chair with a paper-plate filled with buffet-style food - steak and baked potato.
Preoccupied, and several seats away from other crew members.
He drinks a glass of milk.
Out old friend Sapphire takes the seat next to him, holding a skimpy paper plate of vegetables.
RUSSELL I feel bad.
SAPPHIRE Well, at least you feel.
SAPPHIRE That puts you in a higher class of asshole.
They eat in silence.
Sapphire looks around.
The new breed of groupies eye her, as they cruise Russell on the periphery.
They're bolder, flashier.
She eyes them back with seniority.
RUSSELL What did I do?
SAPPHIRE Well - you can do what the big boys do.
SAPPHIRE Nothing.
RUSSELL Yeah.
The girls still circle Russell nearby.
He's unaware.
SAPPHIRE You believe these new girls?
SAPPHIRE None of 'em take birth control, and they eat all the steak.
She looks sadly at her plate of vegetables.
An ever-sharp mind in last night's clothes, she commands Russell's respect.
SAPPHIRE (cont'd) They don't even know what it id to be a fan!
SAPPHIRE (cont'd) To blindly love some silly piece of music...
SAPPHIRE (cont'd) or some band so much that it hurts...
SAPPHIRE (cont'd) please, they're all just after the money.
SAPPHIRE (cont'd) Shoo --
SAPPHIRE (cont'd) Go rob a bank!
SAPPHIRE (cont'd) It's more honest!
RUSSELL Is Penny okay?
SAPPHIRE The Quaalude Incident.
SAPPHIRE Yeah, it wasn't pretty.
SAPPHIRE She could have died.
SAPPHIRE I always warned her about letting too many guys fall in love with her.
SAPPHIRE I guess I was wrong.
SAPPHIRE On of 'em saved her life.
Russell nods.
RUSSELL Well, it's finally over with Leslie.
RUSSELL I'm going to call her.
SAPPHIRE Let her retire.
SAPPHIRE You want to lock her up in a house in Michigan?
SAPPHIRE Please.
SAPPHIRE Write her a song someday.
SAPPHIRE She deserves it.
SAPPHIRE Something about that girl brought out the best in a lot of...
SAPPHIRE ...
SAPPHIRE pretty average people.
SAPPHIRE She deserves it...
Russell stares into his crew meal, nodding a little.
SAPPHIRE (cont'd) ...
SAPPHIRE (cont'd) because something tells me twenty years from now, we'll remember her...
SAPPHIRE (cont'd) and not much else.
Russell smiles to himself, knows it's true.
Dick passes, placing hands on Russell's shoulders, massaging a little.
DICK Have a good vacation.
DICK I hope the band stays together.
DICK Before it all went down the shitter, it was starting to get really good.
Dick claps Russell on the back, and moves on.
He turns to Sapphire.
RUSSELL I'm not going to blame myself.
RUSSELL I do make people happy.
RUSSELL They just shouldn't get to know me...
RUSSELL 'cause it appears to spoil everything.
SAPPHIRE Don't be so easy on yourself.
RUSSELL What gives you the right to get this personal with me.
SAPPHIRE Let's not reminisce.
William moves like a zombie through the airport, and collapses in a seat.
He sits still in the crowded flow of human traffic.
A cluster of Flight Attendants pass.
One stops, a stylish young woman wearing a tall bubble-shaped PSA hat with swirling colors.
ANITA William?
He looks at her.
He feels like he's on Mars, and she looks like a Martian.
ANITA (cont'd) You guys this is my brother!
MALE FLIGHT ATTENDANT "The Narc?!"
William looks woefully at them, like a dog who's been hit by a car.
ANITA You guys, I'll deadhead back later.
ANITA I think I'm needed.
MALE FLIGHT ATTENDANT Nice to finally meet you.
FEMALE ATTENDANT You have a good day!
Anita looks in her brother's face.
ANITA You look awful, but that's great.
ANITA You're living your life!
ANITA You're finally free of...
ANITA her.
WILLIAM Yeah.
ANITA Hey.
ANITA I'll take off work.
ANITA Let's have an adventure together.
ANITA You and me, finally.
ANITA Anywhere you want to go.
ANITA Anywhere in the world.
William whistles the family whistle.
Sister and brother trudge up the steps.
ANITA This is not my idea of a good time.
WILLIAM Just get me to my bed.
ANITA I'll deal with her.
William whistles again.
Mom meets them at the door.
She looks at her trashed son who has finally come home.
For the first time, she hugs Anita first, and it's not lost on Anita.
It's a clumsy neck-hug, neither wanting to commit.
The kid passes to his Mother's left, with suitcase, intentionally nudging her into his sister.
Anita takes this as an aggressive act of love, and hugs her mother back.
Tears stream down Mom's face.
Their cheeks touch.
Mom pulls away, and sees her own tears on Anita's face.
Thinking that she's also crying, she grabs a tissue for them both.
The kid stands in the hallway listening, shaking his head, poised to enter his room, unseen by them.
ANITA What are we going to do about him?
ELAINE I don't know.
ELAINE Whatever happened to him, I just wish it could have happened to me.
ANITA The magazine killed his story.
Now they really hug, Anita gulping back real tears.
William watches them bonding over the oddest thing - his failure.
William goes into the bedroom, the final three feet to sleep, and shuts the door.
A hand places a hotel sign on the door - DO NOT DISTURB.
Slight push in.
He collapses with all his clothes on, almost instantly asleep.
His walls, just as he left them, boast a pantheon of rock heroes...
with a very lonely Abraham Lincoln (or Atticus Finch) in the center.
The elevator doors ding open, and out walks Russell Hammond.
The Secretary has just finished answering the phone, "Straight Arrow Publishers."
She puts the caller on hold.
RUSSELL Hi, I'm Russel Hammond.
SECRETARY You're here regarding?
RUSSELL My life.
Russell stands with the editors, observing the fine portraits on the walls.
He's behind enemy lines, and he knows it.
Everything in the room fascinates him.
RUSSELL I don't care what happens.
RUSSELL I don't care if you put us on the cover.
RUSSELL But you sent us a kid and...
RUSSELL and he was a fan.
RUSSELL And we all made friends with him - absolutely, to get a good story.
RUSSELL But then we actually liked him.
RUSSELL We thought he's...
RUSSELL show us our lives in some mythic way and I guess...
RUSSELL we're not mythic.
RUSSELL We panicked.
JANN You denied most of the story.
RUSSELL Yeah, well, here's the problem with the truth.
RUSSELL It's too true -
BEN Well, we appreciate the visit.
BEN The last time an artist came here, it was Buddy Miles and he punched me.
RUSSELL I'm not punching anybody.
RUSSELL I am personally, as of 2 pm yesterday, on a voyage of self-reinvention.
RUSSELL This is about William Miller.
RUSSELL He lives with us, he lost his virginity, he saw us at our worst, appreciated our best, he saved two lives, including mine...
RUSSELL he smuggled about a half-pound of pot into Boston, and we never even told him -
Nearby, David Felton looks at another editor, raising an eyebrow.
RUSSELL (cont'd) -- we told him too much, we told him everything...
RUSSELL (cont'd) He almost died with us over Tupelo...
RUSSELL (cont'd) if the band survives him, it'll be a miracle...
RUSSELL (cont'd) but you know, he tried to keep up, and that's a journalist to me.
JANN It's too late.
JANN We're going with a different cover.
RUSSELL Thank God.
But Russell looks around at the numerous portraits if dead legendary rock stars, fixing on the one photo closest to all of them, a very vulnerable-looking Janis Joplin.
A second thought.
RUSSELL (cont'd) You tell me it's too late.
RUSSELL (cont'd) But I could go back to my hotel room and...
RUSSELL (cont'd) and O.D.
RUSSELL (cont'd) tonight and something tells me you'd find a way to put me on the cover of the next issue.
RUSSELL (cont'd) Am I right?
He looks at their faces.
They cannot disagree.
RUSSELL (cont'd) I'm learning the game.
RUSSELL (cont'd) We fucked up.
RUSSELL (cont'd) We made friends with him.
BEN Next time we'll all be more professional.
RUSSELL Maybe so.
RUSSELL But God forbid, the day comes when selling yourself is as important as the music you make.
RUSSELL You might have died at the right time, my friend.
JANN Thank you for visiting.
JANN Good luck.
RUSSELL Do what you want, but the story is true.
LONG SHOT RUSSELL at the entrance.
Raises his hand.
RUSSELL (cont'd) Good evening!
Russell stands outside, a traveling man with no where to go.
Oddly, and in a way that surprises him, the world begins to speak to him again...
little noises everywhere, turning into a music of its own.
It's a beautiful and compelling "silence."
He thrusts his hands deep in his pockets, and takes a breath of life.
His head filling again with the music of the world, he begins to walk down the street.
Very naturally, and quite randomly, he is noticed by young passersby.
They can't help it.
He looks like a star.
They can't quite figure out who it is, but it's someone, and they begin to follow him down the street.
Unbeknownst to him as he walks along, deep in thought, a small crowd begins to form...
following him.
A quiet kitchen.
Anita has been cooking.
A substantial breakfast has been placed on the table.
Sausage, orange juice...
and now Anita sets down a plate of pancakes, with syrup and butter, in front of her mother.
William watches his mother facing an old enemy - white sugar.
ANITA They're called pancakes.
ANITA Who knows when we'll be together again.
ANITA Splurge.
ANITA It's what most people call breakfast.
Mom looks at her children, and takes a breath.
ELAINE I went through your records.
ELAINE And I found a song to play for you.
She goes to the stereo and puts on a record.
The two children eye each other - what's coming next?
(Song to be chosen) The two kids eye each other again.
Self-consciously avoiding their gaze, Mom sits and toys with her breakfast.
It's a song she clearly wants them to hear.
It's a song from the heart.
They look at her, amazed.
Elaine looks up, regards her family.
Somehow they're back at this table.
They continue eating breakfast.
Bam.
A bundle of bound Rolling Stone Magazines lands on the newsstand pavement with a thud.
Someone reaches in to cut the cord, as the magazines puff up into view.
It's the new issue, with Russell Hammond on the cover.
The title: Stillwater Runs Deep.
Just another stack of magazines waiting to be places in the racks.
Music segues to Led Zeppelin's "Four Sticks."
Penny Lane's sleeping Polaroid shots of our characters, featuring a few self-portraits.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
