"EVENT HORIZON"
Screenplay by
Philip Eisner
SHOOTING DRAFT
A vast field of stars.
The gas giant Neptune slowly spins into view.
Brilliant and blue and cold against the void.
EXT. NEPTUNE - MODEL A BLACK SILHOUETTE stands out against the planet, tiny against Neptune's scale.
EXT. NEPTUNE - MODEL DRIFT CLOSER to discern the hard angles of a man-made craft.
A ship.
No longer dwarfed by the planet, the scale of the vessel emerges: a vast labyrinth of steel.
Its shadow swallows all in darkness.
Shafts of Neptune's blue light enter through windows, illuminate debris suspended in the zero-gravity environment: shards of metal and glass.
MOVE from the Corridor into:
A cockpit for three.
Neptune's blue light fills the chamber, reflects off immobile particles in the air.
Thick quartz windows look down at Neptune.
The cockpit lights are dark but for one blinking red light.
An emergency beacon.
Under-floor lights go on.
The strobe of the red light reveals a man floating at the helm, slowly spinning.
He is dead, perfectly preserved in the cold vacuum of space.
His eyes are empty black pits and his mouth hangs open in a scream: DR.
WILLIAM WEIR.
Weir opens his eyes, waking from dream.
Sweat beads his ascetic, etched face.
Many years a scientist.
He turns on the bedside lamp, revealing a couple's apartment.
Decorated by a woman, but Weir is alone, unless you count photographs.
His nightstand looks like a shrine to a beautiful woman.
Weir reaches to the stand.
Picks up...
The woman appears thin and haggard and wears a small brave smile.
Weir lies back on the bed.
Looks at the photo.
Presses it to his forehead and closes his eyes.
Trying to be with her, just one more time.
WEIR I miss you.
Weir stands in front of the bathroom mirror, shaving with a straight-razor.
The mirror reveals the bathtub just behind him.
DRIP, DRIP, DRIP...
Weir turns to stare at the bathtub.
Water wells up at the mouth of the tub's faucet, grows impossibly large, falls...
Weir turns back to his shaving.
Weir stands in the kitchenette, staring at the microwave as it cooks his breakfast.
Weir stands before his window, chewing his oatmeal mechanically, forcing himself to swallow.
He reaches out to open the blinds...
INT. STUDIO APARTMENT REVERSE ANGLE as the blinds pull aside, revealing Weir, upside-down.
Weir's window is just one of many in a space station, a delicate combination of cylindrical habitats and solar panels.
The structure hangs above the Earth in low orbit.
A videophone RINGS OS...
WEIR (V.O.) This is Weir.
LYLE (V.O.) Dr. Weir, Admiral Hollis would like to see you as soon as possible.
A military office, United States Aerospace Command seal blazoned on the door.
Views of the Earth.
Admiral HOLLIS sits behind his desk, a gruff career officer and a good man.
Weir enters, escorted by Hollis' adjutant, LYLE.
WEIR You wanted to see me, Admiral?
HOLLIS I apologize for the short notice, Bill, but we've had something come up that requires your immediate attention.
HOLLIS Lyle?
Lyle activates a holographic display of the solar system.
A box magnifies the eighth planet, Neptune, revealing a flashing red dot in its orbit.
LYLE At oh-three-hundred this morning, TDRSS picked up an automated navigation beacon broadcasting at two minute intervals in Neptune orbit.
Lyle hands Weir a stack of hardcopy data.
Weir reads the data with growing excitement.
WEIR Incredible...
WEIR These are the same coordinates before the ship disappeared...
WEIR this, this happened?
WEIR This isn't some kind of hoax?
HOLLIS I wouldn't bring you here on a hoax.
HOLLIS Houston confirms the telemetry and I.D.
HOLLIS codes.
WEIR It's the Event Horizon.
WEIR She's come back.
Hollis answers drily.
HOLLIS That ship was lost in deep space, seven years ago.
HOLLIS If the Titanic sailed into New York harbor, I'd find it more plausible.
HOLLIS Houston wants Aerospace to send out a search and rescue team, investigate the source of the transmission.
HOLLIS If it really is the Event Horizon, they'll attempt a salvage.
HOLLIS We need you to prepare a detailed briefing on the ship's systems for the salvage crew...
WEIR A written briefing can't possibly anticipate the variables on a mission like this.
WEIR I have to go with them.
Lyle looks at Weir, stunned by the request.
LYLE Dr. Weir, you have no experience with salvage procedures.
WEIR I designed the ship's propulsion system.
WEIR I am the only person capable of evaluating the performance of the gravity drive.
WEIR You can't send a Search and Rescue team out there alone and expect them to succeed.
WEIR That would be like...
WEIR like sending an auto- mechanic to work on the shuttle.
LYLE I can understand your desire to redeem your reputation, Dr. Weir, but it doesn't factor into this.
WEIR This is not about my reputation!
WEIR This is not about me at all!
WEIR The Event Horizon was created for one reason: to go faster than light.
WEIR Imagine mankind exploring new solar systems, colonizing new worlds.
WEIR Seven years ago, we didn't just lose the ship and the crew.
WEIR We lost the dream.
WEIR I have to go.
HOLLIS It's not that simple.
HOLLIS Lyle, play the recording for Dr.
HOLLIS Weir.
LYLE Navigation Control tried to hail the vessel.
LYLE This was the only response.
Lyle presses a button on Hollis' desk.
An unholy GARBLE rips from office speakers: STATIC and NOISE and INHUMAN VOICES.
Alone, each sound would raise the hair on your neck.
Together, they are unbearable.
The sound mercifully cuts off to STATIC.
Lyle stops the tape.
Weir sits there, stunned.
LYLE Since the initial transmission, there's been no further contact.
LYLE Just the beacon, every two minutes.
WEIR The crew?
WEIR Could they still be alive?
LYLE The ship had life support systems for eighteen months.
LYLE They're been gone seven years.
WEIR Someone sent that message.
WEIR Admiral, you have to put me on that ship.
Hollis stares at Weir, judging the man with his eyes.
HOLLIS It's against my better judgement, but I'll run this by the Man downstairs.
HOLLIS You'll know my decision by the end of the day.
WEIR Thank you.
HOLLIS Don't thank me, Bill.
HOLLIS I'm not doing you any favors.
Weir leaves.
The door closes behind him.
LYLE You're not seriously considering sending him?
HOLLIS You don't just dismiss Bill Weir.
HOLLIS The man held Oppenheimer's chair at Princeton.
HOLLIS If the Event Horizon had worked, he would have gone down in history as the greatest mind in physics since Einstein.
LYLE The official inquiry blamed Weir's design for the ship's loss.
HOLLIS That doesn't mean a damn thing.
HOLLIS They were looking for a scapegoat and Weir fit the bill.
HOLLIS But he's not responsible for what happened to the ship.
LYLE Does he know that?
HOLLIS What's on your mind?
LYLE He doesn't belong on this mission.
LYLE Responsible or not, he blames himself.
LYLE He's too close to it.
LYLE And then there's his wife.
HOLLIS It's been two years since she died.
HOLLIS He's over it.
LYLE Some things you don't get over.
Beat.
HOLLIS I want our best people on this.
HOLLIS Where's Miller?
LYLE The Lewis and Clark just returned from patrol in the asteroid belt, she's docked in bay four.
The Lewis and Clark pulls away from Daylight station, turns towards the depths of space.
It is a tough-looking spacecraft, all engine.
Sequence omitted from original script.
MOVE IN on thick quartz windows near the ship's nose: the bridge...
Split level.
Above: avionics, navigation, flight control.
STARCK (female, Navigator, sharp mind, sharp tongue) checks the navigation data on her screen as SMITH (male, Pilot, wrapped too tight) punches in the course.
SMITH I can't believe this, I haven't gotten more than my hand in six weeks and now this shit.
SMITH Why not Mars, Cap, Mars has women...
STARCK Smith's right.
STARCK Neptune?
STARCK There's nothing out there.
STARCK If something happens, we'll be on our own.
The captain's chair drops from above, swivels to reveal MILLER (male, Captain, intense).
MILLER I don't like it either, but you know the rules: we get the call, we go.
MILLER Is the course locked in?
SMITH Locked and cocked.
STARCK We're past the outer marker, we can engage the ion drive whenever you're ready.
MILLER Justin?
Below: the bridge's "war-room" -- ship's systems and mission stations.
JUSTIN (male, Engineer, young hot-shot).
JUSTIN Everything green on my boards, Skipper.
MILLER Start the countdown.
STARCK Ion drive will engage in...
STARCK T-minus ten minutes.
MILLER Let's go.
Miller slides down a ladder into the war-room.
The others follow into...
Bulky EVA (extra-vehicular activity) suits line the walls.
MUSIC blares from a JAMBOX, built into a storage locker.
An Emergency Tech stows safety lines: COOPER -- male, the resident pain-in-the-ass.
He SINGS along with the music.
MILLER Kill it.
Cooper reaches up, turns off the box.
COOPER Time to play Spam in the can.
MILLER Don't start with me, Cooper.
Cooper falls in as the crew continues into...
Evidence of long term habitation.
Personalized lockers.
Fold- down bunks, chairs, tables; currently stowed for docking.
A modular galley.
PETERS (female, Emergency Technician, the crew's denmother) and DJ (male, Doctor, a cold perfectionist) load CO2 scrubbers into a bin in the floor.
Weir stands to the side like a fifth wheel.
WEIR Captain Miller, I just want to say...
MILLER The clock is running, Dr. Weir.
MILLER If you'll follow the rest of the crew, they'll show you to the gravity tanks.
Weir hesitates, then follows the crew into Medical.
Miller hangs back.
MILLER What's the hold up?
PETERS Just loading the last of the CO2 scrubbers.
PETERS Good for four months.
MILLER I put in for a replacement for you but no one...
PETERS No, no, its alright.
PETERS I talked to my ex, he'll keep Denny over Christmas and I'll get him this summer.
PETERS Goddam it, Skipper...
PETERS I haven't seen him in two months.
MILLER I am sorry.
MILLER But now we have to go to work.
A high tech operating room.
Modular equipment.
Vertical tanks line the walls, each large enough to hold a human being: gravity couches.
The crew stands before the gravity couches, almost nude, no room for modesty.
Starck catches Cooper looking at her ass as she strips to her undergarments.
Cooper grins.
She flips him off, not bothering to turn around.
COOPER Is that an offer?
STARCK It is not.
Miller disrobes.
Two service tags hang around his neck.
He does not remove them.
Weir approaches him.
WEIR Captain Miller, I appreciate this opportunity...
MILLER Doctor Weir, my crew is not going on your mission because we want to.
MILLER We were pulled off a well deserved leave, to be sent out to the middle of nowhere, and no one's even told us why.
WEIR I've been authorized to brief you and the crew once we reach Neptune space.
MILLER Until then, do what you're told and stay out of my way.
Weir nods, moves to an empty couch bearing his name, written on a piece of tape.
Peters watches him.
PETERS First time in a grav couch?
WEIR Yes.
She checks Weir's couch, helps him climb in.
Weir keeps one eye on Miller.
PETERS Don't worry about it.
PETERS He's hard, but he's fair.
PETERS You're lucky to be shipping out with him.
PETERS He's one of the few Captains in the service with experience in the Outer Reach.
WEIR He's been past Mars?
PETERS He served on the Goliath.
WEIR Wasn't that ship destroyed?
PETERS They attempted to rescue a supply shuttle bound for Titan.
PETERS The shuttle's oh-two tanks ruptured during the rescue, flooded both ships with pure oxygen.
PETERS There was a spark and both ships were incinerated.
PETERS The Skipper and three others just made it to a lifeboat.
PETERS Captain Miller was able...
DJ He doesn't like to talk about it.
DJ swathes one of Weir's arms with alcohol.
DJ You didn't eat anything in the past twelve hours?
Weir shakes his head.
DJ When the Ion drive fires, we'll be taking about 30 gees.
DJ Without a tank, the force would liquefy your skeleton.
DJ injects Weir.
The scientist winces.
WEIR I've seen the effect on mice.
The overhead lights change to red.
MILLER Five minutes.
DJ hands him the breathing mask.
DJ Put this on.
Weir does.
DJ checks the fit.
PETERS You'll be fine.
PETERS You'll wake up and we'll be there.
PETERS Watch your fingers.
DJ closes the tank.
It begins to fill with green gel.
Weir's eyes grow large with fear and then the anaesthesia hits.
His eyes close.
His body draws into a fetal position.
DJ Heart-rate decreasing...
DJ body temp dropping to 80...
DJ 70...
DJ 60...
DJ 50...
DJ 40 degrees Fahrenheit.
DJ He's in stasis.
THE ION ENGINE at the aft of the ship begins to glow a deep red.
The crew hang inert in the gravity couches.
SILENCE.
The engine flares white hot.
The Lewis and Clark lances forward.
The Lewis and Clark races SILENTLY past.
The engine at its aft holds a sustained fusion reaction like the sun.
GRAPHIC: U.S.S. Lewis and Clark.
56 days out.
INT. LEWIS AND CLARK - MEDICAL CLOSE ON WEIR immobile in the grav tank.
He might be sleeping.
He might be dead.
A distant SOUND echoes though the ship, the unholy garble of human and inhuman voices -- it is the Event Horizon, calling to him -- the sound refines into a WOMAN'S VOICE, no more than a WHISPER:
VOICE Billy...
Weir opens his eyes.
VOICE I'm so cold...
Weir's grav tank opens.
WIDER TO REVEAL the seven bodies of the crew, suspended inert in the gel.
A sound: DRIP...
DRIP...
DRIP...
Weir slowly walks to the Bridge.
VOICE I'm so cold...
A naked WOMAN sits at the helm, her back to us.
Completely still.
Her skin is very pale.
Water pools around her chair.
Weir stands behind her.
WEIR Claire?
She does not answer.
She does not move.
Weir reaches out to touch her shoulder, then pulls his hand back, afraid.
WEIR Claire?
WEIR I'm sorry.
WEIR Claire?
He reaches out again.
He touches her hair.
She doesn't move.
Weir catches her reflection in the computer monitors.
Something wrong with her face...
He starts to spin her around.
CLAIRE I'm so cold...
Weir awakes with a jolt, in his grav couch.
His mask has slipped.
His tank has filled with blood.
He is drowning.
Reality.
Weir's eyes open.
He presses against the glass of the tank, trying to force it open, panicked.
The others are already stepping from open tanks.
Weir's tank opens with a HISS.
He tumbles to the floor, gasping, fluid streaming from his mouth.
Peters rushes to him.
WEIR Claire...
DJ! It's okay.
DJ! You're okay.
DJ! Just breathe.
Weir catches his breath.
He looks up.
The crew surrounds him, concerned.
WEIR I'm alright now.
WEIR I'm alright...
DJ helps him to his feet.
DJ Move slowly.
DJ You've been in stasis for fifty-six days.
DJ You're going to experience a little disorientation.
Weir nods.
COOPER Damn, Dr. Weir, don't scare us like that.
COOPER Coffee?
WEIR What?
COOPER Coffee.
WEIR No, thank you.
Cooper, still butt-naked and proud of it, grabs a metal cylinder from the wall and pours a mug for himself.
COOPER Hey, Starck.
COOPER You wanna dry my back?
Starck gives him a cool once over.
STARCK Maybe when you finish puberty.
Miller zips up.
MILLER Starck, why aren't you on the bridge?
STARCK I just finished drying...
MILLER Then what are you doing here?
MILLER Come on, people, let's go!
MILLER And Cooper...
MILLER Put some pants on.
SILENCE.
The Lewis and Clark drifts towards Neptune.
The crew has secured the quarters from flight status.
Bunks have been folded down, each alcove personalized with photographs and pin-ups.
DJ moves around the cabin, checking the crew's radiation badges.
Cooper and Justin sit on their bunks, tossing a handball across the cabin.
Peters holds a "Watchman" video unit, watching a "video letter"...
...from DENNY, her four-year-old son, a paraplegic, grinning widely in his new wheelchair:
DENNY Play horsey, Mommy, play horsey...
IN THE VIDEO, Peters enters shot, scoops her child from the chair.
PETERS Want to play horsey, do you...
Weir sits huddled in a blanket.
Miller takes a seat next to him.
Starck and Smith enter.
Starck sits next to Miller.
SMITH 30 hours to Neptune orbit.
STARCK All boards are green, everything's five by five.
MILLER That's good to know.
MILLER Justin, you wanna stow that?
Justin catches the ball, holds onto it.
MILLER Okay, listen up.
MILLER As you all know by now, we have an addition to our crew.
MILLER Dr. Weir, this is: Starck, navigation; Smith, pilot, Justin, ship's engineer --
COOPER You can call him Baby-bear, he loves that...
MILLER This is Cooper, what the hell do you do on this ship, anyway?
JUSTIN Ballast.
COOPER I am your best friend.
COOPER I am a lifesaver and a heartbreaker...
MILLER He's a rescue technician.
MILLER Peters, medical technician.
MILLER DJ...
DJ Trauma.
MILLER And this is mission specialist Dr.
MILLER William Weir.
MILLER We all know where we're going.
MILLER Dr. Weir is going to tell us why.
Miller and the crew look at Weir, waiting.
Weir clears his throat.
WEIR What I am about to tell you is considered code-black by the NSA.
The crew look at each other: they haven't heard that in a mission briefing before.
JUSTIN That means top-secret, Cooper.
COOPER I heard it.
WEIR The USAC intercepted a radio transmission from a decaying orbit around Neptune.
WEIR The source has been identified as the Event Horizon.
STUNNED SILENCE.
Then everyone talks at once:
STARCK That's impossible!
STARCK She was lost with all hands, what, seven...
JUSTIN Seven years ago, the reactor blew...
PETERS How can we salvage...?
SMITH Let the dead rest, man...
COOPER ...cancel our leave and send us out on some bullshit mission...!
MILLER EVERYBODY SHUT UP!
MILLER Let the man speak.
In the quiet that follows:
WEIR What was made public about the Event Horizon, that she was a deep space research vessel, that its reactor went critical, that the ship blew up...
WEIR None of that is true.
WEIR The Event Horizon was the culmination of a secret government project to create a spacecraft capable of faster- than-light flight.
The crew stares at Weir: he has just dropped another bomb on them.
SMITH You can't do that.
STARCK The law of relativity prohibits faster- than-light travel...
WEIR Relativity, yes.
WEIR We can't break the law of relativity, but we can go around it.
WEIR The ship doesn't really move faster than the speed of light; it creates a dimensional gateway that allows the ship to instantaneously "jump" from one point in the universe to another, light years away.
STARCK How?
WEIR Well, in layman's terms, you use a rotating magnetic field to focus a narrow beam of gravitons; these in turn fold space-time consistent with Weyl tensor dynamics until the space- time curvature becomes infinitely large and you have a singularity...
COOPER Laymen's terms.
Weir thinks of another way to explain it.
He rips a pin-up from Smith's locker.
SMITH Hey...
WEIR Say this paper represents space-time, and you want to get from "point A" here...
WEIR ...to "point B," here.
WEIR Now: what's the shortest distance between two points?
The crew stares at him.
Starck decides to play.
STARCK A straight line.
WEIR Wrong.
WEIR The shortest distance between two points...
Weir folds the paper, lining up point A over point B...
then THRUSTING his pen through both, skewering the pin-up.
WEIR ...is zero.
WEIR That's what the singularity does: it folds space, so that point A and point B coexist in the same space and time.
WEIR After the ship passes through this gateway, space returns to normal.
WEIR It's called a gravity drive.
JUSTIN How do you know all this?
WEIR I built it.
Even Cooper is impressed.
COOPER I can see why they sent you along.
JUSTIN So if the ship didn't blow up, what happened?
WEIR It was the ship's maiden voyage, to test the drive.
WEIR The Event Horizon moved to safe distance using ion thrusters.
WEIR They received the go-ahead to activate the gravity drive.
WEIR And the ship vanished from all our scopes.
WEIR No radar contact, no enhanced optical, no radio contact of any kind.
WEIR They disappeared without a trace.
WEIR Until now.
MILLER Where has it been for the last seven years?
WEIR That's what we're here to find out.
The Lewis and Clark flashes silently past, heading deeper and deeper into space.
The crew assembled.
WEIR We haven't been able to confirm any live contact, but TDRSS did receive a single transmission from the Event Horizon.
Weir punches a button on a console.
The transmission BLARES from the bridge's speakers, STATIC and NOISE and, underneath all, INHUMAN VOICES.
The crew listen, look at one another.
The recording ends abruptly.
SMITH What the hell is that?
PETERS It doesn't sound like anything human.
WEIR Houston has passed the recording through several filters and isolated what appears to be a human voice.
He activates a different file.
The resulting WAIL is more human but no less terrifying, a cry of despair.
The last message from a drowning man...
SMITH Jesus...
MILLER What is that?
DJ It sounds like Latin.
COOPER Latin?
COOPER Who the fuck speaks Latin?
STARCK No one.
STARCK It's a dead language.
DJ Mostly dead.
MILLER What does it say?
WEIR NSA encryption specialists have deciphered some of the message...
Weir plays the HELLISH INCANTATION for a third time.
WEIR There: "...liberatis me..."
WEIR They haven't been able to translate the rest, it's too distorted.
DJ "Liberatis me."
DJ "Save me."
COOPER From what?
MILLER You're convinced the crew could still be alive?
MILLER After seven years?
WEIR The Event Horizon only had life support for eighteen months.
WEIR It seems impossible, but in light of the transmission...
WEIR I have to think that someone has managed to endure until now.
COOPER Skipper, do we get hazard pay for this?
MILLER You heard the tape, Smith.
MILLER We're looking for survivors.
The Lewis and Clark closes in on the blue planet.
The flight crew assembled.
Data flashes across the main monitors on the bridge.
STARCK Crossing the horizon.
STARCK Optimum approach angle is fourteen degrees.
MILLER Come around to three-three-four...
SMITH Heading three-three-four...
MILLER ...Make your approach vector negative fourteen degrees...
SMITH One-four degrees...
RCS thrusters pivot and fire as the ship enters Neptune orbit, dropping lower and lower into the dense blue clouds...
The ship begins to rock as it encounters atmosphere, a growing vibration.
GRAPHICS flash across the main window's HUD.
Neptune's dark shadow fills the screen.
SMITH We have a lock on the Event Horizon's navigation beacon.
SMITH It's in the upper ionosphere, we're in for some chop.
MILLER Bring us in tight.
MILLER Starck, get on the horn, see if anyone's listening...
STARCK This is U.S. Aerospace Command vessel Lewis and Clark, hailing Event Horizon, Event Horizon, do you read...?
STARCK This is the Lewis and Clark, hailing...
SMITH Matching speed...
SMITH now.
SMITH Range to target ten thousand meters and closing...
SMITH Skipper, I got a bad feeling about this...
MILLER We're all on edge, Smith.
MILLER We're a long way out...
SMITH That's not it.
SMITH That ship was built to go faster than light...
SMITH That's just wrong, it goes against everything we know...
MILLER What are you trying to say?
MILLER "If God had intended Man to fly, he would have given us wings?"
SMITH Something like that, yeah.
Miller grins grimly.
MILLER I guess we're about to find out.
MILLER Keep us slow and steady.
SMITH Yes, sir.
MILLER Dr. Weir...!
Weir sticks his head into the bridge.
MILLER I think you want to see this.
Weir climbs up the ladder to the flight deck.
WEIR Where is she?
SMITH Dead ahead, 5000 meters.
Suddenly, the ship SHUDDERS VIOLENTLY.
Weir braces himself in the doorway, staring out the forward window into the roiling azure clouds.
Smith grimaces, his knuckles white at the controls.
SMITH We've got some weather.
MILLER I noticed.
MILLER Starck, anybody home?
STARCK If they are, they're screening their calls.
SMITH Range 3000 meters and closing.
WEIR I can't see anything...
Only turbid clouds of methane ice whirl past the Lewis and Clark's windows.
SMITH 1500 meters.
SMITH We're getting too close...
MILLER Where is it?
STARCK The scope is lit, it's right in front of us...
SMITH 1000 meters...
A red warning light begins to flash in time with a shrill
SMITH Proximity warning!
SMITH 900, 800 meters, 700...
SMITH we're right on top of it, we're gonna hit!
MILLER Starck...
STARCK It should be right there...
She looks up, trails off...
STARCK My God.
...the clouds break, revealing...
THE EVENT HORIZON, right in front of them.
A black labyrinthine blasphemy against Neptune's arctic blue.
Cloud banks encircle the ship as if it were the eye of a hurricane.
MILLER Reverse thrusters full!
The Event Horizon looms enormous as the Lewis and Clark hangs off the port stern, dwarfed by the giant ship.
The turbulence subsides.
The bridge crew stares at the massive craft.
The only sound, the PROXIMITY WARNING.
Finally:
SMITH Jesus, that is one big ugly fat fucker...
WEIR She's not ugly.
Miller reaches over Smith's shoulder, turns off the proximity warning.
Smith snaps back to business.
SMITH Range 500 meters and holding.
SMITH Turbulence is dropping off...
STARCK Picking up magnetic interference.
MILLER Put it through TACS.
MILLER Smith, you up for a flyby?
SMITH Love to.
The Lewis and Clark maneuvers in close to the Event Horizon, dwarfed by the dark ship.
Smith keeps a tight hand on the controls.
The crew stare out the viewport at the abandoned craft.
STARCK Look at the size of that thing.
Weir explains the view out the cockpit window.
WEIR Foredecks.
WEIR Crew quarters, bridge, medical and science labs, hydroponics, what have you.
WEIR That central section connects the forward decks to the Engineering containment area.
WEIR Can we move in closer?
SMITH Shit, Doc, any closer and we're gonna need a rubber...
MILLER Do it.
Smith grimaces.
His hands move carefully over the controls.
The Lewis and Clark moves even closer.
Vanishing into the shadow of the Event Horizon.
The crew stares at the ship rushing past the viewport.
A huge spherical structure looms eerily ahead.
WEIR That's the engineering containment.
WEIR And there's the main airlock.
WEIR We can dock there.
MILLER Smith, use the arm and lock us onto that antennae cluster.
WEIR Be careful.
WEIR It's not a load bearing structure...
The Lewis and Clark carefully maneuvers in close to the Event Horizon's airlock.
A mechanical boom-arm extends from the smaller ship to latch onto the Event Horizon.
Its clawed hand grabs the antennae cluster.
The cluster buckles under the stress.
SMITH It is now.
SMITH We're locked in.
MILLER Starck, give me a read.
A scan of the Event Horizon appears across Starck's screen.
STARCK The reactor's still hot.
STARCK We've got several small radiation sources, leaks probably.
STARCK Nothing serious.
WEIR Do they have pressure?
STARCK Affirmative.
STARCK The hull's intact...
STARCK but there's no gravity and the thermal units are off line.
STARCK I'm showing deep cold.
STARCK The crew couldn't survive unless they were in stasis.
MILLER Find 'em, Starck.
Starck frowns at her display.
STARCK Something's wrong with the bio-scan.
MILLER Radiation interference?
STARCK There's not enough radiation to throw off the scan.
STARCK I'm picking up trace life forms, but I can't get a lock on the location.
WEIR Could it be the crew?
WEIR If they were in suspended animation, wouldn't that effect the scan?
STARCK If they were in stasis, I'd get a location, but these readings, they're all over the ship.
STARCK It doesn't make any sense.
MILLER Okay.
MILLER We do it the hard way.
MILLER Deck by deck, room by room.
MILLER Starck, deploy the umbilicus.
MILLER I believe you're up for a walk, Mr. Justin.
MILLER Go get your bonnet on.
JUSTIN Yes, sir!
Weir starts to follow Justin from the bridge.
MILLER Dr. Weir, I need you on the bridge.
WEIR Captain, I didn't come out here to sit on your bridge, I need to be on that ship...
MILLER Once the ship is secured, we'll bring you on board --
WEIR That is not acceptable --
MILLER -- once we've secured the ship, that's the way it is!
MILLER I need you to guide us from the comm station.
MILLER This is where I need you.
MILLER Help us to do our job.
Weir exhales.
WEIR Very well.
The docking collar umbilicus extends to the Event Horizon's airlock.
Miller, Peters, Justin and Cooper in EVA; Cooper and Justin, without headgear.
COOPER ...come on, Skipper, I already put my shoes on...
MILLER You've had plenty EVA, Coop, it's Justin's turn.
MILLER Stay on station.
MILLER If anything happens...
COOPER I'll be all over it.
Miller nods to Peters.
PETERS Opening inner airlock door.
The inner airlock door opens: CH-THUNK.
Miller, Peters and Justin enter the airlock.
Justin attaches his safety line.
Miller and Peters do not.
COOPER You still need the rope?
COOPER I thought you were one a those spacemen with ice in ya veins.
JUSTIN I'd rather be on the rope and not need it than need it and not have it.
JUSTIN Now step aside, old man.
Cooper puts Justin's helmet on.
It seals tight.
COOPER You just keep your nose clean, Baby Bear.
COOPER Clear the door.
Cooper backs out, allowing the inner airlock door to shut, ECHOING through the ship.
Miller, Peters and Justin float down the brightly lit umbilicus into the Event Horizon, all in EVA suits.
Justin's safety line trails out behind him.
The OUTER AIRLOCK DOOR of the Event Horizon waits for them.
Weir has taken over Justin's station.
He watches the POV monitors like a kid watching Christmas.
Smith and Starck keep tabs over his shoulder.
WEIR You've reached the outer airlock door.
Peters attaches a thumper -- a device using sound waves to measure pressure -- to the inner airlock door.
PETERS We've got pressure.
MILLER Clear and open on my mark.
MILLER Three...
MILLER two...
MILLER one...
MILLER mark.
Peters inserts a zero-G drill into the panel beside the door.
The door slowly opens...
The immense corridor stretches away into darkness in both directions.
Distantly spaced windows manifest as remote pools of blue light amidst endless black, adding to the vast sense of scale.
The light from their dual spotlights on the team's helmets reflects off tiny ice crystals of frozen atmosphere.
They are ants in a tomb built for giants.
PETERS Jesus its huge.
MILLER Ice crystals everywhere.
MILLER This place is a deep freeze.
WEIR You're in the central corridor.
WEIR It connects the personnel areas to Engineering.
MILLER Peters and I will search the forward decks.
MILLER Justin, take Engineering.
MILLER No hot-dogging, not on this one, alright?
JUSTIN Not a chance, sir.
The group separates.
Justin kicks off from the wall, shoots down the corridor at immense speed.
Miller and Peters move in the opposite direction.
They use magnetic plates on their boots and gloves to cling to the walls as they slowly make their way down the dark shaft.
Their journey seems endless.
The darkness almost seems a living thing as it surrounds them.
Miller spots something at a coupling, where two sections of the corridor join...
MILLER Dr. Weir, what's this?
Miller indicates a box nestled against the coupling.
The universal symbol for explosives is on the cover.
PETERS Here's another one.
PETERS They're all over the place.
WEIR They're explosive charges.
MILLER I can see that, what're they for?
WEIR In an emergency, the charges detonate in series, destroying the central section and separating the personnel areas from the rest of the ship.
WEIR That way, if the gravity drive malfunctions, the crew could use the foredecks as a lifeboat.
Peters and Miller keep moving.
PETERS That means they didn't abandon ship.
MILLER So where are they?
MILLER Starck, any luck with the bio-scan?
STARCK I'm running diagnostics now, Skipper...
STARCK Nothing's wrong with the sensor pack, I'm still getting trace life readings, all over the ship.
Miller and Peters unconsciously look around.
Sweat beads their faces.
PETERS There's no one in the corridor but us.
STARCK Not according to the computer.
MILLER Peters is right, no one's here.
PETERS I don't know, this place is really dark, I can't see a thing...
She starts to wave her searchlight around wildly.
MILLER Easy, Peters, we're okay, we're okay.
MILLER Let's finish the sweep.
WEIR Captain Miller, the foredecks are just ahead.
PETERS I can see the hatch.
MILLER Starck, you still showing those readings?
STARCK That's an affirmative.
MILLER Keep your eyes open.
She nods as he reaches for the hatch...
The hatch opens, allowing Peters and Miller entrance into the forward decks.
These areas were intended for human habitation, and seem similar in design to the Lewis and Clark, only larger.
Gravity couches line both walls, eighteen in all.
Empty.
PETERS We found the gravity couches.
Weir peers eagerly at the monitors.
WEIR Any survivors?
MILLER Negative.
Hope drains from Weir's face.
WEIR No one?
MILLER They're empty, Dr. Weir.
MILLER Moving forward.
Miller and Peters split up, each taking a separate exit from the chamber.
Weir looks at Justin's POV screen: a grainy image of the First Containment Seal.
Justin stands before a thick pressure door.
Justin checks the door with his thumper, his boots are now on.
WEIR You've reached the First Containment Seal.
WEIR The engineering decks are on the other side.
JUSTIN We still have pressure.
JUSTIN The radiation count's steady at 7 millirads an hour.
WEIR Background radiation.
WEIR Perfectly safe.
Justin touches a panel beside the door.
It opens.
He enters...
...a long corridor shaped like a tube.
It rotates like a turbine, causing vertigo.
Justin's BREATH echoes in his helmet as he moves forward...
Cooper stares at Justin's safety line in the airlock.
THE SAFETY LINE counts off silently, passing 150 meters...
The corridor ends at a pressure door.
PETERS Dr. Weir, what's this the door to?
WEIR You're at the Bridge, Ms. Peters.
WEIR You still haven't seen any crew?
Miller, moving through a deserted lab.
Empty operating tables.
Stainless steel surgical instruments float in zero-G.
A glove floats up behind him, brushes his shoulder.
He wheels...
the glove is empty.
It spins away.
MILLER If we saw any crew, Doctor, you'd know about it.
MILLER I'm in Medical.
MILLER No casualties, it looks like this place has never been used.
He finds a computer console.
Peters opens the door.
Peters enters.
Looks around: a small antechamber for crew briefings, with chairs and a display table.
Red crystals float in a crimson mist around her.
PETERS I found something.
Weir peers at the monitors, trying to make out the red haze.
WEIR Yes, we can see some kind of mist.
WEIR What is that?
PETERS Blood.
PETERS Looks like arterial spray.
WEIR Can you see a body?
PETERS There's no one here.
MILLER The blood came from somewhere, Peters...
PETERS There's no one here, Skipper.
Peters takes a sample container from her belt.
Carefully tries to capture a suspended crystal...
PETERS Come on...
CLOSE UP OF THE BLOOD CRYSTAL and the Container; Peters' brow furrowed with concentration.
BLOOD AND TISSUE.
Someone died here in a violent and terrible way.
Peters starts to look up but the flash dies away.
She never saw the horror behind her.
Peters turns her attention back to her tiny crystal.
She traps the it, returns the container to her belt.
She moves from the antechamber into...
Her helmet lights sweep the room.
Every surface a control panel.
PETERS Okay.
PETERS I'm on the bridge.
MILLER What you got, Peters?
Peters examines the other consoles -- most are dark but for a few dim lights.
PETERS Everything's been shut down.
PETERS Conserving power, I guess.
PETERS Green light on the hull, it's intact.
MILLER The science workstation has power, I'll see if I can find the crew from here.
Weir stares at Peters' monitor.
WEIR Ms. Peters, turn back and to your left, please.
On her monitor, Peters' POV shifts as she complies.
STARCK What is it?
WEIR Ship's log.
PETERS I see it.
Peters reaches towards a small video deck.
Touches the eject button.
Nothing happens.
PETERS It's stuck.
Justin's light bounces off an even larger pressure door, built like a bank vault.
The Second Seal.
JUSTIN I've reached another containment door.
JUSTIN This thing's huge...
WEIR That's the Second Containment Seal.
WEIR Beyond that, engineering.
JUSTIN I'm going in.
Justin opens the seal.
It releases SLOWLY, inching open.
Justin squeezes through.
Peters takes a small probe from her belt, inserts it into the video deck.
A small laser disc emerges partway from the deck.
Peters pulls on it.
It doesn't move.
PETERS It's really jammed in there.
A shadow crosses the window behind her.
Someone -- something -- is in there with her...
Peters pulls harder.
Nothing.
Another effort.
The disc pulls free.
Peters spins in the zero-gravity, spinning into...
...A BODY floating at the helm, the face illuminated by Peters' helmet lights.
His swollen tongue clogs his gaping, screaming mouth.
His cracked and crystallized skin is crossed by a network of bloated veins.
He has no eyes.
Just like Weir's dream.
Peters' monitor shows the CORPSE'S face, its mouth open in mute agony.
Weir GASPS.
Peters pushes free of the body.
PETERS I found one.
MILLER Alive?
PETERS Frozen.
The dead man's face leers from Peters' monitor.
STARCK What happened to his eyes?
SMITH Explosive decompression.
STARCK Decompression wouldn't do that.
Weir just stares at the ruined face, rapt.
Starck notices.
STARCK You okay?
Weir nods, not taking his eyes from the screen.
Cooper, on station.
He keys his radio.
COOPER Hey, Baby Bear, Mama Bear got a corpsicle for ya...
No reply.
Miller looks up from the workstation, concerned.
COOPER Baby Bear, you copy?
Cooper stares out at Justin's safety line slowly counting off past 175 meters.
COOPER Justin, do you copy?
The Second Seal is open.
Justin's safety line snakes into darkness.
FOLLOW the safety line into the dark...
An alcove, opening into a vast chamber.
Once pristine, all the surfaces have been coated in a dark gray slick.
Globules of fluid hang motionless, sticking to Justin's suit, leeching away his light and swallowing him in darkness.
COOPER ...do you copy?
JUSTIN Uh, yeah Coop, I'm still here.
COOPER Shit!
COOPER Do not do that!
COOPER Where the fuck are you?
JUSTIN I'm in the Second Containment area.
JUSTIN It's pitch black in here.
JUSTIN There must have been a coolant leak.
JUSTIN Man, this shit is everywhere.
JUSTIN I can't see a damn thing.
A lighted console blocks Justin's view of the chamber beyond.
He drifts over to it, wipes the console clear of coolant, revealing dim lights: the station has power.
JUSTIN The reactor's still hot.
JUSTIN Coolant level is on reserve, but still in the green.
JUSTIN I got it...
His expressions changes as he looks past the console and sees...
something.
JUSTIN Holy shit...
COOPER Justin?
JUSTIN I think I found something...
A massive sphere, 10 meters in diameter, dominates the center of the second containment.
Intricate machinery surrounds the sphere but the globe itself is featureless, smooth; a enigmatic monolith.
Black ice encrusts it, giving it the seeming of a living thing.
They stare at Justin's monitor.
SMITH What the hell is that?
WEIR That's the Core: the gravity drive.
WEIR The heart of the ship.
MILLER Justin, check the containment for radiation leaks.
MILLER Peters...
MILLER ...how's the client?
PETERS Crystallized.
Justin examines the outer wall of the Core, looking for any cracks or ruptured seams.
MILLER Justin, finish your sweep.
JUSTIN Almost done, I just gotta check one thing...
Justin turns to the Core...
Justin's monitor fills with static.
STARCK Justin, hold on a sec, you're breaking up...
STARCK Justin...?
Justin reaches towards the Core with his pressure sensor.
His helmet light flickers.
He hesitates...
Miller's helmet light flickers...
Peter's helmet light winks out...
STARCK Justin, come in...
Suddenly, the bio-scan lights up, from green to red as signals race across the display.
WEIR What is it?
STARCK I don't know.
STARCK The life readings just went off the scale.
SMITH Something's wrong...
Justin places the pressure sensor against the Core.
Touching it.
The Core turns deepest black.
A darkness that light cannot penetrate.
For a second, Justin's white suit is captured against the hungry void...
Cooper stares in shock as Justin's safety line as it reels out at an incredible rate -- 250 meters, 300 meters...
INT. EVENT HORIZON - SECOND CONTAINMENT A WAVE surges out of the Core, bending light like a ripple on a pond, pushing coolant and debris before it...
The gravity wave surges forward, blowing out emergency lights as it comes, flotsam and jetsam swirling in its wake...
Data floods Miller's workstation, flashing across the screen too fast for comprehension...
MILLER What the hell...
A DEEP ROAR fills the ship.
Miller rises to investigate...
The door BLOWS APART as THE WAVE HITS, ripples through the Medical Bay towards Miller...
MILLER Oh shit...!
Debris swirls around him...
the wave sweeps him up...
SLAMS him into a bulkhead...
INT. LEWIS AND CLARK - BRIDGE JUSTIN'S POV SCREEN the briefest suggestion of a SCREAMING FACE, obscured by STATIC and ROLL before the screen CUTS to static entirely.
The rest of the crew's POV screens go dead as...
...the wave hits them, threatening to tear the Lewis and Clark apart.
The ship shudders violently.
Consoles EXPLODE with sparks.
Weir and the others hold on for dear life.
STARCK Miller, do you read me, Peters --
SMITH Get them back --
STARCK I'm trying, goddammit --
An equipment rack IGNITES.
Smith grabs an extinguisher, fights the blaze...
Cooper and DJ, bracing against the bulkhead.
Cooper hits the intercom.
COOPER What's happening?
STARCK I don't know, the screens are dead...!
Cooper peers out the airlock window.
JUSTIN'S SAFETY LINE passes 350 meters and accelerating...
COOPER 350 meters...
COOPER 400 meters...
DJ He's in trouble.
DJ Go!
COOPER I'm gone!
Cooper grabs his helmet.
DJ helps him lock the helmet into place with a HISS.
The inner airlock door opens.
As Cooper enters the airlock, Justin's safety reel stops, the line jerking taut at 500 meters.
Miller tries to get his bearings in the dark.
MILLER Boarding party, sound off...
MILLER Peters, do you read me...
MILLER Peters...
Peters' light, too, remains dark, but Neptune's blue light fills the Bridge.
The frozen corpse floats before her.
No longer a man.
A young boy, maybe five years old.
His legs are withered, useless things.
The skin remains a crystallized surface, but the eyes look straight at her, alive.
PETERS Denny...
Peters reaches out to touch the body.
It falls away from her.
No longer her son, but the body of the astronaut.
It hits the door and shatters.
MILLER ...Peters, do you read me...
A MAN'S VOICE, in agony, CRACKLES over Miller's radio:
VOICE Don't leave me...
MILLER Justin?
MILLER Justin, sound off...
MILLER Justin...!
Miller trails off as RED LIGHT flickers across his visor.
He turns...
A BURNING MAN stands in Medical/Science, a human body wreathed in flame.
The eyes are like sunspots.
As the Burning Man moves, bones and black flesh poke through the fire.
He raises one hand to point at Miller in accusation...
Miller's BREATH stops in his throat.
His mouth works but nothing comes out.
He BLINKS...
...and the VISION is gone.
Miller is alone, BREATHING hard.
Cooper enters at full speed, shooting through in a controlled fall...
COOPER Hold on, Baby Bear...
...into the Second Containment.
He catches himself at the console.
Cooper sees Justin's safety line, cut off abruptly by the darkness of the Core.
COOPER Oh my God...
The darkness of the Core ripples...
Justin suddenly emerges from the darkness, a white figure riding a wave of impenetrable blackness.
Cooper catches him, holds him tight as the wave carries them towards the wall.
Cooper sees a control rod -- a long metal spike -- coming at them.
He twists his body so that they miss -- barely -- before slamming into the wall.
COOPER Justin, do you read me?
COOPER Justin...
Cooper pulls Justin close.
Justin's head lolls to one side.
Unconscious.
COOPER Baby Bear, don't do this.
COOPER Don't do this...
Weir, Starck and Smith continue to hold on tightly as the vibration builds...
and builds...
STARCK Here comes another one!
STARCK Hold on!
The second wave hits.
Sparks fly as consoles EXPLODE.
Deep in the ship metal SCREAMS, followed by the SHRIEK of escaping atmosphere.
An emergency klaxon RINGS out: PRESSURE WARNING.
Starck checks Justin's station:
STARCK We lost the starboard baffle!
STARCK The hull's been breached!
The Bridge pressure door begins to close...and then stop.
SMITH The safety circuit's failed!
WEIR We're losing atmosphere...
STARCK There are pressure suits in the Airlock.
STARCK Go!
Starck pushes Weir ahead of her, Smith follows hard as they run the length of the ship for the airlock bay.
The vibration subsides.
MILLER Can anybody hear me...
PETERS Skipper...
MILLER Peters...
MILLER ...you okay?
PETERS Yeah.
PETERS I'm -- I'm okay.
Her voice cracks as she says it.
She looks anything but.
The reports come, one on the other...
COOPER We have a man down...
MILLER Coop, where are you...
COOPER The containment, Second Containment...
MILLER Hold on, Coop...
SMITH Captain Miller...
MILLER Smith, where the hell have you been?!
SMITH We have a situation here...
Starck and Smith already in suits.
DJ assists Weir.
Smith has already locked his helmet into place.
SMITH We lost the starboard baffle and the hull cracked.
SMITH Our safety seals didn't close, the circuit's fried --
Miller moves down the central corridor towards his wounded ship.
MILLER Do we have enough time for a weld?
SMITH We don't have time to fart.
SMITH We're losing pressure at 280 liters a second and our oxygen tanks are cracked.
SMITH In three minutes, our atmosphere will be gone.
SMITH We are fucking dead.
MILLER No one's dying on my watch, Smith!
MILLER What about the reserve tanks?
SMITH They're gone.
Beat.
Miller closes his eyes, desperately trying to think of a solution.
PAN across the faces of the astronauts.
No hope.
Except for Weir:
WEIR The Event Horizon.
The others turn to stare at Weir.
SMITH What?
WEIR It still has air and reserve power, we can activate gravity and life support.
STARCK What if the air has gone bad?
STARCK We can't wear these suits forever.
SMITH I don't think this is a good idea, we don't even know what happened on that ship...
WEIR It beats dying, Mister Smith.
MILLER Dr. Weir's right.
MILLER Get on board the Event Horizon.
MILLER I'll meet you at the airlock.
SMITH But...
MILLER You heard me, Smith.
MILLER Peters, are you with me?
Peters at the life support console.
PETERS I'm ahead of you.
PETERS Bringing the thermal units on line...
Peters flips a series of circuit-breakers.
Reaches for the final switch.
PETERS Hold tight and prep for gees.
Everything floating in the bridge CRASHES to the floor.
Justin and Cooper collapse to the deck, coolant splashing down all around them...
Miller meets the crew as they evacuate the Lewis and Clark.
Weir leads the way, eager; Smith hangs back.
MILLER Everybody okay?
STARCK We're all here.
MILLER Okay.
MILLER Let's find out how much time we just bought.
Miller reaches for the catch on his own helmet.
DJ We haven't tested the air yet.
DJ It could be contaminated...
MILLER No time.
MILLER We need whatever's left in our suits to repair the Clark.
MILLER Like it or not, this is the only oxygen for three billion kilometers.
Miller pulls his helmet off with a HISS.
He breathes deep.
Starck does the same, coughs.
STARCK It tastes bad.
MILLER But you can breathe it.
The Lewis and Clark and the Event Horizon, locked together in Neptune orbit.
Lights shine from the Horizon as power is restored.
No longer cloaked in darkness, it is revealed in all its hideous glory, a nightmare etched in steel.
Weir moves from station to station, restoring power to each.
Starck sits at the communications workstation.
Miller watches over her shoulder.
STARCK The antennae array's completely fried, we've got no radio, no laser, no highgain...
STARCK No one's going to be coming to help us.
MILLER How much oh-two do we have?
STARCK Oxygen is not the problem.
MILLER Carbon dioxide?
STARCK It's building up with every breath we take.
STARCK And the CO2 filters on the Event Horizon are shot.
MILLER We can take the filters from the Clark...
STARCK I thought of that, with the filters from the Clark, we've got enough breathable air for twenty hours.
STARCK After that, we'd better be on our way home.
MILLER What about the life readings you picked up?
STARCK The Event Horizon sensors show the same thing: "Bio-readings of indeterminate origin."
STARCK Right before that wave hit the Clark, there was some kind of surge, right off the scale, but now it's back to its previous levels.
MILLER What's causing the readings?
STARCK I don't know, but whatever it is, it's not the crew.
MILLER So where is the rest of the crew?
MILLER We've been over every inch of this ship and all we've found is blood.
MILLER Dr. Weir?
MILLER Any suggestions?
Weir just stares at the bloodstained wall.
MILLER What happened here?
Miller follows Weir's gaze to the wall: a Rorschach test in blood...
PULL BACK from the bridge windows TO REVEAL...
...the Event Horizon in all its horrific glory, hanging skew in the center of the hurricane like a mote in God's eye.
The Lewis and Clark clings to the giant craft, as insignificant as a tick.
An even smaller figure clings to the hull of the Lewis and Clark...
It's Smith, EVA in full protective gear.
His magnetic boots hold him to the Lewis and Clark's hull.
He kneels over a hole in the hull, where the metal has buckled and torn.
Vapor still leaks from the hole into space.
SMITH Captain Miller, you copy?
MILLER I'm here, Smith, how's the Clark?
SMITH I've found a six inch fracture in the outer hull.
SMITH We should be able to repair it and re-pressurize, it's gonna take some time.
MILLER We don't have time, Smith.
MILLER In twenty hours we run out of air.
SMITH Understood.
Smith uses a foam applicator to fill the hole.
The gel freezes in place.
Smith reaches to his belt, pulls out a ZERO-G NAILGUN.
Presses it to the patch and begins to rivet it into place.
Justin lies unmoving on a table.
His eyes are open, staring at a smear of blood on the ceiling.
A needle slides into the skin below his eye.
He doesn't respond.
DJ removes the needle.
It glistens with blood.
He looks up at Miller and Peters.
MILLER How is he?
DJ His vitals are stable, but he's unresponsive to stimuli.
DJ He might wake up in fifteen minutes.
DJ He might not wake up at all.
PETERS What happened to him?
DJ shakes his head.
Miller eyes the bloodstain above them.
MILLER DJ, take samples from these stains, compare them to medical records, I want to know whose blood this is.
Gravity has scattered debris and freeze-dried blood about the room.
The crew (Justin and Smith excepted) tries to relax on the chairs of dead men.
Their faces are wan and haggard.
Weir relaxes at the table.
Unlike the others, he seems almost at ease.
DJ remains forever stoic; Starck, animated and nervous.
Cooper bounces the handball on the floor, a reflex action.
Miller stares at a video monitor, watching Smith repair the Lewis and Clark.
He turns from the window.
MILLER Okay, people, there's been a change in the mission.
MILLER In less than eighteen hours, we will run out of breathable air.
MILLER Our primary objective is now survival.
MILLER That means we focus on repairing the Lewis and Clark and salvaging whatever will buy us more time.
MILLER Our secondary objective is finding out what happened to this ship and its crew.
MILLER Two months from now, I fully intend to be standing in front of the good Admiral giving my report, and I'd like to have more than my dick in my hands.
Grim smiles all around.
MILLER Peters, I want you to go through the ship's log, see if we can't find some answers.
PETERS I can use the station in Medical, keep an eye on Justin...
MILLER Fine.
MILLER Starck, I want you to repeat the bio-scan...
STARCK What's the point?
STARCK I'll just get the same thing...
MILLER Not acceptable.
MILLER I want to know what's causing those readings.
MILLER If the crew is dead, I want the bodies, I want the crew found.
STARCK I can reconfigure the scan for C-12, amylase proteins.
MILLER Do it.
MILLER Dr. Weir...
WEIR Yes.
MILLER One of my men is down.
MILLER I want to know what happened to him.
COOPER I told you.
COOPER He was inside the Core...
Weir starts shaking his head.
COOPER It was like...
COOPER nothing was there...
COOPER and then Justin appeared and the Core...
COOPER became metal...
WEIR No, he didn't.
COOPER You weren't there.
COOPER I saw it.
WEIR Saw what, Mr. Cooper?
WEIR What did you really see, because what you're describing is not physically possible...
Cooper throws the ball at him, hard.
Weir ducks.
It bounces wildly around the room.
Miller catches it.
MILLER Cooper!
MILLER Enough!
Cooper sits down.
MILLER Dr. Weir, Justin may die.
MILLER Whatever happened to him could happen to all of us.
Beat.
WEIR I don't know what happened to Justin.
COOPER I'm telling you, I saw it...
WEIR What you saw could have been an optical effect caused by gravitational distortion.
COOPER I know what I saw and it wasn't a fucking "optical effect!"
MILLER Hold on, what's this "gravitational distortion?"
WEIR It's possible that a burst of gravity waves escaped from the Core, distorting space-time.
WEIR They could be what hit the Lewis and Clark.
MILLER What could cause them?
MILLER What's in the Core?
WEIR It's complicated...
MILLER How much time do you need?
MILLER We have seventeen hours and forty-two minutes.
MILLER Now: what is in the Core?
Beat.
Here comes another bomb...
WEIR A black hole.
The crew stares at him, stunned.
Miller, Starck and Weir stand before the Core.
Dark ominous structures loom around them, glistening with coolant.
The PULSE of the ship is loud here, a deep THRUM that steals their breath.
Weir's voice is a reverent WHISPER:
WEIR That's how the gravity drive works, you see: it focuses the black hole's immense gravitational power to create the gateway.
WEIR That's how the Event Horizon travels faster than light.
STARCK I can't believe we built this.
MILLER It's insane.
WEIR "Insane?" The finest astronauts fought to be posted to this ship.
WEIR It would take the Lewis and Clark a thousand years to reach our closest star.
WEIR The Event Horizon could be there in a day...
MILLER If it worked.
WEIR If it worked, yes.
They stare at the Core, the surrounding machinery moving in a slow giant's dance.
A trick of the eye, or does the Core stare back at them?
MILLER I want this room sealed.
MILLER The Second Containment is off limits.
WEIR There's no danger.
WEIR The black hole is contained behind three magnetic fields, it's under control.
MILLER Your black hole damn near ripped my ship apart.
MILLER It may have killed one of my men.
MILLER No one goes near that thing.
MOVE IN ON THE CORE until its darkness fills the screen...
Peters sits before the computer workstation, running the ship's log, forwarding through hours of boring footage.
Rubs her eyes.
The lights flicker.
Peters hears something RUSTLING behind her.
She turns...
PETERS Justin...?
Justin lies unmoving on the nearest examination table.
Comatose.
Peters reaches out and picks up a scalpel.
Peters hears the sound again, FINGERNAILS ON PLASTIC.
She moves past Justin...
...past several empty tables, covered with clear plastic...
...to the last table.
She stares in shock.
She slowly reaches out.
Lifts the cover.
Her son DENNY looks at her and GIGGLES.
She GASPS.
The scalpel drops to the floor at her feet.
Denny reaches up to her, to be picked up...
DENNY Mommy...
...but the plastic that still covers his withered legs squirms like a bag full of snakes...
Peters drops the plastic and backs away.
DJ Peters?
She turns.
DJ stands in the doorway, holding blood samples.
Peters turns back, but her son is gone.
DJ reads her expression.
DJ What's wrong?
PETERS Nothing.
PETERS It's nothing.
The Airlock light turns red -- a warning.
The Inner Airlock door control flashes: "LOCKED."
The Outer Airlock door opens.
Smith enters.
He closes the Outer Airlock door.
Atmosphere HISSES into the chamber.
The Inner Airlock door flashes:
Cooper in EVA, getting ready to go outside.
The Inner Airlock door opens.
Smith enters.
Takes off his helmet.
COOPER You been out there a long time.
COOPER Trying to break my record?
SMITH I'd rather spend the next twelve hours Outside than another five minutes in this can.
SMITH This ship is bad.
SMITH It watches you.
COOPER What?
You heard me.
This ship, it's crazy: trying to go faster'n light, that's like the Tower of Babel.
COOPER Shit, Smith, you're going Biblical on me.
SMITH You know what happened to the Tower of Babel, don't you?
SMITH It fell down.
COOPER You're sucking too much nitrogen in your mix.
Starck programs the sensor workstation.
She glances over at Weir: sitting at a computer terminal, his face rapt as data flashes by.
His lips move, muttering to himself.
STARCK Why Dr. Weir, I think you're in love.
WEIR Hmmm.
WEIR Claire used to tell me I loved the Event Horizon more than I loved her.
WEIR I told her that wasn't true, I just knew the Event Horizon better, that's all.
STARCK Claire is your wife?
WEIR Yes.
STARCK It must be hard, being so far away from her.
WEIR Yes.
WEIR I miss her.
WEIR She died.
WEIR Two years now.
STARCK I'm sorry.
Weir keeps his attention focused on the screen.
WEIR These things happen.
WEIR Wait a minute, that's not right...
He fingers fly across the keyboard, double-checking the data.
Miller leans over Weir's shoulder.
MILLER You have something, Dr. Weir?
WEIR The date.
MILLER What about it?
WEIR The Event Horizon's computer think's it's 2034.
MILLER It's 2041...
WEIR Exactly.
WEIR The ship's internal clock is off by seven years.
STARCK Maybe a power interruption crashed the system...
WEIR No, there's no evidence of a surge or spike of any kind.
WEIR It's as if time just...
WEIR stopped for seven years.
MILLER Explanation?
WEIR Intense gravitational fields effect the passage of time, it's possible...
WEIR Black holes make sense on paper, it's all math, you see, but as to what really happened...
WEIR The Event Horizon has passed beyond our plane of reality, and like Lazarus, returned from the dead.
The INTERCOM interrupts them:
PETERS Captain Miller, Dr. Weir?
PETERS I found the final log entry.
Peters sits at the workstation.
Miller, DJ and Weir stand behind her, watching.
A jumpy, handheld camera view of:
Gravity couch bay.
Two crewmen checking electronics modules.
The ship is well-lit, clean, no sign of debris.
The narrator's voice is excited and nervous.
KILPACK We have reached safe distance and are preparing to engage the gravity drive and open the gateway...
PETERS The speaker is the mission commander...
WEIR John Kilpack.
Second Containment.
A lone engineer finishes his check of the Core.
He turns to the camera and gives a self-conscious "thumbs-up."
KILPACK When you get this message, God willing, we will reach the solar system of Proxima Centauri...
MILLER I wonder if they ever made it.
Corridor.
The entire original crew assembled, playing catch with the stuffed dog
KILPACK I just want to say how proud I am of my crew.
KILPACK I'd like to name my station heads Chris Chambers, Janice Rubin, Dick Smith, Tom Fender and Stacie Collins.
KILPACK And to Bill Weir and all the scientists that got us here.
Bridge.
KILPACK addresses the camera.
His face is flushed with excitement.
KILPACK I...
KILPACK uh, I had something historic to say, and I wrote it down but I...
KILPACK I can't find it.
KILPACK Ave, atque, vale.
KILPACK Hail and farewell.
A BURST of static...
...followed by an inhuman HOWL of FEEDBACK, like screaming hyaenas, almost alive.
Through the swirl of static, the suggestion of movement.
Miller freezes the frame.
He squints at the screen...
Obscured by static, the image is blurred beyond comprehension.
MILLER What the hell is that?
MILLER Dr. Weir?
WEIR I don't know.
PETERS I can run the image through a series of filters, try to clean it up.
MILLER Do it.
Suddenly, the lights fade out.
Dim emergency lighting snaps on...
PETERS What's happening...?
DJ A power drain --
MILLER We barely have enough power for life support as it is, if we can't stop the drain, we're not gonna make it.
WEIR The Core...!
Weir heads for the door.
MILLER Wait!
But Weir has vanished into the corridor.
MILLER The rest of you, stay here, I don't want anyone else going near that thing.
Miller follows after Weir.
The Second Containment Seal opens.
Weir is about to enter when Miller stops him.
He checks a Geiger counter.
It is silent.
MILLER No radiation.
MILLER What's causing the drain?
Weir crosses to a console.
Frowns.
WEIR The magnetic fields are holding.
WEIR Maybe a short in the fail-safe circuit.
WEIR I'll check it out.
Miller assists Weir in removing bolts from an access panel.
The panel falls away, revealing a cramped duct leading into the ship's circuitry.
Weir climbs into the duct.
Miller hands him a flashlight and a toolkit.
MILLER We don't get the power back, our air's gonna go bad.
WEIR Check the Core for radiation.
WEIR Carbon dioxide may be the least of our worries.
Weir begins to crawl into the depths of the ship.
Weir's breath ECHOES in the cramped shaft.
He counts off circuit panels as he goes:
WEIR E-three...
WEIR E-five...
WEIR E-seven...
WEIR where are you...
Miller slogs through the coolant to the Core.
Stares at it.
It remains metallic, mundane.
He pulls out a Geiger counter and crosses to the reactor shell.
Examines a gleaming weld.
The Geiger counter CLICKS slowly: no leak.
A yellow light starts flashing on the engineering board.
Starck's eyes widen: the engineering sections flash yellow...and green...
STARCK What the hell...
STARCK'S POV as the bio-scan goes wild.
STARCK Skipper, the bio-scan just went off the scale...
Justin shakes on the bed in an epileptic fit.
DJ rushes to him.
DJ Justin!
DJ Can you hear me?
DJ Justin!
Justin's eyes remain unfocused, unseeing as he tries to speak.
DJ leans in close, trying to hear him speak...
Justin arches in agony and the words come in a strangled, tortured voice:
Weir stops before module E-12.
Hears a faint HISSING and
WEIR There you are.
He uses a screwdriver to open up the module.
Reveals a series of circuit boards.
One SPARKS.
Weir plucks the damaged chips and starts running a by-pass.
His flashlight flickers.
He bangs it against the duct wall.
It grows dimmer.
Goes out.
WEIR Um.
WEIR Captain Miller?
WEIR I, uh, I seem to have a problem with my light.
A single DRIP of water in the darkness...
WEIR Captain Miller?
Another DRIP, then a woman's VOICE like a distant echo:
VOICE Billy.
Weir starts at the sound.
He recognizes the voice.
She speaks again, no longer far away, but a close WHISPER in his ear:
CLAIRE Billy.
CLAIRE Help me.
CLAIRE I'm so cold.
Weir's eyes open wide in hope and fear.
Even the emergency lights go out.
Total darkness.
MILLER We just lost all power in here.
MILLER Dr.
MILLER Weir...?
Miller's voice trails off as he looks towards the Core.
A red glow reflects across his eyes.
He takes a few steps away from the reactor.
He stares...
...at the BURNING MAN, standing before the Core.
The deep ROAR of its conflagration fills the containment.
It slowly turns and raises its arm and points at Miller in accusation.
BURNING MAN Don't leave me...
Miller stares as the Burning Man turns and vanishes into a bulkhead, leaving the wall blackened and burned with his passing.
Total darkness.
Weir's breath ECHOES in the cramped metal space.
WEIR Claire...?
Weir bangs his flashlight.
Again.
Again...
CLAIRE Help me.
CLAIRE I'm so cold.
The flashlight flickers...
Claire's face is inches from Weir's.
CLAIRE So cold.
His flashlight flickers again, snaps on...
She is gone.
Weir lets his head fall to the floor of the deck, breathing in ragged SOBS.
The crew, except for Cooper.
DJ whets a scalpel against the leg of his jumpsuit, an unconscious gesture.
FLICK.
FLICK.
DJ Carbon dioxide poisoning produces hallucinations, impaired judgement...
MILLER Goddammit, DJ, it was not a hallucination!
MILLER I saw a man, he was on fire.
MILLER And then he disappeared.
STARCK Maybe one of the original crew?
MILLER No.
MILLER It was someone else.
STARCK Who?
MILLER Dr. Weir, you were right there, you must have heard something, seen something...
WEIR No.
WEIR I saw nothing.
PETERS I did.
All heads turn to her.
PETERS About an hour ago.
PETERS In medical.
PETERS I saw my son.
PETERS He was lying on one of the examination tables and his legs were...
WEIR Isn't it possible that you were traumatized by finding the body on the bridge?
PETERS I've seen bodies before.
PETERS This is different.
She falls silent, unwilling to say more.
MILLER Peters is right.
MILLER Its like something reaching into your mind.
MILLER Seeing your thoughts and making them real.
MILLER Smith, did you or Cooper experience anything unusual?
Smith, leaning against the doorway:
SMITH I didn't see anything and I don't have to see anything.
SMITH This ship is fucked.
WEIR Thank you for that scientific analysis, Mister Smith.
SMITH Hey!
SMITH You don't need to be a scientist figure it out...
MILLER Smith...
Weir's face is stone.
SMITH ...you break all the laws of physics, you think there won't be a price?
SMITH You already killed the first crew...
MILLER That's enough!
DJ lays one hand on Smith's shoulder to calm him...
Smith reacts violently, turning on DJ, shoving him back.
DJ uses Smith's momentum to spin the pilot into the wall.
He presses his scalpel just below Smith's ear...
DJ freezes.
The scalpel falls from his hands.
He releases Smith.
DJ I'm sorry, I...
DJ I don't know why I did that.
WEIR Carbon dioxide.
Smith goes for Weir.
SMITH He's fucking lying, you know something...!
Miller heads him off, grabs him.
MILLER That's it, that's enough for one day, Smith!
MILLER I need you back on the Clark, I need you calm, I need you using your head, you make a mistake out there, none of are getting home, you understand?
Smith calms.
SMITH Sir.
MILLER Get outside, go back to work.
MILLER I'll join you shortly.
Smith leaves.
MILLER We're a long way from home and we're in a bad place.
MILLER Let's not make it worse.
MILLER If anyone has any constructive suggestions, now is the time.
WEIR I think I can stabilize the fields around the singularity, that should prevent another power drain.
MILLER Do it.
DJ To conserve our oxygen, we should severely restrict our activity.
DJ Anyone who can should get some sleep.
MILLER I don't need sleep, DJ.
MILLER I need answers.
Miller exits.
Starck follows.
STARCK Miller...
MILLER What is it, Starck?
STARCK ...I ran the bio-scan with the DNA/RNA filter.
STARCK The results were bio-readings of indeterminate origin...
MILLER "...bio-readings of indeterminate origin," don't you have anything useful to tell me?
STARCK I've got a theory.
Miller stops.
MILLER Go ahead.
STARCK There was a another surge in the bio- readings right before you...
STARCK you saw what you saw.
STARCK We picked up a similar readings right before the Clarke was damaged.
STARCK What if there were a connection between the two?
STARCK The gravity waves, the hallucination, all part of an defensive reaction, like an immune system...
Miller starts walking again.
MILLER I don't need to hear this.
She rushes to follow.
Miller and Starck enter the Airlock Bay:
STARCK You've got to listen...
MILLER To what?
MILLER What are you saying?
MILLER This ship is alive?
STARCK I didn't say that, I said the bio- readings correspond to what happened to you, the ship is reacting to us...
MILLER We're hanging on by our fingernails and you're giving me bullshit stories...
She grabs him by the arm.
STARCK It's not bullshit, it's the only conclusion the data supports...
MILLER Starck, do you know how crazy that sounds?
MILLER It's impossible.
STARCK I know that.
Beat.
Miller allows himself to relax.
MILLER If you knew it was impossible, then why'd you waste my time?
STARCK I thought you wanted an answer.
STARCK And that's the only one I have.
Miller pulls an EVA suit from the wall, starts putting it on.
MILLER What I want is to survive the next ten hours.
STARCK Nine hours and twenty-two minutes.
MILLER I'm going outside to work on the Clark.
MILLER And Starck...
MILLER don't tell anyone what you just told me.
MILLER We've got enough to worry about.
She nods.
He locks his helmet into place.
Establish.
The ship seems to breathe.
The lights flicker...
ANOTHER ANGLE.
The ship seems to breathe.
The lights flicker...
ANOTHER ANGLE.
The ship seems to breathe.
The lights flicker...
Peters has fallen asleep in her chair.
On the threshold of hearing, a distant POUNDING.
Not a heartbeat.
Metal on metal.
Something trying to get out.
Something trying to get in.
Peters wakes with a start.
PETERS Justin...?
She turns.
Justin lies on the floor in a heap, completely covered by his sheet.
She crosses to him.
Pulls back the sheet...
Revealing empty nitrogen tanks.
PETERS Justin!
She looks up, eyes widening, as...
The IV bottles fill with blood.
Blood fills the X-ray lightboxes, it surges up from gutters in the floor...
And the pounding grows louder...
LOUDER...
almost to Medical...
The spell breaks and she RUNS...
Peters sprints, the SOUND BOOMING after her, almost on her heels...
Peters darts into the Bridge Antechamber.
She SLAMS the pressure door shut behind her, CUTTING OFF the sound.
She turns.
Weir, DJ, Starck look up from their work, staring at her.
DJ What's wrong?
PETERS You didn't hear it?
PETERS You must have heard it!
STARCK Heard what?
Beat.
Peters starts to LAUGH, part hysteria, part relief.
PETERS Oh...
PETERS nothing...
DJ crosses to Peters, concerned.
DJ Sit down...
As he reaches out to touch her...
Peters SCREAMS.
DJ clutches her to him, backs away from the door.
The POUNDING grows louder.
LOUDER.
The door vibrates with each blow Starck puts her hands over her ears.
Peters SCREAMS at the door.
PETERS Stop it!
PETERS Stop it!
But the POUNDING intensifies, metal GROANING under incredible pressure.
DJ What is it?
Weir slowly walks to the door.
STARCK What are you doing?
WEIR It wants me.
WEIR I have to go.
He reaches for the door.
STARCK No...!
Starck grabs him.
He tries to shake her off, but she traps his arm in a wrist-lock.
He turns on her, his face furious...
...and the POUNDING stops.
They remain frozen for a moment.
Afraid to breathe.
Weir shakes the trance.
STARCK In our current environment, Dr. Weir, self-control is an asset.
WEIR I'm alright.
WEIR Please.
In the distance, the POUNDING begins again.
Moving away from them.
The ship systems station BEEPS.
A warning light flashes on the console.
STARCK What is it?
WEIR The forward airlock.
STARCK Miller, Smith, Cooper, any of you in the airlock?
MILLER That's a negative, Starck.
PETERS Justin.
Peters, Starck and DJ rush from the Bridge, leaving Weir behind.
Peters leads Starck and DJ down the corridor towards the Forward Airlock bay.
They round a corner in time to see a figure moving in the Airlock.
They race into the bay even as Justin steps into the Airlock.
He is naked.
PETERS Justin, no!
Justin turns and stares through them with cold eyes.
He reaches out to the airlock control.
The pressure door shuts with a HISS.
Miller, Smith and Cooper cling to the Lewis and Clark's hull.
They carefully remove an access panel, revealing scorched wiring.
COOPER We'll have to re-route through the port conduit to the APU.
SMITH What about the accumulator...?
Starck's VOICE breaks in:
STARCK Miller, come in...
MILLER What's going on in there, Starck?
STARCK Justin's in the airlock.
Starck at the intercom.
The others huddle by the door.
MILLER What?
STARCK He's awake, he's in the airlock, he's not wearing a suit.
MILLER Stay here!
MILLER Don't stop working!
COOPER But Justin...
MILLER I'll get him.
Miller swings his body around, heads across the umbilicus to the Event Horizon.
He moves in great leaps, using the magnetic plates in his gloves and boots to keep from drifting off into Neptune's thin atmosphere.
Starck works the airlock control panel without success.
STARCK He's engaged the override.
PETERS Can you shut it down?
She opens the Airlock access panel.
STARCK I'll try.
STARCK DJ, you better get your bag of tricks.
DJ nods, runs off.
Peters bangs on the Airlock door.
PETERS Justin!
PETERS Open the door!
Peters' voice barely penetrates the pressure door:
PETERS Open the door!
Justin turns off the artificial gravity.
He begins to float gently.
Miller moves like a frantic spider across the surface of the Event Horizon.
MILLER I'm on my way, Starck.
STARCK You better hurry.
STARCK He's engaged the override, we can't open the inner door.
Miller curses under his breath, moves even faster...
Peters, against the window:
PETERS The door, Justin!
PETERS Open the door!
He fixes his gaze upon the outer airlock door.
And beyond it, space.
He speaks in a flat monotone:
JUSTIN Did you hear it?
They are stunned to hear his voice.
Peters answers:
PETERS Yes.
PETERS Yes, Justin, we heard it.
STARCK Keep him talking.
PETERS Do you know what it was?
JUSTIN It gets inside you.
JUSTIN It shows you things...
JUSTIN horrible things...
JUSTIN ...can't describe it...
JUSTIN there are no words...
Weir sits alone, listening to the VOICES on the intercom.
PETERS What, Justin, what shows you?
JUSTIN It won't stop, it goes on and on and on...
PETERS What does?
JUSTIN The dark inside me.
A LOW MOAN escapes Weir's lips.
He cradles his head in his hands.
Miller races across the surface of the Event Horizon, the only sounds, his LABOURED BREATHING, and Justin's tortured VOICE, patched through on his radio:
JUSTIN ...It's inside and it eats and eats until there's nothing left.
PETERS "The dark inside..."
PETERS I don't understand.
JUSTIN From the Other Place...
JUSTIN The other crew, they're there, they're waiting for me.
JUSTIN They're waiting for you.
JUSTIN I won't go back there...
JUSTIN I won't...
Peters presses her face against the Airlock window, trying to calm him:
PETERS Justin, look at me.
PETERS Look at me.
PETERS Open this door.
DJ runs up with his medkit.
STARCK I don't think she can talk him down.
STARCK We need a sedative.
DJ If he opens the outer door he'll turn inside-out.
Starck's hands fly as she re-wires the circuits.
Sweat beads her face.
STARCK Almost got it.
PETERS Come on, Baby-bear, open this door...
Justin looks at her with dead eyes.
He reaches out to gently touch the glass between them.
JUSTIN If you could see the things I've seen, you wouldn't try to stop me.
JUSTIN You'd come with me.
Justin's hand moves to the OUTER AIRLOCK DOOR control.
Hesitates...
then floats to the OUTER AIRLOCK control.
Hits it.
A yellow warning light flashes.
A warning klaxon WHOOPS, deafening.
Justin jerks his hands to his ears, closes his eyes...
COMPUTER Stand-by for decompression.
COMPUTER Thirty seconds...
Justin opens his eyes as if waking from a dream...
JUSTIN Hey, Mama-Bear...
JUSTIN what are doing...?
And then he realizes where he is...and what is about to happen.
JUSTIN Oh my god OH MY GOD...
PETERS Starck!
STARCK I can't!
STARCK The inner door can't open once the outer door has been triggered, it would decompress the entire ship!
JUSTIN You gotta open, you gotta stop it, please...
PETERS We have to do something, oh God...
STARCK Skipper, Justin just activated the door.
STARCK It's on a thirty second delay...
Miller moves through the Event Horizon superstructure, recklessly leaping from one beam to another, trying to build up speed.
MILLER Patch me through to him.
MILLER Justin.
JUSTIN Skipper, you gotta help me...
COMPUTER Twenty seconds.
JUSTIN ...tell them to open the door...
MILLER They can't do that Justin, now listen carefully...
Miller moves faster and faster, his BREATH echoing in his helmet.
He can see the exterior airlock just beyond a deep chasm in the ship's superstructure.
If he misses this jump, Justin will not be the only man to die today.
He doesn't hesitate but leaps, soaring across the chasm towards the airlock.
JUSTIN ...I don't want to die...!
MILLER You're not going to die!
MILLER Not today!
MILLER I want you to do exactly as I say and I'm gonna get you out of there, alright?
JUSTIN But I can't...
JUSTIN I gotta get out of here...
JUSTIN Skipper, please...
MILLER Justin.
MILLER I won't let you die.
Miller's words give Justin hope.
He regains some control.
JUSTIN Okay...
JUSTIN okay...
Justin breathes hard and follows Miller's hurried instructions:
MILLER Tuck yourself into a crouched position, shut your eyes as tight as you can!
STARCK Five seconds.
Miller lands on the superstructure opposite the exterior airlock.
MILLER Exhale everything you got, Baby Bear, we can't have any air in those lungs, blow it all out...
Justin goes into a fetal crouch and covers his eyes.
JUSTIN Oh god --
He wheezes out all his air...
Miller squats on the girder, ready to push off.
He focuses on the 5 meters of space between him and the airlock...
The outer doors OPEN...
The rush of escaping atmosphere carries Justin's body out...
Miller pushes off...
catches Justin's body...
sending them both back towards the open Airlock...
Ice forms on Justin's body.
His veins bulge.
Blood fountains from his noise and mouth, forming a red icicle over his face.
Miller pulls him into the Airlock.
Five seconds have passed since the airlock door opened.
Miller closes the Airlock behind them.
Air HISSES into the chamber.
Justin's body hits the deck as "normal" gravity exerts itself.
Miller opens the Inner Door.
Peters and DJ rush in.
PETERS Oh God...
PETERS Justin...
DJ puts a tube in the Justin's mouth immediately, feeding him oxygen.
PETERS I've got a pulse, he's alive...
DJ Pressure?
PETERS 90 over 50 and falling...
DJ He's crashing...
Blood bubbles from Justin's mouth and eyes.
He GASPS, then SCREAMS, spraying blood from his mouth.
DJ He can breathe.
DJ That's good.
DJ Let's get him to Medical, go, go!
Starck helps DJ and Peters carry Justin from the Airlock.
Miller sits there, exhausted.
Reaches up and pulls his helmet off.
Weir listens to
DJ Intubate, pure oxygen feed, get the nitrogen out of his blood...
PETERS His peritoneum has ruptured...
DJ One thing at a time, let's keep him breathing.
DJ Start the drip, 15cc's fibrinogen, Christ, he's bleeding out...
One of the tanks has been activated.
Swaddled in bandages, Justin floats within, suspended in green gel.
The others -- DJ, Starck, Peters, Miller, Weir -- look exhausted.
DJ He'll live...
DJ if we ever make it back.
MILLER We'll make it.
STARCK CO2 levels will reach toxic levels in four hours.
Peters stands, looking at Justin's ravaged form floating in the tank.
MILLER Peters.
MILLER We need to know what happened to the crew.
MILLER Before it happens to us.
PETERS I'll get back to the log.
PETERS But on the bridge, I won't go back, back in there...
MILLER Thanks.
Peters exits.
STARCK Justin said something about, "The dark inside me..."
STARCK What did he mean?
WEIR It means nothing.
MILLER Is that your "expert opinion?" The only answer we've had out of you is "I don't know."
WEIR Justin just tried to kill himself.
WEIR The man is clearly insane.
DJ How would you explain your own behavior?
WEIR What?
STARCK On the bridge.
STARCK You said "it" wanted you.
Weir glances at Justin...
But it's not Justin in the tank.
It's his wife CLAIRE, naked, wet, dead.
Weir stares at her.
WEIR I said that?
DJ Yes.
DJ You did.
Weir blinks.
Justin floats in the grav couch.
Weir turns back to the others.
WEIR I don't remember saying that.
WEIR Maybe I'm insane, too.
Weir exits.
Miller follows Weir out of the Gravity Couch Bay.
MILLER I want to know what caused that noise.
MILLER I want to know why one of my crew tried to throw himself out of the airlock.
WEIR Thermal changes in the hull could have caused the metal to expand and contract very suddenly, causing reverberations --
MILLER That's bullshit and you know it!
MILLER You built this fucking ship and all I've heard from you is bullshit!
WEIR What do you want me to say?
MILLER You said this ship creates a gateway...
WEIR Yes...
MILLER To what?
MILLER Where did this ship go?
MILLER Where did you send it?
WEIR I don't know...
MILLER Where has it been for the past seven years?
WEIR I don't know...
MILLER The "Other Place," what is that...?
I DON'T KNOW! I don't know.
I DON'T KNOW! There's a lot of things going on here that I don't understand.
I DON'T KNOW! Truth takes time.
MILLER That's exactly what we don't have, Doctor.
Miller moves through the maze of the ship, heading for the Bridge.
As he reaches a junction, he hears...
VOICE Don't leave me...!
Miller wheels like a cat, staring wildly down the branching corridors.
Nothing.
He is alone.
Miller leans against the wall, sinks to the floor, rests his head in his hands.
The grotesque ship continues it's orbit as the moon Triton eclipses the sun.
Darkness swallows all.
DJ enters, checks Justin's display.
MILLER Any change?
DJ turns, surprised.
Miller sits, barely visible in the dark.
DJ No.
DJ No change.
DJ I've analyzed Justin's blood samples.
DJ There's no evidence of excessive levels of carbon dioxide.
DJ Or anything else out of ordinary.
A grim LAUGH from Miller.
MILLER Of course not.
MILLER Justin just climbed into the airlock because he felt like it.
MILLER Just one of those things.
MILLER I swore I'd never lose another man.
MILLER I came close today.
MILLER Real close.
DJ "Another man?" Who?
Miller nods, pulls his service medal from beneath his jumpsuit.
MILLER It was on the Goliath.
MILLER There was this bosun, Corrick, a young guy, a lot like Justin.
MILLER Edmund Corrick, from Decatur, Georgia.
MILLER He got caught when the pressure doors sealed, one closed on his arm.
MILLER Severed it at the wrist.
MILLER The pain of that must have been...
MILLER He passed out and...
Miller trails off.
DJ waits patiently.
Finally:
MILLER I, I tried to go back for him, to save him, but I couldn't get to him in time.
MILLER The fire...
MILLER Have you ever seen fire in zero-gravity?
MILLER It's like a liquid, it slides over everything.
MILLER It was like a wave breaking over him, a wave of fire.
MILLER And then he was gone.
MILLER I never told anyone until now.
MILLER But this ship knew, DJ.
MILLER It knows about the Goliath, it knows about Corrick.
MILLER It knows our secrets.
MILLER It knows what we're afraid of.
MILLER And now you're going to tell me it's carbon dioxide.
DJ No.
Miller sees something in DJ's expression.
MILLER What is it?
DJ I've been listening to the transmission.
DJ And I think Houston made a mistake in the translation.
MILLER Go on.
DJ plays the recording again.
Stops it abruptly.
DJ They thought it said, "Liberatis me," "Save me," but it's not "me."
DJ It's "tutemet:" "Save yourself."
MILLER It's not a distress call.
MILLER It's a warning.
DJ It gets worse.
Miller stares at him.
DJ It's very hard to make out, but listen to this final part.
He plays the recording again.
DJ Do you hear it?
DJ Right there.
MILLER Hear what?
DJ It sounds like "ex infera:" "ex," from; "infera," the ablative case of "inferi."
DJ "Hell."
MILLER "Save yourself.
MILLER From Hell."
MILLER What are you saying, are you saying that this ship is possessed?
DJ No.
DJ I don't believe in that sort of thing.
DJ But if Dr. Weir is right, this ship has passed beyond the boundaries of our universe, of reality.
DJ Who knows where this ship has been...
DJ What it's seen...
DJ And what it's brought back with it.
DJ looks at Miller.
He does not have an answer.
The intercom
COOPER Captain Miller, we're ready to repressurize the Clark.
MILLER On my way.
Miller stands in his EVA suit in the darkened bridge.
He twists a manual valve.
MILLER Alright, Cooper.
Cooper looks at Smith.
COOPER Cross your fingers.
A moment later, mist flows from the vents into the bridge, filling it with atmosphere.
Miller watches the pressure rise on his suit gauge.
SMITH It's holding...
SMITH She's holding...!
COOPER We're still venting trace gasses, gimme twenty minutes to plug the hole.
MILLER You got it, Coop.
Miller removes his helmet.
Breathes deep.
MILLER Back in business.
Peters sits in front of the screen.
The log is still distorted.
Frustrated, she types in a series of instructions.
Get to her feet.
PETERS You got any coffee?
STARCK It's cold.
PETERS I don't care.
Behind Peters, the process refines, accelerates...
pieces coming together like a jigsaw...
Peters turns around.
Sees the screen.
The coffee slips from her hand to the floor.
PETERS Starck...
Starck turns, sees the screen.
PETERS Sweet Jesus.
PETERS Miller...
PETERS MILLER!
Miller, Starck, DJ watch the video.
Peters turns away, miserable.
Unable to watch...
INT. EVENT HORIZON - BRIDGE THE VIDEO SCREEN still distorted by static and roll, but finally lucid: FOUR ORIGINAL CREW of the Event Horizon.
On the Bridge.
ONE MAN dislocates his shoulder with a WET POPPING sound as he shoves his arm down his own throat.
Blood bubbles from his nose.
With a SHUCKING sound, he pulls his stomach out his mouth...
Behind him, a MAN and WOMAN fuck, covered with blood.
She bites through his neck.
His head lolls to the other side.
She buries her face in the torn flesh as he thrusts into her again and again...
Presiding over them, KILPACK.
His eyes are bloody holes.
His hands reach out in offering.
In the palms of his hands, his eyes.
Kilpack opens his mouth and speaks with an INHUMAN VOICE.
KILPACK Liberatis tutemet ex infera...
Miller switches off the video.
No one says anything.
MILLER We're leaving.
WEIR You can't, your orders are specific...
MILLER "...to rescue the crew and salvage the ship."
MILLER The crew is dead, Dr.
MILLER Weir.
MILLER This ship killed them.
MILLER And now it's killing us.
WEIR You're insane.
WEIR You've lost your mind.
MILLER Maybe you're right.
MILLER But it's still my command, and I have leeway to abort when I feel there is an unacceptable threat to my crew.
MILLER And I think there is.
MILLER Starck, download all the files from the Event Horizon's computers.
MILLER Coop, Smith, finish moving the CO2 scrubbers back onto the Clark.
WEIR Don't...
WEIR don't do this...
MILLER It's done.
Peters enters, carrying heavy CO2 scrubbers.
Smith stops her.
SMITH What's going on, sweethearts?
PETERS CO2 scrubbers for the Clark.
PETERS Miller pulled the plug on the mission.
Smith smiles.
SMITH About goddam time.
Sequence omitted from original script.
Weir follows Miller down the Corridor.
WEIR What about my ship?
MILLER We will take the Lewis and Clark to a safe distance and then launch tac missiles at the Event Horizon until I am satisfied that she has been destroyed.
MILLER Fuck this ship.
WEIR You...
WEIR You can't do that!
MILLER Watch me.
Miller turns to walk away.
Weir grabs Miller, wheeling him around, almost frenzied.
WEIR You can't kill her, I won't let you!
WEIR I lost her once, I will not lose her again...!
Miller shoves Weir back into the wall.
The two stare at each other.
Adversaries...
The lights cut to emergency lighting.
STARCK Miller, come in ...
Miller finds the intercom:
MILLER Starck, what the hell is going on?
Starck peers at the Engineering board:
STARCK We just lost main power again.
Miller and Weir are barely visible in the darkness.
MILLER Goddammit!
MILLER Starck, get those files and vacate.
MILLER I want off this ship.
He releases the intercom.
Weir's voice is a WHISPER as he backs into the shadows.
WEIR You can't leave.
WEIR She won't let you.
MILLER Just get your gear back onto the Lewis and Clark, doctor, or you'll find yourself looking for a ride home.
Weir is swallowed by the darkness.
WEIR I am home.
REGULAR LIGHTING snaps on...
Miller looks around.
Dr. Weir has vanished.
MILLER Weir?
MILLER WEIR!
He slams the intercom:
MILLER All hands.
MILLER Dr. Weir is missing.
MILLER I want him found and restrained.
Starck gathers all the files and disks.
Shuts down the consoles, one by one.
Smith and Peters finish removing CO2 scrubbers from panels in the walls.
SMITH Let's go, let's go, this place freaks me out...
PETERS Last one.
Peters follows Smith down the First Containment towards the Main Access Corridor, carrying the last case of scrubbers.
She begins to lag behind.
A GIGGLE echoes down the First Containment.
PETERS Denny?
She turns back to the Second Containment...
A SMALL FIGURE dashes through the darkness in the Second Containment.
Denny...?
PETERS Smith.
Peters turns, but Smith is already out of sight.
She hesitates.
Moves back towards Second Containment.
Again, Peters hears the GIGGLE of a child.
The SCRAPE of metal on metal.
She slowly moves forward...
...into the darkness of the Second Containment.
Peters sees an open access panel.
She looks inside.
A narrow tube, vanishing into darkness.
A YOUNG CHILD'S VOICE echoes from far away:
DENNY Mommy...
PETERS ducks her head and enters the access duct.
PETERS Denny...?
Miller sits at Justin's engineering position.
Flips a series of switches...
Cooper works on the patch as the ship's running lights come on in sequence...
The bridge lights flicker, illuminate...
MILLER Thank you.
SMITH Captain, we got a problem.
MILLER Now what?
SMITH She was right behind me, I turn around, she's gone.
SMITH She could be anywhere.
MILLER Alright.
MILLER Prep the Clark for launch.
MILLER I'll find her.
Peters moves through the duct.
Reaches a junction.
Anything could be with her, there in the dark.
A child's WHISPER, too faint for words.
Peters turns...
Behind her, FOREGROUND, a YOUNG CHILD dashes across the corridor.
Peters turns back.
Too late to see.
Again, the child's WHISPER draws her onward.
PETERS Denny?
PETERS Denny, come to Mommy...
FAINT LAUGHTER is her only answer.
She follows the sound, now climbing into a vertical shaft that takes her higher and higher...
PETERS Hold on, Denny, Mommy's coming...
Peters pulls herself up from the vertical shaft onto a catwalk that snakes between huge oily machinery, just in time to see...
A SMALL CHILD running, disappearing into the gloom ahead.
PETERS Denny?
She runs forward into a junction.
The lights flicker red.
PETERS Denny...?
DENNY Mommy...
Her son can barely be seen in the flickering darkness ahead.
PETERS You can walk...
PETERS Denny, you can walk...
PETERS oh, my baby...
DENNY Wanna show you, Mommy, wanna show you something...
He reaches his arms out to her...
Peters steps forward, reaching for her son...
...falling into an open access hatch, hidden in the dark...
...a twenty meter drop...
Peters hits hard, lies before the Core, an offering of flesh and blood.
Her legs twist beneath her, shattered; blood pools around her head.
Her chest heaves: still alive.
PETERS Denny...
Denny peers down from the top of the shaft and GIGGLES.
CLAPS his hands in childlike glee.
Weir wanders into First Containment, brooding.
WEIR I won't.
WEIR I won't leave.
WEIR This is my ship.
Weir enters the Second Containment.
Freezes as he sees...
Peters body lying twisted and broken before the Core.
WEIR Oh no.
WEIR Peters...?
He rushes to Peters.
Reaches out to touch her but pulls his hand back.
Her eyes are black, eight-ball hemorrhage darkening the irises.
She is dead.
WEIR Why did you do that?
WEIR You didn't have to do that...
CLAIRE Billy.
Weir looks up from Peters' corpse.
CLAIRE stands before the Core.
She is naked.
Her skin is pale and beautiful and cold and wet.
Her hair hangs in her face, covering her milk-white eyes...
Claire stands naked before the bathroom mirror.
Behind her, the tub steams...
Weir stares at Claire in shock.
She walks to him.
Slowly.
She stops in front of him.
Her arms hang at her sides.
He must reach for her.
He does, putting his hands on her hips.
He slides from his chair to the floor to his knees.
He presses his face to her pale belly and cries.
SOBS wrack his body...
...and in the bathroom, she clutches Weir's straight-razor...
She reaches down.
Slowly, her arms cradle his head.
She slides down on him.
Straddles him.
...Claire slips into the steaming water...
He raises his head to her breasts.
His eyes, closed.
She remains unnaturally still, only her hips rocking back and forth.
Weir's mouth opens, GASPS as he enters her...
...and the razor bites her skin...
She caresses his face.
Lifts his face to hers.
Her mouth is slack.
Her hair hangs in front of her eyes.
...Claire floats dead in the red water, eyes open, hair billowing around her head like a halo...
Weir gazes up at her, transfixed.
He takes her hand and raises it to his face.
She caresses his cheek.
And reaches for his eyes...
A MUFFLED SCREAM rips through the Second Containment Seal.
It begins as a human sound and ends as something else, an alien CRY of rage.
The CRY echoes down the Main Corridor.
DJ packs up blood samples.
He raises his head at the sound of the CRY.
Starck GASPS as the CRY resounds through the bridge.
Miller turns in the direction of the CRY.
He begins to move down the Corridor, towards the source.
Cooper examines the weld on the baffle plate.
It's solid.
COOPER Solid as a rock.
COOPER Hey, Smith...
COOPER Smith, clear that airlock, man, I'm coming in.
SMITH Roger that.
Smith carries another load of supplies.
Movement out of the corner of his eye...
He turns in time to see Weir disappear around a corner inside the Event Horizon.
SMITH Dr. Weir!
SMITH Hey, get your ass back on board!
SMITH Dr. Weir!
No response.
Smith keys the radio.
SMITH Skipper, come in...
Miller jogs down the Main Corridor.
An INTERCOM gets his attention:
SMITH Skipper...
MILLER What is it, Smith?
SMITH I just saw Weir, I think he was messing around on the Clark.
Something SPARKS and SIZZLES in the dim light, catching Miller's eye.
He looks up...
One of the EXPLOSIVE CHARGES has been removed from the its mounting in the Corridor.
MILLER Smith, get out of there...
SMITH Come again, Skipper?
MILLER One of the explosives is missing from the corridor.
MILLER I think Weir may have put it on the Clark.
Smith's eyes open wide.
MILLER Get off the Clark now and wait for me at the airlock.
SMITH No, no, we just got her back together...
MILLER Get out of there now!
But Smith has already left the airlock...
...entering the Quarters, tearing through storage lockers.
SMITH Where is it, where is it...
MILLER Smith?
MILLER Smith!
MILLER Fuck!
Miller races down the corridor towards the airlock, towards his ship...
A BEEPING sound catches Smith's attention.
He follows the sound to a storage compartment.
Rifles through it.
SMITH I gotcha...
SMITH I gotcha...
The BEEPS are coming closer and closer together.
Smith grabs a duffel.
SMITH I gotcha.
Opens it.
He sees the EXPLOSIVE CHARGE from the Event Horizon even as the BEEPS become a steady TONE.
He closes his eyes and SIGHS...
Miller enters the docking bay even as a HUGE BLAST knocks him back.
Safety doors close, sealing off the airlock and preventing loss of pressure.
The SILENT EXPLOSION tears the Lewis and Clark into two pieces, spiralling away from each other and from the Event Horizon.
Metal shards, like confetti, fill the space between them.
Cooper clings to the forward section, watching the Event Horizon recede as he tumbles into space.
His FRENZIED BREATHING is the only sound.
Miller gets to his feet.
Stares out the window upon the wreckage of his ship, spiralling away.
He hits the intercom with his forearm.
MILLER DJ.
MILLER The Clark's gone.
MILLER Smith and Cooper are dead.
DJ What happened?
MILLER Weir.
MILLER He used one of the explosives from the Corridor.
The door opens behind DJ.
The lights go out.
DJ turns...
Face to face with Weir...
Blood crusts Weir's cheekbones, his mouth.
He has no eyes.
Only clotted, empty sockets.
DJ opens his mouth to SCREAM.
Weir grabs DJ by the throat, cutting him off.
MILLER DJ, you read me?
DJ does not answer.
The CRASH of glass and steel resonates over the intercom.
Too dark to see...
glimpses of violent motion in the stainless steel cabinets...
the sounds of STRUGGLE continue...
...then something WET...
and the struggle stops.
MILLER DJ?
MILLER DJ, come in...
Finally, Weir emerges from the gloom.
He searches among the surgical instruments until his blood caked hands find a needle...
and thread...
Miller, at the intercom.
He tries another channel.
MILLER Peters...
Peters body lies before the Core.
The intercom CRACKLES.
MILLER Peters, are you there?
MILLER Starck, do you read me?
MILLER Starck...?
But it is Weir who answers.
His voice sounds thick, choked with dirt.
WEIR I told you...
WEIR She won't let you leave...
MILLER Son of a bitch!
Miller yanks open a storage locker full of zero-G tool.
Lifts a nailgun.
Chambers a round.
Cooper watches the Event Horizon fall farther and farther away.
He checks his oxygen gauge.
One tank full, one tank at half.
Cooper twists his backpack around, giving him access to the oxygen tanks.
He seals off his primary hose and disconnects the full tank.
His gauge immediately goes to "Yellow - Reserve."
Cooper points the full tank away from the Event Horizon and
The blast of pressurized air pushes him towards the ship, leaving the wreckage of the Lewis and Clark behind.
Miller races through the corridors to Medical...
...and finds DJ, suspended above the table, neatly dissected.
His organs have been laid out carefully before him on the steel table.
MILLER Oh my God.
DJ raises his head.
DJ Please...
MILLER Oh, God, DJ, what do I...
MILLER how do
DJ Please...
DJ kill...
MILLER Oh God...
Miller raises the nailgun with trembling hands.
FIRES.
Miller approaches the door to the Bridge.
It is open...
Miller stands in the doorway.
A figure sits at the helm.
Miller aims the nailgun.
MILLER Weir.
The figure doesn't move.
Miller slowly circles around the helm...
It's Starck.
Bound with wire in a sadomasochistic pose, unconscious.
MILLER Hold on...
MILLER Get you outta these...
Miller kneels in front of her, puts down the nailgun, loosens the cords.
She BREATHES in ragged gasps, opens his eyes...
Then stops.
She stares over Miller's shoulder like a deer caught in the headlights.
Miller looks behind him...
Miller reaches for the gun...
Weir hits him, sending Miller across the bridge into a bulkhead.
Weir picks up the nailgun, examines it.
Miller slowly gets to his feet.
MILLER Your eyes...
WEIR I don't need them anymore.
WEIR Where we're going, we won't need eyes to see.
MILLER What are you talking about?
WEIR Do you know what a singularity is, Miller?
WEIR Does your mind truly fathom what a black hole is?
WEIR It is NOTHING.
WEIR Absolute and eternal NOTHING.
WEIR And if God is Everything, then I have seen the Devil.
WEIR It's a liberating experience.
With his free hand, Weir reaches for the navigation console.
Flips a series of switches with gore caked fingers.
The display lights up.
COMPUTER Gravity drive primed.
COMPUTER Do you wish to engage?
MILLER What are you doing?
Weir grins as he flips the final switch.
COMPUTER Gravity drive engaged.
COMPUTER Activation in T-minus ten minutes.
Miller lunges for the nailgun.
Weir raises the nailgun to point at Miller's face.
Miller slowly backs away.
MILLER If you miss me, you'll blow out the hull.
MILLER You'll die too.
WEIR What makes you think I'll miss?
Miller sees something out of the corner of his eye...
Cooper.
Outside, braced in the viewport bracket.
Weir spins and FIRES at Cooper.
The nail lodges in the thick quartz glass.
A web of cracks spreads out from the bullet, the glass SHRIEKING under the pressure.
Weir takes a step towards the window, raises the gun to fire again.
Miller dives for the door.
Before Weir can fire,
EXT. EVENT HORIZON - BRIDGE WINDOW (HANGING SECTION) the window EXPLODES outward.
The ship HOWLS as air rushes out, ripping Weir off his feet.
Weir catches himself in the broken window, trying to pull himself back in...
A monitor tears free, SMASHES into him.
HE IS SUCKED OUT.
Miller pulls himself through the door as it begins to shut.
He is safe...
STARCK Don't leave me!
Miller turns.
Starck clings to a console, barely able to resist the winds that try to suck her into the void.
STARCK Please...
STARCK help, help me...
Miller hesitates, looking from Starck back into the safety of the ship.
The door continues to shut.
In seconds, he will be safe.
And she will be dead.
Miller YELLS and rips a compressor from its mount, wedges it in the door to keep it open.
He keeps one hand on the door, reaches the other hand to Starck.
MILLER Give me your hand!
MILLER Your hand!
She does.
Frost forms on their bodies as the air cools.
Their veins begin to bulge, blood pulses from their noses.
He YELLS with exertion...
...drags her to the door...
through the door...
...as the compressor tears free, sucked into space...
...and the door SNAPS shut, missing them by a fraction.
Starck and Miller collapse against the door.
A moment passes between them.
Just happy to be breathing...
...and then the AIRLOCK KLAXON goes off.
MILLER The forward airlock.
Starck and Miller race towards the Forward Airlock Bay.
They enter, see a humanoid shape moving in the strobing light of the airlock.
STARCK Weir can't be alive.
MILLER Whatever was on that bridge wasn't Weir.
Miller looks around for a weapon.
Pulls a zero-G bolt cutter from the wall.
Wields it like a bat.
MILLER Stay behind me.
The inner airlock door releases with a HISS.
Swings open...
Cooper tumbles through, clawing at his helmet.
STARCK Cooper!
Starck rushes to him, takes his helmet off.
He SUCKS air in, COUGHS it out.
COOPER Let me breathe, let me breathe...
STARCK You're okay now, it's over...
MILLER It's not over.
MILLER It's just starting.
Starck follows Miller's gaze to a workstations's flashing display: GRAVITY DRIVE ENGAGED.
ACTIVATION 00:06:43:01...
MILLER Weir activated the drive.
MILLER He's sending us to the Other Place.
STARCK We've got to shut it down, we've got to...
COOPER How?
COOPER The Bridge is gone.
STARCK There must be a way!
STARCK What about Engineering?
COOPER Can you shut it down?
STARCK I don't know the process, Dr. Weir was the expert...
COOPER I don't want to go where the last crew went.
COOPER I'd rather be dead.
STARCK Blow it up?
MILLER We blow the Corridor.
MILLER Use the foredecks as a lifeboat, separate it from the rest of the ship.
MILLER We stay put...
COOPER ...and the gravity drive goes where no man has gone before.
MILLER You prep the gravity couches.
MILLER I'm going to manually arm those explosives.
COOPER Will it work?
MILLER It worked for Weir.
MILLER Prep the tanks.
Cooper nods, heads for the gravity couch bay.
Starck follows Miller to the steel pressure door.
STARCK I'll do it --
MILLER No.
MILLER I'll be right back.
Miller opens the door.
MILLER Close it behind me.
MILLER Just in case.
Beat.
Starck stares at Miller as if memorizing his face.
STARCK Don't be long.
Miller smiles wanly.
The door slides shut with a dull THUNK.
Miller runs down the corridor.
Stops at a bulkhead coupling.
Kneels down to remove the cover from an explosive charge, switch it to MANUAL detonation.
Miller runs to the next coupling.
Repeats the process...
Starck and Cooper check the gravity couches.
One by one, they slide open...
COOPER I'm gonna activate the emergency beacon.
STARCK Hurry.
Cooper exits down a ladder.
Starck turns to the console, activates three gravity couches.
Behind her, two begin to fill with blue gel...
...and one begins to fill with blood...
the hint of dark shapes moving within...
Starck doesn't see it, concentrates on the console.
THUMP.
THUMP.
Starck turns.
Sees the bloody tank.
Sees something moving inside it.
She slowly crosses to the tank.
Peers at it...
HER.
WEIR.
Bone and muscle are exposed where the skin hasn't finished forming.
Starck SCREAMS and backs away.
STARCK Cooper...!
The glass BURSTS in an EXPLOSION OF BLOOD...
A corridor beneath the Gravity Couch Bay.
Cooper searches through circuit panels until he finds the EMERGENCY BEACON breaker.
He runs a by-pass, activating it manually.
The lights begins to STROBE...
DRIP.
DRIP.
A bloodstain spreads over his shoulder.
He follows the drip to the ceiling...
COOPER Starck?
No response.
He slowly moves to peer up the ladder...
...as Starck CRASHES down, bloody but alive.
COOPER What...?
STARCK Run!
She shoves him away...
Weir appears at the top of the ladder, crawling down headfirst like a spider...
Starck gets to her feet, staggers away...
Miller kneels, removing the cover from the last explosive.
Flips a switch.
A small cover pops open.
Miller reaches in, removes a RADIO
He arms the explosives.
Watches the red lights on the explosives wink on in the darkness.
He reaches for an intercom.
MILLER We're armed.
MILLER This fucker's ready to blow...
MILLER ...repeat, we're armed...
STARCK Miller, he's back, he was in the tank...
MILLER Slow down, Starck, I can't understand you, who was in the tank?
A figure seems to coalesce from the shadows behind Miller.
STARCK You have to get back here now, he's out there now, if he finds you...
The figure moves forward into the light...
Arcane runes etch Weir's face; his eyes, now restored, blaze with unholy zeal.
MILLER Who?
MILLER Who?
STARCK Weir.
MILLER He's dead...
Miller glances over his shoulder.
His jaw drops in surprise as he sees...
Weir grinning at him...
then SMASHES the intercom with his fist, cutting off Starck's VOICE.
Miller backs away.
Weir stands between Miller and safety.
MILLER You're dead, I saw you die.
WEIR Weir is dead.
MILLER Then who the fuck are you?
WEIR Your fear.
WEIR Do you remember the Goliath, Miller?
BURNING MAN Do you remember me?
MILLER Corrick...
BURNING MAN You left me behind.
MILLER That's not true...
BURNING MAN I begged you.
BURNING MAN I begged you to save me and you did nothing.
BURNING MAN You stood there and watched me burn...
The Burning Man YELLS and raises his arm in accusation...
...and FIRE RACES OUT FROM BEHIND HIM, flowing over the walls, the ceiling, the floor, racing for Miller like a rising tide...
Miller runs.
Dead ahead, the First Containment...
Miller runs fast.
The fire is faster, flooding in behind him.
Miller dashes for the Second Seal as IT BEGINS TO CLOSE.
The fire gains on him, surrounding him.
Miller dives through the Second Seal...
...barely makes it...
...SLAMS into the engineering console.
Miller looks back at the Second Seal.
It's still open by a fraction when the fire hits it...
...SENDING A LANCE OF FLAME stabbing out towards Miller.
He rolls aside as the fire hits the console.
The console
The Second Seal shuts tight, cutting the fire off.
The paint on the Second Seal begins to bubble and scorch...
and then cools as the fire subsides.
Miller gets to his feet.
Almost allows himself to relax.
Then he sees his shadow before him, dancing in the growing red light.
He turns...
The Second Containment is a holocaust.
Fire swarms over the walls.
Burning jelly drips from Control Spikes.
The Core itself is a blazing orb; the gyroscope that holds it glows red-hot.
Miller stares at the blazing Core.
BURNING MAN Don't leave me!
Miller turns.
The Burning Man stands RIGHT BESIDE HIM.
He SMASHES Miller with a backhand that ignites Miller's clothes and sends him flying.
The detonator falls from Miller's grasp, lost beneath two feet of coolant.
Miller comes up CHOKING and SPLUTTERING.
The Burning Man stalks towards Miller.
The coolant STEAMS and SIZZLES at his feet.
Miller stares at the Burning Man as he approaches.
Slowly rises to his feet.
MILLER You're not Edmund Corrick.
The Burning Man's flames wane, revealing Weir's misshapen form.
Miller throws a wicked right.
Weir catches Miller's fist.
SQUEEZES until blood wells up between his fingers.
Then slings Miller against a cooling tank with BONE CRACKING force.
Miller collapses into the slime, barely able to raise his head to breathe.
Weir slowly approaches.
MILLER What are you?
WEIR You know.
MILLER You want me to believe you're the Devil, well, I don't, that's bullshit!
WEIR I'm not the Devil.
MILLER Then what, what are you?
MILLER Tell me...
WEIR Better if I just show you.
Weir's hands reach down and he grabs Miller by the skull.
Miller GASPS as he sees...
Faster than the eye can see.
More than mind can accept...
The ORIGINAL CREW writhe naked and bloody in carnivorous frenzy...
Peters' bloody grinning child, devouring his mother...
MILLER writhes in Weir's grip.
His hands flail out to the sides.
One hand brushes a long steel cannister sunk in the muck.
A CO2 scrubber...
DJ's dissected body, except that here, DJ looks up, and smiles...
AN ALIEN SUN, red and bloated and dying.
AN ALIEN TERRAIN; a sluggish, oily, black sea.
A hand reaches from the oil...
CLAIRE floating dead in a bathtub filled with the thick black fluid...
Justin, Starck and Cooper, crucified upside-down upon the Third Seal...
His hand closes on the scrubber and he swings it across Weir's head.
Weir reels back, stunned.
Miller gets to his feet.
MILLER You can't have them!
He hits Weir again.
HARD.
Blood gushes from Weir's skull, filling the runes on his face.
Weir staggers.
Miller attacks.
Again and again and again...
This time Weir is ready.
He catches the scrubber and tears it from Miller's grasp.
SMASHES Miller to the floor with a single blow.
Miller GROANS.
WEIR I'm not the Devil.
WEIR I'm much, much older.
WEIR I watched the Beginning and I will see the End.
WEIR I am the dark behind the stars.
WEIR I am the dark inside you all.
Miller gets to all fours, trying to get up.
MILLER ...not the Devil...
Weir kicks Miller savagely.
Miller slides through the coolant, comes to rest beneath a walkway.
He attempts to rise, collapses back into the sludge.
Weir slowly stalks towards him.
WEIR There is no Devil.
WEIR There is no God.
WEIR There is only...
WEIR NOTHING.
MILLER You're lying...!
WEIR I'm not asking you to believe me.
WEIR You'll see for yourself...
WEIR and so will your crew.
WEIR You're all coming with me.
MILLER Starck...
MILLER Cooper...
Weir's grotesque face is inches from his.
He reaches down and pulls Miller from the dripping ooze...
WEIR They are mine.
WEIR And so are you...
...as Miller clears the surface, he holds something in his fist.
Miller stares dead-on into Weir's hellish face...
...and raises his right hand.
HE'S HOLDING THE DETONATOR.
MILLER You can't have them.
MILLER Go to hell.
A small, silent EXPLOSION blossoms in the aft section of the ship...
...followed frames later by a sequence of DETONATIONS that rip the Main Access Corridor apart and propel the foredecks away from the containment section.
The EXPLOSION knocks Starck and Cooper down.
They hold on tightly as...
Waves of distortion ripple over the Event Horizon's containment section...
A dark sphere of energy spreads out from the containment as the gateway opens...
A BLACK HOLE...
The black hole begins to shrink, imploding.
As it collapses, it sucks Neptune's blue clouds with it, creating a TITANIC WHIRLPOOL with the black hole at its center...
The SHRIEKING winds carry the foredecks back towards the whirlpool, towards the black hole...
Cooper and Starck slide across the floor as the deck tips at a terrific angle...
The foredecks teeter on the edge of oblivion...
The black hole collapses utterly, vanishing to a point.
An enormous SHOCKWAVE rips out from the point of implosion.
The foredecks ride the wave away from the implosion and out of Neptune's atmosphere to safety...
The VIBRATIONS subside.
Cooper and Starck stagger to their feet.
Look out the window...
Neptune recedes, the ugly hole of the implosion already being erased by Neptune's violent winds...
Starck's voice is tiny.
STARCK Miller...
Black planets silhouetted by a dying red giant.
The Engineering Containment of the Event Horizon drifts in the eddies of gas that swirl and spiral into the bloated star.
MOVE towards the ship until its shadow consumes all...
Starck awakens but the SCREAMS continue as the Event Horizon calls out to her...
she SCREAMS...
hands on her body...
the CRIES stop...
Starck looks around uncomprehending at the faces around her.
Cooper pushes them aside.
She clings to him, CRYING...
COOPER It's over, hush now, it's over...
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
