THE TRUMAN SHOW
A Screen Play
By
Andrew M. Niccol
A white title appears on a black screen.
"One doesn't discover new lands without consenting to lose sight of the shore for a very long time."
Andre Gide
The title fades off, replaced by a second title.
"We're all in this alone."
Lily Tomlin
A fiber optic camera observes a five-month-old MALE FETUS as he gently floats, weightless, suspended in the amniotic fluid of his mother's womb.
We focus on the unborn's hand, already a tiny, exquisite work of art, moving towards his newly formed lips.
He sucks his thumb.
A seconds old BABY BOY - umbilical cord still attached, smeared with blood and protective skin grease - is held up by an anonymous pair of latex gloves to the camera.
Shocked by the unaccustomed light and cool of the delivery room, the newborn fights for his first, arduous breath.
Following almost immediately, a cry.
From another angle we see the crying infant on a television screen, the individual lines of the screen clearly visible.
The face of the baby thirty-four years later, still crying.
TRUMAN BURBANK, thinning hair, a body going soft around the edges, appearing older than his thirty-four years sits at the wheel of his eight-year-old Oldsmobile Cutlass Supreme.
He cries without shame, making no attempt to wipe away the tears.
Pausing at an intersection in a quiet, working-class suburban street, a spherical glass object suddenly falls from the sky and lands with a deafening crash on the roadway, several yards in front of his idling car.
Truman exits the Oldsmobile to investigate.
Amidst a sea of shattered glass are the remains of a light mechanism.
He looks around him but the street is deserted.
He checks that all the surrounding streetlights are accounted for, even though the fallen fixture is far larger.
He looks up into the sky but there is no plane in sight.
With some effort, Truman picks up what's left of the crumpled light, loads it into the trunk of his car and drives away.
TRUMAN sits behind the wheel of his car, unscrews the cap of a miniature bottle of Jack Daniels and empties the contents into his Styrofoam cup of coffee.
Stirring it in with his finger, he burns himself.
TRUMAN Shit!
As Truman drinks, he becomes aware of the delighted squeals of children coming from the gymnasium of Utopia Elementary School, adjacent to the parking lot.
The sound of the children triggers a memory in his head.
Unlike a conventional flashback, the scene in his memory appears to be playing on a television screen.
A sandy-haired, SEVEN-YEAR-OLD TRUMAN, runs towards a bluff on the beach.
The boy's father, KIRK, late-thirties, beer bottle in hand, flirts with two TEENAGE GIRLS at the shoreline.
Suddenly, the father remembers his son.
He looks anxiously around.
The sight of the boy at the far end of the beach causes him to drop his bottle in the sand and run to him.
The boy is near the top of the cliff before his agitated father comes within earshot.
FATHER Truman!
FATHER Truman!
FATHER Stop!
Truman turns from his perch and waves happily down to his father.
But the smile quickly vanishes when he registers the anger and distress on his father's face.
FATHER Come down now!
His father's unnatural anxiety makes the next bay even more tantalizing.
The boy considers defying his father.
He puts his hand on the rock above him to stretch up and sneak a peek at the other side.
One good stretch would do it.
FATHER No!
TRUMAN Why?
TRUMAN What's there?
FATHER Nothing's there.
FATHER It's the same as this.
FATHER Come down, please!
Truman is suddenly aware that the hundreds of other BEACHGOERS have stopped their activities to stare at him.
Reluctantly he starts to retrace his steps down the rocks.
When he finally jumps to the sand, his father grabs him roughly by the arm and drags him away down the beach.
FATHER I told you to stay close.
FATHER Don't ever leave my sight again.
FATHER You gotta know your limitations.
FATHER You could've been washed away by the tide.
TRUMAN emerges from a subway exit in Lower Manhattan and walks briskly down the bustling street.
A snarl of taxis, buses and COMMUTER traffic.
A STREET VENDOR thrusts a pretzel under Truman's nose, a CAREER WOMAN catches his eye.
Truman stops at a newspaper stand and plucks an issue of Cosmopolitan from the rack, quickly flicking through the glossy pages.
Glancing in the direction of the NEWSPAPER VENDOR and finding him busy with another customer, Truman deftly tears a portion of the open page and pockets the cutting.
He guiltily replaces the magazine, startled to find the Newspaper Vendor standing close behind him.
TRUMAN Gimme a copy of "The Sydney Morning Herald".
VENDOR We ran out.
TRUMAN Thanks anyway.
As Truman hurries away, the Vendor picks up the copy of Cosmo and instantly turns to the torn page.
It is a Lancome advertisement with ISABELLA ROSSELLINI's nose missing.
Truman is still in view but the Vendor makes no effort to confront him, almost as if he were expecting it.
Passing one of the tall, black mirrored buildings that grow out of the pavement, Truman glimpses himself in the reflective glass.
He doesn't like what he sees and attempts to suck in his gut, but quickly concedes defeat.
The image triggers another childhood memory.
Once again, the flashback appears to be playing on a television screen.
The sandy-haired SEVEN-YEAR-OLD TRUMAN sits in the middle row of a Catholic Elementary School classroom surrounded by thirty-or- so other well-scrubbed, uniformed YOUNGSTERS.
DOUGLAS, the boy next to Truman is on his feet under the scrutiny of a sixty- year-old NUN with a face as wrinkled as her habit is starched.
DOUGLAS I wanna be a chiropractor like my dad.
SISTER Tell the class what a chiropractor does, Douglas.
DOUGLAS He helps people by fixing their backs, Sister Olivia.
SISTER That's right, Douglas.
SISTER Perhaps I'll be your first patient.
The CLASS titters.
Douglas sits down, pleased with himself, throwing a smirk to Truman.
SISTER What about you, Truman?
Truman rises to his feet.
TRUMAN I want to be an explorer
TRUMAN ...like Magellan.
The Sister's face falls.
SISTER No one's going to pay you to do that, Truman.
SISTER Besides, you're too late.
SISTER There's nothing left to explore.
The class roars with laughter and Truman takes his seat.
From TRUMAN'S POV we see that he is staring up at relief letters that proclaim, "American Life & Accident Insurance, Inc."
above an office building's entrance.
A POLICE OFFICER walking his beat, wanders in Truman's direction.
From another angle, we observe Truman from the Police Officer's POV - shaky, handheld camera - on a television screen.
Truman enters the building.
In a cramped, cluttered, windowless cubicle, TRUMAN talks on the telephone.
TRUMAN ...okay, okay, let's call it what it is...
TRUMAN I'm not gonna lie to you...life insurance is death insurance...you just gotta ask yourself two questions...one, in the event of your death, will anyone experience financial loss?...and two, do you care?
A CLERK drops a large reference book on Truman's desk.
He checks the spine - "MORTALITY STATISTICS, 1986 to Present".
TRUMAN Hold on will ya?
TRUMAN This's no good.
TRUMAN Lumps all drownings together.
TRUMAN I need drownings broken down by category.
The Clerk shrugs, returns the book to his trolley and continues his rounds.
TRUMAN ...just think about what I've been saying and lemme...hello?...
The person on the other end has hung up.
With an apathetic shrug, Truman replaces the receiver.
He looks over his shoulder and places another call.
TRUMAN Can you connect me with directory inquiries in Sydney, Australia?
TRUMAN ...er, yes.
TRUMAN Do you have a listing for a Lauren Powers...
TRUMAN ...nothing listed?...what about a Sylvia Powers...nothing?
TRUMAN Thanks...
Truman replaces the receiver, disappointed.
TRUMAN stands in line with a crush of other WHITE COLLAR WORKERS.
As he reaches the counter, the store owner, TYRONE, has anticipated his order and ahs already begun preparing a meatball and mozzarella sandwich on Italian roll.
Truman gazes at the sandwich skillfully under construction, pained by his own predictability.
TYRONE How's it goin', Truman?
TRUMAN Not bad.
TRUMAN I just won the State Lottery.
TYRONE Good.
TYRONE Good.
TRUMAN Tyrone, what if I said I didn't want meatball today?
TYRONE I'd ask for identification.
Truman forces a half-smile.
We focus on another MALE OFFICE WORKER in line at the cash register, watching Truman out of the corner of his eye.
About to depart with his sandwich, the man receives a guarded rebuke from the FEMALE CASHIER.
FEMALE CASHIER He's right there.
FEMALE CASHIER You're supposed to pay when he's here.
MALE CUSTOMER He never notices.
We re-focus our attention on Truman who is taking the wrapped sandwich from Tyrone.
TYRONE Hold on, Truman.
TYRONE I got somethin' to show ya.
Tyrone holds up a front page of the New York Post that features a photograph of a scaled-down replica of Columbus' Santa Maria, moored in front of the Manhattan skyline.
Truman's eyes widen at the photograph.
TYRONE The flagship of Christoforo...our Genoese navigator, huh?
TYRONE I know you love this like me.
TRUMAN Not me.
TRUMAN You got the wrong man.
Tyrone tries not to let his disappointment show as Truman pays the Cashier and exits.
TYRONE See ya tomorrow, Truman.
TRUMAN eats lunch alone on a concrete bench in a cement park.
From his briefcase he pulls out an old hardcovered book, "To The Ends Of The Earth - The Age Of Exploration".
A TRANSIENT in a wheelchair approaches, looking for a handout.
Truman gives the homeless man half of his sandwich, reconsiders and gives him it all, his appetite gone.
As the transient wheels himself away, Truman loses himself in his book.
Close up on an old man's face.
CHRISTOF.
Hair pure white, late-sixties, a vitality in his eyes that belies his years.
He stands beside a floor-to-ceiling window in a dimly-lit room.
Outside the window, a single palm tree swaying against a deep blue Californian sky.
A news anchor-style earpiece disappears down the neck of the unconventionally-cut suit he wears.
Suspended from the ceiling above his head is a television monitor upon which a surveillance picture of Truman, engrossed in his book, silently plays.
CHLOE, twenty-something, androgenous-looking, similarly-suited, joins Christof at the window.
CHRISTOF You ever pass a car wreck on the side of the road?
CHRISTOF They're pulling out a body.
CHRISTOF You know you shouldn't look, but you do.
A group of a dozen MEN and WOMEN of varying ages sit around a circular conference table in a sterile, windowless meeting room.
All stare at a single telephone placed in the center of the table, anticipating a call.
On cue, the phone rings and one of the men, after waiting for the second ring, picks up.
MAN Hello?...I'm sorry, I got more than enough insurance.
He hangs up.
After a moment the phone rings again.
TRUMAN sits at his desk, making a cold call.
TRUMAN ...this isn't about insurance, this is about the great variable - when will death occur?
TRUMAN Could be a week, a month, a year.
TRUMAN Could happen today...A sunbather, minding his own business, gets stabbed in the heart by the tip of a runaway beach umbrella...No way you can guard against that kinda thing, no way at all...
The prospect on the other end, unimpressed with his pitch, hangs up.
Truman's supervisor, LAWRENCE, younger than Truman by several years, sharper suit, sharper haircut, appears around the corner of the cubicle.
LAWRENCE Hey, Burbank, I got a bridge-buyer in Stapleton I need you to cloes by four.
Truman turns pale.
TRUMAN Stapleton on Staten Island?
LAWRENCE You know another one?
TRUMAN I can't do it.
LAWRENCE A half hour across the bay.
LAWRENCE Sea air.
LAWRENCE Do you good.
TRUMAN No, I...
TRUMAN ...I got an appointment uptown.
LAWRENCE This is a sure thing.
LAWRENCE They're upping our quota.
LAWRENCE You need this.
Lawrence exits the cubicle.
Truman's head drops.
He picks up the framed picture of his wife from his desk.
MERYL, early thirties, a petite woman easy to mistake for frail.
He deposits the photo in his briefcase and departs.
TRUMAN, briefcase in hand, ashen-faced, stands in line for the Staten Island ferry.
As the TOURISTS and COMMUTERS impatiently brush past him onto the boat, Truman remains frozen to the spot, mesmerized by the scummy water rising and falling beneath the dock, triggering a flashback in his head.
The flashback once again appearing an a television screen, the SEVEN-YEAR-OLD TRUMAN sits alongside his father, KIRK, in a small sailing dinghy.
TRUMAN Let's go further, daddy!
TRUMAN Let's go further!
FATHER It's getting late, Truman.
TRUMAN Please!...
Kirk shakes his head ruefully and indulges his son by heading towards the gathering storm clouds on the horizon.
TRUMAN turns and begins to fight his way back against the tide of PASSENGERS boarding the ferry, emerging back on the street into the bright sunlight, gasping for air.
Gathering himself, he makes for the entrance of Whitehall Street subway station.
Two COMMUTERS surrepticiously observe Truman as he departs.
COMMUTER 1 I can't believe he's taking the long way.
COMMUTER 2 He'll never make it.
TRUMAN stands in a packed subway car, anxiously glancing at his watch, wiping his perspiring hairline with a hankerchief.
A taxi crosses the Verrazano-Narrows Bridge towards Staten Island.
TRUMAN keeps his eyes shut tight all the way across.
refusing to look down at the entrance to New York harbor.
TRUMAN finally reaches his destination at a well-to-do condominium on Bay Street.
As he approaches the lobby, he realizes he has perspiration showing through the armpits of his suit jacket.
A middle-aged CONCIERGE behind a reception desk, is having his hair brushed by a YOUNGER MAN in his mid-thirties.
Anticipating Truman's arrival, the hairdresser fusses one more time and swiftly departs through a rear door.
TRUMAN enters the lobby and approaches the CONCIERGE, trying to keep his arms tightly at his sides to hide the perspiration.
TRUMAN I'm here to see a Mr Hamilton.
CONCIERGE You from the insurance company?
CONCIERGE You missed him.
TRUMAN When will he be back?
CONCIERGE Vacation.
CONCIERGE Two months.
CONCIERGE He waited as long as he could.
CONCIERGE You was supposed to be here by four.
A clock on the wall reads 4.l2pm.
TRUMAN sits by himself in the rattling subway car, defeated.
The only other occupants in the train, a TALL WOMAN, mid- thirties, reading a pulp novel and two MALE YOUTHS, late-teens, sitting opposite the woman, slouching, ogling her.
YOUTH 1 You wanna read to me?
His companion smirks.
YOUTH 1 You wannna read to me?
The woman looks up, unaware of the boys' presence until now.
She quickly avoids eye contact and returns to the book.
The other boy reaches over and snatches the novel from her grasp.
YOUTH 2 My friend asked you a question.
The woman picks up her bag from the floor in a reflex and holds it to her.
She looks around the train for assistance, briefly catching Truman's eye.
The youths also look in Truman's direction, staring him down, daring him to interfere.
Truman quickly averts his gaze.
WOMAN Please...
The boy returns the book to the woman, but before doing so rips out the last page from the novel and stuffs it in his shirt pocket.
YOUTH 2 Now you're gonna have to ask me how it ends.
The train pulls into a deserted station.
Feeling vulnerable, the woman jumps up from her seat and exits.
The youths, sensing a chase, also exit.
Scanning the empty platform, the woman realizes she has made a serious error.
Truman watches through the train's open door as the boys corner the frightened woman but still he remains in his seat.
YOUTH 1 We're gonna tell you how it ends, baby.
One of the youths produces a knife from his pocket and waves it in the woman's face.
YOUTH 2 Don't you wanna know how it ends?
The boys pin the woman to the station wall with the weight of their bodies.
The woman looks again in Truman's direction.
Again she makes eye contact, eyes pleading.
WOMAN Help!!
WOMAN Please, help!!
The woman's second scream is muffled as the train door closes.
Truman looks up to the emergency handle beside the door.
There is still time to act.
He stands up and half-reaches for the handle but moves no further.
The train abruptly pulls away, leaving Truman time to see one of the youths covering the woman's mouth while the other reaches under her skirt before the train enters the tunnel.
Truman bows his head in shame as the train rattles on.
The train safely out of sight, the YOUTHS promptly release the WOMAN.
She calmly hitches down her skirt, no longer afraid.
The young men, no longer angry, help fix her hair and retrieve her shoulder bag.
WOMAN Thanks.
The threesome walk along the platform together, as if lifelong friends.
WOMAN He did nothing.
YOUTH 1 Physical violence paralyzes him.
YOUTH 1 Always has.
The backyard of a modest but tidy one-story tract home.
Beyond the plank fence at the end of the property flows a busy Expressway.
TRUMAN wheels a lawnmower towards the garage as his wife, MERYL, pulls up the drive in her four-year-old Toyota Camry.
She has a sensible blue vinyl bag over her shoulder and carries a new knife-set in a wooden block.
She kisses Truman affectionately on the cheek.
MERYL I got it free with the tune-up.
Looking over Truman's shoulder, she notices a small uncut patch of grass, missed by Truman in one of his passes.
MERYL You missed a section.
Meryl enters the house.
Truman restarts the lawnmower and obediantly pushes it towards the offending patch of lawn.
As the mower brushes up against the unconforming blades of grass, Truman pulls back abruptly.
He checks the kitchen window for Meryl and wheels the mower away, leaving the patch uncut.
MERYL is applying ointment to her wrists as TRUMAN enters.
TRUMAN Do they hurt?
MERYL I was afraid I'd seize up during cross.
MERYL One of the keys kept sticking.
Truman picks up Meryl's newspaper and skims idly through it.
He notes an article headlined, "SLAYING TRIAL ENTERS SIXTH WEEK".
TRUMAN Is he gonna take the stand?
MERYL No point.
MERYL Two eye witnesses saw him near the dumpster where they found the legs.
She flexes her arthritic wrists.
MERYL You gonna eat before you leave?
TRUMAN I'll get something out.
MERYL Did something happen today?
Truman turns to her too sharply, his guilt showing.
TRUMAN What could happen?
An abandoned freeway project in Queens.
The four hundred yard stretch of deserted freeway is paved but unmarked.
At one end is an off-ramp that abruptly ends in inid-air, reinforcing steel protuding from the concrete.
TRUMAN stands at the end of the off-ramp with MARLON, thirty- two, the kind of physique some descibe as fat, others big.
Marlon drinks beer from a can while Truman addresses a teed-up golf ball with a number three wood.
Truman winds up and swings, making a healthy contact with the ball.
The ball arches away into the night sky, lit by the adjacent operating roadway.
From a new angle we see the ball take a huge hop on the outside lane of the abandoned freeway and continue down the asphalt.
Marlon tosses Truman another ball from a bucket of badly scarred golf balls - a ball initialed with the letter, "T".
Truman sets the ball up on the makeshift tee area and launches himself into his second shot.
With a slight fade, the second ball carries even further than the first.
Truman hands Marlon their sole golf club without comment.
Marlon is still looking admiringly in the direction of the shot.
MARLON Ouch.
MARLON Whose nuts were those?
TRUMAN Mine.
Marlon tees up a ball of his own.
initialed with the letter "M".
TRUMAN I gotta get out, Marlon.
MARLON Yeah?
MARLON Outta what?
TRUMAN Outta my job, outta Queens...out!
Marlon takes a practise swing.
MARLON Outta your job?
MARLON What the hell's wrong with your job?
MARLON You gotta great job.
MARLON You gotta desk job.
MARLON I'd kill for a desk job.
Marlon addresses the ball and swings.
A sweeping hook shot that bounces off the freeway out of bounds.
MARLON Sonofabitch.
TRUMAN It doesn't mean anything.
MARLON Nothing means anything.
MARLON Try stocking vending machines for a living.
MARLON My biggest decision of the day is whether the Almond Joys look better next to the Snickers or the Baby Ruths.
Truman selects another "M" ball from the bucket and tosses it to Marlon.
TRUMAN I gotta get out.
Overcompensating with his second shot, Marlon slices the ball in the other direction.
A lucky bounce keeps it on the cement fairway.
MARLON Sure and go where?
Truman gulps his beer as he prepares his answer.
TRUMAN Australia.
MARLON No shit.
MARLON Where is Australia exactly?
MARLON Near England?
Truman picks up a golf ball to demonstrate.
He points to a dimple on his make-shift globe.
TRUMAN See here, this is Queens.
TRUMAN All the way round here, Australia.
TRUMAN You can't get any further away before you start coming back.
TRUMAN Y'know, there're still places in Australia where no human being has ever set foot.
MARLON So when are you leaving?
TRUMAN It's not that simple.
TRUMAN Takes money, planning.
TRUMAN You can't just up and go.
TRUMAN Oh, I'm gonna do it, don't worry about that.
TRUMAN I just gotta move slow.
TRUMAN Pick a moment.
TRUMAN Bonus time's just around the corner.
TRUMAN Soon as I get a retaining wall built on the back of the house I can start thinking about selling up...and I'll be gone.
TRUMAN Up and away on that big steel bird.
TRUMAN I'm going, don't you worry about that.
Marlon nods even though the concept of taking flight is beyond his imagination.
MARLON I never knew anybody who got out.
An awkward moment.
Truman, once again, not so sure of himself.
He masks his doubt by teeing up another ball.
TRUMAN and MARLON wander down the empty freeway, retrieving the golf balls.
As they return them to the bucket they check the initial on each ball to determine the winner of their long-drive competition.
TRUMAN Tick-fucking-tock.
TRUMAN That's the fucking problem, Marlon.
TRUMAN I'm thirty-four.
TRUMAN I'm older than Jesus Christ.
Marlon looks sideways at Truman.
It sounds to him like the beer talking.
TRUMAN Where do the dreams go, Marlon?
MARLON You win.
TRUMAN I'm serious.
TRUMAN Where do the dreams go?
MARLON They're still there.
MARLON Just buried under what we settled for.
They approach Truman's Oldsmobile.
Truman opens the trunk to deposit their humble golfing equipment.
Inside are the remains of the fallen light fixture.
TRUMAN You really think it could've dropped off an airliner?
MARLON Sure.
MARLON It's halogen.
MARLON You oughta report it.
MARLON You coming for a drink?
TRUMAN I can't tonight.
The lines of a television screen signal another of Truman's flashbacks.
A small group of MOURNERS in black, several openly weeping, stand on the end of a small jetty, including the SEVEN- YEAR-OLD TRUMAN, dry-eyed in an ill-fitting suit, his weeping MOTHER, older sister, RAQUEL, and a PRIEST at the head of the gathering.
The priest nods to Truman who holds an ornate wreath, heavy and cumbersome in his tiny hands.
He heaves it off the dock.
A smaller, more simple wreath lands on the calm, dark water beyond the jetty twenty-seven years later.
TRUMAN stares at the wreath for a long moment, turns and wanders back towards the shoreline.
In his work suit minus his shoes and socks, he sits on the sand.
He has a portable tape recorder slung over his shoulder and points a corded microphone at the surf.
For a long while we watch Truman's impassive face as he makes the recording of the lapping waves, staring up at the handful of stars visible through the gloom.
We focus on the lantern room of a nearby lighthouse.
From the light's POV, through the green hue of a night vision camera, we observe Truman get to his feet and walk towards the dark water.
TRUMAN I'm sorry!
TRUMAN I'm sorry!
CHRISTOF's dispassionate face is reflected in the screen of a television monitor that displays the distraught TRUMAN at the water's edge.
At the Formica kitchen table, TRUMAN makes calculations in a school notebook, a bottle of beer close at hand.
MERYL appears in her robe, a glimpse of black negligee beneath, restless.
She throws her arms around Truman's neck.
MERYL What are you doing?
MERYL Come to bed.
TRUMAN I figure we could scrape together eight thousand.
MERYL Oh.
MERYL God, everytime you and Marlon--
TRUMAN --We could bum around the world for a year on that.
MERYL And then what, Truman?
MERYL We'd be back to where we were five years ago.
MERYL You're talking like a teenager.
TRUMAN Maybe I feel like a teenager.
Getting to his feet.
Truman holds Meryl by the arms, talking excitedly to her the way we imagine he did when they were courting.
TRUMAN Meryl, it'd be an adventure.
MERYL We said we'd try for a baby.
MERYL Isn't that enough of an adventure?
TRUMAN That can wait.
TRUMAN I want to get away.
TRUMAN See some of the world.
TRUMAN Explore.
Meryl gives a derisive laugh.
MERYL You want to be an explorer?
MERYL You mean like all the other great explorers from Queens?
MERYL You don't even have a passport, Truman.
MERYL I bet you don't even know how to get one.
The words sting.
Truman turns away.
Seeing the pain she's caused, she changes tack.
MERYL This'll pass.
MERYL Everybody thinks like this now and then.
MERYL Come to bed.
In a nightwatchman's office, two UNIFORMED GUARDS drink coffee.
GUARD 1 How can they have a child?
GUARD 2 It's not gonna be his, you idiot.
GUARD 1 Why not?
GUARD 2 You think she'd go through with it?
GUARD 2 Guess I always thought they'd adopt.
TRUMAN stands in the darkened bedroom in his Hanes underwear looking down at his bed.
MERYL has fallen asleep waiting for him, snoring lightly.
Truman rests his hand tentatively on the bed.
The surface rocks.
A waterbed.
The motion triggers a flashback in his head.
As always the flashback appears to play on a television screen.
The SEVEN-YEAR-OLD TRUMAN sits on the upturned hull of a small dinghy in calm, deep water.
TRUMAN Daddy!!...Daddy!!...
His cries go unanswered.
Two OLD WOMEN, seventies, sit beside wach other on a sofa against a bare wall, looking directly into camera as they talk.
Nothing else of the room is seen.
OLD WOMAN 1 It left him with more than his obvious fear of the water.
OLD WOMAN 1 It's as if he felt his father had gone beyond his limitations and he vowed never to repeat the mistake.
OLD WOMAN 1 He was never the same curious little boy again.
OLD WOMAN 2 We're all born with a pound of cocaine up our nose.
OLD WOMAN 2 By the time we're eleven it runs out.
OLD WOMAN 1 Half the people I knew named their babies after him.
TRUMAN emerges from the subway station and as usual stops at the newspaper stand.
He picks up a copy of Vogue and flips through the glossy cosmetic ads, surreptitiously tearing CLAUDIA SCHIFFER's nose from one of the pages.
He returns the magazine to the rack and begins his daily pilgrimage to work through the rush hour pedestrian traffic.
Pausing to check his profile in the mirrored building, he glimpses the reflection of a HOMELESS MAN standing directly behind him.
Truman, spellbound by the man, suddenly wheels around to face him.
The Homeless Han is in his late-sixties.
more well-groomed and well-fed than the average vagrant, with a serene smile on his face.
From a new angle we see a two-shot of Truman and the Man on a television screen.
The Homeless Man places his hand ever so gently on Truman's cheek.
Truman makes no effort to withdraw.
He is transfixed by the the man's eyes.
He appears to recognize him.
TRUMAN Daddy...
Suddenly a distinguished OLD WOMAN walking a small dog and a YOUNG MALE BUSINESS EXECUTIVE carrying a briefcase, walking in opposite directions along the sidewalk, grab the Homeless Man, one taking each arm.
A bus suddenly screeches to a halt beside the struggling group, doors already open, and before Truman can react, the Old Woman and the Young Executive force the Homeless Man onto the bus.
Truman lurches after them, but he is met by the bus doors, closing sharply in his face.
TRUMAN Hey, stop!
TRUMAN Stop!!
Truman thumps against the doors, but the BUS DRIVER ignores his cries and the bus roars away from the curb.
He starts to run after the bus, colliding with several PEDESTRIANS who make no attempt to avoid him.
Stepping blindly into the street, he tries to hail a taxi.
A vacant cab suddenly switches off its "FOR HIRE" light as he reaches it.
Truman pleads with the TAXI DRIVER through the closed windows and locked doors of the cab but the driver is apparently oblivious to Truman's shouts.
Frantic, Truman, dashes into a nearby parking structure and grabs a bunch of car keys from the key rack of the unsupervised parking attendant's kiosk.
Running along the rows of parked cars, Truman desperately presses the car security buttons attached to the key rings
A car alarm chirps and Truman turns in time to see the car's winking sidelights.
He jumps inside a brand new BMW and guns the car.
The PARKING ATTENDANT, alerted by the squealing tires, appears from the Men's Room and attempts to wave Truman down.
ATTENDANT Hey!
Truman ignores the attendant and accelerates into the street without looking, causing a taxi and a postal van to take evasive action.
Catching sight of the bus in the distance, Truman leans on the car's horn as he recklessly weaves past other motorists.
He is only a couple of car-lengths from the bus.
TRUMAN Two, four, oh, six.
Suddenly the taxis and cars directly in front of him start to slow for no apparent reason.
Truman looks for a way around but the cars crab across the street, blocking any passage, working together almost as if they are running interference.
TRUMAN Outta the way!
TRUMAN Outta the way!
The bus is escaping.
Truman suddenly jumps the sidewalk in the car, scattering
The same cars on the street that seemed intent on slowing his progress suddenly accelerate in unison, anticipating his move.
By the time Truman reaches the end of the sidewalk, the cars are clustered together on the corner in an impenetrable jam.
Truman spies the bus turn the corner at the far end of the street and disappear from view.
Fumbling with the gear stick.
he finally finds reverse but turns to find a hostile group of PEDESTRIANS herded tightly together behind the car, leaving Truman with nowhere left to go.
The car door is suddenly jerked open and the out-of-breath PARKING ATTENDANT yanks Truman from the driver's seat.
ATTENDANT What the fuck are you trying to pull?!
TRUMAN I'm sorry!
TRUMAN I'm sorry!
TRUMAN No harm done!
TRUMAN No harm done!
ATTENDANT I oughta fuck you up!
The Attendant looks into Truman's terrified eyes.
They get the better of him.
ATTENDANT Get the fuck outta here.
The Attendant shoves Truman's briefcase into his arms and brushes him aside.
As he departs, Truman notices that the traffic jam in the street and the mysterious crowd of pedestrians has dissolved.
Row after row of parked buses.
TRUMAN and MARLON exit an administration office.
Instead of heading for the exit, Truman begins marching down the first row of buses, inspecting the number painted on the rear of each one.
MARLON What're you doing?
MARLON The man told you there's no such bus.
TRUMAN He's lying.
TRUMAN Two, four, oh, six was definitely the number.
Marlon stops walking.
Truman continues his inspection.
Seeing there is no reasoning with him, Marlon hurries to catch him up.
TRUMAN I never believed he was dead.
MARLON C'mon, Truman, a lotta times they don't find a body.
MARLON You know what the currents are like in that water.
TRUMAN You had to see his face when that wave hit.
TRUMAN He wasn't scared Marion.
TRUMAN It was like he was expecting it, waiting for it.
TRUMAN He knew it was coming.
MARLON Why would he fake it?
MARLON He's not Elvis Presley.
TRUMAN You know what was really strange about today?
TRUMAN An old woman with a little dog and a businessman, walking in opposite directions on the sidewalk, both react like clockwork.
TRUMAN They force him onto a bus against his will, a bus that doesn't normally stop outside my building.
TRUMAN And when I'm giving chase, the bus never makes another stop and I get the feeling that the traffic and the pedestrians are working together to make sure I never catch up with it.
MARLON Oh, so now it's also the pedestrians and the buses and the cars?
MARLON What are you saying, the entire population of Lower Manhattan is conspiring to stop you finding out that your father staged his death to pursue a life as a street person?
MARLON Oh yeah, that makes sense.
Truman has no answer.
We see an aerial shot of Truman and Marlon on a television screen, continuing to check the rows of buses, Marlon still marveling at Truman's obstinance.
They have come to the last bus in the final row.
Truman hangs his head.
The offending bus is not amongst them.
He makes towards the exit without comment and Marlon follows.
Unseen by the pair, we focus on the ID number on one of the buses they have previously checked - "2400".
A single drip of black paint trickles off the last freshly painted digit.
TRUMAN and MARLON, drinking beer, sit in the rear doorway of Marion's delivery van, wholesale-sized boxes of candy stacked behind them.
TRUMAN You think I imagined it, don't you?
MARLON I think you're missing your dad.
MARLON The anniversary was yesterday, wasn't it?
Truman is surprised Marlon remembered.
Marlon nods to the sidewalk.
MARLON You got sand in your cuffs.
Truman looks down at his feet.
A small, tell-tale pile of sand has poured out of his tight trouser cuff.
TRUMAN Maybe you're right.
TRUMAN If only the old woman hadn't left her dog behind.
We see a flashback in Truman's head of the earlier scene in the Lower Manhattan street.
It confirms that the old woman's DOG was abandoned on the sidewalk.
TRUMAN stands in the corridor of his mother's cramped, fussy.
doilyed apartment with his older sister, RAQUEL, late forties, prematurely grey.
Through a doorway, the figure of his MOTHER is visible asleep in bed, despite the early hour.
Truman and Raquel speak in hushed tones to avoid waking her.
RAQUEL Don't you dare go in.
RAQUEL Truman.
RAQUEL I just got her off to sleep.
TRUMAN It was Dad.
TRUMAN I swear.
Raquel fixes Truman with a contemptuous stare.
RAQUEL Well, the next time he shows up.
RAQUEL bring him over.
RAQUEL Until then, I'm not saying a word about this to Mom and neither are you.
TRUMAN If it wasn't him, it was his twin.
TRUMAN Can you think of a reason he'd want to hide from us?
RACQUEL I know a reason he'd want to hide from you.
RACQUEL Look at how you treat us.
RACQUEL You live ten minutes away, we hardly see you from year to year and then you turn up with this story so insane you don't even believe it yourself.
RACQUEL Haven't you hurt her enough, Truman?
RACQUEL She already blames you.
TRUMAN I was seven years old!
RAQUEL But you're here and he's not.
RAQUEL Has it really taken you this long to invent a story to ease your conscience?
TRUMAN I'm telling you he's alive!
RAQUEL And I'm telling you he's fish food!
Truman meets her unforgiving eyes.
Without another word, he walks out of the apartment.
Truman safely departed, the figure in the bed, rolls out.
CHRISTOF, fully clothed, relishing the danger of being so close to Truman without being detected.
Raquel's demeanor immediately changes, all trace of bitterness gone from her face, she appears younger, posture more upright, almost a different person.
Christof hugs Raquel.
CHRISTOF You did well.
A cavernous dressing room contains a long row of identical mirrored make-up tables.
At the only occupied table, Truman's contrite father, KIRK, is having what's left of his homeless disguise cleaned from his face by a MAKE-UP ARTIST under the watchful eye of two DARK-SUITED BODYGUARDS.
From a mezzanine floor out of Kirk's vision, CHRISTOF and CHLOE also take in the proceedings.
Behind their heads, a monitor shows a surveillance picture of an agitated TRUMAN sitting in his car, trapped in rush-hour traffic.
CHLOE We've tightened security.
Christof nods indifferently, knowing the damage is already done.
CHLOE Why would he do this to us?
CHRISTOF Old age.
CHRISTOF Sentiment.
CHRISTOF You play someone's father all those years, you are someone's father...He sees the way Truman is.
CHRISTOF He feels responsible.
Christof turns and enters an office adjacent to the balcony, containing a state-of-the-art monitor and VCR.
Chloe follows.
Christof plays the cued recording without comment.
We focus on the screen.
A younger-looking CHRISTOF sits in a motorboat in the calm water of Long Island Sound.
Truman's father, KIRK, twenty-seven years younger and a DARK HAIRED BOY, Truman's age at the time, acting as a stand-in, sit in the stern of a sailing dinghy.
Two SCUBA DIVERS in the ocean.
YOUNG CHRISTOF ...as soon as we give the cue, tack to windward...
Kirk rehearses turning the tiller in the instructed direction.
YOUNG CHRISTOF The freak wave will strike from the starboard side.
YOUNG CHRISTOF Remember, you don't go to the diver.
YOUNG CHRISTOF The diver goes to you.
To simulate the wave, one of the divers puts his full weight on the side of the dinghy to capsize it.
Kirk and the boy are tossed into the water.
While the boy immediately bobs to the surface in his life jacket, Kirk fails to surface.
After a long moment, he reappears with the second diver some distance away.
now wearing a spare aqualung.
YOUNG CHRISTOF ...Good!
YOUNG CHRISTOF Good!...of course, on the day you only surface once you're safely beyond the cove...Try it one more time...You okay?
Kirk is staring at Truman's stand-in, clinging to the upturned boat.
Kirk's expression suggests he is not a totally willing participant in the masquerade.
The present-day Christof freezes the monitor on Kirk's uncertain face.
A cluttered garage, dimly lit by a single work lamp.
TRUMAN looks over his shoulder before turning his attention to a dusty trunk under a canvas sheet.
The trunk is fastened with a combination lock.
He deftly dials the correct combination and opens the lid.
Inside, mementoes from his youth.
A "HOW TO SAIL" book, a stack of "GREAT EXFLORERS" magazines, and beneath it all, a garment in a drycleaning bag.
Truman carefully lifts up the plastic to reveal a schoolgirl's lavender cardigan decorated with pearl beading.
He puts the cardigan to his nose and breathes deeply.
Footsteps.
Truman hastily drops the cardigan in the trunk and shuts the lid.
MERYL, standing close behind.
MERYL What're you doing out here?
TRUMAN Fixing the mower.
Meryl doesn't look like she buys it.
MERYL Your sister called.
MERYL She was worried about you.
TRUMAN I saw my father on State Street dressed as a homeless man.
MERYL I kept seeing my brother for years after he died.
TRUMAN What do you want?
MERYL I made macaroni.
TRUMAN I gotta go out.
TRUMAN About a replacement...
TRUMAN ...mower blade.
Meryl nods, not at all convinced.
After an uncomfortable pause, she turns and heads back to the house.
TRUMAN ruefully examines the broken car aerial on his freshly washed Oldsmobile.
In the background is the warning sign he has just ignored, "CLOSE WINDOWS, LOWER AERIALS".
Truman removes the metal coathanger from beneath the lavender cardigan and forces the bent wire into what's left of the severed aerial.
TRUMAN motors down a busy shopping street, crowded on both sides with PEDESTRIANS.
As he drives, he tests his car radio.
Adjusting the tuner knob, he finds a station.
FEMALE VOICE (from radio) ...west on Atlantic...he's making a right on Woodhaven...
Truman glances up at the street signs along his route and finds that they coincide exactly with the streets quoted on the radio.
Distracted, he almost bowls over an OLD LADY on a crosswalk.
MALE VOICE (from radio) ...God, Truman almost hit Marilyn!...he's on the move again, passing the Burger King...
Truman readjusts the radio as it starts to fade out.
Suddenly there is a piercing blast of feedback.
He looks up and, as far as the eye can see, every PEDESTRIAN, MOTORIST and SHOPKEEPER along the street suddenly winces in pain and holds their right ear at exactly the same moment.
MALE VOICE ...something's wrong.
MALE VOICE Change frequencies...
Truman tries to pick up the channel once again but without success.
Still shaken by his experience with the radio, TRUMAN exits a Drug Store with a small, brown paper bag.
Out of the corner of his eye he catches a MALE BYSTANDER still checking his right ear with his finger.
He goes to say something to the by-stander but thinks better of it.
HOOKERS in white heels and spray-on skirts display their wares.
TRUMAN cruises slowly past in his Oldsmobile, the expression of the prostitutes turning from seductive to contemptuous as each is by-passed.
Suddenly Truman pulls sharply into the curb beside a leggy, prostitute, VERONICA, wearing a platinum blonde wig.
She is in deep discussion with a fellow WORKING GIRL.
Veronica recognizes the car and instantly bends down to the open passenger window.
VERONICA Hey, Truman!
VERONICA Where you bin?
VERONICA You bin cheatin' on me?
Veronica opens the door and folds herself into the passenger seat.
VERONICA knows the form.
As TRUMAN pulls away from the curb, she is already removing the lavender cardigan from the drycleaning bag on the back seat.
She drapes the cardigan around her shoulders.
VERONICA Bout time you got this thing cleaned.
VERONICA Don't tell me you bin makin' your old lady wear it.
Truman passes her the brown paper bag without reply.
Veronica removes a bottle of perfume and proceeds to liberally apply it.
VERONICA God, do they still make this stuff?
VERONICA What's the Sell-By Date?
From a vantage point in a disused tower high above the park.
CHRISTOF and CHLOE watch as Truman's Oldsmobile enters the park grounds and comes to a stop near the large metal framed globe, the Unisphere.
Both Christof and Chloe wear earpieces, a miniature television propped at their feet shows a close-up picture of TRUMAN and VERONICA inside the car.
CHLOE ...you see him messing with the antenna...what did you think would happen?..."
CHLOE lapse of concentration", is that what you call it?
CHLOE I call it amateur-hour...
CHLOE In case you hadn't noticed, we don't get to do it over.
Christof, totally unfazed, regards his zealous young assistant with affection and even a mild amusement.
CHLOE You think this is funny?
CHRISTOF The mask has slipped before.
CHRISTOF Everything can be explained.
TRUMAN kills the lights and he and VERONICA exit the car unaware that they are being observed.
CHRISTOF What's dangerous is that he makes the connection between what happened today and the girl.
We focus on Truman and Veronica as they take a seat at the edge of the pool surrounding the great steel globe.
VERONICA Like I say, I don't normally do this.
VERONICA I gotta charge extra.
Truman nods his agreement and forks over several bills.
Veronica deposits the money in her purse and perches herself as modestly as possible on the edge of the fountain.
When she is ready, Truman tenderly places his arm around her shoulder.
Veronica responds, hesitantly, becoming immersed in her role.
She reaches out her own hand and rests it on the nape of his neck.
Slowly both heads drift together, but stop just short of their lips meeting, agonizingly close.
So close they can feel each other's breath, barely a sliver of daylight separating them.
Then finally their lips touch in the most gentle of caresses.
They hold the kiss for another long moment and then simultaneously break.
As they look into each other's eyes, Truman goes to say something but Veronica hushes him by placing a finger to his lips.
Then abruptly she moves out of frame, the cardigan falling from around her shoulders in her haste.
From Truman's POV we focus on the cardigan on the pavement, triggering a flashback in his head.
As with Truman's previous flashbacks, this scene appears to be playing on a television screen.
However, on this occasion it is also accompanied by CHRISTOF's comments from his perch in the tower above the park.
CHRISTOF (V.O.) He's re-created the event on and off for a number of years.
CHRISTOF (V.O.) We've never understood what prompts him to indulge the fantasy, or for that matter what inspired such a painfully shy boy to approach her in the first place...
A SEVENTEEN-YEAR-OLD TRUMAN, carrying a stack of books, spies LAUREN, sixteen going on thirty-five, wearing the lavender, beaded cardigan at her open locker.
She is entertaining two GIRLFRIENDS with what appears to be a lewd tale.
CHRISTOF (V.O.) We'd noticed them making eyes at each other for some weeks but never thought he'd say anything.
CHRISTOF (V.O.) She was a year older, wrote poetry, way out of his league...
Truman, obviously terrified, musters the nerve to approach the lockers.
The three girls look up, surprised by the interruption.
TRUMAN Hi.
GIRLFRIEND 1 See you in class.
Lauren is unsure whether or not to follow her friends.
TRUMAN Lauren, right?
Her name is carefully written in blue ink on the covers of her text books.
LAUREN No.
TRUMAN Look.
TRUMAN I was wonder--
LAUREN --I can't go out with you.
TRUMAN I haven't asked you yet.
LAUREN Well when you do, that's my answer.
LAUREN I'm sorry.
LAUREN It's not up to me.
TRUMAN Why, you married?
Lauren smiles despite herself.
TRUMAN I'm not asking you to have my children, just a pizza.
TRUMAN How about Saturday?
LAUREN No.
TRUMAN Friday?
Lauren looks around the deserted school corridor.
LAUREN Now.
TRUMAN Right now?
TRUMAN We got finals.
LAUREN If we don't go now, it won't happen.
Truman hesitates.
LAUREN Well, what do you want to do?
The SEVENTEEN-YEAR-OLD TRUMAN and LAUREN enter the park near the Unisphere.
The park is deserted on a hot June afternoon.
CHRISTOF (V.O.) We knew we were taking a risk.
CHRISTOF (V.O.) She hadn't been properly coached, but we were torn...
CHRISTOF (V.O.) He'd summoned the courage to make the approach...We wanted to reward that.
CHRISTOF (V.O.) Of course she took full advantage...
Truman and Lauren run up to the ledge of the pool surrounding the steel sculpture.
LAUREN I never knew this place existed.
They both stare down at the inviting water.
Lauren suddenly throws off her cardigan and jumps into the pool without another thought.
She comes splashing to the surface.
Truman stares down, transfixed hy the shimmering water.
LAUREN Come on!
LAUREN Come on!
LAUREN It's wonderful!
TRUMAN I...I can't.
Lauren suddenly stops splashing.
LAUREN That's right.
LAUREN Oh, God, I'm sorry.
She quickly climbs out of the pool, dripping wet.
TRUMAN Why?
TRUMAN You've got nothing to be sorry about.
TRUMAN Has someone been talking to you?
Lauren wrings out her dress.
LAUREN Get me out of here.
LAUREN I don't want to be here.
Lauren starts walking away.
TRUMAN What are you talking about?
TRUMAN Lauren!
TRUMAN Lauren!
Truman runs after Lauren and holds her by the arms, forcing her to face him.
LAUREN My name's not Lauren!
LAUREN It's Sylvia!
Truman looks into her eyes and believes her.
TRUMAN and SYLVIA (as she is now called throughout the remainder of the movie) sit on the ledge of the pool - the same spot as Truman and the hooker, Veronica, seventeen years later.
As we have just seen imitated, Sylvia and Truman kiss with great delicacy.
Truman goes to say something but she covers his lips with her finger.
SYLVIA In a minute someone's going to come and stop me talking to you.
TRUMAN Who?
TRUMAN There's no one around.
SYLVIA You remember when you were a little boy, you stood up in class and said you wanted to be an explorer like Magellan.
SYLVIA And your teacher, Sister Olivia said, "You're too late, Truman.
SYLVIA There's nothing left to explore."
SYLVIA And all the other kids laughed.
SYLVIA And you sat down.
TRUMAN How do you know about that?
SYLVIA It doesn't matter.
SYLVIA You've forgotten about that boy, Truman.
SYLVIA You got scared.
SYLVIA Just because something happens, doesn't mean you can't take another chance in your life.
TRUMAN I don't understand.
SYLVIA There isn't much time.
SYLVIA Just listen.
SYLVIA Everybody's pretending Truman.
SYLVIA Everybody but you.
SYLVIA Look at that project.
SYLVIA You think anybody lives there?
SYLVIA It's all for you, Truman.
SYLVIA A show.
SYLVIA The eyes are everywhere.
TRUMAN Eyes?
TRUMAN Where?
SYLVIA Everywhere, disguised...Truman, they're going to fill your head with lies.
SYLVIA You've got to make yourself deaf, you understand?
SYLVIA When you're afraid the most, it means you're on the right track.
SYLVIA Trust that boy.
SYLVIA Promise me you'll do that?
Truman nods, unsure of the commitment he is making.
Suddenly a 1962 Plymouth roars towards the fountain out of nowhere.
SYLVIA I told you, Truman!
The car skids to a stop and a large MAN, 40ish, with a shock of dark hair jumps from the car.
The man yanks the frightened Sylvia to her feet causing her cardigan to fall to the ground.
TRUMAN Hey!
MAN Get in the car, Lauren!
Truman jumps up.
TRUMAN Who are you?!
MAN I'm her father!
SYLVIA No he's not!
SYLVIA He's just saying that!
SYLVIA Does he look anything like me?!
TRUMAN Shut your mouth!
The man backhands Sylvia roughly across the face and bundles her into his car.
Truman rushes at the man.
TRUMAN Leave her alone!
The man easily fends Truman off, knocking him to the ground.
He slams shut the passenger door of the Plymouth.
MAN I told you not to come here anymore!
MAN Which one are you?
Truman is suddenly struck dumb, the doubts start crowding back into his head.
SYLVIA Don't listen to him, Truman.
SYLVIA Make yourself deaf.
SYLVIA Come find me.
MAN Don't bother!
MAN We're moving to Australia.
MAN New York's done something to her head.
The Plymouth roars away.
Truman stares after it and then turns back to the cardigan left on the ground.
CHRISTOF (V.O.) Why did he say Australia?
CHRISTOF (V.O.) Why couldn't he have said New Jersey?
VERONICA'S head suddenly appears back in frame beside TRUMAN.
VERONICA You want me to do it again?
VERONICA I think I could do it better.
TRUMAN No...thank you.
Truman picks up the cardigan.
They return to the car.
TRUMAN drives VERONICA back to her turf.
She smokes a cigarette, flicking ash out of the window.
TRUMAN Veronica, what do you know for sure?
VERONICA For sure?
VERONICA The nuns at my school, they used to say, "The whole of life is faith."
Truman regards his companion in a new light.
He comes to a stop at the corner where he picked her up.
VERONICA On the house.
Another televised flashback.
The SEVENTEEN-YEAR-OLD TRUMAN stands reflectively beside Sylvia's open and vacated locker.
CHRISTOF (V.O.) We removed all physical trace of her but we couldn't erase the memory...
In a secluded corner of the library the SEVENTEEN-YEAR-OLD TRUMAN sits at a table surrounded by a stack of glossy women's magazines.
By tearing out individual facial features - eyes.
nose, mouth, ears, chin, hair - from photographs of YOUNG WOMEN in the magazine's advertisements, Truman has been able to improvise a composite picture of Sylvia.
The montage is a passable likeness although Truman is not completely satisfied with Sylvia's nose.
He toys with several nose examples before reluctantly settling for one.
He stares wistfully at the completed picture.
SEVENTEEN-YEAR-OLD TRUMAN enters the front door.
His older sister, RAQUEL, has been awaiting his arrival.
CHRISTOF (V.O.) When he decided to go after Sylvia, we were forced to intervene once again...
TRUMAN I've got something to tell you, Sis.
RAQUEL I've got something to tell you too.
TRUMAN I'm going to Australia.
RAQUEL Mom's real sick.
Truman's face falls.
As he enters the bedroom where his ill MOTHER lies gazing at the ceiling, we focus on his EXCHANGE STUDENT APPLICATION that he has inadvertently crushed in his hands.
TRUMAN turns into his street but stops several houses short of his own driveway and kills the car's engine.
In the light of a streetlamp, Truman opens his briefcase and removes the framed photograph of his wife, MERYL.
But he turns his wife's face away from him and opens the clasps on the back of the frame.
Removing the backing, he exposes the composite picture of SYLVIA we witnessed in the flashback of his youth, worn and faded by the years.
With the frame on his lap, Truman retrieves a handful of paper fragments from his jacket.
Noses.
He tests the likeness of each one in turn.
Unsatisfied that any of the new noses is an improvement, Truman tosses them out of his car window.
We watch the paper fragments blowing in the breeze as Truman's car proceeds down the street and into his driveway.
Close up on a nose.
We pull back to reveal that the nose belongs to SYLVIA, seventeen years older than Truman's composite picture - slimmer in the face, wearing her hair shorter.
She is standing at the water's edge on a long, deserted windswept beach, several sailing dinghys pulled up beyond the high-water line.
In the background, a solitary, white beachfront house - an other-worldliness to the idyllic scene.
Looking up into the sky, Sylvia's attention is drawn to a piece of paper carried on the ocean breeze.
The paper catches on the mast of one of the sailing dinghys.
A page from a newspaper, carrying a photograph of TRUMAN in the street where he encountered his father.
Sylvia retrieves the page.
The article's headline reads, "TRUMAN'S FATE IN DOUBT".
Spying a MAN, late-thirties, kindly face, riding up to the beach house on an old bicycle, Sylvia secrets the page under her sweater.
The man waves cheerfully as he comes to join her on the sand.
Sylvia waves cheerfully back.
In a quiet bar, a WAITRESS patiently explains her viewpoint to the BARMAN.
A PATRON on a barstool, eavesdrops.
WAITRESS She was willing to lose him if it meant he could find himself.
WAITRESS Never mind.
TRUMAN sits in his car, about to lace his coffee.
From inside the adjacent Elementary School gymnasium, he hears the familiar excited squeals and shouts of SCHOOL CHILDREN.
Truman suddenly throws aside his miniature of Jack Daniels and sprints across the parking lot and into the school.
TRUMAN slams through the front doors into the reception area.
It is deserted, no one stationed at the administration desk, the corridors empty.
He runs down a vacant corridor, pushing open classroom doors as he goes.
They are all unoccupied.
Finally, he stands outside the gymnasium.
The childrens' voices can still be heard.
Truman takes a deep breath and bursts through the double doors.
The room is empty save for a large reel-to-reel tape recorder in the middle of the basketball court playing a continuous tape of childrens' voices.
The recorder is attached to speakers on tall stands facing the ventilation ducts.
Truman stares at the machine in disbelief.
TRUMAN exits the subway, still lost in thought.
He stops at the newstand and picks up a copy of Vanity Fair to resume his ritual search but his heart is not in it.
He starts his trek to work, pausing to stare at his reflection in the mirrored building, hoping that the Homeless Man will appear at his side once again.
But no one joins him.
However, as Truman continues to stare, it is the building itself that takes his interest.
An imposing forty-story office building, a black, sheer mirrored box clad in the kind of reflective glass that shields its occupants from the world, a building Truman passes every day.
As usual, a steady stream of EMPLOYEES and VISITORS enter and exit the building's high-ceilinged lobby past an intimidating security desk manned by two UNIFORMED GUARDS.
Beyond security are banks of elevators, ferrying executives, clerical staff and delivery personnel to and from their floors of business.
Truman abruptly enters the building.
He strides confidently past the security desk trying to look as if he belongs.
SECURITY GUARD 1 Can I help?
TRUMAN I have an appointment at, er...Diamond Enterprises.
SECURITY GUARD 1 They went bust.
The second Security Guard is rising from his seat to block Truman's path to the elevators but Truman reads his mind and makes a dash for it.
He slips into an elevator just as the doors are closing, defeating the flailing arm of the pursuing guard.
A WOMAN EXECUTIVE in the elevator looks in horror at Truman.
The cause of her concern becomes all too apparent.
Looking beyond the woman, Truman discovers that there is no back to the elevator car.
The elevator is simply an opening into the body of the building.
Truman pushes past the Woman to be confronted with the fact that the entire office block is nothing but a giant, empty shell with no floors above the ground floor.
The PEOPLE Truman has just witnessed entering the other elevators are milling around a refreshment table, sitting on folding chairs, changing their clothes behind temporary curtained cubicles or lining up to re-enter the bogus elevator cars.
Gradually, they all turn to gape at Truman, who in turn stares back, appalled.
The Security Guards suddenly appear at Truman's side and take him by the arm.
SECURITY GUARD 1 You gotta leave.
TRUMAN What're they doing?
SECURITY GUARD 2 You gotta leave.
The Guards frog-march Truman out of the huge facade towards an Emergency Exit.
TRUMAN Just tell me what the hell's going on?
SECURITY GUARD 1 We're re-modelling.
TRUMAN Like fuck!
TRUMAN What're they doing?
TRUMAN continues to struggle as the GUARDS usher him to the street.
TRUMAN You don't tell me, I'll get you investigated!
SECURITY GUARD 2 Investigate what?
SECURITY GUARD 2 You're trespassing!
Truman sees there is no point in arguing further.
His shouts are attracting the interest of PASSERS-BY.
A thought occurs to him.
He starts to run along the street, suddenly entering another building at random.
An office block with a bank on the ground floor.
As he skirts the bank, he feels the eyes of the BANK STAFF and CUSTOMERS on him.
Is he so suspicious-looking or were they expecting him?
Truman rushes to the elevators.
The lights above the doors show all the elevators on upper floors.
Frantic pressing of the elevator button gets no response.
Truman heads for the stairs but is intercepted by a BANK OFFICIAL who bars his way.
OFFICIAL You can't--
TRUMAN --I know.
Truman backs away out of the office and continues to run down the streets of Lower Manhattan's financial district.
Every building he encounters seems to have a SECURITY GUARD anticipating his arrival or a building OFFICIAL hanging a CLOSED FOR BUSINESS sign on the front door.
He feels the eyes of PEDESTRIANS.
Is he simply drawing attention to himself by his behavior?
Truman wheels around, trying to make eye contact with passers-by.
They shy away.
Truman stops still, his head reeling.
From the office window on the twelfth floor, TRUMAN can observe the glass building down the street.
He ponders the black, mirrored box.
LAWRENCE appears at his side.
TRUMAN You ever been into the AMT Building?
LAWRENCE Not since they begun reconstruction.
LAWRENCE What're you doing with that?
TRUMAN I'm going to visit a site.
LAWRENCE What for?
TRUMAN Because I never do.
LAWRENCE That's why we got adjusters.
TRUMAN You got a problem with me going?
LAWRENCE I got a problem with you not doing your job, Burbank.
LAWRENCE You already screwed up once this week.
TRUMAN Let me worry about that.
Truman exits with the report.
After waiting only a matter of seconds for an elevator, he impatiently enters the stairwell.
As soon as he disappears from sight, a grim CHRISTOF emerges from a nearby office, shadowed as always by CHLOE.
They approach Lawrence with the familiarity of business associates.
LAWRENCE 680 West 89th.
Christof nods.
Chloe opens a flip-phone to make a call.
An out-of-breath TRUMAN arrives on the second floor landing of the stairwell to find two burly MOVERS blocking his path with a large office desk they are attempting to transport.
Truman considers retracing his steps, then without warning clambers over the mahogany barrier.
MOVER 1 Hey, would it kill ya to wait?!
TRUMAN paces impatiently on an empty subway platform with other frustrated passengers.
He loses patience and suddenly turns and runs up the stairs.
TRUMAN sits seething in a traffic jam that exists for no apparent reason.
TRUMAN Is there another way?
TRUMAN Can't you get around this?
TRUMAN exits his taxi and takes in the scene.
A partially burnt building, waterlogged, still faintly smoldering.
Truman checks the address on his file.
A small, serious-looking BOY straddles his bicycle on the sidewalk.
TRUMAN When was the fire?
BOY Week ago.
TRUMAN How come it's still smoking?
BOY Started up again.
BOY Kids.
TRUMAN Says here it burnt to the ground.
BOY Wishful thinking maybe?
The boy is wise well beyond his years.
Truman fixes him with a glare.
TRUMAN Someone send you to tell me all this?
BOY You the one askin' questions.
The boy casually rides away.
TRUMAN wanders aimlessly through a city park, observing.
We sense, truly observing for the first time.
A group of YOUTHS play a pick-up game of basketball.
A YOUNG WOMAN walks a pair of AFGHAN HOUNDS.
An OLD MAN answers the incessant questions of his GRANDCHILD.
Nothing appears amiss.
TRUMAN stands amidst a throng of TOURISTS and COMMUTERS marooned on Times Square.
Mesmerized by the two fast-moving rivers of vehicles flowing through the intersection.
Truman stares down at the street, contemplating stepping out into the traffic.
However as his foot is poised, the stream of cars that passed so close by seconds earlier, now appear to be giving him a wider berth.
He steps off the sidewalk and.
to an acompaniment of car horns, begins to wander back and forth without fear through the traffic, confident that each vehicle will take evasive action.
Safely on the other side of the street, he stands in front of the window of an electronics store.
He watches a local TV news show covering the Santa Maria replica moored near Pier 13.
However Truman is forced to look away when he glimpses his own face on another TV taking a feed from a camcorder aimed out the store window.
He shudders at his video reflection.
TRUMAN'S face stares out from a televison monitor.
We slowly pull back to reveal that other smaller monitors surround the first until we find ourselves staring at a video wall in a room the size of a football field.
The curved bank of monitors, suspended by cables from the ceiling, gives the appearance of a giant patch-work mobile.
Investigating the screens we discover surveillance pictures from all over New York City, covering every facet of Truman's life.
Camera angles from the interior of Truman's house, his backyard, car, subway station, office, the deli he frequents, the seashore to which he is drawn, the park he visits with Veronica, the abandoned freeway where he golfs with Marlon, many of the locations strangely devoid of people.
Beneath the video wall is a state-of-the-art mixing desk, its illuminated buttons glowing brightly in the gloom.
Facing the desk, several OPERATORS in high-backed, high-tech swivel chairs, wearing the slimmest of headsets.
SIMEON, a meticulous young man with a penetrating gaze, sits directly in front of the largest of the monitors, co-ordinating camera angles.
CHRISTOF stands over Simeon's shoulder, staring intently at the live picture of Truman now seated at a streetside cafe, continuing to inspect his surroundings.
CHLOE hovers in the background.
There is an uncomfortable silence in the control room as the production crew feel themselves under scrutiny for the first time.
Christof leans forward and talks soothingly into a microphone on the control panel.
CHRISTOF ...Everybody stay focused...remember who you are...
TRUMAN sits alone at the table, still looking for a false move.
A DELIVERY MAN unloads boxes from the back of his truck and carries them into a Restaurant Supply store.
Further down the street CONSTRUCTION WORKERS take their time tending to an electrical repair in an exposed manhole.
A POSTAL WORKER does his rounds.
An OLD WOMAN struggles with two heavy shopping bags.
Everybody appears natural, places to go.
Truman turns his attention to a group of ITALIAN-LOOKING MEN at the only other occupied table at the cafe.
We see extreme close-ups as Truman scans the men's faces for any sign of phoniness.
They are talking loudly, making suggestive comments to the WAITRESS and generally showing off like schoolboys.
Their behavior passes the test, all seems genuine.
Truman idly regards his three-stone wedding ring with which he has been fidgeting.
The on-air monitor shows TRUMAN from the ring's POV, revealing that the small center diamond contains a miniature, hidden camera.
Truman suspects nothing.
He looks up to find two well-to-do 3OGGERS, out for a lunchtime run, making their way down the street towards the cafe.
Truman happens to glance at the sneakers of one of the joggers.
He springs to his feet and blocks the joggers' path.
CHRISTOF Damn!
Unseen by Christof, his Assistant Director, Simeon takes a moment of pleasure from the older man's distress.
TRUMAN Small world.
JOGGER 1 Excuse me.
Truman blocks the man a second time.
TRUMAN You don't remember?
TRUMAN Two days ago I gave you my meatball sandwich in the park.
TRUMAN You were in a wheelchair.
TRUMAN Same sneakers.
An almost subliminal flashback appears in Truman's head confirming that the JOGGER and the HOMELESS MAN in the wheelchair two days earlier are one and the same.
TRUMAN A miracle!
JOGGER 2 Get the hell outta here.
The second jogger pushes Truman back against the cafe table causing him to stumble.
MARLON is loading boxes of candy into the back of his van.
TRUMAN hurries up to him.
TRUMAN Marlon.
TRUMAN I've gotta talk to you.
MARLON Truman!
MARLON Sorry, I'm up against it today.
TRUMAN I've fallen over something, Marlon.
TRUMAN Something to do with my Dad.
TRUMAN I think.
MARLON Are you okay?
MARLON You look like shit.
TRUMAN It's big, Marlon.
TRUMAN You wouldn't believe who's in on it.
MARLON In on what?
TRUMAN There's no point trying to show you, they cover their tracks too well.
TRUMAN But I've been going into a lotta strange buildings, seeing a lotta familiar faces, y'know what I mean?
MARLON Something's definitely in the air.
MARLON My last delivery, a kid got crushed to death.
MARLON tilting a vending machine.
MARLON They won't even let me take the rest of the day off.
TRUMAN Do it, anyway.
Marlon scoffs at the suggestion then realizes Truman isn't joking.
TRUMAN I'm deadly serious.
TRUMAN Marlon.
TRUMAN We can't talk here.
TRUMAN I'm being followed.
MARLON Who?
TRUMAN I don't know.
TRUMAN They look just like regular people.
TRUMAN But I've been writing down numbers - license plates, taxi numbers, ID numbers - the same ones keep cropping up over and over.
MARLON Is someone leanin' on you, Tru?
MARLON Cos I got some friends here, they owe me.
MARLON We can lean back.
MARLON Is he one of them?
TRUMAN I don't know.
TRUMAN Could be.
TRUMAN One thing's certain.
TRUMAN The key is spontoneity.
TRUMAN Be unpredictable.
TRUMAN They can't stand that.
TRUMAN That's why we've got to get outta here.
TRUMAN Can you come with me?
MARLON Christ, Truman.
MARLON You're gonna get both our asses fired.
Marlon shuts his van and gets in.
Truman enters the passenger side.
MARLON Where're we going?
TRUMAN The beach.
CHRISTOF is in deep conversation with two executives.
MOSES, a contemporary of Christof but more jaded and debauched-looking and ROMAN, a fresh-faced, younger man.
CHLOE hovers in the background.
A monitor, suspended from the ceiling shows a surveillance shot of TRUMAN and MARLON pulling into a beach parking lot in Marlon's van.
The glass conference room looks out onto the vast control facility where SIMEON continues to call the shots, all too aware of the closed-door discussion taking place in the background.
CHRISTOF I can't believe how much he's shoved down.
CHRISTOF That he sensed the significance at aged seven and clung to it so fiercely.
Roman paces, agitated, unimpressed.
Moses, mnore respectful.
CHRISTOF You remember, Moses, it used to end right there, before the expansion.
ROMAN Christof, the cracks are starting to show.
CHRISTOF I'll paper over them.
CHLOE Truman's had bouts of paranoia before and recovered.
ROMAN No, not like this.
ROMAN It's compromised.
ROMAN Becoming unwatchable.
Too much for Christof.
He wheels on the young man.
CHRISTOF Fear?
CHRISTOF Doubt?
CHRISTOF Is that what you have trouble watching?
CHRISTOF Perhaps you don't like watching yourself.
Roman is stung into silence.
MOSES Why don't you two wait outside?
Reluctantly Roman and Chloe exit and join Simeon at the video wall.
CHRISTOF He's jumped the rails, Moses, that's all.
CHRISTOF We'll get him back on.
MOSES You know why they're so nervous.
MOSES The birth of Truman's child is going to double revenue.
MOSES For God's sake don't let him upstage you.
MOSES You've been grooming a successor.
CHRISTOF He's not ready.
MOSES Him or you?
CHRISTOF You can't pull him back in without me.
CHRISTOF He's just acting out of character.
MOSES What if he's in character?
MOSES What if he's starting to act in character at last?
MOSES Have you ever considered that?
TRUMAN runs down the beach towards the cliff he attempted to scale as a seven-year-old boy.
TRUMAN sits on the clifftop, staring out at the view his father had been so desperate for him not to see twenty-seven years earlier.
However the deserted bay beyond is exactly as his father described - almost identical to its neighbor.
MARLON, laboring, crests the rise and joins his friend on the clifftop.
MARLON What're we doing here, Truman?
TRUMAN This is where it started.
MARLON Where what started?
TRUMAN Things.
TRUMAN Things that don't fit.
TRUMAN Loose threads.
TRUMAN False steps.
TRUMAN Slips of the tongue.
MARLON Make sense, Truman.
MARLON You going religious on me?
TRUMAN My father didn't want me to see what was over here.
TRUMAN Whatever it was, it's gone now.
TRUMAN I never shoulda listened to him that day.
TRUMAN I knew it was wrong.
We see a quick flashback of SEVEN-YEAR-OLD TRUMAN on the cliff- face twenty-seven years earlier.
TRUMAN There were a hundred people on the beach that day.
TRUMAN Everybody knew what was going on except me.
MARLON I don't want to put you down but why would anybody go to all this trouble over you?
TRUMAN Maybe I've been mistaken for somebody else.
TRUMAN A couple of years ago, I tried to get hold of a copy of Time Magazine.
TRUMAN The week before an ad said, "Next Week: Truman Burbank and the Lost Generation".
Marlon shrugs, unimpressed.
TRUMAN A guy with the same name as me in Time Magazine.
TRUMAN It ain't a common name so I looked out for it.
TRUMAN But the day it came out, every newstand was sold out.
TRUMAN No library had it.
TRUMAN I even wrote off for a back-issue.
TRUMAN Never seen a copy to this day.
Marlon remains unconvinced.
TRUMAN Maybe I'm being set up for something.
TRUMAN You ever feel like that, Marlon?
TRUMAN Like your whole life has been building to something?
Marlon looks skeptically at Truman.
He hasn't had that feeling.
MARLON A coincidence.
MARLON Haven't you ever heard of a coincidence?
TRUMAN I'm a walking coincidence.
TRUMAN I can't count 'em.
TRUMAN No something's happening, Marlon.
TRUMAN I've got to get to the bottom of it.
MARLON Of what?!
MARLON Why're you doing this to yourself?
TRUMAN I'm scared, Marlon.
TRUMAN I'm as scared as hell.
TRUMAN But I've never felt more alive.
TRUMAN It's just like she said.
MARLON Who?
TRUMAN It doesn't matter.
TRUMAN She was too beautiful for here.
Now Marlon is really confused.
TRUMAN Can you lend me some money?
TRUMAN A hundred bucks.
MARLON All I got on me is the takings from the machines.
MARLON Why do you need it?
TRUMAN I'm going away for a while.
The comfortably furnished room of a writer.
Walls lined with books.
Desk overlooking the sea, strewn with notes, photos and other reference material.
Sylvia's name on the spine of several published volumes.
Pages of unfinished manuscript, handwritten in blue ink.
SYLVIA stands at a bookcase, looking for inspiration.
As she pulls out a book, a magazine falls to the floor.
Truman's missing copy of Time Magazine.
His face on the cover with the headline, "Truman Burbank and the Lost Generation".
Sylvia retrieves the magazine.
In front of a nearby mirror, she holds Truman's photographed face next to her own, for a moment imagining them together.
Then, catching herself, she quickly lowers the magazine, left alone with her own reflection.
We see TRUMAN's disturbed face reflected in the screen of his television set, montaged over that of ROBIN LEACH, host of "Lifestyles Of The Rich And Famous".
MERYL, wearing her robe, head against Truman's chest, sips from a bottle of beer.
MERYL What's going on, Truman?
MERYL You're not yourself.
TRUMAN Maybe you just don't know me very well.
CHRISTOF eats a sumptuous meal in an ornate private dining room with an elegant WOMAN, thirty years his junior.
Playing silently on a monitor on an antique side table is a surveillance shot of TRUMAN and MERYL slumped in front of their television.
CHLOE, enters the room and nods an apology to Christof's dinner companion - a woman her own age.
Christof's companion shrugs resignedly.
Christof registers Chloe's thinly disguised resentment, enjoying the rivalry.
Chloe inserts a cassette tape into a nearby VCR.
Christof wipes his mouth with his napkin and picks up his wine glass as he gives the television his full attention.
A commercial for "GLOBAL TRAVEL" begins to play.
TRUMAN continues to watch "Lifestyles" restlessly.
However, as he goes to get up from the sofa, MERYL starts to slide down his chest towards his lap.
MERYL We could do it right here, like we used to.
The program cuts to a commercial break.
The commercial is for "Global Travel".
NARRATOR Travelling Down Under?
NARRATOR Global Travel is turning rates to Australia upside down.
NARRATOR Round Trip to Sydney only $829.
NARRATOR One way, $465.
NARRATOR Global Travel at Broadway and 44th...
Truman perks up at the commercial while Meryl's attention is elsewhere.
TRUMAN Lemme go to the bathroom.
MERYL Don't be too long.
Truman exits the living room.
However, on his way to the bathroom he hesitates at the kitchen table.
He surreptitiously lifts the platic-coated plaid tablecloth to reveal numerous bills laid out flat beneath it to keep the stash hidden.
CHLOE pulls back long, white silk drapes to reveal a spectacular view overlooking the Hollywood Hills.
CHRISTOF rouses from his enormous round bed.
His DINNER COMPANION also stirs, waving coyly to Chloe as she modestly covers herself, only mildly perturbed by the intrusion.
Chloe switches on the television set in the extravagent bedroom.
Playing on the set are TRUMAN and MERYL still fast asleep in their own bed.
CHRISTOF What happened overnight?
CHLOE He couldn't do it, even on the sofa.
CHRISTOF God, that thing of his must be psychic.
CHRISTOF He didn't masturbate?
CHLOE Not for the last two inonths.
Chloe exits and Christof climbs out of bed.
MERYL emerges from the bathroom, ready for work, surprised to find TRUMAN sitting at the kitchen table.
MERYL Aren't you gonna be late?
TRUMAN I got a call in the area.
TRUMAN What's the case?
TRUMAN Anything interesting?
MERYL Rape on the subway.
Truman's eyes widen.
We see a quick flashback in Truman's head of the two YOUTHS assaulting the WOMAN on his train.
MERYL They're guilty as hell but they'll walk.
MERYL No witnesses.
MERYL Her word against theirs.
MERYL Maybe we could meet for lunch today.
Meryl gives him an affectionate kiss and exits the back door.
Truman waits for the sound of Meryl's car to disappear down the road and exits himself.
TRUMAN enters the courtroom building.
A crush of DEFENDENTS, FAMILIES, ATTORNEYS and POLICE OFFICERS.
Truman goes to enter a courtroom but a SECURITY GUARD blocks his path.
SECURITY GUARD You a witness?
TRUMAN Er, yes...
TRUMAN No, no I'm not.
SECURITY GUARD Closed session.
Before the guard can move him on.
Truman sneaks a look at proceedings through the courtroom door window.
He recognizes the two YOUTHS sitting at the defendent's table.
A PROSECUTOR is on his feet, addressing the JURY.
MERYL is working attentively at her stenotype machine, her fingers rapidly pressing the keys.
However, Truman notices a glaring omission.
There is no paper emerging from Meryl's machine.
The roll of paper tape sits on the floor beside her chair leg.
The EMPLOYEES and CUSTOMERS inside GLOBAL TRAVEL are all doing a last-minute primp, fixing their hair and checking their clothes.
Suddenly, in unison, they take their positions and begin working.
As TRUMAN enters GLOBAL TRAVEL, one CUSTOMER looks up a fraction too quickly, anticipating his arrival.
Truman takes a seat at the only unoccupied desk, opposite a female TRAVEL AGENT.
Feeling uneasy about a surveillance camera in the corner of the room, he nervously obscures his face with his hand.
TRUMAN I wanna book a flight to Australia.
AGENT Where exactly?
TRUMAN Australia.
AGENT Where in Australia?
AGENT What city?
TRUMAN Sorry, Sydney.
TRUMAN Sydney, Australia.
TRUMAN That's right.
AGENT For how many?
TRUMAN One.
AGENT When do you want to leave, remembering, of course, that you do lose a day on the way there?
TRUMAN Today.
AGENT I'm sorry.
AGENT I don't have anything for a week.
TRUMAN A week.
AGENT It's the busy season.
TRUMAN You sure you're not trying to keep me here?
TRUMAN You are a travel agent, aren't you?
TRUMAN Your job is to help people travel, not keep 'em where they are.
TRUMAN Or maybe you're a different kind of agent, Doris?
AGENT I do have a fabulous rate on a cruise ship departing for Australia tomorrow.
AGENT But you wouldn't want to do that.
TRUMAN Why wouldn't I?
AGENT I thought you were in a hurry.
TRUMAN That's right.
AGENT You want to book the flight?
Truman pulls out a wad of money from his pocket and several rolls of quarters from Marlon's vending machines.
The agent looks askance at the pile of cash.
TRUMAN You were expecting me, weren't you?
The travel agent ignores the question and prints the ticket.
AGENT It's non-refundable.
CHRISTOF stands with a PRODUCTION MANAGER, mid-thirties, on the forecourt of the Sydney Opera House, its sail-like roofs soaring above them.
Framing the background, the coathanger-shaped Sydney Harbor Bridge.
PROD. MANAGER Happy?
Christof gives a grudgingly complimentary nod.
CHRISTOF Can we contain him long enough?
PROD. MANAGER I think so.
Christof looks skyward at the cottonwool clouds above the harbor.
PROD. MANAGER He flies at night.
PROD. MANAGER Thick cloud cover to disorient him.
PROD. MANAGER Hopefully we'll knock him out with complimentary cocktails, pull the shades down during the movies.
PROD. MANAGER He'll never know.
Christof gives another grudging nod of approval.
The Production Manager is beckoned by a group of CONSTRUCTION WORKERS who are putting the finishing touches to a corner of the Opera House.
CHLOE drifts to Christof's side, a Watchman TV in her hand.
CHLOE Why go to all the trouble?
Christof glances at the TV screen in her hand, showing TRUMAN sitting in his office gazing at his composite picture of SYLVIA.
CHRISTOF He believes she has the answer.
CHLOE Why not just tell him she's dead?
CHRISTOF It's too late for that.
CHRISTOF That won't satisfy him.
CHRISTOF He's going to have to find out for himself.
CHRISTOF See it with his own eyes.
CHRISTOF Right now he needs something genuine.
CHRISTOF Even if we have to fake it.
Close up on typewriting appearing on a page.
"Please accept my resignation from American Life & Accident, Inc.
to take effect immediately.
Yours tru"
TRUMAN gets up from the typewriter in mid-word and strolls to a fellow AGENT's desk.
TRUMAN "Yours truly..."
TRUMAN You spell "truly" "l...y" or "e...l...y"?
INSURANCE AGENT I always write "Yours faithfully..."
Truman finds the appropriate page in the dictionary and gazes at the entry for a long moment.
He looks up, staring into the middle distance.
His eyes widen as something clicks in his mind.
Suddenly LAWRENCE snatches the dictionary from his hand.
LAWRENCE Where the hell have you been, Burbank?
LAWRENCE What the hell's going on?
TRUMAN That's what I'd like to know, Lawrence.
The AGENTS in the other cubicles turn in their direction.
TRUMAN I was just about to resign.
TRUMAN Isn't that a laugh?
TRUMAN I just realized there's nothing to resign from, is there?
LAWRENCE Listen, don't bother with the resignation.
LAWRENCE Just get the fuck outta here.
TRUMAN Why're you all pretending?
TRUMAN Huh?
TRUMAN What is this a front for?
TRUMAN Why aren't I in on the joke?
TRUMAN Was I away that day?!
Noting two colleagues exchanging a look, he pulls the computer off the desk to get their attention.
It lands on the floor with an expensive crash.
TRUMAN I'm talking to you!
TRUMAN Who am I?!
LAWRENCE You better get outta here or I'm calling Security.
TRUMAN "Security!
TRUMAN I'm calling Security".
Truman picks up the framed photograph from his desk, containing SYLVIA's hidden likeness.
Suddenly he wheels on Lawrence, pinning him to a cubicle wall.
TRUMAN You don't believe a single word you're saying!
TRUMAN None of you do!
TRUMAN You hear me?!
We see Truman's manic face from the sprinkler head's POV.
Truman stomps off down the corridor, other Insurance Agents giving him a wide berth.
He shoves computers, desk lamps and pot holders off desks as he goes.
TRUMAN steps out of the office, suddenly able to breathe again, pleased to be outdoors despite the gloomy sky overhead.
CHRISTOF is once again standing at the picture window in the dimly-lit control room where we first encountered him.
Behind him, the fronds of the palm tree sway in a gentle breeze.
The sky, a cloudless, cobalt blue in sharp contrast to the overcast day in New York City.
SIMEON, co-ordinating camera angles, sits in front of the largest of the monitors that shows a live picture of TRUMAN stuck in his car in gridlock.
SIMEON ...and back to the close-up...
CHLOE's attention is focused on a subsidiary monitor displaying a freeze frame of TRUMAN reading the dictionary a few minutes earlier.
CHLOE Do you think he sees the entry?
OPERATOR Hard to tell.
CHRISTOF Why don't we ask him?
CHLOE I don't know how it got there!
CHLOE Enhance.
Christof turns his back on the screen and stares out the window.
We focus on an enhanced picture of the dictionary's text.
genuinely, etc.
2.
in fact; really.
TrumanEsque (<u>E</u>sk)a.
characteristic of the experiences of Truman Burbank (a Trumanesque town, conversation, etc.)
[circa.
1972)
trump,n.
[<triumph], 1.
playing-
TRUMAN drives erratically down a quiet suburban street.
On the sidewalk up ahead, he spies a YOUNG MOTHER pushing an INFANT in a baby carriage.
Truman suddenly swerves sharply and jumps the curb in front of the mother and child, the car straddling the sidewalk.
He has the driver's door open almost before the Oldsmobile has come to a halt.
Truman dashes from the car and plucks the infant from the carriage while the mother stands rooted to the spot.
The startled infant immediately begins to wail as Truman holds the crying bundle in both hands above his head.
TRUMAN Say my name or I'll smash its head open.
The young mother, frozen with fright, does not reply.
TRUMAN Say my name!
YOUNG MOTHER Please, give him to me...
TRUMAN Say my name!
TRUMAN You know my name!
TRUMAN Say it!
YOUNG MOTHER I don't know you.
The commotion has attracted the attention of an OLD MAN across the street, watering his garden.
He drops his hose and hurries towards the fracas.
Halfway across the street, the old man stops in his tracks as he sees the baby, perilously poised in the air.
TRUMAN I mean it!
TRUMAN I'm ready to do it!
TRUMAN What's my name?!!
Truman lifts the screaming baby as far above his head as he can, his arms shaking, fighting the urge to dash the fragile innocent to the concrete.
We see a view of the scene from the POV of a streetlight.
The young mother, recognizing Truman's seriousness, opens her mouth to speak but no sound comes.
TRUMAN This is your last chance!
The anguish in his voice convinces us that Truman is truly on the brink.
The young woman now has tears rolling down her cheeks.
She is at a loss, powerless.
TRUMAN What...is...my...name?!
The young woman mumbles but is unable to supply the name.
Truman, arms shaking, face red with rage, realizes he can't go through with it.
With everything he has, he gathers himself.
After what seems like an age, he ever so slowly lowers the child into the safety of the mother's outstretched arms.
YOUNG MOTHER Thank you, Truman.
Truman shudders at the sound of his name and backs away from the young woman, as if it is she who now represents the threat.
He jumps into his car and slams it into gear, driving over the sidewalk and back onto the street.
The young woman and the old man stare after Truman's car as it roars away.
As TRUMAN drives, he stares, paranoid, at seemingly innocuous features in his Oldsmobile - his rearview mirror, steering wheel insignia, speedometer, airconditioning ducts - and peers up at the streetlamps lining the roadway.
A dozen-or-so of SYLVIA'S FRIENDS, including the MAN we have seen before, sit around a table on the balcony in the afternoon sun, talking animatedly.
A TEN-YEAR-OLD SON of one of the guests has strayed into the living room and switched on the television set hidden away in an antique bureau.
SYLVIA.
emerging from the kitchen, is taken aback by what she sees playing on the screen.
The MAN on the balcony catches her look as she swiftly switches off the TV.
She gently takes the child's hand and leads him outside.
TRUMAN, staring at the freeway from the bottom of the garden.
doesn't bother to look up as MERYL approaches.
TRUMAN See that car way down there?
TRUMAN I bet it's a Suburu station wagon.
Meryl looks idly over the fence at the approaching car.
Finally a Suburu station wagon motors by.
Meryl is unimpressed.
Truman turns his back on the Expressway to continue his game.
TRUMAN I predict the next four cars will be a white Honda Civic, a blue and white Dodge Dart with the front hubcap missing, a Volkswagon Beetle with a dented fender and a motorcycle.
Meryl doesn't wish to participate in the game and makes for the house.
Truman holds her arm, forcing her to watch.
He turns to check his prediction.
A convoy of cars approaches.
TRUMAN There's the Honda...the Dodge...here comes the dented Beetle...
Meryl's attention wavers.
Truman tightens his grip.
TRUMAN Look, damn you!
Following the VW is a school bus.
MERYL Where's the motorcycle?
Truman is momentarily disappointed.
Meryl seizes her chance and heads for the house.
Truman follows her inside.
TRUMAN Don't you want to know how I did that?
TRUMAN Maybe you already know.
TRUMAN Is that it?
Behind Truman's back, a motorcycle putters by.
MERYL is pouring herself ice tea when TRUMAN enters.
MERYL Where have you been?
MERYL I've been calling you all day.
TRUMAN Have you been concerned, Meryl?
TRUMAN Nice name.
TRUMAN "Meryl".
TRUMAN I always liked it.
MERYL Nice of you to say so after eight years.
TRUMAN Actress's name, isn't it?
TRUMAN What's your real name?
MERYL Oh, God.
MERYL What's got into you?
TRUMAN Take a break.
TRUMAN Meryl
TRUMAN I know.
MERYL I invited Marlon and Rita for a barbeque Sunday.
MERYL I thought I'd make my potato salad.
MERYL Remind me...
TRUMAN Drop it, I said.
TRUMAN It's over.
MERYL ...we need more charcoal.
TRUMAN Shut up!
MERYL I'm gonna take a shower.
TRUMAN No.
TRUMAN We're going for a drive.
MERYL What?!
Despite her protests, Truman drags Meryl out the back door and towards his car.
TRUMAN For years I've been saying I want to go some place, well now I'm ready to go.
TRUMAN Let's just jump in the car and go.
TRUMAN holds MERYL's wrist to stop her exiting the car and accelerates out of the driveway in reverse without looking.
TRUMAN I thought maybe, Atlantic City.
MERYL You hate gambling.
TRUMAN That's right.
TRUMAN I do, don't I?
MERYL So why do you wanna go?
TRUMAN Cos I never have.
TRUMAN That's why you go places, isn't it?
TRUMAN Cos you're curious.
TRUMAN I haven't been curious since I was seven years old, y'know that?
TRUMAN Back then you'd have to nail me to the floor to keep me in one place.
All eyes watch the large monitor as surveillance cameras track Truman's speeding car.
CHRISTOF How long to take Atlantic City out of mothballs?
SIMEON We could be up and running...three hours maybe.
CHRISTOF Give me a number five gridlock on the Jersey Turnpike.
TRUMAN and MERYL are hemmed in by a traffic snarl on the New Jersey Turnpike.
We observe the Oldsmobile on a television lens from the POV of a tail-light on the car ahead.
TRUMAN So much traffic, this time of day.
TRUMAN Does that strike you as peculiar?
On the side of the road, TWO MOTORISTS, are arguing over a minor collision.
TRUMAN Look at them.
TRUMAN You believe they're fighting?
TRUMAN I don't believe it.
TRUMAN Why don't you slug him, really make it authentic?
Without warning, Truman suddenly exits the freeway.
But his move is anticipated.
At the end of the offramp a pack of cars suddenly appears.
Other vehicles fill the gap behind.
TRUMAN Blocked at every turn.
TRUMAN Beautifully synchronized, don't you agree?
MERYL You blaming me for the traffic?
TRUMAN Should I?
MERYL You've never been on this road before.
MERYL You don't know what it's like.
TRUMAN That's true.
TRUMAN We could be stuck here for hours.
TRUMAN Could be like this all the way to Atlantic City.
Truman suddenly veers the Oldsmobile onto the sidewalk.
MERYL What the hell are you doing?
TRUMAN You're right.
TRUMAN Let's go back.
TRUMAN I'm sorry.
TRUMAN I don't know what got into me.
Truman rejoins the New Jersey Turnpike, heading back towards Queens, the roadway now relatively free of traffic.
MERYL Would you please slow down, Truman?
Truman floors the Oldsmobile.
The car flies past the exit for Route 276.
He continues along the Jersey Turnpike.
MERYL Truman, that was the turnoff!
TRUMAN I've changed my mind again.
TRUMAN What's Maine like this time of year?!
TRUMAN I've never been to Maine.
TRUMAN Or let's just see where the road takes us.
MERYL Let me out, Truman.
MERYL You're not right in the head.
MERYL You wanna destroy yourself, you do it on your own!
TRUMAN I think I'd like a little company.
CHRISTOF, CHLOE, SIMEON and the other OPERATORS follow Truman's progress from a helicopter shot - the Oldsmobile optically circled to ease identification.
Christof jabs his finger at the rapidly thinning traffic surrounding Truman's vehicle.
CHRISTOF What the hell is wrong with the "carousel"?
CHRISTOF Keep them together.
SIMEON They're rusty.
SIMEON We can't keep up.
SIMEON We don't know where he's going any more.
CHLOE Oncoming is very thin.
As he speeds erratically, TRUMAN glances at the streets either side of the freeway, where he discovers a distinct lack of moving traffic.
TRUMAN Look down there, Meryl!...No cars!
TRUMAN I don't run into traffic.
TRUMAN The traffic follows me around.
TRUMAN We're in a moving pack, don't you see?
Truman abruptly exits the rapidly emptying freeway.
CHRISTOF He's so close!
CHRISTOF It's tantilizing!
CHLOE You want to pull him over?
CHRISTOF No police.
CHRISTOF Not yet.
CHRISTOF We shadow him.
CHRISTOF We don't want him to panic.
CHLOE He's trying to outrun the traffic.
CHRISTOF He's trying to outrun the world.
CHRISTOF Keep him on this route.
CHRISTOF Are we ready?
Simeon nods.
Executives, MOSES and ROMAN have entered the control room.
They hover nervously in the background.
TRUMAN is forced to slow once again behind a line of other cars at a police roadblock.
At the head of the line, the cars are being turned around by POLICE OFFICERS, who are also contending with a swarm of NEWS REPORTERS and TELEVISION CREWS.
TRUMAN It's hard to go places, isn't it?
MERYL There's been an accident, Truman.
MERYL We have to go back.
TRUMAN No.
TRUMAN There's no accident.
TRUMAN It'S just more stalling.
Truman slows beside a POLICE OFFICER.
TRUMAN What's going on?
OFFICER Leak at the plant.
OFFICER They had to shut her down.
TRUMAN Is there any way around?
OFFICER The whole area's being evacuated.
OFFICER A precaution.
Truman falls in line behind the cars making a U-turn when, all of a sudden, he guns his car and swerves past the barricade.
In the twilight sun, SYLVIA'S GUESTS wander up the gravel path, leading away from the beach house, the younger children carried in their parents' arms.
Hanging back from the rest of the group, Sylvia's admirer, wheeling his bicycle, turns back to the house.
As the MAN is about to lean his bicycle against the side of the beach house, he looks in a window.
Lit by a blue-glow, SYLVIA sits transfixed by the television playing in her antique bureau, the screen obscured from our view.
She is unaware of the man's face at the window.
Recognizing what is playing on the screen, the man regards Sylvia with a resigned smile.
He mounts the bicycle and rides back up the path.
Truman's car slides to a stop, blocked by Hazardous Waste vehicles straddling the roadway leading up to the power plant, the pursuing police car blocking his retreat.
TRUMAN flees the car, leaving MERYL in the passenger seat.
MERYL Truman!!
MERYL Come back!!
Truman bursts past the alien-looking HAZARDOUS WASTE WORKERS in their protective suits carrying detection instruments.
The workers give chase in their cumbersome suits, trying to cut off his path to the power plant.
As he crests a slight rise beyond the plant, he is finally tackled to the ground.
However, peering through the long grass, Truman is able to make out the lights of a cityscape in the distance.
CHRISTOF, a trace of panic in his eyes, turning to CHLOE.
CHRISTOF Did he see it?
CHLOE I don't think so.
The reason for Christof's concern becomes all too apparent as the helicopter passes over the power plant, where the struggling TRUMAN is being escorted away.
We see an aerial shot from the helicopter as it emerges directly above the Sydney skyline.
MERYL and TRUMAN sit at their kitchen table.
Truman stoic, tears rolling down Meryl's cheeks.
Truman's airline ticket torn to shreds on the table in front of them.
MERYL Let me get you some help, Truman.
MERYL You're not well.
TRUMAN Why do you want to have a child with me?
TRUMAN You can't stand me.
MERYL That's not true.
TRUMAN Don't lie to me!
Truman's raised voice backs Meryl to her feet.
Truman follows, getting in her face.
TRUMAN Tell me what's happening?!
MERYL I thought you knew everything.
MERYL What could I tell you?
TRUMAN You're part of this, aren't you?!
Meryl grabs a kitchen knife from a wooden block to protect herself.
MERYL Truman, you're scaring me!
Truman looks in her eyes and, with surprising swiftness, grabs her wrist and disarms her.
TRUMAN No, you're scaring me, Meryl!
Truman grabs Meryl by the hair and turns the knife on her.
While pressing the blade to Meryl's throat, Truman starts to march her around the room, talking to the walls, light fixtures, a mirror, doorknob, framed picture, blank television.
TRUMAN Stop this now or I kill your leading lady.
TRUMAN I know you can hear me.
CHRISTOF and the OTHERS watch the monitors spellbound as TRUMAN looks directly into one camera lens after another.
ROMAN is the first to crack.
ROMAN Get somebody in there!
CHRISTOF No.
SIMEON She's in trouble!
SIMEON We've got to help her!
Christof, never taking his eyes from the monitor, leans into the microphone.
We see an extreme close up of MERYL's ear.
Unheard by TRUMAN, from her inner car, we hear a familiar voice.
CHRISTOF (O.C.) He's bluffing.
CHRISTOF (O.C.) Call his bluff.
MERYL Do something...
Upon hearing her remark, Truman's eyes widen.
Sensing that she too is addressing a third person, he jerks her head around to read her face.
TRUMAN Who are you talking to?!
MERYL You're the one talking to the walls!
TRUMAN No.
TRUMAN You said, "Do something."
TRUMAN Who were you talking to?
TRUMAN I swear I'll kill you, if you don't tell me.
Meryl takes the chance to spin out of his grasp and dashes to the bedroom but before she can barricade the door, Truman forces his way inside.
They both tumble onto the waterbed causing it to rock back and forth.
Gripping Meryl's hair, Truman throws aside the bed covers.
TRUMAN How could you buy this damn thing when you know he drowned in front of me?!
Truman raises the kitchen knife but instead of stabbing Meryl begins to slash viciously at the waterbed, opening a large gash.
TRUMAN You have any idea what it's like to drown?
Truman drops the knife and forces Meryl's head into the gaping hole in the bed, submerging her head in the tepid water.
She thrashes her arms wildly trying to free herself.
Truman reluctantly jerks her head back out of the water.
MERYL Truman, stop it!
MERYL Don't let him do it!
TRUMAN I'll kill her!
He dunks her head into the water a second time, holding her head down longer this time.
She continues to struggle.
Suddenly, the front door chimes.
Startled, Truman lets Meryl up for air.
TRUMAN Right on time.
TRUMAN Cops must be telepathic.
Meryl spots the kitchen knife within her reach but Truman beats her to it.
Grabbing the knife by the blade, he slices his hand.
TRUMAN Damn!
At knifepoint, Truman marches Meryl down the hallway to the front door.
The doorbell chimes a second and third time, more insistently.
TRUMAN Stay where you are or I'll kill her!
MARLON (O.C.) Truman?
MARLON (O.C.) It's me, Marlon.
Truman flinches.
He was so convinced it would be the police.
He takes a step back against the hallway wall.
Before he can decide what to do, Marlon has opened the unlocked front door to be confronted with the sight of Truman holding the knife to Meryl's throat, blood streaming from his own wound.
Marlon locks eyes on Truman.
Sizing up the situation, he slowly but decisively removes the knife from Truman's hand.
Meryl wrenches herself free from Truman's now limp grasp, and collapses into Marlon's arms, sobbing.
MERYL They were going to let him kill me!
MARLON and TRUMAN, both nursing bottles of beer, sit on the end of their abandoned freeway off-ramp.
TRUMAN People know who I am, my every move, complete strangers know my name.
TRUMAN Even when there's no one around, I feel the eyes on me.
MARLON I was in the bank today.
MARLON The Federal on Lewis.
MARLON A clerk was talking about somebody named Truman messing with her baby.
MARLON Is that the stranger you're talking about?
Truman closes his eyes as he takes in the explanation.
TRUMAN No.
TRUMAN No.
TRUMAN I've never seen her before.
TRUMAN I know you already think I'm going out of my mind but I genuinely believe the world revolves around me somehow.
TRUMAN Everybody seems to be in on it.
MARLON It's a lot of world for one man.
MARLON You sure that's not wishful thinking, you wishing you'd made something more of yourself?
MARLON Christ, Truman, who hasn't sat on the John and had an imaginary interview with Barbara Walters?
MARLON Who hasn't wanted to be somebody?
TRUMAN That's just it.
TRUMAN I think I am somebody.
MARLON I used to dream all my friends and family got together in a hotel room, thinking of ways to fuck me up.
TRUMAN Sometimes I think it's in my head, sometimes I think it's for real.
Marlon looks around as if drawing inspiration from somewhere in the night.
MARLON Tru, we've known each other since before we could get a hard-on.
Truman half-smiles at the ribald remark.
MARLON The only way we ever made it through high school was cheating off each other's test papers.
MARLON Jesus, they were identical.
MARLON I always liked that, because whatever the answer was, we was right together and we was wrong together.
Truman nods fondly at the memory.
MARLON The only night either of us ever spent in jail, we spent together and I wet myself but you never told anyone.
MARLON I was best man at your wedding and my brother was best man at my wedding and you didn't talk to me for a month over that and I didn't blame you because you've been more of a brother to me than he's ever been.
MARLON And I never shoulda let my Goddam father talk me into that.
Truman is slowly coming around.
Marlon's speech from the heart soothing away his pain.
MARLON I know things haven't worked out for either of us like we used to sit up on Freemont Street all night and dream they would.
MARLON We all let opportunities pass us by, none of us asks for the dance as often as we should.
MARLON I know that feeling when it's like everything's slipping away and you don't want to believe it so you look for answers someplace else.
MARLON But, well, the point is, I would gladly step in front of traffic for you.
Truman grins a melancholy grin, nearly all the way back.
We see a close up of Marlon's ear.
From inside, unheard by Truman, CHRISTOF dictates Marlon's heartfelt speech.
CHRISTOF leans over a microphone at the mixing desk, feeding the lines to Marlon, immersed in the role.
CHRISTOF ...and the last thing I'd ever do is lie to you...
Recognizing the importance of the moment, his colleagues stand around in awe at Christof's spontaneous performance, arguably superior to Marlon's own delivery.
MARLON And the last thing I'd ever do is lie to you.
MARLON Think about it, Truman, if everybody's in on it, I'd have to be in on it too.
MARLON I'm not in on it cos there is no it.
Truman's head slowly drops in surrender, his doubts draining away.
Marlon embraces Truman in a bearhug.
Truman looks over his shoulder to the sky where a single star shines.
From his chair, CHRISTOF modestly accepts the congratulations of his COLLEAGUES.
The two executives, MOSES and ROMAN are at the head of the line, their earlier disagreement suddenly forgotten.
CHLOE gives Christof a warm hug.
MARLON, accepting a towel from a P.A., still in wardrobe, approaches and kneels beside the arm of Christof's chair.
grasping his hand.
MARLON I can't thank you enough.
MARLON I don't know what happened.
MARLON He was so close.
MARLON It threw me.
MARLON I'm indebted.
Christof gives Marlon a consoling pat on the shoulder and Marlon withdraws.
Finally Christof's Assistant Director, SIMEON, approaches and offers his hand.
Christof hesitates before shaking.
Simeon returns to the monitors, now showing TRUMAN alone at the dock or Long Island.
Christof stares out the window to conceal an expression of quiet vindication.
The two OLD WOMEN we have seen before sit on their sofa gazing straight ahead.
On the teievision in front of them, a live picture of TRUMAN - the first time we have seen him broadcast to a viewer's set.
He is reading a book at his kitchen table, unaware of the cameras recording him.
The scene alternates between a wide master shot, a medium tight shot, a close up of Truman's face and two insert shots - one over the shoulder shot of the page he is reading and one from another angle showing the book's title, "To The Ends Of The Earth - The Age Of Exploration".
At one point, a sponsor's border appears on screen, tastefully framing the "action" with the message, "FOLGERS Coffee - Good To The Last Drop."
After several seconds, the border disappears.
Suddenly tbe live picture of Truman shrinks into a window on the screen to accomodate a title sequence that begins to piay around the edge of the image.
Overlapping scenes from Truman's life appear in chronological order, from infancy to adolescence and finally adulthood.
A graphic, "TRUMAN - Total Record Of A Human Life", appears on screen accompanied by an introductory narration.
NARRATOR (O.C.) You are watching "Truman - Total Record Of A Human Life".
NARRATOR (O.C.) Everything that occurs here is real.
NARRATOR (O.C.) There are no re-creations or interruptions.
NARRATOR (O.C.) Due to the live and unedited nature of the program, viewer discretion is advised.
The title sequence is replaced by an INTERVIEWER, mid-fifties, conservative suit and hair, sitting opposite CHRISTOF in a Larry King-style interview setting.
Projected in the background is the live picture of Truman, immersed in his book.
INTERVIEWER Welcome to week seventeen hundred and sixty eight of "Truman" and there can scarcely have been a more momentous week in the show's history.
INTERVIEWER I'm your host, Michael Conners, and this is a special edition of "Tru Talk", the forum where we discuss and analyze recent events with the show's award-winning creator and producer, Christof.
INTERVIEWER I remind viewers that as this is a living history, it is our practise to keep the image of Truman on screen at all times.
INTERVIEWER Welcome.
CHRISTOF Thank you.
INTERVIEWER Before we start taking calls, the huge surge in ratings over the last few days, how do you hope to sustain that audience now that Truman appears to have reconciled himself, returned to "normal"?
CHRISTOF Ratings have never been our primary goal.
CHRISTOF I imagine we'll lose those voycurs only interested in witnessing Truman's latest torment.
CHRISTOF However I'm certain our core audience will remain loyal.
INTERVIEWER But recent events have been so dramatic, it does raise the perennial question.
INTERVIEWER What keeps us watching one man twenty-four hours a day - eating, sleeping, working, sitting for hours in contemplation?
CHRISTOF It has to be the reality.
During this segment, we cut to a cross-section of VIEWERS - the NIGHTWATCHMEN, the two OLD WOMEN on their sofa, the BARMAN and the WAITRESS - listening to Christof's theories on their viewing habits.
CHRISTOF We've become increasingly frustrated watching actors give us phony emotions, bored with pyrotechnics and special effects.
CHRISTOF While the world he inhabits is counterfeit, there's nothing fake about Truman himself.
CHRISTOF No scripts.
CHRISTOF no cue cards.
CHRISTOF It's not always Shakespeare but it's genuine.
CHRISTOF That's how he can support an entire channel.
INTERVIEWER A window onto the human condition?
CHRISTOF I prefer to think of it as a mirror.
CHRISTOF Not only does he give us a glimpse of the truth, he gives us a glimpse of ourselves.
INTERVIEWER But how do you account for the popularity of those eight hours a day when Truman sleeps?
CHRISTOF We find many viewers leave him on all night for comfort.
CHRISTOF Haven't you ever watched your child or your lover sleep?
INTERVIEWER Let's go to some of those viewers' calls.
The Interviewer presses a blinking illuminated button on his desk's high-tech phone terminal.
INTERVIEWER Charlotte, North Carolina, for Christof.
MALE CALLER 1 (O.C.) Hello?
INTERVIEWER You're on, caller.
INTERVIEWER Go ahead.
MALE CALLER 1 Christof, it's a great honor to speak with you.
CHRISTOF Thank you.
MALE CALLER 1 Truman has never been closer.
MALE CALLER 1 The way he looked directly at us, spoke to us for the first time.
MALE CALLER 1 Do you think he'll ever work it out?
CHRISTOF I don't believe so.
CHRISTOF Not now.
CHRISTOF He tested his world, as we all do at certain times, and eventually it passed the test.
CHRISTOF You have to understand, he is a man made-for-TV, the world he occupies his only frame of reference.
CHRISTOF No, for him to come even this close to the truth is a remarkable testament to his instincts.
The Interviewer presses another line on his terminal.
INTERVIEWER Sacramento, California, you're on "Tru Talk".
MALE CALLER 2 (O.C.) How much of a strain has the last few days placed on the actors?
CHRISTOF Working on "Truman" has always been a huge commitment for an actor, not just in terms of separation from friends and family, but since Truman essentially drives the plot, it's a never-ending improvisation.
CHRISTOF Recent events have raised the pressure but also the prestige.
INTERVIEWER Of course Truman has always been very much in on casting.
CHRISTOF As with our own lives, the only people he can't cast are his family.
CHRISTOF Otherwise he has final approval, able to elevate an extra into a lead role as was the case with his only real friend, Marlon, or alternatively relegate a star to a bit player.
INTERVIEWER Istanbul, Turkey, you're on with world-renowned videographer, Christof.
MALE CALLER 3 (O.C.) Christof.
MALE CALLER 3 (O.C.) I've admired your work my whole life, although I can't say I've seen it all.
CHRISTOF Who can?
MALE CALLER 3 Can you settle an argument for me?
MALE CALLER 3 What's the longest time Truman has been off-camera?
CHRISTOF In his entire life, forty-two minutes.
CHRISTOF A technical fault in 1978 accounts for most of that time.
CHRISTOF The remainder generally results from blindspots, in the early days, when Truman would stray out of range of our cameras.
INTERVIEWER The Hague for Christof...The Hague?...lost them.
INTERVIEWER Amagansett, Long Island, you're on "Tru Talk".
FEMALE CALLER 1 (O.C.) How can you say Truman lives a life like any other?
CHRISTOF I believe that to be so.
CHRISTOF I often feel the only difference between Truman's life and our own is that his is being more thoroughly documented.
CHRISTOF We all play our allotted roles--
FEMALE CALLER 1 (O.C.) --He's not a performer.
FEMALE CALLER 1 (O.C.) He's a prisoner.
The Interviewer goes to cut off the call but Christof holds him back.
CHRISTOF --He can leave at any time.
CHRISTOF If his was more than just a vague ambition, if he were absolutely determined to discover the truth, there's no way we could prevent him.
CHRISTOF I think what really distresses you, caller, is that ultimately he prefers the comfort of his "cell"--
FEMALE CALLER 1 (as if trying to convince herself.
FEMALE CALLER 1 giving herself away) --No, you're wrong!
FEMALE CALLER 1 He'll prove you wrong!
FEMALE CALLER 1 He can still do it!
CHRISTOF Do I know you, caller?
CHRISTOF Your voice sounds familiar.
SYLVIA, finger on the button of the phone where she has cut off the call, stares at CHRISTOF on her television screen.
It is she who is the Female Caller.
Christof seems to stare back at her as the talk show continues.
INTERVIEWER Recording a human life from birth to death, that's still the intention?
INTERVIEWER You still believe Truman has more to contribute?
CHRISTOF More than ever.
CHRISTOF By unwittingly allowing us to witness his struggles, he's constantly forcing us to evaluate our own lives.
CHRISTOF He gives us hope.
INTERVIEWER Let's take another call.
INTERVIEWER London, England you're on "Tru Talk".
FEMALE CALLER 2 By definition Truman has to be free of censorship, but has the recent violence and profanity caused a problem for the sponsors...?
Sylvia shuts out the conversation on the television, focusing on the window that displays TRUMAN, still buried in his book.
She comes close to the screen, catching his melancholy.
She has a camera and a white envelope in her hand.
With a look of resolve, she takes her fountain pen and writes Truman's name on the envelope in her familiar blue ink.
Row upon row of digital video cassettes occupy one entire, cavernous room - "Truman" and a date on the spine of each cassette.
Suspended from the ceiling, a monitor shows a live picture of TRUMAN sleeping on the sofa.
Sitting in front of a playback monitor, CHLOE is transfixed by Truman thirty-four years earlier, a FETUS in his mother's womb.
CHRISTOF (O.C.) What are you looking for?
Chloe tries to conceal her startlement at CHRISTOF's unexpected entrance.
CHLOE He was premature, wasn't he?
CHRISTOF Only by two weeks.
CHLOE Curious even then?
CHLOE Like he couldn't wait to get started?
CHRISTOF His eagerness to leave his mother's womb also meant he was the one selected.
CHLOE What was it like, the first show?
CHRISTOF The ultimate live television.
CHRISTOF In competition with five other unwanted pregnancies - the casting of a show determined by an air date - he was the one who arrived on cue.
CHLOE Is it true what you said...on the show tonight?
CHLOE About letting him go if he wanted it badly enough.
CHLOE Would you really do that?
Christof stares at his assistant, weighing her loyalty.
CHRISTOF It won't come to that.
The suitably crestfallen TRUMAN stands in front of his boss, ERROL, sitting behind his ostentaciously large desk.
LAWRENCE lounges on the guest sofa, enjoying Truman's dressing-down.
TRUMAN approaches the bank window.
The teller is the YOUNG WOMAN whose child Truman attacked in the street.
She takes a step back at the sight of Truman, apprehensive, the confrontation fresh in her memory.
Truman glances at the names on the checks in the young woman's hand, realizing how she was able to identify him in the street.
He begins to apologize profusely.
TRUMAN enters the garage, carrying Sylvia's sweater.
He breathes in the scent one last time and reluctantly replaces it in the trunk.
With a sense of finality, he lowers the lid and fastens the lock.
TRUMAN emerges from the garage, wheeling his lawnmower, deliberately averting his eyes from the back of the house.
Staring out of the kitchen window, a tall glass of iced tea in her hand, MERYL has been anticipating her husband's appearance.
She wears a neckbrace, we sense more as a reminder to Truman than for any benefit she might derive.
Feeling Meryl's eyes burning into his back, Truman fires up the mower and heads directly towards the symbolically uncut section of grass.
We focus on the errant blades of grass as they are severed by the mower.
The lawn is now uniformly trimmed.
From a mechanical platform above the Expressway, CHRISTOF and CHLOE watch Truman's final act of defiance laid to rest.
In an office building high above Manhattan's financial district, a ROBOTIC MANNEOUIN in a 3-piece suit stands at an upper-story window mechanically lifting a coffee cup to its mouth.
In the street below, something is different about the rush-hour traffic.
The PEDESTRIANS are all standing around, no one walking.
Some are chatting with each other, others primping.
The cars, vans and taxis are also idling.
Camera locations are being checked.
A miniature camera inserted into the head of a streetlamp, a CAMERA TECHNICIAN waves his hand in front of an innocent-looking fire hydrant, the eye of a MDDEL on a bus shelter's cosmetic ad is wiped clean, the head of a parking meter is replaced, a buttonhole camera is placed on a BUSINESSMAN's double-breasted jacket by a TECHNICIAN - we see from the button's POV, a CONTACT LENS CAMERA is carefully inserted into the eye of Truman's colleague, LAWRENCE, another TECHNICIAN we observe from the contact's POV.
Finally a surveillance camera on the outside of a bank building and a TOURIST'S camcorder are positioned.
CHRISTOF is seated at the control desk, directing the morning session, SIMEON assisting, CHLOE at his shoulder, a buzz of excitement in the room.
CHRISTOF I hope we've got fresh extras.
CHLOE The rotation was made this morning.
CHRISTOF I don't like the couple with the baby.
CHRISTOF They'd never be together.
The COUPLE with the stroller are promptly moved further along the street.
CHRISTOF Who's doing wardrobe?
CHRISTOF I keep seeing the same wardrobe...
TRUMAN spills out of the subway car with hundreds of other COMMUTERS.
We hear Christof's off-camera voice, as always unheard by Truman.
CHRISTOF (O.C.) ...everybody back to One...
CHRISTOF (O.C.) ...and, action background...
At the command, the PEDESTRIANS and VEHICLES begin inoving normally, TRUMAN exits the subway, suspecting nothing.
He begins his trek to work, accompanied by the cued rush hour traffic.
CHRISTOF (O.C.) ...nice...nice...I like the woman with the dog...
CHRISTOF (O.C.) let's keep it moving...I want that traffic kept together...everybody look like you've got places to go...
CHRISTOF covers his microphone to deliver an aside to SIMEON, from whom he has temporarily assumed the role of director.
CHRISTOF I bet he doesn't stop at the newstand.
As predicted, Truman walks by, barely glancing at a newspaper's banner headline, "NUCLEAR POWER PLANT REOPENED".
Christof scans the shot options available to him on the video wall.
CHRISTOF ...Bodycam Two...
The large On-Air Monitor cuts to Truman, via the point-of-view of an approaching PEDESTRIAN.
For an instant, the unaware Truman looks directly into the lens of the disguised camera.
CHRISTOF ...streetlight eight...
The monitor cuts to an overhead shot from a streetlamp.
The camera continues to follow Truman's progress.
CHRISTOF ...ready, Car-Cam One.
CHRISTOF Go to One...
TRUMAN enters his office building as a taxi cruises by.
CHRISTOF ...and cut to interior...
Truman is immediately picked up by a hidden camera inside the building where he exchanges a half-hearted greeting with an ancient SECURITY GUARD.
CHRISTOF ...looser...
The camera widens the angle.
CHRISTOF ...and action, Vivien...
CHRISTOF Looks just like Truman's mother at that age.
VIVIEN, an insurance adjuster approaches the elevator button at the same time as Truman.
However she reaches for it after Truman has already turned his back.
CHRISTOF Damn, she missed her mark!
CHRISTOF Why do we bother with walk-throughs if nobody pays attention?
CHRISTOF Give me a two-shot of Truman and Vivien...go to the master ...hold the elevators...
CHRISTOF Vivien, press the elevator button again ...and make sure you catch his eye this time...
A second time, TRUMAN's brief encounter with VIVIEN goes like clockwork.
As instructed, she hammers away at the elevator button and throws a conspiratorial look to Truman.
The elevator car duly arrives and Truman's eyes follow Vivien's rear as she sachets into the lift.
For a moment he appears to glance at a piece of gaffer tape on the marble floor.
CHRISTOF Good!
CHRISTOF Perfect!
CHRISTOF Cut to the interior...
The monitor cuts to the inside of the elevator, rapidly filling with co-workers.
CHRISTOF ...and Lawrence...
Just as the doors are about to close, LAWRENCE oozes in.
He gives Truman a smug smile.
CHRISTOF ...nice look, Lawrence...and, Vivien...
The elevator doors open and Vivien exits with two co-workers.
LAWRENCE I wouldn't kick her out of bed.
Truman doesn't seem to share Lawrence's enthusiasm for the comely young woman.
He is miles away.
Assembled around a long oval table for a story confernce are several principal characters in Truman's life - MERYL, MARLON, ERROL, TYRONE, RAQUEL, VERONICA and the new actress, VIVIEN, sitting slightly apart from the rest of the cast.
CHRISTOF takes his place at the head of the table, a large monitor showing TRUMAN drinking coffee in his cubicle at American Life plays silently behind Christof's head.
CHRISTOF Regrettably, I have to inform you that Hannah has chosen not to renew her contract.
All eyes turn to Meryl.
She looks at the floor.
CHRISTOF I'm sure we can all respect her reasons.
Meryl receives a sympathetic squeeze of the hand from her co- star Marlon, now out of wardrobe, wearing an Armani suit.
CHRISTOF Her separation from Truman will be orchestrated over the summer.
CHRISTOF However, I'm pleased to announce that television's first on-air conception will still take place.
CHRISTOF You witnessed the initial contact this morning.
CHRISTOF You all know Claudia from her work in theatre.
CHRISTOF Thankfully, Truman doesn't.
The rest of the cast nod politely in Vivien's direction.
CHRISTOF This is a copy of Claudia's back story.
CHRISTOF Her character's name will be Vivien.
CHRISTOF She's the new adjuster at the office.
The cast idly flip through the documents, prominently stamped on the cover, "NOT TO BE TAKEN ON SET".
CHRISTOF We intend to entice Truman into the affair as soon as possible.
CHRISTOF Claudia will make her advance at the seminar Truman's attending next week.
CHRISTOF Details are in your schedules.
CHRISTOF I'm sure you'll all make Claudia welcome.
MARLON Question is, will Truman make her welcome?
The cast snickers.
CHRISTOF I don't have to tell you, how critical the next few weeks will be.
CHRISTOF This takes us into the next generation.
CHRISTOF When Truman's child is born, the network will be switching to a two-channel format to chronicle both lives.
VIVIEN What happens when Truman and the baby are both on camera together?
CHRISTOF There will simply be duplicate coverage.
VIVIEN Let's just hope we don't have twins.
CHLOE When Truman dies do we go back to the single channel?
The cast turn in her direction.
Christof has a second occasion to question his Assistant's loyalty.
The BARMAN, WAITRESS and PATRON we have seen before, observe TRUMAN on the television above the bar.
The cameras track Truman's progress, walking along Broadway.
As he ducks into a sex shop, the threesome at the bar exchange looks.
Inside the store, Truman appears apprehensive.
BARMAN What's he doing in there?
PATRON Meryl's at her mom's.
PATRON Maybe he's got an urge.
On screen, Truman looks through some X-Rated video titles.
WAITRESS What's with the coat?
BARMAN Maybe he doesn't wanna be recognized.
Truman bumps into a display of sex paraphenalia, knocking an item to the floor.
PATRON Nervous.
Truman tries to right the display and hurriedly exits the store, the cameras following his journey as always.
BARMAN Oh God, he never bought nothing.
WOMAN Give him a break.
WOMAN It's taken him thirty- four years to get the nerve to go in there.
We focus on a list left by Meryl on the refrigerator, several pages long.
The kitchen itself is a bombsite.
More than the cliche dishes in the sink - dozens of cardboard boxes stacked haphazardly on the floor.
The usually orderly bedroom is also a mess.
Blankets piled in a heap.
Several large, half-filled cardboard boxes cluttering the room.
A chair in an odd position near the bed.
Clothes strewn everywhere.
Hardly an inch of floor space remains uncovered.
TRUMAN is asleep in bed, the damaged waterbed replaced with a standard mattress.
Although he is completely covered from head to toe in bedding, the outline of his body is still clearly visible.
Close up on the On-Air monitor in the temple of a control room.
It displays a wide shot of Truman's darkened bedroom filmed through the green hue of the night vision cameras.
Assistant Producer, SIMEON, and his VIDEO OPERATORS slouch in their swivel chairs paying scant attention to the screen.
Simeon gives his instructions in a lethargic, metronomic manner.
SIMEON ...Ready two.
SIMEON Go to two.
Operator, eating a doughnut, presses one of the illuminated buttons on the panel and the camera angle changes to a close shot of Truman's covered head.
The camera stays on the blanketed head for a long moment.
SIMEON And back to the medium.
Another button is pressed and the angle changes.
A trace of frustration is evident in the control room.
Recording a sleeping subject is unrewarding enough without also having to contend with Truman's recently aquired camera-shyness.
SIMEON ...and wide...
OPERATOR Could we have picked a bigger loser if we tried?
SIMEON That loser pays our salary.
OPERATOR He's given up on himself again.
SIMEON Who cares?
SIMEON Makes life easier for us.
SIMEON He is what he is.
At the far end of the great room, one of the large double doors opens and CHRISTOF enters, as always accompanied by CHLOE, carrying a leather-bound folder.
Simeon and the Operators subtely straighten in their chairs.
Christof pretends not to notice.
He is staring intently at the On-Air monitor.
CHRISTOF When did he start sleeping like that?
SIMEON About the time Meryl left.
CHRISTOF Is that the best shot we can get?
SIMEON What's to see?
Christof watches Truman, a trace of concern in his eyes.
CHRISTOF What happened to the room?
SIMEON He started to reorganize.
SIMEON I was going to call you.
SIMEON But half-way through, he gave up and fell asleep.
Apparently satisfied, Christof turns to an operator.
CHRISTOF I want to check the set-ups for tomorrow's insurance convention.
Reading off the notes in Chloe's folder, the operator punches up a batch of camera angles on smaller preview monitors.
They show a generic-looking Marriott Hotel, devoid of actors.
A banner in reception reads, "WELCOME AMERICAN LIFE & ACCIDENT".
The Operator looks to Christof for approval and realizes his producer's attention has wandered.
Christof is staring at the sleeping figure of Truman on the On-Air monitor.
CHRISTOF Give me a shot from his wedding band.
SIMEON He took it off.
CHRISTOF Why is he so still?
CHRISTOF He's too still.
Christof picks up a spare headset from the panel and puts it to his ear.
CHRISTOF Isolate the audio in the cans and amplify.
An operator pushes up an audio fader on the panel.
Christof and his colleagues listen to Truman's steady breathing in their headphones.
Simeon and the Operators nod, reassured that nothing is amiss.
Christof is not so easily convinced.
CHRISTOF Give me a preview.
CHRISTOF An ECU on his torso.
A camera hidden in the room's bedside lamp zooms in to Truman's prone outline...while the breathing remains steady, the body does not rise and fall.
CHRISTOF Phone him.
Chloe picks up a phone connected to the desk and dials.
CHRI STOF Wrong number.
The phone on the bedside table, inches from Truman's head, begins to ring.
Truman doesn't flinch.
SYLVIA walks up from the seashore where she has been taking a late night swim.
Hearing the telephone ringing; she rushes to pick it up.
However, after lifting the receiver, the phone continues to ring.
The sound is coming from her television, left on in the bureau.
On the screen, TRUMAN sleeps, seemingly undisturbed by the call.
Sylvia, drying herself, watches with fascination.
CHRISTOF and the CREW are now highly agitated.
CHRISTOF He didn't drink tonight?
CHRISTOF No pills?
Every question receives a shake of the Assistant's head in reply.
CHRISTOF Hang up!
Chloe promptly cuts the connection and Truman's phone ceases to ring.
CHRISTOF Get Marlon over there.
CHLOE Under what pretext?
CHRISTOF Any fucking pretext!
Christof turns his back on the monitors, his mind racing.
MARLON's car squeals to a halt outside Truman's house.
Hurriedly dressed in jeans and coat over a bare chest, he dashes barefoot to the front door.
He tries the doorhandle, pounds on the door and rings the doorbell simultaneously, shouting Truman's name all the while.
MARLON Tru!..Tru!..
Frustrated, Marlon runs to the bedroom and thumps on the window.
He can see the shape of Truman lying on the bed but his shouts fail to rouse him.
Marlon picks up one of Meryl's carefully nurtured flower pots from beneath the bedroom window.
MARLON I'm comin' in, Tru!
Marlon hurls the flower pot through the window sending a shower of glass over Truman's bed.
Still he doesn't move.
Marlon reaches his hand through the shards of glass clinging to the window frame and unlatches the window.
MARLON clanbers headfirst through the opened window and lands in an awkward heap on the floor beside TRUMAN's bed.
He pushes away the clutter in the bedroom and finally stands at his co-star's bedside.
There is a hissing sound.
Marlon gingerly lifts the bedcover.
Beneath the bedding is a life-size inflatable female doll.
The doll has been punctured by the glass and is slowly deflating.
Lying beside the doll's chest is Truman's portable tape recorder.
Marlon picks up the recorder and places it next to his ear.
The cassette plays the sound of Truman breathing.
CHRISTOF, wide-eyed, stares at the image on the On-Air monitor of MARLON and his bizarre companion.
Marlon is frozen, staring into camera.
CHRISTOF Cut transmission.
Simeon hesitates, unsure if has heard correctly.
He looks to Christof for confirmation, his finger poised over an "EMERGENCY" button.
CHRISTOF I said, "Cut"!
Christof lunges forward and presses the button himself.
SYLVIA watches agog as the scene in Truman's bedroom on her television screen is replaced by the "TRUMAN" logo and the message, "TECHNICAL FAULT.
PLEASE STAND BY."
CHRISTOF has taken his place at the control panel.
On the bank of monitors in front of the mixing desk, the OPERATORS systematically search through the numerous set-ups in Truman's home and neighborhood.
Occasionally MARLON or an EXTRA appear in frame as they fan out and begin a man-hunt.
While the on-Air monitor continues to play its test-card, Christof and Simeon concentrate on another isolated monitor playing in fast-rewind, time code in the bottom right corner.
It is a recording of the night's transmission.
Simeon stops on the last on-camera appearance by TRUMAN.
They watch Truman, on-screen, switch off his bedroom light and climb into bed fully clothed, immediately pulling the covers over his head.
As the light is switched off, the recording camera automatically switches to night vision.
Simeon continues to play at normal speed, now and then scrolling forward in fast- forward mode.
Christof suddenly points to the screen.
CHRISTOF There.
CHRISTOF Freeze...Zoom into the chair...
Simeon types the appropriate command.
CHRISTOF Enhance.
On the blown-up screen, between a cardboard box and a chair leg, it is barely possible to make out Truman's hand as he crawls commando-style from his bedroom, his inflatable replacement already positioned in the bed.
CHRISTOF He wasn't making a mess.
CHRISTOF He was engineering a blind spot.
CHLOE How does he know where the cameras are?
CHRI STOF I don't know.
CHRI STOF All I know is we've been filming a blow-up doll for the last three hours.
Simeon feels the hostility.
The systematic search of the monitors continues.
They now reveal that dawn has broken on the set.
SIMEON We've declared a curfew.
SIMEON Only the extras required for the search are on the set.
SIMEON Everyone else is at first positions.
CHRISTOF All prop cars accounted for?
SIMEON He has to be on foot.
SIMEON He has the world's most recognizable face.
SIMEON He can't disappear.
All heads turn to CHLOE as she enters the grand control room with a status report.
CHLOE The sponsors are threatening to pull the plug if we don't make a statement within the next hour.
CHLOE The media is in a feeding frenzy.
CHLOE The phone lines are jammed.
CHLOE Every network has a pirated shot of Harlon and the dummy.
TRUMAN rolls in the dirt of a construction site, tearing at his clothes and caking his face and hair with black inud.
He struggles up a slope onto an adjacent roadway where a shopping cart awaits, loaded with soiled plastic bags.
Looking every inch a derelict, Truman begins to wheel his shopping cart through the empty streets of Brooklyn.
TRUMAN wheels his shopping cart over a deserted Brooklyn Bridge.
Over his shoulder, in the far distance, we see a lone car approaching.
As it nears, we recognize a police car.
Truman takes a look under the bridge, as if participating in the search.
The car slowly draws alongside, the POLICE OFFICER looking straight into Truman's blackened face.
POLICE OFFICER Any sign of him?
TRUMAN Not yet.
The Police Officer takes a second look at Truman.
After what seems like an eternity, he motions his PARTNER to drive on.
POLICE OFFICER Take it easy.
We pan down one concrete canyon after another.
The usually bustling financial district is totally, eerily deserted.
Suddenly we see a line of PEOPLE fanned out across a street.
Then another and another.
PEOPLE of every description, shoulder to shoulder, marching down the otherwise empty streets the way a search is conducted at a crime scene.
The lines include PRINCIPALS and EXTRAS linked arm in arm, wardrobed for their usual roles as EXECUTIVES and SECRETARIES, STORE CLERKS, TELEPHONISTS, MAINTENANCE and CONSTRUCTION WORKERS, WAITERS and WAITRESSES, COOKS, SHOPPERS,
OFFICERS, FIRE FIGHTERS AND HOMELESS PEOPLE.
On one occasion we glimpse Truman's colleagues, LAWRENCE, ERROL and VIVIEN, amongst the searchers.
A building-to-building, floor-to-floor, office-to-office search is also being conducted, each structure secured as they go, the searchers paying special attention to potential blind spots such as closets, dumpsters, man holes, sewers, car trunks, trees and shrubbery.
We focus on one of the waves of searchers.
TRUMAN has linked arms in the middle of a row, his disguise still holding up.
A swarm of helicopters fills the sky.
While his COLLEAGUES monitor the bank of screens, CHRISTOF has been joined by the two ever-anxious studio executives, MOSES and
MOSES Rumors are circulating he's dead.
ROMAN The sponsors are threatening to rip up their contracts.
CHRISTOF Why?
CHRISTOF We're getting higher ratings for that graphic than any time in the series.
The television behind the bar carries the still graphic.
BAR PATRONS animatedly discuss Truman's fate over their drinks.
Some place bets with each other over the outcome.
A crowd of PASSERS-BY hover around a display of televisions in the window of an electronics store, awaiting developments.
The two OLD WOMEN we have seen before stare intently at the graphic on their televisions.
The fan of EXTRAS reaches the harbor and automatically turns to make another sweep.
CHLOE When we flush him out how do we explain this?
CHRISTOF We tell him the truth.
Chloe looks askance at Christof.
CHRISTOF We're making a movie.
SIMEON We'll get him on this next sweep.
CHRISTOF What have we missed?
SIMEON It's just a matter of time.
CHRISTOF No.
CHRISTOF We've missed something.
Christof turns his back on the screens.
Over his shoulder, we see a monitor displaying a view of the harbor.
TRUMAN has broken away from the line of searchers, on the pretext of taking a leak.
He is standing on the edge of Pier 13, facing the harbor, his back turned to those beginning their next sweep.
Suddenly Truman ducks behind one of the green and white inflatable canopies that enclose the Wall Street Racquet Club.
We see a close up of Truman's terrified eyes in his blackened face, staring down at the lapping water.
It triggers a montage of flashbacks.
As usual the images all appear to play on a television screen.
TRUMAN on the CLIFF FACE at seven years old, his second grade teacher SISTER OLIVIA, a close-up of DROWNING STATISTICS at his insurance company, mesmerized by the water in the FERRY TERMINAL, seventeen-year old SYLVIA jumping in the fountain, his WATERBED rocking, and seven-year old Truman sitting on the UPTURNED BOAT in Long Island Sound crying into the darkness.
TRUMAN comes back to reality.
He steels himself, shuts out the doubts and dives into the water.
Underwater we see TRUMAN panicking at the shock of the cold sea, arms and legs flailing.
Suddenly he stops and sinks for a moment in the weight of his clothes.
Then slowly he rises to the surface and begins to swim.
Moored in the harbor is the scaled-down replica of Columbus' flagship, The Santa Maria.
CHRISTOF is spooling through significant scenes in the history of "TRUMAN" on a preview monitor.
He pauses on the scene of SYLVIA and TRUMAN at the fountain in Flushing Meadow Park in the show's seventeenth season.
Sylvia has her finger to Truman's lips.
Christof presses "PLAY" on the mixing desk.
SYLVIA You remember when you were a little boy...
Christof fast forwards, then presses PLAY once again.
SYLVIA ...Trust that boy...
Christof jabs the "PAUSE" button, freezing the picture.
He recites the words to himself.
CHRISTOF Trust that boy...
CHRISTOF We're not watching the sea.
SIMEON Why would we?
CHRISTOF Sweep the harbor.
TRUMAN is at the wheel of the Santa Maria, wind filling her sails.
Covering the face of the ship's compass is Sylvia's composite picture.
His is the only craft afloat in New York Harbor.
As the archaic vessel passes under the Verrazano-Narrows Bridget, the bridge appears on fire in the glow of the sunlight.
Truman steers around Norton Point and sets a course for the open sea - the horizon.
CHRISTOF and his colleagues concentrate on a live aerial shot on a preview monitor, skimming over the calm, featureless sea.
Suddenly in the distance there appears a single sail etched against the horizon.
SIMEON That's him!
CHRISTOF Resume transmission.
Simeon punches a button and the image of the sailing ship is instantly transferred to the large On-Air monitor.
SYLVIA, dozing on the sofa, suddenly blinks open her eyes as the classical music on the television is abruptly replaced by the sound of a helicopte's rotor blade.
Sylvia focuses on the screen, her breath taken away by the sight of TRUMAN at the wheel of the Santa Maria.
CHRISTOF What do we have on that boat?
Simeon scans a computer shot list.
He types in a code.
A camera from the main mast of Truman's ship activates.
Truman, unaware of the camera, is concentrating on steering the vessel.
TRUMAN is out of sight of land, the sea choppier now, rising and falling beneath his boat.
He nears a large buoy bobbing clumsily in the strong swell.
An official-looking sign is attached - "DANGER.
NAVAL EXERCISES.
DO NOT ENTER."
We see an extreme close up of the nautical signpost where a disguised miniature camera tracks Truman's progress.
CHRISTOF and the other PRODUCTION STAFF watch TRUMAN from the buoy's POV as he sails by.
TRUMAN hears a helicopter overhead.
By now the ocean spray has washed most of the dirt from his face, only a residue remains.
The rags he wears, including Sylvia's sweater under his open coat, are soaked.
Her picture clings stubbornly to the compass.
As he steers, he occasionally refers to a "HOW TO SAIL" book from his coat pocket.
He tacks against the wind, as he watches the military chopper circle his boat.
CHOPPER PILOT Alter course immediately.
CHOPPER PILOT You are entering a restricted area.
Truman screams defiantly back to the chopper.
TRUMAN Fuck you!
Two YOUNG MEN on a street corner watch, transfixed, the image of TRUMAN steering the Santa Maria on a portable Watchman TV.
YOUNG MAN 1 I knew he wasn't dead.
The HELICOPTER PILOT continues to circle.
PILOT (over P.A.) Alter course or we fire on your vessel.
TRUMAN screams again at the chopper and gestures wildly at the pilot.
TRUMAN Get the hell away!
TRUMAN It's my life!
CHRISTOF Fire a warning.
A round of machine gun fire strafes the water across the bows of Truman's boat, several rounds striking the deck.
TRUMAN flinches.
In his eyes we see the ghosts return.
With great effort he shakes the doubts from his head and retrieves a flare gun from the storage cabinet in the boat's wheel house.
CHOPPER PILOT (over P.A.) Alter course.
CHOPPER PILOT (over P.A.) Drop your sails.
Truman takes aim at the chopper and fires the flare gun.
The distress flare hurtles towards the hovering helicopter, narrowly missing.
Truman ejects the spent cartridge and reloads.
SIMEON Jesus!
SIMEON God!
SIMEON Is he out of his mind?
CHRISTOF Pull back.
Before the chopper can take evasive action TRUMAN takes aim a second time and fires.
The distress flare fishtails into the sky and to Truman's surprise and delight, finds its mark, striking the rear rotor blade.
Truman lets out a whoop.
The helicopter immediately begins to spiral downwards towards the sea.
The CHOPPER PILOTS bail out of the cockpit, splashing down safely into the coean while the helicopter enters the waves in a spectacular belly flop, sinking out of view in seconds like a stone.
Watching the pilots bobbing around in the ocean in their inflatable life jackets, thoughts of duty invade Truman's head.
He shuts out the thoughts and turns his back, steering away from the drifting pilots.
A look of resolve in his eyes we have never witnessed before.
SYLVIA kneels on the floor in front of the television.
As Christof's cameras dwell on her likeness - the composite picture still covering the ship's compass - she allows herself a brief moment of satisfaction but she does not dare to hope too much.
CHRISTOF, CHLOE, SIMEON, and the OTHERS have been joined in the control room by MARLON, MERYL, KIRK and AUDREY.
CHRISTOF How long will another chopper take?
SIMEON By the time we pick up the pilots, too long.
CHRISTOF We have to stop him for his own good.
CHRISTOF Turn him back with the elements.
SIMEON There's no rescue boat in the area.
SIMEON He won't know what to do.
MOSES For God's sake, Chris.
MOSES The whole world is watching.
MOSES We can't kill him in front of a live audience.
CHRISTOF He was born in front of a live audience.
CHRISTOF Don't worry, he's not willing to risk his life for the truth.
CHRISTOF His doubts will turn him back.
Simeon reluctantly turns to a panel of controls on the desk marked "WAVE", "WIND" and "RAIN".
After typing in a command, he winds the controls towards their maximum settings.
CHRISTOF Kill the lights.
Chloe searches Christof's face, trying to find the man in whom she has believed for so long.
Darkness suddenly descends as storm clouds roll towards Truman's boat at an alarming speed.
High winds buffet the boat.
TRUMAN fights the wheel.
Hurricane force winds shake the masts and keel, ripping the sails to shreds.
The picture of Sylvia is torn from the compass and lost to the sea.
His "HOW TO SAIL" book skids off the deck.
Truman takes a rope from beneath the wheel house and lashes himself to the wheel to secure himself on board.
TRUMAN I'm coming to find you Sylvia!
TRUMAN I'm making myself deaf!
TRUMAN You're going to have to kill me!
TRUMAN Come on!
Monstrous waves continually submerge the deck.
Truman continues to head into the teeth of the gale.
In contrast to his panic-stricken COLLEAGUES, CHRISTOF gives an outward appearance of calm.
However a bead of sweat appearing at his temple betrays him.
SIMEON It's not working.
SIMEON He can sail that thing!
ROMAN How can he sail?!
ROMAN He's in insurance!
ROMAN He hasn't set foot on a boat since he was seven!
MOSES On the behalf of the studio, I demand you cease transmission.
CHRISTOF Keep running!
CHRISTOF I take full responsibility.
CHRISTOF How close?
OPERATOR Very close.
CHRISTOF Capsize him!
CHRISTOF Tip him over!
CHLOE You can't!
CHLOE He's tied himself to the wheel.
CHLOE He'll drown!
SIMEON He doesn't care...
CHLOE You lied, you hypocrite!
CHLOE The only way he can leave, is dead!
Chloe lunges for the control panel but Christof throws her to the floor.
CHRISTOF Do it!
All eyes turn in Christof's direction, as he confirms Chloe's accusation.
SIMEON It's too late...
TRUMAN appears to be losing his fight against the storm, each successive breaker taking its toll on his body, sapping his strength, his bindings the only thing holding him upright, his head slumps, the wheel goes loose in his grasp, spinning out of control.
His will, draining away.
As he is about to be overcome by the next wave, he thrusts his arm into the handles of the spinning wheel.
He cries out in pain at the blow to his forearm but succeeds in halting the wheel.
He braces for one last wave.
But the wave does not come.
A strange phenomenon is occurring in the ocean.
A distinct division has appeared in the ocean swell.
Between the large rolling waves lies a corridor of calmer water, several hundred yards wide, a curious escape lane.
The wind and the rain are also subsiding, the darkness lifting.
Truman steers his vessel down this "sea-lane".
After some time, several large, dark shapes emerge on the horizon.
Land?
Islands?
As Truman steers towards the nearest shape, he discovers what is behind the peculiar wave formations.
It is certainly not the moon.
The dark shape is a huge iron roller, only half of which is exposed above the surface of the sea.
The ocean swell is being caused by the roller slowly turning, mechanically-driven on either end by massive steel arms pumping from the sea bed.
In fact there are rollers spaced four hundred yards apart in both directions along the horizon as far as the eye can see, the calm sea-lanes formed by the gaps between the rollers.
Truman's boat is dwarfed by the gigantic machines.
The exposed half of each roller, the height of a ten story building, its length equivalent to several football fields.
The massive arms perpetually churn.
Truman's face is thrown into shadow as the boat slips quietly past the giant rotating drum.
The water beyond the rollers is dead calm.
Truman stares ahead desperately trying to focus his eyes.
But if the sight of the wave machines was difficult to comprehend, it pales in comparison with the next sight that greets him.
His boat is drifting inexorably, on a slow collision course with the sky.
That infinitely receding horizon line recedes no more.
The sea really does meet the sky.
The join is only too apparent.
Looming above him out of the sea is a cyclorama of colossal dimensions.
The sky is nothing but a painted backdrop.
Truman looks upward, straining his eyes to see the top of the sky, but it curves away at a steep angle beyond his sight.
The bow of the boat comes to rest against the sky, bumping gently into its latex surface.
Truman unties his bindings and stumbles across the deck to the side rail.
Clinging to the rail with one hand, he tentatively reaches out towards the painted cyclorama.
He touches the sky.
He feels the surface, puts both terrified hands against it.
Hie eyes well up with tears.
He presses his distraught face into it.
He screams at the top of his voice.
No words.
A primal scream.
A pained, animal howl.
CHRISTOF and his PRODUCTION STAFF take in Truman's reaction in silence.
TRUMAN's cry echos around bars, offices, shops, homes and streets - wherever a television is to be found.
No VIEWER speaks.
They are stunned to silence, many teary eyed.
As the boat drifts alongside the seemingly never-ending curve of the cyclorama, TRUMAN's attention is drawn to an outline in the otherwise flawless backdrop.
He clambers to the prow of the boat.
There, camoflaged in the painted skyscape just above the water line, is a door.
Truman grabs hold of the recessed doorhandle and halts the drifting boat.
He stands in front of the door and closes his eyes in a silent prayer.
He opens the door in the sky and steps through.
Spontaneous cheers and shouts of joy erupt from VIEWERS in their various locations - bars, homes and offices.
Strangers hug each other and dance in celebration.
Even the cynical VIDEO OPERATOR jumps out of his seat - for the first time in the film - and lets out a joyous whoop, forgetting himself for a moment, caught up in the drama.
OPERATOR Yeah!
Self-conscious, he takes his seat again almost immediately.
His COLLEAGUES are transfixed by the live on-air monitor continuing to play its only available shot, the open door in the sky - Truman out of view.
TRUMAN finds himself on a small metal landing.
A steel ladder rises above him to the height of "sky", the soundstage roof, so high as to be barely visible.
The rungs also continue downward, the depth of the "ocean-bed", to a studio floor far below.
Truman turns and looks back through the door he has just entered.
Unsecured, the Santa Maria is beginning to drift away.
The sea he has feared since childhood, is nothing but an enormous tank.
The sky, a massive cyclorama.
New York City, an elaborate set.
And it is all housed within an impossibly large soundstage.
Truman makes no effort to save the boat.
He shuts the door to his world.
A sign on the back of the door reads, "CLOSED SET.
No Unauthorized Access."
Gradually he becomes aware of another strange phenomenon taking place in the soundstage.
All around him, thousands of light fixtures mounted in the cyclorama to masquerade as stars, are slowly illuminating - switched on by an automatic timer.
(The light fixtures match the one that almost struck Truman's car at the beginning of the film.)
By artificial starlight, Truman begins his long descent of the step ladder.
Below, a studio tram makes its way along the soundstage perimeter, on the last tour of the day.
As he drives, a well-scrubbed, young TOUR GUIDE delivers his tired commentary into a microphone for the thousandth time to the half-full tram of STUDIO VISITORS.
GUIDE ...the soundstage roof houses over eight hundred thousand lights of varying intensities to faithfully recreate the constellations...
However, the passengers are paying less attention than usual.
They stare, perplexed, at the television monitor above the Guide's head, continuing to play the show's only available shot of the open door in the sky.
TRUMAN suddenly steps in front of the tram.
The TOUR GUIDE stands on the brakes, tram lurching to a stop.
The Guide looks from Truman's haunted face to the monitor, hardly able to believe his eyes.
Truman leaps on board, pressing his flare gun into the side of the guide's head.
TRUMAN Nobody move!
TRUMAN Drive!
The terrified Guide pulls jerkily away in the tram, resuming the tour.
TRUMAN Keep talking.
TRUMAN Say whatever you say!
The Guide hesitantly resumes his commentary into his microphone.
GUIDE Er,...the ocean tank contains over six hundred and fifty million gallons of man-made salt water, temperature-controlled...
Truman's attention drifts to the logo on the side of the tram - "TRUMAN STUDIO TOUR".
He is suddenly aware of the tourists gawking at him.
TRUMAN Act normal!
TRUMAN Keep filming!
Truman ducks out of sight as a fleet of STUDIO SECURITY CARS speeds towards the tram.
But they streak past, on their way to the site of Truman's escape.
As he tentatively gets back to his feet, Truman finds a CHILD standing in front of him with an autograph book.
CHILD Please, Mister Truman.
On the child's T-shirt, a large photograph of Truman's face.
CHRISTOF talks anxiously on the phone, unaware of a shift in the balance of power taking place behind his back.
The executives, MOSES and ROMAN are huddling with SIMEON, making him an offer he appears to welcome.
CHRISTOF What do you mean he's not there?
CHRISTOF We can't have lost him again.
On the far side of the control room, behind a huge curved glass wall on a mezzanine floor, a studio tour tram passes by.
TRUMAN crouches behind a seat on the tram, flare gun still trained on the guide's head, taking in the gigantic video wall displaying pictures from every facet of his life.
His heart sinks as he spies the monitor revealing the private spot where he and SYLVIA met.
GUIDE ...on your left, the control room where the angles are selected and the actors receive direction.
GUIDE Of course, the one place we can't show you is the story department.
GUIDE There is none.
GUIDE ...Truman writes the script...
From Truman's POV we watch CHLOE approach CHRISTOF.
She has a pure white envelope in her hands.
As Christof looks up to acknowledge her, he almost makes eye contact with Truman on the tram.
Still inside the studio complex, the tram enters the courtyard of an indoor shopping mall.
Truman gift shops.
TRUMAN is momentarily frozen by the sight of window displays full of books and board games carrying his likeness with titles such as, "TrumanTrivia".
Video cassettes offering "Truman Highlights".
His face emblazoned on T-shirts, caps, coffee mugs and posters.
Even Truman Dolls and a model of his decaying Oldsmobile are offered for sale.
The tram slows to a stop behind other trams at the tour's end.
STUDIO POLICE are checking the disembarking PASSENGERS.
Truman, using the TOUR GUIDE as a shield, also exits the tram.
GUIDE Here he is!
GUIDE It's him!
Truman contemptuously backhands the Guide across the face and makes a run for it.
The guards give chase.
Truman runs into a lookalike mannequin, dressed in a brown suit identical to his own, promoting "TrumanWear".
He pulls his "double" to the ground to block the guards' path.
Sprinting along a featureless corridor, he reaches a dead end.
GUARD We've got him trapped.
Truman enters a doorway marked "NO ENTRY" to find a stairway leading upwards.
He takes the stairs three at a time.
The footsteps and shouts of the guards not far behind.
Flight after flight of stairs.
At one point, he loses his grip on the stair's railing and his gun falls from his hand, clattering for an eternity down the stairwell.
He finally emerges on a landing.
Lungs bursting.
One more door.
He tries the handle.
It opens.
TRUMAN finds himself on the roof of the soundstage.
Outside.
Really outside for the first time in his life.
He looks frantically around him.
Nowhere to hide.
The soundstage stretches for miles in both directions as far as the eye can see, an interminable expanse of roof.
Facing him, a colossal Burbank.
Several other soundstages almost as gigantic as his own.
The palm trees lining the streets, dwarfed by the mammoth barns.
The Hollywood Freeway in the distance, carrying its ribbons of traffic, twenty lanes wide.
Gargantuan office buildings eclipse any skyscraper Truman has ever known.
Directly below him, a dizzying drop to the studio lot and its arched entranceway.
Above him, a large yellow moon in the twilight sky.
The real moon, not the planetarium projection he has been contemplating for the last thirty-four years.
Truman wheels around, suddenly realizing he is not alone.
A GROUP has emerged on the rooftop, standing still and silent in a semi-circle, cutting off any escape.
Along with the STUDIO GUARDS, keeping their distance in the background, are CHLOE, SIMEON, and the two studio executives, MOSES and ROMAN.
In front of them, the co-stars in his life - MARLON, MERYL, sister RAQUEL, mother AUDREY and supposedly dead father KIRK.
No one moves or speaks as Truman scans the familiar faces.
Marlon, in particular, cannot look him in the eye.
Truman's gaze finally falls on the white-haired old man standing at the head of the group.
CHRISTOF.
He approaches Truman alone, carrying a white envelope, calling his name the way a father calls to a son.
CHRISTOF Truman...
Truman seems to sense the significance Christof has had in his life, drawn to and repelled by him at the same time.
As they stand together looking into each other's eyes for the first time, they seem to be the only two figures on the roof.
For a moment Truman averts his gaze to the night sky.
TRUMAN Even the stars I wished on...
As Truman turns his attention back to Christof, he suddenly lunges at him, catching him off-guard, the envelope slipping from Christof's hand.
With a strength he never knew he possessed, Truman forces Christof to the edge of the soundstage roof, threatening to throw them both off his counterfeit world.
Christof clings desperately to Truman to save himself.
The studio guards dare not move.
CHRISTOF You won't do it, Truman.
CHRISTOF I've watched you your whole life.
TRUMAN You never had a camera in my head.
Suddenly the doubts flood into Christof's eyes, fearing he has misjudged Truman, fearing for his life.
TRUMAN Something was real!
TRUMAN Something had to be real!
It takes all of Truman's will not to hurl the old man into the abyss.
Christof, petrified, looks to the pristine, white envelope that lies half over the edge of the roof, glinting in the moonlight.
Truman follows Christof's gaze.
Contemptuously tossing Christof aside, he retrieves the envelope.
Christof crawls to safety, thankful to still be alive, suddenly appearing very small and insignificant.
But Christof and the other figures on the rooftop no longer exist in Truman's mind.
Truman gazes at his name for a long moment, handwritten on the envelope in blue ink, then carefully breaks the seal.
Truman allows the sole item in the envelope to be slowly revealed.
A photograph.
A close up of SYLVIA's face including her eyes, mouth and that perfect, ever-elusive nose.
A serenity comes over Truman.
He lifts up his eyes to the mountains on the far horizon.
As he stands on the very edge of the soundstage roof without fear, clutching the photograph, we commence a long, slow pull-back.
Truman is unaware that directly beneath his feet on the wall of the enormous soundstage is a billboard acrrying a gigantic picture of his face and proclaiming, "TRUMAN - Total Record of a Human Life.
34TH GREAT YEAR!"
We continue to pull back until Truman is nothing but a speck on top of the soundstage so large it never completely clears frame.
The two OLD WOMEN in the living room, the NIGHTWATCHMEN, the two YOUNG MEN with the Watchman TV, the PATRONS in the bar, PASSERS-BY outside an electronics store are all captivated by their television sets.
We focus on the screen of a television.
A small FEMALE BABY sucks a toy on a blanket in the backyard of Truman's old suburban home in Queens, the lawn he mowed for ten years of his life.
The infant's doting parents, MARLON and the new actress VIVIEN, enter frame and begin to fuss over the child.
A border around the action on the screen announces, "ZOE - Total Record Of a Human Life".
Suddenly we see a child's hand on top of the television screen.
A BABY stands unsteadily, supporting herself against the television set in Sylvia's house.
TRUMAN bends down and picks up his baby, tossing her into the air, much to the child's delight.
Truman dwells for a moment on the mirror-image scene on the television before very deliberately shutting it off.
SYLVIA joins Truman and their daughter.
Together, they exit the beach house.
We follow them as they make their way onto the deserted sand and down towards the sea.
</pre>
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
