A majestic panorama of the lush green slopes that are the Columbian highlands.
A faint chopping sound IS HEARD and then another.
WHOOSH.
WHOOSH.
The view changes and tiny dots appear on the hillside vegetation.
WHOOSH.
We realize the dots are people.
Workers swinging long steel machetes in slow methodical rhythm.
WHOOSH.
WHOOSH.
WE SEE the South American Indian MEN clearly now.
Their tar stained teeth.
Their gaunt faces riddled with crow's feet.
Their jaws chewing away on huge wads of coca leaves as they collect the harvest.
Old rickety trucks carrying the huge green tractor-sized bales speed along the narrow road.
The bundles are undone and Columbian women separate out the leaves.
Tribes of underweight workers carry armload after armload of the harvest and ritualistically dump them into a gigantic cannibal pot which sits on top of a raging bonfire.
The leaves are being boiled down and a huge plume of smoke streaks the sky.
Wizened Indios brave the heat and shovel ashes into the pot to cool the solution.
A primitive but enormous makeshift lab contains all the equipment.
The machinery.
The solutions.
The over-sized vats.
Dark-skinned bandoleros smoke cigarettes and sport automatic weapons at all the points of entry.
The coca is now a "basuco" paste and is being sent in for a wash.
A conveyor belt pours out brick after brick of pure cocaine hydrochloride.
The bricks are wrapped, tied up, weighed, and stamped with a "P" before being thrown into duffel bags.
A small twin-engine Cessna is loaded with dozens of duffel bags and the plane takes off.
The Cessna touches down.
The worksite is busy.
George is amongst other workers, working a summer job.
As George is taking five, he looks across the sight to Fred, who is sweeping up debris.
A long way from being the boss.
George stands in line to register for college, wearing his Brooks Brothers suit, bowtie, and freshly Bryllcreamed hair.
The room is crowded and the line is long.
Bob Dylan's "Subterranean Homesick Blues" blares out of one of the kid's transistor radios.
George looks around the room.
He is uncomfortable.
He catches his reflection in the shiny glass partition and stops.
He doesn't like what he sees.
Something is not right.
He looks like everyone else.
Same cookie-cutter hair, same cookie-cutter clothes, same cookie cutter faces.
He's a carbon copy.
REGISTRATION WOMAN Next.
It's George's turn but he doesn't hear it.
"Twenty years of schooling and they put you on a day shift."
The words hit him like a tone of bricks as he continues to stare at his own reflection.
GEORGE (V.O.) I was standing there, and it was like the outside of me and the inside of me didn't match, you know?
GEORGE (V.O.) And then I looked around the room and it hit me.
GEORGE (V.O.) I saw my whole life.
GEORGE (V.O.) Where I was gonna live, what type of car I'd drive, who my neighbors would be.
GEORGE (V.O.) I saw it all and I didn't want it.
GEORGE (V.O.) Not that life.
George sits with Fred.
It's breaktime and Fred eats from a lunch box.
GEORGE There's something out there for me, Dad.
GEORGE Something different.
GEORGE Something free form, you know?
GEORGE Something for me, and college just isn't it.
FRED That's too bad.
FRED You would have been the first one in the family.
GEORGE I know.
FRED Alright.
FRED You want me to get your old job back?
FRED Because I could, you know, I could put in that word.
GEORGE No, Dad.
GEORGE I don't want to...I mean, I just don't want...
It's obvious to Fred that his son doesn't want to be like him.
FRED What are you going to do?
GEORGE I'm going to California.
George and Tuna, now 21-years old, struggle with their bags.
Their new place is a tackily furnished, two-story apartment with small balconies and a view of the ocean.
As George and Tuna struggle with the bags, two California beauties appear on the balcony next door: BARBARA BUCKLEY, 20, and MARIA
GIRLS You guys need some help?
George and Tuna share a look.
TUNA I don't know about you, but I think we're gonna like it here.
Barbara and Maria introduce George and Tuna around to the Manhattan Beach regulars.
They are immediately accepted despite their ill fitting shorts and Tuna's unhip black socks.
The beach scene is one big party.
Lots of beer, music, bikinis, and good times.
By the end of the day, George and Tuna have a hundred new friends.
GEORGE (V.O.) California was like nothing I'd ever experienced.
GEORGE (V.O.) The people were liberated and independent and full of new ideas.
GEORGE (V.O.) (CONT'D) They used words like "right on," "groovy," and "solid."
GEORGE (V.O.) (CONT'D) The women are all beautiful and seemed to share the same occupation.
WOMAN #1 I'm a flight attendant.
WOMAN #2 I'm a flight attendant.
WOMAN #3 I'm a flight attendant.
The weed comes out and is passed around.
Pipes.
Joints.
Bongs.
In SLOW MOTION, Barbara takes a huge hit of grass, grabs George's face, french kissing him, and giving him a huge shotgun.
George and Barbara are sleeping late.
Their bodies intertwined beneath the sheets.
A slam of the front door wakes them up.
It's Tuna.
TUNA Hey, wake up.
TUNA Come on, you two lovebirds.
TUNA Hurry, I want to show you something.
George and Barbara shake cobwebs out and stumble into the kitchen to find Tuna holding a brown paper shopping bag.
TUNA (CONT'D) Figured it out.
GEORGE Figured what out?
TUNA You know how we were wondering what we were going to do for money?
TUNA Being how we don't want to get jobs and whatnot?
TUNA Well, check this out.
Tuna takes the paper bag and empties its contents on the kitchen table.
It's a grey mound of stocky, seedy marijuana.
Barbara examines the reefer.
BARBARA Tuna, this is crap.
TUNA I know it's not the greatest.
TUNA It's commercial.
BARBARA It's garbage.
GEORGE It's oregano.
GEORGE You got ripped off, pal.
GEORGE What are you gonna do with all this?
TUNA We sell it.
TUNA I got it all figured out.
TUNA We make three finger lids and sell them on the beach.
TUNA We move all of it.
TUNA We've made ourselves a hundred bucks.
TUNA Or a lot of weed for our head.
TUNA What do you think?
TUNA Not bad, huh?
TUNA I got the baggies and everything.
BARBARA You can't sell this to your friends.
TUNA Man.
TUNA Fuck you guys.
TUNA I have this great idea and you guys have to be all skeptical.
BARBARA Look, if you really wanna score some dope, I got the guy.
George, Barbara and Tuna stop outside the front door.
GEORGE Are you sure this guy is cool?
BARBARA You'll see for yourself.
TUNA A beauty parlor for men?
TUNA Sounds pretty queer.
They walk in.
George, Tuna and Barbara enter.
The Whipping Post is California's first male hair salon.
George looks around at the customer's being pampered.
Haircuts, pedicures, manicures.
GEORGE Nothing like this back home.
BARBARA Derek!
DEREK FOREAL is a curious man.
Daringly effeminate, especially for the sixties, he is always surrounded by beautiful women.
As he sees Barbara, he stops his haircut and runs to embrace her.
DEREK Barbie!
Derek's female entourage rush over as well.
Kisses all around.
DEREK (CONT'D) So, this is the new man, huh?
DEREK (CONT'D) He's cute!
George and Tuna stick out there hands.
GEORGE George.
TUNA Tuna.
DEREK Tuna, oh my.
DEREK Enchante, George.
DEREK Barbie, he's yummy.
DEREK He looks like a Ken doll.
DEREK Oooh, Ken and Barbie.
DEREK It's perfect.
DEREK Alright, girls, give me five minutes.
Derek makes dismissing gestures and the girls scatter.
DEREK (CONT'D) Everyone, shoo!
DEREK (CONT'D) You, too, Barbie.
DEREK (CONT'D) I want to talk to the boys alone.
After the girls leave, Derek closes the partition and his playful demeanor changes.
He's all business now.
DEREK (CONT'D) What can I do for you guys?
GEORGE We want some grass.
DEREK I know what you want.
DEREK But, first of all, are you cops?
GEORGE No.
DEREK Because if you are, you have to tell me.
DEREK If not, it's entrapment.
GEORGE We're not cops.
GEORGE We're from Massachusettes.
GEORGE I mean, does he look like a cop?
DEREK I guess not.
DEREK Okay.
DEREK You know, you're very lucky you're friends of Barbie's.
DEREK If you weren't, I'd never talk to you.
Derek pulls a television-sized brick of quality marijuana out from under a sink and sets it down in front of George.
GEORGE What the fuck is that?
DEREK It's your grass.
TUNA Wow.
TUNA That's more than we had in mind.
DEREK I don't nickel and dime.
DEREK You want it or not?
George and Tuna look at each other.
GEORGE We'll take it.
Summer on the beach.
It's one big party.
George and Tuna are on the beach.
They are the new kings.
They smoke pot and drink brews.
George and Barbara get close as do Tuna and Maria.
Slowly, George's clothes and hair start to look better, cooler.
George and Tuna hanging out with the SURFERS.
George and Tuna hang with Barbara, Maria and SOME GIRLFRIENDS in bikinis.
George and Barbara hang together at the life guard stand.
George and Tuna on the strand with HIPPY PROFESSORS selling half-ounces.
Derek, Tuna, George, Barbara, Maria and the Elves play volleyball.
Barbecue at Belmont Shores apartment with George, Barbara, Derek, Tuna, Maria and different Elves.
George and Tuna sell half-ounces to BIKERS.
Derek is having a party out of a mini-van in the beach parking lot.
George, Barbara, Tuna and Maria are there.
George and Barbara sit by the water, watching the waves crash into the sand.
The sky is streaked with purple and red.
GEORGE This is it for me.
BARBARA What is?
GEORGE Just everything.
GEORGE You.
GEORGE California.
GEORGE The beach.
GEORGE This spot right here.
GEORGE I feel like I belong here, you know?
GEORGE It just feels right.
BARBARA You happy, baby?
GEORGE Yeah.
GEORGE I am.
The worksite is busy.
George is amongst other workers, working a summer job.
As George is taking five, he looks across the sight to Fred, who is sweeping up debris.
A long way from being the boss.
George stands in line to register for college, wearing his Brooks Brothers suit, bowtie, and freshly Bryllcreamed hair.
The room is crowded and the line is long.
Bob Dylan's "Subterranean Homesick Blues" blares out of one of the kid's transistor radios.
George looks around the room.
He is uncomfortable.
He catches his reflection in the shiny glass partition and stops.
He doesn't like what he sees.
Something is not right.
He looks like everyone else.
Same cookie-cutter hair, same cookie-cutter clothes, same cookie cutter faces.
He's a carbon copy.
REGISTRATION WOMAN Next.
It's George's turn but he doesn't hear it.
"Twenty years of schooling and they put you on a day shift."
The words hit him like a tone of bricks as he continues to stare at his own reflection.
GEORGE (V.O.) I was standing there, and it was like the outside of me and the inside of me didn't match, you know?
GEORGE (V.O.) And then I looked around the room and it hit me.
GEORGE (V.O.) I saw my whole life.
GEORGE (V.O.) Where I was gonna live, what type of car I'd drive, who my neighbors would be.
GEORGE (V.O.) I saw it all and I didn't want it.
GEORGE (V.O.) Not that life.
George sits with Fred.
It's breaktime and Fred eats from a lunch box.
GEORGE There's something out there for me, Dad.
GEORGE Something different.
GEORGE Something free form, you know?
GEORGE Something for me, and college just isn't it.
FRED That's too bad.
FRED You would have been the first one in the family.
GEORGE I know.
FRED Alright.
FRED You want me to get your old job back?
FRED Because I could, you know, I could put in that word.
GEORGE No, Dad.
GEORGE I don't want to...I mean, I just don't want...
It's obvious to Fred that his son doesn't want to be like him.
FRED What are you going to do?
GEORGE I'm going to California.
George and Tuna, now 21-years old, struggle with their bags.
Their new place is a tackily furnished, two-story apartment with small balconies and a view of the ocean.
As George and Tuna struggle with the bags, two California beauties appear on the balcony next door: BARBARA BUCKLEY, 20, and MARIA
GIRLS You guys need some help?
George and Tuna share a look.
TUNA I don't know about you, but I think we're gonna like it here.
Barbara and Maria introduce George and Tuna around to the Manhattan Beach regulars.
They are immediately accepted despite their ill fitting shorts and Tuna's unhip black socks.
The beach scene is one big party.
Lots of beer, music, bikinis, and good times.
By the end of the day, George and Tuna have a hundred new friends.
GEORGE (V.O.) California was like nothing I'd ever experienced.
GEORGE (V.O.) The people were liberated and independent and full of new ideas.
GEORGE (V.O.) (CONT'D) They used words like "right on," "groovy," and "solid."
GEORGE (V.O.) (CONT'D) The women are all beautiful and seemed to share the same occupation.
WOMAN #1 I'm a flight attendant.
WOMAN #2 I'm a flight attendant.
WOMAN #3 I'm a flight attendant.
The weed comes out and is passed around.
Pipes.
Joints.
Bongs.
In SLOW MOTION, Barbara takes a huge hit of grass, grabs George's face, french kissing him, and giving him a huge shotgun.
George and Barbara are sleeping late.
Their bodies intertwined beneath the sheets.
A slam of the front door wakes them up.
It's Tuna.
TUNA Hey, wake up.
TUNA Come on, you two lovebirds.
TUNA Hurry, I want to show you something.
George and Barbara shake cobwebs out and stumble into the kitchen to find Tuna holding a brown paper shopping bag.
TUNA (CONT'D) Figured it out.
GEORGE Figured what out?
TUNA You know how we were wondering what we were going to do for money?
TUNA Being how we don't want to get jobs and whatnot?
TUNA Well, check this out.
Tuna takes the paper bag and empties its contents on the kitchen table.
It's a grey mound of stocky, seedy marijuana.
Barbara examines the reefer.
BARBARA Tuna, this is crap.
TUNA I know it's not the greatest.
TUNA It's commercial.
BARBARA It's garbage.
GEORGE It's oregano.
GEORGE You got ripped off, pal.
GEORGE What are you gonna do with all this?
TUNA We sell it.
TUNA I got it all figured out.
TUNA We make three finger lids and sell them on the beach.
TUNA We move all of it.
TUNA We've made ourselves a hundred bucks.
TUNA Or a lot of weed for our head.
TUNA What do you think?
TUNA Not bad, huh?
TUNA I got the baggies and everything.
BARBARA You can't sell this to your friends.
TUNA Man.
TUNA Fuck you guys.
TUNA I have this great idea and you guys have to be all skeptical.
BARBARA Look, if you really wanna score some dope, I got the guy.
George, Barbara and Tuna stop outside the front door.
GEORGE Are you sure this guy is cool?
BARBARA You'll see for yourself.
TUNA A beauty parlor for men?
TUNA Sounds pretty queer.
They walk in.
George, Tuna and Barbara enter.
The Whipping Post is California's first male hair salon.
George looks around at the customer's being pampered.
Haircuts, pedicures, manicures.
GEORGE Nothing like this back home.
BARBARA Derek!
DEREK FOREAL is a curious man.
Daringly effeminate, especially for the sixties, he is always surrounded by beautiful women.
As he sees Barbara, he stops his haircut and runs to embrace her.
DEREK Barbie!
Derek's female entourage rush over as well.
Kisses all around.
DEREK (CONT'D) So, this is the new man, huh?
DEREK (CONT'D) He's cute!
George and Tuna stick out there hands.
GEORGE George.
TUNA Tuna.
DEREK Tuna, oh my.
DEREK Enchante, George.
DEREK Barbie, he's yummy.
DEREK He looks like a Ken doll.
DEREK Oooh, Ken and Barbie.
DEREK It's perfect.
DEREK Alright, girls, give me five minutes.
Derek makes dismissing gestures and the girls scatter.
DEREK (CONT'D) Everyone, shoo!
DEREK (CONT'D) You, too, Barbie.
DEREK (CONT'D) I want to talk to the boys alone.
After the girls leave, Derek closes the partition and his playful demeanor changes.
He's all business now.
DEREK (CONT'D) What can I do for you guys?
GEORGE We want some grass.
DEREK I know what you want.
DEREK But, first of all, are you cops?
GEORGE No.
DEREK Because if you are, you have to tell me.
DEREK If not, it's entrapment.
GEORGE We're not cops.
GEORGE We're from Massachusettes.
GEORGE I mean, does he look like a cop?
DEREK I guess not.
DEREK Okay.
DEREK You know, you're very lucky you're friends of Barbie's.
DEREK If you weren't, I'd never talk to you.
Derek pulls a television-sized brick of quality marijuana out from under a sink and sets it down in front of George.
GEORGE What the fuck is that?
DEREK It's your grass.
TUNA Wow.
TUNA That's more than we had in mind.
DEREK I don't nickel and dime.
DEREK You want it or not?
George and Tuna look at each other.
GEORGE We'll take it.
Summer on the beach.
It's one big party.
George and Tuna are on the beach.
They are the new kings.
They smoke pot and drink brews.
George and Barbara get close as do Tuna and Maria.
Slowly, George's clothes and hair start to look better, cooler.
George and Tuna hanging out with the SURFERS.
George and Tuna hang with Barbara, Maria and SOME GIRLFRIENDS in bikinis.
George and Barbara hang together at the life guard stand.
George and Tuna on the strand with HIPPY PROFESSORS selling half-ounces.
Derek, Tuna, George, Barbara, Maria and the Elves play volleyball.
Barbecue at Belmont Shores apartment with George, Barbara, Derek, Tuna, Maria and different Elves.
George and Tuna sell half-ounces to BIKERS.
Derek is having a party out of a mini-van in the beach parking lot.
George, Barbara, Tuna and Maria are there.
George and Barbara sit by the water, watching the waves crash into the sand.
The sky is streaked with purple and red.
GEORGE This is it for me.
BARBARA What is?
GEORGE Just everything.
GEORGE You.
GEORGE California.
GEORGE The beach.
GEORGE This spot right here.
GEORGE I feel like I belong here, you know?
GEORGE It just feels right.
BARBARA You happy, baby?
GEORGE Yeah.
GEORGE I am.
George walks in to find Tuna and Maria sitting with KEVIN DULLI, an old friend from back east.
He's sitting in front of a water pipe and coughing his ass off.
TUNA Look what the cat dragged in.
GEORGE Holy shit, Dulli.
GEORGE What the hell are you doing here?
KEVIN Well, I'll tell you.
KEVIN I was walking down the beach, minding my business, when who did I see but this fucking guy.
KEVIN I didn't know you guys were living in California.
GEORGE Yeah, but what are you doing out here?
KEVIN I'm on vacation.
KEVIN On my way back to school.
GEORGE This calls for a joint.
GEORGE You want to do the honors?
KEVIN No, man.
KEVIN I'm too fucked up.
TUNA Nice weed, huh?
KEVIN Fuck yeah.
KEVIN I never seen nothing like it.
KEVIN I'm fucking wasted.
GEORGE Right on.
KEVIN G-d, I'm stoned.
KEVIN I'm stoned.
KEVIN I'm really...
GEORGE Stoned?
KEVIN I wish there was shit like this back home.
GEORGE Yeah?
KEVIN Shit, yeah.
KEVIN Do you know how much money I could make if I had this stuff back east?
TUNA No shit, Kevin?
KEVIN That's right.
GEORGE Yeah?
KEVIN When there's something to move, it's too easy not to.
KEVIN Do you know how many colleges are in a twenty mile radius?
KEVIN U.
KEVIN Mass, Amherst, B.U....
TUNA Smith.
TUNA Hampshire....
KEVIN Right.
KEVIN And Holyoke.
KEVIN There are a hundred thousand rich kids with their parents' money to spend, but there's never anything available.
KEVIN Nothing good, anyway.
KEVIN I'm paying four hundred dollars for shit.
Derek, George and Barbara sit around.
The blinds are drawn.
GEORGE The way we figure it, Barbara flies to Boston twice a week.
GEORGE Two bags per flight.
GEORGE Twenty-five pounds in each bag.
DEREK You're kidding, right?
DEREK That's a hundred pounds a week.
GEORGE Yeah, I know, it's a lot of weight.
BARBARA We're gonna call it California sinsemilla.
BARBARA Sounds exotic.
GEORGE I'm telling you, Derek, it will sell.
DEREK I don't know...
GEORGE Here's the best part.
GEORGE We can charge five-hundred a pound.
DEREK Come on, George, no one is going to pay that.
GEORGE It's already been negotiated.
GEORGE It's done.
GEORGE The money is there waiting.
Derek looks at Barbara.
She nods.
DEREK Goodness.
GEORGE Goodness is right.
GEORGE If you do the math, that's over thirty grand a week profit.
GEORGE I want you to be my partner on this, Derek.
GEORGE Fifty-fifty.
GEORGE That's fifteen thousand a week for you, my friend.
GEORGE In your pocket, free and clear.
DEREK And I only deal with you?
GEORGE Barbara and me.
GEORGE No one else.
Derek thinks about it.
BARBARA It's gonna work, Derek.
DEREK I don't know.
DEREK East coast.
DEREK Airplanes.
DEREK It all sounds pretty risky.
GEORGE She's a flight attendant.
GEORGE They don't check her bags.
George drops Barbara off in her uniform curbside.
They kiss and she walks away with two big, red Samsonites.
She checks them with a SKYCAP and tips him.
A huge jet goes right to left through frame.
Barbara is greeted by KEVIN DULLI with a hug.
A baggage claim check is slipped into Kevin's hand.
BARBARA Any message?
KEVIN Keep it coming.
We see Barbara's two red Samsonites being taken off the belt by Kevin.
Same scene repeated, except different clothes on all.
Maybe Kevin is dressed a little better.
KEVIN More.
The same scene repeated, same things changed again; now Kevin is definitely dressed a little better.
KEVIN I need more.
BARBARA What do you want me to do?
BARBARA I can only take two bags, and I can't fly back here everyday.
KEVIN I know, but I've got a feeding frenzy on my hands.
KEVIN Tell George this is small potatoes.
KEVIN We're missing out on some serious cash.
KEVIN You tell George.
KEVIN He'll think of something.
Tuna drives the big Winny.
Maria rides shotgun.
Barrelling cross-country, it's a party on wheels.
Kevin and his girl, RADA, are the welcoming committee as the RV pulls into the parking lot.
They wave, slap the sides of the Winnebago, and greet the prodigal sons with hugs and handshakes.
George's room is rustic and plush.
A log fire burns and empty champagne bottles adorn the surroundings.
The girls have taken to each other.
The music is loud, and they dance while the boys do business.
Kevin counts out the money.
It's stacked in piles all over the table.
KEVIN Twenty, forty, sixty, eighty, nine.
KEVIN Twenty, forty, sixty, eighty, a thousand.
KEVIN It's all there.
KEVIN Wow.
KEVIN A hundred and twenty-eight thousand dollars.
TUNA Jesus Christ, I'm getting a boner just looking at it.
But George isn't paying attention.
His wheels are turning.
KEVIN What's the matter, George?
KEVIN Something wrong?
KEVIN You look like you just fucked your mother.
TUNA Cheer up, man.
TUNA Half this money is ours.
TUNA We're fucking rich.
GEORGE It's not enough.
KEVIN What?
TUNA What the fuck are you talking about, man?
GEORGE The set-up is wrong.
GEORGE We're doing all the legwork, and at the end of the day, we're still paying retail.
GEORGE We're getting middled.
KEVIN So?
GEORGE So, we need to get to the source.
TUNA Source?
TUNA What about Derek?
GEORGE He's getting middled, too.
GEORGE And Derek's our partner.
GEORGE What's good for us is good for him.
KEVIN Okay.
KEVIN So we need a source.
KEVIN Where do we start?
GEORGE Who speaks Spanish?
We PAN OFF the beautiful waters of Puerto Vallarta.
This is a local beach on a Saturday afternoon.
The girls on the beach are drinking coco-locos and swimming.
George with a bartender.
Tuna and Dulli with cabbies.
George and Derek talking with a local man, RAMON, at a corner bar.
Barbara, Maria and Rada talk with local girls.
TUNA This is bullshit, George.
TUNA We're never going to find anything down there.
KEVIN You know, he's got a point.
KEVIN We're fucking Americans.
KEVIN We stick out like sore thumbs.
DEREK I don't think so.
GEORGE You guys are such babies.
GEORGE You want to go home, go.
GEORGE Me, I'm not going to stop until I find the fucking motherlode.
RADA Georgie, we're gonna get busted if we keep this up.
GEORGE We're not gonna get busted.
KEVIN George, we'll wind up in a Mexican prison getting fucked up the ass by one of Maria's relatives.
MARIA Hey, fuck you, Dulli.
MARIA I'm not Mexican.
MARIA I'm Italian.
BARBARA You're Italian?
KEVIN Yeah, right.
KEVIN Gonzales.
KEVIN What is that, Sicilian?
TUNA As far as I'm concerned, we're on fucking vacation.
He grabs Maria, runs and does a huge belly-flop into the water.
They all laugh.
George and Barbara with local musicians on the beach.
George and Derek at a cab stand.
George talks with a bellboy in the lobby of a local hotel.
George, Barbara, Tuna, Derek, Maria, Kevin, and Rada are at the bar.
Ramon comes up to George, they briefly discuss and George follows him out of the bar.
George and Ramon climb into a beat up V.W. bug and take off.
Fields and Farms.
The V.W. bug pulls up to an old ranch.
They get out of the bug and are greeted by SANTIAGO and his
SANTIAGO Ramon tells me you are looking for some mota.
GEORGE Yes, I am.
Santiago moves to a tarp and pulls it back to reveal many bales of green, seedless sinsemilla.
SANTIAGO For instance, something like this?
GEORGE Very nice.
GEORGE I'll take it.
SANTIAGO Ha ha ha.
SANTIAGO You are funny.
SANTIAGO Really, how much will you be needing?
GEORGE All of it.
GEORGE As much as you've got.
GEORGE A couples thousand pounds.
GEORGE I'll be back in a week with a plane.
SANTIAGO Listen, Americano, it is very nice to meet you, but maybe we are going too fast.
SANTIAGO You take a little and then come back.
GEORGE I don't need a little.
GEORGE I need a lot.
SANTIAGO Marijuana is illegal in my country, and I believe in yours, as well.
SANTIAGO We must be careful.
GEORGE What if I brought you, let's say, fifty thousand dollars?
GEORGE Would that eliminate some of your concerns?
SANTIAGO Amigo, you bring me fifty-thousand dollars, and I have no more concerns.
A pair of boltcutters snaps the chain off a single-engine Cessna.
TUNA I can't believe we're stealing a plane.
KEVIN Don't be such a pussy.
GEORGE It's fine.
GEORGE We're not stealing it.
GEORGE We're borrowing it.
GEORGE And try to look natural.
GEORGE We've got company.
A MECHANIC working on the adjacent plane is giving them the hairy eyeball.
GEORGE (CONT'D) Be cool.
The three boys nod their heads in acknowledgement and give a small wave.
The mechanic smiles and waves back.
The engine is on and the propeller is spinning.
Kevin is at the controls.
Tuna is not making the trip.
He pokes his head in before shutting the cockpit.
TUNA You guys are fucking insane.
George reads from a flight manual.
GEORGE Alright, pull back the throttle...
The engine screams.
GEORGE (CONT'D) Not that far, only halfway.
GEORGE (CONT'D) You sure you know what you're doing?
KEVIN Relax.
KEVIN I've flown with my old man a million times.
KEVIN And he always told me, the taking off part is easy, it's the landing you've got to worry about.
The plane tries to land.
It's a clumsy one.
The Cessna is tipping and touching, first one wheel, then another, almost sideways before straightening out and stopping.
George and Kevin hop out of the plane.
They are greeted by Santiago and the Mexican contingency.
AMIGOS Hola, George!
AMIGOS Bienvenido!
George hands out presents to everyone.
He's like Santa Claus, giving gifts to every man, woman and child.
They love him.
Santiago pumps George's hand.
SANTIAGO Good to see you, Jorge.
SANTIAGO You are a man of your word.
GEORGE Actually, I've got some news.
GEORGE That fifty thousand I promised you, I couldn't get it.
George throws Santiago a duffel bag.
GEORGE (CONT'D) So I brought you sixty.
Rada sits in the Winnebago and keeps flashing the headlights.
Barbara, Tuna, and Maria stand on top of the Winnebago waving big, white towels.
The plane descends from the sky and touches down, making another extremely shaky landing.
It's on the water and beautiful.
The furnishings are distinctly Derek Foreal.
It's a surreal scene.
The holiday decorations are up, TOPLESS WOMEN in elf outfits sip champagne, and a thousand pounds of cannabis lays on the living room floor.
GEORGE Are you sure you want to do this in front of everyone?
DEREK Don't be ridiculous, these are my babies.
George empties the pot all over the floor.
DEREK (CONT'D) George, you're a genius.
DEREK (CONT'D) We're rich.
DEREK (CONT'D) Come, children.
The girls dive on top of Derek, caressing and kissing him.
DEREK (CONT'D) George, get my camera.
Derek poses with a load of marijuana like it's a new fur.
DEREK (CONT'D) Take a picture of me, George.
DEREK (CONT'D) Take a picture of me with my new friends.
DEREK (CONT'D) It'll be a fabulous Christmas card.
A Mexican Real Estate Agent shows Barbara and George a sprawling Villa in Puerto Vallarta.
It's amazing.
White marble on the water.
George looks at Barbara.
GEORGE Should we buy it?
BARBARA Are you kidding?
GEORGE We'll take it.
The team is there.
All of them.
George, Barbara, Kevin, Rada, Tuna, Maria and Derek with a couple of new senorita friends.
They all wear identical Mexican sombreros.
A MEXICAN BOY approaches them with a camera.
MEXICAN BOY Picture?
They pose, their arms thrown around each other in camaraderie, and FLASH.
The picture freezes and WE DISSOLVE.
George is taking Barbara and his parents out to dinner.
The Buggy Whip is Ermine's favorite.
ERMINE I just can't get over the size of that ring.
ERMINE I just love it.
ERMINE Fred, look at it.
ERMINE Tell me you don't love that ring.
FRED I'm just happy that George has found someone he cares for.
ERMINE Yes.
ERMINE Of course.
ERMINE But, I'm talking about that ring.
ERMINE It's something else.
ERMINE Let me tell you.
BARBARA George has exquisite taste.
ERMINE What is that, two carats?
ERMINE That's got to be two carats.
BARBARA I don't know.
ERMINE Yes.
ERMINE It's at least two carats, darling.
ERMINE Treasure it.
FRED Hard to imagine being able to afford a ring like that on a construction salary.
All eyes turn to George, who fumbles.
GEORGE Well, you know.
GEORGE It's um...
ERMINE Oh, shut up, Fred.
ERMINE Shut your big fat mouth.
ERMINE You don't buy it all at once.
ERMINE It's called layaway.
FRED Layaway shmayaway.
ERMINE That's right.
ERMINE Layaway.
ERMINE Something you wouldn't know anything about, you cheapskate.
FRED Who's the cheapskate?
ERMINE You, you big old tightwad.
ERMINE He still has his communion money.
ERMINE Tell him, George.
ERMINE Tell your father about layaway.
GEORGE Yeah, layaway.
ERMINE The boy is happy, Fred.
ERMINE Don't be such a killjoy.
FRED Killjoy?
George looks to Barbara, whose nose is bleeding.
GEORGE Honey, your nose!
BARBARA Oh my G-d, I'm so sorry.
ERMINE Barbara, here, take my napkin.
BARBARA Thanks.
BARBARA I'll be okay.
GEORGE You wanna split?
BARBARA Yeah, I don't feel so well.
GEORGE Okay, guys, we're gonna leave.
GEORGE Let's get the check.
George and Barbara exit the restaurant.
GEORGE Are you sure you're okay?
GEORGE You're pale.
BARBARA I feel like shit.
BARBARA Me and my frigging nosebleeds.
GEORGE I'm taking you to the doctor when we get home, and I don't want to hear any arguments.
BARBARA Would you be bummed out if I didn't go to Chicago with you?
GEORGE No, not at all.
GEORGE Sure.
GEORGE You're right.
GEORGE You fly home and get some rest.
BARBARA Nice first impression.
BARBARA A nose bleed in front of your parents.
GEORGE Oh my G-d, how embarrassing were they?
GEORGE I wanted to shoot myself.
BARBARA Oh, they weren't that bad.
BARBARA I mean, they were kind of cute.
GEORGE Promise me that we'll never be like them.
GEORGE I don't want to wind up like that.
BARBARA Relax, baby.
BARBARA We're going to wind up like us.
MUG SHOTS of George.
Left, right, center.
George sits handcuffed to a chair.
Piles of marijuana bricks roll past him.
GEORGE (V.O.) I had a little problem in Chicago.
GEORGE (V.O.) Something about trying to sell a truckload of dope to an undercover officer.
GEORGE (V.O.) So I applied the three rules of the game under if and when arrested.
George and his COURT APPOINTED ATTORNEY stand before the JUDGE at the arraignment.
GEORGE (V.O.) Rule one: don't fight.
GEORGE (V.O.) A trial will cost you a fortune in lawyer's fees and the jury will chop off your balls and hand them to you on a platter.
JUDGE George Jung, you have been accused of possession of six-hundred and sixty pounds of marijuana with intent to distribute.
JUDGE How do you plead?
GEORGE (V.O.) Rule two: plead not guilty and get bailed out of jail.
GEORGE (CONT'D) Your honor, I'd like to say a few words to the court.
The court appointed attorney puts his head in his hands.
JUDGE By all means.
GEORGE In all honesty, I don't feel like what I've done is a crime and I think it's illogical and irresponsible for you to sentence me to prison.
GEORGE None of the real criminals of the world ever end up behind bars.
GEORGE I mean, when you think about it, what did I really do?
GEORGE Cross an imaginary line with a bunch of plants?
GEORGE You say that I'm an outlaw, you say that I'm a thief, but where's the Christmas dinner for the people on relief?
George stops when his attorney stamps on his foot.
The court officers roll their eyes and the judge smiles.
JUDGE Those are very interesting concepts you have, Mr. Jung.
JUDGE Unfortunately for you, the imaginary line you crossed is real, the plants you brought with you are illegal, and what you did constitutes a crime.
The judge slams his gavel.
JUDGE (CONT'D) Bail is set at twenty-thousand dollars.
George walks out, free on bond, to find Barbara waiting for him.
She doesn't look so good.
BARBARA Surprise.
GEORGE Baby, you didn't have to come.
BARBARA What, and miss all the fun?
BARBARA C'mon, not a chance.
BARBARA So, what's the verdict?
GEORGE Lawyer says he can plead it down to five years.
GEORGE I'll serve two.
BARBARA Two years.
BARBARA George, I can't wait that long.
GEORGE What?
GEORGE You're not going to wait for me?
BARBARA George, I went to the doctor.
BARBARA I don't have two years.
Which brings me to rule number three: which says, fuck rules one and two, skip bail and take off.
George hits the gas and the car screams down the road.
George and Barbara sit on the veranda drinking champagne and watching the sun go down over the Pacific.
Barbara is completely bald.
Rail thin, eyes sunken.
But it doesn't matter.
They're having a great time.
They laugh and hold hands and laugh some more.
Everyone is there.
All in black.
Barbara's casket is lowered into the ground and George climbs to his knees to push the first dirt on the grave.
GEORGE (V.O.) Time is such a funny thing.
GEORGE (V.O.) I look at where I am now, and in here, time inches along.
GEORGE (V.O.) So slow, it hardly seems like it moves.
GEORGE (V.O.) But back then, time went fast.
George pushes dirt along the edge of a flower root.
Still planting those sunflowers, he presses down firmly, standing before him is Barbara, still beautiful and young with flowing locks.
George raises his hand and makes a small wave.
Barbara opens and closes her hand.
Bye bye.
GEORGE It went too fast.
George looks down and Barbara is gone.
No Barbara.
George hops the fence like he did when he was a boy and goes in the back door.
Ermine looks at George blankly.
GEORGE Hi, Mom.
Ermine just keeps looking at him.
GEORGE (CONT'D) Surprised to see me?
ERMINE Take your boots off.
ERMINE You're tan.
GEORGE Mexico.
ERMINE Yeah.
ERMINE We heard all about it.
ERMINE I want you to know I'm deeply sorry about your girlfriend.
GEORGE Barbara.
ERMINE Yes, Barbara.
ERMINE She was very pretty.
GEORGE Thank you.
GEORGE Have you been getting the money I sent you?
ERMINE You mean the drug money?
ERMINE Yes, I got it.
Ermine's hands are trembling.
She is emotional.
She hugs George ferociously, not letting go.
ERMINE (CONT'D) G-d, son.
GEORGE Okay, Mom.
GEORGE It's okay.
GEORGE Where's Dad?
George turns around to see Fred's beaming face.
George and Fred sit at the table, a bottle of Scotch sits between them.
The glasses are raised.
GEORGE May the wind always be at your back and the sun always upon your face...
FRED ...and the winds of destiny carry you aloft...
BOTH ...to dance with the stars.
The glasses clink and the drinks are sucked down.
The bottle is dwindling.
George and Fred are feeling it.
FRED You alright?
George nods.
GEORGE Just low.
FRED You loved her, didn't you?
FRED You really loved her.
GEORGE Yeah, Dad.
GEORGE I really did.
GEORGE What am I gonna do?
FRED Tough spot.
The glasses are refilled.
GEORGE You mad at me?
FRED Not mad.
GEORGE Yeah, you are.
GEORGE I can tell by the way you look at me.
FRED I just don't know what you're thinking.
FRED I don't understand your choices.
FRED You know, the police are looking for you.
GEORGE I know.
GEORGE I'm great at what I do, Dad.
GEORGE I mean, I'm really great.
FRED Let me tell you something, son.
FRED You would have been great at anything.
Something outside catches George's eye.
A light.
A reflection.
A movement.
George is up and on the move.
FRED (CONT'D) Where are you going?
The front door opens and FEDERAL AGENTS pour into the house.
George is up the stairs in a flash.
ERMINE George!
George slams the door behind him, moves over to the window, and opens it.
Cops everywhere.
He's trapped.
Out of options, he folds.
He moves to the corner and sits down, turns on the train set.
A KNOCK on the door is heard.
FBI Agent, JAMES T. TROUT.
TROUT George Jung, you are under arrest.
FRED Open the door, son.
They lead George outside in handcuffs.
Ermine and Fred watch.
ERMINE I had no choice.
George stops and looks at his mother, for the first time realizing her betrayal.
ERMINE (CONT'D) Don't look at me like that.
ERMINE (CONT'D) What was I supposed to do?
ERMINE (CONT'D) You're in our house.
ERMINE (CONT'D) What, was I supposed to be an accomplice?
As George is led to the police car, Ermine follows.
ERMINE (CONT'D) You don't think people know you're a drug dealer?
ERMINE (CONT'D) Everyone knows.
ERMINE (CONT'D) It's no secret.
ERMINE (CONT'D) How do you think that reflects on me?
ERMINE (CONT'D) Every time I go out, I'm humiliated.
ERMINE (CONT'D) I see the stares.
ERMINE (CONT'D) I hear the whispers.
ERMINE (CONT'D) How do you think that makes me feel?
ERMINE (CONT'D) Did you ever once stop and think of me?
George's head is pushed down as he is put in the squad car.
He looks up at his mother.
ERMINE (CONT'D) So you go to jail.
ERMINE (CONT'D) It's for your own good.
ERMINE (CONT'D) You need to straighten your life out.
George is being led through a series of gated corridors.
GUARD Prisoner in.
As he walks, he takes in the faces of the other inmates.
He arrives at his cell and notices he has a ROOMMATE.
GUARD (CONT'D) Prisoner in.
The cell door opens and George steps inside.
There are books and papers spread out over both bunk beds.
George watches as his cellmate quickly clears everything off the top bunk.
Apparently, the papers are private.
George puts his things down and the little man proffers his hand.
He is dark, polite and Colombian.
DIEGO DELGADO My name is Diego Delgado.
DIEGO DELGADO How do you do?
George pushes his tray through the cafeteria line.
Diego is behind him.
DIEGO If you don't mind me asking, what is the reason you are in this place?
GEORGE What?
DIEGO Your offense?
DIEGO Why are you here?
GEORGE I don't want to talk about it.
DIEGO Intriguing.
DIEGO I see.
DIEGO Would you like to know my crime?
GEORGE Not really, no.
DIEGO No?
GEORGE I don't like a lot of conversation, Diego.
DIEGO Me, too.
DIEGO Too much blah, blah, blah, blah is no good.
DIEGO But we are roommates, okay?
DIEGO And we must talk to each other.
DIEGO I am arrested for stealing cars.
DIEGO For the grand theft auto.
DIEGO Okay?
DIEGO So, now it is your turn.
DIEGO Now you will tell me, okay?
DIEGO You will tell me why you are here?
George says nothing.
He keeps eating his food.
DIEGO (CONT'D) Oh, come on, George.
DIEGO (CONT'D) If we are to be friends, we must trust each other.
GEORGE Murder.
DIEGO Ah, yes.
DIEGO The murder.
George lays on his bunk, smoking.
Diego is on the bottom bunk, furiously writing on a notepad.
He flips through his books and rustles his papers.
George peeks over the side to see what Diego is doing.
GEORGE What do you got there, Diego?
DIEGO Nothing.
DIEGO Just a little project.
GEORGE What kind of project?
DIEGO Never mind.
DIEGO Not for you to worry.
GEORGE I thought you said we were roommates.
GEORGE That we should talk about everything.
DIEGO You have your intrigues.
DIEGO I have mine.
DIEGO This is a happy day for me, George.
DIEGO Nine months from today, I will be in Medellin sipping champagne.
DIEGO In nine months, I am free.
DIEGO How much time do you have?
GEORGE Twenty-six months.
DIEGO Twenty-six months?
DIEGO For murder?
DIEGO I must be your lawyer.
GEORGE I've got to get out of here, Diego.
DIEGO Only two ways I know to leave here early.
DIEGO One is to escape.
GEORGE What's the other one?
George is trying to teach basic education to the inmates.
The room, mostly black and hispanic, is hostile.
They don't want to learn.
GEORGE Alright, let's open our books.
INMATE #1 Man, fuck you.
INMATE #2 We ain't opening shit.
INMATE #1 You just the warden's boy.
INMATE #1 We on to you.
INMATE #1 You just trying to knock some time off, asskissing motherfucker.
Diego watches as the room reacts with laughter.
This ain't going to be easy.
GEORGE Alright.
GEORGE You're right.
GEORGE I want to get out of this shithole as fast as I can.
GEORGE And I don't want to do this any more than you do.
GEORGE But for me to walk early, some of you have to graduate.
GEORGE You, forget about it.
GEORGE You're hopeless, go to sleep.
The room laughs again.
INMATE #3 Damn, homeboy, you got ruined.
GEORGE But the rest of you could get diplomas and get jobs when you're on the outside.
The room looks at him.
They ain't buying it.
INMATE #1 Shit, I'm in for life.
INMATE #2 I'm a criminal.
INMATE #2 I ain't getting no motherfucking job.
GEORGE We can learn some criminal shit, too.
GEORGE Alright, I'll make you a deal.
GEORGE What if half the time, we learn about George Washington, and the other half, I'll teach you how to smuggle drugs?
INMATE #2 Man, you don't know dick about smuggling no drugs.
GEORGE I was arrested in Chicago with six hundred and sixty pounds of grass.
GEORGE I think that qualifies me.
Diego looks up from his desk, suddenly very interested.
INMATE #1 How did you get a hold of six-hundred and sixty pounds of dope?
GEORGE Flew it in from Mexico on a single engine Cessna.
GEORGE Now, do we have a deal or not?
They react.
They're in.
GEORGE (CONT'D) Alright, the first thing you need to know about smuggling drugs is that it's easy.
GEORGE (CONT'D) The DEA are a bunch of losers.
GEORGE (CONT'D) They couldn't find their dicks in a whorehouse.
GEORGE (CONT'D) They don't know what the fuck they're doing...
Diego watches George winning over the room.
He listens intently to George's every word.
His wheels are turning.
Lights out.
Diego and George lay in their cots.
George is tired.
Diego is not.
DIEGO George?
DIEGO Hey, George?
DIEGO I listen to what you say to the class today about the smuggling.
DIEGO You are a magico, ah?
George doesn't respond.
DIEGO (CONT'D) I never believed you were a murderer.
DIEGO (CONT'D) I knew.
DIEGO (CONT'D) I knew you are a magico.
DIEGO (CONT'D) I have seen it in you.
DIEGO (CONT'D) It's in your spirit.
GEORGE I'm tired, Diego.
GEORGE Go to bed.
DIEGO You like to make the boundaries disappear.
DIEGO It's not only the money, is it, George?
DIEGO The adventure is part of the victory.
DIEGO It's the thrill, ah?
GEORGE Good night.
DIEGO In my country, I am a magico.
DIEGO A man with a dream.
DIEGO A man on the rise.
DIEGO To take nothing and make it something, okay?
DIEGO I have failed my dream, but I will accomplish.
DIEGO That is why I am in your country.
DIEGO Yes, I lose my freedom.
DIEGO But they do not take my dream.
DIEGO Do you have a dream, George?
GEORGE I would if I could get some sleep.
DIEGO Yes, you have a dream.
DIEGO And maybe you accomplish your dream.
DIEGO But yet you failed.
DIEGO Why?
GEORGE Because I got caught.
DIEGO No, my brother.
GEORGE Because they caught me?
DIEGO You failed because you had the wrong dream.
Diego climbs off his bunk and looks George square in the eye.
DIEGO (CONT'D) George?
DIEGO (CONT'D) What do you know about cocaine?
GEORGE I don't know, Diego.
GEORGE I've got a good thing going already.
GEORGE Everybody smokes pot.
GEORGE It's easy.
GEORGE Cocaine is a rich man's drug.
GEORGE It's too expensive.
DIEGO No, no.
DIEGO That is where you are wrong.
DIEGO For us, it is cheap.
DIEGO In Medellin, we buy for six-thousand dollars a kilo.
DIEGO IN Miami, we sell for sixty.
George's interest is piqued.
GEORGE That's over fifty-thousand dollars profit per kilo.
DIEGO And that's wholesale.
DIEGO Cut it a few times and retail, you're looking at two, three-hundred thousand.
GEORGE Oh my G-d.
DIEGO Yes.
DIEGO And a kilo of coca is smaller than a kilo of your precious marijuana.
DIEGO Everything is the same, George, except instead of thousands, you are making millions.
GEORGE Jesus Christ.
GEORGE Jesus fucking Christ.
DIEGO Now do you see what I am saying?
GEORGE Getting it here is no problem.
GEORGE Trust me.
GEORGE I'll fly it in myself if I have to.
GEORGE What about supply?
GEORGE How much can we get?
DIEGO Don't worry.
DIEGO We will talk of everything.
DIEGO We have the time.
DIEGO You arrive here with a Bachelor of Marijuana, but you will leave with a Doctorate of Cocaine.
Diego and George pouring over Diego's plans.
Discussing, planning, plotting.
DIEGO What type of planes do you have?
GEORGE Four passenger, single engine Cessna.
DIEGO How many kilos can we fit in these planes?
GEORGE I don't know.
GEORGE A hundred, hundred and fifty.
GEORGE How many miles is it from Colombia to Miami?
DIEGO Fifteen hundred.
DIEGO We'll have to stop somewhere to refuel.
GEORGE We'll refuel in the Bahamas.
GEORGE I know someone there.
DIEGO Great.
DIEGO I love the Bahamas.
George is at a payphone.
He drops in about a million quarters until he is finally connected.
GEORGE Diego Delgado, please?
DIEGO Allo?
GEORGE Diego?
GEORGE It's George.
DIEGO George, hallo!
DIEGO Today is the day, ah?
DIEGO Are you out?
GEORGE Yeah, I'm out.
DIEGO Congratulations, brother.
DIEGO I've been waiting for you.
GEORGE How are we doing?
DIEGO Perfect, George.
DIEGO Perfect.
DIEGO Everything is fine down here.
DIEGO Everything is all set up.
GEORGE Do we need a plane?
GEORGE How does this work?
GEORGE When do I see you?
DIEGO Slow down, George.
DIEGO Slow down.
Fred exits the liquor store carrying two bottles of Dom Perignon.
As he catches George's eye, he lifts the bottles showing them off.
George holds up his finger, indicating he'll be just a second.
DIEGO (CONT'D) You need to come down here, everybody meets everybody.
DIEGO (CONT'D) Ho ho ho.
DIEGO (CONT'D) Ha ha ha.
DIEGO (CONT'D) We do one for good faith and then we talk about airplanes.
GEORGE I can't go anywhere, Diego.
GEORGE I'm on parole.
GEORGE I can't leave the state.
DIEGO But you must.
DIEGO It's the only way.
GEORGE I just got released five minutes ago.
DIEGO George, are we gonna do this or not?
George steps outside and spots Diego.
Their eyes meet.
Diego looks different, relaxed.
He wears a straw hat, shorts, and sports a healthy tan.
The two men embrace.
GEORGE Good to see you, Diego.
DIEGO Yes.
DIEGO Look around you.
DIEGO The sun.
DIEGO The water.
DIEGO The women.
DIEGO It's better than Danbury, no?
DIEGO Come on.
DIEGO I have some friends I would like you to meet.
Diego and George sit with five other Colombians, most notably, a man named CESAR ROZA.
The mood is not friendly.
DIEGO Fifteen kilos.
DIEGO Seven and a half in each suitcase.
DIEGO You receive a hundred thousand dollars upon delivery.
GEORGE Okay.
CESAR Not so fast.
CESAR I would like to go over the details.
GEORGE What details?
GEORGE I put the coke in the false bottoms and take it through customs.
CESAR Tell me about the suitcases.
CESAR What is the make and the color?
DIEGO Samsonites.
DIEGO Red.
DIEGO No tags.
Cesar thinks about it.
CESAR Hmm.
CESAR I see.
CESAR Will there be clothes in the suitcase?
GEORGE What?
GEORGE Yeah, sure.
CESAR Whose cloths?
CESAR Your clothes?
GEORGE My clothes, your clothes.
GEORGE What does it matter?
CESAR I would like to know the contents.
CESAR Every detail is important.
GEORGE What are we doing here, Diego?
GEORGE This guy's a clown.
GEORGE He's talking about clothes.
CESAR I demand to know everything.
CESAR I do not trust six-hundred thousand dollars of coca to someone I don't know.
GEORGE It's a lousy fifteen kilos.
GEORGE I piss fifteen kilos.
CESAR The coca is my responsibility!
GEORGE You're a fucking amateur!
DIEGO Gentlemen, please.
DIEGO There is no need to be impolite.
DIEGO Cesar, this will be fine.
DIEGO You have my word.
DIEGO George, Cesar is just being thorough.
DIEGO That's all.
CESAR Very well.
CESAR But just remember, Mr. Jung.
CESAR I will be with you the whole way.
CESAR And I will be watching.
George carries the two Samsonites over to customs inspections.
It's a long walk.
George's heart beats hard.
The sound is audible and grows with every beat.
BA-BUMP.
BA BUMP.
Cesar lurks at the baggage carousel.
GEORGE (V.O.) When you're carrying drugs across the border, the idea is to remain calm.
GEORGE (V.O.) The way I do it is to think of something pleasant, a fun party, a moment of triumph.
GEORGE (V.O.) A sexual encounter.
GEORGE (V.O.) I actually project myself to that place.
GEORGE (V.O.) Anything to keep your mind off the fact that you're going to jail for a very long time if they find the fifteen kilos of cocaine in your suitcases.
George stands in front of the customs agent.
He tries his best to look relaxed as the agent reviews his documents.
CUSTOMS AGENT On vacation?
GEORGE Yes.
CUSTOMS AGENT On vacation for only one day?
BA-BUMP.
BA-BUMP.
The heartbeats are very loud.
GEORGE My brother's wedding.
GEORGE Imagine that, huh?
George's breathing is labored and his swallowing reflex doesn't seem to be working.
Cesar passes through, eyeballing George the whole time.
CUSTOMS AGENT Open your bags, please.
George opens the Samsonites.
Super dry mouth.
BA-BUMP.
BA BUMP.
The beats are deafening now.
Cesar nervously monitors the situation from the payphones.
CUSTOMS AGENT (CONT'D) Whose clothes are these?
GEORGE Mine.
The customs agent holds up a woman's undergarment.
Cesar throws up his hands in frustration.
CUSTOMS AGENT And this?
GEORGE What can I tell you?
GEORGE Different strokes.
George winks at the customs agent, who shakes his head before finishing the inspection.
CUSTOMS AGENT Alright, go ahead.
George moves to the payphones, sets down the two suitcases, and pretends to make a call.
Not inconspicuously, Cesar grabs the bags and walks quickly out of the terminal.
Diego, Cesar, George and JACK STEVENS, a silver haired executive type, lounge around the mini-suite.
Cesar still has that crazy look in his eye.
DIEGO Three-hundred kilos it is, then.
A beautiful Latin woman enters and kisses both Diego and Cesar.
Her name is INEZ, and friendly she is not.
DIEGO (CONT'D) Has everyone met Inez?
DIEGO (CONT'D) This is George.
DIEGO (CONT'D) I've told you about him.
DIEGO (CONT'D) And this is friend, Jack Stevens.
The men proffer their hands, but she just looks at them like ants before sitting down next to Diego.
DIEGO (CONT'D) Try to be more respectful, darling.
DIEGO (CONT'D) My apologies.
DIEGO (CONT'D) But she is mistrustful of Americans.
DIEGO (CONT'D) Shall we proceed?
DIEGO (CONT'D) Let's hear it again, Mr. Stevens.
STEVENS I'll fly down on a Friday, refuel in the Bahamas, and then to Medellin.
INEZ Friday?
Inez addresses Diego and Cesar only.
She speaks in Spanish.
The conversation is about "Why Friday?" Inez has some problem with it.
Diego explains.
And Inez is reassured.
DIEGO Please, continue.
GEORGE We make the pick-up, refuel once more in the Bahamas, and fly back on Sunday with the mom and pop traffic.
CESAR Why are you speaking?
GEORGE Excuse me?
CESAR You.
CESAR Your responsibility is over.
CESAR You do not fly.
CESAR You are not a pilot.
CESAR You are not a distributor.
CESAR You introduced us to Mr. Stevens and the use of his airplane.
CESAR That is all.
CESAR You make a percentage.
CESAR A generous one.
CESAR And you're lucky to get that.
GEORGE I see.
GEORGE How much?
CESAR Padrino will pay ten-thousand per kilo.
CESAR For everyone.
CESAR For you, and you, and you.
He indicates George, Diego and Jack Stevens.
CESAR (CONT'D) There is no negotiation.
CESAR (CONT'D) Three-million dollars.
CESAR (CONT'D) That is all.
STEVENS I want two.
GEORGE Gee, Jack, a million each had such a nice ring to it.
STEVENS No way.
STEVENS I'm doing all the work.
STEVENS Taking all the risk, and it's my plane.
Diego and George look at each other.
STEVENS (CONT'D) Hey, you guys don't have to do shit.
STEVENS (CONT'D) Just sit back and collect your money.
GEORGE You good with this?
Diego nods.
GEORGE (CONT'D) Alright.
This is too much for Inez to handle.
She starts screaming machine gun Spanish.
Something about a "lousy two-hundred and fifty-thousand dollars," and how Diego is "such a coward" to give away all his money.
Diego is embarrassed but tries to remain calm.
DIEGO You will watch what you say.
DIEGO Especially around George.
DIEGO He is my brother and he speaks as good Spanish as you.
But Inez is wild.
She starts in again, a log of "Putos (SOB's)", and "Cojones" and "Maricones (gay/sissys)."
Even Cesar is uncomfortable.
Diego stands.
DIEGO (CONT'D) Okay.
DIEGO (CONT'D) That's enough.
INEZ Get your hands off me.
Inez takes a swing at Diego and catches him full across the face.
Time stops in the room.
Question.
What will Diego do?
Answer: SMACK!
Diego swings back and a full scale is on.
Cesar continues the conversation.
It's surreal.
As if Diego and Inez weren't beating the shit out of each other right in front of them.
CESAR Do you have pictures of your kids?
STEVENS What?
CESAR I'll need to see them.
CESAR Also need their names and the names of their schools.
CESAR We are trusting you with ninety million dollars worth of coca, Mr. Stevens.
CESAR Without your children, there is no deal.
Stevens thinks about it.
Kids as collateral.
Inez and Diego are still duking it out.
But Diego finally gets the upper hand and drags her into the bedroom.
STEVENS Fine.
STEVENS So if that's all, I'll be leaving now.
Cesar walks him to the door.
CESAR Don't forget the pictures.
Diego calls from the other room.
DIEGO George.
DIEGO George, come in here.
Diego has put Inez in the bathroom and is holding the door closed.
She pounds and kicks and screams in frustration, but he pays no attention.
DIEGO What's the matter, George?
GEORGE What's the matter?
GEORGE We're moving three hundred fucking kilos and we're making dogshit.
DIEGO A million dollars for our first run is not bad, George.
GEORGE It is bad.
GEORGE It's chump change.
GEORGE We might as well be hauling suitcases across the border.
GEORGE We're getting screwed.
DIEGO I know.
GEORGE And what happens when these guys stop paying?
GEORGE Sooner or later, these guys are going to cut us out.
GEORGE Then where are we?
DIEGO That's my George, always thinking.
The door is yanked open to reveal Inez.
She is in a rage.
Diego slams it in her face.
DIEGO (CONT'D) This is only part of the business, George.
DIEGO (CONT'D) A very small part.
DIEGO (CONT'D) Don't worry, there is so much more to do.
DIEGO (CONT'D) Which reminds me, I need a favor from you.
DIEGO (CONT'D) I must go to Colombia.
GEORGE What is it, George?
GEORGE Because I have to get home.
GEORGE I've got a parole officer waiting for me.
DIEGO I need you to go to Miami.
George gets out of a taxi to find SEVERAL COLOMBIAN MEN hanging around outside an apartment.
He checks the address and moves over to the men.
GEORGE I'm George.
GEORGE Friend of Diego's?
The Colombian men are not impressed.
They grab George and pull him inside.
George is pinned against the wall and the Colombian men all start screaming at him in Spanish.
There seems to be a problem.
A man, ALESSANDRO, steps forward.
He is the one who speaks English.
ALESSANDRO QUIET!
ALESSANDRO Callate!
ALESSANDRO Where's Diego?
GEORGE I don't know.
GEORGE He sent me.
GEORGE I'm George.
ALESSANDRO Oh, I see.
ALESSANDRO George.
ALESSANDRO Well, that explains everything.
ALESSANDRO Open your mouth, George.
George's puzzled look is replaced by a gun barrel in his face.
Alessandro presses it against George's front teeth.
ALESSANDRO (CONT'D) Now, you listen to me.
ALESSANDRO (CONT'D) Are you hearing me?
George nods.
ALESSANDRO (CONT'D) You see this?
He indicates two duffel bags stuffed with fifty kilos of cocaine.
ALESSANDRO (CONT'D) I've been holding this shit for him for three weeks.
ALESSANDRO (CONT'D) You tell Diego I don't appreciate it.
ALESSANDRO (CONT'D) You tell him I want my money by Friday.
ALESSANDRO (CONT'D) Can you do that?
GEORGE Um-hmm.
George sits on his bed, reading.
Two duffel bags are tucked away in the closet.
Ermine pokes her head in.
ERMINE You have a phone call.
George picks up the phone.
DIEGO George.
GEORGE Jesus Christ, Diego, where are you?
GEORGE It's been eleven days and these guys want their fucking money.
DIEGO Bad news, George.
DIEGO I'm in Colombia.
GEORGE Well, you better get here fast.
GEORGE I'm sitting on...
George notices Ermine is loitering in the hallway, eavesdropping.
GEORGE (CONT'D) Hi, Mom.
George acknowledges her before shutting the door in her face.
GEORGE (CONT'D) I'm sitting on fifty fucking keys.
GEORGE (CONT'D) Get your ass up here.
It's a South American prison.
Diego is on the pay phone.
DIEGO It's a little hard to get away right now.
DIEGO I'm afraid you're on your own.
George and Derek sit in the living room with MR.
T, a hippie ish looking professor.
On the table sits various paraphernalia.
Scales, beakers, test tubes, and a hot box.
George and Derek watch as Mr. T scoops some of George's cocaine and sets it onto the two-inch metal plate.
MR. T What we're doing is measuring the purity.
MR. T Pure coke melts out a hundred and eighty-five, a hundred and ninety degrees.
MR. T Cutting agents melt much lower.
MR. T About a hundred degrees.
MR. T Quality product starts melting at a hundred and forty degrees.
MR. T That's what I'm hoping for.
Mr. T turns the dial.
120.
130.
140.
MR. T (CONT'D) Good.
T (CONT'D) Jesus Christ.
T (CONT'D) Holy fucking Mary!
T (CONT'D) Jesus, fuck me running!
T (CONT'D) Where did you get this shit!
At one-hundred and eighty-seven degrees, the white powder dribbles off the hotplate and melts away.
MR. T (CONT'D) Damn!
MR. T (CONT'D) Can I do a fucking line?!
Mr. T puts his nose in the powder.
George pulls Foreal aside.
GEORGE What did I tell you?
DEREK It's great and everything, but what am I going to do with all this?
GEORGE Sell it?
DIEGO Jesus Christ, George, I don't see you in two years, and you show up at my door with a hundred and ten pounds of cocaine?
GEORGE Just sell it, Derek.
DEREK Alright, but it's gonna take me a year.
Money everywhere.
All over the floor, the counters, the chairs, and even in the sinks.
George and Derek count the money patiently, writing the dollar amount in yellow high lighter on the top of each stack, before wrapping it with a rubber band.
DIEGO Thirty-six hours.
DIEGO I can't believe it.
DIEGO Everything is gone in thirty-six hours.
GEORGE I think it's fair to say you underestimated the market there, Derek.
DIEGO Touche.
GEORGE But to the victor belong the spoils.
George divides the money.
There's a hell of a lot.
GEORGE (CONT'D) Half a million for you.
GEORGE (CONT'D) Half a million for me.
GEORGE (CONT'D) One-point-three five for the Colombians.
DEREK Nice doing business with you, George.
GEORGE Not bad for a weekend's work, huh?
Immaculate in his white turtleneck and sunglasses, George walks with two aluminum cases.
He is greeted by Alessandro and his thugs.
ALESSANDRO Greetings, Mr. George.
GEORGE Where do you guys want to count?
ALESSANDRO On the plane.
GEORGE What plane?
GEORGE We going someplace?
GEORGE Where we headed?
GEORGE You have your money.
GEORGE It's all there.
GEORGE What the fuck is going on?
They usher him away.
The lear jet lands.
The blazer pulls into a long driveway.
They approach a gate where SHIRTLESS TEENAGERS with MAC-10's stand guard.
The gate opens.
YOUNG SOLDIERS open the door for George and roughly usher him over to a Jeep within the confine.
They frisk him top to bottom.
Diego is leaning against another Jeep and waits for George to be released.
DIEGO George, good to see you, my brother.
GEORGE What the fuck is going on?
GEORGE When did you get out of jail?
DIEGO Pablo used his influence.
DIEGO Now, George, watch what you say.
DIEGO Everybody hears everything.
DIEGO A lot of things get said and done that, well, let's just say this isn't America.
DIEGO Life is cheap here, you know?
DIEGO No offense, but you know what I'm saying?
GEORGE Yeah.
GEORGE Keep my mouth shut and let you do the talking.
DIEGO Right.
DIEGO Now who is the person in California?
DIEGO The connection?
GEORGE Just a friend.
DIEGO Who?
DIEGO I need to know.
DIEGO Ah, never mind.
DIEGO We'll talk about it later.
GEORGE Yeah.
GEORGE You do the talking.
The sound of a young man, a MALETON, struggling can be heard in the distance.
From another area, PABLO ESCOBAR emerges.
He is singular in purpose.
He is handed a pistol and moves quickly over to the man and quietly speaks a few words.
And then, without emotion, he shoots the maleton in the head.
George and Diego, who is visibly shaken, watch.
Escobar is handed a towel, and he wipes the splattered blood off his hands, as he moves back.
LARGE COLOMBIAN MAN He will see you now.
LARGE COLOMBIAN MAN Not you.
DIEGO There must be some kind of mistake.
LARGE COLOMBIAN MAN No mistake.
LARGE COLOMBIAN MAN Mr. Escobar will see Mr.
LARGE COLOMBIAN MAN Jung alone.
LARGE COLOMBIAN MAN You are to wait here.
George hesitates.
DIEGO It's alright, George.
DIEGO You go.
LARGE COLOMBIAN MAN This way, please.
The large Colombian man escorts George towards the area where the maleton was just shot.
George looks back at Diego as he is led away.
ESCOBAR So, this is the man who takes fifty kilos and makes them disappear in one day?
GEORGE Actually, it was three.
ESCOBAR The man who gives us the airplanes.
ESCOBAR The man from America.
ESCOBAR The mafia.
ESCOBAR Chicago.
ESCOBAR Boom boom.
ESCOBAR Hollywood.
ESCOBAR You are going to open for us the gates of Hollywood, George?
GEORGE It would be my pleasure.
ESCOBAR Good.
ESCOBAR Very good.
ESCOBAR Welcome, my friend.
ESCOBAR Welcome to my country.
Escobar moves over to embrace George.
George returns it, and their hands come together.
George can't help it.
He reflexively looks at his hands.
Escobar understands.
ESCOBAR (CONT'D) The man in the garden.
ESCOBAR (CONT'D) He was full of courage.
GEORGE Un sapo?
ESCOBAR Un rata - no good.
ESCOBAR But he could have run, fled the country.
ESCOBAR Gone to the policia.
ESCOBAR But then his wife, his children, his parents, his friends, many people would die.
GEORGE Yes.
ESCOBAR But, never mind.
ESCOBAR I am thinking we can do much together.
ESCOBAR This problem with Diego, the stolen car, the jail, is very silly business.
ESCOBAR To release him from the carcel, it causes me much inconvenience.
ESCOBAR The fifty kilos could have been a big problem.
ESCOBAR And I don't like problems.
GEORGE With all respect, Padrino.
GEORGE Diego is my partner.
GEORGE I do not do business without him.
Escobar looks at him with a cold stare.
But George doesn't flinch.
His face reveals nothing.
Finally, a smile breaks across Pablo's lips.
ESCOBAR I like you, George.
ESCOBAR You are loyal.
ESCOBAR That is good.
ESCOBAR That is rare.
ESCOBAR Maybe crazy.
ESCOBAR Yes.
ESCOBAR I can tell already.
ESCOBAR You are like me.
ESCOBAR I look at you and I see myself.
ESCOBAR It's in the eyes, no, George?
GEORGE Yes, it is.
ESCOBAR So, you are wanting to sell the cocaine for me in your country, George?
GEORGE Yes, sir.
GEORGE As much as you can give me.
ESCOBAR As much as I can give you?
ESCOBAR Ha ha.
ESCOBAR Very good.
ESCOBAR I like that.
ESCOBAR Come, George.
ESCOBAR Let us drive.
ESCOBAR We have much to talk about.
Diego watches the two men walk outside.
Escobar throws an arm around George's shoulder.
Pablo hops into a Jeep and motions for George.
The bodyguards come running.
But Pablo waves them away.
Escobar pulls the Jeep off the road and parks it.
Before them is a stunning panorama.
ESCOBAR I like to come up here.
ESCOBAR To make the decisions.
ESCOBAR To be one with nature.
GEORGE It's beautiful.
ESCOBAR People tell me that I am crazy.
ESCOBAR That my business will never work in your country.
ESCOBAR What do you think, George?
Escobar looks out over the vista, allowing George the time to respond in full.
GEORGE What do I think?
GEORGE I don't want my answer to be influenced by what I want, so I'm going to have to say I don't know.
ESCOBAR Yes.
ESCOBAR I do not know, either.
ESCOBAR What do you want, George?
GEORGE I want money.
ESCOBAR Yes.
ESCOBAR Money.
ESCOBAR Which is what, George?
GEORGE Freedom.
ESCOBAR Power?
GEORGE Yeah, maybe.
ESCOBAR Family.
GEORGE Sure.
ESCOBAR Beautiful girls?
GEORGE Keep them coming.
ESCOBAR Keep them coming?
ESCOBAR Ah, yes.
ESCOBAR Ha ha.
ESCOBAR You are right.
ESCOBAR But money.
GEORGE Money.
ESCOBAR And Diego?
GEORGE Diego is my brother.
Escobar looks at George a long time.
He's inscrutable.
ESCOBAR Good.
ESCOBAR Take care of him, George.
ESCOBAR I'm fond of him, but he is sometimes like a baby.
ESCOBAR Keep an eye on him, okay?
Diego is a little pissed off for being left for so long.
He taps his foot and picks at his fingernails.
Escobar and George pull up in the Jeep.
Diego leaps to his feet.
DIEGO Padrino.
Escobar wraps his arms around Diego in an embrace.
ESCOBAR Diego, mijo.
ESCOBAR I've made a decision.
ESCOBAR We are going into business and I would like to start right away.
The following images are overlaid with snow falling and money dropping through frame.
CLOSE SHOTS of George and Diego on the phone, wheeling and dealing, hands counting cash, and lines being drawn off mirrors.
The effect is surreal and dreamy.
A duffel bag is unzipped, revealing bricks and bricks of cocaine.
Each marked with a "P."
A knife punctures one of the bricks.
A mound of white powder is brought up to a man's nose.
It's George who samples, and then it is sampled by the man he is doing business with.
The shot widens TO REVEAL all the participants and dozens and dozens of duffel bags.
A handshake seals the deal.
Handshake after handshake after handshake.
George and Diego counting cash.
It's everywhere.
All over the floor, in two-foot stacks.
Various transactions completed.
George and Diego count.
It's ridiculous how much money there is.
The stacks are now waist high and spill into other rooms.
Inez is there, pacing the floor and rapid-fire talking on the phone.
George and Diego, the Banditos.
Cigars.
Champagne.
Arms around each other in camaraderie.
In Diego's yellow Ferrari.
With Inez, sunning on a yacht.
More coke and more transactions.
When the deals are with Derek Foreal, Diego is always notably absent.
The money is so high, it almost reaches the ceiling.
There is nowhere to put it.
George and Diego sit at the coffee table, dwarfed by the stacks of bills.
There is a discrepancy in the count.
GEORGE Three million.
GEORGE I counted it twice.
DIEGO It's two-point-five, George.
DIEGO I am sure.
George starts to pick up the money.
GEORGE I'm calling it three.
DIEGO We're half a million off.
GEORGE Fuck it.
GEORGE I'm not counting it again.
DIEGO Weight it.
DIEGO If it's sixty pounds, it's three.
DIEGO If it's fifty, it's two-point five.
GEORGE I don't give a shit.
GEORGE Close enough.
George moves down the hall looking for a place to stack the money, but there is no more room.
GEORGE (CONT'D) Where do I put this!?
DIEGO Try the back bedroom.
George opens the back bedroom door to find wall-to-wall money.
It's packed.
GEORGE There's no room.
DIEGO Try the closet.
No luck there, either.
George drops the money on the floor and moves back into the living room.
GEORGE We've got to do something about this.
George and Diego watch as their money is hauled into a huge wall safe.
Armed Panamanian soldiers stand guard.
The Panamanian officials and the BANK PRESIDENT oversee the proceedings.
GEORGE Are you comfortable with this?
DIEGO George, we've got sixty-one million dollars.
DIEGO It's either here or someplace else.
DIEGO We've got to put it somewhere.
DIEGO Unless you want to launder it.
GEORGE And keep only forty-percent?
GEORGE No thanks.
DIEGO Then relax.
DIEGO It's a federal bank.
DIEGO Guaranteed by the government.
DIEGO And Senor Noriega has very lenient banking principles.
DIEGO No questions.
DIEGO No problems.
DIEGO All the pesados keep their money here.
DIEGO Even El Padrino.
DIEGO What do you worry?
DIEGO Everyone knows we are with Escobar.
DIEGO Who is going to fuck with us?
George and Diego sign papers.
The bank president congratulates them and hands them documentation.
GEORGE I love it.
BANK PRESIDENT I'm sorry.
GEORGE I give you thirty-million dollars and you give me this little book.
Diego and Inez's wedding.
The ceremony.
The ring.
The kiss.
The lineup with all of the bridesmaids.
George is the best man, and the only American.
A huge reception.
All the pomp and circumstance Colombian money can buy.
Politicians.
Policemen.
And every smuggler north of Colombia.
George sits with Diego and Inez at the table of honor.
Inez is opening presents.
Diego's tipsiness is a little out of character, but hey, it's his wedding day and a little champagne never hurt anyone.
He drunkenly throws his arm around George's shoulder.
DIEGO I'm married, George.
DIEGO Me.
DIEGO I can't believe it.
DIEGO Can you believe I'm married, George?
GEORGE You're a lucky man, Diego.
DIEGO I love you, my brother, do you know that?
GEORGE I love you too, man.
George notices MIRTHA showing teeth across the room.
GEORGE (CONT'D) I'll be right back, Diego.
INEZ Look, honey, a power boat.
DIEGO Great, baby, great!
They kiss.
George walks across the dance floor directly towards Mirtha.
GEORGE Hello.
MIRTHA Hello.
GEORGE Do I know you?
MIRTHA I don't think so.
GEORGE Why are you smiling?
MIRTHA Why are you smiling?
GEORGE I don't know.
GEORGE My name is George.
MIRTHA I know who you are, El Americano.
MIRTHA Mister George.
GEORGE What is your name?
Cesar arrives.
CESAR Mr. Jung, I see you've met my fiancee, Mirtha.
He kisses her.
GEORGE Mirtha.
CESAR Diego needs to see you right away, please.
CESAR Excuse us, Amorcito.
They leave.
George looks back, Mirtha is giving him more teeth.
George arrives at the table.
Various greetings.
AUGUSTO Pleased to meet you finally, George.
AUGUSTO I am Augusto Oliveras.
GEORGE My pleasure, Augusto.
GEORGE Diego has told me much about you.
RAMON OCHOA Congratulations on your conquest of the West Coast.
RAMON OCHOA How much bigger can we get?
GEORGE Sky's the limit.
GEORGE We're just beginning to tap the market.
GEORGE If it's accepted by actors and musicians, the rest will follow.
They all agree.
Mirtha still gives George the teeth from across the room.
Diego returns to the table.
AUGUSTO We are talking about George's West Coast operation.
DIEGO Ah, George's mystery man.
RAFAEL OJEDA Yes, where is this man?
RAFAEL OJEDA When do we meet him?
DIEGO You don't meet him.
DIEGO George keeps this a secret.
DIEGO He's here meeting everyone, goes to Colombia and meets Pablo, but still keeps his secrets.
DIEGO Even from his brother.
JUAN CARLOS "THE GUAPO" Come on, George, we're all in this together.
EMILIO OCHOA Yes, George, there's enough for everybody.
GEORGE I think Padroni is happy with the current situation.
GEORGE Will you please excuse me?
George exits after Mirtha.
George steps into the empty lobby looking for Mirtha.
He can't find her.
She appears from the shadows and startles him.
George embraces her and plants one on her.
MIRTHA You better know what you're doing, George.
MIRTHA You're playing with fire.
GEORGE I like fire.
CLOSE UP - George does a huge line, left to right.
CLOSE UP - Mirtha does a huge line, right to left.
A stretch limo flies by, left to right.
The windows are open and Mirtha and George whoop it up as they go by.
George and Mirtha out on the crowded dance floor, grooving to the Salsa rhythms.
Champagne bottles in hand, George and Mirtha on the tarmac running from the limo to the waiting private plane.
George and Mirtha poolside, wearing shades, getting some sun.
She blows him a kiss from the adjoining lounge chair.
He blows one back.
She licks her lips and it's on.
He's out of the chair, pouring champagne over her tan body, and licking it off.
She squeals with delight.
A table gets knocked over as they cause a commotion.
A hotel manager comes over, but George hands him a wad of cash and he quickly fucks off.
The dancing is in SUPER SLOW MOTION now.
Passionate, carnal, intimate.
George buys gifts for Mirtha and she shows them off for the camera.
A fur.
A ring.
A house.
Overhead shot of George and Mirtha's bedroom.
It's completely covered with money.
Completely covered.
George and Mirtha make love on the sea of cash.
As CAMERA PULLS UP we see money slowly falling from the ceiling.
There is no white dress.
There is no tuxedo.
George and Mirtha haven't even taken off their sunglasses.
MIRTHA I do.
They kiss.
Mirtha wipes her red nose.
MIRTHA (CONT'D) I need a fucking drink.
George moves to the bedroom.
Mirtha is pregnant and she's showing.
She's also bent over a mirror with a straw in her hand.
George opens the door and takes her by surprise.
GEORGE Jesus Christ.
MIRTHA Oh, don't be such a fucking hypocrite.
MIRTHA I quit smoking, didn't I?
GEORGE Put that shit away, they're here.
Mirtha and George lead Fred and Ermine from room to room, showing off the house.
The decor is, well, eclectic.
It doesn't match the architecture.
ERMINE It's all so beautiful.
MIRTHA What do you think, Dad?
FRED Yeah.
FRED Nice.
ERMINE Look at this credenza.
ERMINE If you don't mind me asking, how much is something like that?
ERMINE It's got to cost a fortune.
GEORGE It's a family heirloom.
ERMINE I've seen those in magazines.
ERMINE They're not cheap.
GEORGE Mirtha comes from a very wealthy family.
ERMINE Oh, I see.
MIRTHA Come on.
MIRTHA I'll show you the rest of the house.
George and his father move outside.
George and his father walk.
GEORGE So, business is going good.
GEORGE I've got this import/export thing going on in Miami that's been very profitable.
GEORGE With my investments...
FRED Don't bullshit me, George.
FRED I don't see you very much, I don't want to waste the time.
They move along the rear of the house.
Classic cars line the driveway.
FRED (CONT'D) You come from my body, remember?
FRED (CONT'D) You're my baby boy.
FRED (CONT'D) The same kid who would jump off a mountain if someone told him he couldn't do it.
FRED (CONT'D) You haven't changed much.
FRED (CONT'D) I know the things you do.
FRED (CONT'D) Not everything.
FRED (CONT'D) But I get the picture and I don't care.
FRED (CONT'D) I don't like it.
FRED (CONT'D) It's not what I would have chosen for you, but it's your life.
FRED (CONT'D) It doesn't have anything to do with me.
He turns and looks at his boy.
FRED (CONT'D) You're like your mother.
FRED (CONT'D) You love money.
GEORGE Dad.
FRED No, it's good.
FRED You have a family.
FRED It's good if it makes you happy.
FRED It's nice to have nice things.
FRED Are you happy, son?
GEORGE Yeah, Dad.
GEORGE I'm happy right now.
Diego puts a straw in his nose and snorts a big gakker.
His eyes are wide, his pupils dilated, and a weapon sticks out of the back of his pants.
He knocks the dust off his nose before moving outside.
George is on the porch, smoking a cigarette.
DIEGO Three years.
DIEGO How long have we been in business?
DIEGO Three years.
DIEGO Does she get to meet your connection?
DIEGO Was she good enough?
GEORGE Shut up, Diego.
GEORGE They're going to be here any minute.
GEORGE I'm trying to concentrate.
DIEGO I'm very angry with you, George.
DIEGO Very angry.
DIEGO You don't take me to California, but you take your bitch wife?
DIEGO A woman?
DIEGO I understand you love her, but it was you and me who started this.
DIEGO You and me.
GEORGE What do you need my connection for, Diego?
GEORGE What are you going to do with it?
DIEGO What do I do with it?
DIEGO Nothing.
DIEGO It's for peace of mind.
DIEGO It's for the principle.
George doesn't have time for this.
He checks the cylinders on his weapon and runs over possible scenarios in his mind.
But Diego won't get off the soap box.
GEORGE Jesus fucking Christ, Diego.
GEORGE I ain't telling you.
GEORGE It's just business.
GEORGE Now, shut up.
GEORGE You're driving me crazy.
DIEGO I'm driving you crazy?
DIEGO No.
DIEGO You're driving me crazy.
DIEGO We had a dream.
DIEGO What happened to our dream?
A black sedan pulls up and FIVE PUERTO RICAN MEN approach the room.
George and Diego greet them and lead them inside.
It's game time.
The atmosphere is charged with danger and everyone is acutely aware of everything.
The guys sit down, their guns bulging through the inside of their suits.
The suitcases are opened.
The rules are the same.
No English.
No raising voices.
No sudden movements.
George offers their leader, TONY, beers for his men, and is politely declined.
The count starts.
George and Diego riff through ten thousand dollar bundles.
Diego is still acting pissy.
He's mumbling to himself, making faces, slamming the money all around.
The guys keep a close eye on him.
Diego finishes a stack, throws one of the bags on the ground.
The conversation is in Spanish unless otherwise indicated.
TONY Algun problema?
GEORGE No no no...
GEORGE no problema, amigo.
GEORGE El dinero esta todo aqui.
GEORGE Lleves las "llaves" y mas tarde lo contaremos.
GEORGE Okay?
GEORGE No problem.
TONY Que problema?
TONY Nosotros esperamos.
The pressure is getting to one of the hoods.
His name is BENNY.
He's got a crazy eye and he seems ready to snap.
George resumes the count, but Diego won't get off it.
DIEGO You embarrassed me, George.
DIEGO You make me look very bad.
BENNY Que esta diciendo?
GEORGE Nothing.
GEORGE Todo esta bien.
DIEGO Everything is not alright.
DIEGO I bring you in, and you slap my fucking face!
GEORGE This is not the time, Diego.
The men all reach for their pieces and all hell starts to break loose.
TONY Hay algun problema?
TONY Hablame!
DIEGO You fucked me in front of my whole family!
GEORGE Fuck you...I didn't fuck you.
BENNY Maldita sea, que diablos esta diciendo?
GEORGE Esta todo aqui, amigo...take the keys.
GEORGE Take 'em and go.
TONY Que esta pasando aqui, jefe?
DIEGO Sientese ye no se meta en lo que no le importa.
The guns are out and pointed.
It's out of control now.
GEORGE Take it easy!
GEORGE Everything's okay!
DIEGO Que es lo que quieren de me, hijueputas campesinos?
George steps forward with the keys.
GEORGE Take the fucking keys!
BLAM!
Courtesy of Benny, George is hit.
The shoulder, the collarbone.
It's hard to tell.
GEORGE (CONT'D) Estoy bien, okay?
GEORGE (CONT'D) Everything is alright.
GEORGE (CONT'D) There's no problem.
GEORGE (CONT'D) Okay?
GEORGE (CONT'D) This never happened.
GEORGE (CONT'D) No one has to know anything about this.
GEORGE (CONT'D) Diego, I want you to calmly tell them where the fucking coke is.
GEORGE (CONT'D) Do it now.
DIEGO Es un Ford blanco junto a una pick-up.
Tony very carefully takes the car keys.
GEORGE No problem, gentlemen.
GEORGE Goodbye.
The men slowly back out the door.
George looks at Diego.
GEORGE (CONT'D) Derek Foreal.
DIEGO What?
GEORGE Derek Foreal.
GEORGE Derek Foreal.
GEORGE Derek fucking Foreal.
GEORGE Alright?
GEORGE The answer to all your dreams.
GEORGE Are you happy now?
George and Diego exit the terminal.
George's arm is in a sling.
The familiar sight of Derek Foreal is Lincoln Continental.
The three men come together, and Diego and Derek are introduced.
The men's hands come together and the FRAME FREEZES on their handshake.
Fred pulls into the driveway in his new car and honks the horn.
Fred and Ermine get out of the car.
FRED Hello, hello.
It's a New Year's Eve party.
A lavish Colombian celebration.
George and a very pregnant Mirtha move through the crowd to find Augusto.
AUGUSTO I'm so glad you two could make it.
AUGUSTO Mirtha, look at you.
AUGUSTO So beautiful.
AUGUSTO You look like you're about to burst.
MIRTHA Thanks.
MIRTHA I am.
MIRTHA Where's Martha?
AUGUSTO I don't know.
AUGUSTO Drunk somewhere.
AUGUSTO Try the bar.
AUGUSTO And if you find her, tell her to come, it's almost midnight.
As Mirtha leaves, Augusto throws his arm around George's shoulder.
AUGUSTO (CONT'D) It's good you came down, George.
AUGUSTO (CONT'D) We need to discuss a few things.
DIEGO Where's Diego?
AUGUSTO He's not here, George.
GEORGE Yeah, well where is he?
GEORGE And who is this Norman K. guy?
GEORGE That's all anyone is talking about.
GEORGE Norman K. Norman K. Do I know him?
Augusto lets out a big laugh.
AUGUSTO Norman Cay is not a person.
AUGUSTO He is an island, George.
AUGUSTO In the Bahamas.
AUGUSTO From what they say, it is free and it's Diego's new home.
GEORGE What?
Augusto throws an arm around George's shoulder.
AUGUSTO Let us walk.
AUGUSTO From what I understand, Diego has bought a hundred and sixty acres, a marina, a hotel, and an airstrip.
GEORGE Motherfucker works fast.
AUGUSTO The word is that soon he is to be king of the middle empire.
AUGUSTO He is doing multiple runs right now and using the island as a jump-off point.
GEORGE He what?
AUGUSTO Yes.
AUGUSTO Jack Stevens is already a very busy man.
AUGUSTO Along with many others.
AUGUSTO You shouldn't stay away so long.
GEORGE That's impossible.
GEORGE We can't be up and running.
GEORGE Who's distributing?
Augusto says nothing.
But the ball is dropping in Times Square.
10, 9, 8, 7...
GEORGE (CONT'D) Oh, no.
Happy New Year.
Streamers, confetti, and champagne.
George marches through the kissing guests and over to a phone.
He's steaming.
The music is up, so he has to scream.
GEORGE (CONT'D) Hello, Derek?
GEORGE (CONT'D) This is George.
GEORGE (CONT'D) Am I wearing lipstick?
GEORGE (CONT'D) I said, am I wearing lipstick?
GEORGE (CONT'D) Because when I'm getting fucked, I want to make sure my face is pretty.
GEORGE (CONT'D) You're buying directly from Diego, aren't you, you son of a bitch?
Derek Foreal in full New Year's regalia, complete with party hat.
DEREK I don't want to get caught in the middle of this.
DEREK That's between you and Diego.
George's face scrinches in pain.
DEREK (CONT'D) It's nothing personal, George.
DEREK (CONT'D) Just business.
GEORGE Yeah.
GEORGE I understand.
GEORGE Just business.
GEORGE Right.
GEORGE Fuck you.
The song ends, and George is left standing there screaming.
GEORGE (CONT'D) I bring you in, and this is how you repay me?
GEORGE (CONT'D) You little homo!
GEORGE (CONT'D) Hey, Derek?
GEORGE (CONT'D) Derek?
It's late.
The family is all there.
Fifteen, twenty strong.
Cuban coffees all around.
MIRTHA Que va hacer?
AUGUSTO Que queres decir.
AUGUSTO Que es lo que el va hacer?
AUGUSTO Pues, no va hacer nada.
MARIA Alguna cosa tiene que hacer.
FAMILY MEMBER #2 De otra manera, es un marica.
FAMILY MEMBER #3 Un hijueputa
FAMILY MEMBER #1 Maricon.
FAMILY MEMBER #2 Mira, vos sos responsable por el exito de Diego.
FAMILY MEMBER #3 El se esta burlando de vos.
FAMILY MEMBER #3 Debes hacer algo, hombre.
MARIA No Puedes hacer ni un culo.
AUGUSTO El no va hacer nada.
AUGUSTO Hay un problema.
AUGUSTO Aqui, hubo un error y nosotros lo vamos ha arreglar.
BLANCA No le escusches a mi yerno.
BLANCA A el solo le importa la plata.
Blanca reaches into her purse, pulls out an ice pick folded in a piece of linen cloth, and puts it down in front of George.
BLANCA (CONT'D) Vos lo tenes que matar, ahorita mismo.
BLANCA (CONT'D) De lo contrario vas a quedar como un marica sin horror.
FAMILY MEMBER #3 Mejor dicho vos sos un aculillado.
FAMILY MEMBER #1 Maricon.
BLANCA Sabes que, vos no tenes pantalones.
BLANCA Nadie te va a respetar.
BLANCA Usa esto.
BLANCA Deja solo un huequito tan pequeno, que ni sangre le va a salir a ese malparido del Diego.
AUGUSTO Blanca, por favor.
MIRTHA Mama, vos sos bien antigua.
MIRTHA Como lo va a matar con un picahielo.
MIRTHA Eso era en su tiempo, estamos casi ya en los ochenta.
MIRTHA El lo va a meter un tiro, lo va a volar, le va a hechar un hijueputa carro encima.
AUGUSTO Dejen la maricada pues!
AUGUSTO No jodan!
AUGUSTO Nadie va a matar a nadie!
AUGUSTO George, debemos hablarle al Patron, es la unica manera, mano.
GEORGE No, no, no, no yo puedo arregarlo solo.
George cruises through the turqoise water of the Caribbean in a sport fisherman.
Before him is Norman Cay.
White sand beaches.
Beautiful.
Pristine.
Waiting for him is Cesar.
CESAR Good to see you, George.
CESAR It's been a long time.
The Yacht Club is a tavern style bar that juts out over the water.
The crimson sky streaks the windows.
Diego looks like Che Guavera.
His hair is long, and a graying beard sticks through his gaunt face.
The bar has been taken over by Diego's BANDITOS.
Automatic weapons and PROSTITUTES accent this drunken setting.
George is escorted through the door by Cesar, and the room quiets.
All eyes on Diego and George.
Diego rises.
DIEGO George, I am happy to see you.
DIEGO How are you, my brother?
GEORGE No more brothers, Diego.
DIEGO Of course we are brothers.
DIEGO Why do you say that?
DIEGO You hurt me, George.
GEORGE You fucked me, Diego.
DIEGO I did not.
GEORGE You went behind my back and you cut me out.
DIEGO No, I never.
DIEGO I would not do that, George.
DIEGO Never.
GEORGE I talked to Foreal, Diego.
There is a pause.
Diego's goons ready their weapons as Diego scoops up a cringer with his pinky and sniffs.
DIEGO Maybe you are right.
DIEGO I did betray you a little bit.
One of the men says something in Spanish and everyone laughs.
George is furious.
He starts to tremble and his face turns red.
DIEGO (CONT'D) Oh, boo hoo, boo hoo.
DIEGO (CONT'D) So sad, George.
DIEGO (CONT'D) I stole your California connection.
DIEGO (CONT'D) So what?
DIEGO (CONT'D) Who introduced you to Pablo Escobar?
DIEGO (CONT'D) Me.
DIEGO (CONT'D) Who introduced you to your fucking Colombian wife?
DIEGO (CONT'D) Me.
DIEGO (CONT'D) Who protected you when my friend Cesar Roza wanted to slice your fucking throat, huh?
DIEGO (CONT'D) Who mad you millions and millions of dollars?
DIEGO (CONT'D) Me.
DIEGO (CONT'D) And what do I get in return?
DIEGO (CONT'D) This?
DIEGO (CONT'D) Accusations?
DIEGO (CONT'D) I have always given you everything, George, but that is over now.
DIEGO (CONT'D) This is my operation.
DIEGO (CONT'D) My dream.
DIEGO (CONT'D) So go home, George.
DIEGO (CONT'D) Go back to your stupid little life.
DIEGO (CONT'D) You can sell half grams to your fucking relatives for all I care.
DIEGO (CONT'D) Because you are out!
George lunges at Diego and is immediately grabbed.
GEORGE You'd better kill me now, Diego, because you're a dead man.
DIEGO George, don't be so emotional.
DIEGO This is business.
DIEGO Besides, I can't kill you, you are my brother.
They lead him away.
George is getting the shit kicked out of him.
His teeth broken, kicked in the head, the body, the groin.
His arm stomped.
Blood and broken bones.
It's a king size beating.
The men prop him up and Cesar reaches back and hits him with a haymaker.
CRACK.
George's nose is broken.
Blood spurts everywhere.
George is dropped to the ground, spit on, and left for dead.
CESAR Say "hi" to your pretty wife for me.
A beautiful, sprawling estate.
A family barbecue, Colombian style, is in full swing.
Kids play soccer.
Zoo animals run wild together.
George is led outside by TWO OVER-ARMED BODYGUARDS.
Pablo sees him and gives George a big hug.
ESCOBAR George, you look terrible.
GEORGE Yeah, well...
ESCOBAR Diego?
GEORGE Yeah.
ESCOBAR Please.
ESCOBAR Sit down.
ESCOBAR We'll drink some scotch.
GEORGE I didn't come here to drink scotch.
ESCOBAR I see.
ESCOBAR I'm sorry about this, George.
ESCOBAR I'm not happy about this situation.
ESCOBAR It's bad.
ESCOBAR You now know who your Brutus is.
GEORGE You know why I'm here.
GEORGE You know what I have to do.
GEORGE I came here for permission.
GEORGE Out of respect, Pablo.
GEORGE This is bullshit, he's making me look like a punk.
ESCOBAR It is very difficult.
ESCOBAR Diego makes me a lot of money.
ESCOBAR If Diego goes so does the money.
ESCOBAR You were an excellent teacher, George.
ESCOBAR When the student has learned well, the teacher is no longer necessary.
ESCOBAR We must remember we have wives, friends, familia.
ESCOBAR Even familia that has not been born.
ESCOBAR But sometimes, we must forget as well.
ESCOBAR I am like you.
ESCOBAR I must teach the lesson.
ESCOBAR We want to teach the lesson.
ESCOBAR But we cannot.
ESCOBAR We must remember that life is the teacher.
GEORGE You're saying life will take care of Diego?
ESCOBAR Life will take care of everybody.
ESCOBAR Diego, me, you.
ESCOBAR It is the teacher.
GEORGE I get it.
GEORGE I'm really pissed, Pablo.
GEORGE You know the DEA knows about Norman's Cay.
GEORGE For Chrissakes, Diego worships Adolf Hitler and John Lennon, that's fucked up!
ESCOBAR I'm sorry, George.
GEORGE Yeah, well, what are you gonna do?
GEORGE You and me, Pablo?
GEORGE Are we good?
ESCOBAR Of course, George.
ESCOBAR We are beautiful.
ESCOBAR We are brothers.
ESCOBAR Real brothers.
ESCOBAR Not like Diego.
ESCOBAR We started this, George.
Escobar embraces George for a moment, and then George starts to move away.
ESCOBAR (CONT'D) And, George?
ESCOBAR (CONT'D) The vengance?
ESCOBAR (CONT'D) It is best served cold.
Mirtha is sleeping.
She's so big, she looks like she's gonna explode.
George sits on the bed and rests his hand on Mirtha's face.
He looks like the Elephant Man.
MIRTHA George.
MIRTHA Oh, Jesus Christ, George.
MIRTHA Look at you.
GEORGE Shhh, honey, never mind.
GEORGE It's alright.
GEORGE It's over.
GEORGE I quit the business.
GEORGE I'm out.
MIRTHA Pablo said no?
GEORGE Pablo said no.
GEORGE It's all over.
GEORGE And I'm never going back.
GEORGE I have you.
GEORGE We have the baby.
GEORGE And there's nothing else.
GEORGE It's just the family now.
GEORGE Shhh.
GEORGE Sleep now.
Fred, Ermine and Mirth are waiting for George in the car.
Mirtha's water has broken.
Ermine honks the horn from the back seat and screams out the window.
ERMINE George, it's time!
ERMINE George!
ERMINE George!
George is high and in a panic.
He races around, trying to get a suitcase packed and find his keys.
GEORGE Coming!
He finally gets it together, but before he runs out the door, he does one last blast.
Mirtha is on the birthing table and screaming in pain.
She's crowning.
George wears hospital scrubs and a surgical mask.
He and his saucer pupils hold Mirtha's hand in comfort.
The baby comes, and DOCTOR MICK BAY slaps it's behind and cuts the cord.
Tough ass Mirtha breaks down and sobs hysterically.
But something is wrong with George.
The color drains from his face.
He grabs his chest and falls over onto the floor.
The MEDICAL STAFF attends to him.
GEORGE (V.O.) Watching my baby girl born did something to me.
GEORGE (V.O.) They talk about religious experiences, I didn't believe in religion.
GEORGE (V.O.) But when Kristina Sunshine Jung came into this world, something in me changed.
GEORGE (V.O.) I looked at her and I knew right then that I could never love anything but my daughter ever again.
GEORGE (V.O.) It sounds sappy, but it was like, click, I knew what I was put on this planet for.
GEORGE (V.O.) It was the greatest feeling I ever had followed by the worst feeling I ever had.
NURSE He fainted.
MIRTHA George!
The doctor grabs George's wrist.
DR. BAY He's in tachycardia.
DR. BAY George, your heart is racing.
DR. BAY Have you been using drugs?
GEORGE Coke.
DR. BAY Cocaine?
DR. BAY How much?
GEORGE I don't know.
GEORGE Maybe eighteen grams.
DR. BAY In how long?
DR. BAY A week?
GEORGE Today.
DR. BAY Oh, Jesus, Get me a 12-lead e.k.g.
DR. BAY and start an i.v.
DR. BAY stat!
DR. BAY This man is having a heart attack.
George lies in the recovery room, sedated, tubes everywhere.
He's hooked up to IV's, monitors, and machines.
Dr. Bay enters.
DR. BAY I've reviewed your toxicology report three times, George.
DR. BAY I've never seen anything like it.
DR. BAY Eighteen grams.
DR. BAY The lethal dose is a gram and a half.
DR. BAY You should be in the Guiness Book.
George cracks a faint smile.
DR. BAY (CONT'D) It's not funny, George.
DR. BAY (CONT'D) You should be dead right now.
DR. BAY (CONT'D) Absolutely.
DR. BAY (CONT'D) I cannot come up with one logical explanation for why you're still breathing.
DR. BAY (CONT'D) I'm not here to give you lectures, I've got no moral interest in what you do.
DR. BAY (CONT'D) But, take it easy, George.
DR. BAY (CONT'D) Stay with us a while.
DR. BAY (CONT'D) You've got a daughter now.
Kristina is crying.
Daddy George to the rescue.
He picks her up, cuddles her.
Gives her a bottle and she quiets.
A one-year-old Kristina is being coaxed by George to take her first steps.
GEORGE Come on.
GEORGE Come on, honey.
GEORGE You can do it.
GEORGE Come to Daddy.
Kristina tries, stumbles.
Gets up again.
She looks like a drunk, but she's doing it.
GEORGE (CONT'D) Good girl!
Mirtha enters.
She's all pinned out, dressed in Ungaro, Cartier, and dark sunglasses.
GEORGE (CONT'D) Look, Mirtha.
GEORGE (CONT'D) She's walking.
MIRTHA She did that before.
GEORGE No.
GEORGE These are her first steps.
GEORGE Watch her.
MIRTHA Yeah.
MIRTHA I know.
MIRTHA She did that before.
GEORGE But this is...
MIRTHA I said, I've seen it before.
GEORGE Alright.
MIRTHA Can you lift the furnace.
MIRTHA I need money.
GEORGE Where are you going?
MIRTHA Out.
The years go by and they are SUPERIMPOSED as they pass.
George, clean and sober, enjoying family life.
Healthy and happy.
Mr. Mom.
Mirtha looks worse and worse as her habit becomes bigger and bigger.
As George and Kristina grow closer and closer, Mirtha is stepping out on the town.
Blowing money right and left.
Shopping with Mirtha, buying clothes, furs, and diamonds.
As Kristina gets older, WE SEE her birthday parties.
George and Kristina wearing paper hats and eating ice cream.
She's two years old, she's three, four, five, six...
The Eastham house is all done up for a party deluxe.
Fully catered, with bartenders, waiters, music, the works.
And of course the three c's, champagne, caviar and Colombians.
George is laughing with Augusto and Martha Oliveros, but when Derek Foreal appears in the doorway, George excuses himself and walks over.
DEREK Happy Birthday, George.
DEREK Mirtha invited me.
GEORGE Yeah.
GEORGE She told me.
DEREK Look, I'm sorry about everything.
DEREK I feel like an idiot.
DEREK You were right.
DEREK I did fuck you.
DEREK And then Diego fucked me.
DEREK Cut me out, too.
GEORGE I heard.
DEREK I lost sight of everything.
DEREK Forgot who my friends were.
GEORGE It's in the past.
GEORGE I'm out of the business now, so forget about it.
GEORGE No hard feelings.
GEORGE We need to move on.
GEORGE And besides, I'm sorry, too.
DEREK You?
GEORGE For calling you a homo.
DEREK That was out of line.
George throws his arm around Derek's shoulder.
GEORGE Good to see you, Derek.
Mirtha runs in with a giant crystal punch bowl filled with mother of pearl.
She holds it over her head triumphantly.
MIRTHA Now let's fucking party, motherfuckers!
MIRTHA Let's have some fucking fun.
DEREK Jesus, is that Mirtha!?
A very underweight Mirtha nervously runs around the party, shoving coke up everyone's noses.
She is gakked to the gills and out of control.
Her pupils a mile wide.
DEREK (CONT'D) Christ almighty, George.
DEREK (CONT'D) Feed her a cheeseburger or something.
DEREK (CONT'D) What does she weight, eighty pounds?
GEORGE I know.
GEORGE She needs to slow down.
GEORGE She's going to blow an O-ring.
Singing.
The birthday cake is brought in, the candles are blown out and everyone cheers.
Mirtha runs over to her husband, still holding the cocaine.
She's sweaty, her hair matted down on one side.
MIRTHA Happy birthday, baby.
MIRTHA Do a line.
She tries to push a line up his nose.
GEORGE No, that's alright.
MIRTHA Oh fucking relax.
MIRTHA Let your hair down for once.
MIRTHA It's your fucking birthday, for Chrissakes.
MIRTHA You're such a fucking pussy.
MIRTHA I swear to G-d, I married this big time drug dealer and wound up with the maid.
Mirtha's loud now and making a scene.
He thinks about it.
GEORGE No honey, I'm alright.
AUGUSTO A toast!
AUGUSTO To Mister George Jung.
AUGUSTO Mr. I 95, north and south.
AUGUSTO My brother-in-law.
AUGUSTO Happy birthday!
Everyone raises their glasses.
EVERYONE To George!
A party guest comes running inside.
PARTY GUEST Cops!
PARTY GUEST They're all over the place.
The WAITERS, in their white jackets, exchange knowing looks.
The BARTENDER comes out from behind the bar.
BARTENDER Freeze!
In an instant, all of the waiters' guns are out.
WAITER Massachusetts State Police Department!
WAITER Everybody on the floor!
Police cars everywhere.
All the party guests are filed out the door, and are being led away.
Mirtha is dragged out, spitting and screaming.
George, in handcuffs, is pushed to a squad car.
He looks through the window to see a FEMALE POLICE OFFICER escorting Kristina out of the house.
George, still dressed in his party clothes, sits at a desk.
TWO DETECTIVES set a confession in front of him.
GEORGE What's this?
DETECTIVE #2 It's your statement.
DETECTIVE #2 How it was all yours, the pound of coke was for personal use and none of the guests had any idea it was there, yeah, right.
George looks through the papers.
GEORGE I want my kid out of protective custody.
GEORGE Now.
GEORGE No fucking around.
GEORGE My wife and my kid on a plane tonight.
GEORGE I sign when they call me safe and sound.
DETECTIVE #1 No fucking way.
GEORGE Fuck you, then.
GEORGE I sign nothing.
The detectives ponder.
DETECTIVE #2 Do it.
Detective #1 walks to the door.
DETECTIVE #1 George?
DETECTIVE #1 You better get yourself a good lawyer this time.
DETECTIVE #1 We're gonna nail your ass to the wall on this one.
GEORGE Oh hey, one more thing?
DETECTIVE #1 What's that?
GEORGE Get me a six pack.
It's the middle of the night.
George walks through a dark and lonely house.
He goes to the furnace, opens it up and sees that there are only five stacks left.
GEORGE Fuck.
George pulls up to the front.
GEORGE Hi.
FRED I heard.
FRED Ermine, your son is here.
ERMINE Tell him I don't want to see him.
ERMINE Tell him he's not welcome here.
GEORGE Mom.
Ermine's back is to George.
She won't look at him.
ERMINE Don't you dare step one foot in this house.
ERMINE You're not my son, you hear me?
ERMINE I don't have a son anymore.
She disappears into the house.
The sound of a door slamming.
FRED She's angry.
FRED It's all over the news.
GEORGE Yeah.
GEORGE Listen.
GEORGE I'm going to be going away for awhile.
FRED You're not going to trial?
GEORGE No.
FRED Good.
They stand there and look at each other for a while.
There's a lot to say but nothing's coming out.
George hands Fred a gym bag.
GEORGE Give this to Mom, will you?
FRED Money.
FRED You and your mother.
FRED All the time chasing it.
FRED I never understood it.
GEORGE Give it to her, Dad.
GEORGE It'll make her happy.
FRED Yeah, I know.
FRED This is it, isn't it?
The two men throw their arms around each other and hold on to one another in the doorway of the old house.
GEORGE Tell Mom, you know...
FRED I'll tell her.
George breaks away and moves to the T-bird.
FRED (CONT'D) Take care of yourself.
George walks through the bank.
George sits at a desk in front of a Panamanian BANK EMPLOYEE.
He slides his bank book across the table.
GEORGE I'd like to make a withdrawal.
The employee opens the book and gets a funny look on his face.
Nervous.
BANK EMPLOYEE Excuse me, please.
He gets up and moves to the BANK MANAGER.
They move to another MANAGER TYPE.
And another.
And then everyone disappears behind closed doors.
Finally, the BANK PRESIDENT emerges and moves over to George.
BANK PRESIDENT I'm afraid there is a problem, Mr. Jung.
BANK PRESIDENT The banks have gone through a change, a nationalization.
BANK PRESIDENT I'm afraid your funds have been appropriated by the Panamanian Government...
George starts to shake.
The bank president tries to explain, but whatever he says is unimportant.
George is paralyzed.
An inexpensive one-bedroom furnished apartment.
It ain't much, but it's home.
Mirtha has just received the news and is losing her mind.
Clara Blanca is cooking dinner.
MIRTHA What are we going to do?!
MIRTHA What are we going to use for money?!
GEORGE Please, Mirtha.
GEORGE I'll start working for Augusto.
GEORGE I'll talk to him tonight.
GEORGE I'll do something.
MIRTHA Don't touch me.
MIRTHA Tell me.
MIRTHA Just answer the question.
MIRTHA What do I spend?
MIRTHA What?
MIRTHA How will we live?
Kristina sits there.
She hears everything, so does Clara Blanca.
GEORGE Not in front of the kid.
MIRTHA Don't give me that shit.
MIRTHA You just better do something.
She storms into the bedroom and slams the door.
George stands there.
Awkward silence.
George goes to Kristina.
GEORGE Everything's gonna be okay, sweetheart.
GEORGE Don't be upset.
KRISTINA What's happening to us?
Tough question to answer.
GEORGE I don't know.
KRISTINA Are we gonna split up?
GEORGE No, never.
GEORGE Don't even think about that, it's impossible.
GEORGE I love your mother.
GEORGE And you are my heart.
GEORGE Could I live without my heart?
GEORGE Could I?
Kristina nods "no."
They embrace.
The car moves along I-95.
George is driving while a jacked up Mirtha does a speed bump.
A cop is following in the distance.
It is not okay.
GEORGE There's a fucking cop behind us, Mirtha.
GEORGE Be cool, will ya.
MIRTHA Fuck you, George, just fucking drive.
GEORGE Hey, why don't you just put a "I'm doing cocaine" sign on the car.
GEORGE What is your fucking problem?
MIRTHA My problem?
MIRTHA We're broke, that's my fucking problem.
MIRTHA And you're a fucking spy.
GEORGE What?
MIRTHA That's right.
MIRTHA Always spying, always judging.
MIRTHA Everyone's laughing at you, you fucking pussy.
MIRTHA You let Diego fuck you in the ass.
MIRTHA Maybe you are a fucking faggot.
MIRTHA You must be fucking Diego because you're not fucking me.
Mirtha grabs nuts.
GEORGE Those are my nuts!
George tries to fend her off.
The car swerves all over the road.
It's turned into a full scale fist fight.
The red lights of Florida's finest come up behind them and George is pulled over.
Mirtha leaps out of the car, teary eyed, crazed and bloodied.
The policemen step from their car.
MIRTHA He's a fugitive and a fucking cocaine dealer!
MIRTHA There's a kilo in his trunk right now!
MIRTHA Take this sorry motherfucker to jail!
George sits behind the wheel.
He knows it's over.
Visiting day.
Inmates sit across from their families.
Mirtha is sitting at the glass.
George walks to his seat.
MIRTHA I'm divorcing you, George.
MIRTHA I'm getting custody of Kristina.
MIRTHA And when you get out next week, you're going to pay support and that's the end of it.
MIRTHA Alright?
MIRTHA There's someone else.
MIRTHA I'm sorry.
George just looks at her.
His face is stone.
But he is moved.
MIRTHA (CONT'D) You should have taken better care of me, you know?
MIRTHA (CONT'D) You've been away a long time.
MIRTHA (CONT'D) Four years.
MIRTHA (CONT'D) Say something.
GEORGE What do you want me to say?
GEORGE I'm in prison.
GEORGE You should know.
GEORGE You put me here.
MIRTHA Fuck you, George.
MIRTHA I knew you'd say something like that.
MIRTHA Always thinking about yourself.
She moves away and drags nine-year old Kristina into the room.
Kristina yanks her arm away and they get into a heated argument.
Through the glass, George can't hear the words but it's clear that Kristina doesn't want to be here.
GEORGE My baby.
GEORGE She's so big.
Mirtha forces Kristina over to the glass and keeps showing her, prompting her to talk.
Kristina stares at George through the glass.
Cool.
Defiant.
Angry.
She picks up the phone and speaks, every word an accusation.
KRISTINA I thought you couldn't live without your heart.
She drops the phone, walks away, and doesn't look back.
George puts in the quarters.
GEORGE Hello, Derek?
GEORGE It's George.
GEORGE Yeah.
GEORGE Yeah, I am.
GEORGE I'm in Miami.
GEORGE I'm looking to do something.
GEORGE I want to put together a crew.
GEORGE Do you know anybody?
GEORGE Leon?
GEORGE I don't know him.
GEORGE What's his last name?
GEORGE Alright.
GEORGE Give me the number.
Nine-year old Kristina Jung leaves school.
George, fresh out of prison, moves across the street to meet her.
KRISTINA What are you doing here?
GEORGE Nothing.
GEORGE I just wanted you to know I was out.
GEORGE I just wanted to see you.
KRISTINA Well, here I am.
KRISTINA See?
GEORGE How are you doing?
KRISTINA George, you just can't show up, tell me you love me, and have everything be okay.
GEORGE Dad.
KRISTINA What?
GEORGE You can call me Dad if you want.
KRISTINA I don't want, alright?
KRISTINA It's not funny.
KRISTINA I'm really pissed off, George.
KRISTINA You blew it, now leave me alone.
GEORGE Kristina, c'mon, I'm sorry.
GEORGE I'm going to make this right.
GEORGE I've got a few things going on...
KRISTINA What do you want from me?
GEORGE Just to walk with you.
GEORGE I want to be your dad again.
KRISTINA Do what you want, it's a free country.
She walks away.
He follows.
George sits at the bar with a man named LEON MINGHELLA.
LEON It's a four-man operation.
LEON Two on the ground.
LEON Two in the air.
GEORGE Who's the co-pilot?
LEON You're looking at him.
LEON We provide the plane, transportation cost, U.S. landing spot, and take it to wherever you want it to go.
LEON You provide the pick up point in South America, and are responsible for payment.
LEON You assume all the bust risks.
LEON We take sixty-five percent of all transportation fees, ten percent of the gross, plus our expenses.
LEON This is not a negotiation, so if this is okay with you, we can talk further.
LEON If not, we can forget we had this conversation.
GEORGE Sounds fine.
GEORGE I'll need to meet everybody.
LEON They're over at the booth.
Leon leads George over.
LEON (CONT'D) Gentlemen, this is George.
LEON (CONT'D) George, this is Ben, G.G. and...
George's eyes widen as he looks at the last man.
It's Kevin Dulli.
GEORGE Holy shit, Dulli!
KEVIN Georgie, oh man, hold the mayo!
GEORGE (V.O.) That was it.
GEORGE (V.O.) Seeing Dulli after fourteen years sealed the deal for me.
GEORGE (V.O.) The rest was just details.
GEORGE (V.O.) My end was roughly five-hundred thousand.
GEORGE (V.O.) Kristina and I could have a good life for five hundred grand.
GEORGE (V.O.) Start over somewhere.
GEORGE (V.O.) One final score.
GEORGE (V.O.) That's all I needed.
AUGUSTO Three-hundred kilos is a very big load, Georgie.
AUGUSTO Why don't we start small?
GEORGE No.
GEORGE I have the space.
GEORGE I figured it out.
GEORGE This is what I want to do.
AUGUSTO Alright.
AUGUSTO I'll ask Pablo, tell him it's for you.
AUGUSTO I don't think there will be a problem.
GEORGE Five-thousand per kilo.
AUGUSTO Ha ha.
AUGUSTO That's too much, Georgie.
AUGUSTO Those days are over.
AUGUSTO The rate is one-thousand dollars.
AUGUSTO Inflation, you know?
GEORGE This is a one time thing, Gusto.
GEORGE One and I'm out.
GEORGE Give me a good price for old time's sake.
GEORGE What do you think?
George and Kristina walk through the neighborhood.
He carries her books.
GEORGE Let me ask you something.
GEORGE If you could go anywhere in the world, anywhere, where would you want to go?
KRISTINA You mean, like a trip?
GEORGE Yeah, sure, whatever.
Kristina thinks about it.
KRISTINA I don't know.
KRISTINA Maybe California.
George is amused by her answer.
GEORGE California?
GEORGE You can go anywhere in the world.
GEORGE India.
GEORGE Tibet.
GEORGE Australia.
GEORGE Paris.
GEORGE And you choose California?
KRISTINA Yeah.
GEORGE What is it?
GEORGE A Disneyland thing?
KRISTINA No.
KRISTINA I just kind of like the sound of it.
GEORGE California, huh?
KRISTINA California.
They turn a corner and arrive at Kristina's house.
Mirtha is standing in the doorway.
GEORGE Go on inside now.
GEORGE I want to talk to your mom alone.
He kisses his daughter goodbye.
KRISTINA Bye, Dad.
KRISTINA See you in the morning, okay?
GEORGE I'll be here.
George moves over to Mirtha.
It's been a while.
MIRTHA What do you want?
GEORGE You knew I was seeing Kristina, right?
MIRTHA Yeah.
MIRTHA She told me.
MIRTHA You walk her to school.
GEORGE Yeah, so I've been thinking.
GEORGE I love her, y'know?
GEORGE I kind of want to have her.
GEORGE I've been away for so long.
GEORGE Make up for the missed time, you know?
MIRTHA I haven't seen one dollar from you.
MIRTHA You haven't paid me one cent in child support, alimony.
GEORGE Yeah, well.
GEORGE I'm working on that.
GEORGE I've got something going.
MIRTHA Yeah?
MIRTHA I better see some money out of it.
GEORGE Yeah, you will.
GEORGE Of course.
Mirtha looks at her ex-husband.
It's not all bad.
MIRTHA Hey, look.
MIRTHA You start paying, who knows what will happen.
MIRTHA You're a good father, George.
MIRTHA I always gave you that.
MIRTHA But you've got to talk to her.
GEORGE Yeah.
MIRTHA She's getting big.
MIRTHA Getting her own ideas.
GEORGE I know.
GEORGE Well, that's all I really wanted to say.
GEORGE So, okay, then.
He moves down the steps and heads for the sidewalk.
MIRTHA Hey, George.
MIRTHA You okay?
GEORGE Yeah.
GEORGE I'm fine.
GEORGE I'm good.
The restaurant is filled with the team.
They discuss, argue, re-examine every little detail.
KEVIN We take off from Lauderdale, Sunday, refuel, and be in Medellin by Monday.
LEON Overnight, refuel, and back Wednesday night.
GEORGE Where are you coming in?
BEN Vero Beach.
G.G. It's good.
G.G. It's small.
LEON Then we drive it to the Lauderdale house where it stays until pick up and payment the next morning.
LEON You want to go over it again?
GEORGE No.
GEORGE All set.
GEORGE Piece of cake.
George is cooking dinner for Kristina.
He's only got a hot plate so it's slow.
The table is set with plasticware.
Kristina chops the salad.
GEORGE I'm thinking about getting out of town this week.
GEORGE You want to come with me?
KRISTINA Where are you going?
GEORGE I don't know.
GEORGE Maybe California.
KRISTINA You swear?
GEORGE Yeah.
GEORGE Go out there, check it out, see what it's like.
GEORGE I've got some stuff to do this week, but I'm thinking maybe Thursday.
GEORGE Thursday after school.
KRISTINA You know I can't.
KRISTINA Mom will never let me go.
GEORGE You let me take care of your mother.
GEORGE You just pack your bags.
KRISTINA But I've got school.
GEORGE There's schools in California.
KRISTINA You swear?
GEORGE That's right.
GEORGE Three o'clock.
GEORGE Thursday.
GEORGE At your mother's.
GEORGE You and me.
GEORGE It's a date.
KRISTINA I don't believe you.
GEORGE I swear.
GEORGE On my life.
KRISTINA Swear on my life.
GEORGE I swear on your life.
George, Ben and G.G. wait on the tarmac.
George is pacing.
The sound of a Cessna is heard and soon it is dropping out of the sky.
The plane lands and taxis over.
Kevin and Leon stick their fists out of the airplane in triumph.
The men quickly unload the plane into the trunks of two Broncos and the back of a truck.
WE FOLLOW the duffel bags out of the Bronco into the house.
The boys sit around as George samples the product.
KEVIN Are we good?
GEORGE Are we good?
GEORGE Yeah, we're good.
GEORGE We're beautiful.
GEORGE We're perfect.
GEORGE This is A grade, one-hundred percent pure Colombian cocaine, Ladies and Gentlemen.
GEORGE Disco shit.
GEORGE Pure as the driven snow.
GEORGE Good riddance.
He looks the boys over.
GEORGE (CONT'D) You saved my life, Dulli.
GEORGE (CONT'D) You'll never fucking know.
GEORGE (CONT'D) All you guys.
GEORGE (CONT'D) Everyone just got a raise.
GEORGE (CONT'D) Instead of ten percent, you get fifteen.
LEON Jesus, George, fifteen percent.
LEON That's an extra two-hundred large.
GEORGE I don't give a shit.
GEORGE Split it up.
GEORGE Have a great life.
GEORGE I'm done.
GEORGE I'm out.
GEORGE Starting over.
GEORGE Cheers.
They clank.
George gets up and does the Snoopy Dance to the bathroom.
GEORGE (CONT'D) Yeah!
GEORGE (CONT'D) Unbelievable.
GEORGE (CONT'D) Dulli, pour us another round.
GEORGE (CONT'D) I gotta hit the head.
George leaves the room.
The camera slowly pans back to the guys.
Something doesn't look right.
They have not moved.
They look bummed.
Leon looks at G.G.
LEON What?
G.G. I feel bad.
BEN Me too.
BEN He's not such a bad guy.
KEVIN Fuck you guys.
KEVIN All of you.
KEVIN I've known him for thirty fucking years.
KEVIN Fucking George.
LEON Yeah, I like him, too.
LEON But what's done is done.
LEON So let's not get all sentimental about it, okay?
The CAMERA PANS BACK SLOWLY to the bathroom door, George comes back into the room, dancing.
He goes and sits down with the guys.
GEORGE Dulli, I was just thinking about that time we landed in Mexico.
GEORGE You've gotten a lot better since then, huh pal?
GEORGE Remember that fucking landing strip?
GEORGE Huh?
George is the only one smiling.
No one is looking at him.
GEORGE (CONT'D) Hey, what's wrong fellas?
GEORGE (CONT'D) Why the long faces?
He looks at each one.
He slowly realizes something's up.
He looks to Dulli finally.
GEORGE (CONT'D) No.
GEORGE (CONT'D) C'mon, Dulli.
The front door busts down, agents pour in.
The CAMERA SWISH PANS to George.
Lights out.
Slow motion.
Slow dolly into
George has tears in his eyes.
He is frozen.
Paralyzed by the memories.
GEORGE Oh, no.
The voices from the bust can be heard as the CAMERA PUSHES SLOWLY into George's face.
Surreal.
GEORGE (V.O.) I was busted.
GEORGE (V.O.) Set up by the FBI and the DEA.
GEORGE (V.O.) That didn't bother me.
GEORGE (V.O.) Set up by Kevin Dulli and Derek Foreal to save their own asses.
GEORGE (V.O.) That didn't bother me.
GEORGE (V.O.) Sentenced to sixty years at Otisville.
GEORGE (V.O.) That didn't bother me.
Nine-year old Kristina Sunshine Jung sits on the front porch as the sun goes down.
Her bags are packed and ready to go.
GEORGE (V.O.) I had broken a promise.
GEORGE (V.O.) Everything I loved in my life goes away.
George is led into a small room and greeted by his lawyer,
ZIGMOND Here's the deal, George.
ZIGMOND You're not getting out.
ZIGMOND I tried to get you furloughed, but your mother squashed it.
ZIGMOND Said it would only upset him.
ZIGMOND I'm sorry.
George takes it in.
Blinks.
The years have not been kind.
GEORGE How's he doing?
ZIGMOND Well, he's out of the hospital, but there's not much anyone can do for him.
ZIGMOND It's just a matter of time.
ZIGMOND Listen, I brought a tape recorder in case you wanted to say something to him.
ZIGMOND That way he could hear your voice.
GEORGE Right.
Zigmond sets the tape recorder down and leaves the room.
George stares long at the machine.
He pushes the record button and looks at the red light.
GEORGE (CONT'D) Hello, Dad...
A sixty-nine year old Fred shuffles from his house to the blue LTD.
He gets in, turns the key, and puts his son's tape into the deck.
GEORGE (V.O.) You know, I remember a lifetime ago, I was about three-and-a-half feet tall, weighing all of sixty-pounds, every inch your son...
Six-year old George runs through the leaves to the truck and rides to work with his father.
GEORGE (V.O.) ...those Saturday mornings going to work with my Dad.
GEORGE (V.O.) We'd climb into that big yellow truck.
GEORGE (V.O.) I used to think it was the biggest truck in the world.
CLOSE ON FRED visibly moved.
GEORGE (V.O.) I remember how important the job we did was.
GEORGE (V.O.) How if it weren't for us, people would freeze to death.
GEORGE (V.O.) I thought you were the strongest man in the world.
Ermine as Loretta Young.
Fred Jung and his son tossing a baseball.
Tuna and George driving off in the black Oldsmobile convertible.
The FBI arresting George in his old bedroom.
GEORGE (V.O.) (CONT'D) Remember those home movies when Mom would dress up like Loretta Young?
GEORGE (V.O.) (CONT'D) And the ice creams and the football games?
GEORGE (V.O.) (CONT'D) Waino, the Tuna, and the day I left for California only to come home with the FBI chasing me?
James J. Trout pulls a handcuffed George's boots over his socks as Fred and Ermine watch.
GEORGE (V.O.) And that FBI agent, Trout?
GEORGE (V.O.) When he had to get on his knees to put my boots on?
GEORGE (V.O.) You said...
FRED That's where you belong...
A choked up Fred repeats the words.
FRED ...you sonofabitch.
FRED Putting on George's boots.
GEORGE (V.O.) That was a good one, Dad.
GEORGE (V.O.) That was really something.
GEORGE (V.O.) Remember that?
George's eyes well up and he sparks a cigarette, as he keeps trying to tell his father goodbye.
GEORGE (V.O.) And that time you told me that money wasn't real?
GEORGE (V.O.) Well, old man, I'm forty two years old.
GEORGE (V.O.) I finally learned what you tried to tell me so many years ago.
Tears come crashing out of the old man's stoic face.
GEORGE (V.O.) I finally understand.
GEORGE (V.O.) You're the best, Dad.
GEORGE (V.O.) I just wish I could have done more for you.
GEORGE (V.O.) I wish we had more time.
A vision of Fred Jung sits on the ground before his fifty-two year old son.
GEORGE I guess I kind of lost sight of things.
GEORGE "May the wind always be at your back and the sun always upon your face, and the winds of destiny carry you aloft to dance with the stars."
GEORGE Love, George.
FRED That was a beautiful message.
GEORGE I meant every word of it.
FRED Did you know I died two weeks after you sent me that tape?
The apparition of Fred disappears and George is left alone once again.
GEORGE Yeah, Dad.
GEORGE I knew that.
George is led into the room where THREE FBI MEN await him.
One of them is named FRED GARCIA.
GARCIA How are you doing, George?
GEORGE What do you guys want?
GARCIA You hear about your old friend, Diego?
GEORGE What about him?
Garcia tosses a newspaper onto the table.
The Miami Herald.
Inside is a full page letter addressed from Diego Delgado to Vice President George Bush.
In the letter, Diego offers to make a deal.
In exchange for immunity, Diego will rat out the entire cocaine business.
Americans, Colombians, Noriega, Escobar, everybody.
Just let him free.
GEORGE (CONT'D) What the fuck?
GEORGE (CONT'D) Is he going to walk?
GARCIA He's going down, George.
GARCIA It's election year.
GARCIA We're not making any deals.
FBI GUY #1 He's never getting out.
FBI GUY #1 Orders from the top.
GARCIA So, how would you like to help us put him away?
FBI GUY #2 We've done our homework.
FBI GUY #2 We know you hate this motherfucker.
GEORGE I don't think so.
GARCIA Don't be stupid, George.
GARCIA We've got him.
GARCIA We've got him dead to rights.
GARCIA But like I said, this is top priority so we're handing out free passes on this one.
GARCIA And the first one's got your name on it.
GARCIA Cut your sentence in half, maybe more.
GEORGE No thanks, fellas.
GEORGE You've got the wrong fucking guy.
GEORGE I'm not a rat.
George sits in the chair behind the plexiglass.
Mirtha enters and takes a seat on the other side.
GEORGE Mirtha, what's going on?
GEORGE Everything okay with Kristina?
MIRTHA Kristina's fine.
GEORGE Is she here?
GEORGE Is she coming?
MIRTHA Is she here?
MIRTHA George, Kristina hates you.
MIRTHA You fucked her over one too many times.
MIRTHA And I'm not here to socialize.
MIRTHA Did you hear about Diego?
GEORGE Yeah.
MIRTHA Well, I got a call from Pablo.
MIRTHA He said this thing with Diego is a disaster.
MIRTHA He's giving up lab locations, names, bank accounts, he was very pissed off.
MIRTHA Pablo said to take him down.
MIRTHA His exact words were "Fuck Diego."
GEORGE He wants me to testify?
GEORGE Is that what he's asking me to do?
MIRTHA George, he wasn't asking.
Mirtha gets up and starts to move away.
GEORGE Mirtha, how are you doing?
MIRTHA Better than you.
George, Archie Zigmond and two armed guards walk down the corridor.
GEORGE Hey, Arch, you think the judge will let us get a cocktail after this is all over?
ZIGMOND I'll see what I can do, George.
GEORGE Thanks, Arch.
They walk into the crowded courtroom.
Packed.
Nuts.
Standing room only.
The courtroom buzzes as George is led down the center aisle and is handed off to the bailiff.
Over this we hear...
CLERK Sir, please state your name.
GEORGE I'm George Jung.
GEORGE Spelled J-U-N-G.
CLERK Thank you.
PROSECUTOR Mr. Jung, do you know Diego Delgado?
GEORGE Yes, I do.
PROSECUTOR Do you see him here in the courtroom?
GEORGE Yes, he's sitting right there at the end of the table.
PROSECUTOR Let the record state the witness has identified, Diego Delgado.
The following sound bytes are dissolved together in montage style...
PROSECUTOR (CONT'D) Mr. Jung, can you describe the circumstances of how you began talking about cocaine with Mr. Delgado?
GEORGE Shortly after I arrived at Danbury Federal Correctional Institute I related to Diego that the crime I was in for was smuggling marijuana.
GEORGE Diego told me he had high level connections in Colombia and they needed to find someone to help them transport cocaine into America...
GEORGE (CONT'D) The first run was fifteen kilos, which we smuggled into Logan Airport in hard shelled suitcases.
GEORGE (CONT'D) We wrapped the cocaine in kitchen cabinet paper, and duct tape, that way if there were any dogs in customs...
GEORGE (CONT'D) I introduced Diego to a pilot named Jack Stevens, who helped us fly 300 kilos of cocaine per week into the United States via twin-engine Cessnas.
GEORGE (CONT'D) Jack would fly into North Carolina, we'd meet him there and drive it down to different distribution points...
GEORGE (CONT'D) I never met Pablo Escobar.
GEORGE (CONT'D) Diego Delgado was my only connection to cocaine from Colombia...
GEORGE (CONT'D) Diego convinced me to keep most of my money in a Panamanian bank.
GEORGE (CONT'D) Diego had a close relationship with Manuel Noriega.
GEORGE (CONT'D) In exchange for allowing us to keep our money there, we paid him a percentage.
GEORGE (CONT'D) There was an 85% chance that if you snorted cocaine between 1977-1984, it was ours.
GEORGE (CONT'D) Initially with my LA connections, we invented the marketplace.
GEORGE (CONT'D) In 1977, there was no other real competition.
GEORGE (CONT'D) The first year we made about 100 million dollars between us.
GEORGE (CONT'D) It was an expensive operation.
GEORGE (CONT'D) Eventually we built up to three different pilots doing multiple runs per week, connections on both coasts, everything was running smooth.
GEORGE (CONT'D) We were like a corporation...
GEORGE (CONT'D) he was very anti-government.
GEORGE (CONT'D) He talked about revolution, forming his own country or island, he was looking for power as well as money.
GEORGE (CONT'D) I was just looking for money.
GEORGE (CONT'D) He disliked the United States, thought it was a police state.
GEORGE (CONT'D) He hoped that by flooding the country with cocaine, it would disrupt the political system and tear down the morality of the country.
GEORGE (CONT'D) Well, yes, Derek Foreal was my connection, I met him back in 1968 when I first moved to Manhattan Beach.
GEORGE (CONT'D) It was Foreal's marijuana connections that kicked off our cocaine market.
GEORGE (CONT'D) Yes, it was my idea to bring the kilos to Los Angeles.
GEORGE (CONT'D) When Diego finally got Derek Foreal's name from me, it was only a matter of months before he'd cut me out.
GEORGE (CONT'D) I'm not sure how my relationship with my daughter and ex-wife have anything to do with this trial.
GEORGE (CONT'D) I mean we're here to talk about Diego Delgado, aren't we?
CALIBANOS Yes, we are Mr. Jung.
We come out of the montage, the defense attorney Diego Delgado, Joe Calibanos, a sleazy-Greek-like-ex-basketball weight lifter guy is now doing the questioning.
CALIBANOS (CONT'D) Mr. Jung, you're a convicted felon, correct?
GEORGE Yes, I am.
CALIBANOS Do you have any agreement or understanding whatsoever with the United States government in regards to your testimony?
GEORGE No, I cam here out of my own volition.
CALIBANOS Excuse me?
GEORGE Something about vengance being best served cold.
CALIBANOS Really.
CALIBANOS Are you getting paid, Mr. Jung?
GEORGE Excuse me?
CALIBANOS Mr. Jung, don't you have an agreement or understanding with the United States Government in connection with your testimony in this case?
GEORGE I'm doing sixty years at Otisville, no chance of parole.
GEORGE Even if they cut my sentence in half I'll be seventy-three years old.
GEORGE That's some fucking deal.
GEORGE I don't know if the parole board, the judge, the pope or Jesus Christ himself can get me out of here.
GEORGE I have a really bad record, I'm not sure what's going to happen.
CALIBANOS So you do have an agreement with the United States Government, Mr. Jung, correct?
George can't respond.
Looks to Diego.
Looks from the jury, the judge, George is on the spotlight and it's uncomfortable.
He feels suddenly sleazy.
CALIBANOS (CONT'D) I thought so.
CALIBANOS (CONT'D) No more questions.
Silence.
The judge tells George he can step down.
Calibanos laughs quietly with associates.
George is bummed.
He walks by Diego.
They look at each other.
GEORGE You shouldn't have taken the 30 million, Diego, I was out.
George is lead away.
CLERK The court calls Mr. Jack Stevens.
Jack Stevens is lead to the stand.
WE SLOWLY DISSOLVE TO:
The green of the New York State countryside drifts by as a brown Mazda moves along Highway 19.
Behind the wheel is a beautiful 20 year old woman wearing dark sunglasses.
She drives absently, her mind somewhere else.
The woman is buzzed through the double doors.
She moves to the MAN behind the desk and takes off her sunglasses.
KRISTINA I'm here to see my father.
ADMISSIONS OFFICER Name?
KRISTINA Kristina Sunshine Jung.
The GUARDS are rounding up the other prisoners and escorting them inside, but George is still planting sunflowers.
GUARD Hey, George, five more minutes, buddy.
The admissions officer looks up from his paperwork.
ADMISSIONS OFFICER Jung.
Kristina grabs her papers and moves to the counter.
ADMISSIONS OFFICER (CONT'D) Belongings in here.
Kristina empties her pockets and deposits her possessions into a locker box.
She is handed a key.
ADMISSIONS OFFICER (CONT'D) Feet on the blue line.
Kristina stands on a blue piece of tape and the admissions officer buzzes open the giant metal door.
But Kristina doesn't move.
ADMISSIONS OFFICER (CONT'D) Miss?
He presses the buzzer again, but she just stands there.
ADMISSIONS OFFICER (CONT'D) Miss?
ADMISSIONS OFFICER (CONT'D) Something wrong?
George turns around as a GUARD taps him on the shoulder.
GUARD George?
GUARD George, come on.
GUARD You've got a visitor.
George looks up to find Kristina being buzzed through the gate.
She moves through the open area and onto the grass quickly.
SLOW MOTION: Father and daughter come together at last in a long embrace.
GEORGE I'm sorry, baby.
GEORGE I'm so sorry.
KRISTINA It's alright, Dad.
GEORGE I didn't mean to...
KRISTINA I know, Dad.
KRISTINA I know...
He hugs her hard.
GEORGE I fucked up.
KRISTINA Shhhh.
GEORGE I love you.
GEORGE I love you so much.
GEORGE You've got to know that.
GEORGE You've got to know.
KRISTINA I know, Dad.
KRISTINA I love you too.
GEORGE After everything.
GEORGE After everything, the only thing left out of my whole life is you.
Kristina looks at her father, smiles, and disappears.
There was no Kristina.
The guard continues to tap.
GUARD George?
GUARD George, come on.
GUARD It's getting dark.
George looks up to find a prison guard.
His name is GUS, and he helps George to his feet.
GEORGE But I have a visitor.
GUS Not today, George.
GUS Time to go back.
GEORGE But I want to put her name on the list for tomorrow.
GEORGE My daughter.
GUS Okay, George.
GEORGE Because she's visiting me.
GUS We'll do that tomorrow, okay?
GUS It's lockdown time.
The shadows grow long, and Gus leads George down a cement path that cuts through the grass.
The huge structure of Otisville looms dark against the sky, and Gus and George take the long walk back.
Standing outside the fences, Kristina smokes a cigarette as she watches her father being led away.
After a few moments, she turns around, walks to her car and gets in.
Time to go home.
And as the brown Mazda pulls out of the driveway, the taillights turn red, growing smaller and smaller, until they finally disappear.
</pre> </pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
