A gray, impenetrable wall of fog.
From somewhere comes the FAINT SOUND of a LITTLE GIRL'S VOICE, singing, slow tempo, almost under her breath.
YOUNG ELIZABETH Yo, ho, yo, ho, a pirate's life for me Yo, ho, yo, ho, it's a pirate's life for me...
Suddenly a massive SHIP emerges from the grey, the Winged Victory maidenhead looming.
It's a British dreadnought, the H.M.S. Dauntless.
Formidable, frightening, twenty-five gun ports on a side, and rail guns to boot.
ELIZABETH SWANN, strawberry blond hair, stands at the bow railing, gazing at the seas, still singing --
ELIZABETH ...drink up me hearties, yo, ho...
JOSHAMEE GIBBS, who was born old, skin a dark leather, clutches her shoulder, startling her.
GIBBS Quiet, missy!
GIBBS Cursed pirates sail these waters.
GIBBS You want to call 'em down on us?
Elizabeth stares wide-eyed at him.
NORRINGTON Mr. Gibbs.
NORRINGTON, a dashing young man, Royal Navy to the core, glares sternly at Gibbs.
Standing besides him is GOVERNOR WEATHERBY SWAN, a man of obvious high station, brass buttons on his thick blue jacket.
He is Elizabeth's father.
NORRINGTON (CONT'D) That will do.
GIBBS She was singing about pirates.
GIBBS Bad luck to sing about pirates, with us mired in this unnatural fog-- mark my words.
NORRINGTON Consider them marked.
NORRINGTON On your way.
GIBBS 'Aye, Captain.
GIBBS Bad luck to have a woman on board, too.
GIBBS Even a mini'ture one.
He returns to his deck-swabbing duties, surreptitiously takes a quick swig from flask.
ELIZABETH I think it would be rather exciting to meet a pirate.
NORRINGTON Think again, Miss Swan.
NORRINGTON Vile and dissolute creatures, the lot of them.
NORRINGTON I intend to see to it that any man who sails under a pirate flag, or wears a pirates brand, gets what he deserves: a short drop and a sudden stop.
Elizabeth doesn't know what 'a short drop and a sudden stop' means.
Gibbs helpfully mimes: a man being hung.
SWAN Captain Norrington...
SWAN I appreciate your fervor, but I am concerned about the effect this subject will have on my daughter.
NORRINGTON My apologies, Governor.
ELIZABETH Actually, I find it all fascinating.
SWAN And that's what concerns me.
SWAN Elizabeth, dear...
SWAN we will be landing in Port Royal very soon, and beginning our new lives.
SWAN Wouldn't it be wonderful if we comport ourselves as befits our class and station?
ELIZABETH Yes, father.
Chastised, she turns away, to look out over the bow rail.
ELIZABETH (CONT'D) I still think it would be exciting to meet a pirate...
The fog still hems in the ship; very little of the sea is visible --
-- but suddenly, a FIGURE comes into view.
A young boy, WILL TURNER, floating on his back in the otherwise empty water.
There is nothing to show where he came from, or how he came to be there.
ELIZABETH (CONT'D) Look!
ELIZABETH (CONT'D) A boy!
ELIZABETH (CONT'D) In the water!
Norrington and Swann spot him --
NORRINGTON Man overboard!
ELIZABETH Boy overboard!
NORRINGTON Fetch a hook!
NORRINGTON Haul him out of there!
Quick movement and activity on the deck.
Sailors use a boathook to snag the boy he the passes.
Norrington and Swann haul him aboard, and lay him on the deck.
Elizabeth sidles in for a closer look.
NORRINGTON (CONT'D) He's still breathing.
SWAN Where did he come from?
GIBBS Mary mother of God ...
Attention is turned away from the boy --
The sea is no longer empty.
WRECKAGE from a ship litters the water...
along with the bodies of its crew.
What is left of the ship's hull BURNS, a ragged British flag hanging limply from the stern.
The H.M.S. Dauntless slips silently through it all.
The scene calls for hushed voices.
SWAN What happened here?
NORRINGTON An explosion in the powder magazine.
NORRINGTON Merchant vessels run heavily armed.
GIBBS Lot of good it did them...
GIBBS Everyone's thinking it!
GIBBS I'm just saying it!
GIBBS Pirates!
SWAN There is no proof of that.
SWAN It could have been an accident.
SWAN Captain, these men were protection.
SWAN If there is even the slightest chance one of those poor devils is still alive, we cannot abandon them!
NORRINGTON Of course not, Governor.
NORRINGTON Come about and strike the sails!
NORRINGTON Unlash the boats!
NORRINGTON Gunnery crew...
NORRINGTON jackets off the cannons!
NORRINGTON Hope for the best...prepare for the worst.
NORRINGTON Move the boy aft.
NORRINGTON We'll need the deck clear.
They lift the boy.
Swann pulls Elizabeth away from the rail, away from the hideous scene in the water.
SWAN Elizabeth, I want you to accompany the boy.
SWAN He's in your charge now.
SWAN You'll watch over him?
Elizabeth nods gravely.
Swann hurries away to help unstow the longboat.
The sailors lay the boy gently on the poop deck, behind the wheel, then hurry off.
Elizabeth kneels down besides the boy.
His good looks are not lost on her.
She reaches out, gently brushes the blond hair from his eyes --
Suddenly, he grabs her wrist, awake now.
Elizabeth is startled, but their eyes lock.
She takes his hand in hers.
ELIZABETH My name is Elizabeth Swann.
WILL Will Turner.
ELIZABETH I'm watching over you, Will.
He clutches her hands, then slips back into unconsciousness.
His movement has opened the collar of his shirt; Elizabeth sees he wears a chain around his neck.
She tugs it free, revealing--
A GOLD MEDALLION.
One side is blank.
She turns it over --
A SKULL gazes up at her.
Vaguely Aztec in design, but to her eyes, it means one thing only:
ELIZABETH (CONT'D) You're a pirate.
She glances back at the crew.
Sees Norrington, giving orders, moving toward her.
She looks back at Will -- comes to a quick decision.
Takes the medallion from around his neck.
Hides it under her coat.
Norrington arrives.
NORRINGTON Did he speak?
ELIZABETH His name is Will Turner -- that's all I found out.
NORRINGTON Very good.
Norrington hurries off.
Elizabeth steals away to the stern of the ship.
Examines her prize -- the gold medallion.
A wisp of wind, and she looks up --
Out over the sea, moving through the fog, silent as a ghost, is a large sailing ship, a schooner --
It has BLACK SAILS.
Elizabeth stares, too frightened to move, or cry out.
The ship is obscured by the fog it as it passes -- but not the mizzen-top ...
and there hangs the frightening skull and crossbones of the Jolly Roger.
Elizabeth looks from it to the medallion -- the skull on the flag is the same as the one on the medallion.
Fog surrounds and closes in on the black ship -- except for the black flag.
As Elizabeth watches, the skull appears to TURN and GRIN at her --
Elizabeth shuts her eyes tight --
-- and then snap open again, startled wide with fear.
But this is no longer twelve-year-old Elizabeth standing on the stern of the Dauntless; this is twenty-year-old Elizabeth, lying in bed in the dark.
She remains motionless (were the images we just saw a nightmare, or a jumbled childhood memory?)
Elizabeth slowly looks as far out the corner of her eyes as possible without moving.
Might there be someone in the room with her, looming over her?
She turns, ready for anything.
She is alone.
Elizabeth sits up, turns up the flame on an oil lamp besides the canopied bed.
She carries the lamp across the room to a dressing table, sits down.
She pulls one of the small drawers all the way out, reaches into a space beneath it and removes --
The MEDALLION.
She has kept it all this time.
It has not lost its luster -- or its sense of menace.
She gazes at it as she absently returns the draw to its place --
A BOOMING knock on the door; Elizabeth jumps up, startled knocking over her chair.
SWANN Elizabeth?
SWANN Is everything all right?
SWANN Are you decent?
ELIZABETH Yes -- yes.
She puts the medallion on, throws on a dressing gown as Swann enters, carrying a large box.
A uniformed maid, ESTRELLA, follows.
SWANN Still abed at this hour?
SWANN It's a beautiful day!
Estrella pulls back the heavy curtains, revealing:
Beneath a blue sky lies the bucolic town of PORT ROYAL, built on a natural harbor.
On a bluff at the mouth of the harbor stands FORT CHARLES, its stone parapets lined with cannon.
SWANN (CONT'D) I have a gift for you.
He opens the boxes, and displays for her a gorgeous velvet dress.
She lets out an admiring gasp.
ELIZABETH It's -- beautiful.
ELIZABETH May I inquire as to the occasion?
SWANN Is an occasion necessary for a father to dote upon his daughter with gifts?
Elizabeth happily takes it, disappears behind a screened- off dressing area.
Estrella follows, carrying the box.
SWANN (CONT'D) Although...I did think you could wear it to the ceremony today.
ELIZABETH Ceremony?
SWANN Captain Norrington's promotion ceremony.
Elizabeth peeks around the screen.
ELIZABETH I knew it.
SWANN Or, rather, Commodore Norrington...a fine gentleman, don't you think?
SWANN He fancies you, you know.
Behind the screen, Elizabeth GASPS.
SWANN (CONT'D) Elizabeth?
SWANN (CONT'D) How's it coming?
ON ELIZABETH -- She holds her hair and the medallion (still around her neck) out of the way as the maid cinches her into a corset over her slip.
Estrella has her foot in Elizabeth's back as she pulls the laces tight.
ELIZABETH Difficult ...
ELIZABETH to say.
SWANN I'm told that dress is the very latest fashion in London.
ELIZABETH Women in London must have learned to not breath.
Estrella is finished.
Elizabeth takes a breath -- and winces.
A butler appears in the doorway of the room.
BUTLER Governor?
BUTLER A caller is here for you.
The caller, dressed in rough clothing, stands in the foyer, looking very out of place, and knowing it.
He holds a long presentation case.
He polishes the toes of his boots on the back of his calves, but it doesn't help.
SWANN Ah, Mr. Turner!
SWANN It's good to see you again!
The caller turns -- it is WILL TURNER.
Handsome, with a watchful demeanor that gives him weight beyond his years.
WILL Good day, sir.
WILL I have your order.
Swann hurries to him, opens the case.
Inside is a beautiful dress sword and scabbard.
Swann takes it out reverently.
WILL (CONT'D) The blade is folded steel.
WILL (CONT'D) That's gold filigree laid into the handle.
WILL (CONT'D) If I may -
He takes the sword from Swann, and balances it on one finger at the point where the blade meets the guard.
WILL (CONT'D) Perfectly balanced.
WILL (CONT'D) The tang is nearly the full width of the blade..
SWANN Impressive.
SWANN ..
SWANN very impressive.
SWANN Commodore Norrington will be pleased, I'm sure.
SWANN Do pass my compliments on to your master.
Will's face falls.
Clearly, the work is his, and he is proud of it.
With practiced ease, he flips the sword around, catches it by the hilt and returns it to the case.
WILL I shall.
WILL A craftsman is always pleased to hear his work is appreciated --
He stops speaking abruptly, staring past Swann -
Elizabeth stands on the stairs.
Granted, the dress may be painful to wear, but holy smokes!
SWANN Elizabeth!
SWANN You look stunning!
Will tries to speak, but can't.
He gives up, smiles to himself, and simply nods emphatically.
ELIZABETH Will!
ELIZABETH It's so good to see you!
Her hand goes to the chain around her throat (the medallion is hidden in the bodice of her dress).
ELIZABETH (CONT'D) I dreamt about you last night.
Will reacts with surprise: "Really?
SWANN Elizabeth, this is hardly appropriate -
ELIZABETH About the day we met.
ELIZABETH Do you remember?
WILL I could never forget it, Miss Swann.
ELIZABETH Will, how many times must I ask you to call me 'Elizabeth'?
WILL At least once more, Miss Swann.
WILL As always.
Elizabeth is disappointed and a little hurt by his response.
SWANN Well said!
SWANN There's a boy who understands propriety.
SWANN Now, we must be going.
Swann takes the case from Will, opens the door for Elizabeth.
Elizabeth straightens her back, gathers her skirts and strides past Will.
ELIZABETH Good day, Mr. Turner.
Swann follows Elizabeth out the door.
WILL Good day.
He watches as she is helped aboard a carriage by the driver.
WILL (CONT'D) Elizabeth.
IN THE CARRIAGE: Swann glowers at his daughter.
SWANN Dear, I do hope you demonstrate a bit more decorum in front of Commodore Norrington.
SWANN After all, it is only
SWANN through his efforts that Port Royal has become at all civilized.
The skeletal remains of four pirates, still clad in buccaneer rags, hang from gallows erected on a rocky promontory.
There is a fifth, unoccupied gallows, bearing a sign:
The top of a billowing sail passes regally in front of them.
On the landward face of the sail, apparently high in the rigging, is a man for whom the term 'swashbuckling rogue' was coined: Captain JACK SPARROW.
He gazes keen-eyed at the display as they pass.
Raises a tankard in salute.
Suddenly, something below catches his attention.
He jumps from the rigging -
-- and that's when we see that his is ship is not an imposing three-master, but just a small fishing dory with a single sail, plowing through the water -- the Jolly Mon.
And it leaks.
Which is why he has the tankard: to bail.
Jack steps back to the tiller, and using a single sheet to control the sail, and the Jolly Mon comes around the promontory, the whole of Port Royal laid out before him.
The huge British dreadnought, H.M.S. Dauntless dominates the bay.
But Jack's attention is on a different ship: the H.M.S.
Interceptor, a small sleek vessel with rail guns and a mortar in the middle of the main deck.
It is tied up at the Navy landing, at the base of the cliffs below Fort Charles.
Smoothly and with no wasted movement, Jack hauls down the sail, stows it, guides the dory alongside a dock.
The HARBORMASTER, a long ledger tucked under his arm, is there to catch a line and help Jack tie up.
HARBORMASTER If you're out rolling scuppers in this tub, you're either incredibly brave or incredibly stupid.
JACK It's remarkable how often those two traits coincide.
He starts up the dock, strapping on his sword belt; besides the scabbard, it also carries a compass, pistol and small powder horn.
The Harbormaster cuts him off.
HARBORMASTER It's a shilling for the dock space, and you're going to have to give me your name.
JACK What do you say to three shillings, and we forget the name?
He tosses three shillings onto the ledger.
The Harbormaster considers, then shuts the ledger on the coins, steps aside.
HARBORMASTER Welcome to Port Royal, Mr. Smith.
Jack gives him a half-salute as he goes past.
Looks across the water toward the Interceptor -- and smiles.
Above the Interceptor, among the parapets of Fort Charles, a ceremony is underway -
With choreographed precision, Swann removes the sword and scabbard from the presentation case, held by a uniformed Navy man.
He slides the sword into the scabbard, holds it out vertically to Norrington, in full dress uniform.
Norrington grasps the scabbard above Swann's hand, and Swann lets go.
Norrington draws the sword, flourishes the sword, and snaps the blade up in front of his face.
Swann steps forward, pins a medal to Norrington's jacket, steps back.
Norrington nods, turns smartly and nods to his fellow officers, turns again and nods to the audience - dignitaries, merchants, plantation owners, their families.
Another flourish, and he returns the sword to its scabbard.
The silence is broken by loud APPLAUSE.
Backslapping from the Navy men.
In the audience, Elizabeth doesn't look so good, out beneath the hot sun.
She applauds briefly, then winces.
Discreetly tries to adjust the corset through the material of the dress, then resumes clapping, trying to hide her discomfort.
Two sailors on sentry duty, MURTOGG and MULLROY, take advantage of what little shade there is on the dock.
But when Jack saunters up, they are immediately on alert.
MURTOGG This dock is off-limits to civilians.
JACK Sorry, I didn't know.
Music drifts down from Fort Charles.
Jack looks up, shields his eyes.
JACK (CONT'D) Some sort of to-do up at the fort, eh?
JACK (CONT'D) You two weren't invited?
MURTOGG No ...
MURTOGG someone has to make sure this dock stays off-limits to civilians.
JACK This must be some important boat.
MULLROY Ship.
JACK Ship.
MURTOGG Captain Norrington's made it his flagship.
MURTOGG He'll use it to hunt down the last dregs of piracy on the Spanish Lake.
MULLROY Commodore.
MURTOGG Right.
MURTOGG Commodore Norrington.
JACK That's a fine goal, I'm sure ...
JACK But it seems to me a ship like that --
JACK -- makes this one here just a wee superfluous.
MURTOGG Oh, the Dauntless is the power in these waters, true enough -- but there's no ship that can match the Interceptor for speed.
JACK That so?
JACK I've heard of one, supposed to be fast, nigh uncatchable ...
JACK the Black Pearl?
Mullroy scoffs at the name.
MULLR0Y There's no real ship as can match the Interceptor.
MURTOGG The Black Pearl is a real ship.
MULLROY No, it's not.
MURTOGG Yes it is.
MURTOGG I've seen it.
MULLR0Y You've seen it?
MURTOGG Yes.
MULLROY You've seen the Black Pearl?
MURTOGG Yes.
MULLR0Y You haven't seen it.
MURTOGG Yes, I have.
MULLR0Y You've seen a ship with black sails that's crewed by the damned and captained by a man so evil that hell itself spat him back out?
MURTOGG ...
MURTOGG No .
MULLROY No.
MURTOGG But I've seen a ship with black sails.
MULLR0Y Oh, and no ship that's not crewed by the damned and captained by a man so evil hell itself spat him back out could possibly have black sails and therefore couldn't possibly be any ship other than the Black Pearl.
MULLR0Y Is that what you're saying?
MURTOGG ...
MURTOGG no.
MULLR0Y Like I said, there's no real ship as can match -- Hey!
But Jack's not there.
Murtogg and Mullroy look around, spot -
Jack standing at the wheel of the Interceptor, casually examining the mechanism.
MULLROY (CONT'D) You!
Jack looks over in exaggeratedly innocent surprise.
The sailors hurry toward the gangplank.
MULLROY (CONT'D) Get away from there!
MULLROY (CONT'D) You don't have permission to be aboard there!
Jack spreads his hands in apology.
JACK I'm sorry.
JACK It's just such a pretty boat.
JACK Ship.
The sailors study him suspiciously.
MURTOGG What's your name?
JACK Smith.
MULLR0Y What's your business in Port Royal, 'Mr.
MULLR0Y Smith' ?
MURTOGG And no lies!
JACK None?
JACK Very well.
JACK You've rumbled me.
JACK I confess: I intend to commandeer one of these ships, pick up a crew in Tortuga, and go out on the account, do a little honest pirating.
MURTOGG I said, no lies.
MULLR0Y I think he's telling the truth.
MURTOGG He's not telling the truth.
MULLROY He may be.
MURTOGG If he were telling the truth he wouldn't have told us.
JACK Unless, of course, he knew you wouldn't believe the truth if he told it to you.
Murtogg and Mullroy consider that point --
Elizabeth, pale and perspiring, fans herself weakly, oblivious to the music and chatter.
NORRINGTON May I have a moment?
He extends his arm.
She takes it.
He walks her away from the party, toward the parapet.
A rather too long of a silence as Norrington works up his courage.
NORRINGTON (CONT'D) You look lovely.
NORRINGTON (CONT'D) Elizabeth.
Elizabeth frowns, unable to focus.
Norrington mistakes her expression as disapproval.
NORRINGTON (CONT'D) I apologize if I seem forward -- but I must speak my mind.
NORRINGTON (CONT'D) This promotion confirms that I have accomplished the goals I set for myself in my career.
NORRINGTON (CONT'D) But it also casts into sharp relief that which I have not achieved.
NORRINGTON (CONT'D) The thing all men most require: a marriage to a fine woman.
NORRINGTON (CONT'D) You have become a fine woman, Elizabeth.
ELIZABETH I can't breathe.
NORRINGTON I'm a bit nervous, myself --
Elizabeth loses her balance, stumbles away from Norrington.
She reaches a hand out to the parapet to steady herself, but it slides off -
-- and then she vanishes over the wall.
Gone.
NORRINGTON (CONT'D) Elizabeth!
Jack reacts, pushes Murtogg aside to see -
Elizabeth plummets from the top of the cliff.
It seems to take her a long time to reach the sea --
Elizabeth hits the water, narrowly missing the sharp rocks.
A wave breaks, and then she is washed out away from the cliff, struggling feebly.
AT THE FORT, Norrington looks down --
He leaps to the top of the parapet, prepared to dive -- a lieutenant, GILLETTE catches his arm.
GILLETTE The rocks, sir!
GILLETTE It's a miracle she missed them!
Norrington shakes off his arm, looks down -- and realizes Gillette is right.
He jumps down and runs --
Jack, Murtogg and Mullroy are still in shock from the sight.
JACK Aren't you going to save her?
MULLR0Y I can't swim.
Murtogg shakes his head -- neither does he.
JACK Sailors.
Above where Elizabeth struggles in the water.
Norrington and several other men pick their way down the cliffs.
They are too far away to get to her in time.
Jack scowls.
He has no choice -- and it pisses him off.
JACK (CONT'D) Fine.
He pulls a pistol from his sword belt, hands it to Murtogg; then hands the belt to Mullroy.
JACK (CONT'D) Don't lose these.
And then he dives into the water, swims toward Elizabeth.
Elizabeth struggles to keep above water, gasping for air '- then a swell rolls over her, and she is submerged -
UNDERWATER, Elizabeth drifts down, unconscious.
The current turns her, and the MEDALLION slips loose from her bodice.
The MEDALLION turns slowly, until the SKULL is fully visible.
A shaft of filtered sunlight hits it, and it
FORT CHARLES: The British flag flies, blown from an offshore breeze.
Suddenly the wind dies, and the flag goes limp.
ON THE DOCKS: Wood and metal fittings on lines bang against masts.
The wind dies, and there is silence.
ON THE EDGE OF TOWN: A CARIBE WOMAN feeds clucking chickens, frowns when they all suddenly go quiet ...
IN THE VILLAGE: A weather vane moves slightly in the wind.
The wind stops, and all is still.
And then ...
...
the weather vane TURNS, and holds steady -- the wind has picked up again, but now blows .from the sea toward the land.
l)ON THE BEACH: an OLD SALT pulls a rope line, pauses.
Turns and gazes to the sky, frowning.
The mangy hound at his side starts BARKING incessantly -
ON THE DOCKS: The lines bang against the other sides of the masts, the wind far stronger now.
FORT CHARLES: the British flag flies in the opposite direction, snapping in the new onshore breeze.
Norrington rushes down, intent on the climb.
Beyond him, past the rocky point, far out to sea, FOG gathers -
UNDERWATER: the medallion hangs below Elizabeth's unmoving form - - and then Jack is there.
He wraps an arm around her and makes for the surface.
ON THE SURFACE, Jack swims toward the dock, struggling.
It is .: far more difficult than it should be.
He stops stroking, and they submerge.
UNDERWATER: Jack realizes that it is Elizabeth's heavy velvet dress that is weighing them down.
He pulls at the buttons on the back, and they give way.
He skins her out of the dress, and kicks away from it.
The dress falls like a cloud into darkness -
ON THE SURFACE: Jack swims with Elizabeth, much more quickly.
AT THE DOCK, Murtogg and Mullroy are there to help haul Elizabeth out of the water.
Jack climbs up, exhausted.
Elizabeth is on her back; Murtogg holds her arms above her head, pumping them.
Mullroy puts his cheek to her nose and mouth.
MULLROY Not breathing.
Murtogg looks down; it seems hopeless.
Jack steps up, drawing Murtogg's knife from its sheath.
JACK Move.
He pushes past Mullroy, kneels over Elizabeth, raises the knife -- Murtogg is shocked -
Jack slits the corset down the middle, yanks it away.
Elizabeth remains still.
And then -- she coughs up water and gasps, choking on her first full breath.
Jack is relieved.
MULLROY I never would have thought of that.
JACK Clearly, you've never been to Singapore.
Jack flips the knife and hands it hilt-first to Murtogg - and that's when he spots -
The MEDALLION.
Jack catches it up in his "hand.
JACK (CONT'D) Where did you get this?
Before Elizabeth can answer, the BLADE of a SWORD is at Jack's THROAT -- Norrington's new ceremonial sword, in fact, looking bright and sharp.
NORRINGTON On your feet.
It looks bad -- Jack standing over Elizabeth, most of her clothes gone.
He gets to his feet.
The rest of Elizabeth's erstwhile rescuers reach the scene, including Swann.
SWANN Elizabeth!
SWANN Are you all right?
He strips off his jacket, drapes it around her.
ELIZABETH Yes -- yes, I'm fine -- Commodore Norrington, do you intend to kill my rescuer?
Norrington looks at Jack.
Jack nods as best he can with a blade beneath his chin.
Norrington sheathes his sword, and extends his hand.
NORRINGTON I believe thanks are in order.
Jack takes Norrington's hand gingerly.
They shake -
-- and Norrington tightens his grip, yanks Jack's arm toward him, then tears back the sleeve of Jack's shirt -
-- exposing a BRAND on Jack's inner wrist: a large 'P.'
NORRINGTON (CONT'D) Had a brush-up with the East India Trading Company, did you ...
NORRINGTON (CONT'D) pirate?
The others react in shock, but the sailors are well-trained --in an instant, half a dozen pistols are aimed at Jack.
He stands there, still holding the corset.
NORRINGTON (CONT'D) Keep your guns on him, men.
NORRINGTON (CONT'D) Gillette, fetch some irons.
Norrington notices something else -- below the 'P' brand is a tattoo: a small bird in flight across water.
NORRINGTON (CONT'D) Well, well...
NORRINGTON (CONT'D) Jack Sparrow, isn't it?
JACK Captain Jack Sparrow.
JACK If you please.
Norrington looks out at the bay.
NORRINGTON I don't see your ship -- Captain.
MURTOGG He said he'd come to commandeer one.
MULLROY I told you he was telling the truth.
MULLROY These are his, sir.
He holds out Jack's pistol and belt.
Norrington takes the pistol, examines it, notes the powder horn on Jack's belt.
NORRINGTON Extra powder, but no additional shot.
Jack shrugs.
Norrington unhooks the compass from the belt, opens it.
He frowns at the reading.
Moves the compass this way and that, keeping it parallel to the ground.
NORRINGTON (CONT'D) It doesn't bear true.
Jack looks away, a bit embarrassed.
Norrington returns the compass to the belt.
Draws the sword half from the scabbard.
NORRINGTON (CONT'D) I half-expected it to be made of wood.
He slides it back into the scabbard, hands it to Mullroy.
NORRINGTON (CONT'D) Taking stock: you've got a pistol with only one shot, a compass that doesn't point north ...
NORRINGTON (CONT'D) and no ship.
NORRINGTON (CONT'D) You are without a doubt the worst pirate I have ever heard of.
JACK Ah, but you have heard of me.
Gillette returns with shackles, approaches Jack.
NORRINGTON Carefully, lieutenant.
Elizabeth steps forward.
Swann's jacket slips off her.
She is unconcerned, but he is intent on putting it back on her.
ELIZABETH Commodore, I must protest.
ELIZABETH Pirate or not, this man saved my life.
NORRINGTON One good deed is not enough to redeem a man of a lifetime of wickedness.
Gillette snaps the manacles closed on Jack's wrists.
JACK But it seems to be enough to condemn him.
NORRINGTON Indeed.
Now that Jack is safely chained, Norrington nods to his men.
All but one stow their weapons, and two step forward -
JACK Finally.
Lightning-quick, he snaps the corset around the hand and wrist of the man holding the pistol and yanks.
The pistol sails into the water.
Before anyone can react to that, Jack has the manacle chain wrapped around Elizabeth's throat.
Pistols are drawn again, but now Elizabeth serves as a shield.
Norrington raises a cautioning hand to his men.
JACK (CONT'D) Commodore Norrington ...
JACK (CONT'D) my pistol and belt, please.
Norrington hesitates, balls his fists in frustration.
JACK (CONT'D) Commodore!
Mullroy hands the pistol and belt to Norrington.
Norrington holds them out to Jack.
JACK (CONT'D) Elizabeth -- it is Elizabeth?
Elizabeth is more angry than frightened.
ELIZABETH Miss Swann.
JACK Miss Swann, if you'll be so kind?
She takes the belt and pistol from Norrington -- Jack's quicker than she is, and takes the pistol from her.
He jerks her around so she is facing him, belly to belly.
JACK (CONT'D) Now, if you'll be very kind?
She figures out what he wants: put the belt on him.
ELIZABETH You are despicable.
JACK I saved your life; now you've saved mine.
JACK We're square.
Done.
He turns her again, and then backs up until he bumps against the cargo gantry.
JACK (CONT'D) Gentleman.
JACK (CONT'D) ..
JACK (CONT'D) m' lady.
JACK (CONT'D) ..
JACK (CONT'D) you will always remember this as the day you almost caught Captain Jack Sparrow.
He shoves Elizabeth away, grabs a rope and pulls free a belaying pin -- a counterweight drops and Jack is lifted up to the middle of the gantry, where he grabs a second rope -
Pistols fire -- and miss.
Jack swings out, out, out, away and around from the gantry.
Norrington has held his shot.
With careful aim, he tracks Jack's trajectory-
Jack drops from the rope even as Norrington FIRES.
His shot tears the rope -
-- as Jack plummets past one of the gantry's guy lines, he snaps the length of manacle chain over the line and grabs hold of the far loop -- slides down the line -
-- drops to the deck of a ship.
He runs, leaping to another ship, then out of sight -
NORRINGTON On his heels!
NORRINGTON Gillette, bring a squad down from the fort!
NORRINGTON Elizabeth, are you -
ELIZABETH Yes, I'm all right, I'm fine!
ELIZABETH Go capture him.
Norrington's taken aback by her ire, and wisely hurries away.
Swann drapes his coat around Elizabeth.
SWANN Here, dear ...
SWANN you should wear this.
Elizabeth shivers, finding suddenly that she is cold.
Glances out at the bay -
-- where a THICK FOG moves across the top of the water.
She takes the jacket.
ELIZABETH Thank you, Father ...
ELIZABETH and let that be the last of your fashion advice, please.
But she accepts his comforting embrace.
The fog creeps through, casting an eerie twilight pall.
An armed search party moves along the street.
They glance down an alley-
On the far side is another search party.
The men nod to each other, continue on.
A moment, and then Jack drops from his hiding place beneath the eaves of a building.
He still wears the manacles.
Across the street is a shop with barn doors, a pass-thru door set in the middle.
Above is a sign with a black anvil.
Jack slips in through the door, takes a look around:
No windows.
The forge is dark, lit by lanterns.
Work-in- progress is scattered about: wagon wheels, wrought iron gates, pipes -- even a cannon with a crack in it.
But every tool is in place; the workbench is tidy and neat.
Jack is startled by a noise: MISTER BROWN, in a blacksmith's apron, snores in the corner, cradling a bottle.
Jack gives him a hard poke.
Another.
Brown snorts, turns away.
Satisfied, Jack sheathes his sword, takes a short-handled sledge from its place on the wall.
Moves to the glowing coke furnace in the middle of the room.
Slowly...
he holds his right hand over the furnace, the chain down in the embers.
The chain begins to GLOW.
Jack sweats, grimaces at the pain -
Moving quickly, he wraps the chain around the nose of an anvil, brings the sledge down with a fast, hard stroke on the glowing links.
One SHATTERS.
Jack drops the sledge, plunges his manacled hand in a bucket of water.
Steam billows.
Jack pulls his hand out, flexes it.
Blisters form beneath the manacle -- but his hands are free.
The SOUND of the latch on the door -- Jack dives for cover.
Will enters the forge, shuts the door behind him.
Spots the drunken Mister Brown in the corner.
WILL Right where I left you.
Something catches his eye: an empty peg on the wall.
The sledge lying beside the anvil.
WILL (CONT'D) Not where I left you.
He moves casually toward the sledge.
Then grabs for it -- but the flat of a sword blade slaps his hand.
Will jumps back.
Jack stands there, sword leveled at Will.
He backs Will up, toward the door.
Will glares at him.
WILL (CONT' D) You're the one they're hunting.
WILL (CONT' D) The pirate.
Jack acknowledges it with a tip of his head ...
then frowns, regards Will.
JACK You look familiar ...
JACK Have I ever threatened you before?
WILL I've made a point of avoiding familiarity with pirates.
JACK Ah.
JACK Then it would be a shame to put a black mark on your record.
JACK So if you'll excuse me ...
Beside the door is a grindstone, a sword resting in the honing guide.
Before Jack can react, Will has it in hand.
JACK (CONT'D) Do you think this is wise, boy?
JACK (CONT'D) Crossing blades with a pirate?
WILL You threatened Miss Swann.
JACK Only a little.
In response, Will assumes an en garde position.
Jack appraises him, unhappy to see Will knows what he's doing.
Jack attacks.
The two men stand in one place, trading feints, thrusts and parries with lightning speed, almost impossible to follow.
Will has no trouble matching Jack.
JACK (CONT'D) You know what you're doing, I'll give you that ...
JACK (CONT'D) Excellent form ...
JACK (CONT'D) But how's your footwork?
JACK (CONT'D) If I step here -
He takes a step around an imaginary circle.
Will steps the other way, maintaining his relationship to Jack.
JACK (CONT'D) Very good!
JACK (CONT'D) And if I step again, you step again.
JACK (CONT'D) And so we circle, circle, like dogs we circle.
They are now exactly opposite their initial positions.
JACK (CONT'D) Ta!
Jack turns and heads for the door, now directly behind him.
Will registers angry surprise -- and then with a vicious overhand motion, he throws his sword -
-- the sword buries itself into the door, just above the latch, barely missing Jack.
Jack registers it, then pulls on the latch, but it won't move up -- the sword is in the way.
Jack rattles the latch.
Tugs on the sword a few times -- it is really stuck in there.
Jack mouths a curse, but when he turns back to Will, he's smiling.
JACK (CONT' D) That's a good trick.
JACK (CONT' D) Except, once again, you are between me and the way out.
JACK (CONT' D) And now you have no weapon.
Eyes on Jack, Will simply picks up a new sword from an anvil.
Jack slumps in dismay -- but then leaps forward.
Will and Jack duel.
Their blades flash and ring.
Suddenly, Jack swings the chain still manacled to his left hand at Will's head.
Will ducks it, comes up wide-eyed.
Then Jack's chain smashes across Will's sword, disarming him.
Will quickly picks up another sword.
Jack becomes aware that the entire room is filled with bladed weapons: swords, knives, boarding axes in various stages of completion.
JACK (CONT'D) Who makes all these?
WILL I do.
WILL And I practice with them.
WILL At least three hours a day.
JACK You need to find yourself a girl.
JACK Or maybe the reason you practice three hours a day is you've found one -- but can't get her?
A direct hit -- and Will coils even more tightly with anger.
WILL No.
WILL I practice three hours a day so that when I meet a pirate ...
WILL I can kill him.
He explodes: kicks a rack, causing a sword to fall into his hand; uses his foot to bring his dropped sword into the air, catches it -- and attacks Jack, both blades flashing.
Jack parries with sword and chain.
Jack's chain wraps around Will's sword; Will twists the handle of his guard through a link, and stabs the sword up into the ceiling -
So Jack's manacled left arm is now suspended from the ceiling.
Not good.
He parries using one hand, twisting and dodging around the furnace -
Jack compresses the bellows, blowing a SHOWER OF SPARKS into Will's face.
Jack grabs the chain, hoists himself up, kicks with his feet, knocking Will back.
Jack uses his full weight, yanks the sword from the ceiling.
Hurls a wooden mallet at Will, then a second, hitting Will on the wrist.
Will drops his sword, falls down, gets up -
Jack's pistol is aimed directly between Will's eyes.
Will steps back, directly in front of the back exit.
Glares, rubs his wrist gingerly.
WILL (CONT'D) You cheated.
JACK Pirate.
Jack steps forward.
Will steps back, fully blocking the door.
JACK (CONT'D) Move away.
WILL No.
JACK Move!
WILL No.
WILL I can not just step aside and let you escape.
Jack cocks the pistol.
Will stares back.
The stand-off lasts for a long moment.
JACK You're lucky, boy -- this shot's not meant for you.
Jack uncocks the pistol.
Will is surprised, reassesses Jack -
Suddenly, Mister Brown SLAMS his bottle against Jack's skull.
Jack crumples to the ground.
The front and back doors smash open, and SAILORS fill the room.
Norrington pushes forward, sees Jack on the ground.
NORRINGTON Excellent work, Mister Brown.
NORRINGTON You've aided in the capture of a dangerous fugitive.
BROWN Just doing my civic duty.
Jack groans.
Norrington stands over him, smiles.
NORRINGTON I believe you will always remember this as the day Captain Jack Sparrow almost escaped.
Norrington's men haul Jack away.
Will watches them go.
Brown looks at his bottle -- broken.
BROWN That ratter broke my bottle.
The thick fog blankets the entire bay now, and the town.
The only structure visible is Fort Charles, high on the
bluff, like a tall ship sailing a sea of grey.
Above the Fort is a clear black sky sprinkled with stars.
A waxing moon shines, giving both Fort and fog an eerie glow.
ANGLE - FORT CHARLES, just below the stone parapets of the fort, visible briefly deep in the fog, like a shark fin slicing through the water: the TOPMAST of a ship, BLACK SAILS billowing.
Flying from the mast is a flag with white Aztec skull.
The Black Pearl has come to Port Royal.
A maid removes a bed warmer from the fireplace, slides it between the sheets at the end of Elizabeth's bed.
ELIZABETH Nice and toasty.
ELIZABETH Thank you, Estrellia.
The maid nods, exits.
Elizabeth opens a book, begins reading, toying absently with the medallion chain around her neck.
The lamp flame begins to diminish.
Elizabeth tries to turn it up.
No good.
The flame goes out, and the room is black.
Will, shirtless, wearing a leather apron, heats an iron ingot at the furnace, hammers it flat -- he stops.
His attention is drawn to the window.
He opens the shutter and peers out -- nothing but fog.
Almost without noticing,
he reaches for a boarding axe hanging on the wall.
Takes it down; it has a satisfying weight in his hands.
CLOSE ON: A mutt of a dog, holding a ring of keys in his mouth.
Three seedy-looking prisoners try to coax the dog to their cell door.
One holds a loop of rope; another waggles a bone.
The dog just sits and cocks its head.
PRISONER Come here, boy...
PRISONER Want a nice, juicy bone?
In an adjoining cell, Jack lies on a pile of straw.
JACK You can keep doing that forever, that dog's never going to move.
PRISONER Excuse us if we ain't resigned ourselves to the gallows just yet.
A noose hangs from a gallows in the courtyard.
Norrington and Swann walk along the far wall.
SWANN Has my daughter given you an answer yet?
NORRINGTON No.
NORRINGTON She hasn't.
SWANN Well, she had a taxing day...
SWANN Ghastly weather tonight.
NORRINGTON Bleak.
NORRINGTON Very bleak.
From the distance, there is a BOOM -
SWANN What was that?
-- and then the WHISTLE of an incoming ball --
NORRINGTON Cannon fire!
He tackles Swann as the wall of the parapet EXPLODES --
Jack sits up.
There are more BOOMS -
JACK I know those guns!
He peers out through the bars of the window.
The other prisoners crowd around their window as well.
JACK (CONT'D) It's the Black Pearl.
PRISONER The Black Pearl?
PRISONER I've heard stories ...
PRISONER she's been preying on ships and settlements for near ten years ...
PRISONER and never leaves any survivors.
JACK There are a lot of stories about the Black Pearl.
The Black Pearl still cannot be seen -- but the fog lights up around her with each boom of her guns.
She's firing on both sides now, hammering both the fort and the town.
Streets, buildings, docks and ships shatter and explode beneath the onslaught.
Villagers panic, run for cover, dodge flying debris as best they can.
If this is not hell on earth, then it's about to be --
-- long boats emerge out of the fog, carrying ARMED PIRATES.
They swarm from the boats, striking down ,villagers indiscriminately and setting fires.
Will slips the boarding axe into his belt at the small of his back.
He puts a dirk in his belt, then a second and a third.
He picks up a second axe and a sword.
Will slides back the doors of the forge --
A woman runs past, chased by a ONE-ARMED PIRATE wearing a yellow bandeau.
Will backhands the axe square into his chest, a deadly blow.
Will heads out, up the street --
The moon is obscured by smoke rising from the burning gallows and wooden roofs.
Cannon fire continues to rain down, but the fort's own cannons now return fire.
NORRINGTON Governor!
NORRINGTON Barricade yourself in my office!
NORRINGTON That's an order!
Swann turns to go -- but finds himself face-to-face with a pirate -- KOEHLER, a handsome blond man with gold earrings.
Beyond Koehler, more pirates come up over the far wall.
Koehler grins and raises a cutlass -
-- Norrington's sword blocks Koehler's slash.
NORRINGTON (CONT'D) They've flanked us!
NORRINGTON (CONT'D) Men!
NORRINGTON (CONT'D) Swords and pistols!
The battle is joined --
INT.
GOVERNOR'S MANSION - ELIZABETH f S BEDROOM - NIGHT
Elizabeth looks out a window at the scene below: even through the fog, multiple fires are visible, and ships burn in the harbor.
Shouts and cries of pain.
Cannon fire
She notices movement directly below her window: two SHADOWY FIGURES, approaching the house -- pirates.
Elizabeth bolts from her room--
She reaches the railing overlooking the foyer, and cries out, just as the butler opens the door -- too late; there is the BOOM of a gun, and the butler crumples.
Elizabeth ducks down in horror, peering through the balusters.
The pirates scan the foyer, searching.
The leader is PINTEL, a sallow-looking pirate with a bald head.
Suddenly Pintel looks up, and locks eyes with Elizabeth.
How could he know she was there?
PINTEL Up there!
The pirates rush for the stairs.
Elizabeth scrambles back into the nearest room--
Elizabeth shuts the door, locks it, listens as the pirates pound up the stairs --
ESTRELLA Miss Elizabeth?
Elizabeth jumps.
Estrella is right behind her, terrified.
They whisper:
ESTRELLA (CONT'D) Are they come to kidnap you, miss?
ESTRELLA (CONT'D) The daughter of the governor would be very valuable.
Elizabeth realizes she's right.
There is the SLAM of a body against the door.
ELIZABETH Listen, Estrella -- they haven't seen you.
ELIZABETH Hide, and first chance, run for the fort .
Estrella nods.
Another SLAM at the door -- it gives a bit - -
Elizabeth shoves Estrella into the corner, between a tall wardrobe and the wall.
Dashes for the side door.
When the door smashes inward, it slams into the wardrobe, and the maid cannot be seen.
The pirates run in -- spot the open side door, and run for it --
Pintel is the first through, and gets the pan of the bed warmer in the face for his trouble -- he staggers back, holding his nose --
Estrella breaks cover, runs for the hall, unnoticed.
-- Elizabeth swings the bed warmer at the second pirate, but he catches it by the handle -- Elizabeth can't jerk it free, so she wrenches it over -- the pan lid swings down, BANGING the second pirate -- hot coals spill on his head, sizzling.
Elizabeth dashes for the hallway stairs -
The pirates burst from the bedroom -- Pintel goes for the stairs, but the second pirate vaults the handrail --
Estrella registers the butler's body, but continues out the still-open front door at a dead run.
Elizabeth follows --
The second pirate lands between Elizabeth and the front door.
His face is BURNED, his hair SMOLDERS -- he reaches - -
Elizabeth pulls up short, runs the other way --
Pintel, on the stairs, grabs her by the hair -- Elizabeth
doesn't slow -- she spins, grabs Pintel's arm with both hands and pulls him hard, belly-first, into the cap of the newel post -- he lets go of her hair -- Elizabeth keeps going
Elizabeth slams the double doors shut, throws the bolts.
The interior shutters are closed over the windows.
Above the fireplace are two crossed swords.
Elizabeth climbs on the firebox; she grabs one of the swords by the hilt and pulls -- but it won't come free.
Both swords are securely attached to the wall.
Damn!
A SMASH from the doors -- the pirates are relentless -
On the table is a platter with fruit, cheese and bread.
Elizabeth grabs the knife from the platter -
Like any bread knife, it has a round point.
Elizabeth jabs it into her palm -- it's useless as a weapon.
Double damn!
The blade of a boarding axe breaches the door -- the pirates will be through soon -- Elizabeth looks around -
The doors give way; the pirates charge through -
Empty.
Elizabeth nowhere to be seen.
Pintel and Smoldering Pirate search, under the table, behind draperies.
PINTEL We know you're here, poppet.
PINTEL Come out and we promise we won't hurt you.
Smoldering pirate gives him look -- he wants to hurt her plenty.
Pintel shakes his head: 'Don't worry, I'm lying.'
PINTEL (CONT'D) We will find you, poppet ...
PINTEL (CONT'D) You've got something of ours, and it calls to us!
Elizabeth hides in the dumbwaiter box, wrapped around the double pulley ropes that go through the center.
PINTEL The gold calls to us!
Elizabeth registers that -- she pulls out the medallion, rubs
the gold with her thumb.
This is their objective.
Light
spills into the- box through gaps in the top as the door above is slid open -- Elizabeth looks up through the gaps -
Pintel leers down at her.
PINTEL (CONT'D) Hello, poppet.
Elizabeth works the ropes to lower the box.
Pintel pulls the other way; he's stronger, and the box rises.
Elizabeth tries to stop it -- wraps her left forearm through the rope and lets it jam against the top of the box.
Elizabeth gasps at the pain, but the box stops.
She saws at the rope with the bread knife.
Smoldering pirate helps pull the rope, crushing Elizabeth's forearm.
Tears of pain on her face, she keeps sawing -
The rope parts, and the dumbwaiter box PLUMMETS -
From behind the door of the dumbwaiter comes a CRASH, and a cloud of dust.
The door slides open, and Elizabeth clambers out.
Her head is cut, she is streaked with dirt, and can barely stand.
She leans over the table, trying to recover.
The sound of running FOOTSTEPS gets louder ...
ELIZABETH Please, no ...
Elizabeth touches the chain of the medallion ...
and a desperate idea occurs to her.
The pirates burst through the door.
Elizabeth backs away, holds the bread knife out to ward them off.
They come around either side of the table, stalking her -
ELIZABETH (CONT'D) Par.
ELIZABETH (CONT'D) ..
ELIZABETH (CONT'D) Parlay!
Pintel can't believe his ears.
PINTEL What?
ELIZABETH Parlay!
ELIZABETH I invoke the right of parlay!
ELIZABETH According to" the Code of the Brethren, set down by the pirates Morgan and Bartholomew, you must take me to your Captain!
PINTEL I know the code.
ELIZABETH If an adversary demands parley, you can do them no harm until the parlay is complete.
PINTEL It would appear, so do you.
SMOLDERING PIRATE To blazes with the code!
He steps forward, dirk drawn -- Pintel stops him.
PINTEL She wants to be taken to the Captain, and she'll go without a fuss.
He looks to Elizabeth: 'right?' Elizabeth nods.
PINTEL (CONT'D) We must honor the code.
Smoldering Pirate concedes the point, sheaths his dirk.
He grabs Elizabeth roughly by the arm -
Will races along, momentarily free of the pirates.
He spots the Governor's Mansion in the distance.
There are FIGURES moving away from it -- Elizabeth, forced by the two pirates.
Will hurries forward -
Suddenly a PIRATE jumps out from the shadows, slashes; Will defends himself.
The pirate has one arm and wears a yellow bandana.
Will hesitates -- didn't he already kill this guy?
The hesitation is just enough for another PIRATE, swinging a flaming torch, to SLAM Will in the head from behind.
Will crumples.
The pirate lights a second torch, hands it to One-arm; they hoot with delight and head off, setting fires as they go.
On the ground, Will doesn't move.
The wall of the cells EXPLODES inward.
Jack pulls himself out from under rubble.
Moonlight spills in through the gaping hole created by the cannon ball.
Beyond it: freedom.
But it is centered on the other cell.
The part of Jack's cell that is gone is too small for a man to slip through.
PRISIONER Praise be!
He and the other two scramble through.
PRISONER (CONT'D) My sympathies, friend - - you've no manner of luck at all!
The three descend the rocks beyond, disappearing from view.
Jack is alone.
Cannon fire continues, occasional hits shaking the fort.
The dog cowers under a long bench, key ring still in his mouth.
Jack sighs -- resigned, he picks up the bone from the other cell, and tries coax the dog forward.
JACK It's all right, doggie ...
JACK come here,
boy.
Come here, Spot.
Rover.
Fido?
To his surprise, the dog crawls out from under the bench.
Jack continues to coax him closer.
The key ring is nearly within Jack's reach -- suddenly, the dog's attention goes to the door into the cell block.
He BRISTLES, GROWLS.
He backs away from the door, whining.
JACK (CONT'D) What's the matter, boy?
The dog bolts, through the bars, into the cell, then out through the breached wall -- taking the keys with him.
The door to the cell block bursts open.
A pair of pirates step in: KOEHLER and TWIGG.
TWIGG This isn't the armory.
He turns to go, but Koehler has spotted Jack.
KOEHLER Well, well...
KOEHLER Look what we have here, Twigg.
KOEHLER It's.
KOEHLER Captain Sparrow.
TWIGG Huh.
TWIGG Last time I saw you, you were all alone on a God-forsaken island, shrinking into the distance.
TWIGG I'd heard you'd gotten off, but I didn't believe it.
KOEHLER Did you sprout little wings and flyaway?
TWIGG His fortunes aren't improved much.
The two laugh.
Jack doesn't.
He steps forward, close to the bars.
This puts him in a spill of moonlight.
He is tight with fury.
JACK Worry about your own fortunes.
JACK The lowest circle of hell is reserved for betrayers ...
JACK and mutineers.
Koehler and Twigg don't like hearing that.
Koehler lashes out, grabs Jack by the throat through the bars.
Jack clutches the pirate's wrist, looks down -
Where they enter the moonlight, Koehler's wrists and hands are skeletal.
Jack's eyes go wide -- he is holding a skeleton arm.
JACK (CONT' D) You are cursed.
Koehler sneers, shoves Jack backwards, hard.
Now out of the moonlight, his hand is normal.
Jack stares, realizing -
JACK (CONT'D) The stories are true.
Koehler ushers Twigg toward the door.
Looks back.
KOEHLER You know nothing of hell.
And then they're gone.
Amid the thunder of cannon fire, a longboat slips through the fog.
Elizabeth sits in the prow.
Columns of water from cannon balls geyser up around the boat.
The fog parts.
Elizabeth looks up to see --
The Black Pearl, a tall galleon, its black sails looming high above her.
At the bow is an ornately carved figurehead of a beautiful woman, arm held high, a small bird taking wing from her outstretched hand.
The longboat makes for a pair of lines dangling from a winch.
Lit by lanterns; no moon is visible beneath the fog.
Smoke hangs heavy above the deck.
Elizabeth's longboat is raised above the deck rail -- pirates spot her, and stare.
One polite fellow steps
forward to offer his hand.
She takes it and steps down.
She huddles, self-conscious in her nightgown and dressing robe.
BOSUN I didn't know we was taking captives.
PINTEL She's invoked the right of parlay...
PINTEL with Captain Barbossa.
ON THE POOP DECK -- an imposing FIGURE in silhouette stands by the wheel, too far away to have heard Pintel's words.
But his head turns at the mention of his name.
The silhouetted figure moves toward the stairs.
A cloud of SMOKE obscures him -- and then, as if he skipped the stairs, he strides out of the SMOKE on the main deck-
This is BARBOSSA.
Despite the bright colors of clothing, definitely not a man you'd want to meet in a dark alley -- or anywhere, for that matter.
Elizabeth, more terrified than ever, cannot look away from his eyes.
But she musters her courage -
ELIZABETH I am here to --
The Bosun SLAPS her.
BOSUN You'll speak when spoken to!
His wrist is grabbed -- painfully -- by Barbossa.
BARBOSSA And you'll not lay a hand on those under the protection of parlay!
BOSUN Aye, sir.
Barbossa releases him.
Turns to Elizabeth, smiles -- it shows both silver and gold teeth.
BARBOSSA My apologies, miss.
BARBOSSA As you were saying, before you were so rudely interrupted?
ELIZABETH Captain Barbossa ...
ELIZABETH I have come to negotiate the cessation of hostilities against Port Royal.
Barbossa is both impressed and amused.
BARBOSSA There was a lot of long words in there, miss, and we're not but humble pirates.
BARBOSSA What is it you want?
ELIZABETH I want you to leave.
ELIZABETH And never come back.
Barbossa and the pirates laugh.
BARBOSSA I am disinclined to acquiesce to your request.
BARBOSSA Means' No.
ELIZABETH Very well.
She quickly slips the medallion off, darts to the side rail, dangles it over the side of the ship.
The pirates go quiet.
ELIZABETH (CONT'D) I'll drop it!
BARBOSSA My holds are bursting with swag.
BARBOSSA That bit of shine matters to me ...
BARBOSSA Why?
ELIZABETH Because it's what you're searching for.
ELIZABETH You've been searching for it for years.
ELIZABETH I recognize this ship.
ELIZABETH I saw it eight years ago, when we made the crossing from England.
BARBOSSA Did you, now?
Elizabeth glares at him.
She's getting nowhere.
ELIZABETH Fine.
ELIZABETH I suppose if this is worthless, there's no reason to keep it.
She flips the medallion up, off her finger -
She catches it by the chain, smiles at him triumphantly.
BARBOSSA (CONT'D) You have a name, missy?
ELIZABETH Elizabeth - (stops herself from saying "Swann"; then:) Turner.
ELIZABETH I'm a maid in the governor's household.
ELIZABETH Barbossa reacts to the name Turner: it confirms what he has suspected.
ELIZABETH The other pirates surreptitiously exchange glances and nods.
BARBOSSA You've got sand, for a maid.
ELIZABETH Thank you, sir.
BARBOSSA And how does a maid come to own a trinket such as that?
BARBOSSA A family heirloom, perhaps?
ELIZABETH Of course.
ELIZABETH I didn't steal it, if that's what you mean.
BARBOSSA No, no, nothing like that.
BARBOSSA Very well.
BARBOSSA You hand that over, we'll put your town to our rudder and ne'er return.
ELIZABETH Can I trust you?
BARBOSSA It's you who invoked the parlay!
BARBOSSA Believe me, Miss, you'd best hand it over, now...
BARBOSSA or these be the last friendly words you'll hear!
Elizabeth hesitates, but she has no choice.
She holds out the medallion.
He grabs it, clutches it in his fist like hope.
ELIZABETH Our bargain.
Barbossa grins devilishly -- but then nods to the Bosun.
BOSUN Still the guns, and stow 'em!
BOSUN Signal the men, set the flags, and make good to clear port!
For the first time since the attack began, the BOOMING of the guns ceases.
Elizabeth is surprised -- and relieved.
The pirates hustle to follow orders.
Barbossa turns away.
ELIZABETH Wait!
ELIZABETH You must return me to shore!
ELIZABETH According to the rules of the Order of the Brethren -
Barbossa wheels on her.
BARBOSSA First.
BARBOSSA Your return to shore was not part of our negotiations nor our agreement, and so I 'must' do nothing.
BARBOSSA Secondly: you must be a pirate for the pirate's code to apply.
BARBOSSA And you're not.
BARBOSSA And thirdly...
the code is more what you'd call guidelines than actual rules.
Welcome aboard the Black Pearl, Miss Turner.
Elizabeth stares in speechless terror -
As the Black Pearl turns out to sea, Elizabeth is led back along the deck to the captain's cabin.
The fog starts to dissipate, turning to a light mist; through it, the Black Pearl makes for the scarlet glow of dawn.
Will comes to, still where he fell, gets to his feet.
He takes in the devastation of Port Royal: the harbor is dotted with burning and sunken ships; buildings are razed and still smolder.
The aftermath of hell on earth.
Will turns, and runs for the Governor's Mansion.
Will races past the smashed doors, into the foyer.
Calls out:
WILL Miss Swann!
WILL Elizabeth!
A terrible silence answers him.
He spots an overturned chair, fallen bookshelf -
Will bursts in, still armed with sword and boarding axe.
WILL They've taken her!
WILL They've taken Elizabeth!
A group stares at him: Swann, Norrington, and Gillette among others, gathered around a map.
The map is so large it drapes over the Governor's desk, the far end supported by a chair.
NORRINGTON We're aware of the situation.
WILL We have to hunt them down -- and save her!
Swann's worry has made him short-tempered.
SWANN Where do you propose we start?
SWANN If you have any information that concerns my daughter, then share it!
SWANN If anyone does, tell me!
SWANN Leave, Mr. Turner.
Murtogg has remembered something.
He ventures it warily:
MURTOGG That Jack Sparrow...
MURTOGG he talked about the Black Pearl.
MULLROY Mentioned it, is more what he did.
MURTOGG Still --
WILL We can ask him where it is -- maybe he can lead us to it!
SWANN That pirate tried to kill my daughter.
SWANN We could never trust a word he said!
WILL We could strike a bargain -
NORRINGTON No.
NORRINGTON The pirates who invaded this fort left Sparrow locked in his cell.
NORRINGTON Ergo, he is not their ally, and therefore of no value.
NORRINGTON We will determine their most likely course, and launch a search mission that sails with the tide.
Will slams the boarding axe into the desk, through the map.
WILL That's not good enough.
WILL This is Elizabeth's life!
Norrington is quick to react; he throws a strong arm across Will's back, and guides him roughly to the door.
NORRINGTON Mr. Turner, this is not the time for rash actions.
NORRINGTON Do not make the mistake of thinking you are the only man here who loves Elizabeth.
NORRINGTON Now, go home.
He opens the door, and then turns away.
Will watches him walk back to the desk.
Will's face sets in resolve, and he leaves.
Jack strains, trying to budge one of the bars.
Even with the damage from the cannon ball, it won't move.
He hears the sound of the door latch -
The door opens, and Will slips in.
Looks around.
Jack lounges on the floor of his cell, apparently relaxed and unconcerned.
Will marches straight up to the bars.
WILL Are you familiar with that ship?
WILL The Black Pearl?
JACK Somewhat.
WILL Where does it make berth?
JACK Surely you've heard the stories?
JACK The Black Pearl sails from the dreaded Isla de Mureta...
JACK an island that cannot be found -- except by those who already know where it is.
WILL The ship's real enough.
WILL So its anchorage must be a real place.
WILL Where is it?
JACK Why ask me?
WILL Because you're a pirate.
JACK And you want to turn pirate yourself?
WILL Never.
WILL They took Miss Swann.
JACK So it is that you found a girl.
JACK Well, if you're intending to brave all and hasten to her rescue and so win fair lady's heart, you'll have to do it alone.
JACK I see no profit in it for me.
Will slams his fist against the bars in frustration.
Jack is surprised at the outburst.
Will thinks ...
makes a decision.
WILL I can get you out of here.
JACK How?
JACK The key's run off.
WILL I helped build these cells.
WILL Those are hook-and-ring hinges.
WILL The proper application of strength, the door'll lift free.
WILL Just calls for the right lever and fulcrum.
Jack watches Will as he speaks, and it dawns on him -- Will is the spitting image of someone he's known in the past.
JACK Your name is Turner.
Will gives him a puzzled look.
WILL Yes.
WILL Will Turner.
Jack grins.
JACK Will Turner...
JACK I'll tell you what, Mr. Turner.
JACK I've changed my mind.
JACK You spring me from this cell, and on pain of death, I'll you to the Black Pearl.
JACK Do we have an accord?
Will gives him a suspicious look.
The deal seems too good.
Jack keeps his hand out, still smiling.
Will shakes it.
WILL Agreed.
JACK Agreed!
Will looks around, figures out what he needs.
He makes a chair his fulcrum, and levers the long bench under the door.
Pushes down -- it's hard work -- but the cell door rises, and then falls forward, CRASHING down on the bench and chair.
Jack is impressed.
He steps out of the cell.
WILL Someone will have heard that.
WILL Hurry.
Will heads for the door.
Jack searches the desk, cupboards.
JACK Not without my effects.
WILL We need to go!
Jack finds his pistol, sword belt, and compass.
Straps on the belt, checks the shot in his pistol.
WILL (CONT'D) Why are you bothering with that?
JACK My business, Will.
JACK As for your business -one question, or there's no use going.
JACK This girl -- what does she mean to you?
JACK How far are you willing to go to save her?
WILL I'd die for her.
JACK Good.
The Jolly Mon, four inches of water in the bottom, squats low in the water, heeled to one side, creaking on its lines.
JACK Ah, now there's a lovely sight!
Jack hops down into the boat.
Prepares to make way.
JACK (CONT'D) I knew the Harbormaster wouldn't report her.
JACK (CONT'D) Honest men are slaves to their conscience, and there's no predicting 'em.
JACK (CONT'D) But you can always trust a dishonest man to stay that way...
Jack notices that Will is standing, frozen on the dock, staring at the boat in dismay.
JACK (CONT'D) Come aboard.
WILL I haven't set foot off dry land I was twelve, when the ship I was on exploded.
WILL It's been a sound policy.
JACK No worries there.
JACK She's far more likely to rot out from under us.
Will steels himself, steps into the boat as if its going to capsize with the slightest movement.
Jack hoists the sail.
JACK (CONT'D) Besides, we are about to better our prospects considerably.
He nods toward the H.M.S. Dauntless, looming in the harbor.
Will whiteknuckles the gunwales.
WILL We're going to steal a ship?
WILL That ship?
JACK Commandeer.
JACK We're going to commandeer a ship.
JACK Nautical term.
WILL It's still against the law.
JACK So's breaking a man out of jail.
JACK Face it, Will: you may say you'll never be a pirate, but you're off to a rip-roaring start.
JACK My advice -- smile and enjoy it.
The Jolly Mon bobs its way across the bay, dwarfed against the H.M.S. Dauntless.
Will holds a stay line with iron fists.
WILL This is either crazy, or brilliant.
JACK Remarkable how often those two traits coincide.
The Jolly Man nears the rudder of the much larger ship -
There's been a breakdown in discipline; about a dozen Navy sailors are gathered together on the main deck, playing dice.
Murtogg and Mullroy among them.
Suddenly, Jack and Will jump out, into the open -
brandishing pistols.
JACK Everybody stay calm.
JACK We're taking over the ship!
WILL Aye!
WILL Avast!
Jack gives him a look, shakes his head: don't do that.
The sailors all look at them -- and then burst out LAUGHING.
They grin, shake their heads.
Jack stands there, grinning with them -- but his gun is still level.
The Lieutenant, GILLETTE, steps forward.
GILLETTE You're serious about this.
Jack moves his pistol across, points it at Gillette.
JACK Dead serious.
GILLETTE You understand this ship cannot be crewed by only two men.
GILLETTE You'll never make it out of the bay.
JACK We'll see about that.
More guffaws from the crew.
A couple sailors move forward, hands on swords -- Gillette holds up a hand.
GILLETTE Sir, I'll not see any of my men killed or wounded in this foolish enterprise.
JACK Fine by me.
JACK We brought you a nice little boat, so you can all get back to shore, safe and sound.
GILLETTE Agreed.
GILLETTE You have the momentary advantage, sir.
GILLETTE But I will see you smile from the yard arm sir.
JACK As likely as not.
JACK Will, short up the anchor, we've got ourselves a ship!
Sailors make their way down a rope ladder, crowd onto the Jolly Mon.
Will pushes hard against the windlass, to no avail ...
the anchor is too heavy for one man.
Jack notices.
JACK A little help?
Gillette shrugs, gestures to Murtogg and Mullroy.
The three men throw their weight into the windlass, and it turns.
Jack's pistol is on them the whole time.
MURTOGG I can't believe he's doing this.
The windless turns, bringing Mullroy into view.
MULLROY You didn't believe he was telling the truth, either.
The windless turns some more, and there's Gillette.
GILLETTE Do you have any idea, boy, what you're doing?
Another quarter turn -
WILL No.
Jack and Will crank a capstan, raising the forward jib sail.
It luffs and billows out.
The huge ship inches forward slowly, pulled by just the one sail.
Jack grins.
JACK Lookee there, mate!
JACK We're underway!
Norrington moves along, concentrating on a manifest.
Alongside him is governor Swann, who glances over -
Sees the tiny Jolly Mon headed toward them, riding low in the water, overloaded with sailors.
Beyond that, the Dauntless sails -- albeit slowly -- for open waters.
SWANN Commodore --
NORRINGTON A moment.
SWANN But --
NORRINGTON Please.
SWANN Dammit, man, it appears someone is stealing your ship!
Norrington glances out at the bay.
Sure enough, the Dauntless is on the move.
Norrington takes a brass telescope from his belt, opens it, trains it on --
The main deck.
He picks out Will -
NORRINGTON Rash, Turner, too rash.
-- then spots Jack, at the wheel.
Lowers the telescope.
NORRINGTON (CONT'D) That is, without doubt, the worst pirate I have ever seen.
Out in the open sea, Jack leans on the wheel, relaxed; not much sailing to do with a following wind.
Will looks back -
WILL They're coming!
He points: the sails of the Interceptor fill out, and the ship cuts through the water toward them-
Norrington's smaller ship quickly comes alongside the slowmoving Dauntless.
Its decks appear empty.
Grappling hooks are thrown, and sailors draw the two ships together.
Norrington's men swarm across.
NORRINGTON Search every cabin, every hold, down to the bilges!
PULL BACK, away from the Dauntless, and past the railing of the Interceptor, where a single SENTRY stands watch -- and we find a soaked Jack and Will as they climb up over the side of the smaller ship, unseen.
Jack tackles the Sentry from behind, covers hi1rmouth.
JACK Can you swim?
JACK Can.
JACK You.
JACK Swim?
Jack removes his hand.
SENTRY Of course, sir.
SENTRY Like a fish.
SENTRY I grew up summers living in Dover, with my uncle -
JACK Good.
Jack lifts the man up, throws him overboard.
Quickly unties the ropes to the grappling hooks.
Will cranks the capstan bars, raising the foresail -
Norrington emerges from a gangway -- and sees his other ship moving away.
NORRINGTON Sailors!
NORRINGTON Back to the Interceptor!
But the distance is already too great.
One brave sailor tries to swing across on a rope, Errol-Flynn style, but falls short with a splash.
Jack waves, and shouts across the distance -
JACK Thank you, Commodore, for getting our ship ready to make way!
JACK We'd've had a hard time of it by ourselves!
Norrington seethes, but his order to Gillette is measured:
NORRINGTON Raise the sails.
GILLETTE The wind is quarter from astern ...
GILLETTE by the time we're underway, we'll never catch them.
NORRINGTON We need only to come about, to put them in range of the long nines.
Gillette looks surprised at the order -- but relays it.
GILLETTE Hands!
GILLETTE Come about!
GILLETTE Jackets off the cannons!
GILLETTE We are to fire on our own ship?
NORRINGTON Better to see it at the bottom of the sea than in the hands of a pirate.
The STEERSMAN turns the wheel.
The Dauntless' course does not change one whit.
STEERSMAN Captain, there's a problem.
The Steersman spins the wheel.
It goes round and round, with no signs of slowing.
STEERSMAN (CONT'D) He's disabled the rudder chain, sir.
NORRINGTON So it would seem.
The Interceptor dwindles with distance.
Gillette watches it go, with some degree of admiration.
GILLETTE He's got to be the best pirate I've ever seen.
Norrington reaches out, stops the spinning ship's wheel.
NORRINGTON So it would seem.
The Interceptor makes for the horizon line.
A SLOW DISSOLVE and with the time passage, the ship is gone; the sky turns a deep twilight blue -
-- with the fat white moon riding just above the horizon.
Suddenly, the edge of a black sail cuts into the foreground, accompanied by the ROAR of the wind and the SNAP of canvas -
Elizabeth stalks the cabin.
Pintel enters, carrying a black silk dress.
PINTEL You'll be dining with the Captain, and he requests you wear this.
ELIZABETH Tell the captain that I am disinclined to acquiesce to his request.
PINTEL He said you say that!
PINTEL He also said if that be the case, you'll be dining with the crew, and you'll be naked.
Angry, Elizabeth holds out her hand.
Pintel's grin fades.
PINTEL (CONT'D) Fine.
He exits, pouting.
Elizabeth examines the dress -
Barbossa enters, followed by PIRATES carrying trays of food, wine, table setting, etc.
Elizabeth stands at the small table in the dress -- lovely.
BARBOSSA Maid or not, it fits you.
ELIZABETH Dare I ask the fate of its previous owner?
BARBOSSA Now, none of that.
BARBOSSA Please dig in.
The table is set.
Elizabeth sits, cuts a tiny piece of meat, eats it daintily.
BARBOSSA (CONT'D) No need to stand on ceremony, and no call to impress anyone.
BARBOSSA (CONT'D) You must be hungry.
Elizabeth drops the pretense: she's starving, and begins to eat like it.
Barbossa watches her intently.
BARBOSSA (CONT'D) Try the wine.
Elizabeth does, a huge swig; she tears off a hunk of bread, devours it.
BARBOSSA (CONT'D) And the apples -- one of those next.
She starts to bite into the apple -- stops.
She is suddenly aware of Barbossa's gaze -- and that he is not eating.
ELIZABETH It's poisoned!
She shoves her plate away -- and takes the opportunity to palm her knife.
Barbossa LAUGHS.
BARBOSSA Oh, there would be no sense in killing you, Miss Turner.
ELIZABETH Then why aren't you eating?
BARBOSSA Would that I could.
He produces the medallion, lets it dangle from his fingers.
BARBOSSA (CONT'D) Do you not know what this is, then?
ELIZABETH It's a pirate medallion.
BARBOSSA It's a piece of the treasure of Isla de Muerta .
Elizabeth gives an infinitesimal shrug, intrigued despite herself.
BARBOSSA (CONT 'D) Ah, so you don't know as much as you pretend.
BARBOSSA (CONT 'D) Back when Cortes was cutting a great bloody swath through the New World, a high priest gave.
BARBOSSA (CONT 'D) him all the gold they had, with one condition: that he spare the people's lives.
BARBOSSA (CONT 'D) Of course, Cortes being Cortes, he didn't.
BARBOSSA (CONT 'D) He'd've made a great pirate, that one.
Barbossa stands, moves to a shelf.
Puts a key to a medium- sized polished wooden box -- the Captain's chest.
Opens it.
BARBOSSA (CONT'D) So the priest, with his dying breath, called on the power of the blood of his people, and put on the gold a curse.
BARBOSSA (CONT'D) If anyone took so much as a single piece, as he was compelled by greed, by greed he would be consumed.
Inside the chest are charts, some gold, a sextant -- and a
few pages of a Mayan CODEX, pieces of tree bark inscribed with Mayan glyphs.
Barbossa removes them carefully, sets them on the table.
Pours over them.
BARBOSSA (CONT'D) Within a day of leaving port for Spain, the treasure ship carrying the gold ...
BARBOSSA (CONT'D) something went wrong.
BARBOSSA (CONT'D) The ship run aground, every man aboard dead, save one.
BARBOSSA (CONT'D) He survived long enough to hide the gold ashore.
BARBOSSA (CONT'D) Over time, the dark magic of the curse seeped into the place, making it a cursed island.
BARBOSSA (CONT'D) An island of death.
BARBOSSA (CONT'D) Isla de Muerta.
He looks up.
Elizabeth has been rapt, involved in the story -but feigns a dismissive attitude.
ELIZABETH That's all very interesting, but I hardly believe in ghost stories any more.
Barbossa is angry.
He stands, sweeps the food off the table.
BARBOSSA You idiot girl!
BARBOSSA It's no make- believe!
BARBOSSA My crew and I, we found the gold, and we did more than take one piece, we took it all.
BARBOSSA Rich men we were and we spent it and traded it and gave it away in exchange
for drink and food and pleasant company.
But we found out: the drink could not sate us, and the food turned to ashes in our mouths, and no amount of pleasant company could ease our torment.
We are cursed men, Miss Turner,
condemned, to be forever consumed by our own greed.
Gold calls to UB, always, and we are driven, always, to find more, and add it to the treasure.
Barbossa picks up the priceless Codex.
Crushes them in his fist.
BARBOSSA (CONT'D) There is but one way to remove the curse.
BARBOSSA (CONT'D) All of the scattered pieces of the treasure must be restored in full, and the blood repaid.
BARBOSSA (CONT'D) We've recovered every piece -- save for this.
BARBOSSA (CONT'D) And as for the blood ...
BARBOSSA (CONT'D) that's what we have you for.
BARBOSSA (CONT'D) And that's why there's no sense in killing you.
BARBOSSA (CONT'D) Yet.
Elizabeth stares at him, horrified.
Using the toe of his boot, Barbossa flips an apple up off the floor, catches it, extends it to Elizabeth.
BARBOSSA (CONT'D) Apple?
Elizabeth slowly reaches for the apple -- and then comes up out of her chair, trying to run around Barbossa_ They struggle briefly, and then suddenly he shoves her away-
Elizabeth's stolen KNIFE is buried in Barbossa's chest, to the hilt --
Barbossa is completely unaffected.
He opens his shirt to get a better look at the knife, pulls it out with little effort.
There is BLOOD on the blade, but none anywhere else.
BARBOSSA (CONT'D) I'm curious -- after killing me, what is it you were planning to do next?
Elizabeth backs away, whirls and barrels out the door -
-- Elizabeth comes to dead stop.
She stares, her jaw working, trying to scream but unable to -
The pirate crew works at their stations, coiling lines, navigating the ship, swabbing decks -- but where the moonlight falls across their bodies, they are nauqht but
Elizabeth turns away from the sight -
Barbossa stands just inside the doorway, out of the moonlight.
He grabs her roughly by the shoulders and jerks her back around -- Elizabeth shuts her eyes -
BARBOSSA Look!
BARBOSSA LOOK!
BARBOSSA The moonlight shows us for what we really are!
BARBOSSA We are not among the living and so we cannot die -
He spins her back around to face him -- he leans forward, putting his face in the moonlight, turning it into a gleaming SKULL with gold and silver teeth -
BARBOSSA (CONT'D) -- but neither are we dead!
BARBOSSA (CONT'D) We have all the desires of the living, but cannot satisfy them!
BARBOSSA (CONT'D) Ten years I have been parched of thirst, and unable to quench it!
BARBOSSA (CONT'D) Ten years, I have been starving to death -- and haven't died!
BARBOSSA (CONT'D) And I have not felt anything for ten years ...
BARBOSSA (CONT'D) Not the wind on my face, nor the spray of the sea ...
BARBOSSA (CONT'D) ...
BARBOSSA (CONT'D) nor the flesh of a woman ...
Elizabeth flinches away from the skeletal hand.
It drops away -- he takes a bottle of wine from the opened case beside the cabin door, uncorks it with his teeth, raises it -
BARBOSSA (CONT'D) You'd best start believing in ghost stories, Miss Turner.
BARBOSSA (CONT'D) Because now you're in one.
He tilts the bottle and drinks -- it runs over his jaw, through his rib cage, drenching his clothes.
Elizabeth darts around him, back into the cabin, and shuts the door.
Barbossa hurls the bottle away.
Elizabeth huddles in the far corner of the cabin, terrified.
The Interceptor cuts across the waves.
Jack at the wheel; Will tightens a line, moves back astern.
Will sharpens his sword with a whetstone: shhhk -- shhhk ...
JACK For a man whose made an industry of avoiding boats, you're a quick study.
WILL I worked passage from England as a cabin boy.
WILL After my mother passed, I came out here ...
WILL looking for my father.
JACK Is that so?
WILL My father.
WILL William Turner?
Jack says nothing.
Will has lost the patience for guile.
WILL ( CONT ' D) I'm not a simpleton.
WILL ( CONT ' D) At the jail - - it was only after you learned my name that you agreed to help.
WILL ( CONT ' D) Since that's what I wanted, I didn't press the matter.
WILL ( CONT ' D) But now -
{an accusation}
You knew my father.
Jack considers his reply -- settles on 'truth.'
JACK I knew him.
JACK Probably one of the few who knew him as William Turner.
JACK Most everyone just called him Bill, or 'Bootstrap' Bill.
WILL 'Bootstrap?'
JACK Good man.
JACK Good pirate.
JACK And clever -"- I never met anyone with as clever a mind and hands as him.
JACK When you were puzzling out that cell door, it was like seeing his twin.
WILL That's not true.
JACK I swear, you look just like him.
WILL It's not true that my father was a pirate.
JACK Figured you wouldn't want to hear it.
WILL He was a merchant marine!
WILL He was a respectable man who obeyed the law, and followed the rules--
JACK You think your father is the only man who ever lived the Glasgow life, telling folk one thing, and then going off to do another?
JACK There's quite a few who come here, hoping to amass enough swag to ease the burdens of respectable
JACK life.
JACK And they're all 'merchant marines.'
WILL My father did not think of my mother -his family -- as a burden.
JACK Sure -- because he could always go pirating.
WILL My father -- was not -- a pirate!
Will's sword is out, levelled at Jack.
Jack gives him a disbelieving look, sighs.
JACK Put it away, Will.
JACK It's not worth getting beat again.
WILL You didn't beat me.
WILL You ignored the rules of engagement.
WILL In a fair fight, I'd kill you.
JACK Then that's not much incentive for me to fight fair, is it?
He kicks a lever on a wench.
The sail boom whips around and slams Will in the chest -- sweeping him off the ship.
His sword clatters onto the deck.
Will dangles above the water.
Jack slips a loop of rope around the wheel to hold the course.
Picks up the sword -- and pokes at Will with it.
Will hand-over-hands away from the blade, to the end of the boom.
JACK ( CONT ' D) As long as you're just hanging there, pay attention.
JACK ( CONT ' D) Must, Should, do, don't, shall, shall not -- those are just suggestions.
JACK ( CONT ' D) There are only two absolute rules.
JACK (CONT'D) What a man can do.
JACK (CONT'D) And what a man can I t do.
Will looks away, not interested.
JACK (CONT'D) For instance: you can accept that your father was a pirate and still a good man...
JACK (CONT'D) or you can't.
JACK (CONT'D) Now me, I can sail this ship to Tortuga, by myself.
JACK (CONT'D) But I can't just let you drown.
Jack swings the boom back in.
Will drops to the deck.
Jack holds the hilt of the sword out.
Will takes it.
Glares at Jack, considers what he'll do next.
Jack watches him coolly.
Will turns and strides to his spot on the deck, sits down, and resumes sharpening his sword: shhhk -- shhhk -- shhhk ...
Jack breathes silent sigh of relief.
Notices his hand is shaking -- he takes the wheel.
WILL Tortuga?
JACK Oh -- did I forget to mention that?
A dank and dirty port, where the tides seem to have swept together the scum of the Caribbean -- pirates, privateers, prostitutes, thieves, and drunkards.
With its cantered, rotting docks, weatherbeaten buildings, and odd assortment of livestock running free -- a donkey, chickens, etc.
-- it is far less civilized than Port Royal.
Jack and Will move through the crowd.
A REDHEADED woman turns her head -- she has noticed Jack.
JACK We need a crew.
JACK We can manage the ship between islands, but the open sea, that's another matter -
Suddenly the Redhead SLAPS Jack, hard.
Satisfied, she turns and strides off.
Will ignores her.
WILL Just do it quickly.
JACK Don't worry.
JACK I've already got my Quartermaster -- there!
Jack leads Will toward a pub: the Faithful Bride, the emblem over the door a politically incorrect painting of a smiling woman holding a bouquet in her chained-and-manacled hands.
Jack pulls open the door; Will goes inside passing a pretty ASIAN women coming out -- she sees Jack and immediately SLAPS him, cursing something in Chinese.
Jack backs away -
Jack closes the door on the woman, joins Will.
They take in the place -- it is populated with a slightly higher class of scum.
Jack spots a BARTENDER, smiles, moves forward -
--and is suddenly DECKED by a waitress.
This is ANAMARIA, tall, strong, tough; she didn't spill a drink off her tray.
ANAMARIA You stole my boat.
JACK AnaMaria!
JACK Have you seen Gibbs?
JACK I need to put together -
She SLAPS him again.
Will shakes his head, heads for the bar.
Jack gets up.
JACK (CONT'D) Borrowed.
JACK (CONT'D) Borrowed your boat.
JACK (CONT'D) Without permission.
AnaMaria charges; Jack backs away, puts a table between them.
She chases him around the table, still carrying the tray.
ANAMARIA My dory.
ANAMARIA The Jolly Mon.
ANAMARIA Where is it?
JACK Safe!
JACK At Port Royal.
JACK With the Royal Navy.
ANAMARIA That boat is my livelihood!
JACK You'll get it back.
JACK Or one better.
ANAMARIA I will.
Away from them, a PATRON calls for his food.
AnaMaria scowls at Jack, moves away -- comes back for.
one more
WILL Jack!
WILL Over here!
AT THE BAR, Will has spoken to the Bartender.
Jack arrives, rubbing his chin.
WILL (CONT'D) He knows Gibbs.
The Bartender nods 'yes.' Then nods 'out back.' Then produces a water bucket from behind the bar.
Jack and Will exchange a look,-and Jack takes the bucket.
A drunken man lays in the mud, having a friendly conversation with two pigs.
He wears an old tattered Navy jacket.
A sudden SPRAY OF WATER splashes across his face, revealing: this is old JOSHAMEE GIBBS (the man who told
pirate stories to Elizabeth when she was a child).
He sputters and roars:
GIBBS Curse you for breathing, you slack-jawed idiot
GIBBS Mother's love, Jack, you know better than to wake a man when he's sleeping.
GIBBS It's bad luck!
JACK Well, fortunately, I know how to counter it.
JACK The man who did the waking buys the man who was sleeping a drink, and the man who was sleeping it drinks it while listening to a proposition.
GIBBS Aye, that'll about do it.
Jack helps Gibbs to his feet -- and then Gibbs is hit with a second wave of water.
Will stands there with the bucket.
GIBBS (CONT'D) Blast it, I'm already awake!
WILL I know.
WILL That was for the smell.
Jack and Gibbs sit at a table in the shadows, a single candle illumining them, speaking in hushed voices.
Will is away from them, at the door, hand on sword, keeping a look- out.
A tankard is set down.
Gibbs lifts it to take a swig -
JACK Just the one.
Gibbs pauses.
He takes a dainty sip.
GIBBS Make it_ast, then.
GIBBS Now, what's the nature of this venture of yours?
JACK First -- have you found me a crew?
GIBBS Oh, there's a hard tale, Jack.
GIBBS Most of the decent pirates in town won't sail with you -- seem to think you're a jinx.
JACK Now where, I wonder, would they have gotten that idea?
Gibbs evades answering by taking a long sip.
Jack leans forward.
Gibbs leans forward.
JACK (CONT'D) I'm going after the Black Pearl.
Gibbs straightens up like he's been hit.
He stares.
He reaches for the drink as if to down it -- but then sets it back down.
He leans forwards again.
Jack has not moved.
GIBBS Say again?
JACK Ilm going after the Black Pearl.
JACK I know where its going to be, and I'm going to take it.
GIBBS Jack, it's a fool's errand: You've heard the tales they tell about the Pearl.
JACK Aye, and that's why I know where it's going to be, and that's why I know what Barbossa is up to.
JACK All I need is a crew.
GIBBS A fool's errand.
JACK Not if the fool has something Barbossa wants.
JACK Something he needs.
GIBBS And you've got that, have you?
ANGLE ON: Jack, as he smiles enigmatically, and shifts his eyes' -- behind him, Will, still on guard, glares a sailor away from the table.
JACK Back there, guarding the door is the son of old Bootstrap Bill Turner.
Gibbs' eyes widen over the edge of the tankard.
Peers at Will.
Then smiles, with more missing teeth than good ones.
GIBBS Well, lookee there.
GIBBS I'll allow you may be onto something, Jack.
GIBBS There's bound to be sailors on this rock crazy as you.
GIBBS I'll find some men.
Gibbs downs the drink, SLAMS the tankard on the table.
Will reacts to the sound, draws both sword and dagger, kicks over a table for cover, and whirls on anyone who moves.
GIBBS (CONT'D) Kid's a bit of a stick, isn't he?
JACK That he is.
On the docks, a disheveled, motley and weatherbeaten group of about a dozen swabs stand in a ragged line-up.
GIBBS Feast your eyes, Cap'n.
GIBBS All of 'em good sea-faring men, faithful hands before the mast, every one worth his salt --
GIBBS -- and crazy, to boot.
Jack holds up a hand -- enough.
He moves down the line, Gibbs at his side.
Then he notices AnaMaria in line, dressed like a man, He raises an eyebrow.
ANAMARIA You owe me a boat.
Jack nods, continues.
One sailor is quite fat, another thin and sickly.
Jack is not happy with his choices.
He stops in front of COTTON, a short sailor with a large, colorful PARROT on his shoulder.
Jack raises an eyebrow.
GIBBS Cotton here is mute, sir.
GIBBS Poor devil had his tongue cut out --
Cotton opens his mouth to show this -- Jack grimaces.
GIBBS (CONT'D) -- so he went and trained the parrot to do the talking for him, nobody knows how.
GIBBS (CONT'D) Nobody knows the parrot's name, neither, so we just call it 'Cotton's parrot.'
Jack decides to test this.
JACK Mr. Cotton.
JACK Do you have the courage and fortitude to follow orders and stay true, in the face danger, and almost certain death?
Cotton lifts the parrot off his shoulder, raises it --
COTTON'S PARROT Wind in your SAILS!
COTTON'S PARROT Wind in your SAILS!
GIBBS Mostly, that seem to mean 'yes.'
Cotton nods vigorously, lowers the parrot, and it goes silent.
Jack shakes his head.
Steps back.
JACK That goes for the rest of you!
JACK Danger and near certain death.
JACK For we are to sail for the Isla de Muerta, to rescue the daughter of Governor Swann.
JACK An equal share of the reward shall be -
Jack hears movement, looks back -- several potential crew members back away in fright; first one, then another, turn and run, followed by more.
Soon just a half dozen are left, including Cotton (with parrot) -- and AnaMaria.
WILL Shut up, before you lose them all!
JACK These are the only ones worth having.
JACK And we're going to need them-
A FLASH of lightening and the CRACK of thunder.
The canvas of every sail is stretched taut.
The ship rocks as it drops into the valley of huge swell, climbs up the other side.
On board, the new crew members scurry about their tasks, pulling lines and trimming sails.
Excellent sailors, it takes everything they have to keep the ship afloat.
AnaMaria is at the helm.
Gibbs staggers along the deck.
GIBBS That fool will have us lose the canvas, and the masts besides!
On Jack, a ROARING wind blowing back his hair, eyes intent on their course.
Gibbs climbs the tilted deck toward him.
GIBBS (CONT'D) Werd best drop canvas, sirl
JACK She can hold a bit longer.
The wind picks up, howling.
Jack smiles.
GIBBS What's in your head to put you in such a fine mood?
JACK We're catching up!
Jack turns back to the sea, enjoying himself.
Gibbs stares at him like he's a crazy man.'
The sound of RAIN pounds down on the deck above - - then suddenly stops.
Elizabeth moves to the stern windows, looks out at the rolling sea below -- no escape there.
She hears the sound of a VQICE calling, gazes up, wondering -
High on the main mast, Twigg cups his hands to his face, calls down:
TWIGG Isla de Muerta!
TWIGG Isla de Muerta, off the port bow!
ON DECK, Barbossa moves to the rail.
The storm clouds are breaking up.
On the horizon is a dark, ominous shape: ISLA DE MUERTA.
Mostly sheer unfriendly cliffs that shoot straight into the water.
It is surrounded by a slate grey sea.
Barbossa grasps the rail with both hands, his expression a mixture of loathing and fear.
Jacoby approaches, hesitant.
JACOBY Orders, Captain?
BARBOSSA Bring her in, not too close.
BARBOSSA I won't brave the reef, not until high tide.
BARBOSSA We lay anchor before dark.
Jacoby nods, backs away.
Barbossa continues to stare -
BARBOSSA (CONT'D) ...
BARBOSSA (CONT'D) that is, if it first doesn't sink back down to hell from where it came.
The Interceptor, on open waters, glorious, her white sails set wing-to-wing.
CLOSE ON: Jack's compass, cradled in both hands.
Jack leans over and studies it -- almost like he's praying.
ON THE COMPASS -- the face shows old-fashioned rose petal style direction markers below a quivering indicator that settles on -- southeast.
JACK Bear three points starboard.
AnaMaria turns the wheel, adjusting course.
The ship leans into the new direction.
Jack looks down -
ON THE COMPASS -- where the indicator spins, reverses, settles on -- northeast.
JACK (CONT'D) Six points port!
AnaMaria frowns, but follows the order, turns the wheel back, and the ship responds.
Will works on deck, coiling a rope -- but he watches Jack and AnaMaria, clearly not happy.
Gibbs hobbles up.
GIBBS Left handed-ropes are coiled against the sun, or it's bad luck!
GIBBS Anty-clockwise.
Gibbs takes over the task.
The ship shifts course again.
Will has had enough.
WILL How do we expect to find an island no one can find -- with a compass that doesn't work?
GIBBS Now, lad, just because it don't point north don't mean it don't work.
GIBBS That compass gives bearings to the Isla de Muerta, wherever it may lie.
WILL Really?
WILL So ...
WILL what's the story on the pistol?
Gibbs settles in, happy to have a willing listener.
GIBBS I'll tell lee.
GIBBS Now, Jack Sparrow has an honest streak in him, and that's where the whole problem starts.
GIBBS This was when he was Captain of the Black Pearl -
WILL What?
WILL He never told me that.
GIBBS Ah -- he's learned, then.
GIBBS Plays things more close to the vest.
GIBBS See, Jack was a cartographer, back in Old England.
GIBBS Somehow I he came by the money to commission the Pearl.
GIBBS Hired himself a crew, promised each man an equal share.
GIBBS So, they're forty days out, and the First Mate says, everything's an equal share, that should mean the location of the island, too.
GIBBS So Jack gave up the bearings.
GIBBS That night, there was mutiny.
Gibbs voice is a whisper, now, so Will has to lean closer.
GIBBS (CONT'D) Jack gave hisself up for the sake of his loyal crewmen.
GIBBS (CONT'D) He was marooned on an island, left there to die.
WILL How did he get off the island?
JACK I didn't!
Will and Gibbs jump.
Jack is right there beside them.
JACK (CONT'D) My body's still there, rotting away, and I am but a ghost!
Will and Gibbs aren't sure what to make of that.
Jack laughs.
GIBBS How did you get off the island?
JACK Ah, that's a dark and unpleasant tale, best left untold.
He starts off.
WILL Wait -- what about the pistol?
JACK The pistol.
JACK When a pirate is marooned, Will, he's given a pistol with a single shot.
JACK No good for hunting, or surviving, really.
JACK But after three weeks of starvation and thirst -- the option of that pistol begins to look good.
Jack lets this sink in.
He pulls out the pistol, raises it.
JACK (CONT'D) But I survived.
JACK (CONT'D) And I still have that single shot.
JACK (CONT'D) It's meant for one man.
JACK (CONT'D) My mutinous first mate -
WILL Barbossa.
Jack shoots a glance at Will -- nods, and moves away.
On Barbossa, face upturned.
No expression in his eyes.
Around him a group of pirates, Elizabeth among them, stand as still as stones, in front of a dark cave opening.
Their faces look upward, their total lack of movement disconcerting.
Above the cave, on a hillock, the pirate Koehler gazes out toward the horizon.
Slowly he TRANSFORMS, head-to-toe, from pirate to SKELETON-
The MOON has climbed free of the storm clouds, rising large.
and full on the horizon.
The skeleton turns -
KOEHLER Moonrise, Captain!
KOEHLER First night of full.
BARBOSSA Hah!
BARBOSSA Be mindful of pits and crevasses.
BARBOSSA Stay together.
He takes a torch.
Moves into the cave.
The pirates follow.
The group keeps together under the firelight.
The path leads between boulders on a slope downhill.
From the echoes and shadows, it's clear the cave system must be huge.
Elizabeth glances over -- the torches illumine caverns off to the side -- and just the edge of a mound of coins.
Clearly there is more, but the rest is lost in darkness.
Twigg, gazing upward in wonder, moves a few feet away from the group.
Barbossa grabs him as he nears a chasm.
BARBOSSA Careful, mate.
BARBOSSA Fall down there, you'd die and miss Judgement Day -- for not even the Lord himself'll come look for you here.
Barbossa lets go, and moves on, descending down, twisting and turning, but always down -
Cotton pulls a sail line, looks out -- sees something.
He lifts the parrot off his shoulder, strokes it along the back.
COTTON'S PARROT Land HO!
COTTON'S PARROT Land HO!
COTTON'S PARROT LAND ho!
COTTON'S PARROT LAND ho!
Indeed, the faint outline of Isla de Muerta is in the distance on the port side.
Will stands, excited, jumps onto the rigging for a better look.
But AnaMaria, at the helm, stares at Cotton, and the parrot.
ANAMARIA How does he do that?
JACK They'll be anchored on the lee side.
JACK Haul your wind, and keep to the weather of the island -
Flickering torchlight.
Pirates stoop low to enter a cavern -
-- and revealed is the spectacular treasure of Isla de
Muerta: overflowing ,chests of coins, gold and silver ingots, jewelry, objects d' art, jade and ivory, brightly colored silks, furniture, jewels and pearls; mirrors and swords -anything and everything of value that might be carried by ship, is here.
The pirates move through, Elizabeth can't help but gaze in wonder.
ELIZABETH The curse drove you to gather this?
BARBOSSA Aye.
BARBOSSA And not a bit of it any use to us, only hoarded.
BARBOSSA But it will drive us no longer.
Elizabeth pauses, staring at herself in a jewel-encrusted mirror -- and then is pushed along by the pirates.
The Interceptor lies at anchor in the distance.
Closer, Jack and will row away from the larger vessel in a small longboat, toward the rocky shore.
The RUSH of a waterfall grows louder.
Will looks: ahead of them is a black CAVE MOUTH, right at water level.
WILL What's that?
JACK Depends.
WILL On what?
JACK On whether the stories are all true.
JACK If they are, that's a waterfall that spills over at high tide, with a short drop to an underground lagoon.
JACK If not -
By now, the moving water tugs on the longboat, and they are sucked in --
JACK (CONT'D) -- well, too late.
The boat rushes forward, plunges into the darkness -
-- the longboat takes a harrowing drop over a short waterfall ...
but then lands safely in a gorgeous underwater lagoon, floats lazily toward a sandy shore.
JACK Chalk one up for the stories.
Will leaps out into the water, pulls the boat ashore -
The pirate group reaches the end of a small chamber of mostly jewels and pearl piled around a large bed -
-- and then emerge into the largest cavern of all, also crammed with treasure, including several mountains of gold coins that reach the ceiling.
Treasure everywhere -
Except for one spot in the center.
A hole in the ceiling lets in a column of moonlight, which illumines:
A stone chest, lid pushed back, decorated with carved Aztec glyphs, filled with gold coins identical to Will's medallion.
A sharp stone knife lies on top.
In front of it, buried in the sand is a skeleton -- and this one doesn't look like it's going to move ever again, judging by the sword in its back.
A crab scurries away from it as the group approaches.
BARBOSSA Here we stand before the cursed treasure of Cortez himself.
BARBOSSA Won by blood, it demands blood in return.
All eyes turn -- onto Elizabeth.
Pintle takes the stone knife from the chest, approaches her.
Elizabeth shrinks back, but is held by two other pirates.
Pintel grins.
Grabs her by the wrist.
She turns her head away, shuts her eyes.
Pintle raises the knife ...
...
and then very carefully, daintily, uses just the sharp tip of the knife to just prick!
Elizabeth's finger.
One tiny red drop of blood appears, and drips down onto the medallion.
Elizabeth opens her eyes, surprised.
PINTEL What did you expect?
PINTEL We're all gentlemen here, right and proper.
The pirates laugh.
Barbossa takes the medallion, grins at Elizabeth.
BARBOSSA You know the first thing I'm going to do after the curse is lifted?
BARBOSSA Eat a whole bushel of apples.
Barbossa approaches the chest, shining in the beam of
moonlight.
BARBOSSA (CONT'D) What was begun by blood, let blood now end!
He tosses the gold medallion onto the others.
The pirates tense, waiting, expectant.
A long beat.
They all look at each other, look at themselves.
Nothing happens.
KOEHLER Did it work?
DEADEYE I don't feel no different.
JACOBY How do we tell?
Barbossa frowns, draws his pistol, and SHOOTS the pirate next to him -- Jacoby -- square in the chest.
Jacoby reacts in shock, grabs his chest ...
but doesn't die.
KOEHLER You're not dead.
JACOBY No.
JACOBY He shot me!
TWIGG It didn't work!
TWIGG The curse is still upon us!
Barbossa searches his mind for an answer ...
turns to Elizabeth.
BARBOSSA You.
BARBOSSA Maid.
BARBOSSA Your father.
BARBOSSA What was his name?!
BARBOSSA Was your father William Turner?!
Elizabeth takes time to smile before answering:
ELIZABETH No.
The pirates cry out in alarm.
Barbossa gathers himself, getting his rage under steely control.
BARBOSSA Where's his child?
BARBOSSA The child that sailed from England eight years ago, the child who is the real owner of that medallion, the child in whose veins flows the blood of William Turner?!
BARBOSSA Where?
Barbossa SLAPS her hard across the face, sending her sprawling.
JACOBY You brought us the wrong person!
PINTEL She had the medallion!
PINTEL She's the right age.
PINTEL She said her name was Turner!
TWIGG You brought us here for nothing?
Barbossa whirls on him --
BARBOSSA If you had sailed with Morgan for ten years like I have, you'd know not to question me!
Elizabeth sits up, watching the pirates argue, for a moment unnoticed.
Suddenly, a scabbard comes down, right above her.
Startled, Elizabeth looks up --
-- Will is at the top of a mound of coins, reaching down with his scabbard for her to grab onto.
Elizabeth quickly leans forward, takes the bloodied medallion from the pile.
Reaches back, grabs the scabbard.
Will pulls her up -
BARBOSSA (CONT'D) If any coward here dare challenge me, let him speak!
BARBOSSA (CONT'D) Any more talk, I'll chain ye to a cannon and send ye to the watery depths!
A sound catches his attention -- coins falling.
He looks up, sees Will and Elizabeth at the top of the treasure stack.
ATOP THE STACK, Will grabs a large shield, flings them forward -- the two ride down the mountain of coins on the far side, slide through a small opening -
Behind them, loose coins from their slide come down in an avalanche, sealing the entrance.
Elizabeth jumps up, silver platter in hand, ready to swing -Jack catches her before she can do any damage.
They recognize each other.
ELIZABETH You?!
JACK Me!
ELIZABETH You're in league with Barbossa!
JACK No, I'm -- rescuing you.
Elizabeth can't comprehend that one.
ELIZABETH You?!
Will gains his footing in the rubble.
WILL Miss Swann!
WILL We're here to rescue you!
WILL It's going badly!
JACK This way!
They race off, toward a bit of moonlight -
The three climb up a dark crevasse that leads out onto the island.
Will takes Elizabeth's hand, helps her.
WILL I'm glad we got here in time.
ELIZABETH Truthfully -- you were a bit late.
JACK The trick isn't getting here, it's getting away.
As if on cue, they hear the yells of pirates, coming closer.
They take off -
The three race through the rocks, the sounds of pursuit close behind.
Suddenly Jack stops.
ELIZABETH Come on!
JACK No.
JACK This won't work.
JACK I'll stay behind, and fight them.
JACK You go on.
Will and Elizabeth stare at him.
WILL No.
JACK I'll lead them away.
The sounds are closer.
JACK (CONT'D) Go to the opposite end of the island, and signal the ship.
JACK (CONT'D) I'll keep 'em busy.
WILL Are you sure?
WILL Jack -- this is not something you have to do.
JACK I'm sure.
JACK When you've led the kind of life I have, there are debts that must be paid.
JACK Maybe I can balance the scales a little.
Will nods, hesitates...
gives Jack his sword - - now Jack has two, ..one for each hand.
Elizabeth gives him a quick kiss.
Will and Elizabeth race away, and are gone.
Jack watches them for a moment, turns to face the pirates.
He sticks the two swords in the ground, crossed.
Leans casually against a rock.
A group of pirates round a corner, cutlasses drawn, ready to fight -- but Jack raises his hand.
JACK (CONT'D) I invoke the right of parlay, according to the Code of the Brethren, set down by the pirates Morgan and Bartholomew...
Jack stands before Barbossa, surrounded by pirates.
Jack has a wide smile on his face -- and Barbossa doesn't like it.
BARBOSSA I'm inclined to kill you now, Jack Sparrow, without so much as a word, if you don't lose that grin from your face.
Jack's smile remains.
Barbossa puts a hand to his cutlass -
JACK The woman's blood didn't work, did it?
Barbossa hesitates.
JACK (CONT'D) I know who's blood you need, to end the curse.
BARBOSSA Say the name, or I slit your throat.
JACK No you won't.
Barbossa nods.
Pintel steps forward, puts a blade to Jack's throat.
Jack's smile widens.
PINTEL Now?
BARBOSSA (NODS) Now.
BARBOSSA (NODS) No, don't kill him.
Surprised, Pintel lowers his cutlass.
Jack's expression hasn't changed.
BARBOSSA (CONT'D) Allow me the humor of listening to your terms.
JACK Simple.
JACK I have something you want more than anything.
JACK The way to free you from the curse of the treasure.
JACK You have something I want -- more than anything.
BARBOSSA The Pearl?
BARBOSSA Oh, that's fine.
BARBOSSA And just how do you expect this to work?
JACK You give me the Pearl.
JACK Then I tell you who you need.
Barbossa stares at him, incredulous.
BARBOSSA That's your offer?
BARBOSSA You, sailing away nice and pretty with the Black Pearl, and all I have is a name?
JACK That's right.
BARBOSSA I'm supposed to ...
BARBOSSA trust you?
The pirates laugh.
JACK I'm a man of my word.
The pirates laugh louder.
JACK (CONT' D) You see, I've got this honest streak in me -- in its own way, a sort of curse.
JACK (CONT' D) Oh, and there's the fact that you have no choice.
BARBOSSA I'll torture it out of you.
JACK You left me on a desert island -- what worse can you do?
Jack is still smiling, intentionally smug now.
Barbossa sees his options dwindling, begins to pace.
BARBOSSA Blast you!
BARBOSSA I'll throw you in prison.
JACK Wait as long as you like.
BARBOSSA You're setting me up for a double cross, you with the ship, and me with nothing more than your word!
JACK Let's say I tell you the wrong person.
JACK What would you do?
BARBOSSA Track you down and -
He sees where Jack is headed.
JACK And if I tell you the truth, you become mortal, and you won't come near me because you know I'd kill you.
Barbossa hesitates.
The pirates are amazed at how the tide has turned; Barbossa has gone past considering the idea, and might even do it.
BARBOSSA Jack, I don't trust you, and that's a fact.
BARBOSSA Never trust a smiling man, you can lay to that.
JACK See, that's where we're different.
JACK I trust you ...
JACK to do what it takes to get what you want.
BARBOSSA You're playing this as close to the edge as any man, I'll give you that.
BARBOSSA We might just have to sign articles, you and I. Jack, you're a pirate at heart, that's certain.
Jack nods.
BARBOSSA (CONT'D) Pintel ...
BARBOSSA (CONT'D) set sail.
BARBOSSA (CONT'D) If this fool plan is to work, we'll need the medallion, and that means catching the ship which brought 'em here.
Jack is caught completely off guard.
For the first time, his smile fades.
JACK What -- you don't have the medallion?
BARBOSSA That fool woman took it.
BARBOSSA You be careful around her, Jack -- she's pretty enough, she'll steal your heart -- but pure evil inside.
JACK I'll watch my back.
BARBOSSA Bosun!
BARBOSSA Set up Mr. Sparrow's quarters, nice and fine ...
BARBOSSA in the brig.
BARBOSSA Meaning no disrespect, of course.
Jack nods, and is taken away.
Barbossa stares after him, not hiding his mistrust.
At full sail, headed out to sea.
Gibbs glances at Elizabeth and Will, talking alone on the forecastle -- shakes his head.
GIBBS Two women on board?
GIBBS A man don't have to be superstitious to know that's trouble.
Elizabeth holds the medallion, and finishes her tale:
ELIZABETH ...
ELIZABETH you were in danger ...
ELIZABETH so I took the medallion.
ELIZABETH And I've kept it ever since.
ELIZABETH They thought I was you, that they needed my blood.
ELIZABETH And it didn't work.
She hands him the medallion.
WILL Why would my father send this to me?
ELIZABETH To keep it away from them?
ELIZABETH No pirate would sail to London, for fear of Execution Dock.
WILL If I had known-
ELIZABETH -- then we never would have met.
Will nods.
They hold each other's gaze a moment.
Will turns away first, leans on the rail.
Looks out to sea, back the direction they came.
WILL I can't believe he would make such a sacrifice for us.
ELIZABETH I guess you can never truly know someone else's heart.
Will glances at her, and nods.
AT THE HELM, Gibbs peers forward, scanning the horizon.
There
is a tiny island in front of them.
GIBBS Shift your heading, steer clear of that island.
GIBBS Fifteen degrees starboard.
On the aft deck, Cotton concentrates on his work, securing a halyard.
Suddenly Cotton's parrot flaps its wings, takes off, lands on the starboard bulwark, squawking -
COTTON'S PARROT Dead men tell NO tales!
COTTON'S PARROT Dead men tell NO tales!
COTTON'S PARROT Dead men tell NO tales!
Cotton looks up - on the horizon, following: black sails.
Gibbs and AnaMaria appear, and see the ship.
ANAMARIA Can we outrun them?
GIBBS Not a chance.
GIBBS Make for the reef.
Miles of blue water.
The Interceptor tacks, leaving a long white wake.
The Black Pearl matches it -- gaining.
Barbossa and Pintel eye the Interceptor, two hounds chasing the fox.
PINTEL What's he doing?
PINTEL Is he going to run her aground?
The Black Pearl is now close behind the Interceptor -- and the Interceptor is headed for the island.
GIBBS Drop the forward anchor!
A SAILOR at the stern of the ship pulls a release, and the
ship's anchor races down into the water, the metal chain
jumping and twisting on deck.
The chain stops, and the Sailor locks it -
With its forward momentum and the anchor down, the Interceptor to turn quickly, pivoting around the anchor.
Barbossa and Pintel watch as the huge ship brings its cannons to bear right in front of them.
BARBOSSA All hands!
BARBOSSA Prepare to come about!
But for now, the Interceptor has the advantage, and takes it:
its cannons boom, and cannonballs rain down.
Jack sees what he can out the porthole.
In the cell with him is Twigg, acting as a guard.
JACK Don't hit my ship!
JACK I mean, kill the lying scoundrel -
JACK I'm a little conflicted, here.
Twigg just stares.
Elizabeth watches as the Black Pearl comes about -- and then there is the low, loud RUMBLE of two dozen cannons firing as one.
The Interceptor is hit.
A barrage of shots follow; most find their mark.
Sailors dive for cover, leaving their cannons; clearly they are overmatched.
Barbossa laughs.
BARBOSSA Strike your colors, you bloody cockroaches!
Another round of fire; Barbossa shows no mercy.
ANAMARIA Looks like they mean to send us under.
GIBBS There -- she's raised the Jolly Roger,
upside down.
AnaMaria, Gibbs, Cotton, even Elizabeth -- all know what this means.
Will doesn't.
He looks to Gibbs for an explanation:
GIBBS (CONT 'D) It's a signal.
GIBBS (CONT 'D) If we resist, it won't just be death.
GIBBS (CONT 'D) There'll be torture as well.
WILL We're not going to just surrender!
GIBBS That we are.
The Black Pearl fires again, a double-ball shot with a chain connecting the two.
It hits the main mast dead ani a CRACKING, SPLINTING sound as it breaks, falls to the deck.
Barbossa moves his ship alongside, preparing to board.
WILL We can at least fight -- we might be able to kill a few-
GIBBS Will -- it'll go worse for us -- for Elizabeth, especially -- if we fight.
Will stares -- and nods.
But his expression is still defiant.
The deck slants; the ship is sinking.
pirates swarm across on ropes, and take control of the Interceptor.
The top masts of the H.M.S. Interceptor sink into the smooth' crystal waters of the Caribbean -
-- as Will and Elizabeth, held by pirates, are brought before Barbossa -- and see that Jack stands beside him, manacled.
Gibbs, AnaMaria and Cotton and the other crewmembers huddle together.
Barbossa's wrath falls on Elizabeth.
BARBOSSA Welcome back, Miss.
BARBOSSA Last time on board, you played me right clever, make pretending and all.
BARBOSSA I hope your stay this time is more pleasant.
BARBOSSA Boys, show her some hospitality!
He shoves her into a group of pirates; they yell their approval.
She is pushed from one to another.
This goads Will to action.
He head-butts the pirate behind him, grabs a pistol, waves it at the pirates.
WILL She goes free!
Will leaps onto the ship's rail.
He steadies himself with a hand on the rigging.
Points the pistol at Barbossa.
BARBOSSA What's in your head, boy?
WILL She.
WILL Goes.
WILL Free.
BARBOSSA You've got one shot -- and we can't die.
WILL You can't.
WILL I can.
He leans out over the ocean.
ELIZABETH No!
Jack pushes forward.
JACK Will -- don't do anything stupid!
JACK Don't say anything stupid -
WILL My name is Will Turner, the son of Bootstrap Bill Turner.
WILL His blood runs in my veins.
WILL You need my blood.
WILL And on my word I will pull this trigger, and sink all the way down to Davy Jones' Locker!
Pintel squints at Will; the pirates murmur surprise.
TWIGG It's true - he's the spittin' image of old Bootstrap.
TWIGG Even talks the same!
Jack drops his head.
Barbossa grins at him.
BARBOSSA Looks like you're back to having nothing to offer.
PINTEL And hers got Old Bill's courage.
PINTEL A curse on him, and you!
Barbossa steps forward.
BARBOSSA Enough of that!
BARBOSSA Name your terms.
WILL Elizabeth goes free!
BARBOSSA We got that part.
BARBOSSA Anything else?
WILL And Jack.
WILL And the crew.
WILL Free and unharmed.
WILL I f you agree...
WILL then...
WILL I will remain with you.
Barbossa considers; his crew waits.
Finally -
BARBOSSA Agreed.
BARBOSSA You have my word, as a gentleman of fortune -
ELIZABETH Will -- you can't trust him.
WILL You must swear by the Holy Bible.
BARBOSSA Eh?
BARBOSSA You have my word, then -- on the Good Book, I do swear, and the Lord spare my worthless soul.
Barbossa crosses himself, as do many of his men.
Will lowers the gun ...
steps down -- the pirates surround him.
They snatch away the pistol.
BARBOSSA (CONT'D) Boatswain!
BARBOSSA (CONT'D) Take your captives belowdecks.
BARBOSSA (CONT'D) Chain them in the galley, and teach 'em how to row.
Gibbs, AnaMaria, Cotton and the rest are led away under guard.
Barbossa looks out to sea, toward the islet.
BARBOSSA (CONT'D) Hah.
BARBOSSA (CONT'D) Look there.
BARBOSSA (CONT'D) That's the very same island we made Jack governor of on our last trip.
BARBOSSA (CONT'D) When you sail the open sea as long as I, you learn to trust the signs fate sends your way.
GIBBS Amen to that...
BARBOSSA Jack, Elizabeth ...
BARBOSSA I'm a man of my word and you're to be set free, right quick.
BARBOSSA Men, break out the plank!
A CHEER goes up from the pirates.
Will realizes what Barbossa intends to do, struggles with his captors.
WILL No!
WILL You gave your word!
BARBOSSA Quiet, boy, or you'll lose your tongue.
BARBOSSA Those as know me know I wouldn't cross my word, and bring down bad luck on the ship.
BARBOSSA I agreed to set them free.
BARBOSSA I didn't say when.
BARBOSSA ..
BARBOSSA nor where.
The Black Pearl lies at anchor, closer now to the islet.
Jack, wrists still bound, stands in the classic 'walking the plank' pose.
Elizabeth is next in line.
Pirates crowd the ship's rail to watch.
JACK It's pure evil to make a Captain walk the plank of his own ship, twice in one lifetime.
JACK No good can come of it.
BARBOSSA Now, Jack.
BARBOSSA That reef is less than a league distant.
BARBOSSA It's a square deal all around, and you can't hope for better.
JACK Someone needs to cut these bonds, then.
Barbossa smiles, shows a pistol.
Points it at Jack.
BARBOSSA You'd best take a swim, Jack.
JACK The last time you did this, you left me a pistol, with one shot.
The pirates mutter agreement.
PINTEL That's proper, sir, according to the code.
BARBOSSA By the Powers, you're right!
BARBOSSA Where's Jack's pistol?
BARBOSSA Who's got it?
BARBOSSA Bring it forward!
JACK A gentleman might give us two pistols, seeing as there are two of us, this time.
A pirate hands Jack's pistol to Barbossa.
BARBOSSA Tell you what.
BARBOSSA I'll give you one pistol, and let you be the gentleman, an' shoot the lady, and starve to death yourself!
BARBOSSA That is, presuming you're not both drownded.
The pirates laugh.
Barbossa tosses Jack the pistol -- but over his head, and down into the water with a splash.
BARBOSSA (CONTID) So how did you get off that island, anyway?
JACK You can go to your grave not knowing.
BARBOSSA That's fair.
Jack glares at Barbossa.
Then he's prodded with a cutlass, takes a step out.
Reaches the end of the plank -- steps off.
Jack plunges down into the water.
Appears on the surface, floundering, struggles to stay afloat.
Will and Elizabeth exchange helpless looks; there is nothing they can do.
BARBOSSA (CONT'D) The lady's next.
BARBOSSA (CONT'D) But first, I'll be wanting that dress back, if you please.
Elizabeth hesitates ...
then strips it off, leaving her in a silk slip.
She throws it at him.
ELIZABETH Here -- it will go well with your black heart !
Barbossa indicates the plank.
ELIZABETH (CONT' D) I will not walk into the ocean.
ELIZABETH (CONT' D) You'll have to throw me in!
Barbossa raises an eyebrow, grins, nods.
BARBOSSA Have at her, lads!
The pirates rush to comply.
Lift her up, toss her over the rail -- with a scream she falls --
We follow Elizabeth amid foam and bubbles as she PLUNGES down
through the water.
Blue and clear, with streaks of sunlight cutting down; bright coral and tropical fish, and a lovely young woman in a silk dress.
..
if it weren't for the mortal danger, the scene could be described as gorgeous.
Elizabeth spots Jack, below her now, sinking, struggling.
She swims down ...
unties his bonds.
Elizabeth starts for the surface.
Inexplicably, Jack swims the other way, further down into the depths.
Elizabeth breaks the surface, looks around.
And then, finally Jack appears, sucking in air.
He shows what he went after: his pistol.
He tucks it into his shirt.
ELIZABETH You went back for that?
ELIZABETH We need to head for the reef!
She starts swimming.
Jack hesitates.
The Black Pearl is already underway; he stares at it.
JACK That's the second time I've had to watch that man sail away with my ship.
He turns away, and swims after Elizabeth.
CLOSE ON: The surf line.
Elizabeth's feet leave prints in the sand ...
and then meet up with matching footprints she made earlier, going in the same direction.
She has walked all the way around the island.
JACK Not all that big, is it?
Jack lays on the beach.
He has dismantled his pistol; the parts, ball and powder dry on his scarf.
ELIZABETH Has it changed since the last time you were here?
JACK The trees are taller.
Jack checks to see if the pistol parts are dry; they are.
He sets about re-assembling and loading his pistol.
ELIZABETH I hope you have no intention of using that.
Jack has finished putting his pistol back together.
He shoves it in his belt, walks off.
JACK Not yet.
JACK Ask me again in a few weeks.
Elizabeth can't believe it.
ELIZABETH Captain Sparrow!
ELIZABETH We have to get off this island -- immediately!
JACK Don't be thinking I'm not already working on it.
He climbs up toward a clump of palm trees.
Digs for something beneath the sand.
He finds it: a large iron ring.
ELIZABETH What is that?
ELIZABETH Is there a boat under there?
Jack heaves the trap door up and over, revealing a pit.
Inside are barrels and bottles of rum ...
all covered with dust and cobwebs, long abandoned.
Jack's face falls.
ELIZABETH (CONT'D) What?
ELIZABETH (CONT'D) What's wrong?
ELIZABETH (CONT'D) How will this help us get off the island?
JACK It won't.
JACK It won't, and so we won't.
He jumps down into the pit, cracks open a bottle of rum,.
takes a swig.
ELIZABETH But ...
ELIZABETH you did it before!
ELIZABETH Last time -
JACK Last time, I was here a grand total of three days.
JACK Last time, the rumrunners who used this island as a cache came by, and I bartered passage off.
JACK (CONT'D) But from the looks of this, they've long been'out of business, and so that won't be happening again.
JACK (CONT'D) We probably have your friend Norrington to thank for that.
ELIZABETH So that's it?
ELIZABETH That's the secret grand adventure of the infamous
ELIZABETH Jack Sparrow?
ELIZABETH You spent three days on the beach drinking rum?
JACK Welcome to the Caribbean, love.
He gathers up a few bottles, heads for the beach.
JACK (CONT'D) You should look at our contretemps this way: we've got shade trees, thank the Lord.
JACK (CONT'D) We've got some food on the trees, thank the Lord again.
JACK (CONT'D) And we've got rum, praise the Lord.
JACK (CONT'D) We can stay alive a month, maybe more.
JACK (CONT'D) Keep a weather eye open for passing ships, and our chances are fair.
ELIZABETH A month?
ELIZABETH Will doesn't have a month!
ELIZABETH We've got to do something to help him!
JACK You're right.
JACK Here's luck to you, Will Turner.
He drinks -- and defiantly returns Elizabeth's angry gaze.
But then turns away, sits down.
JACK (CONT'D) Don't be thinking I'm happy about this, Elizabeth.
JACK (CONT'D) But I see no use in wailing and gnashing my teeth over that which I can do nothing about.
ELIZABETH Not when you can drink instead, at least.
Jack tosses her a bottle.
JACK Try it.
JACK It goes down rough, but it goes down - - and the second swig goes down easier.
Elizabeth considers.
Comes to a decision.
She unseals the bottle, takes a swig.
They sit in silence for a bit.
ELIZABETH And you will call me Miss Swann.
Jack toasts her: you got it.
Elizabeth studies her bottle...
gives Jack a sidelong glance.
Back to her bottle ...
ELIZABETH (CONT'D) Drink up me hearties, yo ho...
JACK What?
JACK What was that?
JACK Something funny, Miss Swann?
JACK share.
JACK Please,
ELIZABETH Nothing ...
ELIZABETH it's nothing.
ELIZABETH Just ...
ELIZABETH I'm reminded of a song I learned as a child.
ELIZABETH A song about pirates.
JACK I know a lot of songs about pirates, but none I'd teach a child.
JACK Let's hear it.
ELIZABETH Oh, no ...
ELIZABETH it's silly.
ELIZABETH Back in England we didn't know a thing about pirates, really.
ELIZABETH They seemed so romantic and daring -
Jack likes the way that sounds.
ELIZABETH (CONT'D) That was before I met one, of course.
JACK Now I must hear this song.
JACK An authentic pirate song.
JACK Have at it.
ELIZABETH Well, perhaps ...
ELIZABETH with a bit more to drink, I might ...
JACK More to drink!
He gathers two more bottles, tosses one to her.
She drops her half-finished bottle to catch it.
Opens it, takes a sip.
JACK (CONT'D) Well?
Elizabeth clears her throat, begins to sing self- consciously, becoming stronger as she goes on.
ELIZABETH We pillage, we plunder, we rifle, we loot, Drink up me hearties, yo ho.
She gestures for him to drink.
He does.
ELIZABETH (CONT'D) We kidnap and ravage and we don't give a hoot, Drink up me hearties, yo ho -
The middle of the night.
A fire BLAZES.
Jack and Elizabeth are roaring drunk, arm in arm, singing the song all the way up to the stars --
JACK/ELIZABETH Yo ho, yo ho, a pirate's life for me!
Yo ho, yo ho, it's a pirates life for me!
JACK I LOVE this song!
JACK Yo ho, yo ho, a pirate's life for me!
JACK We're beggars and blighters,
JACK ne'er do well cads, Drink up me hearties, yo ho!
JACK Aye but we're loved by our mums and our dads.
JACK Drink up me hearties, yo ho!
They hoist their bottles, but only Jack drinks.
He drains the bottle, then tosses it away.
JACK (CONT'D) When I get the Black Pearl back, I'm going to teach it to the whole crew, and we'll sing it all the time!
ELIZABETH You'll be positively the most fearsome pirates to sail the Spanish Main.
Elizabeth salutes the idea with her bottle.
Jack doesn't have a bottle to salute back.
She hands him hers.
He drinks, then settles shakily to the ground.
Elizabeth sits beside him.
JACK Not just the Spanish Main.
JACK The whole ocean.
JACK ..
JACK the whole world.
JACK Wherever we want to go, we go.
JACK That's what a ship is, you know.
JACK Not just a keel and a hull and a deck and sails.
JACK That's what a ship need_ ...
JACK but what a ship is -- what the Black Pearl really-is ...
JACK is freedom.
Elizabeth lays her head on his shoulder.
ELIZABETH Jack, it must be so terrible for you, to be trapped here on this island, all over again.
JACK Ah, well...
JACK the company is better than last time.
JACK And the scenery has definitely improved.
ELIZABETH Mr. Sparrow!
ELIZABETH I'm not sure I've had enough rum to allow that kind of talk.
JACK We've got a few bottles left ...
JACK and we've yet to tap the kegs.
Elizabeth shrugs with a sleight -- but promising -- smile.
She picks up the empty bottle from the ground, holds it up.
ELIZABETH To freedom.
JACK To the Black Pearl.
They tap the bottles together.
Elizabeth feigns a drink as he chugs.
He taps his bottle against her again.
She laughs, feigns another drink -
CLOSE ON -- JACK'S FACE, dead asleep, lying in the sunlight.
His nose twitches.
A bit of SMOKE drifts by.
His nose twitches again.
His eyes open.
Jack GROANS and sits up.
He rubs his head, looks over -
-- all of the foliage in the middle of the island is ON FIRE.
Smoke rises high up into the clear blue sky.
Jack leaps to his feet.
He sees Elizabeth, as she pours out the last of the rum, dowsing a scrub brush at the base of a palm tree.
It goes up in FLAMES.
She rolls the barrel forward -- it starts to BURN merrily.
Jack can't believe his eyes.
JACK What are you doing?
JACK You've burned our food, the shade -- the rum!
ELIZABETH Yes, the rum is gone.
She wipes her hands together.
One of the rum barrels in the fire EXPLODES.
JACK Why?
ELIZABETH One, because it is a vile drink that turns even the most respectable men into scoundrels.
ELIZABETH Two -
She points to the sky.
ELIZABETH (CONT'D) That signal is over a thousand feet high, which means it can be seen for two hundred leagues in every direction.
ELIZABETH (CONT'D) The entire Royal Navy is out to sea looking for me -- do you think there is even a chance they could mass it?
JACK You -- you burned up the island, for a one-time chance at being spotted?
ELIZABETH Exactly.
Elizabeth turns toward the sea.
ELIZABETH (CONT'D) Just you wait, Captain.
ELIZABETH (CONT'D) In an hour, maybe two, keep a 'weather eye open' and you'll be seeing white sails on that horizon!
She sits down, determined.
Shields her eyes, scans the water, waiting, searching.
Jack is speechless.
He throws up his hands, stalks up the sand dune, just to get away from her.
At the crest of the dune, Jack stops -- and stares, incredulous.
We come around to see what he is looking at -
Past Jack, anchored the other side of the island, white sails glorious against the turquoise waters, is the H.M.S.
Dauntless.
A longboat is already being rowed toward them.
Jack shakes his head.
JACK They'll be no living with her after this.
Norrington gives Elizabeth a hand disembarking from the raised long boat.
NORRINGTON Elizabeth, I'm" relieved you're safe.
NORRINGTON Clap him in irons.
NORRINGTON And behind his back this time.
ELIZABETII Commodore, you can't do that!
NORRINGTON You're speaking up for him again?
ELIZABETH He can locate Isla de Muerta -- but I doubt he'll be willing to help us from the brig.
JACK We had time to get to know each other.
NORRINGTON We are bound for Port Royal, not Isla de Muerta.
ELIZABETH No.
ELIZABETH The pirates have taken Will -
NORRINGTON Your father is frantic with worry.
NORRINGTON Our mission was to rescue you and return home.
NORRINGTON That is what we shall do.
NORRINGTON Mr. Turner's fate is regrettable.
NORRINGTON But so was his decision to engage in piracy.
ELIZABETH Commodore, please!
JACK Norrington, think about it ...
JACK the Black Pearl, its captain and crew...
JACK the last pirate threat in the Caribbean.
JACK How can you pass that up?
NORRINGTON By remembering that I serve others, not only myself.
ELIZABETH Commodore, I beg you -- please do this ...
ELIZABETH for me.
ELIZABETH As a wedding gift.
NORRINGTON I am to understand that you will accept my marriage proposal on the condition I rescue Mr. Turner?
ELIZABETH Not as a condition -- a request.
Norrington considers.
To Gillette:
NORRINGTON Free Mister Sparrow, and prepare to come about.
NORRINGTON He'll give you our heading.
Gillette unlocks Jack's manacles.
Jack raises an eyebrow.
JACK Congratulations, sir.
Crew men lead Jack toward the bridge.
Sailors go about their tasks, and the ship begins its slow turn.
NORRINGTON Elizabeth, I hereby withdraw my proposal.
ELIZABETH What?
NORRINGTON I know now where your heart truly lies.
Elizabeth looks at Norrington, seeing him in a new light.
ELIZABETH And now I know...
ELIZABETH where yours does, as well.
They gaze at each other for a moment.
Norrington looks away.
NORRINGTON You may seclude yourself in my cabin.
NORRINGTON I'm afraid we do not have any ladies' clothing aboard.
ELIZABETH Then I can wear men's clothing.
NORRINGTON That would hardly be proper.
ELIZABETH Well, I am not going to stay hidden in a some cabin, 80 I suppose it's going to be heaving bosoms and bare ankles for the remainder of the voyage!
Norrington is exasperated, but then can't help but grin - this is exactly why he loves her.
She grins back at him - she's not going to change.
NORRINGTON Murtogg, take our guest below, and find her some trousers, and a shirt.
Elizabeth smiles, allows herself to be escorted away.
Norrington watches her go ...
then turns his gaze to the sea.
Pintel enters the cell.
It appears empty -- but that's because Will is hanging from the rafters, trying to shove up the ceiling planks with his legs.
PINTEL That ain't going to work.
PINTEL That's the gun deck above yea
Will drops lightly to the deck.
Suddenly:
WILL What happened to William Turner?
PINTEL Ah, William Turner.
PINTEL Stupid blighter.
PINTEL He threw in with us after we relieved Jack Sparrow of his captaincy, but turned out, it never sat well with him- particularly after we found Cortes' treasure, and its peculiar condition.
PINTEL He thought we deserved to be cursed, for leaving ol' Jack to the fate we did.
PINTEL That's why he sent off a piece of the treasure -- to you, as it were: so it would never be recovered, and so cursed we_ remain.
WILL And then he ran.
WILL And he's hiding out someplace where you haven't been able to find him.
PINTEL That's a nice thought, to be sure, and I wager your da wishes he'd thought it hisself.
PINTEL But, no.
PINTEL See, what he'd done, _ didn't sit too well with Captain Barbossa ...
PINTEL so he chained a cannon to his legs and dumped him over.
Will reacts with shock at the account of his father's fate.
PINTEL (CONT'D) Yep, last I saw of Bootstrap Bill, was his face looking up, as he sank down to the crushing black oblivion of Davy Jones' locker.
PINTEL (CONT'D) It was only after, we found out we needed his blood to solve the curse.
PINTEL (CONT'D) That's what you call ironic.
Barbossa appears behind Pintel, flanked by several other pirates.
He regards Will for a moment, then:
BARBOSSA Bring him.
Jack goes to the rail and waits, pretending to look out at the sea.
Elizabeth, dressed in sailor's clothes to excellent effect, joins him.
ELIZABETH You didn't tell Commodore Norrington everything.
JACK Nor did you, I noticed.
ELIZABETH He might delay the rescue ...
ELIZABETH and that would be too late.
JACK Exactly.
ELIZABETH These men will be facing an enemy that seemingly cannot be killed.
JACK I have a plan.
JACK If it succeeds, then any battle will be decidedly brief ...
JACK and one-sided.
ELIZABETH What's your plan?
Isla de Muerta lay dark and menacing on the horizon.
NORRINGTON Elizabeth -- below decks.
NORRINGTON I will not compromise your safety..
She starts to speak; he turns away..
NORRINGTON (CONT'D) Lieutenant, escort Elizabeth to my quarters, and make sure she stays there.
Norrington gazes through his spyglass, at the island.
Jack watches with some amusement as Elizabeth is escorted away.
NORRINGTON (CONT'D) I don't like the situation, mister Sparrow.
NORRINGTON (CONT'D) The island is riddled with caves.
NORRINGTON (CONT'D) I will not put my men at a disadvantage.
JACK Funny, I was thinking along those lines.
JACK How about you let me go in alone, and while you're setting up an ambush, I'll trick the pirates out to you.
NORRINGTON You would do that?
JACK They left me stranded.
JACK Twice.
JACK What have you got to lose?
NORRINGTON Nothing I wouldn't be please to be rid of.
JACK I knew you'd listen to reason!
Torches are lit.
Barbossa leads Will, guarded by Pintel and a band of pirates, into the caves.
A long boat is prepared to be lowered over the side.
Jack wraps his pistol securely in an oilskin pouch.
JACK That chart I drew up'11 get you past the reefs.
JACK If you're steersman's good enough, that is.
NORRINGTON I'll be at the wheel myself.
JACK I'll slip in, talk them into to come out, and you'll be free to blow holy high heaven the whole lot of them.
The crewmen release the lines, and the boat drops -
The pirate group moves deeper into the caves.
Will moves along unwillingly.
PINTEL No reason to fret.
PINTEL It's just a prick of the finger and a few drops of blood.
BARBOSSA Turner blood doesn't flow pure in his veins.
BARBOSSA Best play it safe, and spill it all.
PINTEL I guess there is a reason to fret.
The Dauntless drifts into the lagoon.
Norrington and his men prepare to go ashore.
Lit by torchlight.
Will notices: a crack runs between the floor and the wall of the cave, widening into a ravine.
BARBOSSA Careful, now.
BARBOSSA You could fall in and still be wonder'n when you'll hit dirt.
Will makes a decision.
He intentionally stumbles.
Pintel
shoves him forward -- Will continues forward, grabs the pirate in front of him, swings him into the wall of the cave.
Catches the pirate's torch, and uses it to ward off the others.
WILL You deserve to be cursed -- and remain cursed!
He steps to one side -- and drops into the ravine.
The wall of the ravine becomes a loose gravel slope; Will hits it, and tumbles down, disappears into black.
BARBOSSA Blast him!
BARBOSSA A pox on him, and his father, and the whole damnable line!
BARBOSSA Fan out!
BARBOSSA Find him!
Elizabeth looks out the Captain's small porthole -- sees boats laden with Navy men headed for shore.
She turns away from the porthole, wishing there was something she could do.
Suddenly there is a flutter at the window--
Cotton's parrot is there.
COTTON'S PARROT Drink UP me hearties yo ho!
COTTON'S PARROT Drink UP me hearties yo ho!
The bird flutters off; Elizabeth races to the porthole, and then to the stern window to see it flyaway.
She looks down -- and there, fastened to the stern of the ship, is a small rowboat.
Will races forward, turning this way and that.
He sees a light ahead, heads for it, turns a corner -
-- and runs straight into Jack.
JACK Do you have any idea where you're going?
WILL Jack!
JACK Don't talk.
JACK These caves magnify sound.
JACK Just follow me.
Norrington and men land on the beach, and spread out.
They silently take up positions around the main cave entrance.
Jack leads Will out of a narrow passage -- and stops, staring.
Will is a few steps behind.
WILL Are you certain this is the right way?
JACK It's the right way.
Will join him -- and see what Jack is staring at:
Treasure piled on treasure, sparkling, glowing, seemingly
endless.
At the center is the moonlit clearing, and the stone Aztec chest.
BARBOSSA Thank you, Jack Sparrow.
The jump -- Barbossa is standing right behind them, flanked by his men.
The trio whirl to run - - more pirates emerge from hiding.
Nearly the entire crew of the Black Pearl is there.
The pirates grab Will and Jack.
Will struggles, but Jack does not fight at all.
BARBOSSA (CONT'D) You couldn't have led him back more directly if you knew exactly where you were going.
He laughs, and moves toward the stone chest.
The pirates follow, dragging Will and Jack with them.
WILL You did know where you were going!
WILL You did lead us directly to them!
WILL Why?
Jack looks away -- as Will is manhandled toward the chest.
Barbo8sa steps up to him (becoming skeletal in the moonlight) and puts the medallion around Will's neck.
He picks up the stone knife.
BARBOSSA What was begun by blood, let blood now end!
He raises the knife to Will's throat -
JACK You don't want to be doing that.
Barbossa pretends to think about his words.
BARBOSSA No, I really think I do.
JACK All right then.
That makes Barbossa pause.
He steps out of the moonlight.
BARBOSSA Why don't I want to do this?
JACK Because, right about now, the H.M.S.
JACK Dauntless is lying in wait in the harbor.
WILL Jack!
JACK - - and its guns and crew will cut you and your men to pieces the moment you step outside these caves.
A buzz of apprehension sweeps through the pirates.
PINTEL Do you believe him?
BARBOSSA No.
BARBOSSA But him I believe.
BARBOSSA He is genuinely angry.
JACK You've no hope of surviving Norrington's attack ...
JACK that is, if you're mortal.
BARBOSSA What're you suggesting?
Jack shakes off the hands holding him, strolls toward Barbossa, Will, and the chest of coins.
JACK Simple.
JACK Don't kill the boy yet.
JACK Wait for a more opportune moment.
Will glares, listening to every word he says.
Jack scoops up a handful of coins from the chest.
JACK (CONT'D) Like after you've killed...
JACK (CONT'D) Every...
JACK (CONT'D) Last ...
JACK (CONT'D) One ...
JACK (CONT'D) of Norrington's men.
BARBOSSA I can't help wondering, Jack, why you're being so helpful and all?
BARBOSSA Last time you did that, it didn't end 80 well for you.
JACK The situation has changed.
BARBOSSA That so?
JACK Aye.
JACK See, after you're done with the Royal Navy, you'll have a bit of a problem: the H.M.S. Dauntless.
JACK There you'll be, with two lovely ships on your hands, and what to do?
JACK Of course you'll decide you deserve the bigger one, and who's to argue?
JACK The Dauntless a first-rate ship-of-line, and with it, you can rule the seas.
JACK But if you're Captain of the Dauntless, who's left for the Black Pearl?
Jack smiles and spreads his hands: me.
JACK (CONT'D) I sail for you as part of your fleet, I give you fifteen percent of my plunder, and you get to introduce yourself at tea parties and brothels as 'Commodore Barbossa.'
JACK (CONT'D) Do we have an accord?
Barbossa licks his lips.
It's tempting ...
JACK (CONT'D) Now, you can take care of the Dauntless, right?
BARBOSSA Men!
BARBOSSA Are you up for it?
The pirates yell to the affirmative.
BARBOSSA (CONT'D) Mr. Pintel, select five men to stay here.
BARBOSSA (CONT'D) Take the rest of the men out ...
BARBOSSA (CONT'D) not through the caves.
Jack's expression falters; this he hadn't planned for.
JACK There's ...
JACK another exit?
BARBOSSA Aye, for us there is.
Moonlight shines down into the shallow waters, brightening coral, sparkling over the rippled sand floor.
Suddenly all the fish SCATTER.
Briefly, the waters are empty.
And then FIGURES appear in the distance, seeming to waver in the shifting current.
They scuffle forward, kicking up clouds of sand --
The figures resolve into the skeleton PIRATES, moving silently across the lagoon floor, swords glinting.
The tatters of their clothing drift in the water.
Their skull heads are fixed in an endless grin.
The LEAD PIRATE glides forward -
And stops next to a huge iron ANCHOR -- twice his' height, even buried halfway into the sand.
A heavy CHAIN with barrel-sized links climbs up toward the surface -
A SHADOW falls across the Lead Pirate -- he TRANSFORMS, and we see that it is Pintel.
He looks up -
Above, the heavy chain leads to the giant bottom hull of the H.M.S. Dauntless, silhouetted by moonlight.
The huge shift drifts, again spilling moonlight below -
And the pirates gathered around the anchor are once again SKELETONS, staring with upturned faces.
The Pintel-skeleton puts a knife between his teeth, starts to crawl up the iron rings.
Other pirates crowd forward, and soon the anchor-chain is clustered with skeletons -
Elizabeth has the small boat out, and rows away from the Dauntless, looking ahead over her shoulder.
Cotton's parrot is nowhere to be seen.
In the distance, Pintel breaks the surface near the Dauntless, intent on climbing the anchor; he looks over -
Just as Elizabeth rounds the point, and rocks obscure the small longboat from view.
More skeleton-pirates appear, and Pintel continues his climb.
Two SAILORS, alert and vigilant, stare out toward shore.
The island reveals nothing but blackness.
There is a scurrying sound -- bones scraping against wood - and the sailors JUMP.
They listen, intently -- nothing.
TALL SAILOR Ship rats.
TALL SAILOR Big ones.
SHORT SAILOR Hate those things.
They turn back toward the island, continue their vigil.
A long pause.
SHORT SAILOR (CONT'D) Taste all right, though.
TALL SAILOR That they do.
From behind, the two sailors at the rail are well-lit by a lantern.
Suddenly shadows appear, skeletons, climbing up the sailor's backs.
-MOVE CLOSER and then the skeletons appear, reaching -- the two sailors are grabbed from behind -
Two bodies are tossed out over the rail, hit the water with a splash.
Pintel looks down into the water, satisfied.
Puts away his knife.
Notices, pulls out a long piece of seaweed from his rib cage.
Tosses it.
Turns to the others.
PINTEL Be quick, now.
PINTEL Train the starboard guns on the beach, and set your aim.
PINTEL Wait for my signal, we don't want to spook them.
The pirates hurry to comply -
Elizabeth rounds the point further, and sees: the Black Pearl, anchored in the neighboring cove.
A fleck of color - Cotton's parrot, as it darts in through a porthole.
Elizabeth slows her efforts, silently approaching the ship.
Four PIRATES -- who really ought to be keeping watch -
instead have gathered wine bottles and rum casts into a pile, along apples, biscuits -- all the food on the ship.
They act out a mock-feast, in anticipation of the curse being lifted.
A SKINNY skeleton offers two bottles BIG
BONED skeleton.
SKINNY Which would you prefer first, good sir -rum, or wine?
BIG-BONES I believe I'll have a spot o' rum, if you don't mind, and thank'ee kind sir!
They burst out laughing -- a hideous sound that wheezes through their bones.
Behind them, unnoticed, Elizabeth peeks cautiously around a corner.
She picks her moment and sneaks past quickly, down a gangway, disappearing into the blackness of the ship.
Gillette crouches, running low behind a line of rocks.
He reports to Norrington:
GILLETTE All the men in place, sir.
GILLETTE Ready to fire.
NORRINGTON Wait for my order -- what the blazes is that?
It's the sound of cannon fire -- coming from the Dauntless.
Cannonballs hit the shore; men cry out in anguish.
NORRINGTON (CONT'D) Men!
NORRINGTON (CONT'D) Take cover!
The sailors scramble to find refuge -
Will, guarded by pirates, glares at Jack.
WILL You've been planning this from the beginning.
WILL Since you learned my name.
Jack takes the opportunity to move toward him.
JACK Oh, please -- do I really seem that clever?
Before Will can answer, Jack smoothly slips the sword from a Pirate's scabbard -- tosses it to Will, who catches it despite his surprise.
JACK (CONT'D) Use it well.
He draws his own sword -- and clobbers the Pirate.
Barbossa and the other pirates stare in shock -
BARBOSSA Confound it, Jack -- I was actually beginning to like you!
Swords are drawn, and the Pirates attack.
Jack and Will take on multiple opponents, each with his own style: Will parries, glissades and disarms with lightning fast and perfect form, while Jack uses his blade, fists, acrobatics and anything within reach to survive.
The sailors charge.
The moon emerges from behind a cloud -
Suddenly army of SKELETON PIRATES rise up from the sea, and charge the stunned sailors -- several men are struck down -
NORRINGTON Steady, men!
NORRINGTON Remember -- we're the Navy!
The sailors recover their nerve, and engage the enemy.
It's a full on battle, Royal Navy against Skeleton Pirates -
The Navy men are driven back, surrounded -
Suddenly there is a massive BOOM of cannon fire.
Norrington, in the midst of a swordfight, tries to see -
NORRINGTON (CONT'D) What is happening out there?
It's the Black Pearl, manned by Gibbs, AnaMaria and Cotton, and captained by Elizabeth, coming around the point, cannons blazing.
The pirates on the ship are caught by surprise, try to turn their cannons to this new foe -
Gillette sees the Black Pearl firing on the Dauntless.
GILLETTE They're on our side!
GILLETTE Take heart, men!
The Royal Navy stand their ground and fight -
Only two pirates left: Barbossa and Jacoby.
Jacoby rounds on Will; Barbossa faces off against Jack.
BARBOSSA Just so you know, Jack -- I don't think you're that clever.
BARBOSSA I think you're a fool.
BARBOSSA A mortal fool.
JACK Remarkable how often those two traits coincide.
Jack drives him back, making Barbossa laugh.
BARBOSSA You can't beat me, Jack.
To prove his point, he drops his own sword -- and catches Jack's sword with both hands.
Jack can't free it.
Barbossa twists the sword from Jack's grip, reverses it -
Will battling Jacoby, sees it -- he smashes Jacoby in the jaw, crumpling him
WILL Jack!
Jack stares down at the sword jutting from his chest.
He takes a few steps backward, toward the Aztec gold -- when he steps into the moonlight, JACK BECOME SKELETAL.
JACK Well, isn't that interesting.
Skeleton Jack pulls the sword from his chest.
He pulls something from his pocket: one of the Aztec coins.
JACK (CONT' D) They're so pretty, I just couldn't resist stealing one.
JACK (CONT' D) It's a curse, I guess.
Barbossa grabs up his sword, and rushes Jack.
Both men are in moonlight now, two skeletons in pitched battle.
BARBOSSA So what now, Jack Sparrow?
BARBOSSA Are we to be two immortals, locked in epic battle until the trumpets of Judgment Day?
JACK Or you could surrender.
He shoves Barbossa back, out of the moonlight.
Barbossa stalks the room, his attention focused on Jack.
BARBOSSA Or I could chain you to a cannonball and drop you in the deepest part of the ocean, where you can contemplate your folly forever.
Barbossa charges -
Jack stands out of the moonlight, flesh and blood again, holding his smoking pistol, still aimed at Barbossa.
BARBOSSA (CONT'D) Hah.
BARBOSSA (CONT'D) Ten years you carried that pistol, and you end up wasting your shot.
WILL He didn't waste it.
Will stands over the Aztec chest, holding a bloody sword, his left hand in a fist.
He opens the fist -
-- the medallion, blood covering it, drops from his hand, revealing the cut in his palm.
Barbossa stares, then looks down at his chest.
Blood blossoms on his shirt around the bullet hole.
It spreads quickly.
Barbossa clutches his chest, his face registering pain for the first time in years.
Barbossa falls heavily to the ground, dead.
Jack blows the smoke from the barrel of his pistol...
tosses it away.
Murtogg FIRES a pistol at a pirate.
The pirate is hit, screams in pain, and crumples to the ground.
Mullroy runs through another with his sword.
The pirates react to the sight, and quickly realize their peril.
They set their weapons down in surrender.
The Black Pearl comes alongside the Dauntless, and Jack's crew swarm across, overwhelming the pirates.
The sailors on the beach see it, and CHEER.
Will wraps a cloth around his palm; Jack joins him near the chest.
WILL Well, you're the worst pirate I've ever heard of.
WILL You're a man who can be trusted, who can be counted on, and who can It betray his friends.
WILL What kind of pirate is that?
JACK The worst.
JACK On the other hand, maybe I'm a man who can't pass up a chance for revenge against the black-hearted bastard who stole my ship and left me to die in the middle of the ocean -- twice!
JACK -- and who knows how to get what he wants.
JACK Now that's a great pirate.
Jack cuts his palm, grips the coin he stole above the chest ...
and then hesitates.
Will looks at him...
Jack releases the coin.
It lands in the chest beside the other bloody coin.
Suddenly, the lid of the chest, all on its own, SLAMS SHUT.
Elizabeth stares at it.
WILL Let's get out of here.
Jack, Will, and Norrington gather together on the beach.
Elizabeth calls out:
ELIZABETH You're all right!
The three men turn as one.
An awkward moment -- which of them does she mean?
Elizabeth races across the sand, toward them -- and straight to Will.
She throws her arms around his neck in a hug.
WILL Miss Swann -- are you wearing trousers?
WILL And how did you get off the island?
Elizabeth can't believe that's what he noticed.
Indignant, she steps away from him.
ELIZABETH Yes, I am wearing trousers.
ELIZABETH And as for how we got off the island -- ah, that's a grand adventure, but now is not the time to talk about it.
She reaches a hand behind his neck, decisively kisses him.
ELIZABETH (CONT'D) There.
ELIZABETH (CONT'D) And don't you dare tell me that wasn't a proper kiss!
WILL Elizabeth, I think it doesn't matter- that we are of a different class -
ELIZABETH It doesn't!
WILL -- but that was not a proper kiss.
Pure consternation on Elizabeth's face -
WILL (CONT'D) This is a proper kiss.
Will sweeps her in his arms, leans her back, and kisses her long and well -
Jack puts a hand on Norrington's shoulder.
JACK Tough luck.
JACK I was rooting for you.
Close on: Will's face, stoic, staring forward.
He stands straight and unmoving.
Around him are members of the Royal Navy, standing before for a group of witnesses from town.
It is the courtyard on the top of Fort Charles.
A trial is underway -- with Will as the defendant.
NORRINGTON ...and though I do say so with regret, the law is clear.
NORRINGTON The penalty for piracy is death by hanging.
In the crowd, Elizabeth squeezes the hand of her father, Swann.
She lets go as Swann stands.
SWANN By your leave, I wish to speak on behalf of the boy.
SWANN It is clear that these deeds were performed out of a sincere desire to do good, at great personal risk.
SWANN It seems to me, that in the rare occasion where the right course is committing an act of piracy, then an act of piracy is the right course!
SWANN So in my capacity as Governor, I intend to grant a pardon to --
GILLETTE Sir!
All eyes turn.
Gillette stands at the top of a stairway.
GILLETTE (CONT'D) Jack and his crew have escaped!
GILLETTE (CONT'D) There was no damage to the cell ...
GILLETTE (CONT'D) they must have been set free.
Will and Elizabeth exchange looks.
You?
Not me, you?
No, not me either!
Swann notices something the parapet, points -
SWANN The Black Pearl!
People rush to the parapet.
Sure enough, below in the bay are the distinctive black sails of the Pearl.
The ship cuts through the waters very close to the point -
-- where the gallows of the pirates are.
Suddenly Jack appears, on the point; he swings off the one empty gallows, across and down onto the ship's rigging as it passes.
GILLETTE Sir!
GILLETTE Shall I break out the cannons?
NORRINGTON I don't think that will be necessary.
Norrington raises his hand ...
twirls a key on his finger.
NORRINGTON (CONT'D) A day's head start.
NORRINGTON (CONT'D) That's all he gets.
Will, Elizabeth and Swann look out toward ocean-
Jack monkeys down the rigging.
AnaMaria is at the wheel.
ANAMARIA Captain Sparrow -- the Black Pearl is yours!
Jack runs a hand lovingly along the rail, then takes the wheel.
It feels good -- right -- in his hands.
He enjoys it, and then shifts to 'Captain' mode.
JACK AnaMaria, trim the mainsail!
ANAMARIA Aye, aye, sir!
JACK Mr. Gibbs, organize a cleaning detail - you and Cotton.
JACK I want every inch of the Pearl spic-and-span and ship-shape!
Gibbs actually stomps the deck, executes a salute.
Jack stands at the wheel: he's got his ship back, and all is right with the world.
He begins to unconsciously hum: "Yo, ho, yo, ho, a pirate's life for me ..."
He realizes what he's doing and smiles, the orchestra takes over as the Black Pearl sails for uncharted waters ...
and we FADE UP large words in script:
THE END FADE OUT and CREDITS ROLL
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
