SERENITY
Written by
Joss Whedon
April 18, 2004
EXT. CLASSROOM - DAY It's a group of twelve-year-olds, serious and well dressed.
EXT. CLASSROOM - DAY They sit on their heels under a sparsely elegant tent, small wooden desks with embedded screens in front of them.
EXT. CLASSROOM - DAY The tent is on a lawn surrounded by lush foliage.
EXT. CLASSROOM - DAY People walk about and vehicles glide quietly overhead.
EXT. CLASSROOM - DAY A utopian vista.
GIRL Now that the war's over, our soldiers get to come home, yes?
TEACHER Some of them.
TEACHER Some will be stationed on the rim planets as Peace Enforcers.
I don't understand.
Why were the Independents even fighting us?
Why wouldn't they look to be more civilized?
TEACHER That's a good question.
TEACHER Does anybody want to open on that?
GIRL I hear they're cannibals.
ANOTHER BOY That's only Reavers.
Reavers aren't real.
ANOTHER BOY Full well they are.
ANOTHER BOY They attack settlers from space, they kill them and wear their skins and rape them for hours and hours --
It's true that there are...
dangers on the outer planets.
So let's follow up on Borodin's question.
With all the social and medical advancements we can bring to the Independents, why would they fight so hard against us?
RIVER We meddle.
TEACHER River?
TEACHER RIVER is a dark, intense little girl, writing with one hand and "typing" with the other.
She is a good two years younger than the other kids.
RIVER People don't like to be meddled with.
RIVER We tell them what to do, what to think, don't run don't walk we're in their homes and in their heads and we haven't the right.
RIVER We're meddlesome.
TEACHER (gently taking her
River, we're not telling people what to think.
We're just trying to show them how.
She violently PLUNGES the stylus into the girl's forehead
And we FLASH CUT to the actual present: a 16 year old RIVER sitting in a metal chair, needles stuck in her skull (one right where the teacher had stuck her) being adjusted by a technician.
A second monitors her brain patterns.
The lab is cold, blue, steel.
Insidiously clean.
2ND TECHNICIAN She's dreaming.
Nightmare?
2ND TECHNICIAN Off the charts.
2ND TECHNICIAN Scary monsters.
DOCTOR MATHIAS Let's amp it up.
DOCTOR MATHIAS Delcium, eight- drop.
DOCTOR MATHIAS DOCTOR MATHIAS is not instantly likable -- nor gradually, for that matter.
DOCTOR MATHIAS A cold man, and more than a little satisfied with himself.
Behind him stands a GOVERNMENT INSPECTOR, observing.
And making him a little nervous.
The Inspector is in shadow, but his uniform indicates -- no substantial rank, as does the eagle-crested baton longer than a ruler -- that he clutches in one gloved hand.
See, most of our best work is done when they're asleep.
We can monitor and direct their subconscious, implant suggestions...
River starts convulsing, mewing in misery.
The Inspector starts forward, slowly.
It's a little startling to see, but the results are spectacular.
Especially in this case.
River Tam is our star pupil.
The Inspector steps into the light.
He is rigid, cold, staring at the girl with no emotion at all.
His name, as we will very soon learn, is SIMON.
SIMON I've heard that.
DOCTOR MATHIAS She's a genius.
DOCTOR MATHIAS Her mental capacity is extraordinary, even with the side-effects.
SIMON Tell me about them.
DOCTOR MATHIAS Well, obviously, she's unstable...
DOCTOR MATHIAS the neural stripping gives them heightened cognitive reception, but it also destabilizes their own reality matrix.
DOCTOR MATHIAS It manifests as borderline schizophrenia...
DOCTOR MATHIAS which at this point is the price for being truly psychic.
SIMON What use do we have for a psychic if she's insane?
DOCTOR MATHIAS I don't have to tell you the security potential of someone who can read minds.
DOCTOR MATHIAS And she has lucid periods -- we hope to improve upon the...
DOCTOR MATHIAS I'm sorry, Sir, I have to ask if there's some reason for this inspection.
Am I making you nervous?
DOCTOR MATHIAS Key members of Parliament have personally observed this subject.
DOCTOR MATHIAS I was told their support for the project was unanimous.
DOCTOR MATHIAS The demonstration of her power --
SIMON How is she physically?
DOCTOR MATHIAS Like nothing we've seen.
DOCTOR MATHIAS All our subjects are conditioned for combat, but River...
DOCTOR MATHIAS she's a creature of extraordinary grace.
SIMON Yes.
SIMON She always did love to dance.
SIMON He drops to one knee, slamming his baton to the floor.
As the top pops off like a bouncing betty (the grenade), flying up over Simon and River's heads and then bursting forth in a flat circle of blue energy that bisects the room, flowing through the staff's heads and knocking them out.
Simon rushes to River, gently removes the probes from her head and swabs her, whispering:
River.
Wake up.
Please, it's Simon.
River.
It's your brother.
Wake up...
She begins to stir as a noise moves him to the door, looking out and removing his uniform to reveal an orderly's tunic beneath.
River is suddenly next to him.
He jumps a little.
RIVER Simon.
RIVER A beat, as they face each other, Simon fighting emotion.
They know you've come.
As a guard looks at a monitor.
He mostly resembles a secret service man -- more bureaucrat than thug.
A second man rolls into frame on a chair behind him, also watching the screen.
Simon walks River through the corridor.
They approach a pair of double doors.
SIMON We can't make it to the surface from inside.
SIMON Simon turns suddenly as he hears footsteps, people heading at them from the other side of the doors.
SIMON 4wo SIMON
Find a -- But River has, impossibly, scampered up over some lab equipment to the dark top of the corridor, where she holds herself in a perfect split, feet against the walls and outstretched hand holding the sprinkler for support.
The doors burst open and two doctors pass by, hardly noticing the lone orderly.
Passing right under River.
It's small, 15 feet by 15 feet.
Goes a long way up and a long way down.
One wide hinged window looks in on the hall inside.
Simon and River approach with quiet haste.
They slip through the window.
Simon shuts it, wedges his baton into the handle as the SECURITY AGENTS APPROACH.
They fire at the glass, but their lasers have no effect.
Wind whips River's hair about as she looks up to see a small patch of daylight visible ten stories up.
Sees the sky blotted out by a small ship that hovers above them.
ANGLE: THE SHIP is floating over the grass of rolling hills, the city gleaming far beyond.
This facility is well hidden.
A gurney-sized section of the ship's belly detaches and drops down ten stories, cables spooling it out of the ship.
It comes to Simon and River and stops suddenly.
SIMON Get on!
SIMON He is standing by the window -- and the Security Agent is right behind him, PUNCHING the window with all his might.
SIMON Simon helps River onto the gurney, then jumps on himself as the Security Agent cracks the glass.
SIMON The two are whisked up in the gurney, River on her knees, Simon standing beside her holding one of the cables --
THE OPERATIVE Stop.
THE OPERATIVE The action freezes.
Lovely.
Lovely.
Backtrack.
The action REVERSES, taking us back to the moment of Simon and River on the gurney just before it rises.
f t o
Stop.
There is a motionless beat, River frozen in that crouch, and he steps through what we now see is a hologram of the event.
The Government's man.
We'll just call him THE OPERATIVE.
He is thoughtful, a little removed.
Wire-rimmed glasses, a suit too nondescript to be a uniform, too neat to be casual wear.
He is in:
-- which is long and bare but for drawers of holographic records, a set-up for watching recordings (where the image of Simon and River floats), and a table with computer and chair.
The Operative crosses to the table, looks over some papers.
THE OPERATIVE Biograph.
THE OPERATIVE Simon Tam.
As Simon's history files down in print and pictures -- graduation, security photo from his medical internship -- over one lens of the Operative's glasses.
Remarkable children.
Doctor Mathias storms in, two security men (not the ones from the opening) and a nervous young female intern following.
Mathias looks greyer and more gaunt than when we saw him last.
DOCTOR MATHIAS Excuse me!
DOCTOR MATHIAS No one is allowed in the records room without my express permission.
THE OPERATIVE Enter the doctor.
THE OPERATIVE Forgive me.
THE OPERATIVE I prefer to see the event alone, without bias.
THE OPERATIVE Mathias looks at the hologram -- realizes which one it is.
DOCTOR MATHIAS I need to see your clearance.
THE OPERATIVE You're right to insist.
THE OPERATIVE I know you've had security issues here.
THE OPERATIVE He places his hand on a screen as he says it.
THE OPERATIVE Mathias looks at the readout, and drops the bluster.
DOCTOR MATHIAS Apologies.
DOCTOR MATHIAS An Operative of the Parliament will of course have full cooperation.
DOCTOR MATHIAS I'm not sure what...
DOCTOR MATHIAS I see no listing of rank, or name.
THE OPERATIVE I have neither.
THE OPERATIVE Like this facility, I don't exist.
THE OPERATIVE The Parliament calls me in when...
THE OPERATIVE when they wish they didn't have to.
THE OPERATIVE Let's talk about the Tams.
DOCTOR MATHIAS I assume you've scanned the status logs...
THE OPERATIVE River was your greatest success.
THE OPERATIVE A prodigy -- A phenomenon.
THE OPERATIVE Until her brother walked in eight months ago and took her from you.
DOCTOR MATHIAS It's not quite so simple.
THE OPERATIVE I'm very aware of that.
DOCTOR MATHIAS He came in with full creds.
DOCTOR MATHIAS He beat the ap-scan, the retinal...
DOCTOR MATHIAS There was no way I could --
THE OPERATIVE No, no.
THE OPERATIVE Of course.
THE OPERATIVE The boy spent his fortune developing the contacts to infiltrate this place.
DOCTOR MATHIAS Gave up a brilliant future in.
DOCTOR MATHIAS medicine as well, you've probably read.
DOCTOR MATHIAS Turned his back on his whole life.
DOCTOR MATHIAS Madness.
THE OPERATIVE Madness, no.
THE OPERATIVE Something a good deal more dangerous.
THE OPERATIVE Have you looked at this scan carefully?
THE OPERATIVE At his face?
THE OPERATIVE Mathias looks uncertain.
It's love, in point of fact.
He loved his sister and he knew she was in pain.
So he took her somewhere safe.
DOCTOR MATHIAS Why are you here?
THE OPERATIVE I'm here because the situation is even less simple than you think.
THE OPERATIVE Do you know what your sin is, Doctor?
DOCTOR MATHIAS I.
DOCTOR MATHIAS I would be very careful about what you --
It's pride.
He touches the computer screen and the hologramic image jumps to the Doctor and Simon in the lab, Mathias repeating:
DOCTOR MATHIAS Key members of Parliament have personally observed this subject.
DOCTOR MATHIAS I was told their support --
THE OPERATIVE Key members of Parliament.
THE OPERATIVE Key.
THE OPERATIVE The minds behind every diplomatic, military and covert operation in the galaxy, and you put them in a room with a psychic.
DOCTOR MATHIAS She was...
DOCTOR MATHIAS she read cards, nothing more.
THE OPERATIVE It's come to our attention that River became much more unstable, more...
THE OPERATIVE disturbed, after you showed her off to Parliament.
THE OPERATIVE Did she see something very terrible in those cards?
DOCTOR MATHIAS Whatever...
DOCTOR MATHIAS secrets she might have accidentally gleaned...
DOCTOR MATHIAS it's probable she doesn't even know she knows them.
DOCTOR MATHIAS That they're buried beneath --
THE OPERATIVE But they are in her.
THE OPERATIVE Her mind is unquiet.
THE OPERATIVE It's the will of the Parliament that I kill her.
THE OPERATIVE And the brother.
THE OPERATIVE Because of your sin.
THE OPERATIVE You know, in certain older civilized cultures, when men failed as entirely as you have, they would throw themselves on their swords.
DOCTOR MATHIAS Well, unfortunately I forgot to bring a sword to -- The air rings crisply as the Operative pulls out his sword.
THE OPERATIVE The Parliament has no further interest in psychics.
THE OPERATIVE They represent a threat to the harmony and stability of our Alliance.
DOCTOR MATHIAS I would put that down right now if I were you.
THE OPERATIVE Would you be killed in your sleep, like an ailing pet?
THE OPERATIVE Whatever your failings, I believe you deserve better than that.
THE OPERATIVE The agents move.
THE OPERATIVE He slices the throat of the one behind him with true grace, thrusting at the second as he's pulling out his gun and pinning his hand.
THE OPERATIVE A moment, and the dying agent reflexively squeezes the trigger, shooting his own arm.
THE OPERATIVE The Operative pulls out the sword and the agent falls as quietly as the first.
THE OPERATIVE Mathias bolts but the Operative pins him to the wall.
THE OPERATIVE He bunches his fingers and jabs the side of the Doctor's spine.
THE OPERATIVE Mathias stiffens, suddenly, agonizingly immobile.
THE OPERATIVE The Operative steps back, observes the Doctor's rigid grimace for a moment.
THE OPERATIVE Almost ceremoniously, he drops to one knee and holds the blade out to one side, hilt to the floor and point tilted toward the doctor.
THE OPERATIVE The Doctor stares at it in horror as his paralyzed body begins to tip over toward it.
THE OPERATIVE The Operative turns toward the terrified intern at the door.
Young miss, I'll need all the logs- on behavioral modification triggers.
We'll have to reach out to River Tam, and help her to come back to us.
No matter how far out Simon has taken her, we can -- He's almost startled when the Doctor's body drops into frame, slowed suddenly by the sword.
It squeaks down the blade, the Doctor unable to cry out, as the Operative whispers to him:
This is a good death.
There's no shame in this, in a man's death.
A man who's done fine works.
We're making a better world.
All of them, better worlds.
Mathias is dead.
The Operative pulls the sword out as the body rolls over.
As he wipes the sword down:
Young miss, I need you to get to work now.
I think I may have a long way to travel.
40 She goes.
40 He approaches River, very close, staring...
Where are you hiding,,little girl?
The noise is sucked suddenly out of the room as we black out.
becomes the name painted on the side of a spaceship, with the same in Chinese behind it.
We move away from the ship.
The name is on the nose, under the bridge.
It sticks out from the body of the ship like a craning neck.
The body is bulbous, with propulsion engines on either side and a giant glowing back.
There are two small shuttles tucked in over the 'wings' of the engines.
It's not the sleekest ship in the 'verse, to be sure.
As it hits atmo, the propulsion engines take over and she starts to rock a bit, noise filling our ears.
Camera comes around the front, at the windows and into the bridge, to see the Captain, MALCOLM 'MAL' REYNOLDS, standing and watching.
At that moment, a small piece of the nose breaks off and goes flying past the window.
INT. BRIDGE - CONTINUING [Note: the following sequence will take us through the ship in one extended STEADICAM shot.] The bridge is small: two pilot seats on either side, and a tangle of wires and machinery all about.
INT. BRIDGE - CONTINUING Mal wears the knee-length brown coat and boots of an old Independent.
INT. BRIDGE - CONTINUING Gun at his hip.
INT. BRIDGE - CONTINUING He's not unlike the ship -- he's seen a bit of the world and it left him, emotionally at least, weathered.
INT. BRIDGE - CONTINUING Right now, though, he's mostly startled.
MAL What was that?
MAL He's addressing the pilot, WASH.
MAL Flight gear and a hawaiian shirt, toy dinosaurs populating his station -- no old soldier, but just as startled.
WASH Whoah!
WASH Did you see that -- The ship bucks --
MAL Was that the primary buffer panel?
WASH It did seem to resemble --
MAL Did the Primary Buffer Panel just fall off my gorramn ship for no apparent reason?
MAL Another buck --
WASH Looks like.
MAL I thought Kaylee checked our entry couplings!
MAL I have a very clear memory of it --
WASH Yeah well if she doesn't give us some extra flow from the engine room to offset the burnthrough this landing is gonna get pretty interesting.
MAL Define "Interesting".
WASH "Oh god, oh god, we're all gonna die?"
MAL This is the Captain.
MAL There's a little problem with our entry sequence; we may experience slight turbulence and then explode.
MAL Can you shave the vector --
WASH I'm doing it!
WASH It's not enough.
WASH Kaylee!
MAL Just get us on the ground!
WASH That part'll happen, pretty definitely.
INT. FOREDECK HALL - CONTINUING The camera leads Mal down.
INT. FOREDECK HALL - CONTINUING On either side of the hall are ladders leading down to crew's personal quarters.
INT. FOREDECK HALL - CONTINUING The hulking mercenary JAYNE is coming up out of his bunk as Mal passes.
INT. FOREDECK HALL - CONTINUING He carries a number of rifles and grenades.
JAYNE we're gonna explode?
JAYNE I don't wanna explode.
MAL Jayne, how many weapons you plan on bringing?
MAL You only got the two arms...
JAYNE I just get excitable as to choice, like to have my options open.
MAL I don't plan on any shooting taking place during this job.
JAYNE Well, what you plan and what takes place ain't ever exactly been similar.
MAL No grenades.
MAL No grenades.
MAL First Mate ZOE enters from the lower level.
MAL Her mode of dress and military deference mark her as a war buddy of Mal's.
ZOE Are we crashing again?
MAL Talk to your husband.
MAL Is the mule prepped?
ZOE Good to go, sir.
ZOE Just loading her up.
ZOE Are those grenades?
JAYNE Cap'n doesn't want 'em.
ZOE We're robbing the place.
ZOE We're not occupying it.
All that plays in the background as we lead Mal into the:
INT. DINING ROOM - CONTINUING It's the communal space of the ship, homey and messy.
INT. DINING ROOM - CONTINUING There is food left lying on the table.
INT. DINING ROOM - CONTINUING Mal swipes a dumpling from a plate, pops it in his mouth as another jolt rocks him and sends most of the tableware clattering to the floor.
MAL Kaylee!
He enters:
MAL Kaylee, what in the sphincter of hell are you playing at?
MAL The hall leads to the rust-brown chaos that is the engine room.
MAL Working around the engine in a forest of wires, sparks and smoke is the sweetly pretty mechanic, KAYLEE.
MAL She passes Mal with a slightly impatient smile as he stands in the doorway, raising his voice above the din.
We got the Primary Buffer
KAYLEE Everything's shiny, Cap'n.
KAYLEE Not to fret.
MAL You told me --
You told me the entry couplings would hold for another week!
That was six months ago, cap'n.
MAL My ship don't crash.
MAL If she crashes, you crashed her.
Steam and electricity shoot at him, backing him up.
He turns to see Simon behind him.
Simon is more seasoned than before, but still contrasts the Captain entirely in dress and manner.
He is implacably proper.
Also pissed.
Doctor.
Guess I need to get innocked 'fore we hit planetside.
Simon nods, the ship jolting again.
Bit of a rockety ride.
Nothing to worry about.
SIMON I'm not worried.
MAL Fear is nothing to be ashamed of, Doc.
SIMON This isn't fear.
SIMON This is anger.
Well, it's kinda hard to tell the one from t'other, face like yours.
SIMON I imagine if it were fear, my eyes would be wider.
MAL I'll look for that next time.
SIMON You're not taking her.
MAL No no, that's not a thing I'm interested in talking over with --
SIMON She's not going with you.
SIMON That's final.
MAL I hear the words "that's final" come out of your mouth ever again, they truly will be.
MAL This is my boat.
MAL Y'all are guests on it.
He heads down a side corridor that has steps leading down to:
INT. PASSENGER DORM - CONTINUING Simon is right on his heels as we lead them down the stairs.
SIMON Guests?
SIMON I earn my passage, Captain --
MAL And it's time your little sister learned from your fine example.
SIMON I've earned my passage treating bullet holes, knife wounds, laser burns...
MAL Some of our jobs are trickier than others --
SIMON And you want to put my sister in the middle of that.
MAL Didn't say 'want'.
MAL Said 'will'.
MAL It's one job, Doc.
MAL She'll be fine.
MAL The passenger dorm has a time-worn warmth that most of the
ship shares.
Except, of course, for the sterile blue of:
Into which the two men step.
SIMON She's a seventeen year old girl.
SIMON A mentally traumatized sevente--
MAL She's a reader.
MAL Sees into the truth of things; might see trouble before it's coming.
MAL Which is of use to me.
SIMON And that's your guiding star, isn't it?
SIMON What's of use.
Honestly, doctor, I think we may really crash this time anyway.
Simon jabs the inoculation needle into Mal's arm.
SIMON Do you understand what I've gone through to keep River away from the Alliance?
MAL I do, and it's a fact me and mine have been courteous enough to keep to our own selves.
SIMON Are you threatening to --
MAL I got one purpose here: keep this boat in the air.
MAL I take the jobs I get -- which is less and less, case you ain't been keeping track.
MAL He starts away, Simon still keeping pace.
Every year since the war the Alliance pushes just a little further out towards the rim.
Makes it a chore for naughty men like us to slip about -- and keeping you two on board means working twice as hard to avoid the law.
Means turning down a score of honest jobs.
INT. CARGO BAY - CONTINUING They enter the biggest space on the ship.
INT. CARGO BAY - CONTINUING Giant doors sit at the front, which will open upon landing to reveal a lowering ramp.
INT. CARGO BAY - CONTINUING Catwalks surround the space, leading up at the front to the foredeck hall.
INT. CARGO BAY - CONTINUING We've come all the way through Serenity.
MAL So here is us, on the raggedy edge.
MAL Don't push me and I won't push you.
Simon starts up the stairs as Mal calls to him:
Things get gritty I will keep her from the fray, but she's coming.
Best you get her ready.
As Mal walks on, we tilt up to see the Mule, a four-man hovercraft hanging from chains near the ceiling.
Jayne and Zoe are tossing duffle bags into it.
Zoe, is Wash gonna straighten this boat out before we get flattened?
ZOE Like a downy feather, sir.
ZOE Nobody flies like my mister.
ZOE The camera picks up Simon's feet as they enter foreground on
the catwalk, and track with them to find:
SIMON River...
SIMON She's lying on her side, looking straight at us.
SIMON A loose summer dress draped over her small frame.
RIVER I know.
RIVER We're going for a ride.
Serenity settles gently down as the cargo bay door opens.
INT. CARGO BAY - CONTINUING The chains are hoisted back up into the ceiling of the ship.
INT. CARGO BAY - CONTINUING The mule floats just above the floor, Jayne piling in next to
River in the back:
SIMON Now, River, you stay behind the others.
SIMON If there's fighting you drop to the floor or run away.
SIMON It's okay to leave them to die.
SIMON River puts on a huge pair of goggles, looks at her brother.
RIVER I'm the brains of the operation.
ZOE We should hit town right during Sunday worship.
ZOE Won't be any crowds.
MAL If Fanty and Mingo are right about the payroll, this could look to be a sunny day for us.
Captain, I'll ask you one last time...
MAL Doctor, I'm taking your sister under my protection here.
MAL If anything happens to her, anything at all, I swear to you I will get very choked up.
MAL Honestly.
MAL There could be tears.
MAL He peels out, leaves Simon fuming.
MAL Kaylee sidles up to him...
KAYLEE Don't mind the Captain none, Simon.
KAYLEE I know he'll look out for her.
SIMON It's amazing.
SIMON I bring River all the way out to the raggedy edge of the 'verse so she can hide from the Alliance by robbing banks.
KAYLEE It's just a little Trading Station.
KAYLEE They'll be back 'fore you can spit.
KAYLEE Not that you spit...
Kaylee watches him go, a tad forlorn.
We see the town sprawled before us, as the mule heads in.
The town embodies the lives of folk out here: adobe and wood mix with metal and plastic -- whatever's on hand to build with.
Right now the streets are mainly empty.
The mule pulls up, Zoe hitching it as they speak:
JAYNE What are we hoping to find here that equals the worth of a turd?
MAL Alliance payroll.
MAL There's peace enforcing squads stationed all about this quadrant.
MAL Can't use credits out here -- they got to pay their boys in cashy money.
MAL Which once a month rests here.
ZOE Something about stealing from the Alliance just warms a body like whiskey in winter.
JAYNE Shiny.
JAYNE Let's be badguys.
JAYNE Mal turns back to River.
MAL You ready to go to work, darlin'?
RIVER There's no pattern to the pebbles here, they're completely random.
RIVER I tried to count them but you drove too fast.
RIVER Hummingbird.
MAL Right.
MAL Great.
MAL Let's go.
We are in a camera's eye view, right above the door.
The door slams open, Mal and Jayne stride in, Zoe following and whipping her hogleg right at camera without looking.
Reverse to see the camera is also a small screen with "Welcome to Lilac" on it for the millisecond before it's blown to bits.
There's maybe fifteen people in the place: store workers, farm-folk and a couple dirt-poor kids.
It's a combination post-office, general store, bank, and most other things.
MAL Hands and knees and heads bowed down!
MAL Everybody, now!
MAL Two men who appear to be farm folk rush Mal and the others.
MAL Mal draws on the elder one and he stops dead in his tracks.
MAL Mal's gun is long, not unlike Civil War era issue, but very much new in design.
MAL The other tries to tackle Jayne, which is not necessarily a great idea.
MAL Jayne clotheslines him so hard he spins right upside-down -- and Jayne grabs him by the legs and CRACK!
MAL -- bounces his head right off the floor, knocking him out cold.
Y'all wanna be looking very intently at your own belly buttons.
I see a head start to rise, violence is gonna ensue.
The guy who rushed Mal complies along with everyone else.
Jayne dumps his catch on the floor and rips open his dirty shirt to reveal the purple of an Alliance uniform.
JAYNE Looks like this is the place.
JAYNE He looks up at Mal, who motions for Zoe to open the front door.
JAYNE She does, and River steps in.
JAYNE ANGLE: RIVER'S BARE FEET -- walking slowly among the hunched- over customers as Mal addresses them.
MAL You've probably guessed we mean to be thieving here, but what we are after is not yours.
MAL So let's have no undue fussing.
MAL As he is speaking, Jayne is scrambling to the back office, finding the small vault locked.
JAYNE She's locked up.
JAYNE River suddenly looks around, perturbed.
JAYNE CLOSE ON: a young tough.
JAYNE River looks up at Zoe, alarmed, and silently points to the young man.
JAYNE He is slowly reaching for the weapon in his belt.
JAYNE He finds Zoe's sawed-off nuzzling his cheek.
ZOE You know what the definition of a hero is?
ZOE It's someone who gets other people killed.
ZOE You can look it up later.
ZOE He drops his weapon, slides it across the floor.
ZOE Mal moves to the Trade Agent.
ZOE Hauls him up, tosses him toward the vault.
ZOE Zoe and Jayne follow.
TRADE AGENT This is just a crop moon, don't think you'll find what you --
140 The old man punches in the code.
140 What opens is a tiny wall safe.
140 Bundles of bills, some scattered coin.
140 Unimpressive.
140 Jayne and Zoe are behind the captain, peering in.
ZOE At last.
ZOE We can retire and give up this life of crime.
ZOE Mal reaches in, pulls a lever and the floor opens, a six foot hole appearing, stairs leading to a corridor, all gleaming metal and blue light.
ZOE Zoe smiles.
ZOE Jayne peers down as Mal addresses the Trade Agent.
MAL Is there a fed down there?
MAL Be truthful.
Y'all are Browncoats, hey?
Fought for independence?
MAL War's long done.
MAL We're all just folk now.
MAL Listen up!
MAL We are coming down to empty that vault!
MAL The voice of a young Alliance GUARD comes up from below.
GUARD You have to give me your authorization password!
GUARD Jayne impatiently fires a burst of machine-gun fire down into the hole.
GUARD A beat...
Okay...
Mal looks at Zoe and they head down into:
Which is as modern as something off the Central Planets.
A short corridor leads to a real vault door, that the guard is already opening.
Behind that door, a few bags of the real deal: neatly stacked cash, waiting to be robbed.
INT. TRADING STATION - CONTINUING We move in on River as something crosses her face.
INT. TRADING STATION - CONTINUING Worry.
A WOMAN carrying a bucket and her nine year old SON are looking at the trading station a few buildings away.
Repeater.
Did sound summat like gunblast...
Maybe you aught run tell Lawman...
She turns and right by her, in the shadows, is a man.
Mostly.
He is hideously disfigured, a combination of self- mutilation and the bubbling red of radiation poisoning.
His clothes are rags, his eyes pinpoints of glazed madness.
A blade blurs through frame...
INT. TRADING STATION - CONTINUING River SCREAMS and flops onto her back, pinned by revelation.
INT. TRADING STATION - CONTINUING Others look at her, concerned, as Jayne makes his way to her.
JAYNE What the hell is up?
JAYNE You all right?
JAYNE What's goin' on?
JAYNE He holds her, as she whispers, wide-eyed...
RIVER Reavers.
Zoe is hauling out the last of five bags as Mal talks to the guard, holding his gun at him:
MAL Leg's good, it'll bleed plenty and we avoid any necessary organs...
GUARD I was thinking more of a graze..
MAL Well you don't want it to look like you just gave up...
MAL Every heist, he's gotta start yelling my name --
JAYNE Mal!
JAYNE Reavers!
JAYNE The girl's pitchin' a fit.
JAYNE They're here or they're comin' soon.
JAYNE He is already loading up with bags as Mal thinks quickly.
MAL Get on the mule.
MAL (to the guard, pointing to the
Does that open from the inside?
GUARD Whah -ah- yes...
MAL You get everyone upstairs in there and you seal it.
MAL Long as you got air you don't open up, you understand?
GUARD I -- Buh I --
Mal is in his face, dark and huge:
The doors burst open, Jayne and Zoe coming out first, Mal behind with River in hand.
She is freaked, in her own space.
Jayne and Zoe throw the bags on --
MAL Zoe take the wheel --
JAYNE You see 'em?
JAYNE Anybody see 'em?
JAYNE 1J -- and jump on themselves, Mal scanning the area as he hands River up to Jayne's care.
JAYNE As the craft powers up, slowly moving, the young man Zoe kept from trying to pull his weapon bursts out of the station, grabbing the back of the mule.
YOUNG MAN Take me with you!
MAL Get in the vault with the others --
YOUNG MAN I can't stay here!
YOUNG MAN Please!
MAL It's too many.
MAL Drive, Zoe.
MAL A Reaver craft ROARS over their heads.
MAL It's nearly the size of Serenity.
MAL Torn apart, belching smoke -- a welded conglomeration of ruined ships, painted for war.
MAL Predator, pure.
MAL It disappears over the rooftops.
MAL Drive!
MAL Zoe's face is set with unhappy determination as she floors it, shooting out and leaving the young man in the dust.
MAL As they move from him, four Reavers jump out of the shadows and grab the young man.
MAL Mal unhesitatingly draws his gun.
MAL He nudges a lever with his thumb and a cartridge pops back.
MAL Mal fires twice.
MAL The young man takes both bullets in the chest, slumps down dead.
As the mule shoots past the last building, we see a skiff shoot out from behind the buildings of the adjacent street, right abreast of our gang.
We see the church as the first ship and an even larger one come to hover over it, Reavers dropping down on cable lines to swarm into it.
EXT. DESERT - CONTINUING The mule and the skiff are booking through the rocky terrain.
EXT. DESERT - CONTINUING The skiff swings closer, but Jayne peppers it with automatic fire and it swings away.
EXT. DESERT - CONTINUING There is sporadic return fire.
JAYNE How come they ain't blowing us out of the air?
MAL They wanna run us down.
MAL The up- close kill.
MAL River is squashed down on her back, being very small.
RIVER They want us alive when they eat us.
JAYNE Boy, sure would be nice if we had some grenades, don'tchya think?
JAYNE Mal says nothing, keeps firing.
ZOE Wash, baby can you hear me?
Wash is in a frenzy of switchflipping, prepping for take-off.
WASH We're moments from air.
WASH You got somebody behind you?
We intercut Wash and Zoe at this point:
ZOE Reavers.
ZOE We're not gonna reach you in time.
WASH Just keep moving, honey.
WASH We're coming to you.
EXT. SERENITY - CONTINUING As she lifts off and starts heading toward the others.
EXT. DESERT - CONTINUING Zoe gets the mule in front but a harpoon thwinngs through the air from the skiff and S} NK!
EXT. DESERT - CONTINUING Goes through Jayne's leg..
EXT. DESERT - CONTINUING The harpoon grips the leg and pulls -- Jayne goes flying off the back of the Mule, Mal just grabbing him as the harpoon line reels slowly tighter --
MAL Grab on!
MAL Jayne grabs the Mule, legs dangling, pulled out between the two vessels as Mal slams a new cartridge into his pistol.
JAYNE I won't get et!
JAYNE You shoot me if they take me!
JAYNE Mal steadies himself and takes aim, seemingly at Jayne --
Well don't shoot me first!
Mal fires.
Again.
Steadies himself for one more...
The line holding the harpoon is split by Mal's third shot.
The mule surges forward as Jayne drags on the ground.
Mal hauls him in as River bounds into the front to make room.
Rutting pigs!
Where's -- And River is holding out his weapon before he can ask for it.
Serenity rushes across the desert floor, not much higher off it than the smaller crafts.
WASH Get some distance on 'em.
WASH You come to the flats, I want you to swing round.
WASH Gonna try a Barn Swallow.
INT. BRIDGE - CONTINUING Wash hits the com.
WASH J Simon!
WASH Open the loading dock!
INT. CARGO BAY - CONTINUING Simon moves next to the huge sliding doors at the front, hits a couple of buttons.
INT. CARGO BAY - CONTINUING The doors pull open, as the huge ramp beyond them opens down, letting in a rush of wind and light.
EXT. DESERT - CONTINUING The mule reaches the flats, away from the rocks.
WASH Okay, baby, we've talked this through...
ZOE Talkin' ain't doin'.
ZOE She throws the wheel and the mule comes hard about, fishtailing slightly as it faces the oncoming skiff.
WASH Don't slow down!
As it heads for the mule --
As it heads for the skiff -- and Serenity swoops down out of the sky, bay doors open, and comes right up behind it -- The Mule swallowed by the bigger ship --
INT. CARGO BAY - CONTINUING And only its forward momentum keeps it from being squashed as it flies backwards into the bay, narrowly missing Simon and smashing back into the staircase, sparks and people flying --
EXT. DESERT - CONTINUING Serenity tries to get altitude -- but slams right into the oncoming skiff, tearing it apart --
INT. CARGO BAY - CONTINUING A flaming portion of the top flies in, skids to the floor as small fires erupt from the mule as well -- Simon pulls a lever and jets of C02 shoot out of the floor.
INT. CARGO BAY - CONTINUING Simon hits the button to start the outer ramp closing, then runs to the mule.
INT. CARGO BAY - CONTINUING The C02 stops and he finds River sitting in her seat, completely unharmed.
INT. CARGO BAY - CONTINUING Zoe is climbing painfully out of the other seat, Mal and Jayne both having been thrown.
SIMON River?
RIVER I swallowed a bug.
RIVER Kaylee runs in to see how everyone is.
RIVER She goes to Simon.
KAYLEE Are you okay?
MAL Is he okay?
MAL A bloodied Reaver POPS into frame from under the skiff-top.
MAL He lunges for Mal, baring sharpened teeth -- Mal spins and draws, fires into his belly as Jayne and Zoe both fire at the same time.
MAL The freak takes too long to go down, but down he goes.
MAL Dies sitting against the s i op.
MAL 4 Everybody takes a moment to look at each other.
WASH We all here?
WASH What's going on?
WASH Hello?
WASH r./ ZOE
WASH No casualties.
WASH Anybody following?
WASH Nice flying, baby, and that's a negative.
WASH Clean getaway -- Out of atmo in six minutes.
MAL Set course for Beaumonde.
MAL First thing, I want these bod -- Simon suddenly punches him in the face, causing Mal to stumble back, and Simon to shake his hand in pain.
SIMON You stupid, selfish, son of a whore ---
MAL I'm a hair's breadth from riddling you with holes, Doctor --
SIMON "One simple job!
SIMON She'll be fine!"
MAL She IS fine!
MAL Except for bein' still crazy, she's the picture of health!
ZOE Wasn't for River, we'd probably be left there.
ZOE She felt 'em coming.
SIMON Never again.
SIMON You understand me?
MAL Seems I remember a talk about you giving orders on my boat.
SIMON Well sleep easy 'cause we're off your boat.
SIMON Just as soon as River gets her share of the "bounty".
KAYLEE Well let's not do anything hasty...
MAL No, shiny!
MAL I'm sick a' carrying tourists anyhow.
MAL We'll be on Beaumonde in ten hours time, you can pick up your earnings and be on your merry.
MAL Meantime you do your job.
MAL Patch up my crew.
MAL A beat.
RIVER He didn't lie down.
RIVER They never lie down.
RIVER She is looking at the Reaver.
RIVER Everyone does, for a moment.
Mal and Zoe enter from below.
ZOE No, I think things'll glide a deal smoother for us without River and Simon on board...
ZOE but how long do you think they'll last?
MAL Doc made his call.
MAL They's as babes in a basket when we took 'em in; we sheltered 'em plenty.
MAL Man has to cut loose, learn to stand on his own.
ZOE Like that man back in town?
ZOE They stop by Mal Is room.
MAL I had to shoot him.
MAL What the Reavers woulda done to him before they killed him...
ZOE I know.
ZOE That was a piece a' mercy.
ZOE But before that, him begging us to bring him along...
ZOE vo,
MAL We couldn't take the weight.
MAL Woulda slowed us down.
ZOE You know that for certain
MAL Mule won't run with five.
MAL I shoulda dumped the girl?
MAL Or you?
MAL Or Jayne?
Well, Jayne...
ZOE Coulda tossed the payload.
MAL And go to Fanty and Mingo with air in our mitts, tell 'em "here's your share"?
MAL They'd set the dogs on us in the space of a twitch, and there we are back in mortal peril.
MAL We get a job, we gotta vo make good.
MAL Washenters from the bridge.
ZOE Sir, I don't disagree on any particular point, it's just...
ZOE in the time of war, we woulda never left a man stranded.
MAL Maybe that's why we lost.
MAL She's not happy with the reply.
MAL Mal climbs down to his room as Wash reaches Zoe, slides his arms around her.
INT. MAL'S ROOM - CONTINUING Once alone, Mal lets his own disappointment show.
INT. MAL'S ROOM - CONTINUING He pulls off his holster and drops it over a chair.
INT. MAL'S ROOM - CONTINUING Kicks the toilet closed and sits on his bunk.
INT. MAL'S ROOM - CONTINUING The place resembles a submarine cabin, with charts and clutter, ancient maps on the walls.
Mal moves a bunch of papers off his bunk and a picture slides out.
Hits the floor and starts moving: it's a snapshot-movie
We're close on a beautiful woman who looks at us with amused exasperation.
Behind her is an opulently dressed little shuttle.
INARA Kaylee, are you ever gonna put that capture down?
We gotta have records of everything.
A bona fide Companion entertained clients on this very ship!
In this very bed!
The picture pans over to the bed -- which River is bending over and sniffing curiously.
Inara is packing things up.
For one sweet second, we was almost classy.
INARA 4 You promised to help me pack.
KAYLEE Honest, Inara, why do you have to leave?
KAYLEE Inara shoots an uncertain look at the camera -- and the picture freezes, goes back to the beginning.
KAYLEE During all this, Mal has picked it up.
KAYLEE He looks at it a moment, tosses it aside.
KAYLEE Looks around at nothing much.
I do not get it.
How's a guy get so wrong?
We see the doors in the floor slide open, a second set below.
Pan to see, for a moment, the dead Reaver's face.
Kaylee is opening the doors with a keypad on a cable.
Jayne drags the corpse closer to the doors as he continues:
JAYNE Ain't logical.
JAYNE Cuttin' on his own face, rapin' and murdering -- I mean, I'll kill a man in a fair fight...
JAYNE or if I think he's gonna start a fair fight, or if he bothers me, or if there's a woman, or I'm gettin' paid -- mostly only when I'm gettin' paid.
JAYNE But these Reavers...
JAYNE last ten years they just show up like the boageyman from stories.
JAYNE Eating people alive?
JAYNE Where does that get fun?
JAYNE He dumps the body in, she starts the doors closing.
KAYLEE Shepherd Book said they was men that reached the edge of space., saw a vasty nothingness and just went bibbledy over it.
JAYNE Hell, I been to the edge.
JAYNE Just looked like more space.
KAYLEE I don't know.
KAYLEE People get awful lonely in the black.
KAYLEE Like to get addlepated ourselves, we stay on this boat much longer.
KAYLEE Captain'll drive us all off, one by one.
JAYNE You're just in a whinge cuz that prissy doc is finally disembarking.
JAYNE Me I says good riddance.
JAYNE He never belonged here, and his sister's no saner than one of them Reavers.
KAYLEE That ain't even so!
KAYLEE River's a dear heart and a boon to this crew!
KAYLEE You just don't like her 'cause she can read your mind and everything you think is mean.
JAYNE Well, there is that.
KAYLEE Her and Simon could have a place here.
KAYLEE Now they're leaving us.
KAYLEE Just like Shepherd Book.
KAYLEE She looks up toward one of the shuttles.
Just like Inara...
INT. COMPANION TRAINING HOUSE - DAY And here she is, moving back and down into frame, her eyes half closed in passion.
INT. COMPANION TRAINING HOUSE - DAY She settles on a cluster of brocaded pillows, and we see another head lowering in for a kiss...
INT. COMPANION TRAINING HOUSE - DAY Come around to see it's another lovely young woman -- and that there is a group of ten others watching intently, all in saris, on their knees.
INT. COMPANION TRAINING HOUSE - DAY Two handsome young men with shaved heads in the back, also on their knees.
INT. COMPANION TRAINING HOUSE - DAY Inara stops before the kiss, smiling and coming back up.
INT. COMPANION TRAINING HOUSE - DAY She speaks to the girls (We hear only soft music) as she repositions the one she's with, lowering again; showing her the motion of surrender as if it were a dance step.
They love you.
Inara looks out at the mountains.
The space she's in resembles a Tibetan monastery, if slightly more opulent.
Widen to see she is with SHEYDRA, a somewhat older Companion, the woman whose voice we heard.
She hands Inara a drink.
SHEYDRA The girls.
SHEYDRA They've learned more from you these last months than the rest of us could show them in two years.
INARA They're very sweet.
INARA But they're not Companions.
You've no hope for them?
Junk the lot, start anew?
INARA On Sihnon we started training at twelve.
INARA Years of discipline and preparation before the physical act of pleasure was even mentioned.
INARA Most of these girls --
SHEYDRA They're all of good family, the highest academic standards --
INARA Control.
INARA Was the first lesson.
INARA And the last and these worlds are not like the Central Planets.
INARA There is barbarism dressed up in the most civil weeds.
INARA Men of the highest rank who don't know the difference between a Companion and a common whore.
INARA It's unsafe.
SHEYDRA All the more reason the girls look to you.
SHEYDRA You came out here alone, before the Alliance ever thought to establish a House this remote.
SHEYDRA You've seen so much.
SHEYDRA You're a figure of great romance to them.
SHEYDRA 4d INARA Great romance has nothing to do with being a Companion, Sheydra.
SHEYDRA You should know better.
SHEYDRA I'm not the one who had a torrid affair with a pirate.
SHEYDRA Inara nearly spills her drink.
INARA A who?
INARA With a what?
It's the talk of the House.
The girls all trade stories in the dorms at night.
INARA I didn't...
INARA have a pirate...
SHEYDRA In one of the stories you make love in a burning temple.
SHEYDRA I think that's my favorite.
This is unbearable.
Captain Reynolds is no pirate; he's a petty thief.
And he never laid a finger on me.
All he ever did was rent me a shuttle and be very annoying.
SHEYDRA A year on his shuttle and he never laid a finger on you.
SHEYDRA No wonder you left.
I left because -- go away.
We're no longer friends.
You're a stranger to me now.
SHEYDRA 104 I do love to watch you boil.
SHEYDRA Don't worry.
SHEYDRA The stories will fade.
SHEYDRA And your Captain Reynolds has probably gotten himself blown up by this time.
INARA Yes.
INARA That would be just like him.
Serenity touches down on the crowded atoll amidst a number of other, equally disreputable ships.
The place is filled with every kind of immigrant culture and shop imaginable.
The ramp is open and everyone is filing out, ready to hit the town.
Kaylee is talking to Simon, who has River in hand.
KAYLEE Don't talk to the barkers -- only the captains.
KAYLEE (cont'd) You look the captain in the eye, know who you're dealing with.
a?? I wish there was...
Since he doesn't know what to say, she rattles on:
KAYLEE You shouldn't aughta be so clean.
KAYLEE It's a dead giveaway you don't belong, you always gotta be tidy.
KAYLEE Don't pay anybody in advance.
KAYLEE And don't ride in anything with a Capissen 38 engine, they fall right out of the sky.
SIMON Kaylee.
SIMON She turns and heads off.
SIMON Simon starts in the other direction, but River looks after her and the others.
River...
do you want to stay with them?
It's not safe.
SIMON No, I fear it's not safe anymore.
He's heading off and doesn't hear:
RIVER For them.
We start on a CorVue screen, showing a news report.
On the screen is a shot of the town our gang robbed, now half of it a smoking ruin.
that it was a band of Reavers remains unconfirmed.
The only survivors of the massacre apparently locked themselves in the Trade Station vault until --
During this we come around to see that the screen has a blinking light behind it, come THROUGH the wiring of the back to look out at the bar, with the word "recording" in the corner.
Every screen is a camera, even down here.
40 We pick up Mal and Kaylee heading down into the bar.
40 Cutting away from the camera's view, we can looks two stories straight down as they go, to a close group of dark tables and booths and a second screen playing in the corner.
MAL It's not my fault the Doc's got no stomach for Rim living --
KAYLEE It is entirely and for all your fault!
KAYLEE If you'd given Simon a moment, just a moment where he didn't think you were gonna throw them off or turn them in, he might've --
MAL What?
MAL Swept you into his cleanly arms?
MAL Made tidy love to you?
MAL They have reached the guncheck, where Jayne and Wash have
already checked their guns.
It works like a lunch automat: Mal sticks his gun in a drawer, pulls out a chit -- the q0 drawer closes and rotates, revealing another empty one.
A large bouncer with a shockrod watches impassively.
KAYLEE (as they continue
Don't you dare joke!
You know how much I pined on Simon.
And him fair sweet on me, I well believe, but he's so worried about being found out --
ZOE Captain didn't make 'em fugitives.
KAYLEE But he coulda made 'em family!
KAYLEE Steada driving them off.
KAYLEE Steada keeping Simon from seein' I was there, when I carried such a torch and we coulda -- goin' on a year now I ain't had nothin' twixt my nethers weren't run on batteries!
MAL Oh god!
MAL I can't know that!
JAYNE 40 I could stand to hear a little more...
KAYLEE If you had a care for anybody's heart you woulda --
You knew he was gonna leave.
We never been but a way station to those two.
And how do you know what he feels?
He's got River to worry on but he still coulda shown you...
if I truly wanted someone bad enough, wouldn't be a thing in the 'verse could stop me from going to her.
KAYLEE Tell that to Inara.
KAYLEE For a moment, Mal is too shocked to react.
KAYLEE Kaylee storms out.
MINGO 4 Domestic troubles?
MINGO MINGO is young, tough -- somewhere between a gangster and a fur-trader.
MINGO Sounds lower-class British, or something like it.
FANTY Domestic troubles?
FANTY FANTY moves out from behind Mingo to reveal that he is Mingo's identical twin.
FANTY Apart from slight differences in dress, they are indistinguishable.
MINGO 'Cause we don't wanna interrupt.
FANTY A man should keep his house in order.
MAL Mingo.
MAL Fanty.
MINGO (pointing at his
He's Mingo.
,do
MAL He's Fanty.
MAL You're Mingo.
MINGO Ghahh!
MINGO How is it you always know?
MAL Fanty's prettier.
MAL Feel to do some business?
MINGO Bit crowded, isn't it?
MINGO As you see, we come unencumbered by thugs.
MAL Which means at least four of the guys already in here are yours.
MAL All's one.
MAL I'll just keep Jayne with me.
ZOE Sir, are you sure you don't --
MAL Go.
MAL Go get yourselves a nice romantic meal.
WASH Those are my two favorite words!
WASH Honey...
WASH "Meal..."
MAL It's business.
MAL We're fine.
MAL They leave and the four remaining men sit.
MAL Fanty tosses a few coins to a saloon-girl, who does a little fan-dance...
MAL ANGLE: THE CORVUE CAMERA'S POV of the men is conveniently blocked by her little dance.
MAL Mal's foot nudges a duffel bag of money to Mingo's foot.
MINGO Quite a crew you've got.
MAL Yeah, they're a fine bunch of ruebens.
MINGO How you keep them on that crap boat is the subject of much musing tween me and Fanty.
FANTY We go on and on.
MAL So I'm noticing.
MAL Is there a problem I don't know of?
MAL You got 25% of a sweet take kissing your foot, how come we're not dispersing?
FANTY Our end is forty, precious.
JAYNE My muscular buttocks it's forty --
MINGO It is as of now.
MINGO Find anyone around going cheaper.
Find anyone around going near a sorry lot like you in the first instance.
ANGLE: RIVER has entered, is looking about.
Jayne sees her, nudges Mal, who looks and turns back to business.
We stay on her as she wanders around the perimeter of the bar, vaguely listening in on Mal's deal.
You're unlikable, Mal.
You got no respect for us above you, you got enemies in every quadrant, and your ship's older than the starting point of time.
You's charity cases to such as us.
MAL Well here's a foul thought.
MAL I conjured you two were incompetent; sent us out not knowing there were V0 Reavers about.
MAL Now I'm thinking you picked us out because you did.
MINGO That were a sign of faith, boy.
MINGO And it doesn't affect our forty per.
MINGO Danger is, after all, your business.
JAYNE Reavers ain't business, double dickless.
JAYNE This is all background noise to River, who has moved to the CV screen, on which is a commercial.
JAYNE It's animated, goofy, cartoon animals and anime-style Asian girls all transforming
to insane fantasy figures as they sing about:
We push in, the light from the CV on River's face, pushing to EXTREME CLOSE UP, all noise but the jingle fading out, finally that as well, just the hum in River's ears.
And she whispers:
RIVER Miranda.
RIVER She turns and looks back at the crowd.
RIVER What happens next happens very fast.
RIVER She strides silently to the first table -- two men drinking quietly -- and she slams her foot into one's face, then whips it back into the other's, knocking them both unconscious as -- people are turning, just registering that this girl -- kicks the table into a card player even as she sweeps a bottle off it behind her -- the bottle hits a man behind her square in the face, a man she never even looked at -- people are rising, fleeing or pushing forward --
MAL River...
JAYNE V0 Whuhuh?
JAYNE She's taking out a group of four, high kicks and perfect precision -- Two men come from either side, one whipping out a knife -- she does a perfect split, grabs his wrist above her head, using his momentum to stab the other one -- Mal fights to get back to the gunrack.
JAYNE The bouncer reaches her and she wrests his shockrod from him, uses it on him, on Fanty and Mingo -- the fan-dancer is bolting and River hurls the rod at her head, knocks her cold...
JAYNE She's everywhere.
JAYNE On tables, chairs, under your legs, using the room itself to take out every single person there.
JAYNE One man hides behind a wall -- impossibly, she swings her leg around the corner and nails his face.
JAYNE Jayne grabs her from behind --
Gorrammit, girl, it's me!
She grabs his crotch and squeezes -- his grip loosens and she spins, facing him, and flat-heels his nose with her palm, V0 twirling into a gut kick that doubles him over, dispatching of another while she cracks Jayne's head with a small table -- Somebody pulls a gun and she snaps his elbow, causing him to scream out even before he shoots himself in the gut -- Mal frantically wrests a gun from the vending locker as River knocks the other guy's gun in the air, kicks someone else and then catches it, whips it around just as Mal comes up with his, they are pointed right at each other --
SIMON Eta Kooram Nah Smech!
SIMON And River drops to the ground, fast asleep.
SIMON There is a beat.
SIMON Mal looks around the bar.
SIMON He and Simon, who has run up to the entrance, are the only ones standing.
SIMON He looks down at River.
SIMON She lies unconscious, helpless.
MAL I think maybe we ought to leave.
EXT. SPACE - NIGHT We see two sleek warships glide silently into frame, followed by a third, bigger ship.
EXT. SPACE - NIGHT This is the operative's vessel, and 10 it is everything Serenity is not: sleek, predatory, icy cool.
INT. THE OPERATIVE'S SHIP - BRIDGE - CONTINUING The operative is looking at the Maidenhead security feed -- and River is staring right at him.
Hello again.
Yes, it's me.
I'm glad you've finally asked for me.
An Ensign is revealed looking at a separate monitor:
ENSIGN We got a pos on a retinal -- man carrying her out is Malcolm Reynolds, captains a Firefly-class transport ship, "Serenity".
ENSIGN Bound by law five times, smuggling, tariff dodge...
ENSIGN not convicted.
ENSIGN Nothing here that would --
THE OPERATIVE The ship.
THE OPERATIVE The name of the ship.
Crossref.
Malcolm Reynolds.
Serenity.
He looks over at the Ensign with a small, strange smile on his lips -- as his glasses are covered by text.
ENSIGN Sir?
THE OPERATIVE Serenity Valley.
THE OPERATIVE Bloodiest battle of the entire war.
THE OPERATIVE The Independents held the valley for seven weeks, two of them after their high command had surrendered.
THE OPERATIVE 68% casualty rate.
ENSIGN Of course, Sir, I just didn't --
THE OPERATIVE There.
His glasses stop scrolling and Mal's military file opens, a picture of Mal in one lens.
If the feds ever bothered to crossref justice files with war records...
Yes.
Our Mr. Reynolds was a sergeant, 57th Overlanders.
Volunteer.
Fought at Serenity till the very last.
This man is an issue.
This man hates us.
ENSIGN First Mate Zoe Washburn, formerly Corporal Zoe Alleyne, also in the 57th.
ENSIGN Career army, looks like.
THE OPERATIVE She's followed him far...
THE OPERATIVE Give me the crew, registered passengers -- Our Captain is a passionate man, no room there for subtlety.
THE OPERATIVE He's bound to have some very obvious...
THE OPERATIVE CLOSE ON: THE LENS of his glasses.
THE OPERATIVE On it is a slowly moving picture of INARA.
THE OPERATIVE -40 (continuing) .weakness...
INT. STORAGE LOCKER - NIGHT River is still asleep, Mal finishing chaining her wrists.
INT. STORAGE LOCKER - NIGHT She lies on her side, breathing evenly.
Mal stares at her a moment, then:
INT. DINING ROOM - CONTINUING He exits to find the whole group waiting for him, sans Wash.
SIMON May I see her?
MAL She's still napping just now.
MAL And I believe you've got some storytelling to do.
We're out of atmo, plotted for Haven.
No one following as of yet.
KAYLEE Haven?
KAYLEE We're gonna see Shepherd Book?
We got to lay low.
And I could fair use some spiritual guidance right about now.
I am a lost lamb; what in hell happened back there?
WASH Start with the part where Jayne gets knocked out by a ninety pound girl.
WASH 'Cause I don't think that's ever getting old.
ZOE Do we know if anyone was killed?
MAL It's likely.
MAL I know she meant to Ad kill me 'fore the Doc put her to sleep, which how exactly does that work anyhow?
SIMON Safeword.
The people who helped me break River out -- they had intel that River and the other subjects were being embedded with behavioral conditioning.
They taught me a safeword, in case...
something happened.
KAYLEE Not sure I get it.
SIMON A phrase that's encoded in her brain, that makes her fall asleep.
SIMON If I speak the words, "Eta --
JAYNE Well don't say it!
JAYNE moo ZOE It only works on her, Jayne.
JAYNE Oh.
JAYNE Well, now I know that.
MAL "In case something happened."
SIMON What?
MAL You feel to elaborate on what that something might be?
MAL I mean they taught you that fancy safeword, they must've figured she was gonna, what -- start uncontrollably crocheting?
SIMON They never said what --
MAL And you never did ask.
MAL Mal grabs him and throws him against the wall, in his face.
Eight months.
Eight months you had her on my boat knowing full well she might go monkeyshit at the wrong word and you never said a thing --
SIMON I brought her out here so they couldn't get to her, I don't even know how they --
MAL My ship.
MAL My crewi You had a gorramn timebomb living with us!
INT. STORAGE LOCKER - CONTINUING River's eyes open.
MAL What if she went off in the middle woo of dinner, or in bunk with Kaylee, did that give you a moment's pause?
MAL Simon looks at Kaylee, the truth of Mal's words hitting him.
SIMON I thought she was getting better.
JAYNE And I thought they was gettin' off!
JAYNE Didn't we have a intricate plan how they was gonna be not here anymore?
KAYLEE We couldn't leave them now...
JAYNE No, now that she's a...
JAYNE killer woman we ought be bringin' 'em tea and dumplings!
JAYNE In earnest, Mal: why'd you bring her back on?
JAYNE Mal looks at Jayne, at all of them.
JAYNE Doesn't have an answer.
SIMON May I see her.
SIMON Mal steps aside.
SIMON Simon enters the locker.
JAYNE She goes woolly again, we're gonna have to put a bullet to her.
River mouths the next words right along with Mal:
MAL It's crossed my mind.
WASH Can I make a suggestion that doesn't involve violence, or is this the wrong crowd?
ZOE Honey...
WASH V0 Fanty and Mingo might be coming hard down on us, or the laws...
WASH or maybe nobody could be bunged about a little social brawl.
WASH We need to get our bearings.
WASH I think we need to talk to Mr. Universe.
EXT. SPACE - NIGHT The camera swoops in at a sparking ion cloud, then through the cloud at a barren, metallic satellite moon.
EXT. SPACE - NIGHT Then further in to reveal a sprawling -- and completely empty -- communications complex.
EXT. SPACE - NIGHT Giant satellite dishes everywhere.
INT. MR UNIVERSE'S HQ - CONTINUING Inside, we find an unkempt young man.
INT. MR UNIVERSE'S HQ - CONTINUING Also sleep-deprived, over-caffeinated and kinda sweet.
INT. MR UNIVERSE'S HQ - CONTINUING This is MR UNIVERSE.
INT. MR UNIVERSE'S HQ - CONTINUING He is alone but for his mannikin-like Love-bot, Lenore.
INT. MR UNIVERSE'S HQ - CONTINUING He's surrounded by screens, computers, feeds -- machinery that looks both ultra-modern and long neglected.
INT. MR UNIVERSE'S HQ - CONTINUING All the screens play different images -- it's a mediaverse.
A0 As he watches the security feed of River's fight his image becomes a vidscreen.
A0 He's addressing Wash, Mal and Zoe.
We intercut between the two spaces:
MR UNIVERSE Oh, this is good.
MR UNIVERSE This is...
.she's beating up all the burly men and I'm having a catharsis, it's happening right now, you guys always bring me the very best violence.
You think you're in a hot place?
WASH That's what we're looking to learn.
WASH Is there any follow up, a newswave...
MR UNIVERSE There is no "news", there's the truth of the signal, what I see, and there's the puppet theatre the V0 Parliament's jesters foist on the somnambulant public.
MR UNIVERSE Monkey taught to say the word "monkey" -- lead story on 32 planets.
MR UNIVERSE But the slum riots on Hera, not a --
MAL What about this?
MAL Did this make the...
MAL puppet theatre?
MR UNIVERSE No sir.
MR UNIVERSE And no lawforce flags, either -- I hadda go into the security feed direct...
MAL You can do that?
MR UNIVERSE Can't stop the signal, Mal.
MR UNIVERSE Everything goes somewhere and I go everywhere.
MR UNIVERSE Security feeds are a traipse to access -- and I wasn't the first one in, this has prints on it -- oh!
MR UNIVERSE Look at her go!
MR UNIVERSE A0 Everyone is getting bruises and contusions.
MR UNIVERSE Contoooosions.
ZOE So somebody else has been fed this.
ZOE That doesn't like me too well.
MR UNIVERSE Zoe, you sultry minx, stop falling in love with me.
MR UNIVERSE You're just gonna embarrass yourself.
MR UNIVERSE I have a commitment to my Lovebot, it was a very beautiful ceremony, Lenore wrote her own vows, I cried like a baby, a hungry, angry baby.
MR UNIVERSE And she falls asleep.
MR UNIVERSE Which, she would be sleepy.
MAL Can you go back?
MAL See if anybody spoke with her 'fore she acted up, -40 made any kind of contact with her...
MAL Mr Universe works the screen.
MAL The image rewinds and stops on River coming up to it, looking at it.
MAL She whispers the word, "Miranda", and starts to move away.
Miranda...?
Go back further.
MR UNIVERSE No..
MR UNIVERSE He pulls another screen close, starts working that one.
MR UNIVERSE Matching timecodes, he pulls up the commercial.
MAL Um...
MAL please?
MAL Mr Universe has a third screen showing the commercial as
well -- and it starts breaking down, bursts of code showing through.
As he does so:
MR UNIVERSE Friends and potential lovers, I
have good news and I have the other kind.
Good is you're very smart.
Someone is talking to her.
WASH The oaty bar?
MAL Subliminal.
MAL It's a subliminal message broadwaved to trigger her.
I been seeing this code pop up all over, last few weeks.
And I cannot crack it.
It's Alliance and it's high military, so here then is the bad.
Someone has gone to enormous trouble to find your little friend.
And found her they have.
Mal, Zoe and Wash look at each other.
Do you all know what it is you're carrying?
INT. STORAGE LOCKER - NIGHT River stares at us, impassive, as the camera pulls away from her to reveal Simon, who is cleaning blood off her face.
RIVER They're afraid of me.
SIMON I'm sorry...
RIVER They should be.
RIVER What I will show them...
RIVER Oh God...
RIVER She starts tearing up, breathing faster...
RIVER Simon runs his hands through her hair.
SIMON It's okay, it's okay...
RIVER Show me off like a dog, old men covered in blood, it never touched them but they're drowning in it...
RIVER so much loss...
RIVER I don't know what I'm saying.
RIVER I never know what I'm saying...
SIMON You said something.
SIMON When you were triggered, do you remember?
SIMON The Captain saw you say something on the feed...
RIVER Miranda.
SIMON Miranda.
RIVER Ask her.
RIVER She'll show you all.
SIMON Show us what?
SIMON Who is Miranda?
Am I...
talking to Miranda now?
Nwi? 1/2  She shoots him a look.
RIVER I'm not a multiple, dumbo.
SIMON No.
SIMON Right.
SIMON But I think somehow when they triggered you it brought this up, this memory --
RIVER It isn't mine.
RIVER The memory.
RIVER I didn't bring it and I shouldn't have to carry it, it isn't mine.
Don't make me sleep again.
SIMON I won't.
RIVER Put a bullet to me.
RIVER Bullet in the brain pan, squish.
SIMON Don't say that.
SIMON Not ever.
SIMON We'll get through this.
SIMON She reaches out and touches his face, affectionately.
RIVER Things are going to get much much worse.
SIMON Well, the Captain hasn't tossed us in the airlock, so I'd say we're --
RIVER He has to see.
RIVER More than anyone...
RIVER he has to see what he doesn't want to.
SIMON River.
SIMON What will Miranda show us.
SIMON She thinks.
RIVER Death.
SIMON Whose death?
SIMON And she starts laughing.
SIMON Quietly at first, then louder, then
almost uncontrollably, screaming in his face:
Black Silence.
It's pitch black here, til Serenity's lights throw a hard relief on the rocky wall.
She flies in after, slow and steady, revealing herself to be in a huge mineshaft.
BOOK Lord, I am walking your way.
BOOK ANGLE: THE RAMP lowers to reveal Shepherd BOOK, a working- class preacher and former crew member.
BOOK He smiles as they
come out to meet him:
Let me in, for my feet are sore, my clothes are ragged.
EXT. MINING CAMP - DAY We see the camp: a few shacks and a working mine, as our group come down to it, greeted by a few miners, including an eight year old boy that rushes to Kaylee...
EXT. MINING CAMP - DAY ANGLE ON: A CANNON mounted at the edge of town.
EXT. MINING CAMP - DAY The guy manning it sees them arrive, also goes to greet them.
We see the gang sitting and eating.
Comfortable, even laughing a bit.
Jayne presents Book with a couple of cigars.
Kaylee hoists the boy on her lap.
Look in my eyes, Lord, and my sins will play out on them as on a screen.
Read them all.
Mal approaches Book on the edge of a rise overlooking the town.
Mal has a bowl and chopsticks.
Book is finishing:
BOOK Forgive what you can, and send me on my path.
BOOK I will walk on, until you bid me rest.
MAL Hope that ain't for me, Shepherd.
BOOK It's prayer for the dead.
MAL Then I really hope it ain't for me.
BOOK It's for the men River might have killed in that bar.
MAL Weren't River that did it, you know that.
MAL Somebody decided her brain was just another piece of property to take, fenced it right Vd up.
BOOK You got a plan?
MAL Hiding ain't a plan?
BOOK It'll do you for a spell, and the folks here'll be glad of the extra coin...
MAL .but they'll be coming.
MAL Alliance is after this girl with a powerful will.
MAL I look to hear the tromp of their boots any moment.
BOOK You won't.
BOOK This isn't a palms-up military MW run, Mal.
BOOK No reports broadwaved, no warrants...
BOOK much as they want her, they want her hid.
BOOK That means Closed File.
BOOK Means an Operative, which is trouble you've not known.
MAL I coulda left her there.
INT. STORAGE LOCKER - NIGHT As he continues, we see an image of him watching over the sleeping girl, his mind, racing.
MAL I had an out -- hell, I had every reason in the 'verse to leave her lay and haul anchor.
BOOK Not your way, Mal.
V0 MAL I have a way?
Is that better than a plan?
BOOK You can play the thug all you want, but there's more to you than you're ever like to 'fess.
MAL You just think that 'cause my eyes is all sorrowful and pretty.
BOOK Only one thing is gonna walk you through this, Mal.
BOOK Belief.
MAL Sermons make me sleepy, Shepherd.
MAL I ain't looking for help from on high.
MAL That's a long wait for a train don't come.
BOOK When I talk about belief, why do you always assume I'm talking about God?
BOOK W (Mal has no response) They'll come at you sideways.
As he continues, we see:
EXT. COMPANION TRAINING HOUSE - DAY Inara stands waiting, her back to us, in front of the very vista we first saw her before.
EXT. COMPANION TRAINING HOUSE - DAY The operative comes slowly up the staircase, stands before her.
It's how they think: sideways.
It's how they move.
Sidle up and smile, hit you where you're weak.
BOOK Sorta man they're like to send believes hard.
BOOK Kills and never asks why.
MAL It's of interest to me how much you seem to know about that world.
BOOK I wasn't born a Shepherd, Mal.
MAL Have to tell me about that some time.
BOOK No I don't.
He walks away, offering this:
Sideways.
Mal watches him go, thinking.
EXT. CLASSROOM - DAY The Teacher from the very beginning is standing in front of River, whose desktop screen depicts a single, dark planet.
TEACHER River?
TEACHER Eight-year-old River is working away, not paying attention.
River, you look tired.
I think everybody's a little tired by now; why don't we all lie down.
River looks up, scared.
All the other children wordlessly get up from their seats and lie on the floor next to them.
A little peace and quiet will make everything better.
She starts to lie down herself, right on the grass.
RIVER No...
RIVER Vao TEACHER River.
RIVER Do as you're told.
RIVER It's going to be fine.
RIVER Lie down.
INT. STORAGE LOCKER - NIGHT River starts awake.
INT. MAL'S ROOM - CONTINUING Mal does too, shirtless on his bunk.
MAL Whuh huh nuhwhat?
Mal!
You up?
Got a wave.
I'm a bounce it down to you.
He pops up, turns to the screen as the white noise becomes:
MAL Inara.
MAL REVERSE ON: Inara on Mal's screen.
MAL We see her from about chest level up.
MAL She, presumably, sees the same.
Mal.
I uh, is this a bad time
MAL Good as any.
INARA Please tell me you're wearing pants.
MAL Naked as the day I come cryin'.
MAL How's your world?
INARA Cold.
INARA It's autumn here.
MAL Still at the Training House?
INARA Right where you left me.
MAL I remember it as nice enough.
MAL picturesque.
INARA It is that.
INARA What about you?
Still flying.
So what occasi the wave?
Not that to see you ain't...
well you look very
INT. BRIDGE - CONTINUING watching both Mal and Inara on two Zoe and Wash are secretly at their formal shyness.
INT. BRIDGE - CONTINUING different screens, smiling Jayne enters, wondering what's up...
INARA Oh.
INARA Thank you, I...
INARA I guess we have something of a problem here.
INARA With the locals, I thought maybe...
MAL You could use a gun hand?
INARA I'm hoping not.
INARA But if you were close at all, you -- the crew -- could take your ease here a while...
INARA and there'd be payment...
MAL Payment is never not a factor.
MAL I could sound out the crew...
MAL This pot like to boil over soon?
INARA Soon.
INARA Not right away.
MAL Well, it would be, I mean I would like to...
MAL Kaylee's been missing you something fierce --
INT. BRIDGE - CONTINUING There is a general groan among the audience, which now includes Kaylee as well...
KAYLEE Oh they're so pathetic!
INARA I miss her too.
INARA I even miss my shuttle, occasionally.
MAL Yeah, you left a...
MAL got some of your stuff in a trunk, never did get a chance to drop it off.
INARA Oh.
MAL I didn't look through the...
MAL stuff...
MAL just sundries I expect.
Inara smiles blandly, nods.
An awkward beat.
Well, it's kind of late where I'm at.
I'll send a wave as soon as I can.
INARA Thank you.
INARA She disappears.
INARA Mal thinks a moment.
Mal comes up in, buttoning his shirt.
WASH Inara.
WASH Nice to see her again.
ZOE So, trap?
MAL Trap.
ZOE We goin' in?
ZOE moo MAL It ain't but a few hours out...
WASH Yeah, but, remember the part where it's a trap?
MAL If that's the case, then Inara's already caught in it.
MAL She wouldn't set us up willing.
MAL Might be we got a shot at seeing who's turning these wheels.
MAL We go in.
KAYLEE How can you be sure Inara don't just wanna see you?
KAYLEE Sometimes people have feelings -- I'm referring here to people...
MAL Y'all were watching, I take it.
MAL Guilty glances.
KAYLEE Yes.
MAL 140 You see us fight?
KAYLEE No.
MAL Trap.
EXT. SERENITY - DAY The ship moves gracefully over the mountains.
WASH We're about seventy miles from the Training house.
WASH And nobody on radar...
WASH if the Alliance is about, they're laying low.
MAL They're about.
MAL Find us a home.
MAL I'll take the shuttle in closer.
MAL Zoe, ship is yours.
MAL 4dO He starts out, turns back to Zoe.
Remember: if anything happens to me, or you don't hear from me within the hour...
you take this ship and you come and rescue me.
ZOE What?
ZOE And risk my ship?
I mean it.
It's cold out there.
I don't wanna get left.
EXT. SERENITY - DAY She is nestled in a gorge, overhanging rocks all but burying her from view.
EXT. SERENITY - DAY The shuttle on the right lifts off from the side of the ship and glides off, keeping low.
EXT. COMPANION TRAINING HOUSE - DAY A line of young trainees files by in robes and red shawls pulled over their heads -- one trainee a good deal larger than the others.
She is kneeling in front of a statue of Buddha, lighting a few incense sticks.
The room is sparsely lush -- not as opulent as the shuttle where she entertained men, but still beautifully furnished and draped.
A lace curtain hangs in front of the light, casting its pattern in shadow over everything.
Including the rather large figure in a red shawl who kneels beside Inara.
MAL Dear Buddha, please send me a pony, and a plastic rocket, and --
Mal!
What are you doing here?
MAL You invited me.
INARA I never thought for a second you'd be stupid enough to come!
MAL Well that makes you kind of a tease, doesn't it?
INARA You knew my invitation wasn't on the level --
MAL Which led me to the conclusion that you must be in some trouble.
INARA I'm fine!
INARA I'm.
INARA giddy.
MAL For a woman schooled in telling men what they wanna hear, you ain't much of a liar.
INARA Mal, you cannot handle this man.
I have to say, I'm impressed that you would come for her yourself.
lwi? 1/2  And that you would make it this far in that outfit.
I can be very graceful when I need to.
THE OPERATIVE I've no doubt.
THE OPERATIVE Mal sheds his shawl and robe.
THE OPERATIVE Inara kneels at the alter, picks out another incense stick.
MAL What are you doing?
INARA I'm praying for you, Mal.
THE OPERATIVE That's very thoughtful.
THE OPERATIVE But I mean it when I say you're not in any danger.
MAL Speak your piece.
THE OPERATIVE I think you're beginning to understand how dangerous River Tam is.
MAL She is a mite unpredictable.
MAL Mood swings, of a sort.
THE OPERATIVE It's worse than you know.
MAL It usually is.
THE OPERATIVE That girl will rain destruction down on you and your ship.
THE OPERATIVE She's an albatross, Captain.
MAL Way I remember it, albatross was a ship's good luck...
MAL til some idiot killed it.
MAL Yes, I've read a poem.
MAL Try not to faint.
MAL The Operative moves further into the room.
MAL Whenever he moves, Mal counters.
THE OPERATIVE I've seen your war record.
THE OPERATIVE I know how you must feel about the Alliance.
MAL You really don't.
THE OPERATIVE Fair to say.
THE OPERATIVE But I have to hope you understand you can't beat us.
MAL I got no need to beat you.
MAL I just wanna go my way.
THE OPERATIVE And you can do that, once you let me take the girl back home.
THE OPERATIVE Give me the opportunity to help you.
MAL All I gotta do is let you take one more thing away from me.
MAL I've had a lot of things taken in my time.
MAL And it may just be that this is one too many.
THE OPERATIVE This psychotic, potentially murderous girl who can't have the slightest awareness of your protection.
THE OPERATIVE This is where you "draw the line".
MAL Well I'm a whimsical soul.
THE OPERATIVE There's a number of lives that hang in the balance here.
THE OPERATIVE Lives under your care.
THE OPERATIVE Are they as whimsical as yourself?
MAL I got no notion that I'm being heroical at all.
MAL Any more than I think you're really just a harmless bureaucrat come to help me out.
MAL You move like a killer.
The Operative is stopped by this.
Unhappily, he continues:
THE OPERATIVE I have a warship in deep orbit, Captain.
THE OPERATIVE We locked on to Serenity's pulse beacon the moment you hit atmo.
THE OPERATIVE I can speak a word and send a missile to that exact location inside of three minutes.
THE OPERATIVE Mal pulls a small device, clipped wires sticking out all around it, and tosses it to the Operative.
MAL You do that, best make peace with your dear and fluffy lord.
THE OPERATIVE Pulse beacon.
MAL Advice from an old tracker: you J wanna find someone, use your eyes.
THE OPERATIVE How long do you think you can really run from us?
MAL Oh, a jack-rabbit, me.
MAL 'Sides, I never credited the Alliance with an over-abundance of brains.
MAL And if you're the best they got...
THE OPERATIVE Captain Reynolds, I should tell you so that you don't waste your time: You can't make me angry.
INARA Oh please.
INARA Spend an hour with him.
INARA Mal smiles -- then glares at Inara, mouthing "Hey!"
THE OPERATIVE I need her, Captain.
THE OPERATIVE River is...
THE OPERATIVE my purpose and I will gather her to me.
THE OPERATIVE The brother as well.
THE OPERATIVE Whatever else happens is incidental.
THE OPERATIVE In the greater scheme.
MAL Why is it that the greater scheme always makes everything not that great?
THE OPERATIVE I want to resolve this like civilized men.
THE OPERATIVE I'm not threatening you.
THE OPERATIVE I'm unarmed.
MAL Great!
MAL He draws and shoots the Operative in the chest.
MAL The Operative goes down as Mal grabs Inara, moves for the-doorway.
MAL The Operative is on him in a second, choke-hold from behind.
THE OPERATIVE I am of course wearing full body armor.
THE OPERATIVE I'm not a moron.
THE OPERATIVE He tosses Mal hard against a wall, spinning and blocking a blow from Inara -- she is clearly trained in martial arts, but he flat-heels her to the ground within seconds.
THE OPERATIVE Mal is going for his gun again, turning, and the Operative kicks him in the face, sends him back, gun flying.
THE OPERATIVE Mal gets to his feet and they square off.
THE OPERATIVE Mal breathing hard, nose dripping blood.
THE OPERATIVE The Operative perfectly poised, waiting.
MAL No back up?
MAL We're making an awful ruckus...
THE OPERATIVE They'll come when they're needed.
MAL I'd start whistling.
THE OPERATIVE Captain, what do you think is going to happen here?
THE OPERATIVE They come at each other.
THE OPERATIVE The Operative is the much better trained -- he's fluid, his blows sparse and deadly.
Mal is more bluster and determination, and the operative's precision is wearing Mal down.
Mal punches wild -- the Operative counters with a spin-kick V0 to the head that sends Mal to the ground not far from Inara, breathing hard.
He tries to rise again, painfully, but Inara places her hand on his arm.
The Operative goes to his briefcase by the door, pulls out his sword.
His face has taken on that remote kind of fascination as he looks at it.
Nothing here is what it seems.
INARA I know.
THE OPERATIVE He's not the plucky hero.
THE OPERATIVE The Alliance isn't some evil empire.
THE OPERATIVE This isn't the grand arena.
INARA And that's not incense.
INARA He turns to look: the incense stick burns away -- rather like a fuse -- and FLASHES in an explosion of light and sound.
40 It's a flash-bomb: The Operative sails back as everything goes smoky white and the sound dies to a tiny buzz.
40 The Operative tries to get his bearings -- and four armored soldiers are in his face, asking him for orders...
40 Mal and Inara are gone.
40 He motions for the men to follow them.
THE OPERATIVE Just a flash bomb.
THE OPERATIVE Go!
THE OPERATIVE Go!
Inara leads Mal (who is reholstering his gun) down some steps and along a corridor.
The sound is still tinny and weird.
MAL .I had him...
INARA What?
MAL I think that I was winning!
Mal and Inara move quickly down the mountain.
They look to see that Mal's shuttle has four Alliance guards waiting by V0 it.
Mal ducks back out of sight, pulls a fancy-looking grenade out of his pocket.
Pops the top and hurls it over at the foursome.
CLOSE ON: THE GRENADE, as a series of bars of light go out one by one, counting down --
Grenade!
Everybody dives for cover.
The moment they do, Mal and Inara race into the shuttle, Mal sweeping up the grenade just as the last light goes out and nothing happens.
One soldier turns to look and Mal shoots him back down as the door shuts on him and Inara.
INT. SHUTTLE - CONTINUING Inara pushes into the pilot's seat.
INARA Hang on to something.
MAL 4 You sure you remember how it --
He nearly falls over as:
The shuttle shoots straight up, spinning and heading out.
INT. SHUTTLE - CONTINUING Inara stares straight ahead, relaxing her grip on the controls.
INT. SHUTTLE - CONTINUING Mal is gone.
INARA I told you to hang on.
I'm fine...
We are below Serenity as her bay doors are closing, six little objects floating out of her belly like roe.
These objects are roughly the size of pony-kegs, and clearly home-made, parts welded together almost haphazardly.
They all spark silently to life -- and shoot off in six different directions, as Serenity herself fires up her Firefly effect and burns away from us.
INT. COMPANION TRAINING HOUSE - DAY The Operative sips tea and rubs his temple.
THE OPERATIVE Forget the pulse beacon, there has to be another way to track the ship -- get a read on the nav sat.
THE OPERATIVE It's a registered transport, you must be able to locate --
ENSIGN Sir?
THE OPERATIVE Have you found a nav sat trajectory?
ENSIGN Sir...
ENSIGN we've found seven.
ENSIGN The Operative looks more unhappy than angry.
THE OPERATIVE Does he think this is a game?
EXT. CLASSROOM - DAY The teacher and students sleep as River -- as we saw her in the institute, older, with blood seeping from the needle- holes in her head -- makes her way through them.
EXT. CLASSROOM - DAY Slowly she walks to the floating lecture screen.
EXT. CLASSROOM - DAY On it is the solar system, glowing lines connecting all the stars and planets.
EXT. CLASSROOM - DAY She becomes wide-eyed, breathing hard as it pushes in to one system, one planet...
She looks over to one side of the tent, and we see:
Her POV is of the lab.
There stand some five older men in formal dress.
They stare at her, impassive.
We see flashes of corpses, lying in houses, in city streets -- and a Reaver's screaming face --
And River awakens.
A moment to get her bearings, then her eyes narrow with intent.
INARA (V.0.) We have every reason to be afraid.
JAYNE Why, 'cause this guy beat up Mal?
JAYNE That ain't so hard --
MAL He didn't beat me up --
INARA Because he's a believer.
As Inara continues, we see: Fanty and Mingo, tied to chairs.
Light spills onto their bruised faces as the Operative enters.
INARA (V.0.) He's intelligent, methodical and devout in his belief that killing River is the right thing to do.
INARA I honestly think the only reason we haven't been blown out of the air is that he needs to see her.
SIMON Needs to see her why?
INARA I'm uncertain.
INARA I would say to be sure of the kill, but...
INARA I just know he'll kill us all to get to her.
JAYNE So no hope of a reward, huh?
ZOE Did he mention a deal of any kind?
MAL Give the two of them up.
MAL Go my way.
JAYNE Which you was all ready to do not a day ago.
JAYNE What went sour?
MAL Cutting them loose ain't the same as handing them over.
JAYNE That so?
JAYNE 'Cause the corpse I'm about to become is having trouble telling the difference.
SIMON Did he say anything about a "Miranda"?
INARA What is that?
MAL Don't know who or what, but it's on River's mind.
MAL Conjure it might be the reason he's after her.
INARA You think maybe it poses some kind of threat to the Alliance?
WASH Do we care?
WASH Are we caring about that?
JAYNE You dumbass hogs, the only people she's a threat to is us on this boat!
INT. STORAGE LOCKER - CONTINUING River is near the ceiling, keeping herself up in a split again, feet against the walls.
INT. STORAGE LOCKER - CONTINUING There is a wire mesh cover to the light, and she has bent part of it out, is working it inside the lock of her shackles.
MAL Look, we get back to Haven in a 'r/ few hours time --
JAYNE Hiding under the Shepherd's skirts, that's a manful scheme --
MAL You wanna run this ship?
JAYNE Yes!
MAL Well you can't!
JAYNE Do a damn sight better job'n you.
JAYNE Getting us lashed over a couple of strays...
JAYNE No offense, Doc, I think it's noble as a grape the way you look to River, but she ain't my sister
JAYNE and she ain't your crew.
JAYNE Oh, and neither is she exactly helpless!
JAYNE So where's it writ we gotta lay down our lives for her, which is what you've steered us toward.
MAL I didn't start this.
JAYNE No, the Alliance starts the war -- and then you volunteer.
JAYNE Battle of Serenity, Mal: besides Zoe here, how many --
JAYNE -- I'm talkin' at you -- how many men in your platoon came out of there alive?
JAYNE Mal stares at him.
ZOE You wanna leave this room.
JAYNE You're damn right I do.
JAYNE He stalks upstairs.
JAYNE There's a quiet moment.
INARA This isn't the war, Mal.
INARA Mal turns, eyeing her.
MAL Are you telling me that because you think I don't know --
INARA You came to the training house looking for a fight.
MAL I came looking for you.
INARA I just want to know who I'm dealing with.
INARA I've seen too many versions of you to be sure.
MAL I start fighting a war I guarantee you'll see something new.
Mal walks out into the cargo bay, Inara following, over:
SIMON We'll get off.
SIMON River and I'll get off at Haven and find some --
KAYLEE Nobody's saying that.
WASH Nobody besides Jayne is saying that.
INT. CARGO BAY - CONTINUING Inara tries to catch up to --
INARA Mal.
I got no answers for you, Inara.
I got no rudder.
Wind blows 40 northerly, I go north.
That's who I am.
Maybe that ain't a man to lead but they have to follow so you wanna tear me down do it inside your own mind.
INARA I'm not trying to tear you down --
MAL But you fog things up.
MAL You always have -- you spin me about.
MAL I wish like hell you was elsewhere.
INARA I was.
INT. DINING ROOM - CONTINUING Jayne is looking at the storage locker door.
INT. DINING ROOM - CONTINUING A beat.
JAYNE He moves to the aft hall, shuts and locks the door.
JAYNE Goes 40 back to the locker and starts to unlock it, pulling his gun.
No trouble now, little crazy person...
we're going for a nice
shuttle ride -- He opens the door and she is on him in an instant, whip blow to the throat, the nose -- he fires wildly as she jumps on him, wraps her arms around his neck and topples him back --
The crew enters, drawn by the shots.
Mal is first -- can't open the door.
Looks in to see an unconscious Jayne...
MAL The other way!
MAL Find her and-do not engage!
MAL Everyone piles out the other way.
MAL Simon remains, to look in the window.
ANGLE: SIMON'S POV: There is Jayne, not moving -- and River pops up right in front of us.
He starts, then waits as she opens the door.
SIMON It's gonna be oka -- She elbows his throat viciously.
SIMON He drops to his knees, shocked and gasping, as she spin-kicks him to the ground.
SIMON He doesn't move.
SIMON She looks at him a moment, then takes off.
Mal is throwing his shoulder against the bolted door to the upstairs.
He gives up, looking around.
ZOE She's sealed off the bridge.
ZOE I do not like her there.
KAYLEE Cap'n!
KAYLEE She tosses him a bolt remover.
KAYLEE He starts pulling a bolt out
of a panel on the wall, tells Zoe:
MAL Check the shuttles.
MAL She coulda 40 snuck in.
MAL He pops the panel off and starts wriggling in among the wires.
A floor panel hinges open, Mal pulling himself up.
He moves quietly to the bridge, gun drawn.
He enters to find River frantically punching up coordinates on a big Cortex screen she's pulled out by the copilot's seat.
She whips Jayne's gun at his face, never looking at him.
A moment, and Mal lowers his own gun.
MAL The government's man, he says you're a danger to us.
MAL Not worth helping.
MAL Is he right?
MAL Are you anything but a weapon?
MAL I've staked my crew's life on the a - person-,-- - actual and whole, and if I'm wrong you'd best shoot me now.
MAL Or we could talk more...
RIVER Miranda.
RIVER WIt's a planet.
RIVER Matches the one from her dream.
INT. BRIDGE - LATER Everyone has gathered.
INT. BRIDGE - LATER Wash is piloting now, as they are in atmosphere.
INT. BRIDGE - LATER River is by Simon.
INT. BRIDGE - LATER She moves restlessly, upset.
KAYLEE How can it be there's a whole planet called Miranda and none of us knowed that?
MAL Because there isn't one.
MAL It's a blackrock.
MAL Uninhabitable.
MAL Terraforming didn't hold, or somesuch.
MAL Few settlers died.
RIVER I had to show them.
RIVER I didn't know if you were going to make me sleep.
SIMON You could've asked...
KAYLEE Wait a tick, yeah!
KAYLEE Some ten years back, before the war.
KAYLEE There was call for workers to settle on Miranda, my daddy talked about going.
KAYLEE I should've recalled...
WASH But there's nothing about it on the Cortex -- History, Astronomy...
WASH it's not in there.
MAL Half of writing history is hiding the truth.
MAL There's something on this rock the Alliance doesn't want known.
INARA That's right at the edge of the Burnham Quadrant, right?
INARA (cont'd) Furthest planet out.
It's not that far from here...
WASH Whoah, no, no --
ZOE That's a bad notion --
WASH Honey...
ZOE I got it, baby.
WASH Show them the bad...
WASH She hits some commands on the screen, pulls back to reveal a couple of other planets near Miranda.
ZOE This is us, see?
ZOE And here's Miranda.
ZOE All along here, this dead space in between, that's Reaver territory.
WASH They just float out there, sending out raiding parties --
ZOE Maybe a hundred ships.
ZOE And more every year.
ZOE You go through that you're signing up to be a banquet.
WASH I'm on board with the run and hide scenario -- and we are just about...
WASH He looks at his monitors, looks ahead...
EXT. MINING CAMP - DAY The ship swings around a mountain to come into view of the camp.
EXT. MINING CAMP - DAY I s
It is a world of fire.
Every building burns, some blown right apart.
Bodies litter the scene, not one of them moving.
There's a grounded Alliance ship not far from the cannon that shot it down.
INT. BRIDGE - CONTINUING We see Mal's face as the sight hits him like a gut-punch.
EXT. MINING CAMP - MOMENTS LATER The crew pours out even as the ramp lowers, going off in all directions, calling out to people...
EXT. MINING CAMP - MOMENTS LATER Kaylee heads for the burning church.
KAYLEE Shepherd?
KAYLEE Shepherd Book!
KAYLEE She stops, looking at the ground by the steeple.
KAYLEE There is the body on the ground, face down.
KAYLEE The child she played with at dinner.
KAYLEE Kaylee stares, at first uncomprehending.
KAYLEE ANGLE: MAL, moving in the other direction, approaches the
cannon, Jayne behind him.
He stops and sees: Book, lying by the cannon, torn up badly from the waist down.
Get the Doc.
He moves to the Shepherd, grabs his searching hand.
Shepherd...
Don't move.
BOOK Won't go far...
MAL Shouldn't've been you.
MAL I'm so sorry, it was...
MAL they should've hit us.
MAL They should've hit me.
BOOK That crossed my mind.
I shot him down --
MAL I seen.
BOOK I killed the ship...
BOOK that killed us.
BOOK Not...
BOOK very Christian of me.
MAL You did what's right.
BOOK Coming from you, that means...
BOOK almost nothing...
BOOK HNAAH!
BOOK Ah, I'm long gone...
MAL Doc'll bring you round.
MAL I look to be bored by many more sermons 'fore you slip -- don't move --
BOOK Can't...
BOOK order me around, boy.
BOOK I'm not one of your crew.
MAL Yes you are.
MAL Book coughs up blood, grabbing Mal.
MAL Urgent, almost angry.
BOOK You...
BOOK it's on you now...
BOOK all this death, this shit...
BOOK you have to find a course.
BOOK This can't mean nothing.
BOOK River...
BOOK you have to...
MAL Come on, keep it up --
Book grabs Mal's face, talks as though replying to something:
BOOK I don't care what you believe!
BOOK Just...
BOOK believe it.
BOOK Whatever you have to...
BOOK His breathing becomes laboured.
BOOK Hitched.
BOOK Stopped.
BOOK His hand slips away, his blood leaving a distinct print on Mal's face.
BOOK Jayne and Simon run up,Simon slowing down -- going to the e he's-dead.----Zne -a??a r.7-1, ;,,,r them as Jayne looks around him, Mal still fixed on Book.
JAYNE How come they ain't waiting?
JAYNE They know'd we was coming, how come they only sent one?
MO Zoe realizes the answer, turns to Wash.
ZOE Get on the Cortex.
ZOE Wave the Sanchez brothers, Li Shen -- anyone whose ever sheltered us after a heist.
ZOE Tell them to get out.
ZOE Get out now.
INT. BRIDGE - LATER Silence.
INT. BRIDGE - LATER Every Cortex screen is on, each looking at a different place.
INT. BRIDGE - LATER Every one shows fire, destruction or the snow of an interrupted signal.
INT. BRIDGE - LATER Mal stands alone amidst the screens, saying nothing.
INT. BRIDGE - LATER After a long moment, all of the screens hitch, the images replaced by identical images of the Operative.
INT. BRIDGE - LATER He looks solemn.
THE OPERATIVE V0 I'm sorry.
THE OPERATIVE But I cannot let you hide and I cannot let you run.
THE OPERATIVE Things become...
THE OPERATIVE extreme.
THE OPERATIVE And we wish for another way.
MAL Don't talk at me like a righteous man.
MAL You are a killer of children.
THE OPERATIVE When God wanted Pharaoh to release His people from bondage -- you know the story?
THE OPERATIVE He didn't ask.
THE OPERATIVE He sent his plagues down upon Egypt.
THE OPERATIVE That's me, Captain.
THE OPERATIVE The path to peace is paved with corpses.
THE OPERATIVE It's always been so.
MAL So me and mine got to lie down and
world?
THE OPERATIVE I'm not going to live there.
THE OPERATIVE How could you think -- there's no place for me there, any more than 40 there is for you.
THE OPERATIVE Malcolm, I'm a monster.
THE OPERATIVE What I do is evil, I've no illusions about it.
THE OPERATIVE But it must be done.
MAL Why?
MAL Do you know why?
THE OPERATIVE It's not my place to ask.
MAL You will never see River Tam.
MAL I'm telling you this.
THE OPERATIVE Maybe not.
THE OPERATIVE But you'll keep her close now, and when I blow Serenity out of the air, this will be ended.
THE OPERATIVE You're so terribly out of your depth, Captain.
THE OPERATIVE Your old boat can't take the pressure.
MAL She ain't buckled yet.
MAL And the 40 only reason you're talking such a lot is you can't get a fix on us.
THE OPERATIVE Yes, your scrambler's code is too old for our seekers.
THE OPERATIVE You love that, yes?
THE OPERATIVE The small triumph over modernity.
THE OPERATIVE You really are the noble savage.
MAL Nobody -- ever -- calls me noble.
THE OPERATIVE But that's what's going to kill you, Malcolm.
THE OPERATIVE Nobility.
THE OPERATIVE It confuses your text, which is self-interest.
THE OPERATIVE And sin.
MAL Only- many-I-know-who still --bel i-eved- in sin just died by your hand.
THE OPERATIVE What do you believe in?
MAL Not a solitary thing.
THE OPERATIVE If that were true, you'd be nothing more than a Reaver.
THE OPERATIVE Something changes in Mal's expression.
But then, maybe you're not that far from -- Mal flicks a switch and every screen goes dark.
EXT. MINING CAMP - MOMENTS LATER Mal comes striding out, where the crew have been gathering bodies, laying blankets over them.
MAL Get these bodies together.
ZOE We got time for gravedigging?
MAL Zoe, you and Simon are gonna rope V0 'em together.
MAL Five or six of 'em.
MAL I want them laid out on the nose of our ship.
SIMON Are you insane?
KAYLEE What do you mean, the bodies...
MAL Kaylee, I need you to muck the reactor core, just enough to leave a trail and make it read like we're flying without containment, not enough to fry us.
KAYLEE These people are our friends --
MAL Kaylee, you got a day's work to do and two hours to do it.
MAL (cont'd)
Jayne, you and Wash hoist up that cannon mount.
Goes right on top.
Piece or two of the other ship, stick it on.
Any place you can tear hull without inner breach, do that too.
And we're gonna need paint.
We're gonna need red paint.
ZOE Sir.
ZOE Do you really mean to turn our home into an abomination so we can make a suicidal attempt at passing through Reaver space?
MAL I mean to live.
MAL I mean for us to live.
MAL The Alliance won't have that, so we go where they won't follow.
JAYNE V0 God's balls, there's no way we're going out there!
And everybody (save River) is talking at once:
SIMON What's the point of living if you sink to the level of a savage --
INARA Please, we should talk this over --
JAYNE I ain't takin' orders from a man has lost his brainstem -- , -Mal pule-s-his- in his face, steps back, hand on his.
MAL This is how it works.
MAL Anybody doesn't wanna fly with me anymore, this is your port of harbour.
MAL There's a lot of fine ways to die.
MAL I'm not waiting for the Alliance to choose mine.
MAL He walks through the group, toward the smashed cockpit of the Alliance fighter.
MAL Struggling to get out is the badly wounded pilot.
MAL He sees Mal coming and raises his hands in surrender.
MAL Mal shoots him in the head, turns back.
I mean to confound those killers, and take my shot at getting to Miranda, maybe finding out what all I'm dying for.
That's my theme now.
So I hear a word out of any of you that ain't helping me out or taking your leave I will fucking shoot you.
He grabs a body -- drops it at Zoe's feet as he heads toward the ship.
Get to work.
EXT. SPACE - NIGHT CLOSE ON THE BODIES as they BURN, flames passing over them and suddenly flickering out as dark falls.
EXT. SPACE - NIGHT They are patches of leathered flesh stretched over bone -- monsters, screaming soundlessly in the nothing of space.
EXT. SPACE - NIGHT We arm past them to the windows of the bridge, looking in at Mal, watching, with Zoe behind and Wash at the helm.
EXT. SPACE - NIGHT And we pull back out to see the whole of Serenity for the first time: It is hardly recognizable.
EXT. SPACE - NIGHT Charred corpses on the nose, Cannon atop with a space-suited corpse draped within, long scars, welded-on parts and war paint...
EXT. SPACE - NIGHT the trail of green light burns out with sporadic bursts of vapor.
EXT. SPACE - NIGHT It looks, for all the world, like a Reaver ship.
INT. CARGO BAY - CONTINUING Mal comes down the stairs to the catwalk.
INT. CARGO BAY - CONTINUING He hesitates, then steps into the shuttle.
INT. CARGO BAY - CONTINUING i? 1/2 Mo
INT. SHUTTLE - CONTINUING It's dark in here.
INT. SHUTTLE - CONTINUING Mal stands with his back to the door, no light on his face, shaking.
INT. SHUTTLE - CONTINUING Not crying, but overcome.
INARA Mal.
INARA He looks up: she's in the corner looking through that trunk of hers, hands on a long oilcloth wrapped around something.
MAL Didn't see you.
I figured that.
MAL Anything of use in there?
INARA Maybe.
INARA She puts it down and crosses to the bed.
INARA He sits by her.
MAL You don't have to stay in the shuttle, you know.
MAL There's empty rooms, if you wanna sleep awhile.
INARA You think anyone's set to sleep?
INARA Simon's portioning out overdoses of morphine, just in case.
MAL Cheerful fellow.
MAL Did you really miss this place?
INARA Sometimes...
INARA Not so much right now.
A beat.
He doesn't look at her when he asks:
MAL Why did you leave?
MAL Site does lo9}E-at-- t -m-
INARA Why didn't you ask me not to?
Dissatisfied, Mal rises.
MAL I, uh, I'd better go check on the VW crew.
MAL See how the inevitable mutiny is coming along.
MAL They both want to say more.
MAL They don't.
MAL He goes.
EXT. SPACE - NIGHT Serenity flies, silent.
The group make their way toward the bridge.
Those close enough to get a view out the window are looking freaked -- those already on the bridge are stock still.
Pressed up against the glass of the window is River, just staring.
EXT. SPACE - CONTINUING Reverse to see: an armada.
EXT. SPACE - CONTINUING The black sky is filled with what must be ninety ships in a vague cluster, as Serenity breaks frame headed toward them.
EXT. SPACE - CONTINUING Most of them hang still in the air.
EXT. SPACE - CONTINUING Some move swimmingly about.
EXT. SPACE - CONTINUING Some turn in gentle drifts, as though looking around.
EXT. SPACE - CONTINUING Vd INT.
EXT. SPACE - CONTINUING BRIDGE - CONTINUING They all wait, tensed up, as they approach the armada...
EXT. SPACE - CONTINUING And arrive, moving slowly through the ranks of ships.
EXT. SPACE - CONTINUING Serenity passes a large, bizarrely shaped ship.
EXT. SPACE - CONTINUING It turns, as though watching her.
EXT. SPACE - CONTINUING But lets her pass.
EXT. SPACE - CONTINUING Another minute, and Serenity is through the Armada, headed for the small planet just beyond.
The Operative stares blankly at the Ensign.
THE OPERATIVE Define "disappeared".
THE OPERATIVE The Ensign just looks uncomfortable.
Kaylee, Simon and River have left the bridge.
The clouds fog the windows, so nothing below is visible.
ZOE Every reading I'm getting says normal.
ZOE Oceans, land masses...
ZOE no tectonic instability or radiation.
WASH Yeah, but no power, either.
MAL Nothing at all?
WASH Wait.
WASH Something.
WASH Might be a beacon, but it's awful weak.
MAL Find it.
EXT. SERENITY - DAY As she touches down, filling the frame.
EXT. SERENITY - DAY After a moment Mal, Zoe and Jayne emerge from the airlock in full suits, armed.
EXT. SERENITY - DAY Zoe reads a handheld scanner...
V0 MAL Gravity's Earthnorm.
ZOE 02 levels check, pressure...
ZOE if there's anything wrong the scanner isn't reading it.
ZOE Mal pulls off his helmet.
ZOE Breathes, looking around him.
MAL Well something sure as hell ain't right...
MAL WIDER ANGLE: They're in a CITY.
MAL Gleaming metal, spread out for miles in every direction.
MAL Portions decimated by fires long since cold, others overgrown with weeds, but mostly intact.
MAL But silent, as if trapped in amber.
JAYNE --ai-n-lt the settlement-
ZOE We flew over at least a dozen cities just as big.
ZOE Why didn't we hear about this?
MAL Beacon's up ahead.
Out of their suits now, Mal, Zoe and Jayne take point as the entire crew walks along the street, looking about them.
ZOE Ho.
She moves rapidly, gun out, to:
Face-down on the ground, clothes tattered.
She examines it as Mal approaches, waving the others back.
No entry wound, fractures...
MAL Poison?
Got another one!
ANGLE: JAYNE is by a downed hovercraft.
Inside are three skeletons: two grown-ups and a small child.
Clothes in better condition, and again no sign of violence.
JAYNE They's all just sittin'.
JAYNE Didn't crash...
JAYNE ANGLE: RIVER is quietly becoming more and more upset.
JAYNE CLOSE ON: KAYLEE walks in front of an office building,
staying away from the cars as she hears:
JAYNE Couple more here...
JAYNE 0 0 orpse _of_aman is pressed up against the glass wall right behind her.
JAYNE Mouth open, skin dead blue, terribly skinny...
JAYNE a thing to haunt.
SIMON Kaylee...
SIMON Come this way.
SIMON Come here.
SIMON Don't -- But she looks --
KAYLEE GAAAAaaoh God -- -- and steps back, horrified, as the others approach.
KAYLEE It's an office.
KAYLEE About half the employees are there, in chairs or on the ground, all in the same state as the first fellow.
KAYLEE We see ANGLES of the corpses as the gang evaluates...
JAYNE How come they're preserved?
MAL Place must've gone hermetic when the power blew.
MAL Sealed 'em.
KAYLEE What're they doing?
KAYLEE What's everybody doing?
SIMON There's no discoloration, nobody's doubled over or showing signs of pain...
MAL There's gasses that kill painless, right?
INARA But they didn't fall down.
INARA None of them.
INARA They just lay down.
SIMON More than anything, it looks like starvation.
MAL Anybody want to bet there's plenty of food around?
INARA They just lay down...
INARA They notice River now, in the middle of the street, keening.
INARA She drops to her knees, clutching her head.
As she speaks we see, as she sees, FLASHES: bodies.
In homes, in piles: an entire world, gently dead.
RIVER , make them stop, they're everywhere, every city every house every room, they're all inside me, I can hear them all and they're saying nothing!
RIVER GET UP!
RIVER PLEASE, GET THEM UP!
RIVER , please God make me a stone...
She's starting to damage my calm.
ZOE Jayne --
JAYNE She's right!
JAYNE Everybody's dead!
JAYNE This whole world is dead for no reason!
WASH Let's get to the beacon.
It's small -- landing is easier in cities with flying vehicles.
At the end of a short runway, tipped and damaged, is an Alliance Research Vessel.
The gang makes its way towards it.
It's a mess, doors pried open, signs of violence but no bodies.
The gang walks through it, looking around.
River pulls away from Simon, suddenly determined.
She approaches a console, and a small cylindrical object.
She turns it slightly -- A hologram squawks to life amidst them all.
First we see images that resemble the flashes from River's mind: Corpses, everywhere.
We hear and then see DOCTOR CARON standing exactly where she was when she recorded this message...
(As she speaks, we see angles of everyone watching, taking it in..
River silently mouths every word.)
,two
CARON -- just a few of the images we've recorded, and you can see it isn't..
CARON it isn't what we thought.
CARON There's been no war here, and no terraforming event.
CARON The environment is stable.
CARON It's the Pax, the G-32 Paxilon Hydroclorate that we added to the air processors.
CARON It's...
CARON .well it works...
CARON it was supposed to calm the population, weed out aggression.
CARON Make a peaceful...
CARON it worked.
CARON The people here stopped fighting.
CARON And then they stopped everything else.
CARON They stopped going to work, stopped breeding...
CARON talking...
CARON eating...
CARON There's thirty million people here and they all just let themselves die.
CARON They didn't even kill themselves.
CARON They just...
CARON most starved.
CARON When they stopped working the power grids, there were overloads, fires -- people burned to death sitting in their V0 chairs.
CARON Just sitting.
CARON There is a loud bang somewhere behind her -- she starts, gathers herself.
I have to be quick.
There was no one working the receptors when we landed, so we hit pretty hard.
We can't leave.
We can't take any of the local transports because...
The bang again.
There are people...
they're not people...
about a tenth of a percent of the population had the opposite reaction to the Pax.
Their aggressor response increased...
beyond madness.
They've become...
CARON (cont'd) they've killed most of us...
not just killed, they've done...
things.
Reavers...
they made them...
CARON I won't live to report this, and we haven't got power to...
CARON people have to know...
CARON We meant it for the best...
CARON to make people safer...
CARON to...
CARON God!
CARON She whirls, grabs a gun and fires -- then aims the gun at her own head - but a Reaver is on her, knocks the gun away and bites her face -- She screams continuously as the Reaver tops her, biting at her and tearing at her clothes, at her skin.
Turn it off.
Wash does, nobody saying anything.
10 Mal walks outside.
He takes a few unsteady steps away from the vessel.
Inara appears behind him, follows -- he holds a hand out behind him, seemingly to make her stop, but then he grabs her shoulder, holds her for support.
She puts her hand over his.
MAL I seen so much death...
MAL I been on fields carpeted with bodies, friends and enemies -- I seen men and women blown to messes no further from me than you.
INARA Mal...
MAL But every single one of those people died on their feet.
MAL Fighting.
MAL (cont'd) Or, hell, running away -- doing summat to get through.
This is...
INARA Mal, I need your help with this.
INARA I need you to help me, because I can't -- He looks at her, folds her into his arms.
INARA Brings her face to his, not kissing but touching, pressing into each other with the urgency of pulsing, necessary life.
River falls to her knees, vomiting.
Simon goes to her, puts his hand on her back, lets her ride it out.
SIMON River...
RIVER I'm all right.
RIVER She looks at him, wet eyes full of clarity.
I'm all right.
V0 Wash pulls the recording cylinder out of the console.
The cylinder is on the table.
Mal stands at the head, looking at his crew.
MAL This report is maybe twelve years old.
MAL Parliament buried it, and it stayed buried til River dug it up.
MAL This is what they feared she knew.
MAL And they were right to fear, 'cause there's a universe of folk that are gonna know it too.
MAL They're gonna see it.
MAL Somebody has to speak for these people.
MAL He pauses.
MAL Everyone waits.
You all got on this boat for different reasons, but you all V0 come to the same place.
So now I'm asking more of you than I have before.
Maybe all.
'Cause as sure as I know anything I know this: They will try again.
Maybe on another world, maybe on this very ground, swept clean.
A year from now, ten, they'll swing back to the belief that they can make people...
better.
And I do not hold to that.
So no more running.
I aim to misbehave.
There is a beat as he eyes them all.
JAYNE My grandma always told me: if you can't do something smart, do something right.
JAYNE By way of emphasis he loudly cocks his big-ass rifle.
JAYNE Mal takes in the fact that Jayne has spoken for them all.
MAL That the same grandma told you 4 there was an evil dwarf spirit living in your well?
She was a fun grandma.
SIMON Do we have a plan?
MAL Mr Universe.
MAL We haven't the equipment to broadwave this code, but he can put it on every screen for thirty worlds.
MAL He's pretty damn close, too.
RIVER Based on our orbital trajectories, he reached optimum proximity just before our sunset.
RIVER If we make a direct run within the hour we're only 67,332 miles out.
RIVER At full burn we'd reach him inside of three- hours .
She doesn't notice the reactions to her sudden clarity -- she's still somewhat in her own world.
WASH Still got the Reavers, and probably the Alliance between us and him.
ZOE It's a fair bet the Alliance knows about Mr Universe.
ZOE They're gonna see this coming.
MAL No.
MAL He takes a long moment, his jaw tightening imperceptibly.
They're not gonna see this coming.
CLOSE ON: One of Serenity's jet engines, as it FIRES up.
Serenity is taking off, leaving the dead place behind.
INT. MR UNIVERSE'S HQ - CONTINUING He's talking with Mal and Wash again, very animated.
MR UNIVERSE It's no problem!
MR UNIVERSE Bring it on bring it on bring it on!
MR UNIVERSE From here to the eyes and ears of the 'verse, that's my motto, or it might be if I start having a motto.
MAL (ON SCREEN) We won't be long.
MR UNIVERSE You're gonna get caught in the ion cloud, it'll play merry hob with your radar, but pretty pretty lights and a few miles after you'll be right in my orbit.
MAL (ON SCREEN) You'll let us know if anyone else comes at you?
DROP BACK WIDE to see: The Operative and ten soldiers are in the room, visible to Mr Universe but not to the screen.
MR UNIVERSE You'll be the first.
MR UNIVERSE CLOSE ON: the Operative's sword, as he unsheathes it.
EXT. SPACE - NIGHT We are amongst the Reaver armada.
EXT. SPACE - NIGHT Serenity slices quietly through the ships, as we come around and see Miranda receding in the distance.
EXT. SPACE - NIGHT Serenity drifts through the armada -- and suddenly another ship fires up, running next to her...
EXT. SPACE - NIGHT The two ships pace each other, another vessel coming about as though staring at Serenity, who comes closer and closer to frame, till we see the suited corpse draped on the cannon.
EXT. SPACE - NIGHT It suddenly moves: it's Mal.
EXT. SPACE - NIGHT He swings the cannon round and fires at the ship pacing them.
EXT. SPACE - NIGHT It BLOWS, fragmenting into burning bits that spiral into other ships, causing two smaller ones to blow as well.
EXT. SPACE - NIGHT Mal swings around and fires at another ship.
In close orbit waits the Alliance force, at least fifty strong, and clearly with high tech firepower.
We move in on the Operative's ship, in the middle of the cluster.
INT. THE OPERATIVE'S SHIP - BRIDGE - CONTINUING As the Operative waits with the others.
HELMSMAN I'm reading activity in the cloud.
THE OPERATIVE Lock and fire on my command.
THE OPERATIVE You should have let me see her.
THE OPERATIVE We should have done this as men.
THE OPERATIVE Not with fire...
HELMSMAN Sir!
HELMSMAN ,Wd
EXT. SPACE - CONTINUING It's the Operative's POV: the swirling Ion cloud as Serenity breaks through and heads at us, fully Reavered out.
He looks confused, then smiles at the ruse.
Hits the com:
THE OPERATIVE Vessel in range, lock on...
Bastard's not even changing course...
EXT. SPACE - CONTINUING As Serenity get a bit closer, FIFTY REAVER SHIPS suddenly burst from the cloud, also heading straight at us.
INT. THE OPERATIVE'S SHIP - BRIDGE - CONTINUING The Operative -- and everyone around him - goes big-eyed.
THE OPERATIVE That's not good...
Sir?
THE OPERATIVE Target the Reavers!
THE OPERATIVE Target the Reavers!
THE OPERATIVE Target everyone!
THE OPERATIVE Somebody FIRE!
EXT. SPACE - CONTINUING Serenity suddenly lists hard to port -- until she's almost upside down -- the Alliance ships FIRE, missing Serenity but tagging a few Reaver ships, none of whom have slowed down --
INT. BRIDGE - CONTINUING Mal is back on the bridge as we look out at the upside down Alliance fleet, missiles just passing us --
MAL We're too close for them to arm --
ZOE This is gonna be very tight --
Hey look, we're upside down.
V0 Zoe and Mal shoot a look at Jayne.
WASH I am a leaf on the wind, watch how I soar.
EXT. SPACE - CONTINUING Serenity slips right under the Operative's ship and ducks and weaves between dozens more.
EXT. SPACE - CONTINUING The Reaver force hits the Alliance head on -- and several ships do just that, smashing into bigger ships kamikaze-style, everything exploding -- The fleet mobilizes, blasting Reaver ships, circling around, and an air war begins, a frenzied, balletic ecstasy of destruction that the camera hurtles through as ships and parts of ships fly at and past it.
She nearly makes it all the way through the alliance fleet before a barrelling chunk of debris -- which is twice their size -- forces them to come hard about and remain in the fray.
Mal looks out at the chaos...
MAL Chickens come home to roost...
MAL They are suddenly JOLTED by a glancing blow from another ship -- Wash struggles to control her --
The hell --
It's okay!
I am a leaf on the wind!
MAL What does that mean?
EXT. SPACE - CONTINUING Serenity makes her way past the carnage and heads down toward the tiny satellite moon.
As the vessel shakes, clearly breached, The Operative moves to a door marked: DART.
He puts his thumb to a panel and the door slides up to reveal a standing, almost formfitting one- man cockpit.
The Dart disengages and bullets down towards the surface.
As it moves from the Operative's ship, we see that a Reaver vessel has smashed into the main viewshield, and the ship is spinning, explosions popping silently all over it.
EXT. SERENITY - CONTINUING She continues down, the metallic expanse of Mr Universe's little moon complex sprawling below them.
EXT. SERENITY - CONTINUING A moment after Serenity blows through frame, so does a Reaver ship.
EXT. SERENITY - CONTINUING It fires an electronic pulse at Serenity and sparks fly.
We're fried!
I got no control!
Sparks -- and arcs of electricity -- are everywhere here.
Kaylee jumps back as she is electrocuted -- Simon runs in and pulls her out, slams the door shut on the erupting fires.
MAL Where's the back up?
MAL Where's the back up?
MAL He and Wash are frantically flipping buttons -- the ship whirs to a semblance of life - -
ZOE Back up reads at 20%..
ZOE (to Wash)- Can you get us down?
WASH I'm gonna have to glide her in!
ZOE Will that work?
WASH 140 Long as that landing strip is made of fluffy pillows...
MAL Everybody to the upper decks!
MAL Strap yourselves to something!
EXT. LANDING STRIP - CONTINUING We can see it, a long strip, which halfway along becomes a kind of hanger.
EXT. LANDING STRIP - CONTINUING Serenity arcs at it uncomfortably fast.
INT. BRIDGE - CONTINUING Wash is fighting the stick with extreme concentration as Zoe pulls out a seat as well, straps in.
Jayne, Simon and Inara pull harnesses not unlike "Batman the Ride" seats from the ceiling, help the others in.
-40 And Serenity HITS the ground -- the landing gear folds and snaps under the weight -- the ship keeps going, now inside the hanger, heading towards the entrance to the facility, slowing, fishtailing and coming about a full one eighty -- it goes beyond the strip and crashes down into the pedestrian area, so that the nose is sticking back out at the runway but the body of the ship is hidden from it.
INT. BRIDGE - CONTINUING There is a moment of quiet.
WASH I am a leaf on the wind.
WASH Watch -- A massive harpoon CRASHES through the windshield and impales him to his chair.
WASH It's as thick around as a telephone pole.
WASH Wash has time to open his mouth in surprise before he is dead.
She moves to him --
Wash baby baby no, come on, you gotta move you gotta move baby VW please -- Mal rips her away and to the floor as another projectile slams through the window into the wall above them.
EXT. LANDING STRIP - CONTINUING We see the ship that has fired the harpoons as Reavers start out of it.
EXT. LANDING STRIP - CONTINUING A second Reaver vessel enters frame from above, about to land next to it.
The cargo bay door opens -- just the little door housed inside the ramp -- and Jayne comes out with his biggest gun.
He looks up, toward the edge of the runway, but no Reavers have arrived yet.
JAYNE Go!
JAYNE The entire crew piles out, all heavily bedecked with weapons.
MAL Head inside!
A small double-sized doorway leads to the "Black Room", which is the entrance proper to the facility.
Mal hits a button and huge, thick, blast doors open from the sides AND the top and bottom, creating the effect of a square hole getting bigger.
The hall itself is smaller than the black room, but still has the arrows on the ceiling, that point to an elevator some fifty feet away.
MAL Come on.
MAL Jayne, rearguard.
MAL Zoe slows, looking around her.
ZOE Sir.
ZOE This is a good hold point_
MAL We all stay together --
ZOE No.
ZOE They have to come through here; they'll bottleneck and we can thin 'em out.
ZOE We get pushed ,oO back there's the blast doors.
KAYLEE I can rig 'em so they won't re- open once they close.
MAL Then shut 'em and hide til --
ZOE We need to draw them til it's done.
ZOE This is the place.
ZOE We'll buy you the time.
JAYNE Move those crates back there for cover -- and make sure they ain't filled with anything goes boom.
KAYLEE Wait, Wash -- where's Wash?
KAYLEE Nobody (but River) realized he wasn't there.
KAYLEE Zoe is dead calm.
KAYLEE ,No ZOE He ain't comin'.
KAYLEE Everybody takes that in, Kaylee's eyes welling up.
JAYNE Move the gorram crates!
JAYNE Come on!
JAYNE We hear savage SCREAMS from the hanger -- they're approaching.
JAYNE Mal moves to the door, Jayne beside him.
Reavers rush toward them.
He turns to Jayne.
MAL Tell me you brought 'em this time...
MAL Jayne smiles grimly, tosses Mal a grenade as he pops his own and fastballs it at the Reavers.
It explodes in their midst, smoke and man-parts flying about.
Mal rolls his a shorter distance, then slams the door shut.
40 Explodes, raining a bunch of equipment -- and part of a catwalk -- right in front of the door.
40 In the black room, the door nearly buckles from the explosion.
40 Everyone takes positions behind the crates.
40 Zoe stands calmly, her back to the door, loading her sawed-off.
MAL Zoe...
MAL are you here?
MAL She looks up at him.
ZOE Do the job, sir.
MAL You hold.
MAL Hold till I'm back.
MAL He takes off -- passes Inara, the two of them holding a look for as long as they can.
MAL Then he's in the elevator and gone.
MAL Jayne moves over to Zoe.
JAYNE Captain's right.
JAYNE Can't be thinking on revenge if we're gonna get through this.
ZOE You really think any of us are gonna get through this?
ZOE He looks back at their army: A companion, a doctor, a mechanic and a more-than-usually out of it River.
ZOE A beat,
and he looks back at Zoe with forlorn hope:
JAYNE I might...
The elevator stops and Mal makes his way to the island of screens and machines in the center of the space.
The first thing he takes in is that every broadwave port has been destroyed.
The second:
ANGLE: MR UNIVERSE is lying dead, eyes open, half draped on his equally still lovebot.
A trail of blood shows he crawled from his chair.
V0 Mal comes close.
V0 Nothing.
V0 He starts to move away again and the lovebot turns her head, her eyes focusing with an audible whir.
V0 She speaks with surprisingly realistic expressiveness, and a warped, computery version of Mr Universe's voice.
LOVEBOT Mal.
LOVEBOT Mal stops.
Guy killed me, Mal.
He killed me with a sword.
How weird is that?
I got...
a short span here...
they destroyed my equipment but I have a back-up unit...
bottom of the complex, right over the generator.
Hard to get to.
I know they missed it.
They can't stop the signal, Mal.
They can never stop the signal.
Okay this is painful.
On many levels.
I'm not --
A0 She turns back, powering down.
A0 Recording over.
A0 A beat, and Mal takes off.
INT. BLACK ROOM - CONTINUING Inara is on her knees, unwrapping the oilcloth we saw in her shuttle.
INT. BLACK ROOM - CONTINUING River is in the corner, clutching her head.
RIVER I can't shut them up...
SIMON It's okay...
RIVER They're all made up of rage.
RIVER I can't...
RIVER A BANG as a body slams against the door.
SIMON Just stay low.
SIMON I'm right here.
Jayne moves past them to Zoe, takes position by her.
JAYNE She picked a sweet bung of a time to go helpless on us.
ZOE Jayne and I take the first wave.
ZOE Nobody shoots less they get past our fire.
ZOE Simon moves to Kaylee, who is shaky as hell.
ZOE The bangs on the door continue.
KAYLEE Oh, I didn't plan on going out like this.
KAYLEE I think we did right, but...
SIMON I never planned...
SIMON anything.
SIMON I just wanted to keep River safe.
SIMON Spent so much time on Serenity trying to find us a home I never realized I already had.
SIMON She looks at him with soft surprise.
My one true regret in all this is never being with you.
KAYLEE With me?
KAYLEE You mean to say, as, sex?
I mean to say.
Kaylee snaps her cartridge home with way more precision than we might expect from her, takes steady aim at the door.
KAYLEE Hell with this.
KAYLEE I'm gonna live.
KAYLEE Simon looks at her a moment, then turns his attention to the door.
Inara come up into frame with the contents of the oilcloth: a bow and arrow, which she pulls back with focused grace.
ANGLE: THE DOOR starts to come off its hinges.
INT. MR UNIVERSE'S HQ - CONTINUING A panel is kicked in from the ceiling and the Operative drops down, having clearly entered from a different location.
INT. MR UNIVERSE'S HQ - CONTINUING He looks around, carrying a laser-pistol.
INT. MR UNIVERSE'S HQ - CONTINUING He moves past Mr Universe and Lenore --
MAL Guy killed me, Mal.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING Mal has reached it and surveys the situation.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING Before him is a railing, and he can look down on the generator shaft.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING It's miles deep, with machines rotating and grinding, and arcs of electricity ricochetting around it.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING On the other side is a platform, with the broadwave console sitting behind a clear plastic partition.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING Cables and chains run along the ceiling, around a series of ladder rungs.
MAL Hard to get to.
MAL That's a fact.
INT. BLACK ROOM - CONTINUING lwi? 1/2  The door is pried partially open -- enough for one Reaver to squeeze through and charge.
INT. BLACK ROOM - CONTINUING Zoe stands up and shoots him in the head.
INT. BLACK ROOM - CONTINUING He arcs back hard as the second comes, Zoe shoots him, calmly walking toward the door --
JAYNE Zoe...
JAYNE Gorramnit...
JAYNE But she is in a trance, and we see beneath the calm, to the bubbling magma of rage that keeps her firing, single shots, each one a kill, till five men down and she's out of ammo.
JAYNE The sixth comes at her swinging a blade and she blocks, the precision of military training still in her as she flips him, wresting the blade free and swinging it down out of frame, bringing it up bloody, swinging again as the door bursts open and she's rushed from behind --- But Jayne totes an automatic, sprays killing fire on the lot, moving forward himself --
ZOE!
Get yer ass back in the line!
voi? 1/2  She looks up, almost confused -- and one of Jayne's targets comes back off the ground and slices at her back with a blade, she screams as he cuts deep -- and an arrow lodges in his neck.
Inara pulls up a fresh arrow, shaking only slightly.
Mal is on the railing, reaching for the 'rungs' on the ceiling just above him.
He can almost get them -- one wrong move and he pitches into the jaws of death...
A laser shot nails him in the lower back -- he arches, legs sliding off the rail -- he falls and hits the rail with the backs of his legs, flipping painfully onto his face as he falls, mercifully, back onto the platform.
The Operative comes around some equipment for a closer shot as Mal gets shakily up.
MAL Shot me in the back.
MAL I haven't...
MAL made you angry, have I?
MAL I s
THE OPERATIVE There's a lot of innocent people in the air being killed right now.
MAL You have no idea how true that is.
MAL There's no wise-ass attitude in him now.
MAL They stand, facing off at ten paces.
I know the secret now.
The truth that burned up River Tam's brain and set you after her.
And the rest of the 'verse is gonna know it too.
'Cause they need to.
THE OPERATIVE You really believe that?
MAL I do.
THE OPERATIVE You willing to die for that belief?
V0 I am.
V0 The Operative raises his gun -- but Mal is the quickdraw master, shoots the gun out of the Operative's hand and gets two hits to the chest (armored) before he makes it to cover.
Of course, that ain't exactly plan
He drops out his cartridge and slams another in.
The Operative hides behind some machinery.
Tries to peek out at Mal -- and more shots send him scrambling back to cover.
Mal holsters his gun and jumps for the rung above him, starts going hand over hand to the island, moving as fast as he can.
The Operative sees his moment, dives for his gun -- but it's been ruined by Mal's shot.
He looks over at Mal with death in his eyes.
He runs at the railing, vaults off it, and grabs a chain -- it snaps and he swings, grabbing another.
He reaches Mal and double kicks him from behind -- Mal flies 4 off the rung but grabs a chain -- he tries to kick at the Operative, but the guy is frikkin' Tarzan, he climbs up and pulls a lever releasing one end of Mal's chain -- Mal goes swinging, smacks into the wall six feet below the platform.
He scrambles up just as the Operative swings himself toward the platform from above.
Jayne is still firing continuously as he drags Zoe back to the barricades.
Simon moves to help -- Kaylee firing now, squinting with effort -- and pulls open the cut back of Zoe's shirt, checks the wound.
SIMON Spine's intact --
ZOE Just gimme a bandage.
ZOE Simon pulls a spraycan from his bag, sprays the wound with a foam that hardens instantly into an elastic covering.
There are a few gun shots (as well as nail-balls and blades) from the Reavers.
Jayne switches weapons, tossing another to Zoe and opening fire --
JAYNE Oh, now you're likin' guns, huh?
JAYNE Cheaters!
JAYNE He takes a hit in the shoulder, grimaces and keeps firing.
JAYNE River watches, the gun limp in her hand.
JAYNE Kaylee grabs it and starts another round -- but she's peppered with dart-like projectiles.
JAYNE She screams and drops the weapon, pulling the projectiles from her -- Inara helps her up, pulls her back as
Zoe shouts:
ZOE Everybody fall back!
ZOE Fall back!
ZOE Everyone stumbles or is dragged into the inner corridor.
ZOE Inara hits the controls and the doors start to close, from each side and above and below.
ZOE Then, when the hole is maybe four by four, they stop.
Jayne!
Grenade!
JAYNE Very last one...
JAYNE He tosses it through the hole.
JAYNE Zoe doesn't even flinch from the blast as she thinks.
ZOE They're gonna get in --
KAYLEE Can close it...
KAYLEE from outside...
ZOE No one's coming back from that...
ZOE She tries to stand, fails.
How much ammo do we have?
JAYNE We got three full cartridges and my swingin' cod.
JAYNE That's all.
JAYNE Inara is by the elevator, pounding for it to come.---
INARA Lift isn't moving...
ZOE When they come, try to plug the hole with 'em...
ZOE Kaylee cries out and Simon moves to her.
KAYLEE I'm starting to lose some feeling here...
KAYLEE I think there's something in them darts they throwed at me.
SIMON Lie still.
SIMON I'm gonna give you something to counteract the -- He stands, looking around him.
SIMON His bag is over by Zoe.
My bag.
and SHKOWW!, the bullet takes him in the belly -- everything suddenly moving very slowly as he spins slightly, one foot lifted, a confused expression on his face -- then speeding right back up as he slams down on his back, gasping for air.
River's mouth opens in a scream she doesn't make.
Blood spreads from Simon's belly.
Inara rushes to him, grabs cloth and puts pressure on the wound, puts Simon's hand on it.
INARA Keep pressure here...
SIMON My bag.
SIMON Need...
SIMON adrenaline...
SIMON and a shot of calaphar for Kaylee...
SIMON I can't...
SIMON River...?
SIMON She is by his side, takes his hand.
SIMON She has a kind of serenity to her, like she understands something now.
River...
I'm sorry...
RIVER No.
RIVER No.
RIVER The lights go out.
RIVER Everyone looks about them.
RIVER Jayne fires again, but all the sound has bled out save these two.
SIMON I hate to...
SIMON leave...
RIVER You won't.
RIVER You take care of me, Simon.
RIVER You've always taken care of me.
RIVER She stands as the emergency lights come on, giving her face an unearthly glow as she looks down at him.
My turn.
She's running so fast, nobody has time to react til she DIVES through the hole in the doors, then Simon SCREAMS her name, the scream following us back into the Black Room where River lands in a perfect roll, comes up in a room full of Reavers.
Without a moment's hesitation she makes it to the panel, gets the doors closing.
She dodges a blade, but a blow to,the back of the head shakes her.
She weaves around a couple of Reavers to get to the closing doors, but at the last second her ankle is grabbed and pulled out from under her.
The last thing we see is her being dragged back as they swarm over her.
ANGLE: THE BLAST DOORS, as they shut with a shuddering RLUNG.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING Mal gets up the chain to the platform.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING The Operative is on Mal before he gets his footing, tackles him as Mal's gun goes skittering over the edge into oblivion.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING There is a railing here or Mal would go over as well -- but he comes back with a couple of hammer blows, gets the Operative off him.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING They square off, Mal stumbling back into a tool chest, knocking over tools and computer parts.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING The Operative reaches behind him and pulls his sword gracefully from the holster under his jacket.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING Mal produces his weapon: a tiny screwdriver.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING He hurls a toolbox at the Operative and rushes him, gets inside sword range and tries for the neck with the screwdriver -- the Operative blocks it and works the sword point against the edge of Mal's stomach.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING Starts pushing slowly, despite Mal's resistance, and breaks skin.
Mal looks at the Operative a moment -- and the sword slides all the way through Mal's belly.
Mal's eyes go wide.
THE OPERATIVE You know what your sin is, Malcolm?
MAL Aw hell, I'm a fan of all seven.
MAL He headbutts the Operative viciously, then punches him so hard he staggers back, losing his grip on the sword.
MAL The Operative responds with a spin kick -- Mal holds up the screwdriver and the Operative swings his foot right into it, gasping as Mal pulls the screwdriver -- and leg it's stuck in -- back as he rockets his fist into the Operative's chin.
MAL The Operative goes down hard, dazed, as Mal grabs the sword still in his belly.
But right now...
He pulls the sword out, grimacing.
Holds it over the Operative.
The smile gone.
vao I'm gonna have to go with Wrath.
He stabs down at his foe's face -- but the Operative rolls out of the way, kicks Mal from the ground and is up in a second, grabbing Mal's sword hand -- the sword drops -- and punching him repeatedly in his stomach wound.
INT. INNER HALL - CONTINUING The gang is subdued -- because they are all of them injured and Simon is slipping away.
INT. INNER HALL - CONTINUING Jayne looks at Zoe.
JAYNE You suppose he got through?
JAYNE Think Mal got the word out?
ZOE He got through.
ZOE I know he got through.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING Mal goes down hard, spitting up blood.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING He sees the sword, moves -- but the Operative kicks him in the face.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING Picks him lod up, Mal too tired to throw a decent punch.
THE OPERATIVE I'm sorry.
THE OPERATIVE The Operative spins him and DIGS his bunched fingers right into the same nerve cluster that he paralyzed Doctor Mathias with.
THE OPERATIVE Mal goes rigid, his face a rictus of pain.
THE OPERATIVE The Operative goes near the railing and retrieves his sword.
THE OPERATIVE Mal trembles, trying to move -- but nothing happens.
You should know there's no shame in this.
You've done remarkable things.
But you're fighting a war you've already lost.
He lunges -- and Mal twists gracefully out of the way, grabbing the Operative's swordhand and pulling it forward -- while driving his elbow into the Operative's neck with staggering force.
MAL Iwo Well, I'm known for that.
MAL The Operative drops the blade, mouth open, stumbling back, unable to make a sound.
MAL Mal spins him, grabbing both his arms and working his own through them in a twisted full nelson -- then bringing his arms up suddenly, the Operative's mouth going wider as we hear his arms crack.
MAL Mal drops him sitting against the railing, picks up his
sword, saying:
Piece a shrapnel tore up that nerve cluster my first tour.
Had it moved.
He squats down, looks the Operative in the face.
Sorry 'bout the throat.
Expect you'd wanna say your famous last MW words now.
Just one trouble.
He reaches over the railing, pulls the back of the Operative's jacket through and shoves the sword through the fabric, pinning the Operative in his sitting position.
I ain't gonna kill you.
He moves to the console, starts prepping it.
Hell, I'm gonna grant your greatest wish.
He inserts the cylinder, turns it slightly.
It hums to life.
I'm gonna show you a world without sin.
He hits "send all".
The cylinder lights up and the broadcast V0 begins.
Here it is projected as a two-dimensional image on the clear plastic partition, right in front of the Operative.
There are images first of the city -- of bodies, on the street, in homes and offices...
image after image, jus.t as we saw on the research vessel -- and in River's mind.
These are some of the first sites we scouted on Miranda.
There is no one living on this planet.
There is no one...
Mal hits the controls and a ramp extends towards the other side.
He begins to cross.
Never even looks back.
On the Operative, trapped, watching in growing horror...
INT. BLACK ROOM - CONTINUING CLOSE ON: A Reaver in EXTREME SLOW MOTION.
INT. BLACK ROOM - CONTINUING Face full of fury, he is swinging his blade in a frenzy of hate.
INT. BLACK ROOM - CONTINUING And a small hand smashes that face so hard that teeth fly --
the Reaver clearing frame to reveal:
River.
She is bloodied, but not killed.
She's as she was in the bar -- moving faster and more efficiently than anyone can, ducking and weaving and gutting and kicking and there are piles of Reavers already, she never breaks concentration as she uses their own blades against them, throws them, does everything in her power to stay one step ahead of -- or above -- the mob.
She slams backwards into a wall opposite the blast doors -- and a grappling hook punches through it, just missing her.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING The Operative watches the end of the broadcast.
INT. BASEMENT, OVER THE GENERATOR - CONTINUING We are on his face through the clear plastic, so the images projected on it blur right before him: the Reaver, Dr. Caron -- and her screaming doesn't stop til something is shoved in her mouth.
INT. INNER HALL - CONTINUING The gang is still trying to patch themselves together when the elevator doors open.
INT. INNER HALL - CONTINUING Mal staggers out, holding his bleeding side.
ZOE Sir?
It's done.
Report?
Zoe looks at the badly wounded Simon, is about to give a report -- and the doors start to open behind her.
Everyone turns to look, those who can feebly raising weapons, as the square iris of the opening blast doors widens to reveal River, standing alone.
She is holding two Reaver blades, is bloody but unbowed.
And the only one alive.
We hold on her a moment, then the wall behind her is ripped completely away.
Behind it, grappling hooks chained to a huge tractor pull the wall away as through the smoke come some fifteen Alliance soldiers, who line up, rifles trained on our gang...
SOLDIER Drop your weapons!
SOLDIER Drop 'em now!
Do we engage?
Do we engage?
Mal and the others tense up.
River turns slowly to face the soldiers, blades still gripped...
A soldier levels his gun at her, sweaty and frantic...
others still shouting...
vp INT.
BASEMENT, OVER THE GENERATOR - CONTINUING The Operative sits in silence, the voices coming over his com:
SOLDIER Targets are acquired!
SOLDIER Do we have a kill order?
SOLDIER Do we have an order?
We are close on a gravestone.
It is rounded, looks more like a bell than a headstone.
It is topped by a jar built'into the stone.
The jar is weathered tin at top and bottom, but glass in the middle.
Inside the glass we can see one of those slightly moving photos.
It is of Mr Universe and his lovebot, and the name Mr Universe is carved roughly in the stone beneath.
The camera moves to the right and we see another such stone, 40 this one bearing the image and inscription: Shepherd Derrial Book.
The third is Hoban Washburne.
Wash.
The camera continues moving right, but the next stone houses a small home-made rocket with pieces of paper taped to it instead of a picture-jar.
And fixing another slip of paper to it is River.
She moves away from the stone as Mal does likewise.
They're flanked by the crew: Jayne, Inara (to whom Mal moves), Simon, who stands holding River before him and hand in hand with Kaylee.
He has a crutch supporting his other side.
There is a moment, then they all move aside, saying nothing.
Between them walks Zoe, in a simple white funeral gown, holding a burning taper.
She stands at the stones a moment, then holds the taper to the rocket fuse.
Stands back with the others.
The rocket shoots up into the darkening sky.
They all watch its sputtering tail a moment, then it it explodes in a series of fireworks.
WIDE ON the group, as the fireworks go off over their heads.
We are close on another explosion when it becomes: CLOSE ON: A BLOWTORCH spitting sparks.
Widen to see:
EXT. REPAIR YARD/SERENITY - DAY Zoe is harnessed to the nose of the ship, welding on a replacement for the very window the harpoon that impaled Wash came through.
We are close on River as she works inside a crawlspace just above the engine room, replacing wires.
Some of them run to a computer screen that she checks and adjusts.
Mal and Jayne hold onto the cannon as a crane is lifting it off the top of the ship.
Close on Mal as he watches it go...
t f o And here we see the whole ship for the first time, harnessed by the wings above the ground so she can be worked on all over.
The cannon is being hoisted away from her as a crew of repairmen wheel new landing gear under her belly.
INT. ENGINE ROOM - DAY Kaylee, deeply greasy, tweaks a part on the engine and crosses to the back where Simon, shirtless and not entirely ungreasy himself, is wrenching a bolt into place above his head.
INT. ENGINE ROOM - DAY A moment looking at him and she can't help herself - she slides her arms around his chest...
EXT. SERENITY - DAY On a scaffold, Inara repaints the name on the nose with elegant precision.
INT. ENGINE ROOM - DAY Kaylee and Simon are just making out like fiends, work completely forgotten.
INT. ENGINE ROOM - DAY With nothing resembling elegant precision, they sink out of frame to the floor.
A beat, and River's head appears from the crawlspace above, looking down at them with detached curiosity.
EXT. REPAIR YARD/SERENITY - DAY It's raining as Mal is hauling in the last of the repair equipment.
EXT. REPAIR YARD/SERENITY - DAY The camera moves around him, skirting the ground of the junkyard, till it lands on a figure in foreground, standing watching him from some twenty feet away.
EXT. REPAIR YARD/SERENITY - DAY Mal stops, doesn't turn.
EXT. REPAIR YARD/SERENITY - DAY Hand near his gun.
MAL If you're here to tell me we ain't finished...
MAL then we will be real quick.
MAL The Operative stands just under the canopy of the nose of the ship, framed by the rain behind.
THE OPERATIVE Do you know what an uproar you've caused?
THE OPERATIVE Protests, riots -- cries for a recall of the entire Parliament.
We've seen the broadwaves.
THE OPERATIVE You must be pleased.
MAL 'Verse wakes up a spell.
MAL Won't be long 'fore she rolls right over and falls back asleep.
MAL Taint my worry.
THE OPERATIVE I can't guarantee they won't come after you.
THE OPERATIVE The Parliament.
THE OPERATIVE They have a hundred men like me and they are not forgiving.
MAL That don't bode especially well for you...
MAL giving the order to let us go, patching up our hurt...
THE OPERATIVE I told them the Tams were no longer a threat -- damage done.
THE OPERATIVE (cont'd) They might listen, but...
I think they know I'm no longer their man.
They take you down, I don't expect to grieve overmuch.
Like to kill you myself, I see you again.
THE OPERATIVE You won't.
THE OPERATIVE There is...
THE OPERATIVE .nothing left to see.
THE OPERATIVE Mal looks at him a moment, then picks up his gear to head inside.
THE OPERATIVE The Operative starts away into the rain, then stops to look up at the nose of the ship.
THE OPERATIVE ANGLE: the newly painted Serenity, standing tall in the rain.
"Serenity".
You lost everything in that battle.
Everything you had, everything you were...
how did you go on?
Mal hits the button to close the inner doors, steps inside as they slide together.
Glances at the Operative, unimpressed.
MAL You still standing there when the engine starts, you never will figure it out.
MAL The Operative watches the door shut.
MAL A moment, and he goes.
INT. CARGO BAY - CONTINUING Mal stows the gear as Zoe approaches.
MAL What a whiner...
ZOE Sir, we have a green light.
ZOE Inspection's pos and we're clear for upthrust.
MAL Think she'll hold together?
ZOE She's tore up plenty.
ZOE But she'll fly true.
A beat between them before:
MAL Make sure everything's secure.
MAL Could be bumpy.
ZOE Always is.
ZOE She takes off and Mal heads up the stairs.
INT. FOREDECK HALL - CONTINUING Mal comes in and runs into Inara.
INT. FOREDECK HALL - CONTINUING Jayne passes through as they talk, heading down into his bunk.
INT. FOREDECK HALL - CONTINUING Pays them no mind.
INT. FOREDECK HALL - CONTINUING Neither do Simon and Kaylee, in the dining room stowing supplies.
MAL We're taking her out.
MAL Should be about a day's ride to get you back to your girls.
INARA Right.
MAL You ready to get off this heap and back to a civilized life?
INARA I, uh...
INARA I don't know.
INARA He looks at her, a smile in his eyes.
MAL Good answer.
MAL He turns and heads into the bridge.
INT. BRIDGE - CONTINUING Mal eases himself into his seat.
INT. BRIDGE - CONTINUING Takes a moment to adjust one of Wash's dashboard dinosaurs, then looks to his left.
MAL You gonna ride shotgun, help me fly?
MAL V0 River is in the copilot's seat, looking intently at the screens and buttons.
RIVER That's the plan.
MAL Think you can work out how to get her in the -- She is flipping switches without even looking, as the ship hums to life.
EXT. SERENITY - CONTINUING Her engines fire up and tilt.
EXT. SERENITY - CONTINUING She lifts gently off the ground.
INT. BRIDGE - CONTINUING Mal looks slightly, only slightly nonplussed.
MAL Okay, clearly some aptitude for the...
MAL but it ain't all buttons A0 and charts, .
MAL You know what the first rule of flying is?
MAL Well, I suppose you do, since you already know what I'm about to say.
RIVER I do.
RIVER But I like to hear you say it.
RIVER He looks out at the rain on his windows, at his screens,
taking her up as he says:
MAL Love.
MAL You can learn all the math in the 'verse, but you take a boat in the air you don't love, she'll shake you off just as sure as the turning of worlds.
MAL Love keeps her in the air when she oughta fall down, tells you she's hurting 'fore she keens.
MAL Makes her a home.
MAL River also looks out at the sky.
RIVER Storm's getting worse.
MAL We'll pass through it soon enough.
EXT. SERENITY - CONTINUING As we shoot up with her through sheeting rain, towards the top of the sky.
We are looking down on the stormclouds as Serenity bursts out of them, comes at us, flared by the sun behind the planet as she passes us, her Firefly effect lighting up, about to shoot off into the heavens -- There is a spark and a piece of paneling pops off, whips at camera, blacking out the frame.
What was that?
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
