JUNO
Written by
Diablo Cody
JUNO MacGUFF stands on a placid street in a nondescript subdivision, facing the curb.
It's FALL.
Juno is sixteen years old, an artfully bedraggled burnout kid.
She winces and shields her eyes from the glare of the sun.
The object of her rapt attention is a battered living room set, abandoned curbside by its former owners.
There is a fetid-looking leather recliner, a chrome-edged coffee table, and a tasteless latchhooked rug featuring a roaring tiger.
JUNO (V.O.) It started with a chair.
FLASHBACK - Juno approaches a boy hidden by shadow.
He's sitting in an overstuffed chair.
She slowly, clumsily lowers herself onto his lap.
A 60's Brazilian track plays from a vintage record player.
WHISPERED VOICE Do you know how long I've wanted this?
JUNO Yeah.
WHISPERED VOICE Wizard.
A DOG barks, jarring Juno back to reality.
JUNO Quiet, Banana.
JUNO Hey, shut your gob for a second, okay?
We see a teacup poodle tethered in the yard a few feet away from the abandoned living room set.
The dog yaps again.
JUNO (V.O.) This is the most magnificent discarded living room set I've ever seen.
She swigs from an absurdly oversized carton of juice and wipes her mouth with the back of her hand.
Juno marching down various street, pumping her arms like a jogger and chugging intermittently from the huge carton of juice.
We watch her breathlessly navigate suburbia, clearly on a mission.
Finally, a panting Juno arrives at DANCING ELK DRUG on the main drag of her small Minnesota suburb, Dancing Elk.
The automatic doors of the store part to reveal Juno's flushed serious face.
She carelessly flings the empty juice container over her shoulder and onto the curb.
A group of DROPOUTS with skateboards near the entrance glare at her.
She enters the DRUGSTORE.
ROLLO, the eccentric drugstore clerk, sneers at Juno from behind the counter.
He wears a polyester uniform vest.
ROLLO Well, well.
ROLLO If it isn't MacGuff the Crime Dog!
ROLLO Back for another test?
JUNO I think the last one was defective.
JUNO The plus sign looked more like a division sign.
Rollo regards her with intense skepticism.
JUNO I remain unconvinced.
Rollo pulls the bathroom key out of reach.
ROLLO This is your third test today, Mama Bear.
ROLLO Your eggo is preggo, no doubt about it!
An eavesdropping TOUGH GIRL wearing an oversized jacket and lots of makeup gapes at Juno from the beauty aisle.
TOUGH GIRL Three times?
TOUGH GIRL Oh girl, you are way pregnant.
TOUGH GIRL It's easy to tell.
TOUGH GIRL Is your nipples real brown?
A pile of stolen COSMETICS falls out of the girl's jacket and clatters to the floor.
TOUGH GIRL Balls!
Juno crosses and crosses her legs awkwardly, hopping.
It's obvious she has to use the bathroom urgently.
ROLLO Maybe you're having twins.
ROLLO Maybe your little boyfriend's got mutant sperms and he knocked you up twice!
JUNO Silencio!
JUNO I just drank my weight in Sunny D. and I have to go, pronto.
Rollo sighs and slips her the bathroom key.
Juno races down one of the aisles.
ROLLO Well, you know where the lavatory is.
ROLLO You pay for that pee stick when you're done!
ROLLO Don't think it's yours just because you've marked it with your urine!
JUNO Jesus, I didn't say it was.
ROLLO Well, it's not.
ROLLO You're not a lion in a pride!
ROLLO These kids, acting like lions with their unplanned pregnancies and their Sunny Delights.
In the dim, reeking public bathroom, Juno hovers over the commode with her boxer shorts around her ankles.
She clumsily tries to use the pregnancy test.
We see the test box sitting on the sink.
It's a TeenWave Discount Pregnancy Test.
The accompanying outdated package photo is of a shrugging 80s teen with a resigned expression.
The fine print on the box reads "From the makers of Sun-Glitz Lightening Hair Spritz!"
Juno holds the developing test in her hand and slaps the open test box on the front counter.
Rollo scans it and bags it indifferently.
JUNO Oh, and this too.
She places a giant licorice Super Rope on the counter.
ROLLO So what's the prognosis, Fertile Myrtle?
ROLLO Minus or plus?
JUNO I don't know.
JUNO It's not...
JUNO seasoned yet.
JUNO Wait.
JUNO Huh.
JUNO Yeah, there's that pink plus sign again.
JUNO God, it's unholy.
She shakes the stick desperately in an attempt to skew the results.
Shake.
Shake.
Nothing.
ROLLO That ain't no Etch-a-Sketch.
ROLLO This is one doodle that can't be undid, homeskillet.
Juno walks slowly and dejectedly up the street to her house, gnawing on the Super Rope.
She stops and loops the Super Rope over a low-hanging tree branch, contemplating how to fashion a noose.
Juno trudges toward her HOUSE.
The yard is a wild tangle of prairie grass and wild flowers.
Juno's BEDROOM is decorated with punk posters: The Damned, The Germs, the Stooges, Television, Richard Hell, etc.
She picks up a hamburger-shaped phone to call her best friend,
LEAH's room is cluttered with the sentimental junk that certain girls love to hoard.
The PHONE rings.
LEAH Yo-yo-yiggity-yo.
JUNO I am a suicide risk.
LEAH Is this Juno?
JUNO No it's Morgan Freeman.
JUNO Got any bones that need collecting?
LEAH Only the one in my pants.
JUNO Dude, I'm pregnant.
LEAH Maybe it's just a food baby.
LEAH Did you have a big lunch?
JUNO It's not a food baby.
JUNO I took three pregnancy tests today.
JUNO I am definitely up the spout.
LEAH How did you even generate enough pee for three pregnancy tests?
JUNO I drank like ten tons of Sunny Delight.
JUNO Anyway, yeah.
JUNO I'm pregnant.
JUNO And you're shockingly cavalier.
LEAH Is this for real?
LEAH Like for real, for real?
JUNO Unfortunately, yes.
LEAH Oh my God!
LEAH Oh shit!
LEAH Phuket Thailand!
JUNO That's the kind of emotion I was looking for in the first take.
LEAH Well, are you going to go to Havenbrooke or Women Now for the abortion?
LEAH You need a note from your parents for Havenbrooke.
JUNO I know.
JUNO Women Now, I guess.
JUNO The commercial says they help women now.
LEAH Want me to call for you?
LEAH I called for Becky last year.
JUNO Eh, I'll call them myself.
JUNO But I do need your help with something very urgent.
Leah and Juno struggle to drag a recliner across a well manicured suburban lawn.
They make a formidable team.
LEAH Heavy lifting can only help you at this point.
JUNO That is sick, man.
Leah busts a gut laughing.
It's a stunningly accurate portrayal of Bleeker's parents.
LEAH So, you were bored?
LEAH Is that how this blessed miracle came to be?
JUNO Nah, it was a premeditated act.
JUNO The sex, I mean, not getting pregnant.
LEAH When did you decide you were going to do Bleeker?
JUNO Like, a year ago, in Spanish class.
Bleeker and Juno are sitting at their desks, listening to a teacher lecturing about spanish.
Bleeker discreetly pushes a POSTCARD to Juno with his foot.
She picks it up off the floor, reads it, then looks at Bleeker, who is watching the teacher obediently.
LEAH Aha!
LEAH You love him.
JUNO It's extremely complicated, and I'd rather not talk about it in my fragile state.
She hefts a coffee table with her bare hands.
She's wearing her father's LIFTING BELT.
LEAH So, what was it like humping Bleeker's bony bod?
JUNO It was magnificent, man!
CU of Bleeker putting on double socks in his Car-Bed.
CU of Bleeker putting on his sweat bands.
CU of Bleeker applying Runner's Glide.
CU of a CROISSANT POCKET warming in the microwave.
PAUL BLEEKER steps onto the front porch of his house for early morning track practice.
He wears a cross country uniform that reads "DANCING ELK CONDORS."
He is eating some kind of microwaved snack gimmick.
Bleeker is startled to discover that Juno is outside waiting for him.
She has somehow arranged the living room set on the front lawn, and is seated in the armchair, chewing a pipe officiously.
JUNO Hey Bleek.
BLEEKER Hey, cool tiger.
BLEEKER Looks proud.
JUNO Yeah, I swiped it from Ms. Rancick.
BLEEKER Cool.
JUNO Your shorts are looking especially gold today.
BLEEKER My mom uses color-safe bleach.
JUNO Go Carole.
JUNO So, guess what?
BLEEKER I don't know...
JUNO I'm pregnant.
Stunned silence.
Juno pops up the footrest of the recliner and leans back comfortably.
BLEEKER I guess so.
BLEEKER What are you going to do?
The Dancing Elk Prep cross country team runs past Bleeker's house in a thundering herd, wearing a motley assortment of warm-ups.
Their momentum stirs the crackling fall leaves.
They wave and holler at Bleeker and Juno.
JUNO (V.O.) When I see them all running like that, with their things bouncing around in their shorts, I always picture them naked, even if I don't want to.
JUNO (V.O.) I have intrusive thoughts all the time.
BLEEKER I'm supposed to be running.
JUNO I know.
There's an awkward silence.
BLEEKER So, what do you think we should do?
JUNO I thought I might, you know, nip it in the bud before it gets worse.
JUNO Because I heard in health class that pregnancy often results in an infant.
BLEEKER Yeah, typically.
BLEEKER That's what happens when our moms and teachers get pregnant.
JUNO So that's cool with you, then?
BLEEKER Yeah, wizard, I guess.
BLEEKER I mean do what you think is right.
JUNO I'm real sorry I had sex with you.
JUNO I know it wasn't your idea.
BLEEKER Whose idea was it?
JUNO I'll see you at school, O.K.?
She mounts her bicycle and waves before riding off.
BLEEKER Whose idea was it?
Juno pushes her crappy bike into the bike rack and winds a lock around it.
In the background, a group of 3 NERDS play a live-action RPG.
NERD You did not!
NERD You don't have the armor.
NERD That Orc Armor you bought from the wizard doesn't have the power level to parry my hit!
Juno tries to push through the masses, but the throng of students is thick and unwielding.
Juno rummages through her locker, which is plastered with photos of Leah and Bleeker, plus a giant poster of Iggy Pop in his heyday.
She grabs a dilapidated physics textbook.
A few pages slip out.
STEVE RENDAZO (the same asshole who harassed her as she walked to the drugstore) passes by in the hallway.
STEVE RENDAZO Hey, your book fell apart!
JUNO Yeah.
STEVE RENDAZO It must have looked at your face.
He high-fives his klatch of buddies and moves along.
JUNO (V.O.) The funny thing is that Steve Rendazo secretly wants me.
JUNO (V.O.) Jocks like him always want freaky girls.
JUNO (V.O.) Girls with horn-rimmed glasses and vegan footwear and Goth makeup.
JUNO (V.O.) Girls who play the cello and wear Converse All-Stars and want to be children's librarians when they grow up.
JUNO (V.O.) Oh yeah, jocks eat that shit up.
We see Steve looking back at Juno for a brief second with mixed feelings.
JUNO (V.O.) They just won't admit it, because they're supposed to be into perfect cheerleaders like Leah.
JUNO (V.O.) Who, incidentally, is into teachers.
We see Leah at the far end of the hallway, talking animatedly with a paunchy middle-aged teacher, KEITH.
LEAH Me too!
LEAH I love Woody Allen!
STUDENTS bustle in, as the teacher, MR.
TINKER tries to maintain order.
Juno heads toward her desk and sets down her bag.
MR. TINKER People!
MR. TINKER We're doing our photomagnetism lab today, so find your partner and break out into fours.
Juno looks up and meets eyes with her longtime lab partner: Bleeker.
Sound the gong of awkwardness!
Juno and Bleeker head separately over to an available lab station and unpack their bags in silence.
JUNO Well!
JUNO Nothing like experimenting.
BLEEKER I did the prep questions for this lab last night.
BLEEKER You can copy my answers if you need to.
He slides a piece of graph paper in front of Juno without looking at her.
JUNO Oh, I couldn't copy your work.
BLEEKER But you copy my work every week.
JUNO Oh yeah.
JUNO I'm kind of a deadbeat lab partner, huh?
BLEEKER I don't mind.
BLEEKER You definitely bring something to the table.
JUNO Charisma?
BLEEKER Or something.
The other two LAB PARTNERS, a humorless couple, join them at the station.
JUNO So, who's ready for some photomagnificence?
GIRL LAB PARTNER I have a menstrual migraine, and I can't look at bright lights today.
GUY LAB PARTNER Amanda, I told you to go to the infirmary and lie down.
GUY LAB PARTNER You never listen.
GIRL LAB PARTNER No Josh, I don't take orders.
GIRL LAB PARTNER Not from you and not from any man.
GUY LAB PARTNER You know, you've been acting like this ever since I went up to see my brother at Mankato.
GUY LAB PARTNER I told you, nothing happened!
GIRL LAB PARTNER Something happened.
GIRL LAB PARTNER Because your eyes?
GIRL LAB PARTNER Are very cold?
GIRL LAB PARTNER They're very cold, Josh.
GIRL LAB PARTNER They're cold, lying eyes.
GUY LAB PARTNER What?
GUY LAB PARTNER My eyes are not lying!
GIRL LAB PARTNER Yes they are, Josh.
GIRL LAB PARTNER Since Mankato, they have been lying eyes.
Juno and Bleeker observe the argument like tennis spectators, fascinated by the dynamics of a real couple.
BLEEKER Okay...
BLEEKER I'm going to set up the apparatus.
BLEEKER Juno, want to get a C clamp out of that drawer?
GIRL LAB PARTNER I'm going to the infirmary.
GUY LAB PARTNER Good.
GUY LAB PARTNER Call me when you're OFF the rag.
GIRL LAB PARTNER Fine.
GIRL LAB PARTNER Call me when you learn how to love just one person and not cheat at your brother's college just because you had four Smirnoff Ices and a bottle of Snow Peak Peach flavored Boone's!
GUY LAB PARTNER Good, I'll be sure to do that, Amanda.
GUY LAB PARTNER I'll make a note of it.
He furiously scrawls a fake memo in his notebook.
JUNO Snow Peak Peach is the best flavor of Boone's.
JUNO Right, Bleek?
Bleeker reddens and continues constructing the apparatus.
GIRL LAB PARTNER stalks off dramatically.
Bleeker shakes his head and rifles through his textbook.
Juno examines a large ad in the newspaper that depicts a distraught TEEN GIRL clutching her head in a moment of staged conflict.
The ad reads: "Pregnant?
Find the clinic that gives women choice.
Women's Choice Health Center."
Juno picks up her hamburger phone and dials.
For a moment, she attempts to copy the melodramatic pose from the ad, checking herself out in the mirror.
JUNO "Para instruciones en Espanol, oprima numero dos."
She presses a few buttons in succession.
JUNO Yes, hello, I need to procure a hasty abortion?...
JUNO What was that?
JUNO I'm sorry, I'm on my hamburger phone and it's kind of awkward to talk on.
JUNO It's really more of a novelty than a functional appliance.
She SMACKS the phone a couple of times.
JUNO Better?
JUNO Okay, good.
JUNO Yeah, as I said, I need an abortion, two...
JUNO sixteen...
JUNO Um, it was approximately two months and four days ago that I had the sex.
JUNO That's a guestimate.
JUNO Okay, next Saturday?
JUNO Great.
She hangs up the phone.
JUNO (V.O.) I hate it when adults use the term "sexually active."
A HEALTH TEACHER in slo-mo puts a condom on a banana.
JUNO (V.O.) What does that even mean?
JUNO (V.O.) Can I deactivate someday, or is this a permanent state of being?
JUNO (V.O.) I guess Bleeker went live that night we did it.
JUNO (V.O.) I guess he hadn't done it before, and that's why he got that look on his face.
We see Paulie's face at the moment of his deflowering: he's comically wide-eyed with shock.
Juno, her father MAC, her stepmother BREN, and LIBERTY BELL sit at a very typical kitchen table, eating dinner.
MAC shovels food while chatting about his day.
MAC You should have seen this octopus furnace.
MAC I had to get out my Hazmat suit just to get up in there...
JUNO (V.O.) My dad used to be in the Army, but now he's just your average HVAC specialist.
JUNO (V.O.) He and my mom got divorced when I was five.
JUNO (V.O.) She lives on a Havasu reservation in Arizona...
JUNO (V.O.) ...with her new husband and three replacement kids.
JUNO (V.O.) Oh, and she inexplicably mails me a cactus every Valentine's Day.
PILE OF NEGLECTED CACTI festering in a corner of Juno's room.
JUNO (V.O.) And I'm like, "Thanks a heap, Coyote Ugly.
JUNO (V.O.) This cactus-gram stings even worse than your abandonment."
BREN is cutting up LIBERTY'S food diligently.
Her nails are brilliant, holding the silverware.
JUNO (V.O.) That's my stepmom, Bren...
Bren stitches a needlepoint pillow of a dog.
JUNO (V.O.) She's obsessed with dogs...
Bren's nail salon in all its glory.
JUNO (V.O.) ...owns a nail salon called Bren's Tens...
Bren chats up a customer as she applies a fresh coat.
JUNO (V.O.) ...and she always smells like methylmethacrylate.
Liberty Bell coughs pitifully as Bren leans over her plate.
MAC So Juno, how did your maneuver go last night?
JUNO Which maneuver, sir?
JUNO The one in which I moved an entire living room set from one lawn to another, or the one in which I cleared a sixty-four ounce blue slushie in ten minutes?
Bren speaks in her strong city accent.
BREN Juno?
BREN Did you happen to barf in my urn?
BREN Mac, you know that nice urn by the front door, the one I got up in Stillwater?
BREN I found some weird blue shit, I mean stuff, gunk, in there this morning.
JUNO I would never barf in your urn, Brenda.
JUNO Maybe L.B. did it.
We see Liberty Bell blithely pouring bacon bits onto her dinner.
MAC Liberty Bell, if I see one more Baco on that potato, I'm gonna kick your monkey ass.
Juno trudges toward the front entrance of the clinic.
There is a lone ABORTION PROTESTER, a teenager of Asian descent holding a hugely oversized sign that reads "NO BABIES LIKE
LONE PROTESTER All babies want to get borned!
LONE PROTESTER All babies want to get borned!
Juno recognizes the PROTESTER as a classmate of hers.
JUNO Uh, hi Su-Chin.
SU-CHIN Oh, hi Juno.
SU-CHIN How are you?
JUNO Good.
JUNO I'm good.
JUNO Did you finish that paper for Worth's class yet?
SU-CHIN No, not yet.
SU-CHIN I tried to work on it a little last night, but I'm having trouble concentrating.
JUNO You should try Adderall.
SU-CHIN No thanks.
SU-CHIN I'm off pills.
JUNO Wise move.
JUNO I know this girl who had a huge crazy freakout because she took too many behavioral meds at once.
JUNO She took off her clothes and jumped into the fountain at Ridgedale Mall and she was like, "Blaaaaah!
JUNO I'm a kraken from the sea!"
SU-CHIN I heard that was you.
JUNO Well, it was nice seeing you.
She continues on toward the clinic entrance.
SU-CHIN Juno!
SU-CHIN Your baby probably has a beating heart, you know.
SU-CHIN It can feel pain.
SU-CHIN And it has fingernails.
JUNO Really?
JUNO Fingernails?
She considers the concept, then pushes open the clinic door.
The receptionist sits behind a pane of bulletproof glass.
The waiting room is semi-crowded, occupied mostly by pregnant women, teens and ill-behaved children.
PUNK RECEPTIONIST Welcome to Women's Choice, where women are trusted friends.
PUNK RECEPTIONIST Please put your hands where I can see them and surrender any bombs.
Juno flashes her best jazz hands.
JUNO Hi.
JUNO I'm here for the big show?
PUNK RECEPTIONIST Your name, please?
JUNO Juno MacGuff.
The receptionist raises a pierced eyebrow and arranges some paperwork on a clipboard.
JUNO (V.O.) She thinks I'm using a fake name.
JUNO (V.O.) Like Gene Simmons or Mother Teresa.
The receptionist hands Juno the clipboard and a pen.
PUNK RECEPTIONIST I need you to fill these out, both sides.
PUNK RECEPTIONIST And don't skip the hairy details.
PUNK RECEPTIONIST We need to know about every score and every sore.
The receptionist reaches into one of those ubiquitous women's clinic CONDOM JARS, and holds up a fistful of purple rubbers.
PUNK RECEPTIONIST Would you like some free condoms?
PUNK RECEPTIONIST They're boysenberry.
JUNO No thank you.
JUNO I'm off sex.
PUNK RECEPTIONIST My partner uses these every time we have intercourse.
PUNK RECEPTIONIST They make his balls smell like pie.
JUNO Congrats.
She takes a seat in the WAITING ROOM and rifles through a pile of old magazines.
The magazine selection is lots of "mommy mags" and health related periodicals.
She selects an issue of Family Digest and gingerly flips through for a few moments.
Then she looks over and notices the FINGERNAILS of a nearby teen, who looks as nervous as she does.
The girl bites her thumbnail and spits it onto the floor.
Juno looks away, but immediately notices another waiting woman, who absently scratches her arm with long fake nails.
Suddenly, she sees fingernails EVERYWHERE.
The receptionist clicks her nails on the front desk.
Another woman blows on her fresh manicure.
Everyone seems to be fidgeting with their fingers somehow.
Juno suddenly looks terror-stricken...
PUNK RECEPTIONIST Excuse me, Miss MacGoof?
There's no answer.
We see that Juno's chair is EMPTY.
The receptionist cranes her neck and sees the front door drift shut.
Juno's figure recedes into the distance as she tears off down the street, running as fast as she can.
Leah's front door swings open to reveal a breathless Juno standing sheepishly on the porch.
Leah sighs.
LEAH What are you doing here, dumbass?
LEAH I thought I was supposed to pick you up at four.
JUNO I couldn't do it, Leah!
JUNO It smelled like a dentist in there.
JUNO They had these really horrible magazines, with, like, spritz cookie recipes and bad fiction and water stains, like someone read them in the tub.
JUNO And the receptionist tried to give me these weird condoms that looked like grape suckers, and she told me about her boyfriend's pie balls, and Su-Chin Kuah was there, and she told me the baby had fingernails.
JUNO Fingernails!
LEAH Oh, gruesome.
LEAH I wonder if the baby's claws could scratch your vag on the way out?
JUNO I'm staying pregnant, Le.
LEAH Keep your voice down dude, my mom's around here somewhere.
LEAH She doesn't know we're sexually active.
JUNO What does that even mean?
JUNO Anyway, I got to thinking on the way over.
JUNO I was thinking maybe I could give the baby to somebody who actually likes that kind of thing.
JUNO You know, like a woman with a bum ovary or something.
JUNO Or some nice lesbos.
LEAH But then you'll get huge.
LEAH Your chest is going to milktate.
LEAH And you have to tell everyone you're pregnant.
JUNO I know.
JUNO Maybe they'll canonize me for being so selfless.
LEAH Maybe they'll totally shit and be super mad at you and not let you graduate or go to Cabo San Lucas for spring break.
JUNO Bleeker and I were going to go to Gettysburg for spring break.
Leah sighs, as if there's no helping her nerdy friend.
LEAH Well, maybe you could look at one of those adoption ads.
LEAH I see them all the time in the Penny Saver.
JUNO There are ads?
JUNO For parents?
LEAH Oh yeah!
LEAH "Desperately Seeking Spawn."
LEAH They're right by the ads for like, iguanas and terriers and used fitness equipment.
LEAH It's totally legit.
JUNO Come on, Leah.
JUNO I can't scope out wannabe parents in the Penny Saver!
JUNO That's tacky.
JUNO That's like buying clothes at the Pump n' Munch.
Juno and Leah are sitting at a bench in a park.
They slurp giant blue slushies and sift through a pile of Penny Savers.
Juno has her pipe with her.
JUNO The Penny Saver sucks.
LEAH Yeah, but it sucks for free.
They turn the pages in silence for a moment.
Their lips and teeth are Windex-blue.
LEAH Look at this one "Wholesome, spiritually wealthy couple have found true love with each other."
LEAH "All that's missing is your bastard."
JUNO There's a guy in here who's giving away a piano.
JUNO Free for the hauling!
JUNO We should put it in Bleeker's yard.
LEAH You're not listening to me.
JUNO No, I heard you.
JUNO I just can't give the baby to people who describe themselves as "wholesome."
JUNO I'm looking for something a little edgier.
LEAH What did you have in mind, a family of disturbed loners who are into gunplay and incest?
JUNO I was thinking a graphic designer, mid-thirties, and his cool Asian wife who dresses awesome and plays bass.
JUNO But I'm trying to not be too particular.
LEAH All right, how about this one?
LEAH "Healthy, educated couple seeking infant to join our family of five.
LEAH You will be compensated.
LEAH Help us complete the circle of love."
JUNO Yeesh, they sound like a cult.
JUNO Besides, they're greedy bitches.
JUNO They already have three kids!
LEAH Hey, Juno.
LEAH Juno!
LEAH Look at this one.
She points to the paper and motions for Juno to look.
Juno scans the ad silently.
We see the ad.
It contains a photo of an attractive couple with ambiguous Mona Lisa smiles.
It reads "Educated, successful couple wishes to..."
JUNO (V.O.) They were Mark and Vanessa Loring, and they were beautiful even in black and white.
We see Paulie's bedroom window -- festooned with childish curtains -- and the light on inside.
Bleeker lies on his Car-bed in his track uniform, listening to the same LP from when he and Juno went all the way.
He stares between the pages of his embossed Dancing Elk Prep yearbook.
We see the object of his gaze is Juno's black and white YEARBOOK PHOTO.
Next to it, we see a sloppy, handwritten message from Juno.
We hear Juno's voice reading the message:
JUNO (V.O.) Hey Bleeker!
JUNO (V.O.) Spank off to this with motion lotion.
JUNO (V.O.) Just kidding (kind of.)
JUNO (V.O.) Your best friend, Juno.
Bleeker picks up the phone.
It's the same HAMBURGER PHONE Juno has.
He reconsiders and puts it down.
There's a knock on the bedroom door.
BLEEKER'S MOM pokes her dowdy head inside.
BLEEKER'S MOM Paul?
BLEEKER'S MOM Are you coming downstairs to eat?
BLEEKER I don't think so.
BLEEKER'S MOM You ran eight miles today, Puppy.
BLEEKER I'm not hungry, oddly.
BLEEKER'S MOM But it's breakfast for supper.
BLEEKER'S MOM Your favorite, Paulie.
BLEEKER'S MOM I made French toast and sausage.
BLEEKER'S MOM Patties, not linkies, just like you like it.
Bleeker places his hand silently on his stomach.
BLEEKER'S MOM Juno MacGuff called while you were out running.
BLEEKER'S MOM She wants to know if you're coming to her little coffeehouse performance on Saturday.
BLEEKER Thanks for the message.
BLEEKER'S MOM You know how I feel about her.
BLEEKER You've mentioned it about fifty times.
BLEEKER'S MOM I just hope you don't consider her a close friend.
Bleeker's mom gives up and closes the door.
We see that Bleeker is clutching a pair of PANTIES in one hand, which he slowly releases as the 45 ends.
Bren and MAC are seated on the couch.
Leah is standing nearby for reinforcements.
Juno paces nervously, trying to suss out how to break the massive news.
JUNO I have no idea how to spit this out.
BREN Hon, did you get expelled?
JUNO No.
JUNO The school would probably contact you in the event of my expulsion.
BREN Well, I was just asking.
BREN It seemed plausible.
MAC Do you need a large sum of money?
MAC Legal counsel?
JUNO No, no, I'm definitely not asking for anything.
JUNO Except maybe mercy.
JUNO Like, it would be really great if nobody hit me.
MAC What have you done, Junebug?
MAC Did you hit someone with the Previa?
LEAH Best to just tell them, man.
LEAH Rip off the Band-Aid and let it bleed.
JUNO I'm pregnant.
Bren and Mac are predictably speechless.
BREN Oh, God...
JUNO But I'm going to give it up for adoption.
JUNO I already found the perfect people.
Leah presents the Penny Saver photos of the Lornings.
JUNO They say they're going to pay my medical expenses and everything.
JUNO I promise this will all be resolved in thirty-odd weeks, and we can pretend it never happened.
MAC You're pregnant?
JUNO I'm so sorry, you guys.
JUNO If it's any consolation, I have heartburn that's like, radiating down to my kneecaps and I haven't gone number two since Wednesday.
JUNO Morning!
BREN I didn't even know you were sexually active!
Juno cringes upon hearing her most-hated term.
MAC Who is the kid?
JUNO The baby?
JUNO I don't know anything about it yet.
JUNO I only know it's got fingernails, allegedly.
BREN Nails?
BREN Really?
MAC No, I mean the father!
MAC Who's the father, Juno?
JUNO Oh.
JUNO It's, well, it's Paulie Bleeker.
Bren and Mac burst into shocked laughter.
JUNO What?
MAC Paulie Bleeker?
MAC I didn't know he had it in him!
BREN He just doesn't look, well, virile.
LEAH I know, right?
MAC Okay, this is no laughing matter.
JUNO No, it's not.
JUNO Paulie is virile, by the way.
JUNO He was very good in...
JUNO chair.
Leah fires a be quiet glance at Juno.
MAC Did you say you were thinking about adoption?
JUNO Yeah, well, there's this couple who've been trying to have a baby for five years.
LEAH We found them in the Penny Saver by the exotic birds section.
Bren looks understandably alarmed.
Juno hastily attempts to make the situation sound more legitimate.
JUNO But they have a real lawyer and everything.
JUNO I'm going to meet with them next weekend.
BREN Junebug, that is a tough, tough thing to do.
BREN Probably tougher than you can understand right now.
JUNO Well, I'm not ready to be a mom.
MAC Damn skippy, you're not!
MAC You don't even remember to give Liberty Bell her breathing meds.
JUNO Once!
JUNO And she didn't die, if you recall!
BREN Honey, had you considered, you know, the alternative?
Leah and Juno exchange glances.
JUNO No.
BREN Well, you're a brave young lady.
BREN You're made of stronger stuff than I thought.
BREN You're a little Viking!
JUNO Cool it.
BREN First things first, we have to get you healthy.
BREN You need prenatal vitamins.
BREN Incidentally, they'll do incredible things for your nails, so that's a plus.
BREN Oh, and we need to schedule a doctor's appointment.
BREN Find out where you're going to deliver.
JUNO The term "deliver" is so weird.
JUNO Can we not say "deliver"?
LEAH How does "crap it out" sound?
MAC Juno, I want to come with you to meet these adoption people.
MAC You're just a kid.
MAC I don't want you to get ripped off by a couple of babystarved wingnuts.
JUNO Sure, Dad.
Mac nods, satisfied, then contemplates the situation dismally.
MAC I thought you were the kind of girl who knew when to say when.
JUNO I have no idea what kind of girl I am.
BREN Why don't you girls go upstairs for a while?
BREN I think Mac's gonna blow.
Juno and Leah hightail it upstairs.
MAC Just tell it to me straight, Bren.
MAC Do you think this is my fault?
MAC Her mother's fault?
BREN I think kids get bored and have intercourse.
BREN And I think Junebug was a dummy about it.
BREN But we have to move on from here and help her figure it out.
MAC I'm not ready to be a Pop-Pop.
BREN You're not going to be a Pop-Pop.
BREN And Juno's not going to be a ma.
BREN Somebody else is going to find a precious blessing from Jesus in this garbage dump of a situation.
BREN I friggin' hope.
MAC Did you see it coming when she sat us down here?
BREN Oh God yeah.
BREN But I was hoping she was expelled or into hard drugs.
MAC That was my first instinct too.
MAC Or D.W.I.
MAC Anything but this.
MAC And I'm going to punch that Bleeker kid in the weiner the next time I see him.
BREN Oh Mac, no!
BREN He's a sweet kid.
BREN You know it wasn't his idea.
Mac shrugs in agreement.
Music plays as we see SPARSE IMAGES OF VANESSA LORING'S HANDS preparing the house for Juno's arrival --
Sprucing a vase of FLOWERS.
Straightening a FRAMED PHOTO of the Lorings.
Dusting off a table with one of those WETNAPS for furniture.
Lining up a shelf of BOOKS.
The Previa cruises slowly into the Loring's fancy gated community.
Mac pulls over and parks on the curb.
Mark and Vanessa Loring have an impressive, though generic McMansion.
The entire yard is unlandscaped soil.
Mac presses the doorbell while Juno chews her nails uncomfortably.
Both look mortified as they wait for someone to greet them.
VANESSA opens the door.
She's a pretty, meticulous woman in her early thirties.
Very Banana Republic.
VANESSA Hi!
VANESSA I'm Vanessa.
VANESSA You must be Juno and Mr. MacGuff.
VANESSA I'm Vanessa.
JUNO Vanessa, right?
MAC Hello.
MAC Thank you for having me and my irresponsible child over to your home.
VANESSA Oh no.
VANESSA Thank you.
VANESSA Come on in.
Vanessa awkwardly leads them into her home.
VANESSA Can I take your coats?
JUNO Sure.
She takes off her hooded sweatshirt and thrusts it into Vanessa's arms who sets it on a bench.
JUNO Wicked pic in the Penny Saver, by the way.
JUNO Super classy.
JUNO Not like those other people with the fake woods in the background.
JUNO Like I'm really going to fall for that, you know?
VANESSA You found us in the Penny Saver?
MARK LORING appears next to Vanessa.
He's a boyishly attractive guy in his mid-thirties.
He glances sheepishly at Vanessa upon hearing the Penny Saver mention, then extends his hand to Mac and Juno.
MARK Hi.
MARK I'm Mark Loring.
MARK I'm the husband.
Mark and Vanessa usher Juno and Mac into the austere, spacious living room.
A woman in a business suit sits on the couch with a briefcase in her lap.
MARK This is our attorney, Gerta Rauss.
JUNO Geeeerta Rauuuss!
GERTA Nice to meet you.
Mac seizes Mark's hand and pumps it heartily.
MAC I'm Mac MacGuff, and this, of course, is my daughter Juno.
MARK Like the city in Alaska?
JUNO No.
MARK Cool.
MARK Well, let's sit down and get to know each other a bit.
VANESSA I'll get drinks.
VANESSA What would everyone like?
VANESSA I've got Pellegrino, Vitamin Water...
JUNO A Maker's Mark, please.
JUNO Up.
MAC She's joking.
MAC Junebug has a wonderful sense of humor, which is just one of her many genetic gifts.
JUNO I also have good teeth.
JUNO No cavities.
JUNO We finally got fluoridated water in Dancing Elk.
She bares them frighteningly to demonstrate.
Vanessa stares, unflappable.
MAC We're fine, thank you.
Mac and Juno join Mark and Gerta Rauss on the couch.
GERTA So, Juno.
GERTA First off, how far along are you?
JUNO I'm a junior.
GERTA No, I mean in your pregnancy.
JUNO Oh.
JUNO Uh, my stepmom took me to the doctor yesterday and they said I was twelve weeks.
Vanessa enters with the refreshments on a tray.
VANESSA Oh, that's marvelous.
VANESSA So you're almost into your second trimester, then?
JUNO Yeah, apparently.
JUNO I'm having it on May 4.
VANESSA The tough part's almost over for you.
VANESSA I mean, my girlfriends always tell me the first couple months are the hardest.
JUNO Yeah, but I hardly noticed it.
JUNO I'm more worried about the part where I have to start wearing jeans with an elastic panel in the front.
VANESSA I think pregnancy is beautiful.
JUNO Well, you're lucky it's not you.
Vanessa's looks to the ceiling.
MARK So, let's discuss how we're gonna do this...
MARK thing.
JUNO Well, I just have the baby and give it to you, right?
GERTA Mark and Vanessa are willing to negotiate an open adoption.
MAC Wait.
MAC What does that mean?
GERTA It means they'd send annual updates, photos, let Juno know how the baby is doing as he or she grows up.
GERTA Of course, Juno's legal rights would be terminated...
JUNO Whoah.
JUNO I don't want to see pictures.
JUNO I don't need to be notified of anything.
JUNO Can't we just kick it old school?
JUNO I could just put the baby in a basket and send it your way.
JUNO You know, like Moses in the reeds.
MARK Technically, that would be kickin' it Old Testament.
Mark and Juno lock eyes.
JUNO Yeah.
JUNO Yeah!
JUNO The way people used to do it.
JUNO Quick and dirty, like ripping off a Band-Aid.
GERTA Well, then we agree a traditional closed adoption would be best for all involved, then?
JUNO Shit, yeah.
JUNO Close it up.
Vanessa is clearly ecstatic.
MARK Obviously, we'll compensate you for your medical expenses.
VANESSA Are you looking for any other compensation?
MAC Excuse me?
JUNO Well, no...
JUNO I'm not going to sell the baby.
JUNO I just want it to grow up with people who are ready to love it and be parents.
JUNO I'm in high school, dude.
JUNO I'm ill-equipped.
VANESSA You're doing an amazing and selfless thing for us.
MARK Vanessa has wanted a baby since we got married.
VANESSA I want to be a mommy so badly!
Juno and Mac stare at her.
MAC You don't say.
VANESSA Well, haven't you ever felt like you were born to do something?
MAC Yes.
MAC Heating and air conditioning.
VANESSA Well, I was born to be a mother.
VANESSA Some of us are.
JUNO Mark, are you looking forward to being a dad?
Mark is caught off guard.
MARK Sure, why not?
MARK I mean, every guy wants to be a father.
MARK Coach soccer, help with science projects and...
MARK I don't know.
MARK Fatherly stuff.
Mac casts a subtle, dubious glance at Mark.
VANESSA Well, shall we start looking over the paperwork?
VANESSA Gerta has already drafted some preliminary documents.
JUNO Can I use the facilities first?
JUNO Being pregnant makes you pee like Seabiscuit.
VANESSA Sure.
VANESSA The powder room down here is being re-tiled, but you can use the master bath upstairs.
VANESSA Go up, then turn left and on your right...
JUNO Room with a toilet, got it.
Juno heads into the foyer and up the stairs.
We see a posed photo of Mark and Vanessa in the stairwell.
Their house is beautiful, but frigid.
Juno rubs her arms, shivering.
The Loring's bathroom is huge.
Juno flushes and goes to the double sink to wash her hands.
She opens the overhead cabinet and sees Vanessa's toiletries.
She spritzes on some perfume and examines the more expensive grooming items.
There's a crinkled tube of LUBE in the cabinet.
Juno picks it up, fascinated.
She rubs a drop of it between her hands and runs it through her hair like pomade.
Juno opens the bathroom door and instantly BUMPS into Mark.
JUNO Whoops!
JUNO Yikes, I didn't expect to see you up here.
MARK Sorry.
MARK I was just getting something.
JUNO Did your wife send you up here to spy on me?
MARK What?
MARK No!
MARK Do we come off like paranoid yuppies or something?
JUNO Well, you don't just invite a random pregnant teenager into your house and leave her unsupervised.
JUNO I could be a total klepto, for all you know.
MARK I don't get a klepto vibe from you.
MARK Evil genius?
MARK Maybe.
MARK Arsonist?
MARK Wouldn't rule it out.
JUNO I did steal a squirt of perfume.
JUNO What do you think?
JUNO It's Clinique Happy.
She holds her WRIST up to Mark's twitching nostrils.
JUNO Smell those sparkling topnotes!
Mark inhales.
MARK Am I supposed to feel happy now?
JUNO You should be happy, Holmes.
JUNO I'm giving you and Vanessa the gift of life.
JUNO Sweet, screaming, pooping life!
JUNO And you don't even have to be there when the baby comes out of me all covered in...
MARK Viscera?
JUNO Blood and guts.
MARK We'd better get back downstairs ASAP.
Juno mocks his use of "ASAP" silently.
JUNO Wait a minute.
JUNO Is that a Les Paul?
Juno is staring into a room with the door slightly ajar.
We see GUITARS mounted on the wall, and the edges of posters.
MARK Oh.
MARK That's, uh, my room.
MARK Vanessa lets me have a room for all my old stuff.
JUNO Wow, you get a whole room in your own house?
JUNO She's got you on a long leash there, Mark.
MARK Shut up.
The walls are plastered with FRAMED POSTERS of early-90s alt rock bands.
(Mudhoney, Jane's Addiction etc.)
Mark removes his LES PAUL from its moorings and hands it to Juno.
JUNO It's beautiful.
JUNO I've always liked Gibson better than Fender.
MARK What do you play?
JUNO I rock a Harmony.
MARK Oh.
JUNO What?
JUNO I'm a pawn shop rocker.
MARK Sorry.
MARK I swear I'm not a gear snob.
Juno turns the guitar over, examining it closely.
JUNO What is that, Mahogany?
JUNO What happens if you crack the neck?
MARK Tell me about it.
MARK I used to play in a really tight band back when I lived in Chicago, and one night we opened for the Melvins...
MARK do you know who the Melvins are?
JUNO Yeah.
MARK Well, we were playing with them and I busted this guitar onstage.
MARK It cost me $800 and a dime bag just to have it fixed.
JUNO When was this, like '96?
MARK '93.
MARK I'm telling you that was the best time for rock and roll.
JUNO Nuh-uh, 1977!
JUNO Punk Volume 1.
JUNO You weren't there, so you can't understand the magic.
MARK You weren't even alive!
Vanessa, Mac and Gerta Rauss are waiting in awkward silence for Juno and Mark to return.
Mac notices a brand new PILATES MACHINE sitting in its packaging in a corner of the room.
MAC So.
MAC What's that thing?
VANESSA A Pilates machine?
MAC What do you make with that?
VANESSA You don't make anything.
VANESSA It's for exercising.
Mark and Juno tool around on the guitars unplugged.
They play little riffs.
He teaches her a couple chords.
MAC My wife just ordered one of those Tony Little Gazelles off the TV, you know, from the guy with the ponytail?
Vanessa and Gerta have no response.
MAC That guy just doesn't look right to me.
Suddenly, a shriek of AMP FEEDBACK, followed by loud, discordant GUITAR STRUMMING can be heard drifting down from upstairs.
Vanessa's looks to the ceiling.
VANESSA Will you excuse me?
Mark has strapped on the Les Paul and is playing and singing.
"Doll Parts" by Hole.
JUNO AND MARK "Yeah, they really want you...
JUNO AND MARK they really want you...
JUNO AND MARK they really do."
Building together.
JUNO AND MARK Yeah, they really want you...
JUNO AND MARK they really want you...
JUNO AND MARK and I do to.
VANESSA appears in the doorway.
Juno immediately puts down the guitar.
Mark doesn't notice her immediately.
I WANT TO BE THE... Oh, sorry honey...
Mark clumsily puts down the guitar and stands up.
VANESSA You guys are playing music?
MARK Juno just wanted a closer look at Kimber here.
JUNO Your guitar is named Kimber?
MARK Yeah.
JUNO That's all right.
JUNO My axe is named Roosevelt.
JUNO After Franklin, not Ted.
JUNO Franklin was the hot one with the polio.
VANESSA I think Gerta is waiting for us downstairs with some important stuff for us to go over.
Mark hangs the guitars back on the wall.
He and Juno exit the room, chastised.
Vanessa looks to Mark in question.
VANESSA Didn't mean to interrupt the jam sessions.
Juno and Mac have put their coats on and are in the process of leaving.
Gerta hands Juno the DOCUMENTS.
Vanessa and Mark trail behind.
GERTA So, look those over and give me a call at my office if you have any questions.
VANESSA Juno, we'd really appreciate it if you could keep us updated on any doctor's appointments, ultrasounds, other things of that nature.
JUNO Oh.
JUNO Sure.
JUNO Of course you'd want to know how your kid is cooking.
VANESSA So, then, you really think you're going to go ahead with this?
Mac STARES at Juno gravely.
JUNO Yeah.
JUNO For sure.
JUNO I like you guys.
Juno looks at Mark.
VANESSA How sure?
VANESSA Percentage-wise, would you say you're 80% sure, 90% sure?
Mark seems visibly embarrassed by Vanessa's manic demeanor.
JUNO I'm going to say I'm 104% sure.
VANESSA Oh really?
JUNO Look, if I could give it to you now, I would.
JUNO But it probably looks like a Sea Monkey at this point, so I think we should leave it in there for a while until it gets cuter, you know?
MAC I think that's a great idea.
MARK That's great, right?
MARK Stellar news.
MARK Well, you guys drive safe, and we'll hear from you soon, all right?
MAC All right, take care of yourselves.
Juno and Mac exit.
Mark shuts the door.
All is silent in the foyer.
Mark, Vanessa and Gerta stand motionless.
Gerta pumps her fist triumphantly, trying to create a mood of celebration.
GERTA All RIGHT!
Vanessa buries her head in her hands and weeps hoarsely.
It is now WINTER.
The TRACK TEAM jogs in formation, leaving tracks in the snow.
Those bastards never stop running.
Bleeker is running alone on the track.
His exhalations are icy puffs in the air.
Bleeker's friend VIJAY jogs up alongside him.
Vijay is a solemn, skinny boy, much like Bleeker.
VIJAY Hey man.
BLEEKER Oh, hey Vijay.
VIJAY Did you hear Juno MacGuff is pregnant?
BLEEKER Yup.
VIJAY Just like our moms and teachers!
BLEEKER Yup.
VIJAY Did you hear it's yours?
BLEEKER Yup.
VIJAY What a trip, man.
BLEEKER I don't really know anything about it.
VIJAY You should grow a moustache.
VIJAY You're a real man now.
BLEEKER I can't grow a moustache.
BLEEKER It never comes in evenly.
VIJAY Me neither.
VIJAY But I'm going to stop wearing underpants in order to raise my sperm count.
VIJAY See you.
VIJAY jogs off.
Bleeker STOPS and wipes away his sweat.
We're looking over Juno's now FIVE MONTH PREGNANT BELLY to a school administrator filling out a slip.
Juno takes the slip, turns around and smiles all the way out.
Juno exits the head office and bumps into Bleeker.
BLEEKER Hey Juno...
BLEEKER A couple of us are going to the cineplex after school to donut that movie with the guy with eighteen kids.
JUNO Sorry, Bleek...
JUNO Going for my ultrasound.
JUNO Gotta note and everything.
BLEEKER Okay, cool.
JUNO I'll try to drop by later.
SPLOOGE!
We see ultrasound goo being squirted onto Juno's exposed pregnant belly.
An ULTRASOUND TECHNICIAN is using a Doppler device to view the contents of her burgeoning bump.
Bren and Leah ooh and ahh at the resulting image.
The tech takes measurements and types them into her database.
ULTRASOUND TECH That's the feet...
ALL THREE Oooh...
ULTRASOUND TECH And there's a hand...
The monitor reveals the baby's head.
ALL THREE Check that out...
ALL THREE No way...
BREN Would you look at that?
LEAH Check out Baby Big-Head.
LEAH That kid is scary!
JUNO Hey, I'm a sacred vessel.
JUNO All you've got in your belly is Taco Bell!
LEAH Touche.
JUNO It is really weird looking.
JUNO It's like it's not even real.
JUNO I can't believe there are saps who actually cry at these things.
Juno and Leah look at BREN, who is dabbing her eyes discreetly.
BREN What?
BREN I'm not made of stone.
ULTRASOUND TECH Well, there we have it.
ULTRASOUND TECH Would you like to know the sex?
LEAH Aw, please Junebug?
JUNO No way.
JUNO No, I definitely don't want to know.
ULTRASOUND TECH Planning to be surprised when you deliver?
JUNO I want Mark and Vanessa to be surprised, and if I know, I won't be able to keep myself from telling them and ruining the whole thing.
ULTRASOUND TECH Are Mark and Vanessa your friends at school?
JUNO No, they're the people who are adopting the baby.
ULTRASOUND TECH Oh.
ULTRASOUND TECH Well, thank goodness for that.
BREN Wait, what's that supposed to mean?
ULTRASOUND TECH I just see a lot of teenage mothers come through here.
ULTRASOUND TECH It's obviously a poisonous environment for a baby to be raised in.
Juno, Leah and Bren become immediately defensive.
JUNO How do you know I'm so poisonous?
JUNO Like, what if the adoptive parents turn out to be evil molesters?
LEAH Or stage parents!
BREN They could be utterly negligent.
BREN Maybe they'll do a far shittier job of raising a kid than my dumbass stepdaughter ever would.
BREN Have you considered that?
ULTRASOUND TECH No...
ULTRASOUND TECH I guess not.
BREN What is your job title, exactly?
ULTRASOUND TECH Excuse me?
BREN I said, what-is-your-job-title, Missy?
ULTRASOUND TECH I'm an ultrasound technician, ma'am.
BREN Well I'm a nail technician, and I think we both ought to stick to what we know.
ULTRASOUND TECH What are you talking about?
BREN You think you're special because you get to play Picture Pages up there?
Bren gestures to the ULTRASOUND MONITOR.
BREN My five year-old daughter could do that, and let me tell you, she is not the brightest bulb in the tanning bed.
BREN So why don't you go back to night school in Manteno and learn a real trade!
The ULTRASOUND TECH exits in a huff.
JUNO Bren, you're a dick!
JUNO I love it.
Juno lays in bed checking out the ULTRASOUND PRINT OUT.
The Previa drives into the front gate of Mark and Vanessa's exclusive community.
A sign on the gate reads "Glacial Valley."
Juno rings the doorbell, shifting her weight in the cold.
MARK answers the door, dressed in a t-shirt and jeans.
MARK Juno?
MARK Wow, I didn't expect to see you here.
JUNO I've got something really cool to show you guys.
JUNO Is Vanessa here?
MARK No, she's working late tonight.
MARK She's trying to accrue some extra time off for when, you know...
He gestures awkwardly to Juno's belly.
JUNO Right.
JUNO I hear they can be kind of a time-suck.
MARK Come on in.
MARK You wanna Ginseng Cooler?
JUNO Sure.
JUNO What is it with you rich people and your herb-infused juices?
MARK I don't know.
MARK Something to do with the four-packs...
MARK ...They're not bad.
Mark leads Juno into the kitchen, where he pours two drinks.
The STEREO blares in the background.
JUNO Why aren't you at work?
MARK I mostly work from home.
MARK I'm a composer.
JUNO No shit.
JUNO Like Johannes Brahms?
MARK No, more commercial stuff.
JUNO Like what?
MARK Commercials.
JUNO Oh.
MARK Have you seen those ads for Titanium Power men's deodorant?
JUNO Titanium Power!
JUNO Get more snatch by the batch!
MARK I wrote that.
JUNO You're kind of a sellout, aren't you?
JUNO What would the Melvins say?
MARK They'd say you came a long way out here not knowing if anyone would be home.
She holds up a manila envelope.
JUNO Come on, you're going to want to sit down for this.
As they move into the living room, Juno sits down and motions for Mark to join her on the couch.
JUNO Park it, dude.
Mark sits down.
With great fanfare, Juno retrieves a dark, glossy sheet from the envelope.
It's her ULTRASOUND.
JUNO Behold, good sir!
JUNO The very first photo of your future child.
MARK You're kidding!
Mark EXAMINES the ultrasound, baffled.
JUNO I think it kind of looks like my friend, Paulie.
MARK Oh, is he bald and amorphous?
JUNO No, he's the dad.
Mark looks jolted, as if it's the first time he considered that her baby might have a father.
He stands up and holds the photo up to the light critically.
MARK Can you tell if it's a boy or a girl?
JUNO The doctor can tell, but I decided not to know.
JUNO I want it to be a big surprise.
MARK Well, it can really only go two ways.
JUNO That's what you think.
JUNO I drink tons of booze so you might get one of those scary neuter-babies that's born without junk.
MARK Junk?
JUNO You know...
JUNO it's parts...
MARK I know what junk is.
JUNO Yeah?
MARK We definitely want it to have junk.
JUNO Well don't worry about it.
JUNO My stepmom is forcing me to eat really healthy.
JUNO She won't even let me stand in front of the microwave or eat red M&Ms.
JUNO Hope you're ready.
Mark chuckles.
MARK Wait...do you hear that?
A new SONG has begun.
Mark closes his eyes in ecstasy and walks toward the stereo.
Juno follows him toward the source of the music, looking perplexed by how happy he is.
JUNO What is it?
MARK It's only my favorite song.
MARK It's Sonic Youth doing "Superstar" by the Carpenters.
JUNO I've heard the Carpenters before.
JUNO Chick drummer and freaky dude.
JUNO Not unlike the White Stripes.
MARK You haven't heard the Carpenters like this.
MARK Listen.
Mark grabs the STEREO REMOTE off the kitchen counter and turns up the volume to a roar.
Mark and Juno stand in silence in the kitchen.
Mark mouths along with the lyrics.
MARK Don't you remember you told me you loved me, baby...
JUNO Hey, I like this.
MARK This album is all Carpenters covers by alt-rock bands.
MARK It's called If I Were a Carpenter.
MARK It is God.
MARK I'll rip a copy for you before you leave.
JUNO You don't have to do that.
MARK It's the least I can do.
MARK What did you say your favorite band was?
JUNO I didn't.
JUNO But it's a three-way tie between the Stooges, Patti Smith and the Runaways.
MARK Yeah, I definitely need to make you some CDs.
MARK At least while my kid is hanging out in there.
He gestures at Juno's burgeoning paunch.
Mark walks over to his music collections and starts pulling CD's.
He's got a Carpenter's disc, the "No Alternative" charity compilation, and Mother Love Bone.
Juno spots a VHS TAPE on the coffee table and picks it up.
JUNO The Wizard of Gore?
MARK Oh yeah.
MARK It's Herschel Gordon Lewis.
MARK He's the ultimate master of horror.
JUNO Please.
JUNO Dario Argento is the ultimate master of horror.
Mark SWIVELS AROUND slowly on his desk chair, surprised.
MARK Argento's good, but Lewis is completely demented.
MARK We're talking buckets of goo.
MARK Red corn syrup everywhere.
MARK And fake brains up the yin-yang.
JUNO Frankly, this looks kind of stupid.
Mark gives a look - "Oh, Really?"
We see some particularly memorable footage from The Wizard of Gore.
Mark and Juno are watching the movie and drinking root beer floats.
They're sitting dangerously close on the sofa.
JUNO This is even better than Suspiria.
JUNO You've got decent taste in slasher movies, Mark.
MARK Here's to dovetailing interests.
He raises his mug in a toast and Juno clinks it awkwardly.
JUNO So, have you and Vanessa thought of a name for the baby yet?
MARK Well, sort of.
MARK Vanessa likes Madison for a girl.
JUNO Madison?
JUNO Isn't that kind of...
JUNO I don't know, gay?
MARK God, pretentious much?
MARK I guess everyone should have a mysterious name like Juno, huh?
JUNO My dad went through this phase where he was obsessed with Greek and Roman mythology.
JUNO He named me after Zeus's wife.
JUNO I mean, Zeus had other lays, but I'm pretty sure Juno was his only wife.
JUNO She was supposed to be really beautiful but really mean.
JUNO Like Diana Ross.
MARK That suits you.
JUNO Uh, thanks.
MARK You know, not many teenage girls in your situation would actually go through with this.
JUNO I weighed my options.
JUNO But after all this, I'm glad I didn't, you know, get rid of it.
JUNO I want to have it.
JUNO For you guys.
MARK You're something else.
A door suddenly slams upstairs.
Vanessa's home.
MARK Vanessa.
MARK Shit, you better get out of here.
JUNO Why?
JUNO What the big deal?
MARK Nothing.
MARK She just hates when I sit around watching movies and 'not contributing.'
JUNO I'll handle this.
JUNO I'm really good at diffusing mom-type rage.
Juno jumps up and rushes out.
MARK Wait...
MARK aww, crap!
Vanessa slides her BRIEFCASE off her shoulder and ventures into the living room.
She's struggling to carry some oversized shopping bags.
VANESSA Mark?
VANESSA Are you home?
VANESSA I want to show you some things I picked up.
Juno intercepts her breathlessly, clutching the ULTRASOUND photo.
Mark trails behind her.
JUNO Hi Vanessa!
Vanessa JUMPS and makes a strangled sound.
VANESSA Juno!
VANESSA God, you startled me.
VANESSA What are you doing here?
VANESSA What's wrong?
JUNO Nothing...
VANESSA Then what's going on?
JUNO I went to the doctor today.
Vanessa is obviously entertaining some worse-case scenarios.
Her eyes are wide and she's uncharacteristically ruffled.
VANESSA Is the baby okay?
JUNO Sure.
JUNO It's the right size and everything.
JUNO I even saw its phalanges today!
JUNO Check this...
She holds the ULTRASOUND up to show Vanessa and drapes her arm around her.
VANESSA What...
JUNO This is the baby.
JUNO Your baby.
Vanessa drops the shopping bags, sick with relief.
VANESSA Oh my God...
JUNO Doesn't it look like it's waving?
JUNO It's kind of like it's saying "Hi, Vanessa.
JUNO Will you be my mommy?"
VANESSA Yeah.
VANESSA Yeah, it kind of does.
MARK Juno was nice enough to bring this by for us.
JUNO I came over as soon as I got that cold ultrasound goo off my pelvis.
JUNO My stepmom verbally abused the ultrasound tech so we were escorted off the premises.
VANESSA Oh, that's great!
She can't divert her gaze from the photo.
JUNO See?
JUNO Nothing to worry about.
Vanessa chuckles tightly, clearly embarrassed by her show of emotion.
Vanessa and Mark walk Juno out.
Juno peers at some shopping bags from various kids stores.
JUNO Hey, what kind of swag did you score?
MARK Yeah.
MARK Mall madness, huh?
VANESSA Oh it's just some stuff I picked up.
VANESSA For, you know, the baby.
VANESSA Babies need a lot of things.
VANESSA I want everything to be just right.
JUNO I thought people got all that stuff at baby showers.
JUNO When my stepmom had my sister I remember she got about a million presents.
JUNO They were all lame though, so I wasn't jealous.
MARK I doubt anyone's throwing us a shower.
JUNO Why?
VANESSA Um, I think people are kind of unsure about the situation because it's not, you know, set in stone.
JUNO What do you mean?
JUNO You mean...
JUNO Do you think I'm going to flake out on you?
VANESSA No, no, I don't think that, Juno.
VANESSA It's just that, we went through a situation before where it didn't work out.
Juno glances at Mark and again at Vanessa.
Vanessa looks embarrassed.
MARK Cold feet.
JUNO You should have gone to China.
JUNO I heard they give away babies like free iPods.
JUNO They shoot 'em out of those T-shirt guns at sports events.
VANESSA Right.
VANESSA Well, Juno, your parents must be wondering where you are.
VANESSA You might want to head home.
JUNO Naah.
JUNO I'm already pregnant, so they figure nothing worse could happen to me.
JUNO I gotta bounce anyway.
JUNO It was nice seeing you guys again.
She waves and heads for the door.
MARK Hey, don't forget your bag.
Vanessa looks pain-stricken as Mark helps Juno with her bag.
Juno kicks the snow off her shoes before she enters.
Bren sits at the kitchen table with a mug of coffee and an issue of Dog Fancy.
Juno enters nonchalantly, drinking a giant slushie.
BREN Where the hell have you been, Junebug?
JUNO I drove to St.
JUNO Cloud to show Mark and Vanessa the ultrasound.
JUNO And I wound up staying for a couple of hours.
BREN A couple of hours?
BREN Why are you going up there in the first place?
JUNO They said they wanted to know about this stuff.
JUNO They said to keep them updated, so I did!
BREN You could have sent it to them.
BREN Why would you drive an hour out to East Jesus, Nowhere?
JUNO I don't know, I just did.
JUNO And while we were waiting for Vanessa, Mark and I watched The Wizard of Gore and he burned me some CDs of weird music.
JUNO He's kind of cool.
A beat as Bren absorbs this.
BREN That was a mistake, Juno.
BREN Mark is a married stranger.
BREN You overstepped a boundary.
JUNO Listen, Bren-duhhh, I think you're the one overstepping boundaries.
JUNO You're acting like you're the one who has to go through this and get huge and push a baby out of your vag for someone else.
JUNO Besides, who cares if he's married?
JUNO I can have friends who are married.
BREN It doesn't work that way, kiddo.
BREN You don't know squat about the dynamics of marriage.
JUNO You don't know anything about me!
BREN I know enough.
Bren rises to leave, clutching the Dog Fancy magazine.
JUNO We don't even have a dog!
BREN Yeah, because you're allergic to their saliva.
BREN I've made a lot of sacrifices for you, Juno.
BREN And in a couple years you're going to move out -- and I'm getting Weimaraners.
JUNO Wow, dream big!
BREN Oh, go fly a kite.
Bren STORMS out.
Juno heads to the URN by the door and defiantly pours the remains of her blue slushie into it.
Juno parks her PREVIA on the street.
She walks up to the house and rings the doorbell.
BLEEKER'S MOM answers, visibly annoyed.
Her eyes drift down to Juno's middle.
JUNO (V.O.) Bleeker's mom was possibly attractive once.
JUNO (V.O.) But now she looks a hobbit.
JUNO (V.O.) The fat one that was in The Goonies.
BLEEKER'S MOM Hi Juno.
BLEEKER'S MOM What can I do for you?
JUNO I borrowed Paulie's physics notes in school today.
JUNO I'm pretty sure he needs them back, or his grade could plummet to an A minus.
BLEEKER'S MOM Fine.
BLEEKER'S MOM Come in.
She steals another glance at Juno's belly.
Bleeker's mom escorts Juno wordlessly up the stairs and down the hallway to Paulie's bedroom.
Juno discreetly tries to charge ahead of her, but her expanding middle prevents her from getting past Bleeker's mom.
They share an extremely awkward moment wedged side-by-side in the narrow hallway.
Bleecker's mom nudges past Juno and knocks on Bleeker's bedroom door.
The door has a cheesy racecar-themed decoration hanging on it that says PAULIE'S VRROOOM!
It looks like something a 5-year old might have.
Paulie is on the floor surrounded by old quizzes, studying like the tortured brainiac he is.
Mrs. Bleeker opens the bedroom door.
Juno appears.
Paulie jumps, startled.
JUNO Hey, don't concentrate so hard, man.
JUNO I think I smell hair burning.
Bleeker smiles faintly.
BLEEKER'S MOM Ten minutes.
She closes the door halfway and leaves.
Juno rolls her eyes and pulls the door shut entirely.
BLEEKER What's up?
JUNO I just wanted to come over.
JUNO You know, say hi.
JUNO I miss hanging out with you on school nights.
BLEEKER I miss it too.
He nervously cracks open a container of ORANGE TIC-TACS and pours them into his mouth.
JUNO (V.O.) Orange Tic-Tacs are Bleeker's one and only vice.
JUNO (V.O.) When we made out, the day I got pregnant, his mouth tasted really tangy and delicious.
Bleeker glances at Juno's midsection, embarrassed.
BLEEKER So, it looks like you're getting pregnant-er these days.
JUNO Yeah.
JUNO Um, I hooked up a whole private adoption thing.
JUNO These married people in Saint Cloud are going to be the parents.
Bleeker is visibly relieved.
BLEEKER Really?
BLEEKER What are they like?
JUNO The guy is super cool!
JUNO His name is Mark and he's into old horror movies and he plays guitar.
JUNO I actually hung out with him today.
BLEEKER Is that normal?
JUNO I asked my dad and Bren not to narc us out to your folks, so we should be safe.
BLEEKER Oh.
BLEEKER That's a relief.
Juno walks over to the bed and sits down next to Bleeker.
JUNO I'm going to really start looking like a dork soon.
JUNO Will you still think I'm cute if I'm huge?
BLEEKER I always think you're cute.
BLEEKER I think you're beautiful.
Juno is caught off guard by his sincerity.
JUNO Jesus, Bleek.
BLEEKER Well, I do.
The song playing ends, and another one begins.
It's "the song," the track that Bleeker and Juno both recognize from the infamous night in the basement.
BLEEKER Hey Junebug, when all this is over we should get the band back together again.
JUNO Yeah.
JUNO Sure.
JUNO Once Tino gets a new drumhead we should be good to go.
BLEEKER We could get back together too.
JUNO Were we together?
Bleeker picks at the carpet, dejected.
BLEEKER Well, we were once.
BLEEKER You know, that time.
JUNO What about Katrina De Voort?
JUNO You could go out with Katrina De Voort.
BLEEKER I don't like Katrina.
JUNO I totally heard you did.
BLEEKER I don't.
BLEEKER Katrina smells like soup.
BLEEKER Her whole house smells of soup.
The house is covered in fresh snow.
Mark and Vanessa stand silently in the nursery.
The walls are primed slate gray.
A single ANTIQUE ROCKING CHAIR sits in the corner.
Vanessa beams proudly and holds two paint samples up near the wall.
VANESSA What do you think?
VANESSA Custard or Cheesecake?
MARK They're yellow.
VANESSA Well, I wanted to pick something gender-neutral for now.
VANESSA Once we get the baby, God willing, we can create a more decisive palette.
MARK Why do people think yellow is gender- neutral?
MARK I don't know one man with a yellow bedroom.
VANESSA I think I'm leaning toward Custard in this light.
VANESSA I don't know.
VANESSA I should paint a small area...
MARK Or you could just wait a couple months.
MARK It's not like the baby's going to storm in here any second and demand dessert-colored walls.
VANESSA What to Expect says that readying the baby's room is an important process for women.
VANESSA It's called "nesting."
MARK Nesting, huh?
MARK Are you planning to build the crib out of twigs and saliva?
VANESSA You should read the book.
VANESSA I even flagged the "daddy chapters" for you.
MARK I just think it's too early to paint.
MARK That's my opinion.
VANESSA And I disagree.
Mark shrugs, resigned.
Vanessa points to the nursery's largest wall.
VANESSA That wall is going to need something.
VANESSA Maybe we could put our first family picture there.
MARK Hm.
VANESSA Can you see it?
Mark stares at the wall, looking lost.
Juno and Leah are walking through the mall, looking bored.
Juno is wearing one of Mac's giant hockey jerseys in lieu of actual maternity wear.
Leah gnaws on a giant cinnamon pretzel.
LEAH Yum.
LEAH This pretzel tastes like a friggin' donut!
JUNO Share the love, Tits!
She wrestles Leah for the pretzel.
Onlookers stare at them, appalled, as Leah puts Juno in a half-Nelson.
JUNO She's assaulting me!
JUNO She's denying me fresh-baked goodness!
Leah claps a hand over Juno's mouth.
JUNO Hly shht!
LEAH What?
Juno drags Leah behind a pillar and peers out from behind it.
They're watching a group of well-heeled women and their children shopping en masse.
One of the women is pushing a toddler in an ultramodern stroller.
And one of the women is VANESSA, looking vaguely detached.
JUNO That's her.
JUNO That's Vanessa Loring.
LEAH Of the Penny Saver Lorings?
Juno nods.
LEAH No way!
LEAH She's pretty.
JUNO You sound shocked or something.
LEAH I just thought she'd look really old in real life.
The women gather near a play area, sip Frapps and loudly discuss their outfits for an upcoming party.
WOMAN #1 And I was like, "No offense, sweetie, but nobody looks good in gauchos."
WOMAN #2 Especially not with her build.
JUNO Wah-wah-waaah!
One of the little girls in the group tugs at Vanessa's sleeve.
Vanessa happily follows the little girl over to their play area and begins to play energetically with her.
Juno watches intently, but Leah just snickers.
LEAH She's gonna steal that kid for her collection.
JUNO Right, seriously.
They watch Vanessa for a few more moments.
The other kids wander over toward the play area while their mothers ignore them.
Vanessa continues to entertain the children.
LEAH Bo-ring!
Leah stands up.
Juno lingers for a moment.
Leah and Juno approach the elevator.
JUNO I want a huge cookie.
JUNO And like, a lamb kebob.
JUNO Simultaneously.
LEAH God, Spermy.
LEAH Must you always feed?
The elevator door opens, revealing...
Vanessa.
VANESSA Juno?
Juno tries her best to look enthused.
JUNO Well hi Vanessa!
JUNO What brings you to the mall today?
VANESSA Just, you know, shopping with my girlfriends.
LEAH You're gay?
Juno glares at Leah.
VANESSA No...
JUNO Please excuse Leah.
JUNO She's mentally challenged.
VANESSA Oh, okay.
VANESSA So...
VANESSA how are you feeling?
JUNO Happy?
JUNO Oh, you mean like, physically.
JUNO I'm good.
JUNO Look, I have a snooze button now!
She lifts her shirt and presses her popped-out NAVEL.
VANESSA That's great.
Vanessa is admiring the belly, when Juno grimaces.
JUNO Dude, it's moshing all over.
Vanessa looks confused.
JUNO It's kicking.
Vanessa nods in understanding then begins summoning the courage for an unusual request.
VANESSA Um...
VANESSA Juno, can I -- Can I touch it?
JUNO Are you kidding?
JUNO Everyone at school is always grabbing at my belly.
JUNO I'm like a legend.
JUNO They call me the Cautionary Whale.
She grabs Vanessa's hand and plants it on her stomach.
VANESSA I can't feel anything.
Vanessa moves her hand, wanting desperately to feel the baby.
VANESSA It's not moving for me.
She says this as though it's an admission of failure.
JUNO Oh, you should try talking to it.
JUNO They can apparently hear speech in there, even though it sounds all ten thousands leagues under the sea.
Vanessa kneels down next to the swell of Juno's belly.
VANESSA Hi.
VANESSA Hi, baby.
VANESSA It's me.
VANESSA My name is Vanessa.
VANESSA I can't wait to meet you.
Leah gives a look to Juno as if she's about to barf.
VANESSA Can you hear me sweet angel?
Vanessa looks like she's giving up hope.
Then suddenly,
VANESSA Oh my God -- It moved!
VANESSA I felt it!
JUNO Elbow.
VANESSA Wow!
VANESSA It's magical.
Juno smiles at Vanessa in awe of her genuine affection.
The streets are covered in muddy, slushy snow.
The mud is instantly TRAMPLED underfoot by the collective feet of the Dancing Elk Track Team on their morning run.
Bren cuts the top three inches off a pair of Juno's jeans.
Then, using a sewing machine, begins attaching an elastic waistband.
We're behind that same WAISTBAND, as Juno walks through the students.
Now, people seem to part the waters for the belly.
Mark has the Les Paul on his lap as he stares at the boards of an awful commercial.
CU - THE SCRIPT (storyboards).
A kitchen scene with a kid eating a new breakfast product called -- BRUNCH BOWLZ.
Annoyed and out of ideas, Mark begins an impromptu song...
Mark drops his head, dejected.
Then, the phone rings.
MARK Hello?
JUNO So, I've been spending a lot of time listening to that weird CD you made me.
Mark instantly smiles.
MARK Oh really?
MARK What's the verdict?
JUNO I sort of like it.
JUNO I mean, it's cute.
MARK Cute?
JUNO Well, when you're used to the raw power of Iggy and the Stooges, everything else sounds kind of precious by comparison.
MARK I imagine you have a collection of punk chestnuts to prove your point.
JUNO Consider it your musical education.
MARK I'm dying to see what you've got to teach me.
JUNO Okay, stop surfing porn and get back to work.
JUNO Just wanted to say hi.
MARK Go learn something.
Mark hangs up.
Smiles.
CU on Juno's tray sliding along, picking up an odd combo of pregnant food.
Pull up to find Juno and Leah walking their trays to a table.
LEAH God, you're getting huge.
LEAH How many months has it been now?
JUNO Almost eight.
JUNO You wouldn't believe how weird I look naked.
LEAH I wish my funbags would get bigger.
JUNO Trust me, you don't.
JUNO I actually have to wear a bra now.
JUNO And I have to rub this nasty cocoa butter stuff all over myself or my skin could get stretched too far and explode.
LEAH Hot!
Juno and Leah are sitting inside an emptied awards case on the wall, eating their lunch.
Juno notices that the other kids in the cafeteria can't help but glance her way.
Some look derisive, others are amused.
JUNO God, why is everyone always staring at me?
LEAH Well, you are kind of...
LEAH convex.
She illustrates by making a rounded gesture near her stomach.
JUNO Wow, someone's been actually doing her geometry homework for once!
LEAH I don't have a choice.
LEAH Keith's been grading me really hard lately.
JUNO Please do not refer to Mr. Conyers as "Keith," okay?
JUNO My barf reflex is already heightened these days.
LEAH Keith's hot.
JUNO Eww, he's all beardy!
We see KEITH the teacher talking to some science kids in the background.
He has a Wild America beard.
He lifts a cup of coffee to his lips and slurps lustily.
LEAH Did you hear Bleek is going to prom with Katrina De Voort?
JUNO Katrina?
JUNO Pfft, no way.
JUNO He doesn't like Katrina.
JUNO It must be a pity date.
LEAH He asked her.
LEAH I heard they were going to Benihana, then the prom, then to Vijay's parents' cabin.
JUNO Bleeker told me Katrina's whole house reeks of soup!
LEAH Oh, it totally does.
LEAH I was there for her birthday about four years ago and it was like Lipton Landing.
LEAH But you know, boys have endured worse things for nookie.
JUNO There's no way in hell they're having sex or even holding hands.
LEAH I wouldn't be so sure about that.
LEAH He did it with you.
LEAH He's a man now.
JUNO Yeah, well, Bleek trusted me.
JUNO We're best friends.
LEAH Are you jealous?
LEAH I thought you said you didn't care what he did.
JUNO I'm not jealous, and I don't care.
JUNO I just know he doesn't like Katrina and I don't think he should toy with her emotions like that.
JUNO She seems so nice and all.
LEAH Okay Juno, I'm really convinced.
JUNO Prom is for wenises, anyway.
JUNO Once you're old enough to go, it's not cool anymore.
Bleeker retrieves a book from his open locker.
Juno marches up to him, belly leading the way.
JUNO Are you honestly and truly going to prom with Katrina De Voort?
BLEEKER Um, hi?
JUNO Leah just told me you were going with her.
BLEEKER Yeah, I did ask her if she wanted to go.
BLEEKER A bunch of us from the team are going to Benihana, then the prom, then Vijay's parents' cabin.
Juno is clearly AFFRONTED.
BLEEKER We're getting a stretch limo.
JUNO Your mom must be really glad you're not taking me.
BLEEKER You're mad.
BLEEKER Why are you mad?
JUNO I'm not mad.
JUNO I'm in a fucking great mood.
JUNO Despite the fact that I'm trapped in a fat suit I can't take off, despite the fact that everyone is making fun of me behind my back, despite the fact that your little girlfriend gave me the stinkeye in art class yesterday...
BLEEKER Katrina's not my girlfriend!
BLEEKER And I doubt she was actually giving you the stinkeye.
BLEEKER She just looks like that all the time.
A GIRL strides past (obviously KATRINA) with a sour look aimed squarely at Juno.
JUNO Whatever.
JUNO Have fun at the prom with Soupy Sales.
JUNO I'm sure I can think of something way more cool to do that night.
JUNO Like I could pumice my feet, or go to Bren's dumb Unitarian church, or get hit by a ten-ton truck full of hot garbage juice.
JUNO All those things would be exponentially cooler than going to the prom with you.
She starts to walk away.
Bleeker takes a deep breath.
BLEEKER You're being really immature.
JUNO What?
Bleeker BRACES himself and pushes up his lab goggles.
JUNO That's not how our thing works!
JUNO I hurl the accusations and you talk me down, remember?
BLEEKER Not this time.
BLEEKER You don't have any reason to be mad at me.
BLEEKER You broke my heart.
BLEEKER I should be royally ticked at you, man.
BLEEKER I should be really cheesed off.
BLEEKER I shouldn't want to talk to you anymore.
JUNO Why?
JUNO Because I got bored and had sex with you one day, and then I didn't, like, marry you?
BLEEKER Like I'd marry you!
BLEEKER You would be the meanest wife of all time.
BLEEKER And anyway, I know you weren't bored that day because there was a lot of stuff on TV.
BLEEKER The Blair Witch Project was on Starz, and you were like, "Oh, I want to watch this, but we should make out instead.
BLEEKER La la la."
JUNO Forget it, Bleek.
JUNO Take Katrina the Douche Packer to the prom.
JUNO I'm sure you guys will have a really bitchin' time!
BLEEKER Yeah, well...
BLEEKER I still have your underwear.
JUNO I still have your virginity!
BLEEKER Oh my God, SHUT UP!
JUNO What?
JUNO Are you ashamed that we did it?
BLEEKER No...
JUNO Well at least you don't have to walk around with the evidence under your sweater.
JUNO I'm a planet!
Juno picks up her BACKPACK dejectedly and slides it over her shoulder.
She's about to walk away, when...
BLEEKER Wait, let me take that.
JUNO Huh?
BLEEKER You shouldn't be carrying that heavy bag.
BLEEKER I'll take it.
JUNO Oh.
JUNO It's fine.
JUNO What's another ten pounds?
She turns around, wipes TEARS off her cheek (making sure no one sees) and continues down the hallway.
Juno climbs ungracefully into the van.
She starts the engine, then pauses to dig through her backpack for something.
She produces a brush and begins brushing her hair in the rearview mirror, examining herself self-consciously.
She puts on some Dr. Pepper Lip Smacker and backs out of the driveway.
Mark is seated at the computer, surfing a horror movie website.
He has the blank expression of a bored obsessive.
The doorbell rings.
Mark opens the door.
Juno stands there, looking radiantly knocked-up.
She holds a stack of CDs.
Mark breaks into a grin.
MARK Wow.
MARK That shirt is working hard.
JUNO Is Vanessa here?
MARK Nope.
MARK We're safe.
He and Juno smile conspiratorially.
JUNO Cool.
MARK Come on, I have something for you.
He gestures for Juno to follow him into the house.
The Lorings' basement is dank, cluttered unfinished and unattractive, much like Paulie Bleeker's.
Mark pulls a chain to illuminate a bare bulb.
JUNO Oh, Mark!
JUNO Is this the baby's room?
JUNO It's beautiful!
MARK Hilarious.
MARK No, I just keep all of my old comics down here, and I want to show you one of them.
JUNO Oh God, you're one of those guys...
MARK You're gonna like this, I promise.
Mark RUMMAGES through a cardboard box in the corner.
MARK Here it is.
He shows the COMIC to Juno.
It's called "Most Fruitful Yuki."
It depicts a pregnant JAPANESE GIRL kicking ass and taking names.
JUNO "Most Fruitful Yuki"?
JUNO What is...
JUNO Oh my god, she's a pregnant superhero!
MARK Isn't that great?
MARK I got it when I was in Japan with my band.
MARK She reminds me of you.
Juno examines the comic.
"Most Fruitful Yuki" does resemble her.
JUNO Wow, I actually feel like less of a fat dork now.
MARK Most Fruitful Yuki is bad ass, man.
MARK You should be proud to be the same condition.
She throws a KARATE KICK in Mark's direction with a KEE-YA!
Juno is sincerely pleased.
JUNO Okay, how about some tunes?
There's a battered portable CD player in the corner.
Juno kneels down and pops in one of the discs.
JUNO Now this first one is kinda slow.
JUNO But it's Mott the Hoople so it's still totally rad and hardcore.
Juno puts in the CD and "All The Young Dudes" fills the room.
Mark Laughs.
JUNO What?
MARK I actually know this one.
JUNO You do?
MARK Yeah, this song's older than me, if you can believe that.
MARK I danced to it at my senior prom.
JUNO That's almost interesting, Mark.
JUNO Who did you dance with?
MARK Her name was Cynthia Vogel and she was a good dance partner.
MARK Even let me put my hands on her butt.
JUNO Oh man, I can just picture you slow dancing like a dork!
She mockingly places her hands on Mark's waist and moves back and forth stiffly.
MARK No, I put my hands on your waist.
MARK Then you put your arms around my neck.
MARK That's how we did it in '88.
Mark puts his hands on what remains of Juno's waist.
She drapes her arms around his neck self-consciously.
JUNO Oh, okay.
JUNO Like this.
MARK You've never been to a dance, have you?
JUNO Only squares and nerds go to dances.
MARK What are you?
JUNO I don't know.
They SWAY slowly to the music.
Juno's belly bumps up against Mark.
MARK I feel like there's something between us.
They laugh.
Juno rests her head on Mark's chest.
They dance in silence for a few moments, then stop moving.
Mark pulls Juno as close as he possibly can, given her expanding girth.
MARK I'm leaving Vanessa.
JUNO What?
MARK It's just not working out, but I'm getting my own place in the city...
MARK and I've got it all planned out.
MARK It's something I've wanted to do for a long time...
Juno backs away.
JUNO No.
MARK No?
JUNO No.
JUNO No, you definitely cannot do that, Mark.
JUNO That's a big, fat sack of no!
MARK What's the matter?
JUNO This isn't what we agreed on.
JUNO You guys have to take care of...
JUNO this!
JUNO You are the chosen custodians of the big-ass bump!
She GESTURES wildly to her belly.
Suddenly, something matters to her far more than the approval of an older guy.
MARK But I thought you'd be cool if...
JUNO I want you guys to adopt the Buglet.
JUNO I wanted everything to be perfect.
JUNO Not shitty and broken like everyone else's family.
JUNO Listen, once I have the baby, Vanessa is going to finally be happy, and everything will be all right.
JUNO Believe me on this one!
MARK A baby is not going to fix everything.
MARK Besides, I don't know if I'm ready to be a father.
JUNO But you're old!
MARK I...
MARK How do you think of me, Juno?
MARK Why are you here?
JUNO I don't know.
JUNO I just liked being your friend.
JUNO I sort of liked becoming furniture in your weird life.
MARK This...
MARK ...this is what my life has become.
MARK Stuff in boxes.
MARK Stuff underground.
MARK Is that so appealing to you?
JUNO Yeah, I guess...
JUNO Is this my fault?
JUNO Is Vanessa mad at you because of me?
MARK That's not the point.
MARK We're just not in love anymore.
JUNO Yeah, but didn't you love Vanessa when you married her?
JUNO If you love someone once, you can love them again, I know it.
JUNO My friend Leah has gone out with the same guy, like, four times.
JUNO You're just not trying.
Mark suddenly sees Juno for what she is -- a teenage girl.
MARK I'm such an idiot.
MARK I can't believe what an idiot I am.
He paces over to the wall and KICKS it softly.
JUNO Please don't get a divorce!
JUNO God, Mark, just do me a solid and stay with your wife.
MARK God, you're so young.
JUNO Not really.
JUNO I'm sixteen.
JUNO I'm old enough to tell when people are acting like total a-holes!
Juno turns to leave, then shoots one furious look back at Mark.
JUNO Oh and by the way, I bought another Sonic Youth album and it's the worst thing I've ever heard!
JUNO It's just noise, man!
She bolts up the stairs, sobbing.
Juno reaches the top of the stairs and scrambles toward the front door, only to be intercepted by Vanessa, who's returning home from work, carrying her briefcase and a freshly purchased NURSING PILLOW.
They nearly collide.
VANESSA Juno?
VANESSA What's going on?
JUNO Nothing.
It's obvious from Juno's tears and flushed face that she's lying.
Vanessa instantly goes pale with fear, but she tries her hardest to seem serene and "together" in front of Juno.
VANESSA Mark?
VANESSA Why is Juno crying?
JUNO I'm not crying.
JUNO I'm allergic to fine home furnishings.
JUNO See you later.
She rushes toward the door.
VANESSA Hold on.
Juno halts.
VANESSA Juno, what's the matter?
MARK She's hormonal.
MARK Right, June?
MARK It's just part of the whole process.
Juno looks totally betrayed.
She doesn't respond.
Vanessa looks at Juno's expression and knows Mark is lying.
VANESSA What did you do?
MARK I didn't do anything...
MARK I just...
MARK I've just been thinking.
VANESSA What?
MARK Just thinking if this is really the right thing for us.
VANESSA What are you referring to?
She knows exactly to what he's referring.
MARK I've been just wondering if we're, you know, ready.
VANESSA Of course we're ready.
VANESSA We've taken all the classes.
VANESSA The nursery.
VANESSA The books --
MARK I know we're prepared.
MARK I just don't know if...
MARK I'm ready.
Juno's face continues to fall.
Vanessa notices.
VANESSA Juno, don't worry about this.
VANESSA He just has cold feet.
VANESSA That's how boys are.
VANESSA The books all say the same thing.
VANESSA A woman becomes a mother when she gets pregnant.
VANESSA A man becomes a father when he sees his baby.
VANESSA He's going to get there.
VANESSA He'll get there.
Juno ain't buying it.
VANESSA Why don't we let Juno go home and we can discuss this later on, okay?
MARK It all just happened so fast.
MARK We put that ad in the paper.
MARK I thought it would take months if, you know, ever and then -- boom -- Two weeks later, she's in our living room.
VANESSA She answered our prayers.
MARK Ever since, it's just been like a ticking clock.
This stops Vanessa.
Juno looks offended.
VANESSA What are you saying?
A long hideous beat.
MARK It just feels a little like bad timing.
Another hideous beat.
VANESSA What would be a good time for you?
MARK I don't know.
MARK There's just things I still want to do.
VANESSA Like what?
VANESSA Be a rock star?
MARK Don't mock me.
Vanessa sighs.
It's done.
VANESSA You're trying to do something that's never going to happen.
VANESSA And you know what?
VANESSA Your shirt is stupid.
VANESSA Grow up.
VANESSA If I have to wait for you to become Kurt Cobain, I'm never going to be a mother.
Vanessa looks defeated.
MARK I never said I'd be a great father.
We hear the front door closing.
Vanessa and Mark look over and notice that Juno has escaped the conflict.
Juno runs up to her car sobbing.
She struggles with the keys, but finally makes it into the Previa and drives off.
The Previa slides off the road and comes to a stop on the shoulder.
Juno buckles over the steering wheel, crying, unwinding for the first time since she became pregnant.
After a beat, she begins to gather herself.
Bleeker is sitting next to his bed, noodling on the guitar.
He's playing a theme that we will soon recognise.
Juno lays on the hood of her Previa, contemplating her future.
We push in close...
when she gets an idea.
She hops off the hood and scurries into the Previa where she finds a crumpled up Jiffy Lube receipt.
She unfolds it and pulls out a pen, ready to write something...
a note?
It's quiet after the storm.
Inside, we see Vanessa sitting alone at her perfect dining room table, drinking a glass of wine.
Vanessa takes a sip and continues to let the days events sink in.
After a beat, Mark comes down the stairs to join her.
MARK I called Gerta Rauss.
MARK She says she can represent both of us.
MARK They call it "collaborative divorce."
MARK It's apparently all the rage right now.
MARK And it's easy because we don't have children.
VANESSA No, it's fine.
VANESSA Thanks for making the call, I guess.
Mark nods and sits down.
VANESSA We're actually, finally doing this?
MARK Looks like it, yeah.
VANESSA Have you found a place to stay?
MARK Yeah, downtown.
VANESSA A hotel?
MARK It's a loft.
VANESSA Aren't you the cool guy?
They STARE at the wall, speechless and defeated.
VANESSA I wanted a baby so bad.
VANESSA So bad.
She buries her head in her hands.
MARK I know you did.
There's a LOUD KNOCK on the front door.
Mark opens the door.
There's a folded piece of paper sitting on the doormat.
He squints and sees Juno pulling away in the van.
Mark carefully unfolds the piece of paper -- it takes a minute because of Juno's proficiency in "teen girl origami."
He holds it up.
We can see there's WRITING on the back.
MARK It looks like a bill from Jiffy-Lube.
Vanessa takes the note from his hand and turns it over, examining it.
VANESSA It's for me.
Juno parks her car and walks up to her house.
A porch light's been left on for her, and the place looks cozy and inviting.
JUNO (V.O.) I never realize how much I like being home unless I've been somewhere really different for a while.
She picks a CROCUS from the unkempt garden near the porch and sniffs it.
She lifts her shirt and tickles her belly with it.
Then she tucks the flower into her unkempt hair.
Mac is alone at the kitchen table going over the family finances while drinking one of Bren's weight loss shakes.
Juno enters.
JUNO Hi Dad.
MAC Hey, big puffy version of Junebug.
MAC Where have you been?
JUNO Dealing with stuff way beyond my maturity level.
JUNO Where is everyone?
MAC Bren took Liberty Bell to her tot ice skating class.
JUNO Tot ice skating?
JUNO Tots can't ice skate.
JUNO Liberty Bell's still getting the hang of stairs.
MAC No, but you know Bren.
MAC She dreams big.
JUNO Yeah, she does.
MAC You look a little morose, honey.
MAC What's eating you?
JUNO I'm losing my faith in humanity.
MAC Think you can narrow it down for me.
JUNO I guess I wonder sometimes if people ever stay together for good.
MAC You mean like couples?
JUNO Yeah, like people in love.
MAC Are you having boy trouble?
MAC I gotta be honest; I don't much approve of you dating in your condition, 'cause...
MAC well, that's kind of messed up.
JUNO Dad, no!
MAC Well, it's kind of skanky.
MAC Isn't that what you girls call it?
MAC Skanky?
MAC Skeevy?
JUNO Please stop now.
MAC Tore up from the floor up?
JUNO Dad, it's not about that.
JUNO I just need to know that it's possible for two people to stay happy together forever.
JUNO Or at least for a few years.
MAC It's not easy, that's for sure.
MAC Now, I may not have the best track record in the world, but I have been with your stepmother for ten years now, and I'm proud to say that we're very happy.
Juno nods in agreement.
MAC In my opinion, the best thing you can do is to find a person who loves you for exactly what you are.
MAC Good mood, bad mood, ugly, pretty, handsome, what have you, the right person will still think that the sun shines out your ass.
MAC That's the kind of person that's worth sticking with.
A wave of REALIZATION crosses Juno's face.
JUNO I sort of already have.
MAC Well, of course.
MAC Your old D-A-D!
MAC You know I'll always be there to love and support you, no matter what kind of pickle you're in.
He nods toward her belly.
MAC Obviously.
Juno laughs and hugs her father, planting a smooch on his cheek.
JUNO I need to go out somewhere for just a little while.
JUNO I don't have any homework, and I swear I'll be back by ten.
She salutes and dashes out of the kitchen.
MAC You were talking about me, right?
We push in over Bleeker sleeping in his car-bed towards the window.
We look out onto the lawn to find Juno and Leah running back to the Previa, hopping in, and screeching off.
Bleeker steps out of the house for his usual early-morning run.
He looks down to see a message scrawled in chalk on the stoop: "BLEEKER -- CHECK THE MAIL."
He walks down to the end of the driveway and opens the latch on the mailbox.
At least one hundred containers of ORANGE TIC TACS come pouring out in an colorful deluge.
They spill out onto the driveway.
Bleeker smiles.
Juno waddles toward the field.
The guys on the track team, ridiculously arrayed as usual, are doing hurdler stretches.
They stare at her quizzically.
Bleeker spots Juno approaching and jogs up to the chainlink fence.
BLEEKER Did you put like a hundred things of Tic Tacs in my mailbox?
JUNO Yeah.
JUNO That was me.
BLEEKER Why?
JUNO Because they're your fave.
JUNO And you can never have too much of your favorite one-calorie breath mint.
BLEEKER Well...
BLEEKER thanks.
BLEEKER I think I'm pretty much set until college on the Tic Tac front.
JUNO You know, I've been thinking.
JUNO I'm really sorry I was such a huge bitch to you.
JUNO You didn't deserve that.
JUNO You never deserve any of the poo I unload on you.
BLEEKER You know it's okay.
JUNO Also, I think I'm in love with you.
BLEEKER What, you mean as friends?
JUNO No, for real.
JUNO I think you are the coolest person I've ever met.
JUNO And you don't even have to try.
BLEEKER I try really hard, actually...
JUNO No, you're naturally smart.
JUNO You always think of the funniest things to do.
JUNO Remember when you passed me that postcard during Spanish class, and it was addressed like, "Junebug MacGuff, Row 4, Third Seat From the Blackboard"?
JUNO And it said, "I'm having fun in Barcelona -- wish you were here"?
JUNO That was hilarious.
BLEEKER I was just bored.
BLEEKER I only think school is awesome like, 80% of the time.
JUNO Plus, you're the only person who doesn't stare at my stomach all the fucking time.
JUNO You actually look at my face.
JUNO And every time I look at you, the baby starts kicking me super hard.
BLEEKER It does?
Juno presses Bleeker's hand against her belly.
BLEEKER Wizard!
JUNO I think it's because my heart starts pounding when I see you.
BLEEKER Mine too.
JUNO Basically, I'm completely smitten with you, and I don't care if I'm making an ass out of myself right now, because you've seen me make an ass out of myself a million times, and you still want to be my friend.
BLEEKER Well, yeah.
BLEEKER You're the best friend I've ever had, even when you're being kind of evil.
JUNO That's all I need from you.
JUNO That's more than I could ever ask for.
JUNO You're just golden, dude.
BLEEKER Can we make out now?
JUNO Okay.
Bleeker and Juno KISS, oblivious to the gawking track team guys in the background.
In the distance, near the school entrance, we see STEVE RENDAZO (the kid who always TORMENTS Juno) regarding the makeout session with a sad, envious expression.
LEAH passes by, does a double take, then hurries up to the fence, rolling her eyes.
LEAH You know, you can go into early labor sucking face like that!
Juno gives her the FINGER, not breaking the clinch with Bleeker.
Juno is lying on her back on the bed, staring at the ceiling.
She's more pregnant than we've ever seen her.
She revs a Matchbox car against the slope of her belly and lets it roll.
Juno suddenly sits up, looking thoroughly freaked.
She pats her lap frantically and jumps off the bed.
JUNO Dad!
Mac looks up from the lure he's working on.
MAC What?!
JUNO Either I just pissed my pants or...
MAC Or...
JUNO Thundercats are go!
Mac, Bren and Liberty Bell rush out of the house.
They pile into the Previa at breakneck speed.
Juno waddles behind them, protesting.
CU of Juno wearing a puffy surgical cap.
She's being pushed down the hospital corridor in a wheelchair.
She bursts into giggles.
Pull back to reveal her that Leah is pushing her rather aggressively.
Leah jokingly steers the wheelchair into a wall.
Juno feigns whiplash.
Bren appears behind them and orders Juno out of the wheelchair, exasperated.
She pulls off Juno's surgical cap.
Leah and Juno snicker.
We see Juno is in a BIRTHING SUITE at the hospital, pacing impatiently, bent over in obvious discomfort.
She's wearing her Chuck Taylors and knee socks with her hospital gown.
Leah and Bren stand nearby.
Juno doubles over in pain.
JUNO Ow, ow, fuckity-ow.
JUNO Bren, when do I get that Spinal Tap thing?
BREN It's called a spinal block, and you can't have it yet, honey.
BREN The doctor said you're not dilated enough.
JUNO You mean I have to wait for it to get even worse?
JUNO Why can't they just give it to me now?
BREN Well, honey, doctors are sadists who like to play God and watch lesser people scream.
Juno lets out a genuine shriek of pain.
BREN Shit.
BREN Hey, can we give my kid the damn spinal tap already?
JUNO (V.O.) It really didn't hurt that bad having him.
We see Juno in the process of delivery, from her POV.
Leah holds one of Juno's feet and Bren holds the other.
JUNO (V.O.) The best part was when I peed on Leah during labor.
We see Leah holding Juno's FOOT, which is shaking.
Leah's shirt is soaked.
She rolls her eyes and mouths "Fuck you" at Juno.
Juno's raised MIDDLE FINGER enters the frame.
JUNO (V.O.) And then, out of nowhere, there it was...
The doctor reveals JUNO'S BABY BOY above the sheet.
JUNO (V.O.) There he was.
Juno looks at the baby in awe, then her eyes begin to flutter...
and she passes out.
Paulie Bleeker is running as fast as his legs can carry him on the Dancing Elk track.
There's a very sparse crowd in the bleachers.
As Paulie approaches the tape, his envious teammate Vijay looks on.
Bleeker's mom is seated near Vijay, holding a video camera.
JUNO (V.O.) I decided to not call Bleeker to tell him that I was having the baby.
JUNO (V.O.) He had a big meet against Manteno and I didn't want him to get all worried about me and choke.
Paulie breaks the tape, winning the race.
The fifteen or so people in attendance cheer.
VIJAY His legs are as swift as his seed.
MRS. BLEEKER What did you say?
Bleeker pants at the finish line, dripping with sweat.
ANNOUNCER P.
ANNOUNCER Bleeker has just broken a district record in the 400.
Bleeker looks out at the BLEACHERS, scanning them for Juno.
She's not there.
JUNO (V.O.) But he figured it out anyway.
Bleek takes off RUNNING toward the parking lot without stopping to explain.
His mother stands up, confused.
A NURSE reaches into one of the maternity ward bassinets and gently lifts up a swaddled newborn baby.
The nurse turns and addresses an unseen spectator.
NURSE Would you like to meet your son?
Pull back to reveal she's speaking to VANESSA, who stands, paralyzed, several feet away.
VANESSA I have a son?
NURSE You are the adoptive mother?
VANESSA I have a son.
NURSE Healthy kid, too.
NURSE Didn't waste any time getting out.
Vanessa reaches out for the baby and gingerly accepts him in her eyes.
She spends a few moments just looking at him.
She feels someone watching her, then looks up to see a Bren leaning against the doorway.
Vanessa blinks away her tears self-consciously.
VANESSA How do I look?
BREN Like a mom.
BREN Scared shitless.
Vanessa laughs.
Juno is curled up on her bed in the birthing room.
The birth is obviously over; there's that air of stillness and accomplishment, a task completed.
The doctors have cleared out.
Mac sits in a chair next to the bed, looking like he's not sure what to say.
He holds up a deck of Playing cards as if to initiate a game, but Juno gently pushes his hand away.
Their eyes meet.
His expression is helpless, hers is utterly drained.
MAC Someday, you'll be back here, honey.
MAC On your terms.
Juno nods and swallows.
Over Mac's shoulder, a silhouette appears in the doorway.
It's Bleeker in his track uniform.
Juno sees him and bursts into sudden, ragged sobs.
Mac glances at her, alarmed.
Paulie moves toward the bed.
Mac clears his throat, gets up and leaves the room.
Paulie climbs onto the hospital bed and carefully puts his arm around Juno.
She leans into him, letting herself go for the first time in months.
Juno lies on the bed.
She looks rested and relaxed compared to her earlier crying jag, but her face is still pink and swollen.
Bleeker is curled up next to her, still in his track uniform and spikes.
JUNO (V.O.) Bleeker decided he didn't want to see the baby.
JUNO (V.O.) Neither did I, really.
JUNO (V.O.) He didn't feel like ours.
We see Vanessa leaning over the bassinet, unable to take her eyes off the baby, touching it's hair reverently.
JUNO (V.O.) I think he was always hers.
The nursery is perfectly decorated in Vanessa's immaculate taste.
Nothing looks as though it's been touched.
We see the antique ROCKING CHAIR sitting empty.
JUNO (V.O.) It ended with a chair.
We pan past the wall Vanessa had said "needed something."
There's a framed note on the wall.
It looks like it was handwritten on the back of a Jiffy Lube bill.
We see that it says: "Vanessa -- If you're still in, I'm still in.
Juno."
We move to the door and get a view of Vanessa's bedroom.
We see her lying in bed with a burp cloth draped over her shoulder, feeding the baby.
For the first time ever, Vanessa looks disorganized, unshowered -- and incredibly happy.
There are formula bottles on the bedside table and a bassinet pushed close to the bed.
Obviously, she hasn't been away from the baby for a single moment.
The baby reaches up and grabs Vanessa's thumb.
Vanessa glows with an expression of pure bliss.
It's a sparkling summer afternoon.
Juno wheels her bicycle out of the detached garage.
She waves goodbye to Bren, who is playing in the yard with two WEIMARANERS.
She looks almost as happy with her dogs as VANESSA looked with her baby.
Juno rides her bike aggressively down the street.
Her guitar is slung over her shoulder in a gig bag.
She's obviously not pregnant anymore.
She looks happy, but older.
JUNO (V.O.) As boyfriends go, Paulie Bleeker is totally boss.
JUNO (V.O.) He is the cheese to my macaroni.
JUNO (V.O.) I know people are supposed to fall in love before they reproduce, but normalcy's not really our style.
As she tears recklessly down the street on her bikes, she passes the Dancing Elk TRACK TEAM, still running in outrageously skimpy shorts and bandanas.
Juno RIDES up to a garage where Bleeker is sitting, tuning his guitar.
Juno bikes up to find Bleeker sitting on the stoop.
She smiles and takes out her guitar.
She sits across from Bleeker and pulls the pick out of the strings.
JUNO Ready?
Bleeker nods.
Juno begins strumming her guitar and playing "Anyone Else But You," by the Moldy Peaches.
Bleeker joins in.
At first their playing is discordant, but suddenly it works.
BLEEKER You're a part time lover and a fulltime friend.
BLEEKER The monkey on your back is the latest trend.
BLEEKER I don't see what anyone can see, in anyone else but you.
JUNO Here is the church and here is the steeple.
JUNO We sure are cute for two ugly people.
JUNO I don't see what anyone can see, in anyone else but you.
BLEEKER We both have shiny happy fits of rage.
BLEEKER You want more fans, I want more stage.
BLEEKER I don't see what anyone can see, in anyone else but you.
JUNO You are always trying to keep it real.
JUNO I'm in love with how you feel.
JUNO I don't see what anyone can see, in anyone else but you.
BLEEKER I kiss you on the brain in the shadow of a train.
BLEEKER I kiss you all starryeyed, my body's swinging from side to side.
BLEEKER I don't see what anyone can see, in anyone else but you.
JUNO The pebbles forgive me, the trees forgive me.
JUNO So why can't you forgive me?
JUNO I don't see what anyone can see, in anyone else but you.
JUNO AND BLEEKER TOGETHER Du du du du du du dudu.
JUNO AND BLEEKER TOGETHER Du du du du du du dudu.
JUNO AND BLEEKER TOGETHER I don't see what anyone can see, in anyone else but you.
She and Bleeker exchange glances as they play.
They smile ambiguously.
Juno leans over and kisses Bleeker on the cheek.
Pull out to reveal the surrounding green suburb buzzing with life and summer activity.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
