AMERICAN GANGSTER
Written by
Steven Zaillian
FINAL SHOOTING SCRIPT July 27, 2006
A tall, handsome man in a dark suit emerges from a Lincoln Towncar and enters a small, basement R&B/Jazz club.
He approaches a booth, says something in the din to the men there, then calmly shoots them and exits.
Bumpy Johnson, an elderly but still sturdy black man, elegantly dressed - cashmere overcoat, gloves, Homburg - stands in falling snow atop a flatbed truck - as he does every Thanksgiving - tossing down turkeys to the poor - like a benign king.
Legend: Harlem
A younger man, the gunman from the club - Frank Lucas - Bumpy's driver/bodyguard/collector/protege - watches from below.
Whispering gunfire from a television set veiled by foreground snow: Soldiers in the jungles of Vietnam in 1970.
A rich, cultured, authoritative voice offers:
BUMPY O/S This is the problem.
BUMPY O/S This is what's wrong with America.
The war footage multiplies by twenty: a stack of TVs with price tags dangling from the knobs behind a display window.
BUMPY O/S It's gotten so big you can't find your way.
People on the sidewalk, out of respect or fear, part to let Frank and Bumpy and Bumpy's German shepherd pass.
BUMPY The corner grocery's a supermarket.
BUMPY Candy store's a MacDonald's.
BUMPY And this place.
BUMPY (CONT'D) Where's the pride of ownership here?
BUMPY (CONT'D) Where's the personal service?
BUMPY (CONT'D) Does anybody work here?
Inside, the emporium is vast, with aisles that seem to stretch off into infinity.
The TVs give way to a display window full of Japanese stereo componentry.
BUMPY What right do they have cutting out the suppliers, pushing all the middlemen out, buying direct from the manufacturer - Sony this, Toshiba that, all them Chinks - putting Americans out of work?
He's not really asking Frank, so Frank doesn't answer.
BUMPY What am I supposed to do with a place like this, Frank?
BUMPY Who am I supposed to ask for, the assistant manager?
BUMPY This is the problem.
BUMPY This is the way it is now: You can't find the heart of anything to stick the knife.
Bumpy stops before a display of cameras and stares in.
They're all pointed at him as a pain grips his chest and he sinks to his knees.
Frank kneels down.
FRANK What is it?
Bumpy seems unable to speak, looks to Frank confused.
FRANK Somebody call an ambulance!
But the store suddenly seems empty.
Frank yells into the emporium but can't be heard above the Muzak and the cash registers ringing up sales Bumpy will never see a piece of.
Looking up at Frank, Bumpy manages weakly -
BUMPY Forget it, Frank.
BUMPY No one's in charge.
Limousines from the funeral disgorge mourners: family, friends, celebrities, politicians.
Cops on horseback move through the enormous crowd that has gathered to watch.
FBI agents in cars snap pictures with long lenses of Italian mobsters like Albert Tosca.
REPORTER - whose passing has brought together a who's who of mourners on this chilly afternoon.
REPORTER The Governor has come down.
REPORTER The mayor of New York - its Chief of Police and Commissioner - sports and entertainment luminaries -
A white Bentley pulls up, disgorging Jackie Fox - the original Superfly - and his entourage.
With his trademark tinted Gucci glasses on, he happily poses for anyone with a camera - including the Feds - before going inside.
The report continues on a TV no one's really watching here: a March of Time-like history of Bumpy Johnson, famed Harlem gangster, Robin Hood and killer.
REPORTER ON TV He was a Great Man, according to the eulogies.
REPORTER ON TV A giving man.
REPORTER ON TV A man of the people.
REPORTER ON TV No one chose to include in their remembrances the word most often
associated with Ellsworth Bumpy Johnson: Gangster.
Sitting off by himself in Bumpy's elegant garden apartment, heretofore his private sanctuary, Frank surveys the mourners circling the place like vultures:
Tango Black, a huge brute, scavenging the catered food and tended bar ...
Jackie Fox, surrounded by his ever-present coterie of sycophants ...
Albert Tosca, an elegant Italian capo, and an underling, Rossi, at the bar.
TOSCA White wine, please.
A white man who looks like a banker - and is - sits down next to Frank.
BANKER How you doing, Frank?
FRANK All right.
BANKER What a loss.
BANKER How are you otherwise?
BANKER Things okay financially?
Frank doesn't say.
It feels unseemly to him to be talking about money here.
He watches Tango carelessly set a watery glass of ice on an antique inlaid chess table.
BANKER Bumpy set something up for you?
Frank excuses himself without an answer, crosses to where Tango left the glass, and sets it on a coaster.
TANGO Hey, Frank, get me an ashtray while you're at it.
Bumpy's German shepherd watches as Frank reaches into his jacket, revealing a gun nestled in its shoulder holster.
He takes out a handkerchief, wipes the condensation dry, opens a drawer and removes an ashtray.
He holds it out to Tango - who isn't sure it's not a dare and decides to wander off.
CHARLIE I know you're hurting, Frank.
CHARLIE So am I.
Frank sits back down with Charlie Williams, an older dope man.
CHARLIE You going to be all right?
FRANK Yeah.
CHARLIE I'm sure Bumpy never told you, but he made me promise, anything ever happened to him, I'd make sure you didn't go without.
FRANK I'll be fine, Charlie.
FRANK Half the people here owed Bumpy money when he died.
FRANK A lot of money.
FRANK If they think I'm going to forget to collect, they're wrong.
CHARLIE That's the spirit.
CHARLIE Go get them.
On the TV, over archive film and photographs of crime figures from the 1940's and `50's, the opinion is offered that Bumpy's death "marks the end of an era ..."
A figure, his back to us, walks slowly toward a blackboard like a man to the gallows.
RICHIE V.O. I live in fear of hearing my name called.
PROFESSOR Mr. Roberts, Give us U.S. vs.
PROFESSOR Meade -
RICHIE V.O. Of walking up there, turning around, knowing every one of them knows more than I do -
PROFESSOR Subject, issues, what the determination was and what it means to us today.
Richie Roberts turns and faces his classmates, all of them a decade or more younger than him.
Harlem's jagged teeth skyline juts across the river at the other end of the George Washington Bridge.
On this side - a sledgehammer gripped in Richie's fist, on the move, suddenly fills the frame.
RICHIE You know the Number 1 fear of most people isn't dying; it's public speaking.
RICHIE They get physically ill.
RICHIE They throw up.
RIVERA And that's what you want to do for a living.
RICHIE I don't like being like that.
RICHIE I want to beat it.
Armed with the sledgehammer, Richie and his partner - Javy Rivera - come past a seedy motel office where a TV shows another report about Bumpy Johnson.
Legend: New Jersey
A motel clerk looks up, glimpses the sledgehammer -
CLERK Hey -
Rivera flashes a New Jersey detective's shield without breaking stride.
Takes a subpoena out of another pocket.
RIVERA Who's going to do this?
RICHIE He knows me, he'll take it from me.
RICHIE I've known him since high school.
RIVERA Just throw it in, he doesn't take it.
RIVERA That's good service.
They reach a particular motel room door.
Rivera knocks.
The door opens the length of a chain, revealing a wise guy in an undershirt, who, when he sees the subpoena, start to close the door -
RIVERA Throw it -
As Richie flings the subpoena in, the door slams on his hand.
He wails in agony, tries to shoulder it open, hears the dead bolt lock on the other side, feels Campizi's teeth bite into his fingers, watches his blood run down the frame.
RIVERA Down -
Richie hangs down from his hand as the sledgehammer swings past his head shattering the door -
The door rips from its hinges and the detectives crash in.
The wise guy - Campizi - hurries for the bathroom, slams the door.
This one's hollow and the detectives more easily break through it -
Campizi tries to climb out the bathroom window.
Richie grabs him, throws him into the shower stall, taking the plastic curtain down with them, smearing it with blood as Richie beats at him before Rivera can pull him off.
A male paramedic attends to Campizi's bloodied face while a female paramedic cleans Richie's bloodied hand.
CAMPIZI I swear to God, Richie, I didn't know it was you.
CAMPIZI I would never slam a door on your hand.
CAMPIZI Knowingly.
RICHIE You bit my fuckin hand -
Richie lunges at him, hits him again with his injured hand - which hurts Richie more than it does Campizi.
The paramedics manage to pull him away.
CAMPIZI What can we do, Richie?
CAMPIZI You don't want to do this.
CAMPIZI For old times sake, what can we do?
CAMPIZI Who do you want?
CAMPIZI Who can I give you?
CAMPIZI You want Big Sal's bookie?
CAMPIZI You want his accountant?
CAMPIZI I'll give him to you.
Richie regards him a moment.
A policy ring's accountant wouldn't be bad.
He glances back to his paramedic dabbing at his bloody hand, and notices she's not bad-looking.
She smiles back.
Four men in long black leather coats stride toward like they own the city.
It's impossible to tell if they're cops or gangsters.
Legend: New York City
One of the same undercover cops - Detective Trupo - scribbles a signature and badge number different from the one on his gold shield lying next to the voucher requesting evidence needed in court.
He pushes the voucher under a sign - "All Handguns and Narcotics Before 10am Next Window" - to a clerk who takes it past floor-to-ceiling shelves covered with files, plastic bags bulging with handguns, knives and gambling receipts.
Bulkier items - like shotguns and baseball bats - lie unwrapped with dangling tags.
The clerk reaches a chain-link cage where the most valuable items are locked up - narcotics, pornography, cash - checks the voucher against tags, takes down an old green suitcase.
Trupo's car - a Shelby Mustang - roars up.
He climbs out, crosses to a warehouse with the suitcase as the other three SIU Princes of the City follow from another car, cradling grocery bags.
Trupo snaps the suitcase open revealing five half-kilo bags of uncut heroin in clear plastic bags.
The other cops pull from the grocery bags: a Pyrex mixing bowl, flour sifter, boxes of milk-sugar, latex kitchen gloves, a medical scale, and yellow baggies.
Hands peel back the distinctive black and green "evidence" tape on the clear plastic bags.
Dump the heroin into twenty yellow baggies.
A half-kilo of lactose is poured into each of the now-empty property room bags.
TRUPO Now just enough for the reagent test.
TRUPO He removes one tablespoon of heroin from each of the baggies, and the now-almost-heroin-free powder is mixed through the flour sifter, poured back into the clear bags, the tape resealed, the bags returned to the suitcase.
The suitcase and "heroin," and some weapons and money, have been arranged on an evidence table with the care of a Macy's display window.
Trupo - the officer in charge of the case - watches the jury files in -
A Lincoln Continental pulls up.
Trupo climbs out of his Shelby with a sports bag, crosses to the Lincoln, climbs in back where an Italian wise guy - Rossi - sits.
Trupo unzips the bag revealing the recut heroin - in the yellow plastic.
ROSSI V/O This is the French Connection dope.
ROSSI V/O The same dope Popeye Doyle and Sonny Grasso took from us.
Frank comes into an empty bar, chairs up on tables.
A middle-aged man mopping up glances up at him as he crosses to a back room.
ROSSI V/O They seize it, arrest everybody, whack it up and sell it back to us.
ROSSI V/O Our dope.
ROSSI V/O They been living off it for years, these New York cops.
Several ounces of the dope sits in foreground on a table.
ROSSI They basically control the market with it.
ROSSI What the fuck has happened to the world, Frank?
FRANK Fuckin crooks.
FRANK Rossi, who looks more like a middle-aged accountant than the Italian dope supplier he is, makes two espressos.
ROSSI Sad about Bumpy.
ROSSI Behind Frank, a TV airs a report by Walter Cronkite on the heroin problem among GIs in Vietnam.
ROSSI Things are never going to be the same in Harlem.
ROSSI The girls, the clubs, the music - walk down the street, nobody bothers you because Bumpy's making sure of it.
ROSSI How bad is it there now?
18pt FLASHCUTS TO HARLEM 18pt
Guys barge into a room, steal money from a crap game at gunpoint - Cops push guys against a bar, empty their pockets - A dealer shoots another dealer in an alley -
18pt BACK TO THE HOTEL ROOM 18pt
FRANK It's chaos.
FRANK Every gorilla for himself.
18pt CONTINUED: 18pt
ROSSI Who can live like that?
ROSSI There has to be order.
ROSSI That would never happen with Italians.
ROSSI More important than any one man's life - is order.
A street sign on a corner: 116th and 8th Avenue.
As is his custom, Frank eats breakfast alone.
A middle- aged waitress appears when he's done, picks up his plate and refills his coffee.
FRANK Thank you, Charlene.
FRANK Last one.
CHARLENE It's all right with me, Frank, you can stay all day if you want, but I wouldn't.
CHARLENE It's nice outside.
FRANK Then maybe I'll have to go for a walk.
FRANK Just cause you said so.
FRANK She smiles and leaves.
FRANK Frank pours some sugar in his coffee.
FRANK Someone taps on the window and he looks up, sees two servicemen - one in uniform - one he recognizes.
Frank leads the servicemen up the stairs of a building.
Corner apartment above the street.
A girl sits smoking at a work table covered with drug-cutting apparatus.
Another - Frank's cutter and sometimes-girlfriend, Red Top - sets a couple of packets of heroin in front of the servicemen.
RED TOP On the house for our men in uniform.
SERVICEMAN 1 Why, thank you, sugar, that's very kind.
RED TOP Thank Frank.
Frank nods, you're welcome before the man can thank him.
The servicemen start cooking up the dope.
FRANK How's Nate?
FRANK You seen him?
SERVICEMAN 1 All the time.
SERVICEMAN 1 Nate is everywhere.
SERVICEMAN 1 He's good.
SERVICEMAN 1 Got himself a club now.
FRANK Where, Saigon?
SERVICEMAN 1 Bangkok.
SERVICEMAN 2 I don't think he's ever coming home.
SERVICEMAN 2 Regarding the dope as the servicemen shoot it up -
FRANK You're gonna have to boot it a couple times.
FRANK Cops keep cutting it, selling it, cutting it -
SERVICEMAN 1 I don't want to say anything cause the price is right - but the shit in Nam is way, way, way, way, way -
SERVICEMAN 1 He begins to nod out before he can finish the sentence.
Across the river, Richie, Rivera and Campizi sit in the car parked across from a closed social club.
A man carrying a grocery bag comes out and Campizi ducks lower in the seat.
CAMPIZI That's him.
CAMPIZI Newsboy Moriarty's mob accountant puts the grocery bag in the trunk of a car, climbs in behind the wheel.
From the parked car they observe the accountant putting another bag in his trunk.
He comes out of another place with another bag.
To Campizi -
RICHIE All right.
RICHIE Get lost.
RICHIE Get out.
Campizi slinks out of the car.
Richie and Rivera follow after Newsboy Moriarty's accountant's car.
They tail the car into a lot, park and watch the accountant leave his car and get into another car that's parked there.
RIVERA We gonna stay with him or the car?
Whatever they do, they'll have to decide quick.
RICHIE Let's see who comes for the car.
All the other cars are gone.
Rivera climbs into Richie's with coffee and a Coke in a bag, hands him the can.
RIVERA Think he made us?
Richie doesn't know.
Glances at his watch.
Cranes in his seat to look behind them.
RICHIE You called for the warrant?
RICHIE Where are they?
RIVERA I just called.
RIVERA I called and walked back here and ten seconds has gone by.
Richie watches an attendant lock up, listens to the street lamps buzz, grows impatient.
Indicating the other car:
RICHIE We saw him with the slips, Javy.
RIVERA You saw policy slips?
RIVERA You saw grocery bags.
RIVERA You don't know what's in them.
RICHIE Yes, I do, and so do you, don't give me that bullshit -
RIVERA What's the rush?
RIVERA Half an hour the warrant'll be here -
RICHIE I got night school.
RIVERA Guess you're going to miss it.
RIVERA You know, what you were saying before - about throwing up in front of people - money will take that feeling away.
RICHIE Not when it's less.
RIVERA Less than what.
RICHIE Than what I make now.
RIVERA No lawyer on earth makes less than a cop.
RICHIE They do in the Prosecutor's Office.
RICHIE Three thousand less.
RIVERA You're fuckin kidding me.
Richie isn't kidding.
Rivera stares at him like he's crazy.
Richie checks his watch.
He's waited long enough.
RICHIE Fuck this -
RIVERA Richie -
Richie gets out, opens the trunk, grabs a Slimjim and bolt cutters, cuts through a gate chain and strides to the accountant's car, Rivera following.
Richie trips the passenger door lock and pulls at the trunk release, and, as he comes around back to search it -
RICHIE Check inside.
Rivera may as well; the damage to the case, if there is one anymore, is done.
He crawls inside the car to look under the seats and in the glove compartment.
Gravely -
RICHIE Javy ...
Richie's staring into the trunk like there's a body inside.
Rivera comes over, takes a look, sees it's money: stacks of it rubber-banded together, spilling from grocery bags - more than either of them has ever seen.
As the trunk closes -
Richie and Rivera sit in their car in silence, staring out at the car with the money in it.
Eventually -
RICHIE This isn't a couple of bucks.
RIVERA It's the same thing.
RIVERA In principle.
RICHIE We're talking about principle?
RIVERA Richie, a cop who turns in this kind of money says one thing: He'll turn in cops who take money.
RIVERA We'll be pariahs.
RICHIE We're fucked either way.
RIVERA Not if we keep it.
RIVERA Only if we don't.
RIVERA Then we're fucked, you're right.
RIVERA But not if we keep it.
RICHIE Yes, we are.
RIVERA Goddamn it, did we ask for this?
RIVERA Did we put a gun to someone's head and say, Give us your money?
RIVERA Cops kill cops they can't trust.
RIVERA We can't turn it in.
They regard each other again in silence ...
As a police captain counts the stacks of money, Lou Toback, Richie's superior from the prosecutors office, walks in, his night out interrupted by this emergency.
He crossed to where Richie and Rivera sit alone in a corner.
Quietly:
TOBACK How much.
RICHIE Nine hundred and eighty thousand.
TOBACK What happened to the rest?
It's a joke but isn't funny, not even to Toback.
He regards his men who turned it in, then the other cops in the place - who are watching them and the money being counted.
Toback walks over to the captain, and, quietly:
TOBACK What're you doing counting this in front of everybody?
TOBACK Are you out of your fuckin mind?
TOBACK Take it into a room.
TOBACK Now.
Richie's glance to Rivera says, You're right, we're fucked.
As Richie leaves alone, he's aware of all the eyes on him - knowing the other cops' looks don't signify awe or respect, but contempt and fear, like Rivera predicted.
Neither will ever be trusted again.
He climbs into his car, drives off.
Tango and his bodyguard come in and approach Frank's table where he reads the morning paper as he eats breakfast.
TANGO Didn't you see the jar, Frank?
TANGO I think you walked right past it.
Frank ignores him, forks at his eggs, eats.
Tango sits.
TANGO The money jar.
TANGO On the corner.
TANGO What I got to do, put a sign on it?
Frank indicates that he would answer if his mouth wasn't full.
He swallows finally, but then only reaches for his coffee cup to take a sip, further irritating Tango.
TANGO Bumpy don't own 116th Street no more, Frank.
TANGO Bumpy don't own no real estate in Harlem no more.
TANGO I'm the landlord now and the lease is twenty-percent.
Frank dabs at his mouth with a napkin and gives Tango a look that says that won't be happening.
TANGO Then don't sell dope, Frank.
TANGO Get a fuckin job.
TANGO You need a job?
TANGO You can be my driver, drive me around, open my door, yes, sir, no sir, where to, sir, right away, Massa Johnson, sir.
Right now Tango is dead.
No doubt about it.
On the surface, though, Frank remains cool.
FRANK Twenty percent?
TANGO Of every dollar.
TANGO Every VIG, every truckload, every girl, every ounce.
TANGO In the jar.
FRANK Twenty percent's my profit.
FRANK If I'm giving it to you then what am I doing?
FRANK Twenty percent puts me, and everyone you know, out of business, which puts you out of business.
FRANK There are ways to make money legitimately, and then there's this way.
FRANK Not even Bumpy took twenty percent.
TANGO Bumpy's fuckin dead.
Frank regards Tango a moment, gets up, takes out his money clip, covers the check on the table with a five, peels off a $1 bill from the clip, tosses it down in front of Tango.
FRANK There.
FRANK That's twenty-percent.
As he turns and leaves, Tango watches after him ...
Stitched-up, black and blue hands dump a can of soup in a pot, put it on the stove.
A pencil clutched by long fingers scribbles figures.
But no matter how many times Frank does the arithmetic, there's not much left, he calculates, after he pays the Italian suppliers and, if he were to, Tango.
Richie has moved to a small desk cluttered with law textbooks.
He cracks one open to study for the New Jersey Bar exam as he eats the soup out of the pot he heated it in.
Above him on the wall is a framed photograph of Joe Louis standing over a sprawled-on-the-mat Billy Conn.
A bleak day.
Seagulls fighting over scraps on the sand as others hover overhead, flapping and cawing.
Alone near the water, Frank tosses a stick for the German shepherd he inherited.
Richie opens a small wooden box in his bleak apartment, revealing an ounce of marijuana, rolling papers and clips.
As he rolls a joint -
BUMPY V/O A leader is like a shepherd -
The sounds of the gulls and surf and roller coaster begin to fade as Frank throws the stick again.
BUMPY V/O Sends the fast nimble sheep out front, and the others follow as the shepherd walks quietly behind -
The dog retrieves the stick, but this time - somehow - it's to Bumpy's hand he returns it.
Frank listens attentively.
BUMPY He's got the stick - the cane - and he'll use if he has to.
BUMPY (CONT'D) But most of the time he doesn't have to.
BUMPY (CONT'D) He moves the whole herd - quietly.
Bumpy smiles and tosses the stick.
The smoke from the joint rises to the ceiling as Richie studies.
The dog trots back to Bumpy and Frank with the stick.
Hot dog stand.
Bumpy hands a hot dog to Frank, holds out another to the shepherd.
To camera:
BUMPY What right do they have cutting out the suppliers, the middlemen, buying direct, putting Americans out of work ...
BUMPY This is the way it is now, Frank.
Frank nods.
The vender hands him a napkin.
The shepherd is still with him, but Bumpy is gone, and the gulls and the people on the roller coaster squeal as Frank comes out of his meditative trance with an idea.
A needle pierces the crook of Frank's arm.
Slight grimace.
A cotton ball is pushed onto the puncture.
Malaria shot.
A strobe lights up Frank's face: a passport photo.
The photo and a duplicate are stapled to a passport application.
Keys turn the locks of a safety-deposit box.
The lid lifts revealing decks of cash.
Frank takes it all out, slips one slender packet into Bumpy's banker's jacket pocket.
FRANK Get yourself a new suit.
Under portraits of bank Vice Presidents before him, the man types out a Chemical Bank check for Frank for $400,000.
The sound of the plane growls and fades overhead as Richie's ex-wife keeps an eye on their son playing on a grassy area.
RICHIE I'm sorry.
LAURIE I don't know, Richie.
RICHIE It couldn't be avoided.
RICHIE Next weekend I'll be able to take him.
RICHIE She regards him with a weary look, but he's looking over at one of the other - better-looking - moms in the park.
LAURIE I'm moving.
LAURIE He looks back, not sure he heard right.
RICHIE What?
RICHIE Where?
LAURIE To the St.
LAURIE Regis, what do you care.
LAURIE My sister's.
RICHIE Your sister's.
RICHIE In Vegas?
RICHIE He glances away to a sound: shattering glass.
RICHIE Some teen- agers breaking bottles on the ground.
RICHIE You can't move to Vegas.
RICHIE Not with Michael anyway.
LAURIE What am I supposed to do with him?
LAURIE Leave him with you?
LAURIE There's a picture.
RICHIE Hey, you want to shut up over there?
The teenagers ignore him.
He tries to ignore them, but it's hard with the constant noise.
RICHIE No court will allow it for one thing.
RICHIE I won't allow it.
LAURIE You?
RICHIE When am I supposed to see my son?
LAURIE Last weekend!
Their son glances over at them.
Richie looks over at the teenagers again breaking bottles, then back to Laurie.
RICHIE Laurie, you can't raise a kid in Las Vegas.
LAURIE Oh, like this is a good environment.
LAURIE Around your friends.
LAURIE There are less creeps in Vegas.
RICHIE What's he going to grow up to be in a mobbed up place like that?
RICHIE What are you thinking?
LAURIE I'm thinking - Richie - of him!
RICHIE Goddamn it -
The noise of the glass is driving him crazy.
He strides over to the teenagers, who look at him like, What are you gonna do, old man, it's four against one.
RICHIE I told you nice to shut the fuck up.
RICHIE Now I'm gonna kill you.
He pulls out his gun and aims it at one of them, then the others.
All instinctively try to cover their heads.
RICHIE Pick up the fuckin glass!
RICHIE As they dive to their knees to do what they're told, Laurie walks away with her son, who looks back over his shoulder at his father with his gun out.
Frank sits in the back of a motor samlor.
Bicycles dart around it like flies.
The clientele is almost exclusively black servicemen on R&R and Asian women.
A trio of ex-GI's plays authentic Southern blues on a small stage.
Ham hocks and collard greens come out of the kitchen.
Smoke chokes the place.
Frank, one of the few men not in uniform, and not drunk or stoned, sits alone at a table with a Coca-Cola and surveys the activity: Dope being rolled.
Dope being smoked.
Dope being shot.
GI's and prostitutes climbing a staircase.
His eyes follow an Army Master Sergeant, moving among the tables as if checking on the GI's well being.
But at some, his hand takes money, leaves in its place packets of powder.
The Sergeant feels eyes on him and glances up, catching Frank watching him from across the room.
He squints through the smoke at the figure at the table in the shadows, and, in a kind of shock, more to himself -
NATE Frank - ?
NATE Frank half-lifts his glass to wave, and Nate beams.
Frank has guests at his table now: his cousin Nate the Sergeant, and two young Asian wise guys.
They talk about him in Thai (subtitled):
THAI He say how much he wants?
NATE He said "a lot."
NATE What that means, I don't know.
NATE Four or five keys?
The Thais regard Frank a moment, size him up.
THAI He's your cousin.
NATE My cousin-in-law.
NATE My ex-wife's cousin.
THAI Ask him how much he wants.
NATE How much you gonna want, Frank?
FRANK A hundred kilos.
Nate blinks like there's something in his eye ...
Steam and neon.
Frank and Nate at a crowded stand.
NATE No one I know can get that much.
NATE It'd have to be pieced together from several suppliers and none of it's gonna be 100- percent pure.
FRANK That's not what I want.
NATE I know that.
NATE But that means dealing with the Chiu-Chou syndicates in Cholon or Saigon - if they'll deal with you -
FRANK No, even then it's too late.
FRANK It's been chopped.
FRANK I want to get it where they get it.
FRANK From the source.
Nate stares at him ...
then laughs.
Frank doesn't.
NATE You're gonna go get it.
FRANK Why not.
NATE You're gonna go into the fuckin jungle -
FRANK I've lived in jungles all my (life) -
NATE No.
NATE This is the jungle.
NATE Tigers.
NATE Vietcong.
NATE The fuckin snakes alone will kill you.
A room of student-type desks and no character.
Richie, and fifty others, have been here for hours taking the exam less than half of them will pass.
A motley bunch of Thai thugs and black American soldiers with automatic weapons ride mules through the dense jungle with Nate and Frank, who - armed with a pistol, a rifle and ammo bandolier like Pancho Villa - is enjoying himself.
From his POV, the jungle canopy suddenly opens up on a poppy field the size of Manhattan.
Frank stares down at it.
On the ground now with their small private army, Nate speaks with one of the Thais, then translates for Frank.
NATE He says this whole area's controlled by the Kuomintang - Chiang Kai-Shek's defeated army.
NATE Some of whom they can see down below on the opium farm - Chinese soldiers with outdated weapons.
NATE Frank tips his head to Nate at some other figures below -
FRANK They ain't Chinese.
FRANK A handful of better-armed American sentries at the perimeter of the farm.
FRANK CIA.
FRANK Frank, Nate and the others hang back as one of the Thais steps ahead to speak to the guerillas.
The processing center for the entire region.
The Thai translator is with Frank to negotiate with a vanquished Chinese general.
Other Americans and Thais guard them while the Chinese with their CIA advisors guard them.
The Chinese general examines Frank's papers - passport, visa, bank receipts - and lots of cash - then studies Frank.
GENERAL How would you get it into the States?
FRANK What do you care?
GENERAL Who do you work for in there?
FRANK What do you care?
GENERAL Who are you really?
FRANK It says right there.
FRANK Frank Lucas.
GENERAL I mean, who you represent?
FRANK Me.
FRANK The man doesn't believe it, but lets it go.
GENERAL You think you're going to take a hundred kilos of heroin into the US and you don't work for anyone?
GENERAL Someone is going to allow that?
GENERAL Frank shrugs.
GENERAL The general regards one of his men.
GENERAL In
Chinese, subtitled:
GENERAL I don't believe a word of this.
GENERAL The general regards the cash and paperwork again for a
moment.
And, to Frank:
GENERAL After this first purchase, if you're not killed by Marseilles importers - or their people in the States - then what?
FRANK Then there'd be more.
FRANK On a regular basis.
FRANK Though I'd rather not have to drag my ass all the way up here every time.
FRANK The man regards Frank for a long moment.
FRANK Glances back to the cash and paperwork again.
FRANK Finally -
GENERAL Of course not.
Torrential monsoon rains.
Dripping camouflage.
Nate and Frank climb down from the Huey.
Frank no longer wears the bandolier.
Now a press card dangles from his neck.
Stripes on the uniform of a black colonel with Nate under a canopy.
Outside, in the distance, in the rain, Frank hangs out with some other black servicemen.
COLONEL Where's it now?
NATE Bangkok.
NATE I can bring it here or anywhere in between.
COLONEL A hundred kilos.
COLONEL I never seen that much dope in one place.
NATE It's bigger than an Amana refrigerator- freezer.
Nate and Frank watch the colonel emerge from the tent and cross through the rain on duck-boards to another tent to speak with a white officer, a 2-star general.
NATE Fifty grand.
NATE In advance.
NATE That'll cover them, the pilots and the guys on the other end.
FRANK Give them a hundred.
NATE Fifty, to cover them all.
FRANK A hundred.
FRANK And it's all I got left.
FRANK So if that dope doesn't arrive, for whatever reason -
FRANK Cousin or no cousin - don't let me down.
FRANK He holds out a business envelope fat with money.
FRANK Nate hesitates, knowing Frank has just said he'll kill him if things don't go right, then takes it.
NATE I'll let you know when it's in the air.
The nurse/paramedic who stitched up his hand is in Richie's bed making so much noise he's worried someone will call the cops.
The phone rings.
And won't stop.
Neither will the nurse as Richie answers it -
RIVERA V/O Richie?
RIVERA V/O Richie, I'm in trouble.
RIVERA V/O This fuckin guy "made" me - I don't know how but he did.
RIVERA V/O He went for his gun.
RIVERA V/O I had to do it, I swear to God.
RIVERA V/O Now they're going to kill me.
RIVERA V/O Richie can hear in Sander's voice how serious it is and manages to disentangle himself from the woman.
RICHIE Who.
RIVERA V/O There's a hundred people out there heard the shots.
RIVERA V/O You gotta help me.
RIVERA V/O You gotta do something.
RICHIE Is he dead?
RIVERA V/O He's dead.
RIVERA V/O I'm dead.
RIVERA V/O They're gonna kill me.
RICHIE Where are you?
RICHIE Javy, where are you?
RIVERA V/O That's the problem.
Richie on his police radio, which cuts in and out -
DISPATCHER There are no cars in that area, Detective Roberts.
RICHIE Bullshit.
RICHIE I got a man in trouble and I need back-up.
DISPATCHER I missed that - you're breaking up -
RICHIE I said, put the fucking call out again -
DISPATCHER I just did.
DISPATCHER No one responded.
DISPATCHER I'll try again, but -
RICHIE Fuck you, too.
RICHIE He slams the mic down.
As Richie's car turns a corner, the Stephen Crane Projects - the most foreboding place on earth - rises up: three dark 30-floor towers planted on war-torn grounds where a long-ago torched and abandoned patrol car sits like a monument.
He parks and moves through an agitated all-black crowd, past an ambulance outside one of the towers, through oppressive heat.
It's riot weather.
Drugs on a coffee table.
Body on the floor.
Rivera, despondent, on the couch.
The male paramedics, scared.
Richie on the phone -
RICHIE Sergeant, I'm not asking, I'm fuckin telling you: Get some patrolmen over here now.
Dial tone: the police sergeant has hung up on him.
Richie throws the phone.
The paramedics stare at him.
PARAMEDIC You got no back-up?
PARAMEDIC Why is that?
PARAMEDIC The only other person who would know the answer to that is Rivera, who just shakes his head in despair.
RICHIE Bandage his head.
PARAMEDIC Detective ...
PARAMEDIC he's dead.
RICHIE I know he's fucking dead.
RICHIE Bandage his head, clean him up, put him on a gurney and prop it up so he's sitting.
RICHIE And open his eyes.
Richie comes out ahead of the gurney, moving quickly like it's a matter of life and death (which it is), motioning at the crowd to allow a path to the ambulance.
RICHIE Step back, injured man coming out.
RICHIE Let them do their job and he'll be all right.
RICHIE Ma'am.
RICHIE Excuse me.
RICHIE Step back.
RICHIE Sir.
RICHIE Please.
The people step back when they see the victim on the gurney: tubes in his nostrils, IV in his arm, eyes open.
Before they can look any closer, he's put in the ambulance.
As it pulls out, siren wailing, Richie leads Rivera safely away -
They cross through an alley near the Projects and Rivera finally breathes a sigh of relief.
RIVERA Thank you -
RIVERA The words aren't out of his mouth before Richie shoves him up against a car.
RICHIE You robbed him, didn't you.
RIVERA What?
RIVERA What are you talking about?
RIVERA Richie rips Rivera's jacket pockets.
RIVERA Money spills out.
RICHIE This.
RICHIE Where'd this come from?
RIVERA What.
RIVERA That's my money.
RIVERA I've never taken dirty money in my life.
RICHIE You lying piece of shit -
RIVERA Maybe the occasional gratuity.
RIVERA Like anybody else.
RIVERA You're going to tell me that's wrong?
RICHIE Yeah.
RIVERA No, it isn't.
RIVERA It's part of the salary for getting shot at.
RIVERA For that, certain courtesies are shown.
RIVERA In gratitude -
RIVERA Richie, disgusted with him, lets go of him.
RIVERA Rivera is embarrassed, almost crying, pleading -
RIVERA A discount on a TV, a Doughboy in the backyard, a new dress for your girlfriend maybe once a year.
RIVERA I'm talking about not living in fucking poverty.
RIVERA You want to call that wrong, call it wrong.
RICHIE It's wrong.
RIVERA Then goddamn it, pay me fifty grand a year, you son of a bitch.
RIVERA Pay me what I deserve for getting shot at.
RIVERA No?
RIVERA Fine.
RIVERA Next time four guys come into your place with sawed-off shotguns, you take care of it.
RICHIE You robbed him, and then you shot him, and I helped you get out of there.
RICHIE How many more you shot?
Rivera suddenly tries to get tough -
RIVERA You know what, Richie?
RIVERA Fuck you, you make that kind of accusation against your own kind.
RIVERA And you know why.
RIVERA He takes out his car keys, turns to leave.
RIVERA Comes past Richie who grabs his arm and pushes the sleeve up exposing a line of puncture scabs and scars.
RICHIE You're a disgrace.
RIVERA I'm a leper.
RIVERA Because I listened to you and turned in a million fucking dollars.
RIVERA You know who'll work with me after that?
RIVERA Same as you.
RIVERA No one.
RIVERA Richie squeezes Rivera's hand around the car key.
RICHIE Don't look down there.
RICHIE Look here.
RICHIE You ever fuckin threaten me again, I'll kill you.
RICHIE Richie squeezes Sander's hand so hard the car key cuts through the skin, drawing blood.
Silence.
Marshland.
A beat-up Chevy parked alongside a perimeter fence.
Frank waits by the car as a military Jeep with its lights out comes across a firing range.
It slows, stops.
In it, the silhouettes of three servicemen, black, armed with M-16's.
Silence again, before:
ARMY CAPTAIN Open the trunk.
ARMY CAPTAIN Frank does it, then stands aside as the other servicemen drag four large taped-up duffel bags from the Jeep to his car, lift them into his trunk and slam it shut.
The duffel bags, still closed, on a table.
Frank regards them, nursing a drink, putting off the moment of discovery that he has perhaps spent his life's savings on nothing.
The German shepherd watches as Frank removes the tape from one of the bags.
He pulls it open - has almost no reaction - except to breathe again - then opens the next, and the next.
And we see: Several brick-like packages of No.
4 heroin wrapped in paper marked with Chinese writing, stamped with a label: two lions on their hind legs, paws on a globe, and, in English: DOUBLE UOGLOBE BRAND 100%.
The duffel bags are elsewhere.
The only evidence of any drugs is the small amount Frank has given a chemist - who looks like a Harvard student - to test.
It responds instantly.
The young man looks at Frank.
CHEMIST Typically what I see is 25 to 45 percent pure.
CHEMIST I've never seen anything like this.
CHEMIST No alkaloids, no adulterants, no dilutents.
CHEMIST It's a hundred percent.
CHEMIST May I?
CHEMIST The chemist opens a leather travel syringe kit to shoot up, but Frank gives him some to take home instead.
FRANK Take it with you.
FRANK I don't want to have to call the coroner.
FRANK The chemist gathers his things to leave, offering a last piece of advice -
CHEMIST Store it in a cool, dark place.
A clapboard house set down on a piece of land that was probably once worked by sharecroppers.
An elderly woman framed in a lit kitchen window, doing dishes.
Dark yew trees and scavenged, discarded cars and car parts like patches of rusty snow.
Crickets and bullfrogs.
From a mound of dirt, a young man hurls a baseball to another with a catcher's mitt exactly sixty feet away.
The kid's got a major league arm.
Legend: Greensboro, North Carolina
A glow spills out from a detached shed where a short man in his early 30's works on a stock car.
A greasy phone on the workbench rings and another disreputable-looking man, thumbing through a magazine, answers.
JIMMY Yeah ...
JIMMY for you.
TEDDY Who is it?
Jimmy doesn't know, sets it down.
Teddy comes over wiping his hands on a rag, takes the phone.
TEDDY Yeah.
FRANK V/O Teddy.
TEDDY Who's this?
FRANK V/O Frank.
TEDDY Frank who?
FRANK V/0 Frank your brother.
Divorced couples in custody battles wait with their attorneys in a packed courthouse.
An lawyer carrying papers clipped with a $10 bill, comes past Richie, who's sitting with his lawyer, a woman he's probably slept with.
SHEILA I'm not talking about your proclivities, Richie.
SHEILA Those I only know too well.
SHEILA I'm talking about being a cop.
RICHIE About taking money?
RICHIE I don't care about money.
RICHIE I don't do that.
SHEILA Because it'll come out.
SHEILA You're going to have to sit down with shrinks and social workers, her lawyers, the judge, lots of questions.
RICHIE What's going on there?
The judge's assistant rearranging the pre-trial cases in order of the amount of gratuity clipped to each - $5, $10, $20 bills.
SHEILA Scheduling.
RICHIE No, the money.
SHEILA Scheduling.
SHEILA What about your friends from the neighborhood?
SHEILA You still hang out with them?
RICHIE I play softball on Sundays with some guys.
SHEILA Wise guys.
SHEILA That's going to look good.
RICHIE I grew up with them, big deal.
SHEILA What about Anthony Zaca?
RICHIE What about him?
SHEILA Richie, I'm just trying to understand things your wife has said.
SHEILA If they're not true, tell me.
RICHIE Yeah, Tony's one of them.
SHEILA Is he also your son's godfather?
Richie nods.
Sheila glances over to where Richie's ex-wife sits with her own lawyer across the room.
SHEILA Do you really care about this?
SHEILA Or do you just not want her to win - ever.
SHEILA How often do you see your son as it is?
RICHIE Not enough.
RICHIE But she wants to make it never.
SHEILA Yeah, all right.
SHEILA Give me a twenty.
SHEILA Well, I'm not going to sit here all day.
She takes a twenty from her purse and carries it up to the judge's assistant clipped to their paperwork.
BAILIFF All rise -
Frank and the dog in the back yard of a suburban house.
His neighbors - those he can see - are white.
He hears a sound - cars arriving - and crosses toward the house where a sold "For Sale" sign leans against a half-built kennel.
Out front, a caravan of cars and pickup trucks - North Carolina plates - loaded with boxes and suitcases - has just arrived.
Exhausted from the drive but excited to be here, the travelers climb out: Frank's five brothers, their wives and kids, and their mother.
Teddy thinks it's the right place.
The others aren't as sure.
The house is too nice.
There's a new Lincoln Towncar parked outside the garage.
They'll probably be shot for trespassing.
The front door opens and Frank comes out, trailed by his dog.
He first gathers his mother in an embrace, then each of his startled brothers.
The house is alive with the noise of family and scent of home-cooked food as the extended Lucas clan - there's more than twenty of them - sits around a big dining room table passing the platters around.
Frank, at the head of the table, clearly loves having them all here.
TURNER He got an arm on him.
TURNER Major League arm, ain't that right.
Everyone agrees as Turner's son - Frank's nephew - the 18- year-old boy seen pitching in the North Carolina back yard - tries to shrug.
FRANK You show me after supper.
TURNER You can't catch him.
TURNER He'll take your head off.
TURNER We're talking 95-mile-an-hour.
TURNER You know how fast that is?
TURNER You see the ball leave his hand, and that's the last you see it before it knocks you down.
FRANK Is that right.
The wonderful noise continues downstairs as Frank leads his mother on a tour of the upstairs.
The place is a showroom of traditional Americana.
FRANK This is your room.
Mrs. Lucas is in awe of the splendor of the bedroom and its furnishings.
It's unlike anything she's used ever seen - not Graceland exactly - but not far off.
Her eyes settle on an old vanity dotted with French perfume bottles.
MRS. LUCAS How did you ...
FRANK I had it made.
FRANK From memory.
MRS. LUCAS You were five when they took it away.
MRS. LUCAS How could you remember it?
FRANK I remember.
She's stunned.
Touches the reproduction of the vanity her son last saw more than thirty years ago.
MRS. LUCAS It's perfect.
MRS. LUCAS It's all perfect.
MRS. LUCAS I'm so proud of you.
The Statue of Liberty against the New York skyline.
FRANK V/O The man I worked for ran one of the biggest companies in New York City for almost fifty years.
As Frank leads his brothers down the sidewalk, the Towncar that was parked at the Teaneck house, driven by Frank's body- guard, Doc, follows alongside at the same pace they walk.
FRANK I was with him every day for fifteen of them, looking after him, taking care of things, protecting him, learning from him.
The brothers can't help but notice the storekeepers who wave to Frank, the women who smile, the men who step out of his path like there's a red carpet under his polished shoes.
FRANK Bumpy was rich, but never white man rich.
FRANK Why?
FRANK Because he didn't own the company.
FRANK He thought he did.
FRANK He didn't.
FRANK He only managed it.
FRANK Someone else owned it.
FRANK So they owned him.
Frank leads his brothers up the stairs and down the hall.
FRANK Nobody owns me.
FRANK Because I own my company.
INTERCUT: Feminine hands stamp small packets of blue cellophane with the words `Blue Magic' -
FRANK And my company sells a product that's better than the competition's at a price that's lower.
Frank stops outside an apartment door.
TEDDY What are we selling, Frank?
Frank pushes the door open, revealing -
Five naked women at work tables, their faces veiled by surgical masks, cutting heroin with lactose and quinine in a precise mixture of controlled purity.
The Lucas brothers stare as the supervisor of the activity - clothed, with red hair - comes over.
REDTOP Hi, Frank.
FRANK Honey, these are my brothers.
Tango strolls down the street like he's the Godfather of Harlem, girl on his arm, bodyguard at his side.
As his brothers eat lunch, Frank - who can see Tango outside - uncaps a glass sugar container.
FRANK What matters in business is honesty, integrity, hard work, loyalty, and never forgetting where you came from.
For reasons his brothers can't imagine, Frank empties all sugar from the container onto his plate.
FRANK You are what you are and that's one of two things.
FRANK You're nothing ...
FRANK or you're something.
FRANK Understand what I'm saying?
The brothers nod tentatively, stare at the now-empty glass container.
Frank wipes his mouth with a napkin, gets up.
FRANK I'll be right back.
He comes out of the diner, crosses the street toward Tango, who's buying fruit.
Greets him cheerfully -
FRANK Hey, Tango, what's up.
FRANK I was just thinking about you.
FRANK (CONT'D) I was looking at the jar and you know what?
FRANK (CONT'D) I didn't see nothing in it.
TANGO The fuck you want, Frank -
Before the last word is out of Tango's mouth, Frank's got a gun pressed against his forehead.
Silence.
Everyone backs away - the bodyguard, too.
Tango's girl pulls her arm from his and takes off.
Eventually -
TANGO What're you going to do, boy?
TANGO Shoot me in broad daylight?
TANGO In front of everyone?
It's as if life on the street has stopped.
No one moves; everyone is looking at Frank; maybe that's what he wants.
As Tango laughs at the thought -
FRANK Yeah, that's right.
Frank pulls the trigger and the big man falls back like someone hit with a board.
Frank stands over him and empties the gun in his chest, the shots echoing down the street.
Then it's quiet again.
Everyone's still looking him, but Frank doesn't run.
Instead, he calmly reaches into Tango's suit pocket, takes out a money clip thick with cash, drops it in the "jar" and sets it next to the body.
FRANK For the cops.
FRANK Should be enough.
Frank returns to the diner and sits back down, ignoring the astonished stares from his brothers and everyone else in the place.
Tries to remember where he was in his lecture as he tucks the napkin back in his shirt collar.
FRANK That basically's the whole picture right there.
A cadaver drawer slides open revealing - not Tango - but Rivera, staring up lifeless, his arms, stomach, legs and toes dotted with the scabs of a longtime addict.
DETECTIVE Did you know his girlfriend?
DETECTIVE Good- looking girl.
DETECTIVE One of his informants.
RICHIE Beth.
The medical examiner slides open another cadaver drawer containing her body.
Richie stares at it.
DETECTIVE Should've seen their place.
DETECTIVE Like animals lived there.
RICHIE I have seen it.
DETECTIVE Chose a good night, huh?
DETECTIVE Grand Central Station in here.
MEDICAL EXAMINER It's been like this.
MEDICAL EXAMINER I'm lucky I get home before midnight; lots of careless- ness.
Richie regards Rivera's personal effects resting on his chest in a plastic bag: few bucks, the Corvette key, a half- empty packet of heroin in blue cellophane.
Richie takes the blue cellophane from the bag and, as the drawer closes entombing Sanders, holds it in his hand ...
REPORTER V/O Heroin addiction is no longer exclusive to big city neighborhoods; it's epidemic -
The reports shows lawmakers on Capitol Hill juxtaposed against images of inner-cities, junkies, homicide victims and, perhaps most telling, white suburbia.
REPORTER ON TV Since 1965, law enforcement has watched its steady increase and with it a rise in violent crime.
REPORTER ON TV Now unaccountably, it has exploded, reaching into cities as a whole - our suburbs and towns - our schools.
The TV is in a small police gym where Richie lifts weights, very much aware of his pariah status as out-of-shape cops come in, only to leave again when they see him.
REPORTER ON TV Someone is finally saying: enough.
REPORTER ON TV Federal authorities have announced their intention to establish special narcotics bureaus in Washington, New York, Los Angeles, Chicago, Boston, Newark and other major cities -
Toback comes in, watches Richie, alone, working out.
RICHIE V/O It's a dog and pony show.
TOBACK V/O It's not being advertised as one.
Richie's changing into his street clothes.
RICHIE But it's federal.
RICHIE I'd have to answer to who?
RICHIE FBI?
TOBACK Me and the U.S. Attorney.
TOBACK No one else.
TOBACK No FBI.
TOBACK Hoover knows better than to mix his men with dope.
TOBACK Too much temptation for the feeble-minded.
Though he's not in much of a position to refuse the assignment, Richie still isn't convinced it's a good idea.
Toback levels with him -
TOBACK Richie, a detective who doesn't have the cooperation of his fellow detectives can't be effective.
RICHIE You know why I don't have it.
TOBACK Doesn't matter.
RICHIE No, they're all on the take and I'm not and it doesn't matter to anyone.
RICHIE Instead of giving you a medal for turning in money, they bury you.
TOBACK It's fucked up.
TOBACK You're right.
TOBACK Maybe this's an opportunity away from all that.
They regard each other.
Eventually -
RICHIE I'll do it, but only like this: I don't set foot in a police station again.
RICHIE I work out of a place of my own.
RICHIE And I pick my own guys.
RICHIE Guys I know wouldn't take a nickel off the sidewalk.
TOBACK Done.
An old building that was once an Episcopal church.
The place has been long abandoned.
The city maintenance worker who let Richie in watches him move through the debris- strewn church.
A real estate broker watches Frank consider the high- ceilinged spaciousness of a grand, unfurnished 50's modern Upper East Side penthouse -
Richie regards the colored light thrown down by the stained glass windows -
Frank regards light streaming in from the garden terrace -
Richie picks up a faded photograph of a priest in a broken frame.
To the maintenance man:
RICHIE This is the only floor we'll be using.
Frank distractedly opens and closes a 12' high curtain in one of the rooms -
FRANK No loan, no contingencies.
FRANK Cash sale.
Wet streets and neon.
Well-dressed crowd behind a velvet rope outside the club.
The Apollo in the background: James Brown on the marquee.
A still-powerful older man in a nice suit rises from his chair to wild applause.
From the stage -
SINGER Mr. Joe Louis, ladies and gentlemen.
Joe bows graciously, gives a little wave to the crowd, and sits back down as the band starts up again.
At another table, Frank sits with Charlie Williams and Rossi, slightly older dope men.
Like Frank, they favor expensive tailored suits.
Their dates, too, are nicely dressed - not too much make-up or jewelry.
Frank's glance moves from Joe Louis and his wife to a beautiful young woman at the table.
FRANK Who's the beauty queen?
CHARLIE She is a beauty queen.
CHARLIE No kidding.
CHARLIE Miss Puerto Rico.
Her glance crosses Frank's briefly but is yanked to the entrance of the club when Frank's brothers come in with their wives and girlfriends.
Teddy's in a parrot green suit, gold chains, hat, acting like he owns the place.
Frank hustles Teddy into an empty back room.
FRANK What is this?
He turns Teddy so he's facing a mirror.
TEDDY What.
TEDDY These are clothes.
TEDDY This is a very nice (suit) -
FRANK I'm wearing clothes.
FRANK These are clothes.
FRANK Those -
FRANK - are a costume.
FRANK With a sign on it that says Arrest me.
FRANK You look like fuckin Jackie Fox.
TEDDY What's wrong with Jackie.
TEDDY I like Jackie.
FRANK You like Jackie?
FRANK You want to be Superfly?
FRANK Go work for him, end up in a cell with him.
Teddy pulls himself from Frank's grasp.
Smooths his shirt, adjusts his hat.
Frank tries to explain to him:
FRANK The guy making all the noise in the room is the weak one.
FRANK That's not who you want to be.
TEDDY He wants to talk to you by the way.
TEDDY I told him I'd tell you.
Frank stares at his brother's reflection in the mirror.
FRANK You and Jackie were talking about me?
TEDDY Not about you.
TEDDY We were talking.
TEDDY He said he wanted to talk to you about something.
Frank clearly wants nothing to do with Jackie Fox.
FRANK I'm taking you shopping tomorrow.
TEDDY I went shopping today.
FRANK You go shopping every day.
FRANK Like a girl.
A creme Bentley pulls up and out pour Jackie Fox and his entourage.
He's got an armful of New York Times Magazines -with him on the cover, flaunting Gangster Chic.
He starts handing them out to the crowd on his way into the club.
Joe Louis has come over to speak to Frank at his table.
JOE LOUIS It's a tax thing.
JOE LOUIS It's a mistake my lawyers will straighten out, but for the time being it's a headache -
FRANK How much you owe?
JOE LOUIS It's nothing, like - fifty grand.
Frank isn't sure if it's an honor or a curse to have a celebrity like Joe Louis asking to borrow money, but nods.
FRANK Sure.
FRANK Don't worry about it.
JOE LOUIS Thank you.
JOE LOUIS I'll pay you back soon as -
FRANK Joe.
FRANK It's a gift.
FRANK Not a loan.
FRANK You don't owe me nothing.
Jackie glides into the club with his magazines and entourage.
Frank watches him make the rounds, lingering at Miss Puerto Rico's table and holding her hand longer than he should with his girlfriend on his arm.
Frank glances to Teddy wearily, then to Doc, alone at the next table like a sentry.
Frank doesn't have to say he's ready to leave.
Doc knows the look.
Gets up.
Frank comes into the coat check area where Doc waits with his overcoat.
As Frank slips into it, Miss Puerto Rico - returning from the ladies room - comes through.
ANA Hi.
ANA I'm Ana.
FRANK I'm Frank.
ANA You're Frank and this is your place.
ANA Why's it called Small's?
ANA Why don't you call it Frank's?
FRANK Because I don't have to.
FRANK He smiles, and it's hard to tell which is more enchanted with the other.
A club across the river.
Not nearly as nice as Small's - much louder - but like Small's, almost all black.
Richie shares a booth with a black undercover detective.
RICHIE I'm reluctant to bring anyone in I don't personally know.
SPEARMAN You know me, and I vouch for them.
SPEARMAN Richie nods, Yeah, he knows that, but remains unconvinced.
SPEARMAN Richie, we work together.
SPEARMAN You want me, you got to take them, too.
RICHIE Where are they?
RICHIE Spearman looks out across the crowded dance floor.
SPEARMAN That's Jones.
SPEARMAN With the skinny white woman.
SPEARMAN Richie's glance finds a young black man dancing wildly with his skinny white date.
SPEARMAN That's Abruzzo, with the fat black one.
SPEARMAN Richie sees a young Italian with tatoos - the only other white man in the place - dancing with a heavy black woman.
SPEARMAN Both Jones and Abruzzo look more like criminals than cops.
SPEARMAN Both are good with wires.
SPEARMAN Have good informants.
SPEARMAN They're honest.
SPEARMAN And they're fearless.
SPEARMAN They'll do anything.
SPEARMAN They're insane, Richie, like you.
Frank sits in back alone.
Peers ahead through the windshield.
His face relaxes as he sees -
Ana waiting on a corner, dressed nice, handbag.
The Towncar pulls to the curb.
FRANK I got it.
FRANK Frank gets out before Doc can, and escorts Ana to the car.
FRANK I hope you weren't waiting long.
FRANK A woman as beautiful as you shouldn't have to wait for anything.
FRANK He opens the door for her like a perfect gentleman, slides in after her.
Outside the house, Doc sits in the car reading a newspaper.
Ana considers some family photographs on a mantle.
ANA This is your father?
ANA Frank shakes his head no.
ANA It's a picture of Bumpy.
FRANK You really don't know who that is?
FRANK It's Martin Luther King.
ANA It is not.
FRANK You're right.
FRANK He was as important as Dr.
FRANK King, though.
ANA What'd he do?
FRANK A lot of things.
FRANK He had a lot of friends.
FRANK He served New York and it served him.
ANA What was he to you?
ANA Frank has to think.
ANA Bumpy was more than his employer.
FRANK Teacher.
ANA What'd he teach you?
FRANK How to take my time ...
FRANK how if you're going to do something, do it with care ...
FRANK do it with love.
FRANK And it's working here.
FRANK It's seductive.
ANA Anything else?
FLASHCUTS - Sudden bursts of violence - guys beat up - others shot - one being poured with gasoline as Bumpy looks on calmly -
BACK TO FRANK'S LIVING ROOM The same calm, benign face in the photograph.
BACK TO FRANK'S LIVING ROOM Frank nods.
FRANK How be a gentleman.
ANA That's what you are?
ANA Ana smiles like she knows better.
ANA Any second now, like every other guy she's ever met, she's sure he'll try to take her upstairs.
FRANK I got five different apartments in the city I could've taken you to.
FRANK I brought you here instead -
Ana glances to the stairs which Frank's mother is coming down.
FRANK To meet my mother.
MRS. LUCAS Is this her?
MRS. LUCAS Oh, she's beautiful, Frank.
MRS. LUCAS Look at her.
MRS. LUCAS She's an angel come down from heaven.
MRS. LUCAS Mrs. Lucas embraces Ana like family.
A single, half-empty packet of heroin, the same one from the morgue, in distinctive blue cellophane, tacked to a bulletin board.
Richie, perched on a desk in front of it.
RICHIE Our mandate is to make major arrests.
RICHIE No street guys - we want the suppliers - the distributors.
RICHIE Spearman, Jones and Abruzzo sit in the back, looking like delinquent students.
RICHIE Of everyone in the open ground-floor that's been only slightly renovated - and there are about fifteen of them - they're the most disreputable-looking.
RICHIE Heroin, cocaine, amphetamines.
RICHIE No grass under a thousand pounds.
RICHIE Less than that, someone else can waste their time.
RICHIE Jones nudges Abruzzo to pay attention.
RICHIE Abruzzo elbows him back.
RICHIE Richie just waits like a teacher for their attention.
RICHIE We'll be handling big shipments, big money, big temptation.
RICHIE Yeah.
JONES There's a story about you.
JONES About turning in some money.
JONES A lot of money.
JONES Is it true?
Jones isn't the only one here curious to know.
Simply:
RICHIE It's not true.
Abruzzo, looking like a junkie, dirty jeans, wool cap, approaches a dealer on the corner.
The perspective shifts to Richie, Spearman and Jones in a car, watching as Abruzzo chats briefly with the dealer before the exchange takes place: $10 for a blue-cellophane packet.
Richie and the others watch Jones tests the heroin.
JONES Stuff's ten percent pure.
JONES Strong enough to smoke for all those suburban white kids afraid of needles.
JONES The other detectives are exchange a glance.
JONES None has ever heard of anything on the street that pure.
RICHIE You paid ten bucks for it?
JONES And it's all that's out there.
RICHIE Now, how is that possible?
RICHIE Who can afford to sell shit twice as good for half as much?
RICHIE Richie glances to a Table of Organization: Surveillance photos haphazardly thumb-tacked to a bulletin board - known dope men in the hierarchies of their individual crime families - almost all of them Italian.
An R & B song begins and continues over -
A poppy bulb being pierced, the white liquid oozing, changing into filthy liquids in wooden bowls, and finally a gray paste ...
Frank sits with the bank Vice President who wires a transfer to:
Where Nate sits with the same Thai bank president as before who converts the transfer to cash.
Nate slides cash across a table to a couple of Chinese gangsters.
A tent: Nate hands more cash - the military brass's cut - to the 2-star general from before.
An airstrip: Slicing propellers.
Wounded soldiers on stretchers, helped onto a transport plane.
Nearby, four large crates - Japanese TVs - under cargo netting.
The pilot stuffs more cash in a pouch and salutes Nate.
General Westmoreland returns a salute (archive).
The same plane on the tarmac here, taxiing.
A pile of discarded TV boxes outside a supply warehouse.
At the perimeter of the base, black servicemen transfer heavy taped-up duffel bags from an Army Jeep to a station wagon, hoisting those that won't fit inside onto a roof rack.
Two Lucas brothers tie them down with twine.
The station wagon heading north on a rain-slicked highway, the canvas tarpaulin on top flapping.
In the distance, the spire of the Washington monument glows.
A black woman pushes a shopping cart containing a baby, Pampers, and cases of milk sugar across a parking lot.
Empty milk sugar boxes.
Redtop and her five table workers - clothed now, the surgical masks dangling from their necks - wiping down table surfaces, scales and apparatus.
Tens of thousands of blue-cellophane packets of heroin neatly cover two of the folding tables.
August.
Hot.
Kids wrench open a fire hydrant and with an empty soda can direct the water into a fountain.
The water sprays down onto the windshield of a beat-up Chevy coming slowly through, revealing when it clears, Frank behind the wheel.
He parks.
Glances at his watch.
Clock on the wall of a locker area: 3:58.
Shift change.
Cops in t-shirts.
Fans blowing the humid air around.
Blue and whites arriving and leaving, shirts coming off as the cops alight.
The driver checks his watch: 3:59.
Turns his almost-empty bus up 8th Avenue.
Air conditioner full blast.
Radio announcing the time: 4 o'clock.
Frank glances out the wet windshield of the Chevy and watches 116th Street transform:
It's as if an outdoor market has just opened its stalls.
Junkies and dealers emerging from the alleys, storefronts, tenements and side streets - from the street itself it seems - snarling the cars and delivery trucks caught unaware.
Small blue cellophane packets - and only blue - are pulled from pockets and change hands.
In alleyways it's cooked up and sucked into syringes, and in dank, grim, indescribably filthy rooms, plunged into veins -
10 and 20 dollar bills changing hands - decks of cash rubber-banded together - put into envelopes and delivered to the Lucas brothers, to:
125 LESTER at his metal door shop.
125
126 EUGENE at his dry cleaners.
126
127 TURNER at his tire service shop.
127
128 EARL at his electrical shop.
128
129 TEDDY at his body shop.
129
Piles of cash.
The brothers try counting it all, but it's just too much.
It's actually tiring.
TEDDY We're going to be here all night if we count every bill.
TEDDY TIME CUT: A money-counting machine flips through the bills, its counter flying.
TEDDY The brothers rubberband it all in $100,000 decks.
TEDDY Jot down the numbers.
TEDDY Put the money in newly-assembled file boxes.
TEDDY Tape them shut.
Alone in the room, Frank transfers stacks of $100's from the file boxes into several open safety-deposit boxes.
The penthouse is now richly decorated.
The R & B music playing through a state-of-the-art stereo system.
It's a kind of office party for Frank's brothers, cousins, wives and girlfriends, distributors like Rossi and other East Harlem guys, Charlie Williams, couple of cops on Frank's payroll, and the Chemical Bank Vice President.
BANKER You got a stockbroker, Frank?
FRANK I deal with enough crooks as it is.
FRANK The banker jots down a name and phone number on the back of one of his business cards.
BANKER This one couldn't be more honest.
BANKER Ask around.
BANKER He's got a lot of clients in the business.
BANKER You can't leave all your money in safety deposit boxes; give him a call.
BANKER The banker hands him the card and moves on.
BANKER Frank's trying to have a good time, but the level of noise and revelry is beginning to make him uncomfortable.
CHARLIE Frank.
CHARLIE This is Mike Sibota.
CHARLIE Sibota tries not to look as nervous as he feels.
FRANK Mr. Sibota.
FRANK What can I get you?
SIBOTA A left-hander from what Charlie tells me.
SIBOTA Your nephew?
SIBOTA Frank points to his nephew, Stevie, across the room.
FRANK It's been his dream all his life to play for the Yankees - and he's good enough.
SIBOTA So I hear.
SIBOTA You have him come see me.
SIBOTA We'll give him a try-out.
SIBOTA As the scout hands his card to Frank, we whip over to where Teddy, his driver Jimmy Racine and their girlfriends, coked up, are laughing as a black cop, flashing his detective's shield, pretends to frisk Jimmy.
DETECTIVE What's this?
DETECTIVE Oh, that's it, I'm taking you in.
JIMMY You can't take me in for that, I got a license for that, motherfucker.
DETECTIVE This then - (the pile of coke on the coffee table) But first -
DETECTIVE The cop sucks up a line before pretending to cuff Jimmy.
DETECTIVE All right, now I'm arresting you.
DETECTIVE Everybody laughs.
DETECTIVE Teddy peels $100's from a money clip.
TEDDY Let him go.
TEDDY This is for you.
DETECTIVE What is that, a bribe?
DETECTIVE Oh, now you're all under arrest.
The cop pretends to arrest them all, but what he doesn't pretend is the hand he puts on Jimmy's girlfriend's breast as he frisks her.
JIMMY What is that?
JIMMY It was quick but Jimmy saw it, even though his girlfriend didn't react.
JIMMY The cop, oblivious, is cuffing Teddy now.
DETECTIVE I'm taking you all in.
JIMMY I said, what the fuck was that?
DETECTIVE What was what?
DETECTIVE The room explodes with a boom and the detective crumples to the floor, clutching at his leg, blood running through his fingers onto the carpet.
DETECTIVE Frank stares.
JIMMY Oh, he's all right.
JIMMY I just shot him in the leg.
JIMMY You got a health plan, what are you complaining about.
JIMMY He's fine.
JIMMY Here -
JIMMY Five hundred all right?
JIMMY Six?
JIMMY Look, he's feeling better all the time.
JIMMY Suddenly, Frank grabs Jimmy and throws him against the wall.
As Ana tries to clean the blood stain on the rug with salt and soda water, Frank sits with his five brothers in the debris-strewn aftermath of the party.
Silence before:
FRANK I can't have this kind of stupidity.
TEDDY It was an accident.
TEDDY He feels terrible about it.
FRANK He doesn't feel shit, coked up all the time.
FRANK Get rid of him.
TEDDY Frank.
TEDDY He's your cousin.
TEDDY What's he gonna do?
TEDDY Go back home?
TEDDY I'll talk to him.
TEDDY I'll straighten him out.
TEDDY Frank looks at Teddy in his tinted Jackie Fox-like goggle glasses - like he's going to straighten anybody out.
FRANK Gimme those glasses.
TEDDY What?
TEDDY Why?
TEDDY Frank pulls them from Teddy's face and crushes them.
Richie sifts through the morning mail at his desk.
Stops on an envelope from the New Jersey Bar Association.
As he works up the nerve to open it, Spearman, Jones and Abruzzo organize the Italian wise guys' photos on the T.O.
JONES Ice Pick Paul goes here -
ABRUZZO No, he's under Benny Two-Socks -
JONES No, you're thinking of Benny the Bishop.
JONES Benny Two-Socks is Tosca's deadbeat son- in-law.
SPEARMAN Jonesy's right.
SPEARMAN Richie comes over, studies the Table of Organization a moment, then begins untacking the photos from the top down -
JONES What're you doing?
JONES We just -
RICHIE For a cop the uppermost thing is the arrest.
RICHIE For a prosecutor, the arrest is nothing without the evidence to convict.
RICHIE We don't have any real evidence on anyone on this board, so they're coming down.
RICHIE We're starting over from the street.
ABRUZZO What are you, a prosecutor all of a sudden?
ABRUZZO Richie tacks his exam results onto the T.O. He passed.
Richie and the Amigos observe a buy from a parked car, the blue cellophane changing hands.
Ignoring the buyer as he walks away, they keep watching the seller.
The seller is observed coming out of a mechanics garage.
Richie ignores him as he walks away, watching instead the garage.
Eventually, a mechanic wiping his hands on a rag steps out, and Richie raises a camera.
The image of the mechanic - a supplier - freezes -
A slightly-blurred photo of the mechanic goes up on a new, almost bare Table of Organization.
Atop of a telephone pole, Abruzzo, dripping with lineman equipment, works to attach a `slave' to the lines -
Bare room.
Richie, Jones and Spearman eating take-out food as tape recorder reels turn.
PHONE VOICE Those snow tires you give me last time come in yet?
PHONE VOICE I'm going to want some more of them, gimme one and a half more of them.
PHONE VOICE The detectives laugh.
Toback has Richie sign a voucher for $20,000 cash.
TOBACK This is more than a year's salary, Richie.
TOBACK If it disappears, I won't be able to get it for you again.
RICHIE It'll never be out of my sight.
Jones tapes a tape recorder the size of a pack of cigarettes to Richie's bare chest.
Undercover in a wise guy's cashmere sweater and slacks, Richie watches the mechanic count the $10,000 he's given him.
RICHIE It's got to be `Blue Magic.'
MECHANIC Yeah, yeah, it's `Blue.' You can pick it up here tomorrow.
MECHANIC Where's the rest of the money?
RICHIE That's half.
RICHIE I'll give you the other half tomorrow when you give -
MECHANIC No, no, no, I don't do that.
MECHANIC Go fuck yourself.
MECHANIC Richie rather reluctantly hands over the rest of the 20K.
Spearman watches the pickup truck driven by the mechanic change lanes up ahead - heading for the George Washington Bridge - and glances over concerned to Richie, who is changing the cashmere sweater for an old t-shirt.
SPEARMAN He's going into New York.
SPEARMAN Are we?
RICHIE What are they going to do, arrest us?
SPEARMAN They could.
SPEARMAN New York cops.
SPEARMAN They can do worse than that.
RICHIE We're not losing that money.
RICHIE Go.
As Spearman follows the truck, the George Washington Bridge, linking Jersey to Manhattan, looms in the windshield ...
The pickup pulls to the curb outside a Pleasant Avenue grocery store.
As the guy enters the place, Spearman's car stops long enough for Richie to climb out, and continues on.
Richie crosses the street, tries to see who the guy is talking to inside, but he's just buying a cup of coffee to go.
Spearman's car turns the corner to circle around the block.
As soon as it's gone, the man emerges from the restaurant with the coffee and walks straight at Richie who has to double back quickly not to be seen
Richie sees a delivery truck double-parked, guys unloading crates.
Hears a horn and knows it's must be Spearman stuck on the side street.
The mechanic starts his truck.
Desperate not to lose him (and his money), Richie hurries over to a taxi stopped at a light, flashes his badge.
RICHIE Get out.
TAXI DRIVER What?
RICHIE Get the fuck out of the car!
RICHIE The driver realizes the man outside his taxi is crazy and tries to get his window rolled up.
RICHIE Reaching in, Richie gets his arm stuck, pulls at the lock, yanks the door open, drags the driver out, breaking the cabbie's arm, and jumps in.
RICHIE He swings the cab into opposing lanes to get around traffic, screeches around the corner, glimpses the truck far up ahead - guns the engine, flies through a red light, glances at his mirror at the cars that just missed him almost colliding -
RICHIE The truck turns up ahead, and Richie barrels through another red light, turns the corner and keeps the truck, a couple car-lengths ahead - in sight.
Richie curbs the cab as the guy goes into a dingy pizza parlor.
Richie climbs out, crosses the street.
Coming past the place, he tries to look inside without breaking stride.
From around a corner, striding toward him, come four men looking like Gestapo thugs in leather coats, manicured hair - the Princes of the City.
Richie detours into an alley as they enter the restaurant.
Richie peers in at the restaurant kitchen through a grimy basement window.
Watches Trupo and his SIU detectives burst in, guns drawn.
They rough everybody up, get some down on the floor.
One detective gathers the money and stuffs it in a bag.
Another gathers the dope.
The mechanic tries to protest and Trupo slaps him down with his pistol.
Richie keeps watching as the NY cops arrest no one - but take the dope and the money (Richie's money) - and stride out as abruptly as they appeared, like bandits.
As they come past Richie -
RICHIE That's my money.
SIU DET 1 The fuck are you.
SIU DET 1 What money?
SIU DET 1 Richie shows them his Bureau of Narcotics ID.
RICHIE The bills are sequenced and registered with the Essex County Prosecutors Office.
RICHIE All begin with CF3500.
RICHIE Take a look.
RICHIE One of them checks some of the bills and sees he's right.
SIU DET. 2 Goddamn it, I thought we had a score.
SIU DET. 2 I thought I had a fucking Chris-Craft sitting in my driveway.
RICHIE Honest mistake.
RICHIE Just give it back to me.
SIU DET. 1 This time.
SIU DET. 1 Three of the four cops laugh.
SIU DET. 1 It's an affable gang of thieves.
SIU DET. 1 The one who doesn't laugh hangs back as the others start off.
SIU DET. 1 He examines Richie's New Jersey ID.
TRUPO When's the last time I was in Jersey?
TRUPO Let me think.
TRUPO Never.
TRUPO What're you doing coming over here without letting anybody know?
TRUPO You don't know you can get hurt doing that?
TRUPO (CONT'D) You got your money.
TRUPO (CONT'D) Now, never, ever, come into the city again unannounced.
TRUPO (CONT'D) You come in to see a fuckin Broadway show you call ahead first to see if it's okay with me.
TRUPO (CONT'D) Trupo pats him on the back and leaves with the others.
TOBACK V.O. What do we hate most?
TOBACK V.O. Isn't it the transgressions of others we fear we're capable of ourselves?
It's very late.
Richie and Toback are alone.
Eventually -
TOBACK Richie - cops are like -
RICHIE Yeah, I know, like everyone else.
RICHIE Some of them will steal no matter what.
RICHIE There can be a camera on them they'll do it.
RICHIE Some'll never do it.
RICHIE The rest are capable of either, depending how their department leans ...
RICHIE Only theirs isn't leaning, it's fallen over.
RICHIE The patrol cars don't even stop in Harlem, just roll down the window so the dealers can throw the money in.
RICHIE I saw drops made on precinct steps.
TOBACK What were you doing there?
RICHIE It's where this dope is coming from.
RICHIE Blue Magic.
RICHIE Out of New York.
RICHIE What am I supposed to do, ignore it?
TOBACK The cab driver's filed aggravated assault and grand theft charges -
RICHIE He wouldn't stop.
RICHIE Motherfucker almost ran me over.
TOBACK - which he may reconsider depending on the amount the State of New Jersey offers to settle -
RICHIE I told him I was a cop.
RICHIE I showed him my identification.
TOBACK You stole his cab and broke his arm.
RICHIE I was chasing your 20 thousand dollars.
TOBACK I don't want to hear about you going into New York anymore.
RICHIE Then my investigation's over.
You're not listening to me.
I said: I don't want to hear about it ...
You do whatever you have to do, go wherever you have to go to find out who's bringing this shit into the country ...
Just don't tell me.
Get some sleep.
Richie - in robe and underwear - opens the door to find a woman in the hall holding a briefcase.
VIDA Mr. Roberts?
VIDA I'm here for our appointment.
VIDA He has no idea who the black woman is.
VIDA An old girlfriend he's forgotten maybe.
VIDA Behind him, Vida can see a stewardess buttoning up her uniform by a little travel case on wheels.
VIDA The apartment itself, she can also see, is a mess.
VIDA From Child Social Services?
Barbecue after their Sunday softball game.
Richie and his O.C.
friends - wise guys - still in their brown and orange Weequahie jerseys, drinking beer, cooking hamburgers.
TONY When you asked me to be your son's godfather, I took it very seriously.
RICHIE I know.
RICHIE Richie and Tony Zaca relax in the den-like pool house.
TONY I said yes, I'd take on this responsibility, take care of your son, God forbid something happened to you -
RICHIE Tony, the things she's telling Child
Social Services make me look very bad: Out all night.
Lowlife informants hanging around.
Women -
TONY Old friends like me.
Richie feels horrible doing this.
Silence.
Then:
TONY It's all right.
TONY I understand.
TONY They ask me, I'll tell them what you want me to tell them.
TONY I'll lie for you.
RICHIE Thank you.
RICHIE Tony nods, You're welcome.
RICHIE Can tell there's something else on Richie's mind.
TONY What.
RICHIE You don't have to talk about it, you don't want.
RICHIE What do you hear about Blue Magic?
RICHIE Anything?
TONY A lot of sorrow and misery from guys being put out of business.
TONY That's all.
RICHIE Nothing about who's bringing it in?
TONY Guys down south is all I heard.
RICHIE Down south, Florida?
RICHIE Cubans?
RICHIE What.
TONY I don't know.
TONY All I can tell you is whoever it is, they're upsetting the natural order of things.
TONY Among the framed family photos around them, is a picture of Tony's uncle, Albert Tosca.
A Napoleonic statue of the same man on horseback in a fountain outside a castle-like mansion.
Next to it "ride" three others on marble horses - a woman and two children.
TOSCA Pull -
TOSCA A clay pigeon sails out across the manicured garden.
TOSCA A shotgun blast shatters it.
TOSCA The man with the gun - Albert Tosca - hands another to Frank.
TOSCA As Frank sets to shoot, Ana can seen behind them, with Tosca's wife in the opulent house, looking uncomfortable.
MRS. TOSCA The whole place was imported brick by brick from Gloucestershire.
ANA It's very nice.
ANA Mrs. Tosca nods.
ANA Ana nods.
ANA A strained silence thicker than the tapestries settles over them until -
FRANK Pull -
FRANK The shotgun booms -
As servants stand by, Tosca and his wife and their only guests - Frank and Ana - finished with lunch, get up from the table in the formal Formal dining room.
As Mrs. Tosca leads Ana off to give her a tour of the house, the men head off the other way.
TOSCA She's a lovely girl.
TOSCA You should marry her.
FRANK Too many things to look after right now to think about that.
TOSCA Frank.
TOSCA That's a mistake.
TOSCA If I may say.
TOSCA Don't take her for granted, girl like that.
TOSCA They enter a rich, wood-paneled study lined with books.
TOSCA You interested in history, Frank?
TOSCA The events that have brought us to where we are today?
TOSCA You know who was?
TOSCA Bumpy.
FRANK Bumpy was interested in a lot of things.
TOSCA I always wonder if people know when history's being made.
TOSCA And what they're doing at the time.
TOSCA This, for instance, could be a historic moment, and you're sipping a glass of ice water.
TOSCA Droplets snake down Frank's glass.
TOSCA He senses Tosca has finally gotten around to why he was invited here.
TOSCA Bumpy and I did a lot of business together, as you know.
TOSCA Whatever he needed, he'd come to me and I'd do my best to provide it.
TOSCA He came to me, I didn't go to him, is the point I'm trying to make.
TOSCA You know why?
FRANK He didn't have what you needed.
FRANK You had what he needed.
FRANK We've always had to come to you.
TOSCA Yes.
TOSCA Until now.
TOSCA Tosca studies Frank, who is a study in inscrutability.
TOSCA Monopolies are illegal in this country, Frank, because no one can compete with a monopoly.
TOSCA If they let the dairy farmers do that, half of them would go out of business tomorrow.
FRANK I'm just trying to make a living.
TOSCA Which is your right.
TOSCA Because this is America.
TOSCA But not at the unreasonable expense of others.
TOSCA That's un-American.
TOSCA You know the price you pay for a gallon of milk doesn't represent its true cost of production.
TOSCA It's controlled.
TOSCA Set.
FRANK I set a price I think is fair.
TOSCA It's very unfair, in fact.
TOSCA Your customers are happy, but what about your fellow dairy farmers?
TOSCA You're not thinking of them.
FRANK I'm thinking of them as much as they ever thought of me.
TOSCA All right.
TOSCA I can see you're getting excited.
TOSCA Don't get excited.
TOSCA That's not why I invited you to my home.
TOSCA To get excited.
TOSCA Frank doesn't look excited at all.
TOSCA He's the picture of calm.
TOSCA Tosca smiles benignly and gets up.
TOSCA Here, I got something for you.
Tosca opens a humidor, takes out a couple of Cuban cigars.
TOSCA Now what if - I'm just thinking out loud - you sold some of your inventory wholesale and I helped with the distribution.
FRANK I don't need it.
FRANK I already got everything from 110th Street to Yankee Stadium, river to river.
TOSCA Which is a little mom and pop store compared to what I'm talking about.
TOSCA I could make you bigger than K-Mart.
TOSCA L.A., Chicago, Detroit, Vegas.
TOSCA I'm speaking nationwide.
TOSCA And I'd guarantee you peace of mind.
TOSCA You know what I mean by that.
TOSCA Frank does.
TOSCA It's a backhanded threat.
TOSCA Tosca clips the cigars with a gold guillotine
TOSCA Frank.
TOSCA You can see I'm a Renaissance man.
TOSCA Unfortunately not all my people are as enlightened.
TOSCA Ask them, What is civil rights, they don't know.
TOSCA They're not as open to change from the way things are done and who's doing it.
TOSCA But I can talk to them so there won't be any misunderstanding.
TOSCA That's what I mean by peace of mind.
TOSCA Frank knows, in truth, he's not being given any choice in this matter.
TOSCA Still, maybe it's not so bad.
FRANK You pay what a kilo now, 75, 80?
FRANK I'd consider 50.
FRANK And I can get you as much as you want.
FRANK Tosca slips on his best poker face.
FRANK Fifty thousand a kilo would be an extraordinary coup for him.
TOSCA You see, I was right.
TOSCA This is a historic moment.
TOSCA You're going to be bigger than Bumpy himself.
TOSCA He hands Frank one of the cigars, expertly prepared.
TOSCA Can't smoke it here, unfortunately.
TOSCA Grace doesn't like it.
TOSCA Take it with you.
Doc waits by the car as Frank and Ana walk toward him.
The Toscas wave goodbye from the front step of the mansion.
Frank slips the cigar into his top pocket as they climb in.
ANA Why would you trust these people, the way they look at you?
FRANK They look at me like it's Christmas and I'm Santa Claus.
ANA They looked at us like we're the help.
FRANK No.
FRANK They're working for me now.
A TV: Muhammad Ali, the black man's black man, and Joe Frazier, the white man's black man, at their 1971 Madison Square Garden press conference where Ali says as much.
Most of the guys watching it.
Richie isn't.
He comes over to Table of Organization.
Tacks his Bar Association notice to it.
Regards the photographs, like tentacles of octopus yet to have a head.
Only the lowest section is made up of blacks (including Charlie Williams and Jackie Fox, but not Frank Lucas).
The rest of the faces are white and stop about midway up.
They've hit a wall they can't get past.
Another TV here: Howard Cosell, ringside at the Garden as the first early fans arrive, pointing out that the fight, because of the political stand Ali's taken, is less about boxers than war versus anti-war.
Frank chooses a linen jacket from his extensive color- coordinated racks of Phil Cromfeld suits as Ana, in her lingerie, puts on make-up at a vanity.
He comes up behind her and sets down a small jewelry box.
The TV in the background as Richie puts a camera with a long lens in a sports bag and reaches for his coat -
Ana's reflection in the vanity mirror as Frank slips the engagement ring on her finger.
She wipes at a tear, then gets up and hugs him.
ANA Yes.
ANA She kisses him.
ANA Admires the ring.
ANA And -
ANA I bought you something, too.
ANA She crosses past the TV, takes a garment bag down from her side of the closet, lays it on the bed next to Frank's suit jacket.
ANA She takes hold of the zipper but doesn't immediately pull it, hoping perhaps to create some dramatic tension.
FRANK What is it?
FRANK She unzips the bag like she's unveiling great art.
FRANK But instead of seeing what's inside, we're allowed only Frank's reaction: his smile of anticipation slowly changing to chagrin.
Richie observes celebrities and gangsters arriving in limousines - Sammy Davis Jr.
and his wife, Joe Louis and his, Tosca and some of his guys - then enters the arena as another limo pulls up.
Ana climbs out.
ANA Come on.
ANA You look great.
ANA You want to miss the fight?
ANA Come on.
ANA Finally, a patent leather shoe pokes out, sets down on the curb.
ANA Then its mate beside it.
ANA The shoes step away from the limo and -
Pre-fight.
Richie, blended in with the a group of press photographers, regards the organized crime figures ringside.
He takes a few pictures with the long lens camera as -
The owner of the gleaming patent leather shoes is shown to his second row ringside seat just behind the sports writers, and we move up the full-length chinchilla coat to Frank's uneasy expression -
Richie's camera roams the faces of the prime ticket holders ringside: organized crime figures, celebrities, politicians, women with plunging necklines and platinum hair -
JOE LOUIS Excuse me -
JOE LOUIS Richie can't believe it's Joe Louis brushing past him -
RICHIE Mr. Louis -
RICHIE Joe looks back as Richie approaches him -
RICHIE I'm sorry, but I just have to tell you, sir, you were a hero to me growing up.
RICHIE I still push elevator buttons eight times for the rounds you beat Billy Conn in.
RICHIE For luck.
RICHIE Louis acknowledges Richie only slightly more than not at all.
RICHIE Turns away to join his friends.
RICHIE Richie watches after him, stung by Louis's disregard.
RICHIE He snaps a picture of an Italian wise guy he doesn't recognize ...
RICHIE sifts the camera's view past Frank in the chinchilla coat ...
RICHIE then returns to him, watches as Tosca and his guys sit down behind Frank.
RICHIE Richie can't hear - but can see - their good-natured exchange -
TOSCA Hey, Frank, you keep that hat on, I'm gonna miss the fight -
TOSCA The odd thing to Richie is, Chinchilla's seat is better than all the Italians'.
TOSCA Detective Trupo notices this, too.
TOSCA Richie focuses on the Chincilla's date, a stunning girl, a beauty queen, then shifts back to her boyfriend who's now shaking the proffered hands of other Italians, then Don King.
TOSCA Joe Louis himself - who barely acknowledged Richie's existence - comes over and playfully exchanges "punches" with the man in the chinchilla coat.
TOSCA A sudden roar from the crowd as the lights go out except for the spot on the ring.
TOSCA Ali and Frazier are coming down the steps through the crush of fans and reporters, preceded by soldiers carrying flags -
Richie tries to find the guy in the chinchilla coat, but he's hidden by a flag.
Then he glimpses him again just as Ali shakes his hand before climbing into the ring -
Flashbulbs pop throughout the arena as Robert Goulet begins the National Anthem.
Ali pointedly doesn't sing along.
Richie frames the shadowy figure in the chinchilla coat, focuses as sharp as he can in the bad light, and snaps the shutter -
Richie tacks the photograph of the man in the chinchilla coat to his Table of Organization - low and off to the side by other pieces of the puzzle that don't fit, other new faces with no names.
Spearman holds a scrap of paper -
RICHIE That's is the plate number on the limo.
RICHIE Check with the company, who rented it.
SPEARMAN He's a supplier at most.
SPEARMAN Or just a pimp.
SPEARMAN We'd've heard of him otherwise.
RICHIE No, he's bigger than that.
RICHIE His seats were phenomenal; better than Al Tosca's.
RICHIE Joe Louis and Ali shook his fuckin hand.
RICHIE They look from Tosca's high position on the board to Frank's low one, and a wedding march played in traditional fashion
on organ begins and carries over:
From above, a sea of ladies' hats, all coral and pink.
Below, Frank stands at the altar, waiting for his bride.
RICHIE V/O His name is Frank Lucas ...
Toback sifts through documents Richie has gathered: limousine company records, Frank's thin arrest record, mug shots of him years younger, the photograph from the fights and some more from subsequent surveillances.
RICHIE Originally from Greensboro, North Carolina.
RICHIE Couple of arrests years ago.
RICHIE Gambling, robbery, unlicensed firearm.
RICHIE (CONT'D) For fifteen years he was Bumpy Johnson's collector, bodyguard and driver.
RICHIE (CONT'D) He was with him when he died.
Ana's family and friends on one side of the aisle, the extended Lucas family - on the other.
Frank's mother looks at her eldest son at the altar with pride.
RICHIE Five brothers, he's the oldest, lots of cousins, all living here now, spread out around the boroughs and Jersey.
RICHIE The brothers are -
A Lucas brother hands some dry cleaning to Spearman -
RICHIE V/O Eugene Lucas in Brooklyn -
Another Lucas brother examines a lamp with a frayed cord brought in by Jones.
RICHIE V/O Earl Lucas in Newark -
Another brother at the register, hands Abruzzo a receipt -
RICHIE V/O Lester Lucas in Queens -
Another brother is photographed by Spearman from a parked car as he changes tires on a car up on a hoist.
RICHIE V/O Turner Lucas, the Bronx -
Richie kicks a dent into the fender of his old car.
As an appraiser writes up an estimate, Richie observes Teddy, attending to paperwork inside.
RICHIE V/O And Teddy Lucas, in Bergen County.
A photograph of Teddy goes up on the T.O. next to Frank and the other brothers and some cousins -
RICHIE Except for the chinchilla coat, which no one can explain, Frank's life seems orderly and legitimate.
Best Man Teddy standing next to Frank at the altar as the bride is escorted down the aisle by her father.
Tight on Frank in a beautiful tuxedo -
A light goes on in a penthouse window.
Down below, by his parked car, Richie shivers in the early morning cold.
RICHIE V/O He gets up early.
RICHIE V/O Five a.m.
RICHIE Has breakfast at a Midtown place, usually alone.
Richie tosses a glance inside a restaurant as he passes the window to where Frank sits eating at a table, Doc nearby.
RICHIE Then goes to work.
RICHIE Meeting with his accountant, or lawyer, dropping in on one of the several office buildings he owns.
RICHIE Nights, he usually stays home.
RICHIE When he does go out, it's to a club or dinner - with his new wife - friends, celebrities, sports figures - never O.C. guys.
Richie sits in his car across from Small's where bouncers keep out people like him.
Frank, Ana, Wilt Chamberlain and his wife emerge from the restaurant together.
RICHIE Sundays he takes his mother to church.
RICHIE Then drives out to change the flowers on Bumpy's grave.
RICHIE Every Sunday, no matter what.
Frank's mother tearfully watches her son slip a ring onto Ana's finger next to the fat engagement diamond - before Ana, in turn, puts a gold band on Frank's.
The minister pronounces them husband and wife, the veil is lifted, and they kiss to great applause -
As a photographer takes the official photograph of the wedding party on the steps of the church -
Lou Toback looks from a surveillance photo of the wedding party in his hands, to Richie's Table of Organization: The Lucas brothers and cousins - in the streets of New York and New Jersey, arranged in some imagined hierarchy.
TOBACK Not your typical day in the life of a dope man, Richie.
RICHIE Neither was Bumpy Johnson's and he owned Harlem.
TOBACK You think Frank Lucas took over for Bumpy Johnson?
TOBACK His driver?
TOBACK That's a little far-fetched.
RICHIE Is it?
RICHIE Everything he does, he does like Bumpy.
TOBACK Bumpy never wore a chinchilla coat in his life.
RICHIE We haven't seen that again.
RICHIE That apparently has been retired to the closet.
Frank and Charlie look on as Ana throws the bouquet.
CHARLIE She's the most beautiful bride I ever saw, Frank.
FRANK I wish Bumpy could've met her.
FRANK I wish she could've met him.
Looking at the Lucas Table of Organization -
TOBACK What do you got on him you can use in court?
TOBACK Because this isn't it.
TOBACK You try this without informants and powder, no one's going to jail.
RICHIE Won't get any informants.
RICHIE Not inside.
RICHIE It's like a Sicilian family.
RICHIE Like he's structured his own family the same way to protect himself.
Exactly like one, like a scene from The Godfather as Frank dances with Ana before the reception guests.
RICHIE Being with Bumpy long as he was, he would have been around Italians a lot.
RICHIE Enough to learn that much.
Rice rains down on the bride and groom as they climb into the back of the Towncar.
Doc comes around to the driver's side, gets in and slowly pushes through the crush of guests waving and throwing kisses.
RICHIE But it's not even Frank Lucas I want.
RICHIE I want to know who he's working for: Which Italians are bringing the heroin in.
Flanked front and rear by Frank's security, the marriage car moves along a rain-slick street.
The newlyweds cuddle in back.
Another car pulls up alongside - Trupo's Shelby - and Doc's right hand instinctively comes off the steering wheel to settle on his holstered gun.
Trupo smiles and shakes his head, no.
The Lincoln and security cars and Trupo's Shelby parked.
FRANK Stay in the car
FRANK As Frank and Doc climb out, Frank motions to his other security men to remain calm, he'll handle this.
TRUPO Hello, Frank.
TRUPO If Frank is surprised Trupo knows his name, he doesn't show it, or anything else except an air of professional courtesy.
FRANK Detective.
FRANK Trupo looks in at Ana in the back seat, smiles at her.
FRANK She turns her head away and closes the door.
FRANK Trupo leads Frank away for a private conversation -
TRUPO You sure you done the right thing?
TRUPO She's a beautiful girl - there's no question - but she's got an attitude on (her) -
FRANK Listen to me.
FRANK Before you say another word - about her - or me - remember that you're saying it on the most important fuckin day of my life.
TRUPO Man walks around in a fifty thousand dollar chinchilla coat and he never even bought me a cup of coffee?
TRUPO Something wrong there.
FRANK I don't know what you're talking about.
TRUPO You pay your bills, Frank?
FRANK You want to keep talking, talk to my lawyer, here's his card.
FRANK You call him, because we're done here -
TRUPO Do you pay your bills, I asked you.
FRANK If you're not getting your share, it's not my fault, go ask the chief of police.
TRUPO What's my share?
TRUPO You don't even know me.
TRUPO Maybe I'm special.
FRANK No, you're all the fuckin same.
TRUPO What does that say?
TRUPO Special - Investigations - Unit.
TRUPO See that word there?
TRUPO "Special."
TRUPO Ten grand, first of each month, delivered here.
Frank ignores the card, stares at Trupo like he's a fool.
FRANK Detective ...
FRANK There are some things you don't do.
FRANK This is one of them.
FRANK Not on a man's wedding day.
Frank's resolve throws Trupo off his rhythm.
He manages:
TRUPO Have a nice honeymoon.
Frank doesn't carry Ana across the threshold.
He strides in leaving her at the front door, throws a match in the gas fireplace, comes back from the bedroom a moment later with the $50,000 chinchilla coat and throws it on the flames.
A march on Washington, protesting the war (archive).
INT. JIMMY RACINE'S APARTMENT - NIGHT The report continues on a TV here as Teddy's driver, Jimmy Racine, yells at his girlfriend -
JIMMY Where is it?
DARYLYNN Fuck you, I'm not telling you.
DARYLYNN She comes past the TV and into the kitchen past a table covered with dope paraphernalia.
JIMMY Where is my fuckin dope?
JIMMY You and your girlfriends take it again?
JIMMY I'll fuckin kill you.
JIMMY She yanks open a drawer, grabs a knife and slashes it at him.
JIMMY He grabs a gun and she runs for the stairs -
He chases her into the street, yelling, raises the gun and fires, and she goes down, clutching at her butt, moaning -
Moaning here, too.
Richie's lawyer-ex-girlfriend, in bed with him.
SHEILA Richie, yes, fuck me like a cop, not a lawyer -
SHEILA Oh, God, Richie, no - don't answer it -
SHEILA No, no, no -
RICHIE Yeah -
SPEARMAN V/O PHONE Richie.
SPEARMAN V/O PHONE Newark just picked up one of the celebrities on our Wall of Fame: Teddy's driver.
SPEARMAN V/O PHONE For attempted murder.
Richie's had Jimmy Racine brought over.
Sits with him as the Three Amigos watch from the shadows.
Just coming off his high, and the attempted murder, Jimmy looks disoriented as he sits in cuffs in the dungeon-like basement.
RICHIE Because it's an attempted homicide, that's Grand Jury.
RICHIE Now, that Grand Jury could come in very favorably.
RICHIE Might turn out to be Attempted Manslaughter.
RICHIE Self Defense even.
RICHIE She had a knife.
RICHIE Depends on how I want to deal with you.
RICHIE You see where this is going.
RICHIE Jimmy looks around at the basement dungeon with concern.
JIMMY The fuck is this place?
RICHIE Let's say you beat it somehow.
RICHIE What do you think Cousin Frank'll think of that?
RICHIE He knows you had to sit here listening to something like this.
RICHIE And then you beat an attempted murder?
RICHIE Is he stupid?
RICHIE He'll assume you talked.
RICHIE Jimmy can easily imagine that scenario and it frightens him.
RICHIE You fucked up, Jimmy.
RICHIE But nobody knows.
RICHIE Frank doesn't know.
RICHIE Yet.
RICHIE Do you want him to read about it in the paper?
RICHIE Or do you want to walk out of here - no bail, no trial - just walk out, now.
Jimmy has thought about it all night and walks out of the building into the chilly morning air.
RICHIE V/O Jimmy?
RICHIE V/O Look at me -
RICHIE V/O Jimmy looks over his shoulder as if Richie just called to him from it, which he didn't.
RICHIE V/O There's no one in sight -
RICHIE V/O Any time I want to change my mind?
RICHIE V/O I don't like the quality of your work?
RICHIE V/O I can find a witness saw you shoot your girlfriend.
RICHIE V/O It just took me a while.
RICHIE V/O I even know what he'll look like.
RICHIE V/O He'll look just like you.
Teddy's car comes around a corner and down the street.
Jimmy Racine, wired, looks in the rear view mirror at Teddy in the back seat, and, behind him, Richie's car following.
Richie keeps Teddy's car in view ahead.
Glances in his mirror at the cars following him.
His detectives.
The detectives' cars parked behind a warehouse.
Richie peers into binoculars at: Teddy's car parked by Frank's outside another warehouse loading dock.
Frank gets out, discusses something with his brother, comes past Jimmy to some men in bloody white coats.
He talks to them, returns to his car, takes a valise from the trunk.
He snaps it open revealing stacks of cash, hands it over and walks to a semi-truck, glancing once in Richie's direction.
Though he can't see anyone there he gives a wave to them - or is it to the truck driver to pull out -
Like Bumpy used to do every Thanksgiving, Frank and his brothers, from the back of the truck, hand out hundreds of freshly-butchered turkeys to the poor.
Frank, in an apron, carries in a huge cooked turkey as the extended Lucas family gathers around the table.
It's like Norman Rockwell painting -
Another Thanksgiving picture: addicts shooting up and nodding out in alleys and dingy rooms.
Tight on needles, veins, spoons, filth -
Richie alone at his kitchen table with a sandwich and a beer.
The Macy's parade plays silently on his TV.
A doorbell summons Trupo.
He comes through his entry.
Opens the front door.
Finds no one there - except a large live turkey on the doorstep.
He stares at it nonplussed, then looks up to a sound - a whoosh - as flames engulf the interior and spit out the windows of his Shelby Mustang ...
The big knife in Frank's hand slices into the turkey and lifts meat onto a plate that's passed from hand to hand, the family engaged in several conversations at once, laughing -
Bathroom.
Jimmy Racine, shirt off, wired, changes the batteries of the little tape recorder.
Jimmy comes out, tries to take a chair not too far from Frank who's watching his nephew toss pop-up flies for the younger kids to catch.
FRANK Stevie.
FRANK Come over here.
FRANK I heard you didn't show up.
FRANK (CONT'D) You're too busy to meet with Billy Martin?
FRANK (CONT'D) After I set it up?
FRANK (CONT'D) Stevie shifts around, not wanting to make Frank mad ...
STEVIE I don't want to play pro ball, I decided.
FRANK What're you talking about?
FRANK This is your dream since you were their age -
FRANK Maybe I can set it up again.
FRANK Stevie just stands there, uncomfortable.
FRANK Finally -
STEVIE It's not what I want.
STEVIE I want to do what you do, Uncle Frank.
STEVIE I want to be you.
STEVIE Frank stares at him unhappily.
STEVIE Teddy comes over but Frank barely notices.
TEDDY We got a problem.
Jimmy Racine behind the wheel.
Frank and Teddy in back, speaking quietly.
TEDDY He's been cutting it so much it's down to two, three percent pure.
FRANK You tested it.
FRANK You're sure.
FRANK Teddy nods.
FRANK Frank notices Jimmy looking at them in the rear view mirror.
FRANK The fuck you looking at?
The car pulls up in front of a building in the clothing district.
Jimmy stays while Teddy and Frank go inside.
Jackie's club looks like a set from a blaxploitation film.
Frank and Teddy, led by a bodyguard, come past some turkey carcasses and other remnants of Thanksgiving to where Jackie and a couple friends cavort with some naked girls.
JACKIE Frank.
JACKIE Welcome.
FRANK We need to talk.
JACKIE Great.
JACKIE Girls, get out.
JACKIE The girls gather their things and leave.
JACKIE Frank wipes at a modern leather chair with his handkerchief, throws it away, sits.
JACKIE Jackie lays out a couple lines, offers Frank a rolled up hundred dollar straw.
JACKIE Frank shakes his head, no thanks.
JACKIE You talked to Charlie.
JACKIE You want to hear more about my Black Coalition.
JACKIE Let me explain it to you -
JACKIE But first, let me suck up a line of coke -
FRANK That's not why I'm here.
FRANK (Jackie glances up from the powder.
FRANK No?)
FRANK Everybody's happy, Jackie.
FRANK Charlie, Baz, the cops, the Italians, everybody.
FRANK Everybody except you.
JACKIE I'm happy.
FRANK Then I don't understand.
FRANK Why do you have to take something that's perfectly good the way it is, and wreck it?
FRANK Jackie doesn't seem to understand.
FRANK Brand names mean something, Jackie.
FRANK Consumers rely on them to know what they're getting.
FRANK They know the company isn't going to try to fool them with an inferior product.
FRANK They buy a Ford, they know they're gonna get a Ford.
FRANK (CONT'D) Not a fuckin Datsun.
FRANK (CONT'D) Blue Magic is a brand name; as much a brand name as Pepsi.
FRANK (CONT'D) I own it.
FRANK (CONT'D) I stand behind it.
FRANK (CONT'D) I guarantee it and people know that even if they don't know me any more than they know the chairman of General Foods.
JACKIE What the fuck are you talking about, Frank?
FRANK What you're doing, as far as I'm concerned, when you chop my dope down to five percent, is trademark infringement.
FRANK That.
FRANK That's what this is about.
FRANK Jackie nods, but -
JACKIE With all due respect, Frank, if I buy something, I can do whatever I want with it.
FRANK That's not true.
FRANK That's where you're wrong.
JACKIE If I buy a car, I can paint it, God damn it.
FRANK Jackie, you don't need to.
FRANK You don't need to make more money than you can with Blue the way it is.
FRANK No one does.
FRANK At a certain point it's just greed.
JACKIE What do you want, Frank?
JACKIE You want me to call it something else?
FRANK I have to insist.
FRANK You call it Blue Magic, that's misrepresentation.
JACKIE Fine.
JACKIE I'll call it Red Magic, even though it doesn't sound as good.
FRANK That's all I'm saying.
FRANK Wrap it in red cellophane and -
JACKIE Pink Magic.
JACKIE Black Magic -
FRANK Whack it down to nothing, tie a bow around it and call it Blue Dogshit if you want, just don't let me catch you doing this again.
FRANK Jackie regards Frank for a long moment ...
JACKIE Catch me?
JACKIE Insist?
JACKIE Infringement?
JACKIE I don't like these words as much as please - thank you - sorry to bother you, Jackie.
JACKIE These are better words to use you come into my place without an invitation.
JACKIE Jackie waits to hear a kinder word but Frank doesn't offer one.
JACKIE Jackie nods, Fine, okay, but it's more like a warning.
Frank pulls a girl off Teddy's lap and points him toward the door.
Jackie watches them leave.
They emerge from the building to where Jimmy waits.
TEDDY Give me the keys; take a cab home.
Frank and Teddy driving in silence.
Eventually -
FRANK You don't go over there any more.
FRANK Teddy doesn't like it, but nods.
FRANK Suddenly his face is illuminated by light reflecting in the rear view mirror, an unmarked police car behind them, flashing its brights.
FRANK It's all right, pull over, what are they going to do?
FRANK Give us a ticket?
FRANK But Teddy isn't as calm as he begins to pull over.
As Trupo and his partner climb out of their car and approach Teddy's -
TEDDY Frank?
TEDDY Some of it's in the trunk.
TEDDY Frank regards him with utter disbelief.
TEDDY Teddy shies as if he expects to get hit.
TEDDY The SIU detectives arrive.
TRUPO Hello, Frank.
FRANK Detective.
FRANK How's it going?
FRANK You have a nice Thanksgiving?
TRUPO I did not, as a matter of fact.
TRUPO Get out of the car.
TRUPO The Lucases climb out.
FRANK Where's the Shelby?
TRUPO The Shelby's gone, Frank.
TRUPO Trupo reaches in the driver's side window, takes the keys from the ignition and comes around to the trunk.
TRUPO Frank and Teddy exchange a glance as it opens.
TRUPO Silence.
TRUPO Then -
TRUPO Want to come over here a minute, Frank?
TRUPO Six kilos of heroin are illuminated by the trunk light.
TRUPO Frank and Trupo regard it in silence.
TRUPO Then -
TRUPO Now what are we gonna do about this?
FRANK We're gonna shut the trunk and say good night, forget you pulled us over.
TRUPO I got a better idea.
TRUPO Trupo reaches into the trunk, picks up two of the heroin bricks, tucks them under his arm and looks at Frank -
TRUPO Or would you rather I took it all and threw you and your brother in the fuckin river?
FRANK I don't know, would you rather it's your fuckin house blows up next time?
FRANK They hold each others' stare for a long moment.
TRUPO I loved that car.
FRANK I know.
FRANK Trupo closes the trunk and walks away with his cut of the heroin, calling to his partner -
TRUPO Let's go.
TRUPO As the SIU cops walk to their car, the perspective shifts, through binoculars: Richie watching.
From outside the driver's side, Teddy's head, inside the car, suddenly smashes against the window, cracking it.
His groan is interrupted by Frank's muffled voice -
FRANK Don't you ever put me in a car with dope in it.
Richie comes in, opens the fridge and stares in, his mind elsewhere.
A ringing phone pulls him out of it.
RICHIE Yeah.
RICHIE Tony.
RICHIE How's it going?
Tony's wife and daughters can be seen in the suburban backyard.
Here in the kitchen Tony and Richie watch kernels of popcorn bounce off the inside walls of the first Amana microwave oven.
It's noisier than modern ones.
RICHIE The fuck is a `micro' wave?
TONY It's a scientific force like atomic energy.
TONY It rearranges the molecules.
RICHIE Of what.
TONY Of anything.
TONY Of popcorn.
TONY You don't want to put your head in there.
TONY Tony rakes out the plain, `pre-microwaveable' popcorn, using his hand.
TONY Gives some to Richie.
TONY Half of it's burnt.
TONY I can get you one of these.
TONY Just like this, brand new.
TONY I'll have it delivered.
RICHIE No, thanks.
RICHIE I don't want one.
RICHIE Tony hands Richie some snapshots: The Zaca family on the slopes of a resort, and in and outside a beautiful snow- dotted cabin.
RICHIE This is nice, where's this?
TONY Aspen.
TONY Just got back.
TONY Had a great time.
RICHIE I'd like to ski Aspen some day.
TONY Know who we met?
TONY Burt Reynolds.
TONY I'm not kidding.
TONY Lot of people from Hollywood go up there now, buying up everything.
RICHIE This is your place?
TONY Are you kidding?
TONY You know what it's worth?
TONY Ski-in-ski-out, five bedrooms, sauna, everything.
TONY We were guests.
TONY No ...
TONY No, that's your place.
TONY Everything seems to stop.
TONY Richie becomes aware of the sounds around them, the girls splashing around outside ...
TONY Isn't there something we can do - about leaving the big guy alone?
TONY You know who I mean.
TONY What Richie knows is that no matter what he does or says at this point he's got a problem.
RICHIE If I don't report what you just said to me, you know I could be in a lot of trouble.
RICHIE If I do, then it's you.
TONY I'm hoping you won't do that.
TONY Richie considers the room itself, measuring the odds of microphones and a recorder being in it somewhere.
TONY I'm not taping it.
TONY How do you know?
TONY Because we're friends and I'm telling you.
TONY This is a real offer.
RICHIE From who, your uncle?
RICHIE Why would you do this?
RICHIE Why would you risk our friendship?
TONY Because I care what happens to you.
RICHIE You shouldn't have done it.
TONY I had to.
TONY I had no choice.
TONY Neither do you.
TONY Leave Frank Lucas alone.
RICHIE He's not important enough for you to do this.
TONY Yes, he is.
TONY Richie stares at Tony, then puts the pictures in his hand.
RICHIE Tell Marie I'm sorry I had to leave.
RICHIE You can tell her why.
Alone in the empty building, he stares at the T.O.: The higher echelon Italians like Tosca; lower echelon Harlem guys like Charlie Williams and Frank Lucas.
He gets up then, untacks Frank's photograph from its lowly position and moves it to a place no black has ever occupied - to the top of the pyramid - above the mafia.
Toback regards Frank's picture at top of the Lucas T.O.
RICHIE INS, FBI, IRS - I can't get anything out of them.
RICHIE Nothing on his travel, his bank accounts, property holdings - nothing.
TOBACK That's because they all think you're on the take and you think they are.
RICHIE They don't want this to stop.
RICHIE It employs too many people.
RICHIE Cops, lawyers, judges, probation officers, prison guards.
RICHIE The day dope stops coming into this country, a hundred thousand people lose their jobs.
RICHIE Toback isn't as sure the corruption of the official world is that complete.
SPEARMAN Richie.
SPEARMAN Excuse me.
SPEARMAN Spearman gestures to a couple of men in suits who want to talk to him.
Richie and Tobacke regard the two stone-faced FBI agents -
RICHIE Who took it out?
RICHIE If there's a contract on me, it would be nice to know who took it out.
FBI AGENT We can't say without compromising our source.
FBI AGENT You understand.
RICHIE No.
RICHIE I don't.
RICHIE Not when it's my life.
FBI AGENT If you want, we can assign someone to you.
RICHIE Who?
RICHIE FBI?
RICHIE You're going to protect me?
RICHIE Richie almost laughs at the thought, looks to Toback.
RICHIE In fact, none of this is funny.
Walking toward his apartment down its dark street, bag of groceries in arm, Richie becomes aware someone is following him.
He slows to let the figure get closer, closer, then turns fast, drops the guy and puts a gun to his head.
MAN Don't shoot!
MAN For God's sake.
MAN Richie keeps the gun pressed against the guy's forehead.
RICHIE Talk.
MAN Are you Richard Roberts?
MAN I got a subpoena.
Richie and Laurie sit with their respective lawyers, waiting for the judge to appear.
He leans over -
RICHIE Laurie.
RICHIE I'm sorry I couldn't give you the kind of life you wanted.
RICHIE I'm sorry it was never enough.
RICHIE But don't punish me for being honest.
RICHIE Don't take my son away.
RICHIE She stares at him in disbelief.
RICHIE Then responds in a louder voice than his -
LAURIE What are you saying?
LAURIE That because you were "honest" and didn't take money like every other cop, I left you?
LAURIE The bailiff looks over, but she doesn't care.
You don't take money for one reason: to buy being dishonest about everything else.
And that's worse than taking money nobody gives a shit about - drug money, gambling money nobody's gonna miss.
I'd rather you took it and been honest with me.
Or don't take it, I don't care.
But don't then go cheat on me.
Don't cheat on your kid by never being around.
Don't go out and get laid by your snitches and secretaries and strippers.
I can tell just by looking, she's one of them.
His lawyer.
Which is true.
Everyone's watching them now.
LAURIE You think you're going to heaven because your "honest."
LAURIE You're not.
LAURIE You're going to the same hell as the crooked cops you can't stand.
BAILIFF All rise -
The same judge who sends a collection plate around sits before Richie and Laurie and their attorneys.
SHEILA Your honor, a lot has been said here today about how unsavory Mr. Roberts' environment is for a child.
SHEILA How dangerous it is.
SHEILA I'm sorry, but this is our world.
SHEILA This is where we live and we tell him, Protect us.
SHEILA We give him that responsibility, and then say, Oh, but we don't trust you to raise a child.
SHEILA We don't think you're fit for that.
RICHIE I'm not.
Silence.
Sheila looks at him, but he's looking at Laurie, and speaks to her like they're alone in the room:
RICHIE You're right.
RICHIE This is no place for him.
RICHIE Around me.
RICHIE Take him.
RICHIE The further away the better.
RICHIE For him.
The lights on the Rockefeller Christmas tree blink on to applause.
A carol begins and continues over:
Seats covered with Christmas presents.
Doc, driving, sees Trupo's car parked out front Frank's penthouse.
DOC Frank -
FRANK Yeah, I see them.
FRANK Doc pulls to the curb outside Frank's building.
FRANK As the doorman helps Doc with the big Christmas tree tied to the roof of the car, Frank crosses to Trupo's car with a couple of bottles of Crystal tied with holiday bows.
FRANK Here you go, boys.
FRANK Merry Christmas.
Charlie has come to visit.
A Christmas carol plays as Frank strings the tree with some lights.
FRANK Paying cops is one thing, I understand that.
FRANK I been paying them since I was ten - put more of their kids through college than the National Merit Award.
FRANK This is different, this Special Investigations Unit.
FRANK They think they are special.
CHARLIE They're fucking crooks.
CHARLIE No code of ethics.
CHARLIE Frank plugs the cord in and the tree lights up.
FRANK Someone's been following me.
FRANK Besides cops.
FRANK I see cars where they shouldn't be.
FRANK Guys I don't know -
CHARLIE Me, too.
They regard each other.
The carol continues over:
Ana hangs tinsel on the tree as Frank gives the shepherd some dog toy presents he's bought.
More to himself:
FRANK Bumpy hardly ever went out at a certain point.
FRANK He stayed in - read - watched TV - played chess.
FRANK I thought he chose to lead a quiet life.
FRANK He didn't.
FRANK He couldn't go out without something happening.
ANA We can still go out.
FRANK Where?
FRANK With who?
FRANK Everyone I know is under surveillance.
FRANK I can't even be with my family at Christmas anymore.
FRANK He gets up, pets the dog, and looks out the window at Christmas angels stretched across the street, at people on the sidewalk, wondering perhaps which of them are undercover cops, at Trupo's car, still parked outside.
ANA Why don't you just pay who you have to pay?
FRANK I do pay them, I pay them all.
FRANK Cops, accountants, lawyers, who don't I pay?
FRANK Everybody.
FRANK I pay them a fortune, it doesn't matter.
FRANK It doesn't satisfy them.
FRANK The more you pay, the more they expect.
FRANK (CONT'D) You can't start with them because they can't stop.
FRANK (CONT'D) It's like dope.
FRANK (CONT'D) They always want more.
FRANK (CONT'D) Ana looks vulnerable.
FRANK (CONT'D) Frank almost feels bad that it's his life and problems that have put them here.
FRANK (CONT'D) Eventually, to try to turn it around -
FRANK Put on something nice, we're going out.
Frank and Ana emerge from a service elevator, come down a dark hall and out the back door to an alley to where Doc waits with the car in the falling snow.
Frank's car approaches Small's just as Jackie, with a Santa Claus hat on, climbs out of a sky blue Bentley with his entourage.
Frank groans to Doc -
FRANK Keep going.
DOC Around back?
FRANK Fuck that.
FRANK I'm not going to sneak into my own club.
FRANK Just drive.
Waiting for a take-out order under harsh fluorescent lights -
ANA I'm going to wait in the car.
DOC Go ahead, Frank.
DOC I'll wait for it.
FRANK You can carry it all?
FRANK We ordered a lot.
FRANK Doc nods, go on, go with Ana.
FRANK Frank hands him a couple twenties.
FRANK Ana's already outside.
FRANK Don't forget the yellow sauce.
Ana's half a block ahead, waiting outside the locked car by the time Frank arrives and realizes -
FRANK Doc's got the keys.
FRANK Let's go back.
ANA The lights give me a headache, you go.
FRANK I'm not leaving you on the street.
ANA Get the keys, Frank, it's cold.
ANA He starts back through cascading snow.
ANA Notices a car coming slowly down the street -
The cook dumps sizzling vegetables into a take-out container and puts it in a bag -
The car passes, continues to the end of the block, turns the corner.
Doc hands over money, waits for his change -
DOC Gimme some of that yellow sauce.
Frank sees the car again, coming around the corner, walks briskly back to where Ana waits.
The car is almost upon them as he grabs her by the wrist and pulls her hard along the sidewalk.
The car guns its engine -
As Frank pushes in past the doors with Ana, the windows explode.
They dive to the floor, bullets ripping through the place.
Doc draws his two guns and fires back at the car, hitting it a couple times as it screeches off.
He gathers Ana and Frank off the floor like a presidential bodyguard, hustles them out to the car.
Frank's shoulder is bleeding.
DOC You hit?
FRANK What the fuck was that?
FRANK They pile in and Doc screeches away from the curb.
Heavy security in the hallways: Frank's own men and some cops he's got on the payroll.
Ana steps from the elevator and hurries past, early edition New York paper in hand.
The brothers watch as a private doctor attends Frank's wounds.
He seems all right fine except for the fact that someone had the fucking nerve to take a shot at him - and Charlie he sees in the newspaper - gunned down, dead, lurid Weegee-like photo of him on the front page.
TEDDY Was it Jackie?
TEDDY I'll fuckin kill him whether it was or not, you tell me to.
TEDDY What do you want us to do, Frank?
TEDDY We can't just sit here and -
FRANK Who didn't like Charlie?
FRANK Everybody liked Charlie ...
ANA Who shot at us?
ANA It doesn't matter.
ANA We're leaving.
She pulls a drawer open.
Takes out their passports.
Begins packing.
The brothers watch, not sure what to do, or say.
To them -
FRANK Go home.
FRANK Go see your kids.
FRANK He obviously wants to talk to Ana alone.
FRANK Pulls away from the doctor.
FRANK They all leave.
FRANK Ana keeps packing.
FRANK What are you doing?
FRANK Where've you been?
ANA We're leaving from here.
ANA Money's in the car.
FRANK What money?
ANA Everything from your mother's house.
FRANK In your car?
ANA Yes.
FRANK Where's the car?
ANA Out front.
FRANK With ten million dollars in it?
ANA I didn't count it.
FRANK Are you crazy?
FRANK Take it back to Teaneck.
FRANK What are you doing driving around without security?
FRANK Doc'll take you back.
ANA We're not going there, we're going to the airport.
ANA We're leaving the country.
FRANK To go where?
FRANK No, we're not.
ANA Frank, Charlie's dead.
ANA They tried to kill us.
ANA What else has to happen - ?
ANA He grabs her and holds her to calm her down.
FRANK Shhh.
FRANK Come on, now.
FRANK Shhh.
He holds her close, waits for her breathing to slow before:
FRANK Where are we going to go?
FRANK Spain?
FRANK China?
FRANK Which fuckin place is it going to be?
ANA We can go anywhere we want.
ANA We can live anywhere.
FRANK We can run and hide is what you're saying.
FRANK He slowly shakes his head: that's something he'll never do.
FRANK This is where I'm from.
FRANK This is where my family is.
FRANK My business.
FRANK My mother.
FRANK This is my place.
FRANK This is my country.
FRANK This is America.
The Statue of Liberty in morning light and mist rises from the waters of the Hudson River.
Richie, at his desk, looks up to see Trupo walking through the squad room, followed by Spearman.
SPEARMAN Said he'll only talk to you.
Trupo's attitude has completely changed from the first time they met.
He talks to Richie now like a fellow conspirator -
TRUPO From what I hear, it was the Corsicans.
TRUPO The French Connection, Fernando Rey, the exporters Frank has put out of business.
TRUPO Now, I can take care of him in New York, but I don't want to have to worry every time he drives across the bridge to Jersey someone's gonna take another shot at him.
TRUPO Richie gives nothing away even as it stuns him that Trupo would speak to him this blatantly.
TRUPO We need to start working together.
TRUPO We need to step up our efforts.
TRUPO Next time their aim could be better.
TRUPO We need to keep this cash cow alive.
TRUPO Jimmy Racine comes in - sees Trupo - and leaves - but not before Trupo has seen him.
TRUPO And now he sees the Lucas Table of Organization he didn't notice when he came in.
TRUPO Gets up and walks over to it now and takes a closer look.
TRUPO Sees Frank's picture at the top, like Enemy Number 1.
TRUPO Jesus.
TRUPO What the fuck you doing here?
TRUPO You actually going to arrest Frank Lucas?
TRUPO What's the matter with you?
RICHIE I'm crazy.
RICHIE Can't you tell that?
RICHIE I'm crazy enough to shoot someone and make it look like an accident next time he comes over the bridge without my permission.
RICHIE Get the fuck out of New Jersey.
RICHIE They regard each other a moment before Trupo turns to leave.
A large TV shows chaotic scenes in Saigon.
The US is pulling out of Vietnam.
Tosca has come to see how Frank is recovering, and finds him, agitated, too long in bed even though it's only been a day, changing into a nice shirt, putting on his shoes -
FRANK "I can guarantee you peace of mind," you said.
FRANK Do I look like a man with peace of mind to you?
FRANK They shot at my wife.
FRANK Who does that?
FRANK (CONT'D) Who was it, which one of your people?
FRANK (CONT'D) I'll take that gun away and shove it up their ass.
TOSCA I don't know that it was any of them, Frank.
TOSCA Neither do you.
FRANK Then maybe I'll kill them all just to make a fuckin point.
FRANK Tosca seems more philosophical about it - like Bumpy might have been - but it wasn't him who was shot at.
TOSCA You want to know who it was?
TOSCA I can tell you.
TOSCA It was a junkie.
TOSCA Or a rival.
TOSCA Or some dumb ass kid trying to make a name for himself.
TOSCA Or someone you forgot to pay off.
TOSCA Or slighted without realizing it.
TOSCA Or someone you put out of business by being too successful.
TOSCA Success has a lot of enemies.
TOSCA Your success is who took a shot at you.
TOSCA How you gonna kill it?
TOSCA By being unsuccessful?
TOSCA You can be successful and have enemies, or unsuccessful and have friends.
TOSCA It's the choice we make.
A call has interrupted Nate's massage (and later activities) with a bevy of Thai girls.
He wraps himself in a robe, takes the phone.
NATE Hello?
Frank on a pay phone in a comfortable alcove with a stack of quarters.
Other guests are gathered around a TV in the lounge that shows images of helicopters plucking diplomats off the roof of the American Embassy in Saigon.
FRANK I'm watching the news.
FRANK Where the hell's everyone going?
NATE Home.
NATE The war's over.
FRANK Just like that?
FRANK We're going to leave the fuckin country to the communists?
NATE We been here since 1961, Frank.
FRANK I haven't!
Frank and Nate and their "army" of black servicemen and Thai thugs wind through the jungle with pack mules.
The same farm and hut as before.
Frank and the Chinese General sip tea.
The four million dollars in cash Frank brought sits on the table.
GENERAL Opium plants are hearty enough to outlive any war.
GENERAL They'll still be here long after the troops are gone.
GENERAL But what are you going to do for transportation when the last US plane goes home?
FRANK I'll figure something out.
FRANK You'll see me again.
FRANK The General seems fond of Frank, and not only because of all the money on the table.
GENERAL It's not in my best interest to say this, Frank ...
GENERAL but quitting while you're ahead is not the same as quitting.
FRANK That's what my wife thinks.
GENERAL But you don't think she's right.
GENERAL Frank doesn't say.
Mules are loaded up with burlap bags containing 3,000 kilos of heroin.
The mule train approaches the jungle that surrounds the opium farm.
Nate's Thai thugs, left behind in sniper positions in the trees, stand ready to open fire if they have to as Frank, Nate, the soldiers and mules pass below.
They seem to have made it, winding back down through the jungle with the mules.
Suddenly a barrage of gunfire erupts from the trees - a couple of Nate's men are hit as the rest dive for cover, shouting "Vietcong," and returning the fire.
Frank drops down from his mule, gets a pistol out and shoots into the trees.
Bullet-severed palm fronds rain down.
FRANK Give them half!
FRANK Nate, pinned down by the mules, can't hear him over the noise.
FRANK Cut half of them loose!
FRANK The mules!
FRANK Nate cuts the mule-train tether in the middle, slaps at the animals.
FRANK As the freed mules disappear into a wall of trees the shooting subsides, then stops altogether.
FRANK Smoke from all the gunfire rises like mist around the half dozen Thais and Americans lying dead on the ground.
Teddy makes out with a girl in the back seat of his car.
The pay phone just outside on the corner rings, and he gets out, steps past Jimmy, answers it -
A Thai singer attempts Otis Redding on the little stage.
Frank, at a table here, with a drink and a phone.
FRANK Newark.
FRANK Short Term Parking Lot 3.
TEDDY V/O When you need it?
TEDDY V/O Today?
FRANK Tomorrow will be fine.
Jimmy loiters close enough to the open pay phone, to hear Teddy's side of the conversation.
TEDDY Short Term Lot 3.
TEDDY This the Mustang were talking about ...
TEDDY Camero?
TEDDY ...
TEDDY What's the plate number?
TEDDY Yeah, I got it ...
TEDDY I got it, Frank ...
Jimmy's come over to share his news with the detectives.
But Richie isn't pleased with it - or with Jimmy.
ABRUZZO There's no Short Term Lot 3 at Newark.
ABRUZZO They're lettered, A, B, C, D -
JIMMY I'm just telling you what I heard -
ABRUZZO Then you heard wrong!
ABRUZZO Jimmy shies back a step in case Abruzzo takes a swing.
SPEARMAN Maybe he means the time?
SPEARMAN 3 o'clock?
JONES And this isn't a Jersey plate.
JONES Or New York.
JONES Not with just two letters.
JONES It's three and three, not two and three -
JIMMY It's what he said -
JONES Then what the fuck is it -
JIMMY The fuck should I know -
ABRUZZO You're fuckin lying -
JIMMY It's what he said.
JIMMY I'm sure.
JIMMY Yes!
JIMMY Silence.
JIMMY They all look at each other.
JIMMY After a moment -
RICHIE None of you ever been in the service?
RICHIE It's an Air Force tail number.
The plane, with that tail number, descends through clouds.
Richie's entire staff of detectives, along with Toback, the DA and several customs agents, stand on the tarmac, watching the military plane taxiing toward them -
Quiet sounds of suburban domesticity - chirping birds, a distant lawn mower -
The cabin door slides up, the passengers begin emerging: Military officers, embassy personnel and families.
Richie's detectives and Toback watch him with concern as the official passengers, met by a bevy of assistants, file past -
The kitchen.
Frank's mother shows Ana some old photographs of Frank as a boy as they sip coffee.
There's a tap on the glass French door.
The women look up and see Trupo just outside it, and other police moving past.
He waves.
An Army captain approaches Richie's law enforcement group.
RICHIE Captain, I'm Richard Roberts, Director of the Essex County Narcotics Bureau.
Front door.
Trupo sort of waves a search warrant at Julie as invites himself in.
The NY cops follow, fan out.
Trupo and his detectives head upstairs -
The plane has been brought into a hangar where it's being taken apart like a car stripped by thieves.
Inside the cabin, seats are removed and inspected, carpeting pulled up, panels unscrewed, lavatories dismantled.
Downstairs - Ana and Frank's mother, guarded, can hear Trupo and his detectives, upstairs, ransacking a bedroom.
Upstairs - the SIU detectives pull open drawers, throw clothes from the closets.
Trupo picks up an invitation to a United Nations ball, tosses it down again.
Finds a safety- deposit box key in a sock drawer, puts it in his pocket.
The engines and landing gear are disassembled, the tires opened up and searched.
A nozzle plunges into a toilet and pumps out the contents into barrels detectives fish through with gloved hands -
Ana is taken upstairs, brought before the SIU detectives who wait for the NYPD cops to leave the room.
The place has been torn apart.
TRUPO Your husband's illustrious career is over.
TRUPO The Feds are going to come in and take it all.
TRUPO Everything.
TRUPO But not before I get my gratuity.
TRUPO Where's the money?
ANA There was some on that dresser, but it's gone now so I guess you (took it) -
TRUPO The money!
TRUPO The getaway money Frank and every other gangster keeps in his house!
ANA If you leave now, there's a chance Frank might not kill you -
ANA Trupo slaps her hard across the face -
Richie, off by himself, watches with a growing sense of panic as the mechanics, detectives and customs agents begin removing the metal skin from the plane.
Coffins are being off-loaded.
Downstairs, Mama Lucas puts washcloth on Ana's swollen cheek.
They can hear the search continuing upstairs: things being ripped from the walls, the walls themselves splintered apart with sledgehammers, glass breaking.
To Mama Lucas -
ANA I'm sorry.
They've looked everywhere and found nothing.
The plane, in fact, hardly resembles a plane anymore - no panel left that hasn't been removed, no cavity not probed - except -
Richie's glance settles on the military caskets as they're loaded onto a truck, armed soldiers standing guard -
Frank's bedroom has been destroyed.
Trupo, standing at a window glances out at the sound of a barking of a dog to see Frank's German shepherd down in its kennel.
Richie gets up slowly and approaches the coffins as -
Trupo crosses the lawn toward the kennel and barking dog -
Richie stands over the nearest coffin -
RICHIE Open it.
The army captain regards the detective for a long moment.
RICHIE The warrant permits me to search the plane and its cargo.
RICHIE The captain doesn't comply.
RICHIE Richie moves to open the coffin himself and every soldier's shouldered rifle immediately comes into firing position, aimed at him.
ARMY CAPTAIN But you don't have my permission.
ARMY CAPTAIN Richie stares at the weapons and the uniformed men holding them, safeties off, fingers on the triggers; all they're waiting for is their commander's order to fire.
RICHIE I don't need it.
Trupo regards the shepherd snarling at him from behind the kennel fence.
Comes around back.
Pushes at the frame.
It moves a little, like it's levered -
With the rifles still pointed at him, Richie kneels down, pulls the latches of the coffins, half expecting to hear an accompanying barrage of gunfire.
He lifts the lid.
Sees a long black body bag inside -
Trupo comes around to the front of the kennel again with his gun out and aims it at the dog.
As he fires -
Richie pulls at the zipper, parting the plastic body bag, revealing the remains of a young soldier -
US ATTORNEY That's enough.
The dead dog slides against the fencing as Trupo overturns the kennel to reveal Frank's stash of cash.
Richie and Toback sit before the Federal Attorneys and customs agents.
The US Attorney hangs up a phone ...
then:
US ATTORNEY That was a military transport plane.
US ATTORNEY If there was heroin on board then someone in the military would have to be involved.
US ATTORNEY Which means that even as it fights a war that's claimed 50,000 Americans lives, the military is smuggling narcotics.
US ATTORNEY Richie's in serious trouble and knows it.
US ATTORNEY As does Toback.
US ATTORNEY That's how these events are being interpreted by General Easton in that call to me.
US ATTORNEY That someone employed by the this office believes the United States Army is in the drug trafficking business - and is trying to prove it by desecrating the remains of young men who've given their lives in the defence of democracy.
RICHIE There are drugs on that plane -
US ATTORNEY Shut the fuck up.
US ATTORNEY Richie does, but can't conceal the contempt he feels for these men who've never spent a minute on the street but act as if know more than him, and who are, in the unfortunate organization of his world, his superiors.
US ATTORNEY Is it any wonder then, because of your actions, the entire federal narcotics program is now in jeopardy of being dismantled as completely and enthusiastic- ally as that fucking transport plane?
US ATTORNEY That's what you've accomplished Mr.
US ATTORNEY Roberts.
US ATTORNEY Single-handedly.
RICHIE I had good information the target of my investigation was bringing dope in on that plane.
US ATTORNEY And that target is?
RICHIE Frank Lucas.
RICHIE No one in the room, except Richie and Toback, has ever heard the name.
RICHIE The federal men regard one another blankly.
US ATTORNEY Who?
US ATTORNEY Who's Frank Lucas?
US ATTORNEY Who's he work for?
US ATTORNEY Which family?
RICHIE He's not Italian.
RICHIE He's black.
RICHIE Now there's a longer, even deeper silence, before -
US ATTORNEY Is that supposed to be some kind of joke?
US ATTORNEY You're this close to the end of your career in law enforcement, you're making jokes?
RICHIE I believe Frank Lucas is above the mafia in the dope business.
RICHIE I believe he buys direct from the source in Southeast Asia, cuts out all the middlemen, and uses US military planes and personnel to bring pure No.
RICHIE 4 heroin into United States.
RICHIE Richie is looking at faces that are still trying to make sense out of his ridiculous theory.
RICHIE Toback tries to come to his defense -
TOBACK Richie has a lot of experience -
US ATTORNEY Does he.
US ATTORNEY And how many arrests has he made in his so-called investigation?
RICHIE I was promised when I took this job, it was about real arrests.
US ATTORNEY Does that mean `none?'
RICHIE I have cases against most of Frank's organization.
RICHIE Not him -
US ATTORNEY Frank's organization -
RICHIE That's right.
US ATTORNEY No fucking nigger has accomplished what the American Mafia hasn't in a hundred years!
RICHIE Yeah, you'd know, sitting here, having never been on the (street) -
US ATTORNEY Lou, get this fucking kike out of here -
US ATTORNEY Richie goes for him and lands several punches before Toback and the others can pull him off.
Richie and Toback walk briskly across the lobby -
TOBACK He was out of line, Richie.
TOBACK Richie isn't really listening.
TOBACK Strides past his detectives on his way out of the building.
TOBACK To Spearman -
TOBACK It's over.
TOBACK You're shut down.
TOBACK Toback watches as the detectives follow after Richie striding toward his car.
Frank comes out with an airline representative to find Doc waiting for him.
He can tell immediately something's wrong.
Frank slaps a cartridge into the butt of a pistol.
FRANK Ten million dollars means nothing to me.
Ana stares at the floor.
It all just seems to get worse and worse.
They had their chance to get out and missed it.
FRANK This - is his death warrant.
FRANK He lightly touches his wife's bruised face and walks out.
He comes down the stairs to where Doc waits.
As they head for the door -
MRS. LUCAS Frankie -
MRS. LUCAS Frank glances to where his mother sits in the living room.
MRS. LUCAS Nods to Doc to say, Get the car, I'll be out in a minute.
MRS. LUCAS Goes over to his mother.
MRS. LUCAS Sit down.
MRS. LUCAS He sits.
MRS. LUCAS She studies him in a way she hasn't since he was little.
MRS. LUCAS Eventually -
MRS. LUCAS If you'd have been a preacher, your brothers would be preachers.
MRS. LUCAS If you'd been a soldier, they'd be soldiers.
MRS. LUCAS Do you know that?
MRS. LUCAS They all came here because of you.
MRS. LUCAS You called and they came running.
MRS. LUCAS They look up to you.
MRS. LUCAS They expect you to always know what's best.
MRS. LUCAS But even they know you don't shoot cops.
MRS. LUCAS Even I know that.
MRS. LUCAS Ana knows it.
MRS. LUCAS You seem to be the only one who doesn't.
FRANK Is that where I'm going?
MRS. LUCAS I never asked you where all this came from because I didn't want to hear you lie to me.
MRS. LUCAS Don't lie to me.
MRS. LUCAS Don't do that, too.
MRS. LUCAS She's not pleading, she's telling.
MRS. LUCAS Silence.
MRS. LUCAS Then -
LUCAS Do you really want to make things so bad for your family they'll leave you?
LUCAS Because they will.
LUCAS She will -
LUCAS I know I will.
LUCAS Frank has some trouble looking at her.
LUCAS But then gets up.
LUCAS Walks toward the front door to leave.
LUCAS Hesitates near it a long moment.
LUCAS Then turns and walks upstairs.
LUCAS Trupo will live, at least for now, because of her.
Down in the basement, the body bags are lifted from the wooden coffins.
Set down on tables.
The bags unzipped and the bodies removed.
A rack of clean uniforms is brought in.
The morticians begin dressing the corpses and applying make-up on the dry gray skin.
New white military caskets are trundled in.
Gold handles lifted.
The bodies, clothed and painted now, are deposited on the silk linings.
The lids of the coffins come down and cellophane bags containing folded flags are taped on top.
The white caskets are taken to a loading dock, put in a military truck.
Papers are signed, copies exchanged.
As the truck drives off -
Two black privates on janitorial duty come into the room where the original plain wooden coffins have been discarded.
They remove the lids, then the finely-crafted false bottoms, revealing in 4-inch cavities of each, tightly-packed bricks of Double UO Globe heroin.
As they take them out, a gospel choir begins and continues over:
A laundry truck idles.
Stevie, the Lucas nephew who could have played for Yankees, jumps down, helps the two privates toss several laundry bags into the back of the truck.
A minister on the steps welcomes the congregation which includes Frank, his mother, and Ana -
The laundry truck comes past a guard gate, leaves the base, drives past a stand of trees.
As it passes, Richie, parked by his detectives' cars, recognizes the young driver - who's wearing the same Yankee baseball cap in his T.O. photo.
As Richie and his detectives climb into their cars, two Lucas cars fold in behind the laundry truck.
The detectives follow at a distance -
The sea of ladies' hats from above move in time with the gospel choir.
As always, no matter what else is going on in his complicated life, Frank sits with his mother and Ana in their usual pew.
The gospel music continues over:
Frank emerges from the church, kisses his mother and Ana and put them in a car with a driver.
He climbs into Doc's alone.
His mother watches, wondering perhaps if he intends to go kill Trupo after all.
As Doc's car leaves, so does another.
113. The laundry truck approaches a ramp leading to the George Washington Bridge.
113. Richie, a couple of car lengths behind, follows.
113. The truck continues straight.
From overhead, the laundry truck, the gun car and the van - and the detectives' cars following them all - converge from different directions -
Red Top's van makes a turn.
As Abruzzo's makes the same turn behind it, the infamous Stephen Crane Projects rise up in his windshield.
His foot comes off the gas.
As the gun car passes, he sees Jones's car slow.
Teddy's car approaches from another direction into the Projects, and Abruzzo sees Spearman pull over.
Then the laundry truck turns in, and Richie's slows to a stop, like Abruzzo's, outside the grounds of the foreboding towers.
The gospel music ends.
Doc waits in the car while Frank buys some flowers at a cemetery flower stand.
The surveillance car cruises past.
Toback, in his bathrobe, glass of milk in one hand, phone in the other ...
TOBACK Where is it?
RICHIE V/O Somewhere in the South tower.
TOBACK You know that it's there.
TOBACK You're sure.
RICHIE V/O Positive.
Richie, on a pay phone across down the street from the Projects, looks up at the dark South tower.
RICHIE Lou.
RICHIE We're ready to go in there knowing there's a good chance we won't all come out.
RICHIE That's what we're willing to do.
RICHIE All I'm asking you to do get me a warrant.
RICHIE Silence on the other end of the line ...
RICHIE We don't have a lot of time to fuck around -
TOBACK V/O I'll call in the warrant.
TOBACK V/O And some backup.
TOBACK V/O Don't go in before either gets there.
TOBACK V/O This call disconnects.
The girls spread and tape plastic sheeting to tabletops, then begin changing for work, which means undressing.
Richie and his guys wait for the warrant by their cars.
JONES How long we gonna wait for it?
Pharmaceutical scales balance to their counterweights as the five naked, masked women cut the heroin with quinine to Frank's exacting standards.
Red Top puts on some coffee.
Richie stares down the street, waiting for whatever it is they're waiting for.
Spearman looks at his watch.
RICHIE It'll be here.
A paper-cutter blade slices a sheet of blue cellophane.
The girls at the tables, with the expertise of Cuban cigar makers, wrap pieces of the cellophane like tobacco leaves around precisely-measured 1/4-ounce drifts of Black Magic.
Frank's car winds up the road of the cemetery.
The surveillance car comes through the main gate and parks.
Several black and white and undercover cars approach, sirens off.
Toback himself climbs out of one of the cars and hands Richie the search warrant.
The tall buildings cast long shadows of dread on every activity below, no matter how routine: A woman pushing a stroller, guys shooting hoops, a couple arguing, kids on bikes, old men resting on a graffiti-covered bench.
The unmarked cars drive slowly through it all.
The place teeters on the brink of violence you can feel as gangs move under the shadow of the towers.
Richie removes the cover plate of an elevator, cuts the wires, disengaging it, then leads the Amigos, followed by more detectives to a stairwell.
The place is like Beirut.
Debris-strewn, graffiti-covered.
Frank walks past graves to Bumpy's.
Replaces some dried flowers with fresh ones.
Looks around for something to sit on.
Sees some wooden folding chairs around a fresher grave nearby.
Doc waits by the car in the distance.
Floor by floor, they work their way up the tower like commandos, the squalor and decay and hopelessness somehow intensifying the higher up they go.
Reaching the 17th floor, they listen to a strange sound before easing the fire door open enough to see a kid on a Big Wheels pedalling straight at them.
He passes and the sound fades.
Half the apartment doors are gone.
TVs and radios echo, voices argue, infants wail.
The detectives come around a corner and see at the end of it: a couple of guys with a sawed-off shotguns sitting outside a closed door.
They step back.
Consider one other.
Spearman volunteers with a nod, continues on alone as the others wait.
He walks up to the guys with the guns.
SPEARMAN I got to talk to Teddy.
GUY WITH GUN Get the fuck out of here.
SPEARMAN What the fuck is that?
SPEARMAN I got business with Teddy and it's none of your fuckin business except to knock on the fuckin door and get him.
SPEARMAN As the guy stands, pumping the shotgun, Spearman yanks it hard against his throat like a garrote, forcing him to the floor.
SPEARMAN The shotgun explodes, showering plaster and pellets.
SPEARMAN Jones and Abruzzo are instantly all over the other guy as Richie swings the sledgehammer into the door -
The door splinters - the room already in chaos - Teddy, panicked, runs for the bedroom - the detectives crash in yelling at the girls to get down - a shot from somewhere inside wings Abruzzo - Jones and Spearman firing back - crawling across the floor like an infantrymen -
Richie comes into the darkened bedroom leading with his pistol.
But Teddy's gone.
He sees a tapestry of a tiger on a wall.
Pulls at it, finds a big hole knocked into another dark apartment, climbs through, sees an open door -
As Richie rushes out to the hallway he can hear footfalls echoing in the stairwell.
He starts down, taking the stairs five at a time, chases Teddy down two flights -
Teddy yanks open a door, runs down a corridor, bangs into an apartment.
Richie reaches the apartment just as Teddy is goes out onto an exterior balcony - Richie continues along the interior corridor, running parallel to Teddy on the balcony, who trips over some debris and garbage, looking over his shoulder for Richie -
Richie cuts through another apartment to head him off, but the door to the balcony is nailed shut.
So are the windows.
Richie looks around, grabs a small portable television and, just as Teddy runs past, hurls it through a window at him, hitting him in the head.
He falls hard, dazed.
Richie hurries through the broken window.
Teddy comes to and fights back, until Richie breaks his femur with his bare hands.
Teddy howls in excruciating pain -
Police cars outside.
Eugene Lucas is cuffed and led away.
More police outside Lester's place.
They cuff him.
New Jersey troopers cuff Turner Lucas and lead him away.
Cuffed, Earl Lucas is put in the back of a patrol car.
Frank, on a wooden folding chair at Bumpy's grave, hears the gunning of engines and barking of cops.
He turns to see Doc being handcuffed on the ground by the Towncar.
Glances to a lone figure walking toward him over a rise.
Richie.
Richie arrives at the grave.
Regards the monument to Ellsworth Johnson, and Frank sitting calmly regarding him.
Richie glances around the peaceful surroundings ...
RICHIE What kind of trees are these?
RICHIE Frank looks at the trees, then at Richie, with equal serenity.
FRANK You think you got Frank Lucas.
FRANK You got nothing.
Richie cuts the tags off a new, inexpensive suit.
Slips the jacket on, which seemed somehow to fit a little better at the store.
Cuts the tags off a tie.
Someone throwing up in a stall.
The toilet flushes, the door opens and Richie steps up to a sink, regards his face in the mirror.
Under the fluorescent lights - maybe under any kind - his skin is a shade of death.
He splashes water on it and tries to gather himself.
At the prosecutors table, Richie steals glances at the battery of expensive attorneys over at the defense table.
The courtroom doors swing open and Richie sees Frank Lucas, in a tailored suit, escorted in without cuffs by an amiable- looking federal marshal.
As Frank moves through the gallery, Richie sees it's full of the gangster's friends, many of them celebrities, who smile and greet and fawn as if the Pope has arrived.
Richie has evidence tables covered with cash, weapons, stocks, bonds, property deeds, pictures of Frank's holdings, heroin in blue cellophane.
Frank has celebrities, community leaders, Joe Louis himself who will testify to Frank's benevolent character.
The Champ hugs the heroin trafficker warmly in front of everyone and Richie wonders if he should just give up now.
Richie sees it in slow motion: the hands reaching out to Frank, the pats on his back, lipsticked mouths of beautiful women offering kisses and words of encouragement, his old mother giving him a hug.
He watches Frank's head turn slowly, his eyes passing his phalanx of attorneys, the jury, finally settling on Richie in his cheap suit seated at the prosecutors table.
Frank's eyes smile as they regard Richie, and seem to ask, Can you see this - can you see what you're up against - can you see how insignificant you are?
Reaching the end of the welcoming line finally, Frank brushes by Richie and disappears from view somewhere within the protective husk of his multi-million-dollar legal team.
JUDGE Mr. Roberts -
JUDGE Richie slowly lifts himself from his chair, steps forward, turns to look at the jury that's studying him, finally finds
his voice:
RICHIE Thank you, your Honor.
RICHIE Ladies and gentlemen -
Wire mesh separates Frank from his battalion of lawyers.
He glances over them to Richie being led through the large Visiting Room.
FRANK Here he is, let me talk to him alone.
The attorneys get up and leave.
Richie takes their place.
Frank regards him a moment, offering the same knowing smile from the courtroom.
Richie offers nothing.
FRANK I just heard something.
FRANK I said it couldn't be true.
FRANK You didn't really turn in a million dollars you found in the trunk of a car, did you?
FRANK Richie doesn't say.
FRANK Frank searches his face for some clue to where on earth he's from.
FRANK Want me to tell you what happened to it?
FRANK It ended up in cops' pockets.
RICHIE Maybe.
FRANK Maybe?
FRANK No.
FRANK It did.
FRANK All you did was give it to them for nothing in return.
FRANK Not nothing: You got their contempt.
FRANK Frank studies him.
FRANK Why'd you do that?
FRANK What're you trying to prove, you're better than them?
FRANK You're not better than them.
FRANK You are them.
RICHIE I don't have the time or interest to listen to (this) -
FRANK You did it because it was right.
FRANK That's all.
FRANK Why's that hard to say?
FRANK The question is would you do it again?
FRANK That was a long time ago.
FRANK It'd be very easy to find out.
FRANK Tell me you want to find out, tell me the address, and a car will be there, the trunk loaded.
FRANK Richie knows Frank isn't kidding ...
RICHIE No, thanks.
RICHIE Frank suddenly explodes -
FRANK Who the fuck are you to say no to that?
FRANK You think that impresses me?
FRANK Guards look over, then glance away once it's clear the outburst is through.
FRANK Richie remains serene.
FRANK Eventually -
FRANK Let me ask you something.
FRANK You think by putting me in jail, you're going to stop even one junkie from dying?
FRANK Because you won't.
FRANK If it isn't me, it'll be someone else.
FRANK With me or without me, nothing's going to change.
RICHIE Then that's the way it is.
FRANK You have any sort of case?
FRANK Or just that idiot drives for my brother.
FRANK Is he your case?
FRANK Because if it's just him and the powder, it's not enough.
RICHIE Then you got nothing to worry about.
RICHIE But Frank is worried, most of all by this cop who doesn't take money sitting placidly in front of him.
FRANK My brothers won't talk to you.
FRANK My cousins.
FRANK None of my family.
FRANK No one but that mother fucking driver.
RICHIE I got more than that.
RICHIE I got a line of people wanting to testify that stretches out the door and around the block.
FRANK Bullshit.
RICHIE Is it?
RICHIE Tony the Bug.
RICHIE Benny Two-Socks.
RICHIE Carmine Camanetti.
FRANK Who the fuck are they?
FRANK I don't know them and they don't know me.
RICHIE They sell dope for the Mazzano crime family.
RICHIE Which you all but put out of business.
FRANK This is who you're going to put on the stand?
FRANK Guys who don't know me?
FRANK Who got nothing to do with me?
RICHIE They have everything to do with you.
RICHIE And the only thing they hate more than you is what you represent.
FRANK I don't represent nothing.
RICHIE You don't?
RICHIE Black businessman like you?
RICHIE Of course you do.
RICHIE But once you're gone, things can return to normal.
FRANK Look at me.
FRANK You looking?
FRANK Can you tell by looking it would mean nothing to me if tomorrow you turned up dead?
RICHIE Get in line.
RICHIE That one stretches around the block, too.
RICHIE Frank has never been so frustrated by anyone in his life.
RICHIE He wants to work something out with Richie obviously, but he can't figure out how.
RICHIE Frank studies him.
FRANK What can we do?
RICHIE You know what you have to do.
RICHIE Frank does, but doesn't like it, and doesn't know if he can do it.
FRANK I could give you cops, but that's not who you want, is it.
FRANK You want organized crime names.
RICHIE I'll take them, too.
RICHIE I want them all.
Frank isn't sure he heard right.
FRANK You'll take them, too?
FRANK You'd go after cops?
FRANK Are you serious?
FRANK You'd do that?
FRANK Lock up your own kind?
RICHIE They're not.
RICHIE Not the ones in business with you.
RICHIE They're not my kind any more than the Italians are yours.
RICHIE They regard one another in silence.
RICHIE Richie can tell Frank sees daylight.
FRANK What can you promise me?
RICHIE I can promise you if you lie to me about one name, you'll never get out of prison.
RICHIE Lie about one dollar in one offshore account, you'll never get out.
RICHIE You can live rich in jail the rest of your life, or poor outside it, that's what I can promise.
RICHIE Frank is silent for several moments.
RICHIE Finally -
FRANK You know, I don't care if the feds take all my buildings, my stocks, my off-shore accounts.
FRANK They can take it all, I don't care - use it to build battleships, paint bridges, whatever the fuck they want.
FRANK Fight another war.
FRANK But those other motherfuckers - the cops - put my money in their pockets.
FRANK Millions.
RICHIE I believe it.
RICHIE Frank debates with himself the step he's about to take ...
RICHIE I want to know everyone you've met for the last twenty years.
RICHIE Everyone you sold to.
RICHIE Every cop you ever paid off.
RICHIE Every one who ever stole from you.
RICHIE Every one you remember.
FRANK Oh, I remember them all.
FRANK That's not the problem.
RICHIE What is?
FRANK The jail's aren't big enough.
Surveillance photographs of cops seen earlier taking envelopes of money on 116th Street and other drops go up on a new, elaborate Table of Organization - of cops.
Richie dismantles the Lucas Table of Organization here, taking down the photographs.
As it collapses -
Frank puts up photographs of detectives -
347 QUICK CUTS of the same detectives, in handcuffs, led through
347 police stations past other cops watching with dread like maybe they're next -
347 A surveillance photograph of the four Princes of the City striding down a sidewalk goes up on the cell wall -
348 FLASHCUT as three of the four SIU cops are led away in cuffs
348 from a golf course -
349 A surveillance photograph of Trupo in a black hand - 349
FRANK You go up here.
FRANK Your "special."
FRANK As Frank tapes the picture of Trupo at the top of the pyramid of corruption -
Trupo, coffee in hand, comes into his garage from his kitchen.
Opens the garage door and sees two squad cars parked outside ...
351 A TV: A report on the indictments handed down by the 351 Manhattan DA's office against 53 NYPD and SIU detectives -
Frank gathers his few personal belongings and puts them in a box.
Stands with the box and waits for the cell door to open.
The Table of Organization and files are gone.
Legend: Frank Lucas was convicted of Conspiracy to Distribute Narcotics and sentenced to 70 years.
He served 15 of them.
Legend: Federal authorities confiscated over 250 million dollars from him in real estate, equities and cash in US and foreign banks.
Richie, too, is packing, putting personal items into boxes.
Legend: The day after he convicted Frank Lucas and 30 of his Country Boy relatives, Richard Roberts borrowed $400 from his credit union to help pay for a 3-day vacation to the Bahamas.
Richie, carrying the box, switches off the lights and closes the door behind him on his way out.
Legend: Six months later, he quit the Prosecutors Office to become a defense attorney.
His first client was Frank Lucas.
Frank steps out into sunlight, free but owning nothing but the cardboard box in his arms.
Looks out across the parking lot to see if anyone has come to pick him up.
Sees Richie by his car, hand raised above his head like a flag.
The two of them stand outside Richie's car on the same corner Frank shot Tango.
Frank looks up at the street signs that used to say 116th Street and 8th Avenue.
Now they say 116th Street and Frederick Douglass Boulevard.
FRANK Frederick Douglass Boulevard?
FRANK What was wrong with just plain 8th Avenue?
FRANK He considers the street itself.
FRANK It too has changed.
FRANK The corner groceries, as Bumpy prophesied, really are gone now.
FRANK I used to sit here with Ana in my old car.
FRANK She hated it.
FRANK Now I don't even have a car.
FRANK Or her.
FRANK Frank glances to where his favorite diner used to be, and across the street to where he shot Tango.
FRANK It isn't a fruit stand any more.
FRANK Just do what?
RICHIE What?
FRANK The fuck is that?
FRANK Just do what?
FRANK It's a Nike store with huge paintings of Michael Jordan and the admonition "Just Do It."
RICHIE Sneakers.
RICHIE Expensive ones.
FRANK Who the fuck would buy those?
FRANK A car equipped with sub-woofer bass comes booming past.
FRANK Frank stares at it with the same pained look Bumpy had at the discount emporium.
RICHIE Your brothers know you're out?
FRANK I haven't talked to them in years.
FRANK It's better that way.
FRANK For them.
FRANK I don't know where they are.
FRANK Went back to Greensboro when they got out, I guess.
FRANK Richie nods.
FRANK Frank looks back at the new storefronts.
FRANK What am I going to do now, be a janitor?
FRANK What do I know how to do?
FRANK How am I going to live?
RICHIE I told you I wouldn't let you starve.
FRANK You told me but you can barely take care of yourself.
FRANK (CONT'D) You know, one phone call, Richie, I could be back in business.
FRANK (CONT'D) The look Richie gives him calmly assures Frank if he did that it'd be the last phone he made outside prison - ever.
FRANK I won't.
FRANK I'm just saying I could.
FRANK He buttons the cuffs of the fake Members Only windbreaker Richie bought him off the street.
FRANK Thanks for the clothes.
RICHIE You're welcome.
RICHIE Frank glances away to three young hoods coming toward them like they own the sidewalk and everything around it - baggy pants, bandanas tied around their heads.
FRANK Uh-oh.
FRANK Look out.
FRANK Here come the gangsters.
FRANK Frank's right in their path but doesn't move, forcing one of them to squeeze between him and a parking meter.
FRANK The gangsta looks back, is about to say something, or do something, but, examining the expression of quiet menace on Frank's face, thinks better of it.
FRANK The others stop.
GANGSTA 2 What.
GANGSTA 2 The first one is still staring at Frank, but finally has the good sense to let it go.
GANGSTA 1 Nothing.
GANGSTA 1 They move on.
GANGSTA 1 Frank glances to Richie.
FRANK Every idiot gets to be young once.
FRANK Frank zips up his Members Only jacket, props up the collar and points himself in the other direction.
FRANK Let's get out of here.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
