MR BROOKS
Written by
Bruce A Evans & Raynold Gideon
CLOSE on a Polaroid of a dimly lit COUPLE locked in a sexual embrace.
We cannot see their faces.
MR. BROOKS (V.O.) God grant me the Serenity to accept the things I cannot change...
Our view travels sensuously down the Woman's naked torso to find the Man's head buried between her legs.
MARSHALL (V.O.) Why do you fight it so hard, Earl?
MR. BROOKS (V.O.) Courage to change the things I can...
MARSHALL (V.O.) Come on, you've been a good boy for a long time, you deserve a little fun.
Our view moves back up to the Woman's breasts.
EARL BROOKS' reflection in a mirror.
Earl, in his 40's, has on a tuxedo.
He's in front of a sink in a Public Bathroom and he's whispering to his image.
MR. BROOKS ...
MR. BROOKS and Wisdom to know the difference.
Picking up speed against the hunger in his head:
MR. BROOKS (CONT'D) Living one day at a time, Enjoying one moment at a time, Accepting hardship as a pathway to peace...
From far away comes the sound of applause.
MEN in tuxedos and WOMEN in gowns.
Mr. Brooks is seated at one of the front tables with his wife, EMMA, also 40's.
The audience's hands are coming together for what a MAN at the microphone has just said.
Mr. Brooks is smiling but not clapping; and although his lips don't move we can hear:
MR. BROOKS (V.O.) ...
MR. BROOKS (V.O.) Taking, as He did, this sinful world as it is, not as I would have it.
MR. BROOKS (V.O.) Trusting that He will make all things right if I surrender to His will.
MR. BROOKS (V.O.) That I may be reasonably happy in this life, And supremely happy with Him forever in the next.
MR. BROOKS (V.O.) Amen.
The Man at the microphone raises his arms to quiet the Audience.
MAN I could go on and on about what a great guy Earl is, how he cuts his toe nails...
Everyone laughs.
MAN ...
MAN how he gives freely of his time and money, but let's get Earl up here to speak for himself.
MAN Ladies and Gentlemen, I give you a businessman, a philanthropist, a great friend and the Evanston Chamber of Commerce Man of the Year...
MAN Mr. Earl Brooks.
Mr. Brooks kisses Emma, stands and after accepting congratulations along the way, arrives at the podium.
MR. BROOKS Thank you all very much.
MR. BROOKS The first thing I would like to say is...
MR. BROOKS I don't even know how I cut my toe nails.
Applause and laughter from the Audience.
MR. BROOKS Twenty years ago when I started the Brooks Box Factory I never dreamed I would one day be standing here.
A silver Lexus LS 430 glides past us.
EMMA (V.O.) Did you see Sis Wallace's dress?
Mr. Brooks is driving.
Emma is in the passenger seat.
They're holding hands.
EMMA You could see her nipples.
EMMA At her age she should keep those things hidden.
Mr. Brooks is only listening to his Wife with one ear and underneath what she is saying we can barely hear:
MR. BROOKS (V.O.) God grant me the Serenity to accept...
EMMA The only thing that would have made this evening more perfect is if Jane had been here.
MR. BROOKS She called.
MR. BROOKS She has mid terms coming up.
EMMA She's dropping out, you know.
MR. BROOKS We'll see.
EMMA Nothing she does is wrong to you, is it?...
Mr. Brooks doesn't rise to the bait.
EMMA Well she missed a good party...
As she continues, we look at Mr. Brooks and Emma's voice fades to a murmur.
In the back seat, a Man leans out from behind Mr. Brooks's head.
This is MARSHALL.
He's 50 plus.
Emma can neither see nor hear him.
Marshall exists only in Mr. Brooks's mind.
MARSHALL Come on, Earl, give yourself a break, you know you want to do this.
MR. BROOKS No.
MARSHALL You're the fucking 'man of the year', you deserve it.
MARSHALL It's not like it's not set up.
MARSHALL You already know how to by-pass the alarm, you know how to pick the locks.
MARSHALL Tonight's the perfect night.
MR. BROOKS No, Marshall, I said 'no'!
MARSHALL I heard you, Earl, but you don't mean 'no'.
Emma feels Mr. Brooks's distance.
EMMA What's the matter?
Mr. Brooks pulls himself back into the moment.
MR. BROOKS Nothing.
EMMA You were frowning.
MR. BROOKS I was thinking of what I didn't say in the speech.
EMMA They laughed, they were touched, I don't think anyone felt left out.
MARSHALL They have their dance class tonight.
MARSHALL What if we go by and just look at them.
MARSHALL There's no harm in just having a look.
MR. BROOKS No means 'no', Marshall.
MARSHALL Please...
MARSHALL pretty please.
MR. BROOKS The food tonight was very good, but I wasn't crazy about the dessert.
MR. BROOKS Would you like to stop somewhere and get something sweet?
In a booth, Mr. Brooks and Emma are sharing a Sundae.
Mr.
Brooks steals a look at the Arthur Murray dance class that is taking place behind the full-length windows fronting the second floor of the Building across the street.
EMMA ...
EMMA Labradors are supposed to be nice, or maybe a rescue mutt...
MR. BROOKS The Pound's a pretty sad place; if you want me to, I'll go with you.
EMMA There's an Irish Lab I read about, and I think the breeder is...
Mr. Brooks turns his attention back to the Dancers and again Emma's voice fades to a murmur.
Both Mr. Brooks and Marshall who is seated on the other side of Emma are focused on one particular COUPLE.
The Man and Woman are not great dancers nor are they especially attractive, but Mr. Brooks and Marshall are fascinated with them.
Marshall leans forward and looking slyly around Emma at Mr.
Brooks:
MARSHALL I bet your dick's getting hard, isn't it, just imagining what they would look like dead?
Savoring the ice-cream, Mr. Brooks nods.
Two story modern.
Not ostentatious, but the elegance of the line and the grounds say there's big money here.
Through the door of the DRESSING AREA, Emma can be seen taking off her evening clothes.
Hidden by the darkness on the other side of the bed, Mr.
Brooks is hunched forward on a chair, his head in his hands.
His bow tie is undone, but he's still wearing his Tuxedo.
In obvious torment, he is whispering to himself.
MR. BROOKS ...
MR. BROOKS I can't do this, I can't do this, I can't do this, please don't let me do this, God grant me the Serenity to accept the things I cannot change...
In the DRESSING AREA
Emma is putting on her sleep-wear.
Mr. Brooks steps into the doorway.
MR. BROOKS I'm going to stay up a while, maybe go to the studio and play with some glazes.
EMMA Okay, I'm going to read.
EMMA If I'm not awake, wake me when you come back.
Mr. Brooks comes forward, puts his arms around Emma and hugs her, then easing back, kisses her.
MR. BROOKS I thought you were wonderful tonight.
Mr. Brooks exits the back door and starts down a path that leads away from the house.
MR. BROOKS Don't do this, don't do this, please don't do this, don't do this, don't do, please don't do this...
He passes through a screen of trees and arrives at a small beautiful industrial-looking Building.
No windows except for a narrow strip on three sides just under the edge of the roof.
Mr. Brooks lets himself in with a key.
Exquisitely unique handmade handglazed bowls, vases, cups, plates are scattered haphazardly on shelves and tables around the room.
This is Mr. Brooks's CERAMICS STUDIO.
Mr. Brooks turns on the big industrial kiln and sets the temperature, then in a series of quick cuts changes out of his tuxedo into his work clothes which he selects from a dozen identical pairs of khaki shirts and pants hanging in a closet.
Below the pants and shirts are a dozen pairs of identical leather work shoes.
The windbreaker he puts on is also from a dozen identical windbreakers.
He takes a set of car keys off a hook next to a door which opens into a garage.
Under the light is an older model non- descript Toyota.
The Toyota backs into an alley and with the garage door closing behind it, pulls away.
Marshall is up front with Mr. Brooks.
MARSHALL Oh Lordy, Earl my boy, I've missed this!
MARSHALL We are going to have so much fun!
MR. BROOKS This is the last time, Marshall.
MR. BROOKS Understand me?!
MR. BROOKS The very last time!
A mixture of modest houses and apartment buildings.
Mr.
Brooks's Toyota is parked in the semi-dark cast by a tree.
We rise over the car, over the trees, over the houses to the other side of the block and come down to find Mr. Brooks working the lock on the side door of a small BUNGALOW.
He has on surgical gloves.
The pick is extracted, the handle turned.
The door opens.
There's a chain.
Mr. Brooks removes a pair of bent rubber tipped forceps from a pocket, inserts it in the chain, pulls the door to, gives the tool a twist and gently pushes the door inward.
The chain has been released.
Mr. Brooks quietly closes the door and holding his breath stands very still and listens.
There's a faint indistinct sound coming from the recesses of the house.
Mr. Brooks's feet glide out of the PANTRY.
Now coming slightly behind him is another pair of legs encased in dark slacks.
Move up; the person in the black slacks is Marshall.
In the middle of the KITCHEN, the sound is now recognizable.
It's the moans of a Couple fucking.
This disturbs Mr. Brooks, he hesitates.
Marshall leans in and hisses fiercely in his ear.
MARSHALL Don't you dare quit on me, you piece of shit.
MARSHALL I want to see what they're doing.
Mr. Brooks's spine stiffens and he's going forward again.
Entering a HALLWAY, he reaches into his jacket.
When his hand reappears it's inside a Ziplock bag, his fingers around the butt of a silenced pistol.
He brings the hand and bag to his mouth and tightens the Ziplock against his wrist.
The two Men arrive at a door that's slightly ajar.
Behind it the sounds of the love-making are becoming more intense.
Mr. Brooks nudges the door with his foot.
It opens enough for he and Marshall to see the Couple inside.
The Man and Woman from the Arthur Murray dance class are naked on the bed.
As much as Mr. Brooks hates himself for it he loves watching.
He can now hear his heart beating in his ears.
He begins to breathe in unison with the Couple, but his expression is distant almost clinical.
When the Couple climaxes, when they come, Mr. Brooks's face goes blank.
On the bed the Woman rolls off her Partner and the two of them lie there basking in the afterglow.
Behind them Mr. Brooks pushes the door fully open and slips into the ROOM.
They don't know he's there until he speaks.
MR. BROOKS Hello.
Both the Man and Woman jump with surprise and look.
The Woman screams and scrabbles at the sheet to cover herself.
MAN What the fuck?!
Then he sees the gun.
MAN Hey, man, don't...
BROOKS Be quiet and sit up.
In an attempt to get away, the Woman pushes herself back against the wall.
She can't take her eyes off Mr. Brooks and she can't stop screaming.
POP!
A hole appears above her left eye.
The impact of Mr.
Brooks's High Velocity .22 slug bounces her head off the wall.
The screaming stops.
The Man opens his mouth and begins to shake.
POP!
The bullet through his brain makes him instantly dead and he crumples onto the Girl.
Mr. Brooks looks at what he's done.
His nostrils flare at the scent of death.
Then he moves, he's got work to do.
On his way to the bed, the pistol goes into his pocket.
MARSHALL Whoa, Earl, what the fuck is this?!!
Mr. Brooks snaps a look.
The curtains of the bedroom window are open; and over half of the Apartments in a four story Building on the other side of an alley can see into this room.
Most of their windows are dark.
And there's no one looking out of the windows that are lit.
MARSHALL These pigs liked to fuck with the blinds open, you should have known that, Earl.
MARSHALL This is a big mistake for you, Earl.
MR. BROOKS Almost like I want to get caught, huh, Marshall?
MARSHALL Well, don't fucking do that.
MARSHALL I don't think either of us would enjoy spending the rest of our lives in jail or a lethal injection.
BROOKS Yes, sir.
He grabs a side of cloth in either hand and yanks the curtains closed.
CLOSE on a Polaroid of the dance Couple in a sexual pose.
The attitude of the bodies is awkward and very reminiscent of the ones in the Polaroid we opened the movie with.
Mr. Brooks is kneeling naked in front of the kiln where his murder clothes are being reduced to ash.
Arranged on the floor are Polaroids of the dance Couple in sexual positions.
MR. BROOKS Please forgive me...
MR. BROOKS Please forgive me...
As we look closer at the Photographs we realize by a smear of blood here and there and the distortion of the limbs that these tableaus were arranged after the Couple was killed.
One by one, Mr. Brooks picks up his souvenirs.
He lingers over the last image; and from where he's sitting on the edge of a table:
MARSHALL Don't even think about it.
MARSHALL You know the rules.
Reluctantly Mr. Brooks throws the Polaroids into the fire of the kiln.
MARSHALL Now go up and make love to your beautiful wife.
He leaves.
In the kiln, the Polaroids burst into flame.
The sunlight exposes its charm.
If it weren't for the Police tape, the UNIFORMED OFFICERS, and the PLAINCLOTHES DETECTIVES, it looks like it would be a cool place to live.
An OLDER DETECTIVE, an African-American, comes out on the porch and calls to two other DETECTIVES who are drinking coffee on the lawn:
OLDER DETECTIVE Where the fuck is Atwood?!
YOUNG DETECTIVE I called ten minutes ago, they said she was on her way.
OLDER DETECTIVE She doesn't get here soon, these bodies won't even be dead anymore?
A Uniformed Cop standing guard at the tape:
COP You looking for the lady Cop?
OLDER DETECTIVE Yeah.
COP She's here.
COP She's been sitting in her car right over there for the last half hour.
OLDER DETECTIVE Oh, Christ.
Special Detective TRACY ATWOOD, somewhere in her 30's, is behind the wheel.
The door is open.
By the expression on her face we might guess that Detective Atwood has simply forgotten to get out of the car.
On the seat next to her is a copy of the Chicago Tribune.
The headline of a middle article on the first page reads: THE
Move up to Atwood's face.
The Older Detective followed by the Younger Detective approaches.
OLDER DETECTIVE You thinking of joining us anytime soon, Atwood?
Atwood doesn't look at the Detectives for a long beat and when she does her expression is not friendly.
DETECTIVE ATWOOD I really hated yesterday, Snyder, and then today came along.
As she gets out of the car, the Men notice the bandages on her wrists and falling into step with her on the way to the house.
SNYDER (OLDER DETECTIVE) What happened to your wrists?
Atwood holds up her hands to reveal the extent of the bandages.
DETECTIVE ATWOOD I tried to commit suicide.
The Young Detective laughs.
Atwood whirls on him.
DETECTIVE ATWOOD What's so funny?
YOUNG DETECTIVE Eh...
YOUNG DETECTIVE I...
YOUNG DETECTIVE I don't know, I heard it was because you were drunk and got into a fight with a fish tank.
Atwood sticks her finger into the Young Detective's chest.
DETECTIVE ATWOOD Who are you gonna believe?
DETECTIVE ATWOOD Me or the fucking fish?!
YOUNG DETECTIVE Eh...
YOUNG DETECTIVE you.
DETECTIVE ATWOOD Good.
Atwood turns and leaves the Men.
YOUNG DETECTIVE She's nuts!
SNYDER And rich.
They catch up to Atwood who has squatted down to examine the lock on the front door.
SNYDER There are some scratches in the side door cylinder.
SNYDER Other than that no signs of forced entry.
SNYDER The alarm was armed and we even had to cut the security chains to get in.
DETECTIVE ATWOOD This guy hasn't been active for over two years...
She enters the house.
From the way Atwood looks at her surroundings as she crosses the Living Room we get the feel that this Woman misses nothing.
DETECTIVE ATWOOD ...
DETECTIVE ATWOOD we think he's either dead or in jail on some other charge.
DETECTIVE ATWOOD This is probably a copycat.
Detective Snyder points her down the Hall toward the Bedroom and follows.
SNYDER That's why we called you.
SNYDER You're the God that tells us peons if we have a simple murder here or something we can dump on you.
DETECTIVE ATWOOD Bite yourself.
Atwood arrives in the doorway of the BEDROOM where the murders took place and stops.
The Bodies of the dance Couple are now on the floor.
The Man is propped up against the bed in a sitting position.
The Woman has her head in the Man's crotch.
Almost like Mr. Brooks, Atwood's nostrils flare, but in Atwood's case it's not the scent of death that arouses her but it's like she's searching for the scent of her prey.
In a glance she memorizes the Room, then steps inside.
The Crime Scene TECHNICIANS shift to accommodate Atwood's inspection.
DETECTIVE ATWOOD He always rearranges the bodies, but this is out of character.
DETECTIVE ATWOOD He has never left them in such a crude position.
DETECTIVE ATWOOD Usually it's more romantic with their arms around each other, kissing, their mouths open, their tongues touching.
SNYDER So we have a copycat?
DETECTIVE ATWOOD Where are the thumbprints?
Snyder points to a bare space of wall above the bed.
Atwood leans in to look at two bloody 'thumbprints' placed side by side.
DETECTIVE ATWOOD One his one hers?
SNYDER That's what it looks like.
DETECTIVE ATWOOD What's that?
There are two holes gouged into the plaster of the wall.
SNYDER The bullets went completely through the victims.
SNYDER The killer recovered the slugs.
Atwood unfolds and after another look around the room goes to the window and cracks the curtains.
There's the four story Apartment Building across the alley, its windows staring down at her.
DETECTIVE ATWOOD Were these open or closed when you got here?
SNYDER Closed.
Atwood tries the cord, the curtains are stuck.
DETECTIVE ATWOOD Hmm...
She returns her attention to the murder scene.
DETECTIVE ATWOOD It has never been revealed to the public that the Thumbprint Killer retrieves the slugs.
SNYDER So this one's yours.
DETECTIVE ATWOOD I don't fucking need this.
She doubles back and cracks the curtains for another look at the four story Apartment Building.
DETECTIVE ATWOOD Have you checked the tenants of that building?
SNYDER Only a few of them are home, they say they didn't see anything.
SNYDER We checked the whole neighborhood, so far nobody saw a thing.
Atwood nods and turns back to the bodies.
DETECTIVE ATWOOD Leaving them like this, he must have been angry at them for some reason.
She reaches down and runs a hand over the carpet.
DETECTIVE ATWOOD Where would they keep their vacuum cleaner.
A puzzled Snyder follows her out of the room.
Atwood opens a service closet.
There's the Vacuum Cleaner.
DETECTIVE ATWOOD I'll bet you a hundred bucks, Snyder, there is no bag in that vacuum cleaner.
SNYDER I have no idea what you're looking for.
Atwood unzips the cover.
There is no bag inside.
DETECTIVE ATWOOD He vacuumed the house and took the bag.
SNYDER Oh, shit.
SNYDER That is scary smart.
Detective Atwood is standing on an empty capped plastic gallon milk carton looking over the fence into the back yard of the Murder House.
Snyder has his hand on her back to steady her.
DETECTIVE ATWOOD Okay.
He releases her.
She hops down and directs her attention at the four story Apartment Building.
DETECTIVE ATWOOD Our best hope is if someone in there saw something.
A MAN comes out from behind the next door fence and strides purposefully toward them.
MAN Detective Tracy Atwood?
DETECTIVE ATWOOD Yes.
MAN This is for you.
She accepts the official looking document being offered.
MAN You have been served.
DETECTIVE ATWOOD You fucking asshole!!
DETECTIVE ATWOOD I'm in the middle of a fucking murder investigation!!
MAN Hey, take it easy lady, I'm just the messenger.
DETECTIVE ATWOOD Goddamit!!
SNYDER What is it?
DETECTIVE ATWOOD My soon to be ex-husband's scumbag lawyer is trying to show me how painful she can make my life if I don't give them what they want.
SNYDER This is not the Doctor.
DETECTIVE ATWOOD The doctor was a couple years ago.
DETECTIVE ATWOOD This one is my stupid mistake.
An AA Meeting is getting started.
Mr. Brooks is one of the ASSEMBLED.
The LEADER steps into the semicircle of Men and Women.
LEADER Are there any new members?
A WOMAN comes forward.
WOMAN Hi, my name is Vaughn and I'm an alcoholic.
She rejoins the circle.
Mr. Brooks separates himself from the Others.
MR. BROOKS Hi, my name is Earl and I'm an addict.
When he rejoins the circle, Marshall is there to greet him.
MARSHALL You're such a fucking hypocrite.
MARSHALL If you were honest you would step out there and say 'Hi, I'm Earl.
MARSHALL I killed two people last night and I really got off on it, but I need your help to be cured.'
MR. BROOKS I'm different Marshall, I won't argue that with you.
MR. BROOKS This is the only place that has ever helped me be normal and I've been straight up until last night for the past two years.
MR. BROOKS I'm not going to kill again and I'm not going to quit coming here because it upsets you.
MARSHALL Yeah but for the next 29 days you're going to have to step out there and say 'Hi, I'm Earl, I'm an addict.' And everybody will know you fell off the wagon.
MARSHALL Don't you feel stupid doing that?
MR. BROOKS No.
MR. BROOKS I feel good.
A Cab arrives at the Front Entrance of the BROOKS BOX FACTORY, a long three story brick Building.
A YOUNG WOMAN, 19, is dropped off along with an assortment of luggage and boxes.
It's loud.
We follow a thin piece of cardboard as one machine deals it off the bottom of a stack into the maw of another machine.
That machine prints one side of the cardboard blue.
It is handed off to the third machine which cuts the flaps.
The fourth machine folds and glues those flaps and spits the piece of cardboard out onto a conveyor belt as a box.
Wearing safety glasses and ear protectors along with his business suit, Mr. Brooks picks up the box and hands it to one of three similarly attired MEN, standing nearby.
MR. BROOKS This is not the top of the line or the bottom, but for the money we're talking about this is the quality I can provide you.
As Mr. Brooks talks the Men pass the box between them.
MR. BROOKS Your packaging is the first impression your customers will have of your product...
PA SYSTEM Mr. Brooks, your daughter is waiting for you in your office.
A surprised Mr. Brooks grabs a quick look at the PA Speaker, then continues.
MR. BROOKS ...
MR. BROOKS We'd love to work you with on the design.
MR. BROOKS It's fun to challenge our machines.
MR. BROOKS If you check around, you'll find we're not the cheapest, but we are the best.
On his way through to his office, Mr. Brooks smiles absently at a MAN waiting on the couch.
The pleasant-looking Man in his early 30's, nods.
Mr. Brooks stops at his SECRETARY's desk.
MR. BROOKS Sunday, did Jane call and say she was coming?
SUNDAY I would have given you that message, Mr. Brooks.
SUNDAY She has boxes and suitcases downstairs.
MR. BROOKS Hold my calls.
BROOKS What are you doing here, Gorgeous?
The 19 year old Girl we saw arrive by cab stands up and throws her arms around Mr. Brooks.
JANE I'm sorry, Daddy, please don't be angry with me.
Mr. Brooks kisses Jane on the forehead and goes to sit at his desk.
MR. BROOKS I can guess what you've done, but why don't you tell me and then I'll decide.
JANE I dropped out of school.
MR. BROOKS Okay.
MR. BROOKS Have you told your mother this?
JANE No.
JANE I wanted to speak to you first.
MR. BROOKS You'll have to tell her, I'm not going to do that for you, and then together the three of us will decide where to go from here.
JANE I've thought a lot about this, Dad.
JANE College is a waste of time for me.
MR. BROOKS I don't know how you know that half way through your Freshman year, but...
JANE You didn't go to college, Dad, and you're successful.
JANE I want to come and work for you.
Sitting on the couch:
MARSHALL She's not telling you everything, she's hiding something.
BROOKS I know.
BROOKS I'm not hiring right now.
JANE Just listen to me.
JANE What would happen to the business if, God forbid, something happened to you?
JANE Mom would probably have to sell to strangers.
JANE I'm willing to start at the bottom, you can treat me as a regular employee, I want to learn everything there is to know about running the box business, and then when the time comes, the business would stay in the family.
MR. BROOKS That's sweet, but you're talking about emotion, not business.
MR. BROOKS In fact your mother and I came very close to selling out last year.
JANE What?!
MR. BROOKS If we had been offered a little more money, and they may come back to us, we will sell.
JANE What would you do without...?!
There's a knock on the door.
MR. BROOKS Yes?
Sunday, the secretary, comes in and crossing to Mr. Brooks:
SUNDAY I'm sorry, I know you didn't want to be disturbed, the Man in the waiting room insisted I give you this.
She hands Mr. Brooks a letter-size envelope.
SUNDAY He said you would find what's inside very interesting.
MR. BROOKS What is he?
MR. BROOKS A salesman?
SUNDAY He won't say.
SUNDAY I've never seen him before.
SUNDAY I can tell him to go away if you want me to.
MR. BROOKS That's okay.
She leaves.
Slicing the flap of the envelope, Mr. Brooks picks up with Jane.
MR. BROOKS Part of spending the four years in college is to...
Mr. Brooks can now see the contents of the envelope.
Two snapshot-size PHOTOS taken with a high speed digital camera.
One shows the right side of Mr. Brooks's cheek.
He is in no way identifiable, but that blur of flesh appears to be looking at the dead dance Couple.
The second Photo is a clear shot of Mr. Brooks closing the curtains with the dead dance Couple behind him.
Neither Mr. Brooks's voice or his face betray the enormity of what he's looking at.
MR. BROOKS ...
MR. BROOKS eh...
MR. BROOKS to give yourself the chance to find out who you are and what you want to do.
JANE I'll talk to Mom, but I'm not going back to school.
MR. BROOKS Where would you live?
JANE To save money I would move back home, but no rules, no curfew, I want to be treated like an adult.
Mr. Brooks allows himself a slight smile.
MR. BROOKS Would you pay for your food, would you pay rent?
JANE No, dad, you're a very wealthy man, you can afford to keep me.
Mr. Brooks presses his Intercom.
MR. BROOKS Sunday, would you show the gentleman who gave you the envelope to the conference room, and tell him I'll meet him there and...
MR. BROOKS What happened to the BMW?
JANE A friend is driving it across country, it'll be here next weekend.
MR. BROOKS And get Jane a cab.
He picks up the phone and holds it out to Jane.
MR. BROOKS Call your mother.
JANE Are you going to give me a job?
MR. BROOKS If it were up to me, and I think your mother will agree with this, you should go back to school.
Mr. Brooks comes around the corner.
He's raving at Marshall who's walking beside him.
MR. BROOKS You see all of this?!
MR. BROOKS The factory, the houses, the cars, the money, the respect!!...
A different angle in the same hallway shows Mr. Brooks walking away from us.
A passing EMPLOYEE crosses him.
The Men nod to each other.
Marshall is nowhere in sight.
MR. BROOKS (V.O.) ...
MR. BROOKS (V.O.) I like them!
MR. BROOKS (V.O.) I don't want to lose them!
And then we're back to the original angle and Marshall is again in the picture.
MR. BROOKS ...
MR. BROOKS That's why I didn't want to do the dance Couple!
MARSHALL Stop your fucking whining, Earl, you enjoyed doing that Couple just as much as I did, and look on the bright side, he came to us he didn't go to the Cops.
MARSHALL If he tries to shake us down we kill him.
MARSHALL Period.
MARSHALL We make it fun but we kill him.
MARSHALL End of story.
The Man from the Reception Area is nervously admiring a display of Mr. Brooks's ceramic pieces.
He turns at the sound of the door opening behind.
MR. BROOKS What can I do for you, Mr...?
MAN ...
MAN Let's say, 'Smith'.
MR. BROOKS Okay, Mr. Smith.
Mr. Brooks motions him to a seat.
MR. SMITH (MAN) Before you get the wrong impression, Mr. Brooks, I'm not here to shake you down.
MR. BROOKS Then these are the only copies of these photos and you have no others.
MR. SMITH No.
MR. SMITH I have other copies and other photos, and if something were to happen to me...
MR. BROOKS How did you find me, Mr. Smith?
MR. SMITH You're 'Man of the Year', Mr.
MR. SMITH Brooks.
MR. SMITH Your picture was in the paper.
MR. SMITH If it hadn't been, I don't know what I would have done.
MR. BROOKS Lucky me.
MR. BROOKS What is it that I can help you with?
MR. SMITH I've been watching that Couple for months, they liked to make love with the blinds open.
MR. SMITH Sometimes I would take pictures, you know, visual aides for later.
MR. SMITH It was fun, it was a great way to get off; I thought, until I saw you kill them.
MR. SMITH I have to tell you I have never ever felt a rush like that ever.
MR. SMITH I know you're the Thumbprint killer, you've done this before.
MR. SMITH What I want is to go with you the next time you kill someone.
MR. SMITH And I would like that to be soon.
From the end of the table, Marshall cackles a laugh.
MARSHALL And you were worried that this was going to be unpleasant.
MARSHALL The answer is simple.
MARSHALL Just tell him you've decided never to kill again and he'll go away.
MR. BROOKS You enjoy watching me suffer, don't you?
MARSHALL In a word, yes.
MR. BROOKS Where do you think he has the other pictures?
MARSHALL He put them in a safety deposit box but I'll bet the box is at the bank where he has his checking account and the key is on his keychain.
MARSHALL He really wants to do this, he's not going to go to the cops.
Mr. Smith who has grown uneasy under Mr. Brooks's stare swallows:
MR. SMITH So do we have a deal?
MR. BROOKS From the angle of these pictures...
MR. BROOKS ...
MR. BROOKS you live on the third floor of the apartment building across the alley from the Couple's house.
MR. SMITH Well...
MR. SMITH eh.
MR. BROOKS Yes or no, Mr. Smith?
Mr. Smith nods 'yes'.
MR. BROOKS What time do you get home from work?
MR. SMITH Six thirty, seven, depending on the traffic.
MR. BROOKS You can never come here again, you can never call me.
MR. BROOKS Do you understand that?
MR. SMITH Yes.
BROOKS Tomorrow night, not tonight, tomorrow night, at eight o'clock, leave your apartment and walk east.
BROOKS I'll pick you up.
MR. SMITH If you're thinking of doing anything to me, Mr. Brooks...
MR. BROOKS We're both aware of the rules, Mr.
MR. BROOKS Smith, but I feel I must warn you.
MR. BROOKS If it turns out that you enjoy killing, it can become very addictive.
MR. BROOKS It could ruin your life.
MR. SMITH I want to do this.
MR. BROOKS Have I covered everything?
MARSHALL I can't think of anything else.
Mr. Brooks stands up and opens the door.
MR. BROOKS I'll see you tomorrow night, Mr.
MR. BROOKS Smith.
On his way out, Mr. Smith nods.
Mr. Brooks closes the door.
His chin drops on his chest and he sighs.
MR. BROOKS Please God, please help me find a way not to do this.
Detective Atwood comes out of the CROWD on the sidewalk and enters a Highrise.
Atwood and her ATTORNEYS, a gray-haired Man in his 60's, and an Asian Woman about the same age as Atwood are on one side of the table.
JESSE, Atwood's soon to be ex-husband, very handsome, slightly younger than Atwood, and SHEILA, his attractive divorce lawyer, sit across from them.
ASIAN ATTORNEY We've talked to our client and we've come up with a number that we feel is more than fair.
Atwood is not happy with this.
The Attorney slides a sheet of paper to Sheila.
She turns it over.
On it is written:
ASIAN ATTORNEY We can have a check for that amount in your office by 6 o'clock.
SHEILA We told you at the beginning what we want and that hasn't changed.
GRAY-HAIRED ATTORNEY You know as well as I do, Counselor, if we go to court you're not going to get a million five.
SHEILA I don't know.
SHEILA Let's see.
She holds up the front page of the Chicago Tribune.
"THE HANGMAN ESCAPES" story is circled in red.
SHEILA This is the front page of yesterday's paper...
SHEILA 'Hangman Escapes'...
SHEILA eh...
SHEILA now, here it is...
SHEILA 'after torturing the young women, Thorton Meeks would hang them in public places - church steeples, balconies, Freeway overpasses'...
SHEILA Your client captured Mr. Meeks.
SHEILA This is just one example of the cases my client lived through when he was married to your client.
ASIAN ATTORNEY Your client knew Detective Atwood was a homicide detective when he married her.
SHEILA But he had no idea of the mental anguish that being in close proximity to her work would cause him.
DETECTIVE ATWOOD What about the mental anguish I went through being in close proximity to him.
DETECTIVE ATWOOD Who's gonna pay me for that?
ASIAN ATTORNEY We don't need to get into this, Tracy.
DETECTIVE ATWOOD Yes, we do.
DETECTIVE ATWOOD I was the one who paid for everything while we were married, and now I'm being asked to give him a bonus for spending time with me when I've already paid for it in the first place.
JESSE Tracy, this is not a lot of money for you, and you know how upset I was when Meeks said that he was going to escape and he would come back and kill you.
SHEILA We're quite willing to find out what a court would think that mental anguish is worth.
DETECTIVE ATWOOD Jesse...
DETECTIVE ATWOOD Darling?...
DETECTIVE ATWOOD you know the best thing that could happen to me right now?
DETECTIVE ATWOOD That you get hit by a truck and die.
SHEILA That's it!
SHEILA Mr. Vialo and I are leaving.
SHEILA You've threatened my client, we're going to ask for a restraining order, and we'll see you in court.
The door closes behind them.
GRAY-HAIRED ATTORNEY That's going to cost you, Tracy.
DETECTIVE ATWOOD Fuck it.
DETECTIVE ATWOOD It felt good.
Moonlight seeps around the blinds to reveal Mr. Smith asleep in bed.
Beyond the open BEDROOM door down the hall is only darkness until the eruption of illumination from a penlight momentarily outlines the figure of a Man.
Then we're looking at what the penlight sees.
A keyring.
Hands in surgical gloves isolate the - safety deposit key - and press it into a soft wax block where it leaves its impression.
The light goes off.
In the BEDROOM at the end of the hallway, Mr. Smith begins to snore.
The Figure coasts silently toward the sound.
Mr. Smith's face is sideways on the pillow.
The snores and a little drool burbles out of the corner of his mouth.
WHOOMP!!
The impact of something landing on the bed bounces Mr. Smith upright and awake.
MR. SMITH Ahhh!!!
MR. SMITH Ahhh!!!
MR. SMITH Ahhh!!!
The beam from the penlight hits him in the face.
He raises his hands to shield his eyes.
MR. BROOKS Don't worry, if I were here to kill you, you would already be dead.
The penlight leaves Mr. Smith and Mr. Brooks places it deliberately under his own chin casting long sinister shadows up his face.
He's sitting on the bed next to Mr. Smith.
MR. BROOKS After you left today, I realized our friendship was a little one- sided.
MR. BROOKS (CONT'D) So when we meet tomorrow night would you be so kind as to bring all of the pictures and the memory card from your camera.
MR. BROOKS (CONT'D) That way we can like each other simply for who we are.
MR. BROOKS (CONT'D) If you don't show up, I will presume you've gone to the police and I will kill you.
MR. BROOKS (CONT'D) Even if I go to jail because of you, someone will find you wherever you are and kill you.
The penlight goes off.
There's total silence.
MR. SMITH Mr. Brooks?...
He squints into the black.
MR. SMITH Mr. Brooks?...
Finally he gathers the courage to extend a shaky hand.
The bedside lamp goes on.
The room is empty.
Cautiously Mr. Smith swings his legs out of bed and stands up.
He forces himself to go to the door and from there curls his arm around the jamb into the darkness.
The HALL light is dazzling.
A peek into the BATHROOM shows there is nobody there.
He continues on into the LIVING ROOM.
His camera equipment is on the table.
The tripod is still set up.
There is no sign of Mr. Brooks.
Mr. Smith eyes the front door.
It's closed and the 'security chain' is in place!!
Another quick scan of the room.
It sure seems that he's alone.
He opens the front door the length of the chain and looks up and down the hallway.
It's empty.
Slowly he closes the door.
Standing in the light of his LIVING ROOM, Mr. Smith is more scared and strangely more excited than he's ever been in his life.
MR. SMITH Wow!...
In a robe and pajamas, Mr. Brooks comes down the HALLWAY carrying a glass of milk.
The door to his Daughter's ROOM is partly open.
By the nightlight in the plug at the head of the bed he can see she's asleep.
Mr. Brooks walks to the bed, leans over and kisses his Daughter on the cheek.
MR. BROOKS It's nice to have you home.
He leaves.
The early rays of the sun are moving down the tall buildings.
A garbage truck is picking up the trash.
Dressed for work and a smile on his face, Mr. Brooks comes down the stairs.
In the BREAKFAST ROOM, the mood is decidedly different.
His Wife and Daughter are leaning against opposite walls staring at the floor.
MR. BROOKS What's wrong?
EMMA Ask your daughter what the real reason is she dropped out of school.
JANE I keep telling you it's not the reason.
EMMA You wanted to go to college, you had good grades in High School, your father helped you get into Stanford, we're paying a ton of money, if this is not the reason, then please dear God tell me the reason.
MR. BROOKS Why does your mother think you dropped out of school?
JANE I'm pregnant.
JANE And it's not the reason I dropped out.
JANE Being pregnant wouldn't stop me from going to school if I wanted to go.
MR. BROOKS Who's the father?
JANE Some guy I was seeing.
EMMA Does he know?
JANE Yes, he's a married man and he doesn't want to have anything to do with me.
EMMA Oh, Honey, I'm so sorry.
JANE I'm going to have an abortion anyway, so there is nothing to get upset about.
JANE I wasn't even going to tell you guys.
Mr. Brooks looks directly at his Daughter.
MR. BROOKS There will be no abortion.
JANE Daddy, you are not going to tell me what to do.
JANE It's my body and I will do what I want to do with it.
Mr. Brooks's eyes find Emma's.
Almost imperceptibly she shakes her head 'no'.
MR. BROOKS You're right.
MR. BROOKS I'm sorry.
MR. BROOKS I said it wrong.
MR. BROOKS I'm not trying to tell you what to do.
MR. BROOKS I'm trying to say that a grandchild would be a wonderful gift for your mother and me.
EMMA Please, Honey, don't have an abortion.
JANE Would you really want to have a grandchild, even though I'm not married?
MR. BROOKS Yes.
MR. BROOKS The child is what's important.
MR. BROOKS We would love it and cherish it completely and help you raise it.
JANE If it means that much to you, I'll think about it.
Walking to the Lexus, Mr. Brooks notices Marshall waiting for him on the passenger side.
MR. BROOKS Well, we were right, she was hiding something.
MARSHALL Pregnant's not all of it.
MARSHALL She's hiding something bigger.
MARSHALL Much bigger.
MR. BROOKS You think so?
MARSHALL I know so, and so do you.
Large and small Color Photographs pinned to a corkboard create a Collage of the dance Couple murder scene.
Standing in front of this is CAPTAIN LISTER, a tall slim open- faced Woman in her mid-fifties, and the lead Crime Scene Technician we saw earlier at the Murder House.
TECHNICIAN It's not what's here, it's what's not here that's interesting.
TECHNICIAN There's not a trace of anything foreign.
TECHNICIAN If I didn't know better I'd say these people were killed by a ghost.
CAPTAIN LISTER The autopsy found a tiny piece of plastic in the female victim's brain.
TECHNICIAN We're checking with the ammunition manufacturers.
DETECTIVE ATWOOD That's a dead end, he bags the gun.
TECHNICIAN I don't understand.
DETECTIVE ATWOOD He ziplocks a one gallon plastic freezer bag to his wrist over the gun.
DETECTIVE ATWOOD Bang.
DETECTIVE ATWOOD Bang.
DETECTIVE ATWOOD A little bit of plastic is carried by the first slug, the ejected shells go into the bag and it limits the powder residue.
DETECTIVE ATWOOD I hear you were looking for me.
CAPTAIN LISTER Sigy...
SIGY (TECHNICIAN) Yeah, okay...
SIGY (TECHNICIAN) Did you find anything?
SIGY (TECHNICIAN) Did they have enemies, did they owe money, did anybody ever notice someone watching the house?
DETECTIVE ATWOOD So far they are Mr. and Miss Normal.
SIGY If you find anything, call, it might help me.
He's gone.
CAPTAIN LISTER I received a subpoena from your husband's lawyer for your work records, where you were, date and times for the past two years.
DETECTIVE ATWOOD That's blackmail.
CAPTAIN LISTER Almost three quarters of your cases are current.
CAPTAIN LISTER I can't let that information go into open court.
CAPTAIN LISTER So until you settle your divorce, I'm going to have to put you on a desk.
DETECTIVE ATWOOD That's also blackmail.
CAPTAIN LISTER That's one of your big problems, Atwood, you don't know how to ask for help.
DETECTIVE ATWOOD Do you know what he did to me?
CAPTAIN LISTER You can't grow old as a woman without having at least one lousy man in your life.
DETECTIVE ATWOOD I was so stupid.
DETECTIVE ATWOOD While we were married, while I paid for him to live, the son of a bitch fucked every woman he could get his hands on.
DETECTIVE ATWOOD He fucked my friends, he even fucked a cousin of mine.
DETECTIVE ATWOOD Everyone knew but me, and they were laughing at me behind my back.
DETECTIVE ATWOOD He made me look like an idiot.
DETECTIVE ATWOOD I was a joke.
CAPTAIN LISTER And?...
DETECTIVE ATWOOD And what?
CAPTAIN LISTER Get over it.
DETECTIVE ATWOOD I made him an offer.
DETECTIVE ATWOOD I'm not going to give him one red cent more.
CAPTAIN LISTER I hear what he's asking for, you could take out of pocket change.
CAPTAIN LISTER Do that and go on with your life.
DETECTIVE ATWOOD I couldn't live with myself if I did.
CAPTAIN LISTER I'll spread your work among the other guys and the FBI will be here on thursday...
CAPTAIN LISTER ...
CAPTAIN LISTER they'll take over this case.
DETECTIVE ATWOOD Please, these are my cases.
DETECTIVE ATWOOD Nobody knows them like me.
DETECTIVE ATWOOD Don't give them away and don't give the Thumbprint Killer to the FBI.
DETECTIVE ATWOOD He's killed people in twelve other states, let them fuck up those investigations.
DETECTIVE ATWOOD This one's mine.
CAPTAIN LISTER You heard Meeks escaped?
DETECTIVE ATWOOD Yeah.
CAPTAIN LISTER Do you want a detail on you in case he comes after you?
DETECTIVE ATWOOD I can take care of myself.
CAPTAIN LISTER You're a good cop, Tracy, I don't want to lose you, but you have to help me if you want me to help you.
Atwood is waiting for an elevator.
It arrives.
The doors open.
The car is empty.
Atwood gets in and presses the key for her destination, then slumps into a corner for the ride.
The doors close.
The elevator begins to move.
All at once Atwood screams.
Her pent-up anger and frustration rip the air and she goes nuts.
She punches the wall of the elevator, kicks it, throws herself to the other side, bangs her head against that wall, punches it, kicks it, all the while screaming.
Then the tears come.
The screams stop and she settles upright against the back wall, where she strikes her chest repeatedly with the flat of her closed hand.
DETECTIVE ATWOOD What is wrong with me?
DETECTIVE ATWOOD What is wrong with me?
DETECTIVE ATWOOD What is wrong with me?
It's raining.
The yellow Police tape that still circles the yard snaps in the wind.
Up the driveway, out of sight of all the other homes, there's a movement at the side door of the house.
A closer inspection reveals that it's Detective Atwood.
From under her umbrella she studies her surroundings and as if she's speaking to the killer, she speaks to herself.
DETECTIVE ATWOOD Did you choose them because of where they lived or how they looked or what jobs they had?
DETECTIVE ATWOOD Or did you just pick them because at the instant you saw them, you had decided to kill someone?
DETECTIVE ATWOOD The side door was perfect.
DETECTIVE ATWOOD No one could see you pick the lock.
With a key she lets herself in.
Parked against the curb opposite the driveway of the Murder House is an old green Pontiac Convertible with the top up.
The driver's window is down and from inside a WOMAN, late 20's, is watching the house.
Atwood stops in the PANTRY almost in the exact spot where Mr.
Brooks stopped.
The quiet is filled by the rain drumming on the roof.
The wind rattles the windows.
DETECTIVE ATWOOD How did you know where they were in the house?
She steps into the KITCHEN.
On the way across she bumps into a chair.
DETECTIVE ATWOOD It's darker tonight than it was on your night.
DETECTIVE ATWOOD But still how did you manage not to bump into the furniture?
DETECTIVE ATWOOD Did you have a little light?
DETECTIVE ATWOOD That would be too dangerous.
DETECTIVE ATWOOD I'll bet you were in the house before.
DETECTIVE ATWOOD (CONT'D) So I should ask the neighbors if they saw a meter reader around the house or a telephone repairman or someone from the gas company.
These musings take her through the LIVING ROOM to the entrance of the HALLWAY where she pauses and looks both ways.
DETECTIVE ATWOOD Once again, how did you know where they were?
DETECTIVE ATWOOD Did you check the rooms before you found them?
DETECTIVE ATWOOD She had his semen in her vagina, they had just made love, did you hear them or was there a light on?
She steps into the HALL.
DETECTIVE ATWOOD And when did you bag the gun?
DETECTIVE ATWOOD Because even though I'm sure you're an expert at it, there's still a chance of noise from the plastic.
She continues down the HALL to the BEDROOM.
DETECTIVE ATWOOD Was the door open or did you have to open it?
She opens the door and goes in.
DETECTIVE ATWOOD Were they asleep or awake?
DETECTIVE ATWOOD Was the light on, or did you turn it on?
DETECTIVE ATWOOD Because I know you, you wouldn't risk a shot in the dark.
She turns on the overhead light.
DETECTIVE ATWOOD Too bright.
DETECTIVE ATWOOD What if it wasn't that light that was on, but this one?
She turns on a bedside light and goes back to the door and turns off the overhead.
If the dance Couple were on the bed and their blood was not on the wall, the room would look exactly the way it did when Mr. Brooks said 'hello'.
DETECTIVE ATWOOD That's better...
DETECTIVE ATWOOD What thrill do you get by killing people?
DETECTIVE ATWOOD Is it sexual, is it hate, is it power?
DETECTIVE ATWOOD Do you feel remorse?
DETECTIVE ATWOOD Probably that part of your brain doesn't exist.
DETECTIVE ATWOOD Do you have emotions of love or affection or joy?
DETECTIVE ATWOOD Or have you learned to fake them so you won't stand out in a crowd.
She's at the window now, feeling the curtains.
DETECTIVE ATWOOD What if these are stuck closed because you yanked them closed?
DETECTIVE ATWOOD Which means they were open when you came into the room.
She separates the fabric and looks out the rain-streaked window at the four story building across the alley.
There are lights on in almost all the apartment windows.
DETECTIVE ATWOOD If Mr. and Miss Normal made love with the curtains open and the lights on, someone in that building noticed them and may have seen you.
She allows the fabric to drop back into place and turns to look at the bed.
DETECTIVE ATWOOD Was that what you were angry about?
Moving slowly across a neutral colored wall.
DETECTIVE ATWOOD Thank you for your time.
A door is closed.
We come to the corner and are looking down a HALLWAY at Atwood coming toward us.
We move to her and arrive just as she raises her fist to knock.
Before she can, the door opens and she and Mr. Smith who is on his way out of his Apartment are surprised that the other one is suddenly there.
Each one takes a half step back.
Phwap!
The manila envelope that was wedged under Mr. Smith's left arm hits the floor.
MR. SMITH Oh!
MR. SMITH You scared me.
DETECTIVE ATWOOD I'm sorry...
DETECTIVE ATWOOD ...
DETECTIVE ATWOOD I was about to knock.
DETECTIVE ATWOOD I'm Detective Atwood with the Chicago Police.
MR. SMITH Thank you.
Through the open door, Atwood can see Mr. Smith's camera on a table and the collapsed tripod leaning against the wall.
DETECTIVE ATWOOD Are you a photographer...
DETECTIVE ATWOOD Mr. Baffert?
MR. SMITH No...
MR. SMITH eh, it's kind of a hobby, I just started.
DETECTIVE ATWOOD I don't know if you're aware but there was a murder...
MR. SMITH Oh, yes in the house across the alley...
DETECTIVE ATWOOD Did you happen to see anything unusual or suspicious that night around that house?
DETECTIVE ATWOOD Anything at all?
Mr. Smith puts on his thinking expression and pauses a little bit before:
MR. SMITH No...
MR. SMITH I wondered that when I heard what happened, but...
MR. SMITH no.
MR. SMITH I'm sorry, I'm meeting someone and I don't want to be late.
He moves into the Hallway closing the door behind him.
DETECTIVE ATWOOD Here's my card, if you hear anything or remember anything.
MR. SMITH I wish I could be of more help, but sorry.
Watching him walk away amid the crinkle of his raincoat, Detective Atwood, maybe because of her woman's intuition or maybe because she's a good cop, wonders what is in that manila envelope under his arm.
The thought is gone almost as soon as it comes and she faces about to the next door.
Hunched against the rain, Mr. Smith is acutely aware of the traffic.
His eyes strain to see the Occupants of each passing car.
He doesn't give a second thought to the older non- descript Toyota parked against the far curb.
Mr. Brooks is in the driver's seat.
Marshall is in the back.
They're both tracking the progress of Mr. Smith.
MR. BROOKS He looks clean.
MR. BROOKS He looks like he's alone.
MARSHALL No, I'm telling you he wants to do this.
MR. BROOKS I guess I should turn around and go pick him up.
MARSHALL Nah.
MARSHALL Just honk.
MARSHALL Maybe he'll get killed crossing the street and save us the mess of doing it.
Honk!!
Honk!!
Mr. Smith looks around.
He's not sure that sound was for him.
But when the Toyota honks again and flashes it's lights, Mr. Smith waves and splashes to the center of the street.
Even though he stops to let it pass, a car sounds its horn and swerves to avoid him.
Mr. Smith crosses behind the Toyota and opens the passenger door.
Mr. Smith flops into the seat.
MR. SMITH Woof!
MR. SMITH It's really coming down out there.
MR. BROOKS They say it'll be sunny tomorrow.
Mr. Smith fumbles with the buttons and zipper on his raincoat.
MR. SMITH I never trust those guys, when they say it's going to be clear it always rains and when they say it's going to rain, it's sunny.
He comes up with the manila envelope.
MR. SMITH Here's what you asked for.
Mr. Brooks takes it and hefts it.
MR. BROOKS The pictures and the memory card all here?
MR. SMITH Yeah.
MR. BROOKS You and I both know that not all the pictures are in here and you made a copy of the Memory Card, isn't that so?
MR. SMITH But you understand my position.
Mr. Brooks favors him with a wolfish smile.
MR. BROOKS Yes, I do.
MR. BROOKS But it's my hope that once you get to know me better you'll feel comfortable in giving me all that I've asked for.
MR. SMITH That sounds fair.
MR. SMITH Oh, I almost forgot.
MR. SMITH I thought you might be interested in this.
His hand comes forward with a card.
MR. SMITH It's the policewoman who's looking for you.
Marshall snaps forward from the back seat.
MARSHALL Wow!
MARSHALL We've never known anyone who's looking for us before.
Mr. Brooks pinches the rectangle of paper away from Mr. Smith for a closer view.
MARSHALL We've got to find out everything there is to know about this woman.
MR. BROOKS This is too close, Marshall, too damn close.
Mr. Smith interrupts Mr. Brooks's focus on Detective Atwood's card.
MR. SMITH So, what do we do now?
MR. SMITH What's the plan for the evening?
Mr. Brooks slips the envelope under the seat and starts the car.
MR. BROOKS We drive around until we see someone we think we might enjoy killing.
MR. SMITH Really?
MR. SMITH That's it?
MR. SMITH I thought you might already have someone in mind.
BROOKS I don't enjoy this, Mr. Smith.
BROOKS I do it because I'm addicted to it.
BROOKS And before you entered my life I had vowed I would never kill again.
BROOKS So this is your party, you can chose anyone you want and we'll do it together.
MR. SMITH Can it be someone I know?
MR. BROOKS You never kill someone you know.
MR. BROOKS That's the easiest way to get caught.
The Toyota enters the traffic.
An older WOMAN in a Stewardess uniform is standing in the doorway of her apartment.
Atwood is in front of her in the
STEWARDESS I wasn't in town that night, my roommate was, maybe he saw something.
DETECTIVE ATWOOD May I speak to him?
STEWARDESS He's on his way to Tokyo now, he's also a Flight Attendant.
DETECTIVE ATWOOD Did the victims ever leave the curtains in the bedroom open?
STEWARDESS All the time.
STEWARDESS I don't know if they thought we couldn't see them "fucking" or they didn't care.
DETECTIVE ATWOOD Here's my card, could you ask your roommate to call me when he gets back, the people at that number will find me any hour of the day or night.
STEWARDESS I won't be here, but I'll leave him a note.
Mr. Brooks' Toyota is cruising in the flow of traffic.
MR. BROOKS (V.O.) ...
MR. BROOKS (V.O.) maybe I already know how to pick the locks on the house, if I don't...
BROOKS ...
BROOKS I buy one of those locks and I practice on it, same with the alarm...
BROOKS some I know how to bypass, some I have to study.
MR. SMITH You don't mind me asking these questions?
MR. BROOKS No.
MR. BROOKS This is your first time, you're interested.
MR. BROOKS And you should be if you're...
A neutral-colored PICKUP swerves out of the next lane into Mr. Brooks' lane.
MR. SMITH Jesus Christ!!
Mr. Brooks is forced to slam on his brakes to avoid running up the PICKUP'S tailpipe.
HOONKK!!!
Mr. Brooks angrily lays on the horn.
The brake lights of the PICKUP flash in response causing Mr.
Brooks to brake again.
MR. SMITH Fuck him!!
MR. SMITH It was his fault!!
MR. SMITH What an asshole!!
MARSHALL Maybe Mr. Smith would like to kill the driver of the pickup.
MR. BROOKS What about the driver of the pickup?
MR. BROOKS What if we killed him?
MR. SMITH Oh, fuck, yes!!
MR. SMITH I've always wanted to kill someone who fucked with me in traffic.
The PICKUP makes a right onto a side street.
Mr. Brooks follows.
MR. BROOKS Do you want to kill the driver of the pickup or the owner, they may not be the same.
MR. SMITH The driver.
MR. BROOKS Okay we'll follow until we get a look at him, or her; would it bother you to kill a woman?
MR. SMITH No.
MR. SMITH An asshole's an asshole.
Mr. Brooks begins to slow down.
MR. SMITH What are you doing?
MR. BROOKS The asshole shouldn't know we've decided to follow him, or her.
Detective Atwood is on her way out the Outer Door when the hair on the back of her neck stands on end.
Footsteps can be heard running toward her through the rain.
Her hand goes under her jacket and comes out holding a Glock 9mm.
She sidesteps out of the light into the grayness at the edge of the doorway.
Now she sees the RUNNER.
A hood hides the face.
She can't tell if it's a Man or a Woman.
Detective Atwood thumbs the Glock's safety to the 'off' position.
The Runner passes, white breath coming from an unseen mouth.
She waits while the Figure recedes, then with the gun still in hand she fishes into a pocket for a cell phone and heads in the opposite direction.
A finger speedials a number.
After a second ring a:
MALE VOICE Yes?
DETECTIVE ATWOOD It's Tracy.
DETECTIVE ATWOOD Can you carve out some time for me tonight?...
DETECTIVE ATWOOD I'll be home in an hour and a half.
DETECTIVE ATWOOD I'll see you there.
The phone is shut, the umbrella unfurled and the darkness swallows her up.
The neutral-colored Pickup is parked in front.
The DRIVER gets out.
It has stopped at the curb just beyond the Entrance to the Mini-Mart parking lot.
Mr. Brooks and Mr. Smith watch the DRIVER come around the front of another car before entering the store.
The light reveals the Driver to be a tall middle-age preppie guy with close cropped dark hair and dark-rimmed glasses.
MR. BROOKS Would you recognize him if you saw his driver's license picture?
MR. SMITH Yeah.
MR. BROOKS I've memorized the license number, you write it down.
MR. BROOKS When you get home go on the Internet and find out everything you can about this guy.
MR. SMITH We aren't going to kill him tonight?
MR. BROOKS No.
MR. BROOKS We could, but then we wouldn't be in control.
MR. BROOKS We could leave loose ends, and we both know the danger of that.
MR. SMITH I got it.
MR. BROOKS Look at me.
Mr. Smith does.
MR. BROOKS Close your eyes.
MR. BROOKS What's the number?
MR. SMITH VF...
MR. SMITH eh...
Mr. Smith opens his eyes and grins sheepishly.
MR. BROOKS Don't feel bad, I've been doing this a long time...
MR. BROOKS Pen, paper.
MR. BROOKS Write it down.
MR. SMITH What was your first time?
BROOKS You really don't want to know that much about me, Mr. Smith.
The lane lines are in place.
Detective Atwood is the only one in the water.
Up and down she goes with a long smooth stroke flipping the turns.
She's not swimming for pleasure, she's working out.
The underwater lights cast rippling shadows on the walls and ceiling and since they are the only illumination, the room feels spooky.
Atwood's fingers touch the wall.
She raises her head to check her time, then takes off her goggles.
Hanging onto the gutter she tries to catch her breath, lowers herself under the surface, blows a lungful of bubbles, comes up to face LARRY, a Man slightly younger than she is, in a beautiful suit, perched on the edge of the deck looking down at her.
He has a dress on a hangar over one shoulder and a pair of shoes dangling from the fingers of his other hand.
DETECTIVE ATWOOD Hi.
LARRY Hi.
LARRY I brought a dress and a pair of shoes.
LARRY I thought we could leave from here.
DETECTIVE ATWOOD Great idea.
She lifts herself to him and they kiss.
Detective Atwood and Larry are at a balcony table overlooking a well-populated dance floor.
The Music is 40's and 50's performed by a live BAND.
LARRY ...
LARRY I gave him my driver's license, my student ID, he didn't look anything like me, luckily they never checked.
DETECTIVE ATWOOD I did something like that except I was the one who took the test.
DETECTIVE ATWOOD It wasn't math, a friend of mine was a theology major and needed a second language to get into the Master's program...
LARRY She started her career in theology with a lie?!
DETECTIVE ATWOOD Isn't that what all theology is based on?
LARRY Did you pass the test?
DETECTIVE ATWOOD Oh yeah...
LARRY Don't tell me she ended up as Mother Teresa or the Pope.
DETECTIVE ATWOOD No, she realized very quickly there wasn't enough money in religion for her, the last I heard she'd written a diet book that was very successful.
LARRY She stayed in religion.
Atwood smiles, her fingers find Larry's and they intertwine.
The view floats over the balcony.
As it slowly drops, the PEOPLE on the dance floor, Couple by Couple, disappear until there are only three Couples left, one of them is Atwood and Larry.
Her head is on his shoulder.
It's a slow dance.
Larry is very good and wherever he leads, Atwood easily follows.
The lights begin to dim and we move in.
Larry touches his lips to Atwood's neck.
She arches back and he kisses her neck again and again.
His lips move up and find hers, and we are now close on the kiss.
Gently the lips separate and we slowly retreat.
Looking into her eyes, Larry traces her lips with a finger, then replaces that finger with his tongue.
His lips brush a cheek, down her neck to where it meets her shoulder, his teeth close softly on the muscle, by now we are far enough away to realize that Atwood and Larry have no clothes on and we are:
What light there is, is coming from a room we can't see.
Larry nibbles at Atwood collarbone, kisses a breast, strokes his hands down her sides.
She shivers.
He brushes his lips back and forth across her stomach and then down to where the flesh of her belly meets her pubic hair.
She's watching all of this in a mirror on the opposite wall.
Then he sinks to his knees and buries his head between her legs.
From low in her throat, Atwood moans.
We lose sight of the Couple as we move around a corner.
It's dark.
Atwood is propped up against the headboard, the sheet pulled up over her breasts.
The door to the BATHROOM opens.
Larry dressed in his suit, minus the tie, comes out, kneels on the bed and kisses her.
LARRY Thank you, this was wonderful.
DETECTIVE ATWOOD For me too.
LARRY I'll see you then?
DETECTIVE ATWOOD I'd like that.
DETECTIVE ATWOOD The money is in the usual place.
LARRY It's not just the money, Tracy.
LARRY I like you.
DETECTIVE ATWOOD I like you too, Larry.
DETECTIVE ATWOOD Send me a bill for the dress and the shoes.
LARRY I will.
LARRY Good-night.
DETECTIVE ATWOOD Good-night.
The rain is muffled by the trees.
Move slowly toward the Building then up the side to peek through the narrow window that circles just below the roof line.
In the center of the room, the kiln relieves the darkness with a yellow red glow whose rim touches a slash of white light coming from under a door tucked in a corner.
We creep through the white light across the floor that's littered with splashes of paint and smears of clay to the office door and peer under it.
In front of us are chair casters and two bare feet and legs.
MARSHALL I think that was right.
MARSHALL Go back.
MR. BROOKS We're in.
MARSHALL With the taxes we pay, you'd think they could make it more difficult to hack into the Police personnel files.
We tip toe under the door.
It's crammed with file cabinets.
Sketches for pottery pieces are taped to the walls along with photos of Mr. Brooks, Jane and Emma.
Mr. Brooks, clad only in a T-shirt and underwear, is sitting in front of a computer.
Marshall, dressed as he usually is, is in a chair at his side.
They are both staring at the monitor where on one side of the screen is Detective Atwood's Police ID photo, on the other side of the screen, Mr. Brooks is scrolling through her personnel file.
MR. BROOKS ....
MR. BROOKS Huh...
MR. BROOKS her father's Gerald Atwood, why does that ring a bell?
MARSHALL Someone you did business with, someone we killed?
MR. BROOKS Not someone we killed...
MR. BROOKS MBA...
MR. BROOKS College of William and Mary...
MR. BROOKS she's been a cop for eleven years...
MR. BROOKS Married Doctor Carlson, divorced Dr. Carlson, married Jesse Vialo...
MR. BROOKS restaurateur...
MR. BROOKS separated from Jesse Vialo, sued for support by Jesse Vialo, seeing a shrink because of Jesse Vialo...
MARSHALL Excellent fitness report though.
MR. BROOKS She caught the Hangman, the guy that escaped the other day...
MARSHALL Oooh...
MARSHALL She's caught a lot of people...
MARSHALL And look here, this isn't the first time she's been hunting for us.
MR. BROOKS I wonder what the deal was with her and Jesse Vialo?
Mr. Brooks taps a key that minimizes Atwood's file then drags it to the right hand corner.
In the middle of a key stroke it hits him:
BROOKS Ahhhh...
BROOKS now I remember.
BROOKS Her father, Gerald Atwood, never did business with him but Emma and I met him a couple times, big political fundraiser.
BROOKS He owns or owned one of the largest insurance groups in the country and a lot of other stuff.
Tap, tap, tap.
Jesse Vialo's Driver's license comes up.
MR. BROOKS Jesse Vialo...
MR. BROOKS Good looking, a little younger than she is.
MARSHALL Younger, restaurateur...
MARSHALL She married him on the rebound from the doctor and I'll bet he married her for her money and her connections.
MR. BROOKS The old man being rich doesn't mean she's rich.
MR. BROOKS Maybe he's one of those guys who would rather give it to the Opera than to his kids.
MARSHALL Wouldn't she have to declare any outside income and holdings to the Police?
MR. BROOKS Hmmm...
He restores Atwood's file.
Tap, tap, tap, tap.
Stop.
The Men study the screen then look at each other.
MR. BROOKS The Opera didn't get much.
MARSHALL Why would a woman with her education and worth 60 plus million dollars and probably more to come, want to be a cop?
MR. BROOKS I like that about her.
MARSHALL You're such a fucking snob, Earl.
MARSHALL You like her because she's rich.
MR. BROOKS No, I like her because she found something that's hers.
MR. BROOKS It's not the family business.
MR. BROOKS And she's good at it.
MR. BROOKS I'd like Jane to find something that's hers and that she could be good at.
MARSHALL That's exactly why Atwood scares the shit out of me.
MARSHALL She's a cop who doesn't need the money and she's looking for us.
MARSHALL That's one fucking dangerous human being.
MR. BROOKS The fact that you're not wrong doesn't make me admire her any less.
At a table the Asian Attorney is going over a brief.
There are two foamy coffees in to-go cups in front of her.
Detective Atwood arrives at the table.
DETECTIVE ATWOOD Hi...
She reaches out, the Women shake hands.
ASIAN ATTORNEY Hi.
ASIAN ATTORNEY I got you a Latte.
DETECTIVE ATWOOD Thanks and thanks for meeting me here.
ASIAN ATTORNEY We got an injunction to quash the subpoena for your work records yesterday.
ASIAN ATTORNEY They've already appealed.
DETECTIVE ATWOOD That doesn't help me does it?
ASIAN ATTORNEY Your father has a lot of political muscle.
DETECTIVE ATWOOD My father does nothing for nothing.
ASIAN ATTORNEY I understand.
ASIAN ATTORNEY If you're willing to play the game and ride a desk for a year; I think we can settle for one two five, one five.
DETECTIVE ATWOOD No desk.
ASIAN ATTORNEY Then the only other option is money.
ASIAN ATTORNEY Tell me how high you are willing to go.
DETECTIVE ATWOOD One five.
ASIAN ATTORNEY I can try.
ASIAN ATTORNEY If I were on the other side I'd hold out for more.
DETECTIVE ATWOOD How much more?
ASIAN ATTORNEY Give me a cap and that's how high we'll go.
DETECTIVE ATWOOD Try and get a number out of them first.
DETECTIVE ATWOOD I want to know what ballpark I'm playing in and if it's a lump sum, is it less than something that's paid in installments.
ASIAN ATTORNEY I'll call them today.
Atwood stands up with her coffee.
DETECTIVE ATWOOD I'd like to get this done as soon as possible.
The Asian Attorney also stands and gathering her papers and coffee.
ASIAN ATTORNEY Are you working on the Thumbprint Killer this time?
DETECTIVE ATWOOD Yeah.
ASIAN ATTORNEY That one's creepy to me.
ASIAN ATTORNEY The doors are locked, the alarms are armed and the people are dead.
ASIAN ATTORNEY It makes you feel like you're not safe anywhere.
Atwood nods and opens the front door then follows the Attorney out.
DETECTIVE ATWOOD Where are you parked?
ASIAN ATTORNEY I'm right over there.
DETECTIVE ATWOOD I'm down the street.
DETECTIVE ATWOOD Call me as soon as you have something.
She starts to walk away.
ASIAN ATTORNEY Oh, Tracy...
ASIAN ATTORNEY I almost forgot, your husband says there's a picture of him holding some trophy that you still have.
DETECTIVE ATWOOD He took all those pictures.
DETECTIVE ATWOOD He took everything.
ASIAN ATTORNEY He claims it's his favorite picture and you put it up where you store your suitcases.
DETECTIVE ATWOOD I'll look.
ASIAN ATTORNEY I know it's petty, but you're going through a divorce.
Atwood strides toward her car.
The PEDESTRIAN traffic is light.
It's too early for the stores to be open.
Up ahead a BROWN VAN is idling at the curb, the sliding side door is open.
Atwood can see inside.
Empty except for some furniture blankets.
The Person in the Driver's seat turns to look into the back.
It's the Woman who was watching Atwood outside the Murder House.
Her hands are unseen in leather gloves.
She looks up and their eyes meet.
Two strangers.
The contact is instantly broken.
Atwood takes a deep breath and smiles.
After the rain, the air is brisk and clean.
It's good to be alive.
SLAM!!!
Atwood is body-checked by a Man who springs out of the recess of a doorway.
His arms wrap around her, she's lifted off her feet and the Man throws himself and her into the Van.
Oooff!!
The wind is knocked out of Atwood when she lands left shoulder first on the furniture blankets, the Man on top of her.
The Man is Thorton Meeks, the Hangman, six feet, a solid two hundred pounds.
He's also wearing tight leather gloves.
The Brown Van accelerates fast away from the curb.
His body crushing hers, Meeks kisses Atwood's cheek.
MEEKS Surprise, surprise, Tracy.
MEEKS I told you I was coming back to get you.
He frees his right hand and pulls his gun.
MEEKS I already know where I'm gonna hang you.
MEEKS But first I'm gonna watch her...
MEEKS ...
MEEKS have some fun with you, then she's gonna watch me have some fun with you.
He kisses her again and puts the gun to Atwood's head.
MEEKS Now, don't move.
He raises up and straddles her.
MEEKS You know the drill, I'm gonna put the cuffs on.
With his left hand he fishes a pair of handcuffs from a back pocket and snaps them on Atwood's right wrist.
MEEKS Now the left.
He rolls Atwood on her back and with the chain of the handcuff pulls her right arm toward her left.
All Meeks' talk has allowed Atwood to catch her breath and suddenly she jerks her head up into the gun and screams at the top of her lungs.
At the same time she pulls hard against the handcuff with her right wrist.
A startled Meeks is thrown off balance.
The gun comes away from Atwood's head.
Her left arm now free, Atwood swings her palm with all of her might into Meeks' right ear.
POP!!
His eardrum breaks.
Aaaggh!!
He instinctually reaches to cover the damaged ear with his gun hand.
The Driver doubles around to see what's happening.
From outside, HOONNNKK!!
The Driver's attention returns to the road.
Atwood swings again.
This time she snags the barrel of the gun and using it as a lever bends Meeks' hand back on the wrist.
BLAM!
The gun goes off.
Neither one of them is hit.
At the same time Atwood pulls hard on the handcuff that Meeks is holding in his left hand and twists into him.
This dislodges Meeks and he's off of her.
Snarling like animals they fight for the gun.
CRACK!
Atwood's leverage breaks Meeks' trigger finger.
His grip loosens on the weapon.
She pulls it out of his hand.
A quick push skitters it across the floor.
It drops through the open side door into the street.
Atwood rolls away and reaches for her ankle gun.
Now it's Meeks' turn.
A sharp tug on the chain of the handcuff stalls her motion.
He flicks his other arm and a switchblade is delivered into his right hand.
Snap!!
The blade comes out.
Atwood is reaching again for her ankle gun.
She sees the flash of metal and flings her head back.
Luckily all she receives is a deep gash above her right eye.
Blood immediately begins to cascade over her brow.
Meeks grins and gives another sharp tug on the handcuff to pull Atwood into the range of his knife.
With one foot Atwood kicks at him, with the other she pushes off and propels herself backward to grab a handful of the Driver's hair.
Atwood's weight hinges the Driver's head back until she's looking at the ceiling.
Her scream is equal parts pain and surprise.
The Brown Van veers into the on-coming traffic.
The Driver of the car dead ahead swerves.
The Van solidly clips the rear of that car.
The sudden deceleration of that impact slingshots Atwood and Meeks forward.
She hits the back of the Driver's seat.
Meeks has further to go.
He loses his hold on the handcuffs and smashes into the passenger seat.
Her right hand now free, Atwood scratches for the gun on her hip.
Careening across its lane, the Van sideswipes a parked car.
That impact rips Atwood's hand out of the Driver's hair and sends her sliding on her knees toward the side door.
On her way she unclips her gun and is bringing it out of her holster when Meeks who has managed to hang onto the passenger seat sees this and slams a foot into her chest.
Atwood is launched backward out the side door.
In slow motion Atwood flies through the air while at normal speed the Van is leaving her behind.
SMASH!
Butt first, Atwood hammers into the back window of a parked car.
The shattering glass breaks her fall.
Groggily she rolls out of the indentation.
Gun still in hand and blood covering one side of her face she slides off the car to stand in the street.
The Van is nowhere in sight.
Captain Lister is watching a DOCTOR sew up the gash on Detective Atwood's forehead.
CAPTAIN LISTER We found the van in an underground lot about two miles from where they left you.
CAPTAIN LISTER It was stolen last night.
Detective Snyder comes in and hands a packet of photographs to Atwood.
SNYDER These are the women we have pictures of who know Meeks.
CAPTAIN LISTER Meeks and the Woman, none of the Attendants remember seeing them.
As Detective Atwood begins to go through the pictures.
DETECTIVE ATWOOD That chiropractor, Alvin Griffin, who sold Meeks his steroids, he might know where he is.
CAPTAIN LISTER His phone's been tapped since Meeks escaped.
CAPTAIN LISTER No contact that way so far and he's sure not going to talk to us.
DETECTIVE ATWOOD What about a warrant to search his house?
DETECTIVE ATWOOD Get me in the door and he'll talk to me.
CAPTAIN LISTER How's your divorce going?
DETECTIVE ATWOOD I took your advice and told my lawyer to settle.
Stretching out her arm to return the photos:
DETECTIVE ATWOOD None of these is the woman in the van.
DOCTOR Whoa...
DOCTOR I'm sewing up your head here.
DETECTIVE ATWOOD Sorry.
CAPTAIN LISTER And your ego can handle that?
DETECTIVE ATWOOD It doesn't like any of the other choices.
CAPTAIN LISTER Until Meeks is caught, Snyder is with you.
DETECTIVE ATWOOD Nothing personal, Snyder.
DETECTIVE ATWOOD He's not part of our team.
CAPTAIN LISTER He's there to protect you.
CAPTAIN LISTER And listen to him, he's been alive longer than you have.
SNYDER I didn't volunteer for this, Atwood.
CAPTAIN LISTER The Parking Lot has a security camera.
CAPTAIN LISTER We're checking the tape.
CAPTAIN LISTER If Meeks and the Woman left in a car we'll have a license number.
CAPTAIN LISTER You have two days then I want a progress report on your divorce.
DETECTIVE ATWOOD I think I have all the pieces on the Thumbprint Killer, I'm just not looking at them the right way.
CAPTAIN LISTER Okay, you have three days.
She leaves.
DETECTIVE ATWOOD Every babysitter I ever had loved me.
In the scattering of vehicles Mr. Brooks' Toyota is hidden in plain sight in a row of cars.
Behind the wheel, Mr. Brooks is again wearing his Pottery- Throwing clothes.
Mr. Smith is in the passenger seat and Marshall is leaning forward from the back.
They're all focused to varying degrees on the Entrance to the store.
Mr. Smith raises his watch for a look at the time.
MR. SMITH Maybe he went home with someone else.
MR. BROOKS Can you still see his pickup?
Mr. Smith looks.
MR. SMITH Uh huh.
MR. BROOKS This is not the kind of guy who leaves his pickup in an unguarded Lot overnight.
The silence returns.
All three Men idly observe an old green Pontiac convertible with a frayed top and paint peeling, come into the Lot and park two spaces away facing them.
We saw this car last watching Atwood from outside the Murder House.
The headlights go off.
The Driver's door opens.
The Woman who was with Meeks in the Van steps out and hurries toward the Drug Store.
She of course means nothing to Mr. Brooks but in the brief seconds the domelight is on, he catches sight of the Man in the passenger seat.
A memory tickles his brain.
He turns to Marshall.
MR. BROOKS Where do we know that guy from?
MARSHALL You really should pay more attention to what you read, Earl.
MR. BROOKS That's what I have you for, Marshall.
MARSHALL His picture was on the front page of the paper a couple days ago because he escaped from jail.
MARSHALL He's the killer they call the Hangman.
BROOKS Ahh...
MARSHALL Remember that cop you like, Atwood, who's chasing us, she's the one who put him away.
MARSHALL I think his name is Thorton Meeks.
Mr. Brooks cocks his head at the vague outline of Meeks.
MR. BROOKS Well, well, well...
MR. BROOKS What would life be without surprises?
Mr. Smith who, remember, cannot hear or see Marshall, straightens up.
MR. SMITH There he is!
The Man they are waiting for is coming down the steps of the store.
On the way to his Pickup he takes off a Manager's smock.
MR. SMITH You know what's weird?
MR. SMITH I'll bet he has all these plans of what he's going to do tonight and tomorrow and he doesn't know he will already be dead and won't be able to do any of them.
Mr. Brooks nods absently.
The Drug Store Manager arrives at his truck.
MR. BROOKS I don't think I want to kill this guy.
MR. SMITH What?!
MR. SMITH But you promised we would!
Marshall smiles.
MARSHALL Oh, I love what you're thinking.
MR. BROOKS You have no idea what I'm thinking.
MARSHALL Oh yes I do, and it's wonderfully twisted.
MR. BROOKS I know I said we would, but I don't think it would be that much fun.
Mr. Brooks starts the car and puts it in reverse.
MR. SMITH So just like that, you're saying 'no', it's not going to happen.
MR. BROOKS Yes.
MR. SMITH I see.
Mr. Brooks casts his eyes on the license plate of the car Meeks is in.
MARSHALL You get the number?
MR. BROOKS I got it.
Mr. Brooks' Toyota leaves.
Mr. Smith sits stiffly.
His expression hasn't changed.
MARSHALL Mr. Smith wants you to notice he's pouting.
MR. BROOKS Yeah, I know.
The Toyota is part of the light traffic.
The Toyota comes into view around a corner and stops next to the sidewalk.
BROOKS I know you're upset, Mr. Smith, and I'm sorry.
MR. SMITH Yeah, I am upset.
MR. BROOKS Maybe I was a little abrupt back there, but let me explain.
MR. BROOKS Finding someone you think would be fun to kill is a bit like falling in love.
MR. BROOKS You meet a lot of candidates, and you like some of them and they're nice, but they're not right; and then that special one shows up and your heart beats faster and you know that's the one.
MR. BROOKS The man in the pickup did not make my heart beat faster.
MR. SMITH Okay, he did not make your heart beat faster.
MR. SMITH If not him, who?
MR. BROOKS I don't know, I think I have someone in mind.
MR. SMITH Do you need me to do any work on it?
MR. BROOKS No, let's see how it plays out.
MR. SMITH You see?
MR. SMITH That's my problem.
MR. SMITH That makes me feel like I'm being jerked around, Mr. Brooks.
MR. SMITH I thought it was happening last night, then it was happening tonight.
MR. SMITH And now it's "Let's see how it plays out".
MR. SMITH (CONT'D) I feel like you're planning to back out on our deal and I don't like that feeling at all.
MR. BROOKS I promise you, it will happen.
MR. SMITH When?
MR. SMITH That's what I want to know, Mr. Brooks.
MR. SMITH When?
MR. BROOKS Tomorrow night, same time.
MR. BROOKS When you come out of your building, turn right, go to the first street you can go west on, I'll pick you up on that street.
MR. SMITH Okay.
He gets out and with the door still open, turns back.
MR. SMITH I want to do this.
MR. SMITH But if it drags on too long, I could change my mind.
MR. BROOKS Don't you think I want to do this, Mr. Smith?
MR. SMITH Maybe you don't anymore.
He shuts the door.
Marshall and Mr. Brooks watch him walk away.
MARSHALL Even if that guy was charming and funny I still wouldn't like him.
The Toyota U-turns, makes the corner and is lost from sight.
The garage door opens and Mr. Brooks swings the Toyota inside.
Mr. Brooks steps out of the Toyota onto a sheet of plastic.
Two strides away is an industrial vacuum cleaner.
Mr. Brooks vacuums the passenger seat and dash and floor and everything around it.
Mr. Brooks removes his shoes and leaves them on the plastic, then slips his feet into paper slippers.
With handiwipes he wipes down the outside of the passenger door, in fact anything on that side Mr. Smith could have touched.
He opens the door and wipes down the seat and the dash and the console.
Back on the plastic, Mr. Brooks undresses.
On top of his clothes he drops the used handiwipes, the slippers and the vacuum bag.
The corners of the plastic sheet are folded up, twisted together and Zip-tied to create a nice neat package which Mr.
Brooks picks up and takes into the Ceramics Studio.
Mr. Brooks rinses off the lather under the spray.
The glow from 3000 degrees Fahrenheit is coming through the window of the kiln.
The Driver's license, complete with picture, of the Woman who was with Meeks in the Drug Store parking lot, is up on the computer screen.
Mr. Brooks, now back in his regular clothes, brings the cursor down to the address.
He scores this and drags it into Yahoo Maps 'driving directions'.
A route is generated.
Mr. Brooks brings the cursor up to 'Print' and clicks.
CLOSE on his Printer.
The map is fed out and settles into the tray.
An unmarked Police car stops on the gravel of the Turn- Around.
Two Plainclothes DETECTIVES get out and walk to the front door.
The taller One rings the bell and they wait and then the door is opened by Mr. Brooks.
In a flash he takes in the car and the way the Men are dressed and although his face doesn't betray it, he knows what they are.
MR. BROOKS Hi, what can I do for you?
The shorter One holds up a badge.
DETECTIVE 1 I'm Detective Smolny with the Chicago Police and this is Detective Carfagno, from Palo Alto, California...
CARFAGNO (DETECTIVE 2) We'd like to speak to Jane Brooks, if that's possible.
MR. BROOKS Jane is my daughter, what's this about?
CARFAGNO There was a murder at Stanford not long before she left.
CARFAGNO She may be able to help us.
MR. BROOKS Is she a suspect?
CARFAGNO Not at this time.
CARFAGNO We simply would like to ask her some questions.
SMOLNY (DETECTIVE 1) Is your daughter here?
MR. BROOKS Yes...
MR. BROOKS she is.
CARFAGNO The questions won't take long.
MR. BROOKS I'm sure you would have no objection if she had an attorney present.
SMOLNY That's fine.
SMOLNY Here's my card.
SMOLNY We can schedule a time for later today or tomorrow for her to come in to see us.
Mr. Brooks looks at the card.
MR. BROOKS If you gentlemen can wait, I will call my lawyer right now and see what we can work out.
SMOLNY Oh, that's even better.
MR. BROOKS Would you like some coffee?
SMOLNY Thank you.
Marshall is walking alongside a very disturbed Mr. Brooks.
MARSHALL We both knew she was hiding something bigger, I certainly didn't think it was this big.
MR. BROOKS She's not a suspect, Marshall.
MR. BROOKS She may not have anything to do with it at all.
Mr. Brooks opens a door.
The room that is revealed is a very well equipped home GYM.
In sweats and wearing a Walkman, Emma is working out on an Elliptical machine.
Mr. Brooks motions to her that he wants to talk.
Emma takes off the headphones and pauses the machine.
MR. BROOKS Did Jane ever tell you that there was a murder at her school?
EMMA No.
MR. BROOKS Nothing?
MR. BROOKS Not that a friend died or someone she knew died?
MR. BROOKS Or someone in her dorm died?
EMMA No.
MR. BROOKS There are two Detectives downstairs, one is from Palo Alto, they want to ask her some questions about a murder that occurred shortly before she came home.
EMMA Oh, my Gosh!
EMMA I'm sure if she was close to someone who was murdered, she would have said something.
MR. BROOKS I called Roger, he suggested a criminal attorney, they'll be here within the hour.
EMMA I'll get dressed.
There are now three cars plus the unmarked Police car in the Turn-Around.
Everyone is in the LIVING ROOM.
Jane is on a couch flanked by her Mother and a LAWYER.
Standing behind them is a heavyset LAWYER and a YOUNG LAWYER.
We've never seen any of these Men before.
Facing this Group from the opposite couch are the two Detectives.
There are two tape recorders on the coffee table.
Mr. Brooks is in a chair off to one side watching everything.
For him the conversation is merely a burble of voices.
He studies his daughter while she answers a question.
She is unaware of his scrutiny.
And finally all he can see are her lips moving.
Even the burble has faded to silence.
The unmarked Police car with the two Detectives pulls away.
We move in on the front door.
It opens.
The Lawyers spill out.
Mr. Brooks shakes hands with the lawyer who was sitting on the couch next to Jane.
MR. BROOKS Mr. Clifford, it was a pleasure.
MR. BROOKS Thank you for coming on such short notice.
HEAVYSET LAWYER There won't be any more dropping by like they did today, they'll call us first.
MR. BROOKS Thanks again, Roger.
MR. BROOKS It was a good idea to hear what they wanted to know sooner rather than later.
MR. CLIFFORD We'll talk.
MR. BROOKS Yup.
He waves and re-enters the house.
Mr. Brooks shuts the door and turning, finds himself face to face with Emma and Jane.
The Women are both worried.
He and his Daughter look at each other.
For a brief instant each one tries to find what they hope to find in the other.
Mr. Brooks smiles and folds the Girl into his arms.
MR. BROOKS You did good, Kid.
MR. BROOKS Your answers were clear, concise and honest.
MR. BROOKS And when they tried to trip you up, it didn't work.
JANE I hope so.
JANE I'm not feeling so well.
EMMA Should you lie down?
JANE I think I'd better.
Mr. Brooks kisses his daughter on the top of the head.
MR. BROOKS Try and get some sleep.
Jane bends her steps toward the stairs.
MR. BROOKS I think Roger has a handle on this.
MR. BROOKS He and Mr. Clifford will take care of it.
Emma takes her Husband's hand and after squeezing it follows her Daughter.
On the stairs Jane stops and looks back.
JANE I'm sorry I didn't tell you about it, Daddy.
JANE It was horrible but I really didn't know the guy that well.
JANE It happened at about the same time I found out I was pregnant, and it just went out of my mind.
MR. BROOKS I understand.
Jane resumes her journey up the stairs.
CLOSE on a water glass being filled from a tap.
BROOKS (V.O.) God grant me the Serenity to accept the things I cannot change, Courage to change the things I can, and Wisdom to know the difference...
With a shaky hand, Mr. Brooks raises the glass to his lips.
MR. BROOKS God help me.
MR. BROOKS What do I do?
Sitting on the island behind him Marshall waits for Mr.
Brooks to gulp the glass dry.
MARSHALL She did it, didn't she?
MR. BROOKS Yeah.
MR. BROOKS It'll take the Cops a week to ten days to put their case together and then they'll come back and arrest her.
MARSHALL What are you going to do?
Mr. Brooks puts his hands over his eyes and sobs, then wiping away the tears:
MR. BROOKS I've been afraid of this since the day she was born.
MR. BROOKS She has what I have.
MARSHALL Yes, she does.
MARSHALL But you've always been smart about it.
MARSHALL She was stupid.
MARSHALL She did it because she got off on it, she did it for fun.
MARSHALL Why didn't she think it through?
MARSHALL A hatchet!
MARSHALL And she left it there!!
MR. BROOKS They were pretty graphic, weren't they?
MARSHALL That was to shock her into making a mistake.
MR. BROOKS What does she think I think?
MR. BROOKS Doesn't she remember what she told me?
MR. BROOKS That the BMW was being driven across country by a friend and now right in front of me, she tells the Cops it was stolen.
MARSHALL You've always cleaned up after her, whatever she did, all her life.
MR. BROOKS If the BMW has anything incriminating in it, I hope it was stolen or she dropped it at the bottom of a very deep lake.
MARSHALL Do you think she knows what kind of trouble she's in?
MR. BROOKS I think she thought she had gotten away with it until the Cops showed up.
MR. BROOKS I should have listened to her, it was there.
MR. BROOKS She was telling me.
MR. BROOKS 'I didn't quit school because I was pregnant'.
MR. BROOKS I should have dug deeper.
MARSHALL And where would you be but at the exact same place you are now.
MARSHALL It is not your fault, Earl.
MARSHALL Part of your problem with her is that you always think it is.
MR. BROOKS She has what I have, Marshall.
MR. BROOKS So on a very basic level, it is my fault.
MARSHALL What are you going to do?
MR. BROOKS Maybe the best thing for her would be to let her go to jail.
MARSHALL And what about her child?
BROOKS Emma and I would raise it.
MARSHALL You might be right, Earl, you might be.
MARSHALL Because you know if she's not stopped, she's going to do it again.
MARSHALL And if she wants to take over the box business, the next victim could be you.
MR. BROOKS I don't think she'd go that far.
A slide of what looks like enlarged grains of sand among giant carpet fibers is projected onto a screen.
The Lead Crime Lab Technician:
SIGY We found traces of this in two places.
The slide changes to an overhead schematic showing the interior of the house where the dance Couple was murdered.
Detective Atwood and Detective Snyder are standing with Sigy watching the presentation.
Atwood has a bandage covering the stitches over her eye.
SIGY Here and here.
The red dot indicates an area just outside the Kitchen and just outside the Bedroom.
SIGY We did an analysis and it's made up of feldspar, alumina and kaolin.
DETECTIVE ATWOOD What's that?
SIGY A high fire stoneware clay.
SNYDER Like you make ashtrays and vases from?
SIGY This is more plates and teacups.
SIGY It was slightly wet when whoever it was tracked it into the house and it stuck to the carpet fibers.
SIGY We're thinking it was the killer.
DETECTIVE ATWOOD It could have been tracked in by a friend.
SIGY That's the thing, you see, the friend would have had to have been there almost at the same time the killer was.
SIGY Otherwise the samples would have been dry and the killer would have vacuumed them up.
DETECTIVE ATWOOD Is the clay rare, is it difficult to get?
SIGY You can buy it almost anywhere.
SNYDER That's not much help, Sigy.
DETECTIVE ATWOOD And this is the only incongruity you were able to find in the whole house.
SIGY We've done everything we know how to do.
SIGY It sure doesn't break the case wide open, does it?.
DETECTIVE ATWOOD No, Sigy, it doesn't.
DETECTIVE ATWOOD It does give me an excuse to ask someone some new questions.
Mr. Brooks is standing behind his desk staring blankly at the contents of his briefcase when Sunday, his Secretary, comes in.
SUNDAY Yes, Mr. Brooks?
Mr. Brooks doesn't immediately answer her, he's lost in thought.
MARSHALL Before you open your mouth, be very sure this is the right thing to do.
MR. BROOKS I will never be sure.
Remember; Sunday can neither see nor hear Marshall.
MARSHALL You get pissed at me because I'm always the one arguing to go ahead and do murder.
MARSHALL Not this time, Earl.
MARSHALL This is your decision.
MR. BROOKS I know it's wrong.
MR. BROOKS In my heart I know it's wrong.
MARSHALL Then don't do it.
MARSHALL Go with Mr. Smith tonight and end that, then let the Police put Jane in jail.
MARSHALL Hopefully that will save her and we can happily go on with our tortured lives.
MR. BROOKS That's exactly what I want to do.
MR. BROOKS That's exactly what I should do.
MR. BROOKS The thing is, she's my daughter and I love her.
Mr. Brooks raises his head and looks at Sunday.
MR. BROOKS I'm going home.
MR. BROOKS Cancel everything for the rest of the day.
MR. BROOKS I might be in tomorrow afternoon.
MR. BROOKS I'll let you know about that.
SUNDAY I'll take care of it.
MR. BROOKS If you need me, need me, call my studio, that's where I'll be.
BROOKS (CONT'D) I probably won't pick up, just leave a message.
SUNDAY I'll try not to bother you.
The door closes behind her.
With a hidden lever, Mr. Brooks lowers casters under the kiln and rolls it aside to reveal a Combination Safe imbedded in the concrete floor.
He spins the dial, opens the Safe and extracts four quadruple- pocketed plastic sleeves which he lines up in front of himself.
Each sleeve contains a Driver's License, two Credit cards and cash.
The pictures on the Driver's Licenses are of Mr. Brooks, but you wouldn't immediately recognize him because of the disguises.
As he's trying to decide which of the four Identities would be best for what he has in mind, Marshall comes forward to look over his shoulder.
MARSHALL The thing that bothers me about this, besides the fact we're not prepared, and a multitude of other things, is what does Mr. Smith do when he's walking west tonight and you don't show up.
MARSHALL That little freak could flip out.
Mr. Brooks chooses the first sleeve and the third sleeve.
The other two go back into the Safe.
MR. BROOKS I'll take care of it on the way to the airport.
It's in an Industrial Park.
Mr. Smith exits one of the doors and continues on into the Parking Lot to a moderately expensive foreign car sitting in a space identified by a sign which reads:
Mr. Baffert.
He squeezes the 'disarm' button on his key chain.
The car chirps twice and he opens the door.
Bending his knees to get in, he stops.
There is a section of Newspaper wedged in the steering wheel.
When his brain unlocks he straightens up and moving only the top of his body, makes a quick recon of the surrounding area and his back seat.
Nothing threatening seen, he eases into the seat.
Slam!
The door is closed and locked.
Gingerly, Mr. Smith removes the Newspaper.
It folds open.
On the first page there are words circled in red.
As his eyes dart from one to the other we go in close on the words and hear Mr. Brooks say them as Mr. Smith finds them.
MR. BROOKS (V.O.) Not - able - to - meet -
Mr. Smith turns the page.
MR. BROOKS (V.O.) - tonight - Do - it - same -
Turns the page.
MR. BROOKS (V.O.) - time - tomorrow -
Turns the page.
MR. BROOKS - night - Don't - be - stupid -.
Mr. Smith refolds the Newspaper and throws it at the passenger seat.
MR. SMITH Fuck you!
He inserts the key into the ignition.
RAP-RAP!!
There's a sudden sharp KNOCK!!, on the Driver's window.
Mr. Smith levitates off the seat!!
Unable to breathe, he turns.
Detective Atwood's face lowers into view.
DETECTIVE ATWOOD You remember me?
All Mr. Smith can do is nod.
DETECTIVE ATWOOD Would you step out of the car, please, I want to talk to you.
Atwood steps back as Mr. Smith gets out.
Behind her, Detective Snyder is standing next to the Driver's door of an un-marked Police car which has blocked Mr. Smith in.
DETECTIVE ATWOOD So Mr. Baffert, what is that you have to tell me?
MR. SMITH What do you mean?
MR. SMITH I don't have anything to tell you.
DETECTIVE ATWOOD Really?
DETECTIVE ATWOOD Because I was driving around and I got this sudden feeling that you had something to tell me about the murders.
MR. SMITH No.
MR. SMITH Nothing.
DETECTIVE ATWOOD That's disappointing.
DETECTIVE ATWOOD Because when I left you the last time we talked, I felt I had missed a clue that was right in front of me that would solve this whole case.
MR. SMITH I don't know why you would feel that.
DETECTIVE ATWOOD Didn't you tell me you were an amateur potter, that you made bowls and vases?
MR. SMITH No, I said I was an amateur photographer.
DETECTIVE ATWOOD Are you positive?
DETECTIVE ATWOOD Because we found potter's clay on the carpet of the murder house and I was sure you said to me that you worked with clay, that you made pots.
MR. SMITH No.
MR. SMITH I said my hobby was photography, not pottery.
DETECTIVE ATWOOD Maybe that was it.
DETECTIVE ATWOOD The Stewardess upstairs said the victims kept their curtains open when they made love.
DETECTIVE ATWOOD Could I see some of the pictures you took of that Couple?
Mr. Smith can only stare at Detective Atwood.
His Adam's apple moves up and down though he makes no sound.
Should he or shouldn't he?
Finally he throws his arms up in a shrug but in his half-turn of indecision he happens to spy the Newspaper he tossed at the passenger seat of his car.
Part of it is draped over the console.
The red circles around the words on that page jump out at him.
MR. BROOKS (V.O.) Don't - be - stupid -.
Mr. Smith returns his attention to Detective Atwood.
MR. SMITH You are harassing me, Detective Atwood.
MR. SMITH You know very well I'm not a potter and I don't have any pictures!
MR. SMITH So my feeling is that your feeling is wrong and that you should move your car and let me go home.
DETECTIVE ATWOOD What is your job here?
DETECTIVE ATWOOD What do you do?
SMITH I'm a mechanical engineer.
DETECTIVE ATWOOD You have to be pretty smart for that, don't you?
MR. SMITH I guess.
DETECTIVE ATWOOD Then be smart, Mr. Baffert.
DETECTIVE ATWOOD You lied to me right there at the end.
DETECTIVE ATWOOD I'll be watching you.
DETECTIVE ATWOOD And when you want to tell me the truth, you know how to get in touch with me.
She gives him a dazzling smile.
DETECTIVE ATWOOD See you later, alligator.
Atwood walks back to her car and gets in.
DETECTIVE ATWOOD Goddamit...
As Snyder accelerates away he points to the car's computer screen.
SNYDER Captain Lister got us the search warrant for Meeks' Chiropractor.
DETECTIVE ATWOOD Good.
DETECTIVE ATWOOD Goddamit!, that guy knows something...
DETECTIVE ATWOOD He almost told me and then something happened.
SNYDER You think he did it?
DETECTIVE ATWOOD I don't think it's that simple.
Mr. Smith watches the unmarked police car going away and wipes the sweat out of his hairline.
We're following a STEWARDESS down the aisle.
She stops at a row and leans over to hand a glass of tomato juice to the Person in the Window Seat.
STEWARDESS Here you are, Sir.
Mr. Brooks who now looks like the Man in the picture on the third Driver's license, accepts the drink.
MR. BROOKS Thank you.
He takes a sip and resumes his gaze out the window.
MR. BROOKS God grant me the Serenity to accept the things I cannot change, Courage to change the things I can, and Wisdom to know the difference...
The earth that he is looking at below is a long way away.
Come off a sign which reads: STANFORD UNIVERSITY - 2 1/2 miles to an Alamo rental car traveling south on the El Camino Real.
In his Pottery-Throwing clothes, Mr. Brooks is behind the wheel.
There's an Ace Hardware Store bag sitting upright and open on the passenger seat.
We peek over the edge of the bag.
A brand new hatchet with a gleaming blade sits at the bottom.
Mr. Brooks adjusts the rearview mirror.
Marshall is on the passenger side of the back seat.
MR. BROOKS You're awfully quiet back there.
Without any indication he's been addressed, Marshall continues to stare stoically ahead.
The Alamo Rental car carrying Mr. Brooks continues on.
It's dark.
There's barely enough ambient light to see that we are close on the knob of the Front Door.
From outside we hear the muffled sound of a Black & Decker cordless drill and the knob begins to vibrate.
Someone is drilling the lock.
The sound stops.
The knob turns.
The door opens.
A flashlight is shone into our face.
UNIFORMED POLICEMAN Mr. Alvin Griffin, this is the Chicago Police.
From the protection of the doorjamb, a very young UNIFORMED POLICEMAN is the person shining the flashlight into the house.
He's flanked on either side of the door by Detective Atwood and Detective Snyder.
The Officer's flashlight illuminates a short ENTRYWAY with a HALL immediately off to the left and the LIVING ROOM fading into darkness, straight ahead.
UNIFORMED POLICEMAN We have a warrant to search your home and premises.
UNIFORMED POLICEMAN We're coming in.
Flashlight in her left hand and the Glock in her right, Detective Atwood is the first one across the threshold.
She directs the beam at the wall next to the door; finds the light switch.
Click!
Click!
Click.
DETECTIVE ATWOOD Lights don't work.
She continues to the Hall.
The darkness is so oppressive there, it seems that her stream of light must struggle to pierce it.
The Room at the end is the KITCHEN.
With Snyder hanging in the Entryway to protect her back, Atwood eases the hand with the flashlight around the corner.
The dishwasher, the sink, the cabinets gleam dully back at her.
She steps inside.
A debris field of empty pharmaceutical boxes and vials trails away from the Refrigerator.
Her flashlight sweeps the rest of the Room.
Beyond an open countertop in the DINING AREA, the light blurs past an oval of white, and then comes back.
It's the face of a WOMAN!!
Careful of the litter, Atwood moves forward until she can see that the Woman is sitting in a chair at the far end of the dining table.
Her throat has been cut.
Her head is being held upright by her hair which is taped to the back of the chair.
She has a pen taped between her fingers, but the Appointment Book in front of her is drenched in blood.
DETECTIVE ATWOOD We have a dead woman in here.
A light and footsteps hurry toward her from the LIVING ROOM.
Atwood swings her light at them.
SNYDER Hey!
He squints and turns away.
DETECTIVE ATWOOD I thought you were behind me.
SNYDER The living room is clean.
Atwood swings her light back onto the dead Woman.
The combined illumination of the flashlights cause the support joists twelve feet up to throw eerie shadows onto the open ceiling.
DETECTIVE ATWOOD Snyder, meet Mona.
The Uniformed Policeman comes up beside Atwood.
UNIFORMED POLICEMAN I called it in.
The smell of blood and the sight of the carnage is too much for him.
His gorge rises and he gags.
DETECTIVE ATWOOD Do that outside.
The Officer doesn't have to be told twice.
DETECTIVE ATWOOD Meeks did this.
SNYDER I thought Meeks hung people.
Atwood retraces her steps in the Kitchen.
DETECTIVE ATWOOD Meeks is a steroid freak.
DETECTIVE ATWOOD This Refrigerator was always full of steroids.
DETECTIVE ATWOOD Mona was Alvin Griffin's niece, receptionist, lover and keeper of the keys.
She focuses her flashlight on an open padlock dangling from a steel band that runs around the Refrigerator.
With the barrel of the Glock she opens the door.
The only edibles inside are a tomato, half a loaf of bread, a package of hotdogs and some part of a chicken in a KFC box.
The rest of the space is vacant.
DETECTIVE ATWOOD Well, the steroids are certainly gone.
SNYDER You think Meeks has Alvin with him?
DETECTIVE ATWOOD Meeks thinks Alvin turned him in.
She shuts the Refrigerator.
DETECTIVE ATWOOD Let's go see what's in the rest of the house.
Atwood and her flashlight pass us.
Three feet to her right and slightly behind is Snyder and his flashlight.
The two Detectives are leaving the Living Room and entering the HALL toward the bedrooms.
The ceiling is low here and it feels very claustrophobic.
Ahead is a Door painted red.
But before they get to it, there's a Room on the right.
Snyder shines his light in.
It's a BATHROOM.
The shower curtain is open.
Nobody in the tub.
The Door ahead is waiting, but there's another Door on the right.
Snyder shines his light in.
This one is a Treatment Room with a Therapy table and shelves of oils and unguents.
They've come to the red Door.
Atwood will open this one.
She turns the knob and pushes.
The Door is stuck.
She and Snyder exchange a look.
Snyder shuffles back half a step and flattens himself against the wall.
He shuts off his flashlight.
Atwood takes a deep breath, levers her weight against the door and pushes.
There's a sudden Snap!
Then the door swings freely open.
The beam of Atwood's flashlight reveals a large room containing a bed, a dresser, a...
CREEEKKK!!!
The sound is coming from up in the rafters.
Atwood whips her flashlight in that direction.
For an instant the beam catches a piece of a large shape falling fast right at her.
Then it's lost in the darkness and then picked up again in the reflected light in the Hall.
The shape is a naked Man.
WHACK!!
The Man nails Atwood in the shoulder.
BANG!
Her gun goes off.
She bounces into the wall and onto her ass.
Barely slowed the Man continues in an upward arc.
His feet and knees slam into the ceiling.
Plaster dust rains.
The Man swings back, past Snyder.
He's lost in the darkness again.
Then he swings back into the light and comes to a stop just inside the bedroom Door.
The Man is hanging from a rope around his neck.
He's dead.
His Body is festooned with syringes stuck into his bare flesh.
In fact two of the needles hold a sheet of paper to the Man's chest.
Printed on the paper in big black letters are the words:
DETECTIVE ATWOOD Snyder, this is Alvin Griffin.
The gray of dawn is in the sky.
Mr. Brooks, wearing a disguise that makes him look like the picture on the Driver's license in the first plastic sleeve, gets into a Taxi.
The Cab drops Mr. Brooks off in front of a house.
Mr. Brooks watches the Cab drive away and then with his Carry-On bag starts walking in the opposite direction.
He turns a corner.
Still on foot, Mr. Brooks arrives at his non-descript Toyota.
There are also neighborhood cars parked along the street.
Mr.
Brooks unlocks his car and throws his Carry-On onto the passenger seat.
Mr. Brooks' Toyota speeds up an on-ramp and joins the light traffic.
From the back seat Marshall watches Mr. Brooks remove the pieces of his disguise - a wig, a mustache, glasses, and drop them in the Carry-On.
MARSHALL How do you feel?
MR. BROOKS Dirty.
MARSHALL That's understandable.
MARSHALL You've never killed for this reason before.
MARSHALL The feeling will go away.
MR. BROOKS I don't think so.
MR. BROOKS It's the whole thing, Marshall.
MR. BROOKS If I could find a way to just disappear, where there was absolutely no trace of me; because eventually I will get caught doing this.
MR. BROOKS And it'll be very embarrassing for me and Emma and Jane.
MR. BROOKS So I've been thinking...
MR. BROOKS is there a way that Mr. Smith could kill me and make me disappear.
MARSHALL Number one, Mr. Smith is not smart enough to do that.
MARSHALL Number two, there is no reason, if you're careful, to believe you will ever get caught.
MR. BROOKS I know I will have to plan it for Mr. Smith, but I think that's what I want to do.
MARSHALL I'm not particularly fond of that plan, Earl.
MARSHALL Remember if you die, I go with you and I like being alive.
MARSHALL I like eating, I like fucking, I like killing.
MR. BROOKS I have to end it, Marshall.
MR. BROOKS One way or the other.
MR. BROOKS And I think this is the best way.
MARSHALL Well fuck you then.
Long ago this was a nice area.
A banner hangs from an old Deco building - ROOMS FOR RENT.
Mr. Brooks is walking through the Parking Lot beside the Building.
There, as a first car in a double space is the old green Pontiac convertible.
It's blocked in by another car.
Mr. Brooks sidles between the cars to check the license plate against the one in his memory.
It's the car Thorton Meeks was in, outside the Drug Store.
Mr. Brooks walks away.
Mr. Brooks opens the kiln door and removes three pieces embellished with a beautiful yellow glaze.
He sets them on a table then takes his Carry-On bag and places it in a ceramic trough which he puts into the kiln.
The door is shut.
Flame erupts from the gas jets.
The Bathroom door opens.
Mr. Brooks, in his pajamas, turns out the light and crosses to the bed.
Emma looks up as he pulls back the covers and gets in.
EMMA You worked all night.
MR. BROOKS I had ideas for pots that took too long and the clay kept winning...
MR. BROOKS I'll be fine.
MR. BROOKS (CONT'D) And there's a yellow Chinese glaze I'm trying to get right...
He lays his head on the pillow and is almost instantly asleep.
Reflected in the glass of an open mirrored closet door is a tastefully furnished DEN with floor-to-ceiling windows that look out at LAKE MICHIGAN from the 20th floor.
An empty suitcase falls into this picture and bounces on the carpet.
Behind the mirrored door, Detective Atwood is atop a stepstool rummaging through the suitcases on the highest shelf.
Throughout the Condo there is an incessant ringing of the phones.
Another suitcase goes down and Atwood finds what she's looking for - a framed color 8 x 10 photo of her husband, Jesse.
He's in a business suit and holding some kind of trophy.
The phones stop ringing.
Atwood comes down the stepstool, folds it and is carrying it back to where it lives when the phones start ringing again.
She picks up a cordless in the Den.
DETECTIVE ATWOOD Yes?
The Asian Attorney interrupts her sip of coffee.
ASIAN ATTORNEY Hi Tracy, this is Nancy Tang.
ASIAN ATTORNEY We received a counter offer.
ASIAN ATTORNEY Are you sitting down?
DETECTIVE ATWOOD Yeah, go ahead...
DETECTIVE ATWOOD He can't get that, can he?!
INTERCUT with Nancy.
NANCY (ASIAN ATTORNEY) No, my sense of it is by asking for five, they're hoping you'll settle anywhere between two five and three.
DETECTIVE ATWOOD Never.
DETECTIVE ATWOOD How long can you stall them?
NANCY They know you want this done quickly, so they're going to expect a quick counter offer.
DETECTIVE ATWOOD I need two days.
DETECTIVE ATWOOD Wait two days before getting back to them.
DETECTIVE ATWOOD If they call, tell them it's a big number, I'm thinking about it.
NANCY Okay.
DETECTIVE ATWOOD And the picture he wanted...
She slams the frame of Jesse's photo against the inside of a metal trash can.
Nancy winces and then smiles at the sound of shattering glass.
Atwood plucks the photo out of the frame and tears it so that the rip can be heard over the phone.
DETECTIVE ATWOOD ...
DETECTIVE ATWOOD tell him I couldn't find it.
Mr. Brooks is still asleep.
Emma, dressed for the day, arrives at his side of the bed.
She rubs the back of Mr.
Brooks' hand.
EMMA Earl...
EMMA Earl...
Mr. Brooks opens his eyes.
MR. BROOKS Huh?...
EMMA Roger is on the phone.
In his slippers and robe, Mr. Brooks is standing in the Doorway watching Jane who is leaning over the Counter with an open Newspaper next to a bowl of cereal.
He has a chance to take a good long look before she feels his presence and raises her head.
JANE Oh, Hi, Daddy, I thought you'd already be gone.
MR. BROOKS Roger called.
MR. BROOKS There was another murder last night near Stanford.
JANE Oh...
MR. BROOKS Done the same way as the one they talked to you about.
MR. BROOKS Right down to the hatchet being left at the scene.
Jane can't quite conceal the tremor of surprise that ripples through her and Mr. Brooks sees it.
MR. BROOKS They think they have a serial killer.
MR. BROOKS Obviously you were here last night, so you're in the clear.
JANE That's good news, isn't it?
JANE I mean even if you're innocent it's good news to know you're not a suspect.
MR. BROOKS Oh, yeah.
MR. BROOKS How's the morning sickness?
MR. BROOKS Do you want to ride in with me today?
JANE I feel fine, but I don't know how long that will last.
Mr. Brooks nods, turns to leave, then turns back.
MR. BROOKS Do you love me, Jane?
JANE Of course I love you, daddy, you're my father.
MR. BROOKS Have you decided whether or not to keep the baby?
JANE Not yet.
MR. BROOKS Okay.
Looking off the grill as it overtakes another car in the Fastlane.
Eminem is on the stereo.
The car ahead moves out of the way.
Mr. Smith is rapping along to "Cleanin' Out My Closet".
He knows all the words.
With Eminem fading, we fall behind Mr. Smith.
One car, two cars.
The third car is Detective Atwood's car.
Atwood is driving.
Snyder is in the passenger seat.
SNYDER What are we doing?
DETECTIVE ATWOOD 'Are we there yet?' , are we there yet?' , you sound like a child.
DETECTIVE ATWOOD We're playing a hunch.
SNYDER We've been following this guy all day, he's boring, and everything we run on him comes up clean.
DETECTIVE ATWOOD If it didn't, it wouldn't be called a hunch.
SNYDER Meeks' finger-prints were all over the chiropractor, the note, refrigerator, he's the guy we should be looking for.
DETECTIVE ATWOOD Look where?
DETECTIVE ATWOOD Please tell me.
DETECTIVE ATWOOD Everyone knows who Meeks is and is looking for him.
DETECTIVE ATWOOD The chiropractor was the last link to his old life that I know of.
DETECTIVE ATWOOD The only way we'll find him, now, is if someone turns him in or we trip over him at a bus stop.
DETECTIVE ATWOOD On the other hand, Detective Snyder, no one knows who the Thumbprint Killer is or where he is.
DETECTIVE ATWOOD However, I have a fucking hunch this guy Baffert does.
DETECTIVE ATWOOD I have two days to play that hunch.
DETECTIVE ATWOOD If you feel like you're wasting your time with me, I'd be happy to do it alone.
He looks at her and shakes his head.
SNYDER I had a fight with my wife this morning; what's your problem?
DETECTIVE ATWOOD My husband wants five million dollars.
Mr. Smith's car enters the Parking Lot of a Rib Joint.
Atwood's car stops across the street.
Atwood and Snyder watch Mr. Smith enter the Restaurant.
They wait in silence.
A muted 'tone' announces the arrival of an Email on their computer.
Snyder reads and frowns.
DETECTIVE ATWOOD Bad news?
SNYDER Lister is pulling you off this case.
DETECTIVE ATWOOD Why?!
SNYDER Maybe they caught him.
She twists the screen around so she can read the message.
DETECTIVE ATWOOD No.
DETECTIVE ATWOOD She would have said that.
Snyder points across the street at Mr. Smith coming out of the Restaurant carrying a Take-Out bag.
SNYDER You want to keep following him?
Atwood hesitates.
SNYDER Lister only said you were off the case, not me.
DETECTIVE ATWOOD Good thinking, Tonto.
She starts the car.
There's the muted 'tone' again.
Atwood looks at the computer screen.
DETECTIVE ATWOOD Shit!
DETECTIVE ATWOOD She just 86'ed you too.
Trailed by Snyder, Detective Atwood arrives at Captain Lister's SECRETARY.
DETECTIVE ATWOOD Is she in?
SECRETARY She's with someone.
DETECTIVE ATWOOD Good.
Atwood blows past the Secretary and opens the door to Lister's office.
There are two MEN in suits on the other side of the desk from the Captain.
Atwood ignores them and focuses on Lister.
DETECTIVE ATWOOD You promised if I settled my divorce I had three days on the Thumbprint Killer.
DETECTIVE ATWOOD I have the rest of today and tomorrow left.
CAPTAIN LISTER Detective Atwood, meet FBI Agents Longnecker and Campbell, they're taking over your investigation.
DETECTIVE ATWOOD You promised you would keep them out of it for three days.
CAPTAIN LISTER They won't allow me to keep that promise.
Atwood glares at her then at the FBI Men.
DETECTIVE ATWOOD This is my case, what you're doing is fucked.
DETECTIVE ATWOOD But since I can't stop you, and she won't, here's a tip.
DETECTIVE ATWOOD James Baffert, you should stake him out, he knows something.
DETECTIVE LONGNECKER We have some other ideas we are looking into.
DETECTIVE ATWOOD Then what's the problem?
DETECTIVE ATWOOD You do that and I'll tail Baffert.
DETECTIVE LONGNECKER Thank you for all your good work, Detective.
DETECTIVE LONGNECKER This is our case now.
Atwood looks from one Man to the Other.
DETECTIVE ATWOOD Good luck.
DETECTIVE ATWOOD Later I suppose you'll fill me in on what I'm supposed to be doing around here.
DETECTIVE ATWOOD I'm confused.
She leaves.
Snyder closes the door behind her.
It's deserted with only a small spill of light coming from Mr. Brooks' Office.
Mr. Brooks is at his desk.
The lamp at his elbow throws a yellow cone across his face.
His head is in his hands, he's been crying.
Marshall steps out of the shadows behind him.
MARSHALL It's time to go.
MR. BROOKS Yeah.
He reaches into a bottom drawer and as he takes out an envelope, Marshall reads the tear-stained hand written letter resting on the blotter.
MARSHALL Dear Emma and Jane, my loves, I have a terminal illness and instead of subjecting you to my deterioration, I have decided to disappear.
MARSHALL Don't try to find me, I don't want to be found.
MARSHALL Please believe that the time I spent with you brought me the greatest joy of my life.
MARSHALL Love.
MARSHALL Dad.
Mr. Brooks picks up the letter and folds it.
MARSHALL So you're going to go through with it.
Mr. Brooks stuffs the letter in the envelope, seals it and picks up a pen.
MR. BROOKS It's all planned to work out, Marshall.
On the envelope he writes: For EMMA and JANE.
On the sidewalk Mr. Smith is walking toward the on-coming traffic.
The headlights make it difficult to tell one car from the other until they pass.
That doesn't keep him from looking for Mr. Brooks.
The houses stop and he's passing a pocket park.
In a dark space between the street lamps, a hand falls on Mr. Smith's shoulder.
He jumps and a scream squeaks out of his throat.
It's Mr. Brooks, in his Pottery-Throwing clothes.
MR. BROOKS Are you ready to rock and roll, Mr.
MR. BROOKS Smith?
Mr. Smith swallows hard and nods.
Mr. Brooks propels him into the park.
Mr. Brooks is driving.
Mr. Smith is in the passenger seat.
Both are lost in a wary silence.
Abruptly from the back seat:
MARSHALL I smell gun oil, a gun oil that's different than yours.
MR. BROOKS He brought his gun.
MR. BROOKS After he gets what he wants he plans to kill me.
MARSHALL Ah...
MARSHALL now I get it.
MARSHALL You were counting on that, weren't you?
MR. BROOKS It has a certain logic.
MARSHALL But if your plan is to have him kill you, why do you have to kill someone else first?
MR. BROOKS He'll need to see that to get up the courage to kill me.
Marshall roars with laughter.
MARSHALL Not even you believe that, Earl.
MARSHALL It makes it more exciting, doesn't it, to think he's going to kill you after you kill someone else.
MARSHALL You're getting your rocks off big time, that's why you're doing it.
MR. BROOKS Not true...
MR. BROOKS and if it were, so what?
MR. BROOKS You're goddamn great, you know.
MR. BROOKS To have the balls to do this.
MR. SMITH I'm pretty nervous but that's normal right?
MR. BROOKS Perfectly normal.
Atwood is propped up in bed reading a Magazine.
Her hair is pulled back and her face glistens with Cold Cream.
The phone rings.
Should she answer it?
It rings again, then again.
Reluctantly she grabs the receiver.
DETECTIVE ATWOOD Hello...
DETECTIVE ATWOOD Oh, yes, yes.
DETECTIVE ATWOOD Put him through...
DETECTIVE ATWOOD Hi, this is Detective Atwood speaking, thanks for calling...Yes, your roommate said you were in Tokyo...
DETECTIVE ATWOOD Anything, if you saw anything at all it might be helpful.
A MAN in a Flight Attendant's uniform is standing at the window of the Apartment he shares with the Stewardess.
A cordless phone to his ear, he is looking down at the House where the dance Couple was murdered.
FLIGHT ATTENDANT The weird thing is that they closed their curtains, at first they were open like they always were and they were making love, which they always did, and then when I looked again the curtains were closed, and there were what looked like camera flashes coming from behind the curtains.
INTERCUT with Detective Atwood.
DETECTIVE ATWOOD Camera flashes?
FLIGHT ATTENDANT That's what it looked like.
DETECTIVE ATWOOD That's why he poses them.
FLIGHT ATTENDANT I'm sorry?
DETECTIVE ATWOOD Nothing.
FLIGHT ATTENDANT I wish I could be more helpful, I didn't see the killer or anything like that, but since it was weird I thought I should call.
DETECTIVE ATWOOD You've been very helpful.
DETECTIVE ATWOOD This answers a lot of questions for me.
DETECTIVE ATWOOD Thank you very much, Mr. Struber.
She's about to hang up when Struber speaks again.
FLIGHT ATTENDANT The guy you should talk to is the guy on the floor below us...
FLIGHT ATTENDANT (CONT'D) eh, I can't remember his name, but he told me once that he'd taken some great pictures of that Couple making love, he's the one you should speak to.
DETECTIVE ATWOOD Would that be, Mr. Baffert?
FLIGHT ATTENDANT Yeah, I think Jim or James...
DETECTIVE ATWOOD Thank you very much.
Atwood disconnects then quickly dials.
DETECTIVE ATWOOD Snyder, meet me at Baffert's apartment with a Search Warrant...
DETECTIVE ATWOOD Listen to me, this is what you tell the judge.
Coming up the back STAIRS we arrive at a LANDING and make a right.
In front of us is Mr. Smith watching Mr. Brooks pick the deadbolt in the Service door.
Mr. Brooks straightens up, twists the handle and pushes the door inward.
It's caught by a chain.
He takes the bent rubber- tipped forceps from one pocket, from another he hands Mr.
Smith a pair of latex gloves.
MR. BROOKS Put these on.
In the middle of the large darkened KITCHEN, Mr. Brooks pauses to listen to the sounds of the Apartment.
The gun with the silencer is already in his right hand.
Both are encased in a Ziplock bag.
Beside him, Mr. Smith is wide eyed with fear and anticipation.
His teeth are even chattering.
MR. BROOKS Try a couple deep breaths through your nose.
MR. SMITH I have to take a crap so bad.
MR. BROOKS This won't take long.
Mr. Brooks and Mr. Smith come out of the Kitchen.
The LIVING ROOM is quite well appointed.
There's a fire going in the Fireplace.
The sound of a T.V. is coming from a ROOM off a HALL up ahead.
That is where Mr. Brooks and Mr. Smith are headed.
They're more than half way across the LIVING ROOM when DING!
DONG!, the doorbell rings.
Mr. Smith gasps and looks beseechingly at Mr. Brooks.
Without an ounce of hurry, Mr. Brooks maneuvers him back into the shadows of the KITCHEN.
The doorbell rings again.
A wet spot appears in Mr. Smith's crotch and runs down his pant leg.
Pee drips onto the linoleum.
A Man comes out of the Hallway.
The Living Room light goes on.
The Man is Jesse, Detective Atwood's estranged husband.
He opens the Front Door.
The Woman who comes in is Sheila, his divorce lawyer.
They kiss, tongues.
His hands brush over her breasts.
He begins to unbutton her blouse.
The kiss breaks.
As he continues unbuttoning.
SHEILA I called your wife's lawyer.
SHEILA They're thinking about the five million dollars.
Jesse opens the blouse and looks at the breasts under the bra.
JESSE Realistically how much do you think we can get?
Sheila gives him a quick kiss and moves on into the LIVING ROOM where she drops her briefcase on the couch.
SHEILA If we go to court, best case, two, if she wants to settle, best case, three, but I would be happy with two seven.
Backlit by the Fireplace, Jesse kisses her again.
From the KITCHEN, Mr. Brooks and Mr. Smith watch Jesse unzip Sheila's slacks and dropping to his knees peel them off her legs.
She steps out of them.
He kisses the inside of her thighs, her crotch, then standing up:
JESSE I'll be right back.
On his way out of the LIVING ROOM:
JESSE I think we should hold firm for three.
He shuts off the light.
In the glow of the Fireplace, Sheila removes her jacket.
SHEILA Let's not be piggish, two five, two seven, would be a good deal.
The T.V. goes silent.
Jesse returns with a partially full glass of Champagne.
He hands Sheila a glass from a side table, takes a bottle out of an ice bucket and as he fills her glass:
SHEILA You've already had half a bottle.
JESSE You're late; if we want it, there's more.
They clink glasses.
SHEILA To us.
JESSE To three million dollars.
SHEILA We have to do this fast because remember, Marie is meeting us here.
JESSE We could ask her to join us.
SHEILA Not funny.
JESSE I wasn't trying to be.
She bops him playfully.
He bends and slips a nipple into his mouth.
Sheila bites her lip and moans.
In the KITCHEN, Mr. Smith shifts around for a better view.
The floor under him CRREEEKKS!
In the LIVING ROOM, both Sheila and Jesse react to the sound.
SHEILA Are we alone?
JESSE Yeah.
Mr. Brooks seems to appear magically out of the darkened Kitchen with his gun raised.
He's followed by Mr. Smith.
Sheila opens her mouth to scream.
MR. BROOKS Don't do that.
Detective Atwood hurries down the HALL and out of breath, stops in front of Mr. Smith's door.
She raps sharply.
Waits a bare three seconds and raps again.
DETECTIVE ATWOOD Mr. Baffert?...
DETECTIVE ATWOOD Mr. Baffert?
The door of the Apartment behind her opens and an OLDER WOMAN sticks her head out.
OLDER WOMAN He's gone.
Atwood shows her badge.
DETECTIVE ATWOOD Do you have any idea when he'll be back?
OLDER WOMAN He skipped out.
OLDER WOMAN I heard him leave this evening and a few minutes later there were Movers here.
OLDER WOMAN Musta been behind on the rent.
OLDER WOMAN He didn't even say good-bye.
DETECTIVE ATWOOD Thank you.
As the Old Lady watches, Atwood tries the knob.
It's unlocked.
She pushes the door open.
The HALLWAY and LIVING ROOM she can see are completely empty.
Furniture, T.V., camera equipment, art, gone.
OLDER WOMAN I told you.
On her way in, Atwood draws her gun.
Keeping close to the walls she audits the KITCHEN.
All the Cabinet doors are open.
Dishes, pots and pans, cutlery, gone.
She moves on to the BATHROOM.
Soap, shampoo, toilet paper, toothpaste, toothbrushes, towels, washcloths, the contents of the Medicine Cabinet, gone.
She moves on to the BEDROOM.
Bed, night table, lamps, T.V., computer, gone.
Clothes closets, empty of everything.
She looks around.
Mr. Smith's entire Apartment has been stripped absolutely clean, except...
...
there's a crumpled piece of paper in the far corner of the Bedroom.
Atwood goes over and gets down on one knee.
With her fingers pulling at the corners she is able to straighten the paper enough to make out that it's a work order from a Moving company.
Reading it with the paper pinched between thumb and forefinger of her left hand, Atwood rises.
There's the silhouette of a Man in the doorway behind her.
MAN Obviously Baffert's gone...
Atwood whirls, gun up.
She sees that it's Snyder.
DETECTIVE ATWOOD Goddamit, Snyder.
DETECTIVE ATWOOD Knock.
SNYDER I wasn't able to get the search warrant.
DETECTIVE ATWOOD We may have gotten lucky.
DETECTIVE ATWOOD This is the Moving Company's work order and...
DETECTIVE ATWOOD ...
DETECTIVE ATWOOD it looks like this is the address where they're taking Baffert's stuff.
SNYDER Where were you when you called me?
DETECTIVE ATWOOD At home in bed.
SNYDER Can you prove that?
DETECTIVE ATWOOD I was home in bed, why should I have to prove that?
SNYDER Your husband Jesse and his lawyer were killed tonight...
Atwood slowly lowers her head and fixes her eyes on the floor in stunned silence.
SNYDER It looks like the Thumbprint Killer, I've been ordered to bring you in for questioning.
DETECTIVE ATWOOD Why, I didn't want Jesse dead, I loved him, I hated what he was doing to me...
SNYDER It's on record you said you'd like him dead and who better to fake a Thumbprint killing than you.
DETECTIVE ATWOOD You can't actually believe I would do that.
SNYDER If our jobs have taught us anything, Tracy, is that people do strange things.
SNYDER They just want to ask you some questions.
DETECTIVE ATWOOD I will be happy to answer any questions after we check out this address.
Atwood goes to leave the room.
Snyder blocks her way.
SNYDER I have to take you in, Tracy.
DETECTIVE ATWOOD This is the answer to the Thumbprint Killer, Snyder, and this is where I'm going and you're not going to stop me.
SNYDER Don't make me cuff you, Tracy, because I will if I have to.
Atwood smiles winningly.
DETECTIVE ATWOOD I believe you would.
SNYDER You can count on it.
Snyder never sees it coming.
WHACK!
Atwood's right cross nails him exactly where the jaw meets the neck and down he goes on his ass.
DETECTIVE ATWOOD It would be nice if you could come with me, but if you do and it goes bad, they'll burn your ass.
DETECTIVE ATWOOD So this never happened.
Mr. Brooks' car speeds under an overpass.
SMITH That was great!
SMITH It was fantastic!
SMITH It was everything I hoped it would be.
SMITH Thank you.
MR. BROOKS You're welcome.
In the back seat:
MARSHALL Here comes the gun.
Without taking his eyes off the road.
MR. BROOKS Yup.
Mr. Smith slides a pistol from under his jacket and points it at Mr. Brooks.
MR. BROOKS What are you doing?!
MR. SMITH You're smart enough to figure that out, Mr. Brooks.
MR. BROOKS Well we're going sixty five miles an hour, Mr. Smith, if you shoot me now, there's a good chance we'll both die.
MR. SMITH Not now.
MR. SMITH Take the next off ramp.
MR. BROOKS That wouldn't be very smart of me would it?
He accelerates around a truck into the Fastlane.
Mr. Smith can see the Exit coming up, it's quickly left behind.
MR. BROOKS Think about this.
MR. BROOKS You pissed yourself back there, you left your DNA at the scene of a double homicide, and there's nothing to indicate that I was ever there.
MR. BROOKS If the Cops do an analysis of that urine, and they will, you're the Thumbprint Killer.
MR. SMITH No.
MR. SMITH I still have pictures of you doing the first murder.
Mr. Brooks smiles a knowing smile.
Beyond him on the other side of the Divider, cars are zipping by in the opposite direction.
MR. BROOKS Yes.
MR. BROOKS But what were you doing at the second murder?
Mr. Smith doesn't have an answer for that.
MR. BROOKS Let me help you with a thought.
MR. BROOKS You say I forced you to come along and if I'm not here or more specifically my body is not here to say different, you might have a chance to beat the rap.
MR. BROOKS Now you're probably asking yourself why I would help you.
MR. BROOKS I'm tired, Mr.
MR. BROOKS Smith, I'm tired of killing.
MR. BROOKS But I'm an addict, I can't quit.
MR. BROOKS I've tried.
MR. BROOKS I can't do it on my own.
MR. BROOKS So I'll let you kill me but I want you to do it smart, in a way that I disappear and my family never knows what I was.
SMITH How do I do that?
MR. BROOKS There's a cemetery I know about.
MR. BROOKS We find an open grave, you shoot me, I fall in the grave, you shovel in just enough earth to cover me, tomorrow a casket is lowered onto me and I've disappeared.
MR. BROOKS It's a good plan.
MR. BROOKS What do you say?...
MR. SMITH Why should I trust you?
MR. BROOKS You don't have to trust me.
MR. BROOKS You're the man holding the gun, you saw me put mine in the trunk.
MR. SMITH I don't know.
MR. SMITH You really want me to kill you?
MR. BROOKS Yes.
MR. SMITH Okay...
MR. SMITH But any sudden moves and you're dead on the spot and I'll make sure your family knows what you are.
MR. BROOKS I understand.
Come off the banner hanging across the front - ROOMS FOR RENT, to find Atwood walking away from her car.
DETECTIVE ATWOOD You've come down in the world, Mr.
DETECTIVE ATWOOD Baffert.
High ceilings, once grand, now blue neon and a cage around the Front Desk to protect the Night Clerk who is nowhere in sight.
Somewhere a radio is playing salsa music loud.
Atwood crosses to the elevator.
She pushes the call button.
With an arthritic rattle the door opens.
Atwood selects the 5th Floor.
Creek!, Clatter!, Clank!, the door closes and after a stuttering liftoff the car begins its ascent.
The overhead light flickers on and off.
Atwood looks up at it.
Mr. Brooks leads Mr. Smith across a street to a pedestrian gate set in a high wall.
Through the bars of the gate we can see a Cemetery bathed in moonlight.
Mr. Brooks reaches into his pocket.
Mr. Smith tightens his grip on the gun.
MR. SMITH Uh uh, take your hand out real slow.
Mr. Brooks does as he's told.
A key dangles from his fingers.
MR. BROOKS It's locked.
MR. BROOKS You don't want to climb over, do you?
MR. SMITH What are you doing with a key to a cemetery?
MR. BROOKS I own it.
MR. SMITH Why do you own a cemetery?
Mr. Brooks unlocks the gate and preceding Mr. Smith, goes inside.
MR. BROOKS You always want to invest in things people can't do without.
MR. BROOKS Water and cemeteries are pretty safe.
He locks the gate and handing the key to Mr. Smith:
MR. BROOKS You'll need this to get out.
MR. BROOKS Now there should be an open grave around here somewhere.
MR. BROOKS Let's see if we can find it.
He produces a small flashlight from his pocket and off they go.
Repeating their arthritic performance the elevator doors open.
Atwood steps out into a wide sporadically lit HALLWAY.
Peering at the numbers Atwood goes to her Left.
In the middle of the Hall behind her a Couple exits a Room and drifts to the other side of the Hall on their way to the elevator.
Atwood re-checks the number on the Moving Company's Work Order - 517, she's going the wrong way.
She turns around.
Now Atwood and the Couple are walking toward each other on opposite sides of the Hall.
Atwood steps into an area of light.
The reflection off her face catches the attention of the Man who is wearing a wide brimmed hat.
He lifts his head.
It's Thorton Meeks.
The Woman with him was the Driver of the Van.
She's wearing a watchcap.
Meeks gently takes his Companion's arm.
They stop.
Her eyes go to where he's looking and then back to his.
At some unspoken signal they both draw their guns.
Intent on finding 517 and Baffert, the Couple hasn't registered on Atwood's radar.
BANG!
TWOCK!
A chunk of plaster blows off the wall next to her head.
Startled, Atwood winces away.
BANG!
The Woman fires.
The slug explodes the plaster on the other side of Atwood's head.
Now Atwood is turning toward them, gun in hand.
Meeks fires.
The bullet passes through Atwood's jacket.
Instinctively Atwood assumes a classic duelist's pose offering the smallest target possible.
Calmly she squeezes off her first shot.
The plaster explodes from the wall above Meeks' head.
The Woman fires.
A hole appears in Atwood's sleeve.
Atwood pulls the trigger again.
SMACK!
The Woman screams and falls back into Meeks, a bullet in her hip.
Atwood's third shot takes the hat off Meeks head.
She now realizes who her attackers are.
DETECTIVE ATWOOD Meeks?!!
Dragging the Woman in the direction of the stairs, BANG!
Meeks fires.
Maybe it's his broken trigger finger that affects his aim.
The shots miss.
BANG!
BANG!
The Woman fires.
Atwood's next two shots miss.
Meeks and the Woman arrive at the stairs and before rounding the corner, BANG!
BANG!
BANG!, fire at Atwood who is now moving deliberately at them.
Atwood doesn't try and dodge the bullets or flinch away from them and her shots are unhurried.
The next one catches the Woman in the side.
The one after that nails Meeks in the left shoulder.
He's spun into the Woman.
Leaning on each other Meeks and the Woman lurch down the worn marble steps.
Atwood reaches the stairs and cheats a look around the corner.
BANG!
BANG!
BANG!
From the landing below, Meeks and the Woman fire.
Atwood steps out from behind the wall and shoulders square, shoots.
Another sidestep.
This shot shatters Meeks' knee.
He bellows in pain.
Moving to the side again, Atwood shoots.
But Meeks' knee has collapsed and he and the Woman are already tumbling down the next set of steps.
Atwood waits.
There's silence, then the murmur of voices.
MEEKS Atwood?
DETECTIVE ATWOOD Yeah.
MEEKS Come on down, there's something I want to show you.
Gun at the ready, Atwood edges her way downward.
At about the tenth step she is able to lean over and look through the banisters.
Meeks and the Woman are propping themselves up against the wall on the LANDING below.
Both of them still have their guns.
The moment Meeks' eyes meet Atwood's, he puts his gun to the Woman heads.
BANG!
Atwood sucks in her breath.
Meeks puts the gun to his temple.
BANG!
Atwood clasps a hand to her mouth and exhales in ragged gulps.
The finger of light from Mr. Brooks' handtorch discovers a freshly dug GRAVE.
MR. BROOKS There we are.
MR. BROOKS Now if I stand here...
He positions himself at one end of the Grave.
MR. BROOKS ...
MR. BROOKS and you stand there, not too far away and you shoot me, I should fall straight back into the hole.
MR. SMITH You don't think I have the guts to do this do you?
MR. BROOKS I'm hoping you do.
Mr. Brooks shuts off his light and straightens up.
MR. BROOKS Okay, let's get this over with.
Mr. Smith raises his gun and points it at Mr. Brooks's head.
He hesitates.
MR. BROOKS I'll close my eyes.
He does.
Mr. Smith pulls the trigger.
Click!
Mr. Smith looks in horror at the malfunctioning gun.
Mr.
Brooks opens his eyes.
Mr. Smith aims the gun again.
Click!...
Click!
MR. BROOKS I'm sorry.
As he talks he counters around until Mr. Smith is the one with his back to the open Grave.
MR. BROOKS I really did want you to kill me.
MR. BROOKS But in case at the last minute I changed my mind, I returned to your apartment and bent the firing pin on your gun.
He wrenches the shovel out of a mound of waiting earth.
Mr.
Smith tries to fire the gun at Mr. Brooks again.
BROOKS In fact I even brought another gun for you so you could finish me if I had decided to go through with it.
He opens his jacket and shows Mr. Smith the gun.
BROOKS Unfortunately for you, my daughter is pregnant and just before you pulled the trigger, I realized how much I want to see the end to that story.
MR. SMITH If you do anything to me, if you touch one hair on my head, the Police will find the pictures of you killing that Couple.
MR. BROOKS The contents of your safety deposit box, Mr. Smith, have vanished.
Without warning, Mr. Brooks swings the shovel.
The force of the blow breaks Mr. Smith's left arm.
He howls.
The next blow comes almost immediately.
It smashes into the left side of Mr. Smith's head.
The screams stop and a misfiring set of neurons causes Mr.
Smith to stand up straight and wobbling, look directly at Mr.
Brooks.
The blood streaming down his face is black in the moonlight.
Mr. Brooks takes a step to the side, cocks his wrists and swings again.
His full weight is behind this one.
The blade of the shovel strikes Mr. Smith in the throat very nearly taking off his head.
The flesh that was once Mr. Smith falls to the ground.
MR. BROOKS Before I was the Thumbprint Killer, Mr. Smith, I killed a lot of people in a lot of different ways.
Looking up.
Mr. Smith's body is rolled over the edge.
It falls on top of us.
Mr. Brooks takes a shovel of dirt from the pile and whistling 'By The Light Of The Silvery Moon', begins the task of covering Mr. Smith.
A Newspaper is lying unfolded on the Counter next to the remnants of a breakfast.
The headline reads - NATIONWIDE MANHUNT FOR THUMBPRINT KILLER - Under that headline is a large picture of Mr. Smith aka Mr.
Baffert.
In the lower right corner is another headline to a story - Murder Suicide For The Hangman -.
The reader of the paper is Mr. Brooks.
On a stool next to him, Marshall is also reading.
MARSHALL It says here the Thumbprint Killer is a monster...
MARSHALL annoys you a little bit that you can't take credit, doesn't it?
MR. BROOKS Anyone who is good at what they do, wants recognition.
MR. BROOKS But since I'm not going to do it anymore, I'll let Mr. Smith take the credit.
MARSHALL Don't kid yourself, Earl, you're going to kill again.
MR. BROOKS No, I'm not.
MR. BROOKS I'll continue the AA meetings and I'll control it.
On the other stool next to Mr. Brooks is a WOMAN.
Her large purse hangs open from the back of the stool; the cel phone clearly visible inside.
Mr. Brooks looks at the phone.
MR. BROOKS But there is an answer I would like to have.
Detective Atwood is seated in her CUBICLE reading the same front page Mr. Brooks was reading.
A FELLOW OFFICER stops in the door.
OFFICER Good work, Atwood.
DETECTIVE ATWOOD Thanks, Tom.
He moves on.
From off screen:
ANOTHER OFFICER You should ask the FBI to kiss your ass and buy you a Cadillac.
DETECTIVE ATWOOD I like my ass too much for that.
Snyder comes in and holds up the Work Order from the Moving Company.
SNYDER This is bogus.
SNYDER The company doesn't exist in the city, the state, the United States or Canada.
DETECTIVE ATWOOD So the whole point of this piece of paper was to give me Meeks.
SNYDER That's what it looks like.
DETECTIVE ATWOOD Why?
DETECTIVE ATWOOD Who moved him, where did they move him to, and why did he give me Meeks?
SNYDER That's what we get paid to find out.
Atwood picks up the Newspaper.
DETECTIVE ATWOOD I'm going to go to the bathroom and think about this.
She stands.
The phone rings.
She answers it.
DETECTIVE ATWOOD Detective Atwood...
Looking out at the city, Mr. Brooks speaks into the cel phone he stole from the Woman.
MR. BROOKS Why are you a cop?
INTERCUT with Atwood.
DETECTIVE ATWOOD Who is this?
MR. BROOKS You're rich, you have a good education, you could have gone into your father's business, instead you went outside all of that and became successful on your own.
MR. BROOKS Why?
DETECTIVE ATWOOD You want something from me if you don't tell me who you are I'm going to hang up.
MR. BROOKS Did you think your husband's killing was random and I certainly didn't have to give you Meeks.
DETECTIVE ATWOOD Mr. Baffert?!
Snyder perks up.
She points for him to get on the other line.
MR. BROOKS What's the answer?
DETECTIVE ATWOOD You don't sound like you.
MR. BROOKS I have a little cold.
MR. BROOKS Are you going to give me the answer?
DETECTIVE ATWOOD Where are you?
MR. BROOKS I'll tell you if you can give me the true answer to my question.
Detective Atwood weighs her options and decides to go for it.
DETECTIVE ATWOOD My father was very disappointed I was born a girl and he let me know that.
DETECTIVE ATWOOD I've spent my whole life trying to prove him wrong.
MR. BROOKS Thank you.
DETECTIVE ATWOOD Wait.
DETECTIVE ATWOOD You promised to tell me where you are.
MR. BROOKS Me?
MR. BROOKS I'm on top of a building.
Atwood and Snyder hear the click as Mr. Brooks hangs up.
DETECTIVE ATWOOD Why would he be interested in that?
At the Parking structure, Mr. Brooks holds the phone over the edge and drops it.
We follow the phone down, down, down, until it hits the pavement and disintegrates.
Everything is as it was.
It's dark.
In his robe and pajamas, Mr. Brooks is standing in front of the open refrigerator gazing blankly at the contents with a glass of milk in one hand.
There's nothing he wants in here.
He closes the door.
Carrying the glass of milk, Mr. Brooks passes Jane's ROOM.
The door is ajar.
He stops, backs up and looks.
His Daughter's asleep.
Mr. Brooks walks to the bed and leans over to give her a kiss on the cheek.
His lips have just brushed her flesh when she twists violently under him and stabs upward with a pair of scissors.
The blades are driven deep into his throat.
Mr. Brooks jerks back, the milk flies out of his hand.
MR. BROOKS Agghhh!!!
MR. BROOKS Agghhh!!!
He grabs at the handle of the scissors, but his blood makes them too slippery.
He can't pull them out.
EMMA (V.O.) Honey, Earl, Earl...
Mr. Brooks is tossing in his sleep next to Emma.
She has a hold of his arm.
EMMA Wake up, wake up...
On the pillow Mr. Brooks' eyes fly open.
EMMA You were having a nightmare.
MR. BROOKS Oh...
MR. BROOKS I woke you up.
EMMA It's okay.
She kisses him on the forehead.
EMMA (CONT'D) I'm here, go back to sleep, I'm here.
Taking his hand, she lies back down.
After a moment Mr.
Brooks turns over on his side and looks directly at us.
His lips begin to move but we can't hear what he's saying, so we move in on his face.
It's not until it fills our view that we can hear the words.
MR. BROOKS ...
MR. BROOKS that I may be reasonably happy in this life, And supremely happy with Him forever in the next.
MR. BROOKS Amen.
MR. BROOKS ....
MR. BROOKS God grant me the Serenity to accept...
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
