MARLEY & ME
Written by
Don Roos
March 7, 2007
Some microphone feedback followed by:
Okay, here we go...
everybody watching?
Our screen goes WHITE as a POWERPOINT PRESENTATION BEGINS...
SEBASTIAN (V.0.) (CONT'D) I'd like to tell you all a little lov e story...
SEBASTIAN (V.0.) (CONT'D) But the images n screen are JOURNALISTIC PHOTOS OF
SEBASTIAN (V.0.) (CONT'D) Whoops...
SEBASTIAN (V.0.) (CONT'D) wrong file...
LAUGHTER O.S. and we begin PULLING BACK TO REVEAL:
The lights are dim.
We're looking at a blank, pull-down movie screen in a darkened ballroom.
SEBASTIAN (CONT'D) Hang on, I got this-- Someone O.S. starts CLINKING a fork against a wine glass.
SEBASTIAN (CONT'D) Is joined by others, and then we HEAR calls of "Kiss!
SEBASTIAN (CONT'D) Kiss!"
sitting at the main table, In silhouette, seen from behind, lit only by the votives sprinkled along the table: JOHN GROGAN and his bride of two hours, JENNY.
In response to the crowd, they kiss.
Standing right by them is SEBASTIAN -- tall, good looking, rugged type --John's best man.
SEBASTIAN (CONT'D) Alright, now I'm ready--
And now, on THE PORTABLE SCREEN, Sebastian'S MONTAGE BEGINS: John with his Mom in front of the college dorm, etc.
SEBASTIAN (CONT'D) Here's John, first week of college.
SEBASTIAN (CONT'D) Nice hair, right?
You think that feathering 'S easy?
true.
Takes a very well p wrist action...
CHUCKLES from the crowd.
SEBASTIAN (CONT'D) I'm just saying...
Throughout college...
SEBASTIAN (CONT'D) Was John a star athlete?
SEBASTIAN (CONT'D) A shot of him fumbling a frisbee,
SEBASTIAN (CONT'D) Umm, no.
SEBASTIAN (CONT'D) Was he a ladies man?
SEBASTIAN (CONT'D) With mid-eighties hair, bad glasses.
SEBASTIAN (CONT'D) You tell me.
What he was, was John, and we loved for it.
Taken r.
Sebastian.
up l ^a ni? 1/2 ghte Sebastian turns the camera on himself, holds Sharpie pen, smiles.
SEBASTIAN And he was always looked after by his guardian angel and best friend.
John walking down the quad, with "DUMBASS" written on his forehead.
People passing him are smirking.
JOHN (to CAMERA, which is
People are staring at me - is my fly down?
SEBASTIAN No, no, it's cool.
JOHN All right, enough with the -
JOHN - all right, what?
JOHN What are you looking at?
SEBASTIAN Oh, wait, there's something on your forehead.
SEBASTIAN John brushes it.
SEBASTIAN (CONT'D) You got it.
SEBASTIAN (CONT'D) Leaf or something.
A leaf.
On my forehead.
SEBASTIAN Yeah, it musta had some sap on it.
SEBASTIAN They pass a cluster of CO EDS who laugh at John.
SEBASTIAN (CONT'D) And then there's Jenny.
Looking, indeed, very cool, very put together.
SEBASTIAN Studious, hard-working, quiet.
In short-shorts, wet T-shirt, throwing water balloons at a frat house.
Standing on an empty keg of beer, rolling it like it's a log.
SEBASTIAN (CONT'D) Well, okay, sometimes not so quiet.
Ordering a bunch of guys around, telling who to go where, as the camera ZOOMS OUT, we see they're playing touch football - except she tackles.
Hard.
And then does a little victory dance over the fallen.
Jenny's the captain, in charge...
SEBASTIAN (CONT'D) Okay, maybe a little high-spirited, maybe voted Miss Kegger once or twice too often on Fraternity ROW, but a good girl underneath it all.
SEBASTIAN (CONT'D) Now could they not fall in love?
One of John "flexing" beside a lake, another of Jenny screaming at a football game with a beer in her hand.
SEBASTIAN (CONT'D) Now, in any decent love story, you gotta have the great first meeting.
Sebastian is obviously the passenger shooting John, who's driving.
All right, I'm zooming in.
Whoa.
Not a flosser.
JOHN Turn it off.
JOHN And as he REACHES for it - WHAM'.
JOHN He hits another car!
JOHN The camera goes flying.
JOHN Fumbles.
JOHN SCREAMS.
JOHN YELLS.
JOHN (CONT'D) Jesus Christ!
SEBASTIAN They're okay!
SEBASTIAN They're getting out.
SEBASTIAN Sebastian manages to right the CAMERA and unsteadily films John getting out of the car, heading towards the car he hit.
SEBASTIAN The passenger door opens and Jenny comes out.
SEBASTIAN She's covered in frosting and the remains of a birthday cake which she was carrying in her lap.
SEBASTIAN The damaged car is full of balloons.
JENNY Are you a complete idiot?!
SEBASTIAN And so one of the truly great love affairs of the late eighties began.
SEBASTIAN In the home video, Jenny advances on John, hurls the rest of the cake at him, starts flailing at him with her hands.
The driver of the car, another co-ed, gets out and yells at CAMERA (Sebastian).
SEBASTIAN (CONT'D) Brought together by their love of fast cars, spirited Baskin- Robbins Dreamy Drizzle Ice Cream cake.
John and Jenny both at typewriters.
SEBASTIAN From there, they went on to work together at the school newspaper.
Shot of Jenny standing at the head of a table full of reporters.
SEBASTIAN (CONT'D) Although, technically, they didn't work together so much as John worked for Jenny who was the editor of said paper...
In her office, through the semi-closed Venetian blinds.
SEBASTIAN (CONT'D) Let's just say there were some flagrant workplace violations.
John and Jenny, both in cap and gowns, drinking from plastic champagne glasses.
John displays the top of his cap to CAMERA: the words "NEED JOB" are spelled out in white adhesive tape.
SEBASTIAN The point is their love grew, blah blah blah...
SEBASTIAN And that love continues tonight.
The wedding GUESTS APPLAUD, the lights come up, and Sebastian concludes his toast.
SEBASTIAN And now, please join me in raising a glass to my future neighbors down in Florida, and to the dawn of both a marriage end a brilliant journalistic team, the new Woodward and Bernstein, this time with sex.
SEBASTIAN Bad sex, probably, but - anyway: to John and Jenny Grogan.
She's had an ffect on He's not so much break applause.e him.
They kiss as
PULL BACK TO REVEAL we're looking out a window.
JENNY MmzmII[lm.
JENNY That feels so good.
The two of them sit on the edge of the bathtub, soaking their sore feet.
Jenny's still in her wedding dress, bunched up so as not to get it wet.
John has got the pant legs of his tux rolled up.
Jenny takes a swig from a bottle of champagne, passes it to John.
He looks at her.
JOHN How do I get vou?
JENNY What?
JOHN I'm serious.
JOHN In what world does a guy like me get someone like you?
JENNY Are you kidding?
JENNY You're part of the plan.
JOHN The plan.
JENNY Step one.
JENNY Meet an incredibly sweet, smart, sexy guy.
JOHN Done.
JOHN Step two?
JENNY Marry him.
JOHN Check.
JOHN Step three?
JOHN She smiles, puts her face right up to his...
JENNY Now that one's a surprise...
JENNY They kiss and as we push past them, into the snowy window, we END CREDITS and...
A HEAT MIRAGE.
A battered Toyota Tercel comes over.
a rise.
We follow the car through town, get
Jenny driving.
John clutching his portfolio on his lap.
She cuts a look at him.
JENNY You okay?
JOHN Oh yeah.
As jenny pulls up out front of the building.
She turns to John.
JENNY You know you got this.
JOHN I know, I got it.
JENNY Who are you?
JOHN I'm John Grogan.
JENNY Wrong.
JENNY You're John Friggin Grogan who's about to get a job.
JENNY She leans over and gives him a big, long kiss.
JOHN Um, okay, see now I don't wanna get out of the car.
JOHN i really just wanna sit here and make out with you.
JENNY --Get out of the car.
JENNY He nods, starts to get out, then pauses.
JOHN Who am i again?
Kidding.
As John crosses his fingers, waves and enters the building...
ARNIE (V.0.) Sebastian says you won some award?
ARNIE KLEIN -- fifties, never smiles, flowered shirts -- the editor of the Sun-Sentinel of Fort Lauderdale, Florida, is flipping through John's portfolio.
JOHN Yes, sir, I got a Mitchy.
JOHN (CONT'D) Like a Pulitzer, but for western Michigan.
ARNIE A Mitchy.
ARNIE Min-hmm.
ARNIE So, tell me, why did you want to leave the estimable - (he flips to a story, reads
- Kalamazoo Gazette?
JOHN Well, as you know, Sebastian and I were in college together, and he was always talking about South Florida...
JOHN mostly about the women of South Florida, but anyway, after my wife and I got married we thought it might be nice to come
ARNIE For the women?
JOHN Uh, no-- for the...
JOHN the...
JOHN uh...
ARNIE For the work?
JOHN Yes.
JOHN That.
ARNIE Your wife's Jenny Havens, right?
JOHN Well, Jenny Grogan now--
ARNIE She take the job at the Post?
ARNIE I tried to get her over her
ARNIE Damn fine writer.
ARNIE (CONT'D) What's the matter, the Post didn't want Yo m?
JOHN Well, she does features.
JOHN I'm more a straight news writer.
JOHN This is a better paper for that.
ARNIE Straight news writer, huh.
ARNIE Meaning you think you're a reporter?
JOHN Meaning I know I am.
ARNIE And the six other sweaty-palmed college grads I'm interviewing today, you think you're better than them?
JOHN No, sir.
JOHN In fact, I'm pretty sure I'm not.
JOHN But I do know that I always seem to surprise myself.
JOHN Ten years ago, I was doing bong hits and playing Donkey Kong, never dreamed I'd get into college.
JOHN But I did, and I graduated with honors.
JOHN Two years ago, my buddies told me that the most Jenny Havens would ever say to me was, You're sweet, but I don't like you in that way..
JOHN But she did like me in that way-- and my buddies can suck it because I married her.
JOHN I certainly never thought I'd win some award with a dumbass name--
The "Mitchy."
Exactly sir.
But i surprised myself and I won it.
And if you give me the chance, I'm pretty sure I'll surprise you, too.
Arnie considers him a moment.
ARNIE That's quite a speech, son.
ARNIE You rehearse that, or come up with it on the fly?
JOHN Elevator, on the way up.
How'd I do?
Arnie just looks back at him.
Jenny is writing in her NOTEBOOK when we see John crossing the street through the passenger window.
She looks at him.
Afraid to ask.
JENNY So?
JOHN He's got me on a little thing they like to call...
JOHN Desert Storm--
She gets out of the car and the two embrace right there on the street.
She takes out her notebook, crosses something off on her "list."
JENNY (CONT'D) okay...
JENNY (CONT'D) "Jobs."
JENNY (CONT'D) Done.
JOHN So what's next?
JOHN Lunch?
House.
A HORN HONKING as a ca g nos by on the Dixie Highway in the b.g.
We tilt down to a very mixed neighborhood, to a modest house, THE SOUND OF A TV BROADCAST OVER...
News footage of Iraq's invasion of Kuwait on television.
John and Jenny sit at the table reading a different newspapers.
He glances at her...
JOHN You like the quote about the speed bumps?
"If they save even one life--"
JOHN -"it would be worth it.
JOHN And with that, Janet Dickerson's mother's eyes filled with tears."
That one just felt exactly right, y'know?
JENNY Yeah, no, it's good.
JENNY What happened to the Desert Storm piece?
JOHN That's it.
JOHN The injured girl's dad's in Kuwait.
JOHN What, that's not in there?
JENNY Uhhhh...
JENNY they must've cut it...
JENNY And they kinda misspelled your name.
JENNY John Egan...
JOHN What-- you're kidding-- He reaches for the paper, but she holds it away.
JENNY Forget it.
JENNY It's good, John.
JENNY It's got facts, some color.
JENNY It's a solid piece.
JOHN Thanks.
JOHN I'm almost done with yours.
JOHN This idea of voting machines sounds
JENNY Well, except on the other page I talk about what could happen-- He goes back to reading.
JENNY She sips her coffee.
JOHN Oh, it continues...
JOHN An awkward moment as he now searches for the new page, has to fold back the paper.
JOHN No escaping the fact that ie article is longer and more important than his.
JOHN She finally gets up...
JENNY You know what?
JENNY The rest is just okay, really pretty boring...
JOHN No, no, I'm enjoying it...
JOHN He tortures himself and keeps reading.
JOHN She moves to the sink, starts to rinse out her cup...
JOHN (CONT'D) Wow, they really gave you a lot of space, didn't they?
JOHN (CONT'D) She sets the cup on the counter, looks at the WILTED PLANT on the sill.
JENNY Damn.
JENNY I killed another one.
JENNY How am I ever going to take care of a kid, I can't even keep a plant alive?
JENNY John looks up from the paper.
JENNY "Kid?" She comes gives him a kiss.
JENNY (CONT'D) I'll see you later, Mr. Gorgan.
JENNY (CONT'D) She headsout, leaving John staring terrified at the plant.
A kid, huh...
Sebastian and John fill up at the coffee pot, start to move through the office throughout...
SEBASTIAN Well, what'd you expect?
SEBASTIAN You bought a house, man.
SEBASTIAN A house with a mare room...
JOHN What's wrong with a spare room?
SEBASTIAN It's empty, John.
SEBASTIAN That's what's wrong with it.
SEBASTIAN And you know what else is empty?
SEBASTIAN Her womb.
JOHN I'm starting to worry that we're already at Step Six.
SEBASTIAN What?
JOHN You know Jenny, she's got her whole life organized and planned out...
JOHN Sebastian smiles at a secretary, turns back to John.
SEBASTIAN You want my advice?
SEBASTIAN Get her a PuPPYa??
JOHN A puppy.
SEBASTIAN Something other than you she has to take care of.
SEBASTIAN You have a kid, you're a dad.
SEBASTIAN You're not you anymore.
SEBASTIAN You have a dog, you're a master.
SEBASTIAN You're still a guy.
SEBASTIAN With a life.
JOHN And a dog...
SEBASTIAN Whatever, man.
SEBASTIAN You're still free.
SEBASTIAN You've stopped the clock.
JOHN What clock?
SEBASTIAN Okay...
SEBASTIAN you know in movies when there's, like, a bomb and it's ticking down, ten seconds left, and there's some guy with a wire cutter going, "red wire...
SEBASTIAN blue wire...
SEBASTIAN which one do I cut?" And the guy finally just makes a wild-assed guess and SNIP.
SEBASTIAN Silence.
SEBASTIAN The world is saved.
JOHN Okay...
JOHN is the bomb strapped to a dog...
JOHN because I'm not sure I'm
SEBASTIAN John, you buy this dog, you're saving your world.
SEBASTIAN Because that ticking you hear, is not a bomb, it's her biological clock.
SEBASTIAN John looks back at him.
JOHN Huh.
Sebastian!
They both turn as Arnie sticks his head out of his office.
ARNIE (CONT'D) Your travel's approved.
ARNIE (CONT'D) Get outta here.
SEBASTIAN In motion.
JOHN Where you going?
SEBASTIAN Colombia.
SEBASTIAN I got a guy down there, says he can put me next to Pablo Escobar-- I'm doing this piece, I follow a single coca leaf from Colombia, to the streets of Miami.
JOHN Yeah, you and I once talked about doing something like that.
JOHN We were gonna call it, "From Plant to Pusher."
JOHN Remember?
SEBASTIAN Not really.
--there was another fire at the county dump.
Some kinda methane leak.
JOHN Actually, it's Grogan--
ARNIE I want two paragraphs for the blotter.
John nods, looks off at Sebastian who now sits down at his cluttered desk, pulls a DUFFLE BAG from under his desk.
John watches with envy as Sebastian starts stuffing cameras, recorders, a bowie knife, into the duffle...
JOHN So uh, what kind of puppy?
JOHN Sebastian looks up at him.
JOHN (CONT'D) To, y'know, cut the wire.
SEBASTIAN Get her a lab.
SEBASTIAN They're supposed to be just like little kids.
SEBASTIAN But easier to train.
As John and Jenny get out of the car.
She looks at the house.
JENNY This isn't the ihop...
JOHN A little surprise first...
John is leading Jenny, her eyes closed, through a house towards the kitchen.
LORI, 55, leathery and smoking, is going in front.
LORI Sorry about the smell.
JENNY When can I look?
JOHN Just hang on...
JOHN Lori opens a door to a laundry room.
JOHN (CONT'D) Okay.
JOHN (CONT'D) Now.
JOHN (CONT'D) Jenny opens her eyes and sees a utility room.
JOHN (CONT'D) Nine yellow yipping Lab puppies tumble out of a cardboard box towards John and Jenny.
JOHN (CONT'D) Happy Birthday.
JENNY Oh my God...
JENNY they're adorable...
Wait a minute, my birthday's a month from now.
LORI That's okay, they can't leave for another three weeks anyway.
JENNY John, we never even talked about this.
JOHN You're right.
JOHN Let's go.
JOHN He's kidding.
JOHN And besides, Jenny's already on the floor, letting the puppies climb all over her.
JENNY Look at you guys...
LORI I got papers on the mom and the dad, so you can register these.
JOHN Is the father here too?
Oh, yeah, somewhere.
Anyway, girls are $400, boys are $375.
Except this little guy here.
She points to one male puppy, who is clearly the goofiest most excited.
LORI (CONT'D) You can have him for $325.
JENNY How sweet.
JENNY He's on clearance...
LORI Well, he's a little too stocky for the breed, so he probably won't show.
JENNY He's so sweet...
Marley & He Shooting Draft 18.
JOHN He likes you.
JENNY John, I don't know if I'm ready for a
LORI You have to wait three weeks for the litter to get weaned, before you can bring 'em home anyway.
JOHN Plenty of time to get ready.
JENNY I won't even be here.
JENNY I'm gonna be with my sister then...
JOHN No problem.
JOHN I can take him.
JOHN Be good bonding time.
JOHN Get him all trained in time for you to come home.
JOHN A chuckle from Lori.
JOHN (CONT'D) Let's give 'em all the scare test.
The what?
JOHN I hear the best dog in the litter is the one who doesn't spook easily.
JOHN They turn out to be the most people- centered.
Uh, how are you gonna-- John turns away, and then suddenly turns back with a loud step and a "BOO"!
All of the puppies scatter.
Lily barks.
But Clearance Puppy just leaps onto his shoes, his tail wagging.
LORI (CONT'D) Well, that's your guy.
LORI (CONT'D) John scoops him up.
LORI (CONT'D) Clearance Puppy licks his face.
LORI (CONT'D) John hands him to Jenny.
LORI (CONT'D) She lets him lick her face...
JENNY I would've picked you anyway--
JOHN Meant to be.
JOHN He watches her cuddle the puppy and knows he's done the right thing.
Lori waves goodbye, check in her hand, as John and Jenny walk to the car.
Jenny carries a Polaroid of Clearance Puppy.
JENNY You really sure about this?
JENNY I mean, a puppy's a lot of work.
JOHN How hard could it be?
JOHN We hear A COMMOTION is coming from the woods, something crashing through the brush, breathing heavily.
JOHN They both freeze as the sound comes their way.
JENNY What's that?
JENNY Just then they are nearly knocked off their feet by a huge, rampaging Labrador, soaking wet, covered with mud and burrs.
JENNY It circles them, barking WILDLY, a crazed look in its eye.
JENNY It jumps up on John, muddies his shirt, then barrels past Lori into the house, knocking over a chair on the porch as it goes.
JENNY A beat.
JOHN I think we just met the dad.
John kissing Jenny good-bye.
They finally part...
JENNY Call me as soon as you get him home.
JENNY Oh, hey, we need a name.
JOHN How 'bout I just call him "Clearance Puppy" until you get back.
JOHN I only hope he doesn't say his first word without you.
John steps out of his car and the puppy, now twice the size he was three weeks ago, bounds over to him.
A harried Lori follows, a rope leash and instruction.
sheet in hand.
JOHN Whoa!
JOHN He got big...
JOHN This is the right one, right?
LORI You should see him pack away the puppy chow.
JOHN So, what if I run into any problems?
Oh.
Sure, call me.
All sales are final, though.
Not just for him.
I tell that to everyone.
You want help getting him in the car?
JOHN No, that's okay, I'll just...
JOHN John opens the door, indicates that Marley should jump in.
JOHN Instead, the puppy runs around the car, barking, jumping up on the bumpers.
JOHN John finally catches him, lifts him up, puts him on the front passenger seat atop some towels.
JOHN (CONT'D) There we go.
Well, anyway, thanks for-- But Lori's already inside her house, the door closed.
John and the puppy on the drive home.
The puppy atop a pile of towels.
John looks at him.
JOHN Hey...
JOHN guy.
JOHN The dog just stares at him quizzically.
JOHN Uncomfortable alone with the dog, John turns on the radio.
JOHN BOB MARLEY plays and the puppy THUMPS HIS TAIL.
JOHN (CONT'D) You like Bob Marley?
JOHN (CONT'D) The dog THUMPS HIS TAIL AGAIN.
JOHN (CONT'D) John turns up the music.
JOHN (CONT'D) THUMP.
JOHN (CONT'D) THUMP.
JOHN (CONT'D) THUMP faster this time.
Bob?
Marley.
JOHN (CONT'D) Marley.
JOHN (CONT'D) Okay-- Marley.
JOHN (CONT'D) Cool.
JOHN (CONT'D) But now the pup starts wriggling towards John, John tries to put him back...
JOHN (CONT'D) No-- stay boy...
JOHN (CONT'D) stay.
JOHN (CONT'D) Okay, not really safe, bud-- Marley gets stuck with half his body draped over the console.
JOHN (CONT'D) He remains like this, his tail thumping...
JOHN (CONT'D) John gives up.
JOHN (CONT'D) Alright, fine, but just this time.
25 EXT. 345 CHURCHILL ROAD - NIGHT door.
The dog John pulls up in the driveway and opens the jumps out.
JOHN This is our house...
JOHN The dog immediately pees on the ground.
JOHN (CONT'D) And now it's yours.
As John crouches down, shows him his bowls...
JOHN This one's water.
JOHN This one's food.
Marley starts pawing the food bag.
JOHN (CONT'D) C'mon, man, you've already had kibble and half a seat belt.
JOHN (CONT'D) All right.
JOHN (CONT'D) Special treat.
JOHN (CONT'D) But just today...
JOHN (CONT'D) He opens the bag and Marley tackles it.
JOHN (CONT'D) Several cupfuls spill onto the floor.
JOHN (CONT'D) John goes to the pantry to get the dustpan and brush.
JOHN (CONT'D) When he returns, he finds Marley has eaten the food in the bowl AND every last scrap of spilled food.
JOHN (CONT'D) And now he's squatting to pee again...
JOHN (CONT'D) No, no, no!
JOHN (CONT'D) He picks up the puppy and rushes him outside.
As John sets him down on the ground, steps back.
JOHN Okay, now.
JOHN Pee.
JOHN He motions with his zipper.
JOHN (CONT'D) C'mon, man, do your thing.
JOHN (CONT'D) Alright, I'm gonna show you this one time...
JOHN (CONT'D) From behind, we see John peeing.
JOHN (CONT'D) Except you gotta lift your leg.
JOHN (CONT'D) See, this is how you guys do it...
JOHN (CONT'D) Marley looks at him, squats and pees...
JOHN (CONT'D) Or you could do it like that.
JOHN (CONT'D) Just not in front of other guy dogs.
Jenny's on the phone.
Her young NIECE and NEPHEW wait for her, a board game on the floor between them.
She motions that she'll just be a second...
JENNY Marley.
JENNY I like that...
John's on the phone, talking to Jenny as he follows Marley around the room, trying to keep shoes and socks and cords out of his mouth...
JOHN Are you sure?
JOHN Because it can be temporary...
JENNY No, it's good.
He must be exhausted.
JOHN Oh, yeah, he's pooped.
JOHN Marley lets out a SQUEAK as he tugs at a couch cushion...
Oh, he sounds so sweet!
JOHN Yeah...
JOHN He's very cute.
JOHN Just like a little kid only furrier.
JENNY Put the phone by his ear...
JENNY John chases after the dog who burrows under the couch, his tail sticking out so that John can't get him...
JOHN Uh, okay, he's listening.
JOHN John just holds the phone awkwardly as Jenny coos baby talk.
JENNY Hey, Marley!
JENNY Who's my good boy?!
JENNY Mommy can't wait to meet you...
JOHN Anyway, don't worry, he's doing great.
JOHN Like he's lived here his whole life.
JOHN All eight weeks of it.
JOHN And you know what else?
JOHN I think he's going to be pretty easy to train.
JOHN I mean, he's curious which means he's smart, right?
JENNY Of course he is.
JENNY I can't wait to see him.
JOHN Just him?
JENNY Jealous?
JOHN I'm not the one sleeping in a box.
JENNY I love you.
JENNY I'll see you Friday.
John, dressed to go out, is setting down Marley in his wooden box on the garage floor.
JOHN I'll see you in the morning, okay?
JOHN Marley looks at him with a heartbreaking expression.
JOHN John hesitates.
JOHN (CONT'D) Aw, come on, don't.
JOHN (CONT'D) You'll be fine, alright.
JOHN (CONT'D) And tomorrow, we're gonna tear it up.
JOHN (CONT'D) I'm thinking kibble, park, chew toy, the whole nine yards.
JOHN (CONT'D) Okay?
JOHN (CONT'D) we good?
JOHN (CONT'D) Marley doesn't-look so good, looks kind of sad.
JOHN (CONT'D) John turns and gets out of there.
John gets into his car.
He can hear WHIMPERING.
JOHN Big day tomorrow!
JOHN Rest up, pal!
JOHN He listens a beat; Marley quiets down.
JOHN He gets in his car.
Journalist hang out.'John and Sebastian at the bar.
Many know Sebastian, he's constantly nodding at people throughout:
SEBASTIAN So I'm there in this cave, right?
SEBASTIAN Blindfolded.
SEBASTIAN And I can feel the machine guns, there's like nine of 'em around me...
SEBASTIAN and they tie me to a chair and then Escobar comes in and says-- are you ready?
I read your piece on Kadahfi, And I think you captured his narcissism just right.
Can you believe that?
JOHN Some of it.
SEBASTIAN Man, I wish you could've been there.
JOHN Yeah, but then I wouldn't have been able to do the piece on the water main break at the library.
JOHN That would have sucked.
SEBASTIAN Your time will come, amigo.
JOHN I'll drink to that-- They toast with their beers, Sebastian clocks John looking at his watch.
SEBASTIAN You gotta be somewhere?
JOHN Oh.
JOHN No, it's the puppy.
JOHN It's his first
SEBASTIAN You got adoc?
JOHN Marley.
JOHN A little lab.
JOHN Like you said.
JOHN Remember?
JOHN The bomb...
SEBASTIAN Oh, right.
SEBASTIAN Smart move.
SEBASTIAN You'll see.
SEBASTIAN You've just preserved your quiet way of life for at least another two years.
John pulls up, gets out of his car.
Halfway down the block, we see a POLICE CAR, lights flashing, two OFFICERS talking to a COUPLE.
Another NEIGHBOR, in his robe, stands in the street watching...
Millers got robbed again.
And that mutt of yours hasn't shut up since you left.
John looks towards the garage where we hear WHIMPERING.
The door opens and the puppy gets excited--
JOHN No no...
JOHN I just wanted you to know I'm back.
JOHN The puppy whimpers and he goes over to him, reaches into the box and pets him...
JOHN (CONT'D) Buddy, you really gotta chill, okay?
JOHN (CONT'D) Yeah, I know, good to see you, too.
JOHN (CONT'D) But I'm just inside the house, I'll see you in the morning.
JOHN (CONT'D) Big day tomorrow.
JOHN (CONT'D) Get some sleep.
John gulps orange juice from the bottle.
Leaves a quarter- inch, puts it back in the fridge.
And now we hear BARKING from the Garage.
Water running.
John swallows some preventative aspirin, picks some nachos off his shirt.
He turns off the water.
And we hear WAILING and KEENING coming from the garage.
John has his head buried under the pillows AS THE WAILING AND KEENING GO ON.
AND ON.
AND ON.
Finally, John can't take it anymore.
He sits up, pulls earplugs out of his ears.
As the light comes on and Marley's head appears over the top of the box.
John sighs, comes over and scoops him up...
John gets Marley settled in the box, now by the side of the bed.
JOHN Just this one time.
JOHN John climbs into bed, shuts off the light.
JOHN Marley whimpers and John rolls onto his stomach, reaches into the box and strokes his back, the puppy lays down, still whimpers...
JOHN (CONT'D) Oh, come on...
Hey.
Remember this?
One love, one heart...
Let's get together and feel alright...
John nods off, one arm hanging over the side of the bed into the box, his hand resting on Marley's back as the puppy now snoozes peacefully and we then...
Tail rising in the b.g., wagging.
As John opens his eyes to see Marley snuggled up against his face.
Marley's eyes looking into his.
John reaches over the puppy and shuts off the alarm.
JOHN She comes home today.
JOHN Hung over, he sits up, looks around the messy room, half due to John's bachelor housekeeping habits, half due to Marley.
JOHN Not only has everything has been chewed, but some time during the night Marley discovered how much fun toilet paper is.
JOHN (CONT'D) We should probably clean up.
John vacuums, struggles to empty the bag, puts a broken vase in the trash, does the dishes, etc.
Marley follows him, tail wreaking havoc, knocking over everything that isn't nailed down.
John picks up the HUGE CHEW TOY he'd just bought and examines it as Marley runs into the bathroom...
JOHN Huh.
JOHN It's already completely gnawed up.
JOHN John looks at Marley who emerges dragging a roll of toilet paper, rams right into the screen door, bounces back.
JOHN (CONT'D) Marley, it's a screen, you're not gonna
Meanwhile, Marley backs up a few steps, gets a head of steam, then rams into it again, this time goes right through it.
JOHN (CONT'D) --there.
John gets drenched as he gives Marley a bath.
John drags Marley into the garage.
JOHN I'll be back in an hour.
JOHN Be good.
A bit of THUNDER as John comes out with a bag of groceries and a bunch of flowers.
He gets to the car just as the rain hits.
As John and Jenny kiss outside the terminal.
She holds a stuffed "Pluto."
JENNY How's my puppy?
JOHN I'm okay.
JOHN A little tired, but
She nudges him.
He gives her another kiss.
JOHN (CONT'D) He's waiting for you.
John and Jenny get out of the car.
We hear WHIMPERING in the garage.
JENNY Marley!
JENNY She takes off for the side door of the garage.
They open the door and freeze.
JENNY Oh my God.
JENNY It's a mess.
JENNY It's almost incredible that it's all due to a single puppy.
JENNY The box is in shreds; so are the blankets.
JENNY A puddle of urine on the floor.
JENNY A large piece of dry wall has been chewed off near the big garage door.
JENNY The garbage cans are overturned.
JENNY Marley is whimpering in the corner.
JOHN Wow.
JOHN Okay, this is not how I left it.
JENNY How long has he been in here?
3a??/06/07 30.
JOHN An hour, at the most.
JOHN Jeez...
JOHN he Alg drywall.
JOHN That's just not right.
JENNY Look.
JENNY He's shaking-- Another bit of THUNDER and the puppy whimpers louder.
JENNY (CONT'D) Does thunder scare you, Mister?
JENNY (CONT'D) Hm?
JENNY (CONT'D) He licks her face, snuggles into her.
JENNY (CONT'D) She gives him the Pluto stuffed animal.
JENNY (CONT'D) She hugs him...
JENNY (CONT'D) Look at us.
JENNY (CONT'D) She looks up at John and smiles.
JENNY (CONT'D) He returns the smile.
JENNY (CONT'D) Mission accomplished.
As Marley bursts out of the back bedroom with one of Jenny's bras in his mouth.
JENNY Marley, no!
JENNY Jenny chases him into the kitchen, past John who holds up the newspaper...
JOHN He gave me an extra paragraph...
JOHN Marley bursts through the back screen door...
A seemingly continuous shot, except that it's now A SIX MONTH OLD MARLEY who comes through the screen into the backyard now clutching a set of curtains in his mouth, still attached to the rod, and it's now JOHN who stumbles through the broken wire mesh to chase after him...
JOHN Marley, no!
JOHN John chases him across the backyard.
JOHN Marley goes under the fence and John starts to go over into...
And now it's a NINE MONTH OLD MARLEY who comes up from under the fence clutching a THANKSGIVING TURKEY in his mouth.
And now it's Jenny AND John who go over the fence chasing him...
JOHN Marley, no!
JOHN They wave to the NEIGHBOR standing on his patio watching.
JOHN (CONT'D) Hi, Tom-- Sorry...
JENNY Happy Thanksgiving...
JENNY Marley goes through a hedge and out onto...
Where Marley emerges into FRAME a FULL GROWN DOG, rapidly pulling Jenny by the leash along the intercoastal waterway.
We track with him until a WOMAN WALKING A POODLE IS NOW IN FRAME and Marley gets the two women entangled as he starts humping the smaller dog...
JENNY Marley, no!
John sits across from Arnie.
He looks thrown:
JOHN I don't understand, why me?
ARNIE I'm in a bind, John.
JOHN But I'm a reporter, not a columnist.
ARNIE It's a step up.
JOHN Yeah, but it's a step away from what I wanna do.
ARNIE It's also better pay, you set your own hours, pick your own topics...
ARNIE (CONT'D) and it's only temporary, just until I find someone permanent.
JOHN What happened to Jerry?
ARNIE You may have noticed that in every other column, he went on about The Pie Palace?
JOHN I really haven't read his--
ARNIE Turns out he's been getting free meals in exchange for mentioning the joint.
ARNIE It's also why he became such a fat ass.
ARNIE John nods.
ARNIE Oh.
ARNIE (CONT'D) Anyway, it's twice a week.
ARNIE (CONT'D) And like I said, it's only until I can find someone else to replace him.
ARNIE (CONT'D) Then you're back on, uh...
ARNIE (CONT'D) whatever beat you were on.
John pulls up, gets out of the car.
His neighbors, The year-old GIRL -- short blue hair, pierced eyebrow -- and her MOM -- in a nurses uniform -- unload groceries from the car.
GIRL Your dog's funny.
Uh, thanks.
GIRL He tried to eat one of our tires.
JOHN Yeah, well, dogs need rubber.
JOHN Little known fact, helps the digestive tract...
GIRL Right.
GIRL Along with the occasional black Converse high top which I'd still love to get back by the way.
JOHN I'll do what I can.
GIRL 'Preciate that.
John sits at the table scribbling on a legal pad.
He tears off the sheet and crumples it up, throws it across the room.
Marley bounds into the room, Jenny behind him, sweating.
JENNY I think he dislocated my shoulder.
JENNY He doesn't heel-- hell, he doesn't even walk, he sprints, and I had to pull him off three dogs...
JOHN Poodle?
JENNY Yeah, among others.
JENNY There was a Yorkie, a Dalmatian and a bichon frise that may never be right again.
JENNY What're you doing?
JOHN Arnie gave me a column.
JENNY You're kidding?
JENNY Congratulations!
JOHN Oh, yeah, it's a big honor.
JOHN I get to write about zoning laws and yard sales.
JENNY I bet you make something out of it.
JOHN It's only temporary until he finds someone else.
JOHN I'm just trying to get something down for Tuesday.
JOHN She gives him a kiss, starts out of the room
JENNY You'll think of something.
JENNY And John, I'm serious abut Marley.
JENNY He wreaks havoc everywhere he goes.
JENNY We gotta do something...
MS.
KORNBLUT, weathered and stern, is studying John.
Behind John, eight puppies and their owners are chatting before the class begins.
MS. KORNBLUT Incorrigible?
MS. KORNBLUT I don't believe in that.
MS. KORNBLUT All dogs want to learn.
MS. KORNBLUT But they can't when their owners are weak-willed.
JOHN I'm very strong-willed.
MS. KORNBLUT And where is your animal?
JOHN He's over there.
JOHN With my wife.
JOHN He was a little excited.
JOHN He usually needs a little time to calm down.
JOHN Ms. Kornblut looks at Jenny as she struggles up with Marley.
MS. KORNBLUT I see.
MS. KORNBLUT He calls the shots.
MS. KORNBLUT Which of you will be the trainer?
JENNY we thought we both would, since we want him to listen to both of us at home -
MS. KORNBLUT A dog can only answer to one master.
MS. KORNBLUT Which one of you has the most natural authority in your own relationship?
I'll watch.
MS. KORNBLUT I thought so.
MS. KORNBLUT We begin.
As Ms. Kornblut gestures, demonstrates the command:
MS. KORNBLUT Sit!
The students order their dogs to sit, and most of them do.
The ones that don't require only a little effort to get the idea.
Whereas: Jenny orders Marley to sit; instead Marley jumps up on her and puts his paws on her shoulders.
She presses his butt to the ground, and he rolls over for a belly rub.
She tries to tug him into place and he grabs the leash in his teeth, shaking it playfully.
MS. KORNBLUT (CONT'D) That, class, is an example of a dog that has been foolishly allowed to believe he is the alpha male of his pack.
MS. KORNBLUT (CONT'D) And therefore he cannot be a happy animal.
JOHN Yeah, he looks really bummed.
JOHN Kornblut hears him, death stares John.
MS. KORNBLUT You.
MS. KORNBLUT Joker.
MS. KORNBLUT Rotate in.
MS. KORNBLUT John looks at Jenny who shrugs, holds up the leash for him to take.
As Ms. Kornblut demonstrates on her wrist.
MS. KORNBLUT The choke chain.
MS. KORNBLUT When your animal walks properly by your side, there'll be slack.
MS. KORNBLUT If he pulls, it tightens around his neck like a noose and loosens as soon as he stops pulling.
JOHN Does it hurt them?
MS. KORNBLUT Well, it's not called a hug chain.
MS. KORNBLUT But they learn to like it.
MS. KORNBLUT Go on, collar your dogs.
MS. KORNBLUT Everyone else quickly, easily gets the choke chain around
their dogs' necks.
Of course.
Meanwhile: John kneels down and struggles to put it.
around Marley's neck.
Marley, liking its shiny jingling, tries to eat it.
Much tussling, and John finally gets it around Marley's neck - but Marley still manages to grab it in his teeth.
JOHN He likes it.
MS. KORNBLUT That's because he's eating it...
MS. KORNBLUT Get it out of his mouth.
MS. KORNBLUT Class?
MS. KORNBLUT Give your dogs the sit command.
MS. KORNBLUT All the dogs sit; John forces Marley's butt down.
MS. KORNBLUT (CONT'D) The leash is held in two places.
MS. KORNBLUT (CONT'D) Loop around your right hand, left hand at waist level.
MS. KORNBLUT (CONT'D) Dog always on your left, of course.
JOHN That means us, pal.
JOHN He rearranges Marley so he's on John's left.
MS. KORNBLUT Now, when you give the heel command, step off with your left foot - I don't want to see any right foot first steppers - and walk.
MS. KORNBLUT If your dog gets ahead, administer a correction by forcefully bring your left hand down and towards the right, and he'll respond.
MS. KORNBLUT Shall we?
MS. KORNBLUT One, two, three - now!
MS. KORNBLUT Just as the dogs and owners prepare to step off, Marley lurches ahead of the pack...
JOHN Marley, heel!
JOHN Marley takes off like a fighter jet, dragging John behind.
MS. KORNBLUT Correct him!
MS. KORNBLUT John gives a mighty yank on the leash.
MS. KORNBLUT Marley coughs, hesitates.
MS. KORNBLUT John loosens the leash - and Marley explodes forward again.
MS. KORNBLUT John yanks, Marley stops, John releases, Marley explodes forward.
KORNBLUT (CONT'D) Rein in that dog!
KORNBLUT (CONT'D) All right, everyone, line up again.
KORNBLUT (CONT'D) Demonstration.
KORNBLUT (CONT'D) Mr.
KORNBLUT (CONT'D) Grogan?
KORNBLUT (CONT'D) Pay attention.
KORNBLUT (CONT'D) She takes the leash from John and efficiently guides him into line with the other dogs.
MS. KORNBLUT (CONT'D) It's a simple question of confidence in one's own authority.
MS. KORNBLUT (CONT'D) Shall I demonstrate a simple walk?
JOHN Be my guest.
MS. KORNBLUT Class?
MS. KORNBLUT Even an unruly dog wants to obey his leader.
MS. KORNBLUT Marley?
MS. KORNBLUT Heel.
MS. KORNBLUT And she steps off confidently - but Marley is a bit more confident than she is.
MS. KORNBLUT He lunges, she pulls, he falls back on his hind legs, then barrels up and lurches forward.
MS. KORNBLUT Ms. Kornblut half-stumbles, half rockets across the park.
MS. KORNBLUT She manages to turn Marley around, and the whole process begins again as they make their way back to the line.
MS. KORNBLUT Her face is flushed with embarrassment, anger, and exertion, but Marley, jowls frothing, is having a ball.
MS. KORNBLUT It's like a walking tug-of-war.
MS. KORNBLUT With difficulty, Ms. Kornblut manages to return Marley to John, but not before, as a coup-de-grace, he starts humping her leg enthusiastically.
MS. KORNBLUT She struggles, he knocks her down, and then he buries his face in her crotch and humps her knee.
MS. KORNBLUT John and Jenny rush over.
MS. KORNBLUT John restrains Marley; Jenny helps up Mrs. Kornblut.
MS. KORNBLUT She's livid.
MS. KORNBLUT (CONT'D) That's it!
MS. KORNBLUT (CONT'D) He's out!
JOHN He usually just does this with poodles.
JOHN Maybe it's the hair.
MS. KORNBLUT He's a bad influence on the others.
MS. KORNBLUT Leg-humping is a virus.
MS. KORNBLUT Once it takes hold in a group - he has to go!
As they follow Marley back into the house.
JOHN Well, that was fun.
JOHN Congratulations, Marley.
JOHN You flunked obedience school.
JENNY You know, John, there is something else we can do--
JOHN No, no, I'm not doing that to him.
JENNY It's painless.
JENNY And he'll be a lot more comfortable.
JENNY It'll calm him down.
JOHN Yeah, you know why he'll be calmer?
JOHN Because he'll have nothing to look forward to.
JENNY What're you talking about?
JENNY There are plenty of other things that'll make him
JOHN That's where you're wrong.
JOHN Trust me, Jen: I know.
JOHN I'm a guy.
JOHN And yeah, lots of things make us happy, but the only thing we really look forward to is sex.
JOHN Runner up: the possibility of sex.
JENNY Oh, Please.
JENNY Every book says he'll live
JOHN It'll just feel longer.
JENNY John, he's out of control.
JENNY It's the right thing to do.
JENNY John sighs, looks at Marley who's now humping the stuffed "goofy" that Jenny gave him as a puppy.
Jenny at the wheel.
John in the passenger seat.
Marley in the back, his front paws balanced on the center console.
JOHN It won't be so bad, buddy.
JOHN You'll see.
JOHN Sex is overrated.
JOHN Marley looks-at him.
JOHN (CONT'D) Okay, I'm lying, and I think you know that...
JOHN (CONT'D) so maybe the best thing is to just not talk about it.
JOHN (CONT'D) Jenny cuts him a look.
JOHN (CONT'D) He lowers his voice.
JOHN (CONT'D) Poor son-of-a-bitch.
JOHN (CONT'D) A guilty John cracks the window just a bit and Marley begins listing to starboard, leaning against John to catch a whiff of the outdoor smells.
JOHN (CONT'D) Marley crawls onto John's lap...
JOHN (CONT'D) Oh, okay, you wanna sit up here...
JOHN (CONT'D) Marley now jams his nose into the small opening, snorting to catch the fresh air
JOHN (CONT'D) Least I can do.
JOHN (CONT'D) John lowers the window and Marley gets his whole snout out.
JOHN (CONT'D) Here you go...
JOHN (CONT'D) John lowers the window again and now Marley sticks his whole head out, ears flapping behind him, tongue hanging out like he's drunk.
JOHN (CONT'D) He's so happy.
JOHN (CONT'D) He has no idea what's about to happen to him.
JOHN (CONT'D) Jenny looks over as Marley hooks his paws over the half open window so that his neck and upper shoulders now hang out of the car.
JENNY He's making me nervous.
JOHN He's fine.
JOHN He just wants a little
Suddenly Marley slides his front legs out the window until his front armpits are resting on the glass.
JENNY John, grab him!
JENNY Before John can do anything, Marley is off his lap and scrambling out the window of the moving car.
JOHN He's onto our evil plan, and he's making a break for it!
JOHN But now his butt is up in the air, his hind legs clawing for a foothold...
As Jenny slows down in heavy traffic, John lunges out the window after Marley, grabs the end of his tail with one hand so that Marley dangles upside down, outside the car, by his tail...
He trots along the pavement with his front paws...
Jenny gets the car stopped, HORNS HONKING BEHIND THEM.
JOHN Uh, little help here...
JOHN John's stuck.
JOHN He can't pull the dog back in the window and he can't open the door.
JOHN He can't let go as angry drivers behind them are now starting to swerve around them.
JOHN John hangs on for dear life...
JENNY I got him!
As Jenny puts on the flashers and gets out of the car, runs around to the passenger side...
a group of cars drive slowly by in the other direction, all watching and laughing...
What are you looking at?!
He's losing his balls today!
Cut the guy some slack!
John sits at his desk, tries to write a column.
Sebastian, in a flak jacket, pauses at his desk...
SEBASTIAN Strip mall get approved?
JOHN Riveting planning commission vote.
JOHN Knuckle-biter.
JOHN 8 to 1.
SEBASTIAN You up for a beer?
JOHN Can't, I gotta finish the column.
JOHN Maybe tomorrow?
SEBASTIAN Can't, I'll be in L.A. Part of that drug piece I'm doing--
JOHN Right.
JOHN Another time then.
JOHN John watches him move off, a secretary giving Sebastian a big smile as he passes.
JOHN John sits there another moment, looks at his desk.
JOHN A photo of him and Jenny.
JOHN One of Marley with a flip flop in his mouth.
JOHN John chuckles to himself, then deletes the column, starts typing a new one.
John sits anxiously across from Arnie who sits at his desk reading.
The editor's expression is grim as he looks up at John.
JOHN I'm really sorry, I'll go back and do the zoning piece--
ARNIE The hell you sorry for?
ARNIE It's hilarious.
ARNIE John sits back down, looks at Arnie.
ARNIE See, the thing is, Arnie's face doesn't say "hilarious," but...
Shooting Draft 42.
ARNIE (CONT'D) I loved it.
ARNIE (CONT'D) Getting kicked out of obedience school, the humping, the "Great Escape," all of it.
ARNIE (CONT'D) Hysterical.
ARNIE (CONT'D) Again, Arnie's face remains dead serious as he passes the paper back to John.
ARNIE (CONT'D) Run it.
ARNIE (CONT'D) As is.
JOHN Thank you, sir.
JOHN John starts out of the office.
ARNIE Hey, Gorgan...
Tell him not to feel bad.
Sooner or later, we all lose our balls.
JOHN I'll be sure to pass that on.
Live music, a sexy vibe.
John and Jenny sit outside in the hot Florida night.
Dinner over, John raises his glass...
JOHN To two years.
JENNY That was fast.
JOHN Good, though, right?
JENNY Really good.
JENNY He lifts out of his chair and kisses her, a long one.
JOHN So.
JOHN What's next?
JENNY I was thinking desert.
JOHN No, I mean on your list.
JENNY My list?
JOHN ed, Remember, when we first got marri you had this whole checklist, with like the game plan.
JENNY Right...
JOHN So what came next?
JENNY Let's see...
JENNY a new car maybe?
JOHN afterthat?
JOHN We can do that.
JOHN What was
You sure you wanna know?
JOHN Yeah.
JENNY well, it was between a new roof and a baby.
JENNY He studies her for a long moment, then...
JOHN I can probably live with a few leaks.
JENNY Really?
JENNY Because a leak can turn into something bigger...
JENNY and that can be a big responsibility.
JOHN I know.
JENNY I was just thinking that we might want everything fixed before we went to the next step.
JOHN Well, we've already fixed Marley.
JOHN Literally.
Marley & He Shooting Draft 65
JENNY You're serious about this?
JOHN I think so.
JOHN JENNY t an And you know we're not talking abou actual roof here.
JOHN Yeah, I got that.
JOHN She looks back at him, finally nods.
JOHN They are.
JOHN Then..
JENNY Okay.
JENNY Maybe, instead of tying to have a baby, we should stop trying to not have one.
JOHN If I'm following you correctly -- and I think I am -- this is the part where we go home and get it on, right?
JENNY Bingo.
66 INT. BEDROOM - DAY him.
As Jenny pushes John back onto the bed, starts kissing Things getting hot and heavy quickly.
As they kiss...
JENNY Honey?
JOHN Yeah...
JENNY Did you eat some kibble?
JOHN What?
JOHN And now they part and we see MARLEY'S HUGE FACE RESTING ON THE SIDE OF THE BED, watching, panting up a storm.
JOHN (CONT'D) Marley-- get out of here!
it's fine, he's a dog, he doesn't what he's looking at.
Oh, he knows, and trust me, he the hell out of me right now.
Go on, Marley!
Get out!
But Marley jumps up on the bed, tries to climb on both of
JENNY Marley!
JENNY And now they both start laughing as the dog tries to lick their faces...
Silence.
Arnie reads John's column, his face dead serious.
ARNIE This is even funnier than the last one.
JOHN Thank you, sir.
ARNIE You're good, Gorgan.
ARNIE And not just the dog stuff.
ARNIE The piece on the women of Boca last week.
ARNIE What'd you call them?
JOHN Boccahontis.
ARNIE Hilarious.
ARNIE John nods, starts for the door...
ARNIE (CONT'D) Is it true what you wrote?
ARNIE (CONT'D) You and the wife are trying to have a kid?
JOHN Well, we're not really trying.
ARNIE How's that work?
JOHN Excuse me?
ARNIE Are you having sex?
JOHN Yes.
ARNIE ant?
ARNIE With the intention of getting pregn
JOHN i guess.
ARNIE Congratulations.
ARNIE You're trying.
ARNIE John just stands there.
ARNIE Arnie looks back at him.
ARNIE (CONT'D) I assume you've thought this through?
JOHN Yeah, I mean...
.yeah.
68 INT. SUN-SENTINAL OFFICE - DAY desk.
John walks out of the office, pensive, sits down at his His PHONE RINGS.
JOHN Grogan.
Jenny on the phone, looking at a dry erase calendar.
JENNY I just thought I'd let you know that I'm ovulating.
JOHN Oh.
JENNY Just in case you wanted to come home.
JENNY Like right now.
In the f.g., stands a harried thirty-something FATHER with a screaming INFANT in a Bjorn.
John stands just behind the father who bounces in place trying unsuccessfully to soothe the baby.
GIRL'S VOICE Daddy!
GIRL'S VOICE And now, another KID, 4-year-old girl, jumps up in and out of frame...
GIRL I wanna push the button!
FATHER Daddy can't lift you right now--
GIRL You said I could push the button!
FATHER Alright, okay, I'll just-- He tries to pick her up without leaning over...
GIRL Ow!
GIRL You're hurting me!
FATHER Okay, you know what?
FATHER Never mind, no button!
FATHER A very uncomfortable John now steps forward...
JOHN You want me to give her a hand?
FATHER Oh-- would you mind?
FATHER John lifts the girl up to the panel.
FATHER She runs her hands, from top to button, down the panel, pressing every single button.
Sarah!
Goddammit--
And now the little girl starts bawling in concert with the baby, while a trapped John backs up into the corner.
John gets out of the car.
The young Girl next door gives him a wave as she starts down the sidewalk with her boyfriend.
JOHN Hi.
GIRL Hi.
GIRL John watches the young couple go, arms around each other.
John enters and is greeted as usual by Marley who jumps on him.
JOHN Hey, boy.
Jenny?
JENNY Out in a sec!
JENNY John stands there, Marley looking at him.
JOHN So.
JOHN This is us not trying.
JOHN The bathroom door opens and Jenny walks out in a tiny, silky two-piece thing...
JENNY Hey, Sailor.
JENNY She walks into the bedroom.
JENNY John looks back at Marley as he follows her into the bedroom.
JOHN Catch you later, buddy.
JOHN And closes the door on the dog.
John and Sebastian sit at the bar.
SEBASTIAN So the puppy wasn't enough?
JOHN Well, technically, we're not trying.
JOHN But you know Jenny.
SEBASTIAN But things are good right now, just as they are, right?
JOHN Yeah, things are really good.
SEBASTIAN So why change it up with a kid?
SEBASTIAN I mean, have you already forgotten my little cautionary tale...
JOHN The bomb, right?
SEBASTIAN Yes.
SEBASTIAN The bomb.
SEBASTIAN And just so we're clear, the countdown sequence has been reactivated.
SEBASTIAN By you.
JOHN Well, it's been a few months and nothing's happened.
JOHN Which actually makes me wonder if--
BARTENDER Mr. Grogan?
BARTENDER The BARTENDER sets a PHONE down in front of John.
Phone call.
I loved that thing you did on your dog watching you and your wife have sex?
Really funny stuff...
Thanks...
BARTENDER Seriously, man, your stuff is classic.
JOHN Well, it's just temporary, but thanks.
JOHN John cuts a look at Sebastian, picks up the phone.
JOHN (CONT'D) Hello.
I just wanted to let you know that there's a naked blonde in your bed.
JOHN Oh.
JOHN Why don't you two get started and I'll be there as soon as I can.
JENNY Very funny.
JENNY Can you come home?
JENNY I'll make it worth your while.
JOHN Oh.
JOHN Alright then.
JOHN I'll see what I can do.
JOHN He hangs up.
JOHN Looks at Sebastian.
JOHN (CONT'D) Uh, I'm sorry, man, but I gotta jam.
JOHN (CONT'D) I forgot, I had this thing, I gotta deal
SEBASTIAN She's calling you home, isn't she?
JOHN Yeah.
JOHN See you later.
JOHN John starts out of the bar.
JOHN Sebastian calls after him.
SEBASTIAN Tick tick tick!
Romantic Music on the stereo.
John comes in, wearily, absently pets Marley.
He goes into the bedroom.
The bathroom door is open.
John sits down on the bed.
JOHN You know, this baby thing.
JOHN I been thinking maybe we should take a break.
JOHN You know?
JOHN Obviously, it's not happening.
JOHN Maybe that's nature's way of saying it's not good timing.
JOHN No sound from Jenny.
JOHN He struggles on.
JOHN (CONT'D) Maybe this is a sign that we're not ready for this.
JOHN (CONT'D) I mean, have we really thought this through?
JOHN (CONT'D) Because--
He looks up to see Jenny at the bathroom door.
From her back she brings out a home pregnancy test strip.
JENNY I'm pregnant.
JOHN Great.
JOHN Wow, that's...
JOHN great.
JENNY But you just said
JOHN Yeah, no, I mean-- okay, this is definitely awkward now, but...
JENNY You wanna start over?
JOHN Can I?
JENNY By all means.
JOHN Thank you.
JOHN Okay, well...
JOHN I gotta be honest, I'm a little panicked.
JENNY Are you panicking because I'm pregnant...
JENNY or because you're afraid I'm going to hit you?
JOHN Both.
JOHN It's a twofer thing.
JENNY Are you scared?
JOHN No.
JOHN No.
JOHN Not at all.
JOHN Yeah, yeah I'm pretty scared.
JENNY Me, too.
JENNY But we're gonna be okay.
Look at me...
He looks at her.
She smiles at him.
JENNY (CONT'D) We're gonna be okay.
I believe you.
He looks at her stomach, kisses her there...
As John hands Arnie his latest column...
JOHN That's probably the last one about Marley for a while.
JOHN But in about nine months, I'm gonna have a new subject, might be just as fun.
JOHN Jenny's pregnant.
I'm very happy for you.
Have you bought her a present?
JOHN What?
ARNIE A gift, John.
ARNIE She's carrying a child.
ARNIE Your child.
ARNIE Don't you think that's worth something?
JOHN Uhhh...
ARNIE You don't wanna make the mistake I did.
ARNIE Listen to me.
ARNIE There's gonna come a time, she's fat, she's nauseous, her ankles are swollen, and she's gonna look at you, and this is what that look will mean: "You bastard.
ARNIE You did this to me.
ARNIE You dick, you ruined me."
ARNIE But then...
Shooting Draft 53.
ARNIE (CONT'D) she's gonna remember that little ring, bracelet, anklet, whatever, that you bought her, and she's gonna feel better.
ARNIE (CONT'D) Understand?
JOHN Yeah.
JOHN Can I just--
ARNIE Go ahead.
ARNIE There's a jeweler on the corner.
ARNIE Mention my name.
Lit with candles.
Jenny and John on the couch.
She removes a beautiful gold necklace from a box and holds it up...
JENNY Oh, John, it's beautiful...
JENNY She sets it down on the coffee table, then moves close to him.
JENNY (CONT'D) Thank you...
JENNY (CONT'D) She kisses him.
JOHN I was just thinking about you when I walked by the store and saw it in the window...
JENNY That is so sweet.
JOHN Put it on...
JOHN She turns back to the coffee table and looks around...
JENNY Where'd it go?
JENNY It was right here.
JOHN You just put it down.
JOHN It can't have
And then he stops.
Looks off.
So does Jenny...
JENNY Oh God...
JENNY Marley stands a few feet away, looking strangely gleeful.
JENNY A glint of Gold in the moonlight dangles from his mouth.
JENNY They both get up, start to move towards him...
JENNY (CONT'D) Hey, boy.
JENNY (CONT'D) Come here.
JENNY (CONT'D) Look what I got for you.
JOHN We don't want any trouble...
JENNY Yeah, here's a little something-- (imaginary) treat.
JENNY Marley She reaches into her pocket for an moves looks at her.
JENNY Is this a trick?
JENNY He considers.
JENNY Then he closer.
JENNY John tiptoes up behind him, ever so slowly.
JENNY (CONT'D) I just want to give you a treat and a big kiss.
JENNY (CONT'D) That's a boy...
JENNY (CONT'D) Inch by inch, Marley approaches her.
JENNY (CONT'D) But then, behind Marley, John knocks against a table.
JENNY (CONT'D) Marley freezes.
JOHN He made me!
JOHN Go!
JOHN Jenny lurches for Marley, going for his collar, and John leaps at him from behind.
JOHN Marley skitters away.
JOHN Ah, a game!
JOHN He wags his tail, prances, sticks his rear in the air and his puts his head to the ground.
JOHN John feints, tries to maneuver Marley back into Jenny.
JOHN Jenny finally grabs him from behind.
JOHN John pries open his mouth.
JOHN Nothing.
JOHN He reaches inside, looks up at Jenny.
JOHN (CONT'D) Uh-oh.
John grimaces in the morning sun as he watches Marley poop.
He takes a hose and squirts at the deposit until it runs into the lawn.
Nothing.
JENNY Dr. Jay's sending over a laxative.
JOHN Yay.
John hoses through Marley's huge orange iridescent poops.
JOHN Man, you gotta lay off the mangoes.
You know, years ago, when I pictured my life, somehow standing in my backyard hosing down dog crap in search of my bride's swallowed and recycled ass- kissing gift just didn't spring to mind.
Aha!
Jackpot!
Carefully, Jenny lifts the shiny necklace out of a glass filled with bleach.
JENNY I think it's shinier than before.
JENNY Amazing.
JOHN Yeah.
JOHN He did us a favor.
JOHN And I only threw up eight times.
JENNY My hero.
The NURSE arranges the gown on Jenny.
NURSE How's that crazy dog of yours?
NURSE I'm a big fan.
JOHN Thank you.
NURSE The heartbeat'll be very fast, like a little train.
NURSE That's normal.
Shooting Draft 56.
JOHN Is it too soon to tell the sex?
JOHN Not that I care.
JOHN He can be any sex he wants.
JOHN Male, female, we don't care.
JOHN Unambiguous genitalia, if we had our druthers, but whatever...
NURSE Shhhhh...
NURSE hang on...
NURSE She listens for a moment with a little microphone hooked up to a speaker.
NURSE Nothing.
NURSE (CONT'D) Sometimes you,can't hear it, depending on how the baby is lying.- You're ten weeks, right?
JENNY Next Monday, yes.
NURSE Might be a little early for that.
NURSE Let's go right to the sonogram.
NURSE Did you bring your blank tape?
JOHN Ready to roll.
NURSE Let's get a good picture first.
NURSE It'll be on the monitor there.
NURSE The Nurse begins running the instrument around Jenny's stomach.
NURSE John and Jenny peer at the computer screen.
Hmmm.
This one doesn't seem to be picking up anything.
Excuse me, I'll be just a minute...
She leaves.
Jenny and John smile at each other, but inside each of them, a small pinpoint of fear starts to expand.
We wait for a few moments.
A pressured silence.
And then...
smiles down at DR.
SHERMAN comes in, followed by the nurse, Jenny.
DR. SHERMAN Hi, guys.
DR. SHERMAN Let's have a look at your baby, shall we?
Shooting Draft 57.
SHERMAN (CONT'D) All right, there we go.
SHERMAN (CONT'D) Good.
SHERMAN (CONT'D) Now, look over there.
SHERMAN (CONT'D) Much better resolution, right?
SHERMAN (CONT'D) Jenny and John, holding hands, look at the computer screen.
SHERMAN (CONT'D) They see a sac, which, with a click of the mouse, Dr. Sherman expands and expands.
SHERMAN (CONT'D) But it's empty.
SHERMAN (CONT'D) Jenny tries to smile.
JENNY Is there anything in there?
DR. SHERMAN Not what you'd expect to see at ten weeks.
JENNY Not quite ten weeks.
Dr. Sherman looks at them directly.
Kindly:
DR. SHERMAN Jenny, I'm sorry, but there's no heartbeat.
DR. SHERMAN John and Jenny are still, silent.
DR. SHERMAN (CONT'D) One in six pregnancies ends this way.
DR. SHERMAN (CONT'D) it just happens sometimes, that's all.
DR. SHERMAN (CONT'D) I'm very sorry.
DR. SHERMAN (CONT'D) But you're young and healthy and in a couple of months, you can try again.
Why don't you come by my office on your way out and we can talk some more.
He exits.
John is still holding the blank videotape.
He tries to hide it from Jenny.
He leaves.
Jenny and John look at each other.
JENNY How could this happen?
JENNY What'd I do wrong?
JOHN You didn't do anything--
JENNY I must have.
JENNY Otherwise, how could I lose it?
JOHN Jenny, it's not something you have any control over.
JOHN It's like the doctor said, it just happens--
JENNY Not to me...
JENNY I did something wrong.
JENNY I know it...
JENNY I did something wrong.
JENNY I'm sorry, John...
JOHN Don't say that--
JENNY But I am-- I'm sorry--
JOHN I don't need sorry.
JOHN You didn't do anything!
JOHN She turns away and begins to cry.
JOHN John just sits there, staring at the videotape in his hands.
JOHN Outside in the hall, the door to another examining room opens and they hear a couple laughing, talking excitedly.
JOHN Jenny and John look away from each other, their pain made even worse.
John is driving Jenny home.
JOHN In a couple of months, we can try again.
JOHN Okay?
JOHN Jenny just looks out the window.
John helps Jenny through the kitchen door.
Marley follows them, circles them wildly, then stops, puzzled, as he looks at them.
Jenny goes into the living room; Marley follows her.
JOHN You want some tea?
Hey, you know what I was thinking?
We still have those tickets from your parents for the honeymoon in Ireland.
We can finally do that.
JOHN (CONT'D) Take some time off.
JOHN (CONT'D) It'll be fun, clear our heads, right?
Jenny?
No answer.
He goes into the living room and stops cold:
Jenny sits on the couch.
Marley stands at her feet, with his shoulders between her knees, his big head resting in her lap.
His tail hangs flat between his legs.
His eyes are turned up at her, and he whimpers softly.
Jenny strokes his head a few times and then, with no warning, buries her face in the thick fur of his neck and begins sobbing.
They stay like that for a moment, Marley statue- still, Jenny clutching him to her like an oversized doll.
John stands there, watching Marley take care of her.
No words, just being there.
A lesson here.
Her head down, Jenny raises one arm up towards John and John goes to the couch and wraps his arms around both of them.
We then...
Oh.
He's...
big.
With difficulty, John holds back Marley to protect DEBBY --- 19, glasses, bookish, the house sitter -- from his affection.
JOHN Yeah.
JOHN Close to a hundred pounds.
JOHN He just wants to say hi.
JOHN He won't hurt you.
JOHN Just stand still and be calm.
JOHN You're a dog person, right?
DEBBY well, actually -
JOHN - Ready?
DEBBY okay?
DEBBY John releases Marley who springs on Debby, knocking her back.
Shooting Draft 3106/07 60.
DEBBY (CONT'D) I'm okay!
DEBBY (CONT'D) I'm okay!
JOHN He's not supposed to do that.
JOHN You have to knee him.
JOHN Anyway, it won't happen the whole time.
JOHN Just maybe when you come home.
JOHN This is everything you need to know.
John and Jenny lug their suitcases across the front lawn to the car, Marley running around them.
Debby's glancing through the binder.
JENNY'S VOICE Debby.
JENNY'S VOICE Welcome to our home!
JENNY'S VOICE Marley is a spirited dog who loves interaction.
JENNY'S VOICE We've never left him before but we're sure he'll behave just as he does when we're at home.
JENNY'S VOICE They kiss him goodbye.
JENNY'S VOICE Get in the cab and go.
JENNY'S VOICE Debby runs to Marley, grabs his leash and struggles with all her might to hold on to Marley.
Coach.
But this is 1991, and the planes fly half-full.
John
reads about Ireland in the guide book.
Jenny sees a woma with a child.
She smiles.
No tears.
JENNY'S VOICE There are just a few things about Marley you need to know.
JENNY'S VOICE He eats three times a day.
JENNY'S VOICE If he looks starved, feed him again.
JENNY'S VOICE Of course all this food has to go somewhere.
Debby looks at the piles of orange poop everywhere.
JENNY'S VOICE Use the red shovel and the blue bucket.
JENNY'S VOICE Watch your step.
JENNY'S VOICE Don't worry about the color.
JENNY'S VOICE He likes mangoes.
Marley & He Shooting Draft 61.
John and Jenny enjoy the scenery.
Sheep in the road surround their car.
Jenny leans out, laughing, and takes a picture.
JENNY'S VOICE Marley's ears get a lot of wax buildup.
JENNY'S VOICE Once or twice while we're gone, please use cotton balls and the blue ear- cleaning stuff to clean them out.
JENNY'S VOICE Wear old clothes and try not to breathe.
Debby is throwing up in her mouth a little as she cleans Marley's ears.
Marley loves it.
JENNY'S VOICE Marley is an excellent watchdog.
JENNY'S VOICE And in this neighborhood, that's a good thing.
JENNY'S VOICE You can rest easy at night, knowing he's on the job.
Debby, ears plugged, shades over her eyes, weeps in frustration as Marley HOWLS at the moon.
John and Jenny stop at a bed-and-breakfast for the night.
It's raining softly.
JENNY'S VOICE Thunderstorms are his weak point.
JENNY'S VOICE Well, one of his weak points.
JENNY'S VOICE You can give him sedatives if you think a storm is arriving.
JENNY'S VOICE He doesn't like them, so push them down into his throat as far as they go.
Marley is tearing through the house, terrified.
chasing him with a bottle of tranquilizers.
An Irish widow, MRS.
BUTTERLY, leads them to their room.
Marley & He Shooting Draft 62.
JOHN'S VOICE We do not allow Marley to get up on any piece of furniture, chew on anything except his toys, drink out of the toilet - keep the lid closed and the brick on the lid -
Debby is showering - and then starts SCREAMING.
Marley has stuck his head through the shower curtain and is licking the water.
Debby splashes water at him to make him go away.
Marley, thinking she's playing, scrambles into the tub with her.
She grabs the curtain, and it pops off the curtain rings one by one as in ",Psycho."
JOHN'S VOICE - actually, you might want to keep the bathroom door closed in general.
Debby has run out of the bathroom, a towel hastily wrapped around her.
Marley chases her.
He leaps - and returns to earth with the towel in his mouth.
Debby SCREAMS.
Debby is standing on a coffee table, nude, swatting at an unseen Marley with a bunch of tall artificial flowers.
JOHN'S VOICE Other than that, enjoy him!
JOHN'S VOICE Thanks so much.
JOHN'S VOICE Love, Jenny and John.
Four walls, four different floral wallpapers.
Twin beds.
Above one, the Sacred Heart of Jesus.
Above the other, the Sacred Heart of Mary.
Crucifixes everywhere you look, and a HUGE framed picture of Pope John XXIII.
MRS. BUTTERLY And if you need anything during the night, I'm right next door.
MRS. BUTTERLY The blankets are wool.
MRS. BUTTERLY Good heat in them.
JENNY Oh, they're electric?
MRS. BUTTERLY No, not in this house.
MRS. BUTTERLY My brother died in a fire, God rest him.
In this room, actually.
It's been re- papered.
Good night.
God bless.
Jenny sits on the bed.
The CREAKING is terrible.
JENNY Look, I know we haven't had sex since...
JENNY you know.
JENNY But there's no way we're breaking the streak tonight.
JOHN No kidding.
JOHN 'Cause it's not just God watching.
JOHN God, his mother...
JOHN .and apparently his best friend.
They are in separate beds, staring at the crucifix.
JOHN It's July, but I think I can see my breath.
JENNY I can't feel my toes.
JENNY John gets out of his bed and into Jenny's.
JENNY Much SQUEAKING.
JENNY (CONT'D) My God.
JENNY (CONT'D) Shhh.
JOHN It's not the mattress.
JOHN It's the shrieks of over-sexed souls in hell.
JENNY You wanna join them?
JENNY He looks at her.
JOHN Are you sure, because we don't have to...
JENNY I can't help myself.
JENNY Knowing it hasn't happened in this house in 50 years is a turn-on.
JENNY They roll into each others' arms, the bed squeaking.
JOHN Maybe she's deaf...
The next morning.
John and Jenny, looking flushed and relaxed, and slightly abashed, come downstairs.
Mrs.
Butterly looks at them sourly.
So do the other guests.
They heard us.
JOHN No...
JOHN He jumps as Mrs. Butterly slams the teapot on the table.
MRS. BUTTERLY Tea?
MRS. BUTTERLY I'm off to Mass.
MRS. BUTTERLY Mrs. Butterly leaves.
MRS. BUTTERLY John and Jenny look at the other guests.
MRS. BUTTERLY They smile bravely.
JOHN Wow.
JOHN Any of you hear her bed squeaking last night?
JOHN I hope she hits confession before Mass, that's all I can say.
Another widow, another room, another collection of religious artifacts.
John smiles.
Jenny sits on the bed, smiles at the NOISE, starts taking off her shoes.
John ushers the Owner out of the room.
John and Jenny pull into the driveway.
They see Debby, the house sitter, on the front steps with her bag packed.
She's tired-looking, beat.
She reaches for a pair of crutches.
John gets out of his car, a smile on his face.
JOHN Hey, Debby.
JOHN So how was-- -Debby hurls the binder of instructions at him.
DEBBY There were eleven thunderstorms while you were away.
DEBBY Eleven!
DEBBY And you were right.
DEBBY He doesn't like thunderstorms!
JENNY Okay, yeah, wow.
JENNY Eleven, huh?
JENNY That is a lot.
DEBBY And those goddamned dog tranquilizers don't work!
JOHN Did you give him four at a time?
DEBBY I mean on humans!
DEBBY She hobbles to the car, tries to get in with her crutches.
DEBBY They frustrate her and she ends up beating the ground with them until she throws them down.
DEBBY She's losing it.
DEBBY (CONT'D) And just so you know, I am a dog person.
DEBBY (CONT'D) But that's not a dog!
DEBBY (CONT'D) That's evil with a dog face!
DEBBY (CONT'D) That's also humping your leg!
DEBBY (CONT'D) Lose my number!!
DEBBY (CONT'D) And she gets into her car and guns it, splintering the crutches as she peels out.
DEBBY (CONT'D) John and Jenny, watch her go, turn and look at the front door.
DEBBY (CONT'D) Marley's face in the little square window at the top, peeking out at them.
A THUNDERSTORM outside.
John sits at his desk, tries to work while Marley walks in circles.
John looks at him...
JOHN It's only thunder...
JOHN John goes back to work.
JOHN We hear more THUNDER, and Marley starts howling, knocks over a floor lamp...
JOHN John looks off towards the bedroom...
JOHN (CONT'D) Jenny?!
JOHN (CONT'D) Can you help me out here?
JOHN (CONT'D) I got twenty minutes to file this column!
JOHN (CONT'D) We follow John as he gets up from his desk, heads towards the back bedroom...
JOHN (CONT'D) Jenny?
JOHN (CONT'D) We follow him into the room, an anxious Marley close at his heels.
JOHN (CONT'D) She's not here, he turns around just as she steps out of the bathroom, smiling...
JENNY Luck of the Irish...
JENNY She holds up a pregnancy test with a clear BLUE line, her exuberant face lit up by a FLASH OF LIGHTNING.
JENNY John goes to hug her, as Marley HOWLS in the b.g., we then...
FADE OUT. SUPER: "Nine Months Later."
John and Jenny are asleep.
Marley goes through his nighttime
He chews through a sock.
He drinks out of the toilet.
He works on chewing through the plastic dog food tub.
Another night and he'll be in.
He chases a fly.
Finally he goes to his bed on the floor of the bedroom.
He settles himself down to sleep.
He yawns, he scratches, he closes his eyes.
He snores.
And then - He wakes up, suddenly alert.
He looks over at Jenny.
He gets up, sits by her side of the bed, and waits.
Suddenly Jenny sits up, rests a hand on her stomach.
She catches her breath, leans over to John.
JENNY (CONT'D) John.
JENNY (CONT'D) John, wake up.
JOHN What?
JENNY I think it's time.
Jenny has finished dressing.
Suddenly she yelps in pain, doubles over.
John takes her in his arms.
JOHN It's okay.
JENNY Ow!
JENNY Suddenly, A GROWL.
JENNY They turn to see Marley glaring at John.
JOHN It's okay.
JOHN I'm not hurting her.
JOHN Jenny MOANS again and now Marley's eyes narrow.
JOHN He takes a step towards John.
JOHN (CONT'D) Please don't scream, honey.
JOHN (CONT'D) He'll kill me.
JENNY You put the car seat in this weekend, right?
JENNY They won't let us take the baby home without the car seat installed.
JOHN Like I'd forget that.
Panicking, John is struggling to get the car seat he forgot out of the box.
He starts beating at the Styrofoam.
Marley barks excitedly.
John gets an idea, hands him one end of the box.
JOHN Come on, Marley.
JOHN Help me out here.
JOHN Do what you do best...
JOHN Unsure, Marley licks the box.
JOHN (CONT'D) No, don't lick it, eat it!
JOHN (CONT'D) Destroy it!
JOHN (CONT'D) You can chew through drywall, man!
JOHN (CONT'D) I know you can do this!
JOHN (CONT'D) Marley catches on.
JOHN (CONT'D) He starts shredding the box.
John hurls a suitcase and the partially-assembled, partially- destroyed car seat into the back seat.
He yells:
JOHN Car seat's in!
Jenny is tottering down the walk as John pulls out of the garage, gets her into the passenger seat.
JOHN Ready?
JENNY Yeah.
JENNY You?
JENNY Marley barks from the back seat.
JENNY They both turn and look at him.
JENNY What's he doing here?
John opens the front door, drags Marley in.
John gives him a
JOHN Okay.
JOHN Here...
JOHN Stay.
JOHN Be good.
JOHN Please, God.
JOHN No storms.
JOHN Stay.
The chew toy now almost completely gone.
Marley sleeps beside it as we hear A KEY IN THE LOCK and he gets to his feet, greets John as he comes through the door.
JOHN Hey, boy.
As John let's Marley out.
As John sets down a bowl of food, crouches down as Marley starts to eat.
Marley & Me Blue Revisions 3/07/07 69.
JOHN Here's the thing: in a couple of hours, we're gonna bring the baby home.
JOHN And you'd be doing me a really big favor if you didn't freak out.
JOHN I'm gonna try and do the same thing.
As the sun now streams in through the front windows down onto Marley, who is sound asleep.
We hear A CAR DOOR CLOSE and he raises his head...
A moment later, THE FRONT DOOR OPENS and John comes in and Marley greets him, jumps up on his chest.
JOHN Hey, boy...
JOHN let's go outside...
As Marley relieves himself, John yawning in the b.g.
As Jenny unpacks her suitcase.
Marley bounds into the room and greets her.
JENNY Hello, Marley...
JENNY She crouches down, gives him a kiss, rubs his back.
JENNY And that's when we hear a small, birdlike chirp and the dog freezes.
JENNY Where'd that come from?
JENNY We hear the coo again and this time Marley lifts one paw in the air like a bird dog, and points in the direction of the car seat that we now see sitting on the bed...
JOHN You know what I think would be a bummer?
JOHN If he ate the baby...
.Harley & Me Shooting Draft 70.
She moves to the car seat and turns it around so that now we see the baby for the first time.
She smiles at Marley...
JENNY This is Patrick, Marley.
JENNY Jenny unbuckles Patrick from the car seat and crouches down beside Marley and lets the dog sniff the baby's toes, then up his legs, finally his diaper which puts Marley into a Pampers stupor, the Holy Grail of aromas and Marley's eyes glaze...
JENNY (CONT'D) See, he's not gonna hurt him.
JOHN No, but I'm gonna have to put a lock on the diaper pail.
Garbage day, and the trash piled outside the Grogan house testifies to the change inside.
Empty cartons of diapers, the packaging from a crib, a stroller, the car seats, the Pack'n'Play...
Jenny tries to watch the baby, now crawling around on the floor and file her column over the phone at the same time.
JENNY I have the quote right here-- Patrick crawls over Marley, who's supremely patient as Patrick takes a fistful of his eye.
JENNY (CONT'D) Well, have legal call them again and get a release for it.
JENNY (CONT'D) They told me it was on the record-- Marley-- Patrick, that's his eye-- No, not you, Karla, just get the release.
JENNY (CONT'D) I'll call you back.
Be gentle, Patrick!
Jenny leans back in her chair, rubs her face.
Then...
Laundry.
John sits on a bench, Marley at his feet reading "What to Expect in the First Year."
He takes a breath, looks up, watches a COUPLE make out on a blanket.
The baby in his high chair.
Jenny sets a few cheerios on the tray.
Patrick picks them up and drops them, we follow them down...
To where Marley waits, eagerly vacuuming up the cereal.
It continues to RAIN CHEERIOS and we then BOOM BACK UP and see that Patrick is now eight months old, laughing as he throws the cereal onto the floor...
John stands there letting Marley out.
He looks back at the house, watches Jenny through the window as she sets Patrick down in his crib, shuts the light out.
They're both working at their desks.
Jenny looks up from her computer.
JENNY I need to go in tomorrow for a few hours, see my editor.
JENNY Think you can watch the baby for me?
JOHN Sure.
JOHN John looks around the room.
JOHN The place is a disaster area.
JOHN (CONT'D) Remember us?
JENNY You mean, those younger, skinnier better looking people?
JENNY Yeah, I think I remember them.
JENNY Vaguely.
JOHN Well, I miss them.
JOHN He turns back to his work.
JOHN She looks at him, sets her pad aside, comes up behind him, puts her arms around him.
JENNY They're still here.
JENNY He looks up at their reflection in the window, not so sure.
John and Jenny now asleep on opposite sides of the bed.
On the floor beside John, Marley lifts his head and GROWLS.
We then hear a piercing SCREAM coming from outside.
The dog is already out of the room.
John sits up, immediately starts to get out of bed...
JENNY Honey, don't go out there.
JOHN Stay here.
JOHN Call the police.
Marley's at the door growling as John, in his boxer shorts, grabs the dog by the choke chain and opens the door.
We hear another SCREAM coming from a couple houses down and Marley breaks through the screen, pulling John with him...
As other lights come on, NEIGHBORS start to come out onto the street.
John runs to where we see THE TEENAGE GIRL NEXT DOOR bent over, sobbing, in her driveway beside her car, driver's door still open.
John lets go of Marley and hurries to her.
GIRL He said not to scream or he'd stab me, but I screamed...
GIRL And John sees the blood on her shirt.
GIRL He takes hold of her.
JOHN Okay okay okay, I've got you...
Where's your mom?
GIRL At work...
JOHN Jenny'll call her...
Marley sniffs at the ground, growling more and more intensely.
We hear SHOUTING, "He went that way" as several neighbors take off running.
Marley lifts his head and he, too, bolts into the night---
JOHN (CONT'D) Marley!
JOHN (CONT'D) NO!
JOHN (CONT'D) But he's gone and John has to stay with the girl.
JOHN (CONT'D) We hear SIRENS as she slides down the car and sits down on the ground.
JOHN (CONT'D) John sits down beside her, holding onto her...
JOHN (CONT'D) All this time we've been living here, I never got your name.
GIRL Lisa.
JOHN Well, you're gonna be alright, Lisa, the police are on the way...
JOHN John looks off, wondering where Marley is...
A crime scene.
Jenny, clutching the baby, stands on the porch watching as an AMBULANCE pulls away.
John, now in shorts and a T-shirt, comes jogging up the walk.
JOHN I can't find him anywhere.
JENNY Maybe we should get in the car, drive around.
JOHN I'll get the keys...
JOHN John's coming into the house when a police cruiser pulls to the curb in front of the house.
JOHN A POLICEMAN gets out of the driver's side, then opens the back and leads Marley out.
JOHN He bounds up the walk to the two of them who greet him...
JENNY Marley!
JOHN Where were you?
OFFICER We found him outside the 76 station on Radford.
OFFICER He had the guy cornered in the men's room.
JENNY So you caught the guy?
jig caught the guy.
He also gnawed the barrel of my shotgun, and ate half my radio mic.
They look at Marley wagging his tail, panting.
Anyway, the neighbors all said he belonged here, but none of them wanted to drive him, so...
JOHN Thanks for bringing him home.
OFFICER Helluva dog.
OFFICER John nods as The Officer heads back to his car.
OFFICER Jenny crouches down and gives Marley a big hug and a back rub...
JENNY My hero.
An upscale, newer money neighborhood.
An OPEN HOUSE sign out front.
John pulls up.
He opens the door, holds up a hand to Marley who sits in the back--
JOHN Stay.
JOHN --and starts to unhook Patrick from his car seat.
JOHN Marley bolts out of the car and heads straight for the house...
JOHN (CONT'D) Marley!
A REALTOR is showing a COUPLE around the large, empty, new house.
She points out the designer kitchen that looks out onto the patio and pool, a huge yellow lab now leaping in.
A moment later, we see John, clutching Patrick, enter the backyard, try to haul Marley out of the pool.
He gives up, heads for the house, opens the back door and peers inside.
JOHN Hi.
JOHN The Realtor smiles awkwardly at him.
JOHN (CONT'D) Can I see a set-up, please?
REALTOR Certainly.
REALTOR First home?
JOHN No, we live up in West Palm, over on Churchill?
REALTOR Ooooh.
REALTOR Well, I think you'd find this neighborhood to be quite a pleasant change.
REALTOR And now Marley bolts past him into the house, tracking wet footprints all over the floor, jumps up onto the REALTOR.
Oh...
my...
hello...
JOHN Hey, who's dog is that?
John enters, carrying Patrick, supplies to fix the screen.
JOHN Jenny?
JOHN A wet Marley bounds into the house, heads for the back.
JOHN John follows.
THE Jenny is crouched on the floor when John appears in doorway.
JOHN Hey.
JOHN You alright?
JOHN She stands up, smiles the best she can.
JENNY I'm fine.
JENNY Where you guys been?
JOHN I wanna show you something.
JENNY What?
JOHN A house.
JOHN It's a little pricey, but I think we can do it.
JENNY John, I know we've talked about it, but I'm not sure this is the right time.
JOHN And when would the right time be, Jen?
JOHN After one of us gets stabbed in the driveway?
JOHN C'mon, honey, we're cramped in here.
JOHN This was supposed to be our three-year house, remember?
JENNY I know, but we can't afford to buy a new one.
JOHN Sure, we can.
JOHN With both our salaries--
JENNY Yeah, about that...
JENNY I don't think I'm gonna be able to keep working.
I'm pregnant.
JOHN What?
JOHN Are you sure?
JOHN She steps away, revealing the counter where FOUR PREGNANCY TESTS are lined up, all with the same result: Positive.
JENNY Very.
John sits with Sebastian at his desk.
SEBASTIAN Already?
SEBASTIAN I mean, how old's the one you got?
JOHN About eight months.
SEBASTIAN Jesus.
SEBASTIAN Haven't you heard of birth control?
JOHN Yeah, well, sometimes it doesn't work.
JOHN You know what else doesn't work?
JOHN The one about how "A dog will stop your wife's biological clock."
SEBASTIAN Hey, I'm not the one, keeps getting her pregnant.
SEBASTIAN John gives him a look, sees Arnie heading into his office, takes a breath and gets to his feet.
JOHN Wish me luck.
SEBASTIAN I'm sure he'll give you the raise.
JOHN How do you know?
SEBASTIAN He always gives me one.
SEBASTIAN John just shakes his head, starts for Arnie's office.
John sits across from Arnie.
ARNIE Why should I do this, why are you worth it?
JOHN Because I'm doing a good job?
ARNIE Are you asking me?
JOHN Well, since I took over, the column has doubled in readership...
ARNIE So you are doing a good job.
JOHN Yes, sir.
ARNIE So why not make it permanent?
JOHN You mean, like forever?
ARNIE That's what the word "forever" means.
ARNIE Yes.
John, you know how many yo yo's in the other room would kill to have their own column?
You took a piece of crap About Towner and turned it into something fresh.
I hate to break it to you, son, but you're a good columnist.
JOHN I just had this idea about myself, you know, that I was a reporter.
ARNIE Yeah, well sometimes life comes up with a better idea.
ARNIE Tell you what.
ARNIE You make it a daily column and I'll double your salary.
ARNIE How's that?
A MOVING VAN is parked out front.
Marley runs back and forth as the MOVERS load up the truck, John and and a very pregnant Jenny supervising.
John sees LISA, the girl next door, as she comes out of her house.
She walks over to him.
JOHN Hey, Lisa.
LISA Hi.
You're leaving.
JOHN Yeah.
LISA well, I don't blame you.
LISA I just thought I'd come over and say-- But Marley comes running over and she crouches down to greet him.
LISA She hugs him a while...
LISA (CONT'D) I'm gonna miss you.
LISA (CONT'D) John watches as she holds on to him a bit longer, thanking him as well.
LISA (CONT'D) John turns away, starts back for the van to give her a moment.
LISA (CONT'D) She stands up.
LISA (CONT'D) Where you moving to?
JOHN Boca.
LISA Huh.
JOHN Huh...
JOHN what?
LISA Nothing.
LISA I just...
LISA never pictured, you know, a guy like you moving to Boca.
JOHN A guy like me?
LISA Yeah, you know, young, cool, whatever.
JOHN So you think I'm young and cool.
JOHN And you're not just saying that because I saved your life?
LISA Actually, a paramedic named Josh saved my life.
JOHN Right.
JOHN Well, take care, Lisa.
JOHN Oh,
He reaches into a moving box, pulls out a chewed-up black Converse.
JOHN (CONT'D) I believe this belongs to you.
LISA Thanks.
LISA I'll have to chew up the other one to make it match.
LISA Have fun down there.
JOHN Yeah.
JOHN It's gonna be great.
Still beautiful, but now we hear the sound of a BABY WAILING
This is the elegant kitchen we saw, bare and uninhabited, several scenes ago.
Now it's full of the clutter of the Grogans' life.
The new baby, CONOR is screaming.
We follow Jenny through the new house asshetries to soothe him.
JENNY Shhh, honey.
JENNY Come on.
JENNY John follows now...
JOHN Is he wet?
JENNY No.
JENNY And I can't get a burp out of him.
JENNY I think it's colic.
JOHN Want me to drive him?
JENNY We can't do that every night.
JENNY From the other room, we HEAR Patrick CRYING, "Mommy!"
JENNY (CONT'D) Oh, Jesus.
JOHN I'll do the washer.
John sitting on the washer with his WAILING BABY.
Not fun.
John looks to where Marley lies in the corner, watching.
JOHN Any ideas?
John is opening the cupboards, getting cereal and yogurt into a bowl for Patrick.
Jenny enters with a fussing Conor on her shoulder...
JENNY Can you take him?
JENNY I just need a minute to myself.
JENNY John takes the baby and instantly Conor starts crying louder.
JOHN Happens every time.
JENNY You just need to spend more time with him.
John puts Conor on the changing table, unbuttons his onesie, checks his diaper.
It's wet; he starts changing him.
Conor cries throughout.
Jenny enters.
JENNY It's okay, I'll do it.
JOHN I'm doing it!
JOHN It's fine!
JOHN You tell me to spend more time with him, I do it, and then you take over because I'm not doing it right.
JENNY I don't want you changing him when you're mad.
JOHN I'm not mad!
JOHN He hears himself, lets her change the baby.
JOHN She takes him, sits down with him in a rocking chair, tries to nurse him...
JENNY Conor, come on...
JENNY Conor, please...
JENNY She finally stops trying, rocks the chair, looks helplessly at John.
JENNY (CONT'D) I don't know what's wrong with me.
JENNY (CONT'D) Mothers are supposed to be able to give their baby everything.
JOHN He's just colicky, Jen.
JOHN He'll grow out of it.
JENNY Okay, here's an idea, you stay here and I'll go to work while he grows out of it.
JENNY He holds up his hands, what does he say to that.
JENNY She looks up at him a moment.
JENNY (CONT'D) I'm just tired, alright?
JENNY (CONT'D) Go on.
JENNY (CONT'D) She then resumes trying to nurse the baby.
JENNY (CONT'D) He walks out of the room.
JENNY (CONT'D) She rocks back and forth, looks up with a dark expression as she hears his CAR START.
ARNIE (V.0.) It's post partum depression...
John sits on a stool in front of'a portable SCREEN while a pretty female PHOTOGRAPHER adjusts her lights.
Arnie sits nearby on a desk watching the portrait...
ARNIE Her hormones are all on tilt and she's depressed.
ARNIE It happens.
ARNIE After my fourth kid was born, I'd wake up, find my wife just staring at me with a mallet in her hand.
ARNIE I thought she was gonna kill me in my sleep.
ARNIE I still do...
Did you get her the gift?
JOHN Yeah.
ARNIE Huh.
ARNIE That usually works.
Arnie gets off the desk, says to the Photographer:
ARNIE (CONT'D) Alright, Janice, make him look pretty.
ARNIE (CONT'D) The man's an official columnist now.
ARNIE (CONT'D) Arnie moves off and the photographer looks up from her camera and smiles at John.
ARNIE (CONT'D) He smiles back.
ARNIE (CONT'D) She keeps smiling...
ARNIE (CONT'D) so does he...
ARNIE (CONT'D) she finally indicates his hair...
PHOTOGRAPHER You have a Barney sticker in your--
JOHN Oh-- thanks.
JOHN He rakes his fingers through his hair, grabs the offending sticker, looks at her...
JOHN (CONT'D) I must look like hell...
JOHN (CONT'D) I don't think I've had a full night sleep in two months.
PHOTOGRAPHER Stress?
JOHN Kids.
JOHN I got one with colic, and another, can't make it through the night without coming into my room every two hours.
PHOTOGRAPHER Well, I think you're holding up great.
PHOTOGRAPHER You look cute.
JOHN Really?
PHOTOGRAPHER Yeah, like a cute, exhausted Dad.
PHOTOGRAPHER It's adorable.
PHOTOGRAPHER John just nods stupidly, the dagger so deep in his heart, he'll never reach it.
PHOTOGRAPHER She smiles at him.
You certainly look a lot better than Jerry ever looked.
I tried to get him to take a new picture, but he liked the one they took the day he started the column, nineteen years ago.
JOHN Nineteen years, huh...
JOHN And just when he thought one dagger was brutal enough, his expression goes really pensive.
JOHN And on that look, we see a
FLASH as she takes his picture and go right to:
John pulls into his driveway, turns off the car and just sits there.
As John looks at the house...
the windows all lit up.
Inside Jenny moves about with the baby over her shoulder as Patrick chases Marley around the room.
John sits in the car, unable to move, just watching the chaos in the window.
Marley jumps up against the glass, stands on his hind legs, paws to the window and looks out.
He barks and now Jenny comes up behind him, hauls him off the window and now sees John sitting in the car.
She gives him a look that says "What're you doing?
Get in here!" John quickly gets out of the car...
John and Jenny eat dinner in exhausted silence.
Patrick throws his food on the floor where a happy Marley waits.
Conor starts crying O.S. and Jenny gets up like a robot.
JOHN I'll get him.
JOHN John leaves the room.
JOHN Jenny sits there.
John and Jenny are in bed asleep.
Patrick comes into their room.
PATRICK Mommy?
PATRICK Jenny wakes up on autopilot.
JENNY Okay, honey, let's go back to bed.
JENNY She leads him out of the room.
JENNY And a second later Conor starts crying.
JENNY John lies there a moment, then gets up.
Through the doorway, Jenny, her back to us, gently bounces Conor on her shoulder.
John moves into FRAME...
JOHN Jen, you okay?
She's crying, her back to John who's now in the b.g.
A moment, then...
JENNY I'm fine.
John comes into the kitchen just as Jenny takes a chewed copy of "Good-night, Moon" from Marley's mouth...
JENNY You ruined it!
JENNY Bad dog!
JENNY She leaves the room and John looks at the dog.
JOHN You just had to eat the book?
JOHN What, have you got some kind of death wish?
JOHN I'm telling you, you better chill, or she'll kill you.
JOHN Right after she kills me.
As Jenny loads up the back of the car with bags of groceries.
Patrick, sitting in the cart, looks off and points--
PATRICK Look!
PATRICK Jenny turns and sees A BUS, with John's picture on the side, an advertisement for his column.
PATRICK She watches it pass.
Daddy!
JENNY Uh-huh.
JENNY I see him.
JENNY And she goes back to loading the car.
As Jenny gently sets a sleeping Conor in his crib.
She quietly backs out of the room and shuts the door.
As she peers in on Patrick, also napping in his room.
As Jenny comes in, Marley following and sits down heavily on the bed.
She looks at Marley as he lays down beside the bed.
JENNY Stay.
JENNY She now lays down and closes her eyes.
JENNY A moment of peace.
JENNY And then, somewhere in the distance we hear a faint BEEP BEEP BEEP as some truck backs up.
JENNY Marley lifts his head, perks up his ears and listens.
JENNY Please don't bark, dog.
JENNY Please don't bark.
JENNY BEEP BEEP- And Marley BARKS, bolts out of the room...
JENNY Jenny opens her eyes with a start as Marley runs barking through the house, we hear something CRASH and break O.S.
And now Conor's crying.
As Marley jumps up against the window and peers out.
Jenny comes into the room, sees a lamp on its side, a cushion torn open where Marley now stands.
she grabs him by the collar--
JENNY Why do you do this?!
JENNY Why do you wreck everything!
JENNY Why?!!
JENNY She hauls her hand back to hit him, but hesitates, and just shoves him away from her and storms into the other room for Conor.
As John pulls up, gets out of his car.
We hear Marley barking in the garage.
As John comes in, sees Jenny sitting there on the couch.
JOHN Why's Marley out in the--
JENNY I want that dog out of here.
JOHN Okay.
JOHN I'll take him out.
JOHN She looks up at him.
JENNY I want you to get him out of here and keep him out of here.
JOHN What'd he do--
JENNY I mean it, John.
JENNY I want him gone.
JENNY I want him gone for good.
A sad John posts a "DOG FOR SALE" sign.
A CO-WORKER sign and smiles.
That the dog in your column?
Obed ience school?
Necklace in the poop?
Good luck.
John watches the guy walk off, scribbles a new it up.
This one reads "E F D TO GOOD HOME."
comes up to John.
SEBASTIAN You giving up the dog?
SEBASTIAN i thought yo u loved that thing.
JOHN Jenny wants him out.
SEBASTIAN That's harsh, man.
JOHN I don't know what else to do.
JOHN She's really unhappy.
JOHN Maybe the dog is just one too many things.
SEBASTIAN They're all unhappy.
SEBASTIAN Trust me.
SEBASTIAN Well...
SEBASTIAN who knows?
SEBASTIAN Maybe you'll get lucky and nobody'll want him.
SEBASTIAN John just nods, thinks about that.
SEBASTIAN Sebastian glances around, then takes John aside.
SEBASTIAN (CONT'D) Listen, there's something I gotta tell you.
I'm leaving the paper.
JOHN What?
SEBASTIAN I just gave Arnie my notice.
SEBASTIAN John looks over at Arnie's office, the door's closed.
SEBASTIAN (CONT'D) He's not too happy about it.
SEBASTIAN (CONT'D) He called me an ungrateful quizzling and threw a stapler at me.
JOHN You going over to the Post?
SEBASTIAN I'm going to New York.
SEBASTIAN Sebastian smiles.
SEBASTIAN John doesn't move.
SEBASTIAN (CONT'D) The Gray Lady came courting last week.
Times, I'm talking about the New York
JOHN I know who you're talking about.
SEBASTIAN You don't seem happy for me.
JOHN I am.
JOHN I'm just in shock.
JOHN I mean, I'm in Florida because of you.
JOHN Woodward and Bernstein.
JOHN Remember?
JOHN That was the idea.
SEBASTIAN Yeah, that was the idea before you decided to be the Andy Rooney of South Florida.
JOHN I didn't decide to be anything--
SEBASTIAN Exactly.
SEBASTIAN Boom.
SEBASTIAN That hurts John.
SEBASTIAN They stand there a moment, considering each other, then.
SEBASTIAN (CONT'D) Look, man, you're happy doing your thing and I'm not trying to piss on that.
SEBASTIAN (CONT'D) I mean it, you're good at it.
SEBASTIAN (CONT'D) I just wanted you to be the first to know.
SEBASTIAN (CONT'D) That's all.
The house where John and Jenny bought Marley.
Lori, the breeder, looks at Marley, sitting in the front seat, shakes her head sadly.
Marley & He Shooting Draft
As John posts some more flyers around the park.
He drops a flyer and Marley, walking beside him, starts to eat it...
JOHN Smart boy.
"BROWARD COUNTY DOG RESCUE."
A refuge for dogs.
John fills out a form...
THE Yeah, uh...
THE Monday, then.
THE Give us weekend.
Up to you.
John looks at the dogs in the back, all of them trying to get his attention.
John is working at his desk when Arnie drops a few stacks of letters down.
ARNIE These are all responses to the column you wrote last week.
ARNIE John thinks a moment...
ARNIE (CONT'D) One where you said you may have to give the dog away.
JOHN Oh.
JOHN I assume they all want me to keep him.
ARNIE No.
ARNIE They're all saying they'd take him.
ARNIE Arnie moves on and John stares at the letters.
John walks around the yard picking up Marley's various toys, putting them into a box.
Marley follows, jumping up, trying to get the toys back out of the box.
John grabs a frisbee, looks at the dog.
JOHN You can't lo any more of these, ok ay?
JOHN Because they s e 're not gonna keep getting you more, and I won't be there to look for them...
JOHN He looks at Marley standing there wagging his tail.
JOHN (CONT'D) You're gonna be fine, alright.
JOHN (CONT'D) I'll just be different.
JOHN (CONT'D) Maybe e it'll, b better, nobody poking your yanking your tail.
JOHN (CONT'D) Who knows?
JOHN (CONT'D) Could be better.
Jenny's been watching.
She stands there thoughtfully as John puts the frisbee in the box and resumes the hunt for the rest of Marley's stuff, the dog following him.
Jenny's sitting on the bed waiting as John comes in.
JOHN He's all packed up.
JOHN Patrick will want to say good-bye, but Conor's too young
JENNY You can't do this.
JOHN What do you mean?
JOHN Three days ago, you were pretty clear--
JENNY I know, but you can't do it.
JENNY I won't let you.
JENNY You can't give away Marley.
JOHN Okay, wait.
JOHN I'm lost.
JOHN You told me you didn't want him around.
JOHN What's happened?
JENNY The fact that you would have done something like that, for me, that you love me that much...
JENNY (CONT'D) well, that blows me away.
JENNY (CONT'D) And we're not doing this.
JENNY (CONT'D) It was wrong of me to ask.
JENNY (CONT'D) He comes over and sits down beside her.
Maybe not, maybe Marley is one thin too many.
JENNY I got overwhelmed, John.
JENNY I mean, be.
JENNY one tells you how hard it's gonna
JOHN Which part?
JENNY All of it.
JENNY Marriage.
JENNY Being a parent.
JENNY It's the hardest thing in the world and no one prepares you for that.
JENNY No one tells you how much you have to give up.
me.
I gave up so much of what makes me But I'm not allowed to say that.
People think you're a bad person if you say that.
But it's how I feel sometimes, and I need you to know that.
JENNY It's not your fault.
JENNY It's just something I have to figure out.
JENNY But Marley going, that won't fix anything.
JOHN Okay.
Okay.
She kisses him on the cheek, then gets up and goes into the bathroom.
He sits on the edge of the bed, staring down the hall...
to how they've At the end of the hall, panting, oblivious both just been spared.
John and Jenny and Marley and the two boys stroll.
Feels good to be out as a family again.
Marley wants to greet all the Boca mini-dogs as they are being walked or carried by their owners.
Jenny leans up against John.
JOHN I made reservations at Sunny's.
JOHN Thought we could all sit outside.
JENNY Sounds perfect.
JENNY Thank you.
They are seated at an outside table, shaded by a large round umbrella.
John hooks Marley's leash to two of the table legs as a waiter brings drinks.
Jenny holds up her beer.
JENNY To a perfect day with my boys.
A blonde Boca Trophy wife, with a poodle on a jeweled leash, shrieks excitedly as she meets up with another woman, same type, with another small fluffy'dog.
The little dogs yip.
CAMERA BOOMS DOWN to underneath the table to Marley who has spotted the poodles and is now locked and loaded.
As suddenly their table suddenly leaps away from them and starts moving down the sidewalk, crashing into other tables, banging-into waiters with trays, making a terrible NOISE as it scrapes over the faux Italian paving stones.
The four Grogans sit facing each other across, their drinks suddenly in their laps.
Marley is pulling the table, like a dog with a sled, towards the now-terrified small dogs.
He is chugging forward with every ounce of rippling muscle he has.
JENNY (CONT'D) Marley!
JENNY (CONT'D) John hurries after the dog; Jenny stays with the boys.
As Marley-with-table approaches the small dogs, they break free of their leashes and run.
Several innocent bystanders are knocked off their feet.
There's a florist kiosk in the center of the plaza; Marley- and-table take out most of the merchandise.
Security guards look around wildly.
It's pandemonium, but Marley is in heaven.
He makes a circuit of the entire plaz a, one poor poodle runs for her life.
Finally, back where Marley started, the terrified toy poodle leaps into Jenny's arms.
Marley tries to brake -
JOHN Marley, no!
JOHN - and suddenly, he is jerked back.
JOHN John has tackled the table Marley's dragging.
JOHN Marley YELPS and lands on his bac k, then quickly rights himself, tail wagging, the happiest dog in the world.
JOHN Everyone surrounding them on the plaza has frozen silent.
JOHN They all stare at Marley and the Grogans.
JOHN The poodle jumps out of her arms and runs to its distraught owner.
JOHN Jenny's head is in her hands, her shoulders heaving...
JOHN (CONT'D) Jen, you okay?
Jenny?
And she slowly looks up, LAUGHING UNCONTROLLABLY, her whole body racking, tears in her eyes.
Her LAUGHTER BECOMES-- --A BABY CRYING and we now go to...
As a NEWBORN BABY is placed on Jenny's chest...
JENNY Boys, say hello to Colleen...
JENNY We PULL BACK TO REVEAL: Patrick, now six and Conor four, standing beside the bed with John.
JENNY They all crowd around "mom" as the NURSE now takes a picture.
JENNY On the FLASH, we...
John and the boys plant flowers in front of the house whilehead up like a Marley, chained to a post, lies in the shade, Sphynx, the baby, colleen in a portable bassinet beside him.
Jenny comes outside with some sodas for the boys...
JENNY John, telephone.
CONOR Mom, look what we did!
As John comes inside and picks up the phone.
JOHN Hello?
As John comes back out of the house, looking stunned.
JENNY Who was on the phone?
JOHN Philadelphia Inquirer.
JOHN She looks at him.
JOHN (CONT'D) They're offering me a job.
As a reporter.
I guess the editor was down here on vacation, read my stuff.
JENNY What'd you say?
JOHN I said thank you very much, but I'm happy where I am.
JOHN I mean, it's a big change, Florida to Pennsylvania.
JENNY Yes, it is.
JOHN Anyway.
JOHN John smiles at her, then goes to his sons...
JOHN (CONT'D) C'mon, guys, back to work...
JOHN (CONT'D) She watches as he kneels down beside the boys, resumes digging alongside them.
John reads through a stack of letters...
JOHN Well, that's part of the job.
JOHN To get reader response.
ARNIE re?
ARNIE You notice any recurring themes the
JOHN Yeah.
JOHN We've got a lot of cranks in Broward County.
ARNIE Yeah.
ARNIE Including yi? 1/2 gu the last couple months.
ARNIE "..
ARNIE .if he doesn't like it here, he
should move"...
"more whining resident malcontent"...
"is there anything good about Florida according to Mr. Grogan?"
JOHN Arnie, I'm a commentator.
JOHN We've got issues here.
JOHN Over-crowding, crime, immigration tensions, runaway
ARNIE Florida hasn't soured, John.
ARNIE You have.
What's wrong?
JOHN I don't know.
JOHN Maybe it's turning 40 next week, or maybe...
ARNIE Maybe what?
JOHN Maybe I'm sick of my column.
JOHN I don't really think I'm all that interesting.
ARNIE Are you kidding?
ARNIE You're the comic voice of South Florida's middle class.
ARNIE You're a national treasure.
ARNIE Well, a regional treasure.
ARNIE Municipal treasure, for sure.
ARNIE You're just a little burned out.
ARNIE Why don't you take a coupweeks off?
ARNIE Consider it my birthday present.
John pulls into the driveway, gets out.
John opens the door.
He flicks on the lights and 100 people shout "Surprise!" There are banners hung from the ceiling, reading "HAPPY 40TH."
Jenny is standing there, holding Colleen.
Conor, aged 5 and Patrick age 7 run to their father.
JENNY Happy birthday, honey!
JENNY And he kisses Jenny.
JENNY Hugs the kids.
JENNY Jenny watches him as he i en t e d , distracted.
JENNY shakes hands, hugs their friends, disor
170 INT. LAUNDRY ROOM - NIGHT here.
John , closes John petsdthe dog, rta es up , g greets John.
JOHN Forty.
JOHN Jesus Christ...
JOHN He looks at Marley a moment, then...
JOHN (CONT'D) Hey, buddy, you and me are the same age.
JOHN (CONT'D) You got more grey hair than me, though...
Mind if I just hang here for a minute?
And sits on the floor, his back against the washing machine.
As Jenny brings in a cake with 40 candles on it.
John tries not to be too taken aback by the blaze.
JOHN Okay, who wants to help me here?
JOHN Kids?
JOHN Marley, you too.
JOHN Jenny squats down with the cake, and John and his kids start to blow out the candles.
JOHN (CONT'D) One, two - And then Marley jumps the gun, takes a huge bite of the cake, lit candles and all.
JOHN (CONT'D) - three.
The guests have gone.
John sits in a lounge chair, holding out a fork so that Marley can lick the cake off of it.
Most of the floating lights have gone out.
Jenny comes out.
JENNY Okay, tell the truth, were you really surprised?
JOHN Yeah.
JOHN Thanks, Jen.
JOHN She sits down on his lap...
JENNY You want your present?
JOHN Is it what you gave me last year?
JOHN Because that was real nice-- She hands him an envelope.
JENNY Happy Birthday.
JENNY He opens it, pulls out an AIRLINE TICKET.
JOHN A plane ticket?
JENNY To Philadelphia.
JENNY So you can talk to the editor of the inquirer.
JOHN That was months ago--
JENNY I called the editor last week.
JENNY They'd still like to meet you.
JOHN Jenny, I couldn't do that, uproot us.
JOHN We've got our friends, the schools...
JENNY First of all, you don't even have the job yet, it's just an interview.
JENNY Second of all, you don't have that many friends.
JOHN Thank you.
JOHN What I was trying to say, is that our life is here.
JENNY Baby, I got news for you, our life is wherever we are.
JENNY And you're not happy here anymore, doing that column.
JENNY You're restless, John.
JENNY I feel it.
JENNY I feel it when you read Sebastian's articles every day.
JENNY And I feel it when you sit out in the driveway an extra five minutes before you come in.
Maybe it's time for a change.
JOHN I'm forty, Jen.
JOHN Seems kinda late for that.
JENNY Not so late.
JENNY She stands up in the dark, lifts her dress over her head.
JOHN What're you doing?
JENNY We're not old, John.
JENNY We can still surprise ourselves.
JENNY He sits there stunned as she now dives into the pool.
JENNY She surfaces and smiles at him.
JENNY (CONT'D) Hey.
JENNY (CONT'D) You want your other birthday present or not?
John can't get out of his clothes fast enough.
He leaps the pool and swims over to her, kisses her.
JENNY (CONT'D) We're not old.
JENNY (CONT'D) And then we hear ANOTHER splash.
JOHN Uh-oh...
JOHN And a moment later Marley's head goes bobbing by.
173 INT. SUN-SENTINAL OFFICE - DAY out of his As John packs up his desk.
Arnie sticks his head office.
ARNIE Hey, Gorgan.
ARNIE John smiles to himself, walks over.
ARNIE (CONT'D) I just wanted to say good luck up there.
JOHN Thank you, sir.
ARNIE Also, there's a good chance that every piece of advice I ever gave you, may in fact be total crap.
JOHN I appreciate it just the same.
JOHN They stand there a moment, awkward.
JOHN Then...
ARNIE This would be where a mushier guy would tell you he's proud of you, give you a hug, and send you on your way.
JOHN Really glad you're not that guy, sir.
JOHN Arnie nods, goes back into his office and shuts the door.
Shooting Draft 101.
The Grogans are in the back of the plane.
JOHN Look.
JOHN There's Marley!
JOHN THROUGH THE WINDOW they can see Marley's crate arriving at the plane on a luggage truck.
JOHN Marley is asleep, heavily drugged.
JOHN Conor starts banging on the window.
CONOR Hey, Marley!
CONOR We're up here!
PATRICK He can't hear you with the engine going.
JOHN Not to mention the tranquilizers.
JOHN I think he's already reached his cruising altitude.
The engines ROAR up and the stewardess begins her pre-flight safety demonstration.
John watches her, smiling, relieved they made it this far, when he freezes.
A MUFFLED MOAN is coming from beneath his feet.
Clearly it's Marley.
Passengers near them frown.
is that a dog?
JOHN Maybe, I don't know.
PATRICK Marley's Sad.
PATRICK Marley's our dog.
PATRICK He's with the suitcases.
PATRICK John smiles weakly at the Passenger.
JOHN What an imagination, huh?
We don't have a dog.
He makes the crazy sign with his finger, gesturing at Patrick.
The MOANING gets worse.
John just smiles tightly.
Fall foliage.
Beautiful, picture-perfect countryside.
The Grogan family car winds along the roads.
Marley has his head out the window, tongue wagging...
A two-story country house, no neighbors visible.
Trees, land, woodpile, the whole country living thing.
The Grogans pile out of the car, look at the house.
Marley takes off running...
JOHN Marley!
JOHN Marley jumps into a pile of leaves, scatters them everywhere, rolls over onto his back and knocks over a rake, which falls and breaks a basement window.
JOHN (CONT'D) And...
JOHN (CONT'D) we're home.
As John is introduced to fellow staff and reporters, most of them at least ten years younger than he is.
He's shown his desk.
John sits down at his cubicle, stares out the window at the city.
His EDITOR, black, John's age, approaches with a much younger REPORTER...
EDITOR Hey, John.
EDITOR Settling in okay?
JOHN I'm fine, thanks.
EDITOR Good.
EDITOR I want you to meet Billy...
EDITOR He indicates the twenty-something guy beside him.
EDITOR John and Billy shake hands.
EDITOR (CONT'D) Billy's gonna show you the ropes.
BILLY You're the Florida guy, right?
BILLY The dog columns...
JOHN Well, some of them were, but--
BILLY Cute stuff.
BILLY C'mon, I'll show you around.
January.
John wakes up.
Marley is whimpering at him.
JOHN What?
JOHN And then Conor and Patrick burst into the room.
PATRICK It's here!
White everywhere.
The family and Marley trudge into the snow, unused to their boots and snowsuits.
Marley jumps around, barks like he's a puppy again.
The kids slide down the hill in a toboggan.
John is at the bottom to catch them.
Up at the house, Jenny calls...
JENNY Okay, time for lunch!
JOHN I'll bring this in.
JOHN Go on up.
JOHN The kids and Marley head up to the house.
JOHN John drags the toboggan up the hill.
JOHN He pauses at the top and looks down at the toboggan run.
JOHN He gets on the toboggan.
JENNY Honey, what're you doing?
JOHN I can't remember the last time I rode on a toboggan..
JENNY Exactly.
JENNY He starts sliding down the hill.
JENNY Marley runs for him as he builds up speed...
JOHN Marley, no!
But Marley jumps onto John's lap as they get going...
Flying down the hill.
Marley is much heavier than the kids, and they sail past the place where the kids stopped, through the woods, barely missing trees and low-hanging branches,
JENNY John!
JENNY The creek!
JENNY The toboggan bumps over the crest of a small hill and sails through the air, landing with a crash on the iced-over creek.
JENNY John and Marley tumble into a snow bank on the opposite side.
JENNY A moment.
JENNY But then Marley jumps up and wriggles in delight.
JENNY John painfully unfolds himself, checks for injuries.
JENNY Marley comes up and romps with him.
JOHN Hey...
JOHN wanna do it again?
JENNY John!
John shuts off all of the lights, heads upstairs.
We follow him up the stairs.
He stops near the top, peers through the bannister into...
From the low angle of the stairs, Patrick lies on his side, sleeping.
And then we see Marley's head rise and reveal itself as Marley lifts it to look at John standing there.
He'd been laying there on the bed behind Patrick.
He looks at John, knows he's not supposed to be there, but...
JOHN That's alright, pal.
JOHN I won't tell.
We kicked ass down that hill, didn't we?
John smiles at him and continues up to bed.
Early Spring.
The snow has melted.
Marley, still as a statue, sits at the side of the road, waiting.
Suddenly, he stands up and starts to wag his tail.
A moment later, a yellow dot appears on the horizon.
As it gets closer, Marley gets more and more excited as we now see that the dot is a SCHOOL BUS.
It pulls to a stop beside Marley.
Conor and Patrick get off and are greeted by Marley.
PATRICK Hey, boy.
PATRICK We HOLD WIDE ON THEIR BACKS as the boys start up the road towards home, Marley bounding between them, nipping at Patrick's backpack.
John pulls up as the boys now throw a football back and forth while Marley leaps into the air, trying to intercept it.
John gets out of the car, claps his hands, holds them up...
JOHN Hit me, I'm open!
JOHN Patrick throws the ball to John who catches it, mocks stiff- arms his way to the front steps with the boys now hanging off him as he gives the play-by-play...
JOHN (CONT'D) My God, look at Grogan-- two three- hundred pound linemen literally hanging off him, but he won't be denied!
JOHN (CONT'D) And now Marley jumps on them.
JOHN (CONT'D) Ohhh, out of nowhere, a brutal hit from the Strong Safety and the unthinkable happens...
JOHN (CONT'D) GROGAN GOES DOWN...
JOHN (CONT'D) And he collapses with the boys at the foot of the.
JOHN (CONT'D) steps, Marley all over them, licking whatever faces he can get.
JOHN (CONT'D) Colleen comes out the front door, stands at the top of the steps...
COLLEEN Mommy says dinner and take off your shoes.
JOHN Alright...
JOHN c'mon guys...
JOHN They all get up, start up the steps.
JOHN Marley follows, takes one step when his hind legs buckle.
JOHN John looks back at him.
JOHN (CONT'D) You okay, boy?
JOHN (CONT'D) C'mon...
JOHN (CONT'D) Marley tries the second step and again his legs give out.
JOHN (CONT'D) He looks up at them...
CONOR What's wrong with him, Daddy?
Nothing's wrong.
He's just tired.
Right, Dad?
John sees the way Patrick is looking at him, knows he's protecting his little brother.
JOHN That's right.
JOHN Football just took it out of him.
JOHN C'mon, let's give him a hand.
JOHN And now the three of them go to Marley, help him up the stairs.
John sits across from the editor.
JOHN Too much color.
EDITOR Yeah, I mean, don't get me wrong, it's a good piece, but...
EDITOR you're reporting now, John.
EDITOR I want you to tell the story, I don't want you to be in the
JOHN I'm pretty sure I don't mention myself--
EDITOR The point is, I still feel you in there.
EDITOR John sits there, thinking about that.
EDITOR (CONT'D) All I'm saying is: less you, more facts.
Marley snores on the floor while John, Jenny and the kids all watch a movie together.
Suddenly, they all take a whiff, then wince at once...
CONOR Marley!
CONOR They all begin waving their hands in front of their faces.
JENNY I think someone needs to go out.
Come on, boy...
Marley gets to his feet, follows John to the front door.
Rain falls as John opens the door and Marley trots outside.
As John comes back into the room a moment...
JOHN It's pouring out there...
JOHN He grabs his slicker and heads back out...
As John returns, steps outside, but Marley is nowhere to be seen.
John, claps his hand and whistles...
JOHN Marley!
JOHN Now Jenny appears in the front door.
JENNY What's wrong?
JOHN He's not coming.
JENNY Marley!
JENNY John starts off into the dark...
JOHN He can't be too far...
As John trudges through the rain looking for the dog.
Jenny looks in the barn, the garage...
She looks at John comes into the kitchen - without Marley.
him with concern...
he start out of the room.
JOHN He'll show up.
John is tucking the boys in.
JOHN He's just out exploring.
JOHN You know how much he likes the woods.
PATRICK Bobby says dogs, when they're going to die, they go away to do it.
PATRICK That's what his beagle did.
JOHN And that's true...
JOHN for beagles.
JOHN But not labs like Marley.
JOHN He's just out there making trouble somewhere.
JOHN Don't worry...
John's on the phone to neighbors...
JOHN Okay.
JOHN Well, if you see him...
JOHN thanks.
JOHN He hangs up, goes to the window.
JOHN (CONT'D) I'm gonna get in the car, maybe drive
Jenny.
Shooting Draft 109.
John and Jenny run to'a tree at the edge of the property.
Marley lies on the ground, in a hollow, hidden from view from the hill above.
His belly is swollen, his face drawn.
It's clear he's very ill.
JOHN It's okay, boy, it's okay...
John stands with DR.
PLATT, a female vet.
Marley lies on the floor in a dog bed, an IV is going into his paw.
DR. PLATT He's on an IV for fluids and a sedative.
JOHN So what happened?
DR. PLATT His stomach twisted.
DR. PLATT He ate or drank something quickly, took in a lot of air and his stomach flipped.
DR. PLATT I got a tube down which let out some of the gas.
DR. PLATT I think i untwisted it.
JOHN So he's okay...
DR. PLATT For now.
DR. PLATT But once this happens, it almost always happens again.
DR. PLATT And if it does, there's not gonna be anything I can do.
DR. PLATT He's too old for that kind of surgery.
JOHN What if it doesn't happen again?
DR. PLATT More than likely, it will.
JOHN But what if it doesn't?
DR. PLATT I just think you should prepare yourself that he might not make it through the night.
Maybe one percent of dogs ever survive
JOHN One percent?
JOHN What's that number based on?
DR. PLATT Mr. Grogan--
I'll tell you what it's based on: regular dogs.
Lady, we are so far from 'regular", you have no idea.
My guy here...
He once ate an entire answering machine, and digested it.
Then went back and ate the phone for dessert.
So don't give me numbers like "one percent," because you don't know him.
But I do, and I'll see him in the morning.
We TRACK WITH JOHN as he storms out of the exam room, walks down the hall, goes through waiting room, then he PASSES US as he goes out into the dark parking lot, walks to his car and stops.
We stay BEHIND HIM as he leans with one hand on his car, and doesn't move.
Jenny's sitting at the table looking through a thick album when John comes in.
She looks up at him expectantly.
JOHN We're just gonna have to wait and see.
JOHN If he makes it through the night, I think we'll be alright.
JOHN He notices the album.
JOHN (CONT'D) What're you looking at?
JENNY Your old columns.
JENNY He's in a lot of 'em.
John rotates the album for a better look.
JOHN You saved these?
JENNY Every one.
JENNY He looks up at her.
JENNY (CONT'D) Even on the crappiest day, when the boys were driving me nuts and the laundry wasn't done and a hundred other things were hard, I knew I had this.
JENNY (CONT'D) Five minutes of you.
JENNY (CONT'D) Sometimes they were funny and sometimes they were sad, or silly or whatever, but they were all you.
JENNY (CONT'D) And for those five minutes, you made me feel better.
JENNY (CONT'D) She gets up, comes over to him, leans down and kisses his head.
JENNY (CONT'D) Then, as she starts out...
JENNY (CONT'D) You should read them.
JENNY (CONT'D) They're pretty great.
The sun just coming up.
We hear A PHONE RING OVER.
As John, his head on the table, asleep, pops up at the sound of the ring and grabs the phone.
JOHN Hello?
JOHN Alright.
JOHN Thank you.
JOHN He hangs up, sees Jenny now standing in the doorway, tying her robe, looking at him anxiously.
JOHN (CONT'D) He's coming home.
As John pulls up.
He gets out of the SUV, walks around and opens the back window and now Marley sits up into view.
COLLEEN Marley's back!
COLLEEN John opens the tail gate just as the kids come rushing onto the porch, Marley's tail wagging as he's lifted out of the car and set on the ground, the kids now surrounding him...
Loft.
Downtown.
Full of unpacked boxes.
A mattress on the floor.
Expensive electronics sit atop their cartons.
John follows Sebastian on a "tour."
JOHN Nice place.
JOHN How long you been here?
SEBASTIAN Two years, little more.
SEBASTIAN Sebastian sees John looking at all of the unpacked boxes.
SEBASTIAN (CONT'D) I'm in and out of town so much I really haven't had a chance to settle in.
SEBASTIAN (CONT'D) I hired a decorator, but she and I got into a thing and it got messy--
JOHN Right.
SEBASTIAN Beer?
JOHN I can't, I still got one more interview to do.
JOHN Sebastian opens the fridge revealing nothing but beer and hunk of Parmesan.
SEBASTIAN What's the piece again?
SEBASTIAN Right, you told me that.
SEBASTIAN So you're down in Philly now, huh?
JOHN Just outside.
JOHN More space for the kids.
SEBASTIAN Whatta you got, five now?
JOHN Three.
JOHN Here's a picture of everybody...
JOHN John pulls a photo from his wallet, hands it to Sebastian.
Jenny's holding up.
JOHN Yeah, she's great.
JOHN And that's Colleen our youngest...
SEBASTIAN What's with the ladybug get-up?
JOHN Oh, yeah, that's a funny story.
JOHN She had done this pageant at her preschool two weeks before, but she didn't wanna take off the costume, plus Marley went ballistic for the antenna which is why it looks like he's trying to eat her head.
Yeah, that is funny.
So I was thinking later on maybe Thai?
There's this new place in the meat Packing District.
How's that sound?
Be just like old times.
John stands there a moment, feeling the distance between them.
JOHN Uh, well, actually I'm headed back home later today.
SEBASTIAN Oh.
JOHN In fact, I should probably get going...
SEBASTIAN Alright.
SEBASTIAN Good seeing you, man.
JOHN For sure.
SEBASTIAN Oh, hey, be sure to check out the Delegates Lounge at the U.N...
SEBASTIAN Great Mojitos, really hot interpreters.
JOHN Thanks for the tip.
JOHN And John goes out the door.
JOHN Sebastian takes out his blackberry, dials...
SEBASTIAN Hey, it's Sea-bass.
SEBASTIAN What're you up to tonight?
Oh.
No, that's cool.
Another time then.
He hangs up, stands there in the middle of his big, empty apartment a moment.
He then dials another number.
SEBASTIAN (CONT'D) Hey, it's Sea-bass.
SEBASTIAN (CONT'D) What's going on?
As a cab pulls away and John carries his suitcase up onto the porch.
John enters the house, sets down his suitcase.
JOHN Hello?
JOHN Anybody home?
He sees a note ("PICKING UP THE KIDS.
J"), and peers into:
Where Marley is up on his hind legs, eating something off the counter.
John puts his keys down, but Marley doesn't react.
John sneaks up behind him.
Marley keeps eating the grilled cheese sandwich off the plate...
JOHN (CONT'D) Marley?
JOHN (CONT'D) Hey, boy.
JOHN (CONT'D) Marley looks up briefly as if he heard something, but then returns to eating.
JOHN (CONT'D) John is right behind him.
JOHN (CONT'D) John reaches out and touches Marley, and Marley jumps, totally guilty.
JOHN (CONT'D) Then he turns and greets John.
JOHN (CONT'D) What's the matter, boy?
JOHN (CONT'D) You didn't hear me?
JOHN (CONT'D) Huh?
JOHN (CONT'D) He looks at the dog a moment, thoughtful, then...
JOHN (CONT'D) Let's go for a walk.
As John walks Marley off leash up a hill.
At one point, John has to stop and wait for Marley to catch up.
JOHN Come on, boy, just a little further to the top...
JOHN Marley comes up, panting, eyes wet and happy.
JOHN John looks at him, can see how tired he is.
JOHN (CONT'D) You know what, this is a good spot right here.
JOHN (CONT'D) John looks out at the valley below, settles down onto the damp earth beside Marley.
JOHN (CONT'D) Let's just sit for a while.
JOHN (CONT'D) The two of them sit there, looking out at the beautiful countryside below.
JOHN (CONT'D) John strokes Marley for a moment.
JOHN (CONT'D) Looks at the grey hair, the tired eyes that now look back at him.
JOHN (CONT'D) Hey.
JOHN (CONT'D) So...
JOHN (CONT'D) you're gonna tell me, right?
JOHN (CONT'D) When it's time?
JOHN (CONT'D) Because I don't wanna make that decision on my own.
JOHN (CONT'D) So you just let me know when you're ready, okay?
JOHN (CONT'D) Marley rests his chin on John's arm.
JOHN (CONT'D) Okay.
Jenny is at the top of the stairs.
JENNY Marley?
JENNY Have you seen him?
JOHN He's not up here.
207 John and Jenny find Marley lying peacefully in front of the dying fire.
JOHN I guess I could move his bed down here.
JOHN John sits down beside Marley.
JOHN (CONT'D) Man.
JOHN (CONT'D) He's always slept with us.
JOHN (CONT'D) Now he can't even make it upstairs.
JENNY He looks pretty comfortable to me.
I'll go get his bed.
JOHN Hey Jen?
JOHN why don't you grab a blanket for me, too.
JOHN She nods, starts back up the stairs.
JOHN John grabs a pillow from the couch and lays down beside Marley.
JOHN (CONT'D) This is a good spot.
JOHN (CONT'D) I may never sleep upstairs again.
JENNY Hey.
JENNY Scooch over.
JENNY He looks up and see that Jenny's brought a blanket.
JENNY She lies down with them.
JENNY John puts his arm around them both.
JENNY Marley's tail begins gently pounding the floor.
JENNY (CONT'D) Just like old times.
John sits across from his editor.
JOHN It'd be twice a week.
JOHN Six hundred words.
EDITOR And what's the subject?
JOHN Everyday stuff.
JOHN The stuff we all go through.
JOHN But funnier.
EDITOR I don't get it.
EDITOR I thought you came here to be a reporter.
JOHN I did, but I think we both know that isn't me.
JOHN I'm a columnist.
JOHN A good one.
JOHN A SECRETARY sticks her head in the office...
John-- your wife's on the phone.
She says it's important...
JOHN I'll be right there.
JOHN Think about it.
Jenny on the phone, looking out into the backyard.
JENNY I can't get him back inside.
JENNY He's lying out there in cold...
JENNY and he won't move...
Late afternoon.
John's car pulls up.
Jenny and Patrick are sitting on the floor.
Marley is lying on the dining room floor, breathing heavily.
JENNY Patrick came home and we got him here.
JENNY Dr. Platt said if he's comfortable, leave him here for a while and see.
JENNY But he's no better.
JENNY John kneels down by Marley, who looks at him but doesn't wag his tail or lick his hand.
JENNY He runs his hand over his coat - then over his stomach, the dog flinches.
JOHN I'm taking him in.
JOHN The kids all come into the room, Colleen carrying a stuffed sheep.
COLLEEN Is he sick again?
JOHN Yeah, he is, honey.
JOHN But I'm going to take him to the hospital and they'll try to make him better.
JOHN Conor bends down, nuzzles Marley's face.
CONOR Get better, Mar.
COLLEEN You can take Lamby, okay?
COLLEEN But don't chew her other ear off.
COLLEEN Patrick leans down, hugs Marley tightly and whispers right in
PATRICK Goodbye.
PATRICK When he looks up at his father, John can see that Patrick's crying, that he knows what the other two don't.
John lifts Marley out of the car.
Marley seems a little more alert.
JOHN You wanna walk?
JOHN He sets him down gingerly.
JOHN Hesitantly, Marley walks over to the tree that countless dogs have peed on, sniffs it, then looks around.
JOHN John looks around, too.
JOHN It's a crisp spring night in Pennsylvania.
JOHN Takes a breath...
JOHN (CONT'D) Nice night, huh?
JOHN (CONT'D) Marley looks around, then looks at John.
JOHN (CONT'D) There's something in his expression.
JOHN (CONT'D) John nods, knows what he's saying.
JOHN (CONT'D) Okay, boy.
JOHN (CONT'D) Okay.
JOHN (CONT'D) John, his heart breaking, bends down to carry Marley up the front steps of the clinic.
John stands as Dr. Platt comes out...
DR. PLATT I did everything that worked before.
DR. PLATT But no luck.
DR. PLATT There's still surgery,
JOHN --not strong enough.
DR. PLATT There's blood in his stomach.
DR. PLATT The lining might be compromised.
DR. PLATT I don't know what we'll find if we go in there anyway.
JOHN Can you give me a minute?
JOHN I need to...
JOHN I need to call my wife.
John's on his cell phone...
It's me.
It's the stomach thing again.
Nothing's working.
They could do surgery, but...
Jenny listens to John on the phone.
JENNY I know.
JENNY Jenny nods as tears come.
JENNY They stay on the phone, quiet,
just being with each other.
Finally:
JENNY (CONT'D) I love you, John.
I love you.
John enters.
Marley is on the table, zonked out.
Dr. Platt has put a blanket on the cold metal table so Marley is warm.
DR. PLATT I'll give you some time.
DR. PLATT She goes.
DR. PLATT John stares down at Marley.
DR. PLATT Takes the stuffed lamb out of his pocket, places it under a paw.
DR. PLATT When John puts a hand on his flank, Marley's eyes flutter open.
DR. PLATT His tail THUMPS gently.
JOHN Hey, buddy.
JOHN He pets Marley's head, runs his hands all over Marley's body.
JOHN His coat, still shedding.
JOHN His tail.
JOHN He takes up each paw, each ear, remembering and memorizing at the same time.
JOHN He leans down, puts his nose on Marley's neck and breathes him in.
JOHN Then he goes around, squats down so he's on Marley's level.
JOHN He looks into Marley's eyes.
JOHN (CONT'D) Listen, you know all that stuff we always said about you?
JOHN (CONT'D) What a total pain you are?
JOHN (CONT'D) The world's worst dog?
JOHN (CONT'D) Well, don't you believe it.
JOHN (CONT'D) Don't believe it for a minute.
JOHN (CONT'D) You loved us, every day, no matter what.
JOHN (CONT'D) And that's a pretty amazing thing.
JOHN (CONT'D) Look, I don't know where you're going
from here, but you remember this: You're a great dog, Marley.
You are a great dog.
In the BEDROOM, Jenny sits on the bed, the phone in her hand, waiting, we BEGIN PULLING AWAY DOWN THE HALLWAY.
Dr. Platt is in the room now.
John, his hand on one of Marley's paws, kneels on the ground, looking at Marley, Marley lays on the table, looking right back at him.
DR. PLATT He won't feel a thing.
DR. PLATT He'll just slip away.
DR. PLATT Are you ready?
JOHN We're ready.
JOHN Dr. Platt inserts the needle into the I.V. and presses the plunger.
As a pajama-clad Patrick slips a tape into the VCR...
As we now HOLD ON MARLEY'S EYES, slowly beginning to close.
As Jenny sits vigil by the phone, we CONTINUE PULLING BACK.
As Patrick sits alone in the dark living room, his face illuminated by the TV, as he watches SILENT IMAGES from Grogan family home videos: TWO-YEAR-OLD PATRICK rides on Marley's back through the house at 345 Churchill, young Marley's tail knocking over everything within range, toddler and dog both joyous.
As Marley's eyes finally close.
The CAMERA drifts to John's hand, stroking Marley's side.
Dr. Platt listens to Marley's heart and says:
DR. PLATT He's gone.
DR. PLATT FROM ABOVE, the dog on the table, the doctor discreetly going to the side, and John laying his head next to Marley and putting his arms around him as we now...
As the five Grogans walk across the-property.
Colleen sits on John's shoulders.
They reach a clearing where we see a small grave has been dug.
John sets Colleen down...
COLLEEN He's wrapped in his blanket...
JOHN So he'll be warm.
JENNY You guys want to read your letters?
COLLEEN Mine is a picture.
COLLEEN Of me and Marley.
COLLEEN And grasshoppers.
COLLEEN And ice cream.
COLLEEN Mommy wrote what I said.
COLLEEN "Dear Marley.
COLLEEN I will never forget you, forever."
COLLEEN And those are kisses.
JOHN It's beautiful, honey.
JOHN He'll like it.
JOHN Drop it in.
JOHN Conor?
JOHN Conor reads his piece of paper.
CONOR "Dear Marley.
CONOR I loved you all my life.
CONOR I hope you like heaven and that there's lots to chew on.
CONOR Your brother, Conor Richard Grogan."
CONOR John puts his hand on Conor's shoulder as Conor drops in the letter into the grave.
JENNY Patrick?
JENNY Do you want to say anything?
PATRICK He knows.
JENNY I'd like to give him something.
JENNY Jenny reaches behind her neck and unclasps the gold necklace John gave Jenny when she first got pregnant.
JENNY (CONT'D) This little necklace has been on quite a journey.
JENNY (CONT'D) John smiles at her, remembering.
JENNY (CONT'D) So much shared history.
JOHN Your dad gave this to me to celebrate the beginning of our family.
JOHN But you know what?
JOHN Our family had already begun.
JOHN She looks into the grave, gently sets the necklace atop the blanket, lets her hand rest there a moment, then stands up.
JENNY Good-bye, Clearance Puppy.
John puts few big stones on top of the tamped-down earth.
He sits on his haunches beside the grave, looks up at the house across the yard.
All lit up.
We see the kids sitting by the fire while Jenny moves about the kitchen getting dinner ready.
John sits there watching them.
watching his family.
The family that both he and Marley grew up in.
He gives the fresh dirt a final, loving pat and then, as the last bit of sun goes down, he stands up, and heads for home.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
