BLACK SWAN
Written by
Mark Heyman, Andres Heinz & John McLaughlin
January 11, 2010
A SPOTLIGHT slices black space.
In its beam, a DANCER materializes.
She is fair-skinned.
Beautiful and pure.
The maiden twirls on pointe, a smile on her face, light as air and carefree.
She pauses, her face grows worried.
Sensing someone watching.
Scared, she peers into the darkness.
She moves now, looking, growing more frantic.
Then, a SINISTER MAN emerges out of the darkness behind her.
She stumbles backwards, frightened.
She tries to escape, twirling away, but he pursues.
His true form is revealed, the demon ROTHBART.
He flings his open hand towards her, casting the spell.
She wants to scream, but nothing comes out.
She looks at her body, sensing something happening to her.
Something terrifying.
She spins, panicking, but it's too late.
She disappears beneath the beast's cape.
She emerges as the WHITE SWAN, the iconic protagonist of SWAN
In the darkness, a pair of EYES.
They belong to NINA, the same dancer.
She lies awake in bed, thinking about her dream.
The room looks like it hasn't been redecorated since she was a teenager.
Stuffed animals.
Dolls.
Pink and frilly.
The door opens, throwing LIGHT on her face.
Nina looks towards the door and smiles softly at whoever opened it.
Nina sits up and hangs her BARE FEET off the side of the bed.
Like all ballerinas, she's beautiful and her feet are atrocious.
Covered in corns, broken blisters and bunions.
She arches them, doing her first extensions of the day.
The room is empty of furniture to leave space for dancing.
A large mirror covers the opposite wall entirely.
Nina rubs her knees to get them warm, and then begins her morning exercises, extending and contracting her feet and legs in precise and rhythmic motions.
The skin on her chest stretches tautly over her sternum.
Defined vertebrae run up her back, sinewy muscles contract as she moves.
Her slender neck leads into her hair, contained in a ballerina's bun.
Nina looks serene as she moves, completely in her element.
She hears someone fussing about in the kitchen.
I had the most amazing dream last night.
I was dancing the White Swan.
No answer.
NINA (CONT'D) Different choreography, like the Bolshoi's.
NINA (CONT'D) It was the prologue, when Rothbart casts his spell.
NINA (CONT'D) Nina continues to stretch.
Nina sits at the table.
An older woman, ERICA, places a POACHED EGG and a QUARTER-GRAPEFRUIT in front of her.
ERICA You're in a good mood.
NINA I'm just excited to get back.
ERICA Off-season always makes you grumpy.
Look how pink.
So pretty.
Pretty.
Pretty.
They giggle and Erica resumes packing Nina's shoulder bag with extra clothing, shoes, snack filled tupperware, duct tape, ribbon, thread, etc.
NINA (CONT'D) Plus he promised to feature me more.
ERICA He certainly should.
ERICA You're the most dedicated dancer in the company.
Nina smiles, comforted, and begins taking her vitamins.
Erica walks over with a SWEATSHIRT and holds it above her.
Nina pulls it over her head and starts to push her arms through the sleeves.
What's that?
NINA What?
ERICA There.
Erica points to her shoulder.
Nina feels and finds a small
She shrugs and shakes her head.
Erica gives her a suspicious look, but lets it go and smiles.
Nina finishes pulling down the sweatshirt.
Erica hugs Nina into her chest and kisses the top of her head.
ERICA (CONT'D) Sweet girl.
Nina rides inside a crowded subway, staring absentmindedly at her faint reflection in the train's window.
Suddenly, another train roars by on the opposite track, snapping her awake.
In the next train car, she sees the back of a BALLERINA standing in the midst of the crowd.
Her head bops to music playing through iPod earphones.
Nina moves a strand of hair out of her eyes, and at that exact moment, the girl in the next car moves in the same way.
Mirroring her.
Unnerved, Nina slowly lowers her arm.
So does the other girl.
Although Nina can't quite see her face, the girl seems IDENTICAL from Nina's vantage point.
The train jerks to a stop as it arrives at a station.
Nina sees the girl head to the exit.
She cranes to see her face, but her view's obscured.
The doors slide shut and the train pulls out.
Nina watches the platform whisk by, keeping her eyes peeled, but she doesn't see the girl.
Nina emerges from the subway station onto a city street.
She arrives at the MAJESTIC-LOOKING THEATER, where a few other BALLERINAS likewise trickle towards the entrance.
They all look strangely similar: slender, carrying shoulder bags, wearing leggings and loose sweatshirts.
She passes a ROW OF POSTERS featuring the company's prima ballerina, BETH MACINTYRE.
Nina looks at them, a little envious, before continuing on to the STAGE DOOR.
Crammed into a single dressing room, Nina and the company's 5 SOLOISTS get ready for rehearsal.
Chatting, sewing ribbon onto shoes, applying makeup, putting band-aids on blisters.
Nina removes a new pair of BALLET SHOES, admires them for a moment, before cutting off the satin toe with scissors.
In the background, catty VERONICA and Russian GALINA gossip.
VERONICA Can't believe she's back.
GALINA Of course she is.
VERONICA She can't take a hint?
VERONICA Company's broke.
VERONICA No one comes to see her anymore.
SOLOIST 1 No one comes to see ballet period.
VERONICA That's not true, I heard the Royal had one of their best seasons yet.
GALINA He needs to try something new.
VERONICA No, someone new.
SOLOIST 1 Like who?
VERONICA Like someone who's not approaching menopause.
They snicker.
NINA I think it's sad.
VERONICA What's sad?
NINA Beth's such an amazing dancer.
GALINA So's my grand-mother.
NINA Fonteyn danced into her 50's...
Yeah, we know.
Irked, Nina starts POUNDING the shoes against the floor to soften the toe.
Her eyes are drawn to a NEW GIRL standing in the doorway.
Nina pauses to scrutinize her.
She wears vampy make-up, hair down.
Dark and sexy.
NEW GIRL Soloists?
Wary, the girls mumble mmm-hmm's and nod.
NEW GIRL (CONT'D) Great.
She slinks past the suspicious group of girls and plops down at an open spot.
NEW GIRL (CONT'D) Fucking got off the wrong stop and had to hoof it from 79th.
NEW GIRL (CONT'D) The new girl notices the looks, smirks to herself and starts getting ready.
Nina wears a look of intense concentration as the entire company warms up, including the pubescent CORPS MEMBERS and a handful of MALE DANCERS.
LEGS, HANDS, and FEET repeat the same movements all around her, led by a severe BALLET MISTRESS.
To the back, fondu, to the back, plie.
Fourth, fourth, and one and fifth, to the back...
Like this.
Push it.
Why can't you do this?
Using the mirror, Nina monitors her movements carefully.
The mistress surprises her.
It needs to be looser.
Relax.
Let it flow.
Flustered, Nina nods and tries to follow her instruction.
Suddenly, the girls around Nina begin stripping off their sweatshirts and insulated pants.
Nina sees that the intense and brooding director of the company, THOMAS LEROY, has entered the space.
He has the unkept look of an artist.
Magnetic and intense.
The ballerinas remove their warm-up gear to show off their bodies.
Leroy walks around the room, judging his flock.
Smiles and glances are thrown his way.
He goes up to the ballet mistress, takes her hand and kisses her on the cheek.
Even she manages a smile.
He heads to the line of soloists, studying them.
LEROY We all know the story: virginal girl, pure and sweet, trapped in the body of a swan.
LEROY She desires freedom, but only true love can break the spell.
He taps a dancer on the shoulder, she lights up.
He walks, then taps another.
A selection process of some kind.
Nina looks nervous, has an inkling of what it means.
LEROY (CONT'D) Her wish is granted in the form of a prince.
He nears Nina.
She sneaks peeks at him, eager and hopeful.
He acknowledges her with a small nod and a smile.
But he walks on without tapping her.
She deflates.
LEROY (CONT'D) But before he can declare his love, her lustful twin, the Black Swan, tricks and seduces him.
He approaches the New Girl.
Nina watches, threatened.
But he doesn't tap her either.
LEROY (CONT'D) Devastated, the White Swan leaps off a cliff, killing herself.
LEROY (CONT'D) But, in death, finds freedom.
He taps one more soloist and then CLAPS.
The music stops and all the girls face him, attentive.
LEROY (CONT'D) Good morning, company.
They respond "Good morning" in nervous, unsure voices.
LEROY (CONT'D) We open our season with Swan Lake.
LEROY (CONT'D) Done to death, I know.
LEROY (CONT'D) But not like this.
LEROY (CONT'D) We strip it down.
LEROY (CONT'D) Make it visceral and real.
He pauses for effect.
LEROY (CONT'D) And a new production needs a new Swan Queen.
LEROY (CONT'D) A fresh face to present to the world.
Surprised, the soloists glance at each other, trying to keep their cool.
LEROY (CONT'D) But which of you can embody both swans?
LEROY (CONT'D) The white and the black?
Nina prepares for disappointment.
LEROY (CONT'D) All the soloists I touched...
LEROY (CONT'D) Please go to your scheduled rehearsals this afternoon.
The girls are confused.
LEROY (CONT'D) And the girls I didn't touch, meet me in studio B at five.
Hidden inside a nook, Nina has her eyes closed, nervously HUMMING the score to Swan Lake.
She makes small motions with her feet and hands, going through the choreography in her mind.
Preparing for the audition.
A loud CRASHING sound snaps her out of it.
She goes out into the hallway to investigate.
The door to a PRINCIPAL DRESSING ROOM is halfway open.
Nina cautiously approaches.
Inside, she can see someone moving around the room in a fury, trashing it.
Suddenly, the door swings open and BETH MACINTYRE bursts out.
She makes brief eye-contact with Nina.
BETH What?!
Nina just shakes her head.
Beth scoffs as she slams the door behind her.
She clips down the hall in the opposite direction.
Nina waits until she's gone, then moves closer to the door and peeks inside, curious.
She checks to make sure no one's around and quickly enters.
Large and comfortable.
Beth's presence is everywhere.
Photographs, clothing, and personal belongings scattered across the space.
Nina looks at herself in the mirror and smiles, imagining how great it would be...
Then she notices a LARGE VASE lying on the floor.
The flowers have been shredded, water everywhere.
She moves to the vanity counter and touches Beth's belongings in reverence.
The items are neatly laid out: ballet supplies, jewelry, and makeup.
Her fingers brush a tube of LIPSTICK.
She picks it up.
Nina slips the lipstick into her bag and exits the room.
In the middle of her audition, Nina dances Odette's Variation from Act II of the ballet, a frightened look on her face.
Although her movement is incredibly precise, there's a definite vulnerability.
Exactly as the White Swan should be: fear tinged with melancholy.
Leroy waves his arm.
The music and Nina stop abruptly.
He approaches her and, when he gets close, taps on her sternum with two of his fingers.
LEROY So Nina, would you like to be the Swan Queen?
NINA If you want me to be.
He leans in and talks softly so the other girls can't hear.
LEROY Well, if I was just casting the White Swan, she'd be yours.
She can't help but smile, flattered.
He pulls away from her.
LEROY (CONT'D) But I'm not.
He turns to the PIANO PLAYER.
LEROY (CONT'D) Maestro, Odile's Coda.
The piano player rifles through the song book.
LEROY (CONT'D) Show me your Black Swan, Nina.
Nervous, she glances over at Veronica and Galina, who anxiously await their turn.
She takes a few breaths, then looks towards the piano player and nods.
The music begins.
Nina dances a few steps, and then launches into the most difficult and famous part of Swan Lake: The Black Swan's Coda.
It consists of 32 consecutive fouettes (spins).
LEROY (CONT'D) Come on, not so controlled.
The music builds in intensity, she pushes herself into the next turn.
LEROY (CONT'D) Seduce us!
LEROY (CONT'D) Not just the Prince, but the court, the audience, the entire world!
LEROY (CONT'D) The fouettes are like a spider spinning her web.
LEROY (CONT'D) Come on!
LEROY (CONT'D) Attack it!
LEROY (CONT'D) Attack it!
Leroy runs his hand through his hair, dismayed.
A look of worry spreads across Nina's face.
Knows she's blowing it.
The door CLANGS open and throws Nina's focus completely.
She stumbles, several spins short of finishing.
The New Girl obliviously marches into the room, listening to an iPod.
Good of you to join us.
The New Girl notices everyone staring and pulls out her earphones to talk.
NEW GIRL Sorry.
LEROY Girls, this is Lily.
LEROY Straight off the plane from San Francisco.
LEROY She's filling Rebecca's old spot.
LILY gives a small wave.
Nina eyes her with scorn as she catches her breath.
LEROY (CONT'D) Go on, get warmed up.
LILY I'm good.
Lily starts stripping off her layers, revealing her lithe body.
On her back, she has a TATTOO OF LILIES.
NINA Should I go again?
LEROY I've seen enough.
LEROY Thank you, Nina.
She looks down, getting his meaning.
LEROY (CONT'D) Okay, Veronica.
LEROY (CONT'D) Your turn.
LEROY (CONT'D) The White Swan's variation...
Furious, Nina marches out of the room.
A13 INT.
THEATER BATHROOM STALL - NIGHT A13
Nina stands up from a kneeled position and flushes the toilet.
She wipes her mouth with the back of her hand and exits the stall.
Nina walks along a quiet side street.
She clutches her jacket, for warmth and comfort.
Her CELL PHONE starts ringing.
She digs it out of her bag and checks the CALLER ID: MOM.
She silences it and puts it away.
Up ahead, she sees the sidewalk dead end at a construction site, and detour into an enclosed PASSAGEWAY beneath the scaffolding.
Nina slows, a little scared, but decides to push on.
The passageway is dark.
The temporary lighting dim and flickering.
She walks quickly, trying to get to the other side.
She hears the sound of soft FOOTSTEPS approaching.
She stops, and the other FOOTSTEPS stop.
She looks up and sees the faint outline of a SLENDER WOMAN standing there, almost ghostlike.
Nina starts walking again, keeping her head down, and the other woman continues as well.
As they pass each other, Nina glances at the woman's face and discovers...
The woman looks EXACTLY LIKE HER.
But the moment passes as the woman continues walking.
Nina stares after her, perturbed.
Her cell phone starts RINGING again, piercing the silence.
Nina continues out, ignoring the phone.
Nina enters and locks the deadbolt and chain-lock behind her.
She turns and is startled to see Erica standing right there.
ERICA How did it go?
Nina looks at her confused.
Erica helps take off her coat.
ERICA (CONT'D) You were late, so I called Susie in the office.
ERICA (CONT'D) An audition?!
ERICA (CONT'D) Can't believe he just sprung that on you.
Nina nods.
ERICA (CONT'D) So?
NINA It went okay.
ERICA Just okay?
Erica hangs up her coat, turns and sees Nina tearing up.
ERICA (CONT'D) Darling?
ERICA (CONT'D) Erica goes to her and wraps her in an embrace.
ERICA (CONT'D) Shhh, shhh, tell me what happened.
Nina lies on the floor, stewing.
Her legs straight in the air to drain the lactic acid in her muscles.
I told them it doesn't matter how talented their daughter is, if she misses any more classes, she's out.
She forgets half of what I teach her, and I waste time catching her up.
It's ridiculous.
Nina sits up and retrieves a pair of point shoes from her bag.
She considers them for a moment, then starts to put them on.
She stands, takes a breath, and does a single spin, testing the waters.
She takes a breath and spins again, then again, then again.
Each spin is punctuated by a jab of her foot into the floor.
She jabs her toe down, hard...
NINA Ow!
She winces in pain and automatically grabs her foot.
ERICA Everything alright?
NINA I'm fine!
NINA Nina breathes through the pain and puts her shoe back on.
NINA Her toe jabs into the floor.
NINA She winces a little with pain, but keeps pushing.
NINA She starts to look powerful, willing herself to succeed.
At the end of the 32nd spin, Nina jabs her foot down hard.
She's done it!
Nina looks at herself in the mirror, glazed in sweat, a slight smile of satisfaction.
Nina sits on the edge of the bed, as Erica douses some GAUZE with PEROXIDE and dabs it on the split toenail.
Nina reacts to the sting.
ERICA Shhh.
ERICA Almost done...You're working yourself too hard.
ERICA We all have off days.
NINA If that girl hadn't barged in.
ERICA I'm sure she didn't mean to.
ERICA Remember when you started?
ERICA If I hadn't taken you to each of your classes, you would have been completely lost.
NINA I'm gonna talk to him.
NINA Tell him I finished it.
ERICA He knows you can do the coda.
ERICA It won't convince him one way or the other.
Annoyed, Nina lies down, looking away from her mother.
ERICA (CONT'D) Oh, sweetheart, I know it's disappointing.
ERICA (CONT'D) When you start to get older, there's all this ridiculous pressure.
ERICA (CONT'D) God knows, I understand.
Erica squeezes some arnica gel into her palm and massages it into Nina's calves.
ERICA (CONT'D) But it's alright.
ERICA (CONT'D) No matter what.
ERICA (CONT'D) You'll probably get to dance the Pas de Quatre again.
ERICA (CONT'D) That's such a wonderful part.
ERICA (CONT'D) Or maybe he'll make you a Big Swan.
ERICA (CONT'D) Either way, you'll shine.
NINA I know, mom.
Erica removes Nina's EARRINGS, then opens a JEWELRY BOX sitting on the night stand and drops them inside.
A TOY BALLERINA spins to TINNY MUSIC.
Nina gets under the covers.
Erica tucks her in and sits down on the edge of the bed.
ERICA Everything will be better in the morning.
ERICA It always is.
ERICA Nina watches the ballerina spin and spin with a determined stare.
Nina applies the lipstick she stole from Beth, using the side window as a mirror.
The jerky motion of the train makes it difficult, but she manages.
Nina waits anxiously outside Leroy's office.
She hears someone approach, looks up and sees Leroy coming down the hall.
She puts on a nervous smile.
He doesn't reciprocate.
LEROY Yes, Nina?
NINA Do you have a minute?
NINA She takes a breath and then follows.
Nina closes the door and faces the cozy, dark space.
Large couch, posters from the ballet on the wall--several featuring Beth.
Leroy lights a cigarette, quietly studying her and not making this easy.
He takes a drag, and exhales.
NINA If now's not a good time...
LEROY Now's fine, what is it?
NINA I just wanted to tell you, I practiced the coda last night, and I did it.
LEROY How thrilling for you.
Well...
LEROY Okay, Nina, listen, I honestly don't care about your technique, you should know that by now.
NINA Yes, but-
LEROY Anyway, I've already chosen Veronica, so...
He lifts his hands in the air, "there you go."
I see.
She makes a move towards the door.
LEROY You're not going to try and change my mind?
She looks back at him, uncertain.
Leroy nonchalantly stubs out his cigarette.
LEROY (CONT'D) You must have thought it was possible, coming to find me like this.
He pauses, looks her up and down as if trying to decipher her.
LEROY (CONT'D) Why are you here?
LEROY (CONT'D) All dolled up?
I came to ask you to give me the part.
LEROY That all?
She doesn't know what he means.
He comes around his desk and approaches her.
LEROY (CONT'D) Truth is, when I look at you, all I see is the White Swan.
LEROY (CONT'D) Yes, you're beautiful, fragile, fearful.
LEROY (CONT'D) Ideal casting.
LEROY (CONT'D) But the Black Swan...it's a hard fucking job to dance both.
NINA I can be the Black Swan too.
LEROY Really?
LEROY She's hungry, volatile.
LEROY In four years, every time you dance, I see you obsess over getting each move exactly right, but I never see you lose yourself.
Insecure, she looks like she wants to run out of the room.
LEROY (CONT'D) All that discipline, for what?
NINA I want to be perfect.
He laughs.
LEROY Perfection's not just about control.
LEROY It's also about letting go.
LEROY Surprising the audience.
LEROY Surprising yourself.
LEROY Transcendence.
He considers her for a moment.
LEROY (CONT'D) Very few have it in them.
Without warning, he slowly plants a kiss on her mouth.
It lasts for a moment, but he suddenly jerks away.
LEROY Ow!
LEROY Fuck!
He touches his lip, stunned.
LEROY (CONT'D) You bit me.
She's too scared to respond.
I can't believe it.
That fucking hurt.
He goes to the mirror to check for damage.
He glances back at Nina.
Sorry.
She quickly leaves, shell-shocked.
The company stretch and go through their usual warm-up routine, a tension in the air.
The casting decision still uncertain.
Nina touches her lips, thinking about the encounter.
Then looks over at Veronica, knowing the good news in store.
Veronica notices.
Nina looks away.
What?
Nina shakes her head.
A sudden energy sweeps the room, and she hears the sound of scuffling feet and whispering.
"It's up."
"She just posted it."
"C'mon."
The dancers start exiting into the hallway.
Veronica turns to follow.
NINA Veronica?
Veronica turns around.
It's hard, but Nina decides to be a good loser.
NINA (CONT'D) Congratulations.
NINA (CONT'D) She excitedly pushes through the crowd of girls, wanting to see for herself.
Knowing the outcome already, Nina continues stretching in the deserted space, resigned to her fate.
She finishes, grabs her belongings and walks out.
A crowd of dancers surround the bulletin board, jostling to get a look.
Nina starts walking down the hall in the opposite direction.
Behind her, she can hear a small commotion and then:
VERONICA Why did you tell me that?
She turns and sees Veronica, her face flushed with anger.
Your idea of a joke?
What?
VERONICA Fuck you.
VERONICA The group of girls stares at Nina, making her very self- conscious.
VERONICA First a few, then more and more of the girls smile at her.
VERONICA They make room for her as she pushes through.
She finally gets to the CASTING NOTICE, finds "Swan Queen"
Stunned, she turns around to face the mass of ballerinas.
She sees Lily eyeing her with a flat expression, which turns into a smile to mask her disappointment.
The other girls start congratulating and hugging Nina, some more sincerely than others.
Nina bursts in through the door and heads directly for one of the stalls.
She locks herself in for privacy and dials a number on her CELL PHONE.
She holds it to her ear, anxiously waiting for the person to answer.
NINA Hey...Everything's fine...He picked me, mommy.
She waits for a response.
NINA (CONT'D) Did you hear me?...Yes, I'm going to be the Swan Queen.
Nina laughs at her mother's response and can't help but start crying.
NINA (CONT'D) I'll be home soon, okay?
NINA (CONT'D) I just had to tell you.
NINA (CONT'D) She wipes the tears off with the back of her hand and pulls herself together.
NINA (CONT'D) She comes out of the stall...
Horrified to discover "WHORE" written on the mirror in RED
Nina looks around the bathroom, to make sure she's alone.
She snags a paper towel and wipes off the insult, smearing the mirror with red streaks.
Nina unlocks the door to the apartment.
NINA Mom?
Nina opens the door and pokes her head in.
But Erica's not in there either.
Nina glances at the walls.
Where several homemade PAINTINGS hang, all of the same subject: Nina as a young girl, posing in a tutu.
On a desk, the ORIGINAL PHOTOGRAPH is clipped to a painting in progress.
Out of the corner of her eye, one of the portraits seems to shift.
Nina turns towards it, but the painting's now perfectly still.
Unsettled, Nina withdraws.
Post-shower, Nina's fuzzy reflection stares back in a steam covered mirror.
Nina takes her hand and wipes a streak across, to see herself more clearly.
She looks nervous.
The enormity of what's in front of her setting in.
She turns side-to-side, scrutinizing her body.
She lifts her arm and pinches the skin to check her weight.
She notices a small cluster of RED BUMPS on her shoulder.
A small RASH.
She feels the bumps with her fingers, bothered.
She checks the same place on her other shoulder.
There's no rash, just faint streaks of SCAR TISSUE.
Nina slides the hamper in front of the door to block it.
In the mirror now, one of the bumps is scratched and bleeding.
Nina quickly wipes the blood off with her finger.
The sound of the front door opening steals her attention.
Nina exits the bathroom wearing a robe.
In the kitchen, she sees a CAKE with a lit SPARKLER sitting on the table.
Her mother smiles anxiously.
ERICA My daughter, the Swan Queen.
ERICA She looks at the cake.
ERICA It has a ballerina sketched with frosting.
ERICA Nina hides her disdain.
NINA Oh, mom.
ERICA It's our favorite, vanilla with strawberry filling.
Erica picks up a knife and slices into the cake.
NINA Just a little piece.
Erica ignores her and starts cutting a very large piece.
NINA (CONT'D) That's way too much.
ERICA It's a celebration.
NINA My stomach's still in knots.
Fine then.
Erica grabs the whole cake and heads towards the trash.
Mom, don't.
I'm sorry.
Erica hesitates, but returns.
She sets the cake back down.
ERICA I'm just so proud of you.
Erica lifts the slice onto a plate.
NINA It looks yummy.
First day in the new role, Nina stretches alone.
Muffled sounds of other ballerinas chatting and giggling drift in from the large rehearsal space.
Makes Nina feel a little isolated.
DAVID Hey there...
Nina turns and sees DAVID, the high-cheeked, cocky dancer playing Prince Siegfried.
It is so full, where do I stand.
It is his version of a joke.
Nina politely laughs.
NINA Yeah...good luck finding a spot.
DAVID I am David.
NINA I know you are.
NINA I'm Nina.
DAVID Yes.
DAVID Here we go, huh?
David dances around the space, miming a hunt with a cross- bow.
Nina enters, stretches her body to illustrate her transformation into human, then sees David and acts spooked.
She dances away from him, a scared look on her face, undulating her arms to resemble a bird's flapping.
David gives chase, but Nina spins out of his grasp, disentangles from him.
But he eventually snags her, and they come very close together.
LEROY Okay!
LEROY The Russian ballet mistress nods and smiles, clearly pleased.
LEROY (CONT'D) Okay, Nina.
LEROY (CONT'D) Very good.
Nina smiles, relieved.
Leroy hops out of his chair and approaches.
LEROY (CONT'D) But I knew the White Swan wouldn't be a problem.
LEROY (CONT'D) The real work will be your metamorphosis into the Black Swan.
NINA Okay.
LEROY I saw a flash of her yesterday.
LEROY Get ready to show me more of that bite.
Nina takes a drink from the water fountain.
She hears music emanating from the large rehearsal studio.
Curious, she walks to the open doorway and stops to watch.
CORPS MEMBERS and a few soloists form two lines on both sides of the room.
In the middle, Veronica dances along with Lily.
Nina pays close attention to Lily, sizing her up.
Her dancing is explosive, exudes sex.
LEROY Watch the way she moves...
Leroy has snuck up behind Nina at the doorway and gets very close to her.
LEROY (CONT'D) Imprecise, but sensual.
LEROY (CONT'D) She's not faking it.
LEROY (CONT'D) Pay attention.
LEROY (CONT'D) Nina stares at her, attracted and threatened.
A35 INT.
PRINCIPAL DRESSING ROOM - DAY A35
The company's administrator, SUSIE, shows Nina into the room.
SUSIE You share with Beth from now on, so be considerate.
NINA Thanks, Susie.
Awed, Nina looks around the room.
She scans Beth's photographs and personal belongings, and lands on a large bouquet of FRESH FLOWERS.
SUSIE Those are for you.
SUSIE From Mr. Leroy.
NINA Beautiful.
NINA Nina pulls a card out from the flowers and reads.
NINA A faint smile curls her lips.
Leroy pulls Nina through a fundraiser gala, filled with rich looking PATRONS and some DANCERS from the company.
Bewildered, Nina takes in her high-society surroundings, getting the occasional curious glance as she passes.
Leroy grabs a couple CHAMPAGNE glasses off a WAITER'S tray.
He hands a glass to Nina with a smile.
He leads her up a staircase to a landing that overlooks the party.
LEROY Ready to be thrown to the wolves?
LEROY We need their cash, so smile.
She smiles, as instructed.
LEROY (CONT'D) Ladies and gentlemen, good evening.
The crowd turns their gaze towards them.
All eyes on her.
LEROY (CONT'D) As I stand here tonight, I see so many familiar faces.
LEROY (CONT'D) Your contribution to the art we all cherish profoundly goes straight to my heart and I am very grateful.
Polite applause.
LEROY (CONT'D) Let me begin with a very important announcement.
LEROY (CONT'D) You all have had the chance to be enchanted, transported, sometimes devastated by the performances of this true artist of our company.
LEROY (CONT'D) She has been an exceptional inspiration to my work, a role model to our dancers and a deeply satisfying presence on our stage.
LEROY (CONT'D) You all know who I am talking about...Beth Macintyre
More applause.
Nervous, Nina unconsciously picks at her cuticles.
LEROY (CONT'D) As we all know, every great career comes to an end.
LEROY (CONT'D) Beth is retiring at the end of the season.
LEROY (CONT'D) She will be giving her farewell performance as Melpomene, the role she originated in my first ballet.
People start whispering, stunned by the news.
Nina sees Beth in the crowd, giving a sad smile to the surrounding guests.
Trying to remain dignified.
LEROY (CONT'D) She will be greatly missed, but she will always be remembered.
LEROY (CONT'D) My little princess.
Amidst the mummering, Nina sees Beth quietly sneak out of the crowd and out the front door.
Leroy quickly covers.
LEROY (CONT'D) But as we bid adieu to one star, we welcome another!
He looks at Nina.
She stops picking her nails, self- conscious.
LEROY (CONT'D) As you know, we open our season with my new version of Swan Lake.
LEROY (CONT'D) Taking the role of our new Swan Queen is the exquisite Ms. Nina Sayers.
LEROY (CONT'D) Nina steps forward and curtseys.
LEROY (CONT'D) Someone seems to GIGGLE at her.
LEROY (CONT'D) Insecure, Nina glances towards the source and sees Lily flirting with a RICH GENT, uninterested in the official proceedings.
LEROY (CONT'D) Soon you will have the pleasure of seeing her perform, tonight we raise a glass.
LEROY (CONT'D) To all of you, to Nina, to Beth, to beauty!
PARTY GUESTS surround Nina and Leroy, trying to meet the company's newest star.
Nina basks in all the attention.
LEROY Dr. Brinson and his lovely wife, Ellen, tonight's sponsors.
She shakes DR.
BRINSON'S hand and curtseys to MRS.
BRINSON.
NINA Such a beautiful event.
MRS. BRINSON Not as beautiful as you, dear.
Nina demurs.
They're replaced by another HUSBAND and WIFE.
LEROY And this is Mr. and Mrs. Stein.
LEROY Leroy leans in and whispers in her ear.
LEROY (CONT'D) Relax, you're doing great.
Nina washes her hands.
She looks at herself in the mirror and takes a deep breath.
Someone KNOCKS on the door.
NINA Just a second.
NINA She checks her finger.
NINA No blood, but there's a HANGNAIL.
NINA Accidentally tearing a strip of skin from the nail to her second knuckle.
More KNOCKING startles her.
LILY Come on!
LILY I'm about to burst!
LILY She opens the door.
Lily pushes in.
LILY (CONT'D) Hey!
LILY (CONT'D) Look who it is.
Lily closes the door behind her and locks it.
LILY (CONT'D) I'm Lily, by the way.
LILY (CONT'D) Don't think we've officially met.
Nina.
LILY Our New Swan Queen!
LILY That is so huge!
LILY You must be freaking out.
NINA Yeah...
Lily slides her PANTIES out from under her dress and puts them in her clutch.
NINA (CONT'D) I should probably get back.
LILY Stay.
LILY Keep me company.
Lily starts to refresh her makeup.
Nina stays put for a second, uncertain.
NINA Excuse me.
She opens the door and steps out, where she's immediately met by Leroy.
LEROY Ah, there you are.
Leroy escorts Nina out.
It's a couple hours later and she's tipsy.
She stumbles a little and grabs onto Leroy.
NINA I think I drank too much.
NINA All those toasts...
LEROY You did well.
NINA Really?
LEROY They tried to eat you alive, but here you are, in one piece.
I guess.
LEROY I'll get you a cab.
LEROY Where you going?
NINA Oh, Upper West Side.
LEROY Why don't you come to my place first?
LEROY It's on the way.
She gives him a coy glance, reading between the lines and hiding her excitement.
LEROY (CONT'D) For a drink.
LEROY (CONT'D) Unless you've had enough.
NINA No, that's good.
He starts to look for a cab.
MRS. BRINSON Thomas!!!
They turn, see Mrs. Brinson, the host of the party, standing at the door.
You need to say hello to Karen Halloway before you disappear.
She's from Texas.
Correction: she is Texas.
A minute more of ass-kissing.
Wait here.
He runs back inside to say his goodbyes.
Nina smiles after him, giddy and anxious.
She notices a slender figure watching her from the shadows of the adjoining doorway.
In the dark, she looks like Nina.
Hello?
Spotted, the figure backs up, seeming to disappear.
Nina cautiously approaches, but can't see anyone.
She gets closer to the doorway...and someone JUMPS OUT, startling her.
It's Beth, drunk and shivering.
Cheeks streaked with mascara.
NINA (CONT'D) Beth?
NINA (CONT'D) What are you doing out here?
Beth stares her down.
Nina backs up, nervously grabbing her earlobe.
NINA (CONT'D) I was crushed to hear that you're leaving.
BETH What'd you do to get the role?
Nina shakes her head, confused.
BETH (CONT'D) He always said you were a frigid little girl.
Her words needle Nina, too close to the truth.
BETH (CONT'D) So what did you do to make him change his mind?
BETH (CONT'D) Suck his cock?
NINA Some of us don't need to do that.
Nina's struck a nerve.
Beth starts to come at her.
BETH You fucking little whore.
Beth, I'm-
LEROY What's going on?
They both turn to see Leroy returned.
BETH I need to talk to you.
LEROY You're drunk.
LEROY You should go home.
BETH Don't do that!
BETH Don't just dismiss me!
Poor, poor little princess.
Try to hold it together.
BETH I'm going to drop by later, okay?
BETH I have something I want to give you.
Come on.
He puts his arm around Nina, starts to lead her away.
BETH A token of my appreciation.
He ignores her and raises his arm to hail a cab.
As they enter the cab, Beth calls after them.
BETH (CONT'D) Make the most of it Nina.
Tasteful but spare loft.
Modern and expensive furniture.
Large windows.
Nina stands alone, looking around his inner sanctum, wide- eyed.
She explores the pieces of art, the furniture.
She touches some of it, in awe.
LEROY Here.
She turns, finds Leroy holding out yet another flute of champagne.
For himself, a scotch.
NINA Thanks.
NINA Confused, she sits across from him, alone on the large couch.
He takes an unceremonious sip of his drink and studies her.
Uncomfortable, she takes a drink as well.
LEROY I thought it'd be good to talk about the role.
LEROY Ground us a little.
NINA Yes.
LEROY The better we get to know each other, the more productive we'll be.
LEROY I don't want there to be any boundaries between us.
NINA Me neither.
LEROY Good.
LEROY So, do you have a boyfriend?
She's caught off guard by his question and just smiles uncomfortably.
He waits for an answer.
Finally she manages a reply.
NINA No...
LEROY Have you had many in the past?
NINA A few.
NINA But no one serious.
LEROY You're not a virgin, are you?
Her expression sours at this line of questioning.
She shakes her head.
LEROY (CONT'D) Then there's nothing to be embarrassed about, is there?
LEROY (CONT'D) And you enjoy making love?
NINA Excuse me?
LEROY Sex.
LEROY Do you enjoy it?
Blushing and feeling awkward, she takes a sip of champagne.
LEROY (CONT'D) We need to be able to talk about this.
NINA Okay.
LEROY So?
Nina looks at him, embarrassed, and shrugs.
He smirks, and joins her on the couch.
LEROY (CONT'D) I have a homework assignment for you.
NINA Yes?
LEROY Go home and masturbate.
LEROY Live a little.
She blanches, scandalized.
He finishes off his scotch and stands.
LEROY (CONT'D) It's late.
LEROY (CONT'D) Lots of work tomorrow.
LEROY (CONT'D) The doorman will find you a cab.
Nina looks at herself in the mirror, removing bobbie-pins, as Erica folds clothing and puts it away.
ERICA Sounds like quite an evening.
ERICA Wish I could have been there.
NINA You know I asked.
ERICA I know, Susie told me.
ERICA Guess he wanted you all to himself.
NINA That's not why.
Erica looks adoringly at Nina's reflection in the mirror.
ERICA I don't blame him.
Erica starts to remove Nina's DIAMOND EARRINGS, but pauses.
ERICA (CONT'D) Where did you get these?
NINA They're fake.
ERICA Fooled me.
Erica removes the earrings, then walks behind Nina to unzip her.
Nina faces her.
NINA I can do it.
ERICA Turn.
Nina turns back around, reticent.
ERICA (CONT'D) He must have been at your side all night, showing you off.
Erica finishes unzipping the red dress and sees Nina's shoulder.
ERICA (CONT'D) Oh Nina...
Remembering, Nina pulls away from her.
NINA It's just a rash.
Erica gruffly pulls Nina to the mirror and turns her around.
ERICA What are you talking about?
Nina checks her reflection and sees the RASH, red and irritated from scratching.
NINA It was worse a couple days ago.
NINA It's already getting better.
ERICA You've been scratching again.
Erica yanks her out of the room.
Nina sits on the toilet, stripped to her underwear.
She does her best to cover herself.
Erica finishes dabbing her back with HYDROGEN PEROXIDE and replaces the cap on the bottle.
She pulls out NAIL CLIPPERS and cuts Nina's nails down to their base.
Each CLICK makes Nina twitch.
ERICA I thought you'd outgrown this disgusting habit.(click) You haven't done it for years.
NINA Mom, please.
Erica grabs Nina's other hand.
ERICA It's the role, isn't it?
ERICA All this pressure...
ERICA I was worried it'd be too much.
Nina crawls into bed, avoiding her mother's eyes.
ERICA Don't be mad at me.
ERICA You know I love you, you know I want what's best.
ERICA But we have to take care of you.
ERICA Erica opens the JEWELRY BOX and the tinny music begins playing.
ERICA Nina tries to brush her hand away.
Nina lies wide awake after a restless night.
She slowly reaches down under the covers, down between her legs, to complete Leroy's "homework assignment."
She closes her eyes and starts to maneuver.
She suddenly hears a RUSTLING sound and a short SNORE.
She freezes and opens her eyes.
She slowly sits up in bed and sees Erica SLEEPING on a chair in the corner of the room.
Nina glares at her.
Nina waits her turn as a row of DANCERS perform grand jetes diagonally across the room.
She watches Veronica perform her leaps.
She rejoins the group, giving Nina a nasty stare.
Nina avoids it, looking towards Lily, who gives her a small smile.
Just as Nina's turn arrives, a panicked YOUNG CORPS DANCER rushes in and makes a beeline for the severe ballet mistress.
Nina takes one leap and then stops dancing, sensing something's wrong.
The corps dancer whispers into the ballet mistress' ear.
A look of shock on the mistress' face.
The dancer collapses into the older woman's arms.
The piano music trickles to a halt.
Nina exchanges glances with some of the other dancers.
First a few, then more dancers approach the two women, wanting to find out what's happened.
Nina hangs back, filled with a sinking feeling.
Nina sits as Leroy, worse for the wear, stares at the jets of water.
NINA What happened?
LEROY She walked into the street, got hit by a car.
NINA Oh my god...
LEROY I'm sure she did it on purpose.
NINA How do you know?
LEROY Everything Beth ever did came from within.
LEROY From some dark impulse.
LEROY It's what could make her so thrilling to watch.
LEROY Even perfect at times.
LEROY But also destructive.
Nina hesitates, but has to ask.
NINA Was it right after we saw her?
LEROY It's not your problem.
LEROY This has nothing to do with you.
She looks away, not so sure.
LEROY (CONT'D) Nina, don't let yourself be distracted.
LEROY (CONT'D) Dance is not immortalized like music, poetry or art.
LEROY (CONT'D) It lives for now.
LEROY (CONT'D) For this moment only.
LEROY (CONT'D) And this is your moment.
She attempts a nod.
A46 INT.
PRINCIPAL DRESSING ROOM - DAY A46
Beth's belongings have already been packed up and cleared.
Guilt-ridden, Nina tries to get ready.
She picks up her duffel bag, and removes her SATCHEL.
She unpacks its contents onto the counter: needle and thread, cigarettes, a makeup compact, and the tube of lipstick.
She looks over at the vase of flowers.
A few have wilted.
She pulls them out to make the bouquet look fresh again.
Nina exits the elevator with a BROWN SHOPPING BAG.
She walks down a stark hallway and approaches Beth's hospital room.
Members of BETH'S FAMILY surround the bed, blocking Beth from view.
Nina considers going in, but shyly sulks past, drawing the attention of an OLDER NURSE.
OLDER NURSE You can go in.
NINA It's okay.
NINA Nina walks a little further and leans against the wall to wait.
NINA Nina steps out from hiding and goes inside.
Beth is bandaged and unconscious, attached to MACHINES.
Nina stands at a distance, too intimidated to approach at first.
She looks around the room.
It is lined with large, EXPENSIVE-
She removes the flowers Leroy gave her from the brown bag, and sets them next to the others.
Nina slowly approaches Beth's bedside.
Beth's face is heavily wrapped with bandages.
Only her closed eyes and pale lips can be seen.
She scans down her body, sees a sliver of her thigh, purple with bruises.
Curious, Nina lifts the top edge of the blanket and peeks underneath.
The legs are bloated and horribly bruised, pierced with large pins to reset the shattered bones.
She looks lower and lower, and discovers MAGGOTS feeding on her ankles.
Nina turns away, confronted by the Older Nurse.
OLDER NURSE What are you doing?!
Nina doesn't have an answer.
She just stumbles out the door.
A48 INT.
UPPER WEST SIDE APARTMENT BUILDING - NIGHT A48
Nina steps out of her apartment into the dim hallway, lugging a bag of trash.
She notices some WOODEN DEBRIS from an apartment renovation sitting near the trash chute.
Nina drops the trash bag in the chute, then picks up a piece of BROKEN WOOD.
She considers it for a moment, and hides it inside the sleeve of her sweatshirt.
B48 INT.
UPPER WEST SIDE APARTMENT - LATER B48
Nina quietly steps inside and heads towards her bedroom.
Through Erica's open bedroom door, Nina can see Erica busily sewing ribbon onto pointe shoes, humming to herself.
Nina quietly slips back inside her room.
She removes the wood piece and jams it between the door closet, creating a makeshift doorjamb
She tests it.
Holds pretty well.
She hears a creek.
FOOTSTEPS approach.
She removes the wood and sticks it inside her dresser, not ready just yet.
She quickly lies down on her bed and waits to be tucked in.
The door SQUEAKS open, and Nina looks towards it.
Nina, David, and the dancer playing ROTHBART rehearse the Black Swan and Prince Siegfried's Pas De Deux from Act 3.
David lifts her, then sets her down, and they lean-in towards each other, almost kissing.
LEROY No, no, not so stiff.
LEROY Don't be scared of him.
Nina and David dance the next part of the section, looking more worn out.
LEROY Forget about control.
LEROY I want to see passion.
She still looks tense, not getting it.
LEROY (CONT'D) Let it out!
Nina practices with an OLDER BALLET MISTRESS.
She demonstrates a movement, and Nina mimics her.
The mistress scrutinizes, unimpressed.
A49 INT.
PHYSICAL THERAPIST'S OFFICE - ANOTHER DAY A49
Nina is worked over by a PHYSICAL THERAPIST.
Every joint and muscle aches, but Nina breathes through the pain.
Nina and David finish the section, completely soaked with sweat.
They look at Leroy, heaving breaths.
LEROY David, answer me this question: are you interested in fucking her?
David snickers, embarrassed, shakes his head.
LEROY (CONT'D) No, of course not.
LEROY (CONT'D) No one would be.
Leroy comes face to face with her.
LEROY (CONT'D) Nina, your Black Swan still looks no different than your White Swan.
LEROY (CONT'D) She's's just as...frigid.
49B Suddenly, the lights turn off, throwing them into total 49B darkness.
LEROY (CONT'D) Fuck!
Leroy angrily marches to the door and whips it open.
LEROY (CONT'D) Hey!
LEROY (CONT'D) We're still working in here.
LEROY (CONT'D) Lights back on.
There's a momentary pause, and then the lights return.
LEROY (CONT'D) Thank you!
LEROY (CONT'D) Okay, you guys can go.
LEROY (CONT'D) Thank you for your patience.
You stay.
David gives her an insinuating glance, then shakes his head.
Very used to Leroy's "methods."
DAVID Have fun.
David and the Piano Player leave them alone.
49C Leroy approaches Nina and takes her hands in his.
49C
LEROY I'll be the Prince.
LEROY He walks behind her and puts his hands on her waist.
LEROY They do a series of lifts and spins, Leroy bracing her.
He lets go, she moves away from him.
LEROY Use each finger, your face, your tits, everything.
LEROY Entice me!
LEROY They get very close.
He grabs her arm again, she spins, then he stops her, her back to him.
He runs his hands down her arms.
Slowly, seductively.
She trembles.
LEROY (CONT'D) Just feel my touch and respond.
She turns and leans in close, as though to kiss him...
almost touching lips...but then she tries to push off again.
He tightens his grip, holds her there.
She looks back at him, questioning.
He looks at her intently, pulls her to him, and kisses her.
She melts and eagerly kisses him back.
He pulls away, momentarily.
LEROY (CONT'D) Slow down.
LEROY (CONT'D) Open your mouth.
She doesn't.
Open it.
Nina follows his instruction.
The kiss grows more heated and he wraps his arms around her.
He pushes her back against the mirror.
She whimpers.
He runs his hand down her body, then reaches between her legs.
She GASPS, tries to pull his hand out, but he persists.
She throws her head back as he kisses her neck.
She breathes deep, emits short MOANS, succumbing...
Suddenly, he pulls away from her.
She looks at him confused, flushed and breathing hard.
LEROY (CONT'D) That was me seducing you.
LEROY (CONT'D) It needs to be the other way around.
He turns and starts to walk away.
She can't believe it.
NINA Please don't...
He ignores her and walks out of the room.
Nina sits on the floor, head in hands.
Hey...
Nina startles and looks up.
Sees the dark figure of somebody watching her from the doorway.
Looks like HERSELF.
NINA Who's that?
Lily emerges from the darkness, dressed to leave.
LILY You okay?
NINA I'm fine.
LILY You sure?
50B Lily sits down beside her, oblivious of Nina's desire 50B to be left alone.
She digs out a cigarette from her bag.
Offers it to Nina.
Nina doesn't take it.
NINA We can't smoke in here.
LILY I won't tell if you won't.
Nina reluctantly takes the cigarette, holds it a little awkwardly, clearly not a regular smoker.
Lily sparks a flame for her and then lights one for herself.
Nina puffs, but doesn't inhale.
Lily smirks.
LILY (CONT'D) Big day's getting closer and closer, huh?
LILY (CONT'D) I can't wait.
LILY (CONT'D) You're going to be amazing.
NINA Thanks...
Nina wipes off her tears with her hand.
LILY So, want to talk about it?
NINA Just had a hard day.
LILY Leroy play too rough?
Nina looks at her surprised.
LILY (CONT'D) He seems like a prick.
NINA He's brilliant.
LILY Sure, but not exactly warm and fuzzy.
NINA You don't know him.
Lily smirks with a realization.
LILY Someone's hot for teacher.
Nina gives her a withering glance.
LILY (CONT'D) It's okay.
LILY (CONT'D) I don't blame you.
Nina stands up.
NINA I should go.
NINA It's getting late.
LILY Hey, I was only playing.
Nina walks towards the door.
LILY (CONT'D) Nina?
Nina lies in the bath, eyes closed, concentrating.
Her body jostles slightly, moving her hand between her legs, seeking release.
Growing frustrated, she moves more and more aggressively.
She abruptly stops and submerges herself under the water, defeated.
She lies still, her arms wrapped around her chest.
She opens her eyes, her vision distorted by the water.
Suddenly, her blurred Double appears, staring down at her.
Nina shoots up.
The Double is gone.
Nina scans the bathroom, but she is alone.
Nina notices some water dropping off her fingers, onto the lip of the tub.
Then a few drops of RED land on the white porcelain.
Worried, she examines her fingernails, which have started to grow back.
She discovers blood and bits of skin.
Out of the tub, Nina checks herself in the mirror.
Her shoulder is streaked with deep SCRATCHES.
She grabs a pair of little SCISSORS from the medicine cabinet and starts trimming her fingernails.
She looks up at the mirror and sees her reflection snip off the tip of her index finger.
Nina GASPS and drops the scissors, CLANGING in the sink.
Two of her fingers are bleeding, their tips sliced.
Nina?
Nina looks at the door, already blocked by the hamper.
NINA I'll be out in a second.
NINA Footsteps recede and Nina breathes.
David and Nina dance the Black Swan's Pas de Deux.
Once again, Nina's rigid and self-conscious.
LEROY Try it again.
They resume dancing.
She finishes, out of breath, and looks at Leroy and the Russian ballet mistress.
LEROY (CONT'D) Again.
The piano music starts up again, and she begins dancing.
When she finishes, she looks at him, eager for feedback.
LEROY (CONT'D) Again.
The music starts up again.
Nina stays still, frustrated.
NINA Do you have any corrections?
LEROY No.
She doesn't understand.
He gets up from his chair and goes to her.
LEROY (CONT'D) Lily talked to me.
LEROY (CONT'D) Said she saw you crying.
Nina looks away.
Can't believe Lily talked to him.
LEROY (CONT'D) She said you were upset and I should "take it easy" on you.
NINA I didn't tell her that.
LEROY Maybe you'd like a break for a day or two.
LEROY Or a fucking month.
NINA She shouldn't have said anything!
LEROY I don't care!
LEROY You shouldn't be whining to her!
NINA I didn't.
LEROY You could be brilliant.
LEROY Taking it easy would be a betrayal.
He walks away from her.
NINA I'm sorry.
NINA I'm sorry.
LEROY Stop saying that!
LEROY Stop being so damn weak!
Furious, Nina heads towards the soloists' dressing room.
Hears them chatting in their usual manner.
Nina KNOCKS loudly at the door, interrupting them.
Look who's gracing us with her presence...
NINA Lily, I need to talk to you.
LILY Okay...
NINA Now.
VERONICA Ooooh.
The other girls giggle.
LILY Shut up.
Nina leads Lily to a private nook, fuming.
LILY What's wrong?
NINA You told Thomas about last night?
Lily falters, guilty.
LILY I ran into him this morning.
LILY He said you guys were having some trouble.
NINA Why would he talk to you?
LILY Whoa your highness, I just told him you're working your ass off and I'm sure you'll be great.
NINA You shouldn't have done that.
LILY I didn't fucking do anything.
Lily takes off.
Nina stares after her, at a loss.
A58 INT.
SUBWAY - NIGHT A58
Nina sits on the subway, going home.
She notices that one of her fingernails has a jagged edge.
She removes an EMORY BOARD from her bag and begins filing it down.
A SKEEZY MAN across the aisle ogles her.
Nina keeps her eyes down, trying to ignore him.
He starts to sing an OLD LOVE SONG from the 20's.
Nina stands and goes to the other end of the car.
He continues singing, undeterred.
Nina sits on the floor in a loose sweatshirt, sewing ribbon onto pointe shoes.
Erica sits across from her, sewing ribbon onto another pair.
ERICA Has he tried anything with you?
Nina doesn't respond.
ERICA (CONT'D) He has a reputation...
Nina tries to ignore her.
ERICA (CONT'D) I have a right to be concerned, Nina.
ERICA (CONT'D) You've been staying late so many nights.
ERICA (CONT'D) "Rehearsing."
ERICA (CONT'D) I hope he's not taking advantage, that's all.
NINA He's not.
ERICA Good.
ERICA I don't want you making the same mistake I did.
Thanks.
ERICA Not like that.
ERICA I just mean as far as my career was concerned.
NINA What career?
ERICA The one I gave up to have you.
NINA You were 28.
ERICA So?
NINA And only...
Nina bites her tongue.
ERICA Only what?
NINA Nothing.
ERICA What?
Nothing.
Erica glares at her.
ERICA How's your skin?
NINA It's fine.
ERICA We leaving it alone?
NINA Yes.
ERICA Let me see.
Nina stares back defiantly.
ERICA (CONT'D) Take off your shirt.
NINA No.
Erica starts to come towards her.
The DOORBELL RINGS.
Erica looks at Nina questioningly.
Nina shakes her head.
Erica goes to the door and cracks it open, keeping the chain engaged.
ERICA Can I help you?
ERICA (pause) I'm sorry, she's not in.
Erica shuts the door.
Nina rushes out to see who it was.
NINA Who was it?
NINA Irritated, Nina walks around Erica and quickly opens the door to find out.
ERICA It's no one.
Nina sees a ballerina walking away from the door.
NINA Hello?
Lily turns.
LILY Hey.
What are you doing here?
Nina steps out of her apartment and closes the door.
LILY I wanted to apologize.
Nina just stares, incredulous.
LILY (CONT'D) You were right, I shouldn't have talked to him about you.
Erica opens the door and sticks her head out.
ERICA Sweetheart?
NINA Give me a second.
ERICA Your dinner...
NINA Mom, please!
Erica closes the door.
LILY She's a trip...
NINA How did you know where I live?
LILY I have my ways.
Nina looks at her, darkly.
LILY (CONT'D) Relax, I got it from Susie in the office.
LILY (CONT'D) I feel really shitty.
LILY (CONT'D) Can I make it up to you?
LILY (CONT'D) Take you out to dinner?
NINA I don't think-
LILY A drink?
Nina's tempted.
Erica pokes her head out again.
ERICA Sweetie, you need to rest.
LILY Jesus.
Nina pushes the elevator call button.
Wait.
Nina walks to the door, and grabs her coat.
ERICA What are you doing?
NINA I'm going out.
ERICA What?
Nina ignores her and shuts the door.
Let's go.
A noisy bar and burger joint, packed to the brim.
Lily and Nina sit at a small table.
LILY Can't believe that's what he called her.
LILY So gross!
NINA I think it's sweet.
LILY Little princess?
LILY He probably calls every girl that.
NINA Only Beth.
LILY Well, I'm sure she lost the title after her game of chicken.
Nina's smile fades.
LILY (CONT'D) Bet he'll be calling you little princes any day now.
NINA I don't think so.
LILY Sure, just gotta let him eat the pussy.
Nina blushes, embarrassed, and Lily cracks up.
A WAITER drops a plate in front of her.
Cheese burger, extra bloody.
LILY Danke schoen.
WAITER Let me know if it's not juicy enough.
LILY Oh, I will.
He smiles, keeping his eyes locked on Lily, as he rudely plops down Nina's plate.
WAITER Enjoy.
Lily watches him go, then notices Nina looking annoyed.
LILY What?
NINA Guess I'm invisible.
Lily studies her and digs into her purse.
Pulls out a SEXY SHIRT.
LILY Here, wanna spruce up?
Nina gives her a puzzled look.
LILY (CONT'D) I always carry a spare, case I wake up somewhere unexpected.
Lily picks up her ungainly burger and takes a big bite, a little grease dripping down her chin.
Nina cuts into her dry chicken breast.
LILY (CONT'D) Not like you need more attention these days.
LILY (CONT'D) How is he?
Nina doesn't understand the question.
LILY (CONT'D) Thomas?
NINA I wouldn't know.
LILY Yeah, right.
NINA I don't want to talk about it.
LILY Relax, you're so tense.
Lily pulls out a cigarette case and clicks it open.
Inside, CIGARETTES and a couple PILLS.
LILY (CONT'D) One for you...
Lily grabs one of the pills and slides it over.
LILY (CONT'D) And one for me.
Lily grabs her pill and downs it with a beer.
Nina stares at her pill, too embarrassed to admit she doesn't know what it is.
LILY (CONT'D) Don't worry, it's pure.
LILY (CONT'D) Brought it with me straight from San Francisco.
NINA What is it?
LILY You're kidding?
LILY You never rolled?
Nina blinks.
LILY (CONT'D) Oh boy.
LILY (CONT'D) It'll just make you have a good time.
LILY (CONT'D) Loosen up.
LILY (CONT'D) See the night sky.
How long does it last?
LILY Couple hours.
LILY Tops.
Nina looks at the pill, thinks about it for a second...
NINA That's okay.
LILY Sure?
Wearing the SKIMPY SHIRT Lily offered her, Nina rinses her mouth out with water from the sink, then checks herself out in the mirror.
It's broken and covered with graffiti and stickers.
One particularly bright one says, "Seize the Day-glo."
Nina's cell phone RINGS.
She checks the ID--"MOM"--and silences it.
Nina puts her SWEATSHIRT back on over the shirt, and exits.
Nina returns to her table, but when she gets there, Lily is gone and the table is cleared.
She looks around the crowded room, doesn't see her anywhere.
She heads towards the exit, and sees Lily at the bar, flirting with TWO ATTRACTIVE MEN.
She's very touchy-feely.
Intrigued, Nina stays put, wanting to observe Lily from a distance.
The BARTENDER sets a drink down in front of Lily.
The men compete to pay for it.
Lily takes out the CIGARETTE CASE from her purse, and removes the pill.
Nina looks on, suspicious.
Lily opens the pill, and dumps its contents into the drink.
She stirs it with her finger.
She holds out her finger to one of the men, he sucks off the liquid.
Lily looks over and catches Nina watching.
She waves for her to join them.
Nina reluctantly walks to her.
LILY Heeey, thought we could use some drinks.
NINA I'm gonna go.
LILY This is Tom and this is Jerry.
The guys laugh.
ANDREW Actually it's Andrew.
TOM Tom.
NINA Hi.
LILY You can't leave, I bought you a drink.
Lily holds out the doctored beverage.
Nina eyes it, tempted to go down the rabbit hole...
NINA I really shouldn't, we're on the stage tomorrow.
LILY What, you gonna go home to mommy?
LILY Live a little.
Nina grins sheepishly and takes the drink.
Lily smiles.
NINA Just a couple of hours?
LILY Tops.
Nina takes a tiny sip.
LILY (CONT'D) Go on.
Nina takes another sip and smiles.
LILY (CONT'D) Let's go sit somewhere a little more comfortable.
LILY (CONT'D) Gentlemen?
Nina's drink is half gone.
The foursome sits snugly at a booth.
Nina next to Andrew, shyly avoiding his gaze.
She takes another tentative sip of her drink.
ANDREW You haven't told me who you are.
NINA Oh, I'm a dancer.
ANDREW No, I mean your name.
NINA Nina.
TOM You two sisters?
Yes.
No.
ANDREW Well?
LILY We're blood sisters.
NINA We dance in the same company.
Ahh, ballerinas.
So that's why you look alike.
LILY Tom and Jerry are gay lovers.
TOM Very funny.
LILY Oh, I just assumed.
ANDREW I've never been to the ballet.
LILY In that case you're definitely NOT gay.
TOM It's pretty boring, isn't it?
No, it's not.
It's not for everyone.
You probably aren't sophisticated enough.
TOM You've got some mouth, you know that?
LILY Isn't that compliment a little premature?
Lily sips her drink, staring at Tom flirtatiously.
NINA You guys should come sometime.
NINA I can comp you tickets.
Tom laughs, amused by Nina's earnestness.
TOM Yeah...that'd be neat.
LILY I think we all need another round.
LILY Bottom's up.
She looks at Nina and sucks down her drink, challenging her to follow suit.
Nina takes a breath of courage and empties her glass.
She waits for something to kick in.
LILY (CONT'D) Tom, come with me?
Lily slips out of the booth and Tom follows, leaving Nina and Andrew alone.
She avoids his gaze, nervous.
ANDREW So...what are you guys working on these days?
Her cell phone RINGS, interrupting him.
She quickly turns it off and gives him an embarrassed smile.
NINA Sorry.
NINA Swan Lake.
ANDREW Yeah?
NINA You know it?
ANDREW Oh, no, not really.
ANDREW Heard of it though.
ANDREW What's it about?
NINA It's about a girl who's been turned into a swan.
NINA She needs love to break the spell.
ANDREW Okay.
NINA Yeah, but her prince falls for the wrong girl and she kills herself.
ANDREW So a happy ending, then?
NINA It's beautiful, actually.
ANDREW Like you.
She starts to feel the initial tingles of the drug.
NINA Huh?
ANDREW I said you're beautiful.
She giggles.
That funny?
She gives him a flirtatious glance.
NINA My hands are all sweaty.
NINA Lily slides in next to her.
NINA Nina sees her and melts into her body.
NINA Lily hugs her back.
LILY Uh oh!
LILY Looks like someone's rolling.
LILY Let's get you dancing.
A65 OMITTED A65
Nina kisses Tom on the floor of a crowded dance club.
The drug is in full effect.
The world has soft edges, colors are vivid and bleed into one another.
Lily twirls her around.
Nina attaches herself to her, hungry for the attention.
A cheering section of guys surrounds them.
Nina lets loose.
Dances with abandon.
Nina makes out with someone, her back pushed up against the wall.
Her eyes are closed, she's shiny with sweat.
She opens her eyes, confused to find that it's not Andrew or even Tom, just a STRANGE MAN.
She backs away.
He reaches for her, but she swats him off.
She stumbles around the dance floor, looking for Lily, but only sees a mass of moving bodies.
She finally spots a girl that looks like her from behind.
Nina grabs her shoulder and the GIRL spins around.
Not Lily.
Nina pushes her way out of the club, starting to panic.
She looks around, trying to figure out where she is, but the city is dark and non-descript.
LILY Nina!
Nina turns towards the voice and, with relief, sees Lily exit the club.
LILY (CONT'D) Where you goin'?
Nina stares adoringly at Lily, who has her eyes closed, enjoying the cool air blowing in from her open window.
Lily opens her eyes and catches Nina staring.
Lily smirks.
Using her index and middle finger as "legs," she "walks" her hand over the vinyl seat, all the way to Nina's leg and pokes it.
Nina watches her hand with a smile on her face, glances at Lily.
Lily smiles back, and then "walks" her hand up the leg, until it reaches the edge of Nina's dress.
Lily looks at Nina questioningly.
Nina doesn't protest.
Lily slips her hand underneath the dress, gently makes contact...
Nina shudders, but pulls Lily's hand back out and holds it.
Lily snickers and looks out her window.
Nina looks at their clasped hands, then out her own window, happy.
Nina quietly opens the front door.
Lily GIGGLES.
Nina SHUSHES her.
They slip off their shoes and tip-toe inside.
Nina eases the door shut.
Lily taps her on the shoulder and points towards the hallway.
Erica emerges from the darkness, approaching them slowly.
Distraught.
ERICA Do you have any idea what time it is?
NINA Mmm-hmm.
NINA Late.
ERICA Where have you been?
NINA To the moon and back.
ERICA You've been drinking.
Ding ding ding.
Lily snickers, Nina tries to keep a straight face, but ends up laughing.
ERICA What else?
NINA Huh?
ERICA What else have you been doing?
Nina smiles coyly.
NINA You want to know their names?
Erica grabs Nina's wrist.
ERICA You need to sleep it off.
NINA There were two.
NINA Tom and Jerry...
ERICA Be quiet, Nina.
I fucked both of them.
ERICA Shut your mouth!
ERICA Nina runs into her room and SLAMS the door.
She grabs the broken PIECE OF WOOD from the dresser and jams the door.
She backs Lily away, preparing for the storm.
NINA Don't come in here!
Erica tries to open the door, but it gets stuck.
She peers her eye through the crack.
ERICA What's this?
NINA It's called privacy!
NINA I'm not fucking twelve years old anymore!
Erica struggles a little with the door, but can't get it to budge.
ERICA You're not my Nina right now!
Nina SHOVES the door shut.
Erica's FOOTSTEPS retreat, followed by the SLAM of her bedroom door.
72B Nina is worked up, breathing hard.
72B
LILY Whoa...
LILY Nina flees to the door.
LILY Pauses.
LILY She peeks back and sees that it's actually Lily.
LILY Lily responds with equal force.
LILY They claw at each other, passion exceeding coordination.
LILY She straddles Nina, who looks up at her carnivorously.
LILY Nina flips Lily over, becomes the dominant one.
LILY There's subtle movement underneath the skin.
LILY Little pin pricks push up the flesh, trailing behind her hand.
LILY She bites her neck.
LILY Lily smiles, likes the violence.
LILY Then Lily gets back on top of Nina.
LILY The tattooed lilies on her back undulate and spread out.
LILY Morphing into dark wings.
She kisses down Nina's body.
Further and further...
Lily starts to go down on Nina.
Nervous, Nina whimpers.
Glances down and sees the DOUBLE.
She tries to pull away.
LILY shushes her.
Nina calms back down, seeing that it's her.
She takes a breath and succumbs.
Bumps shoot up all over her skin as her breath quickens.
She closes her eyes, allows the sensation to invade her body and CLIMAXES.
She breathes her way back to earth.
Slowly her eyes open.
She rolls over towards Lily.
But Lily is gone.
Instead her DOUBLE hovers over her.
DOUBLE Sweet girl.
She SMASHES a pillow over Nina's face.
A73 OMITTED A73
Nina lies alone in bed, the sheets and comforter in disarray.
She sits up, clutches her head in pain.
She looks around, but there's no sign of Lily or the Double.
Then her eyes drift to the alarm clock: 11:36.
She snaps out of bed.
Dishevelled, Nina races towards the front door.
She sees Erica brooding at the kitchen table, watching her.
NINA Why didn't you wake me up?
Erica just stares at her, devastated.
NINA (CONT'D) I'm moving out.
Nina races.
She hears muffled Black Swan music playing, rehearsal clearly in progress.
My music.
She runs into the wings and sees the full company rehearsing on stage for the first time...
Another girl dancing her part.
The girl spins and Nina sees her face.
It's Lily!
Horrified, Nina runs onto
76 STAGE 76 and makes a beeline for Leroy, looking beyond apologetic.
The dancers and piano player stop at the interruption.
LEROY Keep going.
LEROY Let's finish the Act.
The piano music resumes, and the dancers pick up where they left off.
Nina meets Lily's eyes.
She makes a sorry face, but then continues dancing.
Nina is forced to watch from the sidelines as Lily and David finish the Black Swan's Pas de Deux.
LEROY (CONT'D) That was good.
LEROY (CONT'D) Let's take 10, then we'll move on to Act 4.
He turns to Nina and his smile fades.
LEROY (CONT'D) Get warmed up.
NINA Thomas, I'm sor-
He ignores her, and walks off stage.
Lily tentatively approaches with the PRACTICE TUTU.
LILY Hey...
Nina snatches it, avoiding eye contact.
She puts it on.
LILY (CONT'D) He wanted to go through the spacing.
LILY (CONT'D) Asked me to step in.
Nina starts stretching.
I overslept.
LILY Oops...
LILY Least you had a good time, right?
Nina doesn't answer.
LILY (CONT'D) Hello?
NINA You put something in my drink.
Yeah...
NINA And took off this morning.
LILY This morning?
NINA Yeah, you slept over.
LILY Uh, no.
LILY Unless your name's Tom and you have a dick.
NINA But we...
Nina stops herself.
LILY We what, Nina?
Lily can read something on her face.
LILY (CONT'D) What, you have some kind of lezzy wet dream?
Nina glances at the dancers, nervous they've heard.
NINA You're lying.
Oh my god, you totally fantasized about me.
NINA Stop.
LILY Was I good?
Shut up!
Other dancers look over.
Nina resumes stretching.
Lily just walks away.
A77 INT.
STAGE - DAY A77
Nina dances the end of the ballet, the White Swan's suicide.
LEROY The Black Swan has stolen your love.
LEROY There's only one way to end the pain.
Nina climbs the stairs of the set and arrives at the "cliff," stopping at the precipice.
LEROY (CONT'D) You're not at all fearful.
LEROY (CONT'D) Filled with acceptance.
Nina looks down.
It's a short drop to a stack of pads, but a HARD FLOOR surrounds it.
LEROY (CONT'D) You look at the Prince, then down at Rothbart, and, yes, up at the audience...And jump!
She hesitates, fearful.
LEROY (CONT'D) Go ahead.
LEROY (CONT'D) You'll be fine.
LEROY (CONT'D) She falls...and lands in the pads, unhurt.
LEROY (CONT'D) Slight applause from the other dancers.
Everybody get a drink then it's notes.
Nina lies in the pads, completely exhausted.
B77 INT.
BACKSTAGE - LATER B77
Nina sits backstage, toweling herself off.
She pauses, noticing Leroy and Lily conversing near the doorway.
Lily nods and touches his arm.
He smiles warmly, then notices Nina watching.
His serious demeanor returns and he pulls away.
He says goodbye to Lily.
Lily follows his gaze and smirks at Nina, rubbing it in, before exiting herself.
A81 INT.
BATHROOM - NIGHT A81
Nina kneels in front of the toilet, a finger down her throat.
She gags, but nothing comes up.
Her eyes tear up, and she tries again, but still just heaves.
Frustrated, she wipes her mouth and flushes.
Nina exits the bathroom and approaches her mother's bedroom door.
It's closed, but the light's on underneath.
She's about to knock, but hesitates.
Through the door, she can hear the sound of her mother watching an INFOMERCIAL on TV.
An unfamiliar, lonely noise.
Nina stands there for a moment, just breathing.
She strengthens her resolve and backs away from the door.
Nina collapses on her bed.
She opens the JEWELRY BOX sitting on her night stand.
She watches the ballerina spin for a moment...
Then suddenly SLAMS the lid shut and throws the box hard against the wall.
She shoots out of bed and starts gathering all her childish possessions--stuffed animals, dolls, keepsakes, etc.
Nina shoves her belongings into the TRASH CHUTE, a pile of her next victims strewn at her feet.
She grabs a TEDDY BEAR IN A TUTU, and jams him in.
A84 INT.
STAGE - DAY A84
Nina dances the Black Swan in front of the nearly completed scenery.
A few TECHNICIANS complete last minute touch-ups.
Leroy watches from his down-stage post, his focus split between her and...
Lily, stretching with the other ballerinas.
She stares at Nina with a dark expression.
Fueled by the competition, Nina pushes herself.
Her dancing becomes more impassioned and aggressive.
She finishes the section, breathing deeply, covered in sweat.
The company enthusiastically claps.
She stares intently at Leroy, awaiting his response.
LEROY At last, I saw the Black Swan.
B84 INT.
COSTUME SHOP - DAY B84
Nina wears the BLACK SWAN COSTUME, facing a mirror.
Another mirror behind her creates an infinite array of reflections.
The overworked COSTUMER checks each seam, pulling the costume taut, analyzing what needs to be taken in and let out.
Nina looks uncomfortable, disliking the scrutiny of her body.
She hears a sharp RUSTLE.
Like someone's scratching.
She looks up at the mirror.
Her reflection stares back.
Behind the first reflection, another Nina has her arm behind her back, like she's scratching her shoulder.
Nina leans to get a better look...
COSTUMER Sit still, I'm almost done.
COSTUMER Costumer checks one more thing, makes one more note.
Okay, all set.
The costumer leaves her to change.
Relieved, Nina quickly takes off the costume and starts to dress in her sweats.
She hears someone enter the costume shop.
LILY Hey...Thomas sent me.
Nina pauses, recognizing her voice.
COSTUMER Yeah, need to get you measured for your Swan Queen costumes.
Nina steps out from behind the privacy curtain, and finds Lily waiting.
What's she doing here?
LILY He made me your alternate.
LILY Just in case...
Nina pushes past her.
C84 INT.
BACKSTAGE HALLWAY - DAY C84
Nina chases after Leroy, in mid-conversation with the STAGE MANAGER and two STAGEHANDS.
NINA Thomas!
He stops and faces her.
NINA (CONT'D) She's trying to replace me.
LEROY (to stage manager,
Go ahead.
I'll catch up.
They continue walking.
LEROY (CONT'D) What's going on?
NINA Lily.
NINA You made her my alternate.
LEROY There's always an alternate, you know that.
LEROY Lily's the best choice.
NINA She wants my role.
LEROY Every dancer in the world wants your role.
NINA No, she's different.
NINA She's after me.
NINA She's trying to replace me.
Nina...
NINA Please believe me.
He studies her for a moment, not sure what to make of this.
LEROY Listen, I know it's been a struggle.
LEROY But you had a breakthrough this morning.
Nina starts to speak, he holds up his hand to silence her.
LEROY (CONT'D) Tomorrow is yours.
LEROY (CONT'D) Give a great performance, and you won't have to worry about Lily, or anyone else.
LEROY No more.
LEROY Go home and rest.
Nina practices the Black Swan, alone with the jaded piano player, working herself hard.
He suddenly stops playing.
NINA What happened?
I gotta life, deary.
He closes the music book and stands.
Don't work too hard.
It's your big day tomorrow.
Annoyed, she watches him leave.
85B She faces herself in the mirror and takes a breath.
85B
She resumes dancing without music, her feet CLICKING on the floor.
As she moves, she notices something strange out of the corner of her eye:
The reflection's dancing lags a little behind hers.
Nina stops.
The sound of her footsteps stops a second later.
She stares at the mirror...troubled.
The door to the room BANGS shut.
She whips towards it and she's suddenly plunged into
Freaked, she stumbles towards the door, and pushes out into
Where it's equally dark.
Lit only by the stage's "ghost light," a single bulb on a stand.
NINA Hey!
NINA Hey!
NINA I'm still in here.
NINA She looks at the cavernous auditorium.
NINA All those empty seats, faced towards her.
NINA Very overwhelming...
She hears a noise in the wings.
NINA (CONT'D) Hey!
NINA (CONT'D) Turn the lights back on!
She gets to the other side of the stage, but the wings seem empty.
Quiet.
86B Then she hears the faint sound of MUFFLED BANGING.
86B
NINA (CONT'D) Hello?
NINA (CONT'D) She heads towards the noise.
NINA (CONT'D) The banging now accompanied by a
It's pretty dark but the sound is unmistakable: two people going at it.
Nina tiptoes past some off-stage SETS and LIGHTING EQUIPMENT.
And peeks around a piece of SCENERY...
Catching a glimpse of Leroy fucking Lily further backstage.
She's wild, clearly enjoying it.
Nina looks away, disgusted.
She peeks back one more time.
Leroy has become the demon Rothbart, ravishing the Double.
She meets Nina's eyes and smiles.
Nina jumps back, knocking into a piece of the set.
The lovemaking pauses at the sound.
Nina flees.
A88 INT.
PRINCIPAL DRESSING ROOM - NIGHT A88
Nina runs in and quickly jams her belongings into her bag.
She notices her reflection in the mirror and removes her diamond earrings.
Then gathers the other trinkets sitting on the counter and puts them all inside her bag.
B88 EXT.
THEATER - NIGHT B88
Nina pushes out the stage door, and passes the ROW OF
They now advertise Swan Lake and feature a beautiful photograph of Nina.
Nina stops and looks at them.
Nina slowly enters Beth's room, but remains at the threshold.
Beth sits in a wheelchair faced towards the window.
Sleeping.
Nina gets up the nerve and quietly walks further in, trying not to wake her.
Nina pulls out the tube of lipstick from her bag and gently places it on the hospital table.
She pulls out the diamond earrings, sets them down.
Followed by the makeup compact, the pack of cigarettes, a needle and thread, and an emory board.
A hand suddenly GRABS Nina's arm.
Awake, Beth stares Nina down.
BETH What are you doing here?
BETH Beth follows her gaze to the random items on her table.
NINA I'm so sorry.
Beth begins touching the objects, vaguely remembering.
NINA (CONT'D) I didn't mean to make you feel this way.
NINA (CONT'D) It's happening to me now.
NINA (CONT'D) She's trying to replace me.
Beth sees the earrings and it all clicks in.
BETH You stole all these things?
NINA I just wanted to be like you.
NINA Perfect.
Beth shoots Nina a dark look and turns away.
BETH I'm not perfect.
BETH I'm nothing.
NINA It's not true.
BETH Fucking nothing!
Beth grabs the emory board and stabs herself in the face.
BETH (CONT'D) Nothing!
BETH (CONT'D) Nothing!!!
NINA Beth?!
Nina spins Beth around.
She is now a bloody version of THE DOUBLE!
She continues stabbing herself.
Nina grabs the Double's hand and struggles to restrain her.
NINA Stop it!
NINA Stop!
The emory board stabs into Nina's arm.
Nina rushes from the room.
She BANGS into a empty stretcher sitting in the hallway, causing a CLAMOR.
The older nurse looks up.
Nina jumps into an open elevator.
She hits the GROUND FLOOR BUTTON, and hides in the corner.
As the doors close, she looks down and sees that, in one hand, she holds the BLOODY EMORY BOARD.
She drops it, disgusted.
Nina runs in and quickly shuts the door behind her.
Takes a breath, and notices some blood still on her hands.
A92 INT.
KITCHEN - SAME A92
She flips on the light.
The room's empty.
She goes to the sink and washes her hands.
She finishes, and flips the light off as she walks out of the room.
She pauses, rushes back and flips on the light.
The Double stares at her from the corner, her face covered in blood.
Terrified, Nina runs.
B92 INT.
BATHROOM - SAME B92
She goes straight to the toilet and VOMITS.
She hears a creaking sound in the apartment and looks towards the open door.
NINA Mommy?!
Nina flings open the door, but Erica's not in there.
She hears RUSTLING, then WHISPERING.
Nina looks around the room.
The paintings of herself seem to move slightly.
Blink.
Mouths move.
They whisper: "Sweet girl" and then start chanting "My turn, my turn, my turn!"
Nina cups her hands over her ears, trying to block it out.
She hears a BANG and looks towards the door.
No one's there.
She glimpses the mirror, which reflects down the hallway.
She sees her Double rushing towards the room.
Scared, Nina whips around, just as her mother arrives in the doorway.
ERICA What are you doing?
Nina closes the door.
Sticks in the broken piece of wood.
A pain shoots through her shoulder.
She SCREAMS, instinctively reaching for it.
She quickly yanks off the sweater and looks at the vanity mirror.
Her back pulsates unnaturally.
Tiny black tips poke through.
The door opens and catches on the doorjamb.
Erica starts POUNDING.
She digs into the open bump on her shoulder with her fingernails.
ERICA Open the door!!!
ERICA Nina concentrates, takes hold of the growth and yanks.
ERICA Nina looks at the object held in her fingers: a sharp, TINY BLACK SPINE.
ERICA Like that of a sea urchin.
ERICA Damp, feathery wisps hang off of it.
ERICA Erica rushes in and finds Nina half-naked, her skin inflamed.
ERICA (CONT'D) Oh my god...
Nina starts forcing her out the door.
Erica pushes back.
ERICA (CONT'D) Stop, you're sick!
NINA Get OUT!
NINA But ROTHBART'S HAND grabs the door frame.
NINA Erica SCREAMS in pain.
NINA She finally gets the door all the way shut.
NINA She looks down, sees one of her knees SNAP backwards, like that of a bird.
NINA Then the other knee SNAPS back.
NINA And SLAMS her head into the radiator.
TINNY MUSIC plays in the darkness.
Nina flutters open her eyes.
The world comes into focus and she sees her mother hovering over her, stroking her hair.
ERICA Sshh, shhh, it's okay.
ERICA I'm here.
Nina looks around, disoriented.
Sees her hands jammed inside thick socks, held on by rubber bands.
Groggy, she tries to pull them off.
ERICA (CONT'D) You were scratching all night.
ERICA (CONT'D) Nina weakly tries to sit up, but Erica pushes her back down.
ERICA (CONT'D) Rest.
ERICA (CONT'D) Shhh, rest.
Nina gives in, too tired to fight her.
Her eyes drift to the source of the tinny music: the open jewelry box.
The ballerina's been broken off, all that remains is a single amputated leg, spinning morbidly on the base.
ERICA (CONT'D) That's good.
ERICA (CONT'D) Rest.
Nina's eyes drift to the alarm clock.
It's gone.
NINA Where's the clock?
ERICA Don't worry.
Nina looks at the dark window.
NINA It's dark.
NINA What night is it?
Nina reads Erica's face.
Reality clicks in.
What time is it?!
Nina tries to sit up, but her mother pushes her back down.
NINA (CONT'D) I have to go.
ERICA Don't worry.
ERICA I called the theater and told them you weren't feeling well.
Nina freaks, struggles more violently.
NINA No, I want to.
ERICA Lie down!
NINA Get off me!
Nina squirms free of Erica's grasp and gets out of bed.
She gets to the door...
But the doorknob's been knocked-off, leaving just a metal post sticking out of the hole.
ERICA We're staying in here until you feel better.
Nina grips the metal post and pulls and pulls, shaking the door.
NINA Where is it?
Erica calmly sits down in her CHAIR, waiting for the storm to pass.
ERICA This role is destroying you.
Nina rifles through her dresser drawers.
She notices her mother sitting calmly.
NINA Move.
ERICA Nina...
Nina grabs her by the wrist.
ERICA (CONT'D) Stop it.
NINA You're crazy!
ERICA What happened to my sweet girl?
Nina yanks Erica off the chair onto the floor.
NINA She's gone.
ERICA Please, you're not well.
Under the cushion Nina grabs the hidden brass DOORKNOB.
Erica lunges for her daughter's legs.
NINA Let go!
ERICA You can't handle it!
NINA I can't?!
NINA I'm the fucking swan queen!
NINA You never even got out of the corps.
ERICA You fucking ungrateful-
Nina jams the knob onto the post, opens the door.
ERICA (CONT'D) Don't leave!
ERICA (CONT'D) Nina!
Nina approaches the theater with harried steps.
Quickly past the row of SWAN LAKE posters.
She reaches the side of the building, flings open the stage door and enters.
Nina frantically makes her way down the bustling hallway, chaotic with dancers.
Excitement in the air.
She nears the soloists' dressing room.
Just outside of it, she spots a group of DANCERS excitedly chatting around a smiling Lily.
Nina stops in her tracks.
Lily glances in her direction, and her smile quickly fades into a sneer.
LILY What are you doing here?
The other girls follow her gaze towards Nina, and their smiles turn to confusion.
LEROY Nina?
She turns and finds that Leroy has approached from behind her.
LILY You're supposed to be sick.
LEROY Lily, give us a minute.
Leroy closes the door behind them.
He looks at Nina, wheels spinning.
LEROY Are you okay?
NINA I'm fine.
Nina goes to her wardrobe, finds her two costumes hanging.
One for the White Swan, one for the Black Swan.
LEROY Nina?
She doesn't heed him, pulls out the White Swan leotard and sets it on her chair.
LEROY (CONT'D) Nina!
NINA What?
LEROY I already asked Lily-
NINA Fuck.
NINA Have you announced it?
He hasn't.
NINA (CONT'D) After Beth, do you need more controversy?
Leroy smirks at her directness.
NINA (CONT'D) I'm here, Thomas.
NINA (CONT'D) I'm doing it.
He looks at her, considering, and gives her a reluctant nod.
She smiles.
LEROY The only person standing in your way is you.
LEROY It's time to let her go.
LEROY Lose yourself.
She nods.
He takes one last look at her and leaves.
She breathes a sigh of relief.
Curious, she cracks open the door and peeks outside:
Leroy has pulled Lily down the corridor to break the news.
Lily takes off, furious.
Through the PA, music from ACT 1 plays.
Nina sits at her vanity in a robe, wearing the full White Swan makeup and FEATHER CROWN.
Pale, with red lipstick and dark eyeliner, she looks like a porcelain doll.
She drops the robe off her shoulder and covers her rash with white makeup.
The STAGE MANAGER'S voice comes through the PA speaker:
STAGE MANAGER (V.O.) Act 2's starting.
STAGE MANAGER (V.O.) Ten minutes.
STAGE MANAGER (V.O.) She removes her other slipper and finds the same toes completely FUSED, forming two large toes with double toenails on either side of the middle toe.
Nina stretches nervously in the wings, awaiting her entrance.
She peeks out through a small hole in the wall, sees the AUDIENCE sitting expectantly in their seats.
The music begins and they shift and mummer in anticipation.
Nina pulls away, taking deep breaths and clenching her hands, trying to stay calm.
On stage, David enters, beginning the Act.
He traverses the stage, "hunting" with a crossbow.
Go.
Nina takes a last breath and runs on.
Under the spotlight, she begins dancing her intro.
David runs towards her and she startles away from him, afraid.
He grabs her and they begin their first Pas de Deux.
Nina comes offstage, catching her breath.
All around her, CORPS MEMBERS dressed as little swans rush back on stage, where FOUR LITTLE SWANS begin the Pas de Quatre.
Nina looks into the opposite wing and sees Leroy watching her.
He gives her a small, contented nod, then disappears behind a swarm of dancers.
On stage, the Four Little Swans perform.
In their identical makeup and costumes, they look disturbingly alike.
During the applause, Nina catches a glimpse of David backstage, sweaty, laughing and holding someone's hands.
Nina can't see who, her view obscured by moving bodies and limbs.
Suspicious, Nina moves to get a better look.
Revealing that David's flirting with Lily.
Nina tenses.
Then the Four Little Swans rush offstage past Nina.
She watches them go, unsettled.
STAGE MANAGER What are you doing?
STAGE MANAGER You're on!
Nina rushes from the wings, directly into David's arms.
All the swans are frozen in two rows on each side of the stage, looking downstage.
David launches Nina into the air, hands around her waist.
He slowly turns her around, keeping her held high.
From her swirling, bird's eye view, Nina sees the rows of identically dressed Little Swans glaring at her...
Nina freaks, jerking her body.
David's grip SLIPS and Nina SLAMS onto the stage.
It's a horrific moment that feels like an eternity.
Gritting her teeth, Nina looks up around her, sees the faces of the other ballerinas.
Staring at her sadistically.
Nina finds Lily, glancing at David.
He snaps to and quickly helps Nina up.
DAVID What the fuck?
DAVID They resume dancing, Nina barely keeping it together.
DAVID Leaving Nina and David alone.
DAVID She pulls away from David, frantically flapping, until she disappears into the wings.
As soon as she's off, she breaks down, hyperventilating.
The dancer playing ROTHBART eyes her with concern.
You alright?
She looks up, sees his creepy MASK, and backs away.
Rothbart has to go back on stage to finish the Act.
Other CORPS MEMBERS surround her, chirping "You okay?, "What happened?" etc.
Dazed, Nina doesn't answer.
The music ends and there's a weak smattering of applause.
STAGE MANAGER That's intermission!
STAGE MANAGER Act 3 in fifteen.
STAGE MANAGER Nina sees Leroy on stage chewing David out, behind the closed curtain.
STAGE MANAGER Leroy runs his fingers through his hair, his back to Nina.
Nina cautiously approaches.
NINA It wasn't my fault.
NINA He dropped me.
He can't even look at her.
What a fucking disaster!
He walks away.
All alone, Nina sees everyone backstage looking at her.
She runs, escaping their stares.
She closes the door behind her, ready to cry.
She looks up, and finds Lily putting on makeup and wearing the Black Swan costume.
LILY Rough start, huh?
LILY Pretty humiliating...
NINA Get out of here.
LILY Wow...rude.
Lily coyly smiles, and continues applying makeup.
LILY (CONT'D) I'm worried about the next act.
LILY (CONT'D) Not sure you're feeling up to it.
NINA Stop.
NINA Just stop.
LILY How about...I dance the Black Swan for you?
Nina looks into the mirror.
Instead of Lily's reflection there's the Double.
NINA Leave me alone.
NINA Leave me alone.
But it's my turn.
Nina's fury rises up from inside.
NINA Leave me alone!!!
She charges...
And smashes her into the WALL LENGTH MIRROR, shattering it.
Shards fall everywhere.
The Double flips Nina over and wails on her.
Punch after punch.
Nina does her best to block the onslaught.
They scuffle, knocking things over, bumping into walls.
The Double gets her hands around Nina's neck...
Gasping for air, Nina tries to pull the hands free, but she's too strong.
Her hands frantically scramble along the surface of the floor.
The fingers barely touch the edge of a MIRROR SHARD, but can't grasp it.
The Double squeezes down.
The blood vessels in Nina's eyes BURST again.
Her neck starts to stretch unnaturally.
Strength surges through her body and she lunges...
Finally grabbing the SHARD.
And DRIVES it into the Double's stomach.
Nina glances at her hand, cut by the mirror, then back up.
The Double is now LILY.
Stunned, Lily looks down and touches the stab wound.
NINA (CONT'D) It's my turn.
NINA (CONT'D) Nina stares at her, breathing heavily, high on adrenaline.
A KNOCK on the door.
STAGE MANAGER Black Swan, places in 5.
Nina zips up the back to the Black Swan costume.
She deliberately applies the Black Swan makeup.
Dark eye shadow and rouge, maroon lipstick.
Dressed in black and wearing the dark make-up of the Black Swan, she looks fierce.
She stares at her reflection, her eyes burning RED.
New rash bumps pop up on her arms, the intensity building within.
Nina bursts onto stage as the Black Swan, accompanied by Rothbart.
She looks powerful, intense as she moves towards David.
His face shows his surprise.
Nina dances the first Pas de Deux with him.
They finish and
She walks away from him.
Alone, she looks at her arms, sees black points trying to push through again.
Some fully emerge as shiny BLACK FEATHERS.
She just watches them, not panicking, but accepting the transformation taking place.
Even beckoning it.
Her second entrance cue is played.
STAGE MANAGER That's you!
She leaps back on
For the Coda.
She takes a brief pause, closing her eyes once more, and then completely lets herself go.
She spins with ferocity.
More BLACK FEATHERS burst out from her shoulders and back.
At last, she truly embodies the Black Swan.
She finishes the Coda, punctuating her last spin with a sharp step that echoes through the theater.
The audience looks on, mesmerized.
Too stunned to clap at first.
111D Nina looks down at the stage, her face glazed with sweat 111D
She has returned to normal.
No feathers.
Normal eyes.
A woman.
She finally looks up at the audience, and they ERUPT in a standing ovation.
Nina walks to the front of the stage, takes her bow.
Nina looks up at the MASS OF BODIES filling the auditorium, vibrating with applause.
Proud, Nina smiles and bows again.
Again and again.
She finally runs off stage, the applause still going strong.
Nina enters the wings, other dancers cheer loudly.
Even Veronica and Galina.
She pushes past all the smiling faces.
It feels very surreal.
She sees Leroy clapping and shaking his head.
Blown away.
LEROY Get back out there!
LEROY Get back-
LEROY The kind of kiss that you can't stop.
LEROY Finally she disengages, staring at him in the eyes, but before he can say anything...
She walks towards her dressing room, a satisfied smile on her face.
She passes the stage manager.
STAGE MANAGER Great job.
STAGE MANAGER You got fifteen til the last act.
STAGE MANAGER She opens the door, makes sure no ones looking, and enters quickly.
She closes the door behind her, locks it.
Turns and sees the broken glass all over the floor.
She eyes the closed wardrobe.
A pool of blood drips out from under the door.
She picks up a towel and lays it over the blood.
She starts to undress.
Back in the White Swan costume, she re-applies the makeup.
There's a KNOCK on the door.
She looks towards it, her face only halfway made-up.
NINA One second.
NINA She peeks through and finds...
LILY looking back at her.
LILY Hey...you were amazing.
Nina's petrified.
LILY (CONT'D) Seriously.
LILY (CONT'D) I'm sorry things got so messed up between us.
LILY (CONT'D) Just, holy shit, totally blown away...
Nina barely manages a nod.
LILY (CONT'D) Anyway, wanted to tell you.
LILY (CONT'D) I'll let you finish.
LILY (CONT'D) Merde.
Lily turns and walks away.
Nina swiftly shuts the door.
She turns around, stares at the wardrobe.
She steps cautiously towards it, her face repeated countlessly in all the reflective shards.
She lifts the towel from the ground and looks at it.
It is clean.
No blood.
She looks down at the floor.
No blood there either.
She slowly opens the door to the wardrobe...
And finds it empty.
No body whatsoever.
She looks over at the broken mirror.
Sees her reflection staring back at her.
She stares at it for a long beat, and realizes something.
She touches her stomach and winces a little.
Pulls back her hand.
It's coated with red liquid.
Blood.
It's started to soak through the costume, creating a faint red spot.
The fabric is ripped at the center of the stain.
She feels inside for confirmation.
And discovers a stab wound, in her own stomach.
She pulls out the sharp tip of mirror still stuck inside.
Blood begins flowing more rapidly.
She drops the mirror.
STAGE MANAGER (V.O.) White Swan in 5.
In a daze, she sits down at the vanity, and finishes applying the rest of the White Swan's makeup.
Nina dances the final Pas de Deux as the White Swan.
Losing blood by the second, everything is woozy and blurry.
She can't do all the steps, but her performance is pained, making it poignant.
A spot of red begins to soak through at the center of her costume.
The music turns ominous, and VON ROTHBART, the evil sorcerer, comes onto stage.
Nina dances away from him, back upstage, towards the cliff.
It's time for her final leap.
Her energy fading, she teeters up the stairs of the set.
One step at a time...
She gets to the top, takes one last look around, at all the eyes watching her.
She notices a familiar face in the audience: HER MOTHER.
She watches with a profound sadness, tears streaking her cheeks.
In the front of Nina's costume, a dark circle has started to form.
Her blood fully seeping through.
And Nina leaps...
She falls through an endless void, her eyes closed.
She slowly twists around in the air, so that she's falling backwards.
She hears something.
Soft and muffled.
The faint sound of applause.
116C She lands slowly and comfortably on PADDING.
116C
The sound of applause is now loud, uproarious.
A group of BALLERINAS surround the mattress, clapping for her, each one dressed as a WHITE SWAN.
Leroy pushes through the group to get to her.
LEROY Listen to them!
LEROY They love you!
LEROY Get up, get up!
LEROY (CONT'D) I always knew you had it in you, little princess.
LEROY (CONT'D) Go take your bow!
Nina is too weak to move.
Lily pushes her way into the group and GASPS, pointing at Nina's abdomen.
Leroy follows her gaze and discovers the spot of blood, which has grown in size.
LEROY (CONT'D) What did you do?
NINA I felt it.
LEROY Oh my god.
NINA ...perfect.
LEROY Someone, get help.
NINA Shhh...
Leroy looks back at her.
She smiles.
NINA (CONT'D) It was perfect.
He understands.
The APPLAUSE grows more and more faint.
Her eyes glaze over and everything goes completely SILENT.
Nina lies there motionless, a smile frozen on her face.
CUT TO BLACK.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
