2012
Written by
Roland Emmerich & Harald Kloser
Second Draft February 19th, 2008
We listen to the immortal music of Mozart's Adagio of the Clarinet Concerto in A.
Space, infinite and empty.
But then, slowly all nine planets of our Solar System move into frame and align.
The last of them is the giant, burning sphere of the sun.
Just as the sun enters frame, a solar storm of gigantic proportion unfolds.
The eruptions shoot thousands of miles into the blackness of space.
Mozart's concerto filters from a jeep's stereo, fighting the drumming sounds of the monsoon rain.
PROF.
FREDERIC WEST, 66, listens to the music.
An Indian BOY playing by the roadside steers his wooden toy ship across a puddle.
The Professor turns to his driver, pointing to the boy.
PROF. WEST Watch out!
But it's too late.
The jeep drives straight through the puddle at full speed, sinking the boy's toy ship.
In the background, the jeep stops in front of a building.
The driver jumps out, leading the Professor towards its entrance.
The sign at the door reads: `Institute for Astrophysics - University of New Delhi'.
An endless mine shaft.
An old elevator cage comes to a grinding halt.
When Prof.
West steps out we see that he is accompanied now by a nervous DR.
SATNAM TSURUTANI, 32.
PROF. WEST How deep are we?
SATNAM 8200 feet.
SATNAM Used to be an old copper mine, Professor, sir.
As Prof.
West follows Satnam, he takes in the unusual setting for this science lab.
PROF. WEST Helmsley told me that the neutrino count doubled during the last sun eruptions.
SATNAM Correct, sir.
SATNAM But that is not what worries me...
They enter a large room with low hanging ceilings.
A small group of WHITE COATS look up from their computers, which all show images of the solar storm we witnessed earlier.
SATNAM (CONT'D) There was a new solar storm, so strong that the physical reaction got even more severe.
PROF. WEST How can that be?
SATNAM We don't know, Professor, sir.
Satnam walks over into another room.
There he opens a hatch on the floor and hot steam rises.
SATNAM (CONT'D) The neutrinos suddenly act like...
SATNAM (CONT'D) microwaves.
Prof. West slowly steps closer.
When he discovers that the water in the tank below is boiling, his face goes pale.
A major fund raising party is under way.
The setting is spectacular.
A terrace overlooking the Washington Mall and the Capitol Building.
ADRIAN HELMSLEY, 32, stands with a group of young POLITICAL AIDES.
He is the only African-American among them.
One of the aides spots CARL ANHEUSER, 58, White House Chief of Staff, working the crowd.
POLITICAL AID #1 Look at Anheuser.
POLITICAL AID #1 Anyone would think he was President.
POLITICAL AID #1 Did you hear, he wants us to sign in and out like school boys?
ADRIAN I still can't believe that Wilson chose him of all people to run the White House.
POLITICAL AID #2 Why not?
POLITICAL AID #2 Anheuser owns the Senate and the Congress.
ADRIAN Shame he's such a pompous ass.
ANHEUSER Somebody mention my name?
Adrian turns to see Anheuser smiling.
ADRIAN Yes sir...
ADRIAN No, sir.
ANHEUSER Which one is it?
ADRIAN We were talking about what a great speech you gave tonight.
ADRIAN Well done, sir.
ANHEUSER It's Helmsley, right?
ANHEUSER I'll remember that.
Anheuser walks away with a dangerous smile.
POLITICAL AID #2 That guy scares the shit out of me.
At that moment Adrian's cell phone rings.
ADRIAN Professor West?
PROF. WEST I've been trying to reach you!
Prof. West is on the phone.
In the background we make out Satnam's family around the dining room table.
PROF. WEST Listen, Adrian.
PROF. WEST The situation is much worse than we thought...
Satnam quiets his little son.
It is the boy we saw earlier with his toy ship.
Adrian follows Anheuser through a hallway of the White House, papers in hand.
ADRIAN Sir, the President needs to know this.
ANHEUSER Helmsley, how long have you been on the job as science advisor?
ADRIAN Four months this week.
ANHEUSER I would say that's enough time to learn that we have rules here.
ANHEUSER You'll just have to wait until the quarterly science briefing.
ADRIAN If this is about what I said last night, I am truly sorry, sir.
ANHEUSER So you didn't like my speech?
Exasperated, Adrian holds out the papers to him.
ADRIAN Can you please have a look at this, sir?
ADRIAN It's really important.
Finally, Anheuser rips the papers out of his hands and starts to walk away, reading.
Suddenly he slows down.
ANHEUSER Who wrote this?
ADRIAN An Indian astrophysicist I graduated with from Harvard and Prof.
ADRIAN West, the preeminent geologist in the US.
ANHEUSER Who else knows about it?
ADRIAN No one, sir.
ANHEUSER Let's keep it that way, Helmsley.
Anheuser walks away.
G8 Summit.
Riot police control the unruly crowd with water cannons.
We see PROTESTERS with Anti Globalization signs behind a fence.
A convoy of limousines is approaching a historic building.
We follow the American delegation into the conference room, where the other G8 delegations are seated around an enormous table.
The President of the United States, THOMAS F. WILSON, 56, doesn't sit down.
He addresses the room and everybody goes quiet.
PRESIDENT WILSON Good Morning...
For the first time we see the President's face.
He is African- American.
PRESIDENT WILSON (CONT'D) I hereby present a motion to meet privately with my seven fellow Heads of State, kindly excluding the rest of the delegates.
A murmur erupts.
The Russian President SERGEY MAKARENKO, 62, whispers to one of his interpreters.
RUSSIAN INTERPRETER Mr. Makarenko wishes to have his interpreters present.
President Wilson looks over to the Russian Colleague.
PRESIDENT WILSON Mr. President, judging from the conversations we've had in the past, I can assure you, your English is absolutely fine, for what I have to say.
As the Russian President waves his interpreter away, all the international delegates leave as well.
The huge doors of the hall close.
A secret service officer in the sound booth switches off the recording equipment to the chamber.
The President gathers himself.
PRESIDENT WILSON (CONT'D) Six months ago I was made aware of a situation so devastating, that at first, I refused to believe it.
PRESIDENT WILSON (CONT'D) However through the concerted efforts of the brightest scientists of several nations, we have now confirmed its validity.
Dead silence.
PRESIDENT WILSON (CONT'D) The world as we know it, will soon come to an end.
A huge Chinese military helicopter blasts through a majestic mountain valley in Tibet.
We are at the top of the world.
A Chinese COLONEL, wearing dark sun glasses, watches from the chopper as the army forces the evacuation of the villages and monasteries.
VOICE You will have new houses, electricity and running water...
Someone speaks on a megaphone in the village square as villagers are evicted by soldiers and herded into trucks.
VOICE ...
VOICE Some among you will even have the chance to work for the glorious People's Republic of China building the biggest dam project in the world...
NENG PANG, a young monk, 18, is loaded into a truck together with his PARENTS, both in their 60's.
Neng's older brother, LIN PANG, 25, is part of a huge crowd of young men and women staying behind by a Tibetan school building.
He turns and yells after the truck.
LIN I will send you money mother.
The Colonel with the dark glasses steps up, addressing the masses.
COLONEL Who can read and write?
Eager hands fly up in the air.
An official makes notes.
COLONEL (CONT'D) Who can weld?
Lin's hand shoots up in the air.
We hear a siren echoing through the mountains and suddenly an explosion.
Lin turns.
In the BACKGROUND, a series of explosions punch enormous holes into the side of the mountain, showering rock everywhere.
A MAN in a dark suit walks through a hallway of the Dorchester looking like your typical MI-6 agent.
The decor is plush and luxurious.
He's stopped by two security men who frisk him.
Heavily ringed fingers flip through a folder.
MI-6 OFFICER Has his Highness had the opportunity to study the dossier?
A SAUDI PRINCE looks up and nods without expression.
SAUDI PRINCE You must understand I have a very big family.
SAUDI PRINCE Mister...
MI-6 OFFICER Isaacs.
SAUDI PRINCE Mister Isaacs, one billion dollars is a lot of money.
MI-6 OFFICER I'm afraid the amount is in Euros, your Highness.
A group of dark figures in overalls walk past famous Renaissance paintings.
They stop at the Mona Lisa.
MANFRED PICARD, 63, head of the French National Museums, stands by LAURA, a young African-American woman in her late 20's.
They observe the specialists opening the case of the famous painting.
A whoosh of air as the vacuum seal breaks.
MANFRED PICARD Laura, I'm putting a lot of trust in your people.
Laura answers in almost perfect French.
LAURA There are too many crazy people who could hurt her, Manfred.
LAURA The World Heritage Foundation has done this all over the world.
In the BACKGROUND the Mona Lisa is taken off the wall and replaced with a perfect replica.
Picard still looks uneasy.
He watches as the real Mona Lisa is sealed into an airtight case.
MANFRED PICARD And she'll be safe now?
MANFRED PICARD Tucked away in the Swiss Alps?
LAURA Perfectly safe.
Picard looks suspicious but says nothing.
The CAMERA MOVES IN on the face of the fake Mona Lisa until all we see is her mysterious smile.
Lifeless bodies encircle a huge fire pit.
They resemble the rays of the sun.
In the background we see the famous step pyramids of Tikal.
NEWSCASTER ...
NEWSCASTER The mass suicide was discovered by a BBC documentary crew in the ancient Mayan city of Tikal...
Many of the dead are women and children looking peaceful and are surrounded by colorful flowers.
NEWSCASTER (CONT'D) ...
NEWSCASTER (CONT'D) the victims were said to have adhered to the Mayan-Quiche Calender which predicts the end of time to occur on the 21st of December this year, due to the sun's destructive forces...
The CAMERA slowly pulls out and we are in--
A shabby apartment in Silverlake.
The TV is on.
NEWSCASTER ...
NEWSCASTER Strangely enough, scientific records do support the fact that we are heading for the biggest solar climax in recorded history...
A small tremor rocks the apartment and the dishevelled face of JACKSON CURTIS, 33, pops up from behind the couch.
He fell asleep at his laptop last night.
JACKSON Oh no.
JACKSON Not again.
One look at his watch and he is off running.
He throws some clothes and a toothbrush in a bag.
His cell phone rings.
JACKSON (CONT'D) Hello?...
JACKSON (CONT'D) What do you mean?
JACKSON (CONT'D) I'm not late.
JACKSON (CONT'D) It's not even 10:30...
Jackson turns off the TV and darts towards the door, stopping only to slide his laptop into a knapsack.
As he turns, he stumbles over a stack of books, all shrink-wrapped and identically titled: `Farewell Atlantis'.
JACKSON (CONT'D) Damn it!
JACKSON (CONT'D) Kate, I'm on my way...
JACKSON (CONT'D) For god's sake...
Frustrated, he kicks them out of his way and exits.
We hold on the books and realize that Jackson's photograph is on their back covers.
The phone call continues as Jackson opens the garage door, struggling to pack his old SUV with camping equipment.
JACKSON They're kids, Kate, going on vacation.
JACKSON It's not a doctor's appointment...
JACKSON it's supposed to be fun.
JACKSON You remember that, right?
JACKSON Fun?
He tries to start the engine, but the battery is dead.
Frustrated, he hits the steering wheel.
Jackson runs across the street with his camping equipment, throwing it into the trunk of a stretch limo parked by the curb.
JACKSON ...
JACKSON I know it's mosquito season at Yellowstone, Kate.
JACKSON I'll pick some up on the way.
He notices a deep crack in the asphalt.
His neighbors, an elderly couple, stand there and stare at it.
NEIGHBOR Merrill, we should move back to Wisconsin.
Jackson gets into the limo and speeds off.
Jackson drives through LA with the radio on.
RADIO HOST ...
RADIO HOST Those shake-proof coffee mugs are a genius idea, and they just show the true nature of us Californians.
We pass a family frantically loading boxes into a van.
RADIO HOST (CONT'D) We'll not bow to little inconveniences like these so called `mini-quakes'...
Jackson passes a man in a wheelchair.
He's holding up a cardboard sign: `Repent - The End is Near'.
Jackson stops and honks in front of an upscale Westwood home.
RADIO HOST ...
RADIO HOST If you have a funny `mini-quake' story you wanna share, call Lisa & Randy at 1-800...
Jackson switches the radio off.
Two kids NOAH, 10, and LILLY, 7, come running down the driveway.
They slow down, as they see the limo.
NOAH Jackson, what is this?
JACKSON Don't call me Jackson, Noah, I'm your father.
Lilly yells from inside the limo.
LILLY Noah!
LILLY Look!
LILLY Daddy's got Space-Busters in the car...
LILLY and Space-Busters 2.
LILLY Awesome!
Their mother, KATE CURTIS, 32, a beautiful woman appears.
KATE So what, you're a chauffeur now?
KATE What happened to the temp work?
JACKSON This is better hours for me.
JACKSON Means I can still write.
KATE Of course.
Kate's new boyfriend, GORDON SILBERMAN, 43, pulls out of the garage in his Porsche wearing his Bluetooth.
GORDON Simone, how many times have I told you, we don't do Lipo on Fridays.
GORDON It's too messy.
Jackson smiles bitterly.
Gordon waves at the kids.
GORDON (CONT'D) Have fun guys.
GORDON (CONT'D) And watch out for those bears.
GORDON (CONT'D) Nice car.
Jackson waves grudgingly as Gordon pulls away.
KATE Noah needs to read twenty pages from his book each day...
She follows Jackson to the car with a bag of pull-up diapers.
KATE (CONT'D) ...
KATE (CONT'D) and Lilly has to put these on, before she goes to sleep.
JACKSON Still?
He shuts the trunk and gets back behind the wheel.
She looks at him seriously.
KATE Jackson, they've been really looking forward to this you know.
KATE Don't let them down.
He nods as the car pulls away.
HARRY HELMSLEY, 73, and his partner TONY DELGADO, 68, board an enormous cruise ship, the `Freedom of the Seas'.
Harry is African-American, Tony is Italian.
He carries a large case.
They pass a poster: `Jazz Night with Harry Helmsley & Tony Delgado'.
HARRY So this time we'll hit the Japs.
TONY So what?
HARRY Well Tony, electronics are cheap there and...
HARRY you could visit your boy Will.
TONY Afternoon ladies...
TONY shoots a charmers smile at a couple of older single ladies on sun loungers.
They smile back coyly.
HARRY Are you even listening to me?
TONY Yes unfortunately I am Harry.
HARRY I heard from Audrey you're a grandpa now.
TONY Why don't you keep your nose out of my family.
TONY You're cramping my style.
HARRY He married a Japanese girl - how is that the end of the world?
HARRY You should at least go see him.
TONY Why?
TONY Do you see your boy?
HARRY Not as much as I'd like.
HARRY DC is a long way.
HARRY But at least we talk.
TONY What about?
HARRY Life, how short it is...
Suddenly they're thrown off balance by a large swell that pulls the massive `Freedom of the Seas' away from the landing, about ten yards.
The next moment, the ship slams back against the dock with an earthshaking BOOM.
TONY What the hell was that?
A murmur goes through the crowd.
Luckily nobody is injured.
The phone rings twice before Laura switches on a light.
We catch a glimpse of a framed photo of her and Adrian.
She answers the phone.
MANFRED PICARD Laura?
MANFRED PICARD They lied to us.
LAURA Manfred is that you?
Picard is speeding in his Peugeot, anxiously checking his rear view mirror.
MANFRED PICARD I had my suspicions.
MANFRED PICARD I should have said something.
MANFRED PICARD They are following me.
LAURA Who is?
MANFRED PICARD They may be listening to us too.
MANFRED PICARD Laura the Heritage Foundation is a sham.
Picard's car approaches a tunnel.
LAURA What?
MANFRED The art you collected, it's not in the Alps.
The Peugeot enters a tunnel.
LAURA Then where is it?
A huge blast rips through the tunnel as his car explodes.
JACKSON AND LILLY (singing along to the
RADIO) `We all live in a Yellow Submarine...'
They're driving through the glorious landscape of Yellowstone National Park.
Noah sits in the back with headphones on playing Space-Busters 2.
As they pass over a ridge, the music station is overpowered by a talk show filtering through.
We hear a raspy and excitable voice.
RADIO HOST ...
RADIO HOST After what is going on in La-La- land with all those surface cracks, I told myself: Get your stupid ass to Yellowstone.
RADIO HOST I don't want to miss all the great fun, when it finally blows...
Lilly reaches for the dial of the radio.
LILLY What happened to the music?
JACKSON Hang on, sweet pea, let daddy listen to this for a moment...
Jackson corrects the dial to get better reception.
RADIO HOST ...
RADIO HOST There's been government people flying in and out all morning.
RADIO HOST And trust me, they did not look happy...
A huge black helicopter brushes over the limo.
RADIO HOST (CONT'D) ...
RADIO HOST (CONT'D) Folks, always remember, you heard it first from Charlie.
They watch in awe as the chopper disappears behind a ridge.
Laura bursts in and heads straight for the TV.
The President looks up from his desk.
LAURA You have to see this.
Sally the President's Secretary enters, flustered.
PRESIDENT WILSON It's alright Sally.
Sally closes the door as Laura turns up the TV.
CNN ANCHOR ...
CNN ANCHOR Mr. Picard had been the director of the French National Museums for 24 years.
CNN ANCHOR As fate would have it his assassination took place in the same Paris tunnel where Princess Diana died in 1997.
The President comes around his desk.
Laura looks at him distraught.
LAURA I just talked to him, Dad.
LAURA He told me the world Heritage Foundation is a sham.
LAURA Is that true?
The President shoots an anxious look across the room.
Laura turns and suddenly realizes that Adrian is standing in the corner.
LAURA (CONT'D) You knew too?
LAURA (CONT'D) You sleep with me and you didn't say anything?
Adrian looks ashamed.
LAURA (CONT'D) I can't even look at you.
LAURA (CONT'D) Either of you!
PRESIDENT WILSON Honey, calm down.
LAURA A man was killed!
LAURA I want the truth Dad.
LAURA Right now.
A dense forest trail.
We hear Lilly before we see her.
LILLY Daddy, where are we going?
JACKSON To a very special place, Lil'bee.
JACKSON It's a lake.
JACKSON A place where mommy and daddy fell in love.
JACKSON Remember the book I gave you?
NOAH I don't want to know where you and mom had sex.
NOAH I'm not ready for that, Jackson.
JACKSON I'm your dad, Noah.
LILLY Daddy!
Jackson runs to catch up with Lilly who has reached a fence with a `keep out' sign posted.
JACKSON This wasn't here before.
Jackson starts to climb the fence.
NOAH Don't you see the signs?
JACKSON It's fine guys.
Jackson and his kids crest a ridge.
They look down on a parched basin with cracked terrain.
JACKSON It's gone.
JACKSON The whole darn lake is gone.
JACKSON I swear you guys there was a lake here.
The kids roll their eyes.
A puddle of water is all that remains of the lake.
Jackson and the kids walk into the basin, unaware of being watched
Jackson spots an electronic measuring device and crouches to have a closer look.
Elsewhere in the lake bed, we see sand seeping through CRACKS in the ground.
NOAH Jackson!
When he looks up, he sees heavily armed soldiers coming towards them from all sides.
JACKSON It's okay, Noh'.
Through the BINOCULARS, we see Jackson and his kids arrested and led over a ridge.
With this we reveal an ENORMOUS RESEARCH FACILITY with hundreds of tents and vehicles surrounding a massive drilling tower.
Adrian Helmsley and Prof.
West exit the drilling tower, both studying papers.
Adrian notices Jackson and his kids nearby, being interrogated by an OFFICER.
ADRIAN I'll be with you in a second, Professor.
Adrian walks towards them.
Jackson stares at the officer with defiance.
OFFICER ...
OFFICER And then you climbed over a posted fence?
OFFICER Just like that?
NOAH I told you.
JACKSON Isn't this supposed to be a National Park?
JACKSON There shouldn't be fences.
JACKSON What are you guys doing around here anyway?
ADRIAN We're geologists...
Jackson turns and sees Adrian standing there.
ADRIAN (CONT'D) I'll handle this officer.
ADRIAN (CONT'D) Thank you.
The officer reluctantly hands him Jackson's license.
JACKSON So, where did the lake go?
ADRIAN That's what we're trying to find out.
ADRIAN We think this whole area has become potentially unstable.
ADRIAN I would advise you to take your kids and leave, Mr...
He throws a look at Jackson's drivers license.
ADRIAN (CONT'D) ...
ADRIAN (CONT'D) Curtis.
He looks up at Jackson with renewed interest.
ADRIAN (CONT'D) Are you by any chance the Jackson Curtis, the author of `Farewell Atlantis'?
JACKSON Yeah, that's me.
Jackson straightens up proudly.
Lilly smiles.
ADRIAN What a coincidence.
ADRIAN I'm reading your book, as we speak...
ADRIAN first third, around day 300, when the shuttle loses communication with earth and drifts off into space.
JACKSON You're one of lucky 422 who bought it.
ADRIAN Actually I didn't buy it.
ADRIAN My father gave it to me.
JACKSON Oh, I see.
Prof. West waves at Adrian from one of the container labs.
Adrian hands back Jackson his drivers license.
ADRIAN Officer, can you return them to the campgrounds, please.
ADRIAN Pleasure to meet you, Mr. Curtis.
Jackson and his kids look after Adrian hurrying away.
LILLY He was very nice.
JACKSON Yes he was, Lil'bee.
Jackson and the kids walk back to the campgrounds when suddenly CHARLIE FROST, 62, a crazy looking guy with binoculars around his neck, stands in their way.
CHARLIE FROST What did the government guys tell you?
Jackson looks at him, instinctively picking up Lilly.
JACKSON They think it's not such a good idea to climb over their fences.
JACKSON They feel the area is unstable.
Charlie bursts out laughing.
CHARLIE FROST Unstable!
CHARLIE FROST Ha-ha!
CHARLIE FROST They say its unstable!
CHARLIE FROST That's funny...
With this he turns around and leaves.
Jackson is sitting on a camp chair, right outside the tent.
He's on his laptop, looking enquiringly at an aerial picture of Yellowstone on Google earth.
In the background we see the kids are in the tent.
NOAH There are mosquitos in here.
NOAH Did anybody spray the tent?
Jackson looks up, remembering he forgot the spray.
JACKSON We'll get some of that tomorrow.
JACKSON For tonight just put your head under the blankie.
LILLY Daddy you said you weren't gonna work on your book.
JACKSON I'm not Honey, I promise.
JACKSON Are you wearing your pull-ups?
Lilly nods as Jackson walks over and tucks her into bed.
He kisses her good night.
He turns and is surprised to see Noah typing a text on his cell phone.
JACKSON (CONT'D) Did mommy buy you that?
NOAH No...
NOAH Gordon gave it to me for my birthday.
Jackson takes the phone from out of Noah's hands.
JACKSON Noah.
JACKSON Things like a cell phone have to be discussed in the family.
NOAH What family?
Jackson reads the message Noah has typed `Hey Gordon, Camping Sucks!'.
Hurt, Jackson hands back the phone.
JACKSON Go to sleep guys.
Commotion.
The base packs up.
Adrian and Prof.
West duck low as they board a chopper.
Adrian is on the phone.
ADRIAN ...
ADRIAN You have to immediately inform the President, Mr Anheuser.
ADRIAN The readings look much worse than I expected.
ADRIAN (CONT'D) Plus Satnam's neutrino figures from India confirm...
We hear Anheuser, yelling.
ANHEUSER ...
ANHEUSER But you guys said...
ADRIAN We were wrong!
ADRIAN By five or six months...
A second later the chopper lifts off.
Jackson has his laptop open with the cursor blinking away on the words `Chapter Seven'.
But he can't concentrate on writing after what Noah has said.
A chopper flies overhead.
Jackson follows it's path over the campsite and his eyes fall on an American flag fluttering on top of a massive radio antennae.
This belongs to an RV truck.
Through the RV's window, Jackson sees the silhouette of Charlie Frost, the guy with the binoculars, speaking into a microphone.
Curious, Jackson flicks on the radio and twists the dial.
ON THE RADIO ...
ON THE RADIO We have a listener calling in.
ON THE RADIO Bill from Cooke City, you're on the Charlie Frost Show.
ON THE RADIO I wanted to know, where will this all start?
Jackson is intrigued.
He puts his laptop down.
ON THE RADIO (CONT'D) Well, something like this could only originate in Hollywood, Ha-Ha!
ON THE RADIO (CONT'D) But seriously, they've got the earth cracking under their asses already, Bill.
Jackson climbs out of his car and starts towards the RV.
He can still hear the radio.
ON THE RADIO (CONT'D) Our family believes in the gospel of our Lord Jesus.
ON THE RADIO (CONT'D) We have nothing to fear, Charlie.
ON THE RADIO (CONT'D) Good for you Bill, good for you!
Charlie hits a switch.
Music starts playing.
The Doors, `The End'.
CHARLIE FROST ...
CHARLIE FROST This is Charlie Frost reporting live from Yellowstone National Park, soon to become the world's largest active volcano.
Charlie is about to take a bite of his sandwich, when there's a knock on the door.
Jackson sticks his head in.
JACKSON Hi.
JACKSON Mind if I join you?
CHARLIE FROST I only got a few minutes.
Charlie bites into his sandwich as Jackson looks around at all the equipment.
JACKSON I just heard part of your broadcast...
JACKSON Mind me asking a question?
JACKSON What exactly is it...
JACKSON that will start in Hollywood?
CHARLIE FROST Actually it's gonna be the whole west coast...
JACKSON What are you talking about?
CHARLIE FROST The apocalypse, the end of days.
CHARLIE FROST The Mayans knew it, the I Ching and the Bible, kind of...
Charlie looks at his watch.
CHARLIE FROST (CONT'D) I got to eat...
CHARLIE FROST (CONT'D) Just check my blog.
CHARLIE FROST (CONT'D) You can download it for free.
Charlie clicks on his laptop.
CHARLIE FROST (CONT'D) ...
CHARLIE FROST (CONT'D) However, we do take donations.
A crudely animated film starts to play.
Charlie narrates on screen in an overly dramatic fashion.
CHARLIE'S VOICE In the year 2012 a cataclysmic event will unfold.
CHARLIE'S VOICE Caused by an alignment of the planets in our solar system that only happens every 640,000 years...
CHARLIE'S VOICE Just imagine the earth as an Orange...
Charlie appears as an animated figure holding an orange.
CHARLIE'S VOICE (CONT'D) ...
CHARLIE'S VOICE (CONT'D) our sun will begin to emit such extreme amounts of radiation, that the core of the earth will melt - that's the inside part of the Orange, leaving the crust of our planet free to shift.
On screen the middle of the orange shrinks, now the skin moves freely around it.
CHARLIE'S VOICE (CONT'D) In 1958, Prof.
CHARLIE'S VOICE (CONT'D) Hapgood named it `Earth Crust Displacement'...
A faded portrait of a scientist appears on screen.
CHARLIE FROST ...
CHARLIE FROST and Albert Einstein endorsed it...
The infamous photo of Einstein, sticking out his tongue.
CHARLIE FROST (CONT'D) The forces of mother nature will be so devastating it will bring an end to this world on winter solstice 12-21-12.
The film ends with an image of the whole earth covered with water.
Charlie shuts the laptop.
CHARLIE FROST (CONT'D) Pretty neat, huh?
CHARLIE FROST (CONT'D) It's a big hit on YouTube.
CHARLIE FROST (CONT'D) I did the animation myself.
CHARLIE FROST (CONT'D) I know what you're thinking.
CHARLIE FROST (CONT'D) But all the governments know about this.
JACKSON If they all knew, don't you think somebody would tell us?
CHARLIE FROST They can't.
CHARLIE FROST Just think about it.
CHARLIE FROST First the stockmarket would crash...
Charlie opens a can of beer.
Phsssh!
CHARLIE FROST (CONT'D) Then the economy...
CHARLIE FROST (CONT'D) boom.
CHARLIE FROST (CONT'D) The dollar...
CHARLIE FROST (CONT'D) boom.
CHARLIE FROST (CONT'D) And then the people in the streets...
CHARLIE FROST (CONT'D) Boom, boom!
CHARLIE FROST (CONT'D) Pandemonium, revolution, war!
CHARLIE FROST (CONT'D) They would never tell us.
CHARLIE FROST (CONT'D) Beer?
Jackson shakes his head still struggling to digest this.
CHARLIE FROST (CONT'D) Only if you're some Sheik, Bill Gates, or maybe one of those Russian billionaires do you stand a chance to buy a seat.
JACKSON A seat?
CHARLIE FROST They're building spaceships, man.
JACKSON Oh...
JACKSON I see.
CHARLIE FROST No really...
CHARLIE FROST One of my listeners, a geography professor at UTSC, has even figured out where they're building them.
CHARLIE FROST He sent me a map.
JACKSON Well...
JACKSON Charlie, I think I gotta go.
JACKSON My kids are sleeping.
Charlie looks at him bug eyed.
CHARLIE FROST Get them out of Yellowstone, man.
CHARLIE FROST It's gonna get ugly here.
JACKSON Night, Charlie.
As Jackson exits, Charlie gets back on the air.
CHARLIE FROST Sorry for the delay, folks.
CHARLIE FROST But even in times like these, a man has got to eat...
Westwood.
The parking lot of Gelson's is nearly empty.
Eerie silence.
Suddenly some of the cars begin to shift in place from an unseen force.
A small CRACK creases the asphalt and slowly crawls towards the brightly lit supermarket.
Muzak is playing.
Kate and her boyfriend Gordon are shopping late.
She picks up some pull-ups for Lilly, Gordon steps up behind her, wrapping his arms around her waist.
GORDON Why don't we make a baby?
He reaches up and touches her breasts.
KATE Stop it!
KATE We're in public.
Gordon lets go of her with mock disappointment.
GORDON Honey, I created them.
GORDON And now suddenly I can't touch them?
Kate pushes him away and moves on.
A few customers are paying at the checkout stand.
BEHIND THEM: Huge glass windows reveal cars slowly sliding into the ever widening crack in the parking lot.
Nobody inside notices.
Gordon catches up with Kate.
GORDON (CONT'D) You always act strange after he shows up?
KATE Just because I don't care for your arrogant humor doesn't mean I'm acting strange.
KATE He is the father of my kids.
GORDON Maybe biologically.
GORDON Can I remind you what that guy did?
GORDON First you gave up med school to have Noah...
GORDON Then you practically raise him and Lilly by yourself while he sat glued to a laptop writing that junk.
KATE Some of his stuff is actually...
KATE He's published Gordon.
GORDON Yeah, published!
GORDON You know your mother was right.
GORDON You've always been drawn to guys with lofty dreams and empty pockets.
GORDON But not this time right, sweetheart?
Kate smiles awkwardly and picks up a can of soup.
The shelf in front of her shakes for a moment.
KATE Did you see that?
GORDON See what?
Kate slowly puts the cans of soup into her cart and looks around.
Gordon senses a problem between them.
GORDON (CONT'D) You know Kate, we have to keep working at this...
GORDON (CONT'D) our relationship.
GORDON (CONT'D) Because I won't end up being just a re-run of you and Jackson.
GORDON (CONT'D) I mean Honey, I feel like...
GORDON (CONT'D) something is pulling us apart?
Before Gordon finishes his sentence--
A violent ROAR!
From front to back, the entire supermarket rips open right between Kate and Gordon.
The few customers scream in horror at the sight of the huge crevasse forming beneath them.
Kate and Gordon are thrown up against opposite aisles holding on for dear life.
They cling to the columns as the shelves fold into the ever widening crack...
Jackson puts down some groceries at the checkout.
JACKSON Just stop scratching.
JACKSON You'll get them infected.
He smiles at the female cashier behind the counter who does not look friendly.
JACKSON (CONT'D) Something for Mosquito bites please?
CASHIER Before or after?
JACKSON What?
The woman looks at Lilly and Noah with their red lumps.
CASHIER I'd get before and after.
She slams two mosquito products on the counter.
LILLY Look!
LILLY Mrs. Birnbaum, my teacher is on
On the store's TV: A heavy-set blonde WOMAN, 45, speaking to a reporter in front of Gelson's.
NOAH That's our supermarket.
The gap in the ground is enormous now, at least half a mile long and 200 feet wide.
JACKSON Kids, we have to pack up and go find mommy.
President Wilson and Anheuser walk towards the Situation Room.
ANHEUSER Sir, you have to initiate the boarding process immediately.
PRESIDENT WILSON Is this even possible?
PRESIDENT WILSON What's our information from China?
ANHEUSER They estimate four of the ships will be ready for launch.
The President is shocked by this news.
PRESIDENT WILSON Only four?
ANHEUSER If it's alright with you sir, I'll brief the panel about the new development.
PRESIDENT WILSON I'd rather have Adrian do that.
PRESIDENT WILSON They trust him.
PRESIDENT WILSON I told him to be in on the meeting.
Anheuser fumes as they enter the situation room.
Flat screens line the walls.
A video conference is under way with each of the G8 members represented.
PRESIDENT WILSON Ladies and Gentlemen, we all knew this day would come.
PRESIDENT WILSON But we never imagined it would come this soon.
He looks over to Adrian.
PRESIDENT WILSON (CONT'D) I would like to pass this over to my science advisor, Adrian Helmsley.
Adrian steps up and gathers himself.
Anheuser watches.
ADRIAN I'll make this brief...
Pointing to a set of charts.
ADRIAN (CONT'D) ...
ADRIAN (CONT'D) According to our latest data from Yellowstone, the temperature of the subterranean crust of the earth, the cement that holds our landmass in place, is increasing at a rapid rate, much faster than anticipated...
All the heads of state are glued to his words.
ADRIAN (CONT'D) ...
ADRIAN (CONT'D) This causes extreme polar instability.
ADRIAN (CONT'D) The magnetic fields have decreased by more than 80% over the last 48 hours.
The German Chancellor, a woman, interrupts.
GERMAN CHANCELLOR How much time do we have, Mr. Helmsley?
Adrian glances to Professor West, standing in the back.
ADRIAN Two, maybe three days if we're lucky.
The Prime Minister of Italy breaks in, upset.
ITALIAN PRIME MINISTER How can you speak about luck in such a situation?
ANHEUSER Apologies Prime minster.
ANHEUSER He's still new to the job.
President Wilson steps up.
PRESIDENT WILSON Nevertheless, Mr. Antonioni, we have to make an immediate decision.
We hear CHEERING and APPLAUSE.
BOXING ANNOUNCER Introducing the 320 pound muscle machine from the Ukraine...
The arena is filled to its max.
The crowd is on its feet.
BOXING ANNOUNCER ...
BOXING ANNOUNCER and tonight's challenger for the heavy weight world championship of the world.
BOXING ANNOUNCER Here he is...
BOXING ANNOUNCER Mister Zultan Balashin!
The crowd ROARS as the boxer and his entourage enter.
The CAMERA moves in on a tall man with blonde clean cut hair.
He is well built, wearing designer clothing from head to toe.
YURI KARPOV, 45, stereotypical Russian oligarch.
He approaches the ringside corner and whistles.
YURI Zultan!
The nervous boxer turns.
ZULTAN Ah, finally, Yuri.
ZULTAN I thought I would not see you.
Yuri hits the boxer's gloves.
Zultan is nervous.
His coach steps in.
COACH He needs to concentrate now, Mister Karpov.
YURI You shut up...
YURI when I talk to my boy, understand?
COACH Yes, Mr. Karpov.
YURI Good...
YURI That is good.
YURI (in Russian to the
BOXER) Zultan my friend.
BOXER) Do not forget.
BOXER) We are fighters.
BOXER) We never go down.
BOXER) We always stay on our feet...
Zultan just keeps nodding, pumping himself up.
YURI (CONT'D) ...
YURI (CONT'D) No matter who is hitting us.
YURI (CONT'D) No matter how hard.
GONG.
First Round.
The fight is on.
YURI (CONT'D) Now, go kill the bastard.
Yuri walks to his seat, sitting down next to his trophy:
TAMARA, 28, blonde, wears the shortest mini one can imagine, designer shoes, handbag, glasses and boobs.
In her lap she holds CAESAR, a tiny dog wearing a diamond collar.
In the ring the boxers maul at each other.
Yuri's cell phone beeps.
It's a text message:
Yuri's whole demeanor changes.
Without a word, he gets up and walks out of the arena.
TAMARA Yuri bear...
TAMARA where are you going?
Yuri does not respond as he squeezes through the crowd.
Zultan, the boxer, notices Yuri leave.
In that split second distraction, he is hit HARD and goes down for the count.
The crowd ROARS!
Jackson has driven all night.
The sun rises, a giant glowing orb.
PUBLIC RADIO NEWS ...
PUBLIC RADIO NEWS Caltech believes that the incident in the Westwood supermarket has released most of the surface tension...
Jackson pulls up.
The kids are asleep.
PUBLIC RADIO NEWS ...
PUBLIC RADIO NEWS It looks like life in the city will soon be back to normal, Mayor Gonzales said at an early morning news conference from his home in Hancock Park.
Jackson switches off the radio and wakes his kids gently.
JACKSON Lilly, we're home sweetie.
JACKSON Wake up big man.
Kate heads to the car.
Still sleepy, the kids grab their stuff and run into her arms.
KATE Oh honey, I'm so glad you're back...
KATE And you too, darling.
JACKSON We tried calling but -
LILLY I'm hungry Mummy.
KATE At least it looks like the Mosquitos ate well.
She looks at Jackson and softens.
KATE (CONT'D) Wanna come in?
Gordon appears at the door.
Jackson watches painfully as Noah runs and gives Gordon a big hug.
His cellphone beeps with a message.
YURI Where are you Curtis?
Yuri stands at a huge window overlooking the strip talking into his phone.
JACKSON Back in Westwood, Mister Karpov.
YURI Good.
YURI That is good.
YURI I'm sending the Gulfstream to pick up Alec and Oleg.
Tamara hovers in the background packing her Louis Vuitton luggage.
Caesar, her little dog, watches from the bed.
TAMARA Tell him to bring Caesar's raincoat, it's in the Range Rover.
Yuri brushes her off.
While talking to Yuri, Jackson is standing in front of the open trunk, changing into his chauffeur suit.
YURI Curtis, make sure you get my boys as fast you can.
A palatial home.
Completely gaudy.
The twins, ALEC and OLEG, wait impatiently.
They are 12 years old and wear identical clothing by Dior.
ALEC Curtis, you are late.
Jackson ignores him and starts throwing the luggage into the limo.
The other twin notices his muddy sneakers.
OLEG Careful with our stuff.
OLEG Don't get it dirty.
Ahead of the limo a crowd has formed in the streets, singing songs and chanting about the end of days.
A SKINNY MAN with a ponytail preaches from the scriptures.
PREACHER ...
PREACHER There will be famines, pestilences and earthquakes, sayeth the Lord.
Jackson has to maneuver through the people.
Banners read: `Prepare for the End'-- 'You cannot escape his judgement'--
Alec looks up from his video game, annoyed.
ALEC Curtis, can't you go faster?
JACKSON Are you guys blind?
JACKSON I can't run people over.
OLEG Why not?
OLEG They're idiots anyway.
Jackson shoots these spoilt brats an angry look.
Jackson stops in front of the Gulfstream.
SASHA, 40, Yuri's Russian pilot is expecting them.
SASHA Hey Jackson.
SASHA Took you a while...
Jackson mutters under his breath as he unloads the luggage, dropping one of them on Alec's foot on purpose.
ALEC Ouch!
ALEC Be more careful!
The other twin has noticed Jackson's intensions.
He gets into his face.
OLEG Now you're laughing, Curtis.
OLEG But we are going on a big ship.
OLEG We will live...
OLEG and you will die.
Oleg grins back at Jackson as the jet door closes.
The Gulfstream taxis onto the runway.
As Jackson turns back to the car a fine surface crack shoots across the tarmac.
We hold on his face as it hits him like a ton of bricks:
Frantically Jackson looks around and spots a MAN in overalls working on a twin engine Cessna.
He runs to him.
JACKSON Where can I rent a plane?
The man points to a shabby office building.
Kate is in her kitchen cooking breakfast for the kids.
Gordon watches the Governor on the news.
GOVERNOR (with Austrian
ACCENT) ...
ACCENT) just this morning my people at Caltech told me that in the last 36 hours we had basically zero earthquake activity in Southern California, which is very rare...
The phone rings.
Kate picks up.
Jackson drives like crazy.
JACKSON ...
JACKSON Kate, we have to get out of LA!
JACKSON I've rented a plane for us.
JACKSON Get the kids ready!
JACKSON I'll be there in five.
KATE The kids have plans today...
JACKSON Are you kidding me!
KATE No I'm not!
KATE Noah has music at 2 and Lil' has Karate.
Gordon rolls his eyes and mutters.
GORDON Not that we'd expect him to remember.
JACKSON California is going down!
JACKSON Pack up the kids!
KATE You're crazy!
KATE The Governor just said we're fine now.
JACKSON The Governor's a meathead, how would he know anything?
JACKSON Kate listen!
JACKSON You gotta trust me over some politician.
JACKSON Come on.
Kate slams the phone down.
Lilly stops eating.
LILLY Mommy, why are you so angry with Daddy?
LAURA Because your daddy is a lunatic, darling.
On the TV, the interview comes to an end.
GOVERNOR ...
GOVERNOR it looks to me, like the worst is over.
That moment a MASSIVE QUAKE hits Los Angeles.
Everybody dives under the table.
ON TV: The news casters and the Governor do the same.
A few seconds later the signal cuts out.
Gordon pulls Kate and the kids close as the earth shakes violently for 20 seconds.
Jackson flies into the driveway and runs into the house.
When he enters, Lilly immediately runs into his arms.
The next tremor hits.
Cracks form on the kitchen floor.
JACKSON We have to leave!
JACKSON Noah, let's go!
KATE I think we're safer here!
JACKSON Noah, now!
JACKSON Kate please...
The whole house rides up and down like on a wave.
GORDON I think he's right.
Finally Kate pushes her son out from under the table.
They all scramble out of the house in a panic.
Kate is cut on the shoulder by falling glass but she hardly notices.
As they storm out of their front door the house crumbles behind them.
JACKSON Get in the car!
The whole street starts to buckle.
Left and right the houses are shaken and smashed like toys.
Just before the wave of destruction can reach them, Jackson tears out of the driveway.
Jackson maneuver's the limo through the crumbling neighborhood.
Right in front of their eyes, streets disappear, trees fall, electrical lines snap.
Sewer pipes burst in front of the car.
NOAH Holy shit!
Jackson has to turn on the windshield wipers.
The limo crashes through a gate onto the tarmac, coming to a stop in front of a twin engine Cessna.
JACKSON Damn it!
JACKSON Where's the pilot?
Kate turns to Gordon.
KATE Gordon, you know how to fly.
GORDON I...
GORDON had a couple lessons...
JACKSON Did you cover taking off?
GORDON Yeah.
JACKSON That's good enough for me.
They start running, when Jackson remembers something and heads back to the Limo.
He grabs his knapsack from the front seat fumbling to zip his laptop back inside it.
Kate shouts.
KATE Jackson, what are you doing?
JACKSON I'm coming.
He jumps out of the car and races back after them.
Behind Jackson the hangar starts to disintegrate.
A gigantic fissure forms in the earth, shooting towards Santa Monica airport.
Gordon fumbles with the controls, Jackson yells from the copilot seat.
JACKSON (CONT'D) Come on, come on...
GORDON (pointing at the
INSTRUMENTS) But I'm supposed to check all these first...
Jackson reaches over and slams Gordon's hand down and the plane lurches forward.
As the Cessna speeds onto the tarmac the control tower goes down and explodes.
Noah discovers the giant crevasse forming behind them.
NOAH Guys, behind us!
As the plane accelerates, the giant crack closes in on them.
Gordon's hand trembles on the throttle control.
Everybody screams on top of each other.
EVERYBODY Gordon!
EVERYBODY Damn it!
EVERYBODY Lift off!
Gordon gathers his courage and pulls the lever.
The plane almost rockets into the air just as the ground beneath them gives way.
They hover for a moment, almost caught in mid-air as the widening crevasse beneath them fights to suck them into the bowels of the earth.
Gordon fights to maintain control but they begin to be pulled down.
The daylight vanishes.
Debris and mud smashes into the plane from all sides.
The canyon walls erupt.
GORDON I can't get it up!
Taking desperate measures, Gordon nearly rips the control stick out of its joint - with a lurch the Cessna lifts out of the abyss.
They all take a deep breath only to realize that now they are flying directly into the collapsing towers of downtown Los Angeles!
Like a roller coaster, Gordon manages to weave the little plane through the tumbling high rises.
They dive one last time to evade the plummeting US BANK TOWER, the tallest building on the west coast.
All are dead silent as they watch the whole of Los Angeles crumble beneath them.
Kate covers Lilly's eyes.
NOAH That was amazing, Gordon!
Jackson looks at Kate and notices her cut.
JACKSON Are you okay?
KATE I'm fine.
KATE How did you know this was gonna happen?
JACKSON I didn't.
JACKSON Do we have enough fuel to make it to Yellowstone?
The plane veers off in a northeasterly direction.
Behind them the destruction of Los Angeles continues.
The gigantic cruise ship plows through the Pacific.
We hear lounge music...
Adrian's father Harry and his partner Tony are on stage.
Harry on the piano, singing, Tony playing the bass.
A waiter brings drinks.
Water for Harry, and a brightly colored cocktail for Tony.
WAITER You got fans Tony...
Tony raises his glass to two old ladies who are sitting at the bar.
WAITER (CONT'D) There's a call for you Harry.
WAITER (CONT'D) Want me to take a message?
HARRY I'll be right there.
The waiter nods.
A few more bars of music, then applause.
HARRY (CONT'D) Thank you ladies and gentlemen.
HARRY (CONT'D) Let's hear it for the one and only Tony Delgado...
HARRY (CONT'D) And I'm Harry Helmsley and we'll be back after a short pit stop.
Applause.
Harry rushes off stage.
ADRIAN Dad...
ADRIAN what I have to tell you is very serious...
Adrian is standing in a dark corner.
Behind him people are packing up, carrying boxes.
ADRIAN You remember when I told you about the dam in China?
ADRIAN Well, it's happening much sooner than we anticipated.
Harry's face has turned serious.
ADRIAN The President has ordered us to clear out the White House.
HARRY Hah...
HARRY About time someone cleaned up that mess.
Adrian fights back the tears.
ADRIAN Where are you, dad?
ADRIAN What exactly is the course of the `Freedom' right now?...
HARRY It's all good, Adrian.
HARRY Don't worry about your old man.
HARRY You have more important things to do now.
There's a tremor in Harry's voice.
HARRY You know, your mom and I, we had a hell of a great life...
HARRY and a hell of a great kid too.
HARRY And the `Freedom' is a pretty big ship you know...
HARRY Don't write your old man off, just yet.
A tear runs down Adrian's face.
HARRY ...
HARRY Besides, I could never leave Tony alone.
HARRY You know how he can't keep decent time by himself.
Pause.
ADRIAN I love you, dad.
Harry bites his lip.
HARRY Love you too, son.
Back in the lounge, Tony has finished his cocktail.
Harry walks up and hollers at the barkeeper.
HARRY Hey Herb.
HARRY Get me a double Jack on the rocks.
TONY After twenty-five years on the wagon?
HARRY Why not?
HARRY Who cares how long we do certain things?
HARRY How long we drink booze, how long we talk to people...
HARRY Or how long we don't talk to people.
Harry grabs Tony by his shirt.
TONY Woah!...
TONY Harry, what's the matter with you?
TONY Let's go.
TONY We're back on.
Harry pulls him even closer.
HARRY Call your kid, you stubborn old ass.
HARRY I'm not going back on that stage unless you promise to call him.
WAITER Tony, the ladies are waiting for you.
HARRY Promise me, Tony...
HARRY please.
Harry stares him down.
TONY Yeah, maybe I should call him...
Harry smiles, downs his bourbon and walks back on stage.
Adrian enters his office.
The TV is on.
NEWS ANCHOR ...
NEWS ANCHOR There is little we know at this point, but the earthquake registered at 10.1 on the Richter scale.
NEWS ANCHOR The whole of the Western seaboard was hit...
Assistants stare at the news in shocked disbelief, some of them are crying.
Prof. West appears at the door.
ADRIAN Have you seen this?
Prof. West silently nods and beckons Adrian, who follows him down the hall into a dark control room.
They look at a wall- sized high def monitor.
PROF. WEST We have satellite images.
PROF. WEST Here's the sequence we've got so far.
On the monitors, detailed satellite imagery displays how the monstrous quake unfolds, leaving California sliding into the sea.
ADRIAN Any news from Yellowstone?
PROF. WEST Anytime now.
The base is abandoned but for a few structures and the enormous drilling tower.
Gordon manages to land the plane next to what looks like a fueling station.
Jackson leaps out checking the pump.
JACKSON Guys, there's fuel!
JACKSON Fill her up and I'll look for Charlie.
KATE You're sure about this?
JACKSON Kate, everything this guy said so far has happened.
JACKSON I'll be right back.
Jackson runs off towards the hills.
LILLY Daddy wait!
LILLY I wanna come with you!
Lilly runs after him.
Jackson picks her up.
KATE Lilly!
KATE Come back!
JACKSON It's fine!
JACKSON I'll take her.
Kate watches as they disappear, worried.
Noah and Gordon have started to fuel the plane.
Jackson and Lilly find Charlie's RV with it's door hanging open.
They enter.
The key is in the ignition.
The radio transmitters are on, but Charlie is gone.
Jackson fiddles with the switches and Charlie's voice comes on.
CHARLIE'S VOICE ...
CHARLIE'S VOICE I am standing here at the highest point on what is the rim of this super volcano...
JACKSON He's got to be close by, Lil'bee...
Jackson jumps behind the wheel and turns the ignition.
LILLY Let's go back, Daddy.
JACKSON Listen to me.
JACKSON We have to find Charlie.
JACKSON He's got a secret map, you know, like Jack Sparrow in `Pirates'.
That catches her interest.
JACKSON (CONT'D) Lil', we have to work as a team now, okay?
JACKSON (CONT'D) You have to help me.
Jackson passes her his mobile phone.
Lilly nods.
He throws the RV into gear and they speed off over the bumpy terrain.
In their dust, we see the earth fissuring!
Jackson drives like a bat out of hell.
CHARLIE'S VOICE ...
CHARLIE'S VOICE The last time this baby blew, was 640,000 years ago...
JACKSON Dial Mommy's number, sweetheart.
Jackson tears up the mountain looking for Charlie.
Kate's phone rings.
LILLY Hi mommy...
KATE Where are you, honey!?
Jackson hears the stress in Kate's voice.
He hisses at Lilly.
JACKSON Tell her we'll be back in ten minutes.
LILLY We're looking for a secret map, mommy.
Jackson grimaces.
Kate tries to keep it together for Lilly.
KATE Let me speak to your daddy, darling.
LILLY Daddy can't talk right now, he's driving really fast...
The RV runs over a boulder.
Lilly hits the roof.
LILLY Ouch!
In the background Kate hears the voice of Charlie Frost.
CHARLIE'S VOICE ...
CHARLIE'S VOICE I tell you guys, any minute now...
CHARLIE'S VOICE any minute the fireworks will start...
KATE Who's in the car with you?
KATE Who's that man screaming?
LILLY He's not in the car.
LILLY He's on a mountain waiting for fireworks.
Lilly spots Charlie way up on a ridge.
He has erected his ten foot radio antenna with the flag fluttering on top.
LILLY (CONT'D) There he is!
LILLY (CONT'D) Up there!
JACKSON You're the best, darling.
JACKSON Give Daddy the phone...
JACKSON Kate I am sorry, I can't talk...
The road ends just below the mountain peak.
KATE Bring back my child, Jackson!
KATE NOW!
Jackson sees Charlie up above, broadcasting.
He hangs up the phone and jumps out of the RV.
JACKSON You wait here for me!
JACKSON You watch the ship while Captain Curtis talks to the pirate.
JACKSON Okay?
LILLY Okay...
Jackson climbs up to Charlie.
Charlie has his broadcasting equipment strapped to his body.
The antenna's flag is whipping in the wind.
CHARLIE FROST ...
CHARLIE FROST I wish you guys at home could see this on TV...
He notices Jackson and muffles the microphone.
CHARLIE FROST (CONT'D) How did you make it up here?
CHARLIE FROST (CONT'D) Thought you were toast.
JACKSON The spaceships Charlie, where are they?
CHARLIE FROST You can't make it there.
JACKSON We have a plane.
JACKSON We can get you out of here too.
JACKSON Let's go Charlie!
All around the landscape begins to collapse.
A three mile crater forms, revealing the awe-inspiring sight of the super- volcano.
CHARLIE FROST You'll never make it out in time.
CHARLIE FROST Just stay and enjoy the big bang.
CHARLIE FROST That your kid?
Jackson discovers Lilly standing behind him, staring at Charlie with her big brown eyes.
Jackson grabs Charlie lifting him off the ground.
JACKSON Where is that god damn map!
CHARLIE FROST Easy, easy.
CHARLIE FROST Watch the mic...
CHARLIE FROST I don't know.
CHARLIE FROST Somewhere in my camper.
A low rumble builds to a rapturous thunder as MILLIONS OF BIRDS tear into flight.
CHARLIE FROST (CONT'D) Wow!
CHARLIE FROST (CONT'D) Look at that!...
CHARLIE FROST (CONT'D) Fly birdies fly!
CHARLIE FROST (CONT'D) This marks the last day of the United States of America folks and by tomorrow...
The mouth of the volcano starts to break apart revealing molten lava underneath.
CHARLIE FROST (CONT'D) ...
CHARLIE FROST (CONT'D) the last of mankind.
CHARLIE FROST (CONT'D) Soon they'll see us from a million miles away, out there in the milky way...
Jackson grabs his wide eyed daughter and races down the mountain.
Jackson and Lilly jump into the RV and races off, with Charlie's broadcast still playing.
CHARLIE'S VOICE ...
CHARLIE'S VOICE The ash cloud will travel everywhere.
CHARLIE'S VOICE (CONT'D) First the lights will go out in Vegas, then Dallas, St.
CHARLIE'S VOICE (CONT'D) Louis and then Washington DC...
Jackson's cell phone rings and he picks up.
JACKSON We're on our way.
KATE Jackson, things are really looking bad here!
In that instant, the air around them vanishes, as if sucked from the landscape into a vacuum.
THE BIGGEST EXPLOSION THE WORLD HAS EVER SEEN...
At least in the last 640,000 years.
To them, all this occurs in total silence.
The sound of the eruption has not reached them yet.
They are frozen, unable to comprehend what is happening.
The explosion begins to resembles an atomic mushroom.
CHARLIE FROST ...
CHARLIE FROST it's beautiful, kids!
CHARLIE FROST Just beautiful!
The sound waves reach Charlie, throwing him to the ground.
The RV flies over the rugged terrain.
Everywhere the earth is cracking, falling apart.
Jackson struggles to swerve around the disappearing landscape.
LILLY It's following us!
Lilly has discovered the expanding ASH CLOUD behind them.
JACKSON Just don't look back, Lil'bee!
The THUNDERING sound envelopes them!
On the radio, the voice of Charlie is getting shrill.
CHARLIE'S VOICE Majestic!...
CHARLIE'S VOICE Oh yeah!
Charlie slowly tries to stand again, silhouetted against the cloud of dust and fire towering above him.
Flaming rocks fly towards him.
When they hit the ground, they detonate like fire bombs.
CHARLIE'S VOICE Oh baby!
CHARLIE'S VOICE It's coming!
Rocks plummet like comets around the RV as Jackson races over a collapsing bridge.
On the radio, in his delirious state, Charlie begins to sing...
CHARLIE'S VOICE `This is the end, my friend'...
Yellowstone looks like a war zone.
The RV dodges the bombardment of fire and rock.
Huge tree trunks and glowing boulders fly at Charlie through the ashes.
He screams at the top of his lungs.
CHARLIE FROST ...
CHARLIE FROST Folks, always remember, you heard it first from Charlie.
A second later, Charlie's radio antenna comes spinning like a scythe through the air.
It decapitates Charlie in an instant.
The radio cuts out.
The forest and the camp grounds are mown flat by the extreme force of the ASH CLOUD.
In the rear view mirror Jackson sees it gaining on them.
A firebomb hits the RV, ripping half the roof off.
Lilly barely makes it under the dashboard.
JACKSON (CONT'D) Stay down there, Lil'!
JACKSON (CONT'D) We're almost there!
JACKSON (CONT'D) Just keep looking at daddy.
Jackson spots the little Cessna in the distance.
At the entrance to the airstrip a huge crevasse forms, cutting the RV off from reaching the plane.
Lilly sticks out her head.
LILLY Mommy!
Jackson swerves wildly to miss the crack, sending Lilly flying out.
Without thinking, he lets go of the wheel, lunging after her and pulling her back inside.
JACKSON Stay down darling.
Jackson races the RV alongside the forming crack.
Spotting a narrow point in the crevasse, he makes a decision.
Slamming the accelerator down, he races towards it at full speed.
Moments later the RV is airborne!
Kate watches, too shocked to scream.
A few drawn out seconds.
Then the RV touches down, crashing 200 feet from the plane.
Kate runs towards the wreckage of the camper.
Lilly jumps out, racing into her mom's arms.
Jackson turns and sees the cloud approaching.
JACKSON (CONT'D) You guys go!
JACKSON (CONT'D) I'll be right there!
Kate pulls Lilly back to the plane.
Jackson jumps into the back of the RV scavenging through the shelves, looking for Charlie's map.
Kate lifts Lilly onto the wing of the plane.
Gordon revs up the engines.
NOAH Give me your hand, Lil'.
Noah pulls his little sister into the cockpit.
Fiery rocks rain from the sky, detonating to the right and left of their plane as Kate climbs in.
GORDON We have to take off!
NOAH No!
LILLY Where's daddy?!
GORDON Kate, I'm sorry but if we wait we'll all die!
Gordon pushes the throttle.
The plane starts to move.
Kate screams.
KATE Gordon!
KATE Wait!
Back in the RV, Jackson is frantically going through the masses of books and papers on the shelves.
Finally, a map.
He unfolds it.
But it's only of the London underground system.
He throws it to the ground and finds another.
This time he's lucky!
There are markings everywhere.
As he races to the door, the ground gives way beneath the RV.
Kate and the kids watch it disappear from sight.
Noah begins to cry and Lilly clings to her mom.
Gordon just stares, paralyzed.
The ASH CLOUD is almost upon them!
Gordon takes action and accelerates the plane.
Kate turns back.
A hand emerges from the crevasse.
Then another, holding a map.
Her face lights up.
LILLY It's daddy!
Jackson pulls himself up and sprints towards them, the map in his hand.
KATE Jackson!
KATE Here!
Kate leans out of the cockpit reaching for him.
NOAH Faster Dad.
NOAH You can make it!
GORDON Kate, grab him for god sake.
GORDON We're almost out of runway.
Using every last ounce of energy, Jackson leaps onto the wing and is yanked into the plane by Kate.
Just at that moment, the plane lifts off.
Jackson falls into the cockpit, completely out of breath.
Lilly crawls over and hugs him.
JACKSON Thanks for waiting guys.
Now all eyes are glued to the speedometer.
180...
190...
The violent ASH CLOUD is hitting their tail rudder.
The plane swerves wildly!
Gordon gets it back under control.
The speedometer finally creeps towards 200 mph and the CLOUD slowly falls back.
Everybody breathes a sigh of relief.
KATE So, now that you got your map, where are we going?
Jackson unfolds it and takes a look.
Hundreds of markings clutter the map.
In the left corner he discovers a large letter C followed by H - I - N - A.
He looks up.
JACKSON We're gonna need a bigger plane.
The White House is being evacuated.
Amidst the chaos stands Anheuser.
Adrian puts down a phone and looks at him.
ADRIAN Just a few minutes ago Yellowstone erupted, sir.
ADRIAN The ash cloud will reach Washington in roughly 7 hours.
ADRIAN Maybe 6.
ADRIAN We have strong easterly winds...
ANHEUSER And the crustal displacement?
ADRIAN No one knows, sir.
Anheuser starts walking, Adrian trails behind.
ANHEUSER Let's get the government airborne and...
ANHEUSER I mean now.
Anheuser and Adrian burst into the Anteroom of the Oval Office.
The President's secretary, SALLY, 55, is packing.
ANHEUSER Where is the President, Sally?
Sally looks up stone faced.
SALLY He said he wanted to spend a few minutes alone.
SALLY I think he's over at the chapel.
ANHEUSER The whole North American continent is about to perish, and Wilson decides to go to church!
Adrian shoots an angry look at Anheuser.
ADRIAN He's praying sir.
ADRIAN Which considering the circumstances is not a bad idea.
ANHEUSER Maybe.
ANHEUSER But right now I need the leader of the free world off his knees and on Air Force One.
ANHEUSER Wheels up 1900 hours.
ANHEUSER Can I leave that with you Helmsley?
Anheuser walks away.
Adrian and Sally exchange a look.
SALLY I really don't like that man.
Adrian finds the President standing near the front of the chapel.
ADRIAN Mr. President?
ADRIAN We need to get you out of Washington immediately.
President Wilson stays with his head bowed.
PRESIDENT WILSON Now matter how idealistic you are taking office.
PRESIDENT WILSON You lose your innocence behind that desk.
PRESIDENT WILSON Laura was right.
PRESIDENT WILSON People have died because of the decisions I made.
ADRIAN That's not your fault sir.
He turns to face Adrian.
PRESIDENT WILSON You sound like Anheuser.
This quietly affects Adrian.
PRESIDENT WILSON (CONT'D) Laura's never looked at me like that before.
PRESIDENT WILSON (CONT'D) Only once...
PRESIDENT WILSON (CONT'D) When I told her, her mother had died.
PRESIDENT WILSON (CONT'D) You knew the first lady?
ADRIAN A little.
PRESIDENT WILSON You know what she said to me that night we brought her to the hospital?
PRESIDENT WILSON `Tommy...
PRESIDENT WILSON I think you should do a lottery.
PRESIDENT WILSON Every one should have a chance to go'.
PRESIDENT WILSON That's what Dorothy said to me.
PRESIDENT WILSON That's what we should have done.
ADRIAN There would have been chaos, sir.
President Wilson looks Adrian in the eyes.
PRESIDENT WILSON You know what I believe, Adrian.
PRESIDENT WILSON I believe nature should choose for itself, from itself.
Adrian takes this in.
PRESIDENT WILSON (CONT'D) Don't let her go.
PRESIDENT WILSON (CONT'D) You'll regret it if you do.
PRESIDENT WILSON (CONT'D) Prove to Laura what kind of a man you are.
PRESIDENT WILSON (CONT'D) And I'll do the same...
PRESIDENT WILSON (CONT'D) You go now.
PRESIDENT WILSON (CONT'D) And watch your back for Anheuser.
Adrian stares at the President in disbelief.
ADRIAN But sir?
PRESIDENT WILSON Go.
PRESIDENT WILSON That's an order Helmsley.
A tense moment before Adrian starts to walk away.
Just as he exits the chapel, Wilson calls after him.
PRESIDENT WILSON (CONT'D) Would you tell my daughter...
PRESIDENT WILSON (CONT'D) there's nothing on earth that I cherish more than her.
We hold on President Wilson's face.
Most of Las Vegas is destroyed.
A 200 foot wide canyon now divides sin city along its famous strip.
The towering casinos still teeter along the canyon's rim.
All forms of emergency rescue operations are deployed around the city.
In the FOREGROUND, we see Las Vegas International Airport, its runway cut dramatically short.
Large pieces of tarmac continue to break off into the crevasse.
Gordon maneuvers his plane through the chaos.
Airplanes are strewn about the runway.
Passengers everywhere.
GORDON I told you we should have gone to my parents' in the Rockies.
KATE Gordon's right.
KATE Look at this mess.
Jackson looks around frantically.
JACKSON You don't understand, it's our only chance.
GORDON This isn't one of your crazy stories now.
GORDON How the hell are we gonna make it to China?
NOAH Gordon, without Jackson, we'd never have made it out of California.
Silence.
Noah is right and they know it.
They taxi past a private jet whose front wheel is stuck in a hole in the tarmac.
We hear a dog barking and the CAMERA finds Tamara, with Caesar in her arms.
YURI Careful with the landing gear!
YURI Tamara, get the boys out of the way!
An airport tow truck attempts to pull Yuri's Gulfstream jet out.
Sasha, the pilot, helps.
A safety announcement echoes through the whole area.
VOICE Attention!
VOICE The US National Guard has informed us, that an extremely hazardous ash cloud is headed towards the city of Las Vegas.
Tamara looks scared and secretly reaches for Sasha's hand.
They share an intimate look, no one else sees.
VOICE (CONT'D) We strongly advise every one to move indoors immediately...
The tow truck driver panics and runs inside.
We move in on Yuri.
For the first time he looks helpless.
In the background, Jackson and his family join the panicked crowd heading towards the terminal building.
Firemen and rescue workers usher them forward.
FIRE MAN Let's move people!
FIRE MAN Inside the terminal!
Jackson and his family are swept along.
Adrian rushes up the stairs of Air Force One, approaching one of the flight officers.
ADRIAN Where's Anheuser?
OFFICER In the command center, sir.
Adrian moves on.
Adrian enters.
Anheuser immediately senses something is amiss.
ADRIAN The President is not coming.
ADRIAN I couldn't convince him to.
Everyone in the room looks up, speechless.
ANHEUSER So, the captain doesn't want to leave his sinking ship?
ANHEUSER Well, Mr. Helmsley, we just learned that the Vice President's chopper crashed 80 miles north of Atlanta.
Adrian is shocked.
ADRIAN What about the Speaker of the House?
ANHEUSER In this chaos...
ANHEUSER I have no idea!
ADRIAN But she's Commander In Chief now.
ADRIAN Sir, I just think -
Anheuser moves in dangerously close.
ANHEUSER I don't care what you think, Helmsley.
Laura quietly enters the Command Center, as Anheuser and Adrian stare each other down.
ANHEUSER (CONT'D) Your ass only made it into the White House, because your old man knew the First Lady...
ANHEUSER (CONT'D) and because of all that affirmative action bullshit.
Anheuser takes it even further.
ANHEUSER (CONT'D) There was a white kid, much more qualified than you.
ANHEUSER (CONT'D) Just so you know.
Adrian's face is ashen.
LAURA Where is my father?
Everyone turns to Laura.
Silence.
ADRIAN He wanted to stay with his people.
Suddenly, the engines of Air Force One turn over.
Laura panics.
LAURA We have to go back!
Adrian tries to hold her close to him.
Anheuser sees this intimate moment and gives a suspicious, questioning look.
A second later Laura pushes Adrian away.
LAURA (CONT'D) Let me get out.
LAURA (CONT'D) Mr. Anheuser - tell the Captain.
ANHEUSER There is a protocol for just this situation Ms. Wilson and I'm afraid we'll have to follow it to the letter.
Anheuser turns to an officer.
ANHEUSER (CONT'D) Tell the Captain, to take off immediately.
Laura looks at him incredulously.
Emergency lights illuminate the densely populated terminal.
RESCUE WORKER People, stay away from the windows!
One of the rescue workers yells, pushing Jackson and his family back.
Frustrated, Jackson turns to Kate and Gordon.
JACKSON We can't get stuck here.
Suddenly a voice...
VOICE Dr. Silberman?
VOICE What are you doing here?
They all turn and stare at Tamara, holding her little dog against her plump breasts.
Kate gives Gordon a look.
GORDON She's a patient, honey.
JACKSON Nice work.
But when Jackson discovers Yuri behind her, his tone suddenly changes.
He gets in Yuri's face.
JACKSON (CONT'D) You bastard.
JACKSON (CONT'D) You knew it all along!
JACKSON (CONT'D) You and those spoiled rotten sons of yours...
Sasha comes running in and cuts through this.
SASHA I found us a plane, an Antonov.
SASHA They were just about to take off, but the tower didn't let them.
YURI Can you still fly that thing?
SASHA Sure...
SASHA But I need a copilot.
Lilly chimes in.
LILLY Gordon is a pilot.
Before Gordon can protest Jackson picks up Lilly.
JACKSON Let's go!
They burst through the emergency exit, setting off an alarm.
Emergency personnel yell after them.
RESCUE WORKER Hey!
RESCUE WORKER Stop!
RESCUE WORKER You can't go out there!
RESCUE WORKER Come back!
But they keep on running.
Sasha now leads the way.
They race around the corner and come to a halt.
Before them, a Russian freight plane of enormous size--
The ANTONOV 225, the biggest aircraft in the world.
NOAH Wow, that is a big plane.
YURI It's Russian.
Sasha, who has run ahead turns back and sees:
A MASSIVE GREY WALL OF ASH moving towards the airport.
SASHA Guys, follow me!
They all run after him up the stairs.
Sasha enters the cockpit and puts on the headset while readying the plane for takeoff.
SASHA You'll find folding seats on each side of the cargo hold...
SASHA ...
SASHA Sit down and buckle up!
They all scramble to get into their seats.
NOAH Wow!
NOAH Look at those!
They discover the cargo they are carrying--
Sports cars, SUV's, concept cars and luxury models, some of them are labeled `Las Vegas Auto Show 2012'.
YURI We had VIP tickets for that.
The six engines of the Antonov come roaring to life.
The plane is starting to move.
Gordon sits uncomfortably in the copilot's seat.
SASHA You check the main bus for the hydraulics.
SASHA I'll balance the tanks.
GORDON Uh...
GORDON What?
Sasha reaches over and does it himself.
SASHA Work the radio and keep an eye on the fuel, okay?
Gordon nods and puts on the headset, trying to focus.
People start SCREAMING, when they discover the menacing WALL OF ASH racing towards them.
RESCUE WORKER Move back, people...
RESCUE WORKER down on the floor!
The nose of the Antonov turns onto the runway.
This humongous plane suddenly looks small against the wall of ash.
Gordon is panicking.
GORDON We have to get going!
Sasha hits the throttle.
SASHA We're going, we're going.
A deafening THUNDER emanates from the engines.
Everybody grabs their seat as the vibration of the aircraft builds.
The Antonov steadily gains speed as it rumbles down the cracked and uneven runway.
The canyon that has swallowed half the city looms ahead.
And behind them the volcanic cloud bears down.
Sasha stares down the gap ahead, determined.
Gordon's face is as white as a sheet.
GORDON We're not gonna make it!
SASHA Shut up!
SASHA We will!
The violent cloud has finally reached the airport.
The terminals are hit by flying debris.
Seconds later, Yuri's Gulfstream is whipped through the air, shattering the huge windows into a thousand pieces.
People are thrown like rag dolls as the jet explodes in a massive fireball.
Kate and Jackson hold their kids tight.
Tamara clings to little Caesar and Yuri to his twins.
The Antonov lumbers heavily towards the inevitable drop off on the horizon.
The runway is way too short...
And to make matters worse, the ground begins to move again, slowly arching the tarmac upwards, creating a crooked ramp at the end of it.
A drop of sweat trickles down Sasha's forehead as he pulls back the wheel.
Gordon holds on for dear life as the huge plane barely lifts off, veering sideways.
The Antonov is on a collision course with the crumbling casino towers along the other side of the rim.
SASHA GOVNO!
SASHA (shit).
SASHA Help me pull!
Gordon grabs the wheel on his side, helping Sasha pull up the beast of a plane.
Very slowly the plane starts to rise and Sasha's face lights up.
They barely make it over a casino called `Paris; Las Vegas'.
But the plane clips its wheels on a high metal structure right behind it, ripping away part of the landing gear.
After some struggle, Sasha manages to steady the Antonov.
Gordon's face is green as he looks back.
GORDON Was that the Eiffel Tower?
Sasha looks over and grins.
He grabs the microphone.
SASHA Ladies and gentlemen, we are on our way to China.
An ancient monastery built atop a solitary mountain rock.
In the distance, the sun glistens off the peaks of the Himalayas.
NENG PANG, a young monk, 20, sits with his superior and teacher LAMA YAK LA, 65.
They have tea beneath a huge bronze bell.
LAMA YAK LA Do not believe in anything simply because you have heard it, Neng.
NENG But Lin is my brother.
NENG He is working inside the big tunnels, where the ships are made.
The Lama remains silent.
NENG (CONT'D) What is in your wisdom for us to do, great Lama...
NENG (CONT'D) if Lin is right, if our world is indeed coming to an end?
Instead of answering, the Lama serves him more tea.
When the cup is full, the Lama doesn't stop pouring.
Neng watches the tea overflow until he can no longer restrain himself.
NENG (CONT'D) It's full, great Lama.
NENG (CONT'D) It can hold no more!
The Lama stops pouring and looks at Neng.
LAMA YAK LA Like this cup, Neng, you are full of your own opinions and speculations.
LAMA YAK LA How can I show you wisdom unless you first empty your cup?
Neng bows his head in embarrassment.
The Lama smiles to himself and takes a chain from around his neck.
On it hangs a set of rusty car keys.
LAMA YAK LA (CONT'D) Be careful with the clutch.
LAMA YAK LA (CONT'D) It tends to slide.
The Lama throws him the keys and the young monk catches them, smiling from ear to ear.
They bow to each other and Neng runs off.
Lama Yak La looks after him as a father would.
He gets up and strikes the bronze bell with a wooden mallet.
As far as you can see is a series of identical little houses.
The house in the foreground has a chicken coop in the garden.
Mrs. Pang enters the coop.
We last saw her when the village was being evacuated.
She grabs one of the hens.
She places its head on a woodblock and picks up a rusty hatchet.
Just about to strike, she hears a strange RATTLING noise.
An old truck comes driving towards the house.
Behind the wheel sits her son Neng.
She puts down the hatchet, yelling.
MRS. PANG Bata!
MRS. PANG Neng is coming!
The young monk jumps out, quickly bowing.
NENG Mother, I got a message from Lin.
NENG He wants us to meet him in Cho Ming, at the west gate.
NENG He says he can get us on one of the ships he is working on.
Mrs. Pang is still holding the chicken by its throat.
MRS. PANG I thought Lin is working on the dam?
NENG The dam is a ship, Mother.
NENG The government lied to us.
NENG There will be a big flood.
The chicken hangs limp in Mrs. Pang's hand.
MRS. PANG Not here in the mountains...
MRS. PANG Let's eat first.
The hen panics as she puts its head back on the block, raising the hatchet again.
NENG No mother!
NENG We must pack up right away.
NENG'S MOTHER We took a trip with the Laem Song ferry once.
NENG'S MOTHER Your father was throwing up the whole way.
The door opens and Mr. Pang appears.
MR. PANG Neng, I did not know you were coming for dinner.
At that moment the hatchet drops with a THUD!
The majestic Antonov is flying high in the Pacific skies.
OLEG Look, the new Bentley.
The boys are exploring the huge freight deck.
Caesar, the little dog, is traipsing along.
Alec, Oleg and Noah marvel at a stylish mixture of luxury and performance cars.
ALEC Our dad had one on order.
ALEC We were supposed to get it next year.
OLEG But then he cancelled it again, because of the ships.
Noah points to a 2012 Aston Martin parked further back.
NOAH If I was rich, I'd get one of those.
OLEG We have one.
OLEG How many cars does your family have?
NOAH My Mom's boyfriend has a Porsche, a Carrera 4.
ALEC Our parents are divorced too.
The boys share a moment of understanding.
NOAH Nothing we can do about that.
Noah reaches for the door of the Bentley.
To his surprise, it opens.
NOAH (CONT'D) Wow...
NOAH (CONT'D) look at this.
Noah jumps into the car.
KATE Be careful, Noh'!
Kate and Lilly are still belted in next to Tamara.
Jackson and Yuri sit on the other side of the Antonov.
TAMARA How did you meet Dr. Silberman?
TAMARA He's great, isn't he?
KATE I think for the same reasons you did.
KATE You know, after breast feeding two kids...
Kate looks at Tamara.
KATE (CONT'D) Did your husband ask you to get your's done?
TAMARA We are not married.
TAMARA And we probably never will...
TAMARA But he paid for them.
KATE I bet he did.
They laugh.
LILLY What did the man pay for mommy?
KATE Nothing, Lil'bee.
Kate looks over at Jackson who's trying to make sense of Charlie's map.
Tamara catches her looking.
TAMARA What's your situation?
Kate lets out a sigh.
KATE Way too complicated...
On the other side of the plane, Yuri has been watching the two women talk.
YURI They seem to like each other.
JACKSON I guess...
JACKSON So tell me Mr. Karpov - how much did you pay?
YURI One billion euro, per seat.
JACKSON That's disgusting.
YURI You know Curtis, I wasn't always businessman.
YURI I am a boxer.
YURI Was my only playing when I was a boy, back in Murmansk.
YURI My coach...
YURI ...
YURI his name also Yuri...
YURI He always said: `Someone wants to beat you...
YURI he has to kill you first'.
Yuri puts his hand on Jackson's shoulder.
YURI (CONT'D) What would you have done, if you rich like me?
YURI (CONT'D) Just look at your gorgeous kids.
YURI (CONT'D) And call me Yuri...
Yuri offers his hand but Jackson doesn't shake it.
Sasha's voice comes over the radio.
SASHA Hi guys.
SASHA The plan is to refuel in Hawaii.
SASHA So, buckle up...
SASHA Gordon and I will do the rest.
Gordon turns to Sasha.
GORDON Let's get this straight, Sasha.
GORDON I'm not a pilot.
GORDON I'm a plastic surgeon.
GORDON I just took some lessons to overcome my fear of flying.
SASHA Why did you give up?
GORDON It didn't work.
Gordon points to the declining altimeter.
GORDON (CONT'D) What about the wheels we lost at take- off?
SASHA There's 14 on each side.
SASHA Some of them must still be there.
With that, Sasha commences the landing procedure.
The Antonov dives into a thick layer of clouds.
SASHA Still nothing from the tower?
Gordon shakes his head.
The two pilots stare ahead watching as the clouds slowly change color, from yellow...
to orange.
They stare out the window in disbelief.
Gordon comes climbing down the metal ladder whispering to Jackson and Yuri.
GORDON Guys, you really oughta take a look at this.
Jackson and Yuri follow Gordon back into the cockpit.
The women exchange a worried glance.
When Jackson and Yuri enter, they don't believe their eyes.
YURI What is that?
SASHA The State of Hawaii!
YURI Not good.
YURI That is not good.
From above we watch as the Antonov flies over an endless ocean of fiery red lava.
The Islands of Hawaii have turned into one big volcano.
JACKSON How much fuel do we have?
SASHA Not enough.
SASHA We'll have to make a water landing somewhere in the South China Sea.
GORDON At least we won't need our landing gear.
Yuri wonders.
YURI What about it?
GORDON We lost it all...
GORDON in Vegas.
The damaged landing gear slowly retracts into the vast belly of the Antonov as it veers off to the east.
Adrian knocks quietly and sticks his head around the door.
Laura is sitting in her father's chair.
ADRIAN Can I come in?
LAURA I've got nothing to say to you.
ADRIAN But I do...
Adrian enters.
He has his travel bag in one hand.
He looks at Laura and gathers himself.
ADRIAN (CONT'D) Your Dad and I...
ADRIAN (CONT'D) we were trying to protect you.
LAURA I'm a big girl Adrian.
LAURA I don't need protection.
LAURA You used me.
LAURA You guys had me gallivanting around the world, as part of your little cover-up.
ADRIAN But you were doing a good job.
LAURA Sure, if your name's Da Vinci or Picasso.
LAURA But if you're some young talent in Podunk, Texas, sorry you're not famous enough.
LAURA People like you and Anheuser and my father - you think you can play God.
Adrian takes a moment, he's desperate to make her see.
ADRIAN You know what your father believed.
ADRIAN That nature will choose itself from itself.
LAURA That's bullshit and you know it.
LAURA It's the fittest, the richest and the strongest that survive.
ADRIAN That's not true.
Adrian glances down and spots Jackson's book poking out of his bag.
ADRIAN (CONT'D) What would you say were the chances of a first time, middle-aged writer, who barely sold 500 copies of his novel making it on board this plane?
LAURA Zero.
LAURA What's your point?
Adrian pulls out the book from his bag.
He shows her.
ADRIAN It's called `Farewell Atlantis' and it's a fantastic read.
ADRIAN It's part of our legacy now.
Laura takes this in.
The plane's intercom cuts through the moment.
INTERCOM Mr. Helmsley, Prof.
INTERCOM West requests your presence immediately.
Adrian takes a breath, but before he leaves -
ADRIAN What if I tried to sort some of this mess out?
ADRIAN I need to know you can forgive me...
Laura looks at him sadly, but with a little hope.
LAURA I need to know that too, Adrian.
Adrian moves for the door.
He stops.
ADRIAN One more thing.
ADRIAN Your father told me you were the most precious thing to him in the whole world...
ADRIAN You are to me too.
As Adrian exits, we hold on Laura's conflicted face.
The cloud from the Yellowstone eruption has hit Washington D.C.
hard.
Pennsylvania Avenue resembles a war zone.
A ten inch layer of ash lies on the ground.
The gates of the White House are wide open, with ash-covered rescue workers running about, resembling ghosts.
The President has turned the whole West Wing into a shelter.
He walks through the packed rooms assisting where he can.
An old African-American LADY holds a crying young girl.
President Wilson kneels down to her.
OLD LADY She can't find her mother.
PRESIDENT Why don't you two girls make yourself comfy on that big couch?
PRESIDENT I'll see what I can do.
The child nods.
The President gets up.
PRESIDENT WILSON Sally, can you take care of them.
PRESIDENT WILSON I'll go check with the Red Cross...
As he leaves, the old lady looks up at Sally and smiles.
OLD LADY No wonder the First Lady fell for him.
OLD LADY I knew Miss Dorothy Jones long before the President, when she was still singing jazz down in Atlanta with Harry Helmsley.
SALLY I know, she was amazing.
The President walks up to the Red Cross tents placed on the front lawn.
He stops one of the Red Cross volunteers.
PRESIDENT WILSON Who can help me with missing persons?
Without looking up, the young guy responds.
RED CROSS VOLUNTEER Sorry man, I'm busy right now.
He then recognizes who he's talking to.
RED CROSS VOLUNTEER (CONT'D) I mean, of course sir.
RED CROSS VOLUNTEER (CONT'D) I didn't realize...
RED CROSS VOLUNTEER (CONT'D) What can I do for you, Mr.
RED CROSS VOLUNTEER (CONT'D) President?
The President pats him on the shoulder.
PRESIDENT WILSON Don't worry about it.
PRESIDENT WILSON You're doing a great job son...
A deep, low rumble begins, stopping everybody in place.
As it builds, the President grabs onto a tent pole to secure himself.
He looks out over Washington D.C. His eyes grow wide...
The National Mall bends like rubber.
The towering Washington Monument breaks into pieces.
An even more deafening sound makes him turn--
The Capitol Building rises from behind the trees, lifted up by earth's incredible force.
As the whole building breaks apart, the President is thrown to the ground.
All the officers and scientists are glued to monitors that show satellite images from all over the globe.
Adrian and Prof. West stare in disbelief.
SCIENCE OFFICER The capitol was hit by a 9.4.
Laura enters the command center unnoticed.
COMMUNICATIONS OFFICER We lost communication with the White House, sir.
She stands there frozen, emotionless.
She looks over to Anheuser, who is shouting orders.
Another officer hands him a phone.
LIEUTENANT #2 President Makarenko for you sir.
LIEUTENANT #2 He's just entered Chinese air space.
Anheuser takes the phone and after a beat answers.
ANHEUSER That's affirmative, Mr. President.
ANHEUSER Until communication is restored, I am in command.
Adrian and Laura look to each other baffled.
ANHEUSER (CONT'D) ...
ANHEUSER (CONT'D) It seems all other Heads of State are en route, however there are unconfirmed reports that the Italian Prime Minister has also decided to stay behind and trust in prayer rather than action...
Pope Benedict XVI holds mass in St.
Peter's Basilica.
Millions of followers flood Vatican City.
It's a sea of candles.
Amidst the mass of believers we see the Italian Prime Minister Antonioni with his family clinging to him.
They all are praying.
A low RUMBLE.
People look around frightened.
In the distance we hear SCREAMING.
A few cardinals huddle together in silent prayer under Michelangelo's famous fresco.
Most prominent above them is `The Creation of Adam'.
The cardinals look up in horror as the rumbling intensifies.
A crack forms on the ceiling, shooting straight through God touching the finger of Adam.
Then the whole fresco breaks apart.
The people in St.
Peter's square begin to panic--
The entire Vatican is lifted up in the air.
We hold on the Prime Minister and his family, as the basilica collapses onto the fleeing masses.
The giant statue of `Christ the Redeemer' on Mount Corcovado.
Behind it, we see Rio de Janeiro being obliterated by violent quakes.
The famous statue of Jesus Christ begins to topple over and crashes down the mountain.
Neng Pang, the young Tibetan monk drives his truck up a bumpy mountain pass.
His parents huddle in the back of the pick-up.
The steering wheel is vibrating badly in his hands as he slides the clutch and downshifts.
As the vehicle slows on the steep incline, the vibrations become much worse.
Neng worries that the truck may be breaking down.
He pulls up and switches off the engine but to his surprise the steering wheel continues to vibrate.
Looking out the windshield, he sees the whole earth shaking violently.
NENG Hold on back there!
Rocks fall all around them.
Jackson sits inside one of the luxury cars and tries the radio.
Kate opens the passenger door and gets in.
JACKSON Couldn't sleep huh?
JACKSON Me neither.
KATE Anything?
JACKSON Nothing, just static.
JACKSON Not even an emergency signal.
KATE I can't think about what's going on down there.
Jackson switches off the radio.
KATE (CONT'D) I wanted to thank you.
KATE (CONT'D) For coming back for us.
JACKSON I couldn't have left you...
Silence.
They both look out through the front windshield at Lilly and Noah curled up together.
KATE Do you think people change?
JACKSON By `people' are we talking about me?
KATE Do you think you've changed since we separated?
JACKSON Well I certainly eat a lot more cereal now...
KATE You know, you always had tunnel vision.
KATE You could always just block things out and write.
KATE You blocked all of us out Jackson.
He thinks about this and can't help asking.
JACKSON Do you love him?
JACKSON Gordon...
KATE I love him enough.
Kate gets out of the car and shuts the door.
He watches her go.
The computers buzz with the incoming data.
COMMUNICATIONS OFFICER ...
COMMUNICATIONS OFFICER Cho Ming reports the first tremors, however none higher than 5.0.
Anheuser looks relieved.
Then the big news hits.
SCIENCE OFFICER #1 The crust has begun to shift, Prof.
SCIENCE OFFICER #1 West.
PROF. WEST By what degree?
SCIENCE OFFICER #1 1.2 percent, but still moving.
ANHEUSER Any clue what to expect next, Professor?
PROF. WEST Once the movement of our land masses comes to a halt, we expect the formation of tidal waves, sir...
PROF. WEST proportional to the magnitude of the corresponding quakes.
Adrian looks distressed as he turns to one of the officers.
ADRIAN Do we have any news from the Japanese seaboard?
Laura notices Adrian's concern.
SCIENCE OFFICER #2 We've recorded two quakes averaging
She grabs Adrian's hand.
Anheuser sees this and his suspicions about them are confirmed.
A cold little smile appears on his face.
Tony is watching TV with a group of passengers.
Harry has just entered and stands near the back of the room.
A TEENAGE BOY with bad acne searches for an available channel that is still broadcasting.
He finds a news program with lousy reception.
NEWSCASTER ...
NEWSCASTER Tokyo seems to have taken the severity of the hit...
NEWSCASTER Unconfirmed reports indicate that the entire island of Japan is below water...
The signal gets weaker.
Harry watches Tony slowly stand up.
As he turns to his friend, his knees begin to buckle.
His face is pale.
TONY I called...
TONY But I never got through.
HARRY I'm so sorry.
Tony only stares back at him.
Behind them, the TV rolls to the side, as the whole room begins to tilt.
Harry grabs on to the door frame, as the passengers along with Tony fall like dominoes.
HARRY (CONT'D) Tony!!
As the ship rolls to the side, Harry finds himself hanging from the door frame now 20 feet off the ground.
He's barely able to pull himself up and roll onto the middle deck.
On his back, Harry is shocked to see the star field and the moon shifting across the sky.
An eerie sound fills the air.
A gigantic swell has formed off to his right.
It's a mountain of water.
Harry turns to see another gargantuan swell close in from the other side of the `Freedom of the Seas'.
The old walled city of Shibam is in ruins.
The 2,000-year-old towers lie on the desert ground.
Hundreds of believers have gathered to pray towards Mecca.
As they raise their hands to heaven in unison, they slow their motion and the chanting dissipates.
They stare into the distance not knowing if what they see is reality or only a mirage.
A monstrous tidal wave rises from the desert sands thundering towards them.
President Wilson's body lays between the rubble.
As he slowly regains consciousness, all he can hear is the flapping sound of the collapsed Red Cross tents.
As President Wilson gets to his feet, he sees--
A tidal wave come sweeping over the remains of the Washington Mall and it carries with it the battleships of the 14th Fleet of the US Navy that were anchored in Chesapeake Bay.
The President looks ahead, calm and peaceful.
PRESIDENT WILSON I'm coming home Dorothy...
The CAMERA follows the aircraft carrier `USS John F. Kennedy' as it slams broadside into the White House.
Hushed voices.
Anheuser, Adrian and Prof.
West stand amongst a group of officers and analysts.
COMMUNICATIONS OFFICER #1 All global ground communication has ceased sir.
COMMUNICATIONS OFFICER #2 The only signal our satellites are picking up are coming from the vessels in Cho Ming.
ANHEUSER At least some good news.
Anheuser turns to Adrian.
ANHEUSER (CONT'D) Would our science advisor care to give us his assessment?
ADRIAN We expect enormous tsunamis to reach landfall in every continent.
ADRIAN The Cho Ming area will be impacted in approximately six hours.
He nods to one of the analysts, who types in a couple of commands.
ADRIAN (CONT'D) ...
ADRIAN (CONT'D) and it looks like the crust has shifted by nearly 23 degrees in a south- westerly direction.
ADRIAN (CONT'D) Here's the computer simulation.
Everybody stares as the graphic illustrates what happened to planet Earth.
ADRIAN (CONT'D) Our data also shows, that our earth's poles have reversed their magnetic fields...
ADRIAN (CONT'D) ...
ADRIAN (CONT'D) These are their new positions.
Anheuser looks at the monitor, then turns to Adrian.
ANHEUSER So Helmsley, what you're telling us here is that...
ANHEUSER the north pole is now somewhere in Wisconsin?
Silence.
Adrian clears his throat.
ADRIAN It's the south pole, sir.
An ALARM SIGNAL goes off--
A red light blinks on the plane's instrument panel.
YURI What's that?
SASHA Engine failure.
SASHA GOVNO!
SASHA Two of six are down.
SASHA We must get ready.
Yuri and Jackson are standing behind the pilots.
JACKSON Let's go wake up the kids.
Yuri nods and they make their way back to the lower deck.
Jackson's family are all asleep in their seats, Lilly in her mom's lap.
She looks like a little angel.
Jackson can't bear to wake them.
He caresses Lilly's face.
NOAH Why do you hate Gordon?
Jackson turns to see Noah is awake.
JACKSON What are you talking about?
JACKSON I don't hate Gordon.
NOAH But you don't like him either.
JACKSON I don't know him that well.
NOAH But I know him.
NOAH He's really nice.
NOAH You should talk to him more often.
NOAH You guys would get along really well.
This breaks Jackson's heart.
He pulls Noah tightly to his chest.
JACKSON I'll give it a try, Noah.
JACKSON I promise.
Kate opens her eyes.
KATE Is it time?
Jackson nods.
KATE (CONT'D) Wake up Lil'bee.
KATE (CONT'D) We're getting ready to land.
On the opposite side of the aircraft, Yuri and Tamara help the twins get into their life vests.
Noah is suspicious.
NOAH What's wrong?
Jackson looks at his kids.
They both look scared.
JACKSON Sasha told us, it could get a little bumpy...
JACKSON and wet.
The Antonov jerks to the side.
Two more engines out.
Alarm signals flash.
The remaining two engines barely hold the plane in the air as it dives into the clouds.
Jackson and his family huddle together.
He puts his arms around Lilly and Noah.
JACKSON Your daddy has to tell you something.
In the background, Gordon climbs down from the cockpit.
He is about to speak when he hears Jackson's voice.
JACKSON (CONT'D) I know that with my writing and work I didn't have a lot of time for you both...
Jackson glances at Kate.
JACKSON (CONT'D) I wasn't there for you, the way I should have been.
Jackson looks Kate directly in the eyes.
JACKSON (CONT'D) ...
JACKSON (CONT'D) And I am so very sorry for that.
Gordon watches as Kate pulls the kids and Jackson tight.
For the first time, they seem a little like the family they once were.
GORDON Jackson, Yuri...
GORDON I think you guys should come back up here.
First Jackson and then Yuri enter the cockpit.
Sasha points out of the window.
SASHA Don't ask me how that happened.
Behind them Yuri and Jackson stare at the snow covered mountains of the Himalayas.
SASHA (CONT'D) There's no more ocean, and it looks like we're pretty close to where we wanted to go.
GORDON It's as if the whole earth shifted by 1500 miles...
JACKSON No shit.
JACKSON It's called 'Earth Crust Displacement' Gordon...
JACKSON Prof. Hapgood, 1958.
Jackson brims with joy.
JACKSON (CONT'D) Way to go Charlie!
SASHA We lost our last two engines.
The plane drops rapidly, nearly scraping the tip of a mountain.
Sasha and Gordon are doing all they can to keep the Antonov in the air.
A vast glacier spreads out in front of them.
SASHA (CONT'D) I'll shoot for that glacier.
SASHA (CONT'D) Drain the brake fluids.
SASHA (CONT'D) It's going to get rocky...
SASHA (CONT'D) There, the blue levers!
The plane plummets, loosing altitude fast.
SASHA (CONT'D) Listen up guys!
SASHA (CONT'D) This may sound a little crazy, but here's what you got to do...
Jackson and Yuri come running.
Yuri yells at his boys.
YURI Get up!
YURI Follow me!
TAMARA Yuri bear, what are we doing?
YURI We're taking the Bentley!
Sasha is struggling with the gyrating wheel.
The glittering snow field comes flying towards them.
SASHA CHTO ZA...
SASHA Gordon!
SASHA We're still too fast!
Sasha pulls the Antonov back up.
SASHA (CONT'D) Now!
SASHA (CONT'D) Open it!
Gordon yanks with all his might.
A loud NOISE.
The cargo door drops open.
The Antonov is extremely close to the glacier's surface.
Jackson tries to start the Bentley, but nothing happens.
Everyone screams in panic.
They all go quiet, except for a few muffled barks from Caesar.
Yuri speaks towards the dashboard, slowly and clearly.
YURI (CONT'D) Engine...
YURI (CONT'D) start...
The motor revs to life.
Yuri looks at Jackson.
YURI (CONT'D) Voice control...
YURI (CONT'D) Sold me on it.
Sasha barely holds on.
He yells at Gordon.
SASHA Your turn Gordon!
SASHA Go!
SASHA Make sure that they make it out of here before I touch down!
GORDON What about you?!
SASHA I'll be fine!
SASHA I have to land this thing!
Gordon hesitates.
SASHA (CONT'D) What are you waiting for!
Sasha nods at him reassuringly.
Gordon bolts out.
The cargo door scrapes against the glacier, hurling ice everywhere.
The Bentley roars.
YURI Push it Curtis!
JACKSON We're waiting for Sasha and Gordon.
Noah turns and sees Gordon.
NOAH Tamara!
NOAH Open the door!
Gordon jumps in.
Tamara yells at him in desperation.
TAMARA Where's Sasha?
GORDON He said he'll be fine and we should get out of here before he touches down.
Yuri notices Tamara's distress as she keeps looking back to the cockpit.
Jackson slams the pedal down trying to gain as much speed as possible to soften their landing.
LILLY Daaadddy!
The Bentley shoots out the back of the plane.
As it hits the snow, the air bags deploy cushioning the passengers.
The Antonov hits the ice and catapults the rest of the luxury cars out of the back cargo hold.
They barrel past the Bentley like skittles, narrowly missing it as they fly off in opposite directions.
The plane skids across the glacier, clipping its wing and causing the aircraft to break apart.
Sasha has no control anymore and watches helplessly as he shoots towards the ledge in the Antonov, plunging into the deep.
The plane crashes and explodes.
As the snow settles we see that the glacier is scattered with luxury cars tomb-stoned in the snow.
The Bentley is half buried.
We hear Caesar barking.
JACKSON Everybody okay back there?
KATE We're all fine.
The door opens and Jackson climbs out, looking around.
Just above the wind, he hears the SOUND OF HELICOPTER BLADES.
One by one the others appear behind Jackson and stare at a surreal sight--
Several Chinese Mil-26 choppers airlift animals over the mountain pass.
GIRAFFES, ZEBRAS, EVEN ELEPHANTS hang by huge straps from these flying machines.
One of the smaller helicopters veers from the transport fleet and lands near the Bentley.
Armed soldiers jump out.
Their Commander speaks to them in a sharp tone.
CHINESE COMMANDER Welcome to the People's Republic of China.
Jackson nods to them.
JACKSON Thank you...
JACKSON Say thank you, kids.
The others acknowledge the soldiers as well.
Hi...
Hello...
CHINESE COMMANDER What color are your passes?
Jackson stands dumbfounded.
The Commander repeats.
CHINESE COMMANDER (CONT'D) What color are your boarding passes?
Still no answer.
He yells an order.
The soldiers point their guns at them.
YURI I have green card.
Surprised, Jackson turns to Yuri who's holding up three green plastic cards.
YURI (CONT'D) For my boys and me.
Tamara can't believe what she's hearing.
TAMARA It's a joke...
TAMARA a mistake...
TAMARA Right Yuri?
Yuri shrugs.
Tamara lunges at him.
TAMARA (CONT'D) You disgust me.
TAMARA (CONT'D) You pig.
Yuri brushes her off, coldly.
And then speaks so they can all understand him.
YURI You think I did not know about you and Sasha?
YURI May god rest that poor bastard's soul.
With that Yuri turns to the others.
YURI (CONT'D) I am sorry guys.
YURI (CONT'D) Good luck.
YURI (CONT'D) And Jackson remember, if someone wants to beat you...
YURI (CONT'D) he has to kill you first.
YURI (CONT'D) Come boys!
The twins grab Caesar and climb into the helicopter.
The dog barks furiously, wanting to stay with Tamara.
The next moment, the helicopter takes off.
GORDON What!...
GORDON Did that just happen!?
They're stranded.
Air Force One is in the background as Laura, Anheuser, and other members of the crew are rushed towards a group of waiting helicopters.
Adrian is a little way back in the middle of the pack.
A Chinese Officer with a list shouts over the noise.
CHINESE OFFICER Mr. Anheuser - you're in Chopper 1.
CHINESE OFFICER Dr.
CHINESE OFFICER Wilson the same.
Laura and Anheuser reach the chopper.
An authoritative Naval Officer greets them, and raises his voice.
CAPTAIN MICHAELS I'm Captain Richard Michaels.
CAPTAIN MICHAELS I'm the skipper of the American boat sir.
CAPTAIN MICHAELS After you!
Anheuser nods and climbs in the chopper.
Captain Michaels helps Laura in.
Adrian arrives just as the Chopper door slides shut and it lifts off.
Laura catches Adrian's look of unease before they soar away.
CAPTAIN MICHAELS My sincerest condolences Dr. Wilson, for your father...
Laura's look thanks him for this.
He turns to Anheuser.
CAPTAIN MICHAELS (CONT'D) Your party is the last to arrive.
ANHEUSER I've been told of damages?
CAPTAIN MICHAELS We haven't completed the assessment but it looks like we lost Number 4 when the crust shifted.
Captain Michaels looks up and points into the distance.
CAPTAIN MICHAELS (CONT'D) There it is!
The CAMERA follows the choppers revealing--
Nine gigantic oval gates that measure at least 60 stories, built into the face of a mountain.
In front of every gate there is a line of huge `Y' shaped metal support structures, which are the launching towers for the ships.
They are each at least 800 feet high.
It's an unparalleled feat of engineering.
The lead chopper descends onto a platform in front of one of the gates, dwarfed against this majestic setting.
The door slides open and Anheuser jumps out.
Laura follows.
She looks around in awe.
Even the utility entrances that lead into the mountain are immense.
The Captain guides them into the hollow mountain.
In the BACKGROUND we see an angry Yuri scream and argue with military personnel, waving his tickets.
YURI What do mean we can't board Number 4?
YURI I want to speak to your supervisor.
SOLDIER I am the supervisor!
SOLDIER Now get in line with all the others while we make arrangements.
YURI I want your name!
SOLDIER (pointing to his
BADGE) Can you read?
BADGE) Now get the hell back with the other green cards, or I'll have you detained.
The twins stand nearby, holding Caesar.
They look afraid.
Jackson and his group are small specks in a barren landscape.
They have made it down the glacier and are now walking over a scree field.
It is hard going.
Jackson carries Lilly.
JACKSON Keep thinking warm thoughts sweetheart.
JACKSON You're doing great.
Kate holds Noah by the hand.
Gordon and Tamara trail behind.
She's still very upset.
TAMARA I should have listened to you, Dr.
TAMARA Silberman.
TAMARA I actually liked the way I looked before that monster talked me into it.
GORDON Did you know he asked for a discount...
GORDON and he paid in installments?
TAMARA Cheap bastard.
GORDON You're better off without him.
GORDON What he said about you and Sasha, is it true?
Tamara nods silently.
TAMARA Now that he's gone I think he was worth a hundred times a man like Yuri.
Suddenly they hear the PUTTERING of an engine.
JACKSON You guys hear that?
In the distance, an old rusty truck comes bumping down the dirt road.
Jackson puts down Lilly and chases after it.
Neng and his parents drive past, billowing a huge cloud of dust just as Jackson reaches the road.
JACKSON Hey!
JACKSON Help!
JACKSON Wait for us!
But Neng doesn't hear him over the rattling truck.
Jackson, pissed, kicks at the rocks on the road.
JACKSON (CONT'D) Shit!
JACKSON (CONT'D) Shit!
Just then, Neng's mother, sitting in the back of the truck, turns and sees his tantrum.
She bangs on the rear window of the cabin.
Neng looks in the mirror and hits the brakes.
Jackson can't believe his luck.
The others show up and they all run towards the truck.
Anheuser and Laura follow Captain Michaels and a Chinese Steward over one of the many boarding bridges erected inside the cavernous mountain that lead to one of the monstrous arks.
Laura stops halfway, gazing in awe--
Deep down below, thousands of workers are swarming over the ship, readying it for launch.
Laura looks up and sees the contrast, spotting the SHEIK we met in the Dorchester Hotel as he boards comfortably with his huge family.
Laura points down at the workers.
LAURA Captain Michaels?
LAURA What happens to all those people?
The Captain doesn't know what to say.
Anheuser turns.
ANHEUSER Dr. Wilson, there's a protocol for all that.
ANHEUSER You just stick to your art.
ANHEUSER We'll handle the rest.
Laura hates him in that moment.
ANHEUSER (CONT'D) Captain?
ANHEUSER (CONT'D) Where is the Bridge?
Anheuser and Captain Michaels move away as Laura stands and watches the frantic workers who are now boarding the animals we saw being airlifted over the mountains.
CHINESE STEWARD Dr. Wilson?
CHINESE STEWARD Your cabin is this way.
Laura has a look of guilt as she follows the steward.
Thousands are on the march up the mountains.
Behind them a valley stretches into the horizon.
Plumes of smoke rise from destroyed cities in the distance.
Amongst the refugees, we discover Satnam, the young astrophysicist, holding his little son.
The rest of Satnam's family trails behind.
Distant WARNING SIRENS pierce the silent march, coming from the cities below.
People start to scream and run, but Satnam stands there frozen.
He fumbles for his satellite phone, then hits a number on its speed dial.
Adrian is unpacking.
He lays down his copy of `Farewell Atlantis' just as his cell phone rings.
ADRIAN Satnam?
ADRIAN Where are you?
SATNAM On the Nampan Plateau...
Adrian's face goes pale.
ADRIAN What?!
SATNAM There's a tidal wave coming from the East!
SATNAM It's huge!
ADRIAN Satnam, what happened?
SATNAM We never got picked up, Adrian, the airlift never came!
Adrian closes his eyes.
Satnam swallows hard.
He stares out into the valley.
SATNAM I have to go!
A wall of undulating foam and debris comes rolling towards him.
A tidal wave of gigantic height.
Everybody panics and scratches for a higher elevation.
But for Satnam it is clear, they do not stand a chance.
He picks up his little son, squeezing him tightly to his chest, humming an Indian lullaby for the scared child.
Adrian hears SCREAMING on the phone and the deafening sound of the approaching wave.
He tenses up, desperate but unable to do anything.
As the noise reaches its height, the line goes dead.
Adrian is left breathless.
Adrian storms onto the bridge.
Many officers and analysts are at work under Captain Michaels.
ADRIAN Do we have the latest satellite images of Napam, India?
SCIENCE OFFICER One moment, sir.
Anheuser and Prof.
West step over and join him.
ANHEUSER Helmsley, what's going on here?
ADRIAN Looks like our model was wrong.
They all stare at the monitor showing several tidal waves coming in from the south.
ADRIAN (CONT'D) Satnam was talking about a wave from the East.
A science officer selects a different quadrant on the satellite display.
They all stare at the new tidal wave that's coming from the East of the Cho Ming valley.
PROF. WEST Jesus!
Anheuser is shocked.
ANHEUSER What does this mean?
ADRIAN The flooding will happen earlier.
ADRIAN Bobby, can you plug in the new data please?
As the officer does this, Prof.
West looks at Adrian with questioning eyes.
ADRIAN (CONT'D) Satnam didn't get picked up.
Prof. West is horrified.
SCIENCE OFFICER Ready sir.
Adrian turns back to the monitor and sees the new tidal wave that is coming towards the Cho Ming valley.
ADRIAN This one is at least 1500 meters high!
ANHEUSER Talk to me Helmsley.
ANHEUSER What does this mean for us?
ADRIAN Bobby, plug in the new data and adjust the count down?
Every one on the bridge stares at a display.
It reads--
02hrs - 09min - 07sec
The science officer nervously hits a few keys and the display changes to--
00hrs - 28min - 10sec...
and counting.
We see the shock on Anheuser's face.
ANHEUSER Get me the other Heads of State.
Neng's truck, loaded with Jackson and the others, creeps up to the service entrance of the launch site.
A lone figure awaits them.
This is Neng's older brother Lin, who we saw signing up for the 'Chinese Dam Project'.
Lin notices the strangers in the pick-up truck.
LIN Who are they?
Neng answers hesitantly.
NENG We found them by the side of the road, my brother.
LIN You must send them back.
NENG I am a follower of the great Lama Yak La.
NENG You know I cannot do that.
The others watch the interaction but do not understand.
Jackson senses a problem.
He grabs Lilly and Noah.
JACKSON Come with daddy.
Gordon and Tamara stare perplexed as Jackson approaches Lin with his kids.
JACKSON (CONT'D) At least take our children with you.
JACKSON (CONT'D) Please.
Lin answers in broken English.
LIN Why should I do that?
JACKSON For the same reason you sent for your parents.
Lin stares at him stone faced.
In desperation, Kate turns to Mrs. Pang.
KATE I have no clue if you understand what I'm saying, but I ask you as a mother, please take my kids with you!
Silence.
A beat.
The old Chinese lady turns to Lin.
MRS. PANG We are all children of this earth.
LIN My plan will not work for so many, mother.
She looks up at her son, determined.
MRS. PANG We will take them all.
MRS. PANG Bata?
Mr. Pang nods and reluctantly, Lin motions to Jackson to follow.
Kate bows to Mrs. Pang.
KATE Thank you ma'am.
KATE Thank you so much.
Jackson and the others acknowledge what Kate has done.
We finally reveal the unbelievable magnitude of this ship yard, built into the hollow belly of the mountains.
Nine gargantuan vessels are lined up next to each other.
Their size is at least four times that of the `Freedom of the Seas'.
However, they look more like spaceships than anything, having been built aerodynamically to withstand the full force of nature.
But only three of these monstrous ARKS are complete.
Number 4 is being repaired, all the others are still under construction, surrounded by scaffolding.
Suddenly SIRENS goes off!
The boarding bridges to the finished vessels begin to retract.
There's growing confusion among the thousands of workers and security personnel.
Opposite the boarding bridges, on a large platform, Yuri and his boys sit in line with the other waiting passengers.
They watch as massive stern gates begin to close.
Yuri jumps up and yells to the others.
YURI They're leaving without us!
The soldier from earlier points his gun at him.
SOLDIER What did I tell you!
Caesar barks at the guy.
YURI Look!
YURI Idiot!
YURI They are leaving you behind too!
The soldier turns to the ships and Yuri knocks him out.
He grabs his boys and runs towards the closing gates.
All the other passengers surge forward with him.
In the distance, on the bow side of the ships, the huge mountain gates of the bay open, revealing a stunning view of Cho Ming Valley.
Lin leads his group over a ridge.
In front of their eyes--
The gates to the mountain open!
LIN We have to hurry!
LIN They launch!
LIN We run out of time!
They follow Lin rushing down the hill, towards one of the many Y-shaped launch structures towering in front of the gates.
Neng and Kate help Mr. and Mrs. Pang down the rocky terrain.
A screeching and thundering noise!
THE THREE COMPLETED VESSELS BEGIN TO INCH FORWARD on metal girders connecting the Y-shaped launch towers.
Laura feels a jolt.
She rushes out of her small cabin and into a swarm of people moving down a crammed endless corridor.
She struggles to fight her way through.
A digital voice blares over the speakers.
COMPUTER VOICE Countdown to departure.
COMPUTER VOICE Launch in 17 minutes - 42 seconds.
Laura bumps into one of Adrian's Science Officers.
LAURA Where can I find Adrian Helmsley?
SCIENCE OFFICER He's in the Technical Command Centre.
SCIENCE OFFICER Follow me.
The three gigantic vessels emerge from the mountain, into the open.
Support helicopters swarm around them like flies.
Lin and his group look like ants as they scale the metal ladders of one of the launch towers.
Verbal commands fly back and forth.
Anheuser watches the preparations from a large window.
He looks over to the command bridges of the other vessels as they continue to be pulled into place.
We cut to the various Heads of State, all at their command posts.
A hatch opens at the top of the launch tower.
Lin is the first to climb out.
Right before his eyes, the hull of the American Ship slowly creeps towards him.
He's but a speck against this man-made behemoth.
Lin hastily pulls the others up.
LIN Faster, Neng!
LIN Help father!
LIN Mother, give me your hand.
It's a race against time.
The huge ship's hull closes in fast.
Lin and his family crawl up the side arm while Jackson hurries to pull up the rest of the group.
Lilly freezes at the sight of the approaching ship.
JACKSON Move Lil'bee!
Jackson rips her out of harm's way, just in time.
In a frenzy, he pushes her up the support arm where the others are already huddled on a small platform.
As the towering wall of steel passes by them, inches from their faces, Mr. Pang loses his balance.
Jackson and Lin both see this, but Jackson is closer--
He grabs the old man by his arm, saving him from falling to his death.
For the first time, Lin acknowledges Jackson with a nod.
The three completed ships are half way out, grinding to their final launching position.
A mob of passengers led by Yuri has fought their way to the ship.
More and more people join them, including soldiers.
Lin, Jackson and the group are huddled on the platform.
The sound of SCREAMING PEOPLE makes them turn.
The storming masses have arrived at the access platform.
There is now a huge drop off between them and the tails of the ships.
TAMARA Oh my god, that's Yuri!
Next to Yuri are his twins, holding Caesar.
She yells!
TAMARA (CONT'D) Caesar!
The little dog hears Tamara and jumps out of Oleg's arms, leaping onto one of the thick cables, that connects the platform with the launching towers.
Alec and Oleg attempt to run after Caesar, but Yuri grabs them by their necks.
YURI Let that stupid dog go!
He's panicked.
The arriving masses are pushing them to the drop off at the edge of the platform.
The ship has reached its targeted position.
A small hatch lines up directly in front of Lin and his group.
LIN Okay.
LIN Now!
One by one they all climb into the hatch.
Jackson being the last in, notices that Tamara has stayed back.
JACKSON Tamara!
JACKSON Come on!
JACKSON Get in!
She doesn't move, anxiously waiting for her beloved dog darting towards her.
The mob pushes at Yuri and his boys.
Passengers on either side tumble off the platform.
Yuri watches one of them fall, hitting his head against a tiny ledge 8 feet below.
To his right, he sees a small ladder leading down.
YURI Down there!
YURI Oleg, you go first!
As they hurry down the ladder, people keep tumbling into the deep.
Reaching the ledge, Oleg discovers Caesar running towards Tamara.
OLEG Daddy look, Tamara!
Yuri cannot believe his eyes.
The hatch behind Tamara begins to move.
The hydraulic supports are being lifted, sealing up the vessel.
TAMARA Caesar darling!
Jackson reaches out from the closing hatch.
JACKSON Tamara!
JACKSON Get in!
Tamara climbs inside the hatch and turns.
TAMARA Come to mommy!
Caesar leaps into her arms only seconds before the hatch seals.
As a last gesture, Tamara sticks out her arm and gives Yuri the finger.
Lin leads the group into a long and narrow chamber where the hydraulics for the tail gate are located.
He opens a tool cabinet, retrieving a giant electrical power drill, almost too big to be carried by one person.
Lin climbs to a hatch near the ceiling and begins to unscrew the huge bolts.
He looks at Jackson.
LIN I need your help.
Laura and the Science Officer enter the Technical Command Center.
She finds Adrian staring at a wall of monitors showing the horrifying scenario on the platforms.
People are falling to their deaths in large numbers in their desperation to board the ship.
LAURA What in god's name is happening Adrian?
ADRIAN Anheuser convinced them all to launch.
Outside, panicking workers, screaming for their life!
Deserted passengers waving their green cards!
Adrian makes a decision and rushes out.
Anheuser turns hearing Adrian storming onto the bridge.
ADRIAN Anheuser!
ADRIAN We have to stop this madness.
With that, Adrian turns to the Communication Officer.
ADRIAN (CONT'D) Bobby, make sure the other bridges can hear this.
The officer hesitates as Laura enters in the background.
ANHEUSER What do you think you're doing?
ADRIAN I know exactly what I'm doing.
ADRIAN Turn it on!
Bobby flicks a switch.
Adrian's voice echoes through all the ships.
ADRIAN (CONT'D) This is Adrian Helmsley, science advisor to President Wilson...
The German Chancellor turns to one of the technicians on the bridge of the European Ship.
GERMAN CHANCELLOR Can you please turn up the volume, Mr.
GERMAN CHANCELLOR Hoffmann?
Next to her stand the British and French Prime Ministers.
ADRIAN I know we've all been involved in making difficult decisions...
ADRIAN to save our human civilization...
Anheuser looks on stoney faced.
ADRIAN ...
ADRIAN But to be human means to care for each other, and civilization means to work together to create a better life.
ADRIAN If that's true there is nothing human and nothing civilized about what we're doing here.
ADRIAN Ask yourselves ...
ADRIAN Can we really stand by and let all those people out there die?
Laura watches him proudly.
ADRIAN (CONT'D) A civilization that allows that, does not deserve to survive.
ADRIAN (CONT'D) Or at least I don't want to be part of it.
Anheuser cuts in with sarcasm.
ANHEUSER We'll miss you Helmsley but somehow we'll get by.
ANHEUSER Officer switch that off.
The Communications Officer looks at Adrian.
ANHEUSER (CONT'D) That's an order soldier.
ADRIAN Don't do it!
The Russian President, together with the heads of state from China and Japan, listen in as Adrian responds.
ADRIAN We have to open our gates and let these people in.
ADRIAN All of them.
Anheuser has had enough.
ANHEUSER Have you lost your mind?
ANHEUSER Look at the countdown.
ANHEUSER We have less than five minutes left...
ANHEUSER And none of our ships have the resources to feed those people.
ANHEUSER If you save them today we all starve tomorrow.
He's almost screaming now.
ANHEUSER (CONT'D) Do you wanna be responsible for the extinction of the human race?
ANHEUSER (CONT'D) Can you handle that, Adrian?!
Silence.
Adrian's battle seems lost.
But he doesn't give up, and instead speaks softly now.
ADRIAN There is a young astrophysicist from India who is the reason we are all here, trying to give mankind a second chance.
ADRIAN He's the one who discovered it all, the one who connected the dots.
ADRIAN We all owe him our lives.
All eyes are glued to Adrian.
ADRIAN (CONT'D) I just learned that he was killed with his family by a tsunami in eastern India.
ADRIAN (CONT'D) You know why?
Adrian stares Anheuser in the eyes as he continues.
ADRIAN (CONT'D) He died because we forgot to pick him up.
ADRIAN (CONT'D) I beg you...
ADRIAN (CONT'D) whatever our future holds don't let us start it with an act of cruelty.
ADRIAN (CONT'D) What will you tell your children...
ADRIAN (CONT'D) and their children?
Silence.
Laura steps up alongside Adrian.
LAURA If my father were here, he would open the gates.
Adrian and Laura share a look.
RUSSIAN PRESIDENT The people of Russia along with...
His Asian colleagues nod in approval.
RUSSIAN PRESIDENT ...
RUSSIAN PRESIDENT China and Japan agree to open the gates.
The German Chancellor speaks up.
GERMAN CHANCELLOR The United Kingdom, Spain, France and Germany, and I believe I can also speak for the Italian Prime Minister...
GERMAN CHANCELLOR ...
GERMAN CHANCELLOR We vote to open the gates.
Laura and Adrian watch Anheuser shaking his head in defeat.
Bobby, the Communications Officer smiles with relief.
Adrian turns to the Captain.
ADRIAN Captain Michaels, you heard them.
One by one the gigantic gates at the stern of the three ships begin to creek open.
The masses gathered on the platform CHEER wildly!
Lilly crawls through the CONNECTING TUNNEL meeting up with Kate in a large bay on the other side.
LILLY Phew...
LILLY It stinks in here.
Together with Neng and his parents, they all look up in
A Giraffe, chewing her cud, smiles down at them.
Caesar barks at her.
TAMARA Sssh...Caesar.
A second later, hundreds of different ANIMALS RESPOND.
They are in the zoological bay.
Gordon helps Noah up the small ladder leading to the connecting tunnel.
Just as he goes to hand him Jackson's backpack, the HYDRAULIC MOTORS begin to GROWL!
Lin looks up in panic.
He screams.
LIN They're opening the gate!
LIN It will crush us!
The whole ceiling begins to lower towards them.
From down below, Jackson sees his son about to be hit by it.
JACKSON Noah!
JACKSON Watch out!
Gordon makes a split second decision.
With all his strength, he shoves the boy into the tunnel.
From the other side of the tunnel, Kate watches as the metal ceiling misses Noah by a hair, but catches Gordon, wiping him off the ladder.
KATE No!
Jackson watches helplessly as Gordon falls past him.
He survives his landing and desperately tries to grab on to the sloping surface, but he can't.
He slips.
Gordon is crushed between the gears, sharing his last look with Jackson before he dies.
Kate helps a trembling Noah out of the tunnel.
NOAH Something happened, mom.
Kate pulls him close and shuts her eyes tightly.
She fights back the tears.
Jackson and Lin know they're running out of time, their remaining space is shrinking every second.
JACKSON We have to stop it!
Lin grabs the huge electrical power drill nearby and attempts to jam it between the hydraulic arm and the wall.
As it digs deeper into the metal, the hydraulic starts to slow down.
Still on the ledge, Yuri and the boys watch as the huge boarding gate lowers towards them.
They are trapped.
Just then, the gates begin to slow, but surely they will be crushed.
Back in the chamber, Lin still struggles with the drill.
Suddenly he slips.
Jackson manages to catch his fall.
But in the process Lin's foot gets caught between the gears, mangling it.
He screams in pain as the hydraulic slowly grinds towards a halt.
JACKSON You did it, man.
JACKSON You did it.
In great pain, Lin grins back at him.
The gates of the ships hit the access platform with a thundering noise.
People begin to rush on board.
Alarm signals go off.
The Captain turns to one of his officers.
CAPTAIN MICHAELS What's wrong with the gate?
OFFICER I don't know.
OFFICER Maybe there's something jamming it, sir.
The countdown on the monitor reads 2 min.
40 sec.
Laura and Adrian share a worried look.
We hear a HOLLOW BELL ring!
Lama Yak La rings the large bronze bell of his monastery.
The booming sound echoes through the Cho Ming valley.
As a gentle wind catches the Lama's clothes, he looks up--
A tidal wave of immeasurable proportion crests the mountains.
The Lama continues to strike the bell as the monastery is wiped clean from the earth.
The technicians desperately try to figure out what's wrong.
An officer waves Adrian over.
SURVEILLANCE OFFICER Sir, we have a breach in the zoological bay.
ADRIAN Can you zoom in?
The video camera moves in on Kate, Noah and Lilly.
Adrian can't believe his eyes.
He turns to Laura.
ADRIAN (CONT'D) I know those kids.
ADRIAN (CONT'D) Remember the book I told you about?
ADRIAN (CONT'D) Their father wrote it.
Captain Michaels shouts across the room.
CAPTAIN MICHAELS We're loaded.
CAPTAIN MICHAELS We can close the gates sir.
ANHEUSER Do it!
Anheuser looks nervously at the countdown.
It reads 1:34
Above Yuri and the boys, people are leaping from the access platform onto the stern gate of the American ship.
Yuri looks for a hole in the flow of people before seizing his chance and lifting the first of his boys up.
YURI Pull yourself up!
Oleg manages to reach up and hold onto the gate.
Inside the ship, officers yell.
DECK OFFICER To the lower decks people!
The gates suddenly screech back into life and begin to close.
Yuri doubles his efforts lifting Alec higher, but Alec cannot quite reach.
Yuri strains with all his effort before deciding.
YURI Oleg!
YURI Catch your brother!
Yuri leaps forward holding Alec out in his arms.
Oleg manages to grab his brother's hands as Yuri lets go and falls into the deep crevasse below.
He makes no noise until he hits the rocks beneath.
Oleg pulls his brother from above.
A SIREN blasts.
Both of Yuri's sons are now on deck.
A loading officer pulls them back, away from the gate.
DECK OFFICER Boys, you gotta move.
ALEC We wait for our father!
ALEC He's still down there!
The loading officer attempts to comfort them.
DECK OFFICER There's no one down there.
DECK OFFICER Come on boys, come...
The Officer and the boys look back as the stern gate slowly closes.
But with a SCREECHING sound it grinds to a halt.
The gate is jammed open leaving a twenty foot gap.
ALARMS sound.
Anheuser and the Captain stare at the monitors.
ANHEUSER Why is the stern gate not closing?
CAPTAIN MICHAELS Something's wrong with the hydraulics, sir.
ADRIAN Captain, over here.
They race over.
Adrian points to a monitor.
ADRIAN (CONT'D) I think we found the problem.
On the monitor, they see Sarah and the others desperately waiting for Jackson and Lin.
ADRIAN (CONT'D) How did they get in there?
SURVEILLANCE OFFICER They must have come through the hydraulic chamber.
SURVEILLANCE OFFICER There...
Bobby, the Surveillance Officer, selects a different camera and we now see inside the tunnel in which Jackson is pulling along a wounded Lin.
LAURA That guy is injured.
LAURA Something must have gone wrong.
ANHEUSER You're damn right something went wrong!
ANHEUSER Congratulations Helmsley, you may have just killed us all but as long as your conscience is clean...
Adrian tries to ignore this.
ADRIAN Let's get an emergency crew there right now.
ADRIAN I'll meet them at the Hydraulic Chamber.
Anheuser sneers him, shooting a look to Laura.
ANHEUSER You think you're the main man now, just because your fucking the President's daughter?
Without thinking, Adrian turns and punches Anheuser hard in the face.
He drops to the floor, out cold.
Everyone stands in stunned silence.
Laura smiles.
Adrian looks around.
ADRIAN What are you all waiting for?
They speed off.
The countdown reads 0 min.
53 sec.
Further down in the valley, the tidal wave has reached the Cho Ming airfield, blasting away the planes with overwhelming force.
The massive propellers of the ships begin to turn.
However, the props of the American ship don't move.
In the background, the huge tidal wave comes thundering towards them.
An IMPACT WARNING sounds as Adrian and Laura race through the crammed hallways with members of the rescue crew.
One of the officers explains.
TECHNICAL OFFICER If we can't close the stern gate, then the engines won't start.
ADRIAN There's no way to override it?
TECHNICAL OFFICER No sir, it has to be done manually.
Kate, Noah and Lilly watch as Jackson nears the end of the tunnel with Lin.
Neng comforts his brother who's about to pass out.
NENG Almost there, Lin...
All three vessels are now engulfed in churning water.
They rock back and forth.
Only the huge support towers they're resting on, keep them anchored.
A new ALARM sounds as water begins to shoot through the open stern gate of the American ship.
The people on the loading bay panic, among them we see Alec and Oleg.
The same ALARM rings out in the hallways of the ship.
Laura, Adrian and their party are all braced against the corridor, as the vessel undulates back and forth.
SURVEILLANCE OFFICER Water has penetrated the stern!
Laura looks unsure.
LAURA What now?
SURVEILLANCE OFFICER The rear of the ship will start sealing itself up one compartment at a time.
Adrian looks at him.
ADRIAN Then how will we get to the hydraulic chamber?
SURVEILLANCE OFFICER If we don't hurry, we won't be able to.
Despite the violent movement of the ship, Adrian pushes on down the corridor towards the back of the boat.
They follow.
Water is also now rushing into the Zoological Bay and only the giraffe can manage to keep her head dry.
Jackson is not yet out of the tunnel with an unconscious Lin.
Kate shouts across to Tamara.
KATE Tamara!
KATE Take Lilly and Noah.
Kate reaches in to help Jackson as Tamara begins to move with Lilly.
Noah remains back with his mother.
Jackson finally makes it through with Lin.
Kate is almost tearful with relief to see him.
KATE (CONT'D) I was so worried about you.
Suddenly the Zoological bay begins to seal itself off.
Lilly, already in the next compartment with Tamara and her dog, screams out as a chamber door quickly slides up, from the floor to the ceiling.
It separates Lilly from her family.
LILLY Mummy!
Jackson and Kate turn but it's too late.
They only catch a glimpse of Lilly before they are sealed in.
The water level continues to rise.
Panicked, Tamara turns and looks around.
Down the corridor, in the distance, she sees Adrian, Laura and the rescue crew approaching.
But between them she spots the next chamber door rising quickly.
TAMARA Lilly run!
Lilly starts moving as Tamara turns and picks up Caesar.
Moving quickly, Lilly is able to climb up and over the fast rising door.
But as she dangles from the other side, she looks down and is too scared to jump.
TAMARA (O.S) (CONT'D) Lilly!
TAMARA (O.S) (CONT'D) Take him.
Lilly looks up and sees two hands straining to hold Caesar above the quickly narrowing gap.
In a courageous move, Lilly grabs the little dog before he gets crushed and together they fall to the ground.
Back on the other side of the chamber door, Tamara looks around.
She is trapped now as the water continues to rush in.
Laura picks Lilly up and comforts her.
Adrian realizes they are too late.
He turns to the rescue crew.
ADRIAN Is there any way to talk to them?
Lilly is close to tears.
The water continues to flood in as Jackson helps Neng with his unconscious brother.
JACKSON We have to move him higher.
JACKSON Over there!
Suddenly, a VIOLENT SHAKE throws them all off balance, pitching them into the water.
In the debris-filled, murky waters we see that the fuselage of Air Force One has slammed against the first of the ship's launch towers.
Slowly it begins to bend, finally giving way.
The other launch towers follow like dominos.
The ship is ripped from its anchorage and sent drifting sideways, rudderless.
Chaos.
Fear.
Everybody holds on for dear life.
The vessel is swept away, over the mountain ridge.
Alec and Oleg scream, desperately trying to hold on as the whole ship capsizes.
The giant ship drifts upside down and rudderless - smashed around by the debris and raging waters.
But then, as it hits another ridge, it rolls right side up and seems to steady itself.
However, the strong currents continue to force it through the mountain ranges of the Himalayas.
The officers try to regain some control.
NAVAL OFFICER Moving at 34 knots, sir.
CAPTAIN MICHAELS What is our position?
NAVIGATION OFFICER Darjeeling valley, heading south east, sir.
The Captain's face drops.
CAPTAIN MICHAELS You must be kidding!
The water rises fast as Kate sees the severity of Lin's wound for the first time.
KATE We need something to stop the bleeding or he'll die.
A split second later Noah holds out his belt.
NOAH Mum, will this do?
Suddenly Jackson hears a voice over a speaker.
ADRIAN Mr. Curtis...
ADRIAN I'm Adrian Helmsley.
ADRIAN We met once before.
ADRIAN Your daughter is with me.
Kate screams with relief.
KATE Lilly!
Adrian is using an emergency wall intercom, with Laura next to him, holding Lilly.
LILLY I'm alright Mom!
Caesar barks.
Tamara hears Caesar over the speaker in her compartment and smiles with relief.
She is struggling to stay afloat though, and is running out of air.
Jackson discovers the wall speaker.
He moves closer to it.
ADRIAN We can't get to you.
ADRIAN Whatever you did, jammed the hydraulics.
ADRIAN If you can't get it out...
ADRIAN None of us will make it.
All eyes are on Adrian as he speaks.
ADRIAN You're our only hope.
Adrian looks at Laura.
JACKSON I'll go back.
JACKSON I'll try my best.
NOAH I'll go with you.
JACKSON You stay with Mommy.
Jackson looks at Kate.
JACKSON (CONT'D) I'll be right back...
The water is up to their chest now.
Jackson takes a breath and disappears underwater.
Back on the bridge, Anheuser regains consciousness and gets to his feet.
His nose is bleeding.
He looks around him.
ANHEUSER Captain, what's happening?
The Captain looks at him annoyed.
CAPTAIN MICHAELS What's happening?...
CAPTAIN MICHAELS We're heading straight for the north face of Mount Everest, Mr. Anheuser.
Anheuser looks at him dumbfounded as he stumbles to the window and sees the massive rock face of Mount Everest in the distance.
Jackson swims down into the dark chamber and reaches the jammed power tool, pulling at it.
But it doesn't budge.
The water level in Tamara's compartment is at its height now and she goes under.
She struggles below the surface for a moment, looking around desperately for a way out but there is none.
Tamara drowns.
Jackson manages to find an air pocket.
He fills up his lungs with air and thinks hard.
As he strips off his jacket, he seems to have a plan.
He dives under again.
Lin is being held up in the water by his brother and parents.
Kate has wrapped the belt around his lower leg and now pulls it tight.
Lin screams.
Noah uses this as the moment to dive underwater, unnoticed, to go and help his father.
Back under water, Jackson is using the extension cord of the power drill to pull himself down to the tool cabinet.
Jackson opens it, retrieving a giant crowbar.
He begins to use it to dislodge the tool but it's hard work.
Anheuser and everybody on the bridge stares as the north face of Mount Everest is almost upon them.
Kate and the Pangs are desperately close to running out of air now, but despite this, Kate still tends to Lin.
After a moment she turns and is first confused then horrified to see that Noah is nowhere to be found.
KATE Noah!
Jackson pulls with all his might, but he can't quite shift the drill.
To his surprise, a pair of young hands join his on the handle of the crowbar.
Noah is alongside him now, helping.
Working as father and son, they manage, little by little, to loosen it before finally the drill comes free.
Adrian gives Noah the thumbs up and the boy heads back to the surface.
Jackson goes to follow but in the last moment he spots the knapsack containing his laptop.
He dives back down for it.
Noah emerges from the water.
NOAH Mom, we did it!
Kate pulls him to her, relieved he is safe.
Noah smiles and calls out towards the nearly submerged speaker.
Lilly and Laura wait nervously.
They hear a muffled voice.
NOAH We got it free.
NOAH Can you hear me?
NOAH We did it!
Adrian leaps up when he hears this.
He flicks a button on the intercom.
ADRIAN Captain Michaels - close the gate!
Hearing this, the Captain yells the eagerly awaited order.
CAPTAIN MICHAELS That's affirmative.
CAPTAIN MICHAELS Close the gate!
TECHNICAL OFFICER Ay, ay, Sir.
We hear a BOOMING sound as the tail gate finally seals.
Jackson reaches his knapsack, but when sees Noah's cell phone lying next to it, he makes a decision and reaches for that instead.
He hears the muffled sound of the engines and smiles.
But as he turns to swim back, his face freezes--
He's looking into the lifeless eyes of Gordon, who floats inches from his face.
The gigantic propellers fight against the current, hitting rock at the base of the mountain.
The battle seems hopeless.
Captain Michaels yells at the top of his lungs.
CAPTAIN MICHAELS Engage starboard stabilizers!
OFFICERS One is engaged...
OFFICERS two is engaged...
OFFICERS number three is out, sir!
The vessel scrapes against the rocks, throwing Anheuser to the floor.
The giant ship escapes the mountain with an inch to spare.
Everyone on the bridge watches in awe as Mount Everest, earth's highest peak, drifts slowly past.
After a long beat, they begin to holler and cheer.
Kate hears the CHEERING coming from the speakers.
The water level stops rising but she still looks around in panic.
KATE Noah!
KATE Where is he?
Noah begins to cry.
NOAH He was just behind me...
Finally!
Jackson bursts out of the water and takes a lungfull of wonderful air.
Kate and Noah are overjoyed.
The Pangs smile to one another.
Jackson looks Kate squarely in the eyes.
JACKSON If you would ever consider to give me another chance...
JACKSON I promise, I'll always be there when you need me.
Kate embraces him tightly.
KATE Whatever you do...
KATE I will never let you go again.
Noah is all smiles.
We hear a voice.
ADRIAN ...
ADRIAN Day 988.
ADRIAN No one is waiting for anything to happen...
The CAMERA moves over the last lines of Jackson's novel.
Adrian sits in his cabin, his copy of `Farewell Atlantis' in his lap.
ADRIAN ...
ADRIAN and all we can hear is the sound of our own breathing that reminds us we are still sharing our memories, hopes and ideas.
Opposite him, Laura sits listening to him read.
ADRIAN (CONT'D) ...
ADRIAN (CONT'D) And funny, just today we found out that the entire crew of the Atlantis, somehow or another, has relatives in Wisconsin.
ADRIAN (CONT'D) The end.
Adrian closes the book.
There's a moment of silence.
LAURA How many copies did you say that sold?
ADRIAN Less than 500.
ADRIAN It's what you might call a cult classic.
Laura looks at him grinning.
LAURA It seems we have very different tastes Mr. Helmsley?
ADRIAN Well that's healthy Dr. Wilson.
ADRIAN Something we could maybe explore...
ADRIAN unless you have other pressing engagements.
LAURA Actually my diary's pretty open.
The intimate moment is cut short.
OFFICER Mr. Helmsley to the bridge please.
Adrian and Laura make their way to the bridge.
CAPTAIN MICHAELS Ladies and gentlemen, this is Captain Michaels speaking.
CAPTAIN MICHAELS In a few minutes, I will be giving the orders to unseal the decks.
Jackson and his family stand amongst thousands of other people who are gathering in anticipation.
CAPTAIN MICHAELS Please be careful when you step out and of course...
CAPTAIN MICHAELS enjoy the fresh air.
Jackson kneels down and zips up Lilly's jacket.
She is holding Caesar, whose still wearing his diamond collar.
LILLY Daddy?
LILLY When can we go back home?
JACKSON There's nothing we can go back to Lil'bee.
JACKSON Whatever's out there, that's our home now.
JACKSON Don't be scared.
LILLY I'm not Daddy.
LILLY No more pull-ups.
JACKSON That's my big girl.
Jackson squeezes Lilly's shoulder.
OLEG Can we pet him?
Lilly turns to see Yuri's boys standing next to her.
LILLY Of course you can.
LILLY He's your doggie.
The boys both smile at her.
Adrian and Laura enter the bridge.
ADRIAN You called for me, sir?
CAPTAIN MICHAELS Prof. West has something to show you, Mr. Helmsley.
The Captain directs him to a monitor.
CAPTAIN MICHAELS (CONT'D) Looks like your scientific projections are way off again.
The Captain grins at Prof.
West.
PROF. WEST The water is receding much faster than we projected, Adrian...
A monitor reveals an image of the African continent, however its shape changed dramatically.
The image of the southern tip is enlarged.
LAURA What's that?
PROF. WEST It's hard to believe, but the Himalayas are no longer the roof of the world.
PROF. WEST It's now the Drakensberg mountains of Kwa-Zulu Natal.
PROF. WEST The whole African continent has risen several thousand feet and most likely, never even flooded.
CAPTAIN MICHAELS Our European colleagues have already set course for it.
Captain Michaels hands Adrian a short wave radio.
CAPTAIN MICHAELS (CONT'D) Here, somebody wants to talk to you.
Adrian curious, grabs the mic.
ADRIAN This is Helmsley.
We hear a muffled, raspy voice through the speakers.
Harry Helmsley stands beside the cruise ship's Captain.
VOICE No, this is Helmsley.
ADRIAN Dad!...
ADRIAN Is that you?
Adrian is ecstatic.
Captain Michaels explains.
CAPTAIN MICHAELS We should have a visual of the `Freedom of the Seas' shortly.
ADRIAN Dad.
ADRIAN We're coming to pick you guys up.
ADRIAN How's Tony?
Harry looks over at Tony who's listening, smiling.
HARRY HELMSLEY He's fine, son.
HARRY HELMSLEY We're all fine.
ADRIAN See you guys soon.
ADRIAN Bye dad.
Harry hangs up.
He picks up Tony, embracing him wildly.
Adrian, still excited from speaking with his dad, grabs Laura and kisses her on the lips.
She squeals.
ANHEUSER Put that woman down Helmsley.
Adrian looks at Anheuser, unsure of what he might say.
ANHEUSER (CONT'D) Young guys like you with your idealistic dreams, you think you can change the world...
Adrian and Laura exchange a look.
ANHEUSER (CONT'D) I just pray to God, that you keep on making the right calls...
ANHEUSER (CONT'D) in this new world of ours.
Adrian nods and with a smile to Laura turns to leave.
ANHEUSER (CONT'D) Mr. Helmsley, one more thing.
Adrian turns back.
ANHEUSER (CONT'D) There was no one.
ADRIAN Pardon me?
ANHEUSER There was no white kid better than you.
ANHEUSER I'm terribly sorry I said that.
Anheuser puts out his hand.
Adrian takes it.
CAPTAIN MICHAELS This is your Captain speaking.
CAPTAIN MICHAELS Standby to open Deck 1.
OFFICER Standing by Sir.
Neng pushes his brother Lin in a wheelchair onto the deck next to his parents.
Mrs. Pang turns to her husband.
MRS. PANG I wonder will the clouds look the same and the stars?
MR.PANG Do not fear.
MR.PANG Some things will never change.
The old Chinese man forces a little smile.
Closer to the front of this crowd Jackson approaches Noah.
JACKSON I thought you might want this.
He takes Noah's cell phone from his pocket and hands it to him.
NOAH Do you think I'll still get a signal ...
NOAH Dad?
Jackson is touched to hear him use that word.
He smiles and hugs him.
Adrian, Laura and Anheuser arrive alongside them.
ADRIAN I finally finished your book Jackson.
KATE Really?
KATE You may well be the first person who ever got to the end.
Jackson looks at her, smiling playfully.
JACKSON Excuse me, I believe he's addressing the author.
JACKSON Well, what did you think?
Adrian smiles.
ADRIAN I'd say...
ADRIAN those astronauts of yours would be shitting themselves, if they knew all their relatives are now stuck in the South Pole.
Suddenly a horn sounds and the sealed deck doors let off a burst of pressurised air.
A murmur goes through the crowd.
Everyone is silent as the huge deck doors slowly begin to roll back and light streams in.
The Pang family try to see over people's heads, even Anheuser looks hopeful.
Jackson pulls his family close as the first rays of daylight hit their faces.
Hatches unseal all around the ship.
Sun streams through the clouds.
Everywhere people emerge outside, into the light of day.
A majestic moment.
They all stare in awe at the waters receding against the ice- covered mountain peaks.
Caesar lets out a YELP of joy.
Almost as soon as the doors have opened, the ship's HELICOPTERS take off, flying towards a stunning site--
The `Freedom of the Seas' is perched on a mountain peak, surrounded by calm waters.
Behind it, they see the most beautiful rainbow.
This is the new world.
And again we hear Mozart's Adagio...
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
