BLUE VALENTINE
Written by
Derek Cianfrance, Cami Delavigne & Joey Curtis
A 5-year old girl wearing pajamas wanders alone down the street.
Me-gan!
FRANKIE crawls through a dog door.
She walks into the living room where the TV is on loud.
DEAN PERIERA, 30 years old, hefty, sleeps in a lazyboy.
Daddydaddydaddy.
Frankie uses the footrest to crawl up onto her dad's belly.
FRANKIE (CONT'D) Wake up Daddy.
What time is it baby?
She sniffles.
He notices.
The back door opens and Dean carries Frankie to the yard.
The first yellow rays of sunlight hit their faces.
He looks over the lawn, an empty bowl, water tin and a doghouse posting the name MEGAN.
He peeks inside the doghouse.
There's no one home.
Dean moves to the fence.
The gate is open.
Dean carries Frankie to the front yard.
They look around.
FRANKIE When's she going to get back?
DEAN She probably just went out for a run.
DEAN She'll be back soon because she's going to get thirsty.
FRANKIE She's going to be thirsty?
Blue Valentine Official Green Script as of 6/9/09 2.
DEAN You know what we should do?
DEAN We should leave her bowl full of water and her dish full of food.
DEAN Because she's gotta get hungry and thirsty sometime.
DEAN You know?
Dean's optimism is infectious.
Frankie nods slowly.
DEAN (CONT'D) Like me.
DEAN (CONT'D) I'm hungry.
DEAN (CONT'D) I'm so hungry I could eat your toes.
Dean pretends to gnaw at Frankie's toes.
Breaks her sadness.
CINDY PERIERA, 28, sleeps in bed.
Sunlight spills through translucent yellow curtains into a small master bedroom.
Dean sets Frankie down on the bed, motions to her to be silent.
He sniffs the air.
She follows.
They eye each other and pounce.
Cindy wakes up with a gasp.
CINDY I'm sleeping!
DEAN We're hungry!
DEAN We're going to eat you.
They pin her arms above her head and 'furber' her armpit.
DEAN (CONT'D) Don't laugh.
DEAN (CONT'D) Come on, don't laugh!
Cindy doesn't laugh, she screams.
Cindy, nursing a weight-loss drink, scans through digital photos on the computer.
We see - family on vacation, Frankie's first day of school, Frankie and a black and white Border Collie mutt - Megan.
Cindy exports the picture when...
A tea kettle whistle blows.
Dean and Frankie sit at the table.
He plays a song for Frankie on a ukulele.
Cindy gets up, turns off the kettle.
DEAN What happened to the flute?
Blue Valentine Official Green Script as of 6/9/09 3.
CINDY C'mon, eat, you can't be late today.
Frankie takes a tiny bite and makes a sour face.
FRANKIE I don't like it...
Cindy turns on the faucet over a pile of dishes, returns to the computer to e-mail herself the missing dog flyer.
DEAN Here...
DEAN we can make it taste better.
Dean spoons the raisins out of her bowl onto the table.
DEAN (CONT'D) This is how a leopard eats.
He laps up his coffee like a cat.
She mimics.
Dean laughs.
CINDY Come on Frankie, use a spoon.
CINDY You know how to use a spoon.
FRANKIE Lepers don't use spoons.
DEAN (WHISPERS) Are you gonna listen to your mother?
DEAN (WHISPERS) I think you better.
Frankie reluctantly takes a tiny bite.
Her face sours and she lets the food fall out of her mouth and back in the bowl.
Cindy returns to the dishes.
DEAN (CONT'D) How old are you?
FRANKIE Five.
DEAN Okay, eat five bites.
Dean gets up, goes to Cindy at the sink.
DEAN (CONT'D) We gotta get a dishwasher...
Blue Valentine Official Green Script as of 6/9/09 4.
DEAN (CONT'D) I'll do it.
DEAN (CONT'D) Come on let me do it.
She drops the sponge, dries her hands.
CINDY Frankie!
CINDY We're leaving in 15.
CINDY Eat!
Frankie ignores her.
CINDY (CONT'D) Alright...
CINDY (CONT'D) Dean watches, shakes his head.
CINDY (CONT'D) He sees the computer on, Cindy's e-mail is still open.
CINDY (CONT'D) He shuts off the running water.
He scans through messages from a bunch of names of people Dean doesn't know.
He sweats, clicks open a return message from a real estate company - apartment now available.
CINDY Look up for mommy...
CINDY come on Frankie!
CINDY We're gonna be late...
CINDY look up.
CINDY CINDY (softens) (cont'd) Don't blink...
CINDY leopards don't blink...
Cindy backs their minivan out of the garage.
Frankie is strapped in her carseat.
Dean comes up to the window, knocks.
Cindy brakes.
Dean hands Frankie her backpack.
DEAN (to Frankie) You be good today for Miss Alex, okay?
Frankie, dressed like a little leopard, nods.
DEAN (to Frankie) (cont'd) Love you.
FRANKIE I love you.
Blue Valentine Official Green Script as of 6/9/09 5.
DEAN (to Cindy) Love you.
He kisses her on the corner of her mouth.
A hesitation.
CINDY ...Love you.
Dean pulls his head out of the window.
DEAN Put your seat belt on.
She starts to back up.
DEAN (CONT'D) C'mon.
DEAN (CONT'D) What's the big deal?
Cindy does as she's told, looks over her shoulder, scrapes the curb.
DEAN (CONT'D) Watch...
DEAN (CONT'D) Dean stands there in his driveway, muttering to himself.
DEAN (CONT'D) He watches the car disappear down the street.
Another car, headed the opposite direction, barrels down the road, past the Periera home.
DEAN (CONT'D) Slow that piece of shit down!
Cindy clicks the "print" button on a computer, moves to the printer.
It spits out a "Missing Dog" flyer.
DR.
SAM FEINBERG - handsome, well-groomed, unshakable confidence - appears at the door, with coffee.
FEINBERG There you are.
Cindy places the flyers in her folder in a rush.
CINDY Sorry...I'm almost done.
Blue Valentine Official Green Script as of 6/9/09 5A.
FEINBERG You got a second?
FEINBERG Did you get a chance to talk it over with your family yet?
CINDY Yeah...
CINDY I'm going to.
Blue Valentine Official Green Script as of 6/9/09 6.
FEINBERG I don't have to tell you, it's a huge opportunity...
CINDY I know I know.
CINDY I should know for sure by Monday.
FEINBERG All right, Monday's our day.
FEINBERG I want the A team up there with me.
FEINBERG Talk it over.
Feinberg walks away down the hallway.
CINDY I will.
Dean drives with a beer in a koozie and a cigarette.
He has a coughing fit, rolls down his window and spits.
CHARLEY - late 30s, hefty, African American - sits in the passenger seat.
He pops the top to a Styrofoam coffee cup.
They talk about sex, women and broken fantasies.
But Dean's attention is on the side of the road, scanning the neighborhood for Megan.
He whistles sharp and loud.
Cheer up man.
God wants you to be happy.
DEAN God's a woman and she's pissed off at me.
An ultrasound monitor, the abstracted image of a 20-week fetus.
Cindy watches Feinberg perform an ultrasound.
DR.
FEINBERG (to Cindy) Do you want to take over from here?
Cindy places her hand on the sensor.
Feinberg places his hand over hers.
They gently glide it over the abdomen.
Blue Valentine Official Green Script as of 6/9/09 7.
DR.
FEINBERG (cont'd) Easy.
Feinberg releases Cindy's hand and removes his latex gloves.
DR.
FEINBERG (cont'd) Very good, Cindy.
You're in good hands.
Cindy is one of our favorites.
Cindy blushes.
She is transfixed on the monitor.
CINDY Do you want to know the sex?
Dean smokes, works in the soon to be living room.
He paints a picture on the wall before covering it up with the roller.
She drives through a drive through and orders fast food.
Cindy drives, fast food wrapper in hand, sees something out the window.
She slows down, waits for opposing traffic to pass, then pulls a wide u-turn.
She rises up out of her seat to look at something.
CINDY Oh no...
CINDY ELLIPSE: A blanket covers a dead Border Collie mutt in the gutter.
CINDY Cindy puts Megan's body into the back of her van.
FOURTH OF JULY music recital.
The Pre-K classes are lined up on small bleachers.
Led by their teacher, the kids sing "I'm A Yankee Doodle Boy."
Frankie, steps out of her line of pre-kindergarteners to see if her parents are in the bleachers.
She spots her father, jumps a little, and wonders if he can see her.
Blue Valentine Official Green Script as of 6/9/09 7A.
Dean sits alone, picks paint off his hands.
He does not fully watch the children - he watches the door for Cindy to enter.
He wonders where she is - every possible scenario passes through his mind.
looks at the clock - 3:35.
Cindy arrives with haste, purse open, holding a big set of keys in her right hand and a water bottle in her left.
She props her sunglasses on her head, looks around for Frankie.
She waves to her, but Frankie doesn't see her.
Dean spots Cindy by the base of the bleachers - relaxes.
He picks up his jacket, puts it on his lap, making room for her.
She looks around for Dean, spots him near the top of the bleachers.
Little waves.
She climbs the crowded bleachers, stopping to talk with parents along the way.
She comes up next to Dean, takes her purse off.
They say "hi" but neither one makes eye contact.
Dean takes the water bottle from her.
Blue Valentine Official Green Script as of 6/9/09 8.
DEAN Didn't think you were gonna make it.
CINDY Did I miss her?
DEAN Almost.
DEAN Her class is coming up.
Dean kisses her cheek.
Cindy settles, arranges her things.
DEAN (CONT'D) You have a good day?
CINDY It was alright...
CINDY Busy.
DEAN Anything good happen?
Cindy shakes her head "no."
She drops her keys into her purse, but they miss the target and she fumbles after them.
DEAN (CONT'D) Is something wrong?
Cindy shakes her head.
Takes the water from Dean.
He stares at her.
She concentrates on closing the clasp on her purse.
DEAN (CONT'D) Why don't you tell me?
She doesn't want to start crying.
Dean gets visibly frustrated.
He's sick of prying everything out of her.
DEAN (CONT'D) Why do you gotta make me beg?
DEAN (CONT'D) I know there's something wrong.
DEAN (CONT'D) It's gonna come out eventually.
DEAN (CONT'D) Just tell me.
The song ends.
A patter of applause.
The teacher introduces the next song "THE BATTLE HYMN OF THE REPUBLIC".
CINDY I found Megan.
DEAN That's great, where?
Blue Valentine Official Green Script as of 6/9/09 8A.
DEAN (CONT'D) Where?
CINDY Over on Urbandale...
CINDY near Spur.
DEAN I told you you gotta close that fucking gate.
Cindy wipes tears.
She has to look up and blink to keep them from rolling down her cheek.
Dean puts his arm around her, holds her close.
She tries to pull away.
He won't let her.
DEAN (CONT'D) I'm sorry.
DEAN (CONT'D) It's not your fault.
Blue Valentine Official Green Script as of 6/9/09 9.
Frankie sees her Mother and Father huddled together.
She sings louder.
Cindy sits in her car, checking her eyes in the rear view mirror.
They are puffy.
Frankie runs full speed into Dean's arms.
He picks her up and walks her to Cindy's car.
DEAN You were great.
FRANKIE Did you find Megan?
DEAN No.
DEAN But...
DEAN I was thinking...
DEAN Maybe she got a job or something...
DEAN You know?
DEAN So she could make some money and buy some food.
DEAN Or maybe she moved out to Hollywood to become a movie dog!
Frankie nods.
Dean gets her to the car.
Straps her in.
DEAN (CONT'D) I was thinking...you should have some fun tonight1 Don't you think?
FRANKIE Yeah!
Cindy listens in the front seat.
She doesn't approve.
The door opens to a grandpa in shorts and a bathrobe wearing navy scuba gear, JERRY HELLER - early 70's.
He has a tube under his nose attached to an oxygen tank.
His porch and front yard are overloaded with Fourth of July decorations.
FRANKIE Pa!
Jerry growls at Frankie.
She screams, scared but delighted.
A yapping dog named SAMMY jumps on her.
Jerry nods at Dean who keeps his distance by the van.
CINDY Aren't you coming up?
Blue Valentine Official Green Script as of 6/9/09 9A.
CINDY (CONT'D) He's an old man.
DEAN What?
DEAN I can't smoke around his oxygen.
Cindy gives Dean a slow look of contempt, grabs the backpack and walks toward the house.
Jerry stands over the hose spigot with Frankie at his side.
JERRY ...Want me to show you a magic trick?
JERRY Here's how you turn the grass green.
JERRY You can teach it to your dad.
The sprinkler jets on.
Cindy comes up and kisses her dad on the cheek.
She straightens Frankie's ears.
CINDY Go say goodbye to Daddy.
CINDY You're not going to see him until tomorrow.
Blue Valentine Official Green Script as of 6/9/09 10.
JERRY Wait...!
JERRY OK...one, two, three GO!
Frankie runs to Dean, dodging the water stream.
She hugs his leg.
He picks her up.
DEAN Hey leopard.
DEAN You be good now.
DEAN You remember what to do when Pa snores?
FRANKIE Cover his mouth and hold his nose.
DEAN That's my girl.
DEAN Gimme a squeezer.
Dean hugs her and she squeezes back as hard as her arms allow.
Dean plays as if his neck was being pinched off.
He sets her on the ground running back to the porch.
She gets caught in the diameter of the sprinkler spray.
She screams as the water chases her.
JERRY It got you!
JERRY Go right!
JERRY OTHER RIGHT!
Dean and Cindy both laugh.
Their eyes meet for the first time in days, maybe weeks.
They exchange a brief smile, filled with mutual love, pride and respect - connected by their little girl.
Frankie stands in front of Cindy, water drips from her bangs.
CINDY Come on silly.
CINDY Let's go in and get dry.
FRANKIE I don't wanna take off my costume!
CINDY You don't have to.
CINDY Let's just go in.
CINDY Dean smokes and watches...
CINDY Cindy hold the screen open with her foot and maneuver father, tank and child inside.
CINDY The screen door closes.
CINDY Sammy barks at Dean through the screen door.
CINDY He tugs his smoke, memories flood.
CINDY He drifts...
The sound of barking.
A YOUNGER DEAN, 24, walks 10 dogs.
Blue Valentine Official Green Script as of 6/9/09 11.
Dean comes inside from the cold.
He tries to walk in quietly - not disturbing Jake who's watching TV in the back bedroom.
He goes to say "hi" but decides he'd rather not disturb him.
Dean sits on the couch which he uses as a bed.
He pulls his travelling bag from underneath the coffee table, digs around for a long sock where he keeps his money.
He stuffs his day's pay ($45), in the sock with the rest of his $ (about $100).
In the kitchen, he opens the fridge.
There is a pie tin with one last slice of pumpkin pie.
Walks to Jake's room.
Stands in the doorway.
Jake doesn't acknowledge him.
DEAN Hey man...
DEAN Can I have a slice of that pie?
A dog poops on the sidewalk.
Dean gets his little bag ready.
Sees - a light post with flyers taped to it.
Dean reads - MEN WANTED-$22/hr.
He tears it down.
Dean waits for the bus to come.
Dean enters, hair combed, still wet, with fresh teeth marks.
JO - 36, receptionist sits beyond a scratched window.
Dean pulls out the folded flyer and asks if they have any work.
JO You're gonna have to speak with Mr.
JO Saned, honey.
JO Wait just a minute, okay.
Dean sits on a chair, smooths his hair, smells his clothes.
Saned - huge hands, the boss - leads Dean through a large, open garage, lined with many sizes of moving trucks.
SANED Normally we are busiest at the beginning of the month.
SANED You break your back for two weeks, you get 2 weeks to rest.
SANED That's normal.
SANED Days start early.
Blue Valentine Official Green Script as of 6/9/09 12.
You'll work on a crew of 4.
The rate for 4 men is $122/hour.$40 goes to the truck.
You split the rest.
Plus tips.
Policy on tardiness; you work for the day you don't get paid.
You're late two times; don't bother coming back.
Any questions, talk to Curtis.
He's your supervisor.
WORKERS eye Dean.
He introduces himself.
Shake hands.
Dean rides in the back of a 20 foot truck.
The wind is cold.
He warms his hands with his breath.
Dean lifts two large boxes and moves toward the stairs.
CURTIS Whoa whoa.
CURTIS You gonna break your neck homey.
CURTIS Look down.
Dean does.
All he sees is brown box.
CURTIS (CONT'D) Can't see your feet.
CURTIS (CONT'D) If you can't see your feet, how you gonna know where the step is?
CURTIS (CONT'D) You goin' bust your ass.
Curtis takes the boxes from Dean and demonstrates.
CURTIS (CONT'D) Turn around.
Curtis hefts the boxes on Dean's back.
He pulls his arms around the back to hold onto them in an awkward position.
CURTIS (CONT'D) You gotta be a mule.
CURTIS (CONT'D) Always carry on your back.
CURTIS (CONT'D) Give `er a try.
CURTIS (CONT'D) He makes it to the truck where Saned waits to help him get the boxes in.
CURTIS (CONT'D) Dean can't quite manage a 30-pound, behind the back hand-off.
CURTIS (CONT'D) He ends up spilling up the boxes and their contents all over the sidewalk.
CURTIS (CONT'D) Saned gets pissed.
CURTIS (CONT'D) Dean gets down on his hands and knees and packs up the boxes - quickly.
Blue Valentine Official Green Script as of 6/9/09 13.
- Dean puts $300 in an envelope, seals it, and writes "THANKS PAL."
He slides the envelope under Jake's door.
- He lays on the couch, wrapped up in a white sheet, smoking a cigarette.
Tries to stretch his back.
LUNCH-TIME.
Dean, Curtis sit in the bed of the truck, legs dangling.
They eat hamburgers and talk about girls.
Dean showers, tries to stretch his aching back.
A fifty something MAN helps an ELDERLY MAN navigate his walker down the stairs of his neglected Brownstone.
Dean holds a ream of unfolded cardboard boxes and can't help but stare.
Curtis slaps him on the back.
CURTIS Gonna happen to you someday too.
INSIDE.
Dank, dark home.
0 upkeep.
The smell makes Dean hold back a gag.
Curtis climbs the stairs to the 2nd floor.
Blue Valentine Official Green Script as of 6/9/09 14.
CURTIS I don't think that old man's been up here in 10 years.
Saned elbows in with rolls of tape and contractor bags.
Box up everything on the first floor.
Toss everything else.
- Dean finds jars of yellow liquid everywhere.
"What's this?" He opens a jars and is overwhelmed by the stench of urine.
DEAN It's fucking pee!
- He runs to the toilet and pukes in to a shit stained porcelain bowl.
Saned berates him for wasting time.
DEAN (CONT'D) How could you live like this?
- He ties a bandana around his nose.
Gets back to packing.
- boxes full of the old man's life (religious items, framed pictures, old cameras and reams of polaroids).
- Boxes are packed, taped and stacked.
Bags of garbage dump into a 20' rented dumpster out in the street.
- Dean and Curtis heft an old couch into the dumpster.
- Barren home reveals a sagging floor.
Ghostly impressions on walls where pictures used to hang.
- The truck takes off, leaving a full dumpster behind.
- Dean and crew cut out of the city.
It's the first time Dean has seen nature in the longest.
Breathes deep.
- The crew carries boxes down a hallway to a single room.
A sign on the door reads, "Welcome home Walter!!!"
CURTIS How we s'posed to fit all this in here?
Blue Valentine Official Green Script as of 6/9/09 15.
- Wipes clean old pictures and knickknacks using toilet paper,.
- Saned carries in a box of food - cans of soup, etc.
SANED Last one.
SANED Lets get a move on.
SANED Gotta make it home for the game.
Dean holds up the man's wedding picture.
DEAN Look how handsome he was.
SANED What are you fucking queer?
Saned hands Dean a wad of bills.
Finish up, we gotta 2 hour drive back.
Saned walks down the hall, calling out to hurry up.
Dean sets the bills down on the dresser.
Continues to arrange the things.
He stares at a picture of old man and his wife.
ELLIPSE - A nurse wheels Walter down the hallway and introduces him to his new room.
DEAN Wait up.
DEAN We gotta do this right...
He takes the wheelchair from the nurse, wheels Walter out of the room, picks him out out of his wheelchair, and carries him back into the room across the threshold of his new home.
DEAN (CONT'D) You are gonna be the new stud in this place.
Dean sets him down in a recliner, then gives him a tour of his room - tells him which drawer his socks are in, where put the aftershave, etc.
Curtis pokes his head around the corner.
CURTIS Boss says we gotta go.
CURTIS We gotta go.
Dean cuts the tour short, wishes the old man luck and tells him he'll come visit him someday.
He backs out of the doorway, grabs his money off the dresser, and says goodbye.
Dean turns and is frozen in his tracks.
Something or someone makes his expression change to that of wonder, eyes fill with love...
he puts the money in his pocket.
Blue Valentine Official Green Script as of 6/9/09 15A.
Cindy pulls into the driveway behind Dean's van.
He walks around her mini van and directs her to open the back hatch.
She presses the button from inside.
Hatch opens.
She gathers the stack of missing dog flyers in the seat next to her.
Dean buries Megan by the fence.
He places a stone on the mound as a marker.
He stands over it, smoking a cigarette.
Cindy looks on from the porch, arms hugging her body.
Dean walks to her and wraps his arms around her.
Her arms fall and move up to touch his side.
CINDY What are we going to tell her?
DEAN We'll tell her Monday.
DEAN After the weekend.
DEAN Let's not ruin her Holiday.
Dean turns Cindy around, closes his eyes, and hugs her.
CINDY She would have wanted to say goodbye.
CINDY Blue Valentine Official Green Script as of 6/9/09 16.
- Cindy washes dishes, straightens up the house.
OUTSIDE - Dean sits in Frankie's little rocking chair, smoking a cigarette.
He looks out over his lawn.
- Picks up frozen dog poop with a little shovel, rinses out Megan's bowls with the hose.
- He watches Cindy inside, cleaning.
He looks at his house.
Remembers something.
He comes in through the sliding glass door and steps over Cindy who is on the floor picking up Frankie's Hotwheels.
He yanks open a junk drawer and pulls out items.
DEAN You remember where we put...
Cindy stops and watches him.
He holds up a gift certificate in an old anniversary card.
DEAN (CONT'D) Here!
DEAN (CONT'D) Let's get the fuck out of here.
DEAN (CONT'D) DEAN (on phone) (cont'd) Hello, I want to see if I can reserve a room for the night...
DEAN (CONT'D) tonight.
DEAN (CONT'D) I have a gift certificate but I don't know if it's still good.
DEAN (CONT'D) Can I give you a number?
CINDY What are you doing?
DEAN Taking us away.
DEAN We gotta get outta this house.
DEAN It's still good?
DEAN Good...
DEAN Well, what rooms do you got?...Hold on a minute...
Dean lowers the receiver to his neck.
DEAN (CONT'D) What room do you want?
DEAN (CONT'D) The North Pole, the Moon Room or Cupid's cave.
DEAN (CONT'D) Which one?
Blue Valentine Official Green Script as of 6/9/09 17.
DEAN (CONT'D) I don't want to hear any excuses.
DEAN (CONT'D) We're going.
DEAN (CONT'D) We deserve it.
DEAN (CONT'D) One night.
DEAN (CONT'D) Because we belong to each other.
DEAN (CONT'D) Pick a room.
CINDY You're crazy.
DEAN You're not going to decide?
DEAN I'll decide.
DEAN That's how decisions get made.
Dean gets a shit-eating grin.
DEAN (CONT'D) Come on let's go get drunk.
He returns to the phone.
DEAN (CONT'D) Give us the moon room.
DEAN (CONT'D) Periera.
DEAN (CONT'D) P-E-R-I- E-R-A...
DEAN (CONT'D) 2...
DEAN (CONT'D) Great...
Dean hangs up.
DEAN (CONT'D) Pack our bags.
DEAN (CONT'D) We're going to the moon!
They argue about who's gonna go in.
- Cindy jerks out a grocery cart, pushes it, scans the aisles of the massive liquor store.
- Tucks two large bottles of champagne under her arm.
- she tries on different pairs of sunglasses at the display.
She assumes the character that each pair suggests.
She is a tough guy cop when...
BOBBY Is that Cindy Heller?
Cindy turns and sees BOBBY ONTARIO, her college sweetheart.
She lifts the glasses on her head, blood rushes to her face.
CINDY Bobby Ontario?
Dean fills his tank.
Blue Valentine Official Green Script as of 6/9/09 18.
Cindy pushes her cart down the aisle along side Bobby, 30 years old, fit.
TAYLOR, a small toddler sits in his cart wearing overalls and a backward baseball cap like his daddy.
BOBBY ...So, you been faithful to him?
CINDY That's a strange question to ask someone you haven't seen in forever.
BOBBY I'm a strange person.
Cindy laughs.
BOBBY (CONT'D) No seriously.
CINDY Yes.
BOBBY Yes you have or yes you haven't?
CINDY Yes...I haven't.
CINDY I mean I have...I have been...Why are you looking at me like that?
BOBBY I'm not looking at you like anything.
CINDY Oh OK.
BOBBY It's hard to be faithful.
BOBBY I don't know if monogamy is possible, especially if you're a man...
CINDY Who's this?
BOBBY This is Taylor.
BOBBY He's two.
BOBBY Got a little girl at home.
BOBBY Irene.
CINDY Wow...
Blue Valentine Official Green Script as of 6/9/09 19.
BOBBY Kids are great.
BOBBY They pick up on things so fast.
BOBBY Like watch...
BOBBY Hey Spence, give me five...
BOBBY Give me five, buddy.
Drooling, and with a toothless smile, Taylor gives his daddy five.
Bobby beams.
BOBBY (CONT'D) Give Cindy five.
Taylor holds up his hand limply so that Cindy has to give him an awkward five.
Bobby laughs.
They reach the register.
BOBBY (CONT'D) To see yourself in your kid's face...
BOBBY (CONT'D) I never experienced anything like that.
CINDY I know...
There is an uncomfortable silence between them.
Cindy starts to unload her purchases.
CINDY (CONT'D) I'm really happy for you.
BOBBY How's your kid?
CINDY She's good.
Pause.
They speak at the same time.
They stop.
Cindy concedes.
CINDY (CONT'D) You go...
BOBBY No, you go...
CINDY Oh...
CINDY I was going to say, you ask her what kind of hair she's got and she says, a bob.
CINDY It's pretty funny.
Blue Valentine Official Green Script as of 6/9/09 20.
Cindy smiles at the ground.
Bobby eyes her purchases - a bottle of vodka, cheap champagne, mixers, snacks.
BOBBY What's her name?
CINDY Frankie.
Fumbling, she starts bagging her groceries.
CHECKER That's $58.42.
Cindy hands the CHECKER a fifty.
The Checker holds it out.
CINDY Oh...I'm sorry.
Cindy searches her wallet, goes into her change purse.
CINDY (CONT'D) How much was the vodka?
The Checker looks at the receipt.
CINDY Can I put that back?
CINDY I'm sorry...
Bobby holds out a twenty dollar bill.
BOBBY I got it.
CINDY Nothankyou.
Just take it off please.
Bobby drops the bill on the scanner.
BOBBY You can get me back.
Cindy pushes the cart hurriedly, stolen shades on her head.
Blue Valentine Official Green Script as of 6/9/09 21.
Dean blows on a hot cup of coffee.
Cindy moves fast, loads in the bags next to their luggage, slams the hatch closed and snatches the keys from Dean's hands.
CINDY Let's go.
DEAN You're drivin'?
Cindy hops in the driver's seat.
Dean rides on the end of the buggy and crashes it into the buggy corral.
She fires up the engine and honks.
He throws his hands up.
Cindy drives the car along a windy, mountain road.
Dean keeps a lidless cup of coffee from spilling.
DEAN Alright, lead foot.
DEAN It's not a race.
Cindy is zoned into the road.
She turns off the radio.
CINDY Isn't it funny how you can be driving for 20 minutes and it feels like you've only been driving for 20 seconds.
CINDY The time just gets swallowed up somewhere...
Dean places his hand on Cindy's hand that rests on the car seat.
A small squeeze.
She squeezes back.
Dean looks at her with tenderness.
Her eyes are on the road.
She lifts her hand to the wheel.
Dean reaches for the radio.
DEAN Do you mind if I turn this back on?
CINDY I was kind of enjoying the silence.
DEAN Let's just see if there's something on...
He scans through the low stations.
DEAN (CONT'D) Anything?
DEAN (CONT'D) Fuck it.
Blue Valentine Official Green Script as of 6/9/09 22.
DEAN (CONT'D) That's better.
DEAN (CONT'D) You're right.
DEAN (CONT'D) It never gets to be just quiet.
DEAN (CONT'D) You know?
Cindy nods.
Dean rolls down his window, spits his gum as far as he can.
He rolls it back up.
DEAN (CONT'D) What are you thinking about?
Dean looks at Cindy, waiting for her to respond.
DEAN (CONT'D) Did you get everything?
CINDY Think so.
DEAN Where d'you get these?
Dean reaches for the glasses on top of Cindy's head.
She feels the dangling tag - "woops."
She tears off the tag and tosses the glasses on the dashboard.
DEAN (CONT'D) Try em' on.
Cindy shakes her head "no."
Dean puts them on his face.
He poses for Cindy.
She grabs the glasses and puts them on.
She looks at Dean.
He holds in a chuckle.
DEAN (CONT'D) You look like your mom.
Cindy takes them off.
Back on the dash.
DEAN (CONT'D) You get any snacks?
CINDY There should be some fig newtons back there.
Dean unbuckles his seatbelt, crawls to the back of the van digs through the bags.
Cindy can't see out of the rear-view.
DEAN Which bag?
CINDY You have to look.
Blue Valentine Official Green Script as of 6/9/09 23.
Cindy enjoys a moment alone, straightens her back, crosses the dotted yellow lines and passes a car, then relaxes.
Dean crawls back up to the front seat.
They both eat a cookie.
DEAN Mmm.
DEAN These are good.
He offers her another one.
She shakes her head.
CINDY I have to pee.
The car stops on the shoulder of the two lane highway.
Cindy gets out of the car.
DEAN You can't wait?
DEAN We're almost there.
CINDY I gotta go.
Cindy jogs across the road.
Dean sees traffic coming.
DEAN Goddamnit Cindy!!
DEAN Pay attention!!!
On the side of the road, she stares into the woods.
Cars pass behind her, headlights flood the night.
She descends into the thicket until the sound of the highway is faint.
Wind through the leaves.
She drops her pants and pees.
Something rustles and she looks into the woods.
CINDY ...Hello?
She stands up and zips up her pants.
Eyes search the shadows.
...Cindy is ALONE.
A leaf falls to earth.
She stares at it and her mind drifts back to...
A YOUNGER CINDY - 22, smart - wheels herself down suburban sidewalks.
Faces of passing people look at her with pity - what a shame that such a pretty girl be in a wheelchair.
Cindy wheels herself across the campus quad.
Students hurry by clutching schoolbooks.
Blue Valentine Official Green Script as of 6/9/09 24.
Wrestling practice.
Bobby - 22, svelte - gets into the defensive position.
TROY LEANER, his buddy, gets on top of him in the offensive position.
Bobby looks up, sees Cindy by the door attempting to pop wheelies in her wheelchair.
Whistle blows!
Bobby escapes the position and wraps Troy up in a double grapevine.
Quickly pins him, stands up, takes off his ear guards, bumps fists.
He walks over to Cindy.
BOBBY What are you doing?
CINDY Research.
BOBBY You're supposed to be a quadriplegic?
CINDY Quads can't use their arms.
CINDY I'm a paraplegic.
BOBBY Don't I give you enough attention?
He presses himself into her and mauls her with a wet kiss.
BOBBY (CONT'D) Wonder what people would think if they saw me making out with a paraplegic?
BOBBY (CONT'D) BOBBY (close (cont'd) Can you come over?
CINDY I can't.
CINDY I have to go get gramma.
Cindy rolls the wheelchair back.
BOBBY Gimme a sec.
Bobby tries to hide the erection trapped in his wrestling singlet.
Blue Valentine Official Green Script as of 6/9/09 25.
The front door opens and Cindy pushes GRAMMA FRANCIS - 80's, Alzheimer's - into the middle class home.
NAPOLEON - an ill- trained dog - greets them with jumps and licks
CINDY Get down Napoleon!
CINDY Get down!
GLENDA HELLER - 50's, desperate - peeks her head out of the kitchen.
She holds a coffee mug filled with gin on the rocks.
GLENDA Ope - I thought you were your Dad.
CINDY Just us.
Cindy kisses her mom on the cheek, can smell the alcohol.
GLENDA How was the beauty shop?
The front door opens and COLONEL JERRY - 65, wound tighter than a navy knot - enters.
Glenda, rushes to greet him.
JERRY Get that fucking dog out of the kitchen!
Come lord Jesus, be our guest, and let Thy gifts to us be blessed.
Amen.
Glenda, Jerry, Gramma Francis and Cindy sit around a dining room table.
Glenda slices a knife through a greenish meatloaf.
She serves a watery slice to Gramma.
GRAMMA Thank you.
Glenda averts her eyes.
She cuts another slice.
Cindy offers Glenda her plate.
The meat breaks apart and half of it lands on the table cloth.
A brownish-green oil.
CINDY It's OK mom.
Blue Valentine Official Green Script as of 6/9/09 26.
Cindy picks up the fallen particles with her fork.
Jerry's eyes burn into Glenda.
She won't look at him.
GLENDA Can I have your plate Dad?
GLENDA Suddenly, Jerry pounds his fist into the mound of meatloaf, obliterating it.
GLENDA Particles of ground meat fly everywhere.
GLENDA Glenda won't look up, her shoulders tremble.
GLENDA Jerry raises his steaming fist.
GLENDA Bits of ground beef stick to his knuckles.
JERRY What'd you do to meatloaf?
JERRY Huh?!
GLENDA They had it ready-made in the deli.
GLENDA I...
GLENDA thought it looked good.
JERRY Are you kidding me?
JERRY How long does it take to make a meatloaf?
JERRY Five minutes?
JERRY You mean to tell me that you didn't have five minutes to make a meatloaf?
JERRY I been up since six this morning busting my fucking ass and you don't have five minutes to make a meatloaf?
GLENDA I thought it would be nice.
JERRY Nice?
GLENDA ...for a change...
JERRY Well, what gave you the idea that any of us needed a change?
JERRY Did you ask for a change?
JERRY Cindy?
JERRY She doesn't ask for anything...
JERRY She doesn't talk.
JERRY You didn't ask for a change, did you mom?...She can't hear!
JERRY And I don't remember asking for a change.
JERRY So, it was you, wasn't it?
JERRY You wanted a change.
JERRY I work all day so you can sit on your fat ass, thinkin' about yourself.
JERRY How you'd like a change.
Blue Valentine Official Green Script as of 6/9/09 27.
GLENDA Sorry.
JERRY Sorry?
JERRY What good is sorry now?
GLENDA Do you want me to make you some eggs?
JERRY I want you to enjoy your fucking dinner.
He storms out of the dining room.
Glenda, Cindy and Gramma sit in silence.
Cindy takes a bite.
CINDY It's not bad.
GLENDA Oh bullshit.
Glenda retreats into the kitchen.
Gramma and Cindy eat.
PROFESSOR ...When I was a young physician, I used to leave the hospital everyday in tears.
Gramma sits in a chair in the bathtub.
Cindy squeezes a sudsy washcloth over her body.
Uses a plastic cup to rinse.
PROFESSOR Just broken down from seeing the suffering of my patients.
Don't get my hair.
Fully clothed, Glenda is passed out on the bed.
Framed family portraits sit on the mantle.
PROFESSOR ...As a result, I began to suffer.
PROFESSOR Not just in my work but emotionally and physically...spiritually...
PROFESSOR Blue Valentine Official Green Script as of 6/9/09 28.
Shirt off, hand stuffed into his underwear - Jerry holds a remote and flicks through channels.
Nothing holds.
PROFESSOR ...There's a choice we all have to make in the medical profession - whether to be sympathetic or empathetic with our patients...
SOUND of TYPING.
An open medical schoolbook on the PSYCHOLOGY OF PATIENTS sits on a well-organized desk.
Cindy stares at the screen, hits "enter."
PROFESSOR ...Imagine your patients as being in a hole.
PROFESSOR To be sympathetic means you throw them a rope to help pull them out...
PROFESSOR PROFESSOR (O.S.)
PROFESSOR (cont'd) ...To be empathetic means you jump in the hole with them...
Cindy sits near the back of the bus.
She hugs her backpack.
PROFESSOR ...Now you're both stuck.
The PROFESSOR stands in front of the class.
There are grids and diagrams illustrating DOCTOR-patient relationships.
It is a big class - students, sitting in steep rows.
I want you to think about that when we go into the next section.
Please pass in your reports.
Cindy passes her paper down.
Bobby, the TA, collects the reports.
Cindy can feel him staring at her as she packs her backpack.
Blue Valentine Official Green Script as of 6/9/09 29.
She tries not to give him the satisfaction, but she can't help it - his cockiness is magnetic.
She looks, notices something new - his belt buckle has his name on it.
A gold necklace dangles from Cindy's neck.
Her arms secure her weight on the bed.
Bobby stands behind her.
His hands caress her back as he looks down at himself inside of her.
He closes his eyes tight, trying to control himself.
But the ecstasy is too much - he comes inside of her, moaning, and lets his body weight smother her onto the bed.
Shit.
She stops moving, feels him shrinking inside of her.
Shit!
BOBBY I couldn't help it.
She gets out from underneath him.
BOBBY (CONT'D) I couldn't help it...
BOBBY (CONT'D) You felt too good.
BOBBY (CONT'D) BOBBY (calls out) (cont'd) Don't trip.
BOBBY (CONT'D) It'll be OK...OK?
Bobby lies back, frustrated, and buttons his pants.
Cindy sits on the toilet, pees; hoping gravity will pull Bobby out of her.
She runs her hand under the faucet and scrubs her crotch, hoping that this will wash him out of her.
Cindy comes out, shirt stretched over her waist.
Bobby sits up, asks her what's wrong?
She can't look.
BOBBY It's your fault.
BOBBY You felt too good.
Blue Valentine Official Green Script as of 6/9/09 30.
CINDY Give em!
Cindy presses her lips together.
She leaps at Bobby and squeezes his crotch and gets her underwear back.
Bobby's face turns vicious.
He snatches them back aggressively.
BOBBY Say you're sorry!
Cindy picks her pants up off the floor - pulls them on.
CINDY Take a deep whiff, you fucking douchebag!
She tears off his necklace, throws it at him, slams the door.
BOBBY I was just joking!
BOBBY God!
Cindy walks briskly, hoodie pulled low, pushing her Gramma in a wheelchair.
Gramma protects her hair from the breeze.
Cindy pushes her Gramma in.
Piles of moving boxes line the hallway.
ELLIPSE - Cindy sits down for dinner with Gramma and the other elderly residents.
Cindy notices a group of men moving boxes into the home.
- Cindy helps gramma with bedtime rituals.
- Cindy reads to Gramma...
but she keeps getting distracted by the commotion across the hall - movers carry boxes and furniture down the hallway.
One in particular, tall,
handsome, catches her eye.
It is Dean.
She cranes her head to see - him decorating the inside of the old man's room.
GRAMMA What is it?
Blue Valentine Official Green Script as of 6/9/09 30A.
CINDY It looks like you have a new neighbor.
Cindy returns to the book, but there is something about the mover that has captured her attention.
She can't stop watching him every time he passes her door.
GRAMMA Glenda...
GRAMMA I mean Cindy...
GRAMMA can I have a cigarette?
CINDY No, Gramma, you're in bed now.
CINDY It's bedtime.
CINDY Do you want me to keep reading?
Gramma nods.
Cindy turns the page, looks up, sees Dean lift the old man over the threshold and into the room.
GRAMMA Cindy.
GRAMMA Have you got a cigarette!
CINDY Okay, shhh.
CINDY But you gotta be quiet.
Cindy gets up and opens the window.
She turns on the fan, digs in Gramma's purse, gets a cigarette and a lighter.
Cindy walks to her gramma's door, sees Curtis walking away from the old man's room.
CURTIS Boss says we gotta go.
CURTIS We gotta go.
She starts closing the door, then sees Dean backing out of the old man's room.
He puts a roll of money in his pocket, turns to leave and sees Cindy watching him.
I didn't just steal that.
Cindy doesn't know what this guy is talking about.
DEAN (CONT'D) (cont'd) You think I just stole that money?
CINDY No.
DEAN You do.
DEAN No, you do.
DEAN I know that you do.
DEAN And the reason that I know that you do is - I have stolen money before...
DEAN a lot of it.
DEAN And I know what it feels like to have someone look at you like that...
Blue Valentine Official Green Script as of 6/9/09 30B.
CINDY Like what?
DEAN The way your lookin'.
DEAN Just so you know, I have a job where I make money.
DEAN Money that I can take girls out on dates with.
CINDY Are you trying to pick up on me?
DEAN Maybe...
SANED Pack it up Periera.
SANED Bus is leaving.
Dean looks toward the door, then back at Cindy.
He sees that he has kind of went to far with his rant.
DEAN Can I give you my number or something.
DEAN DEAN (CONT'D) (cont'd) I'm Dean.
DEAN Just call and you can ask for me.
DEAN I'll get it.
Cindy looks down at the card, at his name.
Then back up to him.
Dean run out, chasing after his ride.
He looking behind before he leaves.
Cindy watches him go out the door.
Blue Valentine Official Green Script as of 6/9/09 31.
Door opens revealing Dean and Cindy holding groceries and suitcases.
Dean flicks on the light, illuminating the Moon Room - a hotel room decorated like the lunar surface.
DEAN Wow.
DEAN Where are we?
He sets down the suitcases, transfixed by the room, a kid in a candy shop.
Cindy moves to the small kitchen that looks like a control room.
She makes herself a drink.
Dean walks into the bright BATHROOM, turns on the shower, a sparse tinkle of water.
DEAN (yells out) I could piss harder than this!
The dual mirrors multiply his reflection.
He looks at himself and removes his coffee-stained shirt.
A neglected body.
But something else distresses Dean.
A fallen hair on the T-shirt he holds.
He runs his hands through his hair, looks in horror at twelve fallen hairs in his palm.
He washes them down the drain and leans to the mirror, inspecting his hairline.
DEAN (CONT'D) Cynthia!
Cindy dials the telephone, drink in hand.
Shirtless, Dean walks out of the BATHROOM with his empty palms open.
DEAN Now watch.
He runs his hands through his hair then shows her his palms - three fallen hairs.
His magic trick.
DEAN (CONT'D) See.
DEAN (CONT'D) I tol' ya.
DEAN (CONT'D) It's falling out!
Cindy ignores Dean who is mesmerized.
DEAN (CONT'D) Oooooooooh shiiiiiiit!
Blue Valentine Official Green Script as of 6/9/09 32.
CINDY (into phone) Hi Dad.
We're here...
It's kind of crazy.
I don't know, should I feel bad?
Dean trots back into the BATHROOM.
He is screaming like a hyena.
CINDY (CONT'D) ...it's just Dean...
CINDY (CONT'D) he's losing his hair.
CINDY (CONT'D) What are you guys doing?
Dean tosses his suitcase onto the circular spaceship bed, watches the graceful way it rebounds.
He shoves the suitcase aside, falls backwards onto the bed.
He sighs with pleasure.
There is a box with a button next to the bed.
He presses it.
The bed rotates.
He looks up at his spinning reflection in the mirror above the bed.
CINDY Lemme talk to the little one.
Is that Francis?
Hey!?
Don't hang up until I talk to her!
CINDY Did Pa make you something to eat yet?
CINDY ...Frankie?
CINDY ...What'd you and Pa eat?
CINDY ...Was it cooked all the way through?
CINDY No pink in there?
CINDY ...
Dean walks up from behind, putting on a clean, white T-shirt.
He snaps his fingers at Cindy.
Cindy swipes his hand away with more force than necessary.
CINDY (CONT'D) Okay sweetheart, your daddy wants to talk to you.
CINDY (CONT'D) I love you...
CINDY (CONT'D) love you...
CINDY (CONT'D) Don't forget to brush your teeth tonight okay.
CINDY (CONT'D) Okay?
CINDY (CONT'D) Here's your dad.
Blue Valentine Official Green Script as of 6/9/09 33.
DEAN (disguised voice) Who's this?
...How do you know I'm your father?
A faint scream of joy is heard through the phone.
Steam accumulates on mirrors.
Cindy takes her clothes off, tests the temperature of the water and steps in the shower.
Dean paces, improvising a bedtime story.
It comes from the well of creativity in him.
Frankie loves to hear him talk.
And he loves to make her happy.
He finishes.
She is happy.
DEAN Are you ready to go to sleep now?
DEAN I'll call you first thing in the morning, OK?
He walks into the living room, stretching the phone cord, grabs the remote and turns on the television - animal doc.
Dean turns the channel.
Tennis.
DEAN (CONT'D) How much?
CLICK.
The news.
DEAN (CONT'D) ...Well, I love you more.
DEAN (CONT'D) Sleep tight.
Dean hangs up and returns to the living room.
He changes the station.
A porno.
He turns the volume down and watches.
He hears water running in the BATHROOM.
CLICK.
A show on space.
Dean cracks open the door to the steam-filled room.
Cindy lathers her hair with her eyes closed.
DEAN What are you doing?
CINDY What does it look like I'm doing?
DEAN Do you like the place?
Blue Valentine Official Green Script as of 6/9/09 34.
CINDY It's fine.
DEAN I'm gonna go order dinner now.
CINDY Fine!
DEAN Any special requests?
CINDY Close the door!
Dean closes the door, remains in the BATHROOM, watches his naked wife, removes his clothes.
Cindy does a double take.
CINDY (CONT'D) What are you doing?
Dean pulls back the shower curtain and steps in.
DEAN What does it look like I'm doing?
CINDY Dean.
The small shower presses them close.
Dean's smile infects her.
He leans over, they kiss.
Brushing lips at first.
Dean presses closer.
Cindy pulls back and pivots him around until the stream of water catches his body.
He leans his head back, the water pours over his hair and face.
He places his hands on Cindy's hips and pulls her close to him.
Cindy hands him a bar of soap.
He builds a gentle lather.
Cindy inches back, turns around.
Dean lathers her back, slow and languid.
DEAN I remember the first time I saw your back.
CINDY What do you remember?
DEAN Everything.
He lowers his hands from her back to her behind.
Cindy turns.
DEAN (CONT'D) I wasn't done.
Blue Valentine Official Green Script as of 6/9/09 35.
He washes her shoulders and neck.
His hands sculpt her body and move to her breasts.
No longer washing her, but molding her.
Cindy looks up.
His hands move to her belly.
He kneels down.
Cindy reaches down and lifts him up by the arms.
But Dean remains where he is.
He begins, on his knees, to wash the entire surface of her left thigh, knee, calf, foot.
Then he moves to her right foot and up her calf, knee and thigh.
Cindy releases her breath.
Then, Dean's hands move up between her legs.
CINDY Okay.
Cindy grabs under his armpits.
He refuses, but she wins.
She pivots them around again.
Standing in the stream of water, Cindy washes the soap off her body, eyes closed, head back.
Dean reaches for her and follows with his fingertips the flow of water down the front of her body.
CINDY (CONT'D) Give me the soap.
She forms a quick lather in her hands.
She rubs it into his chest, her strong hands making circles of suds.
Dean is a tranquil participant.
She lifts up his left arm, scrubs his armpit, then his right.
Her hands build a lather and wash his penis.
Dean catches his breath.
CINDY (CONT'D) Turn around.
Dean obeys.
She continues wash his back, buttocks and legs and stops.
Dean turns around to Cindy who holds a squirt of shampoo in her hands.
She reaches up and scours his head.
DEAN Getting thinner, isn't it?
CINDY Your hair is not falling out.
Cindy pivots him around into the water and rinses him.
CINDY (CONT'D) You're crazy you know...
DEAN I know.
DEAN I love you.
Blue Valentine Official Green Script as of 6/9/09 36.
CINDY Okay, get out.
CINDY I have to finish washing myself.
DEAN I'll do it.
CINDY No.
CINDY Go order dinner.
CINDY I'm hungry.
DEAN Wait, I didn't wash your hair...
Ice dumps into an ice bucket.
Music and laughter emanate from other rooms.
Dean wears a hotel robe and carries a full bucket of ice.
He swipes his key.
A TEENAGE boy in a tuxedo shirt and swim trunks chases a girl in a bikini down the hallway behind him.
DEAN We have neighbors.
Cindy stands in a towel at the bar, waiting for the ice.
CINDY Grump.
CINDY Grump.
She makes 2 drinks - vodka on the rocks.
She hands Dean his drink.
CINDY (CONT'D) Why don't you put some music on Dean?
She pecks him on the cheek, walks to the bedroom to change.
DEAN Thanks.
Blue Valentine Official Green Script as of 6/9/09 37.
She hears the music begin from the other room, knows the song - (Penny & the Quarters or Dynamite Four) It sounds really good right now.
Drink in hand, she begins to sway to the rhythm.
Dean peeks his head around the corner with a shit- eating grin.
He starts to awkwardly dance to the music and make his way down the hallway to the bedroom.
It's been years since they danced in front of each other, and it makes them a little embarrassed to be doing it now.
The closer they get to each other, the less they can be seen, the less they are exposed.
Soon, they are slow dancing, still holding drinks.
They don't feel as vulnerable now.
The cotton on Dean's robe feels good to Cindy's fingertips, she traces invisible pictures on his back.
Dean burrows his nose into Cindy's neck, inhales deeply.
There is a knock at the door.
They both wish it would go away.
It doesn't.
DEAN (YELLS) (cont'd) Coming!
Something about this makes Cindy laugh, Dean too.
He backs away from her, slowly, as if pulled by some unseen force.
The song continues as Dean opens the door and pays the ROOM SERVICE MAN.
Cindy sets the table.
A torn and tattered teddy bear, tied to the grill of the truck, cuts through the early spring morning.
CURTIS (V.O.) Yeah.
CURTIS (V.O.) I can tell what's happening already.
CURTIS (V.O.) You see this person...
CURTIS (V.O.) you think it's love at first sight, and the course of your life will be forever changed.
Dean straps a weight-lifting belt around his waist.
He lifts a TV on his back.
DEAN (V.O.) Maybe...
Cindy gives Gramma a bath, runs her hair under the faucet.
Blue Valentine Official Green Script as of 6/9/09 38.
CURTIS (V.O.) It's like when two streams are flowin' down opposite sides of the mountain, mindin' their business.
A hand tucks sheets under Gramma's chin, kisses her forehead.
CURTIS (V.O.) They're doin' fine until they hit the bottom and run into one another...
Bobby trains, 200 sit ups, his abdomen taught.
CURTIS (V.O.) At that point they got no choice but to become one river.
Dean counts his pay, opens his wallet - packs it with bills.
CURTIS (V.O.) Sure, it's a great feeling at first, all this new water flowing together.
CURTIS (V.O.) But then you travel down a little ways and the land levels out.
CURTIS (V.O.) The current starts moving a little slower.
Papers are passed back.
Cindy's reads "98% Great Insight!" She doesn't look happy though.
She looks a little green.
People start drinking the water.
Pissin' in it.
Putting up dams to stop the flow.
In the corner of the room, Bobby stares at Cindy from behind.
Cindy pushes Gramma Francis up the driveway.
Bobby stands on the porch holding a bunch of red roses.
Cindy ignores it.
In other words, life interferes, you know.
Blue Valentine Official Green Script as of 6/9/09 38A.
Cindy struggles to get Gramma up the ramp of the porch.
Blue Valentine Official Green Script as of 6/9/09 39.
BOBBY Hasn't anyone ever been nice to you?
She takes the flowers, pushes Gramma into the house.
The screen door closes between them.
BOBBY (CONT'D) Don't make me give up on you...
And there's not too many of these rivers that'll make it all the way to the ocean without splitting off eventually.
CURTIS (V.O.) It's just nature, that's all.
Curtis - with harmonica - and Dean - with ukulele - eat hamburgers on their lunchbreak.
CURTIS (CONT'D) And instead of thinking about it you gotta just do something about it.
CURTIS (CONT'D) Action, not thought.
DEAN Anyone call for me?
Dean peeks into Jo's office.
She shakes her head "no."
Dean leans near the window, smoking, looking out at the moon.
DEAN (V.O.) I just keep replaying it in my head.
DEAN (V.O.) Thinking about other things I coulda done.
DEAN (V.O.) Other things I coulda said.
Cindy pours over textbooks but she is distracted.
She opens her window and breathes in the night air.
DEAN (V.O.) You wait your whole life for something to happen...
DEAN (V.O.) Blue Valentine Official Green Script as of 6/9/09 39A.
Cindy pukes in the toilet.
Blue Valentine Official Green Script as of 6/9/09 40.
DEAN (V.O.) ...And you have all these ideas in your head about how you'll act and what you'll say and what you'll do, who you'll be...
She washes the taste out of her mouth and looks at herself in the mirror.
She flicks water at her reflection.
Dean sweeps the bed of the truck.
The broom catches something in the corner.
Dean reaches - a locket.
DEAN (V.O.)
cont'd ...And then the opportunity comes, it presents itself to you, living and breathing in the flesh, and you puss out.
Dean holds up the locket and stares at it, twirling.
He opens the latch - sees a picture of the old man and his wife - 60 years ago.
Dean puts it in his pocket, finishes sweeping up.
Still wearing his work clothes, Dean rides the train out of the city, pulls out the locket.
Reads the inscription on the back - "you are my sunshine."
Dean gets off the train.
Asks some people for directions.
A feeling of anticipation.
Dean pulls the lever - his stop.
Dean walks to the old man's room.
The door is open, lights are off, room is empty.
All the furniture, pictures, gone - just an empty bed.
Dean is at a loss for what to do.
He hears the TV coming from across the hall.
He knocks, waits, then opens Cindy's Gramma's door.
She is lying in bed.
Tries to recognize Dean.
He pulls up a chair next to her.
DEAN Hi.
DEAN I was looking for your neighbor...
DEAN the man who moved in last month.
DEAN Across the hall.
DEAN Do you know what happened to him?
Blue Valentine Official Green Script as of 6/9/09 41.
GRAMMA He went out for groceries.
DEAN What about the girl that was with you?
GRAMMA Who?
The conversation moves in circles.
Not much information is gained.
Dean ends up just holding her hand.
The bus drives away.
Inside, Dean stands.
He is a little down.
He feels around in his pocket.
Finds the locket.
He puts it on.
The bus comes to a stop.
A few passengers get on.
One of them is Cindy.
Dean watches her pay her fare and move to the back of the bus without noticing him.
She finds a seat, pulls her hoodie low, anonymous.
She underlines passages from a textbook using a highlighter.
Dean is frozen.
He gathers the courage to walk toward her.
The moving bus throws his balance.
He stands over her for a moment.
Cindy senses somebody in her space.
She looks up.
Recognizes him, but can't place it.
DEAN Hi.
CINDY Hi.
DEAN I just had a long talk with your gramma...
DEAN is that, is that your gramma?
Cindy remembers him now - he's just dressed nicer - he doesn't look like a mover
DEAN (CONT'D) I was looking for that old guy who moved across the hall, you know?
DEAN (CONT'D) Do you know what happened to him?
Blue Valentine Official Green Script as of 6/9/09 42.
CINDY I think he passed away.
Dean feels for the locket around his neck.
He shakes his head.
DEAN That's exactly what happened to my dog.
DEAN My parents moved out of our house and three days later she was a goner.
He pulls the locket out from behind his shirt.
He unclasps it.
Shows her the pictures.
DEAN (CONT'D) He was so handsome, wasn't he?
DEAN (CONT'D) I was trying to give it back to him.
Cindy looks at it.
CINDY She was pretty too..
Dean thinks about the old man.
The bus drives.
DEAN She must have been crazy.
CINDY Why do you say that?
DEAN Cause there's one thing I know...
DEAN the prettier a girl is the more nuts she is.
DEAN I mean, look at you...
DEAN you must be insane.
CINDY Excuse me?
DEAN It's okay, I mean, I get it.
DEAN It's not your fault.
Cindy pulls the chain to stop the bus.
DEAN (CONT'D) Where you going?
CINDY Home.
Blue Valentine Official Green Script as of 6/9/09 42A.
DEAN Can I walk with you?
Cindy thinks about it.
DEAN (CONT'D) Just for a little bit...
DEAN (CONT'D) And when you don't want to walk with me no more, then just speed up.
Doors to the bus open.
Cindy thinks about it.
Dean and Cindy wander side by side down the sidewalks and streets of the town.
They walk and talk about - small towns and big cities, school and work, dreams and nightmares, being old and being young, etc.
Blue Valentine Official Green Script as of 6/9/09 43.
DEAN Where's you house?
CINDY We passed it.
DEAN Where?
CINDY Back there...
CINDY ELLIPSE: Cindy smokes one of Dean's cigarettes, calls her dad
on a pay phone and tells him she won't be home for dinner because she is studying.
ELLIPSE.
DEAN tells Cindy about his childhood, the
sexualizing of his mother, and his fascination with women's purses.
It makes Cindy a little uncomfortable.
DEAN Do you think it would be okay if I looked in your purse?
CINDY No.
DEAN Why?
Cindy thinks about it for a moment.
Against her better judgement, she hands over her bag.
It weighs a lot.
DEAN (CONT'D) Jeez...
DEAN (CONT'D) What you got in here?
CINDY Books.
CINDY Mostly.
DEAN Lot of books.
DEAN You doing good?
CINDY We'll see.
DEAN What are you gonna be when you grow up?
CINDY I'm trying to get into med school.
Blue Valentine Official Green Script as of 6/9/09 44.
DEAN You going to be a doctor?
CINDY Someday.
DEAN Oh yeah?
DEAN What should I do about this?
He pretends to bump into a pole.
Cindy laughs.
CINDY Don't do it.
CINDY DEAN (rubbing his head) You're gonna be a good doctor.
CINDY I can tell.
CINDY He digs through text books, pens, a wallet, asthma inhaler.
CINDY Then he comes to a bottle of lotion.
CINDY Opens the cap, sniffs.
DEAN (CONT'D) Mmm.
DEAN (CONT'D) This is what you smell like?
DEAN (CONT'D) Cindy nods, "I guess so."
DEAN (CONT'D) I wanna smell like you.
DEAN (CONT'D) Can I?
CINDY You wanna put on my lotion?
Dean nods, applies a little lotion to his fingertips, rubs it in circles on his hands, applies it to his forearms, neck, face.
He enjoys the feeling of it, offers her some.
She say's no.
He digs through her purse and finds lip balm, smells it.
DEAN This is what your lips smell like?
DEAN They must smell good.
He puts some on his lips.
DEAN (CONT'D) Mmm.
DEAN (CONT'D) Your lips must taste good.
CINDY Are you fucking with me?
DEAN No.
DEAN Blue Valentine Official Green Script as of 6/9/09 45.
DEAN What's in there?
She takes her purse back.
CINDY Okay enough...
DEAN Why?
CINDY Because.
Throughout the rest of the night Dean tries to continually steal Cindy's purse from her.
It is a game.
Innocent.
CINDY Aren't you gonna miss your train?
DEAN Probably.
DEAN I think I...
DEAN I think I already did.
DEAN It's okay.
DEAN There's an early one.
CINDY You are just gonna stay up all night?
DEAN Until you get tired...
DEAN Where'd you grow up?
CINDY Here.
DEAN Here?
Cindy gives him a grimace.
CINDY Same streets.
CINDY Same people.
CINDY Everything here is the same.
CINDY You walk down the street, you can't get lost...
CINDY you know.
Blue Valentine Official Green Script as of 6/9/09 46.
DEAN Where do you want to go?
DEAN I mean, if you could go anywhere..
They walk to an old playground.
Cindy gets an idea.
CINDY There!
Cindy runs to an old, creaky merry-go round, jumps on.
CINDY (CONT'D) I used to love these things.
DEAN Oh God...
DEAN I hate these things.
CINDY Push me.
Dean is tentative, but goes along with her.
He starts slow, but she eggs him to go faster.
He runs in circles picking up speed until he is in a breathless, circular sprint.
He can't keep up with the centrifugal force.
CINDY (CONT'D) Get on!
Blue Valentine Official Green Script as of 6/9/09 47.
DEAN What happened, tough guy?
CINDY Make it stop.
DEAN You gotta puke...
DEAN it's the only way.
She refuses.
DEAN (CONT'D) It's the only way.
DEAN (CONT'D) It will make you feel better.
DEAN (CONT'D) Don't be embarrassed.
DEAN (CONT'D) I'll do it.
He sticks his finger down his throat and forces himself to vomit.
The sound of it is too much for her.
She gags.
Side by side, they puke into the gravel.
They finish their business and end up on their backs and out of breath, side by side, looking up at the stars.
They are both covered in sweat.
We see their breath.
CINDY I'm still spinning.
DEAN Me too.
CINDY Maybe it's just the Earth that's spinning.
DEAN Yeah.
DEAN We're flying.
They laugh.
Birds begin to awaken and fly.
DEAN (CONT'D) You should come visit me in the city sometime.
The morning air chills their bodies.
Dean takes off his jacket and uses it as a blanket.
They get close together to get warm and watch the stars spin above them.
The dining room table is set for two.
A single champagne glass is raised.
DEAN To honesty...
Blue Valentine Official Green Script as of 6/9/09 48.
They sit across from each other.
Cindy drinks premature.
DEAN (CONT'D) Hey!
DEAN (CONT'D) Wait up.
CINDY We're toasting tonight?
Dean makes his toast.
CLINK.
Dean quaffs his glass.
CINDY (CONT'D) Sometimes you don't make any sense.
CINDY (CONT'D) You might as well be speaking Chinese.
Dean imitates a Chinese man - it goes on too long.
CINDY (CONT'D) Happy belated anniversary.
Cindy starts to eat a spread of Indian food and booze.
DEAN How is it?
CINDY Good.
CINDY How did Frankie sound?
DEAN Great.
DEAN She's the best.
CINDY She didn't sound sad?
DEAN Naw.
DEAN She's the champ.
DEAN She's the best parts of you and the best parts of me put together.
DEAN Everyday she gets more and more amazing.
Dean chews a bite of meat and washes it down with a shot of vodka.
He refills both their glasses.
CINDY Daddy's little girl.
DEAN She's not mine.
DEAN I'm hers.
Blue Valentine Official Green Script as of 6/9/09 49.
Cindy slows down.
DEAN (CONT'D) I'm her father.
DEAN (CONT'D) She isn't there for me...
DEAN (CONT'D) I'm there for her.
DEAN (CONT'D) That's the way I look at it.
CINDY That's beautiful.
DEAN It's the choice I made when she was born.
Silence.
They chew.
Cindy stares through Dean.
CINDY Why don't you do something...
DEAN Like what?
CINDY I don't know...
CINDY isn't there anything you want to do?
Dean thinks about it.
Shakes his head.
DEAN What am I supposed to want to do?
CINDY I don't know...
CINDY You have so many things you could do.
CINDY You're good at everything.
CINDY You could do anything you wanted.
DEAN I just wanna be with you.
Silence.
Cindy tries not to look disappointed.
DEAN (CONT'D) You look like an animal right now.
DEAN (CONT'D) Your eyes look like an animal.
DEAN (CONT'D) Like a bear's eyes.
CINDY Like right before the bear eats the man?
DEAN Yeah...
DEAN You do.
DEAN It's true.
DEAN That's what you look like.
Blue Valentine Official Green Script as of 6/9/09 50.
DEAN (CONT'D) Whatchu thinking about?
CINDY How different we are.
CINDY You and me.
DEAN Different?
CINDY It's a good thing.
DEAN You think that's good that we're different?
CINDY Absolutely.
CINDY We don't have to get in each other's way.
DEAN And that's the way you like it, don't you?
DEAN You don't like me to bother you.
CINDY I didn't say that.
CINDY What I meant is that it's important for us to have our space.
CINDY That's all.
CINDY We're grown people.
DEAN Well there's not much space here.
DEAN So I guess you won't be able to get away from me will ya?
CINDY You know, we rarely sit down and have a conversation.
CINDY An adult conversation.
CINDY Because every time we do, you turn something that I say around and make it mean something that I didn't mean to say.
CINDY You just blab.
CINDY Blab.
DEAN If you're not interested in hearing what I think I just won't say anything.
CINDY Good luck.
CINDY I just want you to think about what you say sometimes instead of saying what you think all the time.
Blue Valentine Official Green Script as of 6/9/09 51.
DEAN OK.
DEAN I'm going to say something.
DEAN And what I'm about to say I've thought long and hard about.
DEAN I'm the luckiest person alive because I'm living my dream - you, her, this, us, all of it.
Cindy lifts up her empty wine glass to the light.
CINDY I think my glass has a hole in it.
Cindy cuts around her food and pushes a piece aside.
DEAN What's wrong with that?
CINDY It's fat.
DEAN That's the flavor.
DEAN Eat it.
CINDY I don't want to.
CINDY You eat it.
Dean stabs a piece of fat and pops it into his mouth.
CINDY (CONT'D) That's going straight to your tits.
DEAN My tits?
DEAN I got tits?
Dean opens his shirt and peers down at his chest.
DEAN (CONT'D) I could still kick yer ass.
Blue Valentine Official Green Script as of 6/9/09 52.
CINDY Shiiit.
CINDY I bet you a nickel you can't even beat me at arm wrestling.
DEAN A dime and you're on.
Cindy gulps more champagne.
They scoot dishes out of the way and clasp hands in the middle of the table.
CINDY Ready?
DEAN I'm always ready, baby.
CINDY On the count of three...
CINDY One...
CINDY Two...
Cindy flexes and starts.
Dean, acting as if he isn't trying at all, holds Cindy's hand at a stand still.
DEAN Come on.
DEAN Go!
DEAN Start.
Cindy ignores his taunts and pushes as hard as she can.
Slowly, she begins to push Dean's hand down.
Dean groans, letting her win a little.
Cindy presses down with all her weight.
His hand is centimeters from hitting the table.
Then, he turns the tide.
Cindy battles back with all the strength she can muster.
Dean laughs, realizing her passion for victory.
Dean pounds her hand into the table.
He stands kisses his flexed bicep.
Cindy lifts her hand.
A fork is stuck in the back of it.
She looks at it with curiosity.
DEAN (CONT'D) Oh fuck.
CINDY I'm alright.
Blue Valentine Official Green Script as of 6/9/09 53.
DEAN Hold still.
He plucks the fork from her hand, leaving four vampire bites.
CINDY Ow ow ow.
Dean leads her to the kitchen, holds her hand under the faucet.
DEAN You think we should rush you to the hospital before you bleed to death?
Cindy shoots him a look.
Dean wraps her hand with a dishrag.
DEAN (CONT'D) Does it hurt?
CINDY It stings a little.
Dean tries to pick up Cindy.
She struggles against it.
Finally he cradles her like a squirming baby.
CINDY (CONT'D) No, no...
CINDY (CONT'D) Put me down.
CINDY (CONT'D) It's okay...
Dean huffs a little.
Cindy adjusts her weight, self- conscious.
He hefts her down the hallway to the bedroom.
Dean awkwardly sets Cindy down on the circular spaceship bed.
DEAN Wait wait wait.
Blue Valentine Official Green Script as of 6/9/09 54.
DEAN (CONT'D) To numb the pain.
DEAN (CONT'D) Doctors orders.
DEAN (CONT'D) I'm an anesthesiologist.
CINDY I'm spinning.
She sits up.
They toast.
Dean gulps his.
Cindy takes a sip.
DEAN Drink up.
DEAN We haven't gotten loaded together in years.
He tops off her glass, refills his own, and quaffs it.
DEAN (CONT'D) I gotta take a piss.
DEAN (CONT'D) Don't fall asleep.
He kisses her on the forehead, stumbles.
Cindy hears Dean urinating.
She is sickened by it.
She tries to set her full glass on the floor that spins beneath her.
The toilet flushes.
The drink tips over.
A loud crash comes from the BATHROOM.
Cindy sits up.
CINDY What are you doing in there?
CINDY ...Dean?!
An agonizing moan comes from down the hall.
Cindy staggers off the spinning bed and stumbles to the bathroom door.
CINDY (CONT'D) Are you all right?
CINDY (CONT'D) Dean...
She pushes the door but it is blocked.
Dean moans louder.
Cindy pushes again and inches it open.
She sticks her head in, sees him laying on his back looking up at the ceiling.
I fell over.
Blue Valentine Official Green Script as of 6/9/09 55.
CINDY Ew.
CINDY Come on, get up.
DEAN Nope, I want you to come here first.
DEAN I want you to laugh.
Cindy opens the door and Dean scoots, making room for her.
He lets out an "ow" before extending his hand.
DEAN (CONT'D) Come close.
DEAN (CONT'D) I want to hear you...
DEAN (CONT'D) I want to tell you...
DEAN (CONT'D) Shh, come here...
Cindy reluctantly joins him on the bathroom floor.
Their faces are close, eyes locked.
DEAN (CONT'D) You want to hear a joke?
DEAN (CONT'D) OK.
DEAN (CONT'D) What's better than winning a gold medal at the Special Olympics?
CINDY What?
DEAN Not being retarded.
Cindy looks down.
DEAN (CONT'D) Hey...that's not funny?
DEAN (CONT'D) How come you don't think I'm funny any more?
DEAN (CONT'D) I tell you something funny.
DEAN (CONT'D) You laugh.
DEAN (CONT'D) I see you laugh.
DEAN (CONT'D) But you don't really laugh so much.
DEAN (CONT'D) You don't laugh anymore Cindy.
CINDY Dean...
CINDY Come on, it's time for bed.
DEAN No I want to make you laugh.
Tears well up in her eyes.
Dean rolls on top of her.
He cups her face in his hands and stares long into her watery eyes.
DEAN (CONT'D) Hello...
CINDY You're drunk.
Blue Valentine Official Green Script as of 6/9/09 56.
DEAN No, I'm just still in love with you.
After a moment, their lips meet in an awkward rejuvenation.
She moves her head away and pats Dean on the shoulder in a gesture of friendship.
Dean kisses her neck.
DEAN (CONT'D) Do you...
DEAN (CONT'D) you want to have another baby?
DEAN (CONT'D) ...
DEAN (CONT'D) I want another child.
Cindy bites her lip.
He slides his hand between her legs.
CINDY No...
CINDY Dean...
CINDY Wait a second.
She removes his hand and places it on her hip.
Dean continues to kiss her neck.
He slides his hand up to her breasts.
Cindy turns her head in the other direction.
She pushes his hand away.
He brings it back aggressive.
Again.
Cindy squirms underneath him.
He grabs her wrists and holds her arms over her head.
His tongue licks Cindy from her breasts to her face.
She worms her arms away and grabs onto his hair.
She arches her back, looks at him through slit eyes.
His pelvis pulses and he moans.
He looks up at her over his brow into her desperate eyes.
He springs up.
Sweat beads on his forehead.
DEAN What!?
DEAN I can't have sex with my wife!?
Cindy covers her face with her hand.
DEAN (CONT'D) Do I repulse you that much?
DEAN (CONT'D) I'm good to you.
DEAN (CONT'D) I'm good to Frankie.
DEAN (CONT'D) I deserve a little affection.
DEAN (CONT'D) Do you want me to stop loving you?
DEAN (CONT'D) Do you want me to fuck other women?
DEAN (CONT'D) Do you want me to beat you?
CINDY Stop...
CINDY stop...
CINDY stop...
DEAN Is that what you think you deserve?
DEAN Would that make it easier on you so you can treat me like this?
Blue Valentine Official Green Script as of 6/9/09 57.
He unbuckles his belt, pushes his pants and underwear down to his knees, holds himself in his hand.
He lowers onto her.
Cindy adjusts her legs higher.
He rotates his hips, looks away in concentration.
Cindy's arms move around him, grabbing the small of his arching back.
His pelvis humps in a feeble performance.
A small moan.
Cindy's eyes press closed harder.
The erratic motion slows...
stops.
Dean's raspy breathing.
His weight covers Cindy.
She opens her eyes to the ceiling.
DEAN (CONT'D) I'm sorry...I'm sorry...I'm sorry...
She looks at him.
His head faces away.
She rolls out from underneath and stands.
She wraps her dress around her and slips into the bedroom.
Back against the closed door, Cindy turns the lock.
Her eyes shift from despair to relief.
Her gaze grows more wild.
The doorknob jiggles.
A secret, crazy laugh builds in Cindy that she suppresses.
Dean presses his face into the bedroom door.
He talks to her.
On the other side of the door, Cindy listens.
Dean's voice cracks.
A wave of confusion backs Cindy away from the door.
She searches the room for an escape.
There are no windows, the only way out is through the locked door.
Trembling, she wraps her arms around herself.
She tries to make herself as small as possible.
The spaceship bed is the only place where she can disappear.
She crawls underneath the covers, curls into a tight ball.
Sadness lets loose.
Cindy's body pulses with faint, painful tears.
The black walls of the room twinkle with stars suspended in space.
The cries get lost.
Drunk, Dean and Cindy make out on the street corner.
It is cold enough to see their breath.
Their hands caress each other, feel what is underneath the layers of clothes.
Cindy makes a move.
She unbuttons Dean's Pea-Coat, feels the shape of his chest, his abdomen, his back.
CINDY Are my hands cold?
DEAN Yes.
Blue Valentine Official Green Script as of 6/9/09 58.
Dean follows suit, reaching up under her jacket to touch the skin on her lower back.
She recoils from the icy touch.
CINDY You wanna go somewhere.
DEAN Sure.
CINDY Where can we go?
They make out in the back of a cab.
But the cab driver won't allow it.
But they can't keep their hands off each other.
They try not to get caught.
The door to Jake's room is cracked open and the TV is on.
Dean and Cindy tiptoe in the apartment as quietly as they can.
They can't keep their hands off each other.
Dean makes a bed for them on the couch where he sleeps - straightening out a couple white sheets.
They crawl under with clothes on.
CINDY (WHISPERS) Is your roommate awake?
DEAN (WHISPERS) I don't know.
DEAN (WHISPERS) Let me go check.
DEAN (WHISPERS) DEAN (WHISPERS) (cont'd) He's just watching TV.
They start to make out while listening for Jake.
CINDY (WHISPERS) Do you think he's gonna come out?
DEAN (WHISPERS) I don't know...
DEAN (WHISPERS) Should I go see if he brushed his teeth?
Blue Valentine Official Green Script as of 6/9/09 59.
DEAN (WHISPERS)(cont'd) It's still dry.
He gets back on the couch.
They kiss.
Slowly.
Silently.
Their hands search each other under the blanket.
Clothing is removed and there is alot of movement, but the details of what occurs under that single sheet remain largely a mystery.
Jake's bedroom door opens and Jake walks out into the living room and into the kitchen.
Dean and Cindy pantomime sleeping.
They listen and hear Jake opening the refrigerator, pouring himself a bowl of cereal, crunching.
They feel like he's watching them.
Cindy tries her hardest not to laugh.
Jake stares at the trembling sheet with contempt before returning to his room.
Cindy releases her laugh.
Dean tries to shush her, but he can't help laughing himself.
DEAN (CONT'D) Be quiet!
DEAN (CONT'D) Seriously.
DEAN (CONT'D) He's gonna kill me.
DEAN (CONT'D) He already hates me.
CINDY You think he's gonna go to sleep now?
They hear Jake changing channels in the other room.
As quietly as possible, they have sex under the sheet.
A red plus sign bleeds onto the result area of a home pregnancy test.
Cindy sits on a toilet in a stall holding the positive test stick.
A knock on the BATHROOM door.
CINDY Just a second...
She wraps the test in toilet paper and buries it in the trash receptacle.
A moment while the door swings closed.
Silence.
Cindy opens the stall and confronts herself in the mirror.
Cindy writes a note to Dean, his business card sits next to an envelope.
The note reads: I don't know if I can trust you.
Can I trust you?
I'm in trouble.
Bobby places a test paper in front of Cindy.
Her grade, "D."
She covers up her note.
He leans in and swipes the business card.
Blue Valentine Official Green Script as of 6/9/09 59A.
CINDY Give it back!
Bobby crushes the card in his fist.
She tries to pry it open.
She can't.
She's not gonna get it back.
Dean and his buddies, file out of the garage, he notices Cindy across the street, he looks both ways, crosses the street toward her.
The closer he gets to her, the more nervous she gets.
DEAN Are you okay?
Cindy nods.
CURTIS See you later, Elvis!
Dean turns around and sees his work buddies busting him for being a Romeo.
He waves goodbye to them, turns back to Cindy, embarrassed but happy.
She smiles, concealing something.
Blue Valentine Official Green Script as of 6/9/09 60.
Dean and Cindy stand a distance away.
Cars beneath them roar.
DEAN Is it mine?
Cindy looks Dean in the eyes.
CINDY I...
CINDY I don't know...
CINDY It might be...
DEAN You let that asshole knock you up?
CINDY ...I'm sorry...I'm sorry...
DEAN When'd this happen?
CINDY Before us.
DEAN What do you want to do?
CINDY I don't know.
DEAN We'll keep it.
DEAN We'll take care of it.
Cindy nods.
Silence.
CINDY It's not the right time.
Dean looks down, pauses and looks back to Cindy.
DEAN Do you want to take care of it?
A female DOCTOR sits on a wheeled chair in the corner of the room and looks through Cindy's file.
DOCTOR You can put your clothes on the chair.
Blue Valentine Official Green Script as of 6/9/09 61.
Cindy does.
DOCTOR (CONT'D) How are you doing?
CINDY Okay...
The DOCTOR wheels over to the table in the center of the room.
She pulls out a clean sheet of examination table paper.
DOCTOR I'm going to have you lie up here, and put your feet in the stirrups.
Cindy gets on the table, looks over at a tray of instruments.
The Doctor pulls a mask up over her face - the vacuum aspirator on a wheeled base.
Cindy focuses her gaze at the corrugated ceiling, dim light.
DOCTOR (CONT'D) Are you okay?
CINDY Yeah.
The Doctor touches Cindy's knee to spread her legs, picks up an instrument off the table.
DOCTOR I want you to try and relax.
DOCTOR This is going to be a little cold.
The Doctor inserts a speculum into Cindy's vagina.
DOCTOR (CONT'D) There, take a deep breath...
DOCTOR (CONT'D) What do you do?
CINDY I'm a student...
DOCTOR What are you studying?
The Doctor dips a long swab into a solution, inserts it into her vagina.
CINDY I'm studying to be a DOCTOR...
DOCTOR That's what I studied.
Blue Valentine Official Green Script as of 6/9/09 62.
She laughs.
Cindy doesn't know what to do with her eyes.
The Doctor picks up a syringe.
CINDY What's that?
DOCTOR This is a mild anesthetic for your cervix.
DOCTOR You're going to feel a pinch and then it's going to feel like electricity.
Cindy looks back up at the ceiling.
She steady's her breath.
DOCTOR (CONT'D) Can you cough for me.
Cindy coughs.
DOCTOR (CONT'D) Good...
DOCTOR (CONT'D) Why do you want to be a Doctor?
Wheels move across the linoleum floor.
The Doctor positions the vacuum aspirator.
CINDY Because...
CINDY I always thought...
CINDY it would be wonderful to take a sick child and...
Cindy cuts herself off.
The Doctor holds a hose.
DOCTOR And what?
CINDY ...heal them...
DOCTOR Cindy, I'm going to begin the procedure.
DOCTOR It won't take long.
DOCTOR You may feel a little cramping.
The Doctor turns on the vacuum.
Panic flushes Cindy's face.
Her eyes widen.
CINDY Wait...
CINDY wait.
A plastic model of a womb and fetus on the magazine-laden coffee table.
Ashtrays overflow.
Dean, wearing his work clothes, sits among several would-be fathers.
Blue Valentine Official Green Script as of 6/9/09 63.
He snuffs his cigarette and studies the fetus in the plastic uterus.
TROY, Bobby's wrestler friend, sits nearby.
The waiting room door opens, Cindy comes out.
Dean puts the model back and stands up.
They stare at each other.
Dean nods slightly.
Cindy shakes her head "no."
A flush of realization across Dean's face, then a smile.
He goes to her and wraps his arms around her.
Cindy?
Cindy looks over Dean's shoulder to Troy, who gazes at her over a magazine.
Dean looks back and forth between them.
Cindy looks ahead and walks out with Dean.
Darkness passes.
Cindy lies against Dean in the back of the bright bus.
Her head rests on his chest, arms holding his encircling arms.
She is wearing the locket around her neck.
Dean caresses Cindy's earlobe.
Her eyes are closed.
DEAN You're not in this alone.
DEAN This baby is ours.
DEAN It's us.
DEAN Let's start a family.
CINDY Your eyes ever wide open, and you're dreaming?
Cindy breathes deep & settles into him.
Dean hums a lullaby.
CINDY (CONT'D) You smell like you.
Darkness disturbed by beeping.
Cindy awakens, dishevelled from the night before.
She lifts her cell phone off the bedside table and squints to make out the text.
CINDY Shit.
CINDY CINDY (on phone) (cont'd) Hi it's Cindy...
CINDY I have this weekend off.
Blue Valentine Official Green Script as of 6/9/09 64.
CINDY (cont'd on phone)
...Who didn't show?...Meredith again?
How long can she keep doing this?...
Did you try Janet?...She's your first call....I'm out of town too...Yes I know, I know all of it.
Yes...It's going to take me a few hours.
She hangs up, eases the door open.
Dean is passed out in the middle of the hallway.
She tries to wake him, but he's hibernating.
She steps over his fallen body.
- Cindy washes her face in the shower.
She looks at the vampire holes on the back of her hand.
- her hair in a towel, Cindy flicks on the coffee maker.
She eats a banana.
- she throws on jeans and a sweater.
- inhales from an inhaler for her asthma.
- holds her eye open and drops eye-drops.
- vigorously brushes her teeth.
- drinks coffee and writes a note on Fantasuite stationery.
- washes the mug in the kitchen sink.
- tapes the note to the television screen.
- She stands over DEAN.
CINDY Goodbye.
No response.
She closes the door behind her.
The phone rings.
Dean's eyes struggle open, drunk.
He listens annoyed to the ring.
After the eighth ring, he hollers.
DEAN Cynthia!
No response.
He struggles up and stumbles to the phone.
DEAN (CONT'D) Hello?
A prerecorded message.
Good morning.
This is your...11:30 a.m...wake up call.
Blue Valentine Official Green Script as of 6/9/09 65.
He hangs up the phone and looks around the room.
DEAN (confused) (cont'd) Cynthia?
He wanders to the bedroom, the door is open.
Cindy's bags sit next to a made bed.
He calls out for her again.
- He walks into the bathroom and urinates, finds only a damp towel hanging over the shower door.
He touches the bristles of Cindy's toothbrush, flicking up a spray of water.
- He walks to the kitchen and lights a cigarette.
He coughs a little as he pours himself a cup of coffee.
Zaps it in the microwave.
A plane cuts through the sky.
Dean stands in front of an empty parking space.
He stares at where her car should be.
A Chrysler Aspen is parked with its back opened.
KARINA and BILLY, two high school kids, toss in luggage.
Dean leans on the concierge desk.
DEAN Was she with a guy?
Like I said, I couldn't say.
I just got here, so maybe she left before I came in.
He types on the computer.
And, she didn't check out.
You're still booked until...Monday morning.
11 am.
Is there anything else I can help you with sir?
Dean puts his key in the door to his room.
Across the hallway, Billy calls into a room.
Hurry up Randy!
Dean walks in to his room, sits down, heavy.
His stare is out of focus.
He turns on the TV.
Volume comes up loud.
The TV illuminates the note left by Cindy.
Dean stares at it for a moment.
He plucks the note from the screen and reads it.
"Dean - I got called in.
Blue Valentine Official Green Script as of 6/9/09 66.
I was going to wake you but I knew you wouldn't understand.
I'll be back this afternoon to get you.
We have to talk.
I'm sorry...-C"
Dean eyes search for something.
He sees the vodka bottle and takes a drink.
Pacing, he lets out a few angry weeps and reaches in his front shirt pocket for a cigarette.
He's out.
In the ashtray, he grabs a snuffed out butt.
He searches for a lighter.
He lights his cigarette on the stove.
He hears the kids in the hallway.
He opens the door and Randy, a hungover high school kid, and AMANDA, large-chested, short, walk down the hallway, arm and arm.
They slow when see a frighteningly dishevelled Dean, vodka in hand, cigarette in mouth, framed in the door jam.
Dean rides in the back seat of a Jeep Cherokee wedged in between Amanda and Randy.
Billy and Karina sit in the front seat.
Amanda offers Dean a glass pipe.
You want some of this?
Dean accepts the pipe and takes a monster toke, holding it in until his face turns purple.
Spring sky..
Trees blossom.
Cindy walks alone down the street from the train station.
The front door squeaks open, Cindy slips in.
Glenda is passed out on the couch.
She tiptoes up the creaking staircase.
A shower runs.
She heads down the hallway to her room.
Cindy opens the door to her bedroom, falls on her bed and is about to close her eyes but is distracted by the blinking lights of the answering machine.
Cindy presses play.
You have twenty five new messages.
BEEP
Cindy sits up.
Bobby voice is heard - drunk.
Blue Valentine Official Green Script as of 6/9/09 67.
BOBBY (on answering machine) I just want to say to you thanks for making all bets off and freeing me of my human decency.
All your shit's going in the trash, your books are gonna be ripped up.
We'll go to war see who'll win.
I know who the fucker is and I'm gonna destroy him.
BEEP You probably don't know what you did.
I want it all to come out.
It'll be beautiful, It'll be sweet, it'll be awesome.
BEEP
Glenda's bloodshot eyeball appears in the doorway.
Bobby (V.O.)
(cont'd) BEEP Well, what I was really trying to say before your machine cut me off is you created me, I'm your child...
You created the person that I am now, and now you have to deal with this person.
A SOUND - Cindy turns around sees her mom in the doorway.
The car drives down a highway toward the city.
TONY powers down beers in the back.
Underwear hangs from the rearview.
...And I got nothing better to do than destroy you both.
BEEP If you think I'm being evil, you have no idea, no idea at all...
I'm growing very impatient and I really don't give a fuck anymore...
Bobby shotguns a beer in the passenger's seat.
Speed metal music and adrenaline.
The car blasts down the street to the storage facility.
The three bound out of the car, fists clenched, geared up for ultraviolence.
They storm the reception.
The office is empty - Jo is on her lunch break.
Troy tries the door leading to the garage, it is locked.
So he squeezes through the receptionist window, feels underneath the desk for the door release button.
Tony yanks on the door.
The door buzzes open and the gang, Bobby in the lead, rush into the cacophonous garage.
Cindy presses the telephone to her ear - waiting...
Blue Valentine Official Green Script as of 6/9/09 68.
Dean is all alone in the garage, loading up a truck with reams of cardboard boxes for a big job tomorrow.
Bobby and gang search through a maze of yellow trucks.
BOBBY Hey faggot!
Dean continues his work.
BOBBY (CONT'D) Is your name Dean?
DEAN Who's askin'?
Bobby rushes him, throws a shoulder into his stomach.
They both flail to the floor.
The two lock.
Everything is quick.
Bobby sends a flurry of punches to Dean's ribs and guts.
Dean pummels the back of Bobby's head with blind overhead rights.
It becomes clear that Bobby has the upper hand.
He holds Dean's bloodied head in some kind of jiujitsu headlock.
BOBBY Think I'm dumb?
BOBBY Think I'm that dumb?
Dean struggles to breathe but manages to say...
DEAN I think you're a fucking idiot.
Bobby hits him again, harder.
Harder.
BOBBY Fucking faggot!
- Troy and Tony watch the door and egg Bobby on.
- THE PHONE RINGS OFF THE HOOK in the EMPTY OFFICE.
Cindy's mind is taking her to bad places.
She hangs up.
Tells herself that everything is all right.
Paces her room...
Picks up the phone and dials again.
Troy whistles sharp, warning Bobby that Jo has just arrived.
Bobby kicks Dean while he's down.
Dean is beat and Bobby is running out of breath and strength.
Blue Valentine Official Green Script as of 6/9/09 69.
BOBBY Stay away from her!
DEAN Never.
DEAN Dean is on the floor in the fetal position.
DEAN It takes him a while, but he manages to sit up.
DEAN He feels the inside of his split lip with his tongue.
DEAN He doesn't feel pain as much as he feels tingling and ringing - all over.
DEAN Jo comes in.
DEAN She freezes when she sees him.
JO Dean...
JO Telephone.
It takes Dean a while to get up, but he does.
And it takes him a while to get to the office where his phone call awaits.
Once there, he holds the receiver in his hand for a beat...
DEAN Hello?
Cindy wearing scrubs, picks up the ringing phone.
CINDY Mediplex...
CINDY You are going to need to come in...
CINDY We're going to need to see him...
CINDY I can't diagnose over the phone...
CINDY About 20- 30 minutes...
CINDY Okay?
CINDY ...okay, bye...
CINDY CINDY (reading) (cont'd) Maria?
A Hispanic women, MARIA GUEVARA - robust, 50's - clutches her purse and rises off a waiting area chair.
Cindy smiles.
CINDY (CONT'D) Right this way.
Cindy opens the door and gestures to the examination table.
Blue Valentine Official Green Script as of 6/9/09 70.
CINDY Have a seat on the table, Mrs. Guevara.
Maria has a blank look.
CINDY (CONT'D) Do you speak English?
CINDY (CONT'D) Hablas Ingles?
Maria holds her fingers up, indicating an inch.
MARIA Small.
CINDY Poquito?
MARIA Si.
CINDY Yo tabien.
CINDY De donde eres tu?
MARIA El Salvador.
CINDY So...Tu famalia esta aqui?
CINDY Here?
MARIA No no.
CINDY They're in El Salvador?
MARIA Si....Yo...sola.
MARIA How you say en Ingles?
MARIA Sola?
CINDY Uh...Sola...Alone.
MARIA Si.
MARIA Alone.
CINDY But hopefully not lonely.
Maria hides her face with her hand and lets out a self- pitying giggle.
Cindy looks at her clipboard.
CINDY (CONT'D) So you're feeling some pain in your left breast.
CINDY (CONT'D) Uh...Tu dueles en tu chiche?
Blue Valentine Official Green Script as of 6/9/09 71.
MARIA Si Si.
CINDY Well let's take a look.
Cindy hands her a paper robe.
CINDY (CONT'D) Can you take off tu ropas and pongas...
CINDY (CONT'D) put this on?
CINDY (CONT'D) Okay?
CINDY (CONT'D) Comprende?
Maria nods and takes the robe.
Cindy turns to leave.
CINDY (CONT'D) Lo siento mi Espanol es muy mal.
Cindy leaves the room and gets a drink of water from the fountain.
Dr. Feinberg approaches her from behind.
DR. FEINBERG Busy.
DR. FEINBERG Haven't sat down yet.
DR. FEINBERG Walk with me.
DR. FEINBERG DR.
DR. FEINBERG FEINBERG (cont'd) What do you have?
CINDY A woman in 215.
CINDY Hispanic.
CINDY 53.
CINDY Lives alone.
CINDY Complaining of pain in her left breast.
DR. FEINBERG Uh huh.
DR. FEINBERG I'll be in in a minute.
DR. FEINBERG By the way, I was thinking about you.
CINDY Oh yeah?
DR. FEINBERG Yeah, well I can understand how you might not be able to relocate your whole family up to Riverdale, with your daughter being in school and everything.
DR. FEINBERG But, I was thinking, maybe, you could get an apartment.
DR. FEINBERG Work during the week, drive down on weekends.
Blue Valentine Official Green Script as of 6/9/09 72.
DR.
FEINBERG (cont'd) You wouldn't have to worry about being alone...
We could hang out together.
Grab some dinners sometime.
Cindy blushes and then her brow furrows.
CINDY I'm married.
DR. FEINBERG It's not a proposition, I'm just trying to help.
CINDY I don't remember asking you for help.
He holds up his hands and leaves Cindy alone in the hallway.
She looks at the ground, turns around and walks to Room 215.
Maria sits, still clothed, on the table clutching the robe.
Cindy walks into the room and looks at her.
CINDY What's the problem, Maria?
CINDY Tu sabes?
Cindy pantomimes undoing her shirt.
CINDY (CONT'D) No comprende?
CINDY (CONT'D) Necessita take off tu comisitas.
CINDY (CONT'D) Your shirt.
CINDY (CONT'D) Understand?
Maria nods and undoes her blouse.
Cindy turns her back.
Maria sits slumped with her blouse opened.
Cindy pantomimes removing her shirt fully.
Maria does so and sits with her hand covering her face.
Cindy gestures to her bra.
CINDY (CONT'D) Por favor, Maria.
CINDY (CONT'D) Come on.
Maria unhooks her bra.
A purplish cantaloupe-size abscess grows on her left breast.
Cindy's covers her mouth.
CINDY (CONT'D) Oh my God.
CINDY (CONT'D) Jesus Christ.
CINDY (CONT'D) Maria...
Blue Valentine Official Green Script as of 6/9/09 73.
CINDY (CONT'D) Maria!
CINDY (CONT'D) Que eso?
CINDY (CONT'D) Why didn't you come in sooner?
CINDY (CONT'D) Why did you wait this long?!
CINDY (CONT'D) Eso es muy mal.
CINDY (CONT'D) Very bad.
Maria starts to cry.
CINDY (CONT'D) How could you look at yourself in the mirror and pretend it's not there?
CINDY (CONT'D) How long have you been pretending?
Dr. Feinberg walks into the room.
DR. FEINBERG Cindy.
DR. FEINBERG What's going on here?
Cindy points to Maria.
CINDY Her breast.
CINDY Her breast!
Dr. Feinberg takes Cindy's clipboard from her hands.
DR. FEINBERG I can take over from here.
DR. FEINBERG DR.
DR. FEINBERG FEINBERG (cont'd) Hello Mrs. Guevara.
DR. FEINBERG I'm Dr. Feinberg.
DR. FEINBERG I'm your DOCTOR.
DR. FEINBERG Let me see.
DR. FEINBERG It's OK.
He reaches for the trembling Maria's blouse.
Maria flinches.
CINDY It's probably been growing for years!
Dr. Feinberg turns to Cindy.
DR. FEINBERG Out!
DR. FEINBERG DR.
DR. FEINBERG FEINBERG (cont'd) It's going to be alright, Mrs. Guevara.
Cindy backs out of the room.
Blue Valentine Official Green Script as of 6/9/09 74.
Dean gets out of the Aspen.
The kids honk as they drive off.
Drunk and stoned, he walks to the entrance of the clinic carrying their suitcases.
Dean walks through the lobby and approaches Mimi at the reception desk.
He drops his baggage.
Ma'am you're going to have to bring him in...you have to bring him in...
DEAN Where's my wife?
She hands him an in-patient form.
Dean looks at it.
DEAN (CONT'D) I'm not sick.
Mimi cups her hand over the phone.
MIMI You need to fill that out, sir.
MIMI You can go over there.
Mimi returns to the phone.
DEAN There's nothing wrong with me.
Dean hands her back the clipboard.
MIMI No, you need to fill it out, sir.
MIMI Bring it back up to me when you're done.
DEAN Where's my wife?
Mimi lowers the phone.
MIMI Who's your wife?
DEAN Cynthia.
DEAN Where is she?
Blue Valentine Official Green Script as of 6/9/09 75.
MIMI Are you Dean?
DEAN Yeah, are you deaf or are you just dumb?
DEAN Cindy approaches from the hallway.
CINDY Dean?
Saved you a trip.
CINDY I can see that.
CINDY How'd you get here?
DEAN I got a ride.
Mimi appears behind Cindy.
DEAN (CONT'D) - I was going out of my mind.
DEAN (CONT'D) I didn't know if there's an emergency.
DEAN (CONT'D) I didn't know if Francis was hurt.
DEAN (CONT'D) Did you think about that?
CINDY Frankie's fine...
Dean nods.
He looks over Cindy's shoulder at Mimi.
DEAN Taking pictures?
Mimi sits down at her desk and picks up a ringing phone.
CINDY We're not going to do this here.
CINDY CINDY (to Mimi) (cont'd) Give me a few minutes.
MIMI I'll be right here.
MIMI Don't let him brainwash you again.
Blue Valentine Official Green Script as of 6/9/09 76.
CINDY Live your life.
Cindy walks out of the clinic hefting her bags.
CINDY (CONT'D) Help me.
Dean grabs the remaining luggage and follows, throwing back a look to both Mimi and the Gang-banger.
Dean follows behind Cindy.
DEAN Last night got fucked up, OK?
DEAN I know it.
DEAN I know I'm lazy, I eat too much, I drink too much, I drive you crazy with all my jealous bullshit.
DEAN I fuck up.
DEAN I know I'm clumsy.
DEAN But you're not trying anymore.
Cindy hurls the bags into the back of the car.
Dean helps.
DEAN (CONT'D) Please don't make me be alone.
CINDY Are you drunk?
DEAN I'm OK.
CINDY Can you drive?
DEAN Yeah.
DEAN Let's go.
CINDY No, you go.
CINDY Take the car home.
She hands him the keys.
DEAN You don't think about anyone but yourself.
DEAN Do you?
Cindy walks back to the clinic.
Dean follows close behind.
DEAN (CONT'D) You got no time for me anymore.
DEAN (CONT'D) It all goes to this fucking job.
Blue Valentine Official Green Script as of 6/9/09 77.
You give it all to them.
All these people who don't give a shit about you.
They get the beautiful version of you.
What does your family get?
Nothing.
You come home and you're empty.
You think I don't notice?
You think Frankie doesn't notice?
Her mom walking around like a ghost?
CINDY You know how many sacrifices I make every day.
DEAN You!
DEAN What about me?
DEAN I gave up everything for you.
CINDY I never asked you to!
CINDY I can't take this shit anymore.
Cindy enters through the electric doors.
Dean follows Cindy down the hallway to the employee's lounge.
DEAN Take what?
DEAN What can't you take...
DEAN The truth?
DEAN I know you can't...
DEAN You never could.
CINDY You're right Dean, I can't take the truth...I've had it with the truth or whatever it is you make up along the way and label as truth...
CINDY You win.
CINDY I give up...
CINDY I've been lying to you for a long time.
DEAN Who is it?
CINDY It's me, Dean.
CINDY I didn't want to hurt you.
CINDY But I'm not the person you fell in love with.
CINDY And you won't let me be anything but that person.
CINDY That's why I can't look at you.
CINDY Because every time I do I can't stop thinking about how much I want you to hate me.
CINDY But you're too stupid to see it, and too chicken shit to do anything about it.
Blue Valentine Official Green Script as of 6/9/09 78.
DEAN Wait a second...
He grabs her in a hug.
Her arms are pressed into her side.
CINDY I don't love you anymore...
CINDY Why can't you stop loving me?
He pulls back his fist and swings, hitting the metal locker behind Cindy's head.
He repeats the blows with thunderous rage.
Feinberg enters the room.
FEINBERG What the hell is going on!?
Dean turns and takes a blind swing at Feinberg.
One blow and Feinberg reels against the metal lockers.
He hits the ground with a thud.
His nose gushes blood.
Dean paces around Feinberg like a caged animal.
He pulls down a locker with his hand.
It crashes to the floor.
Cindy kneels over Feinberg.
CINDY I'm sorry.
CINDY I'm sorry.
CINDY Let me see.
FEINBERG You're done.
FEINBERG Leave.
Dean jerks Cindy up off the floor.
DEAN Get up.
She hits Dean with a flurry of flailing fists.
CINDY You son of a bitch!
Punches catch him in the nose.
Cindy bullies Dean backwards with repeated shoves to the chest.
He backs up down the hallway.
Mimi stands in the hallway.
MIMI Oh my god.
MIMI Call 911.
MIMI I'm going to call
The doors slide open and Dean backs outside.
CINDY Give me the keys.
Blue Valentine Official Green Script as of 6/9/09 79.
She digs into his pocket and fishes them out.
She marches to the car, gets in the driver's seat, starts the car - the radio blasts at high decibels.
Dean bangs on the passenger side window.
Cindy flips the lock.
Dean gets in the car.
CINDY (CONT'D) I want a divorce!
She has emptied herself.
Her whole body is numb and it feels as if she is floating in space.
Anger overcomes Dean.
He hits the dashboard with concrete fists.
DEAN I know!
DEAN MOMENTS LATER - Dean and Cindy search for the ring.
DEAN It is lost.
DEAN Music begins to play in reverse.
Various Scenes of the Periera family together...
All kinds of flowers.
Colors, smells.
Freshly arranged.
Dean studies them.
Finds the one's he likes.
And steals them.
We follow Dean from behind - walking down the middle of the street.
He holds the flowers.
Meanwhile, we hear Cindy asking her gramma questions about love and life.
"What's it like to be old?" - "when did men stop looking at you?" She confides her feelings for Dean.
(The responses will be real responses - a real conversation).
Cindy and Gramma sit at the dinner table.
The sound of boiling.
Steam rises out of the pots and pans.
They continue their conversation.
Blue Valentine Official Green Script as of 6/9/09 80.
Dean finds the house.
He straightens himself, walks to the front door, rings the BELL, checks the smell of his hands.
Jerry, bourbon in hand, opens the door.
Dean's face is purple and swollen from the fight.
DEAN I didn't know if it was pot luck so I brought an eggplant.
He points at his face.
Behind Jerry, Cindy peeks out from the kitchen at the end of the hallway.
It is the first time she has seen Dean since the fight.
She is shocked.
DEAN (CONT'D) Face looks like an eggplant, don't it?
DEAN (CONT'D) How you doing sir, I'm Dean.
Dean holds out his hand.
Jerry looks Dean up and down.
CINDY Oh God.
Cindy squeezes by her father to Dean.
The expression on her face says it all.
Dean hands her the flowers, leans in and kisses her.
While he's there he whispers.
DEAN I stole these for you.
CINDY Are you okay?
CINDY JERRY (to Cindy) Tell him to take off his shoes.
Dean removes his boots.
A toe wiggles out of a holey sock.
He gathers the hole and tucks it between his big toe and his second toe.
Cindy leads him by the hand to the kitchen.
The Heller family and Dean sit around the table.
Jerry, Glenda and Gramma bow their heads, saying grace.
Come lord Jesus, be our guest, and let thy gifts to us be blessed.
Amen.
Blue Valentine Official Green Script as of 6/9/09 81.
Glenda continues with a little speech about choices, and needing to be able to make mistakes with our choices.
Her speech continues over the next images...
- They eat.
Dean compliments the meal.
Glenda is self depreciating.
Jerry is judgemental.
Gramma wants to go home.
Cindy can't take her eyes off of Dean - she has fallen.
LATER - Cindy leads Dean upstairs to her room.
Dean follows, obediently.
Cindy closes her door behind him.
She begins gently kissing Dean's wounds.
Whispers.
CINDY Does that hurt.
DEAN No.
DEAN It feels good.
DEAN Keep doing it.
She does and is interrupted by...
The FAINT SOUND of her parents fighting downstairs.
JERRY ...She's going to struggle the rest of her Goddamn life with that fucking loser.
JERRY And that's okay with you.
JERRY Sit there...sit there on your fat ass don't do a goddamn thing.
DEAN Maybe I should go.
CINDY Why?
CINDY They'll stop soon.
DEAN I'm going to miss my train.
CINDY Good.
Cindy goes over to her stereo and turns on some music, low - it is the same song that Dean and Cindy listened to in the moon room.
It drowns out some of the fighting.
She approaches him, starts unbuttoning his shirt.
CINDY (CONT'D) Promise me one thing...
CINDY (CONT'D) you'll never let me become an adult.
Blue Valentine Official Green Script as of 6/9/09 82.
DEAN Okay.
She kisses him.
Opens up his shirt.
Reveals a severely bruised torso.
He winces a bit from the movement.
She redresses his wounds, nursing him back to health.
CINDY That motherfucker.
She kisses his chest.
Dean starts getting underneath Cindy's clothes.
He places his palm on her belly.
DEAN I love you.
CINDY I love you too.
DEAN Really?
CINDY Yeah.
From here on out, their actions increase with urgency.
Each moment that goes by makes them more and more desperate to feel the other's skin.
They are down to their underwear when they hear a door slam downstairs.
DEAN Are your parent's gonna walk in on us?
CINDY They never come in here.
They make sweet love.
The front door bursts open and Frankie, still in her leopard costume, charges down the walkway.
FRANKIE Daddy!
FRANKIE Daddy!
FRANKIE Mommy!
Cindy's car sits in the driveway.
Cindy gets out, grabs her suitcase.
Jerry emerges from the house.
Cindy kneels down and hugs Frankie.
She is electricity in her arms.
CINDY Who had candy for breakfast?
Blue Valentine Official Green Script as of 6/9/09 83.
Frankie doesn't answer and squirms out of Cindy's arms.
She runs to Dean who gets out of the car like a wounded soldier.
DEAN Hey sweetheart.
Frankie leaps into Dean's arms.
Cindy walks up to the house.
CINDY How was Frankie?
JERRY She was good.
JERRY Are you OK?
CINDY I'm OK.
CINDY DEAN (holding Frankie) I can't play right now, okay?
He releases his wired daughter who runs circles around him.
Dean walks up to the porch.
He and Jerry stand face to face.
DEAN (CONT'D) Do you want to get out of my way.
Jerry backs away.
Dean walks past him into the house.
JERRY I don't know what happened up there.
JERRY But please Dean, come on.
JERRY Don't push it.
JERRY Let it be...
Dean closes the screen door behind him and locks it.
Jerry pulls on the door.
Hey!
You can't lock me out of my own house!
Dean calls back.
DEAN Keep an eye on Francis.
JERRY I don't have my oxygen!
JERRY Hey!
JERRY Blue Valentine Official Green Script as of 6/9/09 84.
Cindy puts on a simple yellow dress.
She checks herself in the mirror.
Her hand traces the bump on her belly.
Cindy pours a glass of water.
She gulps down aspirin.
Dean keeps his distance at the edge of the room.
In the backyard, Frankie makes herself dizzy by twirling.
Jerry cranes his neck to look into the window of his house.
CINDY I'm not coming home.
Fear strikes Dean.
He presses the base of his palms into his eyes, rubbing until he sees stars.
DEAN We're not alone here Cynthia.
DEAN We have a little girl.
DEAN We need to think about her.
CINDY I am thinking about her.
DEAN All you're thinking about is yourself.
DEAN You.
DEAN Francis is gonna grow up in a broken home and that's OK with you.
CINDY I can't let her grow up in a home where her parents don't love each other.
DEAN Don't love each other?
DEAN I've only ever loved you.
Dean approaches her from behind.
Reaches out...
Dean wears his baby blue tux.
He looks himself up and down in the mirror.
Takes a deep breath.
Cindy flinches from Dean's touch.
A look of terror in her eyes.
Dean hushes her.
He leads her to a chair and sits her down.
He kneels by her side and repeats her name.
Blue Valentine Official Green Script as of 6/9/09 85.
DEAN ...Cynthia...Cynthia...
He holds her hands and gropes her arms, legs, shoulders whatever she will let him touch.
Cindy has tears in her eyes but she is focused.
There is nothing to say.
Dean takes a quarter, places it in a gumball machine, turns the crank.
A plastic box rolls out.
He takes it, shakes it - inside is a plastic ring.
She takes a quarter and follows suit, buying another plastic ring.
In THE KITCHEN, Frankie climbs in through the old dog door.
She sees her father kneeling on the floor at her mother's feet.
Perplexed, she pulls at her bottom lip with her finger.
Cindy releases herself from Dean's grip and goes to her suitcase.
She carries it up the stairs.
Dean and Cindy wait together in a room filled with other people about to get married.
They observe these other people and create fictional narratives about them and their lives for each other.
Cindy opens the door and sets her suitcase on the dusty bed.
The room is just like it used to be.
Dean is defeated.
He sits back against the cupboards and hangs his head down low between his knees.
Frankie touches his shoulders.
She gives him a massage.
FRANKIE I want to stay at Grampa's house next time for fifty nights.
Dean looks up.
He has tears in his eyes.
Frankie touches one as it streams down his face.
FRANKIE (CONT'D) Why you crying?
Blue Valentine Official Green Script as of 6/9/09 85A.
Dean can't answer.
Frankie slides a chair over to the sink.
She steps up and fills the glass with water.
Balancing it still, she brings it to Dean.
She takes a sip and hands the glass to him.
He drinks.
DEAN Thank you...
Blue Valentine Official Green Script as of 6/9/09 86.
Cindy comes down the stairs.
DEAN (CONT'D) Daddy's gonna go now, OK.
Dean stands and picks up Frankie.
He walks to Cindy and hands her over.
Cindy and Dean stare into each other's eyes.
The JUSTICE OF THE PEACE reads them their vows.
Frankie tries to squirm out of her mother's arms.
FRANKIE Daddy!
FRANKIE Cindy sets Frankie down and she runs out the door.
FRANKIE Jerry catches the little girl by the arm and holds her tight.
FRANKIE FRANKIE (SCREAMS) (cont'd) Daddy!
Dean stops and turns.
Cindy walks to the porch.
CINDY Let her go, Dad.
CINDY Families light fireworks off in the middle of the streets.
DEAN continues down the street that connects with other streets, all lined with pretty houses.
Blue Valentine Official Green Script as of 6/9/09 86A.
The houses form neighborhoods that join with other neighborhoods forming towns.
Beyond the towns, hills stretch far into to the horizon.
Fireworks explode against dark blue on blue.
Blue Valentine Official Green Script as of 6/9/09 87.
Dean and Cindy consecrate their vows.
The ceremony lasts all of 45 seconds.
...
you may now kiss the bride.
Dean and Cindy kiss.
We hold on the kiss for as long as it takes.
They stop kissing and look at each other in the eyes.
Then, they start to hug.
And hug...
and hug...
The title BLUE VALENTINE superimposes on top of the image.
Credits start to scroll over...
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
