LAW-ABIDING CITIZEN
Written by
Frank Darabont & Kurt Wimmer
1 OPENING CREDIT SEQUENCE.
Images and sounds are surreal, 1 dreamlike, disturbing:
A HAND is trying to dial three simple numbers.
Trembling fingers miss, try again...we hear boop-boop-boop.
911 OPERATOR 911 operator, what is your emergency?
The phone rises, gripped tightly.
Knuckles white.
We're TIGHT, it's dark, we see no face -- just slack, trembling lips.
Whoever it is, he can't talk.
All we hear is breathing, all we sense is grief and panic and deep shock.
OPERATOR (V.O.) Hello?
OPERATOR (V.O.) Can you hear me?
OPERATOR (V.O.) Can you speak?
CLYDE ...eyes...
OPERATOR (V.O.) What?
OPERATOR (V.O.) Can you speak up?
CLYDE ...her...eyes...
Lights appear like phantoms over blacktop, flashing.
Police cars coming our way.
OPERATOR (V.O.) Sir, what is the nature of your emergency?
The man can't speak.
OPERATOR (V.O.) Sir?
OPERATOR (V.O.) Are you injured?
OPERATOR (V.O.) Do you need medical attention?
The cars blast by us...
CLYDE ...her eyes...she can't...
POLICE VEHICLES converge in SLOW-MOTION, dreamlike.
Doors fly open, COPS jump out, weapons drawn as WE MOVE with them to:
Front door.
RAMP TO NORMAL CAMERA SPEED as it opens, revealing:
BENSON CLYDE, phone still gripped.
He barely registers the weapons aimed at his face.
CAMERA CLOSES IN ON HIM, as:
CLYDE She can't...close her eyes.
He's pulled from frame.
CAMERA KEEPS MOVING, following COPS into the house...
Dark as hell inside.
And tense.
Arms training weapons.
Moving up a tight hallway, emerging into...
...where the flashlight beams find blood-spatter patterns.
Furniture shattered and overturned.
A kid's sneaker.
The flashlights play across TWO BODIES in the wreckage -- a woman's pale hand, a child's motionless leg.
CAMERA DRIFTS AROUND to the cops' faces, as:
COP #1 Dispatch, we have multiple 10-55s, need full response, 11-41.
Chaotic now, vehicles and lights.
The eye of the storm is Clyde on the lawn, hugging his knees, fetal with horror and grief.
He's screaming at the sky, but no sound is coming out.
EMS TECHS enter shot, steal the frame, race toward the door...
TRACKING SHOT at floor level, photos being taken.
FLASHES bathe the foreground wreckage.
FORENSIC TECHS step gingerly.
Uniformed cops hang grimly back, hugging the walls...
CAMERA BRINGS US TO CLOSEUP: A PROFILE IN DEEP SHADOW in the foreground, face tilted obliquely in the wreckage.
A CAMERA FLASH reveals the face with shocking glare and the IMAGE FREEZES.
A TEN YEAR-OLD GIRL, eyes open, staring at us.
CLYDE (V.O.) Her eyes.
CLYDE (V.O.) That's how they were.
CLYDE (V.O.) Open like that.
CLYDE (V.O.) You see?
Clyde is seated, speaking slowly and precisely.
ANGLE WIDENS, revealing the room, light filtering through blinds, as:
CLYDE When I found my wife and child dead, my little girl's eyes were open.
CLYDE The last thing she saw of this earth were the faces of the men who took her life.
CLYDE Can you understand that?
NICK Yes.
NICK Yes, I can.
CLYDE Can you?
CLYDE Really?
CLYDE You?
CANTRELL Mr. Clyde.
CANTRELL I don't see this helping.
CLYDE No?
CLYDE You married?
CLYDE Children?
ANGLE HAS NOW WIDENED/DRIFTED to include D.A. JONAS CANTRELL, Senior Attorney for the State.
He wears thick glasses and is suffering the early stages of macular degeneration.
CANTRELL Divorced.
CANTRELL I have a son and daughter.
CANTRELL Both in college.
CLYDE My daughter was ten.
CLYDE I married late in life.
Clyde spreads the crime scene photos further on the table.
ANGLE COMES AROUND to reveal the third man in the room:
The D.A. under Cantrell -- focused, exceptional at what he does, the man you'd want on your side.
CLYDE You, Mr. Price?
CLYDE Married?
CLYDE Kids?
Nick doesn't answer, stays focused on the task:
NICK I've seen the crime scene photos, Mr. Clyde.
NICK Many times.
NICK They're horrifying.
NICK But they don't alter the facts of the case.
CLYDE Facts?
CLYDE Those men are guilty.
CLYDE Both of them.
CLYDE You know they are.
NICK This isn't about what we know.
NICK It's about what we can prove in court.
CANTRELL Things have gone against us.
CANTRELL Tainted crime scene, evidence thrown out...
CLYDE Maybe you just haven't tried hard * enough.
NICK Look.
NICK We've had only one real break in this case.
NICK The fact that one asshole has decided to testify against the other asshole.
CLYDE In return for immunity.
CLYDE So he gets away with it.
CANTRELL The other man doesn't.
CANTRELL He'll go down for the crime.
CANTRELL That has to count for something.
CLYDE Yes.
CLYDE It counts for half.
CLYDE Don't reward one of the men who murdered my family.
CLYDE Please.
NICK Mr. Clyde.
NICK I can't claim to know what it's like to be in your position.
NICK Losing your wife and child.
NICK But please try to grasp how limited our options are.
NICK This is how the justice system works.
Clyde sits for a long moment, numb, absorbing this.
CLYDE Ah.
CLYDE I see my mistake.
CLYDE I came for justice.
CLYDE Instead I got a system.
SARAH LOWELL, fresh out of law school, is waiting anxiously for the meeting to end, arms full of file folders.
With her is BILL REYNOLDS, the defense attorney in this case, * glancing impatiently at his watch.
Clyde exits the room fast, not watching where he's going, * accidentally plowing into Sarah as he passes.
CLYDE Sorry.
CLYDE My fault.
SARAH It's okay.
On he goes.
Nick and Cantrell exit the room.
SARAH You're due upstairs in three minutes!
SARAH You're gonna be late!
NICK Thank you, voice of doom.
They move toward the elevators with Reynolds.
Sarah's at their * heels, sensing the tension and keeping her mouth shut.
NICK (to Cantrell) * We doing the right thing?
REYNOLDS * (jumps in) * You even doubt it?
REYNOLDS * C'mon, you didn't just tumble off the fucking truck.
REYNOLDS * Do the math...
Cantrell has trouble seeing the elevator button, misses.
Nick presses it for him.
(This is thrown away without comment; both men are used to Cantrell's bad eyes by now.)
They elevator opens, they get on...
...and ride up:
NICK It's your office.
CANTRELL It's your decision.
Nick shoots him a withering look, glances back at Sarah.
NICK What do you think?
REYNOLDS * What are you asking her for?
REYNOLDS * She's * just an intern.
SARAH (deer in the headlights) * I am just an intern.
NICK You were top of your class at Yale, don't give me that shit.
CANTRELL Young lady.
CANTRELL Someday you might have our jobs.
CANTRELL You know the issues of * the case before the court.
CANTRELL Speak.
SARAH Okay.
SARAH Um.
SARAH You can take both men to trial, spend a year and millions of taxpayer dollars, and probably lose.
SARAH Or you can cut a deal and at least put one of the men who did the crime on death row.
SARAH It's a no-brainer.
SARAH * You make the deal.
REYNOLDS * (smug, to the men) * Duh.
They trade a look.
Cantrell glances to Sarah.
CANTRELL When the day comes that you argue a real case in court, you might refrain from summing up with "duh."
SARAH * I'll avoid that.
JUDGE LAURA BURCH presides.
Nick, Cantrell, Sarah are present.
* CLARENCE DARBY is the focus, Bill Reynolds at his side.
JUDGE BURCH * The agreement has been vetted by both sides?
JUDGE BURCH * Satisfactory to all?
REYNOLDS Yes, your Honor.
REYNOLDS Defense approves.
CANTRELL State also approves, your Honor.
Nick places a document before DARBY, along with a pen.
NICK Clarence Darby.
NICK This document guarantees that you will provide testimony against Rupert Ames in the matter of which you were both accused.
NICK In return, you will be
NICK (CONT'D) shielded from further prosecution for those capital crimes.
NICK (CONT'D) But you will plead guilty to the lesser charge of breaking and entering.
REYNOLDS You'll do a maximum of five years.
REYNOLDS With good behavior, you could be out in three.
JUDGE BURCH That also depends on your testimony and the level of your cooperation.
DARBY Your Honor need not worry on my account.
DARBY I assure the court that I am aware of the opportunity I've been given.
DARBY And I am deeply grateful to all concerned.
Nick gives Cantrell a glance, both stoically enduring this proceeding.
Darby pulls the document closer.
DARBY If I may.
DARBY It has come to my attention that Rupert Ames has been spreading * lies about me to the tabloid press.
DARBY * About certain alleged activities of * which I have no knowledge.
DARBY Sexual and otherwise.
DARBY Libel and slander...yes?
NICK You can always sue him.
DARBY Well, no matter.
DARBY My tongue will wag in court, under oath.
DARBY His tongue will wag in hell.
He puts pen to paper, looks to Nick.
DARBY He'll get the chair?
NICK We don't do chair.
NICK We do needle.
Cathedral-like, pigeons fluttering.
The door from the hallway opens and BETSY, a months-old GERMAN SHEPHERD PUPPY, bounds toward us on a leash pulling Cantrell toward the top of the vast marble staircase.
Nick trails them, nervous as hell:
NICK Whoa, Jonas, take my elbow.
CANTRELL I'm not blind.
CANTRELL Yet.
CANTRELL I'll do it.
NICK You're shitty on stairs.
NICK At least let me take the leash so the dog doesn't pull you down.
CANTRELL No.
CANTRELL She needs to imprint on me.
CANTRELL Not you, not somebody else.
Cantrell starts down.
Nick's at his side, hovering and ready to grab him, jumping at every little lurch Cantrell makes.
CANTRELL That's the whole point of this phase.
CANTRELL She needs to get the idea that she and I are partners.
CANTRELL Then the real training can begin.
CANTRELL Unless you wanna lead me around the rest of my life.
NICK I'll pass.
Nick and Cantrell emerge into daylight and find Darby in the protective custody of a FEDERAL MARSHAL on the courthouse steps, surrounded by a crush of REPORTERS:
DARBY ...it was a burglary gone wrong.
DARBY We thought the house was empty.
DARBY Rupert found the woman and child at home and went crazy.
DARBY I was stoned and in fear of my own life, so I fled...
They catch sight of Bill Reynolds, the defense attorney.
CANTRELL Bill!
CANTRELL You let all your clients give testimony on the courthouse steps?
REYNOLDS Hellooo, kettle to pot.
REYNOLDS Since when do you shy away from publicity?
NICK Since everything in this case has gone sideways so far.
NICK Tell your boy to save it for the courtroom.
REYNOLDS He's your boy too now.
REYNOLDS You tell him.
Reynolds proceeds down the steps...
NICK Asshole.
REYNOLDS Dickwad.
CANTRELL Fuckface.
...and vanishes in the crowd.
Nick glances sourly toward Darby.
DARBY ...and may I say for the record how very sorry I am that I failed to prevent Rupert Ames from committing those terrible crimes...
NICK You good here?
CANTRELL Long as nobody bumps into me.
CAMERA FOLLOWS Nick through the crowd toward Darby...
DARBY ...been given a chance to put the drugs and foul living behind me.
DARBY To atone for my past failings and weakness of character.
DARBY It is a gift given me by God's grace...
Darby sees Nick, grabs his hand, shaking it for the cameras.
DARBY ...and the grace and wisdom of this court.
DARBY I cannot thank you enough, sir.
DARBY I cannot.
A BARRAGE OF CAMERA FLASHES.
Nick caught off guard before the * press, Darby not letting go.
Then Nick sees: *
Clyde, a tiny defeated figure far below, waits at the bus stop.
He's gazing up, seeing this photo op happen.
NICK breaks the handshake with a flush of discomfort, signals the federal marshal:
NICK Marshal, escort your man, please!
NICK Mr. Darby is done here!
Darby is hustled down the steps.
The reporters surge to Nick, surrounding him, shouting questions.
Nick looks over their heads and glimpses Clyde getting on a bus.
The door closes, the bus pulls away...
Nick enters.
Dark.
He drops his briefcase by the door.
REFLECTED IN THE MIRROR: KELL, Nick's wife, is just out of the bath, wearing a robe and toweling her hair.
Nick enters behind her.
She cranes back for a kiss, keeps toweling her hair in the mirror.
He hugs her from behind, buries his face in her neck.
Drained.
KELL Shit day?
NICK Shit day.
NICK Better now.
NICK How's she doing?
KELL Fine.
KELL She drove me a little crazy today.
NICK She was busy?
KELL In overdrive.
KELL Here.
KELL Feel.
He reaches around, slowly unties her robe, pulls it open...
...revealing her pregnant belly.
(Our angles have avoided this till now.)
He places his hand, feeling for movement.
KELL Of course she stops kicking the moment you get home.
SLOW TRACKING SHOT finds them in bed, Nick with his head on Kell's chest.
Pensive.
NICK I had to say some things to a man today I didn't want to say.
NICK And I did something I didn't want to do.
KELL You didn't lie to him.
KELL Or bullshit him.
KELL Or shine him on.
NICK None of those things.
KELL So you had your reasons.
KELL You did what you had to.
KELL It's not your fault the world sucks.
Nick smiles, eases his face to her belly.
NICK You in there.
NICK Listen up.
NICK Your mother just said the world sucks.
NICK You may wanna rethink this whole thing.
NICK My advice?
NICK If you're asking?
NICK Just stay in there.
NICK I promise you, nothing will ever make as much sense as it does right now...
KELL What is wrong with you?
NICK ...plus there's shit you don't need to know about.
NICK Rap.
NICK Internet porn.
NICK Madonna's entire back catalog.
KELL Did someone drop you on your head?
KELL Seriously.
KELL I have swollen ankles and all I do is pee.
KELL That baby's coming out.
NICK Okay.
NICK I'm sure you heard that.
NICK Then again there are the Beatles.
NICK 70's funk.
NICK Louie.
NICK Ella.
NICK Be a shame to miss those.
NICK All right, kid.
NICK Bring it on.
NICK But when you're old enough for the world to disappoint you, I hope you won't blame your old man for bringing you into this mess.
NICK Give me that at least.
Nick and Kell asleep.
She's no longer pregnant -- it's now ten years later.
A long beat of quiet...
A small face peers in from the hallway.
EMMA, their 10 year- old daughter.
She darts in, puts her face to Nick's.
EMMA Dad?
NICK Huh?
NICK Wha--?
EMMA You know what it is?
NICK What?
She jumps up on the bed, bouncing up and down and dancing around, hollering at the top of her lungs:
Nick and Kell are too groggy to do anything but ride it out.
Emma sails off the bed and vanishes out the door, hollering all the way up the hallway:
Nick and Kell are left groping with blankets, heart rates, and consciousness:
KELL Glad it's once a year.
Nick and Emma finishing breakfast, getting ready to leave, Kell packing Emma's lunch at the counter:
EMMA Why can't you be here?
NICK It's a work thing.
NICK Grownup stuff.
NICK You know that happens sometimes.
EMMA But it's...
He claps his hand over her mouth.
NICK I believe we've established that.
NICK I let go, you'll stop reminding me?
NICK We'll celebrate this weekend.
NICK Tonight is all about your friends.
NICK Knock * yourselves out, don't give mom any * grief.
NICK I'll try to be home in time to tuck you in, okay?
EMMA Okay.
EMMA But what are you doing tonight that is more important than...
She's doing that "sneakily drawing close" thing again.
Nick holds up his finger, cautioning her to say it quietly.
EMMA ...my birthdaaaaay.
KELL Something he'd get out of if he could.
KELL Here.
KELL Take lunch.
KELL Grab * backpack.
KELL We go.
Emma grabs her stuff, kisses dad, races from the room.
Kell grabs her keys to follow, kisses Nick goodbye.
NICK Nice evasion.
NICK Thanks.
Cars are traveling an old service road...
Nick's in back with Cantrell.
The years have left Cantrell 90% blind; his glasses are beyond Coke bottle-thick.
BLUE - 9-19-08 14. Between them sits Betsy the German shepherd, now ten years old, wearing a guide-dog harness.
BLUE - 9-19-08 14. She looks miserable wearing a big cone-shaped POST-SURGERY COLLAR.
NICK How long she have to wear this stupid thing?
CANTRELL Till the stitches heal.
CANTRELL Week or two.
Nick dotes on the dog, they're old pals:
NICK Poor honey.
NICK Sucks, doesn't it?
NICK But you're very pretty.
NICK Yes, you are.
NICK Even with a radar dish on your head.
SARAH There they are.
SARAH Like clockwork.
SARAH ANGLE SHIFTS TO Sarah -- much more confident and power-suited than last time we saw her -- riding up front with the driver.
The car pulls up to the gate as CAMERA RISES to reveal the * new facility positioned right next to the old one...
The condemned, RUPERT AMES, is placed against the upright execution table and buckled in.
The table is tilted back to vertical.
All Rupert can do is lay there and watch, as:
MEDICAL TECHS swab his arms with alcohol, prepare the needles, find his veins.
The needles are inserted, taped off.
The I.V.
lines are attached.
Very methodical.
The techs leave the room.
The curtain is drawn aside, revealing the big window that separates the chamber from:
Nick and his colleagues are among SEVERAL DOZEN WITNESSES seated in chairs.
They watch as WARDEN IGER faces Rupert.
WARDEN IGER Rupert Ames.
WARDEN IGER Do you have anything to say?
Rupert doesn't have much of an IQ and he's scared shitless, but he does his best:
RUPERT I'm here.
RUPERT Clarence Darby ain't.
RUPERT And that ain't right.
RUPERT 'Cause that man is evil, ain't no other way to say it.
RUPERT All them things he done, and him turn witness against me for it.
He pauses, trying to untangle his thoughts.
RUPERT I did wrong too.
RUPERT I guess I'll pay up.
RUPERT But it was always him sayin' jump and how high, and I just went along.
RUPERT Now he's killin' me and he got you people to do it.
RUPERT And that's a shame.
RUPERT A goddamn shame.
RUPERT And...
RUPERT ...and I guess that's all.
Nick trades a look with Sarah.
Cantrell is stoic.
Warden Iger nods to TWO GUARDS manning the LETHAL INJECTION MACHINE, on which EIGHT OVERSIZED GLASS CYLINDERS in a vertical row are the main feature, filled with various clear liquids.
There are two switches -- one a dummy, the other live (no way to know which is which).
The guards power up the machine.
Lights activate on the board.
Each man grabs a switch, waits.
Nick watches the wall clock.
It hits 7 o'clock.
The warden * nods and the guards flick their switches, quickly leaving the * room.
The warden follows them out, closes the door.
We hear the pumps quietly activate.
Rupert is taking shallow breaths, terrified...then lays back to wait.
PLUNGER ONE slowly descends, emptying its contents into the I.V.
lines...
Rupert sags as the fast-acting barbiturate spreads through his veins...his breathing slows...his head drops back...
he loses consciousness...
PLUNGER TWO depresses, sending the second vial of liquid into the I.V. lines with a quiet whir of pumps...
PLUNGER THREE activates...then PLUNGER FOUR...the row of cylinders emptying in sequence...
Rupert lies unconscious, just drifting away...
He suddenly comes to.
He draws in a long, shaky breath.
It catches in his throat.
His eyes go wide.
His entire body starts to clench against some increasing pain.
Nick is surprised, uncertain.
Betsy starts GROWLING SOFTLY at * Cantrell's side.
Her head comes up, hackles rising.
Nick glances to the dog...then to Iger, sees the stunned look on the warden's face.
Something is definitely wrong.
The pumps keep whirring, the plungers keep descending...
Rupert he throws his head back, mouth wide...
RUPERT Ah...ah...AH!
The witnesses go tense, confused -- what the hell?
RUPERT Ah--ah--Jesus, don't that HURT!
Rupert looks down at his arms, his expression turning to sheer horror, because: The veins are turning angry red, then blackening, as the liquids course through them...
Those are last coherent words he speaks.
From then on, he's just shrieking and bouncing against his straps, because:
His veins are starting to smoke.
Noxious and foul.
The flesh starts giving away, blood eating though skin like acid.
Shock sweeps the onlookers:
SARAH Oh, Jesus.
CANTRELL What's going on?
CANTRELL Nick?
People are on their feet.
Horror and incomprehension.
CANTRELL Nick, goddamn it, what?
NICK I don't know!
Rupert is fast becoming a horror:
It's going down his arms and legs, up his neck, infusing his ears -- a nauseating discoloration courses through his body, using his veins as a road map, going from red to yellow to black like bruises birthing spontaneously before our eyes...
People in the room scream, turning away.
Nick pushes his way to the viewing glass, shouting at the techs:
The techs dash into the chamber -- but are instantly gagging * and choking on the toxic fumes billowing from Rupert.
They * retreat coughing, pulling the door shut again.
Rupert's screams spew forth toxic fumes...breath blows smoke from his nostrils...eyes liquefy...he's arching against his restraints so hard that bones begin snapping, blood spewing and smoking through his skin...
All Nick can do is stand at the glass in horror as whatever is happening runs its course and the victim collapses in a cloudy, toxic haze...
Drained and waiting: Nick sitting against the town car.
Cantrell across from him with Betsy at his side (the guide dog will always be at his side in this movie, specified or not).
EMERGENCY LIGHTS are swirling all around them.
A PARADE OF PEOPLE descends: DETECTIVE DUNNIGAN, Sarah, Warden Iger, COPS, PRISON STAFF.
Intense:
IGER We're still trying to sort through this thing.
CANTRELL Gentlemen, we face a terrible shitstorm of scrutiny in the days to come.
CANTRELL We need answers.
CANTRELL Start with what we know.
IGER Lethal injection is a series of drugs given in a specific order.
IGER Somebody had to have replaced one or more of those ingredients with something else.
IGER Industrial solvent?
IGER Acid?
DUNNIGAN Let's not guess, let forensics do its job.
CANTRELL * How could the chemicals be switched?
CANTRELL * We're in a goddamn prison!
NICK * I'll ask because somebody has to.
NICK * * Is there any chance, no matter how remote, that this was an accident?
NICK * A mix-up?
NICK * Weird shit happens?
A beat of awkward silence.
The warden hesitating.
SARAH Show them.
SARAH The bad part.
Dunnigan brings our group in.
ELECTRICIANS huddle at an array * of circuits and trunk lines.
In the dancing flashlight beams: *
DUNNIGAN * Some kind of bypass on the phone * lines.
Nick sees a CIRCUIT-BOARD spliced into the wiring.
DUNNIGAN * Twenty minutes before the execution, * the prison stopped receiving incoming calls and emails.
DUNNIGAN * Cell service went * dark too.
DUNNIGAN * Signal was probably jammed.
SARAH * The bad part.
SARAH * I was just on with the Governor's office.
SARAH * He commuted Rupert Ames' sentence.
SARAH * They were trying to call us to stop the execution.
SARAH * They couldn't get through.
Nick and Cantrell are stunned as this sinks in.
DUNNIGAN The Governor's incoming number triggered this device and shut out any further calls.
Cantrell removes his glasses, rubs his eyes.
Softly:
CANTRELL Oh, fuck me.
CANTRELL Fuck me.
DUNNIGAN * One more thing.
Dunnigan aims his maglight and swings the junction box cover all the way open.
Scrawled on the inside of the door in red are the words: "HIS TONGUE WILL WAG IN HELL."
DUNNIGAN This mean anything to you?
CAMERA PUSHES IN on Nick...
Nick's LAPTOP sits on an unmarked car, streaming the D.A.'S DATABASE by wireless.
Nick taps the keys, as:
NICK Clarence Darby.
NICK That's what he said when he agreed to testify against the man we executed tonight.
DUNNIGAN "His tongue will wag in hell."
DUNNIGAN Those very words?
DUNNIGAN It was ten years ago.
SARAH I remember it too.
SARAH Some things stick in your head.
NICK Check the court transcripts, they're public record.
DARBY'S MUGSHOT (ten years ago) scans up, along with pertinent * info of that time.
GARZA, Dunnigan's partner, peers at it.
GARZA * I know this prick.
GARZA * I'm pretty sure * he's one of our C.I.s.
Surprised looks are traded.
DUNNIGAN You think, or you know?
GARZA That's not the name he uses now.
GARZA * But I'm pretty sure he's one of Bernstein's informants.
DUNNIGAN Okay, raise Bernstein, I want everything he's got, including an address.
DUNNIGAN We roll with tactical.
NICK How about I ride-along?
NICK Give you a fast, accurate ID on this guy?
CANTRELL Is that necessary?
NICK You said yourself we should move fast.
NICK This thing'll be all over the morning news cycle.
NICK We'd all look a lot better if we have the right man in custody by then.
Off Cantrell's look...
AERIAL SHOT: ANGLING DOWN to find a CONVOY OF POLICE VEHICLES speeding across a bridge.
Garza driving.
Dunnigan riding shotgun.
Nick in back, putting * on a tactical vest.
A transmission comes over the car's * dashboard computer: a MURKY NIGHTTIME SHOT OF A MAN in * sunglasses and Hawaiian shirt.
GARZA That's him.
GARZA "Wayne Dunlap."
DUNNIGAN Is that Clarence Darby?
NICK I think so.
NICK Hard to tell.
Dunnigan scrolls the classified police data pertaining to the informant: dates, number of convictions attributed...
DUNNIGAN Jesus, look at this.
DUNNIGAN No wonder Bernstein loves him.
GARZA We scored a lot of good intel off this fuckhead through the years.
GARZA Almost a shame to bag the guy.
A snort from Nick.
The cops glance back.
NICK A shame?
GARZA He's helped us put a lot of bad people behind bars.
GARZA Look.
GARZA Arrests, convictions...
NICK I can read a C.I. profile.
NICK What I see is an asshole dirty up to his ears in the drug trade.
NICK So you cops look the other way?
NICK He gets a free pass as long as he keeps feeding you convictions?
DUNNIGAN Isn't that what you did ten years ago?
DUNNIGAN Give this guy a free pass in return for a conviction?
DUNNIGAN Maybe we played this asshole to our advantage on the street, but you're the one who put him there.
DUNNIGAN So, no offense, but you might wanna go fuck yourself a little.
Nick stares at the man on the dashboard computer screen...
...who is indeed Clarence Darby, naked and drenched with sweat, * taking a hit off a crack pipe.
A woman's HAND flails up into frame, trying to grab for it.
DARBY Wait...wait...
He sucks in a full breath, hands the pipe off to: LISA, the thin tattooed skank he's got bent over his bed and is fucking from behind.
She flares the bowl with a lighter, barely registering any reaction as he keeps pumping her.
DARBY Almost.
DARBY Almost.
LISA This shit makes you soft, baby.
DARBY Thank you...for stating the obvious...you...bitch...
He grits his teeth.
Screams.
Finishes.
He sags, catching his breath, and glances at the PLASMA TV SCREEN, which has been playing silently.
He grabs the remote, unmutes the set:
NEWSCASTER (V.O.) * ...rumors the execution did not go well due to technical flaws, but that has yet to be confirmed...
DARBY "Did not go well."
DARBY Way to go, Rupert.
DARBY You even fucked up dying.
LISA You know that guy?
DARBY Knew.
DARBY Past tense.
CELL PHONE RINGS, he answers.
VOICE Wayne?
DARBY Depends.
DARBY Who's this?
VOICE Somebody who doesn't want to see you in jail.
VOICE Look out your window.
VOICE Argue later.
VOICE Do it now.
Darby goes to the window.
Headlights in the distance.
Lots of them.
He grabs binoculars off the sill.
All cop.
Racing this way.
No lights, no sirens.
DARBY lowers the binoculars, stunned.
VOICE There's a world of shit coming your way.
VOICE I'd get out the back.
VOICE Now.
Click -- line dead.
Darby frozen for a moment, looking around at all the drugs and paraphernalia.
He scrambles, tossing on his pants, grabbing his shirt.
Lisa jumps off the bed --
LISA What?
She goes to the window, sees cars sweeping from the darkness.
LISA Are those fucking cops?
Darby lunges to a bookcase, grabs a REVOLVER from behind the * books, sails out the bedroom door...
...and races down the steps with Lisa at his heels.
LISA You ain't leaving me here!
She catches him halfway across the room, holding him back.
He smashes the gun into her face repeatedly...
...and knocks her bleeding and crying to the floor.
He sails on through the kitchen, leaving her there...
...and bursts through the screen door, fleeing barefoot across the back yard as VEHICLES AND COPS swarm the front of the house.
A cruiser nails him with a spotlight:
COP VOICE You!
COP VOICE Freeze right there!
Darby, never slowing, swings his arm around, FIRING his revolver blindly at all the lights...
...whoa, fuck, gunshots!
Cops scramble and dive.
Nick has just gotten out of Dunnigan's car -- a cruiser's window takes a blind hit nearby, exploding glass.
Nick ducks, total shock, * out of his element.
Drawing, Dunnigan throws him to the ground.
Darby runs like an amped-up rat in a maze, hearing cop cars in the night: Engines ROARING, tires SQUEALING...
Suddenly, the SOUND OF A HELICOPTER above.
Darby dashes for cover against a garage, lost in shadow.
A massively bright searchlight sweeps from above, probing...
Darby crouches, heart hammering, watching the searchlight scan over rooftops.
His phone RINGS, he answers:
VOICE Ditch the gun.
VOICE Wipe the prints.
DARBY Kiss my ass.
VOICE I heard six shots.
VOICE Revolver?
VOICE Bring extra ammo?
Darby glances at the gun, realizing.
He bangs his head back against the garage wall in frustration -- fuck!
VOICE You shot at cops.
VOICE That's attempted murder if they find the gun on you.
VOICE You're in deep enough without that.
Darby frantically wipes the gun with his shirttail, as:
VOICE You'll need my help getting out.
DARBY What'll it cost me?
VOICE We'll discuss terms later.
VOICE Go south, across 10th.
VOICE Past the El tracks.
VOICE Alley behind the clinic.
DARBY What's there?
VOICE A cop.
VOICE Take his ride, he won't give * you any trouble.
DARBY How do you know?
VOICE 'Cause I tasered his ass.
VOICE You gonna keep asking questions?
Click -- line dead.
Darby breaks cover, heaves the gun into somebody's yard, keeps moving...
Chaotic with cops and lights.
Lisa is dragged out, shrieking and bleeding, her face a broken mess.
ANGLE TO Nick watching it all unfold.
He sees Dunnigan approach:
DUNNIGAN No way he's getting out of this neighborhood.
Darby finds a POLICE CRUISER parked in the moonlight, window down.
Dark inside.
A LOCAL COP is sprawled across the front seat...groaning, coming to.
Darby jumps in, passenger side, wrestles the cop upright.
He yanks the cop's service revolver, slapping him awake.
DARBY Drive.
Darby reaches over and keys the engine to life.
DARBY Drive, fucker!
DARBY I'll put your brains on the dash!
COP Don't shoot!
COP Don't hurt me, okay?
DARBY Depends on you.
DARBY Go.
The cop hits the gas.
Tense moments go by as they accelerate up a dark road.
Darby ducks as COP CARS stream past.
Dunnigan and Nick tense, hearing a VOICE over the radio:
COP VOICE ...air unit three...see no sign of suspect...think we lost him...
DUNNIGAN Keep sweeping the area, unit three.
DUNNIGAN Go house-to-house.
DUNNIGAN Check everything.
DUNNIGAN * Garages, dumpsters, storm drains...
NICK * You gotta be kidding me.
Dunnigan -- angry, at a loss -- doesn't reply.
Cops are * scrambling in all directions.
Nick turns, steps TOWARD CAMERA INTO A TIGHT SHOT, gazing off * into the darkness.
Something very weird just happened here, * but he has no idea what.
Softly: *
NICK * How could we lose him?
Tracks and factories, remote and deserted.
Far away, the POLICE COPTER is still buzzing, searching...
The police cruiser appears, stops.
Darby emerges with gun and * flashlight leveled, motions for the cop to get out.
The cop * complies with hands raised, shaking.
DARBY In the ditch.
COP ...please...don't kill me...
DARBY Knees.
DARBY Let's go.
Darby shoves him stumbling into the ditch.
The cop sinks to his knees and starts to weep.
COP I'll never see my wife and little girl again.
COP I'll never see them.
DARBY It's fucked up.
Darby steps closer, draws the hammer back, takes aim for a head shot...but his PHONE RINGS.
He pulls it fast.
DARBY This my guardian angel?
DARBY Hello?
On his knees in the muck, the cop's quiet weeping becomes soft laughter.
He brings up a cell phone, speaks into it:
COP I see you got out okay.
Darby draws back, confused, gun still aimed.
The cop snaps his cell phone shut, rises to face him.
COP You know why I'll never see my wife and daughter again?
He takes his hat off, peels his moustache away.
Darby pins him with the flashlight, finally and fully revealing:
BENSON CLYDE You took them from me.
Recognition floods Darby.
He pulls the trigger, and:
BLUE - 9-19-08 27. Nothing.
BLUE - 9-19-08 27. Just a click, Darby freezing, a hiss of pain.
BLUE - 9-19-08 27. Not comprehending.
BLUE - 9-19-08 27. Clyde reaches for the gun, pries open Darby's fingers, pulls it from his grasp...
BLUE - 9-19-08 27. revealing the TINY NEEDLES that sprang from the pistol's grip into Darby's palm.
BLUE - 9-19-08 27. Darby stares at his perforated palm.
BLUE - 9-19-08 27. His knees give out and Clyde catches him, eases him to the ground.
ANGLE: A head encased in a hood.
The hood is pulled off, revealing Darby -- eyes wide, lying on a rough table.
Benson Clyde leans over him, checks his pupils.
CLYDE Can't speak?
CLYDE He displays the prop gun rigged with the needles.
CLYDE Tetrototoxin.
CLYDE Fascinating stuff.
CLYDE It paralyzes you, but leaves all other neurological functions intact.
He sets the gun down, starts rooting through some instruments that Darby can't see (though he's straining to).
CLYDE That means you can't move.
CLYDE Or talk.
CLYDE But you can see.
CLYDE Hear.
CLYDE Feel.
CLYDE That last one's important.
CLYDE Feel.
CLYDE You can feel everything.
CLYDE Got some other items here.
CLYDE Drugs to revive you in case you pass out.
CLYDE Stuff like that.
Darby almost manages to speak, thrashing weakly.
Clyde leans over, checks his pupils again.
CLYDE Wearing off a little.
CLYDE No worries.
He tucks a padded block under Darby's head like a pillow, raising his head so he can see better.
Clyde moves down the table, tightens straps holding Darby down.
But the worst part:
TOURNIQUETS are tied on Darby's arms and legs at various points.
Darby sees them and starts hyperventilating.
CLYDE Oh.
CLYDE These.
CLYDE Don't want you bleeding out.
CLYDE This will take a while.
Clyde puts on a thick coat, like a meat-packer's.
He returns, sorting implements, Darby trying to see.
Clyde obliges him, holding things up:
CLYDE Teeth.
CLYDE Balls.
CLYDE Fingers.
CLYDE Maybe toes.
CLYDE Eyelids.
CLYDE In case you insist on shutting your eyes.
Darby's screaming -- but with the tetrototoxin in his system, all that's coming out is air, like a slow leak.
Clyde picks up an object, unfolds it -- a full-body plastic coat.
He puts it on over his other coat, as:
CLYDE Earlier on the phone?
CLYDE I said I'd get you out?
CLYDE You asked me what it would cost?
CLYDE Well.
He finishes buttoning up, crosses back to the table, raises a new object into view: a CIRCULAR POWER SAW.
CLYDE We'll start with an arm and a leg.
CLYDE Go from there.
Pause.
The reality of what he's about to do washing over him: *
CLYDE I've been waiting to say that line * for years.
CLYDE But it wasn't very funny, was it?
CLYDE No.
CLYDE Played much better in my head.
CLYDE Maybe it's my delivery.
He puts a construction-site face protector atop his head, the kind with a full plastic face shield that can be flipped down.
He turns and undoes the slipknot of a laundry cord stretching * up to the ceiling.
He feeds the cord and a full-length mirror * tilts down horizontally above the table.
Darby finds himself * staring straight up into it -- he'll see everything.
The CAMERA'S LCD SCREEN looms large in our shot.
The LCD is dark, the camera inactive.
It's mounted high on a tripod, aimed down at the table.
Clyde approaches b.g., pauses.
CLYDE Gosh.
CLYDE My heart's beating.
CLYDE You?
He flips his visor down -- dark, no face visible.
He reaches up, turns the camera on.
The LCD screen activates.
ANGLE CLOSES IN until all we see is:
THE LCD IMAGE.
Grainy in low light.
Clyde, now faceless behind the visor, crosses to the squirming figure on the table.
We hear the CIRCULAR SAW BUILD TO A HIGH SHRIEK...
...and the SHRIEKING SAW FADES...
THE BLACKNESS OPENS UP -- we're in a cop car's trunk looking up as the lid is opened.
A FIGURE in a meat-packing coat looms over us, faceless and scary behind a dark face protector.
ANGLE INTO TRUNK                                                   * reveals OFFICER HILTS hand-cuffed and duct-taped.
He's spent * the night in here.
He recoils, terrified and blinded by glare.
The figure opens a wicked-sharp butterfly knife, CLICK-CLACKS it open.
He leans down, slits the tape binding Hilts' arms, drops the keys in the cop's hands.
The police cruiser sits on a dirt road, a FEMALE DISPATCHER'S VOICE issuing softly and incessantly from the radio:
FEMALE VOICE ...unit twenty one, come in...unit twenty one, please respond...report your location...
The mysterious figure strides from the police cruiser to a MIDNIGHT BLUE 1965 LINCOLN CONTINENTAL in superb condition, shrugging off his thick coat.
He gets in, hits the gas.
Hilts struggles to uncuff himself in the cruiser's trunk, * arms and legs cramping, as: *
The Lincoln becomes a CLOUD OF DUST receding in the distance...
Cleaning up the aftermath of the party: Nick up on a step- stool taking down the birthday banner; Kell in her robe feeding the dishwasher; Emma zooming in and out shuttling paper plates and plastic cups into a big trash bag...
EMMA ...and while we were singing karaoke, Ashley was all dancing around and jumping up and down and suddenly she gets this look on her face...
KELL I saw it coming.
EMMA ...and suddenly she just went barf.
EMMA Total puke moment.
EMMA And we were all like, ewwww gross!
EMMA It was so funny...
She's out of the kitchen to grab more stuff.
Kell starts preparing a bowl of cereal for Emma.
KELL Funny for her.
KELL I cleaned it up.
NICK I had my "ewwww gross" moment last night too.
KELL Hey.
KELL I had a house full of shrieking ten year-old girls.
NICK Hey.
NICK I saw a guy's veins dissolve.
KELL Honey.
KELL It's not a competition.
KELL Okay, you win.
Emma re-enters, dumping more trash:
EMMA ...so Tara says that's what you get for eating too much cake and that almost made Ashley puke again...
The DOORBELL RINGS.
Kell glances out the window.
KELL Delivery.
EMMA I'll get it!
She runs out.
Nick comes off the step-stool, gratefully accepts a cup of coffee from Kell.
He suddenly freezes, notices:
The kitchen TV is playing CNN: a top-of-the-hour story on the Rupert Ames execution and foul-up.
NICK Oh, shit.
NICK We've gone national.
At the front door, a MESSENGER hands Emma a GIFT BASKET trailing mylar balloons with "Happy Birthday Emma" on them.
EMMA Thank you!
She closes the door, turns toward us, finds a CARDBOARD ENVELOPE on the basket -- a card?
She opens it, finds:
Not a card.
An unlabeled DVD.
LOCAL SHERIFFS (not city cops) are spreading out across the * fields, beating the grass, looking for clues...
ANGLE TO Officer Hilts, blanket-draped and still rattled by his night-long ordeal, being interviewed by a SERGEANT:
SERGEANT ...the suspect who tasered you last * night...was it the same person who * let you out of the trunk this morning?
HILTS I never saw a face...either time...he wore a thing, a face shield...
Suddenly, we hear a DISTANT VOICE shouting in panic:
VOICE Sergeant!
VOICE Sergeant!
Everybody's gaze snaps up, tense.
Across the fields, a YOUNG COP is stumbling away from a distant farm shed, pointing: *
YOUNG COP Come quick!
YOUNG COP You gotta see this!
Nick at the table with Kell, riveted to CNN: STATE OFFICIALS, including Iger, are being grilled in a media frenzy.
Cantrell was right, it's a shitstorm of scrutiny...
Emma, munching her bowl of breakfast cereal, slots the DVD in the player.
She backs up, hits play with the remote.
An IMAGE appears on screen, grainy.
Emma looks perplexed.
It's not a normal DVD -- more like a bad home movie:
A figure in a plastic coat and face shield turns from the camera to a table, where another man is strapped down.
The first man raises a circular saw.
The man on the table is thrashing weakly, trying to move.
Emma still has no idea what she's looking at.
Suddenly:
The man with the saw makes a quick sweep across the table, across the other man's leg at the shin.
The move was so fast and casual that it's taking a moment to sink in:
Emma stands frozen, clutching her cereal bowl.
EMMA Daddy?
B.G., we see Nick lean back in his chair, reacting to her tone of voice...and by what sounds like a shrieking saw.
On screen, the man with the saw picks up the severed limb and shows it to the victim.
It's been lopped off below the knee.
Emma drops her bowl -- it shatters at her feet.
Nick and Kell enter behind her, confused, not sure what they're seeing...
On screen, the man with the saw lops off the victim's forearm.
KELL Oh my God!
Emma turns, throws herself into her parents' arms.
They drop to their knees, shielding their sobbing daughter.
PUSH IN ON them staring at the shrieking saw...
KELL What the hell is this?
KELL Jesus Christ, Nick!
KELL Turn it off!
KELL Turn it off!
KELL It's okay, baby, I'm here...
Nick lunges to turn off the TV as:
The door is swung open in a blaze of sunlight.
The local cops enter with pistols drawn and shotguns leveled.
Faces go stark with horror as their eyes adjust.
SERGEANT Oh my Lord.
A RECORD is pulled from a sleeve.
An old-school vinyl LP.
Cops easing in.
ANGLE SWINGS QUEASILY AROUND as they enter, WIDENING to reveal a scene of nightmare intensity: Blood everywhere.
Streaks.
Spatters.
And body parts.
Strewn and discarded.
Intestines nailed to the rafters overhead.
A RECORD PLAYER NEEDLE DROPS, hits the groove with a HISS of vinyl.
MUSIC STARTS TO PLAY LOUDLY, BOOMING through the space.
FOCUS REMAINS WITH the spinning record.
An OUT-OF-FOCUS FIGURE in a rolling chair pushes away from the record player and sails across the room toward a brightly-lit work table...
Cops are covering their mouths with handkerchiefs, gagging.
The stench is incredible.
Flies are buzzing and swarming.
One cop turns away and doubles over, trying not to puke.
The Sergeant moves cautiously forward, finds: A HEAD.
On the wooden dissection table.
Clarence Darby, not that you'd recognize him.
His eyes are gone.
His lips are missing.
His teeth...well, most of them are scattered about.
A MINIATURE CIVIL WAR SOLDIER is held in extreme magnification before us under a tabletop magnifier, the tip of a paintbrush delicately evoking stunning detail...
Emma is still sobbing into her mother's arms as Nick takes the frame f.g., shouting into the phone:
NICK My daughter is traumatized!
NICK She's * only ten!
NICK It's a goddamn snuff film!
NICK * In my home!
GARZA Price got a video of it happening delivered to his house...
Dunnigan enters frame f.g., snatches up his extension.
He listens for a few beats, trying to get a word in:
DUNNIGAN Yeah, we know.
DUNNIGAN Nick, we know.
DUNNIGAN The body's been found.
DUNNIGAN The pieces, anyway.
DUNNIGAN Call just came in.
DUNNIGAN In some old shed on a farm outside * the city.
DUNNIGAN About a hundred and fifty acre piece of property.
NICK Belonging to who?
A GIANT EYEBALL stares at us, unnaturally magnified by a tabletop magnifier.
The lens is swept aside, revealing:
Benson Clyde.
In addition to the tabletop magnifier, he's wearing MAGNIFYING LENSES on his head.
He examines the figurine with his naked eye, then flips the glasses down to continue...
VEHICLES race along two-lane blacktop: CRUISERS, UNMARKED CARS, TACTICAL VANS.
A POLICE HELICOPTER skims along just above them at scary-low altitude...
The cars veer off pavement and up a dirt road, kicking up an awesome trail of dust as the copter sweeps wide, pacing...
Tense faces: Dunnigan, Garza, Nick.
Clyde pauses, hearing a RUMBLE under the music.
Glances up as the rumble passes overhead -- a helicopter?
He clicks on a tiny fan, holds the figurine under it, giving it a final dry.
A shitstorm descends: vehicles swerving in, COPS jumping out, machine gun-toting SWAT TACTICAL TROOPS pouring from vans...
Clyde, still holding the figurine under the whirring fan, leans to one side in his chair, glancing out the window.
He glimpses scurrying figures behind cars, cops darting and surrounding the house, motioning with hand signals...
He holds up the figurine for a final look.
Satisfied with it, he places it onto:
A CHESSBOARD -- the last piece.
All the others are also hand- painted, gorgeous.
Real craftsmanship here.
He stands.
Calmly moves to the middle of the room.
Kicks off his shoes.
Peels off his shirt and undershirt.
Even takes off his pants.
There will be no confusion about hidden weapons.
He positions himself, very precise and purposeful.
Lifts his hands high above his head.
Presenting himself.
Waiting.
Then, bam: doors EXPLODE in and windows SHATTER as the SWAT tactical troops storm the room, bad-asses in black, machine guns aimed, encircling him, everybody shouting:
Clyde is the calm eye of a pissed-off storm of highly professional cops with itchy trigger fingers.
He remains serene, looking around at them, hands raised high...
He compliantly goes to his knees, then prone, offers his hands behind his back.
They move in, cuff him, as troops spread throughout the house yelling "Clear!"
Nick, wearing his kevlar, follows Dunnigan and Garza.
Nick glances over and sees a perfect 1965 midnight-blue Lincoln Continental in the carport...
Clyde is pulled to his feet just as Nick enters.
UNIFORMS spread out, securing the house.
Dunnigan faces Clyde...
DUNNIGAN Benson Clyde.
DUNNIGAN You have the right to remain silent...
...as the full Miranda is read, Nick and Clyde have their eyes locked throughout -- this moment is all about them...
DUNNIGAN ...understand your rights as I have explained them?
CLYDE Yes.
Clyde is hustled outside, leaving Nick with Dunnigan and Garza in the farmhouse -- it's renovated, clean, very loft-like.
Nick drifts to the table, sees the chess board, can't help admiring the pieces.
Then his eyes go to a floor-to-ceiling bookcase.
He's stunned to realize: they're all law books.
GARZA Check this shit out.
Nick turns, moves to Garza's side.
Dunnigan joins them.
All three staring at a wall.
ANGLE SHIFTS around to reveal:
The long-ago PHOTO (clipped from a newspaper) of Nick and Clarence Darby shaking hands on the courthouse steps.
ANGLE WIDENS to reveal:
Photo after photo.
The crime scene photos...photos of Clyde and his family in happier times...photos clipped from magazines and newspapers about the murder and trial...all very neatly and precisely arrayed.
The entire wall covered with them.
THE MUSIC KEEPS BOOMING from the record player.
Dunnigan turns * TIGHT TO CAMERA and yells:
Clyde sits alone and isolated in a small room.
WIDEN to reveal Sarah at the observation glass.
She turns as Nick steps up.
SARAH He says he'll only talk to you.
Nick and Dunnigan prepare to go in.
Dunnigan takes off his gun and holster, lays them on a table, as Garza activates the VIDEO.
Cantrell finds a chair by feel, sits down, as:
Nick and Dunnigan enter.
Dunnigan melts into a corner to observe as Nick sits across the table from Clyde.
CLYDE Counselor.
NICK Mr. Clyde.
CLYDE Why so formal?
CLYDE We go way back.
CLYDE Call me Benson.
CLYDE Or Ben.
Nick sits across the table from Clyde, settles in.
NICK Well.
NICK I'm here.
NICK So?
CLYDE So.
CLYDE Maybe you can explain what this is all about.
Nick almost laughs -- not what he expected to hear.
NICK I think that's obvious.
Clyde spreads his hands questioningly -- not really.
DUNNIGAN You murdered two people.
DUNNIGAN Rupert Ames and Clarence Darby.
CLYDE Detective...?
DUNNIGAN Dunnigan.
CLYDE Dunnigan.
CLYDE I thought I'd made it clear I would only speak to the gentleman across the table from me.
Dunnigan glowers at him, looks to Nick.
NICK You murdered two people.
NICK Rupert Ames and Clarence Darby.
CLYDE Darby?
CLYDE I knew about Ames, of course.
CLYDE I've been following the news about his horribly botched execution.
CLYDE But Darby too?
CLYDE Quite a coincidence.
DUNNIGAN Cut the shit.
DUNNIGAN We know you did it.
DUNNIGAN Save everybody a lot of time and trouble and just confess.
CLYDE Are you going to continue to insist on being part of this conversation?
DUNNIGAN Yes.
CLYDE Fine.
CLYDE Far be it from me to be rude.
NICK Clarence Darby was found on your property.
NICK Old abandoned shed?
CLYDE I didn't know I had one.
CLYDE It's 150 acres, uncultivated.
CLYDE The other day I found a creek I never knew I had.
CLYDE Hunters trespass all the time.
CLYDE You going to try to pin the dead deer on me too?
SARAH I don't believe this guy.
CANTRELL That man is frosty.
CLYDE It occurs to me that an even moderately clever person could try to frame me for the murder simply by killing him on my property.
CLYDE One of Darby's drug rivals?
CLYDE That's an unsavory world.
CLYDE A jury would have to weigh that possibility.
CLYDE What else you got?
NICK How about video of you dismembering Darby while he was still alive?
CLYDE That's odd.
CLYDE See, if I were to do such a thing, I'd probably wear something so I couldn't be identified.
CLYDE Some kind of mask maybe.
CLYDE But you say it's actually me on the video?
CLYDE Did the camera capture my good side?
Nick snaps, lunges across the table, grabs Clyde.
NICK You sick fuck, you sent it to my house!
NICK My daughter saw that video!
NICK It fucking traumatized her!
NICK She couldn't stop sobbing!
Dunnigan moves in fast, trying to pull Nick off (but failing):
DUNNIGAN Whoa-whoa, Nick, ease off!
CLYDE No trouble here, Detective, we're fine.
CLYDE Thank you, though.
Dunnigan backs off.
Clyde turns back to Nick, who's still got him in his grasp, their faces close.
CLYDE Your daughter is, what, ten now?
CLYDE That's a wonderful age.
CLYDE My daughter was always so busy at that age, so interested, so into everything.
CLYDE Jumping around.
CLYDE I called her "Bean," she jumped around so much.
Nick is easing off by inches, subtly and ineffably weirded- out, unable to break Clyde's gaze.
Softly:
CLYDE I am sorry, Nick, that your daughter experienced that.
CLYDE You're right.
CLYDE That video should not have arrived that way.
CLYDE The person who sent it should have thought twice.
Dunnigan moves in again, gently but firmly pulls Nick away.
DUNNIGAN Okay, enough.
CLYDE Unless there's hard evidence tying me to these crimes -- forensic or otherwise -- why am I here?
CLYDE Why are we having this conversation?
NICK We know you did it.
CLYDE It's not about what you know.
CLYDE It's about what you can prove in court.
CLYDE Your words.
CLYDE Like when you called it a justice system.
CLYDE You know the thing about a system, Nick?
CLYDE Any system can be played.
NICK You think you can play us?
NICK You gonna take me on?
CLYDE Clarence Darby did.
CLYDE And I'm much smarter than he was.
CLYDE Or you.
Nick advances, furious, held back by Dunnigan:
NICK I'm gonna bury you, fucker!
CLYDE That's it, that's what I want!
CLYDE That fire in the belly!
CLYDE That's what I wanted ten years ago!
CLYDE Do it, Nick!
CLYDE Bury me!
DUNNIGAN Sit down!
DUNNIGAN Sit the fuck down!
Clyde does, settles in, speaking calmly:
CLYDE Or.
CLYDE Set me free.
NICK What?
CLYDE Did I stutter?
CLYDE Make your case.
CLYDE Or.
CLYDE Shake my hand on the courthouse steps and send me on my way.
CLYDE I'll even make it easy on you.
CLYDE I will confess, how's that?
NICK You're gonna confess.
CLYDE Let's start tomorrow after a good night's sleep.
CLYDE We'll all be fresh and rested.
Nick paces agitated, with the group: *
SARAH * Ten years he's been planning this?
SARAH * * Patient people make me nervous.
SARAH * This?
SARAH * This freaks me out.
DUNNIGAN * Is he serious about confessing?
DUNNIGAN * * What's his deal, is he crazy?
NICK Confession or not, we're gonna nail him on two counts of first-degree.
CANTRELL Agreed, but softly.
CANTRELL Nothing hard- ass, no grand-standing.
CANTRELL Kid gloves.
NICK Kid gloves?
NICK He's a psycho with a power saw.
CANTRELL Depending on who's writing the headline, he's a grieving husband and father who got revenge on the men who murdered his wife and child.
CANTRELL Public sympathy is to be respected and feared.
CANTRELL This could blow up in our faces if we're not careful.
CANTRELL We can't look like we're pissed off or have an ax to grind.
CANTRELL Are we pissed off?
CANTRELL Do we have an ax to grind?
NICK No.
CANTRELL Then stop acting like it.
Beat.
Nick takes a deep breath.
NICK Okay.
NICK He got under my skin a little.
NICK That's done.
STEADICAM TWO SILHOUETTES: We're following Nick and Sarah through one of the pedestrian tunnels to the street:
NICK ...background check's gotta be thorough, I want to know everything there is to know about this son of a bitch.
NICK Get all the ADAs on it, tell 'em I better not see them sitting around on their asses or texting their pals...
SARAH How about outside help?
SARAH That P.I.
SARAH who helped us on the Jacovitz case?
NICK Yeah, he was good.
NICK And Hanson's * always reliable.
NICK But try to limit their hours, okay?
We find a MERCEDES at the curb -- Kell at the wheel, Emma in back.
Nick gets in.
Sarah leans down, happy to see them.
Emma's face lights up -- the little girl obviously adores her.
KELL Well, hello there beauty!
SARAH Hey Kell!
SARAH Hey Emma, how's my dynamo?
EMMA Hi, Sarah!
KELL We haven't seen you in so long it's ridiculous.
KELL When are you gonna come by for a visit?
SARAH Who needs a life, right?
SARAH Talk to your husband, maybe he'll give us a day off one of these years.
KELL Soon, huh?
KELL Seriously, we miss you.
Sarah blows Emma a big extravagant kiss.
Emma returns it, waves as they pull away.
Nick and Kell glance back, happy to see their daughter acting a bit more like her old self...
Late.
Nick, in t-shirt and pajama bottoms, comes up a dark hallway with a file in his hand, rubbing his eyes.
He comes to his daughter's bedroom door, quietly turns the knob...
...and finds the bed empty.
Sheets thrown back.
Nick stands for a moment, every irrational fear he's ever had washing over him.
CAMERA FOLLOWS HIM fast down the hallway...
...into the master bedroom, where he finds Emma sleeping with Kell.
He stands for a moment, heart hammering.
Softly:
NICK Fuck.
Kell stirs, sees him, puts a finger to her lips.
In whispers:
NICK I saw her bed empty.
NICK Scared the shit out of me.
NICK Don't know why.
KELL She had a bad dream.
KELL She wanted to sleep with us tonight.
NICK Jesus.
EMMA Daddy...?
He climbs onto the bed, cuddles up, Emma between them.
EMMA I had a nightmare.
EMMA That man.
NICK I know.
NICK Shhh.
NICK We're all good.
NICK You're safe.
NICK Nobody's gonna hurt you.
KELL Especially not that man.
KELL Daddy's gonna put him in jail forever.
KELL That's what daddy does.
KELL He makes sure the bad people stay locked away.
Nick lays there, listening...
A huge domed chamber.
In the center of the floor stands a smaller free-standing domed cage, like a bizarre birdcage.
Inside the birdcage: Nick and Garza wait.
Garza mans a camera.
Outside the birdcage: Observers.
Some (Cantrell and Sarah) occupy floor-level, where the video monitors are.
Others (Iger and Dunnigan) are on a catwalk above that encircles the room.
A door opens and Clyde is brought into the birdcage.
He gazes around, checking his surroundings.
CLYDE I admit I expected something more modern.
CLYDE That jail downtown?
NICK Filled to capacity.
NICK It has been for years.
NICK They had to re-open this for the overflow.
NICK Part of it anyway.
GARZA Welcome to the county jail annex.
GARZA * All new inmates come here.
GARZA It was * in the papers.
CLYDE Right.
CLYDE Prison crowding.
CLYDE It's a problem.
He sits.
Nick joins him, pulls out a legal pad.
NICK For the record: You've waived legal counsel.
NICK You've offered to confess to the murders of Clarence Darby and Rupert Ames.
NICK Yes?
CLYDE We'll get to that.
CLYDE First, what I'd really like to talk about is the cot in my cell.
CLYDE It's lumpy.
CLYDE Hardly any padding?
CLYDE Steel springs?
CLYDE Very uncomfortable?
NICK I know what lumpy means.
NICK Sorry to hear it.
NICK But we're not here to talk about prison conditions, we're here to talk about things you've done.
CLYDE Start with things I haven't done.
CLYDE Like get any sleep last night.
CLYDE I said let's begin today fresh and * rested.
CLYDE You recall my words?
NICK * What do you want from me?
CLYDE A bed in my cell.
NICK A bed.
NICK In your cell.
CLYDE Yes, please.
CLYDE One of those Sleep- Matic adjustables.
CLYDE Those are best.
NICK You want the variable temperature control too?
CLYDE That would be nice.
Beat.
Nick tosses his legal pad on the table, swivels around in his chair to the observers up on the catwalk, spreads his arms in a "help me" gesture.
NICK Anybody?
DUNNIGAN It's a steel cot!
DUNNIGAN It's bolted to * the wall!
CLYDE I'm sure they have a wrench.
IGER We also have rules prohibiting * personal items such as beds.
CLYDE Let me get this straight.
CLYDE You're going to let a bed prevent this confession from taking place.
NICK You looking to deal?
NICK All right, how's this?
NICK How about I don't kick your fucking teeth down your throat?
Clyde is mildly taken aback.
The cops tense up.
CANTRELL Nick.
NICK Sorry, Jonas.
NICK Okay, kid gloves.
NICK My daughter slept in our bed last night.
NICK She hasn't done that since she was six.
NICK You gave her nightmares.
NICK So excuse me if I don't feel like cutting any little deals today.
CLYDE My daughter can't have nightmares, because she died with Clarence * Darby's breath in her face.
CLYDE You * gave him a reduced sentence and his * freedom.
CLYDE All I want is a good night's sleep.
Everybody's wound up, talking fast:
NICK This is bullshit.
NICK He's jerking our chain big-time...
CANTRELL I can justify the expense.
IGER It's not just a bed.
IGER Every inmate * here will be on the phone to their * lawyer filing lawsuits for equal treatment.
IGER Can you justify that?
SARAH * We give him a bed, he confesses, we * take the bed away.
SARAH * At most it's one * night.
Cantrell weighs it, decides:
CANTRELL We're talking a high-profile double homicide.
CANTRELL Order the bed.
Clyde watches as MAINTENANCE MEN remove the unbolted cot from the cell and his Sleep-Matic is rolled in.
CONVICTS watch, dumbfounded.
Clyde's cellmate, a towering Aryan Brother named DWIGHT DIXON, stands quietly amazed...
CLYDE (V.O.) Switching the drugs was easy...
Back in the birdcage:
CLYDE I hacked the Fedex database, diverted the package to me, made the switch, sent the package on.
CLYDE It's automated tracking numbers moving millions of packages daily.
CLYDE Nobody's questioning who receives what, or why.
NICK And the prison phones?
CLYDE Get a phone company uniform, hack the prison database, schedule an official visit.
CLYDE They'll wave you through the gate, like they did me.
CLYDE It's simple if you know how things work.
CLYDE It's a system.
CLYDE You learn how it works.
CLYDE You play it.
CLYDE Any system.
NICK I saw him die.
NICK That stuff burned his veins.
NICK He suffered terribly.
CLYDE Score.
Nick flips to a new page on his pad.
NICK Let's move on to Clarence Darby.
CLYDE (sits back) * Hey, you like music?
NICK (hesitates) * Very much.
NICK Why?
CLYDE I could tell.
CLYDE I love music.
CLYDE All of * it.
CLYDE It's like air in my lungs.
CLYDE So the thing about Clarence Darby is, I want my record collection and player brought to me.
CLYDE The vinyl discs as well as CDs.
Reactions all around the room.
Iger leans forward:
IGER Vinyl records and CDs can be broken into shards.
IGER They make excellent weapons.
IGER My answer to that one, Mr.
IGER Clyde, is not no, but hell no.
Clyde absorbs that, looks to Nick, as:
NICK It's a legitimate concern.
CLYDE How about my ipod and speaker dock?
AN IPOD AND SPEAKER DOCK now occupy a small plywood shelf attached to the railing outside Clyde's cell.
A GUARD plugs it in via a long orange extension cord.
ANGLE WIDENS to Iger, who turns to the bars and hands a remote control through to Clyde.
Dixon's watching balefully, as is every inmate on the cellblock.
IGER The player stays out here.
IGER You hand the remote to the on-duty guard every night at lights out.
IGER Those terms aren't negotiable.
CLYDE I appreciate your compromise.
Iger draws close to the bars.
Quietly:
IGER You looking to get your ass kicked?
IGER By every inmate on this cellblock.
IGER You keep this up, they'll take it out on you.
IGER Harshly.
Clyde glances back to Dwight.
Dwight's watching, glowering, agreement in his silence.
Clyde turns back to Iger.
IGER Just trying to keep you alive in here.
IGER That's all.
Iger walks away.
Clyde aims the remote.
MUSIC STARTS PLAYING.
He leans his head on the bars, listening, blissed.
Cons all over the cellblock are staring daggers at him.
CLYDE I took his fingers with a bolt cutter.
CLYDE His toes with a pair of tin snips.
CLYDE His balls with a hacksaw...
CLYDE ...his penis with a box cutter.
CLYDE His skin with a filet knife.
CLYDE His teeth with pliers.
CLYDE His eyes...for those I used my fingers.
CLYDE Check the video I made.
CLYDE All that will match up.
CLYDE I kept him alive for an hour, give or take.
CLYDE Time it.
Nick trades looks with the others in the room -- everybody have what they need?
People nod.
Nicks closes his pad.
CLYDE What now?
NICK My office types it up, you sign.
Nick rises, putting things in his briefcase.
People get ready to leave -- but Clyde motions Garza to keep it rolling.
CLYDE How about a signing bonus?
CLYDE The small concessions you've made so far have kept my cooperation flowing...why not give me a reward for signing?
NICK You don't want to sign, don't sign.
NICK We've got you on videotape, we'll go to trial.
NICK In ten years, when your appeals are exhausted, I'll attend your execution.
NICK I'll make sure nobody tampers with the drugs.
CLYDE Don't be such a hard-ass, Nick.
CLYDE I don't want much.
CLYDE Just a good meal.
CLYDE The food here?
CLYDE Sucks.
CLYDE No offense.
Dunnigan glances at Nick and stifles a smile, enjoying where this is going in spite of himself:
DUNNIGAN What do you have in mind?
CLYDE There's a place in town on Halston.
CLYDE La Traviata.
CLYDE Ever been?
DUNNIGAN It's a little above my pay grade.
CLYDE You know it, don't you, Nick?
NICK I've eaten there.
NICK So?
CLYDE They cater.
CLYDE Tonight, at 7 p.m., I * would like my meal delivered to my cell from La Traviata.
CLYDE With nice silverware, crisp linens...
NICK Not gonna happen.
CLYDE Why not?
NICK Because I have no interest in making it happen.
NICK And you have nothing left to bargain with.
CLYDE C'mon, Nick.
CLYDE We've just started bargaining.
CLYDE You haven't even heard what I'm offering yet.
This makes people pause.
Something in the tone of his voice.
CLYDE Miss Lowell?
CLYDE Is your laptop still on?
CLYDE Would you please do a search?
She flips the laptop opens, dread mounting even though she's not sure why, poises her fingers over the keys.
CLYDE William...Baxter...Reynolds.
Cantrell's quietly stunned as the name sinks in.
Pin-drop silence now.
Laptop keys CLACKING SOFTLY.
People frozen.
DUNNIGAN Who's William Reynolds?
CANTRELL Clarence Darby's defense attorney.
CANTRELL He brokered the testimony deal with us ten years ago.
CANTRELL He's been missing now since...
CLYDE March of '06.
Sarah spins the laptop -- a photo of Reynolds, a story of his disappearance.
CLYDE Detectives Dunnigan and Garza will like this offer, Nick.
CLYDE It'll clear one of their department's missing- persons files.
CLYDE And it'll solve them their third homicide this week.
NICK Tell me.
CLYDE How do you think I located Clarence Darby after he got out of jail and legally changed his name?
CLYDE Reynolds told me -- though it took some * convincing.
PUSH IN ON Clyde in the frozen silence...
CLYDE You want the location of the body?
CLYDE Tonight, 7 p.m., I get my meal * delivered to my cell from La Traviata.
A HELICOPTER THROTTLES UP, everything moving fast: an FBI FIELD TEAM, led by AGENT SAM DAVIES, emerges from a staircase door onto the roof, where they are met by Nick and Dunnigan.
Davies dons his kevlar vest on the move toward the waiting copter, everybody SHOUTING over the rotors:
They get to the helicopter, feds loading in as Nick pulls a business card, hands it to Davies.
Davies gets in, signals the PILOT.
The copter takes to the air, buffeting Nick and Dunnigan...
TIGHT ON CLYDE.
He looks up, speaking slowly and clearly:
CLYDE GPS position is as follows...
FBI HELICOPTER THUNDERING over the city...
VOICE ON RADIO * ...delta niner foxtrot...GPS * coordinates follow...
The helicopter veers, banks into a steep turn...
Nick enters, moves through the bullpen.
ADAs (assistant district attorneys) are working and grimly focused.
Nick pokes his head into Sarah's office.
She looks up.
NICK What do we have so far?
A HIGH-END DELIVERY VAN bearing the logo of La Traviata is waved through the gate into the delivery entrance...
SARAH (V.O.) * He's got no next-of-kin.
SARAH (V.O.) * No family * since his wife and daughter were * killed...
THE FBI HELICOPTER THUNDERS over beautiful green hills...
SARAH (V.O.) He's a tinkerer.
SARAH (V.O.) Little inventions * and gizmos...
Nick gazing out the window, Cantrell seated with his dog, Sarah reading the report thus far:
SARAH ...he holds two dozen patents that have made him a lot of money the last ten years.
SARAH He's invested a lot of it in real estate.
SARAH Weird stuff.
CANTRELL Weird how?
SARAH Properties with no real value.
SARAH Around * airports, chemical plants.
SARAH Stuff * nobody wants...
A CONVICT comes to his bars, peering out...
CONVICT * Motherfucker...
...because here comes the rolling La Traviata cart -- gleaming domes keeping food warm, silver utensils, crisp linens, a ROSE in a bud vase.
A red-jacketed LA TRAVIATA WAITER is pushing the cart, accompanied by GUARDS and Warden Iger.
More cons appear at their bars, faces peering, an angry grumble growing in the cellblock as the cart goes by.
The waiter's looking around, nervous...
SARAH (V.O.) He votes.
SARAH (V.O.) He gives money to charity, mostly victim's funds...
SARAH ...but he also gives a big chunk to macular research.
CANTRELL He donates to eye research?
SARAH RPI.
SARAH That's the charity you work with, isn't it?
CANTRELL Huh.
CANTRELL Strange.
The waiter, hemmed by guards, nervously reads the order:
WAITER ...consomme...sea bass...squab...
WAITER * New York strip, rare...a variety of * pates...
CLYDE Rack of lamb?
WAITER ...oh, yes, rack of lamb...
THE HELICOPTER ROARS IN, lands.
Davies and his men jump out.
AN FBI GROUND TEAM is waiting for them.
A CAMDEN FIELD AGENT runs up and points at the ground, shouting:
Davies signals his team.
SHOVELS AND PICKS hit the ground...
...while GORGEOUS FOOD hits paper plates.
It's being slopped unceremoniously from the fine china by the guards.
TILT UP to Iger overseeing this process, passing china and utensils to the waiter, who's flustered:
WAITER You're bruising the crepes.
GUARD Life's a bitch, then you die.
IGER ...no plates, they break into nice jagged pieces...nothing sharp, nothing that can be made sharp...no forks, no knives, no spoons....lose that carafe...we will have no potential weapons of any kind this evening, thank you...you can eat with your fingers...
CLYDE The guards will think me gauche.
Clyde's got the rose, teasing his nose with it.
All around * the cellblock, inmates are shouting insults and threats...
Sarah is exiting, leaving Nick and Cantrell to stare at the phone and wait for it to ring...
NICK Thanks.
NICK Keep digging.
Digging.
Sod coming off, being set aside on plastic.
FLASH PHOTOS being taken.
Stones being pried up...
Waiter and guards exit with the cart.
The entire cellblock is SHOUTING.
Iger pauses, gives a final glance back.
Softly:
IGER Idiot.
Then he too departs, as:
CLYDE aims his remote.
MUSIC for dining.
Clyde glances back at * Dwight, who's poised and tense.
CLYDE I suppose if I don't share, you'll beat the shit out of me.
CLYDE Make me squeal like a piggy.
CLYDE That sort of thing.
DWIGHT Fuckin' A.
Clyde motions "join me, won't you?" They each take a seat.
Clyde passes Dwight a crisply-folded linen napkin.
Dwight tucks it like a bib.
Clyde lays his on his lap.
A hurled object CLANGS off their bars.
The cons are now throwing things, hollering to raise the dead.
Clyde cranks the music a bit louder, motions for Dwight to dig in.
Dwight goes for it, cramming food in his mouth and grabbing for more, fingers digging in...
...fingers digging in, pulling loose soil, prying stones.
A layer of soil is brushed aside to reveal:
A face.
Embedded in the dirt.
He's been there a long time.
FLASH PHOTOS highlight desiccated lips and teeth...
...lips and teeth -- Dwight chewing, laughing.
Oddly enough, he and Clyde seem to have started enjoying each other's company.
THE MUSIC PLAYS in bizarre counterpoint to: *
THE CACOPHONY of an angry cellblock -- if the cons weren't in their cells, this would be a riot.
All imaginable items are being hurled through bars: toilet paper rolls, books, shoes, clothes, all raining down, showering the cellblock floor...
CLYDE I wonder what the little people are eating tonight?
Dwight throws his head back and laughs...
...while, in deep silence, Nick unwraps a sorry-looking deli sandwich, swaps his pickles for Cantrell's potato salad (their long-standing ritual).
They both keep glancing at the phone...
...as Clyde and Dwight indulge their food orgy.
Dialogue is not important, so we won't hear any -- we'll let the MUSIC * take over and carry -- because it's all about tone:
They're laughing and talking, winding each other up.
And the more Clyde wisecracks, the more Dwight laughs.
Clyde finishes gnawing a lamb rack and says something to Dwight about the ruckus.
Dwight turns, glances out, as:
Clyde casually, but with purpose, lowers the bone onto his lap -- adding it to one already there.
He picks up a fresh one, starts chewing the meat off...
Dark enough now for flashlights.
In the beams, we see the body mostly excavated.
Forensic team members gather, in gloves and breather masks, getting ready to try lifting.
FORENSIC TECH Okay, let's see if we can get him out in one piece...
ANGLE FINDS Davies at the helicopter, activity around him, holding Nick's card and dialing a cell phone...
Clyde laughing, chewing, gnawing that third bone.
ANGLE CLOSES DOWN as he brings it to his lap...
BLUE - 9-19-08 58. TIGHT REVEAL: His napkin wrapped tightly around his hand provides padding for his palm.
BLUE - 9-19-08 58. The two earlier bones are already held between his fingers -- he places the third, makes a fist -- and the bones now protrude from his clenched knuckles like a trio of spikes.
BLUE - 9-19-08 58. TILT UP to Clyde...he reaches across, turns a paper plate over to cover the crepes...
The PHONE RINGS.
Nick snatches it up.
He listens, looks to Cantrell...nods.
They found the body.
Behind Davies, B.G., the body's being extracted from the hole:
FORENSIC TECH ...gently on three...one...two...
DAVIES --we'll have to wait for the autopsy results, but--
DAVIES WHAM -- the GRAVE ERUPTS as HALF A DOZEN BURIED CLAYMORE MINES * pop like firecrackers, knocking Davies forward...
...and Clyde lunges, face no longer laughing, the rolling cart slamming into the wall as the lamb bones protruding from his fist go slamming into Dwight's throat...
...and the dust cloud cascades across the hillside...
...and Clyde has Dwight pinned on the floor against the bars, arm ramming like a piston, punching those bones into Dwight's throat again and again, blood everywhere...
TIGHT ON NICK holding the phone.
He knows something awful just happened on the other end:
NICK Agent Davies?
An open CELL PHONE lies on the grass.
Feet stumble haltingly into the shot.
TILT UP TO:
BLUE - 9-19-08 59. Davies, dazed, staring offscreen in shock.
BLUE - 9-19-08 59. Dust and smoke billowing.
BLUE - 9-19-08 59. People running, shouting...
Clyde rises into the shot, calm now, covered with blood.
He unwraps the napkin from his hand, snaps it open, uses it to wipe the blood from his face.
He takes his seat, positions the cart, uncovers the crepes and resumes eating...
A steel gate slides open, revealing Nick.
Flanking him are Cantrell, Dunnigan, Davies (banged up and bandaged), Iger, others.
They move toward us with purpose, grim and resolute, Sarah bringing up the rear with a young ADA named ROYCE.
NICK Why do you have him in the dome?
IGER He killed his cellmate.
IGER We had to separate him out.
CANTRELL What's wrong with solitary?
IGER We don't have the authority.
IGER Not without a court order.
IGER This place was re-opened under protest as it is.
IGER Some areas are off-limits to our use -- tied up in a legal challenge by the ACLU as cruel and unusual.
IGER Especially solitary.
IGER It was nicknamed the dungeon...
NICK Get Judge Burch on the phone.
NICK Sarah speed-dials as a GUARD lets them in...
Clyde waits in the birdcage, shackled.
The group spreads into the room, silence thick.
Nobody will enter the birdcage this time.
Clyde occupies it alone -- owning it, in fact -- as:
IGER Nice trick with the rack of lamb.
IGER Didn't see that one coming.
NICK Why'd you kill your cellmate?
CLYDE I claim self-defense.
NICK Here's what I think.
NICK You suckered us in.
NICK You ordered that meal for the purpose of killing him.
CANTRELL Which makes it premeditated.
CANTRELL Again.
CLYDE And, again, you'll have to prove that in court.
CLYDE As I've said before...
CLYDE ...make your case.
CLYDE Or set me free.
DAVIES Your booby-trap killed two of mine * and put four in the hospital.
DAVIES That * brings the total of people you've * killed to six -- and be advised the * Bureau does not suffer losing agents in the field.
DAVIES We're done dancing.
DAVIES I have the right to claim jurisdiction here, do I not, Detective Dunnigan?
DUNNIGAN That is correct, Agent Davies.
DAVIES So.
DAVIES I'm gonna rendition your ass.
DAVIES Rumor has it we have places that make Guantanamo look like Disneyland.
DAVIES Don't bother packing, you're gonna disappear.
CLYDE You see, Nick?
CLYDE That man is pissed!
CLYDE That's what I'm talking about!
CLYDE No deals, no compromise!
CLYDE You see?
NICK I see you totally disconnected from reality, that's what I see!
SARAH Judge Burch with an answer for you.
JUDGE BURCH I'm the ACLU's biggest fundraiser in this state.
JUDGE BURCH You wanna put that piece of shit in solitary?
JUDGE BURCH Good.
JUDGE BURCH As far as I'm concerned, you can bury him in the bowels of hell.
NICK Thank you, Judge Burch.
NICK (hangs up, looks to Iger) * Consider your court order signed.
NICK Freedom?
NICK Not likely.
NICK In fact, you just bought a one room suite in the dungeon.
NICK Very exclusive.
IGER You'll have it all to yourself -- the first man down there in over twenty years.
IGER Quite an achievement.
IGER Clyde sinks with a sigh of resignation and defeat, rests his
head wearily on the bars.
Nick moves in, speaking quietly:
NICK You're doing everything wrong.
NICK Making all the wrong moves.
CLYDE It would seem that way.
The wording catches Nick -- but he dismisses it, turns:
NICK Sam.
NICK I know you got hit hard.
NICK I know you're furious.
NICK But I'd like my shot at prosecuting this case.
NICK (off Davies' look) * This started with us.
NICK Let me finish * it.
NICK Give me that chance.
CLYDE I'm seeing fire in your belly, Nick.
CLYDE I like it.
CLYDE Keep going.
CLYDE This is our deal, after all...
CANTRELL Let's not mistake this!
CANTRELL This is not about the two of you!
CLYDE Wake up, blind man!
CLYDE It's been exactly that since I watched him shake Clarence Darby's hand on the steps of the Hall of Justice ten years ago!
CLYDE The Hall of Justice!
His voice echoes off.
In the silence that follows:
DAVIES You wanna take this fuck down?
DAVIES Be my guest.
DAVIES Whatever you need.
CLYDE That's the spirit, yes!
CLYDE It's on you now, Nick.
CLYDE It's your game to lose.
CLYDE Just don't screw up.
CLYDE You do, they'll scapegoat you.
CLYDE That's * how the justice system works.
CLYDE Good call, Sam.
CLYDE Making me disappear was a bad idea.
CLYDE You couldn't have handled the blowback.
NICK Blowback?
CLYDE * Cause and effect.
CLYDE * Your actions * provoke reactions.
CLYDE * The choices you * make come back to haunt you.
CLYDE * * (off their looks) * There are things I've set in motion.
CLYDE * * Dominoes that will fall.
CLYDE * Didn't see * the rack of lamb coming?
CLYDE * Start a list.
CLYDE * All I can do at this point...if I feel like it...is stop them from happening.
CLYDE * Ready to talk deal?
NICK You're insane.
CLYDE See how insane you think this is.
CLYDE You're going to release me from this place with all charges dropped within twenty four hours...
NICK Or what?
CLYDE Or I start killing everybody.
"The Dungeon" -- a small underground block of FIVE CELLS dating back a century or more.
A GUARD is spraying WD-40 into the lock of a cell, trying to turn the key.
It finally does, as:
Clyde is brought in.
GUARDS have him on poles connected to a leather collar around his neck, and they're none too gentle.
Clyde tosses a final glance back at Nick and Iger.
CLYDE Clock's running, Nick.
CLYDE ...and then he's gone, shoved inside.
Nick and the others exit the Dome, thoughts racing:
CANTRELL What can he do?
CANTRELL We've got him boxed in.
CANTRELL He's isolated, for God's sake.
NICK Let's keep him that way.
NICK Strict rules apply.
NICK Law says he gets one hour outside his cell a day, that's what he gets.
NICK Just one, under heavy guard.
NICK The other twenty-three hours, he's in that cell, he's a ghost, he doesn't exist.
NICK No contact whatsoever.
DUNNIGAN You think it was a bluff?
NICK We underestimated him before.
NICK I'd like to know what this prick is capable of.
NICK Update on the background check?
SARAH Properties, investments, a few small * businesses he owns -- a lot of it's * hidden behind false names and shell * companies, but we're still digging...
NICK That's it?
NICK Nothing else unusual?
ROYCE The last twenty years, he's been * Joe Blow Citizen.
ROYCE But prior to that, * we've hit a blank spot.
ROYCE He used to * do consulting for the government, * but we can't pin down what.
BLUE - 9-19-08 64. They absorb this -- especially Davies.
BLUE - 9-19-08 64. All eyes go to him.
NICK What kind of government work leaves a blank spot, Sam?
DAVIES I'll make a few discreet calls.
DAVIES See what I can find out.
Expensive, upscale.
We find Nick and Kell at a table.
She's got her menu, but her attention's really on Nick.
He's toying absently with his wine glass.
KELL Where are you?
NICK Million miles away.
NICK Sorry.
KELL Don't be.
KELL This guy's really doing a number on your head, isn't he?
NICK Yeah.
NICK I guess he is.
NICK It's...killing his cellmate.
NICK I need that to make sense.
KELL Why?
KELL Happens in prison all the time.
NICK Yeah, I know, but...we're not talking some gang-banger.
NICK This man is precise.
NICK Does things for a reason.
KELL He's psycho.
KELL You said so yourself.
KELL We saw it on that video.
KELL Psychos don't need a reason, Nick.
KELL They're just psycho.
KELL Whatever.
KELL You'll figure it out.
KELL You * always do.
NICK Thanks.
NICK I'm a poor excuse, though.
NICK It's date night.
NICK You deserve better.
NICK Just wish you'd picked another * restaurant.
KELL This is our place.
KELL You love it here.
KELL You should have said something...
KELL She raises her menu -- yes, we're in La Traviata.
KELL And the
waiter is the same guy who brought Benson Clyde his meal:
WAITER Have we decided?
WAITER Nick's CELL PHONE RINGS.
WAITER He pulls it, checks the number, gives them a look -- sorry, gotta take this.
NICK Sam?
NICK What is it?
NICK Not far, maybe six blocks.
NICK I'm having dinner with my wife.
DAVIES Two words: doggy bag.
DAVIES Be in your office in ten minutes.
DAVIES Nick, don't ask questions.
DAVIES I was on the phone all day.
DAVIES Believe me when I say we've got one shot at this.
DAVIES He clicks off...
...and faces Nick and Cantrell in the dimly-lit office:
NICK He's coming here?
DAVIES So I'm told.
DAVIES It's called inter-agency cooperation, but don't ask me what agency because I wouldn't know.
DAVIES This isn't even back-channels, this is Theseus in the fucking Labyrinth.
DAVIES I just blew thirty years' worth of favors today calling in this one chit.
DAVIES I hope it's worth it.
The desk phone RINGS.
Nick answers, listens a beat:
NICK Yes.
NICK Yes, we're all here.
NICK Downstairs?
NICK Okay.
NICK Understood.
NICK He said not to take the elevator.
NICK Off their puzzled looks...
Huge, descending seven floors, circles within circles dropping into darkness.
Nick and Davies lead the way down.
Cantrell brings up the rear with his dog and cane...
SPOOK That's good there.
SPOOK They freeze.
SPOOK Nick and Davies peer down.
SPOOK They start to make out a FIGURE in the murky darkness one level below.
SPOOK Which one of you is Davies?
SPOOK Davies takes a step forward.
SPOOK THE SPOOK eases partially into the light -- flinty gaze, military-style haircut.
SPOOK You must be well thought of, Agent Davies.
SPOOK I don't do this.
SPOOK But I was asked nicely by the right people.
SPOOK They briefed me on your problems with Benson Clyde.
NICK What are we dealing with?
SPOOK Things I can neither confirm nor deny.
SPOOK Things of which, if I'm asked, I will disavow any knowledge.
SPOOK The guys trade a look.
SPOOK Cantrell can't help chuckling.
CANTRELL You gotta be kidding me with this guy.
SPOOK He's not.
SPOOK Tell me you grasp the implication of what I've said, or we're done here.
CANTRELL Yeah.
CANTRELL Okay.
CANTRELL I get it.
NICK What was Clyde?
NICK Some kind of spy?
SPOOK Spooks like me are a dime a dozen.
SPOOK Clyde was a brain.
SPOOK He ran a think- tank, inventing things for use in the field.
SPOOK Ways to kill people.
SPOOK You need to get rid of somebody.
SPOOK It's not a situation where you can get close.
SPOOK What do you do?
NICK Ask Clyde?
SPOOK That's right.
SPOOK Ask Clyde.
SPOOK And he'd figure something out.
SPOOK Gizmos, strategy.
SPOOK He was good at it.
NICK How good?
SPOOK You play chess?
NICK Yeah.
NICK Tournament level in college, matter of fact.
SPOOK In my line, we use an aptitude profile based on chess.
SPOOK A tournament- level player like you can think five to eight steps ahead of an average player, did you know that?
SPOOK Me, I think about ten steps ahead, so I'd take you in a game.
NICK What about Clyde?
SPOOK Off the charts.
SPOOK If you're eight steps ahead, he's twenty.
SPOOK Or fifty.
SPOOK He's already got the game won on the first move, you don't even know you're playing yet.
SPOOK This cellmate he killed?
SPOOK You think that was random?
SPOOK Bullshit.
SPOOK That was a pawn taken off the board.
SPOOK If I were you, I'd be trying to figure out what the move was.
NICK I have been.
NICK Any thoughts?
SPOOK Top of my head?
SPOOK Was the cellmate ever connected with this case?
SPOOK Or with Clyde?
SPOOK Was anybody else in that facility?
SPOOK Guards?
SPOOK Cons?
SPOOK The janitor?
SPOOK Any connection at all, no matter how remote.
SPOOK Because if Clyde says he has things in play, he does.
DAVIES Like what?
DAVIES He's locked up.
DAVIES What can he do?
SPOOK You're an average chess player, aren't you?
DAVIES Actually, I kind of suck.
SPOOK I can tell.
SPOOK But I like your tie.
DAVIES Thank you.
DAVIES Father's Day.
SPOOK There's this tie -- we call it the Albert, after Albert DeSalvo.
SPOOK They tiptoe in one night, thread a piano wire with a ratchet gizmo into one of your ties.
SPOOK Sounds crazy, but * trust me it works.
SPOOK You put your tie * on and all day long it slowly tightens.
SPOOK You don't even notice it's cutting off the blood-flow to your brain.
SPOOK Then you drop dead.
SPOOK Brain-dead or plain dead, doesn't much matter at that point.
SPOOK Clyde invented that.
The Spook melts back into the shadows.
The guys crane forward, trying to see.
There's a brief spill of light below as a doorway opens and closes...he's gone.
The three of them stand there absorbing everything they've heard.
Nick sits on a step.
Quiet looks are traded...
...and they all start taking off their ties...
Nick enters tie-less, subdued, distracted.
Kell and Emma are in the living room playing Scrabble.
EMMA Daddy!
EMMA Emma jumps up and runs over for a hug.
EMMA Mom said I could stay up late.
EMMA Wanna play Scrabble?
NICK Let me talk to mom first.
NICK Emma returns to the couch.
NICK Kell comes to Nick, noticing his weird vibe: he's looking around at the room.
NICK Sorry about date night.
KELL It's fine.
KELL You learn anything?
NICK Thing or two.
NICK He moves up the hallway -- slowly, as if noticing the walls for the first time, the picture frames, the light fixtures...
KELL Nick?
NICK Hey, I was thinking.
NICK Maybe you could pack an overnight bag for you and Emma in case you need to...you know...spend the night in a hotel.
NICK Or something.
KELL Why would we wanna do that?
NICK No reason.
NICK It's like a fire-drill thing.
NICK You know.
NICK In case.
He comes in, opens the closet, reaches up for some overnight bags -- but pauses, drawn to his tie-rack inside the door.
He stares at the ties hanging in neat rows...starts touching them, running his hands up and down the fabric...
Kell stands in the doorway watching.
Wondering what the fuck is going on.
And getting a little creeped out.
KELL Honey?
He freezes, feeling something in the seam of a tie.
Runs his fingers up and down, thinking something's in there.
Emma appears in the doorway too, at her mother's side.
Both staring now.
They watch as:
Nick grabs a pair of scissors from Kell's sewing kit, carves the tie lengthwise, rips it open, feverish and faster, finds nothing inside but mangled fabric and thread and -- stops.
Looks back.
Realizes they're staring at him.
KELL What the hell are you doing?
Nick pauses -- what the hell is he doing?
He starts to regain his sense, laughs at himself in amazement.
EMMA Daddy?
NICK It's okay, baby -- I'm fine, I promise.
NICK Go back to your game.
Dubious, Emma departs.
As soon as she's out of earshot:
KELL Seriously, Nick.
KELL What the fuck.
NICK Nothing.
NICK I got paranoid for no reason, that's all.
NICK I'm fine now.
NICK I can't believe I let that son of a bitch Clyde get to me like that.
KELL Are you in danger?
KELL Are we?
The question hangs there -- the real question.
NICK I'm sure we're fine.
He pulls his phone, speed-dials.
NICK * I'll make goddamn sure.
NICK * * (beat, into phone) * Sarah, roust the ADAs.
NICK * Tell 'em * we're pulling an all-nighter.
ADAs are parking their cars along the wall, directed by a waving GUARD.
ANGLE FINDS a lot of people: cop, prison, FBI.
* Sarah jumps out of her car and hurries over to Nick and the others with a flock of EIGHT ADAs at her heels.
NICK Ready to turn this place upside down?
...we find the ADA team spread around the bullpen, aided by prison personnel and police advisors -- everybody's on computers, or sorting heaps of paper files, etc.
NICK See if there's anybody locked up here -- or working here -- ex-cop, witness for the prosecution -- anybody who might have had anything to do with the original Darby-Ames case, or has any previous history with Benson Clyde.
NICK Start with the cellmate.
NICK Flag anything, no matter how insignificant it seems...
NICK JAMESON glances up in dismay from his keyboard.
JAMESON This could take days.
JAMESON Sarah, grabbing a stack from a filing cabinet and slamming
the door shut with her hip, gives him a laser look:
SARAH We boring you, Jameson?
SARAH You got someplace to be?
JAMESON No, Miss Lowell.
SARAH Weekend plans?
SARAH Cancel 'em!
SARAH I don't wanna hear any shit about it!
SARAH Clack-clack, Jameson.
SARAH Clack-clack.
BLUE - 9-19-08 72. Jameson dives onto the keys, starts clack-clacking.
BLUE - 9-19-08 72. Sarah gives Nick a nod -- she's got this in hand.
BLUE - 9-19-08 72. Nick exits...
...and finds a FORENSIC TEAM disassembling Clyde's Sleep-Matic bed -- nuts, bolts, struts, electronics.
The mattress is being razored open, wadding pulled out and run under fluoroscopes.
NICK Well?
DUNNIGAN It used to be a Sleep-Matic adjustable bed.
DUNNIGAN Now it's not.
DUNNIGAN CAMERA FOLLOWS them to a table where an FBI TEAM is focusing all their skills and tech on Clyde's ipod and speaker dock.
DUNNIGAN The TEAM LEADER places the buds in his ears, listening.
NICK What do you have?
TEAM LEADER Rocky Mountain Way.
TEAM LEADER Joe Walsh.
TEAM LEADER What do you want from me, it's a fucking ipod.
TEAM LEADER The other agents snicker, not hiding their amusement, but: *
NICK * Tear it apart, make sure.
NICK * Memory.
NICK * * Speakers.
NICK * Wiring.
NICK * Everything.
GUARDS, FEDS, BOMB-SNIFFING DOGS -- they're cruising the cellblocks, flashlights swiveling, beams catching the faces of sleepy cons in their cells or at their bars...
We find Nick and Iger at Clyde's now-empty cell.
TWO FBI * emerge, shake their heads.
FBI FORENSIC Blood stain.
FBI FORENSIC Few fibers.
FBI FORENSIC That's it.
CONVICT Warden, man, whassup?
IGER Everybody back to sleep.
NICK I want to see him.
Two doors: solid steel outer door, inner barred door.
The outer slides aside, reveals Nick outside the bars.
Inside stands a shadow, waiting: Clyde.
CLYDE You're up early.
CLYDE Trouble sleeping?
NICK It was a good bluff.
NICK But you're done.
NICK Fucking with my head.
NICK Scaring * my family half to death.
NICK Done.
NICK Clyde moves closer to the bars, into the light.
CLYDE Amazing, isn't it?
CLYDE How primal that is.
CLYDE That pull?
CLYDE What a man is capable of when it comes to his family?
NICK * You strip away all the polite shit, * that's what we're really about.
CLYDE * I hope you never face what it is to * lose them, Nick.
CLYDE * It's like dying yourself.
CLYDE * There's nothing worse.
CLYDE * That could play as a threat, of course -- but it's not.
CLYDE * It's * genuine.
CLYDE * And pained.
CLYDE * And sincere.
CLYDE * And Nick knows it.
NICK Good night, Ben.
CLYDE Good night, Nick.
And then the moment's gone and the mocking Clyde returns:
CLYDE Is it casual Friday?
CLYDE I've never seen you not wear a tie.
CLYDE And that says volumes: Clyde's totally aware of what they've been up to and is tickled by it.
CLYDE The outer door GRINDS SHUT...
Night has passed, day is coming.
All the earlier energy has dissipated into anticlimax and weariness.
People straggle across the yard in groups toward their vehicles...
Nick, Dunnigan, Davies, Iger -- all look whipped.
Sarah approaches, briefcase in hand, files under her arm.
SARAH We dug pretty deep for one night.
SARAH Still got a ways to go, but on a first look?
SARAH Nothing.
SARAH Nada.
SARAH Zip.
IGER Well, that's good news.
NICK So far.
NICK Now we double-down.
NICK Make * absolutely certain.
NICK * (nods after ADAs) * Let them all sleep a few hours, * then bring 'em back for round two.
SARAH Due diligence.
SARAH My middle name.
She trudges toward her car, following the ADAs toward their vehicles.
Nick trades relieved looks with the men -- everybody coming down from a tense night.
Davies shakes their hands:
DAVIES Fellas.
DAVIES For once, glad not to be of assistance.
DUNNIGAN Love it when they cry wolf.
The men separate in different directions.
Dunnigan catches a glimpse of Sarah almost at her car -- she loses a page from under her arm, which flutters away on the breeze.
DUNNIGAN Miss Lowell!
DUNNIGAN Lost something!
She looks back, sees the page skittering slowly across the ground.
Weary, she blows a strand of hair from her eyes, sets down her briefcase, walks back to get it...
Dunnigan smiles, keeps walking.
The other men too.
Nick stands a moment, watching, then starts toward his car...
The ADAs are getting to their cars, pulling key fobs, aiming them to unlock their cars...
Sarah is getting to the page, leaning down...
The ADAs are pressing the remotes, a CHORUS OF CHIRPS...
And WHAM -- the cars EXPLODE in a stunning SERIES OF DETONATIONS, killing the ADAs, throwing bodies through the air, kicking cars off the ground and flipping a few skyward...
BLUE - 9-19-08 75. Nick is knocked flat by heat and shrapnel ripping the air...
BLUE - 9-19-08 75. Sarah goes flying.
BLUE - 9-19-08 75. An arcing car slams upside-down nearby on a rocket-booster of flame and shattering axle...
BLUE - 9-19-08 75. And from this point on the visuals and sound are surreal: *
NICK pries himself off the ground, stunned, looking around, trying to figure out what the fuck just happened.
NICK He's disoriented, all sound muffled.
NICK Smoke drifting.
NICK Flames billowing.
NICK Dunnigan runs up to Nick, shouting something.
NICK We can't tell what, because Nick can't hear.
NICK Dunnigan sees Nick is alive, turns and keeps going, running to help the others...
NICK Nick looks over, sees bodies being pulled clear by responders, men running in, beating at flames...
NICK Nick, dazed, looks through the drifting smoke and sees Sarah trying to sit up.
NICK There's something wrong with her leg.
NICK Nick pulls himself to his knees, staggers to his feet as sound filters back in: screams, shouts, the roar of flames.
NICK He stumbles through the smoke to Sarah.
NICK She's on the ground in shock, sobbing and flailing, crying out.
NICK Nick sees the jagged piece of metal that slammed deep into her calf, nearly
severing it.
He drops to his knees, tries to calm her:
NICK You're gonna be all right.
NICK He pulls the metal from her leg -- mistake.
NICK Blood sprays.
NICK He clamps down hard with both hands, blood going everywhere.
MEDIC! I NEED A MEDIC! He keeps clamping down, Sarah screaming and sobbing, as we
FIREMEN spraying the flaming rubble of the cars...
TANGLES OF WRECKAGE billowing smoke...
A BODY BAG dragged across the ground, added to a ROW OF BODY BAGS awaiting transport...
EMERGENCY VEHICLES parked haphazardly, lights spinning...
COPS AND RESPONDERS dealing with the scene...
BLUE - 9-19-08 76. SARAH being wheeled on a gurney to a PARAMEDIC VAN by an EMS TEAM, oxygen mask on her face, gravely injured but stabilized, everything swirling around her, Dunnigan clearing a path...
BLUE - 9-19-08 76. NICK appears, takes her hand.
BLUE - 9-19-08 76. She clasps it weakly.
BLUE - 9-19-08 76. They load her on and the vehicle pulls out with siren and lights...
Back to "real time" -- Cantrell is just getting out of his town car with his dog.
WE FIND Nick on his cell:
NICK Baby.
NICK Listen.
NICK Don't be worried or scared.
NICK But I want you to pack those overnight bags...
NICK I don't have time to explain now.
NICK Just do it, okay?
NICK I'll call you back as soon as I can -- please, honey, I gotta go.
NICK He clicks off as ANGLE COMES AROUND, revealing Davies and his
TEAMS coming his way:
DAVIES Each car had an explosive charge on the gas tank.
NICK He's got someone working with him.
NICK On the outside.
NICK He's got to.
DAVIES Not necessarily.
DAVIES Everything looks pre-rigged.
BOMB EXPERT We found a short-range transmitter beacon buried outside the prison wall.
BOMB EXPERT When your people showed up here and drove in through the gate, the signal armed the bombs.
DUNNIGAN He could have planted those bombs a month ago.
CANTRELL No...no, we've got two dozen ADAs on payroll.
CANTRELL Those eight were picked last night on the spur of the moment.
CANTRELL How could he know which eight would show up?
DAVIES He didn't.
DAVIES Our people just found bombs on every car in your ADA pool.
DAVIES All two dozen.
DAVIES We're disarming those now.
TIGHT ON CLYDE shoved into the birdcage.
The neck-poles are disengaged.
He moves forward, gazing through the bars...
CLYDE I want a phone in my cell.
CLYDE If I'm conducting my own defense, it would be useful.
CLYDE Also in case you and I need to be in touch, Nick.
NICK Fuck you.
CLYDE Your twenty four hours are about up.
CLYDE In return for the phone, I'll extend you another twelve hours.
NICK If not?
CLYDE How many more people die while you stand around dithering?
CLYDE How many do you get killed before my point starts sinking in?
Cantrell closes in, tracking Clyde by voice:
CANTRELL Motherfucker!
CANTRELL Whatever point you had was lost long ago!
CANTRELL Eight kids dead in that yard, most of them just out of college!
CANTRELL Eight!
CANTRELL I have to talk to their families.
CANTRELL I have to try to explain why their loved ones are dead.
Clyde leans down, right in Cantrell's face, intense:
CLYDE I've been waiting for my explanation for ten years.
CLYDE So far...
...NOBODY'S FUCKING BOTHERED! Beat.
...NOBODY'S FUCKING BOTHERED! Cantrell spits in his face, turns away trembling with
rage.
Clyde calmly wipes it off, rises to address them all:
CLYDE If it hasn't dawned on you, this is a war.
CLYDE As in any war, there will be collateral damage.
CLYDE The question, as always, is how much damage you're willing to take before you withdraw.
DUNNIGAN Maybe I got a better idea.
DUNNIGAN Maybe we end this war right now.
DUNNIGAN Fourteen people dead!
DUNNIGAN I have to say * this out loud?
DUNNIGAN Prisoners die in custody all the time.
DUNNIGAN Attacking a guard.
DUNNIGAN Trying to escape.
DUNNIGAN Shit like that.
Clyde, eyes locked, pulls his shirt open -- here's your target.
Dunnigan, temper flaring, yanks his revolver and aims.
DUNNIGAN Don't tempt me.
GARZA Jesus Christ, man, dial it back...
CLYDE Do it.
CLYDE It would be decisive.
CLYDE Stupid, but decisive.
CLYDE Can you handle the blowback, Detective?
CLYDE The "shit like that?"
Nick's stunned, seeing the whole situation spiraling out of control.
He steps in, seizing the moment back:
NICK Put the gun away!
NICK Are you crazy?
DUNNIGAN It's an option.
DUNNIGAN All I'm saying.
DUNNIGAN Risk the blowback.
DUNNIGAN Ride it out.
NICK We're not risking anything.
NICK Or letting him tear us down.
NICK You're not getting us to throw out the rules, like you.
NICK No way.
CLYDE I like rules.
CLYDE I've wanted you to follow them from the start.
CLYDE Like the one that says you prosecute a man who murders my family.
CLYDE So.
CLYDE Rules.
CLYDE A phone buys you another twelve hours.
CLYDE But if you haven't cut my deal and let me go by the deadline...
NICK What?
NICK What then?
CLYDE I'll kill someone in this room.
CLYDE That sucks the air out of the conversation -- everybody stares as that sinks in.
CLYDE Glances are traded.
NICK Who?
NICK He looks at the room full of people, scans their faces as if trying to pick.
NICK He points his finger, starts going from one end of the group to the other...
CLYDE Eenie...meenie...miney...moe...
CLYDE ...from person to person, to the end, moving back again...
CLYDE ...my mother...told me...to pick...a person...and that...person...is...
CLYDE He lands on Cantrell.
CLYDE Silence.
CLYDE Cantrell obviously can't see.
CANTRELL Who's he pointing at?
Everybody on the move, emotions high:
CANTRELL Fuck him.
CANTRELL Let him try.
NICK That's not helpful!
NICK We have fourteen * dead!
NICK You could ask them what he's capable of, but they're in no position to answer.
CANTRELL Point taken.
DAVIES We'll give him his phone.
DAVIES We'll tap in and monitor every call.
DUNNIGAN Buys us another twelve hours, we could use that right now.
DUNNIGAN That puts the deadline at...
DUNNIGAN ...about 7:30 tonight.
CANTRELL Shit.
CANTRELL I'll be in front of a room full of lawyers.
CANTRELL The A.B.A. dinner.
CANTRELL I'm the keynote speaker.
NICK No way.
NICK Find a replacement.
DUNNIGAN Until his deadline passes, you're in protective custody.
DUNNIGAN Not negotiable.
Cantrell isn't happy about it -- but nods.
NICK And have them switch the location of that dinner.
CANTRELL That's last minute.
NICK Exactly.
NICK He could have gotten your schedule in advance -- been planning to take you out at the dinner along with everybody else.
NICK That eenie- meenie act could have been horseshit.
NICK We have to get a few moves ahead.
NICK Plan for every contingency.
DUNNIGAN This way, Mr. Cantrell.
DUNNIGAN Garza, you're with Mr. Price.
DUNNIGAN They split up.
DUNNIGAN Dunnigan leads Cantrell to an unmarked car while Nick and Garza head toward Nick's.
DUNNIGAN Nick's phone RINGS.
He checks the number, answers:
NICK Hey baby -- no, I'm fine.
NICK Really.
NICK Honey, calm down...
He listens a beat, calls to the men getting in the other cars:
NICK Our shit just hit the fan in a big way -- we're all over the news...
NICK Yes, all eight died.
NICK Sarah's in surgery right now...
NICK ...they think so, but...
NICK ...okay, I'll meet you there.
NICK Love you.
NICK He hangs up, aims his key fob -- and hesitates.
NICK He and Garza
trade a look, thinking the same thought.
ANGLE SHIFTS to:
BOMB EXPERT * You're good.
BOMB EXPERT * Car's been swept.
NICK Of course it has.
NICK Thanks.
NICK Nick, feeling foolish, presses the fob.
NICK Nothing but a tiny CHIRP.
NICK He and Garza get in.
Dunnigan drives.
Cantrell and his dog ride in back.
Both men tense and silent.
TWO POLICE CRUISERS provide escort...
Nick is pulling up toward the hospital, sees a TV NEWS VAN at the entrance, a MINICAM CREW arguing with hospital security.
GARZA Go around.
GARZA I'll get us in back.
GARZA Nick hits the gas, drives past the news van...
...and they come past the nurse's duty desk.
UNIFORMS are stationed in the hallway.
Garza pushes a path through:
GARZA Keep the press off this floor, understand?
GARZA Nick squeezes past.
GARZA The floor is busy.
GARZA He finds Kell in the waiting area.
GARZA She looks up, spots him.
GARZA Kell rises.
GARZA She and Nick pull into a tight embrace.
GARZA No words for a long moment.
GARZA Kell's shaken, fighting tears.
NICK Any word?
KELL She's in surgery now.
KELL They're saying she'll be okay.
NICK Thank God.
NICK That's good.
KELL Good?
KELL You'll have to explain the good part, Nick.
KELL I'm missing it.
KELL This is crazy.
KELL What if something happened to you?
KELL What would I say to Emma?
KELL What would we do?
NICK You didn't lose me.
NICK You won't.
NICK Does the school know we're pulling Emma out of class?
KELL I called, yeah, but -- I'd rather be here for Sarah when she wakes up.
KELL Nick -- and for you.
KELL I want to do something...
NICK You are.
NICK Getting our daughter out of harm's way.
NICK And yourself.
NICK Detective.
NICK Will you escort my wife, please?
NICK There's not much time.
NICK I'll be there to see you off.
NICK Okay?
NICK Please?
BLUE - 9-19-08 83. Kell reluctantly walks away with Garza, while: *
A media frenzy is brewing: TRUCKS pulling in, NEWS CREWS gathering.
ANGLE TO A REPORTER on-camera:
REPORTER ...reporting live from a tense scene at City Hall...we have confirmation of earlier reports that eight people with the district attorney's office were killed this morning in an explosion at the County Correctional Annex in George Hill...
Nick enters, finds the STAFF around the bullpen watching the same live report.
Everybody's in shock, a few are crying...
REPORTER ...details are sketchy at this point, and names are being withheld...
REPORTER People start noticing Nick.
REPORTER Royce comes up, looking dazed.
NICK Sarah's fine.
NICK That's the good news.
ROYCE Oh, God, that's a relief...
ROYCE Miss Lowell is okay...she's okay...
ROYCE Everybody reacts -- they needed a shred of good news.
ROYCE We've been getting calls from upstairs.
ROYCE The mayor's people.
ROYCE Someone from our office has to make a statement to the press.
ROYCE With Mr.
ROYCE Cantrell absent, the mayor wants you to do it.
NICK Royce...how much petty cash do we have in the safe?
ROYCE I don't know...four thousand?
NICK Give it to me.
NICK And your cell phone.
NICK I need to borrow it for a few days.
ROYCE What do you want me to tell the mayor?
A FIGURE enters shot, pushes a door open into glaring daylight.
CAMERA FOLLOWS him outside to a podium set up before a swarming MOB OF PRESS shouting questions.
ANGLE COMES AROUND to reveal:
Royce, nervous, leaning to the microphones.
ROYCE We in the D.A.'s office are still reeling from the events of this morning, as you can imagine.
ROYCE It's a tragic day for us...for our city...
Kell and Emma on the platform, Garza hovering nearby, CROWDS swarming around them as boarding calls come over the P.A.
system.
Kell is looking around, anxious.
Nick appears on the platform, hurrying.
They see him.
Emma runs, throws herself into Nick's arms as he crouches.
EMMA I wanna see Sarah...
NICK Hey, hey...she's fine, don't be scared.
NICK That's not allowed.
NICK And there's no reason for it.
EMMA This sucks.
NICK I know.
EMMA Why do we have to go?
NICK 'Cause your mom wants to see a few Broadway shows.
NICK You gonna begrudge her that?
EMMA You're kinda full of shit, Dad.
Nick's taken aback -- not sure whether to laugh.
He trades a look with Kell, who's too tense with worry to care.
NICK Okay, you're right.
NICK Maybe I am a little.
NICK But only a little.
NICK The part you can believe is that this is all going to be fine.
NICK Sarah, us.
NICK I mean it.
NICK Okay?
EMMA Okay.
She detaches from her father.
Nick rises to Kell, pulls an envelope, hands it to her...
NICK No credit cards.
NICK Too easy to track.
NICK Meals, hotel, whatever -- pay cash.
...then takes her cell, swaps it for Royce's...
NICK I'll keep this.
NICK It can be traced.
NICK Use this one instead.
NICK Don't answer unless you see it's me.
KELL Anything else?
NICK I love you.
KELL Emma's right.
KELL This sucks.
She embraces him, fears and emotions swirling.
KELL Be goddamn careful.
BLUE - 9-19-08 86. She breaks the embrace.
BLUE - 9-19-08 86. Nick stands, watching them get on the train.
BLUE - 9-19-08 86. The doors close.
BLUE - 9-19-08 86. The train starts out...
BLUE - 9-19-08 86. Nick turns.
BLUE - 9-19-08 86. Garza's been watching -- a look of sympathy for what Nick's going through...
Kell and Emma on the train, watching buildings slide by outside the window.
Kell troubled, holding her daughter...
WE FOLLOW the train traveling a path through canyons of buildings, leaving the city...
ANGLE SWAPS TRAIN FOR CAR as we drift over a bridge and find Nick's car racing across the span...
Nick and Garza enter.
ANGLE COMES AROUND to reveal the house swarming with HIGH-TECH FBI FORENSIC TEAMS turning the house upside-down, tearing things apart, X-RAY SCANNING walls...
Cantrell sits isolated, near tears of frustration, as the place is trashed around him.
He glances up, hearing:
NICK Jesus.
CANTRELL Nick?
CANTRELL These guys won't even let me pack a bag.
CANTRELL Not even a toothbrush.
CANTRELL Davies enters frame, accompanied by FORENSIC TECHS -- not the guys from downtown, but people who work serious ops.
DAVIES We have granules of an unidentified substance in the ice-maker...
DAVIES He holds up a drinking glass with a few ice cubes, runs a black-light wand behind it -- dark granules become visible on each pass, embedded in the ice.
DAVIES I'm betting something lethal.
TECH #1 Like this salt.
TECH #1 Not sodium chloride.
TECH #1 Potassium chloride.
TECH #1 It's a neuro-blocker, stops the heart -- they use it in lethal injections.
TECH #1 You'd be dead before you got up from the table.
Nick tosses the others a grim look.
NICK I'm telling you, Clyde has someone * working with him.
NICK Someone on the outside.
CANTRELL Who?
CANTRELL Who could he have?
NICK Somebody from his past.
NICK Could be * that spook we met on the stairs, * for all we know -- he'd know how to * plant this shit...
CANTRELL Him?
CANTRELL No--why would Clyde let him come talk to us?
NICK To fuck with our heads?
NICK To get us to bring in our ADAs so he could blow them up?
DUNNIGAN * It would be a Clyde move.
DUNNIGAN * But it's * not proof.
DUNNIGAN * (to Cantrell) * Could he have planted this stuff in * your house before he was arrested?
CANTRELL I--I don't know...
NICK Jonas, think -- last few days, have * you used any ice?
NICK Any salt?
CANTRELL I don't use salt--my cholesterol.
CANTRELL Ice?
CANTRELL Yeah--not long ago.
NICK Before or after he was arrested?
CANTRELL I don't remember!
CANTRELL You track your * use of ice, Nick?
CANTRELL You keep a daily * log?
TECH #2 calls from the kitchen:
TECH #2 Heads-up!
TECH #2 Looks like polonium here.
TECH #2 In his tea pot.
TECH #2 Same way the Russians killed Litvenenko.
TECH #2 Took him two weeks to die.
TECH #2 It's an exotic isotope.
TECH #2 All you need is a trace amount.
TECH #2 Rips through your organs and bone marrow.
TECH #2 Nick's been listening, thunderstruck, paler by the moment.
TECH #2 He looks to Cantrell sitting there, quiet and shaking.
NICK * I'll buy you a new toothbrush.
DRIFTING IN on a reflective glass skyscraper -- spectacular.
The door opens, revealing Nick, Cantrell, et al.
They come into the room...actually, "room" undersells it.
It's the most spectacular suite known to man -- huge open floor plan, with a stunning view of all the downtown buildings surrounding us.
NICK Holy shit.
CANTRELL Nice?
DAVIES I'm actually a little jealous Clyde didn't pick me.
DAVIES Cantrell laughs -- and it lightens everybody's mood.
DAVIES Nick * drifts to the windows, gazing out, as: *
DUNNIGAN It's the presidential suite.
DUNNIGAN Last person who stayed here was actually a president.
DUNNIGAN Of a country.
DUNNIGAN Security here is amazing.
NICK * It's not bad, Jonas.
NICK * I think you can muddle through.
DAVIES You're muddling with him.
DAVIES I don't want you back at your house until my people sweep it.
DAVIES You need pajamas, buy some in the shop downstairs.
DAVIES Nick nods, pulls Sarah's reports from his briefcase.
NICK The background check my office was compiling -- these properties we * think Clyde owns?
NICK If he is working * with somebody, they could be * operating out of any of these.
NICK We * should check them.
DUNNIGAN I'll try to wrangle additional * manpower.
DUNNIGAN Big job.
DAVIES (pages the report) * No shit.
DAVIES This is quite a list.
DAVIES Over * forty locations?
NICK It's not even complete.
NICK Sarah was * in the middle of it -- untangling property ownership from under assumed names, shell companies.
NICK She's the expert on all that.
CANTRELL * Fellas...
CANTRELL * I'm grateful for all your efforts.
CANTRELL * I just wanted to say it.
NICK Save it for tonight.
NICK Hope you're in the mood for Chinese takeout.
CANTRELL Where are you going?
NICK That stuff in your house -- it's all gone too far.
NICK I started this.
NICK I owe everybody at least one last try at defusing it.
A STEEL DOOR opens.
Clyde steps out, shackled, blinking at daylight.
He comes down a short flight of steps...
CAMERA COMES AROUND to reveal his surroundings: not within prison walls, but rather behind the prison -- a loading area we haven't seen, comprised of fences and razor wire.
Nick walks in the rear gate, passed through by Warden Iger himself -- this is clearly an off-the-books meeting.
Nick and Clyde walk to each other, meet halfway.
CLYDE Interesting location you've chosen.
NICK I thought we'd have some privacy.
CLYDE For what?
CLYDE A talk?
CLYDE Or...
CLYDE Maybe you've decided to take Detective Dunnigan's advice.
He's noticing GUARDS atop the prison wall and surrounding roofs -- all with sniper rifles.
NICK Be the perfect place for it.
NICK Outside the wall.
NICK Look like you were shot trying to escape.
Nick and Clyde below.
A SCOPE suddenly rises into frame, turning our shot into a SNIPER SCOPE POV, jumping Clyde's face into magnification.
He smiles in the crosshairs...
CLYDE You have some kind of signal worked out?
CLYDE You scratch your nose and blam, I'm a goner?
NICK Something like that.
CLYDE Might solve all your problems.
CLYDE What's stopping you?
CLYDE Afraid of the blowback?
NICK No.
NICK It's to prove a point.
NICK Just because I have the power, doesn't mean I have to use it.
CLYDE Ah.
CLYDE Nice.
CLYDE Good one.
NICK One can show mercy.
CLYDE Mercy.
CLYDE Right.
NICK Yeah.
NICK So why don't you?
We see Clyde's brain bend a little -- trying to wrap his head around it.
It's almost painful for him.
CLYDE I think we've come a little too far for that, haven't we, Nick?
CLYDE I mean, what do I say?
CLYDE Sorry, my bad?
CLYDE Which way to the execution chamber?
NICK Don't give me that.
NICK Death doesn't scare you.
CLYDE Yeah, but...we're in the flow of this now.
CLYDE You cry havoc, you let slip the dogs of war, you go with * it.
CLYDE You don't just stop because * someone says hey wait.
CLYDE By then the dogs are dragging you.
NICK Until one side admits defeat.
NICK What if I did that?
NICK What if I said...
NICK ...you were right.
NICK I was wrong.
NICK What if I say I should have prosecuted both men ten years ago?
CLYDE I'd say you're making progress.
CLYDE You should have, you know.
CLYDE Prosecuted both.
NICK I'd have lost.
CLYDE With your head held high.
CLYDE And without any blame from me.
Nick's CELL RINGS -- he turns away, answers:
NICK Yeah...
NICK She is?
NICK Great news.
NICK I'll stop on my way back.
NICK And Royce?
NICK Put some get- well flowers in her room, they sell 'em in the lobby.
NICK Thanks.
NICK Six hours in surgery.
CLYDE But she's okay -- good.
CLYDE Miss Lowell is a fine young woman.
CLYDE Oh, hey...your wife and little girl get out of town all right?
NICK You asking that question makes me want to scratch my nose.
Clyde glances around at the snipers with a laugh.
CLYDE Just a guess.
CLYDE It's what I would do.
CLYDE Get 'em out, make sure they're safe.
CLYDE C'mon.
CLYDE Like I'd ever have hurt them anyway.
NICK No?
CLYDE There are limits.
CLYDE Even in war.
CLYDE I may be many things, Nick.
CLYDE But I'm not Clarence Darby.
CLYDE I'm not Rupert Ames.
CLYDE I'm not that kind of monster.
NICK What kind are you?
CLYDE Not the kind who'd hurt your wife and child.
CLYDE Christ, look at me.
CLYDE Mine were my salvation -- then they were killed -- and all I had left was this.
CLYDE Life without them in this fucking charnel-house world.
Pause.
Drawing close:
CLYDE It hurt to lose them, didn't it?
CLYDE Your family.
CLYDE Even knowing they'd come back.
NICK Yeah.
CLYDE Imagine knowing they wouldn't.
NICK I can't.
NICK I can't imagine that.
CLYDE Good.
CLYDE I envy you.
CLYDE For me, knowing * mine won't come back is the only thing that's crowded my thoughts for ten years.
CLYDE If I could take a rusty knife and cut out that part of my brain, I would.
NICK I won't make any more deals with murderers.
NICK If hearing that makes a difference...if that was the point of all this...you've won.
NICK We see Clyde's brain hurting again -- he's trying to believe that, would like to believe that...
CLYDE Counselor.
CLYDE I have no doubt, as we stand here, that you really believe that.
CLYDE I wish I could.
CLYDE Are we done?
CLYDE You gonna scratch your nose, or can I go?
CLYDE Silence now.
CLYDE Nothing left to say.
CLYDE They turn and walk in opposite directions...
...and Clyde is brought in, locked into gloom as the doors SLAM behind him.
He stands, staring at the darkness...
The sun is setting...
...as Nick drives back into town, crossing one of the bridges.
(Not Cantrell's hotel, but one close by.)
A SIGN reads: "A.B.A.
Dinner."
PEOPLE are entering, passing a GREETER.
ANGLE FINDS Judge Burch arriving...
A SECRETARY answers the ringing phone:
SECRETARY Judge's chambers.
VOICE ON PHONE Laura?
VOICE ON PHONE Laura, that you?
SECRETARY I'm sorry, Judge Burch is gone for the evening.
VOICE ON PHONE Dang it.
VOICE ON PHONE Listen, honey, I flew in from Galveston for this A.B.A thing Laura invited me to -- just got here and they said it was moved.
VOICE ON PHONE You got a number, address, anything?
Nick peers in.
Sarah's in bed, leg braced, in traction.
She's awake but groggy -- which isn't stopping her from giving instructions to Royce, who's scribbling notes at her bedside:
SARAH ...tell Hansen we need hard info on those addresses...don't let the shell game on ownership title slow him down...at this point we'll take educated guesses...
SARAH Sarah looks over, sees Nick step in, gives him a weak smile.
NICK Hey.
SARAH Hey.
SARAH Nice flowers.
SARAH Thanks.
SARAH He comes to the bed, takes her hand, squeezes it.
NICK How you doing?
SARAH This place has great drugs.
SARAH Damn.
SARAH I should've totaled my leg long ago.
SARAH But her emotions are in turmoil -- she puts her hands over her face, holding back a sob.
SARAH They're all dead?
NICK I'm afraid so.
NICK Sarah lets herself cry.
NICK Nick waits, then: *
NICK You're alive.
NICK That counts for a * lot.
NICK * (beat) * I'm sorry I put you in harm's way.
She absorbs that, angrily wipes her eyes.
SARAH It wasn't you.
SARAH It was that son of a bitch.
SARAH I hear he's threatened Jonas?
NICK We're all over it.
NICK Jonas is safe -- * out of reach.
Cantrell on the upper level, wearing brand-new sweats, white cane tapping the unfamiliar place, Betsy at his side.
He follows VOICES around the corner...
Inside a room, Garza's playing poker with three other cops: LASZLO, FLEMING, and MITRIUS.
CANTRELL Who's winning?
FLEMING Laszlo, the cheatin' prick...
LASZLO Yer mama...
GARZA Wanna sit in?
CANTRELL If I had my Braille set, I'd clean you out.
CANTRELL Not much of a game if you have to tell me what my cards are.
GARZA Right...sorry.
GARZA The other guys toss Garza a look -- what a moron.
CANTRELL People forget.
CANTRELL No worries.
CANTRELL Enjoy your game, fellas.
FLEMING Need help?
FLEMING Want one of us should walk you down?
CANTRELL I'm good.
CANTRELL Unfamiliar places take me a little longer.
CANTRELL But I get there.
GARZA Holler if you need anything.
GARZA Okay, who's in, who's out...
WAITERS setting out salads, guests taking seats, as:
M.C. Good evening.
M.C. Sorry for any confusion our last-minute change of location might have caused...
That incredible city view -- skyscrapers all around, aglow with lights.
Cantrell enters frame, drawn to the glass...
A POLICE HELICOPTER IS ROARING slowly past out there, drifting among the buildings at our eye level.
Cantrell raises his hand, places it on the glass, feeling the vibrations...
The copter's searchlight sweeps the windows, highlighting him briefly with incredible light he can't see...
...but we can see the copter going by from here, searchlight playing over Cantrell's building -- which is plainly visible just across the way.
ANGLE WIDENS to find Judge Burch at a table, as:
M.C. ...please join me in a warm welcome for our keynote speaker this evening, Judge Laura Burch...
M.C. She rises and heads for the podium amidst APPLAUSE...
Nick exits, arms loaded down with bags of takeout, talking on his cell phone as he heads for his car:
NICK ...yes, you pain in the ass, of course I got your kung-pao...you think I'd forget...just don't give Betsy any, I can't deal with dog farts all night...
Cantrell's sitting in front of that incredible view with Betsy at his feet, on the phone:
CANTRELL How long, man, I'm starving...
Nick gets to his car, checks his watch -- and pauses.
The time reads: "7:27."
Nick is suddenly hit with a momentary sense of dread.
He glances up the street...
ANOTHER ANGLE reveals Nick in deep f.g.
ANOTHER ANGLE looking up the broad avenue -- in the distance stands Cantrell's skyscraper.
NICK I'm minutes away.
NICK Relax.
NICK Nick shakes off his misgivings, hangs up, gets in the car...
Cantrell eases to the floor, sits with Betsy.
He strokes her fur.
She WHINES, uneasy.
CANTRELL It's okay.
CANTRELL It's gonna be okay.
Judge Burch at the podium:
JUDGE BURCH ...Jonas was upset not to be here with you tonight...a personal matter came up...but he wanted me to give you all his fondest regards...
ANGLE LOOKING UP at Cantrell's hotel -- a FIGURE steps into our shot, his back to us.
He pulls a cell phone from his pocket, flips it open, sees the time: "7:29."
The thumb starts pressing numbers -- boop...boop...boop...
ANGLE DRIFTING ACROSS THE FLOOR -- Cantrell and Betsy against the incredible city view...
He finally gets fed up with that surgery collar she's worn the entire movie, reaches around, unsnaps the plastic.
He puts the collar aside, gently ruffs her shaggy neck.
CANTRELL There.
CANTRELL That's better.
CANTRELL He puts his arm around her, taking comfort in her presence.
CANTRELL A quiet, pensive moment...
Nick driving, a block from the hotel now...
...as the FIGURE finishes dialing.
The thumb hovers a moment, then presses "send."
We hear the call RINGING through...
...and Cantrell hears a strange SOUND...almost like a phone ringing -- sort of close but not -- weirdly muffled.
He looks around, trying to pinpoint it.
His head finally swivels down to Betsy lying at his side.
She's WHINING, getting a little freaked, licking her stitches...
Cantrell's hand travels down her fur to her belly...fingertips tracing the stitching...and what he can't see is the strange glow building under her skin...
But he can sense it.
His eyes widen slightly...
...and WHAM!
The room is swallowed in a DETONATION --
-- which BLOWS OUT THE ROOM IN A HUGE EXPLOSION, the rows of windows vanishing in a storm of flame and shattering glass...
Judge Burch and the others gasp as the explosion lights up the night from the building across the way...
Nick slams on his brakes -- he cranes forward, gazing up in horror as the explosion is reflected in his windshield...
The blast kicks from the face of the building, fireball rising with eerie grace into the night sky, as:
The FIGURE steps into frame, pockets the cell phone.
CAMERA PIVOTS BEHIND him, losing Cantrell's building and bringing the other hotel into view -- the one with the lawyers...
Nick jumps out, stunned.
He runs up the street toward the hotel as glass and debris rains onto the sidewalk...
People crowd to the glass, staring out at the skyscraper across the way -- at the smoking ruin that was once a floor...
...and the FIGURE bends down, picks something up.
He hefts it onto his shoulder: a LAWS ROCKET-LAUNCHER.
He flips up the sight, takes aim at the other hotel, fires...
WHOOOSH -- the rocket streaks, leaving a contrail...
FAST CUT: Judge Burch and those around her reacting as the glare of the rocket approaches in a heartbeat --
WHAM!
OUR SECOND EXPLOSION of the night takes out the ballroom, killing dozens, blowing flame and debris across the room...
Nick sees it: the contrail, the second blast, all of it.
It stops him dead in his tracks.
Just overwhelmed.
Garza and his guys come stumbling and bleeding from the room * they were in.
They get to the top of the stairs, find the * front of the suite open to the windy sky outside...
FLEMING ...we need help up here...
GARZA Jesus Christ.
GARZA What the fuck hit us?
Nick stares up, wondering the same thing as we
A 30-foot-high hand-painted domed ceiling above, an equally huge ROUND TABLE below -- an imposing room that says power.
Nick is ushered in.
A DOZEN OR MORE PEOPLE are seated -- top- echelon city brass -- political, fire, police.
Also present are Davies and Dunnigan.
(Dunnigan is not seated -- he's getting his ass reamed today.)
The top dog: THE MAYOR.
He's seething but not a screamer -- a man who keeps it tightly reined:
MAYOR We're worldwide news this morning.
MAYOR Almost twenty dead, among them some of this country's top attorneys.
MAYOR I had friends in that room.
MAYOR Hell, I almost attended myself.
NICK The second explosion.
NICK I saw a rocket * fired.
NICK Clyde does have somebody on the outside.
MAYOR * What you saw or think you saw is * beside the point.
MAYOR * What matters is * that the FBI wanted to rendition * this man out of my city.
MAYOR * The reason * he's still here causing havoc is you.
MAYOR * You wanted to prosecute this case.
MAYOR * Your ambition kept him here * and provoked this tragedy.
DUNNIGAN ...not entirely fair...
MAYOR Detective.
MAYOR Your job is hanging by a thread.
MAYOR I'd think a man of your experience would know when to keep his mouth shut and his ass covered.
Dunnigan -- formidable though he is -- looks away, keeps his mouth shut.
The Mayor approaches Nick, looks him in the eye.
MAYOR When I go in front of the cameras today -- unlike some people who seem unwilling to do so when asked -- I'm going to make goddamn sure the media doesn't hang this abject disaster around my neck.
MAYOR Why?
MAYOR Because I'm hanging it on yours.
MAYOR You're done.
MAYOR Gone.
MAYOR Fired.
MAYOR Non- existent.
MAYOR Get the fuck out.
People going about their business.
Nick exits, dazed, comes down the steps.
He sits on a step, vacant -- a man completely at a loss and out of options.
His CELL RINGS.
He rouses himself, flips it open.
CLYDE (V.O.) Hey.
CLYDE (V.O.) Some legal team from the mayor * showed up here this morning.
CLYDE (V.O.) I hear * you're off the case.
CLYDE (V.O.) Told you they'd * scapegoat you, didn't I?
CLYDE (V.O.) Nick?
CLYDE (V.O.) You there?
NICK * How'd you kill Jonas?
NICK * I know about the second explosion, I saw the contrail, so I know you got somebody working for you.
NICK * But the first explosion -- how?
CLYDE Say you find a guy with a bad cocaine problem.
CLYDE Hungry ex-wives.
CLYDE Greedy mistress.
CLYDE Heavy gambling debts.
CLYDE ...a bizarre sound occurs on the line -- an unidentifiable SHRIEKING SOUND that grows and rapidly dissipates...
CLYDE Say that guy's a veterinarian.
CLYDE You * hand him a million in cash, he'll * do what you ask.
CLYDE Especially if he's * looking to blow town for good...
NICK It was...inside the dog?
CLYDE You own the vet, you own the dog.
CLYDE Explosive wasn't even that big.
CLYDE Stuff I use, it didn't have to be.
CLYDE Hidden in plain sight.
CLYDE That's my specialty.
CLYDE Haven't you figured that out yet?
Nick sighs, rubs his eyes, can barely even speak.
CLYDE What's next for you?
CLYDE Mulling career options?
CLYDE I suppose law is out.
NICK I'm trying to get over my friend being dead.
NICK Aside from that, fuck you.
CLYDE Fair enough.
CLYDE I'll miss you Nick.
CLYDE It was a good dance.
NICK Didn't bring your family back, though, did it?
NICK Has it made you feel better?
NICK All this?
NICK You done making your point?
CLYDE Just warming up.
CLYDE This is Clausewitz shit, my friend.
CLYDE Total war.
CAMERA PUSHING IN on Nick, listening, as:
CLYDE I'm gonna pull the whole thing down.
CLYDE I will topple the gleaming pillars and drag the whole fucking diseased, corrupt temple down on my head.
CLYDE Stay tuned.
CLYDE It'll be Biblical.
Click -- line goes dead.
Nick sits staring at the phone...
Nick enters, finds Sarah crying.
A WALL-MOUNTED TV IS PLAYING A NEWS REPORT of the explosions -- file footage of Jonas Cantrell pops up.
Nick drifts over, sits at her bedside, as:
REPORTER ...going live now to City Hall where Mayor Tilden is about to make a statement...announcing, we're told, among other things, the dismissal of District Attorney Nick Price...
REPORTER The IMAGE cuts to the Mayor stepping to the mic.
MAYOR Thank you all for gathering on this solemn and anxious occasion...
WHITE - 9-7-8 103. Nick MUTES it.
WHITE - 9-7-8 103. He and Sarah don't speak for long moments -- he's waiting for her to pull herself together.
WHITE - 9-7-8 103. She finally does, going into professional mode, pulling her laptop and files and reports around her.
SARAH We got the latest batch of background in.
SARAH Hansen and the other guy did some good work here--
NICK Sarah.
NICK Give it a rest.
NICK It's over.
NICK We're done.
NICK I'm done.
NICK The mayor is nailing my coffin shut.
NICK The best thing you can do right now is distance yourself from me as much as you can -- see what you can salvage of your career.
NICK Sarah is staring at him with "fuck you" in her eyes.
NICK She picks up a multi-page list of addresses, hands it to him.
SARAH This lists over fifty shit-value properties in industrial zones that nobody in their right mind would want to own -- stuff around chemical plants, factories.
SARAH All are owned by Benson Clyde.
SARAH Look at twenty-two.
Nick, not caring, scans down to:
NICK "Joe's Lube-and-Drive Garage."
NICK Went out of business in '94.
NICK Now why would Joe's extinct Lube- and-Shit Garage be of the slightest possible fucking interest to you, me, or anyone?
SARAH The garage, not so much.
SARAH But the address.
SARAH Look at the location.
SARAH Nick looks down at the list again...staring...
A shitty garage in a shitty industrial park.
Bordering it, on the other side of some fencing, are municipal train tracks.
Nick's car pulls up.
He gets out.
It's a ghost town here.
BLUE - 9-19-08 104. He goes to the garage window -- glass thick with dirt.
BLUE - 9-19-08 104. He wipes with his sleeve, but it doesn't help him see in.
TIGHT ON ROLL-UP DOOR -- a CAR JACK jams in under the lip.
We hear CRANKING and the door rises...
Nick drops down, peering in.
He squeezes under the door, stands up.
Gloomy in here.
He hits the door switch -- it RATTLES up * on its tracks, flooding the place with light...
He looks around.
Cobwebs.
Dust.
A CAR under a tarp on the hydraulic floor-lift.
Old shelves and pallets of tools.
Rust.
Grime.
The crap of ages.
He sighs, turns and walks out...
...and pauses.
Something tickling his brain.
Suddenly, a SHRIEKING COMMUTER TRAIN blasts by -- gone, dwindling.
It was a bizarre, distinctive sound...like the one Nick heard during his last phone call with Clyde.
Nick stands frozen, pieces in his head tumbling and threatening to fall into place.
Something about the shape of that car under that tarp...
He turns, staring at it.
Goes back in, drawn to it -- it's long, distinctly old-school, with sharp boxy corners...
He draws the tarp off -- finds a 1965 Lincoln Continental, midnight-blue, in excellent condition.
The last time he saw it, it was parked in a carport at Benson Clyde's farmhouse.
What's it doing here?
More pieces falling into place.
Nick leaves the garage again, walking out...
CAMERA TRACKS HIM across the tarmac, and as we come around the corner of the building, we reveal:
The County Correctional Annex is right there, a backwater corner of the prison not sixty feet away...
Nick stares up at it -- a very curious location indeed.
FAST CUTS: Nick searching...behind shelves...the toilet...in closets...the grimy little office...
He stops.
Looks at the car.
There's a mechanic's pit below that hydraulic lift.
He goes to the control, hits "up"...
ANGLE FROM MECHANIC'S PIT Nick's face comes slowly into view as the hoist rises...
FADE TO BLACK IN BLACKNESS, WE HEAR: Boop-boop-boop...a cell being dialed.
The line RINGING.
A voice answering:
DUNNIGAN Dunnigan.
NICK Do we finish this tonight?
DUNNIGAN Nick?
DUNNIGAN Jesus...
DUNNIGAN Look.
DUNNIGAN No hard feelings, but there is no "we."
DUNNIGAN You're radioactive.
DUNNIGAN I * can't even be seen talking to you...
NICK I know who he's got on the outside.
NICK I'll ask again.
NICK Do we finish this tonight?
NICK Poor Dunnigan looks tortured.
NICK He catches Garza's eye...
A TRAIN SHRIEKS through shot, revealing:
The garage quiet in moonlight.
The area deserted.
Beat.
The garage door rolls up on its tracks.
Darkness within.
A PAIR OF HEADLIGHTS kick on, blinding us.
The Lincoln emerges, moves off into the night as the door rolls down again.
We hear SOFT STATIC from a police radio, and a voice:
DUNNIGAN All units.
DUNNIGAN Subject vehicle is on the move.
DUNNIGAN ANGLE WIDENS to reveal we're in an UNMARKED CAR -- Dunnigan *
at the wheel, Nick beside him.
Dunnigan's on the radio:
DUNNIGAN Everybody maintain distance.
DUNNIGAN Dunnigan puts the car in gear, pulls out...
DRIFTING MAGICALLY THROUGH the downtown skyscrapers...neon- lit rooftops...city lights reflecting off glass buildings...
AN FBI HELICOPTER drops into shot.
CAMERA COMES AROUND, pacing, the copter's reflection in the buildings we're passing...
SKYSCRAPERS pass the lens below us...
There's a midnight-blue Lincoln traveling the streets far below.
It turns a corner, moving up a long boulevard.
CAMERA PIVOTS around a skyscraper, following...
The Lincoln cruising, cold reflections of street lamps kicking off sheet metal, flowing along its body and windshield...
WE START ZOOMING AND RACKING FOCUS to the unmarked cars tailing it in traffic....visually, it becomes a surreal dance of headlights and traffic signals...
A POLICE COPTER joins the FBI copter in the air...both cruising eerily against a kaleidoscopic wash of city lights...
VOICE #1 (V.O.) Maintain two thousand foot ceiling...
VOICE #1 (V.O.) Subject vehicle turning south off of Hudson...into an alley...
DUNNIGAN Hang back...hang back...
The Lincoln pulls to a loading door.
The door rises...
...and the Lincoln enters.
It stops next to a LARGE CUBE VAN with the logo: "Nomos Custodial Services."
CAMERA PUSHES IN as the car door opens, feet step out...
TILT UP to Clyde dressed in a custodial services uniform.
He slams the car door, gets in the van, fires up the engine...
Far below us, the van emerges from the same door, comes out of the alley and back onto the street...
VOICE #2 (V.O.) I got a white van...large cube type...think he switched vehicles...
VOICE #2 (V.O.) moving north again on Hudson...
DUNNIGAN Five and six, stick with that building in case he's trying to cowboy us.
DUNNIGAN All other units, stay with the van...
DUNNIGAN Dunnigan pulls out into traffic, resuming the tail...
VOICE #3 (V.O.) I have visual on van.
VOICE #3 (V.O.) Logo on side reads "Nomos Custodial Services."
NICK Where the hell is he going?
The glorious old building looms above us.
TILT DOWN to reveal a red carpet event brewing -- LIMOS AND LUXURY CARS pulling up, GUESTS in expensive attire getting out...
The NOMOS VAN STEALS THE FRAME as it drives past and turns to go around the back of the building...
A LIMO STEALS THE FRAME BACK as it pulls to the curb.
The Mayor steps out, waving and smiling for FLASHING CAMERAS...
Nick and Dunnigan drive past all the hoopla...
NICK You don't suppose Nomos Custodial * has a service contract with City Hall, do you?
NICK Off Dunnigan's look of "oh shit"...
TIGHT ON A CARD SCANNER as a card is swiped.
THUNK -- the lock disengages.
TILT UP to Clyde as he rolls a loaded custodial cart (with mops and trash barrel) inside...
A GUARD mans the security desk -- he glances up from a BANK OF LIVE-FEED VIDEO MONITORS as Clyde rolls his cart in.
SECURITY GUARD Mr. Nomos!
SECURITY GUARD Ain't seen you around.
CLYDE Ted...had to get that vacation in.
CLYDE Visited my sister in the Keys...
SECURITY GUARD Nice.
SECURITY GUARD Good for you.
CLYDE Hey, what's all that hoopla at the main entrance?
SECURITY GUARD Mayor's got a big fuckin' thing.
SECURITY GUARD Thousand dollar a plate whatever.
SECURITY GUARD They say the Governor might come.
CLYDE I'll stay out of their way.
SECURITY GUARD They're up on six, avoid that floor.
SECURITY GUARD They got more security than God...
Far below: The entrance lit up with arriving cars and guests,
CAMERAS FLASHING... A HELICOPTER DRIFTS through the shot just below us in SLOW- MOTION, rotors thrumming eerily...
...while Clyde rides up.
He stops at five, gets out...
...and rolls his cart up the hallway.
MUFFLED MUSIC from the floor above.
He comes to a door, sorts his keys...
...and enters in darkness.
Moving swiftly, he reaches into his trash barrel, pulls a gleaming STEEL BRIEFCASE from under the shredded papers -- he strides to the judge's dais, lays the case atop it, turns and heads back to his cart...
...as a STREAM OF TACTICAL COPS stampede into the building and up the stairs.
ANGLE FINDS Nick, Dunnigan, and Davies looming over the nervous security guard:
DUNNIGAN What floor?
SECURITY GUARD I told him to avoid six...
SECURITY GUARD There...
SECURITY GUARD On a monitor: Clyde rolls his cart from the courtroom...
SECURITY GUARD That's the main courtroom on five.
NICK That's right below the ballroom.
NICK The Mayor's event.
Early arrivals are coming up, entering the ballroom.
The place * is crawling with SECRET-SERVICE TYPES in suits.
Clyde comes down the hallway B.G., rolling his cart...
F.G., ANGLE FINDS tactical cops with machine guns pouring quietly up the stairs, taking up positions just around the corners, poised and tense.
TIGHTEN IN as the TAC LEADER uses a small mirror to peek around the corner and spot Clyde:
TAC LEADER Subject in sight.
TAC LEADER Do we take him?
Nick, Dunnigan and others are racing up the steps.
Dunnigan * raises his radio to say yes, but:
NICK No.
NICK Let him go.
NICK We know where to find him.
NICK Let's get to that courtroom.
NICK Dunnigan hesitates -- against every instinct in his body.
DUNNIGAN I hope you know what the fuck you're doing.
DUNNIGAN Negative.
DUNNIGAN We're letting him go.
DUNNIGAN All units hang back.
DUNNIGAN Repeat.
DUNNIGAN We are letting the subject go.
The cops trade surprised glances.
The elevator DINGS.
Clyde gets on, the doors close.
The cops swarm up the hallway...
This all happens fast: Bang -- the doors slam open.
Nick leads a huge phalanx of cops and FBI in, weapons and flashlight beams stabbing in all directions.
NICK There.
NICK They race to the judge's dais -- the steel case.
DAVIES Don't touch it!
DAVIES Could be motion sensitive!
DAVIES Davies shoves his way to the front, grabs a small hand-held
drill from one of his guys' tactical vests:
DAVIES I need light!
DAVIES Dozens of beams converge.
DAVIES Davies places the drill, goes to work on the case...grind, grind...
VOICE #4 (V.O.) I have visual...suspect leaving the * building...different service exit...
Clyde exits a loading dock, gets in his van...
...grind, grind...the drill taps through.
Davies yanks it, feeds a fiber-optic tube into the hole, puts his eye to the eyepiece.
He swivels the tube carefully, peering inside...
DAVIES * Crap.
DAVIES * * (glances up) * Explosives.
DAVIES * Nasty ones.
DUNNIGAN What?
DUNNIGAN C-4?
DUNNIGAN Davies takes his eye from the eyepiece, looks at them.
DAVIES C-4 is for girl scouts.
DAVIES This is malglinite.
DAVIES Take out the whole floor above us...maybe this entire corner of the building...
NICK Can you open it?
NICK Disarm it?
DAVIES No, we got tripwires.
DAVIES We open this lid, instant karma's gonna get us.
DAVIES Don't see a motion sensor.
DAVIES Trigger looks simple...dial a cell phone, incoming call arms the trigger -- trigger's set to count down from forty seconds, then boom.
DAVIES That call comes in, we have forty seconds to get as far away from this thing as possible.
DUNNIGAN Alert the mayor's security team.
DUNNIGAN * Evacuate those people upstairs -- * clear that ballroom, go!
NICK No!
Dunnigan turns on him, instant shouting match:
DUNNIGAN No?
DUNNIGAN What the fuck are you talking about, this could go off any second!
NICK He won't set it off until that room is full!
NICK People are still arriving, red carpet shit, that's at least another half hour!
DUNNIGAN I will not take that risk!
NICK You have to!
Beat.
Nick, no longer shouting, but intense and fast:
NICK If I'm him, I've rigged cameras in that ballroom -- live video feed -- first sign of an evacuation, I trigger the bomb.
NICK We have to think ahead of this fuck!
NICK Pause.
NICK Looks traded.
DAVIES I'm open.
DUNNIGAN Okay, Nick.
DUNNIGAN What's the move?
Clyde slams the van door, gets in the Lincoln.
He pulls a handheld CLAMSHELL VIDEO MONITOR -- it shows a LIVE FEED of people entering the ballroom, mingling as they arrive...
Clyde smiles, starts the engine...
The Mayor enters, waving to everybody, shaking hands...
The garage door rises.
The Lincoln backs in, stops on the hydraulic lift.
Clyde gets out, throws the tarp over it.
Briefly checks his clamshell.
Still plenty of time...
He raises the lift a few feet, drops down and crawls under the car into:
Duplicate controls.
He hits the button and the car sinks down atop us, settling to the floor, sealing us into darkness.
WHITE - 9-7-8 113. Beat.
WHITE - 9-7-8 113. A BRIGHT LIGHT turns on -- one of those gazillion
candlepower flashlights.
Clyde aims it and we see:
A TUNNEL hewn into the wall of the mechanic's pit.
Just large enough for Clyde to crawl into.
He does...
Hand-dug, rough dirt held up by two-by-four bracing.
A wheeled platform is the transport -- Clyde's on his back, pulling himself along by an overhead rope, hand over hand...
Clyde emerges in the suffocating darkness of a sub-basement laid into a foundation that dates back to the Civil War.
He crawls free, shining his light as rats scurry in shadows...
He's on his hands and knees at first because the ceiling's so low.
He's finally able to rise, moving along at a crouch...
...and emerging into a proper sub-tunnel.
Now able to walk normally, he navigates the tunnels and comes to:
We're just below the solitary wing.
Clyde has it rigged with all his needs: computer, spare cell phones, various kinds of clothing, even a shelf lined with snacks.
He quickly shrugs off his custodian's outfit, revealing his prison jumpsuit beneath.
He gazes up a welded steel ladder (identical to four others in a row -- one for each cell).
He checks his clamshell one last time, tweaking the bad reception with a relay -- ballroom looks full.
He clicks off his lamp and clamshell, sets them on a shelf...
He goes up the ladder to a hatch in the ceiling...
...and enters through a swiveling portal concealed behind the toilet.
In deep darkness now, he pulls his cell phone, starts inputting a number -- boop...boop...boop...
And he freezes.
Realizing...
There's somebody in there with him...a silhouette sitting on the floor by the door.
The figure reaches out, pushes open the outer door a bit.
Faint light spills in, revealing:
NICK I came to talk.
NICK Guess who wasn't in his cell?
NICK Imagine my surprise.
CLYDE Imagine mine.
NICK Beautiful how you played us.
NICK Getting yourself tossed into solitary -- * pre-rigged with exits from all five * cells.
NICK Whichever one we put you in, you had your bases covered.
NICK I thought I was such a bad-ass putting you down here.
NICK Turns out I was doing what you wanted.
CLYDE That's how you play.
CLYDE Make the other guy think it's his idea.
CLYDE You came to talk, so talk.
NICK Been thinking.
NICK If I'd done things differently -- made different decisions from the start -- we wouldn't have gotten to this point.
CLYDE But it happened.
CLYDE And here we are.
NICK Here we are.
NICK Your decisions put us here too.
NICK This mess is on both of us.
CLYDE You want to hold hands?
CLYDE What's your point?
NICK We can't change decisions we've made.
NICK We can only account for decisions we make from here.
NICK I know what mine will be.
NICK What about you?
NICK You gonna finish dialing that number, or what?
Clyde hesitating, thumb hovering over the number pad.
CLYDE If I don't?
CLYDE What are you offering?
NICK You looking to deal?
CLYDE I'm willing to listen.
NICK Okay, here's the deal.
NICK The deal is...there is no deal.
NICK I told you.
NICK No more deals with murderers.
NICK I'm sticking to that.
NICK That's my decision.
NICK It's what you * taught me.
NICK Strange as it sounds, * I'm grateful for the lesson.
Nick rises, steps out -- pauses, turns back.
NICK Your turn.
NICK You make the right decision, I'll see what I can do for you.
NICK But the wrong decision is one you'll have to live with the rest of your life.
The moment stretches.
Clyde poised -- all down to this.
In * the end, he can't help himself: Boop-boop-boop -- hits send.
CLYDE I'm sorry.
NICK Me too...
Nick pushes the barred door shut...
NICK ...because like I said, it's a decision you'll have to live with the rest of your life.
NICK Which at this point I figure is...
NICK ...another 35 seconds.
...and turns the key in the lock -- klatch.
NICK Check mate.
Clyde hears a SOUND...like a phone ringing -- sort of close but not -- muffled -- like the sound Cantrell heard...
Clyde, realization dawning, thrusts his hand out and jerks the cot blanket up, revealing:
The steel briefcase under his cot.
He glances up to see:
Nick gone.
Clyde scrambles to his portal, yanks on the handle...
ANGLE ON: The hatch handle rattles -- now padlocked shut.
FAST CUT: Dunnigan thrusts himself out of the tunnel, cops grabbing his arms, pulling him free...
Nick comes through the sally-port at a fast stride, through another door, goes up the steps...
Clyde wheels around, frantic as a caged tiger -- he lunges to the door, rattling the bars...
...while Nick pounds faster and faster up staircase after staircase...
Clyde -- enraged, bellowing -- picking up the steel briefcase, swinging it hard against the bars, trying to batter through...
And then stopping.
A self-awareness returning.
Perhaps it's the Clyde that's been missing for years -- the sane one.
Pause.
He sets the briefcase down.
Stands a moment.
He sits down on the briefcase.
Calm now.
Pulls a SMALL PHOTO from his breast pocket.
Gazes at it.
It's his wife and daughter.
He stares at them a while.
Tucks the photo back in his pocket.
Nods.
CLYDE Well played.
CLYDE BOOOOM!
CLYDE The DETONATION is staggering, instantly vaporizing * Clyde and the cell he's in...
...BLOWING the bars right out of the stone on a WALL OF FLAME that overwhelms the lens...
...FLAME HURTLING with express-train force...
...and BLASTING TONS OF BRICK AND MORTAR skyward.
Nick enters the shot as WE DOLLY BACK WITH HIM, walking away from the building going to dust and rubble B.G.
CAMERA PANS HIM AROUND, now following him, as he approaches Davies standing with Iger.
Iger is staring, agog:
IGER Jesus.
IGER * (beat) * Thank God that wing was empty.
IGER A car arriving behind them: Dunnigan getting out, approaching.
IGER How do I explain this to the city?
DUNNIGAN I think the Mayor will have your back.
DUNNIGAN Nick approaches, comes abreast of them.
DUNNIGAN Looks are traded with Dunnigan and Davies.
DUNNIGAN Relief.
DUNNIGAN Fellowship.
DUNNIGAN A touch of sadness.
DUNNIGAN Words aren't needed here.
DUNNIGAN Nick keeps walking, pulls his cell phone, starts dialing.
DUNNIGAN Dunnigan smiles.
DUNNIGAN He knows exactly where Nick's going...
LONG LENS: Nick sitting...waiting...
An ARRIVING TRAIN moves massively into the shot, pulling into the station...
Nick rises.
A SQUEAL OF BRAKES, steel on steel...
Nick engulfed in a crowd of arriving passengers, people getting off, swirling and jostling all around him, wiping frame...
...only two faces he wants to see...
...and there they are...
He sweeps his family into his arms.
The final moments of this movie are all about faces and joy...
...and CREDITS BEGIN as we
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
