ORPHAN
Written by
David Leslie Johnson
February 5, 2007
She's a simple beauty and very pregnant, propped up in a bed, wearing a hospital gown.
A heart rate monitor BEEPS.
She touches her swollen belly, flush with excitement, her eyes full of wonder.
Okayp, just relax.now.
This'll be over Caitti before you know it.
Kate looks up.
Her smile falters-as we REVEAL:
Harsh lights overhead.
-THUNDER rumbles outside.
Kate's on a.
delivery table, legs already in the stirrups.
A sheet hangs- across her belly so we can't see what's going on below her waist.
A DOCTOR and NURSE snap pn gloves, prepare instruments: SHARP BLADES and CURETTES, NEEDLES and FORCEPS.
Kate is stricken.
She tries to sit up.
KATE Wait, I've changed my mind.
KATE I don't want to do this anymore.
KATE The Doctor gives the Nurse an exasperated look.
KATE The Nurse takes Rate's hand, eases her back onto the table.
NURSE Your baby is dead.
NURSE There's nothing.
NURSE else we can do.
NURSE Kate reels, her world turned upside-dowp.
NURSE Emotional free-fall.
KATE No, this isn't what's supposed to happen.
KATE My baby's alive!
NURSE We're so sorry.
NURSE A terrible loss, we're so sorry...
KATE But it's still alive!
KATE It's moving!
KATE Feel it, you can feel it!
KATE Kate tries to put the Nurse's hand on her.belly but the-Nurse- pulls away and hands the Doctor a pair of gleaming.blunt-tipped SURGICAL SCISSORS.
KATE The Doctor leans between Rate's spread legs, disappearing behind the curtain.
KATE Rate gasps.
RATE No, stop!
RATE I want to be asleep!
TOO late for anesthesia.'' The baby's coming.
You're.going to experience some pressure now...
- Kate winces and bites her lip as the Doctor goes about his unseen work.
A GOOD-LOOKING MAN in surgical scrubs stands behind him..
Bizarrely, he's videotaping-the whole thing.
He's Kate's husband, JOHN (late 30's).
He smiles at her from behind -the camera.
JOHN It's okay, honeys You're doing great!
JOHN The Doctor hands the scissors, now slick with gore, to the Nurse.
JOHN H e takes a SUCTION.
JOHN CATHETER and disappears behind-the curtain again.
JOHN The Nurse - presses a button on a vacuum pump and the machine begins to HUM.
JOHN Kate tightly closes her eyes.
KATE This isn't happening.
KATE Wake up, wake up, wake up...
KATE Suddenly -- the thin wail of a BABY CRYING.
KATE Rate's eyes go wide w ith horror as the smiling Nurse approaches with a wriggling bundle wrapped in a blanket.
KATE Blood seeps through the pink fabric.
KATE W e can't see what's inside, but it's moving.
KATE And it's CRYING.
NURSE Congratulations, Mrs. Coleman.
NURSE It's a girl .
NURSE The Nurse offers her the bloody, blanketed bundle.
NURSE Kate screams -
INT. KATE AND JOHN'S BEDROOM - NIGHT -- then snaps awake.
INT. KATE AND JOHN'S BEDROOM - NIGHT She's been having a nightmare.
INT. KATE AND JOHN'S BEDROOM - NIGHT John lies n ext to her in bed.
INT. KATE AND JOHN'S BEDROOM - NIGHT Be stirs, but doesn't wake.
INT. KATE AND JOHN'S BEDROOM - NIGHT Kate slips out of bed and quickly pads to the bathroom;
INT. KATE AND JOHN'S BATHROOM - NIGHT Kate closes the door.
INT. KATE AND JOHN'S BATHROOM - NIGHT We now see that she's not pregnant in reality, only in her nightmare.
INT. KATE AND JOHN'S BATHROOM - NIGHT She slides to the cold floor in t he dark, a hand on her flat belly as she starts to cry...
INT. DOCTOR BROWNING'S OFFICE - DAY Water TRICKLES in a little Zen fountain.
INT. DOCTOR BROWNING'S OFFICE - DAY Kate sits across from -DR.
INT. DOCTOR BROWNING'S OFFICE - DAY -BROWNING, a mousy-haired woman in her 50's.
DR. BROWNING A lot of women experience difficulties around the anniversary of the miscarriage or the baby's expected due date.
DR. BROWNING It's perfectly normal.
KATE I was thinking of" going back to work.
KATE I really thought 1 was doing better.
DR. BROWNING You are.
DR. BROWNING Think about where you were just four months ago.
DR. BROWNING Are you still sober?
DR. BROWNING Kate hesitates.
DR. BROWNING Dr. Browning gives her a penetrating look.
KATE I drove by the wine shop,on my.way.bome the other day.
DR. BROWNING Did you stop?
KATE I really wanted to.
KATE The thought went through m' head, you know.
KATE it wasn't for me, it just might be nice to have a bottle handy in case we had guests.
DR. BROWNING. But you didn't go in?
KATE No.
DR. BROWNING That's all that matters.
DR. BROWNING Let's try to stay focused on the.
DR. BROWNING positive.
DR. BROWNING Grief is different for everyone.
DR. BROWNING You have to take it at your own pace..
DR. BROWNING Keep writing in your journal.
DR. BROWNING You're doing fine.
DR. BROWNING Rate smiles weakly.
DR. BROWNING unconvinced.
Rate hangs curtains over a beautiful picture window.
She steps' back to admire her work, then sighs.
Now what?
Now that she s done, the house suddenly seems-quiet and lonely and too big.
Kate sits in a rocking chair, gazing out a distinctive ARCHED 'WINDOW.
We realize that she's -In a fully furnished and decorated nursery.
Crib, changing table, baby swing.
No baby.
EXT. COLEMAN RESIDENCE - DAY It's a big, dramatic home in an affluent neighborhood.
EXT. COLEMAN RESIDENCE - DAY Kate % crosses the backyard into the nearby woods.
EXT. FOREST - DAY After a short walk, Kate sits by a PEACEFUL BROOK lost in her thoughts.
EXT. FOREST - DAY ,She pulls a JOURNAL filled.
EXT. FOREST - DAY with handwritten entries from her coat pocket.
EXT. FOREST - DAY After a beat,'she begins to write.
Class has just let out, PARENTS arriving to pick up their KIDS.
But the playground is MOSTLY SILENT -- these children an deaf, communicating to one another and their teachers by sign language.
'Kate pulls up in a luxury minivan.
Her five-year-old daughter MAX runs over togreet her.
She's almost- ridiculously cute.
(NOTE: Max doesn't speak.
Her "dialogue" is SIGNED and SUBTITLED.
She wears a REARING AID- to help her read lips.
when people speak to her, they must face her and/or sign.)
Kate kisses Max's'head and helps her into the van, buckling her car seat.
Max shows her an art project she's bringing home.
KATE Wow, did you make this?
Kate's' driving.
She stops at an intersection.
A PREGNANT WOMAN crosses the street in front of them and stops at the corner.
Kate watches her for a long beat as if transfixed...
In the backseat, Max-CLAPS her hands to get Kate's attention.
Kate turns and sees Max pointing to the traffic light.
IVs green.
A car horn HONKS.
Kate snaps -out of it and drives off.
INT. MUSIC ROOM - DAY Kate sits at a baby grand piano,'trying to compose a piece of..
INT. MUSIC ROOM - DAY music.
INT. MUSIC ROOM - DAY She plays a few NOTES, frowns, tries again, takes a pencil and erases what she's written down.
INT. MUSIC ROOM - DAY She pauses to look over-at a beautiful ORCHID in an ornate plants=
by the window.
For a moment, she just stares at it.
Then: 13 1 She's startled by something outside BOUNCING off the side of the house.
She closes her eyes, frustrated.
BANGI EANG1 BANG!
She tries to ignore it, but can't.
Max is playing basketball in the driveway, but the ball's too big for her and the hoop's too.high.
Every time she tries to shoot, the ball falls short and BANGS against the house.
Kate opens-the door, angrily signing as she speaks: Stop banging that against the house!
I'm trying-to work!.
Max gives an abashed look.
Kate sighs.
She knows she was too harsh with her.
KATE -No, I'm sorry..
KATE But just...
KATE take a break for a little while, okay?
KATE Max nods.
KATE Kate goes.
KATE back inside.
KATE A CAR pulls into the-drive..
KATE It's John and eleven--year-old-DANIEL, Rate and John's other child.
KATE Daniel's blonde, brash, and-cocky, the all-American kid.
KATE He's wearing.a Little League uniform.
KATE Daniel runs toward Max.
KATE He steals her ball and dribbles-it around her in circles.
KATE -Max watches glumly.
KATE He offers her the ball, but when she reaches for it, he snatches it away and shoots a lay--up..-
DANIEL Boo -yahl He shoots!
DANIEL He scores!
JOHN Nice one, champ!
JOHN - Daniel pumps his arm and runs inside.
JOHN John walks up the drive, carrying a bouquet of FLOWERS.
JOHN He hands Max the ball and lifts her up to the basket.
JOHN Max happily puts the ball-through'the hoop.
JOHN All right!
JOHN Ginme five!
JOHN She smiles and gives him a high-five as he carries her inside.
Kate has just sat back down at the piano when she hears Daniel tear into the house and run upstairs.
She slumps her shoulders and closes her notebook.
No more work today.
John enters.
JOHN Drapes look'nice.
KATE Curtains.
KATE They're curtains, not drapes.
KATE And haw exciting is my life that -I now know the difference.
He offers her the flowers..
RATE .That's this for?
JOHN Just love you.
JOHN He kisses her as she takes them.
JOHN Some of her gloomy mood melts.
Kate tucks Max into bed.
KATE Ore story.
KATE Then bedtime.
KATE Okay?
KATE Max nods.
KATE happily and picks up a book from her nightstand.
KATE Kate groans inwardly when she sees what it is.
KATE It'.s called.
KATE "We were Going To Have A Baby, .But We Had An Angel Instead."
KATE You want to hear about the baby again?
KATE Max nods.
KATE Kate hesitates, then gives Max a sad smile.
Kate sits on Max's bed, reading and showing her the pictures:
KATE "People send us flowers and cards, but we still miss our baby.
KATE If this just happened to you, I'm sorry you got an angel instead of a'baby.
KATE I.think a baby would have been more fun."
KATE The last picture is a FAMILY WITH A BABY ANGEL watching over them.
KATE Yes, she is.
KATE She's with us every day.
KATE Kate gives Max a gentle kiss on the forehead.
INT. KATE AND JOHN'S BATHROOM - NIGHT Kate opens a medicine chest 'and shakes a PILL from a prescription bottle.
INT. KATE AND JOHN'S BATHROOM - NIGHT She swallows the pill-with a Dixie cup of water.
John watches TV in bed.
Kate enters from the bathroom in a nightshirt and sits on the bed.
She.rubs lotion on her feet.
John watches her, then reaches out, runs his fingers uup and down her back.
Kate freezes.
He can't see the-nervous look that crosses her face.
He moves closer, pushes her hair aside, kissing hex-.
neck.
Kate responds stiffly, trying to get.
in the mood.
He slides a hand around her waist, moves it up to her breast...
KATE I'm sorry.
KATE I can't.
KATE Shit...
KATE She moves away, tears suddenly in.her eyes.
KATE He gives a concerned look, lets her have her space.
KATE A beat.
KATE I'm so sick of feeling like this.
KATE Christ, the kids must thing I'm crazy.
JOHN Will you stop worrying about what everybody else thinks?
KATE How can I?
KATE I saw a pregnant woman today on the way home and I almost lost it.
KATE Just burst into tears with Max sitting right there.
KATE Daniel barely talks to me.
KATE You and I haven't had sex in over a year now.
KATE What if I.never get better?
KATE I don't want to lose you.
JOHN You're never going to lose us.
JOHN I promise you.
JOHN I just wish...
JOHN Have you thought any more about adopting?
KATE I can't even be a mother to the children we already have.
JOHN That's not true.
JOHN The kids understand.
JOHN They just know you're not happy.
KATE But I should be.
JOHN - Do you want another child?
KATE You Snow I do.
KATE More than anything.
JOHN Even if it can-'t be'biologically ours.
JOHN Then what are we talking about this -for?
JOHN Let's do it.
KATE You-don't just adopt a child because you're lonely and depressed.
JOHN That's not why we'd be doing..it.
JOHN We wanted a child a year ago and we still want one, now..
KATE We can't replace our baby.
JOHN No, 'we can't.
JOHN But we can take the' place we made for her in our hearts and our home and give it to a child who needs a family.
Kate, we love being parents.
We're good at it and'it makes.
us happy.
What better reason-do you want?
Kate looks at him for a beat, then smiles and lets her tears fall.
Kate and John are being interviewed by a FEMALE LAWYER.
LAWYER - Are you both employed?
JOHN I'm-an architect at a firm in the city.
JOHN The Lawyer turns to Kate.
JOHN Kate hesitates.
KATE I used to teach music at Yale.
KATE I haven't worked for about a year.
LAWYER - You're sure you want an older child?
LAWYER - - -
With your background, you could have a newborn in as little as a year.
JOHN We've'alread y waited a.long time.
JOHN :We'd lake a child as:quickly as possible.
Well, 'getting an older child-As definitely quicker, not to mention cheaper, but- there's a reason for that.
A lbt of these kids- have serious behavioral problems.'
JOHN We've already signed up for special- needs-'adoption classes.
JOHN Trust me, we're ready for anything.
You must have a lot of love to give.
Are you looking for a boy or a girl?
A girl.
We'd like a little girl.- - -
CAMERA FINDS John's car winding its way along a tree-lined road...
John is driving.
Kate is studying pages and pages of photocopied records in a manila folder.
-John gives her an amused look.
KATE You're not worried about being prepared?
JOHN - There's not gonna be a pop quiz.
JOHN - Kate smiles.
JOHN - She closes the folder and looks at a Polaroid of a happy, seven-year-old Puerto Rican girl stapled to the cover.
JOHN - The name next to the photo is YOLANDA.
It's a pillared mansion with a large porch.
TWO NUNS supervise a' GROUP OF YOUNG GIRLS on a playground.- A sign- out front reads "ST.
CABRINI'S HOME FOR GIRLS."
John's car pulls into the parking lot.
From-2L SHAKY, HANDHELD POV looking out a second floor window, we see Kate and John get out of the'car.
Someone in watching them...
Kate senses movement and looks up...
but there's no one there.
..y
Yolanda; the girl from the Polaroid, is playing with a dollhouse.
The door-opens.
Kate and John are led inside by SISTER ABIGAIL, an African-American nun in her 50's.
SISTER ABIGAIL Yolanda, look who's here to see you.
SISTER ABIGAIL Yolanda, smiles at Kate and John..
SISTER ABIGAIL She runs over to greet them, but stands just out of their reach.
SISTER ABIGAIL -Kate kneels in front of her.
RATE Don't you look pretty!
YOLANDA 6ister Abigail put ribbons in my hair.
YOLANDA See?
KATE Wow, that was nice of her.
KATE Look, we brought you something for the trip tomorrow.
KATE She hands her a bag of activity books and a "Travel Turtle," a kid- sized lap desk for coloring in the car_ Yolanda's face lights up.
SISTER ABIGAIL What do you.say?
YOLANDA Thank you.
YOLANDA Kate reaches out to her, but Yolanda pulls-away, focusing all her attention on her presents.
YOLANDA Rate gives her a sad 'smile.
Yolanda is drawing a picture, "Travel Turtle" on her lap.
Kate and Abigail sit nearby, watching.
Kate seems worried.
Abigail notices.
She speaks in a low voice so Yolanda won't hear:
SISTER ABIGAIL Nervous?
KATE Yeah.
KATE And happy.
KATE And excited.
KATE : And proud.
KATE And scared shitless.
KATE It' s funny.
KATE All the same feelings I had when I was pregnant with our others.
That's what really worries you, isn't it?
Something bad happened, the last time you felt this way.
Yolanda's doing something similar.
She's afraid of :getting hurt again,.
.too.
Bit I have a-good feeling'about you two.
You can help.
each other heal.
And you're lucky.
You have a wonderful husband who can be there for you both.
A flicker crosses Rate's eyes at the mention of het "wonderful husband."
Doubt?
uncertainty?
Abigail.do'esn't see it.
I h T. HOME FOR GIRLS - CORRIDOR - DAY 'John emerges frcaitthe HEN'S ROOM.
The walls of the hallway are lined -with Children's-artwork.
He glances at it as he walks by.
Suddenly, he stops short.
Amidst the crude watercolors and _macaroni mosaics are several beautiful ain s, s'% surprisingly sophisticated, more Like the works of Henri 'R usseahan the o crayon-and-stick-figure scribbles surrounding them.
Then he hears something: a LITTLE GIRL'S VOICE, softly HUN= G a tune.
We know the words.
When I was juuust a lii.ittle yiiir., I asked my mother, what will I be?...
.John follows the HUMMING to a stark, white room.
Light slants in from a big-window, shining on A LITTLE GIRL in a lacy white dress.
Her.
back is to us, so.we can't see her face, just curls of platinum blonde hair spilling to her shoulders.
She sits at an easel, all alone, painting another extraordinary picture.
John watches, curious.
Suddenly; she senses his presence.
She- stops humming, the paintbrush freezes mid-stroke.
She turns.
She looks about eight years old, with pale skin and-bright, doe- like eyes, her delicate features framed by Shirley Temple curls.
It's the face- of a porcelain angel, a perfect little laving doll, friendly and inviting.
She wears a thick black velvet ribbon around her neck and one around each wrist.
Her'name is ESTHER.
JOHN Hi there.
ESTHER Hello.
ESTHER - She speaks with a strange accent.
ESTHER Sounds Eastern European.
JOHN Are these , paintings all yours?
Yes.
Do you like them?
JOHN Very much.
JOHN They're remarkable.
h T ank :you.
My name is Esther.
What's yours?
JOHN John.
JOHN It's nice to meet you.
JOHN She smiles and demurely offers her hand, giggling as he takes it.
JOHN She blushes, then turns back to her painting.
JOHN It's a half- finished jungle scene with a SMILING LION crouched beneath a tree.
JOHN So what's this one going to bo?
ESTHER My paintings are stories that come from my imagination.
ESTHER -This one'-s about a'sad mother lion who can't find her cube.
JOHN She's smiling.
ESTHER She's dreaming about her babies.
ESTHER It's the only thing that makes her happy.
JOHN Well, I hope she finds them.
ESTHER She will.
ESTHER I,bok.
ESTHER As she speaks, Esther dabs her brush and paints little lion cubs
curled up in front of their sleeping mother:
ESTHER They were lost'in the jungle 'and they were so scared because they didn't'have a mother or father.
ESTHER But just when they thought they'd be alone forever, they found their mother sleeping under this tree.
ESTHER And they felt so safe that they fell asleep too.
ESTHER Now when-the mother lion wakes up, her dream will have come true.
ESTHER She has her family again.
JOHN Where did you learn how to do this?
ESTHER Y've just had lots of time to practice, I guess.
ESTHER It's so boring here.
JOAN You don't play outside with the other girls?
JOAN Sounds like they're having fun.
ESTHER I like staying inside.
ESTHER That way I don't get my clothes dirty.
JOHN (amused) - Well, that's very responsible of you, but I'll- bet the sisters could find something else for you.
JOHN to wear.
ESTEER You.don't like my dress?
ESTEER - Don't you think it's pretty?
JOHN Your dress is.
JOHN very pretty.
JOHN I'm ,just saying.
JOHN you could -probably go outside if you really wanted to.
I don't like laying with the other .girls.
I'm different from everyone.
JOHN There's nothing wrong with different.
ESTHER Yes, there is.
ESTHER Everybody says there's not, but it isn't true.
ESTHER I don't care.
ESTHER If I'm sad or lonely, I just come in here a nd paint a story with a happy endingg And when people say they like.
ESTHER my paintings, it makes me feel better.
ESTHER I think.peo le should always try to take the bad things that happen to them and turn them into something good.
ESTHER Don't you?
John is taken aback.
Who j t1m1s )dc?
Before he can respond:
There you are.
Rate and Sister Abigail stand in the doorway.
John waves for Kate to enter and Esther sits up eagerly when she does.
Abigail's expression darkens when she sees who John has been talking to.
JOHN Hey, I'd like you to meet someone.
JOHN - (to Esther).
JOHN Esther, this is my wife, Kate.
JOHN Kate smiles and offers her hand, but instead of shaking it, Esther lovingly presses it to her cheek.
Motta...
Kate'and John exchange a beumsed look'.
JOHN She painted these all by herself.
Wow, you're quite the little-artist.
Thank you.
You smell nice.
Kate laughs.
Sister Abigail shifts uncomfortably.
ESTHER Would you like me to paint you a picture?
ESTHER You can watch me if-you want.
ESTHER I'm normally a little shy, but --
Esther, I'm sorry, they don't have time for you to paint them a picture.
They have to come with me now.
Yolanda's going home with them tomorrow.
isn't that wonderful?
Esther wilts.
She releases Rate's hand and musters a weak smile.
ESTHER Yes.
ESTHER I'm sure she'll be very happy.
KATE It was nice meeting you.
ESTHER - The pleasure was mine.
JOHN You've got a real talent on your hands here.
SISTER ABIGAIL Yes, we're very lucky to have her.
SISTER ABIGAIL But there's something -strange-in Abigail's voice -- she definitely doesn't un -lucky.
SISTER ABIGAIL Esther watches them go.
Sister Abigail walks Kate and John to the front door.
SISTER ABIGAIL The notary will be here at.ten for-you- to sign the placement agreement.
KATE Thank you so much for all your help.
KATE Kate gives her a warm hug.
KATE But mid-embrace, she notices something: Esther is at the end of the hallway, peering at them from around a corner.
KATE Abigail and John see--her,' too.
KATE What did she say to me.back there?
KATE It sounded like...
KATE "motta?"
SISTER ABIGAIL It's Russian.
SISTER ABIGAIL It means "mother."
SISTER ABIGAIL INT.JoHN'S CAR - NIGHT John whistles "Whatever Will Be, Will Be" to himself as he drives.
Kate gives him an amused look, then Jokingly sings along:
KATE - When you were juuust a liuittle
JOHN Sorry, I've got that stuck in my head now.
KATE She.
KATE made quite an impression on.you.
JOHN I wish you co'uld've heard the things.
JOHN she was saying before you c&me in.
JOHN I Jatow adults who aren't that mature.
I wonder' why they didn't show us her case file.
KATE She probably wasn't there when we were first ,looking.
JOHN It just blows may mind, a kid could go through as much-as she must have and still turn out like that.
KATE You sound like you're sorry we're not adopting her instead of Yolanda.
JOHN No, of course not.
JOHN I just hope she.
JOHN gets the right break.
JOHN I wouldn't trade our littl'e' girl for the world.
JOHN You )maw that.
JOHN Rate gives him an adoring look and squeezes his hand.
The sun is just rising,.warming the sky with an idyllic light.
The GIRLS (5-7) are busily getting dressed and making their beds.
The HOUSEMOTHER inspects each of-them in turn.
One bed remains unmade, its occupant missing.
The Housemother turns to the room, ready to give a scolding, but can't find who she's looking for:
HOUSEMOTHER Where's Yolanda?
The OLDER GIRLS (8-12) are-brushing their teeth and washing up.
The Housemother enters and looks around.
HOUSEMOTHER Have any of you seen-Yolanda?
HOUSEMOTHER Nobody has.
Sister Abigail leads the NUNS and LAY ASSISTANTS in a search of the home, looking for Yolanda.
The playroom, art room, chapel, classrooms, laundry room, rest rooms.-- they're all empty.
A young-nun, SISTER JUDITH, walks downstairs into -a dark storage- area.
Lots of hiding places.
SISTER JUDITH Yolanda?
SISTER JUDITH Are you hiding-down here?
SISTER JUDITH Then she notices a closet behind her.
SISTER JUDITH The door.
SISTER JUDITH is ajar.
SISTER JUDITH She reaches out, opens it...
SISTER JUDITH and nearly gags at what she sees inside.
A child's bare feet dangle in mi , , a .,im3.
The "Travel Turtle" is on the floor beneath them.
- A chair lies on its side nearby.
Kate dries her' hair in the bathroom.
The PHONE RINGS O.S. She pauses, suddenly concerned for some reason.
She opens the door.
As John reaches for-the phone, CAMERA MOVES IN on Kate.
She watches from the doorway, her face already registering dread.
She knows.
Even before he answers the phone, somehow she knows.
Bello?
The sky has turned gray.
Kate stares out at the hotel parking- lot, smoking a cigarette.
- Her eyes are red;- but she's long since cried-herself out.
John stands by the open-sliding glass door.
JOHN .The birth family is claiming her body.
JOHN They're planning a private service.
He looks to Kate for a reaction, but she has none.
He continues:
JOHN Sister Abigail thinks she might have been playing something called "The Choking Game."
JOHN It's a kind of schoolyard dare.
JOHN You try to get a rush by having someone choke you until you almost pass out.
JOHN There have been cases where kids have tried it alone and accidentally hanged themselves.
JOHN A beat.
JOHN Kate's voice is distant, as;
KATE So that's it?
KATE She just vanishes from our lives?
JOHN We can have our awn-service.
JOHN I think .it's important that we -
KATE I've been' in grief counseling for almost a year-and-a-half..
KATE If you say the word "closure,."
KATE I'm going to-claw your eyes out.
KATE She's not angry, just matter-of-fact.
KATE Be wants to say something, but holds his tongue.
KATE Silence hangs heavy between them.
KATE Maybe we're not supposed.to do this.
No.
Don't say that.
we -try to .have a baby and I have a 'third-trimester miscarriage that leaves.
me sterile.
'We try to adopt and she dies the night before we bring her home.
That doesn't sound like' somebody's trying to tell us.
something?
Yolanda didn' t the to.teach us a lesson..
We didn't make this-happen.
KATE ' It doesn't make.anndifference.
KATE ' I can't go through this again.
JOHN so let's not.
JOHN Let's adopt.Bather.
JOHN This brings Kate back to reality.
JOHN She eyes him coolly.
KATE Her body's barely cold and you're already thinking about replacing her?
We can't replace Yolanda any more than We can replace Jessie.
But we can't help her anymore, either.
Esther is alive and needs a family.
Right now.
KATE We have to at least wait until.--
JOHN -Until what?
JOHN I don't want to waste .a nother year of our lives wishing for something that we.can't-have.
JOHN (beat).
JOHN I want us to feel like a family again.
Kate regards him for a beat, conflicted.
Then:
KATE Let's see what Sister Abigail thinks.
Sister Abigail hands Rate and John a folder with a Polaroid of Esther stapled to it.
Her- case file.
SISTER ABIGAIL For the most -part, she's an'ideal child.
SISTER ABIGAIL She's originally from Russia, but her English is flawless, Smart as a.tvhip and very mature A?for her age.
SISTER ABIGAIL I don't think I've-ever had to tell her .anything-twice and I've never had to clean-up after her..
SISTER ABIGAIL She's a bit of a- nQat-freak.
JOHN I think we can handle that.
She's also fiercely independent., Whatever the other-children want to do, she wants to.dc the opposite.
JOHN She told me they make fun of her.
SISTER ABIGAIL I'm sure they do, but she doesn't make- things any easier on herself.
SISTER ABIGAIL She just doesn't seem interested in friends..
SISTER ABIGAIL She doesn't even play like a normal child.
SISTER ABIGAIL She just reads and paints.
SISTER ABIGAIL Most of the time she barely-speaks.
KATE Why do'you think that is?
Well, like most of the girls here, there's been no shortage of hardship in her life.- She's been orphaned twice-- her birthmother died of AIDS, then the American family who adopted her was- killed in.a house fire.
And I strongly suspect that she's been sexually abused as well.
KATE By who?
SISTER ABIGAIL I don't know.
SISTER ABIGAIL There's nothing in her -history, but that doesn't necessarily mean anything.
SISTER ABIGAIL Russian adoption - records.
SISTER ABIGAIL are notoriously unreliable.
JOHN Then what are you basing this on?
JOHN Sister Abigail hesitates.
JOHN Deciding how much to say.
SISTER ABIGAIL I wish I knew.
SISTER ABIGAIL There's just something missing with her.
SISTER ABIGAIL A-spark you see in a child's eyes that isn't there.
SISTER ABIGAIL I've only seen that-before in cases where the child had been severely traumatized.
SISTER ABIGAIL It might also explain - some of her idiosyncratic behaviors.
JOHN Like what?
SISTER ABIGAIL She refuses to shower or change clothes with the other girls.' She won't even allow the housemother in-the bathroom with her.
SISTER ABIGAIL She.'.s also very concerned with her physical appearance for her age.
SISTER ABIGAIL She's like a teenager getting ready for a date every morning.
SISTER ABIGAIL She insists on wearing dresses-every day.
SISTER ABIGAIL The ribbons around her wrists and neck stay on day and night.
SISTER ABIGAIL The only trouble we ever had with her was when we tried to take them off.
SISTER ABIGAIL She kicked two of Sister Francis' teeth-out.
SISTER ABIGAIL Kate and Tohn are taken.
SISTER ABIGAIL aback.
SISTER ABIGAIL Abigail sighs.
SISTER ABIGAIL I'm sorry.
SISTER ABIGAIL I'm 'not trying to discourage you.
SISTER ABIGAIL If you're serious, I'll do everything I can to-expedite the process, given the circumstances.
My one reservation is..this.
When-an adoption fails, it's usually because the parents didn't know what to expect.
-And'in this case, I can't' tell you what to expect because the plain fact of the- matter is that-I don't knaw.
Esther is happily-helping a NUN clean the sanctuary.
Kate and John sit in a pew near the back of the empty chapel.
KATE She really did open up with us, didn't she?
JOHN She latched.
JOHN right onto you.
JOHN We're probably the best chance she has at a.
JOHN normal life.
JOHN Esther looks up from her work and waves at them.
JOHN They wave back.
KATE A normal life..' That sounds really good,',doesn't it?
KATE - She smiles.
KATE and takes John- .'s hand.
CAXERA FOLLOWS Esther's feet, saddle shoes CLICKING on -the walk.
Kate walks beside her, holding her hand.
In Esther's free hand, she clutches a DOG-EARED BIBLE held together with a rubber band.
Activity on the playground stops as the girls watch Esther leave.
None of them look sorry to see her go.
She ignores them.
John puts.Esther's things ---- a small suitcase and her-paintings in the trunk of the car..
Sister-Abigail sees them off.-
SISTER ABIGAIL If you ever need anything, please don't hesitate to call.
SISTER ABIGAIL Before Kate.
SISTER ABIGAIL can respond, Esther tugs on her arm.
Come on!
Let's-go) Kate laughingly lets Esther drag her away.
RATE We wills Sister Abigail happily watches them go..
RATE Rate and Esther smile and wave goodbye.' She'waves back...
RATE but once the car pulls out, her smile fades.
RATE She seems'vaguely troubled as they drive away...
Headed for home.
Kate is showing Esther some SIGN LANGUAGE.
Esther makes the sign for each letter as she says it aloud:
KATE Put your thumb here.
KATE She makes the sign for 'T."
KATE Esther.
KATE sees her mistake, corrects it.
ESTHER T-H-E-R.' E-S-T-H-E-R.
ESTHER Esther.
RATE Perfect l
Esther smiles and practices=it a few times.- Outside, the LEAVES have turned color.
Esther gazes out in-wonder.
ESTHER It's so beautiful, motta.
KATE Sweetie, here we say "Mont" or.
KATE "mommy."
ESTHER Kate and John exchange-a warm look.
EXT. PRIVATE ROAD - DAY John's car turns at a GATE and drives down the road leading-to their private community.
EXT. PRIVATE ROAD - DAY The secluded road winds through the forest and crosses the little BROOK we saw earlier.
The Coleman's neighborhood 3.s surrounded by forest,-an upscale community of big houses and manicured lawns.
A POSTMAN delivers the mail.
A HISPANIC NANNY pushes a BABY in a stroller.
GARDENERS tend someone's flowers.
Esther -soaks it all in.
EXT. COLEMAN RESIDENCE - DAY They pull into the driveway and get out.
EXT. COLEMAN RESIDENCE - DAY Esther's mouth practically hangs open at the sight of their beautiful house.
EXT. COLEMAN RESIDENCE - DAY The front door opens and Max runs out to meet them.
EXT. COLEMAN RESIDENCE - DAY Daniel appears in the doorway-with DORIS COLEMAN (arid-60's), their grandmother.
EXT. COLEMAN RESIDENCE - DAY Daniel stands aghast at the sight of the strange, pale girl with the Goldilocks curls and frilly white dress.
-Holy shit:..
Max.
runs straight into Kate's arms and gets a big hug.
KATE Oh, we missed you so muchll Kate gives Max a kiss, then turns to Esther: Max hangs back, a little shy.
KATE Esther signs' to Max without speaking: -
Max gives Kate an excited smile.
KATE She's been practicing the whole way.
Kate takes the girls' hands and they all walk up'to the house.
Esther notices Man's hearing aid.
What's that?
KATE . That's a hearing aid.
KATE . It helps her hear.a little so she can read lips.
KATE . John gives Doris a Use on the cheek.
JOHN Hi, Mont.
JOHN Thanks for watching them.
JOHN Esther, this is Grandma Doris.
ESTSER A pleasure to meet you.
ESTSER Esther surprises everyone by giving her a perfect ltttle rtse Daniel fails to suppress a laugh.
ESTSER Kate silences him with a look.
DORIS How precious!
DORIS It's a pleasure-to meet you, too.
And this is our son, Daniel.
Esther smiles and puts out her hand.
Daniel grudgingly takes it.
ESTHER Hello, Daniel.
DANIEL Hey.
Esther walks from room to room, in awe of her luxurious new home.
Kate and the rest of the family follow her.
ESTHER Everything's so bigi As Esther moves on to the next room, Daniel hangs back and
whispers to John, too loud:
DANIEL Why is she dressed like that?
JOHN Don't be rude.
Esther overhears them, but pretends she didn't.
Kate sees this- and tries to distract her.
KATE Would you like to see-your room?
KATE Esther smiles and nods eagerly.
KATE But on the way up the stairs, she eyes Daniel furtively, sizing him up...
INT. ESTHER'S BEDROOM - DAY Kate pushes the door open and Esther enters.
INT. ESTHER'S BEDROOM - DAY We recognize the room by the arched windows -- this used to be the-nursery.- It's been completely made over as a little girl's room, complete with a lacy white canopy bed covered with a mountain of STUFFED ANIMALS..
INT. ESTHER'S BEDROOM - DAY Esther turns to Kate and John with a toothpaste-commercial smile.
ESTHER It's perfect.
INT. ESTHER'S BEDROOM - NIGHT Esther is in bed, wearing a nightgown.
INT. ESTHER'S BEDROOM - NIGHT Kate and John tuck her in.
ESTHER I love.you, motta -- I mean, Monmiy.
KATE I love you, too, sweetie.
KATE She kisses Esther on the forehead.
KATE John leans in for a kiss and Esther,hugs -him tight.
KATE Then he and Kate turn out the light and close the door.
KATE Esther watches them go...-
INT. UPSTAIRS HALLWAY - NIGHT Kate and John walk to their room, arms lovingly around each other.
They close their door, leaving the hallway empty and dark.
Then: CAMERA SLOWLY MOVES back down the hall toward.the closed door of Esther's_room, PUSHING IN'on the doorknob, lingering there fora long beat...
Then we hear the lock CLICK shut.
JOGGERS.
PAPERBOY.
Lawn sprinklers.
KIDS running and -riding bicycles.
Saturday in the suburbs.
Esther and Max eat breakfast at the table while rate pours their juice.
Daniel tears through wearing a soccer iuniform.
KATE Good luck II I love you II
DANIEL Love you, tools John follows Daniel, kissing Kate on his way out.'
KATE Remember, it's only a game.
I'm a fan.
Fans yell.
_.I'll call to let you know who won.
INT. ESTHER'S BEDROOM - DAY Kate and Esther are decorating.
INT. ESTHER'S BEDROOM - DAY Esther pins up some of her paintings.
INT. ESTHER'S BEDROOM - DAY Kate spreads out a selection of wallpaper borders.
KATE Okay, which one do you like?
ESTHER These are for a'younger child.
ESTHER Did you pick them out for Yolanda?
ESTHER Kate is taken aback.
ESTHER She stammers for a beat.
KATE I'm sorry.
KATE I'll take them back and pick some just for you.
ESTHER It's all right.
ESTHER I rather like this one.
ESTHER Esther points out her.favorite and goes back to pinning up her paintings.
ESTHER Kate sighs.
ESTHER As she rolls up the samples, she notices the same Gothic mansion in several of Esther's older paintings.
KATE '1s that a real place?
ESTHER No.
ESTHER I just made it up.
ESTHER It's a haunted castle where a beautiful- princess was locked away.
ESTHER She waited so long and was so sad that she filled the moat with her tears, but then a handsome prince swam ,across it and rescued her.
I like happy ending's.
Don't you?
Sliding doors open.
Rate and the girls enter.
Esther looks around, dazzled by three stories of glass-ceilinged extravagance.
It's totally alien to her.
Kate and the girls look through racks'.
of children's clothes.
Kate pulls a pair'of jeans with.
flowers embroidered on the pockets.
KATE These are cute.
ESTHER -Jeans are ugly.
KATE But sweetie, you have to have something you can play outside in.
ESTHER That doesn't mean I have to look like a boy.
Kate leads the girls through the mall, carrying BAGS of purchases.
Something catches Esther's eye.
She hangs back, distracted.
It's a pet store.
' In the display is an aguarium filled with TROPICAL.
FISH, their vibrant colors illuminated by a black light in the tank.
Esther gazes in, nose practically against the glass.
RATE You like fish?
ESTHER I like all beautiful things.
ESTHER Kate taps Max's shoulder and signs to her.
KATE You should show her Hodgepodge when we get home.
KATE Max nods eagerly.
KATE Esther givee.them a curious look.
ESTHER Hodgepodge?
ESTHER What's that?
HODGEPODGE is a hamster.
Esther kneels in front of his cage for a closer look.
Kate stands behind her.
Max beams proudly.
KATE Max.
KATE takes care of him all bir herself.
KATE It's her big girl responsibility.
ESTHER Aaaww,-can I pet him?
KATE Sure.
KATE But you have to promise not to- let him out of his.
KATE cage .unless- Hcumey or Daddy is,here to hold him.
ESTEER Why?
KATE Because he's very delicate and you could hurt him.
KATE Okay?
KATE Esther xiods.
KATE Kate scoops.flodgepodge up and kneels between the girls.
KATE Esther and Max share a smile as they stroke his-fur.
A banner reading."
WELCOME HOME, ESTHERII'" has been hung.
John sprays LIGHTER rLUID on a charcoal grill and starts the fire.
Daniel watches attentively at his father's side.
Kate and Doris prepare hamburgers and hot dogs for the barbecue.
They can see Esther and Max laughing and playing horseshoes in the backyard, wearing NEW MATCHING SUNDRESSES..
Adorable;
They grow up fast, don't they?
KATE Too fast.
DORIS So what are your plans now?
KATE Well, we'll get Esther settled, then I'll probably go back, to work.
DORIS Oh, so you think.they'll take you back?
DORIS Kate's eyes flicker with irritation.
KATE I'm not talking about Yale.
KATE I'm going to teach piano lessons from home.
DORIS I see.
DORIS That was such a good position you had at Yale.
DORIS It's a.
DORIS shame.
KATE I didn't quit because I wanted to.
KATE I quit because.I couldn't work anymore.
DORIS I know.
DORIS I'm 5o glad you're doing better now.
Bow's Maxine feeling?
KATE She's fine.
KATE Kate's pointedly not making eye contact with Doris now.
DORIS Well, it's a shame that it took something like that for you to :get help, but I'm glad you did.
DORIS Kate takes.
DORIS the plate of food and leaves without looking at her.
Dinner's over.
Daniel has changed into swim trunks and SPLASHES around in the pool.
Everyone else is gathered around Esther, who's opening a few small presents.
She unwraps a BOOK OF SIGN LANGUAGE and gasps excitedly.
This is perfect!
Thank you!
Eiow do I say "thank you?" Kate shows her.
Esther turns and makes the sign to Max.
Behind them, Daniel climbs out of the pool and runs out to the end of the diving board, poised to jump back in.-
DANIEL, Dad!
DANIEL, Watch this!
DANIEL, But John is focused on Esther.- She's opening a big present la1aled "FROMi DADDY."
DANIEL, Daniel can't get his attention.
DANIEL Dad!
DANIEL 'Dad!!
DANIEL Dad, look!!
DANIEL John distractedly glances over his shoulder at him and Daniel does a huge cannonball into the pool.
DANIEL SPLASH!
DANIEL Suddenly, Esther squeals with glee.
DANIEL She's unwrapped an IIRT EASEL and NEW PAINTING SUPPLIES.
DANIEL By the time Daniel-'s smiling face pops out of the water, he's disappointed to find that Esther has drawn John's attention again, barraging him with-hugs and kisses.
DANIEL She looks at Daniel over John's shoulder and hticks her tongue out at him.
DANIEL Daniel fumes.
INT. ESTHER'S BEDROOM -- NIGHT John walks behind Esther, his-hands over her eyes.
INT. ESTHER'S BEDROOM -- NIGHT Kate leads her into the darkened roam by the hand.
KATE Are you ready?
KATE Esther nods excitedly.
KATE John uncovers her eyes.
KATE Esther stops short in awe.
KATE It's the FISH TAN C from the shopping, mall.
KATE Esther kneels before it, entranced.
KATE She turns the black light on and off, marveling at- how it makes her dzess glow and the colors in her paintings light- -up.
KATE She gives Kate and John a.
KATE big smile.
INT. KATE AND JOHN'S BEDROOM - DAY Rate and John get dressed for church.
INT. KATE AND JOHN'S BEDROOM - DAY John pulls on a tie.
INT. KATE AND JOHN'S BEDROOM - DAY Kate searches through a jewelry box.
INT. KATE AND JOHN'S BEDROOM - DAY She's missing something.
KATE nave-you seen my pearls?
Sunday morning in America.
Kate and John sit with Doris and the kids.
-A.PRIEST reads-from the scripture and a SIGN LANGUAGE II?TERPRETBR translates.
Esther follows along in her own Bible and Kate notices aphoto poking from between its pages.
All she can see is the face of a RUGGED-LOOKING MAN in his 40's.
She eyes it curiously...
Kate is cleaning, picking Max's clothes up from off the.floor.
She sees something that gives her pause -- one of Max's STUFFED ANIMALS has a STRING OF PEARLS hung around its neck.
INT. FAMILY ROOM - DAY Esther and Max are playing a board game.
INT. FAMILY ROOM - DAY Kate enters with the pearls and shows them to Max.
KATE Did you take this out of my jewelry box?
KATE Max shakes her head, confused.
KATE Then-how did it get in your room?
KATE Somebody put this around T.J.'s neck.
KATE Who was it if it wasn't.you?
KATE Max shrugs.
KATE She looks-nervous.
KATE Kate sighs.
RATE Go take a time-out and think about it.
ESTHER But we're playing]
KATE She can finish your game later.
KATE Come on.
KATE Max pouts and follows Kate upstairs.
KATE Esther watches them go.
Esther stands in front of a class full of KIDS.
Their teacher, MRS.
GROSSE, is introducing her.
Esther's wearing a pretty little dress'and Shirley Temple curls, but her usually unflappable smile seems wary, uncertain in the face of these staring third graders.
This is our new student.
Her name is Esther Coleman and I want you all to make her feel very welcome today.
One of the kids, BRENDA, whispers.
a wisecrack to a FRIEND.
Esther shifts uncomfortably.
Esther sits at the end of the table where Brenda and her FRIENDS are eating..
They eye her derisively.
Esther ignores them- and prays over her lunch.
The other girls exchange amused looks.
Brenda folds her hands and makes an earnest, mocking face:
BRENDA Dear Jesus, please help me to not dress like such a freak tomorrow.
BRENDA The girls laugh.
BRENDA Esther pays no attention.
INT./EXT. TREEHOUSE - DAY Daniel and his friends AUSTIN and TREVOR run down a short path through the woods behind.the Coleman's house to a tall tree.
INT./EXT. TREEHOUSE - DAY CAMERA REVEALS an enclosed treehouse about ten feet up -This is' no "Little Rascals" job -- this thing was professionally built.
INT./EXT. TREEHOUSE - DAY They climb up to it.
INT./EXT. TREEHOUSE - DAY Inside, Daniel throws back a rug and pries up a loose plank.
INT./EXT. TREEHOUSE - DAY Under it is a small STASH OF WEED.
INT./EXT. TREEHOUSE - DAY The other
boys open their 'video ina" ine s, c b o books, and an old a "PLAYBOY'.' wi? 1/2 h Cindy Crawford the c
TREVOR Cindy Crawford?
TREVOR This- magazine's older than we axe1 She's probably got Like wrinkly-old grandma boobs Howl
They laugh.
Daniel sparks up a joint.
Suddenly:
ESTHER Do you want to play?
ESTHER The boys quickly waving the wke away.
ESTHER Esther and Max are lo king up lat them
DANIEL Get out of here!
DANIEL This is my treehouse.
DANIEL Dad built it for mM.
DANIEL Esther smiles, then leads Max away.
DANIEL The boys watch them go.
Is your, like, whole family ietarded or something?.
- Trevor and Austin laugh.
Daniel flushes, angry and embarrassed.
INT. BATHROOM - NIGHT Kate finishes drawing a bath for Esther.
KATE I think we should try this with the door unlocked tonight.
KATE What do you say?
What if someone comes in and sees me?
KATE Nobody's'going to come in.
KATE I'll stand right outside the door.
ESTHER I could sing for you.
ESTHER At the home, I used to sing so the sisters would know I was all right.
ESTHER Please?
ESTHER Esther's eyes are desperate, pleading..
ESTHER Kate sighs.
Kate closes the door.
The lock CLICKS shut.
A moment later, Esther starts BUMMING.
Kate listens fbr a beat,-troubled..
Esther and Max are huddled in bed and Kate reads-them a story.
John watches from the doorway.
Kate sees him and smiles.
Kate's in bed, writing'in her journal by the light of d bedside lamp..
Outside, rain PATTERS-on the window and lightning FL1SHBS.
John kisses her good night.
She smiles and surprises him by pulling him close and kissing him more deeply.
He responds..
She places his hand on her breast and he starts to undress her.
Then:.
A KNOCK at the door.
John and Kate cringe at the interruption.
KATE Come in.
KATE The door opens.
KATE It's Esther and Max.
ESTHER We're scared of the lightning.
ESTHER Max giggles.
ESTHER Kate and John exchange a resigned look.'
JOHN Okay, come on.
JOHN But just for tonight.
JOHN Esther and Max excitedly clamber into the bed and snuggle between them.
JOHN Kate and John share amused looks.-
The kids are eating breakfast.
Esther reads her sign language book at the table.
Max signs to Daniel.
He turns to Kate with a frustrated sigh.
DANIEL Mom, what's she saying?
ESTHER She wants you to pass the milk.
ESTHER Kate gives Daniel an admonishing look.
RATE See?
RATE If you studied more, you wouldn't have to ask all-the time.
RATE Daniel glares fit Esther, but she doesn't see it.
RATE John enters, ready for work.
RATE He-grabs his travel mug, gives Kate a kiss.
JOHN See you later.
Esther puts dut her arms for a hug.
He leans in to kiss her, but she clings to him and won't-let go.
She pouts.
ESTEER I want you to take us to school.
ESTEER She looks up at him with big sad eye.a.
ESTEER He can't resist.
JOHN I guess I can be late today.
JOHN I can take them to school and you can pick them up.
ESTHER Yay!
ESTHER We're going with Daddy!
ESTHER - She jumps up from the breakfast table and runs off to get ready..
The kids are leaving for school with John.
Kate sees them off.
DANIEL Bye, Mom.
DANIEL Kate-gives him and Max a kiss, but Esther-runs right by without pausing, hurrying after John.
DANIEL Esther.
DANIEL takes- 'John 'a-hand, holding it on the way to the car.
DANIEL Kate watches them, a little hurt...
INT. LIVING ROOM - DAY Rate sits with Esther, watching her open a gift-wrapped box.
INT. LIVING ROOM - DAY Inside is a JOURNAL like the one we've seen Kate writing in.
KATE I have a journal just like this that I write in every day.
ESTHER - What kinds of things do you write about?
RATE what I did that day, how I feel.
RATE Anything I don't want to forget.
RATE I thought you and I could spend some time together today and start a life book.
ESTHER Whit's that?
RATE It's like an adoption storybook.
RATE And it's all about you.
RATE I did a couple pages to gat you started.
RATE Look.
She opens the journal.
Pasted to.the first page is a photo.from
A DADDY GET rMARRIeED ng Esthermarvelskat Kate'sgwedding dress.
ESTHER So beautiful,..
ESTHER , Kate turns the page to a picture of.Khte and John with Daniel as a BABY.
ESTHER Then Kate, John, and SIX=YEAR-OLD DANIEL with BABY MAX.
KATE This is Daniel when he was born, And there's Max; And there's you.
KATE She turns next to a photo of the-whole- family taken at Esther' s welcome home party.
KATE The caption reads, "ESTHER JOINS THE FAMILY."
RATE . If you want, we can put your other pictures in here, too.
ESTHER What other pictures?
KATE The ones I saw in.
KATE your Bible.
KATE Esther gives her a dismayed look.
KATE - I'm sorry.
KATE - They slipped out at church.
KATE - If they're private, we don't have.to ---
ESTHER It's okay.' I want you to -see them.
ESTHER She smiles, but it looks forced.
INT. ESTHER'S BEDROOM - DAY Kate and Esther sit on the floor.
INT. ESTHER'S BEDROOM - DAY Esther.
INT. ESTHER'S BEDROOM - DAY removes the rubber band from around her Bible and takes out a few battered photographs.
INT. ESTHER'S BEDROOM - DAY They're all of Esther with a rural family -- the man.Kate saw in the photo at church, his WIFE,.
INT. ESTHER'S BEDROOM - DAY and THREE BOYS, aged 6, 10, and 14.
INT. ESTHER'S BEDROOM - DAY In one, they're all posed together in front of a farmhouse.
ESTHER These are the Wallaces.
ESTHER That's James and Hannah.
ESTHER And that's Micah, Luke, and Isaiah.
KATE - This is the American family that adopted you from Russia?
Esther nods'.
They're candid -family snapshots full -of.
laughter and hugs.
Esther'.s adopted father is in all-of them.
The last one is of him and.
Esther, the same photo Kate.
saw part, of at church.
They lookvery'n.ice.
They must have loved you'very much.
Ksther nods, but Kate-sees that she's holding back tears.
RATE What's wrong?.
ESTHER I hid these because Ididn't want you to know how much I miss' them, I was afraid you'd think I didn't love you.
KATE It's okay, sweetie...
KATE I understand.
KATE You know, I lost someone who was very .special to me once, too.
KATE Esther wipes her eyes and looks up, interest piqued.
ESTHER Really?
INT. MUSIC ROOM - DAY Kate shows Esther the orchid in its ornate planter.
RATE We don't have any pictures of Jessica because she died while she was still in my tunny.
RATE But we spread her ashes in here and as long as.
RATE this flower grows, part of her will be alive inside it.
It's okay to be sad.about the people we've lost..
And it.'s okay to iniss them, too.
Esther nods.
They'smile at one another through their tears.
Between classes, crowded with KIDS.,.
Esther clutches her books to her chest.
Daniel and Trovor are walking the other way and as they pass, Daniel dumps Esther's books.
Trevor laughs.
Esther glares at'Daniel and kneels to pick up her books, bitt the kids walking by purposefully kick them, laughing faces leering down at her.
She gathers her books, but one of them is missing.
She looks around.
-Spots it.
Esther's Bible lies on the floor at Someone's feet.
A.hand reaches down.
and picks it up.
It's Brenda.
BRENDA Is this a Bibl?
ESTHER Give it back to me.
ESTHER She reaches for it, but Brenda laughs and raises-it over her head.
BRENDA Jesus-freak brought a Bible to school!
BRENDA Esther angrily swipes at it again, but one of Brenda's friends grabs it first.
BRENDA Esther takes a deep breath, trying to calm down.
May I pleas.
have my Bible?
The girl hesitates, shrugs and offers Sather the Bible...
but snatches it away again at the last second.
Brenda laughs.
8sther reaches for it, but the girls keep passing it between them.
Esther and Brenda grab it at the same time.
There's a brief tug- of-war, then the rubber band SNAPS and the Bible flies apart, pages and hp otos scattering everywhere.
Esther gasps in horror and dives to the floor, desperately scooping up the loose pages.
A"crowd gathers, watching and snickering, Daniel and Trevor among them.
Esther looks to Daniel for help, but he just stands there, watching uncomfortably.
Brenda laughs at Esther crawling around on all fours.
BRENDA Look at the cute little doggied Is this your collar, little doggie?
BRENDA Brenda reaches out and grabs the ribbon-around Rsthdrls neck...
BRENDA The-second Brenda touches the ribbon, Esther flies into panic.
BRENDA She screams an s Brenda'e hand away, aching h_ex e and k coking feet, ster 11 s 5 riekincr At the toy Dg her.lungs.
BRENDA Brenda leaps back, wide-eyed and freaked out.
BRENDA The kids fall into stunned silence.
BRENDA Esther's screams echo in the hallway.
BRENDA A TEACHER comes running.
BRENDA Trevor puts a hand over his mouth so the teacher won't see him laughing.
TREVOR Dude, your sister's a.total spazl
DANIEL She's not my sister.
The drive home from school.
is silent and tense.
Esther stares out the window.
'Kate eyes her in the rearview mirror, concerned.
EXT. COLEMAN RESIDENCE - DAY The minivan is'parked in the drive and the kids are climbing out.
EXT. COLEMAN RESIDENCE - DAY As Daniel and Max head to the house, Kate takes Esther-aside.
RATE Mrs. Grosse told me what happened today.
RATE Do you want to talk.
RATE about it?
RATE Daniel-hangs back to see if Esther is going, to tell on him.
RATE She "sees him standing there, then turns to Rate with a smile.
ESTHER There's nothing to talk about.
ESTHER We were -just playing a game, that's all.
ESTHER She walks away, passing Daniel without, a look.
ESTHER Kate is.
ESTHER dubious.
INT. MAX'S BEDROOM - DAY Max enters, throws down her "Hello Kitty" bookbag ---- and stops short.
INT. MAX'S BEDROOM - DAY Hodgenodte's-cag .is empty.
INT. MAX'S BEDROOM - DAY Max stands frozen for a beat, then starts looking for him.
INT. MAX'S BEDROOM - DAY Esther appears in the doorway.
ESTHER What's the matter?
ESTHER Max turns and tries to block the cage, but Esther sees that it's empty.
ESTHER Esther gasps.
ESTHER Where is he?
ESTHER Were you playing with him?
ESTHER Max frantically shakes her head.
ESTHER Esther quickly shuts the door.
ESTHER You left his cage open!
ESTHER Look!
ESTHER Sure enough, the door of the cage is wide open.
ESTHER Max shakes her head, frightened tears in her eyes.
ESTHER Then how did he get out?
ESTBER You have to think!
ESTBER Mommy's not going to believe your.
ESTBER She didn't.believe you about the necklace and she's not going to believe you about this!
ESTBER Max is devastated.
ESTBER She's sobbing now.
ESTBER Esther tries to calm her.
ESTHER It' a okay.
ESTHER Don't cry.
ESTHER Look 'at me.
ESTHER She takes Max by the shoulders.
ESTHER Max looks up, breath hitching.
ESTSER I'll tell Monmy-it was-my fault.
ESTSER You won't get in any trouble..
ESTSER I'll tell her I took him out of the cage without your permission and he ran away, okay?
ESTSER Max gives a grateful nod.
ESTSER Esther smiles and strokes Max's hair.
ESTHER - Don't worry.
ESTHER - It'll be our little secret.
ESTHER - :Max nods again and gives her a-hug.
ESTHER - She doesn't see the calculating look in Esther's eyes...
INT. SUNROOM - NIGHT A-glassed-in terrace off of Kate and John's bedroom filled with plants.
INT. SUNROOM - NIGHT Kate is wearing only a long T-shirt, watering the plants before bed.
INT. SUNROOM - NIGHT John enters in his pajama bottoms, snuggles into her from behind.
INT. SUNROOM - NIGHT Kate smiles and.leans into him.
INT. KATE AND JOHN'S BEDROOM - NIGHT The lights - are off.
INT. KATE AND JOHN'S BEDROOM - NIGHT Kate and John are in bed, making lave.
INT. KATE AND JOHN'S BEDROOM - NIGHT Slow, passionate, intense.
INT. KATE AND JOHN'S BEDROOM - NIGHT When they're finished,- breathless and trembling, she cradles his face in her hands gazing lovingly up
at.him.
Then something catches her eye in the moonlight: Ethel Jg.wat ,them fr m the -open b edr door, hgr hen frozen 9J1 tth dooxknob.
KATE Oh, my God!
KATE They hurriedly pull the sheets up and Kate turns on the bedside lamp.
KATE Esther stares at them blankly.
KATE . Esther, honey?
KATE . What is it?
KATE . Are you okay?
KATE . Esther just glowers at'her, then turns and walks away.
Esther.
Sits at her easel, painting.
Kate enters and sits down on' the bed.
Esther doesn't look:at her.
She's painting a sophisticated, stylized PORTRAIT OF KATE.
-Other PORTRAITS of the family -arealready pinned to the wall.
Kate shifts uncomfortably.
We need to talk -about last night.
Do we?
KATE Yes.
KATE There are certain things that.
KATE grown-ups do.
KATE that kids aren't supposed to see.
KATE And that was one of them.
KATE Esther keeps painting.
KATE She still hasn't looked at her.
KATE Esther, I need you to listen to me..
KATE Esther pauses.
KATE She deliberately sets her paintbrush down and turns to Kate.
KATE An awkward beat.
KATE See, when two grown-ups love each other very, very much, they like to.
KATE show that love to each other -- Iknow.- They fuck.
KATE Kate is dumbfounded.
KATE Esther regards her with a bored, aloof-look.
INT. JOHN'S DEN - DAY John is troubled by what Kate has told him.
JOHN - She could nave picked it up anywhere.
JOHN Bell, she probably heard it at school.
KATE This wasn't something she overheard.
KATE She knew what it meant.
KATE And the way she said'it.
KATE I don't even think she expected to get in trouble over it.
JOHN We'll talk to her about it tonight.
KATE You think that's enough?
JOHN' What do you suggest?
KATE ' I could take her to Doctor Browning.
JOHN It was one dirty word.
JOHN I don't think we need to call in the shrink just-yet.
KATE Maybe.
KATE It just reminded The of what Sister Abigail said..
KATE We really don't know that much about her.'- The last 'family she-was with could have been - like, "Pass the fucking potatoes" at the dinner table for all we know.
JOHN Iget it, I just- don ''t want to make a bigger deal out of it than it is.
KATE If she's saying "fuck" to my face, what's she doing when we're not around?
KATE We have to be thinking about what kind of influence she's having-on Daniel and Max.
KATE Particularly Max.
JOHN I wouldn't worry about it.
JOHN You're right, we don't know how she was raised, but we do know she's a good kid.
JOHN if Danny and Max want to start acting.like her, that's fine with me.
EXT. COLEMAN RESIDENCE - DAY Esther and Max pick wildflowers along the edge of the forest.
ESTHER Let's pick flowers for Daddy.
ESTHER Max.nods happily.
ESTHER 'Then Esther notices something that makes her stop short.
ESTHER A girl approaching on a bicycle...
ESTHER It's Brenda.
ESTHER She pretends to not see Bather, just rides right by.
ESTHER Esther watches, her face strangely slack...
ESTHER then starts to follow .her.
ESTHER Max gives Esther a confused look, but tags along.
Esther finds Brenda's bike parked at a neighborhood playground ---- swings carousel, jun7le gym, and a-tall corkscrew slide made-tor look like a rocket ship.
There are KIDS playing.
MOMS watching.
A BONELESS GUY with a shopping cart full of stuffed garbage bags asleep by a tree.
WOMEN.
doing pilates.
Esther ignores them all.
Brenda is climbing on the jungle gym with some other kids.
Esther walks over with Max in tow and just watches Brenda play.
Brenda sees her and makes a face.
Esther just stands there.
Staring.
What are you looking at?
No response.
Max tug on Esther's arm, but she's rooted in place, staring blankly at Brenda.
Finally, Brenda can't take it.
She climbs off the jungle gym and walks away.
Esther watches 'her go..
Brenda gets on a swing, but just as she starts to get some height, Ester' right there,.star n ,_p a her again.
Max happily grabs a swing for herself, but Esther is fixated on Brenda.
BRENDA Stop staring at.mel Stop ital.
BRENDA But Esther is unwavering.
BRENDA Can't take her eyes off of her.
BRENDA Brenda gets off the swing and runs away.
BRENDA Esther calmly walks after her.
BRENDA Go-away!
BRENDA Stop following me, freak!
BRENDA Max sees Esther following Brenda and grudgingly gets off the swing, hurrying to -catch up.
BRENDA Brenda gives them an angry look.
Why don't you two,go home and change each other's diapers?
Esther and Max follow Brenda across the park,, Max still uncertain about what's going on..
Brenda heads for.
the tall corkscrew slide.
Steep stairs lead to the enclosed top, the tip of the rocket ship.
Brenda starts up the stairs, then pauses.
She turns to Esther.
BRENDA You go first.
BRENDA Esther doesn't move, but Max gladly takes her turn.
BRENDA After a beat, Esther follows Max up the stairs.
BRENDA Brenda stays behind, watching.
BRENDA Max goes down the spiraling slide, but Esther just stands at the top, looking down at Brenda.
BRENDA Gol!
BRENDA Esther, continues to stare down at her for a beat, then turns and -disappears from eight.
BRENDA only.
BRENDA then does Brenda climb up.
BRENDA Max runs to the stairs for- another turn.
BRENDA Brenda reaches the top and looks around.
BRENDA She sees Max.' But where's Esther?
BRENDA She turns.
Suddenly, Es er is right in ,AIL of her.
She didn't' go down the slide, she was just crouched out of sight.
Brenda gasps -- -- then Este spits Jn her face acrd ush hex dawn the airs.
Brenda SCREAMS as she falls,-limbs flailing, out-of-control.
She lands hard in the dirt and just lies there crying, clutching her arm and bleeding from a gash in her forehead.
Brenda's scream draws alarmed looks.
The Homeless Guy startles awake.
one of the playground mothers comes running to help.
But Max stands frozen, gaping at Esther in total shock.
Esther stares blankly down.at Brenda from atop the slide.
Utterly emotionless.
BRENDA'S FATHER arrives on the scene.
Brenda says something.
to -him and points at Esther and Max, who watch from a distance.
ESTHER Are you going to tell on me?
ESTHER Max shrugs.
ESTHER I didn't mean to hurt her.
ESTHER I just wanted her-to stop picking on me.
ESTHER Don't you hate it when someone is mean to you for no reason?
ESTHER Wouldn't you do almost anything to make them stop?
ESTHER A best.
ESTHER Max nods.
ESTHER Esther offers her hand and Max takes it.
INT. DINING ROOM - NIGHT Esther and Max sit at the table.
INT. DINING ROOM - NIGHT Kate and John eye them sternly.
JOHN Brenda says you pushed her.
ESTHER That's not true!
ESTHER We were just playing and she tripped!
ESTHER I swear!
KATE Did you see what happened?
Esther eyes Max expectantly.
Max hesitates.
Then:
Kate sighs, not entirely convinced...
Kate carefully tends the memorial orchid, spraying it with a fine mist of water.--
Kate's watering the plants when she feels something on'her hand.
There's an ANT on it.
She flicks it off.
Then she seed ANOTHER, this one crawling up her arm.
She makes a face and looks down.
Thg g are ante arwl ng loon a-: arou her feet.
She quickly steps back,- brushing at her- arms and legs.
She looks under one of the plant tables to'see what's attracted them: It's Hodgepodge.
He's been dead for several days, his body swarming with ants and MAGGOTS.
EXT.-COLEMAN RESIDENCE i? 1/2  GARDEN - NIGHT
A hole has been dug in the backyard flower garden.
Kate, John, Esther, and Max stand around it.
Max places a shoebox with "HODGEPODGE" written on it in the hole and lays a flower on top of it.
John starts shoveling dirt into the bole.
Esther and Max exchange a knowing look...
INT. MAX'S BEDROOM - DAY Esther and Max are giggling and playing dress-up.
INT. MAX'S BEDROOM - DAY Clothes are strewn everywhere.
INT. MAX'S BEDROOM - DAY They're both trying to look grown-up.
INT. MAX'S BEDROOM - DAY They're even wearing makeup -- heavy mascara and pink, painted cheeks.
INT. MAX'S BEDROOM - DAY Daniel walks by and sees Max putting on lipstick.
INT. MAX'S BEDROOM - DAY He takes it away from her.
DANIEL Hey, you're not allowed to wear makeup.
DANIEL Does mom know you have this?
ESTHER Give it-back.
DANIEL, Make me.
ESTHER Give it back'or I'll tell Daddy, that you hit her and then you'll be in trouble.
ESTHER Max smiles.
ESTHER Daniel-scowls at Esther, then gives Max the lipstick.
ESTHER He leaves.
ESTHER Max gives Esther a hug.
ESTHER Best friends forever.
f l iT.
SUPERMARKET - DAY Kate waits in line -at the check-out.
Esther and-Max are with her.
Aw .Kate pushes her cart up to the-counter, she looks over and sees the nearby'"WINE & SPIRITS" aisle.
No big.
deal, just a passing glance, a flash of idle distraction.
Her eyes unreadable.
Then:
ESTHER What kind of sex do men crave most?
ESTHER Kate-looks back, shocked.
ESTHER Esther has picked up a "COSMOPOLITAN" from the newsstand and is'reading the cover aloud-to Max.
KATE Put that away.
KATE Don't look at those.
KATE Kate puts the magazine back.
KATE There are several others just like it at kids-eye level.
KATE "Orgasms UNLIMITED!" "Thrill EVERY INCH- Of Him J" Kate'sighs and-'starts putting groceries on the conveyer.-
ESTHER "How To Hit Your G-spot Every Time."
ESTHER Kate whirls.
ESTHER Esther has picked up the same magazine.
ESTHER Kate angrily snatches it and pulls Esther toward her.
ESTHER Max startles.
KATE Stand where I can see yowl
The CASHIER and a couple CUSTOMERS turn to look at her.
Kate ignores them.
Esther can't suppress a little smile.
INT. DINING ROOM - NIGHT The family is eating dinner.
INT. DINING ROOM - NIGHT Esther makes a face and pushes her plate away half-finished.
ESTHER May I be excused?
KATE At least eat your chicken.
ESTHER I'm not going to eat something that I don't like just to make you feel better.
ESTHER That's ridiculous.
Esther, stop it.
Eat the chicken and then you can be excused.
ESTHER Yes, sir.
ESTHER Esther starts eating.
ESTHER Kate gives John an exasperatedlook.
The doo;rbel].
RINGS.
Esther i? 1/2 i? 1/2 dto Esther it.
it's Sisttereys.
a clipboard Abigail.
She's carrying
ESTHER Hello, Sister Abigail.
Hello, Esther.
Esther leads Sister Abigail upstairs.
Kate and John follow-
SISTER ABIGAIL to need updated charts I tA? also going t from her.
SISTER ABIGAIL pediatrician and her dentist for my supervision report.
That's no problem.
We've got a ch up with the dentist next week.
INT. ESTHER'S BEDROOM - DAY .Esther leads Kate, John, and Sister Abigail into her room.
ESTHER Isn't it lovely?
ESTHER Look at my new paintings.
ESTHER -I've=done a portrait -for everyone in the family.
ESTHER She shows sister Abigail the portraits pinned to her wall.
ESTHER There's also a painting of everyone together.
SISTER ABIGAIL That's one good-looking family you've got..
ESTHER I know.
ESTHER Aren't they perfect?
ESTHER Sister Abigail gives Kate and John an amused look-
INT. KITCHEN - DAY Kate, John, and Sister Abigail talk over coffee.
JOHN I swear, we-didn't bribe her to say that.
.y:
SISTER ABIGAIL No explanation necessary.
SISTER ABIGAIL I don't think there e'anything that girl could say that would surprise me.
She dropped the 't--bomb on me a few weeks ago.
'Sister Abigail raises her eyebrows in comic, exaggerated surprise.
Well.
I'm glad to hear she's finally come out of her shell.'
She's just testing us.
It's been nowhere near as bad as we expected.
SISTER ABIGAIL What kinds of things is she doing?
Talking back to me.
Purposefully disobeying.
She took Max to the park without ppesrmission the other day.
That was the biggie.
A girl they were playing with got hurt.
A beat.
Sister Abigail is suddenly apprehensive, tries to cover.
SISTER ABIGAIL Really?
SISTER ABIGAIL is the girl all right?
RATE She broke her arm and had to have something like eleven stitches, I think.
RATE She was lucky.
SISTER ABIGAIL She doesn't.
SISTER ABIGAIL sound very lucky.
JOHN She's lucky she didn't break her neck.
JOHN Sister Abigail seems troubled by this.
EXT. COLEMAN RESIDENCE - DAY Sister Abigail walks out to her car, concerned.
EXT. COLEMAN RESIDENCE - DAY She doesn't see Esther spying down from her bedroom.window, just staring at her with that strange, blank look...
INT. MUSIC ROOM - DAY Kate gives a piano lesson- to a.COLLEGE S7TUDENT, listening as he runs.
INT. MUSIC ROOM - DAY through a finger exercise.
Relax;.
wrists following fingers...
John leads Esther and Max on a bike ride around the neighborhood.
Esther speeds-up, leaving Max behind so she can ride next to John.
ESTHER I'm Daddy's little girl, aren't I?
JOHN That's right.
JOHN You both are.
JOHN As they head home, they see JOYCE 'PATTERSON (late 30's) jogging toward them.
JOHN A blonde with dark roots and an overdone boob job., wearing a skimpy sports bra and mini shorts.
JOHN She waves to tem.
Look at these three cutiesl
JOHN How're-you doing?
JOYCE Hanging in there.
JOYCE Hey,,.
JOYCE I've got.
JOYCE a chair X want moved upstairs.
JOYCE You think you could come over and give me a hand?
JOYCE John glances toward home.
JOYCE Kate's at the door, waving goodbye to the College Student.- She sees John talking to Joyce and gives them an unreadable look before going back inside.
JOHN Uh, yeah.
JOHN Maybe Kate and I -could help you -out.
JOYCE Okay, I'll call you.
JOYCE John and Max start off again, but'Esther doesn't move.
JOYCE She's openly looking Joyce over from head to toe.
ESTHER You have a l ovely body.
JOHN. Come on, Esther.
JOHN. Let's go.
JOHN. Esther reluctantly follows.
JOHN. Joyce eyes her dubiously.
John acid the girls enter.
Kate has juice boxes for the girls.
A.
look passes between John and Rate.
Esther notices.
KATE How was the.iide?
KATE Did you have fun?
Max nods'and heads off; but Esther hangs back, eavesdropping:
KATE Didn't waste -arty time-turning that divorce settlement-into a tit job, did= she?
JOHN I didn't notice.
KATE Yeah, right.
KATE She's teasing, but there's something biting underneath it.
KATE Esther walks away, sipping on her juice box..
After hours.
Sister Abigail is at her desk.
She opens a file and reads.
We see a Polaroid of Esther stapled to the cover...
EXT. CARNIVAL - NIGHT Midway rides and boardwalk games have been set up in the parking lot of Daniel and Esther's school.
EXT. CARNIVAL - NIGHT A banner reads ""EDGAR ELEMENTARY ANNUAL HALLOWEEN HOOT."
EXT. CARNIVAL - NIGHT The place is packed with excited children in Halloween costumes.
EXT. CARNIVAL - NIGHT The school is at the'top of a steep hill.
EXT. CARNIVAL - NIGHT Kate and John walk up it with the kids.
EXT. CARNIVAL - NIGHT Daniel's dressed as a ninja, Max is a "FINDING NEMO" fish, and Esther's an angel, complete with a shiny halo.
John gives Daniel some money to hang out with Austin and Trevor...
On the BOARDWALK, playing games, winning prizes.
Esther shoots BBs at balloons with a toy rifle.
She's pretty good at it...
On the MIDWAY, Esther and Max are whirled around on the Scrambler, screaming and laughing.
Kate and John watch and take pictures..'.
A cheap fun house attraction.
The girls ran up to John and Kate..
ESTHER We want to go in by ourselves)
JOHN Okay, just make sure you hold her hand.
ESTHER I will.
ESTHER - The girls.
ESTHER run inside.
ESTHER John smiles, but Kate watches anxiously.
Esther leads Max through the dark', winding fun house corridors.
Max starts to look cared.
She nearly leaps.
out of her skin when a RUBBER--MASTED GHOUL jumps out at them.
But Esther just laughs at it.
Max sees that she's not afraid and soon they're both giggling at the CHEESY SPOOKS that try to scare them.
EXT. CARNIVAL - NIGHT The girls emerge frtn- the'maze, clutching each other and laughing.
Let's play "hide and seek."
You go first.
Max excitedly runs off.
Esther watches her vanish into the CROWD.
Moments later,-Kate and John appear.
Rate-nervously looks around.
RATE Where's Max?
ESTHER I don't know.
ESTHER I was trying to hold her hand, but she pushed me and ran away.
KATE Oh,.my God...
JOHN It's okay.
JOHN Did YOU see where she went?
ESTHER This way, I think.
ESTHER She points the wrong way.
ESTHER Kate takes her hand and they quickly move through the crowd, looking for Max.
ESTHER John stands on a bench
for a better vantage, Kate grabs passersby:
KATE Have you seen a little girl in-a fish costume?
KATE She has short brown hair?
KATE Nobody's seen her.
KATE Kate grows frantic.
KATE Esther watches with a nonchalant smile, enjoying the drama.- She tugs on Kate's arm.
ESTHER i Mommy, I want scene cotton candy.
ESTHER - 'i? 1/2  'ti
Not now, Esther Ia??
Kate, please.
Take it easy.
She's gotta be around here Then Kate spots Daniel approaching, holding Max's hand.' Kate breathes a sigh of.relief and rushes to give Max a fierce hug.
KATE Are you all right?- Don't you ever run off like that[ What were you thinking?
DANIEL They were playing "hide and seek."
DANIEL - I- saw Esther let her run off.
DANIEL Esther gives him a sharp look.
DANIEL John turns on her, .
DANIEL angry.
JOHN Did you lie to us?
JOHN What did I tell you about'holding her hand?
ESTHER I'm sorry, sir.
ESTHER She looks like she's going, to cry.
ESTHER John sighs, then turns to Kate and Max.
ESTHER Esther gives Daniel a hateful look through her tears.
The kids pile into the minivan for school.
As Daniel climbs in, Esther' drops something behind him and pretends to find it.
ESTHER What's this?
ESTHER She shows Kate a little PLASTIC BAGGIE OF WEED.
ESTHER Daniel blanches when he sees it..
ESTHER His.treehouse staah..
INT. JOHN'S DEN - NIGHT Kate and John confront Daniel.
DANIEL I wasn't taking it to school[
RATE Then what was it doing 'in-your backpack?-
DANIEL I don't knowl" She just put it there to.
DANIEL get me in troubles
JOHN Where would'Esther have gotten pot?
DANIEL She saw me wCth it in the treehouse.
Is that what...you're doing- out .there with Austin and Trevor?
Smoking pot?!
Daniel stammers.
John stews-.
John screws a hasp to the treehouse-door with -a POWER DRILL and slaps a PADLOCK on it.
Daniel stands below,-watching.
John climbs down, shows Daniel the padlock key, and pockets it.
Off limits until further notice.
Be heads to the house; Esther is playing in the backyard..
She takes John's hand and walks inside with him.
Daniel watches them.
INT./EXT. KATE'S MINIVAN - DAY Kate pulls out of the driveway with Esther in the back seat.
INT./EXT. KATE'S MINIVAN - DAY As they leave the neighborhood, Joyce Patterson Jogs by in her skimpy workout clothes.
INT./EXT. KATE'S MINIVAN - DAY She-waves.
INT./EXT. KATE'S MINIVAN - DAY Kate gives a polite nod.
ESTHER Why does she have to'dress like that?
KATE - She just likes the 'attention.
ESTHER Well, I think it's immodest.
ESTHER I don't know why Daddy -likes her so much.
KATE . (a beat, apprehensive)- What do you mean?
ESTHER He's always smiling at her and talking to her.
ESTHER She wants him to come over to her house.
ESTHER Did you know that?
ESTHER Please don't tell Aaddy I told.
ESTHER I don't want him to be mad at me.- Kate doesn't respond, clearly disturbed.
Kate gets out Of the minivan, but Esther stays put'-in her seat.
Rate sighs, frazzled and distracted.
KATE Esther, come on.
ESTHER X told you, I don't like the de ntist.
KATE There's nothing to be afraid of.
ESTHER - I know.
ESTHER - Because I'm not- going-
KATE Esther, get out of the cart Righ t now!
KATE For a moment, they just glare at each other.
KATE Mexican stand-off..
KATE Then Esther sticks her nose in the air and does as she's told.
The DENTIST lowers Esther back in the chair, pulls on rubber gloves.
The HYGIENIST clips a dental bib around Esther's neck.
She hasn't had a check-up in about two years, so she's a little nervous.
she doesn't look to me.
Now let's have a look at those co ppers.
Esther just looks at the ceiling with her mouth tightly shut.
Come on, darling, open wide.
-Esther eyes him anxiously; then reluctantly opens.
Just a bit.
DENTIST That a girl: Little wider...
DENTIST She opens more.
DENTIST He leans in to take a look...
DENTIST Suddenly, she SHdMPS dawnn his jinx s hard Pnou h to draw blo-mss fr and locks i? 1/2 n like Rottweilei? 1/2 ] The Hygienist is frozen in shock.
DENTIST Aaagh!
DENTIST Goddammit!!
DENTIST Help me with her !
DENTIST The Hygienist holds her down while the Dentist tries to pry her mouth open.
DENTIST Finally, he yanks his fingers free, cradling them
painfully.
Esther HISSES at ldm like a cat, lips flecked with blood.
The Dentist and Hygienist exchange a startled.
lock.
Canned MUSAK..
Kate bits waiting.
The Hygienist enters.
Mrs. Coleman?
Kate gives her a confused look.
Then she notices Esther htanding behind the Hygienist with a-smug grin on'her face.
INT./EXT. KATE'S MINIVAN - DAY Driving home..
INT./EXT. KATE'S MINIVAN - DAY Kate stews, on her last frayed nerve.
INT./EXT. KATE'S MINIVAN - DAY Esther gazes out the window, seemingly oblivious, singing a little nonsense song under her breath: "La-la-la, la-la-la-la...
INT./EXT. KATE'S MINIVAN - DAY La--la-la ..."
INT./EXT. KATE'S MINIVAN - DAY Kate stops at a traffic light.
INT./EXT. KATE'S MINIVAN - DAY Glances outside.
INT./EXT. KATE'S MINIVAN - DAY She's stopped next to a LIQUOR.STORE.
INT./EXT. KATE'S MINIVAN - DAY Kate quickly looks .away, her temptation real enough to startle her.
INT./EXT. KATE'S MINIVAN - DAY The light turns green and she drives off without looking back.
INT./EXT. KATE'S MINIVAN - DAY Esther keeps SINGING..
INT./EXT. KATE'S MINIVAN - DAY A few blocks later, they pass a BAR.
INT./EXT. KATE'S MINIVAN - DAY Then a bus shelter with a big ABSOLUTE VODKA AD.
INT./EXT. KATE'S MINIVAN - DAY Kate probably drives by them every day, but now they're popping out at her, sly old enemies that never really left, re-emerging from the shadowy recesses of her mind.
INT./EXT. KATE'S MINIVAN - DAY She tries to focus on the road, Esther's VOICE grating in her head...
INT./EXT. KATE'S MINIVAN - DAY "La-la-la, la-la-la-la:..
INT./EXT. KATE'S MINIVAN - DAY La-la-la, la-la-la-la..."
Kate and Esther enter.
Esther skips upstairs.
Kate sighs, angry and frustrated.
She plays a message on the ANSWERING MACHINE.
Hello, this is Sister Abigail calling for John and Kate.
Please call me as soon as you get this message.
I have.
something that we need to discuss in person.
It's regarding.
Esther.
Esther stands at the top of the stairs, listening to-the message- She's heard everything.
And she's scared.
Scared and pissed.
Kate and John get ready for bed.
KATE He's been our dentist for ten years.
KATE Why would he lie to us?
I didn't say he's lying.
I just think Ws-blowing it out of proportion,
KATE I saw the bite marks.
KATE We're lucky he's not suing us.
JOHN Fine, but I don't believe for a"second that she just did it for no reason.
RATE That's because she's always on her best behavior with you.
JOHN' That's.
JOHN' not true.
JOHN' I've had to deal with her at her worst..
- KATE What you think is her worst is what she's like with me all the time.
- KATE She's completely- different with me than she is with you'.,
JOHN So you've seen her haul off'and bite someone like an animal?
KATE No, but she threw that fit at school
Yeah, because the other kids were harassing her.
It's the same thing here.
She's from a completely different culture Kate.
She has to be taught that this.
behavior isn't appropriate but there's nothing malicious about it.
If'she says she bit him because she was scared and he was hurting her, I don't see any reason not to believe her.
A beat.
Kate looks at him.
She's stewing hbaut something.
KATE So should .1 believe her when she says you've been hitting on Joyce Patterson?
JOHN' Did she say that?
JOHN' t.
Is it true?
JOHN of course not!
KATE Did-she invite You over?'
JOHN She wanted me to help her move a chair.
KATE Oh, - come on.
All right, she was obviously coming to me.
But I shut her down.
KATE Then why didn't you tell me?
JOHN Because I knew how you'd reactl
KATE Really?
KATE You sure it wasn't because you were coming-on to her so obviously that an eight-year-old picked upon it?
KATE A long-beat.
KATE John sighs, resigned.-
JOHN How-long are you going to keep this hanging over me?
JOHN It was ten years ago.
KATE You keep-saying that.
KATE But it's only been about two years since you told me.
KATE Having another child was -supposed to bring us together.
JOHN I'm sorry I didn't tell you-about it- x just feel like I've earned a little trust here.
KATE - I don't know what you expect from me.
KATE - I might never completely trust you again.
KATE - Not like before.
JOHN I gave you a second chance.
i? 1/2 4
Kate stops short.
IIis words-are like a phybical blow.
That's not fair.
JOHN So-you can keep bringing uP my .
JOHN mistakes over and Over, but we're not even allowed to discuss yours?
KATE I was sick!
KATE You were just an asshole who wanted to fuck somebody else!
JOHN You were a danger to our children.
JOHN If I didn't want to.
JOHN make this work, I could have left months ago and nobody would have blamed me.
KATE Nice.
KATE Is that-what-your mother told you?
KATE Angry tears well in her eyes.
KATE He realizes be went too far..
KATE Kate goes into the bathroom and SLAMS the door.
It's late.
Esther and Max sit on the bed in their nightgowns.
Only the bedside light is on.
They're signing to one anothe r.
ESTHER THE MAN LADY YS Comm TOMORROW.
Max anxiously nods her head.
Esther smiles.
The room is dark.
The girls sneak in, still in their nightgowns, and close the door.
Esther turns on a :reading lamp.
Look for the key to the treehouse.' -Max nods and they start searching the room.
Esther rifles through John 's desk.
- Nothing.
She looks in a closet.
A DARK PLASTIC CASE with Two PADLOCKS on it catches her eye...
Max opens a.
keepsake chest and finds SEVERAL KEYS on:a ring.
She excitedly shows them to Esther.
Esther smiles and takes them.
As they're about to leave,.Esther.
Uses.
She looks back at the- closed closet.
Then looks at the keys.
Max eyes her curiously.
Esther slides a chair over to.
the closet and opens it..
She stands on the chair, pulls down the case with the padlocks on it, and sets it on the floor.
She tries a couple of.keys.
Then -- CLICK.
There's a GUN inside.
A shiny revolver and a BOX OF AMMUNITION.
Esther's face lights up.
She.carefully picks up the gun{-turns it over, looks at it.
Max's eyes nearly pop out.
Esther gives her a sly look, then loads a single bullet, SPINS.
the cylinder...
.and points the cmn at ax.
Ri.aht between the Bye
ESTHER Do you -want to_ play?
ESTHER - A beat.
ESTHER Max shakes her head.
ESTHER Esther smiles, fingers the trigger.
ESTHER After a long, awful, pants wetting eternity, she lowers the gun.
ESTHER You're right.
ESTHER We'd better not.
Not yet.
Sister Abigail sits across from Kate and John with a grave look.
SISTER ABIGAIL When you first asked about adopting Esther, I expressed some misgivings.
SISTER ABIGAIL But I wasn't completely straightforward with you.
SISTER ABIGAIL You see, I love children.
SISTER ABIGAIL I've worked with them my entire life.
SISTER ABIGAIL And the thing about love is that it sometimes clouds your judgement.
But the truth is that I knew there was something wrong with Esther from the moment I laid eyes on her.
Kate sits up, concerned.
John bristles.
- KATE You said you suspected, some kind of abuse.
SISTER ABIGAIL Yes, but there was something else.
SISTER ABIGAIL It was hard to say chat it was at first.
SISTER ABIGAIL Just-a feeling that she was a profoundly damaged little girl.
(beat) s eemed Then I notaced that she - always k_ to.
be around whenever ther' wwasa get kind of trouble.- Two girls iii a fight.
And there she'd be .
Someone would get caught stealing.
And ell she'd - myself it Was But I never really.
believed it.
(beat) l who After you told me about the gir broke her arm, -:E -started wondering again.
I called the achool:Esther went to while she was with the Wallaces and asked if there'd been any serious accidents while she.Was there..
One incident was still fresh in everyone's minds.
A boy in one of her classes was stabbed in the throat with a pair of 'scissors.
All the kids-who saw it happen said it was an accident, that he was running with the scissors and fell.
But once again, Esther, was there.
is eavesdropping from around the corner.
She slips away.
JOAN But none of these things were her fault.
SISTER ABIGAIL That's; g I was reluc!tant to t anything bef ore.
SISTER ABIGAIL Now'I think th at may a have been a mistake.
SISTER ABIGAIL Children like Esther, who've spent their entire lives-in institutions, have never had' a chance to 'form normal, lasting bonds..
SISTER ABIGAIL The longterm effects of 'this- can be devastating.
SISTER ABIGAIL In the very worst cases, children who fail to form early attachments are unable to learn the difference between'right and wrong.
SISTER ABIGAIL They can lie, cheat, steal --- .or worse -and and have no remorse whatsoever for their actions.' They view other human beings as objects, pawns for their amusement.
SISTER ABIGAIL And they can-be potentially very dangerous.
INT. ESTHER'S BEDROOM - DAY white s gloves, like she's Esther pulls on -a pair of .
INT. ESTHER'S BEDROOM - DAY dinty hurCh services dressing for morninga
JOEt7- This.doesh't sound like Esther at all.
SISTER ABIGAIL A severely character-disturbed child can appear to be -completely normal, -even exceptional.
SISTER ABIGAIL It's like they have two faces one-they show the outside world in order'to get what they want, and the other, their true face, lying just beneath the surface.
INT. MAX'S BEDROOM - DAY Max sits on her bed, wearing a jacket and clutching her "Bello.
INT. MAX'S BEDROOM - DAY Kitty" backpack.
INT. MAX'S BEDROOM - DAY Anxious and waiting.
INT. MAX'S BEDROOM - DAY Esther enters.
Let's go.
KATE What about the orphanage in Russia where she was raised?
KATE Wouldn't they have been able to tell?
SISTER ABIGAIL - I've put in a call to the director there, but she could have easily slipped through the.
SISTER ABIGAIL - cracks.
JOHN - So the bottom line here is that you don't have proof of any of this.
SISTER ABIGAIL That's true,-I don't.
SISTER ABIGAIL But I believe the circumstantial evidence is enough to warrant taking the next step.
RATE Which is what?
Get Esther out of'the house.
Kate and John are stunned.
JOHN You want to disrupt the adoption over this?!
SISTER ABIGAIL - If I'm-wrong, she-can come back home.
SISTER ABIGAIL - But you need to get her to a therapist who can tell you what you're dealing
JOHN She's just a kids -
SISTER ABIGAIL She's also the sole-survivor of a house fire that killed her last family.
SISTER ABIGAIL It was arson.
SISTER ABIGAIL I did some checking.
SISTER ABIGAIL Someone deliberately set that fire.
SISTER ABIGAIL They-never caught who did it.
JOHN Wait a minute, you're not suggesting --
SISTER ABIGAIL Pyromania is one of the warning signs of a character--disturbed child.
Rate blanches, realizing:
KATE Do you think she had something to do with'what happened to Yolanda?
KATE A long beat.
KATE Sister Abigail hesitates, reluctant to answer.
SISTER ABIGAIL - The thought that a child could cougnit such a monstrous crime flies in the face of everything I hold dear.
SISTER ABIGAIL - But in my opinion, at'a a possibility that you need to take very seriously.
Esther slides the door open -on SCREECHING rails and steps inside.
Walks over to John's workbench.
Looks at the TOOL RACK above it.
INT. LIVING ROOM - DAY Kate and John are stunned by what Sister Abigail has told them.
JOHN We can take her to Doctor -Browning.
JOHN - Kate suggested doing that weeks ago.
JOHN But I don't want to send her away.
JOHN Not without at least some kind of proof.
Sister Abigail.sighs, frustrated.
Kate turns to him:
KATE But what if 'the doctor says she's dangerous?
KATE A beat.
KATE He considers, uncertain and emotional.
Then I guess we.won't.bave any choice.
EXT. FOREST - DAY Daniel sits near.the brook, sullenly throwing rocks in the water.
EXT. FOREST - DAY He hears something behind him and turns.
EXT. FOREST - DAY Esther and Max are running off through.the woods, leaves CRASHING under their feet.' Neither of them ree him.
EXT. FOREST - DAY He eyes them curiously.
EXT. COLEMAN RESIDENCE - DAY Sister Abigail ie leaving.
EXT. COLEMAN RESIDENCE - DAY Rate and John stand by the front door, 'troubled, watching her go.
Esther and Max run toward'the bridge where.
the road into the neighborhood crosses the brook.
They climb an embankment and crouch.
by the bridge abutment, out of breath.
Esther looks both ways.
There's no traffic.
She and Max hide behind the abutment.
Sister Abigail drives away., troubled.
She takes a pack of cigarettes from the glove compartment and lights one.
EXT. PRIVATE ROAD - DAY The girlb wait by the abutment.
EXT. PRIVATE ROAD - DAY The only sound is the RIPPLING brook.
EXT. PRIVATE ROAD - DAY Max looks nervous.
EXT. PRIVATE ROAD - DAY Esther gives her a reassuring smile.
ESTHER - It's going' to be fine.
ESTHER - Just wave your arms and make sure she stops.
ESTHER - Max nods.
ESTHER - Then Esther hears a CAR coming.
ESTHER - She peers out'from behind the abutment.
ESTHER - It's Sister Abigail's car.
ESTHER - Esther quickly ducks out of sight.
ESTHER Here she.
ESTHER comes.
ESTHER Wait until she gets close.
ESTHER Max nervously peers out from behind the abutment.
ESTHER Esther stands behind her.
ESTHER The car starts across the-bridge.
ESTHER Suddenly -- -- sthe pusbes Max it into the Load.
ESTHER stumbles and falls ri ht ,m.
ESTHER on of the _speedi? 1/2  car.
Sister Abigail gasps and SLAMS on the brakes, 'TIRES SQUEALING, stopping the car mere feet from where Max lies in the road.
She frantically.
jumps out of the car and kneels next to Max.
SISTER ABIGAIL Dear Lord!
SISTER ABIGAIL Are you okay, honey?
SISTER ABIGAIL Max looks up at her,-stunned, but unhurt.
SISTER ABIGAIL Sister Abigai1 is taken aback.
SISTER ABIGAIL She recognizes her.
SISTER ABIGAIL - Max...?!
SISTER ABIGAIL - - - A SHADOW falls on Abigail from behind.
SISTER ABIGAIL - She turns and looks "up.
SISTER ABIGAIL - Esther looms.over her, a CLAW HAMMER raised above her head.
SISTER ABIGAIL - efor is a Abigail Va e a , Esther angrily hits her in tie ' l head as hard as she can with the hammer.
SISTER ABIGAIL - CRUNCF#.
SISTER ABIGAIL - Max startles,'eyes wide with shock.
SISTER ABIGAIL - Sister Abigail falls and lies twitching on the pavement.
SISTER ABIGAIL - Eyes staring blankly, one pupil wide from the head trauma.
SISTER ABIGAIL - Blood trickles from under her headdress.
SISTER ABIGAIL - As Max stares at.
SISTER ABIGAIL - the body, paralyzed with fear, Esther scurries into Sister Abigail's car and finds her purse.
SISTER ABIGAIL - She flips through her wallet.
SISTER ABIGAIL - Cash, credit cards.
SISTER ABIGAIL - Takes it all.
SISTER ABIGAIL - Finds her rosary beads.
SISTER ABIGAIL - Grabs them, too.
SISTER ABIGAIL - Then she hurries back to the body.
ESTHER Help me get her off the road.
ESTHER Max looks up blankly, then staggers .to her feet.
ESTHER They each take a hand and start dragging Sister Abigail's body, but she's heavy and they're little.
ESTHER It's all they can do to slowly move her.
ESTHER Then Esther hears something.
ESTHER There's ANOTHER CAR coming.
ESTHER It's still out of sight through the trees, but closing.
ESTHER Esther and Max hurriedly drag the body, struggling it to the side of the road, just as the car rounds the bend.
ESTHER Esther gives the' body a kick,, sending it rolling down the embankment.
ESTHER The car is almost on them.
ESTHER Esther and Max quickly hide under the bridge..
ESTHER Esther grabs Max's backpack and pulls u wig _cm.
ESTHER The car reaches the bridge.
ESTHER Esther listens to it cross, tense, gun .
ESTHER ready...
ESTHER but it passes Abigail's car and continues without stopping.
ESTHER Esther breathes a sigh of relief.
ESTHER Suddenly, there's a CROARING_noise from behind them.' Esther turns.
ESTHER It's Sister Abigail.
ESTHER She's still alive.
ESTHER She's trying to speak, but all that comes out is an awful'MOAN.
ESTHER Esther scowls and grabs the hammer.
ESTHER Sister Abigail looks up at her,' moaning louder.
ESTHER Then Esther brings-the hammer down.
ESTHER CRUNCH.
ESTHER The moans stop.
ESTHER Esther hits her AGAIN and AGAIN.
Ma x 'pr cataton ipes her Se p rettysdr sand white glove harernow splaa ered ith blood.
e s t t
ESTHER Did you get any on you?
ESTHER Max shakes her head, pale and shivering.
ESTHER Good.
ESTHER Let's get her covered up.
ESTHER Esther starts scooping leaves and debris onto Sister Abigail's corpse.
ESTHER Max just watches fora long beat...
ESTHER then shuffles over like a zombie and helps her.
ESTHER Esther smiles..
Esther is wearing a clean dress.
-- She stuffs Max's "Hello Kitty" backpack under the looUe floorboard where Daniel.used to keep his weed.
Max is huddled in a-corner, still dazed.
As the y talk, Esther laces the bloody from Sister"ibigails car i a lastic grocery bag s ade ties kit.off.
ESTHER If you tell on me, you'll get in trouble, too.
ESTHER. That doesn't matter.
ESTHER. 'They'll send you to jail just for helping me bury her.
ESTHER. Max starts to cry.
ESTHER. Esther moves closer, comforting.
ESTHER She wanted to take me away from you.
Now we eau be together forever.
Daniel heads home on the path through the forest.
Be hears a NOISE up ahead and sees Esther and Max emerge from the treeh ouse.
He quickly hides., 'watching.
Esther locks the treehouse_and looks around, see him.
She and down and walk home hol d din in g pe ers out at them...
g hands.
Daniel
The usual suspects are here.
Kids playing.
Moms watching.
The Homeless Guy with.his shopping cart, rooting through a trash can.
A VENDOR selling a SpongeBob popsicle from a cart.
CAMERA FOLLOWS the SpongeBob pop as.
the vendor hands it to a little girl...
It's Esther.
She smiles at the.
vendor and walks away.
She- spots the Homeless Guy across the park and casually heads toward him.
As she approaches, we see that she's carrying the -plastic yrocery bag with the bloody hammer and sister Abigail's things in t.
She carefully looks around to snake sure nobody is watching, then nonchalantly tosses the incriminating bag into the Homeless Guy's shopping cart and keeps walking, sucking on her SpongeBob pop...
Rate hangs up the phone and turns to John.
RATE She's canceling some appointments-so we - can get her in-tomorrow.
RATE They hear Esther HUMMING upstairs and exchange a disgiuieted look.
Esther HUMS O.S. -Her black velvet ribbons have been removed and laid out in a row on the counter.' CAMERA MOVES to the bathtub, where Esther is taking a bath.
The water is faintly red.
-She's scrubbing under her fingernails.
-Humming pleasantly to herself.
And now we see what the ribbons have been covering: the has t ick, knotte t h e wa x u ht.r neck and -wrists.
INT. JOHN'S DEN - NIGHT John sits on his.
INT. JOHN'S DEN - NIGHT desk, eyeing Daniel--wearily.
JOHN Esther and Max?
JOHN You saw them?
DANIEL Oh-huh.
JOHN The treehouse is still locked.
DANIEL Esther had the-keys.
JOHN You mean these keys here?
JOHN He goes over tothe keepsake chest and opens it..
JOHN The KEY RING is there.
JOHN He holds it up.
JOHN Daniel flusters..
JOHN You're not lying to get them in- trouble,.are you?
DANIEL No, I swear!
JOHN I don't know what's got into you lately.
JOHN Just go to your room.
JOHN Daniel leaves, dejected...
and trudges upstairs.
fe doesn't see Esthe emi? 1/2  eras from j - a sh dows behin hii? 1/2 - She glares angrily, after him...
Alone now, John looks at the.key ring, considering.
Be goes to the closet, looks at the'gun case.
Takes it down.
Unlocks it...
The gun.is right where it belongs.
He sighs and closes the case.
Daniel is in bed, sound asleep The doorknob turns, the door CREAKS open.
Someone sneaks into his room, approachinbglh1ss-bbed.
Turns on the bedside light, Daniel stirs, squinting, It's Esther.
Daniel looks up at her, confused.
Ruaaenlv,,shs fistful gf i hair and SLAM bis hea hMk.Aqg__inst the Before he can cal ou ; $he w o a-PAI OF SCISSORS an plunges them tows d his face--- Daniel gasps, but the gleaming point of the scissors stops short,- hovering less than an inch from his wide, staring eye.
ESTHER ssshhh.
ESTHER Esther leans in, her face wild-and terrifying.
ESTHER Daniel lies there breathless, paralyzed with fear.
ESTHER -The.
ESTHER scissors drift from his eye, his between his legs.
ESTHER holds fast by his ha ir.
ESTHER er'voiceis an'e H il, ssibant bhiss
ESTHER You te.11 anybody what you saw and I will cut your hairless little prick off before you even figure out what it'-s for.
ESTHER Do you understand me?
ESTHER She rapidly cuts the air with the scissors -- SNIP-SNIPI Daniel frantically nods his head.
ESTHER She twists his hair again.
ESTHER ,= -it
I won't tells I won't tell, T xomisel p She holds him for a beat, savoring his fear.
A DABX STAIN seeps through the bedspread.
Esther' sees it and grins.
ESTHER You pissed yourself.
ESTHER Daniel is crying, humiliated, belplesa.,'too terrified to dare make a sound.
ESTHER Finally, she releases him and turns off the light.
ESTHER As ick ad :it bWgan it she's go .
ESTHER up in a b all and his faa in his pillow stifl e his Bobs
A SECRETARY sits behind a desk.
Kate flips through a magazine.
m John glances at his watch.
Rate gives him a moment later, Dr Browning emerges from r office u with Esther.
ESTBER It was nice talking to you, Alice.
ESTBER I I hope we can be friends.
DR. BROWNING I'd like that.
DR. BROWNING You can come on in-
INT. DOCTOR BROWNING'S OFFICE - DAY Dr. Browning's manner is serious.
INT. DOCTOR BROWNING'S OFFICE - DAY Kate and John sit, anxious.- '
DR. BROWNING o Well, let's start with what youca me here for.
DR. BROWNING You don't have anything' be worried about with Bsther.
DR. BROWNING John breathes a sigh of relief.
DR. BROWNING Kate gives-a dubious smile.
KATE She's not dangerous?
DR. BROWNING No, of course not.
JOHN Thank God.
DR. BROWNING It's.
DR. BROWNING not all good news .
DR. BROWNING You do have a serious problem in.
DR. BROWNING your home..
But the real issue is with you, Rate Kate reacts, stunned.
Esther.
fidgets, impatient.
She turns to the Secretary:
May I go to the restroom?
Dr. Browning continues.
Kate' can't believe what 'she's hearing:
DR. BROWNING I was able to coax her into admitting that there's been some tension between the two of-you.
DR. BROWNING She's really tr!ing very hard to please you.
DR. BROWNING The problem is that you're blocking her attempts-to attach-with you.
DR. BROWNING That's why whenever something bad happens, you blame her, whether it's really her fault or not.
KATE But that's not what's.been happening.
DR. BROWNING I doubt you're even aware that you're doing it.
DR. BROWNING But subconsciously you t aunt her to be bad because' demonizing her is your way of covering your own feelings _ of inadequacy as a mother.
KATE I don't feel inadequate.
DR. BROWNING But you do have doubts.
DR. BROWNING You worry that' you Could relapse.
KATE What does that have to do with'Esther?
DR. BROWNING Frankly, everything.
DR. BROWNING Your guilt over what happened with Max is preventing- you from bonding with Esther.
DR. BROWNING Kate turns to John, aghast, but he's taking this very seriously.
DR. BROWNING It's made you doubt your fitness as a mother.
DR. BROWNING And that terrifies you.
DR. BROWNING So you're having trouble with Esther, alonV comes Sister Abigail with these stories about her being some kind of monster and you believe them because
it f s easier than with yojW fear ,that there's something hwrong th you.
RATE . What the hell did she tell you?.
Let's not m4ke this about herana m a d dne real progress with her today tell you with complete certainty that Esther is not to blame here.
in a C AMERA MOVES IN on one- , o 131sthex is in a ba11 muttering t herself, her eyes glassy and star
ESTEER She didn't see.
ESTEER She doesn't know.
ESTEER She doesn't knout Ahitl She starts POUNDING the walls-of stall th her fists.
ESTEER We CUT between her a Dr.-B rowning talking to ltate
DR. BROWNING She's an extremely bright, thoughtful, sensitive little girl going through a very challenging time.
DR. BROWNING Esther clutches her head, rocking back and forth.
ESTHER Goddamn, coaksucking bitch!!
ESTHER Thinks she knows well Doesn't know shit!!
DR. BROWNING You just have to learn to be more patient.
DR. BROWNING .You're really very lucky to have her.
Esther's fit has passed.
She neatly composes herself and emerges from the stall...
and sees that there's a WOMAN at the sink.
She eyes Esther warily.
Probably heard everything.
Esther hesitates , then walks right by with.
her nose in the air.
John pulls the car in out of the RAIN.
They get out and Esther.
goes Inside.
When Kate is sure she's out of earshot:
KATE Thanks for the support back there.
JOHN Hey, I'm not a psychiatrist.
JOHN And a lot of what she's saying makes sense.
JOHN Before she can respond, Nate's cell phone RINGS.
JOHN She turns away from John' and'answers it.
JOHN He sighs and goes inside.
KATE - Hello?
is this Mrs. Coleman?
KATE Yes.
KATE Who's calling?
This is Sister Judith from Saint Cabrini's.
I'm sorry to bother you.
Did-Sister Abigail make.it to 'her appointment with you yesterday?
T tXNDER rolls.
CRIME SCENE TAPE flutters in the rain.
POLICE CARS are parked-on the roadside, lights FLASHING.
DETECTIVES shine flashli.ghts'Under the bridge.
sister Abigail's body- has been- discovered.
Kate and John sit across from a POLICE DETECTIVE and TWO UNIFORMED PATROL OFFICERS.
Kate and john-are still in shock.
JOHN We'll help in any way we can.
JOHN We at least owe her that much.
KATE Do you have any idea who could have done this?
We have .a suspect in custody based on an anonymous -tip.
We're just trying.
to - place ham at the time we think the - murder took place.
JOHN Who is it?
I can't tell you that right now.
But he was found with the murder weapon, along with some cash and credit cards.
JOHN Jesus..:: at kind of sick' monster carjacks a nun?
JOHN Kate glances up, sees Esther crouched on the stairs, watching...
JOHN INT.
JOHN fAMiLY ROOM - DAY Daniel sits in a big recliner, sullenly playing a VIDEO GAME SHOOT- EM-OP.
JOHN Kate is researching- on the Internet.
JOHN We get CLOSE SHOTS of some of her Google.results, INTE Ctfs with Daniel BLASTING AWAY
at alien baddies, his face angry and intense: "Character-disturbed Children."
-BLAME.-BLAME-BLAME "Antisocial Personality Djsorder."
PL f-BLAMI- "C ren o Kfll."
Esther enters holding Max's handy leadin her around like a pet.
Max numbly follows.
They walk up to Daniel'in the recliner.
ESTHER We want to sit there.
KATE Esther, Daniel was there first.
KATE - Daniel eyes Esther.
KATE Wary, but defiant.
KATE She sighs and makes a -"cutting" motion with two fingers.
KATE Daniel brusquely turns off th e game and gets out of the chair.
KATE - As' he leaves, Kate calls out,
KATE Daniel?
KATE Daniel?
KATE He ignores her and stomps upstairs.
KATE She watches him, concerned.
INT. JOHN'S DEN - NIGHT Kate shows John some pages she's printed out from the Internet.
KATE This is what Sister Abigail was telling us about.
KATE Character-disturbed children, 'Look at the, symptoms.
"Superficiallycharming.
Difficulty making and keeping frinnds.
Cruelty to pets.
Bossy and controlling.
Overly affectionate with strangers."
JOHN "Extended period of bedwetting.
JOHN Speech pathology.
JOHN Abnormal eye contact."
JOHN She doesn't have half of these.
KATE I still think Doctor Brow have missed something.
KATE iner couldd
have just told her what she wanted; to hear.
Look.
"Character-disturbed children are adroit manipulators.
They can be exceptionally charismatic, oftentimes playing people off one another to get what they want."
JOHN save you showed this to Doctor.
JOHN BA?owiiing?
KATE (hesitates)- I'm not 'seeing her anymore..
JOHN You're not going to therapy?
JOHN When did you decide that?
When do you think?
John sighs.
A tense-beat.
JOHN I know you were.
JOHN upset.
JOHN But we have to at least consider the possibility that she's right about this.
KATE No, we don't.
KATE Why does everybody around here get the.benefit of the doubt fro m you except me?
JOHN That's not true.
JOHN I'm just..worried about you, that's all.
JOHN We can hire someone to help you with the kids if it's getting to be too much.
KATE I don't need help.
KATE All I want is for a doctor who knows what they're doing to give us a second opinion.
INT. ESTHER'S BEDROOM - NIGHT All the lights are out except for the BLACK LIGHT in the aquarium.
INT. ESTHER'S BEDROOM - NIGHT Bather is touching up the PAINTING OF THE MOTHER LION we saw when -we first met her, but we can't see what she's doing to it.
INT. ESTHER'S BEDROOM - NIGHT The black light causes some of the paints on her palette to fluoresce.
John and Kate's VOICES carry, up through the heating vent:
JOHN We're-not going to.keep taking her to doctors until you hear what you want to hear.
KATE - That's not what I'm trying to dal I -want this to work just as much as you do, but there are.
KATE - serious questions.
KATE - that we still don't havethe answers to.
KATE - If Sister Abigail was right about Esther,.
KATE - then people are dead because of
JOHN - She didn't really believe that.
RATS She didn't want to believe it.
RATS But she was worried enough-to think we should put her in foster care until we found out for sure.
JOHN For all, her good intentions, sister Abigail was not a trained psychologist.
JOHN She'had certain suspicions about Esther and they turned out to be wrong.
JOHN Why is can't you accept that?
KATE What if somebody else thought there was something wrong with her?
KATE Like the director of the orphanage in Russia?
KATE Esther stops painting and listens, suddenly apprehensive.
KATE if it's a dead end, I'll drop it.
KATE - But if they say the same thine, then we'd have to get.a second opinion.
KATE John considers.
KATE He doesn't want to be unreasonable.
KATE He nods.
JOHN All right.- See what you can find out.
Esther' fumes.
She angrily throws her painting across the room.
rNT.
KATE AND JOHN'S BATHROOM - MORNING John-is shaving with his shirt off.
He sees Esther in the reflection, slyly watching him.
She smiles at him.
Will, you take me to school today?
JOHN You'll have to get ready early,
I .don't mind.
INT. LIVING ROOM - DAY Kate is on the.
INT. LIVING ROOM - DAY phone.
INT. LIVING ROOM - DAY She has pen and -paper ready to take notes.
KATE Sister Judith?
KATE Hi, this is Kate .Coleman.
KATE I teas.wondering if you'd heard from anyone at the Sludianka Orphan's Shelter in Russia.
KATE sister Abigail said that...- Oh, you did?
KATE What do you mean?...
KATE Well, I don't understand.
KATE How could they not have any record of her being there?
.Yes, please.
Call me the moment you hear anything.
Thank you.
She hangs up, disturbed.
John drives.
Esther rides next to him.
She SNIFFLES and he realizes that she's holding back tears.
JOHN What's the matter?
ESTHER I don't want to go to school.
JOHN Why not?
ESTHER I hate it.
ESTHER Nobody likes me there.
ESTHER Nobody ever likes me.
ESTHER She stares forlornly out the window.
ESTHER Big sad eyes.
ESTHER John sighs.
JOHN You want-to play hooky?
JOHN I can call in- sick and we'll go to -the zoo.
JOHN What do you think?
JOHN Esther smiles through her tears.
ESTHER I'd like that very much.
ESTHER EXT.
ESTHER ME TARY SCHOOL r MORNING Kate drives up the steep hil1 in front of Daniel and Esther's school and stops at the end of a long'line of parents dropping kids off.
ESTHER Daniel.
ESTHER gets out without looking at Kate.
KATE Daniel, wait a minute.
KATE He hangs back.
KATE Rate gives him and Max a concerned-.look.
How are you guys getting along with Esther?
- , Daniel freezes.
An apprehensive look passes between him and Max.
DANIEL Fine, I guess.
KATE Does she ever make you guys feel uncomfortable or do things you know she's not supposed to?
KATE Has she ever hurt either of you?
KATE Daniel wants to say something, but the frightened look on Max's face stops him.
KATE Rate realizes she's struck.a nerve.
KATE Please.
KATE You can tell me anything.
DANIEL -I gotta gu.
DANIEL Before Kate can stop -him, he closes the car door and runs off.
John and Esther walk by the LION exhibit.- She takes John's hand and presses it to her cheek.
ESTHER You don't know how-long I've waited for a 'daddy just.
ESTHER like you.
JOHN And a monany, too.
JOHN Right?
JOHN Esther hesitates.
JOHN John notices.
JOHN She gives a sad shrug.
ESTHER I don't think !'Tommy likes me very much.
John is taken aback.
An awkward beat.-
JOHN That's not true..- Mc=my loves 'you.
ESTHER It's all right.
ESTHER I understand if she doesn't.
ESTHER It must be difficult to love an adopted child as much as- your own..
JOHN Sweetheart, .you are just as much a part of this family- as Danny.
JOHN and Max are.
JOHN Mommy doesn't love'you any less because you're adopted.
JOHN Do you understand?
JOHN She nods, but doesn't look convinced.
JOHN John thinks.
JOHN Why don't you do something special for her?
JOHN So she can see what a good girl you are.
JOHN I'll bet she'd like that.
JOHN Esther's face brightens.
That's a wonderful idea.
I think I know just what I'm.going to do, too.
INT. KITCHEN - NIGHT After dinner.
INT. KITCHEN - NIGHT Kate is loading the dishwasher.
INT. KITCHEN - NIGHT John is brig ing in dirty dishes from the dining room.
INT. KITCHEN - NIGHT Esther enters, all smiles.
INT. KITCHEN - NIGHT Hands hidden behind her back.
INT. KITCHEN - NIGHT John gives Kate an expectant smile.
ESTHER I have a special surprise for you, Mommy.
ESTHER Kate eyes her warily.
ESTHER No idea what to expect.
KATE You do?
ESTHER- I picked this flower just for youl It's Kate's memorial orchid.
ESTHER- Kate gasps.
ESTHER- John is horrified.
ESTHER- Kate reaches for the flower.
KATE Estherl Put that down --l Esther laughs and playfully pulls it away.
KATE Kate grabs her by the wrist and Esther suddenly drops the flower, SHRIEKING in pain.
ESTHER- You're,hurting me!
ESTHER- 's eaction.
ESTHER- Esther runs from the room,-cr her wri wrist- e ying, and startled clutching Esther
JOHN What the hell did you do to her?
KATE I just grabbed her arm!
KATE aohn hurries after Esther.
KATE Kate hangs back, picks the orchid-up" from off the floor.
KATE it's ruined.
INT. FAMILY ROOM - NIGHT Esther sits.
INT. FAMILY ROOM - NIGHT on the nofa, still crying.
INT. FAMILY ROOM - NIGHT john comforts.
INT. FAMILY ROOM - NIGHT her.
INT. FAMILY ROOM - NIGHT Kate looks in on them.
INT. FAMILY ROOM - NIGHT John shoots her an angry look.
Darkness.
Esther slips inside, closes the door, turns on a light.
Goes to the workbench.
There's a VICE bolted to it.
She finds some rags and wraps them around her wrist where Rate grabbed her.
Then she places her wrist in the vice, puts the handle of a SCREWDRIVER between her teeth, and bites down on it.
She takes a couple of deep breaths and sta s clo in the yicg of her are.
Grimacing in agonyy screwdriver clan ed between her teeth against the pain, she twists the vice tighter and tighter..
INT. KITCHEN - NIGHT Rate sits at the table.
INT. KITCHEN - NIGHT John has calmed down, but is still angry.
KATE She knew what it meant to me.
KATE She did it on purpose.,
JOHN It wasn't even her idea.
JOHN I'm the one who told her she should try to do something nice for you.
JOHN He leaves.
It's late, The room is dark.Esther plaintively calls out:
ESTHER Daddy!
ESTHER Daddy!
The door opens.
John,.blearily -enters in his pajamas.
JOHN what in it, sweetheart?
ESTHER My arm huits .'
Okay.
Let me see.
He turns on a bedside lamp and sits on the bed.
She pulls up.hex` sleeve, cringing.
Heir wrist is mottled with HORRIFIC B I
A camera flash POPS.
Esther is in a hospital gown (still wearing her black ribbons) while a SOCIAL WORKER photographs the bruises.
Rate and John sit across from a harried ER DOCTOR.
An x-ray of Esther's arm is clipped to a light box.
ER DOCTOR It's a hairline fracture in her radius.
KATE I swear, I barely touched her.
You'll need to talk to the social - worker about that.
She's going to come in here- and ask you some questions.
JOHN But.it was just an.accident.
ER DOCTOR It's routine.
ER DOCTOR We're required by law to file.
ER DOCTOR a report.
ER DOCTOR Child Protective Services will be in touch to schedule a follow-up visit at your home.
ER DOCTOR Kate is shocked.
ER DOCTOR John shoots her a dirty look.
Home from the hospital.
It's very late.
The kids are wearing coats over their pajamas..
Esther's arm is in a fiberglass cast.
John is carrying Max, who has fallen asleep..
As they start upstairs, Kate reaches out to John.
He hangs back.
Daniel and Esther go to their rooms.
When they're gone:
KATE You know I would never hurt any of the-.
KATE kids on purpose.
JOHN I know.
JOHN It's not what you do on purpose that scares me.
JOHN Kate watches him go.
JOHN ..Be turns away and takes Max upstairs.
Kate site curled up on the window seat by the planter, holding the wilting orchid and sobbing inconsolably, old wounds re-opened...
Dark.
John is asleep, alone in the bed.
The door is ajar.
Esther appears in the.doorway.
She peers in, watching him sleep.
After a beat, she gathers her courage and quietly enters, tiptoeing toward the bed.
She pulls back the covers and.climba in next to him.
John doesn't stir.
Esther curls up beside him.
It's raining.
Rate sits in the parked van.
No sound except RAINDROPS TAPPING the roof.
She's looking out at something.
It's the LIQUOR STORE she drove by earlier.
She's-parked in front of it, staring at it through-the rain-streaked windshield...
Kate puts TWO BOTTLES OF WINE on the counter.
The CASHIER rings them up.
She's anxious, guilty, already hating herself.
KATE We're having guests over for dinner.
KATE The Cashier nods.
KATE Like be gives a shit.
KATE Kate lowers her eyes.-
INT. KITCHEN - DAY The two wine bottles sit on the kitchen counter.
INT. KITCHEN - DAY One bottle is.
INT. KITCHEN - DAY open, a GLASS already poured.
INT. KITCHEN - DAY But Kate's not drinking it.
INT. KITCHEN - DAY She's just standing these, arms folded, looking at it.
INT. KITCHEN - DAY The house is.
INT. KITCHEN - DAY quiet.
INT. KITCHEN - DAY She's alone here.
INT. KITCHEN - DAY Only her demons to keep her company- A long moment of.
INT. KITCHEN - DAY awful indecision passes,, Kate paralyzed.
INT. KITCHEN - DAY Then she looks up, her gaze moving past the wine glass to the window., Through it, she can see the backyard.
INT. KITCHEN - DAY It's the swimming pool that holds her eyes, its cold-surface rippling in the rain.
INT. KITCHEN - DAY But- she's seeing something else there, something awful.
INT. KITCHEN - DAY Impossible to know-
what she's thinking, but whatever it Is, it moves her to action:
She, abruptly grabs the glass and quickly empties it in the sink before she-can change hex mind.
-Then she grabs the.
open wine' bottle and pours it all down the drain.
She runs the water and scrubs the sink with her fingertips, removing every trace.
Tosses the empty bottle in the trash and ties up the garbage bag.
EXT. COLEMAN RESIDENCE - DAY Kate hurries out in the rain and stuffs the kitchen trash in the garbage can, burying it under-another bag.
Kate re-enters, dripping wet.
There's still the other wine bottle.
The unopened one.
She 1}esitates.
Rate's.in the walk-in closet.
She hides' the wine bottle in a cubby in her shoe rack and turns out the light.
Driving the kids to school.
Kate looks drawn and weak.
Daniel and Max stare off into space.
Esther holds a stack of her paintings in her lap, obliviously prattling:
ESTHER I can't wait for show-and-tell.
ESTHER I hope Mrs. Grosse.
ESTHER likes my paintings.
ESTHER I did one especially for her..
ESTHER .Nobody responds.
ESTHER Kate's blocking her out.
ESTHER Esther doesn't mind.
Kate drives up the hill and pulls to the curb.
Daniel gets out, but'Esther struggles, her wrist cast making her clumsy, and she awkwardly fumbles her paintings..
They land in the gutter and start-blowing away.
She gives Kate a horrible,-pleading-look
ESTHER Moumiy!
ESTHER My paintings!
ESTHER Kate eyes her accusingly.
KATE You dropped them on purpose.
ESTHER No, I didn't!
ESTHER I swear!.
ESTHER - Kate doesn't believe it for a second, but sees a CROSSING GUARD and a FEW KIDS hurrying to grab the paintings as they're carried off by the wind.
ESTHER Kate shoots Esther a dirty look, then sets the parking brake with an exasperated sigh and gets out to help...
acti But, the second-Rate is out of the van, Esther springs tut like a snake that's been poised to strike.
sh ci? 1/2  put s s then gear shit in'neutral andggrabs the parki ng her .an alarmed look.
Esther smiles at her...
releases t braka.
Daniel sees Esther jump out of the van, just ag it starts 1 roll ._ ba hil
Frazzled, Kate turns to.
Daniel..
He points.
to the van.
she hurries after it, but it's already.inoving too fast, picking up speed, rolling into oncoming e goes into a panic- fueled 'run,.
sure erupting into ic., Kat
Drivers w van a of s Parked a ars eSHEERING gerssi door.
c d Max is trapped in her car seat, helpless, eyes wide in mute terror,.as the minivan clears the parked cars, head ed for the intersection at the bottom of the hill..
Kate chases it, powsrlen s to do anything but watch.-
The minivan cams into the intersection.
Tires S a?? horns cars yrgave , and s = hal .
T T3 sh - b all and 0MV into a streetlight on the opposa.t e corns .
Kate frantically dashes across the street, hysterical with fear, and throws open the back door.
Max is crying and terrified, but safe.
Kate 'scoops Max into her arms, clutching her to her chest.
It's okay, baby.
It's okay, you're all right.
Mo_irimy' s got you...
A crowd has out front; horrified,.
watching breathlesslyguntilehe sees pull ui? 1/2  Max lsafe y i? 1/2  the van.' A wave of relief washes over him.
Then he whirls angrily, looking for Esther.
Be blithely headed to class, paintings hertarmj,gas if nothing ha pened.
ESTHER Bl.
Rate sits across from John and Dr. Browning.The mood fa grim:
KATE I set the brake.
KATE Bven if I hadn'tr the police said it wouldn't have.:rolled unless it was put in neutral.
DR. BROWNING. But Max says she didn't see Esther do anything wrong.
DR. BROWNING. Max is cover.ng for her.
DR. BROWNING. And X don't think it's the first time.
DR. BROWNING It also-wouldn't be the first time that you've tried to blame Esther for.
DR. BROWNING something that was really your fault.
This.
isn-'t all in my head.
Sister Abigail was right.
There is something wrong with Esther.
And I don't care anymore if I can't prove it.
I'want her out of this house.
John and Dr. Browning exchange a dark look.
So you're at a place where you would actually let somebody take her away?
KATE I'll do whatever I have to,do to protect my children.
JOHN 56 will 1.
JOHN That's why she's here.
JOHN something in his voice makes Kate apprehensive.
JOHN An uneasy beat.
DR. BROWNING I have an opening held for you at a residential rehabilitation clinic about forty-five miles from here.
DR. BROWNING They specialize in extended treatment for women who are relapsed alcoholics.
DR. BROWNING Kate is stunned silent.
DR. BROWNING She gapes at.
DR. BROWNING them.
DR. BROWNING with a mix of anger and fear, unable to stop' a flash of guilt.
DR. BROWNING How much do they know...?.
KATE . What are you talking.about?
I'll stand by you through this for as long as it takes.
My mom'a already agreed., to 'help look after the - kids .
RATS Tell her not to bother.
RATS I'd like you to leave now.
JOHN Kate, don't.
JOHN John stands and takes something from inside the sideboard.
JOHN Ile : sets it on the coffee table between them...
JOHN qtr, s the wine bottl g she hid " he closet.
JOHN Kate is stricken.
JOHN She looks at it like it was a poisonous spider.
JOHN The girls found it while they were playing in your.
JOHN closet.
KATE The girls?" You mean Esther found it.
JOHN Yes, Esther found it.
JOHN Does that make a difference?
JOHN Is she lying?
JOHN A beat.
JOHN Kate's silence-is answer enough.
KATE I didn't...
KATE I bought two bottles.
KATE I poured the other one down-the sink.
JOHN But not this onie.
JOHN Again, no answer necessary..
JOHN Kate looks defeated, tears welling.
KATE I'm not going to rehab.
I'm not going to leave you-alone with the kids again until you do.
- .
KATE I haven't had a drink in almost a year.
KATE John sighs, frustrated.- Dr. Browning intervenes, her voice infuriatingly even.
KATE and calm.'
Relapse is very common in early sobriety.
We can help you.
But not until you drop the charade.
KATE It's not a charade.
KATE I wanted to- drink i t.
KATE You have no fucking idea how.badly I wanted to drink it.
KATE But I didn't.
KATE I know 1 should have told you..
KATE I was just afraid of what you'd do.
JOHN I wanted you to come to me.
JOHN That's why ,I didn't confront you with it last night.
JOHN If Max had gotten hurt this morning, it.
JOHN would've been because I trusted you tell me if there was a problem.
RATE What happened this morning had nothing to do with this!
JOHN l f ow do you expect me to believe that?
KATE Max and Daniel are the only reason I'm still sober.
KATE I would never do anything that would hurt them.
DR. BROWNING You don't think this behavior effects them?
KATE You know damn.well what I'm talking about.
KATE _ Her voice is brittle now, barely controlled.
KATE A beat.
KATE The tears sta rt to spill.
KATE When I look out at the pool and think...
KATE When I try to imagine what would have happened if you hadn't come home early that day...
KATE it makes me want to kill myself.
KATE I would the before I let something like that happen again.
JOHN Then why-not throw both bottles away?
KATE- Becauso"I need help.
KATE- i thought I could handle it myself, but I can't.
KATE- I'll go back to-therapy.
KATE- I'll start going to A.A.
KATE- meetings.
JOHN That's not enough anymore.' I told you last time what I'd do if this'ever happened again.
JOHN I'm trying to give you another chance.
KATE - You haven't heard.a word I've said.
JOHN I've heard enough.
JOHN If it was just the two of us, that would be one thing.
JOHN But I can't let you be in a position where you could hurt the kids.
KATE I'm not the one you need to be worried aboutt Seven people close to Esther have died in the past year.
KATE Max was almost the eighth.
KATE now many more coincidences are you willing to ignore?
JOHN Kate, stop it.
JOHN You're talking about an eight-year-old girl.
JOHN And right now she's making a lot more sense than you are.
KATE I know I haven't given you any reason to believe me.
KATE But you have to.
KATE I'm begging you.
JOHN I'm sorry.
JOHN Maybe if you'd been honest with me from the start.
JOHN But not now.
peer around the corner, watching them argue.
Max is crying.
JOHN You either check into rehab this week or I leave and I take the kids with me.
Esther leans close and whispers into Max's hearing aid:
ESTHER I'll kill her it you tell..
Max gives her a frightened look.- Just then, Doris.appears with a bowl of popcorn.
She quickly ehoos the girls away.
DORIS Come on, you two.
DORIS Let's go watch TV.
DORIS Max wipes her eyes.
DORIS Esther takes her hand and leads her away.
John walks Doris out to her car.-He gives her a hug.
JOHN - You sure you don't mind?
JOHN - She's not going to appreciate your being around.
DORIS .I don't care what she appreciates.
DORIS You can't leave those kids alone with her while you're at work all day.
DORIS You're doing the right thing.
DORIS Don't let her change your mind.
JOHN I'll see you tomorrow.
JOHN Doris gets In her car.
JOHN John looks conflicted.
INT. UPSTAIRS HALLWAY - NIGHT Bedtime.
INT. UPSTAIRS HALLWAY - NIGHT Esther can be heard HUMMING through the closed bathroom door.
INT. UPSTAIRS HALLWAY - NIGHT Daniel listens as he sneaks down the hall in his pajamas...
Max's eyes are red from crying.
She's drawing a picture, but hides it under some other papers when Daniel enters.
Be closes the door.
Esther's HUMMING can be heard O.S. A tense beat.
DANIEL Are you okay?' Max nods.
DANIEL Daniel sits down next to her.
DANIEL He lowers his voice.
DANIEL Did Esther do something to the van?
DANIEL Max turns away and shakes her bead.
DANIEL It's okay.
DANIEL You can tell no.
DANIEL I saw her jump out before .it started to roll.
DANIEL Max gives him a startled look, suddenly frightened.
DANIEL No way.
DANIEL Dad won't believe me.
DANIEL You have to do it with me.
DANIEL Max shakes her head and starts signing, but Daniel can't keep up.
DANIEL Slow down, 'I don't understand.
DANIEL Did she make the van crash?
DANIEL A long beat.
DANIEL Max reluctantly nods'.
DANIEL Then we have to tell Mom and Dad.
DANIEL Max starts crying.
DANIEL She signs, but Daniel doesn't understand.
DANIEL Frustrated, Max starts hitting him.
DANIEL Daniel grabs her arms
DANIEL -Stop it!- She's going to kill us if we don't tell!
DANIEL Morn and Dad can protect us!
DANIEL Max.
DANIEL shakes her head.
DANIEL Daniel releases her.
DANIEL Why not?
Daniel stops short.
Max hesitates, then gets up and shows him the pictures that she hid from him when he first came in.
They're crude crayon drawings of Max and Esther.
In the first, Esther stands atop the rocket ship slide and pushes Brenda down the stairs while Max watches..
The= next one turns Daniel's blood cold.
X &'s of Sister Abigail's murder.
Esther stands over Sister Abigail with a bloody hammer wh e r e Max cowers under the bridge.
The last one is of Esther and Max in the treehouse.
Esther is covered in blood.
DANIEL What did she do in the treehouse?
Suddenly, Esther's O.S."
humming STOPS.
Daniel looks up, alarmed.
DANIEL r She's coming.
'Max quickly hides the.
pictures-.
Daniel scrambles to the door, but -pauses and signs to Max as best he can.
DANIEL Everything's going to be all right.
Daniel hurries back to his room and closes the door, just as Esther emerges from the bathroom.
She pauses, suspicious.
INT.
KATE AND JOHN'S BEDROOM -r NIGHT Kate and John are in bed.
It's 3:23 a.m.' They both appear to be sleeping.
Then Kate.
moves.
She's still wide awake.
She looks over at John, slowly push the covers back, and inches out of bed so that he doesn't wake u es' p.
She quietly dresses.
INT tIPSTAIRS HALLWAY - NIGHT Kate emerges from their bedroom with a small OVERNIGHT BAG and cree ps into the dark hallway, careful not to make any noise.
She stops by the.
door of Max's bedroom, and slowly opens it.
Kate slips inside, closes the door; and starts toward Max's bed...- Suddenly, a desk light comes on.
It's Bather.
She's been sitting there in the dark.
The light casts strange shadows on her face.
Going somewhere, Kate?
Kate startles and whirls to check on Max.
She's.
fast asleep.
ESTHER She's fine.
ESTHER Lot's not wake her.
KATE What are you doing in here?
ESTHER 1-couldn't sleep.
ESTHER I was-afraid you might try to take Daniel and Max away.
ESTHER Kate stands frozen, frustrated and'angry.
KATE Go to your room.
Honestly, we're past that now, aren't we?.
t KATE I'um not going to let you hurt my children.
ESTHER 1m not the one who passedouutt drunk.
ESTHER and let I hear the first step is (on.ffideannttially) -admitting that.
ESTHER you have a problem.
KATE Who told you about that.
KATE - Esther holds up Kate's journal:: Kate blanches.
ESTHER It's in your journal.
ESTHER I found i? 1/2 it a few weeks ago..
ESTHER It's very intimate.
ESTHER 3 learned so much about you.
ESTHER Your marital troubles, your drinking problem.
ESTHER Where you hide your wine bottles.
ESTHER You have lovely handwriting, by the way.
ESTHER Would you like to bear my favorite part?
Esther has a page marked.
She reads:
ESTHER "Eight weeks before my due date, Jessica died-from several undiagnosed birth defects.
ESTHER I hadn't felt her move for days, but now that I knew she was dead, I started-to feel her kick again.
ESTHER It's called phantom fetal movement, like the pain felt in a missing limb.
ESTHER I was an amputee and my baby was the lost part of me.
ESTHER Because of other complications, Doctor Kosgrove didn't want to induce.
ESTHER So I had to wait to go into labor.
ESTHER For sixteen days I carried Jessica's body and felt her ghostnow a kicking in my-belly.
ESTHER y womb coffin and inside me slept a corpse."
ESTHER How perfectly hideous.
ESTHER No wonder you turned into a nasty, smelly drunk.
ESTHER Kate is dumbfounded, trembling with impotent rage and raw emotion.
ESTHER Kate.
ESTHER You don't know how lucky you are, I'll never have children of my own.
ESTHER My father paw to that while I was still-in diapers.
ESTHER I.
ESTHER actually don't"remember a 7 time when he wasn't fucking.me.
I don't want your pity.' He did it to make me strong.
So 1 ,wouldn't turn out weak and 'pathetic like you..
RATE I'mi pot weak..
ESTHER Please.
ESTHER You're soft.
ESTHER Like,& worm.
ESTHER Losing your baby could have.
ESTHER made you stronger.
ESTHER But for you it's alwa s.more therapy and more- pills and more booze.
ESTHER Anything so that you don.'t have to actually face the so state of your miserable existence.
ESTHER And why should you?
ESTHER You've got John to carry your dead weight around..
ESTHER But you know something?
ESTHER You don't deserve him.
ESTHER And sooner 'or later, he's going to figure that out.
ESTHER Esther stands up to leave.
ESTHER Kate-blocks her path.
ESTHER What are you going to do?
ESTHER Hit me?
ESTHER -Kate.
ESTHER looks really tempted.
ESTHER A beat.
ESTHER She puts out her hand for the journal.
ESTHER Esther gives it to her with a smile.
ESTHER Kate steps aside.
ESTHER See you tomorrow.
ESTHER She leaves.
ESTHER Kate glares after her.
INT. KATE AND JOHN'S BEDROOM - DAY .Kate is on the phone, angry, trying to keep her voice low,
KATE I need to know where she came from and I need to know now.
INT. HOME FOR GIRLS - OFFICE - DAY Sister Judith talks.
INT. HOME FOR GIRLS - OFFICE - DAY to Rate on -the phone, looking harried.
I'm sorry, we've called every orphanage in Moscow trying to find out.
KATE We adopted her from yquI How can you not know anything about her?!-
SISTER JUDITH The Wallaces could have adopted her illegally.
SISTER JUDITH Are you-sure remember anything that could he doesn't?
KATE - I'll call you back.
KATE - She curtly hangs up-
INT. FAMILY ROOM - DAY Doris plays a game with the kids.
INT. FAMILY ROOM - DAY Esther feigns' nonchalance, but.
INT. FAMILY ROOM - DAY the tension is thick between Dani?l and Max.
INT. FAMILY ROOM - DAY Doris is oblivious.
DORIS I say Professor Plum did it in the Conservatory with the candlestick...
INT. ESTHER'S BEDROOM - DAY Kate rifles.
INT. ESTHER'S BEDROOM - DAY through Esther 'a things.
INT. ESTHER'S BEDROOM - DAY She finds the life book that e fli it.The p i till blank exce forstherfaamily photos that fate put ingforahers Then she notices that the first page has been torn out.
INT. ESTHER'S BEDROOM - DAY And on the page.
INT. ESTHER'S BEDROOM - DAY captioned '"ESTBER JOINS THE FAMILY," P.sther's face has been et cu oval cut out Df "h farm of r Creepy.
INT. ESTHER'S BEDROOM - DAY Kate ransacks the room,.
INT. ESTHER'S BEDROOM - DAY searching for something,, anything.
INT. ESTHER'S BEDROOM - DAY Then she notices a.stuffed doll that she just knocked over.
INT. ESTHER'S BEDROOM - DAY Its dress has been flipped up, revealing ,g slit, cut in he doll's pack.
INT. ESTHER'S BEDROOM - DAY grabs it.
INT. ESTHER'S BEDROOM - DAY Something has been hidden in the stuffing...
INT. ESTHER'S BEDROOM - DAY Tt's a 'i? 1/2  Bible.
INT. ESTHER'S BEDROOM - DAY Kate pulls it out and quickly looks through the pictures that-Esther keeps inside.
INT. ESTHER'S BEDROOM - DAY They're the same photos of the Wallaces that we saw earlier.
INT. ESTHER'S BEDROOM - DAY With one new addition.
INT. ESTHER'S BEDROOM - DAY It's the missing page from Esther'.s life book, the picture of Kate and John at their wedding.
INT. ESTHER'S BEDROOM - DAY But the face that Esther cut out, from the other picture has been glued over Kate 'a.face here, p 3t loo like JTobm DDd $ her are egi? 1/2 S markied.
INT. ESTHER'S BEDROOM - DAY The caption is still "MOMMY & DADDY GET MARRIED."
INT. ESTHER'S BEDROOM - DAY Kate shudders.
KATE Jesus Christ...
KATE She flips through the: Bible and shakes it, but there's nothing else.
KATE She notices that the Bible -is in a foreign language.
KATE There's an ink stamp on the inside cover.
KATE it's in the sa me.
KATE language as the Bible.
KATE "See on saarne rnatituat omand."
KATE She focuses on two words: seamne.Inatituut.
Daniel gets up from the.game.
DORIS Where are you going?
DANIEL Bathroom.
DANIEL Esther eyes him as he leaves.
Daniel hurriedly sneaks toward John's den, but stops just outside.
Be hears a keyboard CLACKING and warily peers around the.
corner.
Kate ia'working on John's computer.
Daniel eyes the KEEPSAKE BOX.
.No way to get to it unseen.
Be thinks a beat, then slips away...
Kate googles "SAARNE INSTITUUT."
All the sites that come tap are in the same language as Esther's Bible.
She sighs, frustrated.
Then she sees something -- a photo of a Gothic mansion.
The sign out front reads: "Saarne Instituut."
Kate recognizes it - instantly.
It's the same Gothic mansion from Bather's paintings.
She scours the web site for anything' decipherable.
There's a - link: "KONTAKT JA XNFO."
She clicks it.
There's a phone number.
Daniel looks around, finds what he's looking for: a TIRE IRON.
INT. JOHN'S DEN - DAY Kate is on the phone, anxiously 'listening to the TONE of a foreign
telephone ringing.- Then:
Saarne Instituat.
Xas ins -eaan teid
KATE Uh, hello.- I'm sorry, do you speak English?
RECEPTIONIST #1 (V.0.) Ruidas, palun7
KATE Do you speak.English?
KATE Does anybody there speak-English?
KATE This is very- important.
RECEPTIONIST #1 (V.0.) Ma ei sac aru.
RECEPTIONIST #1 (V.0.) Dote Like silmapilk.
RECEPTIONIST #1 (V.0.) Kate starts to-say somethf.ng, but she's interrupted by HOLD MUSIC.
I)aAje runs lookslaround.
o The coast is clear.
Hetstartsi? 1/2 climbing...
INT. JOHN'S DEN - DAY Kate is still .on -hold.
INT. JOHN'S DEN - DAY , Finally-, a MAX' picks up.
INT. JOHN'S DEN - DAY Be speaks English with the same ACCENT as Esther.
INT. JOHN'S DEN - DAY RECEPTIONIST #2 (V.a.)
INT. JOHN'S DEN - DAY Hello?
KATE Is this the Saarne Institute?
RECEPTIONIST #2 (V.O.) yes.
KATE I need to talk to someone about one of your children.
KATE She was adopted by.an American family about a year ago.
I beg your pardon?
KATE A little girl, possibly adopted from your orphanage.
KATE I'm trying to find somebody who might remember her.
RECEPTIONIST #2 (V.O.) This girl, she is -not come from here.
KATE Can't you at least check?
No, I am sorry.
KATE Please, I know she at least spent some time there.'
RECEPTIONIST #2 (V.O.) No, 'ou not understand.
RECEPTIONIST #2 (V.O.) Saarne Institute is not orphanage.
RECEPTIONIST #2 (V.O.) It is mental hospital.
Off Rate's shocked reaction:
CRAAAACK!
Daniel uses the tire iron'to pry the hasp off the treehouse door.
The wood SPLINTERS and the hasp comes free.
He enters and looks'around.
Nothing unusual.
He throws back the rug and pulls up the loose plank.
Max's "Hello Kitt l" backpack is stuffed inside.
He unzips it, his, eyes going wide with ho or...
r r he pulls Bsther' blood-stained d ess fro t L e i? 1/2 c ck.
I couldn't have,done it by myself, you - know.
Daniel whirls around.
'CAMERA REVEALS Esther standing in the doorway behind him.- She's holding something behind her back.
ESTHER - Max is just ag-guilty as I am.
ESTHER - She steps toward him'and he backs..away, angered by her words, but wary of those hands-behind her back.
ESTHER - What's she biding...7
DANIEL You leave her alone.
ESTHER Think about it.
ESTHER Somebody had to have helped me.
ESTHER If they find that dress, they won't just be coming for me.
ESTHER They'll becoming for Max, too..
ESTHER Is that really what you want?
ESTHER She's maneuvering him away from the door.
ESTHER Daniel screws up-his courage and stands his ground.
You're full of shit.
I'm telling Mom what you did and you're gonna fry for it.
All right.
I was just trying to be.
nice.
And with that: she takes a can CHARCOAL, LIGHTER FLUID from behind her back and tazts snravina the-floor At Daniel's feet with Al.
He gasps' and jumps back as it SPLATTERS in.
front of hire.
She douses the floor from one side to the other.
Then she opens a BOOK OF MATCHES and lights one.
Daniel blanches,
ESTHER Goodbye, Daniel.
She drops the match.
- The lighter fluid IGNITES 'and a wall between Daniel the door, Esther smiles at him through fire the ER Tgl,pp3ES trapped.
Kate talks on the phone.
She's e-mailing a picture of Esther.
KATE It's called the Saarne Institute.
KATE S-A -
A-R-N-E.
it's in Estonia:
INT. HOME FOR GIRLS - OFFICE - DAY Sister Judith jots down the info..
SISTER JUDITH Estonia?
SISTER JUDITH This can't be right.
SISTER JUDITH All he r paperwork is from Russia.
KATE Please, just try to find out if sh e was ever a patient there.
KATE I'm sending them a-picture of her right now.
INT./EXT. TREEHOUSE - DAY SMOKE pours from the treehouse.
INT./EXT. TREEHOUSE - DAY Esther has climbed down and is watching it burn .
INT./EXT. TREEHOUSE - DAY Inside, Daniel is surrounded by FLAM ES, choking on black smoke.
INT./EXT. TREEHOUSE - DAY He stumbles to a window and sticks his head out.
The fire closes in.
The place is going up like a tinderbox.
He carefully climbs out the window and stands- on the sill, fifteen feet off the ground.
He hugs the side of the treehouse, panicked.
The FLAMES grow higher, licking at his feet.
No place to go now but up.
He reaches for the edge of the roof and struggles to pull himself onto it, his legs kicking out over empty space.
He gets an elbow on the sloped roof and starts wriggling up onto it...
.suddenly -- he sue.
He glide dawn, arel grabbing the q2 9 t h e with his fin e s aJ the last seco Esther gasps, excited, like she's the front row of a great sports event.
Kate's still on the phone.
She glances out window backyard and the woods beyond.
Suddenly, her eyes wide.
theA COLOMN OF SMOKE rises above the treeetop s.
Realization- and horror slam home at the same time.
t.
Daniel fights desperately to hang on.
Bother watches, eyes wide with exhilaration.
For alone, breathless beat i? 1/2 i? 1/2 ajustt.i? 1/2 gs a there, dangling helplessly, fingers slipping y.
hen hg loses ,dg l b ur[-gts to ou d.
He lands hard and doesn't move.
Esther walks over and crouches next to him.
She touches his neck for a pulse.
He's still alive.
Esther pouts, disappointed.
She- looks around, finds a HEA VY ROCK.
She lifts it over her head, ready to cave.
in Daniel's skull...
Sudde l Y, Max rus e innc3 ushe gsai? 1/2 a?? knck from her hands.
Esther whirls on Max, eye s flashing i rage.
g But then Kate is there, running up the path with Doris not far behind.
Kate sees Daniel's rumppledabodyta and his her world collapses, everything else falling away.
KATE Oh, my God!
KATE Daniell Baby, can you hear me?
KATE Please, baby!
KATE Wake up.
KATE He doesn't move.
KATE Kate calls out to Doris:.
KATE Call nine-one--onel Doris hurries back to the house.
KATE Kate catches Esther watching her warily..
KATE Kate glares at her with pure hate.
FIREFIGIITERS have arrived to put out the treehouse.
NEIGHBORS gather to gawk.
Max is in the house, watching from the window as EMTS load Daniel into an ambulance.
He's still unconscious an d in full cervical immobilization.
Doris bowers nervously.- gby Kthe atewrist.
climbs in with Daniel, angrily dragging Esther
KATE Get in here.
DORIS She can ride with us.
KATE I'm not letting her out of my sight..
INT. HOSPITAL - WAITING ROOM - NIGHT Hours later.
INT. HOSPITAL - WAITING ROOM - NIGHT The-whole-family-waiting fpr-news Kate and John sit across from one another; The silence and tension heavy between its with irls- DOC WAN)
en ers.
Kate a drthesothers are inst ntly on eir feet:
Me stopped.-the abdominal bleeding.
- Ue1B should consider b yourselves ery lucky
Relief 'floods over .Kate and John.
Esther listens, intent...
JOHN Can we see him?
DR. RAJAN In a little while.
DR. RAJAN He 'a resting in
KATE Will he be able to tell us what happened?
KATE A pointed glance-between Kate and John.
KATE Dr. Rajan doesn't notice.
DR. RAJAN It's possible.
DR. RAJAN There's no way of - knowing for sure what he'll remember until he wakes up.
DR. RAJAN Esther shifts nervously.
DR. RAJAN Not the answer she was hoping for...
Rate has taken John aside, voices low, out of earshot of the .others.
She's shown him two pieces of paper: One is'a pa inting Esther did of the old Gothic mansion..
The other in a printout of the photo from the-Saarne Institute's web site.
She-told me she just made it up, but it's.a real place.
JOHN There has to be some other explanation.
JOHN She didn't come from an insane asylum!
KATE How do we know?
KATE The orphanage we thought she came from has never even' heard of her[- Everything.
KATE about her could be a lie!
JOHN - We have her passport, her birth certificate, her school and medical- .
JOHN - records --
KATE It's just paper, JohnI From halfway around the world!-- This isn't last me being paranoid.
KATE Call.
KATE Saint Cabrini's yourself.
KATE if 'you don't believe me.
KATE A beat.
KATE John looks like he's wavering.
RATE Your own mother was there this time.
RATE Only Esther or Daniel could have started that fire.
RATE I know who I think did It.
RATE Do you?
JOHN I don't know what to think anymore.
KATE Well, I'm done connecting the dots for you.
KATE You can believe what you want about me.
KATE Blame me for everything.
KATE I'll leave tonight if you want me to, on one condition.
Esther goes, too.
Esther watches Kate and John.
She can't hear what'they're saying.
She looks worried.
She turns to Doris.
ESTHER Can I have a dollar for the pop machine?
ESTHER Doris gives her a dollar.from her'purse.
ESTHER Esther smiles and heads toward the vending machines..
ESTHER Max watches her go.
ESTHER But as soon as Esther's out of sight, her cheery face turns to graiii.te.
ESTHER She puts the dollar in her pocket and sneaks away...
INT. FOYER - NIGHT Back at home, the phone RINGS.
INT. FOYER - NIGHT The answering machine picks up.
MAN with an Estonian accent (DR.
VARAVA) leaves a message:
I'm.calling for Katherine Coleman.
- This is Doctor V.rava from the Saarne Institute in Tallinn.
Please- cill me immediately;..
Esther peers through a door.and sees Daniel lying unconscious with a rigid A traction, both his arms by wires heart rate monitor BEEPS Esther approaches his bed like the angel of deaths slowly drawing the CURTAIN around them.
The HEART RATE MONITOR Is clipped to his finger.
Esther slips .it onto her own finger.
The machine continues to BEEP, registering her heartbeat instead of his.
Slowly, she climbs up onto the bed, prowling like,a cat.
She carefully straddles him and takes a pillow from under his head.
The movement causes him to stir.
His eyelids flutter.
At the last moment, he sees her looming, over him...
Then s 'ash s the ' ii? 1/2  1 down ova hin face.
he al Daniel struggles,.
but he can barely move, traction wires JANGLING as he thrashes helplessly.
His SCREAMS are muffled under the pillow.
Esther viciously presses down with all her strength...
INT. HOSPITAL - WAITING ROOM - NIGHT Max sits next to Doris, staring at.
INT. HOSPITAL - WAITING ROOM - NIGHT the hallway that leads tor-the .vending area, waiting She get s s p.
INT. HOSPITAL - WAITING ROOM - NIGHT walk toward iit, re d aounting.i? 1/2 looks worried.
INT. HOSPITAL - WAITING ROOM - NIGHT t u and s d a Maxine, where are you going?
INT. HOSPITAL - WAITING ROOM - NIGHT Max turns the corner.
INT. HOSPITAL - WAITING ROOM - NIGHT The vending area is empty.
INT. HOSPITAL - WAITING ROOM - NIGHT Esther isn.'t there.
INT. HOSPITAL - WAITING ROOM - NIGHT Max's eyes go wide with fear.
Daniel has stopped struggling.
When Esther finally lifts the , pillow, his eyes are them a and slid s the pillow d u is headr gently closes e nderneath h Then she climbs down from the bed and slips the heart rate monitor back on his finger.
FLATLINE.
An ALARM sounds.
Max runs up to Kate and John.
She urgently yanks Kate's arm.
KATE What-is it, sweetie?
Suddenly, a CALL comes on the overhead speakers:
Code ninety-nine, ICU.
Code ninety- nine, ICU.
.Dr.
Rajan runs by at top speed.
Kate gasps, panicked.
RATE Oh, My.
RATE God...
RATE Daniell She and John run after Dr. Rajan.
RATE Doris quickly grabs Max to keep her from following.
RATE INT.
RATE HOSPITAL -.
RATE lCD - NIGHT Kate and John follow Dr. Rajan.to the room where a CODE TEAM races to resuscitate Daniel.
KATE Dan.iL-I!
KATE Kate and John try to enter the room, but the ICU NURSE stops them.
KATE What's happening --?1
You have to stay out here.
_ They catch a glimpse of Dr. Rajan picking up defibrillator paddles before the door is SLANHEI) in their terrified faces.
INT.
HOSPITAL - ICU - NIGHT (TIMECtT)
Rate and John sit outside, waiting.
Dr. Rajan emerges.
His face tells.them everything.
Rate's crying before he even says a word.
DR. RAJAN I'm sorry..
DR. RAJAN His injuries were more severe than we first thought.
DR. RAJAN John chokes back tears.
DR. RAJAN He holds Kate close as she sobs.
KATE Oh, no...
KATE Oh, no...
KATE Oh, my baby...
DR. RAJAN We're so sorry.
DR. RAJAN A terrible loss, we're so sorry...
DR. RAJAN Kate gets up and rushes into Daniel's room in time to see the ICU Nurse cover his body with a sheet.
DR. RAJAN Kate collapses to the floor, weak with horror and grief.
DR. RAJAN John tries to comfort her.
DR. RAJAN Then slowly, Kate's eyes turn steely and her grief burns into rage.
DR. RAJAN She pushes.
DR. RAJAN John away and stands up.
RATE Where is she?
Kate storms in and looks-'around, her-face a mask, of fury.
John hurries after her.
She spots Esther.
returning from ding machines, - innocently sipping a.
e c h t e 'ven
KATE What did you do?!
KATE Heads'turi.
KATE Doris and Max are taken aback.
KATE Kate looks insane.
KATE She strides.toward Esther, gaining momentum with every step, but Esther just looks up at her with a half-hidden smile on her fa ce.
What did"you do to him, you bitch?!.
Them ,he slaps sE ther As ha as she.
cmn h t e face, sending her reeling to it fioot Everyone is-horrified.
JOHN Kate!
JOHN Stop it!
JOHN Rate looks ready to hit her again, but a NURSE holds her back.
Esther touches her mouth.
She's bleeding.
For a beat, she just lies r sr - uina shock he Th o John u and-in g bursts a into tear sen en-shewsees stantly
ESTHER Daddy!
ESTHER Daddy!
ESTHER Help me!
ESTHER John scoops her into his arms; Kate is apoplectic.
ESTHER It takes TWO ORDERLIES to hold her.
ESTHER Max watches, crying.
KATE She killed him!
KATE He was going to live and she killed him!1
JOHN She was out here the whole time!
JOHN Dr. Rajan rushes in, readying a syringe.
KATE No!
KATE Get away from me l i!
DR. RAJAH Hold her still!
DR. RAJAH A small crowd has gathered, watching with horror and pity as the Orderlies overpower her.
DR. RAJAH Dr. Rajan-grabs Kate's arm, quickly hunts for a vein, then jabs the needle-in.
DR. RAJAH Kate screams.
Pleaeet Somebody listen to me!
She killed.
my.
babyI She killed my baby...
But her eyelids are already.
drooping .
John watches, nearly overwhelmed with emotion.
Kate goes limp in the Orderlies' arms.
INT. HOSPITAL ROOM - NIGHT Kate lies in a bed, barely conscious.
INT. HOSPITAL ROOM - NIGHT A NURSE.
INT. HOSPITAL ROOM - NIGHT pushes -a 'sedative into an IV tube taped to Kate's arm.
INT. HOSPITAL ROOM - NIGHT Rate looks -up 'groggily.
INT. HOSPITAL ROOM - NIGHT and sees John talking to Dr. Rajan.
DR. RAJAH We can keep her sedated overnight.
DR. RAJAH John nods.
DR. RAJAH He waits for Dr. Rajan and the Nurse to leave, then walks over and looks,down at Kate.
DR. RAJAH She's fighting to stay awake.
JOHN Mom's driving us home.
JOHN I think it's better if you stay here tonight.
JOHN I don't want you around the kids like this.
Kate weakly grasps his hand, her voice a thready whisper:
KATE John...
KATE Please...
KATE Please don't let her take my family...
KATE A long, emotional beat.
KATE John hesitates, conflicted.
KATE Then he places her hand back on the bed and turns away.
KATE She tries to call out, but doesn't have the strength.
KATE - She sees the girls waiting in-the hallway.
KATE Max has been crying.
KATE She looks scared.
KATE John leads them all away.
KATE And the last thing Kate sees-before blacking-out again is Esther's devious smile...
LIGHTNING flashes in the distance.
There's a storm coming.
INT. MAX'S BEDROOM - NIGHT John tucks Max into bed.
INT. MAX'S BEDROOM - NIGHT When he leans down to kiss her, we see Esther watching from the doorway.
INT. MAX'S BEDROOM - NIGHT Max eyes her warily...
JOHN What's wrong, sweetheart?
ESTHER She's thinking about Daniel.
ESTHER Aren't you?
Max reluctantly nods.
John gives her a sad look.
JOHN Me, tQO.
JOHN Esther enters and stands next to john at Max's bedside.
Sweet dreams.
- As she kisses max good night, Esther fuitively redches out and grabs Max's HEARING AID from off her.nigbtstand...
l f 7T.
ESTHER'S BEDROOM - NIGHT - Esther stands at her closet, 'looking through-her pretty dresses, leasantly.SUNG to herself.
She holds one up to her chin, looks at herself in the mirror.
Then another.
She chooses a RUFFLY DRESS and lays it out on her bed.
Shersands ov er it with a a pair of-Scissors in her h a nd , e y eing -it app g y.
After -a thoughtful beat, she starts cutting its rufflesoff...
INT. FOYER - NIGHT Esther's HUMMING can be heard O.S. John trudges downstairs,.
INT. FOYER - NIGHT exhausted and emotionally devastated.
INT. FOYER - NIGHT He-goes into the, living room, slumps in a chair, buries his face in his hands, and cries.
INT. FOYER - NIGHT CAMERA PULLS BACK, revealing the unnoticed answering machine in f.g.
INT. FOYER - NIGHT The light on it is BLINKING.
INT. FOYER - NIGHT One new message...
walks down the hall,i? 1/2 ray with her dress draped over h er-army stillHUM MING.
goes into the bathroom and c oses doo
INT. HOSPITAL ROOM - NIGHT Esther's HUMMING continues, no other sound here at'all...
INT. HOSPITAL ROOM - NIGHT Rate comes to, fighting her drug-induced stupor.
INT. HOSPITAL ROOM - NIGHT She forces herself to sit up and gingerly pulls the IV needle out of her arm.
Esther's HUMK NG.continues, still no sound.
Kate stands in rthede.
doorway.
The bed Daniel was lying in is already-empty and as if -he was never here.
RAIN streaks down the window.
]Cate enters and sits down heavily next to the bed.
She touches the place where her son lay dead only bourn before.
She brehks down and sobs inconsolably, but we can't hear it, only the SUMMING of Esther's lighthearted, melodic tune.
INT. FAMILY ROOM - NIGHT Back to NORMAL SOUND.
INT. FAMILY ROOM - NIGHT John sits on the sofa, eyes red anti teary, watching a videotape-of Daniel pla'irig soccer.
INT. FAMILY ROOM - NIGHT There's a NOISE from the kitchen..
INT. FAMILY ROOM - NIGHT Be_pauses the video, listens.
INT. FAMILY ROOM - NIGHT A moment later, $OFT'KUSIC starts vlayin3 Q.S. An old, crackly recording from the forties of The Ink Spots singing "I'M MAKING BELIEVE."
INT. FAMILY ROOM - NIGHT Sentimental, bittersweet, and a little creepy.
INT. FAMILY ROOM - NIGHT Baffled, John goes to the kitchen...
INT. KITCHEN - NIGHT ...
INT. KITCHEN - NIGHT and stops short at what he sees.
INT. KITCHEN - NIGHT Esther stands on a chair, cutting slices of cheese with a LARGE KNIFE.
INT. KITCHEN - NIGHT -She's prepared a plate of fruit, cheese,-and-crackers.
INT. KITCHEN - NIGHT She's wearing the dress we saw her choose, but with some alterations.
INT. KITCHEN - NIGHT The ruffles are gone, so are-the sleeves.
INT. KITCHEN - NIGHT It's low cut and too grown up.
INT. KITCHEN - NIGHT Her hair is perfectly curled and her face is caked with makeup --- powder, red lipstick, thick mascara, dark eyeliner -- giving her a grotesque, woman-child, eight-year-old- beauty-queen look.
INT. KITCHEN - NIGHT JonBenet Ramsey by way of Angelina Jolie.
INT. KITCHEN - NIGHT John is stupefied.
INT. KITCHEN - NIGHT She szailes at him.
INT. KITCHEN - NIGHT Outside, THUNDER RUMBLES.
Hello, darling.
JOHN What are you doing?
Making you a snack.
You skipped your dinner.
JOHN Get down from there.
JOHN That knife's too sharp for you to be playing with.
JOHN Esther climbs down from the chair and nonchalantly carries the cheese and cracker plate to the dining room, as-if he hadn't said anything.
JOHN John follows her, dumbfounded...
There are TWO GLASSES and a bottle of SPARKLING WATER on the dining room table.
Dim lighting and romantic MUSIC.
John is completely nonplussed.
'Esther sets the cheese plate on the table.
JOHN What is this?
I wanted to do something special for you.
I don't like my daddy to be unhappy.
JOHN - But why are you dressed like that?
Don't you like it?
JOAN No, I don't.- You're not supposed to play with Mommy's makeup.
ESTHER I'm sorry, sir.
ESTHER I.just want to be as' pretty for you-as she is.
JOHN You don't need makeup to be pretty.
JOHN Esther is touched.
JOHN She gazes up at.
JOHN him lovingly.
ESTHER You really mean that, don't you?
JOHN of course.
JOHN Why don't you go wash your face and we'll tuck you back into bed.
ESTHER - But-1 worked so hard.
ESTHER - Can't we stay up just a little longer?
ESTHER - She gives him the big, sad eyes.
ESTHER - They're a little disconcerting under all the makeup..
ESTHER - John sighs.'
JOHN -All right.
JOHN We'll have a little snack and then off -to bed.
JOHN Esther beams.
JOHN John sits down, reluctantly humoring her.
JOHN Esther starts pouring sparkling water into the glasses.
ESTHER We really.
ESTHER should be drinking that bottle-of wine, but I couldn't find it.
JOHN Little girls aren't allowed to drink wine.
ESTHER. I'm not so little.
ESTHER. To family..
She raises a glass in toast.: John gives her a sad look, but goes along with it.
They-CLINK their .glasses together and drink.
But.
instead of sitting down,'Esther continues to stand next to 'him.
She picks up a piece of cheese and tries to feed it to him.
John eyes her uneasily'.
'Be takes the cheese from her.and eats it.
JOHN Why don't you sit down?
ESTBER I like being close to you.
ESTBER She gazes into his eyes and.touches his face.
ESTBER John moves her hand away, suddenly very uncomfortable.
ESTBER She hesitates, nervous...
ESTBER then eans saes Qn h.
ESTBER John grabs her arms and abruptly pushes.
ESTBER her away xn-shock and near-panic.
ESTHER What's wrong?
JOHN Don't ever do that again.
I.
thought you loved me.
You said I was pretty.
JOHN Of course, I love you.
JOHN But not...
JOHN it's different than how I love Mommy.
JOHN You're my little girl.
ESTHER Will you stop saying that?
ESTHER We can be together now, don't you see?
ESTHER She can't come-between us anymore.
JOHN Who can't?
JOHN You mean Mommy?
She's not my inormyl Please, sir, I'll do anything for you...
She reaches out to touch his face again, but he grabs her hand.
JOHN Esther, stop it!
JOHN I mean it.
JOHN This is wrong.
ESTHER Am I being bad?
ESTHER - You can spank me.
ESTHER it you-'.d like.
ESTHER I'll let you.
ESTHER I won't, evn cry.
ESTHER Unless you want me to.
John gapes with-disgust and horror,.
He looks like he-might vomit.
JOHN. God ouoin A beat.
JOHN. Esther looks heartbroken.
JOHN. Suddenly, she tries to kiss him again, desperate this time, throwing herself at him, pushes her to the floor.
JOHN. She frantically crawls back to him.
JOHN. Be hurries to the other side of the table.
ESTHER Please!
ESTHER Please!
ESTHER You're ruin.ing it!
Jesus Christ, lust stop talking!
Go upstairs and wipe that shit off your facel Right nowt Esther runs upstairst crying.- John just gapes in utter disma and revulsion.
He runs Into the kitchen and throws up in the sink.
INT. ESTHER'S BEDROOM - NIGHT Esther situ at her little vanity table, looking at her overly made- up face in the mirror, and sobs hysterically...
Kate is still sitting at Daniel's empty.
bed, eyes red and puffy from crying.
Outside, it's RAINING HARDER.
Lightning FLASHES.
Her CELL PHONE CHIMES.
She eyes it wearily, considers not answering.
'After a few RINGS,-she picks up.,
KATE Hello?
is this Katherine Coleman?
KATE Who's calling?
-Doctor Varava is a craggy-faced an in'his 50's.
His manner is urgent, almost desperate.
as he speaks on the phone.
My name is Doctor Varava from the Saarne Institute.
I got your mobile number from Sister Judith.
Kate sits up, suddenly roused.
RATE Did you get the picture I:sent?
RATE Did you recognize her?
Yes, X did.
Where is she now?
Is- she.
with you?
KATE No, she's at home with my husband.
DR. VARAVA Neetudl Call him ut and to get your family of i? 1/2  e ush er call the police.
KATE He won't do it.
KATE He's not going to do anything without some kind of proof.
DR. VARAVA Then tell him that the little girl in that picture isn't a little girl.
DR. VARAVA Kate stops short, confused and suddenly frightened.
KATE . What are you talking about?
KATE . The picture I sent, you was of our adopted daughter.
KATE . She's only eight years old.
-No, she's not.
She has a pituitary disorder that causes proportional dwarfism.
She only Jcz Tike a child.
INT. ESTHER'S BEDROOM -- NIGHT We're intercuttinq now with Esther at her vanity, her crying building to a MANIACAL WAIL, her MAKEUP STREAKING.
INT. ESTHER'S BEDROOM -- NIGHT from her tears.
DR. VARAVA Her real name is Veera Klammer, she escaped from here eighteen months ago and she's thirty-two years old!
DR. VARAVA Esther SCREAMS, slowly scratching her face with her fingernails..
Kate's mind is reeling.
KATE This can't be.
KATE There has to be a mistake.
Does she have the scars?
RATE What scars?
RATE has stopped crying, her sorrow burning into blind, monstrous rage.
RATE She glares at her reflection, her mascara smeared down her cheeks.
We'had to keep het .in a restraint jacket when she was here to stop her .from hurting' our staff, but she was constantly fighting against it until the collar and cuffs began deep into her skin.
She wound up p scars from it.
Around her wrists and neck; Esther black from her wrists and neck, revealing althe ly r scars over sew
RATE Oh, my God...
RATE - ow could this have happened?
She's been passing herself off as a child for most of her life.
'She worked as a prostitute for years, catering to wealthy pedophiles.
ESTHER curls her upper lip, looking at her top teeth.
ESTHER She reaches up, pulls on her teeth and -- RA-CLICK.
ESTHER y come out
DR. VARAVA She even had a dental.appliance'made to complete the illusion by disguising her adult teeth.
DR. VARAVA Re r- gerfect, earl white }aabY Beth e- d8rn at a f, e s t of- CRgmp, Eoia, fTx.
DR. VARAVA DR.
DR. VARAVA VtAVA When she was finally arrested, she continued the pretense to stay out of jail and: was sent to an orphanage.
You're not the first to have been fooled.
She's even-been adopted before.
A family here in Estonia took her in.and lived with her fog over six.
months.
They never suspected.
Kate-hesitatesa'b.eat, almost afraid to ask:
KATE But why was ahe at your hospital?
Veera is dangerously insane..
She was molested by her father and sexualized at a very early age.
When.
he.
took another lover, he told Veera it was because she could heverbe a real woman.
Veera murdered them both.
ESTHER just stares at herself in the mirror.
ESTHER With her scars revealed, her face scratched, her mascara streaked down 'to her chin, and her awful, yellow, snaggletoothed sneer, she looks like a monster.
DR. VARAVA She now sees herself as trapped in the body of a.
DR. VARAVA child and it disgusts her.
DR. VARAVA She wants to.
DR. VARAVA be what her father considered to be a "real woman."
DR. VARAVA She t wants o be a wife, a mother, a lover.
DR. VARAVA She wants to grow up.
DR. VARAVA - Suddenly, -she grabs her chair and SMASHES the mirror with it.
DR. VARAVA Then she whirls and swings the chair into her aquarium with a 'feral scream --= CRASH!
DR. VARAVA Water-and fish flood onto the floor.
DR. VARAVA When she was adopted here in Estonia, = she tried to find love where she had found as a child.
DR. VARAVA With her new lather.
DR. VARAVA When he refused her, she bordered the entire family in, their sleep.
KATE And then she burned the house down...
DR. VARAVA Yes.
DR. VARAVA How did you know?
DR. VARAVA off Kate's horrified look --
John pushes the door open and looks inside.
JOHN Esther?
JOHN Are you-all right?
JOHN She's not here.
JOHN The light is on, but the room is empty.
JOHN Fish are still FLAPPING around on the floor,-mouths.
JOHN gasping.
JOHN John gives the-broken aquarium an unnerved look.
JOHN Esther, where are you?
JOHN No answer.
JOHN He turns off the light, about to look "elsewhere...
JOHN then stops.
JOHN With the overhead light off, the room is lit only by the black light in Either ' s broken aquar i u m, t 7UVALI ma Esther s p a n i tin ha a chap n S 's painted t = that they ook f een vri d er black h - - - John takes a closer look, turning the black light on and o ff.
JOHN Unde gal lights the painting he saw when he first met Esther,- a mother lion and her sleeping cubs.
JOHN .[Inds black Limos the cube are now dead and 'the mother's mouth .s dripping with blood.
JOHN The paintings that looked like typical family portraits in normal light are now nightmarish visions of death and violence.
JOHN In one, Kate's eyes have been gouged out.
JOHN In another, Daniel's throat has been slashed.
JOHN In the picture of the whole family, John- and Esther look normal, but Kate, Daniel, and Max are all decomposed corpses.
JOHN John staggers back in shock.
JOHN The telephone RINGS, startling him.
JOHN The answering machine picks up.
JOHN He hears KATE.'SVOICE,
John?
Are you there?
Kate is on her cell., running to the- car.
KATE - John[ For God's sake, pick up the fucking phone!
INT. ESTHER'S BEDROOM - NIGHT John turns to leave -- suddenly, th r bursts out mom undo her pile "of stuffed animals with ,s, 3ILD SC Sj3g a n he hei? 1/2 sei? 1/2 lf at John If rom the bed, } labs her scissors into his eve.
INT. ESTHER'S BEDROOM - NIGHT John screams and throws herto the floor.
INT. ESTHER'S BEDROOM - NIGHT Be stumbles out of the room, blood streaming down his face.
UPSTAIRS HALLWAY John staggers to the stairs, the handle of the scissors jutting from his eye socket.
UPSTAIRS HALLWAY But just as he hits.
UPSTAIRS HALLWAY the first step, Baer rushes out and pushes tine cMm the etz{rs.
FOYER John-goes flying, head over heels, crashing into the railing hard enough to SPLINTER it, and lands hard at the foot of the stairs.
FOYER Be lies there in a heap, too stunned.
FOYER to move.
FOYER Esther appears at the top of the stairs.
FOYER looking down at him.
FOYER She.
FOYER has a JU} P ROPE
in her hands and starts slowly walkinq toward him, softly singing:
ESTHER When I was juuust, a lifitle g .iirl I asked'my mother, what .will I be...
ESTHER leg is broke John tries to stand, but cries out in agony.
ESTHER Big He looks up, sees the table with the PHONE on it.
ESTHER As he painfully crawls toward it, Esther closes in on him, singing and winding the jump' rope around her fists like a garotte.
Que sera, sera, Whatever will be, will be...
The future's not ours to see...
John reaches for the phone, actually touches it, when Esther straddles him from nd,- the iump rope around his neck, and starts strangling with it.
The phone.falls out of reach.
John itoo dazed from the fall to fight.
When I grew uuup and feeell in looove I asked my sweetheart what lies ahead Will we have rainbows, day after day Here's what my sweetheart said.-..
John chokes t clawing at the rope as she twists it tighter aid tighter.
Finally, his head droops his remaining eye goes blank.
Be'a dead.
Esther gently lowers has body to the floor, a tear running down her cheek.
She kisses him.
Whispers in his ear:
ESTHER Qua sera, sera.
ESTHER Suddenly -- a GASP from upstairs.
ESTHER Esther whirls.
ESTHER I 's 5 N ax..
ESTHER She stands atop the .stairs,- paralyzed- with fear.
ESTHER She's, seen everything.
ESTHER Esther, looks-u at her with a reassuring smile on her awful, mascara-streaked, blood-splattered monster face.
ESTHER It's all right, baby.
ESTHER -Come to Mommy.
Max runs away.
Esther scowls.
ESTHER Shit l.
ESTHER She scrambles to her feet..
'Esther Pulls John's gun case down-from the closet shelf, frantically unlocks it, and grabs the }.
Kate is speeding home, talking on her cell phone.
Dracena nine-one-one.
What is-your emergency?
KATE I need the police.
KATE There's an intruder in my home.
INT. MAX'S BEDROOM - NIGHT Esther enters, gun in hand, turns on the light.
INT. MAX'S BEDROOM - NIGHT Max isn't here.
INT. MAX'S BEDROOM - NIGHT Esther looks under the bed, opens the closet.
INT. MAX'S BEDROOM - NIGHT Nothing.
UPSTAIRS HALLWAY Max carefully peers out from.around a corner...
UPSTAIRS HALLWAY Suddenly -- no sound..
UPSTAIRS HALLWAY This is how Max experiences the world.
UPSTAIRS HALLWAY A silent vacuum.
UPSTAIRS HALLWAY Her perspective is shot MOS.
UPSTAIRS HALLWAY The hallway is empty and Max cautiously maces her way toward the stairs.
UPSTAIRS HALLWAY Suddenly, Esther emerges from Max's room.
UPSTAIRS HALLWAY Max quickly
ducks into Daniel's room.
Esther doesn't see her:
Max looks around for, a place to hide.
She sees a TOY ROBOT lying on the floor amongst Daniel's things...
KATE AND JOHN'S BEDROOM Esther is searching the walk-in-closet when she hears a LOUD NOISE from Daniel's room - something heavy falling over.
KATE AND JOHN'S BEDROOM She smiles.
UPSTAIRS HALLWAY Esther edges toward Daniel's room, gun raised.
UPSTAIRS HALLWAY There's a STRANGE GRINDING SOUND coming from inside...
Esther enters and looks around, confused.
There's a PM OF BOOKS that.have been knocked to the floor, but Max isn't here.
Then she sees what's making the GRINDING noise.' It's the TOY.
ROBOT.
It's been placed atop a bookshelf, motor grinding, walking on wobbly legs.
As it walks, it pushes books off the edge of the, bookshelf- onto the floor.
That's what made the noise that lured her here.
Esther scowls furiously at the robot and SHOOTS it.
Her back is to.the doorway, so she doesn't see Max emerge from her hiding place in the bathroom.
and slip- past.
INT.fEXT.
JOHN'S CAR -.NIGHT Racing through.
the streets, running stop lights.
Rate is still on her cell.
we have officers on the way, ma' amn.
RATE Well, where the hell are they?
RATE Jesus Christ, I'll be there before they will
Ma'am,- I need you to stay calm.
'Do not approach the house.
Let the officers --- Rate hangs.
up.
INT. BATHROOM - NIGHT Esther enters, looks in the linen closet, pulls back the shower curtain.
INT. BATHROOM - NIGHT Nothing.
INT. BATHROOM - NIGHT she's getting frustrated.
Streaking rain casts frightening shadowa in the glassed-in terrace.
Max quickly sneaks in and crawls under one.
of the numerous plant tables.
Hanging leaves droop almost to the floor, hiding.
her.
But as she curls up in the shadows, she bumps into a table leg and unknowingly knocks over a FLOWER POT.
MOS: -The flower pot SMASHES TO PIECES on the floor directly behind Max.' Naturally, she doesn't bear it.
But E e does.
She turns.
Eyes narrowing, suspicious.
Max cowers underneath the table with her back to the door.
She oesn gee Esther enter.
Esther looks around.
The room is dark and- still: She starts looking under the plant tables, vne by one,.HUMMING to herself.
Max is facing away from Esther and.
doesn't see her-approaching Can't hear her HUMMING.
Es er 19 a ogin -,is ...
Suddenly, TIRES can be heard SQUEALING- out on the street.
Esther stops and hurries to look outside.
She.stands right acr oss from where Max ia hiding and seen her.
Max presses 'her knees to her chest, trying to di sappe4r wMa under the table.
Esther doesn't notice.
Max is-right behind her, there are pieces of BRO=N POTTERY right by Esther's feet, but she hhassher.face pressed to the rain-streaked glass, trying
Fate 's the house.
durb and SKIDS to a stop on the wet law n She jumps o of the ar and sprints to the house.
INT. SUNROOM - NIGHT Esther sees Kate and leaves.
INT. SUNROOM - NIGHT Max breathes a sigh of relief-
INT. FOYER - NIGHT Kate bursts through the front door and-runs insider from the rain and s es'Johni? 1/2 's crumpled on t e floor.
INT. FOYER - NIGHT e h
KATE John!
KATE Oh, my God!
KATE John!'1 She rushes to him, but it's obvious that he's dead.
KATE She leans over his body and bursts into tears, aching at what has been done to him...
KATE then stop and steels herself for what ]sh jds to do..
Kate hurries to the keepsake box and rummages for the.keys.
Can't.
find them.
She.
quickly looks around.
Her breath catches.
The CASE l ies empty on t floor, u let sca tered around it.
Kate.
runs in, sobbing She sees the big knife that Esther was using earlier, grabs it.
Reconsiders.
She throws it aside an d instead draws a huge goddamn BUTCHER'S KNIFE from the knife block.
Kate throws the door open.
Max's bed is empty.
KATE No!!
Kate runs back out, - crying, frustrated, knife' trembling in- her hand.
She calls Esther out,.voice thundering with rage;.'
Esther hears her real name and freezes.
Realization bits.
Gig.'s up.
It's over.
Her eyes flit, panicky.
She quietly darts away.
Esther opens the- door to the basement.
She pulls open the breaker box and starts flipping SWITCHES.
UPSTAIRS HALLWAY Kate cautiously moves down the hall suddenly, he lights go plunging - tlw o se into darkness.
KATE AND JOHN'S BEDROOM Max freezes.- Now-she's blind as well as deaf.
KATE AND JOHN'S BEDROOM The only light comes from the FLASHES OF LIGHTNING through rain-streaked windows.
KATE AND JOHN'S BATHROOM Max hurries inside and hides in the linen closet.
UPSTAIRS HALLWAY Esther sneaks upstairs, hugging the wall, gun held ready.
UPSTAIRS HALLWAY She pauses at the top of the stairs, waiting.
UPSTAIRS HALLWAY Lightning FLASHES..
UPSTAIRS HALLWAY 'The- hallway is empty.
UPSTAIRS HALLWAY She sidles along the wall...
LINEN CLOSET MOS: Max is huddled on the floor, terrified.
LINEN CLOSET Suddenly, there's a FLASH of lightning --'mid Bhe A= fiba movement ti? 1/2 mn qb The 7oUvered slBts-.in .t225 t efo8i? 1/2 .
KATE AND JOHN'S BATHROOM Th& shadowy fizmre is fate.
KATE AND JOHN'S BATHROOM She's within feet of Max's hiding place and doesn't know it.
LINEN CLOSET MOS: Max watches the shadowy figure, nearly hyperventilating, not realizing that it'e Kate.
LINEN CLOSET It's coming closer, closer...
LINEN CLOSET then moves away.
LINEN CLOSET Max catches her breath.
LINEN CLOSET Kate heads back toward the stairs'.
LINEN CLOSET Esther raises the gun and -- BLAM!
LINEN CLOSET The knob on top of the bannister EXPLODES.
LINEN CLOSET Kate startles and whirls' to see Bather, just as she pulls frantically crawls/crabwalks into Esther's room, ehr teas ianother SHOT blows a chunk out of the moulding by
Kate stands by the door with her back to the wail, holding her bloody shoulder.
Her eyes flit, searching for a weapon.
Nothing.
She's standing right outside the door.
Kate breath.
.Esther takes a wary step into the room, gun holds .her Suddenly, Kate lunges body checking Esther against the door.
They struggle for the gun.
It GOES OFF.
Kate kno cks it out of Esther's hand and slams her to the floor, but Esth er is like a wild animal, kicking and shrieking and clawing at Kate'a face.
For a moment, they're locked li ke that, Ka te's hand wringing Esther's neck, Esther's thumb into Kate's wound.
Kate screams in agony, twisting.
Esther wriggles out from under her and scrabbles/slides into the hallway,-quickly scoops up the gun --
FOYER =-bnt Rate mat-out TA S her 'and the tw-q of i o.tvmbl n down the s.
FOYER They-hit the already splintered secon of the mailing and t gives way- -- CRASB 1 Rate and Esther fly through the smashed railing and fall a tangled heap.
FOYER Kate cracks her head.
FOYER The gun goe toSthe floor s They're both stunned by the fall, breath knocked out.
FOYER Kate is dazed, unable to move.
FOYER Esther recovers first, looks around for the gun, can't find it.
FOYER Kate stirs, fighting to stay cons cious.
FOYER Esther squirms away from her crawls over to John's body, and wrenches the scissor from his eye so ket.
FOYER Kate sees her but can only watch helplessly as Esther stagg p towa-rd her, bloody scissors clutched in her little fist like a dagger,
Then.
TSOi hits Es a ii? 1/2 g the ' the head.
ad and clocked her with a heavy Piece of Max 'has snuck up from be 1i Way to go, slugger !
the broken railing stung like a .basebal l bat.
Esther stumbles to her 7mee6, but manages to shake it off.
She slowly rises and turns on Max with a feral snarl.
Max tries to- hit.
her again, but Esther is ready this time and swats the blow aside.
She rips the piece of railing from Max's bands and .tosses it across the .room.
Then.she knocks Max to the floor with a fierce backhand from her fiberglass cast..
eees this and desperately searches fot the gun.
She spots it under'nder a nearby table and starts dragging he rself toward it...
the Esther hears gun S he- es Y%ate for the guw,tnd at her, scissors raised above head g screaming with hate.
Kate reaches whi the n.
Esther 's , almost-on her.
Kate grabs the gun, ls a nd i? 1/2 
Esther staggers back with a bZ hole an ehr the t .
Max watches, wide--eyed, as Esther limply drops the scissors and gives the smoldering bullet hole in her chest a surprised look.
Blood.trickles from her mouth.
She looks up at Kate, frightened tears welling in her big, sad eyes.
ESTHER Please" don't hurt me, Mommy.
ESTHER rat fucking chance, bitch.
ESTHER Kate SHOOTS her again.
ESTHER This one goes right between those pretty eyes.
ESTHER Esther falls to the floor, dead gaze staring at the ceiling, a pool of blood .expanding around her pretty Shirley Tem ple curls.
ESTHER Kate drops the gun and crawls over to Max, scooping her into her arms and hiding her face from the horrible sights all around them- For a long moment, mother anddaghte r o justi? 1/2 holdaeacheother close.
ESTHER Kate strokes Max's hair, cry ng u What Kate can't see"is the'slack, traumatized expression on Max's bloodied face.
ESTHER .vacant and emotionless.
ESTHER That spark you should see in the.
ESTHER eyes of a"child, gone forever.
ESTHER CAMERA PULLS BACK and we
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
