MOON
Written by
Nathan Parker
Story by
Duncan Jones
November, 2007
Helium3 is a gas ejected from the surface of the sun and blown through space by solar winds.
It plays an essential role in Cold Fusion, often toted as the solution to humanity's future energy needs.
There is one major problem...
Helium3 is extremely scarce on Earth.
The gas does, however, exist in abundance on the Earth's only natural satellite:
The Moon.
Should we turn to Cold Fusion in the future, it is conceivable that man will mine the Moon for Helium3 and bring the precious gas back to Earth...
We hear something -- a machine -- CHURNING and POUNDING.
Constant.
Rhythmic.
Though the sound is slightly familiar, we're not sure what it is yet.
Hold for a few seconds and then
The sound belongs to a regular old TREADMILL like you see in most gyms across the world.
Running on it: SAM BELL, mid thirties, thick beard, handsome, striking blue eyes.
Sam's face is flushed and glistening with sweat.
He lunges for a towel draped over the treadmill's bar, dabs his face as he runs.
We see OUTSIDE THE WINDOW: A gray, powdery landscape stretching beneath a BLACK SKY.
Aerial view of the Earth's only natural satellite, the camera roaming about a hundred feet off the surface.
Desolation.
Serious, uncompromising, desolation.
This place makes Antarctica look like Tokyo.
And utter silence.
Eventually the camera arrives at a moon base, DIVING DOWN towards it --
Sam takes a shower, treading in a tight circle beneath the nozzle, eyes closed, hot water blasting his face.
His hair still wet from the shower, Sam sits before a COMMS UNIT, dressed in a "Lunar Industries" boiler suit, a zip up the front, colorful patches sewn into the arms.
He begins to record a message.
SAM Tess.
SAM Hi.
SAM It's me.
SAM How are you, sweetheart?
SAM It's the morning here.
SAM In a few minutes Gerty and I will sit down for breakfast, go over the day's itinerary.
As Sam continues his message, we are given a TOUR of the mining base.
Beginning with:
This is where you want to be if the shit hits the fan.
The base's equivalent of HQ.
A wall of computers and flickering digital displays.
SAM (V.O.) Today begins my 154th week on Selene.
SAM (V.O.) I officially have two weeks to go before I climb into that Return Vehicle...
A small space craft attached to the base.
It is essentially a tiny room with a coffin like, sealed bed in the middle of it: a cryogenic POD with an array of complicated controls surrounding it.
SAM (V.O.) And blast home.
Sam spends most of his time here.
It is kitchen and play room combined.
We PICK OUT a television set, an armchair, a Ping-Pong table, the treadmill.
SAM (V.O.) I never dreamed I'd make it this far.
On a table, we also PICK OUT a LARGE MODEL carved out of BOLSER WOOD.
It's a TOWN.
Intricately done down to the tiniest details.
SAM (V.O.) (CONT'D) There were times, as you know...
We go even CLOSER to the model, seeing that there are actual people, actual characters in the little town; actual buildings: a CHURCH, a TOWN HALL, etc.
Clearly someone has put a ton of work into this thing.
SAM (V.O.) (CONT'D) ...when I thought I was going to crack up.
And the tour of the base continues.
Onto a new room.
A dark storage area Sam has repurposed to grow a handful of plants.
They sit surrounded by darkness, glowing under pools of artificial light.
SAM (V.O.) But I think I've come out the other side now.
A strange angular room, obviously purposeful, but its design more geared to a computer than a human being.
A single bed dominates.
SAM (V.O.) In many ways, this place is all about contradictions.
The empty terrain surrounding the mining base, as viewed from the Monitoring Station window.
Across the landscape a mountain rises from the morning shadows.
SAM (V.O.) It's bleak, it's beautiful.
Some kind of rake or shovel half buried in the powdery soil, like a child's toy abandoned in a sand box.
SAM (V.O.) (CONT'D) It's barren, yet filled with riches.
From up here it is easy to see why the Earth is sometimes referred to as "the blue marble."
A swirl of color.
SAM (V.O.) The earth is thousands and thousands of miles away, but sometimes looks so close I feel like I could reach out and snatch it with my hand.
Sam's bed -- A New York Jets poster on the wall -- a few knickknacks bedside, rock samples in jars, a lucky tambourine Sam got in Mexico some years ago -- a red stress ball -- a photograph by the bed in a frame --
SAM (V.O.) I'm incredibly lonely, yet I'm never alone...
We MOVE CLOSER to the PHOTO by the bed.
Of a slightly younger and clean-shaven Sam with his arms wrapped around his wife of four years, TESS BELL.
SAM (V.O.) (CONT'D) Because I have you.
Tess is a far cry from the stereotypical Astronaut's Wife of the 1960's/70's with the plastic smile and beehive hairdo.
Tess is modern, sophisticated, and jaw-droppingly beautiful.
She looks like she'd be a hard woman to leave behind.
Note: In the photograph Tess is visibly PREGNANT.
SAM (V.O.) (CONT'D) And I have Eve.
SAM (V.O.) (CONT'D) I don't take you guys for granted.
SAM (V.O.) (CONT'D) You know that now.
Back with Sam at the Comms Unit as he wraps up the message.
SAM Please kiss Eve for me.
SAM And tell her daddy will only be away a little longer -- seventeen days longer, approximately.
SAM I love you both dearly.
SAM Bye.
And he sends the message.
The main corridor connecting the different rooms.
We've seen everything there is to see now.
The base is small.
Confined.
Claustrophobic.
It is easy to imagine how someone could crack up here.
Sam leaves the Comms Room and heads down the corridor.
A state of the art robot, a GERTY 3000 -- known simply as "GERTY" -- is preparing Sam's breakfast.
Gerty is in three sections and moves along a horizontal rail that runs throughout the base.
He has a readout screen that perpetually spews data.
His hands resemble pincers, but are perfectly nimble.
For the purposes of helping run the base and looking after Sam, Gerty is as good as human, if not better.
Sam enters.
SAM Morning, Gerty.
GERTY Morning, Sam.
GERTY How are you today?
SAM Fine.
SAM Fine.
SAM You?
GERTY I'm very well.
GERTY How's your headache?
SAM Much better, thanks, pal.
Sam treats Gerty more like a person than a robot.
Whether this is down to Gerty's intelligence or Sam's desperation for company isn't clear just yet.
Note: Gerty talks like a well-educated older man.
His language doesn't have a great deal of inflection (i.e.
Monotone) but he is friendly enough.
Sam switches a dial on a radio but gets nothing but static - - he sticks in a mini cd and skips the first few tracks.
We hear brief clips of talk radio and shuttle through it before he allows it to play on, on some random American station -- an old weather report:
VOICE ON RADIO ...it's a hot one on the East Coast, temperatures soaring to a high of ninety three degrees in New York City --
They zip around the tiny kitchen, together preparing Sam's breakfast, working as a team.
We take in the whole Moon at once.
Gray, colorless, eerie.
From this distance the surface resembling Plaster of Paris.
Sam sits before Selene's main computer, known as THE OLD MAN.
Data flickering off Sam's face.
He is making a log entry.
A CLOCK is running on the monitor.
SAM 8:32 Pacific Time.
SAM Lunar Day 1.
SAM All Harvesters running smoothly this morning.
SAM Readouts are as follows: Matthew, 14.6 miles; Mark 16.8 miles...
Sam continues with his entry while we
Gerty is selecting food for the up-coming week, stacking ready-meals on a small fork-lift buggy.
Pulsing rapidly.
The "ping-ping-ping" of an alarm.
Sam stands before the Big Board.
The names of the four Harvesters (Matthew, Mark, Luke, John) in a collum.
The red light is flashing next to Matthew.
Sam presses an INTERCOM BUTTON, dips down, speaks into it.
SAM Gerty, we've got a live one on Mark.
SAM I'm going out now to rope her in.
GERTY'S VOICE Okay, Sam.
Sam heads off.
Resembling an unmanned puppet.
Sam begins to insinuate his body into the suit.
Three Rovers (moon buggies) parked in their separate bays.
The Rovers are caked in lunar soil, as though sand blasted.
In his space suit Sam bends into one of the Rovers, starts the engine.
Sam drives along, dwarfed by an enormous lunar bolder and the rising slopes of the valley beyond.
A toy car in this vast and alien terrain.
The second in a fleet of four Harvesters (this one known as Mark) collecting lunar soil.
The Harvester resembles a tank and kicks up clouds of dust.
Booming, hulking, efficient.
Sam catches up in his Rover and accelerates into the back of the Harvester up a couple of ramps.
An intricate and dangerous maneuver he executes deftly.
Sam is in an area of the Harvester -- a kind of hatch -- not dissimilar to a garage and known as THE BELLY.
Once safely inside Sam closes the door.
He is able to breathe in the Belly without his helmet, which he duly removes.
Sam steps up to a wall of computers.
A light is flashing to indicate one of the pods is filled with Helium3.
Sam does his thing, eventually removing a keg-size pod of Helium3.
He hauls it over to the Rover and sticks it in a special slot in the equivalent of the Rover's trunk.
A new pod -- an empty -- replaces the pod Sam just removed.
Sam puts his helmet back on, returns to the Rover, reverses out of the Harvester carefully.
Sam snakes through the soil on his way back to base, the tracks of the Rover as sharp as if they had been made through talcum powder.
The Harvester churns into the distance.
Sam loads the filled pod into a CARGO CONTAINER.
The Cargo Container is about the size of a fridge and can take a maximum of five pods.
There are four pods already inside, Sam's new pod taking up the fifth and final slot.
Sam is seated at the Comms Unit recording a message for his superiors back on Earth.
SAM Sam Bell reporting to Central.
SAM 10:14 Pacific Time.
SAM Lunar Day 1.
SAM Overmeyers, Thompson?
SAM It's Sam.
SAM How goes it?
SAM I've got a full container of Helium3 ready to roll.
SAM The purity is pretty good, so assuming your last market prices are still relevant I think you are looking at getting about 3 million dollars per kilo with this load.
SAM By the time this message reaches you it should be in transit.
SAM Otherwise, everything running smoothly.
SAM There was a discrepancy between a couple of the N3000 modulators a couple of days ago, but Gerty and I caught it in time, no big deal.
SAM Uh...how are things down there?
Sam desperately wants to talk but has nothing very important to say.
Then he remembers something.
SAM (CONT'D) Oh, and I just wanted to thank you for sending out the football feed.
SAM (CONT'D) Almost felt live!
SAM (CONT'D) Seriously, I don't mean to be an asshole, but surely replacing one satellite cant be that fucking hard!
SAM (CONT'D) I haven't been able to have a conversation with my wife...
SAM (CONT'D) My kid can talk now...!
SAM (CONT'D) Fuck!
Sam concentrates, getting a grip on his temper.
Two weeks.
Two weeks.
Hey.
Three years is a long haul.
If you guys want to run some psych evals on me when I get back, I'm happy to do it.
It ain't Disney World up here.
That's it.
Over and out.
Sam reaches forward, sends the message.
Sam is loading the Cargo Container into the base's MAGLEV LAUNCHER.
He works with a sense of routine, far away, preoccupied.
All of a sudden Sam STOPS.
He has the feeling someone is standing behind him.
He slowly turns.
A GIRL is standing in the doorway watching him.
She is perhaps fifteen or sixteen years old.
A yellow dress.
Long, wheat-colored hair.
Freckles.
At once beautiful and haunting.
Sam gets the FRIGHT of his life.
He FLIES against the wall.
WIDEN to reveal Sam and the Girl facing off.
Sam POP-EYED and SHAKING.
The Girl IMMOBILE, arms at her sides, head tilted ever so slightly to one side.
The Cargo Container is sent hurtling through space.
A TERRIFIC BLAST.
It distracts Sam's attention, breaks his stare...
And just like that, the Girl is gone.
Sam is just staring at an empty doorway.
Nothing there.
Sam is baffled.
Had to be his imagination.
Had to be.
After a few seconds he shakes his head dismissively and continues working.
Gerty is cutting Sam's hair.
Sam sitting back in a chair, barber shop style, while the robot snip-snip-snips away with a pair of scissors.
Sam is gently squeezing a STRESS BALL in his right hand.
GERTY Sam, is everything okay?
SAM Everything's fine, Gerty.
For a moment there is no sound but the snipping scissors, reminiscent of keys snapping on a typewriter.
Then:
SAM (CONT'D) Why do you ask?
GERTY You don't seem like yourself today.
Sam frowns, contemplative.
For a moment we think he is going to tell Gerty about the Girl he saw earlier -- or imagined he saw.
But he goes with something different.
SAM It's Tess.
GERTY Has something happened?
SAM No, not exactly.
Gerty stops cutting, lowers the scissors.
GERTY Sam, what is it?
SAM Something doesn't feel right, that's all.
A beat.
Sam's fingers twitching around the red stress ball, squeezing harder.
GERTY Sam, it might help to talk about it.
Sam decides to come clean.
SAM Tess isn't responding to things.
GERTY Tess isn't responding to things?
SAM Right.
GERTY What kind of things?
SAM A couple of weeks ago I asked her if she wanted to go on vacation when I get back, and that I was thinking of either Mexico or Hawaii.
SAM (CONT'D) Tess never said anything about it.
SAM (CONT'D) Three messages she's sent me since...and she's never once mentioned the vacation.
GERTY Im sure she can't wait, Sam.
SAM That's not the point.
SAM This is someone who lives for vacations and travelling.
SAM I thought she'd jump at the chance for us to go away -- with Eve, of course -- we'd take Eve.
GERTY Perhaps Tess didn't receive the message?
SAM But this isn't the only time it's happened, Gerty.
SAM When I asked her how her dad was doing on his new heart medicine she didn't respond to that -- I asked her when Eve was going to start nursery -- nothing.
SAM Had her brother got the position at the University?
SAM Nothing.
SAM Nothing.
Sam is really having a go at the stress ball now.
GERTY I think her brother did get the position at the University.
GERTY His name is Christopher, correct?
SAM He did?
GERTY Yes, I seem to recall he got the position.
GERTY Professor of Biochemistry, I think.
GERTY At Syracuse University in New York?
Sam is slightly alarmed that Gerty knows this and he doesn't.
SAM How do you know that?
GERTY You told me.
GERTY Some time ago now.
GERTY Towards the beginning of your time on Selene.
GERTY When we were starting to get to know each other.
GERTY You were very happy for your brother-in-law.
GERTY You danced around the Rec Room, if I remember correctly.
Sam looks perturbed.
For a few seconds he'd eased up on the stress ball.
He starts up on it again now.
SAM Gerty, have you heard anything new about anyone fixing lunar sat?
GERTY No Sam.
GERTY From what I understand it's fairly low on the companies priority list with the Jupiter mission active.
GERTY I would imagine it would be very expensive to fix.
A pause.
Sam still looks troubled.
GERTY (CONT'D) Sam, are you ok?
SAM They need to sort that out.
SAM Seriously.
SAM I've only got two weeks left.
SAM It's not fair on whoever's up here next.
SAM Gerty, you tell them to sort it out.
SAM It's not healthy.
GERTY I will Sam.
GERTY Do you want me to finish cutting your hair later?
SAM Nah.
SAM Come on.
SAM Let's finish this.
Gerty resumes cutting Sam's hair, and stops again, sensing Sam is going to say something more.
The scissors freeze.
SAM (CONT'D) I've got another one of those headaches.
SAM (CONT'D) Can you get me something for it?
GERTY Of course.
GERTY Now?
SAM No not now, afterwards.
The scissors start up again.
SAM (CONT'D) Thanks, pal.
Sam with a HAIRCUT and a neatly TRIMMED BEARD is sitting before the Bolser Wood model of the little town.
He is arched over working away with an EXACTO BLADE -- SQUINTING -- whittling a figure out of wood.
This is difficult and complicated work, and over three years Sam has become highly skilled at it.
Sam can carve an actual person out of wood -- actual cheekbones, actual throats, actual hands -- it's fascinating to watch.
From another room Sam hears the "ping-ping-ping" of an alarm.
Flashing on the comms unit monitor: "NEW TRANSMISSION."
There is a small icon of a telephone.
He carefully puts down the wooden figure and the exacto blade -- stands and leaves the Rec Room.
Sam sits at the comms unit watching a message from his superiors, OVERMEYERS and THOMPSON, a purposeful looking woman in charge and her earnest second.
The two talk RAPIDLY and trade off like a tag team.
At times their tone can be almost bizarrely whimsical.
Overmeyers and Thompson seem to have known Sam for a while, but even so, there is a practised casualness to the repartee.
It's a professional friendliness on Overmeyers part, no more and for Thompson it's merely an eagerness to be involved.
OVERMEYERS Delighted to hear about the latest shipment, Sam.
THOMPSON According to Albatross 90 it should be landing off the California Coast within the next three days.
OVERMEYERS Now in response to your question about the communications equipment, the news is not good.
THOMPSON Sam, those solar storms did a lot more damage than initially thought --
OVERMEYERS Fixing the lunar sat is going to take some time.
OVERMEYERS It's a significant operation.
THOMPSON And what with the Jupiter Program hemorrhaging money --
Sam curses to himself.
OVERMEYERS Lunar doesn't have the budget it once did, Sam, you know that.
THOMPSON Even the coffee machine down in the Hub has been broken since I don't know when --
OVERMEYERS We have to go to Genesis 3 just to get a decent cup of coffee, Sam.
OVERMEYERS Genesis 3.
OVERMEYERS That's three buildings over.
THOMPSON We're hoping to get the live feed up and running by the Fall.
THOMPSON The good news is you'll be home by then, Sam.
OVERMEYERS You only have two weeks to go!
OVERMEYERS Congrat--
Sam shuts off the message before Overmeyers can pipe out his last line.
Sam sits before the dead screen -- eyes closed -- taking a succession of DEEP BREATHS.
Sam playing Ping-Pong.
He has folded up the second half of the table and is using it as a wall.
The sound is rapid and rhythmic: ca-cluck ca-cluck ca-cluck.
Sam taking his FRUSTRATION out on the little white ball.
Sam stands before the toilet urinating.
Rather ironically he is whistling I'm Walking on Sunshine -- focussed ahead at his reflection in the mirror -- angling his face, admiring his haircut, his beard.
Then he looks down to flush the toilet and his WHISTLING abruptly STOPS.
It looks like someone just poured a glass of CRANBERRY JUICE into the toilet bowl.
Literally.
The red urine clouding the water like a squirt of octopus ink.
Yeah, Sam just pissed blood.
There is a "PING!" and Gerty's voice crackles from the intercom.
GERTY'S VOICE Sam, a transmission has arrived from your wife.
Sam reaches over and presses the INTERCOM BUTTON.
SAM Be right there.
And he flushes the toilet.
Sam sitting before the monitor.
He hits the "PLAY" button, begins watching the message.
ON THE MONITOR: Tess is sitting in a living room talking to Sam.
Tess has a sweet voice, she sounds grounded, like she's got a head on her shoulders.
TESS Hi Sam.
TESS It's me.
TESS How are you?
TESS I got your last message, it was really great to hear your voice.
TESS I know you've been really lonely up there, but in a lot of ways it's been good for you, I think.
TESS I hope you don't mind me saying that.
TESS I'm proud of you.
TESS Hey, someone's got something to say.
A WOMAN, possibly a nanny or some form of hired help, swings a LITTLE GIRL into Tess's arms.
This is EVE, Sam and Tess's daughter.
TESS (CONT'D) Eve, it's daddy.
TESS (CONT'D) What did you want to say to him?
TESS (CONT'D) Eve just stares.
TESS (CONT'D) Tess whispers to her ("Remember what we
practiced", etc.)
Finally Eve attempts:
EVE Asstraut.
TESS Who's an astronaut?
TESS Go on!
EVE Daddy asstraut!
Tess laughs.
So does Sam.
TESS That's right, daddy's an astronaut.
TESS Clever girl!
Eve fidgets, rubs her nose, distracted.
TESS (CONT'D) She's shy.
TESS (CONT'D) Uh, Cathy, could you...?
The Maid steps in, hoists Eve away.
Tess waits until they're out of earshot.
TESS (CONT'D) It's her birthday next month.
TESS (CONT'D) I thought we'd get her a play house for the garden.
TESS (CONT'D) We could even pick it out together.
A pause.
Tess just stares into the camera.
She is hundreds and thousands of miles away, but for a second it feels like she's right there in the Comms Room with Sam.
It's intimate.
She finally shakes her head, self-conscious, shy.
TESS (CONT'D) God, I hate these things.
TESS (CONT'D) Sam, I love you.
TESS (CONT'D) I'm thinking of you always.
TESS (CONT'D) I can't wait to see you, sweetheart.
TESS (CONT'D) Okay.
TESS (CONT'D) Bye.
And the message ends.
ON SAM: smiling, on the brink of tears.
The Earth at night, illuminated by a glittering spider's web of artificial lighting.
From the Moon this is one of the most beautiful sights you'll ever see.
Sam is in improved spirits.
He pours himself a glass of juice as Gerty prepares dinner.
SAM What's on the menu tonight, Gerty?
GERTY Baby back ribs with french fries and spinach.
SAM Ribs!
SAM Good choice, pal.
SAM Fine choice.
It might be baby back ribs with french fries and spinach, but it's made from a packet by adding hot water.
Nasty.
Sam sits down with the packet.
Digs in with a fork.
SAM (CONT'D) Oh yeah!
SAM (CONT'D) Compliments to the chef, Gerty, this is delicious!
Sam eating ravenously.
Sam is in the Greenhouse pruning plants with a pair of secateurs.
He treads up the aisles slowly, taking time with each of the plants.
CLASSICAL MUSIC plays over the sound system, Brahms, Beethoven, Bartok, one of the B's.
Sam HUMS along to the music.
A man at peace.
Sam is working on his wooden model of the town.
Across the room the Ed Sullivan Show is on TV.
Ed's guest is a very young Goldie Hawn.
Note: Whenever any TV is watched in the film, it is always a show from 1970's America.
(Mash, Six Million Dollar Man, Laugh-In, etc.)
No explanation is given for this.
Sam is half-watching the TV, but his focus is chiefly on the SMALL HOUSE he is carving.
And carving beautifully.
After a few seconds he stands and snaps off the TV with a remote.
He crosses to the kitchen section of the Rec Room to make some tea.
The water has just boiled.
As Sam is about to pour the boiling water, tea kettle in hand, he glances across the Rec Room and sees:
The Girl.
She's taken Sam's chair before the model.
She is motionless, staring down at the model like she recognizes one of the little figures walking the tiny streets.
Sam calmly puts the tea kettle down and begins to move towards the Girl, slowly, cautiously, like he wants to sneak up on her.
Sam walks right up to the Girl and reaches out his hand...
SAM
And then we CUT to Sam standing in the kitchen.
Over by the model there is no sign of the Girl.
The chair is empty.
She's gone.
Her sitting there, Sam's walk across the room -- apparently he imagined it all.
Sam looks down.
The tea kettle is dangling at an angle and BOILING WATER is DRIBBLING onto his left hand.
Simultaneously: Sam SNAPS his hand AWAY, Sam SCREAMS.
The tea kettle CLATTERS to the floor.
Sam HURRIES to the sink and jerks his hand under a stream of cold water.
Cursing under his breath the whole time: "Shit, piss, fuck..."
Sam sits in a chair as Gerty tends to his scolded left hand.
It's a nasty burn.
SAM I'm going to feel that for a while, aren't I, Gerty?
SAM Damn it.
Gerty applies a translucent balm to the burn.
GERTY Sam, can I ask how it happened?
SAM I told you, I saw something on the TV and spilled boiling water on my hand.
GERTY You saw something on the TV?
SAM Yeah, something on the TV distracted me, Gerty, what's wrong with that?
A pause.
Gerty is wrapping Sam's hand with a bandage.
GERTY Sam, you said it was the TV that distracted you, but when I came in the TV wasn't on.
Gerty has caught him out.
Sam knows it.
GERTY (CONT'D) Perhaps you were imagining things?
Gerty has hit the nail on the head, in a way that makes Sam feel a little uneasy.
Is there something Gerty knows that Sam doesn't?
Sam asleep in bed.
Sam making love to Tess.
We remain very close to their bodies in bed.
The background a blur.
No sound.
It's all flesh and white sheets.
Sensual, delicate, intense.
We feel almost intrusive watching.
Sam wakes up and lunges across the bed to shut off his alarm clock.
We notice a WHITE BANDAGE on the hand that he scolded.
Afterwards: Sam lies back, watching the ceiling, groggy, reflective, still surfacing from his dream.
And then OVER THIS: The sound from the opening of the film, THE TREADMILL, and we
Sam on his morning run.
Gerty is making breakfast.
Sam enters, fresh from the shower.
SAM Morning, Gerty.
GERTY Morning, Sam.
GERTY How are you today?
SAM Fine.
SAM Fine.
GERTY How's the hand?
SAM It's a little sore.
Gerty pops the radio on.
Just another morning on Selene.
Sam sitting before The Old Man doing his daily log entry.
A CLOCK is running on the monitor.
SAM 8:19 Pacific Time.
SAM Lunar Day 2.
SAM Readouts are as follows: Matthew, 9.8 Miles...
Suddenly the monitor BLIPS -- a BLAST of STATIC -- and Sam SEES himself talking on the monitor.
It appears to be a previous log entry.
SAM (CONT'D) Luke...7.3 miles...wow, better look into Luke...
But bizarrely, the Sam talking on the monitor has long hair pulled back into a ponytail -- and no beard --
And then another BLIP -- another BLAST of STATIC -- and the screen turns completely BLACK.
A single word begins to flash in the center of the screen:
The word flashes three times -- before the screen returns to normal, the CLOCK running again.
It all happened so quickly Sam wonders if he didn't just imagine it.
After an awkward pause he simply continues the original log entry.
SAM (CONT'D) Mark, 11 miles on the button...
Pulsing.
Going "ping-ping-ping."
Sam stands across the room with a mug of coffee, peers up at the Big Board, sees that the alarm belongs to Matthew.
He crosses to the INTERCOM, speaks into it.
SAM Gerty, looks like we've got a live one out on Matthew.
SAM I wondered what was taking him so long, the old fart.
SAM I'm heading out in a few minutes, just going to finish my coffee.
GERTY'S VOICE Okay, Sam.
Sam at the wheel in his space suit, speeding towards the first of the Harvesters, known as MATTHEW.
As Sam gets closer to the Harvester, he suddenly sees something:
The Girl.
She is standing maybe a hundred yards away in her yellow dress, resembling a FLAME or a FLOWER in the barren and colorless landscape.
She appears to be staring directly at Sam's rover.
SAM
His face unfolding with panic, alarm, curiosity.
An intense, yearning, curiosity.
He drives closer.
But like in a dream, Sam can't seem to make up any distance between the Rover and the Girl.
He CRUSHES the accelerator peddle.
For a moment Sam drives right alongside the Harvester, clouds of lunar dust being kicked up, cascading against the side window.
But Sam is looking away from the Harvester, focussed on the Girl.
ON SAM: He doesn't notice Matthew (The Harvester) suddenly veer RIGHT, slamming into the side of the Rover and causing Sam to lose control.
The steering wheel swings left and right as Sam desperately tries to STRAIGHTEN the path of the vehicle, but a split second later the Rover is FLIPPED like a matchbox, and SPUN into the path of the Harvester -- a HIDEOUS SCREECH of MANGLED METAL -- the Rover gobbled up by the front of the Harvester, DEVOURED.
The Rover is JAMMED under the Harvester's monstrous AXLE, resembling a crushed beer can in a fist -- and with a BIG, BOOMING GROAN the Harvester slides to a STANDSTILL.
WIDE SHOT: Silence.
The Harvester stationary.
The Rover caught beneath it.
No sign of the Girl.
Silence.
Hold it for five seconds and then
Eyelids fluttering, bright light, at first broken up, filtered, as if viewed through a Kaleidoscope.
Slowly shapes and impressions begin to form and we know where we are.
It's the Infirmary.
A CLEAN SHAVEN and drugged-up Sam is sitting up in bed, propped with a pillow.
Sam doesn't have a scratch on his face, but has clearly been through a terrifying ordeal.
Gerty is bedside.
SAM Where am I?
GERTY Sam, you're in the Infirmary.
GERTY You had an accident.
Sam looks bewildered -- he desperately racks his brain, trying to locate the memory.
GERTY (CONT'D) Do you remember what happened?
SAM No.
SAM I don't remember a thing.
Sam just stares back at Gerty, not so much as a flicker of recognition.
GERTY Do you remember me?
SAM Yes, of course I remember you, Gerty.
GERTY That's good.
GERTY That's very good.
GERTY It's nice to see you awake again.
GERTY I'd like to keep you under observation here in the Infirmary for a few days and run some tests.
A pause.
Sam taking it all in.
Eventually:
SAM How long have I been out?
GERTY Not long.
GERTY Sam, go back to sleep.
GERTY You're still very tired.
GERTY We can talk later.
Sam closes his eyes, sinking deeper into his pillow.
Sam asleep in bed.
Gerty is scanning his head with a small instrument resembling a camcorder.
There are READOUTS on a monitor showing blood flow, oxygen levels and glucose metabolism in the tissues of Sam's brain.
LUKE, one of the Harvesters, crossing the lunar landscape at HALF SPEED.
Sam wakes up from an extended nap.
He thrusts his fists into his eyes like a child, yawns ferociously.
SAM Gerty?
No sign of the robot.
Sam is feeling well enough to walk.
He swings his legs out of bed, begins to plod around the room.
He is tentative at first, slow, as if walking is something he is having to learn from scratch.
Eventually when he is moving fluidly he goes to the door and pokes his head out into the corridor.
Sam peers around.
From another room he can hear the faint drone of VOICES.
One of these voices belongs to Gerty.
The other voices are deeper, faster, human.
SAM Gerty?
The voices continue.
Intrigued, Sam PRESSES ON down the corridor.
As he walks up the corridor in the direction of the Comms Room.
Sam is close enough now that he can actually hear the conversation.
Sam arrives at the door of the Comms Room and peers in.
GERTY (0.S) These were extraordinary circumstances, as you know --
Gerty is installed at the Comms Unit.
Thompson and Overmeyers are on the screen.
The moment Gerty sees Sam he shuts off the monitor and the screen fizzes to black, Thompson and Overmeyers vanishing.
Strange: Gerty appeared to have a live feed.
GERTY Sam, you're out of bed.
SAM I wanted to stretch my legs.
SAM What was that?
GERTY Not talking.
GERTY No.
GERTY We've been having some problems with the lunar sat and our live feed seems to be down.
GERTY I was recording a video message for Central updating them on your progress.
GERTY Sam, you need to stay in bed.
GERTY You're not ready to walk around yet.
Sam nods vaguely, turns around and heads back to the Infirmary slowly.
Sam watching TV -- The Muppet Show, the "Pigs in Space" sketch -- and eating dinner.
He's not laughing.
Sam hunched over the infirmary's stainless steel wash basin giving himself a shave.
He hits the razor on the side of the basin -- tap tap tap -- like a conductor with a baton.
Sam is seated at a table.
Frankly he looks better now than he did before the accident.
Perhaps it's the rosy hue of his freshly shaven face.
He certainly looks younger.
A man revitalized, a man mended.
Gerty is giving Sam something very similar to an IQ Test.
Sam has just arranged a series of blocks into an L-shaped tower.
GERTY Excellent, Sam.
SAM How much longer do I have to be in here, Gerty?
GERTY Sam, you suffered minor brain damage in the crash.
GERTY This has resulted in memory loss and slight logic impairment.
SAM When can I get back to work?
GERTY Central has asked me to slow down the Harvesters to ensure you have time to recuperate and get your strength back --
SAM Terrific.
GERTY The good news is you can return to the sleeping quarters tomorrow.
GERTY But it will still be a few more days before you can resume anything like a normal work schedule.
Sam's face taught with irritation.
He isn't happy.
Gerty gives him the next puzzle to solve.
WE MOVE IN ON SAM'S LEFT HAND as he takes the puzzle, the same hand he scolded in an earlier scene.
The BANDAGE is GONE and the BURN appears to have completely
Sam walking down the corridor in the direction of the Sleeping Quarters.
He stops at a RED LIGHT on the corridor wall, beneath it the word, "EXIT DOORS."
He's locked inside the base.
Sam pulls a face, disgruntled, continues down the corridor.
Sam takes in the New York Jets poster on the wall and walks over to the bed -- studies his lucky tambourine and the glass jar of lunar rock samples -- like he's trying to reacquaint himself with his own belongings.
His eyes arrive on the red stress ball.
Sam scoops up the ball and PITCHES it at the wall like he expects the thing to bounce back to him.
The stress ball doesn't bounce back, simply hits the wall with a dull THUD and DROPS to the
A desolation special.
The blacker than black sky above.
None of the ingredients of life.
On Earth we have rainforests, and flowers, and birds.
We have color.
Up here we realize how lucky we are.
The base is lit by large halogen comfort lights, alone in the lunar desert.
This is a lunar night.
Sam sitting before The Old Man doing a few innocuous tasks, collecting readouts, slurping a cup of coffee.
Gerty is within ear shot.
Sam sees something that pulls him CLOSER to the monitor.
SAM Gerty, do you know about this?
Gerty approaches.
Sam taps the screen.
SAM (CONT'D) Matthew's got no velocity read- out.
SAM (CONT'D) He's completely still.
GERTY He must have stalled.
Sam gives Gerty a look.
That's not good.
Sam is recording a message for Central.
SAM There's no way to tell from here if a track's been thrown, or if it's just something jammed in an axle, or what...
SAM I can shoot out there, check it out, get some video and maybe save you guys the expense of floating in a whole crew!
SAM I know how tight money is right now....
Sam really frustrated now.
He feels cooped up, stir crazy, idle.
SAM (CONT'D) Just give me the word -- or Gerty the word, tell him to unlock the exit doors -- and I'll go out and get Matthew up and running again.
SAM (CONT'D) That's it.
SAM (CONT'D) Over and out.
Sam sends the message.
Sam enters the Rec Room, looks around, his eyes settling on the model of the town.
Sam sits down in front of the model, staring -- he picks up the HOUSE he was carving earlier -- studies it carefully.
Sam and Gerty are seated at the Comms Unit watching a video message from Central.
Sam is holding a carved HOUSE, examining it as he listens to the video.
The familiar faces of Overmeyers and Thompson on the screen, shoulder to shoulder, the two looking more like vultures right now than lizards.
THOMPSON Sam, we appreciate the offer, but you concentrate on feeling better.
SAM Oh for Christ's sake...
OVERMEYERS We don't want you to take any unnecessary risks.
OVERMEYERS You're too important to us.
THOMPSON You're to stay put, understand?
OVERMEYERS It's an order.
THOMPSON It's an order, Sam.
THOMPSON From Lunar.
THOMPSON Stay put.
OVERMEYERS We're going to send a Rescue Unit to tend to the stalled harvester and get the base back on its feet.
SAM Why?
The message ends.
Sam turns to Gerty, irate, the message as good as a kick in the balls.
GERTY I'm sorry Sam.
Sam stares at Gerty.
GERTY (CONT'D) Sam, I am under strict orders not to let you outside.
Sam throws the half completed wood carving in his hand at the other end of the room, breaking it.
He FLIES to his feet -- growling with frustration -- STORMS out of the room.
Sam asleep in bed.
Sam and Tess making love.
We remain very close to their bodies in bed.
The background a blur.
It's the same dream we saw earlier.
Something is different though.
We drift past Sam and Tess, and under the sheets of the bed.
Down between their entwined feet huddles a bearded, wide- eyed Sam, staring directly at us from under the sheets at the end of the bed!
Sam is quietly eating breakfast, lost in thought.
Gerty puttering around in the background.
The radio drones away.
Sam is seated at the Comms Unit watching a message from Tess.
We assume this is an old message since Tess is heavily
Her slender hands are spread over her prodigious belly as she beams at the camera.
TESS He's kicking...or she's kicking.
TESS I'm certain he's a boy.
TESS I wish you could feel it.
TESS I think we made the right choice, Sam.
TESS I really do.
TESS We need some time apart.
TESS We got stuck.
TESS That happens in marriages sometimes.
TESS It's nothing terrible.
TESS Well listen, I love you lots -- and we'll talk soon, okay?
TESS Bye Sam.
A POP and Tess is gone -- the monitor filled with STATIC.
Sam sits staring into space.
Tess' message seems to have agitated him.
SAM Fuck it.
He JUMPS from his chair and HEADS OUT of the Comms Room at pace.
Sam strides in -- swipes a KNIFE from beside the wooden model -- strides out again.
Sam glances left and right -- making sure there's no sign of Gerty -- then begins to PRY open a VENT with the knife.
Once the vent is removed he reaches deep inside and YANKS out a bundle of interwoven WIRES -- Sam bends the wires around the BLADE of the knife -- and CUTS.
GAS ISSUES from the cut wires.
An ALARM sounds.
Sam hides the knife away, shouts down the corridor:
SAM Gerty!
SAM Get over here!
SAM Quickly!
Gerty comes out of the Monitoring Station and SHUTTLES down the corridor.
GERTY What happened?
SAM Don't know -- Micro meteorites, maybe?
SAM Either way there might be damage to the exterior shell.
SAM I'd better go outside and take a look.
GERTY There is no damage to the exterior shell.
SAM It's not that I don't believe you, Gerty, but the inner skin is springing leaks like an ACME fire hose.
SAM Maybe you better let me take a look, just in case, huh?
GERTY Sam, I'm not supposed to let you go outside.
SAM Then let's keep it between you and me then.
SAM Ok?
The robot takes an inordinate amount of time to think this through.
The syrupy gas distorts the light as it collects at Sam's ankles.
Gerty's arms work away as they speedily repair the damage Sam has done.
Finally:
GERTY Okay, Sam.
The "Exit Doors" LIGHT turns from RED to GREEN.
For Sam this is like the BLAST of a STARTING PISTOL -- he immediately takes off down the corridor --
Sam finds his space suit is gone, so grabs the spare suit and scrambles into it.
Two Rovers parked side by side.
One of the parking bays is EMPTY.
Sam stands before the empty bay for a moment -- why is one of the Rovers missing?
If Sam suspected something was wrong before, he is certain of it now.
He climbs into one of the two remaining Rovers.
Sam speeding along in the Rover.
He has Matthew's coordinates plugged into his Navigation System and is following a MAP on a small monitor.
Sam heading towards the stalled Harvester.
It soon becomes apparent that there is something STUCK under the front of the Harvester's AXLE.
A second later it is apparent what that something is: inevitably, it's the MISSING ROVER.
Sam slows his Rover down, approaching the scene with CAUTION.
He parks a few feet away from the wreck and opens the door of his Rover, stepping outside gingerly.
ONE SIXTH GRAVITY is like walking on a trampoline.
Sam takes long strides, bobbing over to the front of the Harvester to take a closer look, his boots leaving deep FOOTPRINTS in the lunar soil.
The crashed Rover is exactly as we left it after the accident, mangled, crushed, captured beneath the trundles of the Harvester.
Sam peers closer and sees that there is an UNCONSCIOUS MAN in a Lunar Industries space suit trapped inside.
Sam can't see the man's face -- he has his back to Sam, his body sprawled across the passenger seat like he's searching for loose change on the floor of the vehicle.
With great effort Sam manages to prize the Rover's door open.
He reaches inside and begins to pull the man out -- Sam's sheer ADRENALINE giving him the strength of a YETI.
Sam DRAGS the unconscious man away from the crashed Rover, his body leaving a big TRACK MARK in the gray soil.
Sam takes a second to catch his breath, then leans down and turns the unconscious man onto his back.
He BRUSHES DUST from the glass of the man's HELMET, leans down even closer.
Through his helmet we see a BLOODY and BEARDED SAM.
Sam as we remember him.
The Sam from the opening twenty minutes of the film.
Sam's face as the PANIC, the ALARM, the SHOCK, the REALIZATION hit him like a wrecking ball: this man he has just pulled out of the crashed Rover is himself.
Sam gathers his wits and manages to lift the unconscious Sam up over his shoulder, fireman's lift style, taking him to the parked Rover.
Sam drives the Rover into the Dock, flies out and removes his space helmet, screaming:
SAM Gerty!
SAM Gerty!
SAM Help!
He reaches into the Rover, lifting out the unconscious Sam.
He carries him in both arms, staggering across the dock -- back arched, arms beginning to sag -- and into the corridor.
Sam promptly collapses and DROPS the unconscious Sam onto the floor.
SAM Gerty!
Gerty approaches, gliding along his rail.
Sam is freaking out big time, exhausted, panic-stricken, bewildered.
SAM (CONT'D) I found him outside by the stalled harvester.
SAM (CONT'D) Who is he?
SAM (CONT'D) What the fuck is going on?
A pause.
Gerty literally seems lost for words.
SAM (CONT'D) Gerty!
GERTY We need to get him to the Infirmary.
SAM Not until you tell me who he is!
GERTY Sam, we need to get him to the Infirmary immediately.
Sam SCOOPS the unconscious Sam up off the ground and lifts him towards the INFIRMARY -- staggering -- stumbling -- going:
SAM Who is he!
SAM Who is he!
Sounding like some deranged homeless man.
Gerty gliding alongside him.
Lying in the Infirmary bed, propped on a pillow, is the first Sam, the bearded Sam, who we will now refer to as SAM 1.
He has a wicked black eye and a purple bruise on the right side of his face, looks like he was on the losing end of a brawl.
He has a DRIP stuck in his arm and a tangle of WIRES attached to his bare chest.
A MACHINE is BEEPING away.
Gerty hovers over him, redressing the BANDAGE on Sam 1's left hand, the one he scolded a while back.
Sam 1's eyes pop open, he is awake, staring directly at Gerty.
GERTY Hello Sam.
GERTY How are you feeling?
SAM 1 Where am I?
GERTY The Infirmary.
GERTY You had an accident out by one of the harvesters.
GERTY Do you remember?
For a second this is playing out like the other Infirmary scene.
A case of deja-vu.
Sam 1's eyes twitch as he catalogues through his memory.
Yes he remembers the crash.
He remembers something else, too.
SAM 1 I saw someone out there, Gerty.
GERTY Who did you see, Sam?
Just then Sam 1 notices the other Sam -- the more current, clean-shaven Sam -- who we will now refer to as SAM 2.
He is standing against the wall watching Sam 1.
SAM 1 I saw a girl.
GERTY You saw a girl out by the harvester?
GERTY How is that possible?
Sam 1 continues to stare at Sam 2, hardly believing his eyes.
GERTY (CONT'D) Sam, you suffered a slight concussion in the crash and have incurred minor injuries, but all in all the prognosis is good.
GERTY (CONT'D) I'm happy to see you again.
As he says this Sam 2 crosses slowly from one side of the room to the other, never taking his eyes off Sam 1.
It's like Sam 2 is purposefully keeping his distance, reluctant, afraid even, to approach any closer.
Meanwhile Sam 1 is beginning to look spooked.
SAM 1 Gerty?
GERTY Yes, Sam?
SAM 1 Is there someone in the room with us?
GERTY Yes.
SAM 1 Who is he?
But Sam 1 knows exactly who it is.
He's seen that face every morning of his life in the bathroom mirror.
GERTY Sam, get some sleep.
GERTY You're very tired.
Sam 2 wordlessly walks out of the room.
Sam 1's eyes shift to Gerty, the spooked expression yet to leave his face.
Sam 1 hobbling along, in addition to his facial injuries he injured his knee in the crash and is walking with a slight LIMP.
The camera TRACKING behind Sam 1 as he swings along and stops at
Sam 1 in the doorway, he peers in.
Seated before the TV watching The Newlywed Game, Sam 2.
He turns from the TV and shares a LONG LOOK with Sam 1.
Finally:
SAM 1 Hi.
Sam 2 just nods.
He turns back to the TV.
Sam 1 continues on down the corridor.
Gerty is studying lunar rock samples through a microscope.
Sam 1 enters.
SAM 1 Gerty, what the hell is going on?
SAM 1 Who is that guy in the Rec Room?
SAM 1 Where did he come from?
SAM 1 Why does he look like me?
Sam 1 is perplexed, but not freaking out, not yet anyway.
GERTY Sam, you're out of bed.
SAM 1 Yes, Gerty, I'm out of bed.
SAM 1 Who is the guy in the rec room?
GERTY Sam Bell.
Sam 1 is officially FREAKING OUT now.
SAM 1 Who the fuck is in the rec room, Gerty!?
GERTY You are Sam Bell.
A long pause.
Sam 1 at the point of tears.
GERTY (CONT'D) Sam, what is it?
GERTY (CONT'D) It might help to talk about it.
SAM 1 I don't understand what's happening, Gerty.
SAM 1 I think I may be losing my mind.
GERTY We could run some tests.
GERTY I haven't reported anything to central, Sam.
GERTY They don't know you were recovered alive from the accident.
SAM 1 Recovered alive?
SAM 1 What do you mean?
SAM 1 Why haven't you reported to central?
GERTY I'm here to keep you safe, Sam.
GERTY I want to help you.
GERTY Are you hungry?
Sam 1 merely nods at this, turning and plodding out of the room, seemingly in a DAZE.
Sam 1 comes out of the Monitoring Station, passes the Rec Room without looking in.
Sam 2 has taken over the room.
The same belongings, of course, but there's a different energy.
For one thing it's very untidy; looks like the bedroom of an unruly teenager.
Sam 1 stands in the doorway, taking it in.
Wordlessly Sam 1 begins to tidy the room.
He seems almost RELIEVED to be able to lose himself temporarily in this physical activity -- making the bed, folding clothes, etc.
Sam 2 has stopped watching TV and is now seated at a table playing solitaire.
Sam 1 appears in the doorway.
Sam 2 looks up.
The energy bristling with tension.
SAM 1 You're Sam Bell.
Sam 2 doesn't answer, goes back to his cards.
Sam 1 enters with CAUTION, takes a seat across the room, purposefully keeping his distance.
SAM 1 (CONT'D) I'm Sam Bell, too.
SAM 2 Yeah.
Sam 1 nods.
A beat.
SAM 1 This is fucked up.
SAM 2 Completely.
Sam 2 slapping down cards.
Sam 1 desperately attempts to put together a coherent thought.
SAM 1 Why...
SAM 1 What are you?
For a second we don't think Sam 2 is going to respond.
Then:
SAM 2 I'm a clone, Sam.
SAM 2 Im a fucking clone.
SAM 1 How long have you been here?
SAM 2 About a week.
A beat.
SAM 1 How are you getting on?
SAM 2 How am I getting on?
SAM 2 The company ordered Gerty to lock all the exits.
SAM 2 I haven't been able to do anything for seven days but sit on my ass.
SAM 1 They locked all the exits?
SAM 1 What about the harvesters?
SAM 2 Slowed them down to half speed, apparently.
SAM 2 (CONT'D) And then when I finally trick Gerty into letting me outside I find a clone of myself in a crashed rover.
SAM 2 (CONT'D) How am I getting on?
SAM 2 (CONT'D) Oh I'm loving it.
SAM 1 I'm not a clone.
SAM 2 Ok, Sam.
SAM 2 You're not a clone.
SAM 1 You're the clone.
The two Sam's are inspecting plants.
SAM 2 How long have you been here?
SAM 1 Almost three years.
SAM 2 Hence the Captain's beard.
SAM 1 Right.
SAM 2 I didn't know it could get so thick.
SAM 2 Does it itch?
SAM 1 No, not really.
SAM 1 (CONT'D) Listen, I wanted to say thank- you.
SAM 1 (CONT'D) If it wasn't for you I'd still be out there in the crashed rover.
SAM 1 (CONT'D) You saved my life.
SAM 1 (CONT'D) Will you shake my hand?
Sam 2 hesitates, eventually shakes Sam 1's hand.
Meanwhile Sam 1 is staring at his clone, astonished.
SAM 2 What?
SAM 1 You look just like me.
SAM 1 It's incredible.
SAM 2 Why do I look like you?
SAM 2 Why don't you look like me?
SAM 1 We look like each other, I guess.
This final line intended as a kind of truce.
Sam 1 and Sam 2 are folding the Ping-Pong table down so they can have a real game.
The two Sams playing Ping-Pong.
It's slightly competitive, but mainly they are just happy to take their minds off their situation for half an hour.
SAM 1 Your serve.
SAM 2 Score?
SAM 1 Two points to eighteen.
SAM 2 Fuck!
Sam 2 slaps his paddle on his thigh, his temper creeping up on him.
He catches Sam's eye.
Gets a grip.
Sam 1 is a better player than Sam 2.
He's been up here longer.
He's had more practice.
After the game, the two Sams are sprawled in their seats, sweaty, flushed, energized.
They sit before the model of the town.
SAM 2 How long did it take you to do this?
SAM 1 I don't remember doing all of it.
SAM 1 I remember when I did the church and the Salvation Army.
SAM 1 And a few of the people.
SAM 1 My mind's been acting kind of weird lately, though.
SAM 2 It's Fairfield, right?
SAM 2 There's Town Hall.
SAM 1 Uh-huh.
SAM 1 You know Fairfield?
SAM 1 That's the Baskin&Robbins.
SAM 1 And there's Tess and Eve.
SAM 1 Do you know Tess?
The mention of their wife has stopped the conversation in its tracks.
Sam 2 immediately drops into deep melancholy.
SAM 2 Yes.
SAM 2 I know Tess.
SAM 1 You know about Eve, right?
It is obvious from Sam 2's expression that he doesn't.
SAM 1 (CONT'D) We had a girl.
SAM 2 We did?
SAM 2 She thought she was going to have a boy.
SAM 2 She was so sure.
SAM 2 Eve?
Sam 1 nods.
SAM 1 She's beautiful.
SAM 1 She's really beautiful.
SAM 2 How much did she weigh?
SAM 2 Isn't that what you're supposed to ask, how much did she weigh?
SAM 1 Nine pounds, eleven ounces.
Sam 2 doesn't know what to do with the news: on the one hand he is jubilant, on the other he's a clone, the baby technically isn't even his.
All of a sudden there is a "PING!" From the Intercom speaker:
GERTY'S VOICE Sam, a message has arrived from Central.
Sam 1 and Sam 2 share a look, then together SPRING from their chairs.
Sam 1 and Sam 2 seated before the Comms Unit.
Sam 1 hits the "Play" button.
Overmeyers and Thompson appear on the screen.
OVERMEYERS Greetings, Sam!
THOMPSON How's our Man?
THOMPSON Feeling better?
OVERMEYERS You getting lots of rest?
THOMPSON Yeah, you resting up, Sam?
THOMPSON You'd better be you bastard.
OVERMEYERS Enjoy it while it lasts!
OVERMEYERS We've got good news.
THOMPSON The Jupiter Program had to be put on hiatus, so we've got a few free pairs of hands --
OVERMEYERS We've managed to secure you a Rescue Unit ahead of schedule.
THOMPSON Rescue Unit Eliza.
A SHOT/STILL PHOTO of Rescue Unit ELIZA.
A meaner group of sons-of-bitches you have never seen.
These guys make the rescue team from Apocalypse Now look like The New Kids on the Block.
OVERMEYERS They've been stationed on Goliath 19 for the last couple of months.
THOMPSON Eliza's been in transit for the last day....we expect them to reach you in approximately 14 hours.
OVERMEYERS Commence to jump for joy!
THOMPSON You'll be back to work in no time.
Now back on Overmeyers and Thompson.
OVERMEYERS Eliza is bringing you something special, Sam.
OVERMEYERS Compliments of the company.
THOMPSON A hooker!
OVERMEYERS No not a hooker.
OVERMEYERS What's wrong with you?
OVERMEYERS It's a little something to drink, Sam, that's all, our way of patting you on the back for all that you've been through.
THOMPSON In the meantime, keep resting up, and hang in there.
OVERMEYERS Yeah you hang in there, Sam.
OVERMEYERS Over and out.
And the screen pops to black.
A pause.
For a moment there is silence, neither of the Sams knowing how to react -- going by the message Thompson and Overmeyers don't know anything about there being two Sams on the base now.
SAM 1 They're sending a Rescue Unit?
SAM 1 Why?
SAM 2 To fix the stalled harvester.
SAM 2 They didn't think I was up to it.
SAM 1 Then I'm going back.
Sam 2 gives Sam 1 a perplexed look.
SAM 1 (CONT'D) I've done my three years.
SAM 1 (CONT'D) That's it for me --
Sam 2 is shaking his head slowly.
SAM 1 (CONT'D) What?
SAM 2 Is that what you really think?
SAM 1 I've got a contract --
SAM 2 You're a fucking clone!
SAM 2 You don't have shit!
SAM 2 At once Sam 1 and Sam 2 ROCKET to their feet -- right in each others faces, on the BRINK of BLOWS.
SAM 1 I'm going home!
SAM 2 You're not going anywhere!
SAM 2 Sam 1 turns around, heads out of the room.
SAM 2 Sam 2 STORMS after him, TALKING the whole time --
SAM 2 (CONT'D) You've been up here too long, man!
SAM 2 (CONT'D) You've lost the plot!
SAM 2 (CONT'D) Gerty shuttles along after them.
Sam 1 presses down the corridor, Sam 2 tailing right behind him.
SAM 2 What, you think Tess is back home waiting for you?
SAM 2 What about the original Sam?
SAM 1 I'm the original!
SAM 1 I'm Sam fucking Bell!
SAM 1 Me!
SAM 1 Me!
Sam 1, stress ball pumping away in his hand, spots Gety and angrily faces him.
SAM 1 (CONT'D) Gerty, am I a clone?
Gerty doesn't know which way to look.
GERTY Yes, Sam.
Sam 1 ducks in the Rec Room, Sam 2 in tow.
Sam 1 takes his old seat before the model.
Sam 2 stands over him.
SAM 2 What about the other clones?
"Other clones?" Sam 1 just stares back.
SAM 2 (CONT'D) Yeah, we might not be the first two to be woken up.
SAM 2 (CONT'D) You said that thing had already been started when you got here.
SAM 2 (CONT'D) Well, who started it?
SAM 2 (CONT'D) There might be other clones up here right now.
SAM 2 (CONT'D) Think about it.
SAM 2 (CONT'D) How did I get here so quickly after your crash?
SAM 2 (CONT'D) They didn't ship me in from Central, there wasn't time.
SAM 2 (CONT'D) I must have come from the base.
SAM 1 That's ridiculous.
SAM 1 Impossible.
SAM 1 Why would hey do that?
SAM 2 I bet there's some kind of secret room --
SAM 1 Secret room?
SAM 2 Yeah, secret room, why not?
SAM 1 You're the one who's lost the plot!
SAM 1 I've been here for three years.
SAM 1 I know every inch of this base.
SAM 1 I know how many dust fibres are between those wall panels over there -- why would they do that?!
SAM 2 Look.
SAM 2 It's a company, right?
SAM 2 They have investors, shareholders -- shit like that.
SAM 2 What's cheaper?
SAM 2 Spending time and money training new personnel or just have a couple of spares here to do the job.
SAM 2 If they make it through their contract, great.
SAM 2 If they don't, hallelujah!
SAM 2 No contract completion fees, no retirement package.
SAM 2 Just thaw out the spare, and keep the profits rolling in.
SAM 2 It's the far side of the Moon, Sam!
SAM 2 The tight fuck's haven't even fixed our communications satellite.
SAM 1 Tess would know.
SAM 2 Do you really think they give a shit about us?
SAM 2 They're laughing all the way to the bank!
SAM 1 Tess would know what's going on!
SAM 1 She wouldn't let that happen!
SAM 2 There's some area we don't know about.
SAM 2 I'm going to find it.
Sam 1 shakes his head dismissively, picks up the wooden house, starts whittling.
Meanwhile Sam 2 has left the room.
Sam 2 in the Monitoring Station checking wall panels, reaching his hand inside cubbies and feeling around deep inside, SEARCHING.
Sam 2 moving along the corridor, pressing his ear against panels, tapping with his finger --
Sam 2 RAMPAGES through the Sleeping Quarters, pushes the bed aside, lifts the mattress, goes tearing through a closet, ripping clothes from hangers, checks the back panel.
Sam 2 has come full circle.
He shifts the ping pong table, goes through cabinets in the kitchen, feels inside --
Sam 1 half-whittling, half-watching.
SAM 1 I told you.
SAM 2 Shut-up!
Finally Sam 2 arrives before the model.
SAM 2 (CONT'D) Get out of the way.
SAM 1 Why?
SAM 2 I want to check underneath there.
SAM 1 You're not moving the model.
SAM 2 Get the fuck out of my way!
Sam 1 stands, keeps his ground.
SAM 1 No.
Sam 1 is still holding the knife.
Though he's not about to use it, both Sams are aware that it's there.
Suddenly Sam 2 LUNGES for the knife; an INTENSE STRUGGLE ensues -- TEETH CLENCHED, sputtering BREATHS -- the two Sams less clones right now than ANIMALS.
Sam 2 is able to loosen Sam 1's grip on the knife -- flinging the weapon across the room -- and SWINGS Sam 1 up against the wall.
Now Sam 2 turns to face the model.
Using BOTH HANDS he lifts the model up HIGH over his HEAD and PUSHES the entire thing UPSIDE DOWN.
A massive CRASH.
There is nothing there but the bare table.
Sam 1 comes up behind Sam 2 with his nose SPEWING BLOOD, wraps both arms around Sam 2's neck.
Sam 2 elbows him in the ribs -- a quick, controlled jab -- SPINS around, manages to secure Sam 1 in an arm lock.
But suddenly there is no struggle coming from Sam 1: he's stopped fighting.
Sam 2 removes him from the headlock -- notices his arm is SMUDGED with Sam 1's BLOOD --
SAM 2 You okay?
Sam 1 has remained bent over, like he's cast in stone, blood RAINING from his face and POOLING at his feet thick and fast.
Sam 2 just staring, as freaked as he is baffled.
SAM 2 (CONT'D) I hardly touched you.
Now he tries to help Sam 1.
SAM 2 (CONT'D) Let me see.
Sam 1 tears away from him.
He looks up, his face a MESS of blood -- the WHITES of his eyes unnaturally bright, shouts:
SAM 1 Get off me!
Sam 1 holds his face with his outstretched hand, as if holding it in place -- STUMBLES from the room -- leaking BLOOD the whole way.
A concerned Sam 2 watches him go.
Sam 1 spills in and locks the door.
He RAPIDLY turns on the faucet and cups his hand to transfer water up to his face -- this going on for a few seconds.
MIRROR Sam 1 stares at his reflection in the mirror, holding a MOUND of TOILET PAPER against his NOSE.
MIRROR The blood flow has subsided
MIRROR Suddenly Sam 1 sees the GIRL in the mirror.
MIRROR It gives him a hell of a FRIGHT.
MIRROR The Girl remains in the mirror looking at Sam 1.
MIRROR A neutral expression, impassive.
MIRROR Sam 1 takes a deep breath, lowers the toilet paper from his nose.
SAM 1 Who are you?
SAM 1 No answer.
SAM 1 (CONT'D) Who are you!
SAM 1 (CONT'D) Sam 1 swings around to confront the Girl...but she's not there, she's vanished.
SAM 1 (CONT'D) Her reflection has vanished from the mirror also.
Sam 2 snaps on the TV with the remote, starts watching Laugh-In, turns, sees Sam 1 wander by in the corridor.
Sam 2 considers calling out to him, opts against it, gives the TV his full attention.
Gerty is stationed at the Old Man collecting data.
Sam 1 enters.
GERTY Hello Sam.
SAM 1 Hi Gerty.
SAM 1 Sam 1 sits.
SAM 1 A pause.
SAM 1 Gerty turns from the monitor, faces of with an EXHAUSTED and DRAINED Sam 1.
GERTY Sam, is everything okay?
SAM 1 We had a fight.
SAM 1 Me and the other guy, the other Sam.
SAM 1 We had a fight, Gerty.
SAM 1 He's a maniac.
SAM 1 You know what he did?
SAM 1 He flipped the entire model over.
SAM 1 Do you know how much work I've put into that thing?
GERTY 938 hours.
SAM 1 938 hours, exactly.
SAM 1 Really?
SAM 1 938 hours.
GERTY Approximately.
SAM 1 He scares me, Gerty.
GERTY What is it about Sam that scares you?
SAM 1 He flies off the handle.
SAM 1 I see it now...I see what Tess was talking about.
SAM 1 I've never told you this, Gerty, but she left me.
SAM 1 Tess left me.
SAM 1 For six months.
SAM 1 She moved back in with her parents.
GERTY I know.
SAM 1 Oh...
SAM 1 It was the year before I came in here.
SAM 1 She gave me a second chance.
SAM 1 I promised her I'd change.
GERTY You have changed, Sam.
SAM 1 Yeah, I guess I have.
A beat.
SAM 1 (CONT'D) Gerty, since I've been up here I've sent Tess over a hundred video messages.
SAM 1 (CONT'D) Where did those messages go?
SAM 1 (CONT'D) Did they ever reach her?
A pause.
GERTY Sam, I can only account for what occurs on the base.
SAM 1 What about the messages she sent to me?
A long pause.
Finally Gerty repeats:
GERTY Sam, I can only account for what occurs on the base.
SAM 1 Gerty, am I really a clone?
GERTY Sam, when you first arrived at Selene, there was a small crash.
GERTY You woke up in the infirmary.
GERTY You suffered minor brain damage and memory loss.
GERTY I kept you under observation and ran some tests.
SAM 1 I remember.
GERTY Sam, there was no crash.
GERTY You were being awakened.
GERTY It is standard procedure for all new clones to be given tests to establish mental stability and general physical health.
GERTY Genetic abnormalities and minor duplication errors in the DNA can have considerable impact--
SAM 1 And Tess?
SAM 1 Eve?
GERTY They are memory implants, Sam.
GERTY I'm very sorry.
56. Sam 1 nods at this.
56. He's broken-hearted.
56. He begins to leave.
GERTY (CONT'D) Sam, it's been several hours since your last meal.
GERTY (CONT'D) Can I prepare you something?
SAM 1 No thanks, Gerty.
SAM 1 Sam 1 exits.
Sam 1 enters the sleeping quarters -- straightens the bed and lies down.
He picks up the picture of the pregnant TESS, stares at it long and hard.
The TV is off.
Sam 2 is sitting, arms folded, entrenched in
GLOOM. Sam 1 enters and heads for the kitchen, prepares himself a snack.
GLOOM. Sam 2 is aware that Sam 1 is there, but keeps his eyes focussed forward, as immobile as a statue.
GLOOM. Eventually Sam 1 tentatively comes over.
SAM 1 You okay?
SAM 2 I'm staring into space.
SAM 2 Get it?
SAM 2 Sam 1 does get it.
SAM 2 He smiles to be polite, sits.
SAM 2 (CONT'D) How's the nose?
SAM 1 Better.
SAM 1 A beat.
SAM 2 Listen, I went haywire before.
SAM 2 I lost it.
SAM 2 I'm sorry.
SAM 1 It's okay.
SAM 2 No it's not okay.
SAM 2 I fucked up Fairfield -- your model -- that's unacceptable.
SAM 2 I don't know what's wrong with me.
SAM 2 I've got a temper.
SAM 2 I need to do something about it.
SAM 1 Yes you do.
A pause.
SAM 2 I've been thinking.
SAM 2 That Rescue Unit -- Eliza -- they'll be here in less than fourteen hours.
SAM 2 I don't know about you but I'd like to figure out where we stand before they get here.
SAM 1 Absolutely.
SAM 2 Ostensibly they're coming to deal with the stalled harvester.
SAM 2 We both know that isn't true.
SAM 2 They're coming to dig your body out of that rover.
SAM 2 They think you're in there.
SAM 1 Right.
SAM 2 What'll their reaction be when they find out you survived the crash?
SAM 2 I wasn't supposed to find you.
SAM 2 Lunar instructed Gerty to lock me inside the base for Christ's sake.
A pause.
Sam 1 thinking it over.
SAM 2 (CONT'D) And there's something else.
SAM 2 (CONT'D) Something I haven't told you.
SAM 2 (CONT'D) Right around the time I was awakened...I walked in on Gerty talking to Central.
SAM 2 (CONT'D) He was having a live conversation.
SAM 1 A live conversation?
SAM 2 Yeah.
SAM 1 That's not possible.
SAM 2 No no no, it is possible.
SAM 2 It's possible because I saw it, that's my point.
Sam 2 feels himself losing his temper a little here.
He reigns himself in.
SAM 1 How do you know the conversation was live?
SAM 2 It was a back and forth exchange.
SAM 2 And I saw Thompson and Overmeyers up on the monitor.
SAM 2 I was supposed to be asleep in the Infirmary.
SAM 2 The moment I walked into the comms room Gerty terminated the transmission.
SAM 2 Now I was a little drugged up, granted, but I didn't imagine it.
SAM 1 The communications equipment is damaged -- there was a solar storm --
SAM 2 Tabitha.
SAM 1 Tabitha, right.
SAM 2 Lunar made it up.
SAM 2 Maybe.
SAM 2 I don't know.
SAM 2 Bottom line is they don't want us to be able to contact Earth.
SAM 2 Otherwise why would they have lied to us?
A pause.
Sam 1 staring forward, concentrating.
Sam 2 concentrating on Sam 1.
SAM 1 How are they blocking the live feed?
SAM 1 The base's communications equipment works fine --
SAM 2 Maybe they're not blocking the signal from inside the base.
SAM 1 From where then?
SAM 1 As if reading each others minds, the two Sams' heads turn to the window -- a slow, perfectly synchronized movement.
SAM 1 The lunar landscape, as black and vast as ever.
SAM 1 The view almost cruel in its emptiness.
SAM 1 It's not giving them any answers, not yet.
Sam 1 speeding along in one of the Rovers.
He wears his space suit and resembles a cosmic racing driver -- shifts up a gear, the vehicle flirting with peak speed.
He flies past one of the Harvesters, speaks through a microphone inside his helmet.
SAM 1 Just passing the last of the Harvesters -- looks like John --
SAM 1 All of this against the ROAR of the Rover's engine.
Driving away from base in a different direction, Sam 2.
He also wears a space suit.
He also guns the engine.
He also has a microphone inside his helmet.
The two clones are able to talk back and forth with no delay.
SAM 2 How long until you're out of the base's range?
SAM 2 We INTERCUT between the two Sams in their Rovers.
SAM 1 If I maintain this speed...a minute.
SAM 1 Ninety seconds tops.
SAM 2 You ever been this far out?
SAM 1 No, never.
ANOTHER ANGLE -- SECOND ROVER Viewed from far away, the Rover's speed less impressive from a distance.
As the Sams continue to drive.
SAM 1 You see anything yet?
SAM 2 Nothing.
SAM 2 You?
SAM 1 There isn't shit out here...I feel like I'm about to drive off the end of the world.
SAM 1 It would help if I knew what I was looking for.
SAM 1 Through the glass of Sam 1's helmet we see his FACE suddenly SHIFT.
SAM 1 (CONT'D) Wait a second, wait a second.
SAM 1 (CONT'D) Sam 1 squints and leans closer towards the windshield, like he's trying to decipher a road sign --
SAM 1 (CONT'D) I see something.
SAM 1'S POV About a hundred feet away -- appearing from thin air -- a massive metal pole stretches up into the black sky.
SAM 2 What is it?
SAM 1 Don't know yet.
SAM 1 Sam 1 getting closer.
SAM 1 (CONT'D) Looks like some kind of antenna.
SAM 2 Antenna?
SAM 2 Really?
SAM 2 Hang on, looks like there's one on this side too.
Sam 2 is indeed approaching something similar.
Sam 1 stops his Rover about twenty feet from the Jammer.
He opens the Rover's door and steps out to take a closer look.
Taking in the Jammer and the adjacent Rover.
Sam 1 loping towards the Jammer, seemingly in slow motion.
The JAMMER is GIGANTIC --An intimidating, stark pole stabbed into the lunar landscape, like the worlds biggest caber.
Next to it Sam 1 is tiny, a white dot, as insignificant as a pin prick.
Sam 1 and Sam 2
We cut back and forth between the two Sams as they both investigate the separate but identical-looking Jammers.
SAM 2 (CONT'D) I can just make out the top.
SAM 2 (CONT'D) Must be a hundred feet tall at least.
SAM 2 (CONT'D) It's huge!
SAM 1 Whoever built these things meant business.
SAM 1 They weren't fucking around.
Their voices ENERGIZED -- they are excited to have made this discovery -- they aren't dealing with the negatives yet.
SAM 1 (CONT'D) What do you think?
SAM 2 Its not an antennae, dude.
SAM 2 Its a jammer.
SAM 2 No wonder we can't get a live feed.
SAM 2 These things must be blocking our signal.
Suddenly Sam 1 doubles over.
He vomits thick, viscous blood and sick into his helmet.
Revolting.
The noise is AUDIBLE over the microphone.
SAM 2 (CONT'D) You okay?
SAM 2 (CONT'D) No answer from Sam 1.
SAM 2 (CONT'D) He COLLAPSES backwards onto the ground.
SAM 2 (CONT'D) His chest LURCHES like he's been punched at from the inside -- he spins over onto his front --
SAM 2 (CONT'D) Sam?
SAM 2 (CONT'D) Sam 1 manages to climb to his feet -- heads slowly back to the Rover -- he dips in, closes the door.
SAM 2 (CONT'D) Sam, can you hear me?
SAM 1 Yeah, I hear you.
SAM 1 I'm going to head back to base.
SAM 1 I'm not feeling too good.
SAM 2 I'll stay out here a little longer.
SAM 2 I want to see if there are any more of these things.
SAM 2 Sam 1 pulls a U-turn and begins his journey back to base.
SAM 2 Sam 2 remains out by his Jammer, investigating further.
Sam 1 at the wheel.
He has pulled his helmet off within the safe pocket of the rovers cabin.
He's a grizzly mess of splashed sick and blood all over his face and chest.
Sam 1 screams out with confusion, frustration, terror.
SAM 1 Fuck!
SAM 1 He seizes the steering wheel, shakes it FIERCELY -- beginning to really LOSE IT --
Sam 1 drives his Rover into the Dock -- not with his customary precision -- parks at an angle, grazes the wall.
The Rover's door JERKS opens and Sam 1 steps out unsteadily, his face visibly PALE through the glass of his helmet.
63. He STAGGERS across the dock -- doesn't even close the Rover's door behind him -- heads into the corridor.
Sam 1 goes swerving up the corridor like a drunkard -- BANGING into walls -- he finally reaches the bathroom and ducks in --
Sam 1 sinks to his knees before the toilet bowl.
With great effort he is able to remove his helmet, placing it on the floor next to him.
He stares into the toilet.
For a moment all is calm.
The gentle "ping-ping-ping" of a computer somewhere inside the base.
Sam breathing steadily.
Spots of sweat on his upper lip.
And then he VOMITS.
He vomits LOUD, he vomits VIOLENTLY.
His whole body THRUSTS forward in the process, taught, tense, like a dog being YANKED on a CHAIN.
Sam 1 vomits again.
And again.
And again.
And stops.
ANGLE FROM ABOVE -- SAM 1 Sam 1's vomit is DARK RED -- he's thrown up BLOOD -- but that's not all -- we can clearly see two or three TEETH floating in the vomit --
THE MIRROR Sam 1 stands, moves to the mirror, opening his mouth wide to look for the missing teeth -- he uses his thumbs, shows his gums -- revealing: yes, he's lost at least a couple of teeth.
THE MIRROR He flushes the toilet.
Sam 2 driving along in his Rover.
He comes across another one of these JAMMERS.
He drives right up, ducks down, peering up through the windshield -- this new Jammer is as tall as the others, in fact, it is identical in every way.
How many of these things are there?
64. Sam 2 circles the Jammer in the Rover, drives on.
Sam 1 enters and sits down at The Old Man.
Frantically he starts typing in numbers.
An array of Log Entries appear ON THE SCREEN.
Sam watches one of them.
SAM 1 January 12th, Lunar hour 8:32.
SAM 1 All Harvesters running smoothly
today.
Readouts are as follows: Matthew, 12.7 miles; Mark 11.9 miles...
These are just his log entries.
What's he looking for?
Sam 1 starts scrolling BACK through the log entries, like he's REWINDING chapters on a DVD, showing himself at various stages of his time on Selene -- his beard essentially growing in REVERSE as the messages stretch further back -- eventually Sam 1 is clean shaven --
SAM 1 (CONT'D) Luke, 12.9 miles; John, 11.1 miles...
SAM 1 (CONT'D) Sam 1 keeps typing in numbers.
ON THE SCREEN "RESTRICTED. PASSWORD REQUIRED." No go.
ON THE SCREEN "RESTRICTED. PASSWORD REQUIRED." He tries to hack his way in, but is having no luck.
ON THE SCREEN "RESTRICTED. PASSWORD REQUIRED." One of Gerty's long spindly ARMS slides into the room.
ON THE SCREEN "RESTRICTED. PASSWORD REQUIRED." Sam backs away from the intimidating piece of machinery, but it stops within reach of the computer.
ON THE SCREEN "RESTRICTED. PASSWORD REQUIRED." Sam 1 watches as the arm reaches forward and taps the password in for him.
ON THE SCREEN "RESTRICTED. PASSWORD REQUIRED." It leaves the room the way it came in.
ON THE SCREEN "RESTRICTED. PASSWORD REQUIRED." Sam 1 continues to go further and further back -- and suddenly he POPS up on the screen again -- or is it him?
ON THE SCREEN "RESTRICTED. PASSWORD REQUIRED." -- this Sam up on the screen has stubble -- no beard -- and looks seriously ILL --
ON THE SCREEN "RESTRICTED. PASSWORD REQUIRED." He is barely able to talk -- in fact he's SLURRING --
SAM ...John, 15.1 miles...sorry, I'm not feeling too hot today -- I'm going to have to continue this later --
SAM The SEQUENCE becomes a FAST-PACED and NIGHTMARISH MONTAGE -- continuing to BACKTRACK through the log entries -- showing yet more SAMS -- one has a MOUSTACHE -- one has a SHAVED HEAD -- one has grown out his hair and has a PONY TAIL, we've seen this particular Sam before in an earlier scene.
SAM But all the Sams have one thing in common: towards the latter end of their log entries they all appear to be in very bad physical shape --
SAM 4 ...I've got blood coming out of my nose...
SAM 5 I don't feel too well, Old Man.
SAM 6 My hair's falling out...look it.
SAM 6 Sam 1 searches even DEEPER into the COMPUTER and uncovers yet more footage.
SAM 6 We see the others Sams returning to Earth -- yet they don't seem to go anywhere -- when they blast off the RETURN VEHICLE remains in its bay --
SAM 6 Sam 1 views different Sams blasting back to earth in the return vehicle -- always with the same result -- the return vehicle remaining in its bay, the Sams seemingly VANISHING.
SAM 6 In one particularly GRAINY SEQUENCE Sam 1 views Gerty opening the lid to the cryo pod in the return vehicle and beginning to VACUUM what appears to be DUST or DEBRIS --
SAM 6 Sam 1 understands now that the Return Vehicle is not a spacecraft, but some kind of INCINERATOR.
Sam 1 heads into the Return Vehicle.
Its dominated by the cryo pod, used to hold astronauts in a state of cryogenic sleep on their way back to Earth.
Sam 1 pops open the lid and starts frantically searching the chamber for TRACES of the previous Sams, eventually finding particles of DUST in the cracks --
66. He closes the lid.
66. A video showing a TECHNICIAN in a white lab coat begins to play on a screen aimed at the glass lid of the pod.
66. It's mute, but we can hear a tinny version of the audio coming from the cryo pod.
66. Sam 1 pushes a button on the monitor and we hear the audio properly.
TECHNICIAN ...relax and breathe deeply.
TECHNICIAN The cryo pod is designed to put you into a deep sleep for the duration of your three day return journey back to Earth.
TECHNICIAN As you begin to get sleepy, think about the magnificent job you've done, and how proud your family are of what you've accomplished.
TECHNICIAN Relaxing music begins to play.
TECHNICIAN After a moment the music stops.
TECHNICIAN There is a pause.
TECHNICIAN Then an almighty pulse of light from the cryo pod.
TECHNICIAN This is how Sams past have met their end.
TECHNICIAN Nuked to ash like microwave meals in the cryo pod.
TECHNICIAN Sam 1 inspects the controls of the spacecraft to see if it really is a vehicle -- in the process of his search he finds himself down on his knees checking out the wiring.
TECHNICIAN Suddenly Sam 1's attention is on the floor BENEATH HIM.
TECHNICIAN He appears to be kneeling on some kind of PANEL -- like a tablet in the return vehicle's floor -- he presses his ear against the panel -- KNOCKS --
TECHNICIAN The panel sounds HOLLOW.
CUBBY Sam 1 opens a cubby, swipes something similar to a CROW BAR, heads out of the frame --
RETURN VEHICLE Back in the Return Vehicle, Sam 1 stands over the panel in the floor.
RETURN VEHICLE He uses the CROW BAR to prize the panel open -- this takes an extraordinary effort -- the panel eventually LIFTING like a manhole cover.
RETURN VEHICLE Sam 1 can't believe his eyes.
RETURN VEHICLE At the top of the OPEN PANEL, leading down into darkness...there's A LADDER.
Sam 2 returns from his tour of the perimeter of the base; pulls up alongside Sam 1's Rover, having to compensate for his clone's poor parking job.
Sam 2 exits the Parking Bay and removes his helmet.
Down the corridor he sees Sam 1 standing outside the Return Vehicle: facing him, waiting.
SAM 2 I saw three more of those jammers.
SAM 2 The base is surrounded.
SAM 2 I printed out their coordinates --
SAM 2 Sam 2 begins to remove a piece of paper from his pocket, but suddenly stops.
SAM 2 He can tell by Sam 1's expression that something has happened.
SAM 2 (CONT'D) What?
SAM 2 (CONT'D) What is it?
SAM 1 I found your secret room.
Standing over the Open Panel, an anxious Sam 1 and Sam 2 stare down.
SAM 2 Who goes first?
SAM 2 Sam 1 wordlessly takes the lead, crouching slightly to seize the ladder and twist his body down into the hole.
SAM 2 He begins to DESCEND.
SAM 2 When he is roughly half way down Sam 2 follows.
Sam 1 reaches the bottom of the ladder.
He's in a dark room, a kind of CHAMBER -- if NASA did crypts, it would look like this.
The only light source right now is the coming from the Return Vehicle up above.
Sam 2 hops down beside Sam 1, squints into the darkness.
SAM 2 Is there a light?
SAM 2 Both Sams FUMBLE along opposing walls -- Sam 1 eventually finding a SWITCH, snaps it on.
SAM 2 An array of overhead fluorescent bulbs begin to STUTTER and FLASH before ILLUMINATING the chamber completely --
The two Sams can hardly believe their eyes: stretching back maybe fifty feet are rows and rows of PODS -- like upright glass coffins -- and standing inside each pod, an as-of-yet UNAWAKENED CLONE.
It's like an ENTIRE ARMY of Sam Bells...
Spooky as hell.
For a few moments Sam 1 and 2 are too stunned to speak.
They walk to the end of the chamber and back again, looking at each clone one at a time -- all the clones are bare chested and wear some kind of white cloth to cover their genitals, like a diaper.
Of course they all look the same, that's why they're clones, but this piece of scientific wizardry is mind- boggling to Sam 1 and 2 -- they MARVEL at how each of the clones is identical in every way, and down to the minutest of details -- same length of hair, same skin tone, same fingernails --
SAM 2 (CONT'D) Why are there so many of them?
SAM 1 The cryo pod in the Return Vehicle is an incinerator.
Sam 2 reacts with appropriate shock.
SAM 2 What?
SAM 1 We don't go home.
SAM 1 We're burned to death up there.
SAM 1 Then the company wakes up a new one.
SAM 1 Every three years.
SAM 1 Like clock work.
Sam 2 absorbing this.
Then:
SAM 2 How do you know all this?
SAM 1 I hacked into the Old Man.
SAM 1 Actually, Gerty did.
SAM 1 I saw footage.
SAM 1 You're right, there have been other clones before us.
SAM 2 How many?
SAM 1 Enough.
A pause.
SAM 2 If that Rescue Unit finds the two of us awake at the same time, they'll kill us both for sure.
SAM 2 Sam 1 doesn't respond, he's in his own world.
SAM 2 (CONT'D) What are we going to do?
SAM 2 (CONT'D) All of a sudden Sam 1 makes a beeline for the ladder, starts heading back up.
SAM 2 (CONT'D) Where are you going?
Sam 1 is digging in drawers, removes some equipment, some wires; a radio, a small machine called a VIDEO PHONE, referred to as a VP.
He is watched by Gerty.
GERTY Sam, can I help you with something?
SAM 1 Not now, Gerty, okay?
SAM 1 Gerty begins to slide out of the room.
SAM 1 Sam calls after him.
SAM 1 (CONT'D) Gerty?
SAM 1 (CONT'D) Why did you help me?
SAM 1 (CONT'D) With the password?
SAM 1 (CONT'D) Doesn't that go against your programming or something?
GERTY Helping you is what I do.
GERTY Gerty leaves.
GERTY Sam 1 goes on picking up equipment, shoves it all into a backpack he swiped from a peg.
GERTY Now Sam 2 appears in the doorway.
SAM 2 What's going on?
SAM 1 There's something I've got to do.
70. Sam 1 brushes by Sam 2 on his way out.
Sam 1 marches up to his Rover, tosses in the backpack and dips inside without his helmet, closes the door and backs out into the black day.
Sam 1 at the wheel, flooring the Rover -- he looks possessed, determined -- a man on a mission --
WIDE SHOT Sam's Rover approaches one of the many Jammers that we now know circle the perimeter of the base.
WIDE SHOT Sam 1 stops the Rover on the other side of the Jammer.
WIDE SHOT Here, outside the range of the Jammers, he figures he might be able to get a signal through to Earth.
WIDE SHOT ON SAM as he removes his equipment from the backpack and starts to uncoil wires -- inserts a small BATTERY PACK onto the back of the VP, sits the VP on his lap.
WIDE SHOT The VP resembles a Play Station Portable with its small but nonetheless high-quality screen.
WIDE SHOT Sam isn't sure who to contact at first...finally he enters some numbers from memory.
WIDE SHOT The VP shaking in his hands.
WIDE SHOT He is nervous, scared.
WIDE SHOT He disables the video mode on his end, so he is only sending audio.
WIDE SHOT A moment of silence.
WIDE SHOT The VP seems dead.
SAM 1 Come on...come on...
SAM 1 Then the VP BEEPS -- the monitor BLIPS -- the message seems to have gone through.
SAM 1 And suddenly a GIRL appears on the screen.
SAM 1 Sam 1 can't believe it.
SAM 1 It's the same Girl from his hallucinations.
SAM 1 Same wheat-colored hair.
SAM 1 Same freckles dotting her cheek bones.
SAM 1 Same yellow dress.
SAM 1 The moment Sam 1 sees the Girl he thinks -- naturally --
that he's imagining things again.
But then she speaks:
GIRL Hello?
That's never happened before.
Sam 1 finally manages to respond:
SAM 1 Uh, Bell residence?
The conversation has a very slight delay, maybe a second or two, and the Girl isn't completely clear on the monitor.
We assume that these minor technical glitches are the same on the Girl's end.
The Girl is sweet, chirpy -- nothing like the haunting, ghost-like figure from Sam 1's hallucinations.
GIRL This is the Bell Residence.
SAM 1 I'm trying to reach Tess Bell.
The girl's expression shifts -- now somewhere between melancholy and curiosity --
GIRL I'm sorry, she passed away some years ago.
Sam 1 GASPS.
He literally gasps.
Like someone just plunged a paring knife into his belly.
SAM 1 No...no way.
The girl just stares.
SAM 1 (CONT'D) Tess Bell?
SAM 1 (CONT'D) Are you sure?
GIRL Uh, yeah, I think so.
GIRL I'm her daughter.
GIRL Can I help you?
And astonishingly, the news of Tess's death actually takes a back seat as Sam 1 is forced to confront this new revelation.
The girl is EVE BELL.
Sam 1 is talking to his DAUGHTER.
Sam 1 tilts his head, a smile twitches on his face.
SAM 1 Eve?
Sam 1 can't believe it.
She's beautiful.
She's beautiful.
EVE BELL Yes?
A moment.
Eve looking more closely, trying to decipher Sam 1's face.
Tears glistening in his eyes.
SAM 1 Hi...
SAM 1 Hi.
SAM 1 Eve.
SAM 1 How old are you now?
For a second Eve is embarrassed -- she blushes slightly -- but is still pulled in, intrigued.
EVE BELL I'm fifteen.
EVE BELL Do I know you?
SAM 1 How did mom die, sweetheart?
EVE BELL Uh...
Now Eve is beginning to look spooked.
She turns away from the screen and calls to someone in another room:
EVE BELL (CONT'D) Dad!
And then we hear a voice.
Sam's voice.
SAM'S VOICE What!
EVE BELL Dad, there's someone asking about mom...
Sam's voice sounds CLOSER, more SUCCINCT, as he comes into the room -- but we don't see him yet -- he sounds, OLDER.
SAM'S VOICE Who's asking about mom?
Sam 1 hurriedly shuts off the VP.
He sits there in the Rover, on the Moon, the middle of nowhere -- hundreds and thousands of miles from Earth -- Sam 1 has never felt more alone than he does right now.
The Rover viewed from outside.
We can't hear a thing.
Just the endless and unrelenting MOON SILENCE.
Inside the Rover we are able to make out Sam 1, quivering at the wheel as he sobs.
CLOSE UP -- THE OLD MAN The "ping-ping-ping" of an alarm.
Appearing on The Old Man's monitor: "RESCUE UNIT ELIZA: ARRIVAL TIME, 12 HOURS and 22 MINUTES."
Sam 2 is sitting before the model.
He's flipped it back over and returned it to the table top.
Now he is attempting to fix some of the demolished pieces.
At this moment he's gluing the spire back on the church.
Sam 2 hears a sound from the corridor.
Moments later Sam 1 appears in the doorway wearing the backpack.
Sam 1 is beginning to look alarmingly ILL.
His depleting health has been evident throughout the film, but now it seems to have jumped to a new level.
He watches Sam 2 for a little while.
SAM 1 Want me to help?
SAM 1 Sam 2 shifts over to give Sam 1 the adjacent chair.
SAM 1 Sam 1 walks over, sits down.
SAM 1 Together they work on gluing the church back together.
SAM 1 (CONT'D) Remember that crazy drunk guy who used to hang out by the church?
SAM 2 Barbara Streisand?
SAM 1 He looked like Barbara Streisand.
SAM 1 We used to hide his Bible when he passed out.
SAM 1 Drove the guy nuts.
Sam 2 nods, remembering.
A pause.
SAM 2 How do you carve these things?
SAM 1 Want me to show you?
Sam 2 nods.
Sam 1 picks up a block of wood, grabs an exacto blade.
Demonstrates.
SAM 1 (CONT'D) You need to hold the wood away from you.
SAM 1 (CONT'D) Like this.
SAM 2 You're shaking.
Sam 2 isn't kidding.
Though he is carving the block of wood, Sam 1 can't keep it steady.
SAM 2 (CONT'D) Why are you shaking?
SAM 1 Watch what I'm doing.
SAM 1 You watching?
SAM 2 Yeah.
SAM 1 Now you try.
Sam 1 hands the wood and exacto blade to Sam 2.
Sam 2 attempts to whittle.
He smiles, a little embarrassed.
SAM 2 I suck.
SAM 1 You'll get the hang of it.
SAM 1 You see, that's a little better already.
Suddenly Sam 1 turns around and has a vicious coughing fit.
It actually seems to propel Sam 1 out of his chair and up onto his feet.
Sam 2 watches with concern.
Eventually the coughing subsides.
SAM 2 What's happening to you?
Sam 1 averts his gaze.
SAM 2 (CONT'D) Listen, I realize I've been less than cooperative.
SAM 2 (CONT'D) But I want to change that.
SAM 2 (CONT'D) You and me, we need to work together.
SAM 2 (CONT'D) And that starts with not keeping secrets from each other.
SAM 2 (CONT'D) Now what's going on?
Sam 1 tells the truth.
SAM 1 I think I'm dying.
Sam 2 stares back at him.
SAM 1 (CONT'D) There's blood in everything.
SAM 1 (CONT'D) My urine.
SAM 1 (CONT'D) My vomit.
SAM 1 (CONT'D) I've got a constant headache.
SAM 1 (CONT'D) Dizzy spells.
SAM 1 (CONT'D) The same thing happened to the other clones.
SAM 1 (CONT'D) I saw it when I hacked into the Old Man.
SAM 1 (CONT'D) After three years they all started to get sick.
SAM 1 (CONT'D) Now it's happening to me.
SAM 1 (CONT'D) Well, it's been happening for a while now.
SAM 1 (CONT'D) A couple of weeks.
SAM 2 What do you think it is?
SAM 1 Maybe we don't live that long.
SAM 1 Maybe we start to decompose or something.
SAM 2 Jesus.
Suddenly Sam 1 closes his eyes -- SWAYS -- looks like he's going to pass out.
SAM 2 (CONT'D) Hey hey hey, you okay?
76. Sam 2 stands and moves to Sam 1.
76. Holds him up, checks his temperature.
SAM 2 (CONT'D) Why don't you lie down for a while?
SAM 2 (CONT'D) Take some tranqs.
SAM 2 (CONT'D) Get some sleep.
SAM 1 No tranqs.
SAM 1 I don't think I would ever wake up again.
SAM 1 Sam 1 manages a nod.
SAM 1 Sam 2 hooks his arm around Sam 1's shoulder, helps him from the room.
Sam 2 deposits Sam 1 onto the bed.
He removes Sam 1's backpack, eases a pillow under his head.
Sam 1 is instantly asleep.
Sam 2 pulls the comforter over him.
Sam 2 begins to leave the room, sees Sam 1's backpack on the floor, the VP sticking out of it.
Curious, Sam 2 grabs the VP.
FLASHING on the VP's SCREEN: "Last Transmission: 15:14pm."
Sam 2 enters the Rec Room and shuts the door.
He moves to one of the tables and sits down, POPS on the VP.
ON THE VP MONITOR we begin to re-watch the conversation between Eve Bell and Sam 1.
Obviously we are only seeing Eve's face on the screen, but WE HEAR Sam 1's voice in the background.
SAM 1 Uh, Bell Residence?
EVE This is the Bell residence.
SAM 2 No you didn't...
SAM 1 I'm trying to reach Tess Bell.
EVE I'm sorry, she passed away some years ago.
EVE Sam 2 and Sam 1 have exactly the same reaction at the same time.
SAM 1 SAM 2 No...no way.
SAM 1 SAM 2 No...no way.
SAM 1 Tess Bell?
SAM 1 Are you sure?
EVE Uh, yeah, I think so, I'm her daughter.
EVE Can I help you?
EVE I'm her daughter.
EVE A couple of days ago Sam 2 didn't know he had a daughter, and now he's seeing her as a teenager, a young woman.
EVE He is stunned.
EVE Sam 2 continues to watch the message but we
Sam 1 fast asleep.
Sam 2 watches him from the doorway.
Gerty is just continuing with his tasks like nothing is happening.
Right now he's STACKING ready-meals and miscellaneous lunar snacks into neat columns.
Sam 2 walks up.
SAM 2 Gerty, I need to talk to you.
GERTY Of course, Sam, how can I help?
SAM 2 We found the hidden room.
SAM 2 We know about the other clones.
A long pause.
Then:
GERTY I don't know of a hidden room.
SAM 2 The hidden room under the Return Vehicle, Gerty.
SAM 2 You know what I'm talking about.
SAM 2 We found it on our own.
SAM 2 Lunar doesn't know anything about it.
A beat.
GERTY The lower deck is out of bounds to awakened clones --
SAM 2 Ordinarily, Gerty, but what with there being two of us awake at the same time, and what with the situation being unprecedented, the rules have had to change.
SAM 2 Do you understand?
GERTY I understand the situation is unprecedented.
SAM 2 Good.
SAM 2 Gerty, how long does it take for a clone to wake up?
GERTY A clone is awake the moment his pod is opened.
GERTY But he is not fully conscious for several hours.
A beat.
SAM 2 Gerty, we need to wake up a new clone.
GERTY I am not permitted to do that, Sam.
SAM 2 If we don't wake up another clone me and the other Sam will die.
SAM 2 We'll die, Gerty.
SAM 2 Do you understand?
GERTY Yes.
SAM 2 Do you want me and the other Sam to die?
GERTY That is the last thing I want.
SAM 2 Then you have to wake up a new clone.
SAM 2 Okay, pal?
SAM 2 Sam 2 waits for a response.
SAM 2 And waits.
CLOSE UP -- THE OLD MAN The "ping-ping-ping" of an alarm.
Appearing on The Old Man's monitor: "RESCUE UNIT ELIZA: ARRIVAL TIME, 6 HOURS and 19 MINUTES."
Sam 1 fast asleep in bed.
A stretch of green grass dissected by a dirt path.
A light breeze.
Endless blue sky above.
No clouds.
No visible sun.
Back on the sleeping Sam 1.
Deep breaths.
Eyelids twitching slightly.
In the distance, sitting beneath a tree on a blanket, we see TESS BELL.
She is removing items from a picnic basket.
Sam enters the frame, his back to the camera.
He watches his wife for a few moments, maintaining his distance.
Tess looks up and sees Sam.
She lifts her hand, waves.
ON SAM -- IN THE DREAM Sam's expression is blank at first, but then he smiles at Tess, waves back.
Sam 1's eyes open slowly.
He's awake.
Was his dream a memory?
A premonition?
Or was it simply made up?
ANOTHER ANGLE -- SAM 1 A BLEARY Sam 1 yawns and stretches his arms over his head.
ANOTHER ANGLE -- SAM 1 He reaches across the bed and rips a couple of tissues from a box of Kleenex, blows his nose.
ANOTHER ANGLE -- SAM 1 Afterwards he checks the tissues: a thick RED GOO came out of his nose, the color and consistency of tomato puree.
ANOTHER ANGLE -- SAM 1 Yeah, gross.
ANOTHER ANGLE -- SAM 1 Sam 1 rolls out of bed, plants his feet on the ground.
ANOTHER ANGLE -- SAM 1 The base seems eerily quiet.
ANOTHER ANGLE -- SAM 1 Too quiet.
ANOTHER ANGLE -- SAM 1 Sam 1 stands and crosses to the door.
Sam 1 begins to walk left, down towards the Rec Room and the Monitoring Station, but hesitates -- he turns the other way, towards the Infirmary, heads that way instead.
Lying in one of the Infirmary beds, eyes closed, a NETWORK of WIRES attached to his chest...Sam.
We don't know which Sam it is yet.
He is clean shaven.
He looks like any one of the clones down in the secret chamber; then again he could just as easily be Sam 2.
And that's what Sam 1 naturally assumes as he enters the Infirmary and sees him lying there.
Sam 1 moves closer, curious, until he is standing right at the edge of the bed.
Sam 1 reaches out his hand to wake him up when there is a voice from the doorway behind:
SAM 2 Don't touch him.
81. Our suspicions are now confirmed.
81. The Sam in the Infirmary bed is a new clone.
81. We will call him SAM 3.
SAM 2 (CONT'D) He's not conscious yet.
SAM 2 (CONT'D) Gerty and I only woke him up a few hours ago.
SAM 2 (CONT'D) Sam 1 is not even remotely on the same page.
SAM 1 Why?
Sam 2 puts his finger to his lips.
Then:
SAM 2 Come to the Rec Room.
SAM 2 Sam 2 turns and leaves.
SAM 2 Sam 1 follows slowly, one or two glances at the sleeping clone along the way.
We cut straight to the Rec Room and the conversation between Sam 1 and Sam 2.
SAM 2 When the Rescue Unit arrives they'll expect to find a body in the crashed Rover, right?
SAM 2 We've got our body.
SAM 1 That guy?
SAM 1 Sam 2 nods.
SAM 1 (CONT'D) They'll expect to find a dead body in the crashed Rover.
SAM 2 I know.
SAM 1 You're going to kill him?
SAM 2 Someone's got to pull the short straw here, better someone who's unconscious than you or me.
Sam 1 simply digesting the gravity of Sam 2's plan.
SAM 2 (CONT'D) If we go through with this, I'm going to need your help hauling him out to the crash site.
SAM 1 What about us?
SAM 1 Eliza arrives, finds you and me as the welcome party --
SAM 2 They're not going to find you and me as the welcome party, they're going to find me.
SAM 2 You're going to blast back to Earth before they get here in one of the Helium 3 containers.
SAM 2 You're going home.
Sam 1 wasn't expecting that.
SAM 2 (CONT'D) You've done your three years.
SAM 2 (CONT'D) I can't expect you to stick around.
SAM 2 (CONT'D) Maybe you can meet Eve in person.
A beat.
SAM 2 (CONT'D) I saw the message on the VP.
SAM 2 (CONT'D) Eve is beautiful.
SAM 2 (CONT'D) She looks like her mom.
Sam 1 realizes that Sam 2 knows everything.
There are no secrets between them now.
They both absorb the impact of knowing Tess is dead.
Finally:
SAM 1 How do you think she died?
SAM 2 I don't know.
SAM 2 Jane died of cancer.
SAM 2 I mean, it was in the family.
SAM 2 Who knows?
SAM 2 Or maybe it was an accident?
SAM 2 Could have been a million things.
SAM 1 I wish I'd been there.
SAM 2 Yeah.
SAM 2 Me too.
SAM 2 The two Sams sitting together, UNITED by their grief.
Shot of Selene from across the lunar plane.
The base looks almost peaceful.
No evidence of the DRAMA going on inside.
The two Sams are testing out the CARGO CONTAINER to see if their plan is going to work and Sam 1 can actually fit inside.
These containers were designed to carry cannisters of Helium 3, not to accommodate human beings.
Sam 1 looks in increasingly bad shape.
Blanket draped around his shoulders -- gaunt, bobbing, shivering.
SAM 2 Go for it.
SAM 2 Sam 1 hunches and slowly insinuates himself into the container -- yes, he fits, but it's tight, like really tight -- Sam 1 can anticipate one hell of a stiff neck by the time he steps out onto terra firma.
SAM 2 (CONT'D) Comfy?
SAM 1 No.
SAM 1 Sam 2 chuckles.
SAM 2 But you fit.
SAM 2 That's good.
SAM 2 You fit.
SAM 2 With a HEAVE Sam 2 PULLS Sam 1 from the container.
Gerty is running tests on the unconscious Sam 3.
84. Sam 1 and Sam 2 stand on opposite sides of the room.
84. Both clones seem uneasy.
84. They can't look at each other.
84. They can't look at Sam 3.
84. Their eyes roam every inch of the room just about before finally settling on Gerty.
84. Regardless of Sam 3 being unconscious, are they really going to kill him?
Sam 2 sits at the comms unit recording the message, a smile plastered on his face, as WIDE as it is FAKE.
SAM 2 Sam Bell reporting to Central.
SAM 2 19:14 Pacific Time.
SAM 2 Lunar Day 14.
SAM 2 Evening Overmeyers, evening Thompson!
SAM 2 According to the Old Man Rescue Unit Eliza will be here in just over three hours.
SAM 2 Not a moment too soon!
SAM 2 I never thought I'd say this, but I want to get out there, I want to work.
SAM 2 I feel like a kid who's been grounded.
SAM 2 Looking forward to Eliza straightening everything out and things getting back to normal around here.
SAM 2 Well...that's it.
SAM 2 I'll let you know how it goes.
SAM 2 Over and out, gentlemen.
SAM 2 Sam 2 sends the message, his SMILE instantly COLLAPSING.
SAM 2 He
mutters under his breath:
SAM 2 (CONT'D) Bastards.
Sam 1 is sitting on the edge of his bed holding the photograph of the pregnant Tess -- staring with great concentration -- almost penetrative -- like he's trying to will himself into the photograph.
We find out what's running through his head, cutting to:
Sam 1 has gone back to his dream -- or his vision -- of Tess sitting on the picnic blanket beneath the tree.
85. Sam and Tess continue to wave to one another.
85. Sam hasn't
moved.
Tess calls out:
TESS Come on!
TESS Suddenly we hear a voice.
SAM 2 Sam?
Sam 2 is standing at the door.
Sam 1 looks up at him.
SAM 2 We need to do it.
SAM 2 We need to do it now.
SAM 2 He'll be conscious any minute.
SAM 2 We've been putting it off for long enough.
SAM 2 Sam 1 stares back at Sam 2 with defiance.
SAM 1 We don't have to do anything.
SAM 1 I changed my mind.
SAM 1 Sam 2 isn't following.
SAM 1 (CONT'D) I'm not going back.
SAM 1 (CONT'D) I'm coughing up blood, I'm as white as a ghost.
SAM 1 (CONT'D) I look like I belong in a graveyard.
SAM 1 (CONT'D) I meet Eve now, I'll scare the shit out of her more than anything else.
SAM 1 (CONT'D) D'you think she'll even come within ten feet of me, the way I look?
SAM 2 What are you talking about?
SAM 2 She's your daughter, man!
SAM 2 She's not going to care what you...
SAM 1 She's not!
SAM 1 She's not...
SAM 1 my daughter.
SAM 1 At least, I'm not her father.
SAM 1 Not to her.
SAM 1 Sam 2 keeps quiet.
SAM 1 (CONT'D) I'll put myself in the Rover, I'll be the body -- it was me to begin with anyway, right?
SAM 1 (CONT'D) You go back to Earth.
SAM 1 (CONT'D) You go back.
SAM 1 (CONT'D) You're healthy.
SAM 1 (CONT'D) You've got three years ahead of you.
SAM 1 (CONT'D) You stand a much better chance than I do.
SAM 1 (CONT'D) The other guy....Gerty can get him up to speed...he can be here to meet Eliza when they arrive.
Sam 1 seems to have it all figured out.
Although Sam 2 should in some ways be relieved by Sam 1's decision, he looks closer to distraught.
SAM 2 This is wrong.
SAM 2 What are we supposed to do?
SAM 2 Sit around here and wait to die?
SAM 2 Fuck that!
SAM 1 I don't know.
SAM 1 It's what we were designed to do.
Both Sams struggle to hold in their emotions; Sam 1 morose, Sam 2 angry.
SAM 2 Screw that!
SAM 2 I'll go!
SAM 2 ...And I'm going to find this asshole, Sam Bell, and ask him why the hell he put us through this shit!
Sam 1 looks concerned.
Sam 2 reads his mind.
SAM 2 (CONT'D) I'll be careful.
SAM 2 (CONT'D) I'll keep Eve out of it.
SAM 2 (CONT'D) She wont even know I exist.
Sam 1 smiles wearily, watching his old self.
SAM 1 You're a good guy, Sam.
SAM 2 I might stop shaving; It suits us.
SAM 2 If all our memories are implants, no disrespect, but I think its about time I got some of my own, as well.
SAM 1 Yeah.
SAM 1 You should travel.
SAM 1 I've always wanted to do that.
SAM 2 I'd like that.
Driving to the crash site.
Sam 2 at the wheel, Sam 1 riding shotgun.
Both men staring ahead in silence.
MATTHEW Where all the trouble really started.
MATTHEW Matthew, the stalled Harvester, with the crashed Rover still trapped beneath it.
MATTHEW The crash site is beginning to resemble some old underwater shipwreck.
MATTHEW The Rover enters the frame, beginning to slow down as it approaches the crash site.
MATTHEW Sam 2 rolls the Rover to a standstill about ten feet from the front of the Harvester.
Sam 2 keeps the engine running as Sam 1 takes a handful of TRANQUILIZERS one by one, washing down each pill with a swig from a bottle of water.
Afterwards: a long pause.
The two Sams sitting side by side, staring across the bleak landscape.
Neither of them wants to say good-bye particularly.
SAM 1 Tess came in for the interview, remember?
SAM 1 Sam 2 is nodding away.
SAM 1 Of course he remembers.
SAM 1 (CONT'D) She was so beautiful.
SAM 1 (CONT'D) Even if she wasn't the best candidate, I just knew I had to give her the job.
SAM 1 (CONT'D) I thought she was so sweet.
SAM 1 (CONT'D) And then it was the end of the summer.
SAM 2 She was going back to San Francisco.
SAM 2 (CONT'D) You knew you had to take a chance.
SAM 2 (CONT'D) So you called her.
SAM 2 (CONT'D) You were terrified and wrote that whole speech for her answer machine --
SAM 2 (CONT'D) But I didn't need it because Tess answered the phone.
SAM 2 (CONT'D) And I could tell in her voice as we talked, she was thinking...
SAM 2 (CONT'D) "Why has Sam called me?" "The internship's over, why's he called me at home?" And then I asked her if she was going to Adrian Fiddle's barbecue and...
SAM 2 (CONT'D) Sam 1 has dropped off to sleep.
SAM 2 (CONT'D) The back and forth exchange is now essentially Sam 2's monologue.
SAM 2 (CONT'D) That's when I knew she liked me.
SAM 2 (CONT'D) Because she didn't want to talk to anyone else!
SAM 2 (CONT'D) She'd get up, get some potato salad, go to the bathroom, but she'd always come back.
SAM 2 (CONT'D) And then we kissed.
SAM 2 (CONT'D) On the steps in front of her apartment building.
SAM 2 (CONT'D) Sam 2 finally turns and looks at Sam 1.
SAM 2 (CONT'D) Sam 1's head cocked to one side, eyes closed.
SAM 2 (CONT'D) Sam 2 lifts the helmet off Sam 1's lap -- carefully lowers the helmet onto Sam 1's head.
Sam 2 LOPES towards the crashed rover holding Sam 1 in both arms like a bride.
He places Sam 1 on the ground and PRIZES open the rover door -- he slowly slides Sam 1 inside.
Inside the Rover Sam 1 lies with his head jammed awkwardly against the passenger side door.
At once he looks peaceful and wretchedly uncomfortable.
Sam 2 can barely bring himself to look at Sam 1.
With both hands he FORCES the door CLOSED, pivots around and slowly BOBS back to his rover.
Sam 2 driving back to base.
He has removed his helmet and is brushing tears from his eyes with his glove.
CLOSE UP -- THE OLD MAN The "ping-ping-ping" of an alarm.
Appearing on The Old Man's monitor: "RESCUE UNIT ELIZA: ARRIVAL TIME, 1 HOUR and 40 MINUTES."
Gerty is continuing to run tests on Sam 3.
Sam 2 enters.
He carries the freighted exhaustion of a man who has just completed a long and difficult journey.
SAM 2 How long before he's conscious, Gerty?
GERTY The new clone will be conscious within one hour.
SAM 2 That's good.
SAM 2 That's very good.
GERTY Sam?
GERTY Where is Sam?
SAM 2 He's gone home, Gerty.
SAM 2 Sam 2 leaves.
Sam 2 is loading OXYGEN CANISTERS into the CARGO CONTAINER in preparation for his trip back to Earth.
Sam 2 working FAST, a sense of URGENCY.
Eliza will be there in a mere 90 minutes!
It's coming down to the wire.
Gerty glides in as he works.
GERTY Sam, this is not going to work.
SAM 2 What?
SAM 2 Why not?
90. Now Sam 2 loads food into the cargo container -- moon snacks, rations, etc.
90. -- and bottles of water.
90. His final addition is a 5 kilo load of precious Helium3; A good 15 million dollars worth!
GERTY If the Rescue Unit examine my memory banks they will discover what has taken place over the last week.
GERTY As you know I record everything.
GERTY If they are suspicious, the first thing they will do is search my memory banks, and this would put you in considerable danger.
GERTY Sam 2 straightens up, giving Gerty his full attention now.
GERTY This is serious.
GERTY It could ruin everything.
GERTY The fact that Gerty has brought it up indicates that the robot's loyalties lie ultimately with Sam.
GERTY (CONT'D) I recommend erasing my memory banks.
GERTY (CONT'D) I can reboot myself once you have departed.
SAM 2 So that's what we're going to have to do.
SAM 2 Are you ok with that?
GERTY I'll require your assistance, Sam.
SAM 2 Sure, just let me finish this.
SAM 2 Sam 2 continues his work.
Sam 3 asleep in bed, very close to consciousness.
Sam 1 inside the crashed rover, resembling a wild animal pinned in a trap.
He's still breathing.
SAM 1'S DREAM Once again we see Tess beneath the tree sitting on the blanket.
SAM 1'S DREAM She looks over at Sam, continuing to wave.
TESS Come on, Sam!
TESS Sam Bell!
TESS Come on!
TESS Sam begins to walk towards Tess.
Back on Sam 1.
The glass of his helmet is beginning to MIST with blood.
Sam sees a sliver of the sun as he dawns on his side of the moon.
He closes his eyes for the last time.
Sam 2 stands before Gerty.
SAM 2 I've set your computer to reboot the second I've blasted off.
GERTY Okay, Sam.
SAM 2 Thanks for all your help, Gerty.
SAM 2 I wish I could say I was going to miss you, buddy, but to be honest, I can't wait to get away from here.
GERTY I understand, Sam.
GERTY I hope life is everything you remember it to be.
SAM 2 Thanks.
SAM 2 Are you sure you're going to be ok?
GERTY Of course.
GERTY The new Sam and I will be back to our programming as soon as I have finished rebooting.
SAM 2 Gerty, I'm not programmed.
92. Gerty doesn't respond.
92. Sam 2 seems troubled.
92. Sam 2 leans forward and activates the Memory Erase button.
92. Gerty's READOUT SCREEN begins to TWITCH and FLASH with RANDOM DATA -- then slowly FADES TO BLACK.
92. The Robot has been officially SHUT DOWN.
92. Gerty just stands there.
92. Completely still.
92. As lifeless as a toy.
92. Sam 2 heads out of the room at top speed.
Shot of LUKE, the third of the Harvesters, heading across the lunar plane.
Sam 2 pauses at the window...looking for Eliza.
The Rescue Unit is so close Sam 2 might actually be able to pick out their spacecraft.
And he can!
It's tiny, but nevertheless it's there -- a metallic spacecraft, glinting like a jewel -- and heading steadily towards the Moon.
There isn't a moment to lose.
Sam 2 swings around, heads for the CARGO CONTAINER.
We remain inside the Monitoring Station as Sam 2 climbs inside the Cargo Container He readies himself.
Says a little prayer and...
he cant do it!
Cursing at himself and glancing at the time ticking away before Eliza lands, he jumps back out of the CARGO CONTAINER and runs back into the base.
Sam 2 sits down before the Old Man.
Eliza's imminent arrival causing increased STRESS and TENSION.
Sam 2 takes out the piece of paper on which the COORDINATES of the Jammers are printed out.
He starts to frantically type, altering the PATH of the
Mark trundling along at half-speed.
The Harvester suddenly changes direction -- veering sharply to the left and heading up over a steep slope.
Back on Sam 2 as he RAPIDLY types, makes an error, screams:
SAM 2 Fuck!
SAM 2 Pounds the delete button, continuing to type coordinates into the Old Man -- He's done!
SAM 2 He leaps out of his chair and tears off through the base towards the cargo container.
As Eliza's spacecraft sets its sights on Selene, we see the Cargo Container ROCKET through the sky in the opposite direction.
For a few moments all is quiet inside the base.
The "PING-PING-PING" of the Old Man.
The grinding GURGLE of a computer readout.
This sequence echoes the tour at the very start of the film, but the base has a decidedly different feel to it now.
It's like an abandoned house.
CLOSE UP -- THE OLD MAN On the monitor: "RESCUE UNIT ELIZA: ARRIVED."
A box shaped spacecraft, all menace and angles, slowly DESCENDING towards the lunar surface.
Gerty sits lifeless.
We hear the sounds of pressure doors opening.
Unrecognized voices as the landing crew enters the base, calling for Sam.
Gerty comes to life.
His principal monitor POPS ON and his pincer-like HANDS begin to TWITCH.
His READOUT SCREEN streams with DATA.
Gerty's head begins to swivel left and right -- as if he's awoken with a stiff neck -- eventually he SEES Sam 3, crosses to him.
Just like that, Gerty continues his routine checks of Sam 3 -- studying Sam 3's heartbeat, his brain activity -- the robot literally picking up where he left off.
And then Sam 3's eyes open.
He is awake.
He blinks at Gerty, cloudy, groggy.
SAM 3 Where am I?
GERTY Sam, you're in the Infirmary.
GERTY You had an accident.
GERTY Sam 3 staring ahead, trying to dig up the memory.
GERTY (CONT'D) Do you remember what happened?
SAM 3 No, Gerty.
SAM 3 I don't remember a thing.
SAM 3 We hear heavy footsteps and voices closer now, just outside the infirmary.
A CLOSE UP of MARK as the Harvester churns along and SLAMS into an JAMMER with full force.
The Jammer wobbles unsteadily from the IMPACT, before finally TOPPLING over, HAZING the air with lunar dust.
The Cargo Container BULLETING through space, fire blasting from its jets like the petals of an exotic flower.
Sam 2 is seriously cramped inside one of the Helium 3 containers, about as comfortable as a pony in a dog kennel, but nonetheless WHOOPING RAUCOUSLY at the sheer velocity of the container -- as well as, and perhaps even more so, the fact that he has successfully escaped the base.
He's going home.
Sam 1 has stopped breathing.
The sun shines on his face.
Sam walks towards Tess.
He sits down in front of her on the blanket.
A beautiful picnic is spread out before them.
Tess has never looked so radiant, so beautiful.
Light from the sky pours into her upturned face.
TESS What took you so long?
TESS Sam just smiles back at her.
TESS She hands him a bottle of wine and a corkscrew.
TESS CAMERA PANS UPWARD -- not a cloud in sight -- but we are just able to pick out the chalky outline of the MOON, resembling a white thumb print in the blue sky.
96. HOLD THIS shot of the Moon for a few seconds before we
On the Comms Unit monitor there is a BLAST of STATIC, followed by a FLASHING MESSAGE:
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
