AN EDUCATION
Written by
Nick Hornby
A nice girls' school in a south west London suburb.
We see girls doing what girls did in a nice girls' school in 1962: walking with books on their heads, practising their handwriting, making cakes, playing lacrosse, dancing with each other.
In one of the classrooms, MISS STUBBS, an attractive, bright, animated schoolteacher, is talking to a small group of sixteen-year-old girls.
Some of these girls seem to be daydreaming - looking out of the window, examining their fingernails.
A couple, including a bespectacled girl who looks five years younger than everyone else in the class, write down everything the teacher says.
Only one, JENNY, beautiful and animated, seems to be listening in the spirit in which Miss Stubbs would like her to listen.
She's smiling, eyes shining - she loves Miss Stubbs, and these lessons.
Miss Stubbs asks a question, and Jenny puts up her hand - the only one in the class to do so.
MISS STUBBS Jenny.
MISS STUBBS Again.
JENNY Isn't it because Mr Rochester's blind?
Jenny's bedroom.
Books about ponies, a much loved teddy bear; a cello huge in the small room leans against the wall.
Jenny is bent over a small desk.
Victorian novels, Latin primers and dictionaries teeter in huge towers either side of her.
She stands and stretches as she turns to us.
She kneels and flicks through her half-dozen or so LPs on the floor near a cheap record player - they're all classical, mostly by Elgar, apart from a Juliette Greco record.
This is the one she chooses.
As the music begins, she sings along.
Immediately there is a thumping noise - someone underneath her is banging on the ceiling impatiently.
MAN'S VOICE I don't want to hear any French singing.
MAN'S VOICE French singing wasn't on the syllabus, last time I looked.
Jenny sighs, and reaches for the volume control.
She turns the music down so low that she has to lie down and put her head right next to the Dansette to hear it.
Close on Jenny as she silently mouths the words along with the almost inaudible track.
Jenny, her mother and father are finishing Sunday lunch.
Jenny's father JACK is in his forties, MARJORIE, her mother is slightly younger than Jack, but every bit as middle- aged.
The food is grey and brown, in keeping with the colour scheme of the house.
They aren't talking - they're listening to Mantovani on the radio.
Jenny gets up from the lunch table.
JENNY I've got an English essay to do by tomorrow morning.
JACK I don't want to hear anything through the ceiling this afternoon, apart from the sound of sweat dripping onto textbooks.
JENNY Cello?
JACK No cello.
JENNY I thought we agreed that cello was my interest or hobby?
JACK It's already your interest or hobby.
JACK When they ask you "What's your interest or hobby?" at your Oxford interview, you can say, "Cello".
JACK That wouldn't be a lie.
JACK You don't need to practise a hobby.
JACK A hobby is a hobby.
JENNY Or interest.
JACK You don't need to be good at it.
JACK You just have to be interested in it.
JENNY Can I stop going to the youth orchestra, then?
JACK No.
JACK The orchestra shows you're a joiner-inner.
JACK Universities like joiner-inners.
JENNY Ah.
JENNY Yes.
JENNY But.
JENNY I've already joined in.
JENNY So now I can stop.
JACK Well, if you stop, that shows the opposite, doesn't it?
JACK That shows you're a rebel.
JACK They don't want that at Oxford.
JENNY No.
JENNY They don't want people who think for themselves.
JACK Course they don't.
Jenny with cello sits in the string section.
Everyone is getting settled, tuning up, latecomers still arriving.
Along the row from Jenny, tuning his violin, is a nice- looking boy of her age, GRAHAM, and she waves at him.
Two 13 year old boys sitting between them wave too, parodically, and then blow kisses, much to Graham's embarrassment and Jenny's fury.
The silly boys dissolve in fits of giggles: this is clearly one of the funniest moments of their lives - until one of them farts noisily and, it would appear from all the frantic gesturing, pungently.
The comic value of the fart tops even the comic value of the wave, and they are scarcely able to stay seated, such is their mirth.
Jenny and Graham are talking while he struggles to take his bike out of a bicycle rack slightly unbalanced by the violin strapped to his back.
Graham is nervous, chronically unconfident and shy.
GRAHAM Should I wear, you know, Sunday best?
JENNY You'd better, I'm afraid.
JENNY Just to show my father you're un jeune homme serieux, not a teddy boy.
GRAHAM Oh, God.
JENNY It'll be all right.
JENNY I won't wait.
JENNY It's going to bucket down in a minute.
JENNY I'll see you at the weekend.
Jenny moves as quickly as she can towards the street.
GRAHAM Oh, yes.
GRAHAM Bye.
The two silly boys from before arrive to blow more kisses.
SMALLER BOY 1 Goodbye, darling!
SMALLER BOY 1 See you at the weekend!
SMALLER BOY 1 I will miss you with all of my heart!
Graham blushes.
Jenny swipes the chief offender over the head with her sheet music.
The rain has begun.
Jenny attempts to cover herself.
A mother and two children cross the road in front of her, and a beautiful, sleek red sports car - a Bristol - stops to let them across.
David, possibly in his mid-thirties, dapper, and almost but not quite handsome, is driving the car.
David, distracted, impatient, spots Jenny at the bus stop.
In front of the car a small wellington boot drops off the foot of one of the children,further slowing down their painfully slow progress across the road.
Jenny is wet.
David makes eye contact.
Jenny smiles ruefully, and enchantingly.
David sighs, and then hesitates for a moment.
The window of the Bristol slowly rolls down.
DAVID Hello.
Jenny ignores him.
DAVID Listen.
DAVID If you've got any sense, you wouldn't take a lift from a strange man.
Jenny smiles thinly.
DAVID I am, however, a music lover, and I'm worried about your cello.
DAVID So what I propose is, you put it in the car and walk alongside me.
JENNY How do I know you won't just drive off with the cello?
DAVID Ah.
DAVID Good point.
He winds down the other window and waves on the cars that have stopped behind him.
DAVID How much does a new cello cost?
DAVID Twenty pounds?
DAVID Thirty?
DAVID I don't know.
DAVID Let's say thirty.
He pulls out a wallet, takes out three ten-pound notes, hands them to her.
DAVID There.
DAVID Security.
Jenny laughs and waves the money away.
Later.
The cello is in the back seat of the Bristol.
Jenny is trotting alongside the car, while David leans nonchalantly across the passenger seat to talk to her while driving.
DAVID I'm David, by the way.
She says nothing.
DAVID And you are...?
JENNY Jenny.
JENNY (Beat) I've never seen a car like this before.
JENNY C'est tres chic.
DAVID It's a Bristol.
DAVID Not many of `em made.
Jenny nods, but doesn't know how to respond.
DAVID How did the concert go?
JENNY It was a rehearsal.
JENNY The concert's next Thursday.
DAVID What are you playing?
JENNY Elgar.
DAVID Ah, Elgar.
DAVID I often think it's a shame he spent so much time in Worcester, don't you?
DAVID Worcester's too near Birmingham.
DAVID And you can hear that in the music.
DAVID There's a horrible Brummy accent in there, if you listen hard enough.
Jenny looks at him and smiles.
She hadn't expected him to be able to make Elgar jokes.
DAVID Anyway, I'm not sure Elgar and Jews mix very well.
JENNY I'm not a Jew!
DAVID No.
DAVID I am.
DAVID I wasn't...accusing you.
JENNY Oh.
JENNY (She smiles awkwardly.)
JENNY Can I sit in the car with my cello?
David stops the car.
DAVID Jump in.
Jenny shuts the door and sinks approvingly into the white leather seat.
David regards the dripping girl with amusement.
JENNY It's even nicer on the inside.
DAVID Where to, madam?
Jenny makes a face.
JENNY I only live round the corner.
DAVID What a shame.
DAVID We'll just make it last as long as we can.
The Bristol is crawling along the road at walking pace.
David reaches across Jenny while driving slowly, opens the glove compartment and takes out a packet of cigarettes.
DAVID Smoke?
JENNY I'd better not.
JENNY I'm a bit close to home.
David lights one for himself.
DAVID I suppose cellists must go to a lot of concerts.
JENNY We don't go to any concerts.
JENNY We don't believe in them.
DAVID Oh, they're real.
JENNY So people say.
DAVID Why don't we believe in them?
JENNY I suppose...What would he say?
DAVID Your father, this is?
JENNY Oh, yes.
JENNY He'd say there's no point to them.
JENNY They're just for fun.
JENNY Apart from school concerts, of course, which are no fun at all, so we go to those.
JENNY The proper ones don't help you get on.
DAVID Which of course is what is so wonderful about them.
DAVID Anyway, you'll go one day.
JENNY Yes.
JENNY I will.
JENNY I know.
JENNY Sometimes it seems as though that's what all this slog is for.
JENNY If I get to University, I'm going to read what I want and think about what I want and listen to what I want.
JENNY And I'm going to look at paintings and go to French films and talk to people who know lots about lots.
DAVID Good for you.
DAVID Which University?
JENNY Oxford.
JENNY If I'm lucky.
JENNY Did you go anywhere?
DAVID I studied at what I believe they call the University of Life.
DAVID And I didn't get a very good degree there.
Jenny smiles.
JENNY This is me.
JENNY Thank you.
She gets out of the car with the cello.
David stares after her for a moment, then drives off.
Jenny, her parents and Graham are eating afternoon tea - neat fish-paste sandwiches, Battenberg cake, best china.
MARJORIE How's your mother, Graham?
GRAHAM She's fine, thanks.
GRAHAM She sends her best, by the way.
JACK Where are you applying, Graham?
Jenny looks embarrassed.
She knows what's coming.
GRAHAM I'm not sure yet.
JACK Well, when will you be sure?
JACK You can't let the grass grow under your feet, you know.
JACK Otherwise you'll be at the back of the queue.
JENNY I suppose so.
JENNY I suppose the growing grass would knock you off balance, and then you'd fall over, and by the time you picked yourself up, there'd be a queue.
Her father shoots her a look - is she being cheeky?
GRAHAM I might take a year off.
Jenny winces.
Jack looks at him as if he's just said he'll take all his clothes off.
JACK What for?
GRAHAM I don't know.
GRAHAM Maybe do some travelling, that sort of thing.
JACK Travelling?
JACK What are you, a teddy boy?
Close-up of Jenny - she knows what's coming, and can't bear it.
Beat.
JACK You know she's going to Oxford, don't you?
JACK Oxford.
JACK English.
JACK If we can get her Latin up to scratch.
Jenny sighs.
JACK So she's studying English at Oxford while you're a wandering Jew...
JACK Jenny looks at him curiously.
JACK Graham steels himself to speak.
GRAHAM Mr Mellor...I'm not a teddy boy.
GRAHAM I'm an homme serieux.
GRAHAM Jeune.
GRAHAM An homme jeune serieux homme.
GRAHAM Jenny winces again.
GRAHAM Her father stares at Graham.
GRAHAM Graham blushes.
It's the night of the youth orchestra concert.
Jenny, her mother and father are on their way out of the door.
Jack is carrying the cello.
Jenny is in her school uniform, with her hair scrubbed back in a severe ponytail.
The three of them are flustered.
Jenny opens the front door for her father and he stumbles outside.
JENNY Oh!
She has seen something on the doorstep, and she stoops to pick it up - a large bunch of flowers.
JENNY They're for me!
MARJORIE Who are they from?
MARJORIE Jenny opens the card that's attached to them.
JENNY Gosh.
JENNY Him.
MARJORIE Who's `him'?
JENNY Just...A chap I met.
MARJORIE A chap who sends flowers?
MARJORIE So he's a man-chap?
JENNY Yes, he is, really.
Jack stares at the flowers in disbelief.
The bunch of flowers has created in Jack the kind of panic and fear more typically associated with a biochemical attack.
JACK What's going on here?
MARJORIE Jack,I'm afraid Jenny has been sent some flowers by a chap.
JACK A chap?
JACK What kind of chap?
JACK Who?
JACK Why?
JENNY He's wishing me luck for tonight.
JACK Are you sure that's all he's wishing?
JACK And where does he get the money from?
JENNY He earns it, I expect.
JACK What do you mean, he earns it?
JACK Why isn't he at school?
JACK What does he do?
JENNY Can we just go?
JENNY Otherwise the bunch of good-luck flowers will actually be responsible for me actually missing the concert.
JENNY Which would be ironic, n'est ce pas?
JACK Well I don't like it.
MARJORIE Objection noted.
MARJORIE Jenny?
JENNY Noted.
JACK Ten bob's worth of luck, I reckon.
JACK That's a lot for a schoolgirl.
JACK You can't leave them out here, anyway.
JACK I'd burgle a house that had flowers outside.
JACK They'll think we're made of money.
Jenny sighs, puts them inside the house, shuts the door.
Jenny and two school friends, HATTIE and TINA, are sitting at a table in a typical late-50s coffee bar, sipping cappuccinos.
Jenny is easily the most attractive of the three - and also, we will see, possibly the cleverest.
HATTIE is slower than the other two, and a lot frumpier; TINA is pretty, and sharp rather than clever.
She is also the least middle-class of the three - she's clearly a scholarship girl.
They are all dressed in an unflattering and unambiguous school uniform - no attempts to disguise it with more fashionable accessories.
Jenny is smoking pretentiously, and seems to be practising some kind of pout.
Tina starts to slurp the froth from her cappuccino with a spoon, inelegantly and noisily.
Jenny tuts her disapproval.
Tina sighs, and puts her spoon down.
JENNY The whole point about him is that he doesn't feel.
TINA We still don't have to like him.
JENNY Camus doesn't want you to like him.
JENNY What he's trying to say is that feeling is bourgeois.
JENNY Being engagee is bourgeois.
JENNY His mother dies and he doesn't feel anything.
JENNY He kills this Arab and he doesn't feel anything.
TINA I wouldn't feel anything if my mother died.
TINA Does that make me an existentialist?
JENNY No.
JENNY That just makes you a cow.
HATTIE Une vache.
Laughter.
Jenny, Hattie and Tina emerge from the cafe, talking.
JENNY Well I'm going to be French.
JENNY I'm going to Paris and I'm going to smoke and listen to Jacques Brel and wear black.
JENNY And I won't speak.
JENNY Ever.
JENNY C'est plus chic, comme...
She breaks off.
Parked outside a tobacconists on the other side of the road is the red Bristol.
She looks towards the shop, and David emerges with a copy of the Times and a packet of cigars.
Jenny crosses the road to talk to him while the others watch.
DAVID Hello.
JENNY Hello.
JENNY Thank you.
DAVID How did it go?
JENNY Oh, fine.
JENNY I think.
JENNY I mean, I didn't mess my bit up, anyway.
JENNY And no-one got thrown out of the orchestra afterwards.
DAVID Always the mark of a cultural triumph.
DAVID Listen.
DAVID I'm glad I ran into you.
DAVID What are you doing on Friday?
JENNY Going to school.
DAVID I meant the evening.
JENNY Oh.
JENNY Yes.
JENNY Of course.
JENNY Nothing.
DAVID Because I'm going to listen to some Schubert in St John's, Smith Square.
DAVID My friends Danny and Helen will be going too, so it wouldn't be...I'll tell you what.
DAVID I'll come and pick you up, and if your mother and father disapprove, then you can have the tickets and go with one of them.
DAVID How does that sound?
Jenny doesn't know what to say.
She looks at David, and his eagerness to please seems to convince her.
JENNY Thank you.
JENNY And I'd like you to take me.
JENNY I'd like to go with someone who knows when to clap.
DAVID I usually watch Danny.
DAVID He knows that sort of thing.
Jenny smiles.
DAVID Seven?
DAVID And we'll probably go for a spot of supper afterwards, if you...But if you, if that's not...Well, we can always put you in a taxi.
JENNY Supper.
DAVID If you want.
JENNY The trouble is, we'll already have eaten.
DAVID Well.
DAVID I mean, if you'd like supper, then, perhaps on Friday you could...not eat?
JENNY Oh.
JENNY Yes.
JENNY Of course.
Jenny smiles, and rejoins her friends on the other side of the road.
Tina and Hattie are standing there almost with their mouths open, amazed.
She doesn't say anything and starts to walk on.
TINA I'm sorry.
TINA I just had the strangest dream.
TINA I dreamed you crossed the road and spoke to a handsome man with the most beautiful car I've ever seen.
TINA And then you came back and you didn't mention it.
Jenny smiles enigmatically.
Tina grabs Jenny mock-urgently.
TINA `Oo wazzee?
JENNY Just a man who's been trying to pick me up.
JENNY We're going to a concert on Friday night.
JENNY And then we're having a spot of supper.
TINA A spot of supper?
JENNY You've heard of supper?
HATTIE We've heard of it.
HATTIE But we've never eaten it.
JENNY Neither of you is interested in the concert part, I notice.
HATTIE No.
HATTIE Of course not.
TINA Oh my God!
TINA I've only just realised!
TINA That's what's going to happen to you, isn't it?
TINA Look at her!
TINA Men are going to pick her up in the street and take her out to supper!
HATTIE God, you're right, Tina.
HATTIE I hadn't thought of that.
HATTIE Look at her.
JENNY Don't be so daft.
TINA We're trying to attract the attention of boys.
16. And she's fighting off men.
16. Anyway.
16. You're going to have to tell us more than that.
JENNY Why?
HATTIE Because no man's ever going to ask us out to supper.
HATTIE Not until we're ladies, anyway.
HATTIE You're going to have to tell us everything.
HATTIE Otherwise it's not fair.
JENNY There won't be anything to tell.
TINA Well, make something up, then.
Jenny is dressed up for her evening out.
She looks good, but also stiff, uncomfortable - she's not herself in her dress, which looks too old for her.
Her father is standing in front of her, shouting.
JACK I won't allow it!
JENNY Fine.
JENNY He's quite happy for you to take me.
JACK Right.
JACK I will.
JENNY Good.
JACK Where is it?
JENNY St John's Smith Square.
JACK Where's that?
JENNY I don't know.
JENNY I'm sure we could find out.
Marjorie comes into the room.
MARJORIE It's in Westminster.
MARJORIE Just around the corner from the Abbey.
Jack looks at her as if she'd just given directions to the nearest opium den.
JACK How d'you know that?
MARJORIE I had a life before we were married, you know.
JENNY He soon put a stop to that.
JACK There we are.
JENNY Where are we?
JACK Near Westminster Abbey.
JACK I'm not going all the way over there.
JENNY The trouble is, that's where St John's Smith Square is.
JACK And I've just said.
JACK That's where I'm not going.
JACK There must be something on locally.
JACK Where's the paper?
MARJORIE Jack, she wants to see someone who can play.
MARJORIE She doesn't want to see Sheila Kirkland scratching away.
MARJORIE I'll take her.
JACK And how are you going to get over there?
JACK RAF helicopter?
The doorbell rings.
JENNY That's him.
JENNY Now what?
JACK Oh, bloody hell.
MARJORIE Jack!
Jenny starts towards the door, and then turns.
JENNY Oh, and by the way...David's a Jew.
JENNY A wandering Jew.
JENNY So watch yourself.
She goes to the door.
JACK What's she talking about?
JACK I've never said anything like that in my life!
JACK Anyway, it's just an expression!
JACK I'm not against the Jews!
Jenny comes back in with David, who is dressed stylishly in his early-60s young executive leisurewear - sports jacket, slacks, cashmere sweater.
He looks out of place - he is brighter and brasher than his surroundings, the most colourful thing in the room, and he seems intimidatingly exotic.
David has obviously heard Jack's last line.
DAVID I'm glad to hear it.
DAVID Hello.
DAVID David Goldman.
He offers his hand.
JACK I didn't mean I'm not against you...
JACK Actually, I did mean that, because I'm not, but...
JENNY Dad!
David's hand is still extended - in his confusion and embarrassment, Jack hasn't yet taken it.
He does so now, and shakes it for way too long.
JACK I'm sorry.
JACK What I'm saying is that you're not the sort of, of person I'd be against, if I were the sort of person who was against...people.
JACK You're not an old...Oh, dear.
JACK I'm Jack, and this is Marjorie.
DAVID You didn't tell me you had a sister, Jenny.
General confusion, until David chuckles naughtily.
Marjorie giggles, and then offers her hand.
DAVID You're a lucky man, Jack.
JACK I suppose I am, yes.
They all sit down.
DAVID So.
DAVID Gosh.
DAVID (He looks around approvingly.)
DAVID This is lovely.
Marjorie smiles.
MARJORIE Thank you.
JACK I'm sorry, David.
JACK Can I get you a drink?
DAVID I'd love one, Jack, but we're running a little late.
DAVID If Jenny's ready, perhaps we'll shoot off.
Jenny looks at her father, and takes a calculated gamble.
JENNY Ah.
JENNY Well.
JENNY Dad's got something to tell you.
JACK No, no, nothing...It was more of a question, really.
JACK How would you get to St John's Smith Square from here?
JACK For future reference?
DAVID Oh, it's a pretty straight run, really.
DAVID Up to Hammersmith, take the A4 through Kensington and you're there.
JACK Simple as that.
DAVID Simple as that.
Jack smiles broadly.
MARJORIE So shall I book some tickets for something?
JACK No.
Beat.
JACK Back by ten, please, David.
JACK She's usually in bed by then.
Jenny winces.
DAVID I was hoping Jenny would come with me afterwards to have a bite of supper with my aunt Helen.
Jenny studies him carefully.
Suddenly his friends Danny and Helen have become `Aunt Helen'.
JACK Oh, well, I suppose...
DAVID How about if I promise to have her in by eleven thirty?
JACK Well, it's Friday night.
JACK And if you're going out to the West End...
DAVID Thanks, Jack.
DAVID I appreciate it.
DAVID See you again.
They exchange warm handshakes.
He turns to Marjorie.
Marjorie extends her hand.
David takes it, but kisses it suavely,leaving her a little flustered.
MARJORIE Have a nice time.
JENNY Bye.
Jenny and David leave.
JACK What's that smell?
JACK Has he got perfume on?
MARJORIE It's called after-shave, Jack.
MARJORIE And it makes a change from carbolic soap.
JACK At least there's no confusion, if you smell of carbolic soap.
JACK Marjorie rolls her eyes.
MARJORIE Nobody's ever going to get confused about you, dear.
Jenny and David walk toward the beautiful hall.
Jenny suddenly looks young in the dress that looks too old for her - other adults are milling around outside, and the women don't look like girls dressed up.
David makes for an incredibly glamorous and attractive couple in their late twenties who are waiting outside - DANNY and HELEN.
Helen is as far from anyone's idea of an aunt as one can get.
She's no more beautiful than Jenny, but she's dressed both appropriately and spectacularly, in early-60s, pre-hippy Bohemian gear.
She turns heads in a way that Jenny is not yet able to.
Danny too is attractive, but soberly so.
David and Jenny are, in a way, paler, less striking versions of these two.
DAVID Hello hello.
DAVID Are we late?
HELEN I was hoping we'd miss the beginning, and then it wouldn't be worth going in, and we could go off dancing or something.
DANNY Helen is one of the more reluctant members of tonight's audience.
DANNY Jenny and David laugh politely.
DAVID Jenny, these are my friends Helen and Danny.
Jenny shakes hands with the two of them.
They both give her fascinated and clearly appraising looks.
They have heard about her.
DAVID (CONT'D) Shall we?
They walk into the hall.
It's a beautiful hall - Jenny is dazzled by the surroundings and the company.
She's particularly bowled over by Helen.
HELEN Look.
HELEN We can leave our coats over there.
HELEN I want to get rid of this.
She nods at the coat she's carrying.
Jenny looks thrilled at the prospect of spending a couple of minutes with Helen.
Danny hands Helen his coat, without saying anything.
The girls walk over to another reception table a few yards away, behind which is a cloakroom.
A lady is exchanging overcoats for tickets.
Almost involuntarily, Jenny touches the sleeve of Helen's velvety jacket.
She stops herself.
Helen notices.
JENNY I'm so sorry.
HELEN That's OK.
HELEN It's nice, isn't it?
JENNY It's beautiful.
JENNY Where did it come from?
HELEN Oh, South Ken somewhere.
Helen looks at Jenny's outfit, her frumpy `smart' dress, apparently wanting to return the compliment.
HELEN This is...Well, it's good for this sort of concert, isn't it?
JENNY Thank you.
Helen is now at the front of the queue, and hands her coat over imperiously.
HELEN We should go shopping together one day, if you want.
She takes a ticket from the cloakroom lady.
JENNY That would be nice.
JENNY But South Ken...
JENNY C'est beaucoup trop cher pour moi.
They stare at each other.
Helen is bewildered, Jenny embarrassed.
HELEN Sorry?
JENNY I just said....It was too expensive for me.
HELEN No you didn't.
HELEN You said something completely different.
JENNY I just...Well, I said it in French.
HELEN In French?
HELEN Why?
Jenny feels humiliated; she is yet to realise what we can see - that Helen is simply very dim.
JENNY I don't know.
Jenny looks away.
Helen stares at her.
The performance bell rings, and they make their way back to the men.
To Jenny's surprise and pleasure, Helen links arms with her as they walk.
HELEN Anyway.
HELEN It's too expensive for me, too.
HELEN We don't have to worry about that.
HELEN If you want something in South Ken, get David to take you shopping.
JENNY Why on earth would he want to take me shopping?
Helen makes a knowing face.
David, Jenny, Danny and Helen in a row in the middle of the auditorium, watching the stage and listening to the music.
Jenny can't concentrate - she's too excited by the occasion and the company.
Jenny sneaks a glance at Helen, who stares straight ahead, unblinking and enigmatic.
David is smiling, as if he's trying to communicate enjoyment; Danny's eyes flicker across the stage - he understands the music, its component parts, which musicians are contributing what.
Jenny takes it all in.
Jenny, David, Danny and Helen emerge with the other concert- goers.
DAVID I booked a table at Juliette's.
DAVID Will that kill the mood, do you think?
HELEN Oh, I do hope so.
The others laugh.
HELEN I always think I'm going to my own funeral when I listen to classical music.
HELEN (Tentatively) That was classical, wasn't it?
DANNY Yes.
DANNY Very classical.
DANNY As classical as you can get.
Helen looks pleased.
DAVID Juliette's it is, then.
DAVID Heaven forbid that we should end the evening reflecting on our own mortality.
Jenny smiles in delight.
She's never met people like this.
A singer in the Julie London mould is singing `I'm In The Mood For Love' while cigarette girls and glamorous waitresses patrol the tables.
Jenny is sitting with the others at a table in the club, eating and talking.
She looks about twelve, but she's thrilled to be there.
We know now that her life can never be the same again, and there will be no going back to fish- paste sandwiches with spotty Graham.
DAVID Have you never heard "Chante Francoise Sagan"?
Jenny shakes her head.
Her eyes are wide - she's clearly awe-struck.
David offers her a cigarette - a Gitane - which she takes.
He lights it for her while she's listening.
DANNY Oh, it's wonderful.
JENNY I've only got....Well, I think it's just called `Juliette Greco'.
JENNY The one with the eyes on the sleeve.
JENNY I saved up and got my French conversation teacher to bring it back after Christmas.
HELEN You've got a French conversation teacher?
JENNY Yes.
HELEN Is that why you suddenly speak French for no reason?
DANNY You must have seen her sing?
Jenny shakes her head again and smiles.
Where would she have seen Juliette Greco?
Danny, meanwhile, is baffled.
Who hasn't seen Juliette Greco?
DAVID She's marvellous.
DANNY But you should see her in Paris, not here.
DANNY David will take you.
DAVID I'd love to.
DAVID You'd fit right in.
HELEN Better than here, really.
DAVID It's wonderful to find a young person who wants to know things.
DAVID There's so much I want you to see.
They sip their drinks pensively, possibly to allow time for the double-entendre to disappear into the smoke.
DAVID Are you still all right to come and have a look at that Pembroke Villas place with me on Friday, Danny?
DANNY Oh.
DANNY No.
DANNY Can't do it.
DANNY There's a Burne-Jones coming up at Christie's on Friday.
DANNY And I want it.
JENNY You're thinking of buying a Burne- Jones?
JENNY A real one?
DANNY I just have a feeling that the pre-Raphaelites are going to take off.
JENNY I love the pre-Raphaelites.
DAVID Do you?
JENNY Yes, of course.
JENNY Rossetti and Burne-Jones, anyway.
JENNY Not Holman Hunt, so much.
JENNY He's so garish.
Danny looks at her.
There's clearly more to this schoolgirl than he thought.
DAVID Absolutely!
DAVID Why don't we all go to the auction?
DAVID Wouldn't that be fun?
JENNY An auction.
JENNY Gosh.
JENNY How exciting.
DANNY Next Friday morning.
DANNY David will pick you up.
JENNY Oh.
JENNY Friday.
DANNY You're busy?
JENNY Well.
JENNY Yes.
She doesn't want to explain why.
DANNY Tant pis.
Helen looks at him aghast.
Why has he started speaking French?
DAVID Are you sure you're busy?
Jenny hesitates.
JENNY No.
JENNY I'm sure I could....re- arrange.
JENNY That would be lovely.
Jenny lets herself quietly into the house.
The hallway is dark, but she can hear noises from the kitchen.
She pokes her head round the corner, and sees her mother doing the washing-up.
MARJORIE Oh, hello, love.
MARJORIE Did you have a nice time?
JENNY What are you doing?
MARJORIE I can't get this casserole dish clean.
MARJORIE We had hot-pot tonight, and it's all burnt round...
JENNY It's twenty-five to twelve.
JENNY We finish tea at seven.
MARJORIE I know what the time is.
MARJORIE How was your evening?
JENNY It was...It was the best night of my life.
MARJORIE And he took you home in his car?
MARJORIE Right to the door?
Jenny looks at her.
She doesn't seem to have heard what Jenny has just said.
JENNY Goodnight, Mum.
MARJORIE And I'm glad you enjoyed the concert.
Jenny, Hattie and Tina are sitting on their desks, waiting for the start of a lesson.
Nine or ten classmates are scattered around the room, talking distractedly, but Jenny's group is much more animated: Tina and Hattie are leaning forward, listening to Jenny, their eyes bright.
They are clearly awestruck by Jenny's tales of the outside world.
TINA I'm not interested in Schubert.
TINA I want to know what else was on the programme.
Laughter.
JENNY There was nothing like that.
JENNY He was the perfect gentleman.
JENNY He just said he wanted to take me places and show me things.
TINA Things plural?
TINA Oh my Gawd!
More laughter.
The English teacher, MISS STUBBS, young and fresh-faced and lively-looking, enters, and picks up on the excitement of Jenny's coterie.
MISS STUBBS I knew that in the end `Jane Eyre' would work its magic upon you.
MISS STUBBS I'm presuming that's what you're so animated about.
The students start to sit down at desks in a more conventional arrangement.
JENNY Of course.
TINA `Jane Eyre' and Jenny's new boyfriend.
JENNY He's not my "new boyfriend".
JENNY God.
TINA It's true.
TINA He's more a man- friend, isn't he?
TINA He's got a sports-car, Miss Stubbs.
MISS STUBBS Ah.
MISS STUBBS A Mr Rochester figure.
TINA I think he must be as blind as Mr Rochester.
Laughter.
Jenny pulls a face at her.
MISS STUBBS Is there no end to your thirst for literary understanding, Jenny?
MISS STUBBS As you may have noticed, I'm attempting to turn the subject away from Jenny's lurid love-life and towards the matter in hand.
She starts to hand out essays.
MISS STUBBS And it's quite clear on this evidence that most of you know much too much about the former, and almost nothing about the latter.
MISS STUBBS Reluctantly I must concede that Jenny is evidently an expert on both matters.
MISS STUBBS Excellent as always, Jenny.
Miss Stubbs slaps an essay down on Jenny's desk.
We can see that it's marked `A+'.
Jenny at her desk, working.
She puts down her pen, distracted.
David sitting in his Bristol, waiting.
We see the Bristol parked outside, and Jenny walking towards it, a small figure in a large playground.
She's clearly just changed out of her school uniform, and she's making last-minute adjustments to her civvies.
A teacher walks towards her, and Jenny almost freezes - but the teacher merely smiles pleasantly and walks past.
Jenny keeps walking at a measured pace for a moment and then breaks into a run.
Jenny and David are driving along a North Kensington street.
JENNY How do you know Danny?
David is distracted.
He's driving slowly, apparently looking for an address.
DAVID Oh, you know.
DAVID We kept bumping into each other, and we became pals, and we've ended up doing a bit of work together, when it suits us.
JENNY What kind of work?
DAVID Property.
DAVID A bit of art dealing.
DAVID Some buying and selling.
DAVID This and that...
He stops the car.
DAVID I'll be two seconds.
He gets out of the car, and Jenny watches him as he crosses the road.
Outside a dilapidated house covered in scaffolding stands a large West Indian family, mother, father, three or four small children and a dog.
They are surrounded by what appears to be all their worldly goods.
David squats down on his haunches, talks to the kids, tousles the hair of the smallest.
Then he takes out a bunch of keys and ushers the family down the path.
He unlocks the door and leads them inside.
In an upper window of the house, we see an old lady peering down anxiously.
David emerges from the house, jangling his keys.
Jenny opens the glove compartment where David keeps his cigarettes, takes out the packet, removes one for herself, offers the packet to David as he gets into the car.
He lights them both.
DAVID I'm sorry about that.
JENNY How do you know those, those ...Negro people?
DAVID They're clients.
JENNY Clients?
DAVID Jenny darling, even schwarzers have to live somewhere.
DAVID And it's not as if they can rent off their own kind, is it?
He starts the car and drives off.
JENNY I'm not sure I quite understand what you do.
DAVID You don't need to.
DAVID It's too boring.
DAVID All you need to know is that I work in property so that I can take you to nice places.
Jenny's POV of the black family in one window, and the little old lady disappearing from another.
Danny intent on a catalogue, Helen gazing dreamily into space, as David and Jenny push their way through the crowded auction room.
The auctioneer burbles on in the background.
DANNY You nearly missed it.
Jenny is in awe of rich London in all its finery.
The auctioneer clears his throat.
AUCTIONEER We turn to lot 41, The Tree of Forgiveness, by Sir Edward Burne- Jones.
AUCTIONEER This is a rare opportunity to purchase a key work of the Pre- Raphaelite movement.
AUCTIONEER Who will start me off at five hundred guineas?
Jenny glances at Danny.
He makes no move at this price.
Neither does anyone else.
He's poised and listening hard.
AUCTIONEER Two hundred?
A middle-aged lady, the epitome of the middle-aged contemporary Sloane, twin-set, pearls and a lot of face powder, raises her hand.
AUCTIONEER Thank you, madam.
AUCTIONEER Three hundred?
A man raises his hand.
AUCTIONEER Do I hear three-fifty?
The middle -aged Sloane nods.
AUCTIONEER Over to you sir.
AUCTIONEER Four hundred guineas?
AUCTIONEER Thank you.
AUCTIONEER Four hundred and fifty...
Danny continues to sit there.
Jenny is confused.
The middle- aged lady bids four-fifty.
David, sitting next to Danny, whispers something to him.
Danny nods.
DAVID Your turn.
Jenny looks at him.
AUCTIONEER No further bids?
DAVID Quick!
Jenny raises her hand high, just as she'd do at school.
AUCTIONEER Five hundred guineas from the very eager new bidder.
People look round and smile when they see who has come in.
Jenny blushes, but stares fixedly ahead.
AUCTIONEER Five hundred and fifty, madam?
AUCTIONEER Thank you.
Jenny looks at David, who nods.
AUCTIONEER Six hundred guineas.
Jenny gestures more economically.
AUCTIONEER Six-fifty?
AUCTIONEER Thank you, madam.
AUCTIONEER Seven hundred...
Jenny is almost insouciant this time.
AUCTIONEER Seven hundred?
The middle-aged lady shakes her head and purses her lips.
when asked if she wants to bid ?700.
AUCTIONEER Sold for six hundred and fifty guineas.
AUCTIONEER Thank you.
He brings down the gavel, and a murmur goes around the room.
Jenny is excited and giggly.
David pats her on the back.
AUCTIONEER Your name, please?
Jenny looks at Danny.
DANNY You know who you are.
JENNY Jenny Mellor.
DANNY I know who you are, too.
DANNY Tell him.
JENNY Jenny Mellor.
DANNY Thank you.
DANNY Couldn't have bought it without you.
DAVID Well done.
DAVID A nerveless performance.
Jenny beams.
She's thrilled.
A beautiful, large, airy sitting room in the first-floor flat in Bedford Square.
The flat is unusually and tastefully decorated, opulent and indicative of Bohemian good taste.
Jenny is sipping a glass of white wine and walking around the room enthralled, looking at Danny's existing Pre-Raphaelite art collection; he has three or four big paintings proudly displayed on his walls.
Danny is talking her through them while Helen and David, sitting on the sofa, watch - David proudly, Helen impassively.
DANNY A couple of years ago you could pick these up for fifty quid, you know.
DANNY Nobody was interested.
JENNY Really?
JENNY Fifty pounds?
JENNY I don't believe you.
Suddenly Jenny sees a cello in the corner of the room - a good one.
JENNY That's not a Lockey-Hill!
DANNY There aren't many people who come in here and say that.
HELEN Certainly not me.
JENNY It's beautiful.
JENNY Do you play?
DANNY I used to.
DANNY I vowed to myself that one day I'd own one of these.
DANNY And now I own one and never touch it.
DANNY It's vulgar to put it on show, really.
HELEN Give it to Jenny.
DANNY That would be even more vulgar.
DAVID Play for us, Jenny.
JENNY Gosh, no.
JENNY One day.
JENNY When I'm good enough for it.
DAVID She's good enough now.
JENNY Oh, David.
JENNY You've never heard me.
Danny stands up and stretches.
DAVID I shall come to hear you in St John's Smith Square.
DAVID Or in Oxford, when you get there.
DANNY We should all go and spend a weekend in Oxford.
DANNY Straw boaters, punting, cream teas, antiquarian bookshops.
DANNY Bit of business, if we can find it.
DANNY What about next weekend?
DAVID/HELEN Yes!
JENNY A weekend away?
JENNY I wouldn't be allowed to do that.
They all look at her.
DAVID I'll find a way.
DAVID I'll talk to them.
JENNY Who?
DAVID Jack and Marjorie.
JENNY About what?
DAVID Oxford.
Jenny hoots with derision.
JENNY You're going to ask my father if I can go away with you for the weekend?
JENNY He'd have you arrested.
DAVID We'll see.
JENNY I'll bet you you can't do it.
DAVID How much?
DANNY Be careful, Jenny.
DANNY You don't know who you're dealing with.
JENNY Half-a-crown.
DAVID You're on.
They shake hands.
Jenny suddenly notice the clock on Danny's mantelpiece.
JENNY Mon dieu!
JENNY You must take me back to school.
JENNY And I've got to change back into my uniform.
There is a silence.
Danny and David make momentary eye contact - they are clearly contemplating the erotic possibilities of Jenny's last sentence.
Helen notices.
HELEN Oh, behave yourselves.
Jenny looks at them all, mystified.
Jenny is in her Latin class, waiting for the lesson to begin.
Tina and Hattie aren't with her, and she sits on her own -the atmosphere of the class is very different from Miss Stubbs' English lessons.
The girls are different, more serious, less fun, and the atmosphere is more sombre.
The teacher, MRS WILSON, is older, plainer, stricter.
She pulls some papers out of her bag.
MRS WILSON Test results for the Virgil translation.
MRS WILSON We will start from the bottom...Patricia.
Jenny puffs out her cheeks.
She's not last.
MRS WILSON (CONT'D) Absent.
MRS WILSON (CONT'D) Margaret.
MRS WILSON (CONT'D) 48%.
MRS WILSON (CONT'D) Jenny...
Jenny winces.
MRS WILSON (CONT'D) 52%.
MRS WILSON (CONT'D) That would just about scrape a pass in the exam proper.
MRS WILSON (CONT'D) Not good enough for Oxford candidates.
Jenny and her mother are sitting on the sofa, staring into space, clearly upset.
On the coffee table in front of them is the test, covered in red ink.
They hear a key in the lock, and they look at each other.
MARJORIE I'll talk to him.
Jack enters, back from work.
He's wearing a suit and carrying a battered briefcase.
He looks at them, and then notices the essay on the table.
JACK It's her Latin, isn't it?
MARJORIE The test didn't...Well, it didn't go as well as we'd hoped.
He picks up the paper.
And you still say I shouldn't go down there and have it out with whatsername?
The Latin teacher?
Because this is hopeless.
How are you going to "have it out" with her?
What are you going to do?
Shout at her until she decides I'm much cleverer than she thinks?
Everyone's doing their best, Jack.
What if their best isn't good enough, though, eh?
What do we do then?
We don't go to Oxford.
Any of us.
Not even you, Dad.
Perhaps it's all a waste of time and money anyway.
You don't mean that.
Well, what's she going to do with an English degree?
And if she's going to spend three years playing that bloody cello and talking in French to beatniks, then I'm throwing good money after bad.
I suppose she might meet a nice lawyer.
But she could do that at a dinner dance tomorrow.
Oh, yes.
That's the whole point of an Oxford education.
It's the expensive alternative to a dinner dance.
What about private tuition?
Is anyone listening to me?
How much is that going to cost me?
MARJORIE Five shillings an hour.
MARJORIE Maybe a little more for A-level.
JACK Five bob!
JACK But...
JACK we could spend five bob on this and five bob on that, and before we know it that's our savings down the drain.
MARJORIE And what else are we spending five bob on?
MARJORIE What else are we spending sixpence on?
JACK Oh, nothing.
JACK (He gestures round the room.)
JACK It's all free.
JACK That vase was free.
MARJORIE It was, actually.
MARJORIE It was a present from Auntie Vi.
JACK That chair was free.
JACK The sofa.
JACK We don't have to pay for anything.
JACK And even if we did, we don't have to work for it.
JACK That's the beauty of life, Jenny.
JACK Everything's free.
JACK Grows on trees.
JACK Wonderful, isn't it?
JACK (He warms to his theme, and grows progressively more berserk.)
JACK We've got a lovely Oxford tree in the garden, lucky for you, so that's Oxford taken care of.
JACK And a whole orchard of school trees, so that's all free.
JACK I'm sure there are some private tuition trees out there.
JACK I'll go and have a look.
He stands up.
MARJORIE Jack...
JACK No, no, won't take me a minute.
JACK I think I saw some at the back there, right next to the pocket money tree.
JACK I'll just nip out and check, see that they're doing all right.
40. Don't want anyone climbing over the wall and scrumping, do we?
40. And you never know.
40. Maybe there'll be a man with deep pockets growing out there.
40. Because God knows we need to find you one.
40. He leaves the room, apparently to look in the garden for the mythical trees.
Jenny and her mother move to the window to watch him talking theatrically to the trees.
Jenny, Hattie and Tina are walking back from school.
TINA You could always go to secretarial college with Hattie.
JENNY Oh, thanks.
HATTIE Charming!
JENNY Oh, no.
JENNY Hattie and Tina follow Jenny's eyes, and they see Graham coming towards them pushing his bike, red-faced, trousers tucked into socks.
GRAHAM Hello.
JENNY Oh.
JENNY Graham.
JENNY Hello.
GRAHAM I haven't seen you for ages....It all went wrong, didn't it?
GRAHAM The tea-party, I mean.
GRAHAM Was it because of the year off?
JENNY No, no.
JENNY It's just...I've got so much to do if I'm going to get the grades I need.
TINA Yes.
TINA She's got no time for boys.
Hattie and Tina try to suppress giggles.
Graham turns an even brighter shade of red.
Hattie and Tina enter the coffee bar.
Jenny feels sorry for him, is on the verge of inviting him to join them...And changes her mind.
JENNY Bye, Graham.
She follows the girls inside.
Jenny is deep in her schoolwork.
She has a Latin vocabulary propped open on the window-ledge.
She looks at it, walks away, mutters to herself, attempting to memorize.
Her concentration is broken by a sudden gale of laughter from downstairs.
She stands outside the living room for a moment, listening.
She hears a man's voice that does not belong to her father, and then more laughter from her father and mother.
David is in the middle of demonstrating his ability to mimic all of the Goons.
Jack and Marjorie are laughing so hard that they can hardly see - they certainly miss Jenny's entrance.
JENNY Hello.
JACK Oh.
JACK Hello.
JACK David does the most brilliant Bluebottle, Jenny.
JACK Actually, he can do all the Goons.
DAVID I don't think I'm very good at Eccles.
JACK Oh, no, you've got him...
JENNY But what's he doing here?
DAVID I wasn't going to disturb you.
DAVID I knew you'd have your nose to the grindstone.
JENNY You came to see Mum and Dad?
JACK Is that so hard to imagine?
Jenny spies an open bottle of wine on the coffee-table.
JENNY And you're drinking?
JENNY But it's not Christmas!
JACK Hark at her!
JACK Makes us sound as though we've signed the pledge.
JACK You don't know everything about us, you know.
JACK We had a life before you came along.
JENNY Yes, that's true.
JENNY I'm only going on what I've seen over the last sixteen years.
MARJORIE I'm trying to think what you missed.
MARJORIE Nothing much comes to mind.
JACK They can't stand to see me enjoying myself.
JENNY Anyway.
JENNY Would you excuse me?
JENNY I've got a huge pile of Latin translation to do.
JACK You didn't tell me David went to Oxford.
Jenny looks at David, who stares back at her straight- faced.
JENNY No.
JENNY I didn't.
For all the good it did me.
What did you read?
Oh, English.
Just like every other semi-employed layabout in London.
(marvelling at the coincidence) English!
Which college?
Merton.
Isn't that funny?
Extraordinary.
I was just telling Jack that I'm going back next weekend.
I go and see my old professor every now and again.
That's what you need, Jenny.
Someone on the inside track.
It's not always what you know, is it, David?
Too true.
And Clive would love Jenny.
Have you ever come across Clive Lewis?
Dad has never come across anyone.
I just thought he might know some of the books.
Dad has never read any books.
What's he written?
DAVID He wrote a children's book called `The Lion, The Witch and The Wardrobe' that did very well, I believe.
MARJORIE CS Lewis?
MARJORIE That's the Clive you're talking about?
DAVID Well, to us he was just the old codger who taught Medieval literature.
DAVID But I came to know him very well.
DAVID We just...got along, do you know what I mean?
Everyone murmurs their comprehension.
MARJORIE Jenny used to love those books.
DAVID Gosh.
DAVID That dates me.
DAVID He was writing them when I was there.
JENNY I'd love to meet him.
There is a pause.
Jack and Marjorie look at the floor.
Somehow, David has manoeuvred a situation where, effectively, he is the one being asked.
DAVID I'm sorry.
DAVID I'm being slow on the uptake.
DAVID Would Jenny like to come with me at the weekend?
JACK Well, I don't know about this weekend.
JACK But one day, yes, thank you.
JENNY How often do you see him?
DAVID Oh, once every couple of years.
DAVID But next time, eh?
JENNY Hopefully I'll be there by then.
JENNY So that won't be much use.
JACK Well, I suppose...Would she have to stay the night?
DAVID Well, I wouldn't want to drive back after one of those Oxford dinners.
Jack chuckles knowingly.
DAVID Clive will get her a room in college.
DAVID That's easy enough.
MARJORIE Sounds like too good an opportunity to pass up.
JENNY Please, Daddy.
JENNY It would be so helpful to know something about the place.
JACK Would it be a bother to you, David?
DAVID I'd be delighted.
Jack, Marjorie and Jenny all beam.
Jenny opens the door for David.
JENNY That was scandalous.
DAVID I told you.
DAVID You owe me half-a- crown.
He kisses her on the cheek and disappears into the night.
David and Danny are waiting for the girls to get ready.
Danny is sitting sprawled in an armchair; David is pacing up and down.
DAVID Come on!
An ornate four-poster bed occupies most of the space in the room.
Helen is doing something to Jenny, but we can't see what.
HELEN Nearly ready!
DAVID How can they only be nearly ready?
DANNY I wouldn't be surprised if three of them come out, you know.
DANNY That's the only explanation.
DANNY They're making themselves a friend.
DANNY LADIES!
DANNY Let's go.
DANNY Please.
Jenny is wearing a floaty print dress that she has borrowed from Helen, and there are lots of other beautiful clothes strewn about the place.
Jenny is sitting at the dressing table, being made up by Helen.
Jenny looks three or four years older, more sophisticated....more like Helen.
She can't believe it.
She looks in the mirror, and for a moment, she forgets to breathe.
HELEN There.
HELEN You'll do.
HELEN You can keep it.
HELEN I can only wear so many every day.
Jenny emerges from her reverie.
JENNY Really?
JENNY Thank you.
HELEN What about tonight?
HELEN Will you be needing a nightie?
HELEN Or not?
JENNY A nightie?
Jenny suddenly understands what Helen means.
JENNY Will we be sharing bedrooms?
HELEN You're not sleeping with him?
JENNY No.
JENNY I'm...No.
HELEN Good for you.
JENNY Really?
JENNY Do you think so?
HELEN You're only sixteen.
HELEN And you don't want to get into the family way, do you?
JENNY Oh, I'd make sure that didn't happen.
JENNY I'm going to do it when I'm seventeen.
JENNY On my seventeenth birthday, hopefully.
HELEN With David?
Jenny pauses.
JENNY Well...Golly.
JENNY I suppose it will be with David, won't it?
HELEN When's your birthday?
JENNY April.
HELEN Oh, he'll be around in April.
HELEN If that's what you want.
HELEN Anyway.
HELEN I'll find you a nightie.
Jenny stares at herself in the mirror again.
The girls emerge.
Both men are entranced by Jenny's transformation.
David can't take his eyes off her.
DANNY Shall, we, ah...
DANNY Make a move?
He gets to his feet.
The Bristol on the country road to Oxford.
The Bristol drives through Oxford.
Jenny catches a quick glimpse of a dreaming spire.
DANNY Imagine spending three years here.
HELEN I know.
She shudders, as if someone has walked over her grave.
JENNY Can we stop?
DAVID Maybe later.
DAVID There are a couple of things we have to do.
Jenny and Helen in the back seat of the car, which is parked outside a house in the back streets of Oxford.
There's no sign of Danny and David.
Jenny sighs impatiently.
HELEN Oh, it's always like this.
HELEN There are millions of places I've never seen because I've been stuck in here.
JENNY You never get out?
HELEN There's never anywhere to go in the places they stop.
Jenny looks out of the window.
This is self-evidently true.
Helen and Danny, Jenny and David are standing in a quiet, old-fashioned pub, warming themselves at an open fire.
David has a pen in his hand, and he's holding a book - `The Lion, The Witch and the Wardrobe'.
DAVID So.
DAVID Now.Is he Clive, do you think?
DAVID Or CS?
HELEN I'm confused now.
HELEN I thought you'd made him up?
DANNY No, we...Never mind.
David walks over to the nearest table and writes in the book.
DAVID There.
He stands up, hands the book to Jenny.
JENNY "To dear Jenny.
JENNY With the pleasure of meeting you.
JENNY Come and see me again soon.
JENNY Clive."
HELEN Dirty old man.
Laughter.
He takes a long drink from his pint of bitter.
A group of students enter, all carrying musical instruments.
They stand at the bar, waiting to be served.
Jenny stares at them with longing - she wants to be one of them.
Helen, meanwhile, stares at them as if they were aliens.
HELEN Why are university girls so strange-looking?
Helen's right.
The girls in the group are all bespectacled and frumpy.
The others laugh.
HELEN It's true.
HELEN And they can't all have started off that way, can they?
HELEN Most girls aren't ugly, but most girl students are.
HELEN So there must be something about those places that, you know, makes you fat, or spotty, or short-sighted.
DAVID Well, if you look at it that way...I mean, that's proper scientific analysis.
DAVID And you can't argue with science.
Helen looks pleased.
HELEN I'm still not quite clear on what you want to do when you get here.
JENNY I want to read English.
HELEN Books?
JENNY Sorry?
HELEN You want to read English books?
JENNY Oh.
JENNY Yes.
JENNY Reading English is just another way of saying...
DANNY I wouldn't worry, Jenny.
DANNY You're wasting your breath.
DAVID Anyway, tomorrow we'll try to get more of a feel for the place.
DANNY Absolutely.
DANNY This would be a good place to do a little business.
David catches Jenny's eye.
This isn't what he meant by "getting a feel for the place."
DANNY All those little old ladies wandering around...I'll bet this place is rife with stats.
JENNY Please explain what stats are.
JENNY You're always going on about them.
DAVID All right.
DAVID Think of a number.
DAVID Now think about the most boring lesson you've ever had at school.
51. Now double it.
51. Done?
51. Doubled?
51. Now multiply it by the number you first thought of, and there you are.
51. That's the official boredom content of stats.
Jenny laughs.
A rather grotty and certainly unromantic B&B bedroom - so unromantic, in fact, that it even has the same fusty curtains from Jenny's sitting room.
David is in bed, his hands behind his head, waiting for Jenny.
As far as we can tell - he's wrapped up in the sheets quite tightly - he's in his underwear.
The bedroom is lit unromantically by the 40-watt overhead light.
Jenny comes into the room wearing one of Helen's nightdresses, a glamorous satiny item quite inappropriate for the occasion or the surroundings.
She looks nervous.
JENNY We've got exactly the same curtains at home.
DAVID Let's not talk about curtains.
DAVID You look beautiful.
DAVID You really are a princess.
Jenny was about to get into bed, but his tone makes her pause at the edge of the bed.
JENNY There's something you should know, David.
JENNY I'm...Well, I'm a virgin.
JENNY And I want to stay that way until I'm seventeen.
DAVID I think that's good.
DAVID I think that's right.
DAVID And for your seventeenth birthday I'm going to take you to Paris or Rome or Florence and make you feel like the most beautiful princess in the kingdom of love.
DAVID But we can still be romantic, can't we?
JENNY Well, yes.
JENNY Of course we can.
JENNY If it doesn't mean...
DAVID Minnie....
JENNY Is that me?
DAVID Yes.
DAVID You're my Minnie Mouse, and I'm your bubbalub.
JENNY Oh.
JENNY If that's what..
DAVID Minnie.
JENNY Yes, David?
DAVID Bubbalub...
JENNY Sorry.
JENNY Yes, bubbalub?
DAVID Would you mind if I had a look at what might one day be mine?
DAVID Just a peek?
His eyes stray to her breasts.
Jenny stares at him.
JENNY You just want to see them?
DAVID I just want to see them.
Jenny, flustered and nervous, looks at her nightgown - she doesn't know what to do.
DAVID Let it fall from your shoulders.
She does so.
He stares.
DAVID Thank you.
He sits up, and lovingly lifts the straps back up.
He smiles at her.
Relieved, she smiles back.
The Bristol, containing David and Jenny in the front seats and Danny and Helen in the back, passing through a pretty Oxfordshire village.
It pulls up outside a country cottage with a `FOR SALE' sign outside.
DAVID Might be worth a look.
The four get out of the car, and Jenny follows David and Danny to the front door of the house.
Helen hangs back.
HELEN Jenny...
HELEN Jenny turns around.
JENNY Aren't you coming?
HELEN We don't go in.
JENNY What are you talking about?
DANNY Helen will look after you.
DANNY Go and find a nice cup of tea somewhere.
DANNY Jenny is mystified.
JENNY I don't need looking after, thank you very much.
JENNY David, I want to see...
JENNY David ignores her.
DANNY I'm not going to tell you a second time.
DANNY Now.
DANNY Run along.
Helen and Jenny waiting for the boys.
Helen is blithe, chatty; Jenny has a face like thunder.
HELEN They won't be long.
HELEN Either way.
JENNY "Either way"?
HELEN Sometimes they find something, sometimes they don't.
In the distance, David is waving at them urgently.
HELEN And when they do find something, we usually have to leave quite quickly.
HELEN They can be a bit naughty, sometimes.
HELEN Anyway.
HELEN It's nice to have company.
HELEN I'm usually outside on my own.
Jenny stares at Helen.
She's beginning to realise who she is dealing with.
An old picture of some kind is wedged between Helen and Jenny on the back seat.
Jenny, furious, is staring out of the window.
Helen attempts to peer around the partition, but settles for a wave.
HELEN Coo-ee.
HELEN Jenny.
Jenny doesn't respond.
DANNY Sorry about being a little brisk back there, Jenny.
DANNY We have our way of doing things.
DANNY Silly, really.
Still no response.
DAVID Oh, come on, Jenny.
DAVID Let's not spoil things.
JENNY Me?
JENNY I'm spoiling things?
DAVID I think there must be some kind of misunderstanding.
Jenny shakes her head bitterly.
They continue driving in silence.
The Bristol pulls up outside Danny's Bedford Square flat.
DANNY Who wants to come up for a drink?
DAVID Jenny?
JENNY No thanks.
JENNY You go.
JENNY I'll find my own way home.
Jenny gets out of the car and starts up the road.
David gets out and starts to chase after her.
DAVID Jenny!
He catches up with her in the street.
DAVID It was an old map.
DAVID A Speed.
DAVID It was cooped up in that miserable little cottage, and she didn't even know what it was.
DAVID What a waste!
DAVID It shouldn't spend its life on a wall in wherever the hell we are.
DAVID It should be with us.
DAVID We know how to look after it properly.
DAVID We liberated it.
Jenny snorts derisively.
JENNY Liberated!
JENNY That's one word for it.
DAVID Oh, don't be bourgeois, Jenny.
DAVID You're better than that.
DAVID I know you have fun with us.
DAVID I can see it.
DAVID You drink everything I put in front of you down in one, every last drop, and then you slam your glass down on the bar and ask for more, and it's wonderful.
DAVID We're not clever like you, so we have to be clever in other ways, because if we weren't, there would be no fun.
56. We have to be clever with maps, and..and..
56. You want to know what stats are?
56. Stats are old ladies who are scared of coloured people.
56. So I move the coloureds in and the old ladies move out and I buy their flats cheap.
56. That's what I do.
56. So now you know.
Jenny nods reluctantly.
DAVID And if you don't like it, then I will understand, and you can go back to Twickenham and listen to the Home Service and do your Latin homework.
DAVID But these weekends, and the restaurants and the concerts..They don't grow on trees.
Jenny looks at him, startled.
Trees again?
DAVID Do you understand?
DAVID Of course you do.
DAVID This is who we are, Jenny.
He turns to face her and holds out his hand.
On Jenny: is she in or out?
Jenny takes his hand.
David pulls her towards him, holds her around the waist and begins to dance with her.
Further up the pavement, Helen and Danny watch, laughing.
David pulls up in the Bristol outside Jenny's house, and they sit in the dark for a little while.
DAVID I suppose you have homework to do.
JENNY Gosh.
JENNY Yes.
JENNY Loads.
JENNY (Beat) Thank you.
JENNY I had a nice time.
DAVID Really?
DAVID In spite of the, the incident?
DAVID With the map?
JENNY As you said in the car, it was a misunderstanding.
DAVID Exactly.
DAVID A muddle.
JENNY You have no idea how boring everything was before I met you.
DAVID I hope that there's something more than excitement to our relationship.
JENNY Excitement's a lot, when you're at school and you live in Twickenham.
DAVID You know what I'm trying to say.
DAVID I want you to like me for who I am, not just what I can do for you.
JENNY But that is who you are.
JENNY I've never met anyone like you.
JENNY Action is character, our English teacher says.
DAVID What does that mean?
JENNY I think it means that if we never did anything, we wouldn't be anybody.
JENNY And I never did anything before I met you.
JENNY And sometimes I think no-one's ever done anything in this stupid country, apart from you.
DAVID That's a good place to end the weekend.
DAVID I'll give you a tinkle.
JENNY Thank you.
They look at each other.
David is clearly smitten.
He moves towards her.
He wants to kiss her, but he doesn't want to frighten her - in the end, Jenny makes it easy for him and moves towards him.
They kiss gently and tenderly.
Flustered, Jenny breaks it off, gets out of the car and goes inside while David watches.
Jenny enters the sitting room with her overnight bag to find the radio on, her father reading the paper and her mother knitting.
When Jenny comes in, Jack beams.
He has clearly turned some kind of corner.
JACK Here she is!
JACK The wanderer returns!
MARJORIE Did you have a nice time?
JENNY Lovely, thank you.
JACK Was he nice to you?
Jenny unzips her bag and pulls out her copy of the book.
She hands it to her father.
JENNY Look inside.
Jack examines the inscription.
JACK Well I never.
JACK Look at this, Marjorie.
He hands it to her.
She examines it reverently.
MARJORIE "Clive"...Lucky girl.
MARJORIE What was he like?
JENNY He was just...normal.
JENNY Kind.
MARJORIE And did he show you round?
JENNY Oh, he was busy.
JENNY David did, though.
MARJORIE What did you think?
JENNY Beautiful.
MARJORIE Did it make you want to work harder?
JACK Never a dull moment with David, is there?
JACK If it's not concerts, it's famous authors.
JACK Bit different from that lad you brought home for tea, isn't he?
MARJORIE David's a lot older than Graham.
JACK Graham could live to be two hundred, and he still wouldn't be swanning around with famous authors.
JACK Hasn't got it in him.
JENNY He might become a famous author, for all you know.
JACK Being one isn't the same as knowing one, is it?
JACK Anyone can be one.
JACK But if you move in those circles...
JENNY What?
JACK Well, it says something about you, doesn't it?
JACK It says you're going places.
JACK It says you're well connected.
JACK He's an impressive young man, that David.
JACK I like him more and more.
MARJORIE Well, they say opposites attract, don't they?
MARJORIE I wouldn't have thought he was your sort.
JACK He wasn't.
JACK And now he is.
MARJORIE Is that how you feel, Jenny?
JENNY I feel....I Feel I should do my homework.
She leaves the room.
Marjorie watches her go thoughtfully.
A group of girls cross-country running.
Jenny and her friends are at the back of the group, and the gym teacher , jogging backwards, gesticulates at them to get a move on.
GYM TEACHER Ladies, please.
GYM TEACHER Christmas is coming.
They put on enough of a spurt to satisfy her, and then immediately stop when the teacher is no longer watching.
Seeing an attractive bench, they sit down.
From somewhere under a skirt, Jenny produces a packet of exotic-looking cigarettes and offers them around.
HATTIE What the hell are those?
JENNY Russian Sobranies.
Hattie and Tina make snooty faces.
Jenny takes a cigarette.
The others follow suit.
Jenny lights them, and they all grimace.
The contrast between the sophisticated cigarettes, and the unsophisticated smokers and context is pronounced.
HATTIE Where did they come from?
TINA She might have bought them from the Savoy, or Claridges, or the opera, or some fancy nightclub.
TINA Who knows, with Jenny?
JENNY Paris.
JENNY You can't buy them here.
TINA You never bought them yourself?
JENNY No.
JENNY I never.
TINA Shut up, you stuck-up cow.
JENNY But I'll bring you some back, if you want.
TINA You're joking.
JENNY Non.
HATTIE He's taking you to Paris?
JENNY Oui.
HATTIE This term?
JENNY Peut-etre.
TINA Isn't it your birthday next Tuesday?
JENNY Might be.
The two friends shriek and jump up and down.
HATTIE Oh, my God!
HATTIE Your birthday!
TINA I wouldn't like to be you.
TINA All those dinners you've had off him.
TINA Ouch.
JENNY You have such a Victorian attitude to sex, you two.
TINA Oh, sorry, Dr Kinsey.
TINA We're not all as experienced as you.
TINA I mean, you've done it...(She counts on her fingers) I make it never!
TINA Can that be right?
HATTIE But your parents are just going to let you swan off like that?
JENNY They don't know yet.
JENNY David's got a plan, he says.
JENNY He usually has something up his sleeve.
TINA I've noticed that.
TINA What did he tell them when you had your weekend in Oxford?
JENNY Oh, it was....(She changes her mind) David went to Oxford.
JENNY Merton.
JENNY English.
JENNY And he offered to show me round.
HATTIE So you have a good-looking boyfriend with pots of money, brains and a nice car.
JENNY Apparently I do.
Tina makes a bitter face.
TINA And they tell us there's a God.
Laughter.
Jenny glances off into the distance, and spots a portly middle-aged woman heading in their direction.
JENNY Sod.
JENNY Miss Davies.
They stand up, grind their Sobranies into the mud, kick them under the bench, and set off at a brisk trot.
The Sobranie stubs come to rest near a pile of dog poo.
Breakfast on Jenny's birthday.
Jenny is at the table buttering toast.
Jack is reading the paper, Marjorie is cooking him eggs and bacon.
JACK Is David taking you somewhere special tonight?
JENNY Not that I know of.
MARJORIE I've asked Graham round for tea and birthday cake.
JENNY Graham?
JACK What do we want him round for?
MARJORIE I happened to be talking to his mother about something, and...
JENNY What did you happen to be talking to her about?
MARJORIE I thought it would be nice.
JENNY What if David turns up?
MARJORIE Are we expecting David to turn up?
Jenny shrugs.
JACK It might not be a bad thing if he did.
MARJORIE Really?
JACK Well, if you think about it, there's more than one way of skinning a cat.
JENNY And who's the skinned cat, in this enchanting image?
JENNY Me?
JACK No, of course...
JENNY I have an education to pursue.
Graham, Jenny and her father are at the dinner table, sitting in the dark.
Marjorie kicks the door open with her foot and comes in holding a birthday cake with seventeen candles burning on it.
She puts it down carefully on the table.
JACK Blow them out, then, before the whole place burns down.
JACK Jenny closes her eyes, makes her wish, blows out her candles.
JACK Her father and mother both look at her, apparently attempting to read her mind.
JACK Jack gets up to turn the lights on.
JACK We can see that by Jenny's side are two unopened, carefully-wrapped presents, both exactly the same size - clearly books.
MARJORIE Who'd like a piece?
MARJORIE In truth, the cake is a rather sorry and unappetising specimen.
MARJORIE There isn't enough icing on the top.
MARJORIE She cuts a couple of slices which immediately collapse.
GRAHAM Never mind.
GRAHAM I'll have one of those.
JACK Come on.
JACK Presents.
JACK Without any real enthusiasm, Jenny opens the first one of the two, from her mum and dad.
JACK It's a Latin dictionary.
JENNY Oh.
JENNY Thank you.
JENNY I needed a new one.
GRAHAM Oh dear.
GRAHAM The doorbell rings.
GRAHAM Jenny perks up.
GRAHAM Jack goes to answer it, and immediately the house is energised: it's David.
Jack answers the door to David.
JACK Good grief.
JACK You won't believe this, Jenny.
JACK Did you leave anything in the shop?
JACK David enters.
JACK You can hardly see him for all the parcels and flowers he's carrying.
DAVID It's a special day.
He and Jenny exchange a glance.
Jack comes in behind him.
JACK She's a special girl.
DAVID Oh, I know it.
DAVID (to Graham) Hello, young man.
JENNY This is Graham.
DAVID Graham, a pleasure.
DAVID I'm David.
They shake hands.
Graham suddenly looks five years younger.
JACK Makes your dictionary look a bit feeble, eh Graham?
Graham looks pained.
Marjorie notices.
MARJORIE And ours too, come to that.
JACK Well, we're not the ones trying to impress her.
JENNY Clearly.
JACK David, what can I get you to drink?
DAVID What's everybody else having?
DAVID What have you got there, Graham?
JACK I've given him a glass of pop.
GRAHAM I'd better be going I have a stack of homework to do.
Graham says his goodbyes.
He tries to catch Jenny's eye, but she looks away.
Marjorie shows him to the door.
DAVID Yes.
DAVID Well.
DAVID You can put the pop away now.
DAVID What is there for the grown-ups?
JACK A glass of something warming?
DAVID You know me so well.
Hearty laughter from the two men.
JENNY Can I open anything yet?
Marjorie comes back into the room.
MARJORIE Wait for me.
DAVID Before you start on that little lot , I have a surprise.
DAVID Next weekend, we're all going to Chez Georges to celebrate Jenny's birthday.
JACK Lovely.
DAVID Chez Georges is in the Boulevard St Germain.
DAVID In Paris.
Jenny giggles her delight.
Jack's smile is a little more forced.
JACK How d'you mean, Paris?
JENNY You know the one, Dad.
JACK But..We haven't got any French money.
JACK And I'm not sure...I just don't think it would agree with me.
JENNY Dad!
JACK They don't like us, the French, you know.
JACK John Sutton at work went once.
JACK They were very rude to him.
JACK I'm not sure I'd like that.
Jenny understands David's ploy perfectly, and the role she must play.
Her eyes fill with tears.
Jack notices.
JACK I don't want to spoil anyone's fun, but...It's not for me, Europe.
JACK We'll go another time.
JENNY You've just said you don't like Europe.
JENNY What's going to change?
JENNY It'll have to be Europe, won't it?
JENNY Because it isn't going to be you.
MARJORIE I can take her.
JACK To France?
JACK And leave me here on my own?
JENNY Oh, for God's sake.
Jack looks cornered.
He needs to find a way out.
DAVID Listen, I'm really sorry to have caused all this to-do.
DAVID I just thought it might be nice.
DAVID But I'll go with Aunt Helen and Uncle Daniel.
DAVID They can have your tickets.
Jack looks at him.
JACK Aunt Helen?
JACK The one who went to the concert with you?
DAVID Yes, that's the one.
JACK Well, there we are.
DAVID Where are we?
JACK Aunt Helen!
JACK Don't you see?
JACK If Aunt Helen's going to be there...
DAVID Of course!
JACK I didn't want to put a spoke in anyone's wheels.
JACK But if you look at it from my angle...A bachelor, taking my daughter off to Paris...
DAVID Oh, impossible.
DAVID I hadn't thought it through properly.
DAVID I do apologise, Jack.
DAVID Would you prefer it if Helen took Jenny on her own?
DAVID I don't mind.
DAVID I've been to Paris before.
JACK Oh, I couldn't possibly ask...No, no.
JACK If Aunt Helen's going...
He smiles broadly.
He's off the hook.
Jenny catches David's eye and smiles.
Hattie, Tina and Jenny are sitting on their desks, waiting for a lesson to start.
Hattie shows Jenny a piece of paper which apparently contains some kind of shopping list.
TINA There are some things you must buy for us, and some things you only have to buy for us if you're a proper, true friend.
TINA (She points at Hattie, then at herself.)
TINA Chanel perfume, Chanel perfume.
TINA (She repeats the gesture) Chanel lipstick, Chanel lipstick.
TINA What have I forgotten?
HATTIE Those funny cigarettes you were smoking.
HATTIE Sobranies.
HATTIE Ten packets each.
A very small girl, twelve or thirteen, comes in to the classroom and approaches Jenny.
SMALL GIRL Are you the girl going to Paris?
Tina, Hattie and Jenny stare at her.
SMALL GIRL Well are you or aren't you?
SMALL GIRL Because I'd like some perfume.
Miss Stubbs comes into the classroom carrying books and essays.
She sees the small girl and shoos her out.
She then approaches Jenny and whispers discreetly into her ear.
MISS STUBBS Jenny, the headmistress would like a word at the end of the lesson.
MISS STUBBS I'm afraid that the legend of Mr Rochester may have travelled further than you intended.
Jenny looks at her, startled and a little sick.
The office is dark, wood-panelled, foreboding, apparently designed to put all visitors ill-at-ease.
The headmistress would probably choose to be wood-panelled if she could.
She's tweedy, bespectacled, severe.
There is a knock at the door.
She doesn't look up from her paperwork.
HEADMISTRESS Come.
Jenny enters, looking young and frightened.
HEADMISTRESS Ah.
HEADMISTRESS Miss Mellor.
Jenny tries to look back at her with all the courage she can muster.
HEADMISTRESS We're all very excited about your forthcoming trip to Paris.
HEADMISTRESS Our excitement, indeed, knows no bounds.
HEADMISTRESS Some of us can talk of little else.
Jenny looks at her feet.
HEADMISTRESS An older man, I understand.
HEADMISTRESS A word of warning, Miss Mellor.
70. There may well have been the odd sixth-form girl who has lost an important part of herself - perhaps the best part - while under our supervision.
70. These things happen, regrettably.
70. If, however, we are made aware of this loss, then of course the young lady in question would have to continue her studies elsewhere, if she still has any use for `A'-levels.
70. Is that clear?
JENNY Can I go now?
HEADMISTRESS Please.
Jenny turns round and walks out without saying another word.
Through the window of a hotel suite, we see a BEA jet soaring into the sky.
David and Jenny aren't on it, though.
They are letting themselves into the room.
Jenny stares at the featureless sitting room.
JENNY There's no bed.
DAVID Ah.
DAVID I pushed the boat out and got us a suite.
JENNY A suite!
DAVID Well, if work stops us getting to Paris until tomorrow, then work can buy us a nice hotel room.
DAVID Anyway, it's a special occasion, isn't it?
JENNY I would have thought that tonight of all nights we only need a bedroom.
Close on David's reaction - she hasn't forgotten that tonight's the night.
David and Jenny in bed, in a dimly lit bedroom.
They are kissing - David more passionately than Jenny.
He is making little whimpers of excitement, and Jenny is clearly trying hard to hide her nerves.
We're acutely aware of her age, and of her virginity.
Suddenly David breaks off.
DAVID Hold on a second.
DAVID I've got something.
Rather absurdly, he half-disappears over the side of the bed, reaching for something on the floor.
He comes back with a banana.
Jenny stares at him.
JENNY What on earth is that for?
DAVID I thought....I thought we might want to practice.
Jenny shrieks with horror.
JENNY With a banana?
DAVID I thought we'd get the messy bit over with first.
JENNY David, I don't want to lose my virginity to a piece of fruit.
DAVID I'm sorry.
David attempts to kiss her again.
Jenny wriggles clear.
JENNY Let's wait until we get to Paris.
JENNY I think the moment might have gone.
DAVID I'm sorry, Minnie.
DAVID I'm such a fool.
Jenny doesn't deny it.
JENNY And David.....
JENNY if tomorrow night does happen, it will never happen again, so...
DAVID Why won't it ever happen again?
JENNY Because the first time can only happen once.
DAVID Oh.
JENNY So, please...No Minnies.
JENNY No baby- talk.
JENNY I'm not old enough for baby- talk.
JENNY Treat me like a grown-up.
David looks chastened.
JENNY I know.
JENNY Let's go and sit in our sitting-room.
DAVID Hooray!
DAVID I'll order some champagne.
Jenny looks at him with what might, from one angle, be construed as fondness.
Juliette Greco on the soundtrack.
Jenny leans against a wall, the Seine and Notre Dame behind her.
David takes her picture.
She looks fantastic in the clothes David has given her for her birthday.
A crowded Left Bank gallery.
Jenny is sitting on the floor watching an impossibly handsome young Frenchman paint black the body of an impressively passive naked woman.
The young man sitting next to Jenny gives her an appraising look.
David, standing at the back and looking square and uncomfortable, notices.
We see three listening booths, all containing customers.
Jenny and David are in the middle booth, listening to the Juliette Greco song on the soundtrack.
(For a moment, the sound quality changes - soundtrack becomes source music, seamlessly.)
Jenny is studying the sleeve.
She wants to hug herself, she's so excited.
A Left Bank cafe - David and Jenny are eating steak frites outside, drinking vin ordinaire, watching the world go by.
They are both anticipating the night ahead.
Jenny is smoking at the second-floor window of a simple, pretty Parisian hotel, wearing a glamorous-looking slip and looking at the street life below her.
The bedroom is simple and romantic - everything the airport hotel wasn't.
David is lying amid rumpled sheets, smoking what is clearly a post-coital cigarette, and watching Jenny from behind.
DAVID Do you still feel like a schoolgirl?
Jenny turns round, smiles, shakes her head.
DAVID And it wasn't too uncomfortable?
JENNY Not after the...first bit.
JENNY It's funny, though, isn't it?
JENNY All that poetry, and all those songs and films, about something that lasts no time at all?
David looks at her.
She isn't being cruel.
She just doesn't know any different.
She returns to her people-watching.
He smokes ruminatively.
...Jenny in her games kit, smoking her Sobranie with her friends on the park bench again.
Hattie and Tina are examining their bottles of Chanel reverently.
Jenny is back to being her seventeen-year-old self; somehow her seventeen- year-old self looks comical, and no longer appropriate.
TINA How can you go back to double French when you've had a weekend with an older man in a posh hotel in Paris?
TINA You wouldn't catch me coming anywhere near this dump.
JENNY It wasn't all glamour.
JENNY We spent half the weekend at Heathrow in a hotel suite .
HATTIE A suite?
HATTIE Oh my God.
HATTIE Your life.
They smoke their Sobranies ruminatively.
TINA You're going to miss it.
TINA All the swanning around in posh hotels.
JENNY Why will I need to miss it?
TINA When you go to Oxford.
TINA Unless you're planning on being with David forever.
Jenny doesn't say anything.
HATTIE You're not, are you?
JENNY God, no.
TINA So?
TINA Won't you miss it?
Jenny shrugs.
Clearly she will, and clearly she hasn't thought about it before.
HATTIE We'll miss it.
Jenny laughs.
Jenny's English class file past Miss Stubbs at the end of a lesson.
Miss Stubbs stops Jenny.
MISS STUBBS Jenny, could I have a word?
JENNY Of course.(To Hattie and Tina) I'll catch you up.
Miss Stubbs waits until the room empties.
MISS STUBBS You can do anything you want, Jenny.
MISS STUBBS You know that.
MISS STUBBS You're clever and you're pretty...
MISS STUBBS But sometimes those things fight.
MISS STUBBS I'm worried that at the moment clever Jenny and pretty Jenny are fighting.
JENNY What do you mean?
MISS STUBBS I couldn't bear it if clever Jenny lost.
MISS STUBBS It's because of people like you that I plough through illiterate essays by Sandra Lovell about her pony.
MISS STUBBS And there aren't many of you, I can tell you.
MISS STUBBS One every few years.
MISS STUBBS Is your boyfriend interested in clever Jenny?
JENNY I think so.
MISS STUBBS Interested enough to let her do what she wants?
JENNY He couldn't stop me.
MISS STUBBS He might not have to stop you.
MISS STUBBS That's what I'm trying to tell you.
JENNY I'm not sure what you're trying to tell me.
MISS STUBBS I'm telling you to go to Oxford.
MISS STUBBS No matter what.
MISS STUBBS Or you'll break my heart.
Jenny looks at her.
JENNY Where did you go?
MISS STUBBS Sorry?
JENNY Where did you go?
JENNY Which university?
MISS STUBBS Girton.
MISS STUBBS Cambridge.
JENNY Oh.
MISS STUBBS What does that mean?
MISS STUBBS `Oh'?
JENNY You're clever.
JENNY And you're pretty.
JENNY So presumably, Clever Miss Stubbs won.
JENNY And here you are, reading all those pony essays.
JENNY I don't know.
JENNY These last few months, I've been to Paris, and to jazz clubs, and I've eaten in wonderful restaurants, and seen wonderful films, heard beautiful music...
MISS STUBBS I'm sure you have.
MISS STUBBS But I was filled up with beautiful things, books and music and conversation, in exactly the same way at Cambridge.
MISS STUBBS And I didn't have to pay the same sort of price.
MISS STUBBS Are you taking precautions, Jenny?
Jenny stares at her angrily.
JENNY It's nothing to do with that.
MISS STUBBS Isn't it?
JENNY Maybe our lives are always going to end up with pony essays.
JENNY Or housework.
JENNY And yes, maybe we'll go up to Oxford.
JENNY But if we're all going to die the moment we graduate, maybe it's what we do before that counts.
MISS STUBBS I'm sorry you think I'm dead.
JENNY I don't think you're dead.
JENNY But...
MISS STUBBS You'd better get to your next class.
She turns her back on Jenny.
Helen, Danny, Jenny get out of David's Bristol, which is parked outside a nightclub called Esmerelda's Barn.
David has parked next to a white Rolls-Royce.
JENNY And we know the person who owns this?
DAVID Yes.
DAVID Perec Rachman.
DAVID He's a....
DANNY A bastard.
Danny and David laugh.
DAVID He's a business acquaintance, and we need to talk to him.
JENNY I gathered that much.
JENNY But why do we have to crawl around the West End looking for his car?
JENNY Why don't you just make an appointment, if you want to see him?
The men snigger.
DANNY What?
DANNY Ring his office?
DANNY Talk to his secretary?
DANNY That isn't how it works with him, dear.
The four walk in and take their coats over to the cloakroom.
The club is a smoky West End club, full of smartly-dressed and dubious-looking men, and young, glamorous, dubious-looking women.
Jenny and Helen look out of place - Helen too ethereal, Jenny too innocent.
There is jazz playing.
DANNY There he is.
We see a nasty-looking man in his late 30s/early 40s.
He is wearing a white sharksin suit and smoking a big cigar.
He's standing by the roulette table, talking to an even nastier- looking man in a dark suit.
They find a table at the back and sit down.
A waitress comes over to their table.
DAVID A bottle of champagne, please.
DANNY Oh-ho.
DANNY Champagne, eh?
He looks at Jenny and David expectantly.
DAVID Don't be bashful.
HELEN No.
HELEN Be Sneezy.
Everyone ignores her.
DAVID All right, then.
DAVID If you won't tell them I will.
DAVID Jenny got two As and a B in her mock-A levels.
DANNY Fantastic.
HELEN Congratulations.
JENNY Thank you.
DAVID The B was in Latin.
DAVID But it's much better than it was, isn't it, Minnie?
Rachman is now standing on his own.
Danny nudges David, and they go over to talk to him just as the champagne arrives.
The waiter pops the bottle of champagne and pours two glasses.
The girls smile and clink glasses.
HELEN Don't worry.
JENNY About what?
HELEN Someone told me that in fifty years no-one will speak Latin, probably.
HELEN Not even Latin people.
HELEN So you shouldn't mind too much about your B.
Jenny stares at her, trying to think of a response.
Danny and David are at the bar, having just finished talking to Rachman.
Danny puffs out his cheeks and shakes his head.
DANNY Well, I'm not sure you'd want him to marry your sister.
DANNY I'm not even sure you'd want to talk to him in a night-club, come to that.
They both chuckle.
There is a silence for a moment.
DANNY You do know what you're doing, old chap?
DANNY With Jenny?
DAVID This is the one, Danny.
DANNY We've heard that before.
DAVID You can see she's different.
DAVID She's got everything.
DAVID You've got Helen, and....
DANNY And you've got Helen with brains.
DAVID Yes.
DANNY I don't want to see her hurt.
They make their way back to their table.
While David and Helen watch, Danny and Jenny dance.
Danny's a good dancer; Jenny is nervous at first, but becomes more comfortable and more expressive, with Danny's help.
JENNY Have you...Have you bought any more paintings recently?
DANNY Have I?
DANNY Let's think?
DANNY Oh, I picked up a little Piper the other day.
DANNY A good `un, I think.
JENNY I'm still trying to work out what makes good things good.
JENNY It's hard, isn't it?
DANNY The thing is, Jenny, you know, without necessarily being able to explain why.
DANNY You've got taste.
DANNY That's not even half the battle.
DANNY That's the whole war.
Jenny smiles at him with gratitude.
There is a sudden closeness between them.
David is watching them carefully.
They return to their table.
DAVID Jenny, we should go.
DAVID It's late.
JENNY Oh.
JENNY Yes.
DANNY Alas.
DANNY One day, school will be over forever, and we can talk about art all night.
DAVID You're all right in a taxi, aren't you?
He guides Jenny firmly out of the club.
Jenny is about to to open the passenger door of the Bristol, but David stops her.
DAVID Wait there.
He runs to the back of the car, opens the boot and starts rummaging through it.
It seems to be full of everything but the thing he's looking for.
JENNY What are you doing?
He slams the boot shut and comes back empty-handed.
DAVID Will you marry me?
Jenny stares at him for a moment, then laughs.
JENNY What were you looking for?
DAVID I thought I had a ring.
DAVID It wouldn't have been the right one.
DAVID But it would have done for tonight.
JENNY Oh, David.
DAVID I'm serious.
JENNY You're very sweet.
DAVID What do you think?
JENNY Please take me home.
She gets into the car.
We see the desperation in David's face, lit by the headlights of a passing taxi, as he slams the door on Jenny after she's got in.
Jenny, Tina and Hattie all smoking in the school toilets.
Jenny is distracted, and standing apart from the others.
Tina looks at her.
TINA How do you say `A penny for your thoughts?' in French?
HATTIE A franc is too much, isn't it?
TINA For her thoughts, yes.
TINA You'd be overpaying by about ninety-nine centimes.
Suddenly the door bursts open and the Latin teacher comes in.
The three girls are lined up in front of the headmistress, hands by their sides.
HEADMISTRESS I'm surprised that you two are standing in front of me.
HEADMISTRESS I'm not surprised to find you here, Miss Mellor, though I do feel rather like the judge who sent Al Capone to prison for tax evasion.
HEADMISTRESS We take a very dim view of smoking.
HEADMISTRESS We take an even dimmer view of some of your other behaviour, which as far as we know has taken place off school premises.
HEADMISTRESS Your appearance here today, however, allows me to remind you that we are trying to teach you how to become young ladies, not nightclub hostesses.
HEADMISTRESS In reality, of course, you are neither.
HEADMISTRESS You are merely silly little girls.
HEADMISTRESS Detention after school.
HEADMISTRESS Go away.
83. Jenny's face sets hard.
83. Something in her shuts down.
Jenny is smoking on the balcony.
Jenny is at her desk in her bedroom, trying to work, but she can't concentrate.
Her hair is tied back in a pony- tail.
She gets up, pulls back the curtains, looks out of the window.
We see what she sees: a sleepy suburban street at night.
She looks back at her desk.
It looks even more boring than the street.
She looks at her scrubbed seventeen- year-old face in the mirror - so much younger than the Jenny we have seen with David.
She makes herself up, and she gets older and more glamorous before our eyes.
In her make-up and her school uniform, she's half-woman, half- child.
We hear the noises drifting up from the kitchen: the radio, the washing-up, occasional muffled conversation.
Jenny walks out of the bedroom and slips downstairs.
Jenny's mother and father are doing the washing up and listening to the radio.
They have their backs to the door.
Jenny enters the room quietly and watches them for a moment
MAN ON THE RADIO They do need some looking after, but nothing that will require too much work.
MAN ON THE RADIO Just leave them in your potting shed for a couple of weeks, and they'll look after themselves.
JACK Oh, aye.
JACK The potting shed.
JACK Who does he think I am?
JACK Prince Rainier of Monaco?
JENNY What if I got married instead of going to college?
JENNY Jack and Marjorie turn around and stare at this strange apparition wearing too much make-up and a school uniform.
JACK Married?
JENNY Married.
JACK It would depend who it was, surely?
JENNY Would it?
JENNY That's interesting.
JACK Course it would.
JACK I wouldn't want you married off just for the sake of it.
JENNY Thanks.
MARJORIE Has somebody asked you?
JENNY Yes.
JACK Who?
Marjorie rolls her eyes.
MARJORIE What did you tell him?
JENNY Nothing yet.
JACK David?
JENNY No.
JENNY A man I just met walking his dog.
JACK David's asked you to marry him?
JACK Bloody hell.
JACK Pardon my French.
MARJORIE Do you have any choice?
MARJORIE Or is it too late.
She looks at her daughter knowingly.
Jack merely looks confused.
JACK Of course she's got a choice.
JACK But it's an interesting one, isn't it?
JENNY This is where you're supposed to say, "But what about Oxford?"
JACK Well.
JACK Looked at it one way, you wouldn't really need to go now, would you?
JACK He's a man going places.
JACK And say what you like, but they know how to take care of their money, don't they?
JACK He'll see you're looked after.
JENNY I wouldn't need to go.
JENNY Would you like to expand on that?
JACK You know what I mean.
Jenny laughs bitterly.
She can't believe it.
JENNY All that Latin!
JENNY All those essays!
JENNY What was the point?
JENNY Why didn't you just send me out prowling round nightclubs?
JENNY It would have been less trouble.
JENNY And I might have had more fun.
JACK We don't know about nightclubs.
JACK We knew about education.
JACK Anyway, it all turned out for the best.
JENNY How?
JACK He wouldn't have wanted you if you were thick, would he?
Jenny stares at them and walks out.
English.
Miss Stubbs is standing at the front of the class, holding a copy of King Lear, and listening as various members of the class massacre the text.
Some are messing about by overacting; others read to the best of their ability, tonelessly and with no understanding of the words.
Lear himself is being read by Ann, the bespectacled girl from the first scene.
She's no King Lear, and she's one of the bad readers.
GIRL 1 May not an ass know when the cart draws the horse?
GIRL 1 Sings whoop jug I love thee.
MISS STUBBS Yes, when it says `Sings', it means he sings those words.
Girl 1 looks at her blankly.
MISS STUBBS Never mind.
MISS STUBBS Lear...
ANN Does any here know me.
ANN This is not Lear.
ANN Does Lear walk thus?
TINA No.
Jenny starts to giggle.
ANN Speak thus?
Tina shakes her head.
ANN Where are his eyes?
Tina doesn't need to say anything - she just looks at Jenny, makes a pair of spectacles with her fingers and squints.
Jenny's giggling fit increases in intensity.
ANN Either his notion weakens, or his discernings are lethargied.
ANN Ha!
ANN Waking?
ANN Tis not so.
ANN Who is it that can tell me who I am?
Jenny's arm shoots up, as if to answer the question.
JENNY Ooh.
JENNY Miss.
JENNY Me.
JENNY I can.
Miss Stubbs looks at Jenny more in sorrow than in anger - Jenny's behaviour now is something new in their relationship.
Jenny stares back at her defiantly.
Suddenly Miss Stubbs notices something glinting on her hand: an engagement ring.
MISS STUBBS Oh, Jenny.
She is, as she promised she would be, heartbroken.
JENNY What?
MISS STUBBS Take it off.
Hattie, who is sitting behind Jenny, notices the ring, too, for the first time.
HATTIE Oh my God.
HATTIE Is that really what I think it is?
HATTIE I'M GOING TO BE A
There is an excited susurration in the classroom.
MISS STUBBS You know there's a school rule about jewelry.
JENNY Half the girls in this room are wearing jewelry.
MISS STUBBS Yes.
MISS STUBBS But none of it is going to ruin their lives.
JENNY We have a difference of opinion on that.
Miss Stubbs stares at her.
Jenny can only just steel herself to stare back.
MISS STUBBS Let's see who's right.
MISS STUBBS Come with me.
Jenny doesn't move.
MISS STUBBS Please don't make me drag you out like a child.
Jenny gets to her feet.
Teacher and pupil leave the room, while the rest of the class watches.
HEADMISTRESS How far advanced are these ridiculous plans?
HEADMISTRESS Have you set a date?
HEADMISTRESS Have you decided on a church?
JENNY We won't be getting married in a church.
JENNY David's Jewish.
The headmistress stares at her, dumbfounded.
HEADMISTRESS Jewish?
HEADMISTRESS He's a Jew?
HEADMISTRESS You're aware, I take it, that the Jews killed our Lord?
JENNY And you're aware, I suppose, that our Lord was Jewish?
The headmistress snorts scornfully
HEADMISTRESS I suppose he told you that.
HEADMISTRESS We're all very sorry about what happened in the War.
HEADMISTRESS But there's no excuse for that sort of malicious and untruthful propaganda.
Jenny smiles to herself.
HEADMISTRESS Anyway, I can now see that you are even more in need of responsible advice than I realised.
HEADMISTRESS Is it true that you don't intend to sit for your exams?
HEADMISTRESS And therefore you won't be applying for University?
JENNY Yes, that's right.
HEADMISTRESS What do you think you're doing?
JENNY Nobody has been able to explain to me the point of University.
89. Therefore I don't see the point of the exams, either.
HEADMISTRESS Nobody does anything worth doing without a degree.
JENNY And nobody does anything worth doing with one, either.
JENNY No woman, anyway.
HEADMISTRESS So what I do isn't worth doing.
HEADMISTRESS Or what Miss Stubbs does, or Mrs Wilson, or any of us here.
Jenny doesn't say anything.
The headmistress takes her silence as an admission of defeat.
HEADMISTRESS Because none of us would be here without our degrees, you realise that, don't you?
HEADMISTRESS And yes, of course studying is hard, and boring, and...
Jenny can't contain herself any longer.
JENNY Boring!
HEADMISTRESS I'm sorry?
JENNY Studying is hard and boring.
JENNY Teaching is hard and boring.
JENNY So you're telling me to be bored, and then bored, and then finally bored again, this time for the rest of my life.
JENNY This whole stupid country is bored.
JENNY There's no life in it, or colour in it, or fun in it.
JENNY It's probably just as well that the Russians are going to drop a nuclear bomb on us any day now.
JENNY So my choice is either to do something hard and boring, OR to marry my...
JENNY my Jew, and go to Paris and Rome and listen to jazz and read and eat good food in nice restaurants and have fun.
JENNY It's not enough to educate us any more, Mrs Walters.
JENNY You've got to tell us why you're doing it.
HEADMISTRESS Because without formal qualifications...
She grinds to a halt.
She has never had to answer this question before.
HEADMISTRESS It doesn't have to be teaching, you know.
HEADMISTRESS There's the Civil Service.
Jenny stands up.
JENNY I don't wish to be impertinent, Mrs Walters.
JENNY But it is an argument worth rehearsing.
JENNY You never know.
JENNY Someone else might want to know what the point of it all is, one day.
She leaves the office.
Jenny is half-walking, half-running, towards the school gates.
She's scared, of course, but exhilarated, too.
All that pressure, and all those years of education, suddenly over, unexpectedly, and certainly unceremoniously.
She looks neither left nor right, but other girls, younger girls, watch her through the windows as she leaves.
Jenny doesn't even look round when she goes through the school gates.
Later.
Jenny and Marjorie are sitting at the kitchen table.
Jack is standing over them; he hasn't even taken his coat off, or put his briefcase down.
JACK How d'you mean, left?
Jenny doesn't answer.
JACK What about your exams?
JENNY I'm not sitting them.
JACK What are we going to tell people?
JENNY Oh, telling people.
JENNY I'd forgotten that what we tell people is more important than anything.
JACK All that...
Marjorie knows what he's going to say, and doesn't want him to.
MARJORIE Jack!
JACK No.
JACK No need for Jack.
JACK She should hear it.
JACK All that money!
JACK Do you know how much it's cost me for you to go through school and take no exams?
JENNY I'm sure David will pay you back.
JENNY Send him a bill.
JENNY As you said, he wouldn't have wanted me if I was dim, so he should fork out.
JENNY Just tell me why there's a point in sitting my exams, and there's no point in me going to University.
Jack gapes at her.
He's floundering.
JACK You know what your trouble is, don't you?
JACK You're too clever by half.
JENNY In which case I should have left school years ago, shouldn't I?
JENNY Ask them for the money back.
JENNY If I'm too clever by half, you overpaid by a third.
Danny, Helen, David and Jenny are in Danny's flat; we have just missed The Announcement - there is champagne already open.
Danny glances quickly and discreetly at David, who catches his eye.
HELEN That's...Gosh.
HELEN That's fantastic news.
Danny isn't so pleased.
DANNY Congratulations.
There is much chinking of glasses.
HELEN I thought you'd see sense about university.
Jenny smiles.
HELEN (CONT'D) You'll stay pretty now.
Laughter from David and Jenny.
JENNY Am I still allowed to read?
HELEN English?
HELEN Books?
More laughter.
HELEN (CONT'D) You won't be laughing when she goes all speccy and spotty, David.
Helen is bemused by their mirth.
Danny watches David thoughtfully.
David and Jenny come out of Danny's flat and approach David's car.
JENNY Danny didn't seem very pleased about our engagement.
DAVID I thought that, too!
DAVID I was wondering whether he might be a bit jealous.
JENNY Jealous?
DAVID You may have noticed that Helen's not really Oxford material.
DAVID I'm going to keep him out of your way.
DAVID They both smile.
DAVID David opens the door for Jenny and she gets into the car.
Jenny is making David a cup of tea.
Her mother is keeping an eye on Jenny - in Marjorie's mind at least, this is a rehearsal for something.
DAVID I haven't put my...my stamp on it yet.
DAVID Haven't had time.
DAVID It needs a woman's touch, really.
DAVID And if you don't like it, we can move.
DAVID Just say the word.
JENNY Where is the flat again?
MARJORIE You have to put the cosy on straight away.
MARJORIE Jenny sighs and rolls her eyes.
MARJORIE She picks up the hand- knitted tea-cosy and puts it on her head.
JENNY Like that?
JENNY David laughs.
MARJORIE No.
MARJORIE On the tea-pot.
JENNY Ah.
JENNY She puts the tea-cosy on the tea-pot.
DAVID Just down from Russell Square.
DAVID Two minutes' walk from the underground.
MARJORIE Jenny!
MARJORIE We could walk to...(She tries to think of somewhere Jenny might find interesting.)
MARJORIE We could walk to the British Museum!
Jenny gives her a look.
MARJORIE I'll leave you to it.
MARJORIE Don't let it stew.
She leaves the room.
JENNY And this is where you're living?
DAVID I've stayed there for the last couple of nights.
DAVID (Beat) On and off.
JENNY You've stayed there two nights "on and off"?
DAVID Is that tea ready?
DAVID One sugar, please.
JENNY David!
DAVID I'm sorry.
DAVID You must think I'm very odd.
JENNY No, but....
JENNY You seem to float around.
JENNY I never know where you are.
She hands him his tea.
DAVID A wandering Jew.(He pauses to take a sip.)
DAVID If I tell you something, will you promise not to laugh?
JENNY It depends on how funny it is.
DAVID I live at home.
JENNY We all live at home.
DAVID No.
DAVID I mean...I live at home...in the same way that you live at home.
JENNY But I live with my mother and fa...(It clicks.)
JENNY You don't mean it.
David nods, shamefacedly.
JENNY Your mother and father?
DAVID Just my mother.
DAVID My father's dead.
DAVID I've been meaning to tell you, Minnie, and it would have been much better than all those silly lies.
DAVID But...
He looks quite upset.
We warm to him.
Jenny leans over and takes his hand.
DAVID Anyway.
DAVID You can see how much I need you.
DAVID And you won't regret this, I promise.
DAVID We'll have so much fun.
DAVID And just think.
DAVID When we get married, you won't have to wait in the car while I do my business..
DAVID You'll be waiting at home, looking at the Burne-Jones on the wall.
DAVID Home, Minnie.
DAVID Our home.
DAVID Can you imagine?
Close on Jenny.
She can't imagine, really.
Jenny, Tina and Hattie in the coffee bar.
Jenny is eagerly scanning the English literature exam paper.
JENNY Did you do this one?
JENNY "Show from any TWO scenes in `Pride and Prejudice' how far it is true that Jane Austen's methods are `essentially dramatic'".
HATTIE Three scenes.
JENNY It says two here.
JENNY Look.
She shows the paper to Hattie.
Hattie slumps onto the formica table and groans.
HATTIE Two.
HATTIE Two.
HATTIE Two.
HATTIE I can't believe it.
Tina rubs Hattie's head sympathetically.
TINA It was an unfair question.
TINA You're hopeless at maths.
TINA What do you do all day, anyway, Lady Muck?
Jenny shrugs.
JENNY I've been looking at flats.
JENNY I've been to look at dresses.
JENNY I've been reading a lot, too.
TINA Reading, trying on dresses...
TINA Where did we go wrong?
JENNY What's this afternoon?
TINA French.
TINA The translation paper.
Jenny is lapping it all up.
She might even be envious.
Jenny and Marjorie are in the sitting room, all dressed up and waiting for David to come and pick them up.
Jenny looks great, as usual; her mother looks smart, if somewhat old- fashioned.
MARJORIE Don't worry.
MARJORIE He'll find a nice place in no time.
MARJORIE He sees plenty of them.
JENNY I'm not sure he sees plenty of nice places.
JENNY Would you like a radiogram for a wedding present?
JENNY We love ours.
Something about this depresses Jenny.
Marjorie notices.
MARJORIE You won't be bored, you know.
MARJORIE He's not boring.
Now they are both thoughtful.
As if on cue, Jack comes into the sitting room, pulling at his tie, looking apprehensive.
He appears to be wearing Brylcreem.
He looks like a little boy who has been made to put on his Sunday best.
JACK What sort of things can you have for starters?
JACK I mean, how will I know what are starters and what aren't?
JACK I'm all right if it's soup or fruit juice.
JACK But if it's anything more than that...
JENNY We've been through this, Dad.
JENNY It'll be quite clearly marked on the menu.
The doorbell rings.
Jack stiffens.
Jenny goes to answer the door.
JACK Why don't you three go out?
JACK I'll be happy here with a tin of...
David enters the room.
He is relaxed, happy.
He has worn a tie, possibly because he knew that Jack would wear a tie.
Jack and Marjorie stand, and they exchange greetings.
DAVID Everybody ready?
DAVID I think you'll like this place, Jack.
DAVID Their wine list is as good as anything I've seen in London.
JACK Someone told me that.
JENNY David, probably.
JENNY Who else would it have been?
Jack and Marjorie approach David's Bristol.
JACK I was hoping you'd take us in this.
DAVID Oh, you won't want to go in anything else after tonight.
DAVID Mind you, it drinks petrol.
DAVID I'm afraid we'll have to stop on the way in to town.
He opens the back door for his future in-laws.
DAVID Madame.
DAVID Monsieur.
They get in, he closes the door, runs round to open the front passenger door for Jenny.
David starts the car, and glances in the rear-view mirror.
DAVID Everyone happy?
JACK I feel like Eamonn Andrews.
DAVID Is that a good thing?
MARJORIE Of course.
MARJORIE Eamonn Andrews is the poshest person that Jack can imagine being.
The Bristol cruises down a London arterial road.
We see, from David's POV, a petrol station approaching.
DAVID Sorry about this.
He slows the car and turns in to the garage.
David gets out of the car as the attendant comes over.
ATTENDANT How can I help you, sir?
DAVID You might as well fill her up.
David looks around and spots a phone box just outside the garage.
He leans in through the open car window.
DAVID I'm just going to make a quick call.
DAVID I'll be two ticks.
Jenny watches him walk towards the phone box.
JACK Do you think we should offer him some petrol money?
JACK Or would he feel insulted?
Jenny watches David as he dials the number.
He notices her, waves, puts the money in the slot.
JACK He'd feel insulted, probably.
JACK He said tonight was his treat.
JACK That must include the petrol, for God's sakes?
David starts to talk, and turns away, as if he's frightened that someone in the car can lip-read.
JACK What do you think?
Nobody pays him any attention.
They lapse into silence.
Jack starts to fiddle with the features in the car - a table springs down from the seat in front of him, much to his alarm.
JACK God almighty.
JACK What have I done?
Jenny opens the glove compartment, looking for the cigarettes that David always keeps there.
She finds the cigarettes, and closes the glove compartment.
But she has seen something in there, so she opens it again.
She takes out some letters and papers and starts to look through them.
David has finished his phone call and is walking towards the car.
He sees Jenny looking through letters and papers, sees the open glove compartment, starts to run across the forecourt.
DAVID Jenny!
It's too late.
We see Jenny's stricken face, gleaming in someone else's headlights.
David gets into the car.
DAVID Jenny, I...
JENNY Take us home.
JACK What's going on?
DAVID There's been a...Jenny's had a bit of a shock.
Jenny laughs, mirthlessly, then starts to weep.
JACK What's happened?
JENNY It's another one of David's little muddles and misunderstandings.
DAVID Jenny, it's not...
JENNY I don't want to hear another word from anybody.
JENNY Take me home.
JENNY NOW.
101. Marjorie and Jack look at each other.
101. David swings the car around and they drive home in silence; Jenny cries constantly, without making a sound.
The Bristol draws up outside Jenny's house.
David jumps out of the car and lets Marjorie and Jack out.
Jack starts to walk towards the house and then stops.
JACK You can sort this out, can't you, David?
JACK Jenny gets out of the car too.
DAVID Of course I can.
DAVID She's just got the wrong end of the stick about something.
JENNY Go inside, Dad.
JENNY Jenny and David watch Jack and Marjorie go into the house.
JENNY The moment the door is closed, Jenny walks towards David.
JENNY She's holding a bunch of letters that she took out of the glove compartment.
JENNY She starts to throw them at him, one by one.
JENNY Mr and Mrs David Goldman, Mr and Mrs David Goldman, Mr and Mrs David Goldman, Mr and Mrs David Goldman..
JENNY When she has thrown the last one, she flies at David - she slaps him, punches him, scratches him.
JENNY David tries to grab her hands, but she's too wild.
DAVID Just let me...
JENNY You're MARRIED!
DAVID Legally, yes, but...
DAVID Finally he manages to subdue her.
DAVID She leans against the car, distraught.
JENNY When were you going to tell me?
DAVID Soon.
DAVID It just - it never seemed the right time.
DAVID You seemed so happy, and I was happy, and...It would have spoiled everything.
DAVID What can I do, Minnie?
DAVID What can I do?
DAVID How can...
JENNY "Oh, Jenny.
JENNY I'm just too busy to find somewhere to live...I live with my mummy."
JENNY You were living with your wife!
JENNY All this time!
DAVID Jenny...
JENNY What's your address?
David gestures vaguely.
JENNY Where?
DAVID Byron Avenue.
JENNY Byron Avenue!
JENNY It's no wonder we kept bumping into each other, then, is it?
JENNY What number?
DAVID There's no point..
DAVID Seventeen.
Jenny picks one of the envelopes up off the ground and looks at it.
JENNY Good grief.
JENNY It's the truth.
DAVID Please.
DAVID You have to understand.
DAVID I was with you just about all the spare time I had.
JENNY Spare time?
JENNY Spare time?
JENNY I can't tell you how grateful I am.
DAVID Don't be like this.
JENNY I have nothing.
JENNY I left school.
JENNY I didn't take my exams.
JENNY Where's it all gone, now?
JENNY I gave my life away.
DAVID Jenny, I can get a divorce.
DAVID Everything will turn out for the best.
DAVID You'll see.
We can see Jack and Marjorie peering through the lace curtains anxiously.
JENNY Go and tell them.
JENNY Go and tell them, then go and tell your wife.
JENNY I want to see you.
JENNY I want to stand there and watch.
David stands on the pavement, looking towards the house.
He looks away; he can't make eye contact with Jenny's parents.
DAVID They're not going to listen to me now.
DAVID Let me come round tomorrow.
DAVID When everyone's calmed down a bit.
JENNY Please don't leave me to tell them on my own.
JENNY Please.
JENNY You owe me that much.
JENNY You owe them that much.
DAVID I owe them a lot more than that.
DAVID I owe them everything.
DAVID They gave me you.
He opens the boot.
It's full of cases of whiskey.
Jenny doesn't even bother asking what they are doing there.
David takes one of the bottles, opens it, takes a long slug.
JENNY Two minutes.
JENNY And then I'll come out and drag you in.
104. Jenny marches into the house and slams the door.
104. The camera stays on David.
104. He gets back into the car and takes another slug of whiskey.
104. Then his shoulders begin to shake, and he cries and cries.
Jenny comes in, leaving the door open for David.
Her parents are standing in the sitting room, looking at her anxiously.
Their coats are still on, and they haven't put the lights on yet.
JACK What's going on?
JENNY He's helping himself to some Dutch courage before facing you.
JENNY Stolen Dutch courage, from the look of it.
JENNY He has something to tell you.
JENNY She stands, pale and young-looking again, opposite her parents.
JENNY Suddenly they are all three lit up by headlights.
JENNY Shot from their POV of the Bristol roaring off up the street.
JACK He just drove off.
JACK We close slowly in on Jenny's face.
JACK But of course he'd drive off!
JACK Can you tell us?
JACK Please?
JACK Jenny?
JACK Jenny can't deal with her own pain, let alone his.
JACK He already looks like a broken, foolish old man.
JACK They should hug.
JACK But they don't.
A suburban street, full of semi-detached houses, not far from Jenny's house.
Jenny walks down the road tentatively - she's looking at the numbers on the houses.
She looks young again - tired, no make-up, no elegant clothes.
She can't bring herself to wear anything that David bought her.
She hesitates at the top of the driveway to the house, steels herself to walk down.
But just at that moment the door opens; there's a homely-looking woman, early 30s.
She is holding the hand of a three-year-old.
Jenny is stunned.
But there's more to come.
The woman deposits the child in the drive, goes back into the house, comes out behind an enormous 1950s pram.
David has found time to father another baby.
WIFE Oh.
WIFE Hello.
JENNY Hello.
JENNY I'm sorry.
JENNY I think I must have the wrong house.
The woman stares at her.
JENNY Yes.
JENNY I wanted number...It's my cello lesson.
JENNY Silly.
JENNY I...
She dries up and looks at the woman helplessly.
WIFE Oh, no.
WIFE Don't tell me.
WIFE Good God.
WIFE You're a child.
Jenny blushes.
Beat.
She turns and tries to walk back up the driveway, but the woman won't let her go.
WIFE No.
WIFE No.
WIFE You stay here.
WIFE If you're old enough to sleep with him, you're old enough to look at me.
JENNY I can't.
But she doesn't move, either.
WIFE You didn't know about any of this.
WIFE Presumably.
Jenny shakes her head.
WIFE No.
WIFE They never do.
WIFE Did he ask you to marry him?
Jenny nods.
WIFE Yes.
WIFE Of course he did.
WIFE You're not in the family way, are you?
WIFE Because that's happened before.
Jenny shakes her head.
WIFE Thank God for that.
WIFE At least you can escape intact.
WIFE (Beat) Relatively speaking.
WIFE Not all of them have done.
WIFE She nods at the children.
WIFE That's why he never goes through with anything.
WIFE He does love them.
JENNY She's beautiful.
WIFE Thank you.
WIFE He.
WIFE (Bitterly) He's four months old.
WIFE Jenny does the maths.
WIFE It's all she can do to stop herself from reeling backwards - she's visibly shaken.
JENNY Four months!
WIFE Yes.
WIFE Babies often are that sort of age.
WIFE Perhaps you can remember a night four months ago when he seemed a little distracted.
WIFE Anyway.
WIFE If you'll excuse us.
WIFE She pushes past Jenny and leaves her standing bereft on the path.
Marjorie and Jack are in the kitchen.
Marjorie is sipping tea, shoulders hunched, defeated.
Jack is pacing around the room, furious.
Normal life has clearly been suspended during this crisis.
Jenny walks in.
MARJORIE Did you see her?
JENNY I saw her.
JENNY I didn't talk to her.
JENNY There wasn't any need.
JACK Well we've got to have this out.
JACK If you won't do it, I will.
JACK He starts for the door.
JENNY Sit down.
JACK I beg your pardon?
JACK I'm still your father, Jenny.
JENNY Oh, you're my father again, are you?
JENNY What were you when you encouraged me to throw my life away?
JENNY I'm a silly schoolgirl.
JENNY Was, anyway.
JENNY Silly schoolgirls are always being seduced by glamorous older men.
JENNY But what about you two?
JACK We didn't...
JACK He gives up hopelessly.
JACK Marjorie says nothing.
JENNY And now I've got nothing.
JENNY I'm...I'm broken.
JENNY Jack looks at her.
JACK That doesn't mean....what I think it means, does it?
JACK It can't.
JENNY What are you talking about?
JACK Just tell me that you didn't...you haven't, you know...You didn't....
JACK Jenny looks at him in disbelief.
MARJORIE I wondered how stupid you were.
MARJORIE Now I know.
Jack stands outside Jenny's bedroom door with a cup of tea.
He knocks tentatively.
Close-up of the floaty print dress that Helen gave her.
The dress is suddenly jerked out of shot, and we pull back to reveal a weeping Jenny stuffing it violently into an already full box of things she is throwing out.
The contents represent her now-despised, David-created adult self.
We can see Juliette Greco albums, photos, expensive- looking jewelry boxes.
She continues to stuff things into the box.
There's a knock on the door.
JACK Jenny.
JACK She continue to put her David-life away into bags.
JACK She ignores him.
Jack is almost in tears.
JACK There's a cup of tea for you here.
JACK No answer.
JACK He puts the tea on the floor, and sits down next to it.
JACK I know I made a mess of everything.
JACK He waits for an answer - nothing.
JACK All my life I've been scared, and I didn't want you to be scared.
JACK That's why I wanted you to go to Oxford.
JACK So that if someone asked you out to a nice restaurant, you wouldn't panic about what was a starter and what was a main course.
JACK And then David came along, and he had money, and he knew famous writers, and he knew how to get to classical music concerts.
JACK But he wasn't who he said he was.
JACK He wasn't who you said he was, either.
Jenny is about to rip a poster off the wall, but she pauses.
JACK The other day, your mother and I were listening to a programme about CS Lewis on the radio, and they said he moved to Cambridge in 1954.
JACK And I said to Marjorie, Well, they've got that wrong, because how would our Jenny get her book signed, if he wasn't in Oxford?
Jenny's face crumples.
She knows he's right.
JACK Jenny, I'm sorry.
Jenny is sitting on the sofa in Danny's flat.
Danny and Helen are in dressing gowns; there are newspapers strewn around.
Danny pours her a brandy.
Helen is sitting next to her, holding her hand.
HELEN I don't really understand what difference it makes.
HELEN When I found out that...
DANNY Helen!
DANNY Not now.
DANNY Helen shrugs.
DANNY I tried to tell him.
DANNY I'm not speaking to him now, if that's any consolation.
JENNY It's a funny world you people live in.
JENNY You both watched me...
JENNY carrying on with a married man, but you don't think it's worth saying anything.
DANNY Ah, well if you want that sort of conversation...You watched David and I help ourselves to a map, and you didn't say much, either.
DANNY He holds Jenny's gaze.
DANNY She looks away.
Jenny has put on her school uniform for this meeting; it completes a circle.
She's back where she started from, or would like to be, anyway.
If she seems older than she did when we first met her, it's because things have happened to her, and they've left a mark on her face.
She's worried and tired.
The headmistress, meanwhile, is delighted by her return - but only because of the opportunities for smugness and schadenfreude it provides.
HEADMISTRESS So.
HEADMISTRESS Your Jewish friend turned out to be married already, I understand.
HEADMISTRESS How unfortunate.
HEADMISTRESS Jenny doesn't say anything.
HEADMISTRESS She has clearly decided to swallow anything she has to.
HEADMISTRESS Anyway.
HEADMISTRESS How do you think we can help?
JENNY I'd like to repeat my last year at school.
JENNY Start all over again.
HEADMISTRESS I got the impression the last time we spoke that you didn't see the point of school.
HEADMISTRESS Or of me, or of any of us here.
JENNY I know.
JENNY I was stupid.
HEADMISTRESS So what is the point?
JENNY I know that I need to go to university.
HEADMISTRESS And what happens if some other chap wants to marry you during your studies next year?
JENNY Some other chap?
JENNY There won't be any other chaps.
JENNY Not for a long, long time, anyway.
HEADMISTRESS I'm afraid I think you're the sort of young lady who attracts chaps whether she wants to or not.
HEADMISTRESS No,I think the offer of a place at this school would be wasted on you.
HEADMISTRESS You showed how little you valued us only weeks ago.
HEADMISTRESS And I must confess that it gives me a sort of grim satisfaction to return the sentiment now.
JENNY Is it really so grim, your satisfaction?
HEADMISTRESS It gives me no pleasure to see our schoolgirls throw their lives away.
HEADMISTRESS Although, of course, you're not one of our schoolgirls any more.
HEADMISTRESS Through your own volition.
JENNY I suppose you think I'm a ruined woman.
HEADMISTRESS Oh, you're not a woman.
HEADMISTRESS Beat.
HEADMISTRESS Jenny stands up and leaves without saying a word.
HEADMISTRESS The headmistress is pleased with her final line.
Jenny working hard in her room.
It's been completely stripped bare of everything except schoolbooks.
She has become ageless, genderless - her life is now monastic.
Jenny walking alone through her old park.
Jenny on her own, smoking nervously.
Hattie and Tina come in.
They obviously haven't seen her since it all happened.
They both hug her sympathetically and sit down.
Nobody knows what to say.
TINA I'm sure my uncle knows someone who could kill him.
TINA If that would help.
TINA Jenny smiles wanly, and briefly.
HATTIE We should have stopped you.
JENNY Did you want to?
TINA Of course we didn't.
TINA Why would we stop you?
TINA Restaurants, hotels, foreign cities, no exams...
JENNY Yes.
JENNY Who'd have thought there'd be a down side to all that?
JENNY I could tell you all about the imagery in Jane Eyre.
JENNY But I couldn't see that a man who stole maps from old ladies might be a liar.
JENNY They look at her.
JENNY This is new information.
HATTIE Well, if you'd told us that we might have tried to stop you.
JENNY There are a lot of things I didn't tell you.
JENNY I was dreaming.
TINA That's the thing about our lives, isn't it?
TINA It's so easy to fall asleep, when there's nothing to keep you awake.
TINA Beat.
HATTIE Are you getting on with the work all right on your own?
113. Jenny thinks.
JENNY No.
JENNY No, I'm not.
Jenny in a suburban street.
She's looking for an address.
She finds the house, walks down the path, rings on a bell.
Miss Stubbs comes to the door.
MISS STUBBS Jenny!
MISS STUBBS It's a warm greeting.
MISS STUBBS She ushers her inside.
It's a proper Bohemian flat, up in the eaves.
There are books and papers and paintings covering every available surface.
Jenny looks around.
Finally, for the first time, we see her in somewhere she can feel at home.
JENNY This is lovely.
JENNY Miss Stubbs makes a face.
JENNY But it is.
JENNY Really.
JENNY I'd love to live somewhere like this.
JENNY Miss Stubbs laughs.
MISS STUBBS Oh, it's not hard.
MISS STUBBS Go to Oxford and become a teacher and this is what you end up with.
JENNY But all these books and pictures....
MISS STUBBS Penguin paperbacks.
MISS STUBBS Posters and postcards.
JENNY Yes, but...That's all you need, isn't it?
114. Just a place to...I'm sorry I said those silly things.
114. I didn't understand.
MISS STUBBS Let's forget all about it.
MISS STUBBS A poster catches Jenny's eye.
JENNY A Burne-Jones.
JENNY Miss Stubbs laughs.
JENNY What?
MISS STUBBS You make it sound as though it's an original.
MISS STUBBS Do you like him?
MISS STUBBS Jenny pauses.
JENNY Yes.
JENNY I do.
JENNY Still.
MISS STUBBS Still?
MISS STUBBS Gosh, you sound very old and wise.
JENNY I feel old.
JENNY But really not very wise.
JENNY Miss Stubbs, I'm....I need your help.
MISS STUBBS I was so hoping that's what you were going to say.
Eighteen months later.
Swelling orchestral music.
Close on Jenny cycling, absorbed, happy, the cello strapped to her precariously.
The camera pulls back to show her cycling through the streets of Oxford.
She's done it.
We follow her for a little while.
She dismounts outside a church and leans the bike against a wall.
Just as she's about to leave it, she sees something and freezes.
We follow her gaze: it's the red Bristol, parked a little way down the road just in front of her.
She scans the street to see if she can find David.
She can - he's coming round a corner, a littler further down the street, unwrapping a packet of cigarettes.
Jenny moves into his eye-line.
He sees her, stops, then walks towards her.
DAVID Jenny.
Jenny says nothing.
DAVID Jenny.
DAVID Minnie.
DAVID I wanted to tell you that I am going to ask my wife for a divorce.
Jenny looks at him disbelievingly.
JENNY Don't you understand what you've done?
David looks at her.
This isn't going to be as easy as he thought.
DAVID I can see my behaviour must have been...
DAVID confusing.
DAVID But we've never sat down and had a proper chat about it all.
DAVID About the whys and wherefores.
DAVID They can wait.
DAVID The important thing is that you're still my Minnie Mouse, and I love you, and you had fun.
DAVID You know you had fun.
JENNY Yes.
JENNY I had fun.
JENNY But I had fun with the wrong person, at all the wrong times.
JENNY And I can't ever get those times back, now.(Beat) Look, David.
JENNY I'm in Oxford.
JENNY Every day I wake up and pinch myself.
JENNY And when I think how close I came...
She looks at him and shakes her head, as if awaking from a dream.
A young man stops behind her on his bike, dismounts, leans his bike against the wall next to hers, waits for her to finish.
She turns her back on David, and the young man offers her his arm.
They walk away together, and David stares longingly after them.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
