THE SOCIAL NETWORK
Written by
Aaron Sorkin
May 28, 2009
MARK (V.O.) Did you know there are more people with genius IQ's living in China than there are people of any kind living in the United States?
That can't be true.
MARK (V.O.) it is true.
What would account for that?
MARK (V.0.) Well first of all, a lot of people live
in China.
But here's my question:
MARK ZUCKERBERG is a sweet looking 19 year old whose lack of any physically intimidating attributes masks a very complicated and dangerous anger.
He has trouble making eye contact- and sometimes it's hard to tell if he's talking to you or to himself.
ERICA, also 19, is Mark's date.
She has a girl-next-door face that makes her easy to fall for.
At this point in the conversation she already knows that she'd rather not be there and her politeness is about to be tested.
The scene is stark and simple.
MARK How do you distinguish yourself in a population of people who all got 1600 on their SAT's?
ERICA I didn't know they take SAT's in China.
MARK I wasn't talking about China anymore, I was talking about here.
ERICA You got 1600?
MARK You can sing in an a Capella group.
Does that mean that you actually got nothing wrong?
MARK Or you row crew or you invent a 25 dollar
ERICA Or you get into a final club.
MARK Or you get into a final club, exactly.
ERICA I like guys who row crew.
Well I can't do that.
And yes, it means I got nothing wrong on the test.
ERICA Have you ever tried?
MARK I'm trying now.
ERICA To row crew?
MARK To get into a final club.
MARK To row crew?
MARK No.
MARK Are you, like--whatever--crazy?
ERICA Sometimes, Mark-seriously-YOU say two things at once and I'm not sure which one we're talking about.
MARK But you've seen guys who row crew, right?
ERICA No.
MARK Okay, well..
MARK they're bigger than me.
MARK They're world class athletes.
MARK And a second ago you said you like guys who row crew so I assumed you'd met one.
ERICA I guess I meant I liked the idea of it.
ERICA The way a girl likes cowboys.
MARK The Phoenix is good.
ERICA This is a new topic?
MARK It's the same topic.
ERICA We're still talking about the finals clubs?
MARK Would you rather talk about something else?
ERICA It's just that since the beginning of the conversation about finals clubs I think I may have had a birthday.
MARK We can change the subject.
There are more people in China with genius IQ's than the entire population of--
MARK It's about exclusivity.
.....what is?
MARK The final clubs.
MARK And that's how you distinguish yourself.
MARK The Phoenix is the most diverse.
MARK The Fly Club, Roosevelt punched the Porc.
ERICA Which one?
MARK The Porcellian, the Porc, it's the best of the best.
ERICA I actually meant which Roosevelt.
MARK Theodore.
ERICA Okay, well, which is the easiest one to get into?
MARK takes a cigarette from a pack, lights it, takes a drag and blows the smoke out before he says...
MARK Hm.
ERICA What?
MARK why would you ask me that?
ERICA I was just asking.
MARK They're all hard to get into.
MARK My friend Eduardo made $300,000 betting on oil futures last summer and he won't get in.
MARK Money or the ability to make it doesn't impress anybody around here.
MARK Everybody can do that.
ERICA He made $300,000 in a summer?
MARK He likes meteorology.
ERICA You said it was oil futures.
MARK If you can predict the weather you can predict the price of heating oil.
MARK You asked me that because you think the final club that's easiest to get into is the one where I'll have the best chance,
I've lost my place again.
MARK You asked me which one was the easiest to get into because you think that's where I have the best chance.
ERICA The one that's easiest to get into would be the one where anybody had the best chance.
MARK I just think you asked--the placement of where you asked the question--
ERICA I was honestly just asking.
ERICA Okay?
ERICA I was asking just to ask.
ERICA Mark, I'm not speaking in code.
MARK Erica--
ERICA You're obsessed with the finals clubs.
ERICA You have finals clubs OCD and you need to see someone about this who'll prescribe some sort of medication.
ERICA You don't care if side effects may include blindness, okay, just do it.
MARK Final clubs.
MARK Not finals clubs and there's a difference between being obsessed and being motivated.
ERICA Yes there is.
MARK Well you do--that was cryptic--so you do speak in code.
ERICA I didn't mean to be cryptic.
MARK I'm saving I need to do something substantial in order to get the attention of the clubs.
ERICA Why?
MARK Because they're exclusive.
And fun and they lead to a better life.
ERICA You think Teddy Roosevelt got elected president because he was a member of the Phoenix Club?
MARK He was a member of the Porcellian and yes I do.
ERICA Maybe he sang in an a Capella group.
MARK I want to be straight forward and tell you that I think you should be a lot more supportive.
MARK If I get in I'll be taking you to the parties and you'll be meeting people that you wouldn't normally get to meet.
You would do that for me?
MARK You're my girlfriend.
ERICA okay, well I want to be straight forward and tell you that I'm not anymore.
What do you mean?
ERICA I'm not your girlfriend anymore,
MARK Is this a joke?
ERICA No, I'm sorry, it's not.
MARK You're breaking up with me?
ERICA You're going to introduce me to people I wouldn't normally get to meet?
ERICA What the fuck is that supposed to mean?
MARK Take it easy.
ERICA What was it supposed to mean?
MARK It was--Erica, the reason we're able to sit here and drink is that you used to sleep with the door guy.
I want to really try not to lose it now.
ERICA (CONT'D) The door guy's name is Bobby.
ERICA (CONT'D) I haven't slept with the door guy, the door guy's a friend of mine.
ERICA (CONT'D) He's a perfectly good class of people and what part of Long Island are you from--England?
MARK I'm from Westchester.
ERICA I'm going back to my dorm.
Wait, wait, thisi reel?
ERICA Yes.
MARK I apologize, okay?
MARK Siddown.
ERICA I'm going back to my dorm, I have to study.
ERICA Yeah.
MARK I'm sorry and I mean it..
ERICA I appreciate that but--
MARK Come on.
ERICA ---I have to study.
MARK You don't have to study.
MARK Let's just talk.
ERICA I can't..
MARK Why?
ERICA Because it's exhausting.
ERICA Going out with you is like dating a stairmaster.
MARK All I meant is that you go to B.U. and so you're not likely to--I wasn't making a comment on your parents--I was saying you go to B.U.
ERICA I have to go study.
MARK You don't have to study.
ERICA How do you know I don't have to study?!
MARK Because you go to B.U.!
MARK ERICA stares at him...
Do you want to get some food?
ERICA I'm sorry you're not sufficiently impressed with my education.
MARK And I'm sorry T don't have a rowboat.
ERICA I think we should just be friends.
MARK I don't need friends.
I was being polite, I had no intention being friends with you.
MARK You're really leaving.
MARK ERICA takes MARK's hand and looks at him tenderly..
Listen, You're going to be successful and rich.
But you're going to go through life thinking that girls don't like you because you're a tech geek.
And I want you to know, from the bottom of my heart, that that won't be true.
It'll be because you're an asshole.
And with that stinger, ERICA walks off and we stay on MARK as the pulsing intro to Paul Young's "Love of the Common People"
ERICA (CONT'D) And you're never getting into a final club.
ERICA (CONT'D) Along with the MUSIC, we slowly push in on MARK.
ERICA (CONT'D) A fuse has just been lit.
Fall.
Semester, 2008
As MARK busts out of the bar, past Bobby the door guy and into the population of Harvard Square.
As MARK continues on, he passes a group of people heading in the opposite direction for a party.
As MARK's steady and determined stride continues, he'll.
pass by all kinds of (seemingly) happy, well-adjusted, socially adept people.
The vocals from the Paul Young song come in--
As the MUSIC CONTINUES and MARK busts into the lobby of his dorm.
He doesn't look at anyone as he heads up the stairs and
INT. MARK'S DORM ROOM - NIGHT A bedroom that's part of a three-bedroom suite.
INT. MARK'S DORM ROOM - NIGHT The MUSIC CONTINUES as MARK walks in, flicks his lap-top on without looking at it and walks out of frame as we stay on the laptop.
AND SHE CAN Then a moment or two later, a glass with ice gets set down next to the lap-top.
AND SHE CAN Then a carton of orange juice followed by a bottle of vodka.
AND SHE CAN MARK's fingers dance easily on the keyboard---like a Juilliard pianist warming up.
AND SHE CAN In the exact time it takes him to pour the vodka and orange juice over ice, the website he's just called up gets loaded onto the screen.
AND SHE CAN Zuckonit.com This is the only place he's comfortable.
He begins blogging.
Erica Albright'a??s a bitch.
You think that's because her family changed their name from Albrecht or do you think it's because all B.U, girls are bitches?
He takes a good gulp of his drink.
We see the words we're hearing filling up his computer screen--
Folks, for the record, she may look like a 34D but she's getting all kinds of help from our friends at Victoria's Secret, She's a 348, as in barely anything there..
False advertising.
Fresh ice gets dropped in the glass and a new drink poured.
"Love of the Common People" continues.
in back of MARK, sitting on the bed and hitting a bong, is
MARK (V.O.) The truth is she has a nice face.
MARK (V.O.) I need to think of something to help me take my mind off her.
MARK (V.O.) Easy enough, except I need an idea.
MARK (V.O.) MARK has moved his mouse to an icon on his desktop labeled "Kirkland Facebook".
MARK (V.O.) He clicks and opens it.
MARK (V.O.) A menu of photos appear.
MARK (V.O.) He blogs again.
MARK (V.0.) (CONT'D) I'm a little intoxicated, I'm not gonna lie.
MARK (V.0.) (CONT'D) So what if it's not even 10PM and it's a Tuesday night?
MARK (V.0.) (CONT'D) The Kirkland Facebook is open on my desktop and some of these people have pretty horrendous f acebook-pics.
MARK (V.0.) (CONT'D) Billy Olson's sitting here and had the idea of putting some of these girls' faces next to pictures of farm animals and have people vote on who's hotter.
INT. FINAL CLUB - NIGHT We'll be cutting back here a lot in this sequence, with the Paul Young song tying them together, as we show---mostly MOS--- preparations under way for the hottest party on campus tonight.
INT. FINAL CLUB - NIGHT We start on a good looking STUDENT fixing his tie in the bathroom mirror.
INT. FINAL CLUB - NIGHT He walks out of the bathroom and into the main area where he's immediately tossed a bottle of champagne by a similarly dressed STUDENT.
INT. FINAL CLUB - NIGHT We see that there are a couple of dozen other guys around.
INT. FINAL CLUB - NIGHT Our guy takes the champagne bottle and sticks it on the bar, which is being stocked by two sexy FEMALE uniformed BARTENDERS.
INT. FINAL CLUB - NIGHT Our guy walks past P. DJ's table where the DJ is setting up his incredibly high-end equipment.
INT. FINAL CLUB - NIGHT Our guy trots down a set of mahogany and red-carpet stairs, opens a heavy door and looks out to the sidewalk.
A BOUNCER in a tuxedo is standing by a velvet rope which is holding back three dozen STUDENTS.
The students are mostly women and the women are all dressed to catch a man.
Over all this, we HEAR MARK CONTINUINGa??
MARK (V.0.) Good call, Mr. Olson!
MARK (V.0.) I think he's on to something.
MARK (V.0.) (CONT'D) year it's on.
MARK (V.0.) (CONT'D) I'm not gonna do the farm animals but I like the idea of comparing two people together.
MARK (V.0.) (CONT'D) It gives the whole thing a very Turing feel since people's ratings of the pictures will be more implicit than, say, choosing a number to represent each person's hotness like they do on hotornot.com.
MARK (V.0.) (CONT'D) The first thing we're going to need is a lot of pictures.
MARK (V.0.) (CONT'D) Unfortunately, Harvard doesn't keep a public centralized facebook so I'm going to have to get all the images from the individual houses that people are in.
MARK (V.0.) (CONT'D) Let the hacking begin.
INT. MARK'S DORM ROOM - NIGHT There are two more kids-in the room with MARK--DUSTIN MOSKOWITZ and CHRIS.-BUGHES.
MARK (V.0.) First u is Kirkland.
MARK (V.0.) They keep everything open and allow indexes in their Apache configuration, so a little NGET magic is all that's necessary to download the entire Kirkland facebook.
MARK (V.0.) Kids' stuff.
MARK (V.0.) On the computer screen, we've been seeing him download picture after picture of Harvard girls.
THREE COES, dressed kill, are talking BOUNCER.
The BOUNCER O l up at TWO HAND CLUB ME BERS.
The MEMBERS give him the nod and the THREE COEDS are SOME M let past the velvet rope.
They're led.
in to a party in full swing.
The best and the brightest are checking out the hottest and the easiest.
INT. MARK'S DORM ROOM - NIGHT MARK finishes another drink and gets back to his work.
MARK (V.0.) Next is Elliot.
MARK (V.0.) They're also open but with no indexes on Apache.
MARK (V.0.) I can run an empty search and it returns all of the images in the database in a single page.
MARK (V.0.) Then I can save the page and Mozilla will save all the images for me.
MARK (V.0.) Excellent.
MARK (V.0.) Moving right along.
MARK (V.0.) Flying by at super-speed on MARR's computer screen have been commands and images that the rest of us can't possibly understand.
INT. FINAL CLUB - NIGHT GIRLS are dancing with each other, doing tequila shots with guys and laughing at jokes.
Over this we HEAR MARK's blog posts starting to cascade into
Lowell has some security.
They require a username/password combo and I'm going to go ahead and say they don't have access to main faa user database, so they have no way of--a??
MARK (V.O.) (CONT'D) Adams has no security but limits the
MARK (V.O.) (CONT'D) For Quincy I'm going to have to get a matching name and student I.D. combo and I'm in.
MARK (V.O.) (CONT'D) All I have to--
Ins'r ions and images fly across MARK'S sereen-
Dunster is intense.
Not only is there no public directory but there's no--
MARK (V.0.) (CONT'D) Leverett is a little better.
MARK (V.0.) (CONT'D) It's slightly obnoxious that they only let you view one picture at a time and I'm not
MARK (V.0.) (CONT'D) --definitely necessary to break out the emacs and modify that pert script.
And now anew guy walks into Mark's room.
This is EDUARDO SAVERIN--a sweet looking Brazilian sophomore who almost always wears a three--piece suit.
EDUARDO What's going on?
MARK (V.0.) Perfect timing.
MARK (V.0.) Eduardo's here and he's going to have the key ingredient.
EDUARDO Mark.
EDUARDO What's going on?
MARK Wardo.
EDUARDO Did you and Erica split up?
MARK How did you know that?
EDUARDO It's on your blog.
MARK Oh yeah.
EDUARDO Are you alright?
MARK I need you.
EDUARDO I'm here for you.
MARK No, I need the algorithm you used for the oil futures.
EDUARDO Are you okay?
MARK We're ranking girls.
EDUARDO Why?
MARK To watch the bottom 200's heads explode.
You think that's such a good idea?
MARY What's the algozithm?
The CLUB PRESIDENT is addressing the GUESTS from the top of
One of the oldest, one of the most exclusive clubs--not just at Harvard but in the world--and I want to welcome you to this year-'s first--
INT. MARK'S DORM ROOM - NIGHT EDUARDO' is writing an equation with a grease marker on the
window.
When the equation's done it looks like this:
1 + 10( b - Ra) / 400
EDUARDO Give each.girl a.-base rating of 1400.
EDUARDO At any time `Girl All has a rating R-a and "Girl B" has a rating R-b.
When any two girls are matched up there' an expectation of which will win based on their current rating.
EDUARDO Those expectations are expressed this way.
MARK Let's write it.
A few more attractive co-eds get let in through the velvet rope.
CUT TO t
MARK makes a few last key strokes and a new website comes up on the screen .
MARK makes a few more keystrokes and two pictures of two Harvard girls come up on the screen.
After a moment...
ALL The one on the left.
ALL MARK clicks the girl on the left and another picture takes the place of the girl on the right.
ALL (CONT'D) On the right.
ALL (CONT'D) MARY clicks the girl on the right while another picture takes the place of the girl on the left.
ALL (CONT'D) Still the right.
EDUARDO It works.
DUSTIN Who should we send it to first?
EDUARDO Dwyer.
CHRIS Neal.
EDUARDO Who are you gonna send it to?
EDUARDO MARK's made the link to e-mail and hits send.
MARK Just a Couple of people.
MARK The question is, who are they gonna send it to?
The party's in its drunken stage.
We move to a room where there's a co-ed poker game underway with the girls smoking cigars, Ai? 1/2 bra and a couple of pairs of stockings are out on the table, As move through the poker room, we see a computer behind one of the players.
The computer is indicating that there's e-mail.
A PLAYER 'turns around and opens the e-mail as the poker game and the party go on behind him.
at it, then He hits a.
link and FACEMASH opens.
He looks
Check this out..
INT. ANOTHER DORM ROOM - NIGHT TWO MALE STUDENTS at a laptop.
The one on the left.
ALL On the right.
A bunch of STUDENTS around a computer.
ALL The right.
Dozens of partiers are around the comp uter.
She's my roommate.
A bunch of students around the computer--
She will cut herself open if she gets a low score on this, can somebody figure out how to bust the curve?
INT. ANOTHER DORM ROOM - NIGHT A FEW STUDENTS gathered at a computer---
On the left.
ALL On the right.
INT. ANOTHER DORM ROOM - NIGHT This time just a single student in his pajamas as he looks at two pictures of girls side by side.
INT. ANOTHER DORM ROOM - NIGHT And another single student voting and
We should instantly know that this dorm room is different.
It's more modern and with less character and history than the others.
A girl is at her computer and in the background is another girl we can't quite make out who's taking notes from a , i extbook.
GIRL Oh shit,
GIRL Albright?
GIRL We rack focus to the studying girl and see that it's ERICA.
GIRL (CONT'D) He blogged about you.
GIRL (CONT'D) ERICA looks at her for a moment, then gets up to look at her
GIRL (CONT'D) No you don't want to read it.
GIRL (CONT'D) ERICA ignores her roommate, We see her mortification as she reads, and at that moment THREE GUYS appear in her open doorway- one of them wearing a padded bra over his Boston University sweatshirt.
GUY Erica.
GUY They lift, separate and support.
GUY Thanks for the tip.
GIRL Get the fuck out, The three guys go on their drunken way as we SLOWLY PUSH IN on ERICA who's frozen in her humiliation and then
STUDENTS The left!
STUDENTS The right!
STUDENTS The left!
STUDENTS The right!
INT. MARK'S DORM ROOM - NIGHT As sets of photos go flying by on his computer screen.
MARK is staring at the chaos of activity he's.cr.eated in the middle of the night.
EDUARDO Mark?
I wonder if maybe you.
shouldn't shut it down before you get into trouble.
MARK ignores him as we pre-lap a PHONE RINGING and
INT. BEDROOM - NIGHT A man named COX is asleep next to his wife.
INT. BEDROOM - NIGHT It's his phone that's RINGING.
INT. BEDROOM - NIGHT COX wakes up and answers it--
COX Hello?
Wait, what?
At 4 in the morning?
A tired GRAD STUDENT who spends the night monitoring the campus computer system is looking at his computer.
well there's a very unusual amount of traffic coming out of Kirkland House.
COX You're saying it's unusual for 4 in the morning?
GRAD STUDENT I'm saying it.
GRAD STUDENT would be unusual for Mother's Day.
COX Alright.
COX COX hangs up the phone.
I have to go in.
What's going on?
COX Harvard's computer system's about to crash.
INT. MARK'S DORM ROOM - NIGHT Pictures are flying by on Mark's computer when suddenly they freeze, Then an icon comes up telling him he's no longer connected to the internet.
INT. MARK'S DORM ROOM - NIGHT Everyone is frozen silent for a moment...
EDUARDO You don't think--
MARY I do,
EDUARDO Go see if it's everybody.
EDUARDO DUSTIN, CHRIS and EDUARDO head out of the room.
EDUARDO MARX drains what's left of the vodka and lights a cigarette as the guys start coming back in the room.
DUSTIN Mine's down.
CHRIS My computer's' frozen.
EDUARDO I mean ...unless it's a coincidence I think this is-Us,
MARK It's not a coincidence.
Holy shit.
Yeah,
It's three years later and MARK is sitting with his LAWYERS at a large conference table.
MARK is wearing a hoodie, sweatpants and Adidas flip-flops--a personal uniform that we'll come to understand.
And while it may take us a while to notice it, MARK's a different person in these flash-forward scenes.
Still tortured and complicated, but comfortable now with his own power.
His lawyer is SY, who's accompanied by some junior associates, one of whom--a pleasant, pretty and professional young contemporary of Mark's named MARYLIN, we'll get to know.
On the other side are EDUARDO and his lawyer, GRETCHEN, also a.
a?? mpanied by some associates.
A STENOGRAPHER is typing the recor..
The room is glass on two sides and through the windows we can see the behemoths of Silicon valley--Oracle, SunMicrosystems, Google, etc.
GRETCHEN is taking MARK's deposition.
GRETCHEN So you were called in front of the Ad Board.
MARK That's not what happened.
GRETCHEN You weren't called in front of the Administrative Board?
MARK No, back, I mean--That's--back at the bar with Erica Albright.
MARK She said all that?
MARK That I said that stuff to her?
GRETCHEN i was reading from the transcript of her
MARK why would you even need to depose her?
GRETCHEN That's really for us to--
MARK You think if I know she can make me look like a.
MARK jerk I'll be more likely--
MARK --to settle, right?
SY Why don't we stretch our legs a minute, can we do that?
SY It's been almost three hours and frankly you did spend an awful lot of time embarrassing Mr. Zuckerberg with the girl's testimony in the bar.
MART I'm not embarrassed, it's just that she made a lot of that up.
GRETCHEN She was under oath.
MARK Then I guess that would be the first time somebody's lied under oath.
MARK People are stretching and getting coffee and talking quietly.
MARK MARK stays in his seat.
MARK MARYLIN, the attractive second year associate who's on Mark's legal team is still sitting too...
MARK about four seats down from Mark.
MARYLIN Eight percent of the male population of Harvard had been on it within two hours?
Eighty.
MARYLIN What?
Eighty percent of the male population.
Wow.
The Harvard Crew is practicing on two-man sculls.
There are three boats that are running roughly even with each other and the two-man crews are rowing with all they've got.
We're gliding along with them in the water--
Bring up the rate!
2 in 2!
One..two--
BOAT) Power 10 in 2!
BOAT) In 2!
BOAT) They had open water after a hundred meters.
BOAT) I don't think we're gonna catch 'em today.
BOAT) And we PULL BACK TO REVEAL that there's a fourth boat which is already five boat, ngths ahead of the other three.
The fourth boat is being crewed by CAMERON and TYLER WINKLEVOSS----identical twins who stepped out of an ad for Abercrombie and Fitch.
They know that the others aren't in their class and even though they're highly competitive athletes, they don't like showing anyone up, least of all their teammates.
CAMERON Is there anyway to make this a fair fight?
TYLER We could jump out and swim.
CAMERON I think we'd have to jump out and drown.
TYLER I'm not willing to do that.
CAMERON What are we at three-quarter power?
CAMERON Let's drop down to a half.
TYLER Or you could row forward and I could row backward.
CAMERON I'd kick your ass.
TYLER We're genetically identical, so biology and mathematics says we'd stay in one place not allowing for the current or the wind.
CAMERON Just row the boat.
And the WINI{LEVOSS twins kick into full gear and open up an even wider lead as we.
Two stacks of The Crimson, Harvard's student newspaper, get dropped on the floor as TYLER and CAMERON walk by--their trays loaded with mountains of eggs and pancakes and carbs.
Everyone knows and loves them in this 200 year old dining hall and they wave and shout to a few people and whisper to a couple of very pretty girls before taking a seat next to DIVYA NARENDRA, a nice looking Indian student whose face is in a copy of the Crimson.
CAMERON What's up?
DIVYA You guys hear about this?
CAMERON What?
DIVYA Two nights ago a sophomore at Kirkland crashed the computers.
CAMERON Which computers?
DIVYA All of them.
DIVYA Be crashed the whole system.
DIVYA TYLER picks up a copy-of the Crimson and begins reading while his brother and DIVYA keep talking.
CAMERON How?
DIVYA He set up a website where you vote on the hotness of female Harvard undergrads.
DIVYA What were we doing that none of us heard about this?
CAMERON I don't know.
CAMERON Rowing, going to class, studying?
CAMERON How much activity was there on this thing that he crashed the--
22,000 votes.
There were 22,000 hits,
TYLER (CONT'D) Cam, this guy hacked into the facebooks of seven houses in two hours.
TYLER (CONT'D) He set up the whole site in one night while he was drunk.
CAMERON 22,000 hits?
TYLER Yeah.
CAMERON How do you know he was du- - - _
TYLER He was blogging simultaneously.
TYLER Divya?
DIVYA I'm way ahead of you.
TYLER This is our guy.
INT. SECOND DEPOSITION ROOM - DAY It's MARX and his LAWYERS again but this time on the other side of the table are TYLER and CAMERON, DLVYA and the.i.r lawyer, GAGE, whose family had first-class seats on the Mayflower.
INT. SECOND DEPOSITION ROOM - DAY we' .l.].
INT. SECOND DEPOSITION ROOM - DAY be back and forth between the two deposition rooms a lot,
CAMERON Cameron Winklevoss.
CAMERON W-I-N-K-L-E-VWO-S-S.
CAMERON Cameron's spelled the usual way.
TYLER Tyler.
TYLER Winklevoss.
TYLER Tyler's spelled the usual way and my last name is the same as my brother's.
MARK stands before a panel of ADMINISTRATORS as well as COX, the systems manager who was woken up in the opening sequence.
ADMINISTRATOR Mr. Zuckerberg, this is an Administrative Board hearing.
You're being accused of intentionally breaching security, violating copyrights and violating individual privacy by creating the website, WWW.FACEMASH.COM.
You're also charged with being in violation of the university's policy on distribution of digitized images.
Before we begin with our questioning you're allowed to make a statement.
Would you like to do so?
Uh...I've, you know, I've apologized in the Crimson to the ABHW, to Fuerza Latina and to any women at Harvard who might have been insulted as I take it they were by the things that have been said tome in the last week.
As for any charges stemming from the breach of security, I believe I deserve some sort of recognition from this Ad Board.
I'm sorry?
MARK Yes.
ADMINISTRATOR I don't understand.
MARK Which part?
ADMINISTRATOR You believe you deserve recognition?
MARK I pointed-out some pretty gaping holes in your system.
COX Excuse me, may I?
ADMINISTRATOR Yes.
COX Mr. Zuckerberg, I'm in charge of security for all computers on the Harvard system.
COX I can assure you of its sophistication and in fact it was that level of sophistication that led us to you in less four hours.
MARK Four hours?
COX Yes sir.
MARE That would be impressive except the algorithm I used was written on my dorm room window.
MARE Keep up the great work.
As the heavy wooden door from the hearing slams shut behind MARK.
EDUARDO is waiting for him.
EDUARDO Well?
MARK Six months academic probation.
MARK They walk out onto--
EDU.ARDO It could have been worse.
MARK No it couldn't.
MARK They made me apologize.
EDUARDO To who?
MARK To them.
MARK Over and over.
EDUARDO It's alright.
MARK No.
EDUARDO It's okay.
EDUARDO You're fine.
I shouldn't have said the thing about the farm animals.
That was stupid.
Everybody's mad at me now.
EDUARDO Maybe, but at least everybody knows you now.
MARX is in his Operating Systems class.
This is considered the hardest class at Harvard and MARK is one of the 50 students with their laptops open as the professor takes them through an impossibly difficult lesson,
So let's look at a sample problem: Suppose we're given a computer with a 16- bit virtual address and a page size of 256 bytes.
A GIRL scribbles something on a piece of paper.
Then hands it to the student next to her and nods that it should be passed over to MARK.
While that's happening--
PROFESSOR (CONT'D) The system uses one-level page tables, which start at address 0x0400.
PROFESSOR (CONT'D) Maybe you want to have DMA.
PROFESSOR (CONT'D) on your 16-bit system, who knows?
PROFESSOR (CONT'D) The first few pages are reserved for hardware flags, etc.
PROFESSOR (CONT'D) MARK opens the note., It reads "Asshole".
PROFESSOR (CONT'D) He looks over and sees a couple of GIRLS looking at him with contempt.
PROFESSOR (CONT'D) Assume page table entries have eight status bits.
PROFESSOR (CONT'D) MARK closes his laptop, gets up and starts to head out of the hall.
PROFESSOR (CONT'D) The eight status bits would be--
And I see we have our first surrender.
Don't worry, Mr. Zuckerberi? 1/2 , brighter, men than you have tried and failed at this class.
1 valid bit, 1 modify bit, 1 reference bit and 5 permission bits.
MARK walks out of the lecture hall and we
As MARK comes out and heads onto the quad--
Mark?
CAMERON and TYLER have been waiting by the entrance.
CAMERON (CONT'D) Are you Mark?
MARK Yeah.
CAMERON I'm Cameron winklevoss.
TYLER Tyler Winklevoss.
Are you guys related?
CAMERON Good.
TYLER That's funny.
CAMERON We've never heard that before.
MARK Did I insult your girlfriends?
MARK What can I do for you?
CAMERON No, you didn't insult our girl--
Actually, I don't know.
We never asked.
CAMERON We should do that.
TYLER Yeah.
CAMERON No, we have an idea we want to talk to you about.
CAMERON Do you have a minute?
You guys look like athletes.
CAMERON We are.
MART What do you do?
TYLER We row crew.
MARK Yeah, I've got a minute.
The most exclusive of all the final clubs.
DIIVYA is sitting in the main living room with a textbook open as the heavy wooden door opens and MARK is escorted in by TYLER and CAMERON.
TYLER You ever been in the Porcellian?
MARK No.
TYLER We can't take you past the living room but we can sit here and talk.
DIVYA H i..
DIVYA MARK is stealing a glance around the room...
CAMERON Mark?
CAMERON This is Divya Narendra, our partner.
MARK Hi.
DIVYA We were really impressed with Facemash and then we checked you out and you also built CourseMatch.
DIVYA MARK is looking at the framed black and white group pictures on the wall.
DIVYA of old Porcellian classes.
DIVYA He sees a pretty co-ed on the couch with her legs stretched over her boyfriend while they study.
DIVYA (CONT'D) Mark?
MARK Yeah .
CAMERON CourseMatch.
CAMERON You go online, you get to see what courses your friends are taking?
MARK Yeah.
DIVYA And you invented something in high school.
MARK An app for an MP3 player that recognizes your taste in music.
DIVYA Anybody try to buy it?
MARK Microsoft.
DIVYA How much did they pay?
MARK I didn't sell it.
MARK I uploaded it for free.
DIVYA MARK gives a short shrug that says both "I don't know" and "Fuck you" at the same time.
3n,
CAMERON Well we've been working for a while on an idea.
CAMERON It's called HarvardConnecti.on.
CAMERON You create your own page, Picture, bio, interests, friends.
TYLER People can see your bio and request to be
MARK Yeah.
MARK How's this different from MySpace or Friendster?
TYLER How?
MARK Yeah.
TYLER Harvard-dot-E--D-U.
CAMERON Harvard.edu.
CAMERON The most prestigious e-mail address in the country.
TYLER This site would be based on the idea that girls want to meet guys who go to Harvard.
TYLER The difference between what we're talking about and MySpace,
MARK --is exclusivity,
Right?
Yes.
CAMERON We want you to be an equal partner.
CAMERON Our first programmer graduated and went to work at Google.
CAMERON Our second programmer just got overwhelmed with school work.
CAMERON We want you to write the code and build the site and we'll provide---
MARK I'm in.
CAMERON --the money.
CAMERON What?
MARK I'm in.
The WINKLEVOSSES and DIVYA with GAGE.
GAGE "I'm in"?, that's what you said?
MARK It was three or four years ago, I don't know what I said.
INT. FIRST DEPOSITION ROOM - DAY EDUARDO with GRETCHEN.
GRETCHEN When did you come to Eduardo?
MARK I don't understand that question.
GAGE Do you remember answering in the affirmative?
MARK The affirmative?
GRETCHEN I'm asking when you came to Eduardo with the idea for Facebook.
MARK It was called TheFacebook back then.
GAGE This doesn't need to be that difficult.
MARK I'm in the middle of two different lawsuits.
GAGE Did you answer affirmatively?
GAGE When Tyler and Cameron Winklevoss and Divya Narendra asked you to build HarvardConnection, did you say yes?
MARK I said I'd help.
GRETCHEN When did you approach Mr. Saverin with the idea for TheFacebook?
MARK I wouldn't say I approached him.
GRETCHEN Sy?
SY You can answer the question.
MARK It was at a party at Alpha Epsilon Pi.
GRETCHEN What's that?
MARK The Jewish fraternity.
MARK It was Caribbean Night.
The lecture hall has been converted into "Alpha Epsilon Pi Caribbean Night, 2003" and the party is about as lame as it sounds.
What's important is that this couldn't be less like the final club party we saw at the beginning if they were playing Pin the Tail on the Donkey.
Some potted palm trees have brought in along with a steel drum set.
The man playing the steel drum set has a yarmulke bobby pinned to his thinning hair.
A table with a punch bowl and assorted cookies is nearby.
EDUA.RDO, in baggy cargo shorts and a Hawaiian shirt buttoned up to the top, is standing with a few similarly dressed friends, including DUSTIN MOSKOWITZ and CHRIS HUGHES, in the sparsely populated room.
On the other side of the room are a few girls--all Asian.
One of the girls is wearing a bikini over her clothes.
A television monitor has been set up with a.
DVD running of Niagara Falls.
EDUARDO It's not that guys like me are generally attracted to Asian girls.
EDUARDO It's that Asian girls are generally attracted to guys like me.
DUSTIN I'm developing an algorithm to define the connection between Jewish guys and Asian girls.
EDUARDO I don't think it's that complicated.
EDUARDO They're hot, they're smart, they're not Jewish and they can't dance.
CHRIS Mark's here.
CHRIS They see MARK come in and look around.
CHRIS EDUARDO waves him over...
Mark.
MARK sees EDUARDO and waves him over to where he is.
He wants to talk privately.
EDUARDO (CONT'D) I'll be back in a minute.
EDUARDO (CONT'D) EDUARDO joins MARK in the back of the room and they take up a spot next to a bay window that's covered on the outside with ice.
MARK I think I've come up with something.
E DUARDO Hang on, I've gotta tell you something you're not going to believe.
MARK What?
EDUARDO I got punched by the Phoenix.
Are you kidding?
EDUARDO No.
EDUARDO I mean it's just the first of the four step process but they slipped the invitation under my door tonight.
EDUARDO T go to the first punch party tomorrow and if they like me--
MARK Yeah.
EDUARDO --I get the second invitation and then the third and then who knows?
MARK You got punched by the Phoenix.
It was, you know ...I'm sure it was just a diversity thing, And I'm never gonna make it in, it was just a diversity thing.
So I'll just ride that'horse until--what did you want to talk about?
Mark?
MARK Yeah.
EDUARDO You said you think you've come up with something.
EDUARDO It seems like MARK's just made a small decision in his head,
Yeah.
I think I've come up with something.
Come outside.
EDUARDO It's 20 degrees outside.
MARK I don't want to stare at that loop of Niagara Falls which has absolutely nothing to do with the Caribbean.
MARK and EDUARDO come outside and are immediately met by the freezing cold air.
MARK People came to Facemash in a stampede, right?
EDUARDO Yeah.
MARK It wasn't because I put up pictures of hot girls.
MARK You can go anywhere on the internet and see pictures of hot girls.
EDUARDO Yeah.
MARK It was because I put up pictures of girls that people knew.
MARK So if people Want to go on the internet and check out their friends, why can't I build a website that offers that?
MARK An online community of friends.
MARK Pictures, profiles, whatever you can click into, visit, browse around.
MARK All from the privacy of your dorm room.
MARK I'm not talking about a dating site.
MARK I'm talking about taking the entire social structure of college and putting it online.
EDUARDO I can't feel my legs.
MARK I know, I'm totally pumped about this.
EDUARDO "It would be exclusive".
MARK --it would be exclusive.
MARK You'd have to know the people on the site to get in.
MARK Like getting punched.
EDUARDO This is interesting.
MARK Like our own Final club except not only can we get into this one, we're the president.
EDUARDO I told him I thought it sounded great.
EDUARDO I mean it did, it was a great idea.
EDUARDO There was no reason to hack, people were going to put their own pictures up.
EDUARDO What they were interested in, what they were looking for, what classes they were taking...
EDUARDO and people had the ability to invite their friends to join.
EDUARDO Or put a different way, not invite their friends to join.
EDUARDO In a world where social structure is very important, that was sexy.
It was a big project and he was going to have to write tens ofa??thousands of lines of code so I wondered why'he was coming to me and not his roommates.
Dustin Moskowitz and Chris Hughes were programmers.
MARK We're gonna need a little start-up cash to rent'the servers and get it online.
EDUARDO That was why.
GRETCHEN Did he offer business terms?
MARK We'll split it 70-30.
MARK 70 for me and 30 for you for putting up a thousand dollars and handling everything on the business end.
MARK You'll be CFO.
GRETCHEN And you said?
EDUARDO I said "Let's do it".
GRETCHEN Okay.
GRETCHEN Did he add anything else?
EDUARDO Yes.
EDUARDO He said---
MARK It probably was a.
MARK diversity thing but so what?
GRETCHEN Why do you think he said that?
Gretchen, what's the relevancy?
GRETCHEN This is discovery, I'm trying to discover.
MARK They're suggesting I was jealous of Eduardo and began a plan to screw him out of the company.
GRETCHEN Were you?
MARK Jealous of Eduardo?
SY Stop typing, we're off the record.
MARK Ma'am, I know you've done your homework and so you know that money isn't a big part of my life, but at the moment I could buy Harvard University, take the Phoenix Club and turn it into my ping pong -room.
EXT. QUAD - NIGHT EDUARDO's walking away and calls back to MARK--
I'll let you know how the party is, We stay on MARK for a moment longer, his wheels turning,
INT. SECOND DEPOSITION ROOM - DAY EDUARDO's in different:.clothes and being questioned by GAGE.
GAGE We recognize that you're a plaintiff in one suit involving Facebook and a witness in another.
EDUARDO Yes sir,
GAGE At any time in the three weeks prior to Mark telling you his idea, did he mention Tyler Winklevoss, Cameron Winklevoss, Divya Narendra or HarvardConnection?
EDUARDO Yes.
EDUARDO He said they'd asked him to work on their site but that he'd looked at what they had and decided it wasn't worth his time.
EDUARDO Uhh, he said even his most pathetic friends knew more about getting people interested in a website than these guys.
GAGE "These guys" meaning my clients.
EDUARDO Yes.
EDUARDO He resented--Mark resented that they- --that your clients, probably thought he would jump at the chance to rehabilitate his image after the Facemash thing but Mark didn't want to rehabilitate anything.
EDUARDO With Facemash he'd beaten the Harvard computers, he'd beaten the Ad Board and he made the girls mad.
EDUARDO Facemash did what he wanted it to do.
EDUARDO MARK kind of nods a little to himself.
EDUARDO It should be noted that these depositions have an extra element of dish ort as everything is being said within a few feet of the peop" being talked about.
GAGE Were you aware that while Mr. Zuckerberg was building TheFacebook he was also communicating with the plaintiffs?
EDUARDO Not at the time I wasn't.
EDUARDO I am now.
GAGE Were you aware that while Mr. Zuckerberg was building TheFacebook, he was leading the plaintiffs to believe he was building Harvard Connection?
SY I have some problems with that question.
EDUARDO No I wasn't.
EDUARDO MUSIC kicks in that will tie this next section together as we
INT. MARK'S DORM ROOM - NIGHT Two printouts of web pages are taped to a white board-- "Friendster" and "MySpace".
INT. MARK'S DORM ROOM - NIGHT Under the two pages, MARK draws a third page and titles it "TheFacebook".
INT. MARK'S DORM ROOM - NIGHT Then he makes the decision to turn the capital "T" into a lower case "t" and it becomes "theFacebook" as we
From mark Zuckerberg to Tyler Winklevoss.
November 30, 2003.
"I read over all the stuff you sent me re Harvard Connection and it seems like it shouldn't take too long to implement, so we can talk about it after I get all the basic functionality up tomorrow night."
INT. MARK'S DORM ROOM - NIGHT The whiteboard is filled with diagrams now under the heading "theFacebook"--login page,, profile page, create account-We move over to see MARK at his computer.
INT. MARK'S DORM ROOM - NIGHT He opens the Emacs program and then Firefox, hits a few keys and the diagram on the whiteboard comes-to life on his computer as we
GAGE Mark Zuckerberg to Cameron Winklevoss.
GAGE December 1, 2003.
GAGE "Sorry I was unreachable tonight.
GAGE I just got about three of your missed.
GAGE calls.
GAGE I was working on a problem set for my systems class."
GAGE CAMERON and TYLER are looking blankly at MARK who's giving them a casual "I'm not scared.of'a??you" look and we
The MUSIC CONTINUES as EDUARDO and other prospective new members, all wearing tuxedos, are lined up in four rows.
The boy at the front of each row has a bottle of Jack Daniels and drinks as long as they can before passing the bottle, relay style, to the boy in back of him as a few seniors look on.
EDUARDO gets handed the bottle and starts in as we
It's an Art History class and as we run past the rows of STUDENTS we see that they all have the same painting up on their laptops as the PROFESSOR gives his lecture.
When we get to MARK's laptop we see that he's writing code for theFacebook
GAGE Mark Zuckerberg to Cameron and Tyler Winklevoss.
GAGE December 10, 2003.
GAGE "This week has been pretty busy thus far with classes and work so I think it's probably best to postpone the meeting."
CAMERON, TYLER and DIVYA are reading the e-mail.
"I'm also really busy tomorrow."
Anybody else feel like there's something up with this guy?
CAMERON Tell him okay but we've gotta make sure we meet before we all head off for break.
INT. EDUARDO'S DORM ROOM - NIGHT EDUARDO's at his desk with his head in a thick textbook when an envelope that says "Phoenix" is slipped under his door.
INT. EDUARDO'S DORM ROOM - NIGHT Be turns and looks to see it-then pumps his fist in victory as
Every available wall space is covered with a diagram or a printout.
EDUARDO comes in with the envelope.
MARK I need a dedicated Linux box running Apache webserver with a mySQL backend.
MARK It's gonna cost a little more money.
EDUARDO How much more?
MARK Two-hundred more.
EDUARDO Do we need it?
MARK To handle the traffic.
EDUARDO Do it.
MARK I already did.
EDUARDO Hey, guess what?
EDUARDO I made the second cut.
MARK Good job.
MARK You should be proud of that right there, don't worry if you don't make it any further.
EDUARDO I'll get outa,here.
INT. SECOND DEPOSITION ROOM - DAY The MUSIC CONTINUESa??
Mark Zuck'erberg to Tyler and Cameron Winklevoss and Divya Narendra.
December 15, 2003.
"I have" a cs problem set that I'm just getting started with and it should be about 15 hours of coding so I'll be busy tomorrow night."
"I won't really be free to meet until next Wednesday afternoon."
.have to cancel Wednesday afternoon.
I've basically been in the lab this whole time and also..."
DIArYA's reading 'off his blackberry to TYLER and CAMERON--
"Won't be able to do it Saturday as I have to meet up with my parents to.."
The MUSIC CONTINUES-- It's snowing and cold as hell.
EDUARDO's now with a smaller group of prospective members, most of whom are in their underwear with a couple of them wearing pants.
They're all blue and shivering.
They're gathered around a statue of John Harvard as a senior announces--
SENIOR As the plaque reads, this is John Harvard, founder of Harvard University in 1638.
SENIOR It's also called The Statue of Three Lies.
SENIOR What are the three lies?
Sir!
SENIOR Mr. Dowd,
SOPHOMORE The three lies--
Shit!
SENIOR Take your pants off.
EDUARDO I know.
SENIOR Mr. Saverin.
EDUARDO 1) Harvard was founded in 1636, not 1638.
EDUARDO 2) Harvard wasn't founded by John Harvard and 3) That's not John Harvard.
SENIOR who is it?
EDUARDO A friend of the sculptor, Daniel.
EDUARDO Chester-
SENIOR You can?-.-tpi your shirt on.
SENIOR And as another kid simply falls to his hands and knees and throws up, we
INT. EDUARDO'S DORM ROOM - NIGHT EDUARDO's studying at his desk but this time wrapped in blankets and wearing gloves when the envelope with "Phoenix" gets slid under his door.
INT. EDUARDO'S DORM ROOM - NIGHT He smiles.
GAGE 39 days after Mr. a??Zuokerberg's initial meeting with my clients and he still hadn't completed work on HarvardConnection.
GAGE But on January 11,
INT. MARK'S DORM ROOM - DAY A website called Network Solutions is up on Mark's screen.
INT. MARK'S DORM ROOM - DAY He hits a couple of keys and waits intently.
INT. MARK'S DORM ROOM - DAY Then the computer shows him what he wanted to see-- www.theFacebook.com-a??--DOMAIN NAME REGISTERED
GAGE To the best of your knowledge, had he even begun work on HarvardConnection?
EDUARDO Not to my knowledge.
INT. CAMERON AND TYLER'S DORM ROOM - NIGHT CAMERON's looking at his e-mail.
CAMERON what in the hell is this?
TYLER What?
"I'm still a little skeptical that we have enough functionality in the site to really draw the attention and gain the critical mass necessary to get a site like this to run."
GAGE This is the first time he mentioned any problem?
DIVYA Yes it was.
GAGE You'd sent 39 e-mails to Mr. Zuckerberg and received 13 return e-mails and this was the first time--
DIVYA He had 42 days to study our system and get out ahead on---
MARK Do you see any of your code on Facebook?
GAGE Sy?
MARK Did I use any of your code?
DIVYA You used our whole fuckin' idea!
Gentlemen.
MARK Match-dot-com for Harvard guys?
GAGE Can I continue with my deposition?
MARK You know you really don't need a damn forensic team to get to the bottom of this.
MARK If you guys were the inventors of Facebook you'd have invented Facebook.
DIVYA I'm just gonna stand over your shoulder while you write is a check.
MARK No shit.
Let's continue, DIVXA'a still staring at MARK, who just smiles a little as he looks down.
February 4th, 2003-
MARK is working at a station.
We can see through the windows that it's a frigid, snowy February day in Cambridge but MARK':: in his hoodie and cargo shorts nonetheless.
It looks like he hasn't slept in days..
On his monitor we can see that he's working on the profile page for theFacebook.
DUSTIN MOSKOWITZ steps up to him quietly,
DUSTIN Mark?
Mark.
MARX turns his head and looks at him...
There's a girl in the art history class that you take.
Her name is Stephanie Attic, Do you happen to know if she has a boyfriend?
MARK just keeps looking at him--barely even blinking---"Why am I being interrupted?"
I mean, have you ever seen her with anyone?
And if not, do you happen to know if she's looking to go out with anyone?
Dustin.
People don't walk around with a sign on them that says-- And MARK stops short right there.
Because in his head, he's just discovered the cure for cancer.
Mark?
As MARK, with his backpack stuffed, comes flying out of the building and into the snow, barely keeping his balance on the ice and we
The heavy door bursts open and MARK comes busting through.
He makes his way with speed and intent up a flight of stairs.
Then another.
And then another until he gets to his floor.
He sprints down his hall toward his dorm room and barely notices EDUARDO leaning against the door.
EDUARDO We were supposed to meet at 9.
EDUARDO MARK is searching the pockets of his shorts for his keys.
EDUARDO (CONT'D) Have you slept yet?
EDUARDO (CONT'D) MARK opens the door and they go into his suite--
MARK I have to add a feature.
EDUARDO What are you adding?
MARK's in his own world as he sits at the computer and calls up theFacebook.
The home page fills the screen.
Shit.
That looks good.
That looks really good.
MARK It's clean and simple.
MARK No flashing lights.
MARK The CAMERA surveys the screen as MARK slips through some functions to show EDUARDO and we see things that are now familiar--A photo, sex, a profile, a list of attributes, a poke application, etc.
MARK MARK (cONT' T) ) But watch.
MARK MARK's called up a the Emacs program and quickly writes out several lines of code...
EDUARDO What'd you write?.
EDUARDO MARK goes back to the profile page.
EDUARDO There's a new area to be filled in...
MARK "Relationship Status", "Interested In".
These two things are what drive life at college.
Are you having sex or aren't you.
It's why people take certain classes, sit`where they sit, go where they go, do what they do, and at its, um, center,`you know, that's what theFacebook is gonna be about, People are gonna log on because after all the cake and watermelon there's a chance they're gonna-
EDUARDO --meet a girl.
MARK --get laid.
MARK Yes.
EDUARDO Really?
And that's it.
What do you mean?
MARK It's ready.
EDUARDO It's ready?
MARK Yeah.
EDUARDO Right now?
MARK It's ready, that was it.
MARK And here's the masthead, MARK hits another couple of keystrokes and the website's masthead comes up.
EDUARDO You made a masthead.
MARK Yeah.
"Eduardo Saverin, Co-Founder and CFO."
MARK Yeah.
EDUARDO You have no idea how much that's going to mean to my father.
MARK Sure I do.
When's it gonna go live?
MARK Right now.
MARK Get your laptop out.
EDUARDO Why do we need my laptop?
MARK Because you've got e-mails for everyone at the Phoenix.
I'm not sure if it's gonna be cool with them that I spammed their--
MARK It's not Spam.
EDUARDO I didn't mean Spam, it's not Spam, it's
MARK If we send it to our friends it'll just bounce around the computer lab,
EDUARDO I haven't gotten in yet.
MARK These guys know people and these guys know girls.
MARK I need their e-mails.
Sure.
EDUARDO takes out his laptop--
MARK Let's start with the president.
EDUARDO "Jabberwockl2@Harvard E-D-U."
MARK Like the Lewis Carrol?
EDUARDO Yeah.
EDUARDO MARK opens up an e-mail and is writing a short message, then includes a link to the site--
MARK These guys.
EDUARDO I know,
MARK Think they're literary geniuses because the world's most obvious Lewis Carroll reference is in their--
EDUARDO They're not so bad.
MARK I'm just saying.
EDUARDO You're right.
Okay.
He hits "Send".
MARK (CONT'D) The site's live.
You know what?
Let's go get a drink and celebrate.
MARK is staring at the computer...
EDUARDO (CONT'D) Mark?
EDUARDO (CONT'D) MARK doesn't hear him.
EDUARDO (CONT'D) We just see MARK's head from the back and it's ever so slightly bobbing back and forth...
Mark?
Are you praying?
THE CROCODILLOS, Harvard's oldest male a Capella group, are singing at the front of the pub in their usual uniform of white tie and tails.
Incongruously, but with surprisingly nice results, the group is covering a song from The Backstreet-Boys--"I Want it That Way"--and the pub full of students is loving it.
We find a table in the back where DIVYA is sitting with some of his friends who are having a nice time.
DIVYA's got his laptop open.
MALE FRIEND When did the Crocodillos start covering the Backstreet Boys?
MALE FRIEND What happened to Cole Porter and Irving Berlin?
FEMALE FRIEND It's a Valentine's theme.
FEMALE FRIEND They're singing love songs.
MALE FRIEND Good point, 'cause Cole Porter and Irving Berlin never wrote any love songs,
FEMALE FRIEND Divya, what are you reading?
DIVYA Seven different people spammed me the same link.
DIVYA We see DIVYA click his mouse on the link--
FEMALE FRIEND What is it?
I don't know, but I'm really hoping it's video of kittens that look like the Marx Brothers 'cause I can never get enough file footage on my computer of animals doing...
DIVYA trails off.
We Slowly PUSH IN on his face as the blood starts draining away...
Div?
DIVYA I--uh...I have to go.
DIVYA DIVYA shuts his laptop, grabs it off the table and starts to bolt out of the pub.
DIVYA His foot gets caught on a chair leg and he falls hard face-first to the floor.
DIVYA (CONT'D) Shit.
DIVYA (CONT'D) He starts out again, then comes back for his coat, grabs it; starts out and falls down all over again.
DIVYA (CONT'D) Finally he's got it together and flies out of the pub and we
CAMERON and TYLER are rowing in a large practice tank--a simulator with a hull, oars and rowable water.
They're focused and charging away in perfect sync when the door at the end of the century-old boathouse opens and DIVYA charges In from the co:Ld with his laptop and a copy of the Crimson in his hands.
Hey!
The twins are in the zone and don't pay any attention.
Hey !
CAMERON Not now, we've got another 5000 meters.
Okay.
I just wanted to let you know Zuckerberg stole our website.
TYLER stops rowing and then CAMERON.
They look at DIVYA...
DIVYA (CONT'D) Mark Zuckerberg stole our website.
DIVYA (CONT'D) It's been live for over 36 hours.
They're in gear.
CAMERON's taken a quick shower but didn't dry off'.
He's in sweatpants with a towel over his shoulder, talking on the phone with his father and holding the Crimson.
DIVYA's on his cell looking for MARK and TYLER, still in his practice clothes, has his desktop computer open to theFacebook and is studying it.
I left a message with his R.A., I left two, now I'm leaving one here.
I'm looking at the article in the Crimson.
Narendra.
Today's.
N-A---just tell him Divya, he knows who I am.
(clicks off phone and starts to dial another number) Asshole knows who I am.
It's titled, "Hundreds Register for New Facebook Website" and then the sub- headline is "Facemash creator seeks new reputation with latest online project."
It's me again.
Can you try looking for his roommates?
Their names are Chris Hughes and Dustin Moskowitz.
No it's today's paper, it went online yesterday morning around 10.
I don't have the slightest idea.
Mr. Hotchkiss.
Thank you.
CAMERON Ty, the lawyer's on the phone with dad.
I'm here with my brother, Tyler, and our partner, Divya.
TYLER "Welcome to theFacebook, TheFacebook is an online directory that connects people through social networks.
TYLER You must have a Harvard.edu address to register."
That's right.
I called earlier.
I'm looking for Mark Zuckerberg.
Yes sir, he's quoted a couple of times.
I can read--it says, "'Everyone's been talking a lot about a universal .facebook within 1 arvard', he says"--he meaning Mark--"I think it's kind of silly that it would take the University a coupl-e-af years to get around to it.
I can do A? better than they can and I did in a week."
Could you leave word that Divya Narendra called, I appreciate it.
I know, that's how he talks.
DIVYA (off another copy of the
"As of yesterday evening, Zuckerberg said over 650 students had registered to use theFacebook.com.
He said he anticipated that 900 students would have joined the site by this morning."
Yeah, Divya was just reading that he'd signed up 650 people on the first day.
TYLER If I were a drug dealer I couldn't give free drugs to 650 people in one day.
DIVYA And this kid doesn't have four friends.
CAMERON Guys, please, for just one second.
That's what we'll do, Mr. Hotchkiss.
We're gonna put it all, together right now and e-mail it to you.
You won't be able to get on the site yourself.
CAMERON (CONT'D) Because you went to Ohio State.
CAMERON (CONT'D) But we'll take care of everything and we'll talk to you first thing in the morning.
CAMERON (CONT'D) This is a
Whoa !.
--and he's very bright and I'm sure he didn't mean to...do what he did.
Thank you very much, and dad, we'll talk to you in the morning too.
Thanks.
CAMERON hangs up,
DIVYA This is a good guy?
CAMERON We don't know that he'.s not a good guy.
DIVYA We know that he took our idea and stole it.
DIVYA We know that-he lied to.
DIVYA our faces for a month and a half-while he--
CAMERON He didn't lie to our faces.
DIVYA He never saw our.
DIVYA faces!
DIVYA Fine, he lied to our e-mail accounts and he got himself a 42-day head start because he knows what apparently you don't which is that getting there first is everythinal
CAMERON I'm a competitive racer, Div, I don't think you need to school me on the importance of getting there first.
Alright.
That was your father's lawyer on the phone with you?
CAMERON Yeah, well his in-house counsel, We're gonna send him everything and he'll look at it and if he thinks it's appropriate he'll send a cease and desist letter.
DIVYA A cease and desist letter doesn't have any teeth.
CAMERON You think we should hire lawyers and sue him?
DIVYA I think we should hire lawyers and have them beat him senseless with a crescent wrench.
TYLER We don't have to do that.
CAMERON That's right.
TYLER We can do it ourselves.
TYLER I'm six-five, 220-pounds and there are two of me.
CAMERON And I'm saying let's Calm down until we know what we're talking about.
DIVYA Just how much more information are you waiting for?
DIVYA We met with Mark three times, we exchanged 52 e-mails, we can prove that he looked at the code, he'd seen what Victor had already done and we talked at length about what we planned to do.
The page looks the same:
What is that on the bottom?
CAMERON It says "A Mark Zuckerberg Production".
DIVYA On the home page?
CAMERON On every page.
DIVYA Hang on, 'cause I need a minute to let the classiness waft over me.
Cam.
(he recites from the Crimson thout having to read it) They wr "Zuckerberg said that he hoped the prly options would help to restore his reputation following student outrage over Facemash.com".
That's exactly what we said to him.
He's telling us to go fuck ourselves.
We know plenty of people at the Crimson.
While we're waiting for dad's lawyer to look this over, we can at least---
CAMERON No.
TYLER --get something going in the paper so that people know-
CAMERON What?
TYLER That this thing is in dispute.
CAMERON We're not starting a knife fight in the Crimson and we're not suing anybody.
DIVYA Why not?
DIVYA CAMERON wants-to answer the question but doesn't..
DIVYA (CONT'D) Why not?
CAMERON He'll say it's stupid.
TYLER Me?
CAMERON Yeah.
DIVYA Say it.
DIVYA Why not?
CAMERON Because we're gentlemen of Harvard.
This is Harvard.
You don't plant stories and you don't sue people.
That's why.
There's a right way to do things.
You thought be was going to be the only one who thought that was stupid?
GAGE During the time when you say you had this idea, did you know that Cameron and Tyler carne from a family of means?
A family of means?
GAGE Did you know that his father was wealthy.
I'm not sure why you're asking me that.
GAGE It's not important that you be sure why I'm asking you.
MARK It's not important to you.
GAGE Sy.
Did you know that they came from money?
MARK I had no idea whether they came from money or not.
GAGE In one of your e-mails to Mr. Narendra you reference Tate Winklevoss' consulting firm.
If you say so.
GAGE Tate Winklevoss founded the firm and its assets are in the hundreds of millions.
MARK or roughly the amount I paid in income tax last year, go on.
GAGE You also knew that Cameron and Tyler were members of a Harvard final club called the Porcellian.
MARK They made a point of pointing that out.
TYLER Excuse us for inviting you in.
Hey.
So it's safe to say you were aware that my clients had money?
MARK Yes.
GAGE Let.me tell you why I'm asking.
GAGE I'm wondering why, if you needed a thousand dollars to start up your project, you didn't ask my clients for it.
GAGE They'd demonstrated to you an interest in this kind of thing so--
MARY From that you're deducing that I didn't go to them because I didn't want them to know what I was working on?
MARY I went to my best friend for the money because he's who I wanted to be partners with because of our similar vision and his superior business skills.
MARY Eduardo was president of the Harvard Investors Association and he was my best friend.
GAGE Your best friend is suing you for 600- million dollars.
MARK I hadn't heard, tell me more.
SY Eduardo, what happened after the initial launch?
GRETCHEN I'm sorry, Sy, would you mind addressing him as Mr. Saverin?
SY They're best friends, Gretchen.
GRETCHEN Not anymore.
SY We just went through this on the-- nevermind.
SY Mr. Saverin, what happened after the initial--
It exploded.
DIVYA Everyone on campus was using it.
DIVYA "Facebook me" was a common expression after two weeks.
SY And Mark?
DIVYA Mark was the biggest thing on a campus that included 19 Nobel.
DIVYA Laureates, 15 Pulitzer Prize winners, two future Olympians and a movie star.
SY Who was the movie star?
Does it matter?
SY No.
EXT./EST.
AUDITORIUMi - NIGHT The lamps in Harvard Yard light the snow falling.
The seminal event for me was when he was in Harvard Square and picked up a copy of Popular Electronics Magazine that ha the MITS Altair Kit on the cover.
There's a lower-level and a balcony and both are full.
MARK and EDUARDO are sitting in the second to last row of the balcony.
We'll hear the SPEAKER but we'll only get to see him in a slightly blurry image as our attention is on MARK and EDUARDO.
SPEAKER And it was a clear day, And I was up in my Radcliffe dorm.
SPEAKER And he brought that up there and said, "Look, it's going to happen without us.
SPEAKER We've got to do it now."
SPEAKER And so I said..."
SPEAKER Okay."
SPEAKER He gets an appreciative LAUGH from the STUDENTS.
SPEAKER (CONT'D) Now the startinga??of this industry was very humble indeed.
SPEAKER (CONT'D) The kit computer on the cover-of that magazine-- We HEAR a little muffled giggling coming from the row behind MARK and EDUARDO, MARK is too into the speech to notice but the giggling registers as a slight annoyance on EDUARDO's face.
SPEAKER (CONT'D) --had an 8080 processor in it, and you had to assemble it yourself and it came with 256K of memory.
SPEAKER (CONT'D) EDUARDO hears the giggling again and turns around.
SPEAKER (CONT'D) In the row behind them and a few seats over are two beautiful Asian students.--ALICE and JENNY.
SPEAKER (CONT'D) They're a little overly made- up for a lecture.
SPEAKER (CONT'D) JENNY, the one sitting closest to EDUARDO, is wearing a short skirt with a white shirt: open one button too far down the front and we can see a hint of the red bra she's wearing underneath.
She leans forward and whispers to EDUARDO--
Your friend--isn't that Mark Zuckerberg?
You know Mark?
JENNY Didn't he make theFacebook?
JENNY EDUARDO smiles a little ...this has just never happened--
EDUARDO Yeah.
EDUARDO Both of us.
EDUARDO It's mine and his.
EDUARDO It's our--we're--yes.
Way cool.
I'm Jenny.
This is Alice.
EDUARDO can't help noticing--just because it's in his line of sight--that down the row from the girls, someone else is pointing at them and whispering to a friend.
Then back to the girls--
Very nice to meet you.
Facebook me when you get home.
Maybe we can all go out for a drink later.
Certainly.
I'll certainly--absolutely I will do that.
EDUARDO turns back to the speaker, who MARK hasn't taken his eyes off of--
SPEAKER There were a set of machines that came after that.
SPEAKER The TRS-80, Apple II,
As the CROWD from the lecture spills out onto the snowy quad.
EDUARDO--always in his suit-.-is buttoning up his overcoat as he walks and MARK zips up his hoodie.
EDUARDO She said "Facebook me" and we can all have a drink later.
EDUARDO Which is stunningly great for two reasons.
EDUARDO One, she said "Facebook me".
EDUARDO Right?
EDUARDO And the other is that, you know--
MARK They want to have drinks later.
EDUARDO Yes: Have you ever heard so many different good things packed into one ordinary-sized sentence?
EDUARDO A group of guys hustle up to MARK and EDUARDO--
STUART Excuse me.
STUART Mark?
MARK Yeah.
STUART I'm Stuart Singer.
STUART I'm in your O.S. lab.
MARK Sure.
STUART Awesome job with theFacebook.
Awesome job.
MARK Thanks.
BOB I'm Bob.
MARK How you doin'.
BOB You know, I could swear he was looking at you when he said the next Bill Gates could be right in this room.
MARK I doubt it.
BOB I showed up late, I don't even know who he was.
It was Bill Gates.
BOB Oh shit, that makes sense.
BOB As MARK and EDUARDO walk on, we leave STUART, VIKRAM and BOB in the background---with STUART and VIKRAM admonishing BOB with--
Are you a moron?/Are you medically stupid?/You can't recognize Bill Gates when he's standing in front of you for an hour?/Mark Zuckerberg now thinks we got into Harvard on a dimwit scholarship./I'm gonna get a Glock 39 and I'm going to kill you./I'm actually going to kill you/etc.
INT. MARK'S DORM ROOM - NIGHT As the door opens and MARK and EDUARDO come into the overheated warmth of the room.
EDUARDO It's time to monetize the thing.
MARK Those Asian girls were cute.
MARK What were their names?
EDUARDO Did you hear what I said?
MARK When?
EDUARDO I said it's time to monetize the site.
MARK What does that mean?
EDUARDO I mean it's time for the website to generate revenue.
MARK No I know what the word means.
MARK I'm asking how do you want to do it?
EDUARDO Advertising.
MARK No.
MARK What were their names?
EDUARDO We've got 4000 members.
MARK 'Cause theFacebook is cool.
MARK If we start installing pop-ups for Mountain Dew it's
EDUARDO Well I wasn't thinking it would be Mountain Dew but at some point--and I'm speaking as the business end of the
MARK We don't even know what it is yet.
MARK We don't know what it is, what it can be, what it will be.
MARK We know it'a??s cool, that's a -priceless asset and we're not giving it up.
MARK EDUARDO is sitting at MARK's desk and he's seen something sitting on top of a pile of'books.,,
EDUARDO Mark, what is this?
MARK What, EDUARDO holds up a letter that's on a lawyer's stationary.
EDUARDO This,
MARK I think it's called a cease and desist letter.
MARK What were their names?
EDUARDO Who?
MARX The girls.
MARX EDUARDO's speed reading the letter.
EDUARDO When did you get this?
MARK About 10 days ago.
MARK Right after we launched the site.
EDUARDO Jesus Christ.
MARK I liked th shorter one.
EDUARDO They're saying--the Winklevoss twins are saying you stole their idea.
MARK I find that to be mildly annoying.
EDUARDO They find it to be property theft.
EDUARDO Why--
EDUARDO --why didn't you show this to me?
MARK It was addressed to me.
EDUARDO They're saying we stole theFacebook from Divya Narendra and the Winka??
MARX I know what it says.
Did we?
MARK What?
EDUARDO Please don't screw around with me now.
MARK I'm not.
EDUARDO Look at me.
MARK What are you, my mother?
EDUARDO The letter says we could face legal action.
MARK No, it says I could face legal action.
EDUARDO It's from a lawyer, Mark.
EDUARDO They must feel they have some grounds for--
MARK The lawyer is their father's house counsel, I checked it out, they're not,
EDUARDO Do they have grounds?
MARK Yes, the grounds are theFacebook is cool.
MARK and popular and sexy and HarvardConnection is lame.
MARK I didn't use any of their code, I didn't use anything.
MARK A guy who builds a really nice chair doesn.'t owe money to everyone who,,, ever built a chair.
MARK Th ey came to me with an idea, I had a better one.
EDUARDO Why didn't you show me the letter?
MARK I didn't think.
MARK it was a big deal..
EDUARDO If there's' something wrong--if there's ever anything wrong--you can tell me.
EDUARDO I'm the guy who can help.
Is there anything you need to tell me?
MARK No,
EDUARDO What are we doing about this?
MARK I went to a 3-L at Student Legal services and he told me to write them back.
EDUARDO What did you say?
"When we met in January, I expressed my doubts about the site--where it stood with graphics, how much programming was left that I had not anticipated--
"---the lack of hardware we had to deal with, the lack of promotion that was needed to successfully launch the website--
"--etc."
This was the first time you raised any of those concerns, right?
MARK I'd raised concerns before.
Bullshit./Not to us.
Fellas.
I'm talking about at the meeting in January to which this letter is referring.
MARK Yeah.
GAGE Let me re-phrase this.
GAGE You sent my clients 32 e-mails.
GAGE In the first 31, you didn't raise any concerns.
Is that a question?
GAGE In the 32nd e-mail you raised concerns about the site's functionality.
GAGE Were you leading them on for six weeks?
MARK No.
GAGE Why hadn't you raised any of these--
It's snowing.
GAGE I'm sorry?
MARK It just started snowing.
GAGE Mr. Zuckerberg, do I have your full attention?
MARK No.
Do you think I deserve it?
. MARK What.
GAGE Do you think I deserve your full attention?
MARK I had to swear an oath before we began the deposition phase and I don't want to get arrested for perjury so I have a legal obligation to say no.
GAGE Okay.
GAGE "No" you don't think I deserve your attention.
MARX I think if your clients want to stand on my shoulders and call themselves tall they have a right to give it a try.
MARX But there's no requirement that I enjoy being here listening to people lie.
MARX You have part of my attention--the minimum amount needed.
MARK (CONT'D) The rest of my attention is back at the offices of Facebook where my employees and I are doing things that no one in this room, including and especially your clients, are intellectually or creatively capable of doing.
MARK (CONT'D) Did I adequately answer your condescending question?
MARK (CONT'D) GAGE just looks casually at MARK.
MARK (CONT'D) MARK doesn't meet his gaze, or the looks from DIVYA, TYLER and CAMERON...
I've got 12:45.
Why don't we.say that's lunch.
GAGE Back at 2:30?
SY Good.
SY Everyone gets np and we
INT.
MARK'S DORM ROOM -a?? NIGHT
EDUARDO puts the letter back on.
the desk and looks at MARK...
Their names were Jenny and Alice- They want to have drinks tonight.
It's a nice men's room--mahopny stalls--in a nice club in Cambridge.
We HEAR the thumping of the house music coming from the club.
And then one of the wooden stall doors flies open and EDUARDO is shoved in, followed by JENNY, who did the shoving.
She's all over him as she presses him back against the divider.
EDUARDO's hands are sliding under JENNY'S white shirt and finding the red bra when they hear a noise.
Someone's gone into the next stall.
Shit.
I don't care.
JENNY keeps him pinned against the divider as she reaches down and unbuckles his belt.
EDUARDO (quietly--nervous).
EDUARDO Oh God.
That's right.
And then he hears another noise from the stall next door.
A thump against the divider.
JENNY's got his fly unzipped.
EDUARDO looks down at the space between the stalls.
He sees a pair of Adidas flip-flops.
Then the sound of moaning, Before EDUARDO has time to say anything, JENNY pulls her shirt open, revealing the red bra, and puts her hand down his pants as we
MARK and EDUARDO are standing guard outside the door.
They're silent but very happy.
A guy comes along to use the men's room.
EDUARDO Sorry.
EDUARDO It'll just be a minute.
EDUARDO Some girls are freshening up in there.
GUY Sweet.
GUY The guy goes off...
Mark.
We have groupies.
MARK can't help a smile.
Then he sees something...
MARK I'll be right back.
EDUARDO Where you going?
MARK makes his way through the crowd toward a round booth.
A girl is sitting there and even though her back is to MARK he can recognize her.
She's with a girlfriend and three guys.
When he makes it to the booth he says--
MARK Erica?
MARK ERICA, from the opening scene, turns her head and looks up to see MARK.
MARK She's looking sexy for her Friday ni.ght on the town and the three guys she's with are studs.
MARK A few more friends of theirs are standing around at the edges of the booth.
Hi Mark.
MARK I saw you from over there.
MARK I didn't know you came to this club a lot.
ERICA It's my first time.
MARK Mine too.
MARK It's not bad.
MARK It's not.
MARK great.
MARK The music's kind of lame.
MARK Could I talk to you alone for a second?
ERICA I think I'm good right here.
MARK okay.
MARK MARK is aware of everyone else around the booth.
I don't know if you heard about this new website I launched.
ERICA No.
MARK ThePacebook?
ERICA You called me a bitch on the internet, Mark.
MARK I'm really sorry about that.
ERICA On the internet.
MARK That's why I came over.
ERICA comparing women to farm animals?
MARX I didn't end up doing that.
ERICA It didn't stop you from writing it.
ERICA As if every thought that tumbles through your head is so clever it would be a crime for it not to be published.
ERICA The internet's not written in pencil, Mark, it's written in ink and you published that Erica Albright was a bitch.
Right before you made some ignorant crack about my family's name, published my bra size and then rated women-based on their hotness.
Why don't you say it to me now, why don't say it to my face?
MARK I don't want to.
Erica, is there a problem?
ERICA No, there's no problem.
You're not a real person, Mark.
You write your bullshit from a dark room because you're a failure at human contact.
I liked you and I was nice to you.
I came over to say I was sorry for all that and to see if there was any chance--
ERICA I don't want to be rude to my fxiends, I should be talking to them.
MARK Okay.
ERICA Hey Mark.
ERICA A year from now you won't remember this conversation and you won't remember me.
MARK I think you're wrong.
ERICA Well...
ERICA listen, good luck with your video game.
ERICA It was an honest mistake on ERICA's part but a kidney punch to
Okay.
MARK turns and goes and sees that EDUARDO has been standing at and watching from a distance with JENNY.
EDUARDO That was cool, you did good.
EDUARDO You talked to her, that was the right thing to do.
It was good, Mark.
We have to expand.
EDUARDO What?
MARK We have to expand.
MARK And MARK heads out the door.
MARK EDUARDO watches MARK and then looks back at the girls and answers the un-asked question--
I don't know.
ALICE Is he mad about something?
INT. MARK'S DORM ROOM - NIGHT The door closes behind DUSTIN MOSKOWITZ and CHRIS HUGHES.
INT. MARK'S DORM ROOM - NIGHT MARK and EDUARDO are waiting and JENNY and ALICE are sitting on the bed.
INT. MARK'S DORM ROOM - NIGHT Everyone's got a beer.
INT. MARK'S DORM ROOM - NIGHT Once the door is closed--
MARK We're expanding theFacebook to Yale and Columbia.
MARK Dustin, I want you to share.
MARK the coding work with me.
MARK Chris, you're going to be in charge.
MARK of publicity and outreach.
MARK You can start by getting a story about the expansion in the B.U.
MARK student newspaper.
CHRIS They hate doing stories about Harvard.
Somebody at the newspaper will be a computer science major and they will have heard of me.
Tell 'em Mark Zuckerberg will do 10 hours of free programming for theno .
EDUARDO Why do you want a story in the B.U.---
MARK Because I do.
MARK Here's the business arrangement.
MARK Eduardo's CFO and owns 30% of the company, Dustin's Vice President and Head of Programming and his 5% of the company will come from my end.
MARK Chris is Director of Publicity and his compensation will depend on the amount of work he ends up doing.
MARK Any questions?
DUSTIN Who are the girls?
EDUARDO Jenny and Alice,
JENNY Is there anything we can do?
MARK No.
MARK That's it.
MARK Yale and Columbia, let's go.
And Stanford.
MARK What?
Stanford.
Its time for them to see this in Palo Alto.
INT. FIRST DEPOSITION ROOM - DAY MARK is sitting alone in the now empty room.
INT. FIRST DEPOSITION ROOM - DAY There's a computer on a table in the corner and MARK makes a few keystrokes and then reads the screen.
INT. FIRST DEPOSITION ROOM - DAY MARYLIN, the young lawyer we met early on, comes in with a plastic salad container in her hand and sits at the far end of the table from MARK, who doesn't acknowledge her.
MARYLIN You don't want any lunch?
No.
MARYLIN You're welcome to some of my salad.
MARK No thank you.
I know this must be hard.
MARK who are you?
MARYLIN I'm Marylin Delpy, I introduced myself this morning.
MARK I mean what do you do?
MARYLIN I'm a second year associate at the firm.
MARYLIN My boss wanted me to sit in on the deposition phase.
MARYLIN MARK nod--.
MARYLIN (CONT'D) What are you doing?
MARK Checking in to see how it's going in Bosnia.
MARYLIN Bosnia?
MARYLIN MARK nods...
MARYLIN (CONT'D) They don't have roads but they have Facebook?
MARYLIN (CONT'D) MARK nods..,
MARYLIN (CONT'D) You really hate the Winklevoss twins, don't you.
MARX I don't hate anybody.
The Winklevi aren't suing me for intellectual property-theft.
They're suing me because for the first time in their lives the world didn't work the way it was supposed to for them.
TYLER and CAMERON are both studying when DIVYA busts in.
DIVYA He's expanding.
TYLER What?
DIVYA He's expanding to Yale, Columbia and Stanford, it'll be in the Crimson tomorrow.
Really.
DIVYA Yeah.
83.a??
TYLER So that cease and Desist letter really scared the shit out of him, huh?
DIVYA I want to hire a lawyer to file for injunctive relief and get this website taken down now!
DIVYA Every minute it's up, Harvard Connection becomes less valuable, I want an injunction, I watt damages, punitive relief and I want him dead.
CAMERON I want those things too!
DIVYA Then why aren't we doing anything about it?!
DIVYA Because we're gentlemen of Harvard?!
CAMERON Because you're not thinking about how it's going to look.
DIVYA How's it going to look?
CAMERON Like my brother and I are dressed in skeleton costumes chasing the Karate Kid around a high school gym.
DIVYA He violated Massachusetts state law.
DIVYA Then when he goes to Connecticut, New York and California he'll have violated federal law.
DIVYA And by the way, he's violated Harvard law.
CAMERON There's no such thing as Harvard Law.
Wait.
Yes there is.
Cam, there is.
TYLER goes to the bookshelf and pulls down a manual.
TYLER (CONT'D) Harvard Student Handbook.
TYLER (CONT'D) Every freshman is issued this book.
TYLER (CONT'D) Somewhere in here it
--you can't steal from another student.
This is what we needed.
DIVYA You think campus security is going to arrest him for copyright violation?
CAMERON We're going to meet with the president.
DIVYA You can't get a meeting with Larry Summers.
CAMERON My brother and I pay tuition at this school, we carry a 3.9 GPA at this school, we've won trophies for this school and we'll be rowing in the Olympics for this school.
CAMERON I want a damn meeting with the-president of this school.
Why Stanford?
DIVYA Why do you think?
A pretty 20 year-old co-ed, AMY, pulls a curtain open and the darkened room immediately fills with un-welcomed sunlight.
AMY You don't know my name, do you?
AMY AMY's wearing nothing but a Stanford sweatshirt and talking to a skinny 22 year-old guy who's lying on her futon.
AMY There's other evidence on the walls that we're at Stanford University.
AMY There are also pieces of AMY'S clothing strewn about.
AMY The young man on the futon is SEAN PARKER.
SEAN Is that something that's important to y ou?
AMY Yes.
SEAN If I say your name will you stop the enhanced interrogation techniques?
AMY Yes.
SEAN Amy.
AMY Nice.
AMY What's my major?
Trombone.
AMY Really?
SEAN I remember something about a trombone.
AMY That was the beer bong.
AMY Tu fais l'amour A la jolie fille et la mete de cote.
SEAN French!
SEAN Your major is French.
AMY Oui.
AMY And what's yours?
SEAN My major?
AMY Yes.
SEAN I don't have one.
AMY You haven't declared?
SEAN I don't go to school here.
AMY You're kidding?
SEAN No.
AMY Where do you go to school?
SEAN Grover Cleveland Elementary.
AMY Seriously, you're not like 15 years old or anything are you?
SEAN No, I'm 22.
You're not like 15 years---
AMY No.
SEAN Good.
AMY So what do you do?
SEAN I'm an entrepreneur.
AMY You're unemployed.
I wouldn't say that.
What would you say?
SEAN That I'm an entrepreneur.
What was your latest preneur?
SEAN Well...I founded an internet company that let college kids download and share music for free.
AMY Kind of like Napster?
SEAN No, exactly like Napster.
What do you mean?
SEAN I founded Napster.
AMY Sean Parker founded Napster.
SEAN Nice to meet you.
You're Sea - arker?
SEAN Ah, you see, the shoe's on the other, uh, table which has turned.
AMY I just slept with Sean Parker?
SEAN All night long, Sister Souljah.
AMY You're a millionaire.
SEAN Not technically.
AMY What are you?
SEAN Technically?
AMY Yeah.
SEAN Broke.
SEAN There's not a lot of money in free music.
SEAN Even less when you're being sued by everyone who's ever been invited to the Grammys.
AMY I think you're cool.
SEAN He too.
AMY I have to hop in the shower and get ready for class.
AMY There's juice or anything else you can find.
AMY Help yourself.
SEAN You mind if I check my e-mail?
AMY Go ahead.
AMY AMY heads into the bathroom but leaves the door a little ajar..
AMY SEAN steps over to AMY's pink laptop and hits a key to wake it out of sleep mode.
AMY The shower starts running in the bathroom.
AMY The laptop springs to life and is open to something SEAN's never seen before--a Facebook page.; He sees AMY's picture and a short profile: Her major at Stanford, courses she's taking, books she likes, clubs she's a.
AMY member of...
Amy?
She can't hear him in the shower.
SEAN explores around a little more.
He knows his way around a computer.
He sees her "friends".
Friend after friend after friend.
Jesus.
He gets up and goes to the bathroom door--
SEAN (CONT'D) Amy?
SEAN Can'you come out here?
AMY Just a second.
SEAN There's a fire, Amy.
What?!
AMY grabs a towel and jumps out of the shower--
Where?:
SEAN Okay, there isn't a fire, but I need to ask you something.
AMY Are you kidding?!
SEAN No.
AMY I could have been killed!
SEAN I3ow?
What do you need to ask me?
SEAN I went to check my e-mail and there's a website open on your computer.
AMY Yeah.
AMY After you went unconscious last night I went on theFacebook for a while.
SEAN What's that?
AMY 'iheFacebook?
AMY It.
AMY started at Harvard and standford's had it for about two weeks and it's awesome except it's addictive.
AMY Seriously, I'm on the thing five times a day, all my friends are.
SEAN You mind if I grab a piece of paper and a pen?
AMY What's wrong?
SEAN Absolutely nothing.
SEAN It's beautiful.
AMY What are you talking about?
SEAN I need to find...
SEAN says a??A SEAN scrolls down to the bottom of the page where it Mark Zuckerberg Production"
SEAN (CONT'D) .Mark Zuckerberg.
CAMERON and TYLER, in dark suits, are waiting to see the president of Harvard, The President's office is in one of the two oldest university buildings in the country, and the SECRETARY sitting at the desk i ven older.
You get the sense that she thinks Harvard would be d -better place if it weren't for all, these students.
She looks at them and the boys give her a polite smile and a small nod before she goes back to her work.
CAMERON I've never been in this building.
SECRETARY This building is a hundred years older than the country.it's in.
Hm.
SECRETARY So do be careful.
TYLER We're just siting in the chairs.
Yes_.
Very good.
She hangs up the phone.
You can go in now.
She points to a door and CAMERON and TYLER get up, quickly straighten themselves, and walk into
LARRY SUMMERS, a large man, is on the phone at his desk in his well-appointed office.
A fire crackles in the sitting area and a 40-ish African-American woman, ANNE, in a pants suit is nearby going over some papers.
SUMMERS waves the boys in--
That's just their own stupidity, I should have been there.
Darkness is the absence of light and stupidity in that instance was the absence of me.
SUMMERS motions for them to sit and they do.
They take in some of the photographs around the room---SUMMERS with BILL CtINTON, etc.
Catherine, I have students in my office now.
Students.
Under.
grads.
I don't know, from the looks of it I think they want to sell me sets of identical Brooks Brothers suits.
We'll speak later.
SUMMERS hangs up the phone--
SUMMERS (CONT'D) Good morning.
CAMERON Good morning, s_ir.
CAMERON I'm Cameron Winklevoss and this is my brother, Tyler.
CAMERON CAMERON is extending his hand but instead of taking it, SUMMERS reaches to the top of a pile of papers and pulls a ten- page letter off the top.
SUMMERS Why are you here?
SUMMERS There's silence while SUMMERS appears to read over the letter...
SUMMERS (CONT'D) That wasn't rhetorical.
CAMERON I'm sorry, I thought you were reading the letter.
SUMMERS I've read the letter.
CAMERON Well I think it's pretty self- explanatory.
CAMERON We had an idea for a website called HarvardConnection--we've since changed the name to ConnectU--and Mark Zuckerberg stole that idea and--
SUMMERS What do you want me to do about it?
SUMMERS CAMERON points to a row of Harvard Student Handbooks on the bookshelf behind SUMMERS.
Well sir, in The Harvard Student Handbook, which is distributed to each freshman--under the heading "Standards of Conduct in the Harvard Community" and the sub-heading, "Honesty"--
SUMMERS Oh dear God.
CAMERON --it says, "The College expects that all students will be honest and forthcoming in their dealings with members of this community.
CAMERON All students are required to respect private and public ownership.
CAMERON Instances of theft, misappropriation or unauthorized use of or damage to property
SUMMERS Excuse me, Anne?
ANNE Yes sir.,
SUMMERS Punch me in the face.
SUMMERS Go ahead-.
--will result in disciplinary action, including the requirement to withdraw from the College."
That's what is says in the handbook.
SUMMERS When did you memorize that?
TYLER (a little frustrated with this
Sir, it's against University rules to steal.
from another student, plain and simple.
SUMMERS You've spoken to your R,A.?
CAMERON Yes sir, and the R.A. made a recommendation to the Ad Board but the Ad Board won't hear us.
SUMMERS Have you tried dealing with Mr.
SUMMERS Zuck.e.rberg directly?
CAMERON Mr. Zuckerberg hasn't responded to any of our e-mails or phone calls for.
CAMERON the last' two weeks.
CAMERON He doesn't answer when we knock on his door at Kirkland and the closest we've come to talking face to face is when I saw him on.
CAMERON the quad and chased him through Harvard Square.
SUMMERS You chased him?
I saw him and I know he saw me and I started after him and he disappeared
SUMMERS You know he could have you arrested for harassment and attempted assault.
This isn't happening.
SUMMERS I don't see this as a University issue.
TYLER Of course it's a University issue.
TYLER There's a code of ethics and an honor code and he violated them both.
SUMMERS You entered into a code of ethics with the university, not with each other.
I'm sorry President Summers, what you just said makes no sense to me at all.
SUMMERS I'm devastated by that.
CAMERON What my brother means is that if Mark Zuckerberg walked into our dorm room and stole our computer it would be a university issue, right?
SUMMERS I really don't know.
SUMMERS This office doesn't handle petty larceny and the only reason I agreed to see you--Anne; by did I agree to see them?
ANNE Colleagues of their father.
SUMMERS So you see?
TYLER This isn't a petty larceny.
TYLER This idea is potentially worth millions of dollars.
SUMMERS Millions of dollars?
CAMERON Yes.
SUMMERS You might be letting your imagination run away with you.
TYLER With all due respect I don't think you're in any position to make that call.
SUMMERS I was U.S. Treasury Secretary, I'm in some position to make that call.
TYLER Letting our imaginations run away with us is exactly what we were told to do in your freshmen address.
SUMMERS Well.
SUMMERS I would try letting your- imaginations run away with you on a new project.
TYLER You would.
SUMMERS Everyone at Harvard is inventing something or starting a new business in their dorm room- Harvard undergraduates believe that inventing a job is better than getting one so can I suggest again that the two of you come up with a new new project?
CAMERON I'm sorry, but that-'s not the point, sir.
SUMMERS What's the point?
CAMERON You don't have to be an intellectual property expert to understand-the, difference between right and wrong.
SUMMERS And you're saying that I don't?
CAMERON Of course I'm not saying that.
TYLER I'm saying that.
TYLER SUMMERS looks at TYLER and then smiles...
TYLER (CONT'D) Just start another project?
TYLER (CONT'D) Like we're making a diorama for the science fair?
SUMMERS Yes.
SUMMERS And if you have a goddam problem with that, Mr. Winklevoss, the courts are always at your disposal.
SUMMERS Athletes don't get special treatment at this school.
TYLER Do they get fairness?
SUMMERS They don't get to run to daddy.
SUMMERS Okay?
SUMMERS This isn't 50 years ago.
TYLER Excuse me, sir, but in your analogy, is daddy our father or you?
SUMMERS Both.
SUMMERS Is there anything else I can do for you?
Well I wouldn't mind that much if you took a flying--
Ty.
Thank you for your time, sir.
We appreciate your seeing us.
SUMMERS Get the door on your way out, would you?
As CAMERON and TYLER exit, TYLER closes the door a little too hard and the brass doorknob comes off in his hand.
He drops it on the SECRETARY'S desk as he exits
TYLER I broke your 335 year old doorknob.
GRETCHEN Eduardo, spring break, you and Mr.
GRETCHEN Zuckerberg took a trip to New York.
EDUARDO Yes.
GRETCHEN What was the purpose of the trip?
EDUARDO As CFO, I'd set up some meetings with potential advertisers.
GRETCHEN Who paid for the trip?
EDUARDO It was paid for out of the thousand dollar account I'd set up a few months earlier.
GRETCHEN At this point your thousand dollars was the only money that had been put into the company.
EDUARDO Yes.
GRETCHEN How did you feel the meetings'went?
EDUARDO They went terribly.
GRETCHEN Why?
EDUARDO Mark was asleep.
MARK I wasn't asleep.
EDUARDO Can I re-phrase my answer?
GRETCHEN Sure.
EDUARDO I wish he'd been asleep.
EDUARDO, in a three-piece suit, is pitching the EXECUTIVE.
MARK, in his hoodie and flip-flops, is completely detached and staring at the floor.
EDUARDO .and we're at 29 schools now with over 75,000 members.
EDUARDO People who go on theFacebook tend to stay on longer than almost any other site and here's the most impressive statistic--67% of people who try it once come back.
EDUARDO Now if you'll
EXECUTIVE Excuse me.
EDUARDO Yes sir.
Are we boring him?
GRETCHEN There was one more meeting scheduled for the New York trip.
EDUARDO Yes.
EDUARDO A dinner.
EDUARDO It was set up through my girlfriend at the time.
GRETCHEN Would you say that mark was excited about this meeting?
EDUARDO Yes, very,
INT. 66 - NIGHT 66 is a hip and trendy restaurant in Tribeca.
INT. 66 - NIGHT The young crowd is drinking cocktails of all different colors and wearing Prada, We FIND EDUARDO,.in a three-piece suit and MARK in his hoodie and flip-flops, along with EDUARDO's now-girlfriend, JENNY, sitting at a table.
INT. 66 - NIGHT with an empty seat waiting.
JENNY They're not gonna card us here.
EDUARDO They might.
JENNY Look around.
EDUARDO It' :l.l be embarrassing,
Tell him they're not gonna card us.
MARK They're not gonna card us.
MARK Are you gonna talk about ads again?
EDUARDO Unless you're the Ballet Theatre of Hartford, the urpose of a business is to make a profit.'
MARK This isn't a business.
EDUARDO That's tough for me because I'm the business head of the company.
EDUARDO MARK says nothing...
He's 25 minutes late.
MARK He's a god, he can be as late as he wants.
EDUARDO He's not a god-
MARK What is he?
EDUARDO 25 minutes late.
JENNY I think Wardo's jealous.
EDUARDO I honestly wasn't jealous.
EDUARDO I was nervous.
GRETCHEN Why?
EDUARDO I didn't know him at all but I'd done an internet search and asked around.
EDUARDO He struck me as kind of a wild man.
JENNY Why?
EDUARDO He crashed out of two pretty big internet companies in-spectacular fashion and he's got a reputation with drugs.
MARK He also founded'the companies.
EDUARDO We don't need him.
MARK He's here.
MARK SEAN PARKER has stepped into the restaurant and is.
MARK saying hello to the hostess while hugging a waitress.
EDUARDO And he does own a watch.
EDUARDO SEAN stops at a table to shake hands with a guy in a suit and kiss his girlfriend.
EDUARDO It's sort of an incongruous sight--this 22 year old kid who's able to work a room like Sinatra.
EDUARDO Who the hell is this?
(quiet] ) .
Take your time...
JENNY Stop it.
JENNY SEAN makes his way'over to MARK's table--
SEAN I'm Sean Parker.
How do you do.
SEAN You must be Eduardo, And Jenny.
SEAN And Mark, its great to meet you.
Great to meet you.
SEAN You guys don't have anything in front of you.
EDUARDO We were waiting for--
SEAN .Cori.
WAITRESS Hey baby boy.
SEAN Could you bring out some things?
SEAN The lacquered pork with that ginger confit?
SEAN I don't know, tuna tartar, some lobster claws, the foie gras and the shrimp dumplings, that'll get us started.
SEAN Jenny, what do you like to drink?
JENNY An appletini?
SEAN Great.
SEAN Four.
EDUARDO From that point on it was a Sean-a-thon.
EDUARDO I'd never seen anyone perform a monologue at dinner before but that's what happened.
INT. 66 - NIGHT The CA[ERA is moving around the table as SEAN--in and out of MOS-a??-is telling story after story while food is brought, drinks put down, more food brought and more drinks put down.
INT. 66 - NIGHT MARK is enthralled, JENNY is sexy and EDUARDO is polite.
EDUARDO (V.O.) He took us through his episode with Napster .
SEAN tried to sell the company to pay the 35 million they said we owed in royalties and in the end we just had to declare bankruptcy but I made a name for myself.
JENNY I'll say.
JENNY EDUARDO (V.o.)
JENNY And then he went to his second business venture which was Plaxo, an online rolodex.
SEAN See, we had a VC from the beginning.
SEAN Michael Moritz, a partner at Sequoia Capital who'd invested in Yahoo and Google.
SEAN Moritz wanted to push me out from
ginning and he hired private detectives to dig up everything on me they could.
Did they find anything?
No.
But I was out of the company.
I'm not done with Moritz and Sequoia Capital yet.
I swear to God, Mark, before I'm 25 I'm gonna make those guys kiss my ass and then cry like girls, There will be retribution for Plaxo and I'm not just talking.
I brought down the record companies with Napster and I'll bring down Michael Moritz,
E DUARDO You didn't bring down the record companies, They won.
SEAN In court.
Yes.
SEAN Well.
EDUARDO (V.O.) And he told story after story about life in Silicon Valley, parties at Stanford and-down in LA, friends who" d become billionaires--and then he finally got around to theFacebook.
SEAN Tell me about your progress.
EDUARDO Well...
EDUARDO we're in 29 schools now and we
SEAN (ignoring EDUARDO and going for
Tell me about the strategy you're using.
MARK Okay.
MARK For instance, we wanted Baylor in Texas but Baylor already had a social network on campus so instead of going right after them, we made a list of every school within a hundred miles and put theFacebook on those campuses first.
MARK Pretty soon all the Baylor kids were seeing their friends on our site and we were in.
SEAN Perfect.
Thank you, it was mine.
Easy.
EDUARDO Settle an argument for us, would you?
EDUARDO I say it's time to start making money from theFacebook but Mark doesn't want advertising.
EDUARDO Who's right?
SEAN Neither of you.
SEAN TheFacebook is cool, that's what it's got going for it.
MART Yes.
SEAN You don't want to ruin it with ads because ads aren't cool.
MARK Exactly.
SEAN it's like you're throwing the coolest party on campus and someone's telling you it's gotta be over at 11:00.
MARY, Exactly.
SEAN You don't even know what the thing is ya??t.
MARK I said exactly that.
SEAN Row big it can get and how far it can go.
SEAN Picture sharing, news feeds, a virtual champagne room, apps you haven't even thought of.
SEAN This.is no time to take your chips down.
SEAN A million dollars isn't cool.
SEAN You know what's cool?
EDUARDO You?
SEAN A billion dollars.
SEAN And that's where you're headed.
SEAN A billion dollar valuation.
SEAN Unless you take bad advice in which case you might as well have come up with a chain of very successful dry cleaners.
SEAN When you go fishing you can catch a lot of fish or you can catch a big fish.
SEAN You ever walk into a guy's den and see a picture of him standing next to fourteen trout?
SEAN No, he's holding an.
SEAN 800 pound marlin and that's what you want.
SEAN Hey guys, it's your company, I don't have a dog in this fight.
SEAN Irjust came to say hi.
No, he came to hook an 800 pound marlin and he did.
He owned Mark after that dinner.
He picked up the check, told Mark they'd talk again soon and was gone.
But not before he made his biggest contribution to the company.
SEAN Oh Hey.
SEAN Drop the "the".
SEAN Just Facebook, It's cleaner.
SEAN And SEAN heads out, patting backs and kissing waitresses along the way.
Shit.
EDUARDO That's gotta be some kind of land speed record for talking.
MARK You want to end the party at eleven.
EDUARDO I'm trying to pay for the party.
MARK There won't be a party unless it's cool.
What'd you think?
EDUARDO Sure, let's drop the "the".
MARK I meant catching the marlin instead of the 1.4 trout.
MARK Doesn't that sound good?
EDUARDO Only if you're a trout.
GRETCHEN I'M going to enter this as Plaintiff's Exhibit 54.
GRETCHEN Incorporation papers for Facebook, a Limited Liability Corporation registered in Florida--
GRETCHEN Why Florida?
EDUARDO That's where my family lives.
GRETCHEN ---and ask the respondent to stipulate that the documents of incorporation state the ownership as follows: 65 percent for Mark Zuckerberg, 30 percent for Eduardo Saverin and 5 percent for Dustin Mosokowitz .
SY We stipulate.
GRETCHEN And that was April 13th, 2004.
SY You can mark it.
Do you have anything here?
SY Yes, thanks, Mr. Saverin, have you ever done anything that would be considered legitimate grounds for termination?
EDUARDO No,
SY You never did anything to embarrass the company or even seriously jeopardize it?
No.
SY No?
EDUARDO No.
SY You were accused of animal, cruelty-
Is this a Doke?
SY I have an article here from The Crimson---
MART I can't have this, Wardo, MARK's talking about the Crimson article in his hand.
MART EDUARDO is standing next to a crate that's holding--wait for it- a live chicken, DUSTIN is sitting at the desktop computer staring at something intently.
EDUARDO It's bullshit, it's one of the other clubs playing a prank.
MARK They identify you as--
EDUARDO I'd gotten into the Phoenix.
EDUARDO I'd been accepted and as part of my initiation I had to, for one week, carry with me at all -Limes and take care of a chicken.
MARK --one of the founders of Facebook.
MARK "Junior Eduardo Saverin, co-founder of Facebook, wa.s-- --I'm not the expert but being connected to torturing animals is probably bad for business.
EDUARDO I wasn't torturing the chicken, I don't torture chickens, are you crazy?
SY Settle down please.
SY I'm holding an
MARK This is scathing.
DUSTIN Nine--hundred and fifty-six.
EDUARDO Listen to me.
I was having dinner in the Kirkland Dining Hail with Mark and I had the chicken with me because I had to have the chicken with me at all times.
This was college.
MARK I'm gonna have to answer for this.
DUSTIN Nine--hundred sixty-nine.
EDUARDO The dining hall was serving chicken for dinner and I had to feed my chicken so I just...I cut up little pieces,of chicken and gave it to the chicken.'There were a lot of people there and someone must have seen me and the next thing I knew I was being accused of forced cannibalism.
EDUARDO At the end of the table, MARYLIN'tries but fails to stifle a small laugh.
EDUARDO EDUARDO looks down the table...
EDUARDO (CONT'D) i didn't'know you can't do that.
EDUARDO (CONT'D) I dealt with the various animal rights groups, I dealt with the Associate Dean of the College, it was all fine.
DUSTIN Nine-hundred and eighty-eight.
EDUARDO Someone from the Fly or the Porc must have reported it.
EDUARDO For all I know it was the Winklevoss twins who may have been tipped off by somebody else who was there.
MARK Alright, let's just forget about it.
EDUARDO I can't forget about it, I'm being accused of animal cruelty.
EDUARDO It's better to be accused of armed robbery.
EDUARDO I'm going to have to explain this to my father, I'm going to have to explain this to everyone, I'm going to have to--what is happening on that?
EDUARDO EDUARDO's referring to a laptop that's open and displaying images of four paintings.
MARK T.
MARK have my final coming up for "Postwar and Contemporary Art" and I haven't been to class.
MARK I'm supposed to write about those four paintings.
EDUARDO Is that a Facebook page?
MARK Yeah, I opened it under an alias.
MARK I posted the paintings and asked people to comment.
MARK Every once in a while I hop on and stir the pot to get a good debate going, it's beautiful.
GRETCHEN Mr. 2uckerberg was cheating on his final exam?
EDUARDO I'd rather not answer that, Gretchen.
GRETCHEN Why not?
EDUARDO Because I'm not suing him for cheating on his final exam and so that's not what friends do.
GRETCHEN Well you just told us he was cheating.
EDUARDO bops.
You told your lawyers I was torturing animals?!
SY No, he didn't tell us about it at all.
SY our litigators are capable of doing a Google search.
SY in fact when we raised the subject with him he defended-yu.
Oops.
DUSTIN Nine ninety-three, we are so close.
MARK We're gonna need more money, Wardo.
EDUARDO I agree.
EDUARDO More servers, more apps--
MARK ---and I want to hit that coal by the end of the summer.
MARK I'm interviewing people tomorrow--two interns to come to Palo Alto for the summer and we're-gonna have to pay them something.
EDUARDO What?
MARK I already found a house for rent on a street two-blocks.from the Stanford campus.
MARK It's a piece of junk but it's perfect and it's got a pool.
EDUARDO When did you decide to go to California for the summer?
You mean when did I actually decide?
EDUARDO Somewhere in the middle of The Sean Parker Variety Hour?
MARK He was right.
MARK California's the place we've gotta be.
EDUARDO You're Jed Clampett?
MARX You guys got The Beverly Hillbillies in--a??
EDUARDO Yes, we got the show in Brazil, it was genius.
MARK What's your problem with Sean?
EDUARDO He doesn't bring anything to the table.
EDUARDO He doesn't have money, Dustin's a better
MARK He's got connections to the VCs.
EDUARDO We don't need VCs, we need advertisers and I've got connections to the VCs.
MARK The real players and--
MARK --as someone who's just really embarrassed the company in a bad way--
EDUARDO It was the Winklevosses, Mark!
MARK Bang on.
Hit refresh.
DUSTIN hits "refresh" on the desk-top computer.
Then smiles...
MARK 150,000 members, Wardo.
Congratulations, dude.
MARK Congratulations.
He was obsessed with the guy from Sequoia Capital.
He was followed by private detectives.
MARK Who came up with nothing.
EDUARDO Enough to get him out of Plaxo.
EDUARDO The drugs, the girls--
MARK We don't know any of that's true.
EDUARDO You can read about it,
MARK And you can read about you torturing birds.
EDUARDO Don't fish eat other fish?!
EDUARDO The marlins and the trout?!
DUSTIN What the hell?
MARK I'm interviewing interns at 10 tomorrow night in t}y CS lab.
MARK Get on board with this or not.
EDUARDO steps through double doors and stops for a moment as he HEARS an odd sound--RAUCOUS CHEERING from a'CROWD that's gathered in one of the classrooms.
EDUARDO walks down to the classroom, opens the door and walks
--where'60 or so STUDENTS are in a semi-circle, five and six deep, cheering on the contestants for the internship.
All the desks in the room have been moved to the sides and five desks with laptops set up in the middle.
Next to each laptop is a shot glass filled with Jack Daniels.
DUSTIN'S holding a.
watch and MARK is walking slowly back and forth behind the five "interviewees" who are intensely typing at their keyboards.
EDUARDO slowly makes his way through the crowd to MARK.
He can see that on the computer screens are a whole lot of numbers and letters that neither he nor we can understand.
He stands next to MARK and watches this for a moment.
Every once in a while, one of the contestants will throw back their shot of Jack Daniels which will instantly get re-filled by a PRETTY ASIAN GIRL.
Throughout all this the CHEERING CONTINUES.
Mark?
MARY, Yeah.
EDUARDO What's goin' on?
MARK They have 10 minutes to get 'root access to a Python webserver, expose its SSL encryi? 1/2 ti_on and then intercept all traffic over its secure port.
EDUARDO They're hacking.
MARK All behind a Pix Firewall Emulator.
MARK But here's the beauty.
EDUARDO You know I didn't understand what you just said, right?
I do know that.
What's the beauty?
MARK Every 10th line of code written, they have to drink a shot.
MARK And hacking's supposed to be stealth, so anytime the server detects an intrusion, the candidate responsible has to drink a shot.
MARK I also have a program running that has a pop-up window appear simultaneously on all five computers--the last candidate to hit the window has to drink a shot.
MARK Plus every three minutes they all have to drink a shot.
Three minutes.
All five candidates drain their shot glasses and slam them down where they get re-filled by the pretty Asian girl.
EDUARDO Can I ask--what part of the interns' jobs will they need to be able to do drunk?
MARX You're right.
MARX A more relevant test would be seeing if they can keep a chicken alive for a week.
what I just said was mean and I'm sorry.
Are we alright?
We started this as a team.
EDUARDO hands MARK a thick envelope---
EDUARDO Here.
MARK What's this?
I opened a new account and put $18,000 it.
Will that get you through the summer?
MARK looks at EDUARDO...
Suddenly two of the candidates hands shoot up almost at the
Here!
Right here!
MARK glances over at the first screen, then the second...
MARK welcome to Facebook.
MARK The place ERUPTS.
MARK The pretty ASIAN GIRL hits an mp3 player that's been hooked up to speakers and a Dr. Dre song blares out--"California, it's time to party..."
MARK The two winners are hugging each other and getting wild congratulations from the crowd.
MARK looks back at EDUARDO and smiles...EDUARDO gives him a pat on the back and we
EDUARDO Yes.
GRETCHEN In addition to the $1000 you'd already put up.
EDUARDO Yes.
GRETCHEN A total of $19,000 now.
EDUARDO Yes.
MARK Hang on.
MARK MARK's scratching something out on a pad...
I'm just checking your math on that.
Yes, I got the same thing.
GRETCHEN I can continue?
GRETCHEN MARK motions "ves"...
After expressing misgivings about Mr.
Zuckerberg 'taking the company and moving it to California for the summer, why did you turn around and put $18,000 in an account for his use?
EDUARDO Wel1...
EDUARDO .I figured we were a team and I wanted to be a team player.
EDUARDO I figured Mark, Dustin and the new interns could work on the site while I worked on generating advertiser interest in New York.
EDUARDO (CONT'D) And mostly I figured., you know...how much could go wrong in three months?
MARK is standing on the roof of this small, campus-area house as LOUD MUSIC plays.
A zii? 1/2 'line is tied from the chimney and runs down over a small swimming pool where it's attached to a telephone pole on the other side.
MARK grabs onto the handle that's connected to the zip line and flies out over the pool, jumping in with a splash and cheers from DUSTIN and the INTERNS who are waiting their turns on the roof.
DUSTIN pulls the handle back up with_a rope that's been rigged, grabs the handle, takes off and jumps into the pool-to similar cheers.
The handle gets pulled back on a rope, an INTERN grabs it,
--and the brick chimney comes crashing down.
The INTERN drops into patio furniture as bricks from the chimney come cascading down.
ALL Shit!/Are you alright?!/ Jesus!/etc-
I'm okay.
MARK You sure?
ERIC Yeah.
MARK Is anything broken?
ERIC No.
ERIC And at that moment a stray brick drops from the roof and crashes through a glass patio table.
That's gonna out into the security deposit.
From inside the DOORBELL RINGS--
DUSTIN That's the doorbell.
MARK I didn't know we had a doorbell.
Andrew!
Get the door!
He's wired in.
MARK walks into--
The place is computer geek paradise.
Computers are everywhere, along with some of the empty boxes they came in.
Pizza boxes, Chinese food containers, empty beer bottles and white boards filled with indecipherable code fill the room.
There are a couple of large mattresses on the floor and a large map of the U.S.
with pins and tags showing the schools where they've already put Facebook and different pins showing the schools they're going for.
As MARK walks to the door, he walks past ANDREW, who's sitting at a computer, writing code and completely oblivious to everything around him.
MARK Andrew.
Not now.
MARK Good boy.
MARK MARK gets to the door and opens it.
MARK He's stunned to see SEAN PARKER standing there with his girlfriend, SHARON.
MARK They all look at each other for a moment---
SEAN Mark?
MARK Sean?
SEAN Do you live here?
MARK Yeah.
MARK Do you?
SEAN We were right across the street, we saw the chimney come--
MARK Yeah.
SEAN Is anybody hurt?
MARK No.
MARK You live across the street.
SHARON I'm Sharon.
SEAN This is my girlfriend, Sharon.
SEAN She lives across the street and I was helping her move out when we saw the chimney--
MARK Yeah, we had a zip line to the pool.
SEAN You came to California.
MARK Yeah.
SEAN You made the right choice.
SEA,'s looking around the place.
DUSTIN and the INTERNS are standing off to the side, happy to be in the presenbe of Sean Parker.
ANDREW'S still locked into his computer.
MARK's off in the kitchen.
Here you go.
A beer comes flying out of the kitchen and SEAN catches it.
Sharon.
Another beer comes flying out which SHARON had no idea was coming and so it smashes into the fireplace.
SHARON Oh God.
SHARON I'm so sorry.
SHARON And a brick comes down the chimney and crashes on top of the broken glass from the beer bottle.
DUSTIN You know, ironically, we're paying an extra 50 bucks a month 'cause it has a working fireplace.
SEAN This house is great.
SEAN The team is great.
SEAN It's exactly what it should be.
I'm Sean Parker.
MARK comes out of the kitchen--
MARK He's wired in.
SEAN That's what I'm talkin' about.
SEAN Where's Eduardo?
MARK He's got an internship in New York.
Eduardo didn't come out?
An ultra-hip San Prancisco nightclub where a line of well- dressed young people stretches from the clipboard holding BOUNCER down the block.
The BOUNCER motions to three SEXY GIRLS who are let in through the velvet rope.
If this reminds us of the scene at the final club party at the beginning of this story than that's fine.
The three SEXY GIRLS take us into
It's a hundred-year old theater that's been converted into a 21st Century hot spot for Silicon Valley's rock stars.
The lower level is a giant dance floor packed"with sweating 20- somethings bouncing to pounding house music.
There are raised blocks where scantily dressed professional.
dancers perform non- stop.
A huge lighting grid hangs from the ceiling shooting colored lights and lasers everywhere.
Also hanging from the ceiling are two trapeze bars with two performers swinging and contorting.
A WAITRESS holding a tray of colored drinks high over her head takes us through the crowd to a spiral staircase that's being guarded by two more BOUNCERS with clipboards.
The staircase leads up to the 2nd level which is all VIP tables that look out over the dance floor.
Each VIP area has a couple of couches and a table covered in bottles of vodka, tequila, rum, mixers, ice, glasses and a private waitress who's happy to bend over and pour a drink for you, And that's where we catch up with MARK and SEAN.
Sitting next to SEAN is a BEAUTIFUL WOMAN and there's another standing behind him and leaning against the couch.
MARK and SEAN have to speak the music.
MARK I still can't believe I rented a house across the street from you.
SEAN That's not my house.
SEAN It was Sharon's.
SEAN I was crashing there for a little.
SEAN bit while I'm taking care of some things.
SEAN But she's done for the summer so she's back at her parents' place and I'm homeless.
Yeah?
You can crash at our.
place for a few days if you want.
SEAN That's sol..id man, thanks,
I'm going to the ladies' room;
SEAN You got it.
I'll go with you.
The two girls exit--
MARK Your date looks so familiar to me,
SEAN She looks familiar to a lot of people.
MARK What do you mean?
SEAN Look at any Victoria's Secret catalogue from the last six months.
You're kidding.
SEAN No man.
SEAN I'll tell you something, you know how I founded Napster?
MARK I know everything there is to know about you Sean.
SEAN Fuck Wikipedia, Mark, no you don't.
I was going out with this girl in high school.
And it was great.
I thought it was great, but the whole time--almost the .whole time we were together., like five months--she was giving blow.
jobs to the co-captain of the lacrosse team.
And I found out and I was willing to forgive her but she told me she loved him.
So I had this dream that I would make a billion dollar company..
Not a million dollar company--any hack can do that---a billion dollar company.
And I would have business cards printed up that said, "I'm CEO..
.Bitch.
It's our time.
We run the universe.
Yeah, she's a Victoria's Secret model.
I want to know where the fuck Eduardo is.
MARK He has an internship.
SEAN An internship?
MARK In New York.
SEAN The company's here.
SEAN A billion dollar company is here.
SEAN And what confuses me is that in New York, Eduardo introduced himself as the business head of Facebook.
SEAN I've been at the front of two of the biggest things in the history of the internet and I can tell you that nothing, nothing is more important to a start-up than the energy and ambition of its founders.
You have to live and breathe the project every minute of every day and-night.
Do you live and breathe Facebook?
MARK Yes.
SEAN I know you do.
SEAN I know those guys back at the house do.
SEAN The guy's eyes did not blink when a beer bottle smashed into a fireplace 10 feet from his work, station.
SEAN So I'll ask again--where's Eduar
It'd be great if you stayed at the house with us.
SEAN I think I should.
SEAN The girls come back--
You guys figure out a new way to get porn on your computer?
You know most of it's bad but some of it's pretty good.
MARK and SEAN aren't paying attention...
SEAN What's your goal for the summer?
MARK We want: to .
MARK be in a hundred schools.
okay.
Okay good.
I'll tell you what.
Gesture of good faith.
While you're getting yourself into a hundred schools, I'm gonna put you on two continents.
What?
SEAN Let's line up some shots.
SEAN You can take away the Cuervo, we'll have Don Julio 1942.
WAITRESS Absolutely, Mr. Parker.
WAITRESS The WAITRESS goes off--
SEAN Mark?
MARK Yeah.
I never told her my name.
we're looking at a stone bridge crossing a perfectly straight stretch of water against the backdrop of the medieval town of Henley, England--founded in 1179.
And after a moment of placid quiet--
Two razor thin skulls explode out from under the bridge for the final, agonizing hundred-meter stretch of the ancient and prestigious Henley Royal Regatta.
The two boats are neck and neck coming out of the bridge.
The port-side boat is being crewed by the two Dutch members of the Ilollandia Roeiclub.
The starboard boat is being crewed by a pair of identical twins wearing tank tops bearing the "H" of Harvard.
We HEAR the ROAR come up from the CROWD in the viewing section.
The crowd is dressed as if for opening day at Ascot -- the women in flowing dresses and wide-brimmed hats, the men i n blazers and brightly colored floral ties.
But the young men in the boats can barely hear the crowd.
Just their own breathing as they pull against the longest natural.
straight stretch of water in the world--a mile and a half torture test against the best competition they've ever faced.
And they're neck and neck.
CAMERON and TYLER can't shake the Dutch.
The CROWD is going crazy in their own English way as none of them can remember ever seeing two boats this close this late.
Mixed in with the British crowd is a small contingent waving the flag of Holland and a slightly larger contingent of Americans.
We'll notice a stoic man in a VIP viewing section and latex we'll be introduced to him as Cameron and Tyler's father, Next to him is their mother, who can barely watch.
Back on the boats it's just the breathing as the skulls slice through the water like jet-powered knives.
50 meters now and there's still no daylight between them.
We see a small trickle of blood from CAMERON's left hand begin to stream down his arm.
25 meters and the Dutch and American fans are going crazy-- even the British aristocracy can't help but get caught ups the closest race in the history of the competition.
The 'ATH_PT'i? 1/2  is silently willing his boys one more fraction of boat speed-- the MOTHER has her hands over her mouth in praying position.
The blood that's covering CAMERON's left arm is being diluted by the sweat that's pouring down from his triceps as they dig, and pull, and pull, and pull, and---
--the finish gun is fired into the air, the oars come out of the water and the bodies of the crewmen slump over.
CAMERON turns his head to the cheering crowd to see the Dutch group holding a giant flag and.jumping up and down.
The Americans bring their giant flag down and fold it up.
The two DUTCH CREW.
MEMBERS pump their fists in the air and hug as the two boats skim along to a gentle stop.
The MOTHER drops her head-and looks down.
The FATHER refuses to look away.
From CAMERON and TYLER, just the'breathing.,
CAMERON and TYLER are standing with their coaches and next to the two DUTCH CREWMEN who are with their coaches.
They're on a stand in the Steward's Enclosure, a sprawling and glamorous tented area for the exclusive use of members and their guests.
After a moment, a man in a double breasted navy blazer steps out with his retinue in tow.
The man is PRINCE ALBERT of Monaco.
He receives a healthy clapping of golf applause as he approaches the stand.
This conversation is done without microphones or anything as modern as that.
His Royal Highness, Prince Albert.
Sir, may I present Mr. Cameron Winklevoss and Mr. Tyler.
Winklevoss of Harvard University.
PRINCE ALBERT Brilliant race.
PRINCE ALBERT Never seen a race that close.
PRINCE ALBERT Less than one second, the steward tells me.
Yes, Your Highness.
PRINCE ALBERT My grandfather, Jack Kelly, was one of the premiere rowers of his day.
PRINCE ALBERT I've been coming to Henley for 30 years.
PRINCE ALBERT Never seen a race that close.
PRINCE ALBERT Have you?
PRINCE ALBERT Have you seen a race that close?
PRINCE ALBERT CAMERON is thinking about starting a war with Monaco right now so he lets his brother do the talking.
No, Your Highness.
Mile and a half races are more commonly won by a boat length or two.
PRINCE ALBERT Yes, that's absolutely right.
PRINCE ALBERT Less than a second though in your case.
PRINCE ALBERT Well as they say, I suppose it just came down to who wanted it more.
Oh what a bullshit cliche: You think we
Cam.
There's an awkward silence for a moment...
PRINCE ALBERT Will I have the pleasure of watching you both row again in Beijing?
TYLER If we make the team, sir, yes.
TYLER Thank you.
PRINCE ALBERT I present you with your Second Place ribbons.
PRINCE ALBERT On to the champions!
And off the APPLAUSE from the crowd, we
The regatta party is underway.
Music, drinks, uniformed waiters, blazers and hats everywhere.
TYLER and CAMERON have changed into their Harvard.
blazers and are joined now by DIVYA.
The three of them have tried to find an unpopulated spot.
TYLER and DIVYA have glasses of beer and are standing but CAMERON's sitting at a table with a laptop open and watching film of the end of the race.
Hitting reverse on the computer and watching, over and over again, the bow of the Dutch boat pull ahead by six inches at just the right moment.
CAMERON Yeah.
CAMERON We didn't want it enough.
CAMERON That was the problem.
CAMERON Fuck you, you fucking little--
DIVYA Casa.
DIVYA The guy' s the prince of a country the size of East Hampton.
DIVYA Let it go.
DIVYA MR.
DIVYA WINKLEVOSS has made his way over...
MR. WINKLEVOSS Boys.
TYLER Dad.
MR. WINKLEVOSS Divya.
DIVYA How are-you, Mr. Winklevoss.
MR. WINKLEVOSS That was a tough beat.
MR. WINKLEVOSS A tough beat.
CAMERON I'm sorry, dad.
CAMERON You and mom flew all the way over.
MR. WINKLEVOSS Listen to me good, you two.
MR. WINKLEVOSS Don't you ever apologize to me for losing a race like that.
MR. WINKLEVOSS Don't you ever apologize to anyone for losing a race like that.
MR. WINKLEVOSS Another man comes along, MR.
MR. WINKLEVOSS KENWRIGHT.
KENWRIGHT -Boys.
TYLER Oh.
TYLER Mr. Kenwright.
TYLER Dad, this is Mr.
TYLER Kenwright, part of our host family this week.
KENWRIGHT Pleasure to meet you.
MR. WINKLEVOSS Good to meet you.
KENWRIGHT I just had the most extraordinary phone chat with my daughter.
KENWRIGHT She told me that she and her friends are all talking about the race, which ended just, a half-hour ago, via their computers.
KENWRIGHT A new website called Facebook.
KENWRIGHT Do you have this in America?
KENWRIGHT Eve.ryon= is frozen...
Your daughter doesn't go to school in the
KENWRIGHT No no.
KENWRIGHT Cambridge.
KENWRIGHT Majoring in French Literature, though I wasn't aware there was such a thing.
They have Facebook at Cambridge?
And Oxford, St.
Andrews, Warwick and the London School of Economics best as I can tell.
because that's where her friends are.
MR. WINKLEVOSS I'm going to find your mother.
Good race, boys.
Live to fight another day.
TYLER Thank you.
TYLER The men leave and CAMERON, TYLER and DIVYA are alone.
TYLER CAMERON looks at them for a moment, then turns back to watching the
TYLER (CONT'D) Turn it off.
Turn it off, Cam.
Look at me.
CAMERON turns to his brother...
TYLER (CONT'D) I don't mind that we got beat by the Dutch by less than a second.
TYLER (CONT'D) That was a fair race, that was a good race and they had the better boat today and they'll see us again.
TYLER (CONT'D) What I mind is that we got beat by Mark Zuckerberg...by less than a second.
We tried the Ad Board, we tried the president of the University and we tried talking to him ourselves.
Now I'm asking you.
For the one-hundreth time.
Let's take the considerable-resources at our disposal and sue him in a federal.
court.
CAMERON looks at his brother...then turns back to the computer.
He watches the Dutch boat pull ahead at the last moment.
TYLER and DIVYA are just about to give up when CAMERON swings back and says--
CAMERON Let's fucking gut that little nerd.
DIVYA Finally!
INT. PALO ALTO HOUSE - NIGHT There's a thunderstorm going on outside and rain is beating hard against the windows, DUSTIN, ANDREW-and the INTERNS are hard at work writing code.
INT. PALO ALTO HOUSE - NIGHT Green Day is pumping from the speakers.
INT. PALO ALTO HOUSE - NIGHT SEAN is pacing the house on his cell phone while two YOUNG WOMEN--dressed to go out for a party--are at the moment each on a free computer playing each other in a game of Counter- Strike.
INT. PALO ALTO HOUSE - NIGHT Basically they're shooting at each other and missing and laughing their heads off, it wouldn't appear as if the house has been cleaned since the last time we saw it and in fact there are signs of more wreckage as well as futons, pillows and blankets on the floor.
But check it out, I saw him today.
SEAN (CONT'D) Moritz, Michael Moritz, my Sequoia Capital---hang on.
SEAN (CONT'D) Are you guys using Wallhacks or Aimbots?
GIRL #1 we don't know, we're just shooting at each other.
GIRL #1 The DOORBELL RINGS but no one pays attention--
SEAN Use Barr cks.
GIRL #1 Like we know what that is.
GIRL #1 Now there's a KNOCKING at the door and we
Ra:i.n is soaking down on EDUARDO as he stands at the front door with a suitcase in his hand.
A taxi is turning around in the driveway and heading off.
EDUARDO knocks on the front door again as we
I saw him getting into his car and he saw me too, I know he did.
A Porsche Carrera 911 Turbo.
Hang on.
SEAN leans over one of the girls, casually hits a few keys and easily kills several of the other girl's soldiers.
GIRL #1 Yes!
GIRL #2 Hey!
GIRL #1 Bong hit.
DUSTIN Anybody hear that banging?
DUSTIN While the following is going on, here's what's happening: The girls have gone over to a 12-foot bong that starts at the floor and goes to the landing at the top of the stairs.
it gets lit at the bottom and smoked at the top so the girl who just got her soldiers hit trots up the stairs.
You don't hear anything, you're supposed to be writing code.
DUSTIN Dude, somebody's at the door.
DUSTIN SEAN goes back to the cell phone conversation as he heads to
The guy hires a P.T, to follow me around.
Who does that in real life?
Michael Moritz and I are gonna meet in a dark alley, I'll take Sequoia Capital down with him.
SEAN opens the door and the soaking wet EDUARDO is standing there...
EDUARDO What the hell.
I'll call you back
What's up?
What's up?
Mark was supposed to get me at the airport two hours ago, I've been calling his cell.
SEAN He was on a 36 hour coding tear so he took a nap for a couple of hours.
SEAN EDUARDO walks into the house and surveys the wreckage--
EDUARDO What in hell happened here?
SEAN Not happened--happening.
SEAN The next big thing.
DUSTIN Wardo!
EDUARDO Hey man.
Back to work.
The girl at the bottom of the stairs has filled the bowl and lights a lighter--
You ready?
GIRL #2 Go.
GIRL #2 EDUARDO watches as the girl at the top of the stairs takes a 12-foot hit from the tower-bong.
EDUARDO Flow old are they, Sean?
SEAN It's not polite to ask,
EDUARDO How old are they?
SEAN You think you know me, don't you.
EDUARDO I've read enough.
SEAN You know how much I've read about you?
SEAN Nothing.
SEAN MARK comes down the stairs--
MARK Wardo.
EDUARDO I waited an hour for you at the airport.
MARK What time is it?
EDUARDO It's midnight.
EDUARDO Or 3AM in New York where I just came from.
MARK You've gotta see some of the new stuff we've got.
MARK Dustin, show him the wall.
MARK I'm just calling it the wall.
SEAN Forget the wall, tell him about the meeting I've got set up with Peter Thiel.
You know Peter Thiel?
EDUARDO No.
SEAN Why would you?
SEAN He just runs a two-billion dollar hedge fund called Clarium Capital and was the money behind PayPal.
Why's he setting up meetings?
MARK Thiel may want to make an angel, investment.
EDUARDO I don't care if he's an actual angel, why's he setting up business meetings?
MARK You've had a long flight.
EDUARDO No, I've had a long wait on the tarmac at JFK, theft a long wait at the passenger loading and unloading zone at SFO and in between there was a long flight.
EDUARDO I run the business end of this company, he's a house guest living rent-free on a generous grant from the Eduardo Saverin Foundation.'
SEAN How's the business end going?
SEAN I see you got some big ticket ad buys lined up.
SEAN The Harvard Eartendi.ng Course, the Seneca Club's Red Party and the Mather House annual "Lather Dance".
SEAN You're just one small step away from bagging Snookies Cookies, I can feel it.
Can I talk to you alone for a minute?
MARK Sure.
Bong hit!
I'm pretty baked.
SEAN Don't worry about it, it's just from the pot.
SEAN EDUARDO's followed MARK into--
MARK How's it going?
MARK How's the internship?
MARK How's Jenny?
EDUARDO How's the internship?
MARK Yeah.
EDUARDO Mark..
EDUARDO .Jesus, I quit the internship.
EDUARDO We've talked about this on the phone, were you even--I quit on my first day.
MARK I do remember you saying that.
EDUARDO Yeah, it was a pretty big deal.
MARK How's Jenny?
Jenny's psycho.
MARK That can be fun.
EDUARDO No I mean she's actually psychotic.
EDUARDO She's insanely jealous and she's irrational and she's violent.
MARK Still, it's nice you have a girlfriend.
EDUARDO I do not want that guy representing himself as part of this company.
MARK You gotta move out here, Wardo, this is where it's all happening.
EDUARDO Did you hear what I just said?
MARK The con etions, the energy-
MARK --the creativity.
EDUARDO He's not part of the company.
MARK We've got over 300,000 members, we're in
EDUARDO I'm aware of that.
MARK --five in Europe.
EDUARDO I'm aware of that, Mark, I'm the CFO.
MARK We need more servers than I ever imagined we'd need.
MARK We need more programmers.
MARK We need more'money.
MARK He set uV the Thiel meeting.
MARK He's set up meetings all around town.
EDUARDO He's set up other meetings?
MARK Yes.
EDUARDO Without me knowing anything about it?!
MARK You're in New York!
EDUARDO Riding subways 14 hours a day to get
MARK How's it going so far?!!
MARK EDUARDO looks at MARK for a long moment before we
EDUARDO comes through the doors with single-minded intent, heads past the tellers and straight to a desk where he takes a bankbook out of his pocket and slaps it on the desk.
Can I help you?
EDUARDO I want to freeze this bank account and cancel all existing checks and lines of credit.
80 stories of polished granite.
We're in the offices of a guy who's hero is Gordon Gekko.
MARK and SEAN are waiting--seated side by side--for a verdict.
SEAN's wearing his best Prada, MARK's wearing his hoodie and Adidas flip-flops.
After a moment...
SEAN You know this is where they filmed Towering Inferno.
That's comforting.
The office door opens and PETER THIEL sticks his head out--
Come back in.
They get up and walk into--
Several of Thiel's lieutenant's are sitting around.
THIEL We've talked it over and congratulations.
THIEL We're gonna start you off with a $500,000 investment.
THIEL Maurice is gonna want to talk to you about some corporate restructuring.
We'll file as a Corporations eiaware and come up with a new stock strn ructure to allow for new investors,
THIEL Now lemme ask you something.
THIEL Who's Eduardo Saverin?
A summer sub-let.
A studio apartment the size of a small too].
shed.
EDUARDO is asleep on top of the covers in the un-air conditioned apartment when he wakes up to the sound of a key in the door; One lock un-locks, then another--
EDUARDO Hello?
EDUARDO --and then the last.
EDUARDO The door opens and JENNY is framed by the dingy light of the hallway.
EDUARDO (CONT'D) Jesus .
JENNY When did you get back?
EDUARDO You scared me.
EDUARDO I need you to knock first.
JENNY When did you get back?
EDUARDO I got back this afternoon.
JENNY And when were you going to call me?
EDUARDO Jen, it was kind of a rough trip and I was tired and--
JENNY Or answer one of my 47 texts?
JENNY Did you know I sent 47 texts?
EDUARDO I did, and I thought that was incredibly normal behavior.
JENNY Are you mocking me?
EDUARDO I brought you a present.
JENNY Why does your status say "single" on your Facebook page?
What?
JENNY Why does your relationship status say "single" on your k'acebook page?
EDUARDO I was single when I set up the page.
JENNY And you just never bothered to change it?
JENNY What?!
EDUARDO I don't know how.
JENNY Do I look stupid to you?
EDUARDO No.
EDUARDO Calm down.
JENNY You're asking me to believe that the CFO of Facebook doesn't know how to-change his relationship status on Facebook?
EDUARDO It's a little embarrassing so you should take it as a sign of trust that I would tell you that.
JENNY Puck you, Wardo.
Easy.
JENNY You didn't change it so you could fuck Silicon valley skanks every time you go out to see Mark.
EDUARDO That is not even remotely true and I can promise you that the Silicon valley skanks don't care what anyone's relationship status is on Facebook.
EDUARDO Please let me give you your present.
EDUARDO EDUARDO's cell phone RINGS--
Oh, your phone does work.
EDUARDO reaches for his cell but JENNY grabs it first to check the ID.
It's Mark.
JENNY tosses the still ringing phone back to him--
EDUARDO Okay, this is gonna be tricky.
EDUARDO Here, open your present.
EDUARDO It's a silk scarf.
JENNY Have you ever seen me wear a scarf?
EDUARDO This'll be your first.
EDUARDO EDUARDO's gotten the gift box out of his half un-packed suitcase, tossed it to JENNY and finally answered the phone.
Yeah.
MARK You froze our account?
MARK in the background there's a small celebration going on with SEAN, DUSTIN, the INTERNS and of course some GIRLS.
MARK Champagne is being sprayed from shaken bottles and the girls.
MARK are dancing to triumphant music.
EDUARDO I did.
MARY You froze the account.
EDUARDO I had to get your attention, mark.
MARK Do you realize that you jeopardized the entire company?
MARK Do you realize that your actions could have easily destroyed everything I've been working on?
EDUARDO We've been working on.
MARK Without money, the company can't function.
MARK What EDUARDO can't see behind his back is that JENNY has taken the gift box and lit it on fire with a cigarette lighter.
MARK (CONT'D) If the servers are down for even a day, our reputation is damaged irreversibly,.
MARK (CONT'D) Users are fickle.
MARK (CONT'D) Friendster has proven that fact.
MARK (CONT'D) And JENNY's now dropped the flaming cardboard box into the wastebasket where the fire grows larger.
MARK (CONT'D) She casually kicks the basket over with her foot.
MARK Even a small exodus, even a few people leaving would reverberate through the whole user base.
MARK The users are interconnected, that's the whole fucking point!
MARK College kids are online because their friends are online and if one
EDUARDO Holy shit!
MARK --goes, all the dominos go!
MARK Do you get that?!
MARK I'm not going back to Caribbean Night at the Jewish fraternity!
EDUARDO I've got a fire in a my apartment!
MARK Did you like being nothing?!
MARK Did you like being nobody?!
MARK Did you like being a pasty- faced geek?!
MARK You wanna go back to that?!
.EDUARDO I'm putting you on speaker.
.EDUARDO EDUARDO hits a button on his cell and tosses it down.
.EDUARDO We'll.
.EDUARDO keep hearing MARK'sa??voice as EDUARDO runs out into the hallway, grabs a fire extinguisher from its wall bracket, comes back in and sprays out the fire.
MARK That was the act'of a child, not a businessman.
MARK And it certainly wasn't the act of a friend, You know how embarrassed I was when I tried to cash a check?
MARK And I was with a girl, Wardo.
MARK It happened in front of a girl.
MARK I'm not going back to that life,
Yeah!
MARK Okay, maybe you were angry, maybe you were frustrated.
MARK I'm ready to let, uh, to let bygones be bygones because I've got some good news.
MARK EDUARDO--with the fire now out--picks up the phone.
EDUARDO I'm sorry.
EDUARDO It .maybe was angry and it was childish.
EDUARDO I needed to get your attention.
MARK I said I've got some good news.
EDUARDO What is it?
MARK Peter Thiel's just made an angel investment of a half a million dollars..
What?
MARK A half a million dollars and he's setting us up in an office.
MARK They want to re- incorporate the company, they want to meet you and they need your signature on some documents so get your ass on the next flight back to San Francisco.
MARK I need my CFO,
I'm on my way.
MARK EDUARDO clicks the phone shut.
JENNY You're going back there?
EDUARDO Yes.
EDUARDO Also I'm breaking up with you.
A glass conference room in the corner of a glass bullpen on a high floor of a high rise.
Cartons are being unpacked, computers are everywhere along with bags of potato chips and boxes of cereal.
In the conference room, EDUARDO is sitting with three LAWYERS at a round, glass table and documents have been put out in front of him.
We can see through the glass that MARY, is working at a computer nearby.
SEAN is also hovering in the background.
LAWYER Four documents, These two are common stock purchase agreements allowing you to buy stock in the newly re-incorporated Facebook instead of the old stock which is now worthless, The third is the exchange agreement, that's for exchanging your old shares for new shares and this is the voter holding agreement.
EDUARDO How many shares of stock will I own?
EDUARDO Jesus Christ.
LAWYER That's a 34.4% ownership share.
LAWYER Why the rise from the original 30%?
EDUARDO Because you may need to dilute it to award shares to new investors.
LAWYER I like dealing with business majors.
You should know that Mark's already taken his percentage from 60 down to 51.
EDUARDO Mark doesn't care about money and he needs to be protected.
LAWYER Dustin Moskowitz owns 6.81%, Sean Parker 6-.47h__
EDUARDO I can live with that.
LAWYER And Peter Theil 7%.
LAWYER Would you like to use my pen?
It's dusk now and the sky outside the room is turning purple.
EDUARDO seems lost in thought.
Eduardo?
EDUARDO looks up.
I'm sorry.
Could you please repeat the question?
Counsel: "And when you signed these documents, were you aware that you were signing your own death certificate?"
No.
It was insanely stupid of me not to have my own lawyer look over all the-the, uh..
.I thought they were my lawyers.
I was a Harvard business major.
I was your only friend.
You had one friend.
My father won't look at me.
Okay.
Eduardo?
Did Mr. Zuckerberg saying anything to you after you signed the papers?
EDUARDO Well there was a lot of handshaking and congratulations.
EDUARDO He'd already told me he wouldn't be coming back to school for at least a semester so we were saying goodbye for a while.
EDUARDO And then before I left, he said----
INT.
rACE000K OFFICE -a?? DAY
MARE But you gotta come back.
MARE Somewhere around the end of November/early December.
MARK (CONT'D) Peter's gonna throw us an amazing party when we hit a million members, it's gonna be out of control.
MARK (CONT'D) You've gotta come back for it.
EDUARDO A million members.
MARK Yeah.
EDUARDO Remember the algorithm on the window at Kirkland?
MARK Yeah.
EDUARDO Yeah, I'll be here.
A brand new black Escalade pulls up in front of a gleaming glass and chrome office building..
SEAN is at the wheel and MARK, in the passenger seat, is wearing brightly colored pajamas with his hair a mess.
They get out of the car and huddle-on the sidewalk.
MARK You sure about-this?
SEAN Oh yes.
SEAN You're 20 minutes late.
SEAN You're going to walk in there and say you overslept.
SEAN and you didn't have time to get dressed, They're gonna pitch you, Sequoia Capital is gonna pitch you.
SEAN They're gonna .tell you why you should take their money.
SEAN They're gonna beg you to take their money, You're gonna nod, you're gonna nod, you're.
SEAN gonna nod and then you're -gonna say, "Which one of you is Michael Moritz?".
SEAN Moritz is gonna say, "That's me".
SEAN And you're gonna say, "Sean Parker says 'Fuck you.' And walk right on out.
Okay.
MARK heads into the office building.
SEAN looks up to the windows of a high floor, points, and says--
SEAN Fuck.
SEAN You.
EDUARDO In late November I got the e-mail from Mark telling me to come out for the millionth member party.
GRETCHEN What else did the e-mail say?
EDUARDO It said that we had to have a business meeting.
EDUARDO That Mark and Sean had played some kind of revenge stunt on Michael Moritz and Sequoia capital.
EDUARDO and that it had impressed Moritz so much that he was making an investment offer that was hard to turn down.
EDUARDO (V.O.) I went out to California and went straight to the new offices.
EDUARDO (V.O.) And it's clear that we're in the offices of a new, high-tech, very successful internet company.
EDUARDO (V.O.) The Facebook logo in blue metallic letters on the wall, the maple desks, new computer monitors, carpeting, a wall covered in graffiti by an artist commissioned for.
EDUARDO (V.O.) the job and -tons of young employees.
EDUARDO (V.0.) (CONT'D) I didn't know whether to dress for the party or the business meeting so I kind of dressed for both.
EDUARDO (V.0.) (CONT'D) We see that most of the employees, especially the women, are dressed to go to an after-work, late-night party.
EDUARDO (V.0.) (CONT'D) But it didn't matter.
GRETCHEN (V.O.) Why not?
EDUARDO (V.0.) Because I wasn't called out there for either one.
GRETCHEN (V.O.) What were you called out there for?
EDUARDO (V.0.) An ambush.
Eduardo'.
LAWYER Eduardo.
LAWYER EDUARDO turns to see the LAWYER he dealt with earlier standing by the door to a glass conference room.
In here.
EDUARDO walks across the bullpen; where no one makes eye contact, and into--
EDUARDO (V.0.) At first I thought he was joking, giving me more contracts to sign.
EDUARDO (V.0.) But then I started reading.
EDUARDO (V.0.) As EDUARDO reads, we rack focus to MARK, who's sitting at a computer'with his back to EDUARDO, focused on his work.
EDUARDO (V.0.) And then we see-SEAN step into the frame and lean against a desk a few yards away.
EDUARDO (V.0.) And then back to EDUARDO, who's almost shaking...
EDUARDO (CONT'D) What is this?
EDUARDO What is this?
LAWYER If you'll let me-- EDUARDO goes back out into--
EDUARDO Mark?
EDUARDO MARK doesn't look up from his computer--
EDUARDO (CONT'D) Mark.
EDUARDO (CONT'D) MARK still doesn't look up--
SEAN He's wired in.
I'm sorry?
SEAN He's wired in.
EDUARDO Is he?
SEAN Yes.
SEAN EDUARDO picks up MARK's laptop over his head and smashes it down on the desk, breaking it into pieces.
How 'bout now, are you still wired in?
SEAN (to the girl at the desk he's
Call security.
Everyone in the office is frozen, silent and watching.
You issued over 24-million new shares of stock.
MARK You were told that if new investors came
EDUARDO How much were your shares diluted?
EDUARDO How much were his?!
GRETCHEN What was Mr. Zuckerberg's ownership share diluted down to?
EDUARDO It wa i? 1/2 
GRETCHEN What was Mr. Moskowitz's ownership share diluted down to?
EDUARDO It wasn't.
GRETCHEN What was Sean Parker's ownership share diluted down to?
EDUARDO It wasn't.
GRETCHEN What was Peter Thief's ownership share diluted down.
GRETCHEN to?
EDUARDO It wasn't.
What was your ownership share diluted down to?
Point-zero-three percent.
MARK You signed the papers.
EDUARDO You set me up.
MARK You're gonna blame me because you were the business head of the company and you made a bad business deal with your own company?!
EDUARDO It's gonna be like I'm not part of Facebook.
SEAN It's not.
SEAN gonna be like you're not part of Facebook, you're not part of Facebook.
EDUARDO My name's on the masthead.
SEAN Check again.
SEAN EDUARDO is momentarily frozen...
EDUARDO This is because I froze the account?
SEAN You think we were gonna let you parade around in your ridiculous suits pretending you were running this company?
EDUARDO Sorry, but my Prada's at the cleaners along with my hoodie and my fuck-you flip- flops you pretentious douchebag.
SEAN Oooh, security is here.
SEAN You'll be leaving now.
SEAN Two SECURITY GUARDS have come in--
EDUARDO :I'm not signing those papers.
SEAN We'll get your signature.
EDUARDO Tell me this isn't about me getting into the Phoenix.
MARK That's right.
MARK It is.
MARK Maybe if you'd spent a little less time with your new friends and a little more time with the company
EDUARDO You did it.
EDUARDO I always knew you did it.
EDUARDO You planted the story about the chicken.
What the fuck is he talking about?
I didn't.
EDUARDO You had me accused of animal cruelty.
SEAN Seriously, what the fuck is up with the chicken?
EDUARDO And I'll bet you just hated that they identified me as a co-founder of Facebook- -which I am!
EDUARDO You better lawyer-up, asshole, 'cause I'm not comin' for my 30 percent, I'm comin' after everythin g
Get him outa here.
EDUARDO I'm going.
SEAN Hang on.
SEAN SEAN hands EDUARDO aa??folded check.
SEAN (CONT'D) There's your $19,000.
SEAN (CONT'D) 1 wouldn't cash it, though, I drew it on the account you froze.
SEAN (CONT'D) EDUARDO looks.
SEAN (CONT'D) at SEAN.
SEAN (CONT'D) .then suddenly and quickly cocks his fist back to punch him in the face.
SEAN (CONT'D) SEAN flinches as EDUARDO holds his punch and lets out a small laugh.
EDUARDO I like standing next to you, Sean.
EDUARDO It makes me look tough in comparison.
EDUARDO EDUARDO exits with the security escort.
EDUARDO There's a long silence in the room...
SEAN That's it.
SEAN That's our show for tonight.
SEAN I want to see everybody here get geared up for a party.
SEAN We're gonna walk down to the club like it's the Macy's Thanksgiving Parade.
SEAN Mackey, put it up on the screen, we've gotta be almost there.
SEAN A young employee hits a remote and a few keys on his computer and a huge flat-screen displays a Facebook page with a read- out of the number of members.
There's scattered applause and excitement as everyone watches.
SEAN takes MARK aside.
SEAN (CONT'D) You alright?
MARK Yeah.
You were kinda rough on him.
SEAN That's life in the NFL.
MARK No.
MARK You didn't have to be that rough on him.
SEAN Listen, I'm putting together a party-.-
MARK Sean?
MARK You didn't have to be that rough on him.
SEAN I get it.
SEAN I'll send flowers.
SEAN I'm putting -together a party after the party at Gamma Phi Beta.
SEAN Ashleigh over there's a sister and she says her friends are all down..
MARK Ashleigh?
SEAN Yeah.
MARK That's great.
MARK I've been, you know, I've been talking to her a little.
MARK I don't know, I think she likes me.
SEAN Oh dude.
MARK What?
SEAN Yeah.
SEAN An intern, ASHLEIGH, comes along With a small package--
ASHLEIGH Excuse me, Mark?
We were just talkin' about you,Ash.
We're on for tonight?
ASHLEIGH Yeah.
This came in for you.
MARK You can put it on my desk.
MARK ASHLEIGH puts the small package on Mark's desk.
SEAN She's 19, I can't he.lp it, But I'll tell you what--after tonight.she's yours.
SEAN in fact, I'm.
SEAN gonna get' you in with all sorts of girls you wouldn't have met before.
Mackey!
Yes sir!
SEAN Refresh!
MARK You'd do that for me?
MARK MACKEY hits the "refresh" key and the big screen shows--
CHEERS erupts throughout the place.
SEAN grabs MARK and hugs him but MARK doesn't quite hug back--he's still hearing what SEAN just said.
We can hear the thumping music coming 'from the party inside and college kids have spilled out onto the front lawn of this pristine, four-columned house.
It's dark but we can make out people dancing.
The place is packed.
INT. BEDROOM - NIGHT We hear the thumping music from the party.
INT. BEDROOM - NIGHT SEAN's in there with a couple of guys, ASHLEIGH and another GIRL.
INT. BEDROOM - NIGHT SEAN's got his cell phone out and will snap a picture every once in a while.
GIRL I can't find a mirror.
GUY Do it on anything.
GUY You can use a CD.
ASHLEIGH Do it off this.
ASHLEIGH ASHLEIGH's sat on the bed and unbuttoned her top so that she's in just a bra.
ASHLEIGH She's offering her chest as a surface off of which to snort cocaine.
GIRL Alright!
GIRL The GIRL taps out some coke from a vial onto ASHLEIGH's chest and starts passing around a rolled up 20-dollar bill for everyone to have a turn and she herself will unbutton her shirt too for the same purpose.
GIRL All this while SEAN is talking,
SEAN The next transformative development?
SEAN A picture sharing application.
SEAN A place where you view pictures that coincide with your social life.
SEAN It is the true...
SEAN digitalization of real life.
SEAN You don't just go to a party anymore, you go to a party with your digital camera and your friends relive the party on Facebook.
SEAN And tagging.
SEAN The idea that you could tag anyone you wanted in those pictures so that people could find themselves.
SEAN Then a digital log of every change in a person's life, broadcast to all their friends instantaneously.
ASHLEIGH Would this be easier without the bra?
GUY It's worth finding out.
GUY The girls start happily slipping off their bras--
I've spent hours--
ASHLEIGH Why has the music stopped?
SEAN I've spent hours watching what people do when they log on.
ASHLEIGH Seriously, why has the music stopped?
ASHLEIGH ASHLEIGH has a point.
ASHLEIGH The music stopped in the addle of SEAN's speech and the sound outside from the party just doesn't sound like a party anymore.
SEAN flow they always checked their friends' status updates, checked to see which of their friends had changed their profiles, changed their photos and mostly...We lived on farms, then we lived in cities and now we're gonna live on the internet.
Sean.
Stop.
Something's going on downstairs, SEAN stops talking-he senses it too now.
SEAN walks out of the room to the--
And out the window he sees a fleet of police cars with their lights flashing parked in front of the house.
Then before he can react, the front door flies open-- POLICE with flashlights walk in--the beams of light streaking across the darkened party floor and the faces..
We HEAR muffled murmurs from the cops of "party's over" and "step to the side" and "nobody's leaving just yet", etc.
SEAN bolts back into--
--leaving the door open.
SEAN It's the cops.
SEAN And they all spring into action.
SEAN The girls are putting their bras back on, SEAN is wiping down a night table with the palm of his hand to get the coke dust off.
POLICEMAN What's goin' on?
POLICEMAN They turn to see TWO POLICEMEN standing in the doorway, their flashlights scanning the room and hitting SEAN's eyes.
We're sorry, was the music too loud?
We've got kind of a celebration going.
POLICEMAN Ladies, I need you to put your shirts on.
SEAN I can have them turn the music down.
SEAN One of the policemen casually takes SEAN's hand and sees that his palm looks like he just used it to erase a blackboard.
SEAN The cop uses his finger to taste what it is.
SEAN (CONT'D) Yeah, that isn't mine.
POLICEMAN Okay, could you all stay where you are.
POLICEMAN And the handcuffs start to come out and we've got a room of terrified children.
Wait, can we just talk for a second?
We start to move in on SEAM...
You got anything in your pockets I need to know about?
SEAN No sir.
Don't be stupid now,
SEAN I don It.
POLICEMAN What's this?
SEAN It's an Epipen,
POLICEMAN And this?
SEAN That's my inhaler.
Ladies, how old are you?
GIRL I'm 20.
ASHLEIGH I'm 19,
POLICEMAN Lying makes a?? i_'E worse.
ASHLEIGH I'm 17, I-'m sorry, I shouldn't have lied.
ASHLEIGH SEAN closes.
ASHLEIGH his eyes at hearing this news as we HEAR the sound of the-cuffs lock around his wrists and we
INT. NEW FACEBOOK OFFICES - NIGHT A digital LED clock on the wall tells us it's 4:40AM.
INT. NEW FACEBOOK OFFICES - NIGHT MARK is sitting at his computer alone.
INT. NEW FACEBOOK OFFICES - NIGHT No one else is in the office.
INT. NEW FACEBOOK OFFICES - NIGHT The San Francisco skyline is beautiful outside the floor-to-ceiling glass.
INT. NEW FACEBOOK OFFICES - NIGHT His cell phone RINGS and he answers.
Hello?
SEAN, freezing with no coat on, is sitting on the bottom of the steps to the police station.'The LAWYER we've seen before is standing in back of him.
Listen, something's happened.
We see MARK listening on his end but can't hear SEAN's end of the conversation.
Shit.
SEAN It's alright, it's gonna be alright.
SEAN I've posted bond-and I wasn't doing anything.
SEAN I mean, I've got allergies so I can't---- We're back on MARK's side.
SEAN He listens...
SEAN listens...
Back on SEAN's side-
SEAN I think it was Moritz.
SEAN I swear, I think it was Michael Moritz.
This is gonna be news, Sean, it's gonna.
be online any second.
I know.
You know with anunderage intern and--
SEAN It's cool, I've got it under control.
I'll get it under control.
I'll call our guys and see what the next move is.
But this is gonna be news now.
SEAN You think it was Moritz?
SEAN 'Cause I do.
SEAN And I'm gonna meet that guy in a dark alley one night.
SEAN Or Eduardo?
SEAN Did Eduardo have me followed?
MARK Go home, Sean.
MARK I'll call our people.
MARK MARK clicks the phone shut.
MARK He sits there a moment.
MARK He looks at the small package.
MARK that Ashleigh dropped on his desk earlier.
MARK He opens up the brown paper wrapping and there's a box.
MARK He opens the box--a thousand brand new business cards.
MARK He takes one of the business cards out and looks at it.
MARK I'm CEO ...Bitoh And over this we HEAR a woman's voice...
Mark?
INT. FIRST DEPOSITION ROOM - NIGHT MARK is sitting alone.-in the conference room.
INT. FIRST DEPOSITION ROOM - NIGHT The only one left is MARYL?N,whose voi? 1/2 .ce we just.
INT. FIRST DEPOSITION ROOM - NIGHT heard.
INT. FIRST DEPOSITION ROOM - NIGHT The lightp of the San Francisco skyline fill the huge picture windows.
MARYLIN Mark?
MARYLIN MARK looks up at her...
MARYLIN (CONT'D) Everyone's gone, MARK doesn't say anything...
MARYLIN (CONT'D) We're done for the day,
Who would you rather he?
MARYLIN I'm sorry?
MARK My lawyer or their lawyer?
Something tells me over the long run there's more money in being your lawyer.
What happened to Sean?
He cashed out most of his stock.
Hey listen, all you had all day was that salad.
You want to get something to eat?
MARYLIN I can't.
MARK I'm not a bad guy.
MARYLIN I know that.
MARYLIN I like you.
MARK What happens now?
MARYLIN Sy and the rest of them are at the Palm having a steak.
MARYLIN Then they'll come back, up to the office and start working on a settlement agreement to present to you.
MARK They're gonna want to settle?
MARYLIN Oh yeah.
MARYLIN And you're gonna have to pay some bonus money too.
MARK Why?
MARYLIN 'Cause you're gonna need these guys to sign a non-disclosure agreement and you're gonna need to be indemnified.
MARYLIN They say one unflattering word about you in public and you own their house, wife and kids.
MARK I invented Facebook.
MARYLIN I'm talking about what a jury'll see.
MARYLIN .That's what I do, that's what I'm doing here.
MARYLIN I'm trying to specialize in voir dire--jury selection.
MARYLIN Clothes, hair, wedding ring, speaking style, likability--
MARK Likability?
MARYLIN I've been licensed to practice law for all of-20 months and I could get a jury to believe you planted the story about Eduardo.
MARYLIN You know how?
MARYLIN Just by asking the question.
MARYLIN Watch.
MARYLIN Why weren't you at the sorority party that night?
MARK You think I'm the one who called the police?
Doesn't matter, I asked the question and now everybody's thinking about it.
You lost the jury in the first 10 minutes.
Farm animals?
Yeah,
MARK I was drunk and angry and stupid.
MARYLIN And blogging.
Pay the fine.
Get your parking validated.
Get out of it.
That's what Sy and the guys'll tell you in the morning.
MARK Would anyone mind it I stayed and used the computer for a minute?
MARYLIN No.
MARYLIN There's a night guy downstairs.
MARYLIN Stay as long as you want.
MARK Thanks.
MARK I appreciate your help today,
MARYLIN You're not an asshole, Mark.
MARYLIN You just want to be.
MARYI,IN, who's been putting on her coat, takes her briefcase and exits.
MARK sits down at the computer.
He logs on to Facebook.
He -types a name in the-search box: "Erica Albright".
Erica's name and picture come up, along with Boston University, '07.
Mark smiles.
She's on Facebook.
He moves the mouse back and forth between two boxes: "Send a Message."
and "Add as a Friend".
He clicks on "Add as a Friend".
A box comes up that reads: "Your request to add Erica Albright as a friend has been sent."
Then MARK clicks to his homepage and waits for the response.
And waits...
Cameron and Tyler Winklevoss received a settlement of 65 million dollars and signed a non-disclosure agreement, They rowed for the U.S. Olympic Team in Beijing and placed sixth.
MARK is still waiting...
Eduardo Saverin received an unknown Gash settlement.
His name has been restored to the Facebook masthead as a founder.
MARK is settling into his chair.
He'll wait all night if he has to.
Facebook has 180 million members in 60 countries.
It's currently valued at 15 billion dollars.
Mark zuckerberg is the youngest billionaire in the world.
MARK waits...
And waits...
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
