BAD TEACHER
Written by
Lee Eisenberg & Gene Stupnitsky
June 6, 2008
EXT. JOHN ADAMS MIDDLE SCHOOL - DAY To establish.
EXT. JOHN ADAMS MIDDLE SCHOOL - DAY A school marquee with removable plastic letters reads, "GOOD LUCK WITH FINALS!" A JANITOR opens the glass and starts removing the letters.
INT. TEACHER'S LOUNGE - DAY POP!
INT. TEACHER'S LOUNGE - DAY A Champagne cork hits the ceiling.
INT. TEACHER'S LOUNGE - DAY TEACHERS who rarely get to drink at work, jockey for
position, holding out their plastic flutes.
(Note: female teachers outnumber male teachers 12:1.)
PRINCIPAL WALLY SNUR, 40s, balding, faces the teachers.
He has a habit of blinking hard before speaking.
PRINCIPAL SNUR Well, it's been another great year here at JAMS.
PRINCIPAL SNUR Who can forget Mr. Pinkus' haunted classroom?
PRINCIPAL SNUR Sandy, thank you.
PRINCIPAL SNUR SANDY PINKUS, 40s, sporting a ponytail, smiles, clearly enjoying the small compliment.
SANDY I ain't afraid of no ghost.
SANDY The other teachers laugh.
PRINCIPAL SNUR Or the wild success of...
Wally, can I just say one quick thing?
Wally turns to AMY SQUIRREL, late 20s, cute and wholesome.
Any trace of sexuality she might have is wiped away by her adult pigtails.
She treats students and adults alike -- like students.
AMY Just wanted to remind everyone the school day's not over.
AMY So let's keep the drinking under control, hmm?
AMY That's it.
AMY Back to you, Wally.
AMY A bunch of teacher roll their eyes.
PRINCIPAL SNUR Thanks, Amy,
PRINCIPAL SNUR Or the wild success of the book drive for the women's prison sponsored by Ms.
PRINCIPAL SNUR Savicki's class?
PRINCIPAL SNUR A broad-shouldered teacher with spiky hair, MS.
PRINCIPAL SNUR SAVICKI, nods.
PRINCIPAL SNUR (CONT'D) But now as the summer is upon us, it's time to not only say goodbye to another school year, but to also say goodbye to a member of our faculty.
Elizabeth, can you come up here?
ELIZABETH HALSEY, mid 20s, pretty and petite, walks up to the front.
She sports an enormous diamond ring and dresses slightly more cosmopolitan than the other teachers.
PRINCIPAL SNUR (CONT'D) You've only been with us for one short year, but know that you'll always be a part of the JAMS family.
PRINCIPAL SNUR (CONT'D) Elizabeth gives Principal Snur an appreciative smile.
PRINCIPAL SNUR (CONT'D) The Teachers lightly applaud.
PRINCIPAL SNUR (CONT'D) And we got you a little something.
PRINCIPAL SNUR (CONT'D) Wally hands Elizabeth an envelope.
PRINCIPAL SNUR (CONT'D) She opens it and.
PRINCIPAL SNUR (CONT'D) pulls out a gift card: BOSTON MARKET.
PRINCIPAL SNUR (CONT'D) $37.
ELIZABETH Almost forty dollars.
ELIZABETH Thank you!
PRINCIPAL SNUR Why don't you say a couple words?
ELIZABETH Okay.
ELIZABETH Um...
ELIZABETH I'm not really good at this type of thing so I'll make it quick.
ELIZABETH I know I've only been here a year, but there's so much I'm going to miss...
INT. ELIZABETH'S CLASSROOM - DAY Elizabeth sits at her desk, cleaning it out.
INT. ELIZABETH'S CLASSROOM - DAY She's tossing the few personal effects she has into a banker's box.
ELIZABETH (V.0.) My students, probably most of all.I'm not saying they were little angels, butthey were all there to learn and that'sthe greatest gift a student can give a teacher.
ELIZABETH (V.0.) Elizabeth's class is horsing around, enjoying the last days of seventh grade.
ELIZABETH (V.0.) A dim-looking BOY tentatively approaches her desk with his yearbook in hand.
ELIZABETH (V.0.) He hands it to Elizabeth, who considers what to write for a beat, then smiles as she signs it.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Elizabeth walks down the hall holding her box.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY SIXTH, SEVENTH and EIGHTH graders all race past her, running toward their summer vacation.
ELIZABETH (V.0.) And I wish that I had gotten to know all of you better, but between four classes and planning a wedding, I had my hands full.
ELIZABETH (V.0.) From the little I do know about you, I know that our students are in good hands.
ELIZABETH (V.0.) Elizabeth passes Amy's classroom, where she is carefully removing inspirational posters from her walls and rolling them into cardboard tubes.
EXT. JOHN ADAMS MIDDLE SCHOOL - DAY Three middle school BURNOUTS are smoking weed in a thicket on the outskirts of the school property.
ELIZABETH (V.0.) And I can't believe it's all over.
ELIZABETH (V.0.) This year flew by.
ELIZABETH (V.0.) And even though I'll never teach again professionally, I've realized that I don't need a blackboard and classroom to set an example.
ELIZABETH (V.0.) Elizabeth comes up behind them.
ELIZABETH (CONT'D) Hand it over.
ELIZABETH (CONT'D) The Burnouts' eyes all go wide and they freeze.
ELIZABETH (CONT'D) One of the burnouts hands her the joint.
ELIZABETH (CONT'D) Everything.
ELIZABETH (CONT'D) The kids look at each other and then pull out a bag with a couple of joints.
ELIZABETH (CONT'D) They hand it over to Elizabeth.
ELIZABETH (CONT'D) This was a warning.
ELIZABETH (CONT'D) Next time, I don't call the principal.
ELIZABETH (CONT'D) I call the cops.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY Elizabeth walks to her brand new MERCEDES.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY She gets in, pulls out a joint and lights it.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY She takes a huge TOKE, and then PEELS out of the lot.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY She tosses her banker's box out the window and extends her hand, giving the school THE FINGER.
ELIZABETH Woo-hoo!
ELIZABETH A couple students look at her strangely.
ANGLE ON The dim-looking kid that had Elizabeth sign his yearbook.
ANGLE ON He flips to the faculty section, and by the picture of Elizabeth is her message: "YOU ARE ILLITERATE!"
You are...
Illit...
Illit...
Elizabeth's car comes barrelling toward him and nearly hits him.
She accelerates into the speed bumps, almost hitting the JANITOR from the opening shot, who's changing the plastic letters to read, "HAVE A GREAT SUMMER!"
Slow down!
A Mercedes with the vanity plate "HIS" is parked in the driveway of an upscale neighborhood.
Elizabeth's matching Mercedes pulls into the adjacent spot.
Her license plate reads "HERS."
A bachelor pad.
Top of the line electronics.
Lots of black leather furniture.
Tacky, but expensive.
Elizabeth pours two glasses of wine and takes a long sip.
Baby Doll?
MARK Coming!
MARK MARK, early 30s, exits the bedroom in his underwear.
MARK He's shaved his head to avoid signs of early balding and is also a full four inches shorter than Elizabeth.
MARK Thankfully for him, he has money.
Hey!
That was a quick party.
Elizabeth kisses Mark on the top of his head and hands him a glass.
ELIZABETH Yeah.
ELIZABETH You should have seen it.
ELIZABETH What a joke.
ELIZABETH She raises her glass for a toast.
ELIZABETH He raises his.
ELIZABETH (CONT'D) Here's to me never having to work again.
ELIZABETH (CONT'D) And I owe it all to you, Lover.
ELIZABETH (CONT'D) Elizabeth takes a big sip.
So I made a reservation at Ruth's Chris, and then I booked us a suite at the Drake, and I thought we could finish the night in "anal alley."
Hmm?
Something drops in the bedroom.
Mark, alarmed, turns towards the door.
Elizabeth brushes past him into --
Elizabeth enters to find -- NOTHING.
Mark follows her in.
Elizabeth looks around -- under the bed, in the closet, behind the door.
MARK See?
MARK Nothing.
MARK Just then, the wooden chest at the foot of the bed SNEEZES.
MARK Elizabeth opens the latch to find SHEILA, 23, dressed only in a thong, scrunched in the fetal position.
MARK She stands, revealing LARGE FAKE BREASTS, and steps out of the chest.
Motherfucker!
ELIZABETH How could you do this to me?!
ELIZABETH I'm sorry.
ELIZABETH You are buying me the biggest pair of yellow diamond earrings they make!
ELIZABETH I'm talking serious blood diamonds.
ELIZABETH Sheila SNEEZES again.
ELIZABETH Bless you.
Get out of my house, bitch!
MARK Don't talk to her like that.
ELIZABETH Excuse me?
ELIZABETH I love her.
ELIZABETH Mark puts his arm around Sheila.
ELIZABETH Elizabeth eyes Sheila's large breasts.
ELIZABETH You love her?
ELIZABETH She's a hooker.
She's not a hooker.
I dance.
Elizabeth takes a deep breath.
Listen, Marky, you made a mistake.
You're human.
I'm human.
And this time it was you.
Maybe six months from now, you'll walk in on me.
I don't know, but probably.
Sheila SNEEZES again.
ELIZABETH (CONT'D) Shut the fuck up.
ELIZABETH (CONT'D) And.
ELIZABETH (CONT'D) maybe I'm talking crazy, but I don't want to throw away our life together over something like this.
ELIZABETH (CONT'D) We're getting married!
ELIZABETH (CONT'D) I'm willing to fight for us.
MARK I'm not.
MARK And you know why?
MARK Because Sheila loves me -- and not just for my money.
MARK Sheila squeezes his shoulder.
ELIZABETH I'm sorry if I care that my future husband can support me.
ELIZABETH We didn't all grow up with a silver spoon in our mouths.
ELIZABETH You can't even imagine what it's like going to bed hungry, night after night.
MARK What are you talking about?!
MARK Both your parents are CPAs.
ELIZABETH My parents worked their asses off to send me to private school.
ELIZABETH Do you know what it's like driving a Pontiac when everyone else gets a Beemer the second they menstruate?
ELIZABETH That shit stays with you.
MARK It's over, Elizabeth.
ELIZABETH For the record, there's a shitload of things that I hate about you, but I still, would've gotten married.
ELIZABETH Because I love you.
MARK I'm gonna need the ring back.
MARK She grabs her bag and heads for the exit.
MARK Mark follows.
ELIZABETH You sad little troll!
ELIZABETH I hope you and your hooker enjoy chlamydia together!
MARK Elizabeth.
MARK The ring.
ELIZABETH I'm not even listening to you anymore.
ELIZABETH She starts to open the door.
ELIZABETH He closes it.
ELIZABETH The ring!
ELIZABETH Like I even want your gay-ass ring.
ELIZABETH She tries pulling it off.
ELIZABETH (CONT'D) It's not coming off.
ELIZABETH (CONT'D) I'll go to the jeweler's tomorrow.
ELIZABETH (CONT'D) Mark takes her hand and removes the ring with ease.
ELIZABETH (CONT'D) Elizabeth steps out into the night.
ELIZABETH (CONT'D) The door SLAMS behind her.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY A red 1994 Grand Am with a cracked windshield peels into the half-empty lot and screeches to a halt.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY The license plate reads "HERS."
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Elizabeth walks down the empty hall.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY It's possible a person has never looked less happy to be anywhere.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY FAINT SOFT ROCK plays from an open door.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Something from inside the classroom catches Elizabeth's eye.
ELIZABETH You've gotta be shitting me.
The room has been decorated to within an inch of its life.
Every surface is covered with posters like "Noted African-Americans," or "Hispanic American Hall of Fame," or "Women Who Dared."
A RED DELICIOUS APPLE has been placed on each student's desk.
Amy, dressed casually in cargo shorts and texas, is trying to hang a large "INTEGRITY" poster.
She looks over, sees Elizabeth staring at her, and immediately lights up.
AMY Elizabeth Halsey, as I live and breathe!
ELIZABETH Amy Squirrel.
AMY I know we barely got a chance to get to know one another last year -- what with you planning the wedding of the century and me juggling all my extra-currics -- but I just want to say that I'm super excited to be across-the-hall-mates.
ELIZABETH Okay.
AMY And I know you kinda skated by last year, doing the bare minimum thing -- you were kind of a lone wolf -- but now you're back and I just know that you are going to rededicate yourself to the task at -- Amy notices Elizabeth's bare hands.
AMY (CONT'D) Where's your beautiful ring?
ELIZABETH My fiance and I broke it off.
ELIZABETH I found him in bed with someone else.
ELIZABETH Oh my gosh!
ELIZABETH It was another man.
Shut the front door!
Somebody needs a hug.
ELIZABETH Somebody doesn't.
AMY Hm.
AMY Another time then.
AMY Elizabeth takes an apple from a desk.
These washed?
AMY Of course.
AMY I'd never serve a student unwashed fruit.
AMY CRUNCH.
AMY Elizabeth takes a huge bite out of the apple.
I thought the teachers got the apples.
AMY Well, I think the students teach me at least as'much as I teach them.
ELIZABETH Stupid.
ELIZABETH Elizabeth tosses the mostly uneaten apple into the trash and exits.
ELIZABETH It hits the rim and lands on the floor.
ELIZABETH Okey-dokey.
INT. ELIZABETH'S CLASSROOM - DAY It's like an asylum -- nothing on the walls.
INT. ELIZABETH'S CLASSROOM - DAY Elizabeth reads from a stack of US Weekly's and circles pictures of CELEBRITY BREASTS.
INT. ELIZABETH'S CLASSROOM - DAY LYNN, late 30s, the kind of woman who spends a lot of time on her internet dating profiles, but rarely gets emailed, pokes her head in.
LYNN Oh sorry, am I interrupting?
ELIZABETH Um -- kinda.
LYNN Do you want to grab some lunch?
ELIZABETH I'm in the middle of something, Lynn.
ELIZABETH My treat.
ELIZABETH Fine.
Elizabeth and Lynn sit at an outdoor table.
Lynn picks at a garden salad.
Elizabeth is eating a bucket of chicken and drinking a large drink.
She pulls a bottle of cough syrup from her purse and dumps it into her drink.
LYNN You have that thing going around, huh?
LYNN Are you excited for tomorrow?
ELIZABETH Is tomorrow Saturday?
LYNN No, it's the first day of school.
ELIZABETH Wait, I thought I had a week to get my class together.
LYNN Yeah, that was last week.
ELIZABETH Fuck my ass.
LYNN If you hate teaching so much, why don't you just get another job?
ELIZABETH And do what?
ELIZABETH Sell perfume at the mall?
ELIZABETH Work at a day care center?
ELIZABETH You know, when I first got into teaching, I thought I was doing it for all the right reasons: short hours, summers off, no accountability.
LYNN I love my summers.
LYNN Fresh corn.
LYNN Mmm.
ELIZABETH From now on, my full-time job will be finding a guy who will take care of me --
LYNN Oh god, I pray for that --
ELIZABETH And that makes a shit ton of money and doesn't ask too many questions.
ELIZABETH I spent most of my summer hanging out at the bars near where the Bulls practice.
ELIZABETH Had some fun, got some cool souvenirs that I Ebayed, but those guys aren't looking to settle down.
ELIZABETH And they all wear condoms.
ELIZABETH And then they take the condoms with them.
ELIZABETH That's how paranoid they are that a girl will try and get pregnant.
ELIZABETH Like it's so easy to get pregnant from a guy nutting into a condom.
LYNN You're gonna find someone great.
ELIZABETH I've been thinking about it a lot.
ELIZABETH I mean, I figure I'm like an 8, 8.5.
ELIZABETH But once I get my new tits, I'll probably be a --
LYNN You don't want to do that.
LYNN You're already so pretty.
ELIZABETH I know I'm hot, Lynn, but I don't stand a chance against all those Barbies dolls out there.
ELIZABETH Anna Nicole had it right, may she rest in peace.
ELIZABETH Lynn checks her watch.
LYNN We should finish up.
LYNN Wally's doing that big orientation for teachers in the auditorium.
ELIZABETH Yeah, I'm not going to that.
LYNN But it's mandatory.
ELIZABETH Ooohhh...
LYNN Yeah, I probably won't go either.
LYNN I don't know I might.
LYNN I'll probably go, but just sit in the back.
LYNN Maybe leave early.
LYNN Maybe stay till the end.
LYNN Play it by ear.
LYNN Or just stay till the end.
LYNN Lynn takes both their, trays and dumps them.
LYNN (CONT'D) This was fun.
ELIZABETH Yeah, it was alright.
ELIZABETH When you said you were taking me to lunch, I kinda thought it was going to be nicer, but this was okay.
LYNN Sorry.
ELIZABETH It's okay.
ELIZABETH You can get me next time.
INT. ELIZABETH'S APARTMENT - NIGHT Not much character, not many furnishings.
Elizabeth is online looking at a PORN SITE.
She stares at the SCREEN and compares breasts to the ones in US Weekly.
She reaches for a bong and pulls a huge hit.
The front door opens and her roommate, KIRK, early 30s, boarish and carrying a tattered backpack and a Big Gulp, walks quickly past Elizabeth.
ELIZABETH Hey, Kirk, what do you think about me with Jessica Simpson's tits?
ELIZABETH He stares at her chest intently.
ELIZABETH She's not bothered by it.
ELIZABETH Go bigger.
ELIZABETH Kirk enters his bedroom and slams the door.
ELIZABETH Cool, yeah.
ELIZABETH She glances at the clock: 3:14 AM.
ELIZABETH (CONT'D) Fuck my ass.
INT. ELIZABETH'S APARTMENT - BEDROOM - NIGHT Elizabeth is asleep.
INT. ELIZABETH'S APARTMENT - BEDROOM - NIGHT After a beat, the ALARM goes off.
INT. ELIZABETH'S APARTMENT - BEDROOM - NIGHT She checks the clock: 5.:15.
INT. ELIZABETH'S APARTMENT - BEDROOM - NIGHT She groans.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY First day of school excitement.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY The bell RINGS, and like rats, the KIDS scurry to their various classes.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Before long, the hallway is empty.
INT. ELIZABETH'S CLASSROOM - MORNING In one corner, CHASE, clearly at the top of the seventh grade food chain, shows off a photo spread of herself modelling in a "Western-Style" clothing catalogue.
INT. ELIZABETH'S CLASSROOM - MORNING GARRETT, 12, wearing grey, stained sweatpants and a grey sweatshirt with block letters that read "GYMNASTICS," stares longingly at Chase from a few desks away.
CHASE The photographer was, like, sooo nice.
CHASE He made me feel sooo comfortable.
I might get flown to Kansas City for their fashion week.
Oh my.
Chase and her friends turn to face Garrett, who's as surprised as they are that he spoke.
CHASE Stalk much?
CHASE Garrett quickly turns away.
CHASE Chase rolls her eyes.
CHASE An angry-looking kid, TRISTAN, wearing a MICHAEL VICK JERSEY, turns to Garrett.
Faggot.
Bless you.
TRISTAN What'd you say to me?
TRISTAN Elizabeth, with large bags under her eyes, enters the class.
TRISTAN Tristan, on a dime, heads back to his seat.
TRISTAN The class immediately quiets down.
TRISTAN SASHA, 12, dressed like a paralegal, walks up to Elizabeth with a large Tupperware tray.
SASHA Hi, I'm Sasha.
SASHA It's a pleasure to meet you.
SASHA My mother baked these for you.
ELIZABETH Just leave them on the desk.
ELIZABETH Sasha, confused, gently puts them down and stands there.
ELIZABETH After a moment, Elizabeth looks up.
ELIZABETH (CONT'D) You need something?
- Sasha shakes her head and retreats to her desk at the front of the class.
ELIZABETH (CONT'D) Anyone here seen "Stand and Deliver?" Show of hands.
ELIZABETH (CONT'D) No one?
ELIZABETH (CONT'D) Edward James Olmos?
ELIZABETH (CONT'D) Wow.
ELIZABETH (CONT'D) Elizabeth takes a DVD from her bag.
ELIZABETH (CONT'D) She points to two KIDS in the front of the class.
ELIZABETH (CONT'D) You and you, go grab the TV and roll it up front.
ELIZABETH (CONT'D) And you, go shut off the lights.
ELIZABETH (CONT'D) The two kids, SHAWN and SPENCER, roll the TV over.
ELIZABETH (CONT'D) Sasha shuts off the LIGHTS.
SASHA We're watching a movie on the first day?
I think it's awesome.
You rock.
GARRETT I agree with Chase.
GARRETT Elizabeth pops in the DVD.
GARRETT "Stand and Deliver," starring Edward James Olmos as a tough-as-nails calculus teacher in an inner-city school begins.
GARRETT Elizabeth takes a bite of one of Sasha's cookies and immediately spits it out.
ELIZABETH Ugh.
ELIZABETH Oatmeal raisin?
ELIZABETH She pushes the Tupperware tray into the trash next to her desk.
ELIZABETH Sasha looks on, sadly.
INT. JOHN ADAMS MIDDLE SCHOOL - CAFETERIA - DAY Lunch is in full swing.
INT. JOHN ADAMS MIDDLE SCHOOL - CAFETERIA - DAY Each clique has staked its own territory.
INT. JOHN ADAMS MIDDLE SCHOOL - CAFETERIA - DAY Several TEACHERS, Elizabeth and Amy among them, are on lunch duty.
ANGLE ON GARRETT, sitting alone, writing in a journal.
ANGLE ON Tristan, the bully, tosses a bowl of cole slaw at Garrett.
TRISTAN Incoming!
TRISTAN Direct hit.
TRISTAN The cole slaw nails him in the shoulder.
TRISTAN Garrett picks some of the cole slaw off his shirt and eats it.
TRISTAN He continues writing.
TRISTAN Amy races over to Tristan and writes him up.
TRISTAN Elizabeth watches, bored, struggling to keep her eyes open.
TRISTAN Amy heads over to Elizabeth.
AMY Somebody's got a case of the sleepies.
AMY Did you see what just happened?
ELIZABETH Yeah, that one kid hit the other kid with the cole slaw.
AMY You weren't at the orientation the other day, but we're doing something new this year.
AMY It's very exciting.
AMY We're splitting the cafeteria into quadrants.
AMY Elizabeth yawns.
AMY (CONT'D) So, anyways, in order for the quadrant system to work, it's vital that each teacher maintain order within their quadrant.
AMY (CONT'D) Because it's really tough for me as head lunch monitor -- or another teacher -- to leave their quadrant to discipline a kid in another quadrant.
AMY (CONT'D) I know it's a lot to take in.
AMY (CONT'D) I'd be happy to sit with-you after school and explain all of the new guidelines.
ELIZABETH Tell you what.
ELIZABETH Why don't you send me a memo, and if I have any questions, I'll come to you.
AMY Okay, Elizabeth.
AMY Sounds like a plan, Stan.
Oh, I meant to ask you.
Did I hear that you were showing a movie this morning?
ELIZABETH How do I know what you heard?
AMY Fair enough.
AMY Listen, I don't want to tell you how to run your class, but maybe it might be fun to do some ice-breakers.
AMY Like "Telephone Charades" or "The String Game."
AMY Or start doing practice questions for the state test.
AMY It's never too soon to start.
ELIZABETH Are we gonna have a problem, me and you?
AMY Oh, shishkebobs, no.
AMY If I gave you that impression, I am so sorry.
AMY Actually, I was really hoping that we could be more than across-the-hall-mates.
ELIZABETH I don't know what you've heard, but I don't munch box.
AMY No, of course not.
AMY I don't even know what that is.
AMY I just meant friends.
ELIZABETH Like getting manicures and going shopping on Sundays?
ELIZABETH Shit like that?
AMY Yes!
AMY Yes!
AMY And helping each other out.
AMY Looking out for one another.
ELIZABETH That's cool.
ELIZABETH Tell you what, friend, I'm gonna get going.
ELIZABETH Cover for me?
ELIZABETH Elizabeth doesn't wait for an answer, walks off.
But you can't leave.
Lunch doesn't end for another...
AMY (CONT'D) Seven minutes.
AMY (CONT'D) Who's going to watch your quadrant?
INT. AMY'S CLASSROOM - LATER Empty.
INT. AMY'S CLASSROOM - LATER Elizabeth looks around and spots the "INTEGRITY" poster on the wall.
INT. AMY'S CLASSROOM - LATER She walks over and studies it.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Elizabeth walks down the hallway with the rolled up poster.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY She.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY passes a man, obviously lost, looking at a map.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY This is SCOTT, 30.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Handsome in a wholesome way.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Elizabeth walks by as he looks up at her helplessly.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY She turns on her heels.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Fresh fish.
Hi there.
You look a little lost.
SCOTT Hi.
SCOTT Can you tell me where Room 124 is?
ELIZABETH I'll do you one better.
ELIZABETH I'll take you there.
SCOTT Oh, you don't have to do that.
ELIZABETH Will you stop?
ELIZABETH It'd be my pleasure.
SCOTT Thanks!
SCOTT I feel like I've been walking around in circles for the last fifteen minutes.
Scott Delacorte.
I'm the new sub.
ELIZABETH Elizabeth Halsey, 7th Grade Language Arts.
ELIZABETH Welcome, welcome.
ELIZABETH They shake hands a beat too long.
ELIZABETH Elizabeth notices Scott's VERY EXPENSIVE WATCH.
ELIZABETH (CONT'D) Helluva watch.
ELIZABETH (CONT'D) What's that -- a Jaeger- LeCoultre?
SCOTT Good eye!
ELIZABETH Thanks.
ELIZABETH I love men's watches.
ELIZABETH It's kind of a hobby.
SCOTT It's a bummer knowing my watch could feed a village for .a year, but my grandfather designed it, so...
ELIZABETH Oh?
ELIZABETH Your grandfather designs watches?
SCOTT The family business.
SCOTT My mom's maiden name is Jaeger.
ELIZABETH Shut up!
SCOTT My parents had a minor meltdown when I decided to join the Peace Corps and become a teacher.
SCOTT But they've been cool about it.
SCOTT Elizabeth smiles and they start walking down the hall.
SCOTT (CONT'D) Integrity.
SCOTT (pointing to poster)..
SCOTT The poster.
SCOTT "Integrity."
SCOTT What a great message for the kids.
ELIZABETH That's why I got it.
ELIZABETH They turn a corner.
ELIZABETH Garrett wheels his backpack past them.
GARRETT Hey, Ms. Halsey!
ELIZABETH Hey...
ELIZABETH dude...
ELIZABETH She slaps him five.
ELIZABETH Scott notices, smiles.
SCOTT Man, I can't wait for the day that I have my own classroom.
ELIZABETH Yeah...
ELIZABETH So did you and your wife just move to town?
SCOTT I'm not married.
ELIZABETH Me neither.
ELIZABETH I was engaged until I walked in on my fiance cheating on me.
ELIZABETH With his brother.
SCOTT That's horrible!
Ooh, 124!
This is me.
ELIZABETH Nice to meet you, Scott Delacourte.
ELIZABETH Hopefully, we'll be seeing a lot of each other.
Only if a teacher gets sick.
Great meeting you, Elizabeth Halsey.
He heads into the room.
Elizabeth cocks her head, checking out his ass as the door closes.
Very nice meeting you.
A PAIR OF PERFECT FAKE BREASTS.
A hand cups them from underneath.
Pull back to reveal DR.
VOGEL, 40s, and his receptionist, DANNI, probably in her 40s, with her shirt off.
Elizabeth watches, rapt.
DR. VOGEL As you can see, the weight is evenly distributed and there's minimal scarring.
Dr. Vogel.
DR. VOGEL "Best Hands in Chicago."
DR. VOGEL Absolutely.
DR. VOGEL Take them for a spin.
DR. VOGEL Elizabeth reaches out, squeezes Danni's breasts.
ELIZABETH Wow.
ELIZABETH And the nipples are just...
ELIZABETH I love them.
ELIZABETH I'll take two.
ELIZABETH They all laugh.
ELIZABETH Elizabeth notices Dr. Vogel'.s watch.
ELIZABETH (CONT'D) Maurice Lacroix.
ELIZABETH (CONT'D) That's a great watch.
And how's that going?
DR. VOGEL She's my rock.
Alright, thanks, Danni.
Danni puts her bra and blouse back on and exits.
So, Elizabeth, have you given any thought to size?
ELIZABETH I was thinking, you know, maybe a D.
DR. VOGEL IJh huh, uh huh.
DR. VOGEL I ,would say, though, with your frame, you might consider something smaller.
DR. VOGEL A large B, maybe a C cup.
DR. VOGEL You'd be surprised how significant those would look.
ELIZABETH Hmm.
ELIZABETH Yeah, I think I'll go with the D's, really turn some heads.
DR. VOGEL You know, Elizabeth, breast enhancement's not a cure-all.
DR. VOGEL I just want to make sure you have realistic expectations.
ELIZABETH Doctor, I lost my fiance to a woman with monster fake tits.
ELIZABETH So now I need monster fake tits so that I won't lose my next fiance.
ELIZABETH Those are my expectations.
ELIZABETH Is that realistic enough for you?
DR. VOGEL Very good then.
INT. DR. VOGEL'S OFFICE - RECEPTION AREA - DAY Elizabeth leans over the counter and grabs a mint from a small bowl.
INT. DR. VOGEL'S OFFICE - RECEPTION AREA - DAY Danni sits behind her desk wearing a headset.
DANNI So you'll be off your feet for about two weeks...
DANNI what works for you?
ELIZABETH Let's do December 19th.
ELIZABETH Start of winter break.
DANNI The 19th it is.
DANNI So the total is $9300 for the surgery plus one night stay at our facility.
DANNI How would you like to pay?
DANNI Elizabeth laughs.
DANNI Danni laughs.
ELIZABETH That's absurd.
ELIZABETH What if I don't spend the night at your facility?
DANNI The night's included in the price.
DANNI Did you not read our literature?
ELIZABETH No.
ELIZABETH A MIDDLE-AGED DOCTOR walks by.
ELIZABETH (CONT'D) Hi...
ELIZABETH (CONT'D) Listen, I'm a teacher, not a drug dealer.
DANNI We accept all major credit cards.
ELIZABETH My credit situation is complicated.
DANNI I'm sorry, but if you can't pay, I can't schedule the appointment.
You know, there are less expensive options.
Have you looked into South America?
ELIZABETH I'll be back.
ELIZABETH Elizabeth dramatically scoops a handful of mints from the bowl and storms out.
INT. ELIZABETH'S APARTMENT - NIGHT Elizabeth, her cell phone cradled to her ear, pulls a LEAN CUISINE out of a freezer STOCKED with them.
Look, I just really need some money.
It's, for a surgery I need.
Elizabeth pokes holes in the Lean Cuisine with a knife and turns on the microwave.
Yes, as a matter of fact, it is about my breasts, dad.
Sorry.
Happy belated birthday.
So, can you wire me some money or not?
Elizabeth walks up a driveway and looks around.
ELIZABETH So I won't beat around the bush, Grammy.
ELIZABETH She pulls the kitchen knife from her bag and SLASHES the back tire of a late-model CAMRY.
ELIZABETH (CONT'D) I'm dying and I need money for surgery.
ELIZABETH (CONT'D) Really?
ELIZABETH (CONT'D) Nothing?
ELIZABETH (CONT'D) Don't you get social security or something?
ELIZABETH (CONT'D) Elizabeth goes around to another tire.
ELIZABETH (CONT'D) Slash.
Elizabeth is still on the phone.
CLOSE ON her computer screen.
Her checking account balance: $45.66.
ELIZABETH Listen, limpdick, you owe me for breaking off the engagement.
ELIZABETH Do you know how embarrassing that was?!
Lover, I don't want to fight.
It's just 10000 dollars and it would really mean the world to me.
Lover?
You there?
Elizabeth hurls her phone at the wall.
It smashes.
ELIZABETH (CONT'D) Fucking Troll!
ELIZABETH (CONT'D) Kirk pokes his head out of his bedroom.
KIRK Did you call my name?
ELIZABETH No.
ELIZABETH I said 'fucking troll.'
KIRK Oh, I thought you said Kirk.
KIRK He turns and heads back in to his room.
ELIZABETH Hey, you got ten grand?
KIRK Nope.
KIRK Kirk closes his door.
KIRK After a beat, he opens it.
KIRK (CONT'D) Also, I might be a little short on the rent this month.
KIRK (CONT'D) Like, a lot short.
He closes his door.
The microwave BEEPS.
Dinner's ready.
INT. TEACHER'S LOUNGE - DAY Elizabeth and Lynn speak in hushed voices in the corner by a vending machine.
INT. TEACHER'S LOUNGE - DAY Amy grades papers on a ratty- looking couch.
INT. TEACHER'S LOUNGE - DAY She glances up at Elizabeth and Lynn.
LYNN I don't know.
LYNN That's a lot of money.
ELIZABETH I know.
ELIZABETH And I hate asking a friend for money -- especially as good a friend as you.
ELIZABETH This has its desired effect on Lynn.
LYNN Maybe I could sell that jewelry my grandmother gave me?
ELIZABETH That turquoise crap?
ELIZABETH Blech.
ELIZABETH No one's buying that.
ELIZABETH But it looks great on you.
LYNN Thanks.
LYNN What about Mark?
ELIZABETH What type of person do you think I am?!
ELIZABETH That assbag cheated on me.
ELIZABETH Did I ever tell you that he has a mole on the tip of his dick?
ELIZABETH I'm just trying to better myself.
ELIZABETH I don't think that's asking for so much.
ELIZABETH Amy walks over.
AMY 'Scuse,me.
AMY Just gonna scooch in here.
AMY She drops quarters into the vending machine, but doesn't bother selecting an item.
AMY This was clearly her "in."
AMY She turns to Elizabeth and Lynn.
AMY (CONT'D) Sooo...
AMY (CONT'D) I know it's none of my business, but I couldn't help but overhear your conversation and I just want to say, that you shouldn't change a thing.
AMY (CONT'D) You should be happy with the way you are.
AMY (CONT'D) That's true.
ELIZABETH Huh.
ELIZABETH Well, do you think mental retards should be happy with the way they are?
ELIZABETH Amy stammers.
ELIZABETH (CONT'D) Lynn, you teach them.
ELIZABETH (CONT'D) What do you think?
I've never asked them.
AMY I would never --
ELIZABETH We don't all have your tits, Squirrel.
ELIZABETH So maybe you should think before you interrupt a private conversation.
AMY I guess that's what you get for trying to help...
AMY Amy pushes the coin release on the vending machine and takes back her change without getting a drink.
AMY Amy heads back to the couch.
ELIZABETH That's right.
ELIZABETH Walk away.
ELIZABETH (then, noticing)- There he is!
ELIZABETH Scott enters.
ELIZABETH All of the female teachers light up.
ELIZABETH There he is!
AMY Well, look what the cat dragged in!
SCOTT I wish it was under better circumstances.
SCOTT Stu Riley's car was vandalized last night.
SCOTT Right in his driveway.
AMY Gang members, probably.
The public school system failed them.
Elizabeth and Amy nod vigorously.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY An empty hallway.
So forget about the way it used to be.
This is not a damn democracy!
We are in a state of emergency and my word is law!
There's only one boss around here, and that's me.
The HNIC.
INT. ELIZABETH'S CLASSROOM - DAY The class is watching "Lean on Me," with Morgan Freeman as a tough-as-nails principal in an inner-city school.
INT. ELIZABETH'S CLASSROOM - DAY Amy's "Integrity" Poster now hangs above the TV.
Head Nigger In Charge.
The bell RINGS.
ELIZABETH We'll pick this up again tomorrow.
ELIZABETH The students shuffle out.
ELIZABETH Garrett hustles after Chase.
GARRETT Quite a film, huh?
GARRETT Chase gives him a weird look and then exits with her friends.
GARRETT Sasha lingers by Elizabeth's desk.
ELIZABETH What.
SASHA I'm a student leader for the D.C. trip --
ELIZABETH Shocker.
SASHA And we're having our car wash this weekend.
SASHA If you're around, maybe we could wash your car.
ELIZABETH I've got some Mexicans who already do it for nothing.
SASHA It's for a good cause.
SASHA This year, we're trying to get some extra money so that we can go on a Duck Tour!
SASHA She hands Elizabeth a flyer.
SASHA Elizabeth glances at it.
Last year's seventh grade raised $6000.
INT. J.A.M.S. - ADMINISTRATION BULLPEN - DAY Elizabeth walks past the SCHOOL SECRETARY toward the Principal's office.
SCHOOL SECRETARY You can't go in there.
SCHOOL SECRETARY He's with a student.
SCHOOL SECRETARY Elizabeth ignores her, adjusts her blouse, and enters.
INT. J.A.M.S. - PRINCIPAL SNUR'S OFFICE - DAY The office is decorated with a DOLPHIN motif.
INT. J.A.M.S. - PRINCIPAL SNUR'S OFFICE - DAY Figurines, a picture of Principal Snur kissing a dolphin.
INT. J.A.M.S. - PRINCIPAL SNUR'S OFFICE - DAY Dolphin calendars.
INT. J.A.M.S. - PRINCIPAL SNUR'S OFFICE - DAY This guy loves dolphins.
INT. J.A.M.S. - PRINCIPAL SNUR'S OFFICE - DAY Principal Snur sits next to ARKADY, a small pale kid.
PRINCIPAL SNUR If you don't like to get wet, Arkady, you could try using deodorant, anti-.
PRINCIPAL SNUR perspirant, maybe some cologne.
PRINCIPAL SNUR I know a lot of the older boys are wearing the body spray.
Bodish spray.
Elizabeth enters and immediately recoils from the smell.
ELIZABETH Blugh!
ELIZABETH Arkady and Principal Snur both look up.
ELIZABETH He holds up his finger -- "one minute."
ELIZABETH Elizabeth notices his cheap dolphin watch.
PRINCIPAL SNUR So why don't you think about that and I'll let your teachers know that you're working on it?
PRINCIPAL SNUR Arkady nods and quickly exits.
ELIZABETH Sorry, I didn't realize you were in with anyone.
PRINCIPAL SNUR We were just finishing up.
PRINCIPAL SNUR Elizabeth, I actually meant to talk to you.
PRINCIPAL SNUR Did I hear that you were showing movies all last week?
ELIZABETH Um...
ELIZABETH some clips, maybe.
ELIZABETH I think in a lot, of ways, movies are the new books.
PRINCIPAL SNUR Huh.
PRINCIPAL SNUR Elizabeth tries a different tact.
PRINCIPAL SNUR She picks up a dolphin- shaped clock from the desk.
ELIZABETH Is this new?
ELIZABETH I love it!
ELIZABETH I think dolphins are smarter than humans.
PRINCIPAL SNUR Me too!
PRINCIPAL SNUR And if you like that, you'll love this.
Principal Snur pulls out an "Adopt-A-Dolphin" certificate.
He lives in the Cayman Islands.
ELIZABETH What a great story.
ELIZABETH Principal Snur visibly relaxes.
ELIZABETH He's sitting across from a kindred spirit.
PRINCIPAL SNUR So what else is new?
ELIZABETH Actually, I was thinking that I want to get more involved.
PRINCIPAL SNUR What a nice surprise.
ELIZABETH Specifically, I thought I could supervise the car wash.
PRINCIPAL SNUR Amy's been running it the last two years...
ELIZABETH She just does so much.
ELIZABETH It might be nice to give her a little rest.
ELIZABETH Especially that early on a Saturday.
PRINCIPAL SNUR I'm so happy that you're dedicating yourself and becoming a real member of the JAMS family.
ELIZABETH It just feels so good to help.
INT. J.A.M.S. - PRINCIPAL SNUR'S OFFICE - DAY Amy stands in the door where Elizabeth was just standing.
INT. J.A.M.S. - PRINCIPAL SNUR'S OFFICE - DAY Principal Snur is behind his desk.
AMY Elizabeth?!
AMY For the seventh grade carwash?
AMY That's bonkers!
Amy immediately regrets saying "bonkers."
AMY (CONT'D) I'm sorry.
AMY (CONT'D) I didn't mean to blow my stack.
PRINCIPAL SNUR I just thought it was nice to see some other teachers step up.
AMY We raised over $6000 last year.
AMY That's a record.
AMY Is this really the best time to start experimenting?
PRINCIPAL SNUR Amy, I see you taking on a.lot of responsibility, what with directing "Annie" and all your work with D.A.R.E.
PRINCIPAL SNUR I'd just hate to see you get overwhelmed like you did in 2004.
PRINCIPAL SNUR She stares at him -- clearly, this is a touchy subject.
AMY Of course.
AMY Well, I should skedaddle.
AMY Looks like someone needs to plan a Saturday morning bike ride.
AMY She turns on her heels and walks out.
Elizabeth is asleep.
Her ALARM goes off.
It's 5:45 AM.
She opens her eyes, sees the time, considers for a beat, then hits SNOOZE.
She closes her eyes.
- After a beat, the ALARM goes off again.
She hits SNOOZE.
Quick Cuts.
Elizabeth hits the snooze button EVERY NINE MINUTES until 8:45.
She stares at the clock.
Garrett stands at the school entrance, holding a giant cardboard sign that reads "CAR WASH" as a few CARS pull in.
Chase, and the other popular girls, are dressed in seventh-grade sexy -- they've tied off their shirts.
The BOYS run around spraying each other, but mostly spraying Garrett.
Garrett laughs, mistakenly thinking that he's part of the fun.
GARRETT Oh, I'm gonna get you guys!
GARRETT A couple of PARENT CHAPERONES stand in small clusters.
GARRETT Tristan, the bully, cocks his arm and aims a soapy sponge at Garrett.
Whoa.
The CAMERA FOLLOWS Tristan's gaze.
ELIZABETH steps out of her car.
She's wearing HIGH HEELS, DAISY DUKES and a BIKINI TOP.
She looks both spectacular and ridiculous.
A couple of PARENTS look over at Elizabeth, in shock.
ELIZABETH Sorry I'm late.
I'm going to say something about her outfit.
The MOTHERS vigorously nod in agreement.
A DAD pipes in.
Well, if it helps raise money...
The other DADS vigorously nod in agreement.
--Elizabeth holds the "Carwash" sign.
A LINE of CARS forms.
An OLDER MAN in an immaculately clean CADILLAC, rolls down his window and hands her money.
--Elizabeth washes in SLO MO, shakes out her hair as she gets WET.
The BOYS and their FATHERS stare at her.
--The GIRLS try to mimic Elizabeth's seductive behavior.
Their MOTHERS run over and pull them away.
--The Older Man in the Cadillac comes back to have his car re-washed.
The carwash is wrapping up.
Elizabeth counts money at a makeshift table and puts the earnings into a metal lockbox.
She glances around and then shoves a large clump of cash into her DAISY DUKES.
What are you doing?
Elizabeth looks up and sees Sasha hiding behind a TRUCK, clearly spying.
ELIZABETH Nothing.
ELIZABETH Get out of here, Dummy.
SASHA Are you stealing our money?
ELIZABETH How dare you?!
ELIZABETH I'm here early on a Saturday for you guys.
ELIZABETH And for the record, nobody likes a tattle tale.
SASHA I haven't tattled.
SASHA Yet.
ELIZABETH Good.
ELIZABETH Cause if you do, I'll deny it and flunk your ass.
ELIZABETH How will that look on your resume?
I didn't say I would say anything.
ELIZABETH Alright then.
ELIZABETH Now beat it.
ELIZABETH I've gotta finish counting this money.
ELIZABETH Sasha walks off.
ELIZABETH Elizabeth picks up a hose and sprays her.
ELIZABETH (CONT'D) See you Monday!
ELIZABETH (CONT'D) Elizabeth waves to SASHA'S MOTHER, who eagerly waves back.
ANGLE ON ANY, across the street, watching through binoculars.
ANGLE ON She's straddling her bike and is wearing a helmet and a sheen of recently-applied suntan lotion.
ANGLE ON She takes a sip from her Camelbak, and pedals away.
INT. ELIZABETH'S APARTMENT - BEDROOM - NIGHT CLOSE ON a fish bowl with a crude sign that reads "New Tits."
INT. ELIZABETH'S APARTMENT - BEDROOM - NIGHT Elizabeth drops in fistfuls of crumpled cash and then writes in a notebook: $1300.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Amy walks down the hall.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY She sees Principal Snur slip into the bathroom.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Amy walks up to the MEN'S FACULTY BATHROOM door and waits.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY The BELL RINGS.
AMY Shishkebobs.
AMY She hesitates a beat and then enters.
Wally is in a stall reading a brochure for a DOLPHIN TOUR.
Amazing.
AMY Wally?
AMY Are you in here?
AMY It's Amy Squirrel.
AMY He instinctively covers himself with the brochure.
PRINCIPAL SNUR Amy?
PRINCIPAL SNUR What are you doing?
PRINCIPAL SNUR Get out!
Amy standing inside.
She scrunches her nose at the smell.
AMY This'll just take a sec.
AMY I thought you might want to know that Elizabeth Halsey showed up at the carwash in a bikini top and short-shorts.
AMY It was pretty racy stuff.
Can we talk about this later?
AMY "Later we'll all die, said the gator to the fly."
Another TEACHER walks past Amy, looking confused.
He hesitates and then goes into an adjoining stall.
PRINCIPAL SNUR Look, Josh Gershman's dad called and said that the carwash was a huge success.
PRINCIPAL SNUR And Lauren Rissman's dad called and said the kids had a great time.
AMY I don't want to speak out of school, but I happened to be pedalling by and saw her get.pretty chummy with the money.
AMY ,And remember, we barely know anything about her.
AMY She was a real lone wolf last year.
PRINCIPAL SNUR Are you accusing Elizabeth of embezzling from the seventh grade car wash?
AMY Something about this doesn't pass the smell test, Wally.
PRINCIPAL SNUR Well, they raised over $7000, so whatever she did worked.
PRINCIPAL SNUR And next time you accuse a fellow teacher of stealing, you better be damn sure.
PRINCIPAL SNUR We're done here.
PRINCIPAL SNUR Amy takes a deep breath.
PRINCIPAL SNUR Her face is BEET RED.
AMY Thanks for the pep talk.
AMY Have a super day, you two.
AMY Amy exits.
AMY Immediately, there is an IMMENSE ERUPTION from the other stall, followed by a sigh.
Christ...
I thought she was never going to leave.
INT. TEACHER'S LOUNGE - DAY Sandy, the math teacher with the ponytail, sits at the table grading papers.
INT. TEACHER'S LOUNGE - DAY Another TEACHER dozes in the corner.
ELIZABETH Hey!
ELIZABETH Are those new Doc Marten's?
Sandy looks behind him at the dozing teacher.
"Is she talking to me?" Guilty.
ELIZABETH How's Period 5?
SANDY Great, thanks for asking.
SANDY We got a new bassist and we finally got a regular gig, which is nice because it's earned.
SANDY It's time to show the world that a bunch of teachers can really rock out.
ELIZABETH Awesome!
Hey, would you mind grabbing me my yogurt from the fridge?
Sure thing.
Sandy goes to the fridge.
Elizabeth pulls visine from her bag, and as his head goes into the fridge, she squirts the entire container into his coffee mug.
You should come to one of our shows.
He hands her the yogurt.
ELIZABETH Oh, I can't.
ELIZABETH Elizabeth exits.
ELIZABETH Sandy sadly takes a sip of his coffee.
SANDY I didn't even tell you the dates.
INT. ELIZABETH'S CLASSROOM - DAY Elizabeth's class is seated.
INT. ELIZABETH'S CLASSROOM - DAY They're staring at her, waiting for her to begin.
CHASE Are we starting "School Ties" today?
CHASE Elizabeth holds up her finger while she finishes reading a
The camera ANGLES to show that she is studying a picture of a topless AFRICAN TRIBESWOMAN with large breasts.
After a beat, Elizabeth looks up.
ELIZABETH Alright, today, we're starting "School Ties."
ELIZABETH Classic.
ELIZABETH You, shut off the lights.
ELIZABETH Elizabeth goes to the DVD player.
ELIZABETH There's a knock at the door and the SCHOOL SECRETARY walks in holding a box.
ELIZABETH She hands it to a confused Elizabeth.
SCHOOL SECRETARY Here it is.
SCHOOL SECRETARY Good luck.
ELIZABETH Here what is?
SCHOOL SECRETARY It's the pre-test for the state standardized test.
SCHOOL SECRETARY It was in the memo.
ELIZABETH Oh, yes.
ELIZABETH In the memo.
ELIZABETH The Secretary leaves.
ELIZABETH Elizabeth stares at the box.
ELIZABETH Tristan and.a couple kids start making farting noises with their hands.
ELIZABETH (CONT'D) Hey.
ELIZABETH (CONT'D) Zip it.
ELIZABETH (CONT'D) Zip your shit.
Alright, look, we all know these tests are gay -- Elizabeth turns to a student who COULD BE GAY.
ELIZABETH (CONT'D) Hey.
ELIZABETH (CONT'D) Elizabeth passes the box to the front of the class, where the kids dutifully take Scan-trons and test booklets.
ELIZABETH.(CONT'D) According to this memo, I'm supposed to give you forty-five minutes per section.
ELIZABETH.(CONT'D) Blah blah blah.
ELIZABETH.(CONT'D) Clear your desks, pencils out and -- begin!
ELIZABETH.(CONT'D) Twenty-five pencils hit paper in unison.
Elizabeth takes the TV and swivels it to face her desk.
She turns on the movie, turns down the volume (just a little bit) and reclines.
INT. JOHN ADAMS MIDDLE SCHOOL - CAFETERIA - DAY Chase and another popular girl strut across the cafeteria, arm in arm.
INT. JOHN ADAMS MIDDLE SCHOOL - CAFETERIA - DAY A THIRD POPULAR GIRL, saving a table, waves them over.
INT. JOHN ADAMS MIDDLE SCHOOL - CAFETERIA - DAY Chase and her friend walk right past the girl like she doesn't exist and take a seat with a bunch of other girls.
Little bitches.
TURN TO REVEAL Elizabeth and Lynn on lunch duty.
TURN TO REVEAL The girl at the table starts BAWLING.
TURN TO REVEAL Amy, also on duty, races over to console her.
ELIZABETH (CONT'D) What a phony.
LYNN Major phony.
LYNN But she also cares a lot, too.
So what's going on with your boobs?
ELIZABETH Shit.
ELIZABETH Shit is going on with my boobs.
ELIZABETH I'm never gonna get married.
ELIZABETH I'm gonna die broke.
ELIZABETH I should just blow my brains out.
ELIZABETH There he is!
ELIZABETH Scott walks down the ramp and HIGH-FIVES a bunch of kids.
ELIZABETH He gives them a big wave.
LYNN I love how his eyes sparkle when he smiles.
ELIZABETH I want to sit on his face.
SCOTT Hey, guys.
ELIZABETH You're really making a habit out of this.
SCOTT Ha, yeah.
SCOTT Actually, Sandy Pinkus in the Math department, I guess he got that stomach bug that's been going around and I got the call.
LYNN I heard he pooped himself in first period.
LYNN A kid had to walk him to the nurse.
ELIZABETH Lynn, would you mind grabbing me a milk?
ELIZABETH Elizabeth gives her a "can you get out of here?" look.
LYNN Scott, do you want anything?
SCOTT I'm good, thanks for asking.
SCOTT Lynn walks off.
ELIZABETH So, Scott -- Lynn comes back.
LYNN Sorry, what kind of milk do you want?
LYNN Skim?
LYNN Whole?
LYNN 2%?
LYNN Chocolate?
ELIZABETH I don't know.
ELIZABETH Surprise me.
LYNN Okay, I'll get you skim.
LYNN No, no, 2%.
LYNN Lynn walks off again.
ELIZABETH She's funny.
ELIZABETH Elizabeth notices Amy looking at her as she continues to console the girl.
ELIZABETH Elizabeth turns back to Scott.
ELIZABETH (CONT'D) So, Scott, I was thinking, I would love to hear about your experiences in the Peace Corps.
ELIZABETH (CONT'D) I love Haiti.
ELIZABETH (CONT'D) Maybe we could go grab a drink some night.
ELIZABETH (CONT'D) Maybe tonight.
SCOTT Isn't it Back-to-School Night?
ELIZABETH Yeah, Silly, I meant after.
SCOTT Cool!
SCOTT Let's get a group together.
ELIZABETH Yeah, definitely!
ELIZABETH Or just the two of us.
ELIZABETH Scott looks around, then lowers his voice.
SCOTT Oh.
SCOTT Um, listen, I'm really flattered.
SCOTT You're one of the nicest people I've met here.
SCOTT But...
SCOTT I'm actually seeing someone.
ELIZABETH Oh?
SCOTT Yeah, we've been keeping it quiet.
ELIZABETH Because she's ugly?
SCOTT No.
SCOTT She's beautiful.
SCOTT She's great.
SCOTT She really cares about the kids.
SCOTT It's just...
SCOTT when you're dating a co-worker...
Squirrel?
Elizabeth whips around to see Amy, who's now sharing a frozen yogurt with the formerly bawling girl.
Amy looks up, smiles and gives a thumbs up to Elizabeth and Scott, signalling that everything's okay with the girl.
Elizabeth NOTICES Amy's LARGE BREASTS straining against her blouse.
She quietly seethes.
SCOTT Anyways, thanks again for asking me out.
SCOTT I'm honored.
SCOTT And I'll take a raincheck on that group date.
SCOTT See ya!
SCOTT Scott crosses through the cafeteria.
SCOTT Lynn returns with a four cartons of milk.
LYNN Here you go.
LYNN I got you one of each.
Lynn hands them to Elizabeth, who takes them, drops them in the trash and storms off.
EXT. JOHN ADAMS MIDDLE SCHOOL - NIGHT At night, under the stars, the SCHOOL looks peaceful, serene.
INT. ELIZABETH'S CLASSROOM - NIGHT Elizabeth is up front.
INT. ELIZABETH'S CLASSROOM - NIGHT She's staring,at the PARENTS.
INT. ELIZABETH'S CLASSROOM - NIGHT They stare right back at her.
INT. ELIZABETH'S CLASSROOM - NIGHT It's awkwardly silent for a beat too long.
ELIZABETH Hi, my name's Elizabeth Halsey.
ELIZABETH Soooooo...
ELIZABETH Any questions?
ELIZABETH Sasha's Mother eagerly raises her hand.
ELIZABETH Elizabeth points to her.
SASHA'S MOTHER Hi, I'm Sasha's mother.
SASHA'S MOTHER We waved to each other at the carwash.
SASHA'S MOTHER I'm a little concerned with the importance you're placing on movies.
SASHA'S MOTHER What about the state test?
SASHA'S MOTHER Elizabeth points to her sign on the wall -- "Don't Question My Authority."
ELIZABETH That's exactly what I say to my students.
ELIZABETH Listen, I'm a good teacher.
ELIZABETH And the school hired me because I'm good at what I do.
ELIZABETH And the reason your son loves my class is because I inspire him.
ELIZABETH Movies are one tool that I use.
ELIZABETH I also use other multimedia techniques, which I'm not going to get into right now.
ELIZABETH Look, I could take you day by day through my entire syllabus, but that's not how I do things.
ELIZABETH I'm not one of these stuffy teachers who's totally by the book.
ELIZABETH I talk to the kids like they're little adults.
ELIZABETH It's about mutual respect.
ELIZABETH So that's my spiel, as the Jews say.
Help yourselves to some delicious snacks and drinks in the back.
Class dismissed.
They head to the back of the class.
ANGLE ON
A "refreshments" table.
A lonely package of OREOS rests against a PITCHER OF TAP WATER.
Elizabeth tries to sneak out the door, but is stopped by a sharply dressed PARENT.
PARENT #1 Excuse me, Ms. Halsey.
I'm Chris' dad.
From Elizabeth's reaction, she clearly has no idea who Chris is.
ELIZABETH Chris...
ELIZABETH Great kid -- and precocious.
ELIZABETH You must be so proud.
CHRIS' DAD Oh, what a relief.
CHRIS' DAD I just wish his grades would reflect it.
ELIZABETH If I know Chris, he'll get there.
CHRIS' DAD Listen, I know you have a full plate, but if you could keep an eye on Chris, my wife and I would really appreciate it.
CHRIS' DAD Chris' dad shakes her hand.
CHRIS' DAD Elizabeth opens her hand, sees a tightly folded HUNDRED DOLLAR bill.
CHRIS' DAD She looks back up at Chris' dad.
For supplies.
Or whatever.
Elizabeth stands with another set of parents.
They're eating Oreos and sipping water.
ELIZABETH You're Chase's parents?
ELIZABETH Great kid -- and precocious.
ELIZABETH You must be so proud.
ELIZABETH The parents beam.
ELIZABETH (CONT'D) A student like that would benefit so much from some extra attention.
CHASE'S MOM You think we should hire a tutor?
CHASE'S MOM I told you.
I'd be happy to do it myself.
It's just hard in a class of twenty-five.
CHASE'S MOM Oh, to be a teacher.
ELIZABETH It's just so hard, on my salary, having to pay for my supplies, my fiance cheated on me with his twin sister...
ELIZABETH and, unlike a lot of these other teachers, all I truly care about is helping your child learn.
ELIZABETH And as their personal tutor, I guarantee a full grade higher -- or your money back.
ELIZABETH Chase's mom takes out her check book.
ELIZABETH (CONT'D) Make it out to "cash."
INT. ELIZABETH'S CLASSROOM - LATER Parents are leaving the class, ad-libbing "thank.you's."
INT. ELIZABETH'S CLASSROOM - LATER Another SET OF PARENTS surreptitiously hand Elizabeth some cash.
INT. ELIZABETH'S CLASSROOM - LATER A Bohemian mother, MELODY, wearing a beret, lingers behind.
MELODY Excuse me, Ms. Halsey.
MELODY I just wanted to introduce myself.
MELODY I'm Melody.
MELODY Garrett's mom.
Nice to meet you...
Garrett's a great kid -- and precocious.
You must be so proud.
MELODY Oh, you're referring to his poetry.
MELODY Thank you.
ELIZABETH You must be so proud.
MELODY I am.
MELODY So so so so so proud.
MELODY So proud.
ELIZABETH A kid like that, if I could just give some more one on one time, he would just blossom.
MELODY I'm so happy to hear you say that.
MELODY would really benefit from that.
ELIZABETH Unfortunately, in a class of twenty- five...
MELODY Ugh.
MELODY Class sizes are ridiculous.
ELIZABETH And with the amount they pay teachers...
MELODY Thank god you love what you do.
ELIZABETH I guess what I'm getting at is, maybe you could help out by giving me a little -- you know -- somethin somethin.
ELIZABETH Elizabeth offers her hand, palm up.
ELIZABETH Melody stares back at her blankly.
ELIZABETH (CONT'D) It's just, it's really tough to teach the way that I want to teach when there's so little money.
ELIZABETH (CONT'D) I mean, look at this place.
MELODY You know what I'm going to do for you?
MELODY Melody opens her pocketbook.
MELODY Elizabeth smiles.
MELODY (CONT'D) I am going to start a letter-writing campaign to the school board, to my congressman, to the mayor -- and keep writing until you get what you deserve.
She opens her date book and writes herself a note.
MELODY (CONT'D) And I'm writing myself a reminder!
MELODY (CONT'D) Melody pulls Elizabeth into a warm hug.
MELODY (CONT'D) You are a saint.
MELODY (CONT'D) Melody exits.
MELODY (CONT'D) Elizabeth is left in the classroom by herself.
ELIZABETH So long, Crazy.
ELIZABETH As Elizabeth pulls out the CASH she just made, we hear the opening beats of COOLIO'S "GANGSTER'S PARADISE."
INT. J.A.M.S. - ADMINISTRATION BULLPEN - DAY The SONG continues.
INT. J.A.M.S. - ADMINISTRATION BULLPEN - DAY Elizabeth pokes her head in.
INT. J.A.M.S. - ADMINISTRATION BULLPEN - DAY The office is empty.
INT. J.A.M.S. - ADMINISTRATION BULLPEN - DAY She walks in, grabs the "Lost and Found" box and exits.
The SONG continues.
Elizabeth stands across from a HIPPIE-LOOKING GIRL.
The pile of "Lost and Found" clothes are laid out on the counter.
The Hippie Girl hands Elizabeth some cash.
INT. ELIZABETH'S APARTMENT - BEDROOM - NIGHT The SONG continues as Elizabeth throws more money in her "New Tits" jar and enters a new amount into her notebook.
INT. ELIZABETH'S APARTMENT - BEDROOM - NIGHT The new balance: $1473.
INT. ELIZABETH'S CLASSROOM - DAY "Gangster's Paradise" CONTINUES and we see that the class is now watching "Dangerous Minds" with Michelle Pfeiffer as a tough-as-nails teacher in an inner-city school.
The SONG continues as Amy, in her empty classroom, stands against the adjoining wall, her ear pressed to it.
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY The SONG continues.
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY The class is still watching "Dangerous Minds."
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY There's some NOISE in the hall.
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY Elizabeth PAUSES the movie, STOPPING the song.
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY She leans into the hall.
ELIZABETH Enough with the commotion!
ELIZABETH The hallway goes silent.
ELIZABETH She comes back in and UNPAUSES the movie.
ELIZABETH The SONG comes back on.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY The SONG continues as the hallway fills with excited kids, who race down the hall and talk animatedly with friends.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Elizabeth pushes through the center.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY The SONG continues.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY Elizabeth sits in her car.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY She lights a joint with the cigarette lighter and deeply inhales.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY KNOCK KNOCK!
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY The SONG abruptly ENDS.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY Elizabeth jumps.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY She turns to her window, sees Sasha, bundled in her winter coat, waving.
ELIZABETH What do you want?
ELIZABETH Sasha motions for her to roll down the window.
ELIZABETH Elizabeth doesn't.
SASHA Is that marijuana?
ELIZABETH It is.
ELIZABETH But it's medicinal.
ELIZABETH Doctor gave it to me.
ELIZABETH Not that it's any of your business.
SASHA Oh, okay.
SASHA Feel better.
My mom and I made you holiday cookies.
Here.
Sasha pulls out a tupperware container.
ELIZABETH Are those oatmeal raisin?
SASHA Sugar.
SASHA Elizabeth considers, then manually rolls down the window a crack.
SASHA She grabs the container and quickly closes her window.
SASHA Elizabeth starts eating a cookie.
ELIZABETH You have anything to drink?
ELIZABETH Sasha shakes her head.
ELIZABETH (CONT'D) Word to the wise: stop dressing like you're running for congress.
SASHA I don't want to run for congress.
SASHA I want to be president.
ELIZABETH See?
ELIZABETH That's what I'm talking about.
ELIZABETH Keep saying stuff like that, you're gonna get punched.
ELIZABETH You really want to be President or is that what your parents tell to be?
ELIZABETH Sasha shrugs.
ELIZABETH (CONT'D) You don't have to decide right now.
ELIZABETH (CONT'D) Who knows?
ELIZABETH (CONT'D) Maybe you wake up one day and decide that you love giving massages and you want to be a masseuse.
ELIZABETH (CONT'D) Salary plus tips.
ELIZABETH (CONT'D) Think about it.
SASHA If I think about it, will I get extra credit?
ELIZABETH Hopeless.
ELIZABETH Watch your feet.
Elizabeth reverses.
Sasha jumps away from the car.
Elizabeth peels out, passing the school marquee that reads, "Happy Holidays, Jammers!
See you in '09!"
Elizabeth rolls over.
It's 3:40 PM.
She yawns and gets out of bed.
QUICK CUTS.
Elizabeth opens her refrigerator.
Nothing except ketchup packets, mustard packets and soy sauce packets.
She reaches for her bong and tries lighting it.
Once.
Twice.
She shakes the lighter.
No luck.
She carries the bong to the stove, turns on the stove, and tries lighting it from there.
No luck.
ELIZABETH Seriously?
Elizabeth walks up to the door.
It's locked.
She shakes the door.
ELIZABETH Seriously?
ELIZABETH She sees a HOMELESS GUY leaning against the storefront.
ELIZABETH (CONT'D) Why's the store closed?
ELIZABETH (CONT'D) The Homeless Guy looks at her strangely.
HOMELESS GUY It's Christmas.
ELIZABETH Seriously?
ELIZABETH Elizabeth looks around.
ELIZABETH The streets are empty.
ELIZABETH Not a person in sight.
HOMELESS GUY Merry Christmas!
ELIZABETH Whatever.
ELIZABETH Hey, you got a lighter?
HOMELESS GUY I don't smoke.
HOMELESS GUY It's bad for you.
HOMELESS GUY Elizabeth walks back to her car, empty-handed.
HOMELESS GUY A MINI- VAN passes.
HOMELESS GUY Stops.
HOMELESS GUY Reverses..
HOMELESS GUY The window rolls down.
HOMELESS GUY It's Garrett and his Mom.
GARRETT Ms. Halsey!
GARRETT Hey, it's me, Garrett!
MELODY Merry Christmas, Ms. Halsey!
MELODY Having a nice Christmas?
MELODY What are you doing the rest of the day?
MELODY Going to see your family?
I'm probably going to meet up with some people.
We're having a big potluck, so...
Elizabeth-shuffles her feet.
MELODY Ms. Halsey.
MELODY Elizabeth.
MELODY Would you like to have Christmas with us?
Cozy and unpretentious.
Filled with crafts.
Elizabeth sits next to Melody and across from Garrett, who's wearing his "Gymnastics" sweatshirt, and his TWO AUNTS, both divorced.
Elizabeth tears through a plate of Christmas cuisine.
MELODY This is a real treat for Garrett.
MELODY He doesn't have a lot of friends come by the house.
ELIZABETH I find that hard to believe.
Listen, I hate to eat and run, but I've gotta head over to the shelter.
GARRETT I thought we could play board games!
A shelter.
That is so inspiring.
ELIZABETH Yeah, I love helping bums.
MELODY Oh, but you have to wait for dessert.
MELODY We have a real treat.
ELIZABETH If it's cheesecake, I'll stay.
MELODY It's even better than cheesecake!
Garrett, why don't you run and get some of your new poetry?
GARRETT Oh god, no one wants to hear it.
GARRETT Oh god, I'm so embarrassed!
MELODY Don't be shy, Marbles.
MELODY Garrett runs out of the room.
ELIZABETH If you're not really serving dessert, I'm gonna have to get going.
MELODY One poem?
MELODY If you like it, maybe you can read it to your homeless friends.
Garrett stands in front of Elizabeth and his family.
He opens his journal, clears his throat, and begins.
GARRETT This is called "The Chase," by Garrett Tiara.
XOXO /My love for you is XOXO/ Her hair is long and straight / Isn't it great?
/ About her smile / That I would walk a mile for / About her personality / That makes me see the best in me / And at night when we sleep / Our souls locked in deep / So that when we sleep / We can stop pretending / And embrace our beautiful ending.
Melody applauds.
The Aunts join in.
Elizabeth claps, then gets up to go.
Garrett shakes them all off.
ELIZABETH She sits back down.
GARRETT We'll dance our dance / We'll revel in romance perchance / One glance / One dance / Because together we can achieve...
GARRETT Ba-lance...
GARRETT Thank you.
GARRETT He closes his journal.
GARRETT Everyone applauds.
GARRETT Melody looks to Elizabeth for a reaction.
ELIZABETH Junior likes to rhyme.
MELODY Patty, Nancy, why don't you give me a hand with dessert -- give them a chance to talk about the poem.
MELODY The women exit, leaving Garrett and Elizabeth.
ELIZABETH So your poem's about that girl?
GARRETT Chase, yeah.
GARRETT You got the subtext.
ELIZABETH Can I give you some advice?
GARRETT Please.
Number one, stop writing poetry.
Two: stop reading it.
And three: don't set your sights so high.
I mean, she's really hot.
If I were you, I'd try for that chubby girl that sits up front -- the one with the teeth?
Elizabeth puts her hands to show teeth going off in different directions.
GARRETT But I like Chase.
ELIZABETH Not gonna happen.
ELIZABETH Look, I was that hot girl.
ELIZABETH Hotter, even.
ELIZABETH And I never would have gone out with a kid like you.
ELIZABETH And I'm not saying that to be mean.
ELIZABETH I'm saying it to be helpful.
GARRETT What do you know?
GARRETT You don't-even know our names.
ELIZABETH I'll tell you what I know: a kid who wears the same "Gymnastics" sweatshirt three days a week isn't getting laid until he's 26.
ELIZABETH That's what I know.
This sweatshirt was my dad's.
It's all he left when he left.
ELIZABETH Well, there's a reason he didn't pack it.
GARRETT Fuck you.
GARRETT Elizabeth pats Garrett on the shoulder.
ELIZABETH Good luck being a loser.
ELIZABETH Thank your mom for dinner.
ELIZABETH Elizabeth heads for the door.
GARRETT Happy New Year.
GARRETT Are you spending that alone, too, or do you want my mom to invite you over?
GARRETT She gives him the finger over her shoulder and leaves.
INT. ELIZABETH'S CLASSROOM - DAY The students, many tanned, many with braids in their hair from their winter vacations, silently stare at Elizabeth.
INT. ELIZABETH'S CLASSROOM - DAY She looks haggard.
INT. ELIZABETH'S CLASSROOM - DAY She pulls out a bottle of cough syrup and takes a long swig.
INT. ELIZABETH'S CLASSROOM - DAY The kids look at each other, like "what is she doing?" Elizabeth lets out a lame, fake cough.
ELIZABETH Shut up.
Elizabeth is-checking her makeup in the mirror.
Lynn enters.
Her blouse has a healthy serving of vomit on it.
LYNN Hey, welcome back.
ELIZABETH What is that, vomit?
ELIZABETH Lynn grabs some towels and blots at the stain..
LYNN Yeah, and a little blood.
LYNN The kids had too much sugar.
LYNN (CONT'D) Anyways, a bunch of us are going out tonight to see Period 5 play.
LYNN (CONT'D) Do you want to come?
ELIZABETH Ugh.
ELIZABETH No.
ELIZABETH Elizabeth heads out.
ELIZABETH Lynn, still blotting, follows her.
Elizabeth and Lynn bump into Scott.
SCOTT Hey, guys.
SCOTT Are you coming to 'In Cahoots' tonight?
SCOTT My band's doing a few songs.
SCOTT Could be fun.
ELIZABETH Um, yes!
ELIZABETH That sounds like a party.
ELIZABETH Lynn, do you want to come?
LYNN Yes.
SCOTT We'll all grab a drink!
ELIZABETH Great.
ELIZABETH I need to get drunk.
ELIZABETH I mean, not drunk drunk.
ELIZABETH But a strong buzz.
ELIZABETH Still be able to drive home.
SCOTT Now we're cooking with grease!
We hear the familiar riff of Shawn Mullin's "Lullaby."
Scott, Sandy (with his hair down), a BALDING BASS PLAYER with a yarmulke and a HEAVY-SET DRUMMER, are playing their hearts out.
This is PERIOD 5.
Amy, and a couple other teachers are front and_center, grooving to the music.
Amy sways with her eyes closed.
Everything's gonna be alright / rockabye...
Scott joins in, harmonizing.
SCOTT Rockabye, rockabye...
Bye, bye...
Bye, bye...
ANGLE ON Elizabeth and Lynn at the bar.
LYNN Aren't they terrific?
LYNN Elizabeth eye-fucks Scott.
LYNN She catches his eye and he quickly smiles before nervously turning his attention to Amy.
LYNN Elizabeth watches Amy dance in SLO M0, her BREASTS bouncing up and down.
ELIZABETH They're perfect.
LYNN You should hear some of their originals.
LYNN She turns to the bartender.
ELIZABETH Two more.
ELIZABETH You want anything?
LYNN No thanks...
LYNN You know, I was thinking that if you still need that money, you should.try and go for the bonus.
LYNN Can't hurt.
ELIZABETH What bonus?
LYNN For the state test.
LYNN (CONT'D) Whichever teacher has the highest scoring class gets a bonus.
LYNN (CONT'D) We talk about it all the time in the faculty meetings.
ELIZABETH How much?
LYNN $5700.
LYNN Could be good, right?
Let's dance!
Lynn runs out onto the dance floor and joins Amy.
Man it's a hot one / like seven inches from the midday sun...
Amy kicks her shoes off, and starts dancing.
Lynn follows suit.
Elizabeth throws back her drink and exits.
The sun is breaking.
Amy listens to NPR as she pulls into the empty parking lot.
Suddenly, she SLAMS on her brakes.
ELIZABETH'S CAR is already there.
Amy puts her car in park and gets out.
She walks over to Elizabeth's car and feels the hood.
AMY Cold.
The clicking of Amy's shoes ECHO through the empty hallway.
She stops, takes off her shoes.
She pitter-patters down the hall to Elizabeth's classroom and PEERS in.
Elizabeth is at the chalkboard, intently writing questions.
She senses something in her periphery and looks over at her window.
Nothing.
Elizabeth goes back to work.
INT. ELIZABETH'S CLASSROOM - LATER Elizabeth waits in the doorway impatiently as the kids filter in.
INT. ELIZABETH'S CLASSROOM - LATER Garrett brings up the rear, rolling his backpack into class.
Let's go, Sylvia Plath.
Garrett rolls his backpack over Elizabeth's shoe..
Elizabeth winces and glares at Garrett.
The rest of the class enters, stops, noticing WORK PACKETS on each of their desks.
Where's the TV?
Everyone, take your seats.
Shawn turns to Spencer.
SHAWN What do you think's going on?
SHAWN Spencer shrugs.
ELIZABETH Come on, come on.
ELIZABETH We have a lot to cover so sit down.
ELIZABETH The class, still confused, quickly take their seats.
ELIZABETH (CONT'D) Alright then.
ELIZABETH (CONT'D) Now.
ELIZABETH (CONT'D) Open your To'Kill A Mockingbird to page one.
ELIZABETH (CONT'D) The kids slowly take out their books.
ELIZABETH (CONT'D) We HEAR the distinct sound of twenty-five book spines cracking as they're opened for the first time.
ELIZABETH (CONT'D) Good.
ELIZABETH (CONT'D) Now, who can tell me why Jem cries when the hole in the tree is filled with cement?
ELIZABETH (CONT'D) Anyone?
GARRETT Because she's a cry baby.
GARRETT The kids chuckle.
GARRETT Chase looks back at Garrett.
Get out.
Garrett clicks up the handle on his bag and heads for the door.
ELIZABETH (CONT'D) We're here to learn.
ELIZABETH (CONT'D) Anyone else have a problem with that?
ELIZABETH (CONT'D) Good.
ELIZABETH (CONT'D) So who has the answer to my question?
ELIZABETH (CONT'D) Everyone looks down.
ELIZABETH (CONT'D) Nobody's read this book?
ELIZABETH (CONT'D) It's on the syllabus.
SASHA You never assigned it to us.
ELIZABETH Well, now I am.
ELIZABETH And we're having a quiz tomorrow.
ELIZABETH Panic.
ELIZABETH (CONT'D) On the first hundred pages.
SASHA You can't do that!
SASHA I have band and jazz band tonight!
SHAWN We haven't had homework all year!
ELIZABETH Hey!
ELIZABETH Zip your shit!
ELIZABETH We've fallen behind, and honestly, your practice tests scores sucked balls -- which was embarrassing to me both on a personal level and as an educator.
Things are about to change.
Recess is over.
INT. ELIZABETH'S APARTMENT - NIGHT Elizabeth reads To Kill a mockingbird and highlights like crazy.
INT. ELIZABETH'S APARTMENT - NIGHT She stops, takes a hit from her bong, and continues.
INT. ELIZABETH'S APARTMENT - NIGHT Her roommate, Kirk, enters through the front door, sipping from a Big Gulp.
ELIZABETH Did you get my Cool Ranch?
ELIZABETH He tosses her a bag of chips.
KIRK You owe me two bucks..
KIRK Kirk walks into his room and closes the door.
INT. ELIZABETH'S CLASSROOM - DAY Elizabeth paces.
INT. ELIZABETH'S CLASSROOM - DAY She has a book of stickers in her hand.
ELIZABETH Okay, now, what is the significance of the Mockingbird in the novel?
ELIZABETH What was Harper Lee trying to tell us?
ELIZABETH No one raises their hand.
Come on, you guys know this.
This is as close to real teaching as we've seen from Elizabeth.
Sasha raises her hand.
We see that she already has two gold star stickers on her forehead.
ELIZABETH (CONT'D) Anyone else?
Chase raises her hand.
CHASE It's a symbol for, um, equality?
CHASE Elizabeth puts a sticker on Chase's forehead.
ELIZABETH Okay, good.
ELIZABETH Can anyone add to what that girl said?
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY The desks have been arranged into a makeshift courtroom.
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY Spencer presides as the judge.
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY Chase and Shawn are the prosecutors.
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY Garrett is dressed like Boo Radley.
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY Tristan, the bully, addresses the rest of the class -- the "jury."
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY Everyone is clearly into the exercise.
INT. ELIZABETH'S CLASSROOM - ANOTHER DAY REVEAL Principal Snur, clad in a dolphin tie, watching from the back of the class.
TRISTAN Ladies and Gentlemen of the jury, you've heard the "facts," but come on, you know me.
TRISTAN I'm Atticus Finch, baby!
TRISTAN The class laughs.
Come on, seriously.
You're gonna side with Chase and Shawn over me?
ELIZABETH Use examples from the book.
SPENCER It doesn't matter what race the defendant is.
SPENCER You've just gotta look at the facts-.
SPENCER Elizabeth nods in agreement.
SPENCER The bell RINGS.
ELIZABETH Good work today.
ELIZABETH And don't forget to leave your closing statements on my desk.
The students all dutifully drop off their papers, placing them in a neat stack next to other ungraded PAPERS.
Principal Snur exits, giving Elizabeth a thumbs up.
Love the tie!
INT. TEACHER'S LOUNGE - DAY Scott and Amy share a bag of trail mix.
INT. TEACHER'S LOUNGE - DAY Sandy reads a Jerry Garcia biography.
INT. TEACHER'S LOUNGE - DAY Lynn grades.
INT. TEACHER'S LOUNGE - DAY papers.
AMY So, you know how I hate to gossip, but I heard that one of the custodians walked in on Omar -- you know, that Arabic boy -- giving...
Oral sex to Matty Feldstein after swim practice in the boy's locker room.
SANDY It just starts younger and younger.
It's nice to finally see the Jews and the Arabs getting along.
Elizabeth enters.
Scott looks up and smiles.
SCOTT Hey, Ms. Halsey.
AMY Your shirt's mis-buttoned.
AMY Her shirt's mis-buttoned.
Oh shit.
Hold on.
Elizabeth turns away from them and starts rebuttoning.
Sandy tries to sneak a peek.
Scott shoots him a dirty look.
Sandy gives an innocent shrug.
ELIZABETH (CONT'D) I've just been such a mess the last few days.
ELIZABETH (CONT'D) Working myself to the bone.
AMY Yeah, it's been quite a change.
Well, I think it's great.
Some teachers just sail by, doing the bare minimum.
It's good to know there are still some actual educators out there.
Elizabeth smiles for Scott, like, "You get me."
ELIZABETH Well, I should get going.
ELIZABETH Nice seeing all of you.
ELIZABETH Amy and Elizabeth smile thinly at one another.
ELIZABETH Elizabeth squeezes Scott's shoulder as she exits.
ELIZABETH Amy notices.
What a good egg.
Amy and Sasha sit in the empty auditorium.
Sasha is dressed as LITTLE ORPHAN ANNIE, including the RED WIG."
Student STAGEHANDS construct a set.
AMY What else, Sasha?
SASHA I don't know.
SASHA I told you about the car wash money.
AMY I can't prove that.
AMY What else?
SASHA I think I've told you everything.
AMY And no more movies in class?
SASHA No, we're actually learning.
SASHA Did you know that Animal Farm isn't even really about animals --
Animal Farm?!
That's not even on the syllabus!
AMY (CONT'D) I know you're forgetting something.
AMY (CONT'D) Do you want extra credit on your diorama or not?
SASHA I want it!
SASHA Let me think...
SASHA Oh there was...
SASHA never mind.
AMY What?
SASHA It was okay.
SASHA It was medicinal.
AMY Wait.
AMY Hold your horses.
AMY What was medicinal?
SASHA Ms. Halsey was smoking in her car, but she told me her doctor prescribed it.
Holy guacamole.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY SLO MO.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Two scary-looking GERMAN SHEPHERDS, their teeth bared, pull two POLICE OFFICERS down the hall.
POLICE OFFICER #1 Come on, Axel, what do you smell, boy?
POLICE OFFICER #1 The Police Officers continue the search.
POLICE OFFICER #1 They lead the dogs up against lockers and knock on class doors.
POLICE OFFICER #1 Amy and Principal Snur watch from the end of the hallway.
You better be right about this -- or I'm going to be getting a lot of panicked calls from parents.
AMY Trust me, Wally.
AMY My kids in D.A.R.E.
AMY tell me everything and there are drugs in this school.
AMY And not just the students.
AMY Some of the female teachers.
The class is split up into mini-sections of four desks each.
The students are quietly and dutifully working.
As Elizabeth reads papers and grades them, we HEAR the various student's voices.
Atticus Finch is a good lawer because he's a good person whose a layer.
Elizabeth looks at Tristan.
As she writes, we HEAR --
ELIZABETH (V.0.) Proofread.
QUICK CUTS.
Elizabeth grades another paper.
She's growing more agitated and is now feverishly writing.
ELIZABETH (V.0.) (CONT'D) Wrong!!!
ELIZABETH (V.0.) (CONT'D) Is this English?
ELIZABETH (V.0.) (CONT'D) Are you fucking kidding me?
ELIZABETH (V.0.) (CONT'D) Elizabeth crosses out with one line, so it's clearly visible beneath.
ELIZABETH (V.0.) (CONT'D) From out in the hallway, we HEAR the loud, aggressive BARKING of the DOGS.
ELIZABETH (V.0.) (CONT'D) Tristan runs to the door and peeks out.
SPENCER Whoa.
SPENCER Drug dogs.
SPENCER Cool.
ELIZABETH Sit down.
ELIZABETH Elizabeth races to the window.
The Police officers and the dogs enter the classroom next to hers.
Elizabeth glances back at her pocketbook.
ELIZABETH (CONT'D) Balls.
ELIZABETH (CONT'D) She races back to her desk.
Keep reading.
Elizabeth takes her seat and leans under her desk, obscuring her from her class.
She opens her pocketbook and pulls out a CIGARETTE CASE.
She pops it open and we SEE three neatly rolled JOINTS.
Without hesitation, Elizabeth POPS the first one into her mouth and starts chewing vigorously.
As she.
makes her way through the second and then the third, the chewing becomes slower and the BARKING becomes louder and louder.
Elizabeth starts CHOKING as the door opens and the Police Officer and the German Shepherd enter, followed by Principal Snur and Amy.
PRINCIPAL SNUR Elizabeth, sorry to bother you.
PRINCIPAL SNUR This will only take a second.
PRINCIPAL SNUR Elizabeth,.
PRINCIPAL SNUR still choking, digs into her purse.
PRINCIPAL SNUR She grabs her cough syrup and takes a huge swig.
PRINCIPAL SNUR Elizabeth wipes her mouth, breathes normally.
ELIZABETH Sorry.
ELIZABETH I had something caught in my throat.
ELIZABETH The German Shepherd continues barking.
POLICE OFFICER #1 What is it, Axel?
POLICE OFFICER #1 Where is it, boy?
POLICE OFFICER #1 The Dog comes bounding at Elizabeth.
POLICE OFFICER #1 Elizabeth's eyes go wide.
POLICE OFFICER #1 Amy licks her lips.
POLICE OFFICER #1 The Dog sideswipes Elizabeth, almost knocking her over, and jumps onto Garrett.
GARRETT Ahhh!!!
GARRETT The'Police Officer starts rummaging through Garrett's bag and pulls out an opened bag of CORN CHIPS.
POLICE OFFICER #1 All clear.
POLICE OFFICER #1 Dog must've responded to these.
POLICE OFFICER #1 Happens.
POLICE OFFICER #1 Elizabeth glares at Amy -- "I know you were behind this."
POLICE OFFICER #1 Amy glares back.
POLICE OFFICER #1 Principal Snur looks at Amy and shakes his head.
AMY Even though that wasn't drugs, junk food is still contraband.
AMY That's detention, Buster.
PRINCIPAL SNUR Enough, Amy.
PRINCIPAL SNUR I think it's time we call off this witch-hunt.
ELIZABETH Thank you, Principal Snur.
ELIZABETH Now if you'll excuse me, my class has a state test to prepare for.
ELIZABETH Principal Snur, Amy and the Police Officer exit.
ELIZABETH Elizabeth slumps down into her chair, and all at once, the combination of WEED and COUGH SYRUP HITS HER.
ELIZABETH (CONT'D) Whoa.
CHASE Are you okay, Ms. Halsey?
CHASE Elizabeth takes a long beat before answering.
ELIZABETH Class dismissed.
SASHA But the bell didn't ring.
ELIZABETH Get out of my face.
ELIZABETH And leave the corn chips.
ELIZABETH The class uncertainly gathers their things and heads out.
ELIZABETH From outside Elizabeth's window, we SEE the SCHOOL BUSSES idling curbside.
ELIZABETH Elizabeth stares at the papers she still needs to grade.
ELIZABETH The papers stare back at her.
ELIZABETH (CONT'D) But first, a nap.
INT. ELIZABETH'S CLASSROOM - NIGHT Elizabeth is asleep at her desk.
INT. ELIZABETH'S CLASSROOM - NIGHT She wakes with a jolt.
INT. ELIZABETH'S CLASSROOM - NIGHT A paper is stuck to her face.
INT. ELIZABETH'S CLASSROOM - NIGHT She looks again at the stack of work, then at the pile of things she's already corrected.
INT. ELIZABETH'S CLASSROOM - NIGHT There's FOUR.
ELIZABETH Balls!
ELIZABETH She knocks the stack of ungraded papers to the ground.
ELIZABETH After a beat, she collects herself, goes to pick the, papers off the floor.
ELIZABETH As she starts tossing them into the trash, something catches her eye: a PRACTICE TEST
MANUAL.
And in the corner, an address:
Peoria Il, 61602
ELIZABETH (CONT'D) Huh.
ELIZABETH (CONT'D) Elizabeth tears off the corner and pockets it.
Hey, it's Elizabeth Halsey...
Elizabeth is driving down the highway and smoking a joint.
ELIZABETH (V.0.) Unfortunately, I can't make it in today.
ELIZABETH (V.0.) My grandmother took a turn for the worse and it looks like she's dead.
INT. ELIZABETH'S CLASSROOM - DAY The kids are laughing and engaged.
INT. ELIZABETH'S CLASSROOM - DAY TURN TO REVEAL SCOTT, dressed in overalls and a straw hat with a piece of hay in his mouth, animatedly teaching.
INT. ELIZABETH'S CLASSROOM - DAY He's holding a copy of "The Adventures of Tom Sawyer."
ELIZABETH (V.0.) Yeah.
ELIZABETH (V.0.) So I'm off to the funeral.
ELIZABETH (V.0.) Wish me luck.
Elizabeth knocks on the door.
A buff, shirtless guy in a backwards hat opens it.
He likes what he sees.
FRAT GUY Hi there.
ELIZABETH Is Tucker here?
Yeah, hold on.
T-baaaaag!
Someone's here.
So you coming to our "CEOs and Corporate Ho's" party tonight?
Elizabeth just stares at the Frat Guy.
He turns away.
Tucker, dressed identically to the Frat Guy but twenty pounds overweight, hustles down the stairs.
He has a tattoo of intertwined teabags around his bicep.
Tucker sits on his bed.
Elizabeth leans against a desk, unwilling to sit down on anything in his disgusting room.
BOB MARLEY plays softly.
TUCKER Do you ever talk to my brother?
ELIZABETH No.
ELIZABETH He dumped me, remember?
TUCKER You and my brother always had the histrionics.
So, do you want to come to our party tonight?
"CEOs and Corporate Ho's?" We're kinda light on Ho's.
ELIZABETH Like I told "Frat Guy #1," I'm not interested.
TUCKER Then what's up?
ELIZABETH I need some date rape drugs.
TUCKER Two things.
TUCKER Number one: who do you think I am?
TUCKER Yeah, I like to party and yeah, I'm in an awesome frat, but that really hurts.
TUCKER And two: they're not "date rape" drugs.
TUCKER It's called GHB -- and it's for weightlifting.
TUCKER It helps build mass, okay?
TUCKER Why do you even want it?
For lifting.
I have money and I'm in a rush.
She takes out a wad of cash.
TUCKER That's all you needed to say.
TUCKER No need to get all histrionic on me.
TUCKER Tucker walks over to a chest, opens it, and takes out a small lockbox.
TUCKER He unlocks it and takes out a small bottle containing a clear liquid.
TUCKER (CONT'D) One capful makes you feel really good.
TUCKER (CONT'D) Two capfuls will knock her out for a couple hours.
TUCKER (CONT'D) You don't want to take any more than two.
TUCKER (CONT'D) Elizabeth hands him some cash.
TUCKER (CONT'D) He hands her the jar and then gives her a big, warm hug.
TUCKER (CONT'D) Listen, I know you and my brother aren't together anymore, but I still think of you as a sister, okay?
ELIZABETH Get your hand off my ass.
TUCKER Sorry, didn't even know I put it down there.
TUCKER Good luck with your lifting.
As Elizabeth drives, we HEAR a phone RINGING.
WOMAN'S VOICE I.S.A.T.
WOMAN'S VOICE How can I direct your call?
ELIZABETH Hi, my name is Marjorie Goodman and I'm calling from the Chicago Tribune.
ELIZABETH Who could I speak to regarding allegations of racial bias on your standardized tests?
ELIZABETH A beat.
WOMAN'S VOICE Please hold.
A portly, unkempt man in a cheap suit, CARL HALABI, nervously walks through the hotel bar.
He sees the back of a WOMAN with a RED PERM.
CARL Marjorie?
CARL "Marjorie" turns and we SEE that it's actually ELIZABETH, wearing the "Little Orphan Annie" wig.
CARL She's sipping a cocktail.
ELIZABETH You must be Carl.
ELIZABETH His face lights up, excited to be in the company of such an attractive woman.
ELIZABETH Elizabeth stands and extends her hand.
ELIZABETH Carl notices Elizabeth's very short skirt.
ELIZABETH (CONT'D) Thanks for meeting me on such short notice.
ELIZABETH (CONT'D) Elizabeth motions for him to sit down.
You find the place alright?
Good drive?
ELIZABETH Great drive.
ELIZABETH I love downstate Illinois.
CARL First time to Peoria?
ELIZABETH Hmm mmm.
CARL A lot of people don't know this, but it's the largest city on the Illinois River.
ELIZABETH Wow.
ELIZABETH I did not know that.
CARL Yup yup.
CARL And it was actually founded before Chicago.
ELIZABETH Hello, Jeopardy!
ELIZABETH Have you ever auditioned?
CARL No.
CARL I should, I should.
CARL Definitely thought about it.
ELIZABETH Listen, I'd love to sit here and chat with you all night.
CARL Yeah...
ELIZABETH But I'm sure you're a very busy man, so I'll get right down to it.
I've spoken to various, um, black citizens who are alleging that your tests are biased towards white people and Orientals.
CARL You can't use my name, okay?
ELIZABETH No problem.
CARL Like I told you on the phone, every couple of years, we get calls from all over the state with these cockamamie charges.
CARL You should hear what they call me.
CARL And I'm not a racist.
CARL I voted for Obama.
CARL That, you can quote me on.
ELIZABETH Oh, right.
ELIZABETH Elizabeth takes out a notebook and pen and starts jotting down notes.
CARL Look, Marjorie, I know my tests aren't perfect.
CARL But what's the alternative?
CARL I'm all for free thinking and creativity, but how do you formulate an education budget without hard numbers from one of my tests?
ELIZABETH You don't need to convince me.
ELIZABETH But you know what would help, Carl?
ELIZABETH For me to see one of this year's tests.
CARL No problem at all.
CARL Elizabeth lights up.
CARL (CONT'D) I'll send you one the day after the schools administer them.
ELIZABETH I'd really love to see it sooner.
ELIZABETH I'm on a bit of a deadline.
CARL I wish I could, but unfortunately, you need one of these bad boys.
CARL Carl holds up a lanyard with a STATE ID CARD and some keys attached.
ELIZABETH Ooh, you look like you're CIA.
ELIZABETH Listen, I totally get it.
ELIZABETH Enough business for one night.
I'm gonna have another drink before I hit the road.
What's your poison?
CARL My poison is the white devil.
CARL Wine.
CARL White wine.
ELIZABETH Fantastic.
ELIZABETH One white wine, one tequila sunrise, and two shots of tequila.
Carl is a little tipsy and slurring his words.
Elizabeth seems to be fine.
CARL You know, Marjorie, this is the best night I've had in a longtime.
ELIZABETH Well, that makes two of us.
ELIZABETH Elizabeth gives Carl "fuck me" eyes.
ELIZABETH He nervously sips his drink.
ELIZABETH (CONT'D) What turns you on, Carl?
CARL Everything.
ELIZABETH You know what turns me on, Carl?
ELIZABETH He giggles nervously.
Sex in an office.
Getting fucked really, really hard against a wooden desk.
Mine's metal.
ELIZABETH Even better.
Carl flips on the fluorescent lights and they flicker on, like dominoes across the ceiling.
They enter his office and Carl awkwardly leans against the metal desk.
CARL So this is the desk.
ELIZABETH Do you have anything to drink?
ELIZABETH Carl goes to a mini-fridge and pulls out an already opened bottle of white wine.
ELIZABETH (CONT'D) White wine in the office.
ELIZABETH (CONT'D) You're a bad boy.
ELIZABETH (CONT'D) Carl pours a glass.
ELIZABETH (CONT'D) Elizabeth swigs from the bottle.
ELIZABETH (CONT'D) Do you have any music?
CARL Um...
CARL I could put on some internet radio.
CARL Carl goes to fiddle with his computer.
CARL Elizabeth quickly reaches into her purse and pulls out the bottle of GHB.
CARL She pours a little into Carl's wine.
CARL And then a little bit more.
CARL As he turns around, she hands him the glass.
ELIZABETH A toast.
ELIZABETH To new friends.
CARL To new lovers.
CARL CLINK.
CARL Carl downs his glass.
I'm gonna take off my shoes.
Is that okay?
ELIZABETH Whatever, man.
ELIZABETH I'm gonna hit the lady's room.
CARL K, first door on your right.
CARL Don't be long.
CARL Carl starts carefully clearing everything off of his desk.
Elizabeth waits in the bathroom.
Yawns.
Checks her watch.
She walks back in.
Carl looks woozy.
The only thing keeping him from passing out is the prospect of seeing Elizabeth naked.
I wanna fug ya agains dis desk.
ELIZABETH Easy, Cowboy.
ELIZABETH Carl stumbles towards her.
ELIZABETH Elizabeth deftly moves around the desk and exits into the bullpen.
CARL Marblorie!
ELIZABETH Carl, I'm gonna need you to pass the fuck out.
ELIZABETH Carl smiles as he feebly chases after her.
ELIZABETH He.
ELIZABETH stops at the photocopier, steadies himself momentarily and then passes out, STILL STANDING.
ELIZABETH Elizabeth grabs the lanyard from Carl's neck and heads back into his office.
ELIZABETH She goes over to the filing cabinets, unlocks it with one of the keys, and starts rifling.
ELIZABETH She pulls out a folder.
ELIZABETH (CONT'D) And bingo was his name-o.
ELIZABETH (CONT'D) She walks over to the photocopier and pushes Carl over.
ELIZABETH (CONT'D) He collapses on the ground -- out cold.
ELIZABETH (CONT'D) She copies the test and puts it back and grabs a stack of scantrons from a shelf.
ELIZABETH (CONT'D) She takes a post-it, scribbles something and sticks it to
his forehead.
As Elizabeth exits, the camera PUSHES IN: "You were AMAZING.
Love, Marjorie."
INT. ELIZABETH'S CLASSROOM - MORNING Elizabeth stares at the clock.
INT. ELIZABETH'S CLASSROOM - MORNING 8:59...
INT. ELIZABETH'S CLASSROOM - MORNING 8:59.
ELIZABETH Okay, go.
ELIZABETH The students open their test books and start.
ELIZABETH Twenty- five pencils hit paper in unison.
INT. ELIZABETH'S CLASSROOM - LATER Elizabeth stares at the clock.
INT. ELIZABETH'S CLASSROOM - LATER 10:59...
INT. ELIZABETH'S CLASSROOM - LATER 10:59.
ELIZABETH Okay, pencils down.
ELIZABETH A couple of groans.
ELIZABETH A couple of frantic moves to fill in more scantron bubbles.
ELIZABETH (CONT'D) Come on, come on.
ELIZABETH (CONT'D) It doesn't even matter.
ELIZABETH (CONT'D) Bring your tests up.
ELIZABETH (CONT'D) The students dutifully place their tests into a neat stack on the corner of Elizabeth's desk and exit.
ELIZABETH (CONT'D) Elizabeth waits for all the kids to leave and then slides all of the exams into the trash.
ELIZABETH (CONT'D) She pulls out a match and lights the exams on fire.
ELIZABETH (CONT'D) She then reaches into her bag and pulls out a new stack of completed exams.
ELIZABETH (CONT'D) She places the new exams into an official-looking folder and exits.
Principal Snur is on stage.
All the teachers sit in the first few rows.
Amy stands at her seat.
AMY If anyone has any information regarding the whereabouts of the missing "Annie" wig, please let me know ASAP.
AMY Because if that wig isn't found, you can bet your bottom dollar the "sun will not come out tomorrow."
AMY Back to you, Wally.
AMY Amy sits.
AMY Principal Snur addresses the teachers.
PRINCIPAL SNUR Thanks, Amy.
PRINCIPAL SNUR Um, okay, I'm sure everyone wants to go home, so I'll be quick.
Fourscore and seven years ago...
Scattered laughter.
Elizabeth rolls her eyes.
PRINCIPAL SNUR So I have here the results of the state exam -- and I'm happy to announce that John Adams Middle School had the fifth highest scores in the state.
PRINCIPAL SNUR The Teachers applaud.
PRINCIPAL SNUR (CONT'D) And I want to single out one of our own, who showed that with hard work and dedication, one person can make a difference.
PRINCIPAL SNUR (CONT'D) She makes me proud to be her boss and she's now $5700 richer.
PRINCIPAL SNUR (CONT'D) With the highest scores in the county -- yes, you heard me right, in the county ---I want everyone to please give a hand to --
AMY Oh boy, third year in a row.
AMY This is starting to get embarrassing.
PRINCIPAL SNUR Elizabeth Halsey!
PRINCIPAL SNUR Elizabeth leans over to Amy, who's sitting beside her.
ELIZABETH This is unexpected.
ELIZABETH All of the color drains from Amy's face as Elizabeth stands and waves at the crowd.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Teachers are exiting the auditorium.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY Scott catches up to Elizabeth, who's marvelling at the bonus check.
SCOTT Hey, if it isn't Professor Smartypants.
SCOTT Scott playfully punches her shoulder.
SCOTT Elizabeth playfully punches him back.
Better not mess with me.
I'm a lot stronger than I look.
So what are you gonna do with your new- found riches?
ELIZABETH Something big.
ELIZABETH Maybe two big things.
ELIZABETH Amy walks up and gives Elizabeth a big, fake hug.
AMY Hey!
AMY Ism so proud of you.
AMY If someone told me at the beginning of the year that you -- you!
AMY -- would get the bonus, I would've said to whomever it was, 'you must be joshing me.' And now, here we are.
AMY Here we are.
SCOTT We should go out and celebrate.
SCOTT Your treat?
AMY What a good, fun idea.
AMY Unfortunately, Scott and I have to go over the itinerary for the D.C. trip.
AMY We're the chaperones.
AMY We're going together.
AMY We're dating, so it'll also be romantic.
AMY You're not dating anyone now, right?
ELIZABETH I've got my eye on someone, but he's dating a major cunt.
ELIZABETH Pardon my French.
SCOTT No, she sounds terrible.
ELIZABETH She is.
AMY Well then.
AMY Scott, we should skedaddle.
AMY Those itineraries won't schedule themselves.
AMY Amy and Scott head off.
AMY Scott turns around.
SCOTT Rain check on those drinks.
You can bet on it.
INT. DR. VOGEL'S OFFICE - RECEPTION AREA - DAY Danni, the receptionist, uncrumples a BALL OF CRUMPLED CASH and counts it.
INT. DR. VOGEL'S OFFICE - RECEPTION AREA - DAY Elizabeth taps her fingers impatiently.
DANNI Almost done.
DANNI We don't normally deal with cash here.
DANNI At the doctor's office.
DANNI Elizabeth slides the bonus check across the desk.
ELIZABETH And this is endorsed.
ELIZABETH And the rest you can put on these.
ELIZABETH Elizabeth slides four credit cards across the desk.
ELIZABETH The MIDDLE-AGED DOCTOR from earlier walks by.
And when would you like to come in?
Hi.
He goes into his office.
Elizabeth turns back to Danni.
DANNI And when would you like to come in?
ELIZABETH Today.
ELIZABETH Tomorrow.
ELIZABETH As soon as possible.
ELIZABETH Danni checks her calendar.
DANNI A week from tomorrow, then?
ELIZABETH Book it.
ELIZABETH Danni slides Elizabeth a packet of literature.
DANNI We have a 48 hour cancellation policy.
DANNI Anything after that, you'll be charged 50% the cost of the surgery -- unless there are extenuating circumstances.
ELIZABETH I wouldn't miss it for the world.
ELIZABETH Elizabeth pulls her shirt away from her body and looks down at her breasts.
ELIZABETH (CONT'D) So long, suckers.
The lot is empty except for Elizabeth's car.
Elizabeth enters and pulls latex gloves from her bag.
She snaps them on.
She takes a seat at Amy's desk and pulls an apple from her bag.
Then she pulls out POISON IVY.
She rubs the apple with the poison ivy leaves and then carefully places it in the center of the desk.
Elizabeth smiles.
INT. AMY'S CLASSROOM - LATER Amy's class is seated.
INT. AMY'S CLASSROOM - LATER Amy enters and heads for her desk.
INT. AMY'S CLASSROOM - LATER She notices the apple and smiles at her class, touched.
INT. AMY'S CLASSROOM - LATER Thank you.
INT. AMY'S CLASSROOM - LATER The class stares back at her blankly.
AMY (CONT'D) Who did this?
AMY (CONT'D) No response from the class.
AMY (CONT'D) Oh come on.
AMY (CONT'D) Nobody wants an extra sticker on their all-star board?
AMY (CONT'D) Amy presses the apple to her ear.
AMY (CONT'D) Who brought you to me?
AMY (CONT'D) Amy places the apple up to her ear.
What's that, Mr. Apple?
You want me to take a bite?
Alrighty-roo.
Amy takes a bite of the apple and then addresses the class.
AMY (CONT'D) Enough horsin' around, let's get started.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY A LUXURY BUS idles curbside.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY Parents see off their kids.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY Scott and Elizabeth are checking kids in.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY Principal Snur walks up.
PRINCIPAL SNUR All set?
SCOTT I think we're good.
PRINCIPAL SNUR Elizabeth, thanks again for hopping in last minute.
PRINCIPAL SNUR You really saved us.
ELIZABETH Is Amy going to be okay?
PRINCIPAL SNUR She'll be fine.
PRINCIPAL SNUR But to be honest, I think she was scaring some of the kids.
ELIZABETH I bet, I bet.
ELIZABETH Well, let her know she's in my thoughts.
ANGLE ON Amy watching from outside her car.
ANGLE ON One side of her face is completely blistered, scaly and red from the POISON IVY.
ANGLE ON The kids have every reason to be scared by her.
ANGLE ON She gets into her car and slams the door.
AMY Fudge!
AMY Fudge!
AMY Fudge!
AMY Fuuuuuck--dge!
Kids sing BUS SONGS.
Elizabeth and Scott sit up front.
Hey, Sasha!
Hey, Sasha!
SASHA I think I hear it again!
KIDS You're wanted on the telephone!
If it's not Chase, then I'm not home!
Chase rolls her eyes.
Up front, Scott and Elizabeth sit next to one another and share ipod buds.
ELIZABETH You guys are amazing.
ELIZABETH Period 5 is definitely going to make it.
ELIZABETH Scott smiles wide.
ELIZABETH Garrett walks up the aisle.
ELIZABETH He looks at Elizabeth, then turns to Scott.
GARRETT Mr. Delacourte, do you think we could go to the poetry museum?
SCOTT Oh, um, I don't know, Champ, um -- Scott looks to Elizabeth, like "please help."
ELIZABETH Oh, honey, I bet everyone would just love to walk around and look at all the poetry on the walls, but unfortunately, the itinerary's really tight.
GARRETT Why are you talking like that?
ELIZABETH Just go sit down, sweetie.
ELIZABETH Garrett gives her an annoyed look and then heads back to his seat.
ELIZABETH Scott smiles at Elizabeth.
SCOTT Wow, you are such a natural.
ELIZABETH When you love what you do, it comes easy.
A splotchy-faced Amy trudges down the hallway.
She passes Elizabeth's room, stops, walks back to the door and peers in.
She looks down the hallway -- it's empty.
Amy rifles through Elizabeth's desk.
She opens the top drawer.
Just pens and paper.
She tries the bottom drawer.
Locked.
Shishkebabs!
Amy drags ELIZABETH'S DESK across the hallway into her room.
It's a slow, difficult and loud process.
Amy, sweating, now drags HER OWN DESK across the.hallway into Elizabeth's room.
She stops to catch her breath.
Amy watches as the MAINTENANCE GUY sorts through his keys and tries to unlocks the desk.
AMY I never lose my keys!
MAINTENANCE GUY What's wrong with your face?
AMY What's wrong with your face?!?!
MAINTENANCE GUY Just making conversation.
MAINTENANCE GUY He finds the right key and opens the desk.
All set.
AMY Super!
AMY Thanks a bunch, Amos!
AMY The Maintenance Man exits.
AMY Amy immediately opens the desk and rummages through it.
AMY She pulls out the "Annie" wig.
AMY (CONT'D) Busted.
AMY (CONT'D) She pulls out a test booklet.
AMY (CONT'D) There's a piece ripped out from the front page.
AMY (CONT'D) Amy's eyes narrow.
AMY (CONT'D) She runs to the floor, where she has neat stacks of what used to be in her desk.
AMY (CONT'D) She finds her test booklet and compares the two, clocking the I.S.A.T. address.
AMY (CONT'D) Looks like somebody's in big, big trouble.
EXT. WASHINGTON, D.C. - DAY To establish.
Elizabeth and Scott stand with the kids in the lobby area.
SCOTT Alright, guys, count-off.
SCOTT The students begin their count-off.
He bumps knuckles with his friend.
As the students continue counting off, we
D.C.
Montage: --Elizabeth and Scott walk with the kids through ARLINGTON NATIONAL CEMETERY.
Elizabeth snaps her gum.
--Elizabeth, Scott and the kids follow a TOUR GUIDE through the WHITE HOUSE.
Elizabeth takes the gum from her mouth and looks for a place to toss it.
She doesn't see a trash can and quickly sticks it to the bottom of an antique table.
--Chase has Elizabeth take a "Charlie's Angels" posed picture of her and her minions.
Elizabeth takes the picture before they're fully posed and hands the camera back.
Amy, her face still covered in the rash, sits across from Carl Halabi, the administrator that Elizabeth roofied.
Carl is staring at a photo of Elizabeth.
CARL She changed her hair.
CARL Is Marjorie in some kind of trouble?
AMY I think you're the one that might be in some kind of trouble!
AMY Did you or did you not give her a copy of the state test?
CARL What?!
CARL No!
All I did was give her a couple of quotes ,for her article and that's it.
AMY What article?
CARL For the Tribune.
CARL She's a reporter there.
CARL Right?
CARL Amy's eyes go wide.
Amy's car ZOOMS past the camera.
Amy's drives, her hands at 10 and 2.
CLOSE ON the speedometer as the needle hovers between 55 and 56 mph.
The students take pictures.
Garrett walks up to chase.
GARRETT Hey, you want me to take your picture?
CHASE No.
GARRETT Alright, well let me know.
GARRETT I've got my camera and my battery's fully charged.
GARRETT She turns away.
Awesome.
.Scott, who stares up at the memorial and looks choked up.
Elizabeth walks up behind him eating a fruit roll-up.
Fruit roll-up?
I'm so conflicted about this man.
Did you know that he had slaves?
Elizabeth tries to dislodge a piece of the fruit roll-up from the back of her mouth with her tongue.
ELIZABETH Yeah, everyone knows that.
SCOTT I just hate slavery so, so much.
SCOTT An unquestionable evil.
SCOTT I hate it.
SCOTT Elizabeth continues struggling with the fruit.
ELIZABETH Slavery's the worst.
SCOTT If I could go back in time and undo slavery, I would.
SCOTT Elizabeth gives him a sideways glance, like "no shit."
ELIZABETH You really hate slavery, huh?
SCOTT I hate it.
SCOTT Elizabeth finally dislodges the chunk of fruit roll-up.
ELIZABETH Got it.
SCOTT You get it.
SCOTT Scott squeezes Elizabeth's shoulder.
SCOTT (CONT'D) Thanks for listening.
ELIZABETH Hey, I want you to know you can talk to me about anything.
ELIZABETH Slavery, the Holocaust, relationships.
ELIZABETH Scott smiles.
ELIZABETH Elizabeth smiles.
ELIZABETH They lock eyes -- a moment.
Principal Snur squeezes a dolphin-shaped stress ball that chirps like a dolphin with every squeeze.
Amy sits across from him, trying to contain her glee.
PRINCIPAL SNUR Test-tampering.
PRINCIPAL SNUR Here?
PRINCIPAL SNUR At J.A.M.S.?
AMY And like I said, she stole the wig.
AMY I think we're dealing with a criminal master-mind.
Sorry to be the bearer of bad news, Wally.
You know how much we all like her.
PRINCIPAL SNUR I know.
PRINCIPAL SNUR It's a tragedy.
PRINCIPAL SNUR But Amy, let's keep this between us.
PRINCIPAL SNUR The last thing we need is a scandal on our hands.
AMY You betcha.
AMY You know what scares me the most?
AMY This is just what we know.
AMY This could be the tip of the iceberg.
AMY Who knows what else she's capable of?
The CAMERA is tight on a hotel room door.
The faint thumping of hotel sex can be heard.
Elizabeth and Scott are dry-humping, FULLY CLOTHED except for their shoes and socks.
SCOTT Oh my gosh, your body feels so good.
ELIZABETH Harder, harder.
ELIZABETH Elizabeth tries pulling off her shirt.
ELIZABETH Scott pulls it back down.
SCOTT Oh my gosh, I'm dry-humping the shit out of you.
ELIZABETH Erg.
ELIZABETH Dry fuck the fuck out of me.
SCOTT Oh my gosh, I'm so close...
SCOTT I'm...
SCOTT pfft.
SCOTT Ugh.
SCOTT Scott rolls off of Elizabeth and exhales deeply.
SCOTT There's a wet spot on his jeans.
SCOTT (CONT'D) That was a mistake.
ELIZABETH That was fast.
SCOTT I know, I'm sorry.
SCOTT But this isn't me.
SCOTT And I.
SCOTT know this isn't you.
SCOTT I'm in love with Amy.
ELIZABETH But we're so good together.
ELIZABETH We both hate slavery, we both love teaching.
ELIZABETH And call me crazy, but I always imagined us spending summers at your family's compound in Hyannisport.
SCOTT I know.
SCOTT And you're awesome and you have a huge heart and I love your empathy.
SCOTT It's just, when I was dry-humping you, I couldn't stop thinking about dry-humping Any.
ELIZABETH It's because of my tits, isn't it?
ELIZABETH Well, I'm getting new ones in, like, two days.
ELIZABETH Don't make a decision until you see them.
SCOTT Elizabeth, I think you're beautiful just the way you are, even with your flat chest.
SCOTT And I think Amy's beautiful.
SCOTT But I just have to do what's right.
SCOTT I made Amy a promise.
Scott holds up his hand, showing off a PROMISE RING.
ELIZABETH What're you -- 13?
ELIZABETH Elizabeth angrily gets up and pulls on her socks.
SCOTT Wait, Elizabeth.
SCOTT Don't go.
SCOTT Spend the night here with me.
SCOTT You can sleep on the other bed.
Ooh, like a slumber party?
I'm leaving.
And for the record, your band sucks, asstard.
Elizabeth opens the room door and exits.
She tries slamming the door, but it's on a spring so it closes very, very slowly.
The kids listen to a TOUR GUIDE on the steps of the memorial.
Garrett sneaks furtive glances at Chase.
Elizabeth stands away from the group, on her cell.
Wally.
Why would I cheat?
If I'm guilty of anything, it's teaching too hard.
Great...
I've got nothing to hide.
She ends the call.
ELIZABETH (CONT'D) Fuck!
ELIZABETH (CONT'D) Scott, wearing a Thomas Jefferson souvenir T-shirt, and all of the students look over at Elizabeth.
ELIZABETH.(CONT'D) What?!
ELIZABETH.(CONT'D) The Tour Guide looks around uncertainly before continuing.
TOUR GUIDE And does anyone know what Abraham Lincoln's nickname was?
TOUR GUIDE Sasha's hand shoots up.
SASHA Honest Abe.
TOUR GUIDE "Honest Abe", that's right.
TOUR GUIDE Because Lincoln always said what was on his mind, even if that meant being unpopular.
TOUR GUIDE Abraham Lincoln always showed great courage.
TOUR GUIDE Garrett takes this in.
TOUR GUIDE He looks over at Chase and then, after a beat, raises his hand.
Yes?
GARRETT I love Chase Streeter-Rossi.
GARRETT All eyes turn to Garrett.
GARRETT Chase looks mortified.
TOUR GUIDE Okay then.
TOUR GUIDE Any other questions?
GARRETT I love you, Chase.
GARRETT I've always loved you.
GARRETT And even though you pretty much stopped talking to me in fifth grade, I don't care.
GARRETT I remember the Chase that wrote me a card when my dad was overweight and had to go to the hospital because of his heart --
SASHA That was from the whole class.
GARRETT Shut up, Sasha, I'm talking about a different card.
And then, a year later, when he left my mom and moved in with his trainer, you wrote me another card.
What happened to us?
Remember when we had a sleepover in the second grade and you wet your bed and you were so embarrassed and you made me promise not to ever tell anyone.
Well, I never did and I never will.
I know we're really young, but remember Romeo and Juliet were only 13.
A lot of people don't know that.
So there it is.
My heart on a sleeve.
Don't let me leave / Always believe / A beat.
Chase stares at Garrett.
CHASE Gross.
CHASE Chase's friends all start laughing.
CHASE The rest of the class joins in.
CHASE Garrett runs down the steps, away from everyone.
SCOTT Alright, guys, let's settle down.
SCOTT The Tour Guide looks around, uncertain.
And these columns here are Doric columns.
Now let's move inside to see the interior murals painted by Jules Guerin.
The Tour Guide leads the group inside.
Elizabeth looks back and sees Garrett on the steps, his head in his hands.
She rolls her eyes and walks down to him.
ELIZABETH Hey, Abe Lincoln, get up.
ELIZABETH Tour's not over.
She just laughed at me.
Called me gross.
ELIZABETH You'll get over it.
ELIZABETH Get up.
GARRETT I'm not going back.
GARRETT Leave me alone!
ELIZABETH Now.
GARRETT No!
GARRETT Garrett runs off.
ELIZABETH Hey, come back here you little -- Elizabeth starts running after him in heels.
ELIZABETH She immediately breaks a heel.
She breaks the other heel.
ELIZABETH (CONT'D) Fucker.
EXT. WASHINGTON, D.C. - DAY The students stand by their bus.
EXT. WASHINGTON, D.C. - DAY Scott addresses them.
SCOTT Who had a good time in D.C.?
SCOTT The students let out a cheer.
SCOTT SCOTT (cont'd) (CONT'D) Who ate too many french fries at lunch?
SCOTT The students let out another cheer.
SCOTT SCOTT (cont'd) (CONT'D) Alright, let's do our final count-off.
TRISTAN A beat.
Wait, wait.
Where's 5?
Who's 5?
Everyone looks around.
SASHA I think it's Garrett Tiara.
SCOTT Garrett!
SCOTT Garrett!
SCOTT Nothing.
SCOTT Scott looks around, stricken.
SCOTT (cont'd) (CONT'D) And where's Ms. Halsey?
Nothing.
SCOTT (cont'd) (CONT'D) Alright, everyone on the bus!
Elizabeth searches for Garrett.
ELIZABETH Garrett!
ELIZABETH Garrett!
ELIZABETH Her cell phone RINGS.
ELIZABETH She checks the caller ID: "HOT SCOTT."
ELIZABETH She puts the phone back in her purse.
The kids are getting restless.
A lot of singing.
A lot of horsing around.
Let's go home!
Let's go home!
Scott sits up front by the driver.
He's on his cell.
I'm freaking out here.
They've been missing over two hours.
I'm just a substitute!
Shut up!!!
The chanting immediately stops.
Amy, the phone cradled to her ear, leans back on her couch.
She's wearing splotches of calamine lotion over her rash and her hair is pulled back.
A TURTLE plods across her kitchen table.
Oh my gosh.
We just might have a Mary Kay Letourneau situation on our hands.
Amy scratches the turtle's neck as it continues across the table.
SCOTT I don't know.
SCOTT You think?
AMY I know.
AMY The woman's a criminal mastermind.
SCOTT This is such a mess.
AMY What I need from you is to focus and get our kids home safe.
AMY I'll take care of everything here.
SCOTT Thanks, Amy.
SCOTT You're a lifesaver.
AMY It's what I do.
AMY Love you, Scooter.
AMY She hangs up the phone and cockily kicks her feet onto the table, accidentally knocking the turtle to the floor.
AMY (CONT'D) Oh boy.
We're no longer in the tourist areas.
A STRAY DOG walks down the middle of the street.
SIRENS WAIL.
PROSTITUTES hail Johns with catcalls.
Elizabeth, still in her broken heels, walks down the gritty street.
Garrett!
Garrett!
Her phone RINGS.
She checks the CALLER ID -- "HOT SCOTT."
I'm looking for him!
Stop fucking calling me!
She powers her phone off and continues down the street.
She passes two PROSTITUTES.
ELIZABETH (CONT'D) Hey, guys.
ELIZABETH (CONT'D) Hi.
ELIZABETH (CONT'D) I'm looking for a young kid, about 13.
ELIZABETH (CONT'D) Really annoying, kind of a cry baby.
ELIZABETH (CONT'D) Have you seen him?
PROSTITUTE #1 Fuck you.
ELIZABETH Fantastic.
PROSTITUTE #2 You best step off, bitch, because this is my block.
PROSTITUTE #2 This here's Poetry's block.
ELIZABETH Poetry?
PROSTITUTE #1 Cause that's how she fuck.
PROSTITUTE #2 I fuck like that.
PROSTITUTE #2 Lyrical.
PROSTITUTE #2 Something occurs to Elizabeth.
PROSTITUTE #2 She smiles.
ELIZABETH Thank you, Poetry.
ELIZABETH And Poetry's friend.
ELIZABETH Elizabeth walks off and sticks out her hand, trying to hail a cab.
ELIZABETH She passes a bunch of HOMELESS MEN warming up by a trash can fire.
Won't get a cab in this neighborhood.
A CAR slows next to Elizabeth.
A JOHN rolls down the passenger window and leans out.
JOHN Hey, sweetheart.
JOHN How much for a titty fuck?
ELIZABETH I need a ride.
JOHN Oh yeah, I need a ride, too.
JOHN Right through those titties.
ELIZABETH No, I need a ride.
ELIZABETH Like you driving, and me pointing mace at your face.
ELIZABETH I'll give you ten bucks.
This is weird.
Twenty.
Elizabeth hops in.
MIDNIGHT.
PARENTS are waiting.
A few console Garrett's mom, Melody.
A few LOCAL NEWS VANS idle nearby.
He's gonna be alright.
The police will find him.
I'm sure they're back at the hotel.
Probably just a mix-up.
The bus pulls up to the curb and stops.
Scott steps off first, clearly confused by the crowd and TV cameras.
Immediately, a reporter thrusts a mic into his face.
REPORTER What can you.
REPORTER tell us about the alleged romance between Elizabeth Halsey and a 13 year old student?
What?
The students step off and the Parents swarm them.
PARENT #1 Oh baby, are you okay?
PARENT #1 Did she touch you?
PARENT #1 Sasha's parents engulf her in a hug.
SASHA'S MOTHER Oh Sasha!
SASHA'S MOTHER You expect this stuff to happen in Florida, not here.
Garrett walks up to a drab building where he sees Elizabeth on the curb waiting for him.
There's a tiny sign that reads "Office of the Poet Laureate."
ELIZABETH It's closed.
ELIZABETH Won't be open till morning.
ELIZABETH Come on.
ELIZABETH Let's get back to the hotel.
ELIZABETH I'm sure everyone's mad at you.
ELIZABETH Garrett stands his ground.
GARRETT I'm not leaving without talking to the poet laureate.
ELIZABETH Do you think that some Shel Silverstein wannabe is going to tell you the meaning of life?
GARRETT What do you care?
ELIZABETH I'm here, right?
GARRETT You have to be here.
GARRETT You're a teacher.
ELIZABETH Not for long.
ELIZABETH I'm getting fired for cheating as soon as we get back.
ELIZABETH Garrett takes a seat next to Elizabeth.
GARRETT So.
GARRETT you came looking for me on your own?
ELIZABETH Yup.
ELIZABETH And you owe me a new pair of Nanette Lepores.
GARRETT I just want to know what to say to Chase to get her to like me.
ELIZABETH You know what you should do?
What?
ELIZABETH Just go out and sleep with as many girls, as you possibly can.
ELIZABETH Get her out of your head.
GARRETT They'll probably reject me, too.
ELIZABETH Yeah, probably.
ELIZABETH But life's about how you deal with rejection.
ELIZABETH You can either hide in a corner and cry or you can get stronger every time.
ELIZABETH And I figure a kid like you with not much going for him -- if he were to choose the latter -- might end up becoming a pretty strong man.
Thanks.
ELIZABETH Now come on, let's get out of here.
ELIZABETH I'm freezing and Mr. Delacourte's probably shitting a brick.
GARRETT I can't go back there.
GARRETT All the kids will laugh at me.
ELIZABETH You seriously think they haven't been laughing already?
GARRETT Maybe Chase is wondering where I am.
ELIZABETH Hate to break it to you, kid, but I don't think anyone gives two shits where we are.
Principal.Snur sits across from Garrett's mother, Melody, who is beside herself.
She is wearing a beret.
A DETECTIVE and Amy are standing behind the desk.
Principal Snur passes her a dolphin-shaped tissue box.
DETECTIVE What else can you tell us about Garrett and Ms. Halsey's relationship?
MELODY It was strictly student/teacher.
MELODY Garrett's a gifted poet and Ms. Halsey was trying to bring that out of him.
MELODY Amy snorts.
DETECTIVE Did they ever spend time outside of the classroom?
MELODY Aside from Christmas at our house?
MELODY Absolutely not.
MELODY The Detective glances at the Principal, like "Oh boy."
AMY She used to give all the guys that look.
AMY That sex look.
AMY You know -- Amy gives her version of a sexy look to the Detective.
AMY (CONT'D) She's a monster.
DETECTIVE Mrs. Tiara, I think we might need to consider the possibility that Elizabeth Halsey has abducted your son and that the two of them are involved in a sexual relationship.
Marbles doesn't even have armpit hair!
DETECTIVE We should send out an Amber Alert.
DETECTIVE We need to catch this Sicko.
A REPORTER talks to camera on the steps of J.A.M.S.
Other NEWS CREWS are in the bg.
REPORTER A school official close to the scandal confirms that in addition to her alleged sexual relationship with the unnamed seventh grader, Elizabeth Halsey has been investigated for possible drug use, standardized testing fraud, and the theft of an "Annie" wig from a school production.
REPORTER The TV Report flashes an unflattering photo of ELIZABETH with a BLURRED OUT GARRETT.
REPORTER In front of the school, the Reporter turns to Principal Snur.
Can you comment on any of these allegations?
PRINCIPAL SNUR The superintendent will speak to the press shortly, but for now, I'd just like to say that I hope Ms. Halsey does the right thing and brings back our student.
Elizabeth buys two tickets.
Garrett hovers beside her.
You're paying me back for this.
Elizabeth's ex-fiance, mark, stands with Sheila and talks to a REPORTER.
MARK Am I shocked?
MARK Mark starts laughing.
She was always very cold to me.
EXT. JOHN ADAMS MIDDLE SCHOOL - NIGHT Chase is crying as she speaks to a DIFFERENT REPORTER.
CHASE Garrett sat diagonal from me in language arts.
CHASE He was always so supportive of my modelling career.
EXT. JOHN ADAMS MIDDLE SCHOOL - NIGHT Lynn stands with a DIFFERENT REPORTER.
She's my best friend.
She tells me everything.
We have lunch together!
EXT. JOHN ADAMS MIDDLE SCHOOL - NIGHT Tristan stands with a DIFFERENT REPORTER.
TRISTAN I've been telling him to hit that all year.
TRISTAN That's my boy!
EXT. JOHN ADAMS MIDDLE SCHOOL - NIGHT Amy talks to a DIFFERENT REPORTER.
AMY "No child left behind."
AMY How ironic.
AMY That a child was left behind.
AMY In Washington, D.C. With a statutory rapist.
Elizabeth and Garrett are seated next to one another on the darkened train.
Garrett's asleep against the window, Elizabeth is reading "In Style" with the overhead light.
Garrett stirs, rolls the other way and gently places his head on Elizabeth's shoulder.
She looks at him and then shrugs her shoulder to get him off.
His head falls back on.
She leaves it.
Elizabeth is asleep on Garrett's shoulder.
Garrett is pressed against the window, clearly uncomfortable.
The Taxi turns a corner and Garrett notices something.
GARRETT Hey, there's a bunch of people outside of my house.
Elizabeth wakes up and looks up to see: A CANDLELIGHT VIGIL, including Amy, Scott, Melody, and many.
of Garrett's classmates; a SEA OF TV CAMERAS; and
ELIZABETH What the fuck?
ELIZABETH Did you steal something?
ELIZABETH The taxi pulls up to the curb and Elizabeth and Garrett .exit.
ELIZABETH CHAOS.
ELIZABETH They're immediately swarmed by everyone.
ELIZABETH The Cops struggle to push past.
Marbles!!!
The reporters thrust mics in her face.
How long have you been Why did you steal the sleeping together?
"Annie" wig?!
Just the once on the train.
What?!
The Cops get through and smother Garrett in a police blanket.
A FEMALE COP roughly leads Elizabeth to one of the squad cars.
ELIZABETH (CONT'D) This is crazy!
ELIZABETH (CONT'D) He's a kid.
ELIZABETH (CONT'D) Elizabeth is put into the back of squad car.
ELIZABETH (CONT'D) I'm a good person!
ELIZABETH (CONT'D) I don't fuck minors!
ELIZABETH (CONT'D) Elizabeth bangs on the window.
ELIZABETH (CONT'D) Amy smiles and waves.
A Sergeant is leading Elizabeth to a phone.
SERGEANT You're quite the celebrity.
ELIZABETH You want an autograph?
SERGEANT You get one call.
SERGEANT Elizabeth picks up the phone.
SERGEANT The Sergeant gives her some space.
Hi, this is Elizabeth Halsey calling.
I'm calling to cancel my surgery for tomorrow.
Extenuating circumstances.
Please, please don't make me lose my deposit.
Elizabeth slams down the receiver.
SERGEANT If you need medical attention, we're required to provide it.
ELIZABETH Just take me back to my cell.
Silence.
Elizabeth and her roommate, Kirk, who's now dressed in an ill-fitting suit and has his hair combed, sit across from Principal Snur and the SCHOOL SUPERINTENDENT, a no- nonsense woman in her 60s.
PRINCIPAL SNUR Again, speaking on behalf of the whole administration, I just want to apologize for what happened.
PRINCIPAL SNUR Clearly, there was a miscommunication.
ELIZABETH Oh, you think?
ELIZABETH Kirk puts his hand up to Elizabeth, like "I'll take care of this."
KIRK My client has been an upstanding member of society her entire life.
KIRK She has spent time as an educator, she has
ELIZABETH More than once!
KIRK And she has touched the lives of those around her -- until last night.
KIRK Elizabeth pulls Kirk into a lawyer/client huddle.
You kind of sound like a pro.
Do you think they're going to find out that I didn't pass the bar?
You're doing great.
They break from their huddle.
KIRK Your administration jumped to conclusions, set off a media fire-storm and has humiliated one of its own.
KIRK As Ms. .Halsey's chief counsel, I've advised her that we have an extremely strong case of libel and that it's certainly within her province to sue the district.
SUPERINTENDENT How do we make this go away?
KIRK Ms. Halsey is not a litigious woman.
KIRK She wants this whole matter to go away as quickly and painlessly as possible.
KIRK Kirk slides a piece of paper across the desk.
KIRK (CONT'D) This is a list of our demands.
KIRK (CONT'D) The Superintendent and Principal Snur scan the list.
SUPERINTENDENT You're kidding me.
ELIZABETH Don't answer right now.
ELIZABETH Let it marinate.
ELIZABETH Oh, and I should mention that if this goes to trial, I can cry on cue.
ELIZABETH Elizabeth starts crying.
ELIZABETH Everybody looks at her, aghast.
ELIZABETH And as quickly she started, she stops.
ELIZABETH (CONT'D) Now, if you'll all excuse me, I should be heading to fifth period.
ELIZABETH (CONT'D) I hate to be tardy.
Elizabeth heads down the empty hallway.
From the auditorium, the faint sound of "Tomorrow, Tomorrow" from "Annie" can be heard.
Amy steps out of the auditorium, humming along to the song.
She notices Elizabeth coming to her.
Amy debates her options.
AMY Elizabeth!
AMY I was so worried.
AMY You gave us quite a scare, you did.
AMY Elizabeth doesn't acknowledge her and continues walking toward Amy, only feet away now.
AMY (CONT'D) Somebody's being a grumple-- BAM!
AMY (CONT'D) Elizabeth punches Amy square in the nose.
AMY (CONT'D) Amy drops to her knees and grabs her nose, now squirting blood.
AMY (CONT'D) Elizabeth keeps walking and turns a corner.
AMY (CONT'D) A BELL RINGS and the hallway starts filling with STUDENTS.
PRINCIPAL SNUR (V.0.) Well, it's been another great year at
QUICK CUTS.
The year is winding down.
Instead of gym, kids are using the time to sign each other's yearbooks.
Chase walks up to Garrett with her yearbook, asks him to sign it.
PRINCIPAL SNUR (V.0.) Who can forget the exciting addition of a climbing wall to the small gym...
QUICK CUTS.
It's class photo day.
With each FLASH, we SEE a different TEACHER with a different CLASS.
And finally AMY, with a bandage over her nose and two black eyes, smiles widely alongside her CLASS.
PRINCIPAL SNUR (V.0.) .Or the student/teacher spelling bee.
Much like the first scene of the movie.
The teachers are sipping plastic flutes of Champagne.
Principal Snur is up front.
Elizabeth lingers in the back.
PRINCIPAL SNUR I think that was a huge s-u-c-c-a-s-s.
PRINCIPAL SNUR Polite laughter.
PRINCIPAL SNUR (CONT'D) But seriously...
PRINCIPAL SNUR (CONT'D) With summer around the corner, it's time to not only say goodbye to another school year, but to also say goodbye to one of our own.
PRINCIPAL SNUR (CONT'D) Elizabeth smiles.
PRINCIPAL SNUR (CONT'D) Amy Squirrel.
PRINCIPAL SNUR (CONT'D) Amy, her face completely healed, steps forward, with a pursed smile.
PRINCIPAL SNUR (CONT'D) After six short years of outstanding, tireless work here, Amy is transferring out of the district.
PRINCIPAL SNUR (CONT'D) I know she'll bring her love for learning to her new students.
PRINCIPAL SNUR (CONT'D) Sandy, the ponytailed teacher, pipes up.
SANDY Speech!
SANDY Speech!
AMY Although leaving was a difficult choice...
AMY Amy looks over to Elizabeth, who motions for her to continue.
AMY (CONT'D) When the superintendent personally asks you to work at one of the worst schools in the state, you say yes.
AMY (CONT'D) I'm looking forward to bringing my brand of zany energy and lust -- not love, lust -- for learning to the underprivileged students at Malcolm X High.
AMY (CONT'D) I welcome the challenge.
AMY (CONT'D) The Teachers applaud, Scott the most enthusiastic.
AMY (CONT'D) Elizabeth steps up to Amy, who flinches.
ELIZABETH Here, I got you this.
ELIZABETH Elizabeth hands Amy a poster tube.
ELIZABETH She.opens it and unravels the "Integrity" poster that Elizabeth stole.
ELIZABETH (CONT'D) And good luck.
ELIZABETH (CONT'D) Somebody's gonna need it.
ELIZABETH (CONT'D) Elizabeth heads for the door.
ELIZABETH (CONT'D) Scott catches up to her.
SCOTT Hey, Stranger.
SCOTT Listen, now that Amy's transferring, maybe the two of us could go grab a drink.
SCOTT Elizabeth walks out.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY Elizabeth's 1994 Grand-Am pulls into her spot.
EXT. JOHN ADAMS MIDDLE SCHOOL - TEACHER PARKING LOT - DAY And as her bare leg steps out of the car, we
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY The hallway is empty.
INT. JOHN ADAMS MIDDLE SCHOOL - HALLWAY - DAY We FOLLOW Elizabeth from behind, and as she reaches for the door to her class, we
INT. ELIZABETH'S CLASSROOM - DAY Quick cuts.
INT. ELIZABETH'S CLASSROOM - DAY From behind, we see Elizabeth place an APPLE on each desk, just as Amy did earlier.
INT. ELIZABETH'S CLASSROOM - DAY Elizabeth's walls are still bare, except for a framed photo of Amy's class picture, with Amy's messed up face, from the year before.
INT. ELIZABETH'S CLASSROOM - DAY The bell RINGS.
INT. ELIZABETH'S CLASSROOM - DAY Elizabeth turns and we now SEE that she has TASTEFUL FAKE
Elizabeth walks to her door and opens it, watching the students as they reconnect with friends and share stories about summer camp.
She notices Sasha who is MASSAGING a BOY's shoulders.
bunch of other EIGHTH GRADE BOYS wait their turn.
Do me!
Do me!
Sasha clearly enjoys the attention.
Elizabeth smiles.
Garrett walks by, hand in hand with Chase.
Trailing both of them are identical rolling backpacks.
He sees Elizabeth and runs over.
ELIZABETH You and Chase, huh?
ELIZABETH She likes the poetry?
GARRETT She likes that I'm kind of a celebrity.
GARRETT But I'm cool with it.
GARRETT I'm the man around here!
ELIZABETH Easy.
GARRETT Well, I should get going.
GARRETT See you around, Ms. Halsey.
GARRETT Oh, and nice...
GARRETT He points at her breasts.
Thanks!
You're the first student to notice.
Garrett smiles and walks off.
Lynn walks by.
She's cleaning another big stain from her shirt.
LYNN Elizabeth, hey!
LYNN How was your summer?
ELIZABETH It was great.
ELIZABETH I met a doctor!
ELIZABETH Plastic surgeon, actually.
ELIZABETH He's amazing.
LYNN He sounds amazing.
LYNN How'd you meet him?
LYNN The internet?
ELIZABETH No, in recovery.
ELIZABETH And I looked like ass, so I know it's real.
LYNN Sounds like a fairy tale.
ELIZABETH It is.
ELIZABETH Storybook.
ELIZABETH Well, not total storybook.
ELIZABETH It's a little messy because his wife filed for divorce last week, but we're gonna get through that.
So you want to grab lunch later?
LYNN Sure!
LYNN My treat.
ELIZABETH No, you got it last time.
ELIZABETH We'll split it.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
