THE KING'S SPEECH
Written by
David Seidler
A shimmering surface of cold water - held in an immense, free standing, white enamelled bathtub with gilded lion's legs - bulges in SLOW MOTION to the chords of Handel's "Trumpet Volunteer".
A head emerges.
White gloved hands, in livery, rush to envelope the surfacing naked wet body in white towels.
The ritual continues with crisp military precision.
CLOSE ON the Royal Coat Of Arms stamped in gold: lion and unicorn embrace a shield divided into four quarters with harp, thistle, and more lions denoting England, Ireland, Scotland and Wales.
The shield is surmounted by a crown.
This emblem is on a cuff-link fastened on a starched white shirt.
Trousers, pressed to a knife-edge, are held for stockinged feet and gartered legs to be inserted.
Mirror-polished boots are laced tight.
Jacket, held ready.
Arms, shoulders, chest received.
Glistening medals attached to front of jacket create a dazzling field of ribbons and medallions.
Epaulets, edged with gold braid tassels, are adjusted.
Polished buttons are fastened.
Multi-coloured collar clasped shut.
White ostrich feathers, topping a tri-corner hat, are fluffed and placed upon brilliantined hair.
PAN DOWN to the handsome features of Albert, Duke of York, known to his family as BERTIE.
He's in his late thirties, the second son of King George V, the reigning King of England.
He conveys a sensitivity which appears in conflict with the manner in which he's been bedecked.
Reflected in a full length mirror, Bertie tells himself: TKS/Seidler/09/17/08 3.
BERTIE You look like a Christmas tree.
He smiles wanly.
THE ROYAL STANDARD flaps atop a gleaming chrome grill.
Liveried footmen open the doors of a stately Austin Princess.
Bertie exits York House with his young wife - ELIZABETH - considered by all to be one of the loveliest women in the land, truly an English rose.
Golden Labradors and Corgis appear from all directions, weaving between them, barking boisterously, creating a happy chaos.
Elizabeth and Bertie glance upwards and wave.
Two little girls, LILIBET and MARGARET ROSE, aged eight and four, wave back from their nursery window.
Bertie nervously lights a cigarette.
Elizabeth pats his hand.
ELIZABETH Buck up, Bertie.
ELIZABETH The BBC said it wouldn't rain.
BERTIE'S POV - Speaker's Corner with its assortment of orators, prophets, protestors, and onlookers gathered around soapboxs, agreeing, disagreeing, shouting comments.
Others carry placards, sing protest songs.
A miners' strike is the focus of the day.
A large, rather untidy workingman with a florid rosacea nose spots the passing Austin and stares at the occupants.
REVERSE ANGLE - Bertie's face stares back.
The first drops splatter against the glass.
Elizabeth sighs.
ELIZABETH (CONT'D) Never trust the wireless.
Bertie's face is obliterated by the increasingly heavy downpour, which segues into a GARGLING sound.
TKS/Seidler/09/17/08 4.
A gentleman in a tuxedo, carnation in boutonniere, is gargling while a TECHNICIAN holds a porcelain bowl and a towel at the ready.
The man in the tuxedo is a BBC NEWS READER.
He expectorates discreetly into the bowl, wipes his mouth fastidiously, and signals to ANOTHER TECHNICIAN who produces an atomizer.
The Reader opens his mouth, squeezes the rubber bulb, and sprays his inner throat.
Now, he's ready.
He looks to the control room.
The FLOOR MANAGER begins a count-down: five...
four...
three...
two...
BBC NEWS READER Ladies and Gentlemen: good afternoon.
BBC NEWS READER This is the BBC National and World Programmes taking you to Wembley Stadium.
He speaks in flawless pear-shaped tones.
There's no higher creature in the vocal world.
ELEVATED SHOT looking down on a sea of dripping black umbrellas hiding the spectators from view.
Bertie and Elizabeth takes their places in a row of gilded chairs with the other dignitaries.
They are:
KING GEORGE V - a barrel-chested man with Naval beard and uniform, accompanied by his wife.
QUEEN MARY - an elegant but icy grande dame.
DR COSMO LANG - a tall, unctuous, churchman with a high, domed, balding head, and a perpetual expression of moral superiority.
WINSTON CHURCHILL - a politician of sixty, as portly as Lang is lean.
They are bantering rivals in ambition.
STANLEY BALDWIN - the Prime Minister of the day.
Heavy-browed.
His hair, as always, parted down the middle.
NEVILLE CHAMBERLAIN - Chancellor of the Exchequer.
Tall, thin, lugubrious, with the expression of a quizzical chicken hawk.
A BBC technician places a huge imposing microphone suspended on springs next to the stadium equipment.
It looks frightening, even to us.
Bertie's shoulders brace as though expecting a blow.
Elizabeth sees his terror.
TKS/Seidler/09/17/08 5.
ELIZABETH Why wasn't he told?
COSMO LANG Ten million people listening around the world, Mam.
COSMO LANG Possibly more.
COSMO LANG His brother, and father, have been broadcasting since last year.
The King, growing impatient, hisses:
KING GEORGE V Get on with it.
KING GEORGE V Show what you're made of!
Bertie moves forward diffidently, without an ounce of confidence, knowing deep within he's doomed.
His stomach knots, chest muscles contract, constricting his breath.
BERTIE Luh-luh-lords, la-la-ladies, gen-tell-men.
It is a shock to realize this is a man with a profound stutter.
A man who cannot speak in public.
Lang whispers to Churchill.
When Lang whispers, everyone can hear.
COSMO LANG I wouldn't miss His Highness' maiden voyage for all the world.
COSMO LANG And on such an important occasion.
Lang really is a piece of work.
For ease of reading, Bertie's stutter is not indicated from this point on in the script.
BERTIE No doubt you wish the Prince Of Wales was standing before you today.
POV - a sea of dripping umbrellas.
No response.
This is going to be a torment for him, and his audience.
A glowing dial on the face of a studio radio.
Everyone listening intently.
TKS/Seidler/09/17/08 6.
BERTIE (ON RADIO) Be that as it may...my brother David is attending to other duties in the furthest parts of this vast Empire...
The radio falls silent.
Eyes widen in concern.
Bertie stands frozen, his mouth agape, jaw muscles locked.
He knows he's considered by all, especially himself, unfit for public life.
Elizabeth is devastated.
KING GEORGE V Just needs more practice.
TRACKING SHOT - rain splatters on brass plaques denoting Dr This or Dr That, specialists in various maladies.
Halt at a plaque that reads: LIONEL LOGUE, SPEECH SPECIALIST.
Umbrella stand, coat rack, wooden waiting bench: that's all.
The door is flung open and Elizabeth enters, drenched, her hat decorated with white silk roses, now limp.
A veil covers her features.
She waits.
Coughs.
No response.
Calls imperiously:
ELIZABETH Are you there?
From behind a door:
LIONEL In the lav.
Princess Elizabeth is not used to this sort of thing.
She's further appalled by the loud gurgling of a toilet being flushed, and startled by the entrance of - LIONEL LOGUE.
He's in his forties, tall, with piercing eyes and charismatic features.
His demeanor is friendly, but professional.
The accent, although Australian, is not heavy, he is after all a speech therapist.
TKS/Seidler/09/17/08 7.
LIONEL (CONT'D) "How poor are they that have not patience!
LIONEL (CONT'D) What wound did ever heal but by degrees?"
ELIZABETH Pardon?
LIONEL Iago...world's greatest villain.
LIONEL Just wants to be bad.
LIONEL Sorry, no receptionist.
He offers to shake hands.
She doesn't take it, even though she's gloved.
ELIZABETH I'd be more comfortable in your office.
LIONEL That's for clients.
LIONEL Where's Mister J?
ELIZABETH He doesn't know I'm here.
LIONEL That's not a promising start.
ELIZABETH My husband's seen everyone.
ELIZABETH They were all useless.
ELIZABETH He's given up hope.
LIONEL A bit premature.
ELIZABETH Because he hasn't seen you?
Lionel doesn't disgree.
ELIZABETH (CONT'D) You're very sure of yourself.
LIONEL I'm sure of anyone who wants to be cured.
ELIZABETH Of course my husband wants to be cured!
ELIZABETH His position requires public speaking upon occasion.
ELIZABETH A torment.
ELIZABETH I fear the requirement may grow more frequent.
LIONEL He should change jobs.
TKS/Seidler/09/17/08 8.
ELIZABETH He can't.
LIONEL Indentured servitude?
ELIZABETH Something of that nature.
LIONEL Well, have your `hubby' pop by and give his personal history.
LIONEL I'll make a frank appraisal.
ELIZABETH Doctor...
Logue tries to object but she over-rides.
ELIZABETH (CONT'D) ...I do not have a "hubby".
ELIZABETH (CONT'D) We never talk about our private lives.
ELIZABETH (CONT'D) Nor do we `pop'.
ELIZABETH (CONT'D) You must come to us.
LIONEL Sorry, this is my game, played on my turf, by my rules.
The lady lifts her veil.
ELIZABETH Perhaps you'll make an exception?
He recognizes her instantly, and is clearly impressed, yet refuses to be intimidated.
LIONEL I thought the appointment was for "Johnson"?
ELIZABETH A name used during the Great War, when the Navy didn't wish the enemy to know His Royal Highness was aboard.
LIONEL I'm considered the enemy?
ELIZABETH You will be, should you continue to be un- obliging.
ELIZABETH TKS/Seidler/09/17/08 9.
LIONEL For my method to succeed there must be mutual trust, complete honesty, and total equality.
LIONEL That process takes place in my consultation room.
LIONEL No exceptions.
ELIZABETH In which case...
ELIZABETH I should have kept my pledge.
ELIZABETH I promised my husband I'd stop seeking "The Great Cure."
ELIZABETH I've wasted your time.
ELIZABETH And mine.
She exits, closing the door firmly behind her.
LIONEL Bloody hell, I buggered that.
WACK!
The sound of something solid meeting leather.
A foot kicks a ball.
Lionel is returning home from work.
He's a well-known fixture locally.
Some lads are playing footie.
One of them passes the ball to Lionel who, despite briefcase and rolled brolly, dribbles skillfully before passing the ball and entering a modest brownstone.
As Lionel mounts the stairs he's set upon by three sturdy boys - VALENTINE, IAN, and PETER - with handkerchiefs tied around the lower portions of their faces and armed with broomstick swords.
VALENTINE Stand and deliver!
LIONEL `ow dares molest...Jack The Ripper?!
The boys scream with delight and a sword fight ensues - Lionel using his brolly.
LIONEL (CONT'D) Beware, Highwaymen, or I'll run yee through.
PETER We're Swagmen, not Highwaymen, Dad.
TKS/Seidler/09/17/08 10.
LIONEL Oh.
LIONEL Beware, jolly Swagmen, I'll skewer yer gizzards.
Lionel wife - MYRTLE - appears at the head of the stairs; a sweet-faced, down-to-earth woman.
MYRTLE You'll all hang from the gallows if you don't come for tea.
LIONEL Boys, I think we'd best go up.
Logue, Myrtle, and the boys are finishing at the table.
LIONEL Had a visit from a lady today.
MYRTLE Another spoiled silly?
VALENTINE May we be excused?
LIONEL You must stay, bored stupid, listening to your parents' inane conversation.
THE BOYS Thanks, dad!
LIONEL And mum.
THE BOYS And mum!
They start to leave.
MYRTLE Take your plates.
The boys grabs their plates and exit.
After a moment...
MYRTLE (CONT'D) No wonder about the silly.
MYRTLE (CONT'D) You're so good at what you do.
TKS/Seidler/09/17/08 11.
LIONEL At what I do.
LIONEL Twas a Lady with a capital L.
MYRTLE Oh, Lionel, that'd get us home in grand style wouldn't it?!
LIONEL She came on behalf of her husband.
LIONEL Which is not the proper way.
LIONEL I told her I was fully booked.
Myrtle is clearly disappointed
LIONEL (CONT'D) She was...too high and mighty.
LIONEL (CONT'D) Know what I mean.
She does.
There's an unspoken code between them.
MYRTLE We wouldn't want that.
Covers her letdown.
MYRTLE (CONT'D) Hard to feel sorry for that sort.
Silence, then:
LIONEL Had a call.
LIONEL Wish me luck?
MYRTLE Course, Lionel.
MYRTLE Loads and loads.
Elizabeth, fashionably attired for an evening-out, is curled on a bearskin rug reading "Peter Pan" to the girls.
ELIZABETH "Mr.
ELIZABETH and Mrs. Darling and Nana rushed into the nursery too late.
ELIZABETH The birds were flown."
Bertie enters, handsome in a tuxedo.
Elizabeth closes the book.
ELIZABETH (CONT'D) Tomorrow, Chapter IV, `The Flight'.
TKS/Seidler/09/17/08 12.
The two little girls clap with joy.
MARGARET ROSE Oh, to fly away!
BERTIE Weren't they lucky.
Within his family, Bertie's stutter is virtually absent.
LILIBET One would have to learn to fly properly of course.
MARGARET ROSE Now a Daddy story!
BERTIE Can I be a penguin instead?
He drops to his knees and waddles.
In his tux he looks like a penguin.
The girls giggle, but are undeterred.
LILIBET The horsie story, please.
BERTIE Ah well.
Called upon to perform, the stutter returns slightly.
But the two girls listen raptly, ignoring their father's minor impediment, and it fades.
BERTIE (CONT'D) Once upon a time there were two horsies.
BERTIE (CONT'D) A white horse that went clip clop clip clop through Hyde Park.
BERTIE (CONT'D) And a black horse that went clip clop clip clop through Hyde Park.
BERTIE (CONT'D) They met in the middle of Hyde Park.
BERTIE (CONT'D) The white horse said "neigh".
BERTIE (CONT'D) The black horse said, "neigh".
BERTIE (CONT'D) The white horse continued on, clip clop clip clop through Hyde Park.
BERTIE (CONT'D) The black horse continued on, clip clop clip clop through Hyde Park.
BERTIE (CONT'D) And that's the end of the story.
BERTIE (CONT'D) Now off to bed.
As the girls exit:
LILIBET A silly story really.
LILIBET But Father tells it rather well.
The girls have gone.
TKS/Seidler/09/17/08 13.
BERTIE David called.
BERTIE He said come round to The Fort on Friday and stay for dinner.
ELIZABETH Will she be there?
BERTIE I suppose.
ELIZABETH Seriously?
BERTIE Seriously, she'll be there.
ELIZABETH I think I meant...
ELIZABETH is David serious?
BERTIE About our coming?
ELIZABETH About her!
BERTIE A married American?
BERTIE Twice divorced?
BERTIE He can't be.
ELIZABETH She can.
Movements behind a curtain.
MUFFLED VOICE (UNSEEN) Now?
From the auditorium:
DIRECTOR Now!
Someone pushes through a gap.
Its Lionel.
LIONEL "Now..."
Falters, begins again.
TKS/Seidler/09/17/08 14.
LIONEL (CONT'D) "Now is the winter of our discontent Made glorious summer by this sun of York..."
His elocution is crisp and flawless.
His acting, however, is unconvincing.
LIONEL (CONT'D) "And all the clouds that lour'd upon our house In the deep bosom of the ocean buried.
LIONEL (CONT'D) Now are our brows bound with victorious wreaths..."
DIRECTOR Thank you.
DIRECTOR Beautiful diction...but I don't hear the cries of a deformed creature yearning to be King.
Lionel struggles to maintain a semblance of dignity.
LIONEL What do you suggest?
DIRECTOR Continue to do whatever you do, and hope it gives you a great deal of satisfaction.
Crushed, Lionel retreats behind the curtain.
Cold and austere mausoleum illuminated by floodlights.
On the parade ground, Grenadier Guards in red coats and black bearskin busbies drill stiffly like toy soldiers.
Viewing stands are beginning to fill.
The King's voice is heard:
KING GEORGE V Stride boldly up to the bloody thing, stare it square in the eye, and talk to it as you would to any decent Englishman.
The King's study resembles a naval captain's cabin.
Both men are uniformed for a state occasion.
Bertie regards the BBC microphone as though it were an alien.
TKS/Seidler/09/17/08 15.
BERTIE I d-d-don't thu-thu-think I c-c-can.
In the presence of his father, Bertie's stuttering returns in full form, his breathing short and shallow, the muscles in spasms.
KING GEORGE V Show who's in command.
KING GEORGE V If you don't, this devilish device will change everything.
KING GEORGE V Used to be, all a King had to do was look reasonable in uniform and not fall off his horse.
KING GEORGE V Now we must creep cap in hand into people's homes that smell of boiled cabbage, and speak nicely to them.
KING GEORGE V We're reduced to that lowest, basest of all creatures...we've become...actors!
KING GEORGE V Don't give me a look of defeated pathos.
KING GEORGE V This is a family crisis!
BERTIE Father, we're not a family, we're a firm.
His father shoots Bertie a surprised look.
Does the lad have a brain after all?
KING GEORGE V We're the oldest, most successful, corporation in the world and sitting on thrones is our business!
KING GEORGE V But any moment now we may be out of work.
KING GEORGE V Your brother came to me the other day, livid a certain lady has been refused an invitation to my Silver Jubilee.
KING GEORGE V I pointed out she wasn't a lady and most definitely wasn't his wife.
BERTIE What did David say?
KING GEORGE V She made him sublimely happy.
KING GEORGE V I said: that was probably because she was sleeping with him.
KING GEORGE V "I give you my word we've never had immoral relations."
KING GEORGE V "As my son, as Prince of Wales, as my heir, do you solemnly swear your friendship with this woman is an absolutely clean one?" "I do", he said.
KING GEORGE V "Look me in the eye," I said.
KING GEORGE V "On my honour" he said.
KING GEORGE V Stared straight at his father...
KING GEORGE V and lied.
BERTIE Oh my brother...
TKS/Seidler/09/17/08 16.
KING GEORGE V When I'm dead that boy will ruin himself, this family, and this nation, within twelve months.
KING GEORGE V Who'll pick up the pieces?
KING GEORGE V David's friend, Oswald Mosley?
KING GEORGE V His black-shirt British Union of Fascists are marching through London.
KING GEORGE V Hitler terrorizing half of Europe, Stalin the other half.
KING GEORGE V Who'll stand between us, the jackboots, and the proletarian abyss?
KING GEORGE V You?
A red light attached to the mike begins a series of warning blinks.
BERTIE What're you going to say?
KING GEORGE V The usual guff.
KING GEORGE V The Archbishop writes it.
KING GEORGE V My people love to hear me say it.
KING GEORGE V Spoken fluently, of course.
They're interrupted by the entrance of the BBC News Reader and Technicians.
KING GEORGE V (CONT'D) That's the chap who taught me how to use this contraption.
KING GEORGE V (CONT'D) You touch your chin with your thumb and the `thing' with the end of your little finger.
KING GEORGE V (CONT'D) Splendid fellow.
SQUISH.
Assisted by the Technicians, the News Reader sprays his throat.
BBC NEWS READER Good evening, ladies and gentlemen, this is the BBC, broadcasting direct from Buckingham Palace upon the occasion of the Royal Silver Jubilee.
BBC NEWS READER His Majesty: King George the Fifth.
KING GEORGE V "I can only say to you, my very very dear people, that the Queen and I thank you from the depths of our hearts for all the loyalty and - may I say so?
KING GEORGE V - the love with which this day and always you have surrounded us.
KING GEORGE V I dedicate myself anew to your service for all the years that may still be given to me."
The News Reader, terribly moved, whispers to his Technicians: TKS/Seidler/09/17/08 17.
BBC NEWS READER That's how a King speaks.
BBC NEWS READER I showed HM how to do it.
The edge of the crowd is visible.
One can sense a vast sea of humanity.
When the glass doors of the upper balcony open the murmur becomes a ROAR.
When the King steps out, it becomes tumultuous.
The King is joined by Queen Mary and the Archbishop of Canterbury, other Royals, and dignitaries.
The noise is deafening.
The King beckons impatiently for someone still inside to join them.
It's Bertie, with Elizabeth.
BERTIE They didn't come to see us, Father.
KING GEORGE V Pretend.
BERTIE Where's David?
KING GEORGE V Bedding his American whore.
KING GEORGE V Come, join the fun!
KING GEORGE V You'll have to do a lot more of this.
KING GEORGE V I'm sending him to the Midlands.
KING GEORGE V With all the factory noise they won't hear a word he says.
The King goes back to waving.
Elizabeth is stunned at the prospect.
The ROAR of the crowd segues into the ROAR of machinery.
Huge industrial wheels whir in neutral.
WORKERS are lined up dutifully to hear the visiting Royal.
Bertie's lips move, but with the noise he cannot be heard.
Elizabeth watches in relief.
Then a FOREMAN, trying to be helpful, signals.
The machinery halts, the factory falls silent.
TKS/Seidler/09/17/08 18.
At first the momentum of speaking without being heard carries Bertie forward.
BERTIE What's needed is cooperation...
Hearing his own voice reverberate through the cavernous factory brings Bertie's stutter back in full form.
BERTIE (CONT'D) ...buh-buh-between the cuh-cuh-classses...
One of the workers sullenly pulls a chain, releasing a blast from a steam whistle that drowns Bertie out.
THE ROYAL STANDARD fluttering.
Elizabeth and Bertie in the back.
BERTIE Is this necessary?
ELIZABETH You know perfectly well.
As they pass a corner news stand, the headline chalkboard reads:
ELIZABETH (CONT'D) Neglects to tell them what must be done, how its to be done, and who's to do it.
BERTIE David has `the touch'.
BERTIE They adore him.
As the Austin halts for lights, people stare to see who's inside.
Some point.
BERTIE (CONT'D) I'll wager they're saying: There's the useless one who can't speak.
Bertie and Elizabeth enter.
She explains in a whisper: TKS/Seidler/09/17/08 19.
ELIZABETH There's no receptionist.
Elizabeth glances nervously at the lavatory door.
ELIZABETH (CONT'D) The Johnsons.
From the inner office.
LIONEL Not finished yet.
Elizabeth is relieved its not coming from the lav.
BERTIE How'd you find this physician?
ELIZABETH Classifieds; next to "Saucy model, Shepherd's Market".
Bertie smiles despite his mood.
ELIZABETH (CONT'D) Comes highly recommended.
ELIZABETH (CONT'D) Charges substantial fees in order to help the poor.
ELIZABETH (CONT'D) Oh dear, perhaps he's a Bolshevik?!
BERTIE I'm not sure I want to see this fellow.
ELIZABETH I'm not sure he wants to see you.
The consultation room door opens and a working class young woman - ANNA - comes out; then realizes with a gasp who they are.
She retreats rapidly back into the consulting room.
ELIZABETH (CONT'D) Perhaps this was a mistake.
After an uncomfortable moment, Anna returns, attempting to be properly formal, and stutters:
ANNA You can go in now, "Mr.
ANNA Johnson".
BERTIE I'm not actually Mr ...
TKS/Seidler/09/17/08 20.
ANNA I know.
ANNA Dr Logue says...
LIONEL Lionel!
ANNA Lionel says...wait here if you wish.
ANNA Or, it being a pleasant day, take a stroll.
ANNA Was that alright?
LIONEL Bloody marvellous.
ANNA Thank you...Lionel.
Anna flees quickly.
LIONEL Mr. Johnson, do come in.
The Yorks look at each other.
A totally different universe from the Spartan waiting area.
A world of books - piles of them spilling everywhere.
Two slightly shabby, but comfortable armchairs.
Well-worn Turkish rug.
Hotplate and two chipped mugs.
Model airplanes hanging from the ceiling.
Recording apparatus.
The walls are pearl grey and smoky blue.
BERTIE My wife's favorite colours.
Here, in a doctor's office, Bertie's stutter returns.
LIONEL Glad we have something in common.
Bertie's head bangs into one of the models.
LIONEL (CONT'D) My lads build them.
LIONEL (CONT'D) Make yourself comfortable.
TKS/Seidler/09/17/08 21.
BERTIE Please...
LIONEL What?
BERTIE You're too close.
BERTIE Five paces is the rule of thumb.
LIONEL That might be difficult in this office.
Bertie perches uneasily on the edge of an armchair.
LIONEL (CONT'D) Nice girl, Anna.
LIONEL (CONT'D) Worried she wouldn't find a husband if she couldn't speak.
LIONEL (CONT'D) Tried to convince her men will find her even more attractive as a silent partner.
LIONEL (CONT'D) The perfect woman.
LIONEL (CONT'D) Sorry, bad Australian joke.
LIONEL (CONT'D) Why'd your wife change her mind and ask for an appointment?
BERTIE I can't discuss that.
LIONEL What can we talk about?
BERTIE That's better.
BERTIE When speaking with a Royal one waits for the Royal to start the conversation and chose the topic.
LIONEL Your joking.
LIONEL That won't work here.
BERTIE I admit if one waits for me to start a conversation one can wait a rather long time.
Silence.
They stare at each other.
BERTIE (CONT'D) You call this making me comfortable?
LIONEL You call this being forthcoming?
BERTIE Aren't you interested in treating me?
TKS/Seidler/09/17/08 22.
LIONEL Only if you're interested in being cured.
More silence.
LIONEL (CONT'D) Cuppa tea?
BERTIE No thank you.
LIONEL I need one.
Turns on the hot plate.
LIONEL (CONT'D) Any idea what you're letting yourself in for?
BERTIE Apparently a great deal of rudeness, Doctor Logue.
LIONEL Call me Lionel.
BERTIE I prefer Doctor.
LIONEL I prefer Lionel.
LIONEL My family calls me far worse.
LIONEL What shall I call you?
BERTIE The Duke of York is appropriate.
LIONEL Oh please.
BERTIE Your Royal Highness then.
LIONEL Much more informal.
BERTIE Prince Albert?
BERTIE Or Frederick?
BERTIE Arthur?
BERTIE George?
BERTIE I've lots of names to choose from.
LIONEL How about Bertie?
TKS/Seidler/09/17/08 23.
BERTIE Only my family uses that.
LIONEL That's what I'll call you then.
LIONEL We must be true equals.
BERTIE If we were equal I wouldn't be here, I'd be at home with my family and no-one would give a damn.
Bertie starts to light a cigarette from a silver case.
LIONEL Don't do that.
Bertie gives him an astonished look.
LIONEL (CONT'D) Sucking smoke into your lungs will kill you.
BERTIE My physicians say it's good for stuttering, relaxes the throat.
LIONEL They're idiots.
BERTIE They've all been knighted.
LIONEL Makes it official then.
LIONEL House rules: no smoking.
BERTIE I thought here we're "equal".
LIONEL As a monarchist I thought you'd appreciate these are my digs and here I rule.
LIONEL No smoking.
LIONEL What was your earliest memory?
BERTIE I beg your pardon?
LIONEL First recollection of the world?
TKS/Seidler/09/17/08 24.
BERTIE I'm not here to discuss personal matters.
LIONEL Why're you here then?
BERTIE Because I bloody well stutter!
BERTIE And you bloody well can't fix it!!!
LIONEL Temper.
BERTIE One of my numerous faults.
LIONEL Do you stutter when you think?
BERTIE Don't be ridiculous.
LIONEL One of my many faults.
LIONEL How about when you talk to yourself?
BERTIE I don't talk to myself!
LIONEL Come on, everyone natters to themselves once in a while, Bertie.
BERTIE Stop calling me that!
LIONEL Shan't call you anything else.
BERTIE Then we shan't speak!
Silence.
The jug has boiled.
Lionel makes himself a cup of tea.
BERTIE (CONT'D) Must I pay for this?
LIONEL Loads.
LIONEL Now: when you talk to yourself, do you stutter?
TKS/Seidler/09/17/08 25.
BERTIE Of course not!
LIONEL Proving your impediment isn't a permanent internal fixture.
BERTIE When I give a speech...I bloody stutter!!!
LIONEL Bet you a bob you can read flawlessly, right here, right now.
BERTIE Easy money.
BERTIE You're on.
LIONEL See your shilling then.
BERTIE Royals don't carry money.
LIONEL How convenient.
Logue fishes a coin from his pocket and puts it on the table.
LIONEL (CONT'D) I'll stake you.
LIONEL (CONT'D) Pay me back next time.
BERTIE If there is a next time.
LIONEL Correct, I haven't agreed to take you on.
During this, Logue has uncovered a piece of apparatus, a recording device with earphones.
He sets a blank disc onto the turntable and positions a microphone, then hands Bertie an open book.
Bertie glares at it defiantly.
BERTIE I certainly can't read The Bard.
LIONEL `Easy money'.
Bertie reads, stuttering badly and getting worse.
BERTIE "To be or not to be, That is the question.
BERTIE Whether it is wiser..."
BERTIE There!
TKS/Seidler/09/17/08 26.
Reaches for the coin.
LIONEL Not so fast.
BERTIE I proved I can't read.
LIONEL You proved you can't listen.
Hands Bertie a pair of heavily padded earphones.
Bertie doesn't want to take them.
LIONEL (CONT'D) A princely bob is at stake.
Bertie reluctantly puts on the earphones.
Logue turns a dial.
LOUD MUSIC is heard.
Bertie takes off the earphones.
The music stops.
BERTIE You're playing music.
LIONEL I'm aware.
BERTIE How can I hear what I'm saying?!
LIONEL Bertie, you're Royal.
LIONEL Surely a prince's brain knows what its mouth is doing?
BERTIE You're not well acquainted with Royal princes, are you?
LIONEL I want to demonstrate that when you can't hear your voice, you don't stutter, thus proving your impediment is not innate.
BERTIE Rubbish.
Bertie replaces the earphones.
Again, the LOUD MUSIC.
His lips move as he reads, but all that can be heard is the music.
Finished reading the passage he takes off the earphones and the music ceases.
He reaches for the coin, but Logue snatches it.
BERTIE (CONT'D) I was terrible.
TKS/Seidler/09/17/08 27.
LIONEL Flawless.
BERTIE I know how I sound!
LIONEL Would I lie to a prince of the realm to win twelve-pence?
BERTIE I've no idea what an Australian might do for that sort of money.
Logue puts the record in a brown paper dust jacket and hands it to Bertie.
LIONEL Souvenir of our first and presumably last encounter.
Bertie glances at the record.
POV - the label: HMV His Master's Voice.
Elizabeth, trying to be gracious, has been cooling her heels with a working class MOTHER and her young son WILLIE.
LIONEL I'm finished with your husband.
BERTIE I'm finished with Doctor Logue!
LIONEL Lionel.
They exit curtly.
WILLIE'S MUM Was that...?
LIONEL Certainly not.
LIONEL How's it going, mate?
WILLIE'S MUM William isn't trying hard enough.
LIONEL Willie?
TKS/Seidler/09/17/08 28.
WILLIE Ddddddoooing ggggggggood.
LIONEL Why am I not surprised?
The Yorks are being driven home.
As they pass Speakers' Corner, Oswald Mosley's blackshirt British Union of Fascists are out in full force.
BERTIE The bloody man did parlour tricks and cheated me out of a shilling.
In fury he rolls down the window and is about to throw away the record.
Elizabeth stops him.
ELIZABETH They'll see.
He quickly rolls up the window.
The sound of an approaching aircraft engine.
A grass strip cut into the moors.
Bertie waits beside a shooting break, the stiff breeze whipping his coat, as a small plane lands and taxis.
The cockpit canopy slides back and the pilot leaps out, removing his leather helmet and goggles, revealing hair gleaming like gold, perfect teeth flashing a dentist's smile.
This is - DAVID - the Prince of Wales, Prince Charming, the media's darling, a sun god descended from the skies accustomed to being worshipped by all.
DAVID Hello, B-b-bertie.
DAVID B-b-been waiting long?
BERTIE Three days.
BERTIE Where've you been?
Bertie stutters badly in the presence of his brother.
DAVID I was busy.
BERTIE So was I. Elizabeth has pneumonia.
TKS/Seidler/09/17/08 29.
DAVID She'll recover.
Bertie shoots him a look.
BERTIE Father won't.
David drives.
Badly.
DAVID He's doing this on purpose.
BERTIE Dying?!
DAVID Some sod tipped him off Wallis is getting a quickie divorce and we're going to make our marriage a fait accompli.
DAVID As an act of pure spite, Father's trying to depart prematurely in order to complicate matters.
The break almost careens off the lane.
BERTIE You believe that?
DAVID Wallis explained it.
DAVID She's terribly clever.
The King is propped up in bed, wrapped in his favorite faded Tibetan dressing gown, hooked to an oxygen tank.
He's surrounded by his wife, Queen Mary, his two eldest sons, his Secretary - CLIVE WIGRAM - his personal physician - DR DAWSON, and a NURSE.
Wigram presents a tray with papers and pen.
WIGRAM The Instruments Of Succession, Your Majesty.
The King is so feeble he can barely make his mark.
Glares at David.
KING GEORGE V You're next?
KING GEORGE V God help us.
TKS/Seidler/09/17/08 30.
He waves them out of the room, but beckons Wigram to come close, and whispers something in his ear.
WIGRAM At the appropriate moment, Your Majesty.
The King nods.
Clear soup is being served at the immense table.
Places set for five, but only Bertie and his mother are seated.
The clinking of silver and china.
Finally:
QUEEN MARY I want my jewelry divided equally.
QUEEN MARY Elizabeth gets first choice.
QUEEN MARY She's not greedy.
BERTIE May I remind you, you're not the one who's dying, Mother.
QUEEN MARY Where are the others?
BERTIE Lord Wigram and Dr Dawson are making arrangements.
QUEEN MARY What sort of arrangements?
BERTIE They didn't say.
QUEEN MARY And David?
QUEEN MARY Fetch him.
David, hunched over a table, appears to be sobbing.
He doesn't hear Bertie's discreet knock.
Seeing his brother crying, Bertie is deeply moved, puts a comforting hand on his shoulder.
David pulls away as though touched by a leper and covers the receiver in his hand.
DAVID I'm on with Wallis!
TKS/Seidler/09/17/08 31.
DAVID (CONT'D) I know, darling, a talk, even a lovely long talk, is a poor substitute for holding tight and making drowsy.
DAVID (CONT'D) Nor making our own drowsies either, as we've had to do far too often lately.
DAVID (CONT'D) Til then, sweet love.
DAVID (CONT'D) Wally misses me terribly
BERTIE Mother says you're late for supper.
David glares at a clock.
DAVID Clocks set five minutes in advance, so as not to be late.
DAVID When I'm King I shall set them back!
Bertie and David enter to find Wigram and Dawson with their mother.
QUEEN MARY Lord Wigram has requested permission to order the coffin.
Nobody wants to take responsibility.
The Queen looks to David.
He nods.
They're interrupted by a BUTLER.
BULTER The Archbishop of Canterbury.
DAVID Who the hell invited him?!
QUEEN MARY Nobody.
QUEEN MARY Don't swear.
DAVID Somebody should bloody well dis-invite him.
DAVID Father swears.
WIGRAM That would be rash.
QUEEN MARY You're not your father.
TKS/Seidler/09/17/08 32.
WIGRAM His Grace can be a persistent enemy.
WIGRAM We need friends.
David knows he's referring to the Simpson affair.
DAVID Show the toad in.
Lang is already sweeping towards them.
COSMO LANG Whatever can I contribute in this dreadful hour?!
The men are huddled, with cigars and port, composing a news release.
Bertie acts as secretary.
COSMO LANG "Tranquilly"?
COSMO LANG "Serenely"?
WIGRAM Peacefully.
The others nod.
COSMO LANG "The King's life is moving peacefully to its..."
COSMO LANG "Termination"?
WIGRAM Close.
COSMO LANG "...to its close."
WIGRAM As a man of letters you're heaven-sent to assist in the editing of our press communique.
Lang beams.
WIGRAM (CONT'D) I'll telephone this through to the BBC and alert The Times to hold the morning edition.
WIGRAM (CONT'D) The problem is...if we're to keep to schedule...time is running out.
The clock is approaching midnight.
TKS/Seidler/09/17/08 33.
DAVID Is my father late for death?
WIGRAM We wouldn't want the news delivered by the disreputable afternoon press, would we?
The brothers look at him.
He expains:
COSMO LANG Who knows what sensational side issues those tabloids might report.
DAWSON Perhaps a peaceful termination?
All eyes on David.
The nurse looks aghast as Dr Dawson administers an injection.
DAWSON Three quarters of a gram of morphia and a gram of cocaine injected into the distended jugular vein.
NURSE No!
NURSE that's...
DAWSON You may leave.
She does so, sobbing.
Everyone watches silently as the King's breathing slows, the twitching jugular subsides, then all movement ceases.
Dawson takes the pulse, and consults his watch.
David sets the hand of the room's big clock back by five minutes.
DAWSON (CONT'D) Time of expiration, 11:55 pm.
DAWSON (CONT'D) On schedule.
Queen Mary curtsies in homage to the new King, taking her eldest son's hand and kissing it.
When she looks up...her eyes are chilling.
QUEEN MARY Long live the King.
TKS/Seidler/09/17/08 34.
Bertie, in despair and grief, has been describing to Elizabeth what happened.
BERTIE The look in mother's eyes, it was...ghastly.
He notices something on his desk, the record Logue made.
POV: the label - His Master's Voice - stares up at him.
He releases his emotions in an outburst of anger.
BERTIE (CONT'D) What's this bloody thing doing here?!
ELIZABETH Bertie...
BERTIE The man was a total fraud!
He picks up the record and is about to smash it against the edge of his desk, then realizes the mess that would make and tosses it into a waste paper basket.
Then changes his mind.
BERTIE (CONT'D) Would you like to hear?
ELIZABETH Not particularly.
BERTIE Well I think you should.
BERTIE You should know what goes on.
BERTIE Telling me he could help me read flawlessly.
BERTIE Lying bastard!
BERTIE Listen to this babble!
Bertie takes the record from the trash and walks to a Victrola stand, lifts the arm, places the steel needle, expecting to hear his stuttering voice.
Instead, what he hears is flawless and flowing:
BERTIE'S RECORDED VOICE "To be, or not to be, - that is the question: - Whether `tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles, And by opposing end them?"
TKS/Seidler/09/17/08 35.
BERTIE'S RECORDED VOICE (CONT'D) "...sea of troubles, and by opposing end them?
BERTIE'S RECORDED VOICE (CONT'D) And by opposing end them?
BERTIE'S RECORDED VOICE (CONT'D) And by opposing..."
Bertie lifts the needle.
He and his wife stare at each other; there are tears in her eyes.
The ROAR OF A HUGE delirious crowd is heard, growing in volume.
The roar becomes chillingly recognizable: "Zeig Heil!
Zeig Heil!
Zeig Heil!"
Hitler, giving one of his mass rally speeches, continues.
The brass numbers 10 appears on the blackness.
It is:
The black front door of the Prime Minister's residence.
The Fuhrer's tirade continues as CAMERA moves through the door into 10 Downing Street itself.
CAMERA explores the dwelling, during which Hitler grows louder and more shrill, until:
The glowing light of an illuminated dial of a radio, listened to by Churchill and Baldwin.
They wear black armbands.
WINSTON CHURCHILL Turn that devil off!
The hysteria stops.
WINSTON CHURCHILL (CONT'D) If only one could do that so easily in real life.
BALDWIN Chamberlain thinks that Hitler can be reasoned with.
WINSTON CHURCHILL Neville is an old woman.
TKS/Seidler/09/17/08 36.
BALDWIN That's the direction its going, Winston.
BALDWIN You're out of step.
WINSTON CHURCHILL We'll see who trips and falls.
BALDWIN Enough pleasantries.
BALDWIN I've asked you here because you seem to be the only sensible member of the King's camp.
WINSTON CHURCHILL Nice of you to say so, Stanley.
BALDWIN Is he willing to be reasonable?
WINSTON CHURCHILL Depends on the definition.
BALDWIN Has he seen the light?
WINSTON CHURCHILL He has.
Baldwin brightens.
WINSTON CHURCHILL (CONT'D) Our Monarch basks in the warming rays of a celestial orb.
WINSTON CHURCHILL (CONT'D) Her name is Wally.
Baldwin's face clouds once again.
A headline screams: HITLER RATTLES SABRE.
Lionel is at his desk reading the newspaper as his sons sprawl on the floor building a model airplane.
VALENTINE Dad?
LIONEL Mmmm?
VALENTINE Time for a Shake, dad.
TKS/Seidler/09/17/08 37.
LIONEL You sure?
THE BOYS Shake!
THE BOYS Shake!
THE BOYS Shake!
Clearly this is a much loved ritual.
Lionel disappears into a closet.
IAN Bet its the Scottish Play.
VALENTINE Othello!
PETER Perhaps something with Falstaff?
Ominous thumps within the closet.
LIONEL (FROM INSIDE THE CLOSET) "Art thou afeard?"
THE BOYS Caliban!
Lionel lumbers out of the closet, a pillow stuffed into his jacket to create a monstrous hunchback.
His acting, performed just for his children, is quite magical.
LIONEL "Be not afeard; the isle is full of noises, Sounds and sweet airs, that give delight, and hurt not.
LIONEL Sometimes a thousand twanging instruments Will hum about mine ears; and sometimes voices, That, if then I had waked after long sleep, Will make me sleep again: and then, in dreaming, The clouds methought would open, and show riches Ready to drop upon me; that, when I waked, I cried to dream again."
The lads are enthralled.
The DOOR BELL RINGS.
Lionel is not expecting anyone.
The Austin Princess waits at the curb.
Bertie is at the door.
He rings the BELL again.
TKS/Seidler/09/17/08 38.
BERTIE'S VOICE Doctor Logue?
Lionel is stunned, covers:
LIONEL Must be a tradesman.
LIONEL Off you go, lads.
LIONEL Mum should be home from work.
The boys gather their things, deposit the model plane on a chair, stow the building materials in a box, and exit the back way.
Lionel goes to the door, but doesn't open it.
BERTIE'S VOICE Logue...?
Logue, expressionless, doesn't respond.
Bertie is torn: part of him wants to flee, yet he desperately needs to be let in.
He knows what must be done.
This is a huge step for him.
BERTIE Lionel...it's Bertie.
The door opens.
LIONEL My condolences.
LIONEL I didn't expect you.
BERTIE Thank you.
BERTIE I didn't expect to be here.
BERTIE May I come in?
LIONEL No.
BERTIE What?
LIONEL My wife doesn't think it's a good idea.
BERTIE Your wife?
LIONEL Myrtle.
TKS/Seidler/09/17/08 39.
BERTIE Myrtle?
BERTIE Myrtle's never met me.
BERTIE I've never met Myrtle.
BERTIE May we discuss Myrtle in private?
BERTIE Its not proper talking about our women on the street.
Lonel gives him a look, but lets him him.
As they enter Bertie notices:
BERTIE What happened to your shoulder?
Lionel hastily removes the pillow, tosses it away.
LIONEL Sore back.
BERTIE What's your Myrtle got to do with me?
BERTIE Elizabeth doesn't much care for you either, but here I am.
LIONEL That woman has style.
BERTIE Which is why she dislikes you.
BERTIE You're far too familiar.
BERTIE May we discuss this properly?
They enter:
LIONEL You look dreadful.
BERTIE Another example of exactly the sort of thing you don't say to a Royal.
BERTIE And you're too close.
LIONEL But you're not Royal in this room.
TKS/Seidler/09/17/08 40.
BERTIE Which is precisely why Elizabeth dislikes you.
He starts to sit.
LIONEL Not there!
CRUNCH.
A model airplane was nestling in the armchair.
LIONEL (CONT'D) Curtis bi-plane, now a Curtis mono-wing.
BERTIE Oh I say, I'm terribly sorry.
BERTIE Tell your lads I'll buy a new one.
Lionel takes out the box of model building gear the boys left.
LIONEL You don't have any money.
LIONEL I'll fix it.
LIONEL So, Bertie, what brings you here?
LIONEL Your father's death?
Bertie is silent.
LIONEL (CONT'D) Mine lay rigid, fists clenched angrily at his sides, daring the Reaper: take me, you bastard!
BERTIE What was he angry about?
LIONEL I was a great disappointment.
BERTIE Thought he'd be proud of you.
LIONEL So did I.
BERTIE A man of stature?
LIONEL A clerk.
BERTIE Oh.
TKS/Seidler/09/17/08 41.
BERTIE (CONT'D) I was informed, after the fact, my father's last words were: "Bertie has more guts than the rest of his brothers put together."
BERTIE (CONT'D) Couldn't say that to my face.
BERTIE (CONT'D) Your mother?
LIONEL Coughed herself to death when I was young.
BERTIE Oh.
LIONEL I remember going to the theatre with her.
LIONEL Not real theatre...traveling players.
BERTIE I've been to Australia.
LIONEL Not where I lived.
BERTIE My brother.
BERTIE That's why I'm here.
LIONEL What's he done?
BERTIE Can't say.
LIONEL I'm going home now.
BERTIE You must undersand, I can't puh-puh-puh...
His jaw and throat muscles constrict.
LIONEL Try singing it.
BERTIE Pardon?
LIONEL Know any songs?
BERTIE "Swanee River".
TKS/Seidler/09/17/08 42.
LIONEL Very modern.
BERTIE Happens to be my favorite.
LIONEL Sing it.
BERTIE Certainly not.
BERTIE May I help?
BERTIE Always wanted to build models.
BERTIE Father wouldn't allow it.
BERTIE I had to collect stamps.
BERTIE He collected stamps.
LIONEL Only if you sing.
LIONEL Goes like this...
LIONEL "Way down upon the..."
BERTIE I know the words!
BERTIE "Way down upon the Swanee River.
BERTIE ..."
BERTIE Etcetera.
LIONEL You didn't stutter.
BERTIE Of course I didn't stutter, I was singing!
BERTIE One doesn't stutter when one sings!
BERTIE Oh...
BERTIE Well I can't waltz around on State occasions warbling!
LIONEL You can with me.
BERTIE That's because you're peculiar.
LIONEL I take that as a compliment.
LIONEL Cut some struts from the balsa.
LIONEL Sorry, hard to show you what to do at five paces.
LIONEL Would you like a cup of tea?
BERTIE No.
BERTIE Yes.
BERTIE Thank you.
TKS/Seidler/09/17/08 43.
Lionel fires up the hot plate.
LIONEL You were about to sing an aria concerning your brother.
BERTIE I'm not crooning to the tune of "Swanee River!"
LIONEL Try "Camptown Races" then.
LIONEL "The Arch of C, he said to me, doo-dah doo- dah..."
LIONEL That sort of thing.
BERTIE I can't talk, or sing, about your future King, doo-dah, doo-dah...
LIONEL My future King?
LIONEL He's your future King too.
LIONEL Did that cause friction?
LIONEL Knowing he'd grow up to be King, but you wouldn't.
BERTIE Certainly not.
BERTIE I've always looked up to David.
BERTIE Water's boiling.
Lionel makes the pot.
LIONEL Two lumps or one?
Bertie, a bit abashed, holds up three fingers.
BERTIE I've a sweet tooth.
BERTIE To tell the truth...
LIONEL Always preferable.
LIONEL Cover it with tissue.
BERTIE ...it was a relief.
BERTIE Knowing I wouldn't be King.
LIONEL Why's that?
Lionel hands him a mug of tea.
Bertie realizes it's chipped and possibly none too clean.
TKS/Seidler/09/17/08 44.
BERTIE I wouldn't have to give speeches!
Reaches into his jacket for his cigarette case.
LIONEL No smoking.
LIONEL What's the age difference?
While Logue isn't looking, Bertie surreptitiously wipes the rim of the mug with his handkerchief.
BERTIE Eighteen months.
LIONEL But for eighteen months you would've been King?!
BERTIE We didn't think about it that way, doctor.
BERTIE Doo-dah doo-dah.
BERTIE David and I were very close.
LIONEL As you said: eighteen months.
BERTIE As brothers!
LIONEL How close?
BERTIE Young bucks...
BERTIE You know.
LIONEL I don't, or I wouldn't ask.
LIONEL Did you go after the same girls?
BERTIE Upon occasion.
LIONEL Princess Elizabeth?
BERTIE What an extraordinarily rude thing to say!
BERTIE David did try to be her beau at one point.
BERTIE Before I met her.
BERTIE She wouldn't have him.
TKS/Seidler/09/17/08 45.
BERTIE (CONT'D) Not like my father...he and his brother, when they were young, kept a girl in St John's Wood and shared her on alternate nights.
An uncomfortable silence.
Too much has been said.
LIONEL Now dope the other wing.
LIONEL Did David tease you?
BERTIE They all did.
BERTIE "Buh-buh-buh-Bertie".
BERTIE Father encouraged it.
BERTIE "Spit it out, boy!" Thought it would make me stop.
BERTIE Is this necessary?!
LIONEL Otherwise the paint will eat through the tissue.
BERTIE I mean the damn questions!
LIONEL Mandatory.
LIONEL Tell me more about your storybook childhood.
LIONEL What was your earliest memory?
BERTIE You asked that before.
LIONEL This time I'd like an answer.
BERTIE Being born.
LIONEL How can you remember that?
BERTIE December 14th.
LIONEL I don't understand.
BERTIE "Mausoleum Day".
BERTIE Prince Albert departed on that date.
BERTIE I was named Bertie to placate Great Grandmamma Victoria.
BERTIE In return, she hated me because it reminded her of her grief.
TKS/Seidler/09/17/08 46.
BERTIE (CONT'D) Let's stick to medical history please.
BERTIE (CONT'D) I'm naturally left handed, which was considered inappropriate.
LIONEL And?
BERTIE I was punished.
BERTIE Now I'm right handed.
LIONEL Anything else?
BERTIE Bandy legs.
BERTIE Also considered inappropriate.
Lionel waits.
BERTIE (CONT'D) Metal splints were made...worn night and day...very painful.
BERTIE (CONT'D) Now I have straight legs.
BERTIE (CONT'D) This is so...tawdry!
BERTIE (CONT'D) I need your services as a Speech Therapist, not Grand Inquisitor.
BERTIE (CONT'D) Are you available?
BERTIE (CONT'D) Or will it be: "Myrtle says no?"
LIONEL You sound angry.
BERTIE Yes, I told you, I have a temper.
LIONEL Angry at me, or at your brother?
Bertie remains stubbornly silent.
Then blurts:
BERTIE He's fallen in love!
LIONEL How dreadful.
BERTIE With the wrong sort of woman!
LIONEL What's wrong with her?
BERTIE She's American.
LIONEL Some of them must be lovable.
TKS/Seidler/09/17/08 47.
BERTIE This one's divorced.
BERTIE Twice.
BERTIE Mrs Wallis Simpson of Baltimore.
BERTIE I want David to be happy, but the family, the Church, the nation, won't have it.
LIONEL Can't they fornicate privately like adults?
BERTIE If only!
BERTIE David used to prefer married women because there was no possible attachment.
BERTIE But now...
LIONEL "Queen Wallis of Baltimore"?
BERTIE Please.
LIONEL Does sound a bit iffy.
BERTIE I made a smudge!
LIONEL Touch it up.
BERTIE You want me to beg for help?
LIONEL I advise you never to beg.
LIONEL Especially if you might be King.
BERTIE Don't say that!
LIONEL I see.
LIONEL For reasons you cannot disclose, fearing ramifications you will not explain, you feel sufficiently anxious to embark upon a course of therapy in which you have no faith?
LIONEL You already owe me a shilling.
Bertie takes a coin out of his pocket, hesitates, then offers it to Logue.
BERTIE I brought it along.
BERTIE You won, fair and square.
BERTIE I'll pay you generously.
Lionel pockets the coin.
TKS/Seidler/09/17/08 48.
LIONEL I'll continue to ask questions.
BERTIE That's what I was afraid of.
LIONEL Nice job.
Bertie sees Lionel glance at his watch.
BERTIE You've someone waiting?
LIONEL I do now.
BERTIE I'd apologize to them in person, but...
LIONEL You don't wish to be seen?
LIONEL Slip out the back way.
BERTIE After the funeral...it may be even more difficult.
BERTIE To remain unobserved.
LIONEL You're having second thoughts.
Bertie's silence is confirmation.
LIONEL (CONT'D) I ask too many questions?
BERTIE Perhaps the wrong sort.
LIONEL We live in South Kensington, small apartment, but no one would see you.
LIONEL Lots of planes.
BERTIE You know, Lionel, you're the first ordinary Englishman...
LIONEL Australian.
TKS/Seidler/09/17/08 49.
BERTIE ...I've ever really talked to.
BERTIE Sometimes, when I ride through the streets and see a `bloke' I'm struck by how little I know of his life, and how little he knows of mine.
BERTIE Cuts both ways.
As Bertie is about to leave, Lionel requests casually:
LIONEL And if you decide to come, bring the Duchess.
LIONEL She might be helpful.
BERTIE She might.
BERTIE If I asked.
BERTIE Very nicely.
BERTIE And how will Myrtle take to our coming into your home?
LIONEL Not sure.
LIONEL She isn't speaking to me.
LIONEL Wants to go home.
LIONEL After the funeral then?
Bertie doesn't answer.
Exits.
Logue is left holding the plane.
He goes to the waiting room door.
LIONEL (CONT'D) How're you doing, Willie?
WILLIE'S MUM Still can't say a sentence.
LIONEL Willie?
WILLIE Iiiiiii'm much bbbbbbbetter.
LIONEL Well done.
A drum roll is heard.
Thrum.
Another...
Thrum!
Thrum!
Funereal bagpipes wail, joining the measured drum-rolls.
TKS/Seidler/09/17/08 50.
On the balcony of the Castle, decorated with black bunting, is a huge BBC microphone, and arrayed in front of it a row of uniformed dignitaries wearing Naval hats of the Napoleonic Wars, replete with ostrich feathers.
One of the dignitaries reads a declaration:
DIGNITARY Whereas it has pleased Almighty God to call to His mercy our late Sovereign, King George the Fifth of blessed and glorious memory...
During this, INTERCUT to the REVERSE ANGLE, showing a massive military parade, mainly Navy personnel, wending its way through the main street of Windsor towards the Castle, accompanying a gun carriage on which rides the King's coffin, draped with the Royal standard, on which rests the Royal Crown topped by a Maltese Cross.
David is seen - very serious.
DIGNITARY (CONT'D) ...that the High and Mighty Prince Edward Albert Christian George Andrew Patrick David is now become our only lawful King.
Canons are fired.
Startled by the salute, a large flock of blackbirds rise up and streak across the wintery sky.
A MURMUR, then a shocked GASP, as the gun carriage transverses a tram track and tilts precipitously.
Suddenly the Royal Crown tumbles and falls, knocking off the Maltese Cross.
COSMO LANG (O.C.) Oh bloody Hell!
WINSTON CHURCHILL (O.C.) A bad omen, Your Grace?
The Archbishop and Churchill are watching the events from the shadows at one end of the balcony.
Below - a scramble to restore the Cross to the Crown, and replace both atop the coffin.
COSMO LANG Don't be disingenuous.
COSMO LANG For our late King's crown to fall from his coffin is not a fortuitous portent.
COSMO LANG What ever is going to happen next?
TKS/Seidler/09/17/08 51.
WINSTON CHURCHILL Is that be the motto of the new reign?
WINSTON CHURCHILL Indeed, will there actually be "a new reign"?
COSMO LANG Winston!
COSMO LANG I'm deeply shocked.
WINSTON CHURCHILL You don't look it.
COSMO LANG My function requires me to appear serene.
WINSTON CHURCHILL That may be increasingly difficult to maintain.
WINSTON CHURCHILL I've been informed by no less an authority than the Prime Minister that our populace has no objection to Royal fornication, but will never tolerate adultery.
COSMO LANG Well, since we cannot acquire a new populace, perhaps we need a new King?
WINSTON CHURCHILL My turn to be profoundly shocked.
Neither look the slightest traumatized.
COSMO LANG Scoff, Churchill!
COSMO LANG Go on...
COSMO LANG scoff!
COSMO LANG But you more than others know full well we'll soon be under siege from the forces of darkness.
WINSTON CHURCHILL The winds of war...a gathering storm?
COSMO LANG Oh, you do have a way with words.
COSMO LANG And who would you suggest to rally the troops, the nation, the Empire, the world?
INTERCUT to Bertie in the funeral cortege, looking frail and pale.
COSMO LANG (CONT'D) A man who cannot speak?
COSMO LANG (CONT'D) In Nuremberg stadium, Herr Hitler mesmerizes millions, whilst the Duke of York cannot successfully order fish and chips.
TKS/Seidler/09/17/08 52.
WINSTON CHURCHILL Would you prefer the next brother?
INTERCUT to Henry, the Duke of Gloucester.
WINSTON CHURCHILL (CONT'D) A bi-sexual former drug addict?
WINSTON CHURCHILL (CONT'D) The unwashed moralistic populace will adore that!
COSMO LANG The youngest, perhaps?
INTERCUT to George, the Duke of Kent.
WINSTON CHURCHILL Now there's dimness.
COSMO LANG I must admit...unburdened with brain.
WINSTON CHURCHILL Thus we're left with David, the rightful heir, who speaks beautifully, even if he talks nonsense.
Below, the coffin is entering the Chapel.
WINSTON CHURCHILL (CONT'D) Come, let us bury one king, before we attempt to bring another to his knees.
They exit.
Re-establishing shot.
The Royal standard flies bravely.
Bertie waits at a table with a group of immaculately attired courtiers and dignitaries.
This is the Coronation Committee.
The chair at the head of the table is empty, everyone waiting for its occupant.
He finally arrives.
David.
He gestures for Bertie to come into the corridor, but deliberately leaves the door open so the committee can hear snatches of Bertie's ensuing humiliation.
TKS/Seidler/09/17/08 53.
David has a habit of constantly fingering his tie.
DAVID Hear you're taking elocution lessons, lad.
BERTIE Pardon?
DAVID Diction.
DAVID Speechifying.
DAVID That's the word around Town.
BERTIE Merely trying to overcome my dreadful impediment...
DAVID (OVER-RIDES) I'm the brother who speaks.
DAVID (OVER-RIDES) Or do you wish to have a go?
BERTIE Good lord no!
BERTIE I hope to...
DAVID Replace me?
DAVID Well...today's your chance.
He thrusts a document into Bertie's hands, then pokes his head into the conference room.
DAVID (CONT'D) My brother will read the Coronation Plans.
BERTIE I'm not prepared!
DAVID As a Boy Scout...and you are one, aren't you, very much a Boy Scout...you must always be prepared.
DAVID Nice and loud, so everyone can hear.
Bertie looks at the pages, his throat constricts, his chest tightens and his hands begin to shake.
BERTIE I...I...I thu-thu-think we should tuh-tuh- table the document.
He attempts to return it to David, but his brother won't accept.
TKS/Seidler/09/17/08 54.
DAVID Tell the others how Mrs Simpson is to be accommodated in a special alcove above the altar.
DAVID Now I'll be off.
DAVID See you at Balmoral this weekend, Buh-buh-Bertie.
In the room, they are appalled.
Bertie stands frozen and shattered.
The lion rampant flutters on the bonnet of the Austin.
Inside, Bertie, wearing a black armband, gestures for the driver to stop.
Pulling his homburg over his brow, Bertie wraps his scarf around the lower portion of his face.
Then catches his reflection in the rearview mirror.
Tells his driver:
BERTIE Wait down the road.
Not wanting to draw attention to his destination, Bertie has disembarked several buildings away from Logue's address.
He makes his way hurriedly.
WACK.
A soccer football hits him on the back.
He wheels around.
The group of local lads look at him unabashed.
LOCAL LAD Kick it `ere, aye, Guv?
Bertie kicks it.
A fine high shot.
LOCAL LAD (CONT'D) Nice one.
They go back to their game.
Bertie rings Logue's bell.
A brief pause.
Bertie glances nervously, hoping not to be recognized.
Lionel opens the door.
LIONEL To be honest, wasn't sure whether to expect you.
BERTIE I wasn't sure either.
TKS/Seidler/09/17/08 55.
LIONEL Something happened?
Bertie stares at his mentor.
Nods.
BERTIE Do I look like a spy?
LIONEL With a toothache.
They disappear inside.
Bertie has to pick his way through discarded toys and sporting equipment, explaining to Logue:
BERTIE I was totally unable to speak.
LIONEL You seldom stutter with me anymore.
LIONEL The boys are a bit untidy.
BERTIE Because you're paid to listen!
LIONEL Like a verbal geisha girl?
Bertie looks around the cluttered, but pleasant room: comfortable furniture a bit battered by the boys, antimacassars to hide the wear spots on the arms, family photos everywhere, well-used Turkish rug on the floor.
LIONEL Home.
BERTIE What more does a man need,eh?
Lionel stares, unsure if he's being patronized.
LIONEL Coming from a man who's lived all his life in castles and palaces.
TKS/Seidler/09/17/08 56.
BERTIE Somebody has to live in them.
LIONEL Somebody does.
Ushers Bertie into his study.
Bertie stands shattered, lost in his painful memory.
BERTIE I couldn't say anything!
LIONEL You could've refused.
LIONEL Don't you know any rude words?
BERTIE What a bloody stupid question!
BERTIE I just said one.
BERTIE Bloody.
BERTIE Bloodybloodybloody!
LIONEL Perhaps a touch more vulgar?
BERTIE Certainly not.
LIONEL To prove you know how.
BERTIE Bugger!
LIONEL A public school prig could do better.
BERTIE Well bloody bugger to you, you beastly bastard!
LIONEL Hardly robust.
BERTIE Shit then.
BERTIE Shit, shit, shit!
LIONEL See how defecation flows trippingly from the tongue?
LIONEL You don't stutter when you swear.
TKS/Seidler/09/17/08 57.
BERTIE Because I'm angry!
LIONEL Get angry more often.
LIONEL Do you know the f- word?
BERTIE Fornication?
LIONEL Oh Bertie...
BERTIE Fuck.
BERTIE Fuck, fuck, fuck!
LIONEL Bravissimo!
LIONEL Now a resounding chorus of...
BERTIE Bloody, bloody.
BERTIE bloody!
BERTIE Shit, shit, shit!
BERTIE Bugger, bugger, bugger!
BERTIE Fuck, fuck, fuck!
A pounding on the wall.
MYRTLE We have children...!
BERTIE This is your fault!
LIONEL Sorry, pet!
LIONEL Won't happen again!
MYRTLE I should hope not!
BERTIE Apologies, Mrs. Logue.
LIONEL First time I've heard you laugh.
BERTIE Royals aren't allowed emotions in public.
LIONEL Which explains a lot.
Bertie is in no mood to be provoked.
TKS/Seidler/09/17/08 58.
BERTIE What do you want me to do, dammit!?
BERTIE Stage my next public appearance as an obscene operetta?!
LIONEL Your next public appearance should be very well rehearsed.
Without thinking, Lionel instinctively reaches out to pat Bertie supportively on the shoulder.
Bertie pulls back in offended shock.
All the warning signals instilled in him are going off.
BERTIE Don't take liberties!
BERTIE You're a dangerous man, Logue.
BERTIE Who sent you?
LIONEL Anyone in mind?
BERTIE The lurking shadows.
BERTIE Courtiers and peers...the whole panoply of a class which once ruled the nation which once ruled the world, afraid of losing their last vestige of privilege if the monarchy is further debased.
LIONEL Your wife was the one who sought me out.
BERTIE Because, dear sweet deluded woman, she believes in me!
LIONEL But you don't share her belief?
LIONEL Why come here?
BERTIE I'm beginning to ask myself that very same question.
BERTIE Your sailing close to the edge, don't push me, Doctor Logue.
LIONEL Lionel.
BERTIE I came here because I was taught from childhood to serve a purpose, and that purpose is to serve.
BERTIE Duty is our sole justification for privilege.
TKS/Seidler/09/17/08 59.
BERTIE (CONT'D) I came here because I was under the illusion you might help me perform that function!
LIONEL Not to worry.
LIONEL They say the King can do no wrong.
BERTIE He can bugger things up!
BERTIE And I am not the King.
BERTIE Mrs. Simpson is seeking a divorce.
BERTIE The Coronation is set for the 12th of May.
BERTIE Her decree becomes final on the 27th of April.
BERTIE That gives them two weeks to marry and put this issue to rest.
LIONEL And if Mr Baldwin stops them?
BERTIE That would be a tragedy.
BERTIE I pray to The Almighty they succeed.
BERTIE I'll do anything within my power to keep my brother on the throne.
LIONEL Does that include debasing yourself?
BERTIE If necessary!
LIONEL Your brother knew perfectly well by giving you a document without warning...
BERTIE Are you saying he wanted me to fail?
LIONEL Are you insisting he didn't?
LIONEL In the future we can parse any document into manageable phrases.
LIONEL You can sing them, swear them, rehearse them til you get the rhythm and flow; that, combined with your growing confidence...
Bertie doesn't want to hear.
BERTIE Growing confidence?
BERTIE Growing dread!!!
BERTIE You're a wicked man, Lionel Logue, trying to get me to thrust myself forward as an alternative to my brother.
BERTIE Trying to get me to commit treason!
TKS/Seidler/09/17/08 60.
LIONEL Trying to get you to realize you need not be governed by fear.
LIONEL Again, why did you seek me out?
LIONEL To take polite elocution lessons so you could attend posh tea parties?!
BERTIE How dare you!
BERTIE I'm the brother of a King...the son of a King...back through untold centuries.
BERTIE You presume to instruct me on my duty?
BERTIE A jumped-up jackeroo from the outback?
BERTIE The disappointing son of an embittered clerk!
BERTIE You're a monster, Doctor Logue.
BERTIE I'm going to Balmoral to spend a pleasant country weekend with my beloved brother.
BERTIE And these sessions are over!
Closed curtains.
Someone fumbles behind it.
LIONEL (BEHIND CURTAIN) Now?
Lionel pushes his way through the gap in the curtain.
A PROVINCIAL DIRECTOR replies from a seat in the auditorium.
(Not the same Director as in the earlier audition scene.)
DIRECTOR Were you told?
DIRECTOR We aren't for London.
DIRECTOR Playing the provinces.
LIONEL Outer Mongolia?
DIRECTOR Available, are we?
LIONEL Nothing prevents.
DIRECTOR I believe that's called "desperate for a part!" Previous experience?
LIONEL Australia.
DIRECTOR You have played the provinces.
DIRECTOR Righto!
DIRECTOR Let's hear what you can do.
TKS/Seidler/09/17/08 61.
LIONEL Caliban?
DIRECTOR Make him deformed.
DIRECTOR Audiences like that.
LIONEL Of course.
LIONEL "Be not afeard; the isle is full of noises, Sounds and sweet airs, that give delight, and hurt not."
As magical as Lionel was when he performed for his boys, here he's stiff and painfully stilted.
LIONEL (CONT'D) "Sometimes a thousand twanging instruments Will hum about mine ears; and sometimes voices..."
DIRECTOR Thank you!
DIRECTOR Don't abandon your day job.
DIRECTOR Next!
Logue bows his head.
Lionel enters and sits dejectedly at the table.
Myrtle and the boys eat in silence.
Finally:
LIONEL You may leave.
VALENTINE Haven't finished yet, Dad.
VALENTINE Oh!
VALENTINE Right!
THE BOYS Thanks, Dad.
THE BOYS Thanks, Mum.
They exit.
Myrtle knows something has happened.
MYRTLE Lionel?
Lionel takes five slim folders out of his jacket pocket and puts them on the table in front of Myrtle.
She studies them, stunned.
TKS/Seidler/09/17/08 62.
MYRTLE (CONT'D) Tickets?
MYRTLE (CONT'D) Home?
LIONEL First class.
A long pause as Myrtle digests this.
MYRTLE What about your...
LIONEL Willie's a problem...not much progress.
LIONEL The others have been referred.
MYRTLE What'll you do when we get home?
LIONEL Try not to act the toff.
LIONEL Teach perhaps.
MYRTLE You could...
LIONEL No!
LIONEL I'm not good enough!
MYRTLE You gave it a try, Lionel.
LIONEL Yes, I had a go.
LIONEL Thanks to your patience.
LIONEL I just bloody well wasn't good enough!
MYRTLE Oh Lionel!
MYRTLE This must've cost you.
CHOP!
CHOP!
CHOP!
The sound of an axe.
A woodsman's axe CHOPS into the thick trunk of a massive tree.
Nearby, a bulldozer cuts into the green turf and rich soil.
The felling and earth removal are being watched by Churchill and Lang from a distant terrace.
In the background a jazz band in white tuxedos syncopates pertly.
TKS/Seidler/09/17/08 63.
WINSTON CHURCHILL Five hundred year old oaks!
WINSTON CHURCHILL Part of the hill!
WINSTON CHURCHILL Removed to improve the view!
COSMO LANG How ever does she do it?
Inside the ballroom, seem through open French doors, an afternoon dance is being held.
Churchill and Lang look in.
At the epicenter, a dashing couple: David, the very picture of insouciance, and clinging to his arm, dripping in jewelry, a rather small, angular, dark haired woman, with a high brow and square jaw - MRS WALLIS SIMPSON.
Her most attractive physical feature is her back, displayed fully by a dress that plunges to her nates.
Surrounded by their entourage, they are the apex of chic.
Watching from the sidelines:
WINSTON CHURCHILL Erotic sexual techniques beyond polite imagination?
WINSTON CHURCHILL I realize of course, that may be outside your personal experience.
Winston exchanges his empty champagne flute for a full one from the tray of a passing footman.
COSMO LANG You've the Devil in you today.
WINSTON CHURCHILL If anyone should know, it would be Your Grace.
COSMO LANG All aspects of mankind are within my venue.
COSMO LANG Did you know, HM has trouble with his glands?
Churchill almost chokes on his champagne.
WINSTON CHURCHILL I'd not appreciated Your Grace was so well versed concerning things testicular!
COSMO LANG They were severely damaged by the measles when HM and his brother were naval cadets.
TKS/Seidler/09/17/08 64.
WINSTON CHURCHILL A veritable encyclopedic font of scatological information.
COSMO LANG Apparently it affects the quality, although not the quantity, of HM's endeavors.
WINSTON CHURCHILL And the brother?
COSMO LANG Unscathed.
COSMO LANG Two daughters.
COSMO LANG I shepherd my flock in all matters, Winston, including multiplication.
They make their way inside.
In the distance an Austin Princess can be seen making its way up the stately tree-line avenue.
Bertie and Elizabeth are dressed for the party.
BERTIE We must try to be pleasant.
ELIZABETH Your father not dead six months, and That Woman throws, "A garden potty."
ELIZABETH P-o-t-t-y.
ELIZABETH She's sleeping in your mother's bedroom.
ELIZABETH And I know perfectly well she calls me `the Dowdy Duchess", and "Cookie".
At the buffet table Churchill helps himself copiously.
WINSTON CHURCHILL Has it occurred to you, as it has only occurred to me, that a Monarch with a gland problem, who realizes he cannot produce issue, might not wish to be King...?
WINSTON CHURCHILL knowing his lack of issue may well become a major issue indeed.
COSMO LANG A dazzling concept...beautifully phrased.
A FOOTMAN announces: TKS/Seidler/09/17/08 65.
FOOTMAN Their Royal Highnesses the Duke and Duchess of York.
Wallis sweeps forward to greet them, but Elizabeth sails past, announcing to no one in particular:
ELIZABETH I came at the invitation of the King.
David turns and bows formally.
Elizabeth cursties in return.
Wallis quickly returns to David, taking him forcefully onto the dance floor.
The Yorks go in the other direction.
To the side, Churchill and Lang watch David and Wallis do a brisk Turkey Trot.
WINSTON CHURCHILL According to the F.B.I....
WINSTON CHURCHILL she is, after all, one of their citizens...our Monarch does not possess exclusive rights to Mrs.
WINSTON CHURCHILL Simpson's sexual favours.
WINSTON CHURCHILL Hitler's Ambassador, Count von Ribbentrop, has been sending her 17 carnations every day...one for each time they've slept together.
COSMO LANG Good Lord, Winston, we must see to it this Empress of the Night does not become Queen of England!
WINSTON CHURCHILL Vividly put.
Churchill has spotted Elizabeth in a side room.
WINSTON CHURCHILL (CONT'D) Allow me to test new waters.
Churchill makes his way to Elizabeth, who is standing in front of a portrait of George IV.
ELIZABETH I don't need to be told I behaved badly.
WINSTON CHURCHILL On the contrary, Mam.
WINSTON CHURCHILL Court etiquette decrees royalty must be greeted by the official host.
WINSTON CHURCHILL In this case: the King.
WINSTON CHURCHILL You behaved impeccably.
WINSTON CHURCHILL As always.
TKS/Seidler/09/17/08 66.
WINSTON CHURCHILL (CONT'D) A relative?
ELIZABETH Distant.
WINSTON CHURCHILL You're well aware, of course, George IV's wife, Mrs. Fitzherbert, was very common indeed...and previously married.
WINSTON CHURCHILL She signed an agreement that she could never become Queen, and their children could not be Royal.
WINSTON CHURCHILL A rather sensible morganatic arrangement.
ELIZABETH That was a very long time ago.
ELIZABETH You're stirring with a rather large spoon, Winston.
ELIZABETH Keep in mind, I'm also a distant relative of Lady Macbeth.
WINSTON CHURCHILL I would disremember at my peril.
David is coming briskly down the corridor, struggling to open a champagne bottle, followed by Bertie determined to catch up.
Elizabeth and Churchill leave the brothers alone.
BERTIE David...
DAVID Wally wants more champagne.
DAVID I have to fetch it.
DAVID She prefers that.
BERTIE Been trying to see you...
DAVID Been terribly busy.
BERTIE Doing what?
DAVID Being King.
TKS/Seidler/09/17/08 67.
BERTIE Where did you get that American accent?
BERTIE David...Father's not dead six months, yet you've put Mrs. Simpson in the suite used by our mother?
DAVID Mama's not still in bed, is she?
BERTIE That isn't funny.
DAVID Ssssssorry, d-d-dear b-b-oy!
BERTIE Please.
BERTIE No more of that.
A moment of silent confrontation.
David backs down.
Sort of.
DAVID Didn't realize you cared.
BERTIE This could end in disaster.
DAVID This will end splendidly.
DAVID With Wallis as my wife.
BERTIE Whatever will she call herself?
DAVID Queen of England, I suspect.
DAVID Kings do marry.
DAVID Empress of India.
DAVID The whole bag of tricks.
BERTIE David!
BERTIE The upper classes are terrified anything which clouds the monarchy makes their situation more dangerous.
BERTIE Hunger marchers are singing the "Red Flag" in front of Westminster...demanding a republic...I've seen them...
DAVID Herr Hitler will sort that out.
BERTIE Who'll sort out Chancellor Hitler?
TKS/Seidler/09/17/08 68.
DAVID He's much maligned.
DAVID By the Jews, according to Wallis.
DAVID And she's very clever about politics.
BERTIE The man's a monster!
BERTIE Our position must remain clear.
DAVID Why's that, old chap?
BERTIE We are a German family!
DAVID Didn't bother anyone during WWI.
DAVID And Kaiser Willie was our uncle.
BERTIE Because we took an English name!
BERTIE Windsor.
BERTIE Because we are England.
BERTIE We are the heart and soul of this nation.
BERTIE That must never change.
DAVID Are you already in charge?
BERTIE I'm trying to warn you.
DAVID Am I being threatened?
BERTIE David, your role is to consult and to be advised.
DAVID Sounds like you've studied our wretched constitution.
BERTIE Sounds like you haven't.
DAVID I won't be a lackey to an unwashed politician like Stanley Baldwin!
BERTIE He's your Prime Minister.
DAVID And I'm his King!
TKS/Seidler/09/17/08 69.
BERTIE If you refuse to listen to our Government, they have no choice but to resign.
DAVID I'll form another.
DAVID There's Winston.
DAVID He'd love to be P.M. We'll create a King's Party.
BERTIE To fight a general election in which your marriage is the only topic?
DAVID I'd risk anything and everything for Wallis.
DAVID Don't I have rights?
BERTIE Privileges.
DAVID Not the same thing.
BERTIE No.
DAVID Yet an ordinary man may marry for love.
BERTIE We're not ordinary men, David!
BERTIE We were bred to be profiles on a coin.
BERTIE If you were ordinary, on what basis could you possibly claim to be King?!
DAVID What's the point then?
DAVID Just to look posh?
DAVID You know...your speech is much improved tonight.
DAVID Hardly a hesitation.
DAVID Yearning for a larger audience, are we?
BERTIE Don't say such a thing!
DAVID Is my young brother trying to push me off the throne?
DAVID Sounds positively medieval.
BERTIE I beg of you, don't do this to my wife, my daughters, to me.
TKS/Seidler/09/17/08 70.
DAVID The politicians will give in.
DAVID See you at my Coronation...Bertie.
The champagne cork finally POPS.
He strides off.
Establishing shot of the Prime Minister's residence.
WINSTON CHURCHILL Nice of you to invite me to your digs, Stanley.
Baldwin and Churchill are alone together.
No love lost between these two men.
BALDWIN As you may have guessed...
Churchill is silent.
Balwin waits, then:
BALDWIN (CONT'D) ...I intend to resign.
BALDWIN (CONT'D) The Royal scandal has weakened my position considerably.
Churchill, on the edge of his seat, can't suppress an anticipatory grin.
Baldwin takes pleasure in deflating it.
BALDWIN (CONT'D) No need to volunteer your services, Winston.
BALDWIN (CONT'D) Neville Chamberlain will take my place, once this Royal matter is settled.
BALDWIN (CONT'D) As Chancellor of the Exchequer he already lives next door.
WINSTON CHURCHILL My opportunity to redecorate will come soon enough, Stanley.
BALDWIN Will it?
BALDWIN Well, enough chit-chat.
BALDWIN The question of a morganatic marriage, as a possible solution, has been put to the Dominion Prime Ministers.
BALDWIN After all, HM is their King too.
Baldwin has a sheath of telegrams in hand.
TKS/Seidler/09/17/08 71.
BALDWIN (CONT'D) Australia: no.
WINSTON CHURCHILL David feels there aren't that many people in Australia.
BALDWIN Canada: no.
BALDWIN Union of South Africa: an inappropriate marriage would create a
permanent wound.
The Irish Free State: states it is not really their affair, and, bluntly, our English King may marry any whore he wants, they'll be well out of it.
WINSTON CHURCHILL Bloody Irish.
BALDWIN New Zealand...wavers.
WINSTON CHURCHILL Ah, the Kiwis!
BALDWIN Being rather remote, they've not even heard of Mrs Simpson.
BALDWIN Hardly a winning hand.
Silence.
BALDWIN (CONT'D) This is not about true love, Winston.
BALDWIN (CONT'D) This is about who's in charge.
BALDWIN (CONT'D) Does the King do what he wants, or what his people want him to do?
BALDWIN (CONT'D) Does the King own his nation, or does the nation own their Monarch?
WINSTON CHURCHILL He won't budge.
BALDWIN Nor will we.
Winston Churchill is incongruously inspecting a rocking horse.
Unable to resist, he sits on it gingerly, rocking back and forth lost in a reverie.
Eyes closed he extends his right arm as though holding a cavalry saber.
Bertie enters startling him.
BERTIE Don't dismount.
TKS/Seidler/09/17/08 72.
WINSTON CHURCHILL Good of you to see me at this late hour.
BERTIE Thought you were in David's camp?
WINSTON CHURCHILL I was.
WINSTON CHURCHILL "I am now free to tell you how I was jockeyed out of the Throne."
BERTIE Good Lord!
BERTIE My brother wrote that?
WINSTON CHURCHILL Wallis wrote it for him.
WINSTON CHURCHILL I'll burn it.
WINSTON CHURCHILL I fear your brother is like the child in a fairy story, given everything in the world, but they forgot his soul.
WINSTON CHURCHILL Quite happy to bring his nation to the brink of civil war just as we face global conflict.
BERTIE We're not coming to that?!
WINSTON CHURCHILL Oh, there'll be war, alright.
WINSTON CHURCHILL Your brother held conversations with the Duke of Saxe-Coburg, your cousin, a ranking member of the Nazi party.
WINSTON CHURCHILL I have the Scotland Yard intercept: "Who is King here?
WINSTON CHURCHILL Baldwin or I?
WINSTON CHURCHILL I myself wish to talk with Hitler, and will do so here or in Germany."
WINSTON CHURCHILL I doubt England is ready to return to absolute monarchy.
BERTIE Surely his motives are misunderstood?
WINSTON CHURCHILL "If I don't get my way, when the war comes, Hitler will crush everyone, including the Americans.
WINSTON CHURCHILL The British may not want me as their King, but I'll soon be back as their leader."
WINSTON CHURCHILL His intent seems crystal clear.
BERTIE Winston?!
BERTIE Don't take him seriously!
TKS/Seidler/09/17/08 73.
WINSTON CHURCHILL Mugs for his cancelled Coronation will soon be on clearance sale.
BERTIE You're willing to go along with this?!
BERTIE Changing horses in mid-stream is a perilous maneuver!!!
WINSTON CHURCHILL Depends how badly the horse you're on stumbles.
BERTIE It's not too late, Winston, you could form a government on his behalf.
WINSTON CHURCHILL I must decline.
WINSTON CHURCHILL Reluctantly.
The rocking horse CRACKS.
Churchill gets to his feet.
WINSTON CHURCHILL (CONT'D) Sorry.
WINSTON CHURCHILL (CONT'D) I've written a new speech for him.
BERTIE I don't want to hear it!
BERTIE Ever!
WINSTON CHURCHILL It does have a rather nice turn of phrase.
It is December 11th, 1936.
If practical use the actual recorded broadcast (truncated).
In London, Birmingham, Edinburgh, country hamlets and cathedral towns...the streets are deserted.
Stragglers hurry indoors to be near:
RADIO FILTER) At long last I am able to say a few words of my own.
RADIO FILTER) Until now it has not been constitutionally possible for me to speak.
RADIO FILTER) A few hours ago I discharged my last duty as King and Emperor.
TKS/Seidler/09/17/08 74.
Bertie and Elizabeth listening to the radio with the two princesses royal sitting at their parents' feet.
Bertie battles his emotions.
DAVID (V.O. RADIO FILTER) Now that I have been succeeded by my brother, the Duke of York, my first words must be to declare my allegiance to him.
MARGARET ROSE Daddy, who broke our rocking horse?
BERTIE A giant.
Elizabeth holds a finger to her lips: shush.
DAVID (V.O. RADIO FILTER) This has been made less difficult to me by the sure knowledge that my brother has one matchless blessing, enjoyed by so many of you, and not bestowed on me -- a happy home with his wife and children.
The glow of a radio dial.
Lionel and Myrtle sit in armchairs, the radio on a side-table between them.
DAVID (V.O. RADIO FILTER) I have found it impossible to carry the heavy burden of responsibility and to discharge my duties as King as I would wish to do without the help and support of the woman I love.
Lionel gets up to turn it off as David's voice concludes:
DAVID (V.O. RADIO FILTER) (CONT'D) We all have a new King.
DAVID (V.O. RADIO FILTER) (CONT'D) I wish him and you, his people, happiness and prosperity with all my heart.
DAVID (V.O. RADIO FILTER) (CONT'D) God bless you all!
DAVID (V.O. RADIO FILTER) (CONT'D) God save the King!
Logue strokes Myrtle's hair.
LIONEL I too "married the woman I love."
TKS/Seidler/09/17/08 75.
MYRTLE You married a shop girl.
LIONEL A wonderful lass.
LIONEL Someone I can talk to heart to heart.
MYRTLE Using simple words and short sentences.
MYRTLE I'm very ordinary.
LIONEL That's why we're suited.
LIONEL I'm just an ordinary bloke.
MYRTLE Ordinary?
MYRTLE You're a man with wild dreams, Lionel.
MYRTLE Mine are so very small.
MYRTLE A job, a husband, a home.
MYRTLE Raising our sons.
MYRTLE That's all I ever wanted.
LIONEL Me too.
MYRTLE Is that why, every day, you've spent hours with a man who's about to be King?
LIONEL That relationship is now past tense.
MYRTLE Yet, for as long as you could, you did what you wanted.
LIONEL I wanted to be a great actor.
LIONEL That's what I wanted.
MYRTLE And failing that...
LIONEL I certainly failed!
MYRTLE A great healer.
MYRTLE Always...'great'.
MYRTLE Where does a shop girl fit in?
LIONEL Very snugly, into my heart!
LIONEL Always have, always will.
TKS/Seidler/09/17/08 76.
MYRTLE Trouble is, Lionel, when you say that, I still believe it.
The Royal standard on a gleaming car's bonnet.
Bertie stands uneasily in the uniform of an Admiral of the Fleet as the driver opens the door.
Bertie realizes its a Rolls.
BERTIE Where's the Austin?
DRIVER The Palace changed it, Your Highness.
BERTIE I liked the Austin.
DRIVER So did I, sir.
The two girls wave from their open playroom window, and call:
MARGARET ROSE You look like a chicken.
LILIBET A rooster.
He waves, and gets in.
A formal voice announces:
MASTER OF THE COUNCIL His Majesty will address the Accession Council and take his oath.
Bertie looks at himself in a full length mirror, making last minute adjustments to his uniform.
Staring at his reflection:
BERTIE How did this happen to you?
TKS/Seidler/09/17/08 77.
Bertie walks to the podium like a man to the gallows faced with an array of the Privy Councillors, members of the House of Lords, the Lord Mayor of the City of London, the Aldermen of the City of London and the High Commissioners of the Commonwealth countries.
All the old symptoms reappear: the tightening of the neck muscles, the protruding Adam's apple, the jaw locking.
BERTIE My Lords, members of the Accession Council, I meet you today in circumstances which are without parallel in the history of our Country...
Its going to be a terrible performance.
He bows his head in humility.
And shame.
Elizabeth is playing quietly with her daughters when the door opens and Bertie appears, still in full regalia, straight from the Accession Council.
He holds his arm out, expecting them to run to him for a hug and kiss, his solace after the ordeal.
They remain where they are.
BERTIE Daddy's home.
They curtsy formally.
LILIBET & MARGARET ROSE Your Majesty.
Bertie is devastated.
Elizabeth takes him quickly out into the corridor.
BERTIE I don't want to lose you.
ELIZABETH How could you possibly?
BERTIE Being what we both dread most.
TKS/Seidler/09/17/08 78.
ELIZABETH Dear, dear, man, I refused your first two marriage proposals because, as much as I loved you, I couldn't abide the thought of living in the Royal gilded cage.
ELIZABETH Then I realized...you stuttered so beautifully...they'd leave you alone.
She takes his face in her hands tenderly.
ELIZABETH (CONT'D) If I must be Queen, I will be a good Queen.
ELIZABETH (CONT'D) The wife of a very great King indeed.
ELIZABETH (CONT'D) You know what you must do.
Logue is working with Anna.
She's reading smoothly and with great intensity.
ANNA "Had I the heavens' embroidered cloths Enwrought with golden and silver light, The bbb..."
Gets stuck.
LIONEL We haven't much more time together.
LIONEL Give it a go.
The doorbell RINGS.
Logue is annoyed.
LIONEL (CONT'D) There weren't any more appointments today.
The bell RINGS again.
He yells:
LIONEL (CONT'D) Piss off!
LIONEL (CONT'D) Anna?
ANNA "The blue and the dim and the dark cloths Of night and light and the half-light..."
The door opens and Bertie enters the waiting area.
Hearing Anna he stops outside the consultation room and listens.
TKS/Seidler/09/17/08 79.
ANNA (CONT'D) "I would spread the cloths under your feet, But I, being poor, have only my dreams.
ANNA (CONT'D) I have spread my dreams under your feet; Tread softly because you tread on my dreams."
Silence.
LIONEL Read it to him.
LIONEL If he doesn't profess his love, he's not a man.
Anna nods earnestly.
ANNA Thank you...Lionel.
She exits via the Waiting Room and almost runs into Bertie.
On recognizing him, she bobs her head.
BERTIE That was lovely.
BERTIE Don't take any guff.
ANNA Can I tell my Harold that's what you said?
BERTIE I'd be honoured.
She dashes off.
Logue comes to the door of the Waiting Room, in effect blocking Bertie's way in.
LIONEL Johnson, isn't it?
LIONEL Have you an appointment?
BERTIE Want me to beg?
LIONEL I told you, Kings don't beg.
BERTIE I believe this time a bit of begging might be required.
BERTIE Elizabeth says I must eat humble crow.
LIONEL Its "crow" or "humble pie".
LIONEL Take your pick.
TKS/Seidler/09/17/08 80.
BERTIE I was frightened and took refuge in being `Royal'.
BERTIE What I said was unforgivable.
BERTIE And...
LIONEL And?
BERTIE What's the one essential thing a King must do?
BERTIE He must believe he is King.
BERTIE How can I possibly do that?
BERTIE For pity sake, Lionel, I beg you: get me through!
BERTIE I'll pay you another shilling.
LIONEL What're friends for?
Logue steps aside, letting Bertie in.
BERTIE I wouldn't know.
The double bed is piled high with clothing, a suitcase at its foot.
Myrtle is sorting.
She hears Lionel enter behind her.
At first, she doesn't turn.
Lionel remains silent.
MYRTLE I've got the boys sorting their things.
MYRTLE Your office will be a chore...
Realizing something is amiss, she turns, and knows instantly what Lionel's going to tell her.
Her hand goes to her mouth to stifle her emotions.
Bertie is with visitors: Churchill and Lang.
There's a slight but discernible change in his demeanor.
COSMO LANG We asked to see Your Highness because there's the urgent question of what to call your brother.
COSMO LANG Aside from the obvious.
Bertie is not pleased with His Grace's joke, but lets it pass.
TKS/Seidler/09/17/08 81.
BERTIE What do you suggest?
COSMO LANG Mr. Edward Windsor?
COSMO LANG All he deserves.
BERTIE What has my brother given up on his abdication, other than the throne?
They look at each other, unsure.
BERTIE (CONT'D) Wouldn't it be a good idea to find out before coming to me?
BERTIE (CONT'D) He cannot be Mister, as he was born the son of a Duke.
BERTIE (CONT'D) Which makes him a Lord at the very least.
WINSTON CHURCHILL Very well, Lord E.W. it is.
BERTIE And as a Lord of the realm, he's entitled to be elected to the House of Commons.
BERTIE Heading a King's Party.
COSMO LANG Unacceptable!
BERTIE So you prefer he takes a seat in the House of Lords?
BERTIE Again, on behalf of a King's Party?
BERTIE Is that acceptable?
WINSTON CHURCHILL Certainly not.
BERTIE But if he's made a Royal Duke, and called His Royal Highness, he cannot stand for Parliament.
BERTIE Nor may he speak or vote in the House of Lords.
COSMO LANG Oh I say...
BERTIE The Duke of Windsor it is.
BERTIE Gentlemen.
He exits abruptly.
Churchill and Lang gather their things stunned.
TKS/Seidler/09/17/08 82.
WINSTON CHURCHILL Not exactly a dummy, is he?
Myrtle is in the shop window, arranging handbags, luggage, and briefcases.
In the store Myrtle can be seen dressing the window, while in his glass office the OWNER, a portly bald gentleman with a Dickensian air, is deep in concerned conversation with a man in trench-coat.
The Owner keeps glancing worriedly in Myrtle's direction.
The two men nod, shake hands.
The fellow in the trench-coat leaves.
The owner beckons another shop-girl over and whispers something to her.
She heads towards Myrtle.
BERTIE (O. S.) "Let's go gathering hearty heather with the gay brigade of grand dragons."
A wall divides the study from the living area, allowing the action in both spaces to be viewed.
IN THE PARLOUR: Elizabeth waits, ill at ease.
LIONEL Splendid.
LIONEL Here's another.
LIONEL "She sifted seven thick-stalked thistles through strong thick sieves."
LIONEL At home, twenty-five times, in rapid succession.
BERTIE Those are my hardest sounds.
Lionel gives him a look.
BERTIE (CONT'D) Oh.
LIONEL Shall we invite your wife in now?
TKS/Seidler/09/17/08 83.
Logue goes to the door and starts to open it.
He shuts it quickly.
LIONEL (CONT'D) I wasn't expecting Myrtle for several hours!
IN THE PARLOUR: Myrtle has entered, definitely unhappy.
Seeing Elizabeth, she's even less happy, and flabbergasted.
MYRTLE Milady?
ELIZABETH "Your Majesty", the first time.
ELIZABETH After that, "Ma'am".
ELIZABETH Not Malm as in Palm, Mam as in ham.
ELIZABETH I'm informed your husband calls my husband Bertie and my husband calls your husband Lionel.
ELIZABETH I trust, however, you won't attempt to call me Liz.
IN THE STUDY: Lionel stands listening, ear to the door.
BERTIE How're they getting on?
LIONEL As to be expected.
IN THE PARLOUR: Myrtle announces:
MYRTLE You may call me "Madam Logue".
Myrtle's at a loss knowing what to do with a Duchess.
MYRTLE (CONT'D) May I offer you a cup of tea, Ma'am?
ELIZABETH Thank you, Madame Logue, but I'm waiting to be summoned.
Silence.
MYRTLE You don't like my husband.
MYRTLE That's what I was told.
ELIZABETH I was told the same.
TKS/Seidler/09/17/08 84.
BERTIE Do we remain in hiding?
LIONEL I'm not going out there!
MYRTLE What do you dislike about my Lionel?
ELIZABETH I don't wish my husband to be demeaned.
ELIZABETH What don't you like about mine?
MYRTLE I don't want my Lionel getting hurt.
There's only one thing can save him now: success.
IN THE STUDY: the men are growing increasingly nervous.
BERTIE We're being cowards.
LIONEL Of course.
LIONEL We're sensible men.
BERTIE You should go in.
LIONEL Me?
LIONEL You.
BERTIE Why me?!
LIONEL You're the Royal.
BERTIE Being a monarchist, I recognize these are your digs.
BERTIE Therefore: here you rule.
BERTIE Therefore: you go in.
Urged by Bertie, Logue opens the door.
IN THE PARLOUR: Logue enters, pretending total innocence and surprise, followed by Bertie, also trying to keep the pretense.
TKS/Seidler/09/17/08 85.
LIONEL Oh!
LIONEL Hello, Lady Elizabeth!
LIONEL Oh!
LIONEL Hello, Myrtle darling!
LIONEL What a pleasant surprise.
Myrtle stares at him and takes her revenge.
MYRTLE Will the Yorks be staying for dinner?
Logue and Bertie look panic-stricken.
Elizabeth comes to the rescue.
ELIZABETH A previous engagement.
LIONEL Some other time, love.
Logue ushers Elizabeth into the study, giving Myrtle a nervous little wave.
She glares and exits.
LIONEL (CONT'D) Glad you had a chance to meet Myrtle.
Bertie stifles a snort.
Elizabeth glares at him.
LIONEL (CONT'D) Good of you to come.
ELIZABETH Harley Street is far too public.
ELIZABETH What is my function here?
LIONEL For me to show you how to pitch in.
ELIZABETH Oh dear, I may not be a `pitch in' type.
LIONEL Piece of cake.
LIONEL Please assume a supine position on the floor.
ELIZABETH What?!
LIONEL Firm support is needed.
TKS/Seidler/09/17/08 86.
Bertie dutifully lies on the floor.
LIONEL (CONT'D) Breathe deeply...expand your chest...
LIONEL (CONT'D) now your stomach...deep into the diaphragm.
LIONEL (CONT'D) Splendid.
LIONEL (CONT'D) How do you feel?
BERTIE Full of hot air.
LIONEL Well on your way to becoming a qualified political speaker.
LIONEL Again...
Bertie inhales deeply.
LIONEL (CONT'D) ...
LIONEL (CONT'D) and hold.
LIONEL (CONT'D) Now, Princess Elizabeth, be so kind as to sit on your husband's stomach.
ELIZABETH Good grief.
LIONEL Gently of course.
Elizabeth sits gingerly on Bertie's stomach, asking solicitously:
ELIZABETH Are you alright, Bertie?
Bertie nods.
LIONEL Now exhale slowly...down goes Princess Elizabeth...inhale slowly...nothing rushed, expanding your chest fully, extending the column of air til it hits the diaphragm...and...up comes Princess Elizabeth.
LIONEL Exhale...down goes Princess Elizabeth...inhale...up comes Princess Elizabeth.
LIONEL You get the idea.
LIONEL Doesn't have to be Princess Elizabeth of course, but I thought you'd prefer your wife to one of the staff.
LIONEL Now comes the fun part.
ELIZABETH There's actually more?
Bertie springs to his feet while Logue opens a window.
TKS/Seidler/09/17/08 87.
LIONEL You will now shout the vowel sounds, all five of them, as loudly as possible, each to last no less than 15 seconds.
LIONEL There's poor coordination between your larynx and diaphragm.
LIONEL Princess Elizabeth, you can be the official timer.
ELIZABETH Vowel sounds?
ELIZABETH Shouted at an open window?
ELIZABETH On a public street?
LIONEL Anyone who can stand at an open window vibrating loudly in full view of the world can learn to give a public speech.
ELIZABETH They can also be considered quite dotty.
ELIZABETH Don't even contemplate it!
BERTIE Sorry, dear, doctor's orders.
BERTIE Aaaaaaaaaaaaaaaaaaa...
BERTIE She's right, those two chaps are staring at me.
ELIZABETH They're always looking at you.
LIONEL You're followed?
ELIZABETH Royal scrutiny, Doctor, best get used to it.
BERTIE ...aaaaaaaaaaaaaaaayyyyyyyyyyy...
BERTIE ...eeeeeeeeeeeeeeeeee...
BERTIE Are you timing this?
BERTIE iiiiiiiiiiiiiiiiiiiiiiii...
BERTIE ooooooooooooooooooooooooo...
BERTIE uuuuuuuuuuu.
The family eat in tense silence TKS/Seidler/09/17/08 88.
VALENTINE May we be excused?
LIONEL No.
The unhappy meal continues.
PETER We don't want to hear you fight.
LIONEL We're not fighting.
LIONEL Your mother isn't talking.
MYRTLE You wish me to speak my mind?
LIONEL Boys, leave.
THE BOYS Thank you, Dad!
THE BOYS Thank you, Mum!
They exit hurriedly.
MYRTLE Lionel...without warning, I arrive home to find the Queen in my parlour.
LIONEL A Duchess, she hasn't been crowned yet.
MYRTLE Lionel, don't quibble!
LIONEL What'd you think of her?
MYRTLE Does it matter!?
MYRTLE She's the Queen and he's the King forgodsake!
MYRTLE What're they doing here?!
LIONEL Why'd you come home so early?
MYRTLE Lionel...
LIONEL They came for help.
TKS/Seidler/09/17/08 89.
MYRTLE What role are you auditioning for now?
MYRTLE Royal saviour?!
MYRTLE Who's going to help us?!
MYRTLE This will bring us down, Lionel.
MYRTLE You know it will.
LIONEL When that poor chap first walked into my office, he was a slim, quiet man with tired eyes and all the outward symptoms of the person upon whom a habitual speech defect has set the sign.
LIONEL You saw him today; once more there was hope.
MYRTLE You're not listening to me!
She gets up angrily and starts carrying dishes to the kitchen.
He follows her back and forth.
LIONEL Myrtle, I love you.
MYRTLE You say that, but you don't listen when I say, in so many ways, how desperately I want to go home, how I never, ever, intended to stay here.
MYRTLE This was to be a holiday trip to see `Mother England', and you turned it into quite something else.
MYRTLE What happened, Lionel?
MYRTLE We went to Wembley Stadium, next thing...you'd cashed in our tickets.
He's silent.
MYRTLE (CONT'D) Very well, I shan't talk of this ever again.
MYRTLE (CONT'D) I will, as always, be supportive of your endeavours.
LIONEL Myrtle...
LIONEL I don't deserve a wonderful woman like you.
MYRTLE How right you are.
LIONEL But why'd you come home so early?
MYRTLE Lionel...I was let go.
TKS/Seidler/09/17/08 90.
He's stunned.
MYRTLE (CONT'D) Inquiries were made...Mr Falkoff wouldn't say who...afterwards it was: `With your hubby treating a personage that high and mighty, you won't be needing employment with us, will you, Mrs Logue?'
LIONEL Why?!
MYRTLE They're frightened, Lionel.
MYRTLE Of what seems so far above them.
MYRTLE I sympathize.
MYRTLE I'm frightened too.
LIONEL Oh, Myrtle.
LIONEL My love...
Establishing shot of this architectural icon.
COSMO LANG Winston, you do read the newspapers?
A massive cavern of stone statuary and stained glass.
The center piece of this particular section is the throne of Edward the Confessor.
Scaffolding is in the process of being erected to supply lighting for the Coronation.
Archbishop Lang and Churchill inspect it with satisfaction.
WINSTON CHURCHILL Only the vulgar ones.
Churchill pours two nips of whiskey into metal cups nested in a hip flask.
WINSTON CHURCHILL (CONT'D) To our new King.
COSMO LANG Let's sincerely hope.
They look at each other in silence.
WINSTON CHURCHILL Is this a `slightly pregnant pause'?
TKS/Seidler/09/17/08 91.
COSMO LANG They say he is dim.
WINSTON CHURCHILL Demonstrably untrue.
COSMO LANG They say he has epilepsy.
WINSTON CHURCHILL Patently erroneous.
COSMO LANG Fragile, prone to illness...
WINSTON CHURCHILL Some correctness in that.
COSMO LANG ...and will die prematurely.
COSMO LANG They predict he'll be unable to complete the Coronation.
WINSTON CHURCHILL What do you propose?
WINSTON CHURCHILL Shorten the ceremony?
WINSTON CHURCHILL Or no ceremony at all?
COSMO LANG My idea exactly!
WINSTON CHURCHILL I believed so.
WINSTON CHURCHILL But what we need is a pageant of pomp and pomposity to impress the world.
COSMO LANG What we need, and what we'll get, may be two rather different things.
COSMO LANG Did you hear his pathetic attempt at the Accession Council?
COSMO LANG He'll never be able to speak in public.
WINSTON CHURCHILL So, we plonk a tinsel crown on his head and lock him in a closet?
WINSTON CHURCHILL Who then will spiritually lead this great nation into war?
WINSTON CHURCHILL Who will address the far flung corners of the Empire, rallying all to our defense?
COSMO LANG Well...
WINSTON CHURCHILL The Head of our Church?
WINSTON CHURCHILL Is that what you have in mind?
TKS/Seidler/09/17/08 92.
COSMO LANG Would it be such a calamity?
WINSTON CHURCHILL Best ask our new King.
Bertie has entered with Logue.
Lang spins around.
COSMO LANG Your Majesty.
WINSTON CHURCHILL Excuse me, sir, duty calls.
He exits quickly.
Cosmo continues nervously as they walk through the Abbey, the Archbishop pointing out the preparations in progress, particularly a booth for broadcasters.
BERTIE Is this the scene of the crime?
COSMO LANG What a peculiar thing to say.
BERTIE Referring to my assault upon the ears of the listeners.
COSMO LANG Ah, yes, wireless is indeed a Pandora's Box.
COSMO LANG I have, however, categorically said no to the BBC's new "radio-with-pictures" gadget.
COSMO LANG Imagine, the unwashed viewing us as we blow our noses or scratch our bottoms.
BERTIE Radio with pictures?!
COSMO LANG It is called..."
COSMO LANG television".
COSMO LANG Happily, with a transmission range of only fifteen miles this "TV" thing has no future.
COSMO LANG We shall, however, be forced to permit cinema; the product of which I shall personally edit.
BERTIE That'll keep you busy, removing all my stops and starts.
COSMO LANG Unless of course you'd prefer a quiet ceremony?
TKS/Seidler/09/17/08 93.
BERTIE What exactly do you mean?
COSMO LANG Something...discreet...private.
COSMO LANG We could pre-record an edited version to be broadcast to the world.
COSMO LANG Or even find an actor with a similar voice.
Logue has arrived and comes out of the shadows.
LIONEL A King based upon deception?
Cosmo takes Bertie aside.
COSMO LANG If your gentleman from Security would give us space, we could discuss this in private.
BERTIE You mean my bodyguard,"Crusher?"
Giving Lionel a scathing look, Lang continues speaking to Bertie confidentially.
COSMO LANG Fret not.
COSMO LANG As I assured our nation in my recent broadcast: "When his people listen to their new Monarch they will note an occasional momentary hesitation in his speech.
COSMO LANG But to those who hear it, it need cause no sort of embarrassment, for it causes none to him who speaks."
COSMO LANG You see, I've paved the way.
COSMO LANG But should you wish to avoid further stress...
LIONEL Why not paint him pink and cover him with sequins?
COSMO LANG Pardon?!
LIONEL If you wish to call attention to his anxiety.
COSMO LANG Does your bodyguard know to whom he's speaking?
COSMO LANG He certainly doesn't know his place!
TKS/Seidler/09/17/08 94.
BERTIE Doctor Lionel Logue, my speech therapist.
COSMO LANG Therapist?!
COSMO LANG I'd no idea!
COSMO LANG Had I known Your Majesty was seeking assistance I would've made my own recommendation.
BERTIE Dr. Logue is to be present at the Coronation.
COSMO LANG Impossibly to find room.
COSMO LANG Even for a Doctor.
LIONEL Just Lionel.
BERTIE Behind the chair of Edward the Confessor.
COSMO LANG The Royal Box!?
COSMO LANG Your Family will be seated there.
BERTIE Which makes it most suitable.
COSMO LANG Perhaps I might be able to add a very small stool.
BERTIE Two comfortable chairs.
BERTIE One for Madam Logue.
BERTIE She's a close friend of my wife.
BERTIE The Queen.
COSMO LANG I'll have someone attend to it.
LIONEL And now, if you don't mind, we need the premises.
COSMO LANG My dear fellow, this is Westminster Abbey!
COSMO LANG The Church must make preparations.
LIONEL So must Bertie.
COSMO LANG Bertie?!
COSMO LANG We do not call the King: "Bertie"!
TKS/Seidler/09/17/08 95.
LIONEL I do.
LIONEL During waking hours we'll need the facilities.
LIONEL It'll be a closed set.
LIONEL No observers.
BERTIE Those are my wishes, Your Grace.
Lang nods curtly and exits.
BERTIE (CONT'D) You've made a dangerous enemy.
LIONEL Wouldn't want him as a friend.
BERTIE And don't ever call me Bertie in public.
A moment of confrontation.
Lionel knows he's overstepped.
LIONEL Tell me...
BERTIE I sense one of your dreadful questions on the horizon.
LIONEL Do you really want to be King?
BERTIE Knew it!
BERTIE I haven't any choice.
LIONEL You can be a wounded King who stumbles through his Coronation.
LIONEL Or, as the Arch of C so archly suggests, no Coronation at all.
LIONEL Always a choice.
BERTIE What's this, you wait til Westminster Abbey, then ambush me?
LIONEL I'm simply asking questions...
LIONEL which you seem unable to answer.
BERTIE I'm a sacrificial lamb being led to slaughter!
BERTIE Damn you!
TKS/Seidler/09/17/08 96.
LIONEL Quite possibly.
LIONEL But at least I know what I want.
LIONEL You haven't the foggiest.
His words reverberate through the empty abbey.
LIONEL That's quite different.
LIONEL Let's get down to work then, shall we?
Bertie glares at him.
LIONEL (CONT'D) As soon as you and Elizabeth enter the West door, you'll be greeted with the hymn "I Was Glad When They Said Unto Me."
LIONEL (CONT'D) You won't actually be that glad, because they sing it for a great long time.
Bertie follows Logue deep into the bowels of the `Abbey'.
LIONEL (CONT'D) You'll then show yourself to the various sides of the Abbey as the Archbishop announces four times in a loud voice, "Sirs, I here present unto you..."
LIONEL (CONT'D) Have you decided your name for when you become King?
LIONEL (CONT'D) For when you become a different person?
BERTIE George.
LIONEL Like your father?
BERTIE Like my father.
LIONEL Not Albert?
BERTIE Given the current situation...too Germanic.
LIONEL "Sirs, I here present unto you, GEORGE, your undoubted King!"
TKS/Seidler/09/17/08 97.
"George, your undoubted King!" echoes through the Abby.
Lang is on the phone.
The door is open.
While talking he watches the work preparations.
On the phone he tells someone:
COSMO LANG I've made inquiries.
Logue enters and sits at the table.
Myrtle serves him.
MYRTLE A bit dry.
MYRTLE Tried to keep it warm.
LIONEL Mmm...
LIONEL Kedgeree!
LIONEL Lovely.
MYRTLE You look done in.
LIONEL I've news for you.
LIONEL You're coming to the Coronation.
MYRTLE I've news for you.
MYRTLE I'm not!
LIONEL You must.
MYRTLE Stand in the rain hoping for a glimpse?
LIONEL Royal Box.
LIONEL You and I.
Stunned silence, then.
MYRTLE Lionel...I'd need a new dress.
LIONEL Rather thought you might.
Valentine calls from the next room: TKS/Seidler/09/17/08 98.
VALENTINE Dad!
VALENTINE Phone!
VALENTINE For you!
LIONEL Won't be a sec.
He exits.
Myrtle waits.
Looks at herself, bemused, reflected in a glass-fronted cabinet.
Even does a curtsey.
The last of the preparation crew are being scurried out by Lang.
He gives a final, satisfied, look at the cavernous space, like a director preparing the stage for a final scene.
He quotes Shakespeare, extremely pleased with himself:
COSMO LANG "The play's the thing, wherein I'll catch the conscience of a King."
He exits.
THE CAMERA explores various elements:
The Throne of Edward the Confessor.
Beneath it, a large rough-hewn stone: The Stone Of Scone.
Leaning against the Throne, a huge sword, set there for the next Coronation rehearsal.
Majestic stained glass windows of saints, kings, and martyrs.
Rows of pews, worn with centuries of use.
Graves of the mighty: kings, poets, and statesmen.
This Abbey holds the history of a nation.
Footsteps resonate.
Lionel enters.
Trips over one of the gravestones.
LIONEL Bertie?
LIONEL Blast!
LIONEL Stepped on Lord Byron.
LIONEL Bertie...?
Lights snap on skewering Lionel.
Bertie steps into view wearing a coat against the night chill of the stone cathedral.
BERTIE This is not a rehearsal, "Doctor" Logue.
TKS/Seidler/09/17/08 99.
LIONEL Ah, the Star Chamber inquisition.
LIONEL I wondered when that would happen.
LIONEL And I'd promised Myrtle a new frock.
BERTIE "Just call me Lionel"!
BERTIE Never did you call yourself `Doctor'.
BERTIE We did that for you.
BERTIE No diploma, no training, no credentials.
BERTIE Just a great deal of nerve.
LIONEL Want to hear my side of the story?
BERTIE There isn't a "your-side-of-the-story".
BERTIE This is my story.
BERTIE And you've ruined it!
BERTIE Its not just the Coronation, terrifying enough, its the radio speech to millions afterwards, and the speech after that, and for the rest of my failed miserable life!
LIONEL Wembley Stadium...
BERTIE You dare remind me?!
LIONEL I was there.
BERTIE Then you knew from the start I was hopeless?!
LIONEL My son, Valentine, asked, "Could you help that poor man?" I replied, "He's too old for me to manage a complete cure, but I could very nearly do it, I'm sure of that."
BERTIE Lying bastard!
LIONEL I knew I could help you.
LIONEL You refuse to believe?
BERTIE In you?!
TKS/Seidler/09/17/08 100.
LIONEL In yourself.
BERTIE Who the hell do you think you are?!
LIONEL A failed actor.
BERTIE Actor?
LIONEL Father wanted me to be a doctor, but I couldn't cut flesh.
LIONEL So I worked in the mines, recited in pubs...
BERTIE An actor?!
LIONEL When the war came, by the time I was ready to be shipped out, the first casualties were limping home.
LIONEL Poor buggers, broken in bone and spirit.
LIONEL `Lionel, you're good with your mouth, see if you can help these poor sods.' The shell-shocked were the saddest.
LIONEL Most stuttered profoundly.
LIONEL Far worse than you.
LIONEL Muscle therapy helped somewhat, but I found I had to go deeper, as you might well imagine.
BERTIE I know nothing of those poor men!
LIONEL I think you do.
LIONEL They had cried out, and the universe had not listened.
LIONEL So they'd lost faith in their voice.
LIONEL My job was to make them shout in righteous anger: "I have the right to be heard!"
BERTIE I suppose that helped them, did it?
LIONEL Make inquiries.
BERTIE Inquiries have been made!
BERTIE No credentials.
LIONEL But a lot of success.
LIONEL No training was given.
TKS/Seidler/09/17/08 101.
LIONEL (CONT'D) Not in Western Australia, not at that time.
LIONEL (CONT'D) I simply knew what to do.
LIONEL (CONT'D) When the war was over I kept being a therapist to earn a living.
LIONEL (CONT'D) When the lads were old enough, I thought, "Alright Lionel, you've always wanted to be an actor, one last go."
LIONEL (CONT'D) I pretended it was our trip home to Mother England, the Great Australian Pilgrimage.
BERTIE To Harley Street?!
LIONEL Cashed in our return tickets.
LIONEL I had three months rent.
BERTIE So you set yourself up on Harley Street as an actor?
BERTIE Harley Street, don't you know, is for doctors!
LIONEL The plaque says, `L.
LIONEL Logue.
LIONEL Speech Specialist'.
LIONEL No mention of a medical degree.
LIONEL No mention of any degree.
LIONEL Some of the diggers I'd helped had come to England.
LIONEL They made referrals.
LIONEL My practice flourished.
LIONEL My acting, however, did not.
BERTIE Well enough to deceive me.
LIONEL Lock me in the Tower.
BERTIE I would if I could!
LIONEL What crime?
BERTIE You've saddled this nation in its moment of peril with a voiceless King.
BERTIE Destroyed the happiness of my family...all for the sake of ensnaring a star client you knew you couldn't possibly assist!
Lionel sits down on the chair of Edward the Confessor.
Leaning against it is the great two-handed sword of St.
George.
BERTIE (CONT'D) What're you doing?
BERTIE (CONT'D) Get up!
TKS/Seidler/09/17/08 102.
LIONEL I'm tired.
BERTIE You can't sit there!
LIONEL Why not?
LIONEL It's a chair.
BERTIE It's the Chair of Edward The Confessor!
BERTIE The throne upon which every King for six and a half centuries has been crowned.
LIONEL It's falling apart.
LIONEL People have carved their initials into it.
LIONEL Needs a stone to keep from blowing away.
BERTIE That's the Stone of Scone!
BERTIE The Stone of Destiny that was once Jacob's pillow.
LIONEL You believe such ballocks I don't care how many royal backsides have sat on it, it's a building block with handles attached.
LIONEL You're just like me, an actor with tawdry stage props you choose to believe are real.
BERTIE Listen to me...
LIONEL Listen to you?!
LIONEL By what right?
BERTIE Divine right, if you must!
BERTIE I'm your King!!!
LIONEL Noooo you're not!
LIONEL Told me so yourself.
LIONEL Said you didn't want it.
LIONEL So why should I listen to a poor stuttering bloke who can't put one word after another?
LIONEL Why waste my time listening to you?
BERTIE Because I have a right to be heard!
LIONEL Heard as what?!
BERTIE A man!
BERTIE I HAVE A VOICE!!!
TKS/Seidler/09/17/08 103.
LIONEL Well then...you're cured.
BERTIE Stop trying to squirm off the hook.
LIONEL Bertie, you'll make a bloody good king.
LIONEL And you know it.
Bertie stares at him.
A familiar voice is heard from the shadows.
VOICE Your Majesty?
The Archbishop of Canterbury.
COSMO LANG You'll be relieved to learn I've found a replacement specialist.
COSMO LANG Impeccable credentials.
There's a long silence.
BERTIE That won't be necessary.
COSMO LANG The matter's already been settled.
COSMO LANG For your own well-being.
BERTIE What did you say?
COSMO LANG Your Majesty's function is to consult...and to be advised.
COSMO LANG You didn't consult, but you've just been advised.
BERTIE Now I advise you, so listen carefully.
BERTIE ...in this personal matter I will make my own decision.
COSMO LANG May I remind you, you do not place the crown upon your own head.
BERTIE And may I remind you, it is my head upon which the crown is placed!
TKS/Seidler/09/17/08 104.
COSMO LANG This will end badly.
Lang turns on his heel.
Lionel ignores what has just happened.
LIONEL In hushed tones the BBC commentator paints a picture for the world, as you stand at the altar divested of your robes.
LIONEL Trumpets echo through the Abbey.
LIONEL The incessant rain clears miraculously as a shaft of sun streams through the stained-glass window catching your golden tunic and bathing you in light like a mediaeval knight.
LIONEL And you are King!
The faint CLICKING WHIR of a film projector is heard.
On the screen: archive footage of the Coronation, capturing the pomp and ceremony.
Cigar smoke rises up.
The voices of Churchill and Lang can be heard.
COSMO LANG I was much moved
WINSTON CHURCHILL There were tears in my eyes too, Your Grace, particularly when I saw you and the Dean of Westminster cannoning into each other.
COSMO LANG That's been edited.
WINSTON CHURCHILL More tears when our new Monarch started towards his throne, only to be brought to an abrupt halt owing to one of the Bishops treading on his robe.
COSMO LANG To the world, all went splendidly.
WINSTON CHURCHILL Amidst a vitrine of glittering jewels, bobbing tiaras, and heaving bosoms.
The footage freezes momentarily.
TKS/Seidler/09/17/08 105.
COSMO LANG Now, Winston, I have something which will bring tears to your eyes.
The archive footage continues, but it is not of the Coronation.
David and Wallis visiting the Fuhrer in Germany: Hitler gallantly kissing Mrs Simpson's hand while Goring and the Duke of Windsor beam; David giving the Nazi salute.
FREEZE FRAME.
The lights come on.
For once, Churchill is speechless.
COSMO LANG (CONT'D) There's no doubt: David is planning a comeback.
COSMO LANG (CONT'D) And will succeed if our King continues to falter.
COSMO LANG (CONT'D) Though Bertie miraculously survived the Coronation he continues to stumble very badly indeed.
COSMO LANG (CONT'D) Soon he must broadcast to the world.
COSMO LANG (CONT'D) Hitler will be listening.
COSMO LANG (CONT'D) David will be listening.
COSMO LANG (CONT'D) Stalin and Roosevelt will be listening.
COSMO LANG (CONT'D) Everyone will be listening.
COSMO LANG (CONT'D) God help us.
BERTIE (V.O.) "In this grave hour...
Bertie and Logue are rehearsing.
BERTIE "In this grave hour...
BERTIE " Sorry.
LIONEL Try again.
BERTIE "In this grave hour...
LIONEL Turn the halts into pauses, during which you say to yourself, "God save the King".
BERTIE I say that all the time, but apparently no one's listening.
LIONEL Use the silence.
LIONEL Long pauses add solemnity to great occasions.
BERTIE Then I'm the solemnest king who ever lived.
BERTIE Lionel, I can't do this!
TKS/Seidler/09/17/08 106.
Logue tries to protest, Bertie over-rides.
BERTIE (CONT'D) If I am to be King...where is my power?
BERTIE (CONT'D) May I form a Government on my own, appoint or dismiss a Prime Minister, chose an Ambassador, levy a tax or declare a war?
BERTIE (CONT'D) None of these things.
BERTIE (CONT'D) Yet I am the seat of all authority.
BERTIE (CONT'D) Why?
BERTIE (CONT'D) Because the Nation believes when I speak, I speak for them.
BERTIE (CONT'D) Yet I cannot speak!
Logue totally ignores the outburst.
LIONEL Take it from the top.
LIONEL "In this grave hour..."
BERTIE "In this grave hour, p-p-perhaps..."
LIONEL Go on...
BERTIE The letter`P' is always difficult.
LIONEL Get a running start, put the words all together.
LIONEL `Perhaps-the-most-fateful...'
BERTIE "In this grave hour...perhaps-the-most- fateful...in our history..."
LIONEL Beaut.
BERTIE "...
BERTIE I send to every household of my peoples...both at home and overseas..."
LIONEL (SINGS) Doo-dah, doo-dah.
BERTIE "...this message...
LIONEL (SINGS) Five miles long...
TKS/Seidler/09/17/08 107.
BERTIE "...spoken with the same depth of feeling for each one of you...
BERTIE as if I were able..."
LIONEL In your head, now: "Bugger, bugger, bugger!
LIONEL Damn, damn, damn!
LIONEL All those bloody blighters are going to have to listen to me!" Can you dance?
BERTIE What?
LIONEL Helps relax the body.
LIONEL Waltz?
BERTIE I prefer pipes.
LIONEL Thought you might.
LIONEL Dance with me.
LIONEL One, two, one-two-three- four.
LIONEL One, two, one- two-three-four.
LIONEL "For the second time..."
LIONEL one-two-three-four "...
LIONEL in the lives of most of us..."
LIONEL one, two, one-two-three- four "...
LIONEL we are at war."
LIONEL Three, four.
Dancing at arm's length with Logue, Bertie repeats:
BERTIE "For the second time...
BERTIE in the lives of most of us...
BERTIE we are at war."
BERTIE One-two- three.
BERTIE (continues on) "Over and over again...
BERTIE we have tried to find a peaceful way...
BERTIE out of the differences...
BERTIE between ourselves...
BERTIE and those who are now our enemies."
BERTIE Bugger, bugger, bugger!
BERTIE Fuck, fuck, fuck!
LIONEL You'll be ready.
BERTIE The shilling you won...
BERTIE still have it?
LIONEL Of course.
TKS/Seidler/09/17/08 108.
Bertie holds out his hand, demandingly.
Somewhat hurt, Lionel hands it over.
BERTIE I'll return it.
Bertie leaves with the shilling, exiting the back way.
Logue opens the waiting room door.
LIONEL Willie!
LIONEL Where's your mum?
WILLIE She had to work.
LIONEL You've been waiting here, alone, all this time?
Willie nods again.
Then, haltingly:
WILLIE I heard the King.
LIONEL Did you?
WILLIE He sang.
WILLIE And shouted rude words.
LIONEL He did.
Willie beams.
LIONEL (CONT'D) Would you like to sing, dance, and shout rude words?
WILLIE (NO STUTTER) I would!
LIONEL Why am I not surprised?
The dreaded BBC microphone.
The room has been transformed into an ad hoc broadcasting studio for this all-important occasion.
TKS/Seidler/09/17/08 109.
The BBC News Reader and Floor Manager are there, along with a small cluster of technicians putting finishing touches to their equipment.
FLOOR MANAGER Think he'll manage?
BBC NEWS READER I've heard he may not even show.
The Floor Manager tries to warn him with his eyes.
Bertie has entered with Elizabeth and Logue.
The Reader wishes he could sink into the floor.
Bertie says nothing, but approaches the looming microphone, while Logue and Elizabeth watch nervously.
BERTIE `Walk up to the bloody thing boldly, stare it square in the eye, man to man.'
BBC NEWS READER If you'll be so kind, to let me show you...
BERTIE I already know.
BERTIE My father taught me.
He spreads the fingers of one hand, touches the apparatus with the little finger, thumb to chin.
The Reader scurries off and tells the others.
BBC NEWS READER His father taught him.
BBC NEWS READER I taught his father.
BERTIE Bugger bugger bugger...bloody bloody bloody...
ELIZABETH Bertie, do make sure that's not switched on!
LIONEL You're going to be splendid.
LIONEL And if you're not?
BERTIE They'll bloody well have to listen to me anyway.
BERTIE Right?
TKS/Seidler/09/17/08 110.
LIONEL Bloody right.
Lang and Churchill have entered.
Elizabeth forces herself to greet them graciously.
ELIZABETH Mr. Prime Minister, Your Grace, how kind of you to join us.
COSMO LANG Wouldn't miss this for the world.
COSMO LANG Congratulations.
COSMO LANG Neville didn't last long, did he?
COSMO LANG Talking to Hitler.
WINSTON CHURCHILL My tenure will be shorter, if the King fails tonight.
Bertie and Logue speak privately.
BERTIE No matter how this turns out, I wish to thank you.
BERTIE For asking such dreadful questions.
BERTIE What can I do in recompense?
LIONEL I've always wanted to be knighted.
BERTIE Sorry.
BERTIE That would raise too many questions.
LIONEL Understood.
Bertie takes something from his pocket.
BERTIE Your shilling.
BERTIE Told you I'd give it back.
LIONEL Keep it for good luck.
BERTIE No, you won this, fair and square.
The object is a silver medal.
Bertie pins it to Logue's jacket.
TKS/Seidler/09/17/08 111.
BERTIE (CONT'D) Made from the melted coin.
BERTIE (CONT'D) Designed it myself, hope you like it, Lionel old friend.
BERTIE (CONT'D) May I call you that?
LIONEL My greatest honour, Bertie.
LIONEL One final question.
BERTIE Oh dear.
LIONEL Do you believe you're King?
A very long pause.
BERTIE Almost.
The red light on the microphone starts to blink.
Logue joins the others.
The Reader is at a smaller microphone near the ad hoc `broadcast booth.
Five, four, three, two...
BBC NEWS READER Good evening, this is the BBC National and World programme, broadcasting from Buckingham Palace.
BBC NEWS READER His Majesty, the King.
During this, Bertie's hands begin to shake, the pages of his speech rattle like dry leaves, his throat muscles constrict, the Adam's apple bulges, his lips tighten...all the old symptoms reappear.
Several seconds have elapsed since the Reader finished.
It seems an eternity.
Elizabeth grasps the sides of her chair with white knuckles.
Lang's eyes roll heavenward.
Churchill studies the situation, ready to leap into the breach.
Bertie and Logue stare at each other.
Logue smiles, perfectly calm, totally confident in the man he's worked with.
His confidence is contagious.
Bertie takes a deep breath and lets it out slowly.
His hands grow steady, his throat muscles relax...all the things he's practiced.
TKS/Seidler/09/17/08 112.
The luminous dial of a wireless.
Unbearable silence.
Then:
BERTIE (V.O. RADIO FILTER) In this grave hour, perhaps the most fateful in our history, I send to every household of my peoples, both at home and overseas...
This is being listened to by Myrtle and the boys.
The boys look at their mum.
Suddenly they explode with cheers as the radio address continues:
In homes, pubs (where we see the man with the rosacea nose), clubs, hotels, boarding houses, factories, mines, prisons, a shearing shed in New Zealand, cattle station in Australia, sites in India, South Africa, loci around the Commonwealth and Empire.
China.
Japan.
The Kremlin.
The White House.
Hitler's mountain top wolf den.
The South of France (where David and Wallis listen dolefully.)
During this, the address continues, with dramatic pauses to be sure, but no real hesitations.
BERTIE (V.O. ON RADIO) ...this message spoken with the same depth of feeling for each one of you as if I were able to cross your threshold and speak to you myself.
BERTIE (V.O. ON RADIO) For the second time in the lives of most of us we are at war.
BERTIE (V.O. ON RADIO) For we are called, with our allies, to meet the challenge of a principle which, if it were to prevail, would be fatal to any civilized order in the world.
BERTIE (V.O. ON RADIO) It is the principle which permits a State, in the selfish pursuit of power, to disregard its treaties and its solemn pledges; which sanctions the use of force, or threat of force, against the sovereignty and independence of other States.
BERTIE (V.O. ON RADIO) Such a principle, stripped of all disguise, is surely the mere primitive doctrine that might is right, and if this principle were established throughout the world, the freedom of our own country and of the whole British Commonwealth of Nations would be in danger.
TKS/Seidler/09/17/08 113.
BERTIE (V.O. ON RADIO) (CONT'D) But far more than this - the peoples of the world would be kept in the bondage of fear, and all hopes of settled peace and of the security of justice and liberty among nations would be ended.
BERTIE (V.O. ON RADIO) (CONT'D) This is the ultimate issue which confronts us.
End the montage with a return to the exterior of Buckingham Palace.
Outside, stand solemn crowds, listening to the speech on loudspeakers.
PAN THEIR FACES, the faces of England, stalwart and resolved.
BERTIE (CONT'D) For the sake of all that we ourselves hold dear, and of the world's order and peace, it is unthinkable that we should refuse to meet the challenge.
BERTIE (CONT'D) It is to this high purpose that I now call my people at home and my peoples across the seas, who will make our cause their own.
BERTIE (CONT'D) I ask them to stand calm, firm, and united in this time of trial.
BERTIE (CONT'D) The task will be hard.
BERTIE (CONT'D) There may be dark days ahead, and war can no longer be confined to the battlefield.
BERTIE (CONT'D) But we can only do the right as we see the right, and reverently commit our cause to God.
The two girls listen to their father on the radio.
BERTIE (V.O. ON RADIO) If one and all we keep resolutely faithful to it, ready for whatever service or sacrifice it may demand, then, with God's help, we shall prevail.
Lilibet's expression tells it all - she can hear it, her father is truly King.
Bertie, in his quiet way is totally in command, and utterly magnificent.
Everyone in the room is awed as he concludes: TKS/Seidler/09/17/08 114.
BERTIE (CONT'D) We may all find a message of encouragement in the lines which, in my closing words, I would like to say to you: `I said to the man who stood at the Gate of the Year, "Give me a light that I may tread safely into the unknown."
BERTIE (CONT'D) And he replied, "Go out into the darkness, and put your hand into the Hand of God.
BERTIE (CONT'D) That shall be to you better than light, and safer than a known way.'" May the Almighty Hand guide and uphold us all.
IN THE AD HOC `CONTROL BOOTH' AREA - the Manager makes a `cut' gesture to Bertie, he's off the air, the red light on the microphone goes out.
The Manager points, and the red light on the Reader's microphone goes on.
BBC NEWS READER This concludes the BBC broadcast of the King's Speech.
Another `cut' gesture from the Floor Manager, the red light goes out and the transmission is concluded.
The Floor Manager looks to the Reader.
BBC NEWS READER (CONT'D) He wasn't perfect.
BBC NEWS READER (CONT'D) Not perfect...
BBC NEWS READER (CONT'D) But by God...
BBC NEWS READER (CONT'D) He moved me.
AT THE MAIN BBC MICROPHONE - Bertie waits for the verdict of his peers.
Churchill first:
WINSTON CHURCHILL Couldn't have said it better myself.
The ultimate compliment.
Lang next.
COSMO LANG I'm speechless.
ELIZABETH Thank God.
She goes to Bertie and kisses him tenderly on the cheek, takes his hand, then Logue's.
TKS/Seidler/09/17/08 115.
ELIZABETH (CONT'D) Well done, Bertie.
ELIZABETH (CONT'D) Well done...
ELIZABETH (CONT'D) ...Lionel.
ELIZABETH (CONT'D) Well done.
She leaves the two men together.
LIONEL I always called you Bertie.
LIONEL Today, I call you King.
He offers his hand.
But instead of taking it, Bertie takes him by the shoulders and gives him a hug.
This is a long way from the five pace rule.
The last barrier has fallen.
Scroll:
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
