ZERO DARK THIRTY
Written by
Mark Boal
October 3rd, 2011
We hear the actual recorded emergency calls made by World Trade Center office workers to police and fire departments after the planes struck on 9/11, just before the buildings collapsed.
We listen to fragments from a number of these calls...starting with pleas for help, building to a panic, ending with the caller's grim acceptance that help will not arrive, that the situation is hopeless, that they are about to die.
DANIEL I own you, Ammar.
DANIEL You belong to me.
DANIEL Look at me.
DANIEL This is DANIEL STANTON, the CIA's man in Islamabad - a big American, late 30's, with a long, anarchical beard snaking down to his tattooed neck.
DANIEL He looks like a paramilitary hipster, a punk rocker with a Glock.
DANIEL (CONT'D) If you don't look at me when I talk to you, I hurt you.
DANIEL (CONT'D) If you step off this mat, I hurt you.
DANIEL (CONT'D) If you lie to me, I'm gonna hurt you.
DANIEL (CONT'D) Now, Look at me.
DANIEL (CONT'D) His prisoner, AMMAR, stands on a decaying gym mat, surrounded by four GUARDS whose faces are covered in ski masks.
DANIEL (CONT'D) Ammar looks down.
DANIEL (CONT'D) Instantly: the guards rush Ammar, punching and kicking.
DANIEL (CONT'D) Look at me, Ammar.
DANIEL (CONT'D) Notably, one of the GUARDS wearing a ski mask does not take part in the beating.
Daniel and the masked figures emerge from the interrogation room into the light of day.
They remove their masks and we see that one is a beautiful young woman in her mid-twenties.
She has a pale, milky innocence and bright blue eyes, thin and somewhat frail looking, yet possessing a steely core that we will come to realize is off-the-charts.
This is MAYA, a CIA targeter and subject-matter expert on her first overseas assignment.
DANIEL Are we gonna board up these windows or what?
Just off the plane from Washington, you're rocking your best suit for your first interrogation, and then you get this guy.
It's not always this intense.
MAYA I'm fine.
MAYA She's not.
DANIEL Just so you know, it's going to take awhile.
DANIEL He has to learn how helpless he is.
DANIEL Let's get a coffee.
MAYA No, we should go back in.
MAYA Something about the strange intensity of her expression makes Daniel reconsider and he turns back to the interrogation room.
DANIEL You know, there's no shame if you wanna watch from the monitor.
DANIEL She shakes her head.
DANIEL (CONT'D) Alright.
DANIEL (CONT'D) At the door, Daniel hands the ski mask back to Maya.
DANIEL (CONT'D) You might want to put this on.
MAYA You're not wearing one.
MAYA Is he ever getting out?
DANIEL Never.
Ammar, bruised from the beating, is restrained with ropes.
Maya stands a few feet behind Daniel, attentive, wary of what is to come.
This is her first interrogation and she is on the verge of vomiting from the stench in the room.
She looks around at the sound-proofed walls, the puddles of water on the floor.
DANIEL Right now, this is about you coming to terms with your situation.
DANIEL It's you and me, bro.
DANIEL I want you to understand that I know you, that I've been studying you for a very long time.
DANIEL I could have had you killed Karachi.
DANIEL But I let you live so you and I could talk.
You beat me when my hands are tied.
I won't talk to you.
DANIEL Life isn't always fair, my friend.
DANIEL Did you really think that when we got you, I'd be a nice fucking guy?
AMMAR You're a mid-level guy.
AMMAR You're a garbage man in a corporation.
AMMAR Why should I respect you?
DANIEL And you're a money man.
DANIEL A paperboy!
DANIEL Daniel paces around Ammar, anger rising.
DANIEL (CONT'D) A disgrace to humanity!
DANIEL (CONT'D) You and your uncle murdered three thousand innocent people.
DANIEL (CONT'D) I have your name on a five-thousand dollar transfer via Western Union to a 9/11 hijacker.
DANIEL (CONT'D) He leans into Ammar's ear.
DANIEL (CONT'D) Uncomfortably close.
DANIEL (CONT'D) And you got popped with 150 kilograms of high explosives in your house!
And then Daniel smiles, laughs.
Mercurial.
DANIEL (CONT'D) I'm just fucking with you.
DANIEL (CONT'D) Beat.
DANIEL (CONT'D) He laughs again.
DANIEL (CONT'D) I don't want to talk about 9/11.
DANIEL (CONT'D) What I want to focus on is the Saudi group.
DANIEL (CONT'D) Daniel shows him a photo.
DANIEL (CONT'D) That there is Hazem al-Kashmiri.
DANIEL (CONT'D) And I know this dude is up to some serious shit, and what I want from you is his Saudi email.
Feel free to jump in.
Ammar, bro, I know that you know this dude, just give me his email...and I will give you a blanket.
I will give you a blanket and some solid food.
No response from Ammar.
Daniel starts putting on his gloves.
DANIEL (CONT'D) I know that you know him.
AMMAR I told you before, I won't talk to you.
DANIEL Have it your way.
DANIEL (CONT'D) Let's go.
DANIEL (CONT'D) It all happens in a flash: in one swift motion, Daniel pushes Ammar to the floor, the guards pin his limbs, and Daniel smothers Ammar's face with a towel.
DANIEL (CONT'D) Ammar thrashes.
DANIEL (CONT'D) Daniel considers his next move.
Grab the bucket.
Maya follows Daniel's gesture to the corner of the room, where there's an ICE CHEST filled with WATER and a PLASTIC
DANIEL (CONT'D) Put some water in it.
DANIEL (CONT'D) She dips the pitcher in the water, hands shaking.
DANIEL (CONT'D) C'mon, let's go.
DANIEL (CONT'D) The stress and strain on her face is enormous as she brings the bucket back to Daniel.
DANIEL (CONT'D) Daniel starts pouring the water on Ammar's face, which is now covered by a towel.
DANIEL (CONT'D) Ammar thrashes with rising panic.
DANIEL (CONT'D) Hazem was a friend of Ramzi Yousef, you guys met in Tunisia back in the 70s.
AMMAR I don't know, you asshole.
AMMAR Maya shakes her head "no."
MAYA That's not credible.
Why are you doing this to me?
DANIEL You're a terrorist, that's why I'm doing it to you.
AMMAR Fuck you.
AMMAR Daniel pours water over the towel so it hits Ammar's nose.
DANIEL I want emails of the rest of the Saudi group.
DANIEL Give me emails of the rest of the Saudi group!
DANIEL Give me one email, and I will stop this!
DANIEL Ammar doesn't speak.
DANIEL He can't.
DANIEL (CONT'D) Who's in the Saudi group, and what's the target?
DANIEL (CONT'D) Where was the last time you saw bin Laden?
DANIEL (CONT'D) WHERE WAS THE
Daniel throws the pitcher, rips the rag off Ammar's mouth: and water spurts out - Ammar nearly drowned.
He gasps for air.
DANIEL (CONT'D) This is what defeat looks like, bro.
DANIEL (CONT'D) Your jihad is over.
DANIEL (CONT'D) Daniel stands.
DANIEL (CONT'D) Get him up.
DANIEL (CONT'D) The guards bring Ammar to his feet.
DANIEL (CONT'D) Daniel, shifting his persona yet again, touches Ammar's face and speaks to him with the comforting tenor of a therapist.
DANIEL (CONT'D) Try to understand the concept here.
DANIEL (CONT'D) I have time, you don't.
DANIEL (CONT'D) I have other things to do, you don't.
It's cool that you're strong.
I respect it, I do.
But in the end, everybody breaks, bro.
It's biology.
Dan and Maya exit.
They've learned nothing.
A colorful, dusty city.
Busy markets.
Poor children.
Dense traffic.
Meanwhile, across town:
National flags.
Imposing buildings.
Armed guards.
The outpost of a superpower.
Maya drives through the checkpoint and up to the main gate.
Descending the lobby staircase with Daniel is JOSEPH BRADLEY, Chief of Station, Pakistan, a smooth, vain, sophisticated former case officer who hasn't quite buffed all the blood out of his fingernails.
BRADLEY How did it go the other night?
DANIEL It was good.
DANIEL The local cops need tactical help.
DANIEL But he's Tier fucking One, baby.
DANIEL There's your money maker.
BRADLEY This is the guy that's KSM's nephew?
BRADLEY What's his issue?
DANIEL He's being a dick.
BRADLEY If he's trying to outsmart you, tell him about your PhD.
DANIEL I am going to have to turn up the heat.
DANIEL He needs to give us the Saudi group now.
DANIEL They reach the lobby, where they can see Maya sitting in the holding area.
DANIEL They walk towards her as Bradley considers what Daniel is asking for.
BRADLEY He's gotta have that - given the family ties.
BRADLEY Permission granted, Daniel reassures his boss.
DANIEL Tight with his uncle, prints all over the 9/11 money.
DANIEL Daniel knocks on the glass for Maya to come in.
DANIEL (CONT'D) Was I lying or what?
DANIEL (CONT'D) The guard opens the door and Maya comes through - not many females come through that door.
Maya, this is Joseph Bradley, our illustrious station chief.
Joe and I did Iraq together.
BRADLEY And we continue our Christian mission here.
BRADLEY Nice to meet you.
MAYA You too, Sir.
BRADLEY How was your flight?
BRADLEY They walk down the lobby towards the Secure Wing.
MAYA Fine.
DANIEL She's been having a great time ever since she got in, isn't that right?
BRADLEY How do you like Pakistan so far?
MAYA It's kinda fucked up.
BRADLEY You volunteered for this didn't you?
MAYA No.
MAYA Bradley smiles.
MAYA He knew she didn't volunteer.
MAYA They reach a secure area and Bradley checks Maya through an electronic door.
Third floor, northeast corner.
She goes through and Daniel and Bradley watch her walk away.
DANIEL Don't you think she's a little young for the hard stuff?
BRADLEY Washington says she's a killer.
DANIEL The children's crusade.
BRADLEY They want the next generation on the field.
BRADLEY Listen, I have a meeting with ISI in twenty minutes.
DANIEL They're slow rolling us in Lahore - you might want to bitch about that.
BRADLEY Did you see the cable from London?
DANIEL Dude, I've been in a dark room with another man for the last two days.
Maya finds her desk.
It's covered with grime.
She tries to clean it as best she can, then sits and looks at the blank log-in screen of her computer.
INT. AMERICAN EMBASSY CIA SECTION - CONFERENCE ROOM A group of thirty-somethings filing in for a meeting, chatting, comradery, taking seats around a conference table.
We will get to know: JACK, mid-40s, a scruffy teddy bear, the liaison from the National Security Agency (NSA).
JESSICA, 30s, an experienced targeter, and the only woman in the station who wears a skirt.
JACK Some dude tells the Malaysian station that his nephew works with a guy who knows a guy--
JESSICA Here we go.
JACK Hold on - He goes to a big feast in Bangkok about a year ago.
JACK The guest of honor?
JACK Usama bin Laden.
JACK Laughter in the room.
JACK (CONT'D) So I say, was Tupac there too?
JESSICA Right, but you forgot - you forgot Mullah Omar.
J.J.
and JEREMY, two case officers, continue the banter:
This is worth 5 million bucks.
J.J. You know we're going to have to chase it down.
JEREMY That's me, man.
JEREMY No job too small.
JACK That's why I have a gift for you, my friend.
JACK Jack hands Jeremy a piece of paper.
JACK Daniel and Maya enter, a little late.
DANIEL Everyone, this is Maya.
DANIEL Maya, everyone.
DANIEL (CONT'D) Please don't ask how it's going with Ammar because she's not going to fucking tell you.
JESSICA Ammar is withholding?
JESSICA Daniel nods.
JESSICA (CONT'D) (reading from her
Washington assesses that Abu Faraj is officially our new number three - JESSICA moves to a wall chart of AQ leadership and repositions Abu Faraj's mugshot to number three in the line, two down from Usama bin Laden.
Meanwhile, in the background, the riffs continue -
DANIEL - Best man for it.
JACK London station is already asking if we think he's in contact with anyone in the U.K.
JEREMY Like we're just keeping it from them.
JEREMY Jessica sits back down and gets down to business.
JESSICA The Jordanians are being really helpful with Ammar's transit papers.
JESSICA Jessica passes Daniel a file.
DANIEL Any imminent threats in here?
JESSICA They want the Consulate, the Marriott, it's low security.
JESSICA And they've got Majid Kahn talking about gas stations in the US.
DANIEL And that's a conversation?
DANIEL Jessica shrugs.
DANIEL At this point, she believes that it is merely a conversation - not a fully realized plot.
JESSICA Honestly?
JESSICA There are six hundred questions in there.
JESSICA I'd concentrate on Heathrow.
JESSICA The Saudis.
JESSICA Does it matter what Faraj thinks about Heathrow?
JESSICA How much latitude does he get to pick targets?
DANIEL I think he'll give up the Saudis.
DANIEL But Heathrow is gonna be tough.
DANIEL Anyway.
DANIEL Anything from last night?
J.J. Quetta base thinks they have a bead on the Arabs that escaped, and they're going to meet with the ISI this afternoon, hopefully to set up a raid down there.
DANIEL Great.
JEREMY And Lahore reporting ISI down there was painfully slow last night.
JEREMY Again.
JEREMY I'm beginning to think it's not incompetence.
DANIEL I agree, I spoke to the Chief about that.
DANIEL Anything on bin Laden?
JESSICA A farmer on the Afghan border near Tora Bora reports: a diamond shaped pattern in the hills, tall male in the center of the diamond, flanked by four guards.
JESSICA It's consistent with UBL's movements.
JEREMY That's supposed to be his royal guard?
MAYA That's pre-9/11 behavior.
MAYA Jessica doesn't appreciate the challenge.
We don't have reason to believe he's changed security tactics.
MAYA We invaded Afghanistan.
MAYA That's a reason.
MAYA And so the rivalry begins.
J.J. Hey, boss, I got a guy for five thousand bucks, he can set up a taxi stand and snoop around a bit.
DANIEL No, don't need him, the diamond sighting is bullshit.
DANIEL See if the Paks will send someone to talk to the farmer.
DANIEL Anything else?
DANIEL We need to be putting runs on the board against Faraj.
DANIEL Speak to the case officers who didn't see fit to make it today.
DANIEL And thank them.
INT. MAYA'S APARTMENT - ISLAMABAD The loud WAILING of the early morning call to prayer from the loudspeakers of a nearby mosque wakes Maya on the couch.
Daniel and the guards enter Ammar's cell with Maya.
Daniel switches on a floodlight, awakening Ammar.
DANIEL Let's take it easy today, huh?
DANIEL Daniel hands Ammar a bottle of orange juice and a bag of falafel.
DANIEL (CONT'D) Hungry?
DANIEL (CONT'D) The food in here sucks so I got you some of this.
DANIEL (CONT'D) Ammar grabs the lunch sack and scarfs down the falafels.
DANIEL (CONT'D) Richard Reid, wow.
DANIEL (CONT'D) I was thinking about him.
DANIEL (CONT'D) The guy gets a bomb in his shoe on a plane.
DANIEL (CONT'D) Unbelievable.
DANIEL (CONT'D) You know him, don't you?
DANIEL (CONT'D) Slowly, Ammar nods.
AMMAR Yes.
DANIEL I'm glad you said that.
DANIEL I have an email from you to him.
DANIEL I've had all your coms for years, bro.
DANIEL Who else is in your Saudi group?
AMMAR I just handed out some cash for them.
AMMAR I didn't know who the guys were.
DANIEL When you lie to me, I hurt you.
AMMAR Please.
DANIEL I believe you.
DANIEL I do, I believe you.
DANIEL Beat.
DANIEL (CONT'D) Do you want the water again, or do you want something else?
AMMAR Please.
DANIEL Just give me a name.
Daniel jumps up.
AMMAR (CONT'D) I don't know.
AMMAR (CONT'D) Daniel kicks out the chair from under Ammar.
AMMAR (CONT'D) The masked guards walk to the rope pulleys.
DANIEL You see how this works?
DANIEL You don't mind if my female colleague sees your junk, do you?
DANIEL Daniel pulls down Ammar's pants.
DANIEL Maya flinches at the bare nakedness.
DANIEL (CONT'D) Dude, you shit your pants.
Daniel turns to Maya -
DANIEL (CONT'D) You stay here, I'll be back.
DANIEL (CONT'D) Daniel goes out, leaving Maya standing alone in front of the naked, chained man.
DANIEL (CONT'D) Ammar looks at her imploringly and she struggles to meet his eyes.
AMMAR Your friend is an animal.
AMMAR Please, help me.
AMMAR Please.
AMMAR A long beat.
MAYA You can help yourself by being truthful.
MAYA The door handle turns.
MAYA It occurs to Maya that perhaps Daniel was testing her resilience, too, as Daniel re-enters with a DOG COLLAR in his hand.
DANIEL This is a dog collar.
DANIEL Daniel unhooks Ammar, snaps the collar and leash around his neck, as Ammar cries out against the humiliation.
Maya flinches.
Daniel is relentless:
DANIEL (CONT'D) You determine how I treat you.
DANIEL (CONT'D) Now Daniel drags Ammar on all fours, pulling him by the leash.
DANIEL (CONT'D) I'm going to walk you.
DANIEL (CONT'D) Maya watches in horror as Daniel walks Ammar to a far corner
of the room, then leans down to address his victim:
DANIEL (CONT'D) What the fuck do you think is going on, Ammar?
DANIEL (CONT'D) Wahleed has already told me that you know.
DANIEL (CONT'D) At last, Daniel reaches an area of the room where there is a large wooden box resting on a platform.
DANIEL (CONT'D) This box sucks.
DANIEL (CONT'D) I'm going to put you in it.
DANIEL (CONT'D) Ammar tries to speak but can't get a word out.
DANIEL (CONT'D) When is the attack?
Sunday.
DANIEL Sunday?
DANIEL Sunday where?
DANIEL This Sunday or next Sunday?
DANIEL Ammar mumbles, almost inaudibly.
AMMAR Monday.
DANIEL Is it Sunday or Monday?
DANIEL Ammar doesn't answer.
DANIEL The masked men approach.
DANIEL (CONT'D) Which day is it?
DANIEL (CONT'D) Partial information is treated as a lie.
AMMAR Saturday.
AMMAR Beat.
AMMAR The masked men open the box.
AMMAR (CONT'D) Sunday!
AMMAR (CONT'D) The guards grab Ammar and carry him to his wooden tomb.
AMMAR (CONT'D) He
shouts with his last reserve of energy:
AMMAR (CONT'D) Monday!
DANIEL Ammar, which day?
Monday, Tuesday, Beat.
AMMAR (CONT'D) Thursday.
AMMAR (CONT'D) Beat.
AMMAR (CONT'D) Friday.
AMMAR (CONT'D) Daniel slams the box shut.
AMMAR (CONT'D) Once again, he's learned nothing.
ECU: a magazine CLICKS into the receiver of a black assault rifle.
The weapon, carried by a BEARDED ARAB MAN dressed in street clothes, rises to shoulder height.
- The man enters the hallway of the KHOBAR RESIDENTIAL TOWERS - And immediately opens fire on TWO WESTERN MEN he happens to find inside, killing them both.
- The CRACK of the shots sends the rest of the residents into a panicky, screaming dash for cover - As he strides quickly down the hall, he finds three other RESIDENTS scrambling for safety, and shoots and kills them all.
INT. AMERICAN EMBASSY CIA SECTION - CONFERENCE ROOM CU TV: news footage of the massacre.
INT. AMERICAN EMBASSY CIA SECTION - CONFERENCE ROOM Daniel, Jessica, and Maya look on in defeat.
INT. AMERICAN EMBASSY CIA SECTION - CONFERENCE ROOM The "Saudi" attack they tried to prevent by pressuring Ammar has occurred.
Don't worry about the Saudis, they'll take care of business.
DANIEL Yeah, now.
JESSICA You warned them - they didn't take you seriously - this is what happens.
JESSICA It's not on you.
DANIEL Who said that?
DANIEL Zied?
DANIEL Fuck him.
DANIEL This is on me.
DANIEL Ammar is on me!!
DANIEL And it's on her!!
DANIEL We can't let this be a win-win for
JESSICA No, no, no.
JESSICA You had - what - days - brief custody - and an unresponsive ally.
JESSICA The way you do this is you look ahead.
JESSICA London.
JESSICA Heathrow.
JESSICA Mass casualties.
JESSICA That plan is still active.
MAYA Ammar doesn't have a clue about what happened.
JESSICA He knows.
MAYA How?
JESSICA You have to be really careful with people in KSM's circle - they're devious.
MAYA He's not going to talk about attacks on the homeland.
MAYA He's going to withhold operational details on the KSM network and probably on bin Laden.
MAYA But he's been in complete isolation, he doesn't know we failed.
MAYA We can tell him anything.
DANIEL Bluff him?
MAYA He hasn't slept, Dan.
MAYA He's clueless.
You don't remember, do you?
You - me: same same.
Bad memory.
While GUARDS move in the deep b.g., Daniel and Maya are seated at a picnic table with an appetizing spread of Arabic food.
Short term memory loss is a side effect of sleep deprivation.
It should come back to you.
The Guards bring a prisoner to the table and remove his hood: Ammar.
He stares weakly at the table.
I don't know.
How can I remember?
MAYA After we kept you awake for 96 hours, you gave us names of some of your brothers and saved the lives of a lot of innocent people.
DANIEL Which is the smart thing to do, you're starting to think for yourself.
DANIEL Ammar is lost.
DANIEL But the food is tempting.
DANIEL (CONT'D) Eat up!
DANIEL (CONT'D) You earned it.
DANIEL (CONT'D) Ammar eats.
DANIEL (CONT'D) So you flew via Amman to Kabul to hang out with your uncle?
DANIEL (CONT'D) Mukhtar.
AMMAR How did you know that?
DANIEL I told you man, I know you.
DANIEL Alright, you got me - flight manifests.
DANIEL It must've been pretty fucked up for you guys after 9/11.
DANIEL What did you do after the invasion and before you went back to Pesh?
AMMAR After 9/11 I had to choose: fight, to protect our turf - or run.
You chose to fight.
Ammar looks Daniel right in the eyes.
AMMAR I wanted to kill Americans.
AMMAR We tried to get into Tora Bora but the bombing was too high.
AMMAR We couldn't cross.
MAYA Sorry, who is the "we" in that sentence?
AMMAR Me and some guys who were hanging around at that time.
I can eat with some other dude and hook you back up to the ceiling?
AMMAR Hamza Rabia, Khabab al-Masri, and Abu Ahmed.
AMMAR Maya makes notes on her pad.
MAYA Who's Abu Ahmed?
MAYA I've heard of the other guys.
AMMAR He was a computer guy with us at the time.
AMMAR After Tora Bora, I went back to Pesh - as you know - and he went North, I think, to Kunar.
MAYA What's his family name?
AMMAR Abu Ahmed al-Kuwaiti.
MAYA Abu Ahmed means "father of Ahmed", it's a kunya.
MAYA (CONT'D) Ammar, I know the difference between a war name and an Arabic name.
DANIEL She got you there, dude.
AMMAR I swear to you both: I don't know his family name.
AMMAR I would have never asked him something like that.
AMMAR It's not how my uncle worked.
AMMAR My uncle told me he worked for bin Laden.
AMMAR I did see him, once, about a year ago, in Karachi.
AMMAR He read us all a letter from the Sheikh.
MAYA A letter?
DANIEL What did it say?
DANIEL Daniel offers Ammar a smoke.
DANIEL (CONT'D) Cigarette?
DANIEL (CONT'D) Ammar accepts.
DANIEL (CONT'D) Daniel's lights it.
AMMAR It said "Continue the jihad.
AMMAR The work will go on for a hundred years."
We fade into a dimly lit research room, where Maya is alone watching interrogation video recordings on an array of monitors.
Some of the videos are rough; but most simply depict two people talking.
The video she's watching now shows a hooded prisoner sitting in a filthy room, the walls smeared with red stains.
SOLDIER INTERROGATOR You and I are gonna talk about some of the guys in the training camps, yeah?
SOLDIER INTERROGATOR The prisoner sits in a chair.
SOLDIER INTERROGATOR He's hooded, but relaxed.
PRISONER Ok.
SOLDIER INTERROGATOR Some of these brothers have done some bad things, and what I want to do is I want to separate them from the people like you.
PRISONER Definitely, yeah.
SOLDIER INTERROGATOR There was a guy called Abu Ahmed from Kuwait.
PRISONER Yes, I remember him.
PRISONER A nice guy.
SOLDIER INTERROGATOR How close was he?
SOLDIER INTERROGATOR What was his relationship to the leadership?
PRISONER I don't know.
SOLDIER INTERROGATOR Did he eat with you guys - did he eat with the good guys - or did he eat with the leadership?
PRISONER I don't know, sir.
PRISONER I have no idea about things like that.
SOLDIER INTERROGATOR Yes you do, you don't need an idea
Maya hits pause and we see that her desk is filled with open windows of interrogations: she is analyzing ten videos simultaneously, comparing them to each other.
She plays another video showing a Turkish prison.
When you met with Khalid Sheikh Mohammed, was this one of the facilitators?
The Interrogator flashes a picture.
The prisoner moans.
Is this Abu Ahmed?
PRISONER Yes.
INT. RESEARCH ROOM - LATER She fast forwards a video - shot in a Polish facility.
INT. RESEARCH ROOM - LATER The prisoner appears to be cold.
INTERROGATOR KSM, your boss.
PRISONER Mukhtar?
INTERROGATOR Mukhtar,'potato', you say 'potahto'.
INTERROGATOR I say 'fucking KSM', but yeah, 'Mukhtar.' After Mukhtar was captured, what did Abu Ahmed do?
PRISONER Abu Ahmed, I believe he went to work for The Sheikh.
INT. RESEARCH ROOM - LATER Maya is still in the research room.
INT. RESEARCH ROOM - LATER She's been going at this for hours and looks fatigued.
INT. RESEARCH ROOM - LATER CU SCREEN: a different INTERROGATOR from the previous video; PRISONER is an older man chained to a desk.
INT. RESEARCH ROOM - LATER The exchange is
in Arabic with an English subtitle on the screen:
PRISONER In Karachi, in 2003 or 2004.
INTERROGATOR He was carrying a letter from bin Laden?
INT. RESEARCH ROOM - LATER Still going, looking exhausted now, Maya manipulates the controls of yet another video clip with a different INTERROGATOR and PRISONER.
INT. RESEARCH ROOM - LATER We're now in a Moroccan facility.
INT. RESEARCH ROOM - LATER The interrogator shows him a photograph of a bearded man.
INT. RESEARCH ROOM - LATER Henceforth, The Photograph.
INTERROGATOR Is that him?
Abu Ahmed.
The interrogator holds The Photograph right in front of the prisoner's face, allowing us to see it as well.
INTERROGATOR Say again?
PRISONER Abu Ahmed.
PRISONER Abu Ahmed.
PRISONER Abu Ahmed.
PRISONER Freeze frame.
A Yemeni prison - the dialogue is a mix of French and English:
INTERROGATOR Abu Ahmed - is he the courier for bin Laden?
PRISONER Who knows who works directly for bin Laden?
PRISONER Let's say he's part of the mix.
INTERROGATOR Were there other people who carried messages from bin Laden?
PRISONER Sure.
INTERROGATOR How many other people?
Four or five.
INTERROGATOR Let's talk about them-- The image freezes.
INTERROGATOR Maya stares at the screen.
Maya is in the kitchen grabbing something to eat.
Jessica, the only other person working this late, walks in, pours herself some coffee.
JESSICA How's the needle in the haystack?
MAYA Fine.
JESSICA Facilitators come and go, but one thing you can count on in life is that everyone wants money.
JESSICA The rivalry is in full bloom.
JESSICA Sometimes it's friendly.
JESSICA Sometimes it's not so friendly.
You're assuming that Al Qaeda members are motivated by financial rewards.
They're radicals.
Correct.
You're assuming that greed won't override ideology in some of the weaker members.
MAYA Money for walk-ins worked great in the cold war, I'll give you that.
JESSICA Thank you.
MAYA Just not sure those tactics are applicable to the Middle East.
Maya hastily throws her clothes and a wig into a suitcase - the world's fastest packing job -
A sprawling shipyard in an industrial area.
A large MILITARY FRIGATE sits in the harbor.
A dark haired WOMAN and a MAN board the ship.
At first we don't recognize the woman with heavy makeup walking down the narrow corridor, and then we realize it's Maya in disguise.
She enters a vast cavernous hold accompanied by a middle aged Afghan man, thick shouldered with years of hard experience in his kind, somewhat sad eyes.
This fatherly man is HAKIM, a former political prisoner in Afghanistan and one of the CIA's most important assets.
In the galley, a PRISONER is chained to a table.
Hakim slides him The Photograph.
The prisoner speaks in Arabic.
He says he looks like Abu Ahmed.
MAYA Who did he work for?
MAYA Hakim translates.
MAYA Then the prisoner speaks.
It was mostly with Abu Faraj - they were always together.
MAYA What did he do for Faraj?
He carried messages from Faraj to bin Laden and from bin Laden back to Faraj.
Maya leans into Hakim -
MAYA We need to ask him something to see if he's telling the truth.
MAYA We don't know if he really knew Faraj.
MAYA Hakim speaks to the prisoner.
HAKIM He just told me the names of all of Faraj's children.
HAKIM I think he's telling the truth.
Maya is pitching Bradley in his office.
Bradley sits with his feet up on his desk, holding The Photograph.
Daniel is slouched on the couch in back.
Jessica is perched on the arm of the couch, bare legs crossed.
Bradley notices.
Maya stands.
MAYA Twenty detainees recognize that photo of Abu Ahmed.
MAYA They say he's part of the inner circle of guys who were hanging out in Afghanistan pre-9/11.
A lot of them say that after 9/11, he went to work for KSM.
When KSM got captured, he went to work for Abu Faraj, primarily as a courier from Faraj to bin Laden.
BRADLEY Well, that's good.
BRADLEY You still-
MAYA Yeah, we don't know if Abu is on the outside of the network - part of a series of cutouts and dead drops - or if he has a direct connection to bin Laden.
MAYA Does bin Laden invite him into the living room and hand him a letter directly?
MAYA Or is Abu just the last guy in a long line of couriers, so that's why everybody knows him?
BRADLEY That's not all you don't know.
BRADLEY You don't have his true name, and you don't have a clue of where he is.
MAYA We know that he's important.
MAYA The fact that everybody's heard of Abu Ahmed but nobody will tell me where he is suggests that.
BRADLEY Maybe.
BRADLEY Detainees could withhold his location for any number of reasons.
BRADLEY Perhaps they don't know; perhaps this Abu is just a cover story and he's really a fucking unicorn.
BRADLEY The withholding doesn't reveal what you want it to - does it?
MAYA No.
BRADLEY And if you did find him, you don't know that he'd be with bin Laden.
DANIEL We don't know what we don't know.
What the fuck is that supposed to mean?
DANIEL It's a tautology.
BRADLEY Listen, not one single detainee has said that he's located with the big guy, just that he delivers messages.
BRADLEY Am I wrong?
MAYA No.
BRADLEY No.
BRADLEY It's still good work.
BRADLEY (CONT'D) Let me know when you've got some actionable intelligence, preferably something that leads to a strike.
The city is in full swing on this bright mid-summer morning.
CARS and BUSES roll through the crowded streets.
Passengers inside the bus read newspapers, listen to music...
another ordinary day.
Then, the bus explodes!
File footage of the aftermath:
REPORTER This is what remains of the #10 bus, which was traveling through Tavistock Square...
Joseph Bradley sits at his desk.
The weight of the world on his shoulders.
On the television in the background, the news report continues, showing disaster footage of PEOPLE bloodied, screaming.
The war on terror is growing and spreading, like an octopus, throughout the base.
We trace the new tentacles of the CIA facility - more hangars, vehicles, PEOPLE moving to and fro.
REPORTER All around, groups of Londoners are standing on corners asking themselves
what has happened here, and who could possibly have done this?
We find Daniel trying to catch a moment of solitude...eating an ice cream cone and standing in front of a makeshift cage filled with wild MONKEYS.
The monkeys are watching Daniel intently, their hands gripping the wire cage.
Daniel playfully feeds them some of his ice cream.
A CIA GUARD approaches Daniel
You Agency guys are twisted.
The detainee is ready.
Daniel nods, weary.
Then a monkey reaches through the bars and steals the remainder of Daniel's ice cream cone.
He looks at the monkey and laughs.
Rain pelts the brown city, turning the gutter water black.
MAYA (PRE-LAP) I want you to understand that I know you.
MAYA (PRE-LAP) I have been following you and studying you for a long time.
MAYA (PRE-LAP) I chased you in Lahore.
MAYA (PRE-LAP) We find Maya entering the gates of a Pakistani prison.
MAYA (PRE-LAP) The weather makes the place seem especially bleak.
HASSAN GHUL, Al Qaeda financier, sits manacled to a desk.
MAYA I had you picked up instead of killing you because you're not a violent man and you don't deserve to die.
GHUL Thank you.
MAYA But you do have deep ties to Al Qaeda that I want to ask you about before you get sent to your next location, which might be Israel.
MAYA Ghul looks ashen.
MAYA (CONT'D) However, depending on how candid you are today, I may be able to keep you in Pakistan.
GHUL What do you want to know?
MAYA I'm going to ask you a series of questions based on your knowledge of Al Qaeda and your position as key financier for the organization.
GHUL I have dealt with the mukhabarat, I have no wish to be tortured again.
GHUL Ask me a question, I can answer it.
MAYA What can you tell me about Atiyah Abd al-Rahman.
GHUL He works for Zawahiri.
GHUL He's in charge of military tactics.
MAYA In what context have you ever heard the name Abu Ahmed?
GHUL He works for Faraj and bin Laden.
GHUL He is his most trusted courier.
GHUL Maya works hard to hide how pleased she is to have this confirmation.
GHUL She's not entirely successful.
MAYA What makes you say that?
GHUL He brought me many messages from the Sheikh.
MAYA Where did you last see him, and where is he now?
GHUL You will never find him.
MAYA Why is that?
GHUL Even I couldn't find him.
GHUL He always contacted me out of the blue.
GHUL He is one of the disappeared ones.
Pakistani families enjoy a fine summer day.
A BOMB is being strapped to a MAN'S leg by a PAKISTANI
You know how this works?
The man is terrified.
Just act naturally.
The Policeman finishes securing the bomb, and sends the man out the door (who we will later deduce is Abu Faraj's courier).
Faraj's Courier walks past playing children...
while from a nearby tower, Daniel observes.
After a moment, ABU FARAJ, who we recognize from his photograph, appears at the south end of the park.
Faraj walks in the direction of his courier, noting his
CHILDREN playing.
Several people in BLACK BURKHAS.
At last Faraj reaches an open area where he can see his courier face to face.
They exchange a nervous glance that conveys the danger: It's a trap.
Faraj spins to flee, but it's too late.
The black BURKHAS descend on him.
It turns out they are heavily armed Pakistani agents.
From on high, Daniel watches his captured prey.
Daniel and an armed guard escort a hooded and handcuffed Faraj to his cell.
DANIEL What do you like?
DANIEL Bob Marley?
DANIEL Reggae?
DANIEL Egyptian music?
DANIEL Just let me know, if there's music you like, I can make a call.
Daniel and the guards take Faraj to a cell laced with barbed wire and lock him inside.
DANIEL Can I be honest with you?
DANIEL I'm bad news.
DANIEL I'm not your friend.
DANIEL I'm not gonna help you.
DANIEL I'm gonna break you.
DANIEL Beat.
DANIEL (CONT'D) I've done it before.
DANIEL (CONT'D) Hey, wake up.
DANIEL (CONT'D) You haven't eaten in 18 hours, we've got to keep your energy up.
DANIEL (CONT'D) You hungry?
Guards force feed Faraj through a feeding tube.
INT. AMERICAN EMBASSY CIA SECTION - MAYA'S CUBICLE - DAY Bradley approaches Maya at her cubicle.
BRADLEY You're in luck, I got you a one-on- one with Faraj.
MAYA Seriously?
MAYA Thank you.
BRADLEY Don't thank me until you hear what I want for it.
BRADLEY He drops a folder on her desk.
BRADLEY (CONT'D) I want you to take care of all of this before your favorite subject.
MAYA Deal.
BRADLEY Don't you want to see what's in the folder?
MAYA You want family ties, financial networks, media sources, disgruntled employees, imminent threats, homeland plots,
Thank you.
MAYA Foreign cells, health status, trade craft, recruiting tactics -- anything else?
Both Maya and Faraj look tired.
This has been going on for hours.
MAYA A lot of brothers told us Abu Ahmed was bin Laden's courier and that he worked very closely with you.
FARAJ You're thinking of Abu Khalid.
MAYA Who?
FARAJ Al Buluchi.
FARAJ My courier for the Sheikh.
MAYA Okay, so you're telling me that all the other brothers are wrong, and there's some famous Buluchi guy that is working for you and bin Laden that I've never even heard of?
FARAJ Why should you have heard of him?
MAYA What does this Buluchi guy look like?
FARAJ Tall, long white beard, thin.
FARAJ He uses a cane.
MAYA Kind of like Gandolf?
FARAJ Who?
MAYA When was the last time you saw him?
FARAJ A month ago, in Karachi, but I don't know where he is now.
FARAJ Sometimes I wouldn't even see him, he would just tell me where to leave the messages.
MAYA I don't believe you.
MAYA The GUARD in the room with them leans forward and SLAPS Faraj across the face.
MAYA Faraj's expression doesn't change and Maya herself remains flat and steady, unmoved by the violence.
MAYA She's not quite the same young lady she was a few years ago.
MAYA (CONT'D) You're not being fulsome in your replies.
FARAJ You can't force me to tell you something I don't know.
MAYA You do realize this is not a normal prison.
MAYA You determine how you are treated, and your life will be very uncomfortable until you give me information I need.
MAYA The guard slaps Faraj again.
MAYA Faraj is impassive.
INT. INTERROGATION ROOM - LATER Maya looks on impassively as Faraj is subjected to harsh treatment.
Maya is retching in the stall.
Maya walks around the facility, quiet at this hour, and finds another insomniac, Daniel, by the monkey cage.
The cage is empty.
MAYA Faraj is completely denying knowing Abu Ahmed, and that's using every measure we have.
DANIEL He's either going to withhold or die from the pressure you're putting on him.
MAYA Do you want to take a run at him?
DANIEL No.
MAYA No?
MAYA Since when?
DANIEL You know, I've been meaning to tell you: I'm getting outta here.
MAYA What?
MAYA You okay?
DANIEL I'm fine.
DANIEL I've just seen too many guys naked.
DANIEL It's gotta be over a hundred at this point.
DANIEL I need to go do something normal for awhile.
MAYA Like what?
DANIEL Go to Washington, do the dance, see how that environment works.
You should come with me.
Be my number two.
You're looking a little strung out yourself.
Maya looks at Dan.
No longer the man he once was.
She doesn't hide her disappointment.
MAYA I'm not going to find Abu Ahmed from
They both look at the empty cage, clocking the irony.
DANIEL They killed my monkeys.
DANIEL Something about an escape.
DANIEL Can you fucking believe that?
MAYA Sorry, Dan.
DANIEL Look, Maya, you gotta be really careful with detainees now.
DANIEL The politics are changing and you don't want to be the last one holding a dog collar when the oversight committee comes.
MAYA I know.
DANIEL And watch your back when you get back to Pakistan.
DANIEL Everyone knows you there now.
Back in Pakistan, the country has indeed changed to a more militarized police state, and as we establish the new environment, we find Maya's grey sedan...
The car pulls up to a checkpoint manned by PAKISTANI POLICE.
The Policeman look at the car - look at the plate - the plate is diplomatic - they walk around the car and stop at the window - shine their bright light right into Maya's eyes.
A POLICEMAN motions for her to roll down her window.
POLICEMAN Where are you going?
MAYA To the Marriott.
MAYA I assume you noticed the dip plates.
POLICEMAN But you have a bag - The policeman motions to a DUFFEL BAG resting on the rear seat.
MAYA It's a gym bag.
MAYA Maya does not get out of the car.
MAYA She stares at him defiantly.
MAYA He advances forward a bit.
MAYA She rolls up her window, flicks the door lock, and starts dialing her cell phone.
MAYA The policeman walks away to rejoin his group.
MAYA The police confer.
MAYA The original policeman returns, this time with several other cops.
MAYA They knock on the glass.
MAYA Hard.
MAYA Maya stares straight ahead.
Jessica is waiting at the table in a beautifully appointed room.
Maya walks in, flustered.
MAYA Fucking checkpoints.
MAYA Maya sits down, absorbed in her Blackberry.
JESSICA Maya?
MAYA Yeah.
JESSICA We're socializing.
JESSICA Be social.
JESSICA Maya puts away her blackberry.
Okay.
JESSICA Look, I know Abu Ahmed is your baby, but it's time to cut the umbilical cord.
MAYA No, it's not.
JESSICA So Faraj went south on you - it happens.
JESSICA There are still cells in London and Spain planning the next round of attacks.
MAYA I can work on it at the same time - plus I think it's a good thing that he lied.
JESSICA No, not at the expense of protecting the homeland, you can't.
JESSICA Wait a minute, why is it a good thing?
MAYA You sound just like Bradley.
MAYA He doesn't believe in my lead either.
It's a good thing because the fact that Faraj withheld on Abu Ahmed is revealing.
The only other thing he lied about was the location of bin Laden himself.
That means Faraj thinks Abu Ahmed in as important to protect as bin Laden.
That confirms my lead.
JESSICA Or it's confirmation bias.
We're all just worried about you, okay?
Is that okay to say?
Maya rubs her eyes, not liking where the conversation is going.
She forces a smile.
JESSICA (CONT'D) Where's Jack?
MAYA He's probably stuck in some check- point somewhere.
JESSICA You two hooked up yet?
MAYA Hello, I work with him.
MAYA I'm not that girl, that fucks.
MAYA It's unbecoming.
JESSICA So?
JESSICA A little foolin' around wouldn't hurt you.
So no boyfriend.
Do you have any friends at all?
She doesn't.
Jessica's phone rings -
JESSICA (CONT'D) It's Jack.
Hey - that's okay -
As alarms wail, Maya struggles to her feet, grabs Jessica by the arm, and they stumble to safety.
Toward the destroyed kitchen, helping each other over obstacles, twisted metal, gaps in the concrete, etc, past injured workers and burning flames.
They continue moving through the debris as the smoke intensifies.
They find each other's hands and grab tightly.
The destroyed Marriott.
REPORTER The blast left a crater 10 meters wide in front of the hotel.
REPORTER The Marriott, one of the most popular destinations for locals and Westerners...
We're high above the wild hinterlands of the Hindu Kush, gliding over the rocky slopes and the pine forests.
We move from peak to peak until we find a remote valley, and we zoom down...
and nestled in the valley we can just make out the barest outlines of a tiny village of mud huts.
Now we are inside a hut and we've shifted to the perspective of a hand held camera, as if someone inside this stone age interior is filming on our behalf, and we see a hard floor, thin gaps in the walls, and FIVE TRIBAL ELDERS talking casually, eating and drinking tea.
We pan across the weathered faces, long beards, and see a video recorder resting on a ledge.
Jessica strides excitedly, almost breaking into a run, through the warren of cubicles that lead to Maya's desk.
INT. AMERICAN EMBASSY CIA SECTION - MAYA'S CUBICLE - DAY Jessica beaming as she approaches Maya.
JESSICA The Jords have a mole!
MAYA What?
MAYA Jessica pops a CD into Maya's computer, loads a file that plays the same video clip we have just seen.
JESSICA He made this video to prove his bona fides.
MAYA Shut the fuck up!
MAYA The camera stops on one man, BALAWI.
Humam Khalil al-Balawi, he's a Jordanian doctor.
He's really motivated.
Maya practically bolts out of her chair.
Together, they start walking towards Bradley's office -
MAYA This could be it!
JESSICA This is it.
CONTINUOUS Bradley has just finished watching the video.
CONTINUOUS Maya and Jessica are in his office waiting for his verdict.
JESSICA He's right there in the inner circle.
BRADLEY I don't buy it.
BRADLEY Didn't you tell me yourself nobody turns on Al Qaeda?
JESSICA The Jords worked him for a year.
JESSICA Dinners, money.
JESSICA They've convinced him that it's his patriotic duty to turn on Al Qaeda and get rich doing it.
BRADLEY Yeah, so the Jords say.
You're right.
We can't rely on the Jords.
We have to evaluate him face to face.
He may not be that smart.
He may be full of shit - but we have to talk to him to find out.
MAYA The key is to meet him so we can figure out for ourselves what he can actually do.
BRADLEY He really asked for a dialysis machine?
BRADLEY You can fill the damn thing with poison.
Maya and a few analysts are watching TV - President-elect Obama is being interviewed on 60 Minutes when Jessica comes into the room with disappointing news -
JESSICA The meeting with Balawi is off.
JESSICA He can't come here to Islamabad.
MAYA Can't or won't?
JESSICA He's not going to travel - security
The TV interview with Obama reaches the subject of enhanced interrogation, and the women pause to listen to the President- elect declare, "America does not torture."
Then they continue:
JESSICA (CONT'D) He wants us to go to him.
JESSICA (CONT'D) He'll meet in Miram Sha or the tribals.
MAYA He knows we're white.
MAYA You'll get kidnapped up there.
MAYA DAVID, an analyst, adds his two cents to the conversation -
DAVID We could do it somewhere else - Germany, or the UK?
DAVID He's got a clean passport.
JESSICA He's not going to travel out of Al Qaeda territory.
DAVID And you're not going to him.
JESSICA I'm not.
JESSICA Believe me.
We're stuck.
DAVID What about Camp Chapman?
DAVID Afghanistan.
DAVID That could be safe territory.
We survey the sprawling base from above.
Helicopters and Humvees traverse the base.
Jessica applies icing to a birthday cake as she cradles a
This may be going overboard, but I baked him a cake!
MAYA O.S. Muslim's don't celebrate with cake.
JESSICA Don't be so literal.
JESSICA Everyone likes cake.
JESSICA It's not too late for you to come, you know.
JESSICA It will be fun.
Maya sits in front of a series of monitors.
She watches a live Predator feed.
MAYA I don't want to be a straphangar.
MAYA It's your show.
MAYA You were the first to see the potential in this.
JESSICA Come on!
JESSICA We've got lots of wine!
JESSICA The target on Maya's monitor disappears in a puff of smoke.
MAYA Cool.
MAYA Bring me back a bottle.
JESSICA I will.
Jessica pours two glasses of wine and raises a toast to her colleague, JOHN.
JESSICA Not to get technical, but this guy is actually the first big break we've had since 9/11.
JESSICA To big breaks and the little people that make them happen.
JESSICA Clink.
JESSICA (CONT'D) So far, everything he's said we've cross checked and it's proved legit...
JESSICA (CONT'D) and I think the money is persuasive.
JESSICA (CONT'D) 25 million dollars?!
JESSICA (CONT'D) That buys a new life.
JOHN Do you think he might be exaggerating his access?
JESSICA Possibly.
JESSICA But Al Qaeda needs doctors and they are short staffed and that could explain his rise.
JESSICA In six months to a year, if he doesn't fuck up, he could be called in to treat bin Laden.
JESSICA And at that moment, with 25 mil on the table, I think he gives up the Big Man.
JESSICA And if he doesn't, we kill him.
The same gathering as the day before, waiting under the merciless sun.
Jessica turns to her crew, which includes LAUREN, a young operative, ZIED, a Jordanian intelligence agent, and the base's CIA SECURITY GUARD, among others.
They rehearse the impending meeting.
JESSICA So John?
JESSICA When he arrives, I'll set the tone, and then I'll flip it to you - and you'll talk about asset protection.
JOHN Roger that.
JESSICA Then Lauren, I know you want to get some questions in there - but give Balawi time after John speaks.
JESSICA We'll cover the basics and have his birthday cake, then we'll get to the nitty gritty.
Jessica turns to Zied.
JESSICA (CONT'D) Is that order okay, or do you want to introduce everyone?
I'll introduce you, and you introduce your team.
He knows this is a high level meeting.
SECURTY GUARD Quick question: all is taking place inside our main building?
JESSICA Right.
JESSICA And Lauren?
JESSICA Washington will want real time updates so please stay on top of that.
JESSICA Be concise.
JESSICA The Director is in the loop.
JESSICA And I wouldn't be surprised if he doesn't update the President.
Yeah, I'm on it.
They take in the possibilities.
JESSICA Now, I just need to get Balawi's ass down here.
Waiting and waiting.
No cars approach.
The sun beats down.
Several hundred yards before the Camp entrance is a beat-up SEDAN.
The car pulls up to the checkpoint but doesn't proceed.
JESSICA Why are there gate guards there?
JESSICA We talked about this, no one is supposed to be there when my source arrives.
JESSICA You might have spooked him already!
SECURTY GUARD Procedures only work if we follow them every time.
JESSICA This time is different - I'm sorry I can't explain, but it's for a good cause.
SECURTY GUARD Look, I'm responsible for everyone's safety, okay?
SECURTY GUARD It's not just about you.
JESSICA I just need them to go away for a minute.
JESSICA You can search him as soon as he gets here.
The Security Guard pauses, then into his radio:
All stations, go ahead and stand down.
Roger.
The guards move away from their post.
The sedan drives past the gate into a maze of barriers.
We follow the car as it navigates the maze of HESCO barriers, kicking up a cloud of dust.
EXT. CAMP CHAPMAN - CIA COMPOUND Jessica runs back to her team and flashes a thumbs up.
EXT. CAMP CHAPMAN - CIA COMPOUND She smiles and pulls out her phone, sending a text.
He's here.
Brb
MAYA Cool!
MAYA The car navigates the second set of barriers.
Maya types on her computer: Wassup you talking yet
EXT. CAMP CHAPMAN - CIA COMPOUND Jessica looks up to see the car approaching and puts the phone back in her pocket.
EXT. CAMP CHAPMAN - CIA COMPOUND The sedan is now 50 yards away.
SECURTY GUARD Okay, he's coming.
SECURTY GUARD We're gonna search him when he gets here.
SECURTY GUARD Everyone prepares.
SECURTY GUARD The car gets closer and closer, a driver in front and a passenger in back.
Maya texts again:
SECURTY GUARD Answer when you can.
EXT. CAMP CHAPMAN - CIA COMPOUND The sedan pulls to a stop.
EXT. CAMP CHAPMAN - CIA COMPOUND A BLACKWATER GUARD taps on the backseat window.
EXT. CAMP CHAPMAN - CIA COMPOUND Balawi exits on the passenger side.
EXT. CAMP CHAPMAN - CIA COMPOUND His free hand is in his pocket.
BLACKWATER GUARD Is he supposed to limp like that?
SECURTY GUARD Take your hand out of your pocket!
SECURTY GUARD Hey!
BALAWI Allahu Akbar, Allahu Akbar
BLACKWATER GUARD Get you hand out of your pocket!
BALAWI Allahu Akbar.
BALAWI Jessica's smile fades And Balawi detonates a suicide vest hidden under this jacket and the resulting shrapnel storm pulps the crowd, massacring them all -
Maya looks at her computer screen.
She sees her last instant message..And waits for a response.
Beat.
Maya looks up, concern on her face.
The explosion smoke still hovers over Camp Chapman.
News reporting of the attack plays over the horrific image.
Maya huddles on the floor under the corner of her desk.
The office has thinned out, and most people have gone home for the day.
Maya is crouched in the corner.
A wounded animal.
Jeremy, the case officer from the conference room, approaches and gives Maya a computer disc.
JEREMY You okay?
JEREMY No response.
I didn't think this day could get any worse, but bad news from Saudi intelligence.
The courier guy, Abu Ahmed, is dead.
It's a detainee video.
Maya still fighting to contain her grief, takes the file as an almost welcome distraction.
She puts the disc into her computer and hits play.
CU COMPUTER SCREEN: A PRISONER being interviewed by a CIA CASE OFFICER holds the photo of Abu Ahmed we've seen so many times.
PRISONER He's dead, in Afghanistan, 2001.
PRISONER I buried him with my own hands.
INTERROGATOR Where?
PRISONER Kabul.
PRISONER Maya stares at the screen.
MAYA I don't believe this.
JEREMY Sorry, Maya, I always liked this lead.
JEREMY Jeremy leaves Maya at her computer.
JEREMY She continues to stare at the screen.
Maya is still by herself.
Her friend Jack approaches -
Hey.
Sorry, I just got here.
What are you gonna do?
MAYA I'm going to smoke everybody involved in this op, and then I'm going to kill bin Laden.
MAYA Off the darkness in her eyes we -
The staff has gathered to hear a word from the boss in a large conference room; it's packed shoulder to shoulder with dozens of people, including Maya, Jim, Jack, Hakim, and Bradley at the front.
GEORGE WRIGHT, Chief of the Afghanistan Pakistan Department, has just flown in from D.C. A big man, striding quickly into the room with the street roll of the Bronx projects he grew up in, George looks ready for a brawl.
GEORGE I want to make something absolutely clear.
GEORGE (CONT'D) If you thought there was some secret cell somewhere working Al Qaeda, I want you to know that you're wrong.
GEORGE (CONT'D) This is it.
GEORGE (CONT'D) There's no working group coming to the rescue.
GEORGE (CONT'D) He stares at his staff.
GEORGE (CONT'D) There's nobody else, hidden away on some other floor.
GEORGE (CONT'D) There is just us.
GEORGE (CONT'D) And we are failing.
GEORGE (CONT'D) We're spending billions of dollars.
GEORGE (CONT'D) People are dying.
GEORGE (CONT'D) We're still no closer to defeating our enemy.
GEORGE (CONT'D) They attacked us on land in 98, by sea in 2000, and from the air in 2001.
GEORGE (CONT'D) They murdered three thousand of our citizens in cold blood, and they've slaughtered our forward deployed.
GEORGE (CONT'D) And what the fuck have we done about it?
What have we done?
We have twenty leadership names and we've only eliminated four of them.
Beat.
GEORGE (CONT'D) I want targets!
GEORGE (CONT'D) Do your fucking jobs, bring me people to kill!
The office has grown bigger and busier and the cubicle maze is filled with many new faces of young agents excited to be in Pakistan.
Sitting alone at her desk we find Maya just as she's finishing a report.
She gets up, crosses the room and goes to the desk of a young woman who reminds us in her idealistic enthusiasm of the way Maya was six years ago.
This is DEBBIE.
DEBBIE Hi.
DEBBIE I painstakingly combed through everything in the system and found this.
She hands Maya a file.
DEBBIE (CONT'D) It's him.
DEBBIE (CONT'D) He was one of ten names on a watch list sent to us by the Moroccans after 9/11: Ibrahim Sayeed.
DEBBIE (CONT'D) They told us to watch out for him, apparently they think his whole family and extended family is bad and has ties to KSM.
He was picked up for fake papers and a doctored exit visa leaving Afghanistan, traveling through Morocco en route to Kuwait.
Abu Ahmed al- Kuwaiti.
This must be Abu Ahmed.
MAYA Doesn't matter, but I wish I had that five years ago.
MAYA How come I never saw it before?
DEBBIE Nobody saw it, most likely.
DEBBIE There was a lot of white noise after 9/11, countries wanting to help out, we got millions of tips and...
Things got lost in the shuffle.
Human error.
Maya turns her attention back to the WHITE BOARD and as Debbie keeps talking we follow Maya's gaze across the row of MUG SHOTS of Al Qaeda personnel.
While a few of the men are African or are distinctive looking for other reasons, most of them look fairly similar in that they're all wearing the same type of clothes and have the same trademark long gnarly beards.
Anyway I thought you should know about it.
I just want to say I've heard a lot about you.
You inspired me to come to Pakistan.
Maya's eyes narrow.
She keeps looking at the WHITE BOARD
DEBBIE (CONT'D) Maybe you'll let me buy you a kabob sometime?
Don't eat out.
It's too dangerous.
Maya stares at the Al Quaeda mugshots - a thought crosses her mind.
Maya on the speaker phone to Daniel.
We intercut.
Daniel is now a suit in Langley.
Dan, Debbie found Abu Ahmed!
DANIEL Fuck.
DANIEL Really?
He was in the files this whole time.
The family name is Sayeed.
DANIEL Ok, but he's dead.
DANIEL So doesn't that make him a little less interesting to you?
MAYA O.S. He may not be.
MAYA O.S. We now know that Abu Ahmed is one of eight brothers.
MAYA O.S. All the brothers in the family look alike.
MAYA O.S. Three of them went to Afghanistan.
MAYA O.S. Isn't it possible that when the three eldest brothers grew beards in Afghanistan, they started to look alike?
MAYA O.S. I think the one calling himself Abu Ahmed is still alive.
MAYA O.S. The picture we've been using is wrong.
MAYA O.S. It's of his older brother, Habeeb.
MAYA O.S. He's the one that's is dead.
DANIEL Okay, what are you basing this on?
MAYA We have no intercepts about Abu Ahmed dying.
MAYA (CONT'D) We just have a detainee who buried somebody who looked like Abu Ahmed.
MAYA (CONT'D) But if somebody as important as Abu Ahmed had died, they'd be talking about it online in chat rooms all over the place.
MAYA (CONT'D) Plus, the detainee said that Habeeb died in 2001.
MAYA (CONT'D) We know that Abu Ahmed was alive then, trying to get into Tora Bora with Ammar.
MAYA (CONT'D) That means it's probably one of the other brothers that's dead.
DANIEL O.S. In other words, you want it to be true.
MAYA Yes, I fucking want it to be true.
MAYA Maya slams the desk.
DANIEL O.S. Calm down.
DANIEL O.S. Beat.
MAYA I am calm.
DANIEL O.S. State your request.
MAYA Move heaven and earth and bring me this fucking Sayeed family's phone number.
A dark (window shades down) executive office, where in the shadows a white American man in a nice suit is kneeling on a prayer rug and saying the Islamic daily prayers.
Daniel waits as the man recites the prayers and presses his pale forehead to the carpet.
This is WOLF.
He is the head of the agency's COUNTER TERRORISM CENTER (George's boss).
DANIEL As-Salamu alaykum.
WOLF Alaykum salam.
DANIEL I need a couple hundred thousand.
DANIEL Four max.
WOLF Where you gonna get that?
DANIEL From you.
WOLF You think so?
DANIEL This could crack open the facilitator Maya's been looking for by giving us a phone number.
She's your killer, Wolf.
You put her on the field.
(reciting a phrase from the KORAN, in Arabic, then loosely
Allah rewards those who strive and fight over those that sit behind a desk.
WOLF nods.
If the blatant attempt to play on his Muslim belief bothers him, he doesn't show it at all.
WOLF As you know, Abu Ghraib and Gitmo fucked us.
WOLF The detainee program is now fly paper.
WOLF We got senators jumping out of our asses, and the Director is very concerned.
WOLF They will not stop until they have a body.
WOLF There it is.
WOLF The quid pro quo.
WOLF There's a reason he's called The Wolf.
WOLF Daniel considers all that he'll go through if he volunteers to be the fall guy for the controversial program.
DANIEL I ran it.
DANIEL I'll defend it.
Daniel and a KUWAITI BUSINESS MAN in a suit are drinking and ogling the RUSSIAN GIRLS prowling the place.
After a few sips of his drink.
DANIEL It's good to be back in Kuwait.
DANIEL It's good to see you again, it's been awhile.
DANIEL The businessman doesn't answer.
DANIEL (CONT'D) I need a favor.
KUWAITI BUSINESSMAN Why should I help you?
DANIEL Because we're friends.
KUWAITI BUSINESSMAN You say we are friends.
KUWAITI BUSINESSMAN How come you only call me when you need help?
KUWAITI BUSINESSMAN But when I need something - you are too busy to pick up the phone.
KUWAITI BUSINESSMAN I don't think we are friends.
DANIEL Fair enough.
DANIEL How about a V10 Lamborghini?
DANIEL How's that for friendship?
They wait while a Lamborghini SALESMAN, disheveled, clearly just awakened, unlocks the door of the dealership.
DANIEL (to the Kuwaiti
The poor fucker had to get out of bed.
As-salamu alaykum.
Thanks my friend.
They step inside and the salesman flicks on the lights revealing shiny cars displayed like jewels on rotating
platforms.
While the Kuwaiti businessman peers inside a silver model, Daniel confers with the salesman like he's bought twenty of these cars.
DANIEL Is this a Balboni?
DANIEL Fuck me.
DANIEL This is nice.
DANIEL What are you thinking?
KUWAITI BUSINESSMAN I think I'll choose this one.
KUWAITI BUSINESSMAN The salesman retreats to a back office.
DANIEL That's a nice choice, my friend.
DANIEL Daniel gives the Kuwaiti a slip of paper.
KUWAITI MAN Who is it?
DANIEL Who do you think?
DANIEL The guy's a terrorist.
DANIEL His mother lives here.
DANIEL I just need her phone number.
KUWAITI MAN There will be no repercussions in Kuwait?
DANIEL Somebody might die at some point in Pakistan.
DANIEL They shake hands.
Sound graphs of phone calls fill the screen.
We cruise through rows upon rows of server facilities, a single monitor in front traces a call to Rawalpindi, Pakistan.
Maya chews on a peanut butter & jelly sandwich.
Jack calls her on her cell.
MAYA Hey, Jack.
JACK You're not gonna like this, he's on the phone, but there's no team to deploy right now.
MAYA Fuck.
MAYA She dashes out runs down the hall to an Exit sign - bursts through the door to a staircase -
- Flies down the staircase - down to another floor, barges through the door -
The station's surveillance team leader, LARRY, unstraps his flack vest.
He looks like the kind of guy you don't mess with....so of course Maya barges into his space like a locomotive.
MAYA How come you haven't deployed a team to stay in Rawalpindi?
LARRY For one thing, it's dangerous.
LARRY For another, the area is too congested for us to be effective without some predictive intelligence.
MAYA That's why you should forward deploy - so you can shorten your response time.
LARRY Still, it wouldn't work.
MAYA Why?
LARRY The guy never stays on the phone long enough.
MAYA You haven't tried.
LARRY Look, I don't have the personnel.
MAYA That's bullshit.
LARRY As it is, my guys don't get any sleep tracking the threats within Pakistan.
LARRY Larry pushes past her to leave, and she follows him.
MAYA Right, I understand.
MAYA But I don't really care if your guys get sleep or not.
MAYA Maya looks at Larry's team sleeping on the couch.
The conversation continues in the bar, for Maya has not relented, although the tone is softer now.
She offers Larry a beer.
He takes it.
LARRY This guy you're obsessed with, what's his name again?
MAYA Abu Ahmed al Kuwaiti is the nom de guerre.
MAYA His true name, we think, is Ibraheem Sayeed.
MAYA His family lives in Kuwait.
LARRY Wasn't it, like, eight brothers - and a million cousins - that we know about - anyone could be calling home -
MAYA I know -
LARRY - It's not like he's saying, "Hey mom, it's me, the terrorist."
MAYA Over the course of two months, he's called home from six different pay phones, from two different cities, never using the same phone twice.
MAYA And when his mother asked him where he was, he lied.
MAYA He said that he was in a place in the country with bad cell reception -- implying he was in the Tribals -- but he was in
MAYA (CONT'D) a market in Peshawar.
MAYA (CONT'D) I'm sorry, but that's not normal guy behavior.
MAYA (CONT'D) That's tradecraft.
LARRY Maybe he just doesn't like his mom?
Look, if he talks about an operation, or refers to anything remotely fishy, I'll get on him.
Okay?
MAYA No.
MAYA Not okay.
MAYA Look, Abu Ahmed is too smart to tip his hand by talking about ops on the phone: he works for bin Laden.
MAYA The guys that talk about ops on the phone don't get that job.
MAYA Larry looks away.
MAYA (CONT'D) A lot of my friends have died trying to do this.
I believe I was spared so I could finish the job.
The girl is a true believer - as pure as they come.
Larry looks at her.
Her sincerity is persuasive.
And just like that, he decides to help her.
Hakim walks through a crowded call center.
Larry joins him from a back entrance.
They look around: nothing.
Hakim parks in front of the Rawal Call Center.
The call center is arranged into two rows of cubby-holes, each separated by a privacy wall.
Hakim searches the place, finds nothing.
CU TV SCREEN: News reports of the attemped NYC bombing.
REPORTER It is in surveillance video and pictures like this of the explosive- laden vehicle just moments before it was parked, that police hope to find the man who wanted so badly last night to leave a body count in Times Square.
The TV news report continues playing in the bg.
Bradley is moving as fast down a hallway.
Coming towards him like a shark from the other end of the hallway: Maya.
Bradley looks determined not to deal with her right now, and lowers his head, but she spreads her arms slightly and basically blocks his passage through the hallway
MAYA I really need to talk to you about beefing up our surveillance operation on the caller.
BRADLEY We don't have a surveillance operation on the caller.
BRADLEY Someone just tried to blow up Times Square and you're talking to me about some facilitator who some detainee seven years ago said might have been working with Al Qaeda?
BRADLEY Maya is practically shaking with zealous rage at her inability to bend Bradley to her will.
MAYA He's the key to bin Laden.
BRADLEY I don't fucking care about bin Laden.
BRADLEY I care about the next attack.
BRADLEY You're going to start working on American Al Qaeda cells.
BRADLEY Protect the homeland.
MAYA bin Laden is the one who keeps telling them to attack the homeland.
MAYA (CONT'D) If it wasn't for him, Al Qaeda would still be focused on overseas targets.
MAYA (CONT'D) If you really want to protect the homeland, you need to get bin Laden.
This guy never met bin Laden.
This guy is a free lancer working off the fucking internet.
No one has even talked to bin Laden in four years: he's out of the game, he may well even be dead but you know what you're doing?
You're chasing a ghost while the whole fucking network grows all around you!
For a moment she is silenced by Bradley's reprimand but then Maya's obsession speaks for her - and like a woman possessed she recklessly goes at him:
MAYA You just want me to nail some low level Mullah-crack-a-dulla so that you can check that box on your resume that says while you were in Pakistan you got a real terrorist.
MAYA But the truth is you don't understand Pakistan, and you don't know Al Qaeda.
MAYA Either give me the team I need to follow this lead, or the other thing you're gonna have on your resume is being the first Station Chief to be called before a congressional committee for subverting the efforts to capture or kill bin Laden.
BRADLEY You're fucking out of your mind.
MAYA I need four techs in a safe house in Rawalpindi and four techs in a safe house in Peshawar.
MAYA Either send them out or send me back to DC and explain to the Director why you did it.
Maya, despondent, sits at the bar, drinking a beer.
Jack approaches.
JACK Fuck the mom, we got the man himself.
JACK Jack puts a cell phone down on the counter.
JACK (CONT'D) Yesterday your caller bought himself a cell phone.
JACK (CONT'D) And every time his phone rings - (he taps the cell
- This phone will ring.
Did I hook you up?
Maya throws her arms around him.
MAYA I love you!
Larry drives his team around the narrow streets of Rawalpindi.
In the backseat, the COMPUTER TECH studies his laptop-like tracking device.
MAYA O.S. My guess is that he lives close to where he's making the calls, and it makes sense he'd be living in Rawalpindi because there's an Al Jezerra office there.
We focus on a MAP of Pakistan on the wall.
Maya is indicating neighborhoods in Rawalpindi.
She's briefing Bradley, Hakim, Larry and a few other people.
MAYA It would be convenient for him to drop tapes off if he's sending either from bin Laden or from an intermediary.
MAYA When he wants to make a call, he leaves the house, walks a few blocks, then switches on the phone.
MAYA We need to keep canvassing the neighborhood until we find him.
Larry is at the wheel, moving slowly through a dangerous part of town.
The streets narrow.
Two motorcycles suddenly pull around in front of Larry's van and stop.
The riders pull out guns.
LARRY We got a shooter!
LARRY Larry tries reversing but a compact car wheels in right behind them, and Larry slams on the brakes.
LARRY The TECH raises an M4.
TECH We're blocked.
HAKIM Let me talk to them.
Hakim gets out of the car and walks toward the men.
We can't hear what they're saying.
At last, Hakim comes back to the car.
HAKIM They said white faces don't belong here.
HAKIM If they don't move, shoot them.
HAKIM A tense beat while the men stare, then finally leave.
On a large wall map, Maya circles "Peshawar" in red.
Larry's SUV speeds onto a highway, weaving in and out of dense traffic.
In the backseat, the Computer Tech is getting tossed around, trying to hang onto the Geo Locating device in his lap.
The Geo Locator starts to BEEP - a blinking red light.
He's east of us.
Try the market.
The congestion thickens.
They slow to a crawl.
The SUV, stuck in traffic.
Can't move.
Larry leaps out of the car and heads into an open air market -
It's packed.
All MEN - most with traditional beards worn by Al Qaeda members - many talking on cell phones.
Impossible to tell who is who.
Impossible to find this needle in a haystack.
The search continues...
Hakim prowls a back alley.
Then goes up on a rooftop to survey the activity below.
Hakim is on a street corner conducting surveillance.
We follow him into a crowd and then lose sight...
We find him again, another street, another fruitless search.
As Hakim goes from street to street, we hear:
We got a signal on Tipu Road for ten minutes.
Then he went to Umar Road for five minutes.
Nogaza Road.
Darya Abad.
That's in the Umar Road area.
In Rawalpindi: Haider Road, Roomi Road.
He went to the Convoy Road, which is near the hospital.
So that's Haider, Roomi Road, Said, No Gaza, Taimur.
He made a call from Haifa Street, that's the spice district.
Jack and Maya click through the tracking maps on her computer screen.
JACK Lahore street, which is also in Pesh, thirty minutes.
JACK Wazir Bag Road, five.
JACK Nishterabad, five.
JACK Phandu Road, five minutes, the Grand Trunk Road, forty five seconds.
JACK There's no pattern.
JACK Sometimes he calls every two weeks - sometimes every three - there's no consistency - I can't predict when he's gonna make another call because the guy's erratic.
MAYA Do you think its intentional?
JACK It might be.
JACK Maybe it just looks erratic to us.
JACK I just can't tell.
INT. MAYA'S APARTMENT - ISLAMABAD Wearing a black burkha, Maya walks into her house and sinks into the couch.
INT. MAYA'S APARTMENT - ISLAMABAD She pulls off the head covering but doesn't bother to remove the burkha.
INT. MAYA'S APARTMENT - ISLAMABAD She switches on the TV.
INT. MAYA'S APARTMENT - ISLAMABAD If you didn't know her better, you'd think she'd gone native.
Find Maya driving up to a check point mobbed with PROTESTERS carrying signs - Joseph Bradley IS A CIA SPY!
KILL THE SPY!
Bradley is CIA, etc.
REPORTER Meanwhile, our chief foreign correspondent, Richard Engel, confirms the CIA's top spy in Pakistan has been pulled out of there.
The PROTESTERS have blocked the embassy check point.
It's going to take a long time to get through.
REPORTER He's been receiving death threats after being named publicly in a lawsuit by the family of a victim of a U.S. drone attack.
Several protesters notice her - they move to her car and start banging on it.
Maya and Bradley and several other STAFFERS watch the protest through a window -
The CROWD grows larger and more unruly.
MAYA ISI fucked you.
MAYA I'm so sorry Joseph.
MAYA It's the first time she's addressed him by his first name.
MAYA Startling, to hear kindness in her voice.
MAYA Joseph turns to reply then thinks better of it and walks away.
Larry's minivan chugs through the crowded markets.
TECH Still on tower three!
TECH Five.
TECH Signal getting stronger.
TECH Ten!
TECH Larry continues driving straight down the main road.
TECH (CONT'D) Fifteen.
TECH (CONT'D) Ten.
TECH (CONT'D) Signal's getting weaker.
We lost him - no signal.
LARRY Heading South.
LARRY The van passes horse-drawn carts, men on cell phones, fruit stands.
LARRY The Tech studies his screen.
TECH He's up at five again.
TECH Fifteen.
TECH Twenty.
Weaker now, he's shifted.
We're back to five.
I don't get it.
LARRY He's driving in circles.
LARRY Larry now drives very fast back to the main road.
LARRY (CONT'D) No change?
TECH No.
And now Larry stops in the middle of the market.
LARRY Let's hope he comes back around.
LARRY Beat.
TECH Twenty.
TECH Thirty.
TECH Forty!
TECH Fifty - we're within ten meters of him.
TECH Larry scans the street - sees a half dozen guys on cell phones.
TECH (CONT'D) He's really close.
LARRY Look at the cars.
LARRY He's in a vehicle.
Larry spots something:
LARRY (CONT'D) The guy with the phone in the white
They snap a photograph of a WHITE POTAHAR SUV.
LARRY (CONT'D) Is that him?
TECH Could be.
LARRY You got him?
TECH I got him.
LARRY I'm breaking off - The grey minivan pulls away.
INT. AMERICAN EMBASSY CIA SECTION - MAYA'S CUBICLE - DAY Larry's photograph of the WHITE POTAHAR SUV plops on Maya's desk.
MAYA Is this what I think it is?
LARRY The guy you've been looking for, geo- located on his cell phone in his white car.
MAYA Thank you!
LARRY If you're right, the whole world's gonna want in on this, so you gotta stick to your guns now.
The new Chief of Station, TIM ALEXANDER, barely looks up from his desk as Maya enters.
I'm amazed that you're still here.
(looks at his watch,
When can we grab lunch?
He sees that Maya, who hovers annoyingly over his desk, isn't gonna wait.
MAYA I need a picket line along the GT highway and men spaced at intervals along the road and at every exit.
ALEXANDER Maya, I know -
MAYA So you agree with me now.
MAYA This is important?
ALEXANDER No, I've just learned from my predecessor that life is better when I don't disagree with you.
A two lane highway.
Tucked on the side of the road is an OLD MAN with a cart of mangoes.
MAYA (V.O.) Our current hypothesis is that he lives somewhere along the highway, in one of the towns, or a medium sized city called Abbottabod, or up near Kashmir.
MAYA (V.O.) ECU: mango cart.
MAYA (V.O.) Nestled among the fruit is a BLACK RADIO.
Squatting in the dirt near a bus stop is another OLD MAN, watching passengers disembark from a bus.
MAYA (V.O.) Kashmir is interesting because it's a way station for the Tribals.
MAYA (V.O.) We stay with the old man for a while.
MAYA (V.O.) At last, the white POTAHAR SUV drives past.
MAYA (V.O.) He makes a note in his pad.
A nut seller, another CIA look out, scoops a handful of nuts into a bag for a CUSTOMER as he keeps an eye on CARS exiting the highway.
He takes note as the white POTAHAR passes him.
MAYA (V.O.) Abbottabod is interesting because we know from detainee reporting that Faraj stayed there, briefly in 2003.
The street is filled with compact cars.
MAYA (V.O.) The good news is he's driving a white SUV.
MAYA (V.O.) SUV's are actually pretty rare in Pakistan.
MAYA (V.O.) If he was driving a sedan or a compact, we'd be fucked.
MAYA (V.O.) Obviously this assumes he doesn't change vehicles.
MAYA (V.O.) Maya at her desk working and we realize that she has been typing all this in a cable she will email to Washington.
The building GUARD sees Maya heading out to her car.
Good morning.
MAYA Good morning, Amad.
MAYA Maya gets in her car.
MAYA The gate opens.
MAYA As she starts pulling out onto the street, suddenly a car drives up in front of her and THREE SHOOTERS come out and hammer Maya's Toyota.
INT. MAYA'S CAR - CONTINUOUS - Bullets spider webbing the glass as Maya slams the car into reverse -
- Maya's guard starts returning fire, but his aim is terrible.
- SHOOTERS bear down on Maya, pumping bullets into her armored car.
The gate closes, saving her, at the last possible moment.
INT. MAYA'S CAR - CONTINUOUS Maya shakes inside her vehicle.
Any American in Pakistan is a target, they don't necessarily know I'm CIA.
ALEXANDER Doesn't matter.
ALEXANDER You're on a list.
ALEXANDER Next time there might not be bulletproof glass to save you.
MAYA Yeah.
ALEXANDER And you, of all people, should know that once you are on their list, you never get off.
We'll keep up on the surveillance, as best we can.
Hakim paces on a street as the POTAHAR we've been following drives past him.
Hakim watches the vehicle enter a gated
The Langley Predator Bay is an impressive sight, a command center bristling with high-tech equipment.
The room is filled with TECHNICIANS.
George is in the center, where he belongs, directing traffic.
People come up and give him new pieces of information.
The big screen displays a single image: The overhead satellite image of the compound in Abbottabod.
From the back of the room, Maya enters, and watches the activity unfold without her...
without her input.
George notices her, gives a thumbs up and then turns back to his troops.
STEVE, early 40s, a senior manager and one of George's top deputies, joins Maya.
STEVE Basically we had a guy who rolled with Al Qaeda and did services for them.
STEVE We lost him for seven years and now we found him again -- and boy does he have a really nice house.
STEVE Is that it?
MAYA Pretty much.
STEVE Okay, let's go talk to the boss.
Maya and Steve are the first to arrive in the wood panelled conference room.
A detailed TABLE TOP MODEL of the compound sits in the center of the conference table, right next to a poster-sized satellite image of the compound.
She starts to sit in one of the chairs.
You should sit back there...sorry.
Steve points her to the back of the room.
STEVE (CONT'D) They're gonna ask: if bin Laden is at the end of this rainbow - is the Pak military with him?
MAYA The question isn't are the Paks protecting bin Laden?'
MAYA (CONT'D) The question is, 'would he allow himself to be protected by the Paks?' I mean, why would he trust them?
MAYA (CONT'D) He tried to kill Musharaf.
MAYA (CONT'D) Steve considers a reply, but the meeting principals are filing in, including Daniel, and when Steve sees the CIA DIRECTOR enter the room, he clears the head of the table.
CIA DIRECTOR Go ahead.
STEVE If you take a right out of Islamabad and drive about forty-five minutes North, you'll find yourself here in Abbottabad.
STEVE A middle class community - some ex-military - not particularly interesting to us.
STEVE Except we did find this compound, which is unique.
STEVE We got a sixteen foot wall around the entire perimeter, the windows are blacked out.
STEVE It's a fortress.
CIA DIRECTOR Can't you put a camera somewhere - in the trees - to get a look into the main house?
GEORGE It will probably be discovered.
CIA DIRECTOR We have to get a look into the house.
CIA DIRECTOR The Director moves to the satellite image.
CIA DIRECTOR (CONT'D) Alright, what's this?
CIA DIRECTOR (CONT'D) This cluster of buildings down here.
GEORGE The PMA - The Pakistan Military Academy.
GEORGE It's their West Point.
CIA DIRECTOR And how close is that to the house?
GEORGE About a mile.
GEORGE A WOMAN'S voice from the back of the room.
MAYA O.S. 4,221 feet.
MAYA O.S. It's closer to eight- tenths of a mile.
CIA DIRECTOR Who are you?
MAYA I'm the motherfucker that found this place, Sir.
MAYA The boss studies her for a moment then turns back to the model.
CIA DIRECTOR I want to know more about who's inside this house by the end of the week.
CIA DIRECTOR The brass files out, leaving Steve and Maya.
STEVE "Motherfucker?" Really?
INT. CIA HEADQUARTERS - AF/PAK DIVISION - DAY Maya sits at her desk, frustrated, then walks down the aisle of cubicles to the glass wall of George's office.
INT. CIA HEADQUARTERS - AF/PAK DIVISION - DAY She grabs a red marker.
MAYA Morning, George.
MAYA In red magic marker, Maya writes the number 21 on the glass.
MAYA Then circles it.
MAYA George looks up.
MAYA (CONT'D) Twenty-one days.
MAYA (CONT'D) It's been twenty- one days since we found the house and nothing's happened!
We see a drone-fed overhead IMAGE of the bin Laden house in real time with a resolution of 100 feet.
Maya stares at the screen, trying to decipher the shapes moving beneath her, thousands of miles away.
The BLIPS move in increments, shadows lengthen.
INT. CIA HEADQUARTERS - AF/PAK DIVISION - DAY ECU - Maya erases the "51" on George's wall and replaces it with "52."
INT. CIA HEADQUARTERS - AF/PAK DIVISION - DAY George looks away.
Maya sits at her desk.
Her phone rings.
Yeah?
STEVE stares at drone image of the COMPOUND, which is under the joystick control of an IMAGERY TECHNICIAN.
STEVE Swing by, I want to show you something.
Maya jumps up from her desk.
Maya walks in.
Steve shows her images on the large monitor.
STEVE This is from a few minutes ago.
STEVE We've got two males, two females, and seven kids.
STEVE Maya points to one of the shapes in the courtyard.
MAYA Who's that?
STEVE I'm saying that's Bushra.
STEVE The brother's wife.
MAYA How do you know the gender?
STEVE This is a clothes-line here, for laundry.
STEVE Men don't mess with the wash.
STEVE We watch that shape move away from the clothes-line and back to the house.
STEVE (CONT'D) It takes her about four seconds to move from there to the front door.
STEVE (CONT'D) So she's on the older side.
MAYA What's that up there?
MAYA (pointing to the other
STEVE Those are kids.
STEVE They're shuffling around, sword-fighting or something with sticks.
You can see their height relative to this - these are cows - so they're probably between seven and nine.
Boys.
Another FIGURE comes out of the house and moves to the clothes- line and grabs some laundry.
MAYA Your female is moving fast.
STEVE That's what I wanted to show you.
STEVE (to the Imagery
Can we pause this please?
That's not the same lady.
That's female #3.
MAYA So you found two males, three females?
STEVE That's correct.
STEVE Maya suddenly gets it.
MAYA You're missing a male.
STEVE Yes we are.
MAYA Wow.
CONTINUOUS George is on one side of a conference table, on the other side is the DEPUTY NATIONAL SECURITY ADVISOR, THE SPECIAL ASSISTANT TO THE DEPUTY NATIONAL SECURITY ADVISOR, and the
GEORGE If there are three females, there ought to be three males.
GEORGE Observant Muslim women either live with parents or with their husbands.
GEORGE We think there's a third family living in the house.
NATIONAL SECURITY ADVISOR So this third male that you've identified as possibly being bin Laden, do I just give up all hope of ever seeing a photograph of him?
GEORGE Hope?
GEORGE Hope is not a targeting layer.
GEORGE You give up your hope right now.
GEORGE We scanned for heat signatures, but we can't validate if it's a man or a woman up there.
GEORGE We found a safe house, but we can't get a vantage point to fire a telescope over the balcony wall.
A DOCTOR comes to the compound offering immunizations.
One of the women let's him in, and he offers polio vaccines to the children.
GEORGE We talked about burrowing a pin hole camera but there's a high risk of discovery.
GEORGE (CONT'D) We have explored the possibility of digging tunnels, of sending hot air balloons, of re-routing supply C- 130's to take a peek, but that might be too alerting.
GEORGE (CONT'D) We've looked for ways of collecting available DNA from his trash - you know, looking for his toothbrush, but they burn the trash.
GEORGE (CONT'D) We started a vaccination program, we sent a doctor to the house, to see if he could pull blood.
GEORGE (CONT'D) A lady in a black burkha rushes out and angrily shoos the doctor away.
GEORGE (CONT'D) That didn't work out.
GEORGE (CONT'D) We thought about sending a guy with a bucket to pull a sample from the sewer to analyze his fecal matter.
SPECIAL ASSISTANT TO THE ADVISOR What was wrong with that, exactly?
SPECIAL ASSISTANT TO THE ADVISOR He looks up.
GEORGE What was wrong with that?
GEORGE The sample would be too diluted.
NATIONAL SECURITY ADVISOR And it's asking too much to get a voice confirmation with him on the phone?
GEORGE They don't make telephone calls from the compound.
GEORGE We pulled the cell tower nearby.
NATIONAL SECURITY ADVISOR And I'm also going to give up hope that he might ever get in that white SUV and drive around a bit and we could see him?
NATIONAL SECURITY ADVISOR Don't they get groceries.
GEORGE The unidentified third male does not get groceries.
GEORGE He does not leave the compound.
GEORGE He does not present himself for photographs.
GEORGE (CONT'D) When he needs fresh air, he paces around beneath a grape arbor, but the leaves are so thick they obscure our satellite views.
GEORGE (CONT'D) This is a professional attempt to avoid detection - real tradecraft.
GEORGE (CONT'D) The only people we've seen behave this way are other top level Al Qaeda operatives.
GEORGE (CONT'D) The National Security Advisor nods to his Special Assistant who slides a big folder across his desk to George.
NATIONAL SECURITY ADVISOR We did a Red Team on your analysis.
NATIONAL SECURITY ADVISOR According to them, this behavior could belong to someone other than Al Qaeda.
They did give a forty percent chance that the unidentified third man is a senior Al Qaeda operative.
But they also said there's a thirty-five percent chance he's a Saudi drug
(reading from the
A fifteen percent chance that he's a Kuwaiti arms smuggler, a ten percent chance that he's one of the relatives of the brothers.
SPECIAL ASSISTANT TO THE ADVISOR Basically, we agree with you, the house screams security, it screams someone who wants privacy, it even screams 'bad guy', but it does not scream bin Laden.
NATIONAL SECURITY ADVISOR You get the point.
If you can't prove it's bin Laden, at least prove it's not somebody else, like a drug dealer.
Beat.
The meeting is adjourned.
As they walk out --
GEORGE You know we lost our ability to prove that when we lost the detainee program.
Who the hell am I supposed to ask?
Some guy in Gitmo who is all lawyered up?
He'll just tell his lawyer to warn bin Laden.
NATIONAL SECURITY ADVISOR You'll think of something.
INT. CIA HEADQUARTERS - AF/PAK DIVISION - DAY Maya is back at George's office, keeping track of time for us by writing each passing day on the window of George's office.
INT. CIA HEADQUARTERS - AF/PAK DIVISION - DAY We watch as she erases the numbers in red and writes new ones.
INT. CIA HEADQUARTERS - AF/PAK DIVISION - DAY 78.
INT. CIA HEADQUARTERS - AF/PAK DIVISION - DAY Time passes.
100 days.
She underscores the numerals in thick magic marker.
The same group around the same conference table.
GEORGE He'd be the first successful drug dealer never to have dealt drugs.
GEORGE He has no internet access to the house.
GEORGE He makes no phone calls either in or out.
GEORGE Who's he selling to, who's he buying from, how's he making his money?
GEORGE And if you're going to say he's retired, I'd say where's his swimming pool, where's the gold cage with the falcons?
GEORGE And why does he send his courier to the two cities in Pakistan we most associate with Al Qaeda, that have nothing particularly to do with heroin production?
GEORGE The National Security Advisor taps his pencil impatiently.
NATIONAL SECURITY ADVISOR The President is a thoughtful, analytical guy.
NATIONAL SECURITY ADVISOR He needs proof.
The National Security Advisor and his team file out.
George approaches.
GEORGE I have to admit, I just don't get the rhythms of politics.
NATIONAL SECURITY ADVISOR You think this is political?
NATIONAL SECURITY ADVISOR If this was political we'd be having this conversation in October when there's an election bump.
NATIONAL SECURITY ADVISOR This is pure risk.
NATIONAL SECURITY ADVISOR Based on deductive reasoning, inference, supposition and the only human reporting you have is six years old, from detainees who are questioned under duress.
NATIONAL SECURITY ADVISOR The political move here is to tell you to go fuck yourself, and remind you that I was in the room when your old boss pitched WMD Iraq...at least there you guys brought photographs.
GEORGE You know, you're right, I agree with everything you just said.
GEORGE What I meant was, a man in your position, how do you evaluate the risk of not doing something, the risk of potentially letting bin Laden slip through your fingers?
GEORGE George shakes his head with an "aww shucks" kind of shake.
GEORGE (CONT'D) That is a fascinating question.
GEORGE (CONT'D) George walks away.
GEORGE (CONT'D) After a beat, the National Security advisor calls after him.
NATIONAL SECURITY ADVISOR Hey.
NATIONAL SECURITY ADVISOR George turns around.
NATIONAL SECURITY ADVISOR The National Security Advisor approaches him.
I'm not saying we're gonna do it.
But the President wants to know: if we were going to act, how would we do it?
Give us options.
Doors of a HANGAR open in front of a large crowd that includes several White House guys, a General, and a squadron of Navy SEALs, including PATRICK, JUSTIN, JARED, SABER, TWO SOAR PILOTS, and some members of the Af-Pak department, George, Daniel, Hakim, and of course, Maya.
The doors grind open to reveal: TWO STEALTH BLACKHAWKS
I actually tried to kill this program a couple of times.
They've gone through an initial round of testing, and they have excellent radar defeat - we just haven't tested them with people in them yet.
The General continues his briefing..
You'll notice these stealth panels similar to what we use on the B2 -
- The rotors have been muffled with decibel killers - it's slower than a Blackhawk and lacks the offense.
But it can hide.
JUSTIN Excuse me.
JUSTIN Can I ask a question?
JUSTIN What do we need this for in Libya?
JUSTIN Gaddafi's anti-air is virtually non- existent.
JUSTIN Maya looks over, not sure what to say.
GEORGE Gentlemen, can I have your attention?
GEORGE My name is George.
GEORGE I run the Af-Pak division at CTC, and I'm primary on this for the agency.
GEORGE This is a title fifty operation.
GEORGE (CONT'D) Some of us have worked together before.
GEORGE (CONT'D) This is a good one.
GEORGE (CONT'D) Maya, do you want to brief them?
GEORGE (CONT'D) Maya looks at the SEALs.
GEORGE (CONT'D) Folds her arms.
GEORGE (CONT'D) This isn't going to be easy.
MAYA There are two narratives about the location of Osama bin Laden.
MAYA This registers on the SEALs.
MAYA (CONT'D) The one that you're most familiar with is that UBL is hiding in a cave in the Tribal Areas, that he's surrounded by a large contingent of loyal fighters.
MAYA (CONT'D) Beat.
MAYA (CONT'D) But that narrative is pre- 9/11 understanding of UBL.
MAYA (CONT'D) The second narrative is that he's living in a city - living in a city with multiple points of egress and entries and with access to communications so that he can keep in touch with the organization.
MAYA (CONT'D) You can't run a global network of inter- connected cells from a cave.
MAYA (CONT'D) Beat.
MAYA (CONT'D) We've located an individual we believe based on detainee reporting is bin Laden's courier.
MAYA (CONT'D) He's living in a house in Abbottabod, Pakistan.
MAYA (CONT'D) And we assess that one of the other occupants of the house is UBL.
JUSTIN Excuse me.
JUSTIN You got an intel source on the ground?
MAYA No.
JUSTIN No?
JUSTIN Okay, so how do you know it's bin Laden?
JUSTIN We've been on this op before, you know.
MAYA Bin Laden uses a courier to interact with the outside world.
MAYA By locating the courier, we've located bin Laden.
PATRICK That's really the intel?
PATRICK That's it?
MAYA Quite frankly, I didn't even want to use you guys, with your dip and your velcro and all your gear bullshit.
MAYA I wanted to drop a bomb but people didn't believe in this lead enough to drop a bomb, so they're using you guys as canaries on the theory that if bin Laden isn't there, you can sneak away and no one will be the wiser.
But bin Laden is there - and you're going to kill him for me.
Bullets are cheap.
George is shaking his head as he talks to Wolf.
GEORGE They are nervous downtown.
GEORGE I don't think we'll get approval this decision cycle.
GEORGE They look up and notice that Maya is standing outside George's office staring at them through the glass.
GEORGE She angrily wipes the number 128 off the window and changes it to 129.
GEORGE Wolf nods.
WOLF It's her against the world.
GEORGE Oh yeah.
George is pulling his tray away from the food service court when Maya ambushes him.
MAYA We've spun up the SEALs - we've done everything humanly possible to collect on the compound, and the collection is not going to get any better.
GEORGE We have to keep working it.
MAYA You're going to come into work one day, and there's going to be a black moving van and a 'for sale' sign in front of that compound.
MAYA George drops his tray down.
GEORGE Maya, you didn't prove it.
Sitting around the table are the CIA Director, JEREMY, Wolf, the DEPUTY DIRECTOR, George, Daniel, Steve and a few other people we don't know.
At the far end of the table are back benchers, including Maya.
CIA DIRECTOR I'm about to go look the President in the eye and what I'd like to know, no fucking bullshit, is where everyone stands on this thing.
CIA DIRECTOR Now, very simply.
CIA DIRECTOR Is he there or is he not fucking there?
CIA DIRECTOR He looks to the Deputy Director.
DEPUTY DIRECTOR We all come at this through the filter of our own past experiences.
DEPUTY DIRECTOR I remember Iraq WMD very clearly, I fronted that and I can tell you the case for that was much stronger than this case.
CIA DIRECTOR Yes or no.
DEPUTY DIRECTOR We don't deal in certainty, we deal in probability.
DEPUTY DIRECTOR I'd say there's a sixty percent probability he's there.
DEPUTY DIRECTOR The CIA Director points to Wolf.
WOLF I concur.
WOLF Sixty percent.
GEORGE I'm at eighty percent.
GEORGE Their OPSEC is what convinces me.
CIA DIRECTOR You guys ever agree on anything?
DANIEL Well, I agree with sixty, we're basing this mostly on detainee reporting and I spent a bunch of time in those rooms - who knows?
DANIEL Maya shoots Daniel a look.
DANIEL What a traitor.
DANIEL (CONT'D) I'd say it's a soft sixty, sir.
DANIEL (CONT'D) I'm virtually certain there's some high value target there, I'm just not sure it's bin Laden.
DANIEL (CONT'D) The CIA Director leans back in his chair.
CIA DIRECTOR This is a cluster-fuck, isn't it?
JEREMY I'd like to know what Maya thinks.
DEPUTY DIRECTOR We're all incorporating her assessment into ours.
Maya can't take it anymore:
MAYA One hundred percent, he's there - okay, fine, ninety-five percent because I know certainty freaks you guys out - but it's a hundred!
The CIA Director walks with Jeremy towards the elevator.
CIA DIRECTOR They're all cowed.
CIA DIRECTOR What do you think of the girl?
JEREMY I think she's fucking smart.
JEREMY As the door closes.
CIA DIRECTOR We're all smart, Jeremy.
Maya is eating lunch by herself when she's startled to see the CIA Director standing by her table.
CIA DIRECTOR May I join you?
CIA DIRECTOR She nods, gulps.
How long have you worked for the
MAYA Twelve years.
MAYA I was recruited out of high school.
CIA DIRECTOR Do you know why we did that?
MAYA I don't think I can answer that question, sir.
MAYA I don't think I'm allowed to answer.
CIA DIRECTOR What else have you done for us besides bin Laden?
MAYA Nothing.
MAYA I've done nothing else.
MAYA He evaluates her...
MAYA weighing her certainty against his decades of Washington experience.
CIA DIRECTOR Well, you certainly have a flare for it.
Jalalabad Airfield: nestled against the rugged mountains of the Pakistan border.
Everything in motion, SOLDIERS, CONTRACTORS, AVIATION ASSETS, PATROLS coming and going.
Patrick and Justin are playing horseshoes.
Maya, happy for the first time since we've met her, watches them
JUSTIN So, Patrick, be honest with me.
JUSTIN You really believe this story?
No offense.
PATRICK I do.
JUSTIN What part convinced you?
JUSTIN Patrick motions to Maya.
PATRICK Her confidence.
PATRICK Maya smiles, laughs.
JUSTIN Really?
JUSTIN Okay.
JUSTIN That's the kind of concrete data point I'm looking for.
JUSTIN He shakes his head.
JUSTIN (CONT'D) If her confidence is the one thing that's keeping me from getting ass- raped in a Pakistani prison...I don't know.
JUSTIN (CONT'D) I'm gonna be honest with you though, I guess I'm cool with it.
They bump fists, laughing.
Maya's cell phone rings.
She moves aside to answer it.
We INTERCUT with George in his Langley office.
GEORGE Maya, I wanted you to hear it first.
GEORGE You know that thing we talked about?
GEORGE It's going to happen.
MAYA When?
GEORGE Tonight.
GEORGE Good luck.
GEORGE She hangs up, turns back to the SEALs, who are still playing horseshoes with the grace of young guys in their prime.
GEORGE Their lives are in her hands.
The small space is filled with personnel and telecommunications gear.
At the back of the room Maya sits quietly, adjusting a headset and speaking calmly into a secure line.
From the corner Hakim watches her.
MAYA Testing - testing 1 - 2 - 3 - A SEAL with his com set on gives her the thumbs up.
MAYA She looks around at all the impressive technology in the makeshift Command Center.
MAYA She walks over to Hakim and they leave together.
MAYA Thank you for coming with me.
HAKIM Of course.
HAKIM I'll go with you where ever you want.
HAKIM A few hundred feet in front of them they can see SEALs preparing their gear.
MAYA Fuck Hakim, what if I'm wrong?
MAYA (CONT'D) I wish we could have just dropped a bomb.
HAKIM Please don't drop it while we're in the house.
MAYA I'm serious.
HAKIM Me too.
HAKIM Don't drop anything while I'm inside.
HAKIM Off her anxious smile --
Blinding white lights - rigged to chain link fencing, like a space shuttle launch - Silhouetted shapes behind the lights and the thump-thump- thump SOUND of high-dollar helicopters - Now push through the glare and the fence into -
A top-secret LZ.
Where twenty-two SEALs in full battle rattle and an attack DOG load into TWO STEALTH BLACKHAWK helicopters Moving fast, wordlessly, loading weapons and gear - under the intense bright white light, then - - Doors slam, engines whine - Fifty yards away, Maya stands alone, looking on.
- And the HELOS rise above the lights and disappear into the night.
Hands feather the controls as the pilot -- one the famed Nightstalker's from the Special Operations Aviation Regiment (SOAR) 160th -- flies without lights, using only his NODs for night vision.
Flying in formation, barely visible in the moonless sky, no flying lights.
The helos near the Tora Bora mountain range: dimly visible bulks rising in front of the helos.
The SEALs gently bounce inside the bellies of the churning beasts.
PRINCE 51 PILOT Thirty seconds to first turn.
JARED Hey Justin, what are you listening to?
JUSTIN Tony Robbins.
JARED Tony Robbins?
JUSTIN You should listen to it.
JUSTIN I got plans for after this.
JUSTIN I want to talk to you guys about it.
JUSTIN It's not selling.
JUSTIN You become a representative.
JUSTIN Everyone chuckles.
Hard left.
The stealths take a sharp turn.
Skimming the mountain.
PATRICK Who here's been in a helo crash before?
PATRICK Everyone raises their hands.
PATRICK (CONT'D) Okay, so we're all good.
BASE - EVENING Technicians track the helos on an array of computer screens.
Now entering Pakistan.
Maya is here, too, working.
She's always working.
Pakistani coms, no chatter.
Find the HELICOPTERS navigating tight mountain passes.
NOTE: Throughout the flying sequence that follows the helicopters fly very close to the ground, with a margin of error less then twenty feet.
The terrain zooms by as we travel through a twisty mountain
- Looming straight ahead on a collision course is a GIANT MOUNTAIN.
They zoom closer.
We can see individual rocks now -
Big left!
Seconds before impact, the HELICOPTERS bank into a hard left turn.
DUST blows off the mountain.
INT. PRINCE 51 - LATER The dog PANTS - sitting in its handler's lap in the dim cabin -
PILOT Ten minutes.
PILOT Three mikes to target.
PILOT Standby for doors open.
PILOT Inside the dim interior, illuminated by only blinking instrumentation, the men are tense, quiet.
PILOT We pass slowly from face to face, noting each SEAL's contemplation of the mission that lies ahead.
PILOT Some of them are anonymous soldiers.
PILOT Many we've come to know: Justin, joyfully bobbing his head, grooving to his iPod...
PILOT Saber's eyes fixed on a thousand-yard stare...
PILOT Hakim struggles to get comfortable and control his anxiety, wipes away sweat...
PILOT Patrick checks his gear for the hundredth time.
Two minutes.
Outside: Darkness....just a THUMP THUMP THUMP...
And then we see them: flying in tight formation, the oddly rectangular helos, with their black stealth panels and sharp edges, like two alien spaceships advancing.
Should be coming up just off our nose, 3 o'clock.
Everyone grabs onto their gear, getting ready to fast rope.
Patrick flings open the side door.
Night wind rushes in -
Small cottages mixed in with larger suburban homes.
Among them, swimming pools.
The water shimmering.
Surreal.
Then: rows of green fields.
A stand of trees.
It appears: AC 1.
It is massive - six or seven times larger than any other nearby structure - with sixteen foot high walls and a gated interior.
A fortress.
PILOT Thirty seconds.
PILOT Patrick leans out for a visual as the wind rips his face -
The helos circle the COMPOUND, kicking up dust, and begin to descend.
Cross cutting all that follows: - At thirty feet above the ground the helicopter begins to shudder and lose stability.
Instead of descending in a straight path, the bird drifts sideways
PATRICK Hey!
PATRICK Slide right.
PATRICK - Then lurches down, falling to within 15 feet of the swirling ground, rotors churning the dust, creating near BROWNOUT conditions, a dust hurricane
INT. PRINCE 51 CU: Pilot finessing the controls - not good enough
PRINCE 51 PILOT Power!
ECU: rear rotor blades edging closer to the wall, inch by inch.
-- Engines straining LOUDLY in the thin, hot air -- The bird loses control, SPINS to a hard landing
INT. PRINCE 51 ECU: Pilot thrusts stick
-- TAIL crashes hard on the WALL, in a awful screech of twisting metal and sheared concrete -
INT. PRINCE 51 -- Tossing the men inside the helo around like rag dolls.
BASE - EVENING The command tent watches the helicopter crash.
PRINCE 52 PILOT Prince 51 is down.
PRINCE 52 PILOT Blackhawk down in the animal pen.
PRINCE 52 PILOT Maya stands, crestfallen.
EXT. HELO CRASH The dust settles to reveal...a twisted wreck.
EXT. HELO CRASH PRINCE 51 has crash landed into a precarious position, with the back half of the helicopter wedged into the top of the wall and the front of it in the ground, leaving the passengers inside suspended more then ten feet off the ground.
Although he's wearing a heavy pack and carrying gear, Patrick jumps down, landing with a knee-shattering combat roll.
Several SEALs follow him.
Patrick pulls out of his roll and turns around to face the house, looming ominously ahead of him.
This mission is still a go.
Off Maya's relief -
The second helo passes over but a storm of debris and garbage from the rooftop creates another flight risk and the helo banks away.
Patrick, Justin and SIX other SEALs cluster near the First Gate in the animal pen.
One of the SEALs places a charge on the gate, while others check the Prayer Room.
Boom!
The charge partially blows open the metal swing doors of the gate, leaving a very narrow gap.
Not ideal.
The SEALs muscle and squeeze their way through the narrow opening in the jagged metal as the SNIPER climbs up on the roof of the prayer room.
Patrick and Jared arrive at the guest house but can't see inside - the windows and doors are covered with sheets.
Patrick kneels down to place a charge at the front door handle when the door erupts with gunfire - Bullets fly out of the wooden door.
One skims Patrick's shoulder as he kneels lower.
Patrick fires back at the house, putting a dozen rounds inside.
A moment passes.
They wait for a response.
The door handle unlocks.
ABU AHMED'S WIFE appears at the doorway and walks out.
JARED Ir-fah ee-dek!
You killed him.
The SEALs peer inside and see ABU AHMED lying dead in a pool of blood.
Patrick and Jared pump safety rounds into the body.
FOUR KIDS are cowering in the corner.
Jared moves them out of the house.
The rest of the P51 SEALS breach a gate to the courtyard of the Main House.
The gate flies open in a fiery ball.
SEALs jump out of P52, rush to the outer wall and set breaching charges on a gate...
While Hakim, the DOG HANDLER, and another SEAL peel off down the block Saber and his team stand by as BOOM!!!, The gate charges go off...only to reveal a BRICK WALL behind the gate.
SABER That's not a door.
SEAL Failed breach.
SEAL They hustle to the next entry way and prepare another breach
The COMMANDING OFFICER hears that the SEALs outside are preparing a charge.
SEAL MIKE radios in
This is Echo 11, we're going to breach the main gate.
Negative.
I'm internal, I'll let you in.
The Commanding Officer opens the gate and the other SEALs walk inside.
As a group, they move towards the main house, arriving at the South side front door.
The door is open and they enter -
Piercing the first floor darkness with their infra red lights, the SEALs advance slowly into the first floor hallway.
Piles of household clutter, stacked high in bizarre shapes, greet them like the innards of a haunted house.
One of the SEAL's catches movement: A figure with an AK-47 scrambling through clutter, then disappearing around a corner.
JUSTIN Abrar!
JUSTIN The figure, Abu Ahmed's brother, ABRAR, re-appears at the end of the hallway.
JUSTIN He pokes his head out -
- And is shot by Justin.
He falls out of view, whimpering in pain.
INT. MAIN HOUSE - FIRST FLOOR HALLWAY - CONTINUOUS Justin walks quickly to Abrar.
ABRAR is down, bleeding.
- Justin fires another round into Abrar as ABRAR'S WIFE comes flying in from the sleeping quarters and shields him with her body.
- Justin shoots her.
She falls...Abrar is underneath her - he is still breathing, gasping and - Justin shoots him again, silencing him - Then looks to his wife and assesses her condition - Badly wounded, faint breathing, life fading from her eyes...
- Justin turns away
INT. MAIN HOUSE - FIRST FLOOR HALLWAY - CONTINUOUS Justin and a BREACHER proceed down the hall to the heavy gate that blocks access to the stairway while another SEAL stays behind.
INT. MAIN HOUSE - FIRST FLOOR HALLWAY - CONTINUOUS Somewhere, children are screaming.
JUSTIN Shut those fucking kids up.
JUSTIN O.S.
JUSTIN the kids quiet down.
JUSTIN (CONT'D) Talk to me.
There's no fucking way we want to blow this thing.
The gate is solid.
This is Echo 11 - we're at our primary set point, prepping to breach.
Wait, Echo 11 - we're internal on the south side - this is a negative breach.
Roger.
We're ready to make our entry out here.
Roger that, we're coming to meet you.
Stay with these kids.
Don't let them in the back room.
In the regrouping that occurs on the side of the main house, Justin and Patrick find themselves side by side - and the old friends take a moment to reconnect while the rest of the team places charges and prepares for the next phase of the assault.
You good?
JUSTIN Yeah.
JUSTIN I forgot...were we supposed to crash that helo?
JUSTIN Patrick allows himself a smile.
PATRICK Ibrahim tried to shoot me through the door.
PATRICK I popped him from the outside.
JUSTIN I fucking smoked Abrar and his wife.
(alt: I think she was
PATRICK Still alive?
JUSTIN She's gonna bleed out.
PATRICK What a fuckin' mess - The door blows - and they keep moving -
INT. MAIN HOUSE - FIRST FLOOR HALLWAY - CONTINUOUS The SEALs reach the staircase, which is sealed off by a separate metal gate than the one inside the hallway.
SEAL Breacher up.
SEAL A charge is prepared.
SEAL Justin, who is now inside one of the side rooms, sees Jared standing close to the door.
JUSTIN Hey man, move!
JUSTIN Jared moves just as -
- Boooom!
-- The door FLIES like a missile right into where Jared had been standing.
Thanks.
JUSTIN Yeah.
Saber goes up the staircase, Patrick following closely behind him, climbing up to see -
A man ducks out of sight.
Saber calls to him.
SABER Khaled!
SABER Saber waits with his carbine raised.
SABER Anxiety crosses his face.
SABER He's vulnerable here, an easy target if Khaled were to come out blasting.
Khaled hears his name being called from below.
A few feet away from him in the dimly lit hall is a loaded AK-47.
He goes to the gun and picks it up.
He hears his name again, "Khaled!" And the voice sounds friendly, urgent.
Perhaps thinking that he can surrender peacefully, Khaled puts the gun down, resting it against a wall, and turns and heads back to the sound of his name.
Saber sees Khaled poke his head around the corner of the stairway and fires - killing him instantly.
Saber pushes past the body, Patrick following, and they climb the staircase leading to the third floor.
The neighborhood, awakened by the crash and gunfire, stirs to life.
Hakim and the SEALs notice LIGHTS flipping on.
And down the block, a group of several young men appear on a roof.
SEAL This is Echo 05, I've got unknowns gathering on the Southwest Rooftops.
SEAL Hakim, move those guys back.
HAKIM Go back brothers, this is official government business, and there is nothing to see here!!
SEAL I'm going to start wasting them.
HAKIM Please!
HAKIM They will kill you!
HAKIM The onlookers pause.
HAKIM SEAL aiming lasers dance across their chests.
They will kill you!
They turn and go.
- SEALs clear the SECOND floor as women and children flow into the hallway...
A SEAL grabs one of the wives and pulls her out into the hallway, while another female disappears behind a large REFRIGERATOR, and he grabs her too.
Justin opens a file cabinet, stuffed with documents.
Saber is climbing the stairs, gun up, towards the third floor, when he sees a flash of movement across the landing above him.
He stops climbing and -
Osama!
Osama!?
Beat.
Beat.
Sweat on Saber's face
SABER (CONT'D) Osama!?
SABER (CONT'D) A man appears at the end of the third floor hallway.
SABER (CONT'D) -- Ssssht !
SABER (CONT'D) a bullet strikes him in the head - knocking him back into a bedroom - Saber fires again, missing - And proceeds down the hallway, going full speed now, Patrick right behind him, sprinting into the bedroom
Two women stand at the entrance of the room.
Saber rushes them and with a football tackle, slams them into the wall.
Patrick enters the room and fires several rounds into the man on the floor.
Possible jackpot.
The women Saber is restraining are wailing, struggling to get to their husband, as a ten year-old boy rushes up to the body.
Patrick pushes him away and kneels down to get a better look at the body.
Dude, do you realize what you just did?
JARED questions the wives.
Who is he?
He is al Noori Hasan.
JARED (shouting back to
She says it's not him.
PATRICK Talk to a kid.
PATRICK Jared kneels down next to a nine year-old girl huddled in the corner and snaps open a chem light.
PATRICK He gives her the glowing green wand.
Daughter, what is his name?
The girl makes no reply.
COMMANDING OFFICER For God and Country, Geronimo.
COMMANDING OFFICER Maya gasps.
The Commanding Officer issues orders.
All Stations: target secure, target secure.
Roger.
Copy.
Target Secure.
COMMANDING OFFICER Target Secure - commence SSE.
INT. SECOND FLOOR - MEDIA ROOM Justin flicks on the lights.
INT. SECOND FLOOR - MEDIA ROOM Moving fast he picks up a COMPUTER tower and throws it to the floor, cracking it open, rips out the HARD DRIVE and tosses that into the bag.
INT. SECOND FLOOR - MEDIA ROOM As we pull back and realize the enormity of the task in front of him - The lights show an organized office, crammed with information, stacks of files, disks, video equipment.
INT. SECOND FLOOR - MEDIA ROOM Twenty years of jihad.
JUSTIN Do not leave a hard drive.
JUSTIN The SEALs gather everything they can.
Saber walks down the staircase in a daze.
We stay with him as he descends, noting the faraway look in his eyes -
Saber walks into the office where the SSE (Sensitive Sight Exploitation) is underway.
What's up?
SABER I shot the third floor guy.
JUSTIN Good for you.
JUSTIN You want to help?
Justin tosses him an SSE bag.
BASE - EVENING The command team studies their monitors.
QRF inbound.
EXT. DIEGO CORRIDOR The COMMANDING OFFICER is talking on two radios at once - one to his men, the other to brass back at Jalalabad base.
Echo 05, this is Red 02, how long do you need for SSE?
At least ten minutes.
You have four.
This is a gold mine, I need more time than that.
If you're not at the LZ in four, I'm going to leave your ass behind.
INT. SECOND FLOOR - MEDIA ROOM Justin yells to his team.
JUSTIN Four minutes!
EXT. HELO CRASH Hakim arrives at the crashed helo.
EXT. HELO CRASH He crawls into the
interior and finds a BLACK BODY BAG.
We follow this bag:
Hakim jogs into the main house with the BODY BAG, and through his POV, we see slow down for the first time since the raid began, noting the destruction: - blood stains on the walls, - Bodies pierced with bullets, - Wailing children.
Where do you need the bag?
SEAL Third floor.
INT. THIRD FLOOR - MASTER BEDROOM SEALs roll the body into the BAG as Patrick and another SEAL collect articles of interest.
INT. THIRD FLOOR - MASTER BEDROOM Two SEALs zip up the bag and carry it out.
INT. THIRD FLOOR - MASTER BEDROOM Just as...
Justin's team leaves the office.
The body bag is laid in the courtyard.
EXT. HELO CRASH - CONTINUOUS The EOD SEAL slides into the belly of Prince 51.
EXT. HELO CRASH - CONTINUOUS While he places charges, another SEAL climbs up to affix charges to the roof and rotors ...and like a tight roper, he walks out on the tail of the helicopter, when suddenly his foot slips, piercing the tail's thin skin, and he nearly falls off.
EXT. HELO CRASH - CONTINUOUS He manages to place a last charge - but the remainder of the tail piece will not be detonated.
Back at the whirling helicopter, the SEALs shove the BODY BAG into the interior compartment and jump in after it.
The helo rises into the night.
EXT. HELO CRASH - CONTINUOUS PRINCE 51 explodes, sending shrapnel and a fireball high into the air
The SEALs watch the flames as the compound shrinks beneath
The fire of the exploded crashed helo blazes in the night.
The SEALs sit silent in the cabin, body bag at their feet.
Bathed in the bright white lights, Maya waits for the helo.
Concern on her face.
At last, she hears it.
A moment later, PRINCE 52 hovers into view and lands.
Patrick and several SEALs run out, carrying the bag...
INT. HANGAR The place is swarming with SOLDIERS, SEALs, and FBI agents
with large bio-metric scanners - loud shouting everywhere: "mark media, first floor, who has a pen, etc."
Maya makes her way towards the hangar tent.
INT. HANGAR She pushes through the busy SEALs.
INT. HANGAR Maya sees it now - way in the corner of the hangar.
She walks and walks towards the bag.
She is alone with it now.
She unzips the BAG CU: Maya.
Seven years telescoping to this moment.
The end of a journey.
She stares at the body for a moment then turns to look across the room where ADMIRAL MCRAVEN meets her eye.
She nods.
Sir, the agency expert gave a visual confirmation.
Yes, Sir, the girl.
Hundred percent.
Maya gazes at the bloodied face, then turns away and zips the bag...and leaves the tent.
Her eyes afire.
Maya waits on the tarmac, alone.
A C-17, one of the largest most impressive planes in the American fleet, rolls to a stop and the hatch opens.
She climbs the ladder -
The cavernous cargo plane is empty of passengers.
The pilot motions to the seats.
PILOT Are you Maya?
MAYA Yeah.
PILOT That's the only name they gave me.
You can sit wherever you want, you're the only one on the manifest.
Maya sits down, buckles in.
The PILOT heads back to the
PILOT (CONT'D) You must be pretty important, you got the whole plane to yourself!
PILOT (CONT'D) Beat.
PILOT (CONT'D) Where do you want to go?
PILOT (CONT'D) She's speechless.
PILOT (CONT'D) Overwhelmed.
PILOT (CONT'D) Finally, she lets go.
PILOT (CONT'D) Those luminous eyes become pools of relief and pain.
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
