AMERICAN HUSTLE
Written by
Eric Warren Singer and David O. Russell
IRVING ROSENFELD, not a small man, gets dressed and meticulously constructs his combover.
Camera WRAPS AROUND, see his hands with rings adjust his dark velvet suit, up to his face, serious, concentrated, intense, he is composing himself before a performance.
Irving is now dressed, ready, and walks down the hall to another room.
Irving composes himself -- looks into cramped surveillance closet, there are FBI Agents -- we only see their hands and arms -- he looks at monitors -- sees a BLACK AND WHITE IMAGE OF ANOTHER ROOM ON MONITOR: MAYOR CARMINE POLITO, swath of salt and pepper hair, cream suit, pinky ring, Rotary Club pin -- ALONG WITH CARL ELWAY, preppie shady businessman.
He exhales pressure, turns as CAMERA PANS TO: SYDNEY PROSSER (who will also be known for some time as EDITH GREENSLY), stylish crafty smart.
They stare at each other intensely -- they have a deep and emotional relationship.
A DOOR BANGS OPEN, and in walks RICHIE DIMASO, Bronx-born.
He stands there.
RICHIE DIMASO What are you doing, going behind my back?
RICHIE DIMASO Telling people I'm screwing up this operation?
RICHIE DIMASO I got you a suite at the fuckin' Plaza Hotel!
IRVING ROSENFELD The shittiest suite at the Plaza Hotel.
RICHIE DIMASO What?!
IRV ROSENFELD The shittiest fuckin' suite.
RICHIE DIMASO Based on what--?
IRVING ROSENFELD And the food is wrong, and--What is this?
IRVING ROSENFELD You, like, went in my closet or something?
EDITH GREENSLY No
IRVING ROSENFELD Are you dressing him like you're dressing me now?
EDITH GREENSLY No, what are you thinking?
EDITH GREENSLY This isn't all about you, you know that.
RICHIE DIMASO What, did you try to dress me so I would look like him?
EDITH GREENSLY No, you're not dressed like him, all right?
RICHIE DIMASO But I do, I look like him.
EDITH GREENSLY No, he's in like, velvet.
EDITH GREENSLY Come on.
IRVING ROSENFELD You asked me to show you how this was done, you wanna fuck it up be my guest.
EDITH GREENSLY What is your problem?
RICHIE DIMASO Hey, look, I never laid a hand on her, all right?
RICHIE DIMASO Is that what this is about?
EDITH GREENSLY Well technically, that's not true.
RICHIE DIMASO Look, we never had sex ok?
RICHIE DIMASO I just --
RICHIE DIMASO (CONT'D) What'd I do?
RICHIE DIMASO (CONT'D) I put my hand like this --
Richie reaches out and puts his hand on Irving's face very carefully, not forcefully.
Irving swipes it away violently the second it touches his face.
IRVING ROSENFELD Don't you fucking touch me.
IRVING ROSENFELD That bothers me --
RICHIE DIMASO Oh it does?
IRVING ROSENFELD Oh yeah.
RICHIE DIMASO That bothers you?
IRVING ROSENFELD Yes.
RICHIE DIMASO You know, a lot of shit bothers me too, but I was trying to help you.
RICHIE DIMASO If I wanted to bother you, if I really wanted to fucking bother you, this is what I'd do.
Richie takes his hand and destroys the combover Irving spent so much time creating.
Irving just stands there, hair ruined, staring at Richie.
IRVING ROSENFELD You shouldn't have done that.
Irving just stands there staring at Richie, hair all wild and messed up looking very angry.
RICHIE DIMASO How's that?
RICHIE DIMASO You bothered now?
RICHIE DIMASO (no answer) Alright, don't make a thing of it.
EDITH GREENSLY You shouldn't touch him.
EDITH GREENSLY He doesn't like that.
RICHIE DIMASO Oh my god, fix his hair.
RICHIE DIMASO Don't make a thing of it.
EDITH GREENSLY It takes some time, ok.
Edith walks over to Irving who is still standing there in silence with his hair all over the place.
She carefully starts helping him put it back together.
RICHIE DIMASO Big fucking deal.
RICHIE DIMASO We got to get in the other room, come on.
RICHIE DIMASO The mayor's in there.
EDITH GREENSLY Yes I know that.
RICHIE DIMASO Should we go to the beauty parlor?
RICHIE DIMASO Is that what we should do?
Richie walks over and opens up a briefcase that's sitting on the dresser.
Inside are stacks of cash.
Edith is still helping Irving put his hair back together.
IRVING ROSENFELD How's it look.
EDITH GREENSLY You look fine.
Richie slams the briefcase shut looking very nervous and intense.
RICHIE DIMASO Let's go.
SLOW MOTION -- DOUBLE DOORS PUSH OPEN AND Edith ENTERS THE
CARMINE POLITO I thought he was going to be here.
CARMINE POLITO I do business face to face, person to person.
CARMINE POLITO That's just who I am.
Richie reaches down and awkwardly slides the briefcase over to Carmine unprompted.
LEAVE MONITOR'S POV AND RETURN BACK TO
CARL ELWAY Whoa, excuse me, excuse me.
CARL ELWAY I'll handle that for the Mayor.
RICHIE DIMASO No, it's for the Mayor.
RICHIE DIMASO It would be a sign of disrespect to the sheik if the mayor didn't take it himself.
RICHIE DIMASO It's for you Mayor.
Carmine looks angry and confused.
He looks over to Carl.
CARMINE POLITO What are you doing?
CARMINE POLITO What-- (to Carl) Carl, what the fuck?
CARMINE POLITO What is this?
CARL ELWAY No, I'll handle it.
CARL ELWAY I'm gonna take care of-- Everything's good.
CARL ELWAY I got everything under control.
CARL ELWAY (TO RICHIE) That's for me.
CARL ELWAY I handle all that for mayor.
CARMINE POLITO What is this?
Irving looks over and says nothing.
Not surprised at all how badly this is all going.
Edith whispers to Richie.
EDITH GREENSLY Just stop it, ok
RICHIE DIMASO He's gotta take it himself, okay?
CARMINE POLITO I don't know what the fuck that is but it's weird you understand?
CARL ELWAY Misunderstanding.
CARL ELWAY Misunderstanding.
CARMINE POLITO I came here to meet a sheik, that's all I know.
CARMINE POLITO I'm very interested in that but he's not here apparently.
CARMINE POLITO Carl?!
Carmine turns and starts to walk out of the room.
CARMINE POLITO (CONT'D) I'm very interested in meeting the Sheik.
CARMINE POLITO (CONT'D) You let me know when THAT could happen!
CARMINE POLITO (CONT'D) Thank you, have a good day.
Carmine leaves the room.
Irving looks over and shrugs his shoulders.
Not surprised at all the way this is going and horrified that Richie has ruined it.
CARL ELWAY Irving!
CARL ELWAY You better come get him.
RICHIE DIMASO Go out there and get him right now.
CARL ELWAY Help me get him back!
RICHIE DIMASO Go get him.
RICHIE DIMASO He needs to take the fuckin' briefcase, Irving.
IRVING ROSENFELD I didn't wanna do it in the first place.
IRVING ROSENFELD This is your show, YOU go get him.
RICHIE DIMASO No, you have no choice.
RICHIE DIMASO You have to go get him.
RICHIE DIMASO Now, go get him, so he takes the briefcase by himself!
RICHIE DIMASO That's the whole plan, Irving!
Irving stands up angry and gets in Richie's face.
IRVING ROSENFELD What were you doing pushing the fucking briefcase, dummy?
IRVING ROSENFELD Huh?
RICHIE DIMASO The whole fuckin' thing was falling apart.
RICHIE DIMASO You know how much I paid for this goddamn hotel that you fucking asked for?!
IRVING ROSENFELD Now I gotta go mop up your mess.
IRVING ROSENFELD I'm gonna go fucking mop up your mess!
Irving storms out of the hotel suite towards the Elevators to get Carmine.
Irving paces back and forth as he waits for the elevator.
We push in on the concerned face of Sydney as Richie rambles on to her.
RICHIE DIMASO You understand what I'm saying, right?
RICHIE DIMASO It wasn't working.
Irving continues to pace back and forth in the hall waiting for the elevator.
IRVING ROSENFELD (V.O.) Did you ever have to find a way to survive and you knew your choices were bad?
Irving walks over and hits the elevator button again.
IRVING ROSENFELD I learned how to survive when I was a kid.
(CONT'D) My father had a glass business.
Drumming up business for his father.
Young Irving and his Father and Mother standing outside the family's glass repair shop in the Bronx as some tough contractors march up to them.
IRVING ROSENFELD (V.O.) I would rather be on the taking side than the getting taken side any day of the week, especially after I saw how my father got taken.
IRVING ROSENFELD (V.O.) I mean, seeing that scarred me for life.
Young Irving runs by a store front as he throws a rock through each window on the store, smashing them all.
IRVING ROSENFELD (V.O.) (CONT'D) I took it upon myself to drum up business.
IRVING ROSENFELD (V.O.) (CONT'D) I became a different kind of guy than my father.
IRVING ROSENFELD (V.O.) (CONT'D) I became a con artist -- from the feet up, for real.
Irv shakes his head, surveys the damage.
IRVING ROSENFELD I was gonna survive no matter what.
IRVING ROSENFELD I still had the glass business and a few dry cleaning stores on the side.
Irving paces around his office smoking a cigar and talking on the phone.
What looks to be stolen art sits on the floor all around him.
IRVING ROSENFELD (V.O.) And I did some art dealing on the side.
IRVING ROSENFELD (V.O.) Stolen or forged art.
Chicago's "Does Anybody Really Know What Time It Is?" fades up.
Jamming early 70s HOLIDAY party -- LONG ISLAND LADIES IN
ENCLOSED POOL -while inside steamed glass SHINY BIKINI
GUYS WHO LOOK MOBBED UP, pale, out of shape, gold chains, in swim trunks, EVEN MORE BURT REYNOLDS TYPE GUYS, slim, hairy, chains.
IRVING ROSENFELD (V.O.) So, one January I go to my friends pool party in Long Island.
Irving sits holding court with some friends by the pool when he turns and sees Sydney for the first time.
PUSH IN ON: Irving.
He looks up, they lock eyes across the party.
IRVING'S HAND GRABS HER ARM -- she turns, taken aback -
IRVING ROSENFELD Is that Duke Ellington on your bracelet?
She does have on a Duke Ellington charm bracelet.
SYDNEY PROSSER As a matter of fact, it is.
SYDNEY PROSSER He died this year, you know.
IRVING ROSENFELD I know.
IRVING ROSENFELD I doubt anyone else here knows or cares about it.
SYDNEY PROSSER Well I care.
SYDNEY PROSSER He saved my life many times.
Irving takes a good look at her, impressed.
IRVING ROSENFELD Mine too.
IRVING ROSENFELD Which one?
SYDNEY PROSSER Jeep's Blues.
IRVING ROSENFELD Jeep's Blues.
IRVING ROSENFELD Oh yeah.
Awkward pause.
IRVING ROSENFELD (CONT'D) You wanna hear it?
SYDNEY PROSSER Right now?
IRVING ROSENFELD Yeah.
SYDNEY PROSSER Sure.
CUT TO: PORTABLE RECORD PLAYER PLAYS START OF JEEP'S BLUES as Irving and Sydney nod to it - he watches her foot in her high wedge and her tanned leg rocking as she sits on arm of sofa.
IRVING ROSENFELD Who starts a song like that?!
SYDNEY PROSSER It's magic.
IRVING ROSENFELD Magic.
They listen to the record, Edith checks Irving out.
SYDNEY PROSSER (V.O.) He wasn't necessarily in good shape, and he had this comb-over that was rather -- elaborate.
SYDNEY PROSSER (V.O.) He had this air about him.
SYDNEY PROSSER (V.O.) And he had this confidence that drew me to him.
SYDNEY PROSSER (V.O.) He was who he was and he didn't care.
IRVING ROSENFELD (V.O.) Like me, she was a very particular person.
IRVING ROSENFELD (V.O.) Like me, she came from a place where her options were limited -- and she had been someone she didn't want to be in her past.
SYDNEY PROSSER (V.O.) It actually can feel kind of sexy sometimes.
SYDNEY PROSSER (V.O.) There's a boldness in it.
SYDNEY PROSSER (V.O.) But where would that boldness take me?
SYDNEY PROSSER (V.O.) I didn't know.
SYDNEY PROSSER (V.O.) But I was gonna find out.
IRVING ROSENFELD (V.O.) Like me, she learned to survive and reinvent herself.
IRVING ROSENFELD (V.O.) She knew she had to reinvent her life and her identity.
IRVING ROSENFELD (V.O.) And like me, she envisioned a better elegant future for herself.
IRVING ROSENFELD (V.O.) Like me, she knew you had to have a vision.
Sydney looks at scrap of paper with info in her hand -- looks up at office building address -- enters.
IRVING ROSENFELD (V.O.) She came to New York.
IRVING ROSENFELD (V.O.) She envisioned it.
IRVING ROSENFELD (V.O.) (CONT'D) And just like that, she applied for a job at Cosmopolitan Magazine.
Clean bright colors, huge blown up Cosmo covers --
Sydney -- innocent, plain, slacks and blouse, hair back, nervously awaits interview.
SHE IS CALLED IN -- NERVOUSLY STANDS, small crumpled scrap of paper in hand, FIXES HER HAIR --
COSMO INTERVIEWER GIRL Well you're obviously here for a reason.
COSMO INTERVIEWER GIRL Let's get to it.
SYDNEY PROSSER Alright.
COSMO INTERVIEWER GIRL Our cover story right now is on cunnilingus.
COSMO INTERVIEWER GIRL What do you think about that?
SYDNEY PROSSER I like it.
COSMO INTERVIEWER GIRL Do you have any clerical skills?
SYDNEY PROSSER Yes.
COSMO INTERVIEWER GIRL Can you type?
IRVING ROSENFELD (V.O.) She was unlike anybody I ever knew.
IRVING ROSENFELD (V.O.) She was smart.
IRVING ROSENFELD (V.O.) She saw through people in situations.
IRVING ROSENFELD (V.O.) And she knew how to live with passion and style.
IRVING ROSENFELD (V.O.) She understood Duke Ellington.
15 CUT TO: Edith WATCHES A COSMO COVER SHOOT -- 15
SYDNEY PROSSER (V.O.) I was broke, fearless, with nothing to lose --
Irv and Sydney dance slowly.
SYDNEY PROSSER (V.O.) (CONT'D) -- and my dream, more than anything, was to become anyone else other than who I was.
Irv holds the door open for Edith as she enters.
IRVING ROSENFELD -- I got two in the Bronx and three in Manhattan.
IRVING ROSENFELD (to an employee) Hey, Byron.
SYDNEY PROSSER (V.O.) He had a chain of dry cleaning stores.
SYDNEY PROSSER (V.O.) He asked me to come in and upgrade my wardrobe-- he said a lot of nice things got left behind by people and forgotten over the years-
IRVING ROSENFELD I mean you wouldn't believe the shit that people leave behind here.
IRVING ROSENFELD Unbelievable.
SYDNEY PROSSER People leave stuff here?
IRVING ROSENFELD Oh yeah.
IRVING ROSENFELD They go out for the night, they drink, come here in the morning, put their clothes in and then they forget.
IRVING ROSENFELD They got no idea where they left it.
Irving touches a hanging blue sequined dress.
IRVING ROSENFELD (CONT'D) Look at that.
IRVING ROSENFELD (CONT'D) Sequined thing.
IRVING ROSENFELD (CONT'D) I don't know.
IRVING ROSENFELD (CONT'D) Is that nice or not?
SYDNEY PROSSER It's beautiful.
Irving and Sydney continue to walk through towards the back and enter a fur vault filled with elegant designer clothes.
IRVING ROSENFELD I mean, some of it's been here for years.
IRVING ROSENFELD They're not picking it up.
IRVING ROSENFELD Nobody's picking it up.
Sydney starts riffling through nice things hanging on the racks.
IRVING ROSENFELD (CONT'D) You like that?
SYDNEY PROSSER I love it.
IRVING ROSENFELD It's yours.
IRVING ROSENFELD You want it?
IRVING ROSENFELD It's yours.
Sydney looks back at Irving in shock.
IRVING ROSENFELD (CONT'D) You look fantastic!
SYDNEY PROSSER Oh my god.
SYDNEY PROSSER I can only dream about these dresses.
SYDNEY PROSSER They're beautiful.
IRVING ROSENFELD (V.O.) I felt like we had a secret.
IRVING ROSENFELD (V.O.) Just the two of us.
IRVING ROSENFELD (V.O.) You know like that thing where you want to just be with the one person the whole time.
IRVING ROSENFELD (V.O.) You feel like the two of you understand something that nobody else gets.
IRVING ROSENFELD (V.O.) I could just tell her everything about myself.
IRVING ROSENFELD (V.O.) And I never had anybody like that in my life before.
IRVING ROSENFELD (V.O.) I felt like finally, I can truly be myself without being ashamed, without being embarrassed.
39 INT.
Irv's dingy office - DAY 39
Irv leads Sydney into a small, dingy Manhattan office on an upper floor.
SYDNEY PROSSER What is this place?
SYDNEY PROSSER Do you sell art here?
IRVING ROSENFELD Yeah, sometimes.
IRVING ROSENFELD This is my office.
SYDNEY PROSSER I know it's your office, but, you have these other places.
SYDNEY PROSSER What's this for?
SYDNEY PROSSER Why did you bring me here?
IRVING ROSENFELD This getting to be my main business, my growing business.
IRVING ROSENFELD I help get loans for guys that can't get loans.
IRVING ROSENFELD I'm their last resort.
SYDNEY PROSSER You're their last resort?
SYDNEY PROSSER Because interest rates are north of 12% and heading to 18%.
IRVING ROSENFELD That's right, smarty pants.
SYDNEY PROSSER Fucking Jimmy Carter.
SYDNEY PROSSER Fucking Nixon really.
SYDNEY PROSSER And the war and the deficit and all of that shit.
IRVING ROSENFELD I love you, you're so smart.
IRVING ROSENFELD You are.
SYDNEY PROSSER Thanks kid but how do you get them the money?
IRVING ROSENFELD Well --
SYDNEY PROSSER You don't do you?
SYDNEY PROSSER You don't.
IRVING ROSENFELD These guys are lousy risks, you know?
IRVING ROSENFELD I can't get them a loan but I get my fee.
IRVING ROSENFELD Five thousand.
SYDNEY PROSSER Five thousand?
SYDNEY PROSSER You take five thousand and you don't give them anything?
IRVING ROSENFELD These are bad guys, you know?
IRVING ROSENFELD They got bad divorces, gambling habits, embezzling, all that shit, you know what I mean?
SYDNEY PROSSER Everybody at the bottom crosses paths eventually in a pool of desperation and you're waiting for them.
IRVING ROSENFELD How about `we'?
SYDNEY PROSSER We?
IRVING ROSENFELD How bout it?
Sydney turns and begins walking out the door as Irving chases her out.
IRVING ROSENFELD (CONT'D) Sydney.
IRVING ROSENFELD (CONT'D) Sydney I'm sorry that was too much.
IRVING ROSENFELD (CONT'D) I went too far.
IRVING ROSENFELD (CONT'D) I didn't want to upset you.
She continues walking out without looking back and leaves.
IRVING ROSENFELD (CONT'D) Sydney please, I'm sorry!
IRVING ROSENFELD (CONT'D) I know it ain't for everybody.
The door slams in Irving's face
IRVING ROSENFELD (CONT'D) Ah GOD I love getting to know you!
IRVING ROSENFELD (TO HIMSELF) What I do that for?
IRVING ROSENFELD (TO HIMSELF) I fucked it up.
IRVING ROSENFELD (TO HIMSELF) I should never tell a woman the truth.
IRVING ROSENFELD (TO HIMSELF) She's so smart.
IRVING ROSENFELD (TO HIMSELF) She's different.
SYDNEY PROSSER You said it was nice knowing me.
SYDNEY PROSSER You said it was nice to meet me.
IRVING ROSENFELD Yeah.
SYDNEY PROSSER Would you like to meet Lady Edith Greensly?
Irving looks stunned as he slowly clasps her extended hand.
SYDNEY PROSSER (CONT'D) I have royal banking connections in London.
SYDNEY PROSSER (CONT'D) I'd love to help you with your loan but of course I have to be very selective.
IRVING ROSENFELD That was fucking fantastic.
SYDNEY PROSSER Thank you.
SYDNEY PROSSER Did you like it?
IRVING ROSENFELD I liked it.
IRVING ROSENFELD I didn't think you were coming back.
IRVING ROSENFELD Thank god you came back.
SYDNEY PROSSER I wasn't going anywhere.
IRVING ROSENFELD I fucking love you.
SYDNEY PROSSER You have me.
ONE OF SYDNEY'S NANNY FRIENDS, REBECCA, walk out of a BUSINESS MAN's (34) house pushing a stroller as the business man comes chasing after them.
SYDNEY PROSSER (V.O.) And so Irving and I began our partnership -- in love and commerce.
BUSINESSMAN Rebecca, hold on.
BUSINESSMAN You're Edith right?
SYDNEY PROSSER(V.O.) He told me to tell my friends I had (in British accent) London banking connections
BUSINESSMAN I'm Jim.
BUSINESSMAN I'm her employer.
BUSINESSMAN Listen - - she told me you can get me a line of credit.
BUSINESSMAN I know you have banking connections in London, England.
SYDNEY PROSSER (V.O.) And after that...say "no" a lot until the guy is hooked.
Edith and Rebecca start walking away as the businessman chases after them.
BUSINESSMAN Becky tell her!
BUSINESSMAN I've never missed a check!
SYDNEY PROSSER (V.O.) It was almost scary how easy it could be to take money from desperate people.
Edith extends her hand to greet ANOTHER BUSINESSMAN, 35.
Edith is dressed in a more sophisticated high end British fashion.
EDITH GREENSLY Lady Edith Greensly, it's so good to see you again.
ANOTHER BUSINESSMAN, 35 Lady -- your ladyship -- thank you again.
IRVING ROSENFELD (V.O.) These are the roles that we were meant to play.
Another desperate businessman sits across from Edith and Irving.
SYDNEY PROSSER We're very selective.
IRVING ROSENFELD You got a strong application.
IRVING ROSENFELD We'll talk about it.
IRVING ROSENFELD I don't take a deal that I can't close.
SYDNEY PROSSER You're not being aggressive enough in putting up your assets --
The man looks nervous --
NERVOUS LOAN APPLICANT Have you ever been to Queens?
NERVOUS LOAN APPLICANT Have you ever been to Great Neck?
NERVOUS LOAN APPLICANT Everybody knows my dealerships.
A desperate man takes out a BUSINESS CHECK BOOK and writes his check.
DESPERATE MAN Five thousand gets me fifty right?
ANOTHER BUSINESSMAN Five will get me thirty five.
ANOTHER BUSINESSMAN Is that right?
ANOTHER BUSINESSMAN, 35 Five grand gets me fifty?
Sydney and Irving laugh and celebrate.
IRVING ROSENFELD (V.O.) I was doing so much more business with her.
IRVING ROSENFELD (V.O.) I mean it doubled, then it tripled.
Sydney -- hair getting bigger -- goes over the books with a Latino Man who nods and watches her --
Edith counts cash in the register - recounts it -- explains how things can be done better as DRY CLEANING WORKER nods.
Irv watches happy.
IRVING ROSENFELD (V.O.) And I never met anyone, man or woman, in business who was so careful and precise about everything.
IRVING ROSENFELD (V.O.) Every stylistic detail.
Irving and Edith discuss a piece of art they're in the process of selling to a businessman.
IRVING ROSENFELD (V.O.) We kept selling art together, too.
EDITH GREENSLY It's really a fabulous example of a genre painting, which is really rare for the time.
EDITH GREENSLY It's a boy and his dog.
EDITH GREENSLY Non-religious painting.
EDITH GREENSLY 55.
EDITH GREENSLY Golden age.
EDITH GREENSLY Dutch painting.
IRVING ROSENFELD Paul Klee.
IRVING ROSENFELD Bauhaus Movement.
IRVING ROSENFELD 1920s.
MIDDLE AGED CAR DEALER Before we go any further, is this legit?
IRVING ROSENFELD Let's just say it's missing from Spain and leave it at that.
EDITH GREENSLY Don't show any Spanish friends.
Irving and Sydney kiss passionately in front of the middle aged car dealer as he tries to hand them his check.
IRVING ROSENFELD (V.O.) I mean it just took off.
IRVING ROSENFELD (V.O.) We got an elegant Manhattan office.
IRVING ROSENFELD (V.O.) We called it London Associates for her accent.
LONDON ASSOCIATES to a pale wall as he and Edith sip champagne from flutes and offer one to the worker who toasts with them.
Irv and Edith kiss gently, lovingly, sincerely on the lips --
They walk into their CLASSIC LOOKING, STAID, PRIVATE BANKING
IRVING ROSENFELD (V.O.) When I was around her I felt joy.
IRVING ROSENFELD (V.O.) Fucking joy!
IRVING ROSENFELD (V.O.) And love.
IRVING ROSENFELD (V.O.) That's what I felt.
47 They dance down Park Avenue together.
47
Irv and Edith dance through the lobby.
As they dance among mostly older wealthy couples on the small dance floor of the elegant restaurant as a live jazz quartet plays "I've Got Your Number".
Camera circles them, putting their foreheads together, very happy.
THEY SING TO EACH OTHER quietly as they dance close.
Irv and Edith make passionate love, we see in pieces --
He gets up, she watches him dress and leave --
53 He drives over the Triborough Bridge.
53
IRVING ROSENFELD (V.O.) As, as far as I could see, people were always conning each other to get what they wanted.
IRVING ROSENFELD (V.O.) We even con ourselves.
55 He drives through the suburb of ranch houses and driveways 55
56 and pulls into his driveway of his split-level ranch.
Irv 56 gets out of his Cadillac and walks to the front door of his house --
IRVING ROSENFELD (V.O.) We talk ourselves into things.
IRVING ROSENFELD (V.O.) We sell ourselves things we maybe don't even need or want by dressing them up.
IRVING ROSENFELD (V.O.) We leave out the risk.
IRVING ROSENFELD (V.O.) We leave out the ugly truth.
Irv walks into the decorated ranch house, frosted glass with bird designs, glass tables, walls, black and brown lacquer everywhere.
He walks into the house and looks at a picture his son did -- a drawing of the Yankees playing baseball -- that is taped to the refrigerator.
IRVING ROSENFELD (V.O.) Pay attention to that because we're all conning ourselves in one way or another just to get through life.
Irv takes Danny's picture from the fridge and tip toes -- with low sounds now of O.S. TV -- Irv goes to A CLOSED DOOR WITH YANKEE STICKERS on it --
Irv OPENS A BEDROOM DOOR TO REVEAL HIS 5 YEAR OLD SON, DANNY.
SYDNEY PROSSER (V.O.) He was married, and he had a son.
DANNY is on the bed, picture books, baseball cards, spread all around him.
Irv stands holding the picture.
Danny looks over his shoulder.
SYDNEY PROSSER (V.O.) He had adopted her son.
SYDNEY PROSSER (V.O.) He was a really good dad and I respected him for that.
SYDNEY PROSSER (V.O.) It was a tough situation for everyone.
Irv's face lights up.
IRVING ROSENFELD Danny.
IRVING ROSENFELD This is a fantastic picture.
IRVING ROSENFELD What did you do today?
DANNY That kid Donovan is being mean to me.
IRVING ROSENFELD The big kid?
IRVING ROSENFELD I thought Mommy picked you up so he couldn't bother you.
DANNY She was late, and then after we put out the fire, mommy said stay in my room with my baseball cards.
Danny reaches across to Irving and takes his glasses off his face and puts them on.
IRVING ROSENFELD What fire?
DANNY Did you know they make a lamp that has the sun in it?
DANNY [Irv looks at him] Mommy got the lamp.
DANNY She made her special drink and the lamp made a fire.
Irv looks concerned.
Irv's wife Rosalyn sits up on the bed in a muumuu, half her face is burned.
ROSALYN ROSENFELD I put out the fire.
ROSALYN ROSENFELD The fire is out.
IRVING ROSENFELD For the first time in my life I do the right thing.
Oh shut up --
I save a young single mother, and her kid.
I marry her.
I adopt him - -
You fell in love!
Don't forget we fell madly in love!
Yes, I fell in love.
My God, I fell in love.
Yes.
But you know what?
I thought you were mysterious like my mother until it turned out that mysterious just meant depressed, hard to reach.
I mean, I'm dying here!
And you need somebody who's gonna be quiet like you.
You're young, you're beautiful.
You gotta find somebody else.
You gotta go out and get some friends all right?
Don't sit inside --
I don't like going out.
You know that I get anxiety when I have to meet people.
You know how hard that is.
Yeah but you can't just stay in the house with the fucking sun lamp.
Alright?
And I can't-- I mean, look, I can't trust you with it anyway.
That fire and everything.
I can't trust to leave you with Danny.
I put the fire out Irving!
There is no fire!
Maybe if you were here more, then there wouldn't have been a fire in the first place.
Oh, what, there wouldn't have been a fire if I was here?
ROSALYN ROSENFELD Just stop with the whole fire thing.
ROSALYN ROSENFELD God it was a mistake.
ROSALYN ROSENFELD I'm sure a million people do that all the time.
ROSALYN ROSENFELD Those sun lamps are dangerous.
ROSALYN ROSENFELD Shouldn't even have them in the house, really.
ROSALYN ROSENFELD I bet that happens all the time.
ROSALYN ROSENFELD This was nothing.
IRVING ROSENFELD We're not happy.
IRVING ROSENFELD Alright?
Rosalyn just stares there for a moment at Irving saying nothing.
ROSALYN ROSENFELD You know that I could take Danny.
ROSALYN ROSENFELD You know that most of your work is illegal.
ROSALYN ROSENFELD And you know that if you tried to divorce me, you know that-- I'm not saying that I would, but I'm saying that I could.
ROSALYN ROSENFELD And I'm saying that that is why I don't like divorce, Irving.
ROSALYN ROSENFELD Women do that in divorces.
ROSALYN ROSENFELD Women get the children, and then the fathers never see them.
ROSALYN ROSENFELD My mother never got divorced.
ROSALYN ROSENFELD My grandmother never got divorced.
ROSALYN ROSENFELD There are NO divorces in my family.
ROSALYN ROSENFELD I am not getting a divorce.
IRVING ROSENFELD Come on.
IRVING ROSENFELD What are we doing here?
ROSALYN ROSENFELD We fight and we fuck and that's what we do.
ROSALYN ROSENFELD That's our thing.
IRVING ROSENFELD (V.O.) She was the Piccaso of passive aggressive karate.
IRVING ROSENFELD (V.O.) She was better than any con artist I'd ever met including myself.
IRVING ROSENFELD (V.O.) And she had me like nobody had me.
Rosalyn sheds her muumuu, to reveal a white leotard.
ROSALYN ROSENFELD Irving, come to mama.
ROSALYN ROSENFELD Come on.
IRVING ROSENFELD (V.O.) You might say she was my karma for how I took advantage of people.
ROSALYN ROSENFELD Irving, come here.
ROSALYN ROSENFELD Come on.
ROSALYN ROSENFELD Get into bed.
IRVING ROSENFELD Alright.
63 Baby, there's such good stuff here.
63
IRVING ROSENFELD (V.O.) I did not want to leave the kid behind.
IRVING ROSENFELD (V.O.) He was my son.
IRVING ROSENFELD (V.O.) She had me.
IRVING ROSENFELD (V.O.) I was her mark.
WE NOW SEE THE MARK: A charismatic, mercurial, wild eyed BUSINESSMAN "MORT PAPIERMAN" in need of a loan.
Mort's eyes go from her knees to her eyes -- His eyes meet Sydney's -- he looks soulful, open.
She stares at him.
Irv notices uncomfortably.
He's JEALOUS.
IRVING ROSENFELD -- and every deal I take, I close.
IRVING ROSENFELD However, my fee is non refundable, just like my time.
MORT PAPIERMAN/RICHIE DIMASO I want to thank you very much Irving for seeing me.
MORT PAPIERMAN/RICHIE DIMASO Sorry I'm so nervous.
Richie reaches for his top button to adjust it.
MORT PAPIERMAN/RICHIE DIMASO (CONT'D) Am I not buttoned?
Edith stares at him and smiles.
MORT PAPIERMAN/RICHIE DIMASO (CONT'D) I just gotta say Mr. Rosenfeld, that Lady Edith was very adamant that you were top notch and --
IRVING ROSENFELD That's correct.
MORT PAPIERMAN/RICHIE DIMASO I really need your help.
MORT PAPIERMAN/RICHIE DIMASO I'm desperate.
MORT PAPIERMAN/RICHIE DIMASO I've got the Audis for collateral and the two boats, and I forgot to mention that I have a little piece of real estate in Long Island.
EDITH GREENSLY No, you didn't mention that.
EDITH GREENSLY Two lunches and you never mentioned that.
MORT PAPIERMAN/RICHIE DIMASO Oh, I was gonna mention it and then the guy with the hat walked in.
EDITH GREENSLY The hat.
MORT PAPIERMAN/RICHIE DIMASO And I forgot totally.
MORT PAPIERMAN/RICHIE DIMASO It was the second time we had lunch.
EDITH GREENSLY You couldn't see his eyes.
EDITH GREENSLY He had no eyes.
EDITH GREENSLY It was like, did he make it?
MORT PAPIERMAN/RICHIE DIMASO Do they sell hats like that?
MORT PAPIERMAN/RICHIE DIMASO Where do they come from?
MORT PAPIERMAN/RICHIE DIMASO Actually, I went to the store that I thought maybe he bought it there.
MORT PAPIERMAN/RICHIE DIMASO I was gonna get you one --
EDITH GREENSLY You were going to get me one?
MORT PAPIERMAN/RICHIE DIMASO Like as a memento.
Irving decides to interject.
IRVING ROSENFELD Two lunches?
EDITH GREENSLY Yes.
EDITH GREENSLY It's two lunches.
EDITH GREENSLY What's the big deal?
IRVING ROSENFELD That's unusual.
EDITH GREENSLY I was trying to get him to be more aggressive.
EDITH GREENSLY On his loan that is.
EDITH GREENSLY Mort PAPIERMAN/RICHIE DIMASO You showed me a whole new side of the city I'd never seen before.
EDITH GREENSLY Oh, good.
EDITH GREENSLY You're welcome.
EDITH GREENSLY Mort PAPIERMAN/RICHIE DIMASO No, thank you.
IRVING ROSENFELD Yeah, right.
IRVING ROSENFELD You liked it?
IRVING ROSENFELD Should I take you there?
EDITH GREENSLY Yes.
IRVING ROSENFELD Should I take you there twice?
EDITH GREENSLY Stop.
IRVING ROSENFELD What's going on, you like this guy?
EDITH GREENSLY Yes I like this guy.
IRVING ROSENFELD Is that messing up your judgement?
IRVING ROSENFELD Don't be stupid.
SYDNEY PROSSER No, he's not messing with my judgment.
IRVING ROSENFELD Hey, play your part.
EDITH GREENSLY Fine.
EDITH GREENSLY You play your part.
MORT PAPIERMAN/RICHIE DIMASO Take it to your people in London.
MORT PAPIERMAN/RICHIE DIMASO Please, take it to them.
MORT PAPIERMAN/RICHIE DIMASO I got the cashier's check right here.
MORT PAPIERMAN/RICHIE DIMASO I give you five and you give me fifty right back, right?
MORT PAPIERMAN/RICHIE DIMASO Please.
MORT PAPIERMAN/RICHIE DIMASO Please don't reject me.
MORT PAPIERMAN/RICHIE DIMASO Give a guy a chance.
THE AIR UNCOMFORTABLY AWKWARDLY UNTIL -- almost in slow motion --Edith takes the check -- staring at Mort.
IRV STARTS
MORT PAPIERMAN/RICHIE DIMASO (CONT'D) Zurich?
MORT PAPIERMAN/RICHIE DIMASO (CONT'D) You got an office in Zurich?
MORT PAPIERMAN/RICHIE DIMASO (CONT'D) Paris?
MORT PAPIERMAN/RICHIE DIMASO (CONT'D) I can call Paris?
IRVING ROSENFELD If you could excuse me for one second?
MORT PAPIERMAN/RICHIE DIMASO Yeah, take your time.
MORT PAPIERMAN/RICHIE DIMASO Do whatever you need to do.
MORT PAPIERMAN/RICHIE DIMASO Go ahead, take your time.
AS Edith OPENS A SIDE DOOR -- BANG - FEDERAL AGENT STOCK
IRVING ROSENFELD You got the wrong office, you're gonna be embarrassed.
MORT PAPIERMAN/RICHIE DIMASO I may not have you, Irving, but I have her on fraud.
MORT PAPIERMAN/RICHIE DIMASO Impersonating another individual.
IRVING ROSENFELD Fraud?!
IRVING ROSENFELD Fraud?
IRVING ROSENFELD What is that?
IRVING ROSENFELD Identity fraud?
MORT PAPIERMAN/RICHIE DIMASO You may be from England, Edith, but you're not royal and you have no banking connections and that's a felony.
MORT PAPIERMAN/RICHIE DIMASO How long is that?
MORT PAPIERMAN/RICHIE DIMASO That's 3- 5 years I think.
EDITH GREENSLY Hey!
EDITH GREENSLY Not so tight!
IRVING ROSENFELD Oh really?
IRVING ROSENFELD That's interesting.
IRVING ROSENFELD I don't even know your real name.
Richie pulls out a badge and shoves it in Irving's face.
RICHIE DIMASO Richie Dimaso, FBI.
RICHIE DIMASO Nice to meet you.
Richie looks at Edith with concern and points at Irving.
RICHIE DIMASO (CONT'D) You gotta get away from this guy.
Agents take boxes of files out of the office- Irv standing alone in center of room- shell-shocked.
IRVING ROSENFELD (V.O.) He wouldn't let me see her for three days.
IRVING ROSENFELD (V.O.) He even managed to delay a lawyer.
Dim cell, lit only from small high barred window, no lights on.
Edith looks like she's coming apart -- circles under her eyes, a shadow of her confident self -- pale, scared, hair flat, stringy, unglamourous, pacing, rocking.
65 She couldn't handle it.
65
FLUORESCENT LIGHTS COME ON IN THE CELL -- Edith squints.
Cell is unlocked by Richie Dimaso WHO enters with a cup and saucer of tea.
He stands near her with the tea.
RICHIE DIMASO Joe, how come the fluorescents are on?
RICHIE DIMASO Can we kill that, please?
RICHIE DIMASO (to Syd) Jesus I put this lamp here for you 'cause I thought it'd be better for you.
RICHIE DIMASO There's a wire here.
RICHIE DIMASO They're scared because people hang themselves but I know you're too smart for that.
RICHIE DIMASO Where's the table and chair?
RICHIE DIMASO There's no bed here?
RICHIE DIMASO It's like a fucking asylum.
RICHIE DIMASO Joe, is everybody off today?
RICHIE DIMASO Jesus Christ it's scary.
RICHIE DIMASO Maybe I wanted to scare you.
RICHIE DIMASO I don't know.
RICHIE DIMASO Maybe it was my idea.
RICHIE DIMASO Maybe i'm a little off the beaten path you know?
RICHIE DIMASO I don't know.
RICHIE DIMASO You look dehydrated.
RICHIE DIMASO Here, want to try some tea?
RICHIE DIMASO Oh yeah, your lips are all chapped.
RICHIE DIMASO (re: tea) It's herbal.
RICHIE DIMASO My favorite.
Richie bends down to Edith who is sitting on the floor in the corner and hands her the cup and saucer.
She lifts the cup but her hand is shaking almost violently as she raises the cup to her lips.
RICHIE DIMASO (CONT'D) I know you think -- look at me.
RICHIE DIMASO (CONT'D) Hey.
RICHIE DIMASO (CONT'D) Edith.
RICHIE DIMASO (CONT'D) I know you think Irv loves you.
RICHIE DIMASO (CONT'D) I know you think you know him -- that he sees the world as a cold, dark place, and he cares about nobody but very few people on his short list: his son, his father, Rosalyn, and you.
RICHIE DIMASO (CONT'D) And you think you're at the top of that list.
RICHIE DIMASO (CONT'D) But what if you're not.
RICHIE DIMASO (CONT'D) What if you're not even on the list at all?
RICHIE DIMASO (CONT'D) He'd be in here right now if he took the check.
She thinks about this.
She trembles.
RICHIE DIMASO (CONT'D) He'd be in here right now if he took the check.
RICHIE DIMASO (CONT'D) But no, you did.
RICHIE DIMASO (CONT'D) God, it's, it's so clear to me.
RICHIE DIMASO (CONT'D) It's so crazy -- it's clear to me, but it's not clear to you.
RICHIE DIMASO (CONT'D) He uses you, Edith, to protect himself.
RICHIE DIMASO (CONT'D) To protect his son and his wife in Long Island.
RICHIE DIMASO (CONT'D) No?
RICHIE DIMASO (CONT'D) Yes.
RICHIE DIMASO (CONT'D) He put a ring on her finger, he adopted her son.
RICHIE DIMASO (CONT'D) They have huge house, they have two cars.
RICHIE DIMASO (CONT'D) What does she do all day?
RICHIE DIMASO (CONT'D) I'll tell you what she does -- she plays with her nails, she watches T.V., and she spends your money, the money that you make.
Edith stares at Richie, taking this in.
RICHIE DIMASO (CONT'D) I don't like that you're in jail while he's going free.
RICHIE DIMASO (CONT'D) I don't like any of that.
RICHIE DIMASO (CONT'D) I want to help you.
RICHIE DIMASO (CONT'D) All the razzle-dazzle that he does, it's not good.
RICHIE DIMASO (CONT'D) It's not real.
RICHIE DIMASO (CONT'D) It's fake.
RICHIE DIMASO (CONT'D) It's not real.
RICHIE DIMASO (CONT'D) Who you are is who you are, between you and God.
RICHIE DIMASO (CONT'D) You and your soul.
RICHIE DIMASO (CONT'D) That's what matters.
RICHIE DIMASO (CONT'D) That's what counts.
RICHIE DIMASO (CONT'D) That's what I'm about.
RICHIE DIMASO (CONT'D) And that's what I see in you.
RICHIE DIMASO (CONT'D) Tell me you didn't feel it the first time we saw each other.
RICHIE DIMASO (CONT'D) Am I crazy?
RICHIE DIMASO (CONT'D) I don't think so.
RICHIE DIMASO (CONT'D) I'm not supposed to be talking like this, but I don't care, I break the rules.
Edith looks at Richie in silence as she thinks about what he's saying.
RICHIE DIMASO (CONT'D) Okay, Edith?
RICHIE DIMASO (CONT'D) Edith.
RICHIE DIMASO (CONT'D) I want to help you.
RICHIE DIMASO (CONT'D) I like you.
RICHIE DIMASO (CONT'D) (whispers) I like you.
RICHIE DIMASO (CONT'D) (dead serious) I like you.
Irv stands alone on the other side of the glass staring at Sydney.
Richard Dimaso walks in.
RICHIE DIMASO Been in there three days.
RICHIE DIMASO Hasn't been so good for her.
Irv continues to stare at Sydney.
RICHIE DIMASO (CONT'D) How does that make you feel her in there?
RICHIE DIMASO (CONT'D) That check was for you, right?
RICHIE DIMASO (CONT'D) But you knew somethin' was off.
RICHIE DIMASO (CONT'D) That's 'cause you're good.
RICHIE DIMASO (CONT'D) You're, like, the best at what you do in the whole country, aren't you?
Irv looks at him.
RICHIE DIMASO (CONT'D) But you know what?
RICHIE DIMASO (CONT'D) If the country were run by people like you, Irving Rosenfeld we'd be living in Eastern Europe or Guatemala.
RICHIE DIMASO (CONT'D) You ever been in Guatemala?
RICHIE DIMASO (CONT'D) You ever been in jail in Guatemala?
RICHIE DIMASO (CONT'D) You ever try to get a telephone or a permit or anything in Guatemala?
RICHIE DIMASO (CONT'D) That's what this country would be like if we let people, let the liars like you, run this country.
IRVING ROSENFELD Who made you god and judge?
RICHIE DIMASO My grandmother lived to be ninety- three years old.
RICHIE DIMASO Never lied in her life.
IRVING ROSENFELD Congratulations.
RICHIE DIMASO Thank you.
RICHIE DIMASO I'm proud of that, too.
RICHIE DIMASO Does that make her not a good person?
RICHIE DIMASO Is that not something to strive for?
IRVING ROSENFELD Why you breaking my balls?
IRVING ROSENFELD Get to the point.
RICHIE DIMASO I see something in you, Irving.
RICHIE DIMASO I get very excited.
RICHIE DIMASO I think that we have a lot of potential here.
RICHIE DIMASO Now, look.
RICHIE DIMASO I came up with the idea.
RICHIE DIMASO It's all from me.
RICHIE DIMASO I want to change things.
RICHIE DIMASO I want to go after white collar crime.
RICHIE DIMASO Irving, you're very skilled.
RICHIE DIMASO And I want you to teach me and we can do this.
RICHIE DIMASO I want four people that do what you do.
RICHIE DIMASO Fraudulent investments.
RICHIE DIMASO Fake certificates of deposit.
RICHIE DIMASO Stolen art, fake art.
RICHIE DIMASO You get me four people and you're off the hook.
IRVING ROSENFELD Four busts and you'll leave us alone?
IRVING ROSENFELD We don't have to testify?
RICHIE DIMASO You're good, you're done.
RICHIE DIMASO Anything you want.
RICHIE DIMASO But if you run, then your life is over.
RICHIE DIMASO You'll be hunted, and it's gonna be very difficult for Rosalyn and your kid to live in this country.
A NICE UPPER EAST SIDE apartment.
Sydney has finally changed her clothing from when she wore the same dress at the holding cell.
It is quiet in the apartment - faint street noise from 3rd Avenue below.
SYDNEY PROSSER We need to leave.
SYDNEY PROSSER We need to run and we need to do it now.
SYDNEY PROSSER We can go to Estonia or Romania, I don't care, we'll take the cash from the bed and get out of here, alright?
SYDNEY PROSSER We talked about it a hundred times.
Irv stares at her and struggles.
IRVING ROSENFELD What about Danny?
SYDNEY PROSSER What about Danny?
IRVING ROSENFELD I adopted him!
IRVING ROSENFELD I gave him my name!
IRVING ROSENFELD I'm not leaving him with Rosalyn, she's unstable!
SYDNEY PROSSER That's a manipulation!
SYDNEY PROSSER Rosalyn's will never let you go.
SYDNEY PROSSER She'll use Danny against you because she's too messed up to let you leave.
IRVING ROSENFELD I can't leave him.
IRVING ROSENFELD I love him.
IRVING ROSENFELD Alright?
IRVING ROSENFELD He's my son.
SYDNEY PROSSER Richie said you would say that.
IRVING ROSENFELD Richie?
IRVING ROSENFELD What, the cop?
IRVING ROSENFELD Your on a first name basis with him?
SYDNEY PROSSER Yes I am.
SYDNEY PROSSER I'm not even on your list am I?
IRVING ROSENFELD What list?
SYDNEY PROSSER Your list.
SYDNEY PROSSER Your short list.
SYDNEY PROSSER Your long list.
SYDNEY PROSSER I'm not even on anyone of your fucking lists.
SYDNEY PROSSER I thought you loved me.
SYDNEY PROSSER I thought we had something.
IRVING ROSENFELD We do have something.
IRVING ROSENFELD I love you, it's perfect!
IRVING ROSENFELD What are you saying?
IRVING ROSENFELD We're gonna go to Romania?
IRVING ROSENFELD We're gonna take Danny?
SYDNEY PROSSER Yes.
SYDNEY PROSSER Yes, that's what I'm saying.
SYDNEY PROSSER You, me, Danny.
IRVING ROSENFELD Well you never said that before.
SYDNEY PROSSER I'm saying it now.
SYDNEY PROSSER We're us, and we can make it an adventure like we did.
SYDNEY PROSSER We can make it an adventure like we make everything, alright?
SYDNEY PROSSER But we have to go now.
SYDNEY PROSSER We have to leave right now.
IRVING ROSENFELD I can't leave Danny.
IRVING ROSENFELD I'll lose custody.
SYDNEY PROSSER You have to take me away!
SYDNEY PROSSER We have to leave!
SYDNEY PROSSER What are you saying?!
SYDNEY PROSSER Oh my god.
IRVING ROSENFELD What are you doing?!
IRVING ROSENFELD Please!
Sydney goes storming out of the room and down the hall of her apartment.
Irving follows.
SYDNEY PROSSER I can't believe this is happening.
IRVING ROSENFELD Don't say I don't love you because that's bullshit!
SYDNEY PROSSER This is bullshit.
SYDNEY PROSSER You are bullshit.
SYDNEY PROSSER We are bullshit.
She starts sobbing, shaking.
IRVING ROSENFELD Please don't do this.
SYDNEY PROSSER I just never thought you were conning me.
IRVING ROSENFELD I could never con you.
IRVING ROSENFELD I love you.
IRVING ROSENFELD Please don't say this.
Irv walks to her and bends down to join her on the floor as she sobs.
SYDNEY PROSSER No, I'm done.
IRVING ROSENFELD Don't say that.
SYDNEY PROSSER I'm gonna do these four busts, these four cons, to get us out of this.
SYDNEY PROSSER Not just me, but us.
SYDNEY PROSSER And I'm gonna get really close with Richie, the cop, in case we need to use him, if we need another move.
IRVING ROSENFELD We don't need another move.
IRVING ROSENFELD We need four busts, and we're done.
SYDNEY PROSSER We are going to need another move, trust me.
SYDNEY PROSSER And you're going to be thanking me.
SYDNEY PROSSER (shifts to British accent) The key to people is what they believe and what they want to believe and I want to believe that we were real, and I want to believe that a man could want me.
SYDNEY PROSSER And I'm gonna take all of that heartbreak, and all of that sorrow, and I am going to use it.
SYDNEY PROSSER And I'm going to make Richie think that I want him, and that I like him, and I'm going to be very convincing -- And I'm pissed at you.
Sydney reaches over and carefully grabs Irving's face lovingly which quickly turns into a slap as she continues on.
SYDNEY PROSSER (CONT'D) Because I'm pissed at you!
Irving stares at Sydney with confusion.
He's never seen her like this before.
SYDNEY PROSSER (CONT'D) Maybe I do like him -- Maybe I like him a lot.
SYDNEY PROSSER (CONT'D) From the feet up right -- baby?
Sydney gets up from the couch and storms back to her room.
SYDNEY PROSSER (CONT'D) Quite your belly aching and come up with something to get us out of this.
SYDNEY PROSSER (CONT'D) And you're right -- I'm in no state to deal with this so what's it gonna be, Mister Mastermind?
69 An Arab sheik?
Why do we need an 69 Arab Sheik?
Richie, in sharp lapeled suit, chain on his neck, walks with Irv and Edith and joined by a man who looks like an ARAB SHEIK who they trail.
IRVING ROSENFELD How do you think this works, stupid?
SYDNEY PROSSER If you could not call him `stupid' which he's isn't, he's smarter than you.
SYDNEY PROSSER Last I checked he's in control here and we work for him now so be nice.
Richie stares at Edith elated that she just stuck up for him.
He's really enjoying this position of power she's putting him in.
IRVING ROSENFELD OK, to set this up and bust a con artist we have to make the honey pot to attract the bees.
IRVING ROSENFELD In order to attract the bees, we need to offer them a wealthy individual who can be taken advantage of, someone special, someone new, someone amazing.
IRVING ROSENFELD Then those guys will want to sell fake bank CDS to THAT guy, take the sheik's money, see?
Richie looks at Irving uncertain.
SYDNEY PROSSER Only they can't get into his money unless you they know someone, and that someone is us.
RICHIE DIMASO Oh that's good.
RICHIE DIMASO (CONT'D) So if you want to get somebody like your con artist friend -- Carl Elway -- you get him to want to buy-
IRVING ROSENFELD Keep your voice down.
RICHIE DIMASO -- or sell fake art or stolen art or fake certificates of deposit, he needs -- who does he need?
RICHIE DIMASO -- he needs a rich sheik guy, and there you go -- we can pinch him!
IRVING ROSENFELD Right, but I don't tell Elway shit.
IRVING ROSENFELD I wait for him to call me.
IRVING ROSENFELD The art world is a small world -- and one of Elway's acquaintances is clocking us right now.
Richie starts to look around.
RICHIE DIMASO Where?
IRVING ROSENFELD Don't look.
Richie looks anyway and sees ELWAY'S ACQUAINTANCE, a man balding, 45 clocking them from the balcony.
IRVING ROSENFELD (CONT'D) You have a good look?
RICHIE DIMASO How do you know the Sheik?
IRVING ROSENFELD This is my friend Al from Queens.
AL FROM QUEENS/SHEIK I do aluminum siding and roofing.
Richie stares, impressed.
Irving, Edith, Richie, and the fake Sheik admire a REMBRANDT painting on the wall.
IRVING ROSENFELD I want to show you something.
IRVING ROSENFELD This Rembrandt here?
IRVING ROSENFELD People come from all over the world to see this.
RICHIE DIMASO Yeah, he's good.
IRVING ROSENFELD It's a fake.
RICHIE DIMASO Wait, what're you talking about?
RICHIE DIMASO That's impossible.
IRVING ROSENFELD People believe what they want to believe.
IRVING ROSENFELD Cause the guy who made this was so good that it's real to everybody.
IRVING ROSENFELD Now whose the master -- the painter or the forger?
Richie's continues to stare at the REMBRANDT on the wall.
RICHIE DIMASO That's a fake?
IRVING ROSENFELD That's the way the world works.
IRVING ROSENFELD Not black and white as you say.
IRVING ROSENFELD Extremely grey.
ELWAY'S ACQUAINTANCE walks up to Irving and the group and steps into the conversation.
ELWAY'S ACQUAINTANCE Irving can I --
IRVING ROSENFELD How many times I gotta tell you.
IRVING ROSENFELD You can't meet the sheik, alright?
Edith sees this and steps into the conversation.
EDITH GREENSLY Arthur?
EDITH GREENSLY Hi.
EDITH GREENSLY Edith.
EDITH GREENSLY We've met before.
EDITH GREENSLY (CONT'D) I wanted to introduce you to Robert Spencer.
EDITH GREENSLY (CONT'D) We're advising the Sheik together.
EDITH GREENSLY (CONT'D) She looks at Richie.
EDITH GREENSLY (CONT'D) Richie offers his hand.
RICHIE DIMASO Yeah, I'm Robert Spencer, advisor to the sheik.
CARL ELWAY, 40, preppie Waspy, very old fashioned with cigarette holder, but something vaguely criminal about him, in his conservative suit, natty white and red striped shirt, and navy blue tie sits with Irving.
CARL ELWAY What's this I hear about a god damn Sheik?!
CARL ELWAY Why you leaving me out of this?
CARL ELWAY I gotta hear about it from my friends?
IRVING ROSENFELD It ain't for you Carl.
CARL ELWAY What do you mean it ain't for me?
CARL ELWAY We gotta do certificates of deposit.
CARL ELWAY I can print as many as you need.
IRVING ROSENFELD This is not a one man operation.
CARL ELWAY Look, I can get other guys.
CARL ELWAY What are you talking about Irving?
IRVING ROSENFELD You're telling me that you can get four guys to sell fake certificates of deposit to my investor within a week?
IRVING ROSENFELD The camera zooms into Irving's shirt collar revealing a tiny microphone.
CARL ELWAY Yes I can make that happen.
CARL ELWAY Carl Elway can do what he says he's going to do.
IRVING ROSENFELD That's interesting but you know I've got other guys lined up.
IRVING ROSENFELD I've got a meeting with my associates.
Richie Dimaso and Edith ARE STANDING THERE -- MUCH TO IRV'S
CARL ELWAY'S ASSISTANT Carl, his associates are here.
CARL ELWAY'S ASSISTANT He's got a meeting he's got to go to.
CARL ELWAY No wait.
CARL ELWAY Don't go anywhere.
IRVING ROSENFELD I've got to go.
Irving gets up to walk out as Richie and Edith stand in the doorway.
IRVING ROSENFELD (V.O.) Crazy thing about people -- the more you say no, the more they want in on somethin.
IRVING ROSENFELD (V.O.) It is so stupid.
Irving looks over at Richie and Edith.
IRVING ROSENFELD I'll tell them, don't worry.
IRVING ROSENFELD Hey you know what Carl just told me?
IRVING ROSENFELD He said he could do this whole thing with four guys within a week.
CARL ELWAY Or we could do somethin' much bigger!
Richie jumps into the conversation.
RICHIE DIMASO Something bigger?
RICHIE DIMASO My guy deals with hundreds of millions of dollars.
RICHIE DIMASO How much bigger?
He walks over to Carl.
CARL ELWAY Hundreds of million -- I knew you were holdin' out on me Irving!
CARL ELWAY Hundreds of millions of dollars?
CARL ELWAY Like much bigger.
CARL ELWAY Like I'm talking about we say never the fuck mind the CD's and we could have some complete access to something huge.
RICHIE DIMASO Huge?
RICHIE DIMASO Like what?
RICHIE DIMASO (introducing himself) Robert Spencer, advisor to the Sheik.
CARL ELWAY Carl Elway.
Irv stares at Richie with contempt, then turns to Edith,
CARL ELWAY (CONT'D) I want you to think of the most undervalued asset in the state of New Jersey today.
CARL ELWAY (CONT'D) The rebuilding of Atlantic City.
Richie looks over at Irving and Sydney and mouths the word
CARL ELWAY (CONT'D) Look, maybe they, maybe they legalized gambling a year ago but nothing's happening.
Irving interjects.
IRVING ROSENFELD Hey, quit while you're ahead Carl.
CARL ELWAY I know the guy.
CARL ELWAY I know the right people who are going to help you out.
RICHIE DIMASO Whose the guy?
CARL ELWAY The guy is Carmine Polito.
RICHIE DIMASO Whose Carmine Polito?
PUSH IN: STODDARD THORSEN, Richie's FBI supervisor.
STODDARD THORSEN Carmine Polito?
STODDARD THORSEN Carmine Polito, no.
We freeze frame on Stoddard as we HEAR Richie'S VO:
AS Richie TALKS WE SEE A SHORT FILM ABOUT Carmine Polito:
- PUSH IN: Mayor Polito walks a Camden street waves, shakes hands of WELL-WISHERS
RICHIE DIMASO (V.O.) My boss Stoddard proceeded to tell me that Carmine Polito was the most quietly powerful person in the state of New Jersey.
RICHIE DIMASO (V.O.) A lifetime native of the very racially mixed Camden, which had become a ghetto, and where he had been Mayor for ten years.
RICHIE DIMASO (V.O.) A very beloved guy.
RICHIE DIMASO (V.O.) A guy who never gave up on his people.
RICHIE DIMASO (V.O.) His father had emigrated from Italy and had stoked coal.
- Frank Sinatras COFFEE SONG, 1940s version, as we see Carmine talk to and dance joyfully with his kids and wife at breakfast.
RICHIE DIMASO (V.O.) A big family guy with five kids.
RICHIE DIMASO (V.O.) They even adopted some other kid.
RICHIE DIMASO (V.O.) A black kid from the Boys and Girls Club who'd lost his family.
RICHIE DIMASO (V.O.) I mean, his household was a joyous place.
RICHIE DIMASO (V.O.) And his wife Dolly, she was the apple of his eye and the center of the household.
RICHIE DIMASO (V.O.) I mean everyone loved this guy.
- PULL OUT Mayor Polito walks up steps of City Hall as he greets a women and her baby; into his office greeted by a couple of AIDES who show him papers to sign.
RICHIE DIMASO (V.O.) And he had a huge heart.
CARMINE POLITO The W.P.A. employed craftsmen to paint this during the Depression.
CARMINE POLITO Why can't we employ people today to do work like this in rebuilding Atlantic City?
RICHIE DIMASO (V.O.) He worked with all the unions.
RICHIE DIMASO (V.O.) He was the leader of the State Assembly.
RICHIE DIMASO (V.O.) And he had just gotten gambling legalized in New Jersey to create jobs.
80 -- FLOOR OF STATE ASSEMBLY -- Carmine huddles with other 80 STATE LEGISLATORS, horsetrading and then poses for a picture with other members of the State Assembly.
RICHIE DIMASO (V.O.) But he couldn't get the funds to rebuild Atlantic City and that was his problem.
RICHIE DIMASO (V.O.) So with our help, he was about to have his hand in the wrong pocket at the wrong time.
RICHIE DIMASO (V.O.) And to me that meant corrupt
STODDARD THORSEN You said grifters and con artists.
STODDARD THORSEN We're not going after some politician.
STODDARD THORSEN This is a bad idea, Richard.
RICHIE DIMASO Shhhh.
RICHIE DIMASO Look, it's really simple.
RICHIE DIMASO All you need is to put two million in a Chase account --
STODDARD THORSEN What?!
RICHIE DIMASO (CONT'D) -- under the Sheik's name --
STODDARD THORSEN Whose two million?!
RICHIE DIMASO Shh, just listen.
RICHIE DIMASO Two million dollars under the Sheik's name, in a Chase account that we control.
RICHIE DIMASO Carmine calls up on the telephone -- calls the bank -- and he sees that the Sheik is real and he has a real account.
RICHIE DIMASO Five days.
STODDARD THORSEN I'm not taking two million dollars of the taxpayers' money and putting it anywhere for five days, I don't care if we control it the whole time.
Richie as he stares at Stoddard in frustration.
RICHIE DIMASO Stoddard, let us do what we need to do to rule out corruption and to get rid of the payoff guys that are ruining this country.
RICHIE DIMASO That's my dream.
RICHIE DIMASO Don't smother it, please.
STODDARD THORSEN You know Richard, I understand your eagerness.
STODDARD THORSEN I really do.
STODDARD THORSEN You know I'm from Michigan, right?
STODDARD THORSEN Let me tell you a story about me, and my dad, and my brother.
STODDARD THORSEN We used to go ice fishing every November.
STODDARD THORSEN Ice Fishing.
STODDARD THORSEN That's what we lived for.
RICHIE DIMASO Holy shit --
STODDARD THORSEN Just listen to me.
STODDARD THORSEN It's beautiful.
STODDARD THORSEN You have a little stove.
STODDARD THORSEN You huddle around, you keep each other warm.
STODDARD THORSEN You drop a line and you just wait.
STODDARD THORSEN One year my brother says, "let's go in October."
STODDARD THORSEN He wants to go ice fishing in October.
STODDARD THORSEN My dad says, "No, the ice is too thin."
STODDARD THORSEN My brother says -- I love my brother he says --
RICHIE DIMASO I understand what's happening.
RICHIE DIMASO You're saying your brother went out on the ice, the ice was too thin, he fell through the ice, he went in the water because he was too eager, and you're saying I'm too eager -- that's what you're saying?
STODDARD THORSEN No, that's not what I'm saying.
RICHIE DIMASO What are you saying?
STODDARD THORSEN We'll finish the ice fishing story another time, young man.
STODDARD THORSEN For now, no Carmine Polito.
STODDARD THORSEN Go do your job.
Richie looks at him annoyed and upset.
RICHIE DIMASO (V.O.) Stoddard shot the whole thing down.
RICHIE DIMASO Boring.
RICHIE DIMASO (V.O.) (CONT'D) But Edith was a genius.
83 SEE B-ROLL OF: Edith and Richie walk back into FBI building, 83
84 down corridor; 84
RICHIE DIMASO (V.O.) (CONT'D) She somehow found this woman who controlled the wire room.
RICHIE DIMASO (V.O.) (CONT'D) A woman I'd never heard of.
RICHIE DIMASO (V.O.) (CONT'D) Way back in a warren buried in the Bureau.
RICHIE DIMASO (V.O.) (CONT'D) This cat lady nobody even talked to.
RICHIE DIMASO (V.O.) (CONT'D) Edith met her in the ladies room and became friends with her.
RICHIE DIMASO (V.O.) (CONT'D) This lady handled all the wires and now, she was working with us.
85 Edith and Richie enter to find BRENDA, FBI, MATRONLY, OLDER; 85 EDITH carries a basket of exotic teas;
RICHIE DIMASO (V.O.) (CONT'D) She was excited to be included in an operation instead of being on the other end of a memo.
RICHIE DIMASO (V.O.) (CONT'D) It was beautiful.
Edith goes to hand her the PIMMS CUP and basket of teas.
EDITH GREENSLY Brenda, hi!
BRENDA MCPHERSON Hi!
EDITH GREENSLY You said you liked exotic food, so that's from England.
BRENDA MCPHERSON That's from England?
EDITH GREENSLY That's right.
EDITH GREENSLY And I brought you some tea as well.
BRENDA MCPHERSON Thank you so much!
BRENDA MCPHERSON Nobody ever tells me about these operations, they just say, "Brenda, do the clerical wiring work and don't ask questions."
EDITH GREENSLY You need to tell Richie about your cats.
EDITH GREENSLY He loves them.
BRENDA MCPHERSON Oh my cats?!
Brenda starts pointing out pictures of all her cats tacked to the walls amidst the wire memos and paperwork.
BRENDA MCPHERSON (CONT'D) Well that's Harry -- look at him standing up, isn't that sweet?
BRENDA MCPHERSON (CONT'D) And that's Wendy.
BRENDA MCPHERSON (CONT'D) She's a rascal.
BRENDA MCPHERSON (CONT'D) But Barnaby, that's another story.
BRENDA MCPHERSON (CONT'D) Barnaby plays the piano!
RICHIE DIMASO That's impressive.
RICHIE DIMASO (V.O.) (CONT'D) We got her to wire two million dollars into an F.B.I.-controlled account at Chase.
RICHIE DIMASO (V.O.) (CONT'D) It'd be there for five days and if Polito called he'd see that the Sheik was real.
Edith and Richie laugh excitedly as they walk the hallways.
RICHIE DIMASO (V.O.) (CONT'D) By the time Stoddard caught up to us Edith made sure his boss was impressed by my idea.
RICHIE DIMASO (V.O.) (CONT'D) So before he even knew it was happening his boss was calling to congratulate him.
ANTHONY AMADO I'm very impressed.
ANTHONY AMADO That was very smart.
ANTHONY AMADO The Sheik with the money in the bank is a fantastic...don't be modest.
RICHIE DIMASO (V.O.) Anthony Amado.
RICHIE DIMASO (V.O.) He was the U.S.
RICHIE DIMASO (V.O.) Attorney, and he had a major hard- on to make a name for himself.
RICHIE DIMASO (V.O.) I mean this guy loved the idea of being famous.
RICHIE DIMASO (V.O.) And Stoddard had to say it was his own idea or he'd look stupid in front of his boss.
89 PUSH IN ON STODDARD -- confused, dismayed.
89
STODDARD THORSEN Thank you, sir, wait, the sheik --
He hangs up, pissed, confused.
STODDARD THORSEN You made me accept praise from my boss who's thanking me for something that never shoulda happened!
STODDARD THORSEN Something that I didn't approve!
RICHIE DIMASO You should be happy.
RICHIE DIMASO There's imaginative things happening in this office, alright?
RICHIE DIMASO We're not just working in a box.
Richie leaves triumphant.
RICHIE DIMASO (V.O.) (CONT'D) We got the two million to put Carmine and the Sheik together.
STODDARD THORSEN Punk.
Laughing Richie and Edith walk briskly on their way out.
RICHIE DIMASO (V.O.) I liked being on this side of the line.
RICHIE DIMASO (V.O.) But someone had been left out.
IRVING ROSENFELD We succeeded because we stayed small.
IRVING ROSENFELD I got you Carl Elway.
IRVING ROSENFELD He bought stolen art, sold fake bank C.D.'s, that's enough.
IRVING ROSENFELD That's one.
IRVING ROSENFELD I get you three more -- no politicians.
Richie and Edith look at him.
RICHIE DIMASO You're gonna do this because you got no choice.
RICHIE DIMASO You work for me.
IRVING ROSENFELD Now you keep changing the rules.
IRVING ROSENFELD You're gettin' a little power drunk, Richard.
You want to tell him, Edith?
You want to wake him up?
Oh no, I said we shouldn't do any of it, Irving.
You know I said that.
So now I support Richie.
He's got vision.
Do it heavy or don't do it.
I mean, he's the one ruining America, not me.
How the hell am I ruining America?
Because people just got over Watergate and Vietnam, alright?
And you're gonna shit all over politicians again?
And just because you want to be a big shot and get a promotion.
No I'm thinking big.
This is gonna be fantastic.
We're doing video surveillance.
I'm doing this from the feet up.
You will never do it properly because you got too much government attitude to be small and sleek.
I'm like the fuckin' Vietcong, man.
I'm in and I'm out.
I was there the whole time -- you don't know it.
That's the fucking art of becoming somebody who people can pin their beliefs and their dreams on.
And you can't do it.
How about a suite at the Sheraton Hotel?
For Carmine Polito and rebuilding Atlantic City?
Why not?
IRVING ROSENFELD You need a luxury hotel for the Sheik.
IRVING ROSENFELD Come on!
RICHIE DIMASO Carmine does back door dealings all the time.
RICHIE DIMASO We don't have a budget for that Irving!
IRVING ROSENFELD You gotta knock the Mayor, the Speaker of the State Assembly -- you gotta knock him off of his fucking feet.
IRVING ROSENFELD He's gotta feel like he's out of his league.
IRVING ROSENFELD What you're offering, this deal, I mean, this is unheard of in the state of New Jersey, maybe even the whole fucking country.
IRVING ROSENFELD A sheik with hundreds of millions of dollars to rebuild Atlantic City -- are you fuckin' kidding me?
IRVING ROSENFELD That's gigantic.
IRVING ROSENFELD And the Mayor, he's going to want to see cash, he's going to want to see it in an account, he's going to want to see it right now, and he will check.
IRVING ROSENFELD And that's why this meeting isn't happening, because to get millions, you need millions.
Edith listens intently.
EDITH GREENSLY We already did it.
IRVING ROSENFELD What?
Irv studies Richie and Edith.
EDITH GREENSLY We got the bureau to park 2 million for three days -- we got the account numbers.
IRVING ROSENFELD `We' meaning you and him?
RICHIE DIMASO Yeah we did it.
IRVING ROSENFELD Really?
EDITH GREENSLY Yeah, me and that guy.
RICHIE DIMASO She showed me.
IRVING ROSENFELD You showed him our thing?
IRVING ROSENFELD You did that without me?
IRVING ROSENFELD Are you kidding me?
EDITH GREENSLY What are you going to do?
RICHIE DIMASO You playing me?
RICHIE DIMASO Are we doing this?
RICHIE DIMASO Or you playing him?
RICHIE DIMASO It'd be very bad for you if you're playing me.
EDITH GREENSLY You're going to have to decide for yourself, kid, I just laid everything out on the table.
RICHIE DIMASO This is all very exciting, I never knew life could be like this.
RICHIE DIMASO You're wild.
RICHIE DIMASO You know we're taking down a very important politician.
Richie stands very close to Edith - between her legs as she sits on the counter.
He puts his hands on her hips, pulls her into him.
He takes her hand -- puts it on his face, makes her feel his cheek and forehead with her hand.
It is intense.
She prepares for him to kiss her but he steps back.
They are both excited.
They stare at each other.
The air is thick with tension, Richie exhales and leaves.
RICHIE DIMASO (CONT'D) This is agent Richard Dimaso, I'm placing $75,000 into this briefcase for Mayor Carmine Polito to procure casino license and building permits for Atlantic City.
Where the film started --
See RICHIE TALK TO CAMERA IN A CORNER OF THE PLAZA SUITE--
IRVING'S EYES WIDEN AS WE CUT TO: Richie SLIDE THE BRIEFCASE OF CASH, AS SEEN BEFORE, Edith puts her hand on top of Richie's to stop him.
Carmine Polito, upset, storms down the street as Irving catches up.
IRVING ROSENFELD Mr. Mayor -- Please stop.
IRVING ROSENFELD Listen, I apologize if that prick offended you.
IRVING ROSENFELD I really apologize.
Carmine will not turn around -- Irving catches up.
CARMINE POLITO Really, I'm all right, thank you.
CARMINE POLITO I'm okay.
IRVING ROSENFELD No.
IRVING ROSENFELD I'm fucking embarrassed to be associated with that guy at all.
IRVING ROSENFELD Can I just say somethin' to you, please?
IRVING ROSENFELD Don't lose this opportunity to fuckin' Florida -- all right?
IRVING ROSENFELD -- because of some bullshit from that punk advisor with his diploma who could never get into the school that we come from.
IRVING ROSENFELD Don't lose that opportunity.
CARMINE POLITO Where you from?
IRVING ROSENFELD I'm from the Bronx.
IRVING ROSENFELD Grand Concourse, Hundred and Sixty-fourth Street.
CARMINE POLITO I got a lot of friends that live up there.
CARMINE POLITO I go to Tomaso's on Arthur Avenue.
CARMINE POLITO You know Tomasos's?
IRVING ROSENFELD Yeah, Tomaso's.
CARMINE POLITO The spicy clams.
IRVING ROSENFELD Yes.
IRVING ROSENFELD They're always good.
CARMINE POLITO Oh, they're to fucking die for, those clams.
CARMINE POLITO I haven't been there in a while.
CARMINE POLITO I like that place.
IRVING ROSENFELD Carmine -- can I call you Carmine?
IRVING ROSENFELD You know, Carmine -- (catches his breath) My fuckin' heart's going from running down the stairs -- I'm not used to running.
IRVING ROSENFELD There's a lotta green grass in that hotel room up there, alright?
IRVING ROSENFELD And all the deals would float through you.
IRVING ROSENFELD You get a serious piece on both ends.
IRVING ROSENFELD You do with that what you will.
IRVING ROSENFELD I live in the real world, I am a family man, I got mouths to feed and everything.
IRVING ROSENFELD But, you know, we just...we gotta grease you directly.
IRVING ROSENFELD No middlemen, no bullshit.
IRVING ROSENFELD It's the Arab way.
CARMINE POLITO Yeah, look, I understand.
CARMINE POLITO It's a great opportunity.
CARMINE POLITO It's just I got a little thrown by going to have a meeting with somebody who ended up not being there, so --
IRVING ROSENFELD Hey, listen, I was thrown as well.
CARMINE POLITO I understand.
CARMINE POLITO I'll deal with you directly.
CARMINE POLITO I don't want any middleman or any of that bullshit.
IRVING ROSENFELD Done.
CARMINE POLITO I like you.
CARMINE POLITO Eye to eye.
CARMINE POLITO We can do business together.
Irv smiles and nods as they walk back into the hotel together.
CARMINE POLITO (CONT'D) How long do you know this guy?
CARMINE POLITO (CONT'D) You work with this guy before?
IRVING ROSENFELD I gotta work with him.
IRVING ROSENFELD He's the Sheik's man.
CARMINE POLITO But I still need to meet the Sheik, okay?
IRVING ROSENFELD Done.
IRVING ROSENFELD I'm going out to dinner with Carmine and the wives in Camden.
RICHIE DIMASO Who?
IRVING ROSENFELD Carmine and myself and the wives.
RICHIE DIMASO What?!
RICHIE DIMASO Without me?!
He doesn't like you, what do you want from me, I got him to come back and take the money and you got him on tape alright?
I can't make him like you.
I did my job.
Did you tell him you were working with me?
That I'm the Sheik's associate?!
I just fucking told you he doesn't like you.
I mean, let him have a night out with a human being for fuck's sake, he's going to jail soon.
You're done with him.
You got him on tape taking a bribe.
Carmine has got to deal with me, Irving.
We're gonna use Carmine.
We're gonna use Carmine to get other people, that's what we're gonna do.
What?!
Like who?!
Carmine's gonna use the Sheik to pay off people.
Are you fuckin' nuts?
What are you say--
We're gonna let Carmine show the Sheik Atlantic City, how he's gonna renovate hotels, and see who shows up.
Whoever the Sheik pays off for licenses and casinos, that's who we're gonna go after.
We're gonna go after all of 'em!
More politicians?
You realize how fuckin' dangerous that is?
There's no fucking reasoning with you.
IRVING ROSENFELD (CONT'D) Edith and I were so successful for so long because we kept it just small enough.
IRVING ROSENFELD (CONT'D) You are takin' us to a very fucking dangerous place, with very serious numbers!
RICHIE DIMASO If your that successful, how come you wound up in this room with me?
RICHIE DIMASO Taking orders from me.
EDITH GREENSLY You're taking your wife out to dinner?
EDITH GREENSLY Your fucking wife?
EDITH GREENSLY Did I just hear you correctly?
IRVING ROSENFELD That's the one thing you heard me say?
EDITH GREENSLY I just find it rather shocking that's all.
IRVING ROSENFELD I get to handle two wives with one dinner, alright?
IRVING ROSENFELD I take Rosalyn out, she keeps her mouth shut, she sees that my work is legitimate, I get to keep my kid, and I get to keep (pointing at Richie) that fucking wife happy.
IRVING ROSENFELD Both wives happy.
Sydney sits alone in her apartment, hair in curlers and sparks a joint.
Richie sits in his bathroom, his hair in tight curlers, as he eats a chicken wing.
RICHIE'S MOTHER Richard!
RICHIE'S MOTHER What are you doing?
RICHIE'S MOTHER Don't eat in the bathroom, I told you so many times!
RICHIE'S MOTHER And Diane brought Napoleons for dessert.
RICHIE'S MOTHER Come out of the bathroom and pray!
RICHIE DIMASO Oh my god, what did you do?
RICHIE'S MOTHER Richard, the filter is broken in the fish tank.
RICHIE'S MOTHER It's a problem.
RICHIE DIMASO See, your job is to do the filter, Mom, mine is to do the gravel.
RICHIE DIMASO When you don't do the filter right all the fish die.
RICHIE DIMASO See?
RICHIE'S MOTHER I can't get the top on that filter.
RICHIE DIMASO I've gone over this a hundred times mom --
RICHIE'S MOTHER -- and please help Richard to marry Diane so that I may have grandchildren and the Pope may have more followers.
RICHIE'S MOTHER And please bless this food that we are about to eat -
RICHIE DIMASO Yeah, hello?
EDITH GREENSLY Hi.
RICHIE DIMASO Who's this?
It's Edith.
Sit down and pray properly!
Are you alright?
Yeah, I'm fine, I'm just alone, you know?
Irving's out with Carmine.
That's right, he went out with Carmine and his wife.
You must not feel so good about that.
Richard, sit down!
Wait who's there?
Who are you with?
Oh, no, it's just people.
People?
I'm your fiancee!
Richard!
Oh, you've got a fiancee.
You're engaged.
Well, I don't know, no fiancee.
I don't know.
You don't know if you have a fiancee?
I don't know --
You don't know?
You don't know if you have a fiancee?
The fish filter is broken!
RICHIE DIMASO I don't.
RICHIE DIMASO No.
EDITH GREENSLY Hmm -- intersting.
RICHIE DIMASO Hey, you want to get together?
RICHIE'S MOTHER Richard, do something about the fish tank.
EDITH GREENSLY Fifty-fourth Street?
RICHIE DIMASO OK, fifty-fourth street.
RICHIE DIMASO That's what that phone call's about.
RICHIE DIMASO Everybody thought, "Oh, Richie DiMaso's gonna stay in the office, pushing papers."
RICHIE DIMASO That's not gonna happen, Mom.
RICHIE DIMASO I'm outside in the field.
RICHIE DIMASO I got people working for me.
RICHIE DIMASO My ideas.
RICHIE DIMASO I'm running the show.
RICHIE DIMASO I'm the quarterback.
RICHIE DIMASO And I'm not gonna settle for no one, Mom.
98 Ext.
BARON'S ITALIAN RESTAURANT- CAMDEN- NIGHT 98
SLOW MOTION: Carmine and DOLLY POLITO (big frosted hair) get out of his maroon Lincoln Town car.
Irv and Rosalyn Rosenfeld get out of his green Cadillac.
SOME
Ella continues.
Mixture of LOCALS: ITALIANS, POLISH, BLACKS AND PUERTO RICANS -- wave to the mayor from the bar, and tables, as Irv and Rosalyn follow.
CARMINE POLITO Rocco, you know like we do.
CARMINE POLITO The chicken very thin.
CARMINE POLITO You should see the way he does this chicken with the red sauce
DOLLY POLITO It's beautiful.
CARMINE POLITO Right?
CARMINE POLITO With the red sauce, the lemon--
CARMINE POLITO Dolly kisses Carmine as he gives his wife's leg a squeeze and kisses her cheek, then her mouth.
CARMINE POLITO Irv and Rosalyn squeeze hands on the table.
CARMINE POLITO SHE KNOCKS BACK A GLASS OF RED WINE as a plate of Chicken Picatta is served to the table.
DOLLY POLITO It's the Piccata of the gods!
DOLLY POLITO She pulls away awkwardly, waiter refills her glass which she throws back right away.
DOLLY POLITO Irv looks concerned.
DOLLY POLITO They all drink.
101 CUT TO - LATER: Carmine and Irving talk.
101
IRVING ROSENFELD I believe that you should treat people the way that you want to be treated.
CARMINE POLITO Right.
IRVING ROSENFELD Didn't Jesus say that or something?
CARMINE POLITO He may have.
IRVING ROSENFELD Also, always take a favor over money.
IRVING ROSENFELD I think Jesus said that as well.
CARMINE POLITO I don't know if he said the second one but he may have said the first one.
CUT TO -- Rosalyn DRUNKENLY LEANS IN TALKING TO Dolly POLITO
ROSALYN ROSENFELD I chip them moving furniture, it's my obsession -- Moving, re- decorating, it makes me feel better like exercise.
ROSALYN ROSENFELD There's this top coat that you can only get from Switzerland and I don't know what I'm going to do because I'm running out of it but I LOVE the smell of it.
DOLLY POLITO I can get that for you, of course.
ROSALYN ROSENFELD There's something, the topcoat, (sniffs nails) it's like perfumey but there's also something rotten?
ROSALYN ROSENFELD I know that sounds crazy, but I can't get enough of it.
Dolly laughs.
ROSALYN ROSENFELD (CONT'D) No, smell it.
ROSALYN ROSENFELD (CONT'D) It's true.
ROSALYN ROSENFELD (CONT'D) Dolly, historically the best perfumes in the world, they're all laced with something nasty and foul.
ROSALYN ROSENFELD (CONT'D) It's true!
She puts it under Irv's nose as he talks to Carmine, he sniffs, closes his eyes, nods without even looking.
ROSALYN ROSENFELD (CONT'D) Irving loves them.
ROSALYN ROSENFELD (CONT'D) He can't get enough of them.
IRVING ROSENFELD I can't get enough.
ROSALYN ROSENFELD Carmine, sweet and sour.
ROSALYN ROSENFELD Rotten and delicious.
She leans across the table and puts them under Carmine's nose.
CARMINE POLITO Smells like flowers.
ROSALYN ROSENFELD Flowers, but with garbage.
CARMINE POLITO You know what that is for me?
CARMINE POLITO It's coriander for me.
ROSALYN ROSENFELD Irving loves it.
ROSALYN ROSENFELD He can't get enough.
ROSALYN ROSENFELD That's what hooks you.
ROSALYN ROSENFELD He always comes back for it.
IRVING ROSENFELD I can't stop.
ROSALYN ROSENFELD He's gonna say we have to talk business in five, four, three, two, one --
IRVING ROSENFELD Dolly, can me and the mayor talk business here?
Carmine and Dolly rush to grab Rosalyn; JULIUS, Carmine's steadfast AIDE, BLACK, 40, BIG SIDEBURNS, LOOSENED TIE and white shirtsleeves, BIG SMILE, helps.
ROSALYN ROSENFELD (CONT'D) No, don't do that it makes me look more drunk than I am!
ROSALYN ROSENFELD (CONT'D) I'm not this drunk.
ROSALYN ROSENFELD (CONT'D) Irving please don't make me go, I was just starting to have fun!
She WOBBLES INTO ARMS OF his WIFE Dolly, she and Carmine help guide Rosalyn out.
Todd Rundgren's "I Saw the Light" plays somewhere.
Edith dressed in tight Halston dress, hair flows huge all round her; walks with Richie, who is waiting in a white gray suit with a white disco collar outside the lapel, chains around his neck.
EDITH GREENSLY Didn't your fiance want to come out tonight?
RICHIE DIMASO Yeah, no, I don't know.
EDITH GREENSLY I'm sorry, we don't have to talk about it.
EDITH GREENSLY I was just teasing you.
RICHIE DIMASO Do you ever think, how did I end up here?
RICHIE DIMASO How did my life become this?
RICHIE DIMASO You ever think that?
RICHIE DIMASO And you wonder, am I ever gonna get to a better place or is this it?
RICHIE DIMASO You ever feel like that?
RICHIE DIMASO Edith stares, nods yes.
EDITH GREENSLY I do.
EDITH GREENSLY I definitely know that.
EDITH GREENSLY Edith nods puts a hand on his face.
EDITH GREENSLY (CONT'D) I'm sorry we don't have to go dancing.
EDITH GREENSLY (CONT'D) We can go have coffee or talk or something.
RICHIE DIMASO No, I need this.
RICHIE DIMASO Please, I need to go dancing with you.
RICHIE DIMASO Richie reaches down and squeezes her hand.
RICHIE DIMASO (CONT'D) Please.
103 Edith smiles.
103
EDITH GREENSLY OK baby, let's go dancing.
67. Richie and Edith DANCE AND DANCE AND SWEAT to Donna Summer's "I Feel Love" -- dance -- riding a high.
67. Edith EXCUSES HERSELF to go to bathroom -- breaks away through crowd -- leaves Richie on dance floor -- then
FROM BEHIND INTO A STALL -- SHE PUTS HER HANDS ON THE TOP OF THE STALL WALL AS RICHIE RUNS HIS HANDS UP HER LEGS FROM HER ANKLES AND UNDER HER DRESS - SHE LEANS HER ASS BACK INTO IT ARCHES HER BACK -- SUDDENLY RICHIE STOPS, throws himself back against the other stall wall, out of breath.
FROM BEHIND INTO A STALL -- SHE PUTS HER HANDS ON THE TOP OF THE STALL WALL AS RICHIE RUNS HIS HANDS UP HER LEGS FROM HER ANKLES AND UNDER HER DRESS - SHE LEANS HER ASS BACK INTO IT ARCHES HER BACK -- Edith LOOKS OVER HER SHOULDER --
RICHIE DIMASO I really fucking like you.
EDITH GREENSLY I like you too.
EDITH GREENSLY I want to live, alright.
EDITH GREENSLY For real.
EDITH GREENSLY No more fake shit.
EDITH GREENSLY Alright?
EDITH GREENSLY She get's real close to his face, almost about to kiss.
EDITH GREENSLY (CONT'D) We're going to wait until we decide to go for love Richie.
EDITH GREENSLY (CONT'D) For real.
EDITH GREENSLY (CONT'D) That's when we fuck.
EDITH GREENSLY (CONT'D) Not till then, ok?
GIRL OUTSIDE STALL Are you gonna fuck for real or get out of the stall for real?
EDITH GREENSLY No more fake shit.
RICHIE DIMASO No more fake shit.
EDITH GREENSLY No more fake shit!
GIRL OUTSIDE STALL Fuck me I gotta piss!
GIRL OUTSIDE STALL The girl outside the stall bangs on the door.
68. She holds his mouth in one hand and leans in and kisses him - they get lost --
EDITH GREENSLY Get out!
RICHIE DIMASO I want to be fucking real!
Irv and Carmine JOYOUSLY SING Tom Jones' "Delilah" WITH a RAUNCHOUSLY HAPPY GROUP OF locals.
INT. BARON'S BACK ROOM- CAMDEN SOCIAL CLUB - NIGHT - LATER Carmine puts down glass of bourbon as he addresses everyone emotionally as he looks at Irving.
CARMINE POLITO This guy right here, Irving Rosenfeld?
CARMINE POLITO You know what he's gonna do?
CARMINE POLITO He's gonna bring the Sheik to Atlantic City, where we can rebuild all those resorts there, put everybody back to work.
CARMINE POLITO Irving stares and is moved by this.
CARMINE POLITO Tears come to his eyes, he feels bad about it all suddenly.
CARMINE POLITO (CONT'D) He's gonna get this community -- he's gonna get this state -- back on its feet where it belongs.
CARMINE POLITO (CONT'D) Isn't that right?
CARMINE POLITO (CONT'D) He's gonna grow our tax base and create thousands and thousands of jobs for everyone.
CARMINE POLITO (CONT'D) You understand that?
CARMINE POLITO (CONT'D) You know what that means?
JULIUS To Irving.
GIRLS To Irving!
GIRLS Carmine sits down on the couch next to Irving.
CARMINE POLITO This guy right here.
CARMINE POLITO He's got a big heart.
IRVING ROSENFELD I'd just hate it if it didn't work out.
CARMINE POLITO What do you mean?
CARMINE POLITO Of course it's going to work out.
CARMINE POLITO Guys like you and me?
CARMINE POLITO We dream and we build.
CARMINE POLITO We never give up.
CARMINE POLITO We never quit.
Irv and Carmine eat breakfast.
CARMINE POLITO Can I ask you a question.
IRVING ROSENFELD Sure.
CARMINE POLITO Is the sheik black?
CARMINE POLITO Irving looks flummoxed.
IRVING ROSENFELD He's an Arab.
IRVING ROSENFELD They look at each other.
CARMINE POLITO That's black, isn't it?
CARMINE POLITO Irv isn't sure what to say.
IRVING ROSENFELD Why you asking?
CARMINE POLITO Maybe it's a dumb question, but I was just wondering -- I would like to arrange for the Sheik to see Camden.
CARMINE POLITO To see the people of Camden.
CARMINE POLITO The people I serve.
CARMINE POLITO The people I love.
CARMINE POLITO Who are mostly black and Puerto Rican.
CARMINE POLITO I really want him to see how good this is going to be for the community, how ready we are for this opportunity, and he can see how far his dollar will go.
CARMINE POLITO You know what I mean?
CARMINE POLITO What do you think?
IRVING ROSENFELD Yeah we can do that.
IRVING ROSENFELD He can see Camden.
CARMINE POLITO Hey, I got something I wanna give to you.
IRVING ROSENFELD For me?
CARMINE POLITO I got you a gift.
CARMINE POLITO Let's get out of here.
CARMINE POLITO The girls are going to kill us I'm sure.
They walk in the morning sun to Carmine's Lincoln where he opens the trunk and they stare at what is inside.
IRVING ROSENFELD What is it?
CARMINE POLITO It's a microwave.
CARMINE POLITO It heats up everything.
CARMINE POLITO Pasta, lasagna, meatballs, whatever.
IRVING ROSENFELD Really?
CARMINE POLITO It's science, yeah.
CARMINE POLITO That's how it heats up the food.
CARMINE POLITO It's scientific.
IRVING ROSENFELD And you specifically bought this science oven for me.
CARMINE POLITO Yes.
CARMINE POLITO A new friend.
CARMINE POLITO Irv is touched.
CARMINE POLITO He sees it is a sincere gift from Carmine, because Carmine likes him; not cynical in any way.
IRVING ROSENFELD Thank you.
CARMINE POLITO Don't put metal in it.
CARMINE POLITO Come on, let's get out of here.
RICHIE DIMASO I need a jet at Teeterboro.
RICHIE DIMASO I need a jet at Teeterboro for the sheik.
STODDARD THORSEN You don't need a jet.
STODDARD THORSEN Let him walk to the curb at JFK.
RICHIE DIMASO Stoddard, that's not how it works.
RICHIE DIMASO You got to do it from the feet up.
STODDARD THORSEN That doesn't mean anything.
STODDARD THORSEN What's that mean?
RICHIE DIMASO It means you gotta be committed!
RICHIE DIMASO It means you gotta be committed to something in your life, for Christ's sake.
RICHIE DIMASO I want a jet at Teterboro for the Sheik.
RICHIE DIMASO It can be a small jet.
RICHIE DIMASO It doesn't even have to take off, cause I know you're so worried about how much money the Bureau's gonna fucking spend.
RICHIE DIMASO It can take off and land on the tarmac, okay?
STODDARD THORSEN Alright, you can have a jet for an hour, but it takes off and lands at Teterboro.
RICHIE DIMASO I got the jet?
STODDARD THORSEN You got the jet.
110 Thank you.
110
Richie goes to walk out of Stoddard's office but stops at the door.
RICHIE DIMASO (CONT'D) So tell me the rest of the ice fishing story.
STODDARD THORSEN Where was I?
RICHIE DIMASO Your father woke you up, it was a blizzard, it was Lake Canoga.
RICHIE DIMASO Come on!
STODDARD THORSEN Okay, well, my brother and I were on the ice and my father came out of the house and I could see him coming.
STODDARD THORSEN He was holding a lantern, and it was in the blizzard and I knew he was gonna be angry.
STODDARD THORSEN So I went to intercept my father because I knew if he saw what my brother was doing he was going to kill him.
STODDARD THORSEN Richie cuts him off.
RICHIE DIMASO So you tried to protect your brother, but you couldn't and that's why you feel bad, because you're trying to protect me and you're worried about me.
RICHIE DIMASO Is that what the story's about?
RICHIE DIMASO About protection?
STODDARD THORSEN No, it's not about protection.
RICHIE DIMASO It's not about protection?
STODDARD THORSEN No.
RICHIE DIMASO Alright, fine.
RICHIE DIMASO Richie walks out the door.
Ros talks to herself carrying tin foil covered tray of lasagna.
ROSALYN ROSENFELD "Don't put metal in the science oven, don't put metal in the science oven, Rosalyn"...always treats me like a fucking child.
ROSALYN ROSENFELD I'll do whatever I want.
ROSALYN ROSENFELD She puts the tin foil lasagna into microwave.
ROSALYN ROSENFELD After a few moments it sparks, explodes into flames.
ROSALYN ROSENFELD DANNY RUNS IN.
DANNY Another fire!
ROSALYN ROSENFELD No, Danny, not that one!
ROSALYN ROSENFELD That one's empty!
ROSALYN ROSENFELD We gotta use the big one!
IRVING ROSENFELD I told you not to put metal in the science oven.
IRVING ROSENFELD Why did you do that for?
ROSALYN ROSENFELD Don't make such a big deal.
ROSALYN ROSENFELD Just get another one.
IRVING ROSENFELD I don't want another one.
IRVING ROSENFELD I want the one that Carmine gave me.
ROSALYN ROSENFELD "I want the one Carmine gave me!" Carmine, Carmine, why don't you just marry Carmine, get a little gold microwave and put it on a chain around your neck.
ROSALYN ROSENFELD You want to be more like Carmine?
ROSALYN ROSENFELD Why don't you build something like he does, instead of all your empty deals that are just like your fucking science oven.
ROSALYN ROSENFELD You know I read that it takes all of the nutrition out of our food.
ROSALYN ROSENFELD It's empty, just like your deals.
ROSALYN ROSENFELD Empty, empty!
IRVING ROSENFELD That's bullshit.
ROSALYN ROSENFELD It's not bullshit.
ROSALYN ROSENFELD I read it in an article.
ROSALYN ROSENFELD Look, by Paul Brodeur.
ROSALYN ROSENFELD Bring something into this house that's gonna take all the nutrition out of our food and then light our house on fire?
ROSALYN ROSENFELD Thank God for me.
ROSALYN ROSENFELD Ros stares defiantly, clicks her nails on the counter.
ROSALYN ROSENFELD PRE- LAP JET ROAR, IRVING STARES AT ROS and BURNED OVEN and looks at the magazine article.
JET ROAR LANDING.
A small airport.
Irv stands alone, staring at Edith and Richie kissing.
Richie, in long full length fleece lined suede coat, walks over towards where Carmine stands.
IRVING ROSENFELD I don't think you should come to Carmine's party tonight.
IRVING ROSENFELD You look beautiful by the way.
EDITH GREENSLY Don't look at me.
EDITH GREENSLY Don't look at my legs, don't look at my hair, don't smell my hair, don't ask me how I am, don't talk to me outside of these roles, 'cause we're done.
IRVING ROSENFELD What are you doing?
IRVING ROSENFELD Get under the umbrella.
IRVING ROSENFELD It's just that Carmine wants Rosalyn to come.
EDITH GREENSLY I don't care.
EDITH GREENSLY You weren't listening.
EDITH GREENSLY I don't care if Rosalyn comes.
EDITH GREENSLY Just do your job, okay?
EDITH GREENSLY You're nothing to me until you're everything.
EDITH GREENSLY I'm not Rosalyn.
EDITH GREENSLY I'm not gonna put up with that shit.
EDITH GREENSLY THEY ARRIVE AT Richie as the JET arrives on the tarmac.
RICHIE DIMASO Now that's a fucking jet right?
IRVING ROSENFELD It's good.
RICHIE DIMASO That's the kinda moves you need to make.
They walk towards the Jet and walk on leaving Carmine and Edith waiting outside.
Irv and Richie step aboard to find FBI AGENT PACO HERNANDEZ putting on a regal looking white Arab keffyeh headdress and robe -- he looks noble.
TWO AGENTS posing as body guards.
RICHIE DIMASO Paco, Richie Dimaso, good to meet you in person [shakes Paco's hand] - this is Irving Rosenfeld.
Irv nods to Paco and the other agents.
PACO HERNANDEZ Paco Hernandez.
PACO HERNANDEZ Nice to meet you.
IRVING ROSENFELD Paco?
IRVING ROSENFELD He's--wait, he's not a real Arab.
PACO HERNANDEZ No.
PACO HERNANDEZ I'm Mexican.
PACO HERNANDEZ From Tuscon.
IRVING ROSENFELD Wait, where's my guy?
IRVING ROSENFELD Where's Al from Queens?
RICHIE DIMASO Who?
IRVING ROSENFELD My friend from Queens.
IRVING ROSENFELD Where is he?
IRVING ROSENFELD What are you doing?
RICHIE DIMASO I gotta hire an F.B.I. guy.
IRVING ROSENFELD What are you-- (to Paco) You speak any Arabic?
PACO HERNANDEZ Yeah.
PACO HERNANDEZ Abdullah Ahmed.
IRVING ROSENFELD That's it?
IRVING ROSENFELD That's all you got?
PACO HERNANDEZ No, I have a couple phrases.
Irving isn't sure, looks Paco up and down.
IRVING ROSENFELD (to Richie) From the feet up, you motherfucker.
IRVING ROSENFELD What are you doing?
IRVING ROSENFELD (to Paco) Act normal.
IRVING ROSENFELD That's it.
IRVING ROSENFELD Like you can barely understand English.
IRVING ROSENFELD You can't speak it.
IRVING ROSENFELD You say as little as possible.
IRVING ROSENFELD You follow my lead.
IRVING ROSENFELD Alright?
PACO HERNANDEZ (to Richie) Who's running this?
PACO HERNANDEZ I thought you were running it.
RICHIE DIMASO I am running this but you've gotta listen to him.
RICHIE DIMASO He's the guy with the vision.
IRVING ROSENFELD I've got the vision?
IRVING ROSENFELD You know what vision I had?
IRVING ROSENFELD You just kissing my girl outside.
IRVING ROSENFELD That's what vision I had.
RICHIE DIMASO I thought you guys broke up.
RICHIE DIMASO I'm giving you a compliment.
PACO HERNANDEZ What's going on?
RICHIE DIMASO Don't worry about it.
Irving takes a expensive looking ceremonial knife out of his jacket pocket and holds it out to Paco.
IRVING ROSENFELD You got a knife.
IRVING ROSENFELD This is for the Mayor.
IRVING ROSENFELD You've got to present it to him.
IRVING ROSENFELD Look me in the eye.
IRVING ROSENFELD This means a lot to you.
IRVING ROSENFELD Right?
IRVING ROSENFELD That knife.
IRVING ROSENFELD Play it.
IRVING ROSENFELD You present it.
IRVING ROSENFELD "Friendship for life," alright?
IRVING ROSENFELD You gotta feel it.
IRVING ROSENFELD Sacred.
IRVING ROSENFELD Can you do it?
PACO HERNANDEZ Right.
PACO HERNANDEZ Sacred.
IRVING ROSENFELD You gotta sell it.
RICHIE DIMASO Sell it.
IRVING ROSENFELD If you believe it's sacred, it's sacred.
RICHIE DIMASO Listen to what he's saying.
IRVING ROSENFELD Can you do it?
RICHIE DIMASO It's the details.
RICHIE DIMASO That's what makes this guy a genius.
IRVING ROSENFELD Again?
IRVING ROSENFELD You compliment me again.
IRVING ROSENFELD What is this, rubbing salt in the wound?
Irving stares incredulously.
RICHIE DIMASO I'm complimenting you.
RICHIE DIMASO (to Paco) Any other questions?
PACO HERNANDEZ Yeah, I think the name of this operation is offensive.
RICHIE DIMASO What?
PACO HERNANDEZ Abscam.
PACO HERNANDEZ "Arab Scam?" It's racist.
IRVING ROSENFELD Are you fucking kidding?
IRVING ROSENFELD What do you care?
IRVING ROSENFELD You're Mexican.
ELO's "10538 Overture" kicks on.
Irv and Richie exit the plane walking slightly behind the "sheik" and his "bodyguards" - the sheik in the front.
The Sheik hands the ceremonial knife to Carmine and bows his head --
CARMINE POLITO Hello Sheik, my friend.
CARMINE POLITO Welcome.
CARMINE POLITO On behalf of the great state of New Jersey I want to welcome you to New Jersey.
CARMINE POLITO I know that was redundant.
CARMINE POLITO I'm sorry.
CARMINE POLITO I'm just very nervous.
116 Carmine takes the knife and looks to the others excitedly.
116
CARMINE POLITO (CONT'D) We have a great party planned for you this evening.
ROSALYN ROSENFELD But what are you talking about, I can't go?
ROSALYN ROSENFELD I just did my hair and makeup and everything!
IRVING ROSENFELD The Sheik's very particular.
IRVING ROSENFELD It's international cultural protocol.
ROSALYN ROSENFELD International protocol?
ROSALYN ROSENFELD What the fuck are you talking about?
IRVING ROSENFELD Do not answer that!
ROSALYN ROSENFELD Hello -- Robert Spencer?
ROSALYN ROSENFELD I don't know a Robert Spencer.
ROSALYN ROSENFELD What do you want?
IRVING ROSENFELD Give it to me.
ROSALYN ROSENFELD Who is that?
IRVING ROSENFELD Look, I told you, for God's sake, I told you not to call here.
ROSALYN ROSENFELD What is that about?
RICHIE DIMASO Two more federal agents tonight,
Ros leaves the room.
IRVING ROSENFELD No way.
RICHIE DIMASO Yes.
RICHIE DIMASO They're bodyguards for the Sheik.
IRVING ROSENFELD That's too many people for me to control, no.
RICHIE DIMASO Look.
RICHIE DIMASO I'm in charge here, alright?
RICHIE DIMASO Just do it.
IRVING ROSENFELD Rosalyn, get off the extension!
ROSALYN ROSENFELD I'm not on it!
But she was on it.
She heard.
IRVING ROSENFELD Look, don't call here again, alright?
IRVING ROSENFELD Don't call at home.
RICHIE DIMASO Alright?
RICHIE DIMASO Good night.
He HANGS UP and walks into the kitchen.
Rosalyn looks at him.
ROSALYN ROSENFELD Federal agents?
IRVING ROSENFELD It's bodyguards for the visiting dignitary, that's all.
ROSALYN ROSENFELD What is it, an I.R.S. thing?
ROSALYN ROSENFELD Like a tax investigation?
IRVING ROSENFELD Why you gotta say that?
IRVING ROSENFELD I mean, that's why I can't invite you.
IRVING ROSENFELD It's too complicated.
IRVING ROSENFELD Listen, come on.
ROSALYN ROSENFELD Are you in trouble?
IRVING ROSENFELD Look, stop being so nosy.
Irving opens the fridge which is a mess.
IRVING ROSENFELD (CONT'D) Look at this shit.
ROSALYN ROSENFELD I'm only nosy cause you never tell me anything.
IRVING ROSENFELD Can we clean up this fridge?
IRVING ROSENFELD I mean, what are you causing trouble for all the time?
ROSALYN ROSENFELD HEL-LO- Oh, hi, Carmine.
ROSALYN ROSENFELD We were just talking about you.
ROSALYN ROSENFELD (CONT'D) Irving's being a mean, boring man saying that he doesn't want me to come tonight.
CARMINE POLITO (on phone)Tell him he's crazy!
ROSALYN ROSENFELD Well, I agree.
ROSALYN ROSENFELD Want to tell him yourself?
IRVING ROSENFELD Gimme the phone, come on.
CARMINE POLITO It wouldn't be a party without you!
ROSALYN ROSENFELD Can you imagine?
ROSALYN ROSENFELD Tell him yourself.
She hands the phone to a very exasperated, anxious, Irv.
IRVING ROSENFELD (into telephone) Hey, Carmie.
CARMINE POLITO Irving, you're crazy!
CARMINE POLITO Your wife is coming, you kidding me?
CARMINE POLITO She's the life of the party!
CARMINE POLITO Everybody loves her.
ROSALYN ROSENFELD I'm the life of the party!
IRVING ROSENFELD Look, you know what she's like.
IRVING ROSENFELD She's unpredictable.
IRVING ROSENFELD She's just always --
ROSALYN ROSENFELD Hey, don't talk about me like that!
ROSALYN ROSENFELD What's Carmine saying?
IRVING ROSENFELD I can't hear what he's saying.
CARMINE POLITO Listen, Irving, it's very important that she come, you understand?
ROSALYN ROSENFELD Carmine loves me.
CARMINE POLITO This is a really big night for us, you understand?
CARMINE POLITO Come on, you gotta bring your wife.
CARMINE POLITO And Dolly's got somethin' special for her.
Dolly is getting dressed for the party in the background.
DOLLY POLITO Tell her I got the nail polish for her.
CARMINE POLITO See?
CARMINE POLITO Listen!
DOLLY POLITO (raising her voice to phone) I got your nail polish for you, sweetie!
CARMINE POLITO You see?
CARMINE POLITO Somethin' special for you.
CARMINE POLITO What is it?
CARMINE POLITO Tell me.
CARMINE POLITO I mean,
CARMINE POLITO What is it, you got a girlfriend coming?
CARMINE POLITO Come on, I thought we were friends.
CARMINE POLITO You're not gonna tell me you got a girlfriend?
CARMINE POLITO This is ridiculous.
IRVING ROSENFELD No, it's just Rosalyn's unpredictable.
CARMINE POLITO Look, we're gonna handle this like men, you understand?
CARMINE POLITO You're bringing your wife.
CARMINE POLITO We're gonna have a good time.
CARMINE POLITO That's an order from the Mayor.
CARMINE POLITO Good-bye.
IRVING ROSENFELD (to Rosalyn) Alright, you happy?
IRVING ROSENFELD Go get ready.
Irv hangs up and exits the kitchen.
ROSALYN ROSENFELD Yes, I am happy.
Elton John's "Goodbye Yellow Brick Road" plays on the soundtrack as Irv drives: tinted glasses, large comb over, blue crushed velvet suit, dark tie -- PAN TO:
VISOR MIRROR -- WHERE Rosalyn APPLIES MASCARA --
Elton John continues as Carmine LIGHTS A CIGARETTE in a two- toned GRAY AND BLACK TUXEDO, at the center of a haphazard red carpet situation in front of a has-been beach resort -- large old movie premiere spotlights rotate onto the facade in an assorted CROWD OF LOCALS some dressed up -
JULIUS, CARMINE, TITO, MELORA (Carmine's STEADFAST AIDES) son DOMINIC, daughter LUCILLE, wife Dolly, assorted COPS, FIREMEN IN FORMAL UNIFORMS WHITE GLOVES, UNION GUYS in suits, fringe the area.
JULIUS, CARMINE, TITO, MELORA (Carmine's STEADFAST AIDES) Carmine 's family is dressed up.
SHRIEKS IN ECSTACY. Greets everyone.
JAMS WITH GRINDING SOUND, LAMP EXPLODES IN SMOKE -- THROUGH THE SMOKE FROM THE FIRE STEPS: Richie IN A WHITE SUIT, Edith stunning SILVER METALLIC Halston dress, WHITE FUR
ROSALYN ROSENFELD I know who you are.
85. Irv tries to turn Rosalyn away, but she keeps turning back giving Edith the hairy eyeball, as Edith gives it right back.
ROSALYN ROSENFELD (CONT'D) I know who that is Irving.
ROSALYN ROSENFELD (CONT'D) Off to the side, Richie steels himself with bump of cocaine before walking inside the old resort, his eyes dilate.
The entourage walks through the ornate lobby as Edith and Rosalyn continue to eyeball each other with Irv uncomfortably in the middle as Carmine ENTHUSIASTICALLY CONTINUES HIS
CARMINE POLITO So this is the lobby.
CARMINE POLITO Now mind you, a week ago this place was a mess, but what existed was this plasterwork.
CARMINE POLITO Look at the detail.
CARMINE POLITO This is beautiful.
CARMINE POLITO My sons are craftsmen.
CARMINE POLITO (to son, Dominic) Please, tell them what you did.
DOLLY POLITO Tell them everything you know.
DOLLY POLITO The trompe l'oeil.
DOMINIC POLITO Birds, sky, clouds, wood.
DOMINIC POLITO Trompe l'oeil -- "Trick of the eye."
CARMINE POLITO We can restore all of this, you see?
CARMINE POLITO You save 50 million -- look at me -- fifty million right off the bat -- I waive the law I helped write.
CARMINE POLITO It said casino construction must be ground up new, we don't do new.
CARMINE POLITO We renovate.
DOLLY POLITO We don't do new.
DOLLY POLITO We renovate.
DOLLY POLITO Carmine leads all of them through the very crowded lobby as he talks.
DOLLY POLITO Irving listens intently, moved.
200 PEOPLE ARE GATHERED around blackjack, roulette, and craps tables, playing and having a good time.
CARMINE POLITO We put in some temporary fun -- some gaming tables, some play money for people to have a good time.
CARMINE POLITO For charity -- the Boys and Girls Club and some arts programs.
CARMINE POLITO Rosalyn walking with Irving, continues to stare daggers at Edith, who stays close to Richie.
CARMINE POLITO Carmine, Julius, Melora, CONTINUE TO LEAD EVERYONE INTO
Carmine continues to walk --
CARMINE POLITO This is the Ocean Room --
CARMINE POLITO He pushes open double upholstered old doors --
THEY ENTER THE LARGE CROWDED YET INTIMATE BEMELMANS STYLE BAR The bar -- LIKE THE BEMELMANS BAR AT THE CARLYLE HOTEL IN
ANOTHER SMALLER BAR ON THE FAR SIDE OF THE ROOM --- Carmine pauses to stare at the MEN AT THE FAR BAR -- FIVE MEN
IN SUITS, 40 TO 60, SLIGHTLY MOB-LOOKING. AS Irv IS PULLED ASIDE CONFIDENTIALLY BY Carmine -- Richie AND Edith WATCH -- Rosalyn STANDS TO THE SIDE -- Carmine puts his arm around Irv's shoulders --
CARMINE POLITO There are some gentlemen over there at the bar.
CARMINE POLITO That's a hundred and thirty years sitting there -- that's how much time's between them.
CARMINE POLITO They run the biggest casinos in the United States.
CARMINE POLITO We have to work with them.
IRVING ROSENFELD Right.
CARMINE POLITO The good news is they know how it's done.
CARMINE POLITO They get it done.
CARMINE POLITO You don't have to worry.
CARMINE POLITO Everyone makes their money.
IRVING ROSENFELD You mean the Mob?
CARMINE POLITO Yes, but they're businessmen, okay?
CARMINE POLITO Now, spend as much or as little time with them as you like, but we do have to deal with them.
CARMINE POLITO All we've got to do is go say hello.
CARMINE POLITO We just gotta say hi, that's all.
Edith looks on, calm, as Richie -- WILD EYED WITH COCAINE AND
IRVING ROSENFELD Carmine, maybe -- I'm not sure that's such a good idea.
IRVING ROSENFELD We gotta confer before we talk to these guys.
RICHIE DIMASO Confer?
RICHIE DIMASO What is there to confer about?
RICHIE DIMASO They're casino guys.
CARMINE POLITO They are businessmen.
RICHIE DIMASO We came all this way, Irving.
RICHIE DIMASO We should be here.
RICHIE DIMASO What's everybody scared of?
RICHIE DIMASO There's nothing to be scared of.
Richie stares down Irv, Edith pulls Richie back -- Rosalyn is starting to go down a SPIRAL OF DEPRESSION as she looks increasingly uncomfortable.
ROSALYN ROSENFELD Those are the guys you're all scared of?
ROSALYN ROSENFELD Those guys over there?
ROSALYN ROSENFELD They don't scare me.
She glares at Edith and Irv and pivots to walk to the bar.
IRVING ROSENFELD Rosalyn!
But she's already on her way over to the MAFIA MEN at the bar who GREET HER WARMLY as Irv, Edith, Richie, and Carmine watch.
RICHIE DIMASO I love this!
Rosalyn walks up to PETE MUSANE, CHARISMATIC, 30 and sits down in between all the Mafia guys..
THE OTHER THREE SALT AND PEPPER MAFIA GUYS LAUGH AND TALK WITH Rosalyn - who gulps a glass of PROSECCO and IS REFILLED BY PETE MUSANE.
ROSALYN ROSENFELD Hi.
ROSALYN ROSENFELD Can I sit here?
Carmine whispers to Irv as he watches Rosalyn talk to the Mafia guys.
CARMINE POLITO Irving, this is not a good idea.
ROSALYN ROSENFELD How you guys doing?
ROSALYN ROSENFELD Everybody over there is really scared of you guys, you know that?
She knocks back the prosecco.
She seems relieved.
Dolly ushers her kids to the door.
DOLLY POLITO Kids, I want you to go up and get some pizza and soda, please.
Irving and Edith watch in horror at Rosalyn.
EDITH GREENSLY It's a disaster.
ROSALYN ROSENFELD I think they have this room all wrong.
PETE MUSANE Yeah?
PETE MUSANE What would you do?
ROSALYN ROSENFELD I would do it in all black and gold and I would do this bar like a big, warm golden mirror.
DICK HELSING Sounds beautiful.
ROSALYN ROSENFELD Thank you.
Rosalyn's smitten by the mobsters.
PETE MUSANE But you expect that from her because she's so beautiful --
ROSALYN ROSENFELD Oh stop.
DICK HELSING Gorgeous.
PETE MUSANE I love her hair, so I know I'm gonna love how she'd do the room --
He touches the front of her huge Farrah overhang bangs.
Richie, Irving, Carmine, and the Sheik walk up to them.
RICHIE DIMASO How do you do?
PETE MUSANE I'm sorry is she your wife?
IRVING ROSENFELD No, she's my wife.
IRVING ROSENFELD She's my wife.
CARMINE POLITO Look at these fine gentleman.
PETE MUSANE Carmine, there you are.
CARMINE POLITO How you doing?
Irving takes the glass of prosecco out of Rosalyn's hand and puts it on table.
PETE MUSANE AND GUYS Ohhhh, heyyyyy!
PETE MUSANE AND GUYS Come onnn!
ROSALYN It's because he's a party pooper.
ROSALYN He's so boring.
Irving stares fuming at Rosalyn and the guys, he nods and forces a smile good naturedly as they put prosecco glass in his hand.
He knows how to fake it.
PETE MUSANE You have a very beautiful wife.
GUYS Salud.
THEY ALL LAUGH.
RICHIE GUIDES SHEIK with ONE BODY GUARD.
RICHIE DIMASO May I present Sheik Abdullah, gentlemen, from Abu Dhabi.
RICHIE DIMASO Sheik, these men are professionals, they run the best casinos in the United States.
The Sheik acknowledges them with a nod.
Irv is extremely uncomfortable.
PETE MUSANE Mr. Sheik, as a sign of our seriousness, Mr. Tallegio came from Miami to meet you tonight.
CARMINE POLITO Mr. Tallegio?
CARMINE POLITO Why didn't you tell me Mr. Tallegio was here?
PETE MUSANE He's in the back room.
IRVING ROSENFELD It's a sign of disrespect to do business on the first meeting.
RICHIE DIMASO That's not true.
RICHIE DIMASO I don't know what your talking about.
RICHIE DIMASO (to Musane) He's got it all wrong.
DICK HELSING Well, don't leave him back there in the back room waiting.
DICK HELSING Come on, let's go.
Rosalyn reaches to have her glass refilled by Dick Helsing when one of the other guys NUDGES her hip in her tight dress and she drops into Pete Musane's lap.
ROSALYN ROSENFELD Hey Irving, I'm going to be having fun.
ROSALYN ROSENFELD Maybe it will be contagious.
ROSALYN ROSENFELD Irving turns and heads with dread towards the back door with Carmine, Richie, and the Sheik.
ROSALYN ROSENFELD Sydney, worried about Rosalyn with Musane, decides to hang back.
VICTOR TELLEGIO Carmine!
IRVING ROSENFELD (V.O.) Victor Tellegio was from Miami.
IRVING ROSENFELD (V.O.) He was Meyer Lansky's right-hand man.
IRVING ROSENFELD (V.O.) In his prior reputation as an enforcer from twenty years ago, he was known to never bury a body because he felt it sent a stronger message to leave it in the street.
IRVING ROSENFELD (V.O.) This is the guy we now had to deal with.
RESUME PUSH IN ON TELLEGIO AS A COUPLE OF BUSBOYS SET UP AN IMPROMPTU TABLE AND CHAIRS.
RESUME PUSH IN ON TELLEGIO AS A COUPLE OF BUSBOYS SET UP AN Carmine greets him.
CARMINE POLITO You sure you don't want to go into the Ocean Bar?
CARMINE POLITO It's really, it's beautiful in there.
VICTOR TELLEGIO I'm very happy I don't have to go there.
VICTOR TELLEGIO I like it here.
VICTOR TELLEGIO There's an exit.
VICTOR TELLEGIO I'm like a ghost.
VICTOR TELLEGIO Nobody knows I'm here.
Busboys whip open a white table cloth for the table.
Everyone sits down.
Tellegio looks at the Sheik, then over to Richie.
VICTOR TELLEGIO (CONT'D) Tell him I speak for our friends in Florida.
VICTOR TELLEGIO (CONT'D) We're very excited.
VICTOR TELLEGIO (CONT'D) It's been our lifelong dream to build casino resorts on the East Coast.
Richie pretends to translate in the Sheik's ear.
VICTOR TELLEGIO (CONT'D) You told him that?
VICTOR TELLEGIO (CONT'D) They didn't want the Jews to make money, they didn't want the Italians to make money, definitely don't want the blacks to make money.
VICTOR TELLEGIO (CONT'D) After the oil embargo -- the gasoline crisis -- the hijackings, the Olympics, they don't want to see Arabs make money, trust me, not on our soil.
VICTOR TELLEGIO (CONT'D) You can tell him this in your own way: I've been in the casino business forty years.
VICTOR TELLEGIO (CONT'D) It's scrutinized more carefully than any other business.
VICTOR TELLEGIO (CONT'D) Carmine made this legal, but we must be careful or they'll take it away.
CARMINE POLITO So, Mister Tellegio, how do you think we should approach this?
CARMINE POLITO What do you want to do?
VICTOR TELLEGIO If you want to get the gaming license and keep it we have to make our principal investor here, the Sheik, an American citizen.
Irving and Richie both look at Victor intensely not sure where this is going.
CARMINE POLITO To expedite citizenship -- well, that requires very special treatment.
VICTOR TELLEGIO You would know the right people to do that, Carmine.
RICHIE DIMASO Carmine knows everybody.
IRVING ROSENFELD What are we talking about?
CARMINE POLITO U.S.
CARMINE POLITO Senators.
CARMINE POLITO Congressmen.
RICHIE DIMASO Wow, that's fantastic.
IRVING ROSENFELD I say stay away from that.
IRVING ROSENFELD That's bad.
IRVING ROSENFELD That's trouble.
IRVING ROSENFELD No, that's not good.
RICHIE DIMASO Irving please.
IRVING ROSENFELD That's trouble.
VICTOR TELLEGIO Who is this guy?
VICTOR TELLEGIO (to Irving) What are you, a farmer?
Richie and Tellegio both laugh.
CARMINE POLITO Mr. Tellegio, I'm sorry, this is Irving.
CARMINE POLITO New York businessman.
CARMINE POLITO Irving Rosenfeld.
VICTOR TELLEGIO Irving, Irving.
VICTOR TELLEGIO What's the matter, Irving?
VICTOR TELLEGIO What's the problem?
IRVING ROSENFELD Nothing.
IRVING ROSENFELD No problem.
VICTOR TELLEGIO Don't get your balls in an uproar.
VICTOR TELLEGIO Everything's fine, everything's good.
VICTOR TELLEGIO It's all good.
VICTOR TELLEGIO It's all good.
VICTOR TELLEGIO I just hope the other part of this is all good.
VICTOR TELLEGIO And real.
VICTOR TELLEGIO Because we're real.
VICTOR TELLEGIO You know that.
VICTOR TELLEGIO You deal with us.
VICTOR TELLEGIO We're a real organization.
VICTOR TELLEGIO We deal with you, we don't know what we're dealing with.
Everyone stares increasingly tense at Tellegio in silence.
This could go wrong at any minute.
Tellegio looks over to Richie and points to the Sheik.
Irving watches in horror as --
VICTOR TALLEGIO Where's he from?
RICHIE DIMASO Abu Dhabi.
VICTOR TELLEGIO Oh, he's from the Emirates.
RICHIE DIMASO Yeah.
VICTOR TELLEGIO (Can I count on you?
VICTOR TELLEGIO You gotta be honest about this.
VICTOR TELLEGIO Do you understand me?
VICTOR TELLEGIO Good means good.
VICTOR TELLEGIO No bullshit.)
VICTOR TELLEGIO (CONT'D) (Did you hear what I said?
VICTOR TELLEGIO (CONT'D) Do you want me to repeat it?)
Irving looks ill, as does everyone else at the table.
VICTOR TELLEGIO (CONT'D) (What do you think now?
VICTOR TELLEGIO (CONT'D) Tell me.
VICTOR TELLEGIO (CONT'D) Tell me.)
RICHIE DIMASO Uh, I think, I think what he's --
VICTOR TELLEGIO No, let him speak for himself.
Sheik swallows hard and looks to Richie.
It's a very tense moment for everyone at the table.
Tellegio stares.
Everyone hangs on this.
Irving and Richie share a look -- what is he doing?
A DRUNK, AL KOWALSKI, a working man, friend of the Mayor BARRELS INTO INTO THE TABLE, spilling drinks.
Tellegio's guys jump in and grab him and start to pull him away.
CARMINE POLITO No, I know him.
AL KOWALSKI You guys are way too serious for a party!(to Tellegio) Hey, what are you drinking?
AL KOWALSKI You got a drink?
CARMINE We're in a very serious meeting.
CARMINE (to Tellegio) I apologize.
AL KALOWSKI I understand, you're in conference.
AL KALOWSKI You gotta come with me now.
AL KALOWSKI You got a speech to give.
AL KALOWSKI Everyone's waiting for you.
CARMINE POLITO Al, I'll be right behind you, okay?
CARMINE POLITO Trust me.
Paco Hernandez/Sheik stands up and reaches over to Tellegio to shake his hand.
Irving panics.
THE MENACING DEEP BASS
SHEIK ABDULLAH It is great doing business with you.
SHEIK ABDULLAH The investment is real.
SHEIK ABDULLAH It was a pleasure to meet you.
Irving exhales in relief that Paco managed to say anything passable in Arabic.
IRVING ROSENFELD (V.O.) What are the odds of an Italian guy from Miami knowing Arabic?
IRVING ROSENFELD (V.O.) But it turns out he's got casino investments in the Mideast and he spent two years learning it to keep the upper hand.
Victor leans over to talk to Carmine.
VICTOR TELLEGIO Listen to me carefully.
VICTOR TELLEGIO If you're real, you put ten million in the bank of our choice in the next two weeks.
Carmine nods.
VICTOR TELLEGIO (CONT'D) Carmine, listen to me carefully, if you're real, you put ten million in the bank of our choice in the next two weeks or not only will the Sheik feel insulted, but our friends in Florida will feel deeply disrespected and so will I.
Irving looks at Victor, who stares back at him.
This is bad.
EDITH GREENSLY Rosalyn, you need to come with me alright?
ROSALYN ROSENFELD I don't need to come with you.
EDITH GREENSLY You need to come with me.
EDITH GREENSLY This needs to stop.
EDITH GREENSLY Come on.
ROSALYN ROSENFELD Oh, you think I should come with you?
EDITH GREENSLY Yeah, you need to come with me right now.
Rosalyn takes her wrist out of Sydney's grasp.
ROSALYN ROSENFELD Why don't you get your fucking hands off me, you fucking whore!
PETE MUSANE Hey!
ROSALYN ROSENFELD You're a whore.
ROSALYN ROSENFELD (to everyone) This is my husband's whore!
EDITH GREENSLY That's real nice.
DOLLY POLITO We're not going to do this in the Ocean Room tonight.
DOLLY POLITO Not tonight.
DOLLY POLITO Please.
ROSALYN ROSENFELD This is my husbands whore!
Dolly escorts Edith over to one side of the room away from Rosalyn.
DOLLY POLITO You stay over here with me.
DOLLY POLITO Everybody just calm down.
DOLLY POLITO I don't know what's going on.
Pete looks over to Rosalyn.
PETE MUSANE You alright?
PETE MUSANE Take it easy.
PETE MUSANE These things happen.
PETE MUSANE Whatever's meant to be will be.
Rosalyn smiles at Pete.
ROSALYN ROSENFELD That's what I always say.
PETE MUSANE You say that?
ROSALYN ROSENFELD Yeah.
PETE MUSANE See?
PETE MUSANE Kindred spirits.
ROSALYN ROSENFELD Whatever's meant to be will be.
PETE MUSANE Whatever's meant to be will be.
Rosalyn looks in mirror: sadness, anger, fear.
Edith rushes in.
EDITH GREENSLY What the hell do you think you're doing?
ROSALYN ROSENFELD What the hell do I think I'm doing?!
ROSALYN ROSENFELD What the fuck do you think you're doing?
ROSALYN ROSENFELD You really gonna come in here and judge me for flirting with somebody after you've been fucking my husband for how many years?!
EDITH GREENSLY You don't have any fucking clue what's going on!
EDITH GREENSLY Rosalyn holds her hand, with wedding ring to Sydney's face.
ROSALYN ROSENFELD I got a ring on my finger.
ROSALYN ROSENFELD We have a child together.
EDITH GREENSLY He doesn't love you Rosalyn he loves me.
EDITH GREENSLY And you know it and I know it and he knows it.
EDITH GREENSLY And it might be done now, but it was beautiful and it was real.
ROSALYN ROSENFELD Stop.
EDITH GREENSLY And we loved each other.
ROSALYN ROSENFELD Shut up.
Rosalyn starts to tear up.
EDITH GREENSLY You scare him, and you manipulate him, and you use your son!
ROSALYN ROSENFELD Well, he must like it on some level.
ROSALYN ROSENFELD He must want it because he keeps coming back for it.
ROSALYN ROSENFELD It's like that perfume that you love that you can't stop smelling, even when there's something sour in it.
ROSALYN ROSENFELD You can't get enough of it.
ROSALYN ROSENFELD But guess what, he's never gonna leave me.
ROSALYN ROSENFELD He's always going to want me, and I will make you so sorry, Edith.
ROSALYN ROSENFELD I will make you so sorry for what you've done to my family, mark my words.
EDITH GREENSLY That is fucked up!
EDITH GREENSLY I would never say anything that fucked up to anybody, but you do because you're gross inside, you're so fucked up and gross.
ROSALYN ROSENFELD Oh, I'm gross inside?
EDITH GREENSLY Yeah.
ROSALYN ROSENFELD Maybe you're gross inside, with robbing people and all that shit that you do?
ROSALYN ROSENFELD Maybe we're both gross inside, that's what Irving loves about us.
ROSALYN ROSENFELD At least he's consistent with his women.
ROSALYN ROSENFELD You know, sometimes in life all you have are fucked up, poisonous choices.
Rosalyn reaches over, grabs Sydney's face and kisses her.
100. Rosalyn laughs a toxic, tough front dark laugh and walks out.
THE BEE GEES "HOW CAN YOU MEND A BROKEN HEART?" STARTS. Sydney looks into the mirror and wipes the lipstick off her lips as Rosalyn storms out of the powder room.
EDITH GREENSLY We need to talk!
EDITH GREENSLY This is serious.
AL KALOWSKI Ladies and gentlemen, your friend, the working man's friend, my friend, Mayor Carmine Polito!
AL KALOWSKI ON STAGE: Carmine TAKES MIC
AL KALOWSKI Irving stands off to the side of the stage as his world closes in around him.
AL KALOWSKI Pulls his heart pills out of his pocket and takes one.
AL KALOWSKI Sydney sees this as she stands nearby with Richie.
AL KALOWSKI Irv, Edith, Richie watch near stage, jostled.
AL KALOWSKI Rosalyn enters the ball room looking disheveled as she is guided by Pete Musane looks to stage.
CARMINE POLITO Hello, Camden!
CARMINE POLITO Hello, New Jersey!
CARMINE POLITO Hello, Atlantic City!
CARMINE POLITO [CROWD ROARS] A lot of my friends been out of work [CROWD WHISTLES - BOOS] A lot of good hard working families just wanna WORK AND LIVE.
CARMINE POLITO (crowd CHEERS) There's no money nowhere.
CARMINE POLITO You gotta be kidding me!
CARMINE POLITO -- don't they remember who built this country?
CARMINE POLITO [CHEERS] The one thing we can all agree about in the State of New Jersey is that we never, ever give up!
CARMINE POLITO Do we?
CARMINE POLITO Carmine dominates the crowd and you can see the emotion in his face as he says this.
CARMINE POLITO He raises his glass to the crowd.
CARMINE POLITO (CONT'D) Please, raise a glass with me to a new era that begins tonight.
CARMINE POLITO (CONT'D) From me and my family, we thank you.
CARMINE POLITO (CONT'D) For all the hard work that you've given us in the community.
CARMINE POLITO (CONT'D) Look what you've done.
CARMINE POLITO (CONT'D) This is beautiful!
CARMINE POLITO (CONT'D) Thank you!
CARMINE POLITO (CONT'D) Crowd ROARS WILDLY.
CARMINE POLITO (CONT'D) Irv watches, MOVED AND DESTROYED.
Irving walks in with his keys, same clothes from night before, as ocean sounds continue, TAKES A GUN FROM THE SAFE, and he stands looking lost and lonely, he turns on the electric dry cleaning rack, where he and SYDNEY STOOD TOGETHER, IN LOVE.
He looks heartsick.
HE STEPS INSIDE THE
BANG BANG BANG -- Richie POUNDS ON SYDNEY'S DOOR -- SYDNEY,
RICHIE DIMASO Can I use your phone?
135 INT.
SYDNEY'S APARTMENT DAY - AS SHE WATCHES -- HE paces 135 intense, phone in hand, SHIRT SLEEVES, a mess.
HE DIALS.
RICHIE DIMASO (CONT'D) Last night was insane.
RICHIE DIMASO (CONT'D) I got it all figured out.
STODDARD THORSEN Stoddard Thorsen.
RICHIE DIMASO Listen, I need the Sherman Suite at the Plaza Hotel, okay?
STODDARD THORSEN That's a whole floor of the hotel.
RICHIE DIMASO I need a whole floor.
RICHIE DIMASO I need it for my operation
STODDARD THORSEN Stop calling it your operation, Richard.
STODDARD THORSEN It's not your operation.
STODDARD THORSEN And I'm not giving you a whole floor of the Plaza Hotel.
RICHIE DIMASO I have members of Congress that are gonna come in right now to try to give the Sheik citizenship.
RICHIE DIMASO They're taking bribes.
RICHIE DIMASO This is happening right now.
RICHIE DIMASO That's what's happening right now.
STODDARD THORSEN Bribing members of Congress are you out of your fucking mind?
RICHIE DIMASO Stoddard.
RICHIE DIMASO Stoddard!
RICHIE DIMASO Shut up!
RICHIE DIMASO Listen!
RICHIE DIMASO Do you know who Victor Tellegio is?
RICHIE DIMASO Victor.
RICHIE DIMASO Tellegio.
RICHIE DIMASO Works for Meyer Lansky.
RICHIE DIMASO You know who that is?
STODDARD THORSEN I know who Victor Tellegio is.
RICHIE DIMASO Resorts International!
RICHIE DIMASO He wants ten million dollars.
RICHIE DIMASO I have two weeks!
STODDARD THORSEN You're not getting ten million dollars.
RICHIE DIMASO Just listen to me!
RICHIE DIMASO You're not listening to me!
RICHIE DIMASO I have two weeks!
RICHIE DIMASO I have two weeks to put this thing together and I need you to get me the Sherman Suite at the Plaza Hotel.
RICHIE DIMASO And your going to fucking do it!
STODDARD THORSEN Lower your voice.
STODDARD THORSEN You don't get to yell at me.
Richie SLAMS DOWN THE PHONE.
Edith (HAIR IN CURLERS) STARES
RICHIE DIMASO Calm me down baby.
RICHIE DIMASO You gotta calm me down.
He handles her hips and neck and waist and ass.
RICHIE DIMASO (CONT'D) Baby let's do this.
RICHIE DIMASO (CONT'D) Let's do this right now.
RICHIE DIMASO (CONT'D) --
EDITH GREENSLY No, no.
RICHIE DIMASO I want to do this.
RICHIE DIMASO You're fucking skin is glowing baby.
RICHIE DIMASO Your skin is glowing.
EDITH GREENSLY I'm not doing this with you.
EDITH GREENSLY We're not going to do this unless we do it for real, alright?
RICHIE DIMASO I want to do this now!
EDITH GREENSLY That's what we agreed on so we're not going to do that alright?
EDITH GREENSLY Alright?
EDITH GREENSLY Where are you?
EDITH GREENSLY You're acting all scary.
She grabs him by the head to calm him down.
EDITH GREENSLY (CONT'D) Are you here with me?
RICHIE DIMASO I love you.
RICHIE DIMASO I love you.
RICHIE DIMASO Look at me.
RICHIE DIMASO I'm in love with you.
RICHIE DIMASO It is real now.
RICHIE DIMASO I just said it so now's the time.
He handles her, nuzzles her neck, starts to turn her on.
EDITH GREENSLY You want the truth?
EDITH GREENSLY You want real?
RICHIE DIMASO I'm ready for real.
SYDNEY PROSSER OK, this is real.
SYDNEY PROSSER Do you hear my voice?
SYDNEY PROSSER This is real.
SYDNEY PROSSER This is real.
SYDNEY PROSSER What you hear is real.
Richie steps back quickly and grabs Sydney.
RICHIE DIMASO What?
SYDNEY PROSSER This is me.
RICHIE DIMASO What do you mean?
RICHIE DIMASO What are you doing an accent?
RICHIE DIMASO An American accent?
EDITH GREENSLY No.
EDITH GREENSLY There is no English.
EDITH GREENSLY There's only American.
EDITH GREENSLY There is no English.
Richie looks at her and continues to hold her looking very confused and flustered.
RICHIE DIMASO What are you talking about?
RICHIE DIMASO Stop it.
RICHIE DIMASO You're Edith.
RICHIE DIMASO You're Edith Greensly.
RICHIE DIMASO I checked your records.
SYDNEY PROSSER I falsified my records back to birth.
SYDNEY PROSSER I falsified them.
SYDNEY PROSSER (CONT'D) My name is Sydney Prosser, and I'm from Albuquerque, New Mexico.
SYDNEY PROSSER (CONT'D) I'm not Edith Greensly.
SYDNEY PROSSER (CONT'D) There is no Edith Greensly.
Richie steps back.
He stares at her darkly.
RICHIE DIMASO You're -- freaking -- me -- out.
RICHIE DIMASO No, you said in the stall that we were going to be real and that we weren't going to fake it.
SYDNEY PROSSER I'm being real now.
SYDNEY PROSSER This is who I am.
SYDNEY PROSSER I'm Sydney Prosser.
SYDNEY PROSSER Ok?
RICHIE DIMASO So -- why -- did you do an English accent after that?
SYDNEY PROSSER I'm sorry I didn't tell you in the stall.
SYDNEY PROSSER (CONT'D) I created Edith because I needed her to survive, okay?
SYDNEY PROSSER (CONT'D) But I'm done with that now.
SYDNEY PROSSER (CONT'D) I'm so fucking done with that.
SYDNEY PROSSER (CONT'D) Like you do what you need to survive, right?
SYDNEY PROSSER (CONT'D) You do it.
SYDNEY PROSSER (CONT'D) You know, you live with your mom -- you have a fiancee you don't even acknowledge, right?
SYDNEY PROSSER (CONT'D) That's what you do.
SYDNEY PROSSER (CONT'D) And you curl your hair in little fucking curlers, which is -- No, it's okay, you look good with it, but you know -- you have straight hair, so that's what you do to survive.
SYDNEY PROSSER (CONT'D) You do all sorts of things, you know.
SYDNEY PROSSER (CONT'D) We all do.
RICHIE DIMASO Please don't talk about that.
RICHIE DIMASO I'm confused.
RICHIE DIMASO I'm confused and --
SYDNEY PROSSER I'm fucking confused too, alright?
RICHIE DIMASO -- I think we should fuck, and then we'll feel it and we won't be confused anymore.
SYDNEY PROSSER No -- I want to talk.
SYDNEY PROSSER I don't want to fuck.
RICHIE DIMASO Yes!
RICHIE DIMASO Come on.
SYDNEY PROSSER NO!
SYDNEY PROSSER I'm not fucking you.
SYDNEY PROSSER I'm not fucking fucking you!
RED FACED LIKE HE MAY HIT HER, a vein stands out in his neck.
SHE FLINCHES.
HE SCREAMS like an animal in confusion and frustration.
Richie in pain holds his cut forehead and eyebrow.
They hear a door open off screen, someone approaches.
Irving appears from around the corner of the wall pointing his handgun at Richie.
IRVING ROSENFELD Will you please step away from Edith.
IRVING ROSENFELD I'm asking you nicely please step away from Edith right now.
RICHIE DIMASO What the fuck --
IRVING ROSENFELD Step away from her.
IRVING ROSENFELD Please.
RICHIE DIMASO You mean Sydney?
Irving looks over to Sydney very confused.
SYDNEY PROSSER I told him.
SYDNEY PROSSER I'm sorry.
SYDNEY PROSSER I just don't give a fuck anymore, I don't give a fuck.
SYDNEY PROSSER I don't fucking care.
RICHIE DIMASO Irving has a gun.
IRVING ROSENFELD What Richie's gotten us into is worse then jail.
IRVING ROSENFELD I told you last night, don't sit down with those goons.
IRVING ROSENFELD And what?
IRVING ROSENFELD Now what?
IRVING ROSENFELD No one's getting ten million for Tellegio.
IRVING ROSENFELD It's over.
RICHIE DIMASO I don't think so.
Irving and Sydney stare.
RICHIE DIMASO (CONT'D) Because when Tellegio finds out what happened, do you think he's gonna go after me?
RICHIE DIMASO (CONT'D) I don't think so.
RICHIE DIMASO (CONT'D) Someone from the Bureau?
RICHIE DIMASO (CONT'D) Think he's gonna go after a politician?
RICHIE DIMASO (CONT'D) He's gonna kill you.
RICHIE DIMASO (CONT'D) Then he's going to go after your son.
RICHIE DIMASO (CONT'D) And Sydney.
Richie PICKS UP PHONE AS THEY WATCH -- HE DIALS.
INTERCUT:
STODDARD THORSEN Stoddard Thorsen.
RICHIE DIMASO You're going to give me the Sherman Suite.
RICHIE DIMASO The whole floor.
STODDARD THORSEN That's a NO.
STODDARD THORSEN I said no wacko.
RICHIE DIMASO And you're going to tell me the point of that FUCKING fishing story.
STODDARD THORSEN Not the way you're behaving.
RICHIE DIMASO What's the matter with you?
RICHIE DIMASO Where are you right now?
STODDARD THORSEN What does that make a difference?
RICHIE DIMASO Just tell me where the fuck you are.
STODDARD THORSEN The field office on 61st street.
RICHIE DIMASO I'm coming to 61st Street.
RICHIE DIMASO Right now.
STODDARD THORSEN You're going to do what?
RICHIE DIMASO To beat -- your ass.
STODDARD THORSEN You're going to what?
STODDARD THORSEN Richie SLAMS the phone down, storms out the apartment.
IRVING ROSENFELD You were right.
IRVING ROSENFELD We should have gone away.
IRVING ROSENFELD Irving sits in the corner of the room a disheveled mess.
IRVING ROSENFELD Sydney sits on the bed drinking a Fresca.
IRVING ROSENFELD (CONT'D) I should have gone away with you.
SYDNEY PROSSER We were supposed to do it from the feet up like you always said.
SYDNEY PROSSER That's how we were meant to do it but you didn't do it like that.
SYDNEY PROSSER You didn't do it like that.
SYDNEY PROSSER You played it safe so there was always a danger you were going to end up with Rosalyn in the dead space, floating on some dead spaceship with the furniture and the curtains.
SYDNEY PROSSER And I was your life line out and you were mine and that was ok.
IRVING ROSENFELD I wish I could get you back.
IRVING ROSENFELD He walks across the room and sits down on the bed next to Sydney.
IRVING ROSENFELD (CONT'D) You know I can't do it without you.
IRVING ROSENFELD (CONT'D) You know that.
IRVING ROSENFELD (CONT'D) Come on.
IRVING ROSENFELD (CONT'D) Me, you and Danny.
IRVING ROSENFELD (CONT'D) Like we said.
SYDNEY PROSSER Like I said.
SYDNEY PROSSER You never said that.
SYDNEY PROSSER I said that.
SYDNEY PROSSER We gotta get over on all these guys.
SYDNEY PROSSER That's what we need to be thinking about right now.
SYDNEY PROSSER Irving takes off his glasses and rubs his eyes.
IRVING ROSENFELD That's big.
IRVING ROSENFELD That's crazy.
IRVING ROSENFELD Whatever it is, it's got to be the best we've ever done.
IRVING ROSENFELD Sydney nods her head yes, stares intensely at Irving as the camera tilts down to reveal: their hands clasped together.
High ceiling, old office.
Close on a tape recorder.
FACE AND A WHITE EYE PATCH ON HIS INJURED EYE, SITTING OPPOSITE PROSECUTOR, AMADO - - the tape recorder and microphone sit on the desk in front of Stoddard as he records a statement for a report.
STODDARD THORSEN Agent Dimaso called me late at night on the 21st.
STODDARD THORSEN I believe that he was intoxicated.
STODDARD THORSEN He threatened me and I told him this was inappropriate.
STODDARD THORSEN I told him procedures exist for reasons we must respect.
STODDARD THORSEN This is the third such call I received from Agent Dimaso.
STODDARD THORSEN He called me again the night of the 5th and he threatened to kill me.
STODDARD THORSEN Subsequently he demanded that I allow him to use the Sherman Suite at the Plaza hotel for purposes of bribing members of congress.
STODDARD THORSEN Camera pull-back reveals: THE CHASTENED Richie SITS LISTENING, IN A SUIT AND TIE.
STODDARD THORSEN He's in trouble with their boss, the prosecutor.
RICHIE DIMASO I am so sorry.
STODDARD THORSEN I'm not finished.
STODDARD THORSEN There's a lot more.
STODDARD THORSEN Richie gets up and pulls up a chair next to Stoddard.
STODDARD THORSEN Stoddard flinches and moves away like he's going to get hit again.
RICHIE DIMASO I have nothing but the utmost respect for you as my mentor.
RICHIE DIMASO (he reaches down and turns the tape recorder off) and as my --
STODDARD THORSEN What are you doing?
RICHIE DIMASO I just want to talk from my heart.
RICHIE DIMASO I don't want it on record.
RICHIE DIMASO I want to get vulnerable.
STODDARD THORSEN Can I finish?
STODDARD THORSEN Can I finish my statement?
RICHIE DIMASO Of course.
RICHIE DIMASO I respect you.
STODDARD THORSEN I think you do other things besides respect me.
Stoddard paces while on the phone, holds up a finger to Richie to wait, Richie picks up Stoddard's phone -- rips the cord out and smashes Stoddard across the face with the base.
Doesn't stop til Stoddard falls to the ground, knocks over desk chair and bookcase behind.
INT. OLD FEDERAL BUILDING - DOWN TOWN They stare at each other.
RICHIE DIMASO It's just hard for me to control my passion.
RICHIE DIMASO I'm a very passionate person.
RICHIE DIMASO (looks to Amado) You're from New York.
RICHIE DIMASO You understand this.
RICHIE DIMASO He goes ice fishing in the midwest.
STODDARD THORSEN That was told to you in confidence.
RICHIE DIMASO He's an ice fishing guy.
RICHIE DIMASO Look at him.
Where we left off.
Stoddard reaches with bloodied hands across -- what is he reaching for?
Oh, on a small table, a gun and a clip.
RICHIE DIMASO What are you doing pulling out your gun?
RICHIE DIMASO Stop it.
RICHIE DIMASO That's not you.
STODDARD THORSEN No, it's me.
STODDARD THORSEN This is me.
STODDARD THORSEN It's me.
RICHIE DIMASO Don't do something that you don't know anything about.
RICHIE DIMASO Alright?
Richie grabs his gun and starts to load it.
RICHIE DIMASO I'll show you how it's done.
RICHIE DIMASO I'm not even going to hit you.
He points the gun at Stoddard.
RICHIE DIMASO (CONT'D) Watch this fucko.
Richie and Stoddard stare at each other in silence.
ANTHONY AMADO So, you want to use the Sherman Suite?
ANTHONY AMADO The entire floor?
Stoddard throws his head back, looks at ceiling in exasperation.
Yes!
At the Plaza Hotel.
What happened to the Mafia?
I thought you were --
This is where they intersect!
This is where the two things intersect.
The Politicians and the Mafia.
Victor Tellegio's people who run resorts international --
Victor Tellegio showed his face?
Yes.
I sat with him.
I sat with Victor Tellegio.
I hung out with him.
We can get him.
We can get his whole organization as well as getting any number of congressmen.
I mean, that's just peeling the first layer of the onion.
Wow.
How you going to do that?
We would get ten million dollars and put it into an account --
TEN MILLION DOLLARS?!
Ten Million dollars?
And that's how we just let them know we're for real.
What does he say he's gonna do for the ten million dollars?
How are we trapping him?
He promises to build casinos, handle the skims, do the licencing - -
STODDARD THORSEN And you have him on tape saying this.
STODDARD THORSEN You have that right?
STODDARD THORSEN No.
ANTHONY AMADO I want you to find a safer way to get Victor Tellegio on a wire.
ANTHONY AMADO No ten million dollars -- that's crazy.
STODDARD THORSEN Thank you.
STODDARD THORSEN Richie looks down, defeated.
ANTHONY AMADO Even to entrap Tellegio it's crazy.
ANTHONY AMADO But you can have the Sherman Suite -
ANTHONY AMADO --Stoddard, please -- To go and get me some congressmen.
ANTHONY AMADO Go get some congressmen taking bribes.
ANTHONY AMADO I want to pinch us some congressmen, ok?
ANTHONY AMADO You come back to me.
ANTHONY AMADO I'm proud of you.
RICHIE DIMASO Thank you.
RICHIE DIMASO And Stoddard.
Richie and Stoddard walk down large, echoey Federal building corridor.
Stoddard walking ten feet ahead turns and points at Richie.
STODDARD THORSEN Good luck keeping your job, by the way, and staying out of jail -- and not being killed by the Mob.
STODDARD THORSEN But other than that you're doing a great job.
STODDARD THORSEN Stoddard turns and storms off.
RICHIE DIMASO What's the end of the ice fishing story?
STODDARD THORSEN I'm not telling you the end of the ice fishing story.
RICHIE DIMASO I'm going to call your fucking brother and find out from him.
STODDARD THORSEN My brother's dead.
RICHIE DIMASO That's how it ends.
RICHIE DIMASO He fell through the fucking ice.
STODDARD THORSEN No it's not.
STODDARD THORSEN He died a different way, many years later.
STODDARD THORSEN He storms off and leaves Richie staring in the hallway.
EXT. PLAZA HOTEL -- DAY Establishing.
Richie walks out of a surveillance room and down the hallway to where Irv and Sydney wait.
RICHIE DIMASO Listen I know it's awkward and I just want to say I'm sorry, alright?
RICHIE DIMASO I think we can stick together and still fulfill our goal.
RICHIE DIMASO I mean, we got the Sherman Suite.
IRVING ROSENFELD You got the whole floor?
RICHIE DIMASO We got the whole floor, yeah.
EDITH GREENSLY That's good.
RICHIE DIMASO Yeah, you ok?
SYDNEY PROSSER Yeah.
SYDNEY PROSSER You?
Richie gestures to his eye that Sydney smashed with the picture frame.
He's got a few little scabs.
RICHIE DIMASO It's alright.
RICHIE DIMASO I got hit a little bit.
RICHIE DIMASO My eye.
RICHIE DIMASO It's a little blurry but I got drops at the pharmacy.
Richie looks over to Irving.
RICHIE DIMASO (CONT'D) Hey, you OK?
IRVING ROSENFELD Yeah, I'm good --
Richie looks back over to Sydney
RICHIE DIMASO Listen, I'm sorry.
SYDNEY PROSSER I'm sorry.
RICHIE DIMASO I'm sorry Irving.
Irving doesn't know what to say, starts to say something twice, stops, can't think of what to say.
Leaves Richie hanging.
Richie directs where cameras should be concealed.
AGENTS
RICHIE DIMASO You can put a camera here.
RICHIE DIMASO And we get it all on film.
RICHIE DIMASO You like it?
EDITH GREENSLY I do.
RICHIE DIMASO Give me those flowers.
RICHIE DIMASO (CONT'D) If we put the flower base here and put a camera in there we can get a clear shot of the couch there where we can put the congressmen.
RICHIE DIMASO (CONT'D) Irving, sitting on the couch, looks kind of disturbed by this.
IRVING ROSENFELD That's right.
IRVING ROSENFELD That's the idea.
RICHIE DIMASO And Carmine will go to jail after he delivers us the congressmen soon to be felons.
RICHIE DIMASO Carmine's aid MELORA answers a ringing phone as Carmine sits at his desk.
MELORA Congressman O'Connell is on the phone --
CARMINE POLITO I got to take this you guys everyone out please.
CARMINE POLITO Dolly Polito, checking the unwatered plants in her husbands office with her coat on, she has just stopped by.
CARMINE POLITO Turns and holds up a parched and dying houseplant.
DOLLY POLITO This is sad.
DOLLY POLITO It's just sad.
CARMINE POLITO Dolly please, I gotta take this.
DOLLY POLITO Ok, sorry.
DOLLY POLITO Everyone out.
DOLLY POLITO Go out.
CARMINE POLITO Congressman, how you doing?
CARMINE POLITO It's Carmine.
CARMINE POLITO Tell me you're gonna be in Trenton this week.
CARMINE POLITO We have an amazing investment opportunity I'd like to discuss with you.
INT. PLAZA HOTEL - GENERAL SHERMAN SUITE - DAY Richie on a black and white surveillance camera as he shows the briefcase full of money.
RICHIE DIMASO I'm federal agent Richard Dimaso.
RICHIE DIMASO I've placed seventy-five thousand dollars into this briefcase for Representative John O'Connell of the Ninth District.
Carmine shakes hands with REP.
JOHN O'CONNELL --
CARMINE POLITO Congressman, thank you for coming by, John --
RICHIE DIMASO (V.O.) Representative O'Connell was contacted by Carmine Polito to ask if he could obtain rapid citizenship through an act of Congress for one Sheik Abdullah, investor.
RICHIE DIMASO (V.O.) They walk up the capitol steps.
CARMINE POLITO You wanna talk jobs, investment, construction, if we can expedite a very wealthy man's citizenship --
150 CAMERA PANS TO HOLE IN CORNER and CAMERA LENS -- 150
RICHIE DIMASO How you doing congressmen?
JOHN O'CONNELL I'm excited to be here.
CARMINE POLITO This brings the state back.
CARMINE POLITO I mean, how long we known each other?
CARMINE POLITO (CONT'D) You know what this is gonna do for us?
CARMINE POLITO (CONT'D) This is huge for the state of New Jersey.
CARMINE POLITO (CONT'D) It stabilizes our economy.
IRVING ROSENFELD Hotels.
IRVING ROSENFELD Restaurants.
IRVING ROSENFELD It's waiting to happen.
IRVING ROSENFELD Carmine sees it, this fucking thing is waiting to happen.
CARMINE POLITO The goddamn bankers.
CARMINE POLITO Keeping their money on the sidelines.
CARMINE POLITO How we supposed to get anything done?
JOHN O'CONNELL Bankers only put money in the game when they can reap insane profit.
Richie staring, mesmerized by this trap.
RICHIE DIMASO The only problem is this citizenship situation.
RICHIE DIMASO I mean, we got to expedite it as soon as possible.
JOHN O'CONNELL Yeah, well I'll tell you, you came to the right place.
Everyone looks tense and on edge before.
JOHN O'CONNELL (CONT'D) I'll make it happen.
CARMINE POLITO Hey, this is going to happen.
Richie slides the briefcase in John's direction.
CARMINE POLITO (CONT'D) This is real.
CARMINE POLITO (CONT'D) You understand?
CARMINE POLITO (CONT'D) This is real.
CARMINE POLITO (CONT'D) On my family.
CARMINE POLITO (CONT'D) On my kids.
CARMINE POLITO (CONT'D) On my life.
CARMINE POLITO (CONT'D) On my work.
JOHN O'CONNELL I know that, Carmine.
JOHN O'CONNELL You're a good man
This hurts Irving to see his friends sincerity.
RICHIE DIMASO I'm federal agent Richard Dimaso.
RICHIE DIMASO I am placing 75 thousand dollars in this brief case for one Representative Gerald Sanders of the 3rd district.
SANDERS I don't want to do anything illegal-
CARMINE POLITO Please Gerry.
CARMINE POLITO Use it as a campaign donation.
CARMINE POLITO Whatever you want to do.
CARMINE POLITO Richie slides the briefcase to him.
RICHIE DIMASO I'm placing g $60,000 into an this brief case for one Congressman Eric Keshoygan of the 4th district --
ERIC KESHOYGAN I'm going to do what I can to help Carmine.
ERIC KESHOYGAN Irv watches in pain as he sits with them.
RICHIE DIMASO A $100,000 into this briefcase for two term United States Senator Horton Mitchell of New Jersey.
RICHIE DIMASO A distinguished silver haired Senator, older.
HORTON MITCHELL Atlantic City.
HORTON MITCHELL All the way down the shore.
HORTON MITCHELL A mecca by the sea.
121. Richie slides over the briefcase.
HORTON MITCHELL (CONT'D) Carmine you're beloved by your people.
HORTON MITCHELL (CONT'D) Your constituency is not even your constituency it's your family.
HORTON MITCHELL (CONT'D) That's what you represent, family.
CARMINE POLITO One small thing we do for this man is a huge thing we do for the people of New Jersey.
CARMINE POLITO This is what we can leave behind.
CARMINE POLITO Irving can't stand how hopeful his friend Carmine is being because Irving knows Carmine is being set up.
CARMINE POLITO He gets up --
CARMINE POLITO (CONT'D) Irving what are you doing?
RICHIE DIMASO Where you going?
IRVING ROSENFELD I just gotta go see a man about a dog.
CARMINE POLITO I appreciate this.
CARMINE POLITO On my family.
CARMINE POLITO On my kids.
CARMINE POLITO This needs to happen.
CARMINE POLITO It's gotta happen.
CARMINE POLITO You've got my word
CARMINE POLITO Irving walks out of the room --
--into another room where Sydney on elegant gold couch, sits alone.
Surveillance equipment and room service trays are on the coffee table.
She watches Irving who is pacing anxiously and very wound up.
IRVING ROSENFELD I want to save us.
IRVING ROSENFELD I want to save Carmine.
IRVING ROSENFELD It's fucking killing me.
SYDNEY PROSSER You know the only way to help Carmine is through the Tellegio thing.
IRVING ROSENFELD It's dangerous.
IRVING ROSENFELD We gotta get a wire in there.
IRVING ROSENFELD We gotta make him feel safe.
SYDNEY PROSSER There's only one thing that can really fuck this up and that's your wife.
IRVING ROSENFELD Yep.
Rosalyn fixes Danny's coat, hands him his lunch and sends him off towards the school's front door --
CLOSE UP: ROSALYN STARES INTO LENS.
Emotional, a mixture of sadness and hope.
She holds a closed bottle of her favorite nail finish and smells it nostalgically.
He gently puts a hand on her knee.
She leaves it there for a moment before pushing it away.
They stare at each other.
PETE MUSANE I don't like your husband.
PETE MUSANE You're no good together.
PETE MUSANE He doesn't appreciate you.
PETE MUSANE Hey, it happens.
PETE MUSANE It happened in my marriage.
PETE MUSANE That's why I went to Miami.
PETE MUSANE Sometimes you just gotta be tough.
PETE MUSANE You gotta stand up and you gotta leave, you know?
Rosalyn looks at Pete smitten.
PETE MUSANE (CONT'D) Sometimes you gotta let something die to let something live.
PETE MUSANE (CONT'D) You're too beautiful to be unhappy.
ROSALYN ROSENFELD I know.
ROSALYN ROSENFELD I mean, I don't want to badmouth my husband, but let me badmouth my husband for a second.
ROSALYN ROSENFELD He just thinks that he knows everything and he's so full of shit.
ROSALYN ROSENFELD He's such a liar.
ROSALYN ROSENFELD He thinks that I'm stupid, but I'm not stupid.
ROSALYN ROSENFELD I hear him on the phone arguing.
ROSALYN ROSENFELD He loves Carmine, but he hates that other guy, that curly- headed I.R.S. guy, or whatever who's carting around my husband's ex-lover, that redheaded whore.
ROSALYN ROSENFELD Anyway.
ROSALYN ROSENFELD You can see that it drives him crazy.
PETE MUSANE You said IRS.
PETE MUSANE What IRS guy?
PETE MUSANE What are you talking bout?
ROSALYN ROSENFELD I hear them on the phone.
ROSALYN ROSENFELD I think that he's got Irv in some sort of bind or something and he's making him do all of this stuff and so Irv and Carmine right now are at the Plaza Hotel throwing away all this money at like Congress or whatever.
ROSALYN ROSENFELD They're giving money to congress or something.
ROSALYN ROSENFELD I don't really know but I overheard it on the phone.
124. Pete's brow furrows - this is serious.
PETE MUSANE You know I hate to do this to you but I have to go talk to your husband.
PETE MUSANE My boss is already angry.
PETE MUSANE You stay here I'm going to give you some money for a taxi home.
PETE MUSANE He puts cash in her hands.
PETE MUSANE (CONT'D) You stay here.
PETE MUSANE (CONT'D) Get yourself some dessert.
PETE MUSANE (CONT'D) Finish the bottle of prosecco.
PETE MUSANE (CONT'D) I'm sorry.
PETE MUSANE (CONT'D) Rosalyn and Pete hold hands as Rosalyn stares into his eyes.
PETE MUSANE (CONT'D) Very emotional.
PETE MUSANE (CONT'D) You alright?
ROSALYN ROSENFELD I don't like change.
ROSALYN ROSENFELD It's really hard for me.
ROSALYN ROSENFELD Sometimes I think that I'll die before I change.
ROSALYN ROSENFELD He kisses her.
PETE MUSANE It's gonna be okay.
PETE MUSANE You're gonna come live with me in Miami.
Pete gets up and walks.
As he does:
164 Don't hurt him too bad.
He's still 164 Danny's father.
Irv and Carmine down sidewalk leaving from The Plaza Hotel --
Pete Musane stands next to an open passenger side door, -- Irv and Carmine do not move, they stare at the open door.
170 Rosalyn in full muumuu, wearing cleaning gloves and holding a 170 vacuum sings to LIVE AND LET DIE while Danny sits on the couch watching her.
Very intense.
Irving and Carmine sit up front with Pete driving and Dick Helsing sits in the back seat looking angry.
DIE" CONTINUOUS Rosalyn continues to sing and gets more intense as the music picks up.
INT. PETE MUSANE'S CADILLAC - "LIVE AND LET DIE" CONTINUOUS Irving looks over to Pete nervously.
INT. PETE MUSANE'S CADILLAC - "LIVE AND LET DIE" CONTINUOUS Unsure of what's going to happen.
DIE" CONTINUOUS Rosalyn whips her head up and down, dancing manically through the house.
INT. IRV AND ROSALYN'S HOUSE - BEDROOM - NIGHT Rosalyn sits on the bed with Danny with clothes all over the place while smoking a cigarette.
ROSALYN ROSENFELD Life is ridiculous and I would never say anything bad about your father in front of you but your father is a sick son of a bitch.
DANNY Daddy's a sick son of a bitch?
ROSALYN ROSENFELD Don't repeat that.
ROSALYN ROSENFELD But yes.
Irving's Caddy comes screeching up to the house and parks in the driveway.
Irv get's out and races inside.
Rosalyn is still sitting on the bed with Danny.
Rosalyn looks scared.
IRVING ROSENFELD (CONT'D) This is a real low in our relationship!
IRVING ROSENFELD (CONT'D) You know where I was recently?
IRVING ROSENFELD (CONT'D) I was in your boyfriend's fucking car!
IRVING ROSENFELD (CONT'D) I saw your nail polish.
WINDSHIELD SMELLS IT, WORRIED.
Carmine glances over his shoulder anxiously at Dick Helsing in the back seat.
PETE MUSANE What's this I hear about your curly haired friend working for the Government?
CARMINE POLITO What?!
CARMINE POLITO Who said that?
IRVING ROSENFELD That's bullshit!
PETE MUSANE Your wife.
Irving is surprised to hear this.
IRVING ROSENFELD That's bullshit.
CARMINE POLITO Rosalyn?
CARMINE POLITO Hey, what the fuck?!
CARMINE POLITO --
PETE MUSANE Shut up.
PETE MUSANE Shut the fuck up.
ROSALYN What are you talking about?!
ROSALYN ROSENFELD Get out of here!
ROSALYN ROSENFELD I'm not doing anything!
Irving looks down to see Danny sitting there on the bed.
IRVING ROSENFELD (CONT'D) Danny.
IRVING ROSENFELD (CONT'D) Come here buddy alright?
IRVING ROSENFELD (CONT'D) Go draw a picture or something.
Irving ushers Danny out of the room.
ROSALYN ROSENFELD You're a real sick son of a bitch for screaming at me like that in front of Danny.
IRVING ROSENFELD He's a mobster alright?
IRVING ROSENFELD That's who you're dealing with.
ROSALYN ROSENFELD Alright fine!
ROSALYN ROSENFELD Yes, I wanted to hurt you but how do you think that I feel all day when you leave me alone all day?
ROSALYN ROSENFELD And all I've ever wanted is for you to love me.
ROSALYN ROSENFELD That's all I ever wanted.
ROSALYN ROSENFELD And stay married and for you to love me.
ROSALYN ROSENFELD And that's why I'm going to Miami!
IRVING ROSENFELD You're NOT going to Miami.
ROSALYN ROSENFELD That's why I'm going to Miami with Pete!
Irving picks up Rosalyn's clothes from the bed where there is an open suitcase, throws them back in the closet.
IRVING ROSENFELD You are NOT going to Miami.
ROSALYN ROSENFELD I finally found somebody who loves me just like YOU always wanted.
IRVING ROSENFELD Too dangerous.
IRVING ROSENFELD Miami?
IRVING ROSENFELD Not now.
IRVING ROSENFELD Too dangerous.
Irv continue to throw clothes back into the closet.
ROSALYN ROSENFELD He likes me just the way I am.
IRVING ROSENFELD Not now.
IRVING ROSENFELD Everything has to stay normal right now.
IRVING ROSENFELD And you're going to shut your mouth!
ROSALYN ROSENFELD You told me that you wanted me to find a nice quiet man!
IRVING ROSENFELD Oh and what a DOOZY you picked!
ROSALYN ROSENFELD He's the one.
IRVING ROSENFELD He's the most dangerous guy ever.
Irving reaches for his heart pills but they fall out of his hands and scatter on the floor.
He bends down to grab them and almost falls.
Rosalyn helps him up.
ROSALYN ROSENFELD (CONT'D) Why aren't you taking your heart pills?
ROSALYN ROSENFELD (CONT'D) Irving, what's going on?
ROSALYN ROSENFELD (CONT'D) What kind of trouble are you in?!
ROSALYN ROSENFELD (CONT'D) What's happening?
IRVING ROSENFELD I've got a plan.
ROSALYN ROSENFELD What's happening?
Irving coughs and steps back.
Out of breath and very winded.
IRVING ROSENFELD I've got a plan.
ROSALYN ROSENFELD You've got a plan?
ROSALYN ROSENFELD When did you get it?
IRVING ROSENFELD It really fucking came to me when I was inside of that canvas bag with your boyfriend's hands around my throat.
IRVING ROSENFELD That's when it really came to me.
CARMINE POLITO Take it off!
CARMINE POLITO Take the bag off his head!
CARMINE POLITO Dick pulls the bag off Irving's head, his comb over is all messed up.
CARMINE POLITO IRVING GASPS.
CARMINE POLITO Pete and Dick LAUGH --
IRVING ROSENFELD We've got two million coming this week!
PETE MUSANE What do you think this is?
PETE MUSANE You think this is a fucking down payment plan?
PETE MUSANE Like were Sears of Chevrolet?
IRVING ROSENFELD You ask Victor if he wants two million this week.
IRVING ROSENFELD That's real money.
IRVING ROSENFELD Two million.
PETE MUSANE Two million?
PETE MUSANE How?
IRVING ROSENFELD Wired in.
They LAUGH, Irving's hair is all messed up.
Pete patches out.
Irving and Carmine are a mess, shirts ripped open, no buttons, they look at each other VERY SHAKEN.
CARMINE POLITO Is it true?
CARMINE POLITO Is it true what he said about your wife?
IRVING ROSENFELD It's not fucking true.
IRVING ROSENFELD That's not true.
IRVING ROSENFELD I can save all of us, and we can save money.
IRVING ROSENFELD I can take care of you and Danny.
IRVING ROSENFELD OK?
IRVING ROSENFELD But you gotta close your mouth.
Rosalyn looks satisfied and points her finger at Irving.
ROSALYN ROSENFELD I knew it.
ROSALYN ROSENFELD I have always said, Irving, that you are very, very hard to motivate properly.
ROSALYN ROSENFELD And I knew that Pete was gonna go over there and knock some sense into you.
ROSALYN ROSENFELD I've been reading this book, Irving.
ROSALYN ROSENFELD It's by Wayne Dyer, about the power of intention.
Irving can't believe what he's hearing right now.
Rosalyn, very satisfied, reaches over the bed and grabs a book.
ROSALYN ROSENFELD (CONT'D) And my intention in sending Pete over to you was so that you could come up with this plan.
ROSALYN ROSENFELD (CONT'D) So, you're welcome.
Irving incredulous, thinks to himself how to respond.
Forces himself to say gently --
IRVING ROSENFELD OK.
IRVING ROSENFELD Thank you, Rosalyn.
IRVING ROSENFELD Thank you for the plan.
ROSALYN ROSENFELD You're welcome.
IRVING ROSENFELD I appreciate that.
IRVING ROSENFELD So, I think that we should be partners on this.
ROSALYN ROSENFELD I'm a good partner.
ROSALYN ROSENFELD Almost better than Edith.
ROSALYN ROSENFELD You ever think about that?
ROSALYN ROSENFELD You ever think about how you might have underestimated me?
IRVING ROSENFELD So what is our plan?
IRVING ROSENFELD Tell me the plan.
IRVING ROSENFELD What are you gonna do?
ROSALYN ROSENFELD I'm going to keep my mouth shut and I'm not going to say anything but what do I do if Pete calls me?
ROSALYN ROSENFELD What am I supposed to say?
IRVING ROSENFELD You gotta stop talking about your government agencies and your I.R.S.
IRVING ROSENFELD and your tax and your conspiracies and all of that.
IRVING ROSENFELD You're gonna say how you were wrong, you were wrong about that.
ROSALYN ROSENFELD I'll tell Pete that I was wrong but you know that in real life, I was right for saying all that stuff because then that spurred on the actions that made you come up with this plan.
ROSALYN ROSENFELD So I will tell Pete.
ROSALYN ROSENFELD The power of intention Irving.
ROSALYN ROSENFELD The power of intention.
Irv is doing everything he can to hold it together.
IRVING ROSENFELD OK.
IRVING ROSENFELD You were right.
Rosalyn gets up from the bed and walks over to Irving.
IRVING ROSENFELD (CONT'D) You're so smart.
IRVING ROSENFELD (CONT'D) Good job, peaches.
ROSALYN ROSENFELD Irving, I've been doing a lot of thinking and -- you need to grow up.
ROSALYN ROSENFELD And you need to face the facts.
ROSALYN ROSENFELD And I think that both of us will be a lot happier if we get a divorce.
As he listens to words he has been saying himself for months, now spoken as Rosalyn's idea.
ROSALYN ROSENFELD Just think about it.
ROSALYN ROSENFELD (kisses him) These things are never easy.
ROSALYN ROSENFELD Irving starts walking away towards the door.
IRVING ROSENFELD Alright.
ROSALYN ROSENFELD Irving.
ROSALYN ROSENFELD Good luck with your plan.
EXT. FBI OFFICE, FEDERAL OFFICE BUILDING, NY - DAY The spare rhythmic intro of Jeff Lynne's "Long Black Road" plays as Richie looks back over his shoulder and walks towards the building with intensity.
IRVING ROSENFELD (V.O.) Necessity truly is the mother of invention.
IRVING ROSENFELD (V.O.) The F.B.I. was willing to wire the two million dollars if it meant taking down Tellegio and his entire organization.
INT. FBI OFFICE, FEDERAL OFFICE BUILDING, NY Brenda in her office.
INT. FBI OFFICE, FEDERAL OFFICE BUILDING, NY Amado looking very pleased on the telephone.
Irving walks with Richie and Sydney up to an office building.
IRVING ROSENFELD (V.O.) A mobster like Tellegio would never meet at the Plaza Hotel, but only at the office of his attorney, Alfonse Simone.
IRVING ROSENFELD (V.O.) They walk into mob lawyer Simone's building.
On an old faded directory: 7TH FLOOR: ALFONSE SIMONE #701
They open door to large, spare reception area of Alfonse Simone's law office.
MIDDLE AGED SECRETARY looks up and picks up the phone.
ALFONSE SIMONE- 64, BRONX, SEASONED LAWYER. Alfonse Simone rises from behind his desk.
ALFONSE SIMONE- 64, BRONX, SEASONED LAWYER. A silent secretary sitting at his side in a white dress stares at our heros as Simone steps forward to introduce himself.
ALFONSE SIMONE Alfonse Simone.
ALFONSE SIMONE Edith walks up to him to shake hands.
ALFONSE SIMONE He shakes hands with Irving and Richie as well.
ALFONSE SIMONE Man in the suit closes the door behind them.
EDITH GREENSLY Edith Greensly.
IRVING ROSENFELD Irving Rosenfeld.
RICHIE DIMASO Good afternoon.
ALFONSE SIMONE Please, be seated.
They sit in three chairs facing Simone's desk: Sydney/Edith, Richie, Irving.
Simone sits behind his desk, the silent secretary sits just behind him slightly to the side, stares at Edith, Richie, Irving.
ALFONSE SIMONE (CONT'D) I appreciate the fact that you all came in person, but the trip was really unnecessary because this whole thing could have been done with a simple wire transfer.
ALFONSE SIMONE (CONT'D) As a matter of fact this is the number of our wire right here.
Simone slides a small pink piece of paper across the desk to them.
Richie stares at the paper, but doesn't touch it.
RICHIE DIMASO Where is Mr. Tellegio?
ALFONSE SIMONE Mr. Tellegio unfortunately was called out of town on business.
RICHIE DIMASO That's not good.
RICHIE DIMASO We were willing to come here today, in person, to see Mr. Tellegio, as a sign of respect to give two million dollars --
ALFONSE SIMONE I can assure you that I have the power of attorney --
RICHIE DIMASO Excuse me.
RICHIE DIMASO If you'll let me finish, we are willing to give two million dollars today of the ten.
RICHIE DIMASO But without Mr. Tellegio here --
IRVING ROSENFELD We can't, we can't make that decision.
IRVING ROSENFELD It's not the right thing.
IRVING ROSENFELD It's not the right time.
IRVING ROSENFELD It's just not good.
EDITH GREENSLY You don't have the authorization to make this kind of choice so don't be hasty, alright?
IRVING ROSENFELD I'm not being hasty.
IRVING ROSENFELD It's just, let's be smart about it.
IRVING ROSENFELD This is not how we do business.
IRVING ROSENFELD (to Simone) I'm sorry.
IRVING ROSENFELD I apologize.
Richie motions with his hand to Edith that he agrees with Irving.
RICHIE DIMASO He's right, we can't.
EDITH GREENSLY I think you should hang in there.
RICHIE DIMASO For what?
RICHIE DIMASO The guy's not here.
IRVING ROSENFELD He isn't.
RICHIE DIMASO That's it.
He stands, goes to the door.
IRVING ROSENFELD This is a surprise.
IRVING ROSENFELD The Sheik doesn't like surprises.
Edith turns in her chair to face them in the doorway.
EDITH GREENSLY Don't leave.
IRVING ROSENFELD Edith, this is not your decision to make.
EDITH GREENSLY I understand but maybe we can call the Sheik.
EDITH GREENSLY Let's call the Sheik.
IRVING ROSENFELD That's not the plan.
IRVING ROSENFELD That's not the --
Edith locks eyes with Richie.
Richie stares at Edith, waves Irving off with his hand.
RICHIE DIMASO No, let's -- I'll call the Sheik.
RICHIE DIMASO (to Simone) Can I use your phone?
ALFONSE SIMONE Please do.
RICHIE DIMASO I don't know if he's in, I'll call the Sheik.
RICHIE DIMASO But before I do, I'd like to go over specifically what this money will be used for.
ALFONSE SIMONE What we will do is we guarantee all proper licenses and construction permits for any hotel casino that plans to open before the end of the year.
Richie glances down at Edith and her handbag.
PUSH IN ON A
ALFONSE SIMONE (CONT'D) And we'll throw in the customary privileges and protection.
RICHIE DIMASO What if there are obstacles, what will you do?
ALFONSE SIMONE Obstacles?
ALFONSE SIMONE We are prepared to overcome any obstacles.
RICHIE DIMASO This is a big enterprise.
ALFONSE SIMONE If we have to pay somebody off, we'll pay somebody off.
ALFONSE SIMONE If we have to lean on somebody, intimidate somebody, we'll intimidate somebody.
ALFONSE SIMONE We're experienced.
ALFONSE SIMONE This is our business.
RICHIE DIMASO That's powerful stuff.
RICHIE DIMASO Thank you.
ALFONSE SIMONE And I'll tell you something else.
ALFONSE SIMONE At the end of this we'll teach you how to skim and how to cut it up and make some money on the side.
ALFONSE SIMONE Because we invented skimming.
ALFONSE SIMONE We've been doing it for thirty years.
A smile creeps across Richie's face.
RICHIE DIMASO Thank you.
RICHIE DIMASO Thank you for clarifying that.
Richie picks up the phone to dial.
RICHIE DIMASO (CONT'D) I think that will be OK for the Sheik.
ANTHONY AMADO This is the Sheik.
RICHIE DIMASO Mr. Tellegio is not here.
RICHIE DIMASO It's just Mr. Alfonse Simone, his lawyer.
RICHIE DIMASO Are we still ok to wire the money?
ALFONSE SIMONE Simone can take the money.
ALFONSE SIMONE What's the number?
Amado writes it down and hands it to Brenda to call in.
BRENDA The funds have been transferred.
ANTHONY AMADO The funds have been transferred.
Amado nods: victory.
BACK TO:
INT. ALFONSE SIMONE'S OFFICE - DAY - CONTINUOUS Richie hangs up.
RICHIE DIMASO The money's been wired.
ALFONSE SIMONE I think we have a deal.
RICHIE DIMASO Yes we do sir.
ALFONSE SIMONE Pleasure doing business with you.
RICHIE DIMASO Okay, well, thank you very much, Mr. Simone.
RICHIE DIMASO (CONT'D) The Sheik's very excited.
ALFONSE SIMONE I'm sure that we'll be seeing each other.
ALFONSE SIMONE Richie and team start to walk out.
RICHIE DIMASO Oh I'm sure we'll be seeing each other very soon.
RICHIE DIMASO You may even get sick of me, like these two.
ALFONSE SIMONE I don't think I'll get sick of you.
ALFONSE SIMONE Nice meeting you.
ALFONSE SIMONE Richie, Edith, and Irving walk down the hall after leaving his office.
ALFONSE SIMONE Richie smiles as the opening of Bowie's "The Jean Genie" momentously starts.
ALFONSE SIMONE Edith smiles as she walks down the hall followed by Irving.
ALFONSE SIMONE Richie puts his hand on the door knob to exit the hallway.
ANTHONY AMADO We're ambitious, that's why!
ANTHONY AMADO Richie suddenly moves to the reel to reel surveillance tape and quiets the room, the music momentarily stops as we hear Alfonse Simone on the surveillance tape.
RICHIE DIMASO Shh, shh, shh!
ALFONSE SIMONE (ON SURVEILLANCE TAPE) If we have to pay somebody off, we'll pay somebody off.
ALFONSE SIMONE (ON SURVEILLANCE TAPE) If we have to lean on somebody, intimidate somebody, we'll intimidate somebody.
ALFONSE SIMONE (ON SURVEILLANCE TAPE) Richie joyfully lip synchs to the rhythm of Simone's incriminating words on tape.
RICHIE DIMASO -- If we have to lean on somebody, intimate somebody, we'll intimidate somebody!!
Irving's big blue car pulls up to the lens.
Irving and Sydney looking a little uneasy.
Irving stares at the house.
IRVING ROSENFELD I gotta do it.
CARMINE POLITO What do you mean, there's no sheik?
CARMINE POLITO What does that mean, "there's no sheik"?
CARMINE POLITO What does that mean?
CARMINE POLITO Carmine stares at Irving.
IRVING ROSENFELD I want to face you like a man because I want to be real now.
CARMINE POLITO Who is "they"?
CARMINE POLITO Irving looks distressed.
CARMINE POLITO He's a wreck.
IRVING ROSENFELD It's the Feds.
CARMINE POLITO The Feds?
IRVING ROSENFELD Yeah.
CARMINE POLITO Irving -- I'm a good person
IRVING ROSENFELD You are!
IRVING ROSENFELD Carmine stands up and looks around the room, disoriented, his life passing before his eyes.
CARMINE POLITO I've been doing this for a long time, for twenty years.
CARMINE POLITO Do you think I woulda taken that money if it wasn't the right thing to do?
IRVING ROSENFELD Hey look, you're a good person I know that but in all honesty --
CARMINE POLITO You said that was the only way, Irv.
CARMINE POLITO You chased me, remember?
IRVING ROSENFELD They fuckin' made me do it.
IRVING ROSENFELD What was I supposed to do?
IRVING ROSENFELD They had Syd in jail.
CARMINE POLITO You made me go back to the Plaza to take that money, you piece of shit!
CARMINE POLITO I was gone!
CARMINE POLITO You fucking prick!
CARMINE POLITO (CONT'D) I was gone, I left!
DOLLY POLITO Is everything alright?
DOLLY POLITO Can I have a word with you?
CARMINE POLITO No, please, Dolly, just go upstairs.
CARMINE POLITO Take the kids and go upstairs!
DOLLY POLITO Alright, alright.
IRVING ROSENFELD I want to make this right.
IRVING ROSENFELD I came here because I want to make it right.
Irving is in tears.
Very upset.
CARMINE POLITO Look at my face.
CARMINE POLITO You tell me that I'm lying to you when I say that everything I do is for the good of the people of New Jersey.
CARMINE POLITO Everything I do is for them.
CARMINE POLITO Am I lying to you?
IRVING ROSENFELD I never had a friend like you before.
CARMINE POLITO I used that money for the goddamn casino.
IRVING ROSENFELD I got some leverage, alright?
IRVING ROSENFELD I can help you out.
CARMINE POLITO This is all shit.
CARMINE POLITO It's all bullshit.
Carmine picks up the knife the Sheik gave him.
CARMINE POLITO (CONT'D) Look at this thing.
CARMINE POLITO (CONT'D) Look at this.
CARMINE POLITO (CONT'D) Ceremonial fucking knife.
CARMINE POLITO (CONT'D) What is this bullshit?
CARMINE POLITO (CONT'D) Some toy?
He drops it on the table.
Irving stares at his friend, removes his glasses.
IRVING ROSENFELD Carmine, Syd and I got a plan for you.
IRVING ROSENFELD We can help you out.
CARMINE POLITO Please get out of my house, Irving.
CARMINE POLITO Will you please leave?
CARMINE POLITO I'm asking you nicely, please leave.
Irving gets up to go and is pushed towards the door by Carmine.
Dolly joins Carmine in tears.
Carmine's kids stand on the stairs.
DOLLY POLITO Get out of our house!
IRVING ROSENFELD I don't want to -- (seeing kids) I'm sorry.
IRVING ROSENFELD I didn't mean for this to happen.
CARMINE POLITO This is not our friend!
IRVING ROSENFELD Truly, I didn't mean for this to happen.
144. Carmine points to his family.
CARMINE POLITO This is what matters to me most and you're crushing it!
CARMINE POLITO You're going to take me away from them you fucking son of a bitch?
CARMINE POLITO Get the fuck out!
183 Carmine lunges at Irving and punches him in the face.
Irving 183 goes down to the ground and his glasses fly off his face.
CARMINE kicks him one last time.
IRVING ROSENFELD I just want to make it right.
CARMINE POLITO Get out of my house.
CARMINE POLITO Look what you made me do!
IRVING ROSENFELD I'm sorry Carmine, I'm sorry.
Irving staggers out of the house in an emotional daze, one hand to his heart, falls to sidewalk with bloody nose and broken glasses --
SYDNEY PROSSER Irving!
SYDNEY PROSSER (CONT'D) Your heart pills.
SYDNEY PROSSER (CONT'D) Where are your heart pills?
SYDNEY PROSSER (CONT'D) She digs through his pockets, finds the pills, and feeds one to him.
SYDNEY PROSSER (CONT'D) Sydney struggles to help Irving to his feet and together, an embattled but surviving couple, they cross the street arm and arm.
SYDNEY PROSSER (CONT'D) She opens the door and helps him into the car.
IRVING ROSENFELD I've got to lay down.
SYDNEY PROSSER Just rest.
SYDNEY PROSSER She gets in and closes the door.
They both slump down on the seat, stare at each other, emotional, humbled.
Sydney gently removes Irving's broken glasses.
They stare at each other, it is quiet.
SYDNEY PROSSER Are you ready?
IRVING ROSENFELD Yes.
IRVING ROSENFELD They stare at each other.
IRVING ROSENFELD (CONT'D) I love you.
IRVING ROSENFELD (CONT'D) She squeezes his hand, raises it to her lips and kisses it.
ANTHONY AMADO Please.
ANTHONY AMADO Come in.
ANTHONY AMADO Sit down.
ANTHONY AMADO They all sit.
ANTHONY AMADO (CONT'D) Do you know where our two million dollars is?
IRVING ROSENFELD Two million?
IRVING ROSENFELD (Irving pushes his new glasses up the bridge of his nose) It's with Victor Tellegio and Alfonse Simone.
ANTHONY AMADO No, actually it's not with Victor Tellegio or Alfonse Simone.
Richie stands by the window, stares angrily at Irving.
RICHIE DIMASO He fucking knows about it.
ANTHONY AMADO It's gone missing.
ANTHONY AMADO Did you know that?
IRVING ROSENFELD Where's it gone?
ANTHONY AMADO That's interesting that you said that because while you were on your way over here, we got an anonymous phone call from someone who said that in exchange for immunity for the two of you and a reduced sentence for Carmine Polito we get our two million dollars back.
IRVING ROSENFELD That's interesting.
IRVING ROSENFELD That's very interesting.
IRVING ROSENFELD I have no idea.
ANTHONY AMADO No idea?
IRVING ROSENFELD No idea what you're talking about.
Irving looks at Sydney who looks back at him and shakes her head.
She doesn't know either.
ANTHONY AMADO I got it.
ANTHONY AMADO I understand how these deals are made.
ANTHONY AMADO See, someone has leverage.
RICHIE DIMASO Anthony, fuck them.
RICHIE DIMASO It's over.
RICHIE DIMASO We got them for wire fraud, it's over.
RICHIE DIMASO (to Irving and Sydney) You're done.
RICHIE DIMASO You're both done.
IRVING ROSENFELD I don't think so.
RICHIE DIMASO Oh, you don't think so?
IRVING ROSENFELD Richard, think about it, YOU requested the two million.
IRVING ROSENFELD And you gave Brenda the account number.
IRVING ROSENFELD We didn't do any of that.
IRVING ROSENFELD None of it.
IRVING ROSENFELD How do we know that YOU don't have the money?
RICHIE DIMASO Am I living in a fucking nightmare right now?
IRVING ROSENFELD I find this a little offensive.
IRVING ROSENFELD Really, I find this a little offensive and I don't see that you got any sort of solid case against--
RICHIE DIMASO Don't let him get in your heads.
RICHIE DIMASO Listen to me, we're dealing with a very clever individual.
IRVING ROSENFELD Richard, think about it.
IRVING ROSENFELD You got some big arrests.
IRVING ROSENFELD You got U.S.
IRVING ROSENFELD Congressmen.
IRVING ROSENFELD You look good.
IRVING ROSENFELD You're gonna be all over the news.
IRVING ROSENFELD You know what doesn't look good?
IRVING ROSENFELD A story about gross incompetence
RICHIE DIMASO I have a warrant for --
RICHIE DIMASO Richie looks around disoriented, we cannot see what he sees yet.
RICHIE DIMASO (CONT'D) I'm sorry, do I have the wrong office?(checks number on the door) Is this 701?
RICHIE DIMASO (CONT'D) Alfonse Simone?
MAN'S VOICE This is 701.
BLACK DIVORCE LAWYER My name is Roger Thigpen.
BLACK DIVORCE LAWYER I've had this office for 25 years.
BLACK DIVORCE LAWYER I'm a divorce attorney.
SYDNEY PROSSER You lost two million dollars of taxpayer money because you were confused about the location and the identity of Victor Tellegio's attorney?
Where we first saw Irving at the pool party.
IRVING ROSENFELD (V.O.) The role of Tellegio's attorney, Alfonse Simone, was played by our friend Ed Malone --
Camera pans from Irving to Ed Malone:
IRVING ROSENFELD (V.O.) the "Cold Cut King of Long Island"--
Ed Malone holds up two packages of cold cuts.
Also holding the cold cuts are the two that frisked everyone at Simone's office.
IRVING ROSENFELD (V.O.) Whose party we were at when Sydney and I first met.
Cut to Irving first meeting Sydney.
Ed Malone, dressed as Alfonse Simone, steps to camera to shake Richie's hand.
ED MALONE Alfonse Simone.
EDITH GREENSLY People believe what they want to believe Richie.
RICHIE DIMASO That's because you conned me!
RICHIE DIMASO You both fucking conned me.
RICHIE DIMASO You both got under me.
RICHIE DIMASO You did!
IRVING ROSENFELD Well that doesn't sound so good, either.
IRVING ROSENFELD I mean -- and I don't know what you're talking about, but -- let's just assume you want to go with that story.
IRVING ROSENFELD Really?
IRVING ROSENFELD That's the story you want to go with?
IRVING ROSENFELD That's what you want the New York Times to hear?
IRVING ROSENFELD That you got conned by the very con men who you forced to entrap the members of Congress in the first place.
IRVING ROSENFELD That's what you want to go with?
IRVING ROSENFELD That doesn't sound so good for your whole thing.
Richie looks like he's going to be sick.
IRVING ROSENFELD (CONT'D) And how ironic that the most creative minds, the ones who are working hardest to get the economy of New Jersey going, those are the ones that you round up.
IRVING ROSENFELD (CONT'D) And why?
IRVING ROSENFELD (CONT'D) Because what, they're the easiest to go after?
IRVING ROSENFELD (CONT'D) And what about the real bullshit artists?
IRVING ROSENFELD (CONT'D) You didn't even come close to the big leagues.
IRVING ROSENFELD (CONT'D) Those big guys.
IRVING ROSENFELD (CONT'D) The money men.
RICHIE DIMASO That's what I was trying to go after.
IRVING ROSENFELD I'm sorry to tell you, you got none of 'em.
STODDARD THORSEN You know, Richard, I think we may call you as a witness, but otherwise you're done.
STODDARD THORSEN I think you better go home.
Richie disoriented, appeals to Stoddard.
RICHIE DIMASO Stoddard --
STODDARD THORSEN Go on home, Richard.
ELO's "10538 Overture" reprises on the soundtrack.
Camera tilts down from the Federal Building to find Richie coming down the stairs, emotional.
Richie walks wiping his eyes, his innocence and Edith, lost.
IRVING ROSENFELD (V.O.) We took down some very big guys.
IRVING ROSENFELD (V.O.) Some of whom were just doing business as usual helping their communities or their states.
IRVING ROSENFELD (V.O.) But some of them knew they had larceny in their blood--
IRVING ROSENFELD (V.O.) And they even admitted it.
IRVING ROSENFELD (V.O.) GREY HAIRED SENATOR HORTON MITCHELL, wife by his side, denies any wrongdoing and is photographed and humiliated as he then sits with her in a Federal car.
IRVING ROSENFELD (V.O.) But in all it was six Congressmen, one United States Senator, and my friend, Carmine Polito.
IRVING ROSENFELD (V.O.) We gave the two million back so Carmine got the reduced sentence.
IRVING ROSENFELD (V.O.) 18 months.
IRVING ROSENFELD (V.O.) The loss of his friendship would haunt me for the rest of my life.
IRVING ROSENFELD (V.O.) And when the story was written, Richard Dimaso's name was never mentioned.
IRVING ROSENFELD (V.O.) Syd and I moved in together.
IRVING ROSENFELD (V.O.) And Rosalyn --
IRVING ROSENFELD (V.O.) ROSALYN IN A NECK BRACE and off white trench coat and sunglasses -
ROSALYN ROSENFELD The car is a little dinged up and I'm a little stiff but I don't want to talk about it.
Irving stares at Rosalyn.
IRVING ROSENFELD (V.O.) She would always be interesting.
Rosalyn gets in to a car, revealing Pete Musane in the driver's seat.
Irving leans in.
PETE MUSANE You know my boss knows you did him a solid.
IRVING ROSENFELD Yes I did.
IRVING ROSENFELD He never took a nickle so they can't get him for nothing.
IRVING ROSENFELD I was never going to let that happen.
Irving starts to leave --
ROSALYN ROSENFELD Irv.
He stops and looks at her.
With red lacquered nails Rosalyn places her favorite nail finish in his hand.
ROSALYN ROSENFELD (CONT'D) I'm done with this nail finish.
ROSALYN ROSENFELD (CONT'D) Bye for now.
ROSALYN ROSENFELD (CONT'D) I'll see you next weekend.
Irving nods.
Rosalyn drives off with Pete.
Sydney stands with Danny.
IRVING ROSENFELD (V.O.) Our conning days were behind us.
Irving and Sydney walk hand and hand with Danny down the street.
Irv drops the nail finish into a trashcan.
IRVING ROSENFELD (V.O.) You can fool yourself for just so long and then your next reinvention better have your damn feet on the ground.
Irving and Sydney admire a piece of art on the wall.
IRVING ROSENFELD (V.O.) We got a loan from a bank and were able to go gallery legitimate.
INT. SMALL BANK - DAY Irving and Sydney sit in front of a banker asking for a loan.
IRVING ROSENFELD (V.O.) The art of survival is a story that never ends.
SYDNEY PLACES THE NEEDLE ON THE RECORD PLAYING ON A TURNTABLE: DUKE ELLINGTON'S JEEPS BLUES, begins.
SYDNEY PLACES THE NEEDLE ON THE RECORD PLAYING ON A SHE STARES
</pre><br> <table width="85%" border="0" align="center" cellpadding="5" cellspacing="0" class="body" style="BORDER-TOP: #000000 1px solid; BORDER-RIGHT: #000000 1px solid; BORDER-LEFT: #000000 1px solid; BORDER-BOTTOM: #000000 1px solid;">
